### ISSUE TITLE
@types/angularjs ng.auto. instead of auto.

### ISSUE THREAD

**Issue by pocesar** [DefinitelyTyped/DefinitelyTyped#10000]
When I went to see the angularjs typings in vscode, the `ng.auto.IInjectorService` on line 173 was red. there's no ng that can be used that way inside the module declaration.

**Comment by mhegazy** [comment]
@types/angularjs is deprecated. use `@types\angular` instead.

**Comment by mhegazy** [comment]
just published deprecation notice to the 1.5.14-alpha
