### ISSUE TITLE
React-router-redux Definition File

### ISSUE THREAD

**Issue by mbeauchamp7** [DefinitelyTyped/DefinitelyTyped#10012]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react-router-redux/react-router-redux.d.ts#L23-L24

As I was using the push method from react-router-redux, 

```
type LocationDescriptor = H.Location | H.Path;
type PushAction = (nextLocation: LocationDescriptor) => RouterAction;
```

I found that it uses the Location from HistoryModule which looks like this

```
    type Location = {
        pathname: Pathname
        search: Search
        query: Query
        state: LocationState
        action: Action
        key: LocationKey
        hash: Hash
        basename?: string
    }
```

Usually when I use react-router's push method, it uses  LocationDescriptorObject which looks like this

```
    type LocationDescriptorObject = {
        pathname?: Pathname
        search?: Search
        query?: Query
        state?: LocationState
    }
```

I think it should be LocationDescriptorObject because of the optional params compared to the Location type that are all required, except basename.

Maybe do it like this?

```
type LocationDescriptor = H.LocationDescriptor;
type PushAction = (nextLocation: LocationDescriptor) => RouterAction;
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.
