### ISSUE TITLE
@types/bluebird 2.0.26-alpha is broken

### ISSUE THREAD

**Issue by pocesar** [DefinitelyTyped/DefinitelyTyped#10017]
![bluebird](https://cloud.githubusercontent.com/assets/461084/16677590/e8806d90-44ad-11e6-9d5a-1627f259f4e4.png)

Other than that, I can't pinpoint why the error is appearing. Using `tsd` was working

**Comment by mhegazy** [comment]
Should be fixed in `@types/bluebird@2.0.27-alpha`
