### ISSUE TITLE
@types/cors missing preflightContinue option

### ISSUE THREAD

**Issue by yeiniel** [DefinitelyTyped/DefinitelyTyped#10026]
The cors expressjs middleware support preflightContinue [configuration option](https://github.com/expressjs/cors#configuration-options). But it is missing in @types/cors.

**Comment by mhegazy** [comment]
should be available in @types/cors once ported to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0

**Comment by yeiniel** [comment]
Thanks again. I think that types-2.0 is a great improvement over the current state of things. Have a good day.

**Comment by mhegazy** [comment]
should be available now under `@types/cors@0.0.30`
