### ISSUE TITLE
No typings for Smartfox

### ISSUE THREAD

**Issue by otolol** [DefinitelyTyped/DefinitelyTyped#10024]
Is it possible to add typings for  [SmarFox HTML5 client API](http://docs2x.smartfoxserver.com/api-docs/jsdoc/) ?

**Comment by ChanceM** [comment]
@otolol I think I will try and take this on as a learning side-project. Would you be able to help write test code for the definition files?

**Comment by otolol** [comment]
@ChanceM no problem. My problem was that I have minified version of Smartfox.

**Comment by ChanceM** [comment]
@otolol Great I'm just shy of half way through it I will push it to a feature branch on my fork when I get a chance.

**Comment by ChanceM** [comment]
@otolol I have pushed the definitions to feature/smart-fox-server. Take a look and see if you want to contribute any test code. Other wise I will submit a PR.
https://github.com/ChanceM/DefinitelyTyped/tree/45fcc262f792ada981c8d022fea4d3ad87ad6e9d/smart-fox-server

**Comment by ChanceM** [comment]
@hecool108 Would you be able to test out this definition. I know you were looking for this a few months ago.

**Comment by otolol** [comment]
@ChanceM  yes I can it. I''make it when I'll have free time.

**Comment by otolol** [comment]
@ChanceM I think everything is ok.

**Comment by ChanceM** [comment]
@otolol Thank you for checking it out. 

I have been pushing a few fixes to that branch as I go. I am adding JSDOCs for everything right now. Once that's done I will submit a PR.

**Comment by hecool108** [comment]
@ChanceM , Is there anything that I can do to help? I'd updated my definition file in my project, but it's still a minimize version for my need. If you need I can push it to my Github

**Comment by ChanceM** [comment]
@hecool108 I took a look at your definition file while putting mine together. If want you could try my definition file and see if any errors show up that  shouldn't.
