### ISSUE TITLE
node.d.ts(11458,205): error TS*** : tons of them

### ISSUE THREAD

**Issue by XiaoWanLINJU** [DefinitelyTyped/DefinitelyTyped#10039]
- [ ] I tried using the https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e5de5c4daf8cdc33ed60704cd6e8021c99a89f92/node/node.d.ts

here is the config of environment:
C:\Users\XiaoWanLI>tsc -v
Version 1.8.10

C:\Users\XiaoWanLI>npm -v
2.15.8

C:\Users\XiaoWanLI>node -v
v4.4.7

C:\Users\XiaoWanLI>tsd --version

> > tsd 0.6.5

I got following errors when I use ctrl + b to compile:
...
node.d.ts(11597,23): error TS1005: ';' expected.
node.d.ts(11597,31): error TS1005: ';' expected.
node.d.ts(11597,36): error TS1005: '{' expected.
node.d.ts(11597,57): error TS1005: ';' expected.
node.d.ts(11597,69): error TS1005: ';' expected.
node.d.ts(11597,83): error TS1005: ';' expected.
node.d.ts(11597,103): error TS1005: ';' expected.
node.d.ts(11597,120): error TS1005: '>' expected.
node.d.ts(11597,121): error TS1005: ';' expected.
node.d.ts(11597,235): error TS1110: Type expected.
node.d.ts(11598,6): error TS1110: Type expected.
node.d.ts(11598,7): error TS1161: Unterminated regular expression literal.
node.d.ts(11599,5): error TS1161: Unterminated regular expression literal.
node.d.ts(11600,3): error TS1161: Unterminated regular expression literal.
node.d.ts(11602,5): error TS1161: Unterminated regular expression literal.
node.d.ts(11603,3): error TS1161: Unterminated regular expression literal.
[Finished in 8.5s with exit code 2]
[cmd: ['node', 'C:\Users\XiaoWanLI\AppData\Roaming\Sublime Text 3\Packages\TypeScript\tsserver\tsc.js', '-p', 'E:/myPython/playground-master-google/playground-master']]
[dir: E:\myPython\playground-master-google\playground-master]
[path: C:\ProgramData\Oracle\Java\javapath;D:\Program Files\python27\Lib\site-packages\PyQt4;C:\Program Files (x86)\Common Files\NetSarang;D:\Program Files\Perl64\site\bin;D:\Program Files\Perl64\bin;C:\Python27\Lib\site-packages\PyQt4;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseGit\bin;C:\Python27\Lib\site-packages\vtk;C:\Python27\gnuplot\binary;C:\Python27\Lib\site-packages\osgeo;D:\Program Files\MATLAB\R2014b\runtime\win64;D:\Program Files\MATLAB\R2014b\bin;D:\Program Files\MATLAB\R2014b\polyspace\bin;D:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\pythonxy\SciTE-3.3.2-3;C:\pythonxy\console;C:\Python27;C:\Python27\DLLs;C:\Python27\Scripts;D:\Program Files\python27\Lib\site-packages\vtk;D:\Program Files\python27\gnuplot\binary;D:\Program Files\python27\Lib\site-packages\osgeo;C:\Python27\SciTE-3.3.2-3;C:\Python27\console;C:\MinGW32-xy\bin;C:\Program Files (x86)\pythonxy\swig;C:\Python27\gettext\bin;D:\Program Files\python27\Lib\site-packages;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\UltraEdit;D:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;D:\Program Files\nodejs\;C:\Users\XiaoWanLI\AppData\Roaming\npm]

I am new in TS, please help~~

**Comment by XiaoWanLINJU** [comment]
import fs = require('fs');

export function classifyfiledata():
    Example2D[] {
  let points: Example2D[] = [];
  let input = fs.createReadStream('run2\\reduced2D.txt');

this is the code use the node.d.ts

**Comment by vvakame** [comment]
please try node.d.ts in master/HEAD

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
