### ISSUE TITLE
protobufjs.d.ts: error TS2304: Cannot find name 'Buffer'

### ISSUE THREAD

**Issue by screenpunch** [DefinitelyTyped/DefinitelyTyped#10044]
I tried using the latest `protobufjs.d.ts` file in this repo and had problems.

`error TS2304: Cannot find name 'Buffer'.`

I have bytebuffer.d.ts installed, but it doesn't export Buffer?

- The authors of that type definition are cc/ @vvakame , @panuhorsmalahti , @johnnyreilly @drpro

**Comment by panuhorsmalahti** [comment]
I think it comes from here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/node.d.ts#L88

**Comment by jagannathTL** [comment]
stuck in same issue 

[11:50:56]  typescript: node_modules/protobufjs/index.d.ts, line: 1346
            Cannot find name 'Buffer'.

    L1346:  constructor(buffer: Buffer);

[11:50:56]  transpile failed

**Comment by panuhorsmalahti** [comment]
Do you have node.d.ts included?
