### ISSUE TITLE
react-native: should ViewProperties be included by other components?

### ISSUE THREAD

**Issue by jokester** [DefinitelyTyped/DefinitelyTyped#10053]
Some react-native components includes `View.propTypes` in their own props, as in [this code](https://github.com/facebook/react-native/blob/master/Libraries/Components/ToolbarAndroid/ToolbarAndroid.android.js#L72).
It seems to me that `react-native.d.ts` does have such properties.

Can [this](https://github.com/jokester/DefinitelyTyped/commit/4f618cdbd046df09bd9193cd41f8b0ced4aca299) can be a fix?

cc @andyshuxin @bgrieder

**Comment by bgrieder** [comment]
By converting an `interface` to a `type` alias we are going to loose the ability to further use it in an `extend` clause.

Did I miss something or can't we jus do 

    export interface ToolbarAndroidProperties extends React.Props<ToolbarAndroidStatic>, ViewProperties {
        ...
    }

**Comment by jokester** [comment]
@bgrieder Thanks for the response. I found that the `extend` way actually works if conflicted propertiy `ref` is resolved (see [this code](https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...jokester:try-rn-include-viewprops-2)).

Without the `ref: `, tsc would complain 

    error TS2320: Interface 'ToolbarAndroidProperties' cannot simultaneously extend types 'Props<ToolbarAndroidStatic>' and 'ViewProperties'.
      Named property 'ref' of types 'Props<ToolbarAndroidStatic>' and 'ViewProperties' are not identical.

**Comment by bgrieder** [comment]
>I found that the extend way actually works if conflicted propertiy ref is resolved (see this code).

IMHO this sounds like a reasonable solution, preferable to creating `types`s

**Comment by jokester** [comment]
Agreed. I'm going to start with the components that included `...View.propTypes`.
