### ISSUE TITLE
Support TypeScript 2.0

### ISSUE THREAD

**Issue by use-strict** [DefinitelyTyped/DefinitelyTyped#10072]
TypeScript 2.0 beta is up on npm. @vvakame, @basarat  , I'll want to update some typings for jQuery but I need tsc 2.0 support first. Do you know what exactly has to be done for this to work?

A big problem also is about breaking changes. Function 'this' types, in conjunction with 'noImplicitThis', will lead to definitions that will be incompatible with older compiler versions. There are probably other backwards-incompatible changes, like patterns in module declarations.

**Comment by mhegazy** [comment]
The TS-2.0 specific declarations are in types-2.0 branch. feel free to send PRs against that branch. also worth noting that this branch is where the `@types` packages get published from.

We intend to merge the types-2.0 branch into master a few weeks after the final TS 2.0 release.

**Comment by use-strict** [comment]
Great, thanks. I'll have a go at it tomorrow.

**Comment by use-strict** [comment]
Looks like that branch is using tsc 1.8 as well.

**Comment by use-strict** [comment]
@mhegazy , looks like the `npm-shrinkwrap.json` file is not consistent with `package.json`. It should be regenerated.

**Comment by use-strict** [comment]
Removed devDependencies from shrinkwrap. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10092

**Comment by jleider** [comment]
This would be great to get merged into the types-2.0 branch.

**Comment by e-cloud** [comment]
@mhegazy , there have been more than a few weeks from July. Is there a clear plan to merge `types 2.0` into `master`?

**Comment by zakdances** [comment]
I'm unclear on this too - at this time, which branch should we be PR'ing?

**Comment by screendriver** [comment]
Quote from the [docs](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request)

> New work should generally be done on the types-2.0 branch. If you want your changes to be available to typings users, then you may edit master instead.

**Comment by vvakame** [comment]
It landed to master branch already. 😉

**Comment by e-cloud** [comment]
So, should we now all commit PR on master rather than types-2.0?

**Comment by vvakame** [comment]
@e-cloud I understand so. @DefinitelyTyped/contributors is this rights?
