### ISSUE TITLE
Invalid 'reference' directive syntax

### ISSUE THREAD

**Issue by sanex3339** [DefinitelyTyped/DefinitelyTyped#10097]
I want to make PR to types-2.0 branch which change `commander` definitions.

When i run `npm test` i got an error

```
commander/index.d.ts(6,1): error TS1084: Invalid 'reference' directive syntax.
```

```
/// <reference types="node" />
```

How can i fix that?

**Comment by mhegazy** [comment]
Use `typescript@2.0.0` or later to build.

**Comment by nicojs** [comment]
Solved it for me. 
@sanex3339 can you close this issue if your problem is fixed as well?

**Comment by gracefdssi** [comment]
I'm using typescrpit version 2.7, and I still encounter this error for the following:

`/// <reference types="angular" />`

**Comment by q640202047** [comment]
`
ERROR in [default] xxx/node_modules/metismenu/types/metismenu.d.ts:6:0
Invalid 'reference' directive syntax.

ERROR in [default] xxx/metismenu/types/metismenu.d.ts:24:55
Cannot find name 'JQueryEventObject'.

ERROR in [default] xxx/src/vendor.browser.ts:4:7
Exported external package typings file 'xxx/node_modules/metismenu/types/metismenu.d.ts' is not a module. Please contact the package author to update the package definition.
`
I met this problem, too.
And my typescrpit is Version 2.9.1.

**Comment by tahabouhali** [comment]
zab fikom

**Comment by malu-mn** [comment]
Getting the same exception. 

> ERROR in node_modules/@types/pdfjs-dist/index.d.ts(7,1): error TS1084: Invalid 'reference' directive 

syntax
Type script version:
`"typescript": "2.8.3"`

Any help to solve this is highly appreciated.

**Comment by daode** [comment]
Th

> Getting the same exception.
> 
> > ERROR in node_modules/@types/pdfjs-dist/index.d.ts(7,1): error TS1084: Invalid 'reference' directive
> 
> syntax
> Type script version:
> `"typescript": "2.8.3"`
> 
> Any help to solve this is highly appreciated.

The same error too... help please...

**Comment by mgpathi** [comment]
Eating my time with this 
ERROR in node_modules/@types/pdfjs-dist/index.d.ts(7,1): error TS1084: Invalid 'reference' directive syntax.
current typescript version: 2.4.2

after upgrading to typescript v 3.1.6
Could not find local "typescript" package.The "@ngtools/webpack" package requires a local "typescript@^2.0.2" package to be installed.Error

***Your help is most precious.

**Comment by mariliasoares** [comment]
Having the same error here. :( nothing yet?
Error Typescript Error
Invalid 'reference' directive syntax.
node_modules/@types/pdfjs-dist/index.d.ts

Typescript Error
Type 'CustomEvent' is not generic.
node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts

current typescript version: 2.6.2

**Comment by malu-mn** [comment]
> Getting the same exception.
> 
> > ERROR in node_modules/@types/pdfjs-dist/index.d.ts(7,1): error TS1084: Invalid 'reference' directive
> 
> syntax
> Type script version:
> `"typescript": "2.8.3"`
> 
> Any help to solve this is highly appreciated.
Issue solved by updating typescript version to 
` "typescript": "3.5.1"`

**Comment by prasanna2402** [comment]
node_modules/@types/pdfjs-dist/index.d.ts(7,1): error TS1084: Invalid 'reference' directive syntax

Tried various typescript version.....but in vain. Please help

**Comment by javierjsv** [comment]
> ¿Cómo puedo arreglar eso?
/// <reference types="angular" />

> solición
en el node_modules\@types\pdfjs-dist\index.d.ts

linea 7 
/// <reference lib="dom"/>

/// <reference types="angular" />
cambiar por 
// <reference lib="dom"/>
///<reference types="angular" />

**Comment by sagaraher** [comment]
I have same issue and version
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10097#issuecomment-499862328

**Comment by BL-AniketChile** [comment]
I had the same issue as https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10097#issuecomment-499826179

Temporary solution for this 
Remove one **`/`** from **`///`** on line number 7 in file **`node_modules/@types/pdfjs-dist/index.d.ts`**

Hope this issue is solved ASAP!!!

**Comment by daode** [comment]
> I had the same issue as [#10097 (comment)](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10097#issuecomment-499826179)
> 
> Temporary solution for this
> Remove one **`/`** from **`///`** on line number 7 in file **`node_modules/@types/pdfjs-dist/index.d.ts`**
> 
> Hope this issue is solved ASAP!!!

I confirm that works. Thanks

An other solution is to use the verision  "typescript": "3.5.1" and not other :(

the modification is to do in package.json file in the bloc: "devDependencies": {}

**Comment by nicojs** [comment]
Removing a slash from the triple slash makes it a normal comment. Just remove it in that case. If you can still compile, it probably wasn't needed anymore.

**Comment by giovannyreyeso** [comment]
> > I had the same issue as [#10097 (comment)](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10097#issuecomment-499826179)
> > Temporary solution for this
> > Remove one **`/`** from **`///`** on line number 7 in file **`node_modules/@types/pdfjs-dist/index.d.ts`**
> > Hope this issue is solved ASAP!!!
> 
> I confirm that works. Thanks
> 
> An other solution is to use the verision "typescript": "3.5.1" and not other :(
> 
> the modification is to do in package.json file in the bloc: "devDependencies": {}

Confirm resolve using "typescript": "3.5.1".

**Comment by mingGitHub** [comment]
use command "npm i typescript@3.5.1"

**Comment by tresloukadu** [comment]
> use command "npm i typescript@3.5.1"

Best solution so you don't need to change your package.json, Especially if you are using version control.

**Comment by EstelleLM-13** [comment]
I 've had the same issue and updating to typescript 3.5.1 was not an option. 
What I've done is using the version for pdfjs-dist that match with my typescript version and so the matching version for ng2-pdf-viewer. 
Here are the different version I used : 
Typescript @2.7.2
ng2-pdf-viewer @5.2.4
@types/pdfjs-dist @0.1.2

**Comment by kumarrrr** [comment]
Removal of one  / from /// at line no 7 works
my ts was 2.7.2

**Comment by xmarkclx** [comment]
Hey guys!

This worked for me:
```
npm i pdfjs-dist@2.0.943 --save
```

This is due to on my end, 

```bash
💬-> npm ls typescript
├─┬ @ionic/app-scripts@3.2.0
│ └─┬ @angular-devkit/build-optimizer@0.0.35
│   └── typescript@2.6.2 
```

Typescript is forced to 2.6.2 max due to the dependencies as shown.

You may have different issues depending on your `npm ls typescript` adventure.

**Comment by allisonjulioo** [comment]
> Hey guys!
> 
> This worked for me:
> 
> ```
> npm i pdfjs-dist@2.0.943 --save
> npm i ng2-pdf-viewer@5.2.3 --save
> ```
> 
> This is due to on my end,
> 
> ```shell
> 💬-> npm ls typescript
> ├─┬ @ionic/app-scripts@3.2.0
> │ └─┬ @angular-devkit/build-optimizer@0.0.35
> │   └── typescript@2.6.2 
> ```
> 
> Typescript is forced to 2.6.2 max due to the dependencies as shown.
> 
> You may have different issues depending on your `npm ls typescript` adventure.
> 
> Don't forget to restart `ionic serve` or something similar.

It's worked for me too. Thanks!!!

**Comment by josuesamano** [comment]
I modified any line in index.d.ts file, save my changes, and compile, my change was a space

**Comment by dunirvana** [comment]
> use command "npm i typescript@3.5.1"

Worked for me

**Comment by shubham8484** [comment]
use "npm i typescript@2.7.1" |
Worked for mee

**Comment by svenmuellerssen** [comment]
I had the same issue while building package "nest-schedule/0.6.4".
Installing typescript v3 with `npm install typescript@3.5.1` solved it.

Thanks a lot for that help here.

**Comment by yashshaha** [comment]
> > I had the same issue as [#10097 (comment)](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10097#issuecomment-499826179)
> > Temporary solution for this
> > Remove one **`/`** from **`///`** on line number 7 in file **`node_modules/@types/pdfjs-dist/index.d.ts`**
> > Hope this issue is solved ASAP!!!
> 
> I confirm that works. Thanks
> 
> An other solution is to use the verision "typescript": "3.5.1" and not other :(
> 
> the modification is to do in package.json file in the bloc: "devDependencies": {}

> Removing extra '/' helps to remove error : "Invalid 'reference' directive syntax.  webpack : Failed to Compile." 
 Thank you.

**Comment by Mirmae7** [comment]
Changing the package.json typescript version from : "typescript": "^2.9.2" -> "typescript": "3.5.1" solved it for me, thanks a lot !
Been tough knowing this was the reason behind webpack not copying the static files under assets inside my jar and causing the front side to be down.
