### ISSUE TITLE
@types/commander and ICommand interface

### ISSUE THREAD

**Issue by sanex3339** [DefinitelyTyped/DefinitelyTyped#10093]
While current version of commander.d.ts allows to use ICommand interface in project, 

```ts
import { Command } from 'commander';

/**
 * @type {commander.ICommand}
 */
private commands: commander.ICommand;

this.commands = new Command();
```

new @types version is not.

```ts
import { Command } from 'commander';

/**
 * @type {commander.ICommand}
 */
private commands: commander.ICommand; // cannot found `commander` namespace

this.commands = new Command();
```

**Comment by mhegazy** [comment]
Fixed in #10172. should be published shortly to npm.

**Comment by sanex3339** [comment]
thank you

**Comment by flying-sheep** [comment]
it’s not fixed though?

```ts
import * as commander from 'commander'

commander.Command
^^^Cannot find namespace 'commander'
```

**Comment by Introvertuous** [comment]
Why is there an export statement at the end of the definitions file that just exports a declared var? Commenting that out fixed this issue for me.

**Comment by Introvertuous** [comment]
I am not sure what is going on here:

```
declare var command: commander.Command & commander.Option & { [key: string]: any };
export = command;
```

Can we not just export this namespace as a module instead? Worked for me.

**Comment by Introvertuous** [comment]
I can open a PR for this if needed.

**Comment by flying-sheep** [comment]
would probably be for the best:

```ts
declare namespace command {
    ....
}

declare const command: commander.Command & commander.Option & { [key: string]: any };
export = command;
```

**Comment by Introvertuous** [comment]
But what is the point of exporting that variable? Here is the equivalent using the class export:
index.d.ts:
```
declare module 'commander' {
    // ....
}
```

index.ts
```
import { Command } from 'commander'
const program: Command = new Command()
// ...
program.parse([]);
```

**Comment by flying-sheep** [comment]
Because that's not how the commander module works?

module.exports is assigned to an object that is modified by calling methods in it. There's nothing else exported. (E.g. no Command class)

In order to be able to use the interfaces we need to treat it as a [module function](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-function-d-ts.html), even though the only things it exports apart from that one object are interfaces.
