### ISSUE TITLE
React native Binding element 'any' implicitly has an 'any' type

### ISSUE THREAD

**Issue by wallverb** [DefinitelyTyped/DefinitelyTyped#10108]
This part is failing in TypeScript 2.0

```
    export interface PlatformStatic {
        OS: PlatformOSType,

        // only documented in PlatformSpecificInformation.md
        select({PlatformOSType: any}): any
    }
```

with error: Binding element 'any' implicitly has an 'any' type

Seems like the issue is exactly as described in here: https://github.com/Microsoft/TypeScript/issues/9657#event-721064694

Should be `select({PlatformOSType}:{PlatformOSType: any}): any`

**Comment by vvakame** [comment]
please send a pull request. I'll review it.
