### ISSUE TITLE
@types/node cannot find name 'xxx'

### ISSUE THREAD

**Issue by sanex3339** [DefinitelyTyped/DefinitelyTyped#10113]
- [x] I tried using the types-2.0 `node/index.d.ts` file in this repo and had problems.

After installing @types/node i got multiple errors:

```
(1,21): error TS2307: Cannot find module 'fs'.
(3,23): error TS2307: Cannot find module 'path'.
(80,41): error TS2304: Cannot find name 'process'.
(5,12): error TS2304: Cannot find name 'global'.
(6,5): error TS2304: Cannot find name 'require'.
```

On master branch version of node definitions everything is ok.

For example for `fs` module i have import like 
```ts
import * as fs from 'fs';
```

For `require` and `global` i have no imports.

**Comment by mhegazy** [comment]
Can you share your project setup? what version of the compiler are you using?

**Comment by sanex3339** [comment]
2.0.0-beta compiler.

project: https://github.com/sanex3339/javascript-obfuscator/tree/dev

project tsconfig:
```json
{
  "compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noUnusedLocals": true
  }
}
```

entry point
```ts
"use strict";

import { JavaScriptObfuscator } from './src/JavaScriptObfuscator';

if (!(<any>global)._babelPolyfill) {
    require('babel-polyfill');
}

module.exports = JavaScriptObfuscator;
```

**Comment by mhegazy** [comment]
I just cloned https://github.com/sanex3339/javascript-obfuscator/tree/dev, installed `@types\node` and ran `tsc` at the root. got multiple duplicate declaration errors, removed `typings\global\node\index.d.ts`, and now it is compiling just file.

**Comment by sanex3339** [comment]
mmm, there no typings\global\node\index.d.ts in repository
https://github.com/sanex3339/javascript-obfuscator/tree/dev/typings/globals

**Comment by mhegazy** [comment]
```txt
c:\test\10113\javascript-obfuscator>git branch
* dev
  master

c:\test\10113\javascript-obfuscator>tsc --v
Version 2.0.0

c:\test\10113\javascript-obfuscator>ls node_modules\@types\
[.]       [..]      [chai]    [chance]  [esprima] [estree]  [joi]     [mkdirp]  [mocha]   [node]    [sinon]

c:\test\10113\javascript-obfuscator>tsc

c:\test\10113\javascript-obfuscator>echo %ERRORLEVEL%
0
```

**Comment by sanex3339** [comment]
try `npm run watch` it run webpack task

**Comment by mhegazy** [comment]
```cmd
c:\test\10113\javascript-obfuscator>npm run watch

> javascript-obfuscator@0.7.0-dev.0 watch c:\test\10113\javascript-obfuscator
> scripts/watch

'scripts' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mhegazy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! javascript-obfuscator@0.7.0-dev.0 watch: `scripts/watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the javascript-obfuscator@0.7.0-dev.0 watch script 'scripts/watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the javascript-obfuscator package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs javascript-obfuscator
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls javascript-obfuscator
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\test\10113\javascript-obfuscator\npm-debug.log
```

**Comment by mhegazy** [comment]
It will be easier for both of us if you can narrow down the isssue to a call to tsc. if it is through the webpack ts loader, then i will not be the best person to help there. maybe @johnnyreilly or @jbrantly can help here.

**Comment by sanex3339** [comment]
hmm, i add 
```json
"types": [
    "node"
]
```

and now everything is ok

**Comment by mhegazy** [comment]
you should not need to add the `types` property, the behavior should be the same with or without it. so looks like a loader issue to me. this is a new feature in TS 2.0, so it is possible that the loader is not returning the expect result to the API.

**Comment by sanex3339** [comment]
ok, i create a related issue for `ts-loader`

**Comment by blakeembrey** [comment]
@mhegazy What is the expected result for the API?

**Comment by mhegazy** [comment]
assuming that the missing API is [`getDirectories`](https://github.com/Microsoft/TypeScript/blob/767da71cc13422c65a6369e26c3a6cfe894a05ef/src/compiler/types.ts#L2918), then the result should be the list of directories under the given path, see default implementation in https://github.com/Microsoft/TypeScript/blob/767da71cc13422c65a6369e26c3a6cfe894a05ef/src/compiler/program.ts#L982

it is also possible that there is a bug in the TS API that is causing this to happen.

**Comment by blakeembrey** [comment]
Awesome, thanks. I'll be sure to pull that into `ts-loader` and `ts-node` when I have a chance (or this'll still be valuable info for anyone else who beats me to it).
