### ISSUE TITLE
$.when definition expects common result interface

### ISSUE THREAD

**Issue by dneimke** [DefinitelyTyped/DefinitelyTyped#10159]
- [Y ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ Y] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ Y] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ Y] I want to talk about `DefinitelyTyped/jquery.d.ts`.
  - The authors of that type definition are cc/ @borisyankov, @choffmeister, @Steve-Fenton 

I have a $.when in the following file which resolves 3 different promise types:

http://embed.plnkr.co/IfFpZuYLJkL4GkbSdoe7/

The Typescript Definition seems to expect that all Result arguments implement a common interface?  

![image](https://cloud.githubusercontent.com/assets/720792/16904692/aa673924-4cd9-11e6-9775-7953dce1ed4d.png)

Is there any way around this?

**Comment by dneimke** [comment]
I think that the solution might be to change the signature of when from this:

`when<T>(...deferreds: Array<T | JQueryPromise<T>/* as JQueryDeferred<T> */>): JQueryPromise<T>;`

To this...

`when<T>(deferred?: T | T[], ...deferreds: Array<any| JQueryDeferred<any>/* as JQueryDeferred<T> */>): JQueryPromise<T>;`

**Comment by dneimke** [comment]
I think the answer is to write more specific overloads for $.when.  For example:

```
class JQueryStatic {

    when<T1>(value1: T1 | JQueryPromise<T1>): JQueryPromise<T1>;
    when<T1,T2>(value1: T1 | JQueryPromise<T1>, value2: T2 | JQueryPromisee<T2>): JQueryPromise<[T1,T2]>;
    when<T1,T2>(value1: T1 | JQueryPromise<T1>, value2: T2 | JQueryPromise<T2>): JQueryPromise<[T1,T2]>;
    
}
```

**Comment by vvakame** [comment]
cc/ @johnnyreilly
