### ISSUE TITLE
react-addons-test-utils: "Generic type 'DOMAttributes<T>' requires 1 type argument(s)."

### ISSUE THREAD

**Issue by donaldpipowitch** [DefinitelyTyped/DefinitelyTyped#10162]
Using `"@types/react-addons-test-utils": "^0.14.13"` (and `"@types/react": "^0.14.27"`, "@types/react-dom": "^0.14.13") with `typescript@beta`:

Error:

```
ERROR in /Users/foo/examples/node_modules/@types/react-addons-test-utils/index.d.ts
(129,47): error TS2314: Generic type 'DOMAttributes<T>' requires 1 type argument(s).
```

Code:

```
export function isElementOfType<P extends DOMAttributes, T extends Element>(
        element: ReactElement<any>, type: string): element is DOMElement<P, T>;
```

It can be fixed if you write something like `DOMAttributes<P>` or `DOMAttributes<{}>`, but I don't know which should be correct.

**Comment by mhegazy** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/commit/9d7d5a209af31672a77f7a59bddcb8088ccc919f

**Comment by donaldpipowitch** [comment]
Thanks.
