### ISSUE TITLE
React typings bar use of this.props.children

### ISSUE THREAD

**Issue by mcclure** [DefinitelyTyped/DefinitelyTyped#10174]
I run

```
tsd install --save react-dom
```

to get React. It installs, according to tsd.json, `6eebd5e90a1cbd6b47b0705ba72dbcd5baf846f3`. I create a tsconfig.json

```
{ "compilerOptions": { "module": "commonjs", "outDir": "build", "jsx": "react"},
"files": [ "test.tsx", "typings/tsd.d.ts" ] }
```

And a sample program:

```
/// <reference path="typings/tsd.d.ts" />

class LinkProps {
    title: string
}

class Link extends React.Component<LinkProps, {}> {
    render() {
        return <a href="/" title={this.props.title}>
            {this.props.children}
        </a>
    }
}

let x = <Link title="test">Test one two</Link>
```

I run `tsc` and:

```
test.tsx(5,34): error TS2339: Property 'children' does not exist on type '{}'.
```

`this.props.children` is the [documented way](https://facebook.github.io/react/tips/children-props-type.html) of accessing the child nodes of a React component. Similarly, the above is the documented way of creating a custom Props ES6 class with (create a standard class with no parents). My expected behavior is that if I'm following the directions, I should be able to access `this.props.children`. However, since `this.props` is a `LinkProps`, it has no children field.

This doesn't work:

```
class LinkProps {
    title: string
    children: JSX.Element[]
}
```

...because then it expects me to provide "children" as an attribute on the `<Link />`.

```
test.tsx(16,28): error TS2322: Type 'string' is not assignable to type 'Element[]'.
```

This **does** work, but it's very silly:

```
render() {
        return <a href="/" title={this.props.title}>
            {(this.props as any).children}
        </a>
    }
```

There should be some solution to this that doesn't require resorting to `any`. My suggestion is that props should be expected to inherit from some kind of standard class like `React.Props` which defines `children` and any other standard members of `this.props`.

Note, I'm a little confused what the difference is between DefinitelyTyped and Typings and why both have their own React bindings, so I'm not sure this is the correct place to be filing this issue.

**Comment by vsiao** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts#L169-L174 should give you the right behavior; maybe you're using an old version of `react.d.ts`?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
