### ISSUE TITLE
NodeJS type definitions improperly type ReadableStream pause() and resume()

### ISSUE THREAD

**Issue by ddaws** [DefinitelyTyped/DefinitelyTyped#10185]
The current type definitions of `ReadableStream`'s `pause` and `resume` method return null. This is not the case in versions 6.x of NodeJS. `pause` and `resume` return a `this` reference to the `ReadableStream`.

See here for `ReadableStream` type definition - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/node.d.ts#L260-L261

See here for the NodeJS doc corresponding to these methods : 

- pause https://nodejs.org/api/stream.html#stream_readable_pause
- resume https://nodejs.org/api/stream.html#stream_readable_resume

**Comment by mhegazy** [comment]
Please send a PR for the update.

**Comment by ddaws** [comment]
@mhegazy sorry for the delay. PR here : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10607

**Comment by mhegazy** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10607
