### ISSUE TITLE
Add escodegen and estraverse to types-2.0

### ISSUE THREAD

**Issue by sanex3339** [DefinitelyTyped/DefinitelyTyped#10180]
It is possible to add definitions for escodegen and estraverse to types-2.0 branch?
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/escodegen
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/estraverse

**Comment by vvakame** [comment]
https://www.npmjs.com/package/@types/escodegen
https://www.npmjs.com/package/@types/estraverse
this is it.
