### ISSUE TITLE
Missing xpath definitions under @types/xpath

### ISSUE THREAD

**Issue by realityfilter** [DefinitelyTyped/DefinitelyTyped#10191]
The xpath type definitions are currently not available under `@types/xpath`.
Please add them. See https://github.com/Microsoft/TypeScript/issues/9184

- [x] I want to talk about `xpath/xpath.d.ts`.
  - The authors of that type definition are cc/ @cspotcode

**Comment by mhegazy** [comment]
The definitions in xpath are now in the standard library. see lib.d.ts.
