### ISSUE TITLE
Latest publish of @types/rx is broken (v2.5.28)

### ISSUE THREAD

**Issue by jonrimmer** [DefinitelyTyped/DefinitelyTyped#10196]
- [x] I tried using the latest `rx/rx.lite.d.ts` file in this repo and had problems.
  - The authors of that type definition are cc/ @Igorbek 

Something seems to have gone wrong with the publication of @types/rx. It only contains two files: index.d.ts and rx-lite.d.ts, while it should contain all of this: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/rx

**Comment by mhegazy** [comment]
The tsconfig.json file should include them all. feel free to send a PR and i will merge it.
