### ISSUE TITLE
Require UTF-8 encoding

### ISSUE THREAD

**Issue by stijnherreman** [DefinitelyTyped/DefinitelyTyped#1026]
There are currently several tickets in the TypeScript issue tracker regarding file encoding.
Starting with TS 0.9.0, ANSI encoding is no longer supported. Files must be encoded as UTF-8 (if they include characters like à or é), else the compiler will choke on the file.

There are already several commits that change a typing to UTF-8, so it might be a good idea to require UTF-8 encoding for all files in this repo. If possible, a mass convert should be done to all files, but I'm not sure if such an operation is without risks.

References:
https://typescript.codeplex.com/workitem/1128
https://typescript.codeplex.com/workitem/1347
https://typescript.codeplex.com/workitem/1537
https://typescript.codeplex.com/workitem/1587

**Comment by jakebailey** [comment]
Old issue, but after formatting, we're definitely all utf-8.
