### ISSUE TITLE
jstree - get_path params not marked to be optional

### ISSUE THREAD

**Issue by TheRealDarklord** [DefinitelyTyped/DefinitelyTyped#10271]
- [x] I tried using the latest `jstree/jstree.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `jstree/jstree.d.ts`.
  - The authors of that type definition are @AdaskoTheBeAsT @vvakame

As per the official [jsTree API](https://www.jstree.com/api/#/?q=get_path) the definition for the get_path method states the second and third parameter to be optional. The current version in this repo acknowledges this fact in the comment section but not in the actual definition.

**Comment by AdaskoTheBeAsT** [comment]
Hi,

thanks for reporting.
Fix implemented
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10272 

Best regards

Adam
