### ISSUE TITLE
jasmine-ajax stubRequest data can be a RegExp as well

### ISSUE THREAD

**Issue by AlexanderHefner** [DefinitelyTyped/DefinitelyTyped#10315]
Hello,

I'm using jasmine-ajax and stumbled over an issue.

The stubRequest function of MockAjax lokks currently like this:
`stubRequest(url: RegExp, data?: string, method?: string): JasmineAjaxRequestStub;`
`stubRequest(url: string, data?: string, method?: string): JasmineAjaxRequestStub;`

But it is possible to make the data as a regex as well:
`MockAjax.stubRequest(url: RegExp, data?: RegExp, method?: string): JasmineAjaxRequestStub;`
`MockAjax.stubRequest(url: string, data?: RegExp, method?: string): JasmineAjaxRequestStub;`

Best Regards,
Alex

@RomanVasilkov

**Comment by vvakame** [comment]
please send a pull request. I'll review it.
