### ISSUE TITLE
Definition of Promise in React-Native Typescript 2.0 branch

### ISSUE THREAD

**Issue by joewood** [DefinitelyTyped/DefinitelyTyped#10319]
The react-native Typescript 2.0 branch for `@types` defines its own version of Promise. Can't this be removed in favor of `--lib es2015.promise` ?

Also, these types seem out of date (missing Linking, StatusBar etc..).  What's the process for keeping them in sync? Just a PR or is there a script automating changes from the main branch?

cc: @RyanCavanaugh

**Comment by vvakame** [comment]
please send a pull request to types-2.0 branch.

**Comment by RyanCavanaugh** [comment]
There's a merge in progress. Once that lands (todayish) we can take a PR against the new branch.

**Comment by joewood** [comment]
Any update on this?

**Comment by mhegazy** [comment]
this is working fine for me with `@types/react-native@0.29.29`
