### ISSUE TITLE
aws-sdk amazon SES

### ISSUE THREAD

**Issue by ronzeidman** [DefinitelyTyped/DefinitelyTyped#10314]
- I tried using the latest `aws-sdk/aws-sdk.d.ts` file in this repo and had problems.
- The authors of that type definition are cc/ @midknight41

the amazon SES class currently looks like this:
```ts
export class SES {
		constructor(options?: any);
		public client: Ses.Client;
	}
```
it should look like this:
```ts
export class SES implements Ses.Client {
        constructor(options?: any);
        config: ClientConfig;

        sendEmail(params: any, callback: (err: any, data: Ses.SendEmailResult) => void): void;
        [....]
}
```
it also lacks a lot of other functions (http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html) but at least you'll be able to send email out of the box.

also `SimpleWorkflow` suffers from the same issue, plus it's name should be `SWF` and not `SimpleWorkflow` (http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SWF.html)

**Comment by midknight41** [comment]
I think something has gone wrong here. SES had definitions before! I'll have a look...

**Comment by midknight41** [comment]
#10384 should correct both mistakes.
