### ISSUE TITLE
Superagent definition doesn't support .then()

### ISSUE THREAD

**Issue by janpieterz** [DefinitelyTyped/DefinitelyTyped#10322]
- [x] I tried using the latest `superagent/superagent.d.ts` (1.4.0+20160724070541) file in this repo and had problems.

Locally this works for me (typescript in es6 mode) but I'm not sure if this applies to all versions etc etc. Thoughts? More than happy to make a pull request if below is good!
``` js
then<TResult>(onfulfilled?: (value: Response) => TResult | PromiseLike<TResult>, onrejected?: (reason: any) => TResult | PromiseLike<TResult>): Promise<TResult>;
then<TResult>(onfulfilled?: (value: Response) => TResult | PromiseLike<TResult>, onrejected?: (reason: any) => void): Promise<TResult>;
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by janpieterz** [comment]
Created #10341
