### ISSUE TITLE
Missing hideNoData/showNoData method in highcharts/index.d.ts

### ISSUE THREAD

**Issue by nitoloz** [DefinitelyTyped/DefinitelyTyped#10342]
I tried using the latest `highcharts/index.d.ts` file in this repo and had problems using one of highcharts plugins - no-data-to-display [code here](https://code.highcharts.com/modules/no-data-to-display.js) and here is a [demo](http://jsfiddle.net/highcharts/hxGmq/) for it.
Unfortunately I can not find chart.hideNoData() and chart.showNoData() methods in the highcharts/index.d.ts and so I can not use them in my web app although they are both used in demo mentioned above. 
Could you please review and check if it is possible to add this plugin interface to the index.d.ts?

Thanks,
Andrey

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by nitoloz** [comment]
@vvakame sorry, it looks like I don't have enough permissions to push my branch to remote repo, because git push returns 403.
Could you probably add following methods to the HighchartsChartObject interface in the highcharts/highcharts.d.ts:
`
    /**
     * Hide the 'No data to display' message added by the no-data-to-display plugin.
     * @since 3.0.8
     */
    hideNoData(): void;

    /**
     * Display a no-data message.
     * @param {String} message An optional message to show in place of the default one
     * @since 3.0.8
     */
    showNoData(message?: string): void;

    /**
     * Returns true if there are data points within the plot area now
     * @return {boolean} If chart has any data.
     * @since 3.0.8
     */
    hasData(): boolean;
` 

Best regards
Andrey

**Comment by vvakame** [comment]
@nitoloz check this document. https://help.github.com/articles/using-pull-requests/

**Comment by nitoloz** [comment]
@vvakame thank you for instructions!
aised a pull request

**Comment by damianog** [comment]
@vvakame consider #10342 closed by #10580
