### ISSUE TITLE
AWS SDK does not have Lambda typing

### ISSUE THREAD

**Issue by nirmalgoswami** [DefinitelyTyped/DefinitelyTyped#10356]
I am talking about aws-sdk/aws-sdk-tests.ts and it does not have typing for lambda

another repo  [aws-sdk-typescript](https://github.com/ingenieux/aws-sdk-typescript) have lambda typing but i dont know how to combine it

cc/ @MichaelBuen @midknight41

**Comment by nirmalgoswami** [comment]
@midknight41 can you please give me answer

**Comment by midknight41** [comment]
#10384 Should address the missing definitions. I had the definitions already and forgot to check them in. My bad.

The repo you reference looks like it generates good definitions but I didn't get a chance to have a good look.

If you were to combine another one in the future you'd need to copy the class definition in the main AWS namespace and the entire Lambda namespace too.

Hope that helps.

**Comment by QuantumInformation** [comment]
There is also no types for the event param, should I open an issue?

![image](https://user-images.githubusercontent.com/216566/30210305-fc820402-9493-11e7-92c1-aadd5715a087.png)

cc @skarum @stefH @darbio

**Comment by midknight41** [comment]
The aws-sdk ships with its own definitions. You should use those. If there is is an error in them you should raise it with the AWS repo.

**Comment by midknight41** [comment]
@andy-ms Given AWS manage their own definitions, shouldn't this issue be closed?

**Comment by andy-ms** [comment]
Yep, `@types/aws-sdk` should give you a deprecation message if you try to install it.

**Comment by buggy** [comment]
Last time I checked the type definitions you need for Lambda aren't included in the aws-sdk. Just add `@types/aws-lambda` and use those. There isn't a definition for `Event` because the structure is dependent on the event source. Instead there are definitions for a number of sources (but not all)

**Comment by QuantumInformation** [comment]
Ah that makes sense
