### ISSUE TITLE
react-bootstrap-table typings should not require a dependency on node

### ISSUE THREAD

**Issue by rmtew** [DefinitelyTyped/DefinitelyTyped#10350]
- [X] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I want to talk about `react-bootstrap-table/react-bootstrap-table.d.ts`.
  - The authors of that type definition are cc/ @flaub @scharf @ianks

I get "cannot find module 'events'" when I install these typings.  I 

There are no separately available typings for events that I can find, and I am not sure installing the node typings is reasonable or correct except as a hack.

As I understand it, events is component of node, which is not necessarily a dependency of anyone using 'react-bootstrap-table' and so I file this as a bug.

**Comment by rmtew** [comment]
Note that installing the node typings also changes the standard javascript api and breaks my code, so definitely is not an option.

**Comment by GeraldIstar** [comment]
Meet the same problem too.

**Comment by ianks** [comment]
Where are the events used?

**Comment by rmtew** [comment]
Manually editing the index.d.ts is what we have to do, as the easiest fix
for now:

Make this change at the start:

  // import { EventEmitter } from 'events';

and this at the end:

export class TableDataSet /* extends EventEmitter */ {
    constructor(data: any);
setData(data: any): void;
clear(): void;
getData(): any;
}

After that, the typings work wonderfully.

**Comment by GeraldIstar** [comment]
Fix by installing node typings:
`typings install node --save --source dt --global`

**Comment by rmtew** [comment]
this is not a solution as I am not using node, and it alters the
environment for node customisations and breaks things.

**Comment by flaub** [comment]
Looks like the latest version does away with the TableDataSet entirely:

https://github.com/AllenFang/react-bootstrap-table/commit/239d8b1c39d07c71db62b1b4850663801fb17517

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
