### ISSUE TITLE
Blockly - DefinitelyTyped

### ISSUE THREAD

**Issue by nazzkhan21** [DefinitelyTyped/DefinitelyTyped#1038]
Working on a web app in TypeScript which requires Blockly.js.

https://code.google.com/p/blockly/

It would be nice if someone could do a definition file for Blockly.

**Comment by trodi** [comment]
Has anyone done work on this? I agree this would be very nice to have.

Code now located here: https://github.com/google/blockly

**Comment by zinovyevdmitry** [comment]
I've started to work on this...

**Comment by trodi** [comment]
Here's a d.ts file for everything in Blockly's core [blockly-d.ts](https://github.com/trodi/blockly-d.ts).

**Comment by jakebailey** [comment]
blockly ships types.

**Comment by trodi** [comment]
For context, Blockly ships types _now_. In 2015, it did not. Excerpt from the afore linked [blockly-d.ts](https://github.com/trodi/blockly-d.ts):

> [Blockly](https://github.com/google/blockly) now ships it's own typescript d.ts file. They generate the file the same way I do, except I also exposed private fields. Prefer their bundled version and only use these types if you are using a version before types were bundled or need all the private types defined.

**Comment by jakebailey** [comment]
Yes, I'm doing cleanup :)
