### ISSUE TITLE
How often are types-2.0 published to npm?

### ISSUE THREAD

**Issue by brunolm** [DefinitelyTyped/DefinitelyTyped#10380]
- [ ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

I'm having an issue with [@types/react-redux](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/react-redux/index.d.ts) I saw that there was a fix 3 days ago https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b488f3cb5f70ea62c66a3ecaef4e38baadf3727c

But on NPM the latest published was 2 weeks ago.

How long does it take to sync? Can we do something about it?

**Comment by vvakame** [comment]
cc/ @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
Tracking at Microsoft/types-publisher#96
