### ISSUE TITLE
Remove `icon` from `React.HTMLAttribute` interface

### ISSUE THREAD

**Issue by smockle** [DefinitelyTyped/DefinitelyTyped#10467]
- [x] I tried using the latest `react/react.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `react/react.d.ts`.
  - The authors of that type definition are cc/ @vsiao @RandScullard @SereznoKot @RyanCavanaugh (these are the latest authors listed by `git blame`)

The `React.HTMLAttribute` interface [defines](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/613673de3672114c562fdf9f142bfeefc29173c9/react/react.d.ts#L1968) `icon?: string;`, but `icon` isn’t an attribute used by any supported HTML element.

`icon` is not included in the HTML4 or HTML5 specs:
[List of HTML4 attributes](https://www.w3.org/TR/html4/index/attributes.html)
[List of HTML5 attributes](https://www.w3.org/TR/html5/index.html#attributes-1)

Mozilla Developer Network includes `icon` in its [list of attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes), but specifies the only element to use `icon` is the [obsolete `<command>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/command). `<command>` isn’t supported in [any desktop or mobile browser](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/command#Browser_compatibility).

**Comment by RyanCavanaugh** [comment]
This is listed in the documentation for React https://facebook.github.io/react/docs/tags-and-attributes.html#html-attributes . Are their docs correct?

**Comment by smockle** [comment]
@RyanCavanaugh Good find. It appears that [React does include `icon`](https://github.com/facebook/react/blob/cccef3c68310df3bd611df2a7b98a530645c67c0/src/renderers/dom/shared/HTMLDOMPropertyConfig.js#L85) in a section labelled `Standard Properties` in the `HTMLDOMPropertyConfig` object.

I’ll open an issue in the React repo and post an update here with any developments. Feel free to close this issue in the meantime, and many thanks for your time! :)

**Comment by RyanCavanaugh** [comment]
I think it'd be fine to send a PR to remove it now. If it's going away in the next React release people may as well stop using it now (which I doubt anyone is anyway!)

**Comment by smockle** [comment]
Thanks! PR sent: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10887
