### ISSUE TITLE
Lodash cloneDeepWith miss-definition

### ISSUE THREAD

**Issue by franleplant** [DefinitelyTyped/DefinitelyTyped#10463]
I tried using the latest `lodash/lodash.d.ts` file in this repo and had problems.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/lodash/lodash.d.ts#L11108

Particularly the `customizer` interface seems wrong and the compiler complains.

The [official docs](https://lodash.com/docs#cloneDeepWith) state:

``` md
This method is like _.cloneWith except that it recursively clones value.

Since
4.0.0

Arguments
value (*): The value to recursively clone.
[customizer] (Function): The function to customize cloning.
```

So customizer should be typed something like this:

``` typescript
type Customizer = (value: TValue, indexOrkey?: number | string, object?:any, stack?: any) => TResult;
```

But it's typed as an Object containing that function

``` typescript
    interface CloneDeepWithCustomizer<TValue, TResult> {
        (value: TValue): TResult;
    }
```

And thus something simple like this does not work (super simple example):

``` typescript
const clone = cloneDeepWith([0,1,2,3], value => value === 0 ? 100 : 200)
```

Thank you.
Fran

**Comment by nycdotnet** [comment]
Please submit a PR for this.  Thanks.

**Comment by franleplant** [comment]
Sure, Ill see if I have that time, thanks

**Comment by aj-r** [comment]
This is fixed now

**Comment by nycdotnet** [comment]
ty
