### ISSUE TITLE
Cannot use long type definitions in node

### ISSUE THREAD

**Issue by vekexasia** [DefinitelyTyped/DefinitelyTyped#10483]
- [ ] I tried using the latest `registry:dt/long#3.0.2+20160602144319"` file in this repo and had problems.

No matter what I do. Then i do `typings install dt~long --save` it complains about Long being a global module. If I add `--global` flag the installation process goes through but 

`import {Long} from 'long'`
or
`import * as Long from 'long'`

gets a complain about Long not being a module.... I'm new to typings sorry if my problem is dumb :(

**Comment by TonyPythoneer** [comment]
Hello, @vekexasia 

Did you check the **typings.json** that the defination had been installed?

**Comment by vvakame** [comment]
cc/ @blakeembrey

**Comment by blakeembrey** [comment]
@vekexasia Did you include `typings/index.d.ts` in the compilation context? There's a page in the README (also mentioned in https://github.com/typings/typings#quick-start) that tells you how to do it - make sure you add it to `tsconfig.json` (or don't exclude it).

**Comment by TonyPythoneer** [comment]
I think OP should offer his detail problems. If his problem can't be solved by commenter, it needs to organizers help.

**Comment by vekexasia** [comment]
I think it was a cache problem within The ide.

I was able to use long after a restart. Sorry if i did not close this before
