### ISSUE TITLE
@types/clone and @types/node npm modules not in npm registry

### ISSUE THREAD

**Issue by chrisgreg** [DefinitelyTyped/DefinitelyTyped#10508]
Getting a 404 when trying to `npm install @types/clone` and `npm install @types/node` which is breaking our prod build.

Any word on when this will be resolved or work arounds?

Thanks

**Comment by Bodhiz** [comment]
Same issue here.

**Comment by RoXuS** [comment]
+1

**Comment by jasongardnerlv** [comment]
+1
it is affecting the installation of PolymerLabs/dom5

**Comment by Bodhiz** [comment]
waiting a fix, a workaround is to add this line in .npmrc : 
```@types:registry=https://registry.npmjs.org```

**Comment by tomconnell-wf** [comment]
Installing from the public registry was not working for me.  I am using n to switch node version, and it did not work in v4.4.7 or v6.3.1.  However, I did `npm up -g npm` while on node 6.3.1.  Then the @types/clone install worked for me.  And subsequently works in either node 4.4.7 or 6.3.1, with the npm version that n provides.  It seems like the node_modules in /usr/local/lib/node_modules/npm/node_modules might have been stale and n wasn't properly replacing them?

**Comment by vvakame** [comment]
cc/ @RyanCavanaugh

**Comment by mhegazy** [comment]
//cc: @andy-ms

**Comment by andy-ms** [comment]
Should be fixed now. See Microsoft/types-publisher#116
