### ISSUE TITLE
[npm]: publishing issue

### ISSUE THREAD

**Issue by Delagen** [DefinitelyTyped/DefinitelyTyped#10506]
Latest published modules has tgz extension when installing but correct extension should be TAR.
My private proxy npm server check for correct mime typing, and fails to install. I need to disable this check.

Please check your publishing scripts

**Comment by Bodhiz** [comment]
Hi @Delagen,
Are you using Sinopia ?  If yes, wow did you disable this file type check ?

**Comment by Delagen** [comment]
No. I use Nexus OSS, because Sinopia is dead project for a year now.
I used sinopia for two years before, but NPM changes quickly and I moving forward.

**Comment by andy-ms** [comment]
Should be fixed now. See Microsoft/types-publisher#116
