### ISSUE TITLE
Request for ava and ava-spec

### ISSUE THREAD

**Issue by RWOverdijk** [DefinitelyTyped/DefinitelyTyped#10502]
I can't seem to find typings for [ava](http://npmjs.com/package/ava) and / or [ava-spec](http://npmjs.com/package/ava-spec).

**Comment by tpetry** [comment]
The typings are provided directly by their projects:
* https://github.com/avajs/ava/blob/master/index.d.ts
* https://github.com/sheerun/ava-spec/blob/master/types/index.d.ts

**Comment by Semigradsky** [comment]
@RWOverdijk could you close this issue?

**Comment by RWOverdijk** [comment]
Sure.
