### ISSUE TITLE
node/node.d.ts http.createServer wrong ?

### ISSUE THREAD

**Issue by mahald** [DefinitelyTyped/DefinitelyTyped#10507]
createServer in the current node definitions was wrong and i had to change it from: 
export function createServer(requestListener?: (request: IncomingMessage, response: ServerResponse) => void): Server;
to: 
export function createServer(requestListener?: Function): Server;
(https is correct)

See: https://nodejs.org/api/http.html#http_http_createserver_requestlistener

wondering a bit as this should be very common, have i missed something ?

- [x ] I tried using the latest `node/node.d.ts` file in this repo and had problems. (-> current master)
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

**Comment by TonyPythoneer** [comment]
Please post your source code.

By the way, I had no this problem.

**Comment by mahald** [comment]
the relevant part of the code is:

`		

        
		...
		import * as http from "http";
		import * as https from "https";
		....
    class Server{
        public app: express.Application;

	 constructor() {
    //create expressjs application
    this.app = express();

    this.setupDummyData();

    this.app.use("/a", graphqlHTTP((request) => ({ schema: this.mySchema, pretty: true, graphiql: true })));
    this.app.use("/b", graphqlHTTP((request) => ({ schema: this.mySchema2, pretty: true, graphiql: true })));
    this.app.use("/", express.static(path.join(__dirname, "htdocs")));

    var options = {
        key: fs.readFileSync("./ssl_certs/server.key"),
        cert: fs.readFileSync("./ssl_certs/server.crt")
    };
    https.createServer(options, this.app).listen(443, "127.0.0.1");
    http.createServer(this.app).listen(80, "127.0.0.1");

       }
      }
`

ErrorMessage before my change was: 
`    src/app.ts(114,23): error TS2345: Argument of type 'Application' is not assignable to parameter of type '(request: IncomingMessage, response: ServerResponse) => void'. 
`

as it's ok for https it's at least inconsistent. On https it's defined like : 
`      export function createServer(options: ServerOptions, requestListener?: Function): Server;)
`
what was fine, while on http it's defined 

`     export function createServer(requestListener?: (request: IncomingMessage, response: ServerResponse) => void): Server;
`

**Comment by TonyPythoneer** [comment]
I see. The **http** definition design only consider **node.js** built-in module, not for **express**. When you assign a **express.Application** value to **http.createServer**, it happens error.

I think it needs to add this definition:
```js
 createServer(app: express.application): Server;
```
Maybe it can be solved.

But I never try to modify definition when it needs to cross module and import relative definition. I need other developers to discuss this.

**Comment by TonyPythoneer** [comment]
@sandersn or @mahald , please close this issue since #10676 is merged now.
