### ISSUE TITLE
[types-2.0] Flux/utils not working

### ISSUE THREAD

**Issue by GiedriusGrabauskas** [DefinitelyTyped/DefinitelyTyped#10524]
I run this command:
```cmd
npm install @types/flux
```
And I get only `flux` typings from [flux/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/flux/index.d.ts).

In result, I can't import `flux/utils` ([read more](https://www.npmjs.com/package/flux#flux-utils)).

`flux/utils` file: [flux/utils/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/flux/utils/index.d.ts).

**Comment by vvakame** [comment]
please try `mv node_modules/@types/flux/utils/index.d.ts node_modules/@types/flux/utils.d.ts`. 
Is this works?

**Comment by GiedriusGrabauskas** [comment]
Folder structure:
```
-- node_modules
  `-- @types
     `-- flux
        `-- index.d.ts
        `-- package.json
        `-- README.md
        `-- type-metadata.json 
```

These files doesn't exist in `@types/flux` package.

**Comment by GiedriusGrabauskas** [comment]
Amm... Maybe the problem is in `tsconfig.json` file? 

`utils/index.d.ts` file is missing from [tsconfig.json](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/flux/tsconfig.json):

```json
 "files": [
   "index.d.ts",
   "flux-tests.ts"
]
```
