### ISSUE TITLE
cassandra-driver Cannot find type definition file for 'long'

### ISSUE THREAD

**Issue by yeiniel** [DefinitelyTyped/DefinitelyTyped#10538]
I was trying the @types/cassandra-driver@0.8.2 package and found this problem. The error message is as follow:

```
node_modules/@types/cassandra-driver/cassandra-driver.d.ts(7,1): error TS2688: Cannot find type definition file for 'long'.
node_modules/@types/cassandra-driver/cassandra-driver.d.ts(15,26): error TS2307: Cannot find module 'long'.
```

The typescript compiler version is Version 2.1.0-dev.20160716

**Comment by jcsrb** [comment]
I fixed this for me by manually installing the `long` typings
`typings install dt~long --save  --global`
