### ISSUE TITLE
TypeScript definition file for Highchart extensions

### ISSUE THREAD

**Issue by inad9300** [DefinitelyTyped/DefinitelyTyped#10540]
Currently there is a [definition file for Highcharts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/highcharts/highcharts.d.ts), but this is not the case for the related extensions/modules like [more](https://github.com/highcharts/highcharts/blob/master/lib/highcharts-more.src.js) and [exporting](https://github.com/highcharts/highcharts/blob/master/lib/modules/exporting.src.js).

It would be great to have TypeScript support for the whole Highcharts library.

Thanks!

**Comment by damianog** [comment]
Hi @inad9300 as for #10580 feel free to contribute for the [other modules](http://code.highcharts.com/) supported by Highcharts.

Anyway I'll see what can I do or maybe @baltie

**Comment by baltie** [comment]
I don't have as much time as I'd like these days for contributing. However, I think most of what is in highcharts-more.js is part of the definitions, as well as some parts of the exporting module. It all depends whether it's in the highcharts API documentation or not. If it is, it is in the definitions, if it is not, it probably isn't there. Which also means that most of the other modules you link to, @damianog, is actually in the definitions.

**Comment by inad9300** [comment]
I see now how things like the `color` property for the `HighchartsSeriesChart` interface are not complete. They are allowed to hold gradients as explained in http://www.highcharts.com/docs/chart-design-and-style/colors, but there is no mention of this in the [API documentation / Options Reference](http://api.highcharts.com/highcharts), which I guess is your main source of information.

**Comment by baltie** [comment]
With regard to gradients, there is a HighchartsGradient interface in the definitions, and the colors property is overloaded in the appropriate places for different types of series. Highcharts might have increased the number of series types that supports gradients since we went through the definitions last.

You are right, the API reference is the main source of information, but it is actually, in my experience, quite comprehensive and complete.

**Comment by mc-suchecki** [comment]
I've started to work on this.

**Comment by mc-suchecki** [comment]
@inad9300 told me that my version is solving the issue for him. I've created a pull request, feel free to comment on it. :+1:
