### ISSUE TITLE
Add default export for angular-ui-router

### ISSUE THREAD

**Issue by clemgrim** [DefinitelyTyped/DefinitelyTyped#10542]
- [x] I tried using the latest `angular-ui-router/angular-ui-router.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `angular-ui-router/angular-ui-router.d.ts`.
  - The authors of that type definition are cc/ @mtiller

Is it possible to add an export field for the module name `ui.router` ?

The basic use case is:

``` ts
import * as uiRouter from 'angular-ui-router';

angular.module('test', [uiRouter])
```

But when I do this I got this typescript error:

> Argument of type 'typeof 'angular-ui-router'[]' is not assignable to parameter of type 'string[]'.
>   Type 'typeof 'angular-ui-router'' is not assignable to type 'string'.

Tell me if I'm doing something wrong
Note that I know I can do `import 'angular-ui-router` and then just put a string as module dependency.
But I really want to use the code above, because it works for all of my other dependencies.

**Comment by josueggh** [comment]
Same petition here!

**Comment by manbearwiz** [comment]
I noticed this comment in the dt module definition 
```
    // Since angular-ui-router adds providers for a bunch of
    // injectable dependencies, it doesn't really return any
    // actual data except the plain string 'ui.router'.
    //
    // As such, I don't think anybody will ever use the actual
    // default value of the module.  So I've only included the
    // the types. (@xogeny)
```

**Comment by josueggh** [comment]
I did this : 

```javascript
import * as angular from 'angular';
import 'angular-ui-router';
import * as uiRouter from "angular-ui-router";

import AppComponent from './app.component';
import Common from "./common/common"
import Components from "./component/component";

const app = angular
  .module("myapp",[
    Common,
    Components,
    "ui.router"
  ])
  .component("app",AppComponent)
  .name;

export default app;
```
So I don't know if is a cleaner way to get the "ui.router" inside the dependencies of my module.

**Comment by dietergoetelen** [comment]
Had the same problem, I solved it as follows to satisfy the compiler:
```
import * as router from 'angular-ui-router';
import * as angular from 'angular';

angular.module('app', [
   <any>router
]);
```

**Comment by Xmary** [comment]
I had the same problem, I solved it with following tsconfig.json file:
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": "src",
    "module": "es6",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5"
  }
}
```
Specifically after adding `module` and `moduleResolution` settings.

**Comment by daerogami** [comment]
I believe this is relevant to this issue, if not I'll create a new issue.
As of 49e00c423a63b6e5b00cf0105c5fe6a2ac57336b
'angular-ui-router/index.d.ts' line 8 has `export default 'ui.router';`

which causes the following error in typescript 2.6+
```TS2714:	(TS) The expression of an export assignment must be an identifier or qualified name in an ambient context.	\scripts\typings\angular-ui-router\index.d.ts	8```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
