### ISSUE TITLE
[types-2.0] Highstock is missing

### ISSUE THREAD

**Issue by JannesMeyer** [DefinitelyTyped/DefinitelyTyped#10564]
I want to talk about `highcharts/highstock.d.ts`.
The authors of that type definition are cc/ @DavidKDeutsch @damianog @baltie

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/highcharts

It is impossible to install highstock type definitions using `npm install @types/highcharts` because the highstock file is not included in this package. Maybe a separate package for highstock would make sense?

**Comment by andy-ms** [comment]
Fixed by #10654
