### ISSUE TITLE
Typing name doesn't match package name

### ISSUE THREAD

**Issue by xt0rted** [DefinitelyTyped/DefinitelyTyped#10572]
- [ ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about [bootstrap.datepicker](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/ecb46a6e3f9bfdd0cc3d23e20a9b3983984cb62f/bootstrap.datepicker)
  - The authors of that type definition are cc/ @borisyankov 

The `bootstrap.datepicker` typing doesn't match the package's name which is `bootstrap-datepicker`. Should this be renamed to match what's on [bower](https://github.com/eternicode/bootstrap-datepicker/blob/4c47c11ee848c2151a46593ab44e96257b3c63f9/bower.json) & [npm](https://github.com/eternicode/bootstrap-datepicker/blob/4c47c11ee848c2151a46593ab44e96257b3c63f9/package.json)?

**Comment by vvakame** [comment]
👍 for npm.
