### ISSUE TITLE
Definition Request: add typings for pouchdb-upsert library

### ISSUE THREAD

**Issue by keithdmoore** [DefinitelyTyped/DefinitelyTyped#10596]
Looking for help to create the typings for the pouchdb-upsert library.  I dont mind going thru the process of testing and submitting a PR for this.  I just need a little help with how I might go about doing this.  https://github.com/pouchdb/upsert/issues/24

@geppy Can you provide me a general approach?

**Comment by keithdmoore** [comment]
Currently have this but I have not been able to test it fully yet:

````javascript
/// <reference path="../pouchdb-core/pouchdb-core.d.ts" />
declare namespace PouchDB {
  export interface Database<Content extends Core.Encodable> {
    // TODO: Add callback version
    upsert(docId: Core.DocumentId, diffFun: Core.Callback<Core.Error, Core.Response>): Promise<Core.Response>;

    // TODO: Add callback version
    putIfNotExists(doc: Core.Document<Content>): Promise<Core.Response>;
  }
}

declare module 'pouchdb-upsert' {
  const PouchDb: PouchDB.Static;
  export = PouchDb;
}
````

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by keithdmoore** [comment]
PR will be submitted soon

**Comment by geppy** [comment]
@keithdmoore That looks great.  If you have any questions feel free to jump on the [PouchDB Slack](http://slack.pouchdb.com/), I'm in `#typescript` with the core devs.

**Comment by keithdmoore** [comment]
@vvakame PR is complete:  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10745

**Comment by vvakame** [comment]
by #10752
