### ISSUE TITLE
React-native: shouldn't __DEV__ be in the global namespace?

### ISSUE THREAD

**Issue by joewood** [DefinitelyTyped/DefinitelyTyped#10640]
In **react-native/index.d.ts** the `__DEV__` global variable is declared as an export:
```typescript
declare var __DEV__: boolean;
```

React Native defines this as a global, it would be better to add this to the set of global namespace exports:
```typescript
declare global {
    const global: React.GlobalStatic;
    function require(name: string): any;
    /**
     * This variable is set to true when react-native is running in Dev mode
     * Typical usage:
     * <code> if (__DEV__) console.log('Running in dev mode')</code>
     */
    const __DEV__: boolean
}
```

**Comment by mhegazy** [comment]
Feel free to send a PR, also a link to the docs would be helpful to validate this change.

**Comment by joewood** [comment]
Sure, will do. Reference to the docs is [here](https://github.com/facebook/react-native/blob/bc42861cbfa00d6cff487d05a93c0a5cd47b8401/packager/README.md) - excerpt below:


------------------------------------------
### /path/to/moduleName.(map|bundle) query params

You can pass options for the bundle creation through the query params,
if the option is boolean `1/0` or `true/false` is accepted.

Here are the current options the packager accepts:

* `dev` boolean, defaults to true: sets a global `__DEV__` variable
  which will effect how the React Native core libraries behave.
* `minify` boolean, defaults to false: whether to minify the bundle.

**Comment by joewood** [comment]
This seems to have been fixed in the npm version [(0.29.30)](https://www.npmjs.com/package/@types/react-native) - but not sure which Github repo this is being published from as DT still looks wrong on the @types2 branch.

**Comment by oargaruna** [comment]
@joewood Why is this closed? I don't see the fix in master.

**Comment by oargaruna** [comment]
I have created a PR with the change: #14916
