### ISSUE TITLE
Incomplete type definition for lodash _.find

### ISSUE THREAD

**Issue by nfiles** [DefinitelyTyped/DefinitelyTyped#10658]
I tried using the latest version of this file: `lodash/lodash.d.ts` and encountered an error.
The type definition for ```_.find``` does not allow the developer to provide a property selector function AND an object to compare. This is a valid form in lodash, and is not included in the TS definition.

Example
```
let arr = [{a: 1}, {a: 2}];
let found = _.find(arr, x => x.a, 1);

// result: found === {a: 1}
```

Solution: `lodash/lodash.d.ts:6821`
```
/**
 * @see _.find
 */
find<T, TObject>(
  collection: List<T> | Dictionary<T>,
  predicate?: (T) => TObject,
  thisArg?: TObject
)
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by alejo90** [comment]
@nfiles in lodash 4.14.0 (the version of lodash `lodash/lodash.d.ts` was written for), your example actually returns `{a: 2}` because the 1 you provided is the index to start the search from and not the `thisArg`. `thisArg` is the last parameter in lodash 3.x.

**Comment by nfiles** [comment]
Ah, sorry for the confusion. I recently switched to lodash 4.* and have made a few mistakes like that. Thanks. :)

**Comment by alejo90** [comment]
FYI, I opened #10789 to add the missing `fromIndex` parameter to `find`.

**Comment by vvakame** [comment]
👍
