### ISSUE TITLE
changes in definitions @types install - react-router and react-router-redux 

### ISSUE THREAD

**Issue by Odol** [DefinitelyTyped/DefinitelyTyped#10664]
The definition library ract-router need be updated the namespace old called "_React" now is "React".
The react-router-redux also need changes the namespace history now is called HistoryModule.

the definitions for history library is autoinstalled but not install the extra folders. 
Need be manually installed for correct work. 

**npm install @types/history --save-dev**

**Comment by mhegazy** [comment]
should be addressed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10663
