### ISSUE TITLE
Mediastream Definitions — Typescript 2.0 Compatibility

### ISSUE THREAD

**Issue by sqwk** [DefinitelyTyped/DefinitelyTyped#10678]
When using the mediastream typings with typescript 2.0, a lot of errors like these are logged:

    All declarations of 'volume' must have identical modifiers.
    All declarations of 'id' must have identical modifiers.
    etc.

What exactly does this mean?

cc @vvakame, @nakakura, @horiuchi, @groege, @Garciat, …

**Comment by mhegazy** [comment]
I do not get this to reproduce locally. this means you have a different copy of the file. what is the other file that is showing the duplicate declaration errors?

**Comment by sqwk** [comment]
Installing the npm module `@types/webrtc` instead, solves the problem. Not sure why a standard typings file produces the errors.
