### ISSUE TITLE
Error at accesing methods of child classes of React.Component

### ISSUE THREAD

**Issue by micnic** [DefinitelyTyped/DefinitelyTyped#10675]
- [x] I tried using the latest `react/react.d.ts` and `react/react-dom.d.ts` file in this repo and had problems.
- [x] I want to talk about `react/react.d.ts` and `react/react-dom.d.ts`.
  cc @jbrantly @vsiao @seansfkelley

I have a class, let's name it C which inherits from `React.Component`:

``` ts
class C extends React.Component<any, any> {
    constructor() {
        super();
    }

    public method() {
        return true;
    }
}
```

I want to create a reference to the rendered component, and call its method like this:

``` ts
const c = ReactDOM.render(React.createElement(C), document.getElementById('some id'));

c.method();
```

Until here everything is fine, but if I want to use any props I can not call instance method:

``` ts
class C extends React.Component<any, any> {
    constructor(props) { // Added the props argument to the constructor to be used in super()
        super(props);
    }

    public method() {
        return true;
    }
}

const c = ReactDOM.render(React.createElement(C), document.getElementById('some id'));

c.method(); // => Property 'method' does not exist on type 'Component<any, {} | void> | Element | void'.
```

I guess the problem is somewhere in the definition for `ReactDOM.render()` or `React.createElement()`, but I could not find a solution.

**Comment by vsiao** [comment]
Can you use `componentWillMount` instead of `constructor`?

**Comment by micnic** [comment]
@vsiao I can use `componentWillMount`, but I need to transfer props and create the state in the constructor, the problem is not that `c.method()` does not exists (it exists!), but the definition is expecting a wrong return type in `ReactDOM.render()` when the `props` are transfered from `constructor` to `super()`. I had to add something like:
```ts
(c as C).method();
```
to not receive the error message that `.method()` is missing.

**Comment by vsiao** [comment]
I understand, but `componentWillMount` should be functionally identical to `constructor`—and will let you call `c.method()` without a cast.

**Comment by micnic** [comment]
ok, I'll use `componentWillMount` for now, but in any case `React.createElement()` has a wrong behavior when constructor comes with the `props` argument. I will try to fix this, hope it's a simple fix :)

**Comment by micnic** [comment]
Closing this issue as this is not a recommended behavior from React docs:

> ReactDOM.render() currently returns a reference to the root ReactComponent instance. However, using this return value is legacy and should be avoided because future versions of React may render components asynchronously in some cases. If you need a reference to the root ReactComponent instance, the preferred solution is to attach a callback ref to the root element.
