### ISSUE TITLE
@types/react-router-redux - Module 'history' has no exported member 'History'

### ISSUE THREAD

**Issue by MarkPieszak** [DefinitelyTyped/DefinitelyTyped#10686]
- [X] I tried using the latest `@types/react-router-redux` file in this repo and had problems.
- [X] Using TypeScript **2.0** beta
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] I want to talk about `@types/react-router-redux`.
  - The authors of that type definition are [react-router-redux repo](https://github.com/reactjs/react-router-redux)

I'm getting an issue when using the @types/react-redux-router with TypeScript 2.0 (inside of the @types itself. Has anyone ran into this before by any chance?

> @types/react-router-redux/index.d.ts - error TS2305: Module '"history"' has no
> exported member 'History'.

**Comment by killianbrackey** [comment]
Any updates on this? Using "@types/react-router": "^2.0.39" and  "typescript": "^2.1.1" and getting the following errors:

```
@types/react-router/lib/history"' has no exported member 'Location'
@types/react-router/lib/history"' has no exported member 'LocationDescriptor'
@types/react-router/lib/history"' has no exported member 'Pathname'
@types/react-router/lib/history"' has no exported member 'Path'
@types/react-router/lib/history"' has no exported member 'Query'
@types/react-router/lib/history"' has no exported member 'HistoryQueries'
@types/react-router/lib/history"' has no exported member 'QueryString'
@types/react-router/lib/history"' has no exported member 'LocationState'
@types/react-router/lib/history"' has no exported member 'Href'
(94,39): error TS2312: An interface may only extend a class or another interface.
(112,26): error TS2693: 'History' only refers to a type, but is being used as a value here.
```

Thanks!

**Comment by andy-ms** [comment]
Looks like it could be due to #11514.
