### ISSUE TITLE
@types/interactjs not in npm registry

### ISSUE THREAD

**Issue by sqwk** [DefinitelyTyped/DefinitelyTyped#10689]
@types/interactjs is not currently in the npm registry. Is the process automatic or does someone have to manually create the package?

**Comment by mhegazy** [comment]
the package name is [`@types/interact.js`](https://www.npmjs.com/package/@types/interact.js) which matches the package name on npm `interact.js`.

**Comment by thasmo** [comment]
Seems like nowadays https://www.npmjs.com/package/interactjs is the more up to date one.
