### ISSUE TITLE
Chance#pick is deprecated, use pickone and pickset

### ISSUE THREAD

**Issue by LOZORD** [DefinitelyTyped/DefinitelyTyped#10684]
- [ ] I tried using the latest `chance/chance.d.ts` file in this repo and had problems. (_no problems, but deprecation is important!_
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `chance/chance.d.ts`.
  - The authors of that type definition are @vvakame @cbowdon

As I said, no build issues, but better to catch this now rather than later.
See http://chancejs.com/#pick

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by LOZORD** [comment]
PR: #10751
