### ISSUE TITLE
Error on chai types

### ISSUE THREAD

**Issue by RWOverdijk** [DefinitelyTyped/DefinitelyTyped#10729]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/chai/chai.d.ts#L412

> node_modules/@types/chai/index.d.ts(412,11): error TS2451: Cannot redeclare block-scoped variable 'Object'.

**Comment by RWOverdijk** [comment]
I just found out I have a _lot_ of these kind of errors. To list a couple:

```
node_modules/typescript/lib/typescriptServices.d.ts(2503,15): error TS2451: Cannot redeclare block-scoped variable 'constElement'.
node_modules/typescript/lib/typescriptServices.d.ts(2504,15): error TS2451: Cannot redeclare block-scoped variable 'letElement'.
node_modules/typescript/lib/typescriptServices.d.ts(2507,15): error TS2451: Cannot redeclare block-scoped variable 'none'.
node_modules/typescript/lib/typescriptServices.d.ts(2508,15): error TS2451: Cannot redeclare block-scoped variable 'publicMemberModifier'.
node_modules/typescript/lib/typescriptServices.d.ts(2509,15): error TS2451: Cannot redeclare block-scoped variable 'privateMemberModifier'.
node_modules/typescript/lib/typescriptServices.d.ts(2510,15): error TS2451: Cannot redeclare block-scoped variable 'protectedMemberModifier'.
node_modules/typescript/lib/typescriptServices.d.ts(2511,15): error TS2451: Cannot redeclare block-scoped variable 'exportedModifier'.
```

I'm thinking I'm doing something wrong (very new to typescript scene, sorry.)

**Comment by alejo90** [comment]
It looks like you have duplicated typings for typescriptServices. I suggest you do a search on your project and see if you can find the typescriptServices.d.ts file more than once.

**Comment by RWOverdijk** [comment]
I found the problem. The source was set to `.`, which includes node_modules. I was just being an idiot.
