### ISSUE TITLE
react-router: withRouter throws error  Property 'router' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes

### ISSUE THREAD

**Issue by bezreyhan** [DefinitelyTyped/DefinitelyTyped#10723]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `react-router/index.d.ts`.
  - The authors of that type definition are cc/ @vvakame @awendland

I get the following error when I use the `withRouter` function:
```
Property 'router' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<PageHeader> & IProps & { children?: {} | undefined...'.
```

Here is the relevant code:
```
interface IProps {
   router: { goBack: { (): void } };
}

class PageHeader extends React.Component <IProps, any> {
  public render() {
    return ( ... )
  }
}

export default withRouter(PageHeader);
```

I also tried to use the module version of the react-router type definition but I got the same error.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by bezreyhan** [comment]
This is not a bug. The reason for this error was that I was not providing an interface for context. Adding this to my component class fixed the issue:

```
  context: IContext

  static contextTypes = {
    router: React.PropTypes.func.isRequired
  }
```

where IContext is:
```
interface IContext {
  router: { goBack: { (): void } };
}
```
