### ISSUE TITLE
redux-form: reduxForm signature does not match documented signature

### ISSUE THREAD

**Issue by aventurella** [DefinitelyTyped/DefinitelyTyped#10733]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/redux-form/redux-form.d.ts#L295-L297

The docs provide this signature:
`reduxForm(config:Object, mapStateToProps?, mapDispatchToProps?, mergeProps?, options?)`

http://redux-form.com/5.3.1/#/api/reduxForm?_k=xqa0hz
https://github.com/erikras/redux-form/blob/v5.3.1/src/createReduxForm.js#L11

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by aventurella** [comment]
So I ran into one issue. Let me know what you think and I can proceed.

Based on the docs:

http://redux-form.com/5.3.1/#/api/reduxForm?_k=xqa0hz

> It takes a config parameter and then optionally mapStateToProps, mapDispatchToProps, mergeProps and options parameters which correspond exactly to the parameters taken by react-redux's connect() function

So I took a gander at react-redux's d.ts so I could get their types. The issue arises here:

They have this signature:

```
cOrSelf<MapStateToProps<TStateProps, TOwnProps>>,
    mapDispatchToProps: FuncOrSelf<MapDispatchToPropsFunction<TDispatchProps, TOwnProps>|MapDispatchToPropsObject>,
    mergeProps: MergeProps<TStateProps, TDispatchProps, TOwnProps>,
    options?: Options
  ): ComponentDecorator<TStateProps & TDispatchProps, TOwnProps>;
```

`mergeProps` and `options` are there just fine, but the interface they are constrained to:

- `MergeProps<TStateProps, TDispatchProps, TOwnProps>`
- `Options` 

Are **not** exported. 

Enter my need for your guidance.

I COULD do this for the sake of just letting it work for now:

```
export function reduxForm(config:ReduxFormConfig,
                            mapStateToProps?:MapStateToProps,
                            mapDispatchToProps?:MapDispatchToPropsFunction|MapDispatchToPropsObject,
                            mergeProps?:any, options?: any):ClassDecorator;
```

`mergeProps?:any, options?: any`. I understand why that's not the most ideal, but I think I would need to submit another PR to the `react-redux` to export their currently  non-exported interfaces. 

Bear with me, I'm new to working with and authoring typings, if they don't need to be exported and can be used, that's even better, but sadly I'm ignorant re: how to get a handle on them to include in the `redux-form` typings.

So the question becomes, unless I can get a handle on those 2 types from react-redux, do the fast/cheap/less then ideal solve? Allow people to at least call `reduxForm` with all it's arguments and sacrifice the detailed type info for those 2 args for now. Or keep it broken and wait till react-redux can export those 2 types. Again, it's entirely possible they don't need to be exported to be used. Like I said I'm pretty green with this, so I'd just need to know how to do it.

What do you think?

**Comment by aventurella** [comment]
Ah.. it looks like I just put the `///` directive at the top:

```
/// <reference path="../react-redux/react-redux.d.ts" />
```

which then lets me:

```
import { MergeProps, Options } from 'react-redux';
```

```
 export function reduxForm<TStateProps, TDispatchProps, TOwnProps>(
    config:ReduxFormConfig,
    mapStateToProps?:MapStateToProps,
    mapDispatchToProps?:MapDispatchToPropsFunction|MapDispatchToPropsObject,
    mergeProps?:MergeProps<TStateProps, TDispatchProps, TOwnProps>,
    options?:Options
  ):ClassDecorator;
```

**Comment by aventurella** [comment]
#10740

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
