### ISSUE TITLE
material-ui/TextField onChange does not allow for other arguments

### ISSUE THREAD

**Issue by bezreyhan** [DefinitelyTyped/DefinitelyTyped#10734]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `material-ui/index.d.ts`.
  - The authors of that type definition are cc/ @ngbrown 

The `onChange` prop for `TextField` a function of type: `React.FormEventHandler`.
`React.FormEventHandler` only expects one argument of type: `FormEvent`. However, onChange provides a second argument - the value of the input that has changed. Though, if you try to use that second argument you will get a compiler error because `React.FormEventHandler` only expects one argument.

The following cases will throw an error:

```
<TextField
   onChange={this.onChange}
/>

onChange(event: React.FormEvent, value: string) { ... )
````

also doing something like this:

```
<TextField
   onChange={this.onChange.bind(this, 'firstName' )}
/>

onChange(inputName: string, event: React.FormEvent) {
   this.setState = { [inputName]: event.target.value };
}
````

A potential fix would be to change the type of `onChange` to a function that allows any args in any order: `{ (...args: any[]): void } `

This comes with some disadvantages. I'm not sure what would be the best route to take.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by bezreyhan** [comment]
I was able to work around this by assigning onChange to a arrow function, rather than using bind:

```
     <TextField
       onChange={(e) => this.setInputState(e, 'lastName')}
     />
```

I'm going to close this for now.

**Comment by apodaka** [comment]
You can perform your settet if you take the name from field and set state using the same name.
i.e.

`
state = {
  form: {
    lastName: ''
  }
}
....
handleChange = (event) => {
  const { target: { name, value } }
  this.setState(() => ({ form[name]: value }))
}
...
<TextField
  name="lastName"
 onChange={this.handleChange}
`

**Comment by Rupeshiya** [comment]
Hi @apodaka ,
In my case not working when I am making a reusable component. Look at the below code
```import React from 'react'
import { makeStyles } from '@material-ui/core/styles';
import TextField from '@material-ui/core/TextField';

const useStyles = makeStyles(theme => ({
  root: {
    display: 'flex',
    flexWrap: 'wrap',
  },
  textField: {
    marginLeft: theme.spacing(1),
    marginRight: theme.spacing(1),
    width: 200,
  },
}));

function InputTextField({ label, placeholder, helperText, onChange, value, multiline, rows, fullWidth, className, id }) {
  const classes = useStyles();

  return (
      <div className="row">
          <div className={classes.root}>
            <TextField
              id={id}
              label={label}
              style={{ margin: 5 }}
              placeholder={placeholder}
              helperText={helperText}
              fullWidth={fullWidth}
              margin="normal"
              InputLabelProps={{
                shrink: true,
              }}
              onChange={onChange}
              value={value}
              rows={Boolean(rows) ? rows : 1}
              multiline={Boolean(multiline) ? multiline : false }
              className={className}
            />
        </div>
      </div>
  );
}
export default InputTextField;
```

**Here is my another component in which I am using this InputTextField component**
```
class CreateSong extends Component {
  state = {
    title: "",
    description: ""
  };
  onChange = (e) => {
    this.setState({[e.target.name]: e.target.value })
  }
  onSubmit = (e) => {
    e.preventDefault();
    const songObj = {
      title : this.state.title,
      content: this.state.description
    };
    console.log(songObj);
    // after adding the graphql mutation property to the component we get all the methods and data in this.props
    this.props.mutate({
      variables: {
        title: this.state.title
      }
      // refetchQueries: [{ query }]
      // redirect to the songs lists
    }).then(()=>{
      this.props.history.push('/');
    })
  }
  render() {
    return (
      <div className="container">
      <h1 className="text text-center">Create Song</h1>
        <div className="form-group" style={{ display: "flex",
          justifyContent: "center",
          margin: 20,
          padding: 20
          }}>
          <form onSubmit={this.onSubmit} style={{width: "50%"}}>
            <div className="form ml-auto">
              <div className="form-group">
                <InputTextField 
                  label="Song Title"
                  onChange={this.onChange}
                  placeholder="Enter song title"
                  value={this.state.title}
                  multiline={false}
                  fullwidth={true}
                />
              </div>
              <div className="form-group">
                <InputTextField 
                  label="Song description"
                  onChange={this.onChange}
                  placeholder="Enter song description"
                  value={this.state.description}
                  multiline={true}
                  rows={3}
                />
              </div>
            </div>
            <input type="submit" className="btn btn-outline-info btn-block" />
          </form>  
        </div>    
      </div>
    )
  }
}```

Please help @apodaka

**Comment by SkyFire2013** [comment]
> You can performe this if you take the name from field and set state using the same name and use just one method.
> i.e.
> 
> ```
> state = {
>   form: {
>     lastName: '',
>     firstName: '',
>   },
> }
> ....
> handleChange = (event) => {
>   const { target: { name, value } } = event;
>   this.setState(() => ({ form[name]: value }))
> }
> ...
> <TextField
>   name="lastName"
>   onChange={this.handleChange}
> />
> <TextField
>   name="firstName"
>   onChange={this.handleChange}
> />
> ```

Thanks men, this really helps me.

**Comment by FerrariF9000** [comment]
01:04:31.792 ENGINE    (W): No module info used, trying to identify -> 0xD57C0000
01:04:31.840 RENDER    (E): GrassMaterialClass: cannot find perlin noise texture (system/textures/perlin.edds)
01:04:31.845 MATERIAL  (E): SMAAEffect area texture not found (system/textures/PP/smaa_area)
01:04:31.845 MATERIAL  (E): SMAAEffect search texture not found (system/textures/PP/smaa_search)
01:04:32.560 SCRIPT       : Compiling Game scripts
01:04:32.561  SCRIPT    (W): @"scripts/GameCode/Effects/SCR_OptimizedMuzzleEffectComponent.c,14": Possible variable name conflict 'inScope'
01:04:32.608  SCRIPT    (W): @"scripts/Game/Editor/UI/Components/Modes/SCR_PhotoSaveModeEditorUIComponent.c,25": Pointer type 'PixelRawData' can only be used with local variables
01:04:32.834  SCRIPT    (W): @"scripts/Game/Campaign/UI/SCR_CampaignUIMutePlayerComponent.c,28": 'GetPlayerBlockedState' is obsolete: Session blocking is no longer supported.
01:04:32.834  SCRIPT    (W): @"scripts/Game/Campaign/UI/SCR_CampaignUIMutePlayerComponent.c,30": 'SetPlayerBlockedState' is obsolete: Session blocking is no longer supported.
01:04:32.834  SCRIPT    (W): @"scripts/Game/Campaign/UI/SCR_CampaignUIMutePlayerComponent.c,35": 'SetPlayerBlockedState' is obsolete: Session blocking is no longer supported.
01:04:32.857  SCRIPT    (W): @"scripts/Game/Components/Damage/SCR_VehicleDamageManagerComponent.c,826": Variable 'geomIndex' is not used
01:04:33.009  SCRIPT    (W): @"scripts/Game/Entities/GridSpawnerEntity.c,180": 'Randomize' is obsolete: If seed need to be used use RandomGenerator instead
01:04:33.094  SCRIPT    (W): @"scripts/Game/Groups/SCR_GroupTileButton.c,683": 'GetPlayerMutedState' is obsolete: Use SocialComponent.IsMuted(playerId).
01:04:33.152  SCRIPT    (W): @"scripts/Game/ScenarioFramework/Actions/AIActions/SCR_ScenarioFrameworkAIActionSetCharacterStance.c,23": 'SetStance' is obsolete
01:04:33.152  SCRIPT    (W): @"scripts/Game/ScenarioFramework/Actions/AIActions/SCR_ScenarioFrameworkAIActionSetMovementType.c,23": 'SetMovementType' is obsolete
01:04:33.249  SCRIPT    (W): @"scripts/Game/UI/HUD/SCR_PlayerListMenu.c,436": 'SetPlayerMutedState' is obsolete: Use SocialComponent.SetMuted(playerId, muted).
01:04:33.249  SCRIPT    (W): @"scripts/Game/UI/HUD/SCR_PlayerListMenu.c,438": 'GetPlayerMutedState' is obsolete: Use SocialComponent.IsMuted(playerId).
01:04:33.249  SCRIPT    (W): @"scripts/Game/UI/HUD/SCR_PlayerListMenu.c,498": 'GetPlayerMutedState' is obsolete: Use SocialComponent.IsMuted(playerId).
01:04:33.250  SCRIPT    (W): @"scripts/Game/UI/HUD/SCR_PlayerListMenu.c,1132": 'GetPlayerMutedState' is obsolete: Use SocialComponent.IsMuted(playerId).
01:04:33.250  SCRIPT    (W): @"scripts/Game/UI/HUD/SCR_PlayerListMenu.c,1135": 'GetPlayerMutedState' is obsolete: Use SocialComponent.IsMuted(playerId).
01:04:33.250  SCRIPT    (W): @"scripts/Game/UI/HUD/SCR_PlayerListMenu.c,1139": 'GetPlayerMutedState' is obsolete: Use SocialComponent.IsMuted(playerId).
01:04:33.314  SCRIPT    (W): @"scripts/Game/UI/Menu/ContentBrowser/MainMenu/SCR_ContentBrowser_AddonsFilteredSubMenu.c,7": 'SetPageItems' is obsolete: Use SetPageSize() instead!
01:04:33.314  SCRIPT    (W): @"scripts/Game/UI/Menu/ContentBrowser/MainMenu/SCR_ContentBrowser_AddonsFilteredSubMenu.c,36": 'SetPageItems' is obsolete: Use SetPageSize() instead!
01:04:33.315  SCRIPT    (W): @"scripts/Game/UI/Menu/ContentBrowser/MainMenu/SCR_ContentBrowser_AddonsSubMenu.c,358": 'SetPageItems' is obsolete: Use SetPageSize() instead!
01:04:33.315  SCRIPT    (W): @"scripts/Game/UI/Menu/ContentBrowser/MainMenu/SCR_ContentBrowser_AddonsSubMenu.c,380": 'SetPageItems' is obsolete: Use SetPageSize() instead!
01:04:33.315  SCRIPT    (W): @"scripts/Game/UI/Menu/ContentBrowser/MainMenu/SCR_ContentBrowser_AddonsSubMenu.c,420": 'SetPageItems' is obsolete: Use SetPageSize() instead!
01:04:33.315  SCRIPT    (W): @"scripts/Game/UI/Menu/ContentBrowser/MainMenu/SCR_ContentBrowser_AddonsSubMenu.c,444": 'SetPageItems' is obsolete: Use SetPageSize() instead!
01:04:33.333  SCRIPT    (W): @"scripts/Game/UI/Menu/GroupSettingsDialogUI.c,37": 'GetPrivilegeAsync' is obsolete: Use SocialComponent.RequestSocialPrivilege() or RequestMultiplayerPrivilege()
01:04:33.370  SCRIPT    (W): @"scripts/Game/UI/Menu/ServerBrowserMenuUI.c,2792": 'GetPrivilegeAsync' is obsolete: Use SocialComponent.RequestSocialPrivilege() or RequestMultiplayerPrivilege()
01:04:33.370  SCRIPT    (W): @"scripts/Game/UI/Menu/ServerBrowserMenuUI.c,2825": 'GetPrivilegeAsync' is obsolete: Use SocialComponent.RequestSocialPrivilege() or RequestMultiplayerPrivilege()
01:04:33.371  SCRIPT    (W): @"scripts/Game/UI/Menu/ServerBrowserMenuUI.c,2850": 'GetPrivilegeAsync' is obsolete: Use SocialComponent.RequestSocialPrivilege() or RequestMultiplayerPrivilege()
01:04:33.408  SCRIPT    (W): @"scripts/Game/Vehicle/SCR_ImpactEffectComponent.c,206": Comparing unrelated types 'Class' and 'Physics'
01:04:33.409  SCRIPT    (W): @"scripts/Game/Vehicle/SCR_ImpactEffectComponent.c,337": Comparing unrelated types 'Class' and 'Physics'
01:04:33.413  SCRIPT    (W): @"scripts/Game/Weapon/Sights/SCR_2DPIPSightsComponent.c,432": 'SetGUIWidget' is obsolete: Use SetRenderTarget(IEntity ent) instead
01:04:33.414  SCRIPT    (W): @"scripts/Game/Weapon/Sights/SCR_2DPIPSightsComponent.c,481": 'SetGUIWidget' is obsolete: Use SetRenderTarget(IEntity ent) instead
01:04:33.415  SCRIPT    (W): @"scripts/Game/Weapon/Sights/SCR_PIPSightsComponent.c,115": 'SetGUIWidget' is obsolete: Use SetRenderTarget(IEntity ent) instead
01:04:33.416  SCRIPT    (W): @"scripts/Game/Workshop/SCR_AddonManager.c,256": 'GetPrivilege' is obsolete: Use SocialComponent.IsPrivilegedTo() or IsMultiplayerAllowed()
01:04:33.416  SCRIPT    (W): @"scripts/Game/Workshop/SCR_AddonManager.c,280": 'GetPrivilegeAsync' is obsolete: Use SocialComponent.RequestSocialPrivilege() or RequestMultiplayerPrivilege()
01:04:34.436 BACKEND      : Loading dedicated server config.
01:04:34.436  RESOURCES    : GetResourceObject @"{0CA1006A8373EA69}Missions/DayZGameMode.conf"
01:04:34.436   RESOURCES (E): Failed to open
01:04:34.436  RESOURCES (E): MissionHeader::ReadMissionHeader cannot load the resource 'Missions/DayZGameMode.conf'!
01:04:39.917 ENGINE       : GameProject load
01:04:39.917  INIT         : GameProject load project data @"C:/Users/19216/Documents/saves/addons/TaskForceMattockUniforms_5CF0C3158AB2337E/TFMattockUniforms.gproj"
01:04:39.917   RESOURCES (E): Wrong GUID/name for resource @"{69A9091E689A6BB4}Language/3RBN_Loc.st" in property "StringTableSource"
01:04:39.918  INIT         : GameProject load project data @"C:/Users/19216/Documents/saves/addons/RayzisOptics_628F720BC527C143/addon.gproj"
01:04:39.918   RESOURCES (E): Wrong GUID/name for resource @"{91C209F9FC805E07}Configs/Localization/RO_localization.st" in property "StringTableSource"
01:04:39.920  INIT         : GameProject load project data @"C:/Users/19216/Documents/saves/addons/WCS_Armbands_61E42AE6714A3CC2/addon.gproj"
01:04:39.920   RESOURCES (E): Wrong GUID/name for resource @"{1FF31851AE8F6625}Language/wcs_armbands_localization.st" in property "StringTableSource"
01:04:39.922  INIT         : GameProject load project data @"C:/Users/19216/Documents/saves/addons/ArmSTALKER2_616A808A84D554BB/addon.gproj"
01:04:39.922   RESOURCES (E): Wrong GUID/name for resource @"{756EB8A0F9E437C2}lokalizations/perevod_main.st" in property "StringTableSource"
01:04:39.922   RESOURCES (E): Wrong GUID/name for resource @"{FA5FFE6AADF9FCA6}localizations/perevod.st" in property "StringTableSource"
01:04:39.922   RESOURCES (E): Wrong GUID/name for resource @"{7DBCE3BBA820FF17}lokalizations/perevod_equipments.st" in property "StringTableSource"
01:04:39.922   RESOURCES (E): Wrong GUID/name for resource @"{A0BBD60B55D15D52}lokalizations/perevod_faction.st" in property "StringTableSource"
01:04:40.858 SCRIPT       : Compiling Game scripts
01:04:40.858  SCRIPT    (E): @"Scripts/Game/UI/Components/EL_ThinSliderWidget.c,18": Overloading event 'OnChange' is not allowed
01:04:40.932  SCRIPT    (W): @"Scripts/Game/Weapon/Attachments/AFW_RangeFinderComponent.c,15": Pointer type 'Animation' can only be used with local variables
01:04:40.963  SCRIPT    (W): @"scripts/GameCode/Effects/SCR_OptimizedMuzzleEffectComponent.c,14": Possible variable name conflict 'inScope'
01:04:40.966  SCRIPT    (W): @"Scripts/Game/Weapon/Sights/RangeFinder/ZeroingTables.c,8": Possible variable name conflict 'offset'
01:04:40.966  SCRIPT    (W): @"Scripts/Game/Weapon/Sights/RangeFinder/ZeroingTables.c,8": Possible variable name conflict 'distance'
01:04:40.974  SCRIPT    (W): @"Scripts/Game/622120A5448725E3/AI/ScriptedNodes/AIGetObstacle.c,12": Pointer type 'Physics' can only be used with local variables
01:04:40.988  SCRIPT    (W): @"Scripts/Game/5ABD0CB57F7E9EB1/Bacon_5ABD0CB57F7E9EB1_FlipUp2DPIPSightsComponent.c,63": Pointer type 'Animation' can only be used with local variables
01:04:41.017  SCRIPT    (W): @"Scripts/Game/Editor/UI/Components/Modes/SCR_PhotoSaveModeEditorUIComponent.c,25": Pointer type 'PixelRawData' can only be used with local variables
01:04:41.022  SCRIPT    (E): @"Scripts/Game/Feature/Quantity/EL_SplitQuantityDialog.c,27": Overloading event 'OnChange' is not allowed
01:04:41.043  SCRIPT    (W): @"Scripts/Game/Vehicle/SCR_WaterEffectModule.c,13": Pointer type 'Physics' can only be used with local variables
01:04:41.043  SCRIPT    (W): @"Scripts/Game/Vehicle/SCR_WaterEffectModule.c,14": Pointer type 'Particles' can only be used with local variables
01:04:41.213  SCRIPT    (E): Can't compile "Game" script module!

Scripts/Game/UI/Components/EL_ThinSliderWidget.c(18): Overloading event 'OnChange' is not allowed
01:06:36.501  SCRIPT    (W): Failed to load

**Comment by FerrariF9000** [comment]
01:04:40.858  SCRIPT    (E): @"Scripts/Game/UI/Components/EL_ThinSliderWidget.c,18": Overloading event 'OnChange' is not allowed
