### ISSUE TITLE
Module '"express-validator"' resolves to a non-module entity and cannot be imported using this construct

### ISSUE THREAD

**Issue by malindap92** [DefinitelyTyped/DefinitelyTyped#10742]
I installed typings for **express-validator** and imported as below but the error **Module '"express-validator"' resolves to a non-module entity and cannot be imported using this construct** is shown
`import * as expressValidator from 'express-validator';`

I even tried to import as below but the same error is returned
`import { ExpressValidator } from 'express-validator';`

Did some digging in the typings code I think the error comes in the following code block
```
// External express-validator module.
declare module "express-validator" {
	import express = require('express');

	/**
	 *
	 * @middlewareOptions see: https://github.com/ctavan/express-validator#middleware-options
	 */
	function ExpressValidator(middlewareOptions?:any):express.RequestHandler;

	export = ExpressValidator;
}
```

I guess the issue is coming from the exporting of the function. Much appreciated if can get this fixed soon.

Thanks 😄

**Comment by llwt** [comment]
To consume an exported function you need to use the following syntax:
```js
import expressValidator = require('express-validator');
```

[related docs](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require)

**Comment by malindap92** [comment]
@llwt I think this works when the TSConfig target is set to ES5 but in the project I'm working in, the target is set to ES6, therefore the import doesn't work as mentioned above. Any thoughts on this issue?

**Comment by llwt** [comment]
@malindap92 Hmm, I'm not sure. It's technically invalid to export a function with the ES6 module loader IIRC, which is why you're getting that error. 

One option is to set `"module": "commonjs"` with `"target": "es6"` to get the compiler to accept that syntax and have it emit `const expressValidator = require('express-validator');`;

Is there a reason you need to emit the ES6 module loading syntax?

**Comment by malindap92** [comment]
@llwt The reason we are setting the target as ES6 is to enable `async / await` for asynchronous programming. We have already exported 'express-validator' as you have mentioned above. Was expecting to export it as `import { ExpressValidator } from 'express-validator'` but I guess it's not a problem.

Thanks for the help 😄

**Comment by arnabmunshi** [comment]
@malindap92  you can write in this way ...
```javascript
import expressValidator from "express-validator";
const { body, validationResult } = expressValidator;
```

**Comment by oceankrish76** [comment]
npm i express-validator@5.3.1


import expressValidator from 'express-validator';
const { check, validationResult } = expressValidator;
