### ISSUE TITLE
Missing `isFocused(): boolean` definition for github-electron

### ISSUE THREAD

**Issue by ccnokes** [DefinitelyTyped/DefinitelyTyped#10768]
- [ x ] I tried using the latest (not the latest but this affects the latest too) `github:DefinitelyTyped/DefinitelyTyped/github-electron/github-electron.d.ts#00b54a3f25f111afd7a6b70b3b56091c5f434129` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @miniak 

Electron.WebContents seems to be missing a definition for `webContents.isFocused`. See https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsisfocused and see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/github-electron/github-electron.d.ts#L3812 where it probably should be. 

Just glancing at the docs, it looks like `isDestroyed` is missing too. I'm still new to TypeScript so let me know if this just my mistake. 

I'm happy to PR that if you'd like. 

Thanks!

**Comment by ccnokes** [comment]
Also it looks like the `Headers` interface (around line 4108) is incorrect. For example:

```javascript

webContents.session.webRequest.onHeadersReceived({ urls: ['*://*.google.com/*'] }, (details, cb) => {
                 //says this is `string` when it's really `string[]`
		let cookieHeaders = details.responseHeaders['Set-Cookie'];
	});
}
```

**Comment by miniak** [comment]
You're right, `webContents.isFocused` was really missing. But `isDestroyed` is there for both BrowserWindow and WebContents.

**Comment by ccnokes** [comment]
@miniak oh must have missed those. Thanks for the quick response!

**Comment by miniak** [comment]
The documentation for https://github.com/electron/electron/blob/master/docs/api/session.md#webrequestonheadersreceivedfilterlistener only says that `responseHeaders` is an object. Isn't it supposed to be a string -> string?

**Comment by ccnokes** [comment]
It is an object of strings : string[], so I think the definition should look like:

```
interface Headers {
		[key: string]: string[];
	}
```

Here's some serialized `details`:
```
"{
    "id": 12,
    "method": "GET",
    "referrer": "",
    "resourceType": "mainFrame",
    "responseHeaders": {
        "Cache-Control": [
            "no-cache,no-store"
        ],
        "Connection": [
            "keep-alive"
        ],
        "Content-Encoding": [
            "gzip"
        ],
        "Content-Length": [
            "15272"
        ],
        "Content-Type": [
            "text/html; charset=utf-8; charset=utf-8"
        ],
        "Date": [
            "Mon, 22 Aug 2016 21:04:28 GMT"
        ],
        "Expires": [
            "Thu, 01 Jan 1970 00:00:00 GMT"
        ],
        "Pragma": [
            "no-cache"
        ],
        "Server": [
            "nginx"
        ],
        "Set-Cookie": [
            "PLAY_FLASH=\"\";Version=1;Path=/;Expires=Thu, 01-Jan-1970 00:00:00 GMT;Max-Age=0;Secure;HttpOnly",
            "redirectUrl=/;Path=/;Secure;HttpOnly"
        ],
        "Vary": [
            "Accept-Encoding, User-Agent"
        ]
    },
    "statusCode": 200,
    "statusLine": "HTTP/1.1 200 OK",
    "timestamp": 1471899869877.868,
    "url": "https://domo.demo.domo.com/auth/index"
}"
```
Note that I am on Electron v1.2.8 so it's possible the latest API is different (probably not but could be worth verifying).

**Comment by miniak** [comment]
Hm, that's weird. I have to check the all the places where the Headers interface is used to avoid breaking other APIs when I fix it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
