### ISSUE TITLE
@types/uuid is not for the uuid module

### ISSUE THREAD

**Issue by dpogue** [DefinitelyTyped/DefinitelyTyped#10766]
The typings file at `@types/uuid` (https://www.npmjs.com/package/@types/uuid) is for a different (unpublished) package than the `uuid` npm package (https://www.npmjs.com/package/uuid).

This is confusing, and the typings should either be moved to `@types/uuid.js` or removed (since there is no npm module that they correspond to).

**Comment by iamolivinius** [comment]
Section "Naming the file" of the contribution guide says: "use the package name as used in the npm package registry."

I'd love to see a name change here, too. 

Does a .d.ts file exist for the uuid module registered on npm?

@staxmanade As the author of `@types/uuid` would you support a name change?

How big would be the impact to users that already rely on `@types/uuid`. (There is no stats section on https://www.npmjs.com/package/@types/uuid)

**Comment by staxmanade** [comment]
I'm all for any cleanup necessary. Feel free to PR the change and merge as necessary.
