### ISSUE TITLE
Moment: error TS2503: Cannot find namespace 'moment'.

### ISSUE THREAD

**Issue by gjuchault** [DefinitelyTyped/DefinitelyTyped#10788]
- [x] I tried using the latest `moment/moment.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

When using Typings (1.3.2), installation creates a nearly empty file because of the two definition files:

```
// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/moment/moment.d.ts
declare var moment: moment.MomentStatic;
```

We should just import moment-node inside moment I guess, as there is not so much usefulness for the two files separation

**Comment by andy-ms** [comment]
Closed by #10805
