### ISSUE TITLE
Duplicate identifiers in angularjs/angular-component-router

### ISSUE THREAD

**Issue by ex37** [DefinitelyTyped/DefinitelyTyped#10781]
- [x] I tried using the latest `angularjs/angular-component-router.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `angularjs/angular-component-router.d.ts`.
  - The authors of that type definition are cc/ @davidreher @vvakame @squadwuschel @calebegg @Huzzle 

Component router redeclares `RouteDefinition` and `ComponentDefinition `, which are already declared in `angularjs/angular.d.ts`. Including both definition files together results many errors like this:
`error TS2300: Duplicate identifier 'component'.`

**Comment by calebegg** [comment]
I don't see definitions for `RouteDefinition` or `ComponentDefinition` in `angularjs/angular.d.ts`:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angularjs/angular.d.ts

Are you sure you're using the latest version of angular.d.ts?

**Comment by ex37** [comment]
Yes, indeed, sorry for confusion, I had an older version of angular.d.ts. For some reason I thought that doing `typings install` updates the typings to the latest version.
