### ISSUE TITLE
node.d.ts not declaring the module "process"

### ISSUE THREAD

**Issue by hriss95** [DefinitelyTyped/DefinitelyTyped#10808]
- [x] I tried using the latest `node/node.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `node/node.d.ts`.
  - The authors of that type definition are cc/ @....

Hello everyone, 

I noticed that node contains a module called "process" which is basically the same as the global variable. If I launch node in the console and type in _require("process")_ I do get the object _process_ as an output. However if I try to _import p = require("process")_ in typescript I get a compile error: _error TS2307: Cannot find module 'process'_ .  Is there a particular reason why this module is not declared in node.d.ts? If not, perhaps it should be created and probably just export a single variable of type NodeJS.Process?

**Comment by hriss95** [comment]
Created a pull request resolving that [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10810)

**Comment by TonyPythoneer** [comment]
@hriss95 or @rbuckton, please close this PR. It had got solved.

**Comment by rbuckton** [comment]
Fixed by #10810.
