### ISSUE TITLE
PDF.js should use pageIndex instead pageNumber

### ISSUE THREAD

**Issue by wellwind** [DefinitelyTyped/DefinitelyTyped#10816]
I am using PDF.d.ts and found current version 1.4.2 of PDF.js use pageIndex not pageNumber.

```typescript
interface PDFPageProxy {

	/**
	 * Page number of the page.  First page is 1.
	 **/
        pageNumber: number;
```

should be

```typescript
interface PDFPageProxy {

	/**
	 * Page number of the page.  First page is 1.
	 **/
	pageIndex: number;
```

**Comment by alejo90** [comment]
According to https://mozilla.github.io/pdf.js/api/draft/display_api.js.html#line681 both are valid, and the difference is that `pageIndex` is 0 based and `pageNumber` is 1 based.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by wellwind** [comment]
pageNumber is right, that's my misunderstanding. thanks.
