### ISSUE TITLE
React.SyntheticEvent has wrong interface

### ISSUE THREAD

**Issue by huan086** [DefinitelyTyped/DefinitelyTyped#10811]
Type definitions for React v0.14

The SyntheticEvent has the signature

```ts
    interface SyntheticEvent<T> {
        ...
        currentTarget: EventTarget;
        ....
        target: EventTarget & T;
        ...
    }
```

which is incorrect. event.target is the HTMLElement that is being clicked on, while event.currentTarget is where handlers has been set. It is impossible for one to know the target (what is clicked on) at compile time, thus specifying `T` makes no sense. The HTMLElement where I attached events is known at compile time, thus `T` can be specified for currentTarget

See https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget

**Comment by alitaheri** [comment]
Seems like this can be closed as it was fixed in #10784 and released as `@types/react v0.14.34`
