### ISSUE TITLE
node: NodeJS.EventEmitter interface lacks methods required of events.EventEmitter class

### ISSUE THREAD

**Issue by BurtHarris** [DefinitelyTyped/DefinitelyTyped#10815]
In the node declarations, it seems like the EventEmitter interface and EventEmitter class have become out of sync so that typescript code which should compile clean generates error TS2352:

repro case::   
    
    /// <reference path="typings/index.d.ts" />
    import {EventEmitter} from 'events';
    const pe = process as EventEmitter;

observed error:

    error TS2352: Type 'Process' cannot be converted to type 'EventEmitter'.
        Property 'prependListener' is missing in type 'Process'.

It seems like this happened when new Node V6 methods on core EvenentEmitter (prependListener, prependOnceListener, and eventName), but in the declaration file these methods were only  only got added to the class declaration in module 'events'.   As a result, attempting to pass the `process` variable to a method expecting a events.EventEmitter generate a typescript error.   

Should these methods be added to both declarations of EventEmitter, or does it make sense to try to eliminate the dual declaration of EventEmitter?

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by BurtHarris** [comment]
I've added a test to node-test.ts demonstrating the issue, and a change to node.d.ts that fixes it for my test case, but that change also breaks a substantial number of other modules.   

I'll submit it as PR  #10888 per @vvakame but it's really **not** ready to be pulled.  I really think the that of both an interface and class **EventEmitter** are defined needs to be addressed.    If everyone had extended from the class, rather than implemented the interface, it wouldn't be a pain to add members.

**Comment by BurtHarris** [comment]
Committed to my branch a full fix which corrects errors generated in other module.

**Comment by BurtHarris** [comment]
Merged into parent
