### ISSUE TITLE
@types/glob: Why is module declaration missing?

### ISSUE THREAD

**Issue by SaschaNaz** [DefinitelyTyped/DefinitelyTyped#10840]
- [x] I tried using the latest `@types/glob` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `@types/glob`.
  - The authors of that type definition are cc/ @vvakame

I tried [`@types/glob` type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/glob/index.d.ts) from NPM but I found that the file misses `declare module "glob"` line. 

```ts
import events = require("events");
import fs = require('fs');
import minimatch = require("minimatch");

declare function G(pattern: string, cb: (err: Error, matches: string[]) => void): void;
declare function G(pattern: string, options: G.IOptions, cb: (err: Error, matches: string[]) => void): void;
/* ... */
```

But the [`glob.d.ts` on the master branch](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/glob/glob.d.ts) have had the line from the start, for years.

```ts
declare module "glob" {

	import events = require("events");
	import fs = require('fs');
	import minimatch = require("minimatch");

	function G(pattern: string, cb: (err: Error, matches: string[]) => void): void;
	function G(pattern: string, options: G.IOptions, cb: (err: Error, matches: string[]) => void): void;
	/* ... */
```

What happened to this file? I cannot do `require("glob")` because of this, is there another way to import the module type without the `declare module` line?

**Comment by vvakame** [comment]
You should use `typescript@beta`. stable version is not support `@types` yet.

**Comment by SaschaNaz** [comment]
@vvakame You're right, but I'm confused about the missing `declare module` thing as `@types/node` still has `declare module`s.

**Comment by vvakame** [comment]
http://goo.gl/i9eyhY this pattern?

**Comment by SaschaNaz** [comment]
Extensibility is a great thing. Thanks for the explanation!

**Comment by SaschaNaz** [comment]
Ah wait wait, so TS 2.0 will enable `require("glob")` even if there is no `declare module` thing with the new `@types` declarations, am I right?

**Comment by vvakame** [comment]
`declare module` is not required.
`@types/xxx` required same format as `--declarations` generated file (in many cases). In my understanding.
