### ISSUE TITLE
dt~react-router-bootstrap Error in [default] Cannot find namespace 'ReactRouter'

### ISSUE THREAD

**Issue by ayxos** [DefinitelyTyped/DefinitelyTyped#10856]
I tried to download the react-router-bootstrap typings definition using typings install dt~react-router-bootstrap --global --save, but my code will still not compile because the ReactRouter referenced by typings/globals/react-router-bootstrap/index.d.ts does not exist.

any idea?

**Comment by vvakame** [comment]
cc/ @blakeembrey

**Comment by ayxos** [comment]
i found the error, i was fetching react-router from npm source instead of using dt source. Now ev works like a charm! mixing sources is not good.
