### ISSUE TITLE
nvd3 is missing 'focus' definition

### ISSUE THREAD

**Issue by zipengwu** [DefinitelyTyped/DefinitelyTyped#10883]
LineChart and StackedAreaChart have focus property and we can control the view finder through it. The current nvd3 is missing 'focus' definition

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by vvakame** [comment]
wow, closed by #10884

**Comment by QuantumInformation** [comment]
These types have become very out of date.
