### ISSUE TITLE
Node Typing Typescript Compile error, TS2304: Cannot find name 'IterableIterator'.

### ISSUE THREAD

**Issue by digital216** [DefinitelyTyped/DefinitelyTyped#10919]
Using the latest Node Definition file `#6.0.0+20160830141956`, the compiler throws a `Typescript Compile error, TS2304: Cannot find name 'IterableIterator'.`  It is coming from a deprecated `NodeBuffer` method (It appears in there 3 times).  Is there another typing file I'm missing, or is this an issue?

**Comment by digital216** [comment]
I found the reference, however I'm not sure if it should be a required thing or not.  The `IterableIterator` is in the `core-js` typing.  My Web API backend does not use `core-js` so it was failing, however my Front End web app (an Angular 2 app) uses it.

**Comment by hewholived** [comment]
This is because of the latest update to node.d.ts and is breaking builds that use ES5 flag in tsc. Can this be fixed asap?

**Comment by Dreampie** [comment]
![image](https://cloud.githubusercontent.com/assets/3667080/18121121/b63f01d0-6f95-11e6-9762-520557321543.png)
![image](https://cloud.githubusercontent.com/assets/3667080/18121135/c31020c4-6f95-11e6-8402-3a5b3539457b.png)

**Comment by alejo90** [comment]
I submitted the pull request. @hewholived I'm sorry for the inconvenience but I believe it to be a fair change, sice the `node.d.ts` addresses node v6 and v6 supports 99% of es 2015. However, maybe a reference to `es6-shim` needs to be included in `node.d.ts` itself? @vvakame @rbuckton

**Comment by rbuckton** [comment]
I would not add a reference to es6-shim. Rather, you can add an empty `IterableIterator<T>` interface as a forward declaration. The empty interface will merge with the definition in lib.es6.d.ts. The node.d.ts file does the same thing with `MapConstructor`.

**Comment by krasevych** [comment]
I have the same problem.
It happened because - I use express.d 
express.d use it - /// <reference path="../express-serve-static-core/express-serve-static-core.d.ts" />
express-serve-static-core.d use it - /// <reference path="../node/node.d.ts" />
node.d it is a v6. but express.d is a v4 and they aren't compatible. If I use node-4.d - it works fine but I should rename manual  from `node-4.d` to `node.d`
Can you fix it?

**Comment by alejo90** [comment]
Thanks @rbuckton

**Comment by hewholived** [comment]
Thanks @alejo90 @rbuckton for the patch. LGTM. Looking forward to seeing it merged into master.

**Comment by BurtHarris** [comment]
Afraid the proposed fix in PR #10943 isn't complete.   Due to the tricky situation, I've prepared a PR #10809  to complete roll-back the change that introduced this.   If #10943 can be fixed, that's OK.

**Comment by alejo90** [comment]
@BurtHarrris thanks for the more thorough testing. I agree, it's worrying that the project wide npm test doesn't catch the issue. I tested it locally as you mentioned and I was able to fix it by making `IterableIterator<T>` extend `Array<T>`. I verified that it works when targetting es2015 too and pushed the fix.

**Comment by shaunluttin** [comment]
I'm receiving this error with the `whatwg-fetch` types with TypeScript Version 2.0.2

```
{
  "name": "my-app",
  "globalDevDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160602141504",
    "whatwg-fetch": "registry:dt/whatwg-fetch#0.0.0+20160829180742"
  }
}
```

```
typings/globals/whatwg-fetch/index.d.ts(19,16): error TS2304: Cannot find name 'IterableIterator'.
typings/globals/whatwg-fetch/index.d.ts(21,13): error TS2304: Cannot find name 'IterableIterator'.
typings/globals/whatwg-fetch/index.d.ts(22,15): error TS2304: Cannot find name 'IterableIterator'.
typings/globals/whatwg-fetch/index.d.ts(23,6): error TS2304: Cannot find name 'Symbol'.
typings/globals/whatwg-fetch/index.d.ts(23,26): error TS2304: Cannot find name 'IterableIterator'.
typings/globals/whatwg-fetch/index.d.ts(88,11): error TS2304: Cannot find name 'ReadableStream'.
```

**Comment by alejo90** [comment]
@shaunluttin I think your issue may be unrelated to this one because this is specific to `node.d.ts`.

@digital216 could you please change the issue name to mention that it's about `node.d.ts`?

**Comment by digital216** [comment]
Done!

**Comment by BurtHarris** [comment]
@shaunluttin, while your issue is similar, it probably deserves a separate bug tracking it because the fix will need to go in a different directory/file, and the errors re `Symbol` and `ReadableStream` have different shim solutions.    Also please include for your case the intended target environment, (browser or node?)

**Comment by shaunluttin** [comment]
@BurtHarris I found a fix. Would you still like me to create a new issue? 
  
Fix:

    .\node_modules\.bin\typings install --save --global dt~core-js

**Comment by BurtHarris** [comment]
Thanks, no probably not.   Did that take care of the reference to ReadableStream?  I don't see it mentioned in that file.

**Comment by vvakame** [comment]
wow, sorry for late. thank you @alejo90 !

**Comment by mikebridge** [comment]
@BurtHarris  ReadableStream is defined in whatwg-streams:

    `typings install dt~whatwg-streams --global --save`

**Comment by piecioshka** [comment]
@digital216 hi there!

I have the same error, but after that command:
```
typings install dt~node --save-dev --global
```
situation was clear.

**Comment by BasieP** [comment]
So now what?

I still have this error, and i don't think i want to run that command on all my projects on the buildserver..
(and i don't like globals anyway)

How about the after-install script of typedoc executes that command (not global)?

**Comment by BurtHarris** [comment]
Just catching up on this, and I've learned more about WHATWG streams in the mean time.

@Basie, `npm install @types/whatwg-streams --save-dev` should probably take care of this for you.
