### ISSUE TITLE
[Types 2.0] node-uuid typings automatically includes its own node.d.ts, causes conflicts

### ISSUE THREAD

**Issue by fluffywaffles** [DefinitelyTyped/DefinitelyTyped#10925]
- [x] I tried using the latest `node-uuid/node-uuid.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

The issue is in the title. It includes its own node.d.ts for some reason, which is out-of-sync with the version I install directly with `npm i @types/node`, and so `tsc` complains.

**Comment by vvakame** [comment]
related #10504
