### ISSUE TITLE
syntax errors in Contacts.d.ts

### ISSUE THREAD

**Issue by olafmat** [DefinitelyTyped/DefinitelyTyped#10935]
- [x] I tried using the latest `cordova/plugins/Contacts.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are @grippstick, @vvakame 

After this merge: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10773 
I have compilation errors in my app.

Used compiler options:
"compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "moduleResolution": "node",
        "isolatedModules": false,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": false,
        "noImplicitAny": true,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true
    },

Errors:
[15:16:16] Starting 'ts'...
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(51,20): error TS1110: Type expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(52,17): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(53,19): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(54,16): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(55,19): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(56,20): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(57,15): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(58,19): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(59,18): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(60,18): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(61,24): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(62,24): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(63,11): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(64,12): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(65,17): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(66,19): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(67,13): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(68,17): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(69,13): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(70,22): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(71,21): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(72,15): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(73,19): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(74,15): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(75,22): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(76,14): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(77,13): error TS1005: ';' expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(78,5): error TS1128: Declaration or statement expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(79,1): error TS1128: Declaration or statement expected.
C:/projects/mitnykredit/bower_components/DefinitelyTyped/cordova/plugins/Contact
s.d.ts(304,5): error TS1110: Type expected.
[15:16:19] TypeScript: 30 syntax errors
[15:16:19] TypeScript: emit succeeded (with errors)
[15:16:19] Finished 'ts' after 2.41 s

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
