### ISSUE TITLE
Number.MAX_SAFE_INTEGER

### ISSUE THREAD

**Issue by JeremyCarlsten** [DefinitelyTyped/DefinitelyTyped#10963]
I don't see Number.MAX_SAFE_INTEGER in the lib.d.ts file. 
Was this excluded for any particular reason? 

Here are the ecma docs on MAX_SAFE_INTEGER
http://www.ecma-international.org/ecma-262/6.0/#sec-number.max_safe_integer

**Comment by vvakame** [comment]
see https://github.com/Microsoft/TypeScript/issues/9937
