### ISSUE TITLE
Definition Request : Leaflet 1.0.0

### ISSUE THREAD

**Issue by Claty** [DefinitelyTyped/DefinitelyTyped#10961]
Hi,

I would be interested in definitions for Leaflet v1.0.0 (currently in rc.3)
[Leaflet 1.0.0 documentation](http://leafletjs.com/reference-1.0.0.html)

I download leaflet/leaflet.d.ts which has a version of 1.0.0 but saw that this was declarations for 0.7.7

Thanks.

**Comment by alejo90** [comment]
@vvakame @mhegazy @andy-ms This issue can be closed now.
