### ISSUE TITLE
Node.d.ts: module 'events' should be usable as EventEmitter type

### ISSUE THREAD

**Issue by BurtHarris** [DefinitelyTyped/DefinitelyTyped#10968]
The sample at https://nodejs.org/dist/latest-v6.x/docs/api/events.html#events_events shows a case where the `EventEmitter` export name isn't used explicitly.   

``` typescript
import EventEmitter = require('events');
class MyEmitter extends EventEmitter {}
const myEmitter = new MyEmitter();
```

This currently generates the message error TS2507: Type 'any' is not a constructor function type.

This is admittedly an odd case, but it seems to be how the (non-typscript specific) Node documentation suggests it should work.   With the patch submitted the above works, but I prefer:

``` typescript
import { EventEmitter } fron 'events';
class MyEmitter extends EventEmitter {}
const myEmitter = new MyEmitter();
```

which (still) works after the patch.   This works at runtime because `EventEmitter === EventEmitter.EventEmitter`.

**Comment by BurtHarris** [comment]
In [typescript  issue 2719](https://github.com/Microsoft/TypeScript/issues/2719) something similar is discussed.   On that thread @ahejlsberg mentioned that its a difficult issue with no clean solution due to differences between CommonJS and ES6 export semantics.    I wonder if this is one of those case.

**Comment by aluanhaddad** [comment]
If you use
```TypeScript
const EventEmitter = require('events');
```
It will never work because you need to use `import` instead of `const` in order to import both the type and value level meanings of a module. 
Then this should work
```TypeScript
declare module "events" {

    namespace EventEmitter { }

    class EventEmitter implements NodeJS.EventEmitter { ... }

    export = EventEmitter;
}
```

**Comment by BurtHarris** [comment]
Your right @aluanhaddad , the example using `const` rather than `import` doesn't get type info, so I've corrected the sample code above to use import.   

The declaration you provided makes __that__ case work, but generates tsc errors many other places where a named export of clase EventEmitter is expected.   Is it possible to get __both__ import styles below to work with the same declaration of module "streams"?:

``` typescript
import * as events from 'events';
class MyEventEmitter extends events.EventEmitter;
````

and

``` typescript
import  EventEmitter  = require('events');
class OtherEventEmitter extends EventEmitter;

````
?

**Comment by BurtHarris** [comment]
@hriss95, have a look.   Is does this cover your concern with EventEmitter?

**Comment by hriss95** [comment]
Hmm, that definitely looks promising. Nice work! I cannot really try it out by tomorrow, but it does look good to me!

**Comment by hriss95** [comment]
Update: It does indeed do the job! Have you created a pull request? I think that a thing which is worth commenting is whether the EventEmitter in module "events" necessarily has the same shape as NodeJS.EventEmitter. That is, events.EventEmitter could contain more properties. Also, I think there is no need to export EventEmitter_Static, you could still access it to be used as a type without exporting it(and I think its a better idea as it is kind of artificial).

**Comment by hriss95** [comment]
@BurtHarris Checking up if you have created a pull request. Otherwise I will do it in a few days, if there is no response here.

**Comment by BurtHarris** [comment]
I'll do so shortly.

**Comment by BurtHarris** [comment]
@hriss95, I'm not sure I understood your input regarding the shape of "events".EventEmitter vs. NodeJS.EventEmitter, so your review of the PR would be valuable.   Other code out there seems to treat these as synonyms, and I thought it best to try to avoid changing that assumption, even if it seems unnecessary to me.

**Comment by levon-gevorgyan** [comment]
Hi guys. I've changed to this 
`
declare module "events" {
    import EventEmitter = NodeJS.EventEmitter;
    export {EventEmitter}
    export default EventEmitter;
}

declare namespace NodeJS {
    export class EventEmitter {
    static listenerCount(emitter: EventEmitter, event: string | symbol): number; // deprecated
        static defaultMaxListeners: number;
        addListener(event: string | symbol, listener: Function): this;
        on(event: string | symbol, listener: Function): this;
        once(event: string | symbol, listener: Function): this;
        removeListener(event: string | symbol, listener: Function): this;
        removeAllListeners(event?: string | symbol): this;
        setMaxListeners(n: number): this;
        getMaxListeners(): number;
        listeners(event: string | symbol): Function[];
        emit(event: string | symbol, ...args: any[]): boolean;
        listenerCount(type: string | symbol): number;
        eventNames(): (string | symbol)[];
        prependListener(event: string | symbol, listener: Function): this;
        prependOnceListener(event: string | symbol, listener: Function): this;
        eventNames(): (string | symbol)[];
    }
    export interface EventEmitterInterface extends EventEmitter{
       new():EventEmitter
       EventEmitter: EventEmitterInterface;
       defaultMaxListeners: number;
    }
   ...
}
`
and seems like working.
