### ISSUE TITLE
@types/webpack lacks webpack-env.d.ts

### ISSUE THREAD

**Issue by jantimon** [DefinitelyTyped/DefinitelyTyped#10978]
Hi 

I would like to use `webpack-env.d.ts` of `@types/webpack` however although the file exists in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/webpack the package does not contain `webpack-env.d.ts`.

```bash
# @types/webpack 1.12.33
ls node_modules/@types/webpack/
 README.md          
 index.d.ts          
 package.json       
 types-metadata.json
```

**Comment by alitaheri** [comment]
Hmmm... even if it does include it, you won't be able to reference it with `/// <reference type=...`

I guess `webpack-env` should become it's own for the sake of simplicity. or atleast, be merged into webpack to make it all easier.

**Comment by jantimon** [comment]
I guess a package on its own would be best as the `webpack` definition is about the *webpack compiler* (node js) and `webpack-env` definition is about the available helpers in the frontend code which will be added by webpack.

**Comment by use-strict** [comment]
As @jantimon said, `webpack-env` should be extracted to a separate package. As far as usage goes, it has the same function as `node.d.ts` and it should be used the same way: e.g. `npm install @types/webpack-env` and then simply using the global `require` in your typescript file. No reference tags needed.

**Comment by use-strict** [comment]
@jantimon , merged.

**Comment by jantimon** [comment]
Cool! 👍
