### ISSUE TITLE
React: Type of props in React.Component

### ISSUE THREAD

**Issue by Elephant-Vessel** [DefinitelyTyped/DefinitelyTyped#11004]
- [x] I tried using the latest `react/react.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `react/react.d.ts`.
  - The authors of that type definition are cc/ @vsiao et al.

I'm using react 15.3.1.

In the constructor of my class that extends React.Component, the props parameter that I actually get contains both `children` and `container`, it's typed at being only the custom user-defined property type `P` while the field `props` is `P & { children?: ReactNode }`.

I see that "React.Props\<T\> is deprecated" and that this means that children is not always available on P by default. Not sure about the background and current state about that, but it seems like the `params` in the constructor always contains both `children` and `container`, where `container` is completely missing from the type def.

**Comment by vsiao** [comment]
A simple fix would be changing the `props` parameter of `constructor` to type `P & { children?: ReactNode }`.

**Comment by Elephant-Vessel** [comment]
Yes, this is not a problem regarding my own code. But shouldn't the class field `props` also contain `container`?

**Comment by Elephant-Vessel** [comment]
Aaaand... If props always is going to contain both of them, I'd probably prefer to write

`constructor(props: React.Props<MyProps>)`
instead of
`constructor(props: MyProps & { children?: ReactNode, container: HTMLElement })`

**Comment by Elephant-Vessel** [comment]
I'm sorry, I just realized that the `container` is not native to React, but is set from [Reactive-Elements](https://github.com/PixelsCommander/ReactiveElements). Sorry for the noise.
