### ISSUE TITLE
Twitter create function is returning Promise<element>

### ISSUE THREAD

**Issue by Thaina** [DefinitelyTyped/DefinitelyTyped#11003]
All these function return `Promise<HTMLElement>`

[createShareButton](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/twitter/twitter.d.ts#L49)
[createFollowButton](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/twitter/twitter.d.ts#L57)
[createHashtagButton](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/twitter/twitter.d.ts#L65)
[createMentionButton](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/twitter/twitter.d.ts#L73)
[createTimeline](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/twitter/twitter.d.ts#L81)
[createTweet](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/twitter/twitter.d.ts#L89)

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by Thaina** [comment]
@vvakame It's too little to fork whole project so I would not like to do. Please just add it to backlog and change it anytimes

**Comment by vvakame** [comment]
I'm not user of that library. I can review incoming PR. 😉 
cc/ @chitoku-k
