### ISSUE TITLE
Leaflet outdated

### ISSUE THREAD

**Issue by rmschots** [DefinitelyTyped/DefinitelyTyped#11012]
In leaflet/leaflet.d.ts, it states to have L.MultiPolyline, while it was replaced in leaflet 1.0-beta1 (July 14, 2015) by L.PolyLine.
Same for L.MultiPolygon.
A lot more changes were probably made in the past year.
Would anyone be so kind to update leaflet to the latest (currently 1.0-rc3 (August 5, 2016))?

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by alejo90** [comment]
@vvakame this issue can be closed now.
