### ISSUE TITLE
Refactor sockjs-client to reflect natural behaviour

### ISSUE THREAD

**Issue by shlomiassaf** [DefinitelyTyped/DefinitelyTyped#11042]
- [ x ] I tried using the latest [socktjs-client/sockjs-client.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/sockjs-client/sockjs-client.d.ts) file in this repo and had problems.
  - The authors of that type definition are:
    @arusakov 
    @mhegazy 

The current implementation is not straight forward.

I'm expecting the definition to reflect a use pattern similar to the one created by TS module.

For example:

```
npm install @types/sockjs-client
```

and 

``` ts
import * as SockJS from 'sockjs-client';

export class MySock {
  url: string;
  sock: SockJS;

  open(): void {
    this.sock = new SockJS(this.url);
  }
}
```

It will error:

```
ERROR in [default] /Users/shlomiassaf/Desktop/Cisco/angular-cli-gui/client/src/app/shared/cli-comm.service.ts:5:8 
Cannot find name 'SockJS'.
```

To fix that I need to use some non usual imports and un natrual behaviour / code.

``` ts
import SockJSClass = __SockJSClient.SockJSClass;
let sockJs: SockJSClass;
```

This is not how a TS build module behave.

> Truth be told could'nt even get it to work with **__SockJSClient** in my angular-cli@webpack project using `@types` but it works in the tests I guess so I won't argue.

If we change the definition files to this:

``` ts
declare module "sockjs-client" {
  export = SockJS;
}

declare class SockJS extends EventTarget {
  constructor(url: string, _reserved?: any, options?: SockJS.Options);

  readyState: SockJS.State;
  protocol: string;
  url: string;
  onopen: (e: SockJS.OpenEvent) => any;
  onclose: (e: SockJS.CloseEvent) => any;
  onmessage: (e: MessageEvent) => any;
  send(data: any): void;
  close(code?: number, reason?: string): void;

  static CONNECTING: SockJS.State;
  static OPEN: SockJS.State;
  static CLOSING: SockJS.State;
  static CLOSED: SockJS.State;
}

declare namespace SockJS {
  interface BaseEvent extends Event {
    type: string;
  }

  interface OpenEvent extends BaseEvent {}

  interface CloseEvent extends BaseEvent {
    code: number;
    reason: string;
    wasClean: boolean;
  }

  interface MessageEvent extends BaseEvent {
    data: string;
  }

  interface SessionGenerator {
    (): string;
  }

  interface Options {
    server?: string;
    sessionId?: number | SessionGenerator;
    transports?: string | string[]
  }

  enum State {
    CONNECTING = 0, OPEN, CLOSING, CLOSED
  }

}
```

No errors and almost natural behaviour.
No more `__SockJSClient.SockJSClass`, `__SockJSClient.OpenEvent` and others...

**Comment by erycson** [comment]
The same problem happens here.

**Comment by kaihenzler** [comment]
+1 same problem

**Comment by BendingBender** [comment]
Tried to do it myself, but the problem is that with the proposed solution one would break all uses of the class constructor without the `new` keyword, something that the current implementation allows. I tried a few things out but couldn't come up with a solution that allows exporting an interface that is both callable and newable and exposes interfaces in a namespace.

Any suggestions welcome.

**Comment by BendingBender** [comment]
Another failed attempt here: #17873
