### ISSUE TITLE
Change return type of jQuery.toArray to be Element[]

### ISSUE THREAD

**Issue by LOZORD** [DefinitelyTyped/DefinitelyTyped#11040]
- [ ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `jquery/jquery.d.ts`.
  - The authors of that type definition are @vvakame @jasonswearingen @johnnyreilly 

It would be more convenient to have the return type of `toArray` be `Element[]` instead of [`any[]`](https://github.com/DefinitelyTyped/DefinitelyTyped/blame/master/jquery/jquery.d.ts#L2784). I'm pretty sure that DOM Nodes (i.e. Elements) are always returned according to the [documentation](https://api.jquery.com/toArray/):

> All of the matched DOM nodes are returned by this call, contained in a standard array

However, I think several projects still use the `any[]` definition (just searched `toArray jquery` in this repo), so there may be a lot of work involved.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by LOZORD** [comment]
PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11098
