### ISSUE TITLE
Incorrect definition of SyntheticEvent<T> in types-2.0/react/index.d.ts

### ISSUE THREAD

**Issue by rohitlodha** [DefinitelyTyped/DefinitelyTyped#11041]
- [ ] I tried using the latest `types-2.0/react/index.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `types-2.0/react/index.d.ts`.
  - The authors of that type definition are @phiresky

```javascript
    interface SyntheticEvent<T> {
        bubbles: boolean;
        currentTarget: EventTarget;
        cancelable: boolean;
        defaultPrevented: boolean;
        eventPhase: number;
        isTrusted: boolean;
        nativeEvent: Event;
        preventDefault(): void;
        isDefaultPrevented(): boolean;
        stopPropagation(): void;
        isPropagationStopped(): boolean;
        persist(): void;
        target: EventTarget;
        timeStamp: Date;
        type: string;
    }
```

should have T with the target
```javascript
    interface SyntheticEvent<T> {
        bubbles: boolean;
        currentTarget: EventTarget;
        cancelable: boolean;
        defaultPrevented: boolean;
        eventPhase: number;
        isTrusted: boolean;
        nativeEvent: Event;
        preventDefault(): void;
        isDefaultPrevented(): boolean;
        stopPropagation(): void;
        isPropagationStopped(): boolean;
        persist(): void;
        target: EventTarget & T;
        timeStamp: Date;
        type: string;
    }
```

**Comment by phiresky** [comment]
Huh. Looks like that was somehow wrongly overwritten by a merge? My commit looked like this: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/084926e23accedcbf700bf480e38abdeabcd971e

**Comment by rohitlodha** [comment]
How can we fix it?

**Comment by phiresky** [comment]
You can submit a pull request. Best also check if any other changes were
reverted, or why it happened

**Comment by phiresky** [comment]
Another relevant commit is a13fa7abf55daedf25b31258b908548f55962c7a

**Comment by phiresky** [comment]
See, https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10811 , https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10784 . Looks like this issue can be closed.
