### ISSUE TITLE
Add GraphQL and Relay

### ISSUE THREAD

**Issue by sibelius** [DefinitelyTyped/DefinitelyTyped#11065]
GraphQL - https://github.com/graphql/graphql-js - https://github.com/nitintutlani/typed-graphql
graphql-relay - https://github.com/nitintutlani/typed-graphql-relay
Relay - https://github.com/graphcool/react-relay-types

**Comment by intellix** [comment]
Create a PR :)

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/graphql
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/graphql-relay
