### ISSUE TITLE
[mongoose][typescript 2.0] @types/mongoose-promise is always installed as dependency

### ISSUE THREAD

**Issue by gitawego** [DefinitelyTyped/DefinitelyTyped#11079]
when use `npm install @types/mongoose --save-dev` to install mongoose definition, the mongoose-promise is always installed as dependency. I just want to use native Promise. the mongoose-promise definition prevents me from using `type MongoosePromise<T> = Promise<T>;`

**Comment by Matthalp** [comment]
+1

**Comment by IOAyman** [comment]
use the following instead:
```ts
import mongoose = require('mongose')
mongoose.Promise = global.Promise
```

**Comment by simonxca** [comment]
@gitawego @Matthalp @IOAyman sorry `mongoose-promise` was removed as a dependency a while ago, but it didn't update for the `types-2.0` branch. I've sent a PR. The updated definitions use `global.Promise` by default so you don't need to do anything else if you're using that.

If you want to use another promise library (q, bluebird, etc.) you can check out: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/mongoose#promises

**Comment by simonxca** [comment]
@mhegazy @horiuchi @vvakame I'm unable to close this issue. Can one of you help?

**Comment by horiuchi** [comment]
@simonxca OK. I close this.

**Comment by joswhite** [comment]
@simonxca Updated link: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mongoose#promises
