### ISSUE TITLE
JQueryXHR and .promise()

### ISSUE THREAD

**Issue by dan-def** [DefinitelyTyped/DefinitelyTyped#11115]
In the latest version of jquery.d.ts there is no support for for calling the promise() function on instances of the jQueryXHR type which you can do in jQuery v3.1.0.

In the jQuery documentation (http://api.jquery.com/Types/#Promise) it states that you should be able to call promise() on promise objects which is not present in the JQueryPromise<T> interface.

**Comment by vvakame** [comment]
cc/ @johnnyreilly

**Comment by johnnyreilly** [comment]
Please submit a PR and we'll review.
