### ISSUE TITLE
[node] constants module exported the quantity of properties isn't consistency with Nodejs

### ISSUE THREAD

**Issue by TonyPythoneer** [DefinitelyTyped/DefinitelyTyped#11136]
Based on interest. I tried to trace #11022.

I used `Object.keys(constants)` to look up the quantity of properties in Nodejs. I got **136**.
But, the definition exports **271** of properties. It's very obviously inconsistency.

So, I am tracing what happened. If I get further information, I will send PR later.

**Comment by hriss95** [comment]
Be careful! As stated in Node's documentation some constants may not be available to some systems. Anyways, the difference in quantity you point out is quite serious.

**Comment by TonyPythoneer** [comment]
@hriss95 Could you help me review #11145 and #11140?

I hope you give me some suggestions. thx.

**Comment by vvakame** [comment]
:eyes:

**Comment by TonyPythoneer** [comment]
Finished #11147 and #11140. Close.
Thanks for @vvakame and @hriss95. :smile:
