### ISSUE TITLE
dns.resolveSrv callback incorrectly typed

### ISSUE THREAD

**Issue by danvk** [DefinitelyTyped/DefinitelyTyped#11151]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/03f3ca4333161dea8c5fa0ba47d55b02da92d40d/node/node-0.12.d.ts#L950

``` ts
export function resolveSrv(domain: string, callback: (err: Error, addresses: string[]) =>void ): string[];
```

The callback is typed as `addresses: string[]`, but it's really an array of objects:

```
interface Address {
  priority: number;
  weight: number;
  port: number;
  name: string;
}
```

See https://nodejs.org/api/dns.html#dns_dns_resolvesrv_hostname_callback

cc @danieljy
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

**Comment by danieljy** [comment]
Worth pointing out that numerous other variants of resolve* are also not properly typed:
resolveMx, resolveTxt, resolveCname

**Comment by vvakame** [comment]
please send a pull request. I'll review it.
