### ISSUE TITLE
@types/jsonwebtoken needs small update

### ISSUE THREAD

**Issue by huineng** [DefinitelyTyped/DefinitelyTyped#11159]
using the latest `index.d.ts` file from @types/jsonwebtoken@7.1.31
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/jsonwebtoken

IT needs to have one line changed  on line 49
headers?: Object; need to be changed to header?: Object;  as per change in jsonwebtoken from v 6.0.0

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by Slonik923** [comment]
This should be closed, since https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11773 was merged.
