### ISSUE TITLE
[lodash] typings vs examples in lodash docs

### ISSUE THREAD

**Issue by rzymek** [DefinitelyTyped/DefinitelyTyped#11170]
I would really like to improve the typings of lodash. The first step in my mind is to make sure all the examples in lodash docs compile with `tsc`.
I've setup some scripts that extract all the examples using `jsdoc` and feed them to `tsc`. Just [a few declarations were needed](https://github.com/rzymek/DefinitelyTyped/blob/types-2.0/lodash/examples/prefix.ts) at the top to make the examples make sense in typescript.
After that [about 60 errors](https://github.com/rzymek/DefinitelyTyped/blob/types-2.0/lodash/examples/RESULTS.md) were left, all concerning the typings, I think. 

I suppose this is a good starting point to make `index.d.ts` more complete and up to date. 
The scripts are kind of a hack using `git`, `make`, `jsdoc` and `node`. Though I'm not really sure how it could/should be integrated with DefinitelyTyped. Currently it goes like this:

1) `git clone [lodash/lodash](https://github.com/lodash/lodash)`
2) run `jsdoc lodash.js -X` to get the documentation in JSON
3) Extract the example code to `examples.ts` wrapping every one in a function
4) Prefix `examples.ts` with [a few declarations](https://github.com/rzymek/DefinitelyTyped/blob/types-2.0/lodash/examples/prefix.ts) of variables and types appearing in the examples
5) Run `tsc examples.ts --pretty`

I'm really looking here for feedback how to properly integrate this flow with this repo.
- [x] I tried using the latest `lodash/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `lodash/index.d.ts`.
  - The authors of that type definition are cc/ @chrootsu @vvakame

**Comment by vvakame** [comment]
It sound good approach.
If we can audit the pull request by the quality tests. 👍 
but we can't running custom script per each library in this repo.

**Comment by rzymek** [comment]
I've moved the automated test to separate repo at https://github.com/rzymek/lodash.d.ts

Current results are at https://github.com/rzymek/lodash.d.ts/blob/master/RESULTS.txt

**Comment by rzymek** [comment]
First PR resulting from these tests: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14947

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
