### ISSUE TITLE
[node.d.ts] stream.Readable and stream.Writable don't have defined eventName

### ISSUE THREAD

**Issue by TonyPythoneer** [DefinitelyTyped/DefinitelyTyped#11182]
According to [stream API - Nodejs](https://nodejs.org/api/stream.html), the document explains that the classes([Class: stream.Writable](https://nodejs.org/api/stream.html#stream_class_stream_writable) & [Class: stream.Readable](https://nodejs.org/api/stream.html#stream_class_stream_readable)) have defined events can be used. I think it needs improvement and adds in the Node.js definition as following:

* [stream.Readable](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/node.d.ts#L2458)
  * [x] [Event: 'close'](https://nodejs.org/api/stream.html#stream_event_close_1)
  * [x] [Event: 'data'](https://nodejs.org/api/stream.html#stream_event_data)
  * [x] [Event: 'end'](https://nodejs.org/api/stream.html#stream_event_end)
  * [x] [Event: 'error'](https://nodejs.org/api/stream.html#stream_event_error_1)
  * [x] [Event: 'readable'](https://nodejs.org/api/stream.html#stream_event_readable)

* [stream.Writable](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/node.d.ts#L2481)
  * [x] [Event: 'close'](https://nodejs.org/api/stream.html#stream_event_close)
  * [x] [Event: 'drain'](https://nodejs.org/api/stream.html#stream_event_drain)
  * [x] [Event: 'error'](https://nodejs.org/api/stream.html#stream_event_error)
  * [x] [Event: 'finish'](https://nodejs.org/api/stream.html#stream_event_finish)
  * [x] [Event: 'pipe'](https://nodejs.org/api/stream.html#stream_event_pipe)
  * [x] [Event: 'unpipe'](https://nodejs.org/api/stream.html#stream_event_unpipe)

---

Other:
* [ http.Server](https://nodejs.org/api/http.html#http_class_http_server)
  * [x] [server.listening](https://nodejs.org/api/http.html#http_server_listening)

Ideally, it needs to add `on` and `once` in the Node.js definition. Besides, it needs to add related tests in the test file.

**Comment by zjiekai** [comment]
Hi, I find [Server.listening](https://nodejs.org/api/http.html#http_server_listening) also missing. Shoud I open a new issue?

**Comment by TonyPythoneer** [comment]
@zjiekai No, you can tell me what porperty is missing. Let me clean up as a list.

**Comment by zjiekai** [comment]
@TonyPythoneer The Server.listening property

**Comment by TonyPythoneer** [comment]
I had send #11214 to fix stream.Readable and stream.Writable.

**Comment by TonyPythoneer** [comment]
I had send #11217 to fix stream.Readable and stream.Writable.

**Comment by vvakame** [comment]
:eyes:

**Comment by TonyPythoneer** [comment]
I had send #11246 PR to add `listening`.

**Comment by TonyPythoneer** [comment]
Close. I solved this issue by myself.
