### ISSUE TITLE
Question : correct process to update typings for the "master" and the “types-2.0” branch

### ISSUE THREAD

**Issue by StefH** [DefinitelyTyped/DefinitelyTyped#11197]
What is the correct process to update typings for the "master" and the “types-2.0” branch:

This project has a “master” branch, and a “types-2.0” branch.

What is the correct process to make a change to a typings file  ?
1]
First create the fix as a PR in the “master” branch and then duplicate the code changes in a new PR on the ”types-2.0″ branch ?

2]
Or create a PR in the “master” branch and also create a PR on the “types-2.0” branch which does a merge ?

3]
Or ?

I could not find this information on the Wiki yet ? Maybe an idea to add something here about the process?

See also my question here : https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/#comment-25535

**Comment by TonyPythoneer** [comment]
Hi @StefH,

There is an issue on #11210 have the same confusion as you. We can move on the follow-up discussion of the issue.

**Comment by tomwanzek** [comment]
FYI you might find some value in reviewing this issue and the responses therein #10711 .

**Comment by andy-ms** [comment]
This is now part of the README: #12070
