### ISSUE TITLE
ObservableArray Subscribe event args not well typed

### ISSUE THREAD

**Issue by alphamax** [DefinitelyTyped/DefinitelyTyped#11203]
- [X] I tried using the latest `knockout/knockout.d.ts` file in this repo and had problems.
- [X] I want to talk about `knockout/knockout.d.ts`.
  - The authors of that type definition are cc/ @vvakame (i think)

Before everything, thanks for all that contributions :)
I just have a remark : there is a missing structure in case of subscribe on an ObservableArray like (see this post)
http://stackoverflow.com/questions/14149551/subscribe-to-observable-array-for-new-or-removed-entry-only?answertab=votes#tab-top

Now you return "T" which is an item but for an array you have a list of structure that indicates what have been added/removed/moved.

Thanks,

**Comment by vvakame** [comment]
cc/ @borisyankov @Igorbek @moonpyk @eSoftware
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/knockout/knockout.d.ts#L3

**Comment by Igorbek** [comment]
It looks like we can improve here. I grabbed this.

**Comment by alphamax** [comment]
You're awsome (and ultra-reactive !)

Thanks again !
