### ISSUE TITLE
Missing/invalid typings in crypto-js

### ISSUE THREAD

**Issue by westy92** [DefinitelyTyped/DefinitelyTyped#11231]
- [x] I tried using the latest `crypto-js/crypto-js.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `crypto-js/crypto-js.d.ts`.
  - The authors of that type definition are cc/ @misak113 @vvakame @Senorsen 

The following should be valid:

``` typescript
import * as crypto from 'crypto-js';

crypto.lib.WordArray.random(32).toString();
// [ts] Property 'lib' does not exist on type 'Hashes'.

crypto.SHA512('derp').toString(crypto.enc.Base64);
// [ts] Supplied parameters do not match any signature of call target.
```

However, the typings do not agree.

My first thoughts are that the `WordArray` typing is missing (see https://github.com/brix/crypto-js/blob/1674e719b04bc7669fb6807756b5ec86cc7f2808/src/core.js#L145) but there is already an interface called `WordArray`.

A quick stab at converting that JS to TS:

``` typescript
interface WordArray {
    words: number[];
    sigBytes: number;
    init(words?: number[], sigBytes?: number): void;
    toString(encoder?: Encoder): string;
    concat(wordArray: WordArray): WordArray;
    clamp(): void;
    clone(): WordArray;
    random(nBytes: number): WordArray;
}
```

What is currently in place:

``` typescript
export interface WordArray {
    iv: string;
    salt: string;
    ciphertext: string;
    key?: string;
}
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by Chandrakala14** [comment]
Is there any solution for this, I am also getting same error ?

**Comment by dhayab** [comment]
@Chandrakala14 for the time being you can do this:

```typescript
((crypto.lib.WordArray as any).random(32) as CryptoJS.WordArray).toString();
```

**Comment by sajadghawami** [comment]
Still no fix? Having the same issue :)

**Comment by misak113** [comment]
I'd like to review your pull requests. It helps everyone to solve this problem ASAP. ;)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
