### ISSUE TITLE
missing: node createSocket: should allow an object as an argument (for options)

### ISSUE THREAD

**Issue by dharmax** [DefinitelyTyped/DefinitelyTyped#11243]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
missing: node createSocket: should allow an object as an argument (for options)

**Comment by TonyPythoneer** [comment]
Could you provide a link to the document?

#11244 , #11245 and this issue are the same questions. Please clean up as an issue and offer a missing list.

**Comment by dharmax** [comment]
@TonyPythoneer, hi!
1. i don't understand what document are you talking about.
2. these are not questions, but three separate bug reports, each of which refer to a missing definition. Do you mean you prefer a single report with the three of these?
