### ISSUE TITLE
[request] gRPC

### ISSUE THREAD

**Issue by pocesar** [DefinitelyTyped/DefinitelyTyped#11264]
Thinking that [gRPC proto definitions](http://www.grpc.io/docs/quickstart/node.html#update-a-grpc-service) files, how hard would to have an interface that acts the same? 

I'm trying to think how packages, services and messages can be created using (nested) interfaces. It would need to be at the same complexity level as the new mongoose typings

**Comment by ngetahun** [comment]
@pocesar Is this issue still open? I would like to work on it.

**Comment by pocesar** [comment]
@ngetahun according to the merged PR in https://github.com/grpc/grpc-node/pull/52 it seems that it's indeed resolved

**Comment by xamgore** [comment]
@pocesar could you close this PR then?
