### ISSUE TITLE
Problem defining interfaces for subdocuments with mongoose

### ISSUE THREAD

**Issue by camilleblanc** [DefinitelyTyped/DefinitelyTyped#11291]
@simonxca 
Following our discussion on thread #10110 

I have another problem with how to declare sub documents.
I have this kind of code:

```
export interface MySubEntity {
	property: string;
	property2: string;
}

export interface MyEntity extends mongoose.Document {
	name: string;
	sub: MySubEntity[];
}

var mySubEntitySchema = new Schema({
  property1: String,
  property2: String
});

var myEntitySchema = new Schema({
  name: String,
  sub: [mySubEntitySchema]
});

export var MyEntityModel: mongoose.Model<MyEntityDocument> = mongoose.model<MyEntityDocument>("MyEntity", myEntitySchema);
```

Now somewhere I have the _id of a MySubEntity, and I have retrieved the MyEntity where it is. 
So to retrieve my sub entity, I'm filtering on the sub array with the _id:

`var mySubSearched = _.find(myEntity.sub, function (sub) { return sub._id == mySubId });`

The problem is: _id is not a property of the interface MySubEntity, but it has one because mongo creates an _id for subdocuments.

So my question is: what is the correct way to declare sub documents?
My first thought was obviously to make the interface MySubEntity to extend mongoose.Document, but then I have another problem somewhere else: when I want to declare in my code a new MySubEntity... well it asks for all the properties of mongoose.Document that are usually created by mongo!

I hope my post is clear enough to understand!
Thanks in advance if you can enlighten me here, I'm really confused now.

**Comment by simonxca** [comment]
@camilleblanc Hmm have you tried: 
```
export interface MySubEntity extends mongoose.Types.SubDocument { ... }
```

Also can you show me the code that causes errors if you use:
```
export interface MySubEntity extends mongoose.Document { ... }
```
And what the error message is? I'll try to reproduce it to see what's going on.

**Comment by camilleblanc** [comment]
@simonxca Sorry for the late reply, I was away.

So the problem is that at one point I need to create a subdocument in my code. So I declare:

`var newSubDoc = <MySubEntity> { property1: "example1", property2: "example2" };`

And if I make MySubEntity extend from mongoose.Document I get the following typescript error:
Type '{ property1: string, property2: string } cannot be converted to type 'MySubEntity'. And then a list of missing properties.

I tried with MySubEntity extending from mongoose.Types.SubDocument as suggested, gives me the same error.

My code works, it's just a typescript issue.

**Comment by simonxca** [comment]
@camilleblanc Unfortunately there's nothing Typescript can do here because above:
```
export interface MySubEntity {
    property: string;
    property2: string;
}

export interface MyEntity extends mongoose.Document {
    name: string;
    sub: MySubEntity[];
}
```
Your declared `sub` to be `MySubEntity[]` and according to the interface of `MySubEntity`, Typescript only knows that each element has `property` and `property2` and nothing else. There's nothing mongoose.Document can do to "add" properties since the type of `sub` is declared explicitly.

Therefore, in `MySubEntity` you must declared the properties of a mongoose subdocument explicitly for Typescript to know it has properties like `_id` etc. The easiest (and probably only) way to do this is:
```
export interface MySubEntity extends mongoose.Document {
    property: string;
    property2: string;
}
```

Which will cause an error in your line:
```
var newSubDoc = <MySubEntity> { property1: "example1", property2: "example2" };
```
Here, this object only has `property1` and `property2` and Typescript will not be able to convert it into an interface that has more properties than `property1` and `property2` because this object will not match that interface.

**Comment by simonxca** [comment]
@camilleblanc What errors do you get if you try this:
```
var newSubDoc = { property1: "example1", property2: "example2" };
```

**Comment by camilleblanc** [comment]
@simonxca Well not typing the newSubDoc var just delays the problem to when I push it into a MyEntity sub list:

`myEntity.sub.push(newSubDoc);`

"Argument of type '{ property1: string, property2: string }' is not assignable to parameter of type 'MySubEntity'.

The other solution I have is simply to add the _id property that I need to the MySubEntity interface. I thought there would be a cleaner way to do.

Thanks for your help anyway :)

**Comment by simonxca** [comment]
@camilleblanc Here are some alternatives you can try:
1) Cast to `any`
```
var newSubDoc = <any> { property1: 'example1', property2: 'example2' };
myEntity.sub.push(newSubDoc);
```

2) Use `mongoose.Types.Array` instead of normal `[]`
```
export interface MySubEntity extends mongoose.Types.Subdocument {
    property: string;
    property2: string;
}

export interface MyEntity extends mongoose.Document {
    name: string;
    sub: mongoose.Types.Array<MySubEntity>;
}
```

3) I don't know which version of Typescript you're using or which IDE you're using, but you could try a different compiler version. On my machine this doesn't cause an error:
```
export interface MySubEntity extends mongoose.Types.Subdocument {
    property1: string;
    property2: string;
}
...
var newSubDoc = <MySubEntity> { property1: "example1", property2: "example2" };
```
I'm using Visual Studio Code with Typescript 1.8.10 / Typescript 2.0.0

**Comment by camilleblanc** [comment]
@simonxca Yes, solution 1 looks like the best way to go for me. I'll go with that for the moment.
Solution 2 doesn't help since I still have the error mentionned in 3) when declaring my newSubDoc.

I'm using Atom 1.9.9 with the atom-typescript package which always uses the last version of ntypescript:
https://github.com/TypeStrong/ntypescript

And thank you for your help! :)

**Comment by simonxca** [comment]
@camilleblanc I forgot to mention in solution 2 you'd declare it as:
```
var newSubDoc = { property1: "example1", property2: "example2" };
instead of
var newSubDoc = <MySubEntity> { property1: "example1", property2: "example2" };
```
But as long as something works that's good :)

**Comment by camilleblanc** [comment]
@simonxca Oh yeah it works, and looks more like the right way to do, since the arrays returned by mongoose.model are of that type (see the example code here:
http://mongoosejs.com/docs/api.html#types_array_MongooseArray.set ) !

Thank you so much

**Comment by camilleblanc** [comment]
@simonxca Ouch, not that easy in the end...
For example this code:

```
import _ = require('lodash');

var subDocsFiltered = _.filter(myDoc.sub, function (sd) { return (sd.property1 == "example") });
```

Now lodash doesn't know mongoose arrays, so subDocsFiltered is considered of type any[], which brings problems further in the code. I have to cast it manually to MySubEntity[].

And since I use lodash a lot, it would make me add manual casting to a lot of places in my code... Not sure if it's worth it :/

**Comment by simonxca** [comment]
@camilleblanc I think this is because of an error in the definitions. Please try this:
Find this line in the definitions and change it:
```
from
class Array<T> extends global.Array {

to
class Array<T> extends global.Array<T> {
```
Let me know if that works for you and if there's anything else causing errors.
If everything works I'll send a PR.

**Comment by camilleblanc** [comment]
@simonxca Totally correct.
It now works perfectly, I don't have to cast anymore.

**Comment by camilleblanc** [comment]
@simonxca Well maybe I spoke a bit too fast.
It all compiles well but now, I have an error when executing some tests, manipulating the new mongoose arrays.
So now since I replaced all my arrays in my interface with mongoose.Types.Array...
I have in MySubEntity a property that is an array of number. So now I put it as a mongoose.Types.Array<number>.

In my test I need to create a new one:

```
var myNewProperty = new mongoose.Types.Array<number>();
myNewProperty.push(1);
```

The execution of this code gives me the following error:
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'caster' of undefined
    at Array._cast (/home/camille/workspace/myproject/node_modules/mongoose/lib/types/array.js:113:24)
    at Array._mapCast (/home/camille/workspace/myproject/node_modules/mongoose/lib/types/array.js:284:17)
    at Object.map (native)
    at Array.push (/home/camille/workspace/myproject/node_modules/mongoose/lib/types/array.js:297:25)
    at /home/camille/workspace/myproject/lib/app/business/myBusiness.js:344:46

I don't get what's wrong with the push method from mongoose Array? I must have missed something here.
Now this has nothing to do with types I'm sorry, but since we started this example here...

**Comment by simonxca** [comment]
@camilleblanc I believe you should not instantiate `new mongoose.Types.Array()` because the constructor is private api: https://github.com/Automattic/mongoose/blob/master/lib/types/array.js#L21

It probably does not work the way you would expect a normal array constructor to work and even if it did, it's highly possible this constructor can change in the future (since it's private) and will break your code.

I may be wrong here, but I think when you declare a schema:
```
var schema = new Schema({
  sub: [Number]
});
```
Mongoose looks at `[Number]` and constructs either an array or a document array for you (depending on the type) and attaches it to your models/documents so that when you access this array, it has all the nice properties and methods mongoose has added for you. 

The TS definitions just provide you with the interface that the array has. (The definitions should probably be changed from classes to interfaces actually).

In your case, since `MySubEntity` is a document, you should probably even be using:
```
interface MyEntity extends mongoose.Document {
  sub: mongoose.Types.DocumentArray<MySubEntity>;
};
```
Would a normal `var myNewProperty: number[] = []` work for you?

**Comment by camilleblanc** [comment]
@simonxca Hmmm I see.
`var myNewProperty: number[] = []` doesn't work for me. I got a typescript error when I do, further in the code `mySubDoc.newProperty = myNewProperty;`
=> Type number[] is not assignable to type 'Array<number>'.

mySubDoc.newProperty is already set and I need it to build the new value, so the only solution I can see would be to make a copy of mySubDoc.newProperty into myNewProperty, empty it and then build its new value... But uffff, it looks ugly!

**Comment by simonxca** [comment]
@camilleblanc If it's not too much trouble, you can do the old `<any>` conversion.
```
var myNewProperty: number[] = [];
mySubDoc.newProperty = <any> myNewProperty;
```
I think it's appropriate here since mongoose changes the type of the array at runtime.

**Comment by camilleblanc** [comment]
@simonxca Ok, I'll go with this then. Not exactly satisfying but looks like I don't have a better choice :)
Thanks again for your help.

**Comment by cyrixmorten** [comment]
Updated these typings today and hit some issues as well.

We are defining or model like this:

```
export interface IProductModel extends IProduct, mongoose.Document {
}

export var Product = mongoose.model<IProductModel>('Product', ProductSchema);
```

Where `IProduct` is shared between server and client containing:

````
export interface IProduct {
  id?: string;
  model: string;
}
````

Resulting in:
````
models/product.ts(160,18): error TS2320: Interface 'IProductModel' cannot simultaneously extend types 'IProduct' and 'Document'.
  Named property 'id' of types 'IProduct' and 'Document' are not identical.
models/product.ts(160,18): error TS2320: Interface 'IProductModel' cannot simultaneously extend types 'IProduct' and 'Document'.
  Named property 'model' of types 'IProduct' and 'Document' are not identical.
```

Wonder why 
1. id is no longer optional
2. model is not allowed (cannot spot what disallows it in the Document definition)

**Comment by simonxca** [comment]
@cyrixmorten 
1) You're right `id` should be optional https://github.com/Automattic/mongoose/blob/master/lib/document.js#L122

2) The `Document` interface corresponds to `function model(...) { ... }` in the source code:
https://github.com/Automattic/mongoose/blob/master/lib/model.js#L3171
For backwards compatibility, we kept using the name `Document`.

This object has a `model()` method that was missing in the previous definitions which is why it worked before, but now there will be a type conflict.

Docs for the `model()` method: http://mongoosejs.com/docs/api.html#model_Model-model
The method is defined here: https://github.com/Automattic/mongoose/blob/master/lib/model.js#L749
And added to `model` here: https://github.com/Automattic/mongoose/blob/master/lib/model.js#L3181
Which is why it's in the `Document` interface.

For your code, if you did `var product = new Product({});`, `product.model;` would be a function so you won't be able to extend `IProduct` whose `model` property is a string.

To verify, if you ran this with Node:
```
var mongoose = require('mongoose');
var schema = new mongoose.Schema({});

var Model = mongoose.model('Model', schema);
var model = new Model({});

console.log(model.model.toString());
```
It would print:
```
function model(name) {
  return this.db.model(name);
}
```

**Comment by simonxca** [comment]
@cyrixmorten I'll add a PR for `id`. But for `model`, I'm not sure what you can do. There is a string property on every `Document` called `modelName` if you can use that.

**Comment by cyrixmorten** [comment]
@simonxca Thank you for the elaborate answer that certainly explains the problem with model. Seems I need to come up with another name for the model entry. 

Would be perfect if id became optional again 👍

**Comment by cyrixmorten** [comment]
@simonxca I'm afraid that `modelName` is not an option either. 

````
server/node_modules/mongoose/lib/schema.js:515
    throw new Error('`' + path + '` may not be used as a schema pathname');
          ^
Error: `modelName` may not be used as a schema pathname
```

Just leaving it here in case others need to rename `model` to something else due to the conflict with Document.

**Comment by cyrixmorten** [comment]
My final solution is to keep `model` within my Schema, then map it to `modelName` when returning results.

````
// IProduct uses 'modelName' to avoid conflict with Document typings
export interface IProductModel extends IProduct, mongoose.Document {}

// ProductSchema sticks with 'model' to avoid `modelName` may not be used as a schema pathname
export var Product = mongoose.model<IProductModel>('Product', ProductSchema);
export default Product;
```

Then either on query or as a toJSON transform, I do: 
````
obj.modelName = obj.model;
delete obj.model;
````

The discrepancy between what is stored in db and what is sent to clients is not ideal, but at least this way I did not need to change the structure of the stored collections.

**Comment by camilleblanc** [comment]
@simonxca 
I'm... back!
I think I found a new issue with the typings. Following my example above:

```
var newEnt = new MyEntityModel();
var newSub = newEnt.sub.create({ property1: "example", property2: "example" });
```

I've got an error on create: Property create does not exist on type Array<MySubEntity>.
But following mongoose doc:
http://mongoosejs.com/docs/subdocs.html

"Sub-docs may also be created without adding them to the array by using the create method of MongooseArrays."

So if I'm not mistaken, my code is correct and shouldn't throw an error here.

**Comment by simonxca** [comment]
@camilleblanc Hmm, what is the type of `newEnt.sub`. It should be `mongoose.Types.DocumentArray` which has a `create` method. In the docs above: http://mongoosejs.com/docs/subdocs.html, if you look at the very top, they define:
```
var childSchema = new Schema({ name: 'string' });

var parentSchema = new Schema({
  children: [childSchema]
});
```
The `childSchema` causes this to be casted into a document array instead of a normal mongoose array.

**Comment by camilleblanc** [comment]
@simonxca Ufff, right. Didn't see there was this document array that is different than mongoose array.
So, I changed my interface to:

```
export interface MyEntity extends mongoose.Document {
    name: string;
    sub: mongoose.Types.DocumentArray<MySubEntity>;
}
```

Now my problem is that create returns an object of type Subdocument that I can't seem to cast to my interface MySubEntity. Shouldn't it return an object of type MySubEntity instead of Subdocument?

`var newSub: MySubEntity = newEnt.sub.create({ property1: "example", property2: "example" });`

`Type 'Subdocument' is not assignable to type 'MySubEntity'.`

**Comment by simonxca** [comment]
@camilleblanc Oops, can you find this in `mongoose.d.ts`:
```
    /*
      * section types/documentarray.js
      * http://mongoosejs.com/docs/api.html#types-documentarray-js
      */
    class DocumentArray<T extends MongooseDocument> extends Types.Array<T> {
      /**
       * Creates a subdocument casted to this schema.
       * This is the same subdocument constructor used for casting.
       * @param obj the value to cast to this arrays SubDocument schema
       */
      create(obj: Object): Subdocument;
    ...
```
Change `Subdocument` to `T`, and see if that works?
If it does then I'll send a PR.

**Comment by camilleblanc** [comment]
@simonxca That works perfectly, thanks :)

**Comment by camilleblanc** [comment]
@simonxca Another possible issue on the typings.
At one point I get the id of a Document as a string, and I need to cast it to an ObjectId. After looking up, I found multiple answers on stackoverflow giving the same solution:

```
var mongoose = require('mongoose');
var objectId = mongoose.Types.ObjectId(stringId);
```

I tested the solution myself, which works. But the typings throw an error:

`Value of type 'typeof ObjectId' is not callable. Did you mean to include 'new' ?`

Adding the new keyword also works and doesn't throw an error.

**Comment by simonxca** [comment]
@camilleblanc `ObjectId` in these definitions is just an alias to mongodb's `ObjectId` as you can see: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/mongoose/mongoose.d.ts#L1097

If you look at the source code for ObjectId here: [ObjectId Source](https://github.com/mongodb/js-bson/blob/master/lib/bson/objectid.js#L28)

```
var ObjectID = function ObjectID(id) {
  // Duck-typing to support ObjectId from different npm packages
  if(id instanceof ObjectID) return id;
  if(!(this instanceof ObjectID)) return new ObjectID(id);
  ...
```

On the 4th line you can see that calling `mongoose.Types.ObjectId(id)` is the same as calling `new mongoose.Types.ObjectId(id)` so you shouldn't have problems with it.

You'll have to ask `mongodb.d.ts` to add it to the definitions. I've tried extending them in `mongoose.d.ts` but couldn't get it to work properly. Might be a bit tricky since `Object(id)` is not in the public api and DefinitelyTyped doesn't want private api in the definitions.

**Comment by camilleblanc** [comment]
@simonxca I see, thanks for the extensive answer. I'll go with `new mongoose.Types.ObjectId(id)` since it's the same.

**Comment by simonxca** [comment]
@camilleblanc actually hold on, I think I found a way to extend it. Look for this in your `mongoose.d.ts`:
```
     /*
      * section types/objectid.js
      * http://mongoosejs.com/docs/api.html#types-objectid-js
      */
    class ObjectId extends mongodb.ObjectID {}
```
And change it to:
```
    /*
     * section types/objectid.js
     * http://mongoosejs.com/docs/api.html#types-objectid-js
     */
    var ObjectId: ObjectIdConstructor;

    type ObjectIdConstructor = typeof mongodb.ObjectID & {
      (s?: string | number): mongodb.ObjectID;
    }

    interface ObjectId extends mongodb.ObjectID {}
```
Let me know if that works and if it causes other issues in your code.

**Comment by camilleblanc** [comment]
@simonxca It works and causes no other issues.
Good job :)

**Comment by iambalajive** [comment]
when i extend mongoose.Document to create my own document interface , i seem to get the **Property 'increment' is missing in type error** . Is this something that recently broke

**Comment by simonxca** [comment]
@iambalajive I don't think so, can you open a new issue and include a code sample that breaks in order to test with?

**Comment by jcyh0120** [comment]
+1 facing this issue when using sub document.

**Comment by maicss** [comment]
Is this a miss defined problem?

![image](https://user-images.githubusercontent.com/9784767/32881780-45fadd22-caed-11e7-82b1-68b1a16d644f.png)

**Comment by maicss** [comment]
And here is another problem, I did search one like this:

![image](https://user-images.githubusercontent.com/9784767/32882299-d99f2ffa-caee-11e7-8bb6-035defffdb02.png)

I did something wrong or `d.ts` defined not properly? Because when I debug in js, it did return a list of blog document.

**Comment by maicss** [comment]
typescript: 2.6.1
mongoose: 4.13.3
@types/mongoose: 4.7.27
node: 9.1.0
OS: Mac OS 10.12.6
```
import mongoose = require("mongoose");
mongoose.Promise = global.Promise;
interface IUser {
  uuid: number
  email: string
  password: string
  displayName: string
}
mongoose.connect('mongodb://localhost:27017/test', {useMongoClient: true});

interface IUserModel extends IUser, mongoose.Document { }

const userSchema = new mongoose.Schema({
  uuid: {type:Number, required: true, index: true, unique: true},
  email: {type: String},
  password: String,
  displayName: String
});

const User = mongoose.model("User", userSchema);

User.insertMany([{uuid: 7, email: "user@appsilon.pl"}])
  .then((d:IUserModel[]) => console.log(d));
```

I got error :
```
Error:(23, 9) TS2345:Argument of type '(d: IUserModel[]) => void' is not assignable to parameter of type '((value: Document[]) => void | PromiseLike<void>) | null | undefined'.
  Type '(d: IUserModel[]) => void' is not assignable to type '(value: Document[]) => void | PromiseLike<void>'.
    Types of parameters 'd' and 'value' are incompatible.
      Type 'Document[]' is not assignable to type 'IUserModel[]'.
        Type 'Document' is not assignable to type 'IUserModel'.
          Property 'uuid' is missing in type 'Document'.
```

**Comment by vschoener** [comment]
I just got the same issue on a new project. Any idea why it breaks? looking deeper in the Document.

**Comment by Narven** [comment]
Don't know if this work...

```
// this will create a MyDocument that does NOT have the increment
type MyDocument = Pick<mongoose.Document, Exclude<keyof mongoose.Document, 'increment'>>
```

then you can do:

```
export interface IUser extends MyDocument({
    firstName: 'string'
    lastName: string,
    createdAt: Date, // this will be automatic generate
    deletedAt: Date // this will be automatic generate
})
```

This is also useful when you have interfaces that define when the `IUserCreated`, `IUserUpdated`, since they need only part of the interface.

type IUserCreated = Pick<IUser, Exclude<keyof IUser, 'deletedAt' | 'createdAt'>>
type IUserUpdated = Pick<IUser, Exclude<keyof IUser, 'deletedAt' | 'createdAt'>>
```

or something like that...

**Comment by rigwild** [comment]
> 1. Use `mongoose.Types.Array` instead of normal `[]`
> 
> ```
> export interface MySubEntity extends mongoose.Types.Subdocument {
>     property: string;
>     property2: string;
> }
> 
> export interface MyEntity extends mongoose.Document {
>     name: string;
>     sub: mongoose.Types.Array<MySubEntity>;
> }
> ```

For anyone that does not want to read the complete thread, this is the solution.

Here is an example to manage subdocuments:
```ts
// Subdocument to be used externally in your app, with no Mongoose references
export interface Homework {
  subject: string
  content: string
  authorId: string
  dueDate: Date
  addedDate?: Date
}

// Document to be used externally in your app, with no Mongoose references
export interface TpGroup {
  name: string
  yearGroup: string
  tdGroup: string
  planningGroup?: string
  remindChannel?: string
  homework: Homework[]
}

// Create the Mongoose document type
// (merge with mongoose.Document and erase `homework` with its Mongoose-array version)
export type TpGroupDocument = TpGroup & mongoose.Document & { homework: mongoose.Types.Array<Homework> }

export const TpGroupModel = mongoose.model<TpGroupDocument>('TpGroup', SchemaObj)
```
