### ISSUE TITLE
[mongoose] Can't use 'new' with extended models (discriminators)

### ISSUE THREAD

**Issue by IOAyman** [DefinitelyTyped/DefinitelyTyped#11323]
- [x] I tried using the latest `mongoose/mongoose.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `mongoose/mongoose.d.ts`.
  - The authors of that type definition are cc/ @simonxca @horiuchi 

**_example code:_**
```ts
...
const base: Model<ibase> = model<ibase>('testfour', baseSchema)
const extended = base.discriminator('extendedS', extendedSchema)
const x = new extended({
  username: 'hi',     // required in baseSchema
  email: 'beddiw',    // required in extededSchema
})
...
```

_**error:**_
```
error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature
```

_**using:**_
```
tsc: v2.0.0
@types/mongoose v4.5.33",
mongoose v4.6.0"
```

**Comment by simonxca** [comment]
@IOAyman I believe this is because the signature of `discriminator()` is wrong. See #10878
Please try finding the `discriminator()` method in the `mongoose/index.d.ts` and change its signature:
```
from:
discriminator(name: string, schema: Schema): T;

to:
discriminator<U extends Document>(name: string, schema: Schema): Model<U>;
```
Let me know if this works for you and I'll send a PR.

**Comment by IOAyman** [comment]
@simonxca Works fine :+1: 

But I applied as proposed in #10878, in which `discriminator()` returns a `ModelConstructor<U>` instead.
