### ISSUE TITLE
[fbsdk] FB.login, Property 'authResponse' does not exist on type 'Object'.

### ISSUE THREAD

**Issue by ycmjason** [DefinitelyTyped/DefinitelyTyped#11327]
Hello all, fbsdk typings seems to have some problem. Should explicitly define the callback response object?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/fbsdk/fbsdk.d.ts#L190

Otherwise in our typescript we can not refer to inner properties of authResponse.

Correct me if I am being silly. Thanks.

**Comment by andy-ms** [comment]
Yes, `Object` is usually the wrong type and it looks like the response has some interesting properties that deserve type declarations. If you want, you could look through the [docs](https://developers.facebook.com/docs/reference/javascript/FB.login/v2.7) and write an `interface FbResponse` to use instead, then submit a PR that fixes this issue. Thanks!
