### ISSUE TITLE
sinon depends of dom when using in non browser environments 

### ISSUE THREAD

**Issue by pleerock** [DefinitelyTyped/DefinitelyTyped#11351]
- I tried using the latest `sinon/sinon.d.ts` file in this repo and had problems.
- The authors of that type definition are cc/ @mrbigdog2u

I'm using sinon on the backend with the latest typescript compiler and have following "lib" configuration in compiler options: `"lib": ["es5", "es6"]`

Unfortunately I have compiler errors, because Sinon is using global DOM objects: [Event](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/sinon/sinon.d.ts#L219) and [Document](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/sinon/sinon.d.ts#L238). So, what to do? I don't want to add "dom" to my lib, Im using it on the backend and don't care about dom stuff.

compiler errors btw:
```
Error:(219, 55) TS2304: Cannot find name 'Event'.
Error:(220, 58) TS2304: Cannot find name 'Event'.
Error:(221, 30) TS2304: Cannot find name 'Event'.
Error:(238, 22) TS2304: Cannot find name 'Document'.
```

**Comment by vvakame** [comment]
good catch.
please check this pattern.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ad537776dbcfa2dd4bfbc32dc87041d649068179/node/node.d.ts#L21-L27
We can use this pattern with this issue.
```
interface Event { }
interface Document { }
```
Could you make a PR?

**Comment by pleerock** [comment]
@vvakame can you take a look? #11453

**Comment by vvakame** [comment]
:+1:
