### ISSUE TITLE
Working on an InboxSDK definition

### ISSUE THREAD

**Issue by rdoursenaud** [DefinitelyTyped/DefinitelyTyped#11357]
[InboxSDK](https://www.inboxsdk.com) is a library to interact with and extend the Gmail UI.

I'm new to the DefinitelyTyped game but I enjoy it so much in my JetBrains IDEs for popular libraries that I decided to give it a go.

If anyone wants to collaborate, please reply and/or @mention me.

**Comment by bplus** [comment]
Any chance this is something that is still happening? I'm just about to give InboxSDK and Typescript a go, which are both new for me.  This would be pretty useful.

**Comment by rdoursenaud** [comment]
@bplus I don't have any customer paying for InboxSDK development at the moment so I've stopped working on the TypeScript definition. That being said, it's almost complete and needs testing. If you're willing to give it a go, you can find it in our fork linked above. Let me know how it works out.

**Comment by shyamal890** [comment]
Would be awesome to have typed definitions for Inboxsdk. I am just guessing since the last update was way back in 2016 there must have been some breaking changes.

**Comment by rdoursenaud** [comment]
@shyamal890 The whole definition has been developed from the InboxSDK documentation and a bit of poking around since the implementation is, AFAIK, closed source.
Fortunately, they include a nice [ChangeLog](https://www.inboxsdk.com/docs/#Changelog) in there that should help you assess the required work.
From my quick glance, there's some deprecated functions and a few new ones but the meat of the definition is still valid.
Feel free to [fork](https://github.com/GPCsolutions/DefinitelyTyped/tree/inboxsdk) and add the missing bits ;)

**Comment by amiram** [comment]
@rdoursenaud I can continue that. I get an error because the function load returns a promise of InboxSDK which is a namespace, and a namespace cannot be returned as a type. Did it work for you in any version of typescript?

**Comment by rdoursenaud** [comment]
@amiram I haven't used it with typescript yet. I merely used it to get autocompletion and type hinting in my JetBrains IDEs which made my work easier. I'll leave the rest to you.

**Comment by amiram** [comment]
@rdoursenaud @shyamal890 @bplus I opened a pull request to DefinitelyTyped to add the types. If you still using the SDK, can you try it before they approve and write your comments?
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26461

**Comment by rdoursenaud** [comment]
@amiram Great! I unfortunately won't have the chance to test it anytime soon but I'll make sure I do when a new InboxSDK project arises.

**Comment by rdoursenaud** [comment]
Just remembered I had posted an announcement on the InboxSDK mailing list. Never had any responses but maybe it would be worth announcing your work there too.
https://groups.google.com/forum/#!msg/inboxsdk/2OQC5sd0E6I/9kBTI02eAAAJ;context-place=forum/inboxsdk

**Comment by rdoursenaud** [comment]
Oh and I just found out that someone (@akopchinskiy) published it on npm : https://www.npmjs.com/package/types-inboxsdk
Maybe you should cooperate.

**Comment by amiram** [comment]
I wonder why it was published without the DefinitelyTyped procedure. It needs to be updated with current docs.

**Comment by FlamesoFF** [comment]
@amiram Maybe because I don't have time to provide docs? I simply published it for convenient work with my project.
p.s. That is my second account.

**Comment by amiram** [comment]
@FlamesoFF I mean the docs of inboxsdk. They were changed since @rdoursenaud created the typings. Do you want to help with my pull request? I saw you made it more structured and with modules which are better than namespace.

**Comment by FlamesoFF** [comment]
@amiram Yes, sure, I can help. But my module structure is not finished yet.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
