### ISSUE TITLE
[types-2.0] Validate D3 version 4 Module Definitions for "strictNullChecks"

### ISSUE THREAD

**Issue by tomwanzek** [DefinitelyTyped/DefinitelyTyped#11365]
This issue is an enhancement request/tracking item pertaining to the TypeScript 2.0 definitions for **D3 version 4 modules** in the **DefinitelyTyped/types-2.0 Branch**.

**The enhancement sought is the module-by-module vetting and updating of the definitions and related tests to ensure they perform with compiler option** `--strictNullChecks`, i.e. determining the need for explicit union types with `undefined`, `null` or both. In some cases, this may require reviewing D3 source code, where the API docs are not explicit.

This is a follow-up open item carried over from the original collaborative development repo [d3-v4-definitelytyped](https://github.com/tomwanzek/d3-v4-definitelytyped)

Specifically, this issue is related to the Definition Request #9936 and the following references:
- [d3-v4-definitelytyped PR 113](https://github.com/tomwanzek/d3-v4-definitelytyped/pull/113) cc @jiemakel
- [d3-v4-definitelytyped Issue 119](https://github.com/tomwanzek/d3-v4-definitelytyped/issues/119) cc @timruffles

For tracking purposes, below is a checklist of the definitions, to be reviewed and updated as necessary:
- [x] d3-array
- [ ] d3-axis
- [x] d3-brush
- [x] d3-chord
- [ ] d3-collection
- [ ] d3-color
- [x] d3-contour
- [ ] d3-dispatch
- [x] d3-drag
- [x] d3-dsv
- [x] d3-ease
- [x] d3-force
- [ ] d3-format
- [ ] d3-geo
- [ ] d3-hierarchy
- [ ] d3-hsv
- [ ] d3-interpolate
- [x] d3-path
- [ ] d3-polygon
- [ ] d3-quadtree
- [ ] d3-queue
- [x] d3-random
- [ ] d3-request
- [x] d3-sankey
- [x] d3-scale
- [x] d3-selection
- [x] d3-selection-multi
- [x] d3-shape
- [x] d3-time
- [x] d3-time-format
- [ ] d3-timer
- [x] d3-transition
- [ ] d3-voronoi
- [x] d3-zoom

PRs to support the completion of this effort are welcome!!! Please ensure the definition authors listed in the header comment are advised of proposed changes before a merge.

cc @gustavderdrache @ledragon

Edit: missing link alias in repo link.
EDIT: Updated completed modules (2016-12-05)
EDIT: Updated completed modules (2016-12-07)
EDIT: Updated (2017-05-02) Added d3-sankey and d3-contour to tracking
EDIT: Updated completed modules (2017-05-13)
EDIT: Updated completed modules (2017-10-12)
EDIT: Updated completed modules (2017-11-04)

**Comment by Ptival** [comment]
@tomwanzek @gustavderdrache @borisyankov

Anyone getting started on fixing this in d3-selection or d3-transition?

Is the solution as simple as adding a ` | null` variant to `BaseType`?

**Comment by tomwanzek** [comment]
I intend to get started on some today. There were some initial proposed changes in a PR to the repo I migrated the definitions from. They were proposed by @jiemakel. I will announce here, when I start working on specific modules and check-off upon completion.

There are a couple of dependencies, I will want to review by the same token. So there is some consistency across definitions, e.g. those with dependencies on d3-selection (and d3-transition).

In general, proposed PRs are more than welcome. Pls simply ensure the authors are @-mentioned for review/approval.

**Comment by tomwanzek** [comment]
I will tackle the following today on my DT fork and start preparing a PR:
* d3-selection
* d3-transition
* d3-selection-multi
* d3-brush
* d3-drag
* d3-zoom

Due to their inherent _Element_ dependencies. Given a chance I will tackle d3-force today or soon thereafter.

If someone, wants to tackle other modules for review/PR, please let me and the authors on the module definitions in question know.

@vvakame could you kindly attach a `help wanted` tag to this thread. Thx!

**Comment by tomwanzek** [comment]
Update: After an initial assessment, I will cycle through JSDoc comments first for the above and submit PRs for those before revisiting `strictNullChecks`.

From a usability perspective, the immediate benefit is bigger and the strict-null checking will entail substantial work to refine the related shape tests.

**Comment by tomwanzek** [comment]
PR submitted for:
* d3-selection
* d3-transiton
* d3-selection-multi
* d3-force

**Comment by tomwanzek** [comment]
Further PR started, covers:
* d3-chord
* d3-path

**Comment by tomwanzek** [comment]
d3-ease submitted as PR.

**Comment by tomwanzek** [comment]
d3-ease complete.

**Comment by denisname** [comment]
I'm interested in having d3-array working in strictNullChecks mode.
Anyone working on it? Otherwise I'm willing to do that.

**Comment by tomwanzek** [comment]
@denisname  I am currently not, I was aiming to tackle **d3-hierarchy** next (incl. its JSDoc comments). Your help would be most appreciated.

cc @gustavderdrache

**Comment by tomwanzek** [comment]
Closed in favor of consolidated tracking issue #23611.
