### ISSUE TITLE
Type of 'onchallenge' connection option might be wrong

### ISSUE THREAD

**Issue by kureta** [DefinitelyTyped/DefinitelyTyped#11363]
- [x] I tried using the latest `autobahn/index.d.ts` file in this repo and had problems.

I guess line 216
`onchallenge?: (session: Session, method: string, extra: any) => OnChallengeHandler;`
should actually be:
`onchallenge?: OnChallengeHandler;`

because the current line is basically a function that takes the same arguments as OnChallengeHandler and returns OnChallangeHandler.

If I ignore this and write my code as if the line was just like what I said everything works perfectly.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by kureta** [comment]
I have sent a [pull request](https://github.com/kureta/DefinitelyTyped/pull/1).

**Comment by vvakame** [comment]
oh, you were send a pull request to your repo!
please send to our repository.

**Comment by kureta** [comment]
I don't know how I managed to do that :) but [here is the new pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11592).

**Comment by michaeljpeake** [comment]
I have a problem with the OnChallengeHandler interface. Namely, if I return a string, my authentication works. If I return a promise, like the typing says I should, it fails.

Should the interface perhaps be `type OnChallengeHandler = (session: Session, method: string, extra: any) => When.Promise<string> | string;`?

**Comment by kureta** [comment]
Do you import When and return When.Promise or do you just return promise. Autobahn uses When promises because it supports progress callback.

**Comment by michaeljpeake** [comment]
I used `When.resolve` as I already have the required token.

**Comment by michaeljpeake** [comment]
I was using `When.resolve(myToken)` as I already have the token. That didn't work. However, just used `import { resolve } from 'when';` and `resolve(myToken)` ... that worked.

**Comment by kureta** [comment]
This is an example of what works for me:

```
onchallange = (session: autobahn.Session, method: string, extra: any) => {
        return When.promise<string>((resolve, reject) => {
            resolve("123secret");
        });
    };
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
