### ISSUE TITLE
Mongoose.d.ts - Missing typing for SchemaType options

### ISSUE THREAD

**Issue by linusbrolin** [DefinitelyTyped/DefinitelyTyped#11399]
- [x] I tried using the latest `mongoose/mongoose.d.ts` file in this repo and had problems.
- [x] I want to talk about `mongoose/mongoose.d.ts`.
  - The authors of that type definition are cc/ @simonxca

The SchemaType class is missing the local options variable.
This gives typing errors when doing something like this:

    let type: SchemaType = new SchemaType('testref', { type: Schema.Types.ObjectId, ref: 'Test' });
    if (type.options && type.options.ref) { // <--- This will cause typing error
      // do stuff
    }

**Comment by simonxca** [comment]
@linusbrolin Thanks!
