### ISSUE TITLE
types-2.0 definitions not compatible with AMD/UMD

### ISSUE THREAD

**Issue by cnshenj** [DefinitelyTyped/DefinitelyTyped#11428]
- [x] I tried using the latest `react/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).

Set "module" to "commonjs" in tsconfig.json, then `import React = require("react")` works fine.
Set "module" to "amd". The compiler complains "Cannot find module 'react'".
`import * as React from "react"` doesn't work either.

**Comment by andy-ms** [comment]
I've filed an issue here: Microsoft/TypeScript#11103.
A quick fix is to add `"moduleResolution": "node"` to your tsconfig.
