### ISSUE TITLE
Mongoose.d.ts - typed Schema definitions and SchemaType options?

### ISSUE THREAD

**Issue by linusbrolin** [DefinitelyTyped/DefinitelyTyped#11439]
- [x] I want to talk about `mongoose/mongoose.d.ts`.
  - The authors of that type definition are cc/ @simonxca

Right now, the definition for Schema and options for SchemaType are just anonymous Objects in mongoose.d.ts.
That's not ideal, since it's impossible to know what options are available and/or required when defining a Schema, or creating plugins that adds options to the SchemaType.

Ideally, the Schema definition should probably have an interface like this:

```
class Schema extends events.EventEmitter {
  constructor(definition?: SchemaDefinition, options?: SchemaOptions);

  add(obj: SchemaDefinition, prefix?: string): void;
}

interface SchemaDefinition {
  [path: string]: SchemaType;
}
```

However, that also forces us to update the SchemaType typings to include typed options, etc.

```
class SchemaType {
  // here we need to add all official parameters (type, ref, etc)
  constructor(path: string, options?: Object, instance?: string); // <-- these options must be typed
}
```

We must then also solve how to show the correct options based on what type is written in the 'type' parameter.
[http://mongoosejs.com/docs/schematypes.html](http://mongoosejs.com/docs/schematypes.html)

For example, if type: Number, then options 'min' and 'max' should be made available.
All the built-in SchemaTypes must be documented in this way.

I'm not entirely sure of what the best approach for doing this would be.
But I thought I could start a discussion about it, since I'm creating a mongoose plugin that has options in the SchemaType object, and I want them to be easily accessed when creating a Schema so no guessing has to be done and no spelling errors be made.

**Comment by simonxca** [comment]
@linusbrolin I think what would help is if we can have some properties specified on an object and still allow declaring arbitrary property names. For example:
```
interface MyObject {
  property1?: string;  // will provide code completion for these properties
  property2?: string;
  ...
  (other properties)   // still allow any other property name
}
```
Though I'm not sure how to do this at the moment. I'm getting an error using: 
```
interface SchemaDefinition {
  [path: string]: SchemaType;
}

Error:
Argument of type '{ title: StringConstructor; author: StringConstructor; body: StringConstructor; comments: { body:...' is not assignable to parameter of type 'MyObject'.
  Property 'title' is incompatible with index signature.
    Type 'StringConstructor' is not assignable to type 'SchemaType'.
```

**Comment by linusbrolin** [comment]
@simonxca yeah I got the same error.
It's because the available parameters are missing in the SchemaType class definition.

That's one of the things we must solve.
SchemaType should probably implement an interface that contains the available properties.
If new properties are added by some plugin, then that plugin should extend the SchemaType class and add the new properties.

**Comment by linusbrolin** [comment]
Or what if we do something like this:

    interface SchemaDefinition {
      [path: string]: SchemaType | ISchemaType | Object;
    }

Where the ISchemaType is the SchemaType interface we create, containing all available properties, and Object being a fallback for anything custom.

**Comment by simonxca** [comment]
@linusbrolin currently a little busy, but I'll take a closer look at this when I get time. Some things to consider:
```
Property 'title' is incompatible with index signature.
```
I believe you'll get this error whenever you have:
```
interface SomeInterface {
  [key: string]: any;
}
...
var someObject: SomeInterface = {
  property1: 'example',  // Property 'property1' is incompatible with index signature.
  property2: 'example'
};
```
I think `property1` must be declared on `SomeInterface` for it not to cause an error. It doesn't accept arbitrary property names. Thing is, the `Object` from `lib.d.ts` does allow arbitrary property names so we'll have to ask Typescript if it's possible to both defined properties that offer code completion and allow arbitrary properties at the same time.

**Comment by simonxca** [comment]
@linusbrolin Also, just want to make sure:
> It's because the available parameters are missing in the SchemaType class definition... SchemaType should probably implement an interface that contains the available properties.

What do you mean by available parameters are missing? Can you give an example of which parameters need to be added if we want `new Schema({title: String})` to not throw an error? I think if the user declared the schema as:
```
new mongoose.Schema({
  title: mongoose.Schema.Types.String
});
```
This would not cause the error `Type 'StringConstructor' is not assignable to type 'SchemaType'.` since your passing in mongoose's version of String now.

In Javascript code, we can also pass in the regular StringConstructor:
```
new mongoose.Schema({
  title: String    // Javascript's native StringConstructor
});
```
So you would at least have to have:
```
interface SchemaDefinition {
  [path: string]: SchemaType | Object;
}
```
To allow both options.

**Comment by simonxca** [comment]
@linusbrolin And I think
```
interface SchemaDefinition {
  [path: string]: SchemaType | ISchemaType | Object;
}
```

Is a good idea. Right now we're running against the problem of `[path: string]` not letting us define arbitrary property names and possibly problems with union types `SchemaType | ISchemaType | Object;`

I'll double-check to see if I can find a way to make it work.

**Comment by linusbrolin** [comment]
@simonxca The error with arbitrary property names should be gone in Typescript 2.0
http://stackoverflow.com/questions/22077023/why-cant-i-indirectly-return-an-object-literal-to-satisfy-an-index-signature-re

However, even in Typescript 1.8, it should still be possible to avoid the errors by explicitly setting the type of the created object:

    let test: SchemaDefinition = { test: String };
    const testSchema: Schema = new Schema(test);

or:

    const testSchema: Schema = new Schema(<SchemaDefinition>{ test: String });

**Comment by linusbrolin** [comment]
@simonxca The 'missing parameters' I was talking about was about this error:

    Type 'StringConstructor' is not assignable to type 'SchemaType'.

Which should be solved with the union type: `SchemaType | ISchemaType | Object;`.
However, it may still require an `any` type aswell to be sure: `SchemaType | ISchemaType | Object | any;`.
But I'm not sure if the `any` type will negate all the others?

**Comment by simonxca** [comment]
@linusbrolin I tried something like this in my editor (VSCode):
```
// mongoose.d.ts
interface Example {
  min: number;
  max: number;
}

class Schema extends events.EventEmitter {
  constructor(definition?: Example | Object, options?: schemaOptions);
  ...
}

// mongoose-tests.ts
var schema = new mongoose.Schema({
  min: 9,
  max: 21
});
```
It didn't give me hints for `Example.min` or `Example.max`. It only gives me hints when the constructor is: `constructor(definition?: Example, options?: schemaOptions);`
Do you get this too?

**Comment by simonxca** [comment]
@linusbrolin Actually I get code completion if I do this:
```
var schema = new mongoose.Schema(<mongoose.Example>{
  min: 9,
  max: 21
});
```
So looks like this might work. I'll try it out when I have time.

**Comment by linusbrolin** [comment]
@simonxca There are docs for the built-in SchemaTypes and their parameters:
http://mongoosejs.com/docs/api.html#schema_Schema.Types

And the docs for the same thing for VirtualTypes:
http://mongoosejs.com/docs/api.html#schema_Schema-virtual

**Comment by linusbrolin** [comment]
@simonxca I went through the base SchemaType parameter docs and I think the interfaces for those may look something like this:

    interface IndexOptions {
      background: boolean,
      sparse: boolean,
      type: string,
      unique: boolean,
      expires: string
    }

    interface ValidateOptions {
      validator: RegExp | Function,
      msg?: string,
      type?: string
    }

    interface SchemaTypeOptions<T> {
      type: T,
      default: () => T | T,
      get: (value: T, schematype?: this) => T,
      index: IndexOptions | Object | boolean | string,
      required: (required: boolean, message?: string) => T | boolean | string,
      select: boolean,
      set: (value: T, schematype?: this) => T,
      sparse: boolean,
      text: boolean,
      unique: boolean,
      validate: (obj: RegExp | Function, message?: string, type?: string) => T | ValidateOptions | ValidateOptions[]
    }

**Comment by simonxca** [comment]
@linusbrolin nice, thanks for gathering those up. I've found something that might work. I put it in the next comment. Below I'll just show what I've tried and how I got to my proposed solution.
Here's what we have so far:
```
var schema = new mongoose.Schema({
  random_property1: Number,
  random_property2: {
    type: Number,
    required: true
  },
  random_property3: mongoose.Schema.Types.Number,
  ...
};
```
The corresponding interface to the schema definition above would be:
```
interface SchemaDefinition {
  [path: string]: SchemaTypeOptions<T> | Constructor | SchemaType;
}
```
**1)** In `SchemaTypeOptions<T>`, we can't define `T` anywhere. Doing `SchemaDefinition<T> {...}` doesn't make sense since we can have different types for `SchemaTypeOptions<T>` (`SchemaTypeOptions<number>`, `SchemaTypeOptions<string>`, etc.). Also `[path<T>: string]` or `[path: string]<T>` doesn't work.

**2)** There is no `Constructor` type. We would have to use `Object` to represent the different constructors (`Number`, `String`, etc). Resulting in:
```
interface SchemaDefinition {
  [path: string]: SchemaTypeOptions | Object | SchemaType;
}
```
I believe we will lose autocompletion if we use `type1 | Object | type2`. We would also lose the nice generic type offered by `SchemaTypeOptions<T>`.

**3)** I'm assuming schemas that don't apply the plugin will not have requirements in the schema definition. In other words: 
```
var NormalSchema = new mongoose.Schema({
  // no requirements, just regular Object
});

var PluginSchema = new mongoose.Schema({
  required1: ...,
  // other properties
});
PluginSchema.plugin(plugin, ...);
```
So changing the constructor:
```
// mongoose.d.ts
type SchemaDefinition = Object;    // default type

class Schema extends events.EventEmitter {
    constructor(definition?: SchemaDefinition, options?: SchemaOptions);
    ...
}

// plugin.d.ts
interface SchemaDefinition {
  required1: ...,
  [path: string]: ...
}

declare module 'mongoose' {
  type SchemaDefinition = Object | {
    reuired1: ...
  };   // need | or else all schemas will have the requirement 
}      // regardless if they're using the plugin
```
Will cause us to lose autocompetion if we use `|`.

**Comment by simonxca** [comment]
@linusbrolin What we **can** do however is have optional type inference. So we would keep:
```
class Schema extends events.EventEmitter {
    constructor(definition?: Object, options?: SchemaOptions);
    ...
}
```
Where `Object` would cover all the different types we could use for the definition.
When defining the schema, we can do this:
```
import {
  Schema,
  SchemaTypeOptions as Options
} from 'mongoose';

var UserSchema = new Schema({
  username: <Options<string>> {
    type: String,
    required: true,
    unique: true
  },
  ...
});
```
You can define the type for each property individually and it will give you autocompletion for `type, required, unique, sparse, etc.`, whatever is in `SchemaTypeOptions<T>`. This will allow you to have:
```
interface NumberOptions extends SchemaTypeOptions<number> {
  min?: number;
  max?: number
}

var UserSchema = new Schema({
  age: <NumberOptions> {
    type: Number,
    min: 13,
    max: 100
  },
  ...
});
```
Which will give you autocomplete for `min`, `max`. You can create your own Schema Type interface for your plugin by extending `SchemaTypeOptions<T>`.

Now suppose your plugin has some required path. You can define and use and interface for it like this:
```
interface PluginSchemaDefinition {
  required1: ...;
  [path: string]: any;
}

import {
  PluginSchemaDefinition as PluginDef,
  SchemaTypeOptions
} from 'mongoose';

var UserSchema = new Schema(<PluginDef>{
  required1: ...,
  username: <SchemaTypeOptions<string>> {
    type: String,
    unique: true,
    ...
  },
  ...
}
```
This will give autocompletion for `required1` as well as all the options for the `username` property. If `required1` is not present in the schema definition, Typescript will throw an error.

This is the best I've found so far. Do you think it would work?

**Comment by linusbrolin** [comment]
The only problems I see with that solution are:
1: It will force everyone to use casting on every line in every schema if
they want any intellisense. Not an optimal solution but if it is the only
working one so far then it's worth doing. But I would prefer avoiding
'Object' as default anywhere possible. It kinda defeats the purpose of
having typings. But as I said, we should use what works.
2: What if a plugin adds options that can/should be used on any available
type? How can those added options be injected to all other
SchemaTypeOptions?
Manually extending every single SchemaTypeOptions interface is not an
option, since it is not future proof nor does it cover any other plugins
options.

Den fre 7 okt. 2016 18:52Simon Xiong <notifications@github.com> skrev:

**Comment by simonxca** [comment]
@linusbrolin Thanks for your feedback, these are good points. I think I found something that might work: https://github.com/simonxca/DefinitelyTyped/blob/schema-type-options/mongoose/mongoose.d.ts#L717

You can give it a try [here](https://raw.githubusercontent.com/simonxca/DefinitelyTyped/schema-type-options/mongoose/mongoose.d.ts).

1) Try creating a new schema and see if the intellisense works properly. Since we're using:
```
interface SchemaDefinition {
  [path: string]: SchemaTypeOptions<any>;
}
...
class Schema extends events.EventEmitter {
  /**
   * Schema constructor.
   * When nesting schemas, (children in the example above), always declare
   * the child schema first before passing it into its parent.
   * @event init Emitted after the schema is compiled into a Model.
   */
  constructor(definition?: SchemaDefinition, options?: SchemaOptions);
  ...
```
This should provide intellisense without any casting required:
```
new mongoose.Schema({
  username: {
    type: String,
    unique: true,
    ...
  }
});
```
If you needed the type parameter in `SchemaTypeOptions<T>`, then you can optionally cast:
```
username: <SchemaTypeOptions<string>>{
  type: String,
  unique: true,
  ...
}
```
You can also define additional `SchemaTypeOptions` by extending:
```
interface SchemaTypeNumberOptions extends SchemaTypeOptions<number> {
  min?: number;
  max?: number;
}
```
But these are ultimately optional if you really want the extra type-checking.
Surprisingly stuff like this still works:
```
new mongoose.Schema({
  username: String,
  age: mongoose.Types.Number
  ...
});
```
So using `SchemaDefinition` instead of generic `Object` is viable.

2) Interfaces can be defined multiple times so if a plugin wants to add an attribute to every `SchemaTypeOption` it can do this:
```
declare module "MyPlugin" {
  interface SchemaTypeOptions<T> {
    property1: T;
    property2: T;
    ...
  }
}
```
If it wants to add an extra attribute to `SchemaDefinition` it can do this:
```
declare module "MyPlugin" {
  interface SchemaDefinition {
    property1: ...;
    property2: ...;
    ...
  }
}
```
And these should start appearing in the intellisense if the user has installed the plugin definitions.

**Comment by linusbrolin** [comment]
@simonxca as far as I can tell, this solution seems to be working.
My plugin has SchemaTypeOptions that should be possible to use on any SchemaType.
In order for that to work, I had to extend the mongoose module, like this:

    declare module "mongoose" {
      interface SchemaTypeOptions<T> {
        myOption1: 'stringLiteral1' | 'stringLiteral2';
        myOption2: 'stringLiteral1' | 'stringLiteral2' | 'stringLiteral3';
      }
    }

The only problem I've had is that I can't get intellisense working with those string literals.
When defining a Schema, I get intellisense for the added options, and in the intellisense tooltip for each option I do get the string literal types.
But the string literal types do not show up as alternatives when using ctrl+space or when writing the options.
I've also tried using enums instead, but with the same result.

I really doubt that issue has anything to do with these typings, but it would still be nice to be able to solve it. :)

**Comment by simonxca** [comment]
Just an FYI, planning to get this done, but currently busy with school. Will be about 2 weeks before I have time to work on this.

**Comment by normdoow** [comment]
Hey @simonxca , I'm having issues with declaring an array of objects in a Mongoose schema. trying to follow what you mentioned here. Updating the SchemaTypeOptions types to handle my object but I'm still getting an error. Would you be able to point me in the right direction here? Thanks!
![image](https://user-images.githubusercontent.com/21371266/100827835-8926a900-3412-11eb-9da9-766b463889d1.png)
![image](https://user-images.githubusercontent.com/21371266/100827847-8fb52080-3412-11eb-8c99-1b76716e6e7b.png)

**Comment by normdoow** [comment]
I think I got it working by doing this. pretty sure it loses the typing but Im ok with that.
```
let SiteModel = model<Site>('Site', new Schema({
    name: String,
    domain: String,
    notionUrl: String,
    prettyUrls: [{ notionUrl: String, prettySlug: String} as SchemaTypeOptions<any>],
    isDNSConnected: {
        type: Boolean,
        default: false
    } as SchemaTypeOptions<any>,
    customFont: String,
    imageUrl: String,
    favIconUrl: String,
    description: String,
    scriptSnippetUrl: String
}))```

**Comment by jarcko** [comment]
Resolved the issue by donwgrafing the version to:
```
"dependencies": {
  ...
   "mongoose": "5.10.2",
  ...
},
"devDependencies":{
  ...
  "mongoose": "5.10.2",
  ...
}

dependencies: {
  
}
```
