### ISSUE TITLE
Question: track number of downloaded definition

### ISSUE THREAD

**Issue by CBaptiste** [DefinitelyTyped/DefinitelyTyped#11434]
Hello,

Is it possible to track down somewhere the number of downloaded definitions for a specific folder ?

Let me know :) That would be a huge help !

Baptiste

**Comment by vvakame** [comment]
cc/ @Bartvds @blakeembrey ?

**Comment by blakeembrey** [comment]
Are you after how many people are using a definition? I have analytics for Typings API requests, but there's many other ways the definition may be downloaded. I don't think GitHub has a way to access the specifics.

**Comment by CBaptiste** [comment]
Yes exactly, I want to know when people do a `typings install` or `tsd install`. The analytics you are talking about sounds good :) 
How can I use it ? Can't find documentation about it

Let me know !

**Comment by CBaptiste** [comment]
any indication on how to use the analytics api ? @blakeembrey 

Thank a lot !

**Comment by Bartvds** [comment]
@CBaptiste TSD has rudimentary build-in Google Analytics, it (anonymously) tracks which commands are run and which definitions get installed.

**Comment by CBaptiste** [comment]
thx @Bartvds, I would need to use tsd as a module, but I can't find the right way to use the analytics feature

Any idea ?

Baptiste

**Comment by Bartvds** [comment]
The analytics aren't readable through TSD module but stored in regular online Google Analytics.

What is your use-case for this?

**Comment by CBaptiste** [comment]
Hello @Bartvds, thx for the answer. I just want to evaluate/quantify the traffic on algoliasearch-client-js. (and to have an estimation of people using angular 2 with Algolia)

what do you think ?

**Comment by Bartvds** [comment]
@CBaptiste for this month I see five install of `algoliasearch-client-js/algoliasearch-client-js.d.ts`, and a few searches:

![algolia](https://cloud.githubusercontent.com/assets/685984/18952390/b3cd76aa-8649-11e6-9074-8dc55150bfef.png)

As this definition is for a very specific this isn't terribly shocking, maybe look into NPM's stats for actual code downloads.

**Comment by CBaptiste** [comment]
must be me haha

Thanks a lot !
