### ISSUE TITLE
Redux-devTools test uses wrong version of devTools.

### ISSUE THREAD

**Issue by stephtr** [DefinitelyTyped/DefinitelyTyped#11458]
tsconfig.json includes index.d.ts and redux-devtools-2.1.4-tests.tsx. redux-devtools-2.1.4-tests.tsx uses index.d.ts instead of redux-devtools-2.1.4.d.ts. It seems like redux-devtools-2.1.4-tests.tsx should test redux-devtools-2.1.4.d.ts and redux-devtools-tests.tsx tests index.d.ts, which is not the case.
One difference between those two versions is, that using one createDevTools returns Function, while the other one returns IDevTools.
Why are there to different versions and why isn't redux-devtools-tests.tsx used as standard test?
( @RyanCavanaugh made the relevant change in tsconfig.json)

**Comment by xStrom** [comment]
This seems incorrect indeed. I think `tsconfig.json` should use `redux-devtools-tests.tsx`.

**Comment by stephtr** [comment]
Fixed sitz #11602
