### ISSUE TITLE
[request] synaptic, a neural network library

### ISSUE THREAD

**Issue by Hongbo-Miao** [DefinitelyTyped/DefinitelyTyped#11462]
Synaptic is an architecture-free neural network library for node.js and the browser
https://github.com/cazala/synaptic

Check the website, it is quite amazing! http://caza.la/synaptic/#/

**Comment by ToastHawaii** [comment]
Pull request for the types [https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12185](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12185)

**Comment by ToastHawaii** [comment]
Type definition for synaptic is now available and can found here 
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/synaptic

Download it manually or install it via npm or nuget.

npm: npm install --save @types/synaptic
nuget: Install-Package synaptic.TypeScript.DefinitelyTyped

Feel free to give feedback or make changes by yourself.

**Comment by Hongbo-Miao** [comment]
Thanks @ToastHawaii !
