### ISSUE TITLE
restify extends http.ServerRequest; which is no longer imported by node?

### ISSUE THREAD

**Issue by SamuelMarks** [DefinitelyTyped/DefinitelyTyped#11488]
- [x] I tried using the latest `restify/restify.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `restify/restify.d.ts`.
  - The authors of that type definition are cc/ @toefraz @rundef

Upgraded my typings.json from:

    registry:env/node#6.0.0+20160825160117

To:

    registry:env/node#6.0.0+20160918225031

(with `"restify": "registry:dt/restify#2.0.0+20160919061041"`)

And got this error (referring to [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3e403832f65f64c1ad1b2e29e4e520838519e14b/restify/restify.d.ts#L38)):

    Error:(32, 34) TS2305: Module '"http"' has no exported member 'ServerRequest'.

**Comment by andy-ms** [comment]
This was likely broken by #11133. Could you send a PR to update `restify` to use the new `IncomingMessage`?

**Comment by SamuelMarks** [comment]
@andy-ms - Found it, was removed on this commit:

https://github.com/types/env-node/pull/35/files#diff-454ff0a7aff1da6588b816d269cf7ff9L321

**Comment by SamuelMarks** [comment]
Not sure if you do any whole-repository changes, but I ran `sed`:

    find -type f -exec sed -i 's/http.ServerRequest/http.IncomingMessage/g' {} \;

And got `git status` of:

	modified:   acl/acl.d.ts
	modified:   applicationinsights/applicationinsights.d.ts
	modified:   browser-sync/browser-sync.d.ts
	modified:   bufferstream/bufferstream.d.ts
	modified:   busboy/busboy-tests.ts
	modified:   express-serve-static-core/express-serve-static-core.d.ts
	modified:   formidable/formidable-tests.ts
	modified:   multiparty/multiparty-tests.ts
	modified:   multiparty/multiparty.d.ts
	modified:   on-headers/on-headers-tests.ts
	modified:   restify/restify.d.ts
	modified:   urlrouter/urlrouter.d.ts
	modified:   ws/ws-tests.ts

Do you want 12 PRs @andy-ms ?

**Comment by andy-ms** [comment]
1 is fine. I am curious about why we have node definitions in both DefinitelyTyped and in `types/env-node`. Errors like this will be common if they stay out-of-sync.
