### ISSUE TITLE
cropperjs.d.ts not compatible with last version of cropperjs library

### ISSUE THREAD

**Issue by peterpeterparker** [DefinitelyTyped/DefinitelyTyped#11482]
Hi,

The cropperjs.d.ts isn't compatible with the last version of cropperjs library, see following post for references:

```
 https://github.com/fengyuanchen/cropperjs/issues/94#issuecomment-249396533
```

Therefore could we update the definition file like following to resolve that issue:

```
 declare module "cropperjs" {
     const Cropper: typeof cropperjs.Cropper;
     export default Cropper;
 }
```

instead of

```
 declare module "cropperjs" {
     const Cropper: typeof cropperjs.Cropper;
     export = Cropper;
 }
```

Thx in advance

**Comment by andy-ms** [comment]
Please make a PR.

**Comment by peterpeterparker** [comment]
@andy-ms, I tried but can't push my local branch >

git push origin Fix11482

fatal: unable to access 'https://github.com/DefinitelyTyped/DefinitelyTyped.git/': The requested URL returned error: 403

**Comment by andy-ms** [comment]
Hi @peterpeterparker, you don't have permissions to directly make changes to this repository. But you can still make a pull request from your own fork. More info [here](https://help.github.com/articles/fork-a-repo/).

**Comment by peterpeterparker** [comment]
Thx. Done:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11490

**Comment by WoMayr** [comment]
It looks like this commit got lost in this PR #11739

**Comment by andy-ms** [comment]
I installed `cropperjs@1.0.0-beta` and still `node -p 'require(\"cropperjs\").default'` is `undefined`.

**Comment by peterpeterparker** [comment]
@vvakame @stepancar could I ask you why  #11490  isn't merged anymore in the master branch respectively why that change you merged was removed?

**Comment by andy-ms** [comment]
See the [README](https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default) about default exports.

**Comment by sosnet** [comment]
But how to import this lib to an Ionic2/Angular2 project and how to use the Constructor? I tried so many different solutions, but none of them worked.. Always getting `TypeError: cropperjs_1.default is not a constructor`

See: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11482 and https://forum.ionicframework.com/t/image-cropping-plugin/51206/77?u=sosat

Thanks

**Comment by andy-ms** [comment]
Try [`import = require()`](http://www.typescriptlang.org/docs/handbook/modules.html).

**Comment by sosnet** [comment]
Wow, thanks!
`import Cropper = require('cropperjs');` did it.

**Comment by peterpeterparker** [comment]
thx @andy-ms for the explanation

I installed both last version of cropperjs and types in my Ionic v2 project and everything went fine, respectively code is still compiling and functionnalities is still working.

Therefore, since I opened that task, I allow my self to close it. 

If someone would face the same problem I had, see both linked REAME or Ionic forum post.

**Comment by gosp** [comment]
Hi, the issue reproduces because the modification was lost??
I just create a PR: [#17929](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17929)
