### ISSUE TITLE
[c3/c3.d.ts] Why is data.onselected, onunselected, etc commented out? 

### ISSUE THREAD

**Issue by hisham** [DefinitelyTyped/DefinitelyTyped#11493]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/). 
- [x] I want to talk about `c3/c3.d.ts`.
  - The authors of that type definition are cc/ @martinduparc @rbanderton @vvakame 

These lines are commented but they are valid calls. 

```
// onselected?: any;
// onunselected?: any;
// ondragstart?: any;
// ondragend?: any;
```

See http://c3js.org/reference.html#data-onselected

**Comment by andy-ms** [comment]
The file was added a year ago with these lines commented out and they haven't been touched since then. Maybe they were simply left out. You could make a PR to add typings for these (something better than `any`).

**Comment by hisham** [comment]
Ok done and pull request created - see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11496
