### ISSUE TITLE
google-maps typing has incorrect type for `google.maps.Map` in callback

### ISSUE THREAD

**Issue by nertzy** [DefinitelyTyped/DefinitelyTyped#11509]
- [x] I tried using the latest `google-maps/google-maps.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `google-maps/google-maps.d.ts`.
  - The authors of that type definition are cc/ @DeividasBakanas @RyanCavanaugh

When you call `GoogleMapsLoader.load`, you pass in a callback, as defined in google-maps/google-maps.d.ts.

The callback type is wrong. The typings file says that `GoogleMapsLoader.load` takes a callback function whose only parameter is the "google" object, and that the "google" object has type:

``` typescript
        (google: { maps: { Map: google.maps.Map } }): void;
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f82ccb560ec3b966fa571384047e27152cfed391/google-maps/google-maps.d.ts#L10

This line is wrong, saying that `google.maps.Map` is a Map instance. `google.maps.Map` is actually the Map constructor function.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.
