### ISSUE TITLE
google-maps typing does not list all properties of `google.maps` object

### ISSUE THREAD

**Issue by nertzy** [DefinitelyTyped/DefinitelyTyped#11512]
- [x] I tried using the latest `google-maps/google-maps.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `google-maps/google-maps.d.ts`.
  - The authors of that type definition are cc/ @DeividasBakanas @RyanCavanaugh

> ⚠️ **NOTE**: There are two separate files discussed below. The one with hyphens in its name (`google-maps`) refers to the typings for the `google-maps` npm package. The one with periods in its name (`google.maps`) refers to the official [Google Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/3.exp/reference) object.

The callback passed in to `GoogleMapsLoader.load` in google-maps/google-maps.d.ts takes an argument that only lists one property, `google.maps.Map`. In reality, the `google.maps` object returned has many more properties, e.g. `google.maps.Marker`, `google.maps.LatLng` etc.

See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/googlemaps/google.maps.d.ts for the full set of properties that google.maps has.

We should either list all of these properties manually, or figure out a way to use all of the `google.maps` namespace from google.maps.d.ts and assign them all at once.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by nertzy** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6c6399ea925cd6f5672aff869aaa7a503a357ee6
