### ISSUE TITLE
Hapi: Most basic app compile is broken if TSC set to disallow Implicit Any

### ISSUE THREAD

**Issue by lukecwilliams** [DefinitelyTyped/DefinitelyTyped#11519]
- [x] I tried using the latest `hapi/hapi.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [x] I want to talk about `hapi/hapi.d.ts`.
  - The authors of that type definition are cc/ @prashaantt @flowpl @hiddenboox @vvakame @jppellerin @StanleyGoldman @hakubo @jasonswearingen @adamcarr @tjoskar @akfish 

It appears to us that a recent check-in broke the most basic Hapi application (our build is also broken on 13.5.0).  After cb07439, a simple server.route() invocation tags the `request` and `reply` parameters with "implicitly has an 'Any' type."  This prevents compiling with tsc if it's set to disallow implicit any.

Removing five lines in hapi.d.ts solves the issue: those containing

```
(request: Request, reply: IStrictReply)
```

Can anyone comment on this, particularly whether you also see a basic server.route() call failing to compile when implicit any is disallowed?

**Comment by akfish** [comment]
Sorry for the delay. Previous messages got buried under too many emails.

So basically you would like this to pass:
```ts 
// Implict handler
server.route({
	method: 'GET',
	path: '/hello',
	handler: function (request, reply) {
		request.log('info', { route: '/hello' }, Date.now());
		reply('hello world');
	}
});
```

A fix is on the way.

**Comment by akfish** [comment]
Please let me know if https://github.com/akfish/DefinitelyTyped/commit/5746599ab1ba0e49fd16e47558f3c18f3c8aa4e1 would resolve your issue, before I send a PR.

**Comment by lukecwilliams** [comment]
Thanks for the quick response AKFish - yes, the compile works again with
this fix.

<http://www.blueseastudios.com/>

   - Luke Williams
   - Blue Sea Studios, LLC
   - www.BlueSeaStudios.com <http://www.blueseastudios.com/>

**Comment by akfish** [comment]
No problem.
