### ISSUE TITLE
Bad export in node.d.ts

### ISSUE THREAD

**Issue by ibrido90** [DefinitelyTyped/DefinitelyTyped#11537]
export function createWriteStream(path: string | Buffer, options?: {
        flags?: string;
        encoding?: string;
        fd?: number;
        mode?: number;
    }): WriteStream;

this should export also

autoClose <Boolean>
start <Integer>

**Comment by TonyPythoneer** [comment]
What module exports the function? Would you provide nodejs API document as reference? 😄

**Comment by ibrido90** [comment]
https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options

**Comment by vvakame** [comment]
:+1:
