### ISSUE TITLE
Angular 1.5 Components constructor cannot be an abstract

### ISSUE THREAD

**Issue by nomaed** [DefinitelyTyped/DefinitelyTyped#11541]
CC @thorn0 @andy-ms @smfeest @christophercr (partook in discussions)

PR #11389 (Commit 624de0de10d2a1437ce1b9268dbcdeffec3cccdf) introduced a change that breaks some specific scenarios of Component options object. This occurs when using a component factory that accepts the controller as an argument, and this controller is a child of a base controller.

Specific line:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angularjs/angular.d.ts#L1664

This is a silly trimmed down example, but is based on a real and more complicated use case.

``` typescript
import * as angular from "angular";

abstract class MyBase {
  public name = "Foo";
}

class MyComponent1 extends MyBase {
  public $onInit() {
    this.name = "BarBar";
  }
}

class MyComponent2 extends MyBase {
  public $onInit() {
    this.name = "MooMoo";
  }
}

function getComponentOptions(Ctrl: typeof MyBase) {
  const myComponent: angular.IComponentOptions = {
    template: `<div>Hi {{ctrl.name}}</div>`,
    controller: Ctrl,
    controllerAs: "ctrl"
  };
  return myComponent;
}

angular.module("testApp", [])
  .component("testEins", getComponentOptions(MyComponent1))
  .component("testZewi", getComponentOptions(MyComponent2));
```

```
20   const myComponent: angular.IComponentOptions = {
           ~~~~~~~~~~~

src/ng-comp-ctrl.ts(20,9): error TS2322: Type '{ template: string; controller: typeof MyBase; controllerAs: string; }' is not assignable to type 'IComponentOptions'.
  Types of property 'controller' are incompatible.
    Type 'typeof MyBase' is not assignable to type 'string | (new (...args: any[]) => IController) | ((...args: any[]) => void | IController) | (stri...'.
      Type 'typeof MyBase' is not assignable to type '(string | (new (...args: any[]) => IController) | ((...args: any[]) => void | IController))[]'.
        Property 'push' is missing in type 'typeof MyBase'.
```

The code is here: https://github.com/nomaed/ts2test/blob/master/src/ng-comp-ctrl.ts
You can play with it by cloning the repo and running `tsc` on the `ng-comp-ctrl.ts` file.

**Comment by thorn0** [comment]
For some reason, it breaks because of the `abstact` keyword. If I remove it, everything works. I'm investigating why this happens.

**Comment by thorn0** [comment]
It boils down to this:
```ts
abstract class MyBase {
  public name = "Foo";
}
let foo: (new (...args: any[]) => ng.IController) = MyBase;
```
The error is: `Cannot assign an abstract constructor type to a non-abstract constructor type.`

**Comment by thorn0** [comment]
It's https://github.com/Microsoft/TypeScript/issues/5843

**Comment by thorn0** [comment]
For now, you can rewrite `getComponentOptions` like this:

```ts
function getComponentOptions<T extends ng.IControllerConstructor & typeof MyBase>(Ctrl: T) {
	const myComponent: angular.IComponentOptions = {
		template: `<div>Hi {{ctrl.name}}</div>`,
		controller: Ctrl,
		controllerAs: "ctrl"
	};
	return myComponent;
}
```

**Comment by thorn0** [comment]
Also everything works if you make `getComponentOptions` generic this way:
```ts
function getComponentOptions<T extends typeof MyBase>(Ctrl: T) {
	const myComponent = {
		template: `<div>Hi {{ctrl.name}}</div>`,
		controller: Ctrl,
		controllerAs: "ctrl"
	};
	return myComponent;
}

angular.module("testApp", [])
	.component("testEins", getComponentOptions(MyComponent1))
	.component("testZewi", getComponentOptions(MyComponent2));
```

**Comment by thorn0** [comment]
I like the last option the most as you don't need to mention any types from `angular.d.ts` there. Everything is inferred.

**Comment by nomaed** [comment]
@thorn0 The last option is the best, even better than the original way I had it.
The factory *is* generic in nature, so using generics syntax is the most precise way to do it.

Thank you, I will use the generic syntax.
Do you think that this issue should be closed since there is a neat solution, or would you like to look into a way to mitigate the compilation error so it will work with the old syntax as well?

**Comment by thorn0** [comment]
https://github.com/Microsoft/TypeScript/issues/5843 is going to be fixed (sooner or later). And while it's not, there are the workarounds that I showed above. So I think we can close this issue. It's good that you renamed it so that it's easier to find it for those who face something similar.

**Comment by nomaed** [comment]
That was the idea :)
Alright then, closing. Thanks for your investigation.

**Comment by nomaed** [comment]
@thorn0 Sorry for reopening the issue but I wanted you to look at that suggested neat solution. It doesn't seem to work. It worked for you since you haven't annotated the object to be of type `angular.IComponentOptions`. When I added the annotation, it fails with an even deeper error trace.
I works when using `ng.IControllerConstructor & typeof MyBase` syntax though.

Any ideas?

```typescript
import * as angular from "angular";

abstract class MyBase implements angular.IComponentController {
  public name = "Foo";
}

class MyComponent1 extends MyBase {
  public $onInit() {
    this.name = "BarBar";
  }
}

class MyComponent2 extends MyBase {
  public $onInit() {
    this.name = "MooMoo";
  }
}

function getComponentOptions<T extends typeof MyBase>(Ctrl: T) {
  const myComponent: angular.IComponentOptions = {
    template: `<div>Hi {{ctrl.name}}</div>`,
    controller: Ctrl,
    controllerAs: "ctrl"
  };
  return myComponent;
}

angular.module("testApp", [])
  .component("testEins", getComponentOptions(MyComponent1))
  .component("testZewi", getComponentOptions(MyComponent2));
```
```
20   const myComponent: angular.IComponentOptions = {
           ~~~~~~~~~~~

src/ng-comp-ctrl.ts(20,9): error TS2322: Type '{ template: string; controller: T; controllerAs: string; }' is not assignable to type 'IComponentOptions'.
  Types of property 'controller' are incompatible.
    Type 'T' is not assignable to type 'string | (new (...args: any[]) => IController) | ((...args: any[]) => void | IController) | (stri...'.
      Type 'typeof MyBase' is not assignable to type 'string | (new (...args: any[]) => IController) | ((...args: any[]) => void | IController) | (stri...'.
        Type 'typeof MyBase' is not assignable to type '(string | (new (...args: any[]) => IController) | ((...args: any[]) => void | IController))[]'.
          Type 'T' is not assignable to type '(string | (new (...args: any[]) => IController) | ((...args: any[]) => void | IController))[]'.
            Type 'typeof MyBase' is not assignable to type '(string | (new (...args: any[]) => IController) | ((...args: any[]) => void | IController))[]'.
              Property 'push' is missing in type 'typeof MyBase'.
```

**Comment by thorn0** [comment]
Removing the `angular.IComponentOptions` annotation is an important part of that solution. So that the types are matched against this interface not inside the `getComponentOptions` function but in the `.component` call.

**Comment by nomaed** [comment]
@thorn0 IMO removing this annotation is not a solution but a workaround, same as using `<any>` which will work just as well. The whole idea is to annotate the function to return an `IComponentOptions` object.

**Comment by thorn0** [comment]
There is an important difference compared to using any. Try for example using a number instead of a string in the template field. You'll see that the code is still strongly typed to some extent. However, unlike a type-annotated object literal, this code doesn't protect you from misspelled property names like "tepmlateUrl".

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
