### ISSUE TITLE
Conflict between redux's inline type definitions and the new @types definitions.

### ISSUE THREAD

**Issue by Emm** [DefinitelyTyped/DefinitelyTyped#11551]
This issue is already touched on in #9247, but with the release of Typescript 2.0 with the new **@types** scoped packages, we may have a way out.

The crux of the matter is that **redux** has been shipping inline type definitions since **3.4.0** earlier this year. However, there still exists a type definition for it in the DefinitelyTyped repo. This, in turn, causes an issue, since the type definitions for an addon like **@types/redux-thunk** depend on the DefinitelyTyped packages, so mechanically, installing **redux-thunk** and **@types/redux-thunk** leads to installing two type definitions for **redux**. This in turns causes problems with the declaration merging mechanism (**redux-thunk** extends **redux**'s interfaces) - that is, it doesn't compile.

Possible solutions:
- remove **redux**'s type definitions from the 2.0 branch (and have a stub package for **@types/redux** as is done for **@types/moment**, which also ships its own type definitions).
- make **redux-form**'s type definitions depend from **redux** and not **@types/redux** (I'm not sure if that would be possible).

**Comment by stephtr** [comment]
Redux-thunk has its own [TypeScript definition](https://github.com/gaearon/redux-thunk/pull/77/commits/b0ec79cabeb498e389a3d41a723031fc4047b236) included.

**Comment by Emm** [comment]
It may be in the repo, but it doesn't ship with the NPM module.Note that
there are quite a number of packages, many of which also do not ship with
their type definitions (like react-redux) depending on @types/redux:

https://www.npmjs.com/package/@types/redux

**Comment by stephtr** [comment]
As far as I noticed this issue has been solved and could be closed.
