### ISSUE TITLE
Missing typings for fields in Schema

### ISSUE THREAD

**Issue by linusbrolin** [DefinitelyTyped/DefinitelyTyped#11571]
- [x] I tried using the latest `mongoose/mongoose.d.ts` file in this repo and had problems.
- [x] I want to talk about `mongoose/mongoose.d.ts`.
  - The authors of that type definition are cc/ @simonxca 

There are a bunch of variables in Schema that are currently not included in the mongoose typings.
They are defined like this in the javascript source code:

```
this.paths = {};
this.subpaths = {};
this.virtuals = {};
this.singleNestedPaths = {};
this.nested = {};
this.inherits = {};
this.callQueue = [];
this._indexes = [];
this.methods = {};
this.statics = {};
this.tree = {};
this._requiredpaths = undefined;
this.discriminatorMapping = undefined;
this._indexedpaths = undefined;
this.query = {};
this.childSchemas = [];

this.s = {
  hooks: new Kareem(),
  kareemHooks: IS_KAREEM_HOOK
};
```

At the very least, all of the paths, virtuals, nested, tree, etc.. should be available.
They can be accessed in plugins for example.

Edit:
Also, the VirtualType class is missing typings for these fields:

```
this.path = name;
this.getters = [];
this.setters = [];
this.options = options || {};
```

**Comment by simonxca** [comment]
@linusbrolin these are private implementation details. Unless they're in the public mongoose api docs, DefinitelyTyped definitions will not include these. See here: http://definitelytyped.org/guides/contributing.html#private-apis

If you really need to use these you'll have to use an index:
```
schema['paths'];
scheam['subpaths'];
```

I know I added a property a few days back `schematype.options`, but I just realized it's not listed in the public docs so it will be removed.

**Comment by linusbrolin** [comment]
@simonxca hmm, ok..
I guess I can live with that.

I found other missing properties though.
Mongoose has support for populating nested fields now, so `ModelPopulateOptions` needs to be updated to include a `populate: ModelPopulateOptions | ModelPopulateOptions[]` property.
Also, the `populate` functions for `MongooseDocument` and `DocumentQuery` also needs to be updated with uniontype `options: ModelPopulateOptions | ModelPopulateOptions[]`.

**Comment by simonxca** [comment]
@linusbrolin Yup you're right. Looks like these are missing.
