### ISSUE TITLE
Shouldn't Typescript version in types-2.0 be ~2.0.0?

### ISSUE THREAD

**Issue by osechet** [DefinitelyTyped/DefinitelyTyped#11574]
In types-2.0 branch, the typescript version in `package.json` is `next`, that is to say `2.1.0-dev` at the time of writing. Shouldn't that version be changed to `~2.0.0`?

**Comment by andy-ms** [comment]
We're using the latest compiler version as a way of checking for breaking changes when we run tests. But definitions should avoid using features specific to TypeScript 2.1 and up.
