### ISSUE TITLE
[wiring-pi] There is no INST_EDGE_FALLING exported const but INT_EDGE_FALLING 

### ISSUE THREAD

**Issue by NoHomey** [DefinitelyTyped/DefinitelyTyped#11604]
- [x] I tried using the latest `wiring-pi/wiring-pi.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I want to talk about `wiring-pi/wiring-pi.d.ts`
  - The authors of that type definition are cc/ @NoHomey

Correcting exported `const` name. There is no [`INST_EDGE_FALLING`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/aee664c7fe39679e29015fe48dc01406f6503ba8/wiring-pi/wiring-pi.d.ts#L32) exported `const` but [`INT_EDGE_FALLING`](https://github.com/eugeneware/wiring-pi/blob/5bea401d9738d995f5b65d3ec013f589f2ca1719/src/wiringPiISR.cc#L260).

**Comment by NoHomey** [comment]
#11603 fixes this issue.

**Comment by vvakame** [comment]
:+1:
