### ISSUE TITLE
Preventing dt-bot from mentioning a user on issues?

### ISSUE THREAD

**Issue by benjaminjackman** [DefinitelyTyped/DefinitelyTyped#11624]
How can I prevent the dt-bot from mentioning me on new issues? I don't see anyway to unsubscribe the bot (perhaps a link to unsubscribe could be included in it's mentions). I have blocked it, but github doesn't prevent mentions from reaching through and still triggering an inbox notification. So it would be better if the bot just did not make the @ mention at all.

Here is an example where it does it's @ mentions:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11613#issuecomment-250657243

I apologize if this isn't the right place to report the issue, but I have tried emailing the bot and mentioning it in issues where i was mentioned in the past but i have not gotten any response.

Thanks!

btw I think it's pretty handy to have the dt-bot in general, but it keeps mentioning me on every commit to the jquery .d.ts after i made a fairly minor change a few years ago.

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/dt-review-tool/blob/master/lib/index.ts
it implemented in here.
I'll working for this. please wait.
