### ISSUE TITLE
colors field is missing from ChartSettings

### ISSUE THREAD

**Issue by nickmkk** [DefinitelyTyped/DefinitelyTyped#11646]
I tried using the latest `chartjs/chart.d.ts` file in this repo and had problems.

I need to set the value of Chart.defaults.global.colors but that field is missing from the ChartSettings interface, how can I get that field added?  The interface should have this additional field.

interface ChartSettings {
    colors?: string[];
}

Thank you

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by stephtr** [comment]
Are you sure that there should be such a property?
I didn't find any reference to `Chart.defaults.global.colors` in the [documentation](http://www.chartjs.org/docs/).

**Comment by nickmkk** [comment]
My apologies, I think it’s actually an angular-chart thing, sorry to waste your time.  I ended up using the ChartJsProvider in angular to set the options, as far as I know there isn’t currently any type definitions for angular-chart.

https://jtblin.github.io/angular-chart.js/

[cid:image001.png@01D250B3.96232760]

It appears their documentation is out of date though, the latest version requires the chartColors attribute instead of colors, my actual implementation below.

[cid:image002.png@01D250B4.314E0DE0]

Thanks for getting back to me about this though, sorry again for wasting your time.

-Nick

**Comment by stephtr** [comment]
No problem, it didn't took that much time ;)
However it would be useful to either close the issue or change it to a definition request.
