### ISSUE TITLE
Implementing defaultProps with ts 2.0 strict null checks

### ISSUE THREAD

**Issue by cwmoo740** [DefinitelyTyped/DefinitelyTyped#11640]
Default properties don't seem to function well currently with strictNullChecks enabled. For example:

```
interface TestProps { x?: number}

class Test extends React.Component<TestProps, null> {

    static defaultProps =  {x: 5};

    render() {
        const x: number = this.props.x;
        return <p>{x}</p>;
    }
}
```

Errors with  `error TS2322: Type 'number | undefined' is not assignable to type 'number'` even though this is guaranteed to work at runtime.

Right now defaultProps and Props seem to be treated as the same type always, but they're actually almost never the same type because optional fields in Props should be overwritten by required values in DefaultProps.

What if there were something like...

```
class ComponentWithDefaultProps<P, D, S> {
    props: P & D & {children?: React.Children};
}
```

that is identical to the existing React.Component typing except for the type of props?

**Comment by JoshuaToenyes** [comment]
Since the default props are set at runtime, I'm not sure if there's a way to handle this nicely, other than a type assertion. (Of course, you could always just disable strict null checks.)

Here's how you may be able to get around it in your example:

```
interface TestProps { x?: number}

class Test extends React.Component<TestProps, null> {

    static defaultProps =  {x: 5};

    render() {
        const x: number = (this.props.x as number);
        return <p>{x}</p>;
    }
}
```

See https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions

If there's a more graceful way of handling this, I'd love to hear it. 

Disclaimer: I've been using TypeScript for about three days, I'm tired, and probably have no idea what I'm talking about.

**Comment by rexk** [comment]
+1000 on updating type definition file to include three generic type definitions.

This used to be fine without `---strictNullChecks`, but now, it is definitely going to be a problem for many component classes.

Flow also implements similar class implementation because of nature of strict null type checking.
https://github.com/facebook/flow/blob/master/lib/react.js#L16
https://github.com/facebook/flow/blob/master/lib/react.js#L104-L105

**Comment by r00ger** [comment]
Seems like we don't have much options here except of waiting for https://github.com/Microsoft/TypeScript/issues/2175 being resolved in order to add third generic.
I don't think that such a (breaking) change (I mean `class Component<P, S, D>`) can be approved by reviewers.
@johnnyreilly @bbenezech @pzavolinsky do you guys have an opinion on that?

**Comment by pzavolinsky** [comment]
@r00ger agreed. Changing the definition is *too* disruptive.

Has anyone considered using `Partial`?

As in: 
```ts
    interface ComponentClass<P> {
-        defaultProps?: P;
+        defaultProps?: Partial<P>;
    }
```

**Comment by pzavolinsky** [comment]
Don't mind that `Partial` stuff above.

**Comment by nishp1** [comment]
Partial only solves how to declare partial propTypes problem. Inside of `render`, `lastName` is still of type `string  | undefined`. To get around it, you have to cast it string using `as` or `!` like shown below. It works, but is not ideal. 

```ts
interface IUser {
    firstName: string
    lastName?: string
}
export class User extends React.Component<IUser, {}> {
    public static defaultProps: Partial<IUser> = {
        lastName: 'None',
    }

    public render () {
        const { firstName, lastName } = this.props
        // error
        lastName.toUpperCase()

        return (
            <div>{firstName} {lastName}</div>
        )
    }
}
```
I've just started using TS. Am I missing anything?

**Comment by vsaarinen** [comment]
If anyone has a good solution for types and defaultProps, I'm all ears. We currently do this:

```js
interface Props {
  firstName: string;
  lastName?: string;
}

interface DefaultProps {
  lastName: string;
}

type PropsWithDefaults = Props & DefaultProps;

export class User extends React.Component<Props, void> {
  public static defaultProps: DefaultProps = {
    lastName: 'None',
  }

  public render () {
    const { firstName, lastName } = this.props as PropsWithDefaults;
    
    return (
      <div>{firstName} {lastName}</div>
    )
  }
}
```

**Comment by Glinkis** [comment]
+1
I am currently battling this issue.

**Comment by iReallyHateUsernames** [comment]
+1

**Comment by psivanov** [comment]
+1

**Comment by aldendaniels** [comment]
In addition to adding the third type parameter, you'll need the ability to diff props against the defaulted props. Happily as of TS 2.4 this is now possible! See https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-319495340

**Comment by Hotell** [comment]
IMHO adding third parameter is a big no no, also Flow team knew that and recently they changed that for greater good. It should be type-checker responsibility to know how to handle these kind of things. 

Don't get me wrong, I love Typescript, but since Flow 0.53 I have to say it's superior for React development https://medium.com/flow-type/even-better-support-for-react-in-flow-25b0a3485627

**Comment by aldendaniels** [comment]
@Hotell Flow does have three type parameters for `React.Component` - per the Medium article you linked to Flow can infer class type parameters from the subclass annotations - a neat language-level feature TS doesn't support, but not a type-declaration consideration AFAIK.

**Comment by Hotell** [comment]
@aldendaniels 
> Flow does have three type parameters for React.Component

nope, it used to be that way before 0.53, not anymore :) https://github.com/facebook/flow/commit/20a5d7dbf484699b47008656583b57e6016cfa0b#diff-5ca8a047db3f6ee8d65a46bba4471236R29

**Comment by aldendaniels** [comment]
@Hotell Ah, sure enough! Thanks for correcting me.

AFAIK there's no way in TS to infer the type of the default props though. Using the three-type-parameter approach we'd likely be able to get correct typing without blocking on upstream changes from the TypeScript team.

Do you know of a way to use the inferred type of a static property without passing `typeof MyComponent.defaultProps` as a type param?

**Comment by Grmiade** [comment]
Any news on this subject? Does someone do a PR to add a third type parameter and use https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-319495340?

**Comment by kgaregin** [comment]
Upvoting issue: same problem

**Comment by marcel-ernst** [comment]
+1

**Comment by joostlubach** [comment]
I also ran into this, and I've chosen (until this is properly fixed) to abstain from using `static defaultProps` and instead use a helper HOC:

File **components/helpers/withDefaults.tsx**:
```tsx
import * as React from 'react'

export interface ComponentDefaulter<DP> {
  <P extends {[key in keyof DP]: any}>(Component: React.ComponentClass<P>): React.ComponentType<
    Omit<P, keyof DP> &         // Mandate all properties in P and not in DP
    Partial<Pick<P, keyof DP>>  // Accept all properties from P that are in DP, but use type from P
  >
}

export default function withDefaults<DP>(defaultProps: DP): ComponentDefaulter<DP> {
  return Component => props => <Component {...defaultProps} {...props}/>
}
```

Now I can use:

File **components/Button.tsx**:
```tsx
import * as React from 'react'
import withDefaults from './helpers/withDefaults'

export interface ButtonProps {
  label: string
  onPress: () => any
}

export const defaultProps = {
  onPress: () => undefined
}

class Button extends React.Component<ButtonProps> {
  // ...
}

export default withDefaults(defaultProps)(Button)
```

Three potential downsides (that I can think of):

1. It requires an HOC, but since this is a quite common paradigm in React world, that seems OK.
2. You have to declare the props as a generic type parameter, and cannot rely on inference from the `props` property.
3. There is no implicit checking of the types of `defaultProps`, but this can be remedied by specifying `export const defaultProps: Partial<ButtonProps> = {...}`.

**Comment by qiu8310** [comment]
According to @vsaarinen, I write a base class with `props: Props & DefaultProps`, so the whole class that extends the base class can directly use `this.props` without use `this.props as PropsWithDefaults`.  

Like this:

```ts
import * as React from 'react'

export class Component<P = {}, S = {}, DP = {}> extends React.Component<P, S> {
  props: Readonly<{ children?: React.ReactNode }> & Readonly<P> & Readonly<DP>
}

export interface Props {
  firstName: string
  lastName?: string
}

export interface DefaultProps {
  lastName: string
}

export class User extends Component<Props, any, DefaultProps> {
  render() {
    const { firstName, lastName } = this.props
    
    // no error
    return (
      <div>{firstName} {lastName.toUpperCase()}</div>
    )
  }
}

```

**Comment by r-tock** [comment]
Actually @qiu8310 that didnt work fully, Still had issues with call sites screaming about those default props not being optional. Got it to work with a minor adjustment


```jsx
import * as React from 'react'

export class Component<P = {}, S = {}, DP = {}> extends React.Component<P, S> {
  // Cast the props as something where readonly fields are non optional
  props = this.props as Readonly<{ children?: React.ReactNode }> & Readonly<P> & Readonly<DP>
}

export interface Props {
  firstName: string
  lastName?: string
}

export interface DefaultProps {
  lastName: string
}

export class User extends Component<Props, any, DefaultProps> {
  render() {
    const { firstName, lastName } = this.props
    
    // no error
    return (
      <div>{firstName} {lastName.toUpperCase()}</div>
    )
  }
}
```

**Comment by yonatanmn** [comment]
This works for me (simplest solution so far)

```ts
interface Props {
  firstName: string;
  lastName?: string;
}

interface DefaultProps {
  lastName: string;
}

export class User extends React.Component<Props> {
  props:  Props & DefaultProps 

  public static defaultProps: DefaultProps = {
    lastName: 'None',
  }

  public render () {
    const { firstName, lastName } = this.props;
    
    return (
      <div>{firstName} {lastName}</div>
    )
  }
}
```

**Comment by geowarin** [comment]
Here is what I came up with if anyone is interested. It should be pretty easy to come up with a patch for react.d.ts:

react.fix.d.ts
```ts
import * as React from "react";

/**
 * From https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-307871458
 * The Diff type is a subtraction operator for string literal types. It relies on:
 *  - T | never = T
 *  - T & never = never
 *  - An object with a string index signature can be indexed with any string.
 */
export type StringDiff<T extends string, U extends string> = ({[K in T]: K} &
  {[K in U]: never} & {[K: string]: never})[T];

/**
 * From https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-311923766
 * Omits keys in K from object type T
 */
export type ObjectOmit<T, K extends keyof T> = Pick<T, StringDiff<keyof T, K>>;

/**
 * Returns a version of type T where all properties which are also in U are optionalized.
 * Useful for makding props with defaults optional in React components.
 * Compare to flow's $Diff<> type: https://flow.org/en/docs/types/utilities/#toc-diff
 */
export type ObjectDiff<T, U> = ObjectOmit<T, keyof U & keyof T> &
  {[K in (keyof U & keyof T)]?: T[K]};

export class Component1<P = {}, S = {}, DP = {}> extends React.Component<ObjectDiff<P, DP>, S> {
  props: any
}

export class Component<P = {}, S = {}, DP = {}> extends Component1<P, S, DP> {
  props: P
}
```

example.tsx
```ts
import * as React from "react";
import {Component} from "./React.fix";

interface UserProps {
  firstName?: string
  lastName: string
}
interface DefaultUserProps {
  firstName: string
}

class User extends Component<UserProps, never, DefaultUserProps> {

  render() {
    return (
        <div>
          {this.props.lastName.toUpperCase()}
        </div>
    );
  }
}

<User lastName="Curry"/>
```

**Comment by r00ger** [comment]
I played with third generic and ended up having something similar to @qiu8310's proposal:

```ts
// ComponentWithDefaultProps.ts
import * as React from "react";

export declare class ComponentWithDefaultProps<P, S, DP extends Partial<P>> extends React.Component<P & DP, S> {}
type redirected<P, S, DP> = ComponentWithDefaultProps<P, S, DP>;
const redirected: typeof ComponentWithDefaultProps = React.Component as any;

export const Component = redirected;

// User.ts
import { Component } from "ComponentWithDefaultProps";
export interface Props {
  firstName: string
  lastName?: string
}
export interface DefaultProps {
  lastName: string
}

export class User extends Component<Props, {}, DefaultProps> {
  public render() {
    const { firstName, lastName } = this.props;
    return <div>{firstName} {lastName.toUpperCase()}</div>;
  }
}
```

However both of these approaches (mine and the approach above) causes the bigger problem. There are types of created component in my example:

```ts
User: React.ComponentClass<P & DP>
User["props"]: Readonly<{ children?: React.ReactNode }> & Readonly<P & DP>
```

Apparently, the `User`'s interface is wrong. `React.ComponentClass<P & DP>` means that `lastName` is required too, so that

```ts
<User firstName="" />;
//    ~~~~~~~~~~~~  Property 'lastName' is missing...
```

In the @qiu8310's example types are different:

```ts
User: React.ComponentClass<P>
User["props"]: Readonly<{ children?: React.ReactNode }> & Readonly<P> & Readonly<DP>
```

But the same piece of JSX causes the same error, because [`tsc`'s JSX checks are based on `props`' type](http://www.typescriptlang.org/docs/handbook/jsx.html#attribute-type-checking).

```ts
<User firstName="John" />;
//    ~~~~~~~~~~~~~~~~  Property 'lastName' is missing...
```

Fun thing is `<User firstName="John" />` turned to `React.createElement(User, {firstName: "John"})` which is valid. In that case type checks rely on `ComponentClass` first type parameter, so 

```ts  
<User firstName="Jonh" />; // doesn't work, but
React.createElement(User, { firstName: "John" }); // works
```

As you see, we would still have to add another trick in order to export a component with correct interface

```ts
export const User = class extends Component<Props, {}, DefaultProps> {
	// ...
} as React.ComponentClass<Props>;

<User firstName="Jonh" />; // works
```

It seems there is no good solution that can be merged to `React`'s definition, you can either use `ComponentWithDefaultProps` and assert the type of exported component, or assert `this.props` type in component (e.g. `const { lastName } = this.props as Props & DefaultProps`, or using exclamation mark `this.props.lastName!.toLowerCase()`).

**Comment by rifler** [comment]
i found some example about this discussion - https://github.com/gcanti/typelevel-ts#objectdiff

**Comment by r00ger** [comment]
@rifler so called HOC approach (I prefer decorator) [has been here for a while](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11640#issuecomment-345447306), we try to come up with a solution that do not add runtime overhead

**Comment by rifler** [comment]
Oh, great
Hope you will find the solution

**Comment by goodmind** [comment]
any progress?

**Comment by Aurelain** [comment]
The following is a variation on the technique mentioned by @r00ger:
```ts
interface IUser {
    name: string;
}
const User = class extends React.Component<IUser> {
    public static defaultProps: IUser = {name: "Foo"}
    public render() {
        return <div>{this.props.name}</div>;
    }
} as React.ComponentClass<Partial<IUser>>;
React.createElement(User, {}); // no error, will output "<div>Foo</div>"
```
Using the above snippet will work, but you will lose the ability to use static properties on User, since it becomes an anonymous class. A hacky solution would be to shadow the class name, like so:
```ts
// tslint:disable-next-line:no-shadowed-variable
const User = class User extends React.Component<IUser>
```
You may now use private static fields inside the class. Public statics are still unusable. Also, notice the need to silence tslint.

**Comment by aldendaniels** [comment]
I thought it worth mentioning that as of TS 2.8, the `Exclude` type is officially supported:

```typescript
type Omit<T, K> = Pick<T, Exclude<keyof T, K>>;
```

See https://github.com/Microsoft/TypeScript/pull/21847.

So all we need is for `React.createElement()` to require the following in lieu of `Props`:
```typescript
Omit<Props, keyof DefaultProps>
```

The only problem is that in the React declarations, there's no `DefaultProps` type - for this we need either a third type parameter OR the ability to infer the type of static members as a language feature.

In the meantime, we've been rolling with the following:

```typescript
/**
 * The Create type allow components to implement a strongly thed create() function
 * that alows the caller to omit props with defaults even though the component expects
 * all props to be populated. The TypeScript React typings do not natively support these.
 */
export type Create<C extends BaseComponent<any, any>, D extends {} = {}> = (
  props?: typeHelpers.ObjectDiff<C['props'], D> & React.ClassAttributes<C>,
  ...children: React.ReactNode[]
) => React.ComponentElement<any, any>;

export interface DomPropsType {
  domProps?: domProps.DomProps;
}

export class BaseComponent<P, S = {}> extends React.Component<P & DomPropsType, S> {
  static create(props?: object, ...children: React.ReactNode[]) {
    return React.createElement(this, props, ...children);
  }

  constructor(props: P & DomPropsType, context?: any) {
  ...
}
```

And all our components look like:
```typescript
export class InsertObjectMenu extends BaseComponent<Props, State> {
  static create: Create<InsertObjectMenu, typeof InsertObjectMenu.defaultProps>;
  static defaultProps = {
    promptForImageUpload: true,
  };
  ...
}
```

Finally we have a lint rule enforcing that the `create` attribute is declared on all components. We don't use JSX, so we use:
```typescript
InsertObjectMenu.create({...})
```

Instead of `React.createElement()`.

We've been using this approach across a large codebase for close to a year now with good success, but we'd love to adopt JSX and this is what's holding us back.

**Comment by Hotell** [comment]
So much time invested in this "simple issues" . I'll just leave this here https://medium.com/@martin_hotell/ultimate-react-component-patterns-with-typescript-2-8-82990c516935  🖖

**Comment by goloveychuk** [comment]
```ts
    interface Component<P = {}, S = {}, DP extends Partial<P>=P> extends ComponentLifecycle<P, S> { }
    class Component<P, S, DP extends Partial<P> = P> {
        constructor(props: P & DP, context?: any);

        // We MUST keep setState() as a unified signature because it allows proper checking of the method return type.
        // See: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18365#issuecomment-351013257
        // Also, the ` | S` allows intellisense to not be dumbisense
        setState<K extends keyof S>(
            state: ((prevState: Readonly<S>, props: P) => (Pick<S, K> | S | null)) | (Pick<S, K> | S | null),
            callback?: () => void
        ): void;

        forceUpdate(callBack?: () => void): void;
        render(): ReactNode;

        // React.Props<T> is now deprecated, which means that the `children`
        // property is not available on `P` by default, even though you can
        // always pass children as variadic arguments to `createElement`.
        // In the future, if we can define its call signature conditionally
        // on the existence of `children` in `P`, then we should  remove this.
        private __externalProps: Readonly<{ children?: ReactNode }> & Readonly<P>;
        props: Readonly<{ children?: ReactNode }> & Readonly<P> & DP;
        state: Readonly<S>;
        context: any;
        refs: {
            [key: string]: ReactInstance
        };
    }

    class PureComponent<P = {}, S = {}, DP extends Partial<P>=P> extends Component<P, S, P> { }


interface ElementAttributesProperty { __externalProps: {}; }

```
Look carefully at last line. 

With this changes we could have 
```ts

interface Props {
    a: string
    b?: string
    c?: string
}

class Comp extends React.Component<Props, {}, typeof Comp.defaultProps> {
    static defaultProps = {
        b: ''
    }

    render() {
        const {a, b, c} = this.props

        let res = a.concat(b)  // ok
        let res1 = a.concat(c) //fail

        return null
    }
}



const res1= <Comp a=''/> // ok
const res3 = <Comp /> // fail
```

Which is best we can get if using `static defaultProps` (ts checker should be changed if we want to omit `typeof Comp.defaultProps`).
Other options, was already said - HOC, type casts.

**Comment by decademoon** [comment]
Here's my (very ugly) attempt based on the idea from https://medium.com/@martin_hotell/ultimate-react-component-patterns-with-typescript-2-8-82990c516935:

```ts

import React from 'react';

type ExtractProps<T> = T extends React.ComponentType<infer Q> ? Q : never;
type ExtractDefaultProps<T> = T extends { defaultProps?: infer Q } ? Q : never;
type RequiredProps<P, DP> = Pick<P, Exclude<keyof P, keyof DP>>;
type RequiredAndPartialDefaultProps<RP, DP> = Required<RP> & Partial<DP>;

type ComponentTypeWithDefaultProps<T> =
  React.ComponentType<
    RequiredAndPartialDefaultProps<
      RequiredProps<ExtractProps<T>, ExtractDefaultProps<T>>,
      ExtractDefaultProps<T>
    >
  >;

function withDefaultProps<T extends React.ComponentType<any>>(Comp: T) {
  return Comp as ComponentTypeWithDefaultProps<T>;
}
```
```ts
interface IProps {
  required: number;
  defaulted: number;
}

class Foo extends React.Component<IProps> {
  public static defaultProps = {
    defaulted: 0,
  };
}

// Whichever way you prefer...
const FooWithDefaultProps = Foo as ComponentTypeWithDefaultProps<typeof Foo>;
const FooWithDefaultProps = withDefaultProps(Foo);

const f1 = <FooWithDefaultProps />;  // error: missing 'required' prop
const f2 = <FooWithDefaultProps defaulted={0} />;  // error: missing 'required' prop
const f3 = <FooWithDefaultProps required={0} />;  // ok
const f4 = <FooWithDefaultProps required={0} defaulted={0} />;  // ok
```

**Comment by MOZGIII** [comment]
@decademoon, seems like we could just use this solution at `@types/react`, can we?
If that so, maybe you can create a PR?

**Comment by RobRendell** [comment]
@decademoon your definition doesn't handle the case where the non-default props actually include optional fields, i.e.

```
interface IProps {
  required: number;
  notRequired?: () => void;
  defaulted: number;
}

class Foo extends React.Component<IProps> {
  public static defaultProps = {
    defaulted: 0,
  };
}
```
I got it working in my case by changing your RequiredAndPartialDefaultProps type to not wrap the "RP" with "Required"

`
type RequiredAndPartialDefaultProps<RP, DP> = RP & Partial<DP>;
`

**Comment by Schlesiger** [comment]
I'm surprised there still isn't a proper solution or at least a working HOC on NPM; unless I have missed something.

**Comment by goodmind** [comment]
https://github.com/Microsoft/TypeScript/issues/23812

**Comment by toiletpatrol** [comment]
Hi everyone. Just wanted to say and if you are still reading this thread: I think @JoshuaToenyes made the most meaningful and helpful explanation. This is definitely not an issue so there's nothing to do with it. Use type assertion in this case.

**Comment by RobRendell** [comment]
@toiletpatrol actually, @decademoon's solution (with my slight amendment) automatically handles default props just fine.  It definitely could be merged into the DT definitions for React to provide the feature standard to everyone.

**Comment by vkrol** [comment]
@toiletpatrol @RobRendell did you see it https://github.com/Microsoft/TypeScript/issues/23812?

**Comment by RobRendell** [comment]
@vkrol I did see that, but I can drop decademoon's implementation in my codebase right now without waiting for releases of new features.

**Comment by BenLorantfy** [comment]
@decademoon Why don't you open a PR to DefinitelyTyped for that?

**Comment by MOZGIII** [comment]
Another workaround that I'm using for now for tricky cases:
```typescript
  const restWithDefaults = { ...Component.defaultProps, ...rest };
  return (
    <Component
      {...restWithDefaults}
    />
  );
```
Nothing wrong with it I guess, so I'm leaving it here as a dirty yet simple workaround.

**Comment by Hotell** [comment]
TS 3.2 and react 16.7 typings are fixing this. can we close ?

**Comment by cbergmiller** [comment]
To save others some time, here is a link to the release notes of Typescript 3.3:
[Support for defaultProps in JSX](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#support-for-defaultprops-in-jsx)

**Comment by pronebird** [comment]
@cbergmiller I am afraid those are the release notes for TypeScript 3.1 🙃

**Comment by denieler** [comment]
still having the same issue with `React.FunctionComponent`

**Comment by mgol** [comment]
@denieler I wouldn't advise using `defaultProps` with `React.FunctionComponent`, it's not natural. It's better to use default function parameters:
```tsx
interface HelloProps {
  name: string;
  surname: string;
}

const HelloComponent: React.FunctionComponent<HelloProps> = ({
  name = 'John',
  surname = 'Smith',
}) => {
  return <div>Hello, {name} {surname}!</div>
};
```

**Comment by mgol** [comment]
@denieler I wouldn't advise using `defaultProps` with `React.FunctionComponent`, it's not natural. It's better to use default function parameters:
```tsx
interface HelloProps {
  name?: string;
  surname?: string;
}

const HelloComponent: React.FunctionComponent<HelloProps> = ({
  name = 'John',
  surname = 'Smith',
}) => {
  return <div>Hello, {name} {surname}!</div>
};
```

**Comment by glecetre** [comment]
@mgol How would you define default function parameters if I didn't want to destructure the props?
I can only think of destructuring only the "defaulted" properties like so:

```
interface HelloProps {
  name?: string;
  surname?: string;
}

const HelloComponent: React.FunctionComponent<HelloProps> = ({
  name = 'John',
  surname = 'Smith',
  ...props
}) => {
  return <div>Hello, {name} {surname}! You are {props.age} years old.</div>
};
```

But I find it disgraceful to extract only *some* of the props.

**Comment by Glinkis** [comment]
@glecetre You can use:
```javascript
HelloComponent.defaultProps = {
    name: 'John',
    surname: 'Smith'
}
```

**Comment by vkrol** [comment]
@Glinkis please, note https://github.com/reactjs/rfcs/pull/107/files#diff-20b9b769068a185d90c23b58a2095a9dR184.

**Comment by mgol** [comment]
@glecetre Why do you not want to destructure all the props? It's simpler than defining `defaultProps` & easier to type. Class-based component's props type may bite you if you export to use externally as props that are required may not be required anymore if there's an entry for them in `defaultProps`. Using `defaultProps` also seems a little magical while in parameter destructuring it's all JavaScript.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
