### ISSUE TITLE
Contributing Guide: How to name typings for scoped packages?

### ISSUE THREAD

**Issue by DominikPalo** [DefinitelyTyped/DefinitelyTyped#11658]
The [Contributing Guide](http://definitelytyped.org/guides/contributing.html) doesn't contain an explanation how to properly name type definitions for a scoped npm module.

For example, I want to write typings for `@company-name/module-name` module, but I don't know how to name it. Should I create a directory named `company-name` in the root of the DefinitelyTyped repository and then a nested directory named `module-name`? Or should I use a single directory with some special delimiter used for separate company-name and module-name? 

Also, how is correct command for fetching scoped types using a new TS2 method `npm install @types/...`? `npm install @types/@company-name/module-name` or?

**Comment by bentruyman** [comment]
Which methods actually work? In my testing, I've only been able to get an un-scoped name to work (e.g. `@company-name/module-name` => `module-name`) inside of one of the `typeRoots`.

**Comment by bradleyayers** [comment]
A specific real-world example of this is the [@kadira/storybook](https://www.npmjs.com/package/@kadira/storybook) package which on cursory searching I've been unable to find typings for.

**Comment by unional** [comment]
Another example: [`@google/maps`](https://www.npmjs.com/package/@google/maps)

**Comment by unional** [comment]
Reference https://github.com/Microsoft/types-publisher/issues/155

**Comment by unional** [comment]
Seems like this is resolved? https://github.com/Microsoft/TypeScript/issues/14819

**Comment by amcasey** [comment]
@andy-ms Can this be closed?

**Comment by unional** [comment]
> Take **@foo/bar** a scoped package of the **@foo** organization hosted in their private feeds

Do you own the **@foo** organization? If you are the owner, you just add the typings directly in your package.

If you don't, and **@types/foo__bar** is not found, that just means that it is not defined in DT.
So you can either contribute to create it or create a custom typings and use it in your app/library directly.
