### ISSUE TITLE
XYZ is not a constructor

### ISSUE THREAD

**Issue by bennycode** [DefinitelyTyped/DefinitelyTyped#11706]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `wolfy87-eventemitter/wolfy87-eventemitter.d.ts`.
  - The authors of that type definition are cc/ @vvakame @ryiwamoto @tkrotoff @dreampulse @Tomino2112

I installed the `wolfy87-eventemitter` via:

``` bash
npm install --save @types/wolfy87-eventemitter
```

Then I tried to use it in my TypeScript project like the [tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/wolfy87-eventemitter/wolfy87-eventemitter-tests.ts) suggest:

``` typescript
import * as EventEmitter from "wolfy87-eventemitter";
...
let emitter: Wolfy87EventEmitter.EventEmitter = new EventEmitter();
emitter.emitEvent('hello-world', [1, 2, 3]);
```

When compiling the code and running it in a browser, I get the following error:

> TypeError: EventEmitter is not a constructor

I printed the `EventEmitter` object to the console and received the following:

**Screenshot**

![Screenshot](https://cloud.githubusercontent.com/assets/469989/19073503/ab73b8de-8a3b-11e6-8a70-c9da02bbcf67.PNG)

It looks like that I need to use `EventEmitter.default` instead of `EventEmitter()`. But if I type `EventEmitter.default` in my TypeScript code, the compiler complains saying:

> error TS2339: Property 'default' does not exist on type 'typeof EventEmitter'

My TypeScript compiler config (`tsconfig.json`) is the following:

``` json
{
  "compilerOptions": {
    "declaration": true,
    "module": "system",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noImplicitAny": false,
    "noImplicitReturns": true,
    "removeComments": true,
    "sourceMap": true,
    "target": "es5"
  },
  "exclude": [
    "node_modules",
    "typings/browser",
    "typings/browser.d.ts"
  ]
}
```

What can I do now to use the "EventEmitter" module in TypeScript?

**Comment by Tomino2112** [comment]
I had the same issue, unfortunately only way to resolve it was uncommenting last line 

```
declare var EventEmitter: typeof Wolfy87EventEmitter.EventEmitter;
``` 

and then in my script

```
import IEventEmitter = Wolfy87EventEmitter.EventEmitter;
```

That was the only way I made this work

**Comment by bennyn** [comment]
Thanks for the quick response. In which file did you uncomment `declare var EventEmitter`?

I thought that my issue is related to a [CommonJS and System.import issue](https://github.com/whatwg/loader/issues/19). 
But in my HTML page this works:

```javascript
System.import('wolfy87-eventemitter').then(function(EventEmitter) {
  var emitter = new EventEmitter();
  emitter.emitEvent('hello-world', [1, 2, 3]);
});
```

But my compiled TypeScript code creates the constructor function within `EventEmitter.default`, which is strange.

**Comment by Tomino2112** [comment]
In the typings file `typings/wolfy87eventemitter/index.d.ts`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
