### ISSUE TITLE
@types/linq is completely outdated

### ISSUE THREAD

**Issue by cervengoc** [DefinitelyTyped/DefinitelyTyped#11711]
We are in the process of migrating to the new TypeScript 2.0 definitions mechanism. We use `linqjs` in our projects, and we noticed that the corresponding `@types/linq` package contains a very old definitions file, which has several errors, and doesn't even declare a module (so it's not possible to `import` AFAIK).

Please add the latest definitions file as well, `3.0.3-Beta5` for example.

**Comment by dsoltesz** [comment]
I just tried to upgrade today and noticed that as well. Very outdated.

**Comment by mhegazy** [comment]
A PR to update the definitions would be appreciated.

**Comment by cervengoc** [comment]
Actually I double checked the current dev status of the `linq.js` library and I saw that indeed it didn't reach the official stable release of the `3.x` branch. So if this is true, the best for now is to keep the typings like this.

@mhegazy I'd be happy to contribute with this, but need some guidance.

If there is any possibility of versioning in `types` packages, then it would be great to add the `3.0.4-Beta5' version as a pre-release or so, but at first glance I can't see how versioning is handled, because I can see only the latest typings in the subfolders everywhere.

**Comment by mhegazy** [comment]
The version of the `@types` package is picked up from the header in the file. see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/linq/index.d.ts#L1

**Comment by cervengoc** [comment]
So if I understand correctly I should only change `index.d.ts` to the `3.0.4-Beta5` file, and then it will get picked up as a new `npm` package version too? How should I indicate that this will refer to a `pre` package?

**Comment by mhegazy** [comment]
@andy-ms noticed that the pacakge seems to have a .d.ts file itself, see http://linqjs.codeplex.com/SourceControl/latest#typescript/linq.js.d.ts. is this an updated one? if so then you can just use that.

**Comment by cervengoc** [comment]
@mhegazy Yes it seems like it includes typings, however, it looks like the npm package doesn't include it. I've contacted the library owner yesterday, hopefully I'll get a reply. Until then it would be good to have a typing version which targets the `3.0` library.

**Comment by deadmann** [comment]
how to import linqjs ? it goes to first if,  `if (typeof define === Types.Function && define.amd) { // AMD` and the root Enumerable does not exists :|

**Comment by andy-ms** [comment]
@deadmann Maybe ask [here](http://linqjs.codeplex.com/)?

**Comment by deadmann** [comment]
i do not have code plex account, and so i may not be there to answer any question afterward
