### ISSUE TITLE
Brush Event Error

### ISSUE THREAD

**Issue by lokeshn44** [DefinitelyTyped/DefinitelyTyped#11727]
I am using the 3.5.36 version of D3. Was trying to implement Brush fucntionality over the chart and getting below error. 
d3-brush.js:312 Uncaught TypeError: Cannot read property 'touches' of nullstarted @ d3-brush.js:312(anonymous function) @ d3.js:6596
57d3-brush.js:194 Uncaught TypeError: Cannot read property 'type' of undefined(anonymous function) @ d3-brush.js:194bindKey @ d3.js:6863selection_data @ d3.js:6913brush @ d3-brush.js:194selection_call @ d3.js:7005render 

please help me on this front.

**Comment by tomwanzek** [comment]
As part of some legacy D3v3 issue clean-up, can this issue be please closed?

D3v4 has been released and supported with actively maintained definitions for several months now, so it would be great to have only current issues open for clarity.

Thanks in advance!

cc @gustavderdrache @andy-ms
