### ISSUE TITLE
Twix typings are breaking in types-2.0 branch

### ISSUE THREAD

**Issue by rastographics** [DefinitelyTyped/DefinitelyTyped#11722]
- [x] I tried using the latest `twix/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `twix/index.d.ts`.
  - The authors of that type definition are cc/ @j3ko

We discovered in [my stackoverflow question](http://stackoverflow.com/a/39820782/2191642) that the typings for twix work fine with moment on the master branch, but the types-2.0 branch (which is what npm @types/twix uses) something is broken which cause twix not to be recognized as a property of moment() anymore. I'm using latest stable typescript 2.0.3.

**Comment by mhegazy** [comment]
this is the same issue as https://github.com/Microsoft/TypeScript/issues/11170

should be fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11547

**Comment by mhegazy** [comment]
should be fixed in `@types/twix@0.6.32`
