### ISSUE TITLE
Expect is not working with TS2, probably need ambient module 

### ISSUE THREAD

**Issue by mohsen1** [DefinitelyTyped/DefinitelyTyped#11720]
I'm trying to use `expect` with `@types/expect` and getting following error:

```
> tsc index.ts && node index.js

/Users/mazimi/Desktop/exp/index.js:3
expect_1["default"](1 + 2).toBe(3);
                   ^

TypeError: expect_1.default is not a function
```

I've created this repository to demonstrate the problem:
https://github.com/mohsen1/expect-tsd

I think expect should ambient modules just like mocha and others.

Also, we want to use `expect` without importing it. How can we declare globals for that without rewriting `expect.d.ts`?

/copy @RyanCavanaugh @vvakame @jmreidy

**Comment by vvakame** [comment]
https://github.com/mjackson/expect/blob/master/modules/index.js#L17
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/expect/expect.d.ts#L70
this line should use `export = expect;` instead of `export default expect;`.
could you send a pull request?

**Comment by mohsen1** [comment]
I get `[ts] An export assignment cannot be used in a module with other exported elements.` when I do that.

Expect library can be used like this:

```ts
import expect, {spyOn} from 'expect'

const o = {foo(){}};
spyOn(o, 'foo').andReturn(1);

expect(o.foo()).toEqual(1);

```

It has a default and multiple non-default exports...

**Comment by mohsen1** [comment]
There is alos this type definition that has much more for expect:

https://github.com/andrew-w-ross/typings-expect/blob/master/expect.d.ts

**Comment by vvakame** [comment]
ah, we need a hack.
add this code.
`namespace expect {}` above `export = expect;`

**Comment by Seikho** [comment]
@vvakame Needed a bit more re-organising than that unfortunately, but should be all good now.

**Comment by vvakame** [comment]
thanks!
@mohsen1 can I close this issue?

**Comment by mohsen1** [comment]
Sure
