### ISSUE TITLE
[angular-resource/index.d.ts] "Identifier 'ng' must be imported from a module

### ISSUE THREAD

**Issue by hisham** [DefinitelyTyped/DefinitelyTyped#11734]
- [x] I tried using the latest `angular-resource/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `angular-resource/index.d.ts`.
  - The authors of that type definition are cc/ @andy-ms @RyanCavanaugh @mhegazy 

Am running hybrid angular 2 & 1 app, with angular-cli (using webpack) and typescript. With the latest versions am getting this error: 

`ERROR in [default] <path>/node_modules/@types/angular-resource/index.d.ts:192:36 
Identifier 'ng' must be imported from a module`

The culprit line is: 

`get(name: '$resource'): ng.resource.IResourceService;`

'ng' is a deprecated namespace isn't it? Changing it to 'angular.resource.IResourceService' fixes the error.

**Comment by mhegazy** [comment]
What version of TS are you using? this error was suppressed in TS 2.0.3.

**Comment by hisham** [comment]
Looks like 2.0.0. Upgrading to TS 2.0.3 does seem to make the error go away. Regardless shouldn't ng.resource.IResourceService be updated to angular.resource.IResourceService?

**Comment by PrettyCities** [comment]
I'm having the same issue.

Hisham, have you been able to find a fix when using external imports?

When I try `import {angular} from 'angular'` I am told that `angular` doesn't export `angular`. Not sure how else to access the namespace...

**Comment by hisham** [comment]
@PrettyCities - I just upgraded to TS 2.0.3 and the error no longer appears. 

I import angular like so: 

`import * as angular from 'angular';
`
