### ISSUE TITLE
Passport - new instance

### ISSUE THREAD

**Issue by normalser** [DefinitelyTyped/DefinitelyTyped#11787]
- [x] I tried using the latest `xxxx/passport.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

'passport' module allows to create new instances like:

``` js
const passport = require('passport')
new passport.Passport()
```

This is useful when using with `passports` modules which requires multiple (separate) instances of `Passport`

`passport.d.ts` file currently won't allow to do that

Here is the missing export: https://github.com/jaredhanson/passport/blob/master/lib/index.js#L18

**Comment by vvakame** [comment]
cc/ @horiuchi

**Comment by horiuchi** [comment]
@wallverb I didn't know what allows to create new `passport` instance.
Where do you find that function? from source file?

I created the `passport.d.ts` file by reference to [the official document](http://passportjs.org/docs).
Thus I might miss also the other features that is not written in the document.

**Comment by wallverb** [comment]
@horiuchi Take a look in here:

https://github.com/jaredhanson/passport/blob/master/lib/index.js#L18

They create default instance and export it
```js
/**
 * Export default singleton.
 *
 * @api public
 */
exports = module.exports = new Passport();
```

But they also export that function so users can create new instance themselves:

```js
/**
 * Expose constructors.
 */
exports.Passport =
exports.Authenticator = Passport;
```

**Comment by horiuchi** [comment]
Yes, I'm sure that use case is correct.

Please fix the passport definition file, and send pull request! 👍

**Comment by wyattjoh** [comment]
Any progress on this one @horiuchi or @normalser?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
