### ISSUE TITLE
[request] co

### ISSUE THREAD

**Issue by antoniobusrod** [DefinitelyTyped/DefinitelyTyped#11788]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

**Comment by alreadyExisted** [comment]
This module already exists https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/coI

I think you need to close this issue /cc @vvakame
