### ISSUE TITLE
@types/chrome missing chrome-app

### ISSUE THREAD

**Issue by fortuna** [DefinitelyTyped/DefinitelyTyped#11809]
- [X] I tried using the latest `chrome/chrome-app.d.ts` file in this repo and had problems.
  - The authors of that type definition are @matthewkimber, @otiai10, @couven92, @RReverser

It's actually not clear to me whether a new directory should be created for `chrome-app` or whether the packaging for `chrome` is broken.

I used to be able to install `chrome-app` with typings, but I can't with `npm install @types/chrome-app`. If I use `npm install @types/chrome`, the installation succeeds, but it doesn't include `chrome-app`. The `chrome-app.d.ts` is in the repository under `chrome/`, but doesn't seem to be in the npm.

**Comment by fortuna** [comment]
It seems to be related to https://github.com/Microsoft/types-publisher/issues/68.
The @types publisher only publishes the `index.d.ts` file and ignores the rest.

**Comment by fortuna** [comment]
It seems this is being fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11811

**Comment by andy-ms** [comment]
Looks like it's fixed now.

**Comment by fortuna** [comment]
I can see `chrome-app.d.ts` under `node_modules/@types/chrome` now, but it seems it's being ignored by the @types system. How do we make that work? Shouldn't it be referenced by `index.d.ts`?

**Comment by andy-ms** [comment]
If `chrome-app.d.ts` and `chrome-cast.d.ts` should always be included, then `index.d.ts` should reference them. If they should be optional then you need to explicitly write `/// <reference types="chrome/chrome-app" />` when you use them.

**Comment by RReverser** [comment]
Yes, they're optional - not every user of chrome.d.ts needs namespaces for apps.
