### ISSUE TITLE
AreaChartOptions missing annotation(s)

### ISSUE THREAD

**Issue by jjhii** [DefinitelyTyped/DefinitelyTyped#11828]
I am using: DefinitelyTyped/google.visualization/google.visualization.d.ts 
Section: AreaChartOptions

https://google-developers.appspot.com/chart/interactive/docs/gallery/areachart#Configuration_Options

In my code I set the annotations for the chart options from the link above.  I get an error stating the option does not exist.  I think is should exist and am requesting it be added.  If I am incorrect about it belonging there could you advise me on the correct method of adding the annotations.

My current work around is the add the following two lines to the AreaChartOptions interface.
            annotation?: any;
            annotations?: any;

I used any for both of them, not sure if there is better option.
In regards to annotations, the closest I could find was ChartAnnotations.  It only has box and text styles and is missing several fields (duration, easing, startup, datum, doman, stem, highContrast, & others).  I am not sure if the missing fields should be added or a new annotations interface should be created.

my code:
    /// Set chart options
    var options: google.visualization.AreaChartOptions = {
        title: trans.get("PathProfileLabel"),
        hAxis: {
            title: trans.get("DistanceBetweenLabel") + " (" + hLabel + ")",
            titleTextStyle: { color: "#333" }
        },
        vAxis: {
            title: trans.get("NormalizedHeightLabel") + " (" + vLabel + ")"
        },
        series: {
            0: { color: "#6E9A3F" },
            1: { color: "#DBAF00", areaOpacity: "0.0" },
            2: { color: "#800080", areaOpacity: "0.0" },
            3: { color: "#5895DB", areaOpacity: "0.0" }
        },
        annotation: {
            5: { style: "letter" }
         },
        annotations: {
            textStyle: {
                bold: true,
                italic: true,
                color: "black"
            }
        }
    };

**Comment by danmana** [comment]
I updated the ChartAnnotations interface to include all fields common for all charts (datum, domain, stem etc). 
Bar and Column charts have 1 extra property, so I created an extension for them.

I added the _annotation**s**_ property to the AreaChartOptions, but I don't see any reference to a _annotation (singular)_ property in the docs for any of the charts, so I didn't add that one.
