### ISSUE TITLE
Superagent or Node typings: can't pipe to request stream

### ISSUE THREAD

**Issue by aseemk** [DefinitelyTyped/DefinitelyTyped#11837]
Hi there,

I'm new to TypeScript and these typings. Really impressive work by all of you. Thank you!

I'm using [Superagent](https://github.com/visionmedia/superagent) and the Superagent typings:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/superagent/index.d.ts

According to the Superagent docs, you can pipe streams to requests:

http://visionmedia.github.io/superagent/#piping-data

``` js
var request = require('superagent')
  , fs = require('fs');

var stream = fs.createReadStream('path/to/my.json');
var req = request.post('/somewhere');
req.type('json');
stream.pipe(req);
```

And the code actually works. But with these typings, that last line is a TypeScript error, because Node's `ReadableStream#pipe` takes a `WriteableStream`, while `SuperAgentRequest` is just a `Stream`.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c4e76d4c4c598290f1d0d6666917ef0ebc3452cc/superagent/index.d.ts#L23

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c4e76d4c4c598290f1d0d6666917ef0ebc3452cc/node/index.d.ts#L286

The SuperAgent code itself indeed inherits from just `Stream`:

https://github.com/visionmedia/superagent/blob/6e6f48fc72a99d183f9dcc34f816bbffccbaa96d/lib/node/index.js#L147

So I'm not sure where the typing is wrong, when this works. Any ideas?

Not sure who I should cc, but the contributors on the Superagent typing are:

@RyanCavanaugh
@sandersn
@minestarks
@andy-ms 

Thank you all again! Cheers. =)

**Comment by minestarks** [comment]
Thank you @aseemk. @varju appears to be the owner of this one. Please go ahead and open a PR. I'm not familiar with this library but I suspect you want to be looking [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/superagent/superagent.d.ts#L84) (not sure why that extends was commented out).

**Comment by varju** [comment]
I haven't been near TypeScript in a few years.  At this point I defer to others who are actively using these libraries.

**Comment by angadn** [comment]
@aseemk Same problem with typings for `request` - can't pipe :(

**Comment by hinell** [comment]
>[superagent/lib/node/index.js#L147](https://github.com/visionmedia/superagent/blob/6e6f48fc72a99d183f9dcc34f816bbffccbaa96d/lib/node/index.js#L147)

It seems `superagent` doesn't inherit stream at all since stream returned by require('stream'), it just nodejs' EventEmitter that is obviously isn't any stream at all. Just see nodejs core library code [here](https://github.com/nodejs/node/blob/master/lib/stream.js#L8):

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
