### ISSUE TITLE
Duplicate identifier 'Redux', 'History' in TypeScript 2.0

### ISSUE THREAD

**Issue by bccsafe** [DefinitelyTyped/DefinitelyTyped#11850]
I tried using the following repo

  "devDependencies": {
    "@types/history": "^2.0.38",
    "@types/react": "^0.14.39",
    "@types/react-dom": "^0.14.17",
    "@types/react-redux": "^4.4.32",
    "@types/react-router": "^2.0.37",
    "@types/react-router-redux": "^4.0.34",
    "@types/redux": "^3.6.31",
    "history": "^4.3.0",
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-redux": "^4.4.5",
    "react-router": "^2.8.1",
    "react-router-redux": "^4.0.6",
    "redux": "^3.6.0",
    "typescript": "^2.0.3",
  }

get the error:

ERROR in /Users/BccSafe/git/React-WebApp-Boilerplate/node_modules/typescript/lib/lib.es6.d.ts
(13274,11): error TS2300: Duplicate identifier 'History'.

ERROR in /Users/BccSafe/git/React-WebApp-Boilerplate/node_modules/typescript/lib/lib.es6.d.ts
(13284,13): error TS2300: Duplicate identifier 'History'.

ERROR in /Users/BccSafe/git/React-WebApp-Boilerplate/node_modules/@types/react-router-redux/node_modules/@types/history/index.d.ts
(8,21): error TS2300: Duplicate identifier 'History'.

ERROR in /Users/BccSafe/git/React-WebApp-Boilerplate/node_modules/@types/react-router-redux/node_modules/@types/redux/index.d.ts
(7,21): error TS2300: Duplicate identifier 'Redux'.

ERROR in /Users/BccSafe/git/React-WebApp-Boilerplate/node_modules/@types/react-redux/node_modules/@types/redux/index.d.ts
(7,21): error TS2300: Duplicate identifier 'Redux'.

ERROR in /Users/BccSafe/git/React-WebApp-Boilerplate/node_modules/@types/react-router/node_modules/@types/history/index.d.ts
(8,21): error TS2300: Duplicate identifier 'History'.
webpack: bundle is now VALID.

All my code in [https://github.com/bccsafe/React-WebApp-Boilerplate](https://github.com/bccsafe/React-WebApp-Boilerplate)

@vvakame @isman-usoh @sheetalkamat @krlm

**Comment by mhegazy** [comment]
This looks like a ts-loader issue. i do not see any errors running tsc.

```cmd
c:\test\11850\React-WebApp-Boilerplate>git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

c:\test\11850\React-WebApp-Boilerplate>node_modules\.bin\tsc --v
Version 2.0.3

c:\test\11850\React-WebApp-Boilerplate>node_modules\.bin\tsc --p tsconfig.dev.json

c:\test\11850\React-WebApp-Boilerplate>echo %ERRORLEVEL%
0

c:\test\11850\React-WebApp-Boilerplate>node_modules\.bin\tsc --p tsconfig.prod.json

c:\test\11850\React-WebApp-Boilerplate>echo %ERRORLEVEL%
0
```

**Comment by mhegazy** [comment]
//cc: @jbrantly and @johnnyreilly

**Comment by bccsafe** [comment]
I tried removing `node_modules` and then run `npm install`

it solved my problem
