### ISSUE TITLE
@types/moment doesn't work

### ISSUE THREAD

**Issue by Mosho1** [DefinitelyTyped/DefinitelyTyped#11864]
I'm not sure you guys are responsible for it, but `npm install @types/moment` doesn't install `.d.ts` files and the npm package itself seems a bit broken.

https://www.npmjs.com/package/@types/moment

**Comment by andy-ms** [comment]
Per the README:

```
This is a stub types definition for Moment (https://github.com/moment/moment).
Moment provides its own type definitions, so you don't need @types/moment installed!
```

That said, installing `@types/moment` should have showed a deprecation message and installed the "moment" package for you. So, the compiler should have still picked up on typings for "moment". Can you provide steps to reproduce your error?

**Comment by IRus** [comment]
Hi!

For sure `@types/moment` doesn't contains definitions. So i found moment.d.ts in moment package.

I think i can write in top of my file:

```
import moment from 'moment';
```

It's works, but vs code show error (webstorm actually find file and provide autocompele, etc.):
```
[ts] Cannot find module 'moment'.
```
and same error while compilation(ts-loader):
```
(13,20): error TS2307: Cannot find module 'moment'.
```

I think i miss something after upgrading to version 2 (currently i use daily ts 2.1.0 builds, but same with 2.0.3)

**Comment by cwmoo740** [comment]
tsconfig.json: 

```
"files": [
    "node_modules/moment/moment.d.ts"
    /// whatever other files you want
]
```

Tell tsc to include that type file manually. It should also work with vscode this way.

**Comment by IRus** [comment]
Hmm, this fix vscode, but doesn't loader (ts-loader).

**Comment by IRus** [comment]
According ts [documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) package should include `types` (or `typings`) property in `package.json` to point compiler to definitions. 

So i wonder why i should pointing typescript to moment's definitions at all.

**Comment by IRus** [comment]
I take a look at `moment.d.ts` and found that it [doesn't declare](https://github.com/moment/moment/blob/develop/moment.d.ts#L10) any module, but namespace: 

```
declare namespace moment {
```
So looks like that why i get following error from compiler:

```
(13,20): error TS2307: Cannot find module 'moment'.
```

I declare moment module inside moment.d.ts:

```
// export = moment; // commented this
 
declare module 'moment' {
  export default moment;
}
```

And error disappears.

So i have few questions here:
- declaring namespace is different from declaring module? than how to support both use cases for library?
- is i miss something? 

Btw. i doesn't have this error and problem when use typings.

**Comment by andy-ms** [comment]
The moment declarations are an external module declaration -- they have `export =` at the [bottom](https://github.com/moment/moment/blob/develop/moment.d.ts#L560) of that file.

This works for me:

```sh
mkdir repro
cd repro
echo '{}' > tsconfig.json
echo 'import moment = require("moment")' > a.ts
npm install moment
tsc --version # Version 2.0.3
tsc
```

You shouldn't need the `"files"` kludge.
Can you try these steps? And also try them with your own `tsconfig.json` to see if that is the problem?

(For posterity, the version of `moment` I installed here is `2.15.1`.)

**Comment by IRus** [comment]
@andy-ms yes, this work for me too. But i really doesn't like `require` syntax and prefer es6 import.
By the way es6 imports works too:
```
yoda@ux32vd:19:44:~/repro $ cat a.ts 
import * as moment from "moment";

const date = moment().format("YYYY");

console.log(date);
yoda@ux32vd:19:44:~/repro $ ./node_modules/.bin/tsc --version
Version 2.0.3
yoda@ux32vd:19:44:~/repro $ ./node_modules/.bin/tsc
yoda@ux32vd:19:44:~/repro $ node a.js 
2016
yoda@ux32vd:19:44:~/repro $ 
```
 
So i think this is issue with `ts-loader` itself.

Thank you for your time!

**Comment by misak113** [comment]
I solved all related problems by using awesome-typescript-loader instead of ts-loader :)

**Comment by claudeduguay** [comment]
The following worked for me. Just wrap the module declaration around the export.

declare module 'moment' {
  export = moment;
}

**Comment by ktrzeciaknubisa** [comment]
Based on what you guys wrote above, the ultimate solution for me was to add index.d.ts file to moment directory.
No imports or updating tsconfig.json was necessary.

Basically after I executed: `npm i "@types/moment`, I had the following folder structure:

    + node modules
        + @types
            + moment
                index.d.ts <--  this is a file I created
                package.json
        + moment
            + ts3.1-typings
                moment.d.ts
            moment.d.ts  
            package.json
      
And the file contents for index.d.ts is:

    /// <reference path="../../moment/ts3.1-typings/moment.d.ts" />
    declare module 'moment' {
       export default moment;
    }
