### ISSUE TITLE
[lodash] Need to build 'lodash.xxx' submodule definition?

### ISSUE THREAD

**Issue by TonyPythoneer** [DefinitelyTyped/DefinitelyTyped#11866]
Hi, @bczengel, @chrootsu, @stepancar

I found `lodash` can install submodule, not all module, such as `lodash.xxx`. Do you think it can do  submodule definitions for it or not?

If it can do, how to manage or make the submodule definitions?

This is my elementary idea.

```
// Type definitions for lodash.assign
// Project: http://lodash.com/
// Definitions by: Brian Zengel <https://github.com/bczengel>, Ilya Mochalov <https://github.com/chrootsu>, Stepan Mikhaylyuk <https://github.com/stepancar>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference path="../lodash/lodash.d.ts" />

declare module "lodash.assign" {
   const assign: typeof _.assign;
   export = assign;
}
```

The `lodash.assign` submodule definition calls the `lodash` main definition. It doesn't need to maintain two definitions because `lodash.assign` type source is from `lodash`.

But the disadvantage is it will create too many submodule definitions as projects in DefinitelyTyped.

Or, in `lodash` definition, it declares `lodash.xxx` module, it will avoid issue about making too many  projects in DefinitelyTyped.

How do you think?

**Comment by TonyPythoneer** [comment]
No one wants to dicuss with me? :sob:

**Comment by vvakame** [comment]
You can do it as you like! 👍 
now, lodash authors is inactive in this repo maybe...

**Comment by stepancar** [comment]
@TonyPythoneer , good suggestion, but i need time to thinking about it

**Comment by TonyPythoneer** [comment]
@vvakame I hope so but this defintiomn is very big and is universally used by developers.  I still want to find authors to discuss this is available or not. I don't hope this will be futile. 😄

**Comment by TonyPythoneer** [comment]
@stepancar I will expect your response. 😄

**Comment by TonyPythoneer** [comment]
@vvakame I think you can join this discussion.
Suppose lodash has 50 submodules can be installed individually, it will create 50 type definitions for all submodules.
As a DefinitelyTyped manager, how do you think?

**Comment by stepancar** [comment]
@TonyPythoneer, I think all definitions for lodash shoul be store in one repo

**Comment by TonyPythoneer** [comment]
@stepancar OK, I got it. I will do it. :smile:
