### ISSUE TITLE
Chance.js: Add `seed` property

### ISSUE THREAD

**Issue by LOZORD** [DefinitelyTyped/DefinitelyTyped#11876]
- [x] I want to talk about `chance/chance.d.ts`.
  - The authors of that type definition are @vvakame 

Since the property [is used](https://github.com/chancejs/chancejs/blob/master/chance.js#L56), `seed` should be present in the type definition here. From my brief look, the type of seed could be `number` or `number | undefined` or `number?`.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by LOZORD** [comment]
Thanks 😄
