### ISSUE TITLE
Breaking change to React StatelessComponent definition

### ISSUE THREAD

**Issue by janslow** [DefinitelyTyped/DefinitelyTyped#11929]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `react/index.d.ts`. (on the types-2.0 branch)
  - The authors of that type definition are cc/ @aozgaa 

Using `typescript@2.0.3` with `strictNullChecks=true`.

After updating from `@types/react@0.14.40` to `0.14.41` (PR #11912 from @donaldpipowitch), I've started getting errors on code which worked before:

For example,

``` bash
$ tsc -p .
src/app/test.tsx(9,7): error TS2605: JSX element type 'ReactElement<any> | null' is not a constructor function for JSX elements.
  Type 'null' is not assignable to type 'ElementClass'.
```

``` tsx
import * as React from 'react';
import { StatelessComponent } from 'react';

const ElementA: StatelessComponent<any> = (props: {}) => (<div />);

function ElementB(props: {}): JSX.Element {
  return (
    <div>
      <ElementA />
    </div>
  );
}
```

It works fine if I use `createElement(ElementA, {})` instead of the TSX form.

**Comment by donaldpipowitch** [comment]
Seems to work for me in a quick test:

```typescript
import React, { StatelessComponent } from 'react';

const ElementA: StatelessComponent<any> = (props: {}) => (<div />);

function ElementB(props: {}): JSX.Element {
  return (
    <div>
      <ElementA />
    </div>
  );
}
```

```json
{
  "compilerOptions": {
    "target": "es6",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "strictNullChecks": false,
    "jsx": "react"
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by donaldpipowitch** [comment]
I'm sorry. I'll try to fix this.

**Comment by donaldpipowitch** [comment]
Sorry, I think this could be a bug with TypeScript itself. I'll write a bug issue there and make a revertable pull request.

**Comment by janslow** [comment]
Thanks.

**Comment by janslow** [comment]
@donaldpipowitch, have you created a PR request for this? Thanks.

**Comment by donaldpipowitch** [comment]
My PR was integrated into this PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11935, but sadly no one has reviewed it so far :(

**Comment by donaldpipowitch** [comment]
@janslow Should be fixed with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11935

Could you test and close this issue, if it works?

**Comment by janslow** [comment]
Yep, that's fixed it now, thanks!
