### ISSUE TITLE
React typings not working

### ISSUE THREAD

**Issue by ajainvivek** [DefinitelyTyped/DefinitelyTyped#11922]
React typings throws errors in terminal after installation via typings

```
error TS2320: Interface 'Element' cannot simultaneously extend types 'ReactElement<any>' and 'ReactElement<any>'.
  Named property 'type' of types 'ReactElement<any>' and 'ReactElement<any>' are not identical.

ERROR in /Users/ajvivek/Dev/ES6/motionize-code/typings/globals/react/index.d.ts
(2375,5): error TS1036: Statements are not allowed in ambient contexts.

ERROR in /Users/ajvivek/Dev/ES6/motionize-code/typings/globals/react-dom/index.d.ts
(69,5): error TS2309: An export assignment cannot be used in a module with other exported elements.

ERROR in /Users/ajvivek/Dev/ES6/motionize-code/node_modules/@types/react-dom/index.d.ts
(19,31): error TS2315: Type 'DOMAttributes' is not generic.

ERROR in /Users/ajvivek/Dev/ES6/motionize-code/node_modules/@types/react-dom/index.d.ts
(44,60): error TS2315: Type 'DOMAttributes' is not generic.

ERROR in /Users/ajvivek/Dev/ES6/motionize-code/node_modules/@types/react/index.d.ts
(2368,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'a' must be of type 'HTMLProps<HTMLAnchorElement>', but here has type 'HTMLProps<HTMLAnchorElement>'.

ERROR in /Users/ajvivek/Dev/ES6/motionize-code/node_modules/@types/react/index.d.ts
(2369,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'abbr' must be of type 'HTMLProps<HTMLElement>', but here has type 'HTMLProps<HTMLElement>'.

```
**index.d.ts**
```
/// <reference path="globals/react/index.d.ts" />
/// <reference path="globals/react-dom/index.d.ts" />
```

Is anyone facing this issue?

**Comment by janslow** [comment]
I'm fetching the react definitions via the `@types/react` package (with `typescript@2.0.3` and `strictNullChecks`) and it broke for me going from `0.14.40` to `0.14.41`. However, I think my issue is unrelated to yours.

It looks like you are pulling in two separate react definitions, using both typings and the new `@types` packages.

Try deleting react from your typings package and explicitly installing `@types/react` instead. See [this TypeScript blog post](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) for more info on @types.

**Comment by ajainvivek** [comment]
I figured out the issue finally.

I went on to install types once via tsd and then typings that led to duplicate typings.

Deleted the @types folder to resolve my issue.

**Comment by bsed** [comment]
../node_modules/@types/react-dom/index.d.ts(15,36): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(16,52): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(18,59): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(20,20): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(24,20): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(28,20): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(32,20): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(33,64): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(33,113): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(35,48): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(43,88): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(46,20): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(51,20): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(56,20): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(61,20): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(62,64): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react-dom/index.d.ts(62,113): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react/index.d.ts(47,64): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react/index.d.ts(52,42): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(55,64): error TS2304: Cannot find name 'SVGElement'.
../node_modules/@types/react/index.d.ts(55,77): error TS2304: Cannot find name 'SVGElement'.
../node_modules/@types/react/index.d.ts(77,64): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react/index.d.ts(81,37): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(84,49): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(87,59): error TS2304: Cannot find name 'SVGElement'.
../node_modules/@types/react/index.d.ts(87,72): error TS2304: Cannot find name 'SVGElement'.
../node_modules/@types/react/index.d.ts(108,66): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react/index.d.ts(117,66): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react/index.d.ts(138,65): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react/index.d.ts(166,48): error TS2304: Cannot find name 'Element'.
../node_modules/@types/react/index.d.ts(279,24): error TS2304: Cannot find name 'EventTarget'.
../node_modules/@types/react/index.d.ts(284,22): error TS2304: Cannot find name 'Event'.
../node_modules/@types/react/index.d.ts(291,17): error TS2304: Cannot find name 'EventTarget'.
../node_modules/@types/react/index.d.ts(297,24): error TS2304: Cannot find name 'DataTransfer'.
../node_modules/@types/react/index.d.ts(305,23): error TS2304: Cannot find name 'DataTransfer'.
../node_modules/@types/react/index.d.ts(309,24): error TS2304: Cannot find name 'EventTarget'.
../node_modules/@types/react/index.d.ts(316,17): error TS2304: Cannot find name 'EventTarget'.
../node_modules/@types/react/index.d.ts(345,24): error TS2304: Cannot find name 'EventTarget'.
../node_modules/@types/react/index.d.ts(437,47): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(440,46): error TS2304: Cannot find name 'SVGElement'.
../node_modules/@types/react/index.d.ts(440,75): error TS2304: Cannot find name 'SVGElement'.
../node_modules/@types/react/index.d.ts(2195,52): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2456,24): error TS2304: Cannot find name 'HTMLAnchorElement'.
../node_modules/@types/react/index.d.ts(2457,27): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2458,30): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2459,27): error TS2304: Cannot find name 'HTMLAreaElement'.
../node_modules/@types/react/index.d.ts(2460,30): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2461,28): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2462,28): error TS2304: Cannot find name 'HTMLAudioElement'.
../node_modules/@types/react/index.d.ts(2463,24): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2464,27): error TS2304: Cannot find name 'HTMLBaseElement'.
../node_modules/@types/react/index.d.ts(2465,26): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2466,26): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2467,26): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2468,33): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2469,27): error TS2304: Cannot find name 'HTMLBodyElement'.
../node_modules/@types/react/index.d.ts(2470,25): error TS2304: Cannot find name 'HTMLBRElement'.
../node_modules/@types/react/index.d.ts(2471,29): error TS2304: Cannot find name 'HTMLButtonElement'.
../node_modules/@types/react/index.d.ts(2472,29): error TS2304: Cannot find name 'HTMLCanvasElement'.
../node_modules/@types/react/index.d.ts(2473,30): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2474,27): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2475,27): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2476,26): error TS2304: Cannot find name 'HTMLTableColElement'.
../node_modules/@types/react/index.d.ts(2477,31): error TS2304: Cannot find name 'HTMLTableColElement'.
../node_modules/@types/react/index.d.ts(2478,27): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2479,31): error TS2304: Cannot find name 'HTMLDataListElement'.
../node_modules/@types/react/index.d.ts(2480,25): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2481,26): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2482,30): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2483,26): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2484,29): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2485,26): error TS2304: Cannot find name 'HTMLDivElement'.
../node_modules/@types/react/index.d.ts(2486,25): error TS2304: Cannot find name 'HTMLDListElement'.
../node_modules/@types/react/index.d.ts(2487,25): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2488,25): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2489,28): error TS2304: Cannot find name 'HTMLEmbedElement'.
../node_modules/@types/react/index.d.ts(2490,31): error TS2304: Cannot find name 'HTMLFieldSetElement'.
../node_modules/@types/react/index.d.ts(2491,33): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2492,29): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2493,29): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2494,27): error TS2304: Cannot find name 'HTMLFormElement'.
../node_modules/@types/react/index.d.ts(2495,25): error TS2304: Cannot find name 'HTMLHeadingElement'.
../node_modules/@types/react/index.d.ts(2496,25): error TS2304: Cannot find name 'HTMLHeadingElement'.
../node_modules/@types/react/index.d.ts(2497,25): error TS2304: Cannot find name 'HTMLHeadingElement'.
../node_modules/@types/react/index.d.ts(2498,25): error TS2304: Cannot find name 'HTMLHeadingElement'.
../node_modules/@types/react/index.d.ts(2499,25): error TS2304: Cannot find name 'HTMLHeadingElement'.
../node_modules/@types/react/index.d.ts(2500,25): error TS2304: Cannot find name 'HTMLHeadingElement'.
../node_modules/@types/react/index.d.ts(2501,27): error TS2304: Cannot find name 'HTMLHeadElement'.
../node_modules/@types/react/index.d.ts(2502,29): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2503,29): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2504,25): error TS2304: Cannot find name 'HTMLHRElement'.
../node_modules/@types/react/index.d.ts(2505,27): error TS2304: Cannot find name 'HTMLHtmlElement'.
../node_modules/@types/react/index.d.ts(2506,24): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2507,29): error TS2304: Cannot find name 'HTMLIFrameElement'.
../node_modules/@types/react/index.d.ts(2508,26): error TS2304: Cannot find name 'HTMLImageElement'.
../node_modules/@types/react/index.d.ts(2509,40): error TS2304: Cannot find name 'HTMLInputElement'.
../node_modules/@types/react/index.d.ts(2510,26): error TS2304: Cannot find name 'HTMLModElement'.
../node_modules/@types/react/index.d.ts(2511,26): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2512,29): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2513,28): error TS2304: Cannot find name 'HTMLLabelElement'.
../node_modules/@types/react/index.d.ts(2514,29): error TS2304: Cannot find name 'HTMLLegendElement'.
../node_modules/@types/react/index.d.ts(2515,25): error TS2304: Cannot find name 'HTMLLIElement'.
../node_modules/@types/react/index.d.ts(2516,27): error TS2304: Cannot find name 'HTMLLinkElement'.
../node_modules/@types/react/index.d.ts(2517,27): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2518,26): error TS2304: Cannot find name 'HTMLMapElement'.
../node_modules/@types/react/index.d.ts(2519,27): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2520,27): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2521,31): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2522,27): error TS2304: Cannot find name 'HTMLMetaElement'.
../node_modules/@types/react/index.d.ts(2523,28): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2524,26): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2525,31): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2526,29): error TS2304: Cannot find name 'HTMLObjectElement'.
../node_modules/@types/react/index.d.ts(2527,25): error TS2304: Cannot find name 'HTMLOListElement'.
../node_modules/@types/react/index.d.ts(2528,31): error TS2304: Cannot find name 'HTMLOptGroupElement'.
../node_modules/@types/react/index.d.ts(2529,29): error TS2304: Cannot find name 'HTMLOptionElement'.
../node_modules/@types/react/index.d.ts(2530,29): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2531,24): error TS2304: Cannot find name 'HTMLParagraphElement'.
../node_modules/@types/react/index.d.ts(2532,28): error TS2304: Cannot find name 'HTMLParamElement'.
../node_modules/@types/react/index.d.ts(2533,30): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2534,26): error TS2304: Cannot find name 'HTMLPreElement'.
../node_modules/@types/react/index.d.ts(2535,31): error TS2304: Cannot find name 'HTMLProgressElement'.
../node_modules/@types/react/index.d.ts(2536,24): error TS2304: Cannot find name 'HTMLQuoteElement'.
../node_modules/@types/react/index.d.ts(2537,25): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2538,25): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2539,27): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2540,24): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2541,27): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2542,29): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2543,30): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2544,41): error TS2304: Cannot find name 'HTMLSelectElement'.
../node_modules/@types/react/index.d.ts(2545,28): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2546,29): error TS2304: Cannot find name 'HTMLSourceElement'.
../node_modules/@types/react/index.d.ts(2547,27): error TS2304: Cannot find name 'HTMLSpanElement'.
../node_modules/@types/react/index.d.ts(2548,29): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2549,28): error TS2304: Cannot find name 'HTMLStyleElement'.
../node_modules/@types/react/index.d.ts(2550,26): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2551,30): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2552,26): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2553,28): error TS2304: Cannot find name 'HTMLTableElement'.
../node_modules/@types/react/index.d.ts(2554,28): error TS2304: Cannot find name 'HTMLTableSectionElement'.
../node_modules/@types/react/index.d.ts(2555,25): error TS2304: Cannot find name 'HTMLTableDataCellElement'.
../node_modules/@types/react/index.d.ts(2556,43): error TS2304: Cannot find name 'HTMLTextAreaElement'.
../node_modules/@types/react/index.d.ts(2557,28): error TS2304: Cannot find name 'HTMLTableSectionElement'.
../node_modules/@types/react/index.d.ts(2558,25): error TS2304: Cannot find name 'HTMLTableHeaderCellElement'.
../node_modules/@types/react/index.d.ts(2559,28): error TS2304: Cannot find name 'HTMLTableSectionElement'.
../node_modules/@types/react/index.d.ts(2560,27): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2561,28): error TS2304: Cannot find name 'HTMLTitleElement'.
../node_modules/@types/react/index.d.ts(2562,25): error TS2304: Cannot find name 'HTMLTableRowElement'.
../node_modules/@types/react/index.d.ts(2563,28): error TS2304: Cannot find name 'HTMLTrackElement'.
../node_modules/@types/react/index.d.ts(2564,24): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2565,25): error TS2304: Cannot find name 'HTMLUListElement'.
../node_modules/@types/react/index.d.ts(2566,28): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2567,28): error TS2304: Cannot find name 'HTMLVideoElement'.
../node_modules/@types/react/index.d.ts(2568,26): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2646,21): error TS2304: Cannot find name 'StyleMedia'.
../node_modules/@types/react/index.d.ts(2647,19): error TS2304: Cannot find name 'Document'.
../node_modules/@types/react/index.d.ts(2652,17): error TS2304: Cannot find name 'EventTarget'.
../node_modules/@types/react/index.d.ts(2682,32): error TS2304: Cannot find name 'HTMLAnchorElement'.
../node_modules/@types/react/index.d.ts(2683,35): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2684,38): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2685,35): error TS2304: Cannot find name 'HTMLAreaElement'.
../node_modules/@types/react/index.d.ts(2686,38): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2687,36): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2688,36): error TS2304: Cannot find name 'HTMLAudioElement'.
../node_modules/@types/react/index.d.ts(2689,32): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2690,35): error TS2304: Cannot find name 'HTMLBaseElement'.
../node_modules/@types/react/index.d.ts(2691,34): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2692,34): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2693,34): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2694,41): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2695,35): error TS2304: Cannot find name 'HTMLBodyElement'.
../node_modules/@types/react/index.d.ts(2696,33): error TS2304: Cannot find name 'HTMLBRElement'.
../node_modules/@types/react/index.d.ts(2697,37): error TS2304: Cannot find name 'HTMLButtonElement'.
../node_modules/@types/react/index.d.ts(2698,37): error TS2304: Cannot find name 'HTMLCanvasElement'.
../node_modules/@types/react/index.d.ts(2699,38): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2700,35): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2701,35): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2702,34): error TS2304: Cannot find name 'HTMLTableColElement'.
../node_modules/@types/react/index.d.ts(2703,39): error TS2304: Cannot find name 'HTMLTableColElement'.
../node_modules/@types/react/index.d.ts(2704,35): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2705,39): error TS2304: Cannot find name 'HTMLDataListElement'.
../node_modules/@types/react/index.d.ts(2706,33): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2707,34): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2708,38): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2709,34): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2710,37): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2711,34): error TS2304: Cannot find name 'HTMLDivElement'.
../node_modules/@types/react/index.d.ts(2712,33): error TS2304: Cannot find name 'HTMLDListElement'.
../node_modules/@types/react/index.d.ts(2713,33): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2714,33): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2715,36): error TS2304: Cannot find name 'HTMLEmbedElement'.
../node_modules/@types/react/index.d.ts(2716,39): error TS2304: Cannot find name 'HTMLFieldSetElement'.
../node_modules/@types/react/index.d.ts(2717,41): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2718,37): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2719,37): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2720,35): error TS2304: Cannot find name 'HTMLFormElement'.
../node_modules/@types/react/index.d.ts(2721,33): error TS2304: Cannot find name 'HTMLHeadingElement'.
../node_modules/@types/react/index.d.ts(2722,33): error TS2304: Cannot find name 'HTMLHeadingElement'.
../node_modules/@types/react/index.d.ts(2723,33): error TS2304: Cannot find name 'HTMLHeadingElement'.
../node_modules/@types/react/index.d.ts(2724,33): error TS2304: Cannot find name 'HTMLHeadingElement'.
../node_modules/@types/react/index.d.ts(2725,33): error TS2304: Cannot find name 'HTMLHeadingElement'.
../node_modules/@types/react/index.d.ts(2726,33): error TS2304: Cannot find name 'HTMLHeadingElement'.
../node_modules/@types/react/index.d.ts(2727,35): error TS2304: Cannot find name 'HTMLHeadElement'.
../node_modules/@types/react/index.d.ts(2728,37): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2729,37): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2730,33): error TS2304: Cannot find name 'HTMLHRElement'.
../node_modules/@types/react/index.d.ts(2731,35): error TS2304: Cannot find name 'HTMLHtmlElement'.
../node_modules/@types/react/index.d.ts(2732,32): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2733,37): error TS2304: Cannot find name 'HTMLIFrameElement'.
../node_modules/@types/react/index.d.ts(2734,34): error TS2304: Cannot find name 'HTMLImageElement'.
../node_modules/@types/react/index.d.ts(2735,48): error TS2304: Cannot find name 'HTMLInputElement'.
../node_modules/@types/react/index.d.ts(2736,34): error TS2304: Cannot find name 'HTMLModElement'.
../node_modules/@types/react/index.d.ts(2737,34): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2738,37): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2739,36): error TS2304: Cannot find name 'HTMLLabelElement'.
../node_modules/@types/react/index.d.ts(2740,37): error TS2304: Cannot find name 'HTMLLegendElement'.
../node_modules/@types/react/index.d.ts(2741,33): error TS2304: Cannot find name 'HTMLLIElement'.
../node_modules/@types/react/index.d.ts(2742,35): error TS2304: Cannot find name 'HTMLLinkElement'.
../node_modules/@types/react/index.d.ts(2743,35): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2744,34): error TS2304: Cannot find name 'HTMLMapElement'.
../node_modules/@types/react/index.d.ts(2745,35): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2746,35): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2747,39): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2748,35): error TS2304: Cannot find name 'HTMLMetaElement'.
../node_modules/@types/react/index.d.ts(2749,36): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2750,34): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2751,38): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2752,39): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2753,37): error TS2304: Cannot find name 'HTMLObjectElement'.
../node_modules/@types/react/index.d.ts(2754,33): error TS2304: Cannot find name 'HTMLOListElement'.
../node_modules/@types/react/index.d.ts(2755,39): error TS2304: Cannot find name 'HTMLOptGroupElement'.
../node_modules/@types/react/index.d.ts(2756,37): error TS2304: Cannot find name 'HTMLOptionElement'.
../node_modules/@types/react/index.d.ts(2757,37): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2758,32): error TS2304: Cannot find name 'HTMLParagraphElement'.
../node_modules/@types/react/index.d.ts(2759,36): error TS2304: Cannot find name 'HTMLParamElement'.
../node_modules/@types/react/index.d.ts(2760,38): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2761,34): error TS2304: Cannot find name 'HTMLPreElement'.
../node_modules/@types/react/index.d.ts(2762,39): error TS2304: Cannot find name 'HTMLProgressElement'.
../node_modules/@types/react/index.d.ts(2763,32): error TS2304: Cannot find name 'HTMLQuoteElement'.
../node_modules/@types/react/index.d.ts(2764,33): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2765,33): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2766,35): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2767,32): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2768,35): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2769,37): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2770,38): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2771,49): error TS2304: Cannot find name 'HTMLSelectElement'.
../node_modules/@types/react/index.d.ts(2772,36): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2773,37): error TS2304: Cannot find name 'HTMLSourceElement'.
../node_modules/@types/react/index.d.ts(2774,35): error TS2304: Cannot find name 'HTMLSpanElement'.
../node_modules/@types/react/index.d.ts(2775,37): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2776,36): error TS2304: Cannot find name 'HTMLStyleElement'.
../node_modules/@types/react/index.d.ts(2777,34): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2778,38): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2779,34): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2780,36): error TS2304: Cannot find name 'HTMLTableElement'.
../node_modules/@types/react/index.d.ts(2781,36): error TS2304: Cannot find name 'HTMLTableSectionElement'.
../node_modules/@types/react/index.d.ts(2782,33): error TS2304: Cannot find name 'HTMLTableDataCellElement'.
../node_modules/@types/react/index.d.ts(2783,51): error TS2304: Cannot find name 'HTMLTextAreaElement'.
../node_modules/@types/react/index.d.ts(2784,36): error TS2304: Cannot find name 'HTMLTableSectionElement'.
../node_modules/@types/react/index.d.ts(2785,33): error TS2304: Cannot find name 'HTMLTableHeaderCellElement'.
../node_modules/@types/react/index.d.ts(2786,36): error TS2304: Cannot find name 'HTMLTableSectionElement'.
../node_modules/@types/react/index.d.ts(2787,35): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2788,36): error TS2304: Cannot find name 'HTMLTitleElement'.
../node_modules/@types/react/index.d.ts(2789,33): error TS2304: Cannot find name 'HTMLTableRowElement'.
../node_modules/@types/react/index.d.ts(2790,36): error TS2304: Cannot find name 'HTMLTrackElement'.
../node_modules/@types/react/index.d.ts(2791,32): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2792,33): error TS2304: Cannot find name 'HTMLUListElement'.
../node_modules/@types/react/index.d.ts(2793,36): error TS2304: Cannot find name 'HTMLElement'.
../node_modules/@types/react/index.d.ts(2794,36): error TS2304: Cannot find name 'HTMLVideoElement'.
../node_modules/@types/react/index.d.ts(2795,34): error TS2304: Cannot find name 'HTMLElement'.

**Comment by mohsen1** [comment]
# `npm ls` is your friend 

Try running a `npm ls --depth=3` (types don't go deeper) to see an offending `@types/react` or `@types/react-dom` instance.

I usually delete `@types` section of my lock file (`yarn.lock` or `package-lock.json`) and remove `node_modules` and re-lock my dependencies when this happens. There is probably a more proper way of forcing deep dependencies to upgrade to latest. Please let others know if you know that!

**Comment by xogeny** [comment]
For what it is worth, I ran across this issue recently when using [`create-react-app` with TypeScript](https://github.com/wmonk/create-react-app-typescript).  The issue was that when resolving versions for `@types/react`, my main `package.json` had the rule "^16.4.8" while `@types/react-dom`'s `package.json` had `"*"` (I really don't know why they do that, can anybody explain that...seems very sloppy to me).

The result was that `@types/react-dom` installed `@types/react` version `16.4.7` (why?!? when `16.4.8` was available?!) but the main `package.json` wanted at least `16.4.8` so `yarn` installed two different versions.  So I changed the rule for `@types/react` in my `package.json` from `"^16.4.8"` to `"16.4.7"` (back one patch level and  no `^`) so that it would match what `@types/react-dom` was picking up.

Not sure why this is necessary (they could both just pick `16.4.8`?!?).  But it worked so I thought I'd share that for anybody else showing up here.

HTH

**Comment by kaimiyang** [comment]
@mohsen1 it's useful...^o^

**Comment by didiyou** [comment]
> For what it is worth, I ran across this issue recently when using [`create-react-app` with TypeScript](https://github.com/wmonk/create-react-app-typescript). The issue was that when resolving versions for `@types/react`, my main `package.json` had the rule "^16.4.8" while `@types/react-dom`'s `package.json` had `"*"` (I really don't know why they do that, can anybody explain that...seems very sloppy to me).
> 
> The result was that `@types/react-dom` installed `@types/react` version `16.4.7` (why?!? when `16.4.8` was available?!) but the main `package.json` wanted at least `16.4.8` so `yarn` installed two different versions. So I changed the rule for `@types/react` in my `package.json` from `"^16.4.8"` to `"16.4.7"` (back one patch level and no `^`) so that it would match what `@types/react-dom` was picking up.
> 
> Not sure why this is necessary (they could both just pick `16.4.8`?!?). But it worked so I thought I'd share that for anybody else showing up here.
> 
> HTH

but how can I know the version of  @types/react by @types/react-dom ?
