### ISSUE TITLE
Getting 'Sinon is not defined' at runtime

### ISSUE THREAD

**Issue by mcm-ham** [DefinitelyTyped/DefinitelyTyped#11947]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4bb4c29cad/sinon/sinon.d.ts#L12

Defines the namespace as `Sinon`, however at runtime I get a `Sinon is not defined` error. If I change the namespace to `sinon` then it works fine. I'm using the npm package for sinon ver 1.17.6. Here is the code where it seems to define the namespace:

`node_modules/sinon/pkg/sinon.js`

``` js
(function (root, factory) {
  'use strict';
  if (typeof define === 'function' && define.amd) {
    define('sinon', [], function () {
      return (root.sinon = factory());
    });
  } else if (typeof exports === 'object') {
    module.exports = factory();
  } else {
    root.sinon = factory();
  }
}
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by mcm-ham** [comment]
Sorry missed your message to create PR. Looks like this issue has now been fixed anyway:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/sinon/index.d.ts
```ts
export = Sinon;
export as namespace sinon;
```
