### ISSUE TITLE
Missing properties and types Fabric.js

### ISSUE THREAD

**Issue by abnersouzarocket** [DefinitelyTyped/DefinitelyTyped#11952]
[X] I want to talk about `fabricjs.d.ts`.
 Version: Type definitions for FabricJS v1.5.0
 @nertzy @doug @evmar 

Hi Guys, I've been using the the fabric.js.d.ts notice couple of issue while using it.

**1.** There is not way to set the **width** and **height** in the fabric.Canvas initializer or after the initialization.
**In JS**
`var canvas = new fabric.Canvas('c', {
                isDrawingMode: true,
                width: 500,
                height: 400,
                freeDrawingCursor: "default",
                backgroundColor: "transparent"
            });`

**Or**
`canvas.width = 100;
 canvas.height = 100;
`
**Workaround:**
`(<any>this.freeHandControl).width = 100;
 (<any>this.freeHandControl).height = 100;`

**2.** Property freeDrawingColor doesn't work, because is not part of the fabric.js, instead should be freeDrawingBrush.color.

**In TS:**
`this.freeHandControl.freeDrawingColor = "#FF0000"`

**In JS:**
`canvas..freeDrawingBrush.color = "#000000";`

Workaround:
`(<any>this.freeHandControl).freeDrawingBrush.color = "#000000";`

**3.** Property freeDrawingLineWidth doesn't work, it's no part of the fabric as well. instead should be freeDrawingBrush.width

**In TS:**
`this.freeHandControl.freeDrawingLineWidth = 3;`

**In JS:**
`canvas.freeDrawingBrush.width = 3`

Workaround:
`(<any>this.freeHandControl).freeDrawingBrush.width = 3;`

**4.** String type missing for ICanvasDimensions
According to the fabric.js docs once the property cssOnly is set to true, you could should specify %/em/px to the width and height

**In JS:**
`canvas.setDimensions({ width: '100%', height: '100%' }, { cssOnly: true });`

**In TS:**
`canvas.setDimensions({ width: 100, height: 100 }, { cssOnly: true })`

**Workaround:**
Change teh d.ts from:
`interface ICanvasDimensions { width: number; height: number; }`

**To:**
`interface ICanvasDimensions { width: number | string; height: number | string; }`

Thanks,
Abner

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
