### ISSUE TITLE
redux-ui decorator is not compatible with react-redux connect decorator

### ISSUE THREAD

**Issue by Guria** [DefinitelyTyped/DefinitelyTyped#11954]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `redux-ui/redux-ui.d.ts`.
  - The authors of that type definition are cc/ @andyshuxin

It is not possible to combine react-redux connect with redux-ui in such way:

``` js
@connect(/* anything acceptable by connect*/)
@ui(/* any acceptable by ui */)
class Some extends React.Component<any, any> {}
```

It is because of wrong retutn type declaration. You must describe WrappedComponent correctly.
Might be react-redux typings could be helpful to look.

**Comment by Guria** [comment]
seems there is a typo in github username stored in redux-ui.d.ts
I am not sure but maybe @andyshuhsin is a right person

**Comment by andyshuhsin** [comment]
@Guria 
Yeah it's me.
I wasn't aware the `@connect` style and it doesn't seem to be documented in the official API https://github.com/reactjs/react-redux/blob/master/docs/api.md#api

We used something like this

```
@ui({
  state: {
    something: 0,
  }
})
class View extends React.Component<> {}

export default connect(mapStateToProps, mapDispatchToProps)(DiscoverPageIndex)
```

I haven't dug into the decorator syntax – is it supposed to work without explicitly configured?

**Comment by Guria** [comment]
@andyshuhsin They are not documented decorator syntax because it haven't landed as some stable proposal. But we can say that
```js
@decorator()
class SomeClass {}
```

are equivalent to 
```js
decorator()(class SomeClass {})
```

So the issue here in fact not in decorator syntax, but in the order we consume connect and redux-ui.
It seems that ui wrapping connect is supported by your typings, but not vice versa:
```js
ui()(connect()(Component))  // Ok
connect()(ui()(Component)) // Failed

**Comment by andyshuhsin** [comment]
@Guria I see. Do you have a PR in mind? I'm currently out of town and it might be a while before I can handle this properly.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
