### ISSUE TITLE
@types/moment-timezone producing `unresolved variable tz`

### ISSUE THREAD

**Issue by doapp-ryanp** [DefinitelyTyped/DefinitelyTyped#11977]
I'm using `@types/moment-timezone@0.2.32` and having a heck of a time figuring out why the static `tz` is giving me a `unresolved variable tz` error.

Here is what I'm doing:

```
import * as moment from 'moment';
import 'moment-timezone';

export class MyClass {
    timezomeGuess: string = moment.tz.guess();
}
```

@seansfkelley @michelsalib any idea what I'm doing wrong here?

Seems like [quite a few people](http://stackoverflow.com/questions/38674835/how-to-include-moment-timezone-in-angular-2-app) are having same issue 

thanks in advance for your time

**Comment by seansfkelley** [comment]
With this `package.json`:

```json
{
  "name": "test",
  "version": "0.0.0",
  "scripts": {
    "start": "tsc"
  },
  "dependencies": {
    "@types/moment": "^2.13.0",
    "@types/moment-timezone": "^0.2.32",
    "moment": "^2.15.1",
    "moment-timezone": "^0.5.6",
    "typescript": "^2.0.3"
  }
}
```

and this `tsconfig.json`:

```json
{}
```

and your snippet as `index.ts`:

```ts
import * as moment from 'moment';
import 'moment-timezone';

export class MyClass {
    timezomeGuess: string = moment.tz.guess();
}
```

`npm start` works as expected. (Indeed, `@types/moment` is actually redundant here.) Perhaps you have outdated versions, or your example is oversimplified from the original problematic source?

**Comment by doapp-ryanp** [comment]
Thanks for the reply.  I am only getting this error in my IDE (Webstorm).  `npm start` works for me as well.  Was hoping that I was just doing something wrong, but since you don't see anything it must just be my IDE is not finding the `ts` correctly.

I will keep this issue open for a week or so in the case I find out how to fix the error in my IDE.

thanks again
