### ISSUE TITLE
react-router without dependencies

### ISSUE THREAD

**Issue by donaldpipowitch** [DefinitelyTyped/DefinitelyTyped#11985]
`react-router@2.0.37`:

```
  "dependencies": {
    "@types/history": "*",
    "@types/react": "*"
  },
```

`react-router@2.0.38`:

```
"dependencies": {},
```

I don't know if this a bug or works as expected. I'd say it is a bug. I don't know where the deps are added in the repo, so I can't make a PR.

**Comment by andy-ms** [comment]
Looks fixed now.
