### ISSUE TITLE
Tinycolor doesn't get installed properly with npm install @types/tinycolor

### ISSUE THREAD

**Issue by harangue** [DefinitelyTyped/DefinitelyTyped#12026]
- [ ] I tried using the latest `tinycolor/index.d.ts` file in this repo and had problems.

The official npm module for tinycolor can be obtained via `npm install tinycolor2`. The type definition for it, however, is listed under `tinycolor`. When I attempted to `npm install @types/tinycolor`, I was unable to use the module until I _also_ installed `npm install tinycolor2`. This name mismatch is very confusing and lost me a lot of time, so I figured I'd report it here.

**Comment by andy-ms** [comment]
Fixed by #12769
