### ISSUE TITLE
@types/react-css-modules: Property 'styleName' does not exist in type 'HTMLProps<HTMLElement>'

### ISSUE THREAD

**Issue by emzero** [DefinitelyTyped/DefinitelyTyped#12040]
Using the latest `@types/react-css-modules: 3.7.4` with TypeScript 2.0.3 and React 15.3.2 results in unrecognized `styleName` property.

`error TS2339: Property 'styleName' does not exist on type 'HTMLProps<HTMLElement>'.`

I was using this custom definition and it worked fine before @types 2.0.

``` typescript
declare module 'react-css-modules' {
    interface Options {
        allowMultiple?: boolean;
        errorWhenNotFound?: boolean;
    }

    module Decorator {
        interface Props {
            styles?: any;
            styleName?: string;
        }
    }

    interface Decorator {
        (defaultStyles: any, options?: Options): any;
    }

    const Decorator: Decorator;

    export default Decorator;
}
```

**Comment by skirsdeda** [comment]
@emzero being solved in #12184.

**Comment by mcrawshaw** [comment]
@skirsdeda merged, please close.

**Comment by mcrawshaw** [comment]
@emzero, please close.

**Comment by AlvinYuXT** [comment]
I have the same problem with `@types/react-css-modules` version 4.6.2

**Comment by evenfrost** [comment]
If anyone stumbles upon same error when using `preact`, add `preact.d.ts` file in your /types directory with following content:

```typescript
import preact from 'preact';

declare global {
  namespace JSX {
    interface HTMLAttributes {
      styleName?: string;
    }

    interface SVGAttributes {
      styleName?: string;
    }
  }
}
```

**Comment by JohnForster** [comment]
@evenfrost 
When I create a types/preact.d.ts file with that content I'm now getting the error

> JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

Any ideas? Is this overwriting an existing preact.d.ts file perhaps?

**Comment by evenfrost** [comment]
@JohnForster works good for me. Maybe some missing/misconfigured Preact-related typings?

**Comment by evenfrost** [comment]
An update for TypeScript 3.7:

```ts
// {project_root}/types/preact.d.ts
declare namespace preact {
  namespace JSX {
    interface HTMLAttributes {
      styleName?: string;
    }

    interface SVGAttributes {
      styleName?: string;
    }
  }
}
```

And in your `tsconfig` there should be proper `compilerOptions.typeRoots` property to catch up your declarations folder:

```json
{
  "compilerOptions": {
    "typeRoots": [
      "./node_modules/@types",
      "./types"
    ]
  }
}

```

**Comment by MrYou0** [comment]
https://stackoverflow.com/questions/43017033/property-stylename-does-not-exist-on-type-htmlpropshtmldivelement

**Comment by EmiyaYang** [comment]
This works for me.

```ts
// global.d.ts
import 'react';

declare module 'react' {
  interface Attributes {
    styleName?: string;
  }
}

```

**Comment by 55utah** [comment]
I fixed this by adding file to my project, named `react-css-module.d.ts`.

```
declare namespace React {
  interface Attributes {
    styleName?: string | undefined;
  }
  interface HTMLAttributes<T> {
    styleName?: string | undefined;
  }
  interface SVGAttributes<T> {
    styleName?: string | undefined;
  }
}
```
