### ISSUE TITLE
[types-2.0] CI is broken on the types-2.0 branch.

### ISSUE THREAD

**Issue by pe8ter** [DefinitelyTyped/DefinitelyTyped#12051]
There are several PRs waiting to be merged into the types-2.0 branch, but all are failing Travis CI tests with about 100K lines of errors unrelated to the PR. The errors look like this:

```
== Errors when compiling /Users/Shemp/Projects/DefinitelyTyped/3d-bin-packing/tsconfig.json ==
\Users\Shemp\Projects\DefinitelyTyped\3d-bin-packing\3d-bin-packing-tests.ts
	 Line 47: Cannot find name 'console'.
\Users\Shemp\Projects\DefinitelyTyped\3d-bin-packing\3d-bin-packing.d.ts
	 Line 1306: Cannot find name 'HTMLCanvasElement'.
```

I ran `npm run all` on the HEAD revision of the upstream types-2.0 branch and got the same mass of errors.

Looking for some guidance on whether or not this is expected, and if so, how we go about getting our PRs approved despite these errors.

**Comment by pramodsankarl** [comment]
+1

**Comment by pe8ter** [comment]
After merging in the upstream branch _and_ installing the latest version of TypeScript nightlies my tests are passing again. Closing the issue.
