### ISSUE TITLE
Problem with knockout extend()

### ISSUE THREAD

**Issue by andywestrate** [DefinitelyTyped/DefinitelyTyped#1210]
I have typescript/knockout code with many usages such as this:

```
class ViewModel {
    name: KnockoutObservable<string> = ko.observable().extend({ required: true, minLength: 3 });
    ...
}
```

This recently stopped working with a change to the knockout.d.ts file (I'm using NuGet; it worked with 0.3.4 and has issues with 0.3.5).  The error is:

```
Cannot convert 'KnockoutSubscribable<any>' to 'KnockoutObservable<string>':
    Type 'KnockoutSubscribable<any>' is missing property 'peek' from type 'KnockoutObservable<string>'.
```

The definition itself changed from:

```
extend(source);
```

to

```
extend(requestedExtenders: { [key: string]: any; }): KnockoutSubscribable<T>;
```

but this is a problem because calling extend returns the same object, so KnockoutObservable.extend() should return KnockoutObservable.

**Comment by ltlombardi** [comment]
@vvakame This should be closed. Already fixed. :blush:
