### ISSUE TITLE
Add support for redis pubsub command

### ISSUE THREAD

**Issue by balaise** [DefinitelyTyped/DefinitelyTyped#12141]
Please add support for redis pubsub command.
Definition: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/redis

**Comment by Neob91** [comment]
Looks like it's already done. @balaise @vvakame can this be closed?

**Comment by SethDavenport** [comment]
There is a typedef for the PUBSUB command but it appears to be incorrect.

If I'm reading this right, it means that we're assuming that the data retrieved from redis is of type `number`:

![image](https://user-images.githubusercontent.com/4614141/89448533-c52c5480-d725-11ea-903e-2d4936d38a15.png)

![image](https://user-images.githubusercontent.com/4614141/89448594-dd9c6f00-d725-11ea-9e0e-96af27a7aef8.png)

However the actual data type returned by redis depends on the `PUBSUB` subcommand argument. E.g.

`PUBSUB CHANNELS` and `PUBSUB NUMSUB` return arrays of strings. Only `PUBSUB NUMPAT` returns a number.

https://redis.io/commands/pubsub
