### ISSUE TITLE
filesaver type should install in @types/file-saver to match the package installation folder name

### ISSUE THREAD

**Issue by hhubik** [DefinitelyTyped/DefinitelyTyped#12148]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ Cyril Schumacher https://github.com/cyrilschumacher

I ran into a minor problem with the [type definition](https://www.npmjs.com/package/@types/filesaver) for the [file-saver package](https://github.com/eligrey/FileSaver.js/).

`npm i file-saver` saves the package in `node_modules/file-saver`.
`npm i @types/filesaver` saves the type definition in `node_modules/@types/filesaver`.

To make Typescript find the module, I had to re-name `node_modules/@types/filesaver` to `node_modules/@types/file-saver`.

Could this be fixed so that the name of the type folder matches the name of the package folder.

Thanks!

**Comment by ColinFrick** [comment]
This seems to affect only Windows environments. I have two development environments, one Windows 7 and one LinuxMint 17.2:
- Windows 7.0: Error while compilining: Cannot find module 'file-saver'.
- LinuxMint: Compiles without problem

If I rename the folder to file-saver, it works on Windows as well.

**Comment by hhubik** [comment]
@ColinFrick - you are right, I am on Windows 8.1 and I used the re-naming of the folder to `file-saver` as a **workaround** as well.  The issue with re-naming is, I assume, that I can no longer rely on `npm install` and `package.json` to update the package in the future.  The name of the of the type definition folder should match the name of the package just like it does with all other packages with separate type definition.

**Comment by zanza00** [comment]
I can confirm the same issue on MacOs and the same workaround works as well

**Comment by NiklasA** [comment]
+1 Windows 7

**Comment by ColinFrick** [comment]
I recently checked again and `npm i @types/file-saver` works now.
See pull request #12507 and https://www.npmjs.com/package/@types/file-saver
