### ISSUE TITLE
How to get the definitions:  Directly from the GitHub repos

### ISSUE THREAD

**Issue by phreed** [DefinitelyTyped/DefinitelyTyped#12168]
How to get the definitions
- Directly from the GitHub repos
  ...from...
  https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/README.md
  ...does not link to anything.

I suspect that the reason the documentation is missing is due to the lack of a good recommendation.

It that a limitation in `npm` makes it impossible to use packages directly from DT.
Specifically, npm does not seem to be able to call out a specific path in a git repository.
https://docs.npmjs.com/files/package.json#git-urls-as-dependencies
...as is possible with local files...
https://docs.npmjs.com/files/package.json#local-paths

However with some small effort a parallel repository can be created that works fine with `npm`.
[For example this repository can be used](https://github.com/phreed/typescript-typings/tree/n3).
The problem then devolves to merging that project into DT.

**Comment by mhegazy** [comment]
DefinitelyTyped is just a repository for declaration files; it is not responsible for the distribution of these file per se. 

[Types-publisher](https://github.com/Microsoft/types-publisher) is the tool that publishes the definitions on DT to npm [@types](https://www.npmjs.com/~types) organization. Types-publisher does not support using other repos as sources for declarations; adding support for this is covered by https://github.com/Microsoft/types-publisher/issues/4

> However with some small effort a parallel repository can be created that works fine with npm.

the main issue is really consistency between packages and their dependencies. in DT there is a test system that ensures a change to one package does not break others. this will need to be replicated for other repos as well.

**Comment by phreed** [comment]
Right.
Given a person who needs to consume a javascript library for which there is no extant typescript defintion file in @types, like me.
I would use `npm install @types/thing` if it existed and am willing to create one if it does not.
The current approach is to cobble something together in my working project and then inject it into a fork of DefinitelyTyped along with some tests.
Then comes the long wait for it to be merged into DefinitelyType and propagated to `@types` to see if I did it correctly.
What would be nice is if there were something like `types-publisher` that would extract a directory and create/update an github project suitable for install by npm.
This is what I am doing manually.

**Comment by mhegazy** [comment]
there is nothing special about the folder. it looks like a normal npm package. so for a package "foo", create `additonalTypes\foo\index.d.ts`. in your `tsconfig.json` set `"typeRoots": [".\additonalTypes", ".\node_modules\@types"]`; with this an import to `import d from "foo"` would first look into `additonalTypes\foo\index.d.ts`. hope that helps.

see http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types for more information

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
