### ISSUE TITLE
react.d.ts missing on*Capture attributes in DomAttributes interface

### ISSUE THREAD

**Issue by dzearing** [DefinitelyTyped/DefinitelyTyped#12193]
- [X] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Referring to this d.ts file:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts

Capturing click events in the capture phase would require `onClickCapture`. The current typings do not have any on*Capture attributes listed in DomAttributes, which forces typings workarounds, or perhaps just a correction to the interface.

See docs here:

https://facebook.github.io/react/docs/events.html#supported-events

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by dzearing** [comment]
@vvakame Adding a PR to master here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12258

Let me know if i need to push this to a different branch.

**Comment by dzearing** [comment]
@vvakame Hey there, friendly ping. It would be awesome to get these fixed. If anyone hits this issue, until this is resolved in the typings, the workaround would be to do something like:

```jsx
<div { ...{ onFocusCapture: this._onFocusCapture } } />
```

**Comment by dzearing** [comment]
Reopened for the correct branch.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12327

**Comment by ericanderson** [comment]
This merged. Please close this issue.
