### ISSUE TITLE
[react-native]  add fetch function in react-native typing

### ISSUE THREAD

**Issue by hktonylee** [DefinitelyTyped/DefinitelyTyped#12198]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I want to talk about `react-native/react-native.d.ts`.

In the `index.d.ts` of `react-native`, `fetch` is defined as type rather than function. The `tsc` will complain `error TS2304: Cannot find name 'fetch'`, but this function works in the app.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by hktonylee** [comment]
I sent one before but failed to compile. Let me send another one.

**Comment by alloy** [comment]
This has been fixed in #15105

**Comment by alloy** [comment]
@DanielRosenwasser This can be closed.
