### ISSUE TITLE
@types/marked missing namespace

### ISSUE THREAD

**Issue by MehulATL** [DefinitelyTyped/DefinitelyTyped#12190]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

<img width="1091" alt="screen shot 2016-10-23 at 11 55 32 am" src="https://cloud.githubusercontent.com/assets/3915230/19628669/113d0fd6-9918-11e6-8cb1-9df6e24c72de.png">

I believe the type definitions is missing a namespace so I can import it

**Comment by UziTech** [comment]
This can be closed
