### ISSUE TITLE
refactor aws-sdk for promise support and with overloading 

### ISSUE THREAD

**Issue by tomdavidson** [DefinitelyTyped/DefinitelyTyped#12205]
- [x] I want to talk about `aws-sdk/aws-sdk.d.ts`.
- Interested persons of that type definition include cc/  @vvakame @midknight41

AWS SDK has supported promises [since March](https://blogs.aws.amazon.com/javascript/post/Tx3BZ2DC4XARUGG/Support-for-Promises-in-the-SDK).  

### Problem
Only some of the definitions allow promises and of those, return types of 'any' are used rather than overloading, such as #11923:

```js
putObject(params: s3.PutObjectRequest, callback?: (err: Error, data: any) => void): any;

// vs overload
putObject(params: s3.PutObjectRequest, callback: (err: Error, data: any) => void): void;
putObject(params: s3.PutObjectRequest): {promise:Promise<any>;};
```

### Proposed
Refactoring the entire file to allow promises and with overloading rather than any.

I'm willing to put in some time, but am a bit green and would like direction for contributors that have more experience with this or even another contrib that provides the needed spec/test.

**Comment by midknight41** [comment]
The overload approach looks sound. Perhaps pick one service (S3 for example) and convert that? 

This definition is huge and some smaller PRs would be easier to review.

This definition lacks a lot of tests and, if you were up for it, adding some would be good.

**Comment by tomdavidson** [comment]
AWS will be shipping official typings relatively soon https://github.com/aws/aws-sdk-js/pull/1189 so I am going to close this issue.

**Comment by midknight41** [comment]
@tomdavidson that's probably the best news I've ever heard!
