### ISSUE TITLE
@types/protractor missing Config

### ISSUE THREAD

**Issue by philjones88** [DefinitelyTyped/DefinitelyTyped#12225]
- [x] I tried using the latest `protractor/index.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

Using version 1.5.20 (latest as of now) I cannot import Config, it is missing. Trying to follow the official typescript protractor example at https://github.com/angular/protractor/blob/master/exampleTypescript/conf.ts

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by thorn0** [comment]
I think `@types/protractor` is deprecated. Protractor is developed in TS now, and the types are bundled with it. If you're following the official typescript example, @philjones88, why did you install `@types/protractor`? That example says nothing about it. It should be enough to install Protractor itself and to use `"moduleResolution": "node"` in [tsconfig](https://github.com/angular/protractor/blob/master/exampleTypescript/tsconfig.json).

**Comment by philjones88** [comment]
I was following
https://github.com/AngularClass/angular2-webpack-starter/blob/master/tsconfig.json

Which strangely includes it.

Sent from my iPhone

On 30 Oct 2016, at 16:30, Georgii Dolzhykov <notifications@github.com<mailto:notifications@github.com>> wrote:


I think @types/protractor is deprecated. Protractor is developed in TS now, and the types are bundled with it. If you're following the official typescript example, @philjones88<https://github.com/philjones88>, why did you install @types/protractor? That example says nothing about it. It should be enough to install Protractor itself and to use "moduleResolution": "node" in tsconfig<https://github.com/angular/protractor/blob/master/exampleTypescript/tsconfig.json>.

**Comment by thorn0** [comment]
That's not an official example. But still it seems like it needs to be updated.

**Comment by cnishina** [comment]
The file you are referring to [https://github.com/angular/protractor/blob/master/exampleTypescript/conf.ts](https://github.com/angular/protractor/blob/master/exampleTypescript/conf.ts) is using Protractor's built in support for types. I agree with @thorn0 that `@types/protractor` is deprecated.

@vvakame this does not appear to be an issue and should be closed.

**Comment by vvakame** [comment]
Now, protractor bundled own typings. https://github.com/angular/protractor/blob/39f0615dfc36c087a2f076d544bb337b16e9bbc3/package.json#L63
We should stop using `@types/protractor`.
