### ISSUE TITLE
@types/router5 seems outdated

### ISSUE THREAD

**Issue by iotch** [DefinitelyTyped/DefinitelyTyped#12221]
- [x] I tried using the latest `router5/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `router5/index.d.ts`.
  - The authors of that type definition are cc/ @sandersky

Hello. Current router5 definitions seems outdated since router5 has been updated to v4. Thanks!

**Comment by vvakame** [comment]
please send a pull request. I'll review it.
