### ISSUE TITLE
express-serve-static-core RequestHandler and ErrorRequestHandler Implementation

### ISSUE THREAD

**Issue by karthikax** [DefinitelyTyped/DefinitelyTyped#12274]
- [x] I tried using the latest `express-serve-static-core/index.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `express-serve-static-core/index.d.ts`.
  - The authors of that type definition are @frogcjn @Strate and others

I am using typescript 2.0.0
I am trying to use [Error handling](https://expressjs.com/en/guide/error-handling.html) middleware for body-parser like this:

```
app.use(bodyParser.json());
app.use((err, req, res, next) => {
    if (err instanceof SyntaxError) {
        res.status(400).json({ status: 400, message: 'Invalid Request' });
        res.end();
    }
});
```

Which gives error like this:

```
ERROR in [default] C:\projects\ems-universal\src\server.ts:47:8 
    Argument of type '(err: Request, req: Response, res: NextFunction, next: any) => void' is not assignable to parameter of type 'PathParams'.
      Type '(err: Request, req: Response, res: NextFunction, next: any) => void' is not assignable to type '(string | RegExp)[]'.
        Property 'find' is missing in type '(err: Request, req: Response, res: NextFunction, next: any) => void'.

    ERROR in [default] C:\projects\ems-universal\src\server.ts:49:12 
    Property 'status' does not exist on type 'NextFunction'.

    ERROR in [default] C:\projects\ems-universal\src\server.ts:50:12 
    Property 'end' does not exist on type 'NextFunction'.
```

When I add extra parameter of type `any` to `RequestHandler` and two more parameter `status` and `end` to `NextFunction` Error disappears. Can anyone fix this? Or any alternative method for error handling?

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by karthikax** [comment]
Thanks @vvakame Thanks for the response.
What i am doing is just hack. It is not correct method. Author or Express users with typescript knowledge can understand the implementation and solve this. If you could fix this it would be great.

Thanks

**Comment by Strate** [comment]
@karthikax could please send PR with added failing test for your case?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
