### ISSUE TITLE
[lodash] Questionable update: Add undefined return to `find`

### ISSUE THREAD

**Issue by LOZORD** [DefinitelyTyped/DefinitelyTyped#12284]
- [x] I want to talk about `lodash/lodash.d.ts`.
  - The authors of that type definition are @vvakame 

Hello again 😀 
I don't know if this will cause a lot of problems down the line, but `find` (and similar functions) should have the return type `T | undefined` instead of just `T`. See the return type documentation [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/lodash/lodash.d.ts#L6802). I could see this being annoying for many as it will throw errors for those using `strictNullChecks` and not checking the return, but it will probably help with the epic goal of safety in the long run.
Up to you... I can handle the PR if you want to move forward.

**Comment by TonyPythoneer** [comment]
@LOZORD The lodash authors are @bczengel, @chrootsu, @stepancar.
If you find any question, you can send PR, @vvakame will review.

**Comment by stepancar** [comment]
@LOZORD  free to PR)

**Comment by LOZORD** [comment]
See #13085
