### ISSUE TITLE
[types-2.0] d3-geo : Update Definitions to correspond to v1.3.1

### ISSUE THREAD

**Issue by tomwanzek** [DefinitelyTyped/DefinitelyTyped#12296]
A new minor version of the d3-geo has been released and there a minor updates required to bring the definitions up to current.

At the time of opening this issue the latest release of the underlying library is 1.3.1.

@Ledragon do you want to take the lead? I think this update should be a quicker PR than preparing the original Definitions 😄

cc @gustavderdrache

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by Ledragon** [comment]
I might, but unsure when I will have time. I will keep posted if and when I get started

**Comment by tomwanzek** [comment]
Getting started on it for this time, will alert you to the PR.

**Comment by tomwanzek** [comment]
Closed with #12492

**Comment by Ledragon** [comment]
Thanks for taking it on, sorry for my lack of availability...

**Comment by tomwanzek** [comment]
Next one's on you :wink: Cheers, T
