### ISSUE TITLE
Minimist and ES6 `import`

### ISSUE THREAD

**Issue by erykpiast** [DefinitelyTyped/DefinitelyTyped#12293]
- [x] I tried using the latest `minimist/index.d.ts` file in this repo and had problems.

I use `minimist` (the latest `1.2.0` version) with TypeScript `2.0.6` and the latest typings. It works perfectly when I use syntax `import minimist = require('minimist')`. Although when I try to import the package with `import minimist from 'minimist'` it says `Module '"./node_modules/@types/minimist/index"' has no default export.`. JS module exports a function by default (and that's what I get when using `import ... = require` syntax).

I'm not familiar with typings syntax, but I see there is function declaration exported as default ([here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/minimist/index.d.ts)) and it looks like overridden by namespace declaration.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by erykpiast** [comment]
Here you are. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12372

**Comment by SeekingMonkey** [comment]
I'm having trouble importing braintree-web in my app.  I'm using Angular2 with TS and having a hard time.

**Comment by andy-ms** [comment]
@SeekingMonkey `braintree-web` isn't declared as an importable module. If you think this is wrong, please make a PR updating the definitions file (but test it in your own code first).
