### ISSUE TITLE
[types-2.0] d3-voronoi : Update Definitions to correspond to v1.1.0

### ISSUE THREAD

**Issue by tomwanzek** [DefinitelyTyped/DefinitelyTyped#12297]
The definitions need to be updated to add the method added in the latest minor version release of the underlying library v1.1.0.

**Comment by tomwanzek** [comment]
FYI cc @gustavderdrache

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by tomwanzek** [comment]
Thx @vvakame . I am in the process of preparing one. It's all for the `types-2.0` branch. I just pushed a PR which is slightly preparatory, i.e. it pins down dependencies of the `d3` standard bundle definitions (see #12325 )

**Comment by tomwanzek** [comment]
Closed with #12331.
