### ISSUE TITLE
Problems with react-select definitions

### ISSUE THREAD

**Issue by marisbest2** [DefinitelyTyped/DefinitelyTyped#12302]
- [x] I tried using the latest `react-select/react-select.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

I'm trying to use the react-select Async component. I tried doing something like

``` typescript
import Select = require("react-select");
                <Select.Async
                    className="my-select"
                    ref={(ref: any) => this.selectNode = ref}
                    onChange={myOnChange}
                    loadOptions={myfunc}
                />
```

and also tried

``` typescript
import Select from "react-select";
                <Select.Async
                    className="my-select"
                    ref={(ref: any) => this.selectNode = ref}
                    onChange={myOnChange}
                    loadOptions={myfunc}
                />
```

Both of them fail to properly load the components. I get console errors about failed invariants with the first way, and on the second way I get messages that "react-select" doesnt resolve to a module. 

Ideas?

**Comment by mayerwin** [comment]
I am also having problems with this package definition, using TypeScript 1.8. The code will compile with the following imports:

```
import Select = require("react-select");
import { Option, ReactSelectProps, ReactAsyncSelectProps, ReactCreatableSelectProps, MenuRendererProps } from "react-select-props";
```
 but Visual Studio reports the following error when trying to use for example `<Select.Creatable options={this.props.options} {...rest} />`: `JSX element type 'Select.Creatable' does not have any construct or call signatures.` Resharper on its end is reporting that it doesn't find the module (which is wrong since it compiles).

**Comment by Sankozi** [comment]
Workaround for people having same problem: 
`        const element = (ReactSelect as any).Creatable;
        const props: ReactCreatableSelectProps = {};
        return React.createElement(element, props); //returns <ReactSelect.Creatable /> with props`

**Comment by mayerwin** [comment]
Just submitted a PR to fix this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12816
Nested class support in TS is not terrible, `react-select` should probably move Creatable so that it is not a nested class.
