### ISSUE TITLE
d3.selection attr value parameter too strict

### ISSUE THREAD

**Issue by laureysruben** [DefinitelyTyped/DefinitelyTyped#12310]
I'm trying to use the d3js v4 typings, but I run into a problem with the attr function in d3.selection. (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/d3-selection/index.d.ts)

It seems to me the value parameter typing is too strict.

`/**
     * Sets the value of the attribute with the specified name for the selected elements and returns this selection.
     * All elements are given the same attribute value.
     *
     * @param name Name of the attribute
     * @param value Constant value for the attribute
     */
    attr(name: string, value: string | number | boolean): this;`

Consider following code to make a donut chart:

`        pieChart = donut(this._data);

```
    var arc = d3.arc()
        .outerRadius(radius - 10)
        .innerRadius(radius - 60);

    var g = svg.selectAll('.arc')
        .data(pieChart)
        .enter()
        .append('path')
        .attr('d', arc)
        .attr('class', 'arc')
        .style("fill", function (d, i) { return color[i]; });`
```

Passing the arc through the attr function is not possible with current typings, but I think it should be.
Am I approaching this the wrong way?

cc @tomwanzek

**Comment by tomwanzek** [comment]
As it currently stands, the `attr(...)` method of a selection, does accept an arc-generator as input. There is a test for it in the [d3-shape test file on line 147](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/d3-shape/d3-shape-tests.ts#L147).

So likely it is a type mismatch between the either the data provided to/expected by the arc generator, or the element `this` context. Can you kindly provide the following additional info:

What is the specific TS error message you see?
What is the exact data structure of `pieChart`?

Thanks

**Comment by tomwanzek** [comment]
@laureysruben Should you still experience an issue, could you kindly provide the additional information requested above?

If your question has been addressed by reviewing the quasi-examples in the referenced test file, please close the issue. Should you require an additional explanation, please do not hesitate. Thanks in advance.

**Comment by laureysruben** [comment]
@tomwanzek Sorry for the late reply, I've been out for a few days. Weird thing is, today I open the exact same code and it just compiles. Seems the typescript compiler got messed up somewhere along the way.

Anyway, thanks for your amazing work on these typings!
