### ISSUE TITLE
[winston] Add "BaseLogLevel" string enum to Winston?

### ISSUE THREAD

**Issue by LOZORD** [DefinitelyTyped/DefinitelyTyped#12366]
- [x] I want to talk about `winston/winston.d.ts`.
  - The authors of that type definition are @bonnici @codeanimal

Do you think it would be useful to add a string enum to the Winston definition that represents the inherent/base log levels? It would look something like this:

``` ts
type BaseLogLevel = 'error' | 'warn' | 'info' | 'debug'
```

The upside is that this is a lot "safer" than the current definition of just `string`, but the downside might be a lot of breaking changes, especially with respect to user-defined log levels. Up to you for how you want to proceed.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by LOZORD** [comment]
See #12520
