### ISSUE TITLE
Mapbox Typings are out of date in npm

### ISSUE THREAD

**Issue by vjm** [DefinitelyTyped/DefinitelyTyped#12383]
- [x ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

https://www.npmjs.com/package/@types/mapbox-gl

**Comment by vvakame** [comment]
please send a pull request to types-2.0 branch. I'll review it.

**Comment by andy-ms** [comment]
`@types/mapbox` comes from the `types-2.0` branch, not from `master`. It should be up-to-date with that.
