### ISSUE TITLE
echart  can't set x : 'center' in title

### ISSUE THREAD

**Issue by lzm420241** [DefinitelyTyped/DefinitelyTyped#12404]
chart.setOption({
                  title: {
                      text: '每日订单数统计',
                      x:    'center',
                      top: '3%'
                  },
{})
error: type is not assignable to parameter of type 'EchartOption'

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by lzm420241** [comment]
x replace by 'left', It's ok!
