### ISSUE TITLE
service_worker_api pushManager.subscribe function signature needs support for options object.

### ISSUE THREAD

**Issue by michahell** [DefinitelyTyped/DefinitelyTyped#12414]
- [x] I tried using the latest `service_worker_api/service_worker_api.d.ts` file in this repo and had problems.

It seems the options object that can be passed to the subscribe function is not accounted for in the type definition:

https://developer.mozilla.org/en-US/docs/Web/API/PushManager/subscribe

The options object should allow the following properties:
`userVisibleOnly` and `applicationServerKey`

Something like this?

```Typescript
interface PushSubscriptionOptions {
	userVisibleOnly: boolean;
	applicationServerKey: Uint8Array;
}
interface PushManager {
	/**
	 * Returns a promise that resolves to a PushSubscription with details of a
	 * new push subscription.
	 */
	subscribe(options: PushSubscriptionOptions) : Promise<PushSubscription>;
}
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by samuelcampos** [comment]
I've created a Pull Request based on @michahell suggestions

**Comment by michahell** [comment]
Sorry guys, I was a bit busy with a lot of stuff, and needed to pick up other things unrelated to Web Push (Notifications). Great @samuelcampos !
