### ISSUE TITLE
Deprecate `*-case` typings

### ISSUE THREAD

**Issue by blakeembrey** [DefinitelyTyped/DefinitelyTyped#12423]
I would like all the `change-case` and dependency modules to be deprecated from DefinitelyTyped. I provide all the definitions inline. How do I do that?

E.g. https://www.npmjs.com/package/@types/title-case, https://www.npmjs.com/package/@types/change-case, https://www.npmjs.com/package/@types/lower-case, etc.

**Comment by vvakame** [comment]
FYI https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

**Comment by blakeembrey** [comment]
Thanks! I'm not sure I'll get around to doing that for all those definitions, I guess the issue can remain open until it's resolved.

**Comment by andy-ms** [comment]
Fixed by #13323
