### ISSUE TITLE
All declarations of 'responseURL' must have identical modifiers.

### ISSUE THREAD

**Issue by mgroenhoff** [DefinitelyTyped/DefinitelyTyped#12434]
Recent Travic CI builds fail with the above error (https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/172278084).

**Comment by cyrilgandon** [comment]
@mgroenhoff : do you know what happens exactly? I don't see which commit broke all the builds

**Comment by mgroenhoff** [comment]
No i don't what went wrong and where. I tried looking at the last types-2.0 Travis build that passed but that seemed totally unrelated. I tried to find it but i gave up due to having to do more important things and this seemed like the most obvious fix.

**Comment by cyrilgandon** [comment]
The last build that pass was this one https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/172170037

`Typescript version: 2.1.0-dev.20161031`

The first build that failed was https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/172213768

`Typescript version: 2.1.0-dev.20161101`

My bet is that the compiler doesn't allow anymore something that it used to.

**Comment by mgroenhoff** [comment]
I also already sent out a PR with this issue but i guessed it was missed https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12435

**Comment by cyrilgandon** [comment]
@mgroenhoff for what it's worth, I have found the culprit: https://github.com/Microsoft/TypeScript/commit/8984e43b205bfb61335902522b5292f6dcbac093

The property `responseURL` becames readonly, while in the chocolatechips lib, the property stay mutable. For the compiler, you can define 2 time the same property in two different definition files, but they have to have the same declaration flags, which is no more the case with this commit.

**Comment by mgroenhoff** [comment]
Yes that was indeed what i expected what was going on but i didn't bother to search through the typescript commits. Thats what you get for having typescript@next in your package.json ;)
