### ISSUE TITLE
TypeScript's JSDom = 2.0.0, official JSDom = 7.0.0

### ISSUE THREAD

**Issue by tsirolnik** [DefinitelyTyped/DefinitelyTyped#12491]
As the title says.

How can I help in order to upgrade the current version available?

**Comment by andy-ms** [comment]
If there are not breaking changes, just change the typings in place and update the version number in the header.
If there are breaking changes, move the current `jsdom/index.d.ts` to `jsdom/jsdom-2.0.d.ts`, and same for tests; then write new definitions in their place.
See the [README](https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute) for more information.
Also, please set `strictNullChecks` to `true` in the tsconfig and keep null/undefined in mind when updating the types.

**Comment by tsirolnik** [comment]
Thanks, I'll look into it. 👍

**Comment by chiptus** [comment]
I think this should be reopened - jsdom is now version 10, and works completely different - using constructor instead of jsdom.env

**Comment by leonard-thieu** [comment]
This was fixed by #16819.
