### ISSUE TITLE
[Request] Type definitions for botkit

### ISSUE THREAD

**Issue by aaronsky** [DefinitelyTyped/DefinitelyTyped#12498]
I recently moved my codebase over from a Coffeescript-based Hubot to TypeScript and Botkit. It's really nice but I would like to see definitions for this library in accordance with an issue raised on their repo several months ago (https://github.com/howdyai/botkit/issues/192).

Here's the repo: https://github.com/howdyai/botkit

**Comment by ypresto** [comment]
howdyai/botkit#192 is already fixed (botkit has its own type def).
