### ISSUE TITLE
Lack of information for using .d.ts files without modules in the browser

### ISSUE THREAD

**Issue by web3d0** [DefinitelyTyped/DefinitelyTyped#12516]
- [ ] I want to talk about `xxxx/xxxx.d.ts`.

With the legacy.d.ts files, the browser was able to use <script src="gl-matrix.js"> and then the IDE would pick up hinting with a ///reference to the gl-matrix.d.ts definitions file in .ts files that were using the gl-matrix functions.

The updated definitions file from 3 months ago has broken this workflow, as export requires modules to be used despite the fact that the functions are available due to having being loaded with <script>. The IDE is looking for a corresponding import and flags an error.

There needs to be documentation explaining how to retain the earlier workflow of being able to load in Javascript files and augmenting the type information in the case where modules are not being used.

**Comment by andy-ms** [comment]
If you think some components of `gl-matrix` should be available as global variables, submit a pull request that adds them. This could mean adding e.g. `export as namespace vec2;` inside of `declare module 'gl-matrix/src/gl-matrix/vec2'`.

**Comment by web3d0** [comment]
I don't want to use modules, and only want the .d.ts files for IDE hinting, as the legacy.d.ts files provide. I'm able to get the behaviour I want by using the legacy files, but I'm forced to use modules if I use the newer files. So there needs to be information on how to revert to the legacy behaviour so that I can load in JS libraries using <script> in the browser and add on typing information without then having to use import.

**Comment by andy-ms** [comment]
Have you tried adding `export as namespace vec2;`? That should declare a global variable.

**Comment by web3d0** [comment]
After looking through the other .d.ts files, it looks like gl-matrix is a bad example and I had mistaken the change to gl-matrix's definitions as the change for node's new format. The new format for node doesn't prevent global definitions from being made when a script tag creates those globals. Thanks for the help, and this issue can be closed.
