### ISSUE TITLE
lib.es6.d.ts for file reader event is inaccurate

### ISSUE THREAD

**Issue by AmitMY** [DefinitelyTyped/DefinitelyTyped#12510]
I want to talk about `lib.es6.d.ts`.

`interface Event` has `target: EventTarget;`
And
`interface EventTarget` does not have `result`

Meaning that this code shows an error:
```
let reader = new FileReader();
reader.onload = e => fileObj.src = e.target.result;
```

> Unresolved variable 'result'

I do not know if to fix this you need to add the 'result' to `EventTarget` or extend it, or any other solution.

**Comment by vvakame** [comment]
it is not included in our repository.
Please talking about it in https://github.com/Microsoft/TypeScript
