### ISSUE TITLE
material-ui: TextField onChange has wrong type

### ISSUE THREAD

**Issue by tomfun** [DefinitelyTyped/DefinitelyTyped#12523]
- [x] I tried using the latest `https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/material-ui/material-ui.d.ts#L1664` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - The authors of that type definition are: // Definitions by: Nathan Brown <https://github.com/ngbrown>, Oliver Herrmann <https://github.com/herrmanno>

There is no any type explanation [at official documentation](http://www.material-ui.com/#/components/text-field), but in **fact**, *onChange* callback signature must be changed from:

```
    interface TextFieldProps {
        onChange?: React.FormEventHandler;
// ....
    }
```
to:
```
        onChange?: (e: FormEvent, value: string) => void;
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by tomfun** [comment]
fixed
