### ISSUE TITLE
[chart.js] not working using types-2.0 and webpack

### ISSUE THREAD

**Issue by stephtr** [DefinitelyTyped/DefinitelyTyped#12525]
- [x] I want to talk about `chart.js/index.d.ts`.
  - The authors of that type definition are cc/ @anuti 

Using chart.js definition from types-2.0 in webpack results in `File '.../node_modules/@types/chart.js/index.d.ts' is not a module.`

Shouldn't there be a `export { Chart };`, `export class Chart {...}` or at least `export = Chart;` within that file?

**Comment by vvakame** [comment]
try with `import chartjs = require("chartjs");`.

**Comment by stephtr** [comment]
That results in `[ts] File '.../node_modules/@types/chart.js/index.d.ts' is not a module.`.
It only works if I add an `export = Chart;` at the end of the definition file.
Using `export class Chart {...}` would enable the new ES6 syntax (`import { Chart } from 'chart.js';`).

**Comment by vvakame** [comment]
ah you are right. 
please send a pull request. I'll review it.
