### ISSUE TITLE
[react-native] are exported as `react` not `react-native`

### ISSUE THREAD

**Issue by fredrikbonander** [DefinitelyTyped/DefinitelyTyped#12535]
- [x] I tried using the latest `react-native/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `react-native/index.d.ts`.
  - The authors of that type definition are cc/ @bgrieder

Shouldn't the `react-native` defenitions be exported as `declare module "react-native"` ? The current published version on NPM defines the module as `declare module "react"`.

This is causing some odd behaviours/confusions:
-  Both `import {StyleSheet} from 'react-native'` and `import {StyleSheet} from 'react'` compile fine with `tsc`.
- Runtime only `import {StyleSheet} from 'react-native'` works.
- IntelliJ (and I would guess other IDE) can't find any definitions for `react-native`

It seems that there's a inconcistency between the https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/react-native/index.d.ts (currently published to NPM) and https://github.com/bgrieder/react-native-typescript-definitions/blob/master/typings/react-native/react-native.d.ts where the former defines everything under the module `react` and the later `react-native`.

**Comment by DomiR** [comment]
How can I use `@types/react-native` with typescript? Why is it not exported as `react-native`.

Thanks, 
@bgrieder

**Comment by bgrieder** [comment]
@DomiR AFAIK the Types 2 definitions (those imported using @types/xxxx) are "auto-generated" by the DefinitelyTyped team and I have not used them.
Alternatively go for the "old style " import
 - create a directory typings/react-native and put the react-native.d.ts file file there
 - import {Whatever} from 'react-native

Note: I have stopped maintaining those typings and I am expecting Microsoft to take over (they have been a large contributor of recent changes)

**Comment by alloy** [comment]
This has been fixed.

**Comment by alloy** [comment]
@DanielRosenwasser Can you close this?
