### ISSUE TITLE
[chart.js] missing data property on Chart class

### ISSUE THREAD

**Issue by stephtr** [DefinitelyTyped/DefinitelyTyped#12530]
- [x] I tried using the latest `chart.js/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `chart.js/index.d.ts`.
  - The authors of that type definition are cc/ @anuti 

At first sorry for just another issue ;)
According to http://www.chartjs.org/docs/#advanced-usage-prototype-methods the chart data can be updated via `myLineChart.data.datasets[0].data[2] = 50;`.
The current TypeScript definition has no property data.
My first try was to add a property `data: ChartData`, but `ChartData` itself has no properties.
My suggestion would therefore be to model the Chart class as a template:
```
interface ChartConfiguration<ChartDataType extends ChartData> {
    data?: ChartDataType;
    ...
}

class Chart<ChartDataType extends ChartData> {
    constructor(context: CanvasRenderingContext2D | HTMLCanvasElement, options: ChartConfiguration<ChartDataType>);
    config: ChartConfiguration<ChartDataType>;
    data: ChartDataType;
    ....
}
```

**Comment by glen-84** [comment]
Should this be closed? (there is a merged PR)

**Comment by stephtr** [comment]
The issue by itself got solved, even though the solution is not optimal (one still can't access `myLineChart.data.datasets` but has to use for example `(chart.data as LinearChartData).datasets`).
However since I won't try solving that problem in the near future, I'm closing this issue.
