### ISSUE TITLE
Update jquery.dataTables

### ISSUE THREAD

**Issue by sliekens** [DefinitelyTyped/DefinitelyTyped#12552]
The current definitions for jquery.dataTables are compatible with DataTables 1.10.8 but there have been 4 newer releases with API changes since that version.

https://cdn.datatables.net/releases.html

**Comment by CNBoland** [comment]
@StevenLiekens we are working on it. I have submitted a [PR for v1.10.8](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12333), and when accepted, I'll move on to each subsequent version of jquery.dataTables to benefit those who are using an older version and also to provide history. Thank you for submitting.

**Comment by CNBoland** [comment]
@StevenLiekens also note that new work is being done on the _types-2.0_ branch rather than _master_ branch.

**Comment by StevenLiekens** [comment]
I'm glad to hear that it's being worked on. Thanks.

**Comment by CNBoland** [comment]
Updated to 1.10.10 [#21731](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21731)
