### ISSUE TITLE
IResourceArray should contain $cancelResuest

### ISSUE THREAD

**Issue by nhack** [DefinitelyTyped/DefinitelyTyped#12601]
- [x] I tried using the latest `angularjs/angular-resource.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `angularjs/angular-resource.d.ts`.

I want to cancel all the pending request when I'm navigating, and for this I'm having a `RequestService` that has a list of all the pending requests: `private resources: Array<IResourceArray<any>>`.
But `IResourceArray` dosen't contain the `$cancelRequest` in it's type definition, and I had to change the type to `any` to make it work, but I guess it should contain that method.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by nhack** [comment]
I've created the pull request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12664
