### ISSUE TITLE
'@types/synaptic' is not in the npm registry.

### ISSUE THREAD

**Issue by Hongbo-Miao** [DefinitelyTyped/DefinitelyTyped#12612]
I tried using the latest [synaptic/synaptic.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/synaptic/synaptic.d.ts) file in this repo and had problems.

cc/ @ToastHawaii

___
When I tried to run

```bash
npm install --save-dev @types/synaptic
```
I got error:

> '@types/synaptic' is not in the npm registry.

**Comment by vvakame** [comment]
`@types` is shipping from `types-2.0` branch.
please wait for merge master into types-2.0 branch.

**Comment by mhegazy** [comment]
should be working now.
