### ISSUE TITLE
ClearReporters feature from jasmine 2.5.1. is missing

### ISSUE THREAD

**Issue by DanAnton** [DefinitelyTyped/DefinitelyTyped#12622]
-  I tried using the latest `jasmine/jasmine.d.ts` file in this repo and I saw that is missing the clearReporters function

I just modified the jasmine.d.ts file and the function is working now. Could you please add that function?
In `interface Env {
.....
 clearReporters():void;
}`
 and in ` interface Reporter {
        clearReporters():void;
....}`

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by zvirja** [comment]
@DanAnton Could you please check whether it's still relevant? I found that latest 3.x definitions contain the `clearReporters` method.

Thanks!

**Comment by DanAnton** [comment]
@zvirja is not relevant anymore. I will close the issue. Thank you!
