### ISSUE TITLE
graphql-types: error TS2304: Cannot find name 'Location'

### ISSUE THREAD

**Issue by nknapp** [DefinitelyTyped/DefinitelyTyped#12621]
First of all, great job for the graphql-types. They have helped a lot.
However, I get this error when compiling my program that uses graphql, just by importing it.
Steps to reproduce:

```bash
mkdir tmp && cd tmp
npm init -y
npm install typescript @types/graphql graphql
echo "import { graphql } from 'graphql'" >index.ts
./node_modules/.bin/tsc --lib es6 index.ts
```

The output of the `tsc`-command is

```
node_modules/@types/graphql/index.d.ts(2217,43): error TS2304: Cannot find name 'Location'.
node_modules/@types/graphql/index.d.ts(2229,43): error TS2304: Cannot find name 'Location'.
node_modules/@types/graphql/index.d.ts(2282,22): error TS2304: Cannot find name 'Document'.
```

At first I thought I needed some browser typings for the classes, but I saw that there *are* actually classes for Document and Location in the file. I haven't found the reason for the problems though.

- [x] I tried using the latest `graphql/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `graphql/index.d.ts`.
  - The authors of that type definition are cc/ @TonyPythoneer, @calebmer

**Comment by calebmer** [comment]
Yeah, looks like there were some missing imports. Not sure how that happened. Thanks for reporting :+1: (fixed with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12636)

**Comment by nknapp** [comment]
Thanks for fixing. Any idea how long it will take to get into npm?

**Comment by TonyPythoneer** [comment]
@nknapp When the PR fixes it gets merged, I think it will be published by types-publisher soon.
