### ISSUE TITLE
Definition Request: reactstrap

### ISSUE THREAD

**Issue by threehams** [DefinitelyTyped/DefinitelyTyped#12634]
I'm currently building type definitions for this library as I use it, so I'll eventually finish the whole thing.

However, if anyone has already written some, please contribute (or just link to a repo) to cut down on duplicate work. I can help with test coverage.

**Comment by ddwwcruz** [comment]
The definitions of reactstrap have already been made. #15357 

This should be closed now.

**Comment by bherila** [comment]
@threehams can you close this?

**Comment by threehams** [comment]
Yes! I missed the last message.
