### ISSUE TITLE
[react] React.createElement cannot be called with implicitly-typed stateless functional component and key prop

### ISSUE THREAD

**Issue by bvanreeven** [DefinitelyTyped/DefinitelyTyped#12647]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Referring to this .d.ts file:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/react/index.d.ts

Since version 0.14.47 of @types/react, a compile error occurs when trying to call `React.createElement` with an implicitly-typed SFC (stateless functional component) *and* adding a `key` to the props.

From the compile error it seems that a different overload of `React.createElement` is chosen by the compiler in this case. When explicitly specifying the type of the SFC, the correct overload is chosen and the compile error does not occur.

Example:

```tsx
import * as React from "react";

type Props = {name: string};

// Create SFC (stateless functional component).
const hello = (props: Props) => <div>Hello {props.name}!</div>;

// Create explicitly-typed SFC.
const hello2: React.SFC<Props> = (props: Props) => <div>Hello {props.name}!</div>;

React.createElement(hello, { name: "World" });
React.createElement(hello, { name: "World", key: 42 }); // <-- does not compile
React.createElement(hello2, { name: "World" });
React.createElement(hello2, { name: "World", key: 42 });
```

Compile error:
```
error TS2345: Argument of type '(props: { name: string; }) => Element' is not assignable to parameter of type 'ClassType<{ name: string; key: number; }, Component<{ name: string; key: number; }, ComponentStat...'.
  Type '(props: { name: string; }) => Element' is not assignable to type 'ComponentClass<{ name: string; key: number; }>'.
    Type '(props: { name: string; }) => Element' provides no match for the signature 'new (props?: { name: string; key: number; } | undefined, context?: any): Component<{ name: string; key: number; }, ComponentState>'
```

**Comment by vsiao** [comment]
I suspect this is because the `StatelessComponent<P>` interface specifies an optional `context` argument. Feel free to send a PR to fix.

**Comment by bvanreeven** [comment]
I discovered that this problem is actually caused by the `key` property in the erroneous call. Because the SFC is implicitly typed and does not have an explicit `props` type, the type parameter `P` of the method call cannot be determined, causing the compiler to select a different overload. I do not think this can be fixed in the React typings, as TypeScript simply cannot determine the correct type for the type parameter.

Workarounds include:
* Explicitly specify the props type parameter: `React.createElement<Props>(hello, { name: "World", key: 42 });`
* Explicitly cast the SFC: `React.createElement(hello as React.SFC<Props>, { name: "World", key: 42 });`
* Use JSX instead of `React.createElement`
