### ISSUE TITLE
cassandra-driver: wrong definition of Row type

### ISSUE THREAD

**Issue by mrgleba** [DefinitelyTyped/DefinitelyTyped#12662]
- [X ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - The authors of that type definition are cc/ @mhegazy @zhengbli 

The definition of Row curretnly is: 
  interface Row {
    get(columnName: string | number): { [key: string]: any; };
    values(): Array<{ [key: string]: any; }>;
    keys(): Array<string>;
    forEach(callback: Callback): void;
  }

which is wrong: 
 - get returns the value of the column and not the whole column:value dictionary,
 - values() returns only the values and not the whole dictionary.

Valid definiotion shoud read:
  interface Row {
    [key: string]: any;
    get(columnName: string | number): any;
    values(): Array<any>;
    keys(): Array<string>;
    forEach(callback: Callback): void;
  }

Original implementation:
https://github.com/datastax/nodejs-driver/blob/master/lib/types/row.js

**Comment by zhengbli** [comment]
Thanks for pointing out. You are welcomed to send a PR to correct the error :)

**Comment by mrgleba** [comment]
I'm not a git guy on a day-to day basis, but finally I was able to create one :)

**Comment by vvakame** [comment]
by #12750
