### ISSUE TITLE
Fix the declaration of FunctionColumnRender 

### ISSUE THREAD

**Issue by StevenLiekens** [DefinitelyTyped/DefinitelyTyped#12687]
- [x] I want to talk about `jquery.dataTables/jquery.dataTables.d.ts`.
  - The authors of that type definition are cc/ @Silver-Connection @omidkrad @pragmatrix @CNBoland 
---
The `FunctionColumnRender` callback should return `any` instead of `void`.

In `jquery.dataTables/jquery.dataTables.d.ts`
```ts
interface FunctionColumnRender {
    (data: any, t: string, row: any, meta: CellMetaSettings): void;
}
```
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery.dataTables/jquery.dataTables.d.ts#L1610-L1612

Documentation:
https://datatables.net/reference/option/columns.render
> the function will be executed and the returned value used.

**Comment by CNBoland** [comment]
I concur.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.
