### ISSUE TITLE
Fix the declaration of FunctionColumnData

### ISSUE THREAD

**Issue by StevenLiekens** [DefinitelyTyped/DefinitelyTyped#12686]
- [x] I want to talk about `jquery.dataTables/jquery.dataTables.d.ts`.
  - The authors of that type definition are cc/ @Silver-Connection @omidkrad @pragmatrix @CNBoland 
---
The `FunctionColumnData` callback should return `any` instead of `void`.

In `jquery.dataTables/jquery.dataTables.d.ts`
```ts
interface FunctionColumnData {
    (row: any, t: string, s: any, meta: CellMetaSettings): void;
}
```
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery.dataTables/jquery.dataTables.d.ts#L1595-L1597

Documentation:
https://datatables.net/reference/option/columns.data
> the function will be executed and the returned value used.

**Comment by CNBoland** [comment]
I concur. However, this is another example where the API is confusing in describing what, if any, data is returned, and it is difficult to express in TypeScript. Since in some cases returned data is required, and in other cases it is not, I was thinking the return type could be `void | any`, leaving it up to the developer to read the documentation and program accordingly.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by StevenLiekens** [comment]
I have a large number of improvements in mind (in addition to this one), but little time to work on it. I use these type declarations for my day-to-day job but the planning for my project is extremely tight and I can't work on improving the typings.

Is someone else prepared to make the changes? I can provide feedback in the form of GH issues / private chat.

**Comment by CNBoland** [comment]
I can help. I've been working on bringing _jquery.datatables_ up to current version. It's been slow because I've been doing it one version at a time for those that may need a particular version, and the PR integrators are busy too.

**Comment by StevenLiekens** [comment]
Sounds good. How can I reach you? Create issues and tag you?

Here's some info to get started. It applies to the function in this issue, but also to many other functions. Especially event callbacks.

The `column.data` callback is one of the functions that use a string discriminator to indicate what the inputs are and what the outputs should be.

```ts
interface FunctionColumnData {
    // t is a string discriminator
    (row: any, t: string, s: any, meta: CellMetaSettings): void;
}
```

The documentation says that the value of `t` (type) is limited to one of `'set'` or `'display'` or `'sort'` or `'filter'` or `'type'`.  It's better to represent these parameters in TypeScript using string literal types and unions of string literal types.

```ts
interface FunctionColumnData {
    (row: any, t: 'set' | 'display' | 'sort' | 'filter' | 'type', s: any, meta: CellMetaSettings): void;
}
```

Don't stop there. You can refine this API by splitting the signature into discriminated unions.

```ts
interface FunctionColumnData {
    (row: any, t: 'set', s: any, meta: CellMetaSettings): void;
    (row: any, t: 'display' | 'sort' | 'filter' | 'type', s: undefined, meta: CellMetaSettings): any;
}
```

This function is called as a setter when `t: 'set'` and does not expect a return type. The value of `s` is the value to set on the current `row`.

This function is called as a getter when `t: 'display' | 'sort' | 'filter' | 'type'` and any return value is acceptable. The value of `s` is always undefined when called as a getter.


In a future version it might be necessary to split the signatures even further.
```ts
interface FunctionColumnData {
    (row: any, t: 'set', s: any, meta: CellMetaSettings): void;
    (row: any, t: 'display', s: undefined, meta: CellMetaSettings): any;
    (row: any, t: 'sort', s: undefined, meta: CellMetaSettings): any;
    (row: any, t: 'filter', s: undefined, meta: CellMetaSettings): any;
    (row: any, t: 'type', s: undefined, meta: CellMetaSettings): any;
}
```

In this version, that extra verbosity adds no value. I'm just showing it to prove that this is a flexible API design because in the future you can tweak the signature of each callback type.

**Comment by StevenLiekens** [comment]
@vvakame I sent a PR
