### ISSUE TITLE
The is an empty npm-debug.log file in the branch types-2.0

### ISSUE THREAD

**Issue by e-cloud** [DefinitelyTyped/DefinitelyTyped#12688]
- [ ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

The filename is `npm-debug.log.3539137130`. You can't see it in github.

This is all i can track down.
![image](https://cloud.githubusercontent.com/assets/5255354/20303030/85d8b5e4-ab64-11e6-9675-9d2f0ed3670a.png)

**Comment by andy-ms** [comment]
Fixed by #12803
