### ISSUE TITLE
jQuery: add a constructor declaration to JQueryStatic to allow for narrowing on instanceof checks

### ISSUE THREAD

**Issue by avonwyss** [DefinitelyTyped/DefinitelyTyped#12692]
- [x] I want to talk about `jquery/jquery.d.ts`.
Since there are some 78 authors I don't mention them all here...

Is there a good reason for not having a `new (): JQuery;` line in the `JQueryStatic`? Without this, TS 2.x does not narrow down usages, e.g.:
```TS
function test(e: JQuery | Element) {
  if (e instanceof $) {
    e.each(...); // <- error, each not defined on JQuery | Element
  } else {
    e...
  }
}
```
With the added `new()` as described above, the compiler will narrow down the types to `JQuery` in the true branch and `Element` in the false branch. Calling `new $()` is obviously quite useless but legal so that should not be a problem.

**Comment by vvakame** [comment]
@johnnyreilly ?

**Comment by johnnyreilly** [comment]
I guess this would be okay.  Feels a bit hacky though; it rather suggests that newing up jQuery is a thing supported.  Is there another way to achieve the same end?

**Comment by avonwyss** [comment]
@johnnyreilly I'm not personally aware of another way, but I'm not the expert, so maybe someone in the TypeScript project could answer that. The goal is just for TypeScript to know how the `$` object and the `JQuery` type relate in terms of the prototype chain in order to enable the type guard and thus type narrowing.

**Comment by leonard-thieu** [comment]
A construct signature isn't enough to to use it as a type guard. `jQuery` needs to be a class. I tried to do it but couldn't figure it out 100%. From https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17159:

> <sub>On a side note, I tried to declare jQuery as a class given that jQuery is really a constructor function but that didn't pan out. I got everything working except for plugins (which some people may find to be a big deal). I couldn't figure out why jQuery interfaces were refusing to merge. If anyone wants to take a crack at it, my best attempt can be found at https://github.com/leonard-thieu/DefinitelyTyped/tree/jquery-rewrite/types/jquery.</sub>

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
