### ISSUE TITLE
analytics-node on the types-2.0 branch is broken

### ISSUE THREAD

**Issue by scharf** [DefinitelyTyped/DefinitelyTyped#12706]
The version on the https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/analytics-node/index.d.ts (which currently looks like this) https://github.com/DefinitelyTyped/DefinitelyTyped/blob/48c95a4bb4c59c9601f54bfb8e5625ba35be12dc/analytics-node/index.d.ts is broken, because it is not possible to create a 

According to the [documentation](https://segment.com/docs/sources/server/node/), an instance is supposed to be created like this:

```js
var Analytics = require('analytics-node');
var analytics = new Analytics('YOUR_WRITE_KEY');
```

But the typings definition suggests to create it like this:

```typescript
import AnalyticsNode = require("analytics-node");
new AnalyticsNode.Analytics('YOUR_WRITE_KEY');
```
But that does not work!

There is an old definition of the module that works: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/36d40a63a05b5cb3413737fbdf7c9a2a26f211fd/analytics-node/analytics-node.d.ts

The key here is

```typescript
declare module "analytics-node" {
  export = AnalyticsNode.Analytics;
}
```

I am not sure how this should look like with typescript-2.0, but the current definition is definitely broken.

**Comment by mhegazy** [comment]
Fixed by #12707
