### ISSUE TITLE
moment.d.ts missing optional parameter for utcOffset

### ISSUE THREAD

**Issue by gregveres** [DefinitelyTyped/DefinitelyTyped#12705]
I am using the latest version of moment.d.ts. it claims it is for version 2.11.1 of moment.js. 

The definition of utcOffset is wrong. According to the documentation here: http://momentjs.com/docs/#/manipulating/utc-offset/

there is an optional parameter of type boolean that indicates if the UTC time should be altered or not. 

The current definition is:
        utcOffset(): number;
        utcOffset(b: number): Moment;
        utcOffset(b: string): Moment;

I think the proper definition should be: 
        utcOffset(): number;
        utcOffset(b: number, keepExistingUTC?: boolean): Moment;
        utcOffset(b: string, keepExistingUTC?: boolean): Moment;

**Comment by Kovensky** [comment]
Moment ships their own type definitions, and [the definition there](https://github.com/moment/moment/blob/develop/moment.d.ts#L549) looks correct.
