### ISSUE TITLE
[Question] where to submit TS 2.1 definitions

### ISSUE THREAD

**Issue by pelotom** [DefinitelyTyped/DefinitelyTyped#12710]
`typescript@next` has just acquired a couple of very useful type system enhancements ([#11929](https://github.com/Microsoft/TypeScript/pull/11929) and [#12114](https://github.com/Microsoft/TypeScript/pull/12114)) which allow much more accurate typings of `underscore` (for example). If I wanted to submit some of these improvements, is there an appropriate branch on which to do it?

**Comment by TonyPythoneer** [comment]
@pelotom Currently, we are focusing on [types-2.0 branch](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0). You can fork this and submit the changes.

**Comment by pelotom** [comment]
Ok, thanks.
