### ISSUE TITLE
angular.d.ts missing "name" property in ng.IDirective 

### ISSUE THREAD

**Issue by krzysieki** [DefinitelyTyped/DefinitelyTyped#12718]
- [x] I tried using the latest `angularjs/angular.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I want to talk about `angularjs/angular.d.ts`.
  - The authors of that type definition are cc/ @thorn0, @smfeest, @snebjorn, @paulvanbrenk, @sandersn, @dt-bot

Latest version of ng.IDirective has no "name" property - it was removed in:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10527

Please restore this property because it is existing, useful and recommended by AngularJS creators in some advanced use cases.

Please check article:
https://toddmotto.com/dynamic-controllers-in-directives-with-the-undocumented-name-property/

**Comment by thorn0** [comment]
This property is an implementation detail. And what is described in that article is a hack. Type definitions are supposed to reflect public API, not things like this. If you need it in your project, you can always augment the types locally.

**Comment by krzysieki** [comment]
This property was present in angularjs/angular.d.ts before - so somebody saw it useful.

Please check:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10527
on why it was removed - because of some special use case.
@snebjorn proposed to use "name" to set a name for directive - but if property "name" is existing in directive and is connected with controller name - it shouldn't be used in other cases (despite it is not documented).

Moreover developer should be notified (by angularjs/angular.d.ts) that "name" property is existing and he should not misuse it  - and this is a job for type definition.

I wouldn't name it a hack solution. 
My understanding of type definitions is that it should describe existing properties - and should not decide which properties can be used and which cannot. 

I see your point: "Type definitions are supposed to reflect public API", but type definitions should also help developers avoiding mistakes and should have an informative role.

Please consider arguments above for "name"  property.

**Comment by thorn0** [comment]
Please see http://definitelytyped.org/guides/contributing.html

**Comment by krzysieki** [comment]
Thanks, closing issue.
