### ISSUE TITLE
Trying to call super.componentWillUnmount on a class extending a React.Component

### ISSUE THREAD

**Issue by kylenicola** [DefinitelyTyped/DefinitelyTyped#12758]
- [x] I want to talk about `react/index.d.ts`.
- The authors of that type definition are cc/ @vsiao @pspeter3

```
Class A extends React.Component {
  componentWillUnmount() {
        // do stuff
  }
}

const extend = (componentClass: React.ComponentClass) => {
  return class extends componentClass {
    componentWillUnmount() {
       super.componentWillUnmount()  // Error: Property 'componentWillUnmount' does not exist on type Component<P, ComponentState>
    }
  }
} 

```

So I filed this bug on typescript thinking the issue may be there:
https://github.com/Microsoft/TypeScript/issues/12282

The issue however is how React.Component is defined.  Since it uses 'implements the Component.Lifecycle' it does not inherit these methods.  My suggestion would be to add these lifecycle methods directly onto React.Component so that we're able to use those super methods.

**Comment by vsiao** [comment]
I would double check that `React.Component` actually has these methods implemented. I suspect that they do not, so it would be an error to call them via `super`.

**Comment by kylenicola** [comment]
Fair enough.  Ended up doing something like this:

```
private callComponentClassWillUnmount(): void {
      const componentClassWillUnmount = componentClass.prototype['componentWillUnmount'];

      if (componentClassWillUnmount) {
        componentClassWillUnmount.apply(this);
      }
    }
```
