### ISSUE TITLE
morris.js: "morris" module

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#12765]
- [X] I want to talk about `morris.js/index.d.ts`.
  - The authors of that type definition are cc/ @mareek, @sindilevich

I am wondering about #10867. `npm install morris` turns up nothing. `npm install morris.js` exists but the downloaded code does *not* define an importable module. Does `import Morris = require("morris");` really work at runtime?

**Comment by sindilevich** [comment]
@andy-ms, please note that #10867 was about describing morris.js correctly in terms of a TypeScript definition file. The PR allows using morris.js in Visual Studio with TypeScript files.

**Comment by andy-ms** [comment]
What do you mean by "correctly in terms of a TypeScript definition file"? TypeScript definition files should aim to be correct with respect to what the library actually does at runtime. If there is no importable `"morris"` module, then `import Morris = require("morris");` *should* be a compile error.

**Comment by sindilevich** [comment]
@andy-ms, morris.js does not implement any module definition by itself. But you can use it in conjunction with a module system, such as require.js, for example. This will be the actual resolver of the import. Hope it makes sense to you.
