### ISSUE TITLE
d3-quadtree definitions are too strict.

### ISSUE THREAD

**Issue by JonnyBGod** [DefinitelyTyped/DefinitelyTyped#12771]
- [ ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `d3-quadtree/index.d.ts`.
  - The authors of that type definition are cc/ @tomwanzek @gustavderdrache @borisyankov

The definitions for d3-quadtree look too strict. Atm we have to pass a [number, number][] but in practice we really can pass an Array<any> and this way it would be more flexible.

Following example works well but gives a bunch of definition errors:

```
      let tree = quadtree()
        .x((e) => e.x)
        .y((e) => e.y)
        .addAll(this.service.getNodes());

      let rb = 2 * 1 + 9;
      let exists = false;

      tree.visit((node, x1, y1, x2, y2) => {
        if (node.data && (node.data.id !== d.id)) {
          let x = d.x - node.data.x,
            y = d.y - node.data.y,
            l = Math.sqrt(x * x + y * y);

          if (l < rb) {
            l = (l - rb) / l * 0.5;
            d.x -= x *= l;
            d.y -= y *= l;
            node.data.x += x;
            node.data.y += y;
          }

          if (l < 30) {
            this.service.state.links.forEach((link) => {
              if (
                link.source.index === i && link.target.index === node.data.index ||
                link.target.index === i && link.source.index === node.data.index
              ) {
                exists = true;
              }
            });

            if (!exists) {
              this.service.createLink(d, { source: d.id, target: node.data.id });
            }
          }
        }
      });
```

errors:

```
[default] .../map.directive.ts:355:21
    Property 'x' does not exist on type '[number, number]'.
[default] .../map.directive.ts:356:21
    Property 'y' does not exist on type '[number, number]'.
[default] .../map.directive.ts:357:17
    Argument of type 'SimulationNodeDatum[]' is not assignable to parameter of type '[number, number][]'.
  Type 'SimulationNodeDatum' is not assignable to type '[number, number]'.
    Property '0' is missing in type 'SimulationNodeDatum'.
[default] Checking finished with 3 errors
```

**Comment by gustavderdrache** [comment]
I don't have a compiler on hand at the moment, but have you tried using the [`d3.quadtree` overload with a type parameter](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/d3-quadtree/index.d.ts#L49-L50)?

It'd be something like this:

```typescript
let tree = d3.quadtree<{ x: number, y: number }>()
  .x(d => d.x)
  .y(d => d.y);
```

**Comment by JonnyBGod** [comment]
Tried it but with:

```
let tree = quadtree<{ x: number, y: number }>()
        .x((e) => e.x)
        .y((e) => e.y)
        .addAll(this.mapService.getD3Nodes());
```

I get error:

```
[default] ../map.directive.ts:357:17
    Argument of type 'SimulationNodeDatum[]' is not assignable to parameter of type '{ x: number; y: number; }[]'.
  Type 'SimulationNodeDatum' is not assignable to type '{ x: number; y: number; }'.
    Property 'x' is optional in type 'SimulationNodeDatum' but required in type '{ x: number; y: number; }'.
[default] Checking finished with 1 errors
```

and with:

```
let tree = quadtree<{ x?: number, y?: number }>()
        .x((e) => e.x)
        .y((e) => e.y)
        .addAll(this.mapService.getD3Nodes());
```

i get:

```
[default] ../map.directive.ts:363:18
    Property 'data' does not exist on type 'QuadtreeInternalNode<{ x?: number; y?: number; }> | QuadtreeLeaf<{ x?: number; y?: number; }>'.
[default] ../map.directive.ts:363:32
    Property 'data' does not exist on type 'QuadtreeInternalNode<{ x?: number; y?: number; }> | QuadtreeLeaf<{ x?: number; y?: number; }>'.
[default] Checking finished with 9 errors
```

Looks like two incompatible definitions. Any reason why you think quad tree definitions should be so tight?

**Comment by JonnyBGod** [comment]
ok manages to remove all errors with:

```
let tree = quadtree<SimulationNodeDatum>()
        .x((e) => e.x)
        .y((e) => e.y)
        .addAll(this.mapService.getD3Nodes());

tree.visit((node: any, x1, y1, x2, y2) => {...}
```

**Comment by tomwanzek** [comment]
Apologies for the slight delay in chiming in, I was what they call "offline" yesterday...

As @gustavderdrache indicated, there are multiple signatures for the `quadtree` factory, to be precise:

```ts
export function quadtree(): Quadtree<[number, number]>;
export function quadtree(data: Array<[number, number]>): Quadtree<[number, number]>;
export function quadtree<T>(): Quadtree<T>;
export function quadtree<T>(data: Array<T>, x?: (d: T) => number, y?: (d: T) => number): Quadtree<T>;
```

The first two signatures correspond to the "default" data type assumption. And yes, @JonnyBGod , you are right that they would create compile errors, when used with any data type other than `Array<[number, number]>`. The reason I say default, is because they correspond to the default x- and y-accessors.

The second set of signatures is the generalized case which accepts any data type for an element in the data array.

Notably, when using the third or forth signature, it is critical that the x- and y-accessors are set appropriately. This can be done either when using the factory 4th signature (with initial data, x- and y-accessor), or as a configuration of the `Quadtree<T>` generator that is returned by the 3rd signature before applying it.

The latter is exactly what you have done now with `quadtree<SimulationNodeDatum>()`.

There is still a todo to complete JSDoc comments for the definitions. Where I have gotten to them yet, I have added in a comment per signature, that explains the meaning of generics in interfaces and factories.

Unfortunately, I did not have a chance to do the same for **d3-quadtree**. Cheers, T

**Comment by JonnyBGod** [comment]
@tomwanzek Thanks for explanation. Makes totally sense now.

**Comment by tomwanzek** [comment]
No worries, @gustavderdrache already had gotten you on the way. I mainly added the above "long form" explanation in for historic record as this is a fairly common pattern throughout the D3 module definitions, only sometimes it involves more than one generic.

Do not hesitate to raise issues/questions like this one in the future though. There is a chance that some of the definitions are too tight for some use cases, I had already relaxed a definition in d3-format after similar feedback. So, thanks!
