### ISSUE TITLE
qrcode-generator/qrcode-generator.d.ts is outdated

### ISSUE THREAD

**Issue by maximumver** [DefinitelyTyped/DefinitelyTyped#12774]
- [x] I tried using the latest `qrcode-generator/qrcode-generator.d.ts` file in this repo and had problems.
- [x] I want to talk about `qrcode-generator/qrcode-generator.d.ts`.
  - The authors of that type definition are cc/ @stefanhuber @kazuhikoarase

Hi, it seems that this definition is outdated, i don't know much about typescript. 
But it looks that some methods have changed their names.
For example: 
`createImageTag(cellSize: number, margin: number) : string; `   
became `createImgTag`
And it seems that some method parameters are optional now..

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by maximumver** [comment]
Thanks, but i am somehow resolved this already time ago.
Don't remember how, maybe 'qrcode-generator' has his own .d.ts file included.
