### ISSUE TITLE
can not install @types/threejs from npm ?

### ISSUE THREAD

**Issue by dyh333** [DefinitelyTyped/DefinitelyTyped#12777]
as the title, i try to install typescript typings for threejs by using npm install, but failed. 
and i can not find something like @types/threejs in https://www.npmjs.com. 
does any plan to upload it to npm server?

**Comment by andy-ms** [comment]
This is available as `@types/three` instead.

**Comment by dyh333** [comment]
thanks, @andy-ms . i found it.
