### ISSUE TITLE
Leaflet: Point interface is incorrect

### ISSUE THREAD

**Issue by HarelM** [DefinitelyTyped/DefinitelyTyped#12785]
Latest leaflet.d.ts file for the latest release of version 1.0 is incorrect:
in ```Point``` interface the following functions are wrong - they should return ```number``` instead of ```Point```
```js
distanceTo(otherPoint: Point): Point;
distanceTo(otherPoint: PointTuple): Point;
```
The NuGet package should not have both versions as they create conflicts when used in Visual Studio...

**Comment by alejo90** [comment]
I just submitted a fix for this issue. I have no experience with Nuget but I think the problem you are seeing comes from whatever they are doing to generate the package. I believe creating a separate issue for that may be better.
