### ISSUE TITLE
Promise not defined in node.d.ts

### ISSUE THREAD

**Issue by midknight41** [DefinitelyTyped/DefinitelyTyped#12781]
- [x] I tried using the latest `node/index.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `node/index.d.ts`.
  - The authors of that type definition are cc/ @RyanCavanaugh 

Unless I'm confused, shouldn't there be a Promise class defined in here? It's been in node.js since v4. It appears to be missing on master and types-2.0

There does appear to be quite a few issues against the node.js definition.

**Comment by andy-ms** [comment]
Use `--lib es6`. More info [here](http://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by midknight41** [comment]
Ah! Thanks @andy-ms
