### ISSUE TITLE
Jasmine CustomEqualityTester interface and Typescript 2.

### ISSUE THREAD

**Issue by SeanSobey** [DefinitelyTyped/DefinitelyTyped#12801]
- [ *] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [* ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Equality testers in jasmine can return true, false and undefined. With the 2.0 typescript compiler option `"strictNullChecks": true` we get the following compiler error with the jasmine type definition:

> Type '(first: any, second: any) => boolean | undefined' is not assignable to type 'CustomEqualityTester'.
>   Type 'boolean | undefined' is not assignable to type 'boolean'.
>     Type 'undefined' is not assignable to type 'boolean'.

I believe the fix would be to change the definition to like so:
```
interface CustomEqualityTester {
	(first: any, second: any): boolean | undefined;
}
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by zvirja** [comment]
@SeanSobey Could you please review whether it's still relevant? Looks like feature is already here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f764e7d5b727818dfc56f87b9864d1ae25c610b0/types/jasmine/ts3.1/index.d.ts#L317

Thanks!

**Comment by SeanSobey** [comment]
Yes its working correctly now, thanks!
