### ISSUE TITLE
Moment CalendarSpecVal interface and Typescript 2. 

### ISSUE THREAD

**Issue by SeanSobey** [DefinitelyTyped/DefinitelyTyped#12802]
- [*] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [*] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

With the 2.0 typescript compiler option `"strictNullChecks": true` we get the following compiler error with the moment type definition:

> Build:Property 'sameDay' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.	*\node_modules\moment\moment.d.ts	63	
> Build:Property 'nextDay' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.	*\node_modules\moment\moment.d.ts	64	
> Build:Property 'lastDay' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.	*\node_modules\moment\moment.d.ts	65	
> Build:Property 'nextWeek' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.	*\node_modules\moment\moment.d.ts	66	
> Build:Property 'lastWeek' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.	*\node_modules\moment\moment.d.ts	67	
> Build:Property 'sameElse' of type 'string | ((m?: Moment | undefined, now?: Moment | undefined) => string) | undefined' is not assignable to string index type 'CalendarSpecVal'.	*\node_modules\moment\moment.d.ts	68

I believe the fix would be to change the definition to like so:

`type CalendarSpecVal = string | ((m?: Moment, now?: Moment) => string) | undefined;`

**Comment by horiuchi** [comment]
The `moment.d.ts` is hosted by official repository instead of `DefinitelyTyped`.
Please vote this pull request: https://github.com/moment/moment/pull/3591

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
