### ISSUE TITLE
Knex asCallback is missing

### ISSUE THREAD

**Issue by cdekok** [DefinitelyTyped/DefinitelyTyped#12817]
- [ ] I want to talk about `knex/index.d.ts`.
  - The authors of that type definition are cc/ @tkQubo

It seems asCallback is missing from the definition file.

**Comment by calebeaires** [comment]
@cdekok Same here, have you found solution!?

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by tkqubo** [comment]
Thanks for your question, but sorry currently I have no time to help you.  Your PR is welcomed 🙇

**Comment by taybin** [comment]
This can be closed as knex provides its own definitions now.

**Comment by cdekok** [comment]
Closing then :)
