### ISSUE TITLE
"assert" module

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#12826]
- [X] I want to talk about `assert/index.d.ts`.
  - The authors of that type definition are cc/ @vvakame

This claims to have 2 projects: https://github.com/Jxck/assert and https://github.com/twada/power-assert .
Jxck/assert is no longer maintained as of Oct 2015, so we can ignore that.
power-assert is actively maintained, and should have its own package.

I think we should deprecate `@types/assert` and create `@types/power-assert`.
Also, it could probably be as simple as:

```ts
/// <reference types="node"/>
import assert = require("assert");
export = assert;
```

**Comment by vvakame** [comment]
sorry for late.
I agree with your opinions.
