### ISSUE TITLE
phonegap-plugin-push.d.ts: subscribe() and unsubscribe() Methods missing

### ISSUE THREAD

**Issue by mikolama** [DefinitelyTyped/DefinitelyTyped#12827]
- [ ] I want to talk about `phonegap-plugin-push/phonegap-plugin-push.d.ts`.

It seems that the methods for subscribing to topics "subscribe(...)" and "unsubscribe(...)" are missing in definition file.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by RayComBomber** [comment]
PR: #13496
