### ISSUE TITLE
Consider making changes to the file system layout

### ISSUE THREAD

**Issue by orta** [DefinitelyTyped/DefinitelyTyped#12878]
Hey there everyone, I've been running a project called CocoaPods for the last few years, and we're had a few problems with a folder structure like this in GitHub - just wanted to give you a heads up.

We currently have about 25k folders in a [git repo](https://github.com/cocoapods/specs/) and we were really starting to [hit performance problems](http://blog.cocoapods.org/Sharding/) because of this structure.

An easy start is to move your types into a sub-folder so that the GitHub page can be a bit less resource intensive, the next one would be to use the same folder structure that CocoaPods and Homebrew uses, which is basically [using a split MD5 string](https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/source/metadata.rb#L41).

Considering the scope of this project, you could very easily hit more files than the CocoaPods Specs repo, so thought I'd offer some feedback 👍

**Comment by vvakame** [comment]
cc/ @DefinitelyTyped/infrastructure

**Comment by orta** [comment]
and now I'm an admin on this repo, everything comes full circle ey?

Thinking about this a few years down the line: The perf issues we got from the CP Specs repo came mainly through clones, and especially shallow clones of the repo from users. DT generates @types npm modules, so folks can grab those subsets of a repo in a way which doesn't make sense in the context of CP. 

So I'm happy to say we don't need to heed this warning from past me 👍
