### ISSUE TITLE
Type definitions for Knockout v3.4.0 failure with extend

### ISSUE THREAD

**Issue by MBurchard** [DefinitelyTyped/DefinitelyTyped#12880]
- [x] I tried using the latest `http_github.com_DefinitelyTyped_DefinitelyTyped_raw_master_knockout_knockout.d.ts` file in this repo and had problems.
- [x] I want to talk about `http_github.com_DefinitelyTyped_DefinitelyTyped_raw_master_knockout_knockout.d.ts`.
  - The authors of that type definition are cc/ @borisyankov @Igorbek 

I installed the External Library into the newest Webstorm today.

		this.roles = ko.observableArray(_d.roles).extend({trackChanges: {initial: false}});
		this.type = ko.observable(_d.type || 'user').extend({trackChanges: {initial: false}});
		this.enabled = ko.observable(_d.enabled).extend({trackChanges: {initial: false}});
		this.salutation = ko.observable(_d.salutation).extend({
			trackChanges: {initial: false},
			validator: {required: false}
		});

In the first line, the extend Method is not resolved.
In the second and third line, it is resolved.
In the fourth line it is again unresolved.

Is this a known Issue and if yes, it's WebStorm or DefinitelyTyped problem

**Comment by Igorbek** [comment]
I've checked that and it worked for me:
```ts
import * as ko from 'knockout';

const o1 = ko.observableArray([1, 2, 3]).extend({trackChanges: {initial: false}});
const o2 = ko.observable('user').extend({trackChanges: {initial: false}});
const o3 = ko.observable(true).extend({trackChanges: {initial: false}});
const o4 = ko.observable(false).extend({
    trackChanges: {initial: false},
    validator: {required: false}
});
```

All the calls have been resolved successfully.

**Comment by MBurchard** [comment]
Don't know where you tested it. As I said, I tested it with WebStorm 2016.3.
But I solved it by not using DefinitelyTyped anymore.
I downloaded all the not minified original JavaScript libraries and configured WebStorm to use them. This works perfectly well :)
