### ISSUE TITLE
Incorrect name of arc property in interface ChartElementsOptions of chart.js.d.ts

### ISSUE THREAD

**Issue by greatromul** [DefinitelyTyped/DefinitelyTyped#12912]
Hello! I've found property `arg?` in interface `ChartElementsOptions` in `chart.js/chart.js.d.ts` (line 172). I guess, it's wrong name. The property should be named as `arc?`, shouldn't it?

The authors of that type definition are @nnnick and @anuti

**Comment by stephtr** [comment]
According to the [documentation](http://www.chartjs.org/docs/#chart-configuration-element-configuration) it should be `arc`. In addition it would make sense to name the type `ChartArcOptions` instead of `ChartArcOtpions`.
