### ISSUE TITLE
Beginner needs help.

### ISSUE THREAD

**Issue by wstaelens** [DefinitelyTyped/DefinitelyTyped#12911]
I've just started with TypeScript and converted some javascript code to TypeScript.
We use jQuery and also a library called Summernote.

To make my TypeScript build I had to write a .d.ts file for summernote.

This file can be found here:
https://github.com/wstaelens/TypeScript-Summernote/tree/master/summernote 

I'm totally new, but still have some questions.
The summernote API is available via http://summernote.org/deep-dive/

**Questions:**

- Have a look at my d.ts file ( https://github.com/wstaelens/TypeScript-Summernote/tree/master/summernote ). Am I doing good so far?

- How do I translate these structures to a definition (nested options and callbacks):

**nested options** ( http://summernote.org/deep-dive/#custom-toolbar-popover ):
```JavaScript
$('#summernote').summernote({
  toolbar: [
    // [groupName, [list of button]]
    ['style', ['bold', 'italic', 'underline', 'clear']],
    ['font', ['strikethrough', 'superscript', 'subscript']],
    ['fontsize', ['fontsize']],
    ['color', ['color']],
    ['para', ['ul', 'ol', 'paragraph']],
    ['height', ['height']]
  ]
});
```

and **callbacks with options** ( http://summernote.org/deep-dive/#callbacks ):

```JavaScript
// onInit callback
$('#summernote').summernote({
  callbacks: {
    onInit: function() {
      console.log('Summernote is launched');
    }
  }
});

// summernote.init
$('#summernote').on('summernote.init', function() {
  console.log('Summernote is launched');
});
```

- How do you translate this 'editor.insertText' but also 'insertText' is a valid name:

You can add code like this:
```JavaScript
$('#summernote').summernote('editor.insertText', 'hello world'));
// If you call API without module name, editor.methodName will be called.
$('#summernote').summernote('insertText', 'hello world');
// info: http://summernote.org/deep-dive/#basic-api
```

Thanks already. Hope I can contribute more in the future!

(also new to github I currently only drag&drop files in github.com site to upload changes (Team Foundation Server user)

**Comment by cmann1** [comment]
I'm also a bit new to Typescript and I'm not sure what the best practices are but I'll try answer some of your questions.

## 1.
> How do I translate these structures to a definition (nested options and callbacks):
> nested options ( http://summernote.org/deep-dive/#custom-toolbar-popover ):

You can use the `type` keyword to define new types of any kind:
```typescript
type ToolbarDef = [string, string[]][];
```
You could go even further by defining acceptable values for groupNames and buttons:
```typescript
type ToolbarGroupName = 'style' | 'font' | 'fontsize'; /* etc. */
type ToolbarGroupButton = 'bold' | 'italic' | 'underline'; /* etc. */
type ToolbarDef = [ToolbarGroupName , ToolbarGroupButton[]][];
```

## 2.
> and callbacks with options ( http://summernote.org/deep-dive/#callbacks ):

Not sure what you mean here but you can also define object and function types with expected and optional paramters:
```typescript
type OptionsDef = {
  callbacks?: {
    [event:string]:() => void
  }
};
```
You can read the documentation to see about defining function type: https://www.typescriptlang.org/docs/handbook/functions.html#writing-the-function-type

## 3.

> How do you translate this 'editor.insertText' but also 'insertText' is a valid name:

Same as a above, you can specify multiple accepted types with the `|` character:
```typescript
summernote(command: 'insertNode'|'editor.insertText', node: Node): JQuery;
```

**Comment by wstaelens** [comment]
thanks for the information!
