### ISSUE TITLE
Signalr

### ISSUE THREAD

**Issue by crh225** [DefinitelyTyped/DefinitelyTyped#12953]
- [X] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [N/A] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....
@keezey, @borisyankov 

withCredentials is missing from the ConnectionOptions interface. I believe it should look like below:

```
    interface ConnectionOptions {
        transport?: string | Array<string> | Transport;
        callback?: Function;
        waitForPageLoad?: boolean;
        jsonp?: boolean;
        pingInterval?: number;
        withCredentials?: boolean;
    }
```

**Comment by ldcdev** [comment]
+ 1 I have same issue

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by crh225** [comment]
@vvakame https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13464
