### ISSUE TITLE
isomorphic-fetch/index.d.ts cannot be included in a project without lib: "dom"

### ISSUE THREAD

**Issue by akdor1154** [DefinitelyTyped/DefinitelyTyped#12968]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
- The authors of that type definition are cc/ @toddlucas

isomorphic-fetch should give us definitions which can be used in-browser or on the server. Hence, it should work with `lib: ["es5", "es6"]` as it does not depend on any browser-specific features. However, this leads to build errors as it directly references Blob and FormData. Should these properties be removed? I'm not confident enough that this is the correct solution to raise a PR immediately, though if this approach is sanctioned I'm happy to do the work.

**Comment by toddlucas** [comment]
I haven't figured out a good way to handle these differences. The problem obviously comes down to the fact that isomorphic-fetch is really two different fetches, with different implementations and standards compliance.

There are at least two ways to build a typings file for this situation. One option is to go with the common subset approach, which would remove all expected fetch typing information that was not in node-fetch. This would present problems for people who want to make full use of fetch in the browser, of course. A second option is to include everything in the browser-based fetch and rely on the developer to know what environment they're running in, and to know what is and isn't supported in node-fetch. This can lead to build or runtime errors. 

The second approach is what the current typings use, as you've pointed out. If it were possible to split out the browser-fetch superset, modulo the common subset, I think that would be very useful. I'm not sure how best to do that in a way that supports common environments and tools. If you have some ideas, I'd be interested in hearing them. Thanks.

**Comment by vvakame** [comment]
If you want to avoid this issue, you can use this pattern.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/index.d.ts#L35-L41
```
interface Blob {}
interface FormData {}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
