### ISSUE TITLE
How to get latest nconf typings via `npm i @types/nconf`?

### ISSUE THREAD

**Issue by k0pernikus** [DefinitelyTyped/DefinitelyTyped#12978]
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `nconf`.

I am using nconf and installed its typings via:

    npm i @types/nconf --save

which installs

     "@types/nconf": {
       version: 0.0.32,
       from: @types/nconf@0.0.32,
       resolved: https://registry.npmjs.org/@types/nconf/-/nconf-0.0.32.tgz
     },

I got the version from [soywiz/typescript-node-definitions](https://github.com/soywiz/typescript-node-definitions) and I thought it was the "correct" repository for it and hence I opened a [pull request](https://github.com/soywiz/typescript-node-definitions/pull/57#issuecomment-263333102) about the `get` method being able to have all parameters optional.

Yet there I was pointed that that repository was abaonded and this one should be used. And true enough, [these typings from this repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/nconf) here are more up to date as the get fix was already provided.

Yet why aren't those fetched when I install the typings? Why do I see the outdated one?

**Comment by mhegazy** [comment]
The source of `@types/nconf` is at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/nconf/index.d.ts

the package has `0.0.32` version since the https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/nconf/index.d.ts does not have a version at the top.

**Comment by Sikian** [comment]
@mhegazy I believe the url is https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/nconf/index.d.ts, I'm getting a 404 with yours.

At any rate, I believe what @mhegazy is trying to convey is that the typings from this repo is the one being fetched. but they seem to be quite out of date. The fact that the file says "Imported from:" is to mention from where the file was copied into this repo. You can see this if you look at the original file https://github.com/soywiz/typescript-node-definitions/blob/master/nconf.d.ts which doesn't have that header.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
