### ISSUE TITLE
angular-strap - Missing templateUrl in IModalOptions

### ISSUE THREAD

**Issue by jjoekoullas** [DefinitelyTyped/DefinitelyTyped#12988]
- [x] I want to talk about `angular-strap/angular-strap.d.ts`.
  - The authors of that type definition are cc/ @samherrmann

See `templateUrl` listed under options in [the angular-strap docs](http://mgcrea.github.io/angular-strap/#/modals).  This property isn't in the current `.d.ts` for angular-strap.

**Comment by samherrmann** [comment]
see #12990
