### ISSUE TITLE
Linear Gradient as Highcharts color not supported

### ISSUE THREAD

**Issue by meddario** [DefinitelyTyped/DefinitelyTyped#12983]
Hi,

- [x] I tried using the latest `highcharts/highcharts.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

it seems that it isn't possible to specify a gradient for the chart colors. For example, this code doesnt' work:
```typescript
        var chartOptions: __Highcharts.Options = {
            chart: {
                type: 'column'
            },
            title: null,
            subtitle: null,
            credits: false,
            colors: [{
                lineargradient: { x1: 0, x2: 0, y1: 0, y2: 1 },
                stops: [
                    [0, '#0077ad'],
                    [1, '#b9e1f3']
                ]
            }],
        };
```
Giving the error: 
`Error	TS2322	Type '{ chart: { type: string; }; title: null; subtitle: null; credits: boolean; colors: { [x: number]:...' is not assignable to type 'Options'.
  Types of property 'colors' are incompatible.
    Type '{ [x: number]: undefined; lineargradient: { x1: number; x2: number; y1: number; y2: number; }; st...' is not assignable to type 'string[]'.
      Type '{ [x: number]: undefined; lineargradient: { x1: number; x2: number; y1: number; y2: number; }; st...' is not assignable to type 'string'.`

This highcharts option is documented here: http://www.highcharts.com/docs/chart-design-and-style/colors

Is there any workaround to make this work?

Thanks in advance

**Comment by BrianLaughlan** [comment]
"stops" on the yAxis for the **solid gauge chart** is also missing from the .d.ts... 

![image](https://cloud.githubusercontent.com/assets/8556999/20835156/5561f1c2-b899-11e6-9e2c-40d4341cc40d.png)

http://api.highcharts.com/highcharts/yAxis.stops

**Comment by PBartrina** [comment]
Are those options from Highcharts v5.* ?
I find missing quite a lot of options and the actual types are for highcharts v4.2

**Comment by LeonDWong** [comment]
Same problem in v8.0.0, could any one help?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
