### ISSUE TITLE
[react-native] - Button is missing

### ISSUE THREAD

**Issue by tvedtorama** [DefinitelyTyped/DefinitelyTyped#13002]
The Button type is missing from the react-native typings.

I added it locally as:
```
export var Button: TouchableHighlightStatic
export type Button = TouchableHighlightStatic
```

... which works, but that might not be the correct way.

**Comment by tvedtorama** [comment]
As a work-around, you could do:

```
import * as ReactNative from 'react-native'
const {Button} = (ReactNative as any as {Button: TouchableHighlight}) 
```
... in addition to your ordinary imports.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by iRoachie** [comment]
@alloy Can close this. It's been added
