### ISSUE TITLE
@types/angular-mocks states it's latest version as 0.0.0 on npmjs

### ISSUE THREAD

**Issue by kristho91** [DefinitelyTyped/DefinitelyTyped#13003]
I tried to run an npm outdated on my project and it told me, that there was a new version for @types/angular-mocks available. But the "new" version is 0.0.0. I can see that npmjs pulls from the types-2.0 branch, but there is no project file for angular-mocks. Maybe that's why the version is wrong?

**Comment by ersimont** [comment]
I came searching about this same issue. I am the one who submitted the PR that caused the new version when it was merged (#12931), but I don't know enough to be more helpful solving it.  I simply modified an existing method signature!

It looks like the `angular-mocks` directory has all the files listed in the [create a new package docs](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0#create-a-new-package) except `tslint.json`.  I doubt that file would help, but anyway there's some more info.
