### ISSUE TITLE
@types/node states it's latest version as 0.0.2 from `npm outdated`

### ISSUE THREAD

**Issue by ersimont** [DefinitelyTyped/DefinitelyTyped#13032]
This seems very similar to #13003, and just started yesterday or today, around the same time as that issue appeared for me.  Running `npm outdated` shows:

```
@types/angular-mocks             1.5.7    1.5.7         0.0.0  sd.app
@types/lodash                  4.14.40  4.14.41       4.14.41  sd.app
@types/node                     6.0.51   6.0.51         0.0.2  sd.app
```

As you can see, the 2 packages in question are incorrect, while `lodash` looks fine.

**Comment by e-cloud** [comment]
no response from maintainer?

**Comment by mhegazy** [comment]
@andy-ms has a fix for this.

**Comment by andy-ms** [comment]
The next update to `node` should publish under `6.0` once more.
