### ISSUE TITLE
[Request] update the uglify-js type definition

### ISSUE THREAD

**Issue by e-cloud** [DefinitelyTyped/DefinitelyTyped#13035]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `uglify-js/index.d.ts`.
  - The author of that type definition is @tkrotoff

When using the current `uglify-js` type definition for webpack, I found it mostly uncompatible with latest uglify-js.

It has problems below:
1. a lot of ast node class of `uglify-js` is missing.
2. some of current typed interfaces are incompatible with latest uglify-js.

---
PS: I use webstorm to inspect the exports of with uglify-js.

![image](https://cloud.githubusercontent.com/assets/5255354/20789399/3995ea3e-b7ef-11e6-918a-77ba80e007a5.png)
![image](https://cloud.githubusercontent.com/assets/5255354/20789403/3def62e0-b7ef-11e6-8a85-bcea4be19141.png)
![image](https://cloud.githubusercontent.com/assets/5255354/20789405/408033cc-b7ef-11e6-83d6-4954f3a1767a.png)
![image](https://cloud.githubusercontent.com/assets/5255354/20789409/42f5b708-b7ef-11e6-8a01-8d8c6d47c3b7.png)

**Comment by tkrotoff** [comment]
@e-cloud UglifyJS2 is *huge*, see http://lisperator.net/uglifyjs/ast and http://lisperator.net/uglifyjs/walk. Implementing everything (and test that everything works fine) is in my opinion a waste of time.

The intent was to have something minimal for type definitions inter-dependencies, see #7512, specially [this schema](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7512#issuecomment-170573879):

```
gulp-htmlmin -> HTMLMinifier -> UglifyJS  <- webpack, gulp-uglify
                                clean-css <- gulp-minify-css
                                relateurl
```

If you feel UglifyJS2 type definition is missing some parts that you need, you can make a PR.

**Comment by e-cloud** [comment]
In fact, i'm also not interested in its multiple node types.

The key point is that, except those node types, other typed interfaces and functions have wrong typings, like unmatched signature.

I just assume you may be more familar with uglify-js, and more appropriate to fix it.

**Comment by tkrotoff** [comment]
> typed interfaces and functions have wrong typings

First step is to list them :)

**Comment by e-cloud** [comment]
such as 
![image](https://cloud.githubusercontent.com/assets/5255354/20821967/d4f32900-b881-11e6-8e72-97807967df4e.png)
argument missing.

Not only AST_Node is an interface but also a namespace. It has some static methods attached.

**Comment by e-cloud** [comment]
It would be great if you add these exported functions:
![image](https://cloud.githubusercontent.com/assets/5255354/20822043/66cdf60c-b882-11e6-9f63-1ac0b05205fd.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
