### ISSUE TITLE
How to use @types in express project

### ISSUE THREAD

**Issue by blackhawk389** [DefinitelyTyped/DefinitelyTyped#13033]
Installed with npm install --save @types/express
Import in project import * as express from "@types/express";
var app = express();
I dont know its necessary to reference into project file
Getting error when starting server "Can not find module @types/express"

tsconfig:
{
	"compilerOptions": {
		"target": "ES5",
		"module": "commonjs",
        "typeRoots" : ["node"]
	}
}

**Comment by aluanhaddad** [comment]
It works for me. But for the love of all things, please write
```ts
import * as express from 'express';
```
or your app will die at runtime.
