### ISSUE TITLE
ERROR when including @types/mocha and transpilling with webpack

### ISSUE THREAD

**Issue by BorntraegerMarc** [DefinitelyTyped/DefinitelyTyped#13064]
- [X] I tried using the latest `mocha/index.d.ts` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] I want to talk about `mocha/index.d.ts`.
  - The authors of that type definition are cc/ @vvakame, @ligaz, 

I've started a new angular2 project and included the following dev dependency:
`"@types/mocha": "2.2.33",`

It installs correctly however when I run:
`webpack --config webpack.config.dev.js --progress --profile --watch`

I get:
```
[at-loader] node_modules/@types/jasmine/index.d.ts:15:18 
    Duplicate identifier 'xit'. 

[at-loader] node_modules/@types/mocha/index.d.ts:33:13 
    Duplicate identifier 'describe'. 

[at-loader] node_modules/@types/mocha/index.d.ts:34:13 
    Duplicate identifier 'xdescribe'. 

[at-loader] node_modules/@types/mocha/index.d.ts:39:13 
    Duplicate identifier 'it'. 

[at-loader] node_modules/@types/mocha/index.d.ts:40:13 
    Duplicate identifier 'xit'. 

```

My webpack config file:
```
var webpack = require('webpack');

module.exports = {
    devtool: 'cheap-module-eval-source-map',

    output: {
        path: './public/js/app',
        publicPath: "/js/app/",
        filename: 'bundle.js',
        chunkFilename: '[id].chunk.js'
    },
    entry: {
        'app': './assets/app/main.polymer.ts'
    },

    resolve: {
        extensions: ['.js', '.ts']
    },

    module: {
        loaders: [
            {
                test: /\.ts$/,
                loaders: [
                    'awesome-typescript-loader',
                    'angular2-template-loader',
                    'angular2-router-loader'
                ]
            },
            {
                test: /\.html$/,
                loader: 'html'
            },
            {
                test: /\.css$/,
                loader: 'raw'
            }
        ]
    },

    plugins: [
        new webpack.ContextReplacementPlugin(
            // The (\\|\/) piece accounts for path separators in *nix and Windows
            /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
            './src' // location of your src
        )
    ]
};
```

Same thing happens with @types/jasmine. Maybe there is a relation?

**Comment by BorntraegerMarc** [comment]
Just found out that the errors:
```
[at-loader] node_modules/@types/jasmine/index.d.ts:9:18 
    Duplicate identifier 'describe'. 

[at-loader] node_modules/@types/jasmine/index.d.ts:11:18 
    Duplicate identifier 'xdescribe'. 

[at-loader] node_modules/@types/jasmine/index.d.ts:13:18 
    Duplicate identifier 'it'. 

[at-loader] node_modules/@types/jasmine/index.d.ts:15:18 
    Duplicate identifier 'xit'. 

```

Also come from here...

**Comment by ligaz** [comment]
It looks like you have both Jasmine and Mocha declaration files that augment the global scope with same variables: `describe`, `it`, etc. You should remove either `@types/mocha` or `@types/jasmine`.

**Comment by BorntraegerMarc** [comment]
Thanks for the fast answer. But I only include mocha. Maybe mocha includes jasmine itself?

**Comment by alejo90** [comment]
No, mocha doesn't include jasmine. Check if you accidentally installed jasmine typings or if one of the other typings you are using includes it as a dependency.

**Comment by BorntraegerMarc** [comment]
Yup, you're right. Just found this issue: https://github.com/s-panferov/awesome-typescript-loader/issues/135

Also commented my fix there. Sorry for opening the issue on the wrong project. Thanks!

**Comment by alejo90** [comment]
Thanks for pointing that issue out. I'm using that loader as well.

**Comment by BorntraegerMarc** [comment]
@alejo90 & @ligaz OK seemed like you guys were right. I just found out that my `"protractor": "4.0.11",` uses jasmine. When I exclude that one, then everything works fine. Do you guys have a solution for this?

**Comment by ligaz** [comment]
I'm not sure why protractor has `@types/jasmine` as `dependency` and not `devDependency`: https://github.com/angular/protractor/blob/master/package.json#L15. Maybe you should open an issue over there.

**Comment by BorntraegerMarc** [comment]
@ligaz thx. Will do so. But this wouldn't solve the problem as well, right? Because the dependencies gets included anyway?

**Comment by BorntraegerMarc** [comment]
Excuse me for asking these questions, but I just have really no idea where to start finding a solution...

**Comment by ligaz** [comment]
`devDependencies` are not included in the final npm package. Regarding to where to start from it looks like you have the following options:
* Use Jasmine, instead of Mocha.
* Tell TypeScript to ignore all files under `node_modules/@types/jasmine` via `tsconfig.json`.

**Comment by BorntraegerMarc** [comment]
With
```
  "exclude": [
    "node_modules"
]
```

Because that doesn't work?

**Comment by ligaz** [comment]
Another thing you can do is to have a post install script that deletes the offending declaration files.

**Comment by ligaz** [comment]
But I think the issue lies in the fact that protractor uses only jasmine, so it conceptually does not support mocha. This yields that if you want to use protractor you should create a separate `package.json` for your E2E tests and not use your root one.

**Comment by BorntraegerMarc** [comment]
OK, I use mocha for other tests. Not protractor... But the post install script is a good idea. Thanks!
