### ISSUE TITLE
React: Component.refs should be HTMLElement?

### ISSUE THREAD

**Issue by tkrotoff** [DefinitelyTyped/DefinitelyTyped#13123]
Currently refs is defined as [ReactInstance (Component<any, any> | Element)](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/31d40c86725a2f3c4012984b0626f3b0a11a61ea/react/index.d.ts#L181):
```TypeScript
class Component<P, S> {
   ...
   refs: {
        [key: string]: ReactInstance
    };
}
```
See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/31d40c86725a2f3c4012984b0626f3b0a11a61ea/react/index.d.ts#L181

I believe this is [a relic from the past](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#dom-node-refs):
*[...] we looked at what you can do with a ref to a React DOM component and realized that the only useful thing you can do with it is call this.refs.giraffe.getDOMNode() to get the underlying DOM node. Starting with this release, this.refs.giraffe is the actual DOM node. Note that refs to custom (user-defined) components work exactly as before; only the built-in DOM components are affected by this change.*

It should be a [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement):

```TypeScript
class Component<P, S> {
   ...
   refs: {
        [key: string]: HTMLElement
    };
}
```

ping @pspeter3 @vsiao based on what I could find in Git blame.

Example of use (there is none currently inside [react-tests.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/31d40c86725a2f3c4012984b0626f3b0a11a61ea/react/react-tests.ts) => what is not tested will obviously break...) :

```TypeScript
class Confirm extends React.Component<void, void> {
  componentDidUpdate() {
    const { example } = this.refs;
    example.focus();
    example.title = 'Hello';
    example.blur();
    example.contains(...);
    ... and all things from HTMLElement...
  }

  render() {
    return (
      <div ref="example" />
    );
  }
}
```

**Comment by vsiao** [comment]
> Note that refs to custom (user-defined) components work exactly as before

which means that it's still possible for the ref to be a `Component<P, S>`. BTW, I would suggest that you use callback refs, which have stronger types built-in.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
