### ISSUE TITLE
Masonry-layout typings not working

### ISSUE THREAD

**Issue by EnzoEghermanne** [DefinitelyTyped/DefinitelyTyped#13157]
I tried using the latest `masonry-layout/index.d.ts` file in this repo and had problems.

I installed both `masonry` and `@types/masonry` through npm.

I imported Masonry as follows:
`import * as Masonry from "masonry-layout";`

In my `tsconfig.json` i have the following rules set:

```
...
"moduleResolution": "node",
"typeRoots": [
      "../node_modules/@types"
    ]
...
```

No matter what I try, I keep getting the error: 

**File 'project_name/node_modules/@types/masonry-layout/index.d.ts' is not a module.**

Is there anyone that has an idea what I'm doing wrong here, or if there is anything wrong with the masonry-layout typings itself?

**Comment by FabianMeul** [comment]
The problem seems to be fixed when you add the following to the masonry-layout/index.d.ts file:

`export = Masonry;
export as namespace Masonry;`
