### ISSUE TITLE
JSZipGeneratorOptions missing compressionOptions in Iterface

### ISSUE THREAD

**Issue by jeremiahgibson91** [DefinitelyTyped/DefinitelyTyped#13167]
- [x ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
Error: 
Argument of type '{ type: string; compression: string; compressionOptions: { level: number; }; }' is not assignable to parameter of type 'JSZipGeneratorOptions'. Object literal may only specify known properties, and 'compressionOptions' does not exist in type 'JSZipGeneratorOptions'
My Solution:
JSZipGeneratorOptions missing compressionOptions?: Object;

**Comment by vvakame** [comment]
please send a pull request. I'll review it.
