### ISSUE TITLE
Filter error

### ISSUE THREAD

**Issue by johneybaraba** [DefinitelyTyped/DefinitelyTyped#1318]
Hi,

after import of d3.d.ts, I get error in that file: 'Incompatible override for member from array'. Is there some kind of quick fix?

Thank you,
Nikola

**Comment by tomwanzek** [comment]
As part of some legacy D3v3 issue clean-up, can this issue be please closed?

D3v4 has been released and supported with actively maintained definitions for several months now, so it would be great to have only current issues open for clarity.

Thanks in advance!

cc @gustavderdrache @andy-ms
