### ISSUE TITLE
npm run new-package

### ISSUE THREAD

**Issue by arolson101** [DefinitelyTyped/DefinitelyTyped#13197]
To contribute new definitions, README.md references running ```npm run new-package -- new-package-name``` but that script does not appear to be in package.json

**Comment by mhegazy** [comment]
it is in the types-2.0 branch, see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e49235e9343db1431bcd15f237be46ab68e98e60/package.json#L19

new packages should be submitted to types-2.0 anyways.

it should be merged in master in the next week or so.

**Comment by andy-ms** [comment]
It's in `master` now.
