### ISSUE TITLE
cropperjs/cropperjs.d.ts is missing `ready` option

### ISSUE THREAD

**Issue by timdoes** [DefinitelyTyped/DefinitelyTyped#13207]
- [x] I tried using the latest `cropperjs/cropperjs.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `cropperjs/cropperjs.d.ts`.
  - The authors of that type definition are cc/ @....

Please see https://github.com/fengyuanchen/cropperjs#ready

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by timdoes** [comment]
Fixed by #14127
