### ISSUE TITLE
Knockout Mapping Types

### ISSUE THREAD

**Issue by aersamkull** [DefinitelyTyped/DefinitelyTyped#13218]
Hi guys
In the types of knockout.mapping/knockout.mapping.d.ts, 
ko.mapping.fromJS (without options) can now be typed (as of TS 2.1):
```
    fromJS<T>(jsObject: T): {
        [P in keyof T]: KnockoutObservable<T[P]>;
    };
```
What do you think  @vvakame ? I could do a PR

**Comment by vvakame** [comment]
If my understanding is correct, the master branch is still `~2.0.0`...

**Comment by ltlombardi** [comment]
I believe this is already implemented. Current implementation shown bellow.
`fromJS<T>(jsObject: T): KnockoutObservableType<T>;`

```
type KnockoutObservableType<T> = {	
        [P in keyof T]: KnockoutObservable<KnockoutObservableType<T[P]>>|T[P];	
};
```

@aersamkull @vvakame  If possible, please close this issue.

**Comment by aersamkull** [comment]
I agree, this is done already.
