### ISSUE TITLE
Create types-2.1 branch so that PRs can be processed

### ISSUE THREAD

**Issue by ericanderson** [DefinitelyTyped/DefinitelyTyped#13228]
Somewhat in line with https://github.com/Microsoft/types-publisher/issues/214, but mostly to just let new PRs with 2.1 features get merged into one place, I propose a types-2.1 branch. This would let the community update the typings for the 2.1 features now and on Jan 7, when MS wants to start supporting 2.1 features on @types, the types-2.1 branch can either be merged into types-2.0 or one of the other proposals can come into effect.

**Comment by andy-ms** [comment]
We're working on a solution that won't require a separate branch. https://github.com/Microsoft/types-publisher/issues/214#issuecomment-266126733
