### ISSUE TITLE
@types/markitup latest version is 0.0.0

### ISSUE THREAD

**Issue by stonio** [DefinitelyTyped/DefinitelyTyped#13222]
Page https://www.npmjs.com/package/@types/markitup about package `@types/markitup` says that latest version is **0.0.0** . I was expected latest version to be like **1.0.x** .

**Comment by andy-ms** [comment]
Should be fixed by Microsoft/types-publisher#209, but it needs an update to trigger the new publish. This would be a good time to lint the package. :wink:
