### ISSUE TITLE
Transition from `types-2.0` to `master`

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#13233]
Next week we plan to begin publishing from `master` and ditch the `types-2.0` branch. So we will do:

- [x] Close all `master` PRs. ([remaining](https://github.com/DefinitelyTyped/DefinitelyTyped/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20base%3Amaster))
- [x] Shut down `types-publisher` temporarily.
- [x] Do a final merge from `master` to `types-2.0`.
- [x] Merge from `types-2.0` to `master`.
- [x] Turn `types-publisher` back on, this time publishing from `master`.

#### Should I start submitting new pull requests to `master`?

Not yet. We're clearing out pull requests for `master`.

#### Can I still submit pull requests to `types-2.0`?

Yes. After we switch to using `master`, we'll do regular merges from `types-2.0` to `master`.
But, once the merge has happened (you'll know because this issue is closed), you should prefer to make new pull requests to `master`.

**Comment by ericanderson** [comment]
@andy-ms , in light of https://github.com/Microsoft/types-publisher/issues/214#issuecomment-266056954, do you think we could discuss having types-publisher publish from "stable" and allowing changes for things like Typescript 2.1 go to master?

**Comment by andy-ms** [comment]
See the next comment (https://github.com/Microsoft/types-publisher/issues/214#issuecomment-266126733); we'd like to have just one branch.

**Comment by mhegazy** [comment]
//CC @blakeembrey, @alexeagle, @vvakame, @johnnyreilly, @staxmanade,@Diullei, @RyanCavanaugh and @DanielRosenwasser

**Comment by johnnyreilly** [comment]
Thanks for the heads up @mhegazy

**Comment by andy-ms** [comment]
It's all done. We will accept (and prefer) pull requests to `master` now.

**Comment by Mukesh1303** [comment]
have the changes for the adding autoHide and endDate to Jqueryui/index.d.ts been committed and merged with Master ?

**Comment by DanielRosenwasser** [comment]
@Mukesh1303 [yes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/38a8e0b03c802c06a9c697538fc3e2f0a1efa0a2/jqueryui/index.d.ts).

**Comment by tkrotoff** [comment]
Why not delete the `types-2.0` branch? (and some other old branches)

**Comment by andy-ms** [comment]
We have to clear out all the PRs still targeting it first.

**Comment by andy-ms** [comment]
Deleted the `types-2.0` branch.

**Comment by G-Rath** [comment]
@andy-ms [`@types/callsite`](https://www.npmjs.com/package/@types/callsite) is still pointing to `types-2.0` in it's package description.

I assume just triggering a new publish would resolve that? Can that be done w/o making an actual change to the package?
