### ISSUE TITLE
jQuery 3 TypeScript definitions

### ISSUE THREAD

**Issue by neooleg** [DefinitelyTyped/DefinitelyTyped#13258]
Hi all,

*jquery/jquery.d.ts* in the first line tells that support only 1.10.x / 2.0.x jQuery?
```
// Type definitions for jQuery 1.10.x / 2.0.x
```
Does it supports **jQuery 3.0**? If yes, let's update it.

**Comment by vvakame** [comment]
cc/ @johnnyreilly

**Comment by johnnyreilly** [comment]
There's a lot of crossover between 1.x/2.x and 3. Mostly the API is the same. However no work (as far as I'm aware) has been done to actively support 3.x.

**Comment by JohnnyWalkerDesign** [comment]
Is there any change on this? jQuery 1 and 2 are really legacy versions now. Thanks.

**Comment by Ballpin** [comment]
I found the latest version here https://www.nuget.org/packages/jquery.TypeScript.DefinitelyTyped/

From DT, how come is not included in this git repo, Is the community trying to enforce us to use MS Package Manager now? -_-

**Comment by johnnyreilly** [comment]
If someone wants to submit a PR for jquery 3 we'll happily take it
