### ISSUE TITLE
Travis CI uses unstable version of TypeScript (@next)

### ISSUE THREAD

**Issue by tkrotoff** [DefinitelyTyped/DefinitelyTyped#13263]
types-2.0 branch [package.json](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/package.json) specifies:
```JSON
"devDependencies": {
  "types-publisher": "Microsoft/types-publisher#production"
}
```

Microsoft/types-publisher#production [package.json](https://github.com/Microsoft/types-publisher/blob/production/package.json#L24) specifies:
```JavaScript
"dependencies": {
  ...
  "tslint": "next",
  "typescript": "next"
  ...
}
```

Thus Travis CI runs [typescript@2.2.0-dev.20161211](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/jobs/183073979#L777)

And of course it breaks contributions, example: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12808#issuecomment-266312946

**Using unstable version of TypeScript??? WTF**

**Comment by andy-ms** [comment]
We've fixed the version now (Microsoft/types-publisher#213). Better TypeScript versioning will be coming soon (Microsoft/types-publisher#214).
