### ISSUE TITLE
d3 ScaleLinear not assignable to AxisScale with --strictNullChecks

### ISSUE THREAD

**Issue by masonk** [DefinitelyTyped/DefinitelyTyped#13264]
- [x] I tried using the latest `d3/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @tomwanzek, @gustavderdrache, @borisyankov 

With d3@4.4.0, on tsc  2.1.4, with --strictNullChecks this doesn't typecheck:

```typescript
        let x = d3.scaleLinear()
            .domain([this.props.xmin, this.props.xmax])
            .range([0, this.width]);
    
        let x_axis = d3.axisBottom(x)
            .ticks(Math.floor(this.width/30), "s");

```

with error

```
[ts] Argument of type 'ScaleLinear<number, number>' is not assignable to parameter of type 'AxisScale<number | { valueOf(): number; }>'.
       Types of property 'copy' are incompatible.
         Type '() => ScaleLinear<number, number>' is not assignable to type '() => AxisScale<number | { valueOf(): number; }>'.
           Type 'ScaleLinear<number, number>' is not assignable to type 'AxisScale<number | { valueOf(): number; }>'.
let x: ScaleLinear<number, number>
```

It's fine at runtime.

Take off --strictNullChecks and it typechecks.

**Comment by masonk** [comment]
Issue seems to be that ```typescript
    ticks(count?: number): number[];
```
is not assignable to

```typescript
    ticks?(count: number | AxisTimeInterval): Array<number> | Array<Date>;
```
which actually I don't think it should be, even without strictNullChecks. You can't pass an AxisTimeInterval to a an axis that is scaled with a ScaleLinear. Instead, we need to infer the type of the Ticks function based on the type of the scale that was passed.

PR inc

**Comment by tomwanzek** [comment]
@masonk **d3-axis** is not yet validated to `strictNullChecks`.  It is, however, next on my to-do-list (the full current status of modules validated for `strictNullChecks` can be found under this tracking issue #11365.) I am already aware that the interface for `AxisScale` will need some tweaking in the process. Most likely this will involve redefining along the lines of  `export type AxisScale = AxisNumericScale | AxisDateScale`, with two new interfaces that reflect the minimal necessary contracts for number-based scales vs date-based scales respectively. While I have not tested it out, it should address the issue currently experienced with the overloaded signatures. Will get to it asap.

cc @gustavderdrache

**Comment by awormasi** [comment]
Is the following related?

Unless I cast axisRight(scaleLinear()).scale() to <any>, I get "Property 'ticks' does not exist on type Axis<number | { valueOf(): number }>". However, it returns <number[]> as expected at run time.

`console.log(axisRight(scaleLinear()).scale().ticks(5)); // [0, 0.2, 0.4, 0.6, 0.8, 1]`
