### ISSUE TITLE
Type `Axis` in `d3-axis` should expose index parameter in `Axis.tickFormat()`

### ISSUE THREAD

**Issue by gustavderdrache** [DefinitelyTyped/DefinitelyTyped#13274]
- [x] I tried using the latest `d3-axis/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `d3-axis/index.d.ts`.
  - The authors of that type definition are cc/ @tomwanzek 

The `tickFormat()` method of D3 axis components is [passed straight to `Selection.text`](https://github.com/d3/d3-axis/blob/master/src/axis.js#L106-L108), which means that it would be useful to expose this in the type definitions. I've written a [codepen](https://codepen.io/gustavderdrache/pen/ZBMrzm) demonstrating the behavior.

This supports a use case I've found in my own work with ordinal scales: we use scaleBand or scalePoint with a numeric domain, but our axes need string labels.

If I have time, I'll try to contribute a fix for this.

**Comment by tomwanzek** [comment]
@gustavderdrache we can tie this review/possible change into finalizing **d3-axis** for `strictNullChecks`, it was next on my hit list anyway...

**Comment by gustavderdrache** [comment]
Absolutely! I'll raise that there's an issue with the latest `tsc` compiler and the definitions. This line got flagged as an error for me in the tests, which is what kept me from submitting a PR right away:

```ts
let rightAxis: d3Axis.Axis<Date> = d3Axis.axisRight(scaleTime());
```

**Comment by tomwanzek** [comment]
Which TS version did you compile with?

**Comment by gustavderdrache** [comment]
2.2.0-dev.20161212.

**Comment by tomwanzek** [comment]
Alright, so we are on the same version. Will need to experiment around a little. It seems there were some changes to the type inference...
