### ISSUE TITLE
Augmenting react-router typings with a 3rd party library (react-router-relay)

### ISSUE THREAD

**Issue by peeter-tomberg** [DefinitelyTyped/DefinitelyTyped#13291]
- [x] I tried using the latest `react-router/react-router-0.13.3.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I want to talk about `react-router/react-router-0.13.3.d.ts`.
  - The authors of that type definition are cc/ @sergey-buturlakin, @mrk21, @vasek17, @ngbrown, @awendland, @KostyaEsmukov 

Hello! 

I'm having trouble augmenting the react-router typings. I've asked this question on StackOverflow ( link here: 
http://stackoverflow.com/questions/41103720/augment-react-router-module-with-react-router-relay-typings ), but have had no luck. What I've gathered from various sources, it might be a problem with how the typings are done for react router. As I'm fairly new to typescript, any help is greatly appreciated.

**Comment by peeter-tomberg** [comment]
Added a bounty to my stackoverflow question if that sparks any interest.

**Comment by andy-ms** [comment]
Unfortunately it doesn't look like TS will do a merge of `export { Router }` in `index.d.ts` with an augmentation of `"react-router"`. But you can modify the original in `react-router/lib/Router.d.ts` instead.

But there's another problem: the namespace is exported with `export default Router`. I don't think there's any way to augment a namespace exposed as a default export.

One option is to change `Router.d.ts` to use a regular export instead:

```ts
...
// react-router/lib/Router.d.ts
export const Router: Router;
export interface Router ... { ... }
export namespace Router { ... }
```

And then augment it with:

```ts
declare module 'react-router/lib/Router' {
    export namespace Router {
        export interface RouterProps {
            environment?: any
        }
    }
}
```

CC @RyanCavanaugh

**Comment by fameoflight** [comment]
@peeter-tomberg  did you ever find a good solution?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
