### ISSUE TITLE
This is a stub types definition for Linq.JS

### ISSUE THREAD

**Issue by sant123** [DefinitelyTyped/DefinitelyTyped#13324]
- [x] I tried using the latest `linq/linq.js.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `linq/linq.js.d.ts`.
  - The authors of that type definition are @marcinnajder

After installing the package [@types/linq](https://www.npmjs.com/package/@types/linq) it says Linq.JS provides its own type definitions. But after looking the library it does not have the type definitions. 

![image](https://cloud.githubusercontent.com/assets/7959437/21160805/2c6d8c72-c154-11e6-82c9-d70ea3e6dffc.png)

**Comment by andy-ms** [comment]
The typings are available on the [repository](http://linqjs.codeplex.com/SourceControl/latest#typescript/linq.js.d.t) but aren't properly bundled. Could you try to contact the author?

**Comment by sant123** [comment]
I'm waiting for an answer ☺ thank you!

**Comment by sant123** [comment]
I'm waiting for an answer ☺ thank you!

**Comment by aluanhaddad** [comment]
The CodePlex project has not been updated since 2012. The @types package says they are for that repo but have the same package name as the more recently maintained, but seemingly separate https://github.com/mihaifm/linq

**Comment by sant123** [comment]
The typings are now available in the linq repository.
