### ISSUE TITLE
X Module '"@types/X/Y/index"' resolves to a non-module entity and cannot be imported using this construct.

### ISSUE THREAD

**Issue by clemgrim** [DefinitelyTyped/DefinitelyTyped#13337]
- [x] I tried using the latest `lodash/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (2.1.0)
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/)

Hello,

I have this error with some modules, here's my code:

```ts
import * as debounce from 'lodash/debounce';
```

and I get this error

> Module 'path/node_modules/@types/lodash/debounce/index"' resolves to a non-module entity and cannot be imported using this construct.

I can't find why this doesnt work. It worked fine with typings, and now I have this error after migrating to `npm @types`

**Comment by nopantsmonkey** [comment]
for me changing lodash typing "@type/lodash" to 4.14.30 fix this

**Comment by clemgrim** [comment]
I have installed:

- @types/lodash@4.14.43
- typescript@2.1.4

**Comment by andy-ms** [comment]
`lodash/debounce` resolves to a function (a "non-module entity"), but you're trying to import it as a namespace. Use `import debounce = require("lodash/debounce")` instead.
https://stackoverflow.com/questions/39415661/why-cant-i-import-a-class-or-function-with-import-as-x-from-y

**Comment by rosskevin** [comment]
Hey @andy-ms - you mentioned here https://github.com/babel/babel/issues/7062#issuecomment-352793728 not to use `import = require` because the source is a mix of js/ts and is being processed by Babel 7.  What other options are there now that we are trying to play nicely with babel?

**Comment by andy-ms** [comment]
You could use `--allowSyntheticDefaultImports` and use a default-import syntax -- babel should have helpers that make that work at runtime.

**Comment by rosskevin** [comment]
I am using `allowSyntheticDefaultImports` with

```js
import * as debounce from 'lodash/debounce'
```

and it yields:

```
src/Tooltip/Tooltip.tsx(10,27): error TS2497: Module '"/Users/kross/projects/material-ui/node_modules/@types/lodash/debounce"' resolves to a non-module entity and cannot be imported using this construct.
```

**Comment by rosskevin** [comment]
I should mention that `ts-node` is running the tests with mocha....so perhaps the diff is there.

**Comment by andy-ms** [comment]
That's not a default import, it's a namespace import -- the default import syntax is `import debounce from 'lodash/debounce'`.

**Comment by rosskevin** [comment]
Right, which fails when running tests with ts-node but succeeds with `tsc`.

**Comment by rosskevin** [comment]
At runtime with ts-node and `import debounce from 'lodash/debounce'`, you get
```js
TypeError: debounce_1.default is not a function
```

**Comment by rosskevin** [comment]
Feels like a giant catch-22 - chasing my tail.

**Comment by andy-ms** [comment]
`--allowSyntheticDefaultImports` doesn't make the default imports work, it just makes the compiler stop complaining -- `ts-node` uses typescript's own transpiler instead of babel. Currently TypeScript doesn't have any runtime helpers to make default imports work but @DanielRosenwasser was working on that.
So the problem is that you're compiling the code with two different tools and they each need different import styles...
One admittedly annoying solution would be to make an untyped `.js` file re-exporting all of your external dependencies as named imports, and a `.d.ts` for it to make TypeScript happy.

**Comment by rosskevin** [comment]
Thanks @andy-ms - added this as a workaround for the moment in `debounce.js`

```js
// workaround
// @see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/13337#issuecomment-352909795
import * as debounce from 'lodash/debounce';

export default debounce;
```
