### ISSUE TITLE
d3 Typings generic function overloading problem (category10 function)

### ISSUE THREAD

**Issue by TitusJonas** [DefinitelyTyped/DefinitelyTyped#13334]
- [x] I tried using the latest `d3/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - The authors of that type definition are cc/ @tomwanzek 

I'm using the d3 Typings and want to create a colors Ordinal with a number Domain.

`        var colors = d3.scale.category10<number>().domain([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);`

The Typings package defines the category10 Functions like that:

```
    export function category10(): Ordinal<string, string>;
    export function category10<Domain extends { toString(): string }>(): Ordinal<Domain, string>;
```

But somehow my function call returns an Ordinal<string, string> and I cant set the domain with an Array of Numbers and get an error in Webstorm.

If I comment out the non generic Function like this:

```
    //export function category10(): Ordinal<string, string>;
    export function category10<Domain extends { toString(): string }>(): Ordinal<Domain, string>;
```

Everything works as expected and I can use numbers for my domain.

Is this a Bug with my code, the d3 library or even the TypeScript compiler?

**Comment by tomwanzek** [comment]
Are you attempting to use D3 version 3.x or version 4? From the looks of it, you are referencing D3 v3.x.

**Comment by tomwanzek** [comment]
With the D3 version 4 definitions, it should be as straight forward as:

```ts
import { scaleOrdinal, schemeCategory10 } from 'd3-scale';

const colorScale = scaleOrdinal<number, string>(schemeCategory10).domain([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
```

Assuming you are simply using `d3-scale` as a standalone module installed from `npm` with definitions installed by `npm install --save-dev @types/d3-scale`

The first generic corresponds to the data type of the scale domain and the second to the domain of the output range.

Your imports may obviously change, if you use a bundle of d3 modules, including `d3-scale`.

**Comment by tomwanzek** [comment]
@TitusJonas Can this be closed?

**Comment by TitusJonas** [comment]
Yes this can be closed, the issue was the wrong d3 version.
