### ISSUE TITLE
Create a d.ts file to UnityLoader.js (Unity3D)

### ISSUE THREAD

**Issue by AlexandreHagen** [DefinitelyTyped/DefinitelyTyped#13340]
Hi ! 
I have to import UnityLoader.js in Angular using TypeScript. However, that lib don't have ts declaration and need configuration variable (array) to work (See below) .

[Link to UnityLoader.js ](https://github.com/AlexandreHagen/UnityWebGL/blob/master/Development/UnityLoader.js) 

Default implementation: 
```html
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Unity WebGL Player | Test Unity</title>
    <style>
    /* a style sheet needs to be present for cursor hiding and custom cursors to work. */
    </style>
  </head>
  <body>
    <canvas class="emscripten" id="canvas" oncontextmenu="event.preventDefault()" height="600px" width="960px"></canvas>
    <script type='text/javascript'>
/* Configuration variable here !! */
  var Module = {
    TOTAL_MEMORY: 268435456,
    errorhandler: null,			// arguments: err, url, line. This function must return 'true' if the error is handled, otherwise 'false'
    compatibilitycheck: null,
    dataUrl: "Development/ExportMiniDev.data",
    codeUrl: "Development/ExportMiniDev.js",
    memUrl: "Development/ExportMiniDev.mem",
    
  };
</script>
/* Library call here !! */
<script src="Development/UnityLoader.js"></script>
  </body>
</html>
```

I have read all [docs](http://www.typescriptlang.org/docs/tutorial.html) and I followed [this](http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) to create a declaration file. 

Here my declaration file (index.d.ts):
```ts
// Type definitions for UnityLoader 5.4.3.f1
// Project: UnityLoader
// Definitions by: Alexandre Hagen <https://github.com/AlexandreHagen>

declare namespace UnityLoader {

    interface Module {
        TOTAL_MEMORY: number,
        errorhandler?: boolean,
        compatibilitycheck?: boolean,
        dataUrl: string,
        codeUrl: string,
        memUrl: string
    }

}
export {};
```

My Folder Structure in node_modules : 
```
    .
    ├── ...
    ├── unity-loader                  
    │   ├── index.d.ts    # Ts declaration file
    │   ├── index.js    # It is a remame of UnityLoader.js
    │   └── package.js    # Package to npm
    └── ...
```
But I still don't understand one thing. How can have links to my declaration a lib that is not in npm package but just a .js? Indeed docs seem about npm packages only.

Currently ```import unityLoader = require("unity-loader");``` is working but no import of UnityLoader.js... So I can't use it.

So what can we do to use a simple global library in Typescript? 
That issue is very important to me I hope you can help!

Ps: I am using Webpack to build my app.

**Comment by superstarmcawesome** [comment]
Hey there.. maybe something you are looking for?
https://stackoverflow.com/questions/43919161/importing-a-unity-webgl-project-into-an-angular2-component/48368812#48368812

Did you have any success so far?  I'm still trying to figure out how to send messages to unity from angular....

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
