### ISSUE TITLE
mongoose.d.ts support of fields with same name as SchemaOptions

### ISSUE THREAD

**Issue by realityfilter** [DefinitelyTyped/DefinitelyTyped#13356]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I want to talk about `mongoose/mongoose.d.ts`.
  - The authors of that type definition are cc/  @simonxca 

I have a schema like this one:
```js
const article = new Schema({
    paragraph: {
        text: String
    }
});
```

With the latest changes in the type definitions the compiler complains about incompatible types for property `text`. It expects it to be a boolean.

I could fix it with rewriting the definition:

```js
const article = new Schema({
    paragraph: {
        type: {
            text: String
        }
    }
});
```

I think the type definition for SchemaDefinition is not complete. It should only apply to schema definitions having a `type` property and should include the variants for simple types (String, Boolean, Schema.Types...) and nested types (user defined inline schema not having a type property).

**Comment by simonxca** [comment]
@realityfilter Good catch, I think I missed this. You can try this one here:
https://raw.githubusercontent.com/simonxca/DefinitelyTyped/patch-mongoose/mongoose/index.d.ts

I just added the `Object` type as a fallback, which should support `String`, `Boolean`, etc. as well as `Schema.Types.String`, etc.

Hopefully it didn't break anything else.
