### ISSUE TITLE
some resources (jsonwebtoken.d.ts, lodash.d.ts and toastr.d.ts) are missing?

### ISSUE THREAD

**Issue by appollo13** [DefinitelyTyped/DefinitelyTyped#13354]
somewhere between 12.12.2016 and 14.12.2016 some resources:
- "jsonwebtoken": "github:DefinitelyTyped/DefinitelyTyped/jsonwebtoken/jsonwebtoken.d.ts"
- "lodash": "github:DefinitelyTyped/DefinitelyTyped/lodash/lodash.d.ts"
- "toastr": "github:DefinitelyTyped/DefinitelyTyped/toastr/toastr.d.ts"

are gone missing. This is causing my build to fail:
"
typings ERR! message Unable to read typings for "jsonwebtoken". You should check the entry paths in "jsonwebtoken.d.ts" are up to date
typings ERR! caused by https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/jsonwebtoken/jsonwebtoken.d.ts responded with 404, expected it to equal 200
"

what can I do to get it running again?

**Comment by andy-ms** [comment]
@blakeembrey

We changed the format of the `master` branch. It looks like you're using `typings`; I believe this has an option to download a specific commit. Hopefully you can find an older commit hash that works for you.

However, the old style of definitions is deprecated, so you might want to use [npm and `@types`](http://www.typescriptlang.org/docs/handbook/declaration-files/consumption.html) instead!

**Comment by blakeembrey** [comment]
Typings would have continued to work if they install from Typings or specified a commit. Typings has **always** warned if someone is installing from `master`, which it would have been doing here and people using this notation would have had to hard-code it themselves. The solutions here are:

1. install using typings - `typings install dt~jsonwebtoken`
2. install by commit hash (add `#commitish` to the end of entry in `typings.json`)

**Comment by appollo13** [comment]
the last available commit for these 3 files (and I guess all files that where removed with #13280) is #6b3bc735ad028ca115c06721fb1c71ffc0e7a546

10x for the support
