### ISSUE TITLE
Okay to close Pull requests that have been reviewed and have an action pending

### ISSUE THREAD

**Issue by basarat** [DefinitelyTyped/DefinitelyTyped#1337]
@Diullei @borisyankov @Bartvds 
Github does not notify us on new commits to an already open pull request. This is a sane decision as the author of the PR might need multiple commits to achieve a target. 

So some pull requests go into the back log when people add commits that fixes pending issues e.g. : https://github.com/borisyankov/DefinitelyTyped/pull/1317 and don't add a comment to notify us. 

This is just my justification for closing a PR, when a PR has been reviewed and awaiting action (e.g. slight modification to definition / some test needs to be fixed etc.) leaving a comment along the lines of : 

> Please reopen PR to notify us once done.

e.g. : https://github.com/borisyankov/DefinitelyTyped/pull/1331

This will help us merge/close PRs in quicker iterations

**Comment by jakebailey** [comment]
This all is handled by the bot.
