### ISSUE TITLE
Some types missing in react-redux-toastr

### ISSUE THREAD

**Issue by wangel13** [DefinitelyTyped/DefinitelyTyped#13390]
- [x] I tried using the latest `react-redux-toastr/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `react-redux-toastr/index.d.ts`.
  - The authors of that type definition are cc/ @Smiche

According to [react-redux-toastr](https://github.com/diegoddox/react-redux-toastr) there are possibility to add react components as toast icon: `icon: (<myCustomIconOrAvatar />)`

```
const toastrOptions = {
  timeOut: 3000, // by setting to 0 it will prevent the auto close
  icon: (<myCustomIconOrAvatar />), // You can add any component you want but note the the with and height are 70px ;)
  onShowComplete: () => console.log('SHOW: animation is done'),
  onHideComplete: () => console.log('HIDE: animation is done'),
  showCloseButton: false, // true by default
  component: ( // this option will give you a func 'remove' as props
    <MyCustomComponent myProp="myValue">
      <span>Hello, World!</span>
    </MyCustomComponent>
  )
}
```

But in type definition type for `icon` is `string`.

Also some options, like `preventDuplicates`, `progressBar`, `transitionIn`, `transitionOut` etc, is not typed. [Example](https://github.com/diegoddox/react-redux-toastr#4-add-the-react-redux-toastr-react-component-to-the-root-of-your-app):

```
    <ReduxToastr
      timeOut={4000}
      newestOnTop={false}
      preventDuplicates={true}
      position="top-left"
      transitionIn="fadeIn"
      transitionOut="fadeOut"
      progressBar/>
```

**Comment by Smiche** [comment]
I can check it out on the weekends, but feel free to fix it if you're in a hurry :p

**Comment by WaNgeL-SaTaR** [comment]
Ok. Feel free, i'm not hurry.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
