### ISSUE TITLE
THREE.js typings issue

### ISSUE THREAD

**Issue by macpooh** [DefinitelyTyped/DefinitelyTyped#13418]
I tried using the latest `three/index.d.ts` file in this repo and had problems.
I've seen lots off errors in console after setting up custom properties for lights. Problem was in type of camera to use. Shadows using OrthographicCamera instead raw Camera, so I've changed type a bit.
export class LightShadow {
        constructor(camera: Camera);
        //camera: Camera;
        camera: OrthographicCamera;
        bias: number;
        ....
    }

**Comment by andy-ms** [comment]
Should the constructor also take an `OrthographicCamera`?

**Comment by macpooh** [comment]
yes, please)

**Comment by macpooh** [comment]
also it might be PerspectiveCamera as well.

**Comment by andy-ms** [comment]
So, you want to be able to put in an `OrthographicCamera` and get back an `OrthographicCamera` or put in a `PerspectiveCamera` and get back a `PerspectiveCamera`.
Might be a case for a generic type `LightShadow<T extends Camera>`, or maybe this is a genuine case for casts.
CC'ing authors @gyohk @florentpoujol @SereznoKot

**Comment by macpooh** [comment]
LightShadow just may accept different types of camera, if I understand you right.

**Comment by vcasagrande** [comment]
I just installed the THREE.js (r86) and the @types/three and noticed that some declarations aren't implemented yet, maybe this list can be useful:

```
LineLoop, RectAreaLight, ArrayCamera, Cylindrical, RectAreaLightHelper, PolarGridHelper, PolyhedronBufferGeometry, ParametricBufferGeometry, TetrahedronBufferGeometry, TextBufferGeometry, OctahedronBufferGeometry, IcosahedronBufferGeometry, DodecahedronBufferGeometry, ShapeBufferGeometry, ExtrudeBufferGeometry, MeshToonMaterial, ClosedSplineCurve3, SplineCurve3, Spline, XHRLoader
```

**Comment by andy-ms** [comment]
@vcasagrande You could make pull requests for those.

**Comment by vcasagrande** [comment]
@andy-ms Ok! I've just forked the repository, will add `BufferAttribute.setArray` and `Math.lerp` too.

**Comment by Sheldan** [comment]
Any update on this issue? The PR got removed as stalled and I just ran into the issue with LineLoop, which was added last year and is still missing from the definition.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
