### ISSUE TITLE
Start a repo of Typescript ports of core example apps from react, redux etc eco system 

### ISSUE THREAD

**Issue by joost-de-vries** [DefinitelyTyped/DefinitelyTyped#13433]
As far as I know there is no shared 'canonical' repo of Typescript versions of the core example apps of react, redux etc.
I think starting one would help people a lot with getting started. And would work as a test case for the type definitions themselves.
And perhaps most importantly it could work as a focal point for people who do react, redux etc in Typescript. To share knowledge about how to use new Typescript features like tagged unions, spread operator and mapped types when coding react/redux etc.

I myself have [ported](https://github.com/joost-de-vries/redux/) the redux `todos` application to Typescript 2.1.4. So I can contribute that.

So what say you? Any interest in collaborating around this?

**Comment by evmar** [comment]
This has nothing to do with DefinitelyTyped.  I think you filed this in the wrong tracker(?)

**Comment by joost-de-vries** [comment]
There is a repo like that [here](https://github.com/Microsoft/TypeScript-React-Starter)
