### ISSUE TITLE
Koa Bodyparser missing enableTypes property in definition

### ISSUE THREAD

**Issue by valVk** [DefinitelyTyped/DefinitelyTyped#13463]
- [x] I tried using the latest `@types/koa-bodyparser@3.0.21.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [x] I want to talk about `@types/koa-bodyparser@3.0.20.d.ts`.
  - The authors of that type definition are cc/ @hellopao @liushigit

From documentation https://github.com/koajs/bodyparser/tree/master

* **enableTypes**: parser will only parse when request type hits enableTypes, default is `['json', 'form']`.

**Comment by hellopao** [comment]
@valVk i've made a pr, [13482](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13482)

**Comment by valVk** [comment]
Thanks!
