### ISSUE TITLE
WebdriverIO missing browser.windowHandleMaximize() type

### ISSUE THREAD

**Issue by jineshqa** [DefinitelyTyped/DefinitelyTyped#13476]
[ webdriverio/index.d.ts] - I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
[2.2.0-dev.20161219 ] - I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
[NO ] - I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
[webdriverio/index.d.ts ] - I want to talk about `xxxx/xxxx.d.ts`.
andy-ms  - The authors of that type definition are cc/ @....

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by timbru31** [comment]
I believe this stale issue can be closed. Seems this was/is fixed since the methods are present in the current version: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webdriverio/index.d.ts#L1484-L1485

**Comment by uniqueiniquity** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32490
