### ISSUE TITLE
d.ts file for bootstrap-validator

### ISSUE THREAD

**Issue by katrina-engelbrecht** [DefinitelyTyped/DefinitelyTyped#13503]
Hi, 
I would like to have the bootstrap-validator.d.ts file to use this very useful tool.
Pls. refer to this link: https://github.com/1000hz/bootstrap-validator/issues/312

**Comment by BradyLiles** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13626

**Comment by katrina-engelbrecht** [comment]
It's great! Thanks bradyliles!
