### ISSUE TITLE
Missing process.stdout.columns in node/index.d.ts

### ISSUE THREAD

**Issue by christianrondeau** [DefinitelyTyped/DefinitelyTyped#13508]
See https://github.com/Microsoft/TypeScript/pull/4213, to follow https://nodejs.org/api/tty.html#tty_class_writestream there should be a `columns` and `rows` properties on `WritableStream` of `process.stdout` and `stderr`.

**Comment by edvail** [comment]
how to workaround while not implemented?

**Comment by christianrondeau** [comment]
I added this to the source files of my project (e.g. `node.stdout.d.ts`):

    declare namespace NodeJS {
      export interface TermWritableStream extends WritableStream  {
        columns: number;
        rows: number;
      }
    }

You then cast:

    var stdout = <TermWritableStream>(process.stdout);

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by arichiardi** [comment]
I maybe saying something really wrong here, but shouldn't this be ported also to types for `v7`?

On in `Socket`/`Stream` here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L370
