### ISSUE TITLE
@types/express-serve-static-core should not depend on @types/node

### ISSUE THREAD

**Issue by whitecolor** [DefinitelyTyped/DefinitelyTyped#13546]
I believe @types/express-serve-static-core should not depend on @types/node (currently it is in dependencies), it should be added in peerDependencies, because otherwise it may result in conflicts, with other installed version (maybe on the upper level of the project).

I don't get where the package.json can be contributed to? I see no package.json here:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/express

cc @borisyankov

**Comment by andy-ms** [comment]
The dependency is added automatically by [types-publisher](https://github.com/Microsoft/types-publisher), inferred because of the `/// <reference types="node" />` in that file.
The dependency is `"@types/node": "*"`, so it can't result in conflicts.

**Comment by whitecolor** [comment]
Well it can as it will force to install the latest version of the dependency if it is not in the project's package.json. But it can be not desirable. It is implicit installation of the dependency - which in general may lead to conflicts. The case is that:
```
/my-project
  package.json (contains for example @types/node@6.0.1)
  node_modules (node-modules contain types for node)
    @types/node
  /sub-project
  package.json (contains for `node-schedule` and `@types/node-schedule`)
  node_modules (node-modules contain types for node)
    @types/node (will instlal some latest node typings)
    @types/node-schedule
```

Though node types in `sub-project` are not really needed to work and types can be taken from higher order `my-project`'s node_modules.

I think such things should go as peerDependencies, or maybe not be not at all. This actually refers to typescript 2. What do you think?
