### ISSUE TITLE
Confusion regarding notNeededPackages.json

### ISSUE THREAD

**Issue by easyfuckingpeasy** [DefinitelyTyped/DefinitelyTyped#13556]
Concerning declaration files in packages, TypeScript HandBook says `make sure to add a reference to it in the DefinitelyTyped repo external package list. Adding this will allow search tools to know that your package provides its own declarations` ([link](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)) whilst Readme says that `if a package was never on DefinitelyTyped, it does not need to be added to notNeededPackages.json`. Is it still recommended to do so, though?

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript-Handbook/pull/467 updates the recommendation on the handbook. we will need to find a better solution for search.
