### ISSUE TITLE
[Bug][lodash] lodash types weird intellisense output

### ISSUE THREAD

**Issue by Luchillo** [DefinitelyTyped/DefinitelyTyped#13557]
- [x] I tried using the latest `lodash/lodash-3.10.d.ts` file in this repo and had problems.

This is the output of VSCode with the `@types/lodash` package:

![image](https://cloud.githubusercontent.com/assets/9698639/21484318/855756b0-cb5e-11e6-8b78-bb8e38d91ea0.png)

I expected to see at least `map` intellisense, and most likely `flatMap` and a few others.

tsconfig file:

```ts
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "noEmitHelpers": true,
    "strictNullChecks": false,
    "baseUrl": "./src",
    "paths": {},
    "lib": [
      "dom",
      "es6"
    ],
    "types": [
      "hammerjs",
      "jasmine",
      "node",
      "selenium-webdriver",
      "source-map",
      "uglify-js",
      "webpack",
      "lodash"
    ]
  },
  "exclude": [
    "node_modules",
    "dist"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}
```

**Comment by andy-ms** [comment]
Looks like a TS bug: Microsoft/TypeScript#13218

**Comment by Luchillo** [comment]
For some reason it works ok in a webpack project i have, but in a clean folder after install and typescript setup it fails as reported.
