### ISSUE TITLE
@types/jquery: Boolean value in .attr validity

### ISSUE THREAD

**Issue by uoziod** [DefinitelyTyped/DefinitelyTyped#13563]
I wondering why it isn't valid to set up boolean values for properties thru `.attr`? Real use case could be: 
`jQuery("#element[type=checkbox]").attr("checked", false);`
CC: @RyanCavanaugh

**Comment by judowalker** [comment]
You would want to use `.prop`:
```js
jQuery("#element[type=checkbox]").prop("checked", false);
```

**Comment by judowalker** [comment]
See also https://github.com/DefinitelyTyped/DefinitelyTyped/issues/4797#issuecomment-118328504
