### ISSUE TITLE
[lovefield][update] request to update typings with the ones inside package

### ISSUE THREAD

**Issue by Luchillo** [DefinitelyTyped/DefinitelyTyped#13574]
- [x] I tried using the latest `@types/lovefield` and had problems.

Basically the lovefield package has it's own type definitions now, and this package is outdated in relation to that.

I want to request an update of this repo using the lovefield own type definition file, for example, the main difference is that in this repo:

```ts
declare namespace lf { ... }
```

While in the lovefield repo the type definition starts like:

```ts
declare module lf { ... }
```

Related files lines: [DefinitelyTyped/lovefield/index.d.ts#L6](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/lovefield/index.d.ts#L6) and [lovefield/master/dist/lovefield.d.ts#L22](https://github.com/google/lovefield/blob/master/dist/lovefield.d.ts#L22)

**Comment by andy-ms** [comment]
Moving discussion to google/lovefield#188. If `lovefield` has its own types, then `@types/lovefield` should be deprecated. But they must bundle the types correctly first; see my comment there.

**Comment by Luchillo** [comment]
Agree.
