### ISSUE TITLE
Compiler error on mapbox

### ISSUE THREAD

**Issue by canda** [DefinitelyTyped/DefinitelyTyped#13591]
- [x] I tried using the latest `mapbox/index.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @anahkiasen

When compiling I have these errors
```
    ERROR in [default] node_modules/@types/mapbox/index.d.ts:42:32 
    Module 'L' has no exported member 'Map'.
    
    ERROR in [default] node_modules/@types/mapbox/index.d.ts:142:32 
    Type 'FeatureGroup' is not generic.
```

**Comment by andy-ms** [comment]
Caused a new publish of `mapbox`, so this appears fixed.
Must have been a bug in an older version of types-publisher.
