### ISSUE TITLE
rxjs typings outdated

### ISSUE THREAD

**Issue by whitecolor** [DefinitelyTyped/DefinitelyTyped#13663]
This
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/rx
is outdated.

Look:
https://github.com/Reactive-Extensions/RxJS/tree/master/ts

**Comment by mhegazy** [comment]
Feel free to send s PR to update the definitions and I will review it.

**Comment by whitecolor** [comment]
Ok, maybe prior to this rx authors will publish them.
https://github.com/Reactive-Extensions/RxJS/pull/1305

**Comment by mhegazy** [comment]
One thing to note is that the structure of these declaration files is not correct. i have a PR for this up in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13652
