### ISSUE TITLE
webvr-api: can't compile to es5

### ISSUE THREAD

**Issue by endquote** [DefinitelyTyped/DefinitelyTyped#13660]
I updated my three.js types to .81, which seems to include the webvr-api types. Cool.

However when trying to build with `tsc` I get:

```
node_modules/@types/webvr-api/index.d.ts(101,43): error TS2304: Cannot find name 'Promise'.
node_modules/@types/webvr-api/index.d.ts(106,18): error TS2304: Cannot find name 'Promise'.
node_modules/@types/webvr-api/index.d.ts(190,20): error TS2304: Cannot find name 'Promise'.
```

I found that changing `"target": "es5"` to `"target": "es6"` in `tsconfig.json` resolved the issue.

However, I was running my es5 code through UglifyJS as part of a webpack setup, and Uglify doesn't do ES6, so it explodes with a bunch of other errors.

I'm new to the whole TS world, so I'm not sure what the fix is, but maybe it's as simple as explicitly importing `Promise`?

@MiiBond, @RyanCavanaugh

**Comment by vvakame** [comment]
try with `--lib es2015`.

**Comment by endquote** [comment]
I tried something like that in researching this issue... `tsc --lib es2015` generates many errors whether the target is set to es5 or es6. `error TS2304: Cannot find name 'window'` at the top of the list. Maybe I'm doing it wrong...

**Comment by andy-ms** [comment]
@endquote [`--lib`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) takes multiple arguments. Sounds like you need "dom" too.

**Comment by endquote** [comment]
That seemed to fix it. Thanks!

tsconfig.json:

```
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "sourceMap": true,
    "lib": [
      "es2015",
      "dom"
    ]
  }
}
```
