### ISSUE TITLE
typings/lodash 4.14.43 and later. Modular import warning.

### ISSUE THREAD

**Issue by Connormiha** [DefinitelyTyped/DefinitelyTyped#13679]
I use modular lodash import, like this:

```js
import * as noop from 'lodash/noop';
import * as pick from 'lodash/pick';
```
Since @typings/lodash 4.14.43 in console i see this warnings:

`error TS2497: Module '"...@types/lodash/noop/index"' resolves to a non-module entity and cannot be imported using this construct.`

`error TS2497: Module '"...@types/lodash/pick/index"' resolves to a non-module entity and cannot be imported using this construct.`

In @typings/lodash 4.14.42 it works well(without warnings).

**Comment by vlio20** [comment]
+1

**Comment by andy-ms** [comment]
See Microsoft/TypeScript#5073 and [this question](http://stackoverflow.com/questions/39415661/why-cant-i-import-a-class-or-function-with-import-as-x-from-y#39415662).
