### ISSUE TITLE
@types/flexslider: Has errors working with Angular2 and TS

### ISSUE THREAD

**Issue by Alfred-W** [DefinitelyTyped/DefinitelyTyped#13692]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @andy-ms

Using flexslider has issues like the one below.  Anyone who has a solution? I have looked everywhere for this.

`node_modules/@types/flexslider/index.d.ts(21,2): error TS7010: 'flexAnimate', which lacks return-type annotation, implicitly
 has an 'any' return type.`

**Comment by andy-ms** [comment]
The definition currently has [`"noImplicitAny": false`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/flexslider/tsconfig.json#L5). You could help by making a pull request that turns this option on, then adding type annotations to the file to fix it.

**Comment by Alfred-W** [comment]
I have forked the repo and I want to make the changes you pointed out. Do I have to create a new branch? I am relatively new to this...

**Comment by Alfred-W** [comment]
Okay. I am having a hard time adding annotations. Most of the variables not typed are functions

**Comment by andy-ms** [comment]
Should be fixed by #13708
