### ISSUE TITLE
when no-import,  can not use bluebird class based on index.d.ts (Type definitions for bluebird 3.0.0)

### ISSUE THREAD

**Issue by vincedan** [DefinitelyTyped/DefinitelyTyped#13694]
Hi,
I met a problem in using bluebird in typescript. I wanna:
1) use bluebird in browser: 
2) don't  use requireJS.

I think the above is a in come use. after I add reference of index.d.ts, I could not find any types.Yes, right now there is no pollution.. at the same time I can't use it.
in Typescript, I don't want to "import" bluebird module, I need something  like a normal class in the same way which a lot of d.ts do. . 

I also notice it seems that basic then method does work with bluebird-2.0.d.ts+bluebird-3.4.7.js and that d.ts meets my requrirement. I can use Promise class directly without any import statement in my code.

 I am fresh for javascript&typescript. if some wrong in above,, please correct me. and thank you a lot.

**Comment by vincedan** [comment]
@andy-ms  I had checked souces code [bluebirdglobal]((https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/bluebird-global)).. I just reviewed the source code of index.d.ts...at line 37 `import * as Bluebird from "bluebird";` I think it needs module import configuration on client and I can not use module loader for some reason

**Comment by andy-ms** [comment]
When you install `@types/bluebird-global`, it should install `@types/bluebird` as a dependency. TypeScript module resolution should be able to find this dependency regardless of what kind of module resolution you're using. Are you getting compile errors? If so, what TS version are you using and can you provide sample code?

**Comment by vincedan** [comment]
thanks, @andy-ms. after your second reminding, I realized that the way I am going on is not right. I don't use npm. I use nuget....... and bluebird-2.0.d.ts does work but 3.0 not..both of them sourced from nuget... I think I should go with trend.
right now I have no question on it. but I was wondering it should be better to modify something on 3.0 (user can get the same result on it) or  abandon that package on nuget. 

thanks again.

**Comment by andy-ms** [comment]
Nuget publishing has been turned off, so you're not going to be able to make fixes to that any more.
https://github.com/DefinitelyTyped/NugetAutomation#readme

**Comment by vincedan** [comment]
It seems that I am out-dated. by the way, I found nothing about announce Date. when was it announced?

**Comment by andy-ms** [comment]
I don't know if they announced that anywhere but the readme.
