### ISSUE TITLE
pullAllWith missing in lodash

### ISSUE THREAD

**Issue by kevin-madhu** [DefinitelyTyped/DefinitelyTyped#13747]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @.... @andy-ms 

The pullAllWith function is missing from typings declarations, but it does work and shows up as a linting error.

**Comment by andy-ms** [comment]
You can help by [making a pull request](https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute) editing `lodash/index.d.ts`.
The package authors are @bczengel @chrootsu @stepancar

**Comment by aj-r** [comment]
`pullAllWith` exists now.
