### ISSUE TITLE
restrictive type definition for Promise.then 

### ISSUE THREAD

**Issue by aktraore** [DefinitelyTyped/DefinitelyTyped#13748]
- I tried using the latest `selenium-webdriver/index.d.ts` file in this repo  for my protractor project and had problems.
- The authors of that type definition are cc/ @....
- This issue is related to another typing issue I had raised on the protractor repo (https://github.com/angular/protractor/issues/3696)
The typing of the **then** method on the Promise class is too restrictive
```javascript
      then<R>(opt_callback?: (value: T) => IThenable<R> | R, opt_errback?: (error: any) => any): Promise<R>;
``` 
Using this typing, if I write a method like this, there will be a typing error saying **promise.Promise<{}>** is not assignable to **promise.Promise<void>**

```javascript
add(index?: number, locator: ElementFinder): promise.Promise<void> {
 return locator.getAttribute('max').then(
(max ) => {
 if (this.array.length < Number(max))
    //// code to add value where I don't return anything thus the void in the methode prototype
}
)
}
```

**Comment by andy-ms** [comment]
You could always use `.then<void>`. (Or `async`/`await`.)

**Comment by cnishina** [comment]
I think this is the syntax is correct as is. In the above issue:

```
return location.getAttribute('max').then(max => {
  if (this.array.length < Number(max)) {
    return 1;  // if we returned a number here, the result is Promise<number>
  }
  return 'a string';  // if we returned a string, the result is a Promise<string>
});
```

The function defined could return anything; however, in your method signature for `add` states that it is a `Promise<void>`. Either the function needs to explicitly say that it is a void function or `.then<void>` needs to be stated. 

```
return location.getAttribute('max').then((max): void => {
  if (this.array.length < Number(max)) {
  }
  // trying to return a number or string would cause a transpile error
});
```

Another way as stated by @andy-ms, is to use `.then<void>`:


```
return location.getAttribute('max').then<void>(max => {
  if (this.array.length < Number(max)) {
  }
  // trying to return a number or string would cause a transpile error
});
```

@andy-ms I think this issue should be closed.

**Comment by aktraore** [comment]
Yes you can close it, I'll just use the above recommendations.
