### ISSUE TITLE
In @types/enzyme: CommonWrapper.reduce<R>() returns R[] instead of R

### ISSUE THREAD

**Issue by hesher** [DefinitelyTyped/DefinitelyTyped#13759]
I tried using the latest `enzyme/index.d.ts` file in this repo and had problems.
  - The authors of that type definition are cc/@NoHomey

```
interface CommonWrapper<P, S> { 
/**
     * Applies the provided reducing function to every node in the wrapper to reduce to a single value. Each node
     * is passed in as a ShallowWrapper, and is processed from left to right.
     * @param fn
     * @param initialValue
     */
    reduce<R>(fn: (prevVal: R, wrapper: this, index: number) => R, initialValue?: R): R[];
}
```
Why is reduce taking `R` as a generic and returning `R[]` and not `R`? 
Reduce should return `R`.

For example, ES5 `.d.ts` has this defintion for `reduce`:
```
reduce(callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: T[]) => T, initialValue?: T): T;
```

**Comment by NoHomey** [comment]
I'm not the only author of the definitions but you are absolutely right, I've also checked the [source](https://github.com/airbnb/enzyme/blob/64ac7441d23157732d38b62a29003646cc92bcd2/src/ShallowWrapper.js#L799-L804).

**Comment by hesher** [comment]
Me too. Just wanted to get a validation. 
I'll open a PR

**Comment by hesher** [comment]
PR is here:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13763

Notice I didn't uptick the version. Wasn't sure if I should.

**Comment by hesher** [comment]
Having some environment trouble. I guess you can go with fixing it yourself or I can fix it tomorrow.

**Comment by NoHomey** [comment]
Version [2.7.0](https://github.com/airbnb/enzyme/releases) is the latest release so no version bump was  necessary. You can close this issue now :smile:
