### ISSUE TITLE
@types/numeral isn't up to date with Numeral 2.x

### ISSUE THREAD

**Issue by vhfmag** [DefinitelyTyped/DefinitelyTyped#13788]
- [x] I tried using the latest `numeral/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I want to talk about `numeral/index.d.ts`.
  - The authors of that type definition are cc/ @hersing @RyanCavanaugh 

As of the last Numeral version (2.0.4) the language method has been renamed to locale but the type definitions didn't keep up with it.

**Comment by godefroyo** [comment]
This issue seems to be resolved in PR #14120 ( @dherges & @mhegazy ).

Does anyone know if an update of the nuget package [numeraljs.TypeScript.DefinitelyTyped](https://www.nuget.org/packages/numeraljs.TypeScript.DefinitelyTyped) is planned ?
