### ISSUE TITLE
@types/node incorrect API/differs from official

### ISSUE THREAD

**Issue by hinell** [DefinitelyTyped/DefinitelyTyped#13782]
## Origin of the issue
The return types of `ReadableStream.setEncoding()` method according to
[nodejs v0.12 API](https://nodejs.org/dist/v0.12.0/docs/api/stream.html#stream_readable_setencoding_encoding) is set to `this` 
[node.js 6x API ](https://nodejs.org/dist/latest-v6.x/docs/api/stream.html#stream_readable_setencoding_encoding) is set to `this`<br> and [node/index.d.ts](https://github.com/hinell/DefinitelyTyped/blob/master/node/index.d.ts#L284) is set to`void` ?!

These are also have return type defined incorrectly:
 ```ts
readable.pause()
readable.resume()
readable.unpipe()
```
All of them expected to return `this` instead of `void/T` as defined by latest node.d.ts.

Obviously that discrepancy requires fix. Essentially there is also need to prepare a list of modules that are dependent on ReadableStream interface (inherit/extends it) to fix them up and avoid any errors like this one #13678. 

## Blank
- [X] I tried using the latest `mongodb/index.d.ts` file with [node.d.ts](https://github.com/types/env-node/tree/master/6.0) provided by [typings](https://github.com/typings/typings)  in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [  ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] I want to talk about `node/index.d.ts`
  - The authors of that type definition are 
@andy-ms
@RyanCavanaugh
@minestarks
@paulvanbrenk
@sandersn
@maghis
@zhengbli
@yuit
@zjiekai
@yortus
@xiemaisi
@rogierschouten
@rakatyal
@mhegazy
@iainmcgin
@horiuchi
@HerringtonDarkholme
@jefff
@Flarna
@icopp
@a8775

**Comment by hinell** [comment]
Well guys, I think it's better replace latest node.d.ts definition by its typings' sibling. 
What do you think? :bulb:

**Comment by mhegazy** [comment]
Feel free to send PR updating the declaration file, and we will be happy to review it and get it merged.
