### ISSUE TITLE
@types/office-js has an incorrect type definition for a function

### ISSUE THREAD

**Issue by arvind1234** [DefinitelyTyped/DefinitelyTyped#13835]
- [x] I tried using the latest `office-js/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `office-js/index.d.ts`.
  - The authors of that type definition are cc/ @OfficeDev

The type definition for the Office.context.mailbox.displayNewAppointmentForm function lists all parameters as individual arguments, whereas the [documentation](https://dev.outlook.com/reference/add-ins/Office.context.mailbox.html#displayNewAppointmentForm) has the function taking in a property bag. On testing the library is looks like the documentation way of taking in a property bag is the correct way to call the function.

Also the Office.context.mailbox.displayNewMessageForm function is missing a type definition.

**Comment by andy-ms** [comment]
Definitions are by @OfficeDev

**Comment by arvind1234** [comment]
Thanks Andy. Sorry that I tagged you, I saw that you updated the index.d.ts and thought you owned it.

**Comment by ElizabethSamuel-MSFT** [comment]
@arvind1234: Is this still an issue for you? Thanks.

**Comment by arvind1234** [comment]
@ElizabethSamuel-MSFT I am no longer working on the project that is using the office-js types. Feel free to close the issue, if you think it is fixed

**Comment by ElizabethSamuel-MSFT** [comment]
@arvind1234: Thanks for responding so quickly. I don't have permission to close this issue so can you close it? Thanks.
