### ISSUE TITLE
Installing @types/mocha for browser use also installs Node typings

### ISSUE THREAD

**Issue by fongandrew** [DefinitelyTyped/DefinitelyTyped#13837]
Using TS 2.1.4. Problem occurs after updating @types/mocha from 2.2.35 to 2.2.36. `npm install @types/mocha` also installs `@types/node`, which may result in errors if you're using Mocha in code targeting a browser environment.

Problem appears to result from the addition of `mocha-node.d.ts` (which has a `/// <reference types="node" />
` line) to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/mocha/tsconfig.json.

Unless there's a way to tell NPM to install only `mocha/index.d.ts` without also including `mocha/mocha-node.d.ts` (or to tell Typescript to ignore the node lib if I've already specified other libs in my tsconfig.json)?

**Comment by andy-ms** [comment]
What errors does it result in?

**Comment by fongandrew** [comment]
In my case, I get `Type 'Timer' is not assignable to type 'number'.`. This is because https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/index.d.ts defines the return type for `setTimeout` as `NodeJS.Timer` (whereas on the browser, it's just a number).
