### ISSUE TITLE
@types/react has v0.0.0 as latest published version

### ISSUE THREAD

**Issue by AviVahl** [DefinitelyTyped/DefinitelyTyped#13834]
Hi DT team,

We're seeing validation failures on our end, as one of our projects is exposing a certain version of `@types/react` (not 0.0.0), while `@types/react-addons-test-utils` brings its own version (0.0.0) of @types/react.

These validation errors happened post the recent changes to the **@types/react** package.

We're getting the following error (and other similar to it):
`node_modules/@types/react/index.d.ts -> 2566:12 Subsequent variable declarations must have the same type.  Variable 'svg' must be of type 'SVGProps', but here has type 'SVGProps'.`

See: https://www.npmjs.com/package/@types/react
"**0.0.0** is the latest of 41 releases"

We suspect the root cause to be the two @types/react versions in our node_modules.
Would it be possible to republish @types/react with a proper (newer) version number, which would also address our issue?

Thanks in advance,
Avi

**Comment by afc163** [comment]
+1

**Comment by bcherny** [comment]
cc @andy-ms - Is this a bug with [types-publisher](https://github.com/Microsoft/types-publisher)?

**Comment by patsissons** [comment]
did the publisher previously support versions with only a single value?

**Comment by andy-ms** [comment]
`@types/react@15.0.0` published.

**Comment by patsissons** [comment]
fantastic! super fast resolution on this!
