### ISSUE TITLE
redux-form/reduxForm.d.ts#FormProps is missing some properties

### ISSUE THREAD

**Issue by nzjoel1234** [DefinitelyTyped/DefinitelyTyped#13879]
- [x] I tried using the latest `redux-form/reduxForm.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `redux-form/reduxForm.d.ts`.
  - The authors of that type definition are cc/ @CarsonF 

As discussed here: https://github.com/erikras/redux-form/issues/1211#issuecomment-271399258:

> @CarsonF It seems you have missed a few things in the FormProps interface... I have noticed that destroyOnUnmount?: boolean and initialValues?: FormData are both missing. Does this sound correct to you or am I missing something?

Before using the typings I was able to pass these as inline props in JSX templates. I.e.:
`<MyReduxForm initialValues={props.data} />` but when I included in the typings this gave an error. If I add `initialValues?: FormData` to reduxForm.d.ts passing the initialValues works.
As mentioned as well as `initialValues` I have also noticed a similar problem with `destroyOnUnmount`

**Comment by janv** [comment]
The v6 definition also misses the ability to configure the Form via props and complains when `form` is ommited in the config parameter of the `reduxForm(config)(MyComponent)` call.

I'm gonna try and create a PR later

**Comment by GeraldIstar** [comment]
`forceUnregisterOnUnmount` flag from reduxForm config is also missing

**Comment by begincalendar** [comment]
The fact that the `form` property is mandatory (in the `Config` interface) is affecting me too.

@janv have you started a PR?
If not, I can get one going.

**Comment by janv** [comment]
Not yet.
I ran into this problem when approaching a migration from redux-form v5 to v6.
But that project has been put on hold at work and I probably won't get back to it until April

**Comment by begincalendar** [comment]
OK, no worries, I'll start one.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
