### ISSUE TITLE
code compiled with rrule/index.d.ts fails at run-time

### ISSUE THREAD

**Issue by psnider** [DefinitelyTyped/DefinitelyTyped#13885]
- [x] I tried using the latest `rrule/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `rrule/index.d.ts`.
  - The authors of that type definition are cc/ @waratuman

Although the recently updated type declarations for the [rrule package](https://www.npmjs.com/package/rrule) describe most of the shape of RRule,
and their tests pass,
the simplest examples from the compiled tests don't run!

Please advise how to fix these.

For example, this code from the [./rrule/rrule-tests.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c0a3889ed815e0cece0414ef4413038a9275a277/rrule/rrule-tests.ts#L1-L10) file:
```
import * as RRule from 'rrule';

// Create a rule:
let rule: RRule = new RRule({
    freq: RRule.WEEKLY,
    interval: 5,
    byweekday: [RRule.MO, RRule.FR],
    dtstart: new Date(2012, 1, 1, 10, 30),
    until: new Date(2012, 12, 31)
});
```

compiles in the test, producing:
```
const RRule = require('rrule');
// Create a rule:
let rule = new RRule({
    freq: RRule.WEEKLY,
    interval: 5,
    byweekday: [RRule.MO, RRule.FR],
    dtstart: new Date(2012, 1, 1, 10, 30),
    until: new Date(2012, 12, 31)
});
```

 but fails at run-time because RRule doesn't actually refer to the intended code, and this error is thrown:
```
TypeError: RRule is not a constructor
```

The problem is that the rrule package contains a class that should is imported in node by referencing the contained element RRule:
```
var RRule = require('rrule').RRule;
```
and the type declarations don't account for this.

**Comment by waratuman** [comment]
Don't know how I missed this since I use it... Working on a fix now.

**Comment by waratuman** [comment]
So this doesn't work in Node I think because it is imported a different way. When using it in the browser it is exported as a global variable: https://github.com/jkbrzt/rrule/blob/v2.1.0/lib/rrule.js#L1888-L1910. I'm trying to figure out how to support both. Any ideas?

**Comment by psnider** [comment]
I tried several things, but didn't figure out a method that I think works for both.
FWIW, this structure works for me for node.js:
```
declare namespace R {
    interface Options {}
    class Weekday {}
//  const decls ...
//  function decls ...
    class RRuleSet extends RRule {}
    export class RRule {}
}
export = R;
```

@andy-ms Might you be able to help us with this?
I noticed that you approved the PR a few months back.   
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11415
