### ISSUE TITLE
React typings - componentWillReceiveProps

### ISSUE THREAD

**Issue by n-s-russell** [DefinitelyTyped/DefinitelyTyped#13897]
- [X] I tried using the latest `react/index.d.ts` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

The authors of that type definition are:

- @RyanCavanaugh RyanCavanaugh
- @andy-ms andy-ms
- @paulvanbrenk paulvanbrenk
- @zhengbli zhengbli
- @yuit yuit
- @donaldpipowitch donaldpipowitch
- @minestarks minestarks
- @epabst epabst
- @bbenezech bbenezech
- @tkrotoff tkrotoff
- @Strate Strate
- @schickling schickling
- @robyoder robyoder
- @phiresky phiresky
- @toraora toraora
- @mhegazy mhegazy
- @mariusschulz mariusschulz
- @neelance neelance
- @mgroenhoff mgroenhoff
- @joshaber joshaber
- @Emm Emm
- @dzearing dzearing
- @mDibyo mDibyo
- @DanielRosenwasser DanielRosenwasser
- @Chudesnov Chudesnov
- @beckend beckend

If a **class which extends Component**'s props' typing is passed into its generics, the nextProps parameter of the componentWillReceiveProps method cannot be inferred.

**Comment by DanielRosenwasser** [comment]
Can you give some actual code to demonstrate the problem you're running into?

**Comment by donaldpipowitch** [comment]
```ts
import React, { Component } from 'react';

class Foo extends Component<{ test: string }, {}> {
  componentWillReceiveProps(nextProps) {}
                         // ^--- Parameter 'nextProps' implicitly has 'any' type.
}
```

```json
{
  "devDependencies": {
    "typescript": "^2.4.0"
  },
  "dependencies": {
    "@types/react": "^15.0.29"
  }
}
```

**Comment by n-s-russell** [comment]
@donaldpipowitch precisely, sorry I didn't comment earlier, I'd forgotten about this issue completely.

**Comment by lukescott** [comment]
I'm having the same issue. `nextProps` show as `any` instead of the props type. It's weird because `componentWillReceiveProps` is defined by `ComponentLifecycle` and it is attached to `Component` using an interface. I've tried doing my own local definition using `implements` and I can't get it to infer the type.

**Comment by DanielRosenwasser** [comment]
This is a limitation of TypeScript at the moment; we've had some ideas, but in the meantime, it's better to name your type and use the declaration.

**Comment by NathanRussellUK** [comment]
With functional components (in newer versions of React), I guess the problem is a compoletely different as there aren't class extension/methods!
