### ISSUE TITLE
Why Node's `http.IncomingMessage` defined as interface, not a class?

### ISSUE THREAD

**Issue by KostyaTretyak** [DefinitelyTyped/DefinitelyTyped#13909]
- [x] I tried using the latest `node/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `node/index.d.ts`.

As said documentation of Node.js, `http.IncomingMessage` [is a class](https://nodejs.org/api/http.html#http_class_http_incomingmessage), not an interface. So why in DefinitelyTyped `http.IncomingMessage` defined [as interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e2988a134ec9fa51deb43487231ac607265ba088/node/index.d.ts#L694)?

Now in my code I can not do this:

```ts
import * as http from 'http';
let Request = http.IncomingMessage;
```

TypeScript error:

> Property 'IncomingMessage' does not exist on type 'typeof "http"'.

I'm doing something wrong?

**Comment by TonyPythoneer** [comment]
This is my personal experience as the reference. Please keep an open mind.

`http.IncomingMessage` can't be used independently. It depends on ` http.Server` and `http.ClientRequest`  as document mentioned.

It's made for parsing detail when http server receives the request. It has passed `http.IncomingMessage`  class and create an object. Finally, it's the `res` in callback argument.

**Comment by KostyaEsmukov** [comment]
@TonyPythoneer I believe you have mentioned me by mistake.

**Comment by TonyPythoneer** [comment]
@KostyaEsmukov Sorry, I should mention @KostyaTretyak.

**Comment by KostyaTretyak** [comment]
@TonyPythoneer, thank you for the answer.

Now I try to do refactoring code for restify to TypeScript format. I see [in code this](https://github.com/restify/node-restify/blob/024cf58dbf1537dbc69c58a7ef2c7a38165b0214/lib/request.js#L19):

```js
var Request = http.IncomingMessage;

// ...

Request.prototype.absoluteUri = function absoluteUri(path) {
  // ... code
};

// ... more code
```

And than, in [`Server` class just](https://github.com/restify/node-restify/blob/024cf58dbf1537dbc69c58a7ef2c7a38165b0214/lib/server.js#L27):

```js
require('./request');
```

As far as I understand, so there extends class `http.IncomingMessage` and its work. Is it not right to do?

**Comment by TonyPythoneer** [comment]
I see it's equivalent to this:
```
interface Request extends http.IncomingMessage {
    absoluteUri: ....
}
```

If you are inexperienced in asserting type, I recommend that you can choice a small library which no depency to learn how to do. Originally, I follow the way to learn how to make typescript definition.

**Comment by KostyaTretyak** [comment]
I understand that I may do, I do this:

```ts
interface Request extends http.IncomingMessage {
    absoluteUri: ....
}
```

But still TypeScript throw en error:
> Property 'IncomingMessage' does not exist on type 'typeof "http"'.

**Comment by TonyPythoneer** [comment]
It's so weired. I will try do that and respond for you tomorrow.

**Comment by KostyaTretyak** [comment]
In my previous comment I was wrong. Actually I try `class extends` (not `interface extends`) with error:

```ts
class Request extends http.IncomingMessage {
    absoluteUri: ....
}
```

**Comment by TonyPythoneer** [comment]
Maybe it has solved your doubt. Does it close this issue?

**Comment by KostyaTretyak** [comment]
No, it does not solve my problem.

**Comment by TonyPythoneer** [comment]
I find `interface extends` is okay. Why you get error? Do you install `@types/node`?

**Comment by KostyaTretyak** [comment]
As you can see subject this issue, I need extends class `http.IncomingMessage`, not interfere. In my previous comment I was wrong because I repeat after you `interface extends`. Actually, [this code extends class](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/13909#issuecomment-271806556).

**Comment by KostyaTretyak** [comment]
I see that really not exists Node.js API for extends `http.IncomingMessage`. This way more as hack and not normal extends:

```js
http.IncomingMessage.prototype.absoluteUri = function absoluteUri(path) {
  // ...
};
```

I [found this](http://stackoverflow.com/a/26337542/1716560) way to extends `http.IncomingMessage`:

```js
var extendedRequest = {
  get userAgent() {
    this.request.headers['user-agent'];
  }
}

createServerCallback(function (req, res) {
  var request = Object.create(extendedRequest);
  request.request = req;
});
```
