### ISSUE TITLE
 Definition Request: nextjs/react-next

### ISSUE THREAD

**Issue by gozes** [DefinitelyTyped/DefinitelyTyped#13925]
I just came cross an [issue](https://github.com/zeit/next.js/issues/96) on on the react-next repo about using typescript with react-next and one of the things mention is that there is no type definition for it so I'm opening this issue to request the type definitions. I would love to use next with typescript as well 😄

**Comment by JerryGreen** [comment]
- [ ] Add useRouter hook definition (https://github.com/zeit/next.js/pull/6869)
