### ISSUE TITLE
typing errors from Node typings file (question)

### ISSUE THREAD

**Issue by sharathbaddam** [DefinitelyTyped/DefinitelyTyped#13949]
I installed latest node typings file by using the following statement 'typings install dt~node --global --save'

When i compile my typescript source files using gulpfile, i'm getting following errors from node/index.d.ts file and also express-serve-static-core/index.ts

![image](https://cloud.githubusercontent.com/assets/22323656/21867247/5606abc6-d81b-11e6-8857-dfdfe40761fb.png)

I'm using typescript version 2.1.4 and node version 6.9.4

**Comment by mhegazy** [comment]
I am not seeing this locally.

```sh
c:\test\13949>typings install dt~node --global --save
node
`-- (No dependencies)

c:\test\13949>tsc  --v
Version 2.1.4

c:\test\13949>tsc

c:\test\13949>echo %errorlevel%
0

```

**Comment by sharathbaddam** [comment]
yes i did something wrong, 
It is working now.
thanks for looking @mhegazy
