### ISSUE TITLE
[Request] nodegit

### ISSUE THREAD

**Issue by aenciso** [DefinitelyTyped/DefinitelyTyped#13963]
Could you please create a definition for nodegit

http://www.nodegit.org/api/

Thanks

**Comment by hinell** [comment]
Feel free to open PR with basic file. I'll help you with definitions.

**Comment by samiraguiar** [comment]
I've been using [these](https://github.com/RabbitLabs/nodegit-typescript-definition/blob/master/nodegit.d.ts) definitions and they work fine. You could talk to the creator to add to DefinitelyTyped.

**Comment by FlorianKoerner** [comment]
https://github.com/RabbitLabs/nodegit-typescript-definition/issues/3#issuecomment-288344937

**Comment by JimiC** [comment]
`nodegit` type definitions are available [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/nodegit).
@aenciso Please close issue.

/cc @horiuchi
