### ISSUE TITLE
heatmap.js

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#13999]
- [X] I want to talk about `heatmap/index.d.s`.
  - The authors of that type definition are cc/ @Lookuptable

The [documentation](https://www.patrick-wied.at/static/heatmapjs/docs.html) on `heatmap` describes a module (also exposed as a global `h337`) that exposes `create` and `register` functions.
The types that we have only declare a global `HeatmapOverlay` class.
But no such class appears anywhere in the [source code](https://github.com/pa7/heatmap.js/blob/master/build/heatmap.js).
Are these types for the wrong version? They say for `v2.0`, but that's the latest version, and the API described on the website seems totally different.

**Comment by rhys-vdw** [comment]
Hi @andy-ms. You're quite right about the botched typings. I'm in the process of adding in the documented types. The undocumented API appears to be from an optional "plugin" that exposes itself globally, but under a separate namespace.

Still learning how to do this properly, but I should have something soon.

**Comment by rhys-vdw** [comment]
@andy-ms Perhaps you could give me some guidance?

The existing types define globals crated in the [`leaflet-heatmap.js` plugin file](https://github.com/pa7/heatmap.js/blob/4e64f5ae5754c84fea363f0fcf24bea4795405ff/plugins/leaflet-heatmap/leaflet-heatmap.js). This file assumes a global called `h337` (ie. the global that is created when [no module system is found](https://github.com/pa7/heatmap.js/blob/4e64f5ae5754c84fea363f0fcf24bea4795405ff/build/heatmap.js#L17)).

If I were to import the module into TypeScript using `import * as h337 from "heatmap.js"` then it would be impossible to use these plugins.

Is it worth preserving types for this plugin API? How does one import a UMD module into a TypeScript project such that it still defines a global and can be used in conjunction?

This is a little of what I have so far:

```ts
export as namespace h337;

/*
* Create a heatmap instance. A Heatmap can be customized with the configObject.
*/
export function create<X extends string, Y extends string, V extends string>(
    configObject: HeatmapConfiguration<X, Y, V>
): Heatmap<X, Y, V>;

export function register(pluginKey: string, plugin: any): void

export class Heatmap<X extends string, Y extends string, V extends string> {
// ...
```

As you [can see](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/62c1cc83044a3a3086f57db9d2fde3d71df0ffc7/types/heatmap.js/index.d.ts#L9-L13) existing types are defined globally. I can preserve these existing types in a `declare module global {}` beneath the actual library API. But I'm unclear on how they would actually be used. Is there a way of configuring TypeScript to not use modules and simply run the script that augments `window`? I'm new to TypeScript and have only used `import`/`export` semantics.

**Comment by andy-ms** [comment]
> The existing types define globals crated in the leaflet-heatmap.js plugin file. This file assumes a global called h337 (ie. the global that is created when no module system is found).

That's unfortunate but there's nothing TypeScript can do about it. I wouldn't recommend trying to force users to never import this module as it *can* be imported if the plugin isn't used. If you try to import the module *and* use the plugin then I guess it will just fail at runtime.

I would just define all the symbols that can possibly be accessed and leave a note describing how to ensure they're defined.

**Comment by rhys-vdw** [comment]
Would it be appropriate to move the plugin types into a file like `types/heatmap.js/plugins/leaflet-heatmap/leaflet-heatmap.d.ts` and declare them globally there? This would map to `require("heatmap.js/plugins/leaflet-heatmap/leaflet-heatmap")`.

**Comment by rhys-vdw** [comment]
I just realized that probably doesn't make sense since you can't `require` it anyway...

**Comment by andy-ms** [comment]
Yeah, better to just leave them as is.
