### ISSUE TITLE
Global modules not available anymore?

### ISSUE THREAD

**Issue by nvivo** [DefinitelyTyped/DefinitelyTyped#14001]
Using `typings install dt~angular --global --save` seems no longer possible, giving the following error:

`Attempted to compile "angular" as a global module, but it looks like an external module. You'll need to remove the global option to continue.`

Not only angular, but algo ui-router, ui-bootstrap, and many others.

"Remove the global option" is not an option. How do I get the global module version?

**Comment by TonyPythoneer** [comment]
please install types by npm. typings is so old.

**Comment by nvivo** [comment]
Is it posible to use the npm version without imports?

**Comment by TonyPythoneer** [comment]
Yes, typescript can auto detect the type when installing by npm. In node, it doesn't need to import.

When definition can be installed by npm, I haven't used typings. The reason is typings is not friendly.

**Comment by nvivo** [comment]
@TonyPythoneer Are you sure this works? I just did a test, typescript cannot find any types when I do.

`npm install --save @types/angular`

From every example I can find, this only works with imports, which is a problem as lots of existing projects cannot be updated just to install a new library.

I'm not saying things shouldn't move on, but there should be a way to get the last global definition somehow. Currently, I'm looking into the git history and saving the file manually. This is not a good solution.

**Comment by nvivo** [comment]
Ok, just found I have to add:
```
{
     "types": ["angular"] 
}
````

in the tsconfig.json. Seems to work.
