### ISSUE TITLE
Inconsistent behavior for JS and TS lodash 'result' method

### ISSUE THREAD

**Issue by denver-HJS** [DefinitelyTyped/DefinitelyTyped#14076]
I'm using the @types/lodash package from NPM and getting inconsistent behavior for it's `_.result(object, path, [defaultValue])` method.

You are supposed to be able to provide a nested path as the second parameter, but the @types/lodash version is only working for top level properties on the object.

Using `_` from [lodash docs](https://lodash.com/docs/4.17.4#result)
![lodash_screen](https://cloud.githubusercontent.com/assets/1916018/22046546/406a909c-dcd6-11e6-9332-45c4a57a57c5.png)

Using `_` in my personal app that's using @types\lodash
![typed_lodash_screen](https://cloud.githubusercontent.com/assets/1916018/22046545/406a2fbc-dcd6-11e6-837e-2ba9cbd206ab.png)

I'm at version **4.14.45**. Could these unmet peer dependencies be causing an issue?
![screen shot 2017-01-17 at 5 05 48 pm](https://cloud.githubusercontent.com/assets/1916018/22046711/604282b6-dcd7-11e6-86c2-fad9ed9866e3.png)

**Comment by TonyPythoneer** [comment]
I don't think this is '@types/lodash' problem. Type file just offters IDE to parse JS lib. It doesn't include logic process.

**Comment by denver-HJS** [comment]
I raised the issue with the lodash repository and they replied to me with 

> We don't maintain the TS typings. That falls to the folks at DefinitelyTyped.

Is it possible that something has been parsed incorrectly? It seems apparent that something is lost in the translation.

**Comment by mhegazy** [comment]
` @types\lodash` is the TS typings. this package however has **no** js code, nor js dependencies. try deleting this package, and trying your scenario again, I do not expect there is any difference.

**Comment by denver-HJS** [comment]
I know that the typings don't have js dependencies, but the conversion from the source lodash library is not correct. The proof is in the OP.

I see the interface in node_modules/types/lodash/index.d.ts:

```
//_.result
    interface LoDashStatic {
        /**
         * This method is like _.get except that if the resolved value is a function it’s invoked with the this binding
         * of its parent object and its result is returned.
         *
         * @param object The object to query.
         * @param path The path of the property to resolve.
         * @param defaultValue The value returned if the resolved value is undefined.
         * @return Returns the resolved value.
         */
        result<TObject, TResult>(
            object: TObject,
            path: Many<StringRepresentable>,
            defaultValue?: TResult|((...args: any[]) => TResult)
        ): TResult;

        /**
         * @see _.result
         */
        result<TResult>(
            object: any,
            path: Many<StringRepresentable>,
            defaultValue?: TResult|((...args: any[]) => TResult)
        ): TResult;
    }
```
but I don't see the implementation anywhere. It must not be evaluating the "nested.property" style path (2nd parameter) correctly.
