### ISSUE TITLE
react-redux broken in master

### ISSUE THREAD

**Issue by pzavolinsky** [DefinitelyTyped/DefinitelyTyped#14080]
The [react-router/tsconfig.json](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react-router/tsconfig.json) has the `"history": ["history/v2"]` option. 

This in turn breaks dependent packages, like `react-redux` (currently not building in `master`).

Effectively this prevents contributions on related packages (most notably the `react` package).

Related to: #14062, #14049, #14028

A quick and dirty (and sad) workaround would be to include `"history": ["history/v2"]` in [react-redux/tsconfig.json](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react-redux/tsconfig.json) copied from [react-router/tsconfig.json](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react-router/tsconfig.json).

Of course, we cannot go chasing every package that depends on `react-router` and patch their `package.json` so a better solution would be to fix `history` and take care of that `v2` folder.

At first glance it would look like the `history` package shouldn't have that `v2` folder at all.

In any case, the repro steps to the broken `master` build are:

```shell
cd react-redux
../node_modules/.bin/tsc
```

Also note that fixing #14056 might prevent this from happening in the future.

**Comment by andy-ms** [comment]
We've already updated the others that depend on `react-router` to have the correct path mappings, this one was missed. `history/v2` is for version 2 of history, `history/index.d.ts` is for version 4. So until packages are updated to use history v4, they need the path mapping.

**Comment by pzavolinsky** [comment]
Cool, please let me know when this gets fixed in `master` to I can rebase my fork.

**Comment by andy-ms** [comment]
You can subscribe to #14090 to be notified when it's merged.

**Comment by pzavolinsky** [comment]
Done, thanks!
