### ISSUE TITLE
export = doesn't let it to use as default export

### ISSUE THREAD

**Issue by TrySound** [DefinitelyTyped/DefinitelyTyped#14160]
- [X] I tried using the latest `lodash/map/index.d.ts` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I want to talk about `lodash/map/index.d.ts`.
  - The authors of that type definition are cc/ @andy-ms @mhegazy

This code

```ts
import map from 'lodash/map';

console.log(map([1, 2], item => item + 1));

```

shows this error

```
$ tsc index.ts
index.ts(1,8): error TS1192: Module '".../node_modules/@types/lodash/map/index"' has no
default export.
```

And when I change this
```ts
import { map } from "../index";
export = map;
```
to this
```ts
import { map } from "../index";
export default map;
```
everything became perfect.

**Comment by andy-ms** [comment]
See the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default).

**Comment by ywzhaiqi** [comment]
solution

    import map = require('lodash/map')
