### ISSUE TITLE
React: Type inference with `ComponentClass` results in `any`

### ISSUE THREAD

**Issue by faddee** [DefinitelyTyped/DefinitelyTyped#14176]
Using type argument inference with `React.ComponentClass<P>` in `@types/react@0.14.57` to `@types/react@15.0.1` results in `P` being `any`.

```tsx
class Foo extends React.Component<{foo: string}, void> {
  render() {
    return <div />
  }
}

function func<P>(base: React.ComponentClass<P>): React.ComponentClass<P> {
  return base;
}

// const Bar: React.ComponentClass<any>
const Bar = func(Foo);
```

With `@types/react@0.14.56` results in:

```tsx
// const Bar: React.ComponentClass<{ foo: string }>
const Bar = func(Foo);
```

Is this a bug or is there another way to infer props now?

- [x] I tried using the latest `react/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `react/index.d.ts`.
  - The authors of that type definition are cc/ @....

**Comment by jwbay** [comment]
Root cause seems to be way back in #11612. When I remove that constructor from the typings locally, inference sites light up.

**Comment by ericanderson** [comment]
Not that my say matters, but LGTM :)

**Comment by samijaber** [comment]
This issue should be reopened. This bugs currently exists with the latest version of `@types/react`, and can be reproduced by instantiating the component's `constructor`. Here's an updated example:

```tsx
type Props = { foo: string }
class Foo extends Component<Props> {
  constructor(props) {
    super(props)
  }

  render() {
    return <div />
  }
}

function func<P>(base: React.ComponentClass<P>): React.ComponentClass<P> {
  return base;
}

// const Bar: React.ComponentClass<any>
const Bar = func(Foo);
```

**Comment by jardakotesovec** [comment]
@samijaber Hi, just noticed the same problem. I think it will be necessary to create new issue..  closed issues often not get much attention.
