### ISSUE TITLE
[Request] datatables-select

### ISSUE THREAD

**Issue by Borzakov** [DefinitelyTyped/DefinitelyTyped#14207]
Would be nice to see definitions for this extension
https://datatables.net/extensions/select/

**Comment by StevenLiekens** [comment]
I have a draft of what the definitions should look like but it is far from complete.
https://gist.github.com/StevenLiekens/166688e7b91aa75406d0b3f971ab1142

**Comment by Borzakov** [comment]
Wow, im blind. 
Didnt press 'Enter' on npm search '@types/datatables-select' (wasnt showing up in fast search for '@types/datatables')
Thanks!
