### ISSUE TITLE
Add support to nvd3

### ISSUE THREAD

**Issue by luisrudge** [DefinitelyTyped/DefinitelyTyped#1422]
To those of us that can't use d3!

http://nvd3.org/ :)

**Comment by robertogyn19** [comment]
+1

**Comment by UzEE** [comment]
+1

I guess there aren't enough people requesting this.

**Comment by Dao007forever** [comment]
+1

**Comment by pgrm** [comment]
:+1:

**Comment by laduran** [comment]
http://media.giphy.com/media/wi8Ez1mwRcKGI/giphy.gif

**Comment by kyranjamie** [comment]
+1

**Comment by on3al** [comment]
+1

**Comment by asdiallo** [comment]
+1

**Comment by lpotapczuk** [comment]
+1

**Comment by QuantumInformation** [comment]
Would love to to see proper syncing of types and nvd3, types have deprecated functions like tooltips() etc
