### ISSUE TITLE
[react-autosuggest] - Invalid type definition

### ISSUE THREAD

**Issue by maticicero** [DefinitelyTyped/DefinitelyTyped#14224]
I'm using latest version of `@types/react-autosuggest`, which at the moment is **7.0.1**

`@types/react-autosuggest/index.t.ts` is exporting two members:

    // ...
    export interface SuggestionSelectedEventData<TSuggestion>
    {
        // ...
    }
    // ...
    export class Autosuggest extends React.Component<any, any> {}

However, the implementation at `react-autosuggest/dist/index.js` (*react-autosuggest v8.0.0*) is only exporting a single member:

    module.exports = require('./Autosuggest').default;

This is causing a conflict between the type definition and the actual implementation, which is making my code fail at runtime.

For instance, take a look at the following code:

    import {Autosuggest} from "react-autosuggest";
    // Autosuggest will yield "undefined" at runtime, but Typescript identifies it as a React.component

    import * as Autosuggest from "react-autosuggest";
    // Autosuggest is a React.Component at runtime, but Typescript identifies it as a namespace.

**Comment by DanielRosenwasser** [comment]
If you're up for it, you can send a PR so that the `.d.ts` file looks like this:

```ts
class Autosuggest extends React.Component<any, any> { }

export = Autosuggest;
```

**Comment by DanielRosenwasser** [comment]
Also, all the interfaces would have to be wrapped in a namespace called `Autosuggest`, so it'd actually be 

```ts
class Autosuggest extends React.Component<any, any> { }
namespace Autosuggest {
    export interface SuggestionSelectedEventData<TSuggestion>{
        // ...
    }
}

export = Autosuggest;
```

**Comment by tbayne** [comment]
@DanielRosenwasser ,
I tried what you suggested but that, for me, didn't get the job done.  I had to do:

```
declare class Autosuggest extends React.Component < any,any > {}
export = Autosuggest;
export as namespace Autosuggest;

declare namespace Autosuggest {

   // All the interfaces
}
```

**Comment by aalenliang** [comment]
how to use it without default export?

**Comment by DanielRosenwasser** [comment]
Try using

```ts
import Autosuggest = require("react-autosuggest")
```

Does that work?

**Comment by pozdena** [comment]
Until this is fixed, this worked for me:

```typescript
import {AutosuggestProps} from 'react-autosuggest'
const Autosuggest = require('react-autosuggest') as
                      new() => React.Component<AutosuggestProps, any>
```

**Comment by begincalendar** [comment]
@aalenliang @pozdena 
How are you using the `Autosuggest` class, such that the error message (you posted) appears?

Also, what versions of TypsScript and `@types/react-autosuggest` are you using?

**Comment by epeli** [comment]
I'm seeing this too. The type of the exported Autosuggest class is just `React.Component<any>`.

My workaround is this

```typescript
import Autosuggest_, {AutosuggestProps} from "react-autosuggest";

const Autosuggest = Autosuggest_ as new () => React.Component<
    AutosuggestProps,
    any
>;
```

Using Typescript 2.5.

**Comment by epeli** [comment]
This actually seems to fix it https://github.com/epeli/DefinitelyTyped/commit/1bf29e6460b65b90ae5ccb91f96e451cb6f18f59

But I'm pretty much a Typescript newbie. Can anyone confirm that this is the right approach?

**Comment by DanielRosenwasser** [comment]
@epeli that sounds appropriate.

**Comment by tkcranny** [comment]
It looks like the typings have been improved in the last year, datatype-specific Autosuggest classes can be made as such:

```js
import * as Autosuggest from 'react-autosuggest'
interface Language {
    name: string
    year: number
}

const LanguageAutosuggest = Autosuggest as { new (): Autosuggest<Language> }
```

(See [DefintlyTyped's README](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-autosuggest) for react-autosuggest for more details)
