### ISSUE TITLE
Select Missing headers variable in interface Select2AjaxOptions

### ISSUE THREAD

**Issue by tonimitrevski** [DefinitelyTyped/DefinitelyTyped#14246]
- [interface Select2AjaxOptions {} ] I want to talk about `select2/index.d.ts`.

I want to ask why in this interface is missing headers variable?

I cannot set headers in ajax call

![headersselect](https://cloud.githubusercontent.com/assets/15773773/22305327/5d1e96a0-e33b-11e6-93be-0ccb860f9ded.png)

**Comment by DanielRosenwasser** [comment]
Feel free to send a PR.

**Comment by tonimitrevski** [comment]
I think we should add a headers variable in Select2AjaxOptions interface. I tested and works fine

![headers select2](https://cloud.githubusercontent.com/assets/15773773/22324114/8e296df8-e3a7-11e6-86bd-69f47a6a9b6e.png)

**Comment by begincalendar** [comment]
I believe this issue can be closed due to the merge from #17122.
