### ISSUE TITLE
Lodash submodules are not working anymore

### ISSUE THREAD

**Issue by asvetliakov** [DefinitelyTyped/DefinitelyTyped#14267]
- [x] I tried using the latest `lodash/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `lodash/index.d.ts`.

@mhegazy, @andy-ms 
This PR #12995 breaks importing lodash submodules with ES6 imports:
```
import * as uniq from "lodash/uniq"
// or
import * as uniq from "lodash.uniq"
```
Gives me this error:
```
message: 'Module '"c:/Users/asvet/work/applications/frontend/node_modules/@types/lodash.uniq/index"' resolves to a non-module entity and cannot be imported using this construct.'
```

Unfortunately i'm compiling to ES2015 modules so ```import uniq = require("lodash/uniq")``` gives me other error

**Comment by andy-ms** [comment]
Related: Microsoft/TypeScript#5073.

**Comment by pocesar** [comment]
```import { sample, shuffle } from 'lodash'``` doesn't work anymore as well

**Comment by jiayihu** [comment]
Why was the PR closed? I'm having the same issue.

**Comment by pocesar** [comment]
the namespace hack had issues with other libraries :(

**Comment by andy-ms** [comment]
@pocesar The NPM package doesn't use a default export. How did you install lodash?

**Comment by pocesar** [comment]
@andy-ms through npm the usual way, only if the mix of Typescript nightly and babel are breaking the imports (target: "es6")

**Comment by andy-ms** [comment]
Some tool you're using is creating a `__useDefault` property on the imported module.

**Comment by shuntksh** [comment]
Had similar issue and  `import cloneDeep  = require("lodash.clonedeep");` worked for me. Not sure it is related to OP's issue though.

**Comment by asvetliakov** [comment]
@shuntksh It's related, but ```import a = require("b")``` construction doesn't work if you target to es6 modules, i.e. have ```"module": "es6"``` in your tsconfig.json, for example when using wepback2.

I'll try to fire another PR

**Comment by evestraw** [comment]
i changed all the import {x} from "lodash" 
export = x 

to export {x} from "lodash"

**Comment by Kovensky** [comment]
Why does the compiler forbid `import foo = require('bar')` when the module target is "es2015"?

**Comment by andy-ms** [comment]
When the target is es6, we expect to emit an ES6 module, not a CommonJS one.

**Comment by Kovensky** [comment]
@andy-ms however, being a module does not forbid access to `require` under the node interop spec.

I guess it can be a problem if you are going to assume your module must work even on a browser that wouldn’t provide require.

**Comment by andy-ms** [comment]
@Kovensky I'm not familiar with the node interop spec; this feature might predate that. Do you have a link?

**Comment by Kovensky** [comment]
@andy-ms hm, never mind what I say; the new spec also removes access to `require`. I assume it became unnecessary after the introduction of dynamic `import()`.

The current interop spec is at https://github.com/nodejs/node-eps/blob/master/002-es-modules.md; the version on `master` was outdated for quite a while but recently a new rewrite actually got merged.

**Comment by aj-r** [comment]
I think this is fixed if you use [`esModuleInterop`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
