### ISSUE TITLE
Lodash's _.mapKeys(object, ...) fails if object is type Object

### ISSUE THREAD

**Issue by Shingyx** [DefinitelyTyped/DefinitelyTyped#14282]
- [x] I tried using the latest `lodash/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `lodash/index.d.ts`.
  - The authors of that type definition are cc/ @chrootsu, @vvakame 

If I call _mapKeys(object, ...) with object being type Object, TypeScript gives the following error when it tries to compile:
`error TS2345: Argument of type 'Object' is not assignable to parameter of type 'List<{}> | Dictionary<{}>'`

I think this should work judging by Lodash's documention: https://lodash.com/docs/4.17.4#mapKeys

There was a similar problem in the past regarding _.some(), found here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/8630

Could you please look into this?

Thanks.

**Comment by stevenmitts** [comment]
Any word on this being fixed? I'm running into this as well on mapKeys.

**Comment by bzums** [comment]
Having the same problem.

**Comment by aj-r** [comment]
This should be fixed by #19356 (although the first argument should have type `object`, not `Object`).
