### ISSUE TITLE
'Cannot find name HTMLElement' error in @types/webdriverio

### ISSUE THREAD

**Issue by thedevelopnik** [DefinitelyTyped/DefinitelyTyped#14306]
- [X ] I tried using the `@types/webdriverio` package and had problems.
- [X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nmalaguti

On lines 148 and 154 of @types/webdriverio there is a type called HTMLElement. When I run tsc on anything that uses @types/webdriverio I get the following error: 

`error TS2304: Cannot find name 'HTMLElement'`

from the lines: 

`script: (elements: HTMLElement | HTMLElement[], ...args: any[]) => P`

one error for the `HTMLElement` and one for the `HTMLElement[]`.

Should this be defined somewhere? How would we define it?

Happy to help or make a PR with some direction.

**Comment by mhegazy** [comment]
do you have `--lib` set? and does it include `dom`?

**Comment by xhallix** [comment]
@mhegazy can you be please a litte bit more precise? I have the same issue - setting my `"lib": [ "es2015" ]` . What do you mean with `dom`?
you refer to this -> https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts ?

Shouldn't this be included in typescript already?

**Comment by timbru31** [comment]
@xhallix he meant that you need to include `"dom"` in your `"lib"` array, like this:
```json
...
		"lib": [
			"es2016",
			"dom"
		],
...
```

**Comment by heqiao** [comment]
Including `dom` doesn't work for me. Did it work for you guys? @timbru31 @xhallix

**Comment by uniqueiniquity** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32490
