### ISSUE TITLE
dot-object pick should return any in stead of void (sent PR)

### ISSUE THREAD

**Issue by aredfox** [DefinitelyTyped/DefinitelyTyped#14319]
- [x] I tried using the `@types/dot-object` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nkovacic @rhalff

**Description**: Function ['pick'](https://github.com/rhalff/dot-object#pickremove-a-value-using-dot-notation) shows in [dot-object](https://www.npmjs.com/package/dot-object) documentation to return a value - yet in the [typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/dot-object/index.d.ts) it has the return value `:void`.

I have used dot-object's `pick` a long time to get values from a given 'path/key' - like done in the documentation: `var val = dot.pick('some.nested.value', obj);` - but now when using this in TypeScript with the current typing it won't let me - as the return type is `void`. 

I would like to suggest changing this to returnign type `any` - as when removing the value it is documented to return it as well before removing it. Hence I don't think (correct me if I'm wrong) there's need for an overload here.

```
       /**
         *
         * Pick a value from an object using dot notation.
         *
         * Optionally remove the value
         *
         * @param {String} path
         * @param {Object} obj
         * @param {Boolean} remove
         */
        pick(path: string, obj: any, remove?: boolean): any;
```

**Reference to dot-object documentation**: https://github.com/rhalff/dot-object#pickremove-a-value-using-dot-notation
```
var obj = {
 some: {
   nested: {
     value: 'Hi there!'
   }
 }
};

var val = dot.pick('some.nested.value', obj);
console.log(val);

Hi there!
```

**Comment by aredfox** [comment]
Created PR for this, if this could help [ https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14320 ]

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
