### ISSUE TITLE
Lodash chain methods uses wrong generic type

### ISSUE THREAD

**Issue by asfernandes** [DefinitelyTyped/DefinitelyTyped#14337]
- [ x ] I tried using the `@types/xxxx` package and had problems.

- Authors: @bczengel, @chrootsu, @stepancar

// Type definitions for Lo-Dash 4.14

This interface (and others) uses wrong types. Type `<T>` should not be used in the method name, only in the interface.

```
    interface LoDashExplicitArrayWrapper<T> {
        /**
         * @see _.head
         */
        first<T>(): T;
    }
```

To make this code use correct type:

```
let a = _([1, 2, 3])
	.chain()
	.first();
```

Currently this code makes `a` with type `{}`.

Definition of interface should be as below, to make `a` of type `number`.

```
    interface LoDashExplicitArrayWrapper<T> {
        /**
         * @see _.head
         */
        first(): T;
    }
```

**Comment by alexjlockwood** [comment]
Any updates on this @bczengel, @chrootsu, or @stepancar? Thanks!

**Comment by JReinhold** [comment]
The exact same problem exists when using `last()` in a chain

**Comment by asfernandes** [comment]
Unfortunately, no feedback from the authors in 4 months...

**Comment by JReinhold** [comment]
I'll try to make an initial PR soon then. do you have an overview of which functions are implicated besides `first()` and `last()`?

**Comment by asfernandes** [comment]
No, I'm not a long lodash's user.

**Comment by JReinhold** [comment]
Cool, I think I've figured it out.

**Comment by JReinhold** [comment]
after in depth testing it seems that
```
let a = _([1, 2, 3])
	.chain()
	.first();
```

actually does return an object (a wrapper for chaining), so this issue should be closed IMO.

However type problems still persists when trying to:
```
let a = _([1, 2, 3])
	.chain()
	.first()
	.value()
```

as it says `value() does not exist on type {}`, but I think that is another issue.

**Comment by asfernandes** [comment]
The issue says about chain *methods*, not "the method chain", so I see no reason for another issue. Return type of first() is definitively wrong.

**Comment by JReinhold** [comment]
how is it wrong?

this code:
```
import * as _ from 'lodash';

let a = _([1, 2, 3])
	.chain()
	.first();

console.log(a);
```
prints:
```
{ [Number: 1]
  __wrapped__: [ 1, 2, 3 ],
  __actions__: [ { func: [Function: thru], args: [Object], thisArg: [Object] } ],
  __chain__: true,
  __index__: 0,
  __values__: undefined }
```

**Comment by asfernandes** [comment]
We're talking about definitely typed project, i.e., about types.

console.log accepts type `any`, so you can't test with it.

I'm saying the type of `a` is incorrectly if wou want to chain more methods on it.

**Comment by JReinhold** [comment]
Ah I see. Can you give an example of a method you would chain after `.first()`? in our `a` example, vanilla Number methods doesn't work (eg. `toFixed()`), and I can't seem to find a LoDash chainable method that would make sense to chain after `first()`. Am I missing something?

**Comment by asfernandes** [comment]
You said a good one: `value()`

**Comment by aj-r** [comment]
Hey guys, just I just discovered this issue. I'm actually working on a PR that revamps all of the implicit/explicit wrappers to fix this. Basically, the new types will look like this:

```
interface LoDashExplicitWrapper<TValue> {
    /**
     * @see _.head
     */
    first<T>(this: LoDashExplicitWrapper<List<T> | null | undefined>): LoDashExplicitWrapper<T | undefined>;
}
```

There will be no more `LoDashExplicitArrayWrapper` or `LoDashExplicitObjectWrapper` - everything will just be `LoDashExplicitWrapper`. This will also fix head, last, find, and any other function with this issue.
