### ISSUE TITLE
node_modules/@types/lodash/index.d.ts:245:25: Cannot find name 'Partial'.

### ISSUE THREAD

**Issue by sandman21dan** [DefinitelyTyped/DefinitelyTyped#14338]
- [ x] I tried using the `@types/lodash` package and had problems.

Using @types/lodash 4.14.50 tslint (Using the default tsconfig from angular-cli) runs without problems, when updated to version @types/lodash 4.14.51 I get consistently the following tslint error:

`
node_modules/tslint/lib/runner.js:91
                    throw new Error(messages.join("\n"));
                    ^

node_modules/@types/lodash/index.d.ts:245:25: Cannot find name 'Partial'.
    at Runner.run (/opt/atlassian/pipelines/agent/build/node_modules/tslint/lib/runner.js:91:27)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/tslint/lib/tslint-cli.js:138:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/tslint/bin/tslint:3:1)
`

**Comment by aboodz** [comment]
I'm facing the same issue on 4.14.51. build details
```
npm ERR! Linux 4.8.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
```
I'm reverting back 4.14.45

**Comment by sandman21dan** [comment]
@aboodz even version 4.14.50 doesn't have the issue, Try that which shouldn't error anymore

**Comment by goleary** [comment]
same here! pinned the version to 4.14.50

**Comment by mhegazy** [comment]
This is the same issue as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13994#issuecomment-275949045.

The `Partial` type referenced should be available in TS 2.1. Fixing the version of the `@types/lodash@ts2.0` (or `@types/lodash@4.14.50`) should address the error you are getting.

**Comment by msaiyaff** [comment]
Changing the version to 4.14.50 solved the error i have got. Thanks

**Comment by muziekklas** [comment]
changing the version of @typing/lodash to 4.14.50 solved the issue with us aswell!

**Comment by vlodko** [comment]
@muziekklas downgrading to @typing/lodash v4.14.50 worked for me! Thanks :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
