### ISSUE TITLE
@types/lodash package has no declare module

### ISSUE THREAD

**Issue by elektromodulator** [DefinitelyTyped/DefinitelyTyped#14378]
index.d.ts in @types/lodash package has no _declare module "lodash",_ so I can't import it into other modules.
This is a problem for me, as I target AMD module type in compiled JavaScript.

**Comment by mhegazy** [comment]
What version of the compiler are you using? can you share your tsconfig.json?

**Comment by elektromodulator** [comment]
I use TypeScript 2.1. My tsconfig.json:
_{
  "compilerOptions": {
    "noImplicitAny": true,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "module": "amd",
    "target": "es5"
  },
  "exclude": [
    "node_modules"
  ]
}_

I don't know why you need this though. Shouldn't these definitions work out of the box for all kinds of configurations?

**Comment by mhegazy** [comment]
so why do you need `declare module "lodash"`? installing the `@types/lodash` should be picked up automatically by the compiler.

**Comment by elektromodulator** [comment]
Because TypeScript compiler cannot import this module.
I looked at some other d.ts files I installed through npm types scope, and I think it's not the declare module is the problem since other d.ts files do not have it either, but they can be imported.
I suspect the issue is rather that there is no export statement in lodash's d.ts file.

**Comment by mhegazy** [comment]
```sh
c:\test\14378>npm install -S @types/lodash
test@1.0.0 c:\test\14378
`-- @types/lodash@4.14.52

c:\test\14378>type tsconfig.json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "module": "amd",
    "target": "es5"
  },
  "exclude": [
    "node_modules"
  ]
}

c:\test\14378>type a.ts
import * as _ from "lodash";

c:\test\14378>tsc --v
Version 2.2.0

c:\test\14378>tsc

c:\test\14378>echo %ERRORLEVEL%
0
```

**Comment by elektromodulator** [comment]
I tried this and this does work, in VS 2015 too
I was doing something wrong, and I was wrong to assume that it was the missing declare model, or export statements.
The problem was with my solution.
