### ISSUE TITLE
Electron RequestOptions Protocol should be lowercase

### ISSUE THREAD

**Issue by tobiaskohlbau** [DefinitelyTyped/DefinitelyTyped#14407]
- [x] I tried using the `@types/electron` package and had problems.

@jedmao @rhysd @aliib 

I've tried to prepare a request with [RequestOptions](http://electron.atom.io/docs/api/client-request/). Looks like there is a little typo within the index.d.ts, protocol is written with an capital p but should be written with an lowercase as stated in the original documentation.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/electron/index.d.ts#L2782

**Comment by aliib** [comment]
Yes, you are right. It should be a lower p.

**Comment by rhysd** [comment]
I made a PR.
