### ISSUE TITLE
[redux-actions] Add type definition for createActions

### ISSUE THREAD

**Issue by felipemsantana** [DefinitelyTyped/DefinitelyTyped#14415]
Type definition for [createActions](https://github.com/acdlite/redux-actions#createactionsactionsmap-identityactions) is missing in [redux-actions/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/redux-actions/index.d.ts).

**Comment by kamek-pf** [comment]
It's gonna be a tough one, 
```typescript
const { thisIsMyActionName } = createActions({
    THIS_IS_MY_ACTION_NAME: () => {}
});
```
`createActions` "camecasifies" the action names at run time.
I'm not a type guru, but I'm not sure this is even possible :/

**Comment by V-Tom** [comment]
is there any update yet?

**Comment by christian-schulze** [comment]
This doesn't need to be an exact type, just something so it compiles. For example, the easiest a loosest type could be:
```
export function createActions(actionMap: any): any
```

**Comment by alexey-pelykh** [comment]
Guess this can be closed due to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/348d75dac9cb9bc550171e09d248e49691910946/types/redux-actions/index.d.ts#L184
