### ISSUE TITLE
angular-xeditable: not able to import xeditable typings along with Angular.

### ISSUE THREAD

**Issue by vireshmanagooli** [DefinitelyTyped/DefinitelyTyped#14464]
- [ ] I tried using the `@types/angular-xeditable` package and had problems.
  - Authors: @andy-ms 

I am getting the error - duplicate identifier for 'angular' module. I have modified the xeditable's typing file, then its working fine. I would raise a pull request. Please review it. 

modified type definition is as follows

`// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1770103b6ef1a658476712c1f127e41dc2c8aca1/angular-xeditable/index.d.ts

declare module "xeditable" {
// Type definitions for Angular xEditable (angular.xeditable module) 0.2
// Project: https://vitalets.github.io/angular-xeditable/
// Definitions by: Joao Monteiro <https://github.com/jpmnteiro>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
    import xeditable = angular.xeditable;
    export = xeditable;
}

declare namespace angular.xeditable {
        interface IEditableOptions {

            /**
              * Theme. Possible values `bs3`, `bs2`, `default`
              */
            theme: string;

            /**
              * Icon Set. Possible values `font-awesome`, `default`.
              */
            icon_set: string;

            /**
              * Whether to show buttons for single editalbe element.
              * Possible values `right` (default), `no`.
              */
            buttons: string;

            /**
              * Default value for `blur` attribute of single editable element.
              * Can be `cancel|submit|ignore`.
              */
            blurElem: string;

            /**
              * Default value for `blur` attribute of editable form.
              * Can be `cancel|submit|ignore`.
              */
            blurForm: string;

            /**
              * How input elements get activated. Possible values: `focus|select|none`.
              */
            activate: string;

            /**
              * Whether to disable x-editable. Can be overloaded on each element.
            */
            isDisabled: boolean;

            /*
            * Event, on which the edit mode gets activated.
            * Can be any event.
            */
            activationEvent: string;
        }

        interface IEditableFormController extends angular.IFormController {

            /**
             * Shows form with editable controls.
             */
            $show(): void;

            /**
             * Hides form with editable controls without saving.
             */
            $hide(): void;

            /**
             * Sets focus on form field specified by `name`.<br/>
             * When trying to set the focus on a form field of a new row in the editable table, the `$activate` call needs to be wrapped in a `$timeout` call so that the form is rendered before the `$activate` function is called.
             *
             * @param name name of field
             */
            $activate(name: string): void;

            /**
             * Triggers `oncancel` event and calls `$hide()`.
             */
            $cancel(): void;

            $setWaiting(value: boolean): void;

            /**
             * Shows error message for particular field.
             *
             * @param name name of field
             * @param msg error message
             */
            $setError(name: string, msg: string): void;

            $submit(): void;

            $save(): void;

        }
}
`

Thanks,
Viresh

**Comment by andy-ms** [comment]
I don't get a compile error when doing `npm install @types/angular-xeditable` and compiling with `typescript@next`. Maybe you're using an older version of the TypeScript compiler or of `@typers/angular`?

**Comment by vireshmanagooli** [comment]
I used following command to install typings in typings.json

`typings install xeditable=github:DefinitelyTyped/angular-xeditable/index.d.ts#1770103b6ef1a658476712c1f127e41dc2c8aca1 --save-dev`

typings -v 0.8.1
Angular -v 1.5.5

I am not getting the errors when I install "angular-translate" and "angular-route". I have modified xeditable definition file similar to "angular-translate" then it started working.

**Comment by andy-ms** [comment]
This looks like an error with the way `typings` transforms the types from DefinitelyTyped.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
