### ISSUE TITLE
@types/hapi Server needs an indexer key

### ISSUE THREAD

**Issue by danielo515** [DefinitelyTyped/DefinitelyTyped#14517]
- [x] I tried using the `@types/hapi` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/). 

Hello,

The `server.decorate` method allows plugins to decorate the server with extra properties/methods. Because this, the server should be accessed by index, for example `server.myProperty` or `server[prop]`. 

I fixed it on my local installation with this:

```js
export class Server extends Events.EventEmitter {

    [key: string]: any;
```

Regards

**Comment by danielo515** [comment]
Any comment regarding this issue? It is preventing any use of hapi on strict environments.

**Comment by AJamesPhillips** [comment]
@danielo515 I've put an example into the new hapi types in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16065
They're in tests/server/decorate.ts

With the current "v16.0" types you should be able to use exactly the same pattern of:

```
server.decorate('server', 'some_server_method', (server: Hapi.Server) => {
    return function(arg1: number){
        return "some text";
    }
});

declare module 'hapi' {
    interface Server {
        some_server_method(arg1: number): string;
    }
}

server.some_server_method(1);
```

**Comment by AJamesPhillips** [comment]
@danielo515 @andy-ms we can close this now 👍
