### ISSUE TITLE
@types/jquery - jQuery Event Object currentTarget not flexible enough

### ISSUE THREAD

**Issue by marksyzm** [DefinitelyTyped/DefinitelyTyped#14515]
- [ ] I tried using the `@types/jquery` package and had problems.

jQuery allows the user to create events on any object i.e. 
```typescript
class A {
  $el: JQuery = $('<div />');
  constructor() {
    this.$el.on('click', this.onClick.bind(this));
  }
  onClick(): void {
    jQuery(this).trigger('objectevent');
  }
}
```
`this` (the app instantiation in the new `objectevent`; a non `Element`) is then assigned to `currentTarget` by jQuery but at present `currentTarget` is typed to `Element` which won't work for any other object such as my case. `currentTarget` needs to be `any` or something along those lines as I can't create a new `JQueryEventObject` and assign any other object to test the events with, nor can I assume the above works in practise.  See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/index.d.ts#L497 for what I mean.

In essence, if I were to emulate a `JQueryEventObject` with that `currentTarget` behaviour I would have to do the following:
```typescript
const a = new A();
jQuery(a).on('objectevent', function (ev) {
  console.log(ev.currentTarget);
});
const objectEvent = jQuery.Event('objectevent');
// forcing it to be an "any" shouldn't be necessary
objectEvent.currentTarget = a as any;
// this should give the console.log with the correct currentTarget as the object "a"
jQuery(a).trigger(objectEvent);
// so should this
a.$el.click();
```

**Comment by dan-def** [comment]
I came across the same limitation today when using event.target.
