### ISSUE TITLE
@types/react-redux connect does not pass props through

### ISSUE THREAD

**Issue by voxmatt** [DefinitelyTyped/DefinitelyTyped#14526]
@ericanderson @sandersn @RyanCavanaugh  Hey everyone, I tried to take a stab at this myself, but no luck. `connect` doesn't properly combine `TStateProps, TDispatchProps, TOwnProps`. It currently only passes through the dispatch props; from what I can see.

I'm really not sure how to do this properly, but ideally, the wrapped component created by `connect` would have the same props as the original component.

**Comment by ericanderson** [comment]
Can you provide sample code? I don't see this problem in my projects. Thanks!

**Comment by voxmatt** [comment]
Yes, happy to provide code — God knows I'm probably just doing something wrong.

A couple relevant components:
(1) `calendar-view.component.tsx` -- the wrapped component
(2) `calendar-view.container.tsx` -- redux & relay container

**calendar-view.component.tsx**
`class CalendarView extends React.Component<ICalendarView.Props, ICalendarView.State> {`

the props on that component (ICalendarView.Props):
```
interface Props extends Container {
    org: ISchema.IOrg;
    user: ISchema.IUser;
    relay: Relay.RelayProp;
    calendars: Array<{ id: string, selected: boolean }>;
    orgId: string;
    selectedEventId: string;
    defragStale: boolean;
    isScheduling: boolean;
    clearDefragStale
}
```

And then in
**calendar-view.container.tsx**
```[javascript]
// there are other imports in this file, but the relevant ones:
import { connect } from 'react-redux';
import CalendarView from './calendar-view.component';
import { clearDefragStale } from '../../state/actions/calendar-view.actions';

function mapStateToProps(state: any) {
  return {
    calendars: state.calendarView.calendars,
    selectedEventId: state.calendarView.selectedEventId,
    defragStale: state.calendarView.defragStale,
    isScheduling: state.calendarView.isScheduling,
  };
};

const reduxContainer = connect(mapStateToProps, {
  clearDefragStale,
})(CalendarView);
```

With that setup, the `reduxContainer` created has an empty object for props; as seen in VSCode:
 
![screen](https://cloud.githubusercontent.com/assets/611503/22796230/7bc8762e-eeae-11e6-8d8e-b8556e2e048e.jpg)

**Comment by ericanderson** [comment]
The type for the second arg in mapStateToProps is the inferred properties type for the returned component. You don't have one so your component has no props.

**Comment by voxmatt** [comment]
Ha, awesome. Works like a charm.

Thanks and sorry for the distraction!
