### ISSUE TITLE
@type/react-color onChange is possibly not optional?

### ISSUE THREAD

**Issue by RickCarlino** [DefinitelyTyped/DefinitelyTyped#14548]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @LKay

```typescript
    interface CustomPickerProps<A> extends React.ClassAttributes<A> {
        color?: Color
        pointer?: React.ReactNode
        // Not actually optional?
        onChange?: ColorChangeHandler
    }
```
We recently used this typing in a project and did not supply an `onChange` callback to ` <Saturation/>` (we were using the component to display a color rather than to set it).

The code compiled fine, but raised a runtime error in production. This leads me to believe that `onChange` is not optional, at least for `<Saturation/>` components. [The source code for <Saturation />](https://github.com/casesandberg/react-color/blob/master/src/components/common/Saturation.js) seems to support this. We were able to easily fix it by [adding a NOOP](https://github.com/FarmBot/farmbot-web-frontend/blob/master/src/images/farmbot_picker.tsx#L96) to `onChange`, but it would have been nice to catch the issue at compile time instead of in production.

I can update the typing to reflect this, but wanted to make sure there wasn't some other reason for leaving `onChange` as optional. If this is in fact an issue worth fixing, I can submit a PR for the fix. Please let me know.

Thanks for authoring this typing.

**Comment by hinell** [comment]
>I can submit a PR for the fix

Well, if you do, then don't forget to fix it in 
```ts 
interface SaturationProps extends CustomPickerProps<Saturation> {} 
```
and link this issue in your PR title as "Closes #14548"

**Comment by LKay** [comment]
Will check and hopefully fix that on Monday.

**Comment by LKay** [comment]
PR #14589 should resolve both problems.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
