### ISSUE TITLE
Npm doesn't have the latest version of auth0-js released.

### ISSUE THREAD

**Issue by rokadias** [DefinitelyTyped/DefinitelyTyped#14560]
- [x] I tried using the `@types/auth0-lock` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @adrianchia 

Once this pull request was released updating auth0-js to have a v7 folder: 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14225

It updated auth0-lock and auth0.widget to use auth0-js/v7. Well what was released in npm for @types/auth0-js does does not include the v7 folder. I think it's because the header in auth0-js version didn't pass the lint test, and I've made a new PR for fixes based on the lint and tsc:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14559

**Comment by od0** [comment]
+1

**Comment by callicles** [comment]
+1

**Comment by od0** [comment]
@rokadias still seeing the same issue despite the PR being merged - anything different on your end?

**Comment by adrianchia** [comment]
could you try with npm install @types/auth0-js@7.0.1 to get the v7 version?

**Comment by od0** [comment]
@adrianchia adding the hard dependency worked, thanks

**Comment by od0** [comment]
I'm only able to run auth0-lock 10.9.0 though - 10.9.2 results in `Cannot find type definition file for 'auth0-js/v7'`

**Comment by rokadias** [comment]
So the work around is to continue using the old version of the dependencies via the following config:
```
devDependencies: {
  "@types/auth0-js": "^7.0.0",
  "@type/auth0-lock": "10.9.0"
}
```

I'm still seeing the same issue of the folder not being included in the npm package, and I don't know why. My pull request just followed the guidelines of the readme more closely.

**Comment by od0** [comment]
this is what's working for me currently: 

```
  "devDependencies": {
    "@types/auth0-lock": "10.9.0",
    "@types/auth0-js": "8.1.1",
    "@types/auth0-js": "7.0.1",
```

**Comment by adrianchia** [comment]
most likely update the package.json in https://github.com/rokadias/DefinitelyTyped/blob/df42ce87e9094053d38d1cca5b1ec95f86c5b5d6/auth0-lock/package.json to specify version 7.x.x instead of latest?

**Comment by rokadias** [comment]
That wouldn't make sense to me since package.json pointing to "^7.0.0" would not include the v7 folder which is what I tried at some point, but I could be incorrect. I'd love for someone to give some clarity here.

**Comment by garyforsterio** [comment]
+1

**Comment by ProTip** [comment]
I'm also seeing errors like this:

```
Cannot find name 'Auth0Error'. 
```

Latest releases, od0's versions work for me.

**Comment by adrianchia** [comment]
Could you try auth0.Auth0Error?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
