### ISSUE TITLE
chokidar watch should implement fs.FSWatcher and it is not

### ISSUE THREAD

**Issue by tyv** [DefinitelyTyped/DefinitelyTyped#14595]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @reppners

**Comment by tyv** [comment]
for example it is missing `.once` etc.. 
here is node fs.FSWatch https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/index.d.ts#L2208-L2235

**Comment by amir-arad** [comment]
see also #14563

**Comment by AviVahl** [comment]
Fix merged into master. FYI @tyv @amir-arad
