### ISSUE TITLE
react-redux connect with an undefined mapStateToProps

### ISSUE THREAD

**Issue by plee-nm** [DefinitelyTyped/DefinitelyTyped#14622]
I tried using the `@types/react-redux` package and had problems.

The connect definition does not allow for an undefined mapStateToProps argument (with strictNullChecks).  [connect docs](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options)

I believe this will work as the only connect definition  

```
export declare function connect<TStateProps, TDispatchProps, TOwnProps>(
    mapStateToProps?: FuncOrSelf<MapStateToProps<TStateProps, TOwnProps>>,
    mapDispatchToProps?: FuncOrSelf<MapDispatchToPropsFunction<TDispatchProps, TOwnProps> | MapDispatchToPropsObject>,
    mergeProps?: MergeProps<TStateProps, TDispatchProps, TOwnProps>,
    options?: Options
): ComponentDecorator<TStateProps & TDispatchProps, TOwnProps>;
```

@tkqubo @seansfkelley

**Comment by seansfkelley** [comment]
I'm unsure why there are two overloads (I guess the intention was to make `mapDispatchToProps` mandatory in the second overload?), perhaps @tkqubo knows as he's maintained this longer than I? In any case, it seems like not a useful distinction in practice, and I would be okay combining them into one all-optionals overload. Could you make a PR?
