### ISSUE TITLE
pg-query-stream

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#14658]
- [X] I tried using the `@types/pg-query-stream` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @asmarques

The test file `pg-query-stream-tests.ts` does not compile. Could you see what's happening?

**Comment by asmarques** [comment]
@andy-ms seems `@types/pg@6.1.35` broke the tests due to a change in the return value of `client.query()`. I am working on a patch for `@types/pg` to fix this.

**Comment by paulvanbrenk** [comment]
@asmarques any progress on this?

**Comment by asmarques** [comment]
I have created PR #15351 to address this issue.

@paulvanbrenk I also reverted your change to the pg-query-stream tests, if you pass a `QueryStream` to `client.query()` the result is a modified `QueryStream` which does not implement the promise interface.

**Comment by andy-ms** [comment]
Fixed by  #15351
