### ISSUE TITLE
Lodash toPairs definition

### ISSUE THREAD

**Issue by cosenmarco** [DefinitelyTyped/DefinitelyTyped#14654]
- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel, @chrootsu, @stepancar

My understanding of toPairs is that it (in the typescript parlance) would return an array of tuples where the first element in the tuple is the key (always a string) and the second element is the value.
What's then the rationale behind current interface declaration for toPairs?
```
    interface LoDashStatic {
        toPairs<T extends {}>(object?: T): any[][];
        toPairs<T extends {}, TResult>(object?: T): TResult[][];
    }

    interface LoDashImplicitObjectWrapper<T> {
        toPairs<TResult>(): LoDashImplicitArrayWrapper<TResult[]>;
    }

    interface LoDashExplicitObjectWrapper<T> {
        toPairs<TResult>(): LoDashExplicitArrayWrapper<TResult[]>;
    }
```
I would have expected something like:
```
    interface LoDashStatic {
        toPairs<T extends {}>(object?: T): [string, any][];
        toPairs<T extends {}, TResult>(object?: T): [string, TResult][];
    }

    interface LoDashImplicitObjectWrapper<T> {
        toPairs<TResult>(): LoDashImplicitArrayWrapper<[string, TResult]>;
    }

    interface LoDashExplicitObjectWrapper<T> {
        toPairs<TResult>(): LoDashExplicitArrayWrapper<[string, TResult]>;
    }
```

**Comment by tamird** [comment]
I just ran into the same problem. I think your definition is correct. Care to send a PR, or should I?
