### ISSUE TITLE
@types/isomorphic-fetch duplicate definitions with typesript 2.2

### ISSUE THREAD

**Issue by davidye** [DefinitelyTyped/DefinitelyTyped#14765]
Typescript 2.2 started including fetch in the dom lib. So I'm now getting a bunch of duplicate definition errors when using typescript 2.2 with @types/isomorphic-fetch. Seems like adding a namespace fixes this issue.

**Comment by Prior99** [comment]
Same problem exists for fetch-mock which depends on @types/whatwg-fetch.

**Comment by tkrotoff** [comment]
See also https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14759#issuecomment-281824514
