### ISSUE TITLE
Renaming packages allowed?

### ISSUE THREAD

**Issue by StevenLiekens** [DefinitelyTyped/DefinitelyTyped#14770]
I'm improving the typings for the DataTables plugin for jQuery. The package and its typings can be found here: 
https://www.npmjs.com/package/datatables.net
https://www.npmjs.com/package/@types/jquery.datatables

The contribution guide says to use the package name used in the NPM registry, which the original authors did not do. Can I submit a PR to rename the typings package?

**Comment by andy-ms** [comment]
👍 Rename it as part of your PR. Remind me to `npm deprecate @types/jquery.datatables "'@types/jquery.datatables' is now '@types/datatables.net'.`

**Comment by StevenLiekens** [comment]
Will do. Thanks for the instructions.
