### ISSUE TITLE
WebSocketServer.clients should be a Set<WebSocket> in @types/ws

### ISSUE THREAD

**Issue by hurrikam** [DefinitelyTyped/DefinitelyTyped#14774]
I'm using the latest "ws": "2.1.0" with "@types/ws": "0.0.38".
The type of the class field WebSocketServer.clients in the typings is WebSocket[], where the actual runtime type is Set<WebSocket>.

**Comment by tim-we** [comment]
Seconded. Still holds for `"@types/ws": "0.0.40"`.
Line 129 needs to be changed to `clients: Set<WebSocket>;`.
