### ISSUE TITLE
Definitely typed file for d3 sankey plugin

### ISSUE THREAD

**Issue by ravibha** [DefinitelyTyped/DefinitelyTyped#14797]
Can someone publish a definitelytyped file for d3-sankey plugin?
Here is the link for the plugin
https://github.com/d3/d3-sankey/

I am relatively new to typescript. Otherwise, would have done that myself.

Thanks in advance!

**Comment by tomwanzek** [comment]
I am taking a stab at it.

FYI @gustavderdrache @Ledragon
