### ISSUE TITLE
Leaflet Polygon getLatLngs() has wrong return type

### ISSUE THREAD

**Issue by mikhailshilkov** [DefinitelyTyped/DefinitelyTyped#14809]
- [X] I tried using the `@types/leaflet` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] Authors: @alejo90

At the moment the function `getLatLngs` is defined on `InternalPolyline` class, the base class of `Polyline` and `Polygon`. But it looks like the return type of `Polygon.getLatLngs` is two-dimensional array. Here is is a fragment of implementation code where points are set:

```
_setLatLngs: function (latlngs) {
		Polyline.prototype._setLatLngs.call(this, latlngs);
		if (LineUtil._flat(this._latlngs)) {
			this._latlngs = [this._latlngs];
		}
	},
```

The leaflet documentation http://leafletjs.com/reference-1.0.3.html#polygon doesn't seem to specify this though.

**Comment by kklimczak** [comment]
Did you make PR with your commit?

**Comment by kevinhughes27** [comment]
I just ran into this as well. @mikhailshilkov are you going to open a PR for your changes?

**Comment by mikhailshilkov** [comment]
@kklimczak  @kevinhughes27 I'm not sure why I haven't done that before, but now I'm not using leaflet anymore. Feel free to use my commit to make a PR of your own.

**Comment by kevinhughes27** [comment]
I looked at applying the patch but the types have actually changed since then and I am not familiar enough with writing types to understand what to do. Polyline defines several options for LatLngs but typescript only seems to accept the first one. I am not sure adding the explicit code to the Polygon type is the correct solution. @alejo90 can you weigh in here?

**Comment by alejo90** [comment]
I'll work on it. I just have to investigate what exactly is being returned.
