### ISSUE TITLE
Update leaflet-editable typings to leaflet 1.0

### ISSUE THREAD

**Issue by mikhailshilkov** [DefinitelyTyped/DefinitelyTyped#14814]
- [X] I tried using the `@types/leaflet-editable` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] Authors: @dalie

Update leaflet-editable typings to be compatible to `leaflet 1.0` definition. If needed, keep the old version under `v0` folder (same what `leaflet` did).

Current problems that I see:

```
leaflet-editable\index.d.ts(46,25): error TS2315: Type 'LayerGroup' is not generic.
leaflet-editable\index.d.ts(90,39): error TS2503: Cannot find namespace 'Mixin'.
```

**Comment by AdamVig** [comment]
@mikhailshilkov With b5eaa88e9effe4eebf076951217bdaf3be861721, it looks like this has been taken care of.

**Comment by PabbleDabble** [comment]
It looks like @types/leaflet-editable has a dependencies of "@types/leaflet": { "version": "0.7.33"... which is causing the issue for me.  If I delete the node_modules folder within src/node_modules/@types/leaflet-editable this solves most of my problems.  

Is there a simple way to update @types/leaflet-editable to require ^0.7.33 or "*" instead?

**Comment by liudas-stonys** [comment]
Did anyone find solution for this? (feelingHopeful)

**Comment by PabbleDabble** [comment]
@liudas-stonys Heya, here's my current 'hack' to get this working.  
* install @types/leaflet-editable using npm
* this will install @types/leaflet@0.7.33 - This is the main issue as far as I can see as I get errors during my npm/build process as I'm using Leaflet 1.0+
* I copied the leaflet-editable folder from the src/node_modules/@types folder (removing the @types/leaflet folder contained within that folder) and sourced it locally in my project's typing folder and updated my tsconfig.json to include this
* I then removed the npm install of @types/leaflet-editable

I know this isn't ideal, but I don't know enough about definitely typed to submit a PR, but I think the real fix would be for someone with a bit more know-how to submit a PR to definitely-typed to update leaflet-editable to rely on @types/leaflet differently.  That last statement might be possibly naive though.

**Comment by MrKartoshka** [comment]
No info about this update?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
