### ISSUE TITLE
jointjs: Declare and export module

### ISSUE THREAD

**Issue by StephenRUK** [DefinitelyTyped/DefinitelyTyped#14815]
- [X] I tried using the `@types/jointjs` package and had problems.
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT @ChrisMoran et al.

Currently I am not able to import JointJS correctly with TypeScript and had to resort to using the (typeless) JavaScript require syntax. Despite reading the TS modules docs & more, I'm by no means a TS expert...but shouldn't the definitions file define and export a module, so it can actually be loaded?

* tsconfig.json: Node package resolution, CommonJS modules.
* Failing statement: `import * as joint from 'jointjs';`
* Also fails: `import joint = require('jointjs');`
* Error in VS Code: **'File ...../node_modules/@types/jointjs/index.d.ts is not a module'**

IMO one way to solve this would be to add following module declaration:

`declare module "jointjs" {
  export = joint;
}`

If I'm doing something completely wrong here, do let me know. Otherwise could you please update the definitions as suggested? Cheers for your feedback!

**Comment by CaselIT** [comment]
The pr should fix this problem

**Comment by StephenRUK** [comment]
Thanks for your swift action @CaselIT , much appreciated!
