### ISSUE TITLE
@types/webappsec-credential-management errors with typescript@2.2.1

### ISSUE THREAD

**Issue by yurlovm** [DefinitelyTyped/DefinitelyTyped#14854]
- [X] I tried using the `@types/webappsec-credential-management` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] [Mention]
  - Authors: @iainmcgin

I got lots of errors with  typescript@2.2.1

ERROR in [at-loader] node_modules\@types\webappsec-credential-management\index.d.ts:82:15
    TS2300: Duplicate identifier 'URLSearchParams'.

ERROR in [at-loader] node_modules\@types\whatwg-fetch\index.d.ts:11:13
    TS2451: Cannot redeclare block-scoped variable 'fetch'.

ERROR in [at-loader] node_modules\@types\whatwg-fetch\index.d.ts:13:14
    TS2300: Duplicate identifier 'HeadersInit'.

ERROR in [at-loader] node_modules\@types\whatwg-fetch\index.d.ts:14:15
    TS2300: Duplicate identifier 'Headers'.

ERROR in [at-loader] node_modules\@types\whatwg-fetch\index.d.ts:31:14
    TS2300: Duplicate identifier 'BodyInit'.

ERROR in [at-loader] node_modules\@types\whatwg-fetch\index.d.ts:43:14
    TS2300: Duplicate identifier 'RequestInfo'.

ERROR in [at-loader] node_modules\@types\whatwg-fetch\index.d.ts:44:15
    TS2300: Duplicate identifier 'Request'.

ERROR in [at-loader] node_modules\@types\whatwg-fetch\index.d.ts:64:11
    TS2300: Duplicate identifier 'Request'.

ERROR in [at-loader] node_modules\@types\whatwg-fetch\index.d.ts:88:15
    TS2300: Duplicate identifier 'Response'.

ERROR in [at-loader] node_modules\@types\whatwg-fetch\index.d.ts:107:11
    TS2300: Duplicate identifier 'Response'.

ERROR in [at-loader] node_modules\@types\whatwg-streams\index.d.ts:32:15
    TS2300: Duplicate identifier 'ReadableStream'.

ERROR in [at-loader] node_modules\typescript\lib\lib.dom.d.ts:6945:11
    TS2300: Duplicate identifier 'Headers'.

ERROR in [at-loader] node_modules\typescript\lib\lib.dom.d.ts:6954:13
    TS2300: Duplicate identifier 'Headers'.

ERROR in [at-loader] node_modules\typescript\lib\lib.dom.d.ts:9321:11
    TS2300: Duplicate identifier 'ReadableStream'.

ERROR in [at-loader] node_modules\typescript\lib\lib.dom.d.ts:9327:13
    TS2300: Duplicate identifier 'ReadableStream'.

ERROR in [at-loader] node_modules\typescript\lib\lib.dom.d.ts:9343:11
    TS2300: Duplicate identifier 'Request'.

ERROR in [at-loader] node_modules\typescript\lib\lib.dom.d.ts:9360:13
    TS2300: Duplicate identifier 'Request'.

ERROR in [at-loader] node_modules\typescript\lib\lib.dom.d.ts:9365:11
    TS2300: Duplicate identifier 'Response'.

ERROR in [at-loader] node_modules\typescript\lib\lib.dom.d.ts:9376:13
    TS2300: Duplicate identifier 'Response'.

ERROR in [at-loader] node_modules\typescript\lib\lib.dom.d.ts:13858:11
    TS2300: Duplicate identifier 'URLSearchParams'.

ERROR in [at-loader] node_modules\typescript\lib\lib.dom.d.ts:13885:13
    TS2300: Duplicate identifier 'URLSearchParams'.

ERROR in [at-loader] node_modules\typescript\lib\lib.dom.d.ts:14893:18
    TS2451: Cannot redeclare block-scoped variable 'fetch'.

ERROR in [at-loader] node_modules\typescript\lib\lib.dom.d.ts:14898:6
    TS2300: Duplicate identifier 'BodyInit'.

ERROR in [at-loader] node_modules\typescript\lib\lib.dom.d.ts:14919:6
    TS2300: Duplicate identifier 'HeadersInit'.

ERROR in [at-loader] node_modules\typescript\lib\lib.dom.d.ts:14929:6
    TS2300: Duplicate identifier 'RequestInfo'.

**Comment by iainmcgin** [comment]
I'm working on resolving this, see #14837.

**Comment by yurlovm** [comment]
Thank you very much!
