### ISSUE TITLE
[@types/heremaps] Error when strictNullChecks is true

### ISSUE THREAD

**Issue by jpchip** [DefinitelyTyped/DefinitelyTyped#14851]
- [ X] I tried using the `@types/xxxx` package and had problems.
- [X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Josh-ES 

When compiling with strictNullChecks set to true, I get the following errors:

```
Error:(4462, 17) TS2411:Property 'normal' of type 'MapType | undefined' is not assignable to string index type 'MapType'.
Error:(4463, 17) TS2411:Property 'satellite' of type 'MapType | undefined' is not assignable to string index type 'MapType'.
Error:(4464, 17) TS2411:Property 'terrain' of type 'MapType | undefined' is not assignable to string index type 'MapType'.
```

The code in question is this interface:

```
export interface MapTypes {
                normal?: H.service.MapType;
                satellite?: H.service.MapType;
                terrain?: H.service.MapType;
                [key: string]: H.service.MapType;
            }
```

Looking at the [Here Map docs](https://developer.here.com/javascript-apis/documentation/v3/maps/topics_api/h-service-platform.html#h-service-platform__createdefaultlayers), it appears that normal, satellite, and terrain are always included in the default map types, so maybe can make them not optional to resolve this issue?

**Comment by Josh-ES** [comment]
@jpchip Apologies for how long it's taken me to respond to this, I've not been able to respond to open source work over the last six months or so. Some changes to the type definitions have just gone through which update the MapTypes interface and introduce a new DefaultTypes interface. If you manage a look at the new version, can you let me know if this is still a problem?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
