### ISSUE TITLE
isomorphic-fetch.d.ts fails with latest typescript

### ISSUE THREAD

**Issue by KnisterPeter** [DefinitelyTyped/DefinitelyTyped#14889]
- [x] I tried using the `@types/isomorphic-fetch` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Since DefinitelyTyped#14796 my project https://github.com/KnisterPeter/pretend/pull/122 fails (https://travis-ci.org/KnisterPeter/pretend/jobs/204695315) with the error message which should be worked around.
@mhegazy can you have look or give me a hint what to do?

**Comment by garbles** [comment]
@KnisterPeter this work around fixed the issue for me for now https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16002

**Comment by KnisterPeter** [comment]
Pretend does not fail anymore
