### ISSUE TITLE
ReactDOM: Argument of type 'Node | null' is not assignable to parameter of type 'Element'.

### ISSUE THREAD

**Issue by monolithed** [DefinitelyTyped/DefinitelyTyped#14926]
```ts
let { parentNode } = ReactDOM.findDOMNode(this);

ReactDOM.unmountComponentAtNode(parentNode);
```

```
Argument of type 'Node | null' is not assignable to parameter of type 'Element'.
```

![img-2017-03-01-00-34-12](https://cloud.githubusercontent.com/assets/803674/23434787/56ed845c-fe17-11e6-86f4-757ea5c32863.png)

- [x] I tried using the `@types/react-dom` package and had problems.
- [x] I tried using the latest stable version of tsc.

**Comment by MartynasZilinskas** [comment]
Hey, you can't unmount element that is `null` or `undefined`.

**Comment by monolithed** [comment]
Yep, I forgot to close this issue.
