### ISSUE TITLE
react-icons generate script

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#14921]
- [X] I tried using the `@types/react-icons` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @apare

Could you provide the build script you used to generate `react-icons`, or at least the data source you used?

**Comment by apare** [comment]
@andy-ms Sorry for the delay... Here is the gist.
https://gist.github.com/apare/33a0d9218c3c1159c7cc127ee85b693d
