### ISSUE TITLE
@types/xlsx bug: Wrong signature for write() function.

### ISSUE THREAD

**Issue by StasD** [DefinitelyTyped/DefinitelyTyped#14974]
- [x] I tried using the `@types/xlsx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @themauveavenger

The @types/xlsx project uses the following signature for the write() function:
`export declare function write(data: any, opts?: IParsingOptions): any;`

Note that the opts parameter has the same type as one in the read() function:
`export declare function read(data: any, opts?: IParsingOptions): IWorkBook;`

Which is WRONG:
https://github.com/SheetJS/js-xlsx#writing-options

Now I'm getting errors when I try to pass an options object with e.g. `bookSST` property...

Originally I posted this here: https://github.com/DxCx/ts-xlsx/issues/10

**Comment by DxCx** [comment]
@StasD i believe you can close this one
