### ISSUE TITLE
D3 Minor Version 4.7

### ISSUE THREAD

**Issue by tomwanzek** [DefinitelyTyped/DefinitelyTyped#15054]
@Ledragon I will tackle this minor version update. Will ping you on the PR when submitted.

cc @gustavderdrache

**Comment by tomwanzek** [comment]
Updated title to reflect full scope of changes related to D3 minor version 4.7:
- [ ] d3-geo 1.6
- [ ] d3-array 1.1
- [ ] d3-format 1.1

**Comment by Ledragon** [comment]
PR reviewed, up for merge on my side.
