### ISSUE TITLE
[oauth2orize] grant missing from server

### ISSUE THREAD

**Issue by stevehipwell** [DefinitelyTyped/DefinitelyTyped#15076]
I tried using the `@types/oauth2orize` package and had problems as the server is missing the grant function and grant object. I am using the latest tsc (2.2.1).

@wokim @heycalmdown

**Comment by heycalmdown** [comment]
Okay it is missing. I'll update it at this weekend, but also you can PR me before weekend.

**Comment by stevehipwell** [comment]
I've created a pull request.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15284
