### ISSUE TITLE
Remove duplicate content 

### ISSUE THREAD

**Issue by birkskyum** [DefinitelyTyped/DefinitelyTyped#15071]
@birkskyum: About duplicate content. I think the Accounts module nested in meteor/accounts-base is necessary, in order to match the javascript, but can the global Accounts module be removed?

@fullflavedave: It would be great to remove all the duplication. This was created when Meteor added support for ES2015 modules (the global modules were the original). Does Meteor 1.4 still support global modules (e.g. for super quick prototyping)? If so, then the global module definitions probably need to be there for backwards compatibility. However, it would be great if the global Accounts module and the one nested in meteor/accounts-base referenced one set of definitions (and all other modules too). My TypeScript skills are a little out-dated, and I haven't fooled around to see if it's possible -- want to give it a try @birkskyum? Let's add a separate issue and continue discussion there.

@birkskyum: Sure, I'll have a look at it.

**Comment by birkskyum** [comment]
@fullflavedave, Meteor 1.4 still support all these global modules. I think the right way forward for Meteor would be to stop doing that, and let the type definitions encourage to using a proper import statement.

That said, It's not a change I know how to make because other libraries inside of DefinitelyTyped depends on the Meteor globals and they all break if I remove them... And it causes the check to fail: #15079 .

**Comment by fullflavedave** [comment]
@birkskyum OK -- thanks for trying.  I guess we will just have to wait for Meteor to stop supporting them.  I guess that won't happen until Meteor 2.0!

**Comment by mattmccutchen** [comment]
I'm preparing to propose some changes to the Meteor typings, and I would be interested in addressing the duplication first if possible.  [Here](https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...mattmccutchen:meteor-dedup) is one potential approach in which the external modules are primary and the globals are aliased.  (This would get a little less ugly if Microsoft/TypeScript#14051 were implemented.)  It's also possible to do it the other way around.  The drawback of any change of this nature is that it breaks any code that was augmenting the definitions that are now aliased: such code will have to be changed to augment the primary definitions, but it can still use the augmentations via the aliases (as demonstrated in the meteor-tests-global.ts file).  Another option is to use a script to generate the two copies from one, like [this](https://github.com/meteor-typings/meteor/blob/09ef92da99549ac090603ce70cfa632db4fad6e7/gulpfile.js#L43).  Meteor typings owners, would you like to go forward with either approach?  If so, I will put together a pull request.

cc: @barbatus @fullflavedave @orefalo @dagatsoin @birkskyum @ardatan @stefanholzapfel @andrei-markeev

**Comment by ardatan** [comment]
And, I think global references of ‘check’ and ‘Match’ has to be removed because they’re not global like others.

**Comment by mattmccutchen** [comment]
> I think global typings of ‘check’ and ‘Match’ has to be removed because they’re not global like others.

What evidence do you base this statement on?  [My application](https://bitbucket.org/espalier-spreadsheet/espalier/src/cff61cf664b4223aa90170eeea26842839864026/src/server/model.ts?at=master&fileviewer=file-view-default#model.ts-556) is using them as global and it seems to work.

**Comment by ardatan** [comment]
@mattmccutchen 
You can see they're not global, just exported.
https://github.com/meteor/meteor/blob/devel/packages/check/match.js

**Comment by mattmccutchen** [comment]
@ardatan How do you conclude they are not global?  As I said, my application uses them as globals and it works.  If you don't believe me, you can go to the [public instance](http://espalier-demo.csail.mit.edu/) and type `check` and `Match` in the developer console.  I traced through the Meteor tool code (due to the dearth of detailed documentation :frowning_face:), and it appears that exports of a Meteor package can indeed be defined as either ES6 exports of the main module specified in package.js (as in the case of the `check` package) or "global" variable assignments.  Near the bottom of `.meteor/local/build/programs/server/packages/check.js` in my application, there is:

```js
var exports = require("/node_modules/meteor/check/match.js");

/* Exports */
Package._define("check", exports, {
  check: check,
  Match: Match
});
```

This calls the `Package._define` helper defined [here](https://github.com/meteor/meteor/blob/aba03743ada9136138265d661e31b5aee9269058/packages/meteor/define-package.js#L9).  The code I quoted is generated [here](https://github.com/meteor/meteor/blob/aba03743ada9136138265d661e31b5aee9269058/tools/isobuild/linker.js#L437) and [here](https://github.com/meteor/meteor/blob/aba03743ada9136138265d661e31b5aee9269058/tools/isobuild/linker.js#L954).

**Comment by ardatan** [comment]
BTW, I mean server-side not client side :) I had many problems because of these global typings. The only thing you have to do is running `meteor shell`, and try it.

**Comment by ardatan** [comment]
```
Mac:backend ardatan$ meteor shell
Welcome to the server-side interactive shell!

Tab completion is enabled for global variables.

Type .reload to restart the server and the shell.
Type .exit to disconnect from the server and leave the shell.
Type .help for additional help.

> check
ReferenceError: check is not defined
    at evalCommandPromise.then (packages/shell-server/shell-server.js:246:21)
    at runBound (domain.js:314:12)
    at bound (domain.js:301:14)
    at defaultEval (repl.js:240:29)
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at repl:1:-61
> Match
ReferenceError: Match is not defined
    at evalCommandPromise.then (packages/shell-server/shell-server.js:246:21)
    at runBound (domain.js:314:12)
    at bound (domain.js:301:14)
    at defaultEval (repl.js:240:29)
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at repl:1:-61
>

```

**Comment by mattmccutchen** [comment]
Perhaps your application does not have a direct dependency on the `check` Meteor package?  If you give me a pointer to the source code, I can try to reproduce the behavior and investigate.

**Comment by mattmccutchen** [comment]
I'm still interested in feedback from the Meteor typings owners on possible approaches to remove the duplication, but I went ahead to prepare a PR to start the YSYL clock ticking.  After seeing how many of the Meteor typing packages in DefinitelyTyped alone augment the global typings of core Meteor, I was convinced that breaking that was a bad idea, so I'm now proposing the second approach, of using a script to generate one copy of the typings from the other.  The new PR is #28064.
