### ISSUE TITLE
TS2304 in @types/node^7.0.7

### ISSUE THREAD

**Issue by ryansmith94** [DefinitelyTyped/DefinitelyTyped#15083]
I tried using the `@types/node^7.0.7` package and had problems when running TSC in a [Travis build](https://travis-ci.org/ryansmith94/rulr/builds/209181447) (see log below).

```
node_modules/@types/node/index.d.ts(1841,45): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/node/index.d.ts(1845,20): error TS2304: Cannot find name 'Iterator'.
node_modules/@types/node/index.d.ts(1850,17): error TS2304: Cannot find name 'Iterator'.
node_modules/@types/node/index.d.ts(1854,19): error TS2304: Cannot find name 'Iterator'.
node_modules/@types/node/index.d.ts(1855,10): error TS2304: Cannot find name 'Symbol'.
node_modules/@types/node/index.d.ts(1855,30): error TS2304: Cannot find name 'Iterator'.
```

**Comment by r00ger** [comment]
Please rever thttps://github.com/DefinitelyTyped/DefinitelyTyped/commit/f9115ebc7e3c8c45c891cf826466d9c8d5483725#diff-57a6a827ef2d97c71215082dc2acbf01

**Comment by r00ger** [comment]
@minestarks

**Comment by mhegazy** [comment]
if you are using `node@7` it seems fair to expect `ES6` features to be present. recommendations here is either add `es6` to your `--lib`, or use `node@6`.

**Comment by ryansmith94** [comment]
Nice thanks @mhegazy, I'll try adding that.

**Comment by ryansmith94** [comment]
That works thanks again @mhegazy! 👍
