### ISSUE TITLE
node_modules/@types/jasmine/index.d.ts(39,52): error TS1005: '=' expected.

### ISSUE THREAD

**Issue by kaleemullah360** [DefinitelyTyped/DefinitelyTyped#15081]
- [ ] I tried using the `@types/jasmine` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] Error: node_modules/@types/jasmine/index.d.ts(39,52): error TS1005: '=' expected.
- [ ] Solution replace this package with older stable version. last known good package
- [ ] when will the error fixed, cause I encounter it more than once

**Comment by knostradamus** [comment]
We rolled back to a stable line: (In case anyone needed this)
change line 39 to 
declare function spyOn(object: any, method: string): jasmine.Spy;

**Comment by wcainboundary** [comment]
Seeing a variant of this with 3 closely located problems, in @types/jasmine 2.5.42 and 2.5.43:
```
ERROR in [default] node_modules/@types/jasmine/index.d.ts:39:37 
A parameter initializer is only allowed in a function or constructor implementation.
ERROR in [default] node_modules/@types/jasmine/index.d.ts:39:45 
Cannot find name 'keyof'.
ERROR in [default] node_modules/@types/jasmine/index.d.ts:39:51 
'=' expected.
```

**Comment by oltur** [comment]
Thank you, it helped me with the same fix in line 41

**Comment by andy-ms** [comment]
Jasmine needs a minumum TypeScript version of 2.1. Dup of #14569.
