### ISSUE TITLE
Handsontable export seems to be wrong

### ISSUE THREAD

**Issue by adamk33n3r** [DefinitelyTyped/DefinitelyTyped#15090]
- [x] I tried using the `@types/handsontable` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @swistach

The type def says that the module exports a named object called `Handsontable` that is a constructor. This is not true. Handsontable exports a function.

The typing requires me to do
```
import { Handsontable } from 'handsontable';
const hot = new Handsontable();
```
but I need to be able to do
```
import * as Handsontable from 'handsontable';
const hot = Handsontable();
```

**Comment by panesofglass** [comment]
I'm in the same boat. I am trying to modify them to work [here](https://github.com/panesofglass/hottest/blob/master/src/handsontable.d.ts), though I'm not having much luck.

**Comment by panesofglass** [comment]
I was able to fix the definition file by taking some cues from the `jquery.d.ts`. One thing I could not resolve was using a `class Handsontable { constructor(...) { ... } }` rather than an `interface Handsontable { new(...): ... }`. While that is considered a "common mistake", I found the use of class prevented things from working properly.

**Comment by panesofglass** [comment]
Looks like handsontable is planning to update the definition file in their repository here https://github.com/handsontable/handsontable/issues/4112.

**Comment by adamk33n3r** [comment]
Oh cool! Thanks.

**Comment by panesofglass** [comment]
@adamk33n3r check out the referenced PR for an updated `handsontable.d.ts`. I don't see any progress in the handsontable repo yet.
