### ISSUE TITLE
@types/async es6 generators

### ISSUE THREAD

**Issue by ddwwcruz** [DefinitelyTyped/DefinitelyTyped#15117]
- [x] I tried using the `@types/async` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Collection functions should be able to accept generators. The code works fine on plain js but won't compile in ts.

**Comment by andy-ms** [comment]
Try [testing](https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute) changes to the types to see what works, then make a pull request.
