### ISSUE TITLE
Build Errors in visual Studion

### ISSUE THREAD

**Issue by JinnaBalu** [DefinitelyTyped/DefinitelyTyped#15131]
there are lot errors like this 
Error	TS1005	Build:';' expected.	
Error	TS1109	Build:Expression expected.
Error	TS1128	Build:Declaration or statement expected.
Error	TS1138	Build:Parameter declaration expected.	

tsconfig.json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "moduleResolution":  "node",
        "removeComments": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "noEmitHelpers": false,
        "sourceMap": true
    },
    "exclude": [
        "node_modules"
    ],
    "compileOnSave": false,
    "buildOnSave": false
}

package.json 

{
  "name": "Talon3",
  "version": "1.0.0",
  "description": "",
  "main": "wwwroot/index.html",
  "author": "Derek A Scott",
  "license": "ISC",
  "dependencies": {
    "@angular/common":                    "~2.2.4",
    "@angular/compiler":                  "~2.2.4",
    "@angular/compiler-cli":              "~2.2.4",
    "@angular/core":                      "~2.2.4",
    "@angular/forms":                     "~2.2.4",
    "@angular/http":                      "~2.2.4",
    "@angular/upgrade":                   "~2.2.4",
    "@angular/platform-browser":          "~2.2.4",
    "@angular/platform-browser-dynamic":  "~2.2.4",
    "@angular/material": "2.0.0-alpha.9-3",
    "@angular/router": "~3.1.0",
    "bootstrap": "3.3.7",

    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.9",
    "rxjs": "^5.0.3",
    "systemjs": "^0.19.41",
    "zone.js": "^0.7.4",

    "expose-loader": "^0.7.1",
    "jquery": "^3.1.1",
    "jquery-ui": "^1.12.1",
    "jquery-ui-sortable": "1.0.0",
    "jquery.caret": "0.3.1",
    "lodash": "^4.17.4",
    "messageformat": "^1.0.2",
    "moment": "^2.17.1",
    "moment-timezone": "^0.5.11",
    "ng2-bootstrap": "^1.1.5",

    "karma-requirejs": "^1.1.0",

    "ng2-bs3-modal": "^0.10.4",
    "ng2-dnd": "^2.1.1",
    "ng2-material": "^0.8.1",
    "ng2-redux": "^5.1.0",
    "ng2-select": "^1.1.2",
    "ng2-translate": "^5.0.0",
    "opn": "^4.0.2",
    "redux": "^3.6.0",
    "redux-localstorage": "^0.4.1",
    "redux-logger": "^2.7.4",
    
    "signalr": "^2.2.1",
    "tassign": "^1.0.0",
    "toastr": "^2.1.2"
    
  },
  "devDependencies": {
    "@types/signalr": "^2.2.32",
    "@types/toastr": "^2.1.30",
    "concurrently": "^3.1.0",
    "css-loader": "^0.26.1",
    "del": "latest",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "gulp": "latest",
    "gulp-concat": "^2.6.1",
    "gulp-inject": "^4.2.0",
    "gulp-minify-css": "^1.2.4",
    "gulp-symdest": "^1.1.0",
    "gulp-task-listing": "^1.0.1",
    "gulp-uglify": "^2.0.0",
    "gulp-sourcemaps": "latest",
    "gulp-tslint": "latest",

    "html-loader": "^0.4.4",
    "html-webpack-plugin": "^2.26.0",
    "image-webpack-loader": "^3.1.0",

    "jasmine-core": "latest",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "latest",
    "karma-coverage": "latest",
    "karma-jasmine": "latest",
    "karma-mocha-reporter": "latest",
    "karma-phantomjs2-launcher": "latest",
    "karma-story-reporter": "latest",

    "lite-server": "latest",
    "null-loader": "^0.1.1",
    "path": "latest",

    "phantomjs2": "latest",
    "require-dir": "latest",
    "systemjs-builder": "latest",
    "tslint": "latest",
    "typescript": "latest",

    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.4",
    "run-sequence": "^1.2.2",
    "shelljs": "^0.7.6",
    "style-loader": "^0.13.1",
    "ts-loader": "^1.3.3",

    "typings": "^2.1.0",
    "webpack": "^1.14.0",
    "webpack-dev-server": "^1.16.2",
    "webpack-merge": "^2.3.1",
    "webpack-stream": "^3.2.0"
  },
  "scripts": {
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings",
    "lite": "lite-server",
    "buildGulp": "gulp build:web:dev",
    "test": "karma start karma.conf.js",
    "webpackDevServer": "webpack-dev-server --inline --progress --port 8080 --content-base ./wwwroot/",
    "dev_start": "tsc && npm install && npm run buildGulp && concurrently \"tsc -w\" \"dotnet run\" \"npm run webpackDevServer\"",
    "start": "tsc && npm install && concurrently \"tsc -w\" \"lite-server\""
  }
}

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
