### ISSUE TITLE
angular-ui-bootstrap IModalServiceInstance should be IModaInstanceService

### ISSUE THREAD

**Issue by damianog** [DefinitelyTyped/DefinitelyTyped#15142]
Hi @xt0rted and @ry8806 

I'am using the `@types/angular-ui-bootstrap` and I think that for convention IModalServiceInstance should be renamed in IModaInstanceService

Thi is only a "cosmetic" and "mnemonic" issue.

**Comment by ry8806** [comment]
I agree,
in AngularJS, the "type of dependancy" (i.e. Service, Factory etc) are all at the end of the name

It would also align with "IModalStackService "

Could you submit a PR?

**Comment by damianog** [comment]
Hi @ry8806 

I renamed IModalServiceInstance and added it as deprecated extension of IModalInstanceService with #a217b4a

**Comment by ry8806** [comment]
looks good, thanks 😄

**Comment by damianog** [comment]
Hi @xt0rted and @ry8806 

when it will be merged?

Thanks

**Comment by ry8806** [comment]
@damianog not too sure, that is down to the Mods on the repo

I don't have permissions to do merges etc

**Comment by xt0rted** [comment]
#15156 has been merged
