### ISSUE TITLE
mysql2 definition

### ISSUE THREAD

**Issue by elaith9** [DefinitelyTyped/DefinitelyTyped#15157]
Is mysql2 definition available? Cant find it on search.

**Comment by ndxbn** [comment]
+1

**Comment by chinthakagodawita** [comment]
For anyone else that ends up here, you can find them at [types/mysql2](https://github.com/types/mysql2).

Or:
* `yarn add --dev types/mysql2`
* `npm install --save-dev types/mysql2`
