### ISSUE TITLE
@types/dockerode needs update

### ISSUE THREAD

**Issue by nlaplante** [DefinitelyTyped/DefinitelyTyped#15171]
- [x] I tried using the `@types/dockerode` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Seikho 

@types/dockerode is missing new methods found in latest version of dockerode [2.41](https://github.com/apocas/dockerode/releases/tag/v2.4.1). For example:

- `Docker.pruneImages`
- `Docker.pruneContainers`

Please add missing methods and types.

**Comment by AlexanderLangguth** [comment]
It is also missing the declarations for the promise based interface.
For example:
```
declare class Dockerode {
    listContainers(options?: {}): Promise<Dockerode.ContainerInfo[]>;
}
```
