### ISSUE TITLE
Issue in @types/c3

### ISSUE THREAD

**Issue by jpchip** [DefinitelyTyped/DefinitelyTyped#15211]
- [x] I tried using the `@types/c3` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mcliment

[line.step_type](http://c3js.org/reference.html#line-step_type) is incorrectly implemented in ChartConfiguration interface. Right now it is:

```
line?: {
            /**
             * Set if null data point will be connected or not.
             * If true set, the region of null data will be connected without any data point. If false set, the region of null data will not be connected and get empty.
             */
            connectNull?: boolean;
            /**
             * Change step type for step chart. 'step', 'step-before' and 'step-after' can be used.
             */
            step_type?: string;
        };
```

But it should be:

```
line?: {
            /**
             * Set if null data point will be connected or not.
             * If true set, the region of null data will be connected without any data point. If false set, the region of null data will not be connected and get empty.
             */
            connectNull?: boolean;
            step?: {
                 /**
                 * Change step type for step chart. 'step', 'step-before' and 'step-after' can be used.
                 */
                 type: string;
             };
        };

**Comment by mcliment** [comment]
Looks correct, can you make a PR?
