### ISSUE TITLE
@types/lodash-es - doesn't match shape of the lodash-es code files

### ISSUE THREAD

**Issue by kylecordes** [DefinitelyTyped/DefinitelyTyped#15227]
- [X] I tried using the `@types/lodash-es` package and had problems.

@stephenlautier

 I'm working with a somewhat unusual build stack (typescript, Closure Compiler) consuming among many things, `lodash-es` and `@types/lodash-es`.

I'm having trouble, because the "shape" of the types does not match that of the actual files. You can see the lodash-es files here:

https://unpkg.com/lodash-es@4.17.4/

The package spec points to lodash.js, and it points to a bunch of files, for example fill.js.

However, over in `@types/lodash-es`, the index points to './sortBy', which is a directory, containing a file './sortBy/index.d.ts'.

This inspires TypeScript to emit import statements like:

```
import sortBy from 'lodash-es/sortBy/index';
```

I'm trying to figure out why this is, and why the types do not match the "shape" (a bunch of files all in the same directory) of code they provide types for. If they did, TypeScript would produce output matching those files.

Incidentally, using a different build stack (rollup and plug-ins) I can persuade rollup to tolerate this incorrect output from TypeScript caused by the (as far as I can tell) incorrect types, and produce output anyway.  But it seems to me that this is one clever tool making up for unusual or perhaps incorrect output from another tool?

**Comment by stephenlautier** [comment]
@kylecordes 

pretty much I did these types and tested with rollup, and I have no experience using closure.
What I wanted to achieve is to have the following syntax work and treeshaked e.g.

```ts
import kebabCase from "lodash-es/kebabCase";
const wings = kebabCase("chickenWings");
```

I believe you are referring to the subfolders when saying do not match the "shape", right?
That was specifically done to simply match the typing import to be treeshaked properly.

With rollup you can also use the following syntax

```ts
import { kebabCase } from "lodash-es";
const wings = kebabCase("chickenWings");
```
However this doesn't get treeshaked (I would prefer this syntax instead).

If you would like to create a PR to change this feel free, not sure how you have it in mind though. If we can get it working for more bundlers such as Closure as you need it would be even better.

**Comment by kylecordes** [comment]
With older tools and module systems (CommonJS), you to "manually tree shake" by splitting code into many modules the import only the module you need, like so:

```
import kebabCase from "lodash-es/kebabCase";
```

However, using such a feature is not what is usually meant by "tree shaking". Instead this is the way things worked all the way back to the first bundling tools in the node ecosystem. There is no need for "-es" modules, with this approach - it already works fine this way the old way, CommonJS.

Tree shaking is the newer innovation, it is essentially the entire reason Rollup exists. Tree shaking means that the bundling tool understands the module system (and that the modules are "static", so they can be statically analyzed, unlike CommonJS). The bundling tool can follow the imports inside and through modules, and include only the relevant code.

As you said, the best syntax to consume the library is this:

```
import { kebabCase } from "lodash-es";
```

In a sense, the reason why the -es packaging exists is to make it possible to consume lodash this way, using a modern tool stack where such consumption works fine with tree shaking.

The interesting thing is that the first syntax works at all. It's not a convenient way to consider lodash (-es), It doesn't match the actual shape of the library, but some of the tooling can consume it anyway.

Is there some tooling to help automatically create these types? Or is it necessary to put them together by hand, file by file?

**Comment by stephenlautier** [comment]
True, its actually cherry picking not treeshake, in this case as you mentioned.

What i had done is a powershell script which copy and manipulates files from lodash typings. If you want i can try and help you, do 1 file with the changes as you suggest and i can try doing the same for the rest.

**Comment by kylecordes** [comment]
Unfortunately I have little time over the next week, though if I have an opportunity I will do as you say and try it myself. But, here is what I had in mind:

There is currently a file `lodash-es/add/index.d.ts`.

Move and rename this file to `lodash-es/add.d.ts`.

Repeat for all the other types.

Rename the file `lodash-es/index.d.ts` to `lodash-es/lodash.d.ts`.

Add a new `lodash-es/index.d.ts` which re-exports everything from `lodash-es/lodash.d.ts`.

In this way, the relatives names and paths of the types will match the names and paths of the contents of the lodash-es package. So that when the compilation stack uses the types to figure out what code to emit, it will emit code that matches the library JavaScript code.

I believe this would then still work exactly as it does now with bundlers that handle the various CommonJS special cases (in which it automatically translates between the name of a file and the name of the directory containing an index file). Yet it would also work with bundlers that expect the types to match the files without such translation.

**Comment by kylecordes** [comment]
(The interesting thing here is that performing the type manipulations is probably just a few minutes of shell hackery. The time-consuming part is trading at proper test harness, which would be an application that uses several of lodash operators, via lodash-es, via the desired import syntax. Then performs bundling using several common tools to verify runtime results with all of them.  The test harness is probably five times as much tedious irritating work as the core work itself!)

**Comment by e-cloud** [comment]
I am working on developing a library - [ng2-permission](https://github.com/e-cloud/ng2-permission). And it depends on `@types/lodash-es`.

Now with `rollup` and `@angular/compiler`, it will be bundled into a single file library. However, i generates the wrong reference to the real `lodash-es` library.

```ts
//...
import { each, isFunction, isNil } from 'lodash-es/index'; // see here
//...
```

The thing is, if I uninstall `@types/lodash-es`, it can generate right reference like this:

```ts
//...
import { each, isFunction, isNil } from 'lodash-es'; // see here
//...
```

I think it's related to the structure of current typings.

**Comment by e-cloud** [comment]
@andy-ms this issue may be tagged as bug

**Comment by stephenlautier** [comment]
@andy-ms I had generated these using a PowerShell script (not a sophisticated one), rather than do them as a monkey

**Comment by andy-ms** [comment]
I am just wondering, can we re-use `lodash/scripts/generate-modules.ts` and just change `export =` to `export default`?

**Comment by stephenlautier** [comment]
ahh I wasnt aware of that script, most probably yes we can use it, because i had something similarish e.g. go through all files and modify the output slightly, so i think it should work

**Comment by e-cloud** [comment]
It's a funny that i also issue a PR to fix this. @andy-ms your fixed version have to manually update the functions list, my version will retrieve it from net.

**Comment by ringvold** [comment]
Awesome that a fix has been merged! I have had the same problems recently myself.
When can we expect a release with these changes?

**Comment by ringvold** [comment]
Awesome that this have been fixed! Thank you so much! :tada:
