### ISSUE TITLE
@types/node`s Array is missing includes()

### ISSUE THREAD

**Issue by mx601595686** [DefinitelyTyped/DefinitelyTyped#15238]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- Authors: @andy-ms

[Array.prototype.includes()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) is missing in `@types/node`.
And this is not a experiment method.

**Comment by andy-ms** [comment]
`@types/node` is just responsible for node.js types, not for all of JavaScript. Try setting [`--lib`](http://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by mx601595686** [comment]
oh. thanks
