### ISSUE TITLE
@types/knex missing with/withSchema functions

### ISSUE THREAD

**Issue by denkomanceski** [DefinitelyTyped/DefinitelyTyped#15237]
I added this to the Knex interface ```withSchema(schemaName: string): Knex;
``` and it works fine, but is also needed for ```with```
- [Qubo](https://github.com/tkQubo)
- [Baronfel](https://github.com/baronfel)

Regards

**Comment by andy-ms** [comment]
Make a pull request?

**Comment by estaub** [comment]
Not sure when/if I'll get to a PR... note that there are two withSchema() functions; it's the one on the querybuilder that's missing

**Comment by estaub** [comment]
This issue is addressed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18452 (already published to NPM) and should be closed.
