### ISSUE TITLE
Please add additonal definitions in node-forge/index.d.ts 

### ISSUE THREAD

**Issue by jaimeburnap** [DefinitelyTyped/DefinitelyTyped#15260]
I have to manually add publicKeyFromPem to this file so I can use it. Then when I run npm update it gets obliterated.

**Comment by ioancole** [comment]
Looks like there are a few other methods missing from that typings file, just comment here to let me know if you want any more added.

**Comment by ioancole** [comment]
PR #15309 should add the method you want, will add the rest of the missing methods when I have time.

**Comment by efroim102** [comment]
It looks like the method encryptRsaPrivateKey is missing too.
