### ISSUE TITLE
firmata.js (definition request & help)

### ISSUE THREAD

**Issue by troywweber7** [DefinitelyTyped/DefinitelyTyped#15261]
I've been using some custom-brewed definitions for [firmata.js](https://github.com/firmata/firmata.js) for a while now and would like to make them public for others to use/improve. I checked with the authors [about bundling the definitions](https://github.com/firmata/firmata.js/issues/153), but they are currently opting for creating an `@types/firmata`. I forked the firmata.js project and [practiced bundling it there, and I'm fairly certain my definitions are close to correct](https://github.com/troywweber7/firmata.js/blob/master/lib/firmata.d.ts) (though they could probably use some polishing). But I suspect I'm going to need some help with generating an `@types/firmata`.

The first reason I need help: I tried running `$ npm run new-package -- --name firmata --template module-class` and received an error.

```bash
$ npm run new-package -- --name firmata --template module-class

> definitely-typed@0.0.1 new-package /Users/troy/Code/DefinitelyTyped
> dts-gen --dt "--name" "firmata" "--template" "module-class"

Unexpected crash! Please log a bug with the commandline you specified.
/Users/troy/Code/DefinitelyTyped/node_modules/dts-gen/bin/lib/run.js:109
        throw e;
        ^

Error
    at new ArgsError (/Users/troy/Code/DefinitelyTyped/node_modules/dts-gen/bin/lib/run.js:25:28)
    at Object.<anonymous> (/Users/troy/Code/DefinitelyTyped/node_modules/dts-gen/bin/lib/run.js:39:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/troy/.nvm/versions/node/v7.5.0/bin/node" "/Users/troy/.nvm/versions/node/v7.5.0/bin/npm" "run" "new-package" "--" "--name" "firmata" "--template" "module-class"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! definitely-typed@0.0.1 new-package: `dts-gen --dt "--name" "firmata" "--template" "module-class"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the definitely-typed@0.0.1 new-package script 'dts-gen --dt "--name" "firmata" "--template" "module-class"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the definitely-typed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     dts-gen --dt "--name" "firmata" "--template" "module-class"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs definitely-typed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls definitely-typed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/troy/Code/DefinitelyTyped/npm-debug.log
```

Since I have a definition file that I think works, perhaps I don't need to perform this step. But I would like some help nevertheless. I have forked this repo so that I can eventually make a PR.

Thanks ahead of time for your help.

**Comment by troywweber7** [comment]
As you can see, I generated an initial pull request #15265 to get this process started. Help is appreciated. Also, recommendations for how I can test that my definitions are still working within an external project would be appreciated.

**Comment by paulvanbrenk** [comment]
@andy-ms Can you comment on this. The actual definition file in the PR looks good to me.

**Comment by andy-ms** [comment]
That PR is merged now, so closing this issue.
