### ISSUE TITLE
Angular readme.md

### ISSUE THREAD

**Issue by aplocher** [DefinitelyTyped/DefinitelyTyped#15274]
Is the first paragraph of the Angular readme.md file correct? 

> Referencing AngularJS definition files in your code
> 
> To do that, simply add `` at the top of your code.

I just add two back-ticks to the top of my file?  Or am I missing something here?  (and what code exactly is this document referring to?)

**Comment by andy-ms** [comment]
That must be a mistake. The types should be included automatically once they are installed in `@types/angular` so you shouldn't need to do anything. The README also mentions some files that no longer exist.
