### ISSUE TITLE
bittorrent-protocol : misused "new"

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#15287]
This contains the code:

```ts
export interface Extension {
        //tslint:disable-next-line:no-misused-new - could use class instead of interface but class is not extendible
        constructor(wire: Wire): this;
```

This declares that `Extension` *instances* are constructible, Not that there is an `Extension` entity which can be constructed to create instances. The stated reason for not using `class` doesn't make sense; classes can be extended using the `extends` keyword.

CC @tlaziuk
Ref: #14086

**Comment by tlaziuk** [comment]
Thanks for pointing that @andy-ms, I've wrote that just by looking at the code <https://github.com/feross/bittorrent-protocol/blob/master/index.js#L144>.

I've just created a PR <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15301> which should improve this extension a bit.

**Comment by andy-ms** [comment]
Thanks!
