### ISSUE TITLE
No iView d.ts file, no Vue d.ts file too

### ISSUE THREAD

**Issue by yangdan8** [DefinitelyTyped/DefinitelyTyped#15300]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

**Comment by andy-ms** [comment]
The `vue` package provides its own types.
If you want typings for `iView`, make a pull request adding them.
