### ISSUE TITLE
Broken definitions for redux-logger

### ISSUE THREAD

**Issue by LKay** [DefinitelyTyped/DefinitelyTyped#15323]
- [x] I tried using the `@types/redux-logger` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors 
  - Authors: @arusakov, @mcrawshaw

The issue is with definitions as of version `@types/redux-logger@2.10.0` and `redux-logger@2.10.2`.

Typings updated yesterday are incorrect. Definitions matches the source of the library but it's no match anymore for compiled version, which is distributed on npm.

Compiled version still uses common js module resolving and doesn't export default thus can't be imported as:
```typescript
import createLogger from "redux-logger";
```
This will produce error: `Uncaught TypeError: redux_logger_1.default is not a function`

Using previous version of definitions and importing it 'the old way': `import * as createLogger from "redux-logger"` works just fine.

**Comment by mcrawshaw** [comment]
I agree with your summary @LKay.

The definition was created against ```redux-logger@2.10.1```.  If you force install this version it should work fine.

The library author has changed ```export``` twice in a few days now.  Please see this issue for more information:
https://github.com/evgenyrodionov/redux-logger/issues/210

I'm waiting for as response on a question from @pilaas before updating the typings again.

**Comment by mcrawshaw** [comment]
Resolved with PR
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15346

**Comment by mcrawshaw** [comment]
@LKay now available on NPM, please close issue.
