### ISSUE TITLE
Sinon types need updates for Sinon 2 including promise support

### ISSUE THREAD

**Issue by rationull** [DefinitelyTyped/DefinitelyTyped#15320]
The typings for SinonJS need to be updated to Sinon 2 which was released just a few days ago now. The main issue I'm hitting is that I'm using the new promises support (similar to sinon-as-promised) but the declarations are not present for the resolves() and rejects() functions on stubs.

There are number of other API changes in 2.0 that should be handled as well. sinon.useFakeTimers(now) is marked in the Sinon docs as being new for 2.0 but is already represented in the current (1.16) version of the types. There may be other minor issues that I haven't encountered.

@mrbigdog2u is the original author of these typings. I can provide a PR addressing the promise issue I hit and other changes that I see with a quick pass through the API docs. It may not be perfect but it would be progress.

**Comment by r-ohan** [comment]
+1

**Comment by rationull** [comment]
This is resolved now after PR 15321 was merged.. barring any API changes I may have missed. Closing.
