### ISSUE TITLE
@types/plotly.js is missing an interface method

### ISSUE THREAD

**Issue by drewtownchi** [DefinitelyTyped/DefinitelyTyped#15343]
@types/plotly.js is missing an interface method PlotlyStatic.redraw(divid: string);

`
    interface PlotlyStatic {
        newPlot(divid: string | HTMLElement, data: any[], layout?: any, config?: PlotlyConfig): void;
        redraw(divid: string);
    }
`

  - Authors: @martinduparc

**Comment by martinduparc** [comment]
Hi @drw112 Feel free to create a PR with your changes

**Comment by chrisgervang** [comment]
Fixed in #15379

**Comment by galuszkak** [comment]
I think this ticket should be closed as it's fixed. 👍

**Comment by PARULAGRAWALdei** [comment]
there is no declare statement in .d.ts file. I have used command "npm install @types/plotly.js".But the following error came .
Try `npm install @types/plotly` if it exists or add a new declaration (.d.ts) file containing `declare module 'plotly';`

I am not getting how to solve this

**Comment by PARULAGRAWALdei** [comment]
I have used "npm i @types/plotly" before
