### ISSUE TITLE
@types/material-ui: Missing GridTileProps.titleStyle

### ISSUE THREAD

**Issue by mattes3** [DefinitelyTyped/DefinitelyTyped#15359]
- [ ] I tried using the `@types/material-ui@0.16.59` package and had problems.
- Authors: @ngbrown @herrmanno

The GridTile component has a property called 'titleStyle' which is missing in the type declaration file.

**Comment by fmavdb** [comment]
I'm also missing this type property. See property declaration:
http://www.material-ui.com/#/components/grid-list #

**Comment by minodisk** [comment]
@mattes3 I think this issue can be closed with: [Add missing properties for GridTile component · DefinitelyTyped/DefinitelyTyped@ef3404f](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/ef3404fb3b95a1e5ee689a8865c22590eaaa65f5)

**Comment by minodisk** [comment]
@andy-ms Could you close this issue?
