### ISSUE TITLE
Need to revert a commit

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#15367]
@horiuchi @vvakame

The latest commit to `master` (#15365) destroyed all history. Doing a normal `git revert` wouldn't fix history. Could you do `git pull; git reset HEAD~; git push -f`? The last commit should be `core-js: Declare globals with 'var' to avoid conflicts (#15362)`.

**Comment by vvakame** [comment]
wait a moment... I'll try it.

**Comment by andy-ms** [comment]
Actually, not sure this is necessary any more.

**Comment by horiuchi** [comment]
I think we do the `git co -b master f8493b7b8; git push -f`?

**Comment by vvakame** [comment]
done.

**Comment by andy-ms** [comment]
OK, what should we do differently the second time?

**Comment by vvakame** [comment]
Unprotect master branch at https://github.com/DefinitelyTyped/DefinitelyTyped/settings/branches/master

```
$ git pull --rebase
$ git reset --hard HEAD^
$ git push -f
```

Protect master branch again.

**Comment by andy-ms** [comment]
Hm, I don't have access to settings on this repo currently.

**Comment by vvakame** [comment]
other owners ( @basarat @blakeembrey @borisyankov @Diullei @johnnyreilly )
I'm suggesting add owner grant to @andy-ms .
We are active on TypeScript still, but inactive in DefinitelyTyped org. (isn't it?)
There is a possibility that we will become active again in future. 😉 
What do you think about this issue?

**Comment by horiuchi** [comment]
I agree to add owner.
I think it is better for at least one person to have an currently active member in the owners.

**Comment by andy-ms** [comment]
It looks like there's no way to preserve history *in the github view*. See http://stackoverflow.com/questions/5646174/how-to-make-github-follow-directory-history-after-renames .

So, I will re-do that commit, and push directly to `master`.

History will not be viewable on github, but we can add a notice to the README to always use `git log --follow`.

OK?

**Comment by basarat** [comment]
@vvakame I am okay with whatever you choose :heart: :rose:

**Comment by shaharmor** [comment]
@andy-ms this change also breaks all IntelliJ integration

**Comment by andy-ms** [comment]
@shaharmor Could you be more specific? What are you trying to do?

**Comment by shaharmor** [comment]
@andy-ms In WebStorm there is a very helpful feature where you can load typescript definitions from DefinitelyTyped for IntelliSense (autocomplete, etc).

Here is a link to the docs about it: https://blog.jetbrains.com/webstorm/2014/07/how-webstorm-works-completion-for-javascript-libraries/

Until this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15365 you would see a list of all the packages from the repo inside the WebStorm UI and you could choose and search whichever you want.

But now all you see is the "types" folder.
You can't go inside folders so it means that you can't load any definitions any more.

**Comment by blakeembrey** [comment]
This has also broken indexing from the Typings registry. A heads up would have been really useful, I'm sure, to the many people using DefinitelyTyped from different tools. I'll need to look into the logs, but I haven't been able to index anything since this commit. Even if I did, however, I'm sure it would have broken all the registry names and required manual undoing to fix the paths.

**Comment by vvakame** [comment]
I added owner grant to @andy-ms 🎉

**Comment by johnnyreilly** [comment]
Fine with me 🌷

**Comment by Diullei** [comment]
Good! :)

**Comment by FrancoisH** [comment]
The reporistory is still not working  form JetBrains products as said here and in issue #15390

**Comment by OUGHT** [comment]
The "download library stub" option in JetBrains WebStorm still does not work. Could you please fix it? =-)

**Comment by blakeembrey** [comment]
@OUGHT this would be something JetBrains needs to fix, do you know if there's somewhere you can file an issue with them?

**Comment by shaharmor** [comment]
They are already aware and working on a fix: https://twitter.com/WebStormIDE/status/846302961055731712

**Comment by OUGHT** [comment]
Thank you for the information! =-)

**Comment by xiaoyueyue165** [comment]
Is it necessary to update?

**Comment by xiaoyueyue165** [comment]
Is it necessary to update?

**Comment by andy-ms** [comment]
@xiaoyueyue165 Could you clarify? The commit was never actually reverted because it turned out to be unnecessary.
