### ISSUE TITLE
[react-autosuggest] - Error with React typings version

### ISSUE THREAD

**Issue by narayram** [DefinitelyTyped/DefinitelyTyped#15412]
- [X] I'm using latest version of @types/react-autosuggest and have issues.
- [X] I tried using the latest stable version of tsc (2.2.1). https://www.npmjs.com/package/typescript
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors 
  - Authors: @nicolas-schmitt, @pjo256, @tbayne

My issue is that I'm getting the below compilation error and Wondering if this is related to the version of react-typings that I'm using. Can you please advise what version of react typings do you use?

![image](https://cloud.githubusercontent.com/assets/13610235/24353143/34ae3d0a-12e4-11e7-9362-43fb102153cf.png)

**Comment by andy-ms** [comment]
`@types/react` defines a generic HTMLAttributes, so check what you have installed.

**Comment by narayram** [comment]
Thanks. I looked in the project further and turns out it was an older version of react typings that was causing the issue. Will upgrade to the latest.
