### ISSUE TITLE
angular bindings: type-safety loss on scope with TS 2.2+

### ISSUE THREAD

**Issue by emmanueltouzery** [DefinitelyTyped/DefinitelyTyped#15431]
Typescript 2.2 introduced ['dotted properties' support](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html#dotted-property-for-types-with-string-index-signatures). From their release announcement:

> Types with a string index signature can be indexed using the [] notation, but were not allowed to use the .. Starting with TypeScript 2.2 using either should be allowed.
> 
> ```
> interface StringMap<T> {
>     [x: string]: T;
> }
> 
> const map: StringMap<number>;
> 
> map["prop1"] = 1;
> map.prop2 = 2;
> ```

Now the problem is [this line of code](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/angular/index.d.ts#L450) in the angular bindings:

```
interface IRootScopeService {
    [index: string]: any; <----------------
```

This means after upgrading to typescript 2.2 `$scope.anythingatallyouwant` will compile!

 - Authors: @diegovilar @thorn0

**Comment by thorn0** [comment]
We can't solve this without introducing a breaking change. But we probably should do it.
See #16316

**Comment by emmanueltouzery** [comment]
closing -- the changes looks good though I couldn't test the changes myself yet
