### ISSUE TITLE
@types/selenium-webdriver - error TS2307: Cannot find module './chrome'.

### ISSUE THREAD

**Issue by bondib** [DefinitelyTyped/DefinitelyTyped#15436]
- [X ] I tried using the `[@types/selenium-webdriver](https://www.npmjs.com/package/@types/selenium-webdriver)` package and had problems compiling.
  - Authors: @BillArmstrong, @Kuniwak, @cnishina

When trying to use @types/selenium-webdriver I get the following typescript compilation (semantic) errors:

/home/bondi/dev/healthshield/harmony/node_modules/@types/selenium-webdriver/index.d.ts(8,25): error TS2307: Cannot find module './chrome'.
/home/bondi/dev/healthshield/harmony/node_modules/@types/selenium-webdriver/index.d.ts(9,23): error TS2307: Cannot find module './edge'.
/home/bondi/dev/healthshield/harmony/node_modules/@types/selenium-webdriver/index.d.ts(10,26): error TS2307: Cannot find module './firefox'.
/home/bondi/dev/healthshield/harmony/node_modules/@types/selenium-webdriver/index.d.ts(11,21): error TS2307: Cannot find module './ie'.
/home/bondi/dev/healthshield/harmony/node_modules/@types/selenium-webdriver/index.d.ts(12,24): error TS2307: Cannot find module './opera'.
/home/bondi/dev/healthshield/harmony/node_modules/@types/selenium-webdriver/index.d.ts(13,25): error TS2307: Cannot find module './safari'.

@BillArmstrong, @Kuniwak, @cnishina - can you please fix this?
Thanks!

**Comment by bondib** [comment]
BTW, using typescript 2.2.1

**Comment by andy-ms** [comment]
That's odd. Can you check the `node_modules/@types/selenium-webdriver` directory to see if those files are there?

**Comment by bondib** [comment]
They are there as you can see. It says it can't find the module... 
(Both vscode and ts complier)


![image](https://cloud.githubusercontent.com/assets/16187518/24417539/75482188-13f1-11e7-8e3b-9454b48fac04.png)

**Comment by andy-ms** [comment]
What are your module resolution settings? Can you show me the relevant output from  `--traceResolution`?

**Comment by bondib** [comment]
These are my tsconfig compiler option settings (my module resolution is set to classic):

> "compilerOptions": {
>     "rootDir": "src/",
>     "sourceMap": true,
>     "target": "es5",
>     "module": "amd",
>     "moduleResolution": "classic",
>     "declaration": false,
>     "noImplicitAny": false,
>     "noResolve": true,
>     "removeComments": true,
>     "noLib": false,
>     "emitDecoratorMetadata": true,
>     "experimentalDecorators": true
>   }

**Comment by andy-ms** [comment]
You have [`noResolve`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) set, so module resolution isn't even happening.

**Comment by bondib** [comment]
Wow - I didn't notice that one...
Not sure why it was set to true - but THANKS!. Anyways, that fixed that.
Thank you again very much for the help! Appreciated!
