### ISSUE TITLE
Select2 option maximumSelectionSize should be maximumSelectionLength

### ISSUE THREAD

**Issue by pajaroblanco** [DefinitelyTyped/DefinitelyTyped#15449]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andy-ms 

The Select2Options interface incorrectly specifies a `maximumSelectionSize` property instead of `maximumSelectionLength` property which causes typescript compilation to fail when trying to use the correct option name.

The property is defined here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/select2/index.d.ts#L47

The Select2 source that references maximumSelectionLength is found here: https://github.com/select2/select2/blob/062c6c3af5f0f39794c34c0a343a3857e587cc97/src/js/select2/data/maximumSelectionLength.js#L5

**Comment by andy-ms** [comment]
Make a pull request?
