### ISSUE TITLE
@Types/Jasmine 'Matchers' must have identical type parameters.

### ISSUE THREAD

**Issue by Jordan-Hall** [DefinitelyTyped/DefinitelyTyped#15443]
- [ x ] I tried using the `@types/jasmine` package and had problems.
  - Authors: @borisyankov @theodorejb @davidparsson

When trying to use Jasmine types definition in awesome-typescript-loader for webpack i'm getting the following error

**[at-loader] ./node_modules/@types/jasmine/index.d.ts:314:15
    TS2428: All declarations of 'Matchers' must have identical type parameters.**

**Comment by Jordan-Hall** [comment]
FIXED: 

So angular documentation tells you to use a helper method for testing:
declare namespace jasmine {
  interface Matchers {
    toHaveText(actual: any, expectationFailOutput?: any): jasmine.CustomMatcher;
  }
}

Since Matchers now strongly types it needed to be changed to <T>

**Comment by manindersoprasteria** [comment]
Hi Jordan ,
Above soln did not work for me.Could u please elaborate what i need to change in Matchers Interface?

**Comment by paullryan** [comment]
@manindersoprasteria You need to update your 
```
interface Matchers {
...
```
to 
```
interface Matchers<T> {
...
```

**Comment by hyndsite** [comment]
@manindersoprasteria you'll also need @types/jasmine version that has that change (e.g. < 2.5.3)
