### ISSUE TITLE
Breaking change in leaflet typings 1.0.58

### ISSUE THREAD

**Issue by bomberblue07** [DefinitelyTyped/DefinitelyTyped#15459]
- [x] I tried using the `@types/leaflet` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @webbiesdk

After upgrading to 1.0.58, onAdd and onRemove in the L.Control typings (line 998) were changed from member functions to member properties. This broke my code that overrode those methods. How do I migrate my code to the latest typings definition i.e how do I have those properties point to my custom functions?

**Comment by webbiesdk** [comment]
I changed them from methods to member properties so that they could be explicitly optional. 

This is one way to change your code:

````TypeScript
declare class Foo {
    classicMethod(): string;
    optionalMethod?:() => string;
}

class Bar extends Foo {
    classicMethod() {
        return "str";
    }
    optionalMethod = () => {
        return "str";
    }
}
````

**Comment by webbiesdk** [comment]
I changed them from methods to properties, so that they could be explicitly optional. 

But i just found out that methods can be optional as well (damn me). 

So I'll send a pull-request to make them back into methods.

Until then, you can use this: 

````TypeScript
declare class Foo {
    classicMethod?(): string;
    optionalMethod?:() => string;
}

class Bar extends Foo {
    classicMethod() {
        return "str";
    }
    optionalMethod = () => {
        return "str";
    }
}

````

**Comment by bomberblue07** [comment]
Fixed in latest version. Thanks!
