### ISSUE TITLE
@types/hapi has wrong defintion of Promises - should be native

### ISSUE THREAD

**Issue by mmc41** [DefinitelyTyped/DefinitelyTyped#15481]
- [X ] I tried using the `@types/xxxx` package and had problems.

@jasonswearingen Currently, @types/hapi defines HapiJs promise as of type IPromise. This is problematic in later versions of typescript which are quite strict and will report IPromise as incompatible with the buildin Promise type. Since HapiJs uses native promises (bluebird was removed a long time ago) there should be no need to define an IPromise. Instead plain standard Promise should be used. Alternatively, IPromise can be defined as IPromise = Promise for backward compatibility.

**Comment by mmc41** [comment]
BTW: Here is example of the exact error one can get without this change when mixing Promise and IPromise. PS. It is not enough to simply add the missing property to the definiton, as typescript  async/await requires the real Promise type to work.

message: 'Type 'IPromise<T>' is not assignable to type 'Promise<T>'.
  Types of property 'then' are incompatible.
    Type '{ <U>(onFulfilled?: (value: T) => U | IThenable<U>, onRejected?: (error: any) => U | IThenable<U>...' is not assignable to type '{ (onfulfilled?: (value: T) => T | PromiseLike<T>, onrejected?: (reason: any) => T | PromiseLike<...'.
      Type 'IPromise<any>' is not assignable to type 'Promise<T>'.
        Types of property 'then' are incompatible.
          Type '{ <U>(onFulfilled?: (value: any) => U | IThenable<U>, onRejected?: (error: any) => U | IThenable<...' is not assignable to type '{ (onfulfilled?: (value: T) => T | PromiseLike<T>, onrejected?: (reason: any) => T | PromiseLike<...'.
            Type 'IPromise<any>' is not assignable to type 'Promise<any>'.
              Property '[Symbol.toStringTag]' is missing in type 'IPromise<any>'.'
at: '27,7'
source: 'ts'

**Comment by jasonswearingen** [comment]
thanks for this info, I will look into modifying this in time (add a ticket to my personal tracker) but it will take a while as I tend to only do "housekeeping" tasks like this when there are bugs to fix in my own libraries.  

if someone else wants to make a pull request, I'll be happy to accept the change though.

**Comment by mmc41** [comment]
I can try to make a PR if you will be quick to look at it - Let me know if you have any preferences about the solution. Removing IPromise and related interfaces and replacing them with native Promise stuff OR declaring IPromise as alias to Promise OR ?

**Comment by jasonswearingen** [comment]
I would recommend you use the PromiseLike<T> interface which is provided by Typescript.  That way it will work with anybody's types as long as their promise implementation conforms to spec.

however I"ve been out of the loop regarding how to best-practice Promise using libraries, so I'd suggest getting another opinion on the matter.

**Comment by mmc41** [comment]
You have a IThenable (if I remember correctly) which can be set to PromiseLike, but for async/await to be used one need to use Promise and not PromiseLike unfortunately. My question is really if you want the interface to try to be backwards-compatible (with some strange interface baggage for historic reasons) or if we should make a clean break and only use the standards stuff ?

**Comment by mmc41** [comment]
@jasonswearingen Have now added a PR for this using a backwards-compatible approach. Please review.

**Comment by andy-ms** [comment]
Fixed by #15568.

**Comment by mmc41** [comment]
@andy-ms Thanks for the merging my change. Can you help explain the process getting the changes into the code, after jasonswearingen ok'ed it. It was the first time I added something to definitelytyped and would like to know what one should do to get things in.

**Comment by andy-ms** [comment]
Normally a DT member has to come along and merge any pull requests.
