### ISSUE TITLE
@types/node-schedule: valid param omitted from Job.schedule and scheduleJob

### ISSUE THREAD

**Issue by rondaa** [DefinitelyTyped/DefinitelyTyped#15505]
@cyrilschumacher

The readme for [node-schedule/node-schedule](https://github.com/node-schedule/node-schedule) has the following example under [set start time and end time](https://github.com/node-schedule/node-schedule#set-starttime-and-endtime)

```
let startTime = new Date(Date.now() + 5000);
let endTime = new Date(startTime.getTime() + 5000);
var j = schedule.scheduleJob({ start: startTime, end: endTime, rule: '*/1 * * * * *' }, function(){
  console.log('Time for tea!');
});
```

Copying this with the current type definition gives error: `Argument of type '{start: Date; end: Date; rule: string;}' is not assignable to parameter of type 'string | Date | RecurrenceRule | RecurrenceSpec'.` After looking for myself I see that neither RecurrenceRule nor RecurrenceSpec match the given object param.

[The source starting at this line](https://github.com/node-schedule/node-schedule/blob/master/lib/schedule.js#L182) shows that start, end, and rule are valid properties of the object parameter.

**Comment by rondaa** [comment]
In my own testing, overloading the RecurrenceSpec interface as follows got the job done:

```
export interface RecurrenceSpec {
    start: Date | string | number;
    end: Date | string | number;
    rule: string;
}
```

I'm new to this so I'm not sure if this is the right way to go. It'd be cool if the author could give me their thoughts.

**Comment by cyrilschumacher** [comment]
Hello @rondaa,

I wrote this definition in 2015 and I see that `start` and `end` parameters appeared recently in [July 2016](https://github.com/node-schedule/node-schedule/commit/b076130a00abd39a063422c0e8f77289733ea3ce#diff-e548a7b1975de2141f59ab352467fc5e). It would be necessary to update the definition by proposing a pull request.

Either I can do it (I have definitions to bring to the project very soon) or you can do it (which is a great exercise) :)

**Comment by rondaa** [comment]
@cyrilschumacher I'll be submitting a PR shortly with tests. As it turns out "overloading" the interface didn't work because then the other version of RecurrenceSpec wasn't recognized. I split it up into RecurrenceSpecObjLit and RecurrenceSpecDateRange. It's a mouthful, but I tried to make them each distinctive while still recognizable as versions of the old RecurrenceSpec.

As a heads up, due to the linting requirement for PRs don't be surprised if you see a lot of line changes.
