### ISSUE TITLE
index.d.ts @types/html-webpack-plugin v2.22.4 does not contains [options:string]:any

### ISSUE THREAD

**Issue by tebeco** [DefinitelyTyped/DefinitelyTyped#15525]
- [x] I tried using the `@types/html-webpack-plugin` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andy-ms @deevus @jantimon i don't know who else should i mention here

as we can see in this repository :
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/html-webpack-plugin/index.d.ts#L81

```
		/**
		 * In addition to the options actually used by this plugin, you can use this hash to pass arbitrary data through
		 * to your template.
		 */
		[option: string]: any;
```

when i install @types/html-webpack-plugin my index.d.ts does not contains this property, since we use webpack config in typesccript this ends up in an error when i try to inject custom configuration into my template like this :

`node_modules\@types\html-webpack-plugin\index.s.ts`
```
new HtmlWebpackPlugin({
      template: path.resolve(__dirname, '..', 'src', 'index.ejs'),
      applicationConfiguration: JSON.stringify(applicationConfiguration)
    })


        <script type="text/javascript">
            window['applicationConfiguration'] = <%= htmlWebpackPlugin.options.applicationConfiguration %>;
        </script>
```

i've check `node_modules\@types\html-webpack-plugin\packages.json`
`"version": "2.22.4"`

**Comment by andy-ms** [comment]
It appears that this package went backwards in version from 2.22 to 2.11 in #13550. Not sure why. 2.11 is the latest, so try installing that.

**Comment by tebeco** [comment]
what went backwards ?
* the plugin ? <== so i have to wait for them to release a 2.23.x ? unpublish version from npm is not an options ^^ ?
* the @types/plugin ? <== if so can,t we push a newer version ?

**Comment by tebeco** [comment]
adding @bumbleblym to the discution

also how is @types/xxx version generated ?

i mean the idea is to simply have to do :
`npm i -D html-webpack-plugin @types/html-webpack-plugin`

nothing else, so until there's a 2.23 that clear this issue it's random ...
and `npm outdated` will yell
also we have tool in our CI that upgrade back nuget and front package, run unit / integration / acceptance and e2e test, so this will fail for month ?

**Comment by tebeco** [comment]
so far i'm editing `index.d.ts` to add the line and it kinda does the trick but it's reaaaaaly ugly

**Comment by andy-ms** [comment]
We publish the version that it says in the comment. In #13550 that version went backwards.
You could always make a pull request updating the types to the latest version of the original library, which is 2.28 now.

**Comment by bumbleblym** [comment]
i updated the version number to follow the major.minor format. the updated definition was valid for `html-webpack-plugin` versions `^2.11`, which includes `2.22`, so i changed it to `2.11`. 

`npm i -S  @types/html-webpack-plugin` installs version `2.11.2`.
`npm outdated` doesn't seem to give me any errors.

nonetheless, i believe updating the version number back to `2.22` should publish a version `2.22.5`. the current latest `html-webpack-plugin` version is `2.28.0`.
