### ISSUE TITLE
"npm test" fails when run with node 6.10.1, "Object.entries is not a function"

### ISSUE THREAD

**Issue by rationull** [DefinitelyTyped/DefinitelyTyped#15564]
The DefinitelyTyped package.json has "engines" set to node >= 6.9.1 but when I run 'npm test' with node 6.10.1 then the tests that run fail with:

Command failed: node /Users/jonathanlittle/src/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../node_modules/dtslint/bin/index.js --dt --noLint
Object.entries is not a function

I hit this running against my changes from PR #15563 but I think it'll fail when changes cause any tests to run.

When I switch to node 7.8.0 the tests pass.

Is this an issue in the code/dependencies that needs to be resolved or does the required node version need to be bumped up?

**Comment by andy-ms** [comment]
FYI, you don't actually need to run the full test suite normally, you can just `yarn lint mypackage` and let travis find any other errors.

**Comment by rationull** [comment]
Good to know. The package I was editing doesn't happen to have lint rules so I was just running `npm test` to run the tests I had modified.

**Comment by andy-ms** [comment]
In that case you can run `tsc`. Or add linting 😃

**Comment by rationull** [comment]
Fair enough :)
