### ISSUE TITLE
Meta-data source (manifest)

### ISSUE THREAD

**Issue by Bartvds** [DefinitelyTyped/DefinitelyTyped#1556]
DT repository needs a meta-data source to provide more information about the definitions to be consumed by both internal and external tooling.

The likely candidate is to put manifest files with some JSON content in the definitions folders and have the tooling filter them out.

This Issue tracks the discussion & progress.

Proposals & prose:
- ~~Organisation Doc: [02](https://docs.google.com/document/d/1mQBij_VYCpQPTV4aaprrttqYPZtwQag1ikqcTLpipTc)~~
- [proposals](https://docs.google.com/document/d/1u0KS9hd1ya84o75lTW-CrQ0EV5zRx-2Gv6VbZeCz0xs/edit?usp=sharing)

Some earlier discussions:
- https://github.com/borisyankov/DefinitelyTyped/issues/1314
- https://github.com/borisyankov/DefinitelyTyped/issues/428
- https://github.com/DefinitelyTyped/NugetAutomation/issues/4

**Comment by jakebailey** [comment]
Trying to do some issue cleanup; after converting to pnpm, all info is now in package.json.
