### ISSUE TITLE
[Request] types definition for @vimeo/player 

### ISSUE THREAD

**Issue by denisyilmaz** [DefinitelyTyped/DefinitelyTyped#15571]
there is only a older vimeo types definition, but not for the current version.
can anybody help out?
see the discussion here: [https://github.com/vimeo/player.js/issues/109](url)

**Comment by SaschaNaz** [comment]
The file is here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/videojs/index.d.ts

**Comment by SaschaNaz** [comment]
The file is here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vimeo/index.d.ts

**Comment by denisyilmaz** [comment]
Unfortunately the typings is not working with the current @vimeo/player.js version

**Comment by SaschaNaz** [comment]
Ah yes, I just posted it to help any contributors find it.

**Comment by denisyilmaz** [comment]
I started working on the typings but have problems with the promise definition for the callback functions… the new api has a good documentation so it shouldn't be that difficult.

**Comment by denisyilmaz** [comment]
closed with commit a209273
