### ISSUE TITLE
Typings for npm's package.json (http://json.schemastore.org/package)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DefinitelyTyped/DefinitelyTyped#15602]
The schema is available at http://json.schemastore.org/package. I'd like to use it in `.d.ts` form for a project. Do such typings exist yet? If not, I'm willing to take a stab at them.

It looks like https://www.npmjs.com/package/json-schema-to-typescript would be well suited for this!

_(Continuation of #9624, which was closed for some reason)_

**Comment by zixia** [comment]
Would be very nice if we can use it this way.

Had you found the solution? @JoshuaKGoldberg

**Comment by JoshuaKGoldberg** [comment]
I haven't put any effort in.

**Comment by JoshuaKGoldberg** [comment]
I think this has probably aged away by now. If someone would like to take it on, feel free to file a new issue :)

**Comment by Maxim-Mazurok** [comment]
This, actually, looks like a good candidate for automation... I'll think about this. Cheers!
