### ISSUE TITLE
Auto-publish typings for schemas on schemastore.org?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DefinitelyTyped/DefinitelyTyped#15603]
See #15602. Rather than having some devs manually run [json-schema-to-typescript](https://www.npmjs.com/package/json-schema-to-typescript) or similar when it suits them, having a single script that pulls in all their packages, converts them to typings, and sends appropriate PRs for updates would be great.

**Comment by andy-ms** [comment]
Does this need to be part of DefinitelyTyped? Couldn't you have a tool that publishes to an `@schema` namespace and then use `import PackageJson from "@schema/package.json`?

**Comment by JoshuaKGoldberg** [comment]
That works too! As long as there's a standardized, ~auto updated way to get these typings.

**Comment by andy-ms** [comment]
Related: Microsoft/TypeScript#3136

**Comment by JoshuaKGoldberg** [comment]
I think this has probably aged away by now. If someone else wants to take it on, feel free to file a new issue. :)
