### ISSUE TITLE
Use improved branch model

### ISSUE THREAD

**Issue by Bartvds** [DefinitelyTyped/DefinitelyTyped#1567]
We should use a fixed branch for each TypeScript compiler version, instead of branching the old version off whenever TypeScript updates and updating the master.

The problem here are inbound urls  they change 'meaning' when we flip the branch.

If we'd keep the TypeScript version in it's own branch the github urls and references would never change. We then don't use master at all.

**Comment by andy-ms** [comment]
With NPM `@types` we have to share a namespace for all compiler versions.
We should just try to keep definitions 2.0-compatible.
Can this be closed?
