### ISSUE TITLE
@types/redux-actions -- ActionFunctionAny seems incorrect?

### ISSUE THREAD

**Issue by ThaNarie** [DefinitelyTyped/DefinitelyTyped#15697]
- [x] I tried using the `@types/redux-actions` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jaysoo @alexgorbatchev 

With the following code:
```
const scrollTo = createAction<number>(SCROLL_TO)
```
the returned function is typed as:
```
type ActionFunctionAny<R> = (...args: any[]) => R;
```

The source code actually calls `'lodash/identity'` as the payloadCreator when not providing one (which only returns the first argument), so there is only 1 parameter expected to end up as the payload, since passing multiple parameters will be useless.

Knowing the above, the type of the first (and only) input argument will exactly match the type of the payload in the action, and the correct typed function should make use of `ActionFunction1` instead by passing the same type for `T1` and `R`:
```
export function createAction<Payload>(
    actionType: string
): ActionFunction1<Payload, Action<Payload>>;
```

With the current implementation of `(...args: any[])` the input of the returned function will never be typed, which is a missed opportunity.

I'm happy to make a PR if the above assumption is indeed correct.

**Comment by ThaNarie** [comment]
The above might not be fully correct after trying the approach, since actions that should NOT receive any arguments/payload, are now forced to receive any.

If we add a version without any generic type and passing void to the Action this would be solved as well:
```
export function createAction(
  actionType: string
): ActionFunction0<Action<void>>;
```

**Comment by meowtec** [comment]
Same question.

Now I have to write like this...
```
createAction<string, string>('ADD', x => x)
```

**Comment by marcinsirocki** [comment]
Could someone show example how createActions() should look like with typings ?

**Comment by huruji** [comment]
same problem

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
