### ISSUE TITLE
Type for stats.js is not working

### ISSUE THREAD

**Issue by Driky** [DefinitelyTyped/DefinitelyTyped#15696]
- [x] I tried using the `@types/stats.js` package and had problems.
- Authors: Definitions by: Gregory Dalton <https://github.com/gregolai>, Harm Berntsen <https://github.com/hberntsen>

When using this defintion I get the following error:
`game.ts:36 Uncaught TypeError: Stats is not a constructor`

I'm importing it that way:
`import Stats  = require('stats.js');`

And it is this line that make it crash:
` this.stats = new Stats();`

**Comment by andy-ms** [comment]
Mentioning the authors: @gregolai, @hbernsten

It seems does seem that the NPM package exports a function (and so the current definition is correct for NPM): `node -p 'require("stats.js")'` is a function. Are you requiring this library in some different way?

**Comment by Driky** [comment]
I'm trying to use it as shown on the README.me from: 
https://github.com/mrdoob/stats.js

And I tried to directly call a function without using new:

```
this.stats.showPanel( 1 );
this.stats.dom.style.position = 'absolute';
this.stats.dom.style.bottom = '0px';
document.appendChild(this.stats.dom); 
```
which gives me: 

```
Uncaught TypeError: Cannot read property 'showPanel' of undefined
    at new Game (:3000/game.js:33)
    at Object.<anonymous> (:3000/app.js:15)
    at Object.execCb (require.min.js:1)
    at b.check (require.min.js:1)
    at b.<anonymous> (require.min.js:1)
    at require.min.js:1
    at require.min.js:1
    at each (require.min.js:1)
    at b.emit (require.min.js:1)
    at b.check (require.min.js:1)
```

I'm new to the javascript/typescript environment, so maybe I'm missing something.

**Comment by andy-ms** [comment]
That doesn't help unless I know how you're assigning `this.stats`.

**Comment by Driky** [comment]
Sorry about that forgot that bit:

`import Stats  = require('stats.js');`

for the import and the following to assign it as a member of my class : 

`stats       :   Stats;`

And thank you for your help ^^

**Comment by andy-ms** [comment]
That still doesn't show the assignment statement. What is the output of this:
```ts
import Stats = require("stats.js");
console.log(Stats);
```

**Comment by Driky** [comment]
Ok now I see the problem:
```
import Stats  = require('stats.js'); 
console.log("Stats = ",Stats);
```

gives this : 

`Stats =  `undefined``

**Comment by andy-ms** [comment]
Well, that's not good. It must be a problem with the module loader, though. If the module doesn't export any thing at all, then no import style will work.

**Comment by Driky** [comment]
The only export I see in the typing is 
```
declare module "stats.js" {
    export = Stats;
}
```
`Stats` being declared as a class at the top of the file.

**Comment by andy-ms** [comment]
Yes, but the typing won't guarantee that it will exist at runtime, and apparently `require("stats.js")` is undefined for you.
The typing is currently written in ambient style, so it also declares a global `Stats` class.

**Comment by MaggieLMJ** [comment]
var Stats = require('../libs/static')
            let stats = new Stats.Stats
            stats.showPanel( 0 ); // 0: fps, 1: ms, 2: mb, 3+: custom


It worked !!!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
