### ISSUE TITLE
Masonry types are under an object when using webpack out of the box

### ISSUE THREAD

**Issue by jsgoupil** [DefinitelyTyped/DefinitelyTyped#15716]
When using `@types/masonry-layout`

Then doing 

    import * as Masonry form 'masonry-layout';
    // ...
    new Masonry.Masonry()

It does not work. The constructor is behind the first object

    new Masonry()

TypeScript 2.1.6 
WebPack  2.3.2  
Masonry 4.4.1

**Comment by andy-ms** [comment]
It looks like you're right, it directly exports the class.
Could you make a pull request fixing this?
The basic structure is:

```ts
export = Masonry;

declare class Masonry { 
	... methods ...
}

declare namespace Masonry {
	... interfaces ...
}

declare global {
    interface JQuery {
        ... methods ...
    }
}
```

It also looks like some of the tests have been commented out!

**Comment by jsgoupil** [comment]
@andy-ms sorry I am not familiar with Definitely typed pull request and I am quite busy at the moment. I will look at how it is done by following this bug :)
