### ISSUE TITLE
stripJsonComments should export its function

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DefinitelyTyped/DefinitelyTyped#15722]
The project exports its function rather than declaring it globally as the typings suggest.

**Comment by andy-ms** [comment]
Are you referring to `types/strip-json-comments/index.d.ts`? This already uses `export =`.

**Comment by JoshuaKGoldberg** [comment]
Stumbled upon the repro for this and pushed it to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15722

In a typical module file, the following gives a "resolves to a non-module entity" error:

```typescript
import * as stripJsonComments from "strip-json-comments";
```

```
[ts] Module '"c:/Code/strip-json-comments-typings/node_modules/@types/strip-json-comments/index"' resolves to a non-module entity and cannot be imported using this construct.
module "c:/Code/strip-json-comments-typings/node_modules/@types/strip-json-comments/index"
```

**Comment by andy-ms** [comment]
#15722 is this issue, did you mean something else?
That error you're  getting is normal since it's a CommonJS rather than ES6 module, although you could hack around it by adding `declare namespace stripJsonComments {}` under `declare function stripJsonComments`.

**Comment by JoshuaKGoldberg** [comment]
Whoops yes :) https://github.com/JoshuaKGoldberg/strip-json-comments-typings is what I meant to paste.
