### ISSUE TITLE
lodash type errors

### ISSUE THREAD

**Issue by SET001** [DefinitelyTyped/DefinitelyTyped#15739]
- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention] @bczengel, @chrootsu, @stepancar, @ericanderson so they can respond.

After I installed lodash types (`npm install @tyles/lodash --save-dev`)  tsc gives me this errors:

`../node_modules/@types/lodash/index.d.ts(12847,29): error TS2304: Cannot find name 'object'.
../node_modules/@types/lodash/index.d.ts(19587,15): error TS2428: All declarations of 'WeakMap' must have identical type parameters.
../node_modules/@types/lodash/index.d.ts(19587,33): error TS2304: Cannot find name 'object'.`

My tsc version is `2.3.0-dev.20170401`

**Comment by SET001** [comment]
Also I don't know if this realated or not but this code:

```
getSocketAccount(socket: SocketIO.Socket): Account|undefined{
   _.find(this.loggedInAccounts, {email: "Asd"})
}
```
also give an error which I don't know how to solve:

`error TS2345: Argument of type '{ email: string; }' is not assignable to parameter of type 'Partial<Account>'.
  Object literal may only specify known properties, and 'email' does not exist in type 'Partial<Account>'.`

loggedInAccounts defined like this:
```
loggedInAccounts: Account[] = []
```

**Comment by ericanderson** [comment]
Are you using @types/es6-shim?

**Comment by SET001** [comment]
nope

**Comment by andy-ms** [comment]
Are you sure that your tsc version is the one actually being used to compile? The `object` type is only available in newer versions of TypeScript but you seem to be getting errors from it.
As for your second error, that all depends on the declaration of the interface `Account`; does it include `email: string` in there too?

**Comment by eyalc4** [comment]
Hi Set,
Install lodash with the following two commands:
npm install --save lodash
npm install @types/lodash@ts2.0 --save-dev 
(the ts2.0 is the key to solve your issue)

**Comment by SET001** [comment]
@eyalc4, thanx, that was the solution for me!

**Comment by andy-ms** [comment]
@SET001 `@ts2.0` installs an older version. You shouldn't need it if you're using the latest TypeScript.

**Comment by eyalc4** [comment]
thats depends on the ts that you run, 
2.0, 2.1, 2.2
for example, to use newer u may use:
npm install @types/lodash@ts2.2 --save-dev

in both cases, it solve your errors.

**Comment by mjwdoek** [comment]
Adding `"skipLibCheck": true`, to my tsconfig.json did it for me.

**Comment by andy-ms** [comment]
@mjwdoek I wouldn't recommend that because it can hide useful errors. You might need to install TypeScript 2.3 or above to fix the errors.

**Comment by YanPengyu** [comment]
@andy-ms you're right,man,thanks!!!  TypeScript 2.3+

**Comment by jamesliauw** [comment]
> Adding `"skipLibCheck": true`, to my tsconfig.json did it for me.

Yes, it works!

**Comment by jamesliauw** [comment]
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "baseUrl": "src/",
    "paths": {
        "@shared": [ "app/shared" ],
        "@shared/*": [ "app/shared/*" ],
        "@core": [ "app/core/" ],
        "@core/*": [ "app/core/*" ],
        "@testing": [ "testing/" ],
        "@testing/*": [ "testing/*" ],
        "@env": [ "environments/" ],
        "@env/*": [ "environments/*" ]
    }
  }
}

**Comment by eightgrids** [comment]
that worksssssssssss

**Comment by eightgrids** [comment]
Adding "skipLibCheck": true, to my tsconfig.json did it for me.
