### ISSUE TITLE
Latest Chai Types break ts type inference

### ISSUE THREAD

**Issue by domoritz** [DefinitelyTyped/DefinitelyTyped#15768]
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4318786e2f26ff2ffee815faa68b4b9714b1a2fa breaks my code. 

I get hundreds of error like this:

```
test/compile/data/aggregate.test.ts(100,7): error TS2453: The type argument for type parameter 'T' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
  Type argument candidate 'VgAggregateTransform[]' is not a valid type argument because it is not a supertype of candidate '{ 'type': string; 'groupby': string[]; 'fields': string[]; 'ops': string[]; }[]'.
    Type '{ 'type': string; 'groupby': string[]; 'fields': string[]; 'ops': string[]; }' is not assignable to type 'VgAggregateTransform'.
      Types of property 'type' are incompatible.
        Type 'string' is not assignable to type '"aggregate"'.
```

I think the problem is that ts cannot infer a generic that is not used. I think the fix is to remove the `<X>` for functions that are not generics. 

cc @JoshuaKGoldberg

**Comment by JoshuaKGoldberg** [comment]
Sure. Can you post a snippet of source code that's seeing the breakage?

**Comment by domoritz** [comment]
Sure!

```ts
assert.deepEqual(aggregates, [{
        'type': 'aggregate',
        'groupby': ['Origin'],
        'fields': ['*', 'Acceleration'],
        'ops': ['count', 'sum']
      }]);
```

From https://github.com/vega/vega-lite/blob/master/test/compile/data/aggregate.test.ts

Thanks for looking into this.

**Comment by JoshuaKGoldberg** [comment]
This looks like a (really interesting) peculiarity of how TypeScript deals with type comparisons and supertypes when the interface has a type union.

```typescript
interface TestInterface {
    required: 'aggregate';
    // The error goes away if this is just a boolean
    other: string | boolean;
}

const actual: TestInterface = {
    required: 'aggregate',
    other: true
};

/*
The type argument for type parameter 'T' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
  Type argument candidate 'TestInterface' is not a valid type argument because it is not a supertype of candidate '{ required: string; other: boolean; }'.
    Types of property 'required' are incompatible.
      Type 'string' is not assignable to type '"aggregate"'.
*/
assert.deepEqual(actual, {
    required: 'aggregate',
    other: true
});

// This is fine!
assert.deepEqual(actual, {
    required: 'aggregate'
});
```

IMO this edge-ish case doesn't justify removing the stricter Chai typings, and if anything should be considered a TypeScript bug. You can always explicitly specify the type argument as `<VgAggregateTransform[]>`. Thoughts?

**Comment by domoritz** [comment]
I'm okay with declaring the types explicitly until this issue is fixed in Typescript.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
