### ISSUE TITLE
Type FinderOptions don't take all possible parameters in @types/pathfinding

### ISSUE THREAD

**Issue by jeremyfourna** [DefinitelyTyped/DefinitelyTyped#15810]
- [x] I tried using the `@types/pathfinding` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @BNedry

Currently the type of `FinderOptions` doesn't cover the parameter `allowDiagonal` and others

```ts
interface FinderOptions extends Heuristic {
        diagonalMovement?: DiagonalMovement;
        weight?: number;
}
```

but the `pathfinding` library has those options in `pathfinding/src/finders/AStarFinder.js`

```js
function AStarFinder(opt) {
    opt = opt || {};
    this.allowDiagonal = opt.allowDiagonal;
    this.dontCrossCorners = opt.dontCrossCorners;
    this.heuristic = opt.heuristic || Heuristic.manhattan;
    this.weight = opt.weight || 1;
    this.diagonalMovement = opt.diagonalMovement;

    if (!this.diagonalMovement) {
        if (!this.allowDiagonal) {
            this.diagonalMovement = DiagonalMovement.Never;
        } else {
            if (this.dontCrossCorners) {
                this.diagonalMovement = DiagonalMovement.OnlyWhenNoObstacles;
            } else {
                this.diagonalMovement = DiagonalMovement.IfAtMostOneObstacle;
            }
        }
    }

    // When diagonal movement is allowed the manhattan heuristic is not
    //admissible. It should be octile instead
    if (this.diagonalMovement === DiagonalMovement.Never) {
        this.heuristic = opt.heuristic || Heuristic.manhattan;
    } else {
        this.heuristic = opt.heuristic || Heuristic.octile;
    }
}
```

We need to have the `FinderOptions` interface that will looks like this : 

```ts
interface FinderOptions extends Heuristic {
        diagonalMovement?: DiagonalMovement;
        weight?: number;
        allowDiagonal?: boolean;
        dontCrossCorners?: boolean;
}
```

**Comment by BNedry** [comment]
👍

**Comment by minotaurrr** [comment]
faced this issue, would manually adding types myself fix it?

**Comment by BNedry** [comment]
@minotaurrr @types/pathfinding needs to be updated, if you have some time you can correct the typings and push them to this repository or you can download and manually link the typings and then edit the FinderOptions interface like above

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
