### ISSUE TITLE
redux-form typing error TS2305 has no exported member 'ChangeEvent'

### ISSUE THREAD

**Issue by jamespero** [DefinitelyTyped/DefinitelyTyped#15846]
While trying to utilize **@types/redux-form** I keep getting a typescript error from the **Field.d.ts** typing that **ChangeEvent** from react is not an exported member.

`ERROR in c:\path-to-code\node_modules\@types\redux-form\lib\Field.d.ts
(4,5): error TS2305: Module '"c:/path-to-code/node_modules/@types/react/index"' has no exported member 'ChangeEvent'.`

I'm locked into using **react 15.3.2** and **tsc 2.2.1** and I'm not able to find any other mention of ChangeEvent related to react or redux-form.

@LKay

**Comment by jamespero** [comment]
This looks to have been caused by an outdated instance of @types/react

**Comment by shadrech** [comment]
@jamespero outdated instance of what? I'm getting the same error

**Comment by dahlbyk** [comment]
Nice, GitHub parsed `@types/react` as a team mention: `<gh:team-mention org="types" team="react" />`.
