### ISSUE TITLE
Upgrade @types/mssql match with node-mssql 4.0.1

### ISSUE THREAD

**Issue by tangkhaiphuong** [DefinitelyTyped/DefinitelyTyped#15855]
mssql 4.0.1 have release and change Connection to ConnectionPool, please update this typing library.

**Comment by andy-ms** [comment]
Please fill in the [issue template](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by j-oliveras** [comment]
@andy-ms I think this can be closed, the types are already up to date by PR #15909.
