### ISSUE TITLE
@types/lodash - Add support for ReadonlyArray in _.chain()

### ISSUE THREAD

**Issue by alexjlockwood** [DefinitelyTyped/DefinitelyTyped#15850]
- Authors: @sandersn @ericanderson @bczengel @chrootsu @stepancar

For example, in the screenshot below, calling `_.chain(ReadonlyArray<string>).map(...).value()` results in type `any[]` instead of type `string[]`.

![screen shot 2017-04-13 at 3 10 43 pm](https://cloud.githubusercontent.com/assets/1380747/25021263/99ec36ee-205f-11e7-917e-fae25b2250be.png)

When I add the following line to the [index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5e1049bce15f9ca048f001d37935ca7946b0be03/types/lodash/index.d.ts#L5896-L5914) file, the issue seems to go away:

    /*********
     * Chain *
     *********/

    //_.chain
    interface LoDashStatic {
      /**
       * Creates a lodash object that wraps value with explicit method chaining enabled.
       *
       * @param value The value to wrap.
       * @return Returns the new lodash wrapper instance.
       */
      chain(value: number): LoDashExplicitWrapper<number>;
      chain(value: string): LoDashExplicitWrapper<string>;
      chain(value: boolean): LoDashExplicitWrapper<boolean>;
      chain<T>(value: ReadonlyArray<T>): LoDashExplicitArrayWrapper<T>;  // <-- THIS LINE
      chain<T>(value: T[]): LoDashExplicitArrayWrapper<T>;
      chain<T extends {}>(value: T): LoDashExplicitObjectWrapper<T>;
      chain(value: any): LoDashExplicitWrapper<any>;
    }

Is there a reason why `ReadonlyArray` doesn't seem to be supported?

**Comment by alexjlockwood** [comment]
@sandersn @ericanderson @bczengel @chrootsu @stepancar

If you all are busy and would like me to work on a pull request, please let me know. :)

**Comment by ericanderson** [comment]
I can review something. No time to fix it myself.

**Comment by alexjlockwood** [comment]
Hey @ericanderson, would you mind reviewing this PR? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15892

**Comment by aj-r** [comment]
@andy-ms I think this should be closed, since #15892 is closed?
