### ISSUE TITLE
Importing 'react-bootstrap' works but importing individual components dont

### ISSUE THREAD

**Issue by iamsaksham** [DefinitelyTyped/DefinitelyTyped#15856]
Why do I need to import `react-bootstrap` like

    import {Button} from 'react-bootstrap';
    ...

    <Button></Button>

but importing like this wont work:

    import * as Button from 'react-bootstrap/lib/Button'

i get this error: `TS2604: JSX element type 'Button' does not have any construct or call signatures.`

as well as this:

    import Button from 'react-bootstrap/lib/Button'
gives this error: `TS1192: Module ''react-bootstrap/lib/Button'' has no default export.`

And when I do `import {Button} from 'react-bootstrap/lib/Button'` then Button is undefined

tsconfig.json:

    {
      "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "commonjs",
        "target": "es5",
        "jsx": "react"
      },
      "exclude": [
        "node_modules"
      ]
    }

webpack:

    ...
            {
              test: /\.tsx?$/,
              loader: "awesome-typescript-loader",
              exclude: /node_modules/
            }
    ...

I even tried using `ts-loader` instead of `awesome-typescript-loader` but the errors are same.

**Comment by andy-ms** [comment]
It looks like `@types/react-bootstrap` doesn't declare individual modules. You could help contribute by breaking apart the current definition into modules.
CC authors @walkerburgin @vsiao @danilojrr @Batbold-Gansukh @octatone @chengsieuly

**Comment by iamsaksham** [comment]
@andy-ms I am new to typescript. Maybe if you can help me with any one component, I'll do the rest then and generate the pull req for that

**Comment by andy-ms** [comment]
I don't know how react-bootstrap is divided, but components would be written just like any other declaration, as in:

**types/react-bootstrap/lib/foo.d.ts**
```ts
export interface Foo { ... };
```

**types/react-bootstrap/index.d.ts**
```ts
export * from "./lib/foo";
```
