### ISSUE TITLE
@types/koa-jwt Property 'unless' does not exist

### ISSUE THREAD

**Issue by winfinit** [DefinitelyTyped/DefinitelyTyped#15880]
- [x] I tried using the `@types/koa-jwt` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @brunokrebs

getting error when using "unless" method:

```
error TS2339: Property 'unless' does not exist on type 'Middleware<Context>'.
```

unit test:

```typescript
import koa = require('koa');
import jwt = require('koa-jwt');

const app = new koa();

app.use(jwt({
    secret: 'some-secret-key'
}));

app.use(jwt({
    secret: 'some-secret-key',
    key: 'auth'
}));

app.use(jwt({
    secret: 'some-secret-key'
}).unless({method: 'OPTIONS'}));
```

tsc command:

```
winfinit$ tsc -p .
koa-jwt-tests.ts(17,4): error TS2339: Property 'unless' does not exist on type 'Middleware<Context>'.
```

**Comment by winfinit** [comment]
PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15881

**Comment by steveklebanoff** [comment]
Looks like PR was merged, can we close this issue?
