### ISSUE TITLE
Bug: Typings not being published to npm

### ISSUE THREAD

**Issue by alan-agius4** [DefinitelyTyped/DefinitelyTyped#15885]
I have recently updated commander typings in PR #15706, Stylelint #15749 and Fs-extra #15577, the PRs where merged however the typings have not been published. Usually they are published upon merge.

https://www.npmjs.com/package/@types/commander
https://www.npmjs.com/package/@types/fs-extra-promise
https://www.npmjs.com/package/@types/fs-extra
https://www.npmjs.com/package/@types/stylelint

**Comment by alan-agius4** [comment]
@andy-ms @borisyankov 

Can someone help please?

**Comment by alan-agius4** [comment]
@DanielRosenwasser, @andy-ms, @borisyankov, @blakeembrey 

Can someone help please?

**Comment by alan-agius4** [comment]
seems like typings for fs-extra, fs-extra-promise and commander, were published all at once.

**Comment by dpoetzsch** [comment]
The same applies for the changes made in PR #15785 for `parse`. Meanwhile, other packages have been updated, only `@types/parse` hasn't.

**Comment by alan-agius4** [comment]
Same applies for
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15807

**Comment by andy-ms** [comment]
Azure is down. I'll publish manually once in a while until it's fixed.

**Comment by alan-agius4** [comment]
Thanks

**Comment by platzhersh** [comment]
Is this still an issue? The npm package seems to have not been updated since 28th of March

**Comment by andy-ms** [comment]
@platzhersh Which package?

**Comment by platzhersh** [comment]
the @types/numeral package: https://www.npmjs.com/package/@types/numeral

**Comment by andy-ms** [comment]
That hasn't been touched on DefinitelyTyped since March 28. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/numeral/index.d.ts

**Comment by platzhersh** [comment]
Hmm.. I have problems using the locales, so I have to follow https://github.com/adamwdraper/Numeral-js/issues/415 to get it working

**Comment by andy-ms** [comment]
If there's a problem with the definitions, you could make a pull request here fixing it.
Don't know why @darkkean concluded that issue to be a TypeScript error, though, since it has a stacktrace.
Is the error that `locale(key? string): string;` should be given a second parameter for options such as `delimiters`?

**Comment by alan-agius4** [comment]
@platzhersh  Seems like the problem is this `Breaking change: The locale function no longer loads locales, it only sets the current locale`

https://github.com/adamwdraper/Numeral-js

From what I understand you need to load the locales now

**Comment by a-k-g** [comment]
I just updated the types for `node-forge` (#16665) and would like to start using them. However, it doesn't seem to have published yet. Also, I'm not clear about the version number, it says 0.6.8 on https://www.npmjs.com/package/@types/node-forge but the DefinitelyTyped repo only ever mentions 0.6.43 for `node-forge`.

**Comment by a-k-g** [comment]
Seems to have been published now as 0.6.9. Thanks!

**Comment by seanbright** [comment]
@andy-ms, could give types publisher a nudge? Looks like 9340ad9a was the last thing published to npm and that was ~3 days ago.
