### ISSUE TITLE
Lo-Dash: Lo-Dash in @types in npm is not compiling.

### ISSUE THREAD

**Issue by HarelM** [DefinitelyTyped/DefinitelyTyped#15888]
- [x] I tried using the `@types/lodahs` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @bczengel, @chrootsu, @stepancar, @ericanderson

When I use the currently available lodash typing I receive a compilation error:
```
.../node_modules/@types/lodash/index.d.ts(12847,29): error TS2304: Cannot find name 'object'.
.../node_modules/@types/lodash/index.d.ts(19587,33): error TS2304: Cannot find name 'object'.
```
When changing the following two lines to Object (with capital letter) the compilation succeeds.

index.d.ts header:
```
// Type definitions for Lo-Dash 4.14
// Project: http://lodash.com/
// Definitions by: Brian Zengel <https://github.com/bczengel>, Ilya Mochalov <https://github.com/chrootsu>, Stepan Mikhaylyuk <https://github.com/stepancar>, Eric L Anderson <https://github.com/ericanderson>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.2
```

**Comment by ericanderson** [comment]
Sounds like you need to upgrade your version of typescript

**Comment by HarelM** [comment]
I'm using 2.1.5. I'll update to 2.2 but the fact is that the file has inconsistencies.

**Comment by ericanderson** [comment]
It may have inconsistencies, but `object` is correct over `Object`. Pull requests for other places that may be wrong are welcome.

If you cant or dont want to upgrade, I believe you can `npm install @types/lodash@ts2.1` if you want to lock to the last time it was compatible with 2.1.

**Comment by ericanderson** [comment]
For your own reference: https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#object-type

**Comment by HarelM** [comment]
Thanks for sharing. I have added an msbuild typescript nuget package to compile my typescript files.
I can rename this issue to inconsistency in lodash object definition if you want since I think this is the only issue here.
Thanks for the quick response, keep up the good work!

**Comment by Delagen** [comment]
#12394

**Comment by JonathanEckman** [comment]
How do you specify the compiler tag in the package.json? `"lodash@ts2.1": "^4.17.2"` does not work.

**Comment by andy-ms** [comment]
@JonathanEckman `npm install --save-dev @types/lodash@ts2.1`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
