### ISSUE TITLE
L.mapbox.accessToken is a const where it should be set-able

### ISSUE THREAD

**Issue by rhwilburn** [DefinitelyTyped/DefinitelyTyped#15898]
I tried using the `@types/mapbox` package and had problems.
The author appears to be: @andy-ms 

I have noticed that the accessToken is a const here: [https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/mapbox/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/mapbox/index.d.ts)

This doesn't allow me to add an access token as I do in my project currently by using the following code:

```
        if (webGlEnabled) {
            // Enable MapboxGL Access
            mapboxgl.accessToken = mapboxApiKey;
        } else {
            // Enable MapboxJS Access
            L.mapbox.accessToken = mapboxApiKey;
        }
```

Should this const field be a let or var instead like the mapbox-gl one here: [https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/mapbox-gl/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/mapbox-gl/index.d.ts)

The error I get is:

> left hand side of assignment cannot be constant

If @andy-ms is happy with the change, I can prep a pull request.

**Comment by andy-ms** [comment]
Fixed in #15907
