### ISSUE TITLE
Facebook-Js-SDK sharedialogparams needs picture property added to match JS functionality

### ISSUE THREAD

**Issue by rhwilburn** [DefinitelyTyped/DefinitelyTyped#15908]
I tried using @types/facebook-js-sdk and found it doesn't support the picture property on sharedialogparams. I was using version: 2.8.1 (latest at the time of writing this). This type definition is written by: Amrit Kahlon <https://github.com/amritk/> @amritk

The following as an example is not supported by type definition because 'picture' is not on the type:

`        FB.ui({
            method: 'share',
            href: 'https://www.routeme.co.nz',
            picture: 'https://cdn1.kongcdn.com/assets/avatars/defaults/robotboy.png?i10c=img.resize(width:28)'
        }, response => { });`

This should be supported as shown here on: [stackoverflow](http://stackoverflow.com/questions/23781698/fb-ui-share-set-the-title-message-and-image). Facebooks documentation doesn't show that you can set your own image, however alot of sources indicate this is supported, including facebooks own test tool here: [fbrell.com](http://www.fbrell.com/saved/809b6c409f3c8dd307023cd78cdb6111) with the following code:

`
<div class="page-header">
  <h1>Mobile Web Share Dialog</h1>
</div>

<p>Run this code on a mobile device or emulator. Tap the button below to trigger a Share Dialog</p>

<div id="shareBtn" class="btn btn-success clearfix">Share</div>

<p style="margin-top: 50px">
  <hr />
  <a class="btn btn-small"  href="https://developers.facebook.com/docs/sharing/reference/share-dialog">Share Dialog Documentation</a>
</p>

<script>
document.getElementById('shareBtn').onclick = function() {
  FB.ui({
    method: 'share',
    mobile_iframe: true,
    href: 'https://developers.facebook.com/docs/',
    picture: 'https://cdn1.kongcdn.com/assets/avatars/defaults/robotboy.png?i10c=img.resize(width:28)'
  }, function(response){});
}
</script>
`

You can compare that to if the picture field is ommitted seeing the original https://developers.facebook.com/docs/ image made by facebook.

I believe this should be added to the sharedialogparams definition, and will do this soon

**Comment by andy-ms** [comment]
Please fill in the [issue template](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by rhwilburn** [comment]
Ive added the info required by the template in the top of the original post. I can't find that user under the @ symbol.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
