### ISSUE TITLE
babel-types FunctionExpression params is incorrectly defined

### ISSUE THREAD

**Issue by athasach** [DefinitelyTyped/DefinitelyTyped#15914]
@yortus I'm using `@types/babel-types` and came across this issue.

According to the documentation for `FunctionExpression` located here: https://babeljs.io/docs/core-packages/babel-types/#apifunction-expression, `params` should be an `Array<LVal>` instead of `Array<Pattern>`.

Right now, `FunctionExpression` is defined as:

```typescript
export interface FunctionExpression extends Node {
    type: "FunctionExpression";
    id: Identifier;
    params: Pattern[]; // <---- Should be LVal[]
    body: BlockStatement;
    generator: boolean;
    async: boolean;
    returnType?: TypeAnnotation;
    typeParameters?: TypeParameterDeclaration;
}
```

which means that `params` cannot include an `Identifier` since `Identifier` is not a `Pattern`.

You can see an example of a `FunctionExpression` with an `Identifier` parameter if you parse the following code in https://astexplorer.net

```javascript
const fn = function(x) {
  return x;
}
```

**Comment by yortus** [comment]
Hi @athasach, I doubt I'll get onto this or #15924 anytime soon. Hopefully someone else can take the time to make the changes. Could you perhaps submit a PR in your private time, to avoid problems with your employer?

**Comment by athasach** [comment]
@yortus Thanks for the quick response. I'll see what I can do.

**Comment by athasach** [comment]
This was fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15973
