### ISSUE TITLE
babel-traverse NodePath<T>.get(...) should also return Array<NodePath<Node>>

### ISSUE THREAD

**Issue by athasach** [DefinitelyTyped/DefinitelyTyped#15924]
@yortus I'm using `@types/babel-types` and came across this additional issue.

`NodePath<T>.get` is currently defined as:

```typescript
get(key: string, context?: boolean | TraversalContext): NodePath<Node>;
```

But `get` returns an array of `NodePath<Node>` objects when `key` indicates an array value. This issue can be addressed if the declaration is redefined to include this possibility:

```typescript
get(key: string, context?: boolean | TraversalContext): NodePath<Node> | NodePath<Node>[];
```

**Comment by athasach** [comment]
See also: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15914#issuecomment-294807803

**Comment by athasach** [comment]
Actually, this is in babel-traverse, not babel-types.

See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/babel-traverse/index.d.ts

**Comment by cameron-martin** [comment]
This has now been fixed: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8ff7e8f29e059f3799c19e0bafb7ac010786ca50/types/babel__traverse/index.d.ts#L423
