### ISSUE TITLE
Angular 4.0.2 UNMET PEER DEPENDENCY 

### ISSUE THREAD

**Issue by limpep** [DefinitelyTyped/DefinitelyTyped#15938]
- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

I ran the following command `npm install --save @types/lodash` and got the following errors 

```
├── UNMET PEER DEPENDENCY @angular/common@4.0.2
├── UNMET PEER DEPENDENCY @angular/compiler@4.0.2
├── UNMET PEER DEPENDENCY @angular/core@4.0.2
├── @types/lodash@4.14.62
└── UNMET PEER DEPENDENCY tslint@5.1.0

```
Using the following command seem to work `npm install @types/lodash@ts2.2 --save-dev` but not sure if it is correct. Thanks

**Comment by andy-ms** [comment]
The peer dependency appears to be from the thing *requiring* `@types/lodash`. Just use `npm info @types/lodash` to see its own peer dependencies (there are none).
