### ISSUE TITLE
Is there a conflict between @types/node and @types/react-native?

### ISSUE THREAD

**Issue by bherila** [DefinitelyTyped/DefinitelyTyped#15960]
- [X] I tried using the `@types/node` and `@types/react-native` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @gyzerok 

Both of the modules seem to define `require` and this results in some compliation trouble: 

```
../node_modules/@types/node/index.d.ts(49,13): error TS2451: Cannot redeclare block-scoped variable 'global'.
../node_modules/@types/node/index.d.ts(73,13): error TS2300: Duplicate identifier 'require'.
../node_modules/@types/react-native/index.d.ts(8541,11): error TS2451: Cannot redeclare block-scoped variable 'global'.
../node_modules/@types/react-native/index.d.ts(8542,14): error TS2300: Duplicate identifier 'require'.
```

Any tips/workarounds?

**Comment by gyzerok** [comment]
@bherila can you, please, create a [SSCCE](http://sscce.org/) repository which one can run by himself?

**Comment by alloy** [comment]
It’s true, there are conflicts between the two. RN provides _some_ features that people are used to from Node (e.g. `require`), however it is definitely not a full-fledged Node environment, so using the Node typings isn’t really correct.

In the end, we solved it by removing the Node typings and just sprinkle a few typings here and there where they were really needed, e.g. in our Jest setup which _does_ run on Node: https://github.com/artsy/emission/pull/453/commits/25f296c7fe1eca268ad0b58d3c251de7b27dcf7f#diff-0b93f41d9b1048bf2a2e50b4036a898aR2

**Comment by rawrmaan** [comment]
@bherila I run this bash script whenever I do a full npm install (and in my npm postinstall script so I can deploy to Heroku. It replaces the global definitions in the RN typings with nonsense so everything compiles nicely: https://gist.github.com/rawrmaan/be47e71bd0df3f7493ead6cefd6b400c

**Comment by bherila** [comment]
Also, for some reason updating to the latest typings of each, and the latest typescript made the problem go away, although I still feel like it isn't "solved" per se :(

But I'll close the issue for the time being. That script also looks helpful, thanks @rawrmaan

**Comment by alloy** [comment]
Good to know 👍

**Comment by dieseldjango** [comment]
I'm running into this problem with my react-native project via a transitive dependency ing react-native-code-push, which through a chain of dependencies installs a package developed in TypeScript for node, which installs @types/node as its own dependency. I hacked around this by removing @types/node in my postinstall script. I could probably also use @rawrmaan's hack, but I'm wondering what the "right" way to deal with this would be.

Should the package that pulls in @types/node not declare it as a dependency? That would leave  types in their own type definition unresolved until the consumer of the package pulls in @types/node. They could declare @types/node as a peerDependency, but then non-node consumers such as myself would get a bogus missing peer warning. Or is this a problem for the react-native-code-push package, which needs to be somehow refactored to eliminate the node dependency?

**Comment by harisvsulaiman** [comment]
@dieseldjango have you solved this?, I'm also encountering this issue.

**Comment by chetmurphy** [comment]
I'm still hitting the problem with typescript 2.5.2, @types/react-native 0.48.0, and @types/node 8.0.22. I'm removing the errors by commenting out the declarations in @types/node and @types/react-native one by one (running tsc each time) starting with the top most error.

**Comment by jcampbell05** [comment]
This is a huge problem with my app which is cross platform since electron pulls it in. One solution is to structure your project in a way to have the dependencies not conflict (have electron and RN as separate packages)

Easier said than done.

**Comment by evanjmg** [comment]
+1 - please fix this. getting with latest everything

**Comment by ou2s** [comment]
+1 I have the issue with RN 0.48.4

**Comment by jcampbell05** [comment]
Is there a way of maybe getting react native to depend on the node type definition instead of rolling it's own ?

**Comment by alloy** [comment]
Alas, RN can’t pull in the node definitions, because RN doesn’t run inside node and so TS wouldn’t be able to tell you that certain APIs are not available.

We maintainers of the RN typings are all for accepting a solution, but please note that +1s are not going to help, the RN typings are completely driven by the needs of the maintainers and contributors.

**Comment by alloy** [comment]
@dieseldjango Alas, the only way to currently do it is indeed to specify it as a peer dependency and leave it up to user to decide what is right for their project.

**Comment by chetmurphy** [comment]
A solution that works for me is to define the types that my project is using in tsconfig.json leaving out the node typing’s like this:

"types": [
      "mathjs",
      "react",
      "react-native",
      "react-native-drawer",
      "react-native-orientation",
      "react-navigation",
      "jest"
    ],

This eliminates the conflict even though node.d.ts is in node_modules @types.
________________________________

**Comment by evanjmg** [comment]
@chetmurphy thanks that is definitely the cleanest workaround

**Comment by jcampbell05** [comment]
@alloy is there a way of including that workaround somehow in the typings ? i.e in documentation or just by having it in a comment at the top of the file

**Comment by alloy** [comment]
I don’t really know if it will be read when added as a comment to the top of the file, it won’t automatically show up anywhere. People looking for this specific problem may just find this issue and maybe it’s helpful advice in general that can be added to the wiki maybe? https://github.com/DefinitelyTyped/DefinitelyTyped/wiki

cc @andy-ms

**Comment by andy-ms** [comment]
@alloy Maybe we could add this information to the duplicate-var error message itself, since that will usually be caused by conflicting types that were automatically included. See Microsoft/TypeScript#19356. CC @mhegazy

**Comment by jcampbell05** [comment]
@andy-ms that would be a great compromise for me :) and would have saved many wasted hours.

**Comment by alloy** [comment]
@andy-ms Agreed, helpful errors are the best. I’d like to PR that, are you suggesting to add something to the error message like the following?

> "Subsequent variable declarations must have the same type.  Variable '{0}' has type '{1}' at {2}, but here has type '{3}'. If conflicting type definitions are being pulled in as dependencies, consider using the `types` compiler option to selectively enable the correct type definitions for your project."

**Comment by andy-ms** [comment]
Should check with @mhegazy first since the first PR was reverted.

**Comment by savovs** [comment]
I'm getting this error and none of the common workarounds work for me. Following this guide with latest everything: https://github.com/Microsoft/TypeScript-React-Native-Starter

**Comment by corydeppen** [comment]
Is the TS community really okay with a workaround like this? Seems a bit odd that we need to explicitly list types our projects are using after they've already been installed, being careful to make sure none are missed.

**Comment by corydeppen** [comment]
Additionally, this workaround doesn't seem valid if your app makes use of any environment variables (e.g. `process.env.REACT_APP_VAR`), as you'd be relying on `@types/node`.

**Comment by andy-ms** [comment]
@corydeppen 

Quoting @alloy:
> RN provides some features that people are used to from Node (e.g. require), however it is definitely not a full-fledged Node environment

Based on this, you shouldn't reference `@types/node` and should rely only on what's in `@types/react-native`. So if `process.env` is available at runtime, it should probably be added to `@types/react-native`.

**Comment by corydeppen** [comment]
@andy-ms My app doesn't use `@types/react-native` directly. I'm seeing this problem using Formik, which references this issue in a [comment](https://github.com/jaredpalmer/formik/blob/master/src/formik.tsx#L15-L25). The Formik source worked around the issue, but I'm assuming I'm seeing it as well because I'm using `process.env` in my React app. It seems crazy to think anyone running into this problem needs to list out all their types, remove `@types/node`, and duplicate Node's `process` definition.

**Comment by andy-ms** [comment]
@corydeppen Is Formik a library that sometimes runs in a node environment but sometimes is loaded in a react-native environment?
Also, how does your app end up using `@types/react-native` indirectly?

**Comment by corydeppen** [comment]
@andy-ms The changes to Formik were actually just [reverted](https://github.com/jaredpalmer/formik/commit/c8de953dfe90f2cbb418164f17c1c8ee8eef48ec).

**Comment by kristerkari** [comment]
Would be nice to get a proper fix for this issue. I'm using `@types/react-native` in my project, but I have some dependencies that are using `@types/node` and that's why I can't get rid of this error.

Using `compilerOptions.types` does not work for me, because if have a few custom `.d.ts` files in my project where types are defined.

I can use `"skipLibCheck": true` to silence the error, but it is a bad workaround because it silences errors from other packages too.

**Comment by ScreamZ** [comment]
I'm encountering the same issue, one fix can be to make `@types/react-native` to have a dependency  (or peerDependency) on `@types/node`. This should not conflict in that case.

I also noticed that 

```json
{
    "lib": ["dom"]
}
```

Must be added in order to prevent those messages to appear, it looks strange to me, why DOM is required in a react native app ? I'm pretty sure there is another way to achieve that goal.

```
node_modules/@types/react-native/globals.d.ts(24,31): error TS2304: Cannot find name 'RequestInfo'.
node_modules/@types/react-native/globals.d.ts(24,51): error TS2304: Cannot find name 'RequestInit'.
node_modules/@types/react-native/globals.d.ts(24,73): error TS2304: Cannot find name 'Response'.
```

Regards

**Comment by danwoodbury** [comment]
has anybody found a resolution for this? Adding types to my compiler options does not work for me for some reason. I am trying to include a swagger TS api client into our app and this problem is stopping me from doing that and as you can imagine and API client is quite integral.

**Comment by kevinsperrine** [comment]
@danwoodbury I just added a postinstall script to package.json to comment out the node.js definition of require since I'm working in RN. Ref: https://github.com/aws/aws-amplify/issues/281#issuecomment-370049435

**Comment by danwoodbury** [comment]
@kevinsperrine thanks. Did you add that to the incoming package? Mine is failing in the build script of the incoming package

**Comment by kevinsperrine** [comment]
@danwoodbury I added it to my project's package.json as a postinstall script so that anytime there's an install it ensures the node require is commented out and allows my project to build. ie: 

```
{
  name: "my-project",
  scripts: {
      "postinstall": "./scripts/postinstall.sh"
  },
  "dependencies": {
    "aws-amplify": "^0.2.9",
    "aws-amplify-react-native": "^0.2.5",
    "react-native": "0.54.2",
  },
  "devDependencies": {
    "@types/node": "^9.4.7",
    "@types/react-native": "^0.52.18",
  }
}
```

**Comment by danwoodbury** [comment]
@kevinsperrine thanks but that dosnt seem to work for me. It fails before it gets to that point when running `yarn add ...` and when I run `yarn install` i get the error `sed: can't read s/\(^declare var require: NodeRequire;\)/\/\/\1/g: No such file or directory` although the file is quite clearly there as I can see it in front of my own eyes

**Comment by danwoodbury** [comment]
nope, same error. I can even find the line within the file it is targeting. Very strange

**Comment by kevinsperrine** [comment]
@danwoodbury Very. Hope you can get it straightened out. sed has different parameters depending on platform, so you might try checking into that.

**Comment by danwoodbury** [comment]
yeh odd, Will have a look into it, worst case I will just have to build the fetch commands manually until I can get this figured out. Thanks for the help

**Comment by kristerkari** [comment]
Using @kevinsperrine's post install script works as a good workaround for me. 

The only thing that you have to take into account is that there are some platform differences with `sed` command. So `sed -i ''` works nicely on OS X, but was failing for me on the linux CI server.

If the `sed` command fails for you, then you can use something else to do the regex replacement, or implement a workaround to support all platforms:
https://stackoverflow.com/a/38595160

**Comment by elnygren** [comment]
Consider reopening the issue, it still exists with

```
  "devDependencies": {
    "@types/graphql": "^0.13.4",
    "@types/node": "^10.9.2",
    "@types/react": "^16.4.12",
    "@types/react-native": "^0.56.14",
    "typescript": "^3.0.1"
```

I'm using Expo SDK v28.0.0 that is based on React Native 0.55.4

**Comment by epeli** [comment]
There's an open issue here https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16825

**Comment by Kstar0722** [comment]
I got the same issue.

"react": "16.5.0",
"react-native": "^0.57.2",
"@types/react-native": "^0.46.7",
"@types/node": "^10.11.7",

**Comment by ch1ll0ut1** [comment]
Also same problem with react native and expo

**Comment by henrikra** [comment]
Does React Native has custom versions of `console` and `require`? If not then it doesn't make sense that React Native defines them in its types

**Comment by henrikra** [comment]
It is common to get node types for example if you want to run your unit tests with TypeScript. In this case you need to use `ts-node` which includes node types

**Comment by alloy** [comment]
I get that, we have that issue too, but the _actual_ RN env (your production env) is not node and so that’s what should take precedence imo. In our case we added a few tiny type defs to our test suite.

**Comment by henrikra** [comment]
What you are using to run your tests with TypeScript? I am using `ts-node` and it's dependency is @types/node so they are always included :/

**Comment by alloy** [comment]
Currently we still use `ts-jest` https://github.com/artsy/emission/blob/f38ad50c76219943738ae901e090e4d8d9db6b69/package.json#L149-L151, but we’re in the process of switching over the entire app and tests to be just babel 7 with its TS support.
