### ISSUE TITLE
sharepoint npmjs has wrong project in summary

### ISSUE THREAD

**Issue by StefanSchoof** [DefinitelyTyped/DefinitelyTyped#15965]
- [x] I tried using the `@types/sharepoint` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

The npmjs project description for https://www.npmjs.com/package/@types/sharepoint is outdated and no longer valid. Currently there stands:
```
This package contains type definitions for SharePoint: 2010.1 / (https:// github.com/gandjustas/sptypescript).
```
The link to the github project is outdated since this is now here. And this is not limited to SharePoint 2010 So better:
```
This package contains type definitions for Microsoft SharePoint.
```

**Comment by andy-ms** [comment]
That is determined based on the first two lines of the file. You could make a pull request updating them.
