### ISSUE TITLE
Please add back fast-json-patch as the package does NOT ship it's typings.

### ISSUE THREAD

**Issue by SimonSchick** [DefinitelyTyped/DefinitelyTyped#15962]
- [x] I tried using the `@types/fast-json-patch` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andy-ms 

Despite the fact that the module IS written in TS, it does NOT ship it's typings, that might not be their intention, I will also open an issue there.

**Comment by andy-ms** [comment]
Link: Starcounter-Jack/JSON-Patch#156
The package isn't deleted from NPM and you can still install it. It will just show a deprecation warning.

**Comment by SimonSchick** [comment]
Sorry for not being precise enough, yes, the package is still there, BUT the latest version contains no typings.

Yes, downgrading the version works but that's not a good solution, someone trying to get typings to the package will be immensely mislead by the message as the package does *not* ship it's own typings.

**Comment by andy-ms** [comment]
Oh, right. You can at least use `@types/fast-json-patch@1.0.4` until Starcounter-Jack/JSON-Patch#159 is in.

**Comment by SimonSchick** [comment]
What I'm asking is to entirely revert the last commit until he addresses the issue.

**Comment by andy-ms** [comment]
I reset the `dist-tag`, so installing `latest` should now get you the old types too.

**Comment by SimonSchick** [comment]
Ok, thanks.

**Comment by andy-ms** [comment]
The package has published its typings now, so reset the tags.
