### ISSUE TITLE
angular $injector.invoke() is incorrectly typed (Function no longer supported)

### ISSUE THREAD

**Issue by NicBright** [DefinitelyTyped/DefinitelyTyped#16017]
The problem can be seen here (type "Function" is no longer supported, but it should be):
![image](https://cloud.githubusercontent.com/assets/1225659/25218395/fce6f66c-25aa-11e7-83e6-42675e31d708.png)

- [x] I tried using the `@types/angular` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mgr01 introduced this bug with this commit: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/30b9603742856c86b1424d3bd77da4b140ee89b4
- The original authors: thorn0 + diegovilar (as mentioned on the npm package site https://www.npmjs.com/package/@types/angular) are not supported by github's "mentioning algorithm"

**Comment by mgr01** [comment]
Sorry about that. What should be the return type of invoke() for 'Function'?

**Comment by mgr01** [comment]
I mean, should it be treated as (...args: any[]): {} or (...args: any[]): any? What is the intention in your code?

**Comment by NicBright** [comment]
I'd say `(...args: any[]): any` would be correct, because it can virtually be anything. The intention basically is to be able to loop over a bunch of custom resolve functions (and have them invoked via `$injector`) with some of them returning stuff and others that don't return anything.

**Comment by mgr01** [comment]
Should be fixed by #16042
