### ISSUE TITLE
Pull request builder should give preview of types-publisher results

### ISSUE THREAD

**Issue by efokschaner** [DefinitelyTyped/DefinitelyTyped#16014]
@andy-ms @RyanCavanaugh
I recently submitted a PR that had some unexpected results when run through the types-publisher. See [this follow-up PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16013) for context and an attempted fix.

This made me realise it would be nice to get more feedback from the types-publisher step as part of the pull request build. Maybe something as far-fetched as having the PRB generate a real pre-release package on npm so that end-to-end testing with the PR's npm package can be done?

**Comment by andy-ms** [comment]
I don't think this will be necessary if we properly ban a `.d.ts` from appearing in a test folder. Then the publish will just be the files you wrote plus a `package.json` and `README.md` generated automatically.

**Comment by efokschaner** [comment]
Thanks @andy-ms, that would definitely help in the specific situation i was in. Feel free to close this issue if there's nothing else we want to do on this matter.
