### ISSUE TITLE
Use React Native Librairies (like FormData)

### ISSUE THREAD

**Issue by pierre-H** [DefinitelyTyped/DefinitelyTyped#16037]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @gyzerok 

Actually, it's impossible to import class from the Librairies/Network folder like https://github.com/facebook/react-native/blob/master/Libraries/Network/FormData.js . Is it possible to add this ?

**Comment by alloy** [comment]
I’m not sure what you mean by it being “impossible to import”, but sure you can submit a PR to add typings for the `FormData` class 👍

**Comment by pierre-H** [comment]
@alloy Done : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16039

**Comment by alloy** [comment]
Going to close this in favour of the PR.
