### ISSUE TITLE
proposal: unify duplicate typings between `swaggerize-express` and `swagger-schema-official`

### ISSUE THREAD

**Issue by bsouthga** [DefinitelyTyped/DefinitelyTyped#16046]
- [x] I tried using the `@types/swaggerize-express` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

Currently both `swaggerize-express` and `swagger-schema-official` have complete type definitions for the openAPI specification. However, there are a few slight inconsistencies between the two which make it hard to use them in tandem. For example:

having installed the following:
- `@types/swaggerize-express@4.0.28`
- `@types/swagger-schema-official@2.0.2`

The following issues a compiler error (under `typescript@2.2.2`): 

```typescript
import * as swaggerize from 'swaggerize-express';
import { Spec } from 'swagger-schema-official';

declare var spec_swagger_schema_official: Spec;
declare var spec_swaggerize_express: swaggerize.Swagger.ApiDefinition;

/**
 * type error here, when the object should be of the same type,
 * as both should be valid openAPI schema
 */
spec_swagger_schema_official = spec_swaggerize_express;
```

Specifically,

```
[ts]
Type 'ApiDefinition' is not assignable to type 'Spec'.
  Types of property 'definitions' are incompatible.
    Type 'DefinitionsObject | undefined' is not assignable to type '{ [definitionsName: string]: Schema; } | undefined'.
      Type 'DefinitionsObject' is not assignable to type '{ [definitionsName: string]: Schema; } | undefined'.
        Type 'DefinitionsObject' is not assignable to type '{ [definitionsName: string]: Schema; }'.
          Index signatures are incompatible.
            Type 'SchemaObject' is not assignable to type 'Schema'.
              Types of property 'allOf' are incompatible.
                Type 'IJsonSchema[] | undefined' is not assignable to type 'Schema[] | undefined'.
                  Type 'IJsonSchema[]' is not assignable to type 'Schema[] | undefined'.
                    Type 'IJsonSchema[]' is not assignable to type 'Schema[]'.
                      Type 'IJsonSchema' is not assignable to type 'Schema'.
                        Types of property 'allOf' are incompatible.
                          Type 'IJsonSchema[] | undefined' is not assignable to type 'Schema[] | undefined'.
                            Type 'IJsonSchema[]' is not assignable to type 'Schema[] | undefined'.
                              Type 'IJsonSchema[]' is not assignable to type 'Schema[]'.
                                Type 'IJsonSchema' is not assignable to type 'Schema'.
```

My proposal would be to use `@types/swagger-schema-official` within  `@types/swaggerize-express` so there is only one location to maintain, and we don't run into minor inconsistencies.

Authors of both definitions (@mohsen1 for `@types/swagger-schema-official` and @mugeso for `@types/swaggerize-express`) have any thoughts?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
