### ISSUE TITLE
loopback types have not hook remote

### ISSUE THREAD

**Issue by richardgong1987** [DefinitelyTyped/DefinitelyTyped#16048]
- [ ] I tried using the `@types/loopback` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
```js
import {User} from "loopback";
class user {
  constructor(public user:User) {
      this.user.afterRemote('create', (req,res,next)=>{})
  }
}

export  = user;
```
expected the Remote hook should be avaible
 
here is office doc: http://loopback.io/doc/en/lb3/Remote-hooks.html

  - Authors: @andy-ms

**Comment by andy-ms** [comment]
You could make a pull request adding it.
Also, the author is @kattsushi.

**Comment by richardgong1987** [comment]
ok.
