### ISSUE TITLE
[ReactNative] missing onScroll on FlatList

### ISSUE THREAD

**Issue by Dimous** [DefinitelyTyped/DefinitelyTyped#16058]
@alloy, @gyzerok 

severity: 'Ошибка'
Property 'onScroll' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<FlatListProperties<any>, ComponentState>...'.'

**Comment by alloy** [comment]
It’s also missing from the docs: https://facebook.github.io/react-native/docs/flatlist.html

Can you please figure out what the complete API is and create a PR for it? I’m closing this ticket because it’s otherwise not a very actionable thing for us.

**Comment by Dimous** [comment]
Its inherited from VirtualizedList.defaultProps

**Comment by alloy** [comment]
Ok. Will you create a PR?
