### ISSUE TITLE
chai.assert.throws can take an errType: Function | RegExp

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DefinitelyTyped/DefinitelyTyped#16067]
The types indicate it has to be one of the following overloads:

```typescript
throws(fn: Function, message?: string): void;
throws(fn: Function, regExp: RegExp): void;
throws(fn: Function, errType: Function, message?: string): void;
throws(fn: Function, errType: Function, regExp: RegExp): void;
```

This should be allowed:

```typescript
throws(fn: Function, regExp: RegExp, message?: string): void;
```

**Comment by damix911** [comment]
@JoshuaKGoldberg Thank you for this fix.

The Chai docs seem to suggest that a 4-parameter form is possible: https://www.chaijs.com/api/assert/#method_throws

And indeed the source itself seem to agree: https://github.com/chaijs/chai/blob/master/chai.js#L6148

I am not sure what the typings should look like for it though.
