### ISSUE TITLE
lodash: isArray should not accept a type parameter

### ISSUE THREAD

**Issue by aj-r** [DefinitelyTyped/DefinitelyTyped#16077]
From [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes):

> `getMeAT<T>(): T`: If a type parameter does not appear in the types of any parameters, you don't really have a generic function, you just have a disguised type assertion.

So I'm saying that this:

```
interface LoDashStatic {
    isArray<T>(value?: any): value is T[];
}
```

should become this:

```
interface LoDashStatic {
    isArray(value?: any): value is any[];
}
```

The tests for this function are also inaccurate:

```
let value: number|string[]|boolean[] = [];

if (_.isArray<string>(value)) {
    let result: string[] = value;
} else {
    if (_.isArray<boolean>(value)) {
        let result: boolean[] = value;
    } else {
        let result: number = value;
    }
}
```

This isn't how `_.isArray` works - it does NOT check if the array is a specific type of array (string[], boolean[], etc.). It only checks if the value is an array.

I've already tested my proposed solution and it does apply the type guard correctly, e.g. `number|string[]|boolean[]` becomes `string[]|boolean[]`  if the result is true, or `number` if the result is false.

I can submit a PR since this should be a really easy fix.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @ericanderson

**Comment by aj-r** [comment]
Same for `isArrayLike` and `isArrayLikeObject`

**Comment by ericanderson** [comment]
I think I agree with you here mostly. There should probably be a simple case for `T[] | any` to be passed in (assuming it works)

```ts
const foo: number[] | string = getFoo();
if (_.isArray(foo) && foo.length > 0) {
  foo[0]; // we can safely infer this is a number.
}
```

**Comment by aj-r** [comment]
Yes, that case would be handled by my proposed definition - `isArray(value?: any): value is any[];`

Typescript is smart enough to recognize that `number[]` is the only available type (out of `number[] | string`) that is compatible with `any[]`, so foo will be of type `number[]` inside the type guard.

**Comment by aj-r** [comment]
Turns out `isArrayLike` and `isArrayLikeObject` are a lot more complicated. I think I've found a solution for them but it seems a bit hacky.
