### ISSUE TITLE
[karma-chai] Description on npm is incorrect.

### ISSUE THREAD

**Issue by JayAndCatchFire** [DefinitelyTyped/DefinitelyTyped#16080]
The description for `@types/karma-chai` on npm is incorrect in that it claims there are no global values.  In truth, there are three: `should`, `expect`, and `assert`.

https://www.npmjs.com/package/@types/karma-chai

**Comment by JayAndCatchFire** [comment]
I was the author of `@types/karma-chai`.  Did I do something wrong to cause the generated description to be incorrect?

**Comment by andy-ms** [comment]
Tracked by Microsoft/types-publisher#340.
