### ISSUE TITLE
Getting error "Cannot find module lodash"

### ISSUE THREAD

**Issue by epitka** [DefinitelyTyped/DefinitelyTyped#16099]
- [yes ] I tried using the `@types/xxxx` package and had problems.
- [ yes] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ yes] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

I have aurelia app with jspm. I followed this process to install lodash  and I cann see it under jspm_modlues and npm/@types

jspm install lodash

npm install @types/lodash

In my script file I have following

import {inject} from "aurelia-framework";
import * as moment from "moment";
import * as _ from "lodash";

Lodash gets red line with message "Cannot find module lodash"

Ctrl + click takes me to index.d.ts file that is type definition for lodash
// Type definitions for Lo-Dash 4.14
Here some lines are also underlined with errors, such as this one

export as namespace _;   export is underlined with message Declaration or statement expected. And so on.

jspm config.js file under map has    

 "typescript": "npm:typescript@2.2.2",
 "lodash": "npm:lodash@4.17.4",

Any ideas what is wrong? All other libraries work fine, and I followed same process.

**Comment by Delagen** [comment]
#12394

**Comment by andy-ms** [comment]
Don't think this is related to #12394.
Use [`--traceResolution`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) to see where TypeScript is looking for lodash.
I do find it mysterious that you can go to the type definition but are still getting a module-not-found error in services, though!

**Comment by Delagen** [comment]
It does not related to lodash module. Current typing does not define way to work with NodeJs app where no global vars. So code without import does not work

**Comment by epitka** [comment]
@Delagen: Not sure i follow "So code without import does not work". I am importing it at the top of the file.
import {inject} from "aurelia-framework";
import * as moment from "moment";
import * as _ from "lodash";

**Comment by epitka** [comment]
@andy-ms Here is what tsc --traceResolution outputs. This is really weird

======== Resolving type reference directive 'lodash', containing file 'c:/bitbucket/sa/sav3/src/SAV3/__inferred type names__.ts', root directory 'c:/bitbucket/sa/sav3/src/SAV3/node_modules/@types'. ========
Resolving with primary search path 'c:/bitbucket/sa/sav3/src/SAV3/node_modules/@types'
Found 'package.json' at 'c:/bitbucket/sa/sav3/src/SAV3/node_modules/@types/lodash/package.json'.
'package.json' does not have a 'typings' field.
'package.json' does not have a 'types' field.
File 'c:/bitbucket/sa/sav3/src/SAV3/node_modules/@types/lodash/index.d.ts' exist - use it as a name resolution result.
Resolving real path for 'c:/bitbucket/sa/sav3/src/SAV3/node_modules/@types/lodash/index.d.ts', result 'c:/bitbucket/sa/sav3/src/SAV3/node_modules/@types/lodash/index.d.ts'
======== Type reference directive 'lodash' was successfully resolved to 'c:/bitbucket/sa/sav3/src/SAV3/node_modules/@types/lodash/index.d.ts', primary: true. ========

**Comment by andy-ms** [comment]
@epitka The `__inferred type names__.ts` message is because lodash was inferred as a types dependency. See [`--types`](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types).
@Delagen If you don't use global variables, you need to use imports -- so why not use them?

**Comment by Delagen** [comment]
@andy-ms see example from #12394

**Comment by hsluoyz** [comment]
Any update on this issue? I encountered a similar issue:

```

  ● Test suite failed to run

    Cannot find module 'lodash' from 'operators.ts'

      15 | import * as rbac from '../rbac';
      16 | import * as ip from 'ip';
    > 17 | import * as _ from 'lodash';
         | ^
      18 | 
      19 | // keyMatch determines whether key1 matches the pattern of key2 (similar to RESTful path),
      20 | // key2 can contain a *.

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (src/util/operators.ts:17:1)

```

**Comment by flip111** [comment]
I have Ghost Version 2.2.2 .. everything seemed fine when i was setting it up. Now when i start to write a blog post i get a red bar on the top. In the network inspector panel i get this response from the server: `{"errors":[{"message":"Cannot find module 'lodash'","errorType":"InternalServerError"}]}`

**Comment by StanislavNemytov** [comment]
Hi, @andy-ms.
You need to use that answer. https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12394#issuecomment-298825183

**Comment by jakebailey** [comment]
This is old, but I don't think this is an issue anymore.
