### ISSUE TITLE
@types/gulp has incompatible types

### ISSUE THREAD

**Issue by rbingham** [DefinitelyTyped/DefinitelyTyped#16110]
The series and parallel method definitions return the wrong type. They currently return NodeJS.EventEmitter and should be returning AddMethodCallback or Function. The reason for this is because the return value for the series and parallel methods are used when creating tasks and the task function takes an AddMethodCallback or Function as one of it's parameters, not NodeJS.EventEmitter.

I am using tsc version 2.1.4

@drewnoakes How should this be handled?

**Comment by drewnoakes** [comment]
My work on the gulp typings is from a while ago and I don't have the context any more.

**Comment by GiedriusGrabauskas** [comment]
Pull request was merged. 👍

**Comment by rbingham** [comment]
That's awesome. Thanks for the update.
