### ISSUE TITLE
React Default Export

### ISSUE THREAD

**Issue by casesandberg** [DefinitelyTyped/DefinitelyTyped#16136]
I have been using the `@types/react` package and it keeps on giving me errors that React does not export a default. It does in fact export a default, I am wondering why you are forced to import React like this: `import * as React from 'react'`

**Comment by Kovensky** [comment]
It does not. The `main` entry point to React is just a file that does `module.exports = require('./lib/React');`.

If you are using typescript's code generation you will have to import `React` with `import * as React`; but if you're using a bundler you should set `allowSyntheticDefaultImports`.

**Comment by casesandberg** [comment]
Sorry, I phrased my statement incorrectly. React exports a single object: (https://github.com/facebook/react/blob/master/src/isomorphic/React.js). 

I am just curious why you can consume and use React and every tutorial to date uses `import React from 'react'` and yet this type definition requires you to use a different import syntax `* as React`?

**Comment by Kovensky** [comment]
Historical reasons, basically; TypeScript implemented the import syntax before it was decided commonjs should appear like a default export instead. Babel, webpack et al implement that, but not typescript.

There are plans to change it, but given how likely it is to be a breaking change it'll probably be behind some flag.

**Comment by casesandberg** [comment]
Ah-- thanks for the clarification.
