### ISSUE TITLE
Type definitions for timezone

### ISSUE THREAD

**Issue by natesilva** [DefinitelyTyped/DefinitelyTyped#16158]
Up for a challenge? 😁 Please add definitions for `timezone`.

The module is great but its API style is unusual, to say the least. It exposes a single function, typically imported as `tz()`, that takes a variety of arguments and returns `number` or `string`. My first attempt looked like this:

```typescript
declare function tz(value: [Date | number | string], tzOrFormat1?: string, tzOrFormat2?: string): [number | string];
declare namespace tz {}
export = tz;
```

* The first param, `value`, can be a `string`. Or it can be any value that can be converted to `number` using the syntax: `+(value)` -- primarily this would be the Date type.

* The `tzOrFormat1` param can be a `string` naming a timezone, or a date formatting `string`, or a time math `string`.

* The `tzOrFormat2` is the same as `tzOrFormat1` -- it’s used if you need to specify both a timezone and a format, and they can be provided in either order (timezone, format) or (format, timezone).

* If `tzOrFormat1`/`tzOrFormat2` does not specify a formatting string, then `number` is returned.

* If `tzOrFormat1`/`tzOrFormat2` specifies a formatting string, then `string` is returned.

* Alternately, you can use the command to load timezone sets (which are type `object`). To do this, instead of passing the usual arguments, you pass in the desired timezone sets as arguments, one per argument, with no limit to the number of arguments. My definition above doesn’t support this.

* With no arguments, it returns its own version number. My definition above doesn’t support this.

* It’s possible to pass an arbitrary number of arguments when doing time math: `tz("2000-01-01", "-1 day", "+1 saturday", "%A %d")` takes a date (in this case specified as a `string`), and accepts a number of `string` arguments that do date math and specify formatting. My definition above doesn’t support this.

**Comment by andy-ms** [comment]
You'll probably have to do this yourself. Some thoughts on how to implement this:

* `[Date | number | string]` is a tuple with one element -- you probably meant just `Date | number | string`.
* For handling timezone sets, it sounds like you can use an overload `tz(...timeZoneSets: object[]): object`. And hopefully there's a better type than `object`.
* The no-argument overload is easy: `declare function tz(): string`. This should go *before* the `..timeZoneSets` overload.

It sounds like the main overload would be `tz(value: Date | number | string, ...args: string[]): string | number`, given that you can pass arbitrarily many arguments. If the content of the strings determines the return type, there's not much we can do except expect you to cast.

Please [try the types out](https://github.com/DefinitelyTyped/DefinitelyTyped#test) yourself before submitting a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
