### ISSUE TITLE
@types/winston options timestamp property has incorrect signature

### ISSUE THREAD

**Issue by JimiC** [DefinitelyTyped/DefinitelyTyped#16173]
- [x] I tried using the `@types/winston` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bonnici @codeanimal @DABH

Options `timestamp` type signature has been changed from `timestamp?: (Function |  boolean)` to `timestamp?(): any | boolean` in PR #15609 which is incorrect and breaking custom transports that implement this property. 
The correct type should be `timestamp: boolean | (() => string | boolean)`.

According to https://github.com/winstonjs/winston/blob/2.3.1/lib/winston/common.js#L137 `timestamp` property can be anything but when strongly typed is should be restrained to a `boolean` or a function (returning `string` or `boolean`).

**Comment by DABH** [comment]
@JimiC Could you check the above-mentioned PR and see if it addresses this correctly?  Let me know

**Comment by JimiC** [comment]
@DABH LGTM. Can you please adjust the test as well?

**Comment by mhegazy** [comment]
addressed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16213
