### ISSUE TITLE
fs-extra typings may need updated

### ISSUE THREAD

**Issue by RyanZim** [DefinitelyTyped/DefinitelyTyped#16183]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @midknight41 @shiftkey

I am one of the maintainers of fs-extra. fs-extra v3 was just published, which adds promise support.

Changelog: https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#300--2017-04-27

I'm not a typescript user, but I think the typings here will need updated, so I thought I'd open this issue here. If not, I can close.

**Comment by shiftkey** [comment]
@RyanZim thanks for the heads up! That changelog and the links off to PRs seems like enough to get started. Would it be cool to pull you in for a review once the PR is opened? Don't worry about not knowing TypeScript, it's just a nice sanity check to ensure we're describing the API correctly...

**Comment by RyanZim** [comment]
Sure, I can try!

**Comment by shiftkey** [comment]
@RyanZim for reference, here's an example from a few days ago https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16082

**Comment by alan-agius4** [comment]
@RyanZim, would you accept a PR to include the typyings inside this library?

Thanks

**Comment by alan-agius4** [comment]
Would you consider having the typings in your repo? I can do a PR if interested

**Comment by RyanZim** [comment]
> Would you consider having the typings in your repo?

Nah, I've had trouble with that in the past. I don't like the idea of having something in the repo none of the core team knows how to maintain.

**Comment by RyanZim** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16218
