### ISSUE TITLE
Add extra type for react-router-redux

### ISSUE THREAD

**Issue by Lapanti** [DefinitelyTyped/DefinitelyTyped#16189]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andy-ms @huy-nguyen 

The current type definitions are missing perhaps in my view one of the most important types, for the action of `LOCATION_CHANGE`. I have used the following quick type for it in my projects but it would be nice if it was part of the library:
```typescript
import { LOCATION_CHANGE } from 'react-router-redux';
export type LocationChangeAction = {
    type: typeof LOCATION_CHANGE,
    payload: {
        pathname: string,
        search: string,
        hash: string,
        key: string,
        props?: {
            match: {
                path: string,
                url: string,
                params: any,
                isExact: boolean,
            },
            location: {
                pathname: string,
                search: string,
                hash: string,
            },
            history: {
                length: number,
                action: string,
                location: string,
            },
        },
    },
};
```

I can create a PR if it is wanted

**Comment by andy-ms** [comment]
Go for it. 🚀

**Comment by mxl** [comment]
This can be closed.

**Comment by aheitzmann** [comment]
Hi @Lapanti ,
I've been looking at the LocationChangeAction type introduced with the commit above, and wondering where the `payload.props` field comes from. react-redux-router v4 and v5 both simply set `payload` to be a `History.Location` when dispatching LOCATION_CHANGE actions, and I've never observed `payload.props` to be defined on any LOCATION_CHANGE action.

The package versions I'm using are:
```
react-router-redux@5.0.0-alpha.7:
  version "5.0.0-alpha.7"
  resolved "https://registry.yarnpkg.com/react-router-redux/-/react-router-redux-5.0.0-alpha.7.tgz#0b4acd052f41c42d0ab7fd89966d587cd35ca165"
  dependencies:
    history "^4.7.2"
    prop-types "^15.6.0"
    react-router "^4.2.0"
```
