### ISSUE TITLE
@types/restify request.query is not a function ERROR

### ISSUE THREAD

**Issue by SplitterAlex** [DefinitelyTyped/DefinitelyTyped#16199]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @blittle

When you call `req.query` in a Route you get following error:
`{"code":"InternalError","message":"req.query is not a function"}` 

`req.query` is an object not a function.

### Section:
```
/**
 * @see getQuery
 */
query: () => string;
```
### should be changed to:
```
/**
 * 
 */
query: any;
```

Further information about QueryParser in restify can be found here; [http://restify.com/#bundled-plugins](url)

## Sample Code 

``` javascript
import {
  acceptParser,
  bodyParser,
  createServer,
  pre,
  queryParser,
  Request,
  Response,
  Server } from "restify";

const server: Server = createServer({
  name: "queryFail",
  version: "0.0.0",
});

server.pre(pre.sanitizePath());
server.use(acceptParser(server.acceptable));
server.use(queryParser());
server.use(bodyParser());

server.get("/queryIsNotAFunction", (req: Request, res: Response, next) => {
  req.query(); // req.query is an object (see queryParser definition) not a function
  res.send(200);
});

/* tslint:disable:no-console */
server.listen(3000, () => {
  console.log(`${server.name} listening at ${server.url}`);
});
```
Type:
`http://localhost:3000/queryIsNotAFunction?field1=value1`
in your Browser and you get following response:
`{"code":"InternalError","message":"req.query is not a function"}`

**Comment by stevehipwell** [comment]
The *restify* type definitions are currently marked as for v2 while the current version is v4. I'm looking at creating an updated version for v5 when it is released but I could look at updating the current definitions to v4.

**Comment by stevehipwell** [comment]
@SplitterAlex I've made this change on my [current pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16274) to enable linting for *restify* types.

**Comment by SplitterAlex** [comment]
@stevehipwell I Haven't noticed the marking for v2. I gonna checkout your pull request. Great Work!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
