### ISSUE TITLE
Add highcharts/highstock type definitions for ScrollbarOptions to the xAxis and yAxis

### ISSUE THREAD

**Issue by ryanewtaylor** [DefinitelyTyped/DefinitelyTyped#16328]
I am using @types/highcharts v4.2.54 and I have enabled scrolling for axes in my highcharts charts per http://api.highcharts.com/highstock/yAxis.scrollbar.

However, there are no type definitions for ScrollbarOptions on the xAxis or yAxis in index.d.ts so the type checking fails. It would be helpful to have ScrollbarOptions defined.

I am not sure of the best method for adding these. I have tried three approaches. All worked but there may be other considerations.

**Approach 1**
```
// index.d.ts
// define a `ScrollbarOptions` interface and add `scrollbar?: ScrollbarOptions` property to `AxisOptions`

interface AxisOptions {
    // other properties
    scrollbar?: ScrollbarOptions;
}

interface ScrollbarOptions {
    barBackgroundColor?: string;
    barBorderColor?: string;
    barBorderRadius?: number;
    barBorderWidth?: number;
    buttonArrowColor?: string;
    buttonBackgroundColor?: string;
    buttonBorderColor?: string;
    buttonBorderRadius?: number;
    buttonBorderWidth?: number;
    enabled?: boolean;
    height?: number;
    liveRedraw?: boolean;
    minWidth?: number;
    rifleColor?: string;
    trackBackgroundColor?: string;
    trackBorderColor?: string;
    trackBorderRadius?: number;
    trackBorderWidth?: number;
}
```

**Approach 2**
```
// highstock.d.ts
// add an intersection type to define an optional scrollbar when using `Highstock.Options`
interface Options extends Highcharts.Options {
        navigator?: NavigatorOptions;
        rangeSelector?: RangeSelectorOptions;
        xAxis?: Highcharts.AxisOptions & { scrollbar?: ScrollbarOptions }
        yAxis?: Highcharts.AxisOptions & { scrollbar?: ScrollbarOptions }
    }
```

**Approach 3**
```
// highstock.d.ts
// Define a new `AxisOptions` to define an optional scrollbar when using `Highstock.Options`
interface AxisOptions extends Highcharts.AxisOptions {
    scrollbar?: ScrollbarOptions;
}

interface Options extends Highcharts.Options {
        navigator?: NavigatorOptions;
        rangeSelector?: RangeSelectorOptions;
        xAxis?: AxisOptions[] | AxisOptions;
        yAxis?: AxisOptions[] | AxisOptions;
    }
```
I'll gladly submit a pull request but could use some guidance on the best approach to adding this to the type definitions.

**Comment by andy-ms** [comment]
Approach 3 seems best (although it seems to remove `scrollbar` from `Options` -- intentional?), but I'm not familiar with the library. Definition authors are @damianog @baltie @AlbertOzimek @DavidKDeutsch

**Comment by ryanewtaylor** [comment]
No. Removing `scrollbar` from `options` is not intentional. In PR #16356 I left that in.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
