### ISSUE TITLE
Material-UI export component props

### ISSUE THREAD

**Issue by szpytfire** [DefinitelyTyped/DefinitelyTyped#16380]
- I tried using the `@types/material-ui 0.17.1` package and had problems.

In order to extend Components I would like to have access to their props. At the moment they aren't exported. Would it be possible to export component props?

Thanks

**Comment by andy-ms** [comment]
Pull requests accepted.

**Comment by minodisk** [comment]
@andy-ms It looks like it can be closed by [Export component props \(\#18856\) · DefinitelyTyped/DefinitelyTyped@2b74a91](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/2b74a91e5fd617ca4b144688807042378979d28a)

**Comment by andy-ms** [comment]
Thanks! Fixed by #18856
