### ISSUE TITLE
react-i18next typings should use generics for proper typing

### ISSUE THREAD

**Issue by icopp** [DefinitelyTyped/DefinitelyTyped#16395]
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @KostyaEsmukov

Right now, the typings require you to do

```
import { InjectedTranslateProps } from 'react-i18next'

interface MyComponentProps extends InjectedTranslateProps {
  ...
}
```

However, this results in unnecessary behavior with the `t` function, because it's marked as optional (to avoid causing errors in other components when importing a translated component). The `t` function always exists, it's just not actually an externally available prop.

Instead, the extend mentioned above shouldn't be needed, and the `translate` HOC function should work something like:

```
import { TranslateProps, translate } from 'react-i18next'

const MyComponentImpl: React.StatelessComponent<MyComponentProps & TranslateProps>;

const MyComponent: React.StatelessComponent<MyComponentProps> = translate<MyComponentProps>(MyComponentImpl);
```

This could use typings something like (very briefly giving an idea):

```
interface TranslateProps {
  t: (text: string) => string
}

function translate<P, S>(component: React.Component<P & TranslateProps, S>): React.Component<P, S>
function translate<P>(component: React.StatelessComponent<P & TranslateProps>): React.StatelessComponent<P>
```

The idea would be for it work very similarly to the typings for react-router or react-redux, which inject the appropriate props while still exporting the component with only its own props.

**Comment by KostyaEsmukov** [comment]
Great idea. Would you like to create a PR?
