### ISSUE TITLE
@types lagging (at least a few days) behind for `office-js`

### ISSUE THREAD

**Issue by Zlatkovsky** [DefinitelyTyped/DefinitelyTyped#16390]
We pushed an update to `office-js` d.ts file a few days ago:  https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/office-js/index.d.ts

However, the @types version is lagging behind -- the latest is from 2 weeks ago.

What is causing the delay?  is there a way to force a re-build?

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

**Comment by andy-ms** [comment]
It looks like the web server was doing "empty" (one line of logs, then nothing) runs for the last few days. But it's doing a good run now, so `@types/office-js` should be updated soon.
