### ISSUE TITLE
"Children are specified twice" error with spread props at React.StatelessComponent in @types/react@15.0.24

### ISSUE THREAD

**Issue by danvk** [DefinitelyTyped/DefinitelyTyped#16424]
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech, @pzavolinsky @digiguru @ericanderson

In this snippet, I get an error that `children` are specified twice. This shouldn't be an issue in practice, but I don't see any way to both use `React.StatelessComponent` and not allow JSX children.

```ts
interface Props {
  value: string;
}

const SelectWrapper: React.StatelessComponent<Props> = props => (
  <select value={props.value}>
    {props.children}
  </select>
);

const MySelect: React.StatelessComponent<Props> = props => (
  <SelectWrapper {...props}>
   //            ~~~~~~~~~~ error TS2710: 'children' are specified twice. The attribute named 'children' will be overwritten.
    <option value='hello'>Hello</option>
  </SelectWrapper>
);
```

Perhaps there should be a `StatelessChildlessComponent` interface?

I'm using TypeScript 2.3.2.

Possibly related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16415

**Comment by cchamberlain** [comment]
@danvk does this work?

```tsx
const MySelect: React.StatelessComponent<Props> = ({ children, ...props }) => (
  <SelectWrapper {...props}>
    <option value='hello'>Hello</option>
  </SelectWrapper>
);
```

**Comment by bbenezech** [comment]
@cchamberlain it does. (met the behaviour in my codebase when upgrading).
@danvk this is intended. You would actually be allowing 2 children props in SelectWrapper, I don't know which one React would choose and it does look like something TS should prevent us from doing.

**Comment by danvk** [comment]
@cchamberlain @bbenezech In my case a better solution would be to not allow children to be passed to `MySelect` (passing children would be incorrect usage). But there's no way to specify this with `StatelessComponent` since it's [hard-coded][1] that passing any type of child in is OK.

I'm not sure if it's possible in general with JSX and TypeScript to prevent passing children, but that would be the ideal solution to this issue.

[1]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8868f90acfd341cfa9096bf9e08d1c976ce8e981/types/react/index.d.ts#L219
