### ISSUE TITLE
Wrong parameters for SignaturePad.toDataURL()

### ISSUE THREAD

**Issue by sheam** [DefinitelyTyped/DefinitelyTyped#16428]
- [x] I tried using the `@types/signature_pad` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @szimek @AbubakerB

the toDataURL() function is defined as parameterless. But the actual function takes two parameters: output type, and quality. It  should be defined like this: ```toDataURL(imageType: string, quality: number): string;```

~S

**Comment by szimek** [comment]
One thing - both parameters are optional - see [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) - so I guess it should rather be `toDataURL(imageType?: string, encoderOptions?: number): string;`.

In the library itself, it's defined as:
```js
SignaturePad.prototype.toDataURL = function (type, ...options) {...};
```
and I should probably fix it there as well to `function (type, options) {...}`.

**Comment by sheam** [comment]
Cool thanks.
