### ISSUE TITLE
react-leaflet components need to define lifecycle methods

### ISSUE THREAD

**Issue by mikew** [DefinitelyTyped/DefinitelyTyped#16454]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @danzel (can't tag https://github.com/davschne for some reason)

We extend a couple of `react-leaflet` classes and are getting errors when calling `super.componentDidMount` and other component lifecycle methods.

**Comment by danzel** [comment]
Do you mean it doesn't compile (Typescript validation), or the resulting code has a runtime error?
If it doesn't compile, please post a reproducing test case.
If it has a runtime error, take it up on the react-leaflet github page. (Who will also want a reproducing test case)

**Comment by mikew** [comment]
It's an issue with the typescript validation, hence raising the issue here. The code runs fine.

```typescript
import { MapComponent } from "react-leaflet";
import { Control } from "leaflet";

class MyComponent extends MapComponent<void, Control> {
  componentDidMount () {
    super.componentDidMount();
  }
}
```

Yields `Property 'componentDidMount' does not exist on type 'MapComponent<void, Control>'. `

**Comment by danzel** [comment]
@davshne ^^

**Comment by danzel** [comment]
Maybe related to #16246 ?

**Comment by mikew** [comment]
pretty sure I tried that issue because using any component from react-leaflet was giving other TypeScript errors.

But even with `index.d.ts` from that PR, the issue remains.

**Comment by mikew** [comment]
Not sure if it's an error on my machine, but even `react-leaflet-tests.tsx` is littered with errors, no `react-leaflet` components satisfy the type checker:

<img width="598" alt="screen shot 2017-05-12 at 4 40 34 pm" src="https://cloud.githubusercontent.com/assets/4729/26014133/bee74054-3731-11e7-97e5-aca611d9f9b1.png">

All the errors boil down to `Type '{ ... }' is not assignable to type 'Readonly<P>'`

TypeScript 2.3.2.

**Comment by danzel** [comment]
I think that PR needs merging to fix those errors

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
