### ISSUE TITLE
Problems with definitions of jquery-param and es6 import

### ISSUE THREAD

**Issue by alfaslash** [DefinitelyTyped/DefinitelyTyped#16456]
- [ ] I tried using the `@types/jquery-params` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @patsissons 

I set compile options `"module": "es2015",` in `tsconfig.json` and get the error:

![require import](https://s8.hostingkartinok.com/uploads/images/2017/05/927bcf8cc7e591837a7b6565ceb7cf37.jpg)

![es6 import](https://s8.hostingkartinok.com/uploads/images/2017/05/ca06f5fdd5a1e76ef030d58104ccd33f.jpg)

**Comment by patsissons** [comment]
This seems related to https://github.com/Microsoft/TypeScript/issues/4170
