### ISSUE TITLE
SockJS-Client does not export the SockJSClass

### ISSUE THREAD

**Issue by raybooysen** [DefinitelyTyped/DefinitelyTyped#16455]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @vladev @arusakov

When using the current type definitions:

```
declare var SockJS: {
  new(url: string, _reserved?: any, options?: Options): SockJSClass;
  (url: string, _reserved?: any, options?: Options): SockJSClass;
```
The constructor returns an instance of SockJSClass, but you cannot do something like this (as it is not exported):

```
import * as SockJS from 'sockjs-client';

let socket: SockJSClass = new SockJS('http://foo.com');
```

**Comment by BendingBender** [comment]
Duplicates #11042
