### ISSUE TITLE
[vexflow] Fix 'stem_direction' for TabNote

### ISSUE THREAD

**Issue by bohoffi** [DefinitelyTyped/DefinitelyTyped#16472]
- [X] I tried using the `@types/xxxx` package and had problems.
  - Authors: @rquiring @sebastianhaas 

Found out that TabNote uses `boolean` as type for `stem_direction`.
Will fix this in a few moments.

Created PR #16473

**Comment by sebastianhaas** [comment]
👍
hopefully this is merged in soon :)

**Comment by bohoffi** [comment]
@sebastianhaas could you check the Box that The CI Has been passed (in the PR)?

**Comment by sebastianhaas** [comment]
Unfortunately, I can't :( (or don't know how to do so, but I can't tick the checkbox or edit the comment)

**Comment by bohoffi** [comment]
Hmmm, maybe it's not necessary. Further down in the PR there is the message that the CI has passed...
