### ISSUE TITLE
FileSaver saveAs is not a function

### ISSUE THREAD

**Issue by jgcoded** [DefinitelyTyped/DefinitelyTyped#16485]
- [x] I tried using the `@types/file-saver` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cyrilschumacher, @DaIgeb

Hello all, I tried using the `@types/file-saver` package in an Angular 4 app and had problems. I'm using typescript 2.3.2. I import the package like so:

```typescript
import * as FileSaver from 'file-saver';
```

I'm using the [Angular4 quickstart](https://github.com/angular/quickstart) as the base for my project. The quickstart uses SystemJS to load dependencies, and I have the ```file-saver``` string in the above import mapped to this:
```typescript
'file-saver': 'npm:file-saver/FileSaver.min.js',
```
It looks in the node_modules/ folder to find the js file. I have some code that generates a zip file, and when I then try to save the zip file with FileSaver like so:
```typescript
. . .
      .then(() => zip.generateAsync({ type: 'blob'}))
      .then(content => {
        return this.getSolutionName()
          .then(name => FileSaver.saveAs(content, `${name}.zip`))
      });
```
My promise is rejected, stating: ```TypeError: FileSaver.saveAs is not a function```. I then tried a bunch of acrobatics to get it working and I then found that replacing the above FileSaver line with this:
```typescript
. . .
.then(name => FileSaver(content, `${name}.zip`))
. . .
```

Makes the code work. Meaning, I get the prompt from my browser to download the zip file. However, I get this error from the typescript compiler:
```
severity: 'Error'
message: 'Cannot invoke an expression whose type lacks a call signature. Type '{ saveAs: FileSaver; }' has no compatible call signatures.'
```

So I then went in and changed the ```file-saver/index.d.ts``` and replaced this code
```typescript

declare var saveAs: FileSaver;

declare module "file-saver" {
    var fileSaver: { saveAs: typeof saveAs };
    export = fileSaver
}
```

with this:

```typescript

declare var saveAs: FileSaver;

declare module "file-saver" {
    export = fileSaver
}
```

and then the code worked as expected with no TypeScript compiler errors:
```typescript
import * as saveAs from 'file-saver';
. . .
      .then(() => zip.generateAsync({ type: 'blob'}))
      .then(content => {
        return this.getSolutionName()
          .then(name => saveAs(content, `${name}.zip`))
      });
```

My questions are

* Is this something that's happening because of Angular4 and SystemJS?
* Is it just my own error?
* Or is this an actual issue with the typings for the file-saver package? 

I tried to change around my code as much as I could to import the FileSaver.min.js file without having to edit the file-saver/index.d.ts file but I had no luck.

Thank you for taking the time to look at this.

**Comment by DaIgeb** [comment]
If you look at the Javascript code from the file-saver
```
if (typeof module !== "undefined" && module.exports) {
  module.exports.saveAs = saveAs;
} else if ((typeof define !== "undefined" && define !== null) && (define.amd !== null)) {
  define("FileSaver.js", function() {
    return saveAs;
  });
}
```

I'm not sure what Angular4 or SystemJS do but if you run it with node your original code would work (at least it does for me)

**Comment by jgcoded** [comment]
I was able to avoid this issue by changing to webpack using the [guide in the angular4 docs](https://angular.io/docs/ts/latest/guide/webpack.html). I no longer use SystemJs.

I reverted the typings file back to its original state and I now import the saveAs function like so:
```typescript
import { saveAs } from 'file-saver';
````

and everything works.

**Comment by roni-frantchi** [comment]
To get it to work without dropping `System.js`, here's a solution that worked for me:
https://github.com/eligrey/FileSaver.js/issues/308#issuecomment-323719394

**Comment by Anderman** [comment]
In Angular 5 I used FileSaver.Default() and Not FileSaver.SaveAs()
```
import * as FileSaver from "file-saver";
.subscribe(data => {
            const blob = data.data;
            const filename = "filename.txt";
            FileSaver.default(blob, filename);
```

**Comment by envil** [comment]
I found the issue, down grade to version 1.3.3 or you will have to change your code: https://github.com/eligrey/FileSaver.js/issues/414

**Comment by swarupbam** [comment]
My file is getting downloaded but it is corrupted.  what may be the issue ?
