### ISSUE TITLE
react-router definitions [Cannot find name 'object' ]

### ISSUE THREAD

**Issue by Odol** [DefinitelyTyped/DefinitelyTyped#16496]
When compiled the react-router definitions throws an error 
Cannot find name 'object'

Changing object for Object fixes this

  "typescript": "^2.3.2"
 "@types/react-router": "^4.0.9",
 "@types/react-router-dom": "^4.0.4",

Regards

**Comment by andy-ms** [comment]
Are you sure you're using TypeScript 2.3.2? `object` was introduced in 2.2.

**Comment by Odol** [comment]
Andy
You're right, it was my mistake, thanks for your time!
Regards
