### ISSUE TITLE
@types/webrtc conflicts with typescript/lib/lib.es6.d.ts 

### ISSUE THREAD

**Issue by vardius** [DefinitelyTyped/DefinitelyTyped#16509]
Adding `dom` inside `compilerOptions` does provides *WebRTC* types, but does not provides `RTCDataChannel` types throwing for example:

`error TS2304: Cannot find name 'RTCDataChannel'.`

and many more related to data channel types are missing.

Installing `@types/webrtc` does provide missing types, but the ones already provided withing `dom` lib produce duplicates, for example:

`node_modules/typescript/lib/lib.dom.d.ts(15038,6): error TS2300: Duplicate identifier 'RTCSdpType'.`

`package.json`
```
"devDependencies": {
    "@types/webrtc": "0.0.21"
}
```
`tsconfig.json`
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "lib": ["es2017", "dom", "scripthost"]
}
```

If we remove `dom` then we get: `Cannot find name 'DOMException'.` and many others.

**Comment by mafrost** [comment]
I'm also seing this issue with both `@types/webaudioapi` and `@types/webrtc`

**Comment by fpizzichillo** [comment]
me too

**Comment by RyanPridgeon** [comment]
Same issue here.

**Comment by RyanPridgeon** [comment]
@vardius @mafrost @fpizzichillo did you find any solutions or workarounds for this problem?

**Comment by vardius** [comment]
Yes It works for me with  `"skipLibCheck": true`

Here is full tsconfig.json that works for me

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "rootDir": "src",
    "outDir": ".code",
    "newLine": "LF",
    "lib": [
      "es2015",
      "es2016",
      "es2017",
      "dom",
      "scripthost"
    ],
    "moduleResolution": "node",
    "importHelpers": true,
    "declaration": true,
    "pretty": true,
    "sourceMap": true,
    "inlineSources": true,
    "noUnusedLocals": true,
    "skipLibCheck": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts",
    "dist",
    "es",
    "lib"
  ]
}
```

**Comment by RyanPridgeon** [comment]
Nice! Works for me

**Comment by zulaica** [comment]
This worked for me as well. Thanks. @vardius!

**Comment by Pato91** [comment]
works for me too. Thanks @vardius

**Comment by NickClark** [comment]
Works, but then my custom definitions are no longer checked. Wish there was a way to only disable for that one file.

**Comment by JTejedor** [comment]
Awesome @vardius! Works wonderful! I think just like @NickClark! I would like disable only those libraries ing with problems

**Comment by tommedema** [comment]
What's the proper way to solve this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
