### ISSUE TITLE
@types/xrm missing context.getVersion

### ISSUE THREAD

**Issue by mariusagur** [DefinitelyTyped/DefinitelyTyped#16528]
- [x] I tried using the `@types/xrm` package and could not find a function I expected
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I verified that the function should exist from the [MSDN documentation](https://msdn.microsoft.com/en-us/library/gg334511.aspx#BKMK_getversion)
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified)
  - Authors: @daryllabar @andy-ms 

Xrm.Page.context should include a function named getVersion() which returns a string value of the Xrm build version (e.g: 8.2.0.749)

**Comment by daryllabar** [comment]
This can be closed @andy-ms
