### ISSUE TITLE
@types/node Error interface only has stack. missing "name" and "message"

### ISSUE THREAD

**Issue by tommck** [DefinitelyTyped/DefinitelyTyped#16526]
- [X] I tried using the `@types/node` package and had problems.

I couldn't find any specific authors

this is the current interface.

```ts
interface Error {
    stack?: string;
}
```

it should be: 
```ts
interface Error {
    message?: string;
    name?: string;
    stack?: string;
}
```

**Comment by andy-ms** [comment]
This is a case of [declaration merging](http://www.typescriptlang.org/docs/handbook/declaration-merging.html). The rest of the interface is in `lib.es5.d.ts`. Just goto-definition on `Error` and it should show you multiple definitions.

**Comment by tommck** [comment]
I don't have a "lib" in my tsconfig.. guess that's why I'm only seeing the node one

**Comment by andy-ms** [comment]
If you don't set `"lib"` there will still be a default choice provided. Try actually using `.name` on an `Error` and use goto-definition on that.

**Comment by tommck** [comment]
if I use name on Error, I get an error.. that's why I'm reporting the problem :)

**Comment by andy-ms** [comment]
Can you provide a reproducible example?

**Comment by tommck** [comment]
ooh.. it's when I inherit from Error and try to use super.name that there's a problem

```ts
export class TestError extends Error {
    constructor() {
        super();

        super.name = 'TestError'; // ERROR
    }
}
```

**Comment by tommck** [comment]
[ts] Only public and protected methods of the base class are accessible via the 'super' keyword.
(property) Error.name: string

**Comment by tommck** [comment]
I think the problem is that extending "Error" is trying to extend the _const_?

```ts
interface Error {
    name: string;
    message: string;
    stack?: string;
}

interface ErrorConstructor {
    new (message?: string): Error;
    (message?: string): Error;
    readonly prototype: Error;
}

declare const Error: ErrorConstructor;
```

and the _const_ Error doesn't have a 'name' property... actually doesn't even have any relationship to the _interface_ Error at all, which seems weird to me

**Comment by tommck** [comment]
But, I wanted to just extend what was there.. Guess that's not possible?

**Comment by andy-ms** [comment]
Why not assign to `this.name` instead?

**Comment by tommck** [comment]
I guess I can, but I just wanted to make sure I was setting the base.. since it's part of the "super", it seemed to make sense to do it that way.

Definitely don't want to implement the interface because I want the stack trace.. So I guess I'll use "this." since that works

**Comment by tommck** [comment]
But shouldn't "super.name" work, conceptually?

**Comment by andy-ms** [comment]
It will work if you target ES6. But correctly transpiling that to ES5 isn't currently supported. But if you're not overriding the setter for `name`, `this.name` is equivalent anyway.

**Comment by tommck** [comment]
well, we're targeting ES5 so that browsers will support it, so I guess I'll be using this.name :)

**Comment by andy-ms** [comment]
OK. Be sure to test that extending Error is working correctly in older browsers.

**Comment by tommck** [comment]
well, we're in pretty new browsers.. IE11+, EDGE, and the latest versions of the "evergreen" browsers.  
Just don't want to trust their ES6 implementations yet

**Comment by hinell** [comment]
@tommck Have you set up the ``'lib`` compiler option to just ``[]``?
Provide your ``tsconfig.json`` file pls.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
