### ISSUE TITLE
[redux-form] Don't Expose FormProps to Consumer

### ISSUE THREAD

**Issue by tugberkugurlu** [DefinitelyTyped/DefinitelyTyped#16548]
> Moving this from https://github.com/erikras/redux-form/issues/2853:

### Are you submitting a **bug report** or a **feature request**?

Consider the component below which is on TypeScript:

```tsx
import * as React from 'react';
import { reduxForm, Field, FormErrors, FormProps } from 'redux-form';

interface FormData {
    name?: string;
    lastname?: string;
}

const validate = (values: Readonly<FormData>): FormErrors<FormData> => { 
    const errors: FormErrors<FormData> = {};

    if(values.name === undefined) {
        errors.name = 'name needed';
    }

    if(values.lastname === undefined) {
        errors.lastname = 'lastname needed';
    }

    return errors;
};

interface SelectionWithFormProps {
    readonly value: string;
    readonly onChange: (val: React.ChangeEvent<HTMLSelectElement> | React.FormEvent<HTMLSelectElement> | string) => void;
}

class SelectionWithForm extends React.Component<FormProps<FormData, {}, {}> & SelectionWithFormProps, {}> {
    render(): JSX.Element {
        return <div>
            <div>
                <Field placeholder="First name" name="name" component="input" />
                <Field placeholder="Last name" name="lastname" component="input" />
                <div>
                    <button className="button button--primary" type="button" onClick={this.props.handleSubmit}>
                        Provide full name
                    </button>
                </div>
            </div>
        </div>;
    }
}

export default reduxForm<Readonly<FormData>, SelectionWithFormProps, {}>({
    form: 'SelectionWithForm',
    validate: validate,
    onSubmit: (values, dispatch, props) => {
        console.log('submit is being handled...');
        props.onChange(values.name + ' ' + values.lastname);
    }
})(SelectionWithForm);

```

### What is the current behavior?

When you try to consume this, you will see that redux form properties are also available to consumer:

![image](https://cloud.githubusercontent.com/assets/328122/25434088/db3ba0e4-2a82-11e7-8c1d-4f24b42b21af.png)

which I imagine does not make sense and more importantly then IntelliSense, this effects the compilation, too.

### What is the expected behavior?

I would expected it to just expose `SelectionWithFormProps` as the shape for valid props to pass through `SelectionWithForm`.

### Sandbox Link

You can see the sample here: https://github.com/tugberkugurlu/redux-form-typescript-repro/tree/2f1ef56d3ac6c7d2df4dcba950f871fd72d8a925 follow the readme on how to get it up and running.

You should be able to open it up on VS Code to observe the IntelliSense behavior. You can also trigger the compilation through `npm run build`

### What's your environment?

 - `redux-form`: 6.5.0
 - `@types/redux-form`: 6.3.2
 - `typescript`: 2.2.1
 - `Node.js`: 4.4.7

### Authors 

@carsonf, @aikoven, @LKay

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
