### ISSUE TITLE
Not able to add a select additionalSignUpFields

### ISSUE THREAD

**Issue by rbarcelos** [DefinitelyTyped/DefinitelyTyped#16556]
@andy-ms , I am hitting the following error when using auth0 types:
C:/Users/rbarcelo/Documents/std/distribuidora/src/app/shared/services/auth.service.ts (16,73): Argument of type '{ additionalSignUpFields: { type: string; name: string; placeholder: string; options: { value: st...' is not assignable to parameter of type 'Auth0LockConstructorOptions'.
Types of property 'additionalSignUpFields' are incompatible.
Type '{ type: string; name: string; placeholder: string; options: { value: string; label: string; }[]; ...' is not assignable to type 'Auth0LockAdditionalSignUpField[]'.
Type '{ type: string; name: string; placeholder: string; options: { value: string; label: string; }[]; ...' is not assignable to type 'Auth0LockAdditionalSignUpField'.
Types of property 'type' are incompatible.
Type 'string' is not assignable to type '"select" | "text"'.

This is how I am configuring the select field:

this.lock = new Auth0Lock(AUTH_CONFIG.clientID, AUTH_CONFIG.domain, LOCK_CONFIG);

where

export const LOCK_CONFIG =
{
additionalSignUpFields: [{
type: "select",
name: "location",
placeholder: "choose your location",
options: [
{ value: "us", label: "United States" },
{ value: "fr", label: "France" },
{ value: "ar", label: "Argentina" }
],
// The following properties are optional
icon: "https://example.com/assests/location_icon.png",
prefill: "us"
}]
}

**I changed locally 
type?: "select" | "text"; 
to 
type?: string;
ant it worked ..**

Thanks

**Comment by andy-ms** [comment]
You may need to provide a contextual type to `LOCK_CONFIG`. Try `export const LOCK_CONFIG: Auth0LockConstructorOptions = ...`.

**Comment by rbarcelos** [comment]
it worked.. thanks
