### ISSUE TITLE
[classnames] Can not access 'ClassArray' interface anymore

### ISSUE THREAD

**Issue by ulfryk** [DefinitelyTyped/DefinitelyTyped#16554]
- [/] I tried using the `@types/classnames` package and had problems.
- [/] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

@adidahiya @JKillian @seansfkelley @mradamczyk

New version of classnames types doesn't allow to use `ClassArray` interface anymore. It was quite usefull…

**Comment by adidahiya** [comment]
I don't think there's much we can do here without breaking the existing `import * as classNames` syntax... perhaps we could add another definition file to the package that has the types you're looking for?

```ts
// index.d.ts

import { ClassArray, ClassDictionary, ClassValue } from "./common";

type ClassNamesFn = (...classes: ClassValue[]) => string;

declare const classNames: ClassNamesFn;

export = classNames;
export as namespace classNames;
```

```ts
// common.d.ts

export type ClassValue = string | number | ClassDictionary | ClassArray | undefined | null | false;

export interface ClassDictionary {
	[id: string]: boolean | undefined | null;
}

export interface ClassArray extends Array<ClassValue> { } // tslint:disable-line no-empty-interface
```

then you'd be able to do

```ts
import { ClassArray } from "classnames/common";
// or maybe?
import { ClassArray } from "@types/classnames/common";
```

**Comment by ulfryk** [comment]
Maybe interfaces can be attached to `classNames` namespace ?

**Comment by varHarrie** [comment]
Is there any progress?

**Comment by bam** [comment]
Maybe is there an opportunity to write additional declaration file?
E.g. ```custom_typings/classnames_override.d.ts``` and declare there all needed types.
But I have no idea how to use it, how can it be included in the project then?
``typeRoots``, ``types`` and ``files`` configs in ``tsconfig.json`` don't work for this...
Does somebody know a workaround?

**Comment by roughearth** [comment]
This is a blocker to integrating `classNames` in to a component library. I am using it internally to my (React) components and want to expose a `prop` that accepts anything that `classNames` does. At the moment, I would have to duplicate the definitions to make that work.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
