### ISSUE TITLE
Can someone help me with this Pull-Request

### ISSUE THREAD

**Issue by dolanmiu** [DefinitelyTyped/DefinitelyTyped#16563]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16562

I need help with this. in the `alexa-voice-service-tests.ts has:

```ts
const avsInstance = new AVS(options);
```

It is red and has errors, and I am not sure how to resolve.

Its something about exporting the class at the module level

**Comment by aluanhaddad** [comment]
Yeah, there is a problem with the typings.
Based on the npm package, the declaration should be in UMD style. That is it should be written as

```ts
export as namespace AVS;
export  = AVS;

declare namespace AVS {
  // wraps everything except the primary export
}
```
Everything except for the `export class AVS` declaration should be moved into the `declare namespace` block above.

ultimately, it should look like

```ts
export as namespace AVS;
export  = AVS;

declare class AVS {
    player: AVS.Player;

    .....
}
declare namespace AVS {
    export enum EventTypes {
        RECORD_STOP, RECORD_START, ERROR, TOKEN_INVALID, LOG, LOGIN, LOGOUT, TOKEN_SET, REFRESH_TOKEN_SET
    }

    ....
}
```
