### ISSUE TITLE
@types/sinon@2.2.2 Map and Set missing

### ISSUE THREAD

**Issue by jraller** [DefinitelyTyped/DefinitelyTyped#16587]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nicojs

The addition by @nicojs causes the following errors that were not present in 2.2.1:

```
(389,30): error TS2304: Cannot find name 'Map'.
(393,28): error TS2304: Cannot find name 'Map'.
(400,30): error TS2304: Cannot find name 'Set'.
(404,28): error TS2304: Cannot find name 'Set'.
```

reverting to version 2.2.1 removes these errors.

**Comment by jraller** [comment]
#8264 might hold the answer. For those not using ES6 something like the following would need to be added:

```
interface Map<v, k> {}
interface Set<T> {}
```

**Comment by aluanhaddad** [comment]
Why not use the `"lib"` option in `tsconfig.json`?
```json
{
  "compilerOptions": {
    "lib": [
      "dom",
      "es2015"
    ],
```

**Comment by nicojs** [comment]
@aluanhaddad when you're not building a browser app for example.

:

**Comment by aluanhaddad** [comment]
I only added `"dom"` as an example. If you are targeting in NodeJS you can still use `"lib": ["es2015"` to get `Set` and `Map` and whatnot.

**Comment by nicojs** [comment]
Ah ok, yeah than that would be better.

Does that mean this version of sinon does not support older versions of node where there is no `Map` and `Set`? If no, than we should still add the interfaces.

**Comment by valotas** [comment]
`lib: ["dom"]` is not enough if you are targeting `es5` if I am not mistaken. Since the types are shimed in Sinon, there should be an interface for them in Sinon IMHO. Unless there is something that I did not get right.

**Comment by jamesmoriarty** [comment]
@jraller your suggestion worked for me. I've raised a PR but I get the feeling there might be a deeper issue.

**Comment by jamesmoriarty** [comment]
```
npm install --save-dev @types/es6-collections
```
Seems to have fixed it.

**Comment by nicojs** [comment]
> ```
> npm install --save-dev @types/es6-collections` 
> ```
> 
> Seems to have fixed it.

Although this is true, i would prefer to use the bundled es6.collections lib. In tsconfig:

```json
"lib": [
          "es2015.collection"
]
```

NB: You might also need other libs, like `"es5"` and `"dom"`

**Comment by jamesmoriarty** [comment]
Thanks @nicojs. I've got it to work with:

```
"lib": ["es5", "es2015.collection", "es2015.promise"]
```
