### ISSUE TITLE
@types/express - app.use() not working as expected

### ISSUE THREAD

**Issue by lengk** [DefinitelyTyped/DefinitelyTyped#16639]
Using the express @types/express
  - Authors: @borisyankov

Thanks for you work Boris! I've been trying to read through the code to understand why I am getting this error:

For the first parameter in express.use() function, I am getting this error: 

**Argument of type 'string' is not assignable to parameter of type 'RequestHandlerParams'.**

**App**
```typescript 
import * as express from 'express'

class App {
    express: express.Application

    constructor(){
         this.express = express()
         this.routes()
    }

    private routes(){
        let routers: Array<Route> = [new IndexRoute]

        routers.forEach(route => {
            // Problem is showing here on the first argument being called with route.url
            this.express.use(route.url, (req: Request, res: Response, next: Function) => {

            })
        })
    }
}
```

**Route v1**
```typescript
import * as express from 'express'

export class Route {
    routehandler: (req: Request, res: Response, next: Function) => {}
    url: string
}
```

I have also tried this:

**Route v2**
```typescript
import * as express from 'express'

export class Route {
    routehandler: express.Router
    url: string
    
    constructor(){
        this.routehandler = express.Router()
    }
}
```

**IndexRoute**
```typescript
import * as express from 'express'
import { Route } from "./Route";

export class IndexRoute extends Route {
    constructor() {
        super()
        this.url = '/'
    }
}

```

In javascript you can create new Routers and pass them to the express app to be used on a certain route like so:

```javascript
const express = require('express')
let app = express()

let router = express.Router()
app.use('/newroute', router)
```

Is this intentional, am I doing something wrong?

**Comment by aluanhaddad** [comment]
Looks like you have the wrong `Request` and `Response` types. The types used by the handlers passed to `use` are declared by the express declaration but you are not qualifying them.

`Request` --> `express.Request`

Also, avoid using the type `Function`.

**Comment by lengk** [comment]
Seems to have resolved my issue. Thanks @aluanhaddad!

**Comment by yasharma** [comment]
Hi i'm facing the same issue, for me the fix is to set explicitly setting the type as `RequestHandler`
```ts
import { Request as ExpressRequest } from 'express';

export interface Request extends ExpressRequest {
  id: string;
}

``` 
requestId Handler.ts
```ts
import { Response, NextFunction } from 'express';
import { nanoid } from 'nanoid';
import { Request } from '../../interfaces/Request';

export const requestIdHandler = (req: Request, res: Response, next: NextFunction) => {
  req.id = nanoid() as string;
  res.setHeader('X-Request-Id', req.id);
  next();
};

```
in App.ts
```ts
 app.use(requestIdHandler as express.RequestHandler);
```

**Comment by stomvi** [comment]
@yasharma I found my issue is similar to yours.  I extended the Request interface in the `express` module declaration to make the session data accessible. But indeed it's not necessary since I declared the session data somewhere else in `express-session` module. Bumped into this error after the latter one was done.
