### ISSUE TITLE
@types/knex missing seeds config definition

### ISSUE THREAD

**Issue by pouyaemami** [DefinitelyTyped/DefinitelyTyped#16683]
- [x] I tried using the `@types/knex` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @edvinv

It looks like there is no definition for seeds whereas there is one for migrations. I therefore cannot set the seeds directory like I can for migrations where I run the CLI command `seed:make`

**Comment by slively** [comment]
PR submitted to fix this

**Comment by baronfel** [comment]
Sorry I slacked and it took so long to get that merged. Can this issue be closed now?

**Comment by slively** [comment]
absolutely, thank you for merging!

**Comment by Taggotty** [comment]
@baronfel Issue seems closed
