### ISSUE TITLE
@types/auth0 getUser should resolve to a single user

### ISSUE THREAD

**Issue by amiram** [DefinitelyTyped/DefinitelyTyped#16688]
`@types/auth0`
getUser should return `Promise<User>` and not `Promise<User[]>`
https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id
@wbhob @westy92

**Comment by westy92** [comment]
I'd be happy to look at a PR.

**Comment by amiram** [comment]
BTW, why is there an interface `UpdateUserParameters` if it is exactly as `ObjectWithId`?

**Comment by amiram** [comment]
@westy92 I think there is also a problem with updateUser. It should not get a whole user as param. This should be something similar to UserData https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id
Do you want me to add it to this PR or open another?

**Comment by westy92** [comment]
Go ahead and add it to this one.

**Comment by amiram** [comment]
@westy92 updateUser fixed and some other methods

**Comment by amiram** [comment]
@westy92 Did you manage to look on this?

**Comment by amiram** [comment]
@westy92 pr was closed. Opened again https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17369

**Comment by acomagu** [comment]
Hey this can be closed now, right?
