### ISSUE TITLE
Winston: timestamp of GenericTextTransportOptions should be optional

### ISSUE THREAD

**Issue by JimiC** [DefinitelyTyped/DefinitelyTyped#16703]
- [x] I tried using the `@types/winston` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DABH

See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/winston/index.d.ts#L403

**Comment by DABH** [comment]
Thanks, please see #16846 where this is fixed!
