### ISSUE TITLE
react-icons : Add className to react-icons-base

### ISSUE THREAD

**Issue by DanielRamosAcosta** [DefinitelyTyped/DefinitelyTyped#16731]
- [x] I tried using the `@types/react-icons` package and had problems.
- [x] I tried using the latest stable version of tsc (2.3.3). https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @apare

[Here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-icon-base/index.d.ts), the interface is missing the `className` prop. May I do a PR?

**Comment by eirikurn** [comment]
It passes all extra props to svg, so IconBaseProps should probably extend `React.SVGProps<SVGSVGElement>`.
