### ISSUE TITLE
[Hapi] value parameter of response validation functions is not Reponse

### ISSUE THREAD

**Issue by Kampfgnom** [DefinitelyTyped/DefinitelyTyped#16750]
Hi there,

I am quite sure, that the first parameter for the `ValidationFunctionForRouteResponse` should not be `Response`.

Here is a small test case to verify Hapi is just putting the response payload into the function:

```typescript
import * as Chai from 'chai';
import * as ChaiPromised from 'chai-as-promised';
import * as Hapi from 'hapi';
import * as Lab from 'lab';

Chai.use(ChaiPromised);
const expect = Chai.expect;
const lab = exports.lab = Lab.script(); // tslint:disable-line:mocha-no-side-effect-code
const describe = lab.describe;
const it = lab.it;

describe('Test validation function input', () => {
    it('expects the validated object to exactly match the reply', () => {
        const server = new Hapi.Server();
        server.connection({});
        let validatedObject: {};
        const expectedObject = { test: 123 };

        server.route({
            path: '/', method: 'GET', config: {
                response: {
                    schema: (value: Hapi.Response, _: Hapi.JoiValidationObject, next: Hapi.ContinuationFunction) => {
                        validatedObject = value;
                        next();
                    }
                },
                handler: (_, reply) => {
                    reply(expectedObject);
                }
            }
        });
        return server.inject({ url: '/', method: 'GET' }).then((res) => {
            expect(validatedObject).to.equal(expectedObject);
            expect(JSON.parse(res.payload)).to.deep.equal(expectedObject);
        });
    });
});
```

Am I missing something here? I also noted your TODO comments in that domain and that the Hapi documentation is quite misleading :)

---

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jasonswearingen @AJamesPhillips

**Comment by AJamesPhillips** [comment]
Hi @Kampfgnom !  Very happy to accept a PR if you want to prepare one I'll review it asap and we can get it merged into master.  Thanks for finding this 👍  :)

**Comment by AJamesPhillips** [comment]
And re the docs.  I was doing the typings in a really rush so now I'm coming back to it and have the aid of your very useful test case "value - the object containing the response object." makes a lot more sense!  :)  Though I think something like "`value` - the value of the response object passed to `reply(value)`." might be better.  What do you think?  Though also I'm not sure this is completely correct as perhaps this value can be modified before it reaches the schema validation function?  The  "the object containing" bit still confuses me.  Would need to look at the source to check it's not doing anything fancy if you passed back `reply()` or `reply(true)` etc... and just passes the value of `undefined` or `true` etc...

**Comment by jasonswearingen** [comment]
fyi I haven't touched the definitions in a while, but it might be good in this case (or others) to refer back to the old hapi typings, as though it was missing a ton of sub-module definitions it has been pretty robust for the core hapi descriptions.

**Comment by AJamesPhillips** [comment]
Good shout @jasonswearingen 

* goes off to check *

Alas, not much good this time though `any` is "correct": https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi/v15/index.d.ts#L569

**Comment by Kampfgnom** [comment]
Concerning the documentation flaw: I added my suggestion to the typing's JSDoc comments.

I do not know enough about the internals of hapi (read: I know next to nothing about it) to make further assumptions about what that value could possibly be :)
