### ISSUE TITLE
Jest v.20

### ISSUE THREAD

**Issue by artemyarulin** [DefinitelyTyped/DefinitelyTyped#16803]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

Jest v.20 has new methods and props according to https://github.com/facebook/jest/blob/master/CHANGELOG.md#jest-2000

Specifically:
  - New promise support for all expect matchers through .resolves and .rejects.
  - New expect.hasAssertions() function similar to expect.assertions().
  - New this.equals function exposed to custom matchers. 
 
I can try to create a PR with those changes if nobody else working on it already?

cc previous author: @hschaeidt

**Comment by albertogasparin** [comment]
Also `jest.spyOn()` has been added

**Comment by artemyarulin** [comment]
`spyOn` was added at v.19 https://github.com/facebook/jest/blob/master/CHANGELOG.md#jest-1900

And I guess even current version has it https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts#L81
Or are you talking about smth else?

**Comment by albertogasparin** [comment]
Right, but I'm currently getting `Property 'spyOn' does not exist on type 'typeof jest'.` (Jest v20, Typescript 2.3.2) so I thought to report it here. Are you not getting this error?

**Comment by artemyarulin** [comment]
Hm, just tried and everything worked fine with such test like in Jest doc:
``` js
test('aaa', () => {
    const video = {
        play() {
            return true;
        }
    }
    const spy = jest.spyOn(video, 'play');
    const isPlaying = video.play();
    expect(spy).toHaveBeenCalled();
    expect(isPlaying).toBe(true);
    spy.mockReset()
    spy.mockRestore()
})
```

Versions:
"jest": "20.0.1",
"ts-jest": "20.0.4",
"typescript": "2.3.3"

Maybe you are using it differently?

**Comment by albertogasparin** [comment]
My bad! Just found out that the typings I got were still for jest 18 😖. Probably an npm cache issue or something. With the up to date typings the error is gone. Sorry!

**Comment by artemyarulin** [comment]
No prob, glad that your issue got resolved :)

**Comment by garbles** [comment]
@artemyarulin Does this address your issue? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16645

**Comment by artemyarulin** [comment]
Yeah, looking forward to get it merged 👍

**Comment by artemyarulin** [comment]
Closed via https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16645
