### ISSUE TITLE
webdriverio.Client.$$ returns Array

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#16841]
- [x] I tried using the `@types/webdriverio` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nmalaguti @timbru31

`webdriverio.Client.$$` returns an Array that you can map over, etc:

```
browser.$$('foo').map(() => {})
```

However this throws a compile error due to incorrect typings.

**Comment by timbru31** [comment]
Thanks, I'll take a closer look later today 👍
