### ISSUE TITLE
[Bug] Redux-Form FormComponentProps interface, onSubmit should be handleSubmit

### ISSUE THREAD

**Issue by luchillo17** [DefinitelyTyped/DefinitelyTyped#16856]
- [x] I tried using the `@types/redux-form` package and had problems.
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @carsonf, @aikoven, @LKay

### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
Types for `@types/redux-form` for `FormComponentProps` interface are like this:
```ts
export interface FormComponentProps extends HTMLProps<HTMLFormElement> {
    /**
     * The function to call when form submission is triggered.
     */
    onSubmit: FormSubmitHandler;
}
```

### What is the expected behavior?
It should be like this:
```ts
export interface FormComponentProps extends HTMLProps<HTMLFormElement> {
    /**
     * The function to call when form submission is triggered.
     */
    handleSubmit: FormSubmitHandler;
}
```

### What's your environment?

redux-form@6.7.0
For typedef and this issue none other matter.

### Other information
This is what i'm forced to do, note the type casting from `this.props` to `any` in `render` function:
```ts
interface ProductProps extends FormComponentProps, RouteComponentProps<any> {
  product: Product;
}

class ProductPage extends React.Component<ProductProps, any> {

  constructor(props: ProductProps) {
    super(props);

    this.state = {
      isNew: !this.props.match.params.id
    };
  }

  public handleSubmit(values) {
    console.log('values: ', values);

  }

  public render(): JSX.Element {
    const handleSubmit = (this.props as any).handleSubmit;
    return (
      <Jumbotron>
        <div className="Product">
          <Panel>
            <h1>{this.state.isNew ? 'Nuevo ' : ''}Producto</h1>
          </Panel>
          <Panel>
            <form onSubmit={handleSubmit(this.handleSubmit)}>
            ...
```

**Comment by luchillo17** [comment]
Originally posted in the `redux-form` repo: https://github.com/erikras/redux-form/issues/2987

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
