### ISSUE TITLE
_spPageContextInfo missing a lot of properties from SharePoint Online

### ISSUE THREAD

**Issue by baywet** [DefinitelyTyped/DefinitelyTyped#16892]
- [x] I tried using the `@types/SharePoint` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @StefanSchoof @andy-ms 

If you expand _spPageContextInfo when browsing a SharePoint online site, you get a lot more properties than currently exposed by the type definition.
The one I'm currently interested into is the `webId` but things like `groupId` `correlationId` and so on could help a lot too.
It'd be good to have those properties reflected in the type definition.

**Comment by StefanSchoof** [comment]
Create a Pull Request with adding these new properties.
