### ISSUE TITLE
react-tether typings module doesn't match library's export

### ISSUE THREAD

**Issue by voliva** [DefinitelyTyped/DefinitelyTyped#16909]
### Description
When using `@types/react-tether` with `react-tether` and the following `tsconfig.json`:

```
    "compilerOptions": {
        "noImplicitAny": false,
        "removeComments": false,
        "preserveConstEnums": true,
        "experimentalDecorators": true,
        "sourceMap": true,
        "noEmitOnError": true,
        "jsx": "react",
        "target": "es5",
        "module": "commonjs",
        "noEmit": true,
        "importHelpers": true,
        "allowSyntheticDefaultImports": true
    }
```

Importing the component through `import TetherComponent from 'react-tether';` and using it, TSC will compile succesfully, but on runtime React will throw an error with:
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### Steps to Reproduce

1. Install `react-tether` (last version, 0.5.7)*
2. Install `@types/react-tether` (last version, 0.5.1)
3. Import and use the component
4. Transpile the file (currently running last version of tsc, 2.3.4)
5. Run it

**Expected behavior:** [What did you expect to happen?]
React tether works properly

**Actual behavior:** [What actually happened?]
React throws an error where the value of the import is undefined.

*Note: I already tested with matching versions 0.5.1 on both react-tether and @types, but it still doesn't work

### Reason behind
Debugging on the transpiled code, when we import `react-tether` we get directly `TetherComponent` class, ready to be used by react.

However, when using it after importing with `import TetherComponent from 'react-tether'`, it transpiles to something like `React.createElement(TetherComponent.default, ...)`, and as it doesn't have `default` defined, it tries to create an undefined element.

By importing with `import * as ReactTether from 'react-tether';`, then we are forced to use it as `ReactTether.default` by TSC (because it understands ReactTether as module), so we get the same transpilation

### Temporal workaround
We must trick the module loader AND tsc, by doing this:
```
import * as ReactTether from 'react-tether';
import TetherComponentType from 'react-tether';
const TetherComponent = (ReactTether as any) as typeof TetherComponentType;
```

This is quite ugly. So I'm importing ReactTether as a module (when it gets used after transpiling, it doesn't call `.default`, and on runtime, I know that it gets imported as a the component), and cast it to the type of TetherComponentType, so I get all the type checks from TSC.

edit: I haven't tried, but looks like `const TetherComponent = (ReactTether as any) as typeof ReactTether.default` should work as well.

### Request
@ryprice I'm out of ideas on how to fix this. I would really appreciate if anyone has some hint, and I'm happy to further investigate and fix it.

**Comment by ryprice** [comment]
@volivia sorry for the slow response. I'm also seeing this error. It seems like the definition is technically correct, but the way react-tether is exporting is actually the broken part. I filed an issue there and we'll see whether they're willing to take my PR. https://github.com/souporserious/react-tether/issues/52

**Comment by ryprice** [comment]
@voliva this actually just got fixed in the most recent release of react-tether on npm a few days ago.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
