### ISSUE TITLE
@types/knex: Property 'modify' does not exist on type 'QueryBuilder'.

### ISSUE THREAD

**Issue by bradsimantel** [DefinitelyTyped/DefinitelyTyped#16919]
- [x] I tried using the `@types/knex` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkQubo, @baronfel 

I'm pretty new to TypeScript, so I'm not really confident enough to make a PR myself, but I ran into an error where the modify method is missing from the QueryBuilder interface. For reference, here's the method in the Knex docs: http://knexjs.org/#Builder-modify

**Comment by 100GPing100** [comment]
I'm commenting here as this seems to be solved by the pull request #24235. This issue should be closed if that is true as it only brings clutter into the issue list.

**Comment by bradsimantel** [comment]
Awesome! Closing now!
