### ISSUE TITLE
@types/three Cannot find Iterable

### ISSUE THREAD

**Issue by JKwasek** [DefinitelyTyped/DefinitelyTyped#16939]
- [ ] I tried using the `@types/three` package and had problems.
I tried to write the simplest application using typescript and three.js library. I have installed everything using npm and during compilation I have the following compilation error:

C:\Users\Jacek\documents\visual studio 2015\Projects\NodejsConsoleApp1\NodejsConsoleApp1>tsc app
node_modules/@types/three/three-core.d.ts(767,24): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/three/three-core.d.ts(771,24): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/three/three-core.d.ts(775,24): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/three/three-core.d.ts(779,24): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/three/three-core.d.ts(783,24): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/three/three-core.d.ts(787,24): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/three/three-core.d.ts(791,24): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/three/three-core.d.ts(795,24): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/three/three-core.d.ts(799,24): error TS2304: Cannot find name 'Iterable'.

Could you help me?

**Comment by andy-ms** [comment]
Try setting [`--lib es6`](http://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by jay3sh** [comment]
@andy-ms i think you meant `--target es6`. That's what worked for me.

**Comment by andy-ms** [comment]
`--target` can set `--lib` as a side effect if you didn't already specify a value. So they would both work.

**Comment by JKwasek** [comment]
Thanks for help :)

**Comment by iTwangcj** [comment]
![image](https://user-images.githubusercontent.com/7961076/30638308-93862624-9e2d-11e7-8739-e22e6828ab61.png)
![image](https://user-images.githubusercontent.com/7961076/30638325-9fa0f8ee-9e2d-11e7-97de-60a1b365ff65.png)

**Comment by preist** [comment]
I tried some of these, but to no avail. I kept getting a `Cannot find name 'Iterable'` error. What finally worked for me was to install the node typing.

```bash
node i --save @types/node
```

**Comment by flyher** [comment]
@JKwasek 
add this in your tsconfig.json
```json
"compierOptions" : {
     "lib" : ["es2015", "es2015.iterable", "dom"]
}
```
