### ISSUE TITLE
boom: BoomError lacks data member

### ISSUE THREAD

**Issue by garthk** [DefinitelyTyped/DefinitelyTyped#16956]
- [x] I tried using the `@types/boom` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @AJamesPhillips 

You need `data?: any` in `BoomError`, else:

```
error TS2339: Property 'data' does not exist on type 'BoomError'.
```

To show `data` in action:

```
$ node
> require('boom').create(400, 'fnord', { a: 1 }).data
{ a: 1 }
```

**Comment by AJamesPhillips** [comment]
Thanks @garthk .
