### ISSUE TITLE
@types/async definition of AsyncIterator<T, E> clashes with Typescript 2.3's AsyncIterator<T> declaration

### ISSUE THREAD

**Issue by marklawlor** [DefinitelyTyped/DefinitelyTyped#16980]
- [ x ] I tried using the `@types/xxxx` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @kern0 @penryn @fenying @pascalmartin 

Typescript 2.3 (`lib.esnext.asynciterable.d.ts`) defines an AsyncIterator as 
```
interface AsyncIterator<T> {
    next(value?: any): Promise<IteratorResult<T>>;
    return?(value?: any): Promise<IteratorResult<T>>;
    throw?(e?: any): Promise<IteratorResult<T>>;
}
```

types/async is defining an AsyncIterator as
```
interface AsyncIterator<T, E> { (item: T, callback: ErrorCallback<E>): void; }
```

This causes an `error TS2428: All declarations of 'AsyncIterator' must have identical type parameters.` when trying to use Typescript 2.3.4 with the `"lib": ["esnext"]` option in your tsconfig.

**Comment by gunzip** [comment]
@andy-ms  @sasanj this prevent using the whole async library with TS >= 2.3.x

**Comment by marklawlor** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19870
