### ISSUE TITLE
@types/hapi has wrong ServerConnection table() type

### ISSUE THREAD

**Issue by makepanic** [DefinitelyTyped/DefinitelyTyped#17005]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jasonswearingen @AJamesPhillips

The Hapi.Server has a [ServerConnection array](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi/index.d.ts#L75) which exposes a [`table()`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi/index.d.ts#L1569) method.
The official [hapi documentation](https://hapijs.com/api/16.1.1#serverconnections) doesn't tell readers what the return value is.

Looking at the [`table()` source](https://github.com/hapijs/hapi/blob/master/lib/connection.js#L336) one can see that it calls the table method on its `_router`.
Turns out that `_router` is an instance of [`Call.Router`](https://github.com/hapijs/hapi/blob/master/lib/connection.js#L81) which gets imported from the [`hapijs/call`](https://github.com/hapijs/call) module.

The `call` routers `table` method returns an [array of its routes](https://github.com/hapijs/call/blob/master/lib/index.js#L358).
Here a route is an [object with some properties](https://github.com/hapijs/call/blob/master/lib/index.js#L51-L58).

This means that the current ServerConnection `table()` method types are wrong.

I would like to fix this but am unsure if this requires a type definition for the `hapijs/call` module or if it's ok to create an interface for the call route object for now.

See attachment for example call route object:
![20170606-210614](https://user-images.githubusercontent.com/1205444/26848232-ffa70f98-4aff-11e7-9c15-814723a1ffb6.png)

**Comment by jasonswearingen** [comment]
@makepanic no problems creating an ad-hoc interface for this.   if/when a ```hapijs/call``` module definition is done, it won't cause a problem as long as it resolves the same (duck-typing).
