### ISSUE TITLE
pouchdb-core Generics

### ISSUE THREAD

**Issue by WorldMaker** [DefinitelyTyped/DefinitelyTyped#17039]
I'm looking to switch from a version of PouchDB typings that was forked back in ancient times to the latest `@types/pouchdb-*` and the thing that immediately struck me was that the generic specification in `pouchdb-core` for `Database<Content extends ...>`  seems to be very inconvenient to my usage cases. Perhaps this is just a difference in how the tools are used, but my usage of PouchDB is typically as a rather heterogeneous data store with no top-level "base" type, and PouchDB instances passed around for multiple uses. Instead, I would like to be able to narrow types at the times of specific queries.

I propose that the generic argument should be removed from `Database` and should be moved entirely to the operation level: `allDocs<T>(...)` and `get<T>(...)`.

I realize that this would be quite a bit of rework and I'd be happy to do that and submit a PR, but wanted to make sure that I wasn't missing some reason for the current use of generic arguments, and that the PR would be welcome if I produce it.

- [x] I tried using the `@types/pouchdb-core` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @spaulg, @trubit, @geppy, @fredgalvao

**Comment by fredgalvao** [comment]
I failed to see why having the generics at the operation level prevents you from having an hererogeneous database service layer.

Would you mind providing more an example of how the current structure fails in delivering correctness and language service assistance?

**Comment by WorldMaker** [comment]
Having the generics *at* the operation level would make it very easy to have a heterogeneous database service layer.

My issue is that currently the generics are at the database level, instead of the operation level, which gets in the way of a heterogeneous database service layer.

At the moment:

```ts
import * as PouchDB from 'pouchdb-core'

interface Cat { /* ... */ }
interface Boot { /* ... */ }

const db = new PouchDB<{} /* I don't what will be queried at instantiation time */>()
const cat = db.get('cat/172') as Cat // now I have cast/type assert and I miss out on the intersection type mixins
const boot = db.get('boot/345') as Boot & PouchDB.GetMeta // might as well manually use the intersection, too
```

It certainly seems preferable to me to allow the generic at the operation level:

```ts
import * as PouchDB from 'pouchdb-core'

interface Cat { /* ... */ }
interface Boot { /* ... */ }

const db = new PouchDB() // No need to specialize the database
const cat = db.get<Cat>('cat/172') // I don't have to manually intersect the type
```

**Comment by fredgalvao** [comment]
I get it now, thanks.

The thing is, both approaches are valid, and there's no easy way known to me to satisfy both with the same contract.

I'm not using the latest version of this type definition myself for other reasons, but the layer where the type lives in my version is the same, so I'll assume my case is a valid one for this discussion.

In my case, I have one global pouch instance connected to the DB without a specific/concrete type, and then I have multiple layers/services that have each their own type scope, which allows me to have a `CatDbService` and `BootDbService` according to your examples. I am always responsible to convert the raw type from pouch to the concrete type of the public api of each of my services, but that was also abstracted away so I had little trouble with it.

```ts
this.lowLevelDB = new PouchDB('<saywhat>', { adapter: 'websql', auto_compaction: true });
```

This is the signature of the base class used for all concrete layers:
```ts
class GenericDB<T extends models.BasicModel, U extends models.BasicModelProperties>
```

The constructor takes the generic type constructor, and the generic pouch db:
```ts
constructor(private clazz: models.ModelConstructor<T, U>, private lowLevelDB: pouchdb.thenable.PouchDB) { }
```

This is an example of the public api that handles generic types inside, and answers the concrete type to the caller:
```ts
findById(_id: string): Promise<T> {
	return this.lowLevelDB.get(_id).then((response) => {
		return new this.clazz(<U><pouchdb.api.methods.BaseDoc>response);
	});
}
```

An example of a concrete DB I have is:
```ts
this.PlaceDB = new GenericDB<models.Place, models.PlaceProperties>(models.Place, this.lowLevelDB);
```

And it's used as in:
```ts
return this.DBManager.PlaceDB.findById(currentTable.$_placeId).then((place) => {
	return this._fillCaches(placeMenu._id, place.$_syncId).catch(()=> { });
});
```

Language service assistance and correctness are both achieved on all layers except for the raw pouch calls, and the implementation I had to do on top of Pouch was a fair price to pay, imo.

I don't think we have a clear answer for this: any side we pick would leave the other side in need of a mannually implemented abstraction layer to achieve language service assistance and correctness.

**Comment by trubit** [comment]
Cant these two approaches be mixed together?
Its generics and typescript allow unions etc. I did last big update on typings, and personally I would prefer suggested solution. But others might not. 
I think its possible to mix it and make generic return type optional.

**Comment by trubit** [comment]
For making it optional maybe this is needed:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#generic-parameter-defaults

**Comment by WorldMaker** [comment]
I forgot about generic parameter defaults; yeah that definitely looks like the solution to me. I will make a PR for that.
