### ISSUE TITLE
highlight

### ISSUE THREAD

**Issue by BurtHarris** [DefinitelyTyped/DefinitelyTyped#17077]
- [x] I tried using the `@types/xxxx` package and had problems..
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:  Niklas Mollenhauer <https://github.com/nikeee/>, Jeremy Hull <https://github.com/sourrust>
Sorry, no matches to these name when I try `@`

Problem: at compile time 
`C:/try/buzzsaw/node_modules/@types/highlight.js/index.d.ts(19,40): error TS2304: Cannot find name
'Node'.`

```typescript
// Type definitions for highlight.js v9.1.0
// Project: https://github.com/isagalaev/highlight.js
// Definitions by: Niklas Mollenhauer <https://github.com/nikeee/>, Jeremy Hull <https://github.com/sourrust>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
````

**Comment by BurtHarris** [comment]
Privately, I've just changed the `Node` in the referenced line to `any`.   I don't know anything about highlight.js, it's not a dependency I chose.

**Comment by andy-ms** [comment]
You need [`--lib dom`](http://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by JoshuaKGoldberg** [comment]
See https://github.com/TypeStrong/typedoc/issues/529: highlight.js is meant to work with jsdom (so without `--lib dom`). I'll send a PR...

**Comment by JoshuaKGoldberg** [comment]
@BurtHarris is this issue resolved?

**Comment by BurtHarris** [comment]
Frankly I've forgotten how to reproduce it, I think I gave up on the code which was using it.    However, reading through this thread, it sounds like it should be.    I'll go ahead and mark closed.
