### ISSUE TITLE
[Request] Update definitions for Highland

### ISSUE THREAD

**Issue by hgwood** [DefinitelyTyped/DefinitelyTyped#17090]
In #16523 ([this comment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16523#issuecomment-302863224)), @vqvu from the Highland team provided valuable information about what's missing or incorrect in the type definitions. I'm leaving this here so that future contributors to these type definitions can found this information.

**Comment by iwllyu** [comment]
I added a few definitions here: https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...iwllyu:highland/add-types

> added consumers: done, toCallback
added transforms: batch, batchWithTimeOrCount, doto, drop, findWhere, tap
added interfaces: PipeableStream and PipeOptions (neither are being used)

And the I reorganized all the functions alphabetically, grouped by section like how the docs are at [highlandjs](http://highlandjs.org) - https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...iwllyu:highland/organize-functions

and I organized vqvu's comment to the groupings, striking out what I put in my branch

### PipeableStream

Not all Highland streams can be used as an argument to `pipe`: only the ones returned by `highland()`and `highland.pipeline()`. To enforce this, I suggest adding this type

```source-ts
interface PipeableStream<T, R> extends Stream<R> {
    // No extra methods. Used to capture the extra "input" type T.
}
```

### Bugs

-   `StreamError` and `StreamRedirect` are not public.
-   `pipe` - Always returns `dest`
    -   `pipe<U>(dest: Stream<U>): Stream<U>` should be `pipe<U>(dest: PipeableStream<R, U>): Stream<U>`.
    -   `pipe<U>(dest: NodeJS.ReadWriteStream): Stream<U>` and `pipe(dest: NodeJS.WritableStream): void` should be more like `pipe<U extends NodeJS.WritableStream>(dest: U): U`
-   `apply` - The type of `f` is probably `(...args: R[]) => void`.
-   `flatMap` - `flatMap<U>(f: (x: R) => U): Stream<U>;` is not a valid type signature.
-   `parallel` - `parallel` turns a `Stream<Stream<R>>` into a `Stream<R>`, not `Stream<R>` to `Stream<R>`. Not sure if this is representable in typescript.
-   `reduce1` - Should be `reduce1(f: (memo: R, x: R) => R): Stream<R>`.
-   `scan1` - Should be `scan(f: (memo: R, x: R) => R): Stream<R>`.
-   `merge` - Same type as `parallel`. Definitely doesn't take an argument.
-   `zip` - Returns a tuple, so more like `zip<U>(ys: U[] | Stream<U>): Stream<[R, U]>`.
-   `each` - This was changed. It now looks like `each(f: (x: R) => void): Stream<never>`. Can `never`be a type parameter? If not, then it should be `void`. Point is, `each` always returns an empty stream.
-   Stream constructor.
    -   `<R>(): Highland.Stream<R>` should be `<R>(): PipeableStream<R, R>`.
    -   `<R>(xs: Highland.Thenable<Highland.Stream<R>>): Highland.Stream<R>` is not a valid signature.

### New stuff

-   Constructor
    -   `<R>(xs: Iterator<R>): Highland.Stream<R>`
    -   `<R>(xs: Iterable<R>): Highland.Stream<R>`

#### Transforms
-   ~~`batch(n: number): Stream<R[]>`~~
-   ~~`batchWithTimeOrCount(ms: number, n: number): Stream<R[]>`~~
-   ~~`doto(f: (x: R) => void): Stream<R>`~~
-   ~~`drop(n: number): Stream<R>`~~
-   ~~`findWhere(props: Object): Stream<R>`~~
- intersperse (missing)
-   `nfcall<U>(args: any[]): Stream<U>`
-   `pick(properties: string[]): Stream<Object>`
-   `pickBy(f: (key: string, value: any) => boolean): Stream<Object>`
-   `rateLimit(num: number, ms: number): Stream<R>`
-   `slice(start: number, end: number): Stream<R>`
-   `sort(): Stream<R>`
-   `sortBy(f: (a: R, b:R) => boolean): Stream<R>`
-   `split(): Stream<string>` - Only works on `Stream<string>` and `Stream<Buffer>`.
-   `splitBy(sep: string | RegExp): Stream<string>`
-   ~~`tap(f: (x: R) => void): Stream<R>`~~
-   `transduce<U>(f: Transducer<any, R, U>): Stream<U>` - `Transducer` defined in the [transducer-js types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/transducers-js/index.d.ts)
-   `uniq(): Stream<R>`
-   `uniqBy(compare: (a: R, b:R) => boolean): Stream<R>`

#### Higher-order streams
-   `mergeWithLimit<U>(n: number): Stream<U>` - Same as `merge`, `parallel`, etc.
-   `pipeline<T, R>(...args: PipelineArgs[]): PipeableStream<T, R>` where `PipelineArgs = Function | NodeJS.ReadWriteStream | PipeableStream<any, any>`. Static.
-   `through<U>(f: (s: Stream<R>) => Stream<U> | NodeJS.ReadWriteStream | PipeableStream<R, U>): Stream<U>`
-   `zipAll(ys: any[][] | Stream<Stream<any>>): Stream<any[]>` - Is this how you do arrays of arrays?
-   `zipAll0(): Stream<any>` - Actually turns `Stream<Stream<any>>` into `Stream<any[]>`

#### Consumption
-   ~~`done(f: () => void): void`~~
-   ~~`toCallback(cb: (err?: Error, x?: R) => void): void`~~

#### Utils
-   `fromError(err: Error): Stream<never>` Static
-   `of<R>(x: R): Stream<R>` Static
-   `streamifyAll(source: Object): Object`
-   `streamifyAll<T>(source: {new(): T;}): {new(): T}` - Alternatively, just `streamifyAll(source: Function): Function`.

**Comment by hgwood** [comment]
Looks nice! You should definitely open a PR.

**Comment by iwllyu** [comment]
After this was merged I ran `typings install dt~highland --G --S` but typings pulled down the previous version. Is there some place where we need to specify the version for typings to see the latest?

the entry in typings.json is `"highland": "registry:dt/highland#1.14.0+20160510010627",`

I know I can specify a commit hash with `"github:DefinitelyTyped/DefinitelyTyped/highland/index.d.ts#50387d40462301d54cda62e24d3b2ee46540f24a",`

but I'd like to know how to get typings install to pick up the latest

**Comment by hgwood** [comment]
`npm info @types/highland` shows a version 2.10.1 published on 2017-06-16, so publication is good. I don't know how `typings` work though.

**Comment by albertorestifo** [comment]
Version 3 of Highland is in Beta and brings more changes: https://github.com/caolan/highland/blob/master/CHANGELOG.md#300-beta5

**Comment by taybin** [comment]
Any updates on this?  Some functions such as `split` and `splitBy` are still missing.

**Comment by taybin** [comment]
Also noticed that the constructor doesn't have:
```
interface CleanupObject {
  onDestroy?: Function;
  continueOnError: boolean;
}
type onFinished = (r: Readable, cb: Function) => void | Function | CleanupObject;
<R>(xs: Readable, of: onFinished): Highland.Stream<R>
```
This makes the current typings unusable with wrapping streams that require the `onFinished()` argument for cleanup.

**Comment by taybin** [comment]
PR for above comment here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36140 (doesn't address split/splitBy/other items)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
