### ISSUE TITLE
Tabs vs spaces?

### ISSUE THREAD

**Issue by Bartvds** [DefinitelyTyped/DefinitelyTyped#1709]
If was running some code against the definitions and was shocked how the repo is infested with [mixed use of tabs and spaces](http://i.imgur.com/vOWAAUK.png). 

We could organise a battle to decide on tabs vs space, but nobody wins there.

Maybe we should just stick with whatever style the original was created and enforce that?

I think we could combine [detect-indent](https://www.npmjs.org/package/detect-indent) with TSLint in the tester (when we have #1314).

**Comment by BirdTho** [comment]
Final conclusion? I just want to contribute, what the heck are you using?

**Comment by basarat** [comment]
> Final conclusion? I just want to contribute, what the heck are you using

Consistent per file.

**Comment by jedmao** [comment]
@basarat the comic is wrong. We all know the Apple guy would use spaces and the Microsoft guy would use tabs.

**Comment by basarat** [comment]
@jedmao I'm an ms guy and I use spaces :)

**Comment by vvakame** [comment]
I think #4211 is nice proposal.

**Comment by davidreher** [comment]
I would propose to use 2 spaces as done in the [airbnb/javascript](https://github.com/airbnb/javascript) styleguide ...

**Comment by glen-84** [comment]
Suggestion: Use the coding standards set out by the library being typed. If the library being typed uses spaces, single quotes, and LFs, then do the same in the type definition. This way we can avoid the spaces vs tabs argument.

The only problem is that it won't be easy to enforce this rule. If you need to enforce it and have full consistency, then I would recommend going with the most popular conventions. According to [this](http://sideeffect.kr/popularconvention/#javascript) website, it's spaces and single quotes.

My personal preference is spaces (4) and *double* quotes, but I'm okay with using single quotes if it means that everything is consistent.

Could the pro-tab and pro-tab-space users accept a similar compromise?

**Comment by basarat** [comment]
> My personal preference is spaces (4) and double quotes, but I'm okay with using single quotes if it means that everything is consistent.

@glen-84 purely for your amusement ... here why the compiler team used double quotes : https://github.com/Microsoft/TypeScript/issues/5811#issuecomment-160187924

* JSON 
* Works across all languages so less of a cognitive load

I personally go with single quotes myself as I find myself doing more and more doing TypeScript exclusively :rose:

**Comment by glen-84** [comment]
I think it's also a bit more legible, and it was 57% vs 43% (not a big difference), but I guess you have to draw the line somewhere. =)

**Comment by GeertJohan** [comment]
I like @jedmao's point on tabs for indentation and spaces for alignment. 

Full disclosure: I'm coming from the Go-land where we have `go fmt` and no discussions about tabs or spaces ever.. It's tabs for indentation and spaces for alignment and it works very very well :+1:

**Comment by hinell** [comment]
Spaces only. Cause nobody knows know how the tabs are exactly rendering in different editors.

**Comment by jedmao** [comment]
@hinell why does it matter if tabs are rendered differently in different editors? It shouldn't, so long as tabs are "only" used for indentation.

**Comment by ExE-Boss** [comment]
I&nbsp;prefer tabs, especially because of&nbsp;this: http://nickgravgaard.com/elastic-tabstops/

**Comment by ExE-Boss** [comment]
Turns&nbsp;out, there’s&nbsp;an&nbsp;even bigger&nbsp;reason to&nbsp;use&nbsp;tabs: **developer&nbsp;accessibility**.

- <https://github.com/prettier/prettier/issues/7475>
- <https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/>

**Comment by jakebailey** [comment]
The repo was formatted consistently using dprint a few months ago, so this is settled.
