### ISSUE TITLE
[react-native] Wrong type definition for Easing.elastic

### ISSUE THREAD

**Issue by PublicParadise** [DefinitelyTyped/DefinitelyTyped#17103]
### Problem

The current definition of `Easing.elastic` reads:
```typescript
elastic: EasingFunction;
```
But `elastic` in [react-native/Libraries/Animated/src/Easing.js](https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/Easing.js#L171)  is implemented as:
```
static elastic(bounciness: number = 1): (t: number) => number { ... }
```

### Proposed Fix

Change the current definition of `Easing.elastic` to:
```typescript
elastic: (bounciness: number) => EasingFunction;
```
(`elastic` is not an `EasingFunction`, it is a utility function that *returns* an `EasingFunction`)

### Issue Form

- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy, @gyzerok, @huhuanming, @jeremistadler

### Thanks

BTW, you guys are doing a great job keeping the `react-native` typescript definition files up to date. I appreciate your work!

**Comment by PublicParadise** [comment]
Alternatively you could define 
```typescript
type ElasticFunction = (bounciness: number) => EasingFunction;
```
and then use `ElasticFunction` instead `EasingFunction`:
```typescript
elastic: ElasticFunction;
```
But sometimes it's clearer to just spell out the declaration:
```typescript
elastic: (bounciness: number) => EasingFunction;
```
I am on the fence on which one is better...

**Comment by alloy** [comment]
If it’s just one typing, then I’d say the latter. If you need the typing you can always just grab it from the interface. Will you be creating a PR for this?

Thanks for the appreciation! 🙏🏽

**Comment by PublicParadise** [comment]
@alloy: I submitted a PR but I didn't go through the trouble of disabling Visual Code's [format on save](https://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
