### ISSUE TITLE
[@types/node] Wrong type definition for emit

### ISSUE THREAD

**Issue by tedlines** [DefinitelyTyped/DefinitelyTyped#17142]
in this commit
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/c9e01b3e760ee7e2f93a7c9052d432f6713347c8#diff-7d84e08967cded0b99ed4328aab0a1a8R489
EventEmitter arguments were defined like this. 
emit(event: Signals, listener: () => void): boolean;
but as below,
https://nodejs.org/dist/latest-v8.x/docs/api/events.html#events_emitter_emit_eventname_args
emitter.emit(eventName[, ...args])
The arguments except 'eventName' can be omitted.

it should be changed like this.
emit(event: Signals, listener?: () => void): boolean;

**Comment by mika-fischer** [comment]
emit does not take a listener argument, so it should actually be replaced by the arguments to the callback or removed altogether if the callback has no arguments.
