### ISSUE TITLE
[@types/strophe] ES6 import doesn't work anymore with 1.2.28 (it worked with 1.2.27)

### ISSUE THREAD

**Issue by nud** [DefinitelyTyped/DefinitelyTyped#17148]
- [x] I tried using the `@types/strophe` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @icholy @DavidKDeutsch 

(proposed fix below)

When updating from `@types/strophe` 1.2.27 to 1.2.28 the following construct doesn't work anymore:

```typescript
import { Strophe } from 'strophe'
```

`tsc` (typescript 2.3.4) gives the following error:

```
ERROR in [...]: Module '"strophe"' resolves to a non-module entity
and cannot be imported using this construct.
```

The only seemingly relevant difference I could spot was the way the module is declared. The working version (1.2.27) used this:

```typescript
declare module 'strophe' {
    export = wrapper;
}
```

while the new one (1.2.28) uses this instead:

```typescript
// Support AMD require
declare module "strophe" {
  export = { Strophe, $build, $msg, $iq, $pres };
}
```

The change was introduced in commit 1b814e5ba706ff92c1ecb8459750d7c6536bb19e.

Removing the `declare module` blocks and adding an `export` to all the `declare` above instead fixes the issue. I can make a pull request if you wish but I am unsure of the implications. It would look like this:

```typescript
export declare namespace Strophe { ... }
export declare function $build(name: string, attrs?: any): Strophe.Builder;
export declare function $msg(attrs?: any): Strophe.Builder;
export declare function $iq(attrs?: any): Strophe.Builder;
export declare function $pres(attrs?: any): Strophe.Builder;
```

For reference, I am using the `strophe.js` 1.2.13 npm module and `@angular/cli` 1.1.1 with the following `tsconfig.app.json` to map the `@types` name with the actual npm library name:

```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "baseUrl": "",
    "paths": {
      "strophe": ["../node_modules/strophe.js"]
    },
    "types": []
  },
```

**Comment by icholy** [comment]
@nud using the `export` breaks my code because `Strophe` isn't globally available anymore.

**Comment by nud** [comment]
@icholy well then you can also revert to the pre-1.2.28 way of doing things, which worked fine.

**Comment by icholy** [comment]
@nud the old way introduces a global `wrapper` namespace which is ugly.

**Comment by nud** [comment]
Hi

What is your (working) way of importing strophe then?

**Comment by icholy** [comment]
@nud I'm not using imports right now. It's pretty annoying because I can't figure out a way to make it work as a `umd`. The `export as namespace` doesn't fit here because there is more than one global being defined. Here's a simpler version of the problem.

``` ts
declare namespace Foo {}
declare function bar(): string;
```

We want those to be globally available to people not using `import`s and also expose a "strope" module which exports those values. @RyanCavanaugh is there a way to do this?

**Comment by serpaulius** [comment]
@nud @icholy @DavidKDeutsch 
As of `@types/strophe` version 1.2.30 there are many errors when trying to use the type definitions anywhere in an Angular 4+ (in my case Ionic 3.9.2) project:

```
[12:20:11]  typescript: node_modules/@types/strophe/index.d.ts, line: 1093
            Module '"xxxx/node_modules/@types/strophe/index"' has no exported
            member 'Strophe'.

    L1092:  type Status = _Strophe.Status;
    L1093:  type LogLevel = _Strophe.LogLevel;
    L1094:  type Builder = _Strophe.Builder;

[12:20:11]  typescript: node_modules/@types/strophe/index.d.ts, line: 1093
            Module '"xxxx/node_modules/@types/strophe/index"' has no exported
            member '$build'.

    L1092:  type Status = _Strophe.Status;
    L1093:  type LogLevel = _Strophe.LogLevel;
    L1094:  type Builder = _Strophe.Builder;

[12:20:11]  typescript: node_modules/@types/strophe/index.d.ts, line: 1093
            Module '"xxxx/node_modules/@types/strophe/index"' has no exported
            member '$msg'.

    L1092:  type Status = _Strophe.Status;
    L1093:  type LogLevel = _Strophe.LogLevel;
    L1094:  type Builder = _Strophe.Builder;

[12:20:11]  typescript: node_modules/@types/strophe/index.d.ts, line: 1093
            Module '"xxxx/node_modules/@types/strophe/index"' has no exported
            member '$iq'.

    L1092:  type Status = _Strophe.Status;
    L1093:  type LogLevel = _Strophe.LogLevel;
    L1094:  type Builder = _Strophe.Builder;

[12:20:11]  typescript: node_modules/@types/strophe/index.d.ts, line: 1093
            Module '"xxxx/node_modules/@types/strophe/index"' has no exported
            member '$pres'.

    L1092:  type Status = _Strophe.Status;
    L1093:  type LogLevel = _Strophe.LogLevel;
    L1094:  type Builder = _Strophe.Builder;

[12:20:11]  typescript: node_modules/@types/strophe/index.d.ts, line: 1111
            Exports and export assignments are not permitted in module augmentations.

    L1110:    export = $build;
```

It is not an import problem, it is something wrong with those type definitions, and I cannot figure out a way to fix it.

Did you manage to use those types somehow with the newest Strophe? Which Strophe version type definitions 1.2.30 are compatible with?

There are some "solutions", but they are without any type definitions (only an `any` variable) which is ugly and.. why then are there type definitions at all?
https://stackoverflow.com/questions/43965906/strophe-xmpp-using-angular-2/47663574#47663574
https://stackoverflow.com/questions/44251412/ionic-2-with-strophe-not-working

Here is another user gave up and used `any` variable:
https://stackoverflow.com/questions/47169311/import-declaration-conflicts-when-using-strophe-muc

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
