### ISSUE TITLE
[d3] DragBehavior is not assignable to Selection.call parameter

### ISSUE THREAD

**Issue by alataffective** [DefinitelyTyped/DefinitelyTyped#17151]
Error described here: https://stackoverflow.com/questions/44472945/d3-js-and-typescript-compilation-error

tsc version 2.3.4
types/d3 version 4.9.0

Authors: @tomwanzek, @gustavderdrache, @borisyankov

Thank you.

**Comment by tomwanzek** [comment]
I'll answer on StackOverflow. The compilation error should simply stem from a mismatch between the element/bound data type combination of the drag behavior and the element(s) to which it is applied.

**Comment by tomwanzek** [comment]
The answer is now posted  on SO overflow, see [here](https://stackoverflow.com/questions/44472945/d3-js-and-typescript-compilation-error/44523718#44523718).

@alataffective  Given that your valid question, does not constitute an actual issue with the definition files themselves, this issue could be closed, I suppose. Hope this helped. :smile: T

**Comment by alataffective** [comment]
@tomwanzek Absolutely fantastic. I really appreciate your help and comprehensive answer. Thanks for the good work : )

**Comment by tomwanzek** [comment]
@alataffective No worries. You're welcome.
