### ISSUE TITLE
【@types/node】Is definition of IteratorResult<T> correct?

### ISSUE THREAD

**Issue by kyasbal-1994** [DefinitelyTyped/DefinitelyTyped#17184]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

![](https://i.gyazo.com/b3784ceb4285c4c1cbfd6c2e6f2a3a4f.png)

I'm afraid of misunderstanding of this definition or ambient of node environment. 
However, I guess this definition of `IteratorResult<T>` is wrong. This should contain `value:T` and `hasNext:boolean`, shouldn't it?

I guess `Iterable<T>` also contains something wrong since it is very weird to have type argument without using it in member properties in interface definition.

**Comment by andy-ms** [comment]
That is a forward-declaration. The full definition will be in `lib.es2015.d.ts`.

**Comment by kyasbal-1994** [comment]
@andy-ms Oh, I haven't see that. I'm sorry to create noob issue.
