### ISSUE TITLE
@types/jquery giving breaking solution while Gulp build

### ISSUE THREAD

**Issue by Parth2402patel** [DefinitelyTyped/DefinitelyTyped#17239]
@tdreyno 

- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

This errors are too many.

I am facing this issue today when used latest version. 

What might be going wrong? 

Error - typescript - node_modules\@types\jquery\index.d.ts(4306,101): error TS2304: Cannot find name 'any'.
Error - typescript - node_modules\@types\jquery\index.d.ts(4455,36): error TS2314: Generic type 'Deferred<TResolve, TRej
ect, any, TNotify>' requires 4 type argument(s).
Error - typescript - node_modules\@types\jquery\index.d.ts(4456,36): error TS2314: Generic type 'Event<TTarget, EventTar
get, TData>' requires 3 type argument(s).
Error - typescript - node_modules\@types\jquery\index.d.ts(4457,41): error TS2314: Generic type 'Event<TTarget, EventTar
get, TData>' requires 3 type argument(s).
Error - typescript - node_modules\@types\jquery\index.d.ts(4458,36): error TS2314: Generic type 'Deferred<TResolve, TRej
ect, any, TNotify>' requires 4 type argument(s).
Error - typescript - node_modules\@types\jquery\index.d.ts(4459,37): error TS2314: Generic type 'AjaxSettings<TContext,
any>' requires 2 type argument(s).
Error - typescript - node_modules\@types\jquery\index.d.ts(4461,43): error TS2694: Namespace 'JQuery' has no exported me
mber 'Coordinates'.
Error - typescript - node_modules\@types\jquery\index.d.ts(4463,28): error TS2314: Generic type 'jqXHR<TResolve, any>' r
equires 2 type argument(s).
Error - typescript - node_modules\@types\jquery\index.d.ts(4464,35): error TS2314: Generic type 'Promise<TResolve, TReje
ct, any, TNotify>' requires 4 type argument(s).
Error - typescript - node_modules\@types\jquery\index.d.ts(4465,53): error TS2694: Namespace 'JQuery' has no exported me
mber 'NameValuePair'.

Regards,
Parth Patel

**Comment by Parth2402patel** [comment]
@tdreyno 

I have replaced @types/jquery folder with my older version of solutions and it works fine for me.

Do you think this issue is due to latest version which is release yesterday 15th June.

Regards,
Parth

**Comment by mustafasadikot** [comment]
I have the same issue with webpack build. 

[1m[31mERROR in [at-loader] [31mnode_modules\@types\jquery\index.d.ts[39m:43:40 
      [31m',' expected.[39m[39m[22m
  
  [1m[31mERROR in [at-loader] [31mnode_modules\@types\jquery\index.d.ts[39m:2364:40 
      [31m',' expected.[39m[39m[22m
  
  [1m[31mERROR in [at-loader] [31mnode_modules\@types\jquery\index.d.ts[39m:2366:46 
      [31m',' expected.[39m[39m[22m
  
  [1m[31mERROR in [at-loader] [31mnode_modules\@types\jquery\index.d.ts[39m:2477:23 
      [31m',' expected.[39m[39m[22m
  
  [1m[31mERROR in [at-loader] [31mnode_modules\@types\jquery\index.d.ts[39m:2478:17 
      [31m',' expected.[39m[39m[22m
  
  [1m[31mERROR in [at-loader] [31mnode_modules\@types\jquery\index.d.ts[39m:2479:17 
      [31m',' expected.[39m[39m[22m
  
  [1m[31mERROR in [at-loader] [31mnode_modules\@types\jquery\index.d.ts[39m:3290:29 
      [31m',' expected.[39m[39m[22m
  
  [1m[31mERROR in [at-loader] [31mnode_modules\@types\jquery\index.d.ts[39m:3299:37 
      [31m',' expected.[39m[39m[22m
  
  [1m[31mERROR in [at-loader] [31mnode_modules\@types\jquery\index.d.ts[39m:3586:30 
      [31m',' expected.[39m[39m[22m
  
  [1m[31mERROR in [at-loader] [31mnode_modules\@types\jquery\index.d.ts[39m:3692:23 
      [31m',' expected.[39m[39m[22m
  
  [1m[31mERROR in [at-loader] [31mnode_modules\@types\jquery\index.d.ts[39m:3693:21 
      [31m',' expected.[39m[39m[22m
  
  [1m[31mERROR in [at-loader] [31mnode_modules\@types\jquery\index.d.ts[39m:3698:41 
      [31m',' expected.[39m[39m[22m

**Comment by Simon-Briggs** [comment]
Also getting an error after upgrading to the latest jquery typings:

```
Error at node_modules/@types/jquery/index.d.ts:2364:84: Cannot find name 'Iterable'.
```

**Comment by MichalMeszaros** [comment]
Last typing from yesterday with version 3.2 does not work for ajax methods correctly and building of typescript is failing.
for example snippet: 
`$.ajax({ url: url }).fail((jqXHR: JQuery.jqXHR.FailCallback, textStatus: string, errorThrown: string) => { });`
Interface JQuery.jqXHR.FailCallback does not contains all properties from jqXHR for example status
using 
`$.ajax({ url: url }).fail((jqXHR: JQuery.jqXHR, textStatus: string, errorThrown: string) => { });` 
will failed.

**Comment by rvanmarkus** [comment]
Also experiencing an error after upgrading to the latest jquery typings;
`Error at node_modules/@types/jquery/index.d.ts:2364:84: Cannot find name 'Iterable'.`

**Comment by klaask** [comment]
Same issue at our end on Centos 7 node 6.10.0 LTS, node 7.4 on macOS works fine.

**Comment by leonard-thieu** [comment]
@Parth2402patel @mustafasadikot @klaask 
Could you guys post repros?

@Simon-Briggs @rvanmarkus 
This happens if you're targeting `es5`. You'll need to add `es2015.iterable` to your `lib` in `tsconfig.json`.
```json
        "lib": [
            "dom",
            "es5",
            "scripthost",
            "es2015.iterable"
        ],
        "target": "es5",
```
Alternatively, you just change your target to `es6`.

@mustafasadikot 
`jqXHR` in the callback is currently annotated incorrectly. I'll put in a PR to fix it. Afterwards, you'll be able to use it without additional annotations.
```typescript
$.ajax({ url: url }).fail((jqXHR, textStatus, errorThrown) => { });
```

**Comment by Parth2402patel** [comment]
@leonard-thieu 

Have tried both options still nothing is working for me. 

This happens if you're targeting es5. You'll need to add es2015.iterable to your lib in tsconfig.json.

        "lib": [
            "dom",
            "es5",
            "scripthost",
            "es2015.iterable"
        ],
        "target": "es5",
Alternatively, you just change your target to es6.

Regards,
Parth

**Comment by leonard-thieu** [comment]
@Parth2402patel that fix doesn't apply to you. Your issue appears to be different. Could you post a repro?

**Comment by roddypratt** [comment]
Not sure if this is related  but I'm seeing something weird with yarn. `yarn outdated` shows 
```
yarn outdated v0.24.6
Package       Current Wanted Latest Package Type URL
@types/jquery 2.0.47  2.0.47 3.2.1  dependencies    
Done in 1.34s.
```
I then run yarn upgrade, and it whirrs away happily without error doing stuff, but when I then run `yarn outdated` again, the output is still the same. Other packages seem to upgrade fine.

**Comment by leonard-thieu** [comment]
@roddypratt 

yarn is indicating that there is a later version available than the version that you want. The version that you want is determined by the semver listed in your `package.json`. You probably have something like `"@types/jquery": "^2.0.47"`. The caret indicates to yarn that it should not upgrade to a higher major version number which is why it continues to list it even after running `yarn upgrade`.

**Comment by roddypratt** [comment]
@leonard-thieu Thanks. I misunderstood what caret meant, and this is the first package I've used with a major version change!

**Comment by alexw10** [comment]
I am seeing the same thing, trying to revert to 3.2.0 instead and see if that fixes it.

**Comment by leonard-thieu** [comment]
@alexw10 could you post a repro?

**Comment by roddypratt** [comment]
Ok, I have the update now, but what's the correct import syntax as `import * as $ from 'jquery` doesn't work any more. `Module "jquery" resolves to a non-module entity and cannot be imported using this construct.` What's the best source of info for the changes introduced by the V3 types file - short of doing a diff on the sources...?

**Comment by leonard-thieu** [comment]
This is the proper import syntax.
```typescript
import jqFactory = require('jquery');
const $ = jqFactory(window);
```
Keep in mind, you only need to use `import` if you're in an environment that doesn't provide a global `window` object. In other cases, jQuery is globally available and you can use `jQuery` and `$` as usual.

You can find a summary of changes at #17159.

**Comment by ccsCarolSerrao** [comment]
Resolve to me:

"target": "es6"

**Comment by roddypratt** [comment]
@leonard-thieu  That gives me:
 `Import assignment cannot be used when targeting ECMAScript 2015 modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.` 

Typescript 2.4, Webpack 2.61, target ES6, module ES6

**Comment by leonard-thieu** [comment]
@roddypratt ahh, okay. I think I'll need to put in a PR to fix that.

**Comment by mikehaas763** [comment]
As others have noted, this is a result of the new jquery type defs (v3) using `Iterable`. If jquery doesn't use es2015 features (which I don't think it does), such as `Iterable`, then these type defs should target lib "es5". Thoughts?

**Comment by leonard-thieu** [comment]
@mikehaas763 jQuery does indeed support `for-of` (since 1.12/2.2 actually).

From http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/
> We’ve added support for the Symbol type and iterators via Symbol.iterator added in ES6/ES2015. “Symbol” will be detectable with jQuery.type, and jQuery objects can be iterated with for-of where supported.
> 
> ```
> for (element of $elements) {
>   console.log(element);
> }
> ```

**Comment by mikehaas763** [comment]
Well, shit, lol. Is there a conventionalized mechanism for libs like jquery which do feature detection to limit the runtime types? If someone is targeting es5 with a library that supports es5, it would be nice to allow newer versions of @types/jquery which map to new jquery features and optionally support new es2015+ apis/constructs.

**Comment by mikehaas763** [comment]
I deleted my last comment by accident. Does jquery itself actually shim Symbol and symbol.iterator?

**Comment by leonard-thieu** [comment]
Doesn't look like it. These are pretty much the only mentions of 'Symbol' or 'iterator' in the library:
https://github.com/jquery/jquery/blob/f71eeda0fac4ec1442e631e90ff0703a0fb4ac96/src/core.js#L448
```javascript
if ( typeof Symbol === "function" ) {
	jQuery.fn[ Symbol.iterator ] = arr[ Symbol.iterator ];
}
```

**Comment by mikehaas763** [comment]
ahh, well, in that case I'm back to wondering if there's some official way to define the interface for libs that depends on the environment

**Comment by leonard-thieu** [comment]
I'm not sure. You could consider using the 2.x typedefs which don't use `Iterable`.
```json
"@types/jquery": "<2.2",
```

**Comment by roddypratt** [comment]
@leonard-thieu  3.2.2 fixes the import issue nicely. Thankyou!

**Comment by weching** [comment]
Same here, build issue with @types/jquery 3.2.5:

`[12:09:14][Step 1/2] node_modules/@types/jquery/index.d.ts(2394,40): error TS1005: ',' expected.
[12:09:14][Step 1/2] node_modules/@types/jquery/index.d.ts(2396,46): error TS1005: ',' expected.
[12:09:14][Step 1/2] node_modules/@types/jquery/index.d.ts(2476,28): error TS1005: ',' expected.
[12:09:14][Step 1/2] node_modules/@types/jquery/index.d.ts(2512,23): error TS1005: ',' expected.
[12:09:14][Step 1/2] node_modules/@types/jquery/index.d.ts(2513,17): error TS1005: ',' expected.
[12:09:14][Step 1/2] node_modules/@types/jquery/index.d.ts(2514,17): error TS1005: ',' expected.
[12:09:14][Step 1/2] node_modules/@types/jquery/index.d.ts(3306,29): error TS1005: ',' expected.
[12:09:14][Step 1/2] node_modules/@types/jquery/index.d.ts(3312,37): error TS1005: ',' expected.
[12:09:14][Step 1/2] node_modules/@types/jquery/index.d.ts(3319,40): error TS1005: ',' expected.
[12:09:14][Step 1/2] node_modules/@types/jquery/index.d.ts(3767,30): error TS1005: ',' expected.`

**Comment by tdreyno** [comment]
Someone must have typo'd, because I have nothing to do with this project. Sorry, hope you find the fix you need.

**Comment by leonard-thieu** [comment]
@weching You need to have TypeScript 2.3 or later.

**Comment by jrkd** [comment]
Just for note -- this is still happening on v3.2.5 when targeting ES3.

**Comment by leonard-thieu** [comment]
There's multiple issues reported in this thread.

---

### Iterable

If you're getting an error similar to
- `Error at node_modules/@types/jquery/index.d.ts:2364:84: Cannot find name 'Iterable'.`

You need to add `es2015.iterable` to `lib` in your `tsconfig.json`.

---

### Unsupported TypeScript Version

`@types/jquery` requires TypeScript 2.3 or higher.

If you're getting errors similar to

- `error TS2314: Generic type 'Deferred<TResolve, TReject, any, TNotify>' requires 4 type argument(s).`
- `error TS1005: ',' expected.`

You need to upgrade to `typescript@2.3` or later.

---

If these solutions are not an option for you, you can drop back to 2.x typings 

```json
"@types/jquery": "<2.2",
```

---

@paulvanbrenk could we get this issue closed? There's multiple issues in this thread that are likely resolved. If users are still having issues with the latest `@types/jquery` published, they're probably better off opening a new issue focused on their problem.

**Comment by kktam** [comment]
I got it working by pairing "typescript": "~2.3.4" with "@types/jquery": "3.2.5"

**Comment by EloyRoura** [comment]
I am quite new in angular2 but I am experiencing the same problems above mentioned:

ERROR in /Users/eroura/SourceCode/tests/my-app/node_modules/@types/jquery/index.d.ts (41,40): ',' expected.
... and a long queue of the same type of errors....

I am using:
$ tsc --version
Version 2.4.1

and installing jquery and @types/jquery as follows:
$npm install jquery --save
$npm install @types/jquery --save

The project is nothing but the default created by:
$ng new my-app

So there is nothing else that is currently using it, but it would not compile anyway. And yes, if you wonder I would eventually use jQuery.

Any help on that please?

**Comment by paulvanbrenk** [comment]
@leonard-thieu I agree closing this issue.

@EloyRoura please create a new issue, or better yet open a question on StackOverflow. This repo is dedicated to the type-definitions and not a great place for general TypeScript questions.

**Comment by thomicdk** [comment]
@mikehaas763 You wrote above that you were wondering if there was an official way of defining the `Iterable` interface for libs that depends on the environment. Did you ever find any other way?

I think the solution proposed by @leonard-thieu is a bit problematic, because when adding the `es2015.iterable` lib gives you much more than just the `Iterable` interface (See https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2015.iterable.d.ts). E.g it extends `Array` with methods like `entries()`, `keys()` and `values()` which are not available if you target `ES5` like many of us do.

**Comment by preist** [comment]
I kept getting a `Cannot find name 'Iterable'` error.
To fix this I did:

```bash
npm i @types/node --save-dev`
```

The node typing contains the `Iterable` definition for `--lib es5` it seems.

**node_modules/types/node/index.d.ts**
```javascript
interface Iterable<T> { }
interface Iterator<T> {
    next(value?: any): IteratorResult<T>;
}
```

**Comment by equinoxmatt** [comment]
Thanks @preist  - your solution seemed to work for me. I didn't have the node typings.

**Comment by rvacchi** [comment]
i am having this problem can anyone help please...
