### ISSUE TITLE
@types/jquery suddently having typings error.

### ISSUE THREAD

**Issue by JudeAlquiza** [DefinitelyTyped/DefinitelyTyped#17237]
Hi,

   Just want to mention that when I tried to download the latest typings for jquery, I suddenly got a lot of typings error.

   I tried to using my old typings for jquery by just copying it inside of @types/jquery and its working.

   I checked @types/jquery and it seems that it just been updated a couple of hours ago.

   Can this be the cause of this?

  PS. I tried to paste some files here but even if its .zip for some reason it won't accept it.

Thanks!
Jude Alquiza.

**Comment by redwyre** [comment]
I had this problem with angular pulling in the new jquery typings, I've worked around it by adding "@types/jquery": "2.0.46",
to my package.json dependencies

**Comment by JudeAlquiza** [comment]
@redwyre thanks, did what you suggested and it worked! :)

**Comment by mdentinho** [comment]
For reference, the problem is that the `@types/angular`'s package.json has its dependency on `@types/jquery` set to `*`.
