### ISSUE TITLE
@types/express-serve-static-core error TS2430: Interface 'Request' incorrectly extends interface 'IncomingMessage'.

### ISSUE THREAD

**Issue by sureshgururajan** [DefinitelyTyped/DefinitelyTyped#17232]
- [x] Package: [`@types/express-serve-static-core`](https://www.npmjs.com/package/@types/express-serve-static-core)
- [x] I tried using the latest stable version of [tsc (2.3.4)](https://www.npmjs.com/package/typescript)
- [x] I have a question that is inappropriate for StackOverflow.
- [x] Authors: @borisyankov ([Boris Yankov](https://github.com/borisyankov/)), [Michał Lytek](https://github.com/19majkel94), @kacepe ([Kacper Polak](https://github.com/kacepe))
---
### Issue

When I execute the command **tsc**, I get the following error:

```
node_modules/@types/express-serve-static-core/index.d.ts(177,11): error TS2430: Interface 'Request' incorrectly extends interface 'IncomingMessage'.
  Types of property 'headers' are incompatible.
    Type '{ [key: string]: string | undefined; }' is not assignable to type '{ [key: string]: string | string[]; }'.
      Index signatures are incompatible.
        Type 'string | undefined' is not assignable to type 'string | string[]'.
          Type 'undefined' is not assignable to type 'string | string[]'.
```

The last time there were no such issues was 20 days ago, when the command **tsc** ran successfully.

Here is a snippet of my package.json file:
```javascript
{
"devDependencies": {
    "@types/body-parser": "^1.16.3",
    "@types/chai": "^3.5.2",
    "@types/express": "^4.0.36",
    "@types/mocha": "^2.2.41",
    "chai": "^3.5.0",
    "concurrently": "^3.4.0",
    "mocha": "^3.4.1",
    "nodemon": "^1.11.0",
    "tslint": "^5.2.0",
    "typescript": "^2.3.2"
  },
"dependencies": {
    "@types/body-parser": "^1.16.3",
    "@types/node": "^7.0.31",
    "body-parser": "^1.17.2",
    "express": "^4.15.3"
  }
}
```

**Comment by sompylasar** [comment]
Happened somewhere between these versions:
### Fails
```
├── @types/body-parser@1.16.3
├── @types/chai@3.5.2
├── @types/commander@2.3.31
├── @types/debug@0.0.29
├─┬ @types/express@4.0.36
│ ├── @types/express-serve-static-core@4.0.47
│ └─┬ @types/serve-static@1.7.31
│   └── @types/mime@1.3.0
├── @types/faker@4.1.0
├── @types/lodash@4.14.66
├── @types/mocha@2.2.41
├── @types/node@7.0.31
├─┬ @types/request@0.0.42
│ └── @types/form-data@0.0.33
├── @types/sinon@2.3.1
```
### Works
```
├── @types/body-parser@1.16.3 
├── @types/chai@3.5.2 
├── @types/commander@2.3.31 
├── @types/debug@0.0.29 
├─┬ @types/express@4.0.35 
│ ├── @types/express-serve-static-core@4.0.47 
│ └─┬ @types/serve-static@1.7.31 
│   └── @types/mime@1.3.0 
├── @types/faker@4.1.0 
├── @types/lodash@4.14.66 
├── @types/mocha@2.2.41 
├── @types/node@7.0.28 
├─┬ @types/request@0.0.42 
│ └── @types/form-data@0.0.33 
└── @types/sinon@2.3.1 
```

Likely `@types/node@7.0.28` -> `@types/node@7.0.31`

**Comment by sompylasar** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/c9e01b3e760ee7e2f93a7c9052d432f6713347c8#diff-7d84e08967cded0b99ed4328aab0a1a8R811

**Comment by sureshgururajan** [comment]
Awesome! Works now! Thank you so much for the fix! 

Cheers,
Suresh Gururajan

**Comment by sompylasar** [comment]
Could anyone please link to the fixing commit? @sureshgururajan

**Comment by sompylasar** [comment]
Found it:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17229
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b9afd83a914c851736565a5f858cff24a486b69a

**Comment by sureshgururajan** [comment]
@sompylasar - Thank you for referencing it.
