### ISSUE TITLE
Typescript 2.4.0 and @types/angular are incompatible due to "Weak Types"

### ISSUE THREAD

**Issue by azrazalea** [DefinitelyTyped/DefinitelyTyped#17257]
See https://blogs.msdn.microsoft.com/typescript/2017/06/12/announcing-typescript-2-4-rc/ under section "Weak Types" for context. I searched issues but not seeing it yet. Looks like per https://github.com/DefinitelyTyped/DefinitelyTyped/commit/1c3565933cc792ebb642477d5eed174d6d2ccd9a you are already aware of the issue though.

Basically many things in the angular types are "Weak Types" and therefore have stopped working if you don't share properties. Specifically `IController` and `IControllerConstructor` are issues with us currently since many of our controllers don't need any of those event callbacks.

This means many(most?) angular apps won't compile with these types and typescript 2.4.0

**Comment by azrazalea** [comment]
I think their solution `Add an index signature to the weak type (i.e. [propName: string]: {}).` is the correct one (though maybe `: any`) in `IController`'s case at least.

**Comment by andy-ms** [comment]
See #17255

**Comment by azrazalea** [comment]
@andy-ms Unless i'm missing something, the only commonality between that PR and this issue is that they both are angular. It's working on promises and doesn't appear to touch any weak types.
