### ISSUE TITLE
@type/jquery 3.2.1

### ISSUE THREAD

**Issue by infofromca** [DefinitelyTyped/DefinitelyTyped#17261]
- [ x] I tried using the `@types/jquery` 3.2.1 
[logs_13961.zip](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1081840/logs_13961.zip)
or   `@types/node`  6.0.38 package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

**Comment by andy-ms** [comment]
I can't tell what problem you're having from that description.

**Comment by infofromca** [comment]
see the .zip file pls

**Comment by andy-ms** [comment]
You'll need to get a more easily reproducible example of your problem.
