### ISSUE TITLE
The mostRecentCall parameter does not exist in Jasmine versions > 2.0

### ISSUE THREAD

**Issue by guoliang** [DefinitelyTyped/DefinitelyTyped#17285]
- [x] I tried using the `@types/2.5.41` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

I think it will just alright if you remove `mostRecentCall` from index.d.ts

**Comment by andy-ms** [comment]
PRs accepted.

**Comment by zvirja** [comment]
@guoliang Could you please check whether it's still relevant? Seems to be fixed in latest v3 ✔️

**Comment by guoliang** [comment]
I suppose it is resolved now then ;)
