### ISSUE TITLE
@types/jquery 3.2.2

### ISSUE THREAD

**Issue by akehir** [DefinitelyTyped/DefinitelyTyped#17298]
- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu @johnnyreilly 

Hi, I upgraded to @types/jquery@3.2.2 after issues with @3.2.1 (described in pull #17276 ). Now I get the following error, when doing $window = jQuery(window):
`TS2322: Type 'JQueryStatic<HTMLElement>' is not assignable to type 'JQuery<HTMLElement>'.
  Property 'jquery' is missing in type 'JQueryStatic<HTMLElement>'.`

If I define the variable as JQueryStatic, I get more errors:
`error TS2339: Property 'on' does not exist on type 'JQueryStatic<HTMLElement>'`

I include jquery as follows:
`import * as jQuery from 'jquery'; ("allowSyntheticDefaultImports": true)`

I'm trying to listen to the window scroll state, ie:
`header.$window.on('scroll', debounce(header.updateScrollState, 16));`

Either we should be able to convert JQueryStatic to JQuery, or have the proper types available on the JQueryStatic?

**Comment by leonard-thieu** [comment]
This should be fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17301. Thank you for reporting this.

**Comment by akehir** [comment]
Great, that was blazing fast! Thanks a lot.
