### ISSUE TITLE
react-native View / Text / ScrollView lost the ability to use arrays in style prop

### ISSUE THREAD

**Issue by pocesar** [DefinitelyTyped/DefinitelyTyped#17308]
- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

Can't assign an array to style (and it's permitted by the docs in https://facebook.github.io/react-native/docs/style.html)

![image](https://user-images.githubusercontent.com/461084/27310398-5ca163e4-5530-11e7-82ed-19fb941b1599.png)

Don't know when the change took place. The index.d.ts now shows

![image](https://user-images.githubusercontent.com/461084/27310408-7f36eec4-5530-11e7-92d2-46ae5fcd24c7.png)

Should be either `ViewStyle | ViewStyle[];` or have a helper type generic (since it's common to a lot of components that use styles, like TextStyle, FlexStyle, etc)

**Comment by kohkimakimoto** [comment]
I have a same issue. Now I use a workaround `as any` like the following:

```
<View style={[styles.bigblue, styles.red] as any}></View>
```
