### ISSUE TITLE
How to solve Error parsing header

### ISSUE THREAD

**Issue by buptyyf** [DefinitelyTyped/DefinitelyTyped#17315]
I want to add a new type/react-list.

When I run 'npm run lint react-list', there is an error 'dt-header  Error parsing header. Expected: foo MAJOR.MINOR (patch version not allowed)'

And my index.d.ts header is as follows:

// Type definitions for react-list 0.8.3
// Project: https://github.com/orgsync/react-list
// Definitions by: Yifei Yan <https://github.com/buptyyf>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.3

**Comment by andy-ms** [comment]
Don't include the patch version. Use `0.8` instead of `0.3`.

**Comment by buptyyf** [comment]
Thank you very much. I have fixed it. @andy-ms
