### ISSUE TITLE
[@types/react-navigation] Navigation Container Props don't have style

### ISSUE THREAD

**Issue by AleksandarDev** [DefinitelyTyped/DefinitelyTyped#17319]
- [X] I tried using the `@types/react-navigation` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript 
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Huhuanming @mhcgrq @fangpenlin 

## Usage:
```jsx
const Navigator = StackNavigator({
    ...
});

<Navigator 
    style={{ 
        width: Dimensions.get("window").width, 
        marginTop: Expo.Constants.statusBarHeight }} />
```

## Error:
```
file: '.../src/App.tsx'
severity: 'Error'
message: 'Property 'style' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<NavigationContainerProps, ComponentState...'.'
at: '76,20'
source: 'ts'
```

## Workaround:

Changed `index.d.ts` from

```ts
interface NavigationContainerProps {
  screenProps?: any
  navigation?: NavigationProp<any, NavigationAction>
  onNavigationStateChange?: (
    preNavigationState: NavigationState,
    nextNavigationState: NavigationState,
  ) => void
}
```

to

```ts
interface NavigationContainerProps {
  screenProps?: any
  navigation?: NavigationProp<any, NavigationAction>
  onNavigationStateChange?: (
    preNavigationState: NavigationState,
    nextNavigationState: NavigationState,
  ) => void,
  style?: ViewStyle
}
```

**Comment by huhuanming** [comment]
cool

**Comment by huhuanming** [comment]
Cool

**Comment by huhuanming** [comment]
😳

**Comment by AleksandarDev** [comment]
@huhuanming It was merged. Thanks

**Comment by jose920405** [comment]
😮  i'm using `this.props.navigation.navigate` and this structure only give me `dispatch` and `state` option
