### ISSUE TITLE
[hapi] Property 'xxx' does not exist on type 'Object when access request.query

### ISSUE THREAD

**Issue by mailto1587** [DefinitelyTyped/DefinitelyTyped#17312]
- [x ] I tried using the `@types/xxxx` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- x[ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jasonswearingen @AJamesPhillips 

I found that the latest tsd of hapi declared the `query` property of class `Request` as type `Object`, instead of type `any`. Then I met the problem to access any properties on `request.query` instance within handler function, even though I configured the right validator.

Why not use type `any` of that? Or if there is a best practice to access `request.query`, please tell me, thank you so much!

**Comment by AJamesPhillips** [comment]
Thanks for raising this issue.  In terms of typing, this should have stayed as `any` though if you're type asserting then it will work fine regardless.  Unfortunately the return type from the `query_validation.validate().value` is just the type of the object passed to it which is not available at compile time (for obvious reasons! :P ).

My code looks something like:

        validate: { query: query_validation },  // where query_validation is a Joi instance
        handler: function (request, reply) {

            const query = request.query as RequestQuery.GetThing;

But a type of `any` would be easier for beginners / building a fast prototype.  If you'd like to prepare a PR that'd be great.

**Comment by mailto1587** [comment]
Yes, it's my first time to use joi indeed. Thank you for sharing your code, it helps me. And I've send a  PR which replaced type of Object with type of any.
