### ISSUE TITLE
@types/bootstrap-slider should depend on @types/jquery@^2.0.47

### ISSUE THREAD

**Issue by ViceIce** [DefinitelyTyped/DefinitelyTyped#17316]
- [x] I tried using the `@types/bootstrap-slider` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dbeckwith 

The types @types/bootstrap-slider should have a dependency to @types/jquery@^2.0.47 because it is incompatible with version 3.x.y.

**Comment by leonard-thieu** [comment]
Could you elaborate on why it's incompatible?

**Comment by ViceIce** [comment]
The [JQuery interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jquery/index.d.ts#L41) is generic in version 3

**Comment by leonard-thieu** [comment]
Looks like it is missing its `@types/jquery` dependency declaration. I've put in a PR to fix that and updated it to work with `@types/jquery@3`.
