### ISSUE TITLE
[@types/chai-as-promised] missing 'be.frozen' test among others

### ISSUE THREAD

**Issue by mattbishop** [DefinitelyTyped/DefinitelyTyped#17329]
- [ X ] I tried using the `@types/xxxx` package and had problems.
- [ X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ X ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu

I want to use chai-as-promised to test for a promised value to eventually be in a frozen state a la http://chaijs.com/api/bdd/#method_frozen like this:

`expect(thePromisedThing).to.eventually.be.frozen;`

Missing language chain methods from this @types definition (see http://chaijs.com/api/bdd/#method_language-chains):

- nested
- own (has `ownProperty` which isn't quite right)
- ordered
- any
- NaN
- ownPropertyDescriptor (misnamed as 'ownProperty')
- oneOf
- change
- increase
- decrease
- by
- extensible
- sealed
- frozen
- finite

**Comment by leonard-thieu** [comment]
@jt000 @Kuniwak I'm not as familiar with the structure of `@types/chai` and `@types/chai-as-promised`. Maybe one of you guys would want to take a look at it?

**Comment by CatGuardian** [comment]
The .own chain is missing on both Chai and chai-as-promised

Here is a snippet from the Chai docs:

expect({a: 1}).to.have.own.property('a');

.own is not recognized.

URL to docs: http://chaijs.com/api/bdd/#method_own

**Comment by danthegoodman** [comment]
It looks like it can be closed now that PR #19351 has been merged in.
