### ISSUE TITLE
[@types/sequelize] issues with promises

### ISSUE THREAD

**Issue by Torhal** [DefinitelyTyped/DefinitelyTyped#17345]
- [x] I tried using the `@types/sequelize` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sandersn 

PR #17245 removed the line ```/// <reference types="bluebird" />```  in both types/sequelize/index.d.ts and types/sequelize/v3/index.d.ts which seems to have broken some distinctly Bluebird-centric methods such as [spread](http://bluebirdjs.com/docs/api/spread.html). Code that previously existed without issue now gives the error ```[ts] Property 'spread' does not exist on type 'Promise<[myType, boolean]>'.```

**Comment by sandersn** [comment]
Adding @lhecker and @andy-ms

**Comment by Torhal** [comment]
Addendum: If I add ```import * as Promise from "bluebird";``` to the Sequelize index.d.ts, under the /// reference entries, the TypeScript error in my code goes away.

**Comment by andy-ms** [comment]
Wait, it looks like the [latest](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sequelize/index.d.ts) already has `import * as Promise from "bluebird";`. #17245 just removes a redundant `/// <reference types="bluebird" />` but leaves the import alone.

**Comment by Torhal** [comment]
Just did so - #17362. Appreciate the input!
