### ISSUE TITLE
@types/hapi

### ISSUE THREAD

**Issue by wesselvdv** [DefinitelyTyped/DefinitelyTyped#17342]
[x] I tried using the @types/hapi package and had problems.
[x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
[x] I have a question that is inappropriate for StackOverflow. (Please ask any appropriate questions there).
[x] Mention the authors (see Definitions by: in index.d.ts) so they can respond.
Authors: @jasonswearingen @AJamesPhillips

I am having some issues with declaration merging to get type checking on my specific contents of credentials. (request.auth.credentials)

I can see that there's a specific interface (AuthenticatedCredentials) for the contents of this, but it's not used on all of the interfaces where credentials occur. On the interface RequestAuthenticationInformation credentials has a type of any, instead of RequestAuthenticationInformation. This is prohibiting me of using declaration merging on it, because I can't change the type of an existing property.

Current:

```typescript
export interface RequestAuthenticationInformation {
    /** true if the request has been successfully authenticated, otherwise false. */
    isAuthenticated: boolean;
    /** the credential object received during the authentication process. The presence of an object does not mean successful authentication. */
    credentials: any;
    /** an artifact object received from the authentication strategy and used in authentication-related actions. */
    artifacts: any;
    /** the route authentication mode. */
    mode: string;
    /** the authentication error is failed and mode set to 'try'. */
    error: Error;
}
```

Proposed solution:

```typescript
export interface RequestAuthenticationInformation {
    /** true if the request has been successfully authenticated, otherwise false. */
    isAuthenticated: boolean;
    /** the credential object received during the authentication process. The presence of an object does not mean successful authentication. */
    credentials: AuthenticatedCredentials; // <=== Changed to AuthenticatedCredentials, so I can merge the declaration with my own implementation of it.
    /** an artifact object received from the authentication strategy and used in authentication-related actions. */
    artifacts: any;
    /** the route authentication mode. */
    mode: string;
    /** the authentication error is failed and mode set to 'try'. */
    error: Error;
}
```

**Comment by AJamesPhillips** [comment]
LGTM.  Thanks for taking time to raise this issue.

**Comment by wesselvdv** [comment]
@AJamesPhillips 

Thanks for the quick response!

Isn't it the case that a empty interface acts as any? I believe that I've read that somewhere.

**Comment by AJamesPhillips** [comment]
Yeah assignment is fine, access will produce type errors.

**Comment by AJamesPhillips** [comment]
@wesselvdv just checking, you going to submit this as a PR?  (With a simple test as well if you could).
