### ISSUE TITLE
[@types/react-router] Type restriction for RouteProps.component creates error

### ISSUE THREAD

**Issue by stefan-schweiger** [DefinitelyTyped/DefinitelyTyped#17355]
- [x] I tried using the `@types/react-router` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sergey-buturlakin @mrk21 @vasek17 @ngbrown @awendland @KostyaEsmukov @johnnyreilly @LKay @DovydasNavickas @tkrotoff @huy-nguyen @grmiade  @DaIgeb 

I'm using react-dom-router (which internally uses react-router) to define some routes, but as soon as I include the d.ts file and run tsc I get the following error:

```
ClientApp/routes.tsx(9,12): error TS2322: Type '{ exact: true; path: "/"; component: typeof Home; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Route> & Readonly<{ children?: ReactNode; }> & Rea...'.
  Type '{ exact: true; path: "/"; component: typeof Home; }' is not assignable to type 'Readonly<RouteProps>'.
    Types of property 'component' are incompatible.
      Type 'typeof Home' is not assignable to type 'StatelessComponent<RouteComponentProps<any>> | ComponentClass<RouteComponentProps<any>>'.
        Type 'typeof Home' is not assignable to type 'ComponentClass<RouteComponentProps<any>>'.
          Type 'Home' is not assignable to type 'Component<RouteComponentProps<any>, ComponentState>'.
            Types of property 'props' are incompatible.
              Type 'Readonly<{ children?: ReactNode; }> & Readonly<{}>' is not assignable to type 'Readonly<{ children?: ReactNode; }> & Readonly<RouteComponentProps<any>>'.
                Type 'Readonly<{ children?: ReactNode; }> & Readonly<{}>' is not assignable to type 'Readonly<RouteComponentProps<any>>'.
                  Property 'match' is missing in type 'Readonly<{ children?: ReactNode; }> & Readonly<{}>'.
```

I've narrowed it down to the following line in v3/index.d.ts:67

```ts
component?: React.SFC<RouteComponentProps<any> | undefined> | React.ComponentClass<RouteComponentProps<any> | undefined>;
```

**EDIT:** At first I thought the order was the problem but turns out I put in a typo in my fix.

```ts
component?: React.ComponentClass<RouteComponentProps<any> | undefined | React.SFC<RouteComponentProps<any> | undefined>>;
```

Notice that React.SFC is inside the brackets of React.ComponentClass. I don't know why this fixes my problem, but I'm pretty sure that this is not a valid solution.
**EDIT END**

~~When you change the order of `React.SFC` and `React.ComponentClass` everything works fine for me.~~ But since I'm pretty new to TypeScript and React I don't know if there are any possible side effects in doing so. I really hope someone of the authers can give me some insight. If there are no problems with changing this line I would be happy to create a PR.

**My Code:**
route.tsx
```ts
import * as React from 'react';
import { Route } from 'react-router-dom';
import { Layout } from './components/Layout';
import { Home } from './components/Home';

export const routes = <Layout>
    <Route exact path='/' component={ Home } />
</Layout>;
```

app.tsx
```ts
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import * as RoutesModule from './routes';
let routes = RoutesModule.routes;

function renderApp() {
    ReactDOM.render(
        <AppContainer>
            <BrowserRouter children={ routes } />
        </AppContainer>,
        document.getElementById('react-app')
    );
}

renderApp();
```

Home.tsx
```ts
import * as React from 'react';

export class Home extends React.Component<{}, {}> {
    public render() {
        return <div>
        </div>;
    }
}
```

**Comment by DovydasNavickas** [comment]
Judging by the errors, you most probably have types included at least *twice* by the compiler.
Usually, the easiest solution is adding `typeRoots` property into your `typescript.json` for `compilerOptions`, like so:
```json
{
    "compilerOptions": {
        <...>
        "typeRoots": [
            "node_modules/@types"
        ],
        <...>
    }
}
```

Try it out, this saved my sanity a few days ago, when I saw colleague specifying `typeRoots` to solve his problems (kudos to @MartynasZilinskas) :)

**Comment by stefan-schweiger** [comment]
@DovydasNavickas thank you for your answer, I've tried your advice but it didn't seem to fix my problem :/

I've now condensed my problem to the smallest "project" I could come up with:

app.tsx
```tsx
import * as React from 'react';
import { Route } from 'react-router-dom';

class Home extends React.Component<{}, {}> {
    public render() { return <div></div>; }
}

export const routes = <Route exact path='/' component={ Home } />
```

package.json
```json
{
  "name": "typingstest",
  "version": "1.0.0",
  "devDependencies": {
    "@types/react": "15.0.24",
    "@types/react-dom": "15.5.0",
    "@types/react-router": "4.0.9",
    "@types/react-router-dom": "^4.0.4",
    "react": "15.5.4",
    "react-dom": "15.5.4",
    "react-router-dom": "4.1.1",
    "typescript": "2.3.2"
  }
}
```
tsconfig.json
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "moduleResolution": "node",
    "target": "es5",
    "jsx": "react",
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "exclude": [ "node_modules" ]
}
```

After I run `npm install` and `tsc` I still get the same error. I've also tried setting `types` and `typeRoots` to everything that came to my mind, but with no  success.

**Comment by Kovensky** [comment]
The component is required to be able to receive `RouteComponentProps`. Change your `extends React.Component<{}, {}>` clause to `extends React.Component<{} & RouteComponentProps<any>, null>`

Since the left side of `&` is a `{}` you can just omit that and only put `RouteComponentProps` there, but that is how you would combine multiple props coming from other higher order components (e.g. react-redux's compose).

**Comment by janpieterz** [comment]
Looking at the definition:
```
export interface RouteComponentProps<P> {
  match: match<P>;
  location: H.Location;
  history: H.History;
  staticContext?: any;
}
```

Shouldn't that be the following?
```
export interface RouteComponentProps<P> {
  match?: match<P>;
  location?: H.Location;
  history?: H.History;
  staticContext?: any;
}
```

**Comment by Kovensky** [comment]
No, because then you'd force components to do undefined checks on every key, but they will not be undefined if you correctly use them with the router.

That also might get caught in the new excess property check for weak types (interfaces where all keys are optional) in 2.4.

**Comment by thesircle** [comment]
@Kovensky Your solution worked for me too. However in context to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17355#issuecomment-310544041 is there a proper solution where we don't have to pass `& RouteComponentProps<{}>` every time?

**Comment by fmavdb** [comment]
I'm also experiencing this issue. Even when including the Route like this:
```
<Switch>
 <Route />
</Switch>
```

Gives the IntrensicAttributes type error.

**Comment by leodsgn** [comment]
I'm having this same issue with:

```
export default withRouter(connect(mapStateToProps)(Header));
```

In my case, I already tried to put `React.Component<HeaderProps & RouteComponentProps<{}>, {}>` but it didn't work.

**Comment by vcardins** [comment]
I got it working by doing this:
```
import` { withRouter, RouteProps } from 'react-router';
...
class Layout extends React.Component<Props & RouteProps, State> 
...
```

**Comment by leodsgn** [comment]
I'll try that. Thanks @vcardins.

**Comment by chrispaynter** [comment]
@vcardins thank you so much. I've been pulling my hair out trying to use the approaches taken with `RouteComponentProps` from [this thread](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17181#issuecomment-316774907). Cheers!

**Comment by thangchung** [comment]
@vcardins Thank you. You save my day 👍

**Comment by IljaDaderko** [comment]
Above didn't work for me, if anyone is interested this does, gives you all types for `history`, `location`, `match`

```
class SignInPage extends React.Component<RouteComponentProps<any>>
```

**Comment by sean-killeen** [comment]
I have managed to solve this by casting as `any` when I am doing the withRouter export.  I know this isn't ideal but it has got me out of a hole.
```
import { withRouter, RouteProps } from "react-router-dom";

...

export class ExampleContainer extends React.Component<ExampleComponentProps & RouteProps, undefined> {

...

export default withRouter(connect(mapStateToProps, mapDispatchToProps)(ExampleContainer) as React.ComponentType<any>);


```

**Comment by Tjorriemorrie** [comment]
@Kovensky that gives (16,45): Types of property 'component' are incompatible.

**Comment by Nopzen** [comment]
Tried @vcardins trick, didn't help me either i solved it byt casting any like so:

```js
const Navigation: React.SFC<NavigationProps & any> = () => {
   ....
}

export default withRouter(Navigation);
```

My case is i have a button inside my navigation that cant use the `<NavLink />` component so need to push to history manually, if there is a better way than `withRouter()` hoc i would like to learn

```
"@types/react-router": "^4.0.30",
"react-router": "^4.3.1",
```

**Comment by npeham** [comment]
I don't get this at all..

I just investigated in this issue and I noticed that when I add the `@types/react-router-dom` dependency beside of the `@types/react-router` dependency I got following error:

```
[ts]
Argument of type 'typeof MyComponent' is not assignable to parameter of type 'ComponentType<MyComponentProps>'.
  Type 'typeof MyComponent' is not assignable to type 'StatelessComponent<MyComponentProps>'.
    Types of property 'propTypes' are incompatible.
      Type '{ prop1: Requireable<any[]>; prop2: Requireable<string>; location: Requireable<object>; prop3: Requireable<number>; history: Requireable<object>; }' is not assignable to type 'ValidationMap<MyComponentProps>'.
        Property 'match' is missing in type '{ prop1: Requireable<any[]>; prop2: Requireable<string>; location: Requireable<object>; prop3: Requireable<number>; history: Requireable<object>; }'.
```

Whether I import the `RouteComponentProps` from `react-router` or `react-router-dom`. I mean this is absolutely clear because as @stefan-schweiger mentioned `react-router-dom` internally uses `react-router` as you can see: 
```
export {
    generatePath,
    Prompt,
    MemoryRouter,
    RedirectProps,
    Redirect,
    RouteComponentProps,
    RouteProps,
    Route,
    Router,
    StaticRouter,
    Switch,
    match,
    matchPath,
    withRouter,
    RouterChildContext
} from 'react-router';
```

But now it comes the confusing part. I just import the `RouteComponentProps` from `react-router` and it gives me the error which I posted above. But if I just remove the `@types/react-router-dom` dependency the error disappears and all works correctly. I really don't understand why these two typings make problems when they are used together. Can anyone explain?

Btw this is the interface for my component:
```
export interface MyComponentProps extends RouteComponentProps<{}> {
    prop1: []
    prop2: string
    prop3?: number
}
```

**Comment by npeham** [comment]
Ok I found the problem. I had a static PropTypes getter defined in my component class. If you change the return type for this getter to `any` or just remove the PropTypes at all, all works just fine!
But its still a little bit confusing why this error appears if I just add the `@types/react-router-dom` dependency.

**Comment by npeham** [comment]
> I don't get this at all..
> 
> I just investigated in this issue and I noticed that when I add the `@types/react-router-dom` dependency beside of the `@types/react-router` dependency I got following error:
> 
> ```
> [ts]
> Argument of type 'typeof MyComponent' is not assignable to parameter of type 'ComponentType<MyComponentProps>'.
>   Type 'typeof MyComponent' is not assignable to type 'StatelessComponent<MyComponentProps>'.
>     Types of property 'propTypes' are incompatible.
>       Type '{ prop1: Requireable<any[]>; prop2: Requireable<string>; location: Requireable<object>; prop3: Requireable<number>; history: Requireable<object>; }' is not assignable to type 'ValidationMap<MyComponentProps>'.
>         Property 'match' is missing in type '{ prop1: Requireable<any[]>; prop2: Requireable<string>; location: Requireable<object>; prop3: Requireable<number>; history: Requireable<object>; }'.
> ```
> Whether I import the `RouteComponentProps` from `react-router` or `react-router-dom`. I mean this is absolutely clear because as @stefan-schweiger mentioned `react-router-dom` internally uses `react-router` as you can see:
> 
> ```
> export {
>     generatePath,
>     Prompt,
>     MemoryRouter,
>     RedirectProps,
>     Redirect,
>     RouteComponentProps,
>     RouteProps,
>     Route,
>     Router,
>     StaticRouter,
>     Switch,
>     match,
>     matchPath,
>     withRouter,
>     RouterChildContext
> } from 'react-router';
> ```
> But now it comes the confusing part. I just import the `RouteComponentProps` from `react-router` and it gives me the error which I posted above. But if I just remove the `@types/react-router-dom` dependency the error disappears and all works correctly. I really don't understand why these two typings make problems when they are used together. Can anyone explain?
> 
> Btw this is the interface for my component:
> 
> ```
> export interface MyComponentProps extends RouteComponentProps<{}> {
>     prop1: []
>     prop2: string
>     prop3?: number
> }
> ```

Ok I found the problem. I had a static PropTypes getter defined in my component class. If you change the return type for this getter to `any` or just remove the PropTypes at all, all works just fine!
But its still a little bit confusing why this error appears if I just add the `@types/react-router-dom` dependency.

**Comment by ushang-thakker** [comment]
I can't believe its more than a year and nobody has solved this ! I am having a similar issue.  If I use
```
class MyComponent extends React.Component<Props & RouteProps, State> // Pay attention here.
{
  // your code...
}
```
In my container I get the following
```
Property 'history' is missing in type '{ isLoaded: boolean; entries: IActivitiesDetail; fetch: ISimpleActionDispatcherAsProp; }'.
```

**Comment by rebornwwp** [comment]
I hava a stupid solution. so stupid
```  typescript
// App.tsx 
<Route path="/hello/:id" component={Hello} />

// Hello.tsx

import * as React from "react";

// this interface is so stupid, but it can solve this problem.
export interface Props {
  match: {
    params: {
      id: string
    }
  }
}

interface State {
  id: string;
}

class Hello extends React.Component<Props, State> {
  state: State;

  constructor(props: Props) {
    super(props);
    console.log(props);
    const { id } = props.match.params;
    this.state = {
      id: id
    };
  }

  render() {
    const { id } = this.state;
    console.log(this.state);
    return (
      <div className="main">
        <div className="content">{id}</div>
      </div>
    );
  }
}

export default Hello;
```
always define your interface by yourself.  when you find better solutions, change this stupid codes.

**Comment by TeemuKoivisto** [comment]
Hmm I got this error just recently as I was bootstrapping new project. It seems that beforehand as I had wrapped my page-components with mobx it prevented the error but now as I have a page-component directly as a parameter to the `component`-prop as such: `<WrappedRoute exact path="/" component={FrontPage}/>` it does not work.

Really peculiar bug and I can't come up with any quick solution, probably I'll just add mobx and be done with it. Can't say I ever had good experience using react-router. One of the better reasons to use Vue but well that's another topic entirely.

**Comment by SimpleCookie** [comment]
I needed this part ` as React.ComponentType<any>)`
so that my code became like this
`  export default withRouter(connect(
      mapStateToProps,
      {}
  )(Routes) as React.ComponentType<any>)`

Not sure why.

**Comment by zebogen** [comment]
I had this problem with a route component. My solution was to import `match` and define my interface as follows:
```js
interface MyProps extends RouteComponentProps {
  match: match<{ myParam: string }>;
}
```
I'm new to Typescript. Not sure if this is a good solution, but it compiles.

**Comment by remojansen** [comment]
I installed `react-router`, `react-router-dom`, `@types/react-router` and `@types/react-router-dom` after bootstraping a project with `react-create-app`. The following works for me:

## index.tsx 

```ts
import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
import Layout from "./pages/layout";
import * as serviceWorker from "./serviceWorker";

ReactDOM.render(<Layout />, document.getElementById("root"));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: http://bit.ly/CRA-PWA
serviceWorker.unregister();
```

## layout.tsx

```ts
import React from "react";
import { Switch, Route, Router } from "react-router";
import { BrowserRouter } from "react-router-dom";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import Home from "./home";
import Talks from "./talks";
import Schedule from "./schedule";
import Tickets from "./tickets";
import Venue from "./venue";
import Sponsors from "./sponsors";
import CoC from "./coc";

class Layout extends React.Component {
    public render() {
        return (
            <div>
                <Navbar/>
                <div className="container content">
                    <BrowserRouter>
                        <Switch>
                            <Route path="/home" component={Home} />
                            <Route path="/talks" component={Talks} />
                            <Route path="/schedule" component={Schedule} />
                            <Route path="/tickets" component={Tickets} />
                            <Route path="/venue" component={Venue} />
                            <Route path="/sponsor" component={Sponsors} />
                            <Route path="/coc" component={CoC} />
                        </Switch>
                    </BrowserRouter>
                </div>
                <Footer/>
            </div>
        );
    }
}

export default Layout;
```

**Comment by nebaz** [comment]
import {RouteComponentProps, withRouter} from 'react-router';

export default withRouter(connect<{}, {}, IProps & RouteComponentProps>(mapStateToProps)(MyComponent));

**Comment by dezman** [comment]
This should work:

```
import { RouteComponentProps } from 'react-router-dom';

type MyProps = RouteComponentProps<{ id?: string }>

const CoolThing: React.FC<MyProps> = ({ match }) => {
  const id = match.params.id;

  return (
    <div>Hopefully that helps!</div>
  );
}
```

export default CoolThing;

**Comment by Shyghar** [comment]
> I have managed to solve this by casting as `any` when I am doing the withRouter export. I know this isn't ideal but it has got me out of a hole.
> 
> ```
> import { withRouter, RouteProps } from "react-router-dom";
> 
> ...
> 
> export class ExampleContainer extends React.Component<ExampleComponentProps & RouteProps, undefined> {
> 
> ...
> 
> export default withRouter(connect(mapStateToProps, mapDispatchToProps)(ExampleContainer) as React.ComponentType<any>);
> ```

This worked for me!! Thank you!

**Comment by lillorme** [comment]
Guys, I have tried everything on this page and it did not work for me. TypeScript is expecting a certain props  and is not getting it. The HOCs seems to not returning it correctly or maybe not at all.
What I did that works for me is, I created a component just for "Route" and called it "RouteContainer".

```
import React from 'react';
import {Route} from 'react-router-dom';

const RouteContainer = (props:any) => {
    const {...otherProps} = props
    return(
        <Route {...otherProps} />
    )
}

export default RouteContainer;
```
Then I imported it in the original component .

```
import RouteContainer from '../../Component/RouteContainer/RouteContainer';

          <RouteContainer 
            exact 
            path={`${match.path}`} 
            component={CollectionOverviewContainer}
          />
```
In doing this, it preserved the integrity of the <Route /> container thus protects it from the HOCs. Doing it this way made sure the <Route /> container get the right props all the time. I'm not sure if this is the best way to solve it but it did the trick for me. In doing it that way I did not need to do any of the following

```
import { withRouter, RouteProps } from "react-router-dom";
...
export class ExampleContainer extends React.Component<ExampleComponentProps & RouteProps, undefined> {
...
export default withRouter(connect(mapStateToProps, mapDispatchToProps)(ExampleContainer) as React.ComponentType<any>);
```
Hope this helps!

**Comment by renso3x** [comment]
> import {RouteComponentProps, withRouter} from 'react-router';
> 
> export default withRouter(connect<{}, {}, IProps & RouteComponentProps>(mapStateToProps)(MyComponent));

This works for me.

**Comment by smitbarmase** [comment]
This worked for me.
```
import { withRouter, RouteComponentProps } from 'react-router-dom';

interface SomeComponentProps extends RouteComponentProps {
	someProp: string;
}

const SomeComponent= ({ someProp, history }: SomeComponentProps) => (
        <p>Hello World</p>
);

export default withRouter(SomeComponent);
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
