### ISSUE TITLE
@types/mssql Improve columns class add function signature definitions

### ISSUE THREAD

**Issue by JimiC** [DefinitelyTyped/DefinitelyTyped#17352]
- [x] I tried using the `@types/mssql` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jaminfarr @buzinas @mrrichar @elhaard @pkeuter

Using the type in my code I discovered that:
- Parameter `options` in [`columns.add`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mssql/index.d.ts#L195) should be optional (i.e. `public add(name: string, type: any, options?: any): void;`)
- The parameter `options` should be strongly typed instead of `any`. Suggested type: 
```typescript
export interface IColumnOptions {
    nullable?: boolean;
    primary?: boolean;
}
```
- The parameter `type` should be strongly typed instead of `any` (will suggest the type when I figure out how it should be exactly declared).
- Function `add` returns `number` instead of `void`.

**Comment by elhaard** [comment]
You are quite right.
As for type, it should be an ISqlType.

Could you submit a pull request for the changes?

**Comment by JimiC** [comment]
Yeah. `ISqlType` seems the right type. Happy to submit a PR.

**Comment by elhaard** [comment]
Which is exacly what you want - since [`type` can be a function](https://github.com/patriksimek/node-mssql/blob/master/lib/table.js#L27)
````javascript
      if (column instanceof Function) {
        column = column()
      }
````

**Comment by JimiC** [comment]
@elhaard While making the improvement I saw some already declared types, where more improvements can be done. I'll submit a PR with all my proposals and you can review them and suggest changes if they aren't acceptable.
