### ISSUE TITLE
[@types/karma] issue with dependency on @types/bluebird

### ISSUE THREAD

**Issue by bolelamx** [DefinitelyTyped/DefinitelyTyped#17360]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

I'm using `@types/karma: '0.13.36'`
and my build failed with errors 

```
ERROR in [at-loader] ./node_modules/@types/bluebird/index.d.ts:50:17 
    TS1005: ',' expected.

ERROR in [at-loader] ./node_modules/@types/bluebird/index.d.ts:50:31 
    TS1005: ',' expected.
```
current version of `@types/karma` is incompatible with the latest version of `@types/bluebird` 3.5.6

**Comment by andy-ms** [comment]
According to its package.json, `karma` really does depend on `bluebird`. Since `bluebird` now depends on TypeScript 2.3 at a minimum, so does `karma`.

**Comment by bolelamx** [comment]
it's versioned as `*` and any new version of `@types/bluebird` can break `@types/karma`

**Comment by ShayHaluba** [comment]
I'm having the same problem, any positive progress?

**Comment by ShayHaluba** [comment]
Hi, I have updated the typescript version to 2.3.2 and it fixed the problem.

**Comment by devoto13** [comment]
`@types/karma` no longer depends on `bluebird`, so I guess this should be closed as obsolete now.
