### ISSUE TITLE
JQuery.Event is not assignable to Event

### ISSUE THREAD

**Issue by Kovensky** [DefinitelyTyped/DefinitelyTyped#17377]
Some properties, such as `bubbles`, are not optional in the DOM `Event` type, but are in the JQuery type.

cc/ @leonard-thieu

(related?): The various `*Target` keys in `JQuery.Event` all share their type with `target`, but that is almost always incorrect unless the event was both not delegated and is being handled at the top of the bubbling order.

**Comment by leonard-thieu** [comment]
> Some properties, such as bubbles, are not optional in the DOM Event type, but are in the JQuery type.

Looks like
- `bubbles`
- `cancelable`
- `eventPhase`

need to be made non-optional. Did I miss any?

> (related?): The various *Target keys in JQuery.Event all share their type with target, but that is almost always incorrect unless the event was both not delegated and is being handled at the top of the bubbling order.

I'm not sure how to best handle this. Should they be set to `EventTarget`? `Element`?

**Comment by Kovensky** [comment]
I am not sure either :cry:

`EventTarget` is probably "more correct" but also more annoying to use without assertion.

**Comment by Kovensky** [comment]
As for the properties, it seems there are also several missing keys. I'm not so sure the JQuery.Event should be assignable to Event anymore _but_ it still feels like it should be...

This is the interface modified enough such that it would type check, with the keys in the order I got the warnings for:

```ts
    interface Event<TTarget = EventTarget> extends Partial<Pick<PointerEvent & KeyboardEvent & TouchEvent, 'altKey' |
        'changedTouches' | 'ctrlKey' | 'detail' | 'metaKey' | 'pageX' | 'pageY' | 'shiftKey' | 'view' |
        'char' | 'charCode' | 'key' | 'keyCode' | 'button' | 'buttons' | 'clientX' | 'clientY' | 'offsetX' | 'offsetY' |
        'pointerId' | 'pointerType' | 'screenX' | 'screenY' | 'targetTouches' | 'toElement' | 'touches'>>,
      Pick<PointerEvent & KeyboardEvent & TouchEvent, 'bubbles' |'eventPhase' |'cancelable' | 'cancelBubble' | 'defaultPrevented' |
        'isTrusted' | 'returnValue' | 'srcElement' | 'scoped' | 'initEvent' | 'deepPath' | 'AT_TARGET' | 'BUBBLING_PHASE' | 'CAPTURING_PHASE'> {
```

This would also become incompatible with `Event` should any augmentation be done at all to `Event`.

**Comment by leonard-thieu** [comment]
Looks like it's possible for `bubbles`, `cancelable`, and `eventPhase` to be `undefined` when creating artificial events (https://fiddle.jshell.net/qy0gzqk7/).

![chrome_2017-06-22_08-48-10](https://user-images.githubusercontent.com/5265970/27434694-8bc8a08a-5727-11e7-9c35-44e7fe276aaf.png)

**Comment by leonard-thieu** [comment]
So I've made this monstrosity: https://github.com/leonard-thieu/DefinitelyTyped/commit/97b11e5918f6189a79562ec6ea3897ff1854cbc2.

In the current typedefs, properties on `JQuery.Event` that are copied from `Event` can be `undefined` even if the original `Event` object guarantees a value for that property. In particular, `bubbles`, `cancelable`, `eventPhase`, `detail`, and `view` will always be defined for real events (but not for artificial events).

I modeled this behavior by introducing type parameters for the properties that jQuery copies. This allows declaring specialized `JQuery.Event` types that can be passed to methods such as `.blur()`.

The commit shows a minimal example of it. What do you think?
