### ISSUE TITLE
Stripe's "exports" vs "declares"

### ISSUE THREAD

**Issue by jdluzen** [DefinitelyTyped/DefinitelyTyped#17378]
- [x] I tried using the `@types/stripe` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @a904guy @ejsmith @amritk @adamcmiel @jleider

At https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/stripe/index.d.ts#L10 and https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/stripe/index.d.ts#L12 I have to change from `export` to `declare` in order for me to see/use the main Stripe function when using --module=none. Should this be changed? I am rather new to TypeScript and haven't fully discerned the differences between export/declare, modules/namespaces, and references/imports.

**Comment by amritk** [comment]
Hey @jdluzen were you using stripe.js v2 or v3?

**Comment by jdluzen** [comment]
Hi amritk, I am using V3.

**Comment by amritk** [comment]
@jdluzen I'm actually pretty new to all of this myself. But if I use declare I get the following error from the tests:
```
/Users/amritk/apps/DefinitelyTyped/types/stripe/index.d.ts
ERROR: 10:1  strict-export-declare-modifiers  Prefer 'export' to 'declare' in an external module.
```
Export is part of the typescript module system so setting the flag to 'none' will prevent it from working. Could you try it without the flag?

**Comment by galuszkak** [comment]
@jdluzen I tackle this problem in #17902

**Comment by galuszkak** [comment]
@jdluzen new packages are released. Please try `@types/stripe-v3` . I think this ticket should be closed as issue is resolved.

**Comment by jdluzen** [comment]
Looks great all, thanks for clearing everything up!
