### ISSUE TITLE
Export Webpack devtool type

### ISSUE THREAD

**Issue by jeremejevs** [DefinitelyTyped/DefinitelyTyped#17387]
I have the following line in my Webpack config:

```ts
...
devtool: isDev ? 'cheap-module-eval-source-map' : 'source-map'
...
```

And to make it compile I have to cast that expression with `as 'cheap-module-eval-source-map' | 'source-map'`, otherwise the compiler complains that it can't assign a string to [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7019f85ea5b3d6d30cbeb3bf05babf612695790d/types/webpack/index.d.ts#L35-L40).

Please, export the type, or look into some alternative solution (can't give suggestions, still learning TS).

@tkqubo @mattlewis92 @bumbleblym @bcherny @tommytroylin

**Comment by mohsen1** [comment]
Making a pull request to do that should be straight forward.

**Comment by jeremejevs** [comment]
Wasn't sure if exporting the type is the best way to address this. Is it? I can make a PR next week.

**Comment by mohsen1** [comment]
Yes, exporting useful types is a valid request.
