### ISSUE TITLE
React: error when using React.Children.toArray result for stateless component

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#17392]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @morcerf

``` ts
const FirstChild: StatelessComponent<{}> = (props) => {
  const childrenArray = React.Children.toArray(props.children);
  const maybeFirstChild = childrenArray[0];
  return maybeFirstChild || null;
};
```

gives error:

```
Type '(props: { children?: ReactNode; }) => ReactChild' is not assignable to type 'StatelessComponent<{}>'.
  Type 'ReactChild' is not assignable to type 'ReactElement<any>'.
    Type 'string' is not assignable to type 'ReactElement<any>'.
```

The type returned by `React.Children.toArray` is wider than the expected return type of `StatelessComponent`.

According to the type definitions, `React.Children.toArray` can return a `ReactChild = ReactElement | string | number`, however I can never get it to actually return `string | number`. Should we update the return type of `React.Children.toArray` to narrow it and return `ReactElement` instead?

**Comment by Kovensky** [comment]
`<FirstChild>this is a string child</FirstChild>`; `<FirstChild>{123}</FirstChild>`.

**Comment by OliverJAsh** [comment]
Hi @Kovensky. Can you elaborate? I don't understand what you're alluding to.

**Comment by Kovensky** [comment]
Inline JSX text is given to children as a string. It is also common to have numbers as a result of JSX expression brackets.

`React.Children.toArray('this is a string child')` will produce `['this is a string child']`.

**Comment by OliverJAsh** [comment]
In that case, is it valid for a stateless component to return a string or number? If so, can we widen the return type of the `StatelessComponent` type to allow strings and numbers?

**Comment by apexskier** [comment]
It's not valid for a stateless component to return a string or number right now, but [React 16 will allow it](https://twitter.com/dan_abramov/status/787778837513994240).

[codepen example](https://codepen.io/apexskier/pen/MoEmQb?editors=0011)

**Comment by OliverJAsh** [comment]
Thanks, good to know. I guess the correct implementation of `FirstChild` according to the types would be to filter out text or number children.
