### ISSUE TITLE
Ramda: Reject definition is missing the object variations

### ISSUE THREAD

**Issue by onethread** [DefinitelyTyped/DefinitelyTyped#17403]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sbking @mdekrey @mrdziuban 

Currently there's only:
```
reject<T>(fn: (value: T) => boolean, list: T[]): T[];
reject<T>(fn: (value: T) => boolean): (list: T[]) => T[];
```

There should be something like (pulled from npm-ramda):
reject<T,U extends Obj<T>>(pred: Pred<T>, obj: U) : U;

**Comment by honzabrecka** [comment]
It broke `filter` in `pipe`: https://github.com/Microsoft/TypeScript/issues/20032
