### ISSUE TITLE
npm @types packages not being updated

### ISSUE THREAD

**Issue by poislagarde** [DefinitelyTyped/DefinitelyTyped#17405]
The readme says

> The master branch is automatically published to the @types scope on NPM thanks to types-publisher. This usually happens within an hour of changes being merged.

My PR (#17370) was merged [yesterday](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17370#event-1133742376), however the npm package has not been updated:

> types types published 3 months ago
> 1.16.3 is the latest of 19 releases

See: [@types/body-parser](https://www.npmjs.com/package/@types/body-parser)

Am I missing something?

**Comment by Kovensky** [comment]
This is also affecting jquery (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17365 is still not on npm) and several other packages merged since yesterday.

**Comment by poislagarde** [comment]
Allright, I'll update the issue title to reflect its wider impact

**Comment by Torhal** [comment]
@sandersn, @andy-ms

**Comment by Torhal** [comment]
I have seen two of the types packages I use be updated today - bluebird, and body-parser - so it seems that types-publisher is running in fits and spurts. Still waiting on updates for salita from two days ago.

**Comment by Kovensky** [comment]
Looks like things are being published again; e.g. https://unpkg.com/@types/body-parser@latest/

**Comment by poislagarde** [comment]
I'm closing this issue

**Comment by sspatari** [comment]
Why this is not updating https://www.npmjs.com/package/@types/intercom-client based on this repos latest version? Am I missing something?

**Comment by sandersn** [comment]
@sspatari Looks like it took 33 minutes to publish (10:50 AM - 11:23 AM), which means that it had to wait for the half-hour timer to publish the change.

For readers who find this page from google: I've been seeing complaints in the last few weeks about publishing delays which seem to have been from npm caching. Maybe npm is experimenting with a more aggressive cache?
