### ISSUE TITLE
react-redux typings 4.4.44 breaking 

### ISSUE THREAD

**Issue by waynebrantley** [DefinitelyTyped/DefinitelyTyped#17419]
After wrapping a component with connect, to prevent the redux properties from being required, you can break up the types and do casting:

```

type TestProps=
    ReduxState     // ... state we've requested from the Redux store
    & ITestProps

interface ITestProps{
    onClick: () => void;
}


const Test: React.StatelessComponent<TestProps> = (props: TestProps) => (.......

export default connect(
    (state: ApplicationState) => {
        return {
            someData: state.someData
        };
    } // Selects which state properties are merged into the component's props
)(Test) as React.ComponentClass<ITestProps>;

```

doing the above with react-redux typings version 4.4.40 works fine.

however, 4.4.44 breaks with the following:

```
TS2345: Argument of type 'StatelessComponent<TestProps>' is not assignable to parameter of type 'Component<DispatchProp<any> & { checkoutData: ICheckoutInfoState; shippingData: IShippingInfoStat...'.
      Type 'StatelessComponent<TestProps>' is not assignable to type 'StatelessComponent<DispatchProp<any> & { someData: IDataState;...'.
        Type 'TestProps' is not assignable to type 'DispatchProp<any> & { someData: IDataState;...'.
          Type 'TestProps' is not assignable to type 'DispatchProp<any>'.
            Property 'dispatch' is missing in type 'TestProps'.
```

@tkrotoff 
@blakeembrey

**Comment by geirsagberg** [comment]
Maybe making `dispatch` in `DispatchProps` optional would fix the issue? i.e.:

Change:

```typescript
export interface DispatchProp<S> {
  dispatch: Dispatch<S>;
}
```

to

```typescript
export interface DispatchProp<S> {
  dispatch?: Dispatch<S>;
}
```

**Comment by blakeembrey** [comment]
Making it optional makes it useless. You can't use it if it's optional. I believe I noted it in the PR's, but you need to change the function signature to `TestProps & DispatchProp<any>`.

**Comment by geirsagberg** [comment]
How would one make it optional for the decorator?

**Comment by dmytro-shchurov** [comment]
+1
connect() no more returns typed with a custom class result. Instead it returns it typed as Component<..>
This causes a problem with specifying element attributes.
We had to return to 4.4.43 which had no such issue.

**Comment by davidspiess** [comment]
Any news on this? We experience the same problem since 4.4.44.

**Comment by vsaarinen** [comment]
Related discussion: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16652#issuecomment-313065845

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
