### ISSUE TITLE
lodash: _.compact should remove more types

### ISSUE THREAD

**Issue by aj-r** [DefinitelyTyped/DefinitelyTyped#17416]
`_.compact` removes all falsy values from an array. The current type definition only removes `null` and `undefined` types from the resulting array:

`compact<T>(array?: List<T | null | undefined> | null | undefined): T[];`

It should also remove `""`, `false`, and `0`. Here is my proposed change:

`compact<T>(array?: List<T | null | undefined | false | "" | 0> | null | undefined): T[];`

I can make a PR because it should be a quick fix. Also, unrelated question: should I be adding my name to the list of authors, since I've been doing most of the lodash changes lately? At what point does one become an author?

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @ericanderson

**Comment by ericanderson** [comment]
If you don't mind making the PR then go for it. Do add yourself to the authors list. There is no formal policy nor does it give any extra rights besides being notified when a PR or issue comes in
