### ISSUE TITLE
@types/paho-mqtt is missing

### ISSUE THREAD

**Issue by amikhalev** [DefinitelyTyped/DefinitelyTyped#17420]
- [x] I tried using the `@types/paho-mqtt` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

My PR for adding typings for the paho-mqtt package was merged several days ago (#17310), but there is still not a `@types/paho-mqtt` package and I am not sure why.

https://www.npmjs.com/package/@types/paho-mqtt returns 404

Am I missing something?

**Comment by Kovensky** [comment]
It looks like something is broken in the publishing side.

Related: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17405

**Comment by amikhalev** [comment]
Looks like it's there now
