### ISSUE TITLE
graphql: definition for subscribe is missing

### ISSUE THREAD

**Issue by csillag** [DefinitelyTyped/DefinitelyTyped#17441]
- [X] I tried using the `@types/graphql package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @TonyPythoneer> @calebmer @intellix @firede

When trying to use the example from here:
https://github.com/apollographql/tools-docs/blob/master/tools/graphql-subscriptions/meteor.md

For this line:
``` JavaScript
import { execute, subscribe } from 'graphql';
```
I get this error:
```
Module '"node_modules/@types/graphql/index"' has no exported member 'subscribe'.
```

It looks like the new subscribe function is not included int the definitions.
(See [here](https://github.com/graphql/graphql-js/blob/a1f63083fb1abb7cb3d57754ae41a54c8ff4b382/src/index.js#L247) for the actual source.)

The relevant lines from my package.json:
```
    "@types/graphql": "0.9.2",
    "graphql": "0.10.3",
```

**Comment by calebmer** [comment]
Feel free to submit a PR. It will likely get merged 👍
