### ISSUE TITLE
types/react/index.d.ts(191,27): error TS1005: ',' expected

### ISSUE THREAD

**Issue by manjularanathunga** [DefinitelyTyped/DefinitelyTyped#17459]
manjula@sat850:/msystem/workspace/m-app_v7$ tsc -v
Version 2.3.4

> pdm-management@1.0.0 start /msystem/workspace/m-app_v7
> tsc && concurrently "tsc -w" "lite-server" 

node_modules/@types/react/index.d.ts(191,27): error TS1005: ',' expected.
node_modules/@types/react/index.d.ts(191,29): error TS1005: '>' expected.
node_modules/@types/react/index.d.ts(191,31): error TS1128: Declaration or statement expected.
node_modules/@types/react/index.d.ts(191,41): error TS1109: Expression expected.
node_modules/@types/react/index.d.ts(212,27): error TS1005: ',' expected.
node_modules/@types/react/index.d.ts(212,29): error TS1005: '>' expected.
node_modules/@types/react/index.d.ts(212,31): error TS1128: Declaration or statement expected.
node_modules/@types/react/index.d.ts(212,41): error TS1109: Expression expected.
node_modules/@types/react/index.d.ts(214,34): error TS1005: ',' expected.
node_modules/@types/react/index.d.ts(214,36): error TS1005: '>' expected.
node_modules/@types/react/index.d.ts(214,38): error TS1128: Declaration or statement expected.
node_modules/@types/react/index.d.ts(214,48): error TS1109: Expression expected.

**Comment by tkrotoff** [comment]
See #17288
You need to upgrade to TypeScript 2.3+ to use the latest types/react/index.d.ts

**Comment by newbusiness** [comment]
Tweaks for TypeScript 2.3 is good, but seems VS2017 doesn't support (AFAIK) 2.3 - only 2.1.5 ...

Has anybody got the new .d.ts file to compile in VS2017, and if so, how?   :-)

(2.1.5 ships with VS2017 - fails to build ... have confirmed 2.3+ standalone compiles fine)

**Comment by dwhood** [comment]
I had the exact same issue (with the same errors when building) and upgraded my global install of typescript (it was version 2.2.0) that fixed the issues I was having...

`>npm list -g --depth=0`

the above command will show you your global version of typescript

**Comment by nagsbhat** [comment]
Greetings... Got similar issue with angular/index.d.ts.
This happened after I deleted node_modules folder and did 'npm install'
Interestingly, it happens only when 'npm start' is run. But does not happen when tsc is issued on command line.
For the time being I replaced index.d.ts with an old copy I had and it worked.
Any help will be appreciated..Please find the details attached:
![image](https://user-images.githubusercontent.com/29256626/32685806-90ab14f0-c6be-11e7-8358-48753b30d26e.png)

**Comment by SivaPrasanna45** [comment]
ERROR in src/app/app.component.ts(110,33): error TS1005: ';' expected.

![image](https://user-images.githubusercontent.com/27672770/35967264-5cd89d14-0ce6-11e8-8670-18e5afa6b687.png)

any one have solution for this?

**Comment by joneyjavascript** [comment]
the error was similar whe i try to run: ionic cordova build android --prod

[09:53:18]  typescript: C:/Projetos/app/node_modules/@types/q/index.d.ts, line: 200
            ',' expected.

     L199:  * Returns a promise that will have the same result as promise, except that if promise is not fulfilled or rejected
     L200:  * before ms milliseconds, the returned promise will be rejected with an Error with the given message. If mes
     L201:  * is not supplied, the message will be "Timed out after " + ms + " ms".

Solution:

Change typescript version from 2.2.2 to 2.3.4 on package.json

**Comment by WCanirinka** [comment]
I am trying to integrate React components in Angular 6 /7 but I am getting this error. I have tried all the solutions online then opted to upgrade from Angular 6 to 7 to see if the problem can change but the errors are still there. Below are the errors I am getting. I need help:
`ERROR in src/react/CustomDiagram/event/component.tsx(6,13): error TS1005: '=' expected.
src/react/CustomDiagram/event/component.tsx(6,41): error TS1005: ';' expected.
src/react/CustomDiagram/event/component.tsx(51,23): error TS1005: ';' expected.
src/react/CustomDiagram/event/component.tsx(52,54): error TS1005: ';' expected.
src/react/CustomDiagram/event/component.tsx(53,65): error TS1005: ';' expected.
src/react/CustomDiagram/event/component.tsx(54,34): error TS1005: ';' expected.
src/react/CustomDiagram/modelExample.tsx(3,13): error TS1005: '=' expected.
src/react/CustomDiagram/modelExample.tsx(3,34): error TS1005: ';' expected.
src/react/CustomDiagram/rule/component.tsx(6,13): error TS1005: '=' expected.
src/react/CustomDiagram/rule/component.tsx(6,41): error TS1005: ';' expected.
src/react/CustomDiagram/rule/component.tsx(42,23): error TS1005: ';' expected.
src/react/CustomDiagram/rule/component.tsx(43,54): error TS1005: ';' expected.
src/react/CustomDiagram/rule/component.tsx(44,65): error TS1005: ';' expected.
src/react/CustomDiagram/rule/component.tsx(45,34): error TS1005: ';' expected.
src/react/CustomDiagram/task/component.tsx(6,13): error TS1005: '=' expected.
src/react/CustomDiagram/task/component.tsx(6,41): error TS1005: ';' expected.
src/react/CustomDiagram/task/component.tsx(41,23): error TS1005: ';' expected.
src/react/CustomDiagram/task/component.tsx(42,54): error TS1005: ';' expected.
src/react/CustomDiagram/task/component.tsx(43,65): error TS1005: ';' expected.
src/react/CustomDiagram/task/component.tsx(44,34): error TS1005: ';' expected.
`

**Comment by olemp** [comment]
> I am trying to integrate React components in Angular 6 /7 but I am getting this error. I have tried all the solutions online then opted to upgrade from Angular 6 to 7 to see if the problem can change but the errors are still there. Below are the errors I am getting. I need help:
> `ERROR in src/react/CustomDiagram/event/component.tsx(6,13): error TS1005: '=' expected. src/react/CustomDiagram/event/component.tsx(6,41): error TS1005: ';' expected. src/react/CustomDiagram/event/component.tsx(51,23): error TS1005: ';' expected. src/react/CustomDiagram/event/component.tsx(52,54): error TS1005: ';' expected. src/react/CustomDiagram/event/component.tsx(53,65): error TS1005: ';' expected. src/react/CustomDiagram/event/component.tsx(54,34): error TS1005: ';' expected. src/react/CustomDiagram/modelExample.tsx(3,13): error TS1005: '=' expected. src/react/CustomDiagram/modelExample.tsx(3,34): error TS1005: ';' expected. src/react/CustomDiagram/rule/component.tsx(6,13): error TS1005: '=' expected. src/react/CustomDiagram/rule/component.tsx(6,41): error TS1005: ';' expected. src/react/CustomDiagram/rule/component.tsx(42,23): error TS1005: ';' expected. src/react/CustomDiagram/rule/component.tsx(43,54): error TS1005: ';' expected. src/react/CustomDiagram/rule/component.tsx(44,65): error TS1005: ';' expected. src/react/CustomDiagram/rule/component.tsx(45,34): error TS1005: ';' expected. src/react/CustomDiagram/task/component.tsx(6,13): error TS1005: '=' expected. src/react/CustomDiagram/task/component.tsx(6,41): error TS1005: ';' expected. src/react/CustomDiagram/task/component.tsx(41,23): error TS1005: ';' expected. src/react/CustomDiagram/task/component.tsx(42,54): error TS1005: ';' expected. src/react/CustomDiagram/task/component.tsx(43,65): error TS1005: ';' expected. src/react/CustomDiagram/task/component.tsx(44,34): error TS1005: ';' expected. `
> 
> My package.json found below:
> `{ "name": "inovation-backend", "version": "0.0.1", "license": "MIT", "scripts": { "postinstall": "ng build --no-progress --prod", "ng": "ng", "start": "http-server ./dist/", "start:hmr": "ng serve --hmr", "start:aot": "ng serve --aot", "start:prod": "ng serve --prod", "start:prod:aot": "ng serve --prod", "build": "ng build", "test": "ng test", "lint": "ng lint", "e2e": "ng e2e", "preinstall": "rm -rf node_modules package-lock.json && npm install -g http-server @angular/cli@1.7.3" }, "engines": { "node": "8.9.4", "npm": "5.7.1" }, "private": true, "dependencies": { "@angular-devkit/build-webpack": "^0.1101.2", "@angular/animations": "^7.2.16", "@angular/cdk": "^6.4.3", "@angular/common": "^7.2.16", "@angular/core": "^7.0.4", "@angular/flex-layout": "6.0.0-beta.17", "@angular/forms": "^7.2.16", "@angular/http": "^7.2.16", "@angular/material": "^6.4.3", "@angular/material-moment-adapter": "^6.2.1", "@angular/platform-browser": "^7.2.16", "@angular/platform-browser-dynamic": "^7.2.16", "@angular/router": "^7.2.16", "@auth0/angular-jwt": "^2.0.0", "@ngrx/effects": "^6.0.0", "@ngrx/router-store": "^6.0.0", "@ngrx/store": "^6.0.1", "@ngrx/store-devtools": "^6.0.0", "@ngx-translate/core": "^8.0.0", "@ngx-translate/http-loader": "^2.0.0", "@swimlane/ngx-charts": "^7.0.1", "@types/react": "^16.4.7", "@types/react-dom": "^16.0.6", "angular-bootstrap-md": "^7.5.4", "angular2-signaturepad": "^2.8.0", "angular2-token": "^0.2.0", "bootstrap": "4.0.0-beta", "ckeditor": "^4.12.1", "ckeditor4-angular": "1.0.0-beta.2", "core-js": "^2.4.1", "d3": "^4.12.2", "date-fns": "^1.29.0", "express": "^4.15.3", "faker": "^5.0.0", "font-awesome": "^4.7.0", "hammerjs": "^2.0.8", "jwt-decode": "^2.2.0", "ls": "^0.2.1", "moment": "^2.22.2", "ng2-dragula": "^1.5.0", "ng2-file-upload": "^1.4.0", "ng2-rut": "^0.3.2", "ngrx-store-localstorage": "^5.0.0", "ngx-color-picker": "^8.2.0", "ngx-dropzone": "^2.0.3", "ngx-material-timepicker": "^3.3.1", "ngx-toastr": "^6.5.0", "pusher-js": "^4.3.0", "react": "^16.6.3", "react-dom": "^16.6.3", "react-flow-diagram": "^2.10.0", "rxjs": "^6.3.3", "rxjs-compat": "^6.3.3", "rxjs-tslint": "^0.1.8", "sweetalert2": "8.14.0", "xlsx": "^0.16.6", "zone.js": "~0.8.26" }, "devDependencies": { "@angular-devkit/build-angular": "~0.6.8", "@angular/cli": "^7.0.7", "@angular/compiler": "^7.2.16", "@angular/compiler-cli": "^7.2.16", "@angular/language-service": "^7.2.16", "@babel/core": "^7.12.10", "@babel/preset-env": "^7.12.11", "@types/jasmine": "~2.5.53", "@types/jasminewd2": "~2.0.2", "@types/node": "^6.14.12", "babel-loader": "^8.2.2", "codelyzer": "~3.2.0", "jasmine-core": "~2.6.2", "jasmine-spec-reporter": "~4.1.0", "karma": "~1.7.0", "karma-chrome-launcher": "~2.1.1", "karma-cli": "~1.0.1", "karma-coverage-istanbul-reporter": "^1.2.1", "karma-jasmine": "~1.1.0", "karma-jasmine-html-reporter": "^0.2.2", "node-sass": "^4.14.1", "protractor": "5.3.0", "ts-node": "~3.2.0", "tslint": "^5.10.0", "typescript": "^3.1.6" } } `

Experiencing the same issue here with React.

**Comment by Pdzly** [comment]
any fix?

**Comment by jonathasborges1** [comment]
any fix ?

**Comment by jakebailey** [comment]
Old issue, but I don't think this is an issue anymore. These old versions are long unsupported.
