### ISSUE TITLE
 @types/node-feedparser is for the wrong package

### ISSUE THREAD

**Issue by hwiechers** [DefinitelyTyped/DefinitelyTyped#17467]
The definitions in  `@types/node-feedparser` are for the `feedparser` package and not the `node-feedparser` package. The repo for `feedparser` is http://github.com/danmactough/node-feedparser but the package name is `feedparser`.

Running the test code https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-feedparser/node-feedparser-tests.ts against `node-feedparser` gives me `TypeError: this._data.slice is not a function`. It looks like the package was incorrecly changed in this commit https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6ae1b1ea58611cd5457424e91335323044e24c72 .

**Comment by bjackson** [comment]
Yes. The name should be changed to `feedparser` instead of `node-feedparser`.
