### ISSUE TITLE
2 semantic errors in enzyme type definition

### ISSUE THREAD

**Issue by nvdbleek** [DefinitelyTyped/DefinitelyTyped#17483]
Hi @tkrotoff why did you remove the state generic parameter on https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/enzyme/index.d.ts#L18 ?

It gives compile errors in our build:
`
08:16:10 /opt/jenkins/workspace/wbd-designer-pr/node_modules/@types/enzyme/index.d.ts(18,35): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
08:16:10 /opt/jenkins/workspace/wbd-designer-pr/node_modules/@types/enzyme/index.d.ts(26,41): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
08:16:10 [08:16:05] TypeScript: 2 semantic errors
08:16:10 [08:16:05] TypeScript: emit succeeded (with errors)
`

Regards,

Nick Van den Bleeken

**Comment by tkrotoff** [comment]
Why? See #17288 
And the solution to your problem is in this discussion : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17288#issuecomment-310761904

**Comment by nvdbleek** [comment]
Sorry apparently the react typings weren't up-to-date on our build server...
