### ISSUE TITLE
angular.element() should accept 'document'

### ISSUE THREAD

**Issue by mattdsteele** [DefinitelyTyped/DefinitelyTyped#17529]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - /cc @borisyankov @leonard-thieu 

Currently code like: `angular.element(document)` throws a compiler error: 

```
Argument of type 'Document' is not assignable to parameter of type 'string | Element'.
  Type 'Document' is not assignable to type 'Element'.
    Property 'classList' is missing in type 'Document'.
```

But this is allowable by AngularJS: https://github.com/angular/angular.js/blob/master/src/jqLite.js#L49

```
> angular.element(document)
Object [ HTMLDocument → forms ]
```

I think the `JQueryStatic` interface needs `| Document` added to its types, but someone else might need to verify.

**Comment by leonard-thieu** [comment]
I put in a PR for this (#17531). Thanks for the report!
