### ISSUE TITLE
Add typings for http-proxy-middleware

### ISSUE THREAD

**Issue by westy92** [DefinitelyTyped/DefinitelyTyped#17542]
Add typings for [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware).

**Comment by zebMcCorkle** [comment]
I just wrote some typings: https://github.com/zebMcCorkle/DefinitelyTyped/blob/add-http-proxy-middleware/types/http-proxy-middleware/index.d.ts

Follow the instructions at https://github.com/DefinitelyTyped/DefinitelyTyped#test-a-new-package to use them.
