### ISSUE TITLE
@types/async bug - Dictionary<{}> vs. Iterable<T>

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#17545]
- [x] I tried using the `@types/async` package and had problems.

I have this issue on SO:

https://stackoverflow.com/questions/44787744/missing-index-signature-in-type-arraystring-with-typescript?noredirect=1#comment76556523_44787744

I have an inkling that instead of using `Dictionary<{}>` for this argument, it should be `Iterable<T>.`

So I am suggesting that there is possibility that typings for @types/async are incorrect.

`Array<string>` is an Iterable, but I do not think an `Array<string>` can be a `Dictionary<{}>`.

I am 100% certain that the async library accepts an Array instance as the first argument to async.mapLimit, along with a host of other functions.

Definitely very interested in resolving this one.

**Comment by makepost** [comment]
TypeScript sees a parameter type mismatch, and skips overloads, both `arr: T[] | IterableIterator<T>` and `arr: Dictionary<T>`. Error message uses last read overload.

See this example:

```typescript
import { map } from "async";

interface IPlace {
  id: number;
}

export class PlaceService {
  public getManyBroken(callback: (error?: Error, places?: IPlace[]) => void) {
    const ids = [0, 1, 2, 3];
    map(ids, this.getOne, callback);

    // "'number[]' is not assignable to parameter of type 'Dictionary<number>'".
  }

  public getMany(callback: (error?: Error, places?: (IPlace | undefined)[]) => void) {
    const ids = [0, 1, 2, 3];
    map(ids, this.getOne, callback);

    // OK.
  }

  private getOne(
    id: number,
    callback: (error?: Error, place?: IPlace) => void
  ) {
    if (Math.random() > 0.5) {
      callback(new Error("NotFound"));
    } else {
      callback(undefined, { id });
    }
  }
}
```

[The `map` definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e65cb3ba52b39d5afc9be6a6bd7d0258ea6adfef/types/async/index.d.ts#L116) uses AsyncResultArrayCallback:

```typescript
export interface AsyncResultArrayCallback<T, E> { (err?: E, results?: (T | undefined)[]): void; }

// ...

export function map<T, R, E>(arr: T[] | IterableIterator<T>, iterator: AsyncResultIterator<T, R, E>, callback?: AsyncResultArrayCallback<R, E>): void;
```

Actual callback receives either an error or an array of `IPlace`. Not an array of `IPlace | undefined`. Why is `| undefined` there? Shouldn't `map` use something like:

```typescript
export interface AsyncMapArrayCallback<T, E> { (err?: E, results?: T[]): void; }
```

?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
