### ISSUE TITLE
@types/react breaks with 2.4.1

### ISSUE THREAD

**Issue by evanjmg** [DefinitelyTyped/DefinitelyTyped#17578]
- [ X] I tried using the `@types/react` package with typescript 2.4.1 and it does not build
- [ X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
`
[at-loader] Checking finished with 1 errors
Error in bail mode: [at-loader] node_modules/@types/react/index.d.ts:181:11 
    Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.
`

**Comment by thisisnaty** [comment]
Hitting this exact error too, have you found a solution? I tried with typescript 2.5, then with 2.3.4 and none worked.

**Comment by wastrilith2k** [comment]
I rolled back to typescript 2.3.2 and was able to move past this.

**Comment by thisisnaty** [comment]
Changing to 2.3.2 worked for compiling with tsc but not with gulp-typescript. For now I just edited index.d.ts for the conflicting types to have a property in common, but there must be another workaround.

**Comment by samuelmaddock** [comment]
To fix this, I ended up locally forking the version of React type definitions I use and making the following change.
```diff
+interface Component<P = {}, S = {}> extends ComponentLifecycle<P, S> { }
-class Component<P, S> extends ComponentLifecycle<P, S> {
+class Component<P, S> {
```
This change reflects the [current state of the React type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/15b7bac31972fbc081028937dfb1487507ca5fc9/types/react/index.d.ts#L199-L200).

The proper fix is to likely to upgrade your React type definitions and possibly any React dependencies used in your project.

**Comment by kant2002** [comment]
@evanjmg could you make sure that you use latest version of React typings. In my project.json generated by .NET Core JavaScript services template the version of React typings was explicitly set without `^` in the package.json which lead to exact same error as yours.

**Comment by jamesdanged** [comment]
This also resolved for me when I switched from the 0.14.xx type definitions to the 15.xx.xx ones.

**Comment by moorthi07** [comment]
**Only typescript 2.3.4  is working** . I have tried, 2.2.2 / 2.4/ 2.5.2  - none worked.

**Comment by Mr-Dolphin** [comment]
In my project, I rolled back to global typescript@2.3.2,it didn't work.Then I recognized that when webpack is bundling,it the loader use the typescript in the node_modules instead the global one.So I rolled the typescript in the node_modules to 2.3.2,re-bundling and it worked.

**Comment by ollwenjones** [comment]
I'm kind of baffled this is still open, as we are now on TS 2.6.1 - we upgraded all our surrounding projects - it never occurred to me that the react project would be the bottle-neck. Just staying on a fixed, older version of TypeScript isn't really a _solution_ - more like a work-around.

We were really hoping to use typescript 2.4+ features like string enums. I'm going to try to follow @samuelmaddock 's example there, but if that doesn't work, we may have to wait. 😢

**Comment by evanjmg** [comment]
I've started a react native project with 16.0.25 @types/react  and 0.48.10 @types/react-native. I'll have to revisit this on the previous project, in order to report that upgrading to 15 is a fix. When I reported the issue I was using a different older version of react that uses webpack etc and has different resolution.

**Comment by evanjmg** [comment]
this is old and I'd recommend just not using this type version.
