### ISSUE TITLE
@types/jquery

### ISSUE THREAD

**Issue by MichalMeszaros** [DefinitelyTyped/DefinitelyTyped#17571]
Invalid typing in JQuery for Deferred and Promise
```
var test = $.Deferred();
var testPromise = test.promise();
var testPromise2 = testPromise.done(() => { });
```
test is type of Deferred<any, any, any> ?
testPromise is type of Promise<any, any, any> ?
and last why is testPromise2  type of **Deferred<any, any, any>** when testPromise is  Promise<any, any, any> ?

This cause failing of build typescript if you have function that should return promise and return deferred object.

**Comment by leonard-thieu** [comment]
Will be fixed by #17513.

**Comment by MichalMeszaros** [comment]
Thanks for quick response, do you know when will this pull request be pushed  ?

**Comment by leonard-thieu** [comment]
Tests are currently failing. I still have to resolve an issue with `$.when()` that I'm having trouble with.
