### ISSUE TITLE
@types/google-maps doesn't allow key, etc. to be set targeting "module": "es2015",

### ISSUE THREAD

**Issue by chadbr** [DefinitelyTyped/DefinitelyTyped#17583]
- I tried using the `@types/google-maps` package and had problems.
- TypeScript version 2.3.4
- angular/cli version 1.1.2 (if it helps...) 
  - Authors: @....

@DeividasBakanas @GiedriusGrabauskas

Whenever I try to use the GoogleMapsLoader in my Angualr4/AngularCLI application, I get an error that the variables exported by the type definition are read only:

```
import * as GoogleMapsLoader from 'google-maps';

GoogleMapsLoader.KEY = 'foo';
```

yields:
```
[ts] Cannot assign to 'KEY' because it is a constant or a read-only property.
```

Any ideas on how to get around this?

tsconfig.json
```
{
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "pretty": true,
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "lib": [
      "es2016",
      "dom"
    ],
    "outDir": "../out-tsc/app",
    "target": "es5",
    "module": "es2015",
    "baseUrl": "",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

**Comment by DeividasBakanas** [comment]
This problem was discussed in a TypeScript issue [#6751](https://github.com/Microsoft/TypeScript/issues/6751).  They recommend to use `require` when importing packages with this behavior expected. 

```ts
import GoogleMapsLoader = require('google-maps');
```

This import  example can be found in [google-maps-tests.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-maps/google-maps-tests.ts#L1) in [`google-maps`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/google-maps) types folder.

**Comment by chadbr** [comment]
yea, you can't use that syntax in Angular apps... they use ECMAScript 2015 modules -- 

you get this error when you try.
----
ERROR in /Users/chadbr/dev/{mycomponent}.ts (1,1): Import assignment cannot be used when targeting ECMAScript 2015 modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
webpack: Failed to compile.
----

I worked around it by adding the script explicitly in my index.html - but it would be nice to use the loader...

Thanks --

**Comment by GiedriusGrabauskas** [comment]
There are two ways to resolve this issue:
1) Use require, as @DeividasBakanas mentioned in [comment](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17583#issuecomment-311953891).
2) Or update source package ([Carrooi/Js-GoogleMapsLoader](https://github.com/Carrooi/Js-GoogleMapsLoader)).

**Comment by chadbr** [comment]
https://github.com/Carrooi/Js-GoogleMapsLoader/issues/52
https://github.com/Carrooi/Js-GoogleMapsLoader/issues/54

ok... I'll close this pending source package is updated.

fwiw, require is not usable in Angular2/4+ projects.
