### ISSUE TITLE
lodash is completely broken with typescript 0.9.7 (1.0rc)

### ISSUE THREAD

**Issue by luisrudge** [DefinitelyTyped/DefinitelyTyped#1759]
see here

![image](https://f.cloud.github.com/assets/941075/2277652/7d8ae386-9f45-11e3-9fd9-096f4d0558d4.png)

Reason:
http://typescript.codeplex.com/wikipage?title=Known%20breaking%20changes%20between%200.8%20and%200.9
"Generic constraints no longer can reference parameters in the same parameter list"

**Comment by r3nya** [comment]
Hey @luisrudge! I guess that you can close this issue. :)

**Comment by luisrudge** [comment]
My pleasure 😬
