### ISSUE TITLE
spyOn(...).mockImplementation should return a SpyInstance rather than a Mock

### ISSUE THREAD

**Issue by jamiecopeland** [DefinitelyTyped/DefinitelyTyped#17605]
- [x] I tried using the `@types/jest` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] @alexjoverm @asvetliakov @NoHomey @orta

While attempting to write a system to un-mock/un-spy on modules I came across what seems to be a problem with types returned by `mockImplementation` (and `mockImplementationOnce`, `mockReturnThis`, `mockReturnValue`, `mockReturnValueOnce`) as a result of calling `spyOn`. This is that while the typings specify that `mockImplementation` returns a `Mock`, what actually comes back is a `SpyInstance` with the `mockRestore` function available to call. It'd be great to get some feedback on this, and if you think it's a valid fix, I can get a PR put together reflecting this change.

The type hack version below works, even though the current types specify that it shouldn't

```
// Spy creating/cleaning utility (as it should be)
const createSpies = (spies: jest.SpyInstance<any>[]) => () => spies.forEach(spy => spy.mockRestore());

// Spy creating/cleaning utility (with hack to prevent compiler from complaining)
const createSpies = (spies: any[]) => () => spies.forEach(spy => spy.mockRestore());

// Test
it('should...', () => {
  const restoreMocks = createSpies([
    jest.spyOn(moduleA, 'sayHi').mockImplementation(() => 'mock hello')
    jest.spyOn(moduleB, 'sayBye').mockImplementationOnce(() => 'mock goodbye')
  ]);

  // Do tests...

  restoreMocks();
});


```

**Comment by duro** [comment]
We need this! @alexjoverm @asvetliakov @NoHomey @orta

Can we get an update, they types haven't been updated in over a month

**Comment by diofeher** [comment]
+1 on that

**Comment by vkrol** [comment]
Is this still an issue? I don't think so. The example from the first message in this thread is working without type errors. You can try it: https://github.com/vkrol/typescript-jest-spy-on-playground
Steps:
1. Clone the repository
2. Run the following commands:
`yarn`
`yarn typecheck`

**Comment by orta** [comment]
Is this needed now that there's been some pretty massive refactoring  in 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32579#issuecomment-460730562 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32816  also ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
