### ISSUE TITLE
[@types/restify] Restify has been updated to 5.0.0

### ISSUE THREAD

**Issue by simonepri** [DefinitelyTyped/DefinitelyTyped#17620]
Restify 5.0.0 is finally released 🎉 so TypeScript definitions needs to be updated accordingly.
As an example the CORS has been removed and moved here:
https://github.com/TabDigital/restify-cors-middleware

The changelog is available here:
https://github.com/restify/node-restify/blob/5.x/CHANGES.md#500

Contributors to notify: @blittle, @stevehipwell, @fortuna, @mhegazy, @andy-ms
Reference for the restify repo: https://github.com/restify/node-restify/issues/1389

**Comment by stevehipwell** [comment]
@simonepri - I've started looking at making the changes for this but as there is currently no v5.0.0 documentation from the Restify team this might be quite painful. Do you have any specifics that are not working for you?

**Comment by simonepri** [comment]
@stevehipwell currently I've not tested at all, the issue was opened just as a reminder.
My plan is to move our project to typescript soon, I will let you now asap.

**Comment by alexgoldstone** [comment]
There is a migration guide available here:
https://github.com/restify/node-restify/blob/5.x/4TO5GUIDE.md

Using restify 4.3.1 I had code that looked like:
```
if (!authenticated) {
    return next(new restify.NotAuthorizedError());
}
```

When I upgraded to restify 5.0.0, the above caused the following error:
```
TypeError: restify.NotAuthorizedError is not a constructor
```

The migration guide explains that I need to use the `restify-errors` project so I do something like:
```
import * as errors from 'restify-errors';
...
...
return next(new errors.NotAuthorizedError());
```

This works however TypeScript outputs:
```
error TS7016: Could not find a declaration file for module 'restify-errors'.
```

**Comment by dthunell** [comment]
Also `restify.queryParser()` etc now seem to be `restify.plugins.queryParser()`

**Comment by alexgoldstone** [comment]
The CORS plugin has been removed entirely and replaced with a recommendation to use:

https://github.com/TabDigital/restify-cors-middleware

This doesn't currently have TypeScript definitions.

**Comment by dthunell** [comment]
I've attempted my first OSS contribution for the CORS middleware here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17747

**Comment by stevehipwell** [comment]
I've created a [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17765#issuecomment-313077551).

**Comment by renjithamadeus** [comment]
Created another PR with some more changes.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18036

**Comment by mattbishop** [comment]
@types/restify 5.0.1 is missing `Server.router`.

**Comment by stevehipwell** [comment]
@mattbishop can you add a link to the documentation for `Server.router`?

**Comment by mattbishop** [comment]
http://restify.com/node-restify/ has a section called "Hypermedia" and on it they refer to `server.router` in their example.

**Comment by stevehipwell** [comment]
@mattbishop - Sorry for the delay. I've added the following properties to the definition for the *Restify* Server interface:

- `server`
- `router`

I've created a [pull](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18626) request for this.

**Comment by mattbishop** [comment]
Thanks @simonepri
