### ISSUE TITLE
Missing PromiseConstructor in core-js

### ISSUE THREAD

**Issue by asmundg** [DefinitelyTyped/DefinitelyTyped#17640]
- [x] I tried using the `@types/0.9.42` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mfdeveloper, @rbuckton

The core-js/fn/promise module declares Promise as core.Promise
```
declare module "core-js/fn/promise" {
    const Promise: typeof core.Promise;
    export = Promise;
}
```

core.Promise is declared as PromiseConstructor;

```
    const Promise: PromiseConstructor;
```

PromiseConstructor is undefined in Typescript when targeting es5. Is this intentional?

**Comment by mfdeveloper** [comment]
@asmundg Make sure that you add `es2015` into `lib` key on `tsconfig.json` file. This is required to load `PromiseConstructor` because this type is defined on `node_modules/typescript/lib/lib.es2015.symbol.wellknown.ts`. Something like this:

```js
"compilerOptions": {
   ...
  "lib": [
      "dom",
      "es2015"
    ]
}
```

> **PS:** Do not explicitly import the module `core-js/fn/promise` if you are using a app that include `zone.js` (e.g Angular apps). You can got the error **Polyfilling Promise api is not necessary when zone.js is loaded**

**Comment by asmundg** [comment]
While I'm aware that I can tell TypeScript that ES6 features are available on the target platform, this seems like an unsafe thing to do when I'm actually importing the Promise constructor from a library.

E.g. Promise is not going to be generally available where it's not imported and telling tsc otherwise runs the risk of hiding bugs.

This is why I'm wondering whether not having a complete declaration for the library functions is by design.

**Comment by mfdeveloper** [comment]
I understand your point. But, if you check the oficial typescript documentation, you will see that include `lib` to use `Promise` is recommended.

Search for **Downlevel Async Functions** in this link below:

 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html

**Comment by asmundg** [comment]
If I read the typescript docs correctly, they recommend using lib: es2015.promise when polyfilling. Which makes perfect sense, since the target platform then fully supports Promise. I also assume that polyfilling will be more or less required if one wants to use async functions. 

It still seems like importing the Promise constructor without adding it to the global namespace should not require declaring that a polyfill is present.

I.e. I don't fully understand why core-js/fn/promise doesn't fully declare its interface, like a normal function. If the reason is that you will basically never use this over the polyfill, that's fine, but should be reflected in the comments. :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
