### ISSUE TITLE
[react-router-redux] Type `Action` is not assignable to type `RouterAction`

### ISSUE THREAD

**Issue by Grmiade** [DefinitelyTyped/DefinitelyTyped#17652]
- [x] I tried using the `@types/react-router-redux` package and had problems.
- [x] I tried using the latest stable version of typescript. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @huy-nguyen 

```typescript
import { routerReducer } from 'react-router-redux'
import { combineReducers } from 'redux'
import { reducer as formReducer } from 'redux-form'

const rootReducer = (client) => combineReducers({
  apollo: client.reducer(),
  form: formReducer,
  router: routerReducer,
})
```

When I create my root reducer, I have this type issue for `routerReducer`:

```
Type `Action` is not assignable to type `RouterAction`
Property `payload` is missing in type `Action`
```

Change `payload` property as an optional property fix this issue but it's annoying to lose this information :/

Any idea? I use Typescript 2.4.1

**Comment by zyml** [comment]
Seems like it's broken due to TypeScript 2.4.1's stricter checking for generic functions. You can set `noStrictGenericChecks` to `true` in your config as a workaround for now.

**Comment by Grmiade** [comment]
Thanks @zyml for this workaround.
https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#stricter-checking-for-generic-functions

**Comment by huy-nguyen** [comment]
The typescript team made a PR for `redux` to make it compatible with TS 2.4.1 (https://github.com/reactjs/redux/pull/2467). Once that PR is released, maybe we should update `react-router-redux`'s definition to match that new `redux` definition?
