### ISSUE TITLE
DOM4

### ISSUE THREAD

**Issue by pravdomil** [DefinitelyTyped/DefinitelyTyped#17664]
- [x] I tried using the `@types/dom4` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @adidahiya @giladgray

I'm missing definitions for:

 [new DOM Level 4 parentNode entries](https://dom.spec.whatwg.org/#parentnode):

  * prepend()
  * append()

And for [new DOM Level 4 childNode entries](https://dom.spec.whatwg.org/#childnode):

  * before()
  * after()
  * replaceWith()
  * remove()

in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/dom4/index.d.ts

**Comment by adidahiya** [comment]
Feel free to send a PR adding those type definitions

**Comment by giladgray** [comment]
@pravdomil I've opened #23178 to add these missing members 👍
