### ISSUE TITLE
Chart.update() function has incorrect argument type

### ISSUE THREAD

**Issue by Miced** [DefinitelyTyped/DefinitelyTyped#17689]
- [x] I tried using the `@types/highcharts` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @damianog 

The Highcharts [Chart.update()](http://api.highcharts.com/highcharts/Chart.update) option seems to accept an `Options` object, rather than an `ChartOptions` (which is nested inside the former). Since Typescript 2.4 this gives problems with weak types.

**Comment by Miced** [comment]
Any update on this? It follows the relevant demo [JSFiddle](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/chart-update/)
@cebor @MartinVSA since you've been doing the latest commits, can you review this?

**Comment by hanssens** [comment]
@Miced this should be fixed in PR #18841, which is merged just now.
Thanks to @azmenak for that one.

**Comment by Miced** [comment]
This is fixed indeed.
