### ISSUE TITLE
@types/chai-http - Add text to Response

### ISSUE THREAD

**Issue by SMAH1** [DefinitelyTyped/DefinitelyTyped#17694]
- [X] I tried using the `@types/chai-http` package and had problems.

`Interface Response` only has `body`.
but when `content-type` is `text/html`,`body` is empty and `text` is used.
please add `text`.

**Comment by G1itcher** [comment]
+1

**Comment by G1itcher** [comment]
This can be closed. Above merge resolves the issue.
