### ISSUE TITLE
[ramda]: Inconsistent definitions (prop, path)

### ISSUE THREAD

**Issue by nenadalm** [DefinitelyTyped/DefinitelyTyped#17736]
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @donnut @mdekrey @LiamGoodacre @mrdziuban @sbking @afharo

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/96617b044317c4e9ed79c0b671d93a4e5f2ecff7/types/ramda/index.d.ts#L1156

definitions
```typescript
path<T>(path: Path): (obj: any) => T;
prop<T>(p: string): <T>(obj: any) => T;
```

example
```typescript
interface Test {
    prop1: 'val';
    prop2: 'val2';
}

const propF = r.prop<'val'>('prop1');
const pathF = r.path<'val'>(['prop1']);

// type: {}
const propVal = propF({});

// type: "val"
const pathVal = pathF({});
```

as you can see calling the created functions using `prop`, `val` exactly the same way returns different types. As for my current uses - I would prefer `prop` to work the way `path` works (though other way around would be probably more correct as you don't have to know type of object passed to the function when creating it). Best would be to allow both cases (but I don't think that's possible in typescript?) - meaning that you can set return type when calling `r.prop<'val'>` or when calling the resulting function `propF<'val'>`. What do you think?

**Comment by afharo** [comment]
yeah, it looks like the second <T> is breaking the type... there should be only 1.
Can you create a PR with these changes so prop is
```prop<T>(p: string): (obj: any) => T;```

I would even think, it worths trying some sort of
```typescript
prop<T, U>(p: K in keyof T): (obj: T) => U
```
This way, hopefully, the compiler will know the resulting type without even providing it as it's inherited from the object.

**Comment by mdekrey** [comment]
Better would be:

        prop<K: keyof T, T>(p: K, obj: T): T[K];
        prop<K: keyof T, T>(p: K): (obj: T) => T[K];

Unfortunately, this is a breaking change for any existing users. I'll play with it this weekend if I get a chance to see if there's a way to keep the old single generic type and support a more specific one that gets the typings right automatically.

**Comment by nenadalm** [comment]
I think that this looks correct (let's not forget about the `undefined` case):

```typescript
prop<T, K extends keyof T>(p: K, obj: T): T[K];
prop<T, K>(p: K, obj: T): undefined;
prop<T, K extends keyof T>(p: K): (obj: T) => T[K];
prop<T, K>(p: K): (obj: T) => undefined;
```

let me know if I should create PR or feel free to create one yourself.

**Comment by nenadalm** [comment]
Better version:
```typescript
prop<T>(p: keyof T, obj: T): T[keyof T];
prop<T>(p: any, obj: T): undefined;
prop<T>(p: keyof T): (obj: T) => T[keyof T];
prop<T>(p: any): (obj: T) => undefined;
```

**Comment by afharo** [comment]
I'm ok with those changes. I don't think it's going to break old users, by doing it the way @nenadalm is proposing, will it?

**Comment by nenadalm** [comment]
@afharo  it will. You won't be even able to compile old code.

Notice that my typings requre 2 types (so if you specify just one - it won't compile). If we want to change typings without breaking code, old typings could be used togeter with new ones. So it would be

```typescript
prop<T, K extends keyof T>(p: K, obj: T): T[K];
prop<T, K>(p: K, obj: T): undefined;
prop<T, K extends keyof T>(p: K): (obj: T) => T[K];
prop<T, K>(p: K): (obj: T) => undefined;

// old typings
prop<T>(p: string, obj: any): T;
prop<T>(p: string): <T>(obj: any) => T;
```

**Comment by mdekrey** [comment]
Looks like despite Microsoft/TypeScript#209 not being completed, generic overloading does work in TS2.0+ in type definition files. As a result, no breaking changes will come of my PR (above.)

**Comment by afharo** [comment]
@mdekrey I'd go ahead with the changes, but, please, improve the tests to actually ensure the expected type (check PR comment in the code).

**Comment by tycho01** [comment]
@nenadalm @afharo @mdekrey consider trying the typings at [`types/npm-ramda`](https://github.com/types/npm-ramda/).

`R.path` has generally been one of the [challenging](https://github.com/Microsoft/TypeScript/issues/12290) functions to type, but it should help for that and a bunch of other typing challenges inherent in Ramda.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
