### ISSUE TITLE
@types/cheerio - index.d.ts(xxx): error TS2304: Cannot find name 'Document'. 

### ISSUE THREAD

**Issue by eriy** [DefinitelyTyped/DefinitelyTyped#17741]
I tried using the `@types/cheerio` package and had problems.

node_modules/@types/cheerio/index.d.ts(124,36): error TS2304: Cannot find name 'Document'.
node_modules/@types/cheerio/index.d.ts(137,21): error TS2304: Cannot find name 'Document'.
node_modules/@types/cheerio/index.d.ts(138,21): error TS2304: Cannot find name 'Document'.
node_modules/@types/cheerio/index.d.ts(142,22): error TS2304: Cannot find name 'Document'.
node_modules/@types/cheerio/index.d.ts(143,22): error TS2304: Cannot find name 'Document'.
node_modules/@types/cheerio/index.d.ts(147,20): error TS2304: Cannot find name 'Document'.
node_modules/@types/cheerio/index.d.ts(148,20): error TS2304: Cannot find name 'Document'.
node_modules/@types/cheerio/index.d.ts(152,26): error TS2304: Cannot find name 'Document'.
node_modules/@types/cheerio/index.d.ts(156,21): error TS2304: Cannot find name 'Document'.
node_modules/@types/cheerio/index.d.ts(157,21): error TS2304: Cannot find name 'Document'.
node_modules/@types/cheerio/index.d.ts(161,27): error TS2304: Cannot find name 'Document'.
node_modules/@types/cheerio/index.d.ts(239,39): error TS2304: Cannot find name 'Document'.
node_modules/@types/cheerio/index.d.ts(239,73): error TS2304: Cannot find name 'Document'.

**Comment by Kovensky** [comment]
You need to use `--lib dom`
