### ISSUE TITLE
@types/angular JQuery in jqlite.d.ts doesn't have index signature

### ISSUE THREAD

**Issue by RIAstar** [DefinitelyTyped/DefinitelyTyped#17772]
- [x] I tried using the `@types/angular` v1.6.25 package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/). 
- [x] Caused by PR #17304 
  - Authors: @leonard-thieu 

The JQuery interface in jqlite.d.ts doesn't have an index signature. As a consequence the compiler throws an error when `noImplicitAny` is on and you want to access the underlying HTML `Element`(s).

Example:
```
// error: Element implicitly has 'any' type because type 'JQuery' has no index signature.
const logElement = (el: JQuery) => console.log( el[0] );
```
Obviously, the same happens with `IAugmentedJQuery`.

**Comment by eseliger** [comment]
Same here, 

`[n: number]: HTMLElement`

is missing on type `JQuery`

Current @types/jquery typings have it here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/HEAD/types/jquery/index.d.ts#L2394

**Comment by leonard-thieu** [comment]
Being worked on by #17676 although we're running into issues.

If you need a workaround, you can add `@types/jquery` v2 or v3 depending on your needs.
