### ISSUE TITLE
@types/ramda/index"' has no exported member 'pipeP'

### ISSUE THREAD

**Issue by ds82** [DefinitelyTyped/DefinitelyTyped#17796]
- [x] I tried using the `@types/ramda` package and had problems.

```
tsc --version                                                                                                                                                                          
Version 2.4.1
node --version                                                                                                                                                                         
v6.10.2
npm --version                                                                                                                                                                        
5.0.3
cat node_modules/@types/ramda/package.json | jq ".version"                                                                                                                           
"0.24.1"
cat node_modules/ramda/package.json | jq ".version"
"0.24.1"
```

```
~/c/reapi-node ❯❯❯ ts-node examples/set-add-label-object-or-content.ts                                                                                                                                    

/Users/dsaenger/.nvm/versions/node/v6.10.2/lib/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/modules/label.ts (18,3): Module '"/Users/dsaenger/code/reapi-node/node_modules/@types/ramda/index"' has no exported member 'pipeP'. (2305)
    at getOutput (/Users/dsaenger/.nvm/versions/node/v6.10.2/lib/node_modules/ts-node/src/index.ts:307:15)
    at /Users/dsaenger/.nvm/versions/node/v6.10.2/lib/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/Users/dsaenger/.nvm/versions/node/v6.10.2/lib/node_modules/ts-node/src/index.ts:496:11)
    at Module.m._compile (/Users/dsaenger/.nvm/versions/node/v6.10.2/lib/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/dsaenger/.nvm/versions/node/v6.10.2/lib/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dsaenger/code/reapi-node/src/index.ts:13:1)
    at Module._compile (module.js:570:32)
    at Module.m._compile (/Users/dsaenger/.nvm/versions/node/v6.10.2/lib/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/dsaenger/.nvm/versions/node/v6.10.2/lib/node_modules/ts-node/src/index.ts:395:12)
```

- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @donnut @mdekrey @LiamGoodacre @mrdziuban @sbking @afharo

``pipeK`` is missing as well

**Comment by ds82** [comment]
Also missing:

``mergeDeepLeft``, ``mergeDeepWith``, ``mergeDeepRight``, ``mergeDeepWithKey``

**Comment by BjornMelgaard** [comment]
why so long

**Comment by BjornMelgaard** [comment]
[npm-ramda](https://github.com/types/npm-ramda/) has following types

**Comment by gunzip** [comment]
as a new ramda user it's not clear if the typings in DefinitelyTyped are deprecated in favour of npm-ramda ones. what's the relation between the two projects ?

**Comment by BjornMelgaard** [comment]
@gunzip they are coexisting, though: 1) imho, npm-ramda typings more elaborate, 2) imhhhhho, programming on typescript using ramda is ineffective

**Comment by jeffrose** [comment]
It would be great if the two initiatives could come together.

**Comment by BjornMelgaard** [comment]
@jeffrose it's impossible, npm-ramda typings are generated programmatically https://github.com/ikatyang/dts-element

**Comment by tycho01** [comment]
@srghma I don't think that was the reason, afaik we'd intended to have the `dist` branch pushed to DT, see https://github.com/types/npm-ramda/issues/191.

but yeah, the intent had been to get the typings reconciled, as admittedly the end user shouldn't have to worry about where to look for typings.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
