### ISSUE TITLE
@types/google-cloud__storage doesn't actually work

### ISSUE THREAD

**Issue by esprehn** [DefinitelyTyped/DefinitelyTyped#17818]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @blove @mlegenhausen

The export of the @google-cloud/storage module is the Storage object itself, not a namespace. 

So if you do:

```
import Storage = require('@google-cloud/storage');
```

and then try to create an instance like:

```
new Storage({ ... })
```

it fails because the types have it exporting a namespace of types, not the Storage object itself.

Also note that the test is all wrong here, it imports a bunch of stuff that doesn't actually exist. It passes given the types, but doesn't match what the library does at all:

https://github.com/blove/DefinitelyTyped/blob/c3d08f7d2e4473b36cae15ebfa82cd442ce1e0fa/types/google-cloud__storage/google-cloud__storage-tests.ts

```
import {
  // ...
  Storage
} from "@google-cloud/storage";
```

but Storage here is undefined with the real @google-cloud/storage code. Since it exports the constructor function for "Storage", with expandos for the other types.

**Comment by alvis** [comment]
As far as I know, the same issue has been raised in the related PR #15155 #16452. I hope @blove would have time to have a look. It would be very much appreciated. 😃

**Comment by baronfel** [comment]
I've submitted a PR that fixes the typings for my use case. Can others take a look?

**Comment by pedrosanta** [comment]
Also, tried to use this type and with was failing to compile on `bucket.upload` when I provided a callback, which is optional, forcing me to use the Promise.

Docs state that callback is optional, this should be supported on type, IMHO.

**Comment by sethetter** [comment]
I seem to be getting a collision between the `Storage` namespace and the `Storage` type [defined in this TypeScript ES6 lib file](https://github.com/Microsoft/TypeScript/blob/a6555921f4b1d51281b1241c69e91e5b82d2f07e/lib/lib.es6.d.ts#L15457-L15471). Has anyone run into this before? @baronfel any ideas here?

**Comment by Methodician** [comment]
I guess google cloud has introduced its own typings?
It still feels funky... if I just
`npm uninstall @types/google-cloud__storage`
and instead:
```
import { Storage } from '@google-cloud/storage';
const gcs = Storage.prototype;

//inside some function
const bucket = gcs.bucket(fileBucket);
```
now everything is working, but this feels hacky and unfamiliar - a pattern I haven't seen/used and just accidentally typed at whim.

Have I stumbled across the right way to use inherent typings provided by google-cloud or could someone tell me the right way?

**Comment by baronfel** [comment]
That's correct, newer versions of the google cloud libraries ship typings with them. You should no longer need this set of external typings. See https://github.com/googleapis/nodejs-storage/blob/master/package.json#L12.

**Comment by Methodician** [comment]
In case anyone else comes across this, the way I did it above didn't actually work. I find a lot of conflicting documentation right now, I guess while everyone catches up, but this from the official `@google-cloud/storage` docs worked while the Firebase docs I looked at were way off:

Correct approach (the name `gcs` is of course arbitrary):
```
import { Storage } from '@google-cloud/storage';
const gcs = new Storage();
```
