### ISSUE TITLE
[RFC] D3 Migration Strategy to Support TS2.2/2.3

### ISSUE THREAD

**Issue by tomwanzek** [DefinitelyTyped/DefinitelyTyped#17846]
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek @gustavderdrache  @Ledragon 

This issue is created as a Request for comment to develop a migration strategy for the core D3 module definitions to support TS 2.3 and/or TS 2.2. It is intended to serve as a basis for assessing the:
* impact of breaking changes introduced with TS 2.2/2.3 compared to the current TS 2.0/2.1 supporting definitions
* new language features to take advantage off
* effort/strategy for creating new definitions to support TS 2.2/2.3
* effort/transition plan for any parallel support of definitions for TS 2.2/2.3 and TS 2.0/2.1

and any related cost/benefit and risk considerations.

I would suggest we first create a discussion template to categories the relevant considerations and then work through them to come up with an approach to address them.

@andy-ms I hope we can draw on your expertise for some targeted feedback as we determine the best path forward.

cc @btelles

**Comment by andy-ms** [comment]
> effort/transition plan for any parallel support of definitions for TS 2.2/2.3 and TS 2.0/2.1

We don't support having multiple versions of a definition for different versions of TypeScript. There is a minimum TS version, and all TS versions above that should be supported.

If a package doesn't actually need any new features, I would recommend staying on an older version. We can still run tests against newer versions (see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17626#issuecomment-313691100). (But if a package's dependency uses a newer TS version, the package must declare a newer version too.)

If you do want to use a newer version of TS, that must become the only version of the definitions. So `@types/d3@ts2.0` would become frozen and all future updates would be ts2.2+ only.

**Comment by Ledragon** [comment]
As I have not been following the latest TS updates and breaking changes, are we now in a situation where existing types do not work anymore with TS 2.2+ ?

**Comment by tomwanzek** [comment]
Closed in favor of consolidated tracking issue #23611.
