### ISSUE TITLE
@types/ioredis is missing sscanStream

### ISSUE THREAD

**Issue by kdcro101** [DefinitelyTyped/DefinitelyTyped#17865]
- [ x ] I tried using the `@types/xxxx` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @satoshun00 @andy-ms

ioredis is missing  sscanStream(key:string, options?: IORedis.ScanStreamOption): NodeJS.EventEmitter;

**Comment by satoshun00** [comment]
:+1:
It is also missing some `command + "Stream"` functions.
https://github.com/luin/ioredis/blob/master/lib/redis.js#L622
