### ISSUE TITLE
[react native] Wrong type definition for Route

### ISSUE THREAD

**Issue by RoryCombe** [DefinitelyTyped/DefinitelyTyped#17928]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy, @gyzerok, @huhuanming, @jeremistadler

The current type definition for `Route` (see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L4572) is:
```
export interface Route {
  component?: React.ComponentClass<ViewProperties>;
  ...
```
which generates an error when providing a stateless component as the Route's component. Proposed fix should be:
```
export interface Route {
  component?: React.ComponentClass<ViewProperties>  | React.StatelessComponent<ViewProperties>;
  ...
```
Then the compile error goes away. I'm new to using TypeScript with React Native, but happy to submit a PR if my assumptions are correct.

Btw, thanks for the great typings library - as a new user I really appreciate being able to just npm install and have all this magic out of box 🙏

**Comment by huhuanming** [comment]
Or like this?

`React.ComponentClass<ViewProperties> | React.ReactElement<ViewProperties> | (() => React.ReactElement<ViewProperties>) | null`

**Comment by RoryCombe** [comment]
@huhuanming Thanks for the quick reply. I seem to still get the compile error then:
```
 Types of property 'component' are incompatible.
    Type '(props: any) => Element' is not assignable to type 'ComponentClass<ViewProperties> | ReactElement<ViewProperties> | (() => ReactElement<ViewPropertie...'.
      Type '(props: any) => Element' is not assignable to type '() => ReactElement<ViewProperties>'.
```
Perhaps I am missing something or doing something wrong? This is my basic stateless component:
```
import * as React from 'react';
import EventsList from './eventsList';

export const PreviousEventsList = (props) => (
  <EventsList {...props} previousEvents />
);

export default PreviousEventsList;
```
And I am simply `push`ing onto a `Navigator` view like this:
```
this.props.navigator.push({
  title: 'Previous Events',
  component: PreviousEventsList,
  passProps: {},
});
```

**Comment by RoryCombe** [comment]
Just a question, but wouldn't the React class interfaces (`StatelessComponent`, `ComponentClass` and `ClassicComponentClass`) suffice in this case? Or is it not that simple?
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L276

**Comment by alloy** [comment]
@RoryCombe I believe you are correct, but I think we should just use `ComponentType`, as defined [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e545c1e19aa728dbf855ec719d8c8738d2eeff33/types/react/index.d.ts#L40).

**Comment by bodhi** [comment]
The same problem exists in FlatList/SectionList with `ItemSeparatorComponent`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
