### ISSUE TITLE
[angular] Unable to specify JSON-P callback parameter name on $http service json() method

### ISSUE THREAD

**Issue by flakey-bit** [DefinitelyTyped/DefinitelyTyped#17936]
As per https://docs.angularjs.org/api/ng/service/$http#jsonp -

"JSONP requests must specify a callback to be used in the response from the server. This callback is passed as a query parameter in the request. You must specify the name of this parameter by setting the jsonpCallbackParam property on the request config object."

The current typings do not allow this callback to be specified (no suitable property exists on angular.IRequestShortcutConfig)

**Comment by galuszkak** [comment]
This should be closed as #17937 is merged.
