### ISSUE TITLE
Select no longer has 'value' prop.

### ISSUE THREAD

**Issue by Unsttopabull** [DefinitelyTyped/DefinitelyTyped#17946]
- [x] I tried using the `@types/react` package and had problems (latest v15.0.37).
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Select element no longer has `value` prop.

`Error:(54, 41) TS2339:Property 'value' does not exist on type 'DetailedHTMLProps<SelectHTMLAttributes<HTMLSelectElement>, HTMLSelectElement>'.`

A simple fix is to just add `value` to `SelectHTMLAttributes<T>`.

**Comment by ypresto** [comment]
Maybe related: #17921

**Comment by nvdbleek** [comment]
Hi `alt` is also missing on AnchorHTMLAttributes. What is the process to get this fixed?

**Comment by Woodahs** [comment]
As far as I know, the anchor element has no 'alt' attribute, you should probably use title instead.

**Comment by nvdbleek** [comment]
@Woodahs thank you for the fast reply, we are going to change it to title.

**Comment by Unsttopabull** [comment]
Fixed in #4fd96da0fe213d4948b5800628510ea5e8fcaa63.
