### ISSUE TITLE
jquery's $.getScript() is not compatible with PromiseLike

### ISSUE THREAD

**Issue by Kovensky** [DefinitelyTyped/DefinitelyTyped#17966]
```ts
import $ from 'jquery'
Promise.resolve($.getScript(''))
```

```
Argument of type 'jqXHR<string | undefined>' is not assignable to parameter of type 'string | PromiseLike<string | undefined> | undefined'.
  Type 'jqXHR<string | undefined>' is not assignable to type 'PromiseLike<string | undefined>'.
    Types of property 'then' are incompatible.
      Type '{ <ARD = never, AJD = never, AND = never, BRD = never, BJD = never, BND = never, CRD = never, CJD...' is not assignable to type '<TResult1 = string | undefined, TResult2 = never>(onfulfilled?: ((value: string | undefined) => T...'.
```

This seems to affect any `jqXHR` whose generic argument is not assignable to `object`.

**Comment by leonard-thieu** [comment]
Works with 
- `object`
- `Object`
- `{}`
- `any`

Seems to fail with anything that has additional properties. This affects anything that extends from `Promise3` (which includes `Promise2` and `jqXHR`). This doesn't affect `JQuery.Promise` which is defined similarly (but not exactly) to `Promise3`.

I don't understand why this happens. We could change `getScript` to return just `jqXHR` instead as a workaround. That still leaves the underlying issue unsolved though.

**Comment by Kovensky** [comment]
It also worked when I tried `{ toString(): string }`, which is why I expected it to work with things assignable to `object` but I guess the range is smaller than expected.
