### ISSUE TITLE
Property 'kendoGrid' does not exist on type 'JQuery<HTMLElement>

### ISSUE THREAD

**Issue by vimalraj-a** [DefinitelyTyped/DefinitelyTyped#17973]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

I am using VSCode editor for my angular project development. VSCode intellisense is working fine with typings/kendo-ui. But, Webpack compilation failed due to the error. 
**Error:**
> "Property 'kendoGrid' does not exist on type 'JQuery<HTMLElement>"

I am using latest angular CLI for this project.

@afftee

**Comment by hanssens** [comment]
@vimalraj-a As it is currently stated, it looks like an implementation-specific question rather than a definition type problem. To me, your question seems to be better suited on something like [StackOverflow](https://stackoverflow.com/) rather than in this repo. 

As a tip: considering you're using Kendo's Grid,  you'll probably have a support agreement because the grid is part of the pro edition. Telerik/Kendo support might also help you further.

**Comment by vimalraj-a** [comment]
This error is same for all kendo components. I have posted the stackoverflow question.
https://stackoverflow.com/questions/45074109/property-kendogrid-does-not-exist-on-type-jqueryhtmlelement

**Comment by rajdeep26** [comment]
@vimalraj-a how did you fix this error? I am also facing a similar issue.

Vscode is not showing any error but webpack compilation fails.

**Comment by vimalraj-a** [comment]
Webpack doesn't respect typings(in my understanding). So, I created separate ts file and added 

`decalre var $: any`

But, Above will be a problem if your work folder has jquery typings. I still don't have solution for this.

**Comment by jay-thanki** [comment]
@vimalraj-a 
> Webpack doesn't respect typings(in my understanding). So, I created separate ts file and added
> 
> `decalre var $: any`
> 
> But, Above will be a problem if your work folder has jquery typings. I still don't have solution for this.

sorry to say but there is a mistake 

it should be 

> declare var $: any; 

not 

> decalre var $: any

**Comment by Basit5159** [comment]
> maybe
> ` (<any>$("#grid")).kendoGrid()`
> could help?

it works for me   :)
but we have to apply a less like this 

-- import --
import * as $ from 'jquery';
import 'lightgallery';
import 'lg-zoom';

-- using --
ngOnInit(): void {
    ($('#lightgallery') as any).lightGallery();
}

yessss i am very happy .

thank you very mush sir
