### ISSUE TITLE
Leaflet -- Typescript 2.4.1 breaks reference to GeoJSON

### ISSUE THREAD

**Issue by TimHambourger** [DefinitelyTyped/DefinitelyTyped#17979]
I get compiler errors using `@types/leaflet` w/ Typescript 2.4.1
- Author: @alejo90 

Stack:
- typescript@2.4.1
- `@types/leaflet`@1.0.65
- `@types/geojson`@1.0.2

tsc gives errors around not finding GeoJSON:

```
ERROR in C:\Users\Tim\xxx\node_modules\@types\leaflet\index.d.ts
(12,25): error TS2503: Cannot find namespace 'GeoJSON'.

ERROR in C:\Users\Tim\xxx\node_modules\@types\leaflet\index.d.ts
(13,28): error TS2503: Cannot find namespace 'GeoJSON'.

ERROR in C:\Users\Tim\xxx\node_modules\@types\leaflet\index.d.ts
(14,33): error TS2503: Cannot find namespace 'GeoJSON'.

ERROR in C:\Users\Tim\xxx\node_modules\@types\leaflet\index.d.ts
(15,25): error TS2503: Cannot find namespace 'GeoJSON'.

ERROR in C:\Users\Tim\xxx\node_modules\@types\leaflet\index.d.ts
(16,30): error TS2503: Cannot find namespace 'GeoJSON'.

ERROR in C:\Users\Tim\xxx\node_modules\@types\leaflet\index.d.ts
(17,35): error TS2503: Cannot find namespace 'GeoJSON'.

ERROR in C:\Users\Tim\xxx\node_modules\@types\leaflet\index.d.ts
(18,32): error TS2503: Cannot find namespace 'GeoJSON'.

ERROR in C:\Users\Tim\xxx\node_modules\@types\leaflet\index.d.ts
(19,36): error TS2503: Cannot find namespace 'GeoJSON'.

ERROR in C:\Users\Tim\xxx\node_modules\@types\leaflet\index.d.ts
(20,23): error TS2503: Cannot find namespace 'GeoJSON'.

ERROR in C:\Users\Tim\xxx\node_modules\@types\leaflet\index.d.ts
(21,28): error TS2503: Cannot find namespace 'GeoJSON'.

ERROR in C:\Users\Tim\xxx\node_modules\@types\leaflet\index.d.ts
(22,31): error TS2503: Cannot find namespace 'GeoJSON'.

ERROR in C:\Users\Tim\xxx\node_modules\@types\leaflet\index.d.ts
(6,23): error TS2688: Cannot find type definition file for 'geojson'.
```

Note that I DO have the geojson package in my `node_modules/@types` folder and that using typescript@2.4.0 compiles w/o issue.

I also tried different versions of `@types/geojson` and `@types/leaflet` to try to work around the issue. The one fix I found was to go back to `@types/leaflet`@0.7.28, which predates the dependency on `@types/geojson`. But that's a significantly different version of the typings which caused other compiler errors downstream.

**Comment by Kovensky** [comment]
Trying to read the leaflet definitions; I have no idea why they're using triple-slash instead of import to refer to geojson 😨

**Comment by alejo90** [comment]
@TimHambourger I'm using Typescript 2.4.1 and @types/leaflet@1.0.65 on a big project and I'm not seeing any issues. I have had problems when updating Typescript versions in the past and not only with the leaflet typing. What I ended up doing was adding this to my tsconfig:

```
"baseUrl": "types",
"typeRoots": [
    "types",
    "node_modules/@types"
]
```

Haven't had issues ever since.

**Comment by TimHambourger** [comment]
@alejo90 Ah! I build my project w/ webpack using the ts-loader, and my version of ts-loader was quite old (0.8.2). Updating to latest (2.2.2) solved my issue.

Thanks for the feedback. I'll close this one out.

**Comment by TimHambourger** [comment]
BTW, relevant discussion about what was going on w/ ts-loader:
https://github.com/TypeStrong/ts-loader/issues/565

**Comment by aluanhaddad** [comment]
> Trying to read the leaflet definitions; I have no idea why they're using triple-slash instead of import to refer to geojson 😨

@Kovensky yes that is a source of much frustration. It is poor style and it prevents path mapping from being used.

To make matters worse, many packages that extend leaflet reference _it_ as a global, polluting the entire ecosystem of packages.

Examples include

[leaflet-curve](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet-curve/index.d.ts)

[leaflet-fullscreen](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet-fullscreen/index.d.ts)

and even

[esri-leaflet](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/esri-leaflet/index.d.ts)

I submitted a PR to fix this a while back but it was rejected.
