### ISSUE TITLE
@types/react in latest TSC 2.4.1 React.createElement('img', { src: string }) does not work

### ISSUE THREAD

**Issue by micnic** [DefinitelyTyped/DefinitelyTyped#18019]
- [x] I tried using the `@types/react` package and had problems. Version 15.0.38
- [x] I tried using the latest stable version of tsc. TypeScript 2.4.1

When trying the following code:
```ts
const logo = React.createElement('img', {
    src: 'logo.png'
});
```
I get this error:
`Argument of type '"img"' is not assignable to parameter of type 'ComponentClass<{ src: string; }>'.`

![image](https://user-images.githubusercontent.com/1449826/28163743-1bde8bae-67d5-11e7-9fc7-d5c08b558fbe.png)

When adding `className` prop it works fine:
```ts
const logo = React.createElement('img', {
    className: 'logo',
    src: 'logo.png'
});
```

cc @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz

**Comment by manugill** [comment]
Running into the same issue.

Seems like at least one of the keys of interface HTMLAttributes has to be defined for the error to go away.

**Comment by micnic** [comment]
I tried to dive in to the typings but could not find any clues. This issues looks to happen because of the stricter rules introduced in TS 2.4 for generics.

**Comment by ericanderson** [comment]
Feel free to put in a PR for an overload of first arg ‘img’

**Comment by don-p** [comment]
Running into this issue as well.

Looking at the code, the typings seems to assume the only element type created by string will be "input".  And there is a comment:
```
    // DOM Elements
    // TODO: generalize this to everything in `keyof ReactHTML`, not just "input"
    function createElement(
```

Is this on a roadmap to address?

**Comment by micnic** [comment]
This issue seems to be fixed.
