### ISSUE TITLE
[@types/handlebars] error 4.0.34

### ISSUE THREAD

**Issue by nadircan** [DefinitelyTyped/DefinitelyTyped#18025]
- [x] I tried using the `@types/handlebars` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

I am using types/handlebars at my project. Today my project cant build. I am getting error like this.

ERROR in [at-loader] node_modules\@types\handlebars\index.d.ts:22:31 
    TS1005: ',' expected.

ERROR in [at-loader] node_modules\@types\handlebars\index.d.ts:24:32 
    TS1005: ',' expected.

ERROR in [at-loader] node_modules\@types\handlebars\index.d.ts:99:40 
    TS1005: ',' expected.

ERROR in [at-loader] node_modules\@types\handlebars\index.d.ts:22:33 
    TS2368: Type parameter name cannot be 'any'

ERROR in [at-loader] node_modules\@types\handlebars\index.d.ts:22:77 
    TS2314: Generic type 'HandlebarsTemplateDelegate<T, any>' requires 2 type argument(s).

ERROR in [at-loader] node_modules\@types\handlebars\index.d.ts:24:34 
    TS2368: Type parameter name cannot be 'any'

ERROR in [at-loader] node_modules\@types\handlebars\index.d.ts:24:79 
    TS2314: Generic type 'HandlebarsTemplateDelegate<T, any>' requires 2 type argument(s).

ERROR in [at-loader] node_modules\@types\handlebars\index.d.ts:96:15 
    TS2314: Generic type 'HandlebarsTemplateDelegate<T, any>' requires 2 type argument(s).

ERROR in [at-loader] node_modules\@types\handlebars\index.d.ts:99:42 
    TS2368: Type parameter name cannot be 'any'

ERROR in [at-loader] node_modules\@types\handlebars\index.d.ts:104:22 
    TS2314: Generic type 'HandlebarsTemplateDelegate<T, any>' requires 2 type argument(s).

ERROR in [at-loader] node_modules\@types\handlebars\index.d.ts:115:34 
    TS2314: Generic type 'HandlebarsTemplateDelegate<T, any>' requires 2 type argument(s).

**Comment by jariztia** [comment]
I'm building a project that worked fine and today is throwing this same error. Please let me know if you find the solution.

**Comment by jariztia** [comment]
@nadircan I just made it work setting the version of @types\handlebars in the package.json to "4.0.33":

"@types/handlebars": "4.0.33",

The problem occurred wih the las verison (4.0.34) released yesterday.

**Comment by nadircan** [comment]
@jariztia thanks for solution. I will try my project and write result.

**Comment by kolisko** [comment]
have the same error since today..

**Comment by jariztia** [comment]
@kolisko It's because of @types\handlebars new version (4.0.34). To bypass this just set the version in the package.json to 4.0.33 like this:
`"@types/handlebars": "4.0.33",`

**Comment by orkisz** [comment]
Jumping to new version of TS should result a major version bumping in this case. Do the author(s) plan to resolve the issue in order to remove this ugly version locking hack?

**Comment by Remper** [comment]
@Kovensky please remove the Typescript 2.3-specific code and release 4.0.35

**Comment by Kovensky** [comment]
As far as I know there is no semver with typings -- the major and minor version numbers are intended to track the supported package's major version number (in this case, handlebars 4.0), with `patch` just being a counter for updates.

The type definition was written with TS 2.3 syntax specifically to maintain backwards compatibility with existing _code_. I could remove the TS 2.3 syntax, but it would break handlebars-using code for everyone, even people that are not sticking to old compilers. The template argument for `Handlebars.compile()` would default to `{}` at compilation time so excess property check would never allow you to pass anything.

**Comment by snow-dev** [comment]
I just remove the folder ./handlebars inside @types, then: `npm install @types/handlebars@4.0.33` all inside /@types,  so it fix from me.

**Comment by lwlewy** [comment]
In my case this happened with quite a few DefinitelyTyped packages, so it was easier to lock the TypeScript to 2.3.4 :disappointed:

**Comment by BendingBender** [comment]
Use either latest [npm](https://www.npmjs.com/get-npm) version or [yarn](https://yarnpkg.com/en/docs/install) to manage lockfiles for your packages automatically. You won't ever have to pin packages again. And a once working configuration won't break until you explicitly decide to upgrade.

**Comment by Remper** [comment]
It's just frustrating to see that part of the npm community is okay with not following semver for whatever reason and decides to arbitrarily break backwards compatibility based on some time-based notion.

I mean yes, I could pin a version (for direct dependencies and the deps of the deps, like I had to in my case) or I could use lockfiles, but do we really want to have such a fragile system, where any patch can throw you into the dependency hell?

Now is probably too late to do anything, so I suggest closing this issue and just accepting the fact that the dependencies should be pinned down at all times for npm.

**Comment by hbweb** [comment]
I've figured it out by just change typescript version in package.json to 

``` "typescript": "^2.4.2", ```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
