### ISSUE TITLE
@types/mongoose: Property 'equals' does not exist on type 'ObjectId'

### ISSUE THREAD

**Issue by polo2ro** [DefinitelyTyped/DefinitelyTyped#18040]
- [x] I tried using the `@types/mongoose` package and had problems.

the equals method on an ObjectId allow to compare 2 objects ID but is not in the typescript definition file

**Comment by polo2ro** [comment]
sorry, i fixed this using Types.ObjectId instead of Schema.Types.ObjectId

**Comment by cvharris** [comment]
@polo2ro I got this same thing, and I'm pulling from `Types.ObjectId`. What does your code example look like?

```js
import { Types } from 'mongoose'
// ...
children.filter((child: Types.ObjectId) => !child.equals(new Types.ObjectId(taskId)))
```
Typescript says `equals does not exist on type ObjectId`

**Comment by polo2ro** [comment]
in my code:
`if (message.from.id.equals(c.userId) || message.to.id.equals(c.userId)) {
`
where c.userId:string and message.from.id:Types.ObjectId

in package.json:
`"@types/mongoose": "^4.7.18", `

i can't remember any other trick used to make it work
