### ISSUE TITLE
I am using a CEAN app. Following errors appear when I am trying to run npm start for angular:

### ISSUE THREAD

**Issue by himanshuranjan4489** [DefinitelyTyped/DefinitelyTyped#18066]
../node_modules/@types/bluebird/index.d.ts(50,17): error TS1005: ',' expected.
../node_modules/@types/bluebird/index.d.ts(50,31): error TS1005: ',' expected.
../node_modules/@types/bluebird/index.d.ts(1079,59): error TS1005: ']' expected.
../node_modules/@types/bluebird/index.d.ts(1079,60): error TS1005: ';' expected.
../node_modules/@types/bluebird/index.d.ts(1079,61): error TS1128: Declaration or statement expected
.
../node_modules/@types/bluebird/index.d.ts(1079,81): error TS1109: Expression expected.
../node_modules/@types/bluebird/index.d.ts(1164,1): error TS1128: Declaration or statement expected.

============================= 

[2017-07-14T13_29_56_054Z-debug.txt](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1148532/2017-07-14T13_29_56_054Z-debug.txt)
[package.json_forAngular.txt](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1148537/package.json_forAngular.txt)
[package.json_forExpress.txt](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1148536/package.json_forExpress.txt)

============================= 

Command: npm -v Results : 4.2.0
Command: node -v Results : v7.8.0
Command: tsc -v Results : Version 2.3.4

**Comment by himanshuranjan4489** [comment]
After some investigation I understood that the problem occurred because I had installed some libraries for Server. After careful installation of modules, I came to know that express-validator has following dependencies:

```
`-- express-validator@3.2.1
  +-- @types/bluebird@3.5.8
  +-- @types/express@4.0.36
  | +-- @types/express-serve-static-core@4.0.49
  | | `-- @types/node@8.0.13
  | `-- @types/serve-static@1.7.31
  |   `-- @types/mime@1.3.1
  +-- bluebird@3.5.0
  +-- lodash@4.17.4
  `-- validator@6.2.1
```
  
Therefore express-validator added bluebird which was causing issue with typescript.
After my further research I understood that I need to use typescript "2.3.2". Therefore, I also modified and installed typescript version "2.3.2" for angular.

Now my problem got resolved but still I have a question.

Why client(Angular/Typescript) is causing problem for a module which is installed for Server(Express) because both of them have their own node_modules folders? How they are related? May be its a trivial question, but I lack this concept.

Thanks in advance for a detailed answer.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
