### ISSUE TITLE
[jQuery] Masonry and jQuery 3.0 fail definition

### ISSUE THREAD

**Issue by ppprevost** [DefinitelyTyped/DefinitelyTyped#18132]
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

I try to update my project that using @types Masonry-layout. 
Jquery is a dependancy and use jquery 2. 
Masonry-layout use jquery 2.0 s a depedancy but put * in th package.json.
Unfortunally  when we install jquery dependancy it install the latest version of jquery (3.0) and not compatible with masonry. 

Please help

**Comment by leonard-thieu** [comment]
In your `package.json`, change `@types/jquery` to the following version:

```json
"@types/jquery": ">=2 <2.2"
```

**Comment by ppprevost** [comment]
thx i will try it
