### ISSUE TITLE
@types/react-router-dom - Namespace 'React' has no exported member 'AnchorHTMLAttributes'

### ISSUE THREAD

**Issue by vitalybaev** [DefinitelyTyped/DefinitelyTyped#18133]
- [x] I tried using the `@types/react-router-dom@4.0.7` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkrotoff @huy-nguyen 

See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-router-dom/index.d.ts#L42

**Comment by JaroInside** [comment]
First of all, I am not good at English and I do not know if I can explain properly.


I had the same problem.
I have looked at the d.tsx file in @ types / react to solve the problem

Interface AnchorHTMLAttributes <T> extends HTMLAttributes <T> {
         Download ?: any;
         Href ?: string;
         HrefLang ?: string;
         Media ?: string;
         Rel ?: string;
         Target ?: string;
  }

I found that the part was missing,
This is done by removing all nodemodules and installing them again.
(To be precise, I used create-react-app typescript to create a new project.)

**Comment by vitalybaev** [comment]
@JaroInside Thanks, I've reinstalled modules and it's indeed fixed.

**Comment by pixelpax** [comment]
Worked for me too. Remember to cut from `yarn.lock` if you're using it, y'all :)
