### ISSUE TITLE
[jquery] isEmptyObject type guard to never

### ISSUE THREAD

**Issue by Mmdixon** [DefinitelyTyped/DefinitelyTyped#18149]
Typescript narrows the user-defined type guard of `isEmptyObject` signature to `never` for `else` or not `!` cases. Example:
```
interface Record {
    name: string;
    value: string;
}

function example(record: Record) {
    if ($.isEmptyObject(record)) {
        // record is of type Record
    } else {
        // record if of type never
    }
}
```
Unfortunately, the interesting case is when the object is not empty.

Tested with
```
"typescript": "^2.4.1",
"@types/jquery": "^3.2.8",
```
Relevant PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17513/commits/6fa5e4bc987d947b14f26c3c7b4e631b1fe40cb1
Authors: @leonard-thieu

**Comment by leonard-thieu** [comment]
That's unfortunate.

Will be fixed by PR #18172.
