### ISSUE TITLE
ComponentInterface propTypes should be optional.

### ISSUE THREAD

**Issue by admmasters** [DefinitelyTyped/DefinitelyTyped#18152]
- [ ] I tried using the `@types/react-native` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/react-native

ComponentInterface for react-native requires propTypes which isn't correct, I have created a PR to make this optional: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18151

**Comment by iRoachie** [comment]
Close @alloy
