### ISSUE TITLE
@types/i18next-express-middleware

### ISSUE THREAD

**Issue by TitaneBoy** [DefinitelyTyped/DefinitelyTyped#18176]
- [x] I tried using the `@types/i18next-express-middleware` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

@cyrilschumacher

Hi...I've recently updated the defenitely type file of the i18next-express-middleware to the last version (0.0.31) and unfortunetly, I have a typescript error.

Here is the error I have:
```
[ts]
Argument of type 'i18n' is not assignable to parameter of type 'I18n'.
  Types of property 'init' are incompatible.
    Type '{ (options: InitOptions, callback?: Callback): i18n; (callback?: Callback): i18n; }' is not assignable to type '(options?: Options & ReactOptions, callback?: (err: any, t: TranslationFunction) => void) => I18n'.
      Types of parameters 'options' and 'options' are incompatible.
        Type 'Options & ReactOptions' is not assignable to type 'InitOptions'.
          Types of property 'load' are incompatible.
            Type 'string' is not assignable to type '"currentOnly" | "all" | "languageOnly"'
```

I didn't change my code at all..Just updated the types/i18next-express-middleware.

I looked up on the documentation of i18next-express-middleware and I'm doing exactly the same thing as described in the documentation..

Here is what I'm doing

```
import * as i18next from 'i18next';
import * as i18nextMiddleware from 'i18next-express-middleware';
import * as express from 'express';
...
const i18nextOptions: i18next.InitOptions = {
  backend: {
    addPath: path.join(process.cwd(), 'language/static/{{lng}}/{{ns}}.missing.json'),
    jsonIndent: 2,
    loadPath: path.join(process.cwd(), 'language/static/{{lng}}/{{ns}}.json')},
  debug: false,
  defaultNS: 'My_Web_Server',
  fallbackLng: 'false',
  keySeparator: false,
  load: 'currentOnly',
  ns: 'My_Web_Server',
  nsSeparator: false,
  preload: ['es', 'fr', 'zh-Hans'],
  saveMissing: true,
  saveMissingTo: 'current',
  whitelist: ['fr', 'es', 'zh-Hans'],
};

i18next
  .use(i18nextBackend)
  .init(i18nextOptions);

const httpsApp = express();
httpsApp.use(i18nextMiddleware.handle(i18next, {removeLngFromUrl: false}));
```
I have the typescript error described earlier in the last line with `i18nextMiddleware.handle(i18next,`, directly on the i18next variable.

Am I doing something wrong or is it possible there is an issue in your definitly type file ?

Thank you for your help ...

**Comment by TitaneBoy** [comment]
Based on the definition type of types/i18next and the code inside the i18nex middleware module, the i18next-express-middleware.handle function should take in parameter a variable of type i18next.i18n

**Comment by cyrilschumacher** [comment]
Hi! Thank you for this error. The library has been updated since that time, but not the definition. I looked your pull request and I accepted it.

Thanks for the update.
