### ISSUE TITLE
@types/node http.Server interface missing property keepAliveTimeout

### ISSUE THREAD

**Issue by StrikeForceZero** [DefinitelyTyped/DefinitelyTyped#18221]
I'm not sure if there is a global issue for tracking un-typed api added in node 8. (If one doesn't exist might be good to make one? Depending on how much new api was added and not currently typed in the repo)

- [Api Documentation (since node 8)](https://nodejs.org/api/http.html#http_server_keepalivetimeout)
- [Node types - interface http.Server (master)](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L791)
- [Node types - interface http.Server (last commit since opening issue)](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/da174820872d5b8786a3c70b29a4434be299d410/types/node/index.d.ts#L791)

```typescript
interface Server extends net.Server {
    //...
    keepAliveTimeout: number;
}
```

I'd have to take some time to look at the contribution guidelines before I could make a PR. 
Hoping someone may be able to toss it in.

**Comment by yume-chan** [comment]
Seems this property has already been added:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/afb4ff4cfb411a9b60c2952a9a6207c6b83be67c/types/node/index.d.ts#L1017-L1025

**Comment by StrikeForceZero** [comment]
Yup was added via https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18385

Closing.
