### ISSUE TITLE
[hapi] Typing for the server methods

### ISSUE THREAD

**Issue by DamodarSojka** [DefinitelyTyped/DefinitelyTyped#18283]
- [true] I tried using the `@types/xxxx` package and had problems.
- [true] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [true] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [true] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jasonswearingen . @AJamesPhillips 

I would like to ask if I am missing something obvious here or is the typing broken for server methods?
Typescript is not able to pickup the type of the server methods and always marks them as void.

Methods are typed during declaration. None of the two methods of exposing the method provides a valid typing:
server.method(methodName, method)
server.method(methodName, server.plugins[pluginName].methods[methodName])

Thanks in advance.

**Comment by AJamesPhillips** [comment]
Sorry I don't understand the question @DamodarSojka , can you give some example code and what you think it should do and what is currently does?

Also see the tests for an example of how to use this:  https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi/test/server/method.ts

**Comment by DamodarSojka** [comment]
Example of a method usage in my application:
Plugin is exposing typed functions: server.expose("methods", {X1, X2, X3});
In a different file the functions are declared as methods: server.method("MethodX1", server.plugins.PLUGINNAME.methods.X1);
The methods are then used in route handlers: req.server.methods.MethodX1(). When using method in the route handler (or anywhere else really!) the type is not properly passed, even when casting  as (req.server.methods.MethodX1() Promise<T>) - type "void" cannot be converted to type Promise<T>.

I hope this makes sense!

**Comment by AJamesPhillips** [comment]
@DamodarSojka right I think I understand.  Could you try out the fix above.  Not entirely sure why the void return type takes precedence.

**Comment by DamodarSojka** [comment]
@AJamesPhillips Works. The explicit type casting is properly working now. Few things are still not working however. The user of a method has to know the signature in order to set the casting. There is no way to "Go to declaration" as it points to Dictionary interface in the hapi.ts. I guess both of those issues are related to your comment "Not possible to improve this typing due to this unresolvable issue:  https://github.com/Microsoft/TypeScript/issues/15190". Do you think it will ever be working correctly? It is a pity hapi methods, a crucial part of the framework and it's foundations (modularity) isn't working.

**Comment by AJamesPhillips** [comment]
Hey @DamodarSojka good to hear.  The comment regarding "Not possible to improve this typing" is related to "Using rest parameter before other arguments in function signature".  The problem you're observing is because the methods attribute was set as a dictionary as opposed to a namespace you could extend.  I debated adding it at that time but decided against it as I didn't want the typings to be too difficult for beginners to get their heads around and change the typings too much for existing code bases.  One thing you could try if you don't want to do copy what's in the tests is something like this:


// server_methods.js

    type SyncX1 = (arg1: string): Promise<string>;

    interface Methods: {
        MethodSyncX1: SyncX1;
        MethodAsyncX1(callback: Hapi.ServerMethodNext): void;
    }

    export default (server: Hapi.Server): Methods => {
        return (server.methods as any as Methods);
    }

// your_script.js

    import methods from "./server_methods";

    methods(server).MethodSyncX1("arg1 value");
    // instead of:
    // (server.methods.MethodSyncX1  as SyncX1)("arg1 value");
