### ISSUE TITLE
[deep-freeze-strict] Cannot 'import', must use 'require' 

### ISSUE THREAD

**Issue by mattbishop** [DefinitelyTyped/DefinitelyTyped#18288]
- [X ] I tried using the `@types/xxxx` package and had problems.
- [ X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mhegazy

If I try to import this type module I get this error:
```import * as deepFreeze from "deep-freeze-strict";
Error:(6, 29) TS2497:Module '"/Users/mbishop/myProject/node_modules/@types/deep-freeze-strict/index"' resolves to a non-module entity and cannot be imported using this construct.
```

I have to use the old-school require:
```const deepFreeze = require("deep-freeze-strict");```

**Comment by andy-ms** [comment]
See the [README](https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default).

**Comment by mattbishop** [comment]
Thanks Andy!
