### ISSUE TITLE
react-modal is not exporting class as default

### ISSUE THREAD

**Issue by fangpenlin** [DefinitelyTyped/DefinitelyTyped#18366]
- [x] I tried using the `@types/react-modal` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @radziksh, @drewnoakes, @homburg, @ttamminen

Given a simple React app with `react-modal` types, like this

```jsx
// MyComponent.tsx
import * as React from 'react'
import * as ReactModal from 'react-modal'

export default class MyComponent extends React.Component {
  render () {
    return (
      <div>
        <ReactModal isOpen={false}>
          <div>Hi</div>
        </ReactModal>
      </div>
    )
  }
}
```

It compiles, but when you open it in browser, you will see error message like this

> React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `MyComponent`.

And if you print the imported module in console, you will find an esmodule like this

```
Object {__esModule: true, default: function}
```

Not sure if I understand this correct, I think overall, react-modal is somehow exported with `export equals` syntax like [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-modal/index.d.ts#L14), it exports the `ReactModal` namespace along with the `ReactModal` class type. However, as it's using `export equals` syntax, the whole module will be literal the object we assigned to it. As a result, we can only use

```js
import * as ReactModal from 'react-modal'
```

to import that module, you cannot do

```
import ReactModal from 'react-modal'
```

As it will complain

```
./@types/react-modal/index has no default export.
```

But if you read the source code of `react-modal`, it's [actually exporting as default](https://github.com/reactjs/react-modal/blob/master/src/index.js#L3)

In the end, our tsx code `MyComponent.tsx` is using `ReactModal` as the whole exported module object instead of its default, and react-modal js file is export default as the class, then react is accepting an es module object as the React component class.

Not sure what's the rationale of export with `export equals`, to fix this problem, maybe it should be exporting as default instead?

**Comment by fangpenlin** [comment]
Some more info,

ts version: 2.4.2
and config

```
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "commonjs",
        "target": "es5",
        "jsx": "react",
        "strictNullChecks": true,
        "experimentalDecorators": true
    },
    "include": [
        "./src/**/*"
    ]
}
```

**Comment by Kovensky** [comment]
It does remain as a default export even in the UMD bundle so there's no `add-module-exports` shenanigans going on (can we all just please stop using `babel-plugin-add-module-exports`).

https://github.com/reactjs/react-modal/blob/master/dist/react-modal.js#L49-L71

Changing it to `export default` in the definition would be correct.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
