### ISSUE TITLE
@types/xml2js  colliding with Node typings it seems

### ISSUE THREAD

**Issue by jrmcdona** [DefinitelyTyped/DefinitelyTyped#18391]
- [ x] I tried using the `@types/xml2js` package and had problems.

  - Authors: @michelsalib, @jasonrm 
  
After I installed xml2js typings,  I get a ton of errors with Node typings.

Here are a few samples.  Do I have a collision here?  Thanks

ERROR in C:/src/Xbox.Ambassadors/Microsoft.Ambassadors/Microsoft.Ambassadors.Webv2/src/server/node_modules/@types/node/index.d.ts (4128,22): Cannot redeclare block-scoped variable 'S_IXOTH'.

ERROR in C:/src/Xbox.Ambassadors/Microsoft.Ambassadors/Microsoft.Ambassadors.Webv2/src/server/node_modules/@types/node/index.d.ts (4427,18): Duplicate identifier 'TLSSocket'.

ERROR in C:/src/Xbox.Ambassadors/Microsoft.Ambassadors/Microsoft.Ambassadors.Webv2/src/server/node_modules/@types/node/index.d.ts (4794,10): Duplicate identifier 'Utf8AsciiLatin1Encoding'.

ERROR in C:/src/Xbox.Ambassadors/Microsoft.Ambassadors/Microsoft.Ambassadors.Webv2/src/server/node_modules/@types/node/index.d.ts (4795,10): Duplicate identifier 'HexBase64Latin1Encoding'.

ERROR in C:/src/Xbox.Ambassadors/Microsoft.Ambassadors/Microsoft.Ambassadors.Webv2/src/server/node_modules/@types/node/index.d.ts (4796,10): Duplicate identifier 'Utf8AsciiBinaryEncoding'.

ERROR in C:/src/Xbox.Ambassadors/Microsoft.Ambassadors/Microsoft.Ambassadors.Webv2/src/server/node_modules/@types/node/index.d.ts (4797,10): Duplicate identifier 'HexBase64BinaryEncoding'.

ERROR in C:/src/Xbox.Ambassadors/Microsoft.Ambassadors/Microsoft.Ambassadors.Webv2/src/server/node_modules/@types/node/index.d.ts (4798,10): Duplicate identifier 'ECDHKeyFormat'.

**Comment by jrmcdona** [comment]
Hmm,   I see the issue.  I have Node Typings installed in my server directory (expressJs).   I am wondering now why this conflict start happening after xml2js is installed in one of the parents.   

I assume becasue xml2js has installed node typings as a dependency.  

I could perhaps move my xml2js code to the Node layer instead of the Angular layer.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
