### ISSUE TITLE
react-loadable

### ISSUE THREAD

**Issue by thchia** [DefinitelyTyped/DefinitelyTyped#18398]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
 - Authors: @Kovensky @odensc

I'm not sure if this was the case originally, but `react-loadable` is now a scoped package `@humblespark/react-loadable`. In accordance to the rules of typing scoped packages, this ought to be renamed to `@types/humblespark__react-loadable`.

**Comment by odensc** [comment]
`react-loadable` isn't a scoped package. Where are you seeing this? `@humblespark/react-loadable` is just a fork of the official `react-loadable`. In fact, the scoped package is older and less active than the official one.

**Comment by thchia** [comment]
Ugh, no idea how I overlooked this. Apologies for wasting your time.

**Comment by odensc** [comment]
No problem.
