### ISSUE TITLE
[redux-form] reduxForm ConfigProps doesn't allow validation errors that don't contain initialValues

### ISSUE THREAD

**Issue by LyraelRayne** [DefinitelyTyped/DefinitelyTyped#18434]
- [x] I tried using the `@types/redux-form` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CarsonF, @aikoven  , @LKay, @bancek 

When using reduxForm with initial values as below, the typings for ConfigProps require that if initial values are specified, the errors object returned by validate must contain at least one key that is in the initialValues object in order to compile.

This doesn't work
```
import * as React from "react"
import { reduxForm } from "redux-form"

const required = (value: string | number) => value ? undefined : "Required"

reduxForm({
    form: "thing",
    initialValues: {
        something: "A something",
        another: "Another thing"
    },
    validate: (values, props) => {
        const errors = {
            bad: required(values.bad)
        }
        return errors
    }
})
```

this does work

```
/* ... */
reduxForm({
    form: "thing",
    initialValues: {
        something: "A something",
        another: "Another thing"
    },
    validate: (values, props) => {
        const errors = {
            something: required(values.something)
        }
        return errors
    }
})
```

**Comment by LKay** [comment]
This is correct behaviour. The code in first snippet won't work because you don't have `bad` key in your original `FormData` type which is in your case resolved from `initialValues` property. In the output for validate you can only specify keys which correspond to the `FormData` generic or `string` value for global error or `_error` key for special case.

The type for errors is:
```typescript
interface ErrorOther<T = void> {
    _error?: T;
}

type FormErrors<FormData = {}, T = void> = {
    [P in keyof FormData]?: ReactElement<any> | string | ErrorOther<T>;
};
```

**Comment by LyraelRayne** [comment]
I disagree that this is correct with regards to the semantics of redux-form.

The output of validate is, according to the docs, either {} or "the validation errors" (i.e. an object containing errors for fields *where an error occurred*). The input of initialValues is a list of fields where it is desirable to have an initial value, which may be Partial (correctly stated in the Typings).

It's perfectly valid semantically to not set an initial value for a field and have that field fail validation. The typings ought to reflect this. It also seems wrong that the type of FormData be determined by a field whose type is Partial<FormData>

Or am I just being incredibly dense and missing the correct spot to put FormData's complete data type so that Typescript knows all of the possible fields?

**Comment by LKay** [comment]
If you don't specify your type of `FormData` either explicitly by passing it to your `reduxForm` call or as part of properties on your component (which can be resolved by the compiler) the compiler tries to resolve it through your partial passed as initialValues. If compiler does that then it assumes that your partial reflects type for the whole form and because `bad` is not part of your partial compiler assumes it's also not part of the `FormData` generic.

**Comment by LKay** [comment]
In short, you have to tell compiler somehow how you form looks like otherwise it tries to map it the best it can.

**Comment by LyraelRayne** [comment]
OK so I *am* supposed to tell it the full type somehow.... I will have a look into how I might do that.

**Comment by LyraelRayne** [comment]
Ohhh! I figured it out

```
reduxForm<FormData>({
    form: "thing",
    initialValues: {
        something: "A something",
        another: "Another thing"
    },
    validate: (values, props) => {
        const errors = {
            bad: required(values.bad)
        }
        return errors
    }
})
```

OR 
```
reduxForm<FormData>({
    form: "thing",
    initialValues: {
        something: "A something",
        another: "Another thing"
    },
    validate: (values, props) => {
        const errors = {
            bad: required(values.bad)
        }
        return errors
    }
})
```

I noticed that the tests don't really cover this at all, so I might make a PR soon including a test demonstrating how this works.

**Comment by LKay** [comment]
Exactly that way! Or through some other types mixed into decorated component. Actually `values` in validate should be `Partial<YourFormData>` as the form might not be fully filled at this point. Here is some code form an actual app. Might look a litle twisted with types, but I hope you get the idea:

```typescript
type FormData = {};

interface StateProps {
     application: ApplicationStateShape;
 }
 
 interface DispatchProps {
     process: typeof process;
 }
 
 type InjectedProps = StateProps & DispatchProps & RouteComponentProps<{}>;
 
 type CustomProps = {};
 
 type StepConfirmProps = InjectedProps & CustomProps
 
 type CombinedFormProps<P = StepConfirmProps & InjectedIntlProps> = P & InjectedFormProps<FormData, P> & RouteComponentProps<{}>;
 
 function mapStateToProps (state: StateShape, props: CustomProps & RouteComponentProps<{}>): StateProps {
     return {
         application : state.application
     }
 }
 
 function mapDispatchToProps (dispatch: Dispatch<StateShape>): DispatchProps {
     return bindActionCreators({
         process
     }, dispatch);
 }
 
 function validate(values: FormData, props: CombinedFormProps) {
     return {}
 }
 
 export const StepConfirm = withRouter(
     connect(
         mapStateToProps,
         mapDispatchToProps
     )(
         injectIntl<StepConfirmProps>(
             reduxForm({
                 form : FORM_NAME,
                 destroyOnUnmount : false,
                 forceUnregisterOnUnmount: true,
                 validate
             })(
                 class StepConfirm extends Component<CombinedFormProps> {
                     render() {
                         return (
                             <div />
                            
                         );
                     }
                 }
             )
         )
     )
 )
```

**Comment by LyraelRayne** [comment]
So does that mean in your example, the 
```
 function validate(values: FormData, props: CombinedFormProps) {
     return {}
 }
```
should be 
```
 function validate(values: Partial<FormData>, props: CombinedFormProps) {
     return {}
 }
```
?


Also when you say "other types mixed into the component" are you referring to the ` InjectedFormProps<FormData, P> ` you've included in the ` type CombinedFormProps<P = StepConfirmProps & InjectedIntlProps> = P & InjectedFormProps<FormData, P> & RouteComponentProps<{}>;
` ?

It looks like Typescript type inference's mystery is eclipsed only by its power haha
