### ISSUE TITLE
@types/paho-mqtt has no exported members

### ISSUE THREAD

**Issue by jgerstle** [DefinitelyTyped/DefinitelyTyped#18443]
I tried using `@types/paho-mqtt`, but I keep getting the error: 

> File '<path>/node_modules/@types/paho-mqtt/index.d.ts' is not a module.

I am using the statement `import * as Paho from 'paho-mqtt';`, which has worked for me in the past when I used a different DefinitelyTyped package. I looked at the index.d.ts file and there seems to be no exports in there, I feel like that's what's causing this. @amikhalev am I missing something? I am using this in conjunction with the npm package [paho-mqtt](https://www.npmjs.com/package/paho-mqtt) is that how it is supposed to be done?

**Comment by amikhalev** [comment]
`paho-mqtt` doesn't export anything. It declares an ambient namespace called `Paho`. So to use it you would do:

```ts
import "paho-mqtt";

const client = new Paho.MQTT.Client(...);
```

**Comment by jgerstle** [comment]
That did it thanks
