### ISSUE TITLE
@types/webpack does not support require.context()

### ISSUE THREAD

**Issue by thw0rted** [DefinitelyTyped/DefinitelyTyped#18446]
- [X] I tried using the `@types/webpack@3.0.5` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @bumbleblym @bcherny @tommytroylin @mohsen1 

Refer to [the Webpack docs](https://webpack.js.org/guides/dependency-management/), `require.context()` is a function with the signature

    require.context(directory, useSubdirectories = false, regExp = /^\.\//)

I'm not a Typescript expert but I'm pretty sure that this package's `index.d.ts` does not define a `context()` function, and there's no mention of `require.context` in [the test cases](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webpack/webpack-tests.ts).

**Comment by mohsen1** [comment]
You need to install and nclude @types/webpack-env in your computer options types array

**Comment by thw0rted** [comment]
Is that a separate `@types` package? I thought `require.context` was a core capability of Webpack.  (I've only been reading the Webpack 2 docs, maybe this is a change in Webpack 3?)

**Comment by mohsen1** [comment]
Yes separate package. @types/webpack is for using webpack programmatically

**Comment by thw0rted** [comment]
If anybody comes across this in the future, I fixed this by installing `@types/webpack-env` -- not sure if that's the package you meant or not.  I'm also not totally clear on what the difference is between the two packages or why they're separate, but hey, it works.

**Comment by deadcoder0904** [comment]
I had already installed `@types/webpack-env` but I had `importAll` function which took in `r` as a parameter & I solved it by using `__WebpackModuleApi.RequireContext` like:

```ts
export const importAll = (r: __WebpackModuleApi.RequireContext) =>
	r.keys().map((fileName: string) => ({
		slug: fileName.substr(2).replace(/\/index\.mdx$/, ''),
		module: r(fileName),
	}))
```

**Comment by karlhorky** [comment]
> I'm also not totally clear on what the difference is between the two packages or why they're separate

Seems like the reason comes from this comment from @jantimon:

> I guess a package on its own would be best as the `webpack` definition is about the _webpack compiler_ (node js) and `webpack-env` definition is about the available helpers in the frontend code which will be added by webpack.

Source: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10978#issuecomment-244349691
