### ISSUE TITLE
@types/redux-form is not working with React 15.6.1

### ISSUE THREAD

**Issue by andrerpena** [DefinitelyTyped/DefinitelyTyped#18456]
I'm trying to use @types/redux-form and it's no longer working.

Errors:
```

ERROR in [at-loader] ./node_modules/@types/redux-form/lib/Field.d.ts:8:5
    TS2305: Module '"c:/Git/matterspace/node_modules/@types/react/index"' has no exported member 'InputHTMLAttributes'.

ERROR in [at-loader] ./node_modules/@types/redux-form/lib/Field.d.ts:9:5
    TS2305: Module '"c:/Git/matterspace/node_modules/@types/react/index"' has no exported member 'SelectHTMLAttributes'.

ERROR in [at-loader] ./node_modules/@types/redux-form/lib/Field.d.ts:10:5
    TS2305: Module '"c:/Git/matterspace/node_modules/@types/react/index"' has no exported member 'TextareaHTMLAttributes'.
ERROR in [at-loader] ./node_modules/@types/redux-form/lib/Form.d.ts:1:21
    TS2305: Module '"c:/Git/matterspace/node_modules/@types/react/index"' has no exported member 'FormHTMLAttributes'.
```

`Field.d.ts` seems broken. I'm using React 15.6.1:

![image](https://user-images.githubusercontent.com/1581429/28696023-4fe06302-7309-11e7-8e46-e4793e6545da.png)

**Comment by JakeBecker** [comment]
What version of `@types/redux-form` are you using? I think `^7.0.0` is broken. If you check the source folder for it, there's a `v6` folder that contains the source for v6 and (oddly) v7, but it looks like the `lib` folder is what got published to npm for v7.

If you're using v7 of the typings, try downgrading to v6.

**Comment by mark-monteiro** [comment]
There are changes in the `@types/react` package that you need to pull in to fix this as noted [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18269):
> The interface for React.HTMLAttributes has been broken apart into multiple interfaces (as of @types/react-15.0.38), each specific to a particular DOM element type (SelectHTMLAttributes, TdHTMLAttributes, etc), and the unified interface with all of the possible DOM element attributes is now AllHTMLAttributes

I was able to fix this by updating `@types/react` to a version after `15.0.38` (`15.0.39` worked fine for me).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
