### ISSUE TITLE
d3-array compatibility with TypedArrays

### ISSUE THREAD

**Issue by gumballhead** [DefinitelyTyped/DefinitelyTyped#18494]
- [x] I tried using the `@types/d3-array` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @gustavderdrache, @borisyankov, @tomwanzek 

When using `d3-array` functions with a `TypedArray`, the typescript compiler doesn't recognize it as a valid parameter and gives me an error.

Example:
```typescript
const data = new Uint8Array([1, 2, 3]);
const [min, max] = extent(data);
```

That will yield an error: `Argument of type 'Uint8Array' is not assignable to parameter of type 'number[]'`

I can `any` my way out of it, but if I edit the type declaration to relax the parameter definition from `T[]` to `ArrayLike<T>`, everyone is happy.

```typescript
/**
 * Return the min and max simultaneously.
 */
export function extent<T extends Numeric>(array: ArrayLike<T>): [T, T] | [undefined, undefined];
```

This would apply to most functions in this library. If that change is acceptable, I'd be happy to submit a PR if you'd like. Thanks!

**Comment by tomwanzek** [comment]
Subject to ensuring that each function in **d3-array** for which we relax the input parameter to use `ArrayLike` does not use `Array` properties/methods, which are not defined on `ArrayLike`, this seems to be a reasonable suggestions.

@gustavderdrache Your thoughts?

**Comment by gustavderdrache** [comment]
:+1:  Something like this bit me once before -- I tried to pass a `ReadonlyArray<T>` into a d3-array function.

We should be careful that there aren't usages of Array methods in the d3-array sources, but just by poking a few source files at random it doesn't appear to be the case.

**Comment by gumballhead** [comment]
I haven't look at the d3-array source much yet but I suppose it's possible some or all of these could be relaxed even further to `Iterable<T>`

**Comment by gustavderdrache** [comment]
Nah, they just use `length` and indexed properties. See [the `max()` function](https://github.com/d3/d3-array/blob/master/src/max.js) for example.

**Comment by tomwanzek** [comment]
@gumballhead Do you want to put the PR? As @gustavderdrache rightly noted, we should use `ArrayLike<T>` as a minimum, given the use of the `length` property. Arguably, we should also add the generalized tests with a TypedArray and `ReadonlyArray<T>` for completeness.

@gustavderdrache Do you remember,if you ran into your `ReadonlyArray<T>` limitation with **d3-array** or one of the other modules? There are several which work on arrays for which this generalization might work. although it would require source code review.

**Comment by gustavderdrache** [comment]
It's been a while, but I believe it was d3-array's zip function. Let's focus on this module first, and see about other cases once it's done.

**Comment by gumballhead** [comment]
Cool, will do :+1:

**Comment by gumballhead** [comment]
I have a working branch up here: https://github.com/gumballhead/DefinitelyTyped/tree/d3-array-arraylike
