### ISSUE TITLE
Type issue for express-mysql-session

### ISSUE THREAD

**Issue by gfoust** [DefinitelyTyped/DefinitelyTyped#18527]
I am having an issue with the type definitions for express-mysql-session as written by @Akim95 

The file [index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-mysql-session/index.d.ts) declares that the module exports the MySQLStore class.

However, I believe the module actually exports an anonymous factory function that can be called to generate the MySQLStore class.  This can be seen in [the documentation](https://www.npmjs.com/package/express-mysql-session) and in [the code for the module](https://github.com/chill117/express-mysql-session/blob/master/lib/index.js).

I'm not sure of the best way to fix this, but here's what I used:

```typescript
import expressSession = require('express-session');

declare function _createStoreClass(session: typeof expressSession): typeof MySQLStore;

export = _createStoreClass;
```

Thanks.

**Comment by itsUndefined** [comment]
Bump please I have the same issue
