### ISSUE TITLE
@types/enzyme ReactWrapper and ShallowWrapper should be classes, not interfaces

### ISSUE THREAD

**Issue by mmiszy** [DefinitelyTyped/DefinitelyTyped#18534]
- [x] I tried using the `@types/enzyme` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @MarianPalkus @NoHomey @jwbay @huhuanming @MartynasZilinskas 

Manual instantiation of `ReactWrapper` through `new ReactWrapper(el, true)` is *required* for testing components which render outside their DOM tree. Unfortunately, with current `enzyme` types,  you'll get an error:

> `ReactWrapper` only refers to a type, but is being used as a value here.

See this thread and in particular this comment for examples of legit usage: https://github.com/airbnb/enzyme/issues/252#issuecomment-266125422

**Comment by jwbay** [comment]
Fix is up at #18891. Note I don't think `true` is a valid second argument. If you look at how `this.root` is used in the wrappers, it's expected to be a wrapper instance.
