### ISSUE TITLE
@types/graphql AsyncIterator AsyncIterable

### ISSUE THREAD

**Issue by ndthanhdev** [DefinitelyTyped/DefinitelyTyped#18557]
- [x] I tried using the `@types/graphql` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @TonyPythoneer @calebmer @intellix @firede @kepennar 

1. node_modules/@types/graphql/subscription/subscribe.d.ts(17,4): error TS2314: Generic type AsyncIterator<T, E>' requires 2 type argument(s).
2. node_modules/@types/graphql/subscription/subscribe.d.ts(29,4): error TS2304: Cannot find name AsyncIterable'.

**Comment by jwulf** [comment]
Discussion in the graphql project: https://github.com/apollographql/graphql-subscriptions/issues/83

**Comment by ksaifullah** [comment]
Fix: https://github.com/apollographql/graphql-subscriptions/issues/83#issuecomment-326675684

**Comment by coder77** [comment]
@ksaifullah Thanks, it works for me. By adding "esnext" in tsconfig.json:

>     "lib": [
>       "es2017",
>       "dom",
>       "esnext"
>     ]
