### ISSUE TITLE
Question: @types/multer import Multer.File type

### ISSUE THREAD

**Issue by dannyhuly** [DefinitelyTyped/DefinitelyTyped#18569]
Hi,

Is it possible to import the `Multer.File` interface from `@types/multer` d.ts file ?

I was unable to import it directly with `import { File } from 'multer';`. 
Is there something I'm missing ?

* Typescript: 2.4.2
* Node: 8.1.3
* [@types/multer#1.3.2](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/multer)

Thanks.

**Comment by BendingBender** [comment]
It should be available via the global namespace `Express.Multer.File`.

**Comment by dannyhuly** [comment]
Was able to reach it with importing the express namespace first

```typescript
import { Express } from 'express';

let multerFile: Express.Multer.File;
```

@BendingBender Thanks for the help. 
Didn't notices that `Multer` is under the `Express` namespace.

**Comment by fwoelffel** [comment]
Is there any particular reason for this to be declared in an `Express` namespace?

**Comment by benwinding** [comment]
I needed to do the following to use a multer File type 
``` typescript
import { Express } from 'express';
import 'multer';
const multer = require('multer');
let multerFile: Express.Multer.File;
```
A bit ridiculous....

**Comment by MistrySaurabh** [comment]
import multer = require('multer');

**Comment by george-norris-salesforce** [comment]
So you can't just use `Multer.File` globally? Why? 

This is ugly..
```
import 'multer';
const multer = require('multer');
let multerFile: Express.Multer.File;
```

**Comment by canove** [comment]
> So you can't just use `Multer.File` globally? Why?

I just used: 
```
interface Request {
  media: Express.Multer.File;
  ticket: Ticket;
}
```

Without import express first.. So maybe its available globally.

**Comment by diegoazh** [comment]
I have a tricky question about why VsCode tell me that `Express` is never read and I currently use `Express.Multer.File`, how can I solve it? 🤔
![image](https://user-images.githubusercontent.com/10166935/94062793-8cbc0500-fdbd-11ea-8e06-ed3082173a8a.png) 
![image](https://user-images.githubusercontent.com/10166935/94062735-6e560980-fdbd-11ea-9178-9e9470a2a478.png)
