### ISSUE TITLE
Suggestion: Specify carat version of `@types/react` for each release of `@types/react-select`

### ISSUE THREAD

**Issue by nottoseethesun** [DefinitelyTyped/DefinitelyTyped#18589]
In the `package.json` for this package, currently there is:

    "dependencies": {
        "@types/react": "*"
    },

It would be better to use [carat ranges](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) than the current wildcard for `@types/react` in the `package.json` for this package, because otherwise say for example the user is on React 15, and React 16 is released, and thus then the `@types/react` version is 16, causing this error:

```
node_modules/@types/react-select/node_modules/@types/react/index.d.ts
(3422,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>
```

- [x ] I tried using the `@types/react-select` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Using: ts-loader: Using typescript@2.4.2

  - Authors: @Hesquibet, @giladgray, @iebaker, @tdreyno @skirsdeda, @vujevits, @devrelm, @MartynasZilinskas

**Comment by ajaska** [comment]
See also: #18484

**Comment by Anahkiasen** [comment]
I'm not using react-select but I'm having the exact same issue:

```json
        "@types/node": "^8.0.19",
        "@types/react": "^15.6.1",
        "@types/react-bootstrap": "^0.0.52",
        "@types/react-dom": "^15.5.2",
        "@types/recompose": "^0.23.3",
        "@types/webpack-env": "^1.13.0",
        "react": "^15.6.1",
        "react-apollo": "^1.4.10",
        "react-bootstrap": "^0.31.2",
        "react-dom": "^15.6.1",
        "recompose": "^0.24.0"
```

**Comment by pierre-H** [comment]
Same bug with react-flatpickr @begincalendar

**Comment by jacortinas** [comment]
I'm having the exact same issue with vague type definitions giving duplicate errors, I want to die.

**Comment by markwangen** [comment]
too sad! I have the same problem even though I didn't change anything. It just happens

**Comment by YagoLopez** [comment]
This is pathetic

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
