### ISSUE TITLE
@types/backbone Collection.set signature is incorrect.

### ISSUE THREAD

**Issue by PaulJuliusMartinez** [DefinitelyTyped/DefinitelyTyped#18593]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov, @nvivo

The `Collection.set` method incorrectly has `Silenceable` set for the type of its second `options` parameter:

```ts
class Collection<TModel extends Model> extends ModelBase {
    ...
    set(models?: TModel[], options?: Silenceable): TModel[];`
    ...
}
```

The [documentation for this method](http://backbonejs.org/#Collection-set) says that it can accept `add`, `remove` and `merge` options.

Presumably it should `ModelSetOptions`, but none of the option interfaces have `add?: boolean` or `merge?: boolean` fields, so those presumably need to be added somewhere as well.

Edit: I've noticed a couple other mistakes/issues:

- Collections can define `url` to either be a [member or a function](http://backbonejs.org/#Collection-url). Collection extends `ModelBase`, which defines `url: any`. If I try to provide a definition in a Collection I get the error: `Class 'Collection<MyModel>' defines instance member property 'url', but extended class 'MyModels' defines it as instance member function.`

- `Collection.slice`'s first argument is not marked as optional. This just calls `Array.slice`, whose first argument is optional.

- `Backbone.sync` can accept either a [model or a collection](http://backbonejs.org/#Sync) to its second argument.

- The options passed to `Collection.add` can include `sort: boolean` which tells the collection whether or not to sort itself after it adds the model. This is admittedly poorly documented in Backbone, as this behavior is only mentioned in the documentation for [`Collection.sort`](http://backbonejs.org/#Collection-sort).

**Comment by Spinarooni** [comment]
Can this be closed?
