### ISSUE TITLE
@types/raven-node - parseUser function missing from config()

### ISSUE THREAD

**Issue by galkowskit** [DefinitelyTyped/DefinitelyTyped#18599]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @scttcper @1999 

Something like this:
```

Raven.config(config.sentry.dsn, {
    name: config.name,
    environment: config.env,
    autoBreadcrumbs: true,
    parseUser: req => {
       // some logic here...
        return {
          id: req.auth.id,
          username: req.auth.username,
        }
    },
  }).install()
```

`parseUser` is missing from definitions. It's working without TS but TS is complaining about the types.

I have added a dirty workaround in the typings:
```
    parseUser?: (any) => any
```

In `index.d.ts` in `export interface ConstructorOptions`. If you wish I can create a PR (with a bit more meaningful types).

**Comment by scttcper** [comment]
https://github.com/getsentry/raven-node/blob/master/lib/parsers.js#L123-L129

Looks like it can be a few things. Opened #18610
