### ISSUE TITLE
@types/elasticsearch Connection handlers types

### ISSUE THREAD

**Issue by maximeloizeau** [DefinitelyTyped/DefinitelyTyped#18603]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @pushplay @andy-ms 

Hi, 
I hope you don't mind the mentions. I use the [http-aws-es connectionClass](https://github.com/elastic/elasticsearch-js/issues/274) with elasticsearch-js and it requires additional fields in the ConfigOptions object that are not specified in the current type.

Is this the correct place to put the missing fields?

Thanks

**Comment by pushplay** [comment]
Hi @maximeloizeau,

I also use `http-aws-es` and have the same problem.  I dodge the problem by casting to `any`, which is pretty lame.

```typescript
const es = new elasticsearch.Client({
    apiVersion: "5.1",
    hosts: esHost,
    connectionClass: require("http-aws-es"),
    amazonES: {
        region: region,
        credentials: creds
    }
} as any);
```

We don't want to put information for every possible connectionClass in `elasticsearch`.  It would be messy.  We would argue about which connectionClasses meet some threshold of relevance.  They might even conflict on typing.

The better solution here is to create a typing for `http-aws-es` that adds the parameters to `Elasticsearch.ConfigOptions` through [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html).

If you'd like to take a shot at writing the declaration file you can flag my name for code review and I'll take a look at it.

**Comment by maximeloizeau** [comment]
Hi,

Thanks for the details, I understand the reasons. 
I was about to start working on the separate declaration file and I discovered the version 2 of http-aws-sdk using the aws-sdk environment config. So it doesn't use the Elasticsearch configuration object anymore.

If that works fine, I'll continue like this, otherwise I'll work on the definitions.

**Comment by schmod** [comment]
Typings are available for [http-aws-es](https://www.npmjs.com/package/@types/http-aws-es), and solve this problem for me.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
