### ISSUE TITLE
Plotly optional properties should be optional on interface

### ISSUE THREAD

**Issue by lukewaters** [DefinitelyTyped/DefinitelyTyped#18612]
While using the Plotly.js interface to define data for plotly charts I was forced to implement all properties by the interface. It would be better for the developer if they were only required by the interface to specify `required` parameters. By default, plotly will use default values if a property is unspecified and this behavior should be preserved.
  - Authors: @chrisgervang @martinduparc @frederikaalund @taoqf

**Comment by martinduparc** [comment]
Please submit a PR

**Comment by taoqf** [comment]
@lukewaters Do you mean `toImage` and `downloadImage`?

**Comment by lukewaters** [comment]
@taoqf I specifically ran into this issue when I was using `Plotly.ScatterData` for some charts. The interface is great in that it allows me to view the settings that are available for configuration, but I am also forced to configure many properties that normally allow me to use defaults. 

One example is `text`, this property is not required for a chart that doesn't define text for a scatter plot, but by strongly typing my series as `ScatterData` I am required to provide a value.

**Comment by taoqf** [comment]
@lukewaters . try use `Plotly.Data` instead of `Plotly.ScatterData`.

**Comment by lukewaters** [comment]
@taoqf That works

**Comment by testica** [comment]
type attribute of Plotly.Data only accept `"bar" | "scatter" | "scattergl"`.. what about `pie` ?

**Comment by taoqf** [comment]
@testica Please submit a PR

**Comment by chrisgervang** [comment]
@lukewaters, the motivation behind it is `Plotly.plot()` expects the `Plotly.Data` type, and you can wrap `ScatterData` in `Partial<..>` if you'd like to define a variable of that type without implementing the whole interface.

Overtime I hope this `Data` type expends to support more than `ScatterData`, and becomes a union type to support the additional data types.

@testica this is a community maintained type definition. We've been pretty quick to pull in contributions 😄

**Comment by amivit** [comment]
I'm thankful there's any type definitions at all, but this issue makes integrating Plotly into an Angular app a PITA. Any alternative solutions? For now I'm sticking with `declare var Plotly: any;`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
