### ISSUE TITLE
[jquery] Cannot append $(...).contents() to jQuery

### ISSUE THREAD

**Issue by cervengoc** [DefinitelyTyped/DefinitelyTyped#18631]
The following code gives compile error using the latest `@types/jquery` package.

```
$("<div/>").append($(".something").contents());
```

The issue is that `append` and similar functions have a pure `JQuery` notation in their signature, which falls back to the `HTMLElement` type argument, which at the end is not compatible with `JQuery<HTMLElement | Text | Comment>` returned by `JQuery.contents()`.

- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @leonard-thieu

**Comment by leonard-thieu** [comment]
Will be fixed by #18633. Thank you for reporting this.

**Comment by cervengoc** [comment]
Thank you, I haven't seen such a quick fix before :)
