### ISSUE TITLE
[jquery] JQuery.Promise<T> cannot be chained properly in some cases

### ISSUE THREAD

**Issue by cervengoc** [DefinitelyTyped/DefinitelyTyped#18636]
Sorry, here I am again. This code doesn't work as expected because the type arguments of `Promise<R, J, N>` have default values of `any`, but the `then` method has default type arguments of `never`.

```
function getSomePromise(): JQuery.Promise<any> { ... }

function getResult(): JQuery.Promise<any> {
  return getSomePromise ().then(result => {
    return process(result);
  });
}

function process(result: any): any {
  ...
}
```

Expected result: The `getResult` method nicely returns a `Promise<any, any, any>`.
Actual result: Compile error because `Promise<any, never, never>` is not compatible with `Promise<any, any, any>`.

- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @leonard-thieu

**Comment by leonard-thieu** [comment]
I think there might be something wrong with your example. `getResult()` would return a `JQuery.Promise3` in that case.

**Comment by cervengoc** [comment]
Sorry the sample wasnt completely correct, I fixed it.

**Comment by cervengoc** [comment]
@leonard-thieu could you please have another look?

**Comment by leonard-thieu** [comment]
The updated example code doesn't produce an error for me. This is the code I used to test:

```typescript
function getSomePromise(): JQuery.Promise<any> {
    return {} as JQuery.Promise<any>;
}

function getResult(): JQuery.Promise<any> {
    return getSomePromise().then(result => {
        return process(result);
    });
}

function process(result: any): any {
    return {};
}
```

**Comment by cervengoc** [comment]
Thanks for the updates, I'll check this again, probably there was some other issue on my side.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
