### ISSUE TITLE
[jquery] Promise<T> is not compatible with JQuery.ajax return value

### ISSUE THREAD

**Issue by cervengoc** [DefinitelyTyped/DefinitelyTyped#18635]
This code is currently not working, complaining about `JQuery.jqXHR` not being compatible with `Promise<T>`. Furthermore, it seems to me that the base of this issue is that `Promise3<.. many arguments ...>` is not compatible with `Promise<T>`.

```
function getResults(): JQuery.Promise<any> {
  return $.ajax(...);
}
```

- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @leonard-thieu

**Comment by leonard-thieu** [comment]
See PR #18638.

I don't believe I can make `JQuery.jqXHR` compatible with `JQuery.Promise` without variadic kinds. I did add compatibility with `Promise` however, so the following should be possible.

```typescript
function getResults(): Promise<any> {
  return $.ajax(...);
}
```

**Comment by cervengoc** [comment]
Thank you for your notes however this would mean that we need to migrate all of our code to use the Promise library signatures instead of the jQuery ones. I mean for example using then instead of done or finally instead of always. While in general this would be good anyways we currently don't have the required resources.

**Comment by cervengoc** [comment]
@leonard-thieu I had a look at the code and saw that `Promise3` extends `PromiseLike`, `Promise2` extends `Promise3`, and `Promise` extends `PromiseLike`. Could you please give some hints about why it couldn't extend `Promise2`, so the chain could get complete?

**Comment by leonard-thieu** [comment]
I've been exploring introducing a common `Promise1` type to serve as a base for jQuery Promises. It would be a single parameter version of jQuery Promises. I'm not 100% sure I can make it work since admittedly I don't fully understand how TypeScript handles method overloading and compatibility. If I can get it working, I think it'll resolve your issue.

**Comment by leonard-thieu** [comment]
Note that you also have the option to add a type assertion to the return type of `$.ajax()`.

```typescript
function getResults(): JQuery.Promise<any> {
    return $.ajax('') as JQuery.Promise<any>;
}
```

**Comment by cervengoc** [comment]
@leonard-thieu Thanks for the update. I'm aware of using a cast but that's kind of a hack IMO. I'm not completely competent but why isn't it possible to inherit `JQuery.Promise` from `JQuery.Promise2`?

**Comment by leonard-thieu** [comment]
Personally, I haven't figured out a way to make it work. I'm not sure if it's actually possible or not. Keep in mind that `JQuery.Promise` is a rest parameter version of the jQuery Promise. As far as I can tell, the problem is rooted in signature compatibility between the two types. You'll get errors similar to the following if you try to extend them.

```
Error:(6284, 15) TS2430:Interface 'Promise3<TR, TJ, TN, UR, UJ, UN, VR, VJ, VN>' incorrectly extends interface 'Promise1<TR, TJ, TN>'.
  Types of property 'pipe' are incompatible.
    Type '{ <ARD = never, AJD = never, AND = never, BRD = never, BJD = never, BND = never, CRD = never, CJD...' is not assignable to type '{ <ARD = never, AJD = never, AND = never, ARF = never, AJF = never, ANF = never, ARP = never, AJP...'.
      Type 'Promise3<any, any, any, any, any, any, any, any, any>' is not assignable to type 'Promise1<any, any, any>'.
        Types of property 'catch' are incompatible.
          Type '<ARF = never, AJF = never, ANF = never, BRF = never, BJF = never, BNF = never, CRF = never, CJF =...' is not assignable to type '<ARF = never, AJF = never, ANF = never>(failFilter?: ((t: any) => ARF | Promise1<ARF, AJF, ANF> |...'.
            Type 'Promise3<ARF, ARF | AJF, ANF, never, never, never, never, never, never>' is not assignable to type 'Promise1<ARF, AJF, ANF>'.
              Types of property 'always' are incompatible.
                Type '(alwaysCallback: TypeOrArray<Callback3<ARF | AJF, never, never>>, ...alwaysCallbacks: TypeOrArray...' is not assignable to type '(alwaysCallback: TypeOrArray<Callback1<ARF | AJF>>, ...alwaysCallbacks: TypeOrArray<Callback1<ARF...'.
                  Type 'Promise3<ARF, ARF | AJF, ANF, never, never, never, never, never, never>' is not assignable to type 'Promise1<ARF, AJF, ANF>'.
```

I haven't figured out how to resolve this issue yet.

As for the type assertion, I think this is one of those cases where it's okay to use. The types ought to be compatible but aren't.

**Comment by cervengoc** [comment]
Actually I meant the opposite way, `Promise` could extend `Promise2`, Promise2` could extend `Promise3`., and `Promise3` extend `PromiseLike`. The latter two is already present. The logic here I think is that `Promise3` is the most flexible, the the others are less and less flexible, so more specific in other words.

**Comment by leonard-thieu** [comment]
Ahh, okay. I see what you mean now. Yes, I think it can be implemented that way. I'll push the code for it in a little bit.

**Comment by leonard-thieu** [comment]
I've updated PR #18638.

This should allow `JQuery.jqXHR` to be assignable to `JQuery.Promise<any>`.
