### ISSUE TITLE
 Type definitions for react-relay don't seem to be accurate anymore

### ISSUE THREAD

**Issue by justinlevi** [DefinitelyTyped/DefinitelyTyped#18676]
- [X] I tried using the ` "@types/react-relay": "^0.9.13",` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] Here is my question asked on  [StackOverflow](https://stackoverflow.com/questions/45535641/react-relay-react-relay-with-typescript-throwing-typeerror-object-prototype-m).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @schickling @graphcool @voxmatt

Seeing this error with the latest version of relay and the latest typings
![screen shot 2017-08-06 at 5 17 35 pm](https://user-images.githubusercontent.com/1117989/29007150-2dc1d8cc-7acb-11e7-95c5-ae1084d57fcd.jpg)

Given the following `package.json`: 

```
"dependencies": {
    "@types/jest": "^20.0.6",
    "@types/node": "^8.0.19",
    "@types/react": "^16.0.0",
    "@types/react-dom": "^15.5.2",
    "@types/react-relay": "^0.9.13",
    "babel-relay-plugin": "^0.9.*",
    "babel-plugin-relay": "1.2.0-rc.1",
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-relay": "1.2.0-rc.1"
  },
```

The following class, taken directly from the `react-relay-tests.tsx` will throw an error when you try to instantiate it. 

```JS
import * as Relay from 'react-relay';

interface Props {
  text: string;
  userId: string;
}

interface State {
}

export default class AddTweetMutation extends Relay.Mutation<Props, State> {

  public getMutation() {
    return Relay.QL`mutation{addTweet}`;
  }

  public getFatQuery() {
    return Relay.QL`
            fragment on AddTweetPayload {
                tweetEdge
                user
            }
        `;
  }

  public getConfigs() {
    return [{
      type: 'RANGE_ADD',
      parentName: 'user',
      parentID: this.props.userId,
      connectionName: 'tweets',
      edgeName: 'tweetEdge',
      rangeBehaviors: {
        '': 'append',
      },
    }];
  }

  public getVariables() {
    return this.props;
  }
}
```

**Comment by justinlevi** [comment]
Also, just to note that using any version of `react-relay` after 0.9.x seems to have the same error for me. 

Here's a simple project for reference. 
https://github.com/justinlevi/HelloWorldTypescriptReactRelay

**Comment by voxmatt** [comment]
Yeah, the type-defs are no longer accurate post Relay 1.0.

On our project, we've copy/pasted the types and put them under `react-relay/classic` — the pre-1.0 types are basically 1:1 with what's in classic now. Unfortunately, building out types for modern is a big undertaking.

**Comment by justinlevi** [comment]
@voxmatt thanks for the note. I can confirm that I can use the classic typings by copying the `node_modules/@types/react-relay` folder into  `<app root>/custom_typings/react-relay/classic` and then adding the typeRoots key to my`tsconfig.json`


```
...
  "typeRoots": [
    "custom_typings",
    "node_modules/@types"
  ]
```

**Comment by alloy** [comment]
This should now work with the typings for Relay v1 as well.
