### ISSUE TITLE
@types/vis locales should not be string array

### ISSUE THREAD

**Issue by kandangit** [DefinitelyTyped/DefinitelyTyped#18687]
I am using last version of types/vis

The locales attribute of the Options interface should be "any" data type instead of string[]

locales?: string[];

vis.js won´t allow this type, only an object is allowed (http://visjs.org/docs/network/)

FYI
@andy-ms @sandersn

Using package.json to import VIS typings into the project

**Comment by sandersn** [comment]
Actually it looks like the type should be something like `Locales` below:

```ts
type Locales = { [language: string]: LocaleMessages };
type LocaleMessages = {
    edit: string,
    del: string,
    back: string,
    addNode: string,
    addEdge: string,
    editNode: string,
    editEdge: string,
    addDescription: string,
    edgeDescription: string,
    editEdgeDescription: string,
    createEdgeError: string,
    deleteClusterError: string,
    editClusterError: string
};
```

**Comment by kandangit** [comment]
Correct. 
Seems Locales can define an object for text messages in a number of languages . For example.

```
let locales = {
    en: {
        addNode: 'Add Node'
    },
    es: {
        addNode: 'Nuevo Nodo'
    }
};
```

Looks like Network constructor will receive this array and the locale used to show texts in the manipulation bar. Some buttons may be hidden so not necessary to override all text messages.

```
let options = {
    "locale": 'en',
    "locales": locales
    //....
};

```

Thanks for your reply.

**Comment by sandersn** [comment]
I made a PR for this at #18714
