### ISSUE TITLE
webpack is missing HashedModuleIdsPlugin

### ISSUE THREAD

**Issue by jcreamer898** [DefinitelyTyped/DefinitelyTyped#18701]
- [x] I tried using the @types/react-native package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for StackOverflow. (Please ask any appropriate questions there).
- [x] Mention the authors (see Definitions by: in index.d.ts) so they can respond.
Authors: @tkqubo @bumbleblym @bcherny @tommytroylin @mohsen1

The exports on the webpack object does not have HashedModuleIdsPlugin so when trying to run webpack production builds with ts-node, it won't compile.

![](http://d.pr/i/x3KTa+)

**Comment by mohsen1** [comment]
Please make a PR. Make sure you add construction options type (if needed) as well.
