### ISSUE TITLE
Add new Typescript team members to DefinitelyTyped

### ISSUE THREAD

**Issue by sandersn** [DefinitelyTyped/DefinitelyTyped#18710]
@amcasey needs to be added as a team member on DefinitelyTyped because he's a new member of the Typescript team who will be doing the DefinitelyTyped rotation this week.

@andy-ms @basarat @blakeembrey @borisyankov @Diullei @johnnyreilly @vvakame can you add Andrew? Thanks.

**Comment by sandersn** [comment]
Could you also add @armanio123 and @uniqueiniquity, who are other new team members? Thanks.

**Comment by RyanCavanaugh** [comment]
Also if I could be made an owner? 🤴

**Comment by blakeembrey** [comment]
Added the members 👍 Looking into repo owner now.

**Comment by blakeembrey** [comment]
@RyanCavanaugh Done. I added you as an owner, but just in case I also added you as "team maintainer" so you can add more people to the TypeScript team in the future. It looks like @andy-ms was also the existing "team maintainer" - it's a new feature to me, but seems handy 😄

**Comment by RyanCavanaugh** [comment]
Thanks!
