### ISSUE TITLE
Tests for code that *doesn't* compile?

### ISSUE THREAD

**Issue by mmkal** [DefinitelyTyped/DefinitelyTyped#18750]
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

@andy-ms 

Has there been any discussion of adding a test file with code that doesn't compile? Let's say I write the types for a package `foo` in some way like this:

```typescript
export function bar(arg: number);
```

I would like to be able to add a test like this

```typescript
import { bar } from 'foo';

bar('wrong'); // tsc-error: Argument of type .* is not assignable to parameter of type 'number'
```

Where the comment signifies that there should be an error matching the regex provided.

This would help make sure that the type definitions are actually useful - that they prevent invalid use of the library.

Should be possible using the api shipped with typescript.

**Comment by andy-ms** [comment]
There is some functionality like that available in [dtslint](https://github.com/Microsoft/dtslint#write-tests), so as long as you're linting your code you can add `// $ExpectError` to a line where you expect an error.

**Comment by mmkal** [comment]
Good enough for me!
