### ISSUE TITLE
React: ComponentClass has incompatible render signature

### ISSUE THREAD

**Issue by Igorbek** [DefinitelyTyped/DefinitelyTyped#18765]
- [x] I tried using the **`@types/react@15.6.1`** package and had problems.
- [x] I tried using the latest stable version of tsc - **2.4.2**. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
- Authors: @richseviora @vbfox

Repro:
```ts
import * as React from "react";

class Test extends React.Component {
    render() {
        return <div />;
    }
}

<Test />; // ok

const TestClass: React.ComponentClass = Test;

<TestClass />; // error
~~~~~~~~~~~~~
```

```
JSX element type 'Component<{}, ComponentState>' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => false | Element | null' is not assignable to type '{ (): false | Element | null; (): Element | null; }'.
      Type 'false | Element | null' is not assignable to type 'Element | null'.
        Type 'false' is not assignable to type 'Element | null'.
```

The bug seems to be introduced in #17025 (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17025#commitcomment-23291749)

**Comment by vbfox** [comment]
There were already multiple cases of this hapenning and being solved by rebuilding node_modules (See comments on https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17161 )

If it doesn't work for you can you upload somewhere a repository reproducing the problem ?

**Comment by Igorbek** [comment]
Sorry, I thought I had clean environment.
