### ISSUE TITLE
Lodash - trim() as Iterator

### ISSUE THREAD

**Issue by aleung** [DefinitelyTyped/DefinitelyTyped#18774]
- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar 

```
_.map<string, string>(stringArray, _.trim).forEach((s: string) => {
  console.log(s);
});
```

Above code got error:

> error TS2345: Argument of type '(string?: string | undefined, chars?: string | undefined) => string' is not assignable to parameter of type 'string | undefined'.
>   Type '(string?: string | undefined, chars?: string | undefined) => string' is not assignable to type 'string'.

I check the typing of `_.map`. It expects the second parameter in type `ListIterator<T, TResult>`. But `_.trim` doesn't match `ListIterator`.

**Comment by sheinzle** [comment]
+1

I run into the same problem:

`let result = _.map(['  foo  ', '  bar  '], _.trim);`

According to tsc, `result` is of type `boolean[]`

**Comment by aj-r** [comment]
I think it's because the parameters of `_.trim` don't all match up with what lodash wants to use for an iterator.

It works fine if you use a lambda to force it to only use the first parameter of `_.trim`:

```
let result = _.map([' foo ', ' bar '], (s) => _.trim(s)); // string[]
```

If it's something you do often, you could store it in a variable:

```
const trim = (s: string) => _.trim(s);
let result = _.map([' foo ', ' bar '], trim);
```

**Comment by aj-r** [comment]
Looks like lodash is clearly meant to support this, given the last example here: https://lodash.com/docs/4.17.4#trim. Not sure if there is a good way to convince Typescript of this, though...

**Comment by aj-r** [comment]
I did some testing, and adding a second `trim` overload that only takes one argument fixes this. i.e.

```
trim(
    string?: string,
    chars?: string
): string;

trim(
    string: string
): string;
```

However this seems a little weird because the second overload looks completely redundant, and goes against the [do's and don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html).

I looked at the lodash source, and found this:

```
@param {string} [string=''] The string to trim.
@param {string} [chars=whitespace] The characters to trim.
@param- {Object} [guard] Enables use as an iteratee for methods like `_.map`.
@returns {string} Returns the trimmed string.
```

So `trim` actually takes 3 arguments, and if the 3rd argument is present, the function runs in iteratee mode and ignores the second argument. So maybe the correct thing to do is something like this:

```
trim(
    string?: string,
    chars?: string
): string;

trim(
    string: string,
    index: any,
    guard: any
): string;
```

**Comment by aj-r** [comment]
There is a similar parameter for `includes`:

> @param- {Object} [guard] Enables use as an iteratee for methods like `_.reduce`. https://github.com/lodash/lodash/blob/4.17.4/lodash.js#L9418
