### ISSUE TITLE
[redux-form] Unable to provide errors to SubmissionError

### ISSUE THREAD

**Issue by kristian-puccio** [DefinitelyTyped/DefinitelyTyped#18811]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CarsonF @aikoven @LKay @Lukas-Zech 

Using TS 2.4.2.

Doing: 
```
    throw new SubmissionError({
        _error: "Sorry there has been a problem, please try again.",
    });
```

Leads to the error: 
message: 'Argument of type '{ _error: any; }' is not assignable to parameter of type 'void | undefined'.
  Type '{ _error: any; }' is not assignable to type 'void'.'

It seems like TS is only allowing the generic params default (void) and not allowing me to override it.
Unless I'm missing some TS stuff.

Thanks

**Comment by IOuser** [comment]
I've had the same issue. And I found following solution:

```
import {
	SubmissionError,
	SubmissionErrorConstructor,
} from 'redux-form';

interface UserCreationErrors {
	[fieldName: string]: string | string[];
}

const UserCreationSubmissionError = SubmissionError as SubmissionErrorConstructor<UserCreationErrors>;

...

throw  new UserCreationSubmissionError({
	field1: field1Errors,
	field2: field2Errors,
	field3: field3Errors,
	_error: 'User creation failure, please check data',
});
```

**Comment by kristian-puccio** [comment]
That is awesome!

Thanks so much
