### ISSUE TITLE
@types/react-native has wrong typings for FlatList> ItemSeparatorComponent

### ISSUE THREAD

**Issue by mcousillas6** [DefinitelyTyped/DefinitelyTyped#18823]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....
I'm currently using `FlatList` on react-native `0.47.1` 

The type definition is technically incorrect as it does not account for `React.Element<any>:`

`ItemSeparatorComponent?: React.ComponentClass<any> | null`

As a result, you will see errors like this when trying to pass in an element as a ItemSeparatorComponent:

`error TS2352: Type 'Element' cannot be converted to type 'ComponentClass<any>'. Type 'Element' provides no match for the signature 'new (props?: any, context?: any): Component<any, ComponentState>'`

From what've tried, this fixes the issue (works the same way as ListEmptyComponent, Header and Footer):
`ItemSeparatorComponent?: React.ComponentClass<any> | React.ReactElement<any> | (() => React.ReactElement<any>) | null`

@alloy , @timwangdev , @jeremistadler  would you mind checking it out?

**Comment by alloy** [comment]
Please include a link to either the docs or the flow typings or source that uses it so we can verify.

**Comment by mcousillas6** [comment]
Here is a screenshot of an example of the issue and the source code. Please let me know if I can send you anything else that might help.
<img width="1319" alt="screen shot 2017-08-11 at 09 52 07" src="https://user-images.githubusercontent.com/13751518/29213708-c94fc13e-7e7a-11e7-9d66-3243d7ed503f.png">

``` typescript
class Example extends Component{
  _renderItem = (rowData) => {
    return (
      <View>
        <Text> {rowData.item} </Text>
      </View>
    );
  }

  //This one breaks
  _renderSeparator= () => <View style={{height: 1, width: '100%', backgroundColor: 'gray'}} />

  render() {
    return (
      <FlatList
        data={['a', 'b', 'c']}
        renderItem={this._renderItem}
        ItemSeparatorComponent={this._renderSeparator}
      />
    );
  }
}
```

**Comment by alloy** [comment]
My bad, I meant “…from the official React Native documentation or code base”, so that we can see what’s actually supported. Having said that, the example would make for a great [test](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/test/index.tsx). Would you consider making a PR for this?

I also think that you want `React.StatelessComponent` for the function version, which is combined with `React.ComponentClass` in [`ComponentType`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fb18e56681e858cef1fa0667e4c23db5f762b008/types/react/index.d.ts#L72).

**Comment by mcousillas6** [comment]
Thanks for the reply! Sorry about the misunderstanding, [here](https://facebook.github.io/react-native/docs/flatlist.html#itemseparatorcomponent) is the link to the `ItemSeparatorComponent` docs.
 
Looks like it should be any `ReactClass` So the final typing should be:
`ItemSeparatorComponent?: React.ComponentClass<any> | React.StatelessComponent<any> | null` right?

Let me know if you agree with the change, I can make a PR after that with the type change and the new test.

**Comment by alloy** [comment]
Looks like you’re right, I’ve also checked [the source](https://github.com/facebook/react-native/blob/37754c5c83b6db87cce434e032f8ab7ba0810168/Libraries/Lists/VirtualizedList.js#L1246-L1248) to double-check 👍 

To clarify my previous comment, I believe you can replace `React.ComponentClass<any> | React.StatelessComponent<any>` by `React.ComponentClass<any>`.

**Comment by mcousillas6** [comment]
You're right, that works 👌.
Already submited the PR with the changes and the test case [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18924).
