### ISSUE TITLE
[react-bootstrap-table] BootstrapTableProps missing expandColumnOptions

### ISSUE THREAD

**Issue by d24wang** [DefinitelyTyped/DefinitelyTyped#18840]
- [x] I tried using the latest `@types/react-bootstrap-table` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

As shown in the official documentation: http://allenfang.github.io/react-bootstrap-table/docs.html#expandColumnOptions

@flaub @alelode

**Comment by dawnmist** [comment]
Fixed in pull request https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20761

**Comment by d24wang** [comment]
Expected definitions has been added, thanks
