### ISSUE TITLE
[@types/semantic-ui] error when try to add param `type: "category"` on search param

### ISSUE THREAD

**Issue by erlangp** [DefinitelyTyped/DefinitelyTyped#18887]
Hello, i got error when try to add param `type: "category"` on search param

- [x] I tried using the `@types/semantic-ui` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] Mention authors: [Leonard Thieu](https://github.com/leonard-thieu) @leonard-thieu 

```
function setupSearchInput(): void {
    let url: string = API_URL + '/read-all-search.php?q={query}';
    let apiSettings: SemanticUI.ApiSettings = {
        url: url
    };
    let fieldsSettings: SemanticUI.Search.FieldsSettings = {
        results: 'results',
        title: 'nama'
    }
    let searchSettings: SemanticUI.SearchSettings = {
        minCharacters: 1,
        fields: fieldsSettings,
        apiSettings: apiSettings,
        onSelect: function (this: JQuery, result: any, response: any) {
            onSelectSearchResult(this, result, response);
        },
        type: "category"
    };
    $('.ui.search').search(searchSettings);
}
```

Error message - Visual Studio Code:
```
[ts]
Type '{ minCharacters: number; fields: (Pick<_Impl, "results"> & Partial<Pick<_Impl, "action" | "catego...' is not assignable to type 'Param'.
Object literal may only specify known properties, and 'type' does not exist in type 'Param'.
```

Error message - `webpack`:
```
ERROR in ./src/app_map.ts
(1289,9): error TS2322: Type '{ minCharacters: number; fields: (Pick<_Impl, "results"> & Partial<Pick<_Impl, "action" | "catego...' is not assignable to type 'Param'.
  Object literal may only specify known properties, and 'type' does not exist in type 'Param'.
```

Screenshot - file `app_map.ts` (my project file):
- [https://imgur.com/BE63rkJ](https://imgur.com/BE63rkJ)
- [https://imgur.com/nF5qYrK](https://imgur.com/nF5qYrK)

Screenshot - Semantic UI Search docs:
- [https://imgur.com/igthuhu](https://imgur.com/igthuhu)
- [https://imgur.com/V4Z9EUO](https://imgur.com/V4Z9EUO)

Thanks

**Comment by leonard-thieu** [comment]
Will be fixed by #18888. Thanks for reporting this.
