### ISSUE TITLE
@types/bull: Name for a job is missing in typings in `Queue.add()`

### ISSUE THREAD

**Issue by mecp** [DefinitelyTyped/DefinitelyTyped#18911]
- [x] I tried using the `@types/bull` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bgrieder, @JProgrammer, @marshall007

Also reported here https://github.com/OptimalBits/bull/issues/653

**Comment by marshall007** [comment]
Good catch. I was waiting for all the v3 API changes to pan out before updating the definitions again, but I will definitely include this in my next PR unless someone else beats me to it.
