### ISSUE TITLE
@types/react-router-redux causing compiling errors

### ISSUE THREAD

**Issue by 8398a7** [DefinitelyTyped/DefinitelyTyped#18918]
## dependency

`typescript`: 2.4.2
`react`: 16.0.0-beta.5
`react-router-redux`: 5.0.0-alpha6
`@types/react-router-redux`: 5.0.5

## errors

```javascript
ERROR in [at-loader] ./node_modules/@types/react-router-redux/index.d.ts:26:45
    TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).

ERROR in [at-loader] ./src/App.tsx:21:6
    TS2604: JSX element type 'ConnectedRouter' does not have any construct or call signatures.
```

## code

```javascript
export class ConnectedRouter<State> extends React.Component<ConnectedRouterProps<State>> {}
```
refs: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-router-redux/index.d.ts#L26

**Comment by huy-nguyen** [comment]
Can you provide a full code sample that, when compiled with typescript, will cause the error? I see that you're having trouble with `ConnectedRouter` so your example should include calls to `connect`, the creation of a `history` and how you create the `redux` store (e.g. with `combineReducers`) like in the [the current test file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/142a2fc41c2bf58381dc62b656149ad555bb42e7/types/react-router-redux/react-router-redux-tests.tsx). 

Also, please note that the `react` 16 that you seem to have trouble with is in pre-release so I'm not sure if that's the type definition version that you want to use. `react` 16 type definition also seesm to be causing problems with other type definitions (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18708). Does pinning the type definition version of `react` and `react-dom` to the latest 15.x version help solve your problem?

**Comment by 8398a7** [comment]
@huy-nguyen Although it has been merged, this problem does not occur in react 15.x series.
