### ISSUE TITLE
Express typings don't include app.on()

### ISSUE THREAD

**Issue by natejgardner** [DefinitelyTyped/DefinitelyTyped#18940]
- [x] I tried using the `@types/express` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @19majkel94 @kacepe 

The Express API is not completely implemented. `app.on()` and `app.mountpath()` are missing, possibly among others. See Express API docs here: [http://expressjs.com/en/api.html](http://expressjs.com/en/api.html)

**Comment by natejgardner** [comment]
Turns out in Typescript you need to use `app.listen.on()`. They do appear available, but not in the same way that they'd be accessed in js.

**Comment by 19majkel94** [comment]
You can make a PR if you need this definitions.
