### ISSUE TITLE
d3 example invalid?

### ISSUE THREAD

**Issue by davidreher** [DefinitelyTyped/DefinitelyTyped#1894]
Hey there,

I tried the second example of Enter and Exit on http://d3js.org/#enter-exit. The typescript compiler complains and tells me on line 
>p.enter()
>The property 'enter' does not exist on value of type 'D3.Selection'.

the same on the exit line.

What am I doing wrong?

**Comment by DanielRosenwasser** [comment]
I assume this was solved with `this` typing at some point.
