### ISSUE TITLE
Lodash definitions not working on TS 2.5

### ISSUE THREAD

**Issue by pocesar** [DefinitelyTyped/DefinitelyTyped#18956]
When using `filter` function, TS 2.5 is giving an error:

```
Type '(recpt: Recipient) => boolean | undefined' has no properties in common with type 'Partial<Recipient>'
```

code looks like this: 

```ts
const recipients: Comunication.Recipient[] = [
  {
    name: 'Prefeitura',
    type: 'orgao',
    groups: ['chat','contato','sms']
  },
]

// ...

_.filter(recipients, (recpt) => (
  recpt.type === 'orgao' && recpt.groups && recpt.groups.indexOf(req.params['group']) !== -1
))
```

same code is working fine in 2.4

**Comment by aj-r** [comment]
Well that's odd. Sounds like a typescript bug to me, but probably needs further investigation...

**Comment by pocesar** [comment]
yes, it seems that it won't accept TRUTHY values, only literal boolean values, having to typecast `|| false` at the end for it to accept the predicate return

**Comment by aj-r** [comment]
Oh, that makes sense. You could also change `recpt.groups` to `!!recpt.groups` to fix it. I'm not sure how this worked in TS 2.4 actually...

I have an open PR (#19356) that should fix this - it makes the `iteratee` implementations more consistent across all functions. Once it's merged, the iteratees should accept any return value, not just `true` or `false`.

**Comment by pocesar** [comment]
es2015 lib does this using `value is S` as the return of the predicate

![image](https://user-images.githubusercontent.com/461084/29748367-f226528a-8aeb-11e7-995a-c7bd3f85809e.png)

**Comment by aj-r** [comment]
Heads up: this will be broken in #20795. See the [discussion](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20795#discussion_r147290556) there for the reasons why. The expected usage is for the callback to return `boolean` (not `boolean | undefined`), and use `!!` when necessary to convert your return value to a boolean. e.g.:

```
_.filter(recipients, (recpt) => (
  recpt.type === 'orgao' && !!recpt.groups && recpt.groups.indexOf(req.params['group']) !== -1
))
```
