### ISSUE TITLE
@types/elasticsearch Client.close() is absent

### ISSUE THREAD

**Issue by dab00** [DefinitelyTyped/DefinitelyTyped#19021]
- [x] I tried using the `@types/elasticsearch ` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @anselmstordeur @pushplay @andy-ms 

Please update class Client:
```
export class Client {
  // ...
  close(): void;
}
```
Client actually has method close()

**Comment by pushplay** [comment]
This was also mentioned in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15202 but looks like it didn't make it into the associated PR.

**Comment by dab00** [comment]
Closed by [#19023](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19023)
