### ISSUE TITLE
compilation failure for @types/sinon-chai

### ISSUE THREAD

**Issue by pratRockss** [DefinitelyTyped/DefinitelyTyped#19025]
I am using @types/sinon-chai 2.7.27.

When i do the npm start i am getting following errors,

 [default] D:\node_modules\@types\sinon\index.d.ts:19:19
     Duplicate identifier 'Sinon'.
 [default] D:\node_modules\@types\sinon\index.d.ts:100:21
     A parameter initializer is only allowed in a function or constructor
entation.
 [default] D:\node_modules\@types\sinon\index.d.ts:100:29
     Cannot find name 'keyof'.
 [default] D:\node_modules\@types\sinon\index.d.ts:100:35
     '=' expected.
 [default] D:\node_modules\@types\sinon\index.d.ts:156:21
     A parameter initializer is only allowed in a function or constructor
entation.
 [default] D:\WBM_repo\wbm\node_modules\@types\sinon\index.d.ts:156:29
     Cannot find name 'keyof'.
 [default] D:\node_modules\@types\sinon\index.d.ts:156:35
     '=' expected.
 [default] D:\node_modules\@types\sinon\index.d.ts:157:21
     A parameter initializer is only allowed in a function or constructor
entation.
 [default] D:\node_modules\@types\sinon\index.d.ts:157:29
     Cannot find name 'keyof'.
 [default] D:\node_modules\@types\sinon\index.d.ts:157:35
     '=' expected.
 [default] D:\node_modules\@types\sinon\index.d.ts:548:9
     A computed property name must be of type 'string', 'number', 'symbol'
any'.
 [default] D:\node_modules\@types\sinon\index.d.ts:548:10
     Cannot find name 'P'.
 [default] D:\node_modules\@types\sinon\index.d.ts:548:15
     Cannot find name 'keyof'.
 [default] D:\node_modules\@types\sinon\index.d.ts:548:21
     ']' expected.
 [default] D:\node_modules\@types\sinon\index.d.ts:548:21
     Cannot find name 'TType'.
 [default] D:\node_modules\@types\sinon\index.d.ts:548:26
     ';' expected.
 [default] D:\node_modules\@types\sinon\index.d.ts:548:27
     Declaration or statement expected.
 [default] D:\node_modules\@types\sinon\index.d.ts:548:29
     Cannot find name 'SinonStub'.
 [default] D:\\node_modules\@types\sinon\index.d.ts:550:1
     Declaration or statement expected.
 [default] D:\\node_modules\@types\sinon\index.d.ts:552:15
     Duplicate identifier 'Sinon'.
 [default] Checking finished with 20 errors

Any help on how can i resolve above issues?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
