### ISSUE TITLE
Owl Carousel 2 Types

### ISSUE THREAD

**Issue by furdzik** [DefinitelyTyped/DefinitelyTyped#19030]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dpiatkowski

Hi,
I using TypeScript in my project and wanted to use Owl Carousel 2, but there is no types for it (there is for previous version Owl Carousel). 
Is there a posibility to add types for Owl Carousel 2 as well?

**Comment by igorissen** [comment]
I have just created typings for OwlCarousel2 library. Check this pull request #19266

**Comment by furdzik** [comment]
Thank You :)

**Comment by malalancette** [comment]
@igorissen, thanks for creating this typings, but it seems it's missing the "autoHeight" plugin option. 

"autoHeightClass" is there, but not "autoHeight".

Is it possible that you implement it?

Thanks

**Comment by igorissen** [comment]
Hello @malalancette, I'll not have time this month to do this modification.
Can you make a pull request?
