### ISSUE TITLE
sinon.stub errors with private/protected methods

### ISSUE THREAD

**Issue by Dante-101** [DefinitelyTyped/DefinitelyTyped#19055]
- [x] I tried using the `@types/sinon` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @deadalusai @mrbigdog2u @rationull @lumaxis @nicojs @43081j

In `SinonStubStatic` using `keyof T` in `<T>(obj: T, method: keyof T): SinonStub;` prevents stub creation for methods declared private in `T`. Most of the times, people stub a private function (for e.g. async operation) to test a functionality. 

Can we revert it to `(obj: any, method: string): SinonStub;`?

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4753cb27edd3ec639b46da8f1ac85884cc00e522

**Comment by nicojs** [comment]
I actually like the signature a lot. It prevented me from stubbing `writeFile` on `path` earlier today (that method does not exist). I also think stubbing private interfaces shoulf be avoided, because it can make tests brittle. You can work around it using an `any` cast. So i can would leave it as it is

**Comment by Dante-101** [comment]
Sorry about the spam. I accidentally ended up pressing close issue button twice! :-|

**Comment by Dante-101** [comment]
I was new to Sinon and using generics in Typescript. After writing a lot of code in Typescript involving generics and inheritance, I also believe this is a better strategy. It aligns with the Typescript design goal number 1 - "Statically identify constructs that are likely to be errors.". 

Thanks! 

Finally closing the issue. 😅
