### ISSUE TITLE
Typescript 2.4 error for webdriver.io "LogPreferenceType don't contain Log types"

### ISSUE THREAD

**Issue by sanyamc-msft** [DefinitelyTyped/DefinitelyTyped#19100]
- [ ] I tried using the `@types/webdriverio package and had problems with typescript 2.4 version
Specially the problems were with logpreference type as they don't include 'browser' and other types; mentioned at https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#log-type

**Comment by uniqueiniquity** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32490
