### ISSUE TITLE
[d3-selection] Selection returned from ".append()" should use current selection's as parent

### ISSUE THREAD

**Issue by cvsguimaraes** [DefinitelyTyped/DefinitelyTyped#19125]
The [current declaration of `selection.append()`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a870cb6d5f2bb38525b889efd7342617d0d2a08e/types/d3-selection/index.d.ts#L473) is using `PElement` and `PDatum` as element and data types of the new selection's parent.

Unless there's some particular D3 behavior I'm not aware of, the return type should be `Selection<ChildElement, Datum, GElement, Datum>`.

cc @tomwanzek Please let me know if my suspicious is correct...

And as always. thanks again for everyone's work on these modules. The more I use it, more I realized how extensive is the API you guys covered. :heart:

**Comment by tomwanzek** [comment]
@cvsguimaraes It seems to me the definitions are in line with the actual behavior of `append(...)` in D3v4 as per [its API documentation](https://github.com/d3/d3-selection#selection_append). Specifically, it states:

> Each new element inherits the data of the current elements, if any, in the same manner as selection.select.

The key phrase being "in the same manner as selection.select". The [latter's API documentation](https://github.com/d3/d3-selection#selection_select) contains the paragraph:

> Unlike selection.selectAll, selection.select does not affect grouping: it preserves the existing group structure and indexes, and propagates data (if any) to selected children. Grouping plays an important role in the data join. See Nested Selections and How Selections Work for more on this topic.

In the code for internally invoked by the `append(...)` method, the parent(s) are preserved as part of the group structure as seen [here](https://github.com/d3/d3-selection/blob/4fe82033967a4d92bdc969ae38677788017440da/src/selection/select.js#L16).

I am copying @gustavderdrache in case I am overlooking something here.

**Comment by gustavderdrache** [comment]
The documentation is right, and we can observe it in the browser console:

```js
> const p = d3.select(document.body).append('p');

// Nothing up my sleeve:
> p.datum();
undefined

// Append a <span> with a string datum
> p.datum('abc').append('span').datum();
"abc"

// Append a <span> with a number datum
> p.datum(123).append('span').datum();
123
```

When I put this in my VS Code, I get no type errors (and can see that the return value of datum() is indeed inferred correctly):

```ts
const stringDatum: string = d3.select(document.body)
  .append('p')
  .datum('abc') // the selection is now a Selection<string, ...> here
  .append('span')  // as is the newly-created child
  .datum();

const numberDatum: number = d3.select(document.body)
  .append('p')
  .datum(123) // the selection is now a Selection<number, ...> here
  .append('span')  // as is the newly-created child
  .datum();
```

Hope that clears things up. It's a bit subtle, but the whole point of TypeScript is to have a compiler double-check our work :)

**Comment by tomwanzek** [comment]
@cvsguimaraes Did the above two comments and references clarify matters or do you have a follow-on question? To expand on @gustavderdrache's example, see the selection parent in the below screenshot:

![append screen capture](https://user-images.githubusercontent.com/16323903/30133790-191a2242-9323-11e7-9089-c62120f08135.PNG)

The `_parents` elements array contains only one element with value `null`, which is the parent "element" of the `<p>` element selection returned by `append('p')`. In turn this is the parent element returned by the initial chained `d3.select(document.body)` selection.

All of this is aligned with the TS definitions:

```ts
    d3.select<HTMLElement, undefined>(document.body)
      .append<HTMLParagraphElement>('p')
      .datum('abc')
      .append<HTMLSpanElement>('span');
```
This will indeed return a selection of type: `Selection<HTMLSpanElement, string, null, undefined>`.

**Comment by cvsguimaraes** [comment]
@tomwanzek Yeah its clear now, thanks guys!
So basically `_parents` doesn't necessarily refers to the actual DOM structure and that was my misunderstanding.

**Comment by cvsguimaraes** [comment]
@tomwanzek Yeah its clear now, thanks guys!
So basically `PElement` and `PDatum` refers to the selection `_parents` which not necessarily refers to the actual DOM structure and this was what I was misunderstanding.

<details>
 <summary>This code</summary>

```typescript
let p = d3.select(document.body).append('p')

let b = p.selectAll('b')
	.data<number>([42, 24])
	.enter()
	.append('b')
	.text(d => d[0])

let i = b.append('i').datum('xxx')

console.log(p)
console.log(b)
console.log(i)
```
</details>

<details>
 <summary>Produces</summary>
The `i` selection with `p` in its `_parents`;

![screenshot from 2017-09-06 19-20-02](https://user-images.githubusercontent.com/1047033/30137252-d4614958-9338-11e7-8a7e-7597c9683f0e.png)
</details>
