### ISSUE TITLE
Need typings for INgModelController.$overrideModelOptions and/or INgModelController.$options

### ISSUE THREAD

**Issue by snaptopixel** [DefinitelyTyped/DefinitelyTyped#19136]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @diegovila @thorn0 @calebstdenis @leonard-thieu

Thank you for the hard work on these typings! You can see where the feature was added here:

https://github.com/angular/angular.js/commit/2546c29f811b68eea4d68be7fa1c8f7bb562dc11

**Comment by thorn0** [comment]
A pull request is welcome. :+1:
