### ISSUE TITLE
angular-protractor.d.ts getLocationAbsUrl has wrong type

### ISSUE THREAD

**Issue by panuhorsmalahti** [DefinitelyTyped/DefinitelyTyped#1914]
Hi, I noticed that getLocationAbsUrl on line 775 in angular-protractor/angular-protractor.d.ts should be a promise instead of a string.

You can see the commit for getLocationAbsUrl here: https://github.com/angular/protractor/pull/254/files

**Comment by cnishina** [comment]
@andy-ms This should be closed since angular-protractor does not exist.
