### ISSUE TITLE
passport-jwt missing fromAuthHeaderAsBearerToken

### ISSUE THREAD

**Issue by mtpultz** [DefinitelyTyped/DefinitelyTyped#19154]
- [x] I tried using the `@types/passport-jwt` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @MugeSo 

The passport-jwt typings appear to be out-of-date.  I noticed that `fromAuthHeader` is now `fromAuthHeaderAsBearerToken`.  I forked the repo and was going to PR an update, but I'm not sure what to do outside of this change, or if more was even needed.

**Comment by AlainD-** [comment]
I also need this declaration so that we can use passport v3.0.0 please.

Thank you in advance.
