### ISSUE TITLE
Can the lodash typings use the more modern 'default' export for the per function export?

### ISSUE THREAD

**Issue by HIMISOCOOL** [DefinitelyTyped/DefinitelyTyped#19153]
I am looking at doing some initial typings for lodash/fp since I really want to use it.
I was looking at how the per function types work and they currently use 
`export = add`
for example

But I tried just now to change it to
`export default add`
meaning in code I can go 
`import add from 'lodash/add'`
and it compiles fine on typescript 2.4.2.
Does anyone see any issues with doing this?

**Comment by aj-r** [comment]
This would probably break things for anyone currently using the module like:

```
import filter = require("lodash/filter");
```

In general I'm a fan of `export default`, but I'm not sure how concerned we should be about breaking changes for things like this.

**Comment by HIMISOCOOL** [comment]
yeah I guess it would, they could just not update ;D
Hopefully we can get some more opinions in here

I could always make it another package but I wouldn't have a clue on what
to name it

**Comment by NaridaL** [comment]
The typings need to mirror the javascript. lodash doesn't use default exports. 
`import add from 'lodash/add'` might make TS happy, but it will break at runtime.
See also https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7896 and https://gist.github.com/albohlabs/1c864d83b17e4e99edff210729327e03

**Comment by fend25** [comment]
@aj-r
How about new major version of typings?
It's breaking change, but new users has to write comment in code like "I'm very sorry for this" and paste a link to this issue. 
There are some important features that developers has to stay in code for compatibility, i. e. we can't drop off some lodash method. I think this issue is not such case. We should stop using old syntax and migrate to the new one.

**Comment by aj-r** [comment]
@fend25 That still doesn't address @NaridaL 's issue - the type definitions need to match what lodash actually does. Changing to `export default` requires a change to the lodash source code as well.

**Comment by aj-r** [comment]
@HIMISOCOOL It turns out that `lodash-es` was created for this exact purpose. So you can do:

```ts
import add from 'lodash-es/add';
```

If that works for you, then we can probably close this issue.

**Comment by aj-r** [comment]
update: in typescript 2.7, you can set `"esModuleInterop": true`, and the default import syntax will work even with plain `lodash`.

e.g. in `tsconfog.json`:

```json
{
  "compilerOptions": {
      "module": "commonjs", // or amd/umd
      "esModuleInterop": true
  }
}
```

then in your `.ts` file:

```ts
import _ from "lodash";
```

So you only need `lodash-es` if you're actually targeting an ecmascript module.
