### ISSUE TITLE
New definition (types/js.spec) not published after 5 days

### ISSUE THREAD

**Issue by mattbishop** [DefinitelyTyped/DefinitelyTyped#19163]
A recent definition was merged into master and passed travis builds, but has not made it's way to npmjs. Other package changes around the same time have been published (for instance, msgpack), so not sure how to diagnose what went wrong.

Here is the merged PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19078

Here is the travis job:
https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/265667146

I have seen other people have issues where publishing takes 24-48 hours. This has been 3 days.

**Comment by piuccio** [comment]
Is this why now I get `npm ERR! fetch failed https://registry.npmjs.org/@types/express-serve-static-core/-/express-serve-static-core-4.0.49.tgz` in my travis builds?

**Comment by andy-ms** [comment]
`@types/js.spec` published. Sorry for the delay!
@piuccio I don't think that problem is related; If you are running `npm install` you should get the latest version that *has* been published, it shouldn't be affected by a delay in publishing a newer version. Might just be a temporary NPM error?

**Comment by mattbishop** [comment]
Thanks I was able to start using it now.
