### ISSUE TITLE
@types/jasmine-enzyme does not contain function type

### ISSUE THREAD

**Issue by bkazi** [DefinitelyTyped/DefinitelyTyped#19179]
- [x] I tried using the `@types/jasmine-enzyme` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bolatovumar 

The [usage](https://github.com/blainekasten/enzyme-matchers/blob/master/packages/jest-enzyme/README.md) for `jasmine-enzyme` package requires importing a `jasmineEnzyme` function from the package
`@types/jasmine-enzyme` does not declare this type or export it, so this throws a `@types/jasmine-enzyme/index.d.ts' is not a module.` error in TypeScript

**Comment by bolatovumar** [comment]
Hey @bkazi, thanks for reporting the issue.
Can you provide a code sample that gives you this error so I can replicate the issue you are having?

**Comment by bkazi** [comment]
Running the tests work since I'm using Karma and it doesn't fail on type errors
The tests do not run without the `beforeEach` block

https://gist.github.com/bkazi/b625eb3ec101c0f77707d27b8a4bc79e

**Comment by bolatovumar** [comment]
Thanks. I will take a look when I get a chance.

**Comment by bolatovumar** [comment]
@bkazi, I added the code to export jasmineEnzyme as a module. Try it and let me know if you run into any issues.

**Comment by bkazi** [comment]
It works perfectly! Thank you!
