### ISSUE TITLE
lodash forEach types broken in v4.14.74

### ISSUE THREAD

**Issue by AustinMatherne** [DefinitelyTyped/DefinitelyTyped#19228]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aj-r 

@ types/lodash v4.14.74 is causing type errors in a project I am working on. v4.14.73 works as expected. `event` is any, but it believes `filter` is a string.
```
forEach(event.filters, (filter, name) => {
    ...
});
```

**Comment by aj-r** [comment]
Yeah, I can reproduce this issue if the first argument has type `any`.

I think the best solution is to add the array overload back BEFORE the string overload, e.g.

```
forEach<T>(
    collection: T[],
    iteratee?: ListIterator<T>
): T[];

forEach<TString extends string | null | undefined>(
    collection: TString,
    iteratee?: StringIterator<any>
): TString;

forEach<...>(
...
```

**Comment by Qwerios** [comment]
Can confirm pinning to v4.14.73 fixed my project builds. Tracking this issue for when we can unpin again.

Using TS version 2.4.2

**Comment by tstackhouse** [comment]
Adding that this also is occurring on cases of `_.filter` and likely others.  Pinning to 4.14.73 fixes as well.

**Comment by aj-r** [comment]
@tstackhouse can you show me your code that works in 4.14.73 but not 4.14.74? For me, the first argument has type `{}` in both versions. Here is my code:

```
const obj: any = {};
const res = _.filter(obj, (value, index, coll) => {
    // value: {}
    // index: number
    // coll: ArrayLike<{}>
    return true;
});
```

**Comment by AnWeber** [comment]
an example for this error would be
```
const obj: any = {bar: 'foo'};
let typecheck: string = null;
_.forEach(obj, (_value, name) => {
	typecheck = name; //-> 'bar' (type number)
});
```
