### ISSUE TITLE
nearley types are wrong

### ISSUE THREAD

**Issue by Hardmath123** [DefinitelyTyped/DefinitelyTyped#19255]
I'm the maintainer of nearley, one of the libraries for which this library provides types. I've gotten a [bug report on nearley](https://github.com/Hardmath123/nearley/issues/276) that we traced to an error in this library. Specifically, the following line is incorrect:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/516ed213ca51babea056b771e431109709f1829a/types/nearley/index.d.ts#L62

Other lines might also be wrong, since the nearley team didn't write that file.

(cc @deltaidea @tjvr @notsonotso. @deltaidea is the one who knows how to fix this.)

**Comment by notsonotso** [comment]
@Hardmath123 other lines *are* wrong. It's basically useless as-is.

**Comment by Hardmath123** [comment]
In that case, maintainers, can I ask if we can temporarily remove the "nearley" part of this repository, until the author has time to fix the types? This sounds like it will cause a lot of confusion. At the very least, I feel there should be some kind of warning so that users know that this module is broken.

**Comment by notsonotso** [comment]
I support the removal suggestion... I lost hours due to this.

**Comment by Hardmath123** [comment]
@deltaidea would you be able to create a PR for this project that disables the nearley types? Or perhaps unpublish and deprecate the `@types/nearley` module on npm?

**Comment by Hardmath123** [comment]
(CCing maintainer @andy-ms)

**Comment by andy-ms** [comment]
I've manually added a deprecation message to the package, but I'd rather not delete the types from here so we can see the diff needed to fix the types.
The types are <100 lines long so hopefully it wouldn't be too hard to fix? They were added pretty recently too, in #16937.

**Comment by Hardmath123** [comment]
Thank you @andy-ms for the quick response!

Yes, it would be nice to fix the types — correct types are better than no types! — but neither of the nearley maintainers actually _use_ TypeScript, so we don't know how to fix them. :-)

Perhaps if @deltaidea has some time…?
