### ISSUE TITLE
@types/react: Subsequent variable declarations must have the same type for 'td'

### ISSUE THREAD

**Issue by JonWallsten** [DefinitelyTyped/DefinitelyTyped#19262]
After updating everything to the latest I get the following issue while compiling my code

![image](https://user-images.githubusercontent.com/5993909/29605049-cf293e78-87e9-11e7-870b-37b5505dbd4f.png)

TypeScript @ 2.4.2
react @ 15.6.1,
types/react @ 16.0.4

Please note that it complains even though the interfaces are identical to the letter.
Downgrading to 16.0.1 works.

**Comment by khell** [comment]
Same issue with @types/react@15.6.2.

**Comment by JonWallsten** [comment]
```
rm yarn.lock && yarn
```
This right there did the trick! Closing this.

**Comment by Zerim** [comment]
For anyone else's reference, I was banging my head on this issue for a while and my issue was that I was using CRA to bootstrap a nested project (i.e. in an examples folder) and the TS module resolution was finding `react` both in the new project's `node_modules` and the parent project's `node_modules`

**Comment by lhew** [comment]
I just added `skipLibCheck: true` on `tsconfig.json` and worked like a charm.
