### ISSUE TITLE
transducers-js new compile errors

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#19276]
Due to Microsoft/TypeScript#16368 we are detecting some new compile errors in the tests.
This library heavily uses generic types -- previously when comparing generic types we would squash all type parameters to `any`, making comparisons almost always succeed.
@colinkahn @dphilipson could you look at the new compile errors and see if the type definitions need to be changed?

**Comment by NaridaL** [comment]
I had a look at this...
as far as I can tell, the issue is 
```ts
// compose functions with same signature
export function comp<T extends (x: any) => any>(...args: T[]): T;
// when a function with generic arguments is passed, e.g. a transducer:
export type Transducer<TInput, TOutput> =
    <TResult, TCompleteResult>(
        xf: CompletingTransformer<TResult, TCompleteResult, TOutput>
    ) => CompletingTransformer<TResult, TCompleteResult, TInput>;
declare const a: Transducer<number, number>
declare const b: Transducer<number, number>
const x = comp(a, b)
// TS bricks generic arguments: x has type 
(xf: CompletingTransformer<{}, {}, number>) => CompletingTransformer<{}, {}, number>
// (should be Transducer<number, number>
// this leads to errors further down the line.
```

There isn't a general solution to this issue, so adding a couple of overloads for Transducers (which seem most likely to be used in conjunction with this) is the best solution I can think of.
