### ISSUE TITLE
Semantic ui : progress Element : contradiction between typescript definition and official documentation

### ISSUE THREAD

**Issue by JosephCaillet** [DefinitelyTyped/DefinitelyTyped#19320]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu
https://semantic-ui.com/modules/progress.html#/usage

According to this [page](https://semantic-ui.com/modules/progress.html#/usage),  by default the call
`$('myProgress).progress('increment')`
will increments progress by 1. So the correct typescript prototype should be:
`(behavior: 'increment', incrementValue = 1): JQuery;`
instead of:
`(behavior: 'increment', incrementValue: number): JQuery;`
The same goes for the decrementation form of this call.

**Comment by leonard-thieu** [comment]
Will be fixed by #19322. Thanks for reporting this.
