### ISSUE TITLE
Definitions for Vue

### ISSUE THREAD

**Issue by Bartvds** [DefinitelyTyped/DefinitelyTyped#1933]
http://vuejs.org/

> Vue.js is a library for building interactive web interfaces.
> It provides data-driven components with a simple and flexible API.

It was mentioned in vue's own tickets (https://github.com/yyx990803/vue/issues/208) but let's track it here too.

Please check both threads and leave a message if you do want to work on this so we don't duplicate effort.

**Comment by kaorun343** [comment]
This issue can be closed because of the current status of Vue.js ( Vue's repository bundles its definition files)
