### ISSUE TITLE
@types/ramda string input to "prop" is not type checked

### ISSUE THREAD

**Issue by jakelazaroff** [DefinitelyTyped/DefinitelyTyped#19346]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @donnut @mdekrey @LiamGoodacre @mrdziuban @sbking @afharo @teves-castro @hojberg 

`prop` doesn't do any sort of check for whether the given property exists on the object. It could be tightened up with this annotation:

```typescript
prop<T> (p: keyof T, obj: T): T[keyof T];
prop<T> (p: keyof T): (obj: T) => T[keyof T];
```

Opening an issue rather than a PR because I'm not sure whether this sort of stringency is even a goal of these types, and I imagine this has the potential to break a lot of code that uses this function.

**Comment by tycho01** [comment]
@jakelazaroff consider trying the typings at [`types/npm-ramda`](https://github.com/types/npm-ramda/), it should fix this and many other typing issues with Ramda. For reference, here are the cases it internally handles for [`prop`](https://github.com/types/npm-ramda/blob/dist/src/prop.d.ts). (These are generated, so not so much optimized for looking at, but more so for getting types right.)

**Comment by borekb** [comment]
`R.prop` is now typed as suggested:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/485d5a96dbec7798394f9843ed9ee38b4a6d05ab/types/ramda/index.d.ts#L2536-L2542

I believe this issue can be closed.
