### ISSUE TITLE
@types/ejs New Options Available for Render

### ISSUE THREAD

**Issue by H2O-2** [DefinitelyTyped/DefinitelyTyped#19352]
- [x] I tried using the `@types/ejs` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @benliddicott 

EJS had a number of new options for rendering available at its [Github Page](https://github.com/mde/ejs), including `filename`, `root`, `rmWhitespace`, etc. Can you update the type definition to reflect these changes please, thank you.

**Comment by msokk** [comment]
@H2O-2 All these variables exist in current definition options, so not an issue anymore?
