### ISSUE TITLE
Missing options

### ISSUE THREAD

**Issue by bashkos** [DefinitelyTyped/DefinitelyTyped#19385]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b84df2925f6422491be2468ead968c36cb3405c4/types/chart.js/index.d.ts#L311

Missing options:
- borderDash
- borderDashOffset
- zeroLineBorderDash 
- zeroLineBorderDashOffset

**Comment by andy-ms** [comment]
Make a pull request?
