### ISSUE TITLE
typings for lodash _.get aren't right!!!

### ISSUE THREAD

**Issue by BjornMelgaard** [DefinitelyTyped/DefinitelyTyped#19433]
- Authors: @bczengel, @ailrun, @aj-r, @ericanderson, @stepancar, @chrootsu

currently typings for `_.get` are

```
        get<TObject, TResult>(
            object: TObject,
            path: StringRepresentable|StringRepresentable[],
            defaultValue?: TResult
        ): TResult;

        /**
         * @see _.get
         */
        get<TResult>(
            object: any,
            path: StringRepresentable|StringRepresentable[],
            defaultValue?: TResult
        ): TResult;

```
I think its better to make like this

```
        get<TResult, TDefault = undefined>(
            object: any,
            path: StringRepresentable|StringRepresentable[],
            defaultValue?: TDefault
        ): TResult | TDefault;
```
usage

```
const maybePublicPath: string | undefined = get<string>(config, ['output', 'publicPath']) // see, it returns string|undefined instead of just string 
const maybePublicPath2: string | number = get<string, number>(config, ['output', 'publicPath'], 1) // second generic argument cant be inferred,  what a shame
```

why?
typescript have to say me "hey, guy, you have to validate it"

something like this validation I think
```
const maybePublicPath = betterGet<string>(config, ['output', 'publicPath'])
invariant(maybePublicPath, "No publicPath for config: ${config}")
const publicPath = maybePublicPath!
```

**Comment by aj-r** [comment]
Hmm... I agree with you in that the types for `_.get` aren't very good right now. However, it would be nice if the generic arguments could be inferred correctly as much as possible, so you don't need to specify them.

I've actually changed the `_.get` overloads as part of my PR (#19356). Here is my change:

```
get<TObject extends object, TKey extends keyof TObject>(
    object: TObject | null | undefined,
    path: TKey | [TKey],
    defaultValue: TObject[TKey]
): TObject[TKey];

get<TObject extends object, TKey extends keyof TObject>(
    object: TObject,
    path: TKey | [TKey]
): TObject[TKey];

get<TObject extends object, TKey extends keyof TObject>(
    object: TObject | null | undefined,
    path: TKey | [TKey],
): TObject[TKey] | undefined;

get(
    object: any,
    path: Many<StringRepresentable>
): any;

get<TResult>(
    object: any,
    path: Many<StringRepresentable>,
    defaultValue: TResult
): TResult;
```

Why I did it this way:

- If the `path` happens to be a key of your object, we can automatically determine the correct return type
- Return type is possibly `undefined` if no default value is given
- You never need to explicitly pass any type parameters

Note that with this change, `get(config, ['output', 'publicPath'])` would return `any`, so you would need to cast it to the correct type (e.g. `get(config, ['output', 'publicPath']) as string | undefined`, or `const maybePublicPath: string | undefined = get(config, ['output', 'publicPath'])`

If this solution doesn't work for you, let me know why, and I can see if there is a better solution.

**Comment by aj-r** [comment]
Oh, I see your PR is for lodash v3, but mine is for v4. We might as well keep both PRs then, but we should try to use consistent types for both versions.

**Comment by BjornMelgaard** [comment]
@aj-r, thank you for pointing out that I wasnt right (in my pr), let me explain
later I was checking publickPath like this

```
const maybePublicPath = get<string>(config, ['output', 'publicPath'])
invariant(maybePublicPath, "No publicPath for config: ${config}")
const publicPath = maybePublicPath! // validation was successful
```
but what I really want is to check with typeof 
```
const maybePublicPath = get(config, ['output', 'publicPath'])
invariant(
  typeof maybePublicPath === 'string',
  'publicPath must be string',
  { maybePublicPath, config }
)
const publicPath = maybePublicPath as string // validation was successful

```
this is the reason why function `Json.parse(string): any` is better than `parseJson<T>(json: string): T;`

so, whatever, I hope when ts will support elvis notation, days will be better

**Comment by BjornMelgaard** [comment]
@aj-r, consider this get types

```
        // when object is empty - defenitely default value will be returned
        get<TKey, TDefault = undefined>(
            object: null | undefined,
            path: TKey | [TKey],
            defaultValue?: TDefault
        ): TDefault;

        // when depth of object is 1 and path to value is right - defenitely value will be returned
        get<TObject extends object, TKey extends keyof TObject>(
            object: TObject,
            path: TKey | [TKey],
            defaultValue?: any
        ): TObject[TKey];

        // in all other cases user must validate outcome in runtime (with typeof for example, NO CASTING WITHOUT VALIDATION!!!)
        get<TExpected, TDefault = undefined>(
            object: any,
            path: StringRepresentable|StringRepresentable[],
            defaultValue?: TDefault
        ): TExpected | TDefault;

```

and tests to first two (any dont need tests :smile:)

```
    {
        // when object is empty - defenitely default value will be returned
        let r1: undefined = _.get(null, 'a')
        let r2: number = _.get(null, 'a', 1)
    }
    {
        // when depth of object is 1 and path to value is right - defenitely value will be returned
        let r1: boolean = _.get({a: true}, 'a')
        let r2: boolean = _.get({a: true}, 'a', 1)
    }
```

**Comment by aj-r** [comment]
@BjornMelgaard not a bad idea. I like the first overload (when object is empty - definitely default value will be returned).

The I don't think the second overload is right because `TObject[TKey]` could be undefined, in which case the default value could still be used. For example:

```
let obj: { foo?: number | undefined } = {};

let result = _.get(obj, "foo", "bar"); // will return "bar" if foo is undefined
```

**Comment by BjornMelgaard** [comment]
sooo ... that mean that we can left only first and third definition?

**Comment by aj-r** [comment]
not necessarily... we could only support `TKey` if `defaultValue` is not specified (like in my previous comment)

**Comment by BjornMelgaard** [comment]
ah, right
```
        // when object is empty - defenitely default value will be returned
        get<TDefault = undefined>(
            object: null | undefined,
            path: any,
            defaultValue?: TDefault
        ): TDefault;

        // when depth of object is 1 and path to value is right - defenitely value will be returned
        get<TObject extends object, TKey extends keyof TObject>(
            object: TObject,
            path: TKey | [TKey]
        ): TObject[TKey];

        // in all other cases user must validate outcome in runtime (with typeof for example, NO CASTING WITHOUT VALIDATION!!!)
        get(
            object: any,
            path: StringRepresentable|StringRepresentable[],
            defaultValue?: any
        ): any;

```

**Comment by aj-r** [comment]
Yeah. I also added a second version of the `TKey` overload in case `object` is `object | null | undefined`. It would also be nice to avoid `<TDefault = undefined>` if possible - then we could keep the typescript version at 2.2 and avoid bumping up to 2.3. We can do this by splitting into 2 different overloads. So maybe something like this (changes marked with **):

```
        // when object is empty - definitely default value will be returned
        get<TDefault>(
            object: null | undefined,
            path: Many<StringRepresentable>, // ** Many<StringRepresentable> instead of any
            defaultValue: TDefault
        ): TDefault;

        // ** same as above, but with no default value
        get(
            object: null | undefined,
            path: Many<StringRepresentable>
        ): undefined;

        // when depth of object is 1 and path to value is right - defenitely value will be returned
        get<TObject extends object, TKey extends keyof TObject>(
            object: TObject,
            path: TKey | [TKey]
        ): TObject[TKey];

        // ** same as above, but handles the case where object might be null or undefined
        get<TObject extends object, TKey extends keyof TObject>(
            object: TObject | null | undefined,
            path: TKey | [TKey]
        ): TObject[TKey];

        // in all other cases user must validate outcome in runtime (with typeof for example, NO CASTING WITHOUT VALIDATION!!!)
        get(
            object: any,
            path: Many<StringRepresentable>,
            defaultValue?: any
        ): any;
```

**Comment by BjornMelgaard** [comment]
@aj-r , I made pr with this types 

```
        // when object is empty - definitely default value will be returned
        get<TDefault>(
            object: null | undefined,
            path: Many<StringRepresentable>, // ** Many<StringRepresentable> instead of any
            defaultValue: TDefault // ** no longer optional
        ): TDefault;

        // ** same as above, but with no default value
        get(
            object: null | undefined,
            path: Many<StringRepresentable>
        ): undefined;

        // when depth of object is 1 and path to value is right - or value, or default will be returned (in case value is undefined)
        get<TObject extends object, TKey extends keyof TObject, TDefault>(
            object: TObject,
            path: TKey | [TKey],
            defaultValue: TDefault // ** no longer optional
        ): TObject[TKey] | TDefault;

        // ** same as above, but with no default value
        get<TObject extends object, TKey extends keyof TObject>(
            object: TObject,
            path: TKey | [TKey]
        ): TObject[TKey];

        // when object may or may not arrive
        get<TObject extends object, TKey extends keyof TObject, TDefault>(
            object: TObject | null | undefined,
            path: TKey | [TKey],
            defaultValue: TDefault
        ): TObject[TKey] | TDefault;

        // ** same as above, but with no default value
        get<TObject extends object, TKey extends keyof TObject>(
            object: TObject | null | undefined,
            path: TKey | [TKey]
        ): TObject[TKey] | undefined;

        // in all other cases user must validate outcome in runtime (with typeof for example, NO CASTING WITHOUT VALIDATION!!!)
        get(
            object: any,
            path: Many<StringRepresentable>,
            defaultValue?: any
        ): any;

```

**Comment by a-tarasyuk** [comment]
@aj-r I have a question about new interfaces for `_.get`:

```
interface IProps {
  value?: string;
  name?: string;
}

interface IDynamicKeys {
  field: string;
}

const props: IProps = {
  name: 'Name',
}

const dynamicKeys: IDynamicKeys = {
  field: 'name',
};
```

`lodash <= 4.14.74`, as a result should be `string`
`const item = get<string>(props, dynamicKeys.field);`

Latest `lodash` version: 
`const item = get<string>(props, dynamicKeys.field);`
Obviously, this code does not work with new interfaces. 

Let's try to follow new interfaces. 

1. `const item = get<IProps, string>(props, dynamicKeys.field);`
2. `const item = get<IProps, string, string>(props, dynamicKeys.field);`
3. `const item = get<IProps, string, string>(props, dynamicKeys.field, '');`

> TKey extends keyof TObject
>    type 'string' does not satisfy the constaint '"value" | "name"'

As we can see, we can not use `string` as `key` type. Is there any way to set **Input** type, **Key** type, **DefaultValue** type? 

I can skip types definition, like so - `const field: string = _.get(props, dynamicKeys.field, '')`, however, I don't think this is a good solution. 

[`Demo`](https://codesandbox.io/s/43oxqz87o9)

**Comment by aj-r** [comment]
@a-tarasyuk You have a couple of options:

1. The easy option: just pass in a string, and let `_.get` return `any`. This is actually preferred over the old method of passing `<string>` as a type constraint (see [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes)).
    ```
    // I believe the correct type here is actually string | undefined (if strictNullChecks is enabled)
    const item: string | undefined = get(props, dynamicKeys.field);
    ```

2. Add an index signature to `IProps`. This effectively makes `keyof IProps = string`.
    ```
    interface IProps {
      [key: string]: string | undefined;
      value?: string;
      name?: string;
    }
    const item = get(props, dynamicKeys.field); // Returns string | undefined
    ```

3. Change `dynamicKeys.field` to use type `'name'` instead of type `string`. This will probably require you to make `IDynamicKeys` into a generic type, so I don't know if this will work for you.
    ```
    interface IDynamicKeys<T> {
      field: keyof T;
    }
    const dynamicKeys: IDynamicKeys<IProps> = {
        field: 'name', // now field has type 'name' | 'value'
    };
    const item = get(props, dynamicKeys.field); // Returns string | undefined
    ```

In general, you should not need to explicitly pass type constraints in lodash functions anymore.

**Comment by a-tarasyuk** [comment]
@aj-r Thanks for your answer. 

1. If I need only one type - `string`, is this acceptable?
    `const field: string = _.get(props, dynamicKeys.field, '')`

2. I'll check it

3. > I don't know if this will work for you.

   You are right, it will not work, as `field` can have different names not only couple predefined values 


> In general, you should not need to explicitly pass type constraints in lodash functions anymore.

You mean that explicitly pass types like so `get<IProps, string, string>(props, dynamicKeys.field);` is useless., am I right?

**Comment by aj-r** [comment]
@a-tarasyuk 

1. That is acceptable as long as `strictNullChecks` is disabled in your project. If you have `strictNullChecks` enabled, then I think it should be `string | undefined`, since `IProps` indicates that name could be undefined. I believe that if `props.name` exists and is set to `undefined`, `_.get` will return `undefined`, NOT your default value of `''`. `_.get` will only return the default value of the `name` property doesn't exist at all (at runtime).

> You mean that explicitly pass types like so get<IProps, string, string>(props, dynamicKeys.field); is useless., am I right?

Yes, that is useless. The point of the generic type constraints is to constrain 2 or more values in the function - either 2 parameters, or a parameter and a return value. In nearly all situations (at least in lodash), the compiler should be able to automatically detect the correct value to use for the type constraint.

**Comment by kelly-tock** [comment]
I know this closed, but how are deeply nested values supposed to be validated at all?  the current key of is only one level deep, right?  this can hide changes in property names in nested objects. was wondering if there is a way to do this with the current types?

**Comment by aj-r** [comment]
There is no way to do this that I'm aware of... the best workaround I can think of is to call `_.get()` multiple times (once for each level of nesting).

**Comment by lafiosca** [comment]
@aj-r 

>  I believe that if `props.name` exists and is set to `undefined`, `_.get` will return `undefined`, NOT your default value of `''`. `_.get` will only return the default value of the `name` property doesn't exist at all (at runtime).

I'm sorry to jump in here way late, but this does not appear to be the case, at least with the current version of lodash (4.17.11):

```
> const lodash = require('lodash');
undefined
> let x = { a: 1, b: undefined };
undefined
> x
{ a: 1, b: undefined }
> lodash.get(x, 'a', 99)
1
> lodash.get(x, 'b', 99)
99
> lodash.get(x, 'c', 99)
99
```

I ended up here because I was searching for info on this very problem:

```
const currentStep = lodash.get(this.props, 'currentStep', 0);
```

Without specifying the generics, the typings are saying that `currentStep` is `number | undefined` when it should just be `number`. I figure I'll just work around this for now by adding a bang to the end:

```
const currentStep = lodash.get(this.props, 'currentStep', 0)!;
```

Thanks,
/joe

**Comment by aj-r** [comment]
Interesting, looks like I was wrong. Anyways, I believe someone just
submitted a fix for this (since we can finally use TS2.8), so try updating
to the latest version.
