### ISSUE TITLE
@types/hapi: Request.response can be a Boom.BoomError

### ISSUE THREAD

**Issue by dboune** [DefinitelyTyped/DefinitelyTyped#19443]
- [ x ] I tried using the `@types/hapi` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jasonswearingen @AJamesPhillips 

`Request.response` may be a Boom object, most likely to occur in an ext like `onPreResponse`. The class definition currently includes some of the Boom properties, like `output`, but misses others, such as `isServer`.

Instead of adding every possible BoomError related property, I believe the alternative is to include `Boom.BoomError` as a possible type for the response.

See here for an example.
https://github.com/dboune/DefinitelyTyped/commit/f4c67c1122e3f10a26469f0ce06dd1924300580d#diff-074ce399e85a82d31a5349f977d389be

I do not know this method is considered appropriate here. If it is, I can clean this up further and submit a PR.

**Comment by AJamesPhillips** [comment]
Hi @dboune, thanks for this.  Sorry for taking a while to get back to you.  In the hapi docs it doesn't currently mention the `isServer()` method.  See the section under "The response object provides the following methods:" at https://hapijs.com/api/16.1.1#response-object  If you could point to the source code, or a test file, or preferably get these docs changed in the hapi repo I'd feel more comfortable about including this in the typings definition as I haven't had a chance to review it properly myself.

As you can see in the current typings we do have `isBoom`, `isMissing`, and `output` which I added after finding them in the source code / examples.  Hence the TODO of "TODO update once Hapi docs describes explicitly".

For now I'd suggest you add the `isServer()` method here with a similar message.  Preferably also filing a PR with hapi to update the docs.

**Comment by dboune** [comment]
@AJamesPhillips no worries. Thanks for your reply!

I miswrote. `isServer` is a property, not a method. I've corrected that above. It is specifically of Boom. I did not intend to suggest that it should be added here, and I do not believe that it should be.

In fact I'm pretty sure `output` shouldn't be here. That is a Boom specific item as far as I know, and while sometimes the Response is actually a BoomError, and thus you can use it in those cases, I don't believe it is present.

From what I can tell, isBoom and isMissing also don't actually exist either, but `if (response.isBoom)` remains the in-practice test to determine if the object is a response, or a BoomError. This is seen in various places throughout the Hapi source code.

In a quick look around I wasn't able to find anywhere that the Response object is extended such that it would include isBoom and the others mentioned. I do see that it extends Podium, but that is all I could find.

---
### Following the reply

Following from `reply()` I can see that it calls `Response.wrap()`
https://github.com/hapijs/hapi/blob/master/lib/reply.js#L167

`Response.wrap()` either calls `Boom.boomify` on the result if it is an `Error`, or builds a new Response object, and then returns whichever.
https://github.com/hapijs/hapi/blob/master/lib/response.js#L61

Back in `reply()`, if the reply is a boom object, it is passed down the chain. _Whatever else is happening, we know that the response could be a BoomError._

*Example use:*
```javascript
    server.ext({
      type: 'onPreResponse',
      method: function (request, reply) {

        if (!request.response || !request.response.isBoom) {
          return reply.continue()
        }

        // We now know that the response is a BoomError

        const error = request.response as Boom.BoomError // This is currently an error
        
        // ...
        
      }
    })
```
---

To reiterate, I do not think it would be appropriate to add isServer, or any other Boom specific property excepting isBoom due to the use, unless it can be made clear that they exist somehow on a non-error Response object.

We absolutely can know that `Request.response` may be a BoomError, and knowing this then gives us access to other Boom specific properties, after of course having tested if the object is one.

**Comment by dboune** [comment]
BTW: I'm going to try some tests later if I can get to it, to see what the shape of both Response and BoomError are in a live process.

**Comment by dboune** [comment]
I apologize for the delay.

Here is my very simple test.

```ts
server.ext('onPreResponse', (request: Request, reply: ReplyWithContinue) => {
  console.log(request.response)
})
```

I then made two requests, one which was made broken to error, and one which was allowed to succeed.

### Error Response

This is very clearly a BoomError, not a Response.

```js
  data: undefined,
  isBoom: true,
  isServer: true,
  output:
   { statusCode: 500,
     payload:
      { statusCode: 500,
        error: 'Internal Server Error',
        message: 'An internal server error occurred' },
     headers: {} },
  reformat: [Function],
  typeof: [Function],
  isDeveloperError: true }
```

### Successful Request

A Response object, and does NOT include isBoom, isServer, output, etc.

```js
{ _eventListeners:
   { finish: { handlers: null, flags: [Object] },
     peek: { handlers: null, flags: [Object] } },
  _notificationsQueue: [],
  _eventsProcessing: false,
  _sourcePodiums: [],
  onPodiumError: null,
  request:
   { _eventListeners: { finish: [Object], peek: [Object], disconnect: [Object] },
     _notificationsQueue: [],
     _eventsProcessing: false,
     _sourcePodiums: [],
     onPodiumError: [Function],
     _bench: { ts: 2814881720.2628 },
     connection:
      { _eventListeners: [Object],
        _notificationsQueue: [],
        _eventsProcessing: true,
        _sourcePodiums: [Object],
        onPodiumError: null,
        settings: [Object],
        server: [Object],
        type: 'tcp',
        _started: true,
        _connections: [Object],
        _onConnection: [Function],
        registrations: [Object],
        _extensions: [Object],
        _requestCounter: [Object],
        _load: [Object],
        _compression: [Object],
        states: [Object],
        auth: [Object],
        _router: [Object],
        plugins: {},
        app: {},
        listener: [Object],
        info: [Object] },
     server:
      { _settings: [Object],
        _caches: [Object],
        _handlers: [Object],
        _methods: [Object],
        _events: [Object],
        _dependencies: [Object],
        _registrations: [Object],
        _heavy: [Object],
        _mime: [Object],
        _replier: [Object],
        _requestor: [Object],
        _decorations: [Object],
        decorations: [Object],
        _plugins: [Object],
        _app: {},
        _registring: false,
        _state: 'started',
        _extensionsSeq: 6,
        _extensions: [Object],
        _eventListeners: [Object],
        _notificationsQueue: [],
        _eventsProcessing: false,
        _sourcePodiums: [],
        onPodiumError: null,
        _parent: null,
        root: [Circular],
        app: {},
        connections: [Object],
        load: [Object],
        methods: {},
        mime: [Object],
        plugins: [Object],
        settings: [Object],
        version: '16.6.0',
        realm: [Object],
        auth: [Object],
        cache: [Object],
        info: [Object],
        listener: [Object],
        registrations: [Object],
        views: [Function],
        render: [Function]
     url:
      Url {
        protocol: null,
        slashes: null,
        auth: null,
        host: null,
        port: null,
        hostname: null,
        hash: null,
        search: '',
        query: {},
        pathname: '/api/users',
        path: '/api/users',
        href: '/api/users' },
     query: {},
     path: '/api/users',
     method: 'post',
     mime: 'application/x-www-form-urlencoded',
     headers:
      { host: 'localhost:8080',
        connection: 'keep-alive',
        'content-length': '59',
        accept: 'application/json',
        'postman-token': '162bbab1-8dbe-e276-1e30-6bac99136289',
        'cache-control': 'no-cache',
        origin: 'chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36',
        'content-type': 'application/x-www-form-urlencoded',
        dnt: '1',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'en-US,en;q=0.8,en-GB;q=0.6' },
     info:
      { received: 1505922879019,
        responded: 0,
        remoteAddress: '127.0.0.1',
        remotePort: 50123,
        referrer: '',
        host: 'localhost:8080',
        hostname: 'localhost',
        acceptEncoding: 'gzip' },
     setUrl: undefined,
     setMethod: undefined,
     id: '1505922879019:localhost:2462:j7t7lgpo:10000',
     app: {},
     plugins: {},
     _route:
      { settings: [Object],
        connection: [Object],
        server: [Object],
        path: '/api/users',
        method: 'post',
        plugin: [Object],
        _special: false,
        _analysis: [Object],
        params: [],
        fingerprint: '/api/users',
        public: [Object],
        _prerequisites: null,
        _extensions: [Object],
        _cycle: [Object] },
     route:
      { method: 'post',
        path: '/api/users',
        vhost: undefined,
        realm: [Object],
        settings: [Object],
        fingerprint: '/api/users',
        auth: [Object] },
     auth:
      { isAuthenticated: false,
        credentials: null,
        artifacts: null,
        strategy: null,
        mode: null,
        error: null },
     pre: {},
     preResponses: {},
     orig: { payload: [Object] },
     params: {},
     paramsArray: [],
     payload:
      { firstName: ‘Test’,
        lastName: ‘User’,
        email: 'testuser@example.com' },
     state: {},
     jsonp: null,
     response: [Circular],
     raw: { req: [Object], res: [Object] },
     addTail: [Function],
     tail: [Function],
     _states: {},
     _entity: {},
     _logger: [],
     _allowInternals: false,
     _expectContinue: false,
     _isPayloadPending: false,
     _isBailed: false,
     _isReplied: true,
     _isFinalized: false,
     _tails: {},
     _tailIds: 0,
     _protect: { _error: [Function], logger: [Circular], domain: [Object] },
     domain:
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        members: [] },
     _onEnd: [Function],
     _onClose: [Function],
     _onError: [Function],
     _onAbort: [Function],
     render: [Function],
     _serverTimeoutId:
      Timeout {
        '0': null,
        _called: false,
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 7889,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        domain: [Object] } },
  statusCode: 201,
  headers: {},
  variety: 'plain',
  source:
   { statusCode: 201,
     message: 'User added',
     data:
      { userId: ‘100’,
        firstName: ‘Test’,
        lastName: ‘User’,
        email: 'testuser@example.com' } },
  app: {},
  plugins: {},
  send: null,
  hold: undefined,
  settings:
   { encoding: 'utf8',
     charset: 'utf-8',
     ttl: null,
     stringify: null,
     passThrough: true,
     varyEtag: false,
     message: null },
  _payload: null,
  _takeover: false,
  _contentEncoding: null,
  _contentType: 'application/json',
  _error: null,
  _processors: { marshal: undefined, prepare: undefined, close: undefined } }
```

**Comment by AJamesPhillips** [comment]
@dboune what's your summary for this?

**Comment by jbarros35** [comment]
I'm still on the same page here.. frustrating.

**Comment by dboune** [comment]
Sadly I missed that last request way back in 2017, and as happens I've long not been working on the project that used Hapi. I believe my solution at the time was to use my own fork of the type definitions.

The summary is that at least at the time of the original writing the definition used for `request.response` misses some important Boom properties, and the developer could be better served by using Boom's own type definition or replicating it as a separate type from `Response`. As well the definition included properties in `Response` that are not actually there when the result is *not* a BoomError, and should not be present when not, with the single exception of `isBoom`.

----

For detail I had previously chased down the code where in these things occur and documented them in the thread above, and provided an example of how I'd expect it to be able to be used along with a link to an example solution. Finally I provided a test showing an actual BoomError and the properties that were present, as well as showing how those properties are not actually present when the result is not a BoomError.

The link below was previously given as an example of how to provide a type definition that would have resolved the stated issue which it seems I had intended to submit as part of a PR if consensus could be created.

https://github.com/dboune/DefinitelyTyped/commit/f4c67c1122e3f10a26469f0ce06dd1924300580d#diff-074ce399e85a82d31a5349f977d389be

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
