### ISSUE TITLE
@typings/jasmine-matchers is missing more than 50 methods

### ISSUE THREAD

**Issue by rmorrise** [DefinitelyTyped/DefinitelyTyped#19482]
- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Bartvds, @JamieMason

I have installed `@types/jasmine-matchers@0.2.30` via NPM. Looking at the _index.d.ts_ file, I see a whole bunch of matchers specified in the library docs that are missing. Some examples from the library doc:

```
 expect(array).toBeArrayOfBooleans();
 expect(array).toBeArrayOfNumbers();
 expect(array).toBeArrayOfObjects();
 expect(array).toBeArrayOfSize(number);
 expect(array).toBeArrayOfStrings();
 expect(array).toBeEmptyArray();
 expect(array).toBeNonEmptyArray();
```

https://github.com/JamieMason/Jasmine-Matchers#matchers

**Comment by JamieMason** [comment]
I don't use TypeScript myself @rmorrise but I think you will need `@types/jasmine-expect`. `jasmine-matchers` is a different package and, although it was created after [Jasmine-Matchers](https://github.com/JamieMason/Jasmine-Matchers), it has the name `jasmine-matchers` on npm.

For better support for TypeScript in Jasmine-Matchers there is this open issue: https://github.com/JamieMason/Jasmine-Matchers/pull/62

Hope this helps, thanks!

**Comment by rmorrise** [comment]
Thanks! I switched to `@types/jasmine-expect` and now I see the typigns. I guess this was a mistake on my part - sorry!
