### ISSUE TITLE
Definition filename collission

### ISSUE THREAD

**Issue by Bartvds** [DefinitelyTyped/DefinitelyTyped#1951]
I think we got a new fun problem category: a definition filename collision:

I've used https://www.npmjs.org/package/uuid and made a simple definition, put it in a `uuid.d.ts` in my project. Now I thought to to add it here but there is already a `uuid` directory with another file with the same name, uppercased: `UUID.d.ts`.

It is a module that is not on any package manager: https://github.com/LiosK/UUID.js

This is of course something that was bound to happen as we mix many sources...  but how are we going to deal with this kind of thing?

Does anybody know if we got many non-npm/bower modules at all?

@staxmanade

**Comment by userpixel** [comment]
I spent the last two hours creating the types for 
https://github.com/JamieMason/Jasmine-Matchers
only to find out that name is taken by
https://github.com/uxebu/jasmine-matchers

___

I suggest creating a system that allows sharing the same top level directory name like this:

```
DefinitelyTyped/jasmine-matchers/jamiemason-jasmine-matchers.d.ts // the new one
DefinitelyTyped/jasmine-matchers/jasmine-matchers.d.ts // the original one
```
