### ISSUE TITLE
Latest CucumberJS Typings version 2.0.3 missing BeforeAll and AfterAll hooks

### ISSUE THREAD

**Issue by arjunjh10** [DefinitelyTyped/DefinitelyTyped#19548]
Hello,
I am upgrading cucumber to version 3.0.1 from v2.3.0 and in the process I was upgrading its type definitions too. But seems like the latest version of types/cucumber which is 2.0.3, does not have `beforeAll` and `afterAll`hooks. The types need to be upgraded to match Cucumber's latest version. 
Thanks

**Comment by RomkeVdMeulen** [comment]
Also, parameter `typeName` in `Transform` has been renamed to `name`: see https://github.com/cucumber/cucumber-js/pull/904

**Comment by Plondrein** [comment]
[PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21648) is waiting...

**Comment by aseeeem** [comment]
The PR has been merged in!
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21648

**Comment by arjunjh10** [comment]
Awesome. Then we can close the issue off. Cheers.
