### ISSUE TITLE
$ npm install @types/jquery.timer --save-dev-->>Cannot find name 'JQueryTimer'

### ISSUE THREAD

**Issue by zhangyu528** [DefinitelyTyped/DefinitelyTyped#19557]
- [ ] I tried using the `@types/xxxx` package and had problems.
$ npm install @types/jquery.timer --save-dev

But, when compiling, output is that

ERROR in /Users/zhangyu27/Documents/git.oschina.net/DuoBaoWeb/src/app/app.component.ts (19,24): Property 'timer' does not exist on type 'JQueryStatic'.

ERROR in /Users/zhangyu27/Documents/git.oschina.net/DuoBaoWeb/src/app/app.component.ts (21,11): Cannot find name 'JQueryTimer'.

Anyone konws the reason? Thx.

**Comment by zhangyu528** [comment]
Any body?

**Comment by andy-ms** [comment]
You probably forgot to reference the types? Try `/// <reference types="jquery.timer" />`.

**Comment by zhangyu528** [comment]
Hello,
Add /// <reference types="jquery.timer" /> in app.componet.ts

ngOnInit(): void {
    this.getCurrentBattle();
    var timer = $.timer(function() {
      alert('This message was sent by a timer.');
    }) as JQueryTimer;
    timer.set({ time : 5000, autostart : true });
  }

But,
ERROR in /Users/zhangyu27/Documents/git.oschina.net/DuoBaoWeb/src/app/app.component.ts (21,19): Property 'timer' does not exist on type 'JQueryStatic<HTMLElement>'.

ERROR in /Users/zhangyu27/Documents/git.oschina.net/DuoBaoWeb/src/app/app.component.ts (23,11): Cannot find name 'JQueryTimer'.
webpack: Failed to compile.

**Comment by zhangyu528** [comment]
I want to give up the typescript back to javascript for the third Libs. @andy-ms

**Comment by andy-ms** [comment]
You are probably not including the types for `jquery.timer` in your project. See the [handbook](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) for more about setting up a TypeScript project.

**Comment by zhangyu528** [comment]
1.This is path of jQuery.timer in node_modules/@types.

![snip20170929_3](https://user-images.githubusercontent.com/2985279/30999878-60f77134-a50a-11e7-8fdb-d26a2e9903dc.png)

2.This is tsconfig file. TypeRoots is node_modules/@types. Is that right?

![snip20170929_8](https://user-images.githubusercontent.com/2985279/31002722-dc72af68-a51e-11e7-8707-6a99569fff31.png)

**Comment by andy-ms** [comment]
You shouldn't need to set `--typeRoots` at all, because we should look in `node_modules/@types` by default anyway. Check the output with `--listFiles --traceResolution` to get a better idea what's going on.

**Comment by zhangyu528** [comment]
I tried to check the output with --listFiles --traceResolution.get not any idea. I am sorry.
![snip20171003_9](https://user-images.githubusercontent.com/2985279/31130276-873fcfc6-a889-11e7-99a7-f72f296d4f70.png)

**Comment by andy-ms** [comment]
That screenshot doesn't show the output of `--listFiles` or `--traceResolution`. Try using the command-line `tsc` compiler and posting the output as plaintext.

**Comment by zhangyu528** [comment]
I has tried using tsc.
![snip20171003_14](https://user-images.githubusercontent.com/2985279/31132426-5a082296-a88f-11e7-8ed8-b6f7c0e2ec74.png)
![snip20171003_13](https://user-images.githubusercontent.com/2985279/31132477-7f1e6c8e-a88f-11e7-9093-9acaabd5e3c2.png)

**Comment by andy-ms** [comment]
In those screenshots you are not using the `--listFiles` or `--traceResolution` command line options. Try running `tsc --listFiles --traceResolution` in the same directory as your `tsconfig.json`, and post the results as plain text.

**Comment by zhangyu528** [comment]
[$ .:node_modules:typescript:bin:tsc --listFiles --.txt](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1352786/node_modules.typescript.bin.tsc.--listFiles.--.txt)

**Comment by andy-ms** [comment]
OK, that contains:
```
======== Type reference directive 'jquery.timer' was successfully resolved to '/Users/zhangyu27/Documents/git.oschina.net/DuoBaoWeb/node_modules/@types/jquery.timer/index.d.ts', primary: true. ========
```

So you're successfully finding `jquery.timer`.
That output also does not seem to contain any compiler errors -- are you sure you're still having this problem?

**Comment by zhangyu528** [comment]
![snip20171003_16](https://user-images.githubusercontent.com/2985279/31133764-fbeb2682-a892-11e7-8498-3afd6b5c3fa8.png)
Yes ,still having the original problem.
This is tsconfig.json. 
Besides I want to know why not to need jquery.timer.js? only to need @type/jquery.timer file.

**Comment by andy-ms** [comment]
That screenshot doesn't show you getting a compile error -- that looks like a runtime error.

**Comment by zhangyu528** [comment]
Yes , ng server output the runtime error.

**Comment by zhangyu528** [comment]
web pack: Failed to comple.

**Comment by andy-ms** [comment]
That probably means that webpack isn't configured to use the `tsconfig` correctly and isn't picking up your installed `node_modules/@types/jquery.timer` like` tsc` is.

**Comment by zhangyu528** [comment]
I want to konw why do not need the jquery.timer.js? Jquery include the timer?

**Comment by andy-ms** [comment]
🤷‍♂️ I don't know how the plugin works, I just know how to get it to typecheck.

**Comment by zhangyu528** [comment]
Thank you. I will try again.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
