### ISSUE TITLE
@types/hls.js - "details" under interface "Data" has wrong type

### ISSUE THREAD

**Issue by sara3988** [DefinitelyTyped/DefinitelyTyped#19563]
- [x] I tried using the `@types/hls.js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jgainfort 

interface Data {} has been changed under  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18552
'details' under this interface Data has been typed "string" which may hold true in some case, but for event like LEVEL_LOADED, this should be of type "LevelDetails".

**Comment by jgainfort** [comment]
@sara3988 Created PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19614

Thank you for finding this.

**Comment by jgainfort** [comment]
@sara3988 PR was merged. usually takes a day or so before its reflected on npm.

**Comment by sara3988** [comment]
@jgainfort Thank you for letting me know! I will check out.

**Comment by sara3988** [comment]
This seems to be in place. Closing the issue.
