### ISSUE TITLE
react-dom does not work with modules=es6 (which is set implicitly by target=es6)

### ISSUE THREAD

**Issue by wereHamster** [DefinitelyTyped/DefinitelyTyped#19584]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @MartynasZilinskas

Importing `react-dom/test-utils` requires `"module": "commonjs"` when `"target": "es2016"`. Otherwise you get the error `test-utils/index.d.ts(8,33): error TS2307: Cannot find module '.'`. You can test this by adding `"target": "es2016"` to the react-dom tsconfig.json file here in this repo and then try to build it.

```sh
$ git diff
diff --git a/types/react-dom/tsconfig.json b/types/react-dom/tsconfig.json
index 8c270fabe..7374d194d 100644
--- a/types/react-dom/tsconfig.json
+++ b/types/react-dom/tsconfig.json
@@ -7,7 +7,7 @@
         "test-utils/index.d.ts"
     ],
     "compilerOptions": {
-        "module": "commonjs",
+        "target": "es2016",
         "lib": [
             "es6",
             "dom"

$ ./node_modules/.bin/tsc --noEmit
index.d.ts(16,8): error TS2307: Cannot find module 'react'.
node-stream/index.d.ts(1,30): error TS2307: Cannot find module 'react'.
react-dom-tests.ts(1,24): error TS2307: Cannot find module 'react'.
react-dom-tests.ts(2,27): error TS2307: Cannot find module 'react-dom'.
react-dom-tests.ts(3,33): error TS2307: Cannot find module 'react-dom/server'.
react-dom-tests.ts(4,37): error TS2307: Cannot find module 'react-dom/node-stream'.
react-dom-tests.ts(5,33): error TS2307: Cannot find module 'react-dom/test-utils'.
server/index.d.ts(1,30): error TS2307: Cannot find module 'react'.
test-utils/index.d.ts(6,8): error TS2307: Cannot find module 'react'.
test-utils/index.d.ts(8,33): error TS2307: Cannot find module '.'.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
