### ISSUE TITLE
@types/jquery - Version 3 definition selector is missing or not recognizing some of the types

### ISSUE THREAD

**Issue by nguyenhthai** [DefinitelyTyped/DefinitelyTyped#19597]
- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu 

Previously, I was using the v2. After updated my jQuery to latest version, I also updated 
the type definition to version 3. However, after the upgrade, Visual Studio is now complaining when using the jquery $ selector with some types. Most notable complaints are:

`$(document) - document is type of Document`

`$(window) - window is type of Window`

```
$("#id").on("click", (e) => {
   var test = $(e.target); - e.target has type of TTarget, which is set to interface EventTarget
});
```
There might be more but those are the general types and should be cover by the selector. Looking over the definition file, I found those lines:
```
/**
  * Creates DOM elements on the fly from the provided string of raw HTML.
  *
  * Binds a function to be executed when the DOM has finished loading.
  *
  * @param selector_object_callback A string containing a selector expression
  *                                 A DOM element to wrap in a jQuery object.
  *                                 An array containing a set of DOM elements to wrap in a jQuery object.
  *                                 A plain object to wrap in a jQuery object.
  *                                 An existing jQuery object to clone.
  *                                 The function to execute when the DOM is ready.
  * @see {@link https://api.jquery.com/jQuery/}
  * @since 1.0
  * @since 1.4
  */
(selector_object_callback?: JQuery.Selector | JQuery.htmlString | JQuery.TypeOrArray<Element> | JQuery |
        JQuery.PlainObject |
        ((this: Document, $: JQueryStatic<TElement>) => void)): JQuery<TElement>;
```
So based on the description, correct me if I am wrong but I interpreted that **JQuery.Selector** is "**A DOM element to wrap in a jQuery object**" and that has a type of string. 
```
 /**
   * A selector is used in jQuery to select DOM elements from a DOM document. That document is, in most
   * cases, the DOM document present in all browsers, but can also be an XML document received via Ajax.
   */
type Selector = string;
```
Would that be an DOM element object itself and not a string? Go back to v2 and this is the definition for DOM element selector: `(element: Element): JQuery;`

In addition, this is currently running on Typescript 2.5 and recently updated from 2.4.

**Comment by leonard-thieu** [comment]
`window` and `document` will match to `JQuery.PlainObject`. `Element` will match to `JQuery.TypeOrArray<Element>`. What errors are you getting exactly?

**Comment by nguyenhthai** [comment]
The general error is `Supplied paramaters do not matched any signature of call target: parameter type mismatch. Parameter "selector_object_callback" should have type assignable to  '(string | Element | Element[] | JQuery<Node> | JQuery.PlainObject<Object> | (($: JQueryStatic<Node>) => void))', but it has type...`

In this case, `window` and `document` will generate the error with type `Window` and type `Document` respectively. Any element or event like above will generate type `Node` instead.

Although the compiler is giving the error, it successfully compiled the source code and I think it might related to the new change with Typescript 2.4 with the introduction of weak type.

**Comment by leonard-thieu** [comment]
ReSharper doesn't seem to be honoring default type parameters.

The error message is showing base types and not default types like you'd expect.

#### Actual
<code>JQuery<**Node**> | JQuery.PlainObject<**Object**> | (($: JQueryStatic<**Node**>) => void))</code>

#### Expected
<code>JQuery<**HTMLElement**> | JQuery.PlainObject<**any**> | (($: JQueryStatic<**HTMLElement**>) => void))</code>

I'd recommend reporting this as a bug to JetBrains.

**Comment by leonard-thieu** [comment]
There were more changes than updating the API going from v2 to v3. I aimed for higher fidelity when I wrote the v3 definitions. As a result, `@types/jquery` v3 requires TypeScript 2.3 while `@types/jquery` v2 only uses up to TypeScript 2.0 features.

**Comment by trickeyone** [comment]
I'm using `typescript@2.6.2` and `@types/jquery@3.2.16` and I'm getting this error. Reverting to `@types/jquery@2.0.46` removed the error.

**Comment by HolgerJeromin** [comment]
The main problem seems to be the handling of document and window inside jquery.d.ts (current master) and TS 2.8.1

```ts
let myDiv = $(document.createElement('div')); //gets default jQuery<HTMLElement> 8-/
myDiv.on('click', (evt) => {
    let target = evt.target; // HTMLElement
});
let myDiv1 = $<HTMLDivElement>(document.createElement('div')); // expected 0-2 Arguments but got 1. huh?
let myDiv2 = $<HTMLDivElement, null>(document.createElement('div')); // expected 0-1 Arguments but got 2. huh?
let myForcedDiv: JQuery<HTMLDivElement> = $(document.createElement('div')) as any;
myForcedDiv.on('click', (evt) => {
    let target = evt.target; // HTMLDivElement
});
let myDoc = $(document); //gets default jQuery<HTMLElement>
myDoc.on('click', (evt) => {
    let target = evt.target; // HTMLElement
});
let myDocForced: JQuery<Document> = $(document); // type HTMLElement is not assignable to Type Document
let myWindow = $(window); //gets default jQuery<HTMLElement>
let myWindowForced: JQuery<Window> = $(window); // type Window does not satisfy contraint Node

```

@leonard-thieu

**Comment by mpreyskurantov** [comment]
Which jQuery dts release version contained this fix first?
