### ISSUE TITLE
[react-bootstrap] prop types are inaccessible

### ISSUE THREAD

**Issue by arolson101** [DefinitelyTyped/DefinitelyTyped#19596]
- [X] I tried using the `@types/react-bootstrap` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @walkerburgin, @vsiao, @danilojrr, @Batbold-Gansukh, @octatone, @chengsieuly, @katbusch, @vitosamson

The latest typings for react-bootstrap follow a new convention for declaring components that leave their formtypes inaccessible.  I have wrapper components that pass their props to child components, and now I can no longer reference them.

e.g. the current Form.d.ts:
```ts
import * as React from 'react';

declare class Form extends React.Component<FormProps> { }
declare namespace Form { }
export = Form

interface FormProps extends React.HTMLProps<Form> {
  bsClass?: string;
  componentClass?: React.ReactType;
  horizontal?: boolean;
  inline?: boolean;
}
```

this can be solved by putting the FormProps into the Form namespace, like so:
```ts
import * as React from 'react';

declare class Form extends React.Component<Form.Props> { }
export = Form

declare namespace Form {
  export interface Props extends React.HTMLProps<Form> {
    bsClass?: string;
    componentClass?: React.ReactType;
    horizontal?: boolean;
    inline?: boolean;
  }
}
```

then consumers of this library can reference them via ```Form.Props```

**Comment by patsissons** [comment]
This needs to be fixed asap, these type definitions are significantly degraded without access to the props typings. Is anyone currently looking at this?

**Comment by vsiao** [comment]
see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19494

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
