### ISSUE TITLE
Custom validation rule property for DataSourceSchemaModelFieldValidation

### ISSUE THREAD

**Issue by corydeppen** [DefinitelyTyped/DefinitelyTyped#19593]
- [x] I tried using the `@types/kendo-ui` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Telerik @tsvetomir

I'm in the process of migrating a project to TS and have run into a situation where a custom validation rule was defined on a field of one of the models. Unfortunately, the `DataSourceSchemaModelFieldValidation` interface doesn't have a string index signature that would allow custom rules to be added to the `validation` object. Would it be reasonable to add a new property to this interface (e.g. `[rule: string]: any;`)?

**Comment by tsvetomir** [comment]
Thanks for reporting this issue. We'll push a fix with the next update.

**Comment by corydeppen** [comment]
@tsvetomir What are you referring to when you say "the next update"?

**Comment by corydeppen** [comment]
@tsvetomir Can you provide an update on when this will be added?

**Comment by tsvetomir** [comment]
The fix has been applied in our code base and will ship with service releases. I'll also submit a PR to DefinitelyTyped so you can get it right away.

Apologies for the caused inconvenience.

**Comment by corydeppen** [comment]
Resolved by #20070
