### ISSUE TITLE
Sinon.stub declares method name to be wrong type

### ISSUE THREAD

**Issue by heatherbooker** [DefinitelyTyped/DefinitelyTyped#19615]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @MrBigDog2U, @rationull, @lumaxis, @nicojs, @43081j 

I'm running into a weird error when I try to stub the global `confirm` method using sinon, chai, and karma w/ headless Chrome. While it does successfully stub the method, the linter complains that `'confirm'` is not the right type.

Here's how I stub it, in the `beforeEach`:
```
this.confirmStub = sinon.stub(global, 'confirm');
```
And the resulting error:
```
Error: Argument of type '"confirm"' is not assignable to parameter
  of type '"undefined" | "ArrayBuffer" | "Int8Array" | "Uint8ClampedArray" |
  "Int16Array" | "Uint16Array" | ...'.
```

It does not accept `'confirm'` or `'potato'`, but takes no offence to `'undefined'` as a string. However, `undefined` as a value also triggers the same error.

I can't find what in the sinon types would be causing this. Any suggestions or potential workarounds appreciated!

**Comment by heatherbooker** [comment]
Update: this can be circumvented by casting the method name, ie:
```
this.confirmStub = sinon.stub(global, 'confirm' as any);
```
Not ideal but useful in the meanwhile if anyone else comes across this!

**Comment by rationull** [comment]
In index.d.ts for the Sinon typings, the stub() function is declared like:

`<T>(obj: T, method: keyof T): SinonStub;`

So it seems like in your case the problem is that 'confirm' is not recognized as a property on `global`. I've never done any frontend Javascript so I'm not sure what the cause would be, but do you have an idea what the TS compiler thinks about the properties on `global` at this point in your code?

If the compiler doesn't know about its properties then you probably will have to resort to an `any` cast. I think you should be able to use `global as any` or `<any>global` instead of casting the 'confirm' string, if you like that better.

**Comment by heatherbooker** [comment]
@rationull Thanks for the response!

Hunh, interesting. I think the types it is using for the global are [these in NodeJS](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L604), because when I try to specify the type like this:

`stub<MyType>(global, 'alert')`

 I get an error:

`Argument of type 'NodeJS.Global' is not assignable to parameter of type 'MyType'.` 

Then the next question I guess is why it's using Node types instead of some sort of browser global definition. I can't find what in [karma types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/karma/index.d.ts) or [mocha types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mocha/index.d.ts) would be affecting it; perhaps I'm looking in the wrong area entirely.

**Comment by rationull** [comment]
OK, that makes sense. So this is a Typescript compiler settings thing rather than a sinon thing. How are you specifying Typescript compiler arguments? (via tsconfig.json or via command line arguments?) What are you specifying for "lib"?

**Comment by heatherbooker** [comment]
Most of the arguments are in a config file, except a few:

`"tslint --type-check -c config/typescript/lint-test.json -p config/typescript/compile.lint-test.json"`

where `compile.lint-test.json` extends a central tsconfig which has:

`"lib": ["dom", "es2017", "esnext.asynciterable"]`

and the `compile.lint-test.json` does have some `compilerOptions` set, namely `path` and `baseUrl`, if that is relevant.

I see in `lib.dom.d.ts` that `confirm` is declared [on `Window`]( https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L13134); and it does turn out that:

`this.confirmStub = sinon.stub(window, 'confirm');`

using `window` instead of `global` removes the error! I am happy with this solution - it also clarifies what exactly I intend to stub.

Thanks so much @rationull for your wisdom!
