### ISSUE TITLE
@types/node@8.0.27 breaks @types/uuid@3.4.2

### ISSUE THREAD

**Issue by LukasKraushofer** [DefinitelyTyped/DefinitelyTyped#19623]
- [/] I tried using the `@types/uuid` package and had problems.
- [-] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
 currently using typscript@2.3.4

our build fails since @types/uuid@3.4.2 loads the dependency @types/node@8.0.27, de build succeeded with @types/node@8.0.26 !

The Error we get is
`ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:5615:11 
    TS2420: Class 'Module' incorrectly implements interface 'NodeModule'.
    Property 'hot' is missing in type 'Module'.`

**Comment by tko** [comment]
Seeing the same issue with `@types/node@8.0.28` although getting the dependency via a private module.

**Comment by devoto13** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19612 should fix this issue.
