### ISSUE TITLE
[angularjs] $watch returns void in @types/angular, but officially returns an unbinding function

### ISSUE THREAD

**Issue by elliot-j** [DefinitelyTyped/DefinitelyTyped#19636]
The type definitions for `$scope.$watch()`, `$scope.$watchCollection()`, and `$scope.$watchGroup()` return void, but the official API docs for angular specify that they return an unbinding function to destroy the created watcher.

[REF]( https://docs.angularjs.org/api/ng/type/$rootScope.Scope )

**Comment by cyrilgandon** [comment]
The return type looks good:

    $watch(watchExpression: string, listener?: string, objectEquality?: boolean) : () => void;

Method name: `$watch`
Arguments: `(watchExpression: string, listener?: string, objectEquality?: boolean)`
Returns: `() => void`  this is a Function


https://github.com/DefinitelyTyped/DefinitelyTyped/blob/69acc07b23b9ef174732a352fc732c363149db15/types/angular/index.d.ts#L511

**Comment by elliot-j** [comment]
@cyrilgandon I was not aware that JS could interpret void in this manner. learn something new every day
