### ISSUE TITLE
[mixpanel] time_event and people.union methods are missing from types

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [DefinitelyTyped/DefinitelyTyped#19642]
- [x] I tried using the `@types/mixpanel` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @hjellek

It appears that the time_event and people.union events are missing from the type definitions for Mixpanel

**Comment by weswigham** [comment]
Closed by #20342
