### ISSUE TITLE
@types/superagent requires @types/node which defines Node environment where browser environment is expected

### ISSUE THREAD

**Issue by sompylasar** [DefinitelyTyped/DefinitelyTyped#19646]
- [x] I tried using the `@types/superagent@3.5.5` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @NicoZelaya @mxl @paplorinc

I'm using `superagent` in the browser environment (not Node). Importing `superagent` loads type definitions `@types/superagent` which unconditionally imports `@types/node` which injects global type definitions for Node environment. After that, the TypeScript compiler tells me that `setTimeout` returns `NodeJS.Timer` while I expect it to return `number` because there should be no `NodeJS` in the browser.

I'm not using the latest `tsc` because I'm building a React+TypeScript app via https://github.com/zhenwenc/create-react-app https://www.npmjs.com/package/zc-react-scripts –
 `typescript@2.4.2` [is bundled](https://github.com/zhenwenc/create-react-app/blob/ad3d5ee66a9e7e7b0326ff4e79cc9ce08d76423f/packages/react-scripts/package.json#L65) with the latest version `zc-react-scripts@1.1.1` at the time of writing.

**Comment by labkey-joshd** [comment]
@sompylasar in case you were still seeing this issue: you can use `window.setTimeout` instead, which should solve the typing issue. See [here](https://github.com/Microsoft/TypeScript/issues/842#issuecomment-297786346) for more info

**Comment by sompylasar** [comment]
@labkey-joshd That helps, thank you.

**Comment by ab-pm** [comment]
Duplicated by https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41425

**Comment by orta** [comment]
This is covered in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55382
