### ISSUE TITLE
Jest has dependency on "Set" type, doesn't have that definition in basic build

### ISSUE THREAD

**Issue by technion** [DefinitelyTyped/DefinitelyTyped#19662]
- [ x] I tried using the `@types/jes` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @NoHomey , @jwbay 

I'm getting the following error when trying to build a simple test case using Jest.

/frontend/node_modules/@types/jest/index.d.ts
(1026,34): error TS2304: Cannot find name 'Set'.

I'm running @types/jest@20.0.8 on typescript@2.5.2. Various research suggests there similar problems are resolved by installing a series of shim modules and their types, but given we're talking about a single line in a large definitions file, it would be great if a simpler/more portable solution could deal with this.

**Comment by kuakman** [comment]
Any workaround besides installing shim modules and their types? Seems like adding lib -> "es6" or skipLibCheck -> true to the tsconfig.json is not helping. The error is still there.

**Comment by technion** [comment]
I've had no luck trying similar workarounds unfortunately. At present I found installing shims introduced more errors than they fixed.

**Comment by cayuu** [comment]
Depending on your TS compile target, you have to include `"lib": ["es6", ...etc ]` in your [tsconfig](http://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by yamafaktory** [comment]
Hi, any new valid workaround? None of the above solutions is fixing the issue.

**Comment by wingtonbrito** [comment]
Any update on this ?

**Comment by technion** [comment]
@wingtonbrito I've sent PR #22025 which has been the fix I've been running.

**Comment by cm42** [comment]
In my case, the jest types were automatically included and caused errors although they were not required in the particular compilation step. So a workaround is the restriction of `@types` considered by the TypeScript compiler:
```javascript
{
  "compilerOptions": {
    // Becomes obsolete when @types/jest is removed or
    // [a distinct pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22025)
    // is installed
    "types": [
      "@types/webpack",
      "@types/node",
      // ...
    ]
  }
}
```
See [documentation](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types).

**Comment by unional** [comment]
Can close?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
