### ISSUE TITLE
Export react-bootstrap element interfaces

### ISSUE THREAD

**Issue by mayerwin** [DefinitelyTyped/DefinitelyTyped#19664]
- [X] I tried using the `@types/react-bootstrap` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
- Authors: @walkerburgin, @vsiao, @danilojrr, @octatone, @chengsieuly, @katbusch, @vitosamson 

I need to extend a `react-bootstrap` element, but am unable to extend its props interface as it is not exported. Can you look at exporting all these interfaces (e.g. `ButtonProps` below) so they are available for extension purposes?

```
declare class Button extends React.Component<ButtonProps> { }
declare namespace Button { }
export = Button

interface ButtonProps extends React.HTMLProps<Button> {
  bsClass?: string;
  active?: boolean;
  block?: boolean;
  bsStyle?: string;
  bsSize?: Sizes;
  componentClass?: React.ReactType;
  disabled?: boolean;
}
```

**Comment by vsiao** [comment]
see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19494
