### ISSUE TITLE
@types/commander: typings are for commander 2.9, now 2.11 exists where `.name()` can be a setter

### ISSUE THREAD

**Issue by sompylasar** [DefinitelyTyped/DefinitelyTyped#19710]
- [x] I tried using the `@types/commander` `2.9.2` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alan-agius4 @mdezem @vvakame

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/046478a6dddca229cd6ba0b9328f5e86b046aece/types/commander/index.d.ts#L251-L256

https://github.com/tj/commander.js/blob/v2.9.0/index.js#L881-L891
```js
/**
 * Get the name of the command
 *
 * @param {String} name
 * @return {String|Command}
 * @api public
 */

Command.prototype.name = function() {
  return this._name;
};
```

https://github.com/tj/commander.js/blob/v2.11.0/index.js#L907-L919
```js
/**
 * Get or set the name of the command
 *
 * @param {String} str
 * @return {String|Command}
 * @api public
 */

Command.prototype.name = function(str) {
  if (0 === arguments.length) return this._name;
  this._name = str;
  return this;
};
```

https://github.com/tj/commander.js/compare/v2.9.0...v2.11.0

There's one more public API change, making `.version()` `flags` optional, but it seems this has been already incorporated:
- https://github.com/tj/commander.js/compare/v2.9.0...v2.11.0#diff-168726dbe96b3ce427e7fedce31bb0bcR833
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/046478a6dddca229cd6ba0b9328f5e86b046aece/types/commander/index.d.ts#L45-L48

**Comment by alan-agius4** [comment]
PRs are welcome to fix the issue.

**Comment by alan-agius4** [comment]
That said, note that commander.js have typings which have not yet been
published.

https://github.com/tj/commander.js/blob/master/typings/index.d.ts
