### ISSUE TITLE
@types/webdriverio - Property 'then' does not exist on type 'never'

### ISSUE THREAD

**Issue by jesusiglesias** [DefinitelyTyped/DefinitelyTyped#19714]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nmalaguti @timbru31 @fsmedberg-tc

Hi,

I have an issue in the type definition when I use the 'keys' command of webdriverio. My code runs properluy but it appears this warning/error. Version: @types/webdriverio": "^4.8.4".

    it('should remove all pages at once', () => {
        return client
            .keys(['Control', 'a'])
            .then( () => class.confirmDeletion())
            .pause(2000)
            .then((elements) => {
                expect(elements.value.length).to.be.equal(0);
            })
    });

Thanks.

**Comment by timbru31** [comment]
@jesusiglesias - would you like to create a PR? ;)

**Comment by jesusiglesias** [comment]
@timbru31 - Yes, I will.
