### ISSUE TITLE
Test failure for whatwg-streams on master

### ISSUE THREAD

**Issue by Oblosys** [DefinitelyTyped/DefinitelyTyped#19740]
The current version of `whatwg-streams` on master does not pass `npm test`, which causes test failures on changes to package `node` (see #19733,#19656,#19612, #19488), and perhaps also other dependencies.

To expose the error, commit a dummy change to a comment in `types/whatwg-streams/index.d.ts` on a separate branch, and run `npm test`, which fails with

    index.d.ts(32,15): error TS2300: Duplicate identifier 'ReadableStream'.

I don't know if the problem is in `whatwg-streams` itself or if a breaking change in one of its dependencies somehow got merged.

- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @saschanaz

**Comment by SaschaNaz** [comment]
ReadableStream is later (partially) adopted in lib.d.ts and that causes this issue. We can remove the duplicated part away.

**Comment by SaschaNaz** [comment]
(I think that won't be very easy because of the limitation to extend lib.d.ts. Adding whole types on TSJS-lib-generator may be easier.)

**Comment by Oblosys** [comment]
This got fixed somewhere along the way.
