### ISSUE TITLE
react redux fetch error

### ISSUE THREAD

**Issue by meninjanho4788** [DefinitelyTyped/DefinitelyTyped#19741]
- [x] I tried using the `@types/react-redux` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

I have a big problem with typescript, My code : 
File ProfileMore.tsx
import { Action, Reducer, ActionCreator } from 'redux';
import { AppThunkAction } from "ClientApp/store";
export interface AuthenProfileMoreState {
  AuthenProfileMore_Object: ObjAuthenProfileMore;
}

export interface ObjAuthenProfileMore {
  user_id: number,
  user_gender: string,
  user_birthday: string
}

export interface LoadAuthenProfileMore {
  type: 'LOAD_AUTHEN_PROFILEMORE',
  AuthenProfileMore_Object: ObjAuthenProfileMore
}

export interface DeleteAuthenProfileMore {
  type: 'DELETE_AUTHEN_PROFILEMORE'
}

type KnownAction = LoadAuthenProfileMore | DeleteAuthenProfileMore;

export const actionCreators = {
  loadAuthenProfileMore: (data: string): AppThunkAction<KnownAction> => (dispatch, getState) => {
    fetch(`/api/account/GetMoreProfile`,
      {
        method: 'GET'
      }).then(
      response => response.json() as Promise<ObjAuthenProfileMore[]>)
      .then((data) => {
        dispatch({ type: 'LOAD_AUTHEN_PROFILEMORE', AuthenProfileMore_Object: data[0] as ObjAuthenProfileMore });
      })
  },
  deleteAuthenProfileMore: (): AppThunkAction<KnownAction> => (dispatch, getState) => {
    dispatch({ type: 'DELETE_AUTHEN_PROFILEMORE' });
  }
};

const unloadedState: AuthenProfileMoreState = { AuthenProfileMore_Object: null };

export const reducer: Reducer AuthenProfileMoreState = (state: AuthenProfileMoreState, action: KnownAction) => {
  switch (action.type) {
    case 'LOAD_AUTHEN_PROFILEMORE':
      return { AuthenProfileMore_Object: action.AuthenProfileMore_Object };
    case 'DELETE_AUTHEN_PROFILEMORE':
      return { AuthenProfileMore_Object: null };
    default:
      const exhaustiveCheck: never = action;
  }
  return state || unloadedState;
};
----------------------------------
File ClientApp/Store/index.tsx
import * as AuthenProfileMore from './Authen/ProfileMore';

export interface ApplicationState {
  authenProfileMore: AuthenProfileMore.AuthenProfileMoreState
}

export const reducers = {
  authenProfileMore: AuthenProfileMore.reducer
};

export interface AppThunkAction<TAction> {
  (dispatch: (action: TAction) => void, getState: () => ApplicationState): void;
}

File Call Action : LoginForm.tsx
import * as React from 'react';
import { connect } from 'react-redux';
import { ApplicationState } from '../../../../store';
import * as AuthenProfileMore from '../../../../store/Authen/ProfileMore';

type LoginFormProps =
  AuthenProfileMore.AuthenProfileMoreState
  & typeof AuthenProfileMore.actionCreators

class LoginForm extends React.Component<LoginFormProps, {}> {
    constructor() {
      super();
      this.btnLogin = this.btnLogin.bind(this);
    }
    btnLogin(values) {
      const endstr = Object.keys(values)
        .map(key => encodeURIComponent(key) + '=' + encodeURIComponent(values[key]))
        .join('&');
      fetch('/connect/token',
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
          },
          body: endstr
        }).then(
        response => response.json())
        .then((responseData) => {
            this.props.loadAuthenProfileMore(responseData.sub);
        })
    }
    btnSignOut() {
      this.props.deleteAuthenProfileMore();
    }
    public render() {
      return 
		button LogIn call this.btnLogin
		button LogOut call this.btnSignOut
      ;
    }
}

export default connect(
  (state: ApplicationState) => Object.assign(state.authenProfile, state.authenAuth, state.authenProfileMore),
  Object.assign(AuthenAuth.actionCreators, AuthenProfile.actionCreators, AuthenProfileMore.actionCreators)
)(LoginForm) as any;

===> When i call action by click button  LogIn : this.props.loadAuthenProfileMore(responseData.sub); it cant get data from API to Store. But when i click button Logout i receive old data of Login Click.

===> When i chage action deleteAuthenProfileMore in actionCreators : (change same loadAuthenProfileMore )

export const actionCreators = {
  loadAuthenProfileMore: (data: string): AppThunkAction<KnownAction> => (dispatch, getState) => {
    fetch(`/api/account/GetMoreProfile`,
      {
        method: 'GET'
      }).then(
      response => response.json() as Promise<ObjAuthenProfileMore[]>)
      .then((data) => {
        dispatch({ type: 'LOAD_AUTHEN_PROFILEMORE', AuthenProfileMore_Object: data[0] as ObjAuthenProfileMore });
      })
  },
  deleteAuthenProfileMore: (data: string): AppThunkAction<KnownAction> => (dispatch, getState) => {
    fetch(`/api/account/GetMoreProfile`,
      {
        method: 'GET'
      }).then(
      response => response.json() as Promise<ObjAuthenProfileMore[]>)
      .then((data) => {
        dispatch({ type: 'DELETE_AUTHEN_PROFILEMORE', AuthenProfileMore_Object: data[0] as ObjAuthenProfileMore });
      })
  }
};
==> It can load data when i click LogIn click.

I have a same store AuthenProfileMore it is AuthenProfile. I think, is it have problem with name ?

**Comment by meninjanho4788** [comment]
Sorry i found my error, because i call many reducer in one component : 
Only change 
Object.assign(AuthenAuth.actionCreators, AuthenProfile.actionCreators, AuthenProfileMore.actionCreators) to ==>
Object.assign({}, AuthenAuth.actionCreators, AuthenProfile.actionCreators, AuthenProfileMore.actionCreators)
i miss {} in Object.assign, it not same actionCreators

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
