### ISSUE TITLE
[d3-geo] Update Definitions to Version 1.7.1

### ISSUE THREAD

**Issue by tomwanzek** [DefinitelyTyped/DefinitelyTyped#19748]
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Ledragon @tomwanzek

Lastest minor version includes new projections:
* `geoNaturalEarth1`
* `geoNaturalEarth1Raw`

**Comment by Ledragon** [comment]
Will try to do that by this week-end, unless you beat me to it

**Comment by tomwanzek** [comment]
Probably not, this time around 😄 Thanks in advance, I will do the approval review this time. Cheers.

**Comment by tomwanzek** [comment]
Closed with #19794.
