### ISSUE TITLE
Node: missing lookup field in tls.ConnectionOptions

### ISSUE THREAD

**Issue by jpap** [DefinitelyTyped/DefinitelyTyped#19776]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @parambirs, @RobDesideri, @tellnes, @WilcoBakker, @octo-sniffle, @smac89, @Flarna, @mwiktorczyk, @wwwy3y3, @Tyriar, @DeividasBakanas, @kjin

The `options` argument to [`tls.connect(options[, callback])`](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback) accepts a `lookup` function that is missing in the types definition:
```
   lookup: <Function> Custom lookup function. Defaults to dns.lookup().
```
which should have the shape described in [`dns.lookup()`](https://nodejs.org/api/dns.html#dns_dns_lookup_hostname_options_callback).

**Comment by jpap** [comment]
The following addition to `tls.ConnectionOptions` appears to fix this:
```
        lookup?: (hostname: string, options: dns.LookupOneOptions | dns.LookupAllOptions | dns.LookupOptions, callback: (err: NodeJS.ErrnoException, address: string | dns.LookupAddress[], family?: number) => void) => void;
```

I'm happy to create a PR on your blessing. :-)

**Comment by smac89** [comment]
According to the documentation: https://nodejs.org/api/dns.html#dns_dns_lookup_hostname_options_callback

Shouldn't the callback address be a string? Why do you have it as an array?

**Comment by Flarna** [comment]
I think @smac89 is correct. The lookup property here should have the same type as that one in `net.createConnection()` (see #19456) as only the "request one" variant of `dns.lookup` is used in this use case.
Actually tls is just passing the lookup option down to net as far as I understood the nodejs source code.

**Comment by jpap** [comment]
[@smac89]
> Shouldn't the callback address be just a string? Why the extra option of dns.LookupAddress[]?

I simply took the existing type definitions of `dns.lookup`.  Looking at the documentation for `dns.lookup(...)` more carefully, I see [there is a special case](https://nodejs.org/api/dns.html#dns_dns_lookup_hostname_options_callback) which covers the array of addresses:

> With the all option set to true, the arguments for callback change to (err, addresses), with addresses being an array of objects with the properties address and family.

[@Flarna]
> Actually tls is just passing the lookup option down to net as far as I understood the nodejs source code.

When the documentation is more general than the code, which path do you take on type definitions?  Do you type according to the API spec in case the code later fulfills the documented functionality, or do you track source?

Once the dust settles here, I'll prepare a PR.  Appreciate your time looking into this!

**Comment by Flarna** [comment]
I'm not sure if there is a guideline in this.
What I had in mind here is that if we use the more generic variant in the definition it requires the user to implement an unneeded complex function. On the other hand implementation may change.

Even it's not documented that `tls.connect()` passes the lookup options down to `net.connect()` I would recommend to sync the type definition in this to avoid confusion.

**Comment by jpap** [comment]
> Even it's not documented that tls.connect() passes the lookup options down to net.connect() I would recommend to sync the type definition in this to avoid confusion.

Just so I'm clear, you're proposing we match the type definition to the **source** not the **documentation**?  i.e. the less-general case?  I'm OK with either... LMK and I'll prepare the PR.  Thank you!

**Comment by jpap** [comment]
@Flarna bump. :-)

**Comment by Flarna** [comment]
Sorry for not responding... Yes, this is my preference here. Lets see if we get other opinions in the review phase of the PR.

**Comment by Flarna** [comment]
@jpap I think this issue can be closed as your PR has been merged.

**Comment by jpap** [comment]
Thanks guys!
