### ISSUE TITLE
react-icons

### ISSUE THREAD

**Issue by dkirchhof** [DefinitelyTyped/DefinitelyTyped#19857]
Hello @apare , 
i tried using the `@types/react-icons` package in combination with webpack.  
Either i can't bundle the package or i don't get any type checks / autocompletion / etc.

`import { MdHome } from "react-icons/lib/md";` will work in webpack but ignores typings.

`import { MdHome } from "react-icons/md";` will use typings but will fail with webpack, because it loads the unbundled icon files ("Unexpected token (1:7) You may need an appropriate loader to handle this file type"). 

I'm using `awesome-typescript-loader` as tsx loader and the typescript compiler excludes all `node_modules`.

**Comment by apare** [comment]
when using webpack, I had to add babel loader for react-icon
add this in your webpack rules
```
{
            test: /\.jsx?$/,
            include: /node_modules\/react-icons/,
            use: [
                {
                    loader: "babel-loader",
                    query: {
                        presets: ["es2015", "react"]
                    }
                }
            ]
        }
```

**Comment by apare** [comment]
I also recommend you use `import { MdHome } from "react-icons/md/home"` because it will only add the require icon in your bundle

**Comment by ideoma** [comment]
I ended up with

     {
        test: /(\.js|\.jsx)$/,
        loader: 'babel-loader',
        include: [path.resolve(__dirname, './node_modules/react-icons/fa'), path.resolve(__dirname, './node_modules/react-icons/go')],
        query: {
            presets: ['es2015', 'react']
        }
      }


and had to install

    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
to make it work

**Comment by dkirchhof** [comment]
Thanks to both of you.
As i don't need babel at all (until now), i will give it a try later on.
