### ISSUE TITLE
Flowtype’s Maybe types

### ISSUE THREAD

**Issue by alloy** [DefinitelyTyped/DefinitelyTyped#19868]
More than once I’ve spent a significant amount of time thinking about how to best port flowtype’s Maybe types when working on the DefinitelyTyped repo. Should we:

1. Just write out `null | undefined` everywhere? (Tedious imo)
2. Go through all the actual code-paths to figure out if the code at runtime actually returns `null` or `undefined` or both? (Very tedious and prone to break as the code could change without changing its typing)
3. Have helpers in the DT repo to ease porting flowtype’ed libs, which would e.g. define `type Maybe = null | undefined` or `type Maybe<T> = T | null | undefined`

cc @andy-ms @DanielRosenwasser

**Comment by andy-ms** [comment]
It's a style issue whether you want to go with 1 or 3. I can't really say which is better, although I would prefer `type Maybe<T> = T | null | undefined` over `type Maybe = null | undefined`. As you said 2 is likely to result in bugs, so it's safer to assume that something coming from a flow type could be either null or undefined.

**Comment by alloy** [comment]
Agreed and this is what I ended up doing 👍
