### ISSUE TITLE
Issue using @types/esri-leaflet with an Angular CLI application

### ISSUE THREAD

**Issue by wznuk** [DefinitelyTyped/DefinitelyTyped#19872]
# ERROR TypeError: Cannot read property 'basemapLayer' of undefined
I have built a very basic application using the Angular CLI. When I build and run the application using `ng serve -o` everything builds successfully. However, when I view the application in Chrome the map portion does not load. Further inspecting the page I see this error in the console.

`ERROR TypeError: Cannot read property 'basemapLayer' of undefined`

## Setup
* Angular 4
* Chrome 61
* leaflet 1.2.0
* esri-leaflet 2.1.1
* types/leaflet for 1.2
* types/esri-leaflet for 2.1.

## Steps to reproduce the error:

These steps assume that you already have [angular CLI](https://cli.angular.io/) installed.

#### Steps 1-6 & 10 are done in terminal/cmd prompt window
1. Create a new application `ng new esriLeafletApp`
2. Navigate to the new application `cd esriLeafletApp`
3. `npm install --save leaflet`
4. `npm install --save esri-leaflet`
5. `npm install --save @types/esri-leaflet`
6. `npm install --save @types/leaflet`
7. Update the contents of the *app.component.ts* file
```
import { Component, OnInit } from '@angular/core';

import * as L from 'leaflet';
import 'esri-leaflet';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent implements OnInit {
  title = 'app';

  constructor() { }

  ngOnInit () {
    const map = L.map('map').setView([51.505, -0.09], 13);
    L.esri.basemapLayer('Streets').addTo(map);
  }
}
```
8. Update the contents of the *app.component.html* file
```
<div style="text-align:center">
  <h1>
    Welcome to {{title}}!
  </h1>
</div>
<div id="map"></div>
```
9. Update the contents of the *app.component.css* file
```
#map {
    height: 500px;
    width: 100%;
}
```
10. Build and run the application `ng serve -o`
11. View the application in Chrome
12. Inspect the code and view the error in the inspector console

## Please Help
Does anyone know why `esri` is `undefined` in the code block ` L.esri.basemapLayer('Streets').addTo(map);` ?

**Comment by wznuk** [comment]
This issue seems to be with the typings file. Until it is fixed here is the workaround I went with.

## The workaround:

- Removed ESRI typings from package.json and node_modules
- Used the import you mentioned: `import * as esri from 'esri-leaflet';
- Used esri directly (i.e. not as an extension of Leaflet).
- Still could use leaflet typings without a problem.

```
import { Component, OnInit } from '@angular/core';

import * as L from 'leaflet';
import * as esri from 'esri-leaflet';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent implements OnInit {
  title = 'app';

  constructor() { }

  ngOnInit () {
    const map = L.map('map', {
      maxZoom: 18,
      minZoom: 0
    }).setView([51.505, -0.09], 15);

    const esriLayer = esri.basemapLayer('Imagery');
    map.addLayer(esriLayer);
  }
}
```

**Comment by strajuser** [comment]
I'm too late, but this it is actual.

Now the workaround is to use previous versions of @types/esri-leaflet, for example. v2.1.0:

1. npm install --save @types/esri-leaflet@2.1.0
2. npm install --save @types/leaflet@1.0.69 (I don't understand why, but without specific version by default npm installs typings for leaflet 0.7)

The problems appeared after this PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19329

By I still can't understand, why classic usage of leaflet-plugin (import 'esri-leaflet') is not working.

**Comment by kragoth** [comment]
I have found what I believe is the fix to this issue.

in the index.d.ts for the esri-leaflet typings add this line at the end.

`export = L.esri;`

After this is done, all my issues went away and I could use the types properly.

**Comment by jrood** [comment]
@kragoth did you already submit a pull request for the `export = L.esri;` fix?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
