### ISSUE TITLE
How to write unit tests in two different files?

### ISSUE THREAD

**Issue by screendriver** [DefinitelyTyped/DefinitelyTyped#19894]
This is not a bug. It's some kind of question or feature request.

I created the pull request #19742 and have **two** test files. One that tests the type definitions as global variables and one for testing that as imported module. I **can't** test both things in one file because tslint complains about that. But if I split that two tests in two different files Travis complains about that.

How can I solve that? Only test one of both? (that would not be the best solution)

**Comment by leonard-thieu** [comment]
Create a `test` directory and place additional test files in there. See https://github.com/DefinitelyTyped/DefinitelyTyped/tree/924fafffc09cfeb0267573af2c847cdbfcfa464d/types/jquery for an example.

**Comment by screendriver** [comment]
Cool thank you! 🎉
