### ISSUE TITLE
@types/hapi - server.decorate does not require a function as the method return type when options.apply is true

### ISSUE THREAD

**Issue by dboune** [DefinitelyTyped/DefinitelyTyped#19914]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jasonswearingen @AJamesPhillips

At present the definition for `server.decorate` includes an override as follows:
```ts
decorate(type: 'request', property: string, method: (request: Request) => Function, options: {apply: true}): void;
```

The return type of the function passed via the method argument is not required to be a function. It may also be any other type. The documentation only refers to it as a 'value'.

https://hapijs.com/api#serverdecoratetype-property-method-options

> options - if the type is 'request', supports the following optional settings:
    apply - if true, the method function is invoked using the signature function(request) where request is the current request object and **the returned value is assigned as the decoration**.

### Proposed Change

```ts
decorate(type: 'request', property: string, method: (request: Request) => any, options: {apply: true}): void;
```

### Example Use

Upon each request a new `MyObject` is created with the request as an argument to the constructor, and assigned to the `myDecoration` property of the Request object.

```ts
function myRequestDecoration(request: Request) {
    return new MyObject({ request })
}

decorate(type: 'request', property: 'myDecoration', method: myRequestDecoration, options: {apply: true})
```

**Comment by AJamesPhillips** [comment]
Hi @dboune I'm a bit out of touch with this.  If this works with your code then please submit a PR.

**Comment by dboune** [comment]
Sorry for the delay in my response. As soon as I have time I'll submit a PR unless someone else gets around to it before then.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
