### ISSUE TITLE
[Openlayers] Is there any reason for hiding olx?

### ISSUE THREAD

**Issue by Ailrun** [DefinitelyTyped/DefinitelyTyped#19956]
- [x] I tried using the `@types/openlayers` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @osechet @ganlhi @wb14123 

By hiding olx, it's hard to separate options as sole variables (when we try to force using `: type` as a coding style).
Olx have only types, so, at least I think, exporting it doesn't makes any problem with transpiling.
Is there any reason for hiding?

**Comment by osechet** [comment]
@Ailrun Because openlayers is a Javascript library and the types defined in olx are not real Javascript classes just documented types. If you look at the code of openlayers, the olx module is defined in [externs/olx.js](https://github.com/openlayers/openlayers/blob/master/externs/olx.js) and for example the olx.interaction.SelectOptions looks like:
```
/**
 * @typedef {{addCondition: (ol.EventsConditionType|undefined),
 *     condition: (ol.EventsConditionType|undefined),
 *     layers: (undefined|Array.<ol.layer.Layer>|function(ol.layer.Layer): boolean),
 *     style: (ol.style.Style|Array.<ol.style.Style>|ol.StyleFunction|undefined),
 *     removeCondition: (ol.EventsConditionType|undefined),
 *     toggleCondition: (ol.EventsConditionType|undefined),
 *     multi: (boolean|undefined),
 *     features: (ol.Collection.<ol.Feature>|undefined),
 *     filter: (ol.SelectFilterFunction|undefined),
 *     wrapX: (boolean|undefined),
 *     hitTolerance: (number|undefined)}}
 */
olx.interaction.SelectOptions;
```

**Comment by Ailrun** [comment]
@osechet
I mean, we can export it as `ol.olx` or something like that, as type, not a value, which is not the problem with JS library. Isn't it?

**Comment by Ailrun** [comment]
And furthermore, do TS typing should use separate namespace instead of `ol` itself? Of course ol code use olx for interface, but it's just for documenting, isn't it?

**Comment by Ailrun** [comment]
Or just exporting 'olx' itself, as the namespace of types (not values). It's not related with real JS file...

**Comment by Ailrun** [comment]
My comments seems chaotic...
For clear suggestion,
1. Exporting `olx` as namespace of types is not related with JS file, isn't they?
2. Why did they separated from the begining? Openlayers `olx` namespace is just for documenting, isn't it?

**Comment by ganlhi** [comment]
Sorry to interrupt but : is there a way to not be flagged as author anymore? I contributed a pull request once, and now I'm spammed with other pull requests every day!

**Comment by Ailrun** [comment]
@ganlhi maybe removing yourself from def file????

**Comment by Ailrun** [comment]
@osechet Is there a problem with my opinion? If it's not border you, could you answer to my question?

**Comment by osechet** [comment]
@Ailrun Sorry I'm sure busy these days and I don't the time to properly think about your suggestion and the consequences. You can maybe create a PR including unit tests to start.

**Comment by Ailrun** [comment]
Ok! Thank you for fast answer!
