### ISSUE TITLE
@types/whatwg-fetch: Cannot find name 'ReadableStream'

### ISSUE THREAD

**Issue by shrutic** [DefinitelyTyped/DefinitelyTyped#19968]
- [x] I tried using the `@types/xxxx` package and had problems.
@types/whatwg-fetch 0.0.33 version has failed with error " node_modules/@types/whatwg-fetch/index.d.ts(32,44): error TS2304: Cannot find name 'ReadableStream'."

I added @types/whatwg-streams to the package.json dev dependencies, but still the failure exists.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
I am on version 2.1.6. Trying now with 2.5.2 which is the latest stable version of tsc. Will update the issue once installation and verification is done.

Got new set of errors on tsc 2.5.2

node_modules/@types/react/index.d.ts(165,11): error TS2559: Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.
node_modules/@types/whatwg-fetch/index.d.ts(11,13): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
node_modules/@types/whatwg-fetch/index.d.ts(13,14): error TS2300: Duplicate identifier 'HeadersInit'.

FYI, a lot of my react-native project also errored out with tsc 2.5.2. It would be great if you could resolve the the issue for tsc 2.1.6
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
Yes 
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ryan-codingintrigue

**Comment by neilzimmerman** [comment]
@loghorn this started after 3cc32b8e73320a5e9e4a17744236180f52c753d9

**Comment by shrutic** [comment]
I solved it by upgrading typescript compiler  to 2.3.2 and removing @types/whatwg-fetch from package.json

Shruti

**Comment by pasho** [comment]
@shrutic what did you use instead of @types/whatwg-fetch?

**Comment by shrutic** [comment]
Whatwg-fetch is built into typescript now . So no changes to code

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
