### ISSUE TITLE
Missing options for `get-port`

### ISSUE THREAD

**Issue by loopmode** [DefinitelyTyped/DefinitelyTyped#19981]
- [x] I tried using the `@types/get-port` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @plantain-00

`get-port` allows specifying a preferred port via options object, e.g. `getPort({port: 8090})`.
However, the type definition does not allow any options, and we get a `Expected 0 arguments, but got 1.` error.

**Comment by plantain-00** [comment]
The referenced PR should fix this issue.

**Comment by loopmode** [comment]
Great, thanks

**Comment by plantain-00** [comment]
If that PR is merged, this issue will be closed automatically.
