### ISSUE TITLE
@types/nock points to wrong place, nothing gets installed

### ISSUE THREAD

**Issue by cvuorinen** [DefinitelyTyped/DefinitelyTyped#19997]
- [x] I tried using the `@types/nock` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bonnici, @horiuchi 

Npm package https://www.npmjs.com/package/@types/nock points to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/nock which gives 404, actual types are at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/nock.

**Comment by andy-ms** [comment]
It was published before the move. But `npm install @types/nock` should still be installing things into your `node_modules`.

**Comment by cvuorinen** [comment]
Ah, so it does. Somehow missed it earlier when having issues with converting some js code to TS and went looking for the types. Seems VS code didn't update the folders after npm install or something.
