### ISSUE TITLE
@types/express-serve-static-core: app.use with error callback not type inferred

### ISSUE THREAD

**Issue by valeriangalliat** [DefinitelyTyped/DefinitelyTyped#20003]
- [x] I tried using the `@types/express-serve-static-core` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:  @borisyankov, @19majkel94, @kacepe

## How to reproduce

```typescript
import express = require('express');

const app = express();

app.use((req, res, next) => {
  next();
});

app.use((err, req, res, next) => {
  next();
});
```

```sh
$ tsc --version
Version 2.5.2
$ tsc express.ts --noImplicitAny
express.ts(9,10): error TS7006: Parameter 'err' implicitly has an 'any' type.
express.ts(9,15): error TS7006: Parameter 'req' implicitly has an 'any' type.
express.ts(9,20): error TS7006: Parameter 'res' implicitly has an 'any' type.
express.ts(9,25): error TS7006: Parameter 'next' implicitly has an 'any' type.
```

## My attempt to debug this issue

In [express-serve-static-core definition of `IRouterMatcher` and `IRouterHandler`](https://github.com/valeriangalliat/DefinitelyTyped/blob/460cf6264603b16bfdcac16a20ec64b133bb04f3/types/express-serve-static-core/index.d.ts#L25-L45), both `RequestHandler` and `RequestHandlerParams` signature variants are provided. Since `RequestHandlerParams` is already an union of types including `RequestHandler`, as far as I understand, explicitly having a variant with `RequestHandler` is redundant with `RequestHandlerParams`.

For some reason, the fact that this declaration is redundant breaks the type inferring of `ErrorRequestHandler` on the `use` function. This bug is only noticeable when using `noImplicitAny` option, otherwise params are silently assumed to be `any` instead of using the types that the `ErrorRequestHandler` provides.

I tried to fix it with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19879, by removing the redundant definition, and it did fix the issue with `ErrorRequestHandler` type inferring, but it moves that issue to `RequestHandler` itself (which is not type inferred anymore). For example after #19879, the repro file above now fails to compile with:

```
express.ts(5,10): error TS7006: Parameter 'req' implicitly has an 'any' type.
express.ts(5,15): error TS7006: Parameter 'res' implicitly has an 'any' type.
express.ts(5,20): error TS7006: Parameter 'next' implicitly has an 'any' type.
```

At first sight the typing file looks like type inferring should work for both `RequestHandler` and `ErrorRequestHandler` in either way (redundant definition or not), so I'm thinking this could be an issue with the TypeScript compiler itself?

I also believe this bug was already known, since the [test file for Express](https://github.com/valeriangalliat/DefinitelyTyped/blob/460cf6264603b16bfdcac16a20ec64b133bb04f3/types/express/express-tests.ts#L21) have explicit types for `ErrorRequestHandler` to circumvent the fact that the compiler couldn't infer them.

**Comment by ikokostya** [comment]
Looks like need additional overload for error handler:

```diff
interface IRouterMatcher<T> {
    (path: PathParams, ...handlers: RequestHandler[]): T;
+   (path: PathParams, ...handlers: ErrorRequestHandler[]): T; 
    (path: PathParams, ...handlers: RequestHandlerParams[]): T;
}
```

Currently for error handler last (and common) signature 

```ts
(path: PathParams, ...handlers: RequestHandlerParams[]): T;
```
is selected. Thus, `TypeScript` cannot infer handler type and you need explicit type assertion:

```ts
app.use(<express.ErrorRequestHandler>((err, req, res, next) => {
  next();
}));
```

**Comment by valeriangalliat** [comment]
Thanks @ikokostya! I tried your patch to add an overload for `ErrorRequestHandler` but I still have the same issue with type inferring on the error request handler. I tried that on `IRouterHandler` too but no luck:

```diff
interface IRouterMatcher<T> {
    (path: PathParams, ...handlers: RequestHandler[]): T;
+   (path: PathParams, ...handlers: ErrorRequestHandler[]): T;
    (path: PathParams, ...handlers: RequestHandlerParams[]): T;
}

interface IRouterHandler<T> {
    (...handlers: RequestHandler[]): T;
+   (...handlers: ErrorRequestHandler[]): T;
    (...handlers: RequestHandlerParams[]): T;
}
```

If I switch the order of `RequestHandler` and `ErrorRequestHandler` then in the regular handler (not error handler) TypeScript assumes that it's an error handler call and assumes that `res` is the callback.

That would mean it's not possible with TypeScript to infer types for both the regular request handler and the error request handler?

**Comment by 19majkel94** [comment]
> That would mean it's not possible with TypeScript to infer types for both the regular request handler and the error request handler?

I think that it's not possible 😞 Try that code in VSCode:
```ts
type ErrorHandler = (err: Error, req: number, res: boolean, next: string) => void;
type RouteHandler = (req: number, res: boolean, next: string) => void;

function registerHandler(handler: ErrorHandler|RouteHandler) {}

registerHandler((err, req, res, next) => {
})
registerHandler((req, res, next) => {
})
```
Apparently TS can't infer the types of function that has different number of parameters.

**Comment by ikokostya** [comment]
> Apparently TS can't infer the types of function that has different number of parameters.

Handbook [says](http://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)

> Don’t write separate overloads that differ only on callback arity:

At this point of view the following example is correct in TypeScript:

```ts
type ErrorHandler = (err: Error, req: number, res: boolean, next: string) => void;

function registerHandler(handler: ErrorHandler) {}

registerHandler((err, req, res) => {})
```

**Comment by valeriangalliat** [comment]
Thanks for the explanations :+1:
