### ISSUE TITLE
@types/react-bootstrap cannot be used with es6 modules because .d.ts utilizes default 'index' import

### ISSUE THREAD

**Issue by breathe** [DefinitelyTyped/DefinitelyTyped#20021]
Compilation of project using `@types/react-bootstrap` package fails with this message when `{modules: "es2015"}` is set in tsconfig.json:

```
node_modules/@types/react-bootstrap/index.d.ts(41,15): error TS2307: Cannot find module './lib'.
workspace/components/Answer.tsx(3,10): error TS2305: Module '"./ai-help/node_modules/@types/react-bootstrap/index"' has no exported member 'Button'.
workspace/components/Answer.tsx(3,18): error TS2305: Module '"./ai-help/node_modules/@types/react-bootstrap/index"' has no exported member 'Modal'.
```

This occurs because index.d.ts tries to import ./lib (relying on commonjs import behavior) rather than ./lib/index

Fixing that yields another instance of same issue within ./lib/index.d.ts

```
node_modules/@types/react-bootstrap/lib/index.d.ts(178,24): error TS2307: Cannot find module './utils'.
```

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @vsiao @danilobjr @octatone @chengsieuly @katbusch @vitosamson @LKay

**Comment by vitosamson** [comment]
Can you check if this works properly before https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19494 was merged? That PR changed the way that components are re-exported from `lib`.

Question to maintainers: is there a way to automatically test definitions against the different `modules` configs?

**Comment by LKay** [comment]
@breathe Can you share the actual code and how you're trying to import components? 

`react-bootstrap` exports all components as commonjs modules with single `export = XXX` statement for each. What I can think of is that Typecript compiler is trying to resolve module incorrectly when forced to es2015 modules resolving mode.

**Comment by breathe** [comment]
@LKay 

I extracted a minimal example to demonstrate the compilation issue: 

https://github.com/breathe/simple-react-bootstrap-ts-compilation-error-example

In project dir:
```
npm install
npm run compile-ts
```

Here's a DefinitelyTyped commit that fixes the error

https://github.com/breathe/DefinitelyTyped/commit/e1370a94c63815453007d8de289c7d7c444f3b3e

My understanding is that this error is happening because es2015 module's don't automatically re-map directory import's to 'directory/index' -- eg:

suppose a file: foo/index.js

`import something from 'foo'` <-- not part of es2015 modules, mapping of foo -> foo/index is a commonjs thing
`import something from 'foo/index'`  <-- works

Note: if the actual react-bootstrap codebase contains the moral equivalent of `import something from 'foo'` -- then this change wouldn't affect that runtime behavior -- the module bundler (or loader) would still need to support the commonjs foo -> foo/index mapping behavior -- I don't think the type definitions need to be concerned with that though (?).  I believe the type declarations should be expressible in a way that is compatible with es2015 module's otherwise its not possible for client code to transpile to es2015 syntax with the current typescript behavior ... (?)

I'm not sure about how or whether the usage of `export =` in the type declarations affects things ...  I would've expected that allowSyntheticDefaults would be involved here somehow -- I would think that I should see a type error if allowSyntheticDefaults = false given that the type declaration for the module claims to be a commonjs style 'default' export ... However setting it to false doesn't produce a type error in my example project ...  In any case -- at module bundling/loading time (I think?) the presence of the `Object.defineProperty(__es6Module,...)` noise in the compiled react-bootstrap library should cause the bundler to 'do the right thing' regardless of how the @types/react-bootstrap exports are typed?

@vitosamson 

Hrm -- I can't figure out a quick way to find a version number for the @types package from your link ... Can you offer an npm compatible link for a version you want me to test ...?

Some more context for what I'm trying to do: I inherited a front-end project built with webpack and babel and added typescript via awesome-ts-loader to the mix in a way that allows incremental conversion of the project to ts.  My notion is to have typescript compiler target es2015 and then let babel-preset-env handle downleveling to whatever browser versions I'm trying to maintain compat with.  I thought this would help maintain compatibility between the already existing js/transpilation/loading processes and the new typescript code.  Hence the desired usage of module: "es2015".

**Comment by breathe** [comment]
Follow up on this ... I figured out more of my issue ... 

Apparently setting the 'module' parameter to other than its default also causes the 'moduleResolution' parameter to change to a non-default value.  'moduleResolution' can be either 'classic' or 'node' -- the 'node' moduleResolution behavior includes the automagic search of 'directory/index' file for 'directory' modules.

I believe the documentation of default compiler options is not accurate https://www.typescriptlang.org/docs/handbook/compiler-options.html

Doesn't include esnext/es2015 strings which I believe are accepted by the compiler: 

This tsconfig.json is more explicit about my intensions -- and resolves my issue ...

```
{
  "compileOnSave": true,
  "compilerOptions": {
    "rootDir": "./",
    "noEmit": true,
    "lib": ["dom", "es2017", "esnext.asynciterable"],
    "strict": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "target": "esnext",
    "allowJs": true,
    "experimentalDecorators": false,
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "preserve",
    "allowSyntheticDefaultImports": true
  },
  "awesomeTypescriptLoaderOptions": {
    "useBabel": true
  },
  "include": ["./workspace/**/*ts", "./workspace/**/*.tsx"]
}
```

**Comment by andnp** [comment]
I guess I would personally prefer that the typings be agnostic to the `module` and `moduleResolution` setting. Perhaps not using the automagic directory search and simply listing the necessary directories? I recognize this is slightly a pain for maintenance, but it's more of a pain point for a user to have to track this down and change their compile settings to integrate with this lib.

**Comment by robdmoore** [comment]
I just encountered this problem. I think it should work ootb regardless of what module setting you have - this was a non-obvious error.

**Comment by mark-schaal** [comment]
Any update on this? I also see a similar behavior with the following TSConfig file in a vanilla CRA 2.0 application:

```
{
  "compilerOptions": {
    "target": "es2015",
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "lib": [
      "dom",
      "es2015",
      "es2016",
      "es2017",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": false,
    "jsx": "preserve",
    "sourceMap": true,
    "noEmit": true,
    "isolatedModules": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noUnusedLocals": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "allowUnreachableCode": false
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "setupJest.ts"
  ],
  "types": [
    "typePatches",
    "node",
    "webpack-env"
  ]
}
```

**Comment by mark-schaal** [comment]
Disregard completely, I just realized that the latest installation I had done with react-bootstrap was now the 1.x-beta release. The DT types for react-bootstrap are not compatible with v1, but react-bootstrap v1 ships with those types by default. Options are to use those or to downgrade react-bootstrap to 0.x.

Sorry about that.
