### ISSUE TITLE
[jsforce] bad and missing typings for querying

### ISSUE THREAD

**Issue by ScottMGerstl** [DefinitelyTyped/DefinitelyTyped#20039]
- [x] I tried using the `@types/jsforce@1.8.4` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @netes , @dolanmiu 

I am trying to query data using the jsforce library with your typings file. I am using version `@types/jsforce@1.8.4`. These are the two scenarios I have run into so far:

**Missing type export in index:**
`export { QueryResult, Query } from './query'`

This is preventing me from using strict type safety for query results.

**Bad typings for sObject querying** [per documentation](https://jsforce.github.io/document/#basic-method-chaining) under the SQL like verbs portion. here is an example:

```javascript
connection.sobject<Coverage>('Coverage__c')
    .select(['Id', 'Name'])
    .include('Coverage_State_Configurations__r')
        .select(['Id']).where({ Is_Active__c: true })
        .end()
    .where({ Is_Active__c: true }).execute(...);
```
The ts error I receive is `"Property 'include' does not exist on type 'Promise<Partial<Coverage>[]>'."` 

It returns a type of `Promise<Partial<T>>` and I believe it should be returning a type of `Query<T>`

I have found that if I use `sobject().find().select()...` I am returned the Query<T> type I need and it executes property.

**Comment by dolanmiu** [comment]
Found the commit which made this change, added a comment:

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/c2bc7792e69366f2183026aa902bcf1406189e0a#diff-22b5790b230cc31555e9a1cbf1988a6f

**Comment by ScottMGerstl** [comment]
@dolanmiu Do you know when the fix will be available?

**Comment by ScottMGerstl** [comment]
@dolanmiu I'm not really sure. I was able to get at `Query<T>` using `import { Query } from 'jsforce/query'`.

But, the more pressing issue is the one in which I have to use `.find()` between `sObject()` and `.select()` to have the right type returned to operate on from `select`. If you do not precede it with `find` (`sobject().select()`) you end up with a returned promise instead of a chaining Query reference. 

Thanks!

**Comment by moupaxolu** [comment]
Adding to the types problems, got an error using the example code from documentation:

> error TS2339: Property 'on' does not exist on type 'QueryResult<{}>'

when running :  
```
var records = [];
conn.query('SELECT Id FROM Account')
.on('record', function(record) {
  records.push(record);
})
.on('end', function(query) {
  console.log(records);
})
.on('error', function(error) {
  console.log('Error returned from query:', error);
})
.run({autoFetch: true, maxFetch: 25});
```
error line 3.

**Comment by dolanmiu** [comment]
I will make a fix today, I think the people who made the change made a mistake

**Comment by dolanmiu** [comment]
@moupaxolu Ok there is a few things

One, yes, there is an error with the typings

Two, it is not possible to have `.on` at the moment because Query is of type `stream.Readable` and it has a `destroy` method. Query also has a `destroy` method. But it is **DIFFERENT**. It simply won't let me, compile error. I believe the documentation is wrong.

http://jsforce.github.io/jsforce/doc/Query.html
https://nodejs.org/api/stream.html

**Comment by dolanmiu** [comment]
Created a pull request for this:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20101

**Comment by dolanmiu** [comment]
The line in particular:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20101/commits/a7cf2556183972672571b76f2061934907dd0cd1

**Comment by moupaxolu** [comment]
@dolanmiu 
I believe I got what you said, being a type adjustment issue only, but query does supports "on" method. Just tested the javascript version of it and works as documented:

`var jsforce = require('jsforce');
var dbconf = require('../dist/db_conf');

var conn = new jsforce.Connection({
});
var records = [];
conn.login(dbconf.username, dbconf.password, function (userinfo) {
  conn.query('SELECT Id FROM Account')
    .on('record', function (record) {
      records.push(record);
    })
    .on('end', function (query) {
      console.log(records);
    })
    .on('error', function (error) {
      console.log('Error returned from query:', error);
    })
    .run({ autoFetch: true, maxFetch: 25 });
});
`

This connected and produced the expected result on the console.

**Comment by moupaxolu** [comment]
@dolanmiu 

I have a question on your latest commit to types/jsforce/query.d.ts

```
-export class Query<T> extends Promise<T> {
+export class Query<T> implements Promise<T> {
```
shouldn't we also extend stream.Readable in this line?

**Comment by moupaxolu** [comment]
Sorry for the multiple posting...

Tried to manually apply your changes to my local files.

1. your "then" and "catch" won't compile properly. I just copied the declaration from other Promise type declaration and that was fixed (at least compiles now...)
```
    then<U>(onFulfilled?: (value: T) => U | Thenable<U>, onRejected?: (error: any) => void): Promise<U>;
    catch<U>(onRejected?: (error: any) => U | Thenable<U>): Promise<U>;
```

2. Error now just changed to 
> Property 'on' does not exist on type 'Query<QueryResult<{}>>'.

So I added the Readable extension to the declaration:
`export class Query<T> extends Readable implements Promise<T> {`

3. Now the error was your original one, about the destroy method type incompatibility. I just added the overload for it and all is working as expected now!
```
    destroy(callback?: (err: Error, ret: RecordResult) => void): Promise<RecordResult[]>;
    destroy(type?: string, callback?: (err: Error, ret: RecordResult) => void): Promise<RecordResult[]>;
    destroy(error?: Error): void;
```

@dolanmiu  Can you please validate and add to your commit?

Thanks

**Comment by dolanmiu** [comment]
@moupaxolu Thanks, thats a good idea adding destroy overload! Did not think of that, will add ASAP

**Comment by dolanmiu** [comment]
@moupaxolu Done

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20101/commits/512d717db2c000f1f1938612a6a88bed7140d2d0

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
