### ISSUE TITLE
[d3] Property 'version' does not exist on type

### ISSUE THREAD

**Issue by pingshunhuangalex** [DefinitelyTyped/DefinitelyTyped#20056]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek @gustavderdrache

I tried using the `@types/d3` package.

I get errors on:
`console.log(d3.version);`

All other d3 command seems to work fine, but the `version` property is nowhere to be found.

**Comment by tomwanzek** [comment]
@pingshunhuangalex Thanks for reporting that this overlooked property! PR to fix is submitted.
