### ISSUE TITLE
[@types/react-dom] has to support react-dom@16.0.0

### ISSUE THREAD

**Issue by cheerun** [DefinitelyTyped/DefinitelyTyped#20062]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkrotoff @MartynasZilinskas @andy-ms 

Hello, 

react-dom@16 introduces new `hydrate()` and other APIs. ~~deprecates existing `render()` API.~~
Therefore, `@types/react-dom` need to apply react-dom@16's new changes.

Thank you.

**Comment by wanglam** [comment]
I had the same problem. I want to use "createPortal" method but doesn't exists in @types/react-dom 15.5.5

**Comment by fongandrew** [comment]
Looks like some work started here (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18453) but stalled.

**Comment by djmarland** [comment]
`renderToNodeStream` is the method I'm looking to use

**Comment by harshes53** [comment]
@cheerun a correction, `render()` API is not deprecated. 

> Hydrating a server-rendered container now has an explicit API. If you're **reviving server-rendered HTML**, use ReactDOM.hydrate instead of ReactDOM.render. _Keep using ReactDOM.render_ if you're **just doing client-side rendering**.

**Comment by cheerun** [comment]
@harshes53 Oh, Thank you for correction!

**Comment by plantain-00** [comment]
There is a PR about this issue: #20065

**Comment by christian-schulze** [comment]
#20065 has been merged, but the module hasn't been published yet.

**Comment by ahstro** [comment]
@christian-schulze Waiting for the automatic publishing. Docs say it should be up within 24 hours of push

**Comment by styfle** [comment]
It's available now. You can see a working example here: https://github.com/styfle/react-server-example-tsx

**Comment by christian-schulze** [comment]
Can confirm. We've now upgraded our app to react 16 with no type errors 👍

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
