### ISSUE TITLE
Puppeteer - PDFOptions (printBackground and landscape) have wrong types

### ISSUE THREAD

**Issue by codeBelt** [DefinitelyTyped/DefinitelyTyped#20115]
@marvinhagemeister

**PDFOptions** `printBackground` and `landscape` need to have a type of `boolean` not `false`.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/df9390235d3d5f3141cf3195c1df2817d23fe241/types/puppeteer/index.d.ts#L128-L129

**Comment by marvinhagemeister** [comment]
@codeBelt Thanks for spotting this one! Just made a PR for this.
