### ISSUE TITLE
@types/jquery v3, $.fn, Property does not exist on type 'JQuery<HTMLElement>'

### ISSUE THREAD

**Issue by Arttse** [DefinitelyTyped/DefinitelyTyped#20156]
- [x] I tried using the `@types/jquery` package version `3.2.12` (installed by npm or yarn) and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (for now it's `2.5.3`)
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu, @borisyankov, @choffmeister, @Steve-Fenton, @Diullei, @tasoili, @seanski, @Guuz, @ksummerlin, @basarat, @nwolverson, @derekcicerone, @AndrewGaspar, @seikichi, @benjaminjackman, @JoshStrobl, @johnnyreilly, @DickvdBrink, @King2500

---

When I'm trying to create jQuery plugin using TypeScript with this (example) code:
```js
import $ from 'jquery';

$.fn.examplePlugin = function () {
  // do something
};
```
I get the error:
`error TS2339: Property 'examplePlugin' does not exist on type 'JQuery<HTMLElement>'`

I think problem in [types/jquery/index.d.ts#L71](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/924fafffc09cfeb0267573af2c847cdbfcfa464d/types/jquery/index.d.ts#L71) Need something to do with it. Thank you for your help.

**Comment by Steve-Fenton** [comment]
Because you are extending jQuery with something new, you'll need to add it to the interface in the definition.

Interfaces are open, so you can put the addition in your own file, you don't need to edit the jQuery type definition.

**Comment by Arttse** [comment]
@Steve-Fenton please give me a working example. Thank you.

**Comment by leonard-thieu** [comment]
Basic example can be found at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/dc178ad6fe32416622ec37de703bb72279ab4bb4/types/jquery/README.md#authoring-type-definitions-for-jquery-plugins

**Comment by Arttse** [comment]
@leonard-thieu I've tried this, it isn't work:
```js
import $ from 'jquery';

interface ExamplePlugin {
  settings: ExamplePluginSettings;

  (behavior: 'enable'): JQuery;
  (settings?: ExamplePluginSettings): JQuery;
}

interface ExamplePluginSettings {
  title?: string;
}

interface JQuery {
  examplePlugin: ExamplePlugin;
}

$.fn.examplePlugin = function (settings) {
  // do something
};

$.fn.examplePlugin.settings = {};

```
Compilation errors:
```
script.ts(18,6): error TS2339: Property 'examplePlugin' does not exist on type 'JQuery<HTMLElement>'.
script.ts(22,6): error TS2339: Property 'examplePlugin' does not exist on type 'JQuery<HTMLElement>'.
```

Maybe I'm doing something wrong? Could you please show me a working example? Thank you.

**Comment by Steve-Fenton** [comment]
I think the fix is to change:

```interface JQuery {```

To:

```interface JQueryStatic {```

Although I'm on mobile and guessing based on memory!

**Comment by Arttse** [comment]
@Steve-Fenton this also does not work

**Comment by Steve-Fenton** [comment]
Ah, I can see the problem. The interface is only merged if it has the same common root...

jQuery is global, but your file is a module.

```namespace global {
    interface JQuery {
        examplePlugin: ExamplePlugin;
    }
}```

A similar fix is to move it into a separate file that isn't a module.

**Comment by Arttse** [comment]
@Steve-Fenton I wrote the example code. You can experiment with it and please tell me about a correct working version (if it's not a bug).

<details>
<summary>src/script.ts</summary>

```js
import $ from 'jquery';

// Example from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/dc178ad6fe32416622ec37de703bb72279ab4bb4/types/jquery/README.md#authoring-type-definitions-for-jquery-plugins
interface ExamplePlugin {
  settings: ExamplePluginSettings;

  (behavior: 'enable'): JQuery;
  (settings?: ExamplePluginSettings): JQuery;
}

interface ExamplePluginSettings {
  title?: string;
}

interface JQuery {
  examplePlugin: ExamplePlugin;
}


$.fn.examplePlugin = function (settings) {
  // do something
};

$.fn.examplePlugin.settings = {};
```
</details>

<details>
<summary>tsconfig.json</summary>

```json
{
  "compilerOptions": {
    "outDir": "compiled",
    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noEmitOnError": true,
    "allowSyntheticDefaultImports": true,
    "removeComments": false,
    "sourceMap": true
  },
  "include": [
    "./src"
  ]
}
```
</details>

<details>
<summary>package.json</summary>

```json
{
  "scripts": {
    "compile": "tsc"
  },
  "devDependencies": {
    "@types/jquery": "3.2.12",
    "typescript": "2.5.3"
  },
  "dependencies": {
    "jquery": "3.2.1"
  }
}
```
</details>

Just run `npm install` and `npm run compile`. With this output is:
```
src/script.ts(20,6): error TS2339: Property 'examplePlugin' does not exist on type 'JQuery<HTMLElement>'.
src/script.ts(20,32): error TS7006: Parameter 'settings' implicitly has an 'any' type.
src/script.ts(24,6): error TS2339: Property 'examplePlugin' does not exist on type 'JQuery<HTMLElement>'.
```

**Comment by georgwittberger** [comment]
@Arttse Since you seem to be referring to my example project: I have found a way to fix the compile errors using the hints from this documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/dc178ad6fe32416622ec37de703bb72279ab4bb4/types/jquery/README.md#authoring-type-definitions-for-jquery-plugins
Please pull the latest version and try again: https://github.com/georgwittberger/jquery-plugin-typescript-example

**Comment by Arttse** [comment]
@georgwittberger thank you very much for this working example! The issue seems to be closed for me.

**Comment by enochfernandez** [comment]
how do i do $(document).foundation in my angular component. I get <script>
    $(document).foundation();
  </script>

ngAfterViewChecked() {
<script>
    $(document).foundation();
  </script>
  }

**Comment by aristotll** [comment]
Does this has anything to do with generics? I write a typing file according to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jquery/README.md, but get same error.

**Comment by leonard-thieu** [comment]
@aristotll Removing the import statement should fix the issue.

**Comment by marcus-petty** [comment]
Any ideas why running webpack would not pick up this error but running karma-webpack would pick it up?

I'm using the awesome-typescript-loader

ERROR in [at-loader] ./src/background/foo.ts:23:25
    TS2339: Property 'JsonRpcClient' does not exist on type 'JQueryStatic<HTMLElement>'.

**Comment by Mblkolo** [comment]
@aristotll, this declaration work with generic. jquery 3.3
`
interface JQuery<TElement> {
    spectrum: any;
}`

**Comment by PandaWood** [comment]
@Arttse would you mind elaborating on exactly what fixed this for you? I can see some links to code but it's difficult to figure out the change that actually fixed it.

**Comment by flendsiva** [comment]
> @Steve-Fenton it doesn't work.
> 
> Here's my code (example) for this issue:
> 
> src/script.ts
> tsconfig.json
> package.json
> You can try it yourself. Just run `npm install` and then `npm run compile`.
> 
> Output:
> 
> ```
> src/script.ts(20,6): error TS2339: Property 'examplePlugin' does not exist on type 'JQuery<HTMLElement>'.
> src/script.ts(20,32): error TS7006: Parameter 'settings' implicitly has an 'any' type.
> src/script.ts(24,6): error TS2339: Property 'examplePlugin' does not exist on type 'JQuery<HTMLElement>'.
> ```

iam also faced same problem,what is do..??

**Comment by yazan9** [comment]
> @Arttse would you mind elaborating on exactly what fixed this for you? I can see some links to code but it's difficult to figure out the change that actually fixed it.

I guess he won't. Got help, found a solution, and moved on ....

**Comment by Gennady-G** [comment]
I had some similar problem.

Used something like this:


```
    import * as $ from 'jquery';
    import * as slick from 'slick-carousel';
```

..

      // then in function:
```
      require('../../../node_modules/slick-carousel/slick/slick.js');

      (<any>$('.slider-wrap')).slick({
        dots: true,
        autoplay: true,
        autoplaySpeed: 1000
    });

```

p.s: install slick carousel and jQuery before:

```
    npm install jquery@>=1.8.0 --save-dev 
    npm i slick-carousel
```

**Comment by Arttse** [comment]
@PandaWood sorry for late answer. Better late than never.

At that time I was helped by using `Object.assign` with TypeScript generics. Referring to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20156#issuecomment-336919184 here is the specific example code: [georgwittberger/jquery-plugin-typescript-example/src/example-plugin.ts#L6](https://github.com/georgwittberger/jquery-plugin-typescript-example/blob/4eb8263f07d22d7bca17e5acc3cb850388b38b52/src/example-plugin.ts#L6)

**Comment by Jamal8548** [comment]
SOLUTION by **JAMAL**
you just need to add this line into a file named jQuery.d.ts and for that open these folders so first open NODE_MODULES then TYPES then jQuery then JQUERY.d.ts and then below interface JQuery.... line add this code of line.
**daterangepicker(options?: any, callback?: Function) : any;**
and dont forget to install jQuery through npm install --save [@types/jquery] in case you could not find this file into TYPES.

**Comment by faisal1357** [comment]
![image](https://user-images.githubusercontent.com/45657326/157632437-018d649f-f01c-4b70-b6f3-eb4c68aae483.png)
I had tried to resolve the problem please guide me

**Comment by faisal1357** [comment]
Property 'daterangepicker' does not exist on type 'JQuery<HTMLElement>'.ts(2339)

**Comment by yazan9** [comment]
> SOLUTION by **JAMAL** you just need to add this line into a file named jQuery.d.ts and for that open these folders so first open NODE_MODULES then TYPES then jQuery then JQUERY.d.ts and then below interface JQuery.... line add this code of line. **daterangepicker(options?: any, callback?: Function) : any;** and dont forget to install jQuery through npm install --save [@types/jquery] in case you could not find this file into TYPES.

Sorry, making a change in node_modules directory should never be the solution. Anytime you clone the respository (node_modules) should not be part of the repositpory - it defeats the purpose if it is - your change will not be there. It also often happens that node_modules need to be deleted and then you'd have to remember to put back the code change again.
