### ISSUE TITLE
Error using definitions

### ISSUE THREAD

**Issue by nrlquaker** [DefinitelyTyped/DefinitelyTyped#20155]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

I've [created](https://github.com/nrlquaker/DefinitelyTyped/commit/d7e4e0e68fad1ca81a6247654f440e50040d93f2) definitions for [blob-to-buffer](https://github.com/feross/blob-to-buffer), but got problems using them.
I've added
```
"baseUrl": "src/types",
        "typeRoots": [
            "types"
        ]
```
to `tsconfig.json` and try to use definitions:
```
import { blobToBuffer } from 'blob-to-buffer'
blobToBuffer(blob, (__: any, buffer: Buffer) => {
...
})
```
and got error in runtime:
`TypeError: blob_to_buffer_1.blobToBuffer is not a function`.
What am I doing wrong?
Using `const blobToBuffer = require('blob-to-buffer')` works fine.

**Comment by GlenCFL** [comment]
It's a runtime error without TypeScript outputting an error, so the problem is in your type definitions. They are too lax on imports due to TypeScript automatically converting files with only exports into a module. The module.exports from blob-to-buffer is a function, so you should probably use ```export = <<function>>``` in order to replicate this in your definition file.

**Comment by nrlquaker** [comment]
Thanks, got it working:
```
declare module "blob-to-buffer" {
    namespace blobToBuffer {}
    function blobToBuffer(blob: Blob, callback: (error: any, buffer: Buffer) => void): void
    export = blobToBuffer;
}
```
then `import * as blobToBuffer from 'blob-to-buffer'`
namespace is needed as explained [here](https://github.com/Microsoft/TypeScript/issues/5073).

**Comment by nrlquaker** [comment]
Reopen, because lint gives an error for this solution #20162

**Comment by GlenCFL** [comment]
It wants you to do something like this:
```ts
// Type definitions for blob-to-buffer 1.2
// Project: https://github.com/feross/blob-to-buffer
// Definitions by: nrlquaker <https://github.com/nrlquaker>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.2

/// <reference types="node" />

declare function blobToBuffer(blob: Blob, callback: (error: any, buffer: Buffer) => void): void;
declare namespace blobToBuffer {}
export = blobToBuffer;
```
This accomplishes exactly the same thing as your current version.

Alternatively, you could add the following to your tslint.json:
```json
{
  "rules": {
    "no-declare-current-package": false,
    "no-single-declare-module": false
  }
}
```

**Comment by nrlquaker** [comment]
Thanks, working with your suggestion.
