### ISSUE TITLE
[@types/node": "8.0.31] Class 'Module' incorrectly implements interface 'NodeModule'.

### ISSUE THREAD

**Issue by hoangphuong020193** [DefinitelyTyped/DefinitelyTyped#20158]
Today I updated @types/node from version 8.0.26 to 8.0.31 and I have a issue.

> [at-loader] Checking finished with 1 errors
> [at-loader] ./node_modules/@types/node/index.d.ts:5630:11
>     TS2420: Class 'Module' incorrectly implements interface 'NodeModule'.
>   Property 'hot' is missing in type 'Module'.

I use typescript 2.5.3, @types/webpack-env 1.13.1

How I can fix this error? Except rollback to 8.0.26?

**Comment by kemalcany** [comment]
This was raised also at [#19601](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19601)

It seems like people solved it via updating (or re-installing) the @types/webpack-env package.

But I am getting the same issue too, even though my repo doesn't have @types/webpack-env as a dependency.

I believe this issue needs to be open until there is a robust solution.

**Comment by rhonsby** [comment]
@kemalcany If you don't have types/webpack-env as a dependency, then it sounds like another dependency may be adding the property `hot` to the `Module` typing.

**Comment by Flarna** [comment]
This should be also fix via #19612 which was merged 4 days ago but for some reason not yet published to NPM.

**Comment by kemalcany** [comment]
I confirm that my errors gone after the 8.0.32 update today.
Thanks very much guys!

**Comment by hoangphuong020193** [comment]
I confirm this error was fixed on ver 8.0.32
