### ISSUE TITLE
@types/better-sqlite3 please export RunResult, Statement and Transaction

### ISSUE THREAD

**Issue by andersea** [DefinitelyTyped/DefinitelyTyped#20166]
- [x] I tried using the `@types/better-sqlite3` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Morfent 

It would be really helpful if the main internal types were exported. Most importantly RunResult, Statement and Transaction.

Right now there is no way to make definitions such as these:

```typescript
interface IPreparedStatements {
    [key: string]: Statement;
}
```

**Comment by BehindTheMath** [comment]
[RunResult](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fe94393d6ac8ac3effe56d038f5b6b34c17c8611/types/sqlite3/index.d.ts#L20) and [Statement](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fe94393d6ac8ac3effe56d038f5b6b34c17c8611/types/sqlite3/index.d.ts#L25) have been exported for years. They just need to be imported and referenced correctly:

```
import * as sqlite3 from 'sqlite3';
let statement: sqlite3.Statement;
```
Or:
```
import {Statement} from 'sqlite3';
let statement: Statement;
```

The sqlite3 library does not have a specific API for transactions. This has been a feature request for a long time (see [here](https://github.com/mapbox/node-sqlite3/issues/3) and [here](https://github.com/mapbox/node-sqlite3/issues/304)).
