### ISSUE TITLE
ManagementClientOptions are inadequately typed

### ISSUE THREAD

**Issue by danielglasgow** [DefinitelyTyped/DefinitelyTyped#20210]
See auth0 ManagemntClient implementation here:
https://github.com/auth0/node-auth0/blob/master/src/management/index.js#L72

The DefinitelyTyped library only specifies domain and token, however:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/auth0-js/index.d.ts#L456

clientId, clientSecrete, audience, scope are all missing.

**Comment by weswigham** [comment]
Fixed in #20214
