### ISSUE TITLE
[@types/sequelize] Missing new Op symbols for operators, replaces deprecated $op operators

### ISSUE THREAD

**Issue by natesilva** [DefinitelyTyped/DefinitelyTyped#20248]
- [ X ] I tried using the `@types/xxxx` package and had problems.
- [ X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ X ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @samuelneff, @CodeAnimal, @drinchev, @babolivier, @kukoo1, @oktapodia, @oktapodia

Beginning in Sequelize 4.12.0 use  of `$ne`, `$in`, `$not` and so on is deprecated. They have been replaced by new symbols in `Sequelize.Op`. If you use the deprecated `WHERE` operators you see this message:

> sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:236:13

Please add the new operators to the `WhereLogic` type.

**Comment by drinchev** [comment]
Please see :

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20284

**Comment by natesilva** [comment]
Thanks. I can’t mark this as a duplicate, but I’ll close it.
