### ISSUE TITLE
Dygraph legend -> add "never"

### ISSUE THREAD

**Issue by meriturva** [DefinitelyTyped/DefinitelyTyped#20244]
- [x] I tried using the `@types/xxxx` package and had problems.

@agaurav i guess that `never` is missing on legend type...see:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6638aa9d6bd7de2605b5109c00ddc70fa6c5cc2f/types/dygraphs/index.d.ts#L600

and

http://dygraphs.com/tests/legend-values.html

**Comment by agaurav** [comment]
Yeah, seems it isn't in up to date.
Created a PR for this.
