### ISSUE TITLE
[@types/react-dom] missing createPortal API

### ISSUE THREAD

**Issue by jgoz** [DefinitelyTyped/DefinitelyTyped#20245]
- [x] I tried using the `@types/react-dom` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @styfle @tkrotoff @MartynasZilinskas @andy-ms

`@types/react-dom@16` is missing the new [`createPortal` API](https://reactjs.org/docs/portals.html).

`createPortal` returns a [ReactPortal](https://github.com/facebook/react/blob/589c0a25dfa18c2090549cc6f5b626d69ea53c2a/src/renderers/shared/fiber/isomorphic/ReactTypes.js#L43-L50) instance, which is a valid [ReactNode](https://github.com/facebook/react/blob/master/src/renderers/shared/fiber/isomorphic/ReactTypes.js#L17).

**Comment by styfle** [comment]
I haven't tried out the portal feature yet so I wouldn't be the best person to write the definitions.

**Comment by dyst5422** [comment]
I looked at this a few days ago but didn't know how to type the portal. Seems like you actually did the work to dig this up

**Comment by kadishmal** [comment]
Has the merged code for `createPortal` been released?

**Comment by jgoz** [comment]
Yes, months ago. I should have closed the issue - thanks for checking.

**Comment by edhenderson** [comment]
Can I clarify what version this fix was added to please?

I've upgraded to 16.0.0 but it no likey `createPortal` - thanks so much.
