### ISSUE TITLE
[@types/three] Missing Matrix3 definitions on three-core.d.ts

### ISSUE THREAD

**Issue by mseefelder** [DefinitelyTyped/DefinitelyTyped#20251]
# I tried using the `@types/three` package and had problems:

`multiply`, `premultiply` and `multiplyMatrices` are missing on Matrix3 class (three-core.d.ts). These are already present on Matrix4, though.

Contributed to the file:
    @Flur
    @markezine markezine
    @efokschaner efokschaner
    @AnotherHermit AnotherHermit
    @RyanCavanaugh RyanCavanaugh
    @sandersn sandersn
    @simonkorz simonkorz
    @V0idExp V0idExp
    @Richard004 Richard004
    @sirDonovan sirDonovan
    @noveyak noveyak
    @LebedenkoN LebedenkoN
    @minestarks minestarks
    @matthewtebbs matthewtebbs
    @jramsay jramsay
    @hjin-me hjin-me
    @FishOrBear FishOrBear

**Comment by mseefelder** [comment]
Pull request with solution: #20253

**Comment by efokschaner** [comment]
I think this issue can be closed as the fix was merged.
