### ISSUE TITLE
@types/react 16 audio video element

### ISSUE THREAD

**Issue by anwarjaved** [DefinitelyTyped/DefinitelyTyped#20287]
After installing React 16 & latest typings @types/react, I am recieving these errors

TS2403: Subsequent variable declarations must have the same type. Variable 'audio' must be of type 'DetailedHTMLProps<AudioHTMLAttributes, HTMLAudioElement', but here has type 'DetailedHTMLProps<AudioHTMLAttributes, HTMLAudioElement>'.

TS2403: Subsequent variable declarations must have the same type. Variable 'video' must be of type 'DetailedHTMLProps<VideoHTMLAttributes, HTMLVideoElement', but here has type 'DetailedHTMLProps<VideoHTMLAttributes, HTMLVideoElement>'.

**Comment by nekoya** [comment]
I also had a same problem, but it seems fixed now.

I use yarn as package manager, perhaps its package may cause this problem.

The package didn't contain `global.d.ts` when the error was occurred.

**Comment by anwarjaved** [comment]
This was happening, beacuse I also have @types/react-dom typings, I think react-dom also have @types/react inside it. I removed @types/react, & its working fine now.

**Comment by lifeiscontent** [comment]
@anwarjaved isn't that a bug? Shouldn't the `@types/react-dom` package make the `@types/react` as a peer dependency instead?
