### ISSUE TITLE
@types/sweetalert needs update for 2.0 with promise-based API

### ISSUE THREAD

**Issue by roddypratt** [DefinitelyTyped/DefinitelyTyped#20286]
@ToastHawaii 

https://sweetalert.js.org/guides/#upgrading-from-1x

**Comment by ToastHawaii** [comment]
@roddypratt 
It seems that the contributors from sweetalert was faster than me, the project has now it own typings.
https://github.com/t4t5/sweetalert/tree/master/typings

**Comment by roddypratt** [comment]
@ToastHawaii Ah, thanks! Just updated to 2.0.5 and those files have appeared.

Next question is how to use them? Having removed @types/sweetalert my previous import is giving a 'cannot find module' error. 

`import * as swal from "sweetalert";` 

I should probably ask on the sweetalert repo, rather than ask you :)
