### ISSUE TITLE
@types/chalk is out of date

### ISSUE THREAD

**Issue by mtpultz** [DefinitelyTyped/DefinitelyTyped#20296]
- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Diullei @Bartvds @nicojs 

The type definitions for chalk are out of date.  Colours like `redBright` are not found as Chalk is now in v1.1.3, but the typings are for v0.4.0.

**Comment by elsigh** [comment]
What is one to do in this scenario? I've found that the type defs for rebass are also out of date / incomplete. Curious what one might do as a workaround.

**Comment by mtpultz** [comment]
@elsigh typically you look at the typings file for the authors and @ mention them that the file is out of date and if they have the time they might push an update.  Usually, I like to have an initial look myself to see if I'm able to PR the changes but find I'm really only useful with easier updates.

**Comment by elsigh** [comment]
I found somewhere else that a workaround is to use the `require` syntax, so it's nice to know there's something to do other than a) more work and b) wait n pray. ;)
