### ISSUE TITLE
@types/requirejs Variable 'require' must be of type 'NodeRequire', Duplicate identifier 'export='

### ISSUE THREAD

**Issue by UsernameError404** [DefinitelyTyped/DefinitelyTyped#20292]
- [x]  I tried using the `@types/requirejs` package and had problems.
- [x]  I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
  - Authors: @andy-ms @wald-tq @jens-duttke 

My index.ts file has following structure after the main code

```
if( typeof exports === 'object' )  { 
    module.exports = xyz; 
} else if( define.amd ) {
    define('a',callback);
}
```

I need both @ types/requirejs for AMD module and 'define' & also @ types/node otherwise it says cannot find name 'module'. Using both @ types/requirejs and @ types/node gives following errors.

`@ types/requirejs Variable 'require' must be of type 'NodeRequire'` (Will this be resolved by renaming 'require' in one of them). 
`Duplicate identifier 'export='` (How do I resolve this ? )

I want to use both types together, so I don't want to use --types tag when compiling, I have also excluded "node_modules" in tsconfig file. I am a newbie in typeScript so this might be a silly question. Please suggest a simple way to solve this.

**Comment by andy-ms** [comment]
I don't think you can use `@types/node` and `@types/requirejs` at the same time, because they both define a global variable `require` with the same name but with different types.
If you're not actually using requirejs, you could just use `declare var define: any;` instead of installing `@types/requirejs`.

**Comment by UsernameError404** [comment]
@andy-ms Okay thanks. Should I declare 'define' in global.d.ts file ? Can I copy the definition of 'define' from requirejs directly into this for getting the same functionality ? Should I define 'define' as an interface ?

**Comment by andy-ms** [comment]
If you're only using it in one place I would just define it right there -- but keep in mind it must appear in a top scope (above the `if`, not inside `else`). If you're using it in multiple places you should create a `.d.ts` file.
If you're only using it in one way you don't need an interface,  you can just use `declare function define(name: string, callback: ???): void;`.

**Comment by UsernameError404** [comment]
@andy-ms Okay. Thanks for replying. This solved my doubts. Please don't close this issue in case I need to ask something regarding this again.
