### ISSUE TITLE
Crypto js -> HmacSHA256 code gave error after npm update to latest type version

### ISSUE THREAD

**Issue by kuldeep-k** [DefinitelyTyped/DefinitelyTyped#20309]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] Authors: @misak113

I need to use authenticate AWS IOT in angular 4 using  "3.1.33",  So I had working code get from [aws iot js docs](http://docs.aws.amazon.com/general/latest/gr/signature-v4-examples.html#signature-v4-examples-javascript) like 

    getSignatureKey(key, dateStamp, regionName, serviceName) {
        const kDate = CryptoJS.HmacSHA256(dateStamp, 'AWS4' + key);
        const kRegion = CryptoJS.HmacSHA256(regionName, kDate);
        const kService = CryptoJS.HmacSHA256(serviceName, kRegion);
        const kSigning = CryptoJS.HmacSHA256('aws4_request', kService);
        return kSigning;
    };

But when I use updated  crypto js / types version "3.1.36", I get errors for wrong types

    Argument of type 'WordArray' is not assignable to parameter of type 'string'

After debug I get difference between versions.

Older index.d.ts file version : 

    type Hash = (message: string, key?: string, ...options: any[]) => string;

New index.d.ts file version : 

    type Hash = (message: string | LibWordArray, key?: string, ...options: any[]) => WordArray;

As return type is WordArray which is passed as second argument in my function calls which require only string type according to new types version. 

Currently I change directly into index.d.ts file to add WordArray into second argument type which works.

    type Hash = (message: string | LibWordArray, key?: string | WordArray, ...options: any[]) => WordArray;

But changes directly in node modules types will fail in further updates / also not recommended. 

NOTE : I do not know if this is genuine bug itself or AWS IOT integration issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
