### ISSUE TITLE
JQuery.append() raises compilation error when appending JQuery array

### ISSUE THREAD

**Issue by dan-def** [DefinitelyTyped/DefinitelyTyped#20316]
- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu 

I have come across some code that I think should compile but does not and can simply replicate the issue with the following:

```
namespace Testing {
    export class TestClass {
        private _someElements: Array<JQuery>;
        private _someElement: JQuery;

        public Foo() {
            this._someElement.append(this._someElements);
        }
    }
}
```
This fails with the error TS2345 stating:

> Argument of type 'JQuery<HTMLElement>[]' is not assignable to parameter of type '(this: HTMLElement, index: number, html: string) => string | Element | Text | Comment | Node[] | ...'.
> Type 'JQuery<HTMLElement>[]' provides no match for the signature '(this: HTMLElement, index: number, html: string): string | Element | Text | Comment | Node[] | JQuery<Node>'.

**Comment by leonard-thieu** [comment]
Interesting. This [works](https://fiddle.jshell.net/leonard_thieu/m2od3gmr/1/) but is undocumented. Thanks for reporting this. Will be fixed by #20319.
