### ISSUE TITLE
[Mongoose] - Subdocument assignment to parent document

### ISSUE THREAD

**Issue by olingern** [DefinitelyTyped/DefinitelyTyped#20331]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @simonxca

[Taken from the Mongoose docs:](http://mongoosejs.com/docs/subdocs.html)

```javascript
var childSchema = new Schema({ name: 'string' });

var parentSchema = new Schema({
  // Array of subdocuments
  children: [childSchema],
  // Single nested subdocuments. Caveat: single nested subdocs only work
  // in mongoose >= 4.2.0
  child: childSchema
});
```

Converted to Typescript (_assume Mongoose is imported_):

```typescript
const childSchema = new mongoose.Schema({ name: String });

const parentSchema = new mongoose.Schema({
  children: [childSchema],
  child: childSchema
});

```

We get the compile error:
```
severity: 'Error'
message: 'Argument of type '{ children: Schema[]; child: Schema; }' is not assignable to parameter of type 'SchemaDefinition'.
  Property 'child' is incompatible with index signature.
    Type 'Schema' is not assignable to type 'SchemaTypeOpts<any>'.
      Types of property 'index' are incompatible.
        Type '(fields: Object, options?: { [other: string]: any; expires?: string; }) => Schema' is not assignable to type 'string | boolean | IndexOpts'.
          Type '(fields: Object, options?: { [other: string]: any; expires?: string; }) => Schema' has no properties in common with type 'IndexOpts'.'
at: '89,49'
source: 'ts'
```

Casting the subdocument as a type of `any` _seems_ to fix the compilation error

```typescript
export const childSchema = new mongoose.Schema({ name: String }) as any;
```

**Comment by MatthiasKunnen** [comment]
Having the same problem.

**Comment by simonxca** [comment]
😳 hmm, I missed this. Sorry!
I believe https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21459 will fix the error.
