### ISSUE TITLE
aws-iot-device-sdk breaks on 2.1

### ISSUE THREAD

**Issue by thchia** [DefinitelyTyped/DefinitelyTyped#20343]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @niik @mlamp 

I'm not sure yet of the exact cause, but there is some mismatch in the mqtt types since aws-iot-device-sdk was [updated to 2.1.0](https://github.com/aws/aws-iot-device-sdk-js/blob/master/CHANGELOG.md#210-sep-28-2017) (it was just published). Notably the mqtt dependency was updated from 2.2 to 2.13, in between which time mqtt added their own types into the package. I think this type file still references definitions from the deprecated `@types/mqtt`.

I'll attempt a fix.

```
ERROR in [at-loader] ./node_modules/@types/aws-iot-device-sdk/index.d.ts:12:45 
    TS2694: Namespace '"/opt/atlassian/pipelines/agent/build/node_modules/mqtt/types/index"' has no exported member 'ClientOptions'.
ERROR in [at-loader] ./node_modules/@types/aws-iot-device-sdk/index.d.ts:182:67 
    TS2694: Namespace '"/opt/atlassian/pipelines/agent/build/node_modules/mqtt/types/index"' has no exported member 'ClientPublishOptions'.
ERROR in [at-loader] ./node_modules/@types/aws-iot-device-sdk/index.d.ts:190:45 
    TS2694: Namespace '"/opt/atlassian/pipelines/agent/build/node_modules/mqtt/types/index"' has no exported member 'Topic'.
ERROR in [at-loader] ./node_modules/@types/aws-iot-device-sdk/index.d.ts:190:67 
    TS2694: Namespace '"/opt/atlassian/pipelines/agent/build/node_modules/mqtt/types/index"' has no exported member 'ClientSubscribeOptions'.
ERROR in [at-loader] ./node_modules/@types/aws-iot-device-sdk/index.d.ts:199:56 
    TS2694: Namespace '"/opt/atlassian/pipelines/agent/build/node_modules/mqtt/types/index"' has no exported member 'ClientSubscribeOptions'.
ERROR in [at-loader] ./node_modules/@types/aws-iot-device-sdk/index.d.ts:260:103 
    TS2694: Namespace '"/opt/atlassian/pipelines/agent/build/node_modules/mqtt/types/index"' has no exported member 'Granted'.
ERROR in [at-loader] ./node_modules/@types/aws-iot-device-sdk/index.d.ts:337:67 
    TS2694: Namespace '"/opt/atlassian/pipelines/agent/build/node_modules/mqtt/types/index"' has no exported member 'ClientPublishOptions'.
ERROR in [at-loader] ./node_modules/@types/aws-iot-device-sdk/index.d.ts:345:45 
    TS2694: Namespace '"/opt/atlassian/pipelines/agent/build/node_modules/mqtt/types/index"' has no exported member 'Topic'.
ERROR in [at-loader] ./node_modules/@types/aws-iot-device-sdk/index.d.ts:345:67 
    TS2694: Namespace '"/opt/atlassian/pipelines/agent/build/node_modules/mqtt/types/index"' has no exported member 'ClientSubscribeOptions'.
ERROR in [at-loader] ./node_modules/@types/aws-iot-device-sdk/index.d.ts:354:56 
    TS2694: Namespace '"/opt/atlassian/pipelines/agent/build/node_modules/mqtt/types/index"' has no exported member 'ClientSubscribeOptions'.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
