### ISSUE TITLE
Scoped package types publishing issue

### ISSUE THREAD

**Issue by stevehipwell** [DefinitelyTyped/DefinitelyTyped#20347]
I created a merge request to get types in for the scoped `@koa/cors` package. My merge request of `@types/koa__cors` was accepted yesterday by @vvakame but now when I try to install I get the following error (paths truncated).

> 48 error path node_modules\.staging\@types\koa__cors-7321ab61
49 error code EISDIR
50 error errno -4068
51 error syscall open
52 error EISDIR: illegal operation on a directory, open 'node_modules\.staging\@types\koa__cors-7321ab61'
53 verbose exit [ -4068, true

I took a look at the tarball and compared it to other type packages and the difference was that there was no folder inside the tarball, just flat files.

I took a look at a non-scoped package published after mine `recharts` and that looks fine. Based on that I think there might be an issue with publishing scoped packages.

**Comment by vvakame** [comment]
@RyanCavanaugh could you take a look this issue?
I tried above commands. It can reproduce same result.
```
$  npm -v
5.3.0
$ npm install @types/koa__cors
...error...
$ yarn -v
1.1.0
$ yarn add @types/koa__cors
...error...
```

**Comment by RyanCavanaugh** [comment]
@andy-ms is this related to the problem we had on Friday?
