### ISSUE TITLE
redis RetryStrategyOptions.error has incorrect type

### ISSUE THREAD

**Issue by lochbrunner** [DefinitelyTyped/DefinitelyTyped#20357]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `redis/index.d.ts`) so they can respond.
  - Authors: @blakeembrey  @andy-ms 

**Expected Definition**

The `error` property of the `RetryStrategyOptions` looks as follows in the javascipt implementation:

```typescript
{
    code: 'ECONNREFUSED',
    errno: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 6379
}
```
as in [github.com/NodeRedis/node_redis](https://github.com/NodeRedis/node_redis/blob/eb3441c7e1e0e4720f095a598fc085979731d904/test/node_redis.spec.js#L985-L987)

**Actual Definition**

But in the definition [redis/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/redis/index.d.ts#L14) it is simple of type `Error`.

PS. I can fix that this weekend, if that is ok.

**Comment by andy-ms** [comment]
PRs accepted. 👍

**Comment by lochbrunner** [comment]
@andy-ms 
It seems that this error is of type [System Error](https://nodejs.org/api/errors.html#errors_class_system_error)

What is the corresponding TypeDefinition for that? Is it [ErrnoException](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L310-L316)?

**Comment by andy-ms** [comment]
That looks right, although I'm wondering why they marked all of the properties as optional.

**Comment by lochbrunner** [comment]
@andy-ms 
In the definition there states in the header:

> // Imported from: https://github.com/types/npm-redis

Are you using an import tool for copying this file? Or copy by hand?
