### ISSUE TITLE
@types/fetch-mock is missing fetchMock.sandbox() function

### ISSUE THREAD

**Issue by Halt001** [DefinitelyTyped/DefinitelyTyped#20421]
- [x] I tried using the `@types/fetch-mock` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @asvetliakov @tamird @merrywhether @chrissinclair  

The `fetchMock.sandbox()` function is missing from the type definitions.

**Comment by JakeSummers** [comment]
Was this issue resolved?  I am experiencing this issue using: `"fetch-mock": "^6.0.1",` and `"@types/fetch-mock": "^6.0.1"`.

**Comment by rubenv** [comment]
@JakeSummers No, type definition still misses the `sandbox()` method.
