### ISSUE TITLE
$.ajaxSettings not supported

### ISSUE THREAD

**Issue by dan-def** [DefinitelyTyped/DefinitelyTyped#20427]
- [x] I tried using the `@types/jQuery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu

According to the jQuery documentation there should be a property `$.ajaxSettings` which exposes an object of type `jQuery.AjaxSettings`. However, in the current version of the jQuery.d.ts file it is not defined.

This, among other things, allows you to access the function jQuery uses under the covers to create a jqXHR instance using `$.ajaxSettings.xhr()`.

**Comment by leonard-thieu** [comment]
Do you have a link to where `$.ajaxSettings` is documented? I can't seem to find it.

**Comment by dan-def** [comment]
The only mention of it I can find in the documentation is in this link http://api.jquery.com/jquery.ajax/ under the context heading. In the github repo, its definition can be found here: https://github.com/jquery/jquery/blob/master/src/ajax.js#L301

**Comment by leonard-thieu** [comment]
Will be fixed by #20433. Thanks for reporting this.

**Comment by dan-def** [comment]
Thank you.
