### ISSUE TITLE
fs-extra definitions missing constants, ReadStream, WriteStream definitions

### ISSUE THREAD

**Issue by damianb** [DefinitelyTyped/DefinitelyTyped#20453]
- [x] I tried using the `@types/fs-extra` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alan-agius4, @midknight41, @shiftkey, @mees-

Definitions are missing the following: 

`fs.constants.*`, `fs.F_OK`, `fs.R_OK`, `fs.W_OK`, `fs.X_OK`, `fs.ReadStream`, `fs.WriteStream`.

It appears that these are populated due in part to relying on `graceful-fs`.  They are confirmed to exist upon hand inspection in REPL when require'ing the `fs-extra` module directly.

```
$ node
> fs = require('fs-extra')
{ constants:
   { O_RDONLY: 0,
     O_WRONLY: 1,
     O_RDWR: 2,
     S_IFMT: 61440,
     S_IFREG: 32768,
     S_IFDIR: 16384,
     S_IFCHR: 8192,
     S_IFLNK: 40960,
     O_CREAT: 256,
     O_EXCL: 1024,
     O_TRUNC: 512,
     O_APPEND: 8,
     F_OK: 0,
     R_OK: 4,
     W_OK: 2,
     X_OK: 1 },
  Stats: [Function: Stats],
  F_OK: 0,
  R_OK: 4,
  W_OK: 2,
  X_OK: 1,

...
```

**Comment by damianb** [comment]
Hmmm, looking at this further, this appears to be an odd sort of issue - mainly revolving around how TypeScript itself no longer lets you use `fs.ReadStream` for instanceof checks.   Might be a deeper problem here.

**Comment by damianb** [comment]
Yep, mainly deeper issues here. Closing.

**Comment by Augustin82** [comment]
Deeper issues but constants are still not exposed, are they?
What's the proposed solution here?
