### ISSUE TITLE
React-Redux: Destructured component not validating props when mapDispatchToProps is included

### ISSUE THREAD

**Issue by herecydev** [DefinitelyTyped/DefinitelyTyped#20456]
- [x ] I tried using the `@types/xxxx` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @thasner @kenzierocks @clayne11 @tansongyang @NicholasBoll 

Given the very simple component

```tsx
import * as React from "react";

const Message = ({ foo, bar }: { foo: string, bar: string}) =>
    <div>{foo}{bar}</div>

export default Message;
```

And container component

```tsx
import Message from "./Message";
import { connect } from "react-redux";

const mapStateToProps = (props : any) => ({
    foo: props.foo
});

export default connect(mapStateToProps, null)(Message);
```

The last line is correctly identified by typescript as problematic; `Property 'bar' is missing in type '{ foo: any; } & null & { children?: ReactNode; }'.`. Excellent, I have type safety.

However upon the inclusion of an empty mapDispatchToProps, i.e.

```tsx
import Message from "./Message";
import { connect } from "react-redux";

const mapStateToProps = (props : any) => ({
    foo: props.foo
});

const mapDispatchToProps = () => ({
});

export default connect(mapStateToProps, mapDispatchToProps)(Message);
```

**or**

```tsx
import Message from "./Message";
import { connect } from "react-redux";

const mapStateToProps = (props : any) => ({
    foo: props.foo
});

export default connect(mapStateToProps)(Message);
```

The compiler can no longer highlight the issue. Interestingly the following will show the issue again;

```tsx
import Message from "./Message";
import { connect } from "react-redux";

const mapStateToProps = (props : any) => ({
    foo: props.foo
});

const mapDispatchToProps = () => ({
    a: 2
});

export default connect(mapStateToProps, mapDispatchToProps)(Message);
```

Is there an issue when the `TDispatchProps` is {} that causes typescript to not see the errors?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
