### ISSUE TITLE
[@types/three] Missing mesh definitions on three-core.d.ts

### ISSUE THREAD

**Issue by neukym** [DefinitelyTyped/DefinitelyTyped#20468]
- [x] I tried using the `@types/three` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @gyohk, @florentpoujol, @SereznoKot, @omni360, @ivoisbelongtous, @piranha771,  @qszhusightp, @nakakura, @Pro, @efokschaner

### Issue

`morphTargetInfluences` and `morphTargetDictionary` are both missing from class `mesh` in `three-core.d.ts`:

```typescript
export class Mesh extends Object3D {
    constructor(geometry?: Geometry | BufferGeometry, material?: Material | Material []);

    geometry: Geometry|BufferGeometry;
    material: Material | Material[];
    drawMode: TrianglesDrawModes;

    setDrawMode(drawMode: TrianglesDrawModes): void;
    updateMorphTargets(): void;
    getMorphTargetIndexByName(name: string): number;
    raycast(raycaster: Raycaster, intersects: any): void;
}
```

I'm guessing the reason they are missing is that they are not initially defined in the original [threejs pseudo-constructor](https://github.com/mrdoob/three.js/blob/dev/src/objects/Mesh.js):

```javascript
function Mesh( geometry,   material   ) { 
  Object3D.call( this );  
  this.type = 'Mesh';  
  this.geometry   = geometry !== undefined ? geometry : new BufferGeometry();
  this.material   = material !== undefined ? material : new MeshBasicMaterial( { color: Math.random() * 0xffffff } );  
  this.drawMode   = TrianglesDrawMode;
  this.updateMorphTargets();  
}
```

 and only added as properties on an 'as needed' basis, eg. (from `mesh.js` itself):

```javascript
  if ( source.morphTargetInfluences !== undefined ) {
    this.morphTargetInfluences = source.morphTargetInfluences.slice();
  }
```
etc.

Could I add `morphTargetInfluences` and `morphTargetDictionary` to the `mesh` class  in `three-core.d.ts` (given that they are both genuine properties, albeit initially undefined), or do `@types/three` authors prefer for the original ThreeJS pseudo-constructors to include them as initialised  fields before they can be added, in which case I will have to raise an issue in ThreeJS first?

**Comment by efokschaner** [comment]
Hi there @neukym, thanks for looking in to this! I see no reason not to declare these members on the class as long as the optionality is represented in the type declaration. Let me know if you need any help adding them, and I'll be available for a review whenever you want.

**Comment by neukym** [comment]
> I see no reason not to declare these members on the class as long as the optionality is represented in the type declaration. 

Ah, great idea, I didn't realise this was an option.

> Let me know if you need any help adding them, and I'll be available for a review whenever you want.

Thanks, I'll work on creating a PR later today.

**Comment by neukym** [comment]
Pull request with solution: #20490
