### ISSUE TITLE
@types/node - fs.ReadStream incorrectly defined as an interface only

### ISSUE THREAD

**Issue by damianb** [DefinitelyTyped/DefinitelyTyped#20496]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DefinitelyTyped @parambirs @tellnes @WilcoBakker @octo-sniffle @smac89 @Flarna @mwiktorczyk @wwwy3y3 @Tyriar @DeividasBakanas @kjin @alvis

As on tin.  This seems to be a deeper issue with the node typescript definitions, in that fs.ReadStream, fs.WriteStream, and possibly other definitions are defined as interfaces; these are actually exposed in node as classes and their definition seems to be inaccurate.

What we can do in node.js, currently:

``` js
const fs = require('fs');

let content;
if(a == 'stream') {
    content = fs.createReadStream('./blah.txt');
} else if(a == 'buffer') {
    content = Buffer.from('blah')
}

// ...

if(content instanceof fs.ReadStream) {
    // do x
}

```

What this prevents in TypeScript, currently, is the following:

``` ts
import * as fs from 'fs'

let content: Buffer|fs.ReadStream

if(a == 'stream') {
    content = fs.createReadStream('./blah.txt')
} else if (a == 'buffer') {
    content = Buffer.from('blah')
}

// the following results in: 'ReadStream' only refers to a type, but is being used as a value here.
if(content instanceof fs.ReadStream) {
    // do x
}
```

This is entirely legitimate use, yet is impeded by the current incorrect definition.

This appears related to #16201, possibly affects #20487.

(p.s., sorry for all the @'s - you have the issue template to thank.)

**Comment by Flarna** [comment]
Is this still an issue as #20493 has been merged meanwhile?

**Comment by zvin** [comment]
In node6 types, `fs.ReadStream` is still an interface: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v6/index.d.ts#L2500
