### ISSUE TITLE
Bluebird - constructor wants `then`-able even though it is overloaded

### ISSUE THREAD

**Issue by conradkleinespel** [DefinitelyTyped/DefinitelyTyped#2051]
Hello everyone !

I am using the `bluebird` Promise library and get a TS compiler error when instantiating a Promise. By just switching lines of two constructor overloads in the definition file, it magically works again (which seems weird, which is why I'm posting here).

Below, I explain what exactly is going on and ask for any valuable input on this issue.

Here's the code in question:

``` typescript
// get either an override file path of the original file path if no override
// is available (used for things like controllers, config, views, models)
private getFile(path: string) {
    var self = this;
    return new Promise<string>(function(fulfill, reject) {
        var override: string = self.getOverrideRoot() + '/' + path;
        fs.exists(override, function(exists: boolean) {
            if (exists)
                fulfill(override);
            else
                fulfill(self.getRoot() + '/' + path);
        });
    });
}
```

I am fulfilling the Promise with a `string` but the TS compiler seems to be asking for a `Promise.Thenable<string>`.

So I had a look at the definition file, which has this:

``` typescript
/**
 * Create a new promise. The passed in function will receive functions `resolve` and `reject` as its arguments which can be called to seal the fate of the created promise.
 */
constructor(callback: (resolve: (thenable: Promise.Thenable<R>) => void, reject: (error: any) => void) => void);
constructor(callback: (resolve: (result: R) => void, reject: (error: any) => void) => void);
```

By switching the two lines, putting the second constructor interface above the first one, I have no more error messages.

Have you had this problem? Would you know of a way to solve this? Is this an issue with the compiler not recognising overloads?

Thanks for your help.

**Comment by pcfreak30** [comment]
Anyone want to get this fixed? This still appears to be a problem.

**Comment by conradkleinespel** [comment]
This was for bluebird, I have no idea if it's still current and has been stale for 3 years, so I'm closing.
