### ISSUE TITLE
@types modules add unneeded dependencies

### ISSUE THREAD

**Issue by Flarna** [DefinitelyTyped/DefinitelyTyped#20519]
- [x] I tried using the `@types/pg-types` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

I found that installing `@types/pg-types` installs also `moment` as it is part of the `dependencies` section in its package.json. Actually pg-types needs `moment` only in tests - and even there it's enough to have the typings.
I tried to change package.json to reference `moment` as devDependency but this seems to be not allowed:
```
Error: C:\workspaces\GitHubForks\DefinitelyTyped/types/pg-types/package.json should contain "dependencies" or not exist.
    at checkDependencies (C:\workspaces\GitHubForks\DefinitelyTyped\node_modules\types-publisher\src\lib\definition-parser.ts:143:9)
    at C:\workspaces\GitHubForks\DefinitelyTyped\node_modules\types-publisher\src\lib\definition-parser.ts:103:51
    at Generator.next (<anonymous>)
    at fulfilled (C:\workspaces\GitHubForks\DefinitelyTyped\node_modules\types-publisher\bin\lib\definition-parser.js:4:58)
    at <anonymous>
```

A fast search has shown that pg-types is not the only one with this issue.
Is it really intended that @types modules result in such dependencies?

fyi @andy-ms @RyanCavanaugh

**Comment by andy-ms** [comment]
Packages should avoid adding unnecessary dependencies just for tests. We don't support test-only dependencies because it would be hard to verify that they really are only necessary for tests -- we would have to compile twice, once with the dependency and once without. Otherwise we might publish a package that only worked with a dependency that wasn't included.
