### ISSUE TITLE
@types/karma broken with removal of log4js typings

### ISSUE THREAD

**Issue by solkaz** [DefinitelyTyped/DefinitelyTyped#20534]
- [x] I tried using the `@types/karma` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkrotoff 

#20518 had removed the log4js typings from DT, as they are now on the log4js repo; however, Karma's typings are now broken as log4js does not export `AppenderConfigBase`:

```
Namespace '"/path/to/project/node_modules/log4js/index"' has no exported member 'AppenderConfigBase'
```

**Comment by AhsanAyaz** [comment]
+1. 
I'm facing this issue too. 
```
(286,26): error TS2694: Namespace '"node_modules/log4js/index"' has no exported member 'AppenderConfigBase'.
```

**Comment by dfstewart3** [comment]
+1

**Comment by andres-artunduaga** [comment]
+1

**Comment by AhsanAyaz** [comment]
Is there a workaround till this is fixed? 
I'm running unit tests on TravisCI.
I tried `"@types/karma": "1.7.0",` to have it installed the exact version I have locally (which doesn't break). The tests run fine locally. But they break on TravisCI

**Comment by clearyusc** [comment]
+1

**Comment by BLipscomb** [comment]
+1

**Comment by crisrendon** [comment]
+1

**Comment by sebastianhaas** [comment]
Not a fix, but as a workaround, you can manually add:

```typescript
export interface AppenderConfigBase {
  type: string;
  category?: string;
  layout?: { type: string;[key: string]: any }
}
```

to `node_modules/log4js/index.d.ts` to at least get going and continue work

**Comment by cschear** [comment]
We fixed our build by including the previous version of log4js ahead of karma:
`"devDependencies": {
    ...
    "@types/log4js": "0.0.33",
    "@types/bowser": "1.0.30",
    "@types/jasmine": "2.5.51",
    "@types/karma": "0.13.35",
    "@types/lodash": "4.14.65"
  }`

**Comment by vorobiel** [comment]
+1

**Comment by steveblue** [comment]
+1

**Comment by desmondcain** [comment]
+1

**Comment by mattdsteele** [comment]
I think the Karma typings still need published before this can be closed?

**Comment by vatsalpande** [comment]
Facing the same issue with 1.7.1

**Comment by andy-ms** [comment]
@vatsalpande The newest `@types/karma` doesn't import anything from `log4js` so you probably had an error while trying to update it -- double-check the actual version in `node_modules/@types/karma/package.json`.

**Comment by vatsalpande** [comment]
Looks like a miss from my side. Its working fine now. Thanks for your input.

**Comment by loonix** [comment]
as @cschear said, for me I only had to add the folowing one: "devDependencies": { ... "@types/log4js": "0.0.33", ...}
