### ISSUE TITLE
Sharepoint.D.TS Missing Fields on ContextInfo and RenderContext_InView

### ISSUE THREAD

**Issue by Cityonhill93** [DefinitelyTyped/DefinitelyTyped#20531]
- [X ] I tried using the `@types/xxxx` package and had problems.
- [X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

@gandjustas
@andrei-markeev
@baywet
@teroarvola

In the JS for SharePoint, "ContextInfo" contains fields called ListTitle and SiteTitle.

Similarly, RenderContext_InView is missing a field called LastSelectedItemIID.

In our current environment, we have the d.ts files checked in, but have modified them to contain these fields. However, we would like to move towards NPM packages. We cannot do so until we get these fields added to the interfaces.

**Comment by Cityonhill93** [comment]
I have created a fork and will resolve this myself.

**Comment by baywet** [comment]
@Cityonhill93 are you talking about the _spPageContextInfo? I added listTitle 4 months ago, webTitle was already there and siteTitle doesn't show up in the context of the SharePoint Online Page.
For RenderContext_InView LastSelectedItemId is here (L1207) but typed as any.

**Comment by baywet** [comment]
disregard my previous comment, saw your PR :)

**Comment by baywet** [comment]
@Cityonhill93 maybe this issue could be closed as the PR has been merged? (I don't have contrib rights on the repos, so you'd need to do it yourself)
