### ISSUE TITLE
@types/sharepoint

### ISSUE THREAD

**Issue by przemasd** [DefinitelyTyped/DefinitelyTyped#20547]
Hi, 
I must use the SP.js in my SPFx Web Part, on Microsoft Doc I found tutorial how install and use library in code, but if gulp build my solution then I have strange errors.

I try found solution this issue in google and on this github, but I didn't give up. 

> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3104,27): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3368,32): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3474,32): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3610,17): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3829,17): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3831,19): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3833,21): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3835,18): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3902,21): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3950,31): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(5627,37): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(5629,60): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6877,34): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6878,44): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6879,40): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6880,35): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6881,45): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6949,34): error TS1005: ',' expected.
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(73,42): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3104,29): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3104,40): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3368,34): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3368,42): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3474,34): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3474,42): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3610,19): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3612,33): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3822,39): error TS2314: Generic type 'ListItemCollection<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3824,61): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3827,59): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3829,19): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3829,40): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3831,21): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3831,42): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3833,23): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3833,44): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3835,20): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3835,48): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3837,53): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3839,34): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3841,35): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3902,23): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3934,26): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3950,33): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3950,72): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3951,31): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3952,33): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3953,38): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3978,72): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3979,31): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(3980,33): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(4278,26): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(4455,41): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(4815,32): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(4846,41): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(4866,30): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(5627,39): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(5627,73): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(5629,62): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(5629,100): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(5831,84): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6877,36): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6877,51): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6878,46): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6878,61): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6879,42): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6879,57): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6880,37): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6880,52): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6881,47): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6881,62): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6947,61): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6949,36): error TS2368: Type parameter name cannot be 'any'
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(6949,83): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(7923,83): error TS2314: Generic type 'ListItemCollection<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(7923,127): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(7930,82): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(7930,107): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(7931,89): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(7931,106): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(8196,31): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(8197,35): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(8200,28): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(8201,32): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(8560,38): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(8561,42): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(8561,53): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(8565,77): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(8570,28): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(8944,71): error TS2314: Generic type 'List<T, any>' requires 2 type argument(s).
> Error - typescript - node_modules\@types\sharepoint\index.d.ts(9207,61): error TS2314: Generic type 'ListItem<T, any>' requires 2 type argument(s).
> Error - 'typescript' sub task errored after 3.85 s
>  "TypeScript error(s) occurred."

I try install an uninstall  @types/microsoft-ajax @types/sharepoint and install newest TypeScript

**Comment by andy-ms** [comment]
It looks like you're not actually using the newest version of TypeScript, since you seem to be failing on type parameter defaults as in `ListItem<T = any>` which were added in ts2.3.

**Comment by przemasd** [comment]
Issue resolve by update Visual Studio, I don't know why VS using older version of TS
