### ISSUE TITLE
`@types/chai` missing under Assert several functions

### ISSUE THREAD

**Issue by elishas** [DefinitelyTyped/DefinitelyTyped#20604]
[ x] I tried using the `@types/chai` package and had problems.
`@types/chai` missing under Assert several functions:
- hasAnyKeys
- hasAllKeys
- containsAllKeys
- doesNotHaveAnyKeys
- doesNotHaveAllKeys
- hasAnyDeepKeys
- hasAllDeepKeys
- containsAllDeepKeys-
- doesNotHaveAnyDeepKeys

**Comment by prasdeva** [comment]
+1
