### ISSUE TITLE
[@types/bootstrap] Types for Bootstrap 4

### ISSUE THREAD

**Issue by furdzik** [DefinitelyTyped/DefinitelyTyped#20646]
- [x] I tried using the `@types/bootstrap` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov

Hi,
I using TypeScript and Bootstrap in version 4.0.0-alpha.6 in my project , but there is no types for it (there is for previous version).
Is there a posibility to add types for Bootstrap 4 as well?

**Comment by alirobe** [comment]
@borisyankov BS4 is now released. Any chance of getting this?
