### ISSUE TITLE
[@types/react-responsive] new version 2.0, lack of style property

### ISSUE THREAD

**Issue by xaviergonz** [DefinitelyTyped/DefinitelyTyped#20656]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @asvetliakov

I'm using the type definitions at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-responsive but they seem pretty outdated.

What especially bothers me is the lack of a style?: React.CSSProperties prop type, since the MediaQuery uses a div to wrap the children and I need to be able to style it.

I tried raising this issue to the repo author (https://github.com/contra/react-responsive/issues/126) but he said that I should better post the issue here since he's not interested in adding TS definitions.

**Comment by asvetliakov** [comment]
Feel free to send the PR, must be simple change, just extends MediaQueryProps from React.HTMLAttributes

**Comment by xaviergonz** [comment]
@asvetliakov 
this is the wrapper tsx file I created for v3.0, however I don't know how to properly transform it to a d.ts file :(

```js
import * as React from 'react';

const reactResponsive = require('react-responsive');

export const toQuery = reactResponsive.toQuery as (obj: MediaQueryMatchers) => string;

export class MediaQuery extends React.Component<MediaQueryProps> {
  render() {
    const {children, ...other} = this.props;
    return React.createElement(reactResponsive.default, other, ...children);
  }
}

export interface MediaQueryMatchers {
  orientation?: 'portrait' | 'landscape';

  scan?: 'progressive' | 'interlace';

  aspectRatio?: string;
  minAspectRatio?: string;
  maxAspectRatio?: string;

  deviceAspectRatio?: string;
  minDeviceAspectRatio?: string;
  maxDeviceAspectRatio?: string;

  height?: number | string;
  minHeight?: number | string;
  maxHeight?: number | string;

  deviceHeight?: number | string;
  minDeviceHeight?: number | string;
  maxDeviceHeight?: number | string;

  deviceWidth?: number | string;
  minDeviceWidth?: number | string;
  maxDeviceWidth?: number | string;

  width?: number | string;
  minWidth?: number | string;
  maxWidth?: number | string;

  color?: boolean;
  minColor?: number;
  maxColor?: number;

  colorIndex?: boolean;
  minColorIndex?: number;
  maxColorIndex?: number;

  monochrome?: boolean;
  minMonochrome?: number;
  maxMonochrome?: number;

  resolution?: number | string;
  minResolution?: number | string;
  maxResolution?: number | string;

  type?: 'all' | 'grid' | 'aural' | 'braille' | 'handheld' | 'print' | 'projection' | 'screen' | 'tty' | 'tv' | 'embossed';
}

export interface MediaQueryProps extends MediaQueryMatchers {
  component?: string | React.SFC<any> | React.ClassType<any, any, any> | React.ComponentClass<any>;
  query?: string;
  style?: React.CSSProperties;
  className?: string;
  children?: React.ReactNode | ((matches: boolean) => React.ReactNode);
  values?: MediaQueryMatchers;
}
```

**Comment by alechill** [comment]
@asvetliakov @xaviergonz I also needed the up to date types and saw your issues too, have raised a PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20949

I lifted some of the props from this issue so have added you to authors (let me know if you don't want this)

Props have been organised out into different interfaces to match the way the lib identifies them as groups for props/matchers/features/types so can be better included/excluded from the correct places

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
