### ISSUE TITLE
Compiler error in @types/request-promise

### ISSUE THREAD

**Issue by ThomWright** [DefinitelyTyped/DefinitelyTyped#20678]
- [x] I tried using the `@types/request-promise` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cglantschnig @joeskeen @AyaMorisawa 

Currently I can't use `@types/request-promise because it gives a compiler error!

```
Error at node_modules/@types/request-promise/index.d.ts:13:15: Interface 'RequestPromise' cannot simultaneously extend types 'Request' and 'Bluebird<any>'.
  Named property 'toJSON' of types 'Request' and 'Bluebird<any>' are not identical.
```

**Comment by andy-ms** [comment]
Could you check the versions of the packages you're using? For `@types/request-promise` and `@types/bluebird` and `@types/request`.

**Comment by schaable** [comment]
I'm having the same error since this morning. Package versions:

```
@types/request-promise@4.1.38
@types/bluebird@3.5.16
@types/request@2.0.0
```

Tried with `typescript@next`, same results.

**Comment by mariuszbajorek** [comment]
In @types/bluebird/index.d.ts change the line:
toJSON(): Object;

to

toJSON(): object;

**Comment by schaable** [comment]
I think you mean in file types/request/index.d.ts

Updating `request` to `2.0.6` solves it.

**Comment by Akuukis** [comment]
I can confirm that with `@types/request@2.0.6` and `@types/bluebird@3.5.16` it works now also for me. And after tinkering manually I can confirm that at least one of the causes was `toJSON(): Object;` not being `toJSON(): object;`.

**Comment by ThomWright** [comment]
Turns out I didn't have `@types/bluebird` installed (at least not directly). Installing it bumped `@types/request` to the required version and everything started working. I'm gonna close this :+1:
