### ISSUE TITLE
Wrong Type in interface Options for react-bootstrap-table

### ISSUE THREAD

**Issue by jop19** [DefinitelyTyped/DefinitelyTyped#20684]
Hello,

in the interface Option for react-bootstrap-table the element 'paginationShowsTotal' got wrong parameters. The PropTypes are  [ PropTypes.bool, PropTypes.func ] but it's declared as 'boolean | ReactElement<any>'

**Comment by RetroCraft** [comment]
Hi,

I'm not a contributor but I think you're understanding Typescript incorrectly. Typescript doesn't use prop-types types, so `PropTypes.bool` is the same thing as `boolean` in Typescript. In the [documentation](http://allenfang.github.io/react-bootstrap-table/docs.html#paginationShowsTotal) it shows that `paginationShowsTotal` uses the function as a React element, ergo `ReactElement<any>`.

However, the documentation also specifies that the function isn't a conventional React component, it intead is a function which accepts three params: `(start: number, to: number, total: number) => React.ReactElement<any>`.

You're also supposed to mention the type authors: @flaub, @alelode, @UJosue10.
