### ISSUE TITLE
[flatpickr] Deprecate types in favour of internal project types

### ISSUE THREAD

**Issue by begincalendar** [DefinitelyTyped/DefinitelyTyped#20701]
- [x] I tried using the `@types/flatpickr` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @UnwrittenFun @rowellx68 @wagich @chmin

Should the types in here be deprecated in favour of those [within the project](https://github.com/chmln/flatpickr/blob/8c55b50373e42e4eeb386112b5e0ec578298e229/index.d.ts)?

**Comment by rowellx68** [comment]
Yeah, this can now be deprecated since flatpickr provides its own. Willing to do it yourself and do a PR? README should have details on how to do this.

**Comment by begincalendar** [comment]
Cool. I'll give it a shot.

**Comment by begincalendar** [comment]
I have a [branch](https://github.com/begincalendar/DefinitelyTyped/tree/fix-20701) for the changes, but it appears that the project hasn't finished exporting all TypeScript types (or at least not in the latest package release).

So this will have to wait until that is done.

**Comment by begincalendar** [comment]
Now blocked by Microsoft/types-publisher#393.
