### ISSUE TITLE
Change interface of lodash Size 

### ISSUE THREAD

**Issue by theGABS** [DefinitelyTyped/DefinitelyTyped#20710]
- [x] I tried using the `@types/lodash` package and had problems.

First I think its typescript trouble, but then I understand typescript work correct. 
https://github.com/Microsoft/TypeScript/issues/19246

I some case 
`size<T>(collection: List<T>|Dictionary<T>): number;`
does not work correct (see https://github.com/Microsoft/TypeScript/issues/19246)
I think if we change interface to 
`size(collection: List<any>|Dictionary<any>): number`
It will be work for any array or object.

**Comment by aj-r** [comment]
Fixed in 4.14.78. The new definition is:

`size(collection: object | string | null | undefined): number;`

Also, make sure to mention the authors when you create and issue, otherwise you're unlikely to get a response. You're like I stumbled across these issues :)

**Comment by aj-r** [comment]
@andy-ms this can be closed
