### ISSUE TITLE
[@types/lodash] differenceBy types are more strict than code suggests

### ISSUE THREAD

**Issue by legatek** [DefinitelyTyped/DefinitelyTyped#20741]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/lodash` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I'm using Typescript 2.3.4 (latest dependency available for my Angular project)
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @ericanderson @aj-r @Ailrun @e-cloud

I have a couple of different classes that use the same semantic property name. Prior to the 4.14.78 release, I could do the following:

```
class A {
  constructor(myName) {
    this.name = myName;
  }
}

class B {
  constructor(myName, age) {
    this.name = myName;
    this.age = age;
  }
}

let a1 = new A('a1');
let a2 = new A('a2');
let b1 = new B('a1', 30);

let diff = _.differenceBy([a1, a2], [b1], 'name');
// result: [{name: a2}]
```

Now, the type definition prevents me from doing this because class A and B are not related. It doesn't appear to be a restriction in lodash code itself. Should the type definition be this strict?

**Comment by aj-r** [comment]
This works for me in typescript 2.3, 2.4, and 2.5:

```javascript
class A {
    name: string;
    constructor(myName: string) {
        this.name = myName;
    }
}

class B {
    name: string;
    age: number;
    constructor(myName: string, age: number) {
        this.name = myName;
        this.age = age;
    }
}

let a1 = new A('a1');
let a2 = new A('a2');
let b1 = new B('a1', 30);

// $ExpectType A[]
_.differenceBy([a1, a2], [b1], 'name');
```

I also tried with private members, but it still worked. Can you provide more details?

Also, pro tip: if you're assigning constructor parameters to member variables, there's a shorthand for that:

```javascript
class A {
    constructor(public myName: string, public age: number) {}
}
```

**Comment by legatek** [comment]
Ah, whoops, I'm running into an issue where Class A is not a supertype. I'm diff'ing against a known property in each class, but the classes themselves aren't sub/supertypes of each other.

```
class A {
    constructor(public myName: string, public company: string) {}
}
class B {
    constructor(public myName: string, public age: number) {}
}

_.differenceBy([a1, a2], [b1], 'name');
// I get: Type argument candidate 'A' is not a valid type argument because it is not a supertype of candidate 'B'.
```
I could certainly write code to do the same thing without _.differenceBy. I'm interested in understanding if I've been abusing this function call or if the type definition is more restrictive than it should be.

**Comment by aj-r** [comment]
Ah I see. Yes that looks like a reasonable way to use differenceBy. I'm not
sure how to support that, though - this worked in old versions, right?

**Comment by legatek** [comment]
Yep, I noticed breakage in updating from @types/lodash@4.14.77 -> 4.14.78

**Comment by aj-r** [comment]
It looks like in 4.14.77, your code would have used this overload:

```
differenceBy<T>(
    array: List<T> | null | undefined,
    ...values: any[]
): T[];
```

That's not great because the type checking is a little too loose. I think the proper way to fix this is to change:

```
differenceBy<T1, T2>(
    array: List<T1> | null | undefined,
    values?: List<T2>,
    iteratee?: ValueIteratee<T1 | T2>
): T1[];
```

to:

```
differenceBy<T1, T2>(
    array: List<T1> | null | undefined,
    values?: List<T2>,
    iteratee?: ValueIteratee<T1 | T2>
): T1[];
```

... and the same for all the other overloads.

In the meantime, you can make your code work by pinning to 4.14.77, or by explicitly passing the type parameter:

`_.differenceBy<A | B>([a1, a2], [b1], 'name');`

**Comment by aj-r** [comment]
I'm working on a PR for this

**Comment by legatek** [comment]
Thanks AJ! I'll pull latest this week; just finished up a prod push and haven't had a chance to look this over yet.

**Comment by aj-r** [comment]
No problem. My fix isn't merged quite yet so pulling won't do you any good anyway :)
