### ISSUE TITLE
[@types/react] improving the literal types in CSSProperties

### ISSUE THREAD

**Issue by pelotom** [DefinitelyTyped/DefinitelyTyped#20743]
@johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz @richseviora

Many of the fields in `CSSProperties` currently have the placeholder type `CSSWideKeyword | any`. [TypeStyle](https://github.com/typestyle/typestyle) has done a lot of legwork already to fill these out with the correct unions of literals, would it be worth copying some of that work over?

**Comment by appsforartists** [comment]
If you look at the [actual React implementation](https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/dangerousStyleValue.js), it adds `'px'` to `number`s, casts to `string`, and [sets the property on `node.style`](https://github.com/facebook/react/blob/94f44aeba72eacb04443974c2c6c91a050d61b1c/packages/react-dom/src/shared/CSSPropertyOperations.js).

Thus, the correct type is probably:

- a union of possible values, for properties with a finite set (e.g. `alignItems`),
- `CSSWideKeyword | number | string` for properties that accept a single length, and
- `CSSWideKeyword | string` for properties that don't.

**Comment by pelotom** [comment]
@appsforartists It seems like that's approximately what you get if you just tweak [`TypeStyle`'s typings](https://github.com/typestyle/typestyle/blob/master/src/types.ts) by replacing

```ts
export type CSSValue<T> = T | T[];
```

with just

```ts
export type CSSValue<T> = T;
```

**Comment by appsforartists** [comment]
@pelotom I'm not sure I follow.

**Comment by pelotom** [comment]
I'm saying I think we could accomplish what you outlined with some small tweaks to the TypeStyle typings... basically just removing the allowance for arrays, since React only allows strings for plural values.

**Comment by pelotom** [comment]
I opened a rough draft PR to demonstrate what I mean: #22076

If this seems like a reasonable foundation I'm happy to refine it into something mergeable.

**Comment by pelotom** [comment]
Another potential source of improvement would be [Glamorous's typings](https://github.com/paypal/glamorous/blob/master/typings/css-properties.d.ts), which are based on the react typings here.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
