### ISSUE TITLE
[@types/react-beautiful-dnd] Type '(event: KeyboardEvent) => void' is not assignable to type 'EventHandler<KeyboardEvent<HTMLDivElement>>'

### ISSUE THREAD

**Issue by lufte** [DefinitelyTyped/DefinitelyTyped#20759]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @varHarrie 

I get the error from the title when trying to use this type definition. Is it possible that this
```
export interface DragHandleProps {
    onMouseDown(event: MouseEvent): void;
    onKeyDown(event: KeyboardEvent): void;
    onClick(event: MouseEvent): void;
...
```
needs to be changed to something like this?
```
export interface DragHandleProps {
    onMouseDown(event: React.MouseEvent<HTMLElement>): void;
    onKeyDown(event: React.KeyboardEvent<HTMLElement>): void;
    onClick(event: React.MouseEvent<HTMLElement>): void;
...
```

**Comment by varHarrie** [comment]
Sorry for my late reply, see #20864.

**Comment by bradleyayers** [comment]
Whoops, I didn't even know this issue existed!

**Comment by lufte** [comment]
Awesome, we can close this once that PR is merged.

**Comment by robertsonsamuel** [comment]
Hey looks like #20864 was merged. I just ran into this issue. Can we close this issue ? Just wanted to clean up issues if possible.
