### ISSUE TITLE
[@types/fabric] Error in module structure

### ISSUE THREAD

**Issue by kputh** [DefinitelyTyped/DefinitelyTyped#20766]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/fabric` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @oklemencic, @joewashear007, @mrand01

If you do not mention the authors the issue will be ignored.

## Description
When trying to initialize the canvas, I get this runtime error: _TypeError: fabric.Canvas is not a constructor_.

The cause seems to be the module structure of the JavaScript source: the correct path/signature is `fabric.fabric.Canvas`, not `fabric.Canvas`.

#### Versions
types/fabric 1.5.26
fabric 1.7.19

**Comment by kputh** [comment]
This issue may be related to #16948.

**Comment by andy-ms** [comment]
The double namespace is a bit suspicious -- what are you using to load the module? Are you using a global variable or an import of some kind?

**Comment by stewartmatheson** [comment]
@andy-ms for me it's happing with an ```import``` . Do type types have to mirror the fabric export which is

```js
module.exports.fabric = fabric;
```

where the right hand side is the global fabric object. I believe the export is setup in this way because of UMD. How do other modules get around this issue with imports and their types?

**Comment by kputh** [comment]
Is use `import * as fabric from 'fabric';`
