### ISSUE TITLE
@types/ws isAlive missing?

### ISSUE THREAD

**Issue by nihiluis** [DefinitelyTyped/DefinitelyTyped#20780]
it seems isAlive property is missing from WebSocket type. see this: https://github.com/websockets/ws#how-to-detect-and-close-broken-connections

**Comment by danthegoodman** [comment]
The `isAlive` property is being dynamically added to the ws instance in the listed example. That property isn't provided by the library.

**Comment by Spongman** [comment]
how does one add this property to the WebSocket declaration?

I have tried all sorts of things to get this to work.

```typescript
import express from 'express';
import expressWS from 'express-ws';
import WebSocket from 'ws';


declare global {
  class WebSocket {
    isAlive: boolean;
  }
}
```

doesn't work. how is this supposed to work?

**Comment by danthegoodman** [comment]
@Spongman Instead of declaring it globally, try this:

```
declare module "ws" {
  interface WebSocket {
    isAlive: boolean;
  }
}
```

You can read more about it here: https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation

**Comment by DISKONEKTeD** [comment]
All you have to do is declare this in your file:

```
interface ExtWebSocket extends WebSocket {
    isAlive: boolean;
}
```

then wherever you're defining that, for example:

```
setInterval(() => {
    wss.clients.forEach((ws: WebSocket) => {
        const extWs = ws as ExtWebSocket;

        if (!extWs.isAlive) return ws.terminate();

        extWs.isAlive = false;
        ws.ping(null, undefined);
    });
}, 10000);
```

**Comment by udhayakumarcp** [comment]
Is there nay native type added for this issue?
