### ISSUE TITLE
Typings for Microsoft Dynamics Execution Context

### ISSUE THREAD

**Issue by thutch10** [DefinitelyTyped/DefinitelyTyped#20879]
I haven't been able to find any typings for the [Execution Context](https://msdn.microsoft.com/en-us/library/gg328130.aspx) when working with Dynamics CRM forms.  Does something like this exist?  If not, can it be added?  I have tagged you because you are on the Xrm typings which are the closest related typings so I am guessing you might have an idea on this question.

@6ix4our @daryllabar @markusmauch @clownwilleatme

**Comment by daryllabar** [comment]
Like this [one](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3543dcb85eea51813c1fc611245a81fe6e500f7b/types/xrm/index.d.ts#L1072)?

**Comment by thutch10** [comment]
@daryllabar That seems like it might be what I am looking for.  We currently have the below code, but I'm thinking maybe the `ExecutionContext` should really be `EventContext`

```
onSave(execObj: ExecutionContext) {
  // Save code here
}
```

**Comment by daryllabar** [comment]
Well there is the SaveEventContext that would be what the onSave event would be applicable here...  

But now I'm starting to be a little confused between the difference of between the ExecutionContext and the EventContext.

What situation are you dealing with here that you're having an issue?

**Comment by thutch10** [comment]
I'm refactoring some Typescript code that we use for custom validations/actions on our forms.  When I try to compile the code into Javascript, I get an error that `ExecutionContext` can't be found.  The documentation for ExecutionContext is [here](https://msdn.microsoft.com/en-us/library/gg328130.aspx).  This code still compiles and runs correctly despite the error, but I would like to figure out why I am getting this error on what seems to be valid code as far as I can tell.

![image](https://user-images.githubusercontent.com/4108068/31947978-9bb37b90-b8a3-11e7-9386-dfd01f7ee0bf.png)

**Comment by clownwilleatme** [comment]
The execution context is defined in the Xrm.Page namespace, and is called "event context". Does this code work?

onSave(execObj: Xrm.Page.SaveEventContext) {
  // Save code here
}

For non-save events this should be Xrm.Page.EventContext

Also, make sure you have checked the option to pass through the execution context to the method in the CRM form customisation UI.

**Comment by daryllabar** [comment]
The TS will never be a 1:1 for the documentation.  @clownwilleatme's code should solve your issue.  Let us know if it doesn't.
