### ISSUE TITLE
Lodash chaining has incorrect return types when using castArray

### ISSUE THREAD

**Issue by alan-agius4** [DefinitelyTyped/DefinitelyTyped#20870]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/lodash` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aj-r 

If you do not mention the authors the issue will be ignored.

```ts
import * as _ from "lodash";
let x: string | string[];

const y = _.chain(x)
	.castArray()
	.value()
```

type of `y` is `(string | string[])[]` when it should be `string[]`

**Comment by aj-r** [comment]
@alan-agius4 What version of typescript and `@types/lodash` are you using? I'm using TS 2.5.3 and `@types/lodash` 4.14.78, and your code works for me - `y` is `string[]`.

**Comment by alan-agius4** [comment]
seems ok with ` 4.14.78` thanks
