### ISSUE TITLE
mongoose should better support lean

### ISSUE THREAD

**Issue by floriantraber** [DefinitelyTyped/DefinitelyTyped#20874]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/mongoose` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @simonxca @horiuchi  @sindrenm 

The lean method should not return an _Object_. The current behavior breaks types and forces the user to do type checking. See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L1582

Idee: Maybe enable the Model to specify a interface which is then sub-sequentially returned in the Query in the lean method?

**Comment by simonxca** [comment]
@floriantraber 
😳 sorry I missed this. We can probably add something like `lean<U>(bool?: boolean): Query<U>;`
and use it like this:
```js
...
.lean<MyType>().exec(function(err, result) {
  // typeof result is MyType
});
```

Is this what you're looking for? Could I get an example of some code that breaks for you?

**Comment by floriantraber** [comment]
I like the idea and it's better than currently. 

The following is an example, where one can call the  `save` method on the user and not on the leanUser., but both have a property name. This should be reflected in the types. 
It think it would be even better, if it was not necessary to specify the type every time. It's unnecessary and error prone (Losing of the information if the results is an object or array). 
```
export type User = { _id: any; name: string; };

export type UserDocument = mongoose.Document & User;

export const userSchema = new mongoose.Schema({ name: String });

export const userModel = mongoose.model<UserDocument>('User', userSchema);

const user: UserDocument = await userModel.findOne();

// currently 
const leanUser: User = await userModel.findOne().lean() as User;

// proposed
const leanUser: User = await userModel.findOne().lean<User>();

// ideal
const leanUser: User = await userModel.findOne().lean();

```

**Comment by simonxca** [comment]
These are great examples, I'll look into it.

**Comment by simonxca** [comment]
@floriantraber Unfortunately, I don't think we have any way of extracting the `User` interface out of `UserDocument`.

However, if we do this:
```js
lean(bool?: boolean): Query<any>;
```

Then this will work:
```js
const leanUser: User = await userModel.findOne().lean();
```

**Comment by floriantraber** [comment]
I would prefer the _generic_ version from your first post to the _any_ version as it's giving more explicit type safety.  

with any: 
```JavaScript
const leanUser: User = await userModel.findOne().lean();
const leanUser = await userModel.findOne().lean(); // leanUser is any
```
with generic:
```JavaScript
const leanUser: User = await userModel.findOne().lean<User>();
const leanUser: User = await userModel.findOne().lean(); // leanUser is {}, ts error
```

Would it be possible to add the User interface as an additional, optional type parameter at model creation? (at `mongoose.model<T>()`) This would supply us with the needed type information when calling the `lean` method.

**Comment by simonxca** [comment]
We can't add optional type parameters at model creation because there is already a type parameter with the type `T extends Document`.

The best we can do here is:
```js
const leanUser = await userModel.findOne().lean<User>();
// or
const leanUser: User = await userModel.findOne().lean();
```

**Comment by simonxca** [comment]
@floriantraber See here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21504#discussion_r152714680

Unfortunately I'm told that we should prefer using:
`lean() as User` instead of `lean<User>(): User`
because the type assertion is more explicit.

See the `getMeAT<T>(): T` bullet point in this section of the DefinitelyTyped readme:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/715a90d/README.md#common-mistakes

**Comment by mharj** [comment]
quickly tested with bit hacking, but I didn't manage to get it actually working
```typescript
interface ModelWithPojo<P extends object, QueryHelpers = {}, T = P & Document> extends NodeJS.EventEmitter, ModelProperties {
```
... this fails as "type 'T' does not satisfy the constraint 'Document'" on multiple functions.
It definitely would be nice to be more strict with types like for new () and .lean()

**Comment by bodolawale** [comment]
I tried 
`const leanUser = await userModel.findOne().lean<User>();`
and I get an error 
**Expected 0 type arguments, but got 1.**
When I remove `User` from lean, I do not get document fields
