### ISSUE TITLE
JQuery .map wrong return type

### ISSUE THREAD

**Issue by elicym** [DefinitelyTyped/DefinitelyTyped#20890]
The .map function on the JQuery interface returns JQuery<HtmlElement>, where really it should return JQuery<T>, where T is the return type of the inner function.

For example:
`$('.abc').map(function(){ return this.id; }).get()`
should return an array of `string`s, not `HtmlElement`s.

**Comment by leonard-thieu** [comment]
Will be fixed by #20953. Thanks for reporting this.
