### ISSUE TITLE
types/bezier-easing suggests bezier-easing 'is not a module'

### ISSUE THREAD

**Issue by emyarod** [DefinitelyTyped/DefinitelyTyped#20930]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ptlis 

If you do not mention the authors the issue will be ignored.

Using `"@types/bezier-easing": "0.0.30"` with `"bezier-easing": "^2.0.3",` indicates that "`@types/bezier-easing/index.d.ts` is not a module". I can get around this error by adding `declare module 'bezier-easing';` to the end of the file, but I am unsure as to whether or not this is a proper solution to the problem

**Comment by andy-ms** [comment]
PRs accepted. I suspect this would be fixed by adding the following:
```ts
export = BezierEasing;
export as namespace BezierEasing;
```

**Comment by emyarod** [comment]
I might be missing some important pieces. After adding the two lines you suggested, running `npm run lint bezier-easing` throws more errors. Is there a problem with using `declare module 'bezier-easing'`? As a TypeScript novice I am still figuring out the language

**Comment by andy-ms** [comment]
`declare module 'bezier-easing';` will declare a module that exports every possible name with a value of type `any` -- not what you want!
As for lint errors, the package currently isn't linted at all -- I've done this in #20952 along with the `export =` fix.
