### ISSUE TITLE
@types/react does not allow returning ReactPortal from render

### ISSUE THREAD

**Issue by Jessidhia** [DefinitelyTyped/DefinitelyTyped#20942]
A `ReactPortal` is not accepted as a valid `ReactElement` as it does not have a `type` or `props` key. However, React itself does accept `ReactPortals` as a valid return value.

This might be a bit tricky to fix as simply changing `StatelessComponent`/`ComponentClass` to return `ReactElement|ReactPortal` will probably break many things.

This problem will also probably repeat itself with future `React.Fragment`.

```tsx
interface PortalProps {
  children: React.ReactNode
  target: Element
}
// type error: ReactPortal not assignable to ReactElement
const Portal: React.SFC<PortalProps> = ({ children, target }: PortalProps) => ReactDOM.createPortal(children, target)
const Portal2 = ({ children, target }: PortalProps) => ReactDOM.createPortal(children, target)
// type error: Portal2 is not a constructor for JSX elements
const test = <Portal2 target={document.body}>test</Portal2>
```

**Comment by charlieman** [comment]
I wonder if this is related, I was just following the tutorial here: https://www.typescriptlang.org/docs/handbook/react-&-webpack.html

And webpack gave me the error "Module has no exported member 'ReactPortal'". Do I need to use a specific version of react or @ types/react?

```
$ webpack

[at-loader] Using typescript@2.6.1 from typescript and "tsconfig.json" from /home/user/ts-react-example/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors
Hash: 4e0027c7639f8f63e2fc
Version: webpack 3.8.1
Time: 2009ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  3.38 kB       0  [emitted]  main
bundle.js.map  3.76 kB       0  [emitted]  main
   [1] ./src/index.tsx 332 bytes {0} [built]
    + 3 hidden modules

ERROR in [at-loader] ./node_modules/@types/react-dom/index.d.ts:16:43 
    TS2305: Module '"/home/user/ts-react-example/node_modules/@types/react/index"' has no exported member 'ReactPortal'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by charlieman** [comment]
I got it working!

First I noticed the version of `@types/react` didn't match that of react so I changed it to the same as react (16.0.0).
Then looking at the yarn.lock file, I saw there was two versions of `@types/react` installed, 15.6.6 and 16.0.0.  I ran the command `yarn check` which gave me this message: `warning "@types/react-dom#@types/react@*" could be deduped from "16.0.20" to "@types/react@16.0.20"`

So I ran `yarn install --flat`which gave me a version to choose from for `@types/react` (and several other packages which now give me warnings for incompatible versions). After that running `webpack` finally worked.

**Comment by kajmagnus** [comment]
Thanks @charlieman, adding `resolutions: ...` solved the same problem for me too (I added v. 16.0.25). I have no idea why Yarn insisted on keeping the 15.x version — nothing seems to depend on that old version.

**Comment by rosskevin** [comment]
I am seeing this with
```
    "@types/react": "^16.0.28",
    "@types/react-dom": "^16.0.3",
```

So I don't have anything down in 15.x. and have no idea why this is happening.

**Comment by rosskevin** [comment]
Ok, so I seem to have figured _something_ out.  When I used `ncu` it updated existing `^16.0.27` to `^16.0.28`, and I yarn installed.  This somehow put the project in a bad state.

As mentioned above, `rm -rf node_modules && yarn` didn't solve the problem, but rm -rf node_modules yarn.lock && yarn` **did** solve the problem.  Evidently forcing yarn to do a from-scratch dependency resolution had an an effect on the results.

**Comment by Cryrivers** [comment]
just found out the topic was totally off. @Kovensky i met the same problem, i think the only solution is to update the type definition file. making `ReactPortal` extend from `ReactElement` or something like that.

**Comment by Cryrivers** [comment]
```ts
interface ReactPortal extends ReactElement<any> {
    key: Key | null;
    children: ReactNode;
}
```
this works for me.

**Comment by ccorcos** [comment]
I'm still unable to fix this. The problem appears to be that @types/react-dom installs an older version of @types/react as you can see from the error trace:

```
node_modules/@types/react-dom/node_modules/@types/react/index.d.ts(3566,13): error TS2717: Subsequent property declarations must have the same type.  Property 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.
```

Here's what I've got going in my package.json:

```
	"devDependencies": {
		"@types/react": "16.0.40",
		"@types/react-dom": "16.0.3",
	},
	"resolutions": {
		"@types/react": "16.0.34",
		"@types/react-dom": "16.0.3"
	},
```

**Comment by ccorcos** [comment]
Lol, my resolution differed from the dependency version.

Also note for others, you can pin version in subpackages (using resolutions)[https://yarnpkg.com/lang/en/docs/selective-version-resolutions/]

```
"@types/react-dom/@types/react": "16.0.40"
```

**Comment by lifeiscontent** [comment]
I'm trying to use a React.SFC and using a react portal inside complains saying it doesn't have a render function. Anyone know of a fix here?

**Comment by netzwerg** [comment]
@lifeiscontent I ran into the same problem. Don't know how to fix it, but I managed to work around it by not using JSX.

So instead of this:
```
<MyComponentWhichUsesAPortal xy={xy}/>
```
you can use your component like this:
```
MyComponentWhichUsesAPortal({xy})
```

**Comment by jariz** [comment]
@lifeiscontent I 'fixed' it by wrapping a <Fragment> around the ReactDOM.createPortal call.
Still really weird SFC does not accept it. (using the latest versions of all typings)

**Comment by SeanRoberts** [comment]
This seems to be fixed with @types/react-dom@16.8.0

**Comment by joshuaellis** [comment]
At `react-three-fiber` we've implemented a `createPortal` function which is identical to `ReactDOM.createPortal` but it current throws the following error: 
```shell
Its return type '{ $$typeof: number | symbol; key: string | null; children: any; containerInfo: any; implementation: any; }' is not a valid JSX element.
```

I've noticed in @types/react theres an exported type ReactPortal but that type doesn't seem to really work either, maybe `React.ReactPortal` isn't correctly typed by somehow passes? Here's the implementation of react-three-fiber.createPortal:
```ts
function createPortal(children: React.ReactNode, containerInfo: any, implementation?: any, key: any = null) {
  if (!containerInfo.__objects) containerInfo.__objects = []
  return {
    $$typeof: REACT_PORTAL_TYPE,
    key: key == null ? null : '' + key,
    children,
    containerInfo,
    implementation,
  }
}
```

Wrapping the call in a fragment does work, but it's not ideal because we have to ask the user to impliment that...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
