### ISSUE TITLE
Knockout Nuget package seems to be out of date

### ISSUE THREAD

**Issue by jfrank14** [DefinitelyTyped/DefinitelyTyped#20950]
I upgraded from Typescript 2.3 to 2.5.3 and got some new compilation errors in my [knockout typings](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/knockout). Looking at the files that are in this repo, it seems clear that the "latest" version as installed by Nuget is older than the repo. Where is this Nuget package maintained and can it be updated with the latest files?

**Comment by andy-ms** [comment]
Nuget publishing was turned off a while ago. It's recommended to use npm (or yarn) instead.

**Comment by jfrank14** [comment]
Whoa, that would explain it. I had no idea. But why turn off Nuget support? What's the harm in maintaining support for those of us that use Nuget in Visual Studio, even if there are newer, better ways?

**Comment by andy-ms** [comment]
One problem is that module resolution will only find packages installed in `node_modules`, which should be managed by NPM. We also changed the repository structure since NuGet was turned off.

**Comment by telmo-rodrigues** [comment]
Yeah, NuGet support would be lovely, i had this problem and yes the NuGet package was really old, would you consider re-enabling NuGet anytime soon? 

Cheers  for the great work !

**Comment by andy-ms** [comment]
I didn't add the nuget pacakges in the first place, and they're unlikely to be turned back on again due to not working well with module resolution, which expects an NPM package structure.

**Comment by vi-jasonm** [comment]
Its an unfortunate change because it means existing projects are broken if the latest version of Knockout is used.  Existing projects don't always have the luxury of converting from the use of NuGet to NPM or whatever the flavor of the day is for package management.

**Comment by ltlombardi** [comment]
If adding npm is not desirable, I suggest manually adding the library to your project, with the appropriate typing. This is what I did in my project.

**Comment by ltlombardi** [comment]
@jfrank14 could you close this issue? Knockout has already been remove from Nuget.

**Comment by jfrank14** [comment]
Sure, although I'm not sure I follow why NuGet can't be supported.
