### ISSUE TITLE
Add perf_hooks module to @types/node

### ISSUE THREAD

**Issue by spencerhakim** [DefinitelyTyped/DefinitelyTyped#20981]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] Authors: @parambirs, @tellnes, @WilcoBakker, @octo-sniffle, @smac89, @Flarna, @mwiktorczyk, @wwwy3y3, @DeividasBakanas, @kjin, @alvis

-----

Node.js 8.5.0 added the [`perf_hooks`](https://nodejs.org/api/perf_hooks.html) module, which implements a subset of the standard performance timing APIs included in TypeScript's ES2017 definitions along with some Node-specific additions.

If anyone needs something simple to hold them over:

```ts
declare module "perf_hooks" {
    export const performance: Performance;
}
```

**Comment by colinskow** [comment]
Put the above declare in a file named `index.d.ts` in the root of the project. (I was trying to put it above the `import 'perf_hooks'` statement and it doesn't work there.)

**Comment by Flarna** [comment]
see #22037
