### ISSUE TITLE
@types/gulp-utils fails to compile

### ISSUE THREAD

**Issue by andrefbsantos** [DefinitelyTyped/DefinitelyTyped#21004]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/gulp-utils` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @emilio-martinez 

Version 3.0.32 of the package @types/gulp-utils fails to compile:

> TSError: ⨯ Unable to compile TypeScript
tools/utils/seed/clean.ts (24,32): Property 'bgRed' does not exist on type 'typeof "/home/vagrant/angular-seed-advanced/node_modules/@types/gulp-util/node_modules/chalk/type...'. (2339)
tools/utils/seed/clean.ts (31,47): Property 'yellow' does not exist on type 'typeof "/home/vagrant/angular-seed-advanced/node_modules/@types/gulp-util/node_modules/chalk/type...'. (2339)
tools/utils/seed/clean.ts (39,40): Property 'red' does not exist on type 'typeof "/home/vagrant/angular-seed-advanced/node_modules/@types/gulp-util/node_modules/chalk/type...'. (2339)
    at getOutput (/home/vagrant/angular-seed-advanced/node_modules/ts-node/src/index.ts:307:15)
    at /home/vagrant/angular-seed-advanced/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/home/vagrant/angular-seed-advanced/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/home/vagrant/angular-seed-advanced/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/vagrant/angular-seed-advanced/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

It seems that a chalk dependency was added to @types/gulp-util in 302970129c1698a5072e1fc94bf6cd813b554185, diff of the package.json can be seen [here](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/302970129c1698a5072e1fc94bf6cd813b554185#diff-6b002a24f1a4841c02c7c8157d7bfcca).

For now i have downgraded to version 3.0.31, which has no issues.

**Comment by joelfsreis** [comment]
+1

**Comment by emilio-martinez** [comment]
As of [`chalk@2.2.0`](https://github.com/chalk/chalk/releases/tag/v2.2.0) the project is providing its own type definitions; therefore listing `chalk` as a dependency is accurate; the definitions coming from this repo are going to be removed (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20789). The problem, for a lack of a better term, is that the "official" definitions differ from the definitions in this repo, so the types need to be adjusted; however, I don't maintain the `gulp-util` type definitions nor am I the author. That said, if I get a chance before the end of the week, I'll adjust.

For more background on the change at `chalk`'s end, see https://github.com/chalk/chalk/issues/215#issuecomment-337456439.
