### ISSUE TITLE
Express Request broken

### ISSUE THREAD

**Issue by simondel** [DefinitelyTyped/DefinitelyTyped#21022]
The current express typings are broken since the [commit two days ago](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f8d0b72ff4dc90d86528ec85b1d43dc5711f2e03).

This causes the following issues:
* Our build fails with ['../../node_modules/@types/express/index.d.ts(84,15): error TS2315: Type 'Request' is not generic.'](https://travis-ci.org/stryker-mutator/stryker/jobs/293006741#L136) in a package that doesn't use anything regarding Express (we install the types at a higher level due to a mono repo)
* Building a test app doesn't work (reproduction: create a new nodejs app. Install typescript and the express typings and run `tsc .`): 
```
node_modules/@types/express-serve-static-core/index.d.ts(178,10): error TS1005: ',' expected.
node_modules/@types/express-serve-static-core/index.d.ts(179,11): error TS1005: ',' expected.
node_modules/@types/express-serve-static-core/index.d.ts(180,12): error TS1005: ',' expected.
node_modules/@types/express-serve-static-core/index.d.ts(181,13): error TS1005: ',' expected.
node_modules/@types/express/index.d.ts(79,28): error TS1005: ',' expected.
node_modules/@types/express/index.d.ts(79,41): error TS1005: ',' expected.
node_modules/@types/express/index.d.ts(79,55): error TS1005: ',' expected.
node_modules/@types/express/index.d.ts(79,70): error TS1005: ',' expected.
```

Tested using `typescript@2.5.3` and `@types/express@4.0.38`

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @19majkel94 @kacepe @alex3165

**Comment by simondel** [comment]
Part of this issue is already being discussed at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20820

**Comment by simondel** [comment]
Pinning my version of `express-serve-static-core` at version `4.0.54` fixed the issue for me.

**Comment by rhyek** [comment]
@simondel you mean @types/express-serve-static-core@4.0.54? If I install that in my project I get the same error with additional output:
```
node_modules/@types/express/index.d.ts(84,15): error TS2315: Type 'Request' is not generic.
index.ts(34,36): error TS2345: Argument of type 'Router' is not assignable to parameter of type 'Router | Express'.
  Type 'Router' is not assignable to type 'Express'.
    Property 'request' is missing in type 'Router'.
index.ts(40,29): error TS7006: Parameter 'req' implicitly has an 'any' type.
index.ts(44,30): error TS7006: Parameter 'req' implicitly has an 'any' type.
```

**Comment by simondel** [comment]
You could try to upgrade to the latest types, perhaps that fixes your issue.

**Comment by rhyek** [comment]
@simondel it is a new project. The  package versions are the latest.

**Comment by rhyek** [comment]
@simondel for some reason the type definitions for `express` were old even though I installed everything through `yarn` from 0 for this new project yesterday. Odd. I upgraded that and everything is fine now.

**Comment by codejamninja** [comment]
Thanks @simondel
