### ISSUE TITLE
Tools to automate definition creation

### ISSUE THREAD

**Issue by Bartvds** [DefinitelyTyped/DefinitelyTyped#2103]
Creating the definitions can be quite time consuming, so we should start looking for some tools that can help with this and document it in the guides.

Let's start by listing the known tools, then later we can add a page to the site.

**Comment by englercj** [comment]
I'm working on a jsdoc3 template that does just this:

https://github.com/englercj/jsdoc2tsd

PR's welcome!

**Comment by jumpinjackie** [comment]
Here's one from me: https://github.com/jumpinjackie/jsdoc-typescript-plugin

**Comment by nkappler** [comment]
very late joining this discussion, but I wanted to let you know that I've wrote definitions for tern...

**Comment by jakebailey** [comment]
Doing some issue cleanup; I believe that this is fairly well handled by dts-gen (which is maintained along side the DT tooling).
