### ISSUE TITLE
@types/stripe v4.7.0 

### ISSUE THREAD

**Issue by MHeironimus** [DefinitelyTyped/DefinitelyTyped#21033]
- [X] I tried using the `@types/stripe` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wjohnsto @codeanimal @sampsonjoliver @LinusU 

When I use v4.7.0 of the `@types/stripe` package, I see the following error:

~~~
error TS2305: Module '".../node_modules/@types/stripe/index"' has no exported member 'Stripe'.
~~~

If I change the `index.d.ts` file as follows:

- line 11: changed `declare` to `export`
- line 77: removed export = Stripe
- line 79: changed `declare` to `export`

it seems to resolve the issue. I am not sure that is the correct fix, however, because I also had to change the call that initializes Stripe (it went from a function call to a class instantiation / i.e. I had to add the `new` keyword).

I do not see this error if I use `@types/stripe@3.0.0`.

**Comment by LinusU** [comment]
> (it went from a function call to a class instantiation / i.e. I had to add the new keyword)

This is probably to be expected, as fas as I know there is no way to annotate that a class can be called as function as well. If there is, I'd be happy to add it...

> `error TS2305: Module '".../node_modules/@types/stripe/index"' has no exported member 'Stripe'.`

This is strange. I'm using the same version of the types, but maybe not the same version of TypeScript? The only thing I can think about from the top of my head...

I'm using TypeScript `2.5.2`, which version are you using?

**Comment by MHeironimus** [comment]
@LinusU I am running TypeScript 2.5.3

~~~
C:\TFS\PaymentService>tsc --version
Version 2.5.3
~~~

**Comment by MHeironimus** [comment]
Update: I am still seeing this issue in @types/stripe v5.0.0

~~~
.../stripeAdapter.ts(3,10): error TS2305: Module '".../node_modules/@types/stripe/index"' has no exported member 'Stripe'.
~~~

**Comment by LinusU** [comment]
Hmm, just realised, how are you importing the package? `import { Stripe } from 'stripe'`?

**Comment by MHeironimus** [comment]
Yes. The following is how I am importing the package:

~~~
import { Stripe } from "stripe";
~~~

The following is how I am using it:

~~~
public stripe: any = Stripe(process.env.STRIPE_TOKEN as string);
~~~

I am using Visual Studio Code as my IDE. It also reports the issue:

![visual studio code screenshot](https://user-images.githubusercontent.com/5286686/34567143-aeb3dc42-f126-11e7-9f2f-d850742486dd.png)

**Comment by LinusU** [comment]
The source code for stripe exports it as `module.exports = Stripe;`, so technically the correct way would be do to `import Stripe = require('stripe')`.

If you are using the [`--allowSyntheticDefaultImports`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) compiler option you should be able to do `import Stripe from 'stripe'`.

**Comment by MHeironimus** [comment]
I updated my `tsconfig.json` file to include the `allowSyntheticDefaultImports` option (see below), but I am still getting the same error.

~~~
...
    "strictNullChecks": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "allowSyntheticDefaultImports": true
},
...
~~~

Error:

~~~
> tsc

src/adapters/stripeAdapter/stripeAdapter.ts(3,10): error TS2305: Module '"C:/TFS/PaymentService/node_modules/@types/stripe/index"' has no exported member 'Stripe'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! payment-service@1.1801.228 build-ts: `tsc`
npm ERR! Exit status 2
~~~

Do you have any other ideas on things I should try?

Thanks,
Matt

**Comment by LinusU** [comment]
You should also remove the brackets (`{` `}`) from around `Stripe`:

```typescript
import Stripe from 'stripe'
```

**Comment by MHeironimus** [comment]
Got this to work doing the following:

~~~
import * as Stripe from "stripe";

...

  public stripe: any = new Stripe(process.env.STRIPE_TOKEN as string);
~~~

Thank you for your help with this issue,
Matt
