### ISSUE TITLE
Leaflet. FeatureGroup.setStyle should return PathOptions

### ISSUE THREAD

**Issue by kutensky** [DefinitelyTyped/DefinitelyTyped#21069]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5761cfc6f2bb9de0af9085e4f119d0ef590c500e/types/leaflet/index.d.ts#L744
It should be PathOptions. According to http://leafletjs.com/reference-1.2.0.html#featuregroup , setStyle method accept PathOptions object as an argument. But in d.ts it says it accept function which returns PathOptions.

**Comment by atd-schubert** [comment]
The title is wrong. It should not return `PathOption`, it should have `PathOption` as argument...
