### ISSUE TITLE
Package @types/lodash.flowright is breaking typescript compiler

### ISSUE THREAD

**Issue by lednhatkhanh** [DefinitelyTyped/DefinitelyTyped#21085]
- [x] I tried using the `@types/lodash.flowright` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- Authors: @bczengel 

The package is breaking tsc with the error `Module .../@types/lodash.flowright/index resolves to a non-module entity and cannot be imported using this construct.`

**Comment by pheromonez** [comment]
Looks like `require`ing the package will work:

``` typescript
import flowright = require('lodash.flowright');
```

**Comment by lednhatkhanh** [comment]
@pheromonez Tks but I have no control over how the package is being imported, it is required by apollo-client 2.0...

**Comment by amborle** [comment]
I got the same error trying to upgrade to apollo-client 2.0...

**Comment by myabc** [comment]
This is also applicable to other lodash packages, including lodash.flatmap:

```src/schema-location.ts(1,26): error TS2497: Module '"/Users/myabc/work/mymaths-content-format/node_modules/@types/lodash.flatmap/index"' resolves to a non-module entity and cannot be imported using this construct.```

**Comment by domachine** [comment]
@pheromonez This sadly doesn't work when targeting ECMAScript modules.

**Comment by radicand** [comment]
I'm working around this for now by removing `@types/lodash.flowright` from my dependencies and manually declaring `declare module 'lodash.flowright';`

**Comment by aj-r** [comment]
I did some quick testing, and it looks like we can add a pointless namespace to convince typescript that this is allowed:

```ts
import { flowRight } from "lodash";
declare namespace _ {
    type FlowRight = typeof flowRight;
}
declare const flowRight1: _.FlowRight;
export = flowRight1;
```

This works with both import syntaxes: `import flowRight = require('lodash.flowRight');` and `import * as flowRight from 'lodash.flowRight';`

**Comment by gdelmas** [comment]
@aj-r i can't get this to work for this import syntax: `import * as flowRight from 'lodash.flowright';`

is this still working for you? which typescript version are you on?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
