### ISSUE TITLE
[Request] promise-mysql

### ISSUE THREAD

**Issue by RetroCraft** [DefinitelyTyped/DefinitelyTyped#21100]
[Github link](https://github.com/lukeb-uk/node-promise-mysql)

Should be very similar to the normal `mysql` package which already has a `@types/mysql` but just with promises.

**Comment by move-zig** [comment]
I made an attempt (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21290), but ran into a problem because I added mysql as a dependency. Does anyone know if it's okay to do as the error log suggests? Would that require a separate pull request?

**Comment by move-zig** [comment]
[travis.log](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1447878/travis.log)

**Comment by move-zig** [comment]
I think this can be closed. The project includes its own type declaration now.
