### ISSUE TITLE
@types/webdriverio custom commands to browser interface

### ISSUE THREAD

**Issue by iambalaam** [DefinitelyTyped/DefinitelyTyped#21118]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nmalaguti  @timbru31 @fsmedberg-tc 

Hi,
I'm using webdriverio and want to add my own custom commands to the browser.  I can use the `browser.addCommand('name', () => {...})` method but have no 'safe' way of calling this in typescript.  
  
I would like to create a setup file initialising all my custom commands, adding them to the browser and redeclaring the browser object.

I can imagine something like
``` javascript
interface allCustomCommands {
    ...
}

declare const browser: WebdriverIO.Client<void> & allCustomCommands;
```

However I the `Client` isn't exported.  Is there any other way around this?

Thanks

**Comment by uniqueiniquity** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32490
