### ISSUE TITLE
@types/node Process is missing seteuid, geteuid, setegid, getegid, setgroups, getgroups

### ISSUE THREAD

**Issue by jez9999** [DefinitelyTyped/DefinitelyTyped#21114]
For some reason `@types/node` is missing `seteuid`, `geteuid`, `setegid`, `getegid`, `setgroups`, and `getgroups` for its `Process` typings.  Could they be added?

**Comment by jez9999** [comment]
@andy-ms @jeffkenney @jinwoo @OliverJAsh @DeividasBakanas @RobDesideri @mwiktorczyk @JoshGlazebrook @Flarna Any ideas on why these are missing?

**Comment by Flarna** [comment]
Best guess here is that initial NodeJs typings were created before they were added to the NodeJs API (Most of these APIs were added in v2.0.0, `setgroups` and `getgroups` in 0.9.4).
Feel free to create a PR to add them.

**Comment by jez9999** [comment]
Pull request created.

**Comment by jez9999** [comment]
It's been checked in.
