### ISSUE TITLE
@types/storybook__react misses declarations for demo.js

### ISSUE THREAD

**Issue by karak** [DefinitelyTyped/DefinitelyTyped#21136]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @joscha

If you do not mention the authors the issue will be ignored.

The statement `import { Button, Welcome } from '@storybook/react/demo';` causes compile error in "stories/index.js" generated by `getstorybook 3.2.3` .

I avoid this by providing my own file like following now.

```typescript
declare module '@storybook/react/demo' {
  export class Button extends React.Component<React.HTMLProps<Button>> {
  }

  export interface WelcomeProps {
    showApp: React.MouseEventHandler<Welcome>;
  }

  export class Welcome extends React.Component<WelcomeProps> {
  }
}
```

Should we include this fragment in @types/storybook__react to complete?

**Comment by joscha** [comment]
Hey @karak - I am unsure about the value it provides to add these definitions to the definitely typed repository. These types are only used in an example, so once you understood the example, you'd most likely go ahead and write code in TS yourself (that would then not need any of these declarations). WDYT?

**Comment by karak** [comment]
As you say, we can actually face this issue away until `getstorybook` would generate "demo.ts" in the future (isn't it ideal?).

But I cannot neglect the value of launching just after set-up to relieve us, although I also doubt how many users rewrite "stories/index.js" to .tsx neatly.  For the configuration works always make us distressed and uneasy, even the developers who have manually performed them many times as me.

**Comment by karak** [comment]
Close this issue.
