### ISSUE TITLE
@types/express/index.d.ts issue: An interface may only extend a class or another interface

### ISSUE THREAD

**Issue by felipesoares93** [DefinitelyTyped/DefinitelyTyped#21140]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/express` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov 

If you do not mention the authors the issue will be ignored.

Hello! Yesterday we deployed a production version of our application to all of our environments with success. Today, however, we are getting the following errors when we try to build and deploy our application again (the process removes the node_modules directory and installs the dependencies again). No code changes were involved.

```
.../node_modules/@types/express/index.d.ts(35,31): error TS2312: An interface may only extend a class or another interface.
.../node_modules/@types/express/index.d.ts(36,43): error TS2312: An interface may only extend a class or another interface.
.../node_modules/@types/express/index.d.ts(46,43): error TS2312: An interface may only extend a class or another interface.
.../node_modules/@types/express/index.d.ts(49,28): error TS2312: An interface may only extend a class or another interface.
```

We use the following @types packages:

```
    "@types/async": "2.0.32",
    "@types/browser-sync": "0.0.34",
    "@types/core-js": "0.9.34",
    "@types/express": "4.0.33",
    "@types/gulp": "3.8.32",
    "@types/gulp-filter": "3.0.29",
    "@types/gulp-load-plugins": "0.0.28",
    "@types/gulp-protractor": "1.0.29",
    "@types/gulp-sass": "0.0.29",
    "@types/gulp-util": "3.0.29",
    "@types/jasmine": "2.5.35",
    "@types/node": "^6.0.45",
    "@types/protractor": "1.5.20",
    "@types/rimraf": "0.0.28",
    "@types/run-sequence": "0.0.28",
    "@types/selenium-webdriver": "2.44.*",
    "@types/systemjs": "0.19.31",
    "@types/yargs": "0.0.34",
    "@types/zone.js": "0.0.27",
    "@types/lodash": "4.14.38"
```

Since we didn’t change anything on our side, we are wondering if anything could have changed that might be causing this issue. After trying to solve the issue and fail, I decided to post it. Also, I noticed that a dependency for the `@types/express` package (`@types/express-serve-static-core`) was published 19 hours ago. Could it be related?

Thanks,

Felipe Carvalho

**Comment by felipesoares93** [comment]
I solved the issue set up the dependency to the last version:

“@types/express”: “4.0.33",
   “@types/express-serve-static-core”: “4.0.49",

**Comment by felipesoares93** [comment]
I "fixed" the problem specifying the dependency to the previous version:

"@types/express-serve-static-core": "4.0.49"

**Comment by CauchyAbel** [comment]
@felipesoares93 I did the same thing to fix this issue but it is definitely really temporary.

**Comment by thotan09** [comment]
[17:38:05] Starting 'copy.tizenSettings'...
[17:38:05] Finished 'copy.tizenSettings' after 78 ms
[17:38:05] Starting 'build.js.staging'...
C:/work/node_modules/@types/express/index.d.ts(35,31): error TS2312: An interface may only extend a class or another interface.
C:/work/node_modules/@types/express/index.d.ts(36,43): error TS2312: An interface may only extend a class or another interface.
C:/work/node_modules/@types/express/index.d.ts(46,43): error TS2312: An interface may only extend a class or another interface.
C:/work/node_modules/@types/express/index.d.ts(49,28): error TS2312: An interface may only extend a class or another interface.
[17:38:13] TypeScript: 4 semantic errors
[17:38:13] TypeScript: emit succeeded (with errors)

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.staging"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dfw-tizen@0.0.1 build.staging: `gulp build.staging --color --env-config staging`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dfw-tizen@0.0.1 build.staging script 'gulp build.staging --color --env-config staging'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dfw-tizen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build.staging --color --env-config staging
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dfw-tizen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dfw-tizen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Naveen kumar Thota\AppData\Roaming\npm-cache\_logs\2017-11-01T21_38_13_151Z-debug.log
C:\work>npm install express@4.0.49
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express@4.0.49"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: express@4.0.49
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.14.0, 0.14.1, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 2.3.11, 2.3.12, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.5.9, 2.5.10, 2.5.11, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.1.0, 3.1.1, 3.1.2, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 1.0.0-beta, 1.0.0-beta2, 1.0.0-rc, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 2.0.0-beta, 2.0.0-beta2, 2.0.0-beta3, 2.0.0-rc, 2.0.0-rc2, 2.0.0-rc3, 3.0.0-alpha1, 3.0.0-alpha2, 3.0.0-alpha3, 3.0.0-alpha4, 3.0.0-alpha5, 3.0.0-beta1, 3.0.0-beta2, 3.0.0-beta3, 3.0.0-beta4, 3.0.0-beta6, 3.0.0-beta7, 3.0.0-rc1, 3.0.0-rc2, 3.0.0-rc3, 3.0.0-rc4, 3.0.0-rc5, 3.3.7, 3.3.8, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 4.0.0-rc1, 4.0.0-rc2, 3.5.0, 4.0.0-rc3, 4.0.0-rc4, 3.5.1, 4.0.0, 3.5.2, 4.1.0, 4.1.1, 3.5.3, 4.1.2, 3.6.0, 4.2.0, 3.7.0, 3.8.0, 4.3.0, 4.3.1, 3.8.1, 4.3.2, 3.9.0, 4.4.0, 4.4.1, 3.10.0, 3.10.1, 3.10.2, 3.10.3, 3.10.4, 4.4.2, 3.10.5, 4.4.3, 3.11.0, 4.4.4, 3.12.0, 3.12.1, 4.4.5, 3.13.0, 4.5.0, 4.5.1, 3.14.0, 4.6.0, 4.6.1, 3.15.0, 4.7.0, 3.15.1, 4.7.1, 3.15.2, 4.7.2, 4.7.3, 3.15.3, 4.7.4, 3.16.0, 4.8.0, 3.16.1, 4.8.1, 3.16.2, 4.8.2, 3.16.3, 3.16.4, 4.8.3, 3.16.5, 3.16.6, 4.8.4, 3.16.7, 4.8.5, 3.16.8, 4.8.6, 3.16.9, 4.8.7, 3.16.10, 4.8.8, 3.17.0, 3.17.1, 4.9.0, 3.17.2, 4.9.1, 4.9.2, 3.17.3, 4.9.3, 3.17.4, 4.9.4, 3.17.5, 4.9.5, 3.17.6, 3.17.7, 4.9.6, 4.9.7, 3.17.8, 4.9.8, 3.18.0, 3.18.1, 4.10.0, 3.18.2, 4.10.1, 5.0.0-alpha.1, 3.18.3, 4.10.2, 3.18.4, 4.10.3, 4.10.4, 4.10.5, 3.18.5, 3.18.6, 4.10.6, 4.10.7, 3.19.0, 4.10.8, 4.11.0, 3.19.1, 4.11.1, 3.19.2, 4.11.2, 3.20.0, 4.12.0, 3.20.1, 4.12.1, 4.12.2, 3.20.2, 4.12.3, 3.20.3, 4.12.4, 3.21.0, 4.13.0, 3.21.1, 4.13.1, 5.0.0-alpha.2, 3.21.2, 4.13.2, 4.13.3, 4.13.4, 4.14.0, 4.14.1, 5.0.0-alpha.3, 4.15.0, 5.0.0-alpha.4, 4.15.1, 4.15.2, 5.0.0-alpha.5, 4.15.3, 4.15.4, 4.15.5, 5.0.0-alpha.6, 4.16.0, 4.16.1, 4.16.2
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Naveen kumar Thota\AppData\Roaming\npm-cache\_logs\2017-11-01T21_44_43_351Z-debug.log

Facing same issue from two days and unable to build my project, When i am trying to install the previous version as you said getting other error, Can you guys help me out. It would be appreciated

**Comment by thotan09** [comment]
I changed it i am able to build now

**Comment by praveen-nuovo** [comment]
After changing too, I am getting the same errors

[16:45:41] Starting 'build.js.dev'...
.../node_modules/@types/express/index.d.ts(69,31): error TS2312: An interface may only extend a class or another interface.
.../node_modules/@types/express/index.d.ts(70,43): error TS2312: An interface may only extend a class or another interface.
.../node_modules/@types/express/index.d.ts(81,43): error TS2312: An interface may only extend a class or another interface.
.../node_modules/@types/express/index.d.ts(84,28): error TS2312: An interface may only extend a class or another interface.
[16:45:50] TypeScript: 4 semantic errors
[16:45:50] TypeScript: emit succeeded (with errors)

Can anyone help me with this

**Comment by felipesoares93** [comment]
@praveen-nuovo did you remove your node_modules folder, forced a cache clean up, etc? And which is the `@types` package that you are getting the index.d.ts error? I did an investigation looking the git commits for the package with problem and all related dependencies, so my hint for you is to do the same for the package that is not working. Sorry for not being able to help much more on that

**Comment by praveen-nuovo** [comment]
@felipesoares93 I removed node_modules folder,  forced a cache clean up. But still getting the same errors. 
Unable to build.

**Comment by PatrykTyszka** [comment]
builder/build/node_modules/@types/express/index.d.ts(69,31): error TS2312: An interface may only extend a class or another interface.
builder/build/node_modules/@types/express/index.d.ts(70,43): error TS2312: An interface may only extend a class or another interface.
builder/build/node_modules/@types/express/index.d.ts(81,43): error TS2312: An interface may only extend a class or another interface.
builder/build/node_modules/@types/express/index.d.ts(84,28): error TS2312: An interface may only extend a class or another interface.

I have the same error message... I tried to downgrade `express-serve-static-core`, but it doesn't work. 

Unable to build my project.

**Comment by PatrykTyszka** [comment]
@JPSchellenberg 👍  Thanks!

**Comment by afr1983** [comment]
@praveen-nuovo I was in the same position. Only worked after I reorganized my package.json to move all @types/* dependencies to devDependencies. Before that, `@types/morgan` was in dependencies, and was pulling the latest version of `express-serve-static-core` on its own.

**Comment by leeroya** [comment]
@JPSchellenberg 👍 Worked.

**Comment by afr1983** [comment]
I've traced the issue to [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21008) PR.

cc @andy-ms Can you please take a look on this?

**Comment by praveen-nuovo** [comment]
@afr1983 
For me, Fixed the problem specifying the dependency. Combination should be like this
	"@types/express": "4.0.33",
	"@types/express-serve-static-core": "4.0.49"

**Comment by andy-ms** [comment]
`@types/express` requires a minimum TypeScript version of 2.2. The error you are getting only happens under TypeScript 2.1 or below.
If you want to continue using ts2.1 you should be able to specify in your `package.json`:
```json
"@types/express": "ts2.1",
"@types/express-serve-static-core": "ts2.1",
```

**Comment by adeshshukla** [comment]
I updated my typescript from 2.1 to 2.2 and it worked like a charm.
Thanks @andy-ms 

"dependencies": {
    . . . .
    "typescript": "^2.2.2"
  },
  "devDependencies": {
     . . . .
    "@types/express": "^4.0.37",
    "@types/express-serve-static-core": "^4.0.50",
  }

**Comment by subodh6580** [comment]
node_modules/@types/express/index.d.ts(69,31): error TS2312: An interface may only extend a class or another interface.
node_modules/@types/express/index.d.ts(70,43): error TS2312: An interface may only extend a class or another interface.
node_modules/@types/express/index.d.ts(81,43): error TS2312: An interface may only extend a class or another interface.
node_modules/@types/express/index.d.ts(84,28): error TS2312: An interface may only extend a class or another interface.

I am enable to resolve this issue. guys help me!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
