### ISSUE TITLE
How to unpublish a definition?

### ISSUE THREAD

**Issue by billccn** [DefinitelyTyped/DefinitelyTyped#21153]
[error-stack-parser](https://github.com/stacktracejs/error-stack-parser) now provides its own `.d.ts` file with its npm distro.

The definition file in DefinitelyTyped is also quite outdated, so it's probably better to delete the definition here and direct users to use the npm packages.

I am happy to submit a PR if people can tell me how to update the npm page and https://microsoft.github.io/TypeSearch/

--

On a related topic, definition files in npm packages are only picked up if `"moduleResolution": "node"` is set. So for people not using node and were relying on `@types` packages alone, the definition will simply be not found. Is there any way to resolve this?

**Comment by leonard-thieu** [comment]
For removing a definition, follow the instructions found at https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package.
