### ISSUE TITLE
ZeroMQ Socket should be a class

### ISSUE THREAD

**Issue by jez9999** [DefinitelyTyped/DefinitelyTyped#21200]
`Socket` in the ZeroMQ package is a class that can have `instanceof` called on it. It should therefore be typed as a class and not an interface.

**Comment by erikma** [comment]
Main drawback here is that classes do not allow interface aggregation like interfaces do, reducing extensibility e.g. for util.promisify().

**Comment by jez9999** [comment]
I never liked interface aggregation anyway, it's confusing.   I say an interface should be defined once and it should be an error to define another identically named interface (except maybe with a C#-like `extends` keyword).

**Comment by jez9999** [comment]
Now merged.
