### ISSUE TITLE
@types/supercluster missing Options for superCluster(Option)

### ISSUE THREAD

**Issue by kl4kennylee81** [DefinitelyTyped/DefinitelyTyped#21211]
The type annotation for Option is missing properties initial, map, reduce.

take from the npm description
https://www.npmjs.com/package/supercluster

Property map/reduce options
In addition to the options above, supercluster supports property aggregation with the following three options:

initial: a function that returns an object with cluster's initial properties.
map: a function that returns properties to use for individual points.
reduce: a reduce function for calculating properties in clusters.
Example of setting up a sum cluster property that accumulates the sum of myValue property values:

var index = supercluster({
    initial: function() { return {sum: 0}; },
    map: function(props) { return {sum: props.myValue}; },
    reduce: function(accumulated, props) { accumulated.sum += props.sum; }
});

Author: @DenisCarriere

**Comment by DenisCarriere** [comment]
Make sense, @kl4kennylee81 feel free to send a PR with the appropriate changes and I can 👍 when the PR passes DefinitelyTyped's tests.

**Comment by DenisCarriere** [comment]
These features are new, they were only documented 2 months ago (before this definition was created).

https://github.com/mapbox/supercluster/commit/4e5dfcf71be4d36a9f7ea9f0f8a8ef5df67ca997

**Comment by kl4kennylee81** [comment]
okay sure thing will tag you again in the PR when completed. thanks!

**Comment by DenisCarriere** [comment]
👍 Sounds like a plan, usually DefinitelyTyped is pretty responsive when it comes with PR, should be merged within a day or two after all tests pass.

Make sure you add new test cases for the new options, just follow the same test style in [supercluster-tests.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/supercluster/supercluster-tests.ts).

**Comment by kl4kennylee81** [comment]
@DenisCarriere hey thanks for the tips. I'm pretty new to typescript as well as opening PR to public repos, I'll tag you in the PR. Any feedback is appreciated. I'll defer to you as well as any of the DefinitelyTyped members.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
