### ISSUE TITLE
@types/puppeteer ElementHandle.type() has the wrong number of arguments

### ISSUE THREAD

**Issue by paynoattn** [DefinitelyTyped/DefinitelyTyped#21210]
- [x] I tried using the `@types/puppeteer` package and had problems.
@marvinhagemeister @ondrejsevcik @davidkpiano @cdeutsch 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b67c928904f03d0911c99ab938b14bc2e59cad40/types/puppeteer/index.d.ts#L194

should be:
```
type(text: string, options?: { delay: number }): Promise<void>;
```
As per the [api docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandletypetext-options).

Should I submit a PR?

**Comment by ondrejsevcik** [comment]
sure thing, any PR that improves typings is more than welcomed ;)

**Comment by paynoattn** [comment]
@ondrejsevcik done.

**Comment by ondrejsevcik** [comment]
Good job, now you need to wait for maintainers to merge it. I'm not the owner of this definition so I can't help you with that ;)
