### ISSUE TITLE
filter isn't playing nice with pipe

### ISSUE THREAD

**Issue by will-wow** [DefinitelyTyped/DefinitelyTyped#21217]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/ramda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @donnut @mdekrey @LiamGoodacre @mrdziuban @sbking @afharo @teves-castro @hojberg

After upgrading to `@types/ramda: 0.25.0`, I'm getting a bunch of type errors from places where I'm using a partially-applied `filter` inside of a `pipe`.

Small test case:

```typescript
interface Foo {
  isFoo: boolean;
}

const isGood = (foo: Foo) => foo.isFoo;
const goodFoos = R.filter(isGood);
const pipedGoodFoos: (xs: Foo[]) => Foo[] = R.pipe(goodFoos);
```

With 0.24, this is fine. But in 0.25, I get this error on the last call to the piped function:
```
Type '(x0: Dictionary<Foo>) => Dictionary<Foo>' is not assignable to type '(xs: Foo[]) => Foo[]'.
  Types of parameters 'x0' and 'xs' are incompatible.
    Type 'Foo[]' is not assignable to type 'Dictionary<Foo>'.
      Index signature is missing in type 'Foo[]'.
```

The error goes away I don't wrap `filterFoos` in a pipe, or if explicitly type the partially-applied function like this:

```typescript
const goodFoos: (xs: Foo[]) => Foo[] = filter(isGood);
```

My guess is that since the 1-arity `filter` since now returning this:

```typescript
interface Filter<T> {
  (list: T[]): T[];
  (obj: Dictionary<T>): Dictionary<T>;
}
```

the `pipe`ed version of filter is for some reason defaulting to `Dictionary<T>` instead of knowing it could could still be either a list or a dictionary.

I'm not sure how to go about fixing this though, while still supporting object filtering. The workaround of explicitly typing all filters is workable, but we've got `filter` in a lot of pipes, so it's a bummer.

**Comment by afharo** [comment]
Hi @will-wow,

I believe this issue is due to R.pipe types. It's very generic because you can send any parameter to `R.pipe`.
Have you tried doing ```const pipedGoodFoos: (xs: Foo[]) => Foo[] =  (xs) => R.pipe(goodFoos)(xs);```?
With a little bit of luck, the compiler will identify the first parameter sent to R.pipe is a Foo[] and filter won't complain.

**Comment by jmjpro** [comment]
still a problem after six months :-(

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
