### ISSUE TITLE
@types/jsdom missing Event definitions

### ISSUE THREAD

**Issue by kevipapo1** [DefinitelyTyped/DefinitelyTyped#21235]
@leonard-thieu 

[jsdom](https://github.com/tmpvar/jsdom) has Event constructors on the window object (e.g. [MouseEvent](https://github.com/tmpvar/jsdom/issues/1546)), but there are no type definitions for these in `@types/jsdom`.

For example, the following is possible with jsdom, but missing the type definition for `window.Event`, causing the build to fail:

```typescript
import { JSDOM } from 'jsdom';
let dom = new JSDOM();
let event = new dom.window.Event('someTypeArg');
```

In your current implementation the type definition for window is:

```typescript
export interface DOMWindow extends Window { eval(script: string): void; }
```

Digging deeper, the Window interface as defined by [TypeScript](https://github.com/microsoft/typescript) itself does not contain definitions for the Event types. However, they do have definitions for these types, just not on the Window interface.

This should be an easy fix, simply include these Event type definitions on the DOMWindow interface for `@types/jsdom`. They could also be added to the Window interface by the TypeScript team. I would also suggest the possibility of the jsdom team making the Event types global, but they are not interested in doing this as indicated in the MouseEvent link above.

**Comment by leonard-thieu** [comment]
I'm not sure why the TypeScript definitions don't include the Event constructors. I think you should raise an issue with the TypeScript team.

**Comment by kevipapo1** [comment]
After opening [an issue](https://github.com/Microsoft/TypeScript/issues/19758) with the TypeScript team, they're considering adding the Event types to the `Window` interface, but it may take a while for them decide on how to do it.

In the meantime, I recommend adding the types to the `DOMWindow` interface as such:

```ts
export interface DOMWindow extends Window {
    eval(script: string): void;
    Event: typeof Event;
    // etc.
}
```

If this sounds good to you, I'll open up a PR.

**Comment by leonard-thieu** [comment]
Sounds good to me. Go for it.
