### ISSUE TITLE
@types/ramda definitions break under Typescript 2.6.1

### ISSUE THREAD

**Issue by burabure** [DefinitelyTyped/DefinitelyTyped#21238]
- [x] I tried using the `@types/ramda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @donnut, @mdekrey, @mrdziuban, @sbking, @afharo, @teves-castro, @1M0reBug, @hojberg, @charlespwd, @samsonkeung

------

Using the latest Typescript compiler (2.6.1) the following code breaks because of the definitions, this did not happen on 2.5.3
```ts
import { compose, pluck, product, props, sum } from 'ramda'

export interface IItemLineForTotals {
  qty: number
  price: number
}

export const getItemTotal: (itemLine: IItemLineForTotals) => number = compose(
  product,
  props(['qty', 'price']),
)
export const getItemsQty: (itemLines: IItemLineForTotals[]) => number = compose(sum, pluck('qty'))
```

```
ERROR in [at-loader] ./src/ui/lib/itemLineHelpers.ts:9:3 
    TS2345: Argument of type '(list: number[]) => number' is not assignable to parameter of type '(x: {}[]) => number'.
  Types of parameters 'list' and 'x' are incompatible.
    Type '{}[]' is not assignable to type 'number[]'.
      Type '{}' is not assignable to type 'number'.

ERROR in [at-loader] ./src/ui/lib/itemLineHelpers.ts:12:81 
    TS2345: Argument of type '(list: number[]) => number' is not assignable to parameter of type '(x: {}[]) => number'.
  Types of parameters 'list' and 'x' are incompatible.
    Type '{}[]' is not assignable to type 'number[]'.
```

**Comment by pelotom** [comment]
Ramda's current typings are too lax for `strictFunctionTypes`. The definition for `pluck` for example is

```ts
pluck<T>(p: string | number, list: any[]): T[];
pluck(p: string | number): <T>(list: any[]) => T[];
```

but should probably be something like

```ts
pluck<K extends string, T>(p: K, list: Record<K, T>[]): T[];
pluck<T>(p: number, list: { [k: number]: T }[]): T[];
pluck<K extends string>(p: K): <T>(list: Record<K, T>[]) => T[];
pluck(p: number): <T>(list: { [k: number]: T }[]) => T[];
```

There's a _lot_ of signatures beyond `pluck` and `props` that suffer from this sort of lax typing :(
