### ISSUE TITLE
JSX element type 'Component<{}, {}>' is not a constructor function for JSX elements

### ISSUE THREAD

**Issue by burabure** [DefinitelyTyped/DefinitelyTyped#21242]
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz @richseviora @theruther4d

---

the following code fails with the latest types (`@types/react: 16.0.19, @types/react-dom: 16.0.2`)

```ts
const foo = (SomeComponent: typeof React.Component) => class extends React.Component<any, any> {
  render() {
    return <SomeComponent />
  }
}
```

```
TS2605: JSX element type 'Component<{}, {}>' is not a constructor function for JSX elements.
          Types of property 'render' are incompatible.
            Type '() => string | number | false | Element | ReactPortal | Element[] | null' is not assignable to type '{ (): string | number | false | Element | ReactPortal | Element[] | null; (): false | Element | n...'.
              Type 'string | number | false | Element | ReactPortal | Element[] | null' is not assignable to type 'false | Element | null'.
                Type 'string' is not assignable to type 'false | Element | null'.
```

**Comment by zenmumbler** [comment]
I had this exact same issue and it turned out that my yarn.lock had 2 slightly different revisions selected of types/react (in my case 16.0.19 and 16.0.20). There was no good reason for this (one had a * as version requirement and the other ^16.0.19) but I fixed it by deleting my yarn.lock (I also removed my node_modules folder as a paranoid step) and then had yarn resolve everything anew.

This time yarn decided that both could use the same react/types package and my errors were gone. The same could happend with NPMs package-lock.json I guess. In any case, I would verify that there isn't some subtle conflict / split-brain issue in your lock file.
If packages keep selecting old versions of types files you can force it in yarn to pick the version you want with a resolutions block in your package.json, see https://yarnpkg.com/en/docs/selective-version-resolutions to force it to use a single version, but this requires manual upkeep.

**Comment by ColinEberhardt** [comment]
I had the same issue as @zenmumbler - various `@types/react-*` dependencies that depend on different versions of `@types/react`.

I updated dependencies to ensure all depended on `"@types/react" "*"` - and that fixed it.

**Comment by burabure** [comment]
I think that was the issue, `rm -rf node_modules && rm yarn.lock && yarn` solved it. Thanks @zenmumbler !

**Comment by wanghaooo** [comment]
My solution is to not use the yarn installation, but use npm by: rm -rf node_modules && rm yarn.lock && npm install

**Comment by wanghaooo** [comment]
My solution is to not use the yarn installation, but use npm by: rm -rf node_modules && rm yarn.lock && npm install

**Comment by chibicode** [comment]
I had a similar error (`"@types/react": "16.4.7"`). Even with this simple code,

```tsx
import React from 'react'

const Foo: React.SFC = () => <span>foo</span>

export default Foo
```

I kept getting:

```
Type 'Element' is not assignable to type 'ReactElement<any>'
  Type 'string | ComponentClass<any> | StatelessComponent<any>' is not assignable to type 'string | StatelessComponent<any> | ComponentClass<any, ComponentState>'.
```

But removing dependencies solved it:

```
rm -rf node_modules && rm yarn.lock && yarn
```

**Comment by morsh** [comment]
Not the prettiest solution, but I solved it by the following example:
`
render() {
      const UntypedComponent = WrappedComponent as any;
      return <UntypedComponent
                {...this.props}
                additionalProp={"Some Value"} />;
}
`

**Comment by qmachard** [comment]
This notation works for me to import `JSX` files into `TSX` but it's not the prettiest :

```
const SomeComponent = require('/path/to/SomeComponent').default;

class MyComponent extends React.Component<any, any> {
    render() {
        return <SomeComponent />
    }
}
```

**Comment by paulmdorr** [comment]
Changing

```TypeScript
export default class SomeComponent extends React.Component<any, any> { /*...*/ }
```

to

```TypeScript
class SomeComponent extends React.Component<any, any> { /*...*/ }

export default SomeComponent;
```

fixed it for me, without having to replace the import with a require.

**Comment by aruniverse** [comment]
@paulmdorr  Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.ts(1046)

**Comment by paulmdorr** [comment]
> @paulmdorr Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.ts(1046)

@aruniverse I'm sorry I should've replied directly to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21242#issuecomment-501206684, where they were talking about the require in tsx and jsx, not in d.ts files. Sorry for the confusion.
