### ISSUE TITLE
[type request] add types for react-google-recaptcha

### ISSUE THREAD

**Issue by kgtkr** [DefinitelyTyped/DefinitelyTyped#21268]
https://www.npmjs.com/package/react-google-recaptcha

**Comment by orobert91** [comment]
How do you import this using ES6 import syntax?

I tried:
import Recaptcha from 'react-recaptcha';
import {Recaptcha} from 'react-recaptcha';
import * as Recaptcha from 'react-recaptcha';

None of these work.

**Comment by kgtkr** [comment]
It's react-google-recaptcha, not react-recaptcha

**Comment by RohrerF** [comment]
typings are avaiable now:

https://www.npmjs.com/package/@types/react-google-recaptcha


this issue can be closed
