### ISSUE TITLE
@types/history compilation errors in TypeScript@2.6.1

### ISSUE THREAD

**Issue by remojansen** [DefinitelyTyped/DefinitelyTyped#21319]
I'm using history v3. I cannot upgrade to the latest version (v4) for now because it introduces some major changes. I upgraded TypeScript and to 2.6.1 and I'm getting:

> [at-loader] Checking finished with 1 errors
> [at-loader] node_modules/@types/history/lib/actions.d.ts:5:16 
> The expression of an export assignment must be an identifier or qualified name in an ambient context. 

The pointed file can be found [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/history/v3/lib/actions.d.ts#L5).

**Comment by andy-ms** [comment]
* That file is part of history v3, and its not in the latest version.
* It appears to have already been fixed, using `declare const defaultExport` instead of attempting to directly `export default {...}` an object literal.

**Comment by MortenChristiansen** [comment]
Yes, this has been fixed in version 3.2.2 of the type definition.

**Comment by remojansen** [comment]
I can confirm that it is fixed :+1:
