### ISSUE TITLE
[@types/leaflet] Jumping from version "1.2.1" to version "0.7.31"?

### ISSUE THREAD

**Issue by big-r81** [DefinitelyTyped/DefinitelyTyped#21311]
@alejo90 @atd-schubert Hi,

is the version "1.2.1" behind "0.7.31" or is it a wrong publish?
I was installing the type definnition in a new project. My code work with version "1.2.1" but not with version "0.7.31"...

**Comment by atd-schubert** [comment]
No, this must be a problem with the process of publishing, I think.

`1.2.1` is definitely the latest version. I recommend to install it with:

```bash
npm install --save @types/leaflet@1.2.x
```

**Comment by davidpronk** [comment]
According to [npmjs](https://www.npmjs.com/package/@types/leaflet ) `0.7.31 is the latest of 56 releases`

**Comment by atd-schubert** [comment]
@DanielRosenwasser Do you know how to set the newer version (`1.2.1`) as latest?

**Comment by big-r81** [comment]
FYI,

on npmjs:
>  types published 3 days ago
1.2.2 is the latest of 57 releases
github.com/DefinitelyTyped/DefinitelyTyped 

But who was setting this?

**Comment by atd-schubert** [comment]
Ah thank you @big-r81 , I don't know who updates the library...

I just wanted to know what is the reason and the solution for the wrong version, also for feature releases...

**Comment by Nexxado** [comment]
version 1.2.2 causes errors for me:

```
ERROR in [at-loader] ./node_modules/@types/leaflet/index.d.ts:586:18
    TS2314: Generic type 'Feature<T>' requires 1 type argument(s).
```

Reverted to v1.2.1 to fix the error.

**Comment by brgrz** [comment]
> version 1.2.2 causes errors for me:
> 
> ERROR in [at-loader] ./node_modules/@types/leaflet/index.d.ts:586:18
>     TS2314: Generic type 'Feature<T>' requires 1 type argument(s).
> Reverted to v1.2.1 to fix the error.

Same error when compiling with version 1.2.6

**Comment by DanielRosenwasser** [comment]
Sorry, I never caught this. Is this still occurring? @andy-ms, any clue how to correct this?

**Comment by andy-ms** [comment]
@types/leaflet latest is currently 1.2.6, don't know what was going wrong in november.
@Nexxado @brgrz In the latest version of `@types/geojson` `Feature` takes 2 type arguments, could you check your version of *that*?

**Comment by Nexxado** [comment]
@andy-ms 1.2.6 works fine for me, thank you.

**Comment by Nexxado** [comment]
v1.2.7 raises new issues:

---

1. `const latlngs: L.LatLng[] = polyline.getLatLngs();` - where `polyline` is of type `L.Polyline` raises this error:
```JS
TS2322: Type 'LatLng[] | LatLng[][] | LatLng[][][]' is not assignable to type 'LatLng[]'.
   Type 'LatLng[][]' is not assignable to type 'LatLng[]'.
     Type 'LatLng[]' is not assignable to type 'LatLng'.
       Property 'equals' is missing in type 'LatLng[]'.
```
---

2. 
```JS
const latlngs = polygon.getLatLngs();
polygon2 = L.polygon(latlngs, options);
```
raises this error on the 2nd line:

```JS
TS2345: Argument of type 'LatLng[] | LatLng[][] | LatLng[][][]' is not assignable to parameter of type 'LatLngExpression[] | LatLngExpression[][]'.
   Type 'LatLng[][][]' is not assignable to type 'LatLngExpression[] | LatLngExpression[][]'.
     Type 'LatLng[][][]' is not assignable to type 'LatLngExpression[][]'.
       Type 'LatLng[][]' is not assignable to type 'LatLngExpression[]'.
         Type 'LatLng[]' is not assignable to type 'LatLngExpression'.
           Type 'LatLng[]' is not assignable to type 'LatLngLiteral'.
             Property 'lat' is missing in type 'LatLng[]'.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
