### ISSUE TITLE
[@types/selenium-webdriver] - Why is version 2.53.43 specified as the latest? 

### ISSUE THREAD

**Issue by wluu** [DefinitelyTyped/DefinitelyTyped#21357]
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] Authors: @BillArmstrong, @Kuniwak, @cnishina, @SupernaviX, @bendxn

Our Jenkins build was failing to build our protractor tests:
```
> tsc -p test/e2e/

node_modules/@types/protractor-helpers/index.d.ts(36,113): error TS2694: Namespace '"/home/ec2-user/home/ec2-user/workspace/UI-protractor/node_modules/@types/selenium-webdriver/index"' has no exported member 'Locator'.
```
I was digging into the issue and discovered that `@types/protractor-helpers` specifies `@types/selenium-webdriver` with `*`:
```
 $ cat ./node_modules/@types/protractor-helpers/package.json | jq '.dependencies'
{
  "@types/jasmine": "*",
  "@types/selenium-webdriver": "*"
}
``` 
 
This will cause our Jenkins job to install `@types/selenium-webdriver@2.53.43`. Before, it was pulling down`@types/selenium-webdriver@ 3.0.8`. We were able make our Jenkins job build our protractor tests again by specifying `@types/selenium-webdriver@ 3.0.8` in our `devDependencies`. 

However, I can't find any information as to why 2.53.43 is set as the latest dist-tag.

**Comment by cnishina** [comment]
I'm not sure why 2.53.43 is listed as the latest on npmjs.com. This seems to be an issue with the release for definitely typed.

**Comment by cnishina** [comment]
@andy-ms any thoughts?

**Comment by SupernaviX** [comment]
https://registry.npmjs.com/@types%2fselenium-webdriver It looks like version 2.53.43 was just released yesterday (because of some tslint-related changes in the v2 folder), and it took precedence over the version which is latest by semver rules.

**Comment by cnishina** [comment]
Neat. I always assumed latest was the largest semver rather than the last published to npm. Anyway, I have a proposed workaround: install `@types/protractor-helpers` and to install `@types/selenium-webdriver` version 3.0.8. At first if you install it in this order, it will pull down the latest at 2.53.43 and then replace it with 3.0.8.

```
npm i -D @types/protractor-helpers
npm i -D @types/selenium-webdriver@3.0.8
```

Removing the `node_modules` directory and doing an `npm install` also results in the correct version 3.0.8.

**Comment by cnishina** [comment]
Thanks @andy-ms for getting selenium-webdriver types back to 3.0.8 as the latest.

**Comment by wluu** [comment]
Thanks everyone for taking a look at this!
