### ISSUE TITLE
@types/reactstrap PopoverBody missing for definitions file

### ISSUE THREAD

**Issue by pierreferry** [DefinitelyTyped/DefinitelyTyped#21374]
Hi, it seems that PopoverBody is missing from definitions file in the last release of @types/reactstrap ( '5.0.1': '2017-11-07' )

Please tell me if i did anything wrong !

Thx
-Authors: @mfal @danilobjr @fabiopaiva @alihammad

**Comment by FaithForHumans** [comment]
This was fixed in #21178

**Comment by pierreferry** [comment]
Thanks!
