### ISSUE TITLE
Can't create Express app with http.createServer()

### ISSUE THREAD

**Issue by jez9999** [DefinitelyTyped/DefinitelyTyped#21371]
- [x] I tried using the `@types/express` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov 

I'm trying to create an Express app the way I used to in JS and it worked, but it doesn't work in TypeScript because `express()` doesn't create an `http.Server`:

```
import * as http from "http";
import express = require("express");

export default class TestClass {
    public static init() {
        const app = express();
        app.use(...);
        let server = http.createServer(app);
        return server;
    }
}
```

I need to do it this way because I don't want to listen immediately, I just want to set up the server and listen later.  How can I get this to work?  Do the typings need changing?  Apparently, `express()` does return an `http.Server` because passing that in works in JavaScript.

**Comment by BruceHem** [comment]
This happens to me too.

**Comment by slawiko** [comment]
Me too!

**Comment by Tryptophan** [comment]
I think the ```@types/express``` package is broken currently (it's not directly maintained by expressjs). Try this:
```
let app: any;
app = express();
...
var server = http.createServer(app);
```

This doesn't use the strict typing typescript lets you do, but it's a temporary workaround that has worked for me.

**Comment by jez9999** [comment]
Kind of sucks that it isn't maintained.

**Comment by BruceHem** [comment]
It should to be fine, something must have gone wrong.

**Comment by slawiko** [comment]
Actually it's an Open Source. Here WE must fix it. Anyone can tell me what's exactly wrong in types?

**Comment by Tryptophan** [comment]
@slawiko I'm not exactly sure whats wrong, but this may help; This is the type app should be:
```
let app: express.Application;
```
but for whatever reason this type can't be passed into ```http.createServer(app);```. So I assume something in express.Application isn't defined correctly.

**Comment by jez9999** [comment]
The problem is that `http.createServer` wants to be passed a `(request: IncomingMessage, response: ServerResponse) => void`.  The object created by `Express()` *does* provide this:
```
export interface Express extends Application {
    request: Request;
    response: Response;
}

export interface Application extends IRouter, Express.Application {
    /**
     * Express instance itself is a request handler, which could be invoked without
     * third argument.
     */
    (req: Request, res: Response): any;
    [...]
```

However, `Request` implements more too, such as:
```
    set(setting: string, val: any): Application;
    get: ((name: string) => any) & IRouterMatcher<this>;
```

Because this is not implemented by `IncomingMessage`, TypeScript says you can't assign the Express object to the required `http.createServer` function signature (which seems odd; why is there a problem implementing *more* than is necessary?) so you get errors like `Property 'get' is missing in type 'IncomingMessage'.`.

You *can* get it to work by casting it to something compatible:
`_server = http.createServer(webApp as (req: any, res: any) => void);`

But this feels clunky/hacky; it's just basically saying to TypeScript "it works, just believe me god dammit!!".  There should be a more elegant way to do it so it fits in nicely with the Express typings.  Someone more au fait with the intricacies of TypeScript needs to advise on this... @andy-ms ? :smile:

**Comment by andy-ms** [comment]
The compiler is behaving correctly -- `req: Request` occurs in an *in* position, so it's contravariant. `Application` declares that it *needs* to be passed a full `Request` with all of its properties, which is incompatible with something that could work with only getting an `IncomingMessage`.
One solution would be to change `Application` to take only an `IncomingMessage` -- if that's accurate to what the library can actually do.

**Comment by jez9999** [comment]
@andy-ms I thought arguments were bivariant in TS?

**Comment by andy-ms** [comment]
Not with [`--strictFunctionTypes`](https://blogs.msdn.microsoft.com/typescript/2017/10/31/announcing-typescript-2-6/).

**Comment by donaldpipowitch** [comment]
I made a PR to fix this when `--strictFunctionTypes` is used. But I'm not _that_ familiar with express, so please comment if this change is correct or not. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21643

**Comment by slawiko** [comment]
@donaldpipowitch it fixes problem for me, but I'm not sure, that it won't break something. Let's ask any expert. Anyway, thank you!
