### ISSUE TITLE
Problem with `continuation` type in highlight.js

### ISSUE THREAD

**Issue by peterjwest** [DefinitelyTyped/DefinitelyTyped#21383]
The highlight.js types specify the `continuation` argument of `highlight(...)` as `boolean | undefined`, however the docs imply that this should be a "mode stack" (http://highlightjs.readthedocs.io/en/latest/api.html#highlight-name-value-ignore-illegals-continuation).

I think the correct type might be `ICompiledMode | undefined`, but not 100% sure.

cc: @nikeee @sourrust

**Comment by nikeee** [comment]
Good catch! Do you want to submit a PR or should someone else do it?

**Comment by peterjwest** [comment]
Fixed, thanks!
