### ISSUE TITLE
React-Bootstrap types interface x incorrectly extends interface y

### ISSUE THREAD

**Issue by parissge** [DefinitelyTyped/DefinitelyTyped#21391]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

I have 8 errors in my project all related with the below message:
Error TS2430 (TS) Interface 'PopoverProps' incorrectly extends interface 'Pick<HTMLProps, "title" | "accept" | "acceptCharset" | "action" | "allowFullScreen" | "a...'.
Types of property 'title' are incompatible.
Type 'ReactNode' is not assignable to type 'string'.
Type 'number' is not assignable to type 'string'. 
C:\Test\node_modules@types\react-bootstrap\lib\Popover.d.ts
Severity Code Description Project File Line Suppression State
Error TS2430 (TS) Interface 'ProgressBarProps' incorrectly extends interface 'Pick<HTMLProps, "title" | "accept" | "acceptCharset" | "action" | "allowFullScreen" ...'.
Types of property 'label' are incompatible.
Type 'ReactNode' is not assignable to type 'string'.
Type 'number' is not assignable to type 'string'. 
C:\Test\node_modules@types\react-bootstrap\lib\ProgressBar.d.ts
.......... and more..........

Currently my package.json is:
  "devDependencies": {
    "types/jquery": "^3.2.16",
    "types/node": "^8.0.50",
    "types/react": "^16.0.22",
    "types/react-bootstrap": "^0.31.7",
    "types/react-dom": "^16.0.3",
    "awesome-typescript-loader": "^3.3.0",
    "css-loader": "^0.28.7",
    "expose-loader": "^0.7.3",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.5",
    "source-map-loader": "^0.2.3",
    "typescript": "^2.6.1",
    "url-loader": "^0.6.2",
    "webpack": "^3.8.1"
  },
  "dependencies": {
    "jquery": "^3.2.1",
    "react": "^16.1.0",
    "react-bootstrap": "^0.31.5",
    "react-dom": "^16.1.0"
  }
Can anyone please advise me what to do?

**Comment by GeertHuls** [comment]
Hi,

It seems like I stumbled across the same issue.
Turns out the version numbers of the @types/react-bootstrap@0.31.7 & react-bootstrap@0.31.5. don't match.

Try installing the typed react bootstrap v 0.31.5 instead:
> npm install --save-dev @types/react-bootstrap@0.31.5

That worked out fine for me.

Regards.

**Comment by parissge** [comment]
Thank you very much.
After switching to 0.31.5 as you pointed out the are no more any errors.
