### ISSUE TITLE
delete @types/autobind-decorator?

### ISSUE THREAD

**Issue by stevemao** [DefinitelyTyped/DefinitelyTyped#21392]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @stevemao

If you do not mention the authors the issue will be ignored.

https://github.com/andreypopp/autobind-decorator/pull/60

Looks like the package defined here is outdated and we include the types in the original package https://github.com/andreypopp/autobind-decorator

**Comment by r3nya** [comment]
Hey @stevemao!
I've created PR about it.
Thank you.

**Comment by r3nya** [comment]
Hey! My PR was merged, please close your task. :)
