### ISSUE TITLE
sinon-test types are out of date

### ISSUE THREAD

**Issue by peterjwest** [DefinitelyTyped/DefinitelyTyped#21401]
sinon-test has changed its exported interface: https://github.com/sinonjs/sinon-test/commit/81ab7d59c4abee846cfd4f6b08f85f28ab322ffd

I _think_ the new types should be:
```
import * as Sinon from 'sinon';

interface Configuration {
  injectIntoThis?: boolean;
  injectInto?: any;
  properties?: Array<"spy"| "stub"| "mock"| "clock"| "server"| "requests">;
  useFakeTimers?: boolean;
  useFakeServer?: boolean;
}

function sinonTest(sinon: Sinon.SinonStatic, config?: Configuration): any;
namespace sinonTest {
    function configureTest(sinon: Sinon.SinonStatic, config?: Configuration): any;
}

export = sinonTest;
```

But not totally sure

cc @mummybot

**Comment by Coteh** [comment]
I think you're right. I have put up a PR [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36558) containing links to a diff and to source code that proves it.

**Comment by peterjwest** [comment]
Great, thanks!

**Comment by Coteh** [comment]
My PR has been merged so this can be closed now.
