### ISSUE TITLE
Missing types for case-sensitive-paths-webpack-plugin

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DefinitelyTyped/DefinitelyTyped#21496]
https://www.npmjs.com/package/case-sensitive-paths-webpack-plugin

**Comment by r3nya** [comment]
Ok, will do it.

**Comment by r3nya** [comment]
Hey @JoshuaKGoldberg!
I've created PR about this typings https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21555.
Waiting for review. :)

**Comment by r3nya** [comment]
Hey! It was merged. Yoo hoo!
Please use it and close your issue.

**Comment by JoshuaKGoldberg** [comment]
Awesome, thanks @r3nya!
