### ISSUE TITLE
Lodash: `flow` has wrong return type when provided function has rest parameter

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#21533]
Given:

``` ts
import pipe from 'lodash/flow';

const identity = <T>(t: T) => t;
const myFn = (x: number, ...ys: number[]) => x;
const myFnPiped = pipe(myFn, identity);

myFnPiped(1, 2);
```

`myFnPiped` has type `(a1: number) => number`.

I expect it to have `(a1: number, ...a2: number[]) => number`.

It seems that the `1-argument first function` overload is being picked.

I can fix it locally by adding another overload specifically for 2-argument first function where the second parameter is a rest parameter:

``` ts
// 2-argument first function
flow<A1, A2, R1, R2>(f1: (a1: A1, ...a2: A2[]) => R1, f2: (a: R1) => R2): (a1: A1, ...a2: A2[]) => R2;
```

This must appear before all `1-argument first function` overloads.

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @ericanderson @aj-r @ailrun @e-cloud @thorn0 @jtmthf

If you do not mention the authors the issue will be ignored.

**Comment by thorn0** [comment]
So basically we need twice as more overloads, right? It seems like we need a script for generating them all. If someone feels like giving it a try, there even already is the `types/lodash/scripts` folder for scripts. And don't forget about `flowRight`.

**Comment by aj-r** [comment]
I created an issue (#20294) which should help simplify the `flow` types. However we may still want to fix this in the meantime, in case that takes a long time to implement.

**Comment by jtmthf** [comment]
@thorn0 @aj-r I used a very rough script to generate the `flowRight` types several weeks ago. I'll see if I can make it more generic and commit it with along with flow improvements.

**Comment by OliverJAsh** [comment]
In TS 3.1+, this is fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35241/files#diff-854c815d18186623bc883d002819f561R175.
