### ISSUE TITLE
[@types/react-native] missing property 'presentationType'

### ISSUE THREAD

**Issue by anarwade** [DefinitelyTyped/DefinitelyTyped#21534]
The property 'presentationType' is missing for react-native's Modal component. 
I tried using @types/react-native 0.50.5.

- Authors: @alloy

**Comment by alloy** [comment]
Please send a PR to add this 🙏 

I’m going to close the issue, because while it’s valid feedback, these  request issues won’t be acted on by us that don’t need to use that API at the moment, at least not any time soon, and so they just sit here and go stale.
