### ISSUE TITLE
Did the version of @types/node just regress from 8.0.52 to 6.0.92?

### ISSUE THREAD

**Issue by davidbowenukibmcom** [DefinitelyTyped/DefinitelyTyped#21550]
- [ * ] I tried using the `@types/node` package and had problems.

> Version `8.0.52` has been working well for us, but when we `npm install` now we get `6.0.92` which is problematic.

- [ * ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

>tsc --version
>Version 2.6.1

- [ * ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

> It probably warrants faster action than a SO thread

- [ * ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sandersn 

I can see in our old builds that we were merrily using @types/node 8.0.52 but we've jumped back to 6.0.92.

Of course it's our own fault for using:

`"@types/node":"*"`

but it seems like an odd thing to happen.

We're seeing issues such as:

```
error TS2305: Module '"url"' has no exported member 'URL'.
```

I've been trying to track down the commit that caused this but am overwhelmed by all the merge requests at the moment.

**Comment by adamkl** [comment]
I just saw the same thing.

**Comment by RyanCavanaugh** [comment]
@andy-ms looks like types-publisher did the wrong thing

> npm dist-tag ls @types/node
latest: 6.0.92 <--- !!
ts2.0: 8.0.52
ts2.1: 8.0.52
ts2.2: 8.0.52
ts2.3: 8.0.52
ts2.4: 8.0.52
ts2.5: 8.0.52
ts2.6: 8.0.52
ts2.7: 8.0.52

**Comment by RyanCavanaugh** [comment]
I've fixed the tag manually in the meantime

**Comment by jinwoo** [comment]
Now 4.2.23 is the latest!!!

**Comment by RyanCavanaugh** [comment]
> Now 4.2.23 is the latest!!!

@jinwoo  ?
```
C:\github\TypeScript>npm dist-tag ls @types/node
latest: 8.0.52
ts2.0: 8.0.52
ts2.1: 8.0.52
...
```

**Comment by jinwoo** [comment]
Now it's back to 8.0.52. When I tried ~32 min ago, it showed

```shell
$ npm dist-tag ls @types/node
latest: 4.2.23
ts2.0: 8.0.52
ts2.1: 8.0.52
ts2.2: 8.0.52
ts2.3: 8.0.52
ts2.4: 8.0.52
ts2.5: 8.0.52
ts2.6: 8.0.52
ts2.7: 8.0.52
```

**Comment by davidbowenukibmcom** [comment]
LGTM.
