### ISSUE TITLE
[@types/ioredis]: new signature for mget makes usage difficult

### ISSUE THREAD

**Issue by marshall007** [DefinitelyTyped/DefinitelyTyped#21579]
- [x] I tried using the `@types/ioredis` package and had problems.
- [x] Mention the authors so they can respond.
  - @plantain-00 (see https://github.com/DefinitelyTyped/DefinitelyTyped/commit/acf639ab3b31fea2f9e7f66ac4189e9ddedbb1b4#diff-77c12eda472c636dbbde3195da016159L94)

```ts
const redis = new Redis();

const keys = [ 'foo', 'bar' ];
redis.mget(...keys);

// -> [ts] Expected at least 1 arguments, but got a minimum of 0.
```

Given that `mget` does require at least one key to be specified, @plantain-00's change updating the signature made sense:

```ts
mget(key: string, ...keys: string[]): any;
```

However, there doesn't appear to be a way to use the spread operator and workaround the resulting compilation error, so I don't think it's worth enforcing. Thoughts?

**Comment by plantain-00** [comment]
#21589 should fix this
