### ISSUE TITLE
Problem defining interfaces for return document with mongoose

### ISSUE THREAD

**Issue by maicss** [DefinitelyTyped/DefinitelyTyped#21592]
@simonxca

typescript: 2.6.1
mongoose: 4.13.3
'\@\types/mongoose': 4.7.27
node: 9.1.0
OS: Mac OS 10.12.6
```
import mongoose = require("mongoose");
mongoose.Promise = global.Promise;
interface IUser {
  uuid: number
  email: string
  password: string
  displayName: string
}
mongoose.connect('mongodb://localhost:27017/test', {useMongoClient: true});

interface IUserModel extends IUser, mongoose.Document { }

const userSchema = new mongoose.Schema({
  uuid: {type:Number, required: true, index: true, unique: true},
  email: {type: String},
  password: String,
  displayName: String
});

const User = mongoose.model("User", userSchema);

User.insertMany([{uuid: 7, email: "user@appsilon.pl"}])
  .then((d:IUserModel[]) => console.log(d));
```

I got error :
```
Error:(23, 9) TS2345:Argument of type '(d: IUserModel[]) => void' is not assignable to parameter of type '((value: Document[]) => void | PromiseLike<void>) | null | undefined'.
  Type '(d: IUserModel[]) => void' is not assignable to type '(value: Document[]) => void | PromiseLike<void>'.
    Types of parameters 'd' and 'value' are incompatible.
      Type 'Document[]' is not assignable to type 'IUserModel[]'.
        Type 'Document' is not assignable to type 'IUserModel'.
          Property 'uuid' is missing in type 'Document'.
```

**Comment by maicss** [comment]
and anothor question:
![](https://user-images.githubusercontent.com/9784767/32881780-45fadd22-caed-11e7-82b1-68b1a16d644f.png)

mongoose model document: http://mongoosejs.com/docs/api.html#model_Model.deleteOne

**Comment by simonxca** [comment]
@maicss Can you initialize your mongoose model like this?
```js
const User = mongoose.model<IUserModel>("User", userSchema);
```
Can you let me know if that works?

**Comment by simonxca** [comment]
Also `deletedOne` looks like it was added recently. I'll add it to the Typescript Definitions.

**Comment by maicss** [comment]
`const User = mongoose.model<IUserModel>("User", userSchema);` works fine. 

Thanks very much!!

**Comment by maicss** [comment]
could you help me with this questions: https://stackoverflow.com/questions/47384420/mongoose-return-document-format-with-typescript

thanks!

**Comment by maicss** [comment]
@simonxca 

```
export interface indexImage {
        name: string,
        author: string,
        width: number,
        height: number,
        id: number,
        format: string,
        url: string,
    }

export interface indexImageDocument extends indexImage, mongoose.Document {}
```
error: 
`Error:(116, 22) TS2320:Interface 'indexImageDocument' cannot simultaneously extend types 'indexImage' and 'Document'.
  Named property 'id' of types 'indexImage' and 'Document' are not identical.`

I know mongodb use `_id`, not use `id`, but here I cannot use key `id`, why limit this?

**Comment by maicss** [comment]
For a week, not any answer, Should I open a new issue for this question?

**Comment by simonxca** [comment]
Oh sorry, I just saw you reopenend. Mongoose has it's own `id` property.
http://mongoosejs.com/docs/api.html#document_Document-id

Which is why you're seeing that error.

How are you using `indexImageDocument` in your code?
Have you taken a look at: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mongoose#creating-and-saving-documents?

**Comment by maicss** [comment]
Thanks for your comment.

code: 
```
//models.ts
const indexImageSchema:mongoose.Schema = new Schema({
    type: {type: String, required: true, "enum": ["temp", "like", "dislike"]},
    name: {type: String, required: true},
    author: {type: String, required: true},
    width: {type: Number, required: true},
    height: {type: Number, required: true},
    id: {type: Number, unique: true, required: true, index: true},
    format: {type: String, required: true},
    url: {type: String, required: true}
}, {id: false});// add id: false here

export const indexImageModel: mongoose.Model<DatabaseInterfaces.indexImageDocument> = mongoose.model<DatabaseInterfaces.indexImageDocument>("indexImage", indexImageSchema);

// interfaces.ts
    export interface indexImage {
        name: string,
        author: string,
        width: number,
        height: number,
        id: number,
        format: string,
        url: string,
        type: "dislike" | "like" | "temp",
    }

    export interface indexImageDocument extends indexImage, mongoose.Document {}

// still has error:
Error:(116, 22) TS2320:Interface 'indexImageDocument' cannot simultaneously extend types 'indexImage' and 'Document'.
  Named property 'id' of types 'indexImage' and 'Document' are not identical.
```

But I don't know why Mongoose use `id` key. Why not something like `__id`, just like `__v`, and now I can create a schema without `id` field by `new Schema({ name: String }, { id: false });`, but it still gives error in typescript.

And will you help me with the stackoverflow question? I will very appreciate it.

Thanks.

**Comment by simonxca** [comment]
I can change so that you can do:
```js
export interface indexImage extends mongoose.Document {
   ...
}

const indexImageModel = mongoose.model<indexImage>("indexImage", indexImageSchema);
```
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21856

Unfortunately, typescript will not let you extend both interface at once.
```js
export interface indexImageDocument extends indexImage, mongoose.Document {}
```

The `id` property has to be exactly the same.

**Comment by maicss** [comment]
[An interface can extend multiple interfaces, creating a combination of all of the interfaces.](https://www.typescriptlang.org/docs/handbook/interfaces.html)
```typescript
interface Shape {
    color: string;
}

interface PenStroke {
    penWidth: number;
}

interface Square extends Shape, PenStroke {
    sideLength: number;
}

let square = <Square>{};
square.color = "blue";
square.sideLength = 10;
square.penWidth = 5.0;
```

---

As the document you means this? : 
```typescript
export interface indexImage extends mongoose.Document{
        name: string,
        author: string,
        width: number,
        height: number,
        id: number,
        format: string,
        url: string,
        type: "dislike" | "like" | "temp",
    }

// and delete code below? 
export interface indexImageDocument extends indexImage, mongoose.Document {}

// this still gets an error:
Error:(105, 22) TS2430:Interface 'indexImage' incorrectly extends interface 'Document'.
  Types of property 'id' are incompatible.
    Type 'number' is not assignable to type 'string | undefined'.

```

**Comment by simonxca** [comment]
Yes, if you change to:
```js
interface PenStroke {
    color: any;
}
```
Then you can't do:
```js
interface Square extends Shape, PenStroke {
    sideLength: number;
}
```
Because the type of the color property has to be identical.
```js
export interface indexImage extends mongoose.Document{
    name: string,
    author: string,
    width: number,
    height: number,
    id: number,
    format: string,
    url: string,
    type: "dislike" | "like" | "temp",
}
```
Is correct, but you'll need to wait for:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21856
to be merged.

**Comment by maicss** [comment]
It solve the problem, but I want know why mongoose keeps key `id`, not `__id` or `__mid` something.

And,  will you help me with the [stackoverflow](https://stackoverflow.com/questions/47384420/mongoose-return-document-format-with-typescript) question? I will very appreciate it.
Thanks.

**Comment by simonxca** [comment]
Does:
```js
export interface summary extends mongoose.Document {
    all: number,
    [tag: string]: number
}
```
Work?

**Comment by maicss** [comment]
No, still the same error.
My Macbook pro's screen crashed this weekend, so I response late. 
<del>$800, it kills me</del>

**Comment by simonxca** [comment]
Hmm unfortunately I think you'll have to do:
```ts
interface summary extends mongoose.Document {
    all: number;
    [tag: string]: any;
}
```
or
```ts
interface summary extends mongoose.Document {
   all: number;
   tags: {
     [tag: string]: number;
   }
}
```

**Comment by maicss** [comment]
emmm...my data is:
```json
{
  all: 11,
  '20171111': 10
}
```
first looks like you write nothing, right?
second is wrong.

![image](https://user-images.githubusercontent.com/9784767/33594709-f29c6cc6-d9cf-11e7-8d92-31630f0302ad.png)

**Comment by simonxca** [comment]
Well the first one will avoid the error. The second one is just a suggestion. If you can't change your data model, then it won't work.

Maybe:

```ts
type summaryDoc = summary & mongoose.Document;
mongoose.model<summaryDoc>(...);
```

**Comment by maicss** [comment]
I give up...just use `any`.

Thank you very much!!

**Comment by flisky** [comment]
@simonxca, any chance we can get `deleteOne` & `deleteMany` & others in ? Thanks!
