### ISSUE TITLE
Ambiguous overloads for `toJS` function cause compile errors

### ISSUE THREAD

**Issue by craxal** [DefinitelyTyped/DefinitelyTyped#21602]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/knockout.mappings` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov

Version 2.0.30 introduced a pair of ambiguous type declarations for the `toJS` function:
```ts
toJS<T>(rootObject: KnockoutObservableArray<T>|T, options?: KnockoutMappingOptions): T[];
toJS<T>(rootObject: KnockoutObservableType<T>|T, options?: KnockoutMappingOptions): T;
```
The ambiguity arises when `rootObject` is of type `T`, in which case only the return types of the overloads distinguish the two. Typescript has no way of determining which overload is the correct one (although I think it just goes with the first one).

**Comment by ffMathy** [comment]
This was also reported in #23015 and has been resolved with two separate PRs that have been referenced in that PR.

**Comment by ffMathy** [comment]
It should be resolved now. It is no longer ambiguous.

**Comment by ltlombardi** [comment]
@craxal , This has been fixed. Could you close this issue?
