### ISSUE TITLE
TS2403: @types/node -- Variable 'require' must be of type 'any', but here has type 'NodeRequire'.

### ISSUE THREAD

**Issue by AnassL** [DefinitelyTyped/DefinitelyTyped#21605]
Hello, I have migrated my app from Angular 4 to Angular 5. Now it stops loading and gives this error:

```
[HMR] bundle has 2 errors
client.js:176 [at-loader] ./node_modules/@types/node/index.d.ts:117:13 
    TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'any', but here has type 'NodeRequire'.
[at-loader] ./node_modules/@types/webpack-env/index.d.ts:187:13 
    TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'any', but here has type 'NodeRequire'.
```

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @parambirs @tellnes @WilcoBakker @octo-sniffle @smac89 @Flarna @mwiktorczyk @wwwy3y3 @DeividasBakanas @kjin @alvis @OliverJAsh

I am using:
Angular CLI: 1.5.0
Node: 8.9.0
OS: win32 x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/ cdk: 5.0.0-rc0
@angular/ cli: 1.5.0
@angular/ material: 5.0.0-rc0
@angular-devkit/ build-optimizer: 0.0.33
@angular-devkit/ core: 0.0.20
@angular-devkit/ schematics: 0.0.35
@ngtools/ json-schema: 1.1.0
@ngtools/ webpack: 1.8.0
@schematics/ angular: 0.1.3
typescript: 2.6.1
webpack-hot-middleware: 2.19.1
webpack-merge: 4.1.0
webpack: 3.6.0

and

    "@types/chai": "4.0.4",
    "@types/jasmine": "~2.6.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "3.2.12",
    "@types/node": "8.9.0",
    "@types/webpack-env": "1.13.1",

I have checked a similar question here: [(DefinitelyTyped/DefinitelyTyped #18646)](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18646), and also I could not find help to solve this issue in stackOverflow, please advise what to do.
Thank you.

**Comment by andy-ms** [comment]
The newest version of TypeScript should be able to  give you the locations of both variable declarations (Microsoft/TypeScript#19339).

**Comment by Sami-L** [comment]
is there a solution or a workaround awaiting the new version of TypeScript comes ?

**Comment by andy-ms** [comment]
You could use find-all-references, or a text search for `var require`.
When you do find the other declaration, you should probably use an explicit [`"types"`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) setting to exclude that and include only the types you need.

**Comment by Flarna** [comment]
@Sami-L The problem here is most likely not the type of `require` defined in node - it'ss the location where it is defined as `any`. Unfortunately typescript 2.6.1 doesn't telll you this location.
As indicated by andy-ms you could try a nightly build of typescript (typescript@next) or a manual search to find this location.

**Comment by Sami-L** [comment]
@andy-ms @Flarna thank you for you answers,  I have made a manual seach to find a variable defined as 'NodeRequire' as stated in the error message, but found it nowhere.
[The nightly drops](https://github.com/Microsoft/TypeScript/wiki/Nightly-drops) contains two packages, do I need to use the second one ? "Microsoft.TypeScript.MSBuild"
In that page, I have found no instructions related to Visual Studio 2017, and for VS code there are two files in .vscode folder: launch.json and tasks.json but no settings.json. 
Please advise on this.

**Comment by Flarna** [comment]
@Sami-L  For VS 2017 I can't tell much as I haven't used it. In VS code you can select to use the workspace version instead of that one included in VS code. see https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
