### ISSUE TITLE
Xrm.Page is throwing compile time error

### ISSUE THREAD

**Issue by DineshNanayakkara** [DefinitelyTyped/DefinitelyTyped#21641]
Hi,

I am new to use this script. I followed the video tutorial as per the page (http://delegateas.github.io/Delegate.XrmDefinitelyTyped/getting-started.html) but I am getting a compile error on Page property of Xrm.Page.

![image](https://user-images.githubusercontent.com/11023983/33003892-b99ed89c-ce11-11e7-9e25-40278d899202.png)

Could you please point me out what could be the error. Thanks.

@daryllabar

**Comment by daryllabar** [comment]
How did you pick me to tag in this?

**Comment by DineshNanayakkara** [comment]
Hi Daryl,

I found you on this thread. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13514 plus the issue template mentioned to tag any authors. Sorry for any inconvenience caused.

**Comment by daryllabar** [comment]
No inconvenience, just curious on how you picked me.  Sorry I can't help.  Good luck!
