### ISSUE TITLE
[@types/moment-timezone] Moment types interfering with Moment-timezone types

### ISSUE THREAD

**Issue by WilCodeBoer** [DefinitelyTyped/DefinitelyTyped#21646]
- Authors: @michelsalib

Greetings Michel!

### Edit
I documented the issue a bit wrong. my colleague will ask it in a better fashion
See his reply for a better explenation

Any chance something could be done about this?

Best regards, 
WilCodeBoer

**Comment by michelsalib** [comment]
Hello,

That's weird, we already have a series of tests that should cover your scenario: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/moment-timezone/moment-timezone-tests.ts

Can you provide a examples that leads to the errors you have ?

**Comment by laurensdijkstra** [comment]
Hi, @WilCodeBoer and I work on the same team so I hope I can create some more clarity on the issue.

We use both `moment` and `moment-timezone`. `moment` has a builtin d.ts; `moment-timezone` we installed via npm. 

Both definitions declare an `interface Moment`. So when using `Moment` as a type in our code we get `Type 'moment.Moment' is not assignable to type 'Moment'.` as it seems Typescript sometimes loads the `moment.Moment` definition and other times loads the `moment-timezone.Moment` definition, which do not match.

When ctrl+clicking on the definition of the type `Moment` in our code we sometimes end up in `moment`'s d.ts and other times in `moment-timezone`'s d.ts.

**Comment by michelsalib** [comment]
Yes what you need to do is to only use
`import * as moment from "moment-timezone"`

**Comment by laurensdijkstra** [comment]
I'm sorry but it seems that our issue is related to antd timepicker. Thanks for your help!

**Comment by michelsalib** [comment]
No problem, I think this can be clsoed then ;)
