### ISSUE TITLE
@types/react createElement not typed correctly.

### ISSUE THREAD

**Issue by lifeiscontent** [DefinitelyTyped/DefinitelyTyped#21651]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz

When using the createElement API you should be able to pass a `ReactElement` to it but the current type definition says it's invalid to do so. Also looks like there is a todo in the definition:

```// TODO: generalize this to everything in `keyof ReactHTML`, not just "input"``` but it seems unrelated.

Any ideas on how to fix this?

Example:

```jsx
import Link from 'next/link';

const Button = ({component = 'button', children, ...props}) => {
  return React.createElement(component, props, children);
}

const Page = (props) => {
  return (
    <div>
      <Button component={Link} to="/foo">Next Page</Button>
      <Button onClick={() => alert('reset')}>Reset</Button>
    </div>
  );
}

```

**Comment by steida** [comment]
It must leverage ReactDOM type. This slightly unrelated code shows how.

```ts
interface EditorReactDOMElementFactory<T, P> extends EditorElement {
  readonly tag: T;
  readonly props?: P;
  readonly children?: readonly (EditorReactDOMElement | string)[] | undefined;
}

interface EditorReactDOMElementDIV extends EditorElement {
  readonly tag?: 'div';
  readonly props?: ReturnType<ReactDOM['div']>['props'];
  readonly children?: readonly (EditorReactDOMElement | string)[] | undefined;
}

/**
 * EditorReactDOMElement has props the same as ReactDOM. If tag is ommited, it's DIV.
 */
export type EditorReactDOMElement =
  | EditorReactDOMElementDIV
  | $Values<
      {
        [T in keyof ReactDOM]: EditorReactDOMElementFactory<
          T,
          ReturnType<ReactDOM[T]>['props']
        >;
      }
    >;

```
