### ISSUE TITLE
@types/puppeteer: ResourceType should be lower-case?

### ISSUE THREAD

**Issue by iwinux** [DefinitelyTyped/DefinitelyTyped#21667]
## Meta

- [x] I tried using the `@types/puppeteer` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @marvinhagemeister

## Problem

In `@types/puppeteer`, `enum ResourceType` is defined as:

```typescript
export type ResourceType =
  | "Document"
  | "Stylesheet"
  | "Image"
  | "Media"
  | "Font"
  | "Script"
  | "TextTrack"
  | "XHR"
  | "Fetch"
  | "EventSource"
  | "WebSocket"
  | "Manifest"
  | "Other";
```

But in https://github.com/GoogleChrome/puppeteer/commit/c3fb3671480af81b24cb9902e5e8912764e493d1, these types are all converted to lower-case - should `@types/puppeteer` get updated as well?

**Comment by marvinhagemeister** [comment]
Thanks for spotting this 👍  Looks like the puppeteer developers keep us on our toes. Since this is a easy minor change, would you be willing to make a PR?
