### ISSUE TITLE
404 Not Found @types/node

### ISSUE THREAD

**Issue by clementino36** [DefinitelyTyped/DefinitelyTyped#21704]
- [X] I tried using the `@types/xxxx` package and had problems.
  - Authors: @DefinitelyTyped @parambirs @WilcoBakker @tellnes @octo-sniffle @smac89 @Flarna

Hi, when running `npm install`, i get a `404 Not Found` error for `@types/node@^7.0.48`. 
I've seen similar issues where people say the package might've been temporarily unavailable, is that the case right now ? I did an `npm install` of the exact same project a month ago, everything was fine and nothing changed on my side since then.
I made sure to run `npm set registry https://registry.npmjs.org/`, no luck.
`node -v` v8.1.2
`npm -v` 5.4.2

Thanks

**Comment by lilred** [comment]
`npm show @types/node@* version` does print `7.0.48`, so this is pretty odd o.O

**Comment by Flarna** [comment]
I tried this locally and it worked. So maybe some temporary issue on NPM.
In general such error look more like a NPM issue then an issue in the typings.

**Comment by clementino36** [comment]
I guess it was just a temporary issue, everything works fine today... Thanks anyway!
