### ISSUE TITLE
[@types/recharts] error TS2604: JSX element type 'Line'...

### ISSUE THREAD

**Issue by ljwagerfield** [DefinitelyTyped/DefinitelyTyped#21702]
Authors: @mthmulders @rapmue @royxue 
Versions tests: `1.0.0` and `1.0.6`

I receive the following errors for all types (`Line`, `LineChart`, `XAxis`, etc.)...
```
error TS2604: JSX element type 'Line' does not have any construct or call signatures.
```

I've tried with the following versions of TypeScript (with webpack `2.3.3`):
```
    "ts-loader": "2.0.3",
    "typescript": "2.3.2",
```
and
```
    "ts-loader": "3.1.1",
    "typescript": "2.6.1",
```

Any ideas what might be the cause & solution?

**Note:**

If I edit the `index.d.ts` file like so:
```
export class XAxis extends React.Component<XAxisProps> { }
```
to:
```
export class XAxis extends React.Component<XAxisProps, {}> { }
```
for each of the types, then it works. It seems that whatever setup I have requires the `State` template parameter to be provided.

**Comment by mthmulders** [comment]
Thanks for the report. What version of React are you using? What version of `@types/react` are you using?

**Comment by ljwagerfield** [comment]
```
"@types/react": "15.0.23",
"@types/react-dom": "15.5.0",
"react": "15.5.3",
"react-dom": "15.5.3",
```

**Comment by mthmulders** [comment]
First of all, sorry for the enormous delay!

I did some digging and found that the second type parameter (`{}` for the component's state) used to be there, but was removed in #19063. I can't really understand why that commit removed it. @andy-ms, maybe you can shed some light on this?

Also, I can't remember that the bot asked me to review #19063, either, although I wrote the initial type definitions for Recharts so I usually get notified...

**Comment by andy-ms** [comment]
That commit removed the type argument because the type parameter has a default value of `{}` already. That might be causing problems if you're not on `typescript@2.3` or above, could you try testing with `typescript@next`?

**Comment by mthmulders** [comment]
Thanks for the explanation, @andy-ms! If I understand correctly from the original report, the problem occurs with `typescript@2.3.2` as well as `typescript@2.6.1`.

But... the React typings are `@types/react-dom@15.5.0`; the default value of `{}` seems to be introduced with 3c9eba9d.

@ljwagerfield, could you try with a newer version of React and typings and see if that resolves the issue at hand?

**Comment by ljwagerfield** [comment]
Updating `@types/react-dom` fixes the issue 👍

**Comment by mthmulders** [comment]
OK, awesome, I suppose this issue can be closed then.
