### ISSUE TITLE
[@types/mongodb] Should export interface DBRef

### ISSUE THREAD

**Issue by FallingSnow** [DefinitelyTyped/DefinitelyTyped#21717]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mongodb` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT

index.d.ts should export [DBRef](http://mongodb.github.io/node-mongodb-native/2.2/api/DBRef.html) interface.

**Comment by CaselIT** [comment]
It should probably be implemented in the [bson typings](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bson) since it's implemented there. Then export it also from the mongodb typings

I'll try to create a pr for this

**Comment by CaselIT** [comment]
Added a PR that should address this issue
