### ISSUE TITLE
[@types/lozad] Should export the Observer interface

### ISSUE THREAD

**Issue by chaucerbao** [DefinitelyTyped/DefinitelyTyped#21789]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/lozad` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @plantain-00

I'm creating a `lozad()` instance in some module A, and passing the resulting `Observer` to functions in modules B/C/D. In order to correctly type those function parameters, I need to reference the `Observer` type definition.

Should the `Observer` definition be exported to accomplish this?

**Comment by plantain-00** [comment]
Moving type `Option` and `Observer` into the namespace should work, then you can access them by `lozad.Observer`.
PR is welcome, and if you cannot do this, tell me, I will do this when I have time.

**Comment by chaucerbao** [comment]
Seems to work for me.  Check it out.
