### ISSUE TITLE
"@types/SimpleBar/index.d.ts is not a module" 

### ISSUE THREAD

**Issue by RyRy79261** [DefinitelyTyped/DefinitelyTyped#21796]
I attempted to make a pull request but couldn't pass the tests. 

I can only get this to work when I add the following to line 8 & 9: 
export = SimpleBar;
export as namespace SimpleBar;

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu

**Comment by ParadiseCircus** [comment]
@leonard-thieu any plans to maintain the npm?

**Comment by leonard-thieu** [comment]
@RyRy79261 could you post a repro of what you're trying to accomplish?

**Comment by RyRy79261** [comment]
@leonard-thieu the reason for this request was that I could not get the type to parse or be imported properly without modification, I was lead to manually adding the fix to the project rather than including this in the packages.json.  I ended up using a different solution.

**Comment by ParadiseCircus** [comment]
Will you be updating the npm with @RyRy79261 fix?

It's needed so the file is recognized as a module.
