### ISSUE TITLE
Developer workflow to locally try a @types/package patch before submitting PR

### ISSUE THREAD

**Issue by rosskevin** [DefinitelyTyped/DefinitelyTyped#21816]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version (2.6.2) of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

My issue is related to the developer setup to try before PR'ing a patch.  I have made updates to `react-autosuggest`, but I do not want to submit a PR before simply trying with my real codebase to ensure I have found everything.  I am also working on a new module for the `found` library.

In my case, I have tried to add an additional local directory to`typingsRoot` in the `tsconfig.json`  but it has no effect. 

e.g.

```json
{
  "compilerOptions": {
    "typeRoots": [
      "node_modules/@types",
      "typings-root"
    ]
  }
}
```

I assume this is a configuration error on my part, but I wanted to ask how others are developing/updating/trying out local modules before submitting them.

Here is a reduced test case: 
https://github.com/rosskevin/local-definitely-typed-dev

This repo contains:
- copy of `@types/react-autosuggest` in `typings-root`
- typical project setup
- `index.tsx` is a copy of `typings-root/react-autosuggest/react-autosuggest-tests.tsx`

`typings-root/react-autosuggest/react-autosuggest-tests.tsx` typechecks in my editor without error, while `src/index.tsx` (a copy of the tests) fails on import with

```
Error:(4, 30) TS7016:Could not find a declaration file for module 'react-autosuggest'. '/Users/kross/projects/local-definitely-typed-dev/node_modules/react-autosuggest/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-autosuggest` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-autosuggest';`
```

**Comment by rosskevin** [comment]
What I did so far was to add a fake `package.json` in `DefinitelyTyped/types/react-autosuggest as 

```json
{
  "name": "@types/react-autosuggest",
  "types": "index.d.ts"
}
```

Then within that directory, `yarn link`.  Back in my project, `yarn link react-autosuggest` to use the package.

Then, before submitting the PR and before running lint, delete the `package.json`.

This seems a bit like I've got quite a bit of overhead just to update a type definition.  If that's the way it is, so be it, I just wanted to know if there is an easier way.

**Comment by ericanderson** [comment]
Shameless plug, I wrote an article on this... 

https://ericlanderson.com/using-custom-typescript-definitions-with-ts-2-x-3121db84015d

**Comment by chrisgervang** [comment]
Thanks @ericanderson, that worked for me. 

A couple tips to point out for the next person:

1. Mirror the folder / file structure of `@types` in the `types` folder you make. This works as expected, and later you can copy/paste straight into definitelytyped.
2. Don't wrap your exports in `declare module 'npm-package' { ... }`, simply export stuff on the top level.
3. Don't use the `/// <reference path="../leaflet/leaflet.d.ts" />` syntax anymore, just import the package to access types: `import * as Leaflet from 'leaflet'`

**Comment by WestonThayer** [comment]
I found this method much friendlier: https://stackoverflow.com/questions/44796039/how-can-i-write-and-use-custom-declaration-files-that-dont-exist-on-definitelyt

It let's you `npm install` a local package instead of modifying your `tsconfig.json`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
