### ISSUE TITLE
Definition request for angular-srtrap

### ISSUE THREAD

**Issue by yogeshp** [DefinitelyTyped/DefinitelyTyped#2181]
Hi,
I need definition file for angular-strap,

http://mgcrea.github.io/angular-strap/

Could you please provide me this ?

-Thanks,
Yogesh

**Comment by samherrmann** [comment]
I started working on this.

**Comment by ChrisTorng** [comment]
How is it now? Anything that can share with us?

**Comment by samherrmann** [comment]
Not yet, sorry about that! I had a few other projects that kept me from finishing this up. I will try to finish it by next week.

**Comment by stevehipwell** [comment]
+1 for this!

**Comment by samherrmann** [comment]
Ok, I have a "alpha" version on my DefinitelyTyped fork: samherrmann/DefinitelyTyped#1

Can some of you review it and/or try it out before I create a pull request on the DefinitelyTyped repo? Thanks!

@yogeshp 
@ChrisTorng 
@stevehipwell

**Comment by lightswitch05** [comment]
@samherrmann any updates on this?

**Comment by samherrmann** [comment]
@lightswitch05 unfortunately no. I haven't received any feedback from anyone so I can't guarantee that the definitions are accurate. I haven't had the time to exercise the definition in a project myself either to at least get some "mileage" on them and gain confidence.

**Comment by vvakame** [comment]
by #7061 :+1:
