### ISSUE TITLE
Installing @types/mocha causes every compile thereafter to fail

### ISSUE THREAD

**Issue by rstuart** [DefinitelyTyped/DefinitelyTyped#21861]
@andy-ms

I'm a complete newbie at this, but it looks like installing @types/mocha causes every compile to fail thereafter.

    $ mkdir xxx
    $ cd xxx
    $ npm init
    $ npm install --sav-dev typescript @types/mocha
    $ >x.ts    # creates empty file
    $ node_modules/.bin/tsc x.ts && echo success
    error TS2688: Cannot find type definition file for 'mocha'.
    $ # Add "types": "lib/mocha.d.ts" to @types/mocha/package.json
    $ sed -i 's#"devDependencies": {#"types": "lib/mocha.d.ts", &#' node_modules/@types/mocha/package.json 
    $ node_modules/.bin/tsc x.ts && echo success
    success
    $

**Comment by andy-ms** [comment]
This doesn't reproduce for me when I follow those instructions -- `node_modules/.bin/tsc x.ts` succeeds with no error. (Since I'm on windows I ommitted the `&&` part and used `echo "" > x.ts` instead of just `>x.ts`.)

**Comment by rstuart** [comment]
Same problem as the other bug I reported.  I'm using npm from Debian Stable.  It works with the current version of Node.  Thanks for your help.

Again, dependency on npm specifying the minimum version it works with would have avoided this bug report.
