### ISSUE TITLE
npm install @types/node: remote repository git@github.com:types/node doesn't exist

### ISSUE THREAD

**Issue by rstuart** [DefinitelyTyped/DefinitelyTyped#21860]
@andy-ms @DeividasBakanas

Following the instructions on https://www.npmjs.com/package/@types/node:

    npm install --save @types/node

Gives the error message: _git clone git@github.com:types/node fatal: Could not read from remote repository_.

All other installs work as expected.  Full [npm-debug.log](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1517213/npm-debug.log) is attached.

**Comment by andy-ms** [comment]
This works for me, you probably have some setting configured that affects installing packages. Installing `@types/node` shouldn't try accessing anything from github.

**Comment by rstuart** [comment]
You are right.  I'm using npm from Debian Stable, and it works with the current version.

A dependency on npm specifying the minimum version it works with would have avoided this bug report.
