### ISSUE TITLE
@types/croppie @types to library inconsistency

### ISSUE THREAD

**Issue by tlawandi** [DefinitelyTyped/DefinitelyTyped#21928]
HI @andy-ms, @sarunint, @dklmuc 

I tried using the `@types/croppie` I get the following issue at runtime

Uncaught TypeError: croppie_1.default is not a constructor.

**Import:** 
import  Croppie from "croppie";

**Usage:**
this.croppie = new Croppie(this.avatarImage,
                {
                    viewport: { width: 256, height: 256, type: this.viewPortType },
                    boundary: { width: 410, height: 410 },
                    showZoomer: true,
                });

In order to get around this problem I used the following.

**Import:** 
import * as Croppie from "croppie";

**Usage:**
this.croppie = new Croppie.Croppie(this.avatarImage,
                {
                    viewport: { width: 256, height: 256, type: this.viewPortType },
                    boundary: { width: 410, height: 410 },
                    showZoomer: true,
                });

This works fine at runtime but i get the following error during typescript compilation phase

error TS2339: Property 'Croppie' does not exist on type 'typeof ".../node_modules/@types/croppie/index"'.
[14:31:25] gulp-notify: [Error running Gulp] Error: ...\avatar-modal.ts(43,40): error TS2339: Property 'Croppie' does not exist on type 'typeof ".../node_modules/@types/croppie/index"'.

**Comment by tlawandi** [comment]
I found that within the .d.ts file if i convert 
export default class Croppie

to 

export class Croppie 

Fixes the issue but imports will need to change

**Comment by sarunint** [comment]
Currently, this is how I use croppie:

`import Croppie from 'croppie';`

Will investigate into this ASAP

**Comment by deependhamecha** [comment]
I am having similar kind of issue. I am getting this error : 
```
core.js:1427 ERROR TypeError: croppie_min_js_1.Croppie is not a constructor
```
on 
```
import Croppie from 'croppie';
```
as well as on
```
import { Croppie } from 'croppie';
```

Any help will be greatly appreciated.

**Comment by sarunint** [comment]
Hi all,

The current definition file is incorrect. I will submit a PR soon.

**Comment by sarunint** [comment]
Hi @tlawandi and @deependhamecha,

The PR has been merged. Could you check if it resolves the issue?

**Comment by tlawandi** [comment]
Hi @sarunint,

Thanks for you're effort on this.

with the new definitions the following line is now failing at run time

            this.croppie = new Croppie(this.avatarImage, {
                viewport: { width: 256, height: 256, type: this.viewPortType },
                boundary: { width: 410, height: 410 },
                showZoomer: true
            });

with the error 

Uncaught TypeError: Croppie is not a constructor

Not sure why this is failing now. So unfortunately this still doesn't work for me.

@mhegazy can i re-open this issue

**Comment by andy-ms** [comment]
@tlawandi Could you provide a complete example? How are you importing it?

**Comment by sarunint** [comment]
Hmm, I dig into source code of Croppie and found that it has inconsistency exporting the module. Will open an issue to Croppie's repository.

**Comment by sarunint** [comment]
I've open a PR at Foliotek/Croppie#452. If that PR is merged, the definition file should (once again) be changed too.

**Comment by mkurcius** [comment]
That PR is merged :+1:

**Comment by sarunint** [comment]
This is still blocked on Foliotek/Croppie#470.

In couple of hours, I'll take a look!

**Comment by sarunint** [comment]
Waiting for Foliotek/Croppie#479 to be merged.

After it have been merged, it should work without changes on this repository.

**Comment by mkurcius** [comment]
Nice! Thank u very much :smile:

**Comment by atrauzzi** [comment]
Looking forward to this being updated!  Is it ready yet?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
