### ISSUE TITLE
[@types/react-native] ScrollViewPropertiesIOS doesn't have the "contentInsetAdjustmentBehavior" property

### ISSUE THREAD

**Issue by jegumhon** [DefinitelyTyped/DefinitelyTyped#21935]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @huhuanming @iRoachie @timwangdev @kamal 

If you do not mention the authors the issue will be ignored.

I'm currently using '@types/react-native@0.49.5'.
But there's no property like the 'contentInsetAdjustmentBehavior' of UIScrollView.
The property is added since iOS 11 is launched.

The react-native@0.49.5 npm included the property.

And I checked the file "index.d.ts" of the RN@0.50 and over.
They also doesn't include the property!!

As a result, I got this error message...
<img width="1146" alt="2017-12-04 6 00 30" src="https://user-images.githubusercontent.com/6110163/33544171-0d4eb97e-d91d-11e7-94d5-e37c03450d58.png">

**Comment by alloy** [comment]
Thanks for taking the time to file a ticket. However, seeing as this doesn’t require any discussion, please send a pull-request that adds the property instead.

**Comment by jegumhon** [comment]
O.K! I'll send a pull-request of this soon!!
