### ISSUE TITLE
[@types/mongoose] HookSyncCallback

### ISSUE THREAD

**Issue by Xenya0815** [DefinitelyTyped/DefinitelyTyped#21938]
@simonxca changed at his pull request ( https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10084 ) the defintion of the pre method from 

    pre(method: string, fn: HookSyncCallback, errorCb?: HookErrorCallback): Schema;

to

    pre(method: string, fn: (next: (err?: NativeError) => void) => void, errorCb?: (err: Error) => void): this;

The old HookSyncCallback was defined as:

    (next: HookNextFunction, ...hookArgs:any[]): any

With the old definition I could add the document as second parameter at the `pre('init)` middleware. I have to use it because the `this` object differs from the passed document object.

**Comment by simonxca** [comment]
Do you have example code that leads to an error that I can use to test?

**Comment by Xenya0815** [comment]
I use it at the moment in an addon component which adds an additional feature to my schema. I tried to strip it down so that it is as simple as possible:

    import {NativeError, Schema} from 'mongoose';

    export default function(schema: Schema) {
      schema.pre('init', function(this: Document, next: (err?: NativeError) => void, data: any): void {
        data.name = 'Hello world'; // normally I change something at the raw data but for the simple example that should be enough 
      });
    }
