### ISSUE TITLE
[@types/chai] tslint issue Property 'rejectedWith' does not exist on type 'Assertion'

### ISSUE THREAD

**Issue by liyinsg** [DefinitelyTyped/DefinitelyTyped#21934]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @segayuu

The following unit test was working fine but with commit https://github.com/DefinitelyTyped/DefinitelyTyped/commit/92728fb5e33abc146606a328574e02c48f6e1637, I got error TS2339: Property 'rejectedWith' does not exist on type 'Assertion'.
```
import {assert, expect, use} from "chai";
import chaiAsPromised = require("chai-as-promised");
  before(async () => {
    use(chaiAsPromised);
  });
    it("xxxx",  () => { expect(yyy).to.be.rejectedWith(Error); });
```

After add back declare module the lint issue is gone,
```
declare module "chai" {
    export = chai;
}
```

**Comment by KurtGokhan** [comment]
I think #21924 should fix this.

**Comment by liyinsg** [comment]
Thanks

**Comment by mceachen** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21879#pullrequestreview-80716086
