### ISSUE TITLE
@types/atom: Point.fromObject and Range.fromObject

### ISSUE THREAD

**Issue by lierdakil** [DefinitelyTyped/DefinitelyTyped#21963]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @GlenCFL 

So, I found one more problem, which is more annoying than simply missing definitions. `Point` has two definitions for `fromObject`:
```typescript
    /**
     *  Create a Point from an array containing two numbers representing the
     *  row and column.
     */
    static fromObject(object: [number, number]): Point;

    /** Create a Point from an existing object which implements PointLike. */
    static fromObject(object: PointLike, copy?: boolean): Point;
```

neither of which allows calling `Point.fromObject(object: PointCompatible)`. From a quick look, it should be similar to `Range.fromObject`, i.e. something like this:

```typescript
static fromObject(object: PointCompatible, copy?: boolean)
```
but I'm not entirely sure.

**Comment by GlenCFL** [comment]
I think the original intention was to limit users to only providing the copy parameter in contexts where it mattered, which this doesn't do correctly either.

I'll make a PR later to fix this if either you or @smhxx do not.
