### ISSUE TITLE
@types/atom: TextEditor.addCursorAtBufferPosition accepts second argument

### ISSUE THREAD

**Issue by lierdakil** [DefinitelyTyped/DefinitelyTyped#21964]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @GlenCFL 

`TextEditor.addCursorAtBufferPosition` accepts second argument, the same as `Cursor.setBufferPosition`.

**Comment by GlenCFL** [comment]
Mentioning @smhxx as well.
