### ISSUE TITLE
question: how to reference external type that are not part of Def typed

### ISSUE THREAD

**Issue by Hotell** [DefinitelyTyped/DefinitelyTyped#22004]
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

  cc: @DanielRosenwasser 

After recent events on skatejs repo ( removal of all type definitions ), I'm working on PR to make them available via DefinitelyTyped. During this I've got stuck on various things, which I didn't find answer to and which should be included in Readme of this repo after resolving ( I'll submit PR)

## 1.
- type definition library has a dependency on other project which types are bundled with npm package, so I cannot import it within DT

example ( skate tests uses preact, preact types are bundled with preact npm package)
```ts
import {h} from 'preact'
import {withComponent} from 'skatejs'

const Component = withComponent()

class Test extends Component {
  render(){
    return <div>Hello</div>
  }
}
```

**UPDATE**

I found that I can explicitly add `package.json` with dependencies, just not sure if you run npm install within type defs folders, so then bundled types are resolved correctly

## 2.

- skate renderers are published under `@skatejs/` namespaces, where should I put those within definitely typed ?

One solutions came up my mind, just want to double check if my assumptions are correct:
- create `types/@skatejs` with all existing renderers  folders, so the outcome structure will look like:
```
types/
  -/@skatejs
      -/ preact-renderer
         -/ index.d.ts
      -/ react-renderer
         -/ index.d.ts
      -/ lit-html-renderer
         -/ index.d.ts
```

**UPDATE**

So I found this I found this https://github.com/DefinitelyTyped/DefinitelyTyped#what-about-scoped-packages 

that means that I have to create 3 types like following:

```
types/
  -/skatejs__preact-renderer
         -/ index.d.ts
  -/skatejs__react-renderer
         -/ index.d.ts
  -/skatejs__lit-html-renderer
         -/ index.d.ts
```

Thanks

**Comment by silkentrance** [comment]
what about a .d.ts that 

```
module "@skatejs/preact-renderer" {
// add missing typings here...
}
```

**Comment by Hotell** [comment]
yeah I wanted to do that, but I think that's not valid  ( to have multiple modules within one file, but correct me if I'm wrong. thx

**Comment by silkentrance** [comment]
what hinders you from trying? AFAIK this is exactly what typescript supports.

**Comment by BehindTheMath** [comment]
I'm having a similar issue to (1) in the OP, but in the definitions themselves, not tests, and adding a package.json doesn't remove the dtslint errors.

I'm writing type definitions for vue-model, which is a Vue plugin. Since it augments Vue, I'm trying to import Vue, as described [here](https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins):
```
import Vue from "vue";
```
but I get an error: `TypeScript@next compile error: Cannot find module 'vue'.`
