### ISSUE TITLE
react-router 3.0.11 dependency on history 3.2.1 breaks with newer TypeScript

### ISSUE THREAD

**Issue by MichaelTontchev** [DefinitelyTyped/DefinitelyTyped#22046]
- [ x] I tried using the `@types/xxxx` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @Grmiade @sandersn @johnnyreilly 

I recently updated from TS 2.4 to 2.6. When I did so, my react-router, which has types with version 3.0.11 threw an error when building because of some outdated syntax in history v 3.2.1.

`TypeScript error: node_modules/@types/history/lib/actions.d.ts(5,16): Error TS2714: The expression of an export assignment must be an identifier or qualified name in an ambient context.`

Can we update the react-router typings to point to history v 3.2.2, where the issue is fixed? I don't see a package.json pointing to the dependency here...

**Comment by nicolashemonic** [comment]
Hi,

I experience the same issue:

`node_modules/@types/history/lib/actions.d.ts(5,16): error TS2714: The expression of an export assignment must be an identifier or qualified name in an ambient context.`

Can you fix history definition ?

Thanks !

**Comment by sandersn** [comment]
#19847 was supposed to fix this. Can you find out if you have this fix by opening `node_modules/@types/history/lib/actions.d.ts` and making sure that sure that its content is:

```ts
export const PUSH: string;
export const REPLACE: string;
export const POP: string;

declare const defaultExport: {
    PUSH: string,
    REPLACE: string,
    POP: string,
};
export default defaultExport;
```

**Comment by MichaelTontchev** [comment]
That was not what history 3.2.1 had. It instead had the export and the declaration merged, which is a syntax error. 3.2.2 fixes this, but the typings for react router 3.0.11 have history 3.2.1 as the dependency, which is what I was pointing out :)

**Comment by MichaelTontchev** [comment]
If I manually install history 3.2.2, it works fine. Just the dependencies for the react router typings need to be updated.

**Comment by sandersn** [comment]
That's weird. When I do a fresh `npm install @types/react-router`, I get `@types/history` at 3.2.2, not 3.2.1 -- `@types/react-router/package.json` specifies that it depends on `@types/history: "^3"`. Are you pinned to a specific version of react-router?

**Comment by MichaelTontchev** [comment]
And what version of @types/react-router does that install for you?

I'm running 3.0.11, which I think is the latest in the 3.x series. Am I wrong?

**Comment by MichaelTontchev** [comment]
That should say version of ```@types/react-router```

**Comment by sandersn** [comment]
No, looks like 3.0.13:

```json
{
  "_from": "@types/react-router@3",
  "_id": "@types/react-router@3.0.13",
```

**Comment by MichaelTontchev** [comment]
Ahhh, I see now. I had listed out all versions in my powershell but didn't realize that they're sorted by release date, not by version, and the newer 3.x versions were hiding between the 4.x versions.

Thanks for catching this silly mistake of mine!

**Comment by sandersn** [comment]
arrgghh `npm`! :fist_right:  :sweat_drops:
