### ISSUE TITLE
Jasmine NuGet Package Shiz

### ISSUE THREAD

**Issue by Steve-Fenton** [DefinitelyTyped/DefinitelyTyped#2207]
Hello team awesome!

The Jasmine NuGet package for Jasmine type definitions downloads both the 1.3 version and the 2.0 version - this means you get an error in Visual Studio because they both define a lot of the same stuff.

What do we need to do to split out the versions... do they need to be separate definitions so they can each have their own NuGet package?

At the moment, you have to install the NuGet package and then delete the older version in order to compiler your application.

Much love!

Steve

**Comment by jakebailey** [comment]
Many many years on, I don't believe this issue to be relevant anymore. DT has the ability to manage multiple versions of packages.
