### ISSUE TITLE
Implicit anys in @types/amcharts since 0.0.43

### ISSUE THREAD

**Issue by ldrick** [DefinitelyTyped/DefinitelyTyped#22121]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/amcharts` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aleksey-bykov

#21960 seems to introduce Amcharts.Gauge and so on.
Some methods now produce errors with tsc strict mode having implicitly the any type.

**Comment by marceloemanoel** [comment]
The issue is also reproducible with the latest version `0.0.44`.

**Comment by ldrick** [comment]
Hi there, I'll come back with appropriate PR.
