### ISSUE TITLE
@types/express - Property 'append' does not exist on type 'Response'

### ISSUE THREAD

**Issue by J6K** [DefinitelyTyped/DefinitelyTyped#22148]
```javascript
import { Request, Response, NextFunction } from 'express';

export const login = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const token = await createTokenForUser(req.user[0].email);
    return res.status(200).append('authorization', token).send('successfully logged in')
  } catch(e) {
    return next(e)
  }
```

.append is a method on the response object, so why does it keep throwing that error?

**Comment by micksatana** [comment]
> res.append() is supported by Express v4.11.0+

I can help with that

**Comment by J6K** [comment]
```javascript
"express": "^4.16.2"
"@types/express": "^4.0.39"
```

Does the type need to be at the version as well? I don't think they have it at 4.1..

**Comment by micksatana** [comment]
@J6K 
I specified 4.11 in the PR type definition header (cannot goes 4.16 yet since I haven't check all functions in 4.16 are supported). 

After the PR approved, you can run `npm update @types/express` to update the package.
