### ISSUE TITLE
Dependents are no longer tested in CI

### ISSUE THREAD

**Issue by Flarna** [DefinitelyTyped/DefinitelyTyped#22172]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

@andy-ms @RyanCavanaugh 

A while ago all dependents have been tested also in CI. This was a pain for node as it resulted in timeouts and unrelated fails as it took too long to test all of them with all typescript version.
To my understanding this was improved via https://github.com/Microsoft/types-publisher/pull/398 to test dependents just with typescript@next.

Now it looks like that dependents are not tested at all anymore. is this intended?
See e.g. https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/316119572?utm_source=github_status&utm_medium=notification

**Comment by andy-ms** [comment]
I was noticing some duplication of dependents yesterday. I'll take a look and see what the cause is. Thanks

**Comment by Flarna** [comment]
Dependents are still not tested. see https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/318002459?utm_source=github_status&utm_medium=notification

**Comment by Flarna** [comment]
Seems like testing dependencies is back - and also unrelated fails and timeouts. see https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/318182029?utm_source=github_status&utm_medium=notification

I ask myself why I reported this :cry:

**Comment by andy-ms** [comment]
We're up to 4007 typings now, so we're running into timeouts again even if testing only with `typescript@next`.
I had a script that looked for packages that provide their own types, so I'll resurrect that and see if we can get rid of some packages.

**Comment by Flarna** [comment]
Is it somehow possible to split the test in to several jobs?
As far as I know the 50 minute timeout is per job not per build (see https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts).
I could imagine something like one job testing dependencies A-K and a second on L-Z...

**Comment by andy-ms** [comment]
That might be possible, but I'd like to look into improving performance as we also run all of the tests in a nightly script that is taking increasingly longer.
