### ISSUE TITLE
@types/i18next-xhr-backend wrong export?

### ISSUE THREAD

**Issue by szszoke** [DefinitelyTyped/DefinitelyTyped#22192]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jamuhl @GiedriusGrabauskas  

I recently tried to use `i18next-xhr-backend` in a TypeScript project and got the following error:
`TypeError: this.backend[fcName] is not a function`

Here is how I'm initializing my i18next instance:
``` TS
import * as i18n from "i18next";
import * as XHR from "i18next-xhr-backend";
import * as reactI18Next from "react-i18next";

const backend: XHR.BackendOptions = {
    loadPath: "{{lng}}",
    parse: data => data,
};

const instance = i18n
    .use(XHR)
    .use(reactI18Next)
    .init({
        backend,
        fallbackLng: "en",
        ns: ["translations"],
        defaultNS: "translations",
        react: { wait: true },
    });

export const translate = reactI18Next.translate("translations");
export interface TranslateProps extends reactI18Next.InjectedTranslateProps {}

export default instance;
```

TypeScript version: 2.6.2
i18next version: 10.2.1
xhr backend version: 1.5.0

The error goes away if I change the type definitions to use default export:
``` TS
// export = I18NextXhrBackend;
export default I18NextXhrBackend;
```
The original JS library also uses a default export. Is there a reason the type definition doesn't?

**Comment by bansalrachita** [comment]
I came across the same issue recently and resolved this by using 
```import XHR from "i18next-xhr-backend";```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
