### ISSUE TITLE
TypeScript bot seems to be a bit rude

### ISSUE THREAD

**Issue by R1ZZU** [DefinitelyTyped/DefinitelyTyped#22221]
Hey guys!

This is most likely my personal preference, but full stop in the end of pull request comment seems a bit rude 😞  

<img width="798" alt="screen shot 2017-12-15 at 5 36 29 pm" src="https://user-images.githubusercontent.com/6261302/34046854-7e84be9a-e1bf-11e7-9787-4934ae020f6f.png">

For example @facebook-github-bot welcomes contributors with `Thank you for your pull request and welcome to our community` and ends his statement with `Thanks!`

Any chance to make @typescript-bot more friendly? 😸

**Comment by leonard-thieu** [comment]
@RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
:hurtrealbad:

**Comment by RyanCavanaugh** [comment]
https://github.com/RyanCavanaugh/dt-mergebot/pull/5/files

**Comment by RyanCavanaugh** [comment]
Feedback welcome on that one

**Comment by ericanderson** [comment]
Lol

**Comment by R1ZZU** [comment]
Wow! Wasn't expecting so fast response, looks great 👍

**Comment by RyanCavanaugh** [comment]
New text should go live within an hour or two 💖
