### ISSUE TITLE
React: Error calling setState with generic intersection type

### ISSUE THREAD

**Issue by nschulze84** [DefinitelyTyped/DefinitelyTyped#22230]
I tried using the `@types/react` package and had problems.

I am getting errors calling setState using an intersection type with version 16.0.30. I did not have these errors with 16.0.27. The commit in question seems to be https://github.com/DefinitelyTyped/DefinitelyTyped/commit/62c2219a6ed6dc34ea969b8c2c87a41d31002660

Minimum code is below:

```
interface TabData<T = () => any> {
    displayName: string;
    data: T;
    disabled?: boolean;
}

interface TabPanelBaseState {
    selectedTab: TabData;
}

abstract class TabPanelBase<TProps, TState> extends React.Component<TProps, TState & TabPanelBaseState> {
    public componentDidMount() {
        this.setState({selectedTab: this.tabs[0]});
    }

    protected abstract tabs: Models.TabData[];
}
```

I am receiving error:
Error:(37, 23) TS2345: Argument of type '{ selectedTab: TabData<() => any>; }' is not assignable to parameter of type '((prevState: Readonly<TState & TabPanelBaseState>, props: TProps) => Pick<TState & TabPanelBaseSt...'.
  Type '{ selectedTab: TabData<() => any>; }' is not assignable to type 'Pick<TState & TabPanelBaseState, "selectedTab"> & Partial<TState & TabPanelBaseState>'.
    Type '{ selectedTab: TabData<() => any>; }' is not assignable to type 'Partial<TState & TabPanelBaseState>'.

I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (2.6.2)
  - Authors: @ericanderson @johnnyreilly

**Comment by natehitchcock** [comment]
I am also seeing this error. It seems the type of the object passed in to setState matches the Pick<T, S> type, but the Partial<T> type isn't being collapsed away. I am only seeing this issues with extended types. ex:

    export interface IState {
        map?: {[key: string]: any};
    }

    export interface IProps {
        system: string;
    }

    class Component<P, S> {
        constructor(props: P, context?: any) { }

        setState<K extends keyof S>(
            state: Pick<S, K> & Partial<S>,
            callback?: () => any
        ): void { }
    }

    export class CharacterCreate<TState extends IState> extends Component<IProps, TState> {
        constructor(props: IProps, state: TState) {
            super(props);
            this.setState({ map: {}}); // ERROR: {map: {}} not assignable to Partial<TState>
        }
    }

In other cases, when I removed the extended type, Partial<T> can be collapsed away. ex:

    export interface IState {
        map?: {[key: string]: any};
    }

    export interface IProps {
        system: string;
    }

    class Component<P, S> {
        constructor(props: P, context?: any) { }

        setState<K extends keyof S>(
            state: Pick<S, K> & Partial<S>,
            callback?: () => any
        ): void { }
    }

    export class CharacterCreate<TState extends IState> extends Component<IProps, TState> {
        constructor(props: IProps, state: TState) {
            super(props);
            this.setState({ map: {}}); // OKAY!
        }
    }

Maybe this is a typescript bug?

**Comment by natehitchcock** [comment]
The tsc guys say this works as intended

[Microsoft/TypeScript#19388](https://github.com/Microsoft/TypeScript/issues/19388)

**Comment by ericanderson** [comment]
Sorry guys. I plan to fix this soon

**Comment by ericanderson** [comment]
The referenced PR should solve this issue. I also added tests that should protect against breaking this edge case again.
