### ISSUE TITLE
material properties missing @types/three

### ISSUE THREAD

**Issue by pbrink231** [DefinitelyTyped/DefinitelyTyped#22238]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

Hello,
I would gladly help if you can direct me in the right direction.  I am very new to this.

I am using Angular 5, I downloaded the latest npm releases today.
```
npm install @types/three --save
npm install three --save
npm install --save three-obj-loader
```

My code is just the object loader section that is giving the problem.  The code runs fine but typescript is giving an error.  I pulled this from the example for loading .obj file
```
      // load .obj model
      // my object - 'assets/objects/objtest.obj'
      // three js man - 'https://threejs.org/examples/obj/male02/male02.obj'
      var Objloader = new THREE.OBJLoader( manager );
      Objloader.load( 'assets/objects/objtest.obj', function ( object ) {
        // traverse through complete object structure
        object.traverse( function ( child ) {
          // can apply texture? Mesh -> yes
          if ( child instanceof THREE.Mesh ) {
            // use child.name to identify Mesh by name given
            // when .obj was exported so you can
            // colorize / change texture only on 
            // specific parts of the object
            console.log('child', child);
            child.material.map = texture;  <--- HERE
            
            if (child.name === 'dach') {
             // color mesh in red
              var color = new THREE.Color("rgb(255, 0, 0)");
              child.material.color.set(color);  <--- HERE
            }
          }
        });
```

The error has to do with the `child.material.color` & `child.material.map`
```
ERROR in src/app/layout/threed/threed.component.ts(176,28): error TS2339: Property 'map' does not exist on type 'Material | Material[]'.
  Property 'map' does not exist on type 'Material'.
src/app/layout/threed/threed.component.ts(181,30): error TS2339: Property 'color' does not exist on type 'Material | Material[]'.
  Property 'color' does not exist on type 'Material'.
```

**Comment by loic294** [comment]
I have the same error with color. Very annoying.

**Comment by Nischda** [comment]
I am still experiencing this error in the current version.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
