### ISSUE TITLE
Using filesize in a browser app

### ISSUE THREAD

**Issue by amitdahan** [DefinitelyTyped/DefinitelyTyped#22243]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andy-ms 

I'm using this `tsconfig.json`:

```json
{
  "compilerOptions": {
    "baseUrl": "../",
    "declaration": true,
    "stripInternal": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "module": "es2015",
    "moduleResolution": "node",
    "paths": {
      "@angular/core": [
        "node_modules/@angular/core"
      ],
      "rxjs/*": [
        "node_modules/rxjs/*"
      ]
    },
    "rootDir": "./src",
    "outDir": "dist",
    "sourceMap": true,
    "inlineSources": true,
    "target": "es5",
    "skipLibCheck": true,
    "lib": [
      "es2015",
      "dom"
    ]
  },
  "include": ["src"],
  "angularCompilerOptions": {
    "strictMetadataEmit": true
  }
}
```

I tried importing `filesize` like this (like the tests):
```typescript
import filesize = require('filesize');
```
and got the following error:
```
semantic error TS1202 Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
```

I also tried using it this way:
```typescript
import filesize from 'filesize';
```
and got the following error:
```
semantic error TS1192 Module '".../node_modules/@types/filesize/index"' has no default export.
```

and lastly, I tried using it like this:
```typescript
import * as filesize from 'filesize';
```
and got the following error:
```
rollup v0.52.2
bundles ./src/index.ts → dist/index.js...
[!] Error: Cannot call a namespace ('filesize')
src/<source-file>.ts (19:15)
17: 
18:     private static transformOne(value: number, options: any): string {
19:         return filesize(value, options);
                   ^
20:     }
21: }
```

Am I doing something wrong or is this an issue with the type definitions?

Thanks!!!

**Comment by andy-ms** [comment]
Try enabling [`--allowSyntheticDefaultExports`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) and using `import filesize from 'filesize';`.

**Comment by amitdahan** [comment]
That did it :) sorry for the bother!
