### ISSUE TITLE
Normalise tabs vs spaces on everything

### ISSUE THREAD

**Issue by Bartvds** [DefinitelyTyped/DefinitelyTyped#2228]
It is a recurring annoyance the current mix of tabs and spaces mess-up the diffs.

It will only get worse over time (I'm guilty) so lets get it over with and start normalising all the code to one standard. Even though I'm a tabs guy myself I think we're best of with 4 spaces.

Then make it official in contribution-guide and use the tester to enforce it. Maybe use TSLint and/or `detect-indent`.

Somebody would have to commit a lot of changes, but if line attribution is a problem we can let @dt-bot do it.

Of course it will break all pending PR's so maybe we should do it in phases.

We can go a step further and run @vvakame's `typescript-formatter` while we're at it.

Related to #1709 and #1569

**Comment by ExE-Boss** [comment]
I&nbsp;prefer tabs, especially because of&nbsp;this: http://nickgravgaard.com/elastic-tabstops/

**Comment by ExE-Boss** [comment]
Turns&nbsp;out, there’s&nbsp;an&nbsp;even bigger&nbsp;reason to&nbsp;use&nbsp;tabs: **developer&nbsp;accessibility**.

- <https://github.com/prettier/prettier/issues/7475>
- <https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/>

**Comment by jakebailey** [comment]
The repo was formatted consistently using dprint a few months ago, so this is settled.
