### ISSUE TITLE
ERROR in node_modules/@types/koa/index.d.ts(104,14): error TS2694: Namespace '"url"' has no exported member 'URL'.

### ISSUE THREAD

**Issue by stevermeister** [DefinitelyTyped/DefinitelyTyped#22405]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d0df8af318e457abf9a8f193f310b53e2feefb70/types/koa/index.d.ts#L28

Are you sure it's correct import here?

I solved the issue by changing it from 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d0df8af318e457abf9a8f193f310b53e2feefb70/types/koa/index.d.ts#L104

to just 

> URL: URL;

**Comment by alexshakura** [comment]
Updating @types/node to newest version fixed this for me

**Comment by jcyongqin** [comment]
I changed the `URL: url.URL;`  to `URL: url.Url;` . 
and solved.

**Comment by milocosmopolitan** [comment]
Actually all you need to do is include `@type/node` to tsconfig compilerOptions
```json
{
  "compilerOptions": {
    "types": [
      "node"
    ]
  }
}
