### ISSUE TITLE
[hapi] Typing for server.register disallows using array of PluginRegistrationObject with different OptionsPassedToPlugin objects

### ISSUE THREAD

**Issue by DamodarSojka** [DefinitelyTyped/DefinitelyTyped#22530]
If you know how to fix the issue, make a pull request instead.

- [true] I tried using the `@types/xxxx` package and had problems.
- [true] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [true] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [true] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jasonswearingen . @AJamesPhillips

First of all I am not a typescript expert so I might be terribly wrong.
```
server.register([{
    register: analyticsModule,
    routes: {prefix: "/tracker"},
    options: {
        DB_IP_API_KEY: process.env.DB_IP_API_KEY,
    },
}, {
    register: billingModule,
    routes: {prefix: "/billing"},
    options: {
        API_KEY: process.env.STRIPE_SECRET_KEY,
    },
}])
```
Fails with: 
```
Error:(58, 17) TS2345: Argument of type '({ register: (server: Server, options: { DB_IP_API_KEY: string; }, next: (err?: Error) => null) =...' is not assignable to parameter of type 'PluginFunction<{}> | PluginRegistrationObject<{}>'.
  Type '({ register: (server: Server, options: { DB_IP_API_KEY: string; }, next: (err?: Error) => null) =...' is not assignable to type 'PluginRegistrationObject<{}>'.
    Property 'register' is missing in type '({ register: (server: Server, options: { DB_IP_API_KEY: string; }, next: (err?: Error) => null) =...'.
```
Not a very useful error message...
What I think is happening here is that the typing relevant in this case:
```
register<OptionsPassedToPlugin>(plugins: PluginFunction<OptionsPassedToPlugin> | PluginRegistrationObject<OptionsPassedToPlugin>): Promise<Error | null>;
```
Fails because it expects all of the elements of the plugins array to have the same type for the options attribute.

In fact once we rename API_KEY to DB_IP_API_KEY the error vanishes. The renaming also has to take place in the definition of the billingModule - an actual implementation of the register, sadly the error message isn't helpful about that either.

Another interesting case is that even though register function of the billingModule specifies:
```
options: {IS_QA: boolean; DB_IP_API_KEY: string}
```
typescript is not complaining about IS_QA not being passed in the options.

**Comment by AJamesPhillips** [comment]
Hey @DamodarSojka, thanks for reporting this.

As a work around for the moment, can you confirm you can call `server.register({...})` twice, once each for the two different plugin registrations?

The only "solution" I can think of for this is to invoke server.register with something like: `server.register<(OptionsPassedToPlugin1 | OptionsPassedToPlugin2)>([{...plugin1}, {...plugin2}])`.  That's just of the top of my head.  Not at a computer so can't check that even makes sense.  That should relax the typings significantly but then would mean you could pass OptionsPassedToPlugin1 to plugin 2 and visa versa.

**Comment by DamodarSojka** [comment]
Thanks for a very quick reply!

I am able to call the register twice, I wasn't actually aware of such possibility! Not sure how to use .then() and .catch() in such case however... 

Yea, the quick solution doesn't really help. I hope there is a better way!

Do you have any idea about the second part of the issue? "typescript is not complaining about IS_QA not being passed in the options"

**Comment by AJamesPhillips** [comment]
What about:

    server.register<TypeOfOptionsPassedToPlugin1>({...})
    .then(() => {
        return server.register<TypeOfOptionsPassedToPlugin2>({...})
    })
    .catch(err => {
        console.error('error registering plugins....', err)
    })

**Comment by DamodarSojka** [comment]
Probably works, but isn't intuitive and elegant for sure.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
