### ISSUE TITLE
@types/mongodb v3

### ISSUE THREAD

**Issue by arusakov** [DefinitelyTyped/DefinitelyTyped#22538]
`node-mongodb-native` v3 is released. Let's play together to provide new typings. Some links:
* Official API reference: [mongodb.github.io/node-mongodb-native/3.0/api/](http://mongodb.github.io/node-mongodb-native/3.0/api/)
* Version 3 changes: [mongodb/node-mongodb-native/blob/HEAD/CHANGES_3.0.0.md](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CHANGES_3.0.0.md)

@CaselIT @kikar @bitjson @dante-101  @mcortesi

**Comment by CaselIT** [comment]
The PR #22626 updates the typings to version 3
