### ISSUE TITLE
Unable to run tests for pull request

### ISSUE THREAD

**Issue by cortopy** [DefinitelyTyped/DefinitelyTyped#22564]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cortopy

I've just made a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22563) and CI fails. Does anybody know why?

I'm unable to run the tests locally because of an Error in a package I'm not trying to edit. Running `npm run test` I get:

```
Started at Fri, 29 Dec 2017 18:49:20 GMT
Found 3978 typings folders in /home/juan/code/open_source/DefinitelyTyped/types
Error: /home/juan/code/open_source/DefinitelyTyped/types/activex-access/package.json should not specify private
    at checkPackageJson (/home/juan/code/open_source/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:144:10)
    at /home/juan/code/open_source/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:102:3
    at Generator.next (<anonymous>)
    at fulfilled (/home/juan/code/open_source/DefinitelyTyped/node_modules/types-publisher/bin/lib/definition-parser.js:4:58)
    at <anonymous>
```

And then, by looking at the Travis logs I also get a stack trace for external packages:

```
Testing sanctuary
	Running: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js 
	Error: Expected `"strictFunctionTypes": true` or `"strictFunctionTypes": false`.
    at Object.<anonymous> (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/checks.js:91:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/checks.js:4:58)
    at <anonymous>
```

**Comment by Haskaalo** [comment]
In [line 2 of package.json in activex-access](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/activex-access/package.json#L2), it make the package private.

You should remove it because it make the package unable to be published to npm.

**Comment by cortopy** [comment]
@Haskaalo but that isn't the package I'm trying to edit. Forgot to mention that, I've edited my issue

**Comment by cortopy** [comment]
@zspitz you appear to be the maintainer of those types. Any reason why your types for activex-access are a private package? DefinitelyTyped seems not to allow that

**Comment by zspitz** [comment]
@cortopy No particular reason. How should we proceed here?

**Comment by cortopy** [comment]
I wouldn't know. I would prefer a maintainer of DefinitelyTyped would comment here, but don't know who to tag

**Comment by cortopy** [comment]
weirdest thing. I removed node_modules, reinstalled and the error about private types is gone
