### ISSUE TITLE
[@types/koa] Issues using Koa middleware after updating @types/koa

### ISSUE THREAD

**Issue by DABH** [DefinitelyTyped/DefinitelyTyped#22568]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DavidCai1993 @jkeylu @brikou

I upgraded `@types/koa` from 2.0.39 to 2.0.43.  Now, lines like
`this.app.use(favicon(__dirname + 'favicon.ico'));`
give errors like
`TS2345: Argument of type 'compose.Middleware<Context>' is not assignable to parameter of type 'compose.Middleware<Application.Context>'.`
where `favicon` comes from `import * as koaFavicon from 'koa-favicon';` and where `this.app` is of type `Koa`.  This happens with several middlewares, it's not just an issue with `koa-favicon`.  The problem seems to be due to changes in `@types/koa` but I'm not sure what the issue really is and how to fix it (i.e., has the syntax for using middlewares been changed, or do middlewares need to export themselves differently, or is this a bug with `@types/koa`?).  Any ideas or suggestions are greatly appreciated!

**Comment by Haskaalo** [comment]
It appear that `type Middleware` in [Koa declaration file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa/index.d.ts#L526) doesn't declare.

Same thing happened while making my PR to `koa-csrf`

**Comment by Haskaalo** [comment]
It need to be fixed **asap** because making apps on Koa using Typescript is now almost impossible without errors about middlewares.

**Comment by Haskaalo** [comment]
It does work when doing

```ts
import {Middleware} from "./node_modules/@types/koa/index";

function test(): Middleware {};
```

But doing

```ts
import * as Koa from "koa";
```

only import `Context` and `Request`

**Comment by DABH** [comment]
What version of typescript are you using, just curious? (I'm on 2.5.3.)  I wonder if Typescript changes handling of default exports in 2.6.x, might be worth a try.  Otherwise, sounds like the type alias needs to be explicitly exported somehow, to avoid having to do something like ^^ that?

**Comment by Haskaalo** [comment]
2.6.2

Actually it was because on `include` on tsconfig.json lol

**Comment by DABH** [comment]
Your tsconfig.json broke things, or your tsconfig.json was what made your solution above work?  I don’t think anything in my tsconfig.json could be causing this issue...

**Comment by Haskaalo** [comment]
One of the folder included in `include` had a declaration file that was overriding the module `koa`.

**Comment by DABH** [comment]
Hmm, I only see 3 modules in my codebase where there's a line like `declare module "koa"`, and in all cases that's preceded by `import * as Koa from "koa";`, so I don't think that's my issue unfortunately.  Wonder what else could be going on...

**Comment by hfjallemark** [comment]
I'm also running in to this issue with latest Node (`v9.11.1`) and latest TypeScript (`v2.8.1`). Did you manage to resolve it @DABH @haskaalo?

**Comment by DABH** [comment]
No, I just held the package back in my repo.  I’ll probaboy try upgrading again in the next few weeks.

**Comment by DABH** [comment]
FWIW with the latest versions, e.g. @types/koa@2.0.44, @types/koa-favicon@2.0.19, koa-favicon@2.0.1, everything seems to work again.  Still no idea what the underlying issue was here, unfortunately, but I'm going to go ahead and close this since I'm no longer experiencing these problems.  Guess some magical package updates have saved the day.

**Comment by hfjallemark** [comment]
Still getting the same errors with `types/koa@2.0.45`. Strange... my workaround for now is:

```
import * as Koa from "koa"

export const app: any = new Koa()
```

**Comment by damianb** [comment]
Running into this right now.

Current koa definitions seem to have created nasty conflicts with koa-body, koa-router, @koa/cors, among others.

**Comment by DABH** [comment]
Sure happy to reopen.

Why do those packages refer to an inconsistent version?  Maybe the issue is that all your koa packages must refer to the same types versions? (I.e. the errors arise due to inconsistent versions?)

**Comment by damianb** [comment]
Interesting.  `koa-body` depends on `@types/koa@2.0.39` as well (though as a devDependency).   I don't see koa-static having any dependency on `@types/koa` at all, though.

**Comment by osdiab** [comment]
It doesn't look like they are referring to an inconsistent version in my code; just seems that the types for `Context` defined in these libraries vs those in Koa itself don't contain all the same entries. Messing around with the types right now to see what might resolve these errors.

**Comment by osdiab** [comment]
I just nuked my `node_modules` and `yarn.lock` then reinstalled, and it looks like it's all good now. I think @DABH is right, perhaps if you incrementally add these libraries they get `koa` versions that actually aren't in sync, and then it fails. Not particularly intuitive, but this usability kink seems like partially an issue with how NPM deals with dependency versions, partially an issue with type compatibility in TypeScript.

**Comment by bezreyhan** [comment]
I just deleted `node_modules` and `yarn.lock` but am still getting errors. I also reverted to `@types/koa@2.0.39` and did the steps above but had no success.

For example, the following code:
```
signInRouter.post("signin", "/final", async (ctx: MyContext) => {
```

throws the following error:
`[ts] Argument of type '"/final"' is not assignable to parameter of type 'IMiddleware'.`

**Comment by chroriginal** [comment]
I got the same however using `tsc --skipLibCheck` solved it for me.

**Comment by AftabSaraz** [comment]
All of the sudden im getting this error. Didn't change anything in packages.json file. Tried deleting node_modules and lock file and building again but still get the same error. Any clue on how to resolve this?

src/controllers/profile.ts(28,80): error TS2345: Argument of type 'import("/app/node_modules/koa-body/node_modules/@types/formidable/index").Files | undefined' is not assignable to parameter of type 'import("/app/node_modules/@types/formidable/index").Files | undefined'.
Type 'Files' is not assignable to type 'Files | undefined'.
Type 'import("/app/node_modules/koa-body/node_modules/@types/formidable/index").Files' is not assignable to type 'import("/app/node_modules/@types/formidable/index").Files'.
  Index signatures are incompatible.
Type 'File | File[]' is not assignable to type 'File'.
Type 'File[]' is not assignable to type 'File'.
Property 'size' is missing in type 'File[]'.

**Comment by pkuczynski** [comment]
@DABH this seems to be a very old issue not happening anymore. I think we should close it...

**Comment by DABH** [comment]
Yeah I am ok with closing this one out.  Thanks all.
