### ISSUE TITLE
@types/react is broken for non react-native users

### ISSUE THREAD

**Issue by kota65535** [DefinitelyTyped/DefinitelyTyped#22607]
Hello, 
After PR #20005 is merged, Importing React namespace (`import * as React from 'react'`) results in overriding typescript built-in type definitions (Event, HTMLElement, etc) by empty definitions.
This change may be useful for react-native users, but not for normal react users.

- Authors: @newyankeecodeshop

**Comment by newyankeecodeshop** [comment]
What are the `lib` settings in your `tsconfig.json` compiler options? Do you have the `dom` library included?

**Comment by kota65535** [comment]
Thanks for the quick response. 
Yes, I'm using following tsconfig.json which comes from `create-react-app <project> --scripts-version=react-scripts-ts` .

```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es6",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}
```

**Comment by newyankeecodeshop** [comment]
I am not sure what is going wrong. The change I made passed all the tests for React and other projects. My understanding of TypeScript is that it will combine the empty interfaces from the global declaration with the interfaces defined in the DOM library.
Can you post the project somewhere for debugging, or post what steps you took after creating the app? Also what version of TypeScript?

**Comment by kota65535** [comment]
Oh silly me, the problem is Webstorm..., not type definition. For some reason, definition jump list does not include ones from `lib.dom.d.ts` which should be there. Type definition has no problem at all.
Sorry for taking up your time. Thank you.

**Comment by petejkim** [comment]
Having this issue with VSCode too... Using React in a dom environment and that file overrides HTML*Element interfaces and the type checking fails as a result

**Comment by newyankeecodeshop** [comment]
When did the issue start? Has it always been a problem?
Can you post more details about your configuration?
