### ISSUE TITLE
@types/node-pg-migrate types aren't up-to-date

### ISSUE THREAD

**Issue by alem0lars** [DefinitelyTyped/DefinitelyTyped#22642]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/jest` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bradleyayers 

Types aren't up-to-date with upstream in many methods (for example: `createTable`, `dropTable`, `createFunction`, `dropFunction`).

**Comment by alem0lars** [comment]
Also `createFunction` and `dropFunction` types are missing.

Here is the updated definition for fixing `createFunction` and `dropFunction`:

```
type FunctionParam = string | {
  mode?: string,
  name?: string,
  type?: string,
  default?: string
};

type FunctionOptions = {
  returns?: string,
  language: string,
  replace?: boolean,
  window?: boolean,
  behavior?: "IMMUTABLE" | "STABLE" | "VOLATILE",
  onNull?: boolean,
  parallel?: "UNSAFE" | "RESTRICTED" | "SAFE"
};

type DropOptions = {
  ifExists: boolean,
  cascade: boolean
};

interface MigrationBuilder {

  createFunction(functionName: string,
                 functionParams: Array<FunctionParam>,
                 functionOptions: FunctionOptions,
                 definition: string): void;

  dropFunction(functionName: string,
               functionParams: Array<FunctionParam>,
               dropOptions: DropOptions): void;

}
```

**Comment by bradleyayers** [comment]
The current version of `@types/node-pg-migrate` targets 2.3, it looks like the latest version of `node-pg-migrate` is 2.14.0 so that probably explains the discrepancy. It'd be great if you could raise a PR to update the types here so a new version of the types can be released.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
