### ISSUE TITLE
Expected publication workflow for new typings that span multiple npm packages

### ISSUE THREAD

**Issue by mootari** [DefinitelyTyped/DefinitelyTyped#22699]
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

I'm currently working on the typings for an npm package that depends on (inherits from) several other npm packages without typings (all Javascript, node). What is the proper publication workflow:
1. Include dependencies as module declarations in the primary package declarations (so that they can gradually be moved out into their own DT directories).
2. Create individual definitions for each package, have them depend on each other, but create a combined pull request.
3. Like 2, but create individual pull requests (walking the dependencies bottom-up).
4. ... ?

**Edit:** To be more clear, the typings I create will also include extensive definitions for the dependencies (which *could* live in their own typings).

**Comment by andy-ms** [comment]
I would go with 2.

**Comment by mootari** [comment]
> I would go with 2.

Will do, thanks!
