### ISSUE TITLE
Notifications of module owner seems to be no longer working

### ISSUE THREAD

**Issue by Flarna** [DefinitelyTyped/DefinitelyTyped#22707]
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

Looks like one of the bots is out of office as module maintainers don't get notified any more once a new PR is created.

Or is mhegazy the new Bot?

@andy-ms @RyanCavanaugh

**Comment by andy-ms** [comment]
Hi, I've asked about this on the GitHub forum: https://github.community/t5/How-to-use-Git-and-GitHub/CODEOWNERS-not-activating-for-anyone-besides-me/m-p/2517#M814
There was also `dt-bot` which was run by @vvakame -- maybe it needs a kick.

**Comment by RyanCavanaugh** [comment]
I'm having `typescript-bot` take over for `dt-bot` just for the sake of centralization

**Comment by RyanCavanaugh** [comment]
Putting hard-working bots out of a job 😢
