### ISSUE TITLE
[yup] invalid types for addMethod

### ISSUE THREAD

**Issue by rosskevin** [DefinitelyTyped/DefinitelyTyped#22721]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/yup` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @vtserman @dhardtke

`addMethod` has incorrect typing.  Using as typed/tested will result in [`yup-tests.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yup/yup-tests.ts)

```
Uncaught TypeError: You must provide a yup schema constructor function
    at Object.addMethod (index.js:66)
```

```js
yup.addMethod(yup.date(), 'format', function(this: Schema) {
    return this.clone();
});
```

As specified in the [README](https://github.com/jquense/yup#yupaddmethodschematype-schema-name-string-method--schema-void) states usage as:

```js
yup.addMethod(yup.date, 'format', ...)
```

**Comment by rosskevin** [comment]
Note I worked around the above with `yup.date as any`, then encountered further issues with the typing of the `function(this: Schema)`.  

The function should accept any args and return `Schema`,  not accept `Schema` as an arg.

**Comment by vtserman** [comment]
I've opened a PR #22736 to fix that. 

Once merged, it should be possible to pass to the `addMethod` a function with a variable number of arguments, like so

```
yup.addMethod(yup.date, 'minimum', function(this: yup.NumberSchema, minValue: number, message: string) {
    return this.min(minValue, message);
});
```
