### ISSUE TITLE
Node IncomingMessage missing reference to `client`

### ISSUE THREAD

**Issue by gDelgado14** [DefinitelyTyped/DefinitelyTyped#22762]
Not sure how to fix this issue. Which is why I'm looking for feedback, suggestions. 

I noticed that `req.client` does not exist in the typedef for `http.IncomingMessage`. Is this an unintended omission? 

I noticed that when using ExpressJS, if I log `req.client` (without any middleware), there is actually a value in this field. And Express makes no mention of it in their typedefs so I am assuming it is a lower level functionality coming from Node's HTTP lib. 

### Authors:
@parambirs 
@tellnes 
@WilcoBakker 
@octo-sniffle, @smac89 
@Flarna 
@mwiktorczyk 
@wwwy3y3 
@DeividasBakanas 
@kjin 
@alvis

**Comment by gDelgado14** [comment]
These are the keys on the `req.client` object: 

```javascript
['connecting',
  '_hadError',
  '_handle',
  '_parent',
  '_host',
  '_readableState',
  'readable',
  'domain',
  '_events',
  '_eventsCount',
  '_maxListeners',
  '_writableState',
  'writable',
  'allowHalfOpen',
  '_bytesDispatched',
  '_sockname',
  '_pendingData',
  '_pendingEncoding',
  'server',
  '_server',
  '_idleTimeout',
  '_idleNext',
  '_idlePrev',
  '_idleStart',
  '_destroyed',
  'parser',
  'on',
  '_paused',
  'read',
  '_consuming',
  '_httpMessage']
```

**Comment by Flarna** [comment]
I can't find any reference to `client` property in NodeJs docs. From source I can see that it points to the socket - same as the (documented) property `socket` and similar as the other alias `connection`.

I think it's best you use one of the documented properties instead adding an undocumented one which may be removed from source.

**Comment by gDelgado14** [comment]
@Flarna that then means that you have a compiler that thinks it's safe to append properties to an `undefined` client key. When in fact, you're overriding the value originally defined inside `req.client`.

The reason I found this is because we had logic like this in our code:

```javascript
// .. middleware that __CONDITIONALLY__ appends `client` to request
// thus req.client may hypothetically be undefined sometimes
app.use(authenticateRequest)

app.get('/some-route', (req, res) => {
  if (req.client) {
   // do something if authenticated
  } else {
    // do another thing if not authenticated
  }
})
```

In the above example, the `else` clause will never ever be executed because req.client is always defined, even though typescript thinks it's undefined by default.

**Comment by Flarna** [comment]
Typescript will issue an error if you access the `client` property on nodejs `http.IncomingMessage` class as this class has no index signature - independent of read/write access. So you can't add/override a `client` to  property to `http.IncomingMessage` without casting/augmenting nodejs types/...

But based on your code sample above it seems you use plain javascript, not typescript. In this case there is no checking at all.

**Comment by gDelgado14** [comment]
Sorry, the code sample didn't use typescript just for brevity, but in our actual codebase it is in TS. 

And ExpressJS's types extend `http.IncomingMessage` and we do append `client` to `req` without the compiler ever telling us there is an error.

**Comment by Flarna** [comment]
Not sure if I fully understand the actual issue. I haven't found the place where `client` is added to `http.IncomingMessage` so don't know which type is used for it but if it is not that one used by NodeJs it's a bad thing.

I think it's more or less impossible to avoid such issues. It would require to add _all_ internal properties to type definitions to ensure that they are never overwritten by some other module extending these object.
Usually internal properties are _not_ added to type definitions as they should be not used by clients. Besides that internal properties are usually not documented and may change without notice even for patch releases.
For classes there is private but quite often just interfaces are exported which have no possibility to mark properties as not accessible.

In general I would avoid to add properties to objects created by some other modules - but yes, I know that this is an usual javascript pattern used at a _lot_ places...
