### ISSUE TITLE
@type/stripe missing items propery on Subscription

### ISSUE THREAD

**Issue by Bene-Graham** [DefinitelyTyped/DefinitelyTyped#22783]
- [X] I tried using the `@types/stipe` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wjohnsto @codeanimal @sampsonjoliver @LinusU @brannon @kkamperschroer @starhoshi

I am currently using: "@types/stripe": "5.0.0"

Based on the documentation: https://stripe.com/docs/api/node#subscriptions

The ISubscription should have a property for items. 

Sample code
```
const subscriptions = await newStripe.customers.listSubscriptions(customerId);
const items = subscriptions.data[subscriptions.data.length-1].items;
```
I can see via debugging the code the items property shows up and is populated.

**Comment by bilby91** [comment]
I realized the same thing today
