### ISSUE TITLE
@types/jest before / after functions miss the async signature

### ISSUE THREAD

**Issue by alem0lars** [DefinitelyTyped/DefinitelyTyped#22802]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/jest` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil

Functions `afterAll`, `beforeAll`, `afterEach`, `beforeEach` are missing the async signature (without the callback argument).

**Comment by jwbay** [comment]
Do you have an example of code that breaks? You don't have to accept the callback, i.e. this should work fine.
```ts
beforeEach(async () => {
  await 5;
});
```

**Comment by alem0lars** [comment]
@jwbay Instead that code gives me type error.

**Comment by alem0lars** [comment]
@NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil also `it` function is missing async support

**Comment by ikatyang** [comment]
Tested with `typescript@2.6.2` and `@types/jest@22.0.1`, no error.

```ts
it("", async () => {
  // something
});

beforeAll(async () => {
  // something
});
```

and its return type is `any`, i.e. it allows whatever you returned, including `Promise` (async). https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1257e0e88384bba80115b26da16e27399bfd9373/types/jest/index.d.ts#L198

Can you share some steps to reproduce?

**Comment by alem0lars** [comment]
@NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil this is an example:

![2018-01-11-095929_1429x1282_scrot](https://user-images.githubusercontent.com/336957/34816787-444f07d8-f6b6-11e7-9ccf-a6bb96a3be43.png)

**Comment by alem0lars** [comment]
@NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil this is an example:

![2018-01-11-095929_1429x1282_scrot](https://user-images.githubusercontent.com/336957/34816787-444f07d8-f6b6-11e7-9ccf-a6bb96a3be43.png)

**Comment by ikatyang** [comment]
You have to specify `--lib es6` to get the `Promise` type.

```json
{
    "compilerOptions": {
        "lib": ["es6"]
    }
}
```

**Comment by alem0lars** [comment]
@NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil this is an example:

![2018-01-11-095929_1429x1282_scrot](https://user-images.githubusercontent.com/336957/34816787-444f07d8-f6b6-11e7-9ccf-a6bb96a3be43.png)

**Comment by alem0lars** [comment]
@NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil This is the config:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2017",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "alwaysStrict": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "*": [
        "node_modules/*",
        "src/typing/*"
      ]
    }
  },
  "typeRoots": ["src/typing", "node_modules/@types"],
  "include": [
    "src/**/*",
    "migration/**/*"
  ]
}
```

Also including specific lib:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2017",
    "lib": ["es6"],
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "alwaysStrict": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "*": [
        "node_modules/*",
        "src/typing/*"
      ]
    }
  },
  "typeRoots": ["src/typing", "node_modules/@types"],
  "include": [
    "src/**/*",
    "migration/**/*"
  ]
}
```

**Comment by alem0lars** [comment]
Ok it was my mistake. Sorry
