### ISSUE TITLE
Navigo types is merged correctly without create a new version, and no posible to get the new changes

### ISSUE THREAD

**Issue by dancespiele** [DefinitelyTyped/DefinitelyTyped#22814]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/navigo` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @RyanCavanaugh 

Hello before I did a pull request for this package and it was merged correctly but instead of the last time it doesn't create any new release and when I install it I get the version 4.0.4 which was before to the new changes

**Comment by RyanCavanaugh** [comment]
What?

**Comment by dancespiele** [comment]
@RyanCavanaugh look this merge https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22799 please. Now when I do a `npm update` it doesn't get any update for @types/navigo, if I delete the types from package.json and I do `npm install` I get the version @types/navigo 4.0.4 which was the before commit(https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22729) that the last commit(https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22799)

**Comment by RyanCavanaugh** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#my-pr-is-merged-when-will-the-types-npm-package-be-updated

**Comment by dancespiele** [comment]
@RyanCavanaugh @andy-ms is more than 24h that the commit for navigo was merged and the version wasn't update to 4.0.5 yet. Could someone try to find out what is the problem please? Thank you!

**Comment by andy-ms** [comment]
It looks like azure got a bad `node_modules` somehow -- it doesn't have `date-utils` which is needed by `adal-node`. I updated the `package-lock.json` recently so that might have triggered a reinstall, but somehow that didn't finish installing everything?

**Comment by dancespiele** [comment]
ok @andy-ms then supposedly it would have to work in few time after you update the package-lock, right?

**Comment by andy-ms** [comment]
Never mind, it looks like that file exists, it just isn't resolving when `require()`d for some reason. It works fine locally though. I'll have to investigate some more.

**Comment by dancespiele** [comment]
@andy-ms the version is update now. Thank you 👍
