### ISSUE TITLE
Merge my changes into @types/expo

### ISSUE THREAD

**Issue by janaagaard75** [DefinitelyTyped/DefinitelyTyped#22834]
Hi @KonstantinKai and @martynaskadisa,

Sorry for creating an issue about this, but the is the only way I can figure out how to contact you.

I have also created some type definitions for Expo, and I would like to merge them into this repo here. It seems that both d.ts files are based on the same source, but I have made many changes, so I actually think it would be easiest to take my version as the new source, and manually merge any changes you have made into that one.

My type definition file is located here <https://github.com/janaagaard75/expo-and-typescript/blob/master/src/expo.d.ts>.

How do you feel about this?

I guess this repo really wants to keep the number of issues as low as possible, so feel free to close this one, and write your response here instead: <https://github.com/janaagaard75/expo-and-typescript/issues/8>.

**Comment by KonstantinKai** [comment]
Hi @janaagaard75, thank you for the work done and your feedback. You are right, this package is based on this https://gist.github.com/pierre-H/eef9a9225fb1c5a0f81180a8b0fbb2c2 source, but I have also made many changes, I have added new API, crucially changed existing code. So, we all work for a common cause. I'll promise to diff your code with existing definitions and merge missed or wrong API soon.

Thank you 👍

**Comment by janaagaard75** [comment]
The APIs that I have changed have received a checkmark: https://github.com/janaagaard75/expo-and-typescript

I've also cleaned up the original code quite a bit, for example removing all the `export` and `public`, since I believe that this is redundant in `.d.ts` files. I've also tried to put everything in namespaces, to try to avoid conflicts between the different APIs.

**Comment by janaagaard75** [comment]
I will help with merging the code, but making pull requests to this file. One question though: Shouldn't everything be put inside a `declare module 'expo'`?

**Comment by KonstantinKai** [comment]
I can't remember why I've made like that, maybe `npm lint` or `npm test` was failing before release.

**Comment by KonstantinKai** [comment]
But this is also right way.

**Comment by KonstantinKai** [comment]
@janaagaard75, oooh, I remembered, I was using `dts-gen` module for creating `types/expo` which generate the following code
```
// Type definitions for 
// Project: https://github.com/baz/foo (Does not have to be to GitHub, but prefer linking to a source code repository rather than to a project website.)
// Definitions by: My Self <https://github.com/me>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/*~ If this module is a UMD module that exposes a global variable 'myLib' when
 *~ loaded outside a module loader environment, declare that global here.
 *~ Otherwise, delete this declaration.
 */
export as namespace myLib;

/*~ If this module has methods, declare them as functions like so.
 */
export function myMethod(a: string): string;
export function myOtherMethod(a: number): number;

/*~ You can declare types that are available via importing the module */
export interface someType {
    name: string;
    length: number;
    extras?: string[];
}

/*~ You can declare properties of the module using const, let, or var */
export const myField: number;

/*~ If there are types, properties, or methods inside dotted names
 *~ of the module, declare them inside a 'namespace'.
 */
export namespace subProp {
    /*~ For example, given this definition, someone could write:
     *~   import { subProp } from 'yourModule';
     *~   subProp.foo();
     *~ or
     *~   import * as yourMod from 'yourModule';
     *~   yourMod.subProp.foo();
     */
    export function foo(): void;
}
```

**Comment by KonstantinKai** [comment]
@janaagaard75, I created a new branch in my fork and already made changes, you can continue work in this branch if you want.

https://github.com/KonstantinKai/DefinitelyTyped/tree/expo-from-janaagaard75

**Comment by janaagaard75** [comment]
Great. I will have a look at in the weekend.

**Comment by janaagaard75** [comment]
Finally got around to look at the branch.

In my test app ([expo-and-typescript](https://github.com/janaagaard75/expo-and-typescript/)) I can't do something like `import { Facebook } from 'expo';`, unless I wrap everything in `index.d.ts` in `declare namespace 'expo'`. So I am a bit puzzled about you got around this. How to you write your `import` statements?

**Comment by janaagaard75** [comment]
I have a couple of changes to the janaagaard75 branch. Are you okay with these? Thought it would nice to know if I am on the right track, before I continue.

**Comment by KonstantinKai** [comment]
@janaagaard75 hi, I made a big mistake, sorry, I had a lot of work and me accidentally updated  working branch with `--force`. Please don't update branch. Can you push your local changes with --force?

**Comment by KonstantinKai** [comment]
@janaagaard75, hi, about import { Facebook } from 'expo' it works fine for me, all tests pass.
About your changes, I left one comment KonstantinKai/DefinitelyTyped@103c762#comments, about other changes I agree with you. I updated working branch and made tiny corrections.

**Comment by janaagaard75** [comment]
I've update the Audio, Video (and AV) section, and added the vector-icons.
