### ISSUE TITLE
Definitions for node-spdy

### ISSUE THREAD

**Issue by minecrawler** [DefinitelyTyped/DefinitelyTyped#2283]
The SPDY protocol is supported by major browsers and I think we really should start supporting it.
There is a implementation for node.js: node-spdy. It would be awesome to have TS definitions!
https://github.com/indutny/node-spdy

**Comment by NKjoep** [comment]
I think this can be closed, we have this:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/spdy/index.d.ts

Btw, the definitions are behind the library. 
`spdy: 3.4.4`
`@types/spdy 3.4.1`

**Comment by n0mer** [comment]
when you instantiate server like this ("spdy": "^3.4.4" , "@types/spdy": "^3.4.1")
```javascript
const app = express();
spdy.createServer(opts, app);
```

then `tsc` gives this semantic error:

```
error TS2345: Argument of type 'Express' is not assignable to parameter of type '(request: IncomingMessage, response: ServerResponse) => void'.
  Types of parameters 'res' and 'response' are incompatible.
    Type 'ServerResponse' is not assignable to type 'Response'.
      Property 'status' is missing in type 'ServerResponse'.
```

`index.d.ts` contains only the following mappings:

```typescript
    export function createServer(base: any,
                                 options: ServerOptions,
                                 handler: (request: IncomingMessage, response: ServerResponse) => void): Server;
    export function createServer(options: ServerOptions,
                                 handler: (request: IncomingMessage, response: ServerResponse) => void): Server;
    export function createServer(handler: (request: IncomingMessage, response: ServerResponse) => void): Server;
```

**Comment by jcheenatcode** [comment]
Receiving exactly the same error, was there any recommendation or progress on how to resolve this issue?

**Comment by jcheenatcode** [comment]
@tony19 / @n0mer were you guys able to figure out why we are getting the following issue 

`
error TS2345: Argument of type 'Express' is not assignable to parameter of type '(request: IncomingMessage, response: ServerResponse) => void'.
  Types of parameters 'res' and 'response' are incompatible.
    Type 'ServerResponse' is not assignable to type 'Response'.
      Property 'status' is missing in type 'ServerResponse'. 
`

when we do 

```
const app = express();
spdy.createServer(opts, app);
```

will we have to change the index.d.ts file to have a new mapping or do you guys have other recommendations

**Comment by tony19** [comment]
@jcheenatcode `spdy` declares `createServer()` with its own [extension of `http.ServerResponse`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/spdy/index.d.ts#L54), which is incompatible with `express`'s [extension of `http.ServerResponse`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec6/types/express-serve-static-core/index.d.ts#L478). The solution seems to be changing `spdy`'s `createServer`'s declaration to use `http.ServerResponse`, as it's the common base class; and this works in my local tests.
