### ISSUE TITLE
[@types/redux-form] Can't pass handleSubmit to onSubmit 

### ISSUE THREAD

**Issue by Lleios** [DefinitelyTyped/DefinitelyTyped#22847]
- [x] I tried using the `@types/redux-form` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/redux-form) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CarsonF @aikoven @LKay @bancek @tehbi4 

# Situation
I have a ts error if i pass handleSubmit method to onSubmit

# Code 
```typescript
import * as React from "react";
import { InjectedFormProps } from "redux-form";

interface ITestFormData {
  foo: string;
}

type TestProps = {} & InjectedFormProps<ITestFormData>;

const test: React.StatelessComponent<TestProps> = ({ handleSubmit }: TestProps) => (
  <form onSubmit={handleSubmit}></form>
);
```
or
```typescript
class TestComponent extends React.Component<TestProps> {

  public render(): JSX.Element {
    const { handleSubmit } = this.props;

    return (
      <form onSubmit={handleSubmit}>
      </form>
    );
  }
}
```
# Error
`[ts]
Type '{ onSubmit: SubmitHandler<ITestFormData, {}>; }' is not assignable to type 'DetailedHTMLProps<FormHTMLAttributes<HTMLFormElement>, HTMLFormElement>'.
  Type '{ onSubmit: SubmitHandler<ITestFormData, {}>; }' is not assignable to type 'FormHTMLAttributes<HTMLFormElement>'.
    Types of property 'onSubmit' are incompatible.
      Type 'SubmitHandler<ITestFormData, {}>' is not assignable to type '((event: FormEvent<HTMLFormElement>) => void) | undefined'.
        Type 'SubmitHandler<ITestFormData, {}>' is not assignable to type '(event: FormEvent<HTMLFormElement>) => void'.`

`[ts]
Type '{ onSubmit: SubmitHandler<ITestFormData, {}>; }' is not assignable to type 'DetailedHTMLProps<FormHTMLAttributes<HTMLFormElement>, HTMLFormElement>'.
  Type '{ onSubmit: SubmitHandler<ITestFormData, {}>; }' is not assignable to type 'FormHTMLAttributes<HTMLFormElement>'.
    Types of property 'onSubmit' are incompatible.
      Type 'SubmitHandler<ITestFormData, {}>' is not assignable to type '((event: FormEvent<HTMLFormElement>) => void) | undefined'.
        Type 'SubmitHandler<ITestFormData, {}>' is not assignable to type '(event: FormEvent<HTMLFormElement>) => void'.
          Types of parameters 'submit' and 'event' are incompatible.
            Type 'FormEvent<HTMLFormElement>' is not assignable to type 'FormSubmitHandler<ITestFormData, {}>'.
              Type 'FormEvent<HTMLFormElement>' provides no match for the signature '(values: Partial<ITestFormData>, dispatch: Dispatch<any>, props: {}): void | Promise<any> | FormErrors<ITestFormData, void>'.
`
# Versions
Packages | Versions
------------ | -------------
`typescript` | 2.6.2
`react` | 16.2.0
`redux-form` | 7.2.0
`@types/react` | 16.0.34
`@types/redux-form` | 7.0.12

**Comment by ochowie** [comment]
Seems like there is an issue that was introduced somewhere between @types/react 16.0.31 and 16.0.34 and/or @types/redux-form 7.0.10 and 7.0.12. When I try this with the older packages it works correctly but I get the same error with the new packages.
