### ISSUE TITLE
Supporting different versions of APIs / NuGet

### ISSUE THREAD

**Issue by johnnyreilly** [DefinitelyTyped/DefinitelyTyped#2288]
Hi team!

I'm pretty sure this has been discussed before but I seem to have lost the original discussion.

Essentially I've been thinking about what we should do with regards supporting different versions of typings on an ongoing basis.  The thing that's got me thinking about this is AngularJS and Jasmine (both of which I've been using recently).

The Angular typings currently on DT are v1.2.x.  We also have the 1.x typings squirrelled away in a legacy folder.  When Angular 1.3.x lands it plans to drop support for IE 9 and that when Angular 2.x lands it's going into an entirely brave new world which does not lend itself to back compatibility with older browsers (that's my understanding anyway).  Either way, I think we are about to hit the scenario where we'll want to host different versions of AngularJS on an ongoing basis to cater for the different versions people are using in their applications.  

Further to that I think it would be good for people to be able to pull the specific version from NuGet using something like this: (better naming conventions entirely possible - this is just an idea)

```
install-package angularjs.1.2.x.TypeScript.DefinitelyTyped
```

or 

```
install-package angularjs.2.x.TypeScript.DefinitelyTyped
```

@Bartvds / @staxmanade  - I think you chimed in with some good stuff on this point before.  Sadly I've forgotten the details :sob: Care to share again?

I've a vague idea you mentioned there was already a convention in place which, if typings were arranged in a certain way, would support the NuGet scenario already.  Did I imagine that?  If not could you refresh our memory on what the convention is?  Or if it doesn't exist, perhaps we could introduce it?

I realise there's a lot in here so I just wanted to kick off the discussion.  Some of this was touched on in #2207 as well.

@basarat participating

**Comment by stevenlivz** [comment]
Hi @johnnyreilly - can I ask where you got with this? I have looked through the issues and can't find any resolution. Coming from an API background, versioning is an absolute must but not sure how tsd supports it (still learning) but the latest VS node project uses express 3.4.4 typings and to get these i had to copy and paste from an existing project as tsd kept getting the 4.0 version which has a different api. I'd expect tsd query express@3.4.4 or even for tsd query express to use my packages.json to figure out the versioning but it didn't in my case.

**Comment by johnnyreilly** [comment]
Hi @stevenlivz, 

No particular progress to report to my knowledge - there isn't an official tie up between versioning in DT and actual packages I'm afraid. It's a little "wild west".

Re Express, if you go back through the history of the typing it only went to 4.x a while ago - you can still find the 3.x somewhere in previous versions. If memory serves that was quite a controversial PR.

@basarat @Bartvds @staxmanade - I think that's still the case re: versioning?

**Comment by basarat** [comment]
> versioning is an absolute must but not sure how tsd supports it (still learning)

Git commit shas :) 

>  I think that's still the case re: versioning

Yup. No change.

------------

If the whole world was written in TS versioning would not be an issue. Since what we have here is *best effort* we have found that just supporting the latest seems to be what the community can provide high quality for. And that's all we have except for a few cases (like angular) where people would like to support different versions. Again there is no strong tie between DT versions and angular versions ... community best effort :rose:

**Comment by johnnyreilly** [comment]
Well expressed @basarat - thanks for that :tulip: :

**Comment by stevenlivz** [comment]
Hi @basart - I completely agree community wise. However, as an example, I used the VS starter project and it uses and older version of Express which fails when I use tsd in VS to get the type definition.

Now, as you say, the community has actually already done the work for the previous version and when i do tsd in VS i'd expect it can use that to get he correct TS version.

It kind of feels like a relatively trivial filter on the tsd query to map a sha to a version (i could be wrong), so i can do tsd query express@3.4.4 --action install (or as i said tsd in VS even uses the packages.json).  

It may be an edge case just now, but this will only become more common (memories of dll's in 1997 streaming through my mind). Looking forward to getting more involved in the project and using typescript :-)

**Comment by jakebailey** [comment]
Doing some issue cleanup; I believe that these days, this is all settled. We can hang multiple versions of a lib just fine.
