### ISSUE TITLE
@types/email-templates class not exported

### ISSUE THREAD

**Issue by aroslov** [DefinitelyTyped/DefinitelyTyped#22937]
- I tried using the `@types/email-templates` package and had problems.
- Authors: @cyrilschumacher @gurisko @blankstar85

Unable to use this code

const email = new Email({
 views: { root: templateDir }
});

from example in https://github.com/niftylettuce/email-templates

seems like only the namespace is exported, but not the class

**Comment by blankstar85** [comment]
What was the error, ? If that is the code, the transport was required until recently. I just updated the typings today. I have been using this in a project of mine. Advise if able. I'm working on being more active. Sorry for the delay in response.

**Comment by aroslov** [comment]
Unable to advise, no longer a part of the project where this was.

**Comment by blankstar85** [comment]
please close this issue then.
