### ISSUE TITLE
[archiver] Missing EntryData fields

### ISSUE THREAD

**Issue by Waldo000000** [DefinitelyTyped/DefinitelyTyped#22944]
The types seem to be missing some fields on `EntryData`, in particular `date`, `stats`, and `mode`, as documented in `node-archiver`: https://github.com/archiverjs/node-archiver/blob/master/lib/core.js#L934

- [x] I tried using the ` "@types/archiver": "^2.0.1"` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dolanmiu, @Crevil

**Comment by dolanmiu** [comment]
stats is already there, 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/archiver/index.d.ts#L21

But the other two are not, will add soon

**Comment by dolanmiu** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23009

Here you go
