### ISSUE TITLE
d3.d.ts generics and interface naming conventions

### ISSUE THREAD

**Issue by gustavderdrache** [DefinitelyTyped/DefinitelyTyped#2300]
I have two (somewhat related) points I'd like to discuss, since implementing either in a pull request would be pretty heavily breaking.

I'm using d3 for a large project and find the lack of generics to be kind of painful. Since most uses of d3 use data-binding, it makes sense to me to have selections (and a few of the data-dependent generators like `d3.svg.symbol`) be parametrized over the bound data.

Secondly, the naming convention for d3 seems to pollute the type namespace somewhat. It seems like declaring `d3` as a module and keeping its interfaces there would be better (thus, the type of `d3.svg.symbol()` would be `d3.svg.Symbol`).

Below is a small sample of what I'm talking about. I'm more than happy to work on this in a fork and contribute it back. Just thought I'd collect some input before doing so.

``` typescript
declare module d3 {
    export module svg {
        export interface Symbol<T> {
            (datum: T, index: number): string;

            type(): (datum: T, index: number) => string;
            type(type: string): Symbol<T>;
            type(type: (datum: T, index: number) => string): Symbol<T>;

            size(): (datum: T, index: number) => number;
            size(size: number): Symbol<T>;
            size(size: (datum: T, index: number) => number): Symbol<T>;
        }

        export function symbol<T>(): Symbol<T>;
    }

    export interface Selection<T> {
        data(): T[];
        data<U>(data: U[], key?: (datum: U, index: number) => string): Selection<U>;
        data<U>(data: (datum: T, index: number) => U[], key?: (datum: U, index: number) => string): Selection<U>;

        attr(name: string): string;
        attr(name: string, value: (datum: T, index: number) => string): Selection<T>;
    }

    export function select(query: string): Selection<any>;
    export function selectAll(query: string): Selection<any>;
}

/// USAGE ///
interface Data { type: string; size: number; }

var data = [
    {
        type: 'foo',
        size: 123,
    },
    {
        type: 'bar',
        size: 456,
    }
];

var symbol = d3.svg.symbol<Data>()
    .type(d => d.type)
    .size(d => d.size);

var nodes = d3.selectAll('foo')
    .data(data)
    .attr('d', symbol);
```

(Apologies for the awkward formatting.)

**Comment by dtchepak** [comment]
I'm using D3 and currently having troubles with `Nest.entries` being the non-generic `NestKeyValue[]` rather than `NestKeyValue<T>[]`. Is that the sort of change you're talking about? If so, big :+1: from me (and happy to help where I can).

Can anyone confirm whether a PR for this would have a decent chance of being accepted?

**Comment by gustavderdrache** [comment]
I've opened #3999 to address this. We should probably close this issue in favor of discussing the PR, but I'll let the project maintainers take that action.

(The nesting issue is surprisingly pernicious, but I think I have an attack plan.)

**Comment by tomwanzek** [comment]
As part of some legacy D3v3 issue clean-up, can this issue be please closed?

D3v4 has been released and supported with actively maintained definitions for several months now, so it would be great to have only current issues open for clarity.

Thanks in advance!

cc @gustavderdrache @andy-ms
