### ISSUE TITLE
Should `enum`s be `const enum`s?

### ISSUE THREAD

**Issue by TexAgg** [DefinitelyTyped/DefinitelyTyped#23002]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/firefox-webext-browser` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bomjacob 

If you do not mention the authors the issue will be ignored.

---

The only `enum` I used was [`ContextType`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3a8270c12cbaa59d973faeb95cb069d04e9cdaaa/types/firefox-webext-browser/index.d.ts#L4995), so I don't know if this is an issue with any other of the enums declared, but I had to change it to a `const enum` to get it to work. 
The [WebExtension API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus) expects a string for that entry, but the Typescript compiler converts an ordinary enum to an object and not a string literal(for example. `browser.contextMenus.ContextType.all` compiled to `browser.contextMenus.ContextType.all` originally but after I changed it to a const enum it compiled to `'all'`)
According to the [Typescript documentation for enums](https://www.typescriptlang.org/docs/handbook/enums.html), `const enum`s are completely inlined, so I assume they would be compiled into the form that the webextension API expects.

**Comment by bomjacob** [comment]
Hmm, thanks a lot for this request.
I'll see what I can do to fix it (though I'm quite busy, but I'll try to do it sometime next week).

**Comment by mhegazy** [comment]
You should not use `const enums` in a .d.ts **ever**. they break single file compilation scenarios. (i.e. compiling with `--isolatedModules`). 

Enums should be a declaration file iff a value with the same name and shape exists at runtime.

otherwise, use a union of literal types.

**Comment by luckyrat** [comment]
Converting the `ContextType` enums to uppercase fixed it for me without needing to use const enums. Same story for `browser.notifications.TemplateType`.

I see no indication of uppercase naming on MDN or the Chrome docs so maybe this needs fixing in https://github.com/mozilla/webextension-polyfill ?

Although the properties are uppercase in Chrome and Firefox (presumably the polyfill is having no effect in this case) so maybe this is just a WebExtensions convention I'm unaware of.

**Comment by bomjacob** [comment]
Hmm, so what would be the correct fix to this issue? I'm a bit stumped myself.
Does breaking single file compilation scenarios matter that much? (I personally have no idea what they are)

**Comment by zspitz** [comment]
@bomjacob Referencing the discussion [here](https://github.com/Microsoft/TypeScript/issues/20703#issuecomment-362013110).

Also, from the [docs](https://github.com/Microsoft/dtslint/blob/master/docs/no-const-enum.md):

> These can't be used by JavaScript users

because they are inlined, they don't exist at runtime by name.

**Comment by anantoghosh** [comment]
@bomjacob 
I think instead of enums
```ts
enum OnBeforeRequestOptions {
  blocking = "blocking",
  requestBody = "requestBody"
}
```
you could use
```ts
type OnBeforeRequestOptions = "blocking" | "requestBody";
```

Still using const enum should be good enough for making extensions, right?

**Comment by t7yang** [comment]
i got everything `undefined` at runtime.

and look like https://github.com/Microsoft/TypeScript/issues/432 point out the reason why current enum doesn't work.

is this issue going to be fixed?

**Comment by anantoghosh** [comment]
@t7yang you could use https://github.com/kelseasy/web-ext-types for now

**Comment by t7yang** [comment]
@anantoghosh 
I used to install web-ext-types, but it outdated (without browser.menus). so I move to firefox-webext-browser, but still bother with this enum issue...

**Comment by anantoghosh** [comment]
@t7yang use browser.contextMenus

> Before Firefox 55 this API was also originally named contextMenus, and that name has been retained as an alias, so you can use contextMenus to write code that works in Firefox and also in other browsers.
