### ISSUE TITLE
 Module '"@types/graphql/language/ast"' has no exported member 'TypeExtensionDefinitionNode'.

### ISSUE THREAD

**Issue by JounQin** [DefinitelyTyped/DefinitelyTyped#23012]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/graphql` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @TonyPythoneer @calebmer @intellix @firede @kepennar @freiksenet @IvanGoncharov @DxCx @rportugal @tgriesser @dyst5422 

If you do not mention the authors the issue will be ignored.

**Comment by dyst5422** [comment]
Graphql version 0.12.x removed TypeExtensionDefinitionNode in favor of more specific type extension nodes.

**Comment by adnsio** [comment]
@dyst5422 check my PR #23010

**Comment by dyst5422** [comment]
Oh, completely misunderstood what you were saying
