### ISSUE TITLE
screeps: invalid declaration of FindTypes lookup interface

### ISSUE THREAD

**Issue by smhxx** [DefinitelyTyped/DefinitelyTyped#23030]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: /cc @MarkoSulamagi @NhanHo @bryanbecker @resir014 @arcath @apemanzilla

Hi, all!

I just wanted to point out that there's a rather insidious error in the current `@types/screeps` definitions, pertaining to the `FindTypes` interface. To be honest, I'm not sure what the best way to address it is, but the current definitions are going to throw compiler errors and have lax type safety in certain situations. I'll copy/paste a bit of it below so you know what I'm talking about:

```typescript
interface FindTypes {
  1: RoomPosition; // FIND_EXIT_TOP
...
  105: Source; // FIND_SOURCES
  '-106': Resource<RESOURCE_ENERGY>; // FIND_DROPPED_ENERGY
  106: Resource; // FIND_DROPPED_RESOURCES
...
  117: Nuke; // FIND_NUKES
}
```

I guess I should start by explaining the trick that's being employed here, to make sure everyone's on the same page: in ECMAScript, object keys (and, by extension, TypeScript interface keys) ***must*** be either a string or a *numeric literal*. By definition, numeric literals can *only* be positive... negative numbers are essentially just the unary negation operator `-` followed by a positive numeric literal, so, long story short, negative numbers can't be used as keys on an object.

In JavaScript, you can sneakily get around this by doing what's shown above; enclose the number in quotes (making it a string,) and due to JavaScript's funky coercion magic, an invalid reference of `foo[-14]` gets coerced to the perfectly fine `foo["-14"]`. The important thing to take from this, though, is that *the string is the "real" key, the negative number is just being coerced to match it and everything happens to work out.* The unfortunate effect of this is that the above code, while perfectly valid in JavaScript, doesn't do anything close to what you might expect in TypeScript.

It looks like someone perhaps tried to compensate for this by adding an index signature to the interface, but that doesn't actually address the issue. Adding `[key: number]: ...` doesn't somehow coerce '-106' to a number, it simply says, "these are the keys it definitely has, and it may have *other* keys, which must be numbers." The '-106' is still exactly what it always was: a `string`.

I think that covers the origin of the issue, so now onto the issue itself. Here's one example, although constructs like this occur throughout `index.d.ts`:

```typescript
type FilterFunction<T extends FindConstant> = (object: FindTypes[T]) => boolean;
```

The problem with this is that, in order to do the lookup `FindTypes[T]`, the `FindConstant` type *must* be exactly equal to `keyof FindTypes`. It almost is, except for that one flaw... `FindConstant` is a union of a bunch of `number` types, including -106, while `keyof FindTypes` is a union of all of the *other* `number` types, plus the type '-106'. For some reason, `dtslint` doesn't seem to catch this, but it's not valid TypeScript and will throw errors if you try to compile it. Compounding that, none of the "Find Overloads" tests actually *use* the callback parameter, so `tsc` doesn't catch its invalid type.

Now, if I knew a good, non-breaking workaround that would address this issue, I would, but unfortunately I'm not 100% convinced that it's actually possible. I toyed around with it a bit, and was able to get *very* close, but unfortunately the compiler wasn't able to infer the generics on its own, meaning you had to do something ridiculously awful like `find<'105', 105>(...)` in order for it to even figure out what the return type should be.

Overall, I feel belittled by the fact that there isn't a good solution to all this jumping out at me yet; I feel bad just opening an issue to say "this is broken" without a good alternative, and yet here we are. If you have any input, maybe workshopping it will produce a viable solution. I'm willing to help with that if you'd like. It just seems so dumb that things would be so needlessly complicated by the Screeps developers deciding do use *one* negative value in an enum when all the rest are positive. 😂 Let me know your thoughts and I'll be glad to assist if I can.

(On an unrelated note, I noticed you guys have a lot of unnecessary generics tacked onto non-generic functions, like the `find()` overload for structures... if all the generic does is pin down the return type, and it isn't used in the parameters at all, you can do `find(...) as TypeOfStructure` or `<TypeOfStructure>find(...)` already, without needing the generic argument. In fact, I'd get rid of the generic on the `Structure` interface as well, and just use the value of `structureType` to perform any necessary inference or type guarding, since the compiler knows how to do that, too!)

Cheers!

**Comment by smhxx** [comment]
I think I may have come up with an alternate way of addressing the issue which *may* be more effective than my previous attempt... can't make any promises, but I'll give it a shot sometime today and see if the compiler is smart enough to figure it out without having to spoon-feed it the generic parameters.

**Comment by Arcath** [comment]
@smhxx We develop this in its own repo.

I've opened an issue there liked to this one so we can work on it.

https://github.com/screepers/typed-screeps/issues/39

**Comment by smhxx** [comment]
Given that the discussion has migrated elsewhere, I'll close this to avoid cluttering the DT issues tab
