### ISSUE TITLE
@types/stripe-react-elements missing `stripe` prop on StripeProvider

### ISSUE THREAD

**Issue by dylanpyle** [DefinitelyTyped/DefinitelyTyped#23058]
- [x] I tried using the `@types/stripe-react-elements` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dan-j @santiagodoldan @sonnysangha

---

May open a pull request for this when I get time - but `@types/stripe-react-elements` defines the props for StripeProvider as:

```ts
interface StripeProviderProps {
  apiKey: string;
}
```

When in reality ([see docs here](https://github.com/stripe/react-stripe-elements#loading-stripejs-asynchronously)) it can also accept a Stripe.js instance in place of apiKey when loaded asynchronously.

I'm guessing the answer is to make it a union of `{ apiKey: string } | { stripe: StripeJsInstance }` but I'd have to do some digging to see if there's a good type definition of the latter...

**Comment by dan-j** [comment]
I contributed to these types for a client I'm no longer working with and I'm not fully up to date with the stripe library, but what you propose sounds reasonable. If you create a pull request I'll be happy to review it, just ensure that you have tests for either scenario.

**Comment by 9Y5** [comment]
@dan-j @dylanpyle 

For `StripeJsInstance` which you've suggested, I think we can reference [`stripe.Stripe` from @types/stripe-v3](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/stripe-v3/index.d.ts#L19-L23)

Kindly [review this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23890) and see if it makes sense.

Cheers 😄

**Comment by 9Y5** [comment]
I realised the type definition of `stripe.Stripe.createToken` doesn't quite fit with `react-stripe-elements.createToken`. So will be reverting back to `StripeProps`.

So only change now is adding `props.stripe` to `StripeProvider`.

**Comment by nabrahamson** [comment]
I'm not sure if this is related, but should the StripeProps interface be exported as well? 

I ask this as I'm trying to use injectStripe in a typescript application. I am getting compiler error on the component that I've used injectStripe on saying that there is no property stripe on my state object for my component.

**Comment by itzsaga** [comment]
@nabrahamson did you figure out a workaround? I just hit the same thing.

**Comment by sambokai** [comment]
@itzsaga Haven't tested but the following should work, provided you have Strip() ready:

`<StripeProvider stripe={Stripe('your_public_key')} />`

**Comment by alfonsoperez** [comment]
Checking the type:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-stripe-elements/index.d.ts#L36

My issue was that I was passing `apiKey` as `string | undefined`. Checking that apiKey is set and therefore passing `apiKey` as `string` did the trick.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
