### ISSUE TITLE
signature_pad/index.d.ts is not a module

### ISSUE THREAD

**Issue by lukescott** [DefinitelyTyped/DefinitelyTyped#23061]
- [x] I tried using the `@types/signature_pad` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @AbubakerB @jrmihalick

When I try to import SignaturePad I get `is not a module`:

```ts
import * as SignaturePad from "signature_pad" // ... is not a module
```

**Comment by jrmihalick** [comment]
Try importing this way in your .ts file

`import 'signature_pad';`

then also make sure you have done the following:

1. Added signature pad in your dependencies of package.json:
```
{
...
  "dependencies": {
...
    "@types/signature_pad": "0.0.30",
    "signature_pad": "2.3.0",
...
  }
}
```
2. Added the signature_pad.js file in the scripts section of your .angular-cli.json
```
      "scripts": [
        "../node_modules/signature_pad/dist/signature_pad.js"
      ]
```
(Your path to signature_pad.js may be slightly different)

**Comment by lukescott** [comment]
I don't use Angular, I use React. I found similar issues on DefinetlyTyped, and they added something similar to this, which seems to have solved my problem:

```ts
export = SignaturePad;
export as namespace SignaturePad;
```

(I added this to the bottom of the index.d.ts file)

Not sure if this is the correct solution, but it seems to be working so far. I can PR it if you want.

**Comment by jrmihalick** [comment]
Let me test that addition on angular, then I will get back to you.

**Comment by aluanhaddad** [comment]
The declaration is wrong. As noted in the opening post, it is indeed missing
```ts
export = SignaturePad;
export as namespace SignaturePad;
```

It is a exported UMD module and the types should reflect that.
https://github.com/szimek/signature_pad/blob/master/rollup.configs.js#L40
It isn't related to angular.

If you are using Modules, then both of
```ts
import 'signature_pad';
```
and
```ts
import * as SignaturePad from "signature_pad";
```
are wrong.

Instead you should write
```ts
import SignaturePad = require("signature_pad");
```
or
```ts
import SignaturePad from "signature_pad";
```
This does not depend on Angular, React, or any other framework.

**Comment by SteffenLanger** [comment]
The solution for me was `import SignaturePad from 'signature_pad/src/signature_pad';`.

I use TypeScript 2.7.2.

**Comment by aluanhaddad** [comment]
@SteffenLanger that presumably works because you have set `--allowJs`. While that is useful and the import form you are using is ideal, the declaration should still be fixed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
