### ISSUE TITLE
`npm test` failing DefinitelyTyped/types/zipkin-context-cls

### ISSUE THREAD

**Issue by apurvaojas** [DefinitelyTyped/DefinitelyTyped#23126]
```
Error: In D:\DefinitelyTyped/types/zipkin-context-cls/package.json: Dependency zipkin not in whitelist.
If you are depending on another `@types` package, do *not* add it to a `package.json`. Path mapping should make the import work.
If this is an external library that provides typings,  please make a pull request to types-publisher adding it to `dependenciesWhitelist.txt`.
```

**package.json**
```
{
  "private": true,
  "dependencies": {
    "zipkin": "^0.11.2"
  }
}
```

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @plantain-00

**Comment by plantain-00** [comment]
zipkin is actually in the white list: https://github.com/Microsoft/types-publisher/pull/428
