### ISSUE TITLE
[react-widgets] inputProps missing from DateTimePickerProps

### ISSUE THREAD

**Issue by antmdvs** [DefinitelyTyped/DefinitelyTyped#23136]
https://jquense.github.io/react-widgets/api/DateTimePicker/#inputProps

If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/react-widgets` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rogierschouten @frodehansen2 

If you do not mention the authors the issue will be ignored.

**Comment by r3nya** [comment]
Hey @antmdvs!

I will try to fix it soon. Thanks for your feedback!

**Comment by r3nya** [comment]
Hello @antmdvs! I did it.
Please update package with typings and close this issue. :)

**Comment by antmdvs** [comment]
Hi @r3nya, thank you. The @types/react-widgets package on npm doesn't seem to have the changes yet so I'm unable to verify. Can you publish the changes to npm?

**Comment by r3nya** [comment]
@antmdvs yeah … it's really strange. I asked maintainers about it.

**Comment by r3nya** [comment]
@antmdvs I don't why, but everything is ok right now. :)
Please check https://www.npmjs.com/package/@types/react-widgets

**Comment by antmdvs** [comment]
Looks good. Thank you!
