### ISSUE TITLE
@types/lodash is throwing errors 

### ISSUE THREAD

**Issue by lmckeen** [DefinitelyTyped/DefinitelyTyped#23144]
- Authors: @DomiR @andy-ms 

I have a travis-ci build that I run once every 24 hours and sometime between yesterday and today, it has errored without any changes on our end.

ERROR in [at-loader] ./node_modules/@types/lodash/index.d.ts:277:1 TS6053: File '/home/travis/build/theREDspace/HammerSpace/node_modules/@types/lodash/seq/prototype[Symbol.iterator].d.ts' not found.

[here is a link to the travis build](https://travis-ci.org/theREDspace/HammerSpace/jobs/332484136)

if you have any ideas that would fix this problem this would be greatly appreciated

**Comment by DomiR** [comment]
Sorry about that, I introduced some auto-generated empty files (including the one mentioned above), which will be removed soon. My guess would be the weird filename...

**Comment by lmckeen** [comment]
this still seems to be an issue

**Comment by DomiR** [comment]
Unfortunately the npm mirror process takes some time... sorry mate.

**Comment by lmckeen** [comment]
This issue has been fixed! Thank you guys for the awesome, quick replies and keep up the good work 😄

**Comment by andy-ms** [comment]
You might also consider reporting a bug with `at-loader` since it thinks empty files don't exist.

**Comment by lmckeen** [comment]
this seems to be an [issue](https://github.com/s-panferov/awesome-typescript-loader/issues/320) that is already tracked in the repo for the webpack typescript loader that we use
