### ISSUE TITLE
[lodash] `zip` and `zipWith` do not allow arrays of different types

### ISSUE THREAD

**Issue by Deilan** [DefinitelyTyped/DefinitelyTyped#23221]
- [X] I tried using the `@types/lodash@4.14.96` package and had problems.
- [X] I tried using the `2.6.2` version of tsc.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel, @chrootsu, @stepancar, @ericanderson, @aj-r, @ailrun, @e-cloud, @thorn0, @jtmthf, @DomiR

`_.zip` and `_.zipWith` do not allow arrays of different types.

Example:
```ts
_.zip(['a', 'b'], [1, 2], [true, false]);
_.zipWith(['a', 'b'], [1, 2], [true, false], (a, b, c) => ({ a, b, c }))
```

Error:
```
[ts]
Argument of type 'string[]' is not assignable to parameter of type 'ArrayLike<number> | ((...group: number[]) => {}) | null | undefined'.
  Type 'string[]' is not assignable to type '(...group: number[]) => {}'.
    Type 'string[]' provides no match for the signature '(...group: number[]): {}'.
```

Reference:
- [zip](https://lodash.com/docs/4.17.4#zip)
- [zipWith](https://lodash.com/docs/4.17.4#zipWith)

**Comment by aj-r** [comment]
As a workaround, you can explicitly pass a type argument, e.g.

```ts
_.zip<string | number | boolean>(['a', 'b'], [1, 2], [true, false]);
```
