### ISSUE TITLE
Lodash _.find does not successfully catch invalid partial object matches

### ISSUE THREAD

**Issue by pimterry** [DefinitelyTyped/DefinitelyTyped#23293]
Both of the below errors should be caught by the TypeScript compiler (with `--strict`). It should be possible to catch these kind of errors generally, and they're certainly not valid calls, but the current Lodash types don't complain at all:

```ts
_.find([{ id: 1 }], { notId: 1 })
_.find([{ id: 1 }], { id: 'hi' })
```

The first should fail as it has no overlapping fields, and the 2nd because the matching field has the wrong type.

I'm using `typescript@2.6.2` & `@types/lodash@4.14.98`, both latest.

---

- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @lukas-zech-software, @aj-r, @ericanderson, @bczengel (my best guess at who might be interested, don't want to ping everybody in the quite long authors list!)

**Comment by aj-r** [comment]
Interesting. I know at one time we accepted any object type as the
predicate. But I thought we changed it to force a partial object match. Not
sure why that's not working.

**Comment by aj-r** [comment]
Found the culprit:

```ts
type ListIterateeCustom<T, TResult> = ListIterator<T, TResult> | string | object | [string, any] | PartialDeep<T>;
```

The `object` type should be removed.

**Comment by aj-r** [comment]
Looks like there are a lot of open lodash issues right now. I'd appreciate if anyone made a PR for this (@bczengel @chrootsu @stepancar @ericanderson @https://github.com/ailrun @https://github.com/e-cloud @thorn0 @jtmthf @Domir). Just comment here if you're working on it so we don't step on each other's feet :)

**Comment by aj-r** [comment]
I tested removing `| object` from the line above. It's not perfect but it makes things better:

```ts
const result = _.find([{ id: 1 }], { notId: 1 }); // No error but result has a strange type: number | ((searchElement: {...
const result: { id: 1 } | undefined = _.find([{ id: 1 }], { notId: 1 }); // Error
```
I think this is at least better than the old behavior where this passed:

```ts
const result: { id: 1 } | undefined = _.find([{ id: 1 }], { notId: 1 }); // No error in v4.14.107!
```
