### ISSUE TITLE
Definition request for nanoscroller

### ISSUE THREAD

**Issue by asurabhi** [DefinitelyTyped/DefinitelyTyped#2333]
It is a jquery plugin to implement custom scrollbars hosted at https://github.com/jamesflorentino/nanoScrollerJS.
Is anyone ready to spend their efforts on this library?
I am eager to do it, but not able to allocate time to it now.
I can spend time only after few weeks. If anyone started on it, please put a message on it, to avoid duplicate effort.

**Comment by brauliobo** [comment]
+1

**Comment by Zihark17** [comment]
This can be closed #14944
