### ISSUE TITLE
[lodash] support lodash/core

### ISSUE THREAD

**Issue by aj-r** [DefinitelyTyped/DefinitelyTyped#23332]
Adding an issue for this so I don't forget. We should support this:

```ts
import _ from "lodash/core";
```

This should be easy now that each function is split into its own file. Just add a `core.d.ts` that is like `index.d.ts`, but references only the relevant functions.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel, @chrootsu, @stepancar, @ericanderson, @ailrun, @e-cloud, @thorn0, @jtmthf, @DomiR

**Comment by aj-r** [comment]
Looks like there are a lot of open lodash issues right now. I'd appreciate if anyone made a PR for this (@bczengel @chrootsu @stepancar @ericanderson @https://github.com/ailrun @https://github.com/e-cloud @thorn0 @jtmthf @Domir). Just comment here if you're working on it so we don't step on each other's feet :)

**Comment by aj-r** [comment]
See https://github.com/lodash/lodash/wiki/Build-Differences

**Comment by aj-r** [comment]
I added a preliminary commit for this (https://github.com/aj-r/DefinitelyTyped/commit/d40601013e71b0c295a50d7d107e50a56e0f6aa0). However, I don't think it's possible to properly support chaining wrappers until we get [Conditional Types]() in TS2.8. But we currently need to keep support with TS2.2.

One possible workaround would be to change our file structure (yet again) so are core functions are defined in one file (`core.d.ts`), and all non-core functions are in another file (`index.d.ts`). Then have `index.d.ts` also re-export all of the functions in `core.d.ts`. However I don't feel like this is worth it unless we get a lot of demand for `"lodash/core"`. If you want to see this, give this issue a thumbs-up 👍 .

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
