### ISSUE TITLE
error TS2694: Namespace 'request' has no exported member 'Response'.

### ISSUE THREAD

**Issue by saisnigdhap** [DefinitelyTyped/DefinitelyTyped#23341]
Hi,
Getting the below exception with npm package @types/request-promise-native version 1.0.12, issue is not reproducible for previous versions. Could anyone look into this asap.
node_modules/@types/request-promise-native/index.d.ts(20,49): error TS2694: Namespace 'request' has no exported member 'Response'.
node_modules/@types/request-promise-native/index.d.ts(24,33): error TS2694: Namespace 'request' has no exported member 'Response'.

Got the below code that is causing the error:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a436740d5ddaff62e522da2ae212031acb7ef935/types/request-promise-native/index.d.ts#L20

Thanks.

**Comment by mastermatt** [comment]
Make sure `@types/request` gets updated >= 2.47.0 when you update `@types/request-promise-native`. The two libs were updated with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23004.

**Comment by saisnigdha93** [comment]
Thank you, this worked.

**Comment by jwhitmarsh** [comment]
I'm having the same issue with `@types/request-promise@4.1.41`. I've installed `@types/request@2.47.0` but it looks like it's still depending on the nested `@types/request` (`/node_modules/@types/request-promise/node_modules/@types/request/index.d.ts`) rather than the version I've installed. 

Is this an issue with my config, or with the package?

**Comment by mastermatt** [comment]
@jwhitmarsh `@types` adds other `@types` as dependancies using `"@types/request": "*"`.
So how you update your decencies makes a difference. 
Just running `npm install @types/request@2.47.0` will not do the job. I'm away from my comp atm, so I can't test if `npm update` is all you need to run after setting `@types/request-promise` to a new version in your `package.json`. Give that a try, of course just deleting `node_modules` and `npm install` is an (probably overkill) option.

That being said, @saisnigdha93 or some core dev can close this issue now.

**Comment by jwhitmarsh** [comment]
@mastermatt thank you! I've never come across having to use `npm update` after an `npm install` before.

**Comment by mastermatt** [comment]
@jwhitmarsh did you already have `@types/request` installed by chance? I'm curious if it had to do with reusing a cached version. 
Sorry for the extra work, I don't think it's possible in `@types` to declare a minimum version for other `@types`, as `Microsoft/types-publisher` will error if you try to add one to a `package.json`.

**Comment by jwhitmarsh** [comment]
I'm not sure that'd I'd _never_ had it installed before. It was newly added to that project, but I might have used it before in another project which presumably will have set the cache - your theory sounds plausible, I'm sorry I can't help confirm it :(

No apology necessary at all - very grateful for your help resolving it.

**Comment by dotansimha** [comment]
Same here. adding `@types/request` causes it to duplicate and the tsc throws errors regarding duplicate symbols.

**Comment by mastermatt** [comment]
@dotansimha you shouldn't need to add `@types/request` explicitly, however, it seems you need to double check which version npm has installed under `@types/request-promise-native`. 
From the comments above, it looks like `npm update` does the trick.

**Comment by dotansimha** [comment]
@mastermatt 
I tried to clean all node_modules in my project, clear Yarn cache, and then reinstall the dependencies.
My `package.json` specify `"@types/request-promise-native": "1.0.14",`, without `@types/request`.

Under `node_modules/@types/`, I have now `@types/request-promise-native` v1.0.14, and `@types/request` v2.0.9 (both in root, same depth level).

Still getting:
```
node_modules/@types/request-promise-native/index.d.ts(20,49): error TS2694: Namespace 'request' has no exported member 'Response'.
node_modules/@types/request-promise-native/index.d.ts(25,33): error TS2694: Namespace 'request' has no exported member 'Response'.
````

**Comment by NerijusV** [comment]
I have sold this issue adding earlier version of @types/request-promise

```
npm install --save-dev @types/request-promise@^3.0.32
```
Hope it helps.

**Comment by sdeprez** [comment]
Same than @dotansimha, the only fix was to downgrade `yarn add @types/request-promise-native@0.9 --dev`

**Comment by unnieayilliath** [comment]
@NerijusV  thanks downgrading solved my issue too ! This is crazy

**Comment by nadavye** [comment]
Any update on this one?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
