### ISSUE TITLE
getInitialProps for next

### ISSUE THREAD

**Issue by Industrial** [DefinitelyTyped/DefinitelyTyped#23356]
If you know how to fix the issue, make a pull request instead.

- [ X ] I tried using the `@types/next` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @brikou 

If you do not mention the authors the issue will be ignored.

**Comment by jadengore** [comment]
Looks like there's an implementation here: https://github.com/stevangoode/NextReact

**Comment by vfaramond** [comment]
Fixed with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25711
