### ISSUE TITLE
SP.Search - SortCollection Add Method definition is incorrect

### ISSUE THREAD

**Issue by tyaramis** [DefinitelyTyped/DefinitelyTyped#2335]
Please fix the type definition for SortCollection class in SP.Search.d.ts. The signature of add() method should be changed.

  export class SortCollection extends SP.ClientObjectCollection<Sort> {
            itemAt: (index: number) => Sort;
            get_item: (index: number) => Sort;
            get_childItemType: () => Object;
            add: (property: Sort) => void;
            clear: () => void;
        }

should be;

export class SortCollection extends SP.ClientObjectCollection<Sort> {
            itemAt: (index: number) => Sort;
            get_item: (index: number) => Sort;
            get_childItemType: () => Object;
            add: (property: string, sortDirection: SortDirection) => void;
            clear: () => void;
        }

**Comment by smayes5** [comment]
This was fixed in commit 8d7e5ce and I believe this issue can be closed.
