### ISSUE TITLE
Problem with connect() in @types/react-redux (all typings latest version)

### ISSUE THREAD

**Issue by ch1ll0ut1** [DefinitelyTyped/DefinitelyTyped#23359]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @thasner @clayne11 @tansongyang @NicholasBoll @mDibyo @pdeva 

**Versions**
TS: 2.7.1
types/react-redux: 5.0.14
types/react: 16.0.36 (react 16.2.0)
redux: 3.7.2

**Problem:**

Since upgrading to react 16.2 from 15.x the typings are broken in many places, often it helped upgrading the typings and libs i was using. For redux it did not.

I read other issues that are related like:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16990
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21640

I tried everything and even cant make it work if not using any optional props and defining all types.

Here a list of cases that dont work:

optional prop case with loose typing
```javascript
namespace MapStateOptionalProp {

  interface Props {
    bar: number,
    test: boolean
  }

  const TestComponent: React.StatelessComponent<Props> = (props: { bar: number, test: boolean }) => <div />

  const mapStateToProps = (_: any) => ({
    bar: 1,
    test: false
  })

  const Test = connect(
    mapStateToProps
  )(TestComponent)

  const verify = <Test />  // error: 
}
```

error:
```javascript
[ts]
JSX element type 'Component<Pick<Props, never>, ComponentState>' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => ReactNode' is not assignable to type '{ (): ReactNode; (): false | Element | null; }'.
      Type 'ReactNode' is not assignable to type 'false | Element | null'.
        Type 'undefined' is not assignable to type 'false | Element | null'.
const Test: React.ComponentClass<Pick<Props, never>> & {
    WrappedComponent: React.ComponentType<Props>;
}
```

very strict typed all props required
```javascript
interface MyProps {
    section: string;
    name: string;
    selected: boolean;
    onSelect: (name: string) => void;
  }

  interface MyStateProps {
    name: string;
    selected: boolean;
  }

  interface MyDispatchProps {
    onSelect: (name: string) => void;
  }

  interface MyOwnProps {
    section: string;
  }

  class MyComponent extends React.Component<MyProps, {}> { }

  function mapStateToProps(state: IStore): MyStateProps {
    return {
      name: '',
      selected: true,
    }
  }

  function mapDispatchToProps(dispatch: any): MyDispatchProps {
    return {
      onSelect: (name: string) => {
        return;
      },
    }
  }

  const MyContainer = connect <MyStateProps, MyDispatchProps, MyOwnProps>(
    mapStateToProps,
    mapDispatchToProps
  )(MyComponent);

  const verify = <MyContainer section="" /> /// error
```
error:
```javascript
[ts]
JSX element type 'Component<Pick<MyProps, "section"> & MyOwnProps, ComponentState>' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => ReactNode' is not assignable to type '{ (): ReactNode; (): false | Element | null; }'.
      Type 'ReactNode' is not assignable to type 'false | Element | null'.
        Type 'undefined' is not assignable to type 'false | Element | null'.
const MyContainer: React.ComponentClass<Pick<MyProps, "section"> & MyOwnProps> & {
    WrappedComponent: React.ComponentType<MyProps>;
}
```

**Comment by cyberhck** [comment]
@ch1ll0ut1 does link we referenced from make any sense, do you think it's related?

**Comment by guillaume86** [comment]
Any news on this? I have a similar issue, all my connected components have their type inferred as `any` now so I lost a lot of type safety/autocomplete goodness in my project.

**Comment by aappddeevv** [comment]
Whatever update happend as described above, broke the check of many of my components plus I get "is not a constructor function for JSX elements."

I could not make sense of the link...what's the advice here?

**Comment by aappddeevv** [comment]
Not sure this is still an issue but I've hit this hard. *Only* components that result from a "connect" are showing this error. Anything else seems to be fine.

**Comment by mukuljainx** [comment]
Hi, any update on this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
