### ISSUE TITLE
Convert a module-based typing into typing without module system

### ISSUE THREAD

**Issue by voltcode** [DefinitelyTyped/DefinitelyTyped#23377]
I moving a large codebase from VS 2013, TS 1.8 into VS 2017 TS 2.5.

The biggest hurdle is getting TS to work correctly. We're using some older react typings, like react.d.ts and react-dom.d.ts

What I want to do is to stay away from TS modules if I can, I'd like to somehow convert (automatically) typings like:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom
into old style typings without modules (they have been available in the past).

How can I perform such conversion, is it at all possible? TSC seems to ignore commands to compile index.d.ts into a something without a module system. Or should I give up and focus on moving into modules (I have quite a few projects to migrate, I'd rather reduce complexity and move to modules after VS 2017 builds everything correctly.

**Comment by aluanhaddad** [comment]
@voltcode it already works that way. See https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html

**Comment by voltcode** [comment]
I'm not sure what you've meant. Whether all typings as they are should already support both usages (with and without a module), and if a typing fails to do so then it is a bug in the typing? Or should I be manually patching the .d.ts somehow (please tell me how) just to make it work without module system?
 
I managed to get past react-dom issues and am stuck at 
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-addons-css-transition-group
and several other addons.

I have no idea how to use the ReactCSSTransitionGroup  from typings in a csproj without module system.
No matter what I try, tsx fails on compilation with reference to ReactCSSTransitionGroup component (in tsx i try to instantiate ReactCSSTransitionGroup).

**Comment by aluanhaddad** [comment]
Many JavaScript libraries support use as both a module or a global and the typings should reflect that and only that.

Check the documentation of the package, check its source code if necessary and determine if it supports your use case. Another  thing you might want to do is to run your code and see if it works. I don't mean if it passes typechecking but whether it runs.

If a package works as a global variable but such usage fails to type check in a non modular project then there is likely an error in the type declaration that should be fixed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
