### ISSUE TITLE
[lodash] Type 'T' does not satisfy the constraint 'object'.

### ISSUE THREAD

**Issue by Ixonal** [DefinitelyTyped/DefinitelyTyped#23375]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @ericanderson @aj-r @Ailrun 

I just did an update of my npm packages and started getting an error in my builds:

> ERROR in [at-loader] ./node_modules/@types/lodash/index.d.ts:12651:53
> Type 'T' does not satisfy the constraint 'object'.

This initially confused me, as I'm not including lodash in my project. After some digging, it appears that TypeDoc recently updated their type dependencies (https://github.com/TypeStrong/typedoc/pull/689/commits/afd6b606631c096624c3a1bf0c0a91ba1d1c640c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R36). I would put in an issue there, but this seems more to be an issue specific to the types.

What it's complaining about, specifically seems to be this:
```typescript
    //_.isWeakSet
    interface LoDashStatic {
        /**
         * Checks if value is classified as a WeakSet object.
         *
         * @param value The value to check.
         * @returns Returns true if value is correctly classified, else false.
         */
        isWeakSet<T>(value?: any): value is WeakSet<T>;
    }
```

In particular, "isWeakSet<T>(value?: any): value is WeakSet<**T**>;"
If I alter T to extend object, the error goes away, but wanted to make sure that's the appropriate fix.

**Comment by aj-r** [comment]
What version of typescript are you using? I suspect this is due to a
breaking change in TS 2.7

**Comment by Ixonal** [comment]
typescript@2.7.1 right now.

**Comment by aj-r** [comment]
Ok. Looks like we need to update our WeakSet and WeakMap interfaces to be
compatible with 2.7. However that will break backwards compatibility with
older versions of typescript.

**Comment by Ixonal** [comment]
Ok, yeah, switching back to typescript@2.6.2 got rid of the error, so that seems to be the issue.

**Comment by aj-r** [comment]
Looks like there are a lot of open lodash issues right now. I'd appreciate if anyone made a PR for this (@bczengel @chrootsu @stepancar @ericanderson @https://github.com/ailrun @https://github.com/e-cloud @thorn0 @jtmthf @Domir). Just comment here if you're working on it so we don't step on each other's feet :)

**Comment by paralin** [comment]
This is killing me right now - has anyone found a workaround in TypeScript 2.7? I'll see if I can find one.

**Comment by aj-r** [comment]
You could try targeting es5? Ultimately we just need to update lodash's
WeakSet interface to match typescript's (I.e. add "extends object") and
update the function call as the OP mentioned. It's a really easy fix so if
someone submits a PR I'll review it.

On Feb 14, 2018 9:40 PM, "Christian Stewart" <notifications@github.com>
wrote:

This is killing me right now - has anyone found a workaround in TypeScript
2.7? I'll see if I can find one.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23375#issuecomment-365810491>,
or mute the thread

**Comment by paralin** [comment]
Nice one, I think targeting es5 with commonjs modules fixes it as a nice short-term workaround.

**Comment by paralin** [comment]
AJ Richardson writes:
> You could try targeting es5? Ultimately we just need to update lodash's
> WeakSet interface to match typescript's (I.e. add "extends object") and
> update the function call as the OP mentioned. It's a really easy fix so if
> someone submits a PR I'll review it.

I have tried this and it seems to work, mostly. Except for one of my projects.

Tsconfig:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "moduleResolution": "node",
        "lib": ["es2015", "es2016", "es2017", "dom"],
        "strict": true,
        "sourceMap": true,
        "declaration": true,
        "allowSyntheticDefaultImports": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declarationDir": "dist/types",
        "outDir": "dist/es",
        "typeRoots": [
          "node_modules/@types"
        ]
    },
    "exclude": [
        "test",
        "dist",
        "coverage",
        "node_modules",
        "prototree"
    ]
}
```

Error:

```
node_modules/@types/lodash/index.d.ts(12651,53): error TS2344: Type 'T' does not satisfy the constraint 'object'.
```

Targeting es5 doesn't seem to fix the error.

**Comment by aj-r** [comment]
It's probably the lib: es2016 and es2017 that's doing it. You can try
removing the while libs and replacing them with the specific parts of the
libs that you need (e.g. es2016.Promise).

**Comment by thehappycoder** [comment]
Removing `es2016` and `es2017` doesn't help. Downgrading to ts-2.6

**Comment by aj-r** [comment]
@Ixonal @paralin @thehappycoder what version of `@types/lodash` are you using? I can't reproduce this error in the latest version (4.14.103). I checked the types and it looks like this now:

```ts
isWeakSet(value?: any): value is WeakSet<object>;
```

So it looks like someone has fixed this already.

**Comment by Ixonal** [comment]
@aj-r 4.14.74, but it's a third party dependency, so I'm not really in control of the versioning.

**Comment by aj-r** [comment]
Ok, so your third party probably needs to update their dependency. You might be able to control the version anyway by running `npm install -S @types/lodash@latest` (or similar in yarn). See if that fixes it.

**Comment by aj-r** [comment]
@Ixonal want to close this issue if it's working now?

**Comment by slinker-hiwa** [comment]
Lodash version: lodash@4.17.4 and @types/lodash@4.14.110
Working fine.

**Comment by patrickroberts** [comment]
Does [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/index.d.ts#L44) need to be updated?

Suggestion:

        interface WeakSet<T extends object> { }

Currently:

        interface WeakSet<T> { }

**Comment by GoygovRustam** [comment]
This issue is blocking update to angular 6. Angular 6 requires typescript version >= 2.7.2 . 
Is it possible to update lodash? I see people suggesting a change, could those changes be accepted?

**Comment by GoygovRustam** [comment]
fixed this by installing latest types.  "@types/lodash": "^4.14.110",

`npm install @types/lodash^4.14.110`

**Comment by aj-r** [comment]
@Ixonal can you close this issue if it's working? Unfortunately I don't have the power to close it :(

**Comment by Ixonal** [comment]
Sorry, thought y'all had close power :D

**Comment by agillesp** [comment]
This is broken again @4.14.129, but in a new place. I can fix things by changing

   `isWeakSet<T>(value?: any): value is WeakSet<T>;`

to

   `isWeakSet<T extends object>(value?: any): value is WeakSet<T>;`

**Comment by aj-r** [comment]
@agillesp I don't follow - the current definition for that function is:

```ts
isWeakSet(value?: any): value is WeakSet<object>;
```

There is no `T` parameter (although maybe there should be).

**Comment by patrickroberts** [comment]
@aj-r a type parameter should only be used if the function explicitly uses that type. Seeing as 

```ts
function isWeakSet<T extends object>(value?: any): value is WeakSet<T> {
  return value instanceof WeakSet;
}
```

does not use `T` anywhere in its body, nor does it actually determine that `value` is a `WeakSet<T>` _specifically_, the type parameter is not only unnecessary, but actually harmful since it incorrectly constrains the type of `value` more than was actually determined, which could eventually lead to a runtime error due to a wrong assumption about the contained type of the `WeakSet`.

**Comment by agillesp** [comment]
Ah, drat, sorry for the noise (and wasting your time). This was bubbling up from a subdir `node_modules` which had a much older version installed. All is well now.

**Comment by stakkdev** [comment]
> 

Thank you sir

it's working for me
