### ISSUE TITLE
Should pdfjs-dist export a PDFJS object?

### ISSUE THREAD

**Issue by sid-kap** [DefinitelyTyped/DefinitelyTyped#23397]
It appears, according to the test, that to use these typings you have to declare a variable PDFJS of type PDFJSStatic:
```
var PDFJS: PDFJSStatic;
```
(as is done in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/80589689957696f66bfd59960aadd2c5bc2cac31/types/pdfjs-dist/pdfjs-dist-tests.ts#L8)
If such a variable does exist in the global namespace, shouldn't the d.ts file include this as well, so that every user doesn't have to do this themselves?

**Comment by sid-kap** [comment]
cc @jbaldwin

**Comment by andy-ms** [comment]
Actually, looking at the installed package, it appears to be a UMD module that writes to a `pdfjsDistBuildPdf` global variable if not loaded as a module. Could you test what works for you at runtime (ignoring compile errors for now)?

**Comment by sid-kap** [comment]
Here's what has been working for me at runtime:
```typescript
import { PDFJSStatic } from "pdfjs-dist"
let PDFJS: PDFJSStatic = require("pdfjs-dist")
```
But I would prefer to do one of
```typescript
import { PDFJS } from "pdfjs-dist"
```
or 
```typescript
import * as PDFJS from "pdfjs-dist"
```

**Comment by sid-kap** [comment]
```typescript
import { PDFJS } from "pdfjs-dist"
```
was also working for me at runtime, before I turned on `"noImplicitAny": true`. (It must have been treating `PDFJS` as an `any` type.)

**Comment by andy-ms** [comment]
> was also working for me at runtime, before I turned on "noImplicitAny": true

That doesn't make sense, `noImplicitAny` shouldn't affect runtime behavior.

**Comment by sid-kap** [comment]
Sorry if I wrote something misleading. What I mean is that it was working both at compile time and runtime, but then I turned on `noImplicitAny`, so it no longer compiles, which is why I switched to the following import:
```typescript
import { PDFJSStatic } from "pdfjs-dist"
let PDFJS: PDFJSStatic = require("pdfjs-dist")
```

**Comment by sid-kap** [comment]
But the point is, importing `PDFJS` as a member of the module `"pdfjs-dist"` works... it just doesn't compile under the existing `d.ts`

**Comment by sid-kap** [comment]
The thing that confuses me is that both importing it as a module and importing the `PDFJS` object
 from the module work at runtime. How is that possible?

**Comment by andy-ms** [comment]
The module appears to have a `PDFJS` member, however, this member has different keys from the module itself, so those two imports aren't identical. The typings appear to describe the `PDFJS` member rather than the module as a whole though, so I think they could be improved by adding `const PDFJS: PDFJSStatic;` to `namespace PDF`. I'll make a PR.

**Comment by sid-kap** [comment]
Great, thanks!!
