### ISSUE TITLE
[@types/mongoose] Incorrent callback signature for schema.post() method

### ISSUE THREAD

**Issue by nicky-lenaers** [DefinitelyTyped/DefinitelyTyped#23406]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @simonxca @horiuchi @sindrenm @lukasz-zak

If you do not mention the authors the issue will be ignored.

I have already layed out the full issue on the official mongoose repo, only to find out the issue does not belong there. Instead, based on my findings I concluded the issue belongs here.

**[Link to original issue](https://github.com/Automattic/mongoose/issues/6084)**

Brief summary:

I am using a `post()` hook on a schema. The hook is defined **before** the Model is created, which is the order the docs specify. The code looks like this:

```ts
projectSchema.post('save', (doc, next) => {
  console.log("POST SAVE", doc);
  next();
});
```

I find some trouble on the static type checker from TypeScript. The type definition looks like this:

```ts
/**
     * Defines a post hook for the document
     * Post hooks fire on the event emitted from document instances of Models compiled
     *   from this schema.
     * @param method name of the method to hook
     * @param fn callback
     */
    post<T extends Document>(method: string, fn: (
      error: mongodb.MongoError, doc: T, next: (err?: NativeError) => void
    ) => void): this;

    post<T extends Document>(method: string, fn: (
      doc: T, next: (err?: NativeError) => void
    ) => void): this;
```

Especially the second one defines the callback function with 2 parameters, `doc` and `next`. But when I use this, TypeScript type checker finds errors:

**1. The `next` function is red underlined**
![1-next-error](https://user-images.githubusercontent.com/2785350/35771731-ac95e0a4-0931-11e8-9cc5-ad65a8edddcd.png)

**2. The type of `next` is incorrect, it is trying to be of type `Document`. I do not agree with him.**
![2-next-description](https://user-images.githubusercontent.com/2785350/35771740-d8d47fb8-0931-11e8-98b2-1e3312ddcf27.png)

**3. The description of `doc` is also incorrect, as it tries to be an Error. No can do, you `doc`**
![3-doc-description](https://user-images.githubusercontent.com/2785350/35771747-ff00c7e6-0931-11e8-9755-2f3452f59268.png)

I guess this should be fixed here.

Thank you!

**Comment by nicky-lenaers** [comment]
@simonxca @horiuchi @sindrenm @lukasz-zak Any of you guys looking into this issue currently?

**Comment by simonxca** [comment]
@nicky-lenaers unfortunately, it looks like Typescript is not able to detect the override of `fn` it thinks it's always the first type (with 3 arguments). You'll have to add explicit types here:
```ts
projectSchema.post('save', (doc: Document, next: Function) => {
  ...
});
```

**Comment by nicky-lenaers** [comment]
@simonxca Thanks for your response, I see. I did notice that, when the order is reversed, the types are correct. I think it's also worth mentioning that [TypeScript 2.8](https://blogs.msdn.microsoft.com/typescript/2018/03/27/announcing-typescript-2-8/) comes with [conditional types](https://blogs.msdn.microsoft.com/typescript/2018/03/27/announcing-typescript-2-8/#conditional-types) that would fix this problem.

Anyway, thanks again. I'll be able to continue from here!

**Comment by jbaranski** [comment]
The signature doesn't understand that the first argument can be a regexp. Do you want another bug for that?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
