### ISSUE TITLE
[d3-selection] Update to v1.3.0

### ISSUE THREAD

**Issue by Ledragon** [DefinitelyTyped/DefinitelyTyped#23433]
[d3-selection v1.3.0](https://github.com/d3/d3-selection/releases/tag/v1.3.0) is out. New API comprises two new methods that need being added.

cc @tomwanzek @gustavderdrache @borisyankov

**Comment by tomwanzek** [comment]
Thanks for the gentle nudge. Already in the pipeline: see PR #23323. 😄 

You can close this issue in favour of the one linked to the PR for closure: #23252 .

**Comment by Ledragon** [comment]
Sh*t, I checked the issues but did not find it... Even though you mentioned me. I guess I should go to bed instead of wasting your time -_-

**Comment by tomwanzek** [comment]
No time wasted. It's a sunny day beyond my laptop screen 🌞

**Comment by Ledragon** [comment]
Wow, where do you live? It'9:30PM, pitch dark,  and freezing outside here...

**Comment by tomwanzek** [comment]
3:30PM -7 Celsius, beautiful sun, light ❄️  for later tonight when it's time to hit the gym in Toronto. 😉
