### ISSUE TITLE
[d3] Update to v4.13

### ISSUE THREAD

**Issue by Ledragon** [DefinitelyTyped/DefinitelyTyped#23434]
[d3 v4.13](https://github.com/d3/d3/releases/tag/v4.13.0) is out, referencing `d3-selection` v1.3.0.

cc @tomwanzek @gustavderdrache @borisyankov

**Comment by tomwanzek** [comment]
Once #23323 is merged, we could theoretically publish D3 4.13. However, my strong preference would be to resolve the blocking issue #23257 regarding dependency pinning.

I would prefer to publish a last patch release for D4 v4.12 which already pins the minor dependencies (with d3-selection 1.2). Afterwards, we would publish D3 v4.13 with updated dependencies.

**Comment by Ledragon** [comment]
Yes, I thought this might come up. It is time we start to pay close attention to what version of the dependent modules is used for each version of the bundle...

**Comment by tomwanzek** [comment]
We did in the beginning, we always pinned D3 to minor versions of its `@types/d3-xxx` dependencies. Then the `package.json` stub in our repo folder was removed. Now that we have backwards breaking changes inbound, it's not just a hypothetical  anymore...

**Comment by Ledragon** [comment]
I remember that, it made things so easy... But anyway, let's not have that conversation here, while it is already open somewhere else ^^

**Comment by tomwanzek** [comment]
Agreed.

**Comment by tomwanzek** [comment]
@Ledragon Doing some housekeeping, we can close this one now 🎉
