### ISSUE TITLE
esModuleInterop breaking tests

### ISSUE THREAD

**Issue by Alorel** [DefinitelyTyped/DefinitelyTyped#23435]
Tests are now failing instantly after bef4d2b27db722a9e5f262d470fa3e010b0f93e3

See #23427's files changed and the resulting [build error](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/337720091#L3011).

@andy-ms

**Comment by andy-ms** [comment]
Fixed in master, thanks. Didn't realize that PR was merged (github said it failed to merge, then unicorned...)
