### ISSUE TITLE
@types/webpack#3.8.5 url issue

### ISSUE THREAD

**Issue by uncleramsay** [DefinitelyTyped/DefinitelyTyped#23456]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @bumbleblym @bcherny @tommytroylin @mohsen1 @jcreamer898 @ahmed-taj @alan-agius4 @elliottsj 

---

The latest version of  `@types/webpack` seems to have a different url path:

```
$ npm view @types/webpack@3.8.4 dist

{ integrity: 'sha512-xZ1XD7he+dji6Gs1L8OuY44uzXnruD7Ron1gpA59sC+M8Zmg97V26uchuBJh1B1NOQA1m4Upc72k8ROtNli0tg==',
  shasum: '82069b43851ac7fdb94f96245758903c2a989107',
  tarball: 'https://registry.npmjs.org/@types/webpack/-/webpack-3.8.4.tgz' }


$ npm view @types/webpack@3.8.5 dist

{ integrity: 'sha512-YrRis2hq8PxzGkOfF33pW7bPpCmb26BfkIv2odCiqhnd0PwXfg3oNPbeiS+DY6iT11Yx0Bq4XUgE527NGmcM2w==',
  shasum: '793a0dc6c49900095313c4f424eda6fb814dd76b',
  tarball: 'https://registry.npmjs.org/@types/webpack/-/@types/webpack-3.8.5.tgz' }
```

Note the extra `@types` in the latter's tarball path.

This is messing up our private registry, which can't resolve the new path. Any ideas why this happened?

Many thanks

**Comment by feltnerm** [comment]
Chiming in to say you're not alone and I am experiencing the same issue. Using artifactory/jfrog as our private registry.

```sh
$ npm view @types/webpack@3.8.4 dist

{ tarball: 'https://widen.jfrog.io/widen/api/npm/npm-virtual/@types/webpack/-/webpack-3.8.4.tgz',
  shasum: '82069b43851ac7fdb94f96245758903c2a989107' }
```

```sh
$ npm view @types/webpack@3.8.5 dist

{ tarball: 'https://widen.jfrog.io/widen/api/npm/npm-virtual/@types/webpack/-/@types/webpack-3.8.5.tgz',
  shasum: '793a0dc6c49900095313c4f424eda6fb814dd76b' }
```

w/ npm's default registry:

```sh
$ npm view --registry https://registry.npmjs.org @types/webpack@3.8.4 dist

{ integrity: 'sha512-xZ1XD7he+dji6Gs1L8OuY44uzXnruD7Ron1gpA59sC+M8Zmg97V26uchuBJh1B1NOQA1m4Upc72k8ROtNli0tg==',
  shasum: '82069b43851ac7fdb94f96245758903c2a989107',
  tarball: 'https://registry.npmjs.org/@types/webpack/-/webpack-3.8.4.tgz' }
```

```sh
$ npm view --registry https://registry.npmjs.org @types/webpack@3.8.5 dist

{ integrity: 'sha512-YrRis2hq8PxzGkOfF33pW7bPpCmb26BfkIv2odCiqhnd0PwXfg3oNPbeiS+DY6iT11Yx0Bq4XUgE527NGmcM2w==',
  shasum: '793a0dc6c49900095313c4f424eda6fb814dd76b',
  tarball: 'https://registry.npmjs.org/@types/webpack/-/@types/webpack-3.8.5.tgz' }
```

**Comment by ferdaber** [comment]
Adding in that this is actually breaking VS Code's automatic type acquisition since it will attempt to install `@types/webpack@latest` and errors out during the install, thus preventing any types from being automatically downloaded if you don't already have them cached.

**Comment by atiniir** [comment]
Also joining the bandwagon on this.  I'm working with jFrog support as well to see if they can provide any insight or workarounds

**Comment by darrennolan** [comment]
Did this get resolved with a new version? I see artifactory haven't responded yet, but I'm keen to reenable it on our builds.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
