### ISSUE TITLE
[@types/got] Need Update

### ISSUE THREAD

**Issue by a632079** [DefinitelyTyped/DefinitelyTyped#23454]
- [x] I tried using the `@types/got` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @LinusU @BendingBender 

----------------------

`got` had a large break changes in `v8.x.x` API.
This Return: 
```
Promise<Response>
```
Instead of Return
```
Promise<Body>
```
I Hope you can update it soon.

**Comment by LinusU** [comment]
Are you sure about that? It isn't mentioned in the changelog 🤔 

https://github.com/sindresorhus/got/releases/tag/v8.0.0

**Comment by aoberoi** [comment]
also, on line 83:

```
    type GotUrl = string | http.RequestOptions | URL;
```

I think the `URL` is meant to be `Url`
