### ISSUE TITLE
@types/mongoose 5.0.1 installs incorrect @types/mongodb as dependency

### ISSUE THREAD

**Issue by lustoykov** [DefinitelyTyped/DefinitelyTyped#23518]
Package installs legacy `@types/mongodb` as dependency which results in

```
node_modules/@types/mongoose/index.d.ts(2392,29): error TS2694: Namespace '"...node_modules/@types/mongodb/index"' has no exported member 'ChangeStreamOptions'.


node_modules/@types/mongoose/index.d.ts(2392,77): error TS2694: Namespace '"...node_modules/@types/mongodb/index"' has no exported member 'ChangeStream'.
```

Installed `@types/mongodb` has in its package.json

```
    "name": "@types/mongodb",
    "version": "2.2.16",
```

while current one is 3.0.5. The package compiles just fine via `@types/mongodb, v3.0.5`

  - Authors: @simonxca @horiuchi @sindrenm @lukasz-zak @Alorel

**Comment by GongT** [comment]
+1

But no error when use watch mode ???? (-w)

**Comment by Alorel** [comment]
@andy-ms How can we specify a specific `@types` package version as a dependency? I tried creating a package.json, but the test script fails saying I can't specify `@types` packages there.

**Comment by andy-ms** [comment]
`@types/mongoose` depends on `"@types/mongodob": "*"`, which should be the latest version if you didn't specify anything else. It's possible to use path mapping to specify a dependency on a specific *older* version of a package, but for the latest the dependency will always be "*". This can sometimes cause problems (see #23257), but right now you'll just have to specify a higher mongodb version in your own package.json (or specify none at all and depend on the default being the latest).

**Comment by lustoykov** [comment]
> as a temporary workaround, try explicitly adding a @types/mongodb dependency in your project with the version set to >=3.0.0.

@Alorel, unfortunately that doesn't work since the global `@types/mongodb` is being detected and `@types/mongoose` installs its local version of `@types/mongodb` directly into its own `node_modules` folder.

**Comment by andy-ms** [comment]
@lustoykov `@types/mongodb` has a "*" dependency, so it should not be forcing you to use an older version. Maybe you have a lockfile that's keeping it at an old version?

**Comment by lustoykov** [comment]
@andy-ms - spot on, that was the problem!

Thanks everybody for the help, I'm closing the issue.

**Comment by serveryang** [comment]
@Anthony59273 
 try install `npm install --save-dev @types/mongoose@^4.7.8`

**Comment by CruiseMan** [comment]
@serveryang Downgrade `@types/mongoose` is not an option for me, is any other workaround ?.

**Comment by d-dmytro** [comment]
I **temporarily** solved the conflicting versions of the @types/mongodb between @types/mongoose and @types/connect-mongo, by uninstalling @types/connect-mongo: `npm uninstall -D @types/connect-mongo` and declaring the "connect-mongo" modules as "any" in the custom definitions file (e.g. src/custom.d.ts). IMO, this workaround is ok for now, as I use "connect-mongo" in one place only (when I setup the session store).

**Comment by fider** [comment]
Same with latest @types of mongoo**se** but it is enoug to add @types/mongo**db** manually
```sh
$ npm i -D @types/mongodb@3.1.17
```

**Comment by dylanh724** [comment]
2 years later, there are still similar issues -- for example, I can import most things fine:

![image](https://user-images.githubusercontent.com/8840024/110242297-687d6a80-7f90-11eb-8aa3-fdd8e53fa3b5.png)

However, things like CreateQuery? Nope, not found.

![image](https://user-images.githubusercontent.com/8840024/110242322-81861b80-7f90-11eb-802b-ee6287fd6eaf.png)

package:
![image](https://user-images.githubusercontent.com/8840024/110242281-53a0d700-7f90-11eb-8ab2-5deb6b31fa43.png)
