### ISSUE TITLE
`ReactDOM.render` has a wrong method signature

### ISSUE THREAD

**Issue by justjavac** [DefinitelyTyped/DefinitelyTyped#23527]
Hi @MartynasZilinskas @theruther4d

- [x] I tried using the `@types/react-dom` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

------------

`ReactDOM.render` has a wrong method signature, [react-dom/index.d.ts#L94-L99](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-dom/index.d.ts#L94-L99)

```ts
(
    parentComponent: Component<any> | Array<Component<any>>,
    element: SFCElement<any>,
    container: Element,
    callback?: () => void
): void;
```
This has been in d.ts file for a long time.

In the source code of react.js, the `render` function only accepts 3parameters: `element`, `container`, `callback`.

-----------------

I wrote a demo:

**Foo.tsx** (ComponentClass)

```ts
import * as React from "react";

export interface FooProps {
  name: string;
}

export class Foo extends React.Component<FooProps> {
  render() {
    return <div>Hello {this.props.name}!</div>;
  }
}
```

**Bar.tsx** (StatelessComponent)

```ts
import * as React from "react";

export interface BarProps {
  name: string;
}

export const Bar = (props: BarProps) => <div>Hello {props.name}</div>;
```

**index.tsx**

```ts
import * as React from "react";
import * as ReactDOM from "react-dom";

import { Foo } from "./Foo";
import { Bar } from "./Bar";

const hello = new Foo({
    name: "Foo",
});

const bar = React.createElement(Bar, { name: "Bar" });

ReactDOM.render(hello, bar, document.getElementById("root"));
```

**webpack.config.js**

```js
module.exports = {
  entry: "./src/index.tsx",
  output: {
    filename: "bundle.js",
    path: __dirname + "/dist"
  },

  devtool: "source-map",

  resolve: {
    extensions: [".ts", ".tsx", ".js", ".json"]
  },

  module: {
    rules: [
      { test: /\.tsx?$/, loader: "awesome-typescript-loader" },
      { enforce: "pre", test: /\.js$/, loader: "source-map-loader" }
    ]
  },

  externals: {
    "react": "React",
    "react-dom": "ReactDOM"
  }
};
```

When I run `webpack`, it can successfully compile, without any error.

output:

```
[at-loader] Using typescript@2.7.1 from typescript and "tsconfig.json" from ~/react_ts/tsconfig.json.
[at-loader] Checking started in a separate process...
[at-loader] Ok, 0.569 sec.

Hash: 1824d6946f211a66d0f0
Version: webpack 3.10.0
Time: 2016ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  4.51 kB       0  [emitted]  main
bundle.js.map  4.35 kB       0  [emitted]  main
   [1] ./src/index.tsx 388 bytes {0} [built]
   [3] ./src/Foo.tsx 1.02 kB {0} [built]
   [4] ./src/Bar.tsx 220 bytes {0} [built]
    + 2 hidden modules
Done in 2.82s.
```

But when I run the app, I got nothing but the error message

> Target container is not a DOM element.

**Comment by MartynasZilinskas** [comment]
I think it was accidentally left, because I couldn't find it in any documentation, event before 1 year ago.
/cc @vsiao
