### ISSUE TITLE
firefox-webext-browser wrong types for browser.runtime.Port

### ISSUE THREAD

**Issue by jpdigital** [DefinitelyTyped/DefinitelyTyped#23542]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/firefox-webext-browsesr` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bomjacob  

If you do not mention the authors the issue will be ignored.

The definitions for the `browser.runtime.port` type are not correct according to the [documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/Port) of these functions at developer.mozilla.org. For example:

- According to examples in the documentation the listener function added by `onMessage.addListener` should take one parameter, the message received. According to the type definition in the `@types/firefox-webext-browser` package the function does not take any parameters.
- The `postMessage` function should take one parameter, the message to post. But according to the type definitions it does take not parameters.

**Comment by bomjacob** [comment]
Yes, you would indeed be correct.
This bugs stems from the fact that the schema files at https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/schemas/runtime.json#35 are incorrect (or at least not detailed enough). I'll add an override in https://github.com/bomjacob/definitelytyped-firefox-webext-browser/blob/master/index.js when I find the time. (if you wanna submit a PR to https://github.com/bomjacob/definitelytyped-firefox-webext-browser with a fix, do feel free :D)
