### ISSUE TITLE
@types/react-navigation 'addListener' does not exist in type 'NavigationProp<any, NavigationStackAction>'.

### ISSUE THREAD

**Issue by xerotolerant** [DefinitelyTyped/DefinitelyTyped#23558]
Following the new instructions on the [react navigation site](https://reactnavigation.org/docs/redux-integration.html) for integrating redux with react-navigation I am encountering this error.
I'm not super experienced with typescript so I'm not sure how to expand the typings to add the prop.

```
error TS2345: Argument of type '{ dispatch: any; state: any; addListener: any; }' is not assignable to parameter of type 'NavigationProp<any, NavigationStackAction>'.
  Object literal may only specify known properties, and 'addListener' does not exist in type 'NavigationProp<any, NavigationStackAction>'.
```

@Huhuanming @mhcgrq @fangpenlin @abrahambotros @petejkim @iRoachie @charlesfamu @timwangdev @bang88 @svbutko

**Comment by timwangdev** [comment]
The definition is currently not compatible with react-navigation 1.0.0.

PRs are welcome.
