### ISSUE TITLE
Hapi 17 - Problems and regressions.

### ISSUE THREAD

**Issue by SimonSchick** [DefinitelyTyped/DefinitelyTyped#23562]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/hapi` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jhsimms @rafaelsouzaf 

If you do not mention the authors the issue will be ignored.

I noticed multiple issues when trying to apply these typings today:

- `ServerRoute` should _not_ have `config` anymore, it was renamed to `options`.
- `.ext` methods are no longer overloaded and require manual typings in callback. eg. `server.ext('onPreResponse', (req, reply) => {})`, this worked before and is a regression.
- `plugins` on `ServerRouteOptions` shoud _not_ be a Dictonary, it should just be `PluginSpecificConfiguration`, otherwise all keys would need to be the same value, this is a regression.
~~- `app`, `plugins`, `route`, `state`, `auth` are missing from `Request` see https://github.com/hapijs/hapi/blob/master/lib/request.js#L41, this is a regression.~~ this might be an issue with local typings, hold on.

**Comment by SimonSchick** [comment]
Furthermore, I tried narrowing things myself, you _will_ have to change the `Lifecycle.Method` interface to `    export type Method = (request: Request, h: ResponseToolkit, err?: Error) => ReturnValue;
`

**Comment by SimonSchick** [comment]
Also it seems you can no longer enhance typings by simple doing something like this:

```typescript
import 'hapi';
declare module 'hapi' {

  export interface Request {
     ...
  }
}```
you now need to specify `hapi/definitions/request/request` which is kind of a pita.

**Comment by SimonSchick** [comment]
Also ```decorate(type: 'handler' | 'request' | 'server' | 'toolkit', property: string, method: Function, options?: {apply: boolean;  extend: boolean} ): void;``` doesn't narrow correctly, overloads should be used here.

**Comment by SimonSchick** [comment]
Also it seems there is a general lack of overloading, `server.events.on` also doesn't narrow, the documentation does however.

**Comment by SimonSchick** [comment]
Also `RequestInfo { id: string; }` is missing too.

**Comment by jhsimms** [comment]
Good catches, Simon.

I noticed the "hapi/definitions/request/request" thing after it was merged, as well, and I agree, it's very annoying.  Do you think we should collapse the definitions into a single file?

**Comment by SimonSchick** [comment]
@jhsimms I was going to suggest but held off because it's going to be one huge mess.
I'm a little torn between preserving previous behaviour/compatibility and keeping the code base tidy.

I'm generally in favour of collapsing it tho.

**Comment by SimonSchick** [comment]
Also `ext` on `RouteOptions` should be narrowed 🙂

**Comment by SimonSchick** [comment]
Another issue, we aggregate and mass register endpoints/middlewares, this doesn't seem to play well with the current definition of `register`.

Adding this to the end of the definitions resolves the issue:
```
    register(plugins: ServerRegisterPluginObject<any>[], options?: ServerRegisterOptions): Promise<void>;
```

**Comment by SimonSchick** [comment]
Also `ServerRegisterOptions.routes.vhost` should be optional.

**Comment by jhsimms** [comment]
I will have the time to work on this toward the end of this week.

**Comment by saboya** [comment]
Also, some parts may be too cumbersome to work with. Take `AuthCredentials` for example. You now have to merge your own definition if you want to pass your own properties, as in:

```typescript
declare module "hapi/definitions/request/request-auth" {
	interface AuthCredentials {
		id: string;
		name: string;
	}
}
```

And since the definition is basically empty:

```typescript
/**
 * User-extensible type for request.auth credentials.
 */
export interface AuthCredentials {
    user?: string;
}
```

I don't see why this couldn't just be `object` instead.

**Comment by SimonSchick** [comment]
I don't actually know why it has `user?: string` in there cc @jhsimms.
The reason it's not _just_ object is to preserve type safety, you probably know what your credentials object contains, so you might as well define them yourself.

**Comment by SimonSchick** [comment]
All of these were resolved.

**Comment by mmiszy** [comment]
How do you extend `AuthCredentials` from my codebase now? @saboya

**Comment by saboya** [comment]
@mmiszy There's an example of `AuthCredentials` being overriden in hapi-auth-basic tests.

**Comment by mmiszy** [comment]
Oh wow, thank you! Not sure how I missed that, my bad.
