### ISSUE TITLE
@types/react-native-navigation missing appStyle

### ISSUE THREAD

**Issue by danilobuerger** [DefinitelyTyped/DefinitelyTyped#23564]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @egorshulga 

If you do not mention the authors the issue will be ignored.

The rnn types are missing lots of `appStyle` props for `startSingleScreenApp` and `startTabBasedApp`. See https://github.com/wix/react-native-navigation/blob/8c21b85bb40d78ac512c5922f29604509156585a/src/deprecated/platformSpecificDeprecated.android.js#L141 for example.

**Comment by egorshulga** [comment]
Could you make an exhaustive list of `appStyle` props missed and make a PR? 
Current types definitions are based on [docs](https://wix.github.io/react-native-navigation/#/top-level-api?id=starttabbasedappparams).

**Comment by danilobuerger** [comment]
@egorshulga See https://wix.github.io/react-native-navigation/#/styling-the-navigator?id=style-object-format

**Comment by egorshulga** [comment]
@danilobuerger, this link describes the `NavigatorStyle` object format. 
This object is passed to the `startTabBasedApp()` as `{ tabs: { navigatorStyle: { ... } } }` and to the `startSingleScreenApp()` as `{ screen: { navigatorStyle: { ... } } }`.

**Comment by danilobuerger** [comment]
@egorshulga https://github.com/wix/react-native-navigation/blob/8c21b85bb40d78ac512c5922f29604509156585a/src/deprecated/platformSpecificDeprecated.android.js#L319 says different:
```
params.appStyle = convertStyleParams(params.appStyle);
```

**Comment by egorshulga** [comment]
I tend to follow the docs, not the implementation, cause it's hard to predict the effects of using undocumented features.

**Comment by danilobuerger** [comment]
@egorshulga I would generally agree with you, but if a library is not documented well, we have to resort to looking at the code. It's not like `appStyle` is a hidden feature. Just see https://github.com/wix/react-native-navigation/issues?utf8=%E2%9C%93&q=is%3Aissue+appstyle Its also partially documented for `startTabBasedApp`.

The main maintainer has also pointed out that prop on several occasions there.

**Comment by egorshulga** [comment]
So you suggest following changes, am I correct?
```
    appStyle?: {
        orientation?: 'auto' | 'landscape' | 'portrait';
        bottomTabBadgeTextColor?: string;
        bottomTabBadgeBackgroundColor?: string;
        backButtonImage?: any;
        hideBackButtonTitle?: boolean;
-   };
+   } | NavigatorStyle;

```

**Comment by danilobuerger** [comment]
And adding `appStyle` as `NavigatorStyle` to `startSingleScreenApp`. I am unsure though if everything from `NavigatorStyle` works in `appStyle` as well. This would require a deep dive into the lib.
