### ISSUE TITLE
Typings for using _.get on nested object.

### ISSUE THREAD

**Issue by syamksundar** [DefinitelyTyped/DefinitelyTyped#23588]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/223f02239792281fa7f6b39ba1ed8c420dbc945f/types/lodash/object/get.d.ts#L98

I have an object:
```
let routeData: IRoute = {
  data: {
    previousName: 'xyz'
  }
}
```
My code has,
```
  _.get<IRoute, string>(routeData, 'data.previousName')
```
Which used to work fine until new version which forces me to change typing from string to key of IRoute object.

My use case is I want get on nested object. How do I use the typing?

**Comment by aluanhaddad** [comment]
The following works perfectly
```ts
_.get(routeData, 'data.previousName'); // any
```
Explicitly specifying the _type_ arguments when calling a generic functions is usually a mistake. It is desirable for the types to follow directly from the _value_ arguments and their relationships.

However, to actually write this in a manner that yields a well typed result, you can write
```ts
_.get(routeData, 'data', 'previousName'); // IRoute['data']['previousName'];
```

**Comment by Delagen** [comment]
@aluanhaddad As I know 
```
_.get(routeData, 'data', 'previousName'); // IRoute['data']['previousName'];
```
works as
```
const result=routeData && routeData['data'];
result===undefined?'previousName':result
```

**Comment by a7madgamal** [comment]
any way to let typescript understand the key `xxx.yyy.zzz.....` as the correct type of input[xxx][yyy][zzz].... ?

**Comment by deser** [comment]
Also, I've noticed that when you get via chaining types are propagated correctly. 
_.chain(routeData).get('data').get('previousName').value(); // correct type would be assigned
