### ISSUE TITLE
TypeScript types for @types/chrome 

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#23597]
@andy-ms  @niikoo @pyle 

I am using the following code:

```js
chrome.devtools.inspectedWindow.eval('<your code>', {
    useContentScriptContext: true
}, function(result) {
    // result of the execution
});
```

however this gives me these errors:

<img width="379" alt="screenshot 2018-02-13 00 26 20" src="https://user-images.githubusercontent.com/11139560/36140012-96ee8772-1054-11e8-8dd9-a573b51fe0ba.png">

<img width="1069" alt="screenshot 2018-02-13 00 26 34" src="https://user-images.githubusercontent.com/11139560/36140008-91a0dd42-1054-11e8-8237-025840dc785f.png">

I think the code I have is correct, so I think the typings might be incorrect. What do I do? 

To be clear, I have 3 args, including a callback, and the typings don't like that. If I remove the 3rd arg, then it complains that `useContentScriptContext` is not a recognized prop.

**Comment by pyle** [comment]
Hey,

So haven't looked at the chrome typing before (only the chrome-app), but looking at the typing, there is only 2 arguments:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chrome/index.d.ts#L1680

But you are right, the chrome api:
https://developer.chrome.com/extensions/devtools_inspectedWindow#method-eval
has 3 args listed.

So we have a couple of options here, you can write a Pull Request to fix this up.

Or, one of the definition owners can take a look: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chrome/index.d.ts#L3

For the meantime you should be able to cast any on eval so you can use the method. afaik there isn't an ignore comment for things like this.

**Comment by ORESoftware** [comment]
@matthewkimber can you take a look at this one?

**Comment by couven92** [comment]
@ORESoftware https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23619

**Comment by ORESoftware** [comment]
@couven92 cool thx
