### ISSUE TITLE
Tls changes break type definitions

### ISSUE THREAD

**Issue by charsleysa** [DefinitelyTyped/DefinitelyTyped#23596]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @hoo29

If you do not mention the authors the issue will be ignored.

#23393 seems to have broken a lot of type definitions, especially for packages that contain their own type definition files.

More specifically, the rename from `TlsOptions` to `TlsServerOptions`.

Is this a necessary change that will be supported going forward?

**Comment by hoo29** [comment]
I renamed TlsOptions to TlsServerOptions to make it more descriptive. @andy-ms / @DanielRosenwasser - is it better to rename these things and ask people to change their local definitions and code, or to leave it as is? Or, is there a process for making breaking type definitions that I completely ignored?

If the answer is leave them as is - I have created a pull request to undo the renaming.

**Comment by andy-ms** [comment]
> I renamed TlsOptions to TlsServerOptions to make it more descriptive.

I don't think that's worth having a change -- there are probably a lot of people creating `const options: TlsOptions = ...` who would be broken.

**Comment by andy-ms** [comment]
Ah, it was already done in #23615. Thanks!
