### ISSUE TITLE
Request: typings for Rollup configuration file

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#23604]
https://rollupjs.org/guide/en#configuration-files

**Comment by aluanhaddad** [comment]
Rollup is now shipping its own declarations. https://rollupjs.org/guide/en#typescript-declarations

**Comment by OliverJAsh** [comment]
Does that include the configuration file?

**Comment by aluanhaddad** [comment]
Yes, the entry point [here](https://github.com/rollup/rollup/blob/ea6fe6a3562521262ace9ede0a09d0e9c1fa5d68/src/rollup/index.ts#L218) uses the interface declared [here](https://github.com/rollup/rollup/blob/master/src/rollup/index.ts#L58).

Be advised that there are some unspecified declaration dependencies which makes it a bit awkward. See [this comment](https://github.com/rollup/rollup/issues/1862#issuecomment-357214494) for what to install.

**Comment by OliverJAsh** [comment]
I tried to use it but got errors because `output` does not exist on the type `InputOptions`.

For configuration, I guess we need a new type which includes both input and output options?

``` ts
// rollup.config.js
// @ts-check

import { InputOptions } from 'rollup';
import resolve from 'rollup-plugin-node-resolve';
import legacy from 'rollup-plugin-legacy';

/** @type {InputOptions} */
const config = {
    input: 'target-tsc/index.js',
    /* Error: Type '{ input: string; output: { [x: string]: any; file: string; format: string; sourcemap: boolean; };...' is not assignable to type 'InputOptions'.
  Object literal may only specify known properties, and 'output' does not exist in type 'InputOptions' */
    output: {
        file: 'target-rollup/index.js',
        format: 'es',
        sourcemap: true,
    },
    plugins: [
        resolve(),
        legacy({
            // `parse-sizes` does not export anything. We use this plugin to add a named export.
            'node_modules/parse-sizes/parse-sizes.js': {
                parseSizes: 'parseSizes',
            },
        }),
    ],
};

export default config;
```

**Comment by aluanhaddad** [comment]
Your definitely right. Looks like it should have an `output` property declared to be of type [`OutputOptions`](https://github.com/rollup/rollup/blob/master/src/rollup/index.ts#L93).

**Comment by xt0rted** [comment]
I think this issue can be closed now. I'm not seeing this error with the latest version (0.65.2).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
