### ISSUE TITLE
Compilation errors in jszip typings

### ISSUE THREAD

**Issue by jeff-burgess** [DefinitelyTyped/DefinitelyTyped#23610]
I'm seeing what appear to be syntax errors when building with Typescript 2.2.2:

`ERROR in /Users/jeffburgess/Projects/iv-apps-spaceplanner/node_modules/@types/jszip/index.d.ts
(109,58): error TS1005: ',' expected.`

`ERROR in /Users/jeffburgess/Projects/iv-apps-spaceplanner/node_modules/@types/jszip/index.d.ts
(213,57): error TS2314: Generic type 'JSZipGeneratorOptions<T, OutputType>' requires 2 type argument(s).`

`ERROR in /Users/jeffburgess/Projects/iv-apps-spaceplanner/node_modules/@types/jszip/index.d.ts
(222,34): error TS2314: Generic type 'JSZipGeneratorOptions<T, OutputType>' requires 2 type argument(s).`

If I remove " = OutputType" from the following line...
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/242fcd3080c74d4b1015f7a94c6a63a9928052f0/types/jszip/index.d.ts#L109
...my app compiles as I would expect.

After reading the [docs for generics](https://www.typescriptlang.org/docs/handbook/generics.html), I couldn't determine the purpose of the " = OutputType" expression in line 109.

**Comment by jeff-burgess** [comment]
Ha! I didn't check, I just assumed they weren't there.  :)  Closing.

**Comment by uipoet** [comment]
@jeff-burgess Apologies, I got a false positive after removing `@types/jszip` in VSCode. I guess the server cached the types. After restarting, the types are not there. This time I actually looked at the source code of `jszip` and there is no TypeScript to be found. We do indeed need `@types/jszip` and it is also broken for me when compiling. :(
