### ISSUE TITLE
React types don't account for new esModuleInterlop flag in typescript v2.7

### ISSUE THREAD

**Issue by IljaDaderko** [DefinitelyTyped/DefinitelyTyped#23640]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas  @onigoetz @richseviora @theruther4d 

---

Typescript 2.7 introduced `"esModuleInterop": true` which essentially enables us to use imports like `import React from "react"` as opposed to `import * as React from "react"` I added these lines to my tsconfig.json

```
    "moduleResolution": "node",
    "module": "es6",
    "esModuleInterop": true,
```

When I run my application everything seems to work correctly with tsc compiler in comand line, however in vscode I get tons of [ts] errors like this: `node_modules/@types/react/index"' has no default export.`

**Comment by DovydasNavickas** [comment]
First of all, which version of types are you using?
Secondly, not sure it's types issue, but let's see.

**Comment by DovydasNavickas** [comment]
There's not only `esModuleInterop` compiler option, but `allowSyntheticDefaultImports` too. And this is the one you need 👍

**Comment by tkrotoff** [comment]
@DovydasNavickas 
> And this [`allowSyntheticDefaultImports`] is the one you need

btw I think there is something wrong in [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/compiler-options.html):
> --esModuleInterop [...] and enable --allowSyntheticDefaultImports for typesystem compatibility

For me this means that with `esModuleInterop`, `allowSyntheticDefaultImports` should be true

**Comment by IljaDaderko** [comment]
Yeh, I thought `allowSyntheticDefaultImports` gets enabled out of the box with that esModule flag, will give it a shot and specify it manually tomorrow and will let you know how it goes 👍

**Comment by IljaDaderko** [comment]
adding `allowSyntheticDefaultImports` resolves the issue.
