### ISSUE TITLE
datatables.net-select incomplete

### ISSUE THREAD

**Issue by eman1986** [DefinitelyTyped/DefinitelyTyped#23650]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/datatables.net-select` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] @andy-ms 

the definition for the datatables.net-select package is incomplete, namely the events are not included and as such I'm getting build errors.

**Comment by andy-ms** [comment]
Pull requests accepted. (Also, package author is @szechyjs , not me)

**Comment by eman1986** [comment]
oh sorry about that
