### ISSUE TITLE
Add gtag to google.analytics types

### ISSUE THREAD

**Issue by markgoho-EDT** [DefinitelyTyped/DefinitelyTyped#23718]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @FreshRob @andy-ms @Tyler-Murphy @Calvin-Huang @patkujawa-wf 

It's only been a few weeks, but it looks like Google is now using a different script and syntax for Google Analytics. Here's the migration guide: 

https://developers.google.com/analytics/devguides/collection/gtagjs/migration

**Comment by patkujawa-wf** [comment]
Wow, that's a big change in the API. I don't work with typescript any more, nor google analytics, so I can't take this on.

**Comment by Tyler-Murphy** [comment]
I think gtag deserves its own types, separate from the existing google.analytics types. [Gtag's documentation](https://developers.google.com/gtagjs/) says it's for many different Google platforms:

> The global site tag (gtag.js) is a JavaScript tagging framework and API that allows you to send event data to AdWords, DoubleClick, and Google Analytics. Instead of having to manage multiple tags for different products, you can use gtag.js and more easily benefit from the latest tracking features and integrations as they become available.
> 
> gtag.js makes it easy to send data to multiple Google products by adding code to your website. There's no need to create additional accounts or manage configuration in a separate interface.

There may be overlap with Google Tag Manager types, since they both use `window.dataLayer`, and the transition from gtag to GTM is meant to be easy if you decide to use GTM after setting up gtag.

Here's the [gtag reference](https://developers.google.com/gtagjs/reference/api), which is probably a good starting point for adding types.

**Comment by odahcam** [comment]
Maybe a `@types/gtag` should be created. 🤔

**Comment by odahcam** [comment]
Not from me.

**Comment by dandrei** [comment]
Would love to see this.

**Comment by Rokt33r** [comment]
I'll do. Should be finished in one or two days.

**Comment by wminshew** [comment]
when can we expect this to be available on npm?

**Comment by rbuckton** [comment]
According to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34020#issuecomment-478202760, it has already been published. 

I checked and `npm info @types/gtag.js` reports it as existing.

**Comment by wminshew** [comment]
My bad -- I thought I had searched npm and definitelytyped I don't know how I missed it.... embarrassing. Thank you!

**Comment by tbunique** [comment]
Not sure if I should open a new issue for this but this doesn't seem compatible with App + Web Analytics.

Example here : https://developers.google.com/analytics/devguides/collection/app-web/user-properties

'set' doesn't like having a string as its next argument.

**Comment by Rokt33r** [comment]
@tbunique Please open a new issue and ping me. I'll look around it later.

**Comment by NevenLiang** [comment]
@rbuckton How to use it? Should `gtag` not be exported in the type definition file? https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gtag.js

**Comment by NevenLiang** [comment]
@Rokt33r Should `gtag` not be exported in the type definition file? If not, how to use it?

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gtag.js

**Comment by JLarky** [comment]
Just install https://www.npmjs.com/package/@types/google.analytics package and install the snippet

**Comment by ozmoroz** [comment]
> @Rokt33r Should `gtag` not be exported in the type definition file? If not, how to use it?
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gtag.js

`gtag` variable is exported globally when you add `@types/gtag` to you `package.json`.
You can use its type by doing this in your code:
```ts
const gtag: typeof gtag
```

**Comment by ts-web** [comment]
The package is `@types/gtag.js` and once installed, `window.gtag` has the proper type :+1:

**Comment by Stopa** [comment]
I'm running into a weird issue where the package `@types/gtag.js` is installed, is present in `package.json` and `yarn.lock` , but the application won't build - webpack says 
```ERROR in ./src/index.tsx
Module not found: Error: Can't resolve '@types/gtag.js' in '/Users/stepan/work/portal/src'
 @ ./src/index.tsx 11:0-24```
 
 My first thought was that it might be a naming issue - do you think there could be any problems with external dependencies with names ending with a valid extension?

**Comment by ts-web** [comment]
@stopa it sounds like you're importing the `@types` package from your code, is that right? In that case remove that import and rely on [the types and typeRoots configs](https://www.typescriptlang.org/tsconfig#types)

**Comment by Stopa** [comment]
@ts-web 

You're right, I was trying to import it manually - this way VSCode at least was not giving any TS errors. I removed the manual import, my `tsconfig.js` doesn't override any `types` or `typeRoots` config, but typescript compiler now can't seem to find types for `gtag`: 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/408256/102467917-915d2600-4059-11eb-9f67-b3a0567a60fa.png">

Other `@types` packages resolve correctly, `@types/gtag.js` is included in `package.json` and `yarn.lock` and is present under `node_modules`.

**Comment by remjx** [comment]
my issue was that in my `tsconfig.json` I was explicitly specifying `types`. Once I removed the `types` key the default behavior of picking up @types from package.json kicked back in and voila.

**Comment by binarybaba** [comment]
Just here for people who stumbled upon this:
Adding `/// <reference types="@types/gtag.js" />` to the top of the file also resolved my stuff :)

**Comment by jbojcic1** [comment]
> Just here for people who stumbled upon this: Adding `/// <reference types="@types/gtag.js" />` to the top of the file also resolved my stuff :)

this is the only thing that works for me too. Not sure why. my tconfig looks fine. when I run `tsc --showConfig -p tsconfig.json` I am getting:
```
{
    "compilerOptions": {
        "preserveSymlinks": true,
        "rootDir": "../../..",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node10",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "importHelpers": true,
        "target": "es6",
        "module": "esnext",
        "lib": [
            "es2017",
            "dom"
        ],
        "skipLibCheck": true,
        "skipDefaultLibCheck": true,
        "strict": true,
        "allowJs": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "forceConsistentCasingInFileNames": true,
        "baseUrl": "../../..",
        "resolveJsonModule": true,
        "paths": {
           ...    
        },
        "jsx": "react-jsx",
        "noImplicitOverride": true,
        "noPropertyAccessFromIndexSignature": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "outDir": "../../../dist/out-tsc",
        "typeRoots": [
            "/Users/jbojcic/workspace/my-repo/node_modules/@types"
        ]
    },
    "files": [
        "./src/index.ts",
        "./src/hooks/useAnalyticsPageView.ts",
        "./src/components/GoogleAnalyticsScripts.tsx"
    ],
    "include": [
        "**/*.js",
        "**/*.jsx",
        "**/*.ts",
        "**/*.tsx"
    ],
    "exclude": [
        "**/*.spec.ts",
        "**/*.test.ts",
        "**/*.spec.tsx",
        "**/*.test.tsx",
        "**/*.spec.js",
        "**/*.test.js",
        "**/*.spec.jsx",
        "**/*.test.jsx"
    ]
}
```
