### ISSUE TITLE
[winston] Update winston definition to 3.0.x

### ISSUE THREAD

**Issue by tomwanzek** [DefinitelyTyped/DefinitelyTyped#23743]
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bonnici @codeanimal @DABH

It would be great, if definitions for `winston` 3.0.x could be provided.

**Comment by DABH** [comment]
Duplicate of #20418 , we're working on it :)

**Comment by tomwanzek** [comment]
@DABH Thanks for the cross-reference. Hopefully, you get the question of whether the definitions will go directly into the `winston` package resolved quickly. 👍
