### ISSUE TITLE
ramda: no types found when using functions from es import

### ISSUE THREAD

**Issue by mribichich** [DefinitelyTyped/DefinitelyTyped#23765]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @donnut @mdekrey @mrdziuban @sbking @afharo @teves-castro @1M0reBug @hojberg @charlespwd @samsonkeung @angeloocana @raynerd @googol @moshensky @ethanresnick

If you do not mention the authors the issue will be ignored.

How could we solve this?

I would love to be able to `import sortBy from 'ramda/es/sortBy';` and have definitions

Maybe we could copy de index.d.ts file to an `es` folder, remove the `declare namespace R` line and then from the main index.d.ts import the `es/index` and re export all the functions from the `R namespace`. That way we have only one definition for function

thanks

**Comment by mribichich** [comment]
Actually we should create a file for each function definition in the `es folder` and then import each in the main index and re export them in the `R static namespace`

**Comment by mribichich** [comment]
great thanks! I'll take a look at it

**Comment by battmanz** [comment]
I just tried `types/npm-ramda`. It looks like they support importing from the `src` folder using commonjs:

    import sortBy = require('ramda/src/sortBy');

But they do NOT support importing from the `es` folder using ES6 modules. What would it take to implement the idea from @mribichich to create a file for each function in the `es` folder?

**Comment by tycho01** [comment]
@battmanz would you mind filing this as an issue over there? I'm on phone now but think es modules may have been discussed there before.

**Comment by rafaelcichocki** [comment]
I submitted this as an issue here: https://github.com/types/npm-ramda/issues/395 
And it already got fixed and merged, and is available at [types/npm-ramda#dist](https://github.com/types/npm-ramda/commit/068584583f1c940b28a1ec4d64eec770d7858fb8)

**Comment by benjamingeorge** [comment]
I still get typescript errors for es import `import filter from "ramda/src/filter";`  Maybe i'm misunderstanding @rafaelcichocki last post, but has this not been fixed yet? 
i'm using ramda & @types/ramda v0.26.1

**Comment by googol** [comment]
@benjamingeorge you need to import from `ramda/es/filter` instead of `ramda/src/filter` to get the es imports. Only the es imports are typed currently, not the commonjs imports from `ramda/src`

**Comment by benjamingeorge** [comment]
great thank you.

**Comment by googol** [comment]
Actually, this https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33334 was just merged, so the `ramda/src` imports should also work with the latest typings

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
