### ISSUE TITLE
analytics-node types not working

### ISSUE THREAD

**Issue by davidanaya** [DefinitelyTyped/DefinitelyTyped#23760]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/analytics-node` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
  - Authors: @fongandrew, @thomasthiebaud

When trying to use the types with analytics-node library we get an error.
Upon removing the types, everything works as expected.

More details in this thread
https://github.com/segmentio/analytics-node/issues/132

Thanks

**Comment by fongandrew** [comment]
What's your TypeScript version and what does your tsconfig look like?

Specifically, you might want to try fiddling with the `allowSyntheticDefaultImports` and/or `esModuleInterop` flags.

**Comment by davidanaya** [comment]
Typescript version is 2.4.2

tsconfig.json
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "angularCompilerOptions": {
    "genDir": "./ngc"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

I import the library like this
`import * as Analytics from "analytics-node";`

and everything works fine. If I install the  @types I get
`
[ts] Module '"/Users/myuser/myproject/node_modules/@types/analytics-node/index"' resolves to a non-module entity and cannot be imported using this construct.`

**Comment by fongandrew** [comment]
Ah, it looks like you're using this in browser? The `analytics-node` package is intended for server-side Node.js use (hence why it works as expected with `require` but is a little odd with ES module imports).

The recommended use for Segment is to  use the web snippet (https://segment.com/docs/sources/website/analytics.js/quickstart/). You can use https://ww.npmjs.com/package/@types/segment-analytics to type check it. I'm personally not a huge fan of the global `analytics` var it creates, but keep in mind that there's certain functionality in the client side library (e.g. identifying a user with a cookie) that's completely absent in the Node library.

If you do want to stick with `analytics-node`, you should update to TypeScript 2.7 and turn on the `esModuleInterop` flag in your tsconfig. Then import the library's default export like this: `import Analytics from 'analytics-node'`. See the `esModuleInterop` section of https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html for why this is necessary.

**Comment by ajsharp** [comment]
I'm having the same problems as @davidanaya, not using in the browser but I do have `dom` in `compilerOptions.lib` in `tsconfig.json`.

Also trying to do any sort of import -- default, named -- and nothing is working.

**Comment by ajsharp** [comment]
@fongandrew I'd like to be using ES6 imports, but can only get commonJS require to work currently. 

`esModuleInterop` seems to cause errors with other modules imported like this: `import * as module from 'module'`

**Comment by ajsharp** [comment]
By deleting the default export and changing the namespace to a module, I can do es6 imports. Obviously this would break the module because it eliminates the default export. There's a way to support both styles -- @types/express does and and many others support it -- I just don't know how to do it.

**Comment by fongandrew** [comment]
About the errors with `esModuleInterop` on `import * as module from 'module'`, are the modules CommonJS modules with a single `export = `? If so, TypeScript might be unhappy about that. The fix is to `import module from 'module'` instead.

The reason TypeScript enforces the above is that `import * as module from 'module'` is invalid ES6 when the export is, say, a single function or class. From https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html:

> ECMAScript spec stipulates that a namespace record is a plain object, and that a namespace import (foo in the example above) is not callable

**Comment by fongandrew** [comment]
Those examples would compile with your suggested changes, but are they actually valid at runtime?Based on the README for https://www.npmjs.com/package/analytics-node, it looks like the export is a single class, not an object with a class property. So the ES6 we're looking for is probably this?

```js
import Analytics from 'analytics-node'; // new Analytics("API_KEY")
```

**Comment by havenchyk** [comment]
@ajsharp I'm on the opposite side. Only `import = require` works for me.

@fongandrew I see that `esModuleInterop` solves the problem, but without using it, where should the fix be addressed? I mean should `analytics-node` be changed to use default export instead or maybe it can be solved somehow on side of type definitions in this repo? Or should we wait for ES import/export to become a standard in node.js? Could you please clarify?

**Comment by sabrehagen** [comment]
Can you follow up on this please @fongandrew? Using `@types/analytics-node@0.0.32` as follows

```
import Analytics from 'analytics-node';
```

produces

```
Module '"node_modules/@types/analytics-node/index"' has no default export.
```

**Comment by fongandrew** [comment]
@sabrehagen, does `esModuleInterop` fix the problem?

**Comment by fongandrew** [comment]
@havenchyk, absent `esModuleInterop`, the only way to use that syntax is for `analytics-node` to move to a default ES module export. Here's the thing though -- unless Node itself forces a migration to ES modules, the CommonJS single export remains perfectly valid. There technically isn't anything to fix. `esModuleInterop` isn't a hacky workaround. It's actually how, AFAICT, the TS devs want us to type these scenarios.

At any rate, it doesn't make sense IMHO to update the type def to use an ES-style export until the module itself does. Your code might compile, but you'll still run into runtime errors.

**Comment by andreasdj** [comment]
Is there a reason for only exporting the Analytics class and not the interfaces themselves? It's difficult to use the error callback with typed parameters as the interfaces aren't exported.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
