### ISSUE TITLE
lodash: Add ReadonlyArray back and update to TS 2.5

### ISSUE THREAD

**Issue by aj-r** [DefinitelyTyped/DefinitelyTyped#23766]
In #23710 , we removed `ReadonlyArray` types because they don't work well in typescript pre-2.5 (apparently they result in an infinite loop). 

Now that lodash is fixed for the 2.2-2.4 people, I think we should add `ReadonlyArray` support back, and bump the typescript version up to 2.5.

It's a trade-off (support `ReadonlyArray` vs. support old versions of typescript), but I think supporting `ReadonlyArray` is the better option here, because people with old versions of typescript have a workaround: `npm install @types/lodash@ts2.4`. People who use `ReadonlyArray` currently have no good workaround - they'll need to add type assertions to their readonly arrays to make lodash accept them.

Thoughts @mhegazy ?

**Comment by aj-r** [comment]
I tried resolving the memory issues in TS 2.2-2.4, but then the tests actually fail. Looks like there were bugs with `ReadonlyArray` in 2.2-2.4 that are show-stoppers as far as lodash is concerned. So the only way is upgrading to TS 2.5. However that's not nice either, since it requires a few other libraries to also update to TS 2.5 (since they depend on us).

**Comment by quentez** [comment]
On our side we use a fork for this reason.

**Comment by aj-r** [comment]
Actually we can probably implement this for real now, since lodash was just upgraded to TS 2.6
