### ISSUE TITLE
[@types/auth0] User - ambiguity between sub and user_id

### ISSUE THREAD

**Issue by theigor** [DefinitelyTyped/DefinitelyTyped#23785]
- [x] [Mention]
  - Authors: @donaldpipowitch , @amiram , @westy92 @paulvanbrenk , @akvamalin 

There seems to be some ambiguity between `user_id` and `sub` properties of the `User` type. The signature I am getting back has a `sub` property and not a `user_id` property at all and there seems to be discussion that this is a bug within Auth0 - https://github.com/auth0/passport-auth0/issues/48. Here's an example of what I get back when using Auth0:

```ts
{ 
  nickname: 'theigor',
  name: '...',
  picture: '...',
  updated_at: '2018-02-20T14:44:00.335Z',
  email: '...',
  email_verified: false,
  iss: '...',
  sub: 'auth0|...',
  aud: '...',
  iat: 1519137840,
  exp: 1519173840,
  at_hash: '...',
  nonce: '...'
}
```

On the client side, the types for auth0-js provides for both a user_id and a sub property in `Auth0UserProfile`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/070eb128b86954afae4f896dc0923c85c15c586a/types/auth0-js/index.d.ts#L600 

But on server side, the `User` type has only `user_id`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/070eb128b86954afae4f896dc0923c85c15c586a/types/auth0/index.d.ts#L319

I can submit a PR if all we need to do is add a `sub?: string` property - I'm just not sure if that's what we want to do. Ideally, the auth0-js and auth0 should have the same types, no? Maybe someone from auth0 can weigh in - I feel like one of these packages should reexport most of the types from the other.

Thanks,

Igor

**Comment by theigor** [comment]
Also, what I end up having to do to actually get the auth id on the client side is:
```ts
const auth_id = p.user_id ? p.user_id : p.sub;
```
where p is an instance of `auth0-js/Auth0UserProfile`

**Comment by dandrei** [comment]
I have the same issue as @theigor in v2.9.7 of `@types/auth0`. The property `sub` is missing from the TS definition, but is present in the objects thsemselves.

cc: @westy92

**Comment by westy92** [comment]
Please open a PR to fix it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
