### ISSUE TITLE
React types assume a global HTMLDialogElement

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DefinitelyTyped/DefinitelyTyped#23798]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @theruther4d @richseviora @onigoetz @DovydasNavickas (last 4 in the header)

Related to #18484.

I think both of these packages should remove the `"dom"` entry from their `tsconfig.json` `"lib"`. That's the only reliable way to verify not adding these dependencies.

**Comment by gnbond** [comment]
Saw this after an npm update which upgraded to types/react@16.0.38

"npm start" began complaining, and application would not run but went direct to the error page from the dev server

```
M:\ctm-ts-app\node_modules\@types\react\index.d.ts
(3508,58): error TS2304: Cannot find name 'HTMLDialogElement'.
```

Monkey-see, monkey-do adding a line to global.d.ts fixed it for me:
 ```
 --- global.d.ts.orig    2018-02-22 12:43:31.759188000 +1100
+++ global.d.ts 2018-02-22 12:25:37.960159000 +1100
@@ -34,6 +34,7 @@
 interface HTMLButtonElement extends HTMLElement { }
 interface HTMLCanvasElement extends HTMLElement { }
 interface HTMLDivElement extends HTMLElement { }
+interface HTMLDialogElement extends HTMLElement { }
 interface HTMLDListElement extends HTMLElement { }
 interface HTMLEmbedElement extends HTMLElement { }
 interface HTMLFieldSetElement extends HTMLElement { }

```

But I am a TS neophyte and not really familiar with npm and stuff, so don't take my word for it.
