### ISSUE TITLE
[@types/react-table] FilterRender onFilterChange error: 'Expected 0 arguments, but got 1'

### ISSUE THREAD

**Issue by SuperRunt** [DefinitelyTyped/DefinitelyTyped#23836]
- [x] I tried using the `@types/react-table` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] Mention the authors so they can respond:  @royxue @psakalo @Havret 

**Code example that produces the error:**
```
let renderer: FilterRender = ({filter, onFilterChange}) => (
            <Dropdown placeHolder="All" onChanged={ (item) => onFilterChange(item.key) } options={ intervals.map((c) => { return { key:c.key, text: c.text } }) } />
        )
```

**Error:** 
`onFilterChange` gets following error: `TS2554: Expected 0 arguments, but got 1.` 

**Possible solution:**
I'm wondering if this could be fixed by changing ReactTableFunction def to something like:
`export type ReactTableFunction = (predicate?:any) => void;`
I don't _think_ this will have any unwanted side effects. If authors agree, I can create a PR. 
Thanks in advance.

**Comment by yuliaHope** [comment]
This is not a root of problem. `react-table` don't know anything about onFilterChange, it dispatch onChange. 

**Possible solution**:
export type ReactTableFunction = (predicate?: any) => void;
export type FilterRender = (
    params: { column: Column; filter: any; onChange: ReactTableFunction; key?: string },
) => React.ReactElement<any>;

**Comment by SuperRunt** [comment]
@yuliaHope 
My bad, I should have updated this, but I got caught up in the project where I'm using this library. Your observation is correct and onFilterChange is indeed a problem, since that is what's defined in the type file, but it doesn't exist in the react-table code.

From line 13 in @types/react-table/index.d.ts:
`export type FilterRender = (params: { column: Column, filter: any, onFilterChange: ReactTableFunction, key?: string }) => React.ReactElement<any>;`
As you can see, the definition uses onFilterChange, which it shouldn't, and I think changing to use onChange is the way to go.

My code (based on library author's example): 
```
 let renderer: FilterRender = ({ filter, onChange }) =>
        <Dropdown onChanged={ (item) => onChange(item.key) } options={ this.options } />
```
Gives this TS error:
Type '{ column: Column; filter: any; onFilterChange: ReactTableFunction; key?: string | undefined; }' has no property 'onChange' and no string index signature.

Thanks for your time, and my apologies for not updating the code I shared with the correct function name.

**Comment by neokeld** [comment]
@SuperRunt @yuliaHope Same problem here. Indeed, react-table dispatch onChange on version 6.7.6 (last on github) and @types/react-table specifies onFilterChange on 6.7.5 version (latest).
(However we notice that on npmjs.org the latest version of react-table is 6.8.0 which is strange)

**Comment by SuperRunt** [comment]
@neokeld @yuliaHope

OK, so the solution should be to update two lines:
line 8 to: `export type ReactTableFunction = (predicate?:any) => void;`
line 13 to: `export type FilterRender = (params: { column: Column, filter: any, onChange: ReactTableFunction, key?: string }) => React.ReactElement<any>;`

Would that solve your issue, @neokeld ? If so, I'll submit a PR.

**Comment by neokeld** [comment]
I provide a link to the PR : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24034

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
