### ISSUE TITLE
@types/zen-observable/index has no default export

### ISSUE THREAD

**Issue by rbannat** [DefinitelyTyped/DefinitelyTyped#23849]
- [x] I tried using the `@types/zen-observable` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aicest 

Trying to compile without allowSyntheticDefaultImports in typescript compilerOptions throws ...@types/zen-observable/index has no default export.

```
node_modules/apollo-link/lib/index.d.ts(4,8): error TS1192: Module '"/node_modules/@types/zen-observable/index"' has no default export.

node_modules/apollo-link/lib/link.d.ts(2,8): error TS1192: Module '"/node_modules/@types/zen-observable/index"' has no default export.

node_modules/apollo-link/lib/linkUtils.d.ts(2,8): error TS1192: Module '"/node_modules/@types/zen-observable/index"' has no default export.

node_modules/apollo-link/lib/types.d.ts(2,8): error TS1192: Module '"/node_modules/@types/zen-observable/index"' has no default export.
```

**Comment by andy-ms** [comment]
`node -p 'require("zen-observable").default'` is undefined, so I think the type definition is right in this case.

**Comment by dwaynelavon** [comment]
@rbannat Any solution for this yet?

**Comment by rbannat** [comment]
@dwaynelavon I temporarily set `allowSyntheticDefaultImports` to true in typescript compiler options
