### ISSUE TITLE
Translating README in to Spanish

### ISSUE THREAD

**Issue by LuigiBaute** [DefinitelyTyped/DefinitelyTyped#23854]
HI! I would like to contribute with this project by offering a translation in to Spanish (my native language) I can translate any PR you want. I work for Utopian-io as translator. Let me know if interested!

**Comment by DanielRosenwasser** [comment]
Wow, this would be super awesome! Perhaps putting together a `README.es.md` would be helpful if you'd be up to the task. Just send a PR and feel free to tag me.

**Comment by LuigiBaute** [comment]
Hi! @DanielRosenwasser I've been arguing about the term ''lint, linting'' I understand lint means: A linter or lint refers to tools that analyze source code to flag programming errors, bugs, stylistic errors, and suspicious constructs.[1] The term is originated from a Unix utility that examined C language source code. Should I translate the word? I could mention it as an analyzer? let me know!

**Comment by LuigiBaute** [comment]
I'd also like to know the term _bundles_ and _stub_ to be able to translate'm or not. ?

**Comment by DanielRosenwasser** [comment]
From [this page](https://github.com/standard/standard/blob/master/docs/README-esla.md) it looks like the word "lint" and "linter" is used verbatim (i.e. un-translated). I think "bundle" should also be kept in its English form.

Stub is probably something that should be translated to Spansh; the basic meaning is like a "scaffolding", "skeleton", or "blueprint" - something that is meant to be filled in with real actual contents.

Feel free to have fun with conjugation though (e.g. "lintar", "bundlar", etc. 😄).
