### ISSUE TITLE
Question: Extending interface JQuery with TypeScript

### ISSUE THREAD

**Issue by Legends** [DefinitelyTyped/DefinitelyTyped#23888]
If you know how to fix the issue, make a pull request instead.

- [] I tried using the `@types/jQuery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu, @borisyankov  @choffmeister 

How to extend the `JQuery` interface to support jQuery plugin methods where the `options` parameter has an `Enum` property.

The problem with the below approach is, I have to create a separate module `EnumCircleShape.ts` and import it into my app.ts file.

While this works, it duplicates code (Enum in d.ts and EnumCircleShape.ts) and an additional import is required, in order to use the plugin in `app.ts`.

If I remove the `import` from `app.ts` I can successfully transpile with `tsc`, but then I get a runtime error:

[![enter image description here][1]][1]

*It works without importing if I remove the enum property of the `IOptions` interface. But this isn't a solution.*

**Usage (app.ts):**
  
     import { CircleShape } from "./EnumCircleShape";

        $("#slider").roundSlider({
            step: 20,
            circleShape: CircleShape.customQuarter
        });

**jQueryInterfaceExtensions.d.ts**

    interface JQuery {
        roundSlider(options: IOptions | string): jQuery;
    }
    
    interface IOptions {
        circleShape?: CircleShape;   
    }
    
     enum CircleShape {
        full = "full",
        halfTop = "half-top"
    }

**EnumCircleShape.ts**

     enum CircleShape {
        full = "full",
        halfTop = "half-top"
    }

  [1]: https://i.stack.imgur.com/yHvL5.png

**It would be good to make a little advanced tutorial how to extend `JQuery` as many plugins don't have a `.d.ts` available.**

**Comment by leonard-thieu** [comment]
You'd typically define `CircleShape` as a union of its possible values instead of creating an enum for it.

```typescript
type CircleShape = 'full' | 'half-top' | 'custom-quarter';
```

```typescript
$("#slider").roundSlider({
    step: 20,
    circleShape: 'custom-quarter'
});
```

**Comment by Legends** [comment]
```
type CircleShape = 'full' | 'half-top' | 'custom-quarter';

interface IOptions {
    circleShape?: CircleShape;
}
```

**app.ts**

```
import "./JQueryInterfaces";

$("#slider").roundSlider({
    circleShape:  .................
});
```
But then I don't have intellisense

**Comment by Legends** [comment]
Aaaa ok:

$("#slider").roundSlider({
    circleShape: "|"
});

I have add quotation marks and then Ctrl+Enter.

**Thanks a lot!**
