### ISSUE TITLE
WebPack Imported Module2 three_ColladaLoader is not a constructor

### ISSUE THREAD

**Issue by Perinban** [DefinitelyTyped/DefinitelyTyped#23918]
When I try to import the Collada file, I get the following error, Is there any way I could solve the problem?
The same happens when I add GITF loader.

The following code I have used.
1. npm install three --save
2. npm install --save @types/three

![collada](https://user-images.githubusercontent.com/26972975/36656905-6681e4b6-1af0-11e8-8970-ae0ee8307bab.png)

Below I have attached my code for it.

Map.html

    <ion-header>

      <ion-navbar>
        <ion-buttons >
          <button ion-button (click)="onOpenMenu()">
            <ion-icon name="menu"> </ion-icon>
          </button>
        </ion-buttons>
        <ion-buttons end>
          <button ion-button (click)="onOpenMenu()">Start Navigation
          </button>
        </ion-buttons>
        <ion-title></ion-title>
      </ion-navbar>

    </ion-header>

    <ion-content padding>
        <div id="WebGL output"></div>
    </ion-content>
Map.ts

      import { Component } from '@angular/core';
      import { NavController, NavParams, MenuController } from 'ionic-angular';

      import * as THREE from 'three';

      @Component({
        selector: 'page-map',
        templateUrl: 'map.html',
      })
      export class MapPage {

        constructor(public navCtrl: NavController, 
                          public navParams: NavParams,
                          private menuCtrl: MenuController) {
        }

        ionViewDidLoad() {

          let loader = new THREE.ColladaLoader();
          loader.load("assets/Building/MITblock.DAE", function (collada) {

          });

        }
        onOpenMenu() {
          this.menuCtrl.open();
        }
      }

**Comment by sentenza** [comment]
I'm facing the same issue and that's frustrating. I don't see any error in [the definition of the ColladaLoader](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/three/three-colladaLoader.d.ts) .

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
