### ISSUE TITLE
Naming pattern for typings whose modules are published to namespaces

### ISSUE THREAD

**Issue by pe8ter** [DefinitelyTyped/DefinitelyTyped#23961]
I don't see anything in the README that describes how to name typings whose modules are already namespaced. It looks like the pattern is to make the typings' directory follow the pattern `{namespace}__{package}` (note the two underscores), but I didn't see this spelled out anywhere.

My suggestion is to put this into the README after the other naming suggestion near the top.

I'd be happy to file a PR if you'd like.

**Comment by leonard-thieu** [comment]
I believe you're looking for this https://github.com/DefinitelyTyped/DefinitelyTyped#what-about-scoped-packages.

**Comment by pe8ter** [comment]
Geez. I went through the headings twice and still missed it. Embarrassing.

Thanks!
