### ISSUE TITLE
global declaration of Express.Request.user collides between @types/express-jwt and @types/passport

### ISSUE THREAD

**Issue by lietzi** [DefinitelyTyped/DefinitelyTyped#23976]
- [x] I tried using the `@types/express-jwt` & `@types/passport` package together and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- Authors: @horiuchi, @enaeseth, @theigor, @tlaziuk, @danielpa9708, @wokim, @kacepe, @Sl1MBoy  

Hello!
I used `@types/express-jwt` together with `@types/passport` in a project and getting this compile error:
`node_modules/@types/express-jwt/index.d.ts(52,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'user' must be of type 'User', but here has type 'any'.`

`@types/express-jwt` declaration of `user?: any` is colliding with the definition in `@types/passport` where the global property `user` of the `Request` interface in the `Express` namespace is defined as Type `User`.

I changed `user?: any` locally in `@types/express-jwt` to `user?: User` but does not know if this is appropriate for a PR.

Greetings,
Lietzi

**Comment by danielpa9708** [comment]
:thinking: Changing to `user?: User` in @types/express-jwt would not be appropriate for express-jwt does not depend on passport

**Comment by danielpa9708** [comment]
Maybe creating a pacakge just for holding the user definition and make passport and express-jwt depend on it ?

**Comment by lietzi** [comment]
@danielpa9708 thank you for your quick response..

I digged a little deeper in this issue..
at a first glimpse i thought `User` was declared in Express but as you mentioned 
it is declared in passport and so it is not a good idea to create a dependency here..
furthermore i found, that it is just introduced by your commit c75ee379eb78e44d3c7a04d0ab4f10ed93625c1d

So i think for now i will go back to the previous version 
and look for a proper solution later on..

**Comment by ali-habibzadeh** [comment]
Skip libs until it's fixed:

`"compilerOptions": {
    "skipLibCheck": true
  },`

**Comment by aberenyi** [comment]
Any update on this?

**Comment by danielpa9708** [comment]
don't think so, have any ideas ?

**Comment by wyattjoh** [comment]
Also experiencing issues. Unsure the best way to resolve.

**Comment by mctep** [comment]
@danielpa9708 what do you think about to add the same `User` interface from `@types/passport` to `@types/express-jwt`?

```ts
// @types/express-jwt
declare global {
    namespace Express {
        export interface Request {
            user?: User
        }

        interface User {
            [_: string]: string;
        }
    }
}
```

**Comment by danielpa9708** [comment]
It's ok by me, that would solve the problem,
I'm not sure if this is the right approach though

**Comment by mctep** [comment]
Hm... In my opinion it is the right approach because developers who uses `@types/express-jwt` should be able to extend their `req.user` object also. And looks like there is no other way other than define extendable interface.

**Comment by danielpa9708** [comment]
Ok, seems fair

**Comment by TheImpressionist** [comment]
So, I can see this is still a thing. 

```typescript
declare global {
    namespace Express {
        // tslint:disable-next-line:no-empty-interface
        interface AuthInfo {}
        // tslint:disable-next-line:no-empty-interface
        interface User {}

        interface Request {
            authInfo?: AuthInfo;
            user?: User;

            // These declarations are merged into express's Request type
            login(user: User, done: (err: any) => void): void;
            login(user: User, options: any, done: (err: any) => void): void;
            logIn(user: User, done: (err: any) => void): void;
            logIn(user: User, options: any, done: (err: any) => void): void;

            logout(): void;
            logOut(): void;

            isAuthenticated(): boolean;
            isUnauthenticated(): boolean;
        }
    }
}
```

It collides with my own solution.

**Comment by rclmenezes** [comment]
How to type request.user now:

```
type UserModel = import("../src/server/models/User").default;

declare namespace Express {
  export interface User extends UserModel {}
}
```

**Comment by omakoleg** [comment]
Fully redefining User within `Express` namespace also works
```
declare global {
    namespace Express {
        interface User {
            customerId: number
        }
    }
}
```

**Comment by wcjord** [comment]
> How to type request.user now:
> 
> ```
> type UserModel = import("../src/server/models/User").default;
> 
> declare namespace Express {
>   export interface User extends UserModel {}
> }
> ```

Where is the appropriate place to put this? Thank you!

**Comment by jeffstephens** [comment]
@wcjord put this anywhere that gets loaded in your codebase - I prefer to have it as close as possible to the entry point. Also, I had to use @omakoleg's solution with `declare global`.

**Comment by renatogbp** [comment]
I am using NestJS, and declaring a global User did not work for me. Still getting this error:
```
node_modules/@types/express-jwt/index.d.ts:43:13 - error TS2717: Subsequent property declarations must have the same type.  Property 'user' must be of type 'User', but here has type 'any'.

43             user?: any
               ~~~~

  node_modules/@types/passport/index.d.ts:24:13
    24             user?: User;
                   ~~~~
    'user' was also declared here.


Found 1 error.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
