### ISSUE TITLE
As of React 16, React.Component's setState should accept null or an updater function that returns null

### ISSUE THREAD

**Issue by joshhead** [DefinitelyTyped/DefinitelyTyped#23983]
As noted in the React 16 [release announcement](https://reactjs.org/blog/2017/09/26/react-v16.0.html#breaking-changes), when calling `setState` with `null` or if the updater function returns `null`, no update will be triggered.

The `setState` definition in DefinitelyTyped React [index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3f7c783b0a9add99477f9b88cb20886fca443b5b/types/react/index.d.ts#L287) does not allow `null` to be passed to `setState` or returned from the updater function (when `--strictNullChecks` is on), but both cases are valid uses of `setState`.

@ericanderson @vsiao

**Comment by ericanderson** [comment]
Im not sure thats true for `setState(null)` but it definitely true for `setState(() => null);`

Want to put in a PR? I'd approve that quickly (if you tag me)

**Comment by joshhead** [comment]
Looking at the code for [setState](https://github.com/facebook/react/blob/v16.2.0/packages/react/src/ReactBaseClasses.js#L53), the documentation string doesn't mention `null` as an allowed value, but the invariant check seems to let it through. I'm also going off of the release announcement, which says, "Calling setState with null no longer triggers an update." I think `this.setState(null)` used to be equivalent to `this.forceUpdate()`, but now it is essentially a no-op. So the code seems to be there to support `setState(null)` but I'm not sure whether developers are supposed to be able to rely on that behavior.

I will open a PR and tag you.

**Comment by TomasHubelbauer** [comment]
@joshhead I believe this issue should be closed since the PR has been merged?

**Comment by predragdavidovic** [comment]
Hi @ericanderson, when I put on my handle change setState({null}) or setState(() => null) render is called. And my component do re-render. I'm using 16.8.6
