### ISSUE TITLE
Knex generic support

### ISSUE THREAD

**Issue by darky** [DefinitelyTyped/DefinitelyTyped#24000]
*Note: this problem already mentioned https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10558 long time ago*

Now **knex** types so weak and abstract, because there is no possibility to pass generic, that mean particular table structure.

```typescript
// Instead this abstract code
knex("documents").where("timestamp", ">", 1519911406);

// I want to use generics
knex<{timestamp: number}>("documents").where("timestamp", ">", 1519911406);

// That show me, if I wrong
knex<{timestamp: number}>("documents").where("date", ">", 1519911406);
```

**Comment by taybin** [comment]
This can be closed as knex provides its own definitions now.  I believe knex-0.17's definitions support something similar to this.
