### ISSUE TITLE
Hapi - `Request.state` does is typed incorrectly.

### ISSUE THREAD

**Issue by SimonSchick** [DefinitelyTyped/DefinitelyTyped#24014]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/hapi` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jhsimms 

According to https://hapijs.com/api#serverstatename-options you can pass objects to this method as well.

**Comment by jhsimms** [comment]
@SimonSchick Looks correct.  I noticed the server.events.on and server.events.once definitions are also broken for the callback form, as they won't accept custom events.

**Comment by SimonSchick** [comment]
@jhsimms you're suppose to add overloads for these events, that's kind of the idea.

**Comment by SimonSchick** [comment]
This was fixed in #24956
