### ISSUE TITLE
jss: csstype incompatible with React/JSX common usage

### ISSUE THREAD

**Issue by estaub** [DefinitelyTyped/DefinitelyTyped#24049]
@pelotom @uniqueiniquity 

I believe the recent changes to the JSS typings are breaking for any JSX (React) user.
In JSX, pixel-valued CSS values are usually expressed as numbers, not strings, and csstype requires strings.  So something as simple as:

`jss.createStyleSheet({aStyle: {width:1}})
`
is now invalid; "1px" would be required.  @pelotom, too bad you didn't catch this, given https://github.com/frenic/csstype/issues/4#issue-294138953.

I hate to pour cold water on a lot of hard work, but I think rollback is recommended.
There are a lot of React JSS users, especially with the imminent release of material-ui 1.0.
You MAY want to consider use of the `CSSProperties` definition in @types/react (but probably not).

If we're lucky, I'm missing something!

**Comment by DanielRosenwasser** [comment]
#24050 should address this. Thanks for the heads up @estaub!

**Comment by frenic** [comment]
The default type for length can be changed to `string | number` in csstype using generic argument. The default was changed to `string | 0` to align with W3C standards. I'm sorry it caused this impact but I'll look into how to verify changes before releasing in the future.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23116#pullrequestreview-100975655
