### ISSUE TITLE
types/leaflet GeoJSON.setStyle method should take StyleFunction as input

### ISSUE THREAD

**Issue by juanargote** [DefinitelyTyped/DefinitelyTyped#24044]
- [x] I tried using the `@types/leaflet` package and had problems.
- Authors: @atd-schubert 

Based on leaflet's [GeoJSON documentation](http://leafletjs.com/reference-1.3.0.html#geojson-setstyle), the `GeoJSON.setStyle` method should take a `StyleFunction` as input, but since the method isn't overridden it currently expects a `PathOptions` as defined in FeatureGroup.

**Comment by atd-schubert** [comment]
I think here is a problem with the [original documentation](http://leafletjs.com/reference-1.3.0.html#geojson-setstyle) vs the [source code](https://github.com/Leaflet/Leaflet/blob/master/src/layer/GeoJSON.js#L148). According to the source code both seems to be right. Leaflet check if it is a style object or a styler function. Someone should make a PR for this... In addition also for the Leaflet documentation...
