### ISSUE TITLE
jest "mockResolvedValue" and "mockRejectedValue" and friends are missing

### ISSUE THREAD

**Issue by danawoodman** [DefinitelyTyped/DefinitelyTyped#24067]
It appears that `mockResolvedValue`, `mockResolvedValueOnce`, `mockRejectedValue`, `mockRejectedValueOnce` are missing (and maybe more?) from @types/jest even though they exist in the documentation:
https://facebook.github.io/jest/docs/en/mock-function-api.html#mockfnmockresolvedvaluevalue

I could not find a related issue so sorry if this is a duplicate

/cc @jwbay @NoHomey @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @AhnpGit

**Comment by wsmd** [comment]
Indeed they are. These methods are being added in #24046

**Comment by danawoodman** [comment]
Ok awesome. Weird that a project wide search didn't show that PR but maybe it is because there are so many types defined in the repo?
