### ISSUE TITLE
react-widgets: `id` property for `DateTimePicker`

### ISSUE THREAD

**Issue by zerkms** [DefinitelyTyped/DefinitelyTyped#24074]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rogierschouten @rogierschouten @frodehansen2 @r3nya 

At this point `DateTimePicker` and perhaps every other component from the `react-widgets` does not have a definition for the `id` property, yet they recommend having it

> To help ensure maximum accessibility, every widget should have an id attribute. 

at https://jquense.github.io/react-widgets/

Could somebody please add `id: string;` to the `interface ReactWidgetsCommonProps<C>` perhaps.

**Comment by RetroCraft** [comment]
Opened a pull request with suggested fix.

**Comment by r3nya** [comment]
@RetroCraft thank you!
