### ISSUE TITLE
openlayers formatConstructors in DragAndDropOptions type mismatch

### ISSUE THREAD

**Issue by levinzz** [DefinitelyTyped/DefinitelyTyped#24115]
As explained [in this openlayers issue](https://github.com/openlayers/openlayers/issues/7931), there seems to be a type mismatch with the `formatConstructors` parameter of `DragAndDropOptions`.

In index.d.ts, `formatConstructors` is defined like this : 
`formatConstructors?: Array<((n: ol.format.Feature) => any)>;`

I understand this as 

> formatConstructors can be null or an array of functions that take a feature as parameter and return _any_

From what I understand from the referenced issue, however it should be defined as follows:
> formatConstructors can be null or an array of functions that, when called with the new keyword, return an instance of ol.format.Feature.

@osechet @wb14123 @Ailrun @mylen @iamthechad @danmana @yairtawil @pierremarc : could you please look into it ?

**Comment by osechet** [comment]
I didn't know that Closure syntax. So I guess `formatConstructors` should be defined as an `Array<typeof ol.format.Feature>`.
@levinzz I don't have a project to test this right now. Can you make a try by manually modifying `node_modules/@types/openlayers/index.d.ts` in your project?

**Comment by levinzz** [comment]
After changing `DragAndDropOptions ` as you advised, it compiles without error. (and kml drop on the map happens to be working well)

```typescript
        /**
         * @typedef {{formatConstructors: (Array.<typeof ol.format.Feature>|undefined),
         *     projection: ol.ProjectionLike,
         *     target: (Element|undefined),
         *     source: (ol.source.Vector|undefined)}}
         */
        interface DragAndDropOptions {
            formatConstructors?: Array<typeof ol.format.Feature>;
            projection: ol.ProjectionLike;
            target?: Element;
            source?: ol.source.Vector;
        }
```

**Comment by osechet** [comment]
Great, thanks. The problem is we probably have others similar cases in the definitions. I'll have a look.

**Comment by osechet** [comment]
Good news: this is the only error of this kind.

**Comment by levinzz** [comment]
I somehow figured that too. I searched the openlayers api for a similar type and found only this one.
