### ISSUE TITLE
[@types/react-redux] redux as peerDependency

### ISSUE THREAD

**Issue by eps1lon** [DefinitelyTyped/DefinitelyTyped#24136]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors
@tkqubo @thasner @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo @pdeva

Currently types packages do not allow peerDependencies while the actual packages can have peerDependencies. In this case react-redux allows redux to match `^2.x.x || ^3.x.x || ^4.x.x`. The typings for redux v4 however have changed so typescript is throwing `All declarations of 'Dispatch' must have identical type parameters.` 

Adding ```"paths": {
      "redux": ["node_modules/redux"]
    }``` to my tsconfig did not solve this problem so I'm wondering what the current approach is to typings for peerDependencies that have their own typings.

**Comment by kenzierocks** [comment]
Duplicate of #21312 or #20299?

**Comment by eps1lon** [comment]
This was caused by an unrelated package that defined its own `Dispatch` type. It was however not obvious from the error message at which places a `Dispatch` type was defined so I confused this with a peerDependencies issue.
