### ISSUE TITLE
@type/react-color onChange is missing the `event' parameter

### ISSUE THREAD

**Issue by ralph-cheng** [DefinitelyTyped/DefinitelyTyped#24146]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @LKay @markspolakovs @mntdn

If you do not mention the authors the issue will be ignored.

According to the react-color document, the `onChange` props has the signature of `onChange(color, event)`.
See [2.13.4 documentation](https://github.com/casesandberg/react-color/blob/v2.13.4/docs/documentation/03.02-onChange.md) and [master documentation](https://github.com/casesandberg/react-color/blob/master/docs/documentation/03.02-onChange.md) for reference.

`event` has been missing from current [type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-color/index.d.ts#L31):
```javascript
export type ColorChangeHandler = (color: ColorResult) => void;
```
I did some simple debugging using react-color's documentation page, and found that the `event` parameter could be of different types. For example:

- If I click the color or the gradient, it is a `SyntheticMouseEvent`
- If I enter a RGB value, it is a `SyntheticKeyboardEvent` 
- If I drag over the gradient, it is a `SyntheticMouseEvent` (mousedown) followed by a sequence of `MouseEvent` as I drag

and the event.target also varies

- For `SyntheticMouseEvent` and `MouseEvent`, it is a div
- For `SyntheticKeyboardEvent`, it is an input

Without being too careful, it might make sense to define `onChange` to something like
```javascript
export type ColorChangeHandler = <T> (color: ColorResult, event: React.MouseEvent<T> | React.KeyboardEvent<T> | MouseEvent) => void;
```
It really isn't necessary to make `event` optional, as typescript is [designed to be unsound](https://www.typescriptlang.org/docs/handbook/type-compatibility.html) for this.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
