### ISSUE TITLE
Unable to instantiate XMLElementOrXMLNode in xmlbuilder 

### ISSUE THREAD

**Issue by akshaychannabasaiah** [DefinitelyTyped/DefinitelyTyped#24180]
- [x] I tried using the `@types/xmlbuilder` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

  - Authors: @wallymathieu 

If you do not mention the authors the issue will be ignored.
``` 
import * as XMLBuilder from 'xmlbuilder';
export class someClass{
toXML(): XMLBuilder.XMLElementOrXMLNode {
        var root = XMLBuilder.create('root')
            .ele('xmlbuilder')
            .ele('repo', { 'type': 'git' }, 'git://github.com/oozcitak/xmlbuilder-js.git')
            .end({ pretty: true }); // This returns a string while it should return a XMLElementOrXMLNode object
        var xml: XMLBuilder.XMLElementOrXMLNode = new XMLBuilder.XMLElementOrXMLNode();
        xml.text(root);        
        return xml;
    }
}
```
When I execute this code ablove, I get a `he.XMLElementOrXMLNode is not a constructor` error. There just seems to be no way to instantiate the XMLElementOrXMLNode object.

**Comment by wallymathieu** [comment]
Perhaps the surface area of the API has changed? So a pull request would then probably be welcome.

**Comment by akshaychannabasaiah** [comment]
I am only beginning with TypeScript. I am not sure how to proceed. But I sure will try it out this weekend. Thanks!
