### ISSUE TITLE
@types/webpack 4.1.0 - @types/tapable error

### ISSUE THREAD

**Issue by leebenson** [DefinitelyTyped/DefinitelyTyped#24239]
- [x] I tried using the `@types/webpack@4.1.0` package and had problems.
- Authors: @tkqubo @bumbleblym @bcherny @tommytroylin @mohsen1 @jcreamer898 @ahmed-taj @alan-agius4 @elliottsj @jason0x43

Bumping from @types/webpack 4.0.0 -> 4.1.0 introduced this error on Typescript build:

> node_modules/@types/webpack/index.d.ts(19,10): error TS2305: Module '"/Users/leebenson/dev/sandbox/wp4/node_modules/@types/tapable/index"' has no exported member 'Tapable'.
node_modules/@types/webpack/index.d.ts(19,19): error TS2305: Module '"/Users/leebenson/dev/sandbox/wp4/node_modules/@types/tapable/index"' has no exported member 'HookMap'.
node_modules/@types/webpack/index.d.ts(20,10): error TS2305: Module '"/Users/leebenson/dev/sandbox/wp4/node_modules/@types/tapable/index"' has no exported member 'SyncBailHook'.
node_modules/@types/webpack/index.d.ts(20,24): error TS2305: Module '"/Users/leebenson/dev/sandbox/wp4/node_modules/@types/tapable/index"' has no exported member 'SyncHook'.
node_modules/@types/webpack/index.d.ts(20,34): error TS2305: Module '"/Users/leebenson/dev/sandbox/wp4/node_modules/@types/tapable/index"' has no exported member 'SyncLoopHook'.
node_modules/@types/webpack/index.d.ts(20,48): error TS2305: Module '"/Users/leebenson/dev/sandbox/wp4/node_modules/@types/tapable/index"' has no exported member 'SyncWaterfallHook'.
node_modules/@types/webpack/index.d.ts(21,10): error TS2305: Module '"/Users/leebenson/dev/sandbox/wp4/node_modules/@types/tapable/index"' has no exported member 'AsyncParallelBailHook'.
node_modules/@types/webpack/index.d.ts(21,33): error TS2305: Module '"/Users/leebenson/dev/sandbox/wp4/node_modules/@types/tapable/index"' has no exported member 'AsyncParallelHook'.
node_modules/@types/webpack/index.d.ts(21,52): error TS2305: Module '"/Users/leebenson/dev/sandbox/wp4/node_modules/@types/tapable/index"' has no exported member 'AsyncSeriesBailHook'.
node_modules/@types/webpack/index.d.ts(21,73): error TS2305: Module '"/Users/leebenson/dev/sandbox/wp4/node_modules/@types/tapable/index"' has no exported member 'AsyncSeriesHook'.
node_modules/@types/webpack/index.d.ts(21,90): error TS2305: Module '"/Users/leebenson/dev/sandbox/wp4/node_modules/@types/tapable/index"' has no exported member 'AsyncSeriesWaterfallHook'.

**Comment by kkweon** [comment]
Is there a temporary fix for this?

**Comment by wKoza** [comment]
You can fix it with:

>"@types/tapable": "0.2.4",

**Comment by AviVahl** [comment]
```
> yarn info @types/tapable dist-tags
yarn info v1.5.1
{ latest: '0.2.5',
  'ts2.0': '0.2.4',
  'ts2.1': '0.2.4',
  'ts2.2': '0.2.4',
  'ts2.3': '1.0.0',
  'ts2.4': '1.0.0',
  'ts2.5': '1.0.0',
  'ts2.6': '1.0.0',
  'ts2.7': '1.0.0',
  'ts2.8': '1.0.0' }
```
DT needs to publish 1.0.0 as latest.

**Comment by rdsedmundo** [comment]
I'm with the same problem here.

wKoza's solution doesn't work as who is downloading this package is webpack itself.

**Comment by GabrielDuarteM** [comment]
@AviVahl  `yarn info @types/tapable dist-tags` now gives me `latest: '1.0.2',` as the latest version, but the issue still happens to me

**Comment by jcreamer898** [comment]
Would be really good to get a proper solution here, are there any ideas on what might be the issue? I'll help where I can.

**Comment by mariohmol** [comment]
Still not working at my side (1.0.0 and 1.0.2) adding in packge json a well... this was working just now in same machine.. some latest update on webpack did it?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
