### ISSUE TITLE
@types/kcors incorrect type definition for origin option

### ISSUE THREAD

**Issue by demisx** [DefinitelyTyped/DefinitelyTyped#24242]
@Xstoudi Please correct me if I am wrong, but I believe the type definition for https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/kcors/index.d.ts#L14 should be:

```ts
  origin?: ((ctx: Koa.Context) => string) | string;
```

**Comment by Xstoudi** [comment]
Yeah probably, don't hesitate to PR.

**Comment by demisx** [comment]
@Xstoudi Done. Please review at your earliest convenience.
