### ISSUE TITLE
Lodash _.get incorrectly assumes result is non-nullable

### ISSUE THREAD

**Issue by mxdubois** [DefinitelyTyped/DefinitelyTyped#24248]
I've encountered a case where the `_.get` typedef silently and incorrectly assumes that the return type is not null. This seems fairly dangerous as developers are likely to assume that typescript is checking null dereferences on the return value when they use `_.get` and `--strictNullChecks` together. 

----

**Case A - using a dot-separated path string** ⛔️
```
interface PropsA {
  institution?: { 
    name: string 
  };
}

const props: PropsA = { institution: undefined };

const nameOrNil = _.get(props, 'institution.name');
const lowercased = nameOrNil.toLowerCase();
```
_Expected:_ Raises "Object is possibly 'undefined'"

_Observed:_ Does not raise any type errors.

**Case B - using a top-level key** ✅
```
interface PropsB {
  institutionName?: string;
}

const props: PropsB = { institutionName: undefined };

const nameOrNil = _.get(props, 'institutionName');
const lowercased = nameOrNil.toLowerCase();
```
_Expected:_ Raises "Object is possibly 'undefined'" 

_Observed:_ Raises "Object is possibly 'undefined'" (this case works correctly)

**Environment**
Relevant versions:
```
typescript@2.7.1
lodash@4.17.4
@types/lodash@4.14.104
```

Command: `tsc --p . --noEmit`

tsconfig: 
```
{
  "compilerOptions": {
    "lib": ["dom", "es7"],
    "outDir": "./dist/",
    "pretty": true,
    "strict": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "strictNullChecks": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "module": "es6",
    "moduleResolution": "node",
    "target": "es2018",
    "jsx": "react",
    "allowJs": true,
    "sourceMap": true,
    "baseUrl": ".",
    // Must match webpack.config.js resolve settings
    "paths": {
      "mfi/*": ["./src/*"]
    },
    "typeRoots" : ["./types", "./node_modules/@types"]
  }
}
```

**Authors:** @bczengel, @chrootsu, @stepancar, @aj-r, @ailrun, @e-cloud, @thorn0, @jtmthf, @DomiR

I really appreciate you all maintaining these types! Let me know if I can help clarify anything.

**Comment by aj-r** [comment]
In your first case, I believe _.get is returning any, since we have no idea
what the return type will be. I agree that it would be nice to return a
more specific type, but I don't think that's possible with Typescript.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
