### ISSUE TITLE
history package missing EventListenerOrEventListenerObject

### ISSUE THREAD

**Issue by CzBuCHi** [DefinitelyTyped/DefinitelyTyped#24264]
- [x] I tried using the `@types/xxxx` package and had problems.
- Authors: @sergey-buturlakin @ngbrown @rokoroku 

file: DOMUtils.d.ts
error TS2304: Cannot find name 'EventListenerOrEventListenerObject'.

fixed locally by `type EventListenerOrEventListenerObject = any;` but i rather to have official fix ....

**Comment by Kumagor0** [comment]
@CzBuCHi how exactly did you fix locally? Like, in what file did you add ```type EventListenerOrEventListenerObject = any;```? I tried doing it in main js file but it didn't fix the error. Did you copy the whole @types/history into your repository and added that line?

**Comment by CzBuCHi** [comment]
@Kumagor0 nope ... i just edited file in node_modules folder :)

**Comment by name1ess0ne** [comment]
Have same issue

**Comment by congqiao** [comment]
I'm having the same issue with TypeScript 3.

TypeScript 2 works.

**Comment by rokoroku** [comment]
Did you add `'dom'` to the `compilerOptions.lib` in your `tsconfig.json` file?
`type EventListenerOrEventListenerObject` is located in `lib.dom.d.ts`

see this link: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L16866

**Comment by name1ess0ne** [comment]
I have tried to add "dom", but seems it conflicts with react-native:
A lot of errors like this:
```
node_modules/@types/react-native/globals.d.ts:66:3 - error TS2717: Subsequent property declarations must have the same type.  Property 'body' must beof type 'string | ArrayBuffer | ArrayBufferView | Blob | FormData | URLSearchParams | ReadableStream | null | undefined', but here has type 'string |ArrayBuffer | DataView | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | Blob | FormData | null | undefined'.

66   body?: BodyInit_;
     ~~~~

node_modules/@types/react-native/globals.d.ts:92:14 - error TS2300: Duplicate identifier 'RequestInfo'.


92 declare type RequestInfo = Request | string;
                ~~~~~~~~~~~

  ../../../../../usr/local/lib/node_modules/typescript/lib/lib.dom.d.ts:17154:6
    17154 type RequestInfo = Request | string;
               ~~~~~~~~~~~
    'RequestInfo' was also declared here.
```

**Comment by name1ess0ne** [comment]
Hi guys, we have solved this issue in our project. It is a best workaround that we have found for now.
What needs to be done.

1. Create folder with name typings in your app directory
2. Add this lines in your tsconfig.json
```
{
    "compilerOptions": {
        "typeRoots": ["./typings", "./node_modules/@types"]
    },
    "include": ["./typings/**/*.ts", "./src/**/*.ts*" ]
}
```
3. Inside typings folder create file with name that matches *.d.ts (for example historyFix.d.ts)
4. Add this code to the file
`interface EventListenerOrEventListenerObject {}`
5. Now app should compile

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
