### ISSUE TITLE
[nodegit] Cannot import a single export from a module 

### ISSUE THREAD

**Issue by turtle11311** [DefinitelyTyped/DefinitelyTyped#24275]
- [x] I tried using the `@types/nodegit` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dolanmiu @JimiC 

When i transpile typescript code below, generated js code is not require nodegit module.
```typescript
// source code
import { Clone } from 'nodegit'

Clone.clone('url', 'path', {
  bare: 0
})
```

```javascript
// generated code
"use strict";
exports.__esModule = true;
nodegit_1.Clone.clone('url', 'path', {
    bare: 0
});
```

**Comment by JimiC** [comment]
As it happens I too have come up with some strange behavior when using the `esModuleInterop` flag. As it turns out the typings need some refining.

**Comment by dolanmiu** [comment]
Are you sure you are importing it correctly?

I have read this:

https://jaxenter.com/discovering-typescript-2-7-141060.html

And it says:

As part of the endeavor to find the best way to interoperate with existing “legacy” module formats, TypeScript introduces the new -- esModuleInterop flag for callable Common JS modules. Under the new feature, these modules must be imported as default imports, as seen below:

```ts
import express from "express";
```

So maybe you need to do:

```ts
import nodegit from "nodegit";
```

**Comment by JimiC** [comment]
`import nodegit from "nodegit";` works when you use `esModuleInterop` but you lose debugging ability. Stoping the code on a breakpoint and hovering over `nodegit` you don't get any intellisense. We will have to refine the typings to export also a `namespace` so we can use `import * as nodegit from "nodegit";`

**Comment by JimiC** [comment]
After all `nodegit` itself is non-callable and falls in the `starImport` category.

**Comment by dolanmiu** [comment]
Could it be because it should be

```ts
export * from "./buf"
export * from "./attr"
```

etc etc

**Comment by JimiC** [comment]
I haven't found how to do it yet, cause I have other pressing RL matter going on. But you are more than welcome to ponder on it and suggest an improvement. I'll certainly look at it as soon as I find some time as I need it for a project I'm in.

**Comment by dolanmiu** [comment]
I am in the process of updating the `nodegit` typings but for a different reason

The official API doc is very inconsistent with the examples shown in the nodegit repo

Missing methods, methods which dont work, attributes which should be methods etc. Weird...

**Comment by JimiC** [comment]
Yeah, I had a conversation with the team and they recently fixed the docs generation script. It may still be gronky.

**Comment by turtle11311** [comment]
Is it not recommended to import a single export from a module?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
