### ISSUE TITLE
Unnecessary *-tests.ts dependencies on "mocha" causing problems

### ISSUE THREAD

**Issue by cspotcode** [DefinitelyTyped/DefinitelyTyped#24295]
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

I would like to update the mocha declarations in a way that requires TS2.1. (for `keyof`)  However, the tests for many *other* declarations in this repository reference mocha.  They are unrelated to mocha; they do this solely so their test file can be structured like mocha tests (using `describe` and `it` calls) even though the tests will never be executed.

I would like to create a separate declaration for these situations.  This way I can impose the TS2.1 requirement for my updated mocha declarations without requiring TS2.1 in all these other, unrelated declarations.

Here's an example, [types/webdriverio/webdriverio-tests.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webdriverio/webdriverio-tests.ts#L1-L7).

Currently it is:
```
/// <reference types="mocha" />
// ...
describe("webdriver.io page", () => {
    it("should have the right title - the good old callback way", () => {
```

I would like to change the `<reference>`:
```
/// <reference types="mocha-dt-shim" />
```

... where "mocha-dt-shim" will be an incomplete copy of the mocha declarations, compatible with TS 2.0, declaring the `describe()`, `it()`, etc functions that these other *-tests.ts files are expecting.

Is this the best approach?  How can I suppress this declaration from being published to npm?  Is there a better name?  A better place to put it?  Should I use `<reference path=` instead of `<reference types=`?

Any guidance is appreciated.

@wwestrop @andy-ms @simondel @aleung @falsandtru @ericeslinger @smhxx

**Comment by andy-ms** [comment]
It might be better to just use blocks and comments.
```ts
{ // webdriver.io page
    { // should have the right title - the good old callback way
        ...tests here...
    }
}
```
That's if the separated blocks are really worthwhile. Some files also put separate tests in separate functions (that are never called).

**Comment by cspotcode** [comment]
I was hoping to minimize the amount of effort just to update the mocha declarations.  So instead of making big changes to a dozen other declarations, I'd just change their `/// <reference>`.  But if you think this is more ideal, I can do it this way.

**Comment by andy-ms** [comment]
For a quick fix you could just copy-paste the following:
```ts
declare function describe(s: string, cb: () => void): void;
declare function it(s: string, cb: () => void): void;
```

**Comment by cspotcode** [comment]
That's actually what I started with.  Ok, thank you for the second opinion!  I'll go with that.
