### ISSUE TITLE
Openlayers types typo

### ISSUE THREAD

**Issue by fvr17** [DefinitelyTyped/DefinitelyTyped#24337]
- [x] I tried using the `@types/openlayers` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @osechet, @wb14123, @ailrun, @mylen, @iamthechad, @danmana, @yairtawil, @pierremarc

If you do not mention the authors the issue will be ignored.

There is a typo in index.d.ts of @types/openlayers
Line 7544:

>type Units = "degress" | "ft" | "m" | "pixels" | "tile-pixels" | "us-ft";

It should be:
>type Units = "degrees" | "ft" | "m" | "pixels" | "tile-pixels" | "us-ft";

("degrees" instead of "degress")

**Comment by osechet** [comment]
@fvr17 Yes, you're right. I'll fix it.
