### ISSUE TITLE
Typo in bot email

### ISSUE THREAD

**Issue by screendriver** [DefinitelyTyped/DefinitelyTyped#24352]
I found a typo in the email that I received from the TypeScript Bot 😉 

```
Thank you for submitting this PR!

Because this PR doesn't have any code reveiwers...
```

~reveiwers~ reviewers

**Comment by ffflorian** [comment]
This was fixed in https://github.com/RyanCavanaugh/dt-mergebot/pull/6 but apparently not applied yet.
