### ISSUE TITLE
@types/d3 d3.pie.value parameters' type are incompatible 

### ISSUE THREAD

**Issue by justforuse** [DefinitelyTyped/DefinitelyTyped#24371]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/d3` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek

I use `@tyeps/d3` int this way
```
class GroupCountData{
    proportion: number;
}

...

const pie: Pie<void, GroupCountData> = d3.pie()
            .sort(null)
            .value((d: GroupCountData, i: number, data: GroupCountData[]): number => {
                return d.proportion;
            });
```

and an error happened:
```
Error:(479, 20) TS2345: Argument of type '(d: GroupCountData, i: number, data: GroupCountData[]) => number' is not assignable to parameter of type '(d: number | { valueOf(): number; }, i: number, data: (number | { valueOf(): number; })[]) => num...'.
  Types of parameters 'd' and 'd' are incompatible.
    Type 'number | { valueOf(): number; }' is not assignable to type 'GroupCountData'.
      Type 'number' is not assignable to type 'GroupCountData'.
```
What's wrong?
Thanks your help

**Comment by denisname** [comment]
`const pie: Pie<void, GroupCountData> = d3.pie()`
should be
`const pie = d3.pie<void, GroupCountData>()`

**Comment by tomwanzek** [comment]
To expand a little on @denisname 's comment. The TS definitions for `pie<...>()` in d3-shape contain the following JSDoc comment for the overload when it is used with two generic parameters.
```ts
/**
 * Constructs a new pie generator with the default settings.
 *
 * Ensure that the accessors used with the pie generator correspond to the arguments passed into them,
 * or set them to constants as appropriate.
 *
 * The first generic corresponds to the type of the "this" context within which the pie generator and its accessor functions will be invoked.
 *
 * The second generic refers to the data type of an element in the input array passed into the Pie generator.
 */
export function pie<This, Datum>(): Pie<This, Datum>;
```

So, as @denisname points out, the second template parameter corresponds to `GroupCountData` in your case. The first generic parameter is the `this` context in which the generator and its accessor functions will be invoked. So, `void` does not seem very appropriate. If the `this` context does not matter to your use case, just let it default to `any`, you can then simply go with the shorter overload: `pie<GroupCountData>()` which returns `Pie<any, GroupCountData>`.

**Comment by tomwanzek** [comment]
@justforuse Have the above comments answered your question? If so, please close the issue. If not, let us know what else we can do to resolve... 😄

**Comment by justforuse** [comment]
thanks
