### ISSUE TITLE
[@type/readct-redux] Type 'S' does not satisfy the constraint 'Action<any>'

### ISSUE THREAD

**Issue by ysunf** [DefinitelyTyped/DefinitelyTyped#24396]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be   @@ignored.
@tkqubo @thasner @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo 

I'm a newer to react and redux. I try to build a basic project with typescript2.7.2, react, redux., antd.
I got this error:
>  node_modules\@types\react-redux\index.d.ts
(29,35): error TS2344: Type 'S' does not satisfy the constraint 'Action\<any\>'

the src code is this:
```
type Dispatch<S> = Redux.Dispatch<S>;
```

My code is this:
```
//index.tsx
ReactDOM.render(
    <Provider store={store}>
        <UIApp />
    </Provider>,
  document.getElementById('root') as HTMLElement
);
registerServiceWorker();
```

```
//app.tsx
class App extends React.Component<any, State> {
  render() {
    const { level, onIncreaseClick } = this.props;
    return (
      <div className="App">
        <Row gutter={2} className="gutter-row">
          <Col span={6}>
            <div className="gutter-box">
              <RobotaoRepeatUISimilarXpathUnit />
            </div>
          </Col>
          <Col span={7}>
            <div className="gutter-box">
              <RobotaoRepeatUIRelativeXpathUnit />
            </div>
          </Col>
          <Col span={8}>
            <div className="gutter-box">
              <RobotaoRepeatUIOtherSettingUnit />
            </div>
          </Col>
          <Col span={3}>
            <div className="gutter-box">
              <RobotaoRepeatUIControlUnit />
            </div>
          </Col>
        </Row>
        <Row>         
          <Col span={24}>
            <ButtonGroup>
              <Button type="primary" size="small"><Icon type="left" />Backward</Button>
              <Button size="small" disabled={true}>Pages</Button>
              <Button type="primary" size="small" onClick={onIncreaseClick}>Forward<Icon type="right" /></Button>
            </ButtonGroup>
          </Col>
        </Row>
        <Row>
          <Col span={24}>
            <TestComponent name="李默然" level={level}/>
          </Col>
        </Row>
        <Row type="flex" justify="space-between" align="bottom">
          <Col span={4}><DemoBox value={100}>col-4</DemoBox></Col>
          <Col span={4}><DemoBox value={50}>col-4</DemoBox></Col>
          <Col span={4}><DemoBox value={120}>col-4</DemoBox></Col>
          <Col span={4}><DemoBox value={80}>col-4</DemoBox></Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (state: State) => {
  return { level: state.level };
}

const mapDispatchToProps = (dispatch: Dispatch) => {
  return {
    onIncreaseClick: () => dispatch(IncrementAction)
  }
}

export const UIApp = connect(mapStateToProps, mapDispatchToProps)(App);
```

```
//actions.tsx

export const IncrementAction = { type: "increase" };
```

```
//reducer.tsx
interface Action {
    type: string;
}

export type State = {
    level: number;
}

const reducer = (state: State = {level: 1}, action: Action) => {
    switch (action.type) {
        case 'increase':  
            return {level: state.level + 1};
        default:
            return state;
    }
};

export const store = createStore(reducer);
```

```
//TestComponent.tsx
export interface TestComponentProps {
    name: string;
    level: number;
}

class TestComponent extends React.Component<TestComponentProps, {}> {
    render() {
        const { name, level } = this.props;

        if (level <= 0) {
            throw new Error(`Character Level Cannot be ${level}`);
        }
        return(
            <div className="TestComponent">
                Hello {name}, Level: {level}
            </div>
            );
    }
}

export default TestComponent;
```
I've tried some methods. Including install typescript@2.6.2, but still same error.
I import and use 'Dispatch' in 'App.tsx'.
however, if I change the code into this:
```
const mapStateToProps = (state: State) => {
  return { level: state.level };
}

export const UIApp = connect(mapStateToProps, )(App);
```
still the same error.

**Comment by andnp** [comment]
Ah yes, it appears that [this commit](https://github.com/reactjs/redux/commit/cbdca6215e1891e97120ac05c971618182455e54#diff-b52768974e6bc0faccb7d4b75b162c99) in redux changed the contract for dispatch. I'm guessing you are using redux v4 pre-release?

**Comment by ysunf** [comment]
@andnp thanks for your suggestion in reactjs/redux,  indeed, there are several differences, I'll check them out. Thanks

**Comment by alexey-pelykh** [comment]
redux v4 is a release, any updates on this?

**Comment by andnp** [comment]
I haven't gotten a chance to test it myself, but it appears #25109 will fix this issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
