### ISSUE TITLE
[@types/elasticsearch] SearchParams definition doesn't include body

### ISSUE THREAD

**Issue by marcoreni** [DefinitelyTyped/DefinitelyTyped#24403]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/elasticsearch` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CasperSkydt , @bfsmith , @ddunkin , @pushplay , @mlamp , @ahmadferdous , @SimonSchick , @brabster , @deerawan 

`SearchParams` does not support `body`, as documented here:
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-search

**Comment by mlamp** [comment]
Hey,

it should include through GenericParams, check: 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3d5138fc4bad7aea4a1a49f85e113717901261dc/types/elasticsearch/index.d.ts#L588
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3d5138fc4bad7aea4a1a49f85e113717901261dc/types/elasticsearch/index.d.ts#L129-L136

**Comment by marcoreni** [comment]
Oh you're right! Don't know why I didn't see it rightaway.

Sorry, need to drink more coffee...
