### ISSUE TITLE
[@types/autobahn] The OnChallengeHandler may return a promise

### ISSUE THREAD

**Issue by konsultaner** [DefinitelyTyped/DefinitelyTyped#24408]
@421p According to : https://github.com/crossbario/autobahn-js/issues/178#issuecomment-374587657 and https://github.com/cujojs/when/issues/505#issuecomment-374590862

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/autobahn/index.d.ts#L209

May return a promise object or just a string. I'm new to TypeScript otherwize I would have done a pull request

    type OnChallengeHandler = (session: Session, method: string, extra: any) => When.Promise<string>;

**Comment by konsultaner** [comment]
Would this be the correct notation?

    type OnChallengeHandler = (session: Session, method: string, extra: any) => When.Promise<string> | string;

**Comment by Waqas-Zamir** [comment]
how should I get token asynchronously inside onChallengeHandler?

**Comment by konsultaner** [comment]
If you need to implement a custom authentication using oAuth or if you want to provide a second challenge factor coming from another challenge, i.e. an SMS-tan or a hardware token.

**Comment by Waqas-Zamir** [comment]
but the OnChallengeHandler is not returning Promise.

type OnChallengeHandler = (session: Session, method: string, extra: any) => string;

**Comment by konsultaner** [comment]
I know. This is the issue. In JavaScript it is possible to return either a string or a promise. But the typescript definition only shows the string as possible return value. I guess this is what it is needed to be changed to:

>     type OnChallengeHandler = (session: Session, method: string, extra: any) => When.Promise<string> | string;

**Comment by Waqas-Zamir** [comment]
That fix will be really appreciated.
Waiting for the fix in typescript.
