### ISSUE TITLE
Puppeteer typings assume global DOM lib types

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DefinitelyTyped/DefinitelyTyped#24419]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @marvinhagemeister @cdeutsch @jwbay

Using Puppeteer in a Node project without the dom type `NodeListOf` gives type errors. `@types/puppeteer` should provide an empty `interface NodeListOf { }` shim for compilation runs that don't include the different `"lib"` set. It should also compile without the dom lib types.

```
../../node_modules/@types/puppeteer/index.d.ts:754:30 - error TS2304: Cannot find name 'NodeListOf'.

754     pageFunction: (elements: NodeListOf<Element>, ...args: any[]) => any,
                                 ~~~~~~~~~~
```

Edit: double-checked; it's just `Element`, `Node`, and `NodeListOf`.

**Comment by tarunjangra** [comment]
I think, i am struggling with similar problem. 

> 
../../../node_modules/@types/puppeteer/index.d.ts(740,29): error TS2304: Cannot find name 'Element'.

740     pageFunction: (element: Element, ...args: any[]) => any,
                                ~~~~~~~


../../../node_modules/@types/puppeteer/index.d.ts(754,30): error TS2304: Cannot find name 'NodeListOf'.

754     pageFunction: (elements: NodeListOf<Element>, ...args: any[]) => any,
                                 ~~~~~~~~~~


../../../node_modules/@types/puppeteer/index.d.ts(754,41): error TS2304: Cannot find name 'Element'.

754     pageFunction: (elements: NodeListOf<Element>, ...args: any[]) => any,

**Comment by JoshuaKGoldberg** [comment]
For now, make stub interfaces for those interfaces in your own files:

```typescript
// See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24419

interface Element { }
interface Node { }
interface NodeListOf<TNode = Node> { }
```

**Comment by cdeutsch** [comment]
Is there a reason you don't just bring in the "dom" types in your tsconfig file?

Puppeteer loads up a web browser, so I think it makes sense to use the "dom" types, even in Node. (assuming it doesn't cause other issues)

**Comment by tarunjangra** [comment]
Yeah, as you said there is no harm to define "dom" types in tsconfig. 
Thanks.

**Comment by JoshuaKGoldberg** [comment]
There is harm in defining the `"dom"` types in the tsconfig. Although Puppeteer loads up a web browser, the Node process launching it doesn't have access to the global browser-specific variables such as `name` and `performance`. See https://github.com/Microsoft/TSJS-lib-generator/issues/327

Even for apps that run in the context of the browser, it's not unreasonable to intentionally exclude `"dom"` and to let UI-specific libraries (Angular, React, Vue, etc.) deal with browser specifics.

**Comment by richard-joseph-dunelm** [comment]
Until this is resolved, `skipLibCheck` could also be used (tsconfig, package.json). See:

https://github.com/firebase/firebase-tools/issues/749#issuecomment-383246748

**Comment by HopperGithub** [comment]
Is there any solution to resolve or ignore this error?
`node_modules/@types/puppeteer/index.d.ts(182,30): error TS2304: cannot find name 'Element'`

**Comment by NikhilVerma** [comment]
It would be useful if Typescript (along with existing lib) also exported interfaces. So you could so something like

```js
import { Window } from 'typescript/lib/lib.dom.namespaced';

page.evaluate(() => {
    (window as Window).alert('something');
});

```

**Comment by heroneto** [comment]
Hi people, i'm facing the same problem with types definition, and Element is not exported from any Lib.

To get apropriate intelisense with **el** methods, i changed my code with below example:

From:
``` 
...  
await page.waitForTimeout(3000)
await page.waitForSelector('button[type=submit]') 
await page.$eval('button[type=submit]', el => el.click())
await page.waitForNavigation({waitUntil: "load"})
await page.goto(url)
...
```

To this:
``` 
...  
await page.waitForTimeout(3000) 
await page.waitForSelector('button[type=submit]')
await page.$('button[type=submit]').then(el => {
  el.click()
})
await page.waitForNavigation({waitUntil: "load"})
await page.goto(url)
...
```

![image](https://user-images.githubusercontent.com/41599309/100899925-19133400-34a1-11eb-8fc4-e6b7c6701c55.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by tannerlyons** [comment]
If anyone finds this issue in the future and wants an easy solution, you can use [a triple-slash directive ](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-lib-) in the file you write your puppeteer code in.

It's not perfect, but it allows you to say "I'm writing node code but for JUST this file tell the compiler to assume the DOM is also available". as @JoshuaKGoldberg [noted](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24419#issuecomment-376201164), this is dangerous. It would be reasonable to make sure the puppeteer code is isolated in its own file.

```tsx
/// <reference lib="DOM" />

import puppeteer from "puppeteer";

// Do your puppeteer stuff.
export const runMyPuppeteerCode = async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  await page.goto(url);

  const someElement: Element = await page.evaluate(() => {
    const aButton = document.querySelectorAll(".my-button");
     ...
```
