### ISSUE TITLE
[@types/crypto-js] Can't add option object to the SHA3 function

### ISSUE THREAD

**Issue by gimyboya** [DefinitelyTyped/DefinitelyTyped#24425]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @misak113 

the `SHA3` function provides an option to control the output length as shown in this example:

```javascript
    var hash = CryptoJS.SHA3("Message", { outputLength: 512 });
    var hash = CryptoJS.SHA3("Message", { outputLength: 384 });
    var hash = CryptoJS.SHA3("Message", { outputLength: 256 });
    var hash = CryptoJS.SHA3("Message", { outputLength: 224 });
``` 
however when i am getting the following type error when trying to specify the the `outputLength`:

```
Argument of type '{ outputLength: number; }' is not assignable to parameter of type 'string | WordArray | undefined'.
  Object literal may only specify known properties, and 'outputLength' does not exist in type 'string | WordArray | undefined'.
```

**Comment by misak113** [comment]
Let's create a PR for it ;) @gimyboya It make sense

**Comment by gimyboya** [comment]
@misak113 good initiative :) so here we go
```typescript
type Hash = (message: string | LibWordArray, key?: string | WordArray, ...options: any[]) => WordArray;
```
this is how the function is defined and to solve the problem i did this
```typescript
const hash = CryptoJS.SHA3(data, undefined, { outputLength: 256 });
```
[[source]](https://stackoverflow.com/questions/49396548/cant-add-option-object-to-the-sha3-function-with-typescript)
so the problem is that typescript is forcing me to declare the `key` parameter which in the declaration it's still optional with the `?` token

i don't really know how to fix this on the `@types/crypto-js` file

**Comment by misak113** [comment]
Ok, now I see the problem. I needed to refactor Hash functions a little. Look at associated PR. Is it correct?

**Comment by gimyboya** [comment]
Ohh yeah we could overload the functions.
I will have to try it once I have the time :)
