### ISSUE TITLE
@types/geojson can't be installed

### ISSUE THREAD

**Issue by GiulioMRBS** [DefinitelyTyped/DefinitelyTyped#24436]
- [X ] I tried using the `@types/geojson` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz @richseviora @theruther4d @guilhermehubner

I can't install terraformer-wkt-parser, because it has "@types/geojson": "^1.0.0"  as dependency.
I tried to install @types/geojson and it doesn't work. It seems that the entire repository has been removed.

![installterraformer](https://user-images.githubusercontent.com/1579333/37703463-0ee0d7b8-2cf6-11e8-85e1-a98f857b009e.PNG)

![installgeojson](https://user-images.githubusercontent.com/1579333/37703461-0ec18408-2cf6-11e8-8d4a-0a76b26aba08.PNG)

**Comment by redbmk** [comment]
This still seems to be an issue...it's not giving me a 403, but I do get:

```
$ npm i -D @types/geojson
npm ERR! code ETARGET
npm ERR! notarget No matching version found for es-abstract@1.14.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'object.values'
npm ERR! notarget
```

I would have guessed the install would really just consist of copying over the `index.d.ts` file...

**Comment by redbmk** [comment]
The error I had stemmed from using `npm install` in a project that was using `yarn` 🤦‍♂ . That's a pretty misleading error though 😕.

Anyway, I'm able to install `@types/geojson` fine now that I've realized my mistake. Seems like this issue should be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
