### ISSUE TITLE
Underscore: Chain of object, and then map is wrong

### ISSUE THREAD

**Issue by Ciantic** [DefinitelyTyped/DefinitelyTyped#2447]
```
var obj: { [k: string] : number } = {
       'test' : 5,
       'another' : 8,
       'third' : 10
    },
    empty = {};

_.chain(obj).map(function (value, key) {
    empty[value] = key;
    console.log("vk", value, key);
});
```

This gives error, it assumes `value` to be of type obj, in fact it is a number. I tried to fix this, but couldn't yet wrap my head around this. Somehow it's trying to use ListIterator for objects _after_ using a chain for objects.

`error TS2008: Value of type '{}' is not indexable by type '{ [k: string]: number; }'`

**Comment by yoursunny** [comment]
I cannot reproduce this bug on `@types/underscore` 1.8.9 with `underscore` 1.8.3 or 1.9.1
I guess the issue is resolved, and can be closed?
