### ISSUE TITLE
Property 'xml' does not exist on type 'typeof "node_modules/@types/d3/index"

### ISSUE THREAD

**Issue by deniska-info** [DefinitelyTyped/DefinitelyTyped#24516]
- [x] I tried using the `@types/d3` package and had problems.
- [x] I tried using the 2.6.2 version of tsc. https://www.npmjs.com/package/typescript

  - Authors: @andy-ms 
  - Authors: @tomwanzek 

According this issue https://github.com/d3/d3-fetch/issues/14 the following methods were added to d3-fetch 1.1.0: 
- d3.html
- d3.svg
- d3.xml

Is there any chance that `@types/d3` will support these methods?
Thank you!

**Comment by tomwanzek** [comment]
@LeDragon, I will take a run at upgrading **d3-fetch** to 1.1, will let you know for review.
