### ISSUE TITLE
next/dynamic doesn't match dynamic import spec

### ISSUE THREAD

**Issue by lifeiscontent** [DefinitelyTyped/DefinitelyTyped#24537]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/106d393592fe348ea3da2ef1fc1faa1317e045b5/types/next/dynamic.d.ts#L27

@andy-ms hey do you think you could update the definition to match the import spec?

by default dynamic import returns `{default: Promise<React.ComponentType<TCProps>>}` not `Promise<React.ComponentType<TCProps>>`

**Comment by andy-ms** [comment]
Pull requests accepted. I'm not familiar with this library, the authors are @dru89 and @brikou.
