### ISSUE TITLE
jquery append does not accept JQuery type

### ISSUE THREAD

**Issue by cmoedk** [DefinitelyTyped/DefinitelyTyped#24553]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly,   @leonard-thieu

#https://github.com/DefinitelyTyped/DefinitelyTyped/commit/44a9d083d4186908b951885aec029fae602b7eb5#diff-38ca0d3fc099227b1c19a1df229bc03e

I think this is the  commit that stopped .append from accepting JQuery type. The line changed was

`append(...contents: Array<JQuery.htmlString | JQuery.TypeOrArray<JQuery.Node> | JQuery>): this;`

to
 
`append(...contents: Array<JQuery.htmlString | JQuery.TypeOrArray<JQuery.Node> | JQuery<JQuery.Node>>): this;`

[Example](https://imgur.com/a/2aS7p)

Typescript: "typescript": "^2.7.2"
Types: "@types/jquery": "^3.3.1",

Using Webstorm 2018.1

**Comment by cmoedk** [comment]
Nevermind, was some bug in webstorm...

**Comment by G-Rath** [comment]
@cmoedk I'm having the same problem - Was there a bug reported on YouTrack for this? or did you have another solution?

**Comment by cmoedk** [comment]
Now I'm mad, that I didn't comment how I resolved the bug in webstorm. I would think I either invalidated caches and restarted, or updated webstorm to a newer version.
