### ISSUE TITLE
[@types/react-native] missing RequestInfo, RequestInit and Response.

### ISSUE THREAD

**Issue by josemigallas** [DefinitelyTyped/DefinitelyTyped#24551]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @huhuanming @iRoachie @timwangdev @kamal @nelyousfi 

I have a React Native module (aka library) written in TS but when I try to transpile it using `tsc` it throws me the following errors:
```
node_modules/@types/react-native/globals.d.ts(24,31): error TS2304: Cannot find name 'RequestInfo'.
node_modules/@types/react-native/globals.d.ts(24,51): error TS2304: Cannot find name 'RequestInit'.
node_modules/@types/react-native/globals.d.ts(24,73): error TS2304: Cannot find name 'Response'.
```
My dependencies in package.json are:
```
  ...
  "peerDependencies": {
    "react-native": "0.53.3"
  },
  "devDependencies": {
    "@types/react": "^16.0.41",
    "@types/react-native": "^0.52.19",
    "tslint": "^5.9.1",
    "typescript": "^2.7.2"
  }
```
And when I go open `node_modules/@types/react-native/globals.d.ts` the IDE shouts there are unknown types:

![screen shot 2018-03-27 at 13 23 51](https://user-images.githubusercontent.com/11672286/38019844-f9a15278-3278-11e8-9383-94af5f98b7ea.png)

So I can only assume that the file is missing these classes or that I somehow need to depend on some other @types that I don't know of yet. I would imagine these are in `@types/react` but no.

Thanks in advance.

**Comment by Fatkhi** [comment]
Try adding DOM declarations in `tsconfig.json`. Like this:
```
{
  ...,
  "compilerOptions": {
    ...,
    "lib": [
      "dom"
    ]
  }
}
```

**Comment by timwangdev** [comment]
Actually `RequestInfo`, `RequestInit` and `Response` have included in `es6` lib, it's not necessary to add `dom` lib in tsconfig

**Comment by binki** [comment]
@Fatkhi Adding `dom` triggers #24573.

@timwangdev I see [the definitions in `lib.es6.d.ts`](https://github.com/Microsoft/TypeScript/blob/23ed9f842301ab8c7894823afc7a356da960adcf/lib/lib.es6.d.ts#L21837), but I still get the error even if I put `"lib":["es6"]`. Is there anything that would cause TypeScript to skip those definitions when I have `"lib"` set like that?

**Comment by newyankeecodeshop** [comment]
This has been addressed by #25255. Can you upgrade the types and see if it fixes this?
Also, do not add the "dom" library to your `tsconfig.json`. React Native does not implement the DOM or most of the browser JavaScript runtime. You don't want people using those features accidentally.

**Comment by shivawu** [comment]
Confirm this is fixed for me, thanks a lot for fixing this fast!

**Comment by newyankeecodeshop** [comment]
Awesome. Would you mind closing this?
