### ISSUE TITLE
[@types/react] Strict version of CSSProperties?

### ISSUE THREAD

**Issue by trisrael** [DefinitelyTyped/DefinitelyTyped#24568]
[CSSProperties](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/93fd7cb02d7eaa6366a979bdc1b32559d9153d25/types/react/index.d.ts#L823) allows for [any key to be added]( 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2446).

When mistakes like `var myStyles = { marginTopt: "12px" }` are made they throw no error.

Is it possible to provide an interface without the `[key: string]: any` and then have `CSSProperties` extend it and add the `[key: string]: any`?

**Comment by Kovensky** [comment]
Now that @types/react is using `csstype`, this will eventually be provided by https://github.com/frenic/csstype/pull/21

**Comment by arnauorriols** [comment]
`@keyframes` is not included in `CSS.Properties`, and therefore it is no longer a valid property of a `React.CSSProperties` object. How can I use @keyframes (or any other at-rule) from now on?

**Comment by pelotom** [comment]
@arnauorriols in what context are you trying to use `@keyframes`? @-rules are not allowed in inline styles, which is all React's `CSSProperties` are intended to capture. Are you using a downstream CSS-in-JS library which is using React's `CSSProperties` as a proxy for all valid CSS? If so, that library should depend directly on `csstype` and patch its typings as needed.

**Comment by arnauorriols** [comment]
> Are you using a downstream CSS-in-JS library which is using React's CSSProperties as a proxy for all valid CSS? If so, that library should depend directly on csstype and patch its typings as needed.

I'm using `JSS`. It's not a mistake of the library but mine. `csstype` is the correct way to go. Thanks!
