### ISSUE TITLE
Cannot find name Set/Map

### ISSUE THREAD

**Issue by Legends** [DefinitelyTyped/DefinitelyTyped#24627]
My `webpack.config.ts` (dev dependency, should not go to `outDir`) that's why I put it in my root folder and not under `rootDir`. 
Therefore it is throwing the above error.

How to configure this: Compile it and don't throw errors for `webpack.config.ts` and don't copy the output of it to `outDir`?

If I exclude it, it won't compile it, of course.

**Comment by Legends** [comment]
Changing to ` "module": "es2015",` fixed it, before I had `es6`.

I thought `es6 == es2015` ?

**Comment by nerdkid93** [comment]
Yeah, I ran into this issue as well. The @types/webpack `index.d.ts` file uses `Set` and `Map` but those aren't defined anywhere in that file (and they aren't imported from one of @types/webpack's dependencies either)

**Comment by Legends** [comment]
Usually if you have this problem you add `"lib": ["es6"] `, I had a different one, that i solved extending tsconfig.json
