### ISSUE TITLE
Could not find a declaration file for module 'lodash-es'. 

### ISSUE THREAD

**Issue by Legends** [DefinitelyTyped/DefinitelyTyped#24676]
@stephenlautier 

> Could not find a declaration file for module 'lodash-es'. 'c:/.../node_modules/lodash-es/lodash.js' implicitly has an 'any' type.
>   Try `npm install @types/lodash-es` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash-es';`

I have installed:
```
yarn add lodash-es
yarn add @types/lodash-es
```

![image](https://user-images.githubusercontent.com/966368/38195538-32f26b30-367e-11e8-99de-a912af6f1291.png)

**package.json**
```
    "lodash-es": "^4.17.8"
  },
  "devDependencies": {
    "@types/lodash-es": "^4.17.0",
```

**Comment by aj-r** [comment]
I'm not sure what's going on but it looks like a configuration issue. Have you set a value for `typeRoots` in your `tsconfig.json`? If not, you should be fine. If you have, does it include `"node_modules/@types"`? Also have you verified that the `lodash-es` folder does exist inside  `node_modules/@types`?

**Comment by Legends** [comment]
Hm, I have opened this issue, afterwards I have uninstalled `lodash-es`, installed it now again and it works...
Strange...

**Comment by xgqfrms** [comment]
# it works  ✅

```sh
$ yarn add lodash-es

$ yarn add -D @types/lodash-es

```

**Comment by justingolden21** [comment]
For anyone using a specific lodash package as a standalone (for example, using `lodash.merge` with `import merge from 'lodash.merge';`)

`npm install -D @types/lodash.merge` (or of course `yarn add` or `pnpm` etc)
