### ISSUE TITLE
Helmet types missing referrerPolicy option

### ISSUE THREAD

**Issue by yonilerner** [DefinitelyTyped/DefinitelyTyped#24707]
- [X] I tried using the `"@types/helmet": "0.0.37"` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors
  - @cyrilschumacher 
  - @EvanHahn 

The `referrerPolicy` middleware seems to be missing entirely from the definitions.

**Comment by EvanHahn** [comment]
I worked on [adding TypeScript support to the `referrerPolicy` middleware](https://github.com/helmetjs/referrer-policy/compare/typescript) to be distributed with the module. I'm waiting for some [corrections to `connect`'s type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24883) before continuing.

**Comment by yonilerner** [comment]
Thank you!

**Comment by EvanHahn** [comment]
The updates to `connect`'s DefinitelyTyped type definitions have been merged, so I'm unblocked. I'll hopefully get to adding support in the next few weeks!

**Comment by yonilerner** [comment]
@dajomu Im a little confused here. The PR you linked says that its merged, and I can clearly see the change here: https://github.com/dajomu/DefinitelyTyped/blob/master/types/helmet/index.d.ts but when I do `npm install --save-dev @types/helmet`, the change isnt in the installed package. Ive removed and re-added it also. Also tried on a brand new project. Any ideas?

**Comment by EvanHahn** [comment]
@yonilerner I tried `npm install @types/helmet` in a new directory and it seemed to include the changes. Maybe you're not downloading the newest version?

**Comment by yonilerner** [comment]
Finally figured it out. I use a proxy to access NPM packages, and the proxy's cache needed to be invalidated. Thanks for the help.
