### ISSUE TITLE
No JSDoc comments for bootstrap.d.ts

### ISSUE THREAD

**Issue by jmatthiesen** [DefinitelyTyped/DefinitelyTyped#2475]
The bootstrap.d.ts definitions don't have any JSDoc comments. There's great documentation on the Bootstrap site (http://getbootstrap.com/javascript/), it would be nice to have these incorporated into the d.ts file.

**Comment by jakebailey** [comment]
Cleaning up old issues; as far as I can tell, the boostrap package has loads of JSDoc comments these days.
