### ISSUE TITLE
Typescript Bot won't admit we broke up!

### ISSUE THREAD

**Issue by richseviora** [DefinitelyTyped/DefinitelyTyped#24782]
I removed myself from the React authors list as I didn't have bandwidth to contribute, but I'm still getting [tagged on PRs](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24780).

Could someone help me tell Typescript Bot that it's not them, it's me? 😄 

- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

@dt-bot @Flarna

**Comment by Flarna** [comment]
@richseviora Don't know why you think that I can help in this. I have no special rights in this repo nor any special friendship with @typescript-bot 😁.
My best guess is that the content of .github/CODEOWNERS is used instead the content of the index.d.ts file.

@andy-ms I think you are way better than me in helping here.

**Comment by RyanCavanaugh** [comment]
Yeah, we haven't automated updating of the CODEOWNERS file. I had a script to regenerate it but I'm not sure where it is...

**Comment by richseviora** [comment]
@mhegazy @andy-ms please re-open this. #24847 did not remove my name from the `types/react`.

**Comment by andy-ms** [comment]
#24849

**Comment by richseviora** [comment]
@andy-ms thank you! This is much appreciated :)
