### ISSUE TITLE
Cannot find module 'csstype'

### ISSUE THREAD

**Issue by liketurbo** [DefinitelyTyped/DefinitelyTyped#24788]
Hi, I am trying to use react with typescript, I installed (`react`, `react-dom`), (`@types/react`, `@types/react-dom`), in attempt to launch project I get error `ERROR in [at-loader] ./node_modules/@types/react/index.d.ts:55:22` `Cannot find module 'csstype'`. I tried `npm i csstype` in `@types/react` and in root of project. Also despite to error, in module `@types/react` exists folder node_modules/csstype, so I don't even know why this error happens.

***tsconfig.json***
```
{
    "compilerOptions": {
        "outDir": "./build/", // path to output directory
        "strictNullChecks": true, // enable strict null checks as a best practice
        "module": "es6", // specify module code generation
        "jsx": "react", // use typescript to transpile jsx to js
        "target": "es5", // specify ECMAScript target version
        "allowJs": true, // allow a partial TypeScript and JavaScript codebase
        
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
    },
    "exclude": [
        "node_modules"
    ],
    "include": [
        "./source/**/*.tsx",
        "./source/**/*.ts"
    ]
}
```   
**package.json**
```
{
  "name": "suggestion-app",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "webpack:server": "babel-node node_modules/.bin/webpack-dev-server --mode=development"
  },
  "dependencies": {
    "react": "^16.3.1",
    "react-dom": "^16.3.1"
  },
  "devDependencies": {
    "@types/react": "^16.3.5",
    "@types/react-dom": "^16.0.4",
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-3": "^6.24.1",
    "caniuse-lite": "^1.0.30000697",
    "clean-webpack-plugin": "^0.1.19",
    "css-loader": "^0.28.11",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.10.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.7.0",
    "file-loader": "^1.1.11",
    "glob": "^7.1.2",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "^0.4.0",
    "postcss-cssnext": "^3.1.0",
    "postcss-loader": "^2.1.3",
    "purify-css": "^1.2.5",
    "purifycss-webpack": "^0.7.0",
    "script-ext-html-webpack-plugin": "^2.0.1",
    "webpack": "^4.5.0",
    "webpack-cli": "^2.0.14",
    "webpack-dev-server": "^3.1.1"
  }
}

```
**source/index.ts**
```
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import './styles/main.css';

ReactDOM.render(
  <h1>Hello, world!</h1>,
  document.getElementById('root')
);
```
*OS: Ubuntu 17.10*

**Comment by frenic** [comment]
Try `compilerOptions.moduleResolution: true`

**Comment by bencoveney** [comment]
I had this error as well.

`moduleResolution: true` gives me errors - and isn't listed in [the docs](https://www.typescriptlang.org/docs/handbook/compiler-options.html) as a valid value - but setting `moduleResolution: "node"` looks like it has done the job 👍

**Comment by frenic** [comment]
Sorry, I meant to say `"node"` 😆 Changed my comment.

**Comment by HJava** [comment]
Set `"moduleResolution": "node"` is useful for me, too.

**Comment by jcrben** [comment]
Can anyone provide color on why? Is there an update that would make setting this unnecessary?

**Comment by frenic** [comment]
If `compilerOptions.module === "AMD" or "System" or "ES6"` the default for `compilerOptions.moduleResolution` would be `"Classic"`, otherwise it's `"Node"`. So if you use one of these module strategies, but have all your packages under `node_modules`. The `compilerOptions.moduleResolution` must be set to `"Node"`.

For `Classic`:
> For non-relative module imports, however, the compiler walks up the directory tree starting with the directory containing the importing file, trying to locate a matching definition file.

For `Node`:
> Node will look for your modules in special folders named node_modules. A node_modules folder can be on the same level as the current file, or higher up in the directory chain. Node will walk up the directory chain, looking through each node_modules until it finds the module you tried to load.

([source](https://www.typescriptlang.org/docs/handbook/module-resolution.html))

**Comment by svipben** [comment]
`"module": "commonjs"` fixed this issue for me, try it.

**Comment by austinbruch** [comment]
For those using `classic` module resolution who _don't_ want to change to `node` module resolution, I was able to get around this problem by adding a `paths` entry for `csstype` in my `tsconfig.json`, since my project is using the `baseUrl` config option. See [baseUrl documentation](https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url) for more details.

Obviously, this is not a scalable approach if you have many conflicts like this, but this was our first and this has at least bought us some time if we want to consider switching over to `node` module resolution.

**Comment by aventurella** [comment]
I was running into this as well.

Via WebPack + TypeScript 
```
Module not found: Error: Can't resolve 'csstype' 
```

What fixed it for me, which is likely pretty hackey, but as of TS 2.9 you can `import()` types (https://blogs.msdn.microsoft.com/typescript/2018/05/31/announcing-typescript-2-9/#import-types), so I did this and it compiles now without complaint:

```
type VisibilityProperty = import('csstype').VisibilityProperty;
type AnimationProperty = import('csstype').AnimationProperty;
```

**Comment by htbkoo** [comment]
Hi. Thanks for the suggestion [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24788#issuecomment-379575711) of setting `compilerOptions.moduleResolution: "node"`.
However unfortunately, the moduleResolution is already set as "node" when I created the project using [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript).

I will keep on checking but would be great if someone already knew the answer and can tell me how to fix it :-)

**Comment by Rahul-Sagore** [comment]
I am changing `types/react-tag-autocomplete` and running `npm run lint react-tag-autocomplete`. Getting same error, `error TS2307: Cannot find module 'csstype'`.

After adding `"moduleResolution": "node",` in `compilerOptions` of `react-tag-complete`'s `tsconfig.json`, it gives error: `Error: Unexpected compiler option moduleResolution`.

Any help?

**Comment by mike-marcacci** [comment]
This drove me nuts trying to author a type definition that depended on react. It turns out that the `csstype` library has its own TS definitions, which are thus not present in the `/types` directory of this repo. I created an issue in dtslint to address this:

https://github.com/Microsoft/dtslint/issues/226

**Comment by nossbigg** [comment]
For me, setting the `moduleResolution` param didn't work, so I manually performed the solution to which @mike-marcacci had already suggested at the [PR he raised at the `dtslint` repo](https://github.com/microsoft/dtslint/issues/226):
```bash
cd types/react
npm i
```

**Comment by mcmar** [comment]
@Rahul-Sagore I'm getting the same error as you. Did you ever figure out how to resolve this?

**Comment by Rahul-Sagore** [comment]
@mcmar Nope.

**Comment by agustin107** [comment]
> @Rahul-Sagore I'm getting the same error as you. Did you ever figure out how to resolve this?

You have to install dependencies of `types/react` and that will work :)

**Comment by fyodore82** [comment]
I also have this issue.
1. Setting `"moduleResolution": "node",`  give me error `Error: Unexpected compiler option moduleResolution`
2. I've tried to

    cd types\react
    npm i

Then running `npm run lint <my-package>` shows me huge amount of errors with `csstype` like

    ../react/node_modules/csstype/index.d.ts(2071,31): error TS1005: '(' expected.
    ../react/node_modules/csstype/index.d.ts(2083,19): error TS2693: 'LetterSpacingProperty' only refers to a type, but is being used as a value here.
    ../react/node_modules/csstype/index.d.ts(2083,49): error TS1005: '(' expected.
    ../react/node_modules/csstype/index.d.ts(2096,15): error TS2693: 'LineBreakProperty' only refers to a type, but is being used as a value here.

And several hundreds of similar lines

**Comment by DanceParty** [comment]
Same error as @fyodore82 after performing steps 1/2

**Comment by flearsmedia** [comment]
Solve it by write "node" with a capital "N":

> "moduleResolution": "Node"

Works on our side.

https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by psmaAaron** [comment]
The `"moduleResolution": "Node"` solution didn't fix it for me, but going into the `/types/react` directory and running `npm install` resolved the issue.

**Comment by orta** [comment]
Hi folks, we just shipped a new version of dtslint (4.0.7) which includes https://github.com/microsoft/dtslint/pull/319 - what this change does is give a very actionable error message when you end up in this state:

```sh
> yarn lint gatsby-plugin-breakpoints

Error: 
A module look-up failed, this often occurs when you need to run `npm install` on a dependent module before you can lint.

Before you debug, first try running:

   npm install --prefix /Users/ortatherox/dev/typescript/DefinitelyTyped/types/react

Then re-run. Full error logs are below.

Errors in typescript@4.3 for external dependencies:
../react/index.d.ts(38,22): error TS2307: Cannot find module 'csstype' or its corresponding type declarations.

    at /Users/ortatherox/dev/typescript/dtslint/bin/index.js:207:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/ortatherox/dev/typescript/dtslint/bin/index.js:6:58)
```

Because the DT repo doesn't have a lockfile, this means anyone cloning from basically now shouldn't hit this issue in the future. For anyone else, I'd expect doing either `yarn upgrade` and whatever the  `npm` version is will bump your dtslint and it will show that too.

**Comment by pshoniuk** [comment]
Changing the import to Type-Only Import (TypeScript ^3.8) solved the issue for me.

`import type * as CSS from 'csstype'` => `import type * as CSS from 'csstype'`

**Comment by ruslanaplid** [comment]
For me:
Copy paste `node_modules/csstype` to `node_modules/@type`
