### ISSUE TITLE
Typings needed, and started, for RSVP Promise Library.

### ISSUE THREAD

**Issue by Taytay** [DefinitelyTyped/DefinitelyTyped#2479]
I created a Gist that contains the type definitions I made for the RSVP Promise library:
https://gist.github.com/Taytay/2f66bc465e43a2f16efe

I haven't written unit tests for it, and haven't gone over this with a fine toothed comb. However, we use it in our project, and I'm hopeful that if anyone else does a search for RSVP typings here, they'll stumble across this and think, "Wow, let's finish this!"

(I wasn't sure what to do with this code since it isn't PR ready. Please let me know if there is a better way to do "submit" this to the community.)

**Comment by ryanone** [comment]
Hi @Taytay - I know this was discussed a long time ago, but now that TSD is deprecated, is there a plan to move this to [typings registry](https://github.com/typings/registry)?
