### ISSUE TITLE
@types/gm missing .in method

### ISSUE THREAD

**Issue by kachkaev** [DefinitelyTyped/DefinitelyTyped#24795]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ChaosinaCan @maartenvanvliet

Hi guys 👋  Looks like gm's [`.in` method](https://github.com/aheckmann/gm#custom-arguments) is missing. It is used to send custom args to `gm/im` and it'd be great if you could add it!

## Code
```js
import * as gm from "gm";

const im = gm.subClass({ imageMagick: true });

export const convert = (
  sourcePath: string,
  targetPath: string,
  size: number,
  quality: number,
): Promise<void> =>
  new Promise<void>((resolve, reject) => {
    im(sourcePath)
      .resize(size)
      .quality(quality)
      .in("-background", "white", "-alpha", "remove")
      .write(targetPath, (err) => (err ? reject(err) : resolve()));
  });
```

## Problem

<img width="552" alt="screen shot 2018-04-07 at 21 41 01" src="https://user-images.githubusercontent.com/608862/38460152-654142c8-3aac-11e8-89e4-3eafc0ec1287.png">

## Workaround

```ts
      // @ts-ignore
      .in("-background", "white", "-alpha", "remove")
```
↑ this disables type checking in further chained calls, e.g. `.write()`

**Comment by ChaosinaCan** [comment]
I haven't done anything with gm recently, so I'm not sure I could make and test a proper fix, but I will gladly review any changes to fix this.
