### ISSUE TITLE
@types/wordcloud - node_modules/@types/wordcloud/index.d.ts' is not a module.

### ISSUE THREAD

**Issue by KayHS** [DefinitelyTyped/DefinitelyTyped#24838]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andy-ms 

I get the following errors when using this package.

 node_modules/@types/wordcloud/index.d.ts' is not a module.

using Angular 5

import * as WordCloud from 'wordcloud';
or 
import { WordCloud } from 'wordcloud';

**Comment by andy-ms** [comment]
I don't see evidence that this actually is a module? As far as I can tell, this is only available by the `WordCloud` global variable. Could you test to find out what works at runtime, ignoring type errors?

**Comment by KayHS** [comment]
@andy-ms you're right it works at run time, but this type error is annoying. Ive omitted import { WordCloud } from 'wordcloud'; for now because its not doing anything.

**Comment by andy-ms** [comment]
Are you saying that an `import` statement works at runtime, or that it works without the `import`?

**Comment by KayHS** [comment]
Works without because like you mentioned it is a global variable. instead i just used. const WordCloud = require('wordcloud');

it makes me wonder what is the point of this package?

**Comment by andy-ms** [comment]
If you need to `require('wordcloud')` then that implies that the packages *is* available as a module and the type definition should be updated.

**Comment by KayHS** [comment]
Yes just to recap how i got it work

1. `npm install wordcloud --save`
2. add to the scripts array in .angular-cli.json `../node_modules/wordcloud/src/wordcloud2.js`
3. in component `const WordCloud = require('wordcloud'); `

However, the author does say it is not a module. https://github.com/timdream/wordcloud2.js/issues/115

So i am equally confused why this works.
