### ISSUE TITLE
[react-native] ART Path type

### ISSUE THREAD

**Issue by alexdunne** [DefinitelyTyped/DefinitelyTyped#24830]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy, @huhuanming, @iRoachie 

Hey. I'm trying to use the Art package in React Native and found a missing type `Path`. I implemented the types myself but got stuck when I realised `Path` returns either the same instance or if, no further methods are called, a path.

This is where I got up to:

```
// ... 

interface ARTPath {
    path: number[];
    penDownX: number | null;
    penDownY: number | null;
    penX: number;
    penY: number;
};

interface ARTPathStatic {
    (): ARTPathStatic | ARTPath;
    arc(
        x: number,
        y: number,
        rx?: number,
        ry?: number,
        outer?: boolean,
        counterClockwise?: boolean,
        rotation?: number
    ): ARTPathStatic | ARTPath;
    arcTo(
        x: number,
        y: number,
        rx?: number,
        ry?: number,
        outer?: boolean,
        counterClockwise?: boolean,
        rotation?: number
    ): ARTPathStatic | ARTPath;
    close (): ARTPathStatic | ARTPath;
    moveTo (x: number, y: number): ARTPathStatic | ARTPath;
}

// ...

export interface ARTStatic {
    ClippingRectangle: ClippingRectangleStatic;
    Group: GroupStatic;
    Path: ARTPathStatic; // **Addition here**
    Shape: ShapeStatic;
    Surface: SurfaceStatic;
    Text: ARTTextStatic;
}
```

Here is an example of the `Circle` being implemented. as you can see `Path` is a builder. However, you don't need to call `close` to get the path. For example this will return a valid path:

```
var path = Path().moveTo(0, -radius)
        .arc(0, radius * 2, radius)
        .arc(0, radius * -2, radius)
```

[Here is the Path class](https://github.com/sebmarkbage/art/blob/master/core/path.js) and [this is the 'Class' it extends](https://github.com/sebmarkbage/art/blob/master/core/class.js). From what I can gather, the second link is what returns you the path if no further methods are called.

My question is how do I setup `ARTPathStatic` so that it can return either itself or `ARTPath`.

Thanks 👍

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
