### ISSUE TITLE
[jss] Support simple (e.g. "&:hover") pseudo-selectors of jss-nested.

### ISSUE THREAD

**Issue by estaub** [DefinitelyTyped/DefinitelyTyped#24862]
Consider support for simple jss-nested pseudo-selectors like &:hover, which I suspect are the overwhelming majority of pseudo-selector use in jss.  csstype has pseudoselectors, but of course they are without the leading ampersand, which is a trigger for jss-nested. 

Support might look like the attached [pseudos.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1892345/pseudos.ts.txt), together with a definition or two at some level leveraging those, e.g. roughly

```ts
export type CSSDeclBlock = 
    CSS.Properties<string | number> & {[key in Pseudos]?:CSS.Properties<string | number>}
```

It might make sense to try to get the [pseudos.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1892345/pseudos.ts.txt) definitions into `csstype`, but probably only as a separate, standalone file.

**Comment by estaub** [comment]
If anyone goes after this, you _may_ want to also think about nested media-queries in the same syntactic position.  These are considerably harder to come up with a reasonable solution for, because there is no hope of a library-provided lexicon of likely keys; the developer must declare, or provide some way to infer, the keys that they are using.  I ended up with this, which is definitely lame but may help seed thought: 

```ts
export type CSSDeclBlock<ODDKEYS extends string =''> = 
    CSS.Properties<string | number> & {[key in Pseudos]?:CSS.Properties<string | number>}  & {[key in ODDKEYS]?:CSS.Properties<string | number>}

//=== used as:

// Force string-constant typing.  
// Consider use of a  string enum; 
//   see https://basarat.gitbooks.io/typescript/docs/types/literal-types.html

const mqSmallWindow: '@media (max-width: 1280px) and (max-height: 1024px)' = 
    '@media (max-width: 1280px) and (max-height: 1024px)'
const mqNotSmallWindow: '@media (min-width: 1281px), (min-height: 1025px)' = 
    '@media (min-width: 1281px), (min-height: 1025px)'

export type UsedMediaQueries = typeof mqSmallWindow | typeof mqNotSmallWindow

type MyCSSBlock = CSSDeclBlock<UsedMediaQueries>

```

**Comment by pelotom** [comment]
The issue here is with Material UI, not `@types/jss`: https://github.com/mui-org/material-ui/issues/11004

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
