### ISSUE TITLE
[@types/temp] error TS2307: Cannot find module '.'

### ISSUE THREAD

**Issue by rogerta** [DefinitelyTyped/DefinitelyTyped#24872]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/temp` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DanielRosenwasser
---
I see the following error when compiling typescript code with `@types/temp@0.8.1`:
```
.../node_modules/@types/temp/index.d.ts(10,23): error TS2307: Cannot find module '.'.
```
This module is being installed as a dependency of `polymer-cli@1.7.0-pre.4`.  I am compiling with typescript version 2.8.1.

The following change seems to correct the problem.  Replace the line:

```
import * as temp from ".";
```
with:
```
import * as temp from "./index";
```

**Comment by rogerta** [comment]
This issue is also present in `@types/temp@0.8.31`.

**Comment by DanielRosenwasser** [comment]
@rogierschouten was there any reason you switched it to `"`?

**Comment by DanielRosenwasser** [comment]
Also, I believe that should still just work; any clue @mhegazy @RyanCavanaugh?

**Comment by rogierschouten** [comment]
@DanielRosenwasser  yes that was important, something broke, but I can't remember it right now. It had something to do with the Node resolution algorithm when multiple versions of the same module were present, or with a circular dependency that gets created when the typings refer to themselves by name.

I can try to look it up next week when I'm back at work and have access to our Git repo

**Comment by rogierschouten** [comment]
@poelstra @mgroenhoff @peterkooijmans  I discussed this with all of you at the time, something with linked npm installations I think, can you remember what this was?

**Comment by rogierschouten** [comment]
I just remembered what the problem was.  When the 'temp' typings refer to 'temp' (i.e. `require('temp')`, there are circumstances where the require call resolves to a DIFFERENT VERSION of the typings (when NPM has loaded multiple versions of a set of typings in a recursive module). 

Requiring `require('.')` instead of `require('temp')` ensures that you always get the proper version.

The problem doesn't arise with your average run-of-the-mill NPM usage but it did for us.

**Comment by rogerta** [comment]
Got it.  How about my suggestion of replacing `'.'` with `'./index'`?  Does that also break things in your scenario?

**Comment by rogierschouten** [comment]
@rogerta I think it would be ok, as it resolves to the same thing.
