### ISSUE TITLE
jqlite.d.ts have no selector for children()(line:125)

### ISSUE THREAD

**Issue by PratyushaBoppana** [DefinitelyTyped/DefinitelyTyped#24947]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/angular/jqlite.d.ts` file and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@borisyankov 
@choffmeister 
@Steve-Fenton 
@Diullei 
@tasoili 
@jasonswearingen 
@seanski 
@Guuz 
@ksummerlin 
@basarat 
@nwolverson 
@derekcicerone 
@AndrewGaspar 
@seikichi 
@benjaminjackman 
@pksorensen 
@JoshStrobl 
@johnnyreilly 
@DickvdBrink 
@King2500 
@leonard-thieu 
@andrewiggins 

If you do not mention the authors the issue will be ignored.

**Comment by leonard-thieu** [comment]
> `children()` - Does not support selectors

[AngularJS's jqLite](https://docs.angularjs.org/api/ng/function/angular.element#angularjs-s-jqlite)

---

If you need support for selectors, add `jquery` and `@types/jquery` to your project.

**Comment by PratyushaBoppana** [comment]
But, in method documentation it is saying that it accept selectors
    /**
     * Get the children of each element in the set of matched elements, optionally filtered by a selector.
     *
     * @see {@link https://api.jquery.com/children/}
     */
    children(): this;

**Comment by leonard-thieu** [comment]
The method documentation is incorrect. That's an error from copying over the definitions from `@types/jquery`.

**Comment by PratyushaBoppana** [comment]
Okay. Thank you
