### ISSUE TITLE
[@types/protractor-helpers] - Would be good to split the Jasmine dependency

### ISSUE THREAD

**Issue by hepiyellow** [DefinitelyTyped/DefinitelyTyped#24969]
@johncant I tried using this package from a project which is already using `jest`.
I get `ts` duplicate type errors, because `jest` and `jasmine` have common names (`describe`, `it`,...) 
I think anyway, the `@wix/protractor-helper` package can be split into 2 packages (for `protractor` and for `jasmine`).

What do you think?

**Comment by johncant** [comment]
@hepiyellow - I've been lucky enough not to have done much frontend in the last two years, so I'm woefully behind on developments in the node/typescript ecosystem and might not be able to help you much. I don't even remember writing protractor-helpers or why I would have done something like that. Sorry I can't help much.

**Comment by hepiyellow** [comment]
OK, I'll try latest comiters (-:
@andy-ms @mhegazy
