### ISSUE TITLE
[RFC] D3 TypeScript Changelog

### ISSUE THREAD

**Issue by tomwanzek** [DefinitelyTyped/DefinitelyTyped#24999]
@gustavderdrache @Ledragon @denisname 

As you are aware we have come across a number of suggested changes to D3 related definitions, which have merit, but would constitute a breaking change. We do not have semantic versioning detached from the underlying D3 modules for obvious reasons.

It has been on my mind for a while to create a standalone repo for those who like to use D3 with TypeScript. Without getting to exuberant, it would serve two purposes:

(1) Maintain a manual `CHANGLOG.md` for the typescript definitions. Probably simply focused on breaking changes, where we think the merits out way the cost, e.g.:
* imposing a new minimum TS version, which has been in stable release for a sufficient time and the resulting new features used
* "minor" tweaks to the definitions which are technically breaking, but can be quickly fixed with fix recommendations in `previously: abc-approach, now: xyz-approach`
(2) Have a suitably scoped "How-to" wiki which does not cover the entire API, but rather fundamental questions like
* different strategies for importing D3/d3-xyz,
* fundamentals of using the generics so widely used throughout the definitions
* building block patterns

We could see, if Mike would entertain such a repo under the d3 org. Might be a fine mid-ground alternative to maintaining the definitions in D3 itself. With the latter being out of the question at this point in time.

Alternatives would be a repo outside the D3 org, or using the D3 wiki with dedicated pages.

Thoughts?

**Comment by tomwanzek** [comment]
PS. The repo approach would have the benefit, of people being able to watch it for changes to the `CHANGELOG.md`

**Comment by denisname** [comment]
For jQuery, they juste put a readme in the [type directory](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jquery). This may be the simplest way to start for the changlog. On the other hand, this has low visibility.

About the "how to us typing"... I converted several (70+) of bl.ocks.org, mostly Mike's ones, to d3 v5 in TypeScript. At first just to learn about d3 and TS, now to test my definitions changes on others people _real_ code... I had the idea to publish them one day.

**Comment by tomwanzek** [comment]
About the README, I had the same thought, regarding low visibility. I.p. since following DT does not have much of a filter. I am solely relying on being @-mentioned for that very reason...

**Comment by tomwanzek** [comment]
As to the wiki v bl.ocks.org. My thought was mainly around explaining the meaning and motivation behind certain things for beginners/converts from JS to TS.

Similar to your converted bl.ocks, I chose pre-existing standard examples to illustrate on strategy to using d3-ng2-service in d3-ng2-demo. I.e. use a familiar example  so it's easy for folks to spot the differences rather than a completely fresh start...

**Comment by Ledragon** [comment]
I have to say, I am not too fond of the idea of maintaining the types outside this repository. Though it would make management of said types easier, I fear a lack of visibility for people who want to get started, or who want to contribute or report issue.

Also, would we manage to get the types published under `@types` directly? I travelled the path NuGet>dts>typings>npm to get my types at various points in time, and having everything within npm is a very comfy place to be.

As for the How to ideas, I am totally incline to it! I already [posted my way](https://wordpress.com/stats/post/866/hstefanski.wordpress.com) of doing things and how I go about it, but having a living repo would be a bliss! I have been thinking about using [StackBlitz](https://stackblitz.com/) (which seems to be the hotness of the moment) for that purpose for a while, but  did not get up to it yet. I have never used it, so I have no idea how good of a fit it would be.

Finally, totally out of subject, [this library](https://github.com/palantir/plottable) is built using d3 and TypeScript. As it is a substantial code base, the maintainers would maybe have some insights on how to use or what they think about the current and future state of the d3 types.

**Comment by Ledragon** [comment]
My bad, I misread what you said. I honestly never realized some definitions had a readme here, which stresses the lack of visibility of these. So indeed having a separate repo that could be followed by users could be useful. But this repo should then have to be made visible ^^

**Comment by Ledragon** [comment]
I think on a short term basis we could use the README here, per definition, and go for a separate repo in a second step, together with guidelines on how to use TypeScript with d3, bundling advice, examples, etc.

**Comment by tomwanzek** [comment]
@andy-ms If we want to start using the README.md for each of the definition files to include some information akin to a CHANGELOG section going forward, what would we best do? Need to ensure we got all the requisite information which is currently auto generated, plus any additional information we want to add in. Is there anything else to be mindful of, given the publication pipeline to `npm/@types`?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
