### ISSUE TITLE
[@types/react-native] scrollToLocation missing in SectionList

### ISSUE THREAD

**Issue by yamiscott** [DefinitelyTyped/DefinitelyTyped#25025]
- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy, @huhuanming, @iRoachie, @timwangdev, @kamal, @nelyousfi, @alexdunne, @bm-software

I noticed that scrollToLocation is missing from the type definitions:

    const index = 10
    const section = 0
    const list: SectionListStatic = ref
    list.scrollToLocation({animated: true, itemIndex: index, sectionIndex: section})

Typescript linter reports:

    Error:(226, 18) TS2339: Property 'scrollToLocation' does not exist on type 'SectionListStatic<YourComponentHere>'.

**Comment by iRoachie** [comment]
Just added, should be merged in a couple hours.

**Comment by yuhj86** [comment]
Excuse me, ```scrollToLocation``` is a method ,not a property.
@iRoachie

**Comment by iRoachie** [comment]
You are right! My bad

**Comment by iRoachie** [comment]
@yuhj86 Fixed [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25505)
