### ISSUE TITLE
error TS2304: Cannot find name 'SP

### ISSUE THREAD

**Issue by hmendezm** [DefinitelyTyped/DefinitelyTyped#25033]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/Sharepoint` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

I installed  @type/sharepoint  and when I start writing code using SP see code below but when I build the project in visual studio code I get the error TS2304: Cannot find name 'SP. Do I need to do something else? Do I need to add something in the typings.d.ts file?

```
const tUrl = "";
    const tTitle = "";
    const options = {
      url: tUrl,
      title: tTitle,
      dialogReturnValueCallback: this.onPopUpCloseCallBackWithData
    };
    SP.UI.ModalDialog.showModalDialog(options);
```
best regards
hmendezm

**Comment by baywet** [comment]
could you provide your tsconfig.json please?

**Comment by Chaitra1006** [comment]
I to face the same error. Below is the copy of tsconfig.json:
{
  "compilerOptions": {
    "target": "es5",
    "forceConsistentCasingInFileNames": true,
    "module": "commonjs",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@microsoft"
    ],
    "types": [
      "es6-promise",
      "webpack-env"
    ],
    "lib": [
      "es5",
      "dom",
      "es2015.collection"
    ]
  }
}

**Comment by DanielHabenicht** [comment]
This is not an Issue with `@types/Sharepoint` as it does only provide the Typings and not the Sharepoint Context you are trying to call with `SP.UI.ModalDialog.showModalDialog(options);`. 

Maybe this issue can be closed by @baywet . 

@hmendezm look at this [Stackoverflow](https://stackoverflow.com/questions/31173738/typescript-getting-error-ts2304-cannot-find-name-require), as it might provide the solution for your problem.

**Comment by baywet** [comment]
@DanielHabenicht I don't have any rights on the repo and I can't close others' issues :)

**Comment by DanielHabenicht** [comment]
Ok, than we will have to wait for @hmendezm.

**Comment by baba43** [comment]
@hmendezm did you solve your issue because I came across this as well.

**Comment by hmendezm** [comment]
Hi Sebastian. Sorry but this was long time ago and I do not remember how I
fixed it.
