### ISSUE TITLE
expect-puppeteer:  toMatchElement() definition is wrong

### ISSUE THREAD

**Issue by tja4472** [DefinitelyTyped/DefinitelyTyped#25035]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/expect-puppeteer` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @JoshuaKGoldberg

I think the definition for toMatchElement() is wrong.

Currently:
```typescript
toMatchElement(selector: string, value: string, options?: ExpectTimingActions): Promise<void>;
```
Should be:
```typescript
toMatchElement(selector: string, options?: ExpectToClickOptions): Promise<void>; 
```

so can be used like this:
```typescript
await expect(page).toMatchElement('e2e-attribute-basic .single', { text: 'Single' });
```

At the moment it always passes the test.

**Comment by gmalicky** [comment]
Fix has been merged, issue can be closed now.
