### ISSUE TITLE
@types/storybook__addon-knobs misses definition for selectV2

### ISSUE THREAD

**Issue by panmau** [DefinitelyTyped/DefinitelyTyped#25094]
- [X] I tried using the `@types/storybook__addon-knobs` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

- Authors: @joscha @martynaskadisa 

In the [Storybook documentation](https://github.com/storybooks/storybook/tree/master/addons/knobs#selectv2) there's a type `selectV2` described but when I try to import it in my Typescript project, it isn't defined.

**Comment by joscha** [comment]
@maracuja-juice Contributions welcome :)
