### ISSUE TITLE
Webdriverio: Some, maybe all methods that have Client<T> interface return type should also have PromiseLike<T>

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [DefinitelyTyped/DefinitelyTyped#25186]
- [x] I tried using the `@types/webdriverio` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nmalaguti , @timbru31 , @fsmedberg-tc , @tanvirislam06, @phil-lgr, @lmc28

Hi All, 

Some, maybe all methods that have Client<T> interface return type should also have PromiseLike<T>

**Example**: 

[Touch command](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webdriverio/index.d.ts#L863)

```typescript
touch(selector: string, longClick: boolean): Client<T> 
```
Should become 

```typescript
touch(selector: string, longClick: boolean): Client<T> & PromiseLike<Element>
```
I'm open to doing a pull request but figured it's best to discuss it first.

Note: I'm not sure what the T is suppose to represent, is a client not just a client or is T the type of the resolved promise?...

**Comment by marthinus-engelbrecht** [comment]
Another option would be to have the `Client<T>` interface extend `PromiseLike<T>`

**Comment by vladimiry** [comment]
Would love this to be merged.
