### ISSUE TITLE
Cannot use UserAgentParser as class type from "ua-parser-js"

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DefinitelyTyped/DefinitelyTyped#25202]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/ua-parser-js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @superduper @legendecas @MeLlamoPablo>

```typescript
import UserAgentParser = require("ua-parser-js");

const parser: UserAgentParser = new UserAgentParser();
//            ~~~~~~~~~~~~~~~
```

```
Cannot find name 'UserAgentParser'.
```

**Comment by MeLlamoPablo** [comment]
This could be fixed by changing:

```diff
declare module "ua-parser-js" {
+    export class UAParser {
-    class UAParser {
        static VERSION: string;
        static BROWSER: IUAParser.BROWSER;
        static CPU: IUAParser.CPU;
        static DEVICE: IUAParser.DEVICE;
        static ENGINE: IUAParser.ENGINE;
        static OS: IUAParser.OS;

        /* ... */
    }
-   const exported: typeof UAParser & { UAParser: typeof UAParser };
-   export = exported
}
```

However it would invalidate the following import syntaxes:

```typescript
import * as UAParser from "ua-parser-js"
import UAParser = require("ua-parser-js")
```

making this one be the only one valid:

```typescript
import {UAParser} from "ua-parser-js"
```

I don't think this is a big deal at all because that's the standard ES6/TypeScript import syntax. @superduper @legendecas any thoughts?

**Comment by JoshuaKGoldberg** [comment]
Interestingly enough, it looks like the library supports both syntaxes, but only mentions the old-style `import UAParser = require("ua-parser-js")` in the README. 

https://github.com/faisalman/ua-parser-js/blob/dfb8e758d107655897761115c4b1780d0d989e3c/src/ua-parser.js#L1009

https://github.com/faisalman/ua-parser-js/blob/dfb8e758d107655897761115c4b1780d0d989e3c/src/ua-parser.js#L1040

Since [we shouldn't be importing `* as` classes](https://stackoverflow.com/questions/35706164/typescript-import-as-vs-import-require/35706271), that change sounds reasonable (if slightly inaccurate) to me.

**Comment by rimiti** [comment]
You can import without *require* like that:

```
import {NextFunction, Request, Response} from "express";
import {UAParser} from "ua-parser-js";

export default (req: Request, res: Response, next: NextFunction) => {
  req.ua = new UAParser((typeof req.headers["user-agent"] === "undefined") ? "" : req.headers["user-agent"] as (string));
  next();
};

```

**Comment by devth** [comment]
What's the solution here? I get `Cannot find name 'UAParser'` when using:

```typescript
import * as UAParser from "ua-parser-js";
```
or

```typescript
import {UAParser} from 'ua-parser-js';
```

when trying to use `UAParser` as a type, e.g.:

```typescript
type Context = {
  browserInfo: UAParser;
};

**Comment by MeLlamoPablo** [comment]
@devth the solution is to make a PR with the diff that I described earlier in this issue. I was hesitant to make it before knowing the opinion on @superduper @legendecas but since they have'n answered I guess that it's ok to proceed.

This PR means making breaking changes but as @JoshuaKGoldberg mentioned the `import * as foo from "bar"` syntax is wrong to begin with, and the `import foo = require("bar")` is old, so I don't think that this is a big deal.

Go ahead and send a PR and I'll approve it, or I'll send it myself whenever I can.

**Comment by DedaDev** [comment]
@devth

```ts
import UAParser = require("ua-parser-js");

const browserName :UAParser.IBrowser['name'] = 'Chrome'
```

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues for repos I no longer have context on. If anybody has a need for what this issue was asking about, I'd encourage them/you to file a new issue. Cheers!
