### ISSUE TITLE
Minimum typescript version for nodejs typings

### ISSUE THREAD

**Issue by Flarna** [DefinitelyTyped/DefinitelyTyped#25280]
NodeJS typings have a very long list of dependent modules. Quite a lot of them have no need for typescript newer then 2.1. Not sure if there are any modules/projects which use typescript 2.1 but use latest typings.
CI verifies that the dependency chain is clean therefore NodeJS typings have to stick on 2.1.

Is there a plan/roadmap to upgrade the minimum typescript version or is it planned to stick on 2.1 features?

@andy-ms @RyanCavanaugh What are your thoughts on this?

refs: #25279

**Comment by SimonSchick** [comment]
bump

**Comment by Flarna** [comment]
closing as min version is 2.7 now and I assume typescript team will bump this further in future.
