### ISSUE TITLE
IFilterProvider.register misses the factory argument

### ISSUE THREAD

**Issue by icorne** [DefinitelyTyped/DefinitelyTyped#25281]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/angular` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @diegovilar @thorn0 @calebstdenis @leonard-thieu 

I'm trying to use the type ng.IFilterProvider, but I'm getting an error:

$filterProvider.register('translate', () => (value) => value)
Error:(3, 3) TS2554: Expected 1 arguments, but got 2.

**Comment by thorn0** [comment]
Contributions are welcome. Could you submit a pull request?

**Comment by icorne** [comment]
Ok, I'll try, anywhere I can go for help, or to discuss things? This is new to me :)

**Comment by calebstdenis** [comment]
@icorne I've only ever submitted one PR in this particular project but I'm happy to help whatever way I can.
