### ISSUE TITLE
LineLoop is missing from three typing

### ISSUE THREAD

**Issue by Sheldan** [DefinitelyTyped/DefinitelyTyped#25294]
The class LineLoop is available in three.js, but its missing from the definitions. Source code is [here](https://github.com/mrdoob/three.js/blob/master/src/objects/LineLoop.js).

- [x] I tried using the `@types/three` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @gyohk , @florentpoujol, @omni360 , @ivoisbelongtous , @piranha771 , @qszhusightp , @nakakura , @Pro , @efokschaner ,  @dhritzkiv , @apurvaojas , @NotWoods

**Comment by Sheldan** [comment]
Found this was already mentioned in #13418.

**Comment by dhritzkiv** [comment]
That's okay - I would keep this issue open. #13418 is outdated and less actionable/specific than this.
