### ISSUE TITLE
[@types/lodash] - FP typings: _.omit typings can be improved.

### ISSUE THREAD

**Issue by Nimelrian** [DefinitelyTyped/DefinitelyTyped#25365]
- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @aj-r @Ailrun @e-cloud @thorn0 @jtmthf @DomiR

The generated types for fp.omit are currently as follows:

```ts
interface LodashOmit {
    (paths: lodash.PropertyPath): LodashOmit1x1;
    <T extends lodash.AnyKindOfDictionary>(paths: lodash.__, object: T | null | undefined): LodashOmit1x2<T>;
    <T extends lodash.AnyKindOfDictionary>(paths: lodash.PropertyPath, object: T | null | undefined): T;
    <T extends object>(paths: lodash.__, object: T | null | undefined): LodashOmit2x2<T>;
    <T extends object>(paths: lodash.PropertyPath, object: T | null | undefined): lodash.PartialObject<T>;
}
interface LodashOmit1x1 {
    <T extends lodash.AnyKindOfDictionary>(object: T | null | undefined): T;
    <T extends object>(object: T | null | undefined): lodash.PartialObject<T>;
}
type LodashOmit1x2<T> = (paths: lodash.PropertyPath) => T;
type LodashOmit2x2<T> = (paths: lodash.PropertyPath) => lodash.PartialObject<T>;
```

This typing is rather rough and can be improved. Before lodash defined the fp typings itself, I used this:

```ts
omit<T extends object, K extends keyof T>(properties: K[], object: T | null | undefined): Omit<T, K>;
omit<T extends object, K extends keyof T>(properties: K[]): (object: T | null | undefined) => Omit<T, K>;
omit<T extends object, K extends string>(properties: K[], object: T | null | undefined): PartialObject<T>;
omit<T extends object, K extends string>(properties: K[]): (object: T | null | undefined) => PartialObject<T>;
```

Where Omit is typed like this:
```ts
type Diff<T extends string, U extends string> = ({ [Prop in T]: Prop } &
	{ [Prop in U]: never } & { [x: string]: never })[T];
type Omit<T, K extends keyof T> = Pick<T, Diff<keyof T, K>>;
```

This improves the typing of the result of _.omit tremendously:
```ts
const foo = { a: 42, b: "Hello", c: { d: 1024 } };
const bar = _.omit(["a"], foo)
// bar's type is inferred as { b: string, c: { d: number } }
```

It may be possible to carry these improved typings over to the regular lodash typings.

**Comment by aj-r** [comment]
FYI, `omit` will be removed in lodash v5, so you might want to avoid using it if possible. See https://github.com/lodash/lodash/issues/2930. I'll still fix this since it doesn't look too hard, and we'll need the same fix for `unset` anyway.

**Comment by delventhalz** [comment]
Running into this same issue. Omit's use of Partial is mucking up the types that come out of it. I was surprised to find that even after updating `@types/lodash` to the latest version (`4.14.136`), I was still using a definition of omit based on Partial. 

Did some digging and discovered that while the omit type in the `common/` directory has the updated type:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/common/object.d.ts#L3076

The version of omit in the `ts3.1/` directory still uses partial:
https://github.com/DefinitelyTyped/DefinitelyTyped/blame/master/types/lodash/ts3.1/common/object.d.ts#L1896

It is unclear to me what the purpose of the ts3.1 directory is or why my TypeScript config is using it (I am using TS 3.4). Is there some guidance for how I can point TypeScript at the corrected version of omit?

**Comment by aj-r** [comment]
I think we should fix the 3.1 version to use the proper types for omit,
since that should be the most up-to-date version. PRs are welcome.

**Comment by helixbass** [comment]
I think I just ran into the same issue when using `lodash/fp`'s `pick()`, was getting a type error that appeared to be caused by the fact that `pick()` was (incorrectly?) using `Partial`

I'm using `@types/lodash@4.14.136` and `typescript@3.5.3`, is that known/expected behavior for `pick()`?

**Comment by olso** [comment]
```json
"typescript": "4.0.3",
"lodash": "^4.17.20",
"@types/lodash": "^4.14.161",
```

```ts
omit(obj, ["id"]);
// or
omit(obj "id");
```

will not check if `["id"]` or `"id"` key(s) exist on perferctly typed `obj`...

I ended up doing

```ts
function guardOmitKeys<T extends unknown, K extends (keyof T)[]>(obj: T, keys: K) {
  return keys;
}

omit(obj, guardOmitKeys(obj, ["id"]))
```
