### ISSUE TITLE
[@types/jss] Nested styles syntax is broken.

### ISSUE THREAD

**Issue by professional-human-being** [DefinitelyTyped/DefinitelyTyped#25392]
- [x] I tried using the `@types/jss` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- Authors: @appsforartists, @kof, @pelotom

```javascript
jss.createStyleSheet( {
  container: {
    padding: 20,
    '&:hover': {
      background: 'blue',
    },
    '&.clear': {
      clear: 'both',
    },
    '& .button': {
      background: 'red',
    },
    '&.selected, &.active': {
      border: '1px solid red',
    },
  },
} );
```

```
[ts] Argument of type '{ container: { padding: number; '&:hover': { background: string; }; '&.clear': { clear: string; }; '& .button': { background: string; }; '&.selected, &.active': { border: string; }; }; }' is not assignable to parameter of type 'Partial<Record<"container", Style>>'.
  Types of property 'container' are incompatible.
    Type '{ padding: number; '&:hover': { background: string; }; '&.clear': { clear: string; }; '& .button': { background: string; }; '&.selected, &.active': { border: string; }; }' is not assignable to type 'SimpleStyle | Observable<PropertiesHyphen<Length>> | undefined'.
      Object literal may only specify known properties, and ''&:hover'' does not exist in type 'SimpleStyle | Observable<PropertiesHyphen<Length>> | undefined'.
```

Also, type-based suggestions is broken too.

**Comment by Robula** [comment]
Similar issue here:

```
const css = {
  foo: {
    flexDirection: 'row'
  }
}
jss.createStyleSheet(css)
```
```
error TS2345: Argument of type '{ foo: { flexDirection: string; }; }' is not assignable to parameter of type 'Partial<Record<"foo", Style>>'.
  Types of property 'foo' are incompatible.
    Type '{ flexDirection: string; }' is not assignable to type 'Style'.
      Type '{ flexDirection: string; }' is not assignable to type 'Observable<PropertiesHyphen<string | number>>'.
        Property 'subscribe' is missing in type '{ flexDirection: string; }'.
```

**Comment by orangecoloured** [comment]
I'm currently having the same issue with flexDirection, position and pointerEvents.
Any way to solve this?

'pointer-events' works though.
Tried this stupid trick with 'position' and no luck.

**Comment by appsforartists** [comment]
It looks like this might work for the OP's issue:

```ts
export type Style = SimpleStyle | Observable<csstype.PropertiesHyphen<Length>>;
export type FlatStyles<Name extends string = any> = Record<Name, Style>;
export type Styles<Name extends string = any> = Record<Name, Style|FlatStyles>;
```

I just pasted everything into the playground to experiment with it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by danielstern** [comment]
12/1/2022 Ran into this issue
