### ISSUE TITLE
Namespace '"meteor/mongo".Mongo' has no exported member 'ObjectID'

### ISSUE THREAD

**Issue by ymchun** [DefinitelyTyped/DefinitelyTyped#25395]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- Authors: @barbatus @fullflavedave @orefalo

when upgraded `@types/meteor` to `1.4.15`
the following message will show during compile
`Namespace '"meteor/mongo".Mongo' has no exported member 'ObjectID'`

Example of my code:
```
import { Mongo } from 'meteor/mongo';

public someFunc(id: Mongo.ObjectID): any {
  // ...
}
```

**Comment by ymchun** [comment]
tried with meteor@1.6.1 & 1.6.1.1

**Comment by jschmold** [comment]
How did you solve this? I have this issue as well and am unable to make heads or tails of it.
