### ISSUE TITLE
Problem with react-copy-to-clipboard 

### ISSUE THREAD

**Issue by vaske** [DefinitelyTyped/DefinitelyTyped#25414]
I tried using the `@types/react-copy-to-clipboard` package and had problems.
JSX element type 'CopyToClipboard' does not have any construct or call signatures.

I imported it as 
```
import * as CopyToClipboard from 'react-copy-to-clipboard';
```

and then use as 

```
                <CopyToClipboard
                    // type='text'
                    text={ this.state.value ? this.state.value : '' }
                    onCopy={ () => this.setState({copied: true}) }
                >
                    <span>test</span>
                </CopyToClipboard>
```

What we should do to avoid such issue?

Authors: @mabels and @BernabeFelix

**Comment by Bernabe-Felix** [comment]
@vaske have you imported CopyToClioboard as `improt CopyToClipboard from 'react-copy-to-clipboard'`?

**Comment by vaske** [comment]
@Bernabe-Felix with that I'm getting error as well, like there is no export name like that, etc...

**Comment by BernabeFelix** [comment]
got it, could you please paste you code implementation to have more context

**Comment by vaske** [comment]
Well nothing specific, just import and then in render I call CopyToClipboard as I mentioned in main comment.

**Comment by BernabeFelix** [comment]
Yes, without any problem

**Comment by mal-sokol** [comment]
I have the same exact situation!
I import it as 

`import * as CopyToClipboard from "react-copy-to-clipboard";`

and I got Typescript error 

`JSX element type 'CopyToClipboard' does not have any construct or call signatures.`

**Comment by TejasQ** [comment]
I'd +1 this and add that the type definitions do not account for the fact that this library exports a _named_ version of itself alongside a default export. As in, both 

a) `import { CopyToClipboard } from "react-copy-to-clipboard"` _and_,
b) `import CopyToClipboard from "react-copy-to-clipboard"` 

should be valid.

In essence, this should not error:
![Image](https://user-images.githubusercontent.com/9947422/45521473-4f0e5580-b77b-11e8-8db6-5356dad205f5.png)

More info here:
https://github.com/nkbt/react-copy-to-clipboard/pull/97

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by notShadowM** [comment]
I just faced a problem with @vaske code that the component doesn't accept children  so  all it needs is to add in children: ReactNoe in the interface

here is my code:

`
declare module "react-copy-to-clipboard" {
  import React from "react";

  interface Options {
      debug: boolean;
      message: string;
  }

  interface Props {
      text: string;
      onCopy?(a: string, b: boolean): void;
      options?: Options;
      children?: ReactNode
  }

  class CopyToClipboard extends React.Component<Props, {}> {}
  export default CopyToClipboard;
}
`

**Comment by vaske** [comment]
@notShadowM yeah I think that is only for React 18
