### ISSUE TITLE
Feature: React.createRef accepting interface

### ISSUE THREAD

**Issue by jake-daniels** [DefinitelyTyped/DefinitelyTyped#25468]
Hi, I would like to use new `createRef` function with interface (not a class type) as generic argument.
Now it works like this:

```
class Foo extends React.Component {
   getBar = (): number => {
      return 6
   }
   ...
   render () {
      ...
   }
}

class Baz extends React.Component {
   foo = React.createRef<Foo>()
   ...
   render () {
      return (
         <Foo ref={this.foo} />
      )
   }
}
```
It's super nice, but when I'm in a `Baz` class and use `this.foo.current`, I have access to all lifecycle methods, props, state, context and so on.
I would like to create an interface for the `Foo` class and use it like this:
```
interface IFoo {
   getBar: () => number,
}

class Foo extends React.Component implements IFoo {...}

class Baz extends React.Component {
   foo = React.createRef<IFoo>()
}
```
...and `getBar` would be the only property accessible in `this.foo.current`.
Do you think it would be possible?

Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa

**Comment by ferdaber** [comment]
Technically you do have access to all public methods of the component class instance, if you want to limit it to just the interface you can cast it when passing it into `ref`:
```tsx
class Baz extends React.Component {
  foo = React.createRef<IFoo>()
  
  render() {
    return <Foo ref={this.foo as React.RefObject<Foo>} />
  }
}
```

This will work for as long as `Foo` is assignable to `IFoo`, which is what you wanted.

**Comment by jake-daniels** [comment]
@ferdaber Thanks, this is exactly what I wanted.

**Comment by TedDriggs** [comment]
@ferdaber out of curiosity, why doesn't this work today? I'm guessing that we lose the knowledge somewhere that `<Foo />` is an `IFoo`.

**Comment by ferdaber** [comment]
The way I think about it is that a class only implements an interface, it doesn't "become" the interface. With polymorphism, you can cast that an instance of a class that implements an interface as just that interface, but it can also be cast as the class itself. 

If you were to do something like this:
```ts
interface IFoo {
  foo(): void
}
interface IBar {
  bar(): void
}

class FooBar implements IFoo, IBar {}

const fooBar = new FooBar() // can be cast to FooBar, IFoo, and IBar
```

`fooBar`'s proper, or "default" type is `FooBar`, but it can be cast to any of the three since it implements two interfaces. Does that make sense?

**Comment by ferdaber** [comment]
I also just realized you might've been asking why I had to cast it in the prop itself. I believe with props, they are compared bivariantly. I'm not knowledgeable at all in type theory so I'm just going to leave you with this link: https://www.stephanboyer.com/post/132/what-are-covariance-and-contravariance https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html
