### ISSUE TITLE
@types/superagent's package.json has some error

### ISSUE THREAD

**Issue by muzea** [DefinitelyTyped/DefinitelyTyped#25498]
- [X] I tried using the `@types/superagent` package and had problems.
- [X] I tried using the tsc@2.8.1.
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

The package.json is 
```json
{
    "name": "@types/superagent",
    "version": "3.5.8",
    "description": "TypeScript definitions for SuperAgent",
    "license": "MIT",
    "contributors": [
        {
            "name": "Nico Zelaya",
            "url": "https://github.com/NicoZelaya",
            "githubUsername": "NicoZelaya"
        },
        {
            "name": "Michael Ledin",
            "url": "https://github.com/mxl",
            "githubUsername": "mxl"
        },
        {
            "name": "Pap Lőrinc",
            "url": "https://github.com/paplorinc",
            "githubUsername": "paplorinc"
        },
        {
            "name": "Shrey Jain",
            "url": "https://github.com/shreyjain1994",
            "githubUsername": "shreyjain1994"
        }
    ],
    "main": "",
    "repository": {
        "type": "git",
        "url": "https://www.github.com/DefinitelyTyped/DefinitelyTyped.git"
    },
    "scripts": {},
    "dependencies": {
        "@types/node": "*"
    },
    "typesPublisherContentHash": "5d8b5ee5ed6f3a6c822e9da99cea48d4f596a689e1bacb9f49769aff95328733",
    "typeScriptVersion": "2.2"
}
```

Now (2018-05-03), `"@types/node": "*"` will be resolved to `@types/node@10.0.3`, will receive an error when compiling, like
```bash
node_modules/@types/core-js/index.d.ts(504,5): error TS2687: All declarations of 'iterator' must have identical modifiers.
node_modules/@types/node/index.d.ts(83,14): error TS2687: All declarations of 'iterator' must have identical modifiers.
```
But if we explicitly specify an earlier version, eg `@types/node@7.0.7`, tsc will no longer report error.
I think we should add a package.json to explicitly specify the version of `@types/node`.

Related issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15104
Demo code: https://github.com/muzea/compile-demo

@GintasG

**Comment by muzea** [comment]
@NicoZelaya @mxl @paplorinc @shreyjain1994 
Sorry for bothering, can someone handle this problem?

**Comment by shreyjain1994** [comment]
I don't know if its possible to explicitly specify a particular version of `@types/node` since the package.json for `@types/superagent` (and for all other typescript definitions) is generated automatically when it is published (which is again done automatically).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
