### ISSUE TITLE
React-Bootstrap NavDropdown missing "title" prop.

### ISSUE THREAD

**Issue by JRPMike** [DefinitelyTyped/DefinitelyTyped#25490]
Cannot use an icon for NavDropDown "title" instead of text because the NavDropdown.d.ts file does not override title (in the "Standard HTML Attributes" in the React index.d.ts). I added "title?: any;" to the NavDropdownBaseProps and got the result that I desired but I do not know if that is the correct solution.

types/react-bootstrap:0.32.9

```
import * as React from 'react';
import { DropdownBaseProps } from './Dropdown';

declare namespace NavDropdown {
  export interface NavDropdownBaseProps extends DropdownBaseProps {
    active?: boolean;
    noCaret?: boolean;
    eventKey?: any;
    title?: any;
  }

  export type NavDropdownProps = NavDropdownBaseProps & React.HTMLProps<NavDropdown>;
}
declare class NavDropdown extends React.Component<NavDropdown.NavDropdownProps> { }
export = NavDropdown;
```

Authors: @vsiao @danilobjr  @Batbold-Gansukh @octatone @chengsieuly @mretolaza @katbusch @vitosamson @LKay @aaronbeall @jrakotoharisoa

**Comment by aaronbeall** [comment]
Good catch, we've fixed this other places using `Omit<HTMLProps, "title">` and set `title` to `ReactNode`, for [example in `DropdownButton`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-bootstrap/lib/DropdownButton.d.ts).

I'd accept a passing PR with this:

```
declare namespace NavDropdown {
    export interface NavDropdownBaseProps extends DropdownBaseProps {
        active?: boolean;
        noCaret?: boolean;
        eventKey?: any;
        title?: React.ReactNode;
    }

    export type NavDropdownProps = NavDropdownBaseProps & Omit<React.HTMLProps<NavDropdown>, "title">;
}
declare class NavDropdown extends React.Component<NavDropdown.NavDropdownProps> { }
```

It would be great if someone could audit all the components to solve this issue everywhere, I think I've seen 3 or 4 PRs fixing this issue in different components.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
