### ISSUE TITLE
recompose, withStateHandlers: indexer "leaks" onto inner component

### ISSUE THREAD

**Issue by city41** [DefinitelyTyped/DefinitelyTyped#25536]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/recompose` package and had problems.
- Authors: @iskandersierra @mrapogee @clayne11 @Pajn @lucasterra 

When using `withStateHandlers`, I am finding that my inner component must define an indexer on its props. I have detailed the issue [on stackoverflow](https://stackoverflow.com/questions/50162759/recompose-withstatehandlers-and-typescript-implementation-type-leaks-to-compone)

Example:

Define an SFC:

```
interface IProps {
    className?: string;
    isEditing: boolean;
    toggleEditing: () => void;
}

const MyComponent: React.SFC<IProps> = ({ className, isEditing, toggleEditing }) => (
    <button className={className} onClick={toggleEditing}>{isEditing ? 'stop editing' : 'start editing'}</button>
);

export default MyComponent;
```

Then, create a stateful version of it using `withStateHandlers`

```
import { withStateHandlers, StateHandlerMap, StateHandler } from 'recompose';
import MyComponent from '../components/myComponent';
interface IProps {
    className?: string;
}

interface IToggleEditingState {
    isEditing: boolean;
}

interface IToggleEditingStateUpdaters extends StateHandlerMap<IToggleEditingState> {
    toggleEditing: StateHandler<IToggleEditingState>
}

const withToggleEditState = withStateHandlers<IToggleEditingState, IToggleEditingStateUpdaters, IProps> (
    { isEditing: false },
    {
        toggleEditing: (state) => () => ({ isEditing: !state.isEditing })
    }
);

const StatefulMyComponent = withToggleEditState(MyComponent);
```

The compiler will raise two issues:

1. on the SFC, `toggleEditing`'s type is incorrect, it needs to be `(...payload: any[]) => object`
2. the SFC needs to have an indexer, ie: `[key: string]: any`

So to get things to compile, `IProps` on the SFC needs to become:

```
interface IProps {
    className?: string;
    isEditing: boolean;
    toggleEditing: (...payload: any[]) => object;
    [key: string]: any;
}
```

For (1), I do see that the recompose docs say that is the signature. I think it'd be nice if we could get a more strongly typed signature. But that is more a feature request.

For (2), I feel needing that indexer is a bug.

**Comment by city41** [comment]
I'd be happy to attempt my own PR to fix this. But I am very new to TypeScript, so thought starting with an issue first would be better.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
