### ISSUE TITLE
Select2 jQuery v1 and 2 compatibility

### ISSUE THREAD

**Issue by denisname** [DefinitelyTyped/DefinitelyTyped#25548]
The last Select2 type definition use some jQuery interfaces and types that are actually only part of the jQuery v3 type definition. Let's see how we can make it work with any versions.

In the `on` functions, `JQuery.EventHandlerBase<T, S>` can be replaced by `(this: T, eventObject: S)`.

For `JQuery.PlainObject`, it's a trivial interface, so we may just add our own one in select2 types.

After a quick check, the `JQuery.Event` and `JQuery.Event<.>` can most probably be replaced by `BaseJQueryEventObject`. I need to verify this a little deeper.

For `JQuery.Ajax.AjaxSettingsBase` we can _not_ replace it by `JQueryAjaxSettings`. As it will force to have `url: string`. We may however simply add a `JQueryAjaxSettingsBase` to jQuery v1 and v2 type definition like it has been done for v3. @leonard-thieu any thoughts, can we make such small change?

Worst case we can go for an ugly `url: any`, waiting for better solutions...

**Comment by leonard-thieu** [comment]
> In the on functions, JQuery.EventHandlerBase<T, S> can be replaced by (this: T, eventObject: S).

> For JQuery.PlainObject, it's a trivial interface, so we may just add our own one in select2 types.

These sound reasonable.

> After a quick check, the JQuery.Event and JQuery.Event<.> can most probably be replaced by BaseJQueryEventObject.

They're not compatible unfortunately. I believe you'll need to define handlers for each.

> For JQuery.Ajax.AjaxSettingsBase we can not replace it by JQueryAjaxSettings. As it will force to have url: string. We may however simply add a JQueryAjaxSettingsBase to jQuery v1 and v2 type definition like it has been done for v3.

I think it's best to avoid making changes to the v1 and v2 declarations. Stability in those declarations is very important. I believe TypeScript has a way to grab all properties _except_ specific ones? In which case, you should be able to exclude the existing `url` property and re-declare it.

**Comment by denisname** [comment]
@leonard-thieu Thank you for your quick reply.
