### ISSUE TITLE
Angular Material/Angular type mismatch

### ISSUE THREAD

**Issue by gpit2286** [DefinitelyTyped/DefinitelyTyped#25589]
If you know how to fix the issue, make a pull request instead.

- [ x ] I tried using the `@types/angular` and `@types/angular-material` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
    - @blbigelow 
    - @diegovilar

If you do not mention the authors the issue will be ignored.

Recently updated Typescript to 2.8.3 and it seems to be more strict about namespaces/modules.  

In @types/angular, there is a namespace exported. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0c23284637983455f4aff76ae58c54b11b1a9974/types/angular/index.d.ts#L32
In @types/angular-material, there is a module declared. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0c23284637983455f4aff76ae58c54b11b1a9974/types/angular-material/index.d.ts#L12 

Typescript it favoring the namespace export over the module export.  I can remove the namespace export in @types/angular and everything works fine.  https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0c23284637983455f4aff76ae58c54b11b1a9974/types/angular/index.d.ts#L21 

Advice on the best way to fix this?

**Comment by CharlesBean** [comment]
The issue above seems to be related to breaking changes in the Typescript compiler. I've submitted a PR to solve the above issue by mimicking the approach [@types/ui-router](https://github.com/CharlesBean/DefinitelyTyped/tree/master/types/angular-ui-router) took when adding namespaces to the angular type package (dependency)

Notes:

1. PR does not modify the namespaces nor removal of angular-material "extending" the angular namespace
2. PR removed export assignment

Hopefully this PR will be accepted, as it shouldn't introduce any breaking changes and fixes the above issue by allowing the following (in the same manner ui-router does):

`
import { IScope } from 'angular';
import { IBottomSheetOptions } from 'angular-material';
import { IState } from 'angular-ui-router';

// import functions properly, while previous namespaces references for earlier TS versions also works
`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
