### ISSUE TITLE
@types/glue - Should compose type def return a Promise?

### ISSUE THREAD

**Issue by sundeer** [DefinitelyTyped/DefinitelyTyped#25604]
@garfty 
According to the [Glue Docs](https://github.com/hapijs/glue/blob/master/API.md#usage),  Glue.compose(manifest) returns a promise that resolves to the server object but the type def here looks like this:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/106d393592fe348ea3da2ef1fc1faa1317e045b5/types/glue/index.d.ts#L31

shouldn't it be:
```ts
export function compose(manifest: Manifest, options?: Options): Promise<Server>;
```

set me straight if I wrong as I am new to TS and statically typed languages in general.

**Comment by garfty** [comment]
Yes, you are correct. Apologies for this, I'd actually fixed it locally but not copied the code over to Definitely Typed. This should be fixed in the latest update.

Let me know if you have any other problems. ^_^
