### ISSUE TITLE
@types/hapi - how to type payload, pre, etc?

### ISSUE THREAD

**Issue by samhh** [DefinitelyTyped/DefinitelyTyped#25605]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [*] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @BorntraegerMarc @rafaelsouzaf @jhsimms @SimonSchick 

*: I've posted a question [here](https://stackoverflow.com/questions/50231386/hapi-w-typescript-w-o-type-assertion), though I'm unsure if it's a limitation of the typings or my implementation (presumably the latter).

---

```typescript
server.route({
  method: 'POST',
  path: '/example',
  options: {
    pre: [{
      assign: 'example',
      method: (req) => {
        return { msg: `Mr. ${req.payload.name} Example` };
      },
    }],
  },
  handler: (req) => {
    return {
      success: true,
      info: req.pre.example.msg,
    };
  },
});
```

How do I correctly type `req.payload` and `req.pre`? I can force the former with type assertion but not the latter.

Thanks!

**Comment by mmiszy** [comment]
What do you think about making `RequestQuery`, `Request['payload']`, `Hapi.Lifecycle.Method` etc. generic so that you could provide (optional) types on per-route basis?

What I have in mind is instead of ugly casting:

```typescript
type MyQueryType = {
  a: number,
  b: boolean,
};

export const somethingHandler: Hapi.Lifecycle.Method = async (request, h) => {
  const query = request.query as MyQueryType; // :-(
}
```

We could have:
```typescript
type MyQueryType = {
  a: number,
  b: boolean,
};

export const somethingHandler: Hapi.Lifecycle.Method<MyQueryType> = async (request, h) => {
  // now `request.query` is MyQueryType // :-))
}
```

and similarly for `payload`?

**Comment by SimonSchick** [comment]
As already mentioned, making these generic is rather questionable, it doesn't really have any benefits over casting.

**Comment by SimonSchick** [comment]
Again, we are extremely quickly going down the generic hell if we did that, what is the issue with casting here?

**Comment by mmiszy** [comment]
Casting quickly becomes a bit tedious:

```ts
server.route({
  method: 'GET',
  path: '/users/{userId}',
  options: {
    validate: {
      params: {
        userId: Joi.number().required(),
      }
    }
  },
  handler: (request: Hapi.Request) : AddResult => {
    const { userId } = request.params as unknown as { userId: number };
    return null;
  }
});
```

Making it generic was now also suggested here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25229

**Comment by SimonSchick** [comment]
I'm not really a fan of making it a generic tbh, you're just moving the type assertion elsewhere.
Granted you wouldn't need the `unknown` type assertion first but we would quickly dig ourselves into a hole if we want to apply this to `payload`, `headers`, `params`, `state` etc. since all of these may be mutated by `joi` validations.

Maybe making the property value default to `unknown` would work but that'd be a nasty breaking change for everyone who is currently using hapi.

**Comment by sqren** [comment]
Crazy idea: Would it be possible to infer the type of `req.query` and `req.params` via the validation options?

**Comment by mmiszy** [comment]
@sqren it would, but it's highly experimental and unofficial: https://github.com/TCMiranda/joi-extract-type

**Comment by SimonSchick** [comment]
@sqren I tried this before but the resulting generics were an ungodly unreadable mess, I think we are better off this way, for now anyways.

**Comment by sqren** [comment]
I'm going to re-open this discussion again :)

I think we are missing out on a big opportunity of letting users create solid contracts between their client (frontend) and server (backend) applications. 
One way of letting users do this is by allowing them to specify the query params via a generic argument to `Request`.  

Imagine this backend route:
```ts
// Define query params once. This can now be re-used in both frontend and backend
interface Query {
    transactionType: string;
    transactionName: string;
}

export const chartRoute = {
  method: 'GET',
  path: '/charts',
  handler: (req: Request<Query>) => {
    const { transactionType, transactionName } = req.query; // automatically typed as { transactionType: string, transactionName:string }
    return 'Hello World!';
  }
};

server.route(chartRoute);
```

Then on the client (frontend) the query params I supply to `restClient` will be type checked:
```ts
import { chartRoute } from '/server/routes/chart';

// We can infer the query params supplied to the route handler on the server. This inference happens inside restClient
type ChartRouteHandler = typeof chartRoute['handler']
const res = await restClient<>({
  pathname: `/charts`,
  query: {
    transactionName: 'i am a string' // ✅ This is defined as a string on the backend
    transactionType: 1337 // ❌This is also defined as a string on the backend but a number is given
  }
});
```

By supplying a `Query` param as a generic argument to `Request` on the server, and by doing a bit of inference in `restClient` we can ensure that the server and client stays synced. So if `transactionName` is removed from the server, it will no longer be valid to supply on the client either.

In the above case `restClient` also returns the correct type for the response (inferred from `ReturnType<chartRoute['handler']>`).
We can even go further than this and type check other properties, like `method` to make sure they are also aligned between client and server.

I think this is a really interesting avenue of type checking across application boundaries that is currently not well supported.
If you have other ways of solving this I'm very interested to hear them.

**Comment by mmiszy** [comment]
You might want to take a look at [typesafe-hapi](https://github.com/mmiszy/typesafe-hapi#readme) that I'm working on. It uses [typesafe-joi](https://github.com/hjkcai/typesafe-joi).

**Comment by kishor82** [comment]
@sqren  i am getting `Type 'Request' is not generic.` when i pass generic argumanet.

**Comment by sqren** [comment]
@kishor82 My examples don't work. They are merely suggestions for how I think it could work.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
