### ISSUE TITLE
[@types/react-router] Duplicate identifier 'NavLink'.

### ISSUE THREAD

**Issue by wildcart** [DefinitelyTyped/DefinitelyTyped#25688]
@tkrotoff, @huy-nguyen, @p-jackson VS Code complains about duplicate `NavLink` exported from `@types/react-router-dom/index.ts` (version 4.2.6):
```
...
45: export interface LinkProps extends React.AnchorHTMLAttributes<HTMLAnchorElement> { ... }
50: export class NavLink extends React.Component<LinkProps, any> {}

52: export interface NavLinkProps extends LinkProps { ... }
60: export class NavLink extends React.Component<NavLinkProps, any> {}
```

I guess the fix would the patch below but I am not sure:
```
@50
- export class NavLink extends React.Component<LinkProps, any> {}
+ export class Link extends React.Component<LinkProps, any> {}
```

After applying the patch, VS Code's Intellisense is able to propose meaningful completions on `<Link>`. Without, it doesn't show anything useful.

**Comment by huy-nguyen** [comment]
Can you provide an example (best if the example is part of the test file in `react-router`'s directory) with the error message?

**Comment by wildcart** [comment]
sorry for the false positive: I switch from `Link` to `NavLink` and hit 'rename symbol' on the import which changed the typings (only wanted to change it locally in the file :( ).

After reinstalling it back to 'normal'.

Sorry for the noise.
