### ISSUE TITLE
lodash.flowRight loses generic type

### ISSUE THREAD

**Issue by evollu** [DefinitelyTyped/DefinitelyTyped#25694]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andy-ms

### Problem
I'm using lodash's flowRight to compose react's higher order component. However after flowRight, type definition is lost, becoming simply `{}`
This issue only happens if I define a generic type in HOC. [Here is an example showing the issue](https://www.typescriptlang.org/play/#src=type%20X%20%3D%20%7B%0D%0A%20%20%20%20x%3A%20string%2C%0D%0A%20%20%20%20y%3A%20string%0D%0A%7D%0D%0A%0D%0Afunction%20A%3CP%3E(x%3A%20P)%20%7B%0D%0A%20%20%20%20return%20x%0D%0A%7D%0D%0A%0D%0Afunction%20B%3CP%3E(y%3A%20P)%20%7B%0D%0A%20%20%20%20return%20y%0D%0A%7D%0D%0A%0D%0Afunction%20flowRight%3CA1%2C%20R2%2C%20R1%3E(f2%3A%20(a%3A%20R1)%20%3D%3E%20R2%2C%20f1%3A%20(a1%3A%20A1)%20%3D%3E%20R1)%3A%20(a1%3A%20A1)%20%3D%3E%20R2%20%0D%0A%7B%0D%0A%0D%0A%7D%0D%0A%0D%0Avar%20data%3A%20X%20%3D%20%7B%0D%0A%20%20%20%20x%3A%20%221%22%2C%0D%0A%20%20%20%20y%3A%20%222%22%0D%0A%7D%0D%0A%0D%0Alet%20y%20%3D%20B(A(data))%0D%0A%0D%0Alet%20z%20%3D%20flowRight(A%2CB)(data)). you see `y` has type `X` while `z` is only {}

Can anyone help?

**Comment by evollu** [comment]
seems to be caused by https://github.com/Microsoft/TypeScript/issues/9366

**Comment by b4stien** [comment]
The issue you mention is resolved (and the PR associated is merged) but we still have the same problem, have you find a fix @evollu ?
