### ISSUE TITLE
selenium-webdriver is missing .headless() for firefox.Options

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DefinitelyTyped/DefinitelyTyped#25712]
- [x] I tried using the `@types/selenium-webdriver` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @BillArmstrong, @Kuniwak, @cnishina, @SupernaviX, @bendxn>

As per https://developer.mozilla.org/en-US/Firefox/Headless_mode#Automated_testing_with_headless_mode, there is a `.headless()` method on `firefox.Options`. 

```javascript
var firefoxOptions = new firefox.Options();
firefoxOptions.setBinary('/path/to/binary');
firefoxOptions.headless();
```

I've verified it exists and works as expected locally; however, the types package doesn't include it.

**Comment by thedanielgray** [comment]
Should this issue be closed now that it's merged?
