### ISSUE TITLE
@types/reactstrap misses CustomInput interface

### ISSUE THREAD

**Issue by Fakkio** [DefinitelyTyped/DefinitelyTyped#25727]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/reactstrap` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alihammad @mfal @danilobjr @FaithForHumans @KurtPreston @timc13 @patrickrgaffney 

Hi,
i'm using reactstrap@6.0.1 and @types/reactstrap@5.0.25 and i've seen that it misses the interface for CustomInput. See http://reactstrap.github.io/components/form/ at the end of the page.

Thanks

**Comment by FaithForHumans** [comment]
Addressed in PR #25714
