### ISSUE TITLE
Rc-tree types are not up to date

### ISSUE THREAD

**Issue by Channa53** [DefinitelyTyped/DefinitelyTyped#25738]
@johnnyreilly @Methuselah96 
I'm trying to use rc-tree type, and specifically to use TreeNode with Icon property and I get an error that icon does not exist on this type. 
Here is my issue in rc-tree repo - https://github.com/react-component/tree/issues/161

Regards,
Channa

**Comment by johnnyreilly** [comment]
Sure - submit a PR?
