### ISSUE TITLE
[@types/lodash] Wrong return type for `_.get`

### ISSUE THREAD

**Issue by th0r** [DefinitelyTyped/DefinitelyTyped#25759]
Here is a code snippet:
```ts
import _ from 'lodash';

interface Item {
  bool: boolean;
}

interface Items {
  [name: string]: Item;
}

const items: Items = {
  foo: {bool: true},
  bar: {bool: false}
};

const fooBool: boolean = _.get(items, 'foo.bool');
```

Last line produces the following error:
```
Type 'Item' is not assignable to type 'boolean'
```

Seems like lodash types treats `path` parameter here as a simple property name but it's a property path.

P.S. error can be fixed by using `['foo', 'bool']` instead of `'foo.bool'`.

Versions:
- Tested with `typescript@2.7.2 / @2.8.3`
- `@types/lodash@4.14.108`

Mentions: @bczengel @chrootsu @stepancar @aj-r @Ailrun @e-cloud @thorn0 @jtmthf @DomiR

**Comment by aj-r** [comment]
There's not much we can do about this, unfortunately. We could try returning `any` for all dictionary (string-indexed) types. Hopefully that won't have bad effects on non-indexed objects.

**Comment by th0r** [comment]
Ok, agree. Thanks!
