### ISSUE TITLE
@types/react-redux Allow Selector without OwnProps

### ISSUE THREAD

**Issue by VincentLanglet** [DefinitelyTyped/DefinitelyTyped#25804]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-redux` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @thasner @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo @pdeva @Kallikrein @jrakotoharisoa 

I use a lot of selector without the need of ownProps

```
interface AppState {
    auth: { email: string, password: string }
}

const selectEmail: Selector<AppState, string, undefined> = (state) => state.auth.email;
const selectPassword: Selector<AppState, string, { id: string }> = (state, ownProps) => ownProps.id + state.auth.password

const state = { auth: { email: 'email', password: 'password' } };
const email = selectEmail(state, undefined);
```

I expect to write something like

```
const selectEmail: Selector<AppState, string> = (state) => state.auth.email;
const email = selectEmail(state);
```

Without breaking the type for 
```
const selectPassword: Selector<AppState, string, { id: string }> = (state, ownProps) => ownProps.id + state.auth.password
```

But I didn't found how to do it, or how to rewrite the existing type.

**Comment by VincentLanglet** [comment]
@alloy I don't know who to ask, I tag you cause you merged some of my PR, I was hoping you could help me / redirect me.

I'll be happy to make a PR to improve the selector type of `@types/react-redux`.

I want to write something like
```
export interface Selector<S, TProps> {
    (state: S): TProps
}
export interface Selector<S, TProps, TOwnProps> {
    (state: S, ownProps: TOwnProps): TProps
}
```

**Comment by alloy** [comment]
Alas, I lack all context on this to being able to help you well, I don't even use Redux. Perhaps it could help by writing some failing tests first of what you'd like to be able to do, PR that as a Work In Progress PR and ask the maintainers to look at that.

**Comment by VincentLanglet** [comment]
Ok, done
