### ISSUE TITLE
@types/ramda - Typings for composeP and pipeP missing

### ISSUE THREAD

**Issue by andys8** [DefinitelyTyped/DefinitelyTyped#25801]
- [x] I tried using the `@types/ramda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- Authors: @donnut @mdekrey @mrdziuban @sbking @afharo @teves-castro @1m0rebug @hojberg @charlespwd @samsonkeung @angeloocana @raynerd @googol @moshensky @ethanresnick @leighman @CaptJakk

Source: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/index.d.ts#L395

The typings for `pipeP` and `composeP` are missing.
http://ramdajs.com/docs/#composeP
http://ramdajs.com/docs/#pipeP

The `P` prefixed versions exist for composition of functions that return a `Promise`.
```
pipe :: (((a, b, …, n) → o), (o → p), …, (x → y), (y → z)) → ((a, b, …, n) → z)
pipeP :: ((a → Promise b), (b → Promise c), …, (y → Promise z)) → (a → Promise z)
```

**Comment by tommireinikainen** [comment]
I'm also missing typings for pipeP. Looks like there's another set of typings for ramda (https://github.com/types/npm-ramda) that includes `pipeP` and `composeP` but I'd much rather use the DefinitelyTyped types.

There's an existing thread/PR on syncing the npm-ramda types with DT but unfortunately looks like it didn't go anywhere: DefinitelyTyped/DefinitelyTyped#15912

**Comment by CaptJakk** [comment]
The earliest I can get to this is next week. Is there anyone else who can take a look into it before then?

**Comment by andys8** [comment]
@CaptJakk Would be awesome if you have a look.

**Comment by googol** [comment]
Added a PR for these
