### ISSUE TITLE
react-native-auth0 refresh tokens missing

### ISSUE THREAD

**Issue by ksbeking** [DefinitelyTyped/DefinitelyTyped#25823]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ascariandrea 

If you do not mention the authors the issue will be ignored.

For the react-native-auth0 typing:
Under the password realm, the login and signup functions return refresh tokens that are not typed.
The PasswordRealmResponse type should contain refresh tokens.

**Comment by ascariandrea** [comment]
Hi @ksbeking 
Unfortunately the `react-native-auth0` documentation is poor, so I would need you to share the output of `passwordRealm` method. Can you?

**Comment by ksbeking** [comment]
That is the documentation for it: https://auth0.com/docs/api-auth/grant/password.

Also, 
![screen shot 2018-05-18 at 15 43 27](https://user-images.githubusercontent.com/9087625/40237986-3dfd10a4-5ab2-11e8-892f-9de54b915b0b.png)

**Comment by ascariandrea** [comment]
@ksbeking I opened a PR that should fix your problem

**Comment by ksbeking** [comment]
Thank you so much
