### ISSUE TITLE
[@types/lodash] undefined incorrectly part of explicitly chained `_.get`

### ISSUE THREAD

**Issue by NicBright** [DefinitelyTyped/DefinitelyTyped#25834]
- [x] If you know how to fix the issue, make a pull request instead.
I'd prefer to talk about this first. I can provide a PR afterwards if you like me to do so.

- [x] I tried using the `@types/lodash` package and had problems.

## `_.get()` in an explicit chain ...
... unnecessarily adds `undefined` to the return type. Example:

```typescript
interface Car {
    engine: Engine;
}
  
interface Engine {
    name?: string;
    horsepowers: number;
}

const car: Car = {} as Car; // dummy
const name = _.chain(car)
   .get('engine').get('name').value(); // string | undefined <-- OK because "name" is optional
const horsepowers = _.chain(car)
    .get('engine')
    .get('horsepowers').value(); // number | undefined <-- NOK because horsepowers is NOT optional
```

The type definition that's used by TS is this (let's name it `#1` as i'll refer back to it later):
```typescript
        /**
         * @see _.get
         */
        get<TObject extends object, TKey extends keyof TObject>(
            this: LoDashExplicitWrapper<TObject | null | undefined>,
            path: TKey | [TKey],
        ): LoDashExplicitWrapper<TObject[TKey] | undefined>;
```

In my understanding, this should be the overload used instead (let's name it `#2`). It does not yet exist:
```typescript
        /**
         * @see _.get
         */
        get<TObject extends object, TKey extends keyof TObject>(
            this: LoDashExplicitWrapper<TObject>,
            path: TKey | [TKey],
        ): LoDashExplicitWrapper<TObject[TKey]>;
```

Now it could be that `undefined` in a chain of nested property accessing (i.e. multiple `.get().get().get()` calls) needs to be forwarded (because as soon as a property is optional, then `undefined` is part of the return type). That's why the existing type definition `#1` still needs to be present.

## Conclusion
The issue can be fixed if we add the overload `#2` just **above** the overload `#1`.

Then we have correctly:
```typescript
const horsepowers = _.chain(car)
   .get('engine')
   .get('horsepowers').value(); // number <-- OK :)
```

Plus: if you make the engine optional as well like this:
```typescript
interface Car {
    engine?: Engine;
}
```
Then we will also have correctly:
```typescript
const horsepowers = _.chain(car)
    .get('engine')
    .get('horsepowers').value(); // number | undefined <-- OK because "engine" can be undefined
```

Of course the versions with the `defaultValue` need to be addressed as well. What do you think?

- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
versions tested: 2.7.2 + 2.8.3

- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @aj-r @Ailrun @e-cloud @thorn0 @jtmthf @DomiR

**Comment by aj-r** [comment]
I think it should be using this overload which already exists:

```ts
get<TKey extends keyof TValue>(
    path: TKey | [TKey]
): LoDashExplicitWrapper<TValue[TKey]>;
```

not sure why it doesn't use that.

**Comment by NicBright** [comment]
@aj-r You're totally right. It's been my fault. Somehow I inadvertently have managed to modify my version to be this (which TS didn't complain about).

```typescript
        /**
         * @see _.get
         */
        path: TKey | [TKey]
        get<TKey extends keyof TValue>(
        ): LoDashExplicitWrapper<TValue[TKey]>;
```

Could have saved us both a lot of time if I had made sure I got a pristine object.d.ts file :-/ Sorry for that.
