### ISSUE TITLE
[@type/node] Property does not exist from net.Server.address()

### ISSUE THREAD

**Issue by ttranPCS** [DefinitelyTyped/DefinitelyTyped#25865]
Hello everyone,

I tried to build and run the mock debugger from VS Code.
> https://github.com/Microsoft/vscode-mock-debug

The error occurs from the file extension.ts line 79
`config.debugServer = this._server.address().port;`

Error:
> Property 'port' does not exist on type 'string | AddressInfo'. Property 'port' does not exist on type 'string'.

I went to the file index.d.ts and changed line 2841 from
`address(): AddressInfo | string;`
to
`address(): AddressInfo;`

And the error will disappear and everything works fine.
Could you please help me with this problem?
Thank you.

Here are some info:

VS Code
> Version 1.22.2
> Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
> Date 2018-04-12T16:34:44.222Z
> Shell 1.7.12
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

OS: ubuntu 18.04

@parambirs Could you please give me a hint?

**Comment by Flarna** [comment]
`net.address()` returns a `string` in case socket is bound to a windows pipe or unix domain socket or it returns a `AddressInfo` object if it is bound to a TCP socket. Therefore type is correct and you have to check in your code which type it is or you cast.

**Comment by Antibioticvz** [comment]
Can not make this work
`const { port } = app.address();`
Previous working index.d.ts version was
`address(): { port: number; family: string; address: string; };`
Current implementation
`address(): AddressInfo | string;        `

> [ts] Type 'string | AddressInfo' has no property 'port' and no string index signature.

Can anyone provide an example how to get the port property?

**Comment by Flarna** [comment]
try `const { port } = app.address() as AddressInfo;` if you know that you get no string in your usecase.

**Comment by Antibioticvz** [comment]
@Flarna  That works! Thank you!
