### ISSUE TITLE
Plugin Registration

### ISSUE THREAD

**Issue by ozum** [DefinitelyTyped/DefinitelyTyped#25887]
@BorntraegerMarc, @rafaelsouzaf, @jhsimms, @SimonSchick

I'm trying to write type definitions for [schwifty](https://github.com/hapipal/schwifty) hapi plugin. Plugin is exporting other attributes besides `plugin` attribute as ssen [here](https://github.com/hapipal/schwifty/blob/master/lib/index.js).

**schwifty.js**
```js
exports.Model = SchwiftyModel
exports.plugin = {}
```

I have struggle to use `server.register({ plugin: Schwifty })`, because it seems not allowed by Hapi definitions.

**index.d.ts**
```ts
import { Plugin } from "hapi";

interface RegistrationOptions {...}

export const plugin: Plugin<RegistrationOptions>;
export class Model {}
```

**server.ts**
```ts
import * as Schwifty from "schwifty";

// Three variations:
await server.register(Schwifty); // OK
await server.register({ plugin: Schwifty, options: {...} }); // ERROR (see message below)
await server.register({ plugin: 9999, options: {...} }); // ERROR obviously
await server.register({ plugin: Schwifty.plugin, options: {...} }) // OK
```

`Object literal may only specify known properties, and 'plugin' does not exist in type '(PluginBase<any> & PluginNameVersion) | (PluginBase<any> & PluginPackage) | Plugin<any>[]'.`

I was expecting `await server.register({ plugin: Schwifty, options: {...} });` to work, because it conforms `hapi` plugin standard. I guess in hapi definitions, `Server.register()` or `ServerRegisterPluginObject` does not allow this.

Could you please advise?

**Comment by SimonSchick** [comment]
I don't think the second variant you listed would even work. Can you please provide the typings you created for your package?

**Comment by ozum** [comment]
@SimonSchick @jhsimms thanks.

Please see gist [here](https://gist.github.com/ozum/db981432cd7b472b98fc87b40834558a).
Example from original [README](https://github.com/hapipal/schwifty) of Schwifty.

Also, while looking the code, I have another point on **line 58** that I need help. I will be grateful, if you have suggestion for that too.

**line 58 from [gist](https://gist.github.com/ozum/db981432cd7b472b98fc87b40834558a)**
`models: (all?: boolean) => { [key: string]: typeof Model };`

Schwifty adds Objection/Schwifty model classes on runtime dynamically using `server.schwifty(MyModel)` and retrieves it using `const { MyModel } = request.models()`.

Is there a way to provide exact class type instead of parent class `Model` here? I have several trials using generics (`<T>`), but cannot achieve desired result.
