### ISSUE TITLE
issue with @types/ws?

### ISSUE THREAD

**Issue by toovs** [DefinitelyTyped/DefinitelyTyped#25890]
`node_modules/@types/ws/index.d.ts(179,24): error TS2694: Namespace '"net"' has no exported member 'AddressInfo'.`

any ideas?

**Comment by peterkelly** [comment]
I found that to the latest type definitions for node fixed this problem:

```
nom install @types/node
```

**Comment by toovs** [comment]
yup! thx.

**Comment by austinried** [comment]
This means that these types are only compatible with `@types/node@10`, which is what currently gets installed when you use `@types/node`.  I can find no information on `ws` that says it is not compatible with node <10, why was a dependency on node 10 taken for the types?

Closest thing I can find is that version 5.0.0 of `ws` dropped support for node < 4.5.0, so these type definitions for 5.x should be working with everything above that.

**Comment by Griffork** [comment]
I'm trying to use these types on node @6.12 and they're not working.

**Comment by kyledetella** [comment]
I just downgraded `@types/node` from `^10.x` to `9.3.0` (the version of Node I am pinned to) to mitigate [this issue](https://github.com/angular/angular/issues/24245) (which is actually _not_ an Angular issue, btw) and am now experiencing this issue.

**Comment by Griffork** [comment]
@kyledetella a pull request has been submitted and should be completed in the next week or so.

In the meantime you can add the dollowing code to an empty. d.ts file in your project to get it to compile

``` ts
declare module 'net' {
    export interface AddressInfo {} 
} 
```
Writing on phone - sorry for mistakes.

**Comment by kyledetella** [comment]
Thanks @Griffork. That did the trick!

**Comment by Griffork** [comment]
Looks like the fix has been merged. I haven't tested it yet though.
