### ISSUE TITLE
Question: How do I use lodash@mergeWith with spread args

### ISSUE THREAD

**Issue by sdwvit** [DefinitelyTyped/DefinitelyTyped#25940]
Hey, 
I have latest types@lodash, and I bumped into typing problem:

I have the code:
```
...mergeWith({}, ...poll_results, _resultsMerger)
```
where _resultsMerger is customizer function

And in typedef I see:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2f052d79f7154b608d0f64495ae1fea54a71bc02/types/lodash/common/object.d.ts#L2739-L2745
As you can see, there is no customizer func.

Thus, I receive the error
```
code.js(114,10): error TS2557: Expected at least 1 arguments, but got 1 or more.
```

How am I suppose to rewrite code so I don't have error?

**Comment by aj-r** [comment]
It's probably an issue with `poll_results` or `_resultsMerger`, but without knowing what they are, it's impossible to say. Can you give some more details on those variables?

This code works for me with no error:

```ts
const poll_results: any[] = [];
function _resultsMerger(a: any, b: any) {
    return a === b;
}

_.mergeWith({}, ...poll_results, _resultsMerger);
```

**Comment by sdwvit** [comment]
thanks for the working example @aj-r

I have fixed it long time ago by changing logic, so I no longer need _.mergeWith

**Comment by SerkanSipahi** [comment]
I had the same error message with `merge`

error with: `merge(...objectList)`;
fixed with: `merge({}, ...objectList)`;

**Comment by aj-r** [comment]
Unfortunately that is not supported due to a limitation in typescript. If
you really want to do that you could disable type checking:

(merge as any)(...objectList);
