### ISSUE TITLE
Changes in d3 types tagging (versions should be fixed)

### ISSUE THREAD

**Issue by XC-** [DefinitelyTyped/DefinitelyTyped#26000]
In our project we use d3 type definitions and today we noticed that the version tagging has changed recently. Now _latest_ tag points to 0.4.4 (which breaks our build on TS 2.5) instead of 1.0.32. This might be fine if the intention is that _latest_ always points to the most recent release. However, when installing @types/d3 this causes problems as it does not have fixed dependency versions. Installing ts2.5 tagged version does not install ts2.5 tagged dependencies. As in our case, this can cause breaking builds.

How to mitigate: specify @types/d3's dependency versions explicitly in the package.json. 
Proper fix: @type/d3's dependencies should have specific versions defined (or use the same tag as the main package).

**Comment by msandeeprao38** [comment]
same issue

**Comment by phyratokar** [comment]
I run into this problem as well.

**Comment by sanalpanicker** [comment]
Same issue and all our builds failed

**Comment by andres-artunduaga** [comment]
Getting the same issue here

**Comment by phyratokar** [comment]
Seems like the issue was resolved, I can again install and build my application without any additional devDepencies.

**Comment by XC-** [comment]
In short term, yes, the issue was resolved but in long term the problem still exists as long as @types/d3 has an asterisk as version for its dependencies. If a new version of 0.x -line is released (I don't know if this can still happen, but considering that 0.4.4 was released, I assume it can) then we run into this issue again. Right now only way to guarantee that this won't happen again is to define the dependencies by ourselves in dev dependencies. Rather than doing that, it should be resolved by those maintaining the package.

**Comment by tomwanzek** [comment]
@XC- Can this issue be closed? It seems the version tagging issues introduced by a updates to legacy version definitions have been resolved.

**Comment by XC-** [comment]
If the policy is that there is no guarantee what versions of d3's dependencies will be installed with a specific version (or tag) of d3 main package, then I guess it can be. In that case the question is that is the policy clearly documented and is it stated that the dependency versions should be defined alongside d3 version in whatever package requires it.

The way I see it, is that when I install a specific release of @types/d3, I should also receive specific versions of the dependencies as well, not "latest". Of course, I am not the maintainer or the owner of this package and things like these depend on what are the specs and policies. From what I've seen, root cause to the issue still exists and may break things later on as well, so personally I wouldn't call this solved.

**Comment by tomwanzek** [comment]
@XC- It's not an issue package maintainers can address. It is an issue rooted in the way the DefinitelyTyped -> npm publication pipeline works. I wish, I could address it. We have repeatedly asked for the ability to use a `package.json` stub to pin minor versions of dependencies, but have been advised that this feature is no longer supported.

It's not for lack of trying. See this issue thread under [Strategy for D3 Version 5 Definitions Release ](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23257#issuecomment-362477088)

**Comment by XC-** [comment]
Well if that is the situation, I will close this issue.
