### ISSUE TITLE
Enzyme instance() method should be able to carry type of wrapped class

### ISSUE THREAD

**Issue by amacleay** [DefinitelyTyped/DefinitelyTyped#26039]
**This is an issue to track the problem meant to be addressed by #18043**

If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @MarianPalkus @NoHomey @jwbay @huhuanming @MartynasZilinskas @thovden
  - Original PR author @mohsen1 

# Issue
Calls to `shallow(..).instance()` should have the type of the component they wrap.

# Example
(thanks to @mohsen1 - took straight from the test PR)
```typescript
class MyComponentWithMethods extends React.Component<{}, {}> {
    someMethod() {
        return 'some string';
    }
}
function test_instance_method_inferring() {
    let wrapper = shallow(<MyComponentWithMethods />);
    let instance: MyComponentWithMethods = wrapper.instance();
    let b: string = wrapper.instance().someMethod();
}
```
Result:
```
Property 'someMethod' is missing in type 'Component<any, any, any>'.
```
Workaround: cast the output of `instance`
```typescript
function test_instance_method_inferring() {
    let wrapper = shallow(<MyComponentWithMethods />);
    let instance = wrapper.instance() as MyComponentWithMethods;
    let b: string = wrapper.instance().someMethod();  // works
}
```

Possible solution: add a third property parameter to `shallow`
```diff
export function shallow<P>(node: ReactElement<P>, options?: ShallowRendererProps): ShallowWrapper<P, any>;
< export function shallow<P, S>(node: ReactElement<P>, options?: ShallowRendererProps): ShallowWrapper<P, S>;
> export function shallow<P, S, C = Component<P, S>>(node: ReactElement<P>, options?: ShallowRendererProps): ShallowWrapper<P, S, C>;
```

This would mean that the test above would pass with the following change:
```typescript
function test_instance_method_inferring() {
    let wrapper = shallow<{}, {}, MyComponentWithMethods>(<MyComponentWithMethods />);
    let instance: MyComponentWithMethods = wrapper.instance();
}
```

I can try to put together a PR if that seems like a sensible idea.

**Comment by mohsen1** [comment]
I like the idea of extra generic parameter but it should all be infered so users don't have to pass all those generic parameters

**Comment by astorije** [comment]
@mohsen1, thanks for your answer!
That makes total sense, but I'm afraid both my and @amacleay's skills (we work together) haven't reached that far yet. Do you know how we could do this?

**Comment by mohsen1** [comment]
Generic type parameters that are generics themselves [work just fine in TypeScript](http://www.typescriptlang.org/play/index.html#src=class%20A%3CT%3E%20%7B%0D%0A%20%20%20%20constructor(public%20t%3A%20T)%20%7B%7D%0D%0A%7D%0D%0Aclass%20C%3CT%2C%20U%3E%20%7B%0D%0A%20%20%20%20constructor(private%20t%3A%20T%2C%20private%20u%3A%20A%3CU%3E)%20%7B%20%7D%0D%0A%0D%0A%20%20%20%20getT()%3A%20T%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.t%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20getU()%3A%20U%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.u.t%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Aconst%20c%20%3D%20new%20C(1%2C%20new%20A('str'))%3B%0D%0A%0D%0Alet%20a%3A%20number%3B%0D%0Aa%20%3D%20c.getT()%3B%0D%0A%0D%0Alet%20b%3A%20string%3B%0D%0Ab%20%3D%20c.getU()%3B%0D%0A%0D%0A). I have not looked into this particular issue but you should be able to make it work. 

I think you're on the right track here. Please give it another shot and let me know if that didn't work :)

**Comment by jwbay** [comment]
It's not possible to get the component type from a JSX expression because the return type of all JSX expressions is currently just `JSX.Element`, so inference is a no-go. This may be worth raising with the TS team.

The third instance type parameter isn't great because the first two are actually on that type. One option is to drop down to one parameter, the component type, and use index types to get props and state. It would be a fairly massive breaking change, but it seems to work pretty well, and could even give you methods off of `.find(Component).instance()`:
```ts
declare class Test extends React.Component<{ a?: number }> {
  method(): void;
}

declare function shallow<C extends React.Component = React.Component>(node: JSX.Element): ShallowWrapper<C>;

interface ShallowWrapper<C extends React.Component> {
  props(): C['props'];
  state(): C['state'];
  instance(): C;
}

const wrapper = shallow<Test>(<Test />);

wrapper.props().a; // ok, number
wrapper.instance().method; // ok, () => void;
```

**Comment by mohsen1** [comment]
JSX (React.crrateElement really) is breaking the types here. The only way to solve this is to have a runtime function in typescript that accepts the component class and props and will invoke React.createElement in it with shallow wrapped in it.

**Comment by amacleay** [comment]
I can take a run at @jwbay 's suggestion in a PR if that seems sensible. It makes sense to me, at least.

@mohsen1 - is that really feasible? I'm not sure how such a thing would work.

**Comment by mohsen1** [comment]
I mean something like this:

function shallow (componentClass, props) {
  return shallow(<componentClass {...props} />)
}

**Comment by mohsen1** [comment]
With @Hotell generic syntax you can have a runtime wrapper function that removes the need of casting or providing generic type:

```ts
import enzyme from 'enzyme';

function shallow<P = {}, C extends React.Component<P>>(ComponentClass: typeof C, props: P) {
  return enzyme.shallow<C>(<ComponentClass {...props} />)
}
```

with that, this should work:

```
class MyComponent extends React.Component<{foo: number> {
 render() { return null }
}
swallow(
```

**Comment by Hotell** [comment]
that is unnecessary boilerplate @mohsen1

all you need to do from now on is in demonstrated in test https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26565/files#diff-2931280905f283a37c4795c53167755cR354

```tsx
class MyComponentWithMethods extends React.Component<{}, {}> {
    someMethod() {
        return 'some string';
    }
}
test('instance type by providing component type explicitly works', () => {
    const wrapper = shallow<MyComponentWithMethods>(<MyComponentWithMethods />);
    expect(wrapper.instance().someMethod()).toBe('some string');
  }
}
```

**Comment by mohsen1** [comment]
I mean if you don't want to repeat component type in the generic you can do that runtime function :)

**Comment by joshuatTW** [comment]
This works well with const. Does anyone know how to do this for an implicitly typed  any `let`?

e.g. 

```
let component;  // typed any
beforeEach(() => {
  component = mount<MyComponent>(<MyComponent>);
});

test('my test', () => {
 //component is still typed any
});
```

**Comment by joshuatTW** [comment]
I now get this error `error TS2347: Untyped function calls may not accept type arguments.` when compiling

**Comment by mohsen1** [comment]
You need to declare the type of `component` before assigning to it.

**Comment by dannypule** [comment]
@joshuatTW 

To use it with let, you need to use the Props and/or State types from your component and pass them to `ShallowWrapper<Props, State>;`

```js
import MyComponent, { Props, State } from './MyComponent';

...

let wrapper: ShallowWrapper<Props, State>;

...

wrapper = shallow< MyComponent >(< MyComponent {...props} />);

...

expect(wrapper.instance().someMethod()).toBe('some string');
```

**Comment by P0ntiuS** [comment]
Can this work for functional components?

Like 
```JavaScript
function MyComponentWithMethods(): JSX.Element {
    function onButtonClick(): void {
        console.log('Button clicked!');
    }
    return (<button onClick={onButtonClick}>Click me!</button>);
}
```

**Comment by jfirebaugh** [comment]
> It's not possible to get the component type from a JSX expression because the return type of all JSX expressions is currently just JSX.Element, so inference is a no-go. This may be worth raising with the TS team.

Relevant TypeScript issues:

* https://github.com/microsoft/TypeScript/issues/14729
* https://github.com/microsoft/TypeScript/issues/13890
* https://github.com/microsoft/TypeScript/issues/21699
* https://github.com/microsoft/TypeScript/pull/29818
