### ISSUE TITLE
d3-dsv erroneous export?

### ISSUE THREAD

**Issue by newsash** [DefinitelyTyped/DefinitelyTyped#26033]
- [+] I tried using the `@types/d3` package and had problems.
- [- (latest `@angular/cli` -> typescript ~2.7] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [?] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [+] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek @gustavderdrache @borisyankov

> ERROR in node_modules/@types/d3-fetch/index.d.ts(9,10): error TS2305: Module '".../node_modules/@types/d3-dsv/index"' has no exported member 'DSVParsedArray'.
> node_modules/@types/d3-fetch/index.d.ts(9,26): error TS2305: Module '".../node_modules/@types/d3-dsv/index"' has no exported member 'DSVRowString'.
> node_modules/@types/d3-fetch/index.d.ts(9,40): error TS2305: Module '".../node_modules/@types/d3-dsv/index"' has no exported member 'DSVRowAny'.
> node_modules/@types/d3-fetch/index.d.ts(9,57): error TS2497: Module '".../node_modules/@types/d3-dsv/index"' resolves to a non-module entity and cannot be imported using this construct.
> node_modules/@types/d3/index.d.ts(24,15): error TS2498: Module '".../node_modules/@types/d3-dsv/index"' uses 'export =' and cannot be used with 'export *'.
>

**Comment by victornoel** [comment]
The wrong version is published on npm as latest, see also yarnpkg/yarn#5880 where this was discussed.

**Comment by tomwanzek** [comment]
@andy-ms It seems that when commit https://github.com/DefinitelyTyped/DefinitelyTyped/commit/09c94e3e87efc06f5c8b95ff1761298408edb4d5 was merged and published, it unfortunately updated the `latest` version for `npm/@types/d3-dsv` back to a patch release for version **0.4.x** (historic major version). While the same PR also contained changes to the current **1.x** version of `d3-dsv` definitions.

Is there an easy way to update the `latest` on npm, or do we have to push some non-material change to the 1.x `index.ts` to trigger a proper release of latest?

@newsash and @victornoel thanks for tracking this one down, sorry for the inconvenience :smile:

cc @denisname

**Comment by victornoel** [comment]
@tomwanzek btw, you could check npm/npm#6778 or npm/npm#4709 for ideas on how to better handle the situation (I haven't read them in details, I hope there are good answers) :)

**Comment by denisname** [comment]
Made a small PR. Guess this will be the simplest and fastest way to fix this "nonsense".

Note: `d3-scale` also was updated for two versions in that commit. So it may be broken too.

**Comment by tomwanzek** [comment]
@newsash Can we close this issue, the immediate issue has been closed.

@victornoel Thanks for the links, unfortunately as definition authors we don't control the publication pipeline.
