### ISSUE TITLE
How to redact or omit my name from a package?

### ISSUE THREAD

**Issue by JayAndCatchFire** [DefinitelyTyped/DefinitelyTyped#26092]
Once upon a time, I submitted a type package for karma-chai.  It's this one: https://www.npmjs.com/package/@types/karma-chai

As you can see, the README that was generated includes my full name in the "Credits" section.  I don't mind a link to my github account, but I'd prefer it if my legal name wasn't used.  Is there something I can do about that?

**Comment by JayAndCatchFire** [comment]
@andy-ms?

**Comment by RyanCavanaugh** [comment]
This is just pulled from the header in the file: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/karma-chai/index.d.ts#L3

You can change that to a psuedonym or whatever; we'll accept anything that's from you as how you'd like your name to be displayed in the README

**Comment by JayAndCatchFire** [comment]
Thank you!
