### ISSUE TITLE
Express typings seem to choke on middleware

### ISSUE THREAD

**Issue by jbreckmckye** [DefinitelyTyped/DefinitelyTyped#26146]
- [√] I tried using the `@types/xxxx` package and had problems.
- [√] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [√ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [ √] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @19majkel94 @kacepe @micksatana @samijaber 

I'm having the current problem using @types/express 4.11.1 & TSC 2.8.3.

The following code cannot compile:

```typescript
function aMiddleware(req: Request, res: Response, next: NextFunction) {
    next();
}

app.get('/foo/bar', aMiddleware);
```

I get the following error:

```
TS2345: Argument of type '(req: Request, res: Response, next: NextFunction) => void' is not assignable to parameter of type 'RequestHandlerParams'.
  Type '(req: Request, res: Response, next: NextFunction) => void' is not assignable to type '(RequestHandler | ErrorRequestHandler)[]'.
    Property 'includes' is missing in type '(req: Request, res: Response, next: NextFunction) => void'.
```

**Comment by micksatana** [comment]
Hi Jimmy,

You need to import like this...
```
import { Express, Request, Response, NextFunction } from 'express';
const express = require('express');

const app: Express = express();

function aMiddleware(req: Request, res: Response, next: NextFunction) {
    next();
}

app.get('/foo/bar', aMiddleware);
```

The reason is `Request`, `Response`, `NextFunction` of Node.js is not the same as Express.

Hope this help.

**Comment by jbreckmckye** [comment]
Thanks, I'll give that a try!

**Comment by jbreckmckye** [comment]
This works great. Thanks muchly.

**Comment by jonah-cod** [comment]
Thanks this works

**Comment by dhawel** [comment]
Thanks !
