### ISSUE TITLE
[@types/webpack] properly type devServer

### ISSUE THREAD

**Issue by joma74** [DefinitelyTyped/DefinitelyTyped#26171]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo

Hey,

As mentioned in https://github.com/Microsoft/TypeScript/issues/14377#issuecomment-393491871; if advisable, instead of 
```
devServer?: any; // TODO: Type this
```
connect to `webpack-dev-server.Configuration`.

**Comment by mohsen1** [comment]
Please make a pull request :)

**Comment by SystemDisc** [comment]
It seems to me that `devServer?: any;` is actually more correct than what you're proposing, and in fact maybe it should even be removed.

What should be done instead, I think, is to properly update `webpack.Configuration` in `@types/webpack-dev-server`. I'll make a PR for you.

**Comment by joma74** [comment]
Fixed by oneof(#27009, #26895).
