### ISSUE TITLE
Last update to CollectionElements breaks type

### ISSUE THREAD

**Issue by jan-johansson-mr** [DefinitelyTyped/DefinitelyTyped#26238]
The change of CollectionElements from:

`interface CollectionElements extends
        EdgeCollection, NodeCollection, SingularElement { }`

in version 3.1.9, to

`type CollectionElements = EdgeCollection | NodeCollection | SingularElement;`

in version 3.1.10, breaks cytoscape type, e.g. `cytoscape.elements().jsons()` now produces a typescript error (typescript complains e.g: `Property 'jsons' does not exist on type 'CollectionElements'. Did you mean 'json'?
  Property 'jsons' does not exist on type 'SingularElement'.`).

Here is the link to the line breaking the type:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e4a45e562bf9fd6e94178c9484e5dd488a379997/types/cytoscape/index.d.ts#L1130

@Cerberuser, @ypconstante 

Thanks

**Comment by Cerberuser** [comment]
Thanks. It seems that I've missed this part (and probably some more). I'll look into this ASAP.

**Comment by Cerberuser** [comment]
There are too many breaks in places previously untested, I can't understand the whole impact yet. Seems that we should just revert this change for now, anything better would come a bit later.

**Comment by jan-johansson-mr** [comment]
Thanks @Cerberuser.

**Comment by Cerberuser** [comment]
#26398 - seems to be fixed, waiting for update on npm.

**Comment by jesskfullwood** [comment]
Thanks for the update. I found that I am now getting a new typeerror when setting a callback on an edge element:
```
    TS2339: Property 'on' does not exist on type 'EdgeSingular'. 
```
I guess `EdgeSingular` no longer implements `CollectionEvents`?

**Comment by Cerberuser** [comment]
Yes, I see the place where it is broken (seems that I haven't tested this feature properly). PR will be sent today.

**Comment by Cerberuser** [comment]
Fixed by #26685.

**Comment by tbarron-xyz** [comment]
Looks like this issue can be closed as the pull request was merged.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
