### ISSUE TITLE
TS2717: Subsequent property declarations must have the same type.  Property 'div' must be of type 'any', but here has type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.

### ISSUE THREAD

**Issue by henres** [DefinitelyTyped/DefinitelyTyped#26264]
Hello, i have a problem with types/react on build time :

```
"typescript": "^2.8.4"
"@types/react": "^16.3.16"
"node": "v8.11.2"
```

```shell
ERROR in [at-loader] ./node_modules/@types/react/index.d.ts:2277:13 
    TS2717: Subsequent property declarations must have the same type.  Property 'div' must be of type 'any', but here has type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
```

Author: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa

**Comment by ferdaber** [comment]
Looks like there's an overlapping definition in your project. It might be that you have (in an external type library or in your own code) have a definition for this:
```ts
declare namespace JSX {
  declare interface IntrinsicElements {
    div: any
  }
}
```

**Comment by henres** [comment]
Yeah, ... My bad, still a newbie in it. So many people trigger for this ! So sorry.

Thanks for the help @ferdaber 

Have a nice day !
