### ISSUE TITLE
Couldn't find package "aws-serverless-express" on the "npm"registry.

### ISSUE THREAD

**Issue by am17torres** [DefinitelyTyped/DefinitelyTyped#26277]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andy-ms 

If you do not mention the authors the issue will be ignored.

```
❯ yarn add -D @types/aws-serverless-express
yarn add v1.6.0
warning package.json: No license field
info No lockfile found.
warning No license field
[1/4] 🔍  Resolving packages...
error Couldn't find package "aws-serverless-express" on the "npm"registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

<img width="326" alt="image" src="https://user-images.githubusercontent.com/70786/40952073-e6ae5576-6847-11e8-8052-361a79c32e96.png">

**Comment by andy-ms** [comment]
It works for me with `npm info @types/aws-serverless-express`. Maybe you're using a proxy? Could you try with `npm` instead of `yarn`?

**Comment by am17torres** [comment]
I was able to download it successfully today; sorry for the false alarm.
I think I fell victim to https://status.npmjs.org/incidents/f1d1s28rtvqm
