### ISSUE TITLE
[expo] add 27.0.0 version

### ISSUE THREAD

**Issue by moshfeu** [DefinitelyTyped/DefinitelyTyped#26284]
- Authors: @KonstantinKai 

I started in my branch expo-27.0.0 here:

https://github.com/moshfeu/DefinitelyTyped/tree/expo-27.0.0

Should I create a pull request once I finish them all? If anyone to join the effort, should he commit to my branch?

**Comment by KonstantinKai** [comment]
Hi, No, You shouldn't. The current issue is enough. Thanks 👍

**Comment by moshfeu** [comment]
So I will create a PR only when I will finish the task, right?

**Comment by KonstantinKai** [comment]
Yep.

**Comment by moshfeu** [comment]
Ok, Thanks!

**Comment by moshfeu** [comment]
Created [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26324).

**Comment by moshfeu** [comment]
Merged
