### ISSUE TITLE
@types/enzyme breaks with typescript 2.9

### ISSUE THREAD

**Issue by harry-sm** [DefinitelyTyped/DefinitelyTyped#26345]
@MarianPalkus @NoHomey @andy-ms 
types/enzyme fails with typescript 2.9.1

Error
`Interface 'Element' cannot simultaneously extend types 'ReactElement<any>' and 'ReactElement<any>'.
  Named property 'type' of types 'ReactElement<any>' and 'ReactElement<any>' are not identical.`

**Comment by andy-ms** [comment]
@harry-sm Could you clarify how you're getting this error? `cd types/enzyme` and `tsc` doesn't show any error.

**Comment by harry-sm** [comment]
@andy-ms 
All I did was update my project typescript dev dependency to 2.9.1 and then tried to run the project which resulted in that error.
![image](https://user-images.githubusercontent.com/15040197/41129021-4af0a880-6a7e-11e8-8473-9d4167439bfd.png)

**Comment by andy-ms** [comment]
I notice that the path is `node_modules/@types/enzyme/node_modules/@types/react`. That probably indicates you have two different versions of `@types/react` installed, which likely causes the error.

**Comment by harry-sm** [comment]
Ok I'll try and update my `@types/react` and see what happens.

**Comment by harry-sm** [comment]
@andy-ms 
So updated my `@types/react` and got the same error. I went into the node_modules folder and saw that `@types/enzyme` is using `@types/react v16.0.40`. I switched to that version and the error is gone but now other packages are broken. I was using `v16.3.17` before.

**Comment by Hotell** [comment]
I had similar problem, but it was merely with yarn dependency resolution. Try remove yarn.lock and install deps again. solved that issue for me ( clean shallow dependency tree, no react types duplicates )

**Comment by harry-sm** [comment]
@Hotell Thanks that fixed the issue and some others I have been having :).
