### ISSUE TITLE
@types/ramda

### ISSUE THREAD

**Issue by gkTim** [DefinitelyTyped/DefinitelyTyped#26375]
Hi,

I've got the following error when I try to use ramda in an angular 6 project.
I've tried it with ts 2.7.2 and 2.9.1.

```
ERROR in node_modules/@types/ramda/index.d.ts(89,27): error TS1005: ';' expected.
node_modules/@types/ramda/index.d.ts(89,41): error TS1005: ';' expected.
node_modules/@types/ramda/index.d.ts(89,69): error TS1005: '(' expected.
node_modules/@types/ramda/index.d.ts(89,75): error TS1005: ')' expected.
node_modules/@types/ramda/index.d.ts(93,11): error TS1005: ';' expected.
node_modules/@types/ramda/index.d.ts(93,53): error TS1005: '(' expected.
node_modules/@types/ramda/index.d.ts(94,11): error TS1005: ',' expected.
node_modules/@types/ramda/index.d.ts(94,53): error TS1005: '(' expected.
node_modules/@types/ramda/index.d.ts(95,14): error TS1005: ')' expected.
node_modules/@types/ramda/index.d.ts(98,11): error TS1005: ';' expected.
node_modules/@types/ramda/index.d.ts(98,31): error TS1005: ')' expected.
node_modules/@types/ramda/index.d.ts(98,52): error TS1005: '(' expected.
node_modules/@types/ramda/index.d.ts(98,67): error TS1005: '(' expected.
node_modules/@types/ramda/index.d.ts(98,76): error TS1005: ',' expected.
node_modules/@types/ramda/index.d.ts(98,83): error TS1005: ')' expected.
node_modules/@types/ramda/index.d.ts(106,31): error TS1005: ';' expected.
node_modules/@types/ramda/index.d.ts(106,53): error TS1005: ',' expected.
node_modules/@types/ramda/index.d.ts(107,18): error TS1005: ';' expected.
node_modules/@types/ramda/index.d.ts(107,52): error TS1005: '(' expected.
node_modules/@types/ramda/index.d.ts(109,5): error TS1005: ',' expected.
node_modules/@types/ramda/index.d.ts(109,6): error TS1005: ')' expected.
node_modules/@types/ramda/index.d.ts(2139,1): error TS1128: Declaration or statement expected.
```

- [x] I tried using the `@types/ramda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sbking @mdekrey 

If you do not mention the authors the issue will be ignored.

**Comment by harrygr** [comment]
@donnut @tycho01 @mdekrey

**Comment by tycho01** [comment]
@gkTim consider trying the typings at https://github.com/types/npm-ramda/. 2.9 compatibility is still an [open issue](https://github.com/types/npm-ramda/issues/391) there, but up to 2.8 should work.

**Comment by gkTim** [comment]
@tycho01 Thanks for the hint. This works.

**Comment by philip-firstorder** [comment]
For me this is the most up-to-date configuration that works, newer versions will break.
```
"ramda": "0.25.0",
"@types/ramda": "0.25.24", // newer until 0.25.33 will break
"typescript": "2.7.2" // newer until 2.9.2 will break
```

**Comment by weiyiao** [comment]
I use @types/ramda@0.25.24, is Ok.

**Comment by amilner42** [comment]
> For me this is the most up-to-date configuration that works, newer versions will break.
> 
> ```
> "ramda": "0.25.0",
> "@types/ramda": "0.25.24", // newer until 0.25.33 will break
> "typescript": "2.7.2" // newer until 2.9.2 will break
> ```

I went with:

```
"ramda": "^0.25.0",
"@types/ramda": "^0.25.0",
"typescript": "^2.9.2"
```

And this seems to be working. Will post again if there are surprises...

**Comment by emrehayirci** [comment]
I've experienced a very similar issue for @types/ramda 0.27.38 and the solution for me was to stay at 0.27.34

**Comment by grapereader** [comment]
So what was added in the last 3 revisions that is breaking on recent TS versions? They should either be rolled back or fixed.

**Comment by jedahan** [comment]
Same issue with tsc v4.2.4

**Comment by jsamr** [comment]
OK with tsc v4.4.2

**Comment by jakebailey** [comment]
These versions are well outside our documented support window; closing.
