### ISSUE TITLE
Type definion for the dns.lookupService is missing

### ISSUE THREAD

**Issue by bgedik** [DefinitelyTyped/DefinitelyTyped#26389]

**Comment by r3nya** [comment]
Hey @bgedik!

This function was added in node v0.11.14 (https://nodejs.org/api/dns.html#dns_dns_lookupservice_address_port_callback).

For supports it we need to add this code:

```js
export function lookupService(address: string, port: number, callback: (err: NodeJS.ErrnoException, hostname: string, service: string) => void): void;

export namespace lookupService {
  export function __promisify__(address: string, port: number): Promise<{ hostname: string, service: string }>;
}
```

I can create a PR for it but don't know how to create typings for unstable node.js version (0.11.x).

**Comment by bgedik** [comment]
@r3nya While it says ``added in 0.11.14``, it is actually not correct. It is there in LTS ``v8.11.1``. See here: https://nodejs.org/dist/latest-v8.x/docs/api/dns.html#dns_dns_lookupservice_address_port_callback

Also, we are using it in ``v8.11.1``, so I am pretty sure it is there.

**Comment by r3nya** [comment]
Oh damn. You're right … 

> v0.11.14

**0**.11.14 ROFL.

**Comment by r3nya** [comment]
@bgedik I've created PR for it. Waiting for review. 😉

**Comment by r3nya** [comment]
Hey @bgedik!

My PR was merged and you can install new verision for typings. Please close this issue. ;)

**Comment by bgedik** [comment]
Thanks @r3nya.
