### ISSUE TITLE
Missing type definition for types/jest: "toHaveBeenNthCalledWith"

### ISSUE THREAD

**Issue by blackarctic** [DefinitelyTyped/DefinitelyTyped#26387]
The type definition for `toHaveBeenNthCalledWith` in `types/jest` seems to be missing in the latest version.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5f9dbc9836364dfd530af2ea3e3ddc1b47536a64/types/jest/index.d.ts#L470

https://facebook.github.io/jest/docs/en/expect.html#tohavebeennthcalledwithnthcall-arg1-arg2-

![screen shot 2018-06-08 at 3 21 50 pm](https://user-images.githubusercontent.com/10765285/41179327-f8a79324-6b2f-11e8-8e0e-40b26120cf43.png)

![screen shot 2018-06-08 at 3 23 37 pm](https://user-images.githubusercontent.com/10765285/41179330-fa9c5f0c-6b2f-11e8-83a4-14b10763ba31.png)

**Comment by blackarctic** [comment]
From what I can tell, `index.d.ts` should include 

```ts
/**
 * If you have a mock function, you can use `.toHaveBeenNthCalledWith`
 * to test what arguments it was nth called with.
 */
toHaveBeenNthCalledWith(nthCall: number, ...params: any[]): R;
```

**Comment by r3nya** [comment]
Hey @blackarctic!

I've created PR for it #26399 … waiting for review. 😉

**Comment by blackarctic** [comment]
Looks good! 👍
