### ISSUE TITLE
Commit 80987f14289ed45458c4ef2bcad5ab8baaeae151 broke @type/fs-extra

### ISSUE THREAD

**Issue by Godzil** [DefinitelyTyped/DefinitelyTyped#26460]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/fs-extra` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @KSXGitHub 

With Typescript 2.9.1

```
$ tsc -v
Version 2.9.1
```

Submission 80987f14289ed45458c4ef2bcad5ab8baaeae151 broke support of `@types/fs-extra`:

```
$ npm run compile

> crunchy@1.3.1 compile /.../Crunchy
> tsc

node_modules/@types/fs-extra/index.d.ts:210:94 - error TS2694: Namespace '"fs".symlink' has no exported member 'Type'.

210 export function symlink(srcpath: string | Buffer, dstpath: string | Buffer, type: fs.symlink.Type | undefined, callback: (err: NodeJS.ErrnoException) => void): void;
                                                                                                 ~~~~


node_modules/@types/fs-extra/index.d.ts:212:95 - error TS2694: Namespace '"fs".symlink' has no exported member 'Type'.

212 export function symlink(srcpath: string | Buffer, dstpath: string | Buffer, type?: fs.symlink.Type): Promise<void>;
                                                                                                  ~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! crunchy@1.3.1 compile: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the crunchy@1.3.1 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by KSXGitHub** [comment]
I already created https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26381 to fix this issue. In the meantime, I can either pin your `@types/fs-extra` version or update `@types/node`.

**Comment by Roopa-Siddaveerappa** [comment]
Any update on above  issue

**Comment by KSXGitHub** [comment]
@Roopa-Siddaveerappa As I said above, I created https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26381 so this is no longer my concern. You should subscribe to said pull request if you want to hear any update.

**Comment by Ccz-Chen** [comment]
Any update on the issue?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
