### ISSUE TITLE
@types/node missing fs.constants.COPYFILE_FICLONE

### ISSUE THREAD

**Issue by JeffJacobson** [DefinitelyTyped/DefinitelyTyped#26534]
Not all of the [constants](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_file_copy_constants) are defined in the type definition file for node.

Below is the script I was writing when I encountered the issue. (I had to cast `constants` as `any` in order to work around the issue.)

```typescript
/**
 * Copies CSS files from the node_modules directory to the css directory.
 */
import { constants, copyFile } from "fs";
import { resolve } from "path";

const [source, dest] = [
  "../node_modules/dialog-polyfill/dialog-polyfill.css",
  "../css/"
].map(relpath => {
  return resolve(__dirname, relpath);
});

const outCssFile = resolve(dest, "dialog-polyfill.css");

// Copy the file, overwriting if it already exists.
copyFile(source, outCssFile, (constants as any).COPYFILE_FICLONE, err => {
  if (err) {
    console.error("Copy file error", err);
  }
});

```

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond. If you do not mention the authors the issue will be ignored.

## Authors
- @parambirs
- @tellnes
- @WilcoBakker
- @octo-sniffle
- @smac89
- @Flarna
- @mwiktorczyk
- @wwwy3y3
- @DeividasBakanas
- @kjin
- @alvis
- @eps1lon
- @Hannes-Magnusson-CK
- @jkomyno
- @ajafff
- @hoo29
- @n-e
- @brunoscheufler
- @mohsen1
- @KSXGitHub
- @a-tarasyuk
- @islishude
- @r3nya

**Comment by Flarna** [comment]
Agree. Could you create a PR?

**Comment by JeffJacobson** [comment]
@Flarna, I could create a pull request, but I will not have time to do so for quite a while.

**Comment by JeffJacobson** [comment]
I'm working on a pull request now.
