### ISSUE TITLE
whether @types/gsap needs update

### ISSUE THREAD

**Issue by Renhj90520** [DefinitelyTyped/DefinitelyTyped#26532]
Hi, I tried using the `@types/gsap` package and had problems.
gsap suggests that import CSSPlugin as following 
import { CSSPlugin } from "gsap/all";  or import CSSPlugin from 'gsap/CSSPlugin'
I do this in my angular 4 project, but it seems not working, and gsap is already at version 2.0.1, is this one needed update?
@codeBelt  @ProbablePrime

**Comment by ProbablePrime** [comment]
@Renhj90520 Yes, it would need an update to support this. 

Unfortunately the way things are configured right now each plugin will need types added to: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gsap/Plugins.d.ts

GSAP has a ton of plugins and when i did the last update I only touched ones I was used or that were already present.

**Comment by Gabb1995** [comment]
Do Types help with tree shaking when using the build optimizer? Because I'm trying to use GSAP in my Angular 7 project and with build optimizer enabled I keep getting that TimelineLite is not a constructor.

**Comment by ZachSaucier** [comment]
GSAP 3 now has its own official Typescript definitions included in the package. Please post issues on [the official GSAP repo](https://github.com/greensock/GSAP).
