### ISSUE TITLE
@types/dc should reference the type file supplied by crossfilter

### ISSUE THREAD

**Issue by phyratokar** [DefinitelyTyped/DefinitelyTyped#26548]
- [x] I tried using the `@types/dc` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @hansrwindhoff @mtraynham @MatthiasJobst 

Dc has crossfilter2 as a dependency, which supplies their own type file, but @types/dc still uses the type file from @types/crossfilter. Could someone that knows how to do it change this?

**Comment by hansrwindhoff** [comment]
We are not using the crossfilter types in the definition file, only in the tests, So I removed the reference from the def file.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26608

**Comment by phyratokar** [comment]
Ah ok, sorry my mistake. I saw in my packacke-lock.json that @types/crossfilter is a requirement of @types/dc and assumed that it is a dependency. I'll close this issue then. Thanks for the quick response!
