### ISSUE TITLE
React-native having conflict with dom, impacting react native web projects

### ISSUE THREAD

**Issue by VincentLanglet** [DefinitelyTyped/DefinitelyTyped#26616]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @huhuanming @iRoachie @timwangdev @kamal @nelyousfi @alexdunne @swissmanu @bm-software @tkrotoff @a-tarasyuk 

Hello, I have a project for mobile and web using react native and react native web.

In my "web" code, I am using "window" or "document" and there is no typing in the @types/react-native for this ; this is normal because this should not be used for full react-native project. 
I try to add the "dom" type in my tsconfig but I have conflict with the @types/react-native ones.

Did you find a solution or is this an issue ?

**Comment by VincentLanglet** [comment]
Any advice ?

**Comment by alloy** [comment]
> Did you find a solution or is this an issue ?

Sorry, I’d love to help but haven’t run into the situation myself.

I’m thinking that maybe you need different configs for the two platforms.

> But in fact, I realize I don't know why RN types has defined the same than the dom lib...

Because React typings expect those to exist, so they need to be stubbed out so the RN typings can be used without needing to load the full dom ones.
