### ISSUE TITLE
- [@types/angular-mocks] Recent pull request causes breaking changes.

### ISSUE THREAD

**Issue by kylegalloway** [DefinitelyTyped/DefinitelyTyped#26641]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/angular-mocks` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @thorn0, @diegovilar, @daltin 

When updating from `@types/angular-mocks@1.5.9` to `@types/angular-mocks@latest`, tests using `respond` started failing due to a type mismatch. I tracked it down to the recent PR #26248 that updated the `respond` method. It changed the typing of the 2nd version of it from 
```
respond(status: number, data: string | Object, headers?: Object, responseText?: string): IRequestHandler;
```
to 
```
respond(
        status: number,
        data: string | object,
        headers?: IHttpHeaders,
        responseText?: string
      ): IRequestHandler;
```
This looks innocent enough, however, changing the data parameter's type from `string | Object` to `string | object` (notice the big `O` versus the little `o`) stops a user from being able to pass null into `respond` as the data parameter. This is a breaking change that unfortunately broke my previously working suite of tests. This stops me from updating to the newest version of @types/angular-mocks.

**Comment by thorn0** [comment]
While [the documentation](https://docs.angularjs.org/api/ngMock/service/$httpBackend#when) actually says that `data` can only be an array, an object, or a string, yours is definitely a valid use case, so the docs and the type definitions should reflect that. Feel free to submit respective PRs. (In the definitions, let's add `| null` to `string | object`.)

**Comment by kylegalloway** [comment]
Closing this, I've put in a PR to fix this issue. Please let me know if something else needs to be done here.
