### ISSUE TITLE
[@types/geojson] MultiLineString is missing from GeoJson Geometry type

### ISSUE THREAD

**Issue by AndyPowell32** [DefinitelyTyped/DefinitelyTyped#26663]
The Geometry type is missing the MultiLineString option:

export type Geometry = Point | MultiPoint | LineString | Polygon | MultiPolygon | GeometryCollection;

@JeffJacobson @andy-ms @atd-schubert @icholy @denisname @weswigham @sheetalkamat @woutervh-

**Comment by icholy** [comment]
Are you going to open a PR?

**Comment by AndyPowell32** [comment]
@icholy _>> Are you going to open a PR?_

I'm hoping that someone who is familiar with the process will do that
