### ISSUE TITLE
[@types/knockout] All implementers of KnockoutExtensionFunctions are type-unsafe.

### ISSUE THREAD

**Issue by aakasaka** [DefinitelyTyped/DefinitelyTyped#26660]
- [x] I tried using the `@types/knockout` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @Igorbek @moonpyk @EnableSoftware @BenjaminEckardt @ffMathy

If you do not mention the authors the issue will be ignored.

---

I saw #17290. I think it's not good.
`KnockoutExtensionFunctions` has a index signature that returns `any` value. This makes all implementers type-unsafe, because the compiler won't warn any typos.

```
var o = ko.observable(0);
o.iCanTypeAnything();

var c = ko.computed(() => o());
c.peeeeek();
```

**Comment by Igorbek** [comment]
This indeed does seem wrong. I think the fix would be just to remove index signature altogether.
Any implementations of extension functions just need to extend the interface if they need.
Please feel free to submit a PR or wait somebody to pick it up.

**Comment by aakasaka** [comment]
Thanks, I submitted #26683. However, did you mean to remove not the `KnockoutExtensionFunctions` interface but the index signature only? If so, I'll fix it.

**Comment by aakasaka** [comment]
Thank you for approving.
