### ISSUE TITLE
[@types/pixi.js] Update package

### ISSUE THREAD

**Issue by ilya-klindukhov** [DefinitelyTyped/DefinitelyTyped#26666]
Hi.

Could you deploy new version ( 4.8.1) of `@types/pixi.js` to npm registry?
Types definition for this version already exists in https://github.com/pixijs/pixi-typescript  
 
  - Authors: @clark-stevenson

Thank you.

**Comment by clark-stevenson** [comment]
@sandersn kindly merged the PR and this issue is resolved.

**Comment by ilya-klindukhov** [comment]
Thanks for the operative solution of the problem
