### ISSUE TITLE
[lodash] Error in findLast definition

### ISSUE THREAD

**Issue by Alexsey** [DefinitelyTyped/DefinitelyTyped#26680]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel, @chrootsu, @stepancar, @aj-r, @ailrun, @e-cloud, @thorn0, @jtmthf, @DomiR

Consider code
```js
_.findLast([1, 2, 3], v => v % 2)
```
It is 100% currect but type definition has some problems with it saying
```
Argument type function(*): number is not assignable to parameter type ListIterateeCustom  | undefined
...
  Type function(*): number is not assignable to type ListIterateeCustom
    Type function(*): number is not assignable to type ((value: number, index: number, collection: List ) => boolean) | string | [string , any] | {[P in keyof number]?: PartialDeep }
      Type function(*): number is not assignable to type {[P in keyof number]?: PartialDeep } 
```
As it says in the docs (for `find` because docs of `findLast` refers to docs for `find`)
```
Iterates over elements of collection, returning the first element predicate returns truthy for. The predicate is invoked with three arguments: (value, index|key, collection).
```
Where `truly` means ANY. It's not `true`. So all return value should be acceptible

**Comment by thorn0** [comment]
It is a [known language-level issue](https://github.com/Microsoft/TypeScript/issues/19456). There is a tradeoff to be found here between type strictness and type coercions. Some (myself included) prefer the former, some (like you) the latter. At the same time, I am somehow okay (got used to, I guess) with the fact that expressions in `if` statements don't have to be striclty boolean in TypeScript while I can easily imagine people wanting that.

**Comment by Alexsey** [comment]
I understand that generally there is arguable situation about truly/falsy values and how to type them, but here we have a spec that explicitly says `truly`. And I think we should follow the spec

**Comment by thorn0** [comment]
I believe many would disagree with you on that. E.g. see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20795#discussion_r147290556

**Comment by Alexsey** [comment]
In this case, as a JS user that is using TypeScript definitions through IDE for additional code checks, I have no choice than just disable these inspections. Because in JS code conversion of return type to boolean looks stupid
