### ISSUE TITLE
[@types/webpack] Loader context missing loadModule method

### ISSUE THREAD

**Issue by cleavera** [DefinitelyTyped/DefinitelyTyped#26691]
- [x] I tried using the `@types/webpack` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @bumbleblym @bcherny @tommytroylin @mohsen1 @jcreamer898 @ahmed-taj @alan-agius4 @elliottsj @jason0x43 @dennispg @christophehurpeau

The types for loader context seem to be missing definitions for the loadModule method.
https://webpack.js.org/api/loaders/#this-loadmodule

**Comment by mohsen1** [comment]
This shouldn't be too bad to add. Please make a pull request
