### ISSUE TITLE
@types/fs-extra -- fs.symlink.Type is not defined

### ISSUE THREAD

**Issue by breathe** [DefinitelyTyped/DefinitelyTyped#26730]
```
node_modules/@types/fs-extra/index.d.ts:210:94 - error TS2694: Namespace '"fs".symlink' has no exported member 'Type'.

210 export function symlink(srcpath: string | Buffer, dstpath: string | Buffer, type: fs.symlink.Type | undefined, callback: (err: NodeJS.ErrnoException) => void): void;
                                                                                                 ~~~~


node_modules/@types/fs-extra/index.d.ts:212:95 - error TS2694: Namespace '"fs".symlink' has no exported member 'Type'.

212 export function symlink(srcpath: string | Buffer, dstpath: string | Buffer, type?: fs.symlink.Type): Promise<void>;
                                                                                                  ~~~~

```

```
> npm ls @types/fs-extra
ai-services@1.0.0 /Users/bcohen/software/masslight/ai_services
└── @types/fs-extra@5.0.3
```

@KSXGitHub -- This commit seems to have added the not-globally-available type ...?  https://github.com/DefinitelyTyped/DefinitelyTyped/commit/80987f14289ed45458c4ef2bcad5ab8baaeae151

Does fs-extra require a particular version of `@types/node` -- I'm currently using `@types/node@9.6.5`?

- [X ] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @KSXGitHub

If you do not mention the authors the issue will be ignored.

**Comment by KSXGitHub** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26381

**Comment by KSXGitHub** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26381

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
