### ISSUE TITLE
[@types/jest] toMatchSnapshot has to be updated to new type signature

### ISSUE THREAD

**Issue by andys8** [DefinitelyTyped/DefinitelyTyped#26746]
`toMatchSnapshot` is expecting an optional `string`.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/954ee278de2931e65309800c0bb8b6da362920af/types/jest/index.d.ts#L477

This was changed with Jest `v23`. 
`.toMatchSnapshot(propertyMatchers, snapshotName)`
https://facebook.github.io/jest/blog/#snapshot-property-matchers
https://facebook.github.io/jest/docs/en/expect.html#tomatchsnapshotpropertymatchers-snapshotname

**Comment by Adverbly** [comment]
Hey - Typescript noobie here. Any temporary workaround for this?

**Comment by andys8** [comment]
Really temporary workaround is `@ts-ignore`. I added a PR because this issue is still open and should be solved.

**Comment by andys8** [comment]
PR merged :)
