### ISSUE TITLE
[@types/bull] Some properties are missing from Job Definition

### ISSUE THREAD

**Issue by swayam18** [DefinitelyTyped/DefinitelyTyped#26742]
The Job interface seems to be missing the following properties:

```
name: string,
progress?: number
delay?: number
timestamp: number
finishedOn?: number
processedOn?: number
```

Is this intentional? Or has it just not been defined yet.

- [x] I tried using the `@types/bull` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: Authors: @bgrieder , @JProgrammer , @marshall007, @weeco, @blaugold, @iamolegga, @koblas

**Comment by koblas** [comment]
I don't think there is any intention -- though I notice that at least ```delay``` might be obsolete.

https://github.com/OptimalBits/bull/blob/1c01719232e954a37ac362ff062e75c6422488a5/lib/job.js#L130

**Comment by swayam18** [comment]
Ah great, then I can create a pull request to include the non deprecated properties. Thanks

**Comment by danmana** [comment]
These seem like private fields and are not described by the [reference documentation](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md); the only fields mentioned in the docs are `id` and `data`, and maybe `name`.

These fields do apear to be part of the JSON representation of the Job - [see toJSON](https://github.com/OptimalBits/bull/blob/master/lib/job.js#L122), but this method is not documented anywhere.

The `progress` field is actually internally stored as [`_progress`](https://github.com/OptimalBits/bull/blob/master/lib/job.js#L37) as there is already a method called [`progress`](https://github.com/OptimalBits/bull/blob/master/lib/job.js#L106)

I'm not familiar with the library, how common is it to actually use these fields?
If it's a common scenario, perhaps we should add them (and maybe make a pull request to the library to update the reference docs)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
