### ISSUE TITLE
[@types/xmldom] Error:(13, 16) TS2304: Cannot find name 'DOMImplementation'.

### ISSUE THREAD

**Issue by khusamov** [DefinitelyTyped/DefinitelyTyped#26745]
Compile-time errors:
```
Error:(13, 16) TS2304: Cannot find name 'DOMImplementation'.
Error:(26, 64) TS2304: Cannot find name 'Document'.
Error:(30, 33) TS2304: Cannot find name 'Node'.
```

Screenshot:
![image](https://user-images.githubusercontent.com/4146998/41771792-e5cc5f24-761e-11e8-8438-d0077bcbb96e.png)

- [x] I tried using the `@types/xmldom` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/). 
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo

**Comment by sudo-suhas** [comment]
Faced same issue. Furthermore, because of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/26218, II cannot enable dom lib typngs.

**Comment by tete17** [comment]
Any updates/workarounds?

**Comment by karfau** [comment]
The changes applied in the PR should also work as a workaround as long as the PR has not been merged. I hope it still helps/is still relevant.
