### ISSUE TITLE
[@types/jest] expect(...).toThrowError does not accept an Error instance

### ISSUE THREAD

**Issue by dbkaplun** [DefinitelyTyped/DefinitelyTyped#26756]
`expect(...).toThrowError` does not accept an `Error` instance, so this fails.
```ts
export const exportedErr = new Error(); // elsewhere

expect(Math.random).toThrowError(exportedErr);
// [ts]
// Argument of type 'Error' is not assignable to parameter of type 'string | RegExp | Constructable | undefined'.
//   Type 'Error' is not assignable to type 'Constructable'.
//     Type 'Error' provides no match for the signature 'new (...args: any[]): any'.
```

Here is the bug: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4ca75191c795850da4fab102a083302eb2c5fd1f/types/jest/index.d.ts#L566-L570

---

- [x] I tried using the `@types/jest` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @ahnpnl @joshuakgoldberg @UselessPickles @r3nya @hotell

**Comment by Hotell** [comment]
I don't think that is supported by jest. You can assert against constructor, not against instance

```ts
export const exportedErr = new Error(); // elsewhere

expect(Math.random).toThrowError(Error);
```

**Comment by Hotell** [comment]
ok I double checked, jest supports also error instances 

https://github.com/facebook/jest/blob/48560bf52fa9d587f302d4d8512e7f7c8038f8c5/packages/expect/src/to_throw_matchers.js#L26
