### ISSUE TITLE
How To Unsubscribe From TypescriptBot?

### ISSUE THREAD

**Issue by willisplummer** [DefinitelyTyped/DefinitelyTyped#26817]
I've made a few minor contributions but I'm not really working with Typescript anymore.. Is there a way to get the TypescriptBot out of my mentions 🙏

**Comment by weeco** [comment]
Probably the only way is to submit another pull request where you remove yourself as author.

**Comment by RyanCavanaugh** [comment]
Yep, we'll approve any PR to remove yourself from the definition header.

You can also just go for the nuclear option and block the bot :wink:

**Comment by willisplummer** [comment]
Thanks! Just blocked it :)
