### ISSUE TITLE
webdriverio: elementIdDisplayed(id: ElementId) has been marked as deprecated

### ISSUE THREAD

**Issue by buaban** [DefinitelyTyped/DefinitelyTyped#26841]
I want to filter elements by visibility. But it does not work. `elementIdDisplayed` is always true.

Here is my code.

```
const isDisplayed = await browser.elementIdDisplayed(elem.ELEMENT);
if(isDisplayed) {
    console.log('IT IS DISPLAYED');
}
```

All the elements log 'IT IS DISPLAYED' although some of them are hidden.
I have found that the root cause is that the real result is in `isDisplayed.value`. But typescript does not allow me to call it because the method in `index.d.ts` has been deprecated. So the return type is `never`.

`elementIdDisplayed(id: ElementId): Client<RawResult<boolean>> & RawResult<boolean> & never;`

I use a workaround as follows, now typescript allows me to call property value, and it works properly now. The hidden elements won't print the sentence.
```
const isDisplayed: any = await browser.elementIdDisplayed(elem.ELEMENT);
if(isDisplayed.value) {
    console.log('IT IS DISPLAYED');
}
```

Can you explain why the method is deprecated? 
If it is an accident, I can fix it for you.
@nmalaguti @timbru31 @fsmedberg-tc @phil-lgr @tanvirislam06

types/webdriverio: 4.10.3
spectron: 3.8.0
chrome: 67
chromedriver: 2.40
os: mac 10.13.5

**Comment by timbru31** [comment]
Good catch. Looking at the W3C spec, it's stated that this is not part of the spec (see https://www.w3.org/TR/webdriver/#element-displayedness). @christan-bromann, can you assist? :) - the https://github.com/webdriverio/webdriverio/blob/master/lib/protocol/elementIdDisplayed.js method is not marked as deprecated.

**Comment by christian-bromann** [comment]
Not sure why it is marked as deprecated. This command will change in v5 anyway as we assign new names to protocol commands (e.g. https://github.com/webdriverio/v5/blob/master/packages/webdriver/protocol/webdriver.json#L295-L305). In v4 elementIdDisplayed is a protocol command and the value is accessed by calling `result.value`.

**Comment by uniqueiniquity** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32490
