### ISSUE TITLE
not work with ionic3 

### ISSUE THREAD

**Issue by dc165015** [DefinitelyTyped/DefinitelyTyped#26850]
I posted this issue to stackoverflow: https://stackoverflow.com/questions/51021605/types-meteor-not-working-with-angular-ionic

I created a new ionic3 project and then installed @type/meteor package by following steps: 
1. ionic start myproject blank --no-link 
2. cd myproject
3. npm i @types/meteor
4. ionic serve
Then, it always got lots of errors all about mongo.d.ts:

[17:54:42] typescript: node_modules/@types/meteor/mongo.d.ts, line: 49 ';' expected.

  L48:  $all?: T[],
  L49:  $elemMatch?: T extends {} ? Query<T> : FieldExpression<T>,
  L50:  $size?: number,
[17:54:42] typescript: node_modules/@types/meteor/mongo.d.ts, line: 49 Property or signature expected.

  L48:  $all?: T[],
  L49:  $elemMatch?: T extends {} ? Query<T> : FieldExpression<T>,
  L50:  $size?: number,
[17:54:42] typescript: node_modules/@types/meteor/mongo.d.ts, line: 49 Declaration or statement expected.

  L48:  $all?: T[],
  L49:  $elemMatch?: T extends {} ? Query<T> : FieldExpression<T>,
  L50:  $size?: number,
[17:54:42] typescript: node_modules/@types/meteor/mongo.d.ts, line: 49 '(' expected.

  L48:  $all?: T[],
  L49:  $elemMatch?: T extends {} ? Query<T> : FieldExpression<T>,
  L50:  $size?: number,
[17:54:42] typescript: node_modules/@types/meteor/mongo.d.ts, line: 49 Expression expected.

  L48:  $all?: T[],
  L49:  $elemMatch?: T extends {} ? Query<T> : FieldExpression<T>,
  L50:  $size?: number,
[17:54:42] typescript: node_modules/@types/meteor/mongo.d.ts, line: 50 Expression expected.

  L49:  $elemMatch?: T extends {} ? Query<T> : FieldExpression<T>,
  L50:  $size?: number,
  L51:  $bitsAllClear?: any,
[17:54:42] typescript: node_modules/@types/meteor/mongo.d.ts, line: 51 Expression expected.

  L50:  $size?: number,
  L51:  $bitsAllClear?: any,
  L52:  $bitsAllSet?: any,
[17:54:42] typescript: node_modules/@types/meteor/mongo.d.ts, line: 52 Expression expected.

  L51:  $bitsAllClear?: any,
  L52:  $bitsAllSet?: any,
  L53:  $bitsAnyClear?: any,
[17:54:42] typescript: node_modules/@types/meteor/mongo.d.ts, line: 53 Expression expected.

  L52:  $bitsAllSet?: any,
  L53:  $bitsAnyClear?: any,
  L54:  $bitsAnySet?: any,
[17:54:42] typescript: node_modules/@types/meteor/mongo.d.ts, line: 54 Expression expected.

  L53:  $bitsAnyClear?: any,
  L54:  $bitsAnySet?: any,
  L55:  $comment?: string
[17:54:42] typescript: node_modules/@types/meteor/mongo.d.ts, line: 55 Expression expected.

  L54:      $bitsAnySet?: any,
  L55:      $comment?: string
[17:54:42] typescript: node_modules/@types/meteor/mongo.d.ts, line: 56 ',' expected.

  L55:          $comment?: string

and many lines of similar errors followed...

meteor version: @1.7.0.3 or @1.6.0 ; 
node version: @8.11.3; 
npm version: 5.6.0; 
macOS version: 10.13.5

package.json content:
```
{

  "name": "myproject",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "4.7.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "4.7.0",
    "@ionic/storage": "2.1.3",
    "@types/meteor": "^1.4.16",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.10",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project"
}
```

tsconfig.json content:
```
    {
      "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "declaration": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": [
          "dom",
          "es2015"
        ],
        "module": "es2015",
        "moduleResolution": "node",
        "sourceMap": true,
        "target": "es5"
      },
      "include": [
        "src/**/*.ts"
      ],
      "exclude": [
        "node_modules",
        "src/**/*.spec.ts",
        "src/**/__tests__/*.ts"
      ],
      "compileOnSave": false,
      "atom": {
        "rewriteTsconfig": false
      }
    }
```

Any idea? I was stuck with this for days...

**Comment by dc165015** [comment]
I checkout backward to package-lock.json history which is working in another project, it seems some minor dependencies changed

**Comment by woeller-klindo** [comment]
I had the same problem. Using 

`"typescript": "~2.9.2",`

instead of

`    "typescript": "~2.6.2",`

solved the problem for me.

**Comment by dc165015** [comment]
It is not a problem related to types, it's meteor's.

**Comment by lilian131** [comment]
@dc165015 hi did you figure out the problem ?

**Comment by dc165015** [comment]
@lilian131 I always ran into this issue when ionic and meteor share the same node_module directory and package.json, also package-lock.json. 

Since I seperated them, that is, use independent, not linked files, the error was gone forever.
