### ISSUE TITLE
"Subsequent variable declarations must have the same type with" @types/mocha@5.2.3

### ISSUE THREAD

**Issue by mrwillis** [DefinitelyTyped/DefinitelyTyped#26863]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/mocha@5.2.3` package and had problems:

I run `tsc` and receive this error:

```
node_modules/@types/mocha/index.d.ts:2646:9 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'before' must be of type 'any', but here has type 'HookFunction'.

2646     var before: Mocha.HookFunction;
             ~~~~~~
```

Any ideas?

`tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "lib": [
      "ES2015"
    ],
    "sourceMap": true,
    "strict": true,
    "types": [
      "node",
      "mocha"
    ],
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  }
}
```

- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (`v2.9.2`)
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kazimanzurrashid, @otiai10, @jt000, @enlight @cspotcode @1999 

If you do not mention the authors the issue will be ignored.

**Comment by mrwillis** [comment]
Sorry for the ping, completely unrelated issue.

**Comment by eljenso** [comment]
@mrwillis Getting similar errors. How did you fix it?

**Comment by cspotcode** [comment]
Hit Shift+F12 to "find all references" and see where `before` is declared.
It appears to be declared multiple times, but it should only be declared
once by the mocha declarations.
