### ISSUE TITLE
react-redux: connect() accepts class components which render an array of elements, but not functional components which render an array of elements

### ISSUE THREAD

**Issue by tomjakubowski** [DefinitelyTyped/DefinitelyTyped#26867]
- [X] I tried using the `@types/react-redux` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @thasner @clayne11 @tansongyang @NicholasBoll @mDibyo @pdeva 

Since React 16, components are allowed to [return an array of elements when rendering](https://reactjs.org/blog/2017/09/26/react-v16.0.html#new-render-return-types-fragments-and-strings). The `react-redux` types, though, only allow `connect()` to be used with such a class component; I cannot find a way to satisfy the type checker using a functional component. A short example, using `@types/react-redux` 6.0.3 and `@types/react` 16.4.2

```
import * as React from 'react';
import { connect } from 'react-redux';

interface Props {
  names: string[]
}

function FunkyComponent({ names }: Props) {
  return names
    .map((name, idx) => <h1 key={idx}>Hello {name}!</h1>);
}

class ClassyComponent extends React.Component<Props> {
  public render() {
    return this.props.names.map((name, idx) => <h1 key={idx}>Hello {name}!</h1>);
  }
}

interface AppState {
  friends: string[]
}

function mapStateToProps({ friends }: AppState): Props {
  return {
    names: friends
  };
}

const Container = connect(mapStateToProps)(FunkyComponent);
```

This fails with:

```
Argument of type '({ names }: Props) => Element[]' is not assignable to parameter of type 'ComponentType<Props>'.
  Type '({ names }: Props) => Element[]' is not assignable to type 'StatelessComponent<Props>'.
    Type 'Element[]' is not assignable to type 'ReactElement<any> | null'.
      Type 'Element[]' is not assignable to type 'ReactElement<any>'.
        Property 'type' is missing in type 'Element[]'.
```

A change of `FunkyComponent` to `ClassyComponent` on the last line passes the type checker. Seems like both cases ought to.

**Comment by tomjakubowski** [comment]
One workaround with sufficiently recent JSX is to wrap the array in `<>`, or with older JSX `<React.Fragment>`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
