### ISSUE TITLE
[@types/react] return array without fragments

### ISSUE THREAD

**Issue by vanyathecyborg** [DefinitelyTyped/DefinitelyTyped#26890]
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @morcerf, @tkrotoff, @DovydasNavickas, @onigoetz, @theruther4d, @guilhermehubner, @ferdaber, @jrakotoharisoa

I've had issues typing components that return array without Fragments like this:
```
Type '({ slides }: Props & { children?: ReactNode; }) => Element[]' is not assignable to type 'StatelessComponent<Props>'.
Type 'Element[]' is not assignable to type 'ReactElement<any>'.
        Property 'type' is missing in type 'Element[]'.
```

```javascript
type SlideItem = {
    id: number,
    url: string,
    type: string,
    title: string,
}

interface Props {
    slides: Array<SlideItem>
}

const Slide : React.SFC<Props> = ({ slides }) => (
    slides.map(item => (
        <Image
            key={item.id}
            url={item.url}
        >
            <StyledSlide>
                <Heading
                    uppercase
                    mono
                    size="M"
                >
                    {item.type}
                </Heading>
                <Heading
                    uppercase
                    mono
                    size="XL"
                    marginTop={25}
                >
                    {item.title}
                </Heading>
            </StyledSlide>
        </Image>
    ))
);
```

If I wrap this in a Fragment, then it works:
```javascript
<Fragment>
		{slides.map(item => (
                    ...
		))}
	</Fragment>
```

**Comment by Kovensky** [comment]
This is a TypeScript issue because functions are treated especially by the compiler; this is the bug tracking it: https://github.com/Microsoft/TypeScript/issues/21699

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
