### ISSUE TITLE
[@types/recompose] error TS2709: Cannot use namespace 'ObservableConfig' as a type.

### ISSUE THREAD

**Issue by rosskevin** [DefinitelyTyped/DefinitelyTyped#26959]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/recompose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @iskandersierra @mrapogee @clayne11 @Pajn @lucasterra

I'm not using these @types/recompose directly, I'm getting them transitively from the latest `material-ui-pickers`, which is using the latest @types/recompose@0.26.1.  They are failing during a build with:

```sh
$ tsc -d --project tsconfig.build.json
../../node_modules/@types/recompose/index.d.ts(402,23): error TS2709: Cannot use namespace 'ObservableConfig' as a type.
../../node_modules/@types/recompose/index.d.ts(412,24): error TS2709: Cannot use namespace 'ObservableConfig' as a type.
../../node_modules/@types/recompose/index.d.ts(422,23): error TS2709: Cannot use namespace 'ObservableConfig' as a type.
../../node_modules/@types/recompose/index.d.ts(432,26): error TS2709: Cannot use namespace 'ObservableConfig' as a type.
../../node_modules/@types/recompose/index.d.ts(442,24): error TS2709: Cannot use namespace 'ObservableConfig' as a type.
../../node_modules/@types/recompose/index.d.ts(452,24): error TS2709: Cannot use namespace 'ObservableConfig' as a type.
```
Which refers to:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/recompose/index.d.ts#L398-L455

It is occurring with the absolute latest typescript@2.9.2 and @types/recompose@0.26.1.  I have no idea why otherwise I would pitch in - I don't spot the error.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
