### ISSUE TITLE
Can't use namespaces from sinon/index.d.ts

### ISSUE THREAD

**Issue by sripberger** [DefinitelyTyped/DefinitelyTyped#26997]
I'm having difficulty getting access to sinon type information from my tests in Node.js. Importing like so:

`const sinon: Sinon.SinonStatic = require('sinon');`

produces `Cannot find namespace 'Sinon'.`. Meanwhile this:

`const sinon: sinon.SinonStatic = require('sinon');`

similarly produces `Cannot find namespace 'sinon'.`.

Of course, if I don't provide any type information to to the variable like so:

`const sinon = require('sinon');`

it compiles without error, but then I can't use any typescript features with it.

The problem seems to be related to [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3b761f9d6cfcd1fe4a7955e74f8682d9dd7382eb/types/sinon/index.d.ts#L579), since commenting it out causes expected behavior. Browsing TS documentation I can tell that this kind of thing is used as an equivalent for `module.exports = ` in CommonJS, but I'm unsure what the meaning of such a thing would be in a declarations file.

Any possibility of a fix? Or if this is fine and I'm just using it wrong?

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @MrBigDog2U @rationull @lumaxis @nicojs @43081j @JoshuaKGoldberg

**Comment by nicojs** [comment]
Can you try `import sinon = require('sinon');`. Typings should work with this setup

**Comment by sripberger** [comment]
Hey, that works. Nice.

Looks like it also works with the ES6-style `import * as sinon from 'sinon';`. I suppose the `import` keword is doing some magic that's needed to work with these typings, then?

If so I suppose I'll just close this. Not really a problem, just caught me off guard since I'm new to TS and generally use CommonJS-style modules.

**Comment by nicojs** [comment]
> I suppose the `import` keyword is doing some magic that's needed to work with these typings, then?

Correct. The guys creating TypeScript choose to go with the new ES6 style syntax rather than the CommonJS style, because the CommonJS style really just is a method call, not a language construct. It is much more dynamic than the ES6 module specification so they decided on that module syntax.

I can't close this issue, only DT maintainers and you can do that.

Have fun with TypeScript

**Comment by sripberger** [comment]
Will do. Thanks for your help!
