### ISSUE TITLE
`history`: no way to customise or override `LocationState`

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#27012]
`LocationState` has type `any`:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/566e0394859fdc1dc893658ccec6b06372d56a91/types/history/index.d.ts#L46

There should be a way of customising/overriding this, so we're not forced to cast/validate an `any` type every time we try to use it.

I am currently working around this by patching the types to remove the `LocationState` type, and adding it back in via module augmentation and namespace merging:

``` ts
declare module 'history' {
  namespace History { type LocationState = CustomLocationState; }
}
```

Hopefully one day TS will allow `any` types to be overriden: https://github.com/Microsoft/TypeScript/issues/4062

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sergey-buturlakin @ngbrown @rokoroku 

If you do not mention the authors the issue will be ignored.

**Comment by OliverJAsh** [comment]
I don't think #27699 would quite resolve this issue for instances where we receive a `Location` type for which we can't specify the generic (i.e. it is given to us by a library such as React Router).

**Comment by gwmccull** [comment]
@OliverJAsh I'm using the changes with React Router.  It allows you to specify the shape of the LocationState in the component props

![image](https://user-images.githubusercontent.com/580060/43536397-57d8f73c-9571-11e8-9fa6-a27417f168ba.png)

**Comment by OliverJAsh** [comment]
That works if you're explicitly defining your prop types, but if you're relying on inference, the generic default will be used, e.g.

``` ts
withRouter(props => {
  props.location.state // any
})
```

This is what I meant by "instances where we receive a Location type for which we can't specify the generic".

A way to customise/redefine `History.LocationState` wouldn't suffer from this problem.

**Comment by danielnixon** [comment]
> This is what I meant by "instances where we receive a Location type for which we can't specify the generic".

Not the prettiest, but you could do this:
```
  type MyHistoryState = {
    readonly foo: string;
  };

  withRouter(
    (props: RouteComponentProps<{}, StaticContext, MyHistoryState>) => {
      return <>{props.location.state.foo}</>;
    },
  );
```

**Comment by OliverJAsh** [comment]
> Then you could easily define a `withRouterWithMyHistoryState`.

That's sort of what we've been doing—we've defined wrappers for all types/values which include a reference to `LocationState`—in addition to `withRouter`, there's also `useLocation`, `useHistory`, `History`, `Location`, `LocationDescriptor`, `LocationDescriptorObject`, and `RouteComponentProps`. The problem is: this list is far from complete (I'm sure we're missing some wrappers) and it requires a lot of discipline to make sure the correct wrappers are used. For this reason I'm keen to improve the types so we can just use the built-in types/values, without having to define wrappers. (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41568 is an attempt at doing that.)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
