### ISSUE TITLE
[@types/react-native] Misleading error message in react native

### ISSUE THREAD

**Issue by wilcus** [DefinitelyTyped/DefinitelyTyped#27053]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @huhuanming @iRoachie @timwangdev @kamal @nelyousfi @alexdunne @swissmanu @bm-software @tkrotoff @a-tarasyuk

I set up a javascript project with typescript https://github.com/wilcus/ErrorImage

Here is the relevant code:

```javascript
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  Image
} from 'react-native';

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Image
          source={require('./cake.jpg')}
          resizeMode={'stretch'}
          style={{ flex: 1, width: null }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});
```
When I execute tsc show me this error

```
App.js:17:11 - error TS2326: Types of property 'style' are incompatible.
  Type '{ flex: number; width: null; }' is not assignable to type 'StyleProp<ImageStyle>'.
    Type '{ flex: number; width: null; }' is not assignable to type 'RecursiveArray<false | ImageStyle | RegisteredStyle<ImageStyle> | null | undefined>'.
      Property 'length' is missing in type '{ flex: number; width: null; }'.

17           style={{ flex: 1, width: null }}
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

But the expected error should be 'width is not assignable to type null' 

Error 'length' is misleading

**Comment by alloy** [comment]
This looks like something to take up with the TypeScript project itself, rather than these typings. As such, I’m going to close this.
