### ISSUE TITLE
[@types/joi] turn on strictNullCheks

### ISSUE THREAD

**Issue by jakubzloczewski** [DefinitelyTyped/DefinitelyTyped#27063]
@rokoroku, I see that you have large input in development of typings for joi library so I'm addressing you. 

Do you know if there is plan to make strictNullCheks = true?
Is there any reason against setting it true?

**Comment by rokoroku** [comment]
I agree with setting `strict` flags to true, but I have no idea about its obstacle. 
(Previously I just changed the indentation or generic type parameters, so not setting `strict` flag is not my intention.) 

Have you tried it? Do you get some error after enabling `strict` mode?

**Comment by jakubzloczewski** [comment]
I see.

I haven't tried, but I will try to do this. 

In my project I have strictNullChecks equals true what is good practice but then Joi.ValidationResult should be possibly null in definitions.
