### ISSUE TITLE
Lodash: `mapValues`: incorrect overload is used for object backed by type alias

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#27154]
Currenty, if `mapValues` is given a value whose type is a type alias (instead of an interface), it returns a `Dictionary`, i.e. it loses all information about the object keys. I expect it to return a mapped type, i.e. retain all information about object keys.

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26983

We can't fix this until we can bump the TS version for Lodash typings to 2.9. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26983#issuecomment-403468520.

/cc @aj-r 

``` ts
    const abcObjectRecord: Record<'a' | 'b' | 'c', string> = anything;
    // $ExpectType { a: string; b: string; c: string; }
    _.mapValues(abcObjectRecord, (value, key, collection) => {
        value;  // $ExpectType string
        key; // $ExpectType string
        collection; // $ExpectType Record<"a" | "b" | "c", string>
        return "";
    });
```

```
Error: /Users/OliverJAsh/Development/DefinitelyTyped/types/lodash/lodash-tests.ts:5548:5
ERROR: 5548:5  expect  Expected type to be:
  { a: string; b: string; c: string; }
got:
  Dictionary<string>
ERROR: 5551:9  expect  Expected type to be:
  Record<"a" | "b" | "c", string>
got:
  Dictionary<string>
```

**Comment by tiagoefmoraes** [comment]
If anyone is looking, latest version that don't have this problem is 4.14.104

**Comment by OliverJAsh** [comment]
Now Lodash types have TS 3.1+ support, I raised a fix here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35342.

**Comment by jwalton** [comment]
Well, this broke my build: https://github.com/exegesis-js/exegesis/blob/master/src/options.ts#L85

**Comment by OliverJAsh** [comment]
Unfortunately that is going to happen when types change. If you believe your use case is well justified and can't be migrated, we'll need to investigate with an isolated test case.

**Comment by aj-r** [comment]
@jwalton can you elaborate on what broke? It looks fine to me, but I can't compile it at the moment :)

**Comment by jwalton** [comment]
Oops, I linked to master above and then I fixed it.  :P  This was the broken line: https://github.com/exegesis-js/exegesis/blob/cde90e0e2353e12d6ea6df8c2cf39a8e2d2dca57/src/options.ts#L85

But, I think it was actually broken because my type in the original were, in fact, wrong.  -_-
