### ISSUE TITLE
async autoInject and similar should use task callback argument/parameter for type def

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#27180]
@fenying @jeremyhon  @rlindgren @sasanj 

- [x] I tried using the `@types/xxxx` package and had problems.

I am on tsc 2.9.1, and `@async/types` version: 2.0.49

With this code in mind:

```js

            async.autoInject({

                getLatestVersionFromNPMRegistry(cb: EVCb<RegistryData>) {
                  getLatestVersionFromNPMRegistry(dir, name, cb);
                },

                checkGitStatus(cb: EVCb<GitStatusData>) {
                  getStatus(dir, '<remote>', cb);
                },

                getBranchName(checkGitStatus: any, cb: EVCb<BranchNameData>) {
                  getCurrentBranchName(dir, '<remote>', cb);
                }

              },

              (err, results) => {

                log.info('added the following package name to the map:', name);
                
                map[name] = {
                  name,
                  localVersion: version,
                  npmVersion: results.getLatestVersionFromNPMRegistry.npmVersion,
                  branch: results.getBranchName.branchName,
                  upToDateWithRemote: results.checkGitStatus.upToDateWithRemote,
                  workingDirectoryClean: results.checkGitStatus.workingDirectoryClean,
                  path: dir,

                };

                cb(null);

              });
```

Note that the type def for EVCb is: 
```js
export type EVCb<T> = (err: any, val: T) => void;
```

I am looking for type checking that can occur on the final results object. E.g:

results.getLatestVersionFromNPMRegistry
results.getBranchName.branchName,
results.checkGitStatus.upToDateWithRemote,

`results` seems to be of type `any`...isn't there a way for TS to extract the resolution type from the last argument to each of the task functions?

I see this currently:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/async/index.d.ts#L178

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
