### ISSUE TITLE
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself

### ISSUE THREAD

**Issue by Slessi** [DefinitelyTyped/DefinitelyTyped#27185]
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

The build is timing out for my PR at #27094 - Don't know what would cause this

> Installing to /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/typescript-installs/next...
> Installed!
> Testing...
> 
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
> 
> The build has been terminated

**Comment by leonard-thieu** [comment]
I think this is typically a transient issue. You could try restarting the build by closing and re-opening the PR.

**Comment by Slessi** [comment]
@leonard-thieu Right you are, closing & re-opening fixed it, but pushing new commits (bogus commits with just new lines) would not.

#sigh
