### ISSUE TITLE
Lodash/fp convert method not typed

### ISSUE THREAD

**Issue by toniopelo** [DefinitelyTyped/DefinitelyTyped#27194]
The `convert` function that should be available on each `lodash/fp` exported member is not typed correctly for `mapValues` (the only one I checked but probably others too)

I should be able to do the following:
```js
import { mapValues } from 'lodash/fp'

const mapValuesUncapped = mapValues.convert({ cap: false })
// I get the error => `[ts] Property 'convert' does not exist on type 'LodashMapValues'.`
```

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @aj-r @Ailrun @e-cloud @thorn0 @jtmthf @DomiR

**Comment by aj-r** [comment]
Cool, I didn't know you could use `convert` like that.

However this will be really tricky to implement - it will be really hard (if not impossible) to return the correct function definitions for all of the various combinations of convert parameters (`cap`, `curry`, etc.). Or do you want it to return a generic function type like `(...args: any[]) => any`?

**Comment by toniopelo** [comment]
@aj-r
I actually thought about a full typing of this, I don't think it's so hard to do.
I actually just opened a PR about this, please fell free to take a look and give me a feedback :)
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27224

**Comment by gunar** [comment]
Same problem here with `reduce`.

**Comment by TkDodo** [comment]
Hmm, I am still getting those errors, even though I am using the latest type definitions:

```
import { reduce } from 'lodash/fp'

const reduceWithOutCap = reduce.convert({ cap: false })
```
```
Error:(24, 32) TS2339: Property 'convert' does not exist on type 'LodashReduce'.
```

the interface clearly says:

```
interface LodashReduce extends LodashConvertible {
```

```
interface LodashConvertible {
    convert(options: lodash.ConvertOptions): (...args: any[]) => any;
}
```

so I don't really know what's going on :/ Does anyone have the same issues?

**Comment by toniopelo** [comment]
@TkDodo Yeah, the PR that got merged a few days ago lacks type definitions for typescript 3.1+.
They are in a separate folder and I didn't catch them at the time.

I just submitted another PR to fix this: #45235
So I guess you have to wait for this one to be merged. Review should be pretty fast as I just duplicated my work.

Have a nice day!

**Comment by TkDodo** [comment]
@toniopelo Thanks for the info. I've subscribed to the PR :)

**Comment by JulienDemarque** [comment]
@TkDodo @toniopelo This seems to be still an issue on lodash 4.17.21.

**Comment by toniopelo** [comment]
Yes @JulienDemarque, unfortunatly https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45235 had some issues as you can see in the comments and I didn't have the time to push it forward. The PR is now closed but feel free to take the work from here and reopen a PR mentioning the closed one for history :)
