### ISSUE TITLE
[@types/webdriverio] Property 'getText()' does not exist on type 'Element'

### ISSUE THREAD

**Issue by AnnikaNissen** [DefinitelyTyped/DefinitelyTyped#27190]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/webdriverio` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nmalaguti  @timbru31 @fsmedberg-tc @tanvirislam06 @phil-lgr

If you do not mention the authors the issue will be ignored.

---

**Problem description:**

The following WebdriverIO code works perfectly fine, but VisualStudio Code marks `getText()` as an error with the message "Property 'getText()' does not exist on type 'Element'":
```typescript
browser.elements('.listing-list .listing-tile').value[0].getText();
```
The same is true for e.g. `.click()`. 

When using this code (same functionality/output), no error is shown:
```typescript
$$('.listing-list .listing-tile')[0].getText()
```

**Possible solution**

Probably the return type of `browser.elements('.myElements').value` should be the same as for `$$('.myElements')`.

**Comment by AnnikaNissen** [comment]
@nmalaguti @timbru31 @fsmedberg-tc @tanvirislam06 @phil-lgr

☝️ Does one of you have the possibility to review this?

**Comment by uniqueiniquity** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32490
