### ISSUE TITLE
@types/eslint: Missing properties in eslint.CLIEngine

### ISSUE THREAD

**Issue by jorgegonzalez** [DefinitelyTyped/DefinitelyTyped#27204]
Hi, I am getting several errors due to missing properties in the current type definitions. Specifically:

```
[ts] Namespace '"/Users/jorge/Code/korra/node_modules/@types/eslint/index".CLIEngine' has no exported member 'outputFixes'.

[ts] Property 'options' does not exist on type 'CLIEngine'.
```

These errors show up for the following snippets:

```ts
import { CLIEngine } from 'eslint';

// ...

export default class Engine {
  eslintConfig: CLIEngine.Options;
  CLIEngine: CLIEngine;
  outputFixes: CLIEngine.outputFixes; // First error

// ...

if (fix) {
  this.CLIEngine.options.fix = true; // Second error
}
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/eslint/index.d.ts

- [x] I tried using the `@types/eslint` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @pmdartus, @j-f1, @saadq

Would appreciate any help! And thanks for the work you do!

**Comment by jorgegonzalez** [comment]
Using `eslint@4.19.1` and `@types/eslint@4.16.3` by the way. Not sure if this is the problem.

**Comment by saadq** [comment]
So a few things here...

For the first error, I think the problem might be that you need to use `typeof`:

```
outputFixes: typeof CLIEngine.outputFixes
```

For your second error, you are correct that the `options` instance property in `CLIEngine` is not in the type definition. However, I think that property may only be meant for internal use as there is no documentation for that instance property anywhere. Also, I think the main purpose of the `options` is to configure the `CLIEngine` when creating it. I don't think you would want to change the options after the `CLIEngine` has already been instantiated with the options you pass it. Instead, you should change the `options` object itself _before_ you pass it to `CLIEngine` when doing `new CLIEngine({ ... })`.

---

As a side note, I noticed you have `eslintConfig: CLIEngine.Options;`. Just to mention in case you weren't aware, that the `CLIEngine.Options` object is not 1-1 compatible with an eslint config you may get from an `eslintrc.json`. There are several differences such `CLIEngine.Options` having some additional properties like `allowInlineConfig`, `ignorePattern`, etc. Also, in an eslintrc.json file you have an `env` object like so:

```json
{
  "env": {
    "es6": true,
    "node": true,
    "browser": true
  }
}
```

but with `CLIEngine.Options`, you use a property called `envs` and pass it an array:

```ts
new CLIEngine({
  envs: ['es6', 'node', 'browser'],
  ...
})
```

There is some other stuff like that, so just make sure to check out [the docs](https://eslint.org/docs/developer-guide/nodejs-api#cliengine) if you haven't already.

**Comment by jorgegonzalez** [comment]
Thank you for the detailed response @saadq!

**Comment by jorgegonzalez** [comment]
Why do you need the `typeof CLIEngine.outputFixes` when `CLIEngine: CLIEngine;` works?

**Comment by jorgegonzalez** [comment]
Also I was indeed using `CLIEngine.Options;` incorrectly. I appreciate the clarification, feel free to close this issue.

**Comment by j-f1** [comment]
> Why do you need the `typeof CLIEngine.outputFixes` when `CLIEngine: CLIEngine;` works?

This might be a little confusing, but here’s my attempt at an explanation:

The `CLIEngine` class is both a value (the thing that you use `new` on) and a type (representing *instances* of the `CLIEngine` class). When you try to access one of its properties, you’re using it as a value, so it needs the `typeof` construct to represent the type of that property

**Comment by jorgegonzalez** [comment]
Great explanation @j-f1. Makes sense.

**Comment by jorgegonzalez** [comment]
Again, I appreciate the help!
