### ISSUE TITLE
Don't auto-tag authors after they've removed themselves from files

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DefinitelyTyped/DefinitelyTyped#27268]
Example: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27267

I removed myself as an author from `@types/react` for my own sanity a while back and still get tagged in its issues.

**Comment by RyanCavanaugh** [comment]
Apologies, the review pings are generated from CODEOWNERS and CODEOWNERS isn't automatically updated. I've updated the file and will try to get that file kept more up-to-date

**Comment by JoshuaKGoldberg** [comment]
Thanks :)
