### ISSUE TITLE
[@types/sequelize] Bluebird vs Promise

### ISSUE THREAD

**Issue by ShayBox** [DefinitelyTyped/DefinitelyTyped#27272]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/sequelize` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Thomas-B @nrschultz @todd 

If you do not mention the authors the issue will be ignored.

I realize this is likely a limitation with promises being Bluebird, but because of that I can't await them, even though awaiting them actually does work, and I can't convert them to real promises.
Not sure what you can do about these two problems, but anything would be great. It is very annoying to have to either //ignore or use .then, and very intrusive that I can't convert to a real Promise.

**Comment by todd** [comment]
I need a sample use-case here - I can't recall having problems `await`ing Bluebird promises.

**Comment by todd** [comment]
@ShayBox Did you get your issues worked out? Can this be closed?

**Comment by todd** [comment]
@ShayBox Honestly, this feels like more of a tslint issue than anything.

**Comment by todd** [comment]
@ShayBox It actually looks like you can configure tslint to target different types of Promise libraries, not just the stdlib `Promise`.

https://palantir.github.io/tslint/rules/await-promise/

**Comment by ShayBox** [comment]
Thanks 👍

**Comment by grantila** [comment]
Ugh, my bad, it actually returns bluebird promises, despite the confusing documentation.
