### ISSUE TITLE
@types/npmlog does not work

### ISSUE THREAD

**Issue by littlepiggy03** [DefinitelyTyped/DefinitelyTyped#27296]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/npmlog` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DanielMSchmidt

If you do not mention the authors the issue will be ignored.

According [`npmlog`'s doc](https://github.com/npm/npmlog#readme), `npmlog` is not using ES6-style export, so #25291 is invalid.

This should be the actual one:
```typescript
import * as npmlog from "npmlog";
```

But `@types/npmlog` exports things for this:
```typescript
import npmlog from "npmlog";
```

**Comment by towry** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/npmlog/index.d.ts#L12

`newGroup` need to be added.
