### ISSUE TITLE
Specify @types/node version in @types/atom package.json

### ISSUE THREAD

**Issue by smitchell556** [DefinitelyTyped/DefinitelyTyped#27311]
- [x] I tried using the `@types/atom` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @GlenCFL @smhxx  @lierdakil

Is there a way to specify the @types/node dependency version in @types/atom's package.json? When working with an older version of @types/atom, the dependencies that it pulled caused @types/atom to break because the versions weren't specified and the latest versions were incompatible. package.json isn't in the repo so I assume DefinitelyTyped generates the package.json when it publishes @types/atom?

This may be a DefinitelyTyped problem since other @types packages also don't specify the versions of the dependencies they rely on.

**Comment by GlenCFL** [comment]
There is support for specifying the dependencies of a definition, including the required version, through a package.json file at the definition root. An example of that in practice can be found [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/21badac033c858e50d6c58da3e39b1a5e631692e/types/vue-scrollto/package.json). I believe only dependencies on the whitelist located [here](https://github.com/Microsoft/types-publisher/blob/master/dependenciesWhitelist.txt) can be used here on DefinitelyTyped. We might request for `@types/node` to be added to the list, but we wont be able to retroactively publish new versions for any now broken older versions.

I assume you've already found the solution on your end, which would just be installing the appropriate version of `@types/node`. If you're using a version of `@types/atom` earlier than 1.21, then there will be other dependencies for you to worry about as well.

**Comment by smitchell556** [comment]
Yes, that was the solution I came up with. It's not pretty but it works. I'll close this since it's not really a problem with @types/atom, but the way DefinitelyTyped publishes packages.

Thanks for your time.
