### ISSUE TITLE
Generic type 'ThunkAction' requires 4 type argument(s)

### ISSUE THREAD

**Issue by baroale** [DefinitelyTyped/DefinitelyTyped#27338]
I am getting an error when trying to start my application:

```
/node_modules/@types/redux-testkit/index.d.ts
(34,34): Generic type 'ThunkAction' requires 4 type argument(s).
```

Replacing the line:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b56eb29ea66f803f5c5ae8099f5de354a03968fe/types/redux-testkit/index.d.ts#L34

With the following:
```
export function Thunk(thunkFunc: ThunkAction<any, any, any, any>, extraArg?: any): ThunkTestkit & {
```

seems to resolve the issue.

package.json:

```
{
  "name": "web",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@types/file-saver": "^1.3.0",
    "@types/rc-slider": "^8.2.3",
    "@types/react-redux": "^6.0.3",
    "@types/redux": "^3.6.0",
    "file-saver": "^1.3.8",
    "rc-slider": "^8.6.1",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-redux": "^5.0.7",
    "react-scripts-ts": "2.16.0",
    "redux": "^4.0.0",
    "redux-devtools-extension": "^2.13.5",
    "reselect": "^3.0.1",
    "semantic-ui-css": "^2.3.2",
    "semantic-ui-react": "^0.81.3"
  },
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "@types/jest": "^23.1.2",
    "@types/node": "^10.3.6",
    "@types/react": "^16.4.2",
    "@types/react-dom": "^16.0.6",
    "@types/redux-testkit": "^1.0.0",
    "redux-testkit": "^1.0.6",
    "typescript": "^2.9.2"
  }
}
```

It looks like this was introduced in redux-thunk 2.3.0

**Comment by baroale** [comment]
Created a [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27341)

**Comment by baroale** [comment]
Closing due to merged pull request.

**Comment by vort3xxx** [comment]
@baroale, 

This PR broke my project running redux-thunk 2.2.0.   

    ERROR in [at-loader] ./node_modules/@types/redux-testkit/index.d.ts:34:34
    TS2314: Generic type 'ThunkAction' requires 3 type argument(s)

The dependencies section of `package.json` should have been updated as part of this PR, since they still indicate that `redux-thunk` 2.2.0 is safe, which is no longer true.

**Comment by baroale** [comment]
Closing again. Package.json has been updated.
