### ISSUE TITLE
[mongoose] Add countDocuments() and estimatedDocumentCount()

### ISSUE THREAD

**Issue by alfirin** [DefinitelyTyped/DefinitelyTyped#27369]
In order to be coherent with the mongo driver and mongoose and following this PR : 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27008/files

Could we have the countDocuments() and estimatedDocumentCount() methods in mongoose?

Thanks a lot guys.

CC: @ergoithz, @ethanresnick, @Alorel

**Comment by marcelh-gh** [comment]
@alfirin there is already a PR for this: #27283

**Comment by alfirin** [comment]
Thanks a lot and it has even been merged.
