### ISSUE TITLE
Question about adding new types for @babel/* packages

### ISSUE THREAD

**Issue by mgroenhoff** [DefinitelyTyped/DefinitelyTyped#27384]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @yortus @baxtersa @marvinhagemeister @bcherny

I would like to have/add types for at least some of the `@babel/*` packages but before I start creating PR(s), I want to get other peoples opinions.

`@babel/core` in its current state can be just an alias to/copy of `babel-core` for now. Can I just do something like this or do I need to copy/paste it?
```js
// @babel/core
export * from "babel-core";
```

The version of `babel-types` on NPM is `6` but the version mentioned in the types is `7`. The version of `@babel/types` is `7` so what's going on here? Also `@babel/core` types will depend on `@babel/types` types or should I just import `babel-types`?

I am not really sure on how to move forward so I like to get some thoughts on this.

**Comment by mgroenhoff** [comment]
@marvinhagemeister So do you think I should just copy `babel-types` to `@babel/types` and copy `babel-core` to `@babel/core`?

**Comment by baxtersa** [comment]
I haven't followed this too closely, but as was mentioned in [this other PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26433), the v7 babel-types package (`@babel/types`) comes with its own type definitions that are codegen'd from the AST definitions. Those types should be preferred to duplicating code for `@babel/types` here. The other `@babel/*` packages aren't bundled with types though, so I imagine types for the other v7 packages would be welcome.

**Comment by mgroenhoff** [comment]
@baxtersa That would be nice if we can just import that but I don't know if there is a way to import something that is not in the repo?

**Comment by baxtersa** [comment]
If you add `@babel/types` to `dependencies` in `package.json`, then types are imported with normal import statements from the `@babel/types` package, i.e. types don't _need_ to be published to DefinitelyTyped, and shouldn't be if they're bundled with the npm package.

For example,
### package.json
```json
{
  "dependencies": {
    "@babel/types": "^7.0.0-beta.54"
  }
}
```
### foo.ts
```ts
import { numericLiteral } from '@babel/types';
numericLiteral('foo');        // This doesn't typecheck
numericLiteral(42);           // This typechecks
```

**Comment by mgroenhoff** [comment]
Nice! I did not know that was possible. I can't find any documentation about that feature though but I found an example with a `package.json` in the repo.

**Comment by mgroenhoff** [comment]
Closing because types are merged. Thanks for the feedback!

**Comment by rafaelweinstein** [comment]
It looks like the auto-generated asserts aren't included in the merged type declarations

e.g. `assertExpressionStatement`.
