### ISSUE TITLE
Declaration for customer.list not up to date

### ISSUE THREAD

**Issue by jekel1818** [DefinitelyTyped/DefinitelyTyped#27421]
The declaration file does not seems up to date with the latest documentation for the method: 
    _https://stripe.com/docs/api/node#list_customers_

The doc shows that I should be able to pass an _email_ or a _limit_ has an argument. However, there is no signatures matching those inputs in the declaration file.

![screenshot 2018-07-19 16 42 59](https://user-images.githubusercontent.com/8727739/42968998-d2e2ce3e-8b72-11e8-95c6-a2d7674d5602.png)

**Comment by andy-ms** [comment]
Closed by #27517
