### ISSUE TITLE
@types/jquery jQuery $(img).load() must allow single callback

### ISSUE THREAD

**Issue by GrishaevPavel** [DefinitelyTyped/DefinitelyTyped#27442]
$('<img>').load( function(){} ) is error, but must be ok, because it is an image, not any HTMLElement

- Authors: @leonard-thieu 

( is it ok that i mention you? if not, please say ho to do )

**Comment by leonard-thieu** [comment]
That overload was removed in jQuery 3.0.

https://api.jquery.com/load-event/

> ( is it ok that i mention you? if not, please say ho to do )

Yes. It's perfectly fine to mention me for jQuery related issues.
