### ISSUE TITLE
react-spinkit error: ’Spinner’ only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by coventry** [DefinitelyTyped/DefinitelyTyped#27455]
- [x] I tried using the `@types/react-spinkit` package and had problems.

```
$ tsc --listFiles | grep spinkit
/path/to/my/package/node_modules/@types/react-spinkit/index.d.ts
```

- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
```
$ tsc --version
Version 2.9.2
```
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/). 

How can I use `react-spinkit` in typescript, without getting the above error? Here's an example of a file, `spin.tsx`, where I get the error:

```typescript
import * as React from 'react';
import { Spinner } from 'react-spinkit'

export const MySpinner = () => <Spinner name="circle" />
```

Here is the error I get from `tsc`:

```
$ tsc --jsx react src/components/spin.tsx
src/components/spin.tsx:4:33 - error TS2693: 'Spinner' only refers to a type, but is being used as a value here.

4 export const MySpinner = () => <Spinner name="circle" />
                                  ~~~~~~~
```

Here are the relevant portions of my `package.json`:

```json
{
  "name": "my package",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "enzyme": "^3.3.0",
    "immutable": "^3.8.2",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-modal": "^3.5.1",
    "react-scripts-ts": "2.16.0",
    "react-spinkit": "^3.0.0",
    "redux": "^4.0.0"
  },
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "tslint --project . && react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "*",
    "react-test-renderer": "^16.4.1",
    "@types/jest": "^23.1.5",
    "@types/node": "^10.5.2",
    "@types/react": "^16.4.6",
    "@types/react-dom": "^16.0.6",
    "@types/react-spinkit": "^3.0.0",
    "typescript": "^2.9.2"
  }
}
```
 
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @pelotom  @zzanol

**Comment by coventry** [comment]
Oh, and here is my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
      "lib": ["es6", "es2017", "es2015", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}
```

`"es2017"` and `"es2016"` I just added to `compilerOptions.lib`. I get the same error, with or without them.

**Comment by coventry** [comment]
I found I was able to import without typescript errors using `import * as Spinner from 'react-spinkit'`. So I'm happy enough for now, but maybe there should be something documenting that.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
