### ISSUE TITLE
Asserting non-compiling code in tests file

### ISSUE THREAD

**Issue by zspitz** [DefinitelyTyped/DefinitelyTyped#27536]
If you know how to fix the issue, make a pull request instead.

- [X] I tried <del>using</del> authoring the `@types/activex-word` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

Let's say I have a package with the following declaration:
```
declare class Application {
    PrintOut(OutputFileName: string, PrintToFile: true, StartPage?: number): void;
    PrintOut(OutputFileName?: undefined, PrintToFile?: false, StartPage?: number): void;
}
```
with the following calls being valid:
```
x.PrintOut('abcd', true);
x.PrintOut(undefined, false);
x.PrintOut(undefined, undefined);
x.PrintOut();
```
and the following calls being invalid:
```
x.PrintOut(undefined, true);
x.PrintOut('abcd', false);
x.PrintOut('abcd', undefined);
x.PrintOut('abcd');
```
Now, I would like to try using conditional types to express the same as the aforementioned overloads. I can add the valid calls to the `<package>.tests.ts` file, to ensure that the valid calls remain valid.

How can I assert on the invalid calls in the tests file, to ensure that they remain invalid?

**Comment by andy-ms** [comment]
You could use [`$ExpectError`](https://github.com/DefinitelyTyped/DefinitelyTyped#lint).
