### ISSUE TITLE
React 16.4.7 breaks with react-redux for connect interface

### ISSUE THREAD

**Issue by gyandeeps** [DefinitelyTyped/DefinitelyTyped#27545]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react` and `@types/react-redux` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @andy-ms @pravdomil @RyanCavanaugh @jeremejevs 

### Version

Typescript: 2.9.x
`@types/react`: 16.4.7
`@types/react-redux`: 6.0.5

### Code

```ts
import * as React from "react";
import { Dispatch } from "redux";
import { connect } from "react-redux";

type RootState = {
    x: string;
    y: string;
};

type UserEditOwnProps = {
    isNew?: boolean;
    onCloseEditing: () => void;
};

type UserEditActions = {
    updateUser: () => void;
    updateUser1: () => void;
    updateUser2: () => void;
};

type UserEditStateProps = {
    allRoles: string[];
    allRoles1: string[];
};

type UserEditProps = UserEditOwnProps & UserEditActions & UserEditStateProps;

type UserEditState = {
    isUserValid: boolean;
};

class UserEdit extends React.Component<UserEditProps, UserEditState> {
    constructor(props: UserEditProps) {
        super(props);
        this.state = {
            isUserValid: true
        };
    }

    public static defaultProps: Partial<UserEditProps> = {
        isNew: false
    };

    static getDerivedStateFromProps(
        nextProps: UserEditProps,
        prevState: UserEditState
    ): Partial<UserEditState> | null {
        return null;
    }

    render() {
        return <span>hi</span>;
    }
}

const mapDispatchToProps = (dispatch: Dispatch) => ({
    updateUser: () => null,
    updateUser1: () => null,
    updateUser2: () => null
});

const mapStateToProps = ({ x, y }: RootState) => ({
    allRoles: [x],
    allRoles1: [y]
});

export default connect<
    UserEditStateProps,
    UserEditActions,
    UserEditOwnProps,
    RootState
>(
    mapStateToProps,
    mapDispatchToProps
)(UserEdit);
```

### Issue

Error:
```
Argument of type 'typeof UserEdit' is not assignable to parameter of type 'ComponentType<UserEditProps>'.
  Type 'typeof UserEdit' is not assignable to type 'StatelessComponent<UserEditProps>'.
    Type 'typeof UserEdit' provides no match for the signature '(props: UserEditOwnProps & UserEditActions & UserEditStateProps & { children?: ReactNode; }, context?: any): ReactElement<any> | null'.
```

### Workaround

1. Install `@types/react` version `16.4.6`. (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27417 - this changes makes the difference)
1. If I remove `getDerivedStateFromProps` static method then everything is fine.

**Comment by mcmillhj-wta** [comment]
Not sure if this is related, but we also encountered an issue on the latest version. Downgrading @types/react-redux to 6.0.3 fixed our compilation issues.

**Comment by zarv1k** [comment]
Confirm this one. Downgrading @types/react-redux to 6.0.4 fixed our compilation.

**Comment by shincysl** [comment]
Confirmed. Downgrading @types/react-redux to 6.0.4 fixed my issue. This change breaks the compilation. https://github.com/DefinitelyTyped/DefinitelyTyped/commit/2fa8371b3c01ebf25aaf0a39dc6118a909f58110#diff-ee7ace1841a23c70c0c2b663cfae1cb7

**Comment by Kovensky** [comment]
I had many errors on a specific project when updating, with incredibly misleading and hard to understand and solve type errors...... errors pointing to a completely unrelated property at times, but they were all correctly pointing to _something_ being incorrect in the types.

In most cases it was a component that did not expect a nullable prop (as in `| null`) but it is nullable in the `mapStateToProps` result, but almost never the error message pointed to the correct property. Errors also were completely misleading when the component expected a function with no arguments but the function that was given in `mapDispatchToProps` expected arguments.

In all these cases, the error was either on the component side, or some non-null assertions were missing; and these errors probably would have been caught even without this change if the return value of the `mapStateToProps` / `mapDispatchToProps` functions had been declared with a portion of the actual props. 🤔

**Comment by shincysl** [comment]
Any updates on this issue?
There is a comment in @types/react-redux "ie: decorated component can accept more types than decorator is injecting".
Breaking commit: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27260/files
The commit swapped DecorationTargetProps and InjectedProps. (was DecorationTargetProps[P] extends InjectedProps[P], now InjectedProps[P] extends DecorationTargetProps[P]). Obviously, either the new commit or the comment is wrong. Can anyone have a check? 
In our project, we declare the return type of both mapStateToProps and mapDispatchToProps as Partial<Props> so that visual studio code can pop up code code completion automatically. After 6.0.5, we can no longer do this any more. The return type of mapStateToProps and mapDispatchToProps are too strict.

**Comment by mbenadda** [comment]
All errors I've seen from this update did stem from mismatched injected props passed to a component.

The way I see it, the change in the `Shared` type was actually a bug correction: the previous behavior was definitely not what should be expected. Enforcing more specificity in the expected type than the received type makes no sense for the purposes of verifying the received types.

I think it's right the way it is now: `DecorationTargetProps` need to be equally or less specific than `InjectedProps`.

The problem in your case @shincysl is that you return `Partial<Props>`. That's obviously not more specific than `Props` and therefore fails to satisfy the decorated component's requirements.

**Comment by gyandeeps** [comment]
@mbenadda I am trying to understand your point here with my code example in the original issue. Do you have any insight into this. Thanks

**Comment by shincysl** [comment]
@mbenadda Thanks for the explanation. So I have to split Props into StateProps and DispatchProps instead of Partial....

**Comment by gyandeeps** [comment]
Any insight here will be greatly appreciated. Thanks

**Comment by gyandeeps** [comment]
closing as this is fixed with latest release of `@types/react`.
