### ISSUE TITLE
@types/pdfkit document. - Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by parisgianluca** [DefinitelyTyped/DefinitelyTyped#27561]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @erichillah 

Hello, i tried using @types/pdfkit in an Angular project, but an error blocked me, my code is the following:

```
import * as PDFDocument from 'pdfkit';

import {
  Component,
  OnInit
} from '@angular/core';
@Component({
  selector: 'app-print',
  templateUrl: './print.component.html',
  styleUrls: ['./print.component.css']
})
export class PrintComponent implements OnInit {
  constructor() {}

  ngOnInit() {}

  print = () => {
    const doc = new PDFDocument();
  }
}
```

And i got the following error:

```
document.js:10 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at extend (document.js:10)
    at document.js:26
    at Object.<anonymous> (document.js:243)
    at Object../node_modules/pdfkit/js/document.js (document.js:247)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/print/print.component.ts (main.js:5422)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/app.routes.ts (app.module.ts:169)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/app.module.ts (app.const.ts:44)
```

How can I resolve this? Thanks in advance

**Comment by erichillah** [comment]
Hi @parisgianluca , this does not look like a typing error but rather an error on the library. What version of Pdfkit are you using ? Also make sure your weback copnfig is able to load the all the pdfkit dependencies. Pdfkit uses browserify brfs module internally to load the font files, you should properly configure webpack to load those file, something like a file loader for example.

**Comment by parisgianluca** [comment]
I'm using version 0.7.2 as described in the `index.d.ts`, is it right? So I have to install `brfs` in my application? Ho can I configure my webpack to load those files? Is there some documentation about this?

Thank you very much

**Comment by erichillah** [comment]
Please look at this link https://github.com/huy-nguyen/webpack-and-pdfkit might be helpful. I never configured pdfKit with webpack myself.

**Comment by parisgianluca** [comment]
Thank you for the response, I will check the link you gave me. But I'm using Angular v6, and I cannot configure webpack myself, did you ever used pdfkit with Angular 2+?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
