### ISSUE TITLE
[lodash] Should _.keyBy have a type using keyof?

### ISSUE THREAD

**Issue by benwaffle** [DefinitelyTyped/DefinitelyTyped#27578]
here is the definition for _.keyBy:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9d267d6d685e5e34da7ff7a27f5f84b65d8653f9/types/lodash/common/collection.d.ts#L1396

Should there be a version that takes a List\<T\> and a keyof T?
Otherwise in my code I have to call `.toString()` on the key to go from `string | number | symbol` to `string`.  

- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel, @chrootsu, @stepancar, @aj-r, @ailrun, @e-cloud, @thorn0, @jtmthf, @DomiR

**Comment by aj-r** [comment]
We should probably change all iteratees to allow `number` and `symbol`.
