### ISSUE TITLE
[@types/webpack] 'devServer' does not exist in type 'Configuration'

### ISSUE THREAD

**Issue by eljenso** [DefinitelyTyped/DefinitelyTyped#27570]
- [x] I tried using the `@types/webpack` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @bumbleblym @bcherny @tommytroylin @mohsen1 

I'm using `webpack-dev-server` and before upgrading from v4.4.4 of `@types/webpack`, everything worked fine.
But now that I upgraded to v4.4.8, following warning is printed:
```
WARNING in [at-loader] ./webpack/development.ts:12:3 
    TS2322: Type '{ mode: "development"; devtool: "source-map"; devServer: { host: string; clientLogLevel: string; ...' is not assignable to type 'Configuration'.
  Object literal may only specify known properties, and 'devServer' does not exist in type 'Configuration'.
```

Config in question looks like this:
```ts
import * as webpack from "webpack";

import { commonConfig } from "./common";

const config: webpack.Configuration = {
  ...commonConfig,

  mode: "development",

  // Enable sourcemaps for debugging webpack's output.
  devtool: "source-map",
  devServer: {
    host: "0.0.0.0",
    clientLogLevel: "none",
    port: 3000
  }
};

export default config;
```

Could be a result from #26895.

**Comment by mohsen1** [comment]
I think `@types/webpack-dev-server` contributes the `devServer` member now. Try installing it

**Comment by eljenso** [comment]
This works, thanks!

**Comment by inakianduaga** [comment]
This is not working for me on TypeScript 3.0.1

```
    "@types/webpack": "^4.4.11",
    "@types/webpack-dev-server": "^3.1.0",
```

Somehow the module augmentation is not being picked up. If I copy it manually into the webpack config it gets read but then I get a compilation error at a later stage. Not sure what I would be missing

**Comment by ericyang89** [comment]
it works for me 
```
  "@types/webpack": "^4.4.17",
 "@types/webpack-dev-server": "^3.1.1",
```

**Comment by IAMtheIAM** [comment]
Make sure you import both into your webpack config

```
import * as webpack from 'webpack';
import * as webpackDevServer from 'webpack-dev-server';

const config: webpack.Configuration = {}
```

If you import them both, then it works, but without the webpackDevServer import, it doesnt recognize the type

**Comment by FlamesoFF** [comment]
> I think `@types/webpack-dev-server` contributes the `devServer` member now. Try installing it

That not works.

**Comment by uipoet** [comment]
I had better results after explicitly merging the types:

```TypeScript
import { Configuration as WebpackConfiguration } from "webpack";
import { Configuration as WebpackDevServerConfiguration } from "webpack-dev-server";

interface Configuration extends WebpackConfiguration {
  devServer?: WebpackDevServerConfiguration;
}

export const configuration: Configuration = {
  ...
  devServer: {
    historyApiFallback: true,
    hot: true,
    port: 3000
    ...
  }
  ...
}
```

**Comment by IlCallo** [comment]
> @types/webpack-dev-server contributes the devServer member now

This used to work for me, but now it isn't anymore.

```ts
import { Configuration as WebpackConfiguration } from 'webpack';
import 'webpack-dev-server';
```

In this way the `Configuration` interface isn't augmented as expected.
Tryed to dig a bit into it, but I could not find any changes which could have triggered this change.

@uipoet solution works, even if I'd preferred previous way

**Comment by rpivo** [comment]
Trying @uipoet 's suggestion, but it does not work for me. This is how I'm using it.

```js
import { Configuration as WebpackConfiguration } from 'webpack';
import { Configuration as WebpackDevServerConfiguration } from 'webpack-dev-server';
import merge from 'webpack-merge';
import common from './webpack.common';
import path from 'path';

interface Configuration extends WebpackConfiguration {
  devServer?: WebpackDevServerConfiguration;
}

const __dirname = path.resolve();

const dev: Configuration = merge(common, {
  devServer: {
    compress: true,
    contentBase: path.join(__dirname, 'dist/dev'),
    hot: true,
    open: true,
    port: 9000,
  },
  devtool: 'source-map',
  externals: {
    'react': 'React',
    'react-dom': 'ReactDOM',
  },
  mode: 'development',
});

export default dev;

```

If I comment out `devServer: {...}`, then the webpack build works (without devServer, of course ☹️.

**Comment by mmesar** [comment]
I got rid of the bug when I downgraded @types/webpack-dev-server from **3.11.3** to **3.11.1**
It's not the best of solutions, but with time it will go away by itself :)

**Comment by cinderblock** [comment]
This issue is still present with `@types/webpack-dev-server@3.11.6`. Had to downgrade to `3.11.1`.

**Comment by trusktr** [comment]
If you're using CommonJS instead of ESM format in your webpack.config.js, the following works:

```js
// This causes the webpack-dev-server types to extend webpack's types.
/** @typedef {import('webpack-dev-server')} */

/** @type {import('webpack').Configuration} */
const config = {
  // ...

  devServer: { /* this is type checked now */ }
}

module.exports = config
```

**Comment by ruanyl** [comment]
If you are using yarn, you can check` yarn.lock` and see if there were multiple versions of `webpack` been installed.

In my case, a webpack plugin installed a different version of `webpack` in its own `node_modules`, after removing the duplication, everything works fine.

**Comment by evenfrost** [comment]
For the future comers: `@types/webpack-dev-server` package is deprecated as `webpack-dev-server` has its own types now. See [this comment](https://github.com/webpack/webpack/discussions/15076#discussioncomment-1887720) on how to properly configure types.

**Comment by waleiwalei** [comment]
> Make sure you import both into your webpack config
> 
> ```
> import * as webpack from 'webpack';
> import * as webpackDevServer from 'webpack-dev-server';
> 
> const config: webpack.Configuration = {}
> ```
> 
> If you import them both, then it works, but without the webpackDevServer import, it doesnt recognize the type

if works for me :
import * as webpackDevServer from 'webpack-dev-server'

**Comment by ackvf** [comment]
Often, VSCode is not picking up types for me, even after reload, `Restart TS server` or `Restart Extension Host`. What fixes it is when I manually open the type file that contributes the type.

In this case, opening `\node_modules\webpack-dev-server\types\lib\Server.d.ts` immediately removes the red squiggles.

This is all I needed
```
import * as webpack from 'webpack'
import { type Configuration } from 'webpack'

const config: Configuration = { /* ... */ }
```

**Comment by justinzhustuff** [comment]
I got the same error with `"webpack": "5.89.0"`, so I did like this:
```
import { type Configuration as WebpackConfiguration } from 'webpack';
interface Configuration extends WebpackConfiguration {
  devServer?: any;
}

```

**Comment by samuraijane** [comment]
For those who might be using `webpack-merge`, remember to pass `Configuration` type.

```javascript
import { Configuration as Config } from "webpack";
import { Configuration as DevServerConfig } from "webpack-dev-server";

const devServer: DevServerConfig = { ... };
const config: Config = { ... };

export default merge<Config>(common, config); <-- include type here
```
