### ISSUE TITLE
[chrome] [RFC] Consistently use the @since marker

### ISSUE THREAD

**Issue by fredrikhr** [DefinitelyTyped/DefinitelyTyped#27584]
# Description

As I pointed out in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27571#issuecomment-407903343, [Use JSDoc: @since](http://usejsdoc.org/tags-since.html) specifies the `@since` tag as the following: 

> The `@since` tag indicates that a class, method, or other symbol was added in a specific version.

In the typings for chrome we have used this rather unconsistently. Sometime we have used it, like in line 2692: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/75cb16b116a30f2b98a91613ba3dd17420d0c709/types/chrome/index.d.ts#L2690-L2694

In other cases we have not used this tag, like e.g. in line 259: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/75cb16b116a30f2b98a91613ba3dd17420d0c709/types/chrome/index.d.ts#L257-L262

# Motivation

* Unconsistent documentation. I think we should at least try to keep the documentation consistent, meaning that we should agree on ONE style to use.
* Adds more information to the API documentation. In several parts Google does add a Since information, and the `@since` is exactly there to documentent that particular information.
* More context for tooling. It would be nice to have a linter (or linter-extensions) that could emit warnings (and squiggles) for use of APIs that are not available on the Chrome version you are targeting your extension for. Such linting would be MUCH easier to write if the APIs were annotated properly with the `@since` tag.

# Proposal

I propose that the `@since` tag should be used consistently, either everywhere, or nowhere. However that begs the question of how several corner-cases should be handled.

## Text value of the `@since` tag

The example on JSDoc shows `@since 1.0.1` which is a proper parsable semver version. Now the documentation here does not state that semver (or dotted-version) format is required, but that makes the version much easier to parse for tooling.

However, in those cases where we already use the `@since` tag, we use `@since Chrome XX` since that is the closest we can get to the information displayed in the Chrome API documentation pages.

I am concerned that using a proper semver version format would deviate too much from the information displayed on the Chrome API pages. *Incidentally: Is `47` a valid semver, and if not should we really expand that to `47.0.0`?*

We could of course introduce a semver versioning pattern like `47.0.0-Chrome-47`, but I feel that would only make the version information less readable.

## Where to use the `@since` tag

The Use JSDoc site states that the `@since` tag is to be used for classes, methods, or other symbols. In the case of the Google Chrome API documentation we also have "Since" information for entire namespaces. However, the "Since" information is here listed in a table together with permission (and other) information, like shown below. Using the `@since` tag here, might cause greater deviation from the original documentation pages, since the `@since` tag should be placed after the (implicit) `@summary` tag, which the `Permissions` section is part of.

| | |
| - | - |
| Description: | Namespace description... |
| Availability: | Since Chrome XX. |
| Permissions: | `namespacePermission.action` |

# Summary

I propose:

* The `@since` tag should be used on every declaration that is nested inside a namespace as long as the information is available on the Chrome API documentation pages. (i.e. noted in the documentation in red-coloured text either preceeding or following a type/member description)
* The `@since` tag should read: `@since Chrome XX` where `XX` denotes the integer value of the Chrome version where the type or member was first introduced.
* Namespace declarations should not use the `@since` tag and keep the information as similar as possible to the information displayed on the Chrome API documentation pages. An example of how a namespace should be documented can be seen in lines 19-24 for the `accessibilityFeatures` API. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/75cb16b116a30f2b98a91613ba3dd17420d0c709/types/chrome/index.d.ts#L19-L25

# Assignees

I am happy do go through the API file and perform the required changes, but I'd rather come to an agreement on the style first, before I RegExp the hell out of the entire document.

# CC

Authors of `types/chrome/index.d.ts`: @matthewkimber, @otiai10, @couven92, @RReverser, @sreimer15

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
