### ISSUE TITLE
about react-native-navigation

### ISSUE THREAD

**Issue by hpmax00** [DefinitelyTyped/DefinitelyTyped#27593]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-native-navigation` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @egorshulga @jasonmerino 

If you do not mention the authors the issue will be ignored.

I want to make pr for @types/react-native-navigation, but I can not find it in the repository.
There is not navBarBackgroundColor and  navBarTextColor type in appStyle

**Comment by egorshulga** [comment]
@hpmax00 react-native-navigation v2 is now written in typescript, that is why type definitions have been removed as not needed.
See #27202

**Comment by hpmax00** [comment]
Got it, but it better  when it have release version , then remove the repo
