### ISSUE TITLE
[@types/react] Unable to create HoC that only takes React.ComponentClass as an input

### ISSUE THREAD

**Issue by nodaguti** [DefinitelyTyped/DefinitelyTyped#27645]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @morcerf, @tkrotoff, @DovydasNavickas, @onigoetz, @theruther4d, @guilhermehubner, @ferdaber, @jrakotoharisoa, @pascaloliv, @hotell

----
### Motivation
I'd like to create a HoC whose input is limited to `React.ComponentClass`, not `React.ComponentType` as most blog posts and tutorials suggest, so that I can set a `ref` to the input (wrapped) component.

### Issue details
I've created a repository to reproduce an issue: https://github.com/nodaguti/typescript-component-class-hoc, so please go and see the repo.

The following is a copy of its description:

----

Limiting the type of a wrapped component from `React.ComponentType` to `React.ComponentClass` causes an interesting error in typing resolution of the wrapped component in `render()`.

While there is no issue if I type the wrapped component with `React.ComponentType` or `React.StatelessComponent`, TypeScript starts to complain when I switch the type to `React.ComponentClass` so that only a class-based component would be acceptable as the wrapped component, saying the following error:

```
$ tsc --project ./tsconfig.json
index.tsx:55:11 - error TS2326: Types of property 'injectedA' are incompatible.
  Type '(Readonly<{ children?: ReactNode; }> & Readonly<OriginalProps & ExternalProps> & { injectedA: 0; ...' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Component<OriginalProps & InjectedProps, Componen...'.
    Type '0' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Component<OriginalProps & InjectedProps, Componen...'.
      Type 'Readonly<{ children?: ReactNode; }> & Readonly<OriginalProps & ExternalProps> & { injectedA: 0; i...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<OriginalProps & InjectedProps, Component...'.
        Type 'Readonly<{ children?: ReactNode; }> & Readonly<OriginalProps & ExternalProps> & { injectedA: 0; i...' is not assignable to type 'Readonly<OriginalProps & InjectedProps>'.

55           injectedA={0}
             ~~~~~~~~~~~~~


index.tsx:56:11 - error TS2326: Types of property 'injectedB' are incompatible.
  Type '(Readonly<{ children?: ReactNode; }> & Readonly<OriginalProps & ExternalProps> & { injectedA: 0; ...' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Component<OriginalProps & InjectedProps, Componen...'.
    Type '"injected"' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Component<OriginalProps & InjectedProps, Componen...'.
      Type 'Readonly<{ children?: ReactNode; }> & Readonly<OriginalProps & ExternalProps> & { injectedA: 0; i...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<OriginalProps & InjectedProps, Component...'.
        Type 'Readonly<{ children?: ReactNode; }> & Readonly<OriginalProps & ExternalProps> & { injectedA: 0; i...' is not assignable to type 'Readonly<OriginalProps & InjectedProps>'.

56           injectedB="injected"
             ~~~~~~~~~~~~~~~~~~~~
```

which seems that TypeScript mistakenly believes that the type of the wrapped component's props is `OriginalProps & ExternalProps`, not `OriginalProps & InjectedProps`.

Considering the fact that typing the wrapped component with `React.ComponentType` and `React.StatelessComponent` doesn't cause the error, I believe something might go wrong with a type definition of `React.ComponentClass`.

#### Steps to reproduce

1. Clone this repository
2. `yarn install`
3. `yarn lint`

#### Expected result

No errors are emitted.

#### Actual result

The above errors are emitted.

**Comment by oriSomething** [comment]
Same for me. My check it's from this [commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/09468a17a1d8e600d835b2705ea52a532cbfa7b6#diff-96b72df8b13a8a590e4f160cbc51f40c).
The default param for state in `ComponentClass` cause it.
Maybe, it can be fixed with `ComponentType` declare `ComponentClass` state generic param as `any`.

**Comment by gyandeeps** [comment]
This change also led to this issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/27545

**Comment by johnnyreilly** [comment]
Maybe that change should be reverted; seems it's causing problems - or would that just create different problems?

**Comment by Hotell** [comment]
This was issue even before "[accused commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/09468a17a1d8e600d835b2705ea52a532cbfa7b6#diff-96b72df8b13a8a590e4f160cbc51f40c)"

![image](https://user-images.githubusercontent.com/1223799/43370214-6dff8fbe-937b-11e8-8690-399c3ffbd3eb.png)

**Comment by johnnyreilly** [comment]
Ah - as you were then. BTW I just encountered a video of you @Hotell on Twitter! Zero to hero with React and TypeScript. Alas you were speaking a language I don't.

But your dreads were lovely.

**Comment by nodaguti** [comment]
@Hotell
Thank you so much for sharing your great post and giving a clear solution. Replacing `<OriginalProps extends {}>` with `<OriginalProps extends InjectedProps>` has resolved the issue like a magic!

Should I close this issue then?

**Comment by oriSomething** [comment]
For me this solution didn't work (extending interface)

**Comment by Hotell** [comment]
@nodaguti 

> has resolved the issue like a magic!

While it solved partially your issue, it doesn't work in real life ( what you want is to remove the injected props or make them optional on wrapper ).

So you need to do this:

```tsx
const HoCWithComponentClass = <OriginalProps extends InjectedProps>(
  Cmp: React.ComponentClass<OriginalProps>
) => {
  /**
   * remove InjectedProps from wrapper interface and make them optional
   * so following wont get any errors:
   * 
   * ```tsx
   * const EnhancedWithComponentClass = HoCWithComponentClass(TestCmp)
   *
   * const App = () => {
   *   return (
   *    <><EnhancedWithComponentClass externalA={'asd'} /></>
   *  )
   * }
   * ```
   */
  type WrapperProps = Pick<
    OriginalProps,
    Exclude<keyof OriginalProps, keyof InjectedProps>
  > &
    Partial<InjectedProps>

  class InjectedComponent extends React.Component<
    WrapperProps & ExternalProps
  > {
    render() {
      return <Cmp injectedA={0} injectedB="injected" {...this.props} />
    }
  }

  return InjectedComponent
}
```

Which still throws error

![image](https://user-images.githubusercontent.com/1223799/43386780-fc1685e6-93e4-11e8-81e9-dcd4a1c93f91.png)


> Should I close this issue then?

Nope, I think it's a TypeScript generics issue. Will try to reproduce this with vanilla JS and report bug to TS.

**Comment by Hotell** [comment]
As I've expected, this issue has nothing to do with React nor React typings :)

[Here is the issue demonstrated on vanilla JS](http://www.typescriptlang.org/play/#src=export%20type%20WrapperProps%3COriginalProps%2C%20InjectedProps%3E%20%3D%20Pick%3C%0D%0A%20%20OriginalProps%2C%0D%0A%20%20Exclude%3Ckeyof%20OriginalProps%2C%20keyof%20InjectedProps%3E%0D%0A%3E%20%26%0D%0A%20%20Partial%3CInjectedProps%3E%0D%0A%0D%0A%0D%0Ainterface%20ExternalProps%20%7B%0D%0A%20%20externalA%3A%20string%0D%0A%7D%0D%0A%0D%0Ainterface%20InjectedProps%20%7B%0D%0A%20%20injectedA%3A%20number%0D%0A%20%20injectedB%3A%20string%0D%0A%7D%0D%0A%0D%0Aabstract%20class%20Component%3CP%20%3D%20%7B%7D%2C%20S%20%3D%20%7B%7D%3E%20%7B%0D%0A%20%20abstract%20render()%3A%20object%0D%0A%20%20props%20%3D%20%7B%7D%20as%20P%0D%0A%20%20state%20%3D%20%7B%7D%20as%20S%0D%0A%7D%0D%0A%0D%0Ainterface%20ComponentClass%3CP%20%3D%20%7B%7D%3E%20%7B%0D%0A%20%20new%20(props%3A%20P)%3A%20Component%3CP%3E%0D%0A%20%20defaultProps%3F%3A%20P%0D%0A%20%20displayName%3F%3A%20string%0D%0A%7D%0D%0A%0D%0Aexport%20const%20withComponentClass%20%3D%20%3COriginalProps%20extends%20InjectedProps%3E(%0D%0A%20%20Cmp%3A%20ComponentClass%3COriginalProps%3E%0D%0A)%20%3D%3E%20%7B%0D%0A%20%20type%20InjectedComponentProps%20%3D%20WrapperProps%3COriginalProps%2C%20InjectedComponent%3E%0D%0A%20%20class%20InjectedComponent%20extends%20Component%3C%0D%0A%20%20%20%20InjectedComponentProps%20%26%20ExternalProps%0D%0A%20%20%3E%20%7B%0D%0A%20%20%20%20render()%20%7B%0D%0A%20%20%20%20%20%20this.props.externalA%20%2F%2F%20%24ExpectType%20string%0D%0A%20%20%20%20%20%20this.props.injectedA%20%2F%2F%20%24ExpectType%20undefined%0D%0A%20%20%20%20%20%20this.props.injectedB%20%2F%2F%20%24ExpectType%20undefined%0D%0A%0D%0A%20%20%20%20%20%20%2F%2F%20ISSUE%3A%0D%0A%20%20%20%20%20%20%2F%2F%20TypeScript%20cannot%20properly%20flow%20Constructor%20generic%20arguments%0D%0A%20%20%20%20%20%20%2F%2F%20%24ExpectError%0D%0A%20%20%20%20%20%20const%20cmpInstance%20%3D%20new%20Cmp(%7B%20injectedA%3A%201321%2C%20injectedB%3A%20'12321'%20%7D)%0D%0A%0D%0A%20%20%20%20%20%20%2F%2F%20FIX%3A%0D%0A%20%20%20%20%20%20%2F%2F%20You%20need%20to%20explicitly%20cast%20props%20to%20OriginalProps%20generic%20type%0D%0A%20%20%20%20%20%20%2F%2F%20%24ExpectType%20Cmp%0D%0A%20%20%20%20%20%20const%20cmpInstanceWithCast%20%3D%20new%20Cmp(%7B%0D%0A%20%20%20%20%20%20%20%20injectedA%3A%201321%2C%0D%0A%20%20%20%20%20%20%20%20injectedB%3A%20'12321'%2C%0D%0A%20%20%20%20%20%20%7D%20as%20OriginalProps)%0D%0A%0D%0A%20%20%20%20%20%20return%20%7B%20type%3A%20cmpInstance%20%7D%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%0D%0A%20%20return%20InjectedComponent%0D%0A%7D%0D%0A) with FIX included ;) You're welcome

**Comment by Hotell** [comment]
Ok so this is solid and works:

```tsx
// types.ts
export type WrapperProps<
  OriginalProps extends InjectedProps,
  InjectedProps
> = Omit<OriginalProps, keyof InjectedProps> & Partial<InjectedProps>

export type Omit<T, K extends keyof T> = T extends any
  ? Pick<T, Exclude<keyof T, K>>
  : never
```

```tsx
export const HoCWithComponentClass = <OriginalProps extends InjectedProps>(
  Cmp: React.ComponentClass<OriginalProps>
) => {
  // props definition exposed on final component created by this HoC
  type WrapperCmpProps = WrapperProps<OriginalProps, InjectedProps> &
    ExternalProps

  class InjectedComponent extends React.Component<WrapperCmpProps> {
    render() {
      const props = {
        // InjectedProps
        injectedA: 12321,
        injectedB: 'injected',
        // OriginalProps & ExternalProps
        ...(this.props as object) /* need to cast to object as TS cannot spread Generics */,
      } as InjectedProps & OriginalProps & ExternalProps

      return <Cmp {...props} />
    }
  }

  return InjectedComponent
}
```

![react-component-class-and-hoc](https://user-images.githubusercontent.com/1223799/43781689-c980b9a6-9a5d-11e8-9a22-a26e2e13b12c.gif)
