### ISSUE TITLE
[styled-jsx] Not robust to updates in @types/react

### ISSUE THREAD

**Issue by vivaldus** [DefinitelyTyped/DefinitelyTyped#27646]
- [X] I tried using the `@types/styled-jsx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @R1ZZU

<hr>

I've been using styled-jsx the last few months with typescript (really appreciate all your work on it!) Periodically I've been getting this TS Error after various refactoring / package upgrading:

```bash
Property 'jsx' does not exist on type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'
``` 

After bashing the keyboard repeatedly, I managed to get it to go away every time, but got so fed up with it that I decided to try to get to the bottom of the problem. I *think* that it's caused whenever I have multiple instances of `@types/react` within my `node_modules/@types` dir, which happens when e.g. I try upgrading to the latest version of @types/react (e.g. `yarn upgrade --latest @types/react`) but that normally leaves all the other modules in `@types/*` that require `@types/react` retaining the previous version of it. I found that the above error seemed to go away when I made my installed version of `@types/react` exact and used resolutions in `package.json` to coordinate everything in `@types`  to use that same exact version of `@types/react`. I.e. this seemed to fix the problem:

```jsonc
{
    //...
    "devDependencies": {
        //...
        "@types/react": "16.4.7",
        //...
    },
    "resolutions": {
        "**/@types/react": "16.4.7"
    }
}
```

So my question is whether having multiple versions of `@types/react` nested with `@types` is the reason why I've been getting the typing error noted above and, if so, is there any way the `@types/styled-jsx` could be modified so that others and myself won't run into this problem again? Thanks!

**Comment by freedomsky11** [comment]
Thank you very much! It revolves mine problem. I have this problem today, and I have been trying lots of advice, but none of one working except this.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
