### ISSUE TITLE
All declarations of 'JQuery' must have identical type parameters.

### ISSUE THREAD

**Issue by zgosalvez** [DefinitelyTyped/DefinitelyTyped#27657]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/bootstrap` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @denisname 

If you do not mention the authors the issue will be ignored.

---

This occurs when using @types/bootstrap with Angular-CLI, and it is failing to compile. Here's the exact error.

```bash
ERROR in node_modules/@types/bootstrap/index.d.ts(357,15): error TS2428: All declarations of 'JQuery' must have identicaltype parameters.
node_modules/@types/jquery/index.d.ts(3275,11): error TS2428: All declarations of 'JQuery' must have identical type parameters.
```

**Comment by leonard-thieu** [comment]
You need to update `@types/bootstrap`.

**Comment by thorn0** [comment]
Please close this issue if it's resolved.
