### ISSUE TITLE
Stripe: fix nullable types

### ISSUE THREAD

**Issue by LinusU** [DefinitelyTyped/DefinitelyTyped#27656]
A longtime problem with the Stripe typings has been that the nullability of each property has more often than not been off. This is mainly because their API documentation doesn't mention nullability, and many updates to fix it comes from when we encounter it in the wild from the API.

But there is hope! An employee of Stripe has pointed us to a specification of their API which includes `nullable` annotations for all the properties.

> Try [the OpenAPI specification](
https://github.com/stripe/openapi/tree/master/openapi) (see `spec3.yaml` in particular). Fields on resources have a `nullable: true` annotation where they're nullable.

Armed with this we should be able to fix the nullability on all properties once and for all 🙌 

Now, this is going to be a shit ton of work, but if we pull together it probably shouldn't be too hard. I've compiled a list of all the interfaces here, so that we can check them off as we go:

- [ ] `accounts`
  - [ ] `IAccount`
  - [ ] `IAccountCreationOptions`
  - [ ] `IAccountShared`
  - [ ] `IAccountUpdateOptions`
  - [ ] `IExternalAccountCreationOptions`
  - [ ] `IExternalAccountUpdateOptions`
  - [ ] `IBankAccountListOptions`
  - [ ] `ICardListOptions`
  - [ ] `IRejectReason`
- [ ] `applicationFees`
  - [ ] `IApplicationFee`
  - [ ] `IApplicationFeeListOptions`
  - [ ] `IApplicationFeeRefund`
  - [ ] `IApplicationFeeRefunds`
  - [ ] `IApplicationFeeRefundCreationOptions`
- [ ] `balance`
  - [ ] `IBalance`
  - [ ] `ISourceType`
  - [ ] `IBalanceTransaction`
  - [ ] `IBalanceListOptions`
- [ ] `charges`
  - [ ] `ICharge`
  - [ ] `IChargeCreationOptions`
  - [ ] `IChargeCaptureOptions`
  - [ ] `IChargeUpdateOptions`
  - [ ] `IChargeListOptions`
  - [ ] `IOutcome`
  - [ ] `IChargeRefunds`
- [ ] `coupons`
  - [ ] `IDiscount`
  - [ ] `ICoupon`
  - [ ] `ICouponCreationOptions`
- [ ] `customers`
  - [ ] `ICustomer`
  - [ ] `ICustomerSubscriptions`
  - [ ] `ICustomerCreationOptions`
  - [ ] `ICustomerUpdateOptions`
  - [ ] `ICustomerListOptions`
  - [ ] `ICustomerSourceCreationOptions`
  - [ ] `ICustomerCardSourceCreationOptions`
  - [ ] `IBankAccountSourceListOptions`
  - [ ] `ICardSourceListOptions`
- [ ] `disputes`
  - [ ] `IDispute`
  - [ ] `IDisputeEvidence`
  - [ ] `IDisputeUpdateOptions`
- [ ] `events`
  - [ ] `IEvent`
  - [ ] `IEventListOptions`
- [ ] `fileUploads`
  - [ ] `IFileUpdate`
  - [ ] `IFileUploadCreationOptions`
  - [ ] `IFileUploadListOptions`
- [ ] `invoices`
  - [ ] `IInvoice`
  - [ ] `IInvoiceLineItem`
  - [ ] `IInvoiceCreationOptions`
  - [ ] `IInvoiceUpdateOptions`
  - [ ] `IInvoicePayOptions`
  - [ ] `IInvoiceListOptions`
  - [ ] `IInvoiceLineItemRetrievalOptions`
  - [ ] `IInvoiceUpcomingOptions`
  - [ ] `IPeriod`
- [ ] `invoiceItems`
  - [ ] `InvoiceItem`
  - [ ] `InvoiceItemCreationOptions`
  - [ ] `InvoiceItemUpdateOptions`
  - [ ] `InvoiceItemListOptions`
- [ ] `orders`
  - [ ] `IOrder`
  - [ ] `IOrderItem`
  - [ ] `IOrderCreationOptions`
  - [ ] `IOrderUpdateOptions`
  - [ ] `IOrderPayOptions`
  - [ ] `IOrderListOptions`
  - [ ] `IOrderItemCreationHash`
  - [ ] `IShippingMethod`
- [ ] `payouts`
  - [ ] `IPayout`
  - [ ] `IPayoutCreationOptions`
  - [ ] `IPayoutListOptions`
- [ ] `plans`
  - [ ] `ITier`
  - [ ] `ITransformUsage`
  - [ ] `IPlan`
  - [ ] `IPlanCreationOptions`
  - [ ] `IPlanUpdateOptions`
  - [ ] `IPlanCreationOptionsProductHash`
- [ ] `products`
  - [ ] `IProduct`
  - [ ] `IProductCreationOptions`
  - [ ] `IProductUpdateOptions`
  - [ ] `IProductListOptions`
  - [ ] `IPackageDimensions`
- [ ] `recipientCards`
- [ ] `recipients`
  - [ ] `IRecipient`
- [ ] `skus`
  - [ ] `ISku`
  - [ ] `ISkuCreationOptions`
  - [ ] `ISkuUpdateOptions`
  - [ ] `ISkuListOptions`
  - [ ] `IInventory`
  - [ ] `ISkuAttributes`
- [ ] `webhooks`
  - [ ] `StripeWebhookEvent`
- [ ] `ephemeralKeys`
  - [ ] `IStripeVersion`
  - [ ] `ICustomer`
  - [ ] `IEphemeralKey`
  - [ ] `IAssociatedObject`
- [ ] `tokens`
  - [ ] `IToken`
  - [ ] `ICardToken`
  - [ ] `IBankAccountToken`
  - [ ] `ITokenBase`
  - [ ] `ITokenCreationOptionsBase`
  - [ ] `ICardTokenCreationOptions`
  - [ ] `IBankAccountTokenCreationOptions`
  - [ ] `IPiiTokenCreationOptions`
- [ ] `transfers`
  - [ ] `ITransfer`
  - [ ] `ITransferReversals`
  - [ ] `ITransferCreationOptions`
  - [ ] `ITransferUpdateOptions`
  - [ ] `ITransferListOptions`
- [ ] `transferReversals`
  - [ ] `IReversal`
  - [ ] `IReversalCreationOptions`
  - [ ] `IReversalUpdateOptions`
- [ ] `bankAccounts`
  - [ ] `IBankAccount`
  - [ ] `IBankAccountHash`
  - [ ] `ISourceCreationOptions`
  - [ ] `IBankAccountUpdateOptions`
- [ ] `bitcoinReceivers`
  - [ ] `IBitcoinReceiver`
  - [ ] `IBitcoinTransaction`
  - [ ] `IBitcoinReceiverCreationOptions`
  - [ ] `IBitcoinReceiverListOptions`
- [ ] `cards`
  - [ ] `ICard`
  - [ ] `ICardHash`
  - [ ] `ICardUpdateOptions`
  - [ ] `ISourceCreationOptions`
  - [ ] `ISourceCreationOptionsExtended`
- [ ] `subscriptions`
  - [ ] `ISubscription`
  - [ ] `ISubscriptionCustCreationOptions`
  - [ ] `ISubscriptionCreationOptions`
  - [ ] `ISubscriptionUpdateOptions`
  - [ ] `ISubscriptionCancellationOptions`
  - [ ] `ISubscriptionListOptions`
  - [ ] `ISubscriptionCreationItem`
  - [ ] `ISubscriptionUpdateItem`
- [ ] `subscriptionItems`
  - [ ] `ISubscriptionItem`
  - [ ] `ISubscriptionItemCreationOptions`
  - [ ] `ISubscriptionItemUpdateOptions`
  - [ ] `ISubscriptionItemDeleteOptions`
  - [ ] `ISubscriptionItemListOptions`
- [ ] `refunds`
  - [ ] `IRefund`
  - [ ] `IRefundCreationOptions`
  - [ ] `IRefundCreationOptionsWithCharge`
  - [ ] `IRefundListOptions`
- [ ] `sources`
- [ ] `countrySpecs`
  - [ ] `ICountrySpec`
- [ ] `reviews`
  - [ ] `IReview`
- [ ] `applications`
  - [ ] `IApplication`
- [ ] `resources`
  - [ ] `IPlanListOptions`

Paging all the Stripe typings authors: @wjohnsto @codeanimal @sampsonjoliver @LinusU @brannon @kkamperschroer @starhoshi @bruun @galtalmor @htunnicliff @squirly @tzarger

**Comment by LinusU** [comment]
Another approach could be to try and generate the entire `.d.ts` file from the API specification. Not sure how feasible that would be though 🤔 

Took a quick stab here: https://gist.github.com/LinusU/0463421d8cfead428fa4f02270246aa1

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
