### ISSUE TITLE
webvr-api is incompatible with typescript 3.0.1

### ISSUE THREAD

**Issue by abirmingham** [DefinitelyTyped/DefinitelyTyped#27706]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @efokschaner

Upon upgrading from 2.9 to 3.0:
```
ERROR in /data/depot-ui/node_modules/@types/webvr-api/index.d.ts(136,5):
TS2717: Subsequent property declarations must have the same type.  Property 'leftBounds' must be of type 'number[] | Float32Array', but here has type 'number[]'.
ERROR in /data/depot-ui/node_modules/@types/webvr-api/index.d.ts(137,5):
TS2717: Subsequent property declarations must have the same type.  Property 'rightBounds' must be of type 'number[] | Float32Array', but here has type 'number[]'.
```

Looks like node_modules/typescript/lib/lib.dom.d.ts has been updated such that VRLayer now references `number[] | Float32Array | null`, whereas webvr-api references `number[] | null`.

Thanks!

**Comment by abirmingham** [comment]
Looks like this may actually be a bad idea. See https://github.com/Microsoft/TypeScript/issues/26038

**Comment by jddxf** [comment]
@abirmingham Can we just import the dom lib using [new triple-slash-reference directive](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#-reference-lib--reference-directives)?

**Comment by efokschaner** [comment]
@jddxf how would that affect users of this typing module that are using typescript versions before they were included in dom lib?

**Comment by milewski** [comment]
meanwhile is there anyway to ignore this error?

**Comment by efokschaner** [comment]
Hi @milewski , there's a potential workaround mentioned here https://github.com/Microsoft/TypeScript/issues/26038#issuecomment-409024131 as well as some more discussion of this issue
