### ISSUE TITLE
error TS2339: Property 'order' does not exist on type 'object'.

### ISSUE THREAD

**Issue by grizzlysol** [DefinitelyTyped/DefinitelyTyped#27734]
```
$.fn.dataTable.ext.type.order['prioritySort-pre'] = function ( d ) {
  switch ( d ) {
        case 'Low':    return 1;
        case 'Medium': return 2;
        case 'High':   return 3;
  }
  return 0;
};
```

I keep getting an error "error TS2339: Property 'order' does not exist on type 'object'."
The type on interface ExtSettings on line 2004 of index.d.ts needs to include type with an order property.

@omidkrad @pragmatrix @CNBoland

**Comment by grizzlysol** [comment]
Fixed the issue.
In jquery.dataTables.js on line 13862, DataTable.ext is defined with property type on line 14173.
type is define as:
```
(property) type: {
    [x: string]: any;
    detect: any[];
    search: any;
    order: any;
}
```
In index.d.ts of @types/datatables.net I defined the following:
```
interface ExtTypeSettings {
        [x: string]: any;
        detect: any[];
        search: any;
        order: any;
    }
```
I updated the ExtSettings interface where type uses the new ExtTypeSettings.

```
 interface ExtSettings {
   ...
   type: ExtTypeSettings;
 }
```

I no longer have the previously mentioned issue.

**Comment by CNBoland** [comment]
Thank you for the feedback @grizzlysol . I like your idea. However, according to the jquery.dataTables.js reference you mentioned, the data types can be more explicit. Here is what I came up with:

```
interface ExtTypeSettings {
    detect: FunctionExtTypeDetect[];
    search: object;
    order: object;
}

type FunctionExtTypeDetect = (data: any, settings: DataTables.Settings) => (string | null);
```
I don't see a need for `[x: string]: any;` defined `ExtTypeSettings`, but I may have missed something. Can you expound on that?

**Comment by CNBoland** [comment]
Thank you for the feedback @grizzlysol . I like your idea. However, according to the jquery.dataTables.js reference you mentioned, the data types can be more explicit. Here is what I came up with:

```
interface ExtTypeSettings {
    detect: FunctionExtTypeDetect[];
    search: object;
    order: object;
}

type FunctionExtTypeDetect = (data: any, settings: DataTables.Settings) => (string | null);
```
I don't see a need for `[x: string]: any;` defined `ExtTypeSettings`, but I may have missed something. Can you expound on that?

**Comment by grizzlysol** [comment]
@CNBoland, I think you are right, I was just following the definition. I also don't see a need for `[x: string]: any`, removing it doesn't seem to cause an issue. Also, I like how you explicitly defined `detect`. 
I think this will be fine as a fix.

**Comment by CNBoland** [comment]
Ok, great! Would you like to submit a PR for this?

**Comment by CNBoland** [comment]
@grizzlysol I went ahead and committed what I was playing around with (cleaned up, of course). Thank you for reporting the problem.

**Comment by grizzlysol** [comment]
@CNBoland Hey, sorry I didn't add a PR for this. I'm pretty new to this and have been very busy. Thanks for adding the fix.
