### ISSUE TITLE
[@types/hapi] Wrong option type

### ISSUE THREAD

**Issue by zamu87** [DefinitelyTyped/DefinitelyTyped#27758]
In ServerOption interface, the tls value should be boolean | https.ServerOptions

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cdcc5dd4ff3a08eebb585200b9fae29209637650/types/hapi/index.d.ts#L2908

**Comment by SimonSchick** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27551

This can be closed I think.

**Comment by zamu87** [comment]
Thanks @SimonSchick for your answer, but i mean that tls param in ServerOption interface should of type **https.ServerOptions** and not **https.RequestOptions** as it is. Thanks

**Comment by zamu87** [comment]
resolved in PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28447#issuecomment-416582717

**Comment by SimonSchick** [comment]
Please do not close issues that have not been resolved.
