### ISSUE TITLE
@types/react-intl breaks package react-intl

### ISSUE THREAD

**Issue by bombek92** [DefinitelyTyped/DefinitelyTyped#27807]
So after installing @types/react-intl (2.3.8) into my project the import
from react-intl/locale-data stopped working.

This is how I imported locale datas for different languages:

> import frLocaleData from 'react-intl/locale-data/fr';
> import deLocaleData from 'react-intl/locale-data/de';

After adding @types/react-intl into package.json and installing them I got this error:

> [ts] Module '"react-intl/locale-data/pl"' has no default export.

Authors: @bgrieder  @cdroulers @gyzerok @tillwolff @LKay @bhouser @kristerkari @formatlos

**Comment by pheromonez** [comment]
We've been using `@types/react-intl@2.3.8` for some time now. Here's how we add locale data:

```typescript
import { addLocaleData } from 'react-intl'
import * as de from 'react-intl/locale-data/de'
import * as fr from 'react-intl/locale-data/fr'

addLocaleData([...fr, ...de])
```

**Comment by a821246710** [comment]
```
import * as xx
```
Doesn't work for me, it imports an object instead of array.

![screen_shot_2018-08-17_at_7_32_32_pm](https://user-images.githubusercontent.com/6903774/44264408-1733f100-a255-11e8-9284-d0960beb7d7e.png)

Did I miss something?

**Comment by pheromonez** [comment]
@a821246710 You might be using a version of `@types/react-intl` that isn't compatible with the version of `react-intl`. I tried importing the `zh` locale using the `import * as zh...` syntax, and it is importing as an array for me.

These are the versions of the libraries I am using:
* react-intl: 2.4.0
* @types/react-intl: 2.3.8
