### ISSUE TITLE
Is there a typing for package.json?

### ISSUE THREAD

**Issue by Ailrun** [DefinitelyTyped/DefinitelyTyped#27814]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

Is there a typing for package.json? If not, can I make one?

**Comment by Ailrun** [comment]
@andy-ms @sheetalkamat

**Comment by Ailrun** [comment]
@nukuuk ??? What I meant in this issue is about `package.json` file itself, not about any packages on NPM.

**Comment by pluma** [comment]
@Ailrun Since `package.json` is a JSON spec, not a JS API, you might want to look into JSON schema instead. Specifically this is the public schema for `package.json` files used by IDEs and editors like VS Code: http://json.schemastore.org/package

**Comment by Ailrun** [comment]
@pluma But we can import `package.json` in node.js, and we need to handle imported value.

**Comment by pluma** [comment]
That sounds like a case for something like this: https://github.com/bcherny/json-schema-to-typescript

That said, I think this is the wrong place to discuss this as `package.json` is not a library or environment but a JSON data format. There's no guarantee that any file called `package.json` is actually a `package.json` file (i.e. that it adheres to the spec) so you would probably want to type it explicitly on import (i.e. `const packageJsonData = require("../package.json") as PackageJson`).

Also ES modules don't support JSON files AFAIK so I don't think specific JSON files should be treated any different than any other files whose contents could be loaded and parsed at runtime.

**Comment by Ailrun** [comment]
@pluma We still need that `PackageJson`. Package you suggest is just a creator for that `PackageJson` type, not a way to share it.

**Comment by pluma** [comment]
Yes. That's what I said. You could use that tool to generate TypeScript typings for the various existing JSON schemas. But I don't think this is a problem DefinitelyTyped is built to address.

**Comment by Ailrun** [comment]
@pluma DT is a way to share typings, isn't it? WHAT I SAID FROM THE FIRST TIME IS ABOUT SHARING TYPING OF PACKAGE.JSON.

**Comment by ffflorian** [comment]
@Ailrun try https://www.npmjs.com/package/@schemastore/package :slightly_smiling_face:

**Comment by xgqfrms** [comment]
# typings & package.json

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

```json

{
    "name": "awesome",
    "author": "xgqfrms",
    "version": "1.0.0",
    "main": "./lib/main.js",
    "types": "./lib/main.d.ts"
}

```

```json

{
    "name": "awesome",
    "author": "xgqfrms",
    "version": "1.0.0",
    "main": "./lib/main.js",
    "typings": "./lib/main.d.ts"
}

```

**Comment by Ailrun** [comment]
@xgqfrms Sorry, what you suggested is nothing to do with my question.
The link explains how to add a typing of a package to package.json, yet my question is about typing of package.json itself, not a package.

**Comment by trajano** [comment]
At the moment we cheated the system by adding 
```
declare module "*.json" {
  const value: any;
  export default value;
}

```

**Comment by remcohaszing** [comment]
A type definition for `package.json` is available in [type-fest](https://github.com/sindresorhus/type-fest)

```ts
import { PackageJson } from 'type-fest';
```

**Comment by ajaxlab** [comment]
https://www.npmjs.com/package/package-json-type 😃 

```ts
import {
  IDependencyMap,
  IEngines,
  IPackageJson,
  SPDXLicenseIDApproved
} from 'package-json-type';
 
const dependency: IDependencyMap = {
  bar: '^1.0.0',
  baz: '^2.1.0',
  qux: 'file:../src/qux'
};
 
const engines: IEngines = {
  node: '>=6.0.1 <11.0.0',
  yarn: '^1.15.0',
  zlib: '^0.14.0'
};
 
const license: SPDXLicenseIDApproved = 'MIT';
 
const pkg: IPackageJson = {
  name: 'foo',
  version: '1.2.3',
  dependency,
  description: 'This is awesome foo',
  engines,
  license 
};
```

**Comment by wulechuan** [comment]
```ts
import type T_npm_packageJSON from '../package.json'
```

```js
/** @typedef {import('../package.json') T_npm_packageJSON } */
```

Non complete, neither necessary to be complete. It ALWAYS provides what YOUR packageJSON looks like.

**Comment by vladpuz** [comment]
[pkg-types](https://github.com/unjs/pkg-types)

```typescript
import type { TSConfig, PackageJson, GitConfig } from "pkg-types";
```
