### ISSUE TITLE
@types/storejs should be renamed to @types/store

### ISSUE THREAD

**Issue by jake-low** [DefinitelyTyped/DefinitelyTyped#27825]
Authors: @vbortone, @harry0000, @Ky6uk

Typings for the NPM package `store` ([npmjs.com/package/store](https://www.npmjs.com/package/store)) are located in `types/storejs` in this repository, and are consequently published as [@types/storejs](https://www.npmjs.com/package/@types/storejs). This contradicts the DefinitelyTyped README which states:

> For an NPM package "foo", typings for it will be at "@types/foo".

Furthering the confusion, [npmjs.com/package/storejs](https://www.npmjs.com/package/storejs) exists and is an unrelated project.

I'm assuming this name mismatch is unintentional. If that's correct, **let me know and I can open a pull request to fix this**.

**Comment by Ky6uk** [comment]
Yeah. I also was confused about it when I tried to use this typing first time.

**Comment by harry0000** [comment]
> If that's correct, let me know and I can open a pull request to fix this.

Great!

[npmjs.com/package/store.js](https://www.npmjs.com/package/store.js) seems not to be used since v1.0.4.

**Comment by vbortone** [comment]
This probably dates back to much earlier in the project history.  Go ahead
and make the change.

Best Regards,

Vin
