### ISSUE TITLE
[@types/jest] enforce target types for toEqual, toBe, etc. 

### ISSUE THREAD

**Issue by bogdan-zaharia-hs** [DefinitelyTyped/DefinitelyTyped#27840]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/jest` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @JoshuaKGoldberg @bradleyayers

Right now `expect().toEqual` has the signature `toEqual(expected: any): R`. Similarly for `toBe`. I think it would be better to enforce the type `R` on these assertions (and possibly others, but these are the most used), since it does not make sense for the code to compile if the types are not compatible. Also, it helps with autocompletion in IDEs. 

I could have opened a PR for this, but before that I wanted to know what were the motivations for the current type signatures and if there are any issues preventing the more restrictive ones.

**Comment by bogdan-zaharia-hs** [comment]
Tried to set `toEqual(expected: R): void` and `toBe(expected: R): void` and got a lot of errors in `test-tests.ts` related to `jasmine.any` (e.g. `expect(7).toBe(jasmine.any(Number));`).

I could not think of an easy way to make things work, since jasmine.Any is not generic, so I gave up.

For now, we use some helpers in our tests, like:
```ts
function expectToEqual<T>(actual: T, expected: T): void {}
```

**Comment by OliverJAsh** [comment]
How about this? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47553
