### ISSUE TITLE
[@types/node] Writable and WritableStream incompatibility

### ISSUE THREAD

**Issue by Astrych** [DefinitelyTyped/DefinitelyTyped#27873]
version: @types/node 10.5.6
typescript in version 2.9.2

After last commit 9fe65ab328e585b5f06336faebedbf26d46c11c3 from pull request #27788 made by @rbuckton I see a lot of following errors:

```
ERROR in node_modules/@types/node/index.d.ts(6081,13):
TS2416: Property 'write' in type 'Writable' is not assignable to the same property in base type 'WritableStream'.
  Type '{ (chunk: any, cb?: ((error: Error | null | undefined) => void) | undefined): boolean; (chunk: an...' is not assignable to type '{ (buffer: string | Buffer, cb?: Function |
undefined): boolean; (str: string, encoding?: string ...'.
```

Now i can't do the following:

```typescript
import fs from "fs";
import zlib from "zlib";

const inputStream = fs.createReadStream(sourcePath);
const unzip = zlib.createUnzip();
const outputStream = fs.createWriteStream(targetPath);

inputStream.pipe(unzip).pipe(outputStream);
```

Because it emmits:

```
TS2345: Argument of type 'Unzip' is not assignable to parameter of type 'WritableStream'.
  Types of property 'write' are incompatible.
    Type '{ (chunk: any, cb?: ((error: Error | null | undefined) => void) | undefined): boolean; (chunk: an...' is not assignable to type '{ (buffer: string | Buffer, cb?: Function
| undefined): boolean; (str: string, encoding?: string ...'.
      Types of parameters 'cb' and 'cb' are incompatible.
        Types of parameters 'err' and 'error' are incompatible.
          Type 'Error | null | undefined' is not assignable to type 'Error | undefined'.
            Type 'null' is not assignable to type 'Error | undefined'.
```

No issues with version: @types/node 10.5.5

**Comment by rbuckton** [comment]
@Astrych: I added this test to node-tests.ts locally:

```ts
// GH: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/27873
function stream_compatibility() {
    const inputStream = fs.createReadStream("");
    const unzip = zlib.createUnzip();
    const outputStream = fs.createWriteStream("");
    inputStream.pipe(unzip).pipe(outputStream);
}
```

However, I am not seeing the issue locally. It is possible that a different declaration file in your compilation has a module augmentation that modifies `NodeJS.WritableStream` that is causing the problem, as I ran into a similar problem in _vinyl-fs_ that I corrected in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27788/commits/544fcfa051afecb76cc6cc9d6ee4ddc6cc463268.

If you are able to determine which declaration file has this issue, if it comes from a package on DefinitelyTyped we should be able to file a PR to update the offending package.

**Comment by Astrych** [comment]
Hm, ok, I will check that. Thanks.

**Comment by Flarna** [comment]
I thought it is related to disabled `"strictNullChecks": false` but I tried above sample in a standalone setup with `"strictNullChecks": true` and typescript doesn't complain.

**Comment by Astrych** [comment]
@rbuckton Found it. In my case it was also *vinyl-fs* library but not as a direct dependency but dependency of other dependency. package-lock.json has frozen *vinyl-fs* version as 2.4.8 which caused the issue. Thanks, you are great! :)

**Comment by sudiptosen** [comment]
Thanks guys - I deleted the package-lock.json and reinstalled, resolved rightaway

**Comment by Phoscur** [comment]
Thank you guys, ran into this with discord.js 14.15 & TS5.5, it's fixed: https://github.com/discordjs/discord.js/issues/10358
