### ISSUE TITLE
[@types/styled-system] Dependence on styled-components

### ISSUE THREAD

**Issue by leshkovichpvl** [DefinitelyTyped/DefinitelyTyped#27881]
Why in <code>@types/styled-system</code> dependence on <a href="https://github.com/styled-components/styled-components">styled-components</a> ? -___-

Authors: @maxdeviant, @phobon, @zephraph, @damassi, @alloy, @maoueh, @lavoaster

**Comment by phobon** [comment]
As far as I know, the dependency was purely for the purposes of tests that all pull requersts into DefinitelyTyped require. The other authors may have more to add, but I think you should open a PR to remove the dependency.

**Comment by leshkovichpvl** [comment]
Sba custom styled function for test.

**Comment by alloy** [comment]
Let‘s close this issue in favour of further discussion on the PR.
