### ISSUE TITLE
Support for react-leaflet 2.0

### ISSUE THREAD

**Issue by benneq** [DefinitelyTyped/DefinitelyTyped#27887]
- [x] I tried using the `@types/react-leaflet` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @danzel @davschne @yuit 

(looks like Author @davschne doesn't exist)

`react-leaflet` released version `2.0` a few weeks ago. Looks like there were some breaking changes.

Changelog: https://github.com/PaulLeCam/react-leaflet/releases/tag/v2.0.0

Especially `LeafletConsumer, LeafletProvider, withLeaflet` are missing.

Thank you for your great work!

**Comment by davschne** [comment]
I most certainly do exist. Reports of my death have been grossly exaggerated.

Yeah, looks like the type defs could use an update. Not sure whether I'll have time to do it. If you'd like to take a stab at updating them, @benneq, I'm happy to review the PR.

**Comment by benneq** [comment]
Glad you exist :) Really strange. When I created this issue it didn't suggest me your name, while typing @davschne. Now it works as expected.

I've never written `d.ts` files. Not sure if I have enough time in the next couple days / weeks.

Isn't there any `flow -> typescript` tool? The `flow` definitions of the library itself look pretty solid. Though I guess it could(?!) be pretty easy to just let some tool convert it to typescript.

At the moment I'm using something like this as a workaround:
```
import * as RL from 'react-leaflet';
const ReactLeaflet = RL as any;
ReactLeaflet.withLeaflet(...);
```

**Comment by shincysl** [comment]
Here is my workaround.

// https://react-leaflet.js.org/docs/en/context.html
import * as L from "leaflet";
import "react-leaflet";
declare module "react-leaflet" {
    const withLeaflet: <T>(component: T) => T;
    interface LeafletContext {
        map?: L.Map;
    }
}

**Comment by gwillz** [comment]
To extend on @shincysl's workaround.
https://gist.github.com/gwillz/9498267353770cbd121fe3aabc5cec68

Includes Consumer/Provider, withLeaflet props, and contextValue property for a few types.

**Comment by slisystem** [comment]
Happy new year guys! Any news? :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
