### ISSUE TITLE
Update index.d.ts to the node-rsa version 1.0.1

### ISSUE THREAD

**Issue by sgomanf** [DefinitelyTyped/DefinitelyTyped#27885]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sandersn 

If you do not mention the authors the issue will be ignored.

Now in node-rsa 1.0.1 the importKey(key: NodeRSA.Key, format?: NodeRSA.Format): void; function must return this (NodeRSA)

**Comment by sandersn** [comment]
Looks like the authors of this d.ts are actually @alitaheri and @xm
