### ISSUE TITLE
L.Util.extend type isn't allowing for more than 2 parameters

### ISSUE THREAD

**Issue by WilliamRADFunk** [DefinitelyTyped/DefinitelyTyped#27916]
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @alejo90 @atd-schubert @mcauer

Using Angular 5 (and properly wrapping leaflet in an Angular-friendly way), I have a typescript error when using the L.Util.extend function with more than 2 parameters, as seen in the following screenshot example:

![exampleoferror](https://user-images.githubusercontent.com/10148684/43744904-3434e54c-99aa-11e8-8b30-2e0bfe259a53.JPG)

Leaflet itself uses this function with three parameters in some cases. One example is in leaflet/src/core/Events.js as seen in the following screenshot:

![leafletusing3params](https://user-images.githubusercontent.com/10148684/43744887-27bd9390-99aa-11e8-836f-84960270fec0.JPG)

Any chance this is already in the works for a @1.2.10 ?

**Comment by andy-ms** [comment]
Package authors are @alejo90 @atd-schubert @mcauer

**Comment by WilliamRADFunk** [comment]
Sorry about that. I corrected it.
