### ISSUE TITLE
@types/generic-pool: release and destroy's return type.

### ISSUE THREAD

**Issue by yinso** [DefinitelyTyped/DefinitelyTyped#27921]
If you know how to fix the issue, make a pull request instead.

- [ x ] I tried using the `@types/xxxx` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wrboyce , @jerray 

Looking at [the definition of the release method](https://github.com/coopernurse/node-pool/blob/master/lib/Pool.js#L497-L516), it looks like it should have the type of `PromiseLikevoid>`, however, right now [the definition has a type of `void`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a8f8fdcd1ecbe58d50045dd2cf291b13e7a915f4/types/generic-pool/index.d.ts#L22).

The same applies to [the `destroy` method](https://github.com/coopernurse/node-pool/blob/master/lib/Pool.js#L527-L546) and [its type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a8f8fdcd1ecbe58d50045dd2cf291b13e7a915f4/types/generic-pool/index.d.ts#L23).

Any reason for using `void` instead of `PromiseLike<void>`? Thanks.

**Comment by jerray** [comment]
Yes, it's a mistake. Could you make a pull request to fix it?
