### ISSUE TITLE
@types/jasmine - Spy.withArgs() method missing

### ISSUE THREAD

**Issue by stamminator** [DefinitelyTyped/DefinitelyTyped#27938]
- [x] I tried using the `@types/jasmine@latest` package and had problems.

Authors: @borisyankov, @theodorejb, @davidparsson, @gmoothart, @lukas-zech-software, @Engineer2B
____

In the documentation for [Jasmine 3.1](https://jasmine.github.io/api/3.1/Spy), the `Spy` class contains the `withArgs` instance method. This is missing from the latest version of `@types/jasmine`.

**Comment by stamminator** [comment]
@borisyankov, @theodorejb, @davidparsson, @gmoothart, @lukas-zech-software, @Engineer2B 

Is anyone able to take a look at this?

**Comment by gmoothart** [comment]
Seems reasonable; can you send a PR?

**Comment by stamminator** [comment]
@gmoothart I'll submit one shortly. I'm an NPM noob, though... how do I increase they version from 2.8.8? I think we should move it to 3.1.0 for parity with Jasmine

**Comment by gmoothart** [comment]
Versoning is not managed well by DefinitelyTyped. Following the pattern in
the jasmine typings, though, you should copy everything to a "v2" folder
and then rev the main typings file to v3 with your change.


Gabe

**Comment by stamminator** [comment]
Gotcha. So is the version number of the package some managed process that's out of our control? Just wondering how people get the correct version that corresponds to the library they're using without combing the source code for [mentions of which version it corresponds to](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/jasmine/index.d.ts#L1).

**Comment by gmoothart** [comment]
The jasmine version is just a comment in the typings file, which you linked
to. In practice most typings changes are additive and not breaking changes
(as is the case with your proposed change) so this isn't too bad. You are
not <https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7719> alone
<https://stackoverflow.com/questions/44848828/typescript-types-version-related-to-library-version>
in
thinking this is insufficient but it is just the way it is.

**Comment by stamminator** [comment]
Thanks for the info!

**Comment by stamminator** [comment]
So I'm working on a 3.0 version (because that's the first one where `withArgs` was introduced) and I'm making some quality of life changes as well to some of the method signatures and JSDoc comments to adhere to the [official version docs](https://jasmine.github.io/api/3.0/global.html), but I'm noticing some peculiarities that make we wonder how accurate their official docs are. Take [`xit`](https://jasmine.github.io/api/3.0/global.html#xit), for instance. If it's just a temporarily disabled `it`, why should it change `it`'s method signature by dropping the `timeout` param? Same for [`fit`](https://jasmine.github.io/api/3.0/global.html#fit) — why should it make the `testFunction` param required when it's optional for `it`?

Based on your experience with this project, should I take the word of these docs and make the typings conform to them, or do I need to dig into the actual Jasmine source code (and maybe test it out) to make sure conforming the typings to the docs won't result in runtime errors? I'd appreciate the feedback of any prior authors.

**Comment by steverice** [comment]
Not a prior author, but I have noticed a number of places where the types do not match the source.

For example, jasmine's spy strategy `.and.throwError` [takes an `Error` or a `string`](https://github.com/jasmine/jasmine/blob/v2.8.0/src/core/SpyStrategy.js#L77), but these type definitions have it as [just a string](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2ae8bc7a1c05064713371851d1a7ce26f02f8841/types/jasmine/index.d.ts#L642) (both for jasmine 2.8). To your point however, even the [official Jasmine documentation gets it right](https://jasmine.github.io/api/3.0/SpyStrategy.html#throwError).

I've come across a few cases like this, so I suspect there are more. I think it'd be a marked improvement to just bring these types in line with what the official docs say. Those docs appear to be generated directly from the JSDoc in the source, so running something like https://www.npmjs.com/package/tsd-jsdoc and doing a diff may be an easier way to spot issues.

**Comment by janriemer** [comment]
#30872 closes this.

> For example, jasmine's spy strategy .and.throwError takes an Error or a string, but these type definitions have it as just a string (both for jasmine 2.8).

I'm going to do a PR for this now.

**Comment by DmitryEfimenko** [comment]
this can be closed

**Comment by Blackbaud-JasonBodnar** [comment]
Is this supposed to allow us to use `withArgs()` on objects created with `createSpyObj()`?

I'm using jasmine 3.4.0:

$ npm view jasmine version
3.4.0

I create my spy:

```
mockAccessResolverService =
      jasmine.createSpyObj<AccessResolverService>('AccessResolverService', ['resolveAccessByEntitlements', 'resolveAccess']);
```

When I try to define the behavior for a method:

```
mockAccessResolverService.resolveAccess.withArgs([ADD_EDIT_PERMISSION]).and.returnValue(Observable.of(false));
```

I get:

```
TypeError: mockAccessResolverService.resolveAccess.withArgs is not a function
```

**Comment by zvirja** [comment]
@Blackbaud-JasonBodnar Please ensure to install the latest `@types/jasmine`, as your sample works perfectly fine for me.
