### ISSUE TITLE
Lodash: Question about ObjectIterator

### ISSUE THREAD

**Issue by ersimont** [DefinitelyTyped/DefinitelyTyped#27954]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aj-r I see you modified the code near this recently

If you do not mention the authors the issue will be ignored.

---

I am developing/maintaining [Micro-dash](https://github.com/simontonsoftware/micro-dash), and ran into interesting problems recently around iteratees. Looking at the typing definitions for lodash here, I see
```ts
    // Note: key should be string, not keyof T, because the actual object may contain extra properties that were not specified in the type.
    type ObjectIterator<TObject, TResult> = (value: TObject[keyof TObject], key: string, collection: TObject) => TResult;
```

That "Note" is a great point; just because an object matches a given type doesn't mean that it _only_ has the keys in that type. E.g.:

```ts
type NarrowType = { mainVariable: number };
const wideObject = { mainVariable: 1, anotherVariable: 'two' };
const narrowObject: NarrowType = wideObject;
_.forEach(narrowObject, (value, key) => {
  // "key" will take more values than just `keyof NarrowType`
  // (i.e. `anotherVariable`)
});
```

However, that same rationale applies to `value`. It will take more values than just `Narrow[keyof Narrow]` (which evaluates to `number`). Specifically, for the second iteration it will be the `string` 'two'. But applying this insight would mean `value` should really be `any`, which is less useful for the common case that the object contains _only_ the attributes defined by its type.

So finally, my question: what is the rationale for making `value` narrowly defined (`TObject[keyof TObject]` instead of `any`), but `key` more widely defined (`string` instead of `keyof TObject`)? I'd love to be pointed to a good discussion about that (or to have one here) as I improve the typing definitions for my own library.

Thanks!

**Comment by ersimont** [comment]
I guess I'll follow the PR template instructions and mention all the authors listed in `index.d.ts`:
- @bczengel
- @chrootsu
- @stepancar
- @aj-r
- @ailrun
- @e-cloud
- @thorn0
- @jtmthf
- @DomiR

**Comment by aj-r** [comment]
That's a good question and unfortunately I don't have a good answer. For dictionary/indexed types, we definitely want to make `value` have a specific type. But for normal object types, I'm not sure.

**Comment by ersimont** [comment]
OK. Thank you for getting back to me. It seems like a decision between being more technically correct (use the types `any` and `string`), verses more useful in the common case (`T[keyof T]` and `keyof T`). At least for now, I decided to go with the "more useful in the common case" approach below. But if anyone else has more thoughts I would love to hear them!
```ts
export interface NumberKeyedObject {
  [key: number]: any;
}

export type ObjectIteratee<T, O> = <K extends keyof T>(
  item: T[K],
  key: T extends NumberKeyedObject ? string : K,
) => O;
```

**Comment by Terverok** [comment]
Hi, I've connected issue with type of `map`. I want to iterate through object that keys have `number` type, but ObjectIteratee doesn't allow iteratee that takes as a second argument type `number` as a key.
```typescript
type NumberKeyedObject = {
    [key: number]: sth;
}
```
In place where I've
```typescript
map(NumberKeyedObject, (value: sth, key: number) => { ... }))
```
It gives me an error: **`Type 'string' is not assignable to type 'number | undefined'`**
I think that types for keys should be more specific than generic **"string"**

**Comment by aj-r** [comment]
I think at runtime, the keys in the callback will always be strings, even if you declared them as numbers (e.g. `1` will be converted to `"1"`). Will need to double check though.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
