### ISSUE TITLE
[@types/restify] The RedirectOptions interface does not accept object in query parameter

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [DefinitelyTyped/DefinitelyTyped#27965]
I tried using the @types/restify package and had problems. The RedirectOptions interface does not enable the query parameter to be used with an object. Today the [implementation accepts only string](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2025fc00e63ca97fed52107237fd4d56bca0e392/types/restify/index.d.ts#L854). 

code like this is not possible for example

```js
    return res.redirect({
      pathname: '/resetPassword',
      query: {
        token: newToken
      }
    }, next)
```

@blittle @stevehipwell @leanazulyoro @mgebundy one suggestion is to change the code to support the [documentation example](http://restify.com/docs/response-api/#redirect) to accept an object but I do not know if there is an interface ready for this

```js
export interface RedirectOptions {
    /**
     * redirect location's query string parameters
     */
    query?: string|object;
}
```
What do you think?

**Comment by mgebundy** [comment]
Hi @carvalhoviniciusluiz 

Yeah, that interface looks like it needs to be updated. Feel free to submit a PR, and I'll give it a review!

**Comment by carvalhoviniciusluiz** [comment]
need to set a typing?
```js
type Query = { [key: string]: any }

export interface RedirectOptions {
    query?: string|Query
}
```

or may be
```js
export interface RedirectOptions {
    query?: string|{ [key: string]: any }
}
```
What is the ideal form?

**Comment by mgebundy** [comment]
@carvalhoviniciusluiz from my digging just `Object` should be fine, it doesn't need to be so specifically typed.
