### ISSUE TITLE
[@types/qlik-engineapi] wrong definition of interface IGenericDimensionsListProperties

### ISSUE THREAD

**Issue by ralfbecher** [DefinitelyTyped/DefinitelyTyped#27970]
interface IGenericDimensionsListProperties extends IGenericProperties {
        qInfo: IGenericMeasureListNxInfo;
        qDimensionListDef: IDimensionListDef;
    }

qInfo needs to be defined as: **IGenericDimensionListNxInfo**

**Comment by konne** [comment]
@ralfbecher thank for the contribution
