### ISSUE TITLE
@types/react 16.4.8 breaks prop-types

### ISSUE THREAD

**Issue by webpepper** [DefinitelyTyped/DefinitelyTyped#28015]
Here's an example that works fine with versions _prior_ to 16.4.8

**MyComponent.tsx**
```
import * as React from "react";
import * as PropsTypes from "prop-types";

interface IProps {
  hello?: string;
  world?: boolean;
}

export const MyComponent: React.SFC<IProps> = props => <div>Hello World!</div>;

MyComponent.propTypes = {
  hello: PropsTypes.string,
  world: PropsTypes.bool
};
```
I'm not 100% sure where exactly the issue is coming from but downgrading to 16.4.7 makes everything work.

With 16.4.8 I get this error:

```
[ts]
Type '{ hello: Requireable<string>; world: Requireable<boolean>; }' is not assignable to type 'ValidationMap<IProps> | undefined'.
  Type '{ hello: Requireable<string>; world: Requireable<boolean>; }' is not assignable to type 'ValidationMap<IProps>'.
    Types of property 'hello' are incompatible.
      Type 'Requireable<string>' is not assignable to type 'Validator<string | undefined>'.
        Types of property '[nominalTypeHack]' are incompatible.
          Type 'string | null | undefined' is not assignable to type 'string | undefined'.
            Type 'null' is not assignable to type 'string | undefined'.
```

Adding `.isRequired` to all props makes the error go away, but... why?

```
MyComponent.propTypes = {
  hello: PropsTypes.string.isRequired,
  world: PropsTypes.bool.isRequired
};
```

**Comment by webpepper** [comment]
No updates?

This "improvement" breaks tens of projects with tons of code. I'm removing prop-types everywhere I can (since Typescript interfaces are used) but this issue is still a real pain in the rear compartment.

For now my solution is to manually install @types/react@16.4.7 but then again, it has to be done for every single project individually.

It's one of those cases when a non-breaking release (16.4.x) actually breaks everything (I may be wrongfully assuming you follow semver) 😞

**Comment by ipanasenko** [comment]
BTW, it's not possible to remove usage of `prop-types`, if context is used.
Also locking `@types/react` to 16.4.7

**Comment by icopp** [comment]
I'll second the 😱 at this breaking a ton of existing projects in a minor version update.

**Comment by martpie** [comment]
I had to switch to a newer version of React typings for the better `defaultProps` handling, but this issue is extremely frustrating.

Using `@ts-ignore` is not a solution

**Comment by Shakahs** [comment]
I have found the pull request that introduced this issue, it includes a very long discussion about why this was done and how to migrate your code: #26813.

I do not expect this "bug" to be fixed, the change is apparently intentional and permanent.

**Comment by ipanasenko** [comment]
@Shakahs are you sure that's it? I think it's about different issue, and it was reverted: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26946

**Comment by Shakahs** [comment]
@ipanasenko I see, you are right, my apologies. I skimmed the PR and it seemed to fit. 
Hoping for a resolution to this, or at least a migration path. I too have pinned to 16.4.7 for now.

**Comment by milesj** [comment]
I've had to lock to 16.4.7 everywhere also. This really needs to be resolved, or the changes in x.8 needs to be reverted.

**Comment by pleunv** [comment]
I was looking into incrementally adding types via JSDoc yesterday and spent most of the day hitting this wall repeatedly. I eventually gave up and still have absolutely no idea how to do this. Is there any sort of documentation for these changes? All I can say is: this is not adoption-friendly. At all.

**Comment by westandy-dcp** [comment]
This is still broken at 16.4.18.  Has anyone narrowed down the issue?

**Comment by milesj** [comment]
@westandy-dcp This was the closest fix: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29887

But a recent change on master in regards to JSX has broken everything React related. So we're in a shitty limbo state now.

**Comment by evans** [comment]
@milesj Any update on the status of React related PRs?

Unfortunately I haven't followed the limbo state closely, though if there is something I can do to help this along, please let me know. With the release of TS 3.2, does that change our status?

**Comment by milesj** [comment]
@evans All of the @types package using React need to be updated to 3.2. Not sure on the progress of this.

**Comment by andrewbranch** [comment]
@ferdaber continuing our conversation from #31133, can you give an example of what the `nominalTypeHack` accomplishes? I.e. either some code that only compiles with it or some bad code that only doesn't compile with it? (Did that make sense? 😄)

**Comment by ferdaber** [comment]
If someone is willing to check and run the proper tests, we may be able to solve this issue by changing the static `propTypes` property of `ComponentClass` and `FunctionComponent` such that it will create a `ValidationMap` of its props that transform nullable and undefined-able props into both, so that it satisfies the DX of developers not having to deal with writing their props as precisely, but also satisfies the type checking of the compiler.

**Comment by andrewbranch** [comment]
I'm happy to work on this with a little more guidance on how to make sure I'm not breaking the existing type inferences. I can find lots of edits to @types/prop-types that make the red squigglies disappear, but I'm sure they make some things overly permissive.

**Comment by ferdaber** [comment]
The change would not be to `@types/prop-types` but rather to `@types/react` instead, where the canon `FunctionComponent` and `ComponentClass` types are defined, we need to make the allowable `propTypes` property more loose than just `ValidationMap<P>`, something like `LooseValidationMap<P>` where it widens nullable or undefined-able types to both.

**Comment by ferdaber** [comment]
This should be fixed by #31280

**Comment by emilio-martinez** [comment]
Is this supposed to be resolved? I'm still getting this  issue even though I can see the PR above reflected in my types

**Comment by milesj** [comment]
@emilio-martinez This hasn't been an issue for a while now. Be sure your react and all related `@types` are at the latest version.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
