### ISSUE TITLE
[@types/qlik-engineapi] extend definition of interface IDimensionItemLayout

### ISSUE THREAD

**Issue by ralfbecher** [DefinitelyTyped/DefinitelyTyped#28078]
Please add property qInfo:

    interface IDimensionItemLayout {
        qInfo: INxInfo;
        qMeta: INxMetaTitleDescriptionTag;
        qData: null;
    }

@konne

**Comment by konne** [comment]
@ralfbecher should be fixed after this PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28088
