### ISSUE TITLE
@types/sharp - input not optional

### ISSUE THREAD

**Issue by ShayBox** [DefinitelyTyped/DefinitelyTyped#28100]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/sharp` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @lith-light-g @wooseopkim 

If you do not mention the authors the issue will be ignored.

Line 18, says sharp's input param can be optional, and it can be, but does not actually allow me to exclude it
```js
sharp({
	create: {
		background: '#FFFFFF',
		channels: 4,
		height: 100,
		width: 100,
	},
});
```
Code to reproduce

**Comment by wooseopkim** [comment]
I can't use my laptop right now, so could you provide the error message? The parameter is marked optional(`options?: sharp.SharpOptions`) already.

**Comment by ShayBox** [comment]
The input param and options are both marked as optional, but it doesn't work like that, you can't use a second param if you don't give the first.
With sharp you can exclude the input param and only give the options just fine.

**Comment by wooseopkim** [comment]
@ShayBox Sorry for late response, I'll work on this issue tonight and see if I can find a working solution.
