### ISSUE TITLE
Recompose: `Subscribable` generic does not capture RxJS `Observable`

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#28103]
Copied from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27525:

When using stream helpers e.g. `mapPropsStream`, the `Subscribable` generic does not capture RxJS `Observable`:

``` ts
function testMapPropsStreamRxJs() {
    type OwnProps = { a: number; };
    type StreamProps = { b: number; };
    const transformFn = (_props: RxJS.Observable<OwnProps>): RxJS.Observable<StreamProps> => RxJS.of({ b: 1 });
    const enhancer = mapPropsStream(transformFn)
    // $ExpectType ComponentEnhancer<OwnProps, StreamProps>
    enhancer
}
```

This fails with:

```
Error: /Users/OliverJAsh/Development/DefinitelyTyped/types/recompose/recompose-tests.tsx:398:5
ERROR: 398:5  expect  Expected type to be:
  ComponentEnhancer<OwnProps, StreamProps>
got:
  ComponentEnhancer<{}, {}>
```

Here is a smaller example of the problem:

``` ts
declare function identitySubscribable<T>(
  subscribable: Subscribable<T>,
): Subscribable<T>;

declare const props$: Observable<OwnProps>;

const subscribable = identitySubscribable(props$);
// $ExpectType Subscribable<OwnProps>
// but got Subscribable{}>
subscribable;

// No type error, as expected :-)
const props2$: Subscribable<OwnProps> = props$;
```

Why is the generic not inferred (and thus falling back to `{}`)?

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @iskandersierra @mrapogee @clayne11 @Pajn @lucasterra @DogPawHat

If you do not mention the authors the issue will be ignored.

**Comment by Pajn** [comment]
I don't think Typescript is capable of doing the required level of inference to figure out those generic parameters.

To figure out that an `Observable<OwnProps>` is an `Subscribable<OwnProps>` requires typescript follow the generic parameter of Observable to the subscribe method to the RxJs Observer parameter to the next parameter, recognize that that corresponds to recomposes Observer type an that the parameter matches the Observer type parameter, then back out to the Subscribable type and recognize that it can infer it's type parameter from the Observer types type parameter via them subscribe method.

It's a super long inference chain with multiple non-obvious inference points.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
