### ISSUE TITLE
@types/puppeteer - Error when compiling

### ISSUE THREAD

**Issue by iserifith** [DefinitelyTyped/DefinitelyTyped#28104]
Hi,
Im trying use puppeteer in an angular app and get this error when compiling.

`ERROR in node_modules/@types/puppeteer/index.d.ts(15,38): error TS1005: ';' expected.
node_modules/@types/puppeteer/index.d.ts(15,73): error TS1005: '(' expected.
node_modules/@types/puppeteer/index.d.ts(15,76): error TS1005: ')' expected.
node_modules/@types/puppeteer/index.d.ts(18,40): error TS1005: ';' expected.
node_modules/@types/puppeteer/index.d.ts(18,68): error TS1005: ';' expected.
node_modules/@types/puppeteer/index.d.ts(18,71): error TS1109: Expression expected.`

and sometimes [https://hastebin.com/upereteman.coffeescript](https://hastebin.com/upereteman.coffeescript) .

@marvinhagemeister @cdeutsch @ksm2

**Comment by marvinhagemeister** [comment]
@iserifith Are you sure that your `node_modules` directory is up to date? The linked output looks like some dependencies are missing.

**Comment by iserifith** [comment]
It was fresh angular instalation. I even tried remove the node modules folder and install it again. Here is my [package.json](https://hastebin.com/cavojinoxa.json)

**Comment by iserifith** [comment]
I switch the typescript version to 2.8.1. however [this](https://hastebin.com/ruwoquniwa.coffeescript) still persist. Could it be a path issue? I manually check the node_module folders and everything is there.

**Comment by ksm2** [comment]
@iserifith You are using puppeteer which is made for Node.js in a browser environment. Therefore, modules like `fs`, `crypto` and `child_process` are missing. This has nothing to do with these typings.

**Comment by iserifith** [comment]
That makes sense. Thank you.

**Comment by jsdevtom** [comment]
This still applies to node environments. Simple reproduction steps:

1. Set up basic TypeScript environment: `git clone --depth=1 https://github.com/Microsoft/TypeScript-Node-Starter.git <project_name>`
2. install dependencies: `cd <project_name> && npm i -S puppeteer && npm i -S -D @types/puppeteer`
3. go to `server.ts` and import puppeteer: `import puppeteer from 'puppeteer';`
4. try to compile `npm run build`

I have tried lots of combinations of ignoring `node_modules` to no avail.

**Comment by ksm2** [comment]
@jsdevtom You need at least TypeScript 2.8 (see here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/puppeteer/index.d.ts#L7)
I tried your reproduction steps, using TypeScript 2.8 works:

1. `npm i typescript@2.8`
2. `npm run build`

**Comment by jsdevtom** [comment]
@ksm2 Thank you! That worked!
