### ISSUE TITLE
@types/cheerio .get() can return more types than stated in the definitions

### ISSUE THREAD

**Issue by gaspardip** [DefinitelyTyped/DefinitelyTyped#28125]
- [X] I tried using the `@types/cheerio` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @blittle @vilic @wmaurer @umarniz @LiJinyao @chennakrishna8

====

Current types state `.get()` can only return `string[]`, `CheerioElement[]` or `CheerioElement`.

This is not true, [example code](https://runkit.com/gaspardip/5b73a04f4e7a6100115dd595)

Should be `any`.

Regards.

**Comment by AzSiAz** [comment]
Issue can be closed
