### ISSUE TITLE
[react] component.propTypes requires all props to be defined in the ValidationMap

### ISSUE THREAD

**Issue by vitosamson** [DefinitelyTyped/DefinitelyTyped#28142]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei 

Say you have a `Button` component that's defined as:

```tsx
interface Props extends React.ButtonHTMLAttributes<any> {
  size: string;
}

export const Button: React.SFC<Props> = ({ size, children, ...props }) => (
  <button className={`btn btn-${size}`} {...props}>{ children }</button>
)

Button.propTypes = {
  size: PropTypes.string.isRequired,
}
```

TS will throw the following error:

```
[ts]
Type '{ size: Validator<string>; }' is not assignable to type 'ValidationMap<Props>'.
  Property 'autoFocus' is missing in type '{ size: Validator<string>; }'.
(property) React.StatelessComponent<Props>.propTypes?: PropTypes.ValidationMap<Props> | undefined
```

It looks like it expects every prop that's defined in `Props` to be included in `propTypes` - in this case, since `Props` extends `React.ButtonHTMLAttributes`, that includes all of the possible `button` props.

I tried using `Partial<Props>` [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L344):

```ts
    interface StatelessComponent<P = {}> {
        ...
        propTypes?: ValidationMap<Partial<P>>;
        ...
    }
```

But that does not resolve the issue, so I'm not sure what the right approach is here.

Typescript: 3.0.1
@types/react: 16.4.10

**Comment by ferdaber** [comment]
This is a known issue, I will be fixing this in a later PR. 

Problem line is here: (the optional modifier is removed): https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d42a3e4e16e57ff1fe5a18c300f568b6be4eb608/types/prop-types/index.d.ts#L27

**Comment by vitosamson** [comment]
@ferdaber I was just about to post the same and tag you. Is there a PR open for that or do you want me to make one?

**Comment by ferdaber** [comment]
You can make one if you wish, that would be greatly appreciated. I haven't started on it.

**Comment by andrewbranch** [comment]
I opened a PR for this. Making ValidationMaps require every prop to have a validator is pretty catastrophic if your components tend to extend `React.HTMLAttributes` 😅
