### ISSUE TITLE
@types/web3 not fulfilling needs 

### ISSUE THREAD

**Issue by justinkchen** [DefinitelyTyped/DefinitelyTyped#28144]
One issue with it is that imports have to be like `import We3 = require('web3');` because of the way it is exported (https://stackoverflow.com/questions/39415661/what-does-resolves-to-a-non-module-entity-and-cannot-be-imported-using-this)

The other is that it would be better as a more descriptive namespace I think similar to the 0xproject definition of it

https://github.com/0xProject/0x-monorepo/blob/development/packages/typescript-typings/types/web3/index.d.ts

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@simon-jentzsch
@nitzantomer
@zurbo
@yxliang01
@phra 
@naddison36
@icaroharry
@linusnorton
@jpeletier
@anneau
@matrushka
@andrevmatos
@Levino 
@zlumer 
@archangel-irk

**Comment by Levino** [comment]
The way you import the library is determined by the way the library is exported. There is nothing we can change about that fact that `web3` uses [`module.export`](https://github.com/ethereum/web3.js/blob/190e4973d105624f553aa1ee51ed1570d63b77e6/packages/web3/src/index.js#L78). We are just typing the status quo here. We are not changing the library. If there is a better way to do this please elaborate.

I do not understand the second problem you describe.

I suggest you answer the following questions:

What did you do? What did you expect? What happened?

Thanks.

**Comment by justinkchen** [comment]
For the first problem, do you know why other modules can be imported like `import * as _ from 'lodash'` for example, but web3 can't?

For the second problem, the thing is that no other types are exported from the package so I can't do things like export a a Web3.ContractInstance or get a Provider type without just basically copy/pasting the types locally.  Would be good to create a namespace similar to the 0xproject and export other types relevant to working with web3 instead of just the class.

**Comment by justinkchen** [comment]
What did you do? 
Tried to use @types/web3 instead of the 0xproject typings

What did you expect? 
Things would work as is

What happened?
compile failed with the non-module error ((https://stackoverflow.com/questions/39415661/what-does-resolves-to-a-non-module-entity-and-cannot-be-imported-using-this)
then i tried changing to `import Web3 = require('web3')` but then lost all the namespaced types that 0xproject provides with their package.

**Comment by Levino** [comment]
One quick remark: typings from `0xproject` are for `web3@0.20.x` not for `web3@1.x`.

**Comment by Levino** [comment]
https://github.com/lodash/lodash#lodash:
> The Lodash library exported as a UMD module.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
