### ISSUE TITLE
@types/koa-router incompatible type with graphiqlKoa() ?

### ISSUE THREAD

**Issue by AndrewRayCode** [DefinitelyTyped/DefinitelyTyped#28167]
I'm using `@types/koa-router`

I have this code:

```jsx
import * as KoaRouter from 'koa-router';
import { graphiqlKoa, graphqlKoa } from 'apollo-server-koa';

const router = new KoaRouter();

router.get('/graphiql', graphiqlKoa({
  endpointURL: '/graphql',
}));
```

It's raising this type signature error:

```
Argument of type '(ctx: Context) => Promise<void>' is not assignable to parameter of type 'IMiddleware'.
  Types of parameters 'ctx' and 'ctx' are incompatible.
    Type 'IRouterContext' is not assignable to type 'Context'.
      Types of property 'app' are incompatible.
        Type 'import("pplicatio")' is not assignable to type 'Application'.
          Types of property 'middleware' are incompatible.
            Type 'import("myproject/node_modules/@types/koa-compose/index").Middleware<import("pplicatio").Context>[]' is not assignable to type 'import("myproject/node_modules/@types/koa-compose/index").Middleware<import("myproject/node_modules/@types/koa/index").Context>[]'.
              Type 'import("myproject/node_modules/@types/koa-compose/index").Middleware<import("pplicatio").Context>' is not assignable to type 'import("myproject/node_modules/@types/koa-compose/index").Middleware<import("myproject/node_modules/@types/koa/index").Context>'.
                Types of parameters 'context' and 'context' are incompatible.
                  Type 'import("myproject/node_modules/@types/koa/index").Context' is not assignable to type 'import("pplicatio").Context'.
                    Property 'params' is missing in type 'Context'.
```

I'm brand new to typescript and working on a koa server to serve GraphQL. This type error is huge and I'm not sure where to begin on it.

@andy-ms @jackwilsdon @sdbondi I see you have worked on this file, any ideas?

**Comment by andy-ms** [comment]
@AndrewRayCode When I try that I get an error `Module '"[....]/node_modules/apollo-server-koa/dist/index"' has no exported member 'graphiqlKoa'.` (same for `graphqlKoa`).

**Comment by sibelius** [comment]
we need types for `koa-graphql` as well

**Comment by Waltarb** [comment]
> @AndrewRayCode When I try that I get an error `Module '"[....]/node_modules/apollo-server-koa/dist/index"' has no exported member 'graphiqlKoa'.` (same for `graphqlKoa`).

I also have this problem, anyone have a solution?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
