### ISSUE TITLE
[@types/react] Type inference not working for callback in React component with tagged union props

### ISSUE THREAD

**Issue by sgoll** [DefinitelyTyped/DefinitelyTyped#28174]
**TypeScript Version:** 3.1.0-dev.20180813

**@types/react Version:** 16.4.11

**Code:**

```ts
import * as React from "react";

type Props =
  | {
      type: "foo";
      onChange(value: number): void;
    }
  | {
      type: "bar";
      onChange(value: string): void;
    };

class Foo extends React.Component<Props> {}

const foo = <Foo type="foo" onChange={value => {}} />;
```

**Expected behavior:** TypeScript should be able to infer that the argument `value` in the `onChange` handler of `<Foo/>` has type `number`.

**Actual behavior:** TypeScript is unable to infer the type of `value` and reports (in strict mode): `[ts] Parameter 'value' implicitly has an 'any' type.`

I am unsure if this is a (known) deficiency in TypeScript, a limitation of the `@types/react` package, or maybe even intended behaviour.

@johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei

**Comment by ericanderson** [comment]
Why not just use generics?

**Comment by ferdaber** [comment]
@ericanderson can generic type parameters be inferred for generic classes used as value-based components? AFAIK back in TS 2.7 (last I checked) that wasn't possible.

**Comment by sgoll** [comment]
@ericanderson The example in my original post is somewhat contrived. For my actual use case, I have arbitrary tagged unions with inhomogeneous members instead of the above, so something more like the following:

```ts
type Props =
  | {
      type: "foo";
      methodOne(foo: number): void;
      methodTwo(bar: number): void;
    }
  | {
      type: "bar";
      methodTwo(bar: string): void;
      methodThree(baz: string): void;
    };
```

Usually I would define separate components for each type of the union but in this case the union's origin is from a mapped type over some external definition and may contain an arbitrary number of types.

**Comment by sgoll** [comment]
To be more precise, the problem only happens when two types in the union contribute to the same method and the method types are not identical, e.g.

```ts
type Props =
  | {
      type: "foo";
      onFoo(value: number): void;  // only for type="foo"
      onBaz(value: number): void;  // used in both "foo" and "bar", here with "number"
    }
  | {
      type: "bar";
      onBar(value: string): void;  // only for type="bar"
      onBaz(value: string): void;  // used in both "foo" and "bar", here with "string"
    };
```

In the following element declarations, TypeScript can infer `onFoo` and `onBar` correctly (argument is either of type `number` or type `string`) but cannot infer `onBaz` (argument is of type `any`):

```ts
const foo = <Foo type="foo" onFoo={value => {}} onBaz={value => {}} />;
const bar = <Foo type="bar" onBar={value => {}} onBaz={value => {}} />;
```

If I change the definition of `Props` so that `onBaz` is identical, everything works fine. It seems to me that the overloading is the root of the issue here.

Interestingly, I would expect TypeScript to either infer the proper type (depending on `type` that would be either `number` or `string`), or at least a union of possible types (which would be `number | string`) instead of `any`. Strange.

**Comment by Hotell** [comment]
I wasn't sure if this is really issue with JSX types and can verify that it indeed is. Everything works as expected in vanilla JS:

```tsx
import React, { Component } from 'react'

type Props =
  | {
      type: 'foo'
      onFoo: (value: number) => void // only for type="foo"
      onBaz: (value: number) => void // used in both "foo" and "bar", here with "number"
    }
  | {
      type: 'bar'
      onBar: (value: string) => void // only for type="bar"
      onBaz: (value: string) => void // used in both "foo" and "bar", here with "string"
    }

class Foo extends Component<Props> {}

// ERROR
const foo = <Foo type="foo" onFoo={(value) => {}} onBaz={(value) => {}} />
// ERROR
const bar = <Foo type="bar" onBar={(value) => {}} onBaz={(value) => {}} />

const fooObj: Props = {
  type: 'foo',
  onFoo: (value) => {},
  onBaz: (value) => {},
}

// OK
const barObj: Props = {
  type: 'bar',
  onBar: (value) => {},
  onBaz: (value) => {},
}
```
// OK

Also might be related to https://github.com/Microsoft/TypeScript/issues/25503 ? not sure

**Comment by Hotell** [comment]
Although leveraging generics fixes your issue:

```tsx
import React, { Component } from 'react'
type Props<T> =
  | {
      type: 'foo'
      onFoo: (value: T) => void // only for type="foo"
      onBaz: (value: T) => void // used in both "foo" and "bar", here with "number"
    }
  | {
      type: 'bar'
      onBar: (value: T) => void // only for type="bar"
      onBaz: (value: T) => void // used in both "foo" and "bar", here with "string"
    }

class Foo<T> extends Component<Props<T>> {}

const foo = (
  <Foo<number> type="foo" onFoo={(value) => {}} onBaz={(value) => {}} />
)
const bar = (
  <Foo<string> type="bar" onBar={(value) => {}} onBaz={(value) => {}} />
)
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
