### ISSUE TITLE
@types/chromecast-caf-receiver not correctly scoped

### ISSUE THREAD

**Issue by enjikaka** [DefinitelyTyped/DefinitelyTyped#28190]
I tried using the `@types/chromecast-caf-receiver` package and had problems.
Using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Authors: @craigrbruce

Installing @types/chromecast-caf-receiver and then starting to make a CAF Receiver app like the latest information from the google docs ( https://developers.google.com/cast/docs/caf_receiver_basic ) result in an error already on the first line:

```
const context = cast.framework.CastReceiverContext.getInstance();
const playerManager = context.getPlayerManager();
```

```
src/js/main.js:1:22 - error TS2339: Property 'framework' does not exist on type 'typeof import("/.../node_modules/@types/chromecast-caf-receiver/index")'.

1 const context = cast.framework.CastReceiverContext.getInstance();
```

The cast library is included in the HTML like so: `<script src="//www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js"></script>`

**Comment by enjikaka** [comment]
Hi @craigrbruce, thanks for replying!

I think the problem is rather that `chromecast-caf-receiver/index.d.ts` does not have the correct structure. It should expose `framework` on the case namespace.

I tweaked around a bit with it now and got it to work. I'll make a PR.

**Comment by craigrbruce** [comment]
Hi @enjikaka - I would be interested to see what you have done and perhaps need to reproduce your problem. `framework` is exported in a separate file .. i.e. `cast.framework`. 

I am working for Australia's leading broadcaster building a large CAF application using these types for several months and have not encountered any issues. Of course, I could be missing something or have generally exported modules/namespaces in an unintuitive way :)

Looking forward to your PR.

**Comment by enjikaka** [comment]
@craigrbruce I've never played around with TypeScript type defs so I might be way off track here but I attempted adding a global const and a declaring the namespace with an interface which has the imported framework as a prop. Like so (index.d.ts);

```
import Framework from './cast.framework';

declare namespace castsdk {
    interface Cast {
        framework: Framework;
    }
}

declare global {
    const cast: castsdk.Cast;
}
```

I've played around a lot in the code now so it broke, but a while ago after adding the global const it worked; then the global `cast` from the script tag got connected to the type def! 

I'll also point out that I am not using TypeScript directly, but the jsconfig in VSCode to typecheck normal JS with TypeScript. See: https://code.visualstudio.com/docs/languages/javascript#_type-checking

**Comment by KakoDaSeZove** [comment]
Any updates for this? I am facing with the same issue...

**Comment by harabara** [comment]
I can't even import from `from 'chromecast-caf-receiver/framework'` it doesn't seem to be exposed.

**Comment by craigrbruce** [comment]
Hi @harabara, @KakoDaSeZove  and @enjikaka 

I have submitted a PR that addresses this issue:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31012

Sorry for the late response, it has been exceptionally busy.

Cheers

**Comment by craigrbruce** [comment]
Hi again @harabara @KakoDaSeZove and @enjikaka 

This is now merged and should work for you now.

Depending on your setup, you may need to add a `global.d.ts` and add `/// <reference types="chromecast-caf-receiver" />` at the top to get it running

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
