### ISSUE TITLE
[@types/node] v10.7.1 has wrong definition for Decipher

### ISSUE THREAD

**Issue by etsuo** [DefinitelyTyped/DefinitelyTyped#28200]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

`index.d.ts` has:
```
    export interface Decipher extends NodeJS.ReadWriteStream {
        update(data: Buffer | NodeJS.TypedArray | DataView): Buffer;
        update(data: string, input_encoding: HexBase64BinaryEncoding): Buffer;
        update(data: Buffer | NodeJS.TypedArray | DataView, input_encoding: any, output_encoding: Utf8AsciiBinaryEncoding): string;
        // second arg is ignored
        update(data: string, input_encoding: HexBase64BinaryEncoding, output_encoding: Utf8AsciiBinaryEncoding): string;
        final(): Buffer;
        final(output_encoding: string): string;
        setAutoPadding(auto_padding?: boolean): this;
        // setAuthTag(tag: Buffer | NodeJS.TypedArray | DataView): this;
        // setAAD(buffer: Buffer | NodeJS.TypedArray | DataView): this;
    }
```
It looks like the change was introduced here: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/2bb44da669f80e3bf7b2592379294f81dff673ee by @Flarna

As per the latest nodejs docs, `Decipher` still clearly supports:

* `setAuthTag` (https://nodejs.org/api/crypto.html#crypto_decipher_setauthtag_buffer)
* `setAAD` (https://nodejs.org/api/crypto.html#crypto_decipher_setaad_buffer_options)

I'd submit a PR, but this seems really intentional and I want to make sure that I understand why this change was made before I dive in.

**Comment by Flarna** [comment]
I think it was not my commit mentioned above; it was via PR #26655. fyi @ZaneHannanAU 

According to docs `Decipher` support `setAuthTag` and `setAAD` only for modes GCM and CCM and for these interfaces `DecipherCCM` and `DecipherGCM` were added so I'm not sure what is missing here.

But maybe the in your case typescript is not able to detect the correct overload of `createDecipheriv` used and as a result the return type is the base interface.

**Comment by Flarna** [comment]
I think I found the issue - the generic overload using `string` should be last and additionally `options` should be optional for all overloads:
```
    export function createDecipheriv(algorithm: CipherCCMTypes, key: string | Buffer | NodeJS.TypedArray | DataView, iv: string | Buffer | NodeJS.TypedArray | DataView, options?: CipherCCMOptions): DecipherCCM;
    export function createDecipheriv(algorithm: CipherGCMTypes, key: string | Buffer | NodeJS.TypedArray | DataView, iv: string | Buffer | NodeJS.TypedArray | DataView, options?: CipherGCMOptions): DecipherGCM;
    export function createDecipheriv(algorithm: string, key: string | Buffer | NodeJS.TypedArray | DataView, iv: string | Buffer | NodeJS.TypedArray | DataView, options?: stream.TransformOptions): Decipher;
```

**Comment by etsuo** [comment]
thanks @Flarna - my apologies for misidentifying you as having introduced the change.
