### ISSUE TITLE
[@types/ioredis] psubscribe interface doesn't match api

### ISSUE THREAD

**Issue by sushi30** [DefinitelyTyped/DefinitelyTyped#28220]
**Expected:** psubscribe is supposed to accept a callback function as specified by [API](https://github.com/luin/ioredis#pubsub).

**Actual:** accepts array of strings ([link](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ioredis/index.d.ts#L422))
`psubscribe(...patterns: string[]): any;`
 

- [x] I tried using the `@types/ioredis` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @plantain-00 @pietrovismara @jeffkenney @br8h @andy-ms @minestarks @aliarham11 @BastienAr @d-yokoi 

If you do not mention the authors the issue will be ignored.

**Comment by plantain-00** [comment]
PR is welcome

**Comment by sushi30** [comment]
I don't see how this is possible. Asked about it in [stackoverflow](https://stackoverflow.com/questions/51918274/how-do-i-specify-a-callback-function-after-rest-parameters-in-typescript) and will be happy to receive some input from the community.

**Comment by plantain-00** [comment]
You can add  a line`psubscribe(...patterns: any[]): any;` after that line

**Comment by sushi30** [comment]
This isn't possible as rest parameters have to be last according to TypeScript.

**Comment by pietrovismara** [comment]
@sushi30 This means the function signature of `psubscribe` is incompatible with a proper TypeScript notation. I suggest you add a new line where you remove the rest parameter and set a fixed amount of patterns, like:

```
psubscribe(pattern: string, callback: (Error, number) => void): any;
```
If that's not enough, I'm afraid I don't know what other help to offer...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
