### ISSUE TITLE
React-Navigation issue with React-Native

### ISSUE THREAD

**Issue by Sean-Brown** [DefinitelyTyped/DefinitelyTyped#28245]
I just upgraded react-navigation major versions from 1 to 2. I now witness build errors from the @types/react-navigation package:
```
node_modules/@types/react-navigation/index.d.ts(40,3): error TS2305: Module '"/Users/sbrown/Projects/sidekickmobileapp/node_modules/@types/react-navigation/node_modules/@types/react-native/index"' has no exported member 'ViewProps'.
node_modules/@types/react-navigation/index.d.ts(592,51): error TS2304: Cannot find name 'NonNullable'.
node_modules/@types/react-navigation/index.d.ts(592,71): error TS2304: Cannot find name 'NonNullable'.
```

The project uses:
react: 16.2.0
react-native: 0.52.3
react-navigation: 2.11.2
@types/react: 16.0.41
@types/react-native: 0.52.19
@types/react-navigation: 2.0.16

Is it that my react-navigation package isn't compatible with the given versions of react or react-native? The application runs fine, however our CI server fails to build the application because of these tsc "errors".

**Comment by pheromonez** [comment]
@Sean-Brown Check the version of Typescript you are running on the CI server. The `NonNullable<T>` type was added in in Typescript 2.8 (along with other conditional types): https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#predefined-conditional-types

**Comment by Sean-Brown** [comment]
Thanks I did notice that, however the other issue with `ViewProps` being undefined still exists. It appears that it is [fixed in a later release](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25363), however if I upgrade the @types/react-native version then I'm met with a slew of other errors. Also I notice that upgrading to version 2.8 has another error related to Geolocation ([known issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24573)).

For now I'm probably just going to have to set the `skipLibCheck` so that the CI server won't see those bogus errors and fail.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
