### ISSUE TITLE
@types/datatables.net incorrect return type for columns().visible()

### ISSUE THREAD

**Issue by AlexRiina** [DefinitelyTyped/DefinitelyTyped#28274]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

@omidkrad @pragmatrix @CNBoland 

I'm running in to some trouble with `api.columns().visible()`. In practice, this returns an Api wrapping an area of booleans, but the type definition seems to indicate it is a single boolean, so I get

> TS7017: Element implicitly has an 'any' type because type 'Boolean' has no index signature.
from the compiler while it works in the browser

```
api.columns().visible()
_Api(13) [false, true, false, true, true, false, false, true, true, false, false, false, false, context: Array(1), selector: {…}, tables: ƒ, table: ƒ, draw: ƒ, …]
```

`api.columns` is a `ColumnsMethodsModel` which, when evaluated has `ColumnsMethods`. `ColumnsMethods` extends `CommonColumnMethod` which has

```
        visible(): boolean;
```

I'm able to resolve my issue by adding
```
        visible(): boolean[];
```
to ColumnsMethods, but I think a more accurate solution would be along the lines of 
```
        visible(): Api<boolean>;
```
and parameterizing Api with 
```
interface Api<T> ... {
    [key: number]: T;
}
```

I'm pretty new to typescript so I apologize if this is poorly stated.

**Comment by CNBoland** [comment]
This appears to be the relevant documentation: https://datatables.net/reference/api/columns().visible()
The .visible() method accepts two optional boolean parameters and returns `DataTables.Api`.

Is this the same as you are referring to, @AlexRiina?

**Comment by AlexRiina** [comment]
Yep, exactly that.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
