### ISSUE TITLE
[stellar-sdk] Various mis-typings

### ISSUE THREAD

**Issue by ire-and-curses** [DefinitelyTyped/DefinitelyTyped#28340]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/0.8.6` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @carl-foster @TristonJ @pselden @maxbause 

I've verified these all work with `@ts-ignore`.
1. `stellar-sdk.xdr.DecoratedSignature.hint` and `stellar-sdk.xdr.DecoratedSignature.signature` are missing
2. `stellar-sdk.xdr.TransactionResult` is missing
3. `stellar-sdk.OperationCallBuilder.operation` is missing
4. `stellar-sdk.OrderbookCallBuilder` has the wrong return type (it actually returns  an `OrderbookRecord`, but  `call()` returns a `CollectionPage<OrderbookRecord>`. This one is really nasty because since it's not a CollectionPage, the cursor is not exposed, so there's no way to iterate through the full list of orders. Is this a bug in the underlying sdk itself?

**Comment by Carl-Foster** [comment]
Thanks for the report. That last one isn't too nasty, I've actually run into a similar style of the typing bug with the TransactionCallBuilder. In a fork, I've got updated types that work with TypeScript 2.8. Looks like this:
```ts
export class CallBuilder<T extends Record, U extends T | T[]= T[]> {
    constructor(serverUrl: string)
    call: U extends T[] ? CallCollectionFunction<T> : CallFunction<T>;
    cursor(cursor: string): this;
    limit(limit: number): this;
    order(direction: 'asc' | 'desc'): this;
    stream(options: {
        onmessage: (message: T) => any,
        onerror?: () => any,
    }): () => void;
}
```

**Comment by morleyzhi** [comment]
@Carl-Foster I think I'm running into OP's issue with the types for Server.accounts(). Can you provide how you declare the types for TransactionCallBuilder if CallBuilder is typed with that code snippet? Or would you be willing to update my PR with what you've ended up with?

**Comment by morleyzhi** [comment]
This is my proposed fix for the CallBuilder issue. I'm new to Typescript so I'm not 100% sure that this is doing what I think it is, but it passes tests and it works in my local repo:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34113/commits/6bbfe8b5acfbd4d92768f391a3321a19f42ad331

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
