### ISSUE TITLE
redux-form breaking changes in patch version 7.4.6

### ISSUE THREAD

**Issue by Crashthatch** [DefinitelyTyped/DefinitelyTyped#28356]
After upgrading my project to @types/redux-form@7.4.6 (from 7.4.5) I get typescript errors when building my project.

```
    TS2345: Argument of type 'never[]' is not assignable to parameter of type 'FormErrors<FormData, any> | undefined'.
  Type 'never[]' has no properties in common with type 'FormErrors<FormData, any>'. 
```

and 

```
    TS2314: Generic type 'DecoratedComponentClass<FormData, P, ErrorType>' requires 3 type argument(s).
```

It looks like these were caused by the changes here by @ethanresnick (reviewed by @paulvanbrenk, merged by @andy-ms ) : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26494/commits

I guess these are deliberate changes to enhance typing / support non-string types? But they break backwards compatibility with existing dependant projects (eg. mine). Should it have been released as a patch version? I realise that the `types/react-redux` package major should align with the `react-redux` major (ie. 7) but it still seems like this could have been a minor bump if it breaks backwards compatibility (bumping minor still isn't proper semver, but I don't see another option)?

Is there a way I can configure my project to prevent breaks like this in future when `types` packages (short of pinning to the exact version?) 

Or have I used the types incorrectly in my project somehow, which has resulted in this break?

**Comment by andy-ms** [comment]
@Crashthatch Could you provide sample code that reproduces the first error?
For the second error we could accept a PR adding a default for `ErrorType`.

> Is there a way I can configure my project to prevent breaks like this in future when types packages (short of pinning to the exact version?)

No, because `@types` packages don't follow semver and every change might be a breaking change.

**Comment by gitowiec** [comment]
There is some kind of mistake in `actions.d.ts`
```
export declare function stopSubmit(form: string, errors?: FormErrors<FormData, any>): FormAction;
```
FormData here is not used as generic, it should, at last, look like this
```
export declare function stopSubmit<FormData>(form: string, errors?: FormErrors<FormData, any>): FormAction;
```
This error makes impossible to use `stopSubmit` action with own errors payload....
