### ISSUE TITLE
@types/es6-collections causes compiler errors when targeting ES6

### ISSUE THREAD

**Issue by sci4me** [DefinitelyTyped/DefinitelyTyped#28386]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rbuckton 

I have a TypeScript project targeting ES6. When I install @types/es6-collections, I get these [errors](https://pastebin.com/5NjFxZhh). When I target ES5, there are no compiler errors.

Here's my tsconfig.json:
```
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "es6",
		"moduleResolution": "node",
		"outDir": "dist",
		"sourceMap": true
	},
	"include": [
		"src/**/*.ts"
	]
}
```

And package.json:
```
{
  "name": "project-name",
  "version": "0.1.0",
  "description": "project-description",
  "scripts": {
    "clean": "rm -rf dist",
    "run": "node dist/cli.js",
    "build": "tsc",
    "test": "NODE_ENV=test mocha --require ts-node/register --recursive 'test/**/*.ts'",
    "coverage": "nyc npm test",
    "lint": "tslint --fix -c tslint.json 'src/**/*.ts' && tslint --fix -c tslint.json 'test/**/*.ts'"
  },
  "author": "sci4me",
  "license": "MIT",
  "devDependencies": {
    "@types/es6-collections": "^0.5.31",
    "@types/mocha": "^5.2.5",
    "@types/node": "^10.9.2",
    "mocha": "^5.2.0",
    "nyc": "^12.0.2",
    "ts-node": "^7.0.1",
    "typescript": "^3.0.1"
  },
  "dependencies": {
    "commander": "^2.17.1",
    "solc": "^0.4.24",
    "source-map-support": "^0.5.8"
  },
  "nyc": {
    "include": [
      "src"
    ],
    "require": [
      "source-map-support/register",
      "ts-node/register"
    ],
    "extension": [
      ".ts"
    ],
    "reporter": [
      "text",
      "html"
    ],
    "produceSourceMap": true,
    "sourceMap": true,
    "instrument": true,
    "all": true
  }
}
```

I apologize if I'm just doing something dumb; I'm really new to the TypeScript ecosystem. However, so far, my research online hasn't led me to a solution.

EDIT: After messing with it further, I was somehow able to get it working. Not sure how I got it working but it is working. I did uninstall @types/es6-collections. I suspect this issue is actually invalid.

**Comment by rbuckton** [comment]
es6-collections is a shim library to add es6 collections (map, set, etc.) to an es5 runtime. If you are targeting ES6 you most likely do not need es6-collections.

**Comment by rbuckton** [comment]
@sci4me: Should I go ahead and close this issue?

**Comment by sci4me** [comment]
@rbuckton Yeah, go ahead and close it. I was confused as my editor wasn't detecting the es6-collections (Map, etc.) without @types/es6-collections before, when targeting ES6. Not sure what I did that fixed it but it's working now.
