### ISSUE TITLE
@types/koa-bodyparser is at version 5.0.1 but there is no version 5 of this module

### ISSUE THREAD

**Issue by natesilva** [DefinitelyTyped/DefinitelyTyped#28434]
Currently `@types/koa-bodyparser` is at version 5.0.1. But the module that it covers, `koa-bodyparser`, is only up to version 4.2.1 and there is no v5 that I can find, not even with a `beta` or `next` label.

Is the version number of the `@types` supposed to be in sync with the module it covers?

**Comment by pe8ter** [comment]
Since `koa-bodyparser` is only in the 4.x range, I would expect the typings to match that version, which it does. It looks like someone pushed up the wrong version at some point.

**Comment by natesilva** [comment]
The typings are now at `4.2.2` while the module itself is at `4.2.1`. Close enough, and it’s not v5. Since the version number is fixed-ish, I’ll close this.
