### ISSUE TITLE
Error when installing @types/semver

### ISSUE THREAD

**Issue by Nickvda** [DefinitelyTyped/DefinitelyTyped#28490]
Greetings,

For the past day I have been struggling to install all my dependencies, as it keeps crashing at @types/semver. I have tried installing older versions, but it seems that other dependencies really want the newer version. This is the error that I keep getting (colleagues of mine are getting it as well:)

`npm verb cli   'i',
npm verb cli   '--save',
npm verb cli   '--verbose',
npm verb cli   '@types/semver' ]
npm info using npm@5.10.0
npm info using node@v8.11.4
npm verb npm-session cc916526eab315eb
npm http fetch GET 404 http://private-repo/@types%2fsemver 186ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 830ms
npm verb stack Error: 404 Not Found: @types/semver@latest
npm verb stack     at fetch.then.res \AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
npm verb stack     at tryCatcher (\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
npm verb stack     at Promise._settlePromise (\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
npm verb stack     at Promise._settlePromises (\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
npm verb stack     at Async._drainQueue (\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
npm verb stack     at Async._drainQueues (\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues (\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
npm verb stack     at runCallback (timers.js:810:20)
npm verb stack     at tryOnImmediate (timers.js:768:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
npm verb cwd C:\Sources\projectX
npm verb Windows_NT 10.0.17134
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "--verbose" "@types/semver"
npm verb node v8.11.4
npm verb npm  v5.10.0
npm ERR! code E404
npm ERR! 404 Not Found: @types/semver@latest
npm verb exit [ 1, true ]
npm timing npm Completed in 1701ms

npm ERR! A complete log of this run can be found in:
npm ERR!     AppData\Roaming\npm-cache\_logs\2018-08-29T08_02_50_085Z-debug.log
`

If I try to simply `install @types/semver` I get the exact same issue. `npm ERR! 404 Not Found: @types/semver@latest
`

What is going wrong here?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
