### ISSUE TITLE
[@types/faker] The FakerStatic interface must have optional params in the system.

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [DefinitelyTyped/DefinitelyTyped#28574]
- [x] I tried using the `@types/faker` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @basp 

[At this point in the specification](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6ef608b70cdeae831fbc64c2ff8e8fa832bc51f8/types/faker/index.d.ts#L204) the parameters must be optional. [The method receives two parameters](https://github.com/Marak/faker.js/blob/3a4bb358614c1e1f5d73f4df45c13a1a7aa013d7/lib/system.js#L16) but does not use them at all

The suggestion is that the code looks like this
```js
system: {
  fileName(ext?: string, type?: string): string;
  commonFileName(ext: string, type?: string): string;
  ...
};
```
What do you think about it?
I am forwarding the PR with the modifications.

**Comment by mattbishop** [comment]
Have you filed a bug with Faler.js to see if they will use them? I want to see if they are really optional.

**Comment by carvalhoviniciusluiz** [comment]
The methods in question have parameters but do not use them, I observed the body of the code in [line 16](https://github.com/Marak/faker.js/blob/3a4bb358614c1e1f5d73f4df45c13a1a7aa013d7/lib/system.js#L16) and [line 34](https://github.com/Marak/faker.js/blob/3a4bb358614c1e1f5d73f4df45c13a1a7aa013d7/lib/system.js#L34) of the file system.js
```js
  /**
   * generates a file name with extension or optional type
   *
   * @method faker.system.fileName
   * @param {string} ext
   * @param {string} type
   */
  this.fileName = function (ext, type) {
    var str = faker.fake("{{random.words}}.{{system.fileExt}}");
    str = str.replace(/ /g, '_');
    str = str.replace(/\,/g, '_');
    str = str.replace(/\-/g, '_');
    str = str.replace(/\\/g, '_');
    str = str.replace(/\//g, '_');
    str = str.toLowerCase();
    return str;
  };

  /**
   * commonFileName
   *
   * @method faker.system.commonFileName
   * @param {string} ext
   * @param {string} type
   */
  this.commonFileName = function (ext, type) {
    var str = faker.random.words() + "." + (ext || faker.system.commonFileExt());
    str = str.replace(/ /g, '_');
    str = str.replace(/\,/g, '_');
    str = str.replace(/\-/g, '_');
    str = str.replace(/\\/g, '_');
    str = str.replace(/\//g, '_');
    str = str.toLowerCase();
    return str;
  };
```

**Comment by mattbishop** [comment]
Yes I see that the parameters are not used. That is likely a bug in Faker. It would be good to file an issue to make them aware of it. Possibly they would want to require these parameters. Not likely I suppose but still worth filing an issue.

**Comment by carvalhoviniciusluiz** [comment]
Yes, I understand, I'm going to ask that question and wait for the answer. 
It's not nice to do `faker.system.fileName ('', '')` in tests.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
