### ISSUE TITLE
Upgrade to TypeScript 3.0 breaks this. 

### ISSUE THREAD

**Issue by ldenevi** [DefinitelyTyped/DefinitelyTyped#28598]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6ef608b70cdeae831fbc64c2ff8e8fa832bc51f8/types/webvr-api/index.d.ts#L136-L137

Added " | Float32Array" to these types and it worked for me.

**Comment by supergoose** [comment]
+1
