### ISSUE TITLE
[@types/styled-components] How do you use `attrs`?

### ISSUE THREAD

**Issue by ryansmith94** [DefinitelyTyped/DefinitelyTyped#28597]
@Igorbek @probablyup originally posted this in https://github.com/styled-components/styled-components/issues/1959 and was told to post here.

Hi, it's unclear how `attrs` should be used with TypeScript, I'm not sure if there's just a bug in the types. Here's what we've got so far, this is the only way to make the component definition work as expected, but then the component usage fails with the error `[ts] Type 'string' is not assignable to type 'never'.`.

```ts
import styled from '../utils/mural-styled-components';

interface AdditionalProps {
  readonly size: string;
}

interface ChangedProps {
  readonly type: string;
  readonly margin: string;
  readonly padding: string;
}

const WeirdComponent = styled.input.attrs<AdditionalProps, ChangedProps>({
  // we can define static props
  type: 'password',

  // or we can define dynamic ones
  margin: (props) => props.size || '1em',
  padding: (props) => props.size || '1em',
})`
  color: palevioletred;
  font-size: 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;

  /* here we use the dynamically computed props */
  margin: ${(props) => props.margin};
  padding: ${(props) => props.padding};
`;

import React from 'react';
export const X = () => (
  <WeirdComponent size="massive"/>
); // [ts] Type 'string' is not assignable to type 'never'.
```

## Environment
```md
## System:
 - OS: Linux 4.15 Linux Mint 19 (Tara)
 - CPU: x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
 - Memory: 7.84 GB / 15.60 GB
 - Container: Yes
 - Shell: 4.4.19 - /bin/bash
## Binaries:
 - Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
 - npm: 6.4.0 - ~/github/mural/node_modules/.bin/npm
## npmPackages:
 - styled-components: ^3.3.0 => 3.4.4
```

**Comment by Epikem** [comment]
Seems like `size` property is conflicting with React `InputHTMLAttributes<T>`

```ts

    interface InputHTMLAttributes<T> extends HTMLAttributes<T> {
        ...
        pattern?: string;
        placeholder?: string;
        readOnly?: boolean;
        required?: boolean;
        size?: number; //already defined
        src?: string;
        step?: number | string;
       ...
    }
```
And `attrs` calculates its attributes using diff between additional props & react element attributes.

```ts

export interface ThemedStyledFunction<P, T, O = P> {
  (
    strings: TemplateStringsArray,
    ...interpolations: Interpolation<ThemedStyledProps<P, T>>[]
  ): StyledComponentClass<P, T, O>
  <U>(
    strings: TemplateStringsArray,
    ...interpolations: Interpolation<ThemedStyledProps<P & U, T>>[]
  ): StyledComponentClass<P & U, T, O & U>
  attrs<U, A extends Partial<P & U> = {}>(
    attrs: Attrs<P & U, A, T>
  ): ThemedStyledFunction<DiffBetween<A, P & U>, T, DiffBetween<A, O & U>>
}
```
So below code works.

```tsx
interface AdditionalProps2 {
  size22: string;
  // size: string; // not works if this line uncommented.
}

const WeirdComponent = styled.input.attrs<AdditionalProps2>({ })`
  color: palevioletred;
  font-size: 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
`;

export const X = () => (
  <WeirdComponent size22={"massive"} size={324} defaultValue='dsdsd'/>
); 
```

**Comment by ryansmith94** [comment]
Ah great spot, thanks @Epikem 👍

**Comment by beausmith** [comment]
Another working solution for extending an html element type as a styled component with custom attributes:

Component `Main.tsx`: 

```ts
interface Props {
  noMargin?: boolean
}
const Main = styled('main')<Props>`
  margin: ${({ noMargin }: Props) => (noMargin ? undefined : '1rem')};
`
export default Main
```

Usage in other component `OtherComponent.tsx`:

```ts
import Main from './Main'
const OtherComponent = () => (
  <Main noMargin />
); 
export default OtherComponent
```

**Comment by antoinerousseau** [comment]
That solution didn't work for me.
Ended up with:

```tsx
const Box = styled.div.attrs({})`
  position: ${(props: {fixed: boolean}) => (props.fixed ? 'fixed' : 'absolute')};
  top: 0;
`
```

**Comment by beausmith** [comment]
Hey, @antoinerousseau, does this help? I wish this example had been around when I was first looking! 

## Using custom props with Styled Components in Typescript.

Custom props are props which are not valid HTML attributes of the element being styled. 

Choose prop names which will clearly never conflict with any default attributes of the tag being used. eg. `isFixed` is not among the [valid DIV attributes](https://stackoverflow.com/q/2185519/101290).

```jsx
interface Props {
  isFixed?: boolean
}

const Box = styled.div`
  position: ${({ isFixed = false }: Props) => (isFixed ? 'fixed' : 'absolute')};
  top: 0;
`

export default () => (
  <div>
    <Box isFixed={true}>I'm a box</Box>
  </div>
)
```

## Using custom props and html element attributes with Styled Components in Typescript.

In this case `type` is among the [valid attributes of the `button` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Attributes), and `isFixed` is not!

I've found it useful to use separate `interface` statements for `attrs` and `props`.

```jsx
interface Props {
  isFixed?: boolean
}

interface Attrs {
  type?: string
}

const Button = styled.button.attrs(({ type = 'button' }: Attrs) => ({
  type,
}))`
  position: ${({ isFixed = false }: Props) => (isFixed ? 'fixed' : 'absolute')};
`

export default () => (
  <div>
    <Button isFixed={true} type="submit">
      I'm a button with type "submit" instead of default type of "button"
    </Button>
  </div>
)
```

**Comment by antoinerousseau** [comment]
@beausmith thanks!

**Comment by nielskrijger** [comment]
Thanks! Nice catch.

Sadly I got stuck on a different error using typescript 3.3.3333. I copied the code from the example:

```jsx
import styled from 'styled-components';
import React from 'react';

interface AdditionalProps2 {
  size22: string;
  // size: string; // not works if this line uncommented.
}

const WeirdComponent = styled.input.attrs<AdditionalProps2>({})`
  color: palevioletred;
  font-size: 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
`;

export const X = () => <WeirdComponent size22={'massive'} size={324} defaultValue="dsdsd" />;
```

and typescript returned the following error:

```
error TS2322: Type '{ size22: string; size: number; defaultValue: string; }' is not assignable to type 'IntrinsicAttributes & { max?: string | number; required?: boolean; disabled?: boolean; hidden?: boolean; dir?: string; form?: string; slot?: string; style?: CSSProperties; title?: string; pattern?: string; ... 273 more ...; readOnly?: boolean; } & { ...; } & { ...; }'.
  Property 'size22' does not exist on type 'IntrinsicAttributes & { max?: string | number; required?: boolean; disabled?: boolean; hidden?: boolean; dir?: string; form?: string; slot?: string; style?: CSSProperties; title?: string; pattern?: string; ... 273 more ...; readOnly?: boolean; } & { ...; } & { ...; }'.

16 export const X = () => <WeirdComponent size22={'massive'} size={324} defaultValue="dsdsd" />;
```

Not being a typescript expert I have no clue yet what might fix this :-/

**Comment by beausmith** [comment]
@nielskrijger - the reason that you are getting this error using the `size` attribute is because it is already an intrinsic attribute of the `input` html element. You need to use a different name.

**Comment by vomvoru** [comment]
> Thanks! Nice catch.
> 
> Sadly I got stuck on a different error using typescript 3.3.3333. I copied the code from the example:
> 
> ```js-jsx
> import styled from 'styled-components';
> import React from 'react';
> 
> interface AdditionalProps2 {
>   size22: string;
>   // size: string; // not works if this line uncommented.
> }
> 
> const WeirdComponent = styled.input.attrs<AdditionalProps2>({})`
>   color: palevioletred;
>   font-size: 1em;
>   border: 2px solid palevioletred;
>   border-radius: 3px;
> `;
> 
> export const X = () => <WeirdComponent size22={'massive'} size={324} defaultValue="dsdsd" />;
> ```
> 
> and typescript returned the following error:
> 
> ```
> error TS2322: Type '{ size22: string; size: number; defaultValue: string; }' is not assignable to type 'IntrinsicAttributes & { max?: string | number; required?: boolean; disabled?: boolean; hidden?: boolean; dir?: string; form?: string; slot?: string; style?: CSSProperties; title?: string; pattern?: string; ... 273 more ...; readOnly?: boolean; } & { ...; } & { ...; }'.
>   Property 'size22' does not exist on type 'IntrinsicAttributes & { max?: string | number; required?: boolean; disabled?: boolean; hidden?: boolean; dir?: string; form?: string; slot?: string; style?: CSSProperties; title?: string; pattern?: string; ... 273 more ...; readOnly?: boolean; } & { ...; } & { ...; }'.
> 
> 16 export const X = () => <WeirdComponent size22={'massive'} size={324} defaultValue="dsdsd" />;
> ```
> 
> Not being a typescript expert I have no clue yet what might fix this :-/

I solved it temporarily.

```js-jsx
import styled from 'styled-components';
import React from 'react';

interface AdditionalProps2 {
  size22: string;
  // size: string; // not works if this line uncommented.
}

const WeirdComponent = styled.input.attrs<AdditionalProps2>({})<AdditionalProps2>`
  color: palevioletred;
  font-size: 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
`;

export const X = () => <WeirdComponent size22={'massive'} size={324} defaultValue="dsdsd" />;
```

**Comment by vomvoru** [comment]
> Thanks! Nice catch.
> 
> Sadly I got stuck on a different error using typescript 3.3.3333. I copied the code from the example:
> 
> ```js-jsx
> import styled from 'styled-components';
> import React from 'react';
> 
> interface AdditionalProps2 {
>   size22: string;
>   // size: string; // not works if this line uncommented.
> }
> 
> const WeirdComponent = styled.input.attrs<AdditionalProps2>({})`
>   color: palevioletred;
>   font-size: 1em;
>   border: 2px solid palevioletred;
>   border-radius: 3px;
> `;
> 
> export const X = () => <WeirdComponent size22={'massive'} size={324} defaultValue="dsdsd" />;
> ```
> 
> and typescript returned the following error:
> 
> ```
> error TS2322: Type '{ size22: string; size: number; defaultValue: string; }' is not assignable to type 'IntrinsicAttributes & { max?: string | number; required?: boolean; disabled?: boolean; hidden?: boolean; dir?: string; form?: string; slot?: string; style?: CSSProperties; title?: string; pattern?: string; ... 273 more ...; readOnly?: boolean; } & { ...; } & { ...; }'.
>   Property 'size22' does not exist on type 'IntrinsicAttributes & { max?: string | number; required?: boolean; disabled?: boolean; hidden?: boolean; dir?: string; form?: string; slot?: string; style?: CSSProperties; title?: string; pattern?: string; ... 273 more ...; readOnly?: boolean; } & { ...; } & { ...; }'.
> 
> 16 export const X = () => <WeirdComponent size22={'massive'} size={324} defaultValue="dsdsd" />;
> ```
> 
> Not being a typescript expert I have no clue yet what might fix this :-/

I solved it temporarily.

```js-jsx
import styled from 'styled-components';
import React from 'react';

interface AdditionalProps2 {
  size22: string;
  // size: string; // not works if this line uncommented.
}

const WeirdComponent = styled.input.attrs<AdditionalProps2>({})<AdditionalProps2>`
  color: palevioletred;
  font-size: 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
`;

export const X = () => <WeirdComponent size22={'massive'} size={324} defaultValue="dsdsd" />;
```

**Comment by gfazioli** [comment]
> Hey, @antoinerousseau, does this help? I wish this example had been around when I was first looking!
> 
> ## Using custom props with Styled Components in Typescript.
> Custom props are props which are not valid HTML attributes of the element being styled.
> 
> Choose prop names which will clearly never conflict with any default attributes of the tag being used. eg. `isFixed` is not among the [valid DIV attributes](https://stackoverflow.com/q/2185519/101290).
> 
> ```js-jsx
> interface Props {
>   isFixed?: boolean
> }
> 
> const Box = styled.div`
>   position: ${({ isFixed = false }: Props) => (isFixed ? 'fixed' : 'absolute')};
>   top: 0;
> `
> 
> export default () => (
>   <div>
>     <Box isFixed={true}>I'm a box</Box>
>   </div>
> )
> ```
> 
> ## Using custom props and html element attributes with Styled Components in Typescript.
> In this case `type` is among the [valid attributes of the `button` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Attributes), and `isFixed` is not!
> 
> I've found it useful to use separate `interface` statements for `attrs` and `props`.
> 
> ```js-jsx
> interface Props {
>   isFixed?: boolean
> }
> 
> interface Attrs {
>   type?: string
> }
> 
> const Button = styled.button.attrs(({ type = 'button' }: Attrs) => ({
>   type,
> }))`
>   position: ${({ isFixed = false }: Props) => (isFixed ? 'fixed' : 'absolute')};
> `
> 
> export default () => (
>   <div>
>     <Button isFixed={true} type="submit">
>       I'm a button with type "submit" instead of default type of "button"
>     </Button>
>   </div>
> )
> ```

the below ```
interface Props {
  disabled?: boolean;
}

interface Attrs {
  href?: string;
}

const Link = styled.a.attrs(({ href = "#" }: Attrs) => ({
  href,
  onClickCapture: (event: any) => event.preventDefault()
}))`
  color: ${({ disabled = false }: Props) => (disabled ? "#eee" : "initial")};
`;``` doesn't work for me if I use

```
<Link href={supportUrl} target={"_blank"}>
          Click here
</Link>
```

I've got `href="#"`

any clue?

**Comment by rnmp** [comment]
To be honest I find myself more comfortable wrapping external dependencies in an API of my own. In the case of styled components, I came up with this typed wrapper that makes my life easier:

``` typescript
interface StyleProps<T> extends Partial<Attr> {
  element: keyof JSX.IntrinsicElements | React.ComponentType<any>
  css: (props: T) => string
  className?: (props: T) => string
}

const style = <T extends {}>({ element, css, ...attrs }: StyleProps<T>) => {
  return styled(element).attrs<T>(attrs)<T>`${props => css(props)}`
}
```

You could add overloads to support string literal versions of `css` or `className, but for now I find this easier.

**Comment by mulholio** [comment]
attrs is going to be deprecated in v5 according to my VSCode JSDoc preview:

![image](https://user-images.githubusercontent.com/20966690/68483053-b6664f00-0232-11ea-9712-780f1b2605f3.png)

What I've found to work much better is using a function argument to the regular `div`/`button`/etc funciton as in this tweet:

https://twitter.com/siddharthkp/status/1191690477789208578?s=20

That way, typing works easily and you just pass a generic 

e.g.

```typescript
export const Container = styled.div.attrs<{ rotationSeed: number }>(
  ({ rotationSeed, theme }) => {
    const rotationAmount = randomRotation(rotationSeed);
    return `
      display: flex;
      flex-direction: column;
      transition: transform 0.3s ease, box-shadow 0.3s ease;
      transform: rotateZ(${rotationAmount}deg);

      &:hover {
        transform: rotateZ(-${rotationAmount}deg) scale(1.1);
      }
    `;
  },
);
```

**Comment by probablyup** [comment]
It’s not deprecated, just a particular syntax is.

**Comment by mulholio** [comment]
Oh, interesting. Can you elaborate?

**Comment by probablyup** [comment]
Sure, the ability to supply an attrs object that has functions consuming
props as keys is what was deprecated in v4 and removed in v5. The
recommended variant is to supply an attrs function and return an object
containing the desired overrides instead.

So basically do a function that receives props to return an object, rather
than an object that has one or more inner functions that consume props.

**Comment by fingerartur** [comment]
The **answer** everybody was looking for:

```typescript
  import styled from 'styled-components'
  
  const Container = styled.div.attrs<
      { size: number }, // What is consumed by .attrs()
      { width: number, height: number } // What comes out of .attrs()
  >((props) => {
      return {
          width: props.size,
          height: props.size,
      }
  })<{ size: number }> // The outer type
  `
      width: ${props => props.width}px;
      height: ${props => props.width}px;
`

const container = <Container size={200} />
```

**Comment by jtbandes** [comment]
Thanks for the tip. In my case, TS was able to infer the return type of attrs(), but the final "outer type" was the trick I needed. So I just did:

```
const Foo = styled.div.attrs<{ width: number }>(
  ({width}) => ({ style: ... })
)<{ width: number }>`
  ...
`;
```

**Comment by davilima6** [comment]
@ajeetshah, @fingerartur, @jtbandes: could you please check if #775 looks OK? I basically just used the info you provided! Glad to amend (in this PR if broken/needed, or in another if an improvement)

https://styled-compone-git-fork-davilima6-feat-ts-attrs-method-s-597647.vercel.app/docs/api#using-attrs-method

**Comment by matthew-dean** [comment]
@fingerartur 

> The answer everybody was looking for:

OMG finally!! Thank you. I wish comments on an issue could be upvoted.

**Comment by Leo-X** [comment]
> @nielskrijger
> 
> I solved it temporarily.
> 
> ```
> import styled from 'styled-components';
> import React from 'react';
> 
> interface AdditionalProps2 {
>   size22: string;
>   // size: string; // not works if this line uncommented.
> }
> 
> const WeirdComponent = styled.input.attrs<AdditionalProps2>({})<AdditionalProps2>`
>   color: palevioletred;
>   font-size: 1em;
>   border: 2px solid palevioletred;
>   border-radius: 3px;
> `;
> 
> export const X = () => <WeirdComponent size22={'massive'} size={324} defaultValue="dsdsd" />;
> ```

thank  you!   this is works :

import { HTMLAttributes } from 'react';
interface IProps extends HTMLAttributes<HTMLDivElement> {
    open?: boolean;
}

const ScModal = styled.div.attrs<IProps>(scProps => {
    console.log('scProps --888:', scProps);
    return !scProps.open ? { style: { display: 'none' } } : {};
})<IProps>`
                   &.d4k-modal-root { position: fixed; }
                `

**Comment by irishcarbomb777** [comment]
To anyone here with their types not working even when directly copying and pasting some of the answers here, styled-components@^6 has type issues and these examples won't work. I had to downgrade to v5 to get my types to work!
