### ISSUE TITLE
[@types/styled-components] Unable to provide prop types to CSS Helper

### ISSUE THREAD

**Issue by seanemmer** [DefinitelyTyped/DefinitelyTyped#28628]
@Igorbek @probablyup originally posted this in styled-components/styled-components#1959 and was told to post here.

It is possible to provide Typescript prop types to a regular styled component (ThemedStyledFunction) using the following technique (as per the official docs at https://www.styled-components.com/docs/api#typescript):

```
interface StyleProps {
  row?: boolean,
}

export const Flex = styled<StyleProps>(component)`
  display: flex;

  ${p => p.row && css`
    flex-direction: row;
  `}
}
```

However, it is not possible to do so with a CSS block generated using the CSS helper (ThemedCssFunction):

```
interface StyleProps {
  _p: number,
  _m: number
}

export const helpers = css<StyleProps>`
  ${p => p._p && css`
    padding: ${p._p}px
  `}

  ${p => p._m && css`
    margin: ${p._m}px
  `}
`
```

It does not appear that ThemedCssFunction has the same type variable signature as ThemedStyledFunction, and is unable to extend the prop types available to the underlying template literal.

**Comment by fverloop** [comment]
I'm also running into this. I'm working with a collection of helpers. I've solved this for now by wrapping the `css` helpers in a function like this:

```Typescript
type WithTheme<P> = P & {
  theme: Theme;
};

interface TypeProps {
  color?: Color;
}

const base = (props: WithTheme<TypeProps>) => css`
  line-height: 1.4;
  font-weight: 400;
  color: ${props.theme.color[props.color]};
`;

export const H1 = styled.h1<TypeProps>`
  ${base}
  font-size: 110px;
`;
```

I would love to hear if this can be done any smarter. It would be great if this was possible:

```Typescript
interface TypeProps {
  color?: Color;
}

const base = css<TypeProps>`
  font-family: Colfax;
  line-height: 1.4;
  font-weight: 400;
  color: ${props.theme.color[props.color]};
`;

export const H1 = styled.h1<TypeProps>`
  ${base}
  font-size: 110px;
`;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
