### ISSUE TITLE
mongoose.Error.ValidationError & mongoose.Error.ValidatorError types missing

### ISSUE THREAD

**Issue by idanyadgar** [DefinitelyTyped/DefinitelyTyped#28642]
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (3.0.3)
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi @sindrenm @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd

The following code is running and working after compiling to js, I get a validation error when trying to `save()` my document as I expected:
```ts
import * as mongoose from 'mongoose';

const ObjectId = mongoose.SchemaTypes.ObjectId;

const itemSchema = new mongoose.Schema({
    name:         { type: String,     required: true  },
    description:  { type: String,     required: false },
    type:         { type: ObjectId,   required: true, ref: 'ItemType'  },
    creator:      { type: ObjectId,   required: true  },
    catalogRefs:  { type: [ String ], required: false },
    manufacturer: { type: ObjectId,   required: false },
    images:       { type: [ String ], required: false },
    attachments:  { type: [ String ], required: false },
    properties:   { type: Map,        required: true, of: mongoose.SchemaTypes.Mixed }
}, { timestamps: true });

itemSchema.pre('save', async function() {
    const error = new mongoose.Error.ValidationError(this);
    error.errors.properties = new mongoose.Error.ValidatorError('properties', 'properties is not good', 'notvalid', this.properties);

    throw error;
});

export default mongoose.model('Item', itemSchema);
```

But on compilation I also get these errors:
```
error TS2339: Property 'ValidationError' does not exist on type 'typeof Error'.
const error = new mongoose.Error.ValidationError(this);
error TS2339: Property 'ValidatorError' does not exist on type 'typeof Error'.
error.errors.properties = new mongoose.Error.ValidatorError('properties', 'properties is not good', 'notvalid', this.properties);
```

**Comment by stablio** [comment]
@idanyadgar looks like all of the MongooseErrors are missing. Have opened PR #29709 that adds these.

**Comment by JulioJu** [comment]
@armanio123  you have merged the corresponding PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29709 . Therefore the current issue could be close ! :-)

**Comment by JulioJu** [comment]
@minestarks  as  #29709  was merged, maybe you could close this  issue ?

**Comment by karanalpe** [comment]
I'm trying get type error in catch exception.

`
import { Error } from 'mongoose';

catch (error) {        
      let erro: Error = error;
      erro.code <<< doesn't exists
}
`

Have any ideia?

Sorry for question, but I'm begginer.
