### ISSUE TITLE
@types/btoa - module is not a default export

### ISSUE THREAD

**Issue by Jameskmonger** [DefinitelyTyped/DefinitelyTyped#28648]
- [x] I tried using the `@types/btoa` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johngeorgewright

The package `btoa` has the following contents (irrelevant parts removed):

```
function btoa() { ... }
module.exports = btoa;
```

The current typings mark it as `export default` however that then tries to access `module.exports.default` which is `undefined`.

**Comment by Jameskmonger** [comment]
@johngeorgewright

**Comment by tup1tsa** [comment]
It's not export default. It's an error.
It should be export = btoa.
And you use it like this 
import btoa = require('btoa')
It is special typescript export/import for legacy modules.

**Comment by tup1tsa** [comment]
> I wasn't sure of the syntax to use in the .d.ts file
Neither did I when I made my first pull request. We're on the same page
