### ISSUE TITLE
@types/OfficeJs mailbox.item.body (typed Office.Body) .getAsync result returns... Office.Body

### ISSUE THREAD

**Issue by michahell** [DefinitelyTyped/DefinitelyTyped#28670]
This is a question @LanceEa @Zlatkovsky @AlexJerabek @ElizabethSamuel-MSFT:

I just updated from `@types/office-js` `0.0.100` to `0.0.109` and I noticed that the `AsyncResult` now has a template type. However, it seems that the `Body` interface method `getAsync` returns `Body` as `AsyncResult` template type again... is this a mistake: ?

```
getAsync(coerciontype: Office.CoercionType, options?: Office.AsyncContextOptions, callback?: (result: AsyncResult<Office.Body>) => void): void;
```
At first I was thinking maybe there is another `Body` interface somewhere, but I could not find any.
this used to return a string, or at least, that is how we used it.

*update* it seems to have happened already in `0.0.102`

**Comment by ElizabethSamuel-MSFT** [comment]
@michahell No, it is correct. If you still want a string returned, you should set the coerciontype to CoercionType.Text or other appropriate value for your purpose.

**Comment by ElizabethSamuel-MSFT** [comment]
@michahell: You were right about this. @sebastianmattar is kindly making this update in PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30050.

**Comment by michahell** [comment]
Thanks, this did really make no sense at all :)
