### ISSUE TITLE
[@types/puppeteer] ts error when assigning null to defaultViewport when strictNullChecks is enabled 

### ISSUE THREAD

**Issue by sriramrudraraju** [DefinitelyTyped/DefinitelyTyped#28677]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/puppeteer` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] @marvinhagemeister. @cdeutsch, @ksm2
  - Authors: [Marvin Hagemeister](https://github.com/marvinhagemeister), [Christopher Deutsch](https://github.com/cdeutsch), [Konstantin Simon Maria Möllers](https://github.com/ksm2) .

## Issue
 `"strictNullChecks": true` in tsconfig.json
```
puppeteer.launch({
      headless: false,
      defaultViewport: null
    });
```

## Screenshot
![image](https://user-images.githubusercontent.com/13767258/45178836-72199200-b1dc-11e8-8f6a-6a77dcb9af1f.png)
(edit: forgot to crop image)

assigning type `null` to  `defaultViewport` (line: 1658) in @types/puppeteer/index.d.ts resolved me the error.

**Comment by marvinhagemeister** [comment]
Just checked with the [api docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions) and can confirm that this is a bug in our typings.

**Comment by searleser97** [comment]
Is there any work in progress to fix this issue?

**Comment by jakebailey** [comment]
puppeteer is typed upstream, so if this bug still exists, it should be reported there.
