### ISSUE TITLE
Typescript Type Error When Used With Constructor

### ISSUE THREAD

**Issue by CJamesKeller** [DefinitelyTyped/DefinitelyTyped#28709]
----
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sheetalkamat , @whtsky , @beheh , @Chnoch @GiedriusGrabauskas 
----

**Overview:**
Our project is using:
- react-i18next   7.11.0,
- i18next   11.6.0,
- react   16.0.0,
- react-native   0.51.0,
- typescript   2.9.2,
- @types/react-i18next   7.8.2,
- @types/i18next   8.4.4,
- @types/react   16.4.7,
- @types/react-native   0.56.4

And we have a component setup like this:

**index.tsx**
```javascript
import * as React from 'react';
import { I18nextProvider } from 'react-i18next';
import { Provider } from 'react-redux';
import { applyMiddleware, createStore } from 'redux';
import thunkMiddleware from 'redux-thunk';

import AppContainer from './containers/app/index';
import i18n from './i18n';
import reducers from './reducers/index';

const store = createStore(reducers, applyMiddleware(thunkMiddleware));

const App = () => (
	<I18nextProvider i18n={i18n}>
		<Provider store={store}>
			<AppContainer />
		</Provider>
	</I18nextProvider>
);

export default App;
```

**i18n/index.ts**
```javascript
import * as i18n from 'i18next';
import { reactI18nextModule } from 'react-i18next';

import * as enUS from './en-US/common.json';

export default i18n
	.createInstance()
	.use(reactI18nextModule)
	.init({
		lng: 'en-US',
		react: { wait: true },
		resources: { 'en-US': { common: enUS } },
	});
```

**tsconfig.json**
```javascript
{
	"compilerOptions": {
		"allowJs": true,
		"allowSyntheticDefaultImports": true,
		"experimentalDecorators": true,
		"jsx": "react-native",
		"module": "commonjs",
		"moduleResolution": "node",
		"noEmit": true,
		"noErrorTruncation": true,
		"outDir": "dist",
		"pretty": true,
		"rootDirs": [
			"src",
			"example/src"
		],
		"skipLibCheck": true,
		"target": "es2015",
		"types": [
			"jest",
			"node",
			"react",
			"react-native"
		]
	},
	"exclude": [/* our excluded folders*/],
	"include": [/* our included folders */]
}
```

And then within the App, we have a component like this:
(The interfaces are exported from another file, but all laid out here, names changed, in the exact format as we use them)

**Some Component:**
```javascript
interface ComponentProps {
	func1: Function;
	func2: Function;
	t?: Function;
	infoObj1: any;
	stringThing: string;
	importantThing: ImportantThing; /* defined by another interface */
	error?: ErrorObject; /* same deal */
}

interface ImportantThing { /* all optional */
	name?: string;
	isThingish?: boolean;
	someId?: string | null;
	importance?: Importance; /* again, another interface */
	watch?: Watch; /* and here */
}

interface Importance {
	group: Group[];
	names: Names;
}

interface Group {
	title: string;
}

interface Names {
	display: string;
}

interface Watch {
	attribute: Attribute[];
	organizedAttrs: OrganizedAttrs;
}

interface Attribute {
	writable: boolean;
	name: string;
	display: Display;
	labels: string[];
}

interface Display {
	name: string;
}

interface OrganizedAttrs {
	main: Main;
	secondary: Secondary;
}

interface Main {
	attributes: Attribute[];
}

interface Secondary {
	label: string;
	attributes: Attribute[];
}

interface ErrorObject {
	status?: string | number;
	message: string;
	name?: string;
}

interface ComponentState {
	doThing?: boolean;
}

class SomeComponent extends Component<ComponentProps, ComponentState> {
	public constructor (props) {
		super(props);
		this.state = {
			doThing: false
		};
	}
	/* lifecycle methods and content rendered; setState is used for an onPress() function */
}

export const Some = translate(['common'])(SomeComponent);
```

**Error Message:**
`Type '{ /* properties with types here */ }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<Pick<any, never> & TranslateHocProps, ComponentState, any>> & Readonly<{ children?: ReactNode; }> & Readonly<Pick<any, never> & TranslateHocProps>'.`

**Question:**

Our component renders and tslint is happy as can be if we do not call `super(props)`.

But as soon as we add in a constructor again to handle `state`/`setState`, we get the errors.

I was unable to find any documentation of similar errors that helped with this issue, and have been using a bad workaround for the time being.

Do you have any idea why we might be encountering this issue?

Thank you.

**Comment by beheh** [comment]
You don't need to list `t` manually in your component's Props, just extend the `InjectedTranslateProps` exported from the `react-i18next` root.

**Comment by CJamesKeller** [comment]
That seems to have handled the issue! Thank you so much for clarifying!
