### ISSUE TITLE
Issue with latest Sequelize Types

### ISSUE THREAD

**Issue by Bene-Graham** [DefinitelyTyped/DefinitelyTyped#28715]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @samuelneff @codeanimal @drinchev @babolivier @kukoo1 @oktapodia @morpheusxaut @TitaneBoy @zjy01 @nidzov @Raigen @todd @nrschultz @thomas-b

PR Author: @henrikra 

In PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28294 Type check to make sure the attributes and the model definition equal each other was done, this is awesome. BUT, I am having an issue where if you have a model like the following:

Model:
```
export default (sequelize: Sequelize, dataTypes: DataTypes): SequelizeStatic.Model<IClientInstance, IClientAttributes> => {
    const model = sequelize.define<IClientInstance, IClientAttributes>("Client", {
        clientName: dataTypes.STRING,
        clientNameLower: dataTypes.STRING,

    },
    {

    });

    model.associate = (models) => {
        model.belongsTo(models.Region, { foreignKey: "addressRegionId" });
        model.belongsTo(models.SubRegion, { foreignKey: "addressSubRegionId" });
    };

    return model;
};
```

Attribute:
```
export interface IClientAttributes extends IEntity<number> {
    clientName: string;
    clientNameLower: string;

    addressRegionId: number;
    Region?: IRegionInstance;

    addressSubRegionId: number;
    SubRegion?: ISubRegionInstance;
}
```

The typescript compiler complains that addressRegionId, and addressSubRegionId are missing from the model, even though they are define as part of the associations.

Except for the TSC errors, the code works fine. Not sure if there is a work around or not for this?

**Comment by todd** [comment]
I typically define my association IDs as part of the model regardless of whether the framework handles creating the columns for me or not. In this way, your model definitions become explicit and self-documenting.

If you don't want to do that, you could always make your association IDs optional properties in the same way the actual associated model instances are.

I'd say those are two decent workarounds (with the former being what I would prefer, personally), but I'd be curious if either of those options are unpalatable to you.

**Comment by Bene-Graham** [comment]
@todd Thank you for the quick reply

Reviewing my models, every where but two of my models had the foreign keys as optional (Oops :(  )

Fixing those two models and everything compiles again.

Thanks
