### ISSUE TITLE
Regression: JQueryPromise is not assignable to Promise

### ISSUE THREAD

**Issue by rdicroce** [DefinitelyTyped/DefinitelyTyped#28768]
- [x] I tried using the `@types/jquery` package and had problems.
- [ ] ~~I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript~~
I am using TypeScript 2.9.2 and cannot upgrade because Angular does not support TS 3 yet.
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu

@types/jquery 3.3.3 has a regression. 3.3.2 did not have this problem.

With 3.3.3 and later, this code:

```typescript
	setValueToDefault (): Promise<void> {
		if (this._defaultValue === undefined) {
			return this.WebService.getDefaultValue(this.entityType).done(value => {
				if (this._defaultValue === undefined) {
					this._defaultValue = value;
				}
				if (this.value === undefined) {
					this.changeValue($.extend({}, this._defaultValue));
				}
			});
		} else {
			this.changeValue($.extend({}, this._defaultValue));
			return Promise.resolve();
		}
	}
```

Results in this error:

```
ERROR in src/main/frontend/components/entityReferenceAutocomplete.component.ts(73,4): error TS2322: Type 'JQueryPromise<EntityReference>' is not assignable to type 'Promise<void>'.
  Property '[Symbol.toStringTag]' is missing in type 'JQueryPromise<EntityReference>'.
```

In the above code, this.WebService.getDefaultValue() returns a JQueryPromise<EntityReference>.

Since the regression appears in 3.3.3, the culprit is most likely #26420.

**Comment by leonard-thieu** [comment]
Will be fixed by #28769. Thanks for reporting this!
