### ISSUE TITLE
Tests on master branch are failing. So are failing tests on all PRs!!!

### ISSUE THREAD

**Issue by dolezel** [DefinitelyTyped/DefinitelyTyped#28809]
- Authors: @RyanCavanaugh @armanio123

**Comment by dolezel** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6d9d1c7a924548017fa3c23959c7dac4492c2e85

**Comment by dolezel** [comment]
Fix in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28794

**Comment by RyanCavanaugh** [comment]
Sorry for the breaks everyone - did a ton of merging a few days ago to get caught up here and some conflicting edits went in.
