### ISSUE TITLE
[@types/jquery] scrollTop / scrollLeft / offset return undefined?

### ISSUE THREAD

**Issue by krishan** [DefinitelyTyped/DefinitelyTyped#28852]
I noticed these types are currently in `master`:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5f7be1fd628aaa36a1414d6ba59df8ff03ca3f1e/types/jquery/index.d.ts#L4726, https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5f7be1fd628aaa36a1414d6ba59df8ff03ca3f1e/types/jquery/index.d.ts#L5369, https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5f7be1fd628aaa36a1414d6ba59df8ff03ca3f1e/types/jquery/index.d.ts#L5353

According to Jquery docs, none of these methods return `undefined`, see: https://api.jquery.com/offset/, https://api.jquery.com/scrollTop/ and https://api.jquery.com/scrollLeft/.

I have code that assumes "not undefined" running in production for years, which I am now converting to typescript, and it kind of irks me to add `as number` typecasts everywhere...

Is this a bug in `@types/jquery`? 

@leonard-thieu

**Comment by leonard-thieu** [comment]
#### `offset()`

> **Note**: jQuery does not support getting the offset coordinates of hidden elements or accounting for margins set on the `<html>` document element.
> 
> While it is possible to get the coordinates of elements with `visibility:hidden` set, `display:none` is excluded from the rendering tree and thus has a position that is undefined.

#### `scrollTop()` / `scrollLeft()`

`scrollTop()` and `scrollLeft()` will return `undefined` when called on an empty set.

---

If you're certain that these methods will return a value when called, you can use the non-null assertion operator (`!`) instead.

**Comment by krishan** [comment]
Thank you very much for the quick response!
