### ISSUE TITLE
@types/prop-types & @types/react has circular dependency

### ISSUE THREAD

**Issue by adisbladis** [DefinitelyTyped/DefinitelyTyped#28881]
Circular dependencies are a huge issue when working with third party tooling (graphing dependencies, integrating into other build systems etc).

I think the correct solution here would be to put @types/react in the bundleDependencies (https://docs.npmjs.com/files/package.json#bundleddependencies) attribute in package.json to make the circular dependency invisible to consumers of this package.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DovydasNavickas @ferdaber

**Comment by wilcoschoneveld** [comment]
+1

**Comment by Spenhouet** [comment]
Is this the source of the following errors / issues?

- https://stackoverflow.com/questions/52339225/react-typescript-2312-14-duplicate-identifier-librarymanagedattributes
- https://stackoverflow.com/questions/52399839/typescript-duplicate-identifier-librarymanagedattributes
- https://stackoverflow.com/questions/52323056/typescript-error-duplicate-identifier-librarymanagedattributes
- https://github.com/ant-design/ant-design/issues/11697

**Comment by adisbladis** [comment]
@Spenhouet I think it looks like this might be your issue. You could try manually deleting the nested directory.

**Comment by Spenhouet** [comment]
> @Spenhouet I think it looks like this might be your issue. You could try manually deleting the nested directory.

That leads to other errors since other packages seem to depend on them.

**Comment by adisbladis** [comment]
I meant to say manually flatten. Sorry :)

**Comment by Spenhouet** [comment]
> I meant to say manually flatten. Sorry :)

You say that like it is easy 😅

My current workaround is adding `"skipLibCheck": true` to `tsconfig.json`.

https://stackoverflow.com/a/52404148/2230045

**Comment by ferdaber** [comment]
A short term fix would be to duplicate the ReactNode definition in prop-types. If someone opens a PR I can review it.
