### ISSUE TITLE
@types/highcharts

### ISSUE THREAD

**Issue by lisemon** [DefinitelyTyped/DefinitelyTyped#28973]
Hi @andy-ms, @jphamilton etc :)

I am trying to add an eventlistener to my RangeSelectorButton, as this example
http://jsfiddle.net/bu3o9w2n/1/

However there is no `events` property defined for RangeSelectorButton in `highstock.d.ts`.
Highcharts API doc: https://api.highcharts.com/highstock/rangeSelector.buttons.events
Can you please add this?

```
interface RangeSelectorButton {
        type: string; // Defines the timespan, can be one of 'millisecond', 'second', 'minute', 'day', 'week', 'month', 'ytd' (year to date), 'year' and 'all'.
        count?: number;
        text: string;
        dataGrouping?: any; // not sure how this works
    }
```

**Comment by andy-ms** [comment]
PRs accepted.
