### ISSUE TITLE
@types/jquery doesn't support "target": "es5" as of v3.3.8

### ISSUE THREAD

**Issue by uknickwilliams** [DefinitelyTyped/DefinitelyTyped#28988]
- [ X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

tsc fails when using @types/jquery version 3.3.8.

Error message:
```
node_modules/@types/jquery/index.d.ts:6774:19 - error TS2693: 'Symbol' only refers to a type, but is being used as a value here.
```

Sample failing repo [here](https://github.com/uknickwilliams/-types-jquery-es5-error). To get the error message run `npm install` and then `tsc`.

If you downgrade the @types/jquery to v3.3.7 there is no issue.

**Comment by leonard-thieu** [comment]
Fixed by #28975.
