### ISSUE TITLE
Redis definitions are duplicated

### ISSUE THREAD

**Issue by basarat** [DefinitelyTyped/DefinitelyTyped#2898]
This : https://github.com/borisyankov/DefinitelyTyped/blob/master/node_redis/node_redis.d.ts should be deleted and merged into https://github.com/borisyankov/DefinitelyTyped/blob/master/redis/redis.d.ts as `redis` is the NPM name : https://www.npmjs.org/package/redis

Discovered in : #2885

**Comment by begincalendar** [comment]
I believe this issue can be closed now, as the #6344 issue and its PR (#6372) should have addressed it.

**Comment by philraj** [comment]
Where are the node_redis type definitions now hosted? I'm having trouble finding them.
