### ISSUE TITLE
@types/react Question: can you allow only specific JSX elements as props?

### ISSUE THREAD

**Issue by junseld** [DefinitelyTyped/DefinitelyTyped#29017]
- [X] I tried using the `@types/react` package (version 16.4.14) and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (version 3.0.3)

I would like to define props to only allow a specific React/JSX element:
E.g. I have a badge component
```
class Badge extends React.Component<BadgeProps> { ... }
```

and an entry component that should only allow passing a badge element:
```
interface EntryProps {
  // doesn't work because <Badge {...} /> is not of this type
  badge: React.ReactElement<BadgeProps> 

  // had something like this previously but it allows all kind of elements ... <div /> ...
  //  badge: JSX.Element 
  //  badge: React.ReactNode

  //  some other props...
}
class Entry extends React.Component<EntryProps> { ... }
```

am I missing something or is this not possible at the moment?

Thanks

**Comment by Miklet** [comment]
Can you show how did you pass your component?

**Comment by junseld** [comment]
I use it like that and I want to only allow elements of type `ReactElement<BadgeProps>`:
```
<Entry 
  badge={<Badge {...} />}
/>
```
it shows an error
Error: `Type 'Element' is not assignable to type 'ReactElement<BadgeProps>'.`
and I had to cast:
`<Badge /> as ReactElement<BadgeProps>`

**Comment by Miklet** [comment]
I was trying to achieve your goal but I failed. What about `React.ComponentType<P>`? It will limit components that you can pass but you would not be able to pass props.
```
type EntryProps = {
  badgeComponent: React.ComponentType<BadgeProps>
}
```
Then you can use it like that:
```
<Entry badge={Badge} />
```
Here you can look at my try using `React.ReactElement` but I could pass element with required props but also others, so it didn't work well 😅

**Comment by junseld** [comment]
hmm. well thanks for trying.
it works with passing the component. I could also pass (some of) the props for the badge but doesn't seem right.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
