### ISSUE TITLE
@types/pouchdb plugins incompatible with mixins

### ISSUE THREAD

**Issue by cdaringe** [DefinitelyTyped/DefinitelyTyped#29078]
- [x] I tried using the `@types/pouchdb` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @AGBrown @geppy @fredgalvao

# problem

```ts
import adapterFind from 'pouchdb-find'
...
// error TS2420: Class 'Pouchy' incorrectly implements interface 'Database<{}>'. Property 'find' is missing in type 'Pouchy'
export class Pouchy implements PouchDB.Database {
    ...
}
applyMixins(Pouchy, [adapterFind, ...])
function applyMixins(derivedCtor: any, methodOwner: any[]) {
  methodOwner.forEach(methodOwner => {
      Object.getOwnPropertyNames(methodOwner).forEach(name => {
          if (!derivedCtor.prototype[name]) derivedCtor.prototype[name] = methodOwner[name];
      });
  });
}
// ^ just as described in the TS documentation
```

the `PouchDB.Plugin type === 'some string constant'`, so when I try to denote that my class (a wrapper around Pouch) implements a plugin, the compiler doesn't see that the methods are actually making it onto the target prototype.

i'm a little new to this, so i'm guessing that the `Plugin` type needs to be beefed up with a union type, wherein one of those describes the methods a plugin adds

**Comment by geppy** [comment]
@cdaringe `applyMixins` still requires you to redeclare fields/properties, per [TypeScript's mixin documentation](https://www.typescriptlang.org/docs/handbook/mixins.html):

> …we create stand-in properties and their types for the members that will come from our mixins.
> This satisfies the compiler that these members will be available at runtime.
> This lets us still get the benefit of the mixins, albeit with some bookkeeping overhead.
> 
> ```ts
> // Disposable
> isDisposed: boolean = false;
> dispose: () => void;
> // Activatable
> isActive: boolean = false;
> activate: () => void;
> deactivate: () => void;
> ```

Side note: does the code work when you run it?  `applyMixins` is supposed to be used with code that's design to be mixed in that way (it won't call constructors, and it won't traverse [the prototype chain](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain)).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
