### ISSUE TITLE
@types/react-select missing type definition for `theme` prop on `Select`

### ISSUE THREAD

**Issue by nottoseethesun** [DefinitelyTyped/DefinitelyTyped#29072]
- [ x] I tried using the `@types/react-select` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @claasahl @jonfreedman 

I get this error:

```
[ts] Property 'theme' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Select<{ col: string; as: string; }>> & Pick<Readonly<{ children?: ReactNode; }> & Readonly<Props<{ col: string; as: string; }>>, "children"> & Partial<...> & Partial<...>'.
```

with code like this (some code elided) (I used (theme) => theme for demonstration purposes only) :

```
        <Select
          isDisabled={isReadOnly}
          isMulti={true}
          components={components}
          getOptionLabel={...}
          getOptionValue={...}
          theme={(theme) => theme} 
          value={...}
          ...
         />
```

I believe that this only needs the `theme` property to be added to this list in `@types/react-select/lib/Select.d.ts` :

```
export default class Select<OptionType> extends React.Component<Props<OptionType>, State<OptionType>> {
  static defaultProps: Props<any>;

  // Misc. Instance Properties
  // ------------------------------

  blockOptionHover: boolean;
  clearFocusValueOnUpdate: boolean;
```

**Comment by claasahl** [comment]
Hi @nottoseethesun 

Are you willing to share a minimal example, which illustrates your point? Perhaps a [codesandbox](https://codesandbox.io/)

**Comment by nottoseethesun** [comment]
Sorry I am not able to, however, it seems pretty straightforward: the `theme` prop is simply non-existent in the type definition, `Select`.  So it makes sense that there would be a type error if the `theme` property is used.  

Here is the doc on `theme`: https://react-select.com/styles#overriding-the-theme  If you expand the example, you can see the canonical usage, which means having a `theme` prop, and that causes a type error, which is not surprising since `theme` is nowhere to be found in the type definition of `Select`.

**Comment by claasahl** [comment]
Hi @nottoseethesun 

Thanks for the link. I tried, but failed, to get the referenced [sample](https://react-select.com/styles#overriding-the-theme) working in a [sandbox](https://codesandbox.io/s/zkpr25qx6x). It looks to me that the `theme` prop is not yet configurable in the latest official release from end of July.

Are you using a custom/nightly built?

**Comment by mmrath** [comment]
@claasahl The latest(v2.1.0) release has theme property

https://react-select.com/styles#overriding-the-theme

**Comment by claasahl** [comment]
Hi @mmrath 

Thanks for the pointer. The `theme` property is included in the lastest `react-select` release.

If you are up to it, feel free to submit a PR with the newly added `theme` property.

**Comment by sebastiendan** [comment]
`classes` seems to also be missing?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
