### ISSUE TITLE
LibraryManagedAttributes not mapping defaultProps for element type

### ISSUE THREAD

**Issue by dagda1** [DefinitelyTyped/DefinitelyTyped#29138]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - @ferdaber

I have the following component:

    interface LayoutProps {
      children: React.ReactNode;
    }
    
    type LayoutComponent = React.ComponentType<LayoutProps>;
    
    interface RootProps {
      Layout?: LayoutComponent;
    }
    
    class Root extends React.Component<RootProps> {
      static defaultProps: Pick<RootProps, 'Layout'> = {
        Layout: ({ children }: { children: React.ReactNode }) => <>{children}</>
      };
    
      render() {
        const { Layout, children } = this.props;
        return (
          <Layout>  // JSX element type 'Layout' does not have any construct or call signatures.
            {children}
          </Layout>
        );
      }
    }
    
    ReactDOM.render(<Root>Foobar</Root>, document.getElementById('mount-node'));

typescript does not pick up the fact that there is a `defaultProp` for `Layout` which I thought it would due to the new [LibraryManagedAttributes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2312) mapped type.

I am using `@types/react@16.4.14` and typescript `3.0.3`.

Typescript complains about `Layout` not being callable when I thought that the prop would be mapped from `defaultProps`

I have `strictNullChecks` set to true.

If I add this code, then it is fine:
```
      render() {
        const { Layout, children } = this.props;
    
        if (!Layout) {
          return null;
        }
    
        return <Layout>{children}</Layout>;
      }
```

**Comment by ferdaber** [comment]
Library managed attributes allows the resolution to happen outside the component. If you have a default prop for `Layout` then this should be how you structure the code:
```tsx
interface RootProps {
  Layout: LayoutComponent
}

class Root extends React.Component<RootProps> {
  static defaultProps = {
    Layout: ({ children }: { children: React.ReactNode }) => <>{children}</>
  }

  render() {
    return <this.props.Layout /> // this is guaranteed to be defined based on RootProps
  }
}

const myRoot = <Root /> // LibraryManagedAttributes allows you to render Root in JSX 
// without needing to pass in an attribute called 'Layout' 
```

**Comment by Hotell** [comment]
@ferdaber provided a clear solution. can we close this ?

**Comment by ferdaber** [comment]
The interface itself is used for internal consumption by the component itself. If you want to get the "apparent" or "allowable" props for the component (i.e. for external consumption), maybe for reuse, you can do this:
```ts
interface Props = { /* ... */ }
class MyComponent extends React.Component<Props> { /* ... */ }

const AllowableMyComponentProps = JSX.LibraryManagedAttributes<typeof MyComponent, Props>
```

This will take any static `defaultProps` as well as `propTypes` of `MyComponent` and resolve it against `Props` with the same algorithm that determines allowable JSX attributes to be given.
