### ISSUE TITLE
React:  invalid types for props with tagged unions and `defaultProps`

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#29162]
Related https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27267

I have a bunch of use cases with a component where the props type is a tagged union (aka discriminated union aka sum type). When using `defaultProps`, the result "input" props is not as expected.

``` tsx
import * as React from 'react';
import { Component as ReactComponent, ReactNode } from 'react';

{
    type Props =
        | {
              type: 'a';
              href: string;
          }
        | {
              type: 'button';
              onClick: Function;
          };
    class Component extends ReactComponent<Props> {
        static defaultProps = {
            type: 'a',
        };
    }

    <Component />; // should error (missing 'href'), got other error (missing 'onClick')
}

{
    type Props =
        | {
              type: 'a';
              href: string;
          }
        | {
              type: 'button';
          };
    class Component extends ReactComponent<Props> {
        static defaultProps = {
            type: 'a',
        };
    }

    <Component />; // should error (missing 'href'), got none
    <Component href="foo" />; // should not error, got none
    <Component href={1} />; // should error (incorrect type for 'href'), got none
    <Component type="a" />; // should error (missing 'href'), got error
    <Component type="a" href="foo" />; // should not error, got none
    <Component type="button" />; // should not error, got none
}
```

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ferdaber @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei

If you do not mention the authors the issue will be ignored.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
