### ISSUE TITLE
@types/i18next-express-middleware: Argument of type (@types/i18next/index) I18next..i18n' is not assignable to parameter of type (@types/i18next-express-middleware/.../index) I18next.i18n

### ISSUE THREAD

**Issue by TitaneBoy** [DefinitelyTyped/DefinitelyTyped#29163]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/i18next-express-middleware` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cyrilschumacher 

Hi... Since the last update of i18next@11.9.0, when using typescript to compile my project containing i18next-express-middleware, I have a typescript error saying:

> Argument of type 'import("C:/Personal_Data/Web-Server/node_modules/@types/i18next/index").i18n' is not assignable to parameter of type 'import("C:/Personal_Data/Web-Server/node_modules/@typeode18next-express-middleware/node_modules/@types/i18next/index").i18n'.
  Types of property 'init' are incompatible.

With investigation, I found that @types/i18next-express-middleware does not install the last version of i18next in its dependencies. Instead of installing i18next@11.9.*, it install i18next@8.4.5. In the last version of i18next, the type of property 'missingKeyHandler' in the 'InitOptions' interface has a property named 'lng' that has a 'string[]' type. But in the version of i18next installed by i18next-express-middleware, the lng property has a 'string' type.

![image](https://user-images.githubusercontent.com/15614466/45975168-7550b280-c011-11e8-8615-9f97c05edd7d.png)

Here is part of my package dependencies:

![image](https://user-images.githubusercontent.com/15614466/45975354-0162da00-c012-11e8-8c02-f48a889a2474.png)
![image](https://user-images.githubusercontent.com/15614466/45975374-1475aa00-c012-11e8-9321-e693c8981e14.png)

I don't know how to force @types/i18next-express-middleware to install the latest version of i18next in its dependencies.

Thanks for your help.

**Comment by DevanB** [comment]
I, too, have this issue and am unable to understand how to resolve it. I found it through a different manner, however.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28892

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
