### ISSUE TITLE
apigee-access Leads to Wrong Emit.

### ISSUE THREAD

**Issue by jGleitz** [DefinitelyTyped/DefinitelyTyped#29183]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CasperSkydt

Using the `apigee-access` types lead to invalid code being emitted. When using it like it is proposed in [`apigee-access-test.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/apigee-access/apigee-access-tests.ts), the emitted code tries to access `apigee.default.x` instead of `apigee.x`.

You can reproduce this by running this bash script:

```bash
#!/bin/bash

rm -rf apigee-access-types-error
mkdir apigee-access-types-error
cd apigee-access-types-error

npm init -y
npm i --save-dev typescript @types/apigee-access @types/node
npm i apigee-access

curl https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/apigee-access/apigee-access-tests.ts > apigee-access-tests.ts
node_modules/.bin/tsc --strict --lib dom,es6 --module commonjs apigee-access-tests.ts
```

The emitted code will look like this (excerpt):

```javascript
var apigee_access_1 = require("apigee-access");
...
var val1 = apigee_access_1["default"].getVariable(request, 'TestVariable');
```

This is wrong, there is no `apigee_access_1["default"]`. Correct would be:

```javascript
var apigee_access_1 = require("apigee-access");
...
var val1 = apigee_access_1.getVariable(request, 'TestVariable');
```

This is fixed for me if I declare the types like this:

```typescript
declare module "apigee-access" {
    function getVariable(request: any, name: string): string | number | boolean;
    ...
}
```

But I have no experience with writing typings, so I don’t know if this is a valid solution. If it is, I’m glad to create a Pull Request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
