### ISSUE TITLE
@types/expo Latest Expo versions support

### ISSUE THREAD

**Issue by isotopeee** [DefinitelyTyped/DefinitelyTyped#29200]
- Authors: @KonstantinKai @martynaskadisa @janaagaard75  @ssanchezmarc  @fhelwanger @umidbekkarimov @moshfeu @prokopcm @tinaroh @binki 

Hi, do you plan to support the latest versions of expo? I've just upgraded to the latest version `^30.0.0` and of course, there are some changes in the API (for instance `Permissions.getAsync` now accepts string varargs Permissions `Expo.Permissions.getAsync(...permissionTypes)`).

Thanks

**Comment by moshfeu** [comment]
You are more than welcome to create a PR for this version. You can follow a previous version PR for reference: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26324

**Comment by janaagaard75** [comment]
(You can work around type definition issues by casting to any - add `as any`. It ain't pretty but it works.)

**Comment by isotopeee** [comment]
@moshfeu I would love to but I think I won't be able to make one at least for now for I have several ongoing projects.  Thanks folks!

**Comment by moshfeu** [comment]
@isotopeee The newer version is coming (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29823). Since the most of the work was done, you can easily add you changes, if you have a time.
