### ISSUE TITLE
Build failing with error "Interface 'DuplexOptions' incorrectly extends interface 'WritableOptions".

### ISSUE THREAD

**Issue by ermolaevalexey** [DefinitelyTyped/DefinitelyTyped#29232]
using webpack 4.4.1 and awesome-typescript-loader 5.1.1
build failing with this error
Build of project is failing with error provided in heading
- [ X] I  `@types/react-dom` v. 16.0.8 package requires `@types/node` package v. 10.11.1
- [X ] I using typescript 2.9.2
- [X ] [Mention]( ) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
 - Authors: @DefinitelyTyped , what can be done with that?

Full error stack:
```
ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:6527:19
--
27-Sep-2018 18:11:06 | TS2430: Interface 'DuplexOptions' incorrectly extends interface 'WritableOptions'.
27-Sep-2018 18:11:06 | Types of property 'write' are incompatible.
27-Sep-2018 18:11:06 | Type '((this: Duplex, chunk: any, encoding: string, callback: (error?: Error \| null \| undefined) => voi...' is not assignable to type '((this: Writable, chunk: any, encoding: string, callback: (error?: Error \| null \| undefined) => v...'.
27-Sep-2018 18:11:06 | Type '(this: Duplex, chunk: any, encoding: string, callback: (error?: Error \| null \| undefined) => void...' is not assignable to type '((this: Writable, chunk: any, encoding: string, callback: (error?: Error \| null \| undefined) => v...'.
27-Sep-2018 18:11:06 | Type '(this: Duplex, chunk: any, encoding: string, callback: (error?: Error \| null \| undefined) => void...' is not assignable to type '(this: Writable, chunk: any, encoding: string, callback: (error?: Error \| null \| undefined) => vo...'.
27-Sep-2018 18:11:06 | The 'this' types of each signature are incompatible.
27-Sep-2018 18:11:06 | Type 'Writable' is not assignable to type 'Duplex'.
27-Sep-2018 18:11:06 | Property 'readable' is missing in type 'Writable'.
27-Sep-2018 18:11:06 |  
27-Sep-2018 18:11:06 | ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:6539:15
27-Sep-2018 18:11:06 | TS2720: Class 'Duplex' incorrectly implements class 'Writable'. Did you mean to extend 'Writable' and inherit its members as a subclass?
27-Sep-2018 18:11:06 | Property 'pipe' is missing in type 'Duplex'.

```

**Comment by MarkRobinson01** [comment]
I have recently had the same problem, upgrading to Typescript V3.1.1 solved the issue

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
