### ISSUE TITLE
@types/quill incompatible with latest quill-delta

### ISSUE THREAD

**Issue by buu700** [DefinitelyTyped/DefinitelyTyped#29253]
The latest release of `quill-delta` introduced a first-party type definition that's slightly incompatible with this one. Specifically, passing a first-party `Delta` object in where `@types/quill` expects a `DeltaStatic` causes the following error:

```
Argument of type 'Delta' is not assignable to parameter of type 'DeltaStatic'.
  Types of property 'reduce' are incompatible.
    Type '<T>(predicate: (accum: T, curr: Op, index: number) => T, initialValue: T) => T' is not assignable to type '<T>(predicate: (acc: T, curr: DeltaOperation, idx: number, arr: DeltaOperation[]) => T, initial: T) => T'.
      Types of parameters 'predicate' and 'predicate' are incompatible.
```

---

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @43081j, @andy-ms

**Comment by andy-ms** [comment]
PRs accepted.

**Comment by vKuka** [comment]
Why the [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29340) was added only for v2?
