### ISSUE TITLE
@types/next/document and typescript 3.1.1

### ISSUE THREAD

**Issue by virzak** [DefinitelyTyped/DefinitelyTyped#29270]
@joaovieira 

Thanks for the definitions!

Typescript 3.1.1 seems to break the document test (works fine with 3.0.3).

The error is: 
```
[ts]
Class static side 'typeof default' incorrectly extends base class static side 'typeof Document'.
  Types of property 'getInitialProps' are incompatible.
    Type '(ctx: NextDocumentContext<Record<string, string | string[] | undefined>>) => Promise<{ pageContext: PageContext; styles: Element; buildManifest: Record<string, any>; html?: string | undefined; head?: ReactElement<...>[] | undefined; }>' is not assignable to type '(context: NextDocumentContext<Record<string, string | string[] | undefined>>) => DefaultDocumentIProps'.
      Type 'Promise<{ pageContext: PageContext; styles: Element; buildManifest: Record<string, any>; html?: string | undefined; head?: ReactElement<any>[] | undefined; }>' is not assignable to type 'DefaultDocumentIProps'.
        Property 'buildManifest' is missing in type 'Promise<{ pageContext: PageContext; styles: Element; buildManifest: Record<string, any>; html?: string | undefined; head?: ReactElement<any>[] | undefined; }>'.
```

Reduced the example to minimalistic, but still getting the error
```typescript
class MyDoc2 extends Document<WithUrlProps> {
  public static async getInitialProps({ req, renderPage }: NextDocumentContext) {
    // without callback

    // with callback
    const { html, head, buildManifest } = renderPage();

    const styles = [<style />];

    // Custom prop
    const url = req!.url;

    return { html, head, buildManifest, styles, url };
  }

  public render() {
    return <html />;
  }
}
```

**Comment by joaovieira** [comment]
@virzak just updated myself to v3.1.1 as well. Don't think this is related to the TS version but to the async type instead. We're discussing it on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29181#issuecomment-425535563

**Comment by joaovieira** [comment]
I see. We took from the default `Document.getInitialProps` which is an array of elements but you're right that it can be any `React.ReactNode`.

**Comment by virzak** [comment]
Awesome, thanks so much @joaovieira ! Closing this.

**Comment by roninMo** [comment]
I just tried building this myself to handle mui components and I'm getting the same error, and I don't know how to fix it. I'm using typescript version 4.6.3 and I don't how to tackle this. Here's my code: 

`
import Document, {Head, Html, Main, NextScript} from 'next/document';
import {ServerStyleSheet} from 'styled-components';

export default class MyDocument extends Document {
  static async getInitialProps(ctx: any) {
    const sheet = new ServerStyleSheet();
    const originalRenderPage = ctx.renderPage;

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: (App: any) => (props: any) => sheet.collectStyles(<App {...props} />),
        });

      const initialProps = await Document.getInitialProps(ctx);
      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        ),
      };
    } finally {
      -sheet.seal();
    }
  }

  render() {
    return (
      <Html>
        <Head>
          <link
            href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;1,400;1,700&display=swap"
            rel="stylesheet"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
`

This code was also just pulled from the mui docs, but I don't know why it's throwing that error. It builds in dev fine; however running a build in prod stops because of this error
