### ISSUE TITLE
@type/parse: Namespace '_' has no exported member '_Chain'

### ISSUE THREAD

**Issue by agoldis** [DefinitelyTyped/DefinitelyTyped#29273]
I tried using the `@types/parse` package and had problems. 

```
node_modules/@types/parse/index.d.ts:472:16 - error TS2694: Namespace '_' has no exported member '_Chain'.
```

Looking at the https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/underscore I see that `_._Chain<T>` is indeed not exported.

I wonder if `Collection` functionality event exist in Parse JS SDK
(https://github.com/parse-community/Parse-SDK-JS/tree/master/src) or is it a legacy definition... 

May be the whole `Collection` and `Event` definitions are not needed anymore. 

https://github.com/DefinitelyTyped/DefinitelyTyped/blame/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/parse/index.d.ts#L470

Authors: @dpoetzsch @flavionegrao @wesleygrimes @RyanCavanaugh

**Comment by guillaume-soulie** [comment]
@agoldis did you find a workaround ?

**Comment by agoldis** [comment]
@guillaume-soulie 😬
https://github.com/agoldis/types-parse
Let's see if they'll accept my PR, will issue one tomorrow

**Comment by agoldis** [comment]
@guillaume-soulie 👆🏻 please upvote :)

**Comment by guillaume-soulie** [comment]
thanks you for the PR.
