### ISSUE TITLE
React Svg style attribute error

### ISSUE THREAD

**Issue by budarin** [DefinitelyTyped/DefinitelyTyped#29333]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ferdaber 

ts reports a bug:
```jsx
        <svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 100 100">
            <g transform="translate(0,-952.36218)">
                <path style="fill-rule:evenodd;fill:#74a4c7;"
                    d="M59.188,21.5c-..." transform="translate(0,952.36218)"
                />
            </g>
        </svg>
```

Error: 
```bash
[ts] Type 'string' is not assignable to type 'CSSProperties | undefined'.
index.d.ts(1753, 9): The expected type comes from property 'style' which is declared here on type 'SVGProps<SVGPathElement>'

(JSX attribute) style: string
```

**Comment by Hack-IT** [comment]
I think your path element is wrong. You've added SVG attributes into CSS style property. You should put SVG attributes directly into SVG path element: 

<path fillRule="evenodd" fill="#74a4c7"
     d="M59.188,21.5c-..." transform="translate(0,952.36218)"
  />

**Comment by ferdaber** [comment]
@Hack-IT is correct. If you do want to apply CSS styles, you have to do it using an object, which is what React expects.

**Comment by budarin** [comment]
@Hack-IT @ferdaber thanks!

**Comment by donrus** [comment]
You can insert any CSS rules, but you should add them in object style:
` <path style={{fillRule:'evenodd;', fill:'#74a4c7;'}}
         d="M59.188,21.5c-..." transform="translate(0,952.36218)"
/>`
this works for React

**Comment by VadimChorrny** [comment]
> You can insert any CSS rules, but you should add them in object style: ` <path style={{fillRule:'evenodd;', fill:'#74a4c7;'}} d="M59.188,21.5c-..." transform="translate(0,952.36218)" />` this works for React

thanks man 🔥
