### ISSUE TITLE
React-intl `injectIntl` declaration chage

### ISSUE THREAD

**Issue by Ackos95** [DefinitelyTyped/DefinitelyTyped#29364]
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bgrieder, @cdroulers, @gyzerok, @tillwolff, @LKay, @bhouser, @kristerkari, @formatlos, @lukyth

Hey guys, I'm not sure who did this, but in some update on `@types/react-intl` `injectIntl` method declaration is updated, and I'm not sure that I understand why. From what I see [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-intl/index.d.ts#L32) `P` (generic) must extend `InjectedIntlProps`. Why is that?

I see that behavior remained unchanged (types of received and returned component remained the same), but this still breaks all my current components, and I don't really see reason why. Practically I have to add `& InjectedIntlProps` to all of my `injectIntl` invocations? Is that done on purpose to force extracting component prop types into interface (or type) which would include `InjectedIntlProps`? It was much more intuitive for me to create something like this.

```ts
type TMyComponentProps = {
   prop1: string;
   prop2: string;
   prop3?: number;
};

const MyComponent = injectIntl<TMyComponentProps>(
   class MyComponentInner extends React.Component<TMyComponentProps & InjectedIntlProps, any> {
      /* component code */ 
   }
);

export {
   MyComponent,
};
```

Because then I clearly see what is necessary from props to inject when using `MyComponent` (no `InjectedIntlProps`, and yet if I'm using `WrappedComponent` I also see explicitly that I need to provide `InjectedIntlProps` as well.

Can someone maybe explain why this approach changed, am I missing something?

**Comment by lukyth** [comment]
Would this answer your question? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28223 (the PR that introduce `P extends InjectedIntlProps`)

**Comment by Ackos95** [comment]
@lukyth If I understand correctly it was done like that to avoid approach I've mentioned (with adding `& InjectedIntlProps` in component class)? 

I'm not sure that I agree with that logic. From my perspective it is much easier to just add `& InjectedIntlProps` into component class to ensure that `intl` is included into props and to have separate type which is defining props that need to be provided somehow, instead of making that type include `intl` and then extract that when preparing props to inject. Take a look on this example, I've modified example from above to use that approach and created use case where it becomes dirty (just note that in previous example only thing that could be called dirty was `& InjectedIntlProps` part inside component class declaration).

```ts
type TMyComponentProps = {
   prop1: string;
   prop2: string;
   prop3: number;
} & InjectedIntlProps;

const MyComponent = injectIntl<TMyComponentProps>(
   class MyComponentInner extends React.Component<TMyComponentProps, any> {
      /* component code */ 
   }
);

// see the type here, pretty dirty
const propsToProvide: Pick<P, Exclude<keyof P, keyof InjectedIntlProps>> = {
   prop1: 'test',
   prop2: 'test2',
};

<MyComponent {...propsToProvide} />
```

**Comment by lukyth** [comment]
@apapirovski Could you please take a look at this?

**Comment by apapirovski** [comment]
This was done to support `defaultProps`.

But the generic here is meant to identify the inner props which would obviously include `intl`. This is a pretty common pattern follow for most HoCs (including react-redux `connect`). It's also important to note that the old definition did nothing to verify that the component passed to it actually accepted `intl` whereas this new one does.

To address your issue, you don't need to actually specify the generic. It can infer it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
