### ISSUE TITLE
@types/react-i18next "republish", not picking up dependent type updates

### ISSUE THREAD

**Issue by DevanB** [DefinitelyTyped/DefinitelyTyped#29408]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @GiedriusGrabauskas @Chnoch @beheh @whtsky 

Recently the `@types/i18next` package was updated that included a change that was correct for i18next.

The issue I'm here to report (and ask for guidance on how I can help) is that `@types/react-i18next` references the `@types/i18next` package, but was not updated with the new `@types/i18next` release.

I've verified this locally by navigating to `node_modules/@types/react-i18next/node_modules/@types/i18next/index.d.ts` and found that the update type is not present. I've also manually updated that `index.d.ts` and verified that the updated type corrects the issue. 

A thread about this issue can be found at: #28892

I'm unsure of how to proceed to ask for a "rebuild/publish" of `@types/react-i18next`. Thanks! 😄

**Comment by chillitom** [comment]
also.. `@types/react-i18next` appears to be behind `react-i18next` with some interfaces not documented e.g. `NamespacesConsumer`
