### ISSUE TITLE
Updates needed for @types/sequelize

### ISSUE THREAD

**Issue by billybarnum** [DefinitelyTyped/DefinitelyTyped#29414]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @samuelneff @CodeAnimal @drinchev 

I'm on a project that has to work with a wide variety of databases, old legacy ones and new postgres ones. I've had to add the following as a workaround:

            declare module 'sequelize' {
                interface AssociationOptionsHasOne {
                    sourceKey?: string;
                }

                interface AssociationOptionsBelongsTo {
                    scope?: Sequelize.AssociationScope;
                }

                interface DataTypes {
                    GEOGRAPHY: any;
                    CIDR: any;
                    INET: any;
                    MACADDR: any;
                }
            }
The first one was for a table with non-standard primaryKey name (not "id") with a hasOne association to another table. The second one was for a table with a compound foreign key that needs a belongsTo association. Scopes are used on the associations as a workaround for sequelize not directly supporting compound FKs. The third one is for new-ish postgres data types that are now supported by sequelize.

It's a pretty complex definition file and I wasn't comfortable submitting a PR, so I'm just letting you guys know.

Cheers and thanks for this project!

-BillyB

**Comment by SimonSchick** [comment]
I suggest you look at https://github.com/types/sequelize
The typings here on DT are heavily outdated and also inaccurate, I plan to publish new typings for v5 of sequelize.

**Comment by billybarnum** [comment]
@SimonSchick I forgot to thank you for your response. How rude!

Anyway, I got sidetracked but just started looking at the new typings. I see the reduction in generics at the top level. I like it, although it means quite a few changes for me.

I'll get to it then. And thanks again, man.

-B
