### ISSUE TITLE
@types/yup: How to strongly-type ObjectSchema

### ISSUE THREAD

**Issue by mellis481** [DefinitelyTyped/DefinitelyTyped#29412]
I'm using yup with Formik in my React app which I've written in Typescript.  I have the following `FormikProps` interface:

```
export interface InvoiceLevelTotal {
  amount?: number;
  currency?: string;
}
```

I've created the following `ObjectSchema` which I'm ultimately passing into the `validationSchema` property of my `Formik`:

```
const formSchema: Yup.ObjectSchema<InvoiceLevelTotal> = Yup.object().shape({
  amount: Yup.number().required('Amount is required'),
  currency: Yup.string().required('Currency is required')
});
```

As you can see, I'm attempting to type my `ObjectSchema` against my interface for type checking purposes, however if I change `currency` to `currrrrrency`, it does not throw a Typescript compile-time error like I would expect.

How can I strongly-type an `ObjectSchema`?

**Comment by mellis481** [comment]
It looks like the code should actually be as follows:

```
const formSchema = Yup.object<InvoiceLevelTotal>().shape({
  amount: Yup.number().required('Amount is required'),
  currency: Yup.string().required('Currency is required')
});
```

**Comment by esanzgar** [comment]
In yup@0.27, I was able able tto enforce the type in this way:

```
const formSchema = Yup.object().shape<InvoiceLevelTotal>({
  amount: Yup.number().required('Amount is required'),
  currency: Yup.string().required('Currency is required')
});
``` 

However, is there any way to infer a type from the schema, so that there is no need of creating the type twice. Short of like this:

```
const formSchema = Yup.object().shape({
  amount: Yup.number().required('Amount is required'),
  currency: Yup.string().required('Currency is required')
});

type InvoiceLevelTotal = typeof formSchema.[something]
```

**Comment by jedrichards** [comment]
@esanzgar Yep, looks like it: https://github.com/jquense/yup#typescript-support

**Comment by esanzgar** [comment]
@jedrichards thanks, that exactly what I was looking for...

> @esanzgar Yep, looks like it: https://github.com/jquense/yup#typescript-support

**Comment by thiskevinwang** [comment]
Obligatory 2020 (soon 2021) update:
https://github.com/jquense/yup/blob/master/docs/typescript.md

**Comment by KutnerUri** [comment]
I got it working like so:
```ts
type Values = {
  name: string;
  seeders: string[];
  owner?: AccountDescriptor;
};

const schema = Yup.object().shape<Record<keyof Values, Yup.AnySchema>>({
  name: Yup.string().required(),
  seeders: Yup.array(),
  owner: Yup.object().required(),
  cat: Yup.string() // <-- getting error here, hurray
});
```

is there maybe a simpler syntax? it seems overly complicated.

**Comment by ysfaran** [comment]
I added a utility type `Shape` to @KutnerUri's solution to allow all `ObjectShapeValues` and also made it `Partial` so you can specify the keys you want:

```ts
import * as yup from "yup";
import { ObjectShape } from "yup/lib/object";

type ObjectShapeValues = ObjectShape extends Record<string, infer V> ? V : never 
type Shape<T extends Record<any, any>> =  Partial<Record<keyof T, ObjectShapeValues>>

type Values = {
  name: string;
  seeders: string[];
  owner?: AccountDescriptor;
};

const schema = yup.object<Shape<Values>>({
  name: yup.string().required(),
  seeders: yup.array(),
  owner: yup.object().required(),
  cat: yup.string() // <-- getting error here, hurray
});

// works because of Partial
const partialSchema= yup.object<Shape<Values>>({
  name: yup.string().required(),
});

// works because of ObjectShapeValues 
const schemaWithRef= yup.object<Shape<Values>>({
  name: yup.ref("someRef")
});
```

**Comment by jackle-1playsports** [comment]
> I added a utility type `Shape` to @KutnerUri's solution to allow all `ObjectShapeValues` and also made it `Partial` so you can specify the keys you want:
> 
> 
> 
> ```ts
> 
> import * as yup from "yup";
> 
> import { ObjectShape } from "yup/lib/object";
> 
> 
> 
> type ObjectShapeValues = ObjectShape extends Record<string, infer V> ? V : never 
> 
> type Shape<T extends Record<any, any>> =  Partial<Record<keyof T, ObjectShapeValues>>
> 
> 
> 
> type Values = {
> 
>   name: string;
> 
>   seeders: string[];
> 
>   owner?: AccountDescriptor;
> 
> };
> 
> 
> 
> const schema = yup.object<Shape<Values>>({
> 
>   name: yup.string().required(),
> 
>   seeders: yup.array(),
> 
>   owner: yup.object().required(),
> 
>   cat: yup.string() // <-- getting error here, hurray
> 
> });
> 
> 
> 
> // works because of Partial
> 
> const partialSchema= yup.object<Shape<Values>>({
> 
>   name: yup.string().required(),
> 
> });
> 
> 
> 
> // works because of ObjectShapeValues 
> 
> const schemaWithRef= yup.object<Shape<Values>>({
> 
>   name: yup.ref("someRef")
> 
> });
> 
> ```

What yup version do you use?

**Comment by ysfaran** [comment]
@jackle-1playsports 

yup version `0.32.11`

**Comment by AuthorProxy** [comment]
why is closed if we still need to use some hacks to get it working?

**Comment by usermeme** [comment]
```
import { AnySchema } from 'yup/lib/schema';

export type Shape<Fields extends Record<string, unknown>> = {
  [Key in keyof Fields]: AnySchema<Fields[Key]>;
};

export type UserFields = {
  firstName: string;
  lastName?: string
};

 const validationSchema = Yup.object<Shape<UserFields>>({
        firstName: Yup.string().default(''),
        lastName: Yup.string().default(''),
  });
```

**Comment by jpoehnelt** [comment]
You can also use conditional types to improve on the above and not fallback to `AnySchema` for all keys.

https://justin.poehnelt.com/posts/strongly-typed-yup-schema-typescript/

```js
import * as yup from "yup";

export type ConditionalSchema<T> = T extends string
  ? yup.StringSchema
  : T extends number
  ? yup.NumberSchema
  : T extends boolean
  ? yup.BooleanSchema
  : T extends Record<any, any>
  ? yup.AnyObjectSchema
  : T extends Array<any>
  ? yup.ArraySchema<any, any>
  : yup.AnySchema;

export type Shape<Fields> = {
  [Key in keyof Fields]: ConditionalSchema<Fields[Key]>;
};
```

**Comment by wkoutre** [comment]
> You can also use conditional types to improve on the above and not fallback to `AnySchema` for all keys.
> 
> https://justin.poehnelt.com/posts/strongly-typed-yup-schema-typescript/
> 
> ```js
> import * as yup from "yup";
> 
> export type ConditionalSchema<T> = T extends string
>   ? yup.StringSchema
>   : T extends number
>   ? yup.NumberSchema
>   : T extends boolean
>   ? yup.BooleanSchema
>   : T extends Record<any, any>
>   ? yup.AnyObjectSchema
>   : T extends Array<any>
>   ? yup.ArraySchema<any, any>
>   : yup.AnySchema;
> 
> export type Shape<Fields> = {
>   [Key in keyof Fields]: ConditionalSchema<Fields[Key]>;
> };
> ```

@jpoehnelt this is clever 💪 Any thoughts on how to handle `yup.mixed()`? 😬

**Comment by bertdida** [comment]
This one worked for me
```js
type SchemaObject = {
  [key in keyof MyInterface]: yup.Schema<any>
}

const schema = yup.object().shape<SchemaObject>({
  ...
})
```

**Comment by gmonitoring** [comment]
How to do it today? Are there any examples?

**Comment by ericbowden** [comment]
I ended up making a helper method that I call to reduce code:

```
// interface
interface CoolType {
  requestBody: string;
  headers?: string;
  deadline: number;
  apiEndpoint: string;
}

// helper method
const yupTyped = <T,>(obj: Record<keyof T, AnySchema>) => {
  return object().shape<typeof obj>(obj);
};

// define schema
const formSchema = yupTyped<CoolType>({
  requestBody: object().required().json(),
  deadline: number().required().positive().integer(),
  headers: string().optional(),
  endpoint: string().required(), // <--- should throw error now
});
```

**Comment by EugeneNovikov13** [comment]
This is my way to solve the problem:

// form schema generic
export type FormSchema<T> = {
	[K in keyof Required<T>]: Schema<T[K]>;
};

// form's fields interface sample
interface IAccountForm {
	name: string;
	surname: string;
	email: string;
	image?: string; // optional field
}

// schema
export const accountFormSchema = yup.object().shape<FormSchema<IAccountForm>>({
	name: yup.string().required(),
	surname: yup.string().required(),
	email: yup.string().required().email(),
	image: yup.string().url(),
});

**Comment by parad0xe** [comment]
I hope this will help someone.

```ts
import { Schema } from "yup"

export type Shape<Fields extends Object, Strict = true> = {
	[Key in keyof (Strict extends true ? Fields : Partial<Fields>)]: Fields[Key] extends object
		? Schema<Strict extends true ? Fields[Key] : Partial<Fields[Key]>>
		: Schema<Fields[Key]>
}
```

Then,

```ts
const mySchema = object().shape<Shape<MyType, true | false>>({ 
    ... 
})
```

**Comment by codemile** [comment]
Why is this still so hard?

**Comment by Hashiphoto** [comment]
This is fully solved. See the README section: [Ensuring a schema matches an existing type](https://github.com/jquense/yup?tab=readme-ov-file#ensuring-a-schema-matches-an-existing-type)

**Comment by epeguero** [comment]
This doesn't work on yup 1.4.0.
The below does not produce the expected type error:

```
type Form = { a: number; b: string; c: number };
// Expected type error, but none produced
const badSchema: yup.ObjectSchema<Form> = yup.object({
  aa: yup.number().required(),
  a: yup.number().required(),
  b: yup.string().required(),
  c: yup.number().required(),
  d: yup.string(),
});
```

[Code Sandbox](https://codesandbox.io/p/sandbox/thys5s)

**Comment by davisperezg** [comment]
> I hope this will help someone. `my yup version: 1.4.0`
> 
> _**Add three new custom types: `Shape`, `Infer` and `GetSchemaDefinition`**_
> 
> ```ts
> // yup.types.ts
> 
> import { AnySchema, InferType, ObjectSchema, Schema } from "yup"
> 
> type GetSchemaDefinition<T> = T extends ObjectSchema<infer U> ? U : never
> 
> export type Shape<DType extends object, Strict = true> = {
> 	[Key in keyof (Strict extends true ? DType : Partial<DType>)]: DType[Key] extends Array<any>
> 		? Schema<DType[Key]>
> 		: DType[Key] extends object
> 			? Strict extends true ? Schema<DType[Key]> : Schema<Partial<DType[Key]>>
> 			: Schema<DType[Key]>
> }
> 
> export type Infer<TSchema extends ObjectSchema<unknown>> = InferType<AnySchema<GetSchemaDefinition<TSchema>>>
> ```
> 
> Then,
> 
> ```ts
> // my-type.schema.ts
> 
> import { Infer, Shape } from "path/to/yup.types.ts"
> import { object, Schema } from "yup"
> 
> type MyType = {
>     a: "value 1",
>     b?: "value 2",
>     c: "Value 3"
> }
> 
> const _mySchema = object().shape<Shape<MyType, true | false>>({ 
>     ... 
> })
> 
> export type mySchemaType = Infer<typeof _mySchema>
> export const mySchema = _mySchema as Schema<mySchemaType>
> ```
> 
> > object().shape<Shape<MyType, _**true**_>>({ ... })      # mySchemaType = { a: string, b?: string, c: string }
> > object().shape<Shape<MyType, _**false**_>>({ ... })     # mySchemaType = { a?: string, b?: string, c?: string }
> 
> Work with nested yup objects
> 
> With react-hook-form - yupResolver
> 
> ```ts
> import { Resolver } from "react-hook-form"
> export const mySchemaResolver = yupResolver(_mySchema) as Resolver<mySchemaType>
> ```

```ts
// yup.types.ts

export type Infer<TSchema extends ObjectSchema<unknown>> = InferType<AnySchema<GetSchemaDefinition<TSchema>>>
```

I get: Type 'unknown' does not satisfy the constraint 'Maybe<AnyObject>'

I had to place any

```ts
// yup.types.ts

export type Infer<TSchema extends ObjectSchema<any>> = InferType<AnySchema<GetSchemaDefinition<TSchema>>>
```

The typing works fine for me, thanks, could you clarify why I export "mySchema" if it doesn't have a use?

```ts
// my-type.schema.ts

...

export const mySchema = _mySchema as Schema<mySchemaType>
```

**Comment by parad0xe** [comment]
Hi @davisperezg 

You're welcome!

Indeed, if you don't use it, there's no reason to export it. 
In my example, I've only specified it to show its use.

You can therefore delete this line:
> export const mySchema = _mySchema as Schema<mySchemaType>

if you don't use it.

**Comment by davisperezg** [comment]
> Hi [@davisperezg](https://github.com/davisperezg)
> 
> You're welcome!
> 
> Indeed, if you don't use it, there's no reason to export it. In my example, I've only specified it to show its use.
> 
> You can therefore delete this line:
> 
> > export const mySchema = _mySchema as Schema
> 
> if you don't use it.

my optional attributes are typed as unknown and not as 'string | undefined'.

```ts
export interface IFormProduct {
  cantidad: number;
  codigo?: string;
  descripcion: string;
  mtoValorUnitario: string;
  porcentajeIgv: number;
  tipAfeIgv: string;
  unidad: string;
}
```

```ts
export const _mySchemaProduct = yup.object().shape<Shape<IFormProduct, true>>({
  tipAfeIgv: yup
    .string()
    .required("El tipo de afectación del IGV es obligatorio"),
  cantidad: yup
    .number()
    .min(0.000001, "La cantidad debe ser al menos 0.000001")
    .required("La cantidad es obligatoria"),
  unidad: yup.string().required("La unidad es obligatoria"),
  descripcion: yup
    .string()
    .min(3, "Campo obligatorio [3-500 caracteres]")
    .max(500, "Campo obligatorio [3-500 caracteres]")
    .required("Campo obligatorio."),
  mtoValorUnitario: yup
    .string()
    .typeError("Campo obligatorio")
    .required("Campo obligatorio"),
  porcentajeIgv: yup
    .number()
    .positive("El porcentaje debe ser positivo")
    .required("Campo obligatorio"),
  codigo: yup.string().optional(),
});
```

where 'codigo' detects me as unknown when it should be 'string | undefined'.

**Comment by parad0xe** [comment]
Hi @davisperezg

Indeed, when using the `?:` syntax to define a property, Yup is unable to infer the type as `type | undefined`.

To prevent this, you should explicitly define the property as `codigo: string | undefined`.

The reason for this behavior is that the `?:` syntax specifies whether a property may or may not exist in the object. As a result, Yup cannot reliably determine the type of the property in cases where it is defined.

**Comment by davisperezg** [comment]
Hi @parad0xe Thanks for the clarification, you helped me a lot.

```ts
interface A {
  a: string;
  b: string;
  c: C;
}

interface C {
  name: string | undefined;
}

const sche = yup.object().shape<Shape<A, true>>({
  a: yup.string().required(),
  b: yup.string().required(),
  c: yup
    .object()
    .shape<Shape<C, true>>({
      name: yup.string().optional(),
    })
    .required(),
});
```

ts error: Property 'name' is optional in type '{ name?: string | undefined; }' but required in type 'C'

I get the same error with arrays
