### ISSUE TITLE
At least new UpdateQuery<T> in mongodb 3.1.10 is broken

### ISSUE THREAD

**Issue by JochenAtWork** [DefinitelyTyped/DefinitelyTyped#29429]
To make it usefull all fields should be optional. Elsewhere:

  Type '{ $set: { locked: boolean; }; }' is not assignable to type 'UpdateQuery<IDbFloor>'.
    Property '$inc' is missing in type '{ $set: { locked: boolean; }; }'.

**Comment by wingsbob** [comment]
Additionally, `$addToSet` isn't allowed by the new types

**Comment by JochenAtWork** [comment]
Sorry, we are just prior to production and I fixed the dependency to below 3.1.10. But I checked your commit and it looks as I would expect it in the first place.

So I'll close this issue for me now.

Just wondering why in Condition $where ist not optional.

**Comment by floric** [comment]
> Sorry, we are just prior to production and I fixed the dependency to below 3.1.10. But I checked your commit and it looks as I would expect it in the first place.
> 
> So I'll close this issue for me now.
> 
> Just wondering why in Condition $where ist not optional.

Oh, not sure. I didn't need conditions yet. But I just reused the existing conditions and refactored them. In case somethings breaks again feel free to improve them. :/
