### ISSUE TITLE
React-native Switch missing props

### ISSUE THREAD

**Issue by Hauglid** [DefinitelyTyped/DefinitelyTyped#29466]
Description
The typescript definition for Switch is missing the new props thumbColor and trackColor in:
"@types/react-native": "0.57.1",

Gives error
TS2339:
Property 'thumbColor' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes & Readonly<{ children?: ReactNode; }> & Readonly'.

Property 'trackColor' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes & Readonly<{ children?: ReactNode; }> & Readonly'.

  - Authors: 
 @alloy @huhuanming @iRoachie @skn0tt @timwangdev @kamal @nelyousfi @alexdunne @swissmanu @bm-software @tkrotoff @a-tarasyuk @mvdam @esemesek

Notes: 
I tried to look in the index.d.ts file to see where I could add the props and make a PR, but it was a bit too confusing, sorry.

**Comment by iRoachie** [comment]
These props don't exist in the documentation. https://facebook.github.io/react-native/docs/slider

**Comment by Hauglid** [comment]
Thats because I am using the Switch, not the Slider. 

https://facebook.github.io/react-native/docs/switch

Trackcolor is one of the props, seems like i misspelled thumbTintColor though.

**Comment by iRoachie** [comment]
Oh my so sorry 🤦🏽‍♂️

**Comment by Hauglid** [comment]
According to this commit thumbTintColor has been renamed to thumbColor, but I am on my  phone so I can’t see if the commit has been added or not.
https://github.com/facebook/react-native/commit/965adee109b86cc36f39a713237ade9592f13dad

**Comment by iRoachie** [comment]
Added here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29477/files. Will have to wait on a release for `thumbColor`

**Comment by Hauglid** [comment]
thumbTintColor gives a warning when used. 
According to this commit thumColor is the corret prop to use. 
https://github.com/facebook/react-native-website/pull/572

**Comment by iRoachie** [comment]
There's no thumbColor prop here https://facebook.github.io/react-native/docs/switch so it probably isn't released yet?

**Comment by Hauglid** [comment]
It is, I have checked the source code (https://github.com/facebook/react-native/blob/0.57-stable/Libraries/Components/Switch/Switch.js)  and if you choose the master branch for the documentation you can see that the prop is updated there as well.
