### ISSUE TITLE
[styled-components] Property 'View' does not exist on type 'ThemedBaseStyledInterface<any>'. Did you mean 'view'?

### ISSUE THREAD

**Issue by jgfidelis** [DefinitelyTyped/DefinitelyTyped#29474]
If you know how to fix the issue, make a pull request instead.

Authors: @Igorbek @Igmat
typescript: `^3.0.1`
styled-components: `4.0.0-beta.10` and also tried  `3.4.9`
@types/styled-components: `3.0.1`

If try to do:
`const A = styled.View` I get the error:

` Property 'View' does not exist on type 'ThemedBaseStyledInterface<any>'. Did you mean 'view'`

Am I doing something wrong?

**Comment by gitsad** [comment]
Here is your answer:
change `import styled from 'styled-components';` into `import styled from 'styled-components/native';`

**Comment by jgfidelis** [comment]
@gitsad thanks! A friend told me the same thing some days ago, I think it should be better documented in the styled-components docs

**Comment by dawidk92** [comment]
This issue needs to be reopened.

When I'm importing styled-components like: `import styled from "styled-components/native"`
TypeScript throws an error: `TS7016: Could not find a declaration file for module 'styled-components/native'. '[project_path]/node_modules/styled-components/native/dist/styled-components.native.cjs.js' implicitly has an 'any' type.`

Package versions:
typescript: `3.1.1`
styled-component: `4.0.0-beta.11.3`
@types/styled-components: `4.0.1` also tried `3.0.2`

Beside that `styled-components/native` is [deprecated from version 3 or higher](https://www.styled-components.com/docs/basics#react-native) so importing from it shouldn't be a solution.

**Comment by jgfidelis** [comment]
@dawidk92 Using `@types/styled-component: 3.0.2` and `styled-component: 3.4.9`, I am able to use when importing from `styled-components/native`. I think the 4.0.0 beta still does not have types.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by sakilobm** [comment]
Maybe you are using **expo** TRY THIS
See this Expo Documentation Bottom of the page
[https://docs.expo.dev/guides/using-styled-components/](url)

You are using Expo project, It's Work Try It
------------------------------------------------------------
 - import styled from 'styled-components/native';
 - const Container = styled.View`
 ------------------------------------------------------------
 + import styled from 'styled-components';
 + const Container = styled(View)`
    background-color: #fff;
-------------------------------------------------------------
