### ISSUE TITLE
[three] Cannot find 'VRDisplay'

### ISSUE THREAD

**Issue by Chiff** [DefinitelyTyped/DefinitelyTyped#29515]
After using `@types/three` i get this error:

```
ERROR in node_modules/@types/three/three-core.d.ts(7799,18): error TS2304: Cannot find name 'VRDisplay'.
node_modules/@types/three/three-core.d.ts(7800,23): error TS2304: Cannot find name 'VRDisplay'.
node_modules/@types/three/three-vrcontrols.d.ts(15,27): error TS2304: Cannot find name 'VRDisplay'.
node_modules/@types/three/three-vreffect.d.ts(20,27): error TS2304: Cannot find name 'VRDisplay'.
```

Reproduction steps: 
 * `ng new app`
 * `yarn add @types/three`
 * Adding reference to `app.component.ts`: `/// <reference path="../../node_modules/@types/three/index.d.ts"/>`
 * `ng serve`

Right now i'm editing lines below to type `any`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/57c4cca47bb51cfd5696b21cafc66d0a5a06b5ff/types/three/three-core.d.ts#L7799

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/57c4cca47bb51cfd5696b21cafc66d0a5a06b5ff/types/three/three-core.d.ts#L7800

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/57c4cca47bb51cfd5696b21cafc66d0a5a06b5ff/types/three/three-vrcontrols.d.ts#L15

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/57c4cca47bb51cfd5696b21cafc66d0a5a06b5ff/types/three/three-vreffect.d.ts#L20

Is this issue on my side or can I create pull request to change type from `VRDisplay` to `any`?

Repo: https://github.com/Chiff/Vrdisplay-issue-types-three

**Comment by ryan0122** [comment]
I'm having the same issues. Please address.

**Comment by vkarenko** [comment]
Hi all!
I'm just updated version of "Typescript" to v.2.8.1 in my project and it's compiling without any errors now.

**Comment by Chiff** [comment]
> Hi all!
> I'm just updated version of "Typescript" to v.2.8.1 in my project and it's compiling without any errors now.

I did test `typescript@2.8.1` and it did not make any error.


However this produces following warning:
```
@angular/compiler-cli@6.1.9 requires typescript@'>=2.7.0 <2.8.0' but 2.8.1 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.7.0 <2.8.0'

To disable this warning run "ng config cli.warnings.typescriptMismatch false".
```

Also I should've mentioned I'm running project on `angular@6.0.8` and after little search I found this issue https://github.com/angular/angular/issues/25141#issuecomment-408173569. I will test it later.

**Comment by Chiff** [comment]
Also look at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28692#issuecomment-419628917 (I will test it later)
