### ISSUE TITLE
angular.d.ts: Missing definition resumeBootstrap

### ISSUE THREAD

**Issue by thisispaul** [DefinitelyTyped/DefinitelyTyped#2955]
I might be wrong but it looks to me that the angular definitions file is missing the resumeBootstrap function.

The use of this function is explained here: https://docs.angularjs.org/guide/bootstrap

It's probably been missed as the function doesn't even exist unless the window name is "NG_DEFER_BOOTSTRAP!"

**Comment by schmkr** [comment]
Yes, it's missing. You can find the function defined in `angular.js` here:

https://github.com/angular/angular.js/blob/426a5ac0547109648e5c5e358f668c274a111ab2/src/Angular.js#L1537

**Comment by galuszkak** [comment]
I think this should be closed as it is fixed here: 
`https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/angular/index.d.ts#L180`
