### ISSUE TITLE
Property 'expand' does not exist on type 'MatcherUtils'.

### ISSUE THREAD

**Issue by haldunanil** [DefinitelyTyped/DefinitelyTyped#29574]
See original issue created in the Jest Github [here](https://github.com/facebook/jest/issues/7091#issuecomment-426685869). 

- [X] I tried using the `@types/jest` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Asana @NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @ahnpnl @JoshuaKGoldberg @UselessPickles @r3nya @Hotell @sebald

**Comment by haldunanil** [comment]
Hi @wsmd, thanks for the speedy fix! When will it hit `npm` for an update?

**Comment by andy-ms** [comment]
@haldunanil Looks like it's already been published.

**Comment by haldunanil** [comment]
Yep, it's resolved on my end as well. Thanks @wsmd and @andy-ms !
