### ISSUE TITLE
React: unexpected error when passing single item array as children

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#29570]
``` tsx
import * as React from 'react';

const Wrapper: React.SFC<{
    children: Array<React.ReactElement<{}>>;
}> = ({ children }) => <div>{children}</div>;

const el = (
    /* Type '{ children: Element; }' is not assignable to type '{ children: ReactElement<{}>[]; }'.
  Types of property 'children' are incompatible.
    Type 'Element' is not assignable to type 'ReactElement<{}>[]'.
      Property 'length' is missing in type 'Element'. */
    <Wrapper>
        <div>foo</div>
    </Wrapper>
);

const el2 = (
    // No error, good!
    <Wrapper>
        <div>foo</div>
        <div>foo</div>
    </Wrapper>
);
```

Workaround:

``` tsx
export const Wrapper: React.SFC<{
    children: React.ReactElement<{}> | Array<React.ReactElement<{}>>;
}> = ({ children }) => <div>{children}</div>;

const el = (
    <Wrapper>
        <div>foo</div>
    </Wrapper>
);
```

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei 

If you do not mention the authors the issue will be ignored.

**Comment by Hotell** [comment]
This is correct behaviour. 

If only single Node is provided as a child it's type of `ReactNode`, if you provide multiple items, it's an array. 
Preact behaves differently  ( children is always an array ). In react you can mitigate that via `Children.toArray(this.props.children)` 

![image](https://user-images.githubusercontent.com/1223799/47086198-244f6b00-d219-11e8-94c6-6d802a765f3f.png)

**Comment by OliverJAsh** [comment]
> If only single Node is provided as a child it's type of `ReactNode`, if you provide multiple items, it's an array.

I understand this is the behaviour, but do you know where this behaviour is defined? Why is this the behaviour, instead of always using an array?

**Comment by Hotell** [comment]
That's how React implements children. You can search in their source

**Comment by ferdaber** [comment]
It's defined here: https://github.com/facebook/react/blob/4f0bd45905b52b52406a006ccf42046828aa6bf2/packages/react/src/ReactElement.js#L205

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
