### ISSUE TITLE
Prevent typescript-bot from mentioning me

### ISSUE THREAD

**Issue by matthieusieben** [DefinitelyTyped/DefinitelyTyped#29602]
So, I contributed once and provided a fix.

Now I keep being mentioned by @typescript-bot.

How can I stop the spam madness, @RyanCavanaugh ?

**Comment by matthieusieben** [comment]
Basically the opposite of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29584

**Comment by RyanCavanaugh** [comment]
It's pinging you because you added your name to the author list

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L22

You can remove yourself from that list if you don't want to be pinged for notifications, or just Block the bot using the normal github UI
