### ISSUE TITLE
openpgp.decrypt is async but not in the types interface

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [DefinitelyTyped/DefinitelyTyped#29646]
- [X] I tried using the `@types/openpgp` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @damonpam

In the source code of openpgpjs one can see, that `openpgp.message.read` is an asynchronous function: https://github.com/openpgpjs/openpgpjs/blob/37517313307ae2d2f8e200d265dd9fffeada21f4/src/message.js#L708.
However, in the types, this is not indicated. Hence the TypeScript compiler will show an error when trying to compile the following snippet:

    function openpgp_decrypt(encrypted: string): string {
        let u8int_encoder = new TextEncoder();
        let encrypted_u8int_arr = u8int_encoder.encode(encrypted);

        // https://github.com/openpgpjs/openpgpjs/blob/master/README.md#getting-started
        let options: openpgp.DecryptOptions = {
            message: await openpgp.message.read(encrypted_u8int_arr),
            passwords: ["something"],
            format: "utf8"  // "utf8" | "binary"
        };

        openpgp.decrypt(options).then((plaintext: openpgp.VerifiedMessage) => {
            // The attribute `data` will have the decrypted message as
            // either `Uint8Array` or `string`, depending on what was
            // specified in the `DecryptOptions` given to `decrypt`.
            return plaintext.data;
        }).catch((err) => {
            return `ERROR WHILE DECRYPTING: ${err}`;
        });
        return "OTHER ERROR";
    }

The error being:

    src/index.ts:223:22 - error TS1308: 'await' expression is only allowed within an async function.

    223             message: await openpgp.message.read(encrypted_u8int_arr),
                             ~~~~~

(Of course line numbers and file names can differ in other projects.)

I believe this to be an error in the types. If this is not so, please let me know how one would go about decrypting as intended in the code snippet, using TypeScript.

My package versions are:

    "dependencies": {
        ...
        "@types/openpgp": "^4.0.0",
        "openpgp": "^4.1.1"
    },
    "devDependencies": {
        ...
        "typescript": "^3.1.2"
    },

My `tsconfig.json` looks as follows:

    {
        "compilerOptions": {
            "declaration": true,
            "noImplicitAny": true,
            "noEmitOnError": true,
            "noUnusedLocals": true,
            "module": "commonjs",
            "moduleResolution": "node",
            "target": "ES6",
            "outDir": "./lib",
            "lib": [
                "ES6",
                "DOM"
            ],
            "types": []
        },
        "include": ["src/*"]
    }

In the my `node_modules` directory, I was also able to find `openpgp` and its `dist` folder, where I found the following code inside `openpgp.js`:

    /**
     * Read a chunk of data.
     * @returns {Promise<Object>} Either { done: false, value: Uint8Array | String } or { done: true, value: undefined }
     * @async
     */
    Reader.prototype.read = async function () {
      if (this[externalBuffer] && this[externalBuffer].length) {
        const value = this[externalBuffer].shift();
        return { done: false, value };
      }
      return this._read();
    };

I am not sure this is exactly the method that is in the `namespace` `message`, but I would guess so. So the `async` seems to be there as well.

Edit 1: I read on https://stackoverflow.com/questions/52116664/declaring-an-async-method-in-a-typescript-module, that the `async` keyword is of no relevance in type definitions, but instead that the return type is a `Promise`. If that is truly the case, then the return types are missing instead of the `async` keyword.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
