### ISSUE TITLE
[swagger-schema-official] v2.0.11 breaks existing functionality

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [DefinitelyTyped/DefinitelyTyped#29696]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/swagger-schema-official` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bsouthga @nimerritt @mauriedo 

If you do not mention the authors the issue will be ignored.

I was using v2.0.10 without any issues but the last update in v2.0.11 is breaking my code.

I am calling `this.doc.definitions[definition].properties` where `doc` is of the type `Spec`. The error thrown is 

```
error TS2339: Property 'properties' does not exist on type 'Referenceable<Schema>'.
  Property 'properties' does not exist on type '{ $ref: string; }'.
```

**Comment by mauriedo** [comment]
Hi @SayakMukhopadhyay, apologies, you are totally right. I messed it up by wanting to increase the scope of my change (the last thing merged).

I've reverted part of my changes and they are in Pull Request now. Hoping this fixes your issue soon.
