### ISSUE TITLE
N3: Term definition issues

### ISSUE THREAD

**Issue by LaurensRietveld** [DefinitelyTyped/DefinitelyTyped#29703]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @phreed @rubensworks

I found two issues in the ts defs that needs discussing:
- The typescript def exposes N3 term types, such as [Literal](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/n3/index.d.ts#L48) from the root index file. Importing this class (e.g. to do `instanceof` checking) wont work, because N3 seems to [expose](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/n3/index.d.ts#L48) this via the `N3.DataFactory.internal.Literal` 
- The `N3.DataFactory.literal` function returns something of type `RDF.Literal` (see [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/n3/index.d.ts#L79)). This is not compatible with N3, and it should return the _N3_ class Literal as return type

Not submitting a PR here because I'm not sure how we should proceed with fixing the typings. I wouldnt mind the following fix, but that would need some rewiring in N3 itself as well:
1) Move the term types in `N3.DataFactory.internal` to the root of N3. That would automatically fix the issue of the typescript defs (that are defining these term types at the root)
2) Change the return type of the DataFactory functions from the RDF type defs, to the `N3` defs for terms

**Comment by rubensworks** [comment]
> Change the return type of the DataFactory functions from the RDF type defs, to the N3 defs for terms

This seems like a clean solution (not sure why I didn't write them like this initially).

I'm on holidays at the moment, so I'm not able to implement this change myself atm, but I'd be happy to review a PR if you'd submit one.

**Comment by LaurensRietveld** [comment]
Sure, I'll add it in a PR. Will add some other stuff as well, like typings for the `toJSON` functions.
One other typing related thing we should discuss is the `Term` definition. Is there a reason why `Term` wasnt defined as `type Term = Literal | NamedNode | BlankNode` (etc etc)?
Such a definition would make the typings more powerful, as typescript would derive what type you have based on your conditions

**Comment by rubensworks** [comment]
> Is there a reason why Term wasnt defined as type Term = Literal | NamedNode | BlankNode (etc etc)?

I think the main reason was support for extensibility. But you could argue that developers should not be able to add new term types themselves, so in that sense it makes sense to change the typings as such.

I'm just wondering if this would be a breaking change in existing code that uses these typings (probably not).

**Comment by LaurensRietveld** [comment]
I'm  not seeing any errors in my code (or n3) when switching to a union type. I agree there _could_ be breaking changes, but those would probably be corner cases that might not be that spec compliant anyway

About extensibility: I've seen some discussion in the spec about this (https://github.com/rdfjs/representation-task-force/issues/121). General consesus seems to be that we're going for a closed set (though nothing is decided yet). We _could_ use generics if we'd like to support extensibility, but that would feel like we're changing the interface for a use case that isnt going to happen anyway.

About the PR: perhaps it's better if you do that when you get back, because there are many `RDF.Term` references of which we can probably switch 90% to `Term`. In practice a simple find/replace operation, but I'd like to avoid renaming one too many

**Comment by rubensworks** [comment]
Sure! I can look into it around the end of this month.

**Comment by LaurensRietveld** [comment]
Went ahead an started a PR anyway, considering I was doing the same thing in rdf-js as well: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29836
