### ISSUE TITLE
[@types/jest] expect.not does not exist on type 'Expect'

### ISSUE THREAD

**Issue by maschino** [DefinitelyTyped/DefinitelyTyped#29715]
I'm trying to write an unit test with the following expection:

```expect(groupClass).toEqual(expect.not.stringContaining(className));```

The typings are telling me that not does not exist on type 'Expect'. I think the typings are slightly incorrect, as `expect(foo).not.toBe(bar)` does work.

Relevant part in the jest documentation:
https://jestjs.io/docs/en/expect#not

I guess the fix is quite simple, I tried adding the following to the types and I guess it works. However I don't have enough experience with this repo and how the tests work, so I'm not sure how to do the PR myself.

```
interface Expect {
...
    /**
    * If you know how to test something, `.not` lets you test its opposite.
    */
    not: Expect;
...
}
```

**Comment by maschino** [comment]
I forgot to mention the authors:

 Mention the authors (see Definitions by: in index.d.ts) so they can respond.
Authors: @Asana @NoHomey @jwbay @asvetliakov @alexjoverm  @epicallan  @ikatyang  @wsmd  @JamieMason  @douglasduteil  @ahnpnl  @JoshuaKGoldberg  @UselessPickles  @r3nya  @Hotell  @sebald

**Comment by wsmd** [comment]
Thanks for submitting the issue, @maschino! I look into in the issue shortly.

> so I'm not sure how to do the PR myself.

In the mean time, you can find more information and construction on how to contribute to the project here. https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute
