### ISSUE TITLE
[@types/react-redux] Infer injected component props with new ReturnType conditional type

### ISSUE THREAD

**Issue by TimoGlastra** [DefinitelyTyped/DefinitelyTyped#29759]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @kenzierocks @clayne11 @tansongyang  @NicholasBoll  @mDibyo @pdeva @Kallikrein @val1984 @jrakotoharisoa @apapirovski 

Since TypeScript 2.8 TypeScript now has the ReturnType type conditionals for functions. Every example i see for getting types for connected components the interfaces are declared explicitly with the injected props.

The props for connected components could be inferred from `mapStateToProps` and `mapDispatchToProps` with the new ReturnType.

I'm not sure if it will work for all cases, but in my project have it set it up like below:

```typescript
const mapStateToProps = (state: RootState) => ({ // RootState contains declaration for whole state
  products: state.product.products,
  error: state.product.error,
  isLoading: state.product.isLoading
});

const mapDispatchToProps = (dispatch: Dispatch) =>
  bindActionCreators(
    {
      // actionCreators returns objects with type and payload
      getVaccinationAddresses: actionCreators.getVaccinationAddresses,
    },
    dispatch
  );

// Combine return types of both functions
type ReduxProps = ReturnType<typeof mapStateToProps> & ReturnType<typeof mapDispatchToProps>;
```

After this the `ReduxProps` type could be used for a component:

```typescript
interface Props extends ReduxProps {
    myOtherProp: string
}
```

If i'm not overlooking anything i think this could be a great way to reduce unnecessary code. If so i would be happy to further investigate the issue / enhancement.

**Comment by ablakey** [comment]
Thank you for sharing this. I'm using it now and it seems to work fine so far. Greatly cuts down on repeated typing.

**Comment by nirus** [comment]
@TimoGlastra  Perfect. Works better. Thanks for the solution.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
