### ISSUE TITLE
PapaParse referencing unknown name "File"

### ISSUE THREAD

**Issue by SaltyQuetzals** [DefinitelyTyped/DefinitelyTyped#29752]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @torpedro, @rainshen49, @jfloff, @johnnyreilly, @albertorestifo, @BehindTheMath, @3af 

__TSC Version__ 3.1.1

I clean installed `@types/papaparse` from npm, and was notified of the following errors when compiling:

```
Cannot find name 'File'.

export function parse(file: File, config?: ParseConfig): ParseResult;
```

```
Cannot find name 'File'.

complete?(results: ParseResult, file?: File): void; // default: undefined
```

```
Cannot find name 'File'.

error?(error: ParseError, file?: File): void;       // default: undefined
```

I'm new to Typescript, and it seems as though the TSC version these types were written for was 2.2, which was released over a year ago. Is there any way these definitions can be updated?

**Comment by BehindTheMath** [comment]
Did you set the `lib` option in the `compilerOptions` in `tsconfig.json`? It includes `DOM` by default, but if you set it manually, you need to add `DOM`.

**Comment by SaltyQuetzals** [comment]
I haven't set the `lib` option in `compilerOptions`. My `target` option is `"es6"`, which the [Compiler Options page](https://www.typescriptlang.org/docs/handbook/compiler-options.html) says includes `DOM`.

**Comment by SaltyQuetzals** [comment]
```language=json

// tsconfig.json
{
  "extends": "./node_modules/gts/tsconfig-google.json",
  "compilerOptions": {
    "rootDir": ".",
    "outDir": "build",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "es6"
  },
  "include": [
    "src/*.ts",
    "src/**/*.ts",
    "test/*.ts",
    "test/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

```
// usage
import {parse} = require('papaparse');

**Comment by BehindTheMath** [comment]
Your tsconfig.json extends that of [gts](https://github.com/google/ts-style/blob/aced6158df1f43ebc875823d9dc43fa6a4f7aacb/tsconfig-google.json), which sets the `lib` option. If you want to use Papaparse, you need to override it and include `DOM`.

**Comment by marc101101** [comment]
in your tsconfig.json:

```
 "compilerOptions": {
    "rootDir": ".",
    "outDir": "build",
    "noImplicitAny": false,
    "lib":["DOM"]
  },
```

Explanation: https://stackoverflow.com/questions/39303385/what-does-the-tsconfig-option-lib-do
