### ISSUE TITLE
Use const enum instead of enum for Sharepoint type Definitions

### ISSUE THREAD

**Issue by DanielHabenicht** [DefinitelyTyped/DefinitelyTyped#29777]
I will provide a PR shortly but wanted to ask before. 

- [x] I tried using the `@types/sharepoint` package and had problems.
- Authors: @gandjustas @andrei-markeev @baywet @teroarvola @dennispg

The issue is that if you use Enums from this Type definition (e.g.: `SP.FieldType.note` ) without loading SP.js beforehand, there will be a runtime error like `Uncaught TypeError: Cannot read property 'note' of undefined`. 

In order to resolve this it would be great if the complier would simply inline the value of the enum, when compiling. 

This is achieved by using `const enum`: https://medium.com/@katbusch/typescript-enums-explained-e5f9a101afc9

What do you think about it?

**Comment by dennispg** [comment]
This is very interesting and a nice catch. I've gone ahead and approved the pull request, however I do have some thoughts:

If you were not using typescript, and for example wanted to refer to SP.FieldType.note from a plain JS script.. You would normally need to wait for SP.js to load before you could rely on using SP.FieldType.note, that's expected.

This optimization allows you to leverage these constants even from say a non-browser node.js or electron sort of context, so thats good.

However, if for some crazy reason Microsoft decides to change the value of one of these enums in the future, this type definition would need to be kept in perfect sync to avoid some extremely strange potential bugs.. I know it should be exceedingly rare for a change like that, but crazier things have happened.

Just food for thought.

Thanks for the pull request!

**Comment by DanielHabenicht** [comment]
I just encountered the problem you described. 

I think I will remove the PR and go for more granular changes, changing one `const` after another, when I have tested it working with my app. 

This would be a breaking change otherwise, because it would provide the wrong id's for e.g. `ListTemplateTypes`.

**Comment by DanielHabenicht** [comment]
And thats where it gets tricky, Microsoft defines some enum values as `undefined`. In Typescript you can't specify
```typescript
const enum ListTemplateType {
    accessRequest = undefined,
}
``` 
I could just go ahead and init them with a random value. But I am not sure if it breakes something. 
Any ideas how to circumvent this problem?

**Comment by dennispg** [comment]
Well specifically in the case of this enum `ListTemplateType`, even though the MS docs say "undefined", if you look directly in `sp.js` they are all actually defined with a proper value:

```javascript
SP.ListTemplateType.prototype = {
    invalidType: -1,
    noListTemplate: 0,
    genericList: 100,
    documentLibrary: 101,
    survey: 102,
    links: 103,
    announcements: 104,
    contacts: 105,
    events: 106,
    tasks: 107,
    discussionBoard: 108,
    pictureLibrary: 109,
    dataSources: 110,
    webTemplateCatalog: 111,
    userInformation: 112,
    webPartCatalog: 113,
    listTemplateCatalog: 114,
    xmlForm: 115,
    masterPageCatalog: 116,
    noCodeWorkflows: 117,
    workflowProcess: 118,
    webPageLibrary: 119,
    customGrid: 120,
    solutionCatalog: 121,
    noCodePublic: 122,
    themeCatalog: 123,
    designCatalog: 124,
    appDataCatalog: 125,
    appFilesCatalog: 126,
    dataConnectionLibrary: 130,
    workflowHistory: 140,
    ganttTasks: 150,
    helpLibrary: 151,
    accessRequest: 160,
    promotedLinks: 170,
    tasksWithTimelineAndHierarchy: 171,
    maintenanceLogs: 175,
    meetings: 200,
    agenda: 201,
    meetingUser: 202,
    decision: 204,
    meetingObjective: 207,
    textBox: 210,
    thingsToBring: 211,
    homePageLibrary: 212,
    posts: 301,
    comments: 302,
    categories: 303,
    facility: 402,
    whereabouts: 403,
    callTrack: 404,
    circulation: 405,
    timecard: 420,
    holidays: 421,
    imeDic: 499,
    externalList: 600,
    mySiteDocumentLibrary: 700,
    issueTracking: 1100,
    adminTasks: 1200,
    healthRules: 1220,
    healthReports: 1221,
    developerSiteDraftApps: 1230,
    accessApp: 3100,
    alchemyMobileForm: 3101,
    alchemyApprovalWorkflow: 3102,
    sharingLinks: 3300,
    hashtagStore: 3400,
    recipesTable: 3410,
    formulasTable: 3411,
    webTemplateExtensionsList: 3415,
    itemReferenceCollection: 3500,
    itemReferenceReference: 3501,
    itemReferenceReferenceCollection: 3502
};
```

Converting to `const enum` requires that all these values be defined in the .d.ts as well, and now that I look more closely.. most of the enums in this definition do not have any of the values necessary for that to be useful. Also the more I think about it, that is the correct way for it to be defined here as well. I was wrong to approve the pull request without thinking more into it.

`sp.js` provides these enums so that they can be managed and/or changed from `sp.js` without needing to change anything on the consumer's side. The compiled JS should still contain SP.FieldType.note.

I think the capability to be able to inline/hardcode these values  in the compiled JS without `sp.js` being loaded is a separate use case in fact. I think maybe the better approach for this then, is for all these enums to be copied and housed in a separate npm module altogether as const enums. For example:

```typescript
import {FieldType} from 'sharepoint-jsom-enums';
```

**Comment by DanielHabenicht** [comment]
Yeah, maybe I will make a package out of it. For now everything works, if you do it locally:
1. create a folder `types` in your project
2. Copy the sharepoint folder from `@types` into your project and make the changes you want.
3. Modify your `tsconfig.json` to include your types folder: 
```
{
"compilerOptions": {
    "module": "commonjs",
    "noImplicitAny": true,
    "typeRoots": [
        "./node_modules/@types",
        "./types/",
    ]
},
"files": ["./app.ts"]
}
```
As described here: https://stackoverflow.com/a/45437448
3. Uninstall Sharepoint Types: `npm uninstall -S @types/sharepoint`
4. Install the dependecy for sharepoint types: `npm install -S @types/microsoft-ajax`
