### ISSUE TITLE
office-js: No definition for Office.context.auth.getAccessTokenAsync()

### ISSUE THREAD

**Issue by AKlaus** [DefinitelyTyped/DefinitelyTyped#29771]
If you know how to fix the issue, make a pull request instead.

- [ x ] I tried using the `@types/xxxx` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @OfficeDev, @LanceEA, @Zlatkovsky, @kbrandl, @Rick-Kirkham, @AlexJerabek, @ElizabethSamuel-MSFT.

----
`office-js` doesn't have definition for [Office.context.auth.getAccessTokenAsync()](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins#sso-api-reference) and `Office.context.auth` at all.

**Comment by AlexJerabek** [comment]
@mosslive, @AKlaus, @Rick-Kirkham We're working on a beta/preview plan for DefinitelyTyped and our office-js documentation as a whole. I'll be sure to alert the thread when there's something available.

**Comment by AlexJerabek** [comment]
Hi @AKlaus and @mosslive,

I've submitted PR #34086 to address this issue. We'll be using `@types/office-js-preview` for preview APIs going forward. Right now, aside from the SSO APIs, there are Excel and Word preview APIs there. We're working on transitioning the Outlook add-in preview APIs there as well (they're currently in `@types/office-js`).

Thanks! I can't close the issue, but I believe this is resolved, correct?

**Comment by AKlaus** [comment]
@AlexJerabek, it's a good solution. Thank you!

**Comment by ElizabethSamuel-MSFT** [comment]
Small clarification about Outlook: The preview items are currently in -preview as well but we're working on removing them from @types/office-js.

**Comment by AlexJerabek** [comment]
Good catch @ElizabethSamuel-MSFT. I've updated my comment.

**Comment by ElizabethSamuel-MSFT** [comment]
@ryancavanaugh I believe this issue has been resolved. Can you close this item? Thanks.
