### ISSUE TITLE
[jquery] Tests failing on master

### ISSUE THREAD

**Issue by leonard-thieu** [DefinitelyTyped/DefinitelyTyped#29818]
@andy-ms @RyanCavanaugh 

Tests are now failing on `master` for `@types/jquery`.

These issues appear to be related to TypeScript 3.2.0-dev.20181017.

[Detailed log](https://github.com/DefinitelyTyped/DefinitelyTyped/files/2488149/log.txt)

They were previously passing as of the last PR (https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/442400448?utm_source=github_status&utm_medium=notification).

---

Is there any way to _not_ test against `typescript@next` when testing locally? ~~I believe these errors might be masking other errors.~~ Actually, it seems like dtslint is not honoring any other rules except for `expect`.

**Comment by andy-ms** [comment]
Microsoft/TypeScript#27949
