### ISSUE TITLE
[react]: defaultProps doesn't work with function component - LibraryManagedAttributes

### ISSUE THREAD

**Issue by Hotell** [DefinitelyTyped/DefinitelyTyped#29816]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

  - Authors: @ferdaber @johnnyreilly @sandersn @RyanCavanaugh @tkrotoff

**Dependencies:**

```
"typescript": "3.1.3"
"@types/react": "16.4.18",
"@types/react-dom": "16.0.9",
```
**Code Sample:**

```tsx
type Props = {
  onClick: (ev: import('react').MouseEvent<HTMLElement>) => void
  children: import('react').ReactChild
} & typeof defaultProps

const defaultProps = { color: 'red' }

const Button = ({ onClick: handleClick, color, children }: Props) => (
  <button style={{ color }} onClick={handleClick}>
    {children}
  </button>
)
Button.defaultProps = defaultProps

const handleClick = () => console.log('clicked')
const color = 'red'

export const Example = () => (
  <>
    <Button onClick={handleClick}>Click me</Button>
  </>
)
```

**Current Behaviour:**

`<Button onClick={handleClick}>Click me</Button>` will get compile error

```
 Property 'color' is missing in type '{ children: string; onClick: () => void; }'.
```

Following code works with class component as expected:

```tsx
class Button extends Component<Props> {
  static readonly defaultProps = defaultProps
  render() {
    const { onClick: handleClick, color, children } = this.props

    return (
      <button style={{ color }} onClick={handleClick}>
        {children}
      </button>
    )
  }
}
```
![image](https://user-images.githubusercontent.com/1223799/47094954-7fd72400-d22c-11e8-94f0-07f5a258fc93.png)

**Expected Behaviour:**

Make default props work for both class and function components

**Comment by ferdaber** [comment]
Interesting, I had thought that TS 3.1 allows static properties to be picked up by the typechecker, to prevent exactly this bug?

What's the result of this type check:
```ts
function foo() {}
foo.defaultProps = {}

type DefaultPropsOfFoo = typeof foo extends { defaultProps: infer D } ? D : never
```

**Comment by Hotell** [comment]
> What's the result of this type check:
![image](https://user-images.githubusercontent.com/1223799/47097093-f0803f80-d230-11e8-928d-696c5d5be00f.png)

**Comment by Hotell** [comment]
related -> https://github.com/Microsoft/TypeScript/issues/27425 

so it's gonna be fixed in 3.2 but before that a whole react types needs to be revamped to be compatible with latest

**Comment by Hotell** [comment]
fixed in 3.2 and react types 16.7.x

**Comment by panjiesw** [comment]
@Hotell Is the fix available in `3.2.0-rc`? Tried it with `@types/react` version `16.7.6`, and it's still shows `missing in type` error even though it's in defaultProps of an `SFC`.

**Comment by Hotell** [comment]
@panjiesw 

> s the fix available in 3.2.0-rc?

Yup

![image](https://user-images.githubusercontent.com/1223799/48767016-a9ceab00-ecf0-11e8-96c4-98db5c02fc50.png)

![image](https://user-images.githubusercontent.com/1223799/48767039-bb17b780-ecf0-11e8-9a71-baae4dd88640.png)

make sure your editor consumes proper TS version 

![image](https://user-images.githubusercontent.com/1223799/48766994-9a4f6200-ecf0-11e8-8b3b-3cc1a83c8b9c.png)

**Comment by panjiesw** [comment]
@Hotell 

Do we have to declare the `defaultProps` like yours? This is how I used to declare it, and TS still complains

![2018-11-20-174904_3840x1080_scrot](https://user-images.githubusercontent.com/1451848/48769029-31b2b600-eced-11e8-9a5d-40eb54524372.png)

![2018-11-20-174924_3840x1080_scrot](https://user-images.githubusercontent.com/1451848/48769043-3a0af100-eced-11e8-87da-c58033dce78a.png)

VSCode is properly configured

![2018-11-20-174937_3840x1080_scrot](https://user-images.githubusercontent.com/1451848/48769048-3d9e7800-eced-11e8-9495-a8afb2752880.png)

**Comment by Hotell** [comment]
Works for me both ways. 

If in doubt restart tsserver or even better execute tsc from terminal ( `yarn tsc` ):

![image](https://user-images.githubusercontent.com/1223799/48769964-f8cc0e80-ecf7-11e8-8dba-b868bb5ffb31.png)


I highly recommend using my pattern:
- define defaultProps as constant and infer type from it
- explicitly define children

To learn more check: https://medium.com/@martin_hotell/10-typescript-pro-tips-patterns-with-or-without-react-5799488d6680

>  but I prefer using SFC

SFC is dead. You should use `FunctionalComponent` which mitigates usage of generics ( and also introduces unnecessary type "churn" for newbies ) 👀

![image](https://user-images.githubusercontent.com/1223799/48771873-937b1c00-ecfd-11e8-83aa-17becb4b7b73.png)

**Comment by panjiesw** [comment]
Yup just realized that SFC is deprecated. I'll use your pattern if it's the only way to make it works with defaultProps of FunctionComponent, and it also has valid points. Thanks for your article btw!

I put my repro here https://github.com/panjiesw/react-ts-32 in case you want to try it. I still can't get it to work with `FunctionComponent<Props>` pattern, even running `npx tsc` gives the same error.
