### ISSUE TITLE
Declare optional parameter for executeSync method

### ISSUE THREAD

**Issue by LsKoder** [DefinitelyTyped/DefinitelyTyped#29844]
For package **@types/ibm_db**:

Method signature:
`executeSync(params: any[]): ODBCResult;`
should be changed to:
`executeSync(params?: any[]): ODBCResult;`

As documented. It is an optional parameter

**Comment by SimonSchick** [comment]
Without the package name, no-one will be able to help you.

**Comment by LsKoder** [comment]
> 
> 
> Without the package name, no-one will be able to help you.

I added it to description. Thanks
