### ISSUE TITLE
[@types/big.js] TypeError: Cannot read property 'RoundUp' of undefined

### ISSUE THREAD

**Issue by itslenny** [DefinitelyTyped/DefinitelyTyped#29864]
If you know how to fix the issue, make a pull request instead.

- [ x ] I tried using the `@types/xxxx` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....
@nycdotnet @googol 

I'm trying to use big.js, but I'm getting type errors on the const enums. I'm not sure if this is something that can be fixed through some sort of tsconfig change or if it's a genuine bug in the typing. Any guidance would be appreciated.

The simple code...

```
import { Big, RoundingMode } from 'big.js';

Big(1).round(0, RoundingMode.RoundUp);
```

Results in: `TypeError: Cannot read property 'RoundUp' of undefined`.

I'm running the app through ts-node (not compiled with tsc) when this occurs which I'd think is a totally normal use case at this point.

I think if these enums were changed to non-const so they'd work fine at runtime. However, I have other const enums in my code that work without issue so it seems to be specific to this package.

**Comment by bobvandevijver** [comment]
I haven't found a way to solve it (I'm using Babel), did you? For babel, it looks like this issue is relevant: 
https://github.com/babel/babel/issues/8741.

**Comment by ndresx** [comment]
I just stumbled upon the same issue until I decided to repro this in a minimal sandbox https://codesandbox.io/s/magical-frog-qgxi9?file=/src/index.ts:57-60, with the same result, and unfortunately, without a fix yet.

**Comment by MikeMcl** [comment]
The `RoundingMode` enum in the big.js type definitions works just fine, so this is likely an issue with your project configuration.

Here is a zip file containing a minimal test case.

[ts_test.zip](https://github.com/DefinitelyTyped/DefinitelyTyped/files/5758824/ts_test.zip)

Just run `tsc test.ts` and then `node test.js`.

```js
import { Big, RoundingMode } from "big.js";
let r = Big(1.67).round(0, RoundingMode.RoundUp);
console.log(r.toString());    // '2'
```

**Comment by Semigradsky** [comment]
@itslenny  Static rounding mode constants were added in v6.1.0 so this should no longer be a issue.

**Comment by bobvandevijver** [comment]
@Semigradsky Actually, the typings must be updated before the new constants can be used. Luckily, I already submitted one 😄 See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52610!
