### ISSUE TITLE
mongodb: connect() deprecated?

### ISSUE THREAD

**Issue by liuxh0** [DefinitelyTyped/DefinitelyTyped#29903]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0e95a07e460e8b2223949a53fdcb5395b0bcda13/types/mongodb/index.d.ts#L47-L52

Definition file says the connect() method is deprecated, but I didn't find any information about deprecation on that link.

![image](https://user-images.githubusercontent.com/15948574/47253608-92807180-d455-11e8-988b-83cdb047f5ca.png)

So is that deprecated or not???

**Comment by erikc5000** [comment]
I'm pretty sure the definition file is wrong.  I corrected this as part of a pending pull request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30890.
