### ISSUE TITLE
MongoDB $pull won't work for nested interface types.

### ISSUE THREAD

**Issue by j** [DefinitelyTyped/DefinitelyTyped#29911]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mongodb` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT @daprahamian @andy-ms @bitjson @dante-101 @mcortesi @EnricoPicci @AJCStriker @julien-c @daprahamian @denys-bushulyak @BastienAr @sindbach @geraldinelemeur @jishi @various89 @angela-1 @lirbank @hector7 @floric

If you do not mention the authors the issue will be ignored.

```typescript
interface BundleDocument {
  _id: ObjectId;
  items: BundleItemDocument[];
}

interface BundleItemDocument {
  product: string;
  sku: string;
  price: number;
}

const collection = db.collection<BundleDocument>('bundles');

await collection.updateOne({ _id }, {
  $pull: {
    items: {
      product: "..."
    }
  }
});
```

The above shows incompabitle index signatures.  I believe it's when items are nested?

I'm trying to remove an "item" where "product" = "..." and @types/mongodb won't let me.

**Comment by floric** [comment]
Hey, I had a look. You are right. It seems as if the types for the Conditions currently don't work for nested paths. I'm currently unsure, but shouldn't `items.product` as a flat key work in your case?

**Comment by j** [comment]
@floric yeah i tried "items.product" first and it yelled at me too.  :(

**Comment by floric** [comment]
Just created a small PR for as a temporary fix. But the `any` types should get better. But I'm currently lacking experience about all possible values and how to improve the nested types.

**Comment by rbuckton** [comment]
The problem is that `product` is not a property of `BundleItemDocument[]`, since it is an array. This could be addressed with conditional types [introduced in TypeScript 2.8](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#conditional-types).

**Comment by floric** [comment]
Thanks. I will have a look tomorrow! :)

**Comment by erikhofer** [comment]
`$pull` also doesn't work with plain string arrays like this: https://stackoverflow.com/a/32002845/5519485

**Comment by fchu** [comment]
I hit the same issue. Not too familiar with TS nor mongodb (...), but it seems that the $pull operator is expecting a full TSchema object (BundleItemDocument), while per the mongo docs, some partial should be accepted too

**Comment by j** [comment]
@rbuckton https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40056
