### ISSUE TITLE
react-native: Cannot find name 'global'.

### ISSUE THREAD

**Issue by fantasy525** [DefinitelyTyped/DefinitelyTyped#29915]
@types/react-native@0.57.7,tyescript:3.1.3
`
global.time=33
`
and  The TSC compiler prompt cannot find name global

**Comment by Esemesek** [comment]
It isn't a good practice to use this `global` keyword, but it exists and should be present in `react-native` context.

**Comment by fantasy525** [comment]
yeah thanks you , i know,but Sometimes we do need it,
