### ISSUE TITLE
@types/chai No types for Chai's internal api (parameters of chai.use have type any)

### ISSUE THREAD

**Issue by mpsijm** [DefinitelyTyped/DefinitelyTyped#29922]
- [x] I tried using the `@types/chai` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jedmao @Bartvds @AGBrown @olivr70 @mwistrand @JoshuaKGoldberg @shaunluttin @Naktibalda @micksatana @ErikSchierboom

`Chai.ChaiStatic.use` is typed as `use(fn: (chai: any, utils: any) => void): ChaiStatic`.

The parameters `chai` and `utils` do have types, but they are part of the "private" API of chai, see for example `chai.Assertion` in [chaijs/chai](https://github.com/chaijs/chai/blob/master/lib/chai/assertion.js#L59). I'm trying to extend Chai, which means I would like to have the type of (amongst others) `chai.Assertion`.

Is there a reason why the internal API is not typed? This would be useful for Chai plugin developers.

**Comment by 9999years** [comment]
Working on a PR to support this.

**Comment by vaarijshah** [comment]
Getting 
```
node_modules/@types/sinon-chai/index.d.ts:87:31 - error TS2694: Namespace 'Chai' has no exported member 'ChaiPlugin'.
87 declare const sinonChai: Chai.ChaiPlugin;
``` 
after using 2.7.36. I think this might be adding some dependency that I don't have. Any help is appreciated.

**Comment by 9999years** [comment]
Try `npm update`? Sounds like the version of `@types/chai` is too old. I can look into it further later, though.
