### ISSUE TITLE
[@types/web3] Add disconnect method to providers

### ISSUE THREAD

**Issue by yxliang01** [DefinitelyTyped/DefinitelyTyped#29929]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [ X I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
 
Authors: 
@simon-jentzsch
@nitzantomer
@zurbo
@yxliang01
@phra
@naddison36
@icaroharry
@linusnorton
@jpeletier
@anneau
@matrushka
@andrevmatos
@Levino
@zlumer
@archangel-irk

If you do not mention the authors the issue will be ignored.

These new methods were added by PR https://github.com/ethereum/web3.js/pull/1881 https://github.com/ethereum/web3.js/pull/2003
Only need to modify https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/web3/providers.d.ts with tests.

**Comment by yxliang01** [comment]
Note that https://github.com/ethereum/web3.js/pull/2003 at the moment.

**Comment by Levino** [comment]
As long as this is not in the docs, we should not consider it stable and as such it should not be included in the DT definitions. See also https://web3js.readthedocs.io/en/1.0/search.html?q=disconnect&check_keywords=yes&area=default

**Comment by Levino** [comment]
As long as this is not in the docs, we should not consider it stable and as such it should not be included in the DT definitions. See also https://web3js.readthedocs.io/en/1.0/search.html?q=disconnect&check_keywords=yes&area=default

**Comment by Levino** [comment]
As long as this is not part of the official docs, we should not type it. Should be considered experimental. See also https://web3js.readthedocs.io/en/1.0/search.html?q=disconnect&check_keywords=yes&area=default I vote for closing this issue and reopen / recreate once the documentation contains information on the disconnect feature.

BTW: Who the f**k approves PRs which extend the API of a library but do not amend the docs to reflect these API extensions?

**Comment by yxliang01** [comment]
@Levino I think your concern is legit. However, I prefer to leave this open as a reminder, instead of closing then we might forget about it.

For the PR approval thing, I can't comment since I'm not in the organization. :joy:

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
