### ISSUE TITLE
[@types/react-native] Cannot find name 'alert'.

### ISSUE THREAD

**Issue by fantasy525** [DefinitelyTyped/DefinitelyTyped#29942]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Esemesek 

my code
```
alert("333")
```
The TSC compiler prompt cannot find name alert,

expect:
compile success

**Comment by Esemesek** [comment]
I think you are looking for [this](https://facebook.github.io/react-native/docs/alert). Global `alert` does not exist in `react-native` context.

**Comment by fantasy525** [comment]
> I think you are looking for [this](https://facebook.github.io/react-native/docs/alert). Global `alert` does not exist in `react-native` context.

yeah, I have found it,thank you!
