### ISSUE TITLE
[@types/nodegit] Incorrect return type for Commit.history()

### ISSUE THREAD

**Issue by gins3000** [DefinitelyTyped/DefinitelyTyped#29969]
- [X] I tried using the `@types/nodegit` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Dolanmiu @tniessen

File: commits.d.ts

`Commit.history()`'s documentation says `Don't forget to call start() on the returned event.` and the return type is `EventEmitter`.

`EventEmitter` does not have a function called `start()`.

**Comment by dolanmiu** [comment]
![image](https://user-images.githubusercontent.com/2917613/47359128-cf51a000-d6c3-11e8-823b-5f9a54d55889.png)

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/nodegit/commit.d.ts#L82

I am not sure what to do about this

**Comment by dolanmiu** [comment]
Maybe extend EventEmitter, and add that method in

**Comment by gins3000** [comment]
Seems like the error is already in their own docs then. Perhaps I'll head over to the nodegit repo and file an issue there.

**Comment by dolanmiu** [comment]
Thanks! :)
