### ISSUE TITLE
how to reslove this error?

### ISSUE THREAD

**Issue by zhangjinghuan** [DefinitelyTyped/DefinitelyTyped#29968]
ERROR  Failed to compile with 1 errors                                                                                                           17:55:35

 error  in ./node_modules/requirejs/bin/r.js

Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
> #!/usr/bin/env node
| /**
|  * @license r.js 2.3.6 Copyright jQuery Foundation and other contributors.

 @ ./node_modules/cesium/index.js 5:16-36

**Comment by zhangjinghuan** [comment]
i was "npm install --save-dev @types/node"，and then ,in 'vue' + 'vue-lic3' project,
when i used  "import {Viewer,buildModuleUrl} from 'cesium'",my project report errors!

**Comment by Icemap** [comment]
@zhangjinghuan 
I got a same question In React + TS + Cesium.
But I can't solve it yet.

**Comment by andig89** [comment]
You can write `import 'shebang-loader!requirejs';` (npm install shebang-loader) but
```
requirejsVars.requirejs(['example'],
    function(example) {

    }
)
```
return undefined :/. It looks like in 
```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else {
		var a = factory();
		for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
	}
})(window, function() {
```
exports and module are not undefined and everything works differently :/.
So... i use
```
new WebpackShellPlugin({
    onBuildStart: ['sh onBuildStart.sh']
})
```
 write shell script onBuildStart.sh
```
#!/bin/sh
cp node_modules/requirejs/bin/r.js src/js/requirejs.js
sed 1d src/js/requirejs.js > src/js/requirejs.js.tmp && mv src/js/requirejs.js.tmp src/js/requirejs.js
```
and add in webpack.config.js
```
new CopyWebpackPlugin([{
    from: 'src/js/requirejs.js',
    to: 'js/requirejs.js',
}])
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
