### ISSUE TITLE
babel__core breaks with latest @babel/parser

### ISSUE THREAD

**Issue by spalger** [DefinitelyTyped/DefinitelyTyped#29963]
- [x] I tried using the `@types/babel__core` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- Authors: @yortus @marvinhagemeister @mgroenhoff

It looks like since v7.1.0 `@babel/parser` ships with TypeScript types, which override the types from `@types/babel__parser` and are slightly different in several ways. I'm not sure how libraries that start shipping types is normally handled in DT, but the easiest option I've found is to replace `from "@babel/parser"` with `from "babel__parser"` to force using the `@types/babel__parser` types, though I'm pretty sure this isn't a good idea. Any idea what I should do to get this fixed?

Happy to submit a PR.

**Comment by mgroenhoff** [comment]
There is already a PR ready and waiting #29403 but it is currently blocked on #27729

**Comment by spalger** [comment]
Fantastic, looking forward to both getting fixed!
