### ISSUE TITLE
Types for Google Drive

### ISSUE THREAD

**Issue by lostmsu** [DefinitelyTyped/DefinitelyTyped#300]
https://developers.google.com/drive/

**Comment by slawiko** [comment]
I suppose we can close this issue

**Comment by baxtersa** [comment]
I just implemented types for the google drive v2 API in PR #17165 , this can probably be closed

**Comment by grant** [comment]
This issue is being tracked here: https://github.com/google/google-api-nodejs-client/issues/503

**Comment by ltlombardi** [comment]
This should be closed

**Comment by grant** [comment]
Yes, please close this issue.

**Comment by grant** [comment]
@sandersn Please close this fixed issue.
