### ISSUE TITLE
[@types/react] Add properties Suspense & lazy

### ISSUE THREAD

**Issue by eljenso** [DefinitelyTyped/DefinitelyTyped#30031]
[React v.16.6 has been released](https://reactjs.org/blog/2018/10/23/react-v-16-6.html) and it brings [lazy](https://reactjs.org/docs/code-splitting.html#reactlazy) and [Suspense](https://reactjs.org/docs/code-splitting.html#suspense).

Running `tsc --build tsconfig.json` throws:
```   
src/components/DynamicComponent/index.tsx:28:24 - error TS2339: Property 'lazy' does not exist on type 'typeof React'.                                                      

28       component: React.lazy(() => import(this.state.url)),
                          ~~~~

src/components/DynamicComponent/index.tsx:46:14 - error TS2339: Property 'Suspense' does not exist on type 'typeof React'.

46       <React.Suspense fallback={<div>Loading...</div>}>
                ~~~~~~~~

src/components/DynamicComponent/index.tsx:55:15 - error TS2339: Property 'Suspense' does not exist on type 'typeof React'.

55       </React.Suspense>
                 ~~~~~~~~
```

@johnnyreilly @bbenezech @pzavolinsky

**Comment by dbchristopher** [comment]
After being blocked by this, I took the less-than-ideal approach of simply adding `// @ts-ignore` before the React import

```js
// @ts-ignore
import React, { Suspense, lazy } from 'react';
```

As per https://twitter.com/martin_hotell/status/1055381631094190080, it sounds like it will be a while before we get official types for React 16.6. I'd prefer to have access to `lazy` and `Suspense` until then.

**Comment by FredyC** [comment]
Had no opportunity to test this out yet, but I am wondering, is lazy loaded component properly inferred for prop types?

**Comment by Kovensky** [comment]
It does work locally 😇

![image](https://user-images.githubusercontent.com/73085/47561950-db559000-d957-11e8-9252-6d79ced42ffd.png)

**Comment by eljenso** [comment]
@dbchristopher This did not work for me so I used another workaround:
```ts
import React from "react";
const Suspense = (React as any).Suspense;
const lazy = (React as any).lazy;
```

**Comment by arkon** [comment]
This was added in #30054.

**Comment by eljenso** [comment]
@arkon You're right, will close this issue.
