### ISSUE TITLE
[@types/styled-components] v4's as prop is missing in .attrs and templates

### ISSUE THREAD

**Issue by nickmccurdy** [DefinitelyTyped/DefinitelyTyped#30042]
- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @lavoaster

The following component appears to work fine with typechecking disabled, with `<Heading />` and `<Heading as="h2" />` displaying text at two different sizes and colors. However, there is a type error because `as` appears to be missing from the argument type of Text.

```ts
export const Heading = styled(Text).attrs({ as: 'h1' })`
  color: ${props => props.as === 'h1' && props.theme.headline};
  font-size: ${props => scale(props.as === 'h1' ? 2 : 1)};
`;
```

Additionally, If I remove `.attrs({ as: 'h1' })` and set `defaultProps` manually, I get `Property 'as' does not exist on type 'ThemedStyledProps<...>'` where I try to use `props.as` in the second and third lines.

**Comment by Igorbek** [comment]
A smaller repro:

```ts
const AttrsWithOnlyNewProps = styled.h2.attrs({ as: 'h1' })` `;
```

**Comment by nickmccurdy** [comment]
Thanks for the quick fix!

My type errors in `.attrs` and template function props are fixed, but now I get errors about missing props when I don't pass `as`. Is this intentional? It seems like an inference issue.

```ts
export const Heading = styled(Text).attrs({ as: 'h1' })`
  color: ${props => props.as === 'h1' && props.theme.headline};
  font-size: ${props => scale(props.as === 'h1' ? 2 : 1)};
`;

<Heading>Heading</Heading>
```
```
[ts]
Type '{ children: string; }' is not assignable to type 'Readonly<ThemedOuterStyledProps<DiffBetween<{ as: string; }, DetailedHTMLProps<HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>>, Record<"name" | "actionPanelBackground" | "actionPanelBorder" | "background" | "controlBackground" | "controlBorder" | "headline" | "link" | "linkHover" | "panelBackground" | "primary" | "primaryDark" | "primaryDarker" | "text", string>>>'.
  Property 'as' is missing in type '{ children: string; }'.
```

**Comment by Igorbek** [comment]
@nickmccurdy it looks like a separate issue. The change I made did not have effect on this. I'll look into it.

**Comment by nickmccurdy** [comment]
It seems like the error is only caused when props are inferred, if I give the template a generic props attribute everything works fine.

**Comment by RajeshPandey057** [comment]
You can define a type with "as" as optional argument and use something like this, it will not give error,
`type HeaderProps = {
as? : string,
}
export const Heading = styled(Text).attrs<HeaderProps >(({as})=>console.log(as))<HeaderProps >`
  color: ${props => props.as === 'h1' && props.theme.headline};
  font-size: ${props => scale(props.as === 'h1' ? 2 : 1)};
`;`
