### ISSUE TITLE
[@types/sequelize] `findById` is deprecated, `findByPk` is unavailable

### ISSUE THREAD

**Issue by bteixeira** [DefinitelyTyped/DefinitelyTyped#30056]
- [X] I tried using the `@types/sequelize` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @samuelneff @codeanimal @drinchev @babolivier @kukoo1 @oktapodia @morpheusxaut @TitaneBoy @zjy01 @nidzov @Raigen @todd @nrschultz @thomas-b

According to the API reference, `Model.findById` no longer exists and `Model.findByPk` is the right way to fetch a record by id/primary key.

If I use `findByPk` typescript fails to compile.
If I use `findById` I get a deprecation warning from Sequelize.

Not sure if this is related to the new API introduced by Sequelize 4

**Comment by rationalthinker1** [comment]
So is there anything we can do about it?

**Comment by villasv** [comment]
findByPk is already on `index.d.ts`, so maybe this should be closed?
