### ISSUE TITLE
Node v11 proposal

### ISSUE THREAD

**Issue by SimonSchick** [DefinitelyTyped/DefinitelyTyped#30072]
Violating the PR template for once since I'm

With node v11 been released I was hoping we could perhaps make a cut and see if we can improve the node typing structure a little bit and cleanup various hacks by bumping up minimum TS versions.

I'm looking for some feedback on: https://github.com/SimonSchick/DefinitelyTyped/commit/bb7d90c9b3f14be390ef47d51792be9d0ee09dde
This splits each module into its own file, some hacks are still needed for EventEmitter, cluster and Console) to work correctly tho.

@andy-ms, @rbuckton any thoughts before I ping the rest of the contributors, is mass updating dependent packages feasible or too much of a breaking change?

**Comment by rbuckton** [comment]
We [recently added support](www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#version-selection-with-typesversions) for `"typesVersions"` to TypeScript 3.1 to allow us to more cleanly support newer type features in TS 3.1 and later. Support for this should be available soon on DefinitelyTyped.

**Comment by andy-ms** [comment]
@SimonSchick Two potential pitfalls:
* The non-`index` files may simply not be included in the compilation. Use `tsc --listFiles` to check.
* `declare module` has a different meaning depending on whether it appears in global scope or inside of a module. In global scope it declares a module; inside a module it augments a module.

**Comment by Flarna** [comment]
@rbuckton I don't get how the typesVersions feature should be introduced here.

If I understand this correct it's possible to create more variants of definitions for a module which are selected depending on the typescript version in use and as a result we can create a variant which uses 3.1 features.

But doesn't this imply that we have to maintain two variants? 
I fear that after the first refactoring mentioned above we have two separate files which will be never get synced as a simple copy paste will not work anymore.

And how is the publishing setup done for this in this repo?

**Comment by andy-ms** [comment]
> And how is the publishing setup done for this in this repo?

We will simply publish both the root and `ts3.1` directories in the same package. TypeScript's module resolution does the work to choose which is used, not NPM.

**Comment by SimonSchick** [comment]
@andy-ms devils advocate: Have you considered making the nodejs typings a lib and ship it with TypeScript, or even ship it with node somehow? The typings are so big an integral to the types ecosystem that it would probably sensible to separate them.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
