### ISSUE TITLE
react-router path should support string | string[]

### ISSUE THREAD

**Issue by rachitpsolanki** [DefinitelyTyped/DefinitelyTyped#30158]
export interface RouteProps {
  location?: H.Location;
  component?: React.ComponentType<RouteComponentProps<any>> | React.ComponentType<any>;
  render?: ((props: RouteComponentProps<any>) => React.ReactNode);
  children?: ((props: RouteComponentProps<any>) => React.ReactNode) | React.ReactNode;
  **path?: string[] | string ;**
  exact?: boolean;
  sensitive?: boolean;
  strict?: boolean;
}

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

@sergey-buturlakin @mrk21  @vasek17

**Comment by jtreminio** [comment]
v 4.4.0 was recently released, has what you need: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-router/index.d.ts#L80

**Comment by rachitpsolanki** [comment]
> v 4.4.0 was recently released, has what you need: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-router/index.d.ts#L80

@jtreminio 
Thank you!!

**Comment by jtreminio** [comment]
proptypes still complains, though. You can use the following to suppress the console warning: https://github.com/ReactTraining/react-router/issues/5866#issuecomment-385207863

**Comment by mrichmond** [comment]
why not just fix the propTypes? 

Here's my slightly cleaner but still very "hacky" solution:

```JavaScript
import { Route } from 'react-router-dom';
import { oneOfType, array, string } from 'prop-types';
Route.propTypes.path = oneOfType([array, string]);
```
