### ISSUE TITLE
Recharts Area is missing data prop

### ISSUE THREAD

**Issue by mastertinner** [DefinitelyTyped/DefinitelyTyped#30181]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/recharts` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @mthmulders, @rapmue, @royxue, @ZheyangSong, @richbai90, @caspeco-dan, @pkeuter, @jrsaunde, @paulmelnikow, @crusectrl, @apalugniok

The `Area` component's typings are missing the `data` prop.

**Comment by CruseCtrl** [comment]
You could raise a pull request to add in the `data` prop

**Comment by mastertinner** [comment]
Sorry, I had something misconfigured. This is actually not a bug. My bad.
