### ISSUE TITLE
README needs revision regarding creating new typings for existing package I don't own

### ISSUE THREAD

**Issue by kylegoetz** [DefinitelyTyped/DefinitelyTyped#30238]
The readme says to create a folder with the same name as the package I want to create typings for (`prompt`). Then it says if I have NPM >=5.2 (I have 5.6) to run the command `npx dts-gen --dt --name prompt --template module`. It does not say which folder to run it from. I created a `@types` path and then `prompt` within it and then from the `@types/path` I ran the command.

Response was an error: 

    npx: installed 59 in 8.147s
    Unexpected crash! Please log a bug with the commandline you specified.
    ENOENT: no such file or directory, mkdir 'types/prompt'

So then I went to the parent dir and renamed @types to types and tried again from the new `types` dir.

    npx: installed 59 in 4.083s
    Unexpected crash! Please log a bug with the commandline you specified.
    ENOENT: no such file or directory, mkdir 'types/prompt'

then I went to the parent of `types` and tried again:

    npx: installed 59 in 3.949s
    Directory types/prompt already exists and -overwrite was not specified; exiting.

So I tried the same command with `-overwrite` added:

    npx: installed 59 in 3.915s
    0.5.7

Looks like it worked. But then I look in my pwd and there's nothing added. So the program didn't actually do anything as far as I can tell. It definitely didn't generate the d.ts file or tsconfig or tslint files.

Inside `types` itself, nothing. Inside `types/prompt` nothing. If I `rm -rf types` and run the command, I get the same success-apparent response, but no `types` path is even created.

So the README needs to be updated with better instructions for this. I don't know how to fix it since I don't know how to get it working, so I can't make a PR.

**Comment by ntnbrtnkv** [comment]
Had same problem
I was able to generate files by those steps:
1. `mkdir types/my-package-name`
2. `npx dts-gen --dt --name my-package-name --template module --overwrite`

Notice that _overwrite_ option has 2 dashes, not 1
