### ISSUE TITLE
types/node: make util.inspect.custom a 'unique symbol', not only a 'symbol'?

### ISSUE THREAD

**Issue by emmanueltouzery** [DefinitelyTyped/DefinitelyTyped#30241]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Microsoft @DefinitelyTyped @jkomyno @a-tarasyuk @alvis @r3nya @BrunoScheufler @smac89 @tellnes @DeividasBakanas @eyqs @Flarna @Hannes-Magnusson-CK @KSXGitHub @hoo29 @kjin @ajafff @isLishude @mwiktorczyk @matthieusieben @mohsen1 @n-e @octo-sniffle @parambirs @eps1lon @SimonSchick @ThomasdenH @WilcoBakker @wwwy3y3 @ZaneHannanAU

In node, if we want custom rendering for custom objects in the REPL and in console.log, we used to have to override `inspect()`. In recent versions of node, we must instead override `[util.inspect.custom]`, which is a symbol. See the documentation:
https://nodejs.org/api/util.html#util_util_inspect_custom
[update: [better link](https://nodejs.org/api/util.html#util_custom_inspection_functions_on_objects)]

The implementation of `custom` was changed recently as well:
https://github.com/nodejs/node/commit/dadd6e16888baac8fd110432b81f3fd1237be3e1#diff-a43208147d795be6dd3517c53226e37dL402

I think that in the type definitions, the type of `custom` should not be `symbol` as it is now, but `unique symbol`. The reason being that we can't define class members with `[util.inspect.custom]` as it is, as the compiler says:

    error TS1169: A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.

My current workaround is to say...

```typescript
import * as util from 'util';

// @ts-ignore
export const inspect: unique symbol = util.inspect.custom;
```

and later `[inspect](): string`. Even casting to `any` is not enough, I need `@ts-ignore`.

PS: I tried to make a PR and failed. It was https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30237

**Comment by SimonSchick** [comment]
Not going to work given the fact that the node typings have to support a very old version of TS.

**Comment by emmanueltouzery** [comment]
it's really not rare that I wish that there was some #ifdef mechanism in typescript, with version constraints :-(

It's quite painful as it is now. One would wish to define the constant oneself, ignoring the one exported by node, but as you can see in the commit I pasted, they've been changing it through time.. Using the constant is the best way to be compatible with multiple node versions. Well, worst-case I guess the `@ts-ignore` solution works, but...

**Comment by ZaneHannanAU** [comment]
Ugh…
At this point I think we should deprecate most old/unused/otherwise broken versions…

**Comment by TheAkio** [comment]
This seems to be fixed with newer node typings. I'm using @types/node with version 10.14.5 and I don't get this error anymore, but I got the error with some 10.12.X typings.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
