### ISSUE TITLE
[@types/request] Error in tsc output

### ISSUE THREAD

**Issue by wolfy1339** [DefinitelyTyped/DefinitelyTyped#30270]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @soywiz @bonnici @Bartvds @joeskeen @ccurrens @lookfirst @mastermatt @josecolella

I get an error when using the request definitions:
```
node_modules/@types/request/index.d.ts:76:15 - error TS2430: Interface 'DefaultUriUrlRequestApi<TRequest, TOptions, TUriUrlOptions>' incorrectly extends interface 'RequestAPI<TRequest, TOptions, TUriUrlOptions>'.
  Types of property 'defaults' are incompatible.
    Type '(options: TOptions) => DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>' is not assignable to type '{ (options: TOptions): RequestAPI<TRequest, TOptions, RequiredUriUrl>; (options: (UriOptions & TOptions) | (UrlOptions & TOptions)): DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>; }'.
      Type 'DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>' is not assignable to type 'RequestAPI<TRequest, TOptions, RequiredUriUrl>'.
        Types of property 'post' are incompatible.
          Type '{ (uri: string, options?: TOptions | undefined, callback?: RequestCallback | undefined): TRequest; (uri: string, callback?: RequestCallback | undefined): TRequest; (options: (UriOptions & TOptions) | (UrlOptions & TOptions) | (TOptions & {}), callback?: RequestCallback | undefined): TRequest; (callback?: RequestCall...' is not assignable to type '{ (uri: string, options?: TOptions | undefined, callback?: RequestCallback | undefined): TRequest; (uri: string, callback?: RequestCallback | undefined): TRequest; (options: (UriOptions & TOptions) | (UrlOptions & TOptions), callback?: RequestCallback | undefined): TRequest; (options:
(UriOptions & TOptions) | (UrlO...'.
            Types of parameters 'uri' and 'options' are incompatible.
              Type '(UriOptions & TOptions) | (UrlOptions & TOptions)' is not assignable to type 'string'.
                Type 'UriOptions & TOptions' is not assignable to type 'string'.

76     interface DefaultUriUrlRequestApi<TRequest extends Request,
                 ~~~~~~~~~~~~~~~~~~~~~~~
```
 **I don't use `request` directly, I use `request-promise-native`**

Also going to include the authors of `request-promise-native`: @gustavohenke @mastermatt 
It's also worth noting that the dependecy of `@types/request`  in `@types/request-promise-native` is not up to date

**Comment by mastermatt** [comment]
@wolfy1339 can you provide a gist that replicates this issue?
I have `request-promise-native` in several production apps using `strict: true` without issue.

**Comment by wolfy1339** [comment]
Unfortunately there's no code attached to this, only including the typings makes the error appear.
I've created a simple TS module and it has the same problem. https://gist.github.com/wolfy1339/57853f693763f3923ae97d46a6557464
I have used this command to compile it
``` $ tsc test.ts --lib es2018 --target esnext -m commonjs```

**Comment by mastermatt** [comment]
I can't reproduce this. Here are my steps from a clean working dir
```bash
~/src: mkdir test
~/src: cd test
~/src/test: npm --version
6.4.1
~/src/test: npm init -y
> Wrote to ~/src/test/package.json:

{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


~/src/test: npm i @types/request-promise-native
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ @types/request-promise-native@1.0.15
added 6 packages from 47 contributors and audited 7 packages in 0.95s
found 0 vulnerabilities

~/src/test: touch index.ts
~/src/test: vim index.ts ## paste in contents of https://gist.github.com/wolfy1339/57853f693763f3923ae97d46a6557464

~/src/test: tsc index.ts --lib es2018 --target esnext -m commonjs
~/src/test: echo $?
> 0
```

macos 10.13.6

**Comment by wolfy1339** [comment]
Somehow I have had broken dependencies. I'm not exactly sure how that had happened, but flushing my `node_modules` folder, reinstalling my deps, fixed the problem
