### ISSUE TITLE
@types/minio missing error event type for ListObjectsV2 stream.

### ISSUE THREAD

**Issue by christopher-wong** [DefinitelyTyped/DefinitelyTyped#30291]
[listObjectsV2()](https://docs.minio.io/docs/javascript-client-api-reference#listObjectsV2) dispatches 2 event types to the response stream, an error event and a data event.

```
var stream = minioClient.listObjectsV2('mybucket','', true)
stream.on('data', function(obj) { console.log(obj) } )
stream.on('error', function(err) { console.log(err) } )
```

The error type is missing from the [type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d65c4ab6663dab4bb98b2c1041302c109e9e5e94/types/minio/index.d.ts#L62-L64).

Likely needs 

```
export interface BucketStream<T> extends Stream {
  on(event: 'error', ....
}
```

- [x] I tried using the `@types/minio` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @OutdatedVersion

**Comment by OutdatedVersion** [comment]
Hey @christopher-wong, 

The missing `error` event has been addressed with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30316. (:

**Comment by christopher-wong** [comment]
🎉🎉🎉 thanks!

--
Christopher Wong
B.S. Candidate in Engineering and Computer Science
Northeastern University 2019
(610) 716-1749
christopherwong.co

________________________________

**Comment by christopher-wong** [comment]
@OutdatedVersion it looks like the minio.listObjectsV2() stream also dispatches an "end" event.

```
let data = [];
stream.on('data', (obj) => {
    data.push(obj)
})
stream.on('end', () => { console.log(data)})
```

It's documented for https://docs.minio.io/docs/javascript-client-api-reference.html#listIncompleteUploads but not listObjectsV2, but it works.

**Comment by nlfiedler** [comment]
listObjects() is also missing an 'end', otherwise you can never know when it is done.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
