### ISSUE TITLE
react-native-modalbox 'screen' variable

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#30296]
@iRoachie @Hotell @pelotom
In `react-native-modalbox-tests.ts` there is a `screen` variable that is undefined. Did this come from `react-native` at some point? If so, should it be added back, or should `react-native-modalbox-tests` be updated to not use it?

**Comment by pelotom** [comment]
@andy-ms I don't know, I don't think I've ever had anything to do with this project or its types.

**Comment by iRoachie** [comment]
@andy-ms Can close this issue. Sent the PR to fix.
