### ISSUE TITLE
.d.ts files using future TypeScript language features

### ISSUE THREAD

**Issue by RyanCavanaugh** [DefinitelyTyped/DefinitelyTyped#3031]
The TypeScript language is picking up two new features that will be really big for .d.ts authors: union types (`n: number|string`) and type aliases (`type JQueryable = string|JQuery|HTMLElement`).

How will DefinitelyTyped manage this? It's probably unrealistic to assume everyone is using the bleeding-edge compiler, but people will want to be using these ASAP when they become broadly available. Is it time to branch the entire repo into a "1.0 language" branch and a "Latest release language" branch? Just throwing out ideas.

**Comment by vvakame** [comment]
start 1.4.0 support. https://github.com/borisyankov/DefinitelyTyped/pull/3466

**Comment by johnnyreilly** [comment]
Exciting!

**Comment by jakebailey** [comment]
Doing some issue cleanup; I think this is all well settled.
