### ISSUE TITLE
webdriverio $ conflict with jquery $

### ISSUE THREAD

**Issue by NiGhTTraX** [DefinitelyTyped/DefinitelyTyped#30313]
- [x] I tried using the `@types/webdriverio` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nmalaguti @timbru31 @daveparslow

Running `tsc` (`npm run build`) in https://github.com/NiGhTTraX/react-cosmos-proxy-buffet:

```
node_modules/@types/jquery/misc.d.ts:4990:15 - error TS2451: Cannot redeclare block-scoped variable '$'.

4990 declare const $: JQueryStatic;
                   ~

  node_modules/@types/webdriverio/index.d.ts:1919:18
    1919 declare function $(selector: string): WebdriverIO.Client<WebdriverIO.RawResult<WebdriverIO.Element>> & WebdriverIO.RawResult<WebdriverIO.Element>;
                          ~
    '$' was also declared here.

node_modules/@types/webdriverio/index.d.ts:1919:18 - error TS2451: Cannot redeclare block-scoped variable '$'.

1919 declare function $(selector: string): WebdriverIO.Client<WebdriverIO.RawResult<WebdriverIO.Element>> & WebdriverIO.RawResult<WebdriverIO.Element>;
                      ~

  node_modules/@types/jquery/misc.d.ts:4990:15
    4990 declare const $: JQueryStatic;
                       ~
    '$' was also declared here.

node_modules/@types/webdriverio/index.d.ts:1920:18 - error TS2451: Cannot redeclare block-scoped variable '$'.

1920 declare function $<P>(selector: string): WebdriverIO.Client<P>;
                      ~

  node_modules/@types/jquery/misc.d.ts:4990:15
    4990 declare const $: JQueryStatic;
                       ~
    '$' was also declared here.
```

**Comment by xemlock** [comment]
I dealt with this issue in a rather brute-force way - by calling the following code in my npm `postinstall` script:

```js
const fs = require('fs');
const path = require('path');

const packagePath = path.resolve('node_modules/@types/jquery');
const typedefsPath = `${packagePath}/index.d.ts`;

fs.writeFileSync(
    typedefsPath,
    fs.readFileSync(typedefsPath).toString()
        .replace('declare var \$: JQueryStatic;', '')
        .replace('export = $;', 'export = jQuery;')
);
```

It "fixes" the type definitions by removing `$`, and making `jQuery` a default export instead of `$`.

**Comment by NiGhTTraX** [comment]
Sorry for the ping, but have the authors seen this? @nmalaguti @timbru31 @daveparslow

Since I'm actually not using both jquery and webdriverio at the same time, is there any way to disable the `@types/jquery` package through `tsconfig.json` (I could have a separate config for the test files).

**Comment by daveparslow** [comment]
From a webdriver.io perspective, it is by design as it does have a global $ which is not the same as the jQuery $.

This is a TypeScript question (https://github.com/Microsoft/TypeScript/) about conflicting types, but I can give pointers.  Yes, It is pretty typical to have separate config for test files although you typically might want your test config to extend your base tsconfig for your project and then just exclude jQuery and use ---traceResolution with the TypesScript compile if you are not sure why jQuery is getting included.  For details you can search TypeScript issues such as this one https://github.com/Microsoft/TypeScript/issues/22331

**Comment by uniqueiniquity** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32490
