### ISSUE TITLE
Node.js 10.11 'Console' definition does not meet spec

### ISSUE THREAD

**Issue by leegee** [DefinitelyTyped/DefinitelyTyped#30339]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DefinitelyTyped, @tdreyno jkomyno, @a-tarasyuk, @alvis, @r3nya, @brunoscheufler, @smac89, @tellnes, @DeividasBakanas, @eyqs, @Flarna, @Hannes-Magnusson-CK, @KSXGitHub, @hoo29, @kjin, @ajafff, @islishude, @mwiktorczyk, @matthieusieben, @mohsen1, @n-e, @octo-sniffle, @parambirs, @eps1lon, @SimonSchick, @ThomasdenH, @WilcoBakker, @wwwy3y3, @ZaneHannanAU

`// Type definitions for Node.js 10.11`
`// Project: http://nodejs.org/`

After typing all those author tags, I hope I'm not wrong in thinking that the Node `Console` class ought to have type defintions two forms of constructor, as described on NodeJS.org site[1]:

`Version | Changes
-- | --
v10.0.0 | The Console constructor now supports an options argument, and the colorMode option was introduced.

[1]: https://nodejs.org/api/console.html#console_new_console_stdout_stderr_ignoreerrors

**Comment by Flarna** [comment]
Seems you are right, the changes introduced in NodeJS 8 and 10 have not been added till now.

Feel free to create a PR to improve this.

**Comment by leegee** [comment]
I'll have a go.... ymmv

**Comment by leegee** [comment]
Before a PR, how does this look?

```
    interface ConsoleConstructor {
        prototype: Console;
        new(ConsoleConstructorOptions): Console;
    }

    interface ConsoleConstructorOptions {
        stdoutOrConsoleConstructorOptionsObject: WritableStream | ConsoleConstructorOptionsObject;
        stderr?: WritableStream;
    }

    interface ConsoleConstructorOptionsObject {
        stdout?: WritableStream;
        stderr?: WritableStream;
        ignoreErrors?: boolean;
        colorMode?: boolean | <string;
    }
```
My understanding from the NodeJS docs is that the options object *must* specify one or two writable streams ('with one or two writable stream instances') but I don't know how to  state that in TS, or even if it is possible.

**Comment by Flarna** [comment]
Well to answer this question I had to prepare the changes so I created a PR (#30359).
