### ISSUE TITLE
RsaPrivateKey passphrase is optional

### ISSUE THREAD

**Issue by Maxpain177** [DefinitelyTyped/DefinitelyTyped#30350]
`passphrase` is not required, but optional, according to [offical API docs](https://nodejs.org/api/crypto.html#crypto_sign_sign_privatekey_outputformat)!

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/adc9c3f22047fcfa11ee04d243a8c1519c04771c/types/node/index.d.ts#L6272

**Comment by Flarna** [comment]
I think you are right. Could you create a PR?

**Comment by Maxpain177** [comment]
> I think you are right. Could you create a PR?

Yes
