### ISSUE TITLE
Hey, I want to start with Angular .. but whenever I run npm start the error comes

### ISSUE THREAD

**Issue by KeineConnection** [DefinitelyTyped/DefinitelyTyped#30354]
node_modules/@types/jasmine/index.d.ts(138,30): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,47): error TS1005: ';' expected.
node_modules/@types/jasmine/index.d.ts(138,90): error TS1005: '(' expected.
node_modules/@types/jasmine/index.d.ts(138,104): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(138,112): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,113): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(138,121): error TS1005: ')' expected.
node_modules/@types/jasmine/index.d.ts(138,147): error TS1005: '(' expected.
node_modules/@types/jasmine/index.d.ts(138,162): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(138,163): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,164): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(138,165): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(138,179): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,183): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(138,208): error TS1005: '{' expected.
node_modules/@types/jasmine/index.d.ts(138,217): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(138,222): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,227): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(138,228): error TS1109: Expression expected.
node_modules/@types/jasmine/index.d.ts(138,230): error TS1005: ')' expected.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Moritz\AppData\Roaming\npm-cache\_logs\2018-11-07T17_10_56_447Z-debug.log

**Comment by jmaltis** [comment]
Same issue here.
Downgrade to version 2.8.9 worked for me.

**Comment by KeineConnection** [comment]
> Dasselbe Problem hier, weil ich "Typoskript" verwende: "~ 2.7.2". 
> Das Downgrade auf Version 2.8.9 hat für mich funktioniert.

I use TypeScript 3.1.6

**Comment by michaelryan0509** [comment]
I also saw this error and had to roll back to @types/jasmine version 2.8.9. Not sure if it's relevant, but I use typescript version 2.3.4. Is there a list of which versions of typescript are supported in @types/jasmine 2.8.11?

**Comment by de-dan** [comment]
@michaelryan0509 The easiest way to look this up is on npm: https://www.npmjs.com/package/@types/jasmine
Under the tab "Versions" you find the corresponding typescript version for each @types/jasmine version

**Comment by ayushnigamsworld** [comment]
> @michaelryan0509 The easiest way to look this up is on npm: https://www.npmjs.com/package/@types/jasmine
> Under the tab "Versions" you find the corresponding typescript version for each @types/jasmine version

Really worked for me. Best solution in town goes to @de-dan

**Comment by traderMax** [comment]
I have to lock the package @types/jasmine to 2.8.9 (you need to remove the "~" before 2.8.6 or 2.8.9 in package.json. Then remove the **package-lock.json** and **node_modules** and "npm cache clean --force" and "npm install"

**Comment by vijayakumar-psg587** [comment]
@traderMax. Thank you. that actually worked without the need to downgrade or upgrade

**Comment by hssa-saslanka** [comment]
Hi All,

You have just change typescript@2.8.4 and @types/jasmine@2.8.3

Like 

1. npm install typescript/2.8.4 --save-dev
2. npm install @types/jasmine@2.8.3 --save-dev

It's working 100%.

Thanks,

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
