### ISSUE TITLE
@types/fs-extra -- Updates needed for Node v10.10+

### ISSUE THREAD

**Issue by bsiegel** [DefinitelyTyped/DefinitelyTyped#30398]
`@types/fs-extra` needs to be updated to account for changes in Node v10.10+.
Tagging @alan-agius4 @midknight41 @shiftkey @mees- @jrockwood

Relevant bits of the changelog are:

### Notable changes

* **fs**
  * Added a `recursive` option to `fs.mkdir` and `fs.mkdirSync`. If this option
    is set to true, non-existing parent folders will be automatically created. [#21875](https://github.com/nodejs/node/pull/21875)

### Notable Changes

* **fs**:
  * The methods `fs.read`, `fs.readSync`, `fs.write`, `fs.writeSync`,
    `fs.writeFile` and `fs.writeFileSync` now all accept `TypedArray` and
    `DataView` objects. [#22150](https://github.com/nodejs/node/pull/22150)
  * A new boolean option, `withFileTypes`, can be passed to `fs.readdir` and
    `fs.readdirSync`. If set to true, the methods return an array of directory
    entries. These are objects that can be used to determine the type of each
    entry and filter them based on that without calling `fs.stat`. [#22020](https://github.com/nodejs/node/pull/22020)

**Comment by carlosflorencio** [comment]
Any news on this?

**Comment by nullberri** [comment]
```
import fs from "fs-extra"

declare module "fs-extra" {
    export function readdir(
        path: string | Buffer,
        options?: { withFileTypes: boolean }
    ): Promise<fs.Dirent[] | string[]>
}

```

This seems to work.

**Comment by douglascayers** [comment]
Thanks @nullberri, that was very helpful.

I later came across https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42656 and learned about [typescript method overloading](https://www.typescriptlang.org/docs/handbook/functions.html#overloads).

Per the [NodeJS docs](https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback), depending on if `withFileTypes` is `true` or `false` then `readdir` will return different response. To get type safety from this then the module augmentation needs at least two versions of the `readdir` method as shown below.

Link to [types/node/fs.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/445f92ce91b337be3dcdb16307fa048c95c93d1f/types/node/fs.d.ts#L1062) when `withFileTypes: true`.

Link to [types/node/fs.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/445f92ce91b337be3dcdb16307fa048c95c93d1f/types/node/fs.d.ts#L1045) when `withFileTypes?: false`.

```js
declare module 'fs-extra' {
    // If 'withFileTypes' is false or not provided then string[] is returned.
    export function readdir(
        path: string | Buffer,
        options?: { encoding?: BufferEncoding | null; withFileTypes?: false },
    ): Promise<string[]>;

    // If 'withFileTypes' is true then dirent[] is returned.
    export function readdir(
        path: string | Buffer,
        options?: { encoding?: BufferEncoding | null; withFileTypes: true },
    ): Promise<fs.Dirent[]>;
}
```
