### ISSUE TITLE
google-apps-script: A mistyped? type

### ISSUE THREAD

**Issue by aiya000** [DefinitelyTyped/DefinitelyTyped#30400]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/google-apps-script` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @motemen, @grant

- - -

If you do not mention the authors the issue will be ignored.

Hello :smiley:

I'm developping a google apps script, and found an issue.

Below code raises an error.

<img width="604" alt="2018-11-09 11 44 59" src="https://user-images.githubusercontent.com/4897842/48243412-a3ece600-e423-11e8-8d92-e26f23dcf978.png">

( ☝️  says "a specified attribute's value is invalid: payload")

```typescript
function requestAimlWithSheets() {
    const response = UrlFetchApp.fetch("https://httpbin.org/anything", {
        method: "put",
        payload: ['poi'],
    })
    Logger.log(response.getContent())
}
```

And below raises no errors.

```typescript
    const response = UrlFetchApp.fetch("https://httpbin.org/anything", {
        method: "put",
        payload: 'poi',  // string!
    })
```

```typescript
    const response = UrlFetchApp.fetch("https://httpbin.org/anything", {
        method: "put",
        payload: JSON.stringify(['poi']),  // string!
    })
```

Also [the official document](https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app#fetch) doesn't say 'payload' can be an `object` :thinking:

Maybe @types/google-apps-script needs below.

```diff
diff --git a/types/google-apps-script/google-apps-script-tests.ts b/types/google-apps-script/google-apps-script-tests.ts
index a6a3ac8437..e564254d8a 100644
--- a/types/google-apps-script/google-apps-script-tests.ts
+++ b/types/google-apps-script/google-apps-script-tests.ts
@@ -28,11 +28,11 @@ CalendarApp.GuestStatus.NO;
 
 // test for URLFetchRequestOptions.payload
 import URLFetchRequestOptions = GoogleAppsScript.URL_Fetch.URLFetchRequestOptions;
-const postTest = (payload: Object): string => {
+const postTest = (payload: string): string => {
   const url = 'http://httpbin.org/post';
   const params: URLFetchRequestOptions = {
     method: 'post',
     payload: payload
   };
   return UrlFetchApp.fetch(url, params).getContentText();
 };
diff --git a/types/google-apps-script/google-apps-script.url-fetch.d.ts b/types/google-apps-script/google-apps-script.url-fetch.d.ts
index 28cc744672..05a5a27b64 100644
--- a/types/google-apps-script/google-apps-script.url-fetch.d.ts
+++ b/types/google-apps-script/google-apps-script.url-fetch.d.ts
@@ -48,7 +48,7 @@ declare namespace GoogleAppsScript {
        * payload. It can be a string, a byte array, or a JavaScript object. A JavaScript object will be
        * interpretted as a map of form field names to values, where the values can be either strings or blobs.
        */
-      payload?: string | object | Base.Blob;
+      payload?: string | Base.Blob;
 
       /**
        * Deprecated. This instructs fetch to resolve the specified URL within the intranet linked to your
```

**Comment by grant** [comment]
OK. Please file a Pull Request to fix the issue.

**Comment by aiya000** [comment]
I opened #30403 👍

**Comment by grant** [comment]
Hi @aiya000, it looks like this is actually a bug with using arrays `[]`. You should be able to use objects.
Can you close that PR and file a new issue?

https://issuetracker.google.com/issues/new?component=191640&template=824113

**Comment by aiya000** [comment]
I made https://issuetracker.google.com/issues/119372344
