### ISSUE TITLE
[@types/react] Missing context in every component

### ISSUE THREAD

**Issue by chapterjason** [DefinitelyTyped/DefinitelyTyped#30433]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Asana, @AssureSign, @Microsoft, @johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @morcerf, @tkrotoff, @DovydasNavickas, @onigoetz, @theruther4d, @guilhermehubner, @ferdaber, @jrakotoharisoa, @pascaloliv, @Hotell, @franklixuefei 

**Configuration**

```
        "@types/react": "^16.7.2",
        "@types/react-dom": "^16.0.9",
        "typescript": "^3.1.6",
```

I always get some messages like this. For every component, self written or not.

```
ERROR in [...]/Components/Navigation/NavigationItem.tsx(29,17)
      TS2605: JSX element type 'AnchorButton' is not a constructor function for JSX elements.
  Property 'context' is missing in type 'AnchorButton'.
```

**Comment by IljaDaderko** [comment]
Similar issue with 16.7.2

<img width="500" alt="screenshot 2018-11-10 at 17 45 16" src="https://user-images.githubusercontent.com/3154053/48303873-91040f80-e510-11e8-8a97-5ee13903f8c3.png">

Code for toggle image (its using react-native, but type error is coming from react types package)

```js
import * as React from 'react';
import {
  Animated,
  GestureResponderEvent,
  StyleSheet,
  TouchableWithoutFeedback,
  View
} from 'react-native';
import RatioImage, { IProps as RatioImageProps } from '../components/RatioImage';
import { durationNormal, easeOutQuad } from '../services/Animation';

/**
 * Types
 */
export interface IProps extends RatioImageProps {
  activeSource: { uri: string };
  active: boolean;
  onPress(event: GestureResponderEvent): void;
}

export interface IState {
  animation: Animated.Value;
}

/**
 * Component
 */
class ToggleImage extends React.Component<IProps, IState> {
  state = {
    animation: new Animated.Value(this.props.active ? 1 : 0)
  };

  componentDidUpdate(prevProps: IProps) {
    const { active } = this.props;
    const { animation } = this.state;
    if (active !== prevProps.active) {
      Animated.timing(animation, {
        toValue: active ? 1 : 0,
        easing: easeOutQuad,
        duration: durationNormal,
        useNativeDriver: true
      }).start();
    }
  }

  render() {
    const { onPress, width, ratio, source, activeSource, style } = this.props;
    const { animation } = this.state;

    return (
      <TouchableWithoutFeedback onPress={onPress}>
        <View style={[styles.container, style]}>
          <Animated.View
            style={[
              styles.image,
              styles.activeImage,
              {
                opacity: animation.interpolate({
                  inputRange: [0, 1],
                  outputRange: [0, 1]
                })
              }
            ]}
          >
            <RatioImage width={width} ratio={ratio} source={activeSource} />
          </Animated.View>

          <Animated.View
            style={[
              styles.image,
              {
                opacity: animation.interpolate({
                  inputRange: [0, 1],
                  outputRange: [1, 0]
                }),
                transform: [
                  {
                    scale: animation.interpolate({
                      inputRange: [0, 1],
                      outputRange: [1, 1.4]
                    })
                  }
                ]
              }
            ]}
          >
            <RatioImage width={width} ratio={ratio} source={source} />
          </Animated.View>
        </View>
      </TouchableWithoutFeedback>
    );
  }
}

export default ToggleImage;

/**
 * Styles
 */
const styles = StyleSheet.create({
  container: {
    position: 'relative'
  },
  image: {
    alignSelf: 'center'
  },
  activeImage: {
    position: 'absolute'
  }
});

```

**Comment by johnnyreilly** [comment]
See discussion here: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/9039892f8ea3823b0a37d2b9764ba413a9eb6aa9#commitcomment-31247157

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
