### ISSUE TITLE
[@types/react] useEffect with Promise

### ISSUE THREAD

**Issue by xiaoxiangmoe** [DefinitelyTyped/DefinitelyTyped#30455]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @acdlite @sebmarkbage @gaearon

If you do not mention the authors the issue will be ignored.

now:

```typescript
    type EffectCallback = () => (void | (() => void));
```

Can we change it to:

```typescript
    type EffectCallback = () => (void | (() => void) | Promise<void> | Promise<()=>void>);
```

This will help to write a callback in the form of an async function.

```typescript
useEffect(async ()=>{
    const response = await fetchSomeThing('/foo/bar')
    setState(response.data.results);
  }, []);
```

**Comment by Cryrivers** [comment]
`useEffect` doesn't seem to support async function.
