### ISSUE TITLE
Missing LINK and PURGE verbs on koa-router types

### ISSUE THREAD

**Issue by jorgeclaro** [DefinitelyTyped/DefinitelyTyped#30464]
Missing LINK and PURGE verbs on koa-router types:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa-router/index.d.ts

Authors:
@schfkt
@JounQin 
@romain-faust

**Comment by pavel1992** [comment]
I m sorry, but i'm not an author:) the right person is @schfkt

**Comment by romain-faust** [comment]
Can you provide a link to the documentation ?

**Comment by jorgeclaro** [comment]
Seems that PURGE is a custom one. At least would be nice to have at least the LINK and UNLINK available.

https://www.iana.org/assignments/http-methods/http-methods.xhtml
