### ISSUE TITLE
@types/hapi - request.app and server.app are not the same

### ISSUE THREAD

**Issue by wesselvdv** [DefinitelyTyped/DefinitelyTyped#30465]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/hapi` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick @jhsimms @rafaelsouzaf

If you do not mention the authors the issue will be ignored.

Currently the types for request.app and server.app are considered the same:

```typescript
/**
     * Provides a safe place to store server-specific run-time application data without potential conflicts with
     * the framework internals. The data can be accessed whenever the server is accessible.
     * Initialized with an empty object.
     * [See docs](https://github.com/hapijs/hapi/blob/master/API.md#-serverapp)
     */
    app: ApplicationState;
```

```typescript
    /**
     * Application-specific state. Provides a safe place to store application data without potential conflicts with the framework. Should not be used by plugins which should use plugins[name].
     * [See docs](https://github.com/hapijs/hapi/blob/master/API.md#-requestapp)
     */
    app: ApplicationState;
```

I would like to be able to decorate the request.app with request specific application state, whereas the server.app should be decorated with server specific application state. (e.g. difference between a shared db connection, and population session information by default on a query.)

My suggestion is to change it to the following:

```typescript
/**
     * Provides a safe place to store server-specific run-time application data without potential conflicts with
     * the framework internals. The data can be accessed whenever the server is accessible.
     * Initialized with an empty object.
     * [See docs](https://github.com/hapijs/hapi/blob/master/API.md#-serverapp)
     */
    app: ServerApplicationState;
```

```typescript
    /**
     * Application-specific state. Provides a safe place to store application data without potential conflicts with the framework. Should not be used by plugins which should use plugins[name].
     * [See docs](https://github.com/hapijs/hapi/blob/master/API.md#-requestapp)
     */
    app: RequestApplicationState;
```

Whereas both still are empty interfaces that we can override at our own leisure.

**Comment by SimonSchick** [comment]
Yea, there was a fair bit confusion going on about `server.settings.app` `server.app` and `request.app`, thanks for pointing this out, if you create a PR I will approve it asap.

**Comment by ptorian** [comment]
Would there be any interest in making `ServerApplicationState` and `RequestApplicationState` generic parameters that get taken in on the `Server` constructor so that any usages of `app` or `server.app` (e.g. on requests) get properly typed? Or is there another way to handle this?

**Comment by SimonSchick** [comment]
I don't think this is a good idea, as it would involve passing generics *everywhere* which is really annoying.

**Comment by ptorian** [comment]
True, it would involve passing generics everywhere. Maybe I'm just not clear on how the types here are supposed to work, how would one extend `ApplicationState` in order to get static type checking on `request.app` inside of route handlers?
