### ISSUE TITLE
BigInt nodejs typings support

### ISSUE THREAD

**Issue by lal12** [DefinitelyTyped/DefinitelyTyped#30471]
Typescript 3.2 will contain support for BigInt and will be released this month (I assume probably during the next days?). BigInt was also enabled by default in Node v10.4. Are there any efforts or plans made to implement the BigInt type definitions for node 10 yet?

@SimonSchick @Flarna @rbuckton

**Comment by SimonSchick** [comment]
Ehh, @andy-ms is BitInt contained in a lib? They really shouldn't be in node typings since they are also supported in browsers, and copy pasting definitions is always bad :)

**Comment by andy-ms** [comment]
It should be in `--lib esnext` already.

**Comment by lal12** [comment]
The question wasn't about typescript but about the node typings?

**Comment by SimonSchick** [comment]
@lal12 thanks for clarifying, we will probably have to look into doing a split of typings for 3.x at that point in order to support it.
I will look into rolling node 11.x typings for ts 3.1 once it's out.

**Comment by Flarna** [comment]
I think the most important point is to find a good way to split the node typings into a typescript 2.1 and 3.1 part without running into a sync/maintenance nightmare. I don't think that anyone would like to maintain two versions (incl. tests) of node type definitions.

On the one hand there are several hundred of packages depending on node typings working with 2.1 and on the other hand most maintainers of node type definitions would like to use newer typescript features.

**Comment by lal12** [comment]
> I will look into rolling node 11.x typings for ts 3.1 once it's out.

I think backporting them  would be important too, since node 10 is LTS for quire a while now.

**Comment by felixfbecker** [comment]
I'm also in need for `process.hrtime.bigint(): bigint`. Can't people on 2.x simply use `disableLibCheck`?

**Comment by felixfbecker** [comment]
This is also impossible to work around:
![image](https://user-images.githubusercontent.com/10532611/48554846-cf6a4780-e8df-11e8-9973-30fd21e6286a.png)

**Comment by Flarna** [comment]
once #30477 is merged the infrastructure to use newer typescript features in node typings should be ready.

**Comment by Flarna** [comment]
`process.hrtime.biging()` should be covered by #33176

**Comment by ttraenkler** [comment]
I see this issue has been closed but I do not see bigint types for e.g. fs.Stats.ino https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v10/fs.d.ts which are documented as number | bigint in the docs https://nodejs.org/api/fs.html#fs_stats_ino

**Comment by SimonSchick** [comment]
Might take a stab at this, can't make any promises atm.

**Comment by Flarna** [comment]
@ttraenkler Could you create a PR? It's much better if people really using an APIs do the changes as they verify it in real apps instead of relying on docs/release notes.

**Comment by ttraenkler** [comment]
@Flarna I will have a look and might create a PR for the fs module.

**Comment by RReverser** [comment]
Should this issue be reopened? Looks like fs stats are still not updated.

**Comment by SimonSchick** [comment]
@RReverser This has been implemented and various people including me are using this?
Can you perhaps be more specific what is supposedly missing?
