### ISSUE TITLE
Wrong type for headers in w3cwebsocket constructor

### ISSUE THREAD

**Issue by lab360-ch** [DefinitelyTyped/DefinitelyTyped#30534]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9acca8ab3e8b198aa3332f3ff6f03c0a6e3ce1e9/types/websocket/index.d.ts#L697

headers?: any[] should be headers?: any

headers passed as dictionary and not as list to the constructor

**Comment by dpopp07** [comment]
You might also consider `OutgoingHttpHeaders` from `@types/node`
