### ISSUE TITLE
[@types/react] useEffect(async () => ...) does not account for async

### ISSUE THREAD

**Issue by IljaDaderko** [DefinitelyTyped/DefinitelyTyped#30551]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Asana, @AssureSign, @Microsoft, @johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @morcerf, @tkrotoff, @DovydasNavickas, @onigoetz, @theruther4d, @guilhermehubner, @ferdaber, @jrakotoharisoa, @pascaloliv, @Hotell, @franklixuefei

Right now I am unable to make function that `useEffect` takes in as async, since it returns following error:

> [ts]
> Argument of type '() => Promise<void>' is not assignable to parameter of type 'EffectCallback'.
>   Type 'Promise<void>' is not assignable to type 'void | (() => void)'.
>     Type 'Promise<void>' is not assignable to type '() => void'.
>       Type 'Promise<void>' provides no match for the signature '(): void'. [2345]

**Example**
```js
useEffect(async () => {
  await ...
})
```

Judging by what I've googled async function inside useEffect is a valid option?

**Comment by IljaDaderko** [comment]
App

**Comment by rauldeheer** [comment]
Hi! You can now easily use the `async await` syntax with the React `useEffect` hook with [this](https://www.npmjs.com/package/use-async-effect) package. I hope this will help you, and others.

**Comment by alfonmga** [comment]
@rauldeheer thanks for the package but I think would be better if we could use `async` without add extra dependencies. Anyways I'll use your package for now.

**Comment by daryl** [comment]
Why is this closed? Having issues with this too.

**Comment by IljaDaderko** [comment]
@daryl function within `useEffect` should not be async by design in react. You either need to implement this logic or use package mentioned by @rauldeheer.

So there are no issues with types, they are actually helping you to catch this incorrect use case.

**Comment by mlg87** [comment]
for anyone else finding themselves here:
- [Suspense will handle fetching data in the near future](https://github.com/facebook/react/issues/14326#issuecomment-441680293)
- while you can't return a promise in `useEffect`, you can get around this by:
```ts
const [thing, setThing] = useState(null);

useEffect(() => {
  Api.makeRequest()
    .then(res => {
      // do what you need to do with res here
      setThing(res);
    });
});
```

**Comment by ferdaber** [comment]
A very useful custom hook:
```ts
function useAsyncEffect(effect: () => Promise<void | (() => void)>, dependencies?: any[]) {
  return useEffect(() => {
    const cleanupPromise = effect()
    return () => { cleanupPromise.then(cleanup => cleanup && cleanup()) }
  }, dependencies)
}
```

**Comment by yfain** [comment]
Instead of this 
```
useEffect(async () => {
  await ...
})
```
try this:

useEffect( {async () => {
  await ...
}} )

I had the same issue and it helped.

**Comment by SanthoshRaju91** [comment]
> Instead of this
> 
> ```
> useEffect(async () => {
>   await ...
> })
> ```
> 
> try this:
> 
> ```
> useEffect( {async () => {
>   await ...
> }} )
> ```
> 
> I had the same issue and it helped.

This is like your providing object to the useEffect function, BTW I think this is wrong. Objects I think are not represented in this way.

**Comment by yfain** [comment]
@SanthoshRaju91 I've updated my post. Initially, I put the curly braces in the wrong place. Thanks for noticing.

**Comment by SanthoshRaju91** [comment]
Let me try this to fix my issue. Thank you for helping us understand the usage of useEffect

**Comment by kostrse** [comment]
> 
> 
> A very useful custom hook:
> 
> ```ts
> function useAsyncEffect(effect: () => Promise<void | (() => void)>, dependencies?: any[]) {
>   return useEffect(() => {
>     const cleanupPromise = effect()
>     return () => { cleanupPromise.then(cleanup => cleanup && cleanup()) }
>   }, dependencies)
> }
> ```

The cancellation pattern is wrong in my oppinion. It should work as a cancellation mechanism, not deferred cleanup. Otherwise the effect callback would still have chance to have effect on outside state  after the hook was already cancelled.

It should be something like this instead:
```ts
function useAsyncEffect(effect: (isCanceled: () => bool) => Promise<void>, dependencies?: any[]) {
  return useEffect(() => {
    const canceled = false;
    effect(() => canceled);
    return () => { canceled = true; }
  }, dependencies)
}
```

**Comment by Ofer-Gal** [comment]
@kostrse How can I use the data returned from "doSomeAsyncStuff"  the variable "result" is void.

**Comment by luizcoutinhozup** [comment]
> Hi! You can now easily use the `async await` syntax with the React `useEffect` hook with [this](https://www.npmjs.com/package/use-async-effect) package. I hope this will help you, and others.
> 
> Cheers  !

Thanks!!!
