### ISSUE TITLE
[ @types/single-spa-react ] throws ts error with --strictFunctionTypes, suggestion for better CustomProps typings

### ISSUE THREAD

**Issue by chris-dopuch** [DefinitelyTyped/DefinitelyTyped#30666]
If you know how to fix the issue, make a pull request instead.
(I have a proposed solution linked here, happy to PR if it looks good)

- [x] I tried using the `@types/single-spa-react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Garrett-Smith-iq 

## What I tried to do

I tried to use Single-spa-react with a component that takes custom props (https://single-spa.js.org/docs/building-applications.html#custom-props)
My tsconfig includes the compiler option `--strictFunctionTypes`, which we believe is a good practice to use because it can catch certain run time errors.
We discovered that using this setting with `@types/single-spa-react` would produce a tsc error when you pass in a component in the Options to singleSpaReact. 
Here is a minimal repro case with a basic TS create-react-app boilerplate -- this is the line which will cause the error. 
https://github.com/chris-dopuch/custom-props-type/blob/master/src/App.tsx#L33
If you `npm i && npm run build` you will see this:
```
Projects/custom-props-type/src/App.tsx
(33,3): Type 'typeof App' is not assignable to type 'ComponentClass<{}, any>'.
  Types of parameters 'props' and 'props' are incompatible.
    Type '{}' is not assignable to type 'Readonly<IAppProps>'.
      Property 'name' is missing in type '{}'.
```

## What I expected

I expected it to either be permissive with the prop types that the `rootComponent` takes (e.g. being `any` as opposed to `{}`)
or else I expected it to take a generic type param to specify the prop types of `rootComponent`

## Proposed solution

I think a better way to handle this is to take a generic argument to `singleSpaReact` which declares the component type that it will take. This could help to catch issues where the props that your component takes do not line up with the props provided from Single-Spa. (IMO the _best_ way to handle it would be if we could derive the custom props type from the call to single-spa's `registerApplication` but since the root library is not typed, I am unsure how to do that).

Here's a gist with an example of how I would update the type definition:
https://gist.github.com/chris-dopuch/84ca6da1840ea453ed13ab2897fca03b

(Note: I also changed the signature of the lifecycle methods because they don't actually take `opts, props`, they just take `props`, see here: https://github.com/CanopyTax/single-spa-react/blob/master/src/single-spa-react.js#L49)

**Comment by chris-dopuch** [comment]
On a second read-through, I'm realizing that the `ComponentType` generic in my example should be optional and default to `React.ComponentClass` but you get the gist of my idea I hope.

**Comment by chris-dopuch** [comment]
@Garrett-Smith-iq Hoping to hear back from you soon. If I don't hear anything within the next week I'll just move forward with pull-requesting these changes.

**Comment by Garrett-Smith-iq** [comment]
I don't have the time to work on this. If you're able to make a PR I think that's the best way to go forward 👍

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
