### ISSUE TITLE
[@types/graphql] Usage of Maybe for optional arguments

### ISSUE THREAD

**Issue by pbuyle** [DefinitelyTyped/DefinitelyTyped#30667]
After upgrading to the latest version of @types/graphql, I';m getting error in my unit tests for my custom scalars. When testing their `parseLiteral` methods, tsc now complains that one of the two arguments are missing (`variables`). 

The TS definition for the function is
```
export type GraphQLScalarLiteralParser<TInternal> = (
    valueNode: ValueNode,
    variables: Maybe<{ [key: string]: any }>
) => Maybe<TInternal>;
```

which is a translation of the following Flow definition
```
export type GraphQLScalarLiteralParser<TInternal> = (
  valueNode: ValueNode,
  variables: ?ObjMap<mixed>,
) => ?TInternal;
```
This TS definition force the nullable and possibly undefined `variables` argument to be explicitly passed with a `undefined` value instead of being omitted like you would do for an optional argument. I don't known much about Flow, but I would expect the _maybe_ here is  used to make the arguments optional. In which case, I would expect the TS definition to be
```
export type GraphQLScalarLiteralParser<TInternal> = (
    valueNode: ValueNode,
    variables?: Maybe<{ [key: string]: any }>
) => Maybe<TInternal>;
```

However, it may be that not using an optional argument in the TS definition is intentional.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @TonyPythoneer , @calebmer @intellix, @firede, @kepennar, @freiksenet, @IvanGoncharov, @DxCx, @rportugal, @tgriesser, @dyst5422, @adnsio, @divyenduz, @bradzacher, @clayne11,@JCMais
If you do not mention the authors the issue will be ignored.

**Comment by bradzacher** [comment]
You would be wrong in how maybe works in flow.
Flow has the optional modifier, just like TS.

Optional and maybe are related, but defining a property as one doesn't automatically mean the other is true as well.

In flow if something is optional, then the caller DOESN'T have to supply it, but if they do, they HAVE to give it a non null value.

If something is maybe, the caller HAS to supply it, however they can supply a null or undefined value.

In this case, the typescript types exactly match the flow types.

**Comment by pbuyle** [comment]
Then the best is to keep the behavior as provided by the authors of the Flow type definition and don't make the arguments optional.
