### ISSUE TITLE
Using @types/angular with JQuery v3

### ISSUE THREAD

**Issue by oBusk** [DefinitelyTyped/DefinitelyTyped#30705]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/angular` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @diegovilar @thorn0 @leonard-thieu @scipper 

If you're trying to use `@types/angular@^1.6.51` together with `@types/jquery@^3.3.22`  there will be mismatches that can cause issues. 

The exact issue I was running in to was working with events, `JQuery.Event` in JQuery v3 and `JQueryEventObject` in JQuery v2. 

Using `$.on()` will _work_, but falls to a `@deprecated` signature, which is suboptimal.

I've createda repo, https://github.com/oBusk/angular-jquery-event-issue that shows this situation.

I don't know if the solution is to upgrade JQLite to JQuery v3? Question is how that would work together with `@types/jquery@^1.0.0` or `@types/jquery@^2.0.0`

**Comment by thorn0** [comment]
I'm afraid it's intended behavior. Exactly because of this:

> Question is how that would work together with @types/jquery@^1.0.0 or @types/jquery@^2.0.0

**Comment by HolgerJeromin** [comment]
> Odd. In your example, you provide a callback that uses the JQuery.Event type from @types/jquery@3 but TypeScript ends up selecting the overload the uses the deprecated JQueryEventObject type. I'm not sure why this happens.

There is no valid match with all overloads. But TS reports this as a missmatch to one of the overloads (the last?). This happens often to me. Quite confusing message.
