### ISSUE TITLE
[@types/styled-components] error when using css from css helper in keyframes helper

### ISSUE THREAD

**Issue by mbohgard** [DefinitelyTyped/DefinitelyTyped#30752]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek, @Igmat, @Lavoaster, @Kovensky 

Versions:
TypeScript: 3.1.6
@types/styled-components: 4.1.1
styled-components: 4.1.1

When inserting css generated by the css helper in a keyframes block I get the error
`
Argument of type 'FlattenInterpolation<ThemeProps<any>>' is not assignable to parameter of type 'SimpleInterpolation'.
  Type 'FlattenInterpolation<ThemeProps<any>>' is not assignable to type 'FlattenSimpleInterpolation'.
    Types of property 'concat' are incompatible.
      Type '{ (...items: ConcatArray<Interpolation<ThemeProps<any>>>[]): Interpolation<ThemeProps<any>>[]; (...items: (string | number | false | Keyframes | Pick<StyledComponentBase<any, any, any, any>, "defaultProps" | ... 2 more ... | "withComponent"> | ... 6 more ... | undefined)[]): Interpolation<...>[]; }' is not assignable to type '{ (...items: ConcatArray<SimpleInterpolation>[]): SimpleInterpolation[]; (...items: (string | number | false | Keyframes | Pick<StyledComponentBase<any, any, any, any>, "defaultProps" | "displayName" | "$$typeof" | "withComponent"> | ... 5 more ... | undefined)[]): SimpleInterpolation[]; }'.
        Type 'Interpolation<ThemeProps<any>>[]' is not assignable to type 'SimpleInterpolation[]'.
          Type 'Interpolation<ThemeProps<any>>' is not assignable to type 'SimpleInterpolation'.
            Type 'FlattenInterpolation<ThemeProps<any>>' is not assignable to type 'SimpleInterpolation'.
`

Sample code:
```typescript
const show = css`
  opacity: 1;
  transform: scale(1) translateY(0);
`;

const hide = css`
  opacity: 0;
  transform: scale(0.95, 0.8) translateY(20px);
`;

const entry = keyframes`
  from { ${hide} }
  to { ${show} }
`;
```

Both `${hide}` and `${show}` generates the same error here. Since I don't use any interpolation here in the `show` or `hide` css I can fix this by not using the css helper but I think that's beside the point.

**Comment by Kovensky** [comment]
Oops, I guess this can be fixed by adding an extra overload to `css` that returns `SimpleInterpolation`

This is because interpolations _are_ allowed in `keyframes`, as long as they are not functions.
