### ISSUE TITLE
Definition request for hypernova-react

### ISSUE THREAD

**Issue by d9su** [DefinitelyTyped/DefinitelyTyped#30761]
Currently rolling my own for `hypernova-react`. [There are only two functions](https://github.com/airbnb/hypernova-react/blob/master/src/index.js) and they directly feed the params to `React.createElement`, so I just had to copy some definitions from `@types/react` for that method.

I could open a PR but didn't want to deal with the test cases. Theoretically it would borrow lots of parts from `@types/react` for the `React.createElement` as well, but they look pretty complicated. If anyone wants to take a stab at creating the definitions, here's my version so far:

```ts
// Augmenting hypernova-react: https://github.com/airbnb/hypernova-react/blob/master/src/index.js
// Types referenced from `createElement` from @types/react: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L176-L209
declare module 'hypernova-react' {
  import {
    ReactHTML,
    ReactSVG,
    SFC,
    ClassType,
    ClassicComponent,
    ComponentState,
    ClassicComponentClass,
    Component,
    ComponentClass,
  } from 'react';

  export function renderReact(
    name: string,
    component: 'input' | keyof ReactHTML | keyof ReactSVG | string
  ): void;
  export function renderReact<P>(
    name: string,
    component: SFC<P> | ClassType<P, ClassicComponent<P, ComponentState>, ClassicComponentClass<P>>
  ): void;
  export function renderReact<P, T extends Component<P, ComponentState>, C extends ComponentClass<P>>(
    name: string,
    component: ClassType<P, T, C>
  ): void;
  export function renderReact<P>(
    name: string,
    component: ComponentClass<P>
  ): void;

  export function renderReactStatic(
    name: string,
    component: 'input' | keyof ReactHTML | keyof ReactSVG | string
  ): void;
  export function renderReactStatic<P>(
    name: string,
    component: SFC<P> | ClassType<P, ClassicComponent<P, ComponentState>, ClassicComponentClass<P>>
  ): void;
  export function renderReactStatic<P, T extends Component<P, ComponentState>, C extends ComponentClass<P>>(
    name: string,
    component: ClassType<P, T, C>
  ): void;
  export function renderReactStatic<P>(
    name: string,
    component: ComponentClass<P>
  ): void;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
