### ISSUE TITLE
Lodash _.pick changes the types of the properties

### ISSUE THREAD

**Issue by trusktr** [DefinitelyTyped/DefinitelyTyped#30797]
Authors: @DomiR  @jtmthf @thorn0 @e-cloud @ailrun @aj-r @stepancar @chrootsu @bczengel 

I was trying to use lodash `_.pick` to make an new object with a subset of properties of another object, but pick seems to change the properties from not required (f.e. using `?` notation), to required.

The source object that I'm copying from has both required and not-required props.

Is it possible to improve the type definition of `_.pick` so that it maintains the requiredness of the properties in the new object?

**Comment by trusktr** [comment]
I'm on v 4.14.106 of the type defs

**Comment by Ailrun** [comment]
@trusktr Did you try with v4.14.118 (latest one)? It uses `Pick` so it should preserve optionalness of properties.

**Comment by trusktr** [comment]
Awesome, thanks!
