### ISSUE TITLE
pouchdb-core using types form  dom lib instead of node-fetch

### ISSUE THREAD

**Issue by AGrzes** [DefinitelyTyped/DefinitelyTyped#30814]
- [x] I tried using the `@types/pouchdb-core` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors
  - Authors: @kmoe @tiangolo @TobiasBales @fredgalvao @geppy @trubit @spaulg

I'm getting bunch pf errors when using  `@types/pouchdb-core` without dom lib
```
node_modules/@types/pouchdb-core/index.d.ts:93:19 - error TS2304: Cannot find name 'Request'.
93     url: string | Request,
                     ~~~~~~~
node_modules/@types/pouchdb-core/index.d.ts:94:12 - error TS2304: Cannot find name 'RequestInit'.
94     opts?: RequestInit
              ~~~~~~~~~~~
node_modules/@types/pouchdb-core/index.d.ts:95:14 - error TS2304: Cannot find name 'Response'.
95 ) => Promise<Response>;
                ~~~~~~~~
```

To reproduce 
```bash
npm install types/pouchdb-core typescript
echo '' >index.ts
npx tsc --lib es5 index.ts
```
When I add `dom` to lib then the errors disappears but the typing's uses `Request`, `RequestInit` and `Response` from `dom` instead of `node-fetch` and it causes incompatibility down the line.

The latest change added 
```typescript
/// <reference types="node-fetch" />
```
but it is apparently not working

**Comment by G-Rath** [comment]
@kmoe @tiangolo @TobiasBales @fredgalvao @geppy @trubit @spaulg 

This is a huge problem, as it's preventing me from using `PouchDB` in `typescript`.

Any chance of getting a fix or workaround?

**Comment by AGrzes** [comment]
I investigated the issue and it is not simple - the issue appears to be that `node-fetch` is defined as external module and whole `pouchdb` typings are using internal modules - and those two does not mix well.

The righ_ solution appears to be to rewrite `pouchdb` typings using external module syntax but it would be huge effort.

References 
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-did-adding-an-import-or-export-modifier-break-my-program
https://github.com/Microsoft/TypeScript/issues/8004
https://github.com/Microsoft/TypeScript/issues/909

**Comment by nsgundy** [comment]
Same issue here, unable to use typings for PouchDB in a nodejs application.

**Comment by GaganGowda89** [comment]
I tried cloning this project  `https://github.com/worldsibu/convector-example-fabcar-rest` later cd with `npm i` I get this error message.

I am using,
**node -v :** v8.15.0
**npm -v :** 6.4.1
**OS :** opensuse Leap 15.0

**Error logs:**

```
> fabcar-cc@0.1.0 build /home/abc/Documents/projects/convector-example-fabcar-rest/packages/fabcar-cc
> npm run clean && tsc


> fabcar-cc@0.1.0 clean /home/abc/Documents/projects/convector-example-fabcar-rest/packages/fabcar-cc
> rimraf dist client

../../../../../node_modules/@types/pouchdb-core/index.d.ts:93:19 - error TS2304: Cannot find name 'Request'.

93     url: string | Request,
                     ~~~~~~~

../../../../../node_modules/@types/pouchdb-core/index.d.ts:94:12 - error TS2304: Cannot find name 'RequestInit'.

94     opts?: RequestInit
              ~~~~~~~~~~~

../../../../../node_modules/@types/pouchdb-core/index.d.ts:95:14 - error TS2304: Cannot find name 'Response'.

95 ) => Promise<Response>;
                ~~~~~~~~


Found 3 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! fabcar-cc@0.1.0 build: `npm run clean && tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the fabcar-cc@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abc/.npm/_logs/2020-04-01T10_23_04_644Z-debug.log
lerna info lifecycle fabcar-cc@0.1.0~prepare: Failed to exec prepare script
lerna ERR! lifecycle "prepare" errored in "fabcar-cc", exiting 2
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! fabcar@0.1.0 lerna:install: `lerna bootstrap`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the fabcar@0.1.0 lerna:install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abc/.npm/_logs/2020-04-01T10_23_04_657Z-debug.log
ERROR: "lerna:install" exited with 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fabcar@0.1.0 install: `npm-run-all -s lerna:install`
npm ERR! Exit status 1

```
 I get this error for almost all typescript dependent projects.

**Comment by daweedm** [comment]
A quick fix is the following in your `tsconfig.json` file:

```js
{
  "compilerOptions": {
    "skipLibCheck": true,
    (...)
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
