### ISSUE TITLE
Joi extend

### ISSUE THREAD

**Issue by sm2017** [DefinitelyTyped/DefinitelyTyped#30877]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

@rokoroku , @SimonSchick , @k7sleeper , @RyanCavanaugh , @schfkt , @wingsbob , @DanielRosenwasser , @andy-ms , @minestarks , @TheWillG , @wanganjun , @richsilv , @rbuckton , @rafaelkallis , @pasieronen , @ozum , @janari , @farzadso , @dankraus , @pyrrho , @Botik , @b-galazka , @aconanlai

In the following line 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/joi/index.d.ts#L1156

As `extend` returns `any` , When we use an extension like : 

```js
const BaseJoi = require('joi');
const Extension = require('joi-date-extensions');
const Joi = BaseJoi.extend(Extension);
 ```

We loose auto completion in IDE , as the `Joi` is `any`

**Comment by sm2017** [comment]
@rokoroku , @SimonSchick , @k7sleeper , @RyanCavanaugh , @schfkt , @wingsbob , @DanielRosenwasser , @andy-ms , @minestarks , @TheWillG , @wanganjun , @richsilv , @rbuckton , @rafaelkallis , @pasieronen , @ozum , @janari , @farzadso , @dankraus , @pyrrho , @Botik , @b-galazka , @aconanlai

Please reply

**Comment by SimonSchick** [comment]
It's extremely hard and/or impossible to be typed correctly as you are adding extensions, simply cast the result to the desired schema type, example:

```
export declare type JoiType = typeof joi;
export interface ExtendedStringSchema extends joi.StringSchema {
    filename(): this;
    password(minScore: number): this;
}
export interface ExtendedArraySchema extends joi.ArraySchema {
    delim(delimeter: string): this;
}
export interface ExtendedSchema extends JoiType {
    date(): ExtendedDateSchema;
    string(): ExtendedStringSchema;
    array(): ExtendedArraySchema;
}
const mySchema = <ExtendedSchema>joi.extend(...)
```

Ideally we would make it returns `unknown` but that'd be a breaking change.

**Comment by sm2017** [comment]
@SimonSchick thank you

What you think , which is better?

```js
export function extend(extension: Extension|Extension[], ...extensions: Array<Extension|Extension[]>): any;
```

OR

```js
export declare type JoiType = typeof joi;
export function extend(extension: Extension|Extension[], ...extensions: Array<Extension|Extension[]>): JoiType;
```

I think `extend` must returns `JoiType` instead of `any`

**Comment by SimonSchick** [comment]
No, because in an extension you might override existing function making them incompatible.
