### ISSUE TITLE
[react-native] Tests failing with typescript@next

### ISSUE THREAD

**Issue by devrelm** [DefinitelyTyped/DefinitelyTyped#30958]
Tests for `@types/react-native` are failing with the following error, which is blocking many other PRs:

```
Error in react-native
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/react-native/test/index.tsx:821:17
ERROR: 821:17  expect  TypeScript@next compile error: 
JSX element type 'NativeBridgedComponent' does not have any construct or call signatures.
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:158:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/index.js:5:58)
    at <anonymous>
Error: The following packages had errors: react-native
    at doRunTests (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/tester/test-runner.ts:131:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

It looks like it's related to TypeScripts [improved tagged unions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#non-unit-types-as-union-discriminants) logic, as well as a recent change to the types for react-native in #30874 by @ide.

I'm not sure what the best route is to fix this -- it could be argued as either a `@types/react-native` issue, or a TypeScript issue -- but wanted to make sure that it was on people's radars.

One possible solution could be to have `requireNativeComponent` return a `React.ComponentType<any>` instead of a `React.ReactType`, though I don't know what other effects that would have.

There's a related (I think) issue in the Typescript repo here: Microsoft/TypeScript#28631

- [x] I tried using the `@types/react-native` package and had problems.
- [ ] ~I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript~ *N/A* - occurs with typescript@next
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @huhuanming @iRoachie @skn0tt @timwangdev @kamal @nelyousfi @alexdunne @swissmanu @bm-software @tkrotoff @a-tarasyuk @mvdam @esemesek @mrnickel

**Comment by ide** [comment]
Let’s revert my PR for now if that fixes things. Alternatively just returning “any” instead of ReactType is fine I think.

Perhaps what happened is that the TS tests used TS latest (3.1) and next (3.3) and didn’t cover 3.2 and we’ll need to test with 3.2.

**Comment by ide** [comment]
Put up a fix here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30959. I came to the same conclusion as @Pajn about the source of the error, thanks for independently verifying.
