### ISSUE TITLE
[react] defaultProps check breaks redux connected components

### ISSUE THREAD

**Issue by srittau** [DefinitelyTyped/DefinitelyTyped#30957]
- [X] I tried using the `@types/react` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @tkrotoff, @DovydasNavickas, @onigoetz, @theruther4d, @guilhermehubner, @ferdaber, @jrakotoharisoa, @pascaloliv, @hotell, @franklixuefei, @Kovensky

Upgrading from `@types/react` 16.7.7 to 16.7.10 (`@types/react-redux` at 6.0.10 and `redux` at 4.0.1) breaks connected components with default props:

```typescript
interface FooProps {
    x: number;
}

class Foo extends React.Component<FooProps> {
    static defaultProps = {
        x: 123,
    };
}

const ConnectedFoo = connect(
    () => ({
        x: 42,
    })
)(Foo);

const x = <ConnectedFoo/>;
```

typescript 3.2.1 complains in the last line:

```
Property '[Invalid_defaultProps]' is missing in type '{}' but required in type 'Readonly<Invalid_defaultProps<Pick<FooProps, never>, { x: number; }> & Pick<Pick<FooProps, never>, never> & Partial<Pick<Pick<FooProps, never>, never>>>'.
```

It's possible that this is fixable and should be fixed in `@types/react-redux`. If that's the case, please reassign.

**Comment by dougefr** [comment]
I've got the same error upgrading from version 16.7.8 > 16.7.10 in ant-design components

`TS2741: Property '[Invalid_defaultProps]' is missing in type '{ size: number; src: any; }' but required in type 'Invalid_defaultProps<Readonly<{ children?: ReactNode; }> & Readonly<AvatarProps>, { prefixCls: string; shape: string; size: string; }>'.`

**Comment by Pajn** [comment]
The same error comes with `react-apollo`, or every other single package on NPM that defines `defaultProps` or `propTypes`....

**Comment by danieldietrich** [comment]
@mattmccutchen I experience the same problem as @dougefr (see his [comment](
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30957#issuecomment-443278732)). 

However, my project does not use redux, nor `@types/react-redux` is a (transitive) dependency (read: it isn't present in the node_modules folder).

Does this still makes sense regarding your investigation?

Thx for looking into it!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
