### ISSUE TITLE
[react-beautiful-dnd] Missing onBeforeDragStart

### ISSUE THREAD

**Issue by mattes3** [DefinitelyTyped/DefinitelyTyped#30998]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @varHarrie, @bradleyayers, @paustint, @marknelissen

## Bug or feature request?

bug

### Expected behavior

Sample from readme.md compiles like it is.

### Actual behavior

With Typescript, the sample does not compile because the property 'onBeforeDragStart' does not exist in DragDropContextProps. See `index.d.ts` in \@types/react-beautiful-dnd:

```ts
export interface DragDropContextProps {
    onDragStart?(initial: DragStart, provided: HookProvided): void;
    onDragUpdate?(initial: DragUpdate, provided: HookProvided): void;
    onDragEnd(result: DropResult, provided: HookProvided): void;
}
```

### Steps to reproduce

1. yarn install react-beautiful-dnd @types/react-beautiful-dnd
1. compile sample from react-beautiful-dnd README.md with Typescript

### What version of `React` are you using?

16.6.3

### What version of `react-beautiful-dnd` are you running?

react-beautiful-dnd: 10.0.2
\@types/react-beautiful-dnd: 7.1.2

### What browser are you using?

does not matter because error happens already at compile time.

### Demo

```ts
import * as React from 'react';
import { DragDropContext } from 'react-beautiful-dnd';

class Board extends React.Component<BoardProps> {

render() {
    return (
      <DragDropContext
        onBeforeDragStart={this.onBeforeDragStart}
        onDragStart={this.onDragStart}
        onDragUpdate={this.onDragUpdate}
        onDragEnd={this.onDragEnd}
      >
        <div>Hello world</div>
      </DragDropContext>
    );
  }
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
