### ISSUE TITLE
[react-select] Creatable formatOptionLabel type of first argument 

### ISSUE THREAD

**Issue by n9** [DefinitelyTyped/DefinitelyTyped#31018]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-select` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @claasahl, @Darep, @burtek, @jonfreedman 

Currently first argument of `Select`'s `formatOptionLabel` is `OptionType` (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/7c33a958277e53aa335dcddec28ebfe6502638ca#diff-d6823b1f9b8e6eeb8324daf220a5c9d2R110). This is not true, in case of new value in `Creatable`.

In that case new values are created by `getNewOptionData` that ([currently](https://github.com/JedWatson/react-select/blob/9f309e837c489abdc0fb51a47506788fb56485b9/src/Creatable.js#L58-L62)) by default creates the following object:
```javascript
{
    label: optionLabel,
    value: inputValue,
    __isNew__: true,
}
```

Not sure how to solve that properly though. (Add another generic parameter? Add constraint to the existing generic parameter? ...)

**Comment by guyzmo** [comment]
I have a similar typing issue with `onChange` on Creatable: the first parameter is expecting a prototype of:

```
onChange(value: {__isNew__: boolean, value: OptionType, label: string}, action: ActionMeta<OptionType>)
```

whereas the type definition of `onChange`expects:

```
onChange(value: ValueType<OptionType>, action: ActionMeta<OptionType>)
```

to solve this I had to pass the `onChange()` method as:

```
<SelectCreatable<OptionType>
  {...props}
  onChange={handleChange as (v: ValueType<OptionType>, a: ActionMeta<OptionType>) => void}
/>
```

I'm not sure whether this is an issue with the original project (typed in flow) or with the transformation in TS.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
