### ISSUE TITLE
node.d.ts and requirejs.d.ts throwing compilation errors

### ISSUE THREAD

**Issue by thusithagh** [DefinitelyTyped/DefinitelyTyped#31030]
- [x] I tried using the `@types/node` and `@types/requirejs` packages and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x]  - Authors: @jkomyno , @a-tarasyuk , @alvis, @r3nya, @brunoscheufler, @samuela, @jbaldwin 

I have recently upgraded my Azure DevOps extension from typescript 1.8 to 3.2.1. The same time I've been upgrading the other dependencies and type definitions. As a result I currently have requirejs type 2.1.20 and Node.js type 10.12 (version numbers as per the *.d.ts).

Which throws below errors while compiling:

> node_modules/@types/node/index.d.ts(7696,5): error TS2300: Duplicate identifier 'mod'.
> node_modules/@types/requirejs/index.d.ts(38,11): error TS2300: Duplicate identifier 'mod'.
> node_modules/@types/requirejs/index.d.ts(422,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.

I understand there are some sort of similar questions in the net, but I don't see a proper answer to any.
Appreciate if you could have a look and let me know how to fix this.

Thank you.

**Comment by shanmudev** [comment]
Hi @thusithagh ,

Any solution found?

**Comment by thusithagh** [comment]
@shanmudev I think I ended up editing one of the *.d.ts files. This was some time back so I don't remember the specifics.
