### ISSUE TITLE
lodash fp pipe with compact

### ISSUE THREAD

**Issue by lfender6445** [DefinitelyTyped/DefinitelyTyped#31044]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu 

_________

I am getting an error from TSC when compiling the following code 

```ts
import * as pipe from  'lodash/fp/pipe'
import * as compact from 'lodash/fp/compact'

const foo = [1,'',2,'',3]

pipe(compact)(foo)
```

> Argument of type 'LodashCompact' is not assignable to parameter of type 'Many<(...args: any[]) => any>[]'.
>   Property 'push' is missing in type 'LodashCompact'.
> 
> 6 pipe(compact)(foo)

**Comment by lfender6445** [comment]
ignore this, i realized the arity here was wrong

**Comment by RobinBuschmann** [comment]
@lfender6445 Did you get it working with `strictNullChecks`? With `strictNullChecks` enabled I'm getting a similar error compiling the following:
```ts
import {pipe, compact, flatten} from 'lodash/fp';

const arr = [[['a']], [['c']], [['b']]];

pipe(compact, flatten)(arr);
```
> Error:(5, 6) TS2345: Argument of type 'LodashCompact' is not assignable to parameter of type '(a1: {}, a2: {}, a3: {}, a4: {}, ...args: any[]) => {}[]'.
  Types of parameters 'array' and 'a1' are incompatible.
    Property 'length' is missing in type '{}' but required in type 'ArrayLike<false | {} | "" | 0 | null | undefined>'.

Thanks!
