### ISSUE TITLE
How to specify the required TypeScript version?

### ISSUE THREAD

**Issue by bowenni** [DefinitelyTyped/DefinitelyTyped#31148]
A subset of the declarations of `web-animation-js` became a part of the TypeScript standard library in TS 3.1. Therefore the existing type declarations for `web-animations-js` conflict with the TS 3.1 standard library.
I'm trying to update the type declarations by removing those that are now in the standard library. This change is obviously incompatible with TS < 3.1 because those removed interfaces are simply undefined in the earlier TypeScript versions.

I'm now stuck on running the tests. How do I specify that the new type declarations only work with TS >= 3.1?

According to https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-use-features-from-typescript-21-or-above I need to put `// TypeScript Version: 3.1` as the last line of your definition header but doing so gives me an error
```
Testing...
web-animations-js failing:
Error: Could not parse version: line is '// TypeScript Version: 3.1'
    at Object.parseTypeScriptVersionLine (/usr/home/bowenni/workspace/DefinitelyTyped/node_modules/definitelytyped-header-parser/index.js:181:15)
```
when running `yarn test`.

I have also tried to create a `package.json` for `web-animation-js` and added 
```
  "dependencies": {
    "typescript": "^3.1.0"
  }
```
This doesn't seem to do anything. I'm still getting errors like
```
ERROR: 52:38   expect  Compile error in typescript@2.9 but not in typescript@next.
TypeScript@next features not yet supported.
Cannot extend an interface 'KeyframeEffect'. Did you mean 'implements'?
```
So it's still checking against TS 2.9.

I'd appreciate any thoughts.

**Comment by bowenni** [comment]
Friendly ping :)

**Comment by ltlombardi** [comment]
Things seems really slow here.. :-(

**Comment by BendingBender** [comment]
Things have changed for TS>=3.1 because the compiler now has a notion of different typings for different TS versions.

The way you do this for TS >= 3.1 is:
 - you keep existing types for TS < 3.1 the way they are
 - you create a new directory (usually called `ts3.1` and put the types for TS >= 3.1 in there.
 - you create a `package.json` in the types root dir with *at least* the following content:
```json
{
    "private": true,
    "types": "index",
    "typesVersions": {
        ">=3.1.0-0": {
            "*": [
                "ts3.1/*"
            ]
        }
    }
}
```

You can search for packages that already do this for reference, just look at `openpgp` or `jsdom` types.

**Comment by bowenni** [comment]
Thanks Dimitri.

Looks like the types for TS 3.1 and above were updated in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30734. Closing this issue then.
