### ISSUE TITLE
Nodejs typings are missing Object.setPrototypeOf()

### ISSUE THREAD

**Issue by the1mills** [DefinitelyTyped/DefinitelyTyped#31194]
@jkomyno @KSXGitHub @Flarna @jeremiergz 

- [x] I tried using the `@types/10.12.12` package and had problems.

Looks like there is no definition of `Object.setPrototypeOf`, a.k.a. the `Object` constructor does not have that static method, but it should according to MDN:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf

![screenshot from 2018-12-09 03-17-57](https://user-images.githubusercontent.com/2148448/49696607-0c350180-fb61-11e8-9bcb-d07983835182.png)

https://stackoverflow.com/questions/52402166/property-setprototypeof-does-not-exist-on-type-objectconstructor

**Comment by Flarna** [comment]
This is not a node type definition problem as Object is not part of node, it's the javascript language. As a result this is part of typescript lib definitions.
You have to include lib es2015 or later in your tsconfig.json.
