### ISSUE TITLE
[react-datepicker] Support registerLocale

### ISSUE THREAD

**Issue by Fakkio** [DefinitelyTyped/DefinitelyTyped#31256]
- [x] I tried using the `@types/react-datepicker@2.0.0` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @radziksh @andrewBalekha @smrq @Rogach @royxue @KoalaHuman @seansfkelley @justingrant @jakeboone02 

Hi,

I'm trying to use `registerLocale` but it seems there is no such member exported yet. Can someone fix this?

Thanks,
Fabio.

**Comment by jakeboone02** [comment]
I created #31267 to resolve this issue.  Note that the second argument to `registerLocale` is not typed, other than `{}`.  Once `date-fns` v2 is out, we can import that and type the second `registerLocale` argument as a `Locale` from `date-fns`.
