### ISSUE TITLE
Update Google Apps Scripts Types

### ISSUE THREAD

**Issue by dustinmichels** [DefinitelyTyped/DefinitelyTyped#31273]
@grant , I attempted to update some Google Apps Scripts type definitions with a [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30361) but wasn't able to get it through.

Opening an issue because I would still love to see some types updates.

---
Most importantly for me:

- The [ `OverGridImage`](https://developers.google.com/apps-script/reference/spreadsheet/over-grid-image) type seems to be missing. Consequently: 
    *  [`Sheet.insertImage()`](https://developers.google.com/apps-script/reference/spreadsheet/sheet#insertImage(String,Integer,Integer)) returns void, instead of `OverGridImage`.
    *  [`Sheet.getImages()`](https://developers.google.com/apps-script/reference/spreadsheet/sheet#getImages()) does not exist. Should return `OverGridImage[]`.

--- 
I'm also having some issues with Google Sheet `protections`, which may be harder to fix. (The issue seems to be at the Google API level, not the type definitions level but I'll mention it anyway.)

I use the line: `protection.removeEditors(protection.getEditors());` which is a clearly documented example usage for the [Protection class](https://developers.google.com/apps-script/reference/spreadsheet/protection). I get type errors because:
- [`getEditors`](https://developers.google.com/apps-script/reference/spreadsheet/protection#geteditors) returns `User[]` while 
- [`removeEditors` ](https://developers.google.com/apps-script/reference/spreadsheet/protection#removeeditorsemailaddresses) takes `String[]` as a parameter.

---
I could try opening another PR with a narrower scope. If others are more comfortable with writing TypeScript type definitions and can make these updates, I would be very appreciative!

**Comment by grant** [comment]
OK. I'll look at updating the types.

**Comment by niikoo** [comment]
I'm working on it at the moment, looking to make a PR soon

**Comment by smac89** [comment]
In addition to this, the `SheetsOnChangeChangeType` should not be enum, but rather a string type so that it can be usable when compiled to gas.

```ts
type SheetsOnChangeChangeType = "EDIT" | "INSERT_ROW" | "INSERT_COLUMN" | "REMOVE_ROW" | "REMOVE_COLUMN" | "INSERT_GRID" | "REMOVE_GRID" | "FORMAT" | "OTHER";
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
