### ISSUE TITLE
[graphql] Breaking change - Type inheritance

### ISSUE THREAD

**Issue by MatthiasKunnen** [DefinitelyTyped/DefinitelyTyped#31317]
- [x] I tried using the `@types/graphql@14.0.3` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @TonyPythoneer, @calebmer, @intellix, @firede, @kepennar, @freiksenet, @IvanGoncharov, @DxCx, @rportugal, @tgriesser, @dyst5422, @adnsio, @divyenduz, @bradzacher, @clayne11, @JCMais.

PR #29492 breaks the following code. 
```ts
/**
 * A list that cannot be null nor can its contents be null.
 * Equal to [Object!]! in the GraphQL type language.
 * @param {T} type
 * @returns {GraphQLNonNull<GraphQLList<GraphQLNonNull<T extends GraphQLType>>>}
 * @constructor
 */
export function GraphQLStrictList<T extends GraphQLType>(
    type: T,
): GraphQLNonNull<GraphQLList<GraphQLNonNull<T>>> {
    return new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(type)));
}
```
Error:
```
src/graphql/types.ts:37:5 - error TS2322: Type 'GraphQLNonNull<GraphQLNullableType>' is not assignable to type 'GraphQLNonNull<GraphQLList<GraphQLNonNull<T>>>'.
  Type 'GraphQLNullableType' is not assignable to type 'GraphQLList<GraphQLNonNull<T>>'.
    Property 'ofType' is missing in type 'GraphQLObjectType' but required in type 'GraphQLList<GraphQLNonNull<T>>'.

37     return new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(type)));
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Breaking change introduced in 14.0.2.
See the breaking change here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29492/files#diff-f4f6b32607e449673c0e42074e61fb4a

The important part of the diff:
```diff
@@ -154,14 +154,21 @@
  *     })
  *
  */
-export class GraphQLList<T extends GraphQLType> {
+interface GraphQLList<T extends GraphQLType> {
     readonly ofType: T;
-    constructor(ofType: T);
     toString(): string;
     toJSON(): string;
     inspect(): string;
 }
 
+
+interface _GraphQLList<T extends GraphQLType> {
+    (type: T): GraphQLList<T>;
+    new (type: T): GraphQLList<T>;
+}
+
+export const GraphQLList: _GraphQLList<GraphQLType>;
+
 /**
  * Non-Null Modifier
  *
@@ -182,14 +189,20 @@
  *
  * Note: the enforcement of non-nullability occurs within the executor.
  */
-export class GraphQLNonNull<T extends GraphQLNullableType> {
+interface GraphQLNonNull<T extends GraphQLNullableType> {
     readonly ofType: T;
-    constructor(ofType: T);
     toString(): string;
     toJSON(): string;
     inspect(): string;
 }
 
+interface _GraphQLNonNull<T extends GraphQLNullableType> {
+    (type: T): GraphQLNonNull<T>;
+    new (type: T): GraphQLNonNull<T>;
+}
+
+export const GraphQLNonNull: _GraphQLNonNull<GraphQLNullableType>;
+
 export type GraphQLWrappingType = GraphQLList<any> | GraphQLNonNull<any>;
 
 export function isWrappingType(type: any): type is GraphQLWrappingType;
```

**Comment by MatthiasKunnen** [comment]
I've no idea whether this is the correct approach, but it seems hacky.
The breaking PR tries to type the following JavaScript code.
```js
// node_modules/graphql/type/definition.js:286
function GraphQLNonNull(ofType) {
  if (this instanceof GraphQLNonNull) {
    this.ofType = assertNullableType(ofType);
  } else {
    return new GraphQLNonNull(ofType);
  }
}
```
It's a function that can be called with or without `new` and returns the same object.

**Comment by JCMais** [comment]
The type is hacky, I found it on StackOverflow or some obscure issue on TypeScript repo, I don't recall right now.

The idea is to merge both types into something that could be called with or without new, but looks like it's not working properly.

I'm totally in favor of reverting it if it's causing more problems than helping, but I would love if someone could find a solution that works for both cases, because I've worked with both in multiple code bases.

**Comment by MatthiasKunnen** [comment]
I was not able to find a better way to type this function either. Perhaps this specific problem deserves its own StackOverflow question or TypeScript issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
