### ISSUE TITLE
[react] Generic synthetic event type for DOM & Native

### ISSUE THREAD

**Issue by pshrmn** [DefinitelyTyped/DefinitelyTyped#31315]
I was trying to write a hook that returns an event handler that can be used in both React DOM and React Native applications. However, there is no generic event type that can be used to describe events from either place.

```ts
function useEventHandler<T extends ???>(...) {
  return function(event: T) {
    // ...
  }
}
```

The [`SyntheticEvent`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2bd0b3271c992ed9c22055f7151216f64afd7a3b/types/react/index.d.ts#L909-L935) and [`NativeSyntheticEvent`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0d4d1453b2e21c6273ec4a7d2496bfc56a77dc45/types/react-native/index.d.ts#L362-L378) interfaces share the same properties and only differ in three property types:

| property | @types/react | @types/react-native |
|---|---|---|
| nativeEvent | Event | T |
| target | EventTarget | NodeHandle |
| currentTarget | EventTarget & T | NodeHandle |

A union could be used, but I personally think that a base event shared by both would be a more ideal solution.

Is there any reason not to provide a generic synthetic event type? I very well could be missing something, which is why I opened an issue instead of a PR.

```ts
// to illustrate the idea, here is one possible implementation

// react/index.d.ts
interface BaseSyntheticEvent<E = Event, T = any, C = any> {
  nativeEvent: E;
  target: T;
  currentTarget: C;
  // and the rest of the properties...
}

interface SyntheticEvent<T = Element> extends BaseSyntheticEvent<
  Event,
  EventTarget,
  EventTarget & T
> {}

// react-native/index.d.ts
interface NativeSyntheticEvent<T> extends React.BaseSyntheticEvent<
  T,
  NodeHandle,
  NodeHandle
> {}
```

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei @Kovensky

**Comment by ferdaber** [comment]
I don't think there's any issue with creating a base type, it might probably be because the event types predated the native event types.
