### ISSUE TITLE
[@types/intl-tel-input] index.d.ts is not a module error

### ISSUE THREAD

**Issue by sjyn** [DefinitelyTyped/DefinitelyTyped#31375]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @fdnhkj @leonard-thieu @molnarm 

If you do not mention the authors the issue will be ignored.
===========================================
There seems to be an issue with the types module. When i have the types module installed, tsc outputs the following error:

`error TS2306: File '.../node_modules/@types/intl-tel-input/index.d.ts' is not a module.`

Upon further inspection, it looks like type module is using namespaces rather than modules, and I suspect that may be the ultimate cause of the issue. I messed around with the index.d.ts file for a little while but couldn't seem to get around the issue. My current solution is to just uninstall the types module completely.

The error is originating from the `import * as TelInput from 'intl-tel-input';` statement in my `.ts` file. I'm still pretty novice at the whole module ecosystem in TS, so it's possible that I'm doing something incorrect here.

I should note that I'm doing this in an Angular application. I installed the `intl-tel-input` and `@types/intl-tel-input` packages, and am opting out of the jQuery support as I want to drop jQuery as a dependency in my application. I've also created a [stackblitz demonstrating the issue](https://stackblitz.com/edit/angular-klohlh?file=src%2Fapp%2Ftel-input.directive.ts) (see the error on the import statement).

Any feedback would be appreciated

**Comment by leonard-thieu** [comment]
Thanks for reporting this. Will be fixed by #31569.
