### ISSUE TITLE
[@types/uuid] types depend on @types/node even though the package does not

### ISSUE THREAD

**Issue by attaboy** [DefinitelyTyped/DefinitelyTyped#31399]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @iamolivinius @felipeochoa @cjbarth

I'm using the `uuid` module in a browser-based application, which works fine. The @types/uuid package, however, adds a dependency with @types/node, which I do _not_ want, since there are some inconsistencies with how certain methods work. (e.g. setTimeout returns a number in browsers, but returns something else in Node.js), and adding those types interferes with my project's type validity.

If possible, the uuid types should not add a global dependency on Node types.

**Comment by bencoveney** [comment]
It would be good if there could be 2 sets of types for the library - one for use in the browser and one for use in node.

**Comment by sam-s4s** [comment]
So, the actual library's JS code uses `Array` and not `Buffer` - so why does the type contain `Buffer` at all? Bug? Can this be fixed?

**Comment by bencoveney** [comment]
Buffer is used in files in the `/lib` directory - e.g. https://github.com/kelektiv/node-uuid/blob/master/lib/sha1.js

**Comment by sam-s4s** [comment]
Ok, but given this runs in the browser for me, without node, then it shouldn't need a type in node...

**Comment by DanielSchaffer** [comment]
A similar issue is that including `@types/node` causes conflicts between the return types of `setTimeout` and `setInterval` when compiling for the browser

**Comment by DanielSchaffer** [comment]
The library itself exports different things depending on the runtime environment. Is there a way to provide types that do the same? How is this done for other libraries that do something similar?

**Comment by sam-s4s** [comment]
Good question - sadly I have no idea!

**Comment by DanielSchaffer** [comment]
Another option could be to use a locally defined `BufferLike` interface with the same signature - same-ish end result, but without the dependency on NodeJS types

**Comment by sam-s4s** [comment]
Maybe that is the best solution. Not much would need to be defined to make it compatible.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
