### ISSUE TITLE
Missing signatures for the http server constructor and the createServerMethod

### ISSUE THREAD

**Issue by franciscosucre** [DefinitelyTyped/DefinitelyTyped#31390]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/node` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jkomyno @a-tarasyuk @alvis @r3nya @BrunoScheufler @smac89 @tellnes @DeividasBakanas @eyqs @Flarna @Hannes-Magnusson-CK @KSXGitHub @hoo29 @kjin @ajafff @isLishude @mwiktorczyk @matthieusieben @mohsen1 @n-e @parambirs @eps1lon @SimonSchick @ThomasdenH @wwwy3y3 @ZaneHannanAU @jeremiergz @samuela

If you do not mention the authors the issue will be ignored.

Hello, i am developing a subclass of the standard node http server, but when i try to use it's constructor i receive this error:

```js
export default class SuGoServer extends Server {
  constructor(options = {}) {
    super(
      Object.assign(
        {
          IncomingMessage: SuGoRequest,
          ServerResponse: SuGoResponse,
        },
        options,
      ),
    );
}
```

> Argument of type '{ IncomingMessage: typeof SuGoRequest; ServerResponse: typeof SuGoResponse; }' is not assignable to parameter of type '(req: IncomingMessage, res: ServerResponse) => void'.
>   Type '{ IncomingMessage: typeof SuGoRequest; ServerResponse: typeof SuGoResponse; }' provides no match for the signature '(req: IncomingMessage, res: ServerResponse): void'.ts(2345)

I verified the type definitions and this possible signature for the http server server constructor do not exist. They do not exist on the createServer either. 

I have been trying to solve this problem to make you a pull request, but i am not really an expert in typings and haven't had success yet.

Here is the documentation of the createServer with lists the posible options to be received. This options are also applicable to the new Server() constructor. This works fine in normal javascript.

https://nodejs.org/docs/latest-v10.x/api/http.html#http_http_createserver_options_requestlistener

I hope the signature can be added, if not, any other help would be appreciated. 

Thanks!

**Comment by isLishude** [comment]
The type of http.Server has been defined.I think that your `typeof SuGoRequest` is not suited to `IncomingMessage`

```typescript
    class Server extends net.Server {
        constructor(requestListener?: (req: IncomingMessage, res: ServerResponse) => void);

        setTimeout(msecs?: number, callback?: () => void): this;
        setTimeout(callback: () => void): this;
        maxHeadersCount: number;
        timeout: number;
        keepAliveTimeout: number;
    }
```

see more here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L1202

**Comment by franciscosucre** [comment]
Hey @isLishude , thanks for answering! That is not what i meant, i'm sorry. I meant that the signature for the constructor that accepts the options parameter is missing.

options <Object>

IncomingMessage <http.IncomingMessage> Specifies the IncomingMessage class to be used. Useful for extending the original IncomingMessage. Default: IncomingMessage.
ServerResponse <http.ServerResponse> Specifies the ServerResponse class to be used. Useful for extending the original ServerResponse. Default: ServerResponse.

**Comment by Flarna** [comment]
Seems that the possibility to pass options to `createServer` (and also to constructor) introduced in 9.6.0 has not been added to type definitions yet.

**Comment by franciscosucre** [comment]
thanks @Flarna ! That is what i meant, sorry if a did not explain myself well.

**Comment by Flarna** [comment]
@franciscosucre Could you create a PR for this? This would have the big benefit that you can verify it already in your code before you submit it.

**Comment by franciscosucre** [comment]
@Flarna i can, but i have 2 questions:

1. ¿Which repository do i fork?
2. ¿Which type would have to set to those options? IncomingMessage and ServerResponse are classes ¿How can i represent them in the signature? ¿With any?

**Comment by ThomasdenH** [comment]
You can probably just add another line similar to this:

``constructor(options: {});``

**Comment by franciscosucre** [comment]
Alright, i started it but i have to leave the computer for a while, we'll test it out and then make the pull request and metion it here. Thanks @ThomasdenH !

**Comment by Flarna** [comment]
besides the file `types/node/index.d.ts` file which holds the definitions there is also the file `types/node/node-tests.ts` which includes tests.
For local tests in your code it's only needed to replace the file `node_modules/@types/node/index.d.ts` with your modified variant.

Usually `any` should be avoided if more concrete types are possible. Maybe adding something like this works (have not tried):
```
interface ServerOptions {
    IncomingMessage?: IncomingMessage,
    ServerResponse?: ServerResponse
}
...
constructor(options: ServerOptions, requestListener?: (req: IncomingMessage, res: ServerResponse) => void);
...
function createServer(options: ServerOptions, requestListener?: (request: IncomingMessage, response: ServerResponse) => void): Server;
```

**Comment by franciscosucre** [comment]
But the options passed are meant to be subclases of incomingMessage and Server Response, in order to extend their functionality, would that interface work with that? I can test later, but I am away from a computer for now.

**Comment by Flarna** [comment]
I would expect so as a subclass of `IncomingMessage` is actually an `IncomingMessage` (and more).

**Comment by franciscosucre** [comment]
Alright I'll test them later and report here the results. Thanks!

**Comment by franciscosucre** [comment]
Hi @Flarna when i set ServerOptions with IncomingMessage i get this error:

> Argument of type '{ IncomingMessage: typeof SuGoRequest; ServerResponse: typeof SuGoResponse; }' is not assignable to parameter of type 'ServerOptions'.
  Types of property 'IncomingMessage' are incompatible.
    Type 'typeof SuGoRequest' is missing the following properties from type 'IncomingMessage': httpVersion, httpVersionMajor, httpVersionMinor, connection, and 37 more.ts(2345)

My SuGoRequest object extends the http IncomingRequest so i do not know why are they incompatible. 

```js
class SuGoRequest extends IncomingMessage {
  public id?: string;
  public rawBody: any[] = [];
  public body: object = {};
  public path?: string;
  public url: string = '';
  public query: object = {};
  public method: string = '';

  /** 
   * Methods
   */
}
```

With any they work, but i know it is not the ideal solution.

**Comment by franciscosucre** [comment]
I made the pull request, right now it has the options in many, my code compiles with this. If i place the IncomingMessage type on ServerOptions, then the error i mentioned ocurrs

**Comment by Flarna** [comment]
Sorry, completely forgot about this.
Sure, you can cast the constructor to `any` and then you can pass any arguments you want.

**Comment by franciscosucre** [comment]
@Flarna don't worry. I mean the pull request i made had the typings with any. Could it be merged? Otherwise i have no way of using in my project. I cannot override the http typings.

**Comment by Flarna** [comment]
I think `any` is to generic and not needed.
```
interface ServerRequestOptions {
    IncomingMessage: typeof IncomingMessage;
    ServerResponse: typeof ServerResponse;
}
```
Should be fine for server constructor/`createServer`. The missing part is the request callback but as indicated in the PR I found no way to do this correct for typescript <2.8.

But if the above is enough for you it should be fine. There is already work ongoing to create a version used for >3.1 so maybe this can be added later then.

**Comment by franciscosucre** [comment]
Alright, could this fix be merged? I am not pushing, just asking. Thanks!

**Comment by Flarna** [comment]
I think it should work if you add the following in your code: 
```
declare module "http" {
	interface ServerOptions {
		IncomingMessage: typeof IncomingMessage;
		ServerResponse: typeof ServerResponse;
	}
	function createServer(options: ServerOptions, requestListener?: (request: IncomingMessage, response: ServerResponse) => void): Server;
}
```

**Comment by franciscosucre** [comment]
@Flarna that works for the createServer method but I actually need the definition for the constructor of the server class as I am extending the http classes like server, incomingMessage and Server Response. As server is a class in the definition, I cannot augment it with this module syntax.

**Comment by franciscosucre** [comment]
Thanks @Flarna, that casting trick allowed me to compile and continue my project. Then this typings will be added when a version for typescript > 3.1 is added? Should i close this issue or leave it open?
