### ISSUE TITLE
@types/react-navigation has no exported member 'createAppContainer'.

### ISSUE THREAD

**Issue by sm1th** [DefinitelyTyped/DefinitelyTyped#31400]
- [x] I tried using the `@types/react-navigation` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @huhuanming @mhcgrq @fangpenlin @petejkim @iRoachie @phanalpha @charlesfamu @timwangdev @bang88 @svbutko @levito @YourGamesBeOver @ArmandoAssuncao @cliedeman @magrinj @TizioFittizio @stigi @LinusU @jshosomichi @jakebooyah @brunoro @DenisFrezzato @mickaelw @alechill @builtbyproxy @jkillian @jeroenvervaeke @chagasaway

Looks like we need some typings for v3 of react-navigation.

package.json:
```
"@types/react-navigation": "^2.13.8",
"react-navigation": "^3.0.8"
```

App.tsx
```
import { createStackNavigator, createAppContainer  } from 'react-navigation';
```

Error:
```
{
	"resource": "....../src/App.tsx",
	"owner": "typescript",
	"code": "2305",
	"severity": 8,
	"message": "Module '\"....../node_modules/@types/react-navigation\"' has no exported member 'createAppContainer'.",
	"source": "ts",
	"startLineNumber": 13,
	"startColumn": 32,
	"endLineNumber": 13,
	"endColumn": 50
}
```

**Comment by nicholasrq** [comment]
same with `defaultNavigationOptions`. really looks like somehow types were downgraded to 2.x version

```
"@types/react-navigation": "^2.13.8",
 "react-navigation": "^3.0.8",
```

Error:
```
Object literal may only specify known properties, and 'defaultNavigationOptions' does not exist in type 'BottomTabNavigatorConfig'
```

```
Argument of type '{ initialRouteName: string; defaultNavigationOptions: ({ navigation }: any) => { animationEnabled: boolean; tabBarColor: string; tabBarOptions: { showLabel: boolean; style: { backgroundColor: string; borderTopWidth: number; borderTopColor: string; }; activeTintColor: string; inactiveTintColor: string; }; tabBarIcon:...' is not assignable to parameter of type 'BottomTabNavigatorConfig'.
  Object literal may only specify known properties, and 'defaultNavigationOptions' does not exist in type 'BottomTabNavigatorConfig'.
```

Code:

```typescript
import { createBottomTabNavigator } from 'react-navigation'

/* ... */

const Tabs =  createBottomTabNavigator({
  /* screens definition */
}, {
  initialRouteName: INITIAL_ROUTE,
  defaultNavigationOptions: ({ navigation }) => {
    /* ... */
  }
})
```

**Comment by sorakthunly** [comment]
Is there any temporary solution around this?

**Comment by sm1th** [comment]
@sorakthunly I switched to using react-navigation 2.x.x for now.

**Comment by daryl** [comment]
Having the same problems.

**Comment by sorakthunly** [comment]
For someone else who still wants to keep the benefit of the typings while still using react-navigation@3.x.x, I recommend trying this.

```Typescript
const reactNavigation = require('react-navigation');
const createAppContainer = reactNavigation.createAppContainer;
```

createAppContainer will not have a type definition but at least it's a temporary workgroup. With this you can also create your own type definition by doing:

```Typescript
export interface AppContainer {
  ..
}
const createAppContainer: AppContainer = reactNavigation.createAppContainer;
```

**Comment by sm1th** [comment]
@nicholasrq Super!
