### ISSUE TITLE
[styled-components] Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes...

### ISSUE THREAD

**Issue by patricknick** [DefinitelyTyped/DefinitelyTyped#31491]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/styled-components` package and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @Lavoaster @Kovensky 

I have the following code snippet of a component which should be correct according to the styled-components documentation.

```
const Wrapper = styled(Box)`
  border: 1px solid grey;
`;

const App = () => (
  <Wrapper>
    <Hello name="CodeSandbox" />
  </Wrapper>
);
```

Typescript though returns the following error:

> Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & Pick<Pick<BoxProps | (BoxProps & RefAttributes<Component<BoxProps, any, any>>), "a11yTitle" | "alignSelf" | "gridArea" | "margin" | "align" | ... 19 more ... | "wrap"> & Partial<...>, "a11yTitle" | ... 23 more ... | "wrap"> & { ...; } & { ...; }'.ts(2559)

I tried to find a solution but the only thing I found was this question on [StackOverflow].(https://stackoverflow.com/q/53724583/6882608)

Do you have some ideas how to solve this? 

I created a CodeSandbox where it can be reproduced: https://codesandbox.io/s/10z3qz9jp4
(In the beginning the error doesn't show in the sandbox. As soon as you add `<Wrapper someProp="">` and then remove it again, the error shows up.)

Dependencies:
- Typescript 3.2.2
- styled-components 4.1.3
- @types/styled-components 4.1.4
- @types/react 16.7.17

**Comment by champagne-randy** [comment]
Tnx a bunch for the SO ref @patricknick. This was [reported here](https://github.com/styled-components/styled-components/issues/2294) but closed ¯\_(ツ)_/¯ . Shared your input there, hopefully there'll be traction

**Comment by Igorbek** [comment]
I opened the CodeSandbox where it doesn't show any errors now. Has that issue been resolved somehow or still a thing?

**Comment by patricknick** [comment]
For some reason the error isn't shown initially. I had to switch files first or add and remove a property. I assume it's a bug of CodeSandbox.

**Comment by boschni** [comment]
I'm also running into this issue. The following code:

```tsx
interface WrapperProps {
  className?: string
}

const WrapperFCComponent: React.FC<WrapperProps> = p => (
  <div className={p.className}>{p.children}</div>
)

export class WrapperClassComponent extends React.Component<WrapperProps> {
  render() {
    return <div className={this.props.className}>{this.props.children}</div>
  }
}

const WrapperFC = styled(WrapperFCComponent)`
  border: 1px solid grey;
`

const WrapperClass = styled(WrapperClassComponent)`
  border: 1px solid grey;
`

const wrapperFC = <WrapperFC>Text</WrapperFC>
const wrapperClass = <WrapperClass>Text</WrapperClass>
```
Triggers the following error when using the WrapperClass component:
```
[ts] Type '{ children: string; }' has no properties in common with type 'IntrinsicAttributes & Pick<Pick<WrapperProps & RefAttributes<WrapperClassComponent>, "className" | "ref" | "key"> & Partial<Pick<WrapperProps & RefAttributes<WrapperClassComponent>, never>>, "className" | ... 1 more ... | "key"> & { ...; } & { ...; }'. [2559]
```
The WrapperFC component seems to work properly.

**Comment by JKillian** [comment]
I've [made a PR to fix this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32843) (though the main purpose was to add typings for `styled-components/native`). Please feel free tto try it out or leave a review!

**Comment by patricknick** [comment]
@JKillian Thanks for your work! I tried my CodeSandbox with the latest package but unfortunately this issue seems to remain unsolved:
https://codesandbox.io/s/y38p6wqq1x
(remember switching files first, otherwise the error is not shown in the editor)

**Comment by JKillian** [comment]
Hey @patricknick, I'm unable to see any errors in your example, not sure it it's a CodeSandbox issue or not. Could you send a screenshot of what you're seeing?

Also, not sure if it matters, but you may want to add the react types to your project also:

```
    "@types/react": "16.8.3",
    "@types/react-dom": "16.8.1",
```

**Comment by patricknick** [comment]
Funny, I don't see it anymore either. I could have sworn it was there when I posted it. Anyway, thanks for getting back to me. :)
