### ISSUE TITLE
[@types/classnames] error with bind: Cannot invoke an expression whose type lacks a call signature 

### ISSUE THREAD

**Issue by sidsethupathi** [DefinitelyTyped/DefinitelyTyped#31521]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/classnames` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @adidahiya @JKillian @seansfkelley @mradamczyk @marvinhagemeister 

I'm new to Typescript so sorry if this is user error.

I have a project bootstrapped with [Create React App](https://facebook.github.io/create-react-app/) which now supports Typescript.

When trying to use `classnames/bind` and the example from `classnames-test.ts`, I get an error.
```typescript
import * as cn from "classnames/bind";
const styles = {
  foo: "abc",
  bar: "def",
  baz: "xyz"
};
const cx = cn.bind(styles);
const className = cx("foo", ["bar"], { baz: true }); // => "abc def xyz"
```

```
Type error: Cannot invoke an expression whose type lacks a call signature. Type '{ default: ClassNamesExport; }' has no compatible call signatures.  TS2349

    14 | };
    15 | const cx = cn.bind(styles);
  > 16 | const className = cx("foo", ["bar"], { baz: true }); // => "abc def xyz"
       |                   ^
    17 |
```

If it helps, this is the default `tsconfig.json` that I am using as provided by CRA.

```json
{
  "compilerOptions": {
    "target": "es5",
    "allowJs": true,
    "skipLibCheck": false,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": [
    "src"
  ]
}
```

**Comment by marvinhagemeister** [comment]
I just tried to reproduce it locally but I'm unable to. The example posted works for me with the latest `classnames`, `@types/classnames` and `typescript` versions installed.

**Comment by sidsethupathi** [comment]
Here's a minimal example to reproduce: https://github.com/sidsethupathi/cra-classnames-typescript

I was able to resolve this by changing `esModuleInterop` in `tsconfig.json` from `true` to `false`.
