### ISSUE TITLE
[@types/jasmine] Latest change in 3.3.4 breaks tests

### ISSUE THREAD

**Issue by aav7fl** [DefinitelyTyped/DefinitelyTyped#31551]
In the most recent change to the Jasmine types, the behavior of `SpyObj` has removed the ability for me to Spy on some classes. 

Example: I am spying on `MatExpansionPanel` from `@angular/material/expansion/typings/expansion-panel`. 

I am creating the Spy with:
```  
let matExpansionPanelMock: jasmine.SpyObj<MatExpansionPanel>;
matExpansionPanelMock = jasmine.createSpyObj<MatExpansionPanel>('MatExpansionPanel', ['_getExpandedState', 'open', 'close']);
```

However, when I try to do anything with the `matExpansionPanelMock`, I am left with the error: 
```
TS2345: Argument of type 'SpyObj<MatExpansionPanel>' is not assignable to parameter of type 'MatExpansionPanel'.   Property '_viewContainerRef' is missing in type 'SpyObj<MatExpansionPanel>'.
```

This only showed up after `[@types/jasmine]` was updated from 3.3.3 -> 3.3.4. I believe these are the changes that are causing my issue, but I'm unsure if it's a bug or a new convention.

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d89ab9a678475a2aa97041ee5c33fb8997efcb74#diff-9e4053693e748b8ffdb3e9eb9d9299e8

- [x] I tried using the `@types/jasmine` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (3.1.6 latest for Angular 7)
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @fdim

If you do not mention the authors the issue will be ignored.

**Comment by FDIM** [comment]
The fix is on it's way
