### ISSUE TITLE
What is the replacement for the pipe method?

### ISSUE THREAD

**Issue by davidshen84** [DefinitelyTyped/DefinitelyTyped#31561]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/vinyl/index.d.ts#L319

According to [this][1] page, the `pipe` function is still the only way to operate files. I wonder why this method is marked with a `@deprecated` attribute in this package, and what would be the appropriate replacement.

[1]: https://gulpjs.com/docs/en/getting-started/working-with-files

**Comment by davidshen84** [comment]
Hi @thorn0 ,

I found it was you added this deprecation mark.

https://github.com/DefinitelyTyped/DefinitelyTyped/blame/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/vinyl/index.d.ts#L319

But in JS, `src(...).pipe()` is still the only way to handle the stream. I am new to gulp in TypeScript. Could you help me find the recommended replacement of the `pipe` function?

**Comment by thorn0** [comment]
See https://github.com/gulpjs/vinyl/issues/107

**Comment by thorn0** [comment]
`src(...)` returns a **readable stream**, not a **Vinyl file**. The method that was removed was a method of Vinyl files. In the future, please use StackOverflow for questions like this.

**Comment by davidshen84** [comment]
@thorn0 ,

Yes, I saw that bug. But https://github.com/gulpjs/vinyl-fs is still using `pipe` in the example. Maybe they forgot to update the document?

I posted a [question][1] on SO, but no reply yet.

Could you advise me of a better alternative?


Thanks

[1]: https://stackoverflow.com/questions/53865935/whats-the-replacement-for-the-pipe-function-in-gulp

**Comment by davidshen84** [comment]
So embarrassing...it turns out to be an IDE config error.  Very sorry!
