### ISSUE TITLE
`react-native-popup-dialog` out of date

### ISSUE THREAD

**Issue by atrauzzi** [DefinitelyTyped/DefinitelyTyped#31613]
If you know how to fix the issue, make a pull request instead.

- [✔] I tried using the `@types/xxxx` package and had problems.
- [✔] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [✔] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [✔] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - @PaitoAnderson 
  - @connectdotz 
  - @bm-software 
  - @dalwadani 

As per: https://github.com/jacklam718/react-native-popup-dialog/issues/145#issuecomment-448449564

It looks like some of the events you can handle aren't listed.

**Comment by i-schuetz** [comment]
This library can't be used in Typescript right now... right? I get compiler errors with the first code snippet in the readme...

**Comment by PaitoAnderson** [comment]
I've just submitted #32457 to fix this.

**Comment by PaitoAnderson** [comment]
This should be fixed now. Please close.

**Comment by i-schuetz** [comment]
Seems it's out of date again? The footer property is missing. I'd do this but just started learning Typescript.
