### ISSUE TITLE
 Variable 'require' must be of type 'NodeRequire', but here has type 'Require'

### ISSUE THREAD

**Issue by kumaresan-subramani** [DefinitelyTyped/DefinitelyTyped#31628]
- [x] I tried using the `@types/requirejs` package and had problems.

**package.json**
`
"devDependencies": {
    "@syncfusion/ej2-build": "*",
    "@types/chai": "^3.4.28",
   "@types/jasmine": "2.8.9",
    "@types/jasmine-ajax": "^3.1.27",
    "@types/requirejs": "^2.1.31"
  }

`
**When i try  compile my application it throws below error:**

> [11:47:10] Starting 'scripts-gen'...
> D:/workspace/components/ej2-button-components/node_modules/@types/requirejs/index.d.ts(396,13): error TS2403: **Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.**
> [11:47:23] 'scripts-gen' errored after 12 s
> [11:47:23] TypeScript error: D:/workspace/components/ej2-button-components/node_modules/@types/requirejs/index.d.ts(396,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.
>     at Object.getError (D:\workspace\components\ej2-button-components\node_modules\gulp-typescript\release\utils.js:53:15)

**versions:**
node - v8.11.3
npm  - 5.6.0
typescript -3.0.3

Please check this and provide any solution for this ASAP

**Comment by kumaresan-subramani** [comment]
In here, i need updation https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/requirejs/index.d.ts#L421

**Comment by kumaresan-subramani** [comment]
Any update on this?

**Comment by jonesmac** [comment]
I think I am facing this issue as well.  Any update?

**Comment by thiagomajesk** [comment]
Same here, I get the error:

```
C:/Users/{userName}/Source/Repos/project/Project.Web/node_modules/@types/node/module.d.ts(2,5): error TS2300: Duplicate identifier 'mod'.
C:/Users/{userName}/Source/Repos/project/Project.Web/node_modules/@types/requirejs/index.d.ts(38,11): error TS2300: Duplicate identifier 'mod'.
C:/Users/{userName}/Source/Repos/project/Project.Web/node_modules/@types/requirejs/index.d.ts(422,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.
```

Any reasons why this [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35946) hasn't been reviewed/ accepted yet?

**Comment by VM8198** [comment]
@kumaresan-subramani Any updates here? I am getting the same error

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
