### ISSUE TITLE
[@types/echarts] error with v4.1.3

### ISSUE THREAD

**Issue by hesi726** [DefinitelyTyped/DefinitelyTyped#31720]
http://echarts.baidu.com/option.html#series-line.markPoint.data, the data is a Array,
but in the 4.1.3, LineChart.ts  , line 4693, defined it as Object, 
so i cannot assign array to it.

@xieisabug @AntiMoron @liveangela @Ovilia

**Comment by AntiMoron** [comment]
You can force convert that data into an object.

**Comment by hesi726** [comment]
Yes, i do so, but i think the best way is to change code in LineChart.ts.

**Comment by AntiMoron** [comment]
You can see that it's already been declared correctly in the latest code. You can try `npm update`.

```typescript
data?: (
                (void | string | number | SeriesLine.DataObject)[]
                | (void | string | number | SeriesLine.DataObject)[][]
            );
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/91c7ffb876d586c8cf5468119439ce0a40f9bdbd/types/echarts/options/series/line.d.ts#line=2704

**Comment by houxinli** [comment]
> You can see that it's already been declared correctly in the latest code. You can try `npm update`.
> 
> ```ts
> data?: (
>                 (void | string | number | SeriesLine.DataObject)[]
>                 | (void | string | number | SeriesLine.DataObject)[][]
>             );
> ```
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/91c7ffb876d586c8cf5468119439ce0a40f9bdbd/types/echarts/options/series/line.d.ts#line=2704

It seems to be that only the data of the series get fixed rather than the data of the markpoints
