### ISSUE TITLE
[@types/react] Argument of type 'Element' is not assignable to parameter of type 'ReactElement<any>'.

### ISSUE THREAD

**Issue by ethanneff** [DefinitelyTyped/DefinitelyTyped#31734]
`"@types/react": "16.7.13"` works. 
`"@types/react": "16.7.14"` and ``"@types/react": "16.7.18"`` (latest) throws this error.

Using `"typescript": "3.2.2"`.

**Comment by elfinitiy** [comment]
Downgraded to `"@types/react": "16.7.13"

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/c2367fab52cf48fafa9daa915f0714a81d3c122f#diff-96b72df8b13a8a590e4f160cbc51f40c this commit replaced `ValidationMap` to `WeakValidationMap` on `propTypes?` in the following interfaces
```
StatelessComponent
RefForwardingComponent
ComponentClass
```
Only replacing in `RefForwardingComponent` did not create any errors.
The error created is the following:
```
      TS2345: Argument of type 'Element' is not assignable to parameter of type 'ReactElement<any>[]'.
  Type 'Element' is missing the following properties from type 'ReactElement<any>[]': length, pop, push, concat, and 26 more.
```

**Comment by ferdaber** [comment]
Please check to see if you have duplicate React types installed in your `node_modules` first:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17161#issuecomment-446933731

**Comment by ethanneff** [comment]
Adding the following to my `package.json` resolved the issue. 

```js
"resolutions": {
  "@types/react": "16.7.18"
}
```

Seems pretty silly that we need an override just to upgrade a type definition. Shouldn't this be a breaking change?

**Comment by ferdaber** [comment]
The DT repository does not follow semver, so all changes are potentially breaking changes. That said the react types gets affected by duplicated versions more often because it's a fairly central dependency to most component libraries.

**Comment by ethanneff** [comment]
Okay. Good to know. Thanks for the help!

**Comment by elfinitiy** [comment]
Adding the `resolutions` did solve my issue.
But somehow `yarn remove @types/react` + `yarn add @types/react` did. It definitely looks like multiple-react-types issue.

**Comment by mansi7771** [comment]
So there is no other way to solve this than to put "resolutions"? 

As mentioned by @elfinitiy I did
npm remove @types/react + npm add @types/react

However, it still didn't work for me. 

all my children props are breaking after upgrading to react 16.9.0 and throwing this same error

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
