### ISSUE TITLE
Add Typescript 3 support for @types/youtube

### ISSUE THREAD

**Issue by derschnee68** [DefinitelyTyped/DefinitelyTyped#31753]
I have updated my code to Typescript 3, and now I get the following error:
```ReferenceError: YT is not defined```

I also see in @types/youtube package that current typing is for Typescript 2.1
```// TypeScript Version: 2.1```

I think the issue is related, but I don't know more. Maybe someone else has the same problem ?

**Comment by lancedikson** [comment]
@derschnee68, have you managed to find a fix for it? We ran into the same issue now and can't find a quick fix for it.
