### ISSUE TITLE
[yargs] Object is of type 'unknown'

### ISSUE THREAD

**Issue by pc-jedi** [DefinitelyTyped/DefinitelyTyped#31785]
- [x] I tried using the `@types/yargs` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @poelstra, @mizunashi-mana, @pushplay, @jeffkenney, @JimiC, @tkazec, @steffenvv

Since version 12.0.3 and higher it is not possible to pass in `process.argv` as described here:
https://github.com/yargs/yargs/blob/master/docs/api.md#api

Example:
```typescript
import * as yargs from 'yargs';

const args: string[] = ['--update']

const argv = yargs(args)
        .boolean('update')
        .boolean('extern')
        .argv;
```

Error: `TS2571: Object is of type 'unknown'.`

**Comment by steffenvv** [comment]
Thanks for reporting this, @pc-jedi! The return type was indeed wrong for the case when you call yargs with an argument list, declaring that the parsed arguments would be returned, instead of the parser. I have just created a PR with the fix.

**Comment by pushplay** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31791 is approved.  The fix should go out soon.
