### ISSUE TITLE
Suggestion: Separate repos for the types

### ISSUE THREAD

**Issue by smac89** [DefinitelyTyped/DefinitelyTyped#31794]
Can we try something with this giant repo where we split out all the types into seperate repos all still within `DefinitelyTyped`? :man_shrugging:

The names will of course have to change to something that doesn't use `@` symbol anymore. Maybe `types-node`, `types-react`, etc.

---

The only problem I can think of is if there are **types that rely on other types** within this repo, then there might be issues. I think this problem can be solved by including the dependency in `package.json`.

There is also the issue of the sheer **magnitude of such undertaking**. I also don't see this as too much of a threat seeing as this is a website full of devs and github api is free, so I'm sure there exists a script somewhere to do this.

---

Anyways, what do people think of this? Is it possible or not? What about publishing to NPM; does this affect that process in any significant way :question:

**Comment by DanielRosenwasser** [comment]
Check out the conversation over at #25748 regarding this.
