### ISSUE TITLE
@types/hapi - RouteOptionsResponseSchema doesn't include References

### ISSUE THREAD

**Issue by ryuuji3** [DefinitelyTyped/DefinitelyTyped#31826]
- [x] I tried using the `@types/hapi` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick @jhsimms @rafaelsouzaf @saboya

Currently I am trying to define the route options and use a Joi reference. This behavior has worked in hapi-swagger previously.

```ts
const route: Hapi.ServerRoute = {
   // ...
   options: {
      validate: {
          query: {
            param1: Joi.ref("a.b"),
            param2: Joi.ref("$x")
         } 
      }
   }
}
```

However, it appears that `Reference`- is not included in `RouteOptionsResponseSchema`
```ts
export type RouteOptionsResponseSchema =
    boolean
    | ValidationObject
    | AnySchema
    | ((value: object | Buffer | string, options: ValidationOptions) => Promise<any>);
```

Would it make sense to include it?

**Comment by SimonSchick** [comment]
Technically everything that you can pass to `Joi.object` can be passed here...

**Comment by ryuuji3** [comment]
To be clear, the above attempt to use a Joi reference gave the following type error. If you meant there should be no reason it can't, I'll be happy to submit an MR. I just didn't know enough about it to do so.

```
Type '{ tags: string[]; handler: () => string; validate: { query: { param1: Reference; param2: Reference; }; }; }' is not assignable to type 'RouteOptions | ((server: Server) => RouteOptions)'.
  Type '{ tags: string[]; handler: () => string; validate: { query: { param1: Reference; param2: Reference; }; }; }' is not assignable to type 'RouteOptions'.
    Types of property 'validate' are incompatible.
      Type '{ query: { param1: Reference; param2: Reference; }; }' is not assignable to type 'RouteOptionsValidate'.
        Types of property 'query' are incompatible.
          Type '{ param1: Reference; param2: Reference; }' is not assignable to type 'RouteOptionsResponseSchema'.
            Type '{ param1: Reference; param2: Reference; }' is not assignable to type 'ValidationObject'.
              Property 'param1' is incompatible with index signature.
                Type 'Reference' is missing the following properties from type 'AnySchema': validate, allow, valid, only, and 25 more.ts(2322)
index.d.ts(3162, 5): The expected type comes from property 'options' which is declared here on type 'ServerRoute'
(property) ServerRoute.options?: Hapi.RouteOptions | ((server: Hapi.Server) => Hapi.RouteOptions)
additional route options. The options value can be an object or a function that returns an object using the signature function(server) where server is the server the route is being added to and this is bound to the current realm's bind option.
```

**Comment by saboya** [comment]
Taking a quick look, the fastest solution would be to use `JoiObject` from `joi` instead of `AnySchema`. Not sure if that's the desirable route though.

Maybe we should use `Schema` instead and add `| Reference` to it. For type completion purposes, that might be the best solution.

**Comment by ryuuji3** [comment]
I'll test that out and put together an MR. Thank you!

**Comment by ryuuji3** [comment]
Thank you!
