### ISSUE TITLE
relay-runtime: `QueryResponseCache` support

### ISSUE THREAD

**Issue by artola** [DefinitelyTyped/DefinitelyTyped#31827]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/relay-runtime` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @voxmatt @alloy 

If you do not mention the authors the issue will be ignored.

Actual typings for version `1.3.0` (and still valid for newest 1.4.0 to 1.7.0) miss `QueryResponseCache `.

I augmented it by adding:

```ts
import * as RelayRuntime from 'relay-runtime';

declare module 'relay-runtime' {
  export class QueryResponseCache {
    constructor(options: {size: number; ttl: number});
    clear(): void;
    get(queryID: string, variables: Variables): QueryPayload | null;
    set(queryID: string, variables: Variables, payload: QueryPayload): void;
  }
}
```

Does it makes sense a PR ?

**Comment by alloy** [comment]
Sure, please do 👍

**Comment by artola** [comment]
PR created: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31841

**Comment by alloy** [comment]
👍
