### ISSUE TITLE
[@types/config] config.get is not a function

### ISSUE THREAD

**Issue by EricChoiKR** [DefinitelyTyped/DefinitelyTyped#31830]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/config` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @RWander @forrestbice @albertovasquez 

**On Node.js 8.11.1, NPM 6.5.0**
typescript@3.2.2
ts-node@7.0.1
config@3.0.1
@types/config@0.0.34

I was using before(TS@2.x):
```typescript
import * as config from "config";
config.get("key")
```
but, there is error in current version as follow:
```
TypeError: config.get is not a function
```

Can you check this?

**Comment by BendingBender** [comment]
You have to import this module like this:
```typescript
import config = require("config");
```

**Comment by EricChoiKR** [comment]
@BendingBender 
I read it but that solution is seems like a kind of expedient.
Impossible to solve it basisly?

**Comment by BendingBender** [comment]
Sorry, I'm not sure what you mean. Did you try the solution? Did it work for you?

**Comment by EricChoiKR** [comment]
Yeah, it does work, but I want to run too: ```typescript import * as config from "config"; ```

**Comment by BendingBender** [comment]
Then use either the `--allowSyntheticDefaultImports` or `--esModuleInterop` compiler option.

**Comment by EricChoiKR** [comment]
@BendingBender Thank you very much!

**Comment by erwanlbp** [comment]
If someone see this error : 
Be sure to import config with `import config from 'config';` instead of `import * as config from 'config';` ...
Too many hours lost
