### ISSUE TITLE
[@types/recompose] ComponentEnhancer does not pass through props of passed in component

### ISSUE THREAD

**Issue by roman-balzer** [DefinitelyTyped/DefinitelyTyped#31885]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @iskandersierra @clayne11 @Pajn @lucasterra @brian-lives-outdoors  @TiuSh 

I'm currently trying to get recompose into my react codebase. Therefore I was trying to get some basic things working, and I got it working, but I'm not really sure, if this is the correct way recompose is intended to work.

So I have following Code:

    interface Value {
      value: string
    }

    interface Loading {
      loading: boolean
    }
    
    const TestComponent = (props: Value) => <div>Value: {props.value}</div>
    const LoadingComponent = () => <div>Loading ...</div>

So I have a TestComponent, which should display the Value provided in the props, and additionaly I have a LoadingComponent, which should be shown, when the loading props is set.

So I used the `branch` function of recompose

    const withLoading = branch<Loading>(
      ({loading}) => loading, 
      renderComponent(LoadingComponent)
    ) 

Now when I use `withLoading`on **any Component without props** I can set the loading prop on them.

    const EnhancedCompWithLoading = withLoading(SomeCompWithoutProps)
    
    render() {
      return <EnhancedCompWithLoading loading={this.state.loading} />
    }

This works fine for me, the real problem starts when trying to use this with Components with props. When I try it like this:

    const TestWithLoading = withLoading(TestComponent)
    
    render() {
      return <TestWithLoading value="testVal" loading={this.state.loading} />
    }

I get the ErrorMessage `TS2339: Property 'value' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<Loading, any, any>>
& Readonly<{ children?: ReactNode; }> & Readonly<Loading>'.`

So I looked the type definition in @types/recompose up. `branch<TOutter>` returns a `ComponentEnhancer<any,TOutter>`. Which I understand, I want to be able to provide `any` component, and the `<TOutter>` generic is so, that the resulting component knows about the needed props for the test function. Thats also working without additionals props.

However the TypeDefinition for the ComponentEnhancer looks like this (recompose 0.30.2):

    interface ComponentEnhancer<TInner, TOutter> {
      (component: Component<TInner>): ComponentClass<TOutter>
    }

So, the `ComponentEnhancer<any, Loading>` which I received from the previous `branch` function will return a `ComponentClass<Loading>`. However the `<TInner>` of the component I provide to the ComponentEnhancer will be thrown away and I cant use my `Value` props in the Enhanced Component.

I did ask the same thing on [StackOverflow](https://stackoverflow.com/questions/54025204/correct-typing-for-higherordercomponents-with-recompose-and-typescript) . There was an answer by Titian Cernicova-Dragomir, with a different Type Definition, which would fix my issue. Or is it intented not to be able to pass the props of the passing in component?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
