### ISSUE TITLE
[@types/jquery] Cannot specify type for variable

### ISSUE THREAD

**Issue by cawa-93** [DefinitelyTyped/DefinitelyTyped#31891]
- [x] Authors: @leonard-thieu
@borisyankov
@choffmeister
@Steve-Fenton
@Diullei
@tasoili
@jasons-novaleaf
@seanski
@Guuz
@ksummerlin
@basarat
@nwolverson
@derekcicerone
@AndrewGaspar
@seikichi
@benjaminjackman
@s093294
@JoshStrobl
@johnnyreilly
@DickvdBrink
@King2500
@terrymun

### My code example ###
```js
/** @type {JQuery<HTMLBodyElement>} */
const $body = jQuery('body')
const firstAnchor = $body.find('a').first()
```
`firstAnchor` has `JQuery<HTMLBodyElement>`

![image](https://user-images.githubusercontent.com/1662812/50686682-ffec7900-1026-11e9-9727-b0e2a0682ef3.png)

And if I try change type then I get error:
```
Type 'JQuery<HTMLBodyElement>' is not assignable to type 'JQuery<HTMLAnchorElement>'.
  Type 'HTMLBodyElement' is missing the following properties from type 'HTMLAnchorElement': charset, coords, download, hreflang, and 20 more.ts(2322)
```
![image](https://user-images.githubusercontent.com/1662812/50686722-2a3e3680-1027-11e9-9cd5-03d05f608a73.png)

How do I specify the types for variables that do not cause errors?

**Comment by King2500** [comment]
Have you tried `@var` instead of `@type` ?
