### ISSUE TITLE
[@types/recompose] withHandlers forces you to leak outer props into the inner props

### ISSUE THREAD

**Issue by akomm** [DefinitelyTyped/DefinitelyTyped#31893]
- [x] I tried using the `@types/recompose` package and had problems.
- Authors: @iskandersierra @clayne11 @Pajn @lucasterra @brian-lives-outdoors @TiuSh

`withHandlers` forces you to leek outer props into inner.

I have to use intersection on my inner component:

```tsx
class TextInput extends React.PureComponent<OuterProps & InnerProps, {}> {}
```

Otherwise I get a type mismatch TS error, that stuff in __OuterProps__ is missing in ComponentType\<__InnerProps__\>.

I could fix the issue, with validation checks still working by changing the following:

```ts
    export function withHandlers<TOutter, THandlers>(
        handlerCreators:
            | HandleCreators<TOutter, THandlers>
            | HandleCreatorsFactory<TOutter, THandlers>
    ): InferableComponentEnhancerWithProps<THandlers & TOutter, TOutter>;
```

to:

```ts
    export function withHandlers<TOutter, THandlers>(
        handlerCreators:
            | HandleCreators<TOutter, THandlers>
            | HandleCreatorsFactory<TOutter, THandlers>
    ): InferableComponentEnhancerWithProps<THandlers, TOutter>;
```

Type-checking still works in all cases I have tested. Did not PR because not sure how you handle versions here and especially when there is maybe BC break.

*edit*
I think it is also important to note, that the issue is obvious once you remap equally named outer prop to an inner prop. The resulting type is an intersection of the props outer and inner type.

**Comment by TiuSh** [comment]
Actually the props are coherent with what the code from `recompose#withProps` really do: it merges the props it receives with the handlers that it creates. See my comment https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31429#issuecomment-451493274 for further details.

**Comment by akomm** [comment]
I read your post. I was going through exactly same thinking procedure, funny :). I realized that `withProps` actually passes through outer props and was almost done thinking that this is an issue, when I realized it actually still is.

1. The way intersection works in TS, when properties of intersected types are equally named:

```ts
type A = {
  handler: (x: number) => void,
};

type B = {
  handler: (x: string) => void,
};

type C = A & B; // {handler: ((x: number) => void) & ((x: string) => void)}

function works(c: C) {
  c.handler(10); // works
  c.handler("string"); // works
}
```

You see how it does not make any sense? Like many hocs, withProps shadows inner props with equally named outer props.

2. JS behavior should not be mapped to expected TS behavior 1:1 in regards to typing. While you can in plain JS(X) do this:
```jsx
<Component propDoesNotExist />
```
You can not do this in TS(X) without type checker error. This is because you are only allowed to pass in props, which are specified! Therefore your case described in the comment is already covered without OuterProps intersection required. To be allowed to pass through outer props to the inner component's props, this outer props must actually be part of the inner props already.

**Comment by TiuSh** [comment]
Oh your right ! I didn't think about "conflicting" intersections !... 😓 

But it could be easily fixed with a `Merge<T1, T2>` type:
```typescript
type Merge<T1, T2> = Pick<T1, Exclude<keyof T1, keyof T2>> & T2;

type A = {
  value: number;
  handler: (x: number) => void;
  handlerA: (y: boolean) => void; 
};

type B = {
  value: string;
  handler: (x: string) => void;
  handlerB: (y: boolean) => void;
};

type C = Merge<A, B>;

function works(c: C) {
  // A typings
  const a: number = c.value; // doesn't work
  c.handler(10); // doesn't work
  c.handlerA(true); // works

  // B typings
  const b: string = c.value; // works
  c.handler("string"); // works
  c.handlerB(false); // works
}
```

So the correct typing for `withProps` should be:
```typescript
    export function withHandlers<TOutter, THandlers>(
        handlerCreators:
            | HandleCreators<TOutter, THandlers>
            | HandleCreatorsFactory<TOutter, THandlers>
    ): InferableComponentEnhancerWithProps<Merge<TOutter, THandlers>, TOutter>;
```

But I strongly think that we should explicitly merge outter props to the one generated by the HOC ! Otherwise this type of errors won't be catched:
```typescript
interface ComponentProps {
  value: string;
  onChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
}

const Component: React.SFC<ComponentProps> = ({ value, onChange }) => (
  <input onChange={onChange} value={value} />
);

interface OutterProps {
  value: number;
  onChange: (value: string) => void;
}

interface Handlers {
  onChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
}

const enhance = withHandlers<OutterProps, Handlers>({
  onChange: ({ onChange }) => e => onChange(e.target.value)
});

enhance(Component); 
// Error: 
// Argument of type 'FunctionComponent<ComponentProps>' is not assignable to parameter of type 'ComponentType<Merge<OutterProps, Handlers>>'.
//  Type 'FunctionComponent<ComponentProps>' is not assignable to type 'FunctionComponent<Merge<OutterProps, Handlers>>'.
//    Type 'ComponentProps' is not assignable to type 'Merge<OutterProps, Handlers>'.
//      Types of property 'value' are incompatible.
//        Type 'string' is not assignable to type 'number'.
```

**Comment by akomm** [comment]
I see a huge flaw in this approach. Let me explain why.

In short, it dismantles:
1. The idea and benefits behind compositions.
2. TSX property validation logic.


In detail:
1. You are coupling the inner layer to the outer layer. Your example is a 1:1 definition/usage relation. The moment you start to create new components enhancing the same one, you get into trouble, because the inner/base component is now coupled to which outer interface? And why does it even know about other components using it? Its an bottom up relation you are creating here which kills the purpose of compositions. If you think now "OuterProps can be a generic", this starts getting monkey-patching direction, because why should a component define arbitrary generics, just in case it might get enhanced one day? What if it is a library?

2. Lets take `withHandlers` because its the topic. Its behavior behavior is to:
- take **any** props in,
- use handler creators to create the handler properties,
- merge the handler properties over all received props,
- then pass ALL the resulting props to the inner component. 

This is valid in JSX. But passing in **any** props to the inner component is an error in TSX. Now who decides which properties are allowed to be passed to the inner component? Obviously the inner component itself and not the outer! But the inner component should not care about outer components interfaces! (as explained in 1.)

So having to specify the outer props on the inner component is basically a monkey-patch approach to the problem.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
