### ISSUE TITLE
[styled-components] Typedef for styled-components

### ISSUE THREAD

**Issue by Werter12** [DefinitelyTyped/DefinitelyTyped#31964]
- [x] I tried using the `@types/styled-components: ^4.1.4` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @Lavoaster 
1. What typedefs should I use for the styled-components except any? 
```
export const BaseButton: React.FunctionComponent<IStyledButtonProps> = props => {
  const { children, className, icon, onClick, disabled, type, variant, dataAttributes } = props;
  const dataAttrs: IDataAttributeMap = mapWithDataPrefix(dataAttributes);

  return (
    <button disabled={disabled} onClick={onClick} type={type} className={className} {...dataAttrs}>
      <span>{children}</span>
      {icon && (
        <Icon
          wrapperStyle={css`
            min-height: ${IconScale.m};
            min-width: ${IconScale.m};
            padding-left: 8px;
          `}
          name={icon}
          size={IconScale.m}
          fillColor={
            variant === ButtonVariant.primary ? falconTheme.color.white : falconTheme.color.black
          }
        />
      )}
    </button>
  );
};
export const Button = styled(BaseButton)`
  background: ${({ theme, variant }) => buttonVariant[variant].background.default(theme)};
  border: ${({ theme, variant }) => buttonVariant[variant].border.default(theme)};
  box-shadow: ${({ theme, variant }) => buttonVariant[variant].boxShadow.default(theme)};
  color: ${({ theme, variant }) => buttonVariant[variant].color(theme)};
`;
```
I am getting the following error: **Expected variable-declaration: 'Button' to have a typedef**

**Comment by Igorbek** [comment]
Is that different from #31970? Please provide full reproducible code.

**Comment by Werter12** [comment]
Yes, this is different  from  #31970 . This issue is more general. Whatever component I creating with `styled` function I the **Expected variable-declaration:'to have a typedef** error is trowed, due to the `typedef` tslint rule and I am wondering what type for typedef should I use except any.
