### ISSUE TITLE
[@types/socketcluster-server] missing some definitions

### ISSUE THREAD

**Issue by ishantiw** [DefinitelyTyped/DefinitelyTyped#31969]
I want to use functions related to [@types/socketcluster-server](https://www.npmjs.com/package/@types/socketcluster-server) but some of them are missing its definition.

For example, I tried to use `close()`([scserver.js#L595](https://github.com/SocketCluster/socketcluster-server/blob/master/scserver.js#L595)) on SCServer but its definition is not present

```javascript
import http from 'http';
import { attach, SCServer, SCServerSocket } from 'socketcluster-server';

const scServer =  attach(http.createServer());

scServer.close(() => { // Error: Property 'close' does not exist on type 'SCServer'
  // do something
  });
```

Similar to this, there are more definitions in `SCServer` which are missing are listed below.

`getPath`
`generateId`
`removeMiddleware`
`verifyHandshake`
`verifyInboundEvent`
`isAuthTokenExpired`
`verifyOutboundEvent`

 Authors: @DanielRose

**Comment by ishantiw** [comment]
@DanielRose Thanks, appreciate your help 👍

**Comment by DanielRose** [comment]
PR is in and accepted: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32136

**Comment by ishantiw** [comment]
Thanks @DanielRose 👍
