### ISSUE TITLE
[styled-components] Interface is not satisfied by constrains in the styled-component

### ISSUE THREAD

**Issue by Werter12** [DefinitelyTyped/DefinitelyTyped#31970]
- [x] I tried using the `@types/styled-components: ^4.1.4` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @Lavoaster 

I am trying to pass interface IStyledButtonProps but receive error that I IStyledButtonProps not satisfied by constrains 
```
export const BaseButton: React.FunctionComponent<IStyledButtonProps> = props => {
  const { children, className, icon, onClick, disabled, type, variant, dataAttributes } = props;
  const dataAttrs: IDataAttributeMap = mapWithDataPrefix(dataAttributes);

  return (
    <button disabled={disabled} onClick={onClick} type={type} className={className} {...dataAttrs}>
      <span>{children}</span>
      {icon && (
        <Icon
          wrapperStyle={css`
            min-height: ${IconScale.m};
            min-width: ${IconScale.m};
            padding-left: 8px;
          `}
          name={icon}
          size={IconScale.m}
          fillColor={
            variant === ButtonVariant.primary ? falconTheme.color.white : falconTheme.color.black
          }
        />
      )}
    </button>
  );
};
export const Button = styled<IStyledButtonProps>(BaseButton)`
  background: ${({ theme, variant }) => buttonVariant[variant].background.default(theme)};
  border: ${({ theme, variant }) => buttonVariant[variant].border.default(theme)};
  box-shadow: ${({ theme, variant }) => buttonVariant[variant].boxShadow.default(theme)};
  color: ${({ theme, variant }) => buttonVariant[variant].color(theme)};
`;
```
**Error:** Type 'IStyledButtonProps' does not satisfy the constraint '"symbol" | "object" | "button" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | "canvas" | ... 152 more ... | FunctionComponent<...>'.
  Type 'IStyledButtonProps' is not assignable to type 'FunctionComponent<any>'.
    Type 'IStyledButtonProps' provides no match for the signature '(props: any, context?: any): ReactElement<any>

**Comment by Igorbek** [comment]
How is `BaseButton` defined? What is it type?
Could you please provide a full repro code?

**Comment by AmirTugi** [comment]
What was the fix for this?
Why was this closed?

**Comment by atvorch** [comment]
> What was the fix for this?
> Why was this closed?
> 
> I'm having the same issue

Have you found the solution?

**Comment by AmirTugi** [comment]
I ended up defining the component outside of the styled and then making a different component which is wrapping the first one with `styled`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
