### ISSUE TITLE
[@types/async] AsyncResultCallback<T, E = Error> doesn't respect async.waterfall variadic results

### ISSUE THREAD

**Issue by logicbomb421** [DefinitelyTyped/DefinitelyTyped#31984]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @notarseniy @Penryn @fenying @pascalmartin 

If you do not mention the authors the issue will be ignored.

<hr />

It appears the definition for `AsyncResultCallback` does not handle the potential for variadic results when using `async.waterfall`. For example, in javascript, the following works:

```js
const async = require('async');
async.waterfall(
  [
    cb => async.setImmediate(cb.bind(null, null, 1, 2)),
    (arg1, arg2, cb) => async.setImmediate(cb.bind(null, null, arg1, arg2, 3, 4))
  ],
  (err, one, two, three, four) => {
    console.log(one);
    console.log(two);
    console.log(three);
    console.log(four);
  }
);
```
Which produces the output:
```
1
2
3
4
```
However, when attempting to convert this to TypeScript, tsc errors on the callback signature with the following:
> error TS2345: Argument of type '(err: any, one: any, two: any, three: any, four: any) => void' is not assignable to parameter of type 'AsyncResultCallback<any, any>'.

Looking into this a bit, I'm not even sure TS has the concept of variadic types (how could it know the number of arguments resolved at runtime during compile?). I can resolve this in my code by returning an array, but I'm not sure if this is a bug in the type definition, or simply not possible overall.

Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
