### ISSUE TITLE
Using typesVerisons

### ISSUE THREAD

**Issue by screendriver** [DefinitelyTyped/DefinitelyTyped#31983]
In my latest pull request the Travis build complains with `Error: Don't use // TypeScript Version for newer TS versions, use typesVerisons instead.`

Unluckily I can't find anything about that 🤔  Could anyone please help me with that? Where and how can I put this information into?

**Comment by nikolay-borzov** [comment]
I found some info [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html)

**Comment by BendingBender** [comment]
Just look at the typedefs for `debounce-promise` or `create-html-element` if you need examples of how to do it.

**Comment by BendingBender** [comment]
How's about this:

#### I want to use features from TypeScript 3.1 or above.

For a full explanation of how to do it, you can read it up on the [official TypeScript documentation](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html).

Here's a short explanation to get you started.

1. You'll have to add a `package.json` file to your package definition, with 
the following contents:

```json
{
    "private": true,
    "types": "index",
    "typesVersions": {
        ">=3.1.0-0": { "*": ["ts3.1/*"] }
    }
}
```

2. Create the sub-directory mentioned in the `package.json` inside your types directory (`ts3.1/` in this example) and add the types and tests specific for the new TypeScript version. Don't forget to remove the definition header from the `ts3.1/index.d.ts` file.

3. Correct the `baseUrl` and `typeRoots` options in `ts3.1/tsconfig.json` to look something like this:
```json
{
    "compilerOptions": {
        "baseUrl": "../../",
        "typeRoots": ["../../"],
        ...
    },
    ...
}
```

You can look [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/debounce-promise) and [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/create-html-element) for examples.

**Comment by BendingBender** [comment]
I'll add this as a PR if it's OK.
