### ISSUE TITLE
reactJS setState typings error for extended State

### ISSUE THREAD

**Issue by burtek** [DefinitelyTyped/DefinitelyTyped#31994]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @tkrotoff, @DovydasNavickas, @onigoetz, @theruther4d, @guilhermehubner, @ferdaber, @jrakotoharisoa, @pascaloliv, @hotell, @franklixuefei, @Kovensky, @pshrmn

I think there is something wrong with `setState` typings. I prepared [an example (https://codesandbox.io/s/6wx5zrmvnr)](https://codesandbox.io/s/6wx5zrmvnr) as I'm unable of clearly explaining what I mean.

In short words: Assuming a component with a State type that extends 2 or more interfaces ( either by `type State = A & B` or `interface State extends A, B`), trying to call setState with destructured param of type `A | B` results in typings error:

```
Argument of type '{ a: string; } | { b: string; }' is not assignable to parameter of type 'AppStateInterface | ((prevState: Readonly<AppStateInterface>, props: Readonly<{}>) => AppStateInterface | Pick<AppStateInterface, "a" | "b">) | Pick<AppStateInterface, "a" | "b">'.
  Type '{ a: string; }' is not assignable to type 'AppStateInterface | ((prevState: Readonly<AppStateInterface>, props: Readonly<{}>) => AppStateInterface | Pick<AppStateInterface, "a" | "b">) | Pick<AppStateInterface, "a" | "b">'.
    Type '{ a: string; }' is not assignable to type 'Pick<AppStateInterface, "a" | "b">'.
      Property 'b' is missing in type '{ a: string; }'.
```

**Comment by ferdaber** [comment]
Seems to be a limitation of the `setState` type, it tries to use `Pick` instead of `Partial` to disallow setting `undefined` to non-nullable properties, but at the same time we run into this limitation with union types where the inferred generic type parameter isn't compatible with the parameter type.

The workaround for this would be for you to have to manually assert it:
```ts
// "correct" type
this.setState({ ...state }) as Pick<AppStateType, 'a' | 'b'>)
// this also works, but is not as accurate for more complex state types
this.setState({ ...state }) as AppStateType)
```

**Comment by burtek** [comment]
@ferdaber The second workaround will actually be ok for my callback, thanks.

I now found out there was more discussion about `setState` in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18365

**Comment by ferdaber** [comment]
Thanks for finding it! I was about to link that issue but couldn't find it 😅

**Comment by ericanderson** [comment]
I think you just triggered some PTSD for me 🤣
