### ISSUE TITLE
Can't get attrs to work cleanly with additional props

### ISSUE THREAD

**Issue by AharonDror** [DefinitelyTyped/DefinitelyTyped#32104]
styled-components: 4.1.2
typescript: 3.2.1

I can't seem to manage to use both attrs with additional props.
I've looked at https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28597, and the solution there doesn't work for me. The simplified version of the solution is this:
```
const A = styled.div.attrs<{testMe: string}>({})``;

const Comp = () => <A testMe='DoesNotWork' />
```
And I'm getting an error that I have a type mismatch. Basically saying that A does not have a property called `testMe`.

This however, does work as expected.
```
const A = styled.div<{testMe: string}>``;

const Comp = () => <A testMe='DoesWork' />
```

I can work around this, but it would be much preferable if it could work out of the box instead of having to wrap this component.. An ugly workaround that works is choosing some prop that exists on divElement (even though it's not used) and wrapping the styled-component as follows:
```
const A = styled.div.attrs<{testMe: string}>({})``;

const WrapA = (props: {testMe: string, onClick?: () => void}) => <A {...props} />

const Comp = () => <WrapA testMe='DoesWork' />
```

If `onClick` is removed then the error is that the type {testMe: string} and .... HTMLDivElement have no properties in common. If someone wants to use this workaround, note that you need to define the `onClick` property as an optional property so you won't be forced to pass it as a prop to your component.

@Igorbek, @Igmat, @Lavoaster, @Kovensky ?

**Comment by AharonDror** [comment]
Is it that much of an edge case that no one else needs it?
Running into this issue time and time again...

**Comment by antoinerousseau** [comment]
Try [this](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28597#issuecomment-468339012)

**Comment by KnisterPeter** [comment]
@AharonDror This should work as you expect it:

```ts
const A = styled.div.attrs({})<{testMe: string}>``;

const Comp = () => <A testMe='DoesWork' />
```

**Comment by Igorbek** [comment]
`attrs` provides props for you styled component, they meant to be passed with values. If you want to accept them in a component, use what @KnisterPeter suggested:

```ts
const A = styled.div<{testMe: string}>` css `;
<A testMe='works' />;
```

**Comment by AharonDror** [comment]
Thanks @KnisterPeter ! Slightly surprised I didn't check that placement of the brackets. Don't really understand then why either placements of brackets are possible.
@Igorbek was just trying to simplify the problem. In the issue above I give that exact example as something that does work
