### ISSUE TITLE
Error TS2339 Property bytesWritten does not exist on type zlib.Gunzip/zlib.Inflate

### ISSUE THREAD

**Issue by hanaeddy** [DefinitelyTyped/DefinitelyTyped#32110]
@types/node 10.12.18
tsc 3.2.2

In zlib, bytesWritten is the new name of bytesRead which is deprecated (warning at runtime)
For using bytesWritten, need to add this line in index.d.ts (1784):

    interface Zlib {
        readonly bytesRead: number;
        readonly bytesWritten: number; <==
        close(callback?: () => void): void;

**Comment by Flarna** [comment]
created #32159
