### ISSUE TITLE
[@types/d3-array] Please update to latest version v2.0.3

### ISSUE THREAD

**Issue by piyushgupta1** [DefinitelyTyped/DefinitelyTyped#32162]
Hello,

D3-array has been updated to major version release v2.0.0. I am using this in typescript based lib 

Typescript Version - v3.2.2
Node Version - v8.11.2

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/d3-array` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @gustavderdrache , @borisyankov , @tomwanzek , @denisname

If you do not mention the authors the issue will be ignored.

**Comment by Ledragon** [comment]
Thanks for reporting this, I will try tackling it in the upcoming days (not a promise, but will try my best)

**Comment by maneetgoyal** [comment]
I am using `"d3-array": "^2.2.0",`, can the types be updated please? Getting errors, for instance, the function `groups` is missing from the types.

cc: @gustavderdrache, @borislavjivkov, @tomwanzek, @denisname, @ledragon

**Comment by Ledragon** [comment]
Hi,
Thanks for reporting this. There is actually a lot of work to update all d3 modules to their latest versions... And I am not sure as to how much time any of us can devote to this currently (you might have noticed that not much has been done recently). Feel free to submit a PR to update the types. I can try fitting this one in my schedule, but cannot promise anything...

**Comment by maneetgoyal** [comment]
@Ledragon Thanks for the prompt response. Can you please share the steps to generate type definition from the [source files](https://github.com/d3/d3-array)? Will be useful for creating PRs for other devs, if you're not able to update the definitions by yourself.

**Comment by Ledragon** [comment]
Actually slower on the second reply :-)
Not sure I have "steps" to provide. The way I tend to do these is by reading the documentation, adding the definitions in the types, and adding associated tests. I never personally used the original source to extract definitions automatically. I go read the original code when I am unsure about the types of the parameters or the like.

**Comment by chriszrc** [comment]
Any updates here? Are we really the only 4 people in the world using d3-array in typescript?

**Comment by Ledragon** [comment]
Sorry, time is tight, and as I don't use v5 much these days, this has become a lesser priority... But this stays on my mind still

**Comment by Schizzomarino** [comment]
That would be real good @Ledragon and all other contributors.
I find the d3 data-churning functions so clean and efficient; very handy for keeping code clean and fast.
We now have type definitions for all the functions, but none seem to account for spread arguments (for example using two keys with rollup will throw an error saying that only 3 arguments were expected.
I have tried to change/play with the type definitions in d3-array/index.d.ts but it is unfortunately beyond my skill level...

**Comment by maneetgoyal** [comment]
@Schizzomarino, @chriszrc  Would you guys be able to help with providing the test cases (in `d3-array-tests.ts`) for the latest `d3-array v2.4.0` version? I have started updating to `2.4.0` compatible definitions on a separate [fork](https://github.com/maneetgoyal/DefinitelyTyped/tree/maneet/d3-array-2.4) (will be a very big task to contribute definitions for all the missing versions, so focussing on the latest one only). Apart from **factoring in the spread arguments** in some places, some functions are also missing from the current type definitions:

1. Statistics
- [x] `minIndex`
- [x] `maxIndex`
- [x] `cumsum`
- [x] `quantileSorted`

2. Search
- [ ] `least`
- [ ] `leastIndex` (`scan` is deprecated)
- [ ] `greatest`
- [ ] `greatestIndex`
- [ ] `bisect` (same as `bisectRight`)

3. Transformations
- [ ] `groups`
- [ ] `rollups`
- [ ] `count`

4. Bins
- [ ] `bin` (`histogram` is deprecated)

---

- The typings for the checked ones are included so far in that fork, but they are currently missing test cases. 
- Will now target to update the **Search** functions from above in the next few days. Not a priority for me too currently, so pushing code only when I can find the time.
- Was hoping that if some of us users can split certain tasks like writing test cases, checking what needs to be updated, updating the typings, etc., we might be able to pull it more quickly. 
- Following @Ledragon's [suggestion](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/32162#issuecomment-525394567) and comparing the missing definitions with existing ones seems to be quite effective so far.

**Comment by Ledragon** [comment]
Thanks for the effort!

I think there is a need to resync all versions of all modules with the existing ones, including the global d3 types bundle. I'll try taking care of that shortly, so that we can try and see where we stand and how to move

**Comment by maneetgoyal** [comment]
Hi @Ledragon, is there any road-map on how to move forward on this? (Willing to help out with anything (testing, coding, etc.) if you have other commitments at the moment.)

**Comment by Ledragon** [comment]
@maneetgoyal Update of all d3 types is monitored in #38939; I would suggest to close this and track everything there, if ok for you

**Comment by maneetgoyal** [comment]
That’s great @Ledragon. Tagging the OP @piyushgupta1 regarding your suggestion.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
