### ISSUE TITLE
[@types/luxon]  -  toRelative doesnot exist on DateTime

### ISSUE THREAD

**Issue by shajeeck** [DefinitelyTyped/DefinitelyTyped#32213]
- [x] I tried using the `@types/luxon` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @colbydehart @FourwingsY @jsiebern @mastermatt 

[@types/luxon]  -   toRelative, toRelativeCalendar does not exist on DateTime mentioned at
https://moment.github.io/luxon/docs/manual/moment.html#humanization

**Comment by mastermatt** [comment]
@shajeeck those methods were only added a couple days ago in [v1.19](https://github.com/moment/luxon/blob/master/changelog.md#190).

I'm working on a PR now to add the types here.
