### ISSUE TITLE
@types/enzyme - missing type definition for renderProp

### ISSUE THREAD

**Issue by lnhrdt** [DefinitelyTyped/DefinitelyTyped#32234]
Enzyme v3.8.0 released the `renderProp` feature from airbnb/enzyme#1863. It looks like the types haven't caught up with the new feature yet.

CC: airbnb/enzyme#1863 committers: @dferber90 / @ljharb

CC: Enzyme definitions authors: @MarianPalkus / @NoHomey / @jwbay / @huhuanming / @MartynasZilinskas / @thovden / @Hotell

**Comment by lnhrdt** [comment]
This was resolved in #32963. Thanks @aputinski!

**Comment by yurii-sorokin** [comment]
According to [docs](https://airbnb.io/enzyme/docs/api/ReactWrapper/renderProp.html) `ReactWrapper` also supports `renderProp`
