### ISSUE TITLE
[@types/lodash/fp]: Wrong definition for `mapKeys`

### ISSUE THREAD

**Issue by GerkinDev** [DefinitelyTyped/DefinitelyTyped#32247]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel, @chrootsu, @stepancar, @aj-r, @Ailrun, @e-cloud, @thorn0, @jtmthf, @DomiR

If you do not mention the authors the issue will be ignored.

----

Hello gentle people contributing to this repository!

I'm having a problem with a FP function definition for `lodash`: it seems that the value we iterate on is expected to be an array, but according to [lodash's documentation](https://lodash.com/docs/4.17.11#mapKeys), it should be an object/dictionary

Here is a minimalist repro I made:

```ts
import {mapKeys} from 'lodash/fp';

const out = mapKeys( k => k.toUpperCase() )( { foo: 1, bar: 2 } );
```
> Argument of type '{ foo: number; bar: number; }' is not assignable to parameter of type 'ArrayLike<{}>'.
> Object literal may only specify known properties, and 'foo' does not exist in type 'ArrayLike<{}>'.

Is that intended ? Did I misused this function ?

Thank you for your work, and cheers! 🍻

**Comment by aj-r** [comment]
It looks like it's grabbing the first overload:

```
(iteratee: lodash.ValueIteratee<number>): LodashMapKeys1x1;
```

What you really want is the 4th overload:

```
(iteratee: lodash.ValueIteratee<string>): LodashMapKeys2x1;
```

Ideally I think we should change the order of these overloads so the `string` one is used by default. That may not be a straightforward change though.

As a workaround, can you specify an explicit type for your callback parameter? e.g.

```
const out = mapKeys( (k: string) => k.toUpperCase() )( { foo: 1, bar: 2 } );
```

The `fp` types are a bit rough, so in general you'll probably need to be very explicit like this.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
