### ISSUE TITLE
 [@types/socketcluster-server] missing some definitions for SCServerSocket

### ISSUE THREAD

**Issue by ishantiw** [DefinitelyTyped/DefinitelyTyped#32246]
I want to use functions related to [@types/socketcluster-server](https://www.npmjs.com/package/@types/socketcluster-server) but some of them are missing its definition. This is issue is similar to #31969 , thanks to @DanielRose on that.

For example, I tried to use `destroy()`([scserversocket.js#L595](https://github.com/SocketCluster/socketcluster-server/blob/master/scserversocket.js#L274)) on SCServerSocket but its definition is not present

```typescript
import http from 'http';
import { attach, SCServerSocket } from 'socketcluster-server';

const scServer =  attach(http.createServer());
scServer.on('connection',
  (socket: SCServerSocket): void => {
     socket.destroy() // Destroy is not a function in socket (SCServerSocket)
  }
```

Similar to this, there are more definitions in `SCServerSocket` which are missing are listed below.

`terminate`
`sendObjectBatch`
`encode`
`decode`
`sendObjectBatch`
`sendObject`
`deauthenticateSelf`
`triggerAuthenticationEvents`

 Authors: @DanielRose

**Comment by DanielRose** [comment]
I'm very busy right now; I'll take a look next week.

**Comment by DanielRose** [comment]
PR is in: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32589

**Comment by ishantiw** [comment]
PR got merged, Thanks @DanielRose for your help 👍
