### ISSUE TITLE
[@types/smtp-server] Type issues

### ISSUE THREAD

**Issue by MrXyfir** [DefinitelyTyped/DefinitelyTyped#32263]
- [x] I tried using the `@types/smtp-server` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

@markisme @Taisiias @dex4er 

```ts
import { SMTPServer } from 'smtp-server';

new SMTPServer({
  onData(stream, session, callback) {
    // [ts] Property 'sizeExceeded' does not exist on type 'Readable'. [2339]
    if (stream.sizeExceeded) return callback(new Error('Message too big'));

    // [ts] Property 'address' does not exist on type 'false | SMTPServerAddress'.
    //      Property 'address' does not exist on type 'false'. [2339]
    if (session.envelope.mailFrom.address == 'foo@bar.com') return callback();
  })
});
```

**Comment by dex4er** [comment]
@MrXyfir 

What is this `sizeExceeded`? There is no such property in `Readable` class.

For second error: `mailFrom` is a monad type `false | SMTPServerAddress`. It means that you have to check first if expression is true before accessing any properties:

```ts
if (session.envelope.mailFrom && session.envelope.mailFrom.address === 'foo@bar.com') return callback();
```

**Comment by MrXyfir** [comment]
See https://nodemailer.com/extras/smtp-server/#using-size-extension for `sizeExceeded`.

> When creating the server you can define maximum allowed message size with the size option, see RFC1870 for details. This is not a strict limitation, the client is informed about the size limit but the client can still send a larger message than allowed, it is up to your application to reject or accept the oversized message. To check if the message was oversized, see stream.sizeExceeded property.

Good to know about `mailFrom`. That's basically what I ended up doing but I thought there might be a better way to handle it.

I'm assuming you're referring to `onData: (...) => {` vs `onData(...) {`? Either syntax works fine, that's not an issue.

**Comment by dex4er** [comment]
@MrXyfir ah I got it. So it means we need to introduce some new interface for this stream because this is not a simple `Readable`.
