### ISSUE TITLE
preventDefault() and isDefaultPrevented() missing from slickgrid.d.ts

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/DefinitelyTyped#3228]
In slickgrid.d.ts 

https://github.com/borisyankov/DefinitelyTyped/blob/master/slickgrid/SlickGrid.d.ts#L44 

It is mentioned in comments above class `EventData` that 

_“This is pretty much identical to how W3C and jQuery implement events.”_

However, the following functions that are in events implementation of jQuery and W3C are missing in slickgrid.

`isDefaultPrevented()` in jquery.d.ts
https://github.com/borisyankov/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L525

`preventDefault()` in jquery.d.ts
https://github.com/borisyankov/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L530 

I found this out when I was trying to write something similar to the context menu example of slickgrid

https://github.com/mleibman/SlickGrid/blob/gh-pages/examples/example7-events.html#L100

Another example where slickgrid uses `preventDefault()` would be 

https://github.com/mleibman/SlickGrid/blob/master/slick.groupitemmetadataprovider.js#L95
or
https://github.com/mleibman/SlickGrid/blob/master/slick.groupitemmetadataprovider.js#L119

There are some good explanations and examples of the uses of `preventDefault()` in these articles and discussions –

http://www.w3.org/TR/DOM-Level-2-Events/events.html 
`preventDefault`
_If an event is cancelable, the preventDefault method is used to signify that the event is to be canceled, meaning any default action normally taken by the implementation as a result of the event will not occur. If, during any stage of event flow, the preventDefault method is called the event is canceled. Any default action associated with the event will not occur. Calling this method for a non-cancelable event has no effect. Once preventDefault has been called it will remain in effect throughout the remainder of the event's propagation. This method may be used during any stage of event flow. 
No Parameters
No Return Value
No Exceptions_

How it differs from `return false` or `stopPropagation()` and `stopImmediatePropagation()`
http://stackoverflow.com/questions/5302903/jquery-event-stopimmediatepropagation-vs-return-false 
http://fuelyourcoding.com/jquery-events-stop-misusing-return-false/

Please let me know in case `preventDefault()` was intentionally left out and the reason if any for that.

Thanks and Regards
Payoj

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
