### ISSUE TITLE
[Slate-React] node is not assignable to DocumentJSON

### ISSUE THREAD

**Issue by carpben** [DefinitelyTyped/DefinitelyTyped#32318]
@andykent, @majelbstoat @JanLoebel @YangusKhan @kalley @Kornil @isubasti @sgreav 

- [ x] I tried using the `@types/xxxx` package and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

I just copied initialValue from the documentation and I get a type error. 

![image](https://user-images.githubusercontent.com/13496178/51435587-8fc72f80-1c83-11e9-9500-26b1164f9020.png)

![image](https://user-images.githubusercontent.com/13496178/51435616-06fcc380-1c84-11e9-87f1-880f264fe813.png)

**Comment by scarletks1214** [comment]
just add 'object' property to 'leaves' property.

**Comment by scarletks1214** [comment]
original code was
leaves: [
              {
                text: 'A line of text in a paragraph.',
              },
            ],

current code is

leaves: [
              {
                object: 'leaf', // add this line!!!!!
                text: 'A line of text in a paragraph.',
              },
            ],

**Comment by scarletks1214** [comment]
Your error happens as the typescript version rising up.(not sure)
Take care ? mark at the declaration of properties

**Comment by carpben** [comment]
@scarletks1214 , sorry but I didn't understand. Why is this error happening? What could I do to solve it? Should anything be changed in the documentation?

**Comment by carpben** [comment]
adding `object: 'leaf',` as suggested by @scarletks1214 does solve the problem. 
Is there a problem in @types/slate or should the documentation be fixed?

**Comment by ivan-ha** [comment]
also faced the same error, it's because `object: "leaf"` is required in `TextJSON`, but it was missing in the example

can be suppressed by adding `object: "leaf"` back, not sure if it's problem of `@types/slate` or the doc though

```js
const initialValue = Value.fromJSON({
  document: {
    nodes: [
      {
        object: "block",
        type: "paragraph",
        nodes: [
          {
            object: "text",
            leaves: [
              {
                object: "leaf",  // <----- add this line
                text: "A line of text in a paragraph."
              }
            ]
          }
        ]
      }
    ]
  }
});
```

**Comment by Svarozich14** [comment]
For now there leaves is deprecated, but type definition isn't updated.
So you need to use old way or new with ts-ignore:
```
nodes: [
          {
            object: "text",
            // @ts-ignore
            text: "A line of text in a paragraph."
          }
        ]
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
