### ISSUE TITLE
Update breaks Yargs function and argument types

### ISSUE THREAD

**Issue by mikl** [DefinitelyTyped/DefinitelyTyped#32338]
- [x] I tried using the `@types/yargs` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @poelstra, @mizunashi-mana, @pushplay, @jeffkenney, @JimiC, @tkazec, @steffenvv

After upgrading `@types/yargs`, my project no longer compiles. I'm using yargs commandfiles with syntax like this:

```
import { Arguments, Argv, CommandBuilder } from 'yargs'

export const command = 'import-file <file>'
export const describe = 'run the importer on a single file'
export const builder: CommandBuilder = (yargs: Argv) => {
  return yargs
    .positional('file', {
      describe: 'path to file to import'
    })
    .options({
      cleanDestination: {
        boolean: true,
        describe:
          'Clean the destination folder from previously generated files before proceeding.'
      }
    })
}

export async function handler(args: Arguments) {
  // Actual implementation omitted.
}
```

With `@types/yarn` version `12.0.1`, this works fine. With version `12.0.5`, the following errors are reported:

```
src/commands/importFile.ts:14:23 - error TS2314: Generic type 'CommandBuilder' requires 2 type argument(s).
14 export const builder: CommandBuilder = (yargs: Argv) => {
                         ~~~~~~~~~~~~~~

src/commands/importFile.ts:32:37 - error TS2314: Generic type 'Arguments' requires 1 type argument(s).
32 export async function handler(args: Arguments) {
                                       ~~~~~~~~~
```

For completeness' sake, I also tried version 12.0.2. This reports the same error, so the problem appears to have been introduced between 12.0.1 and 12.0.2 and not been fixed since.

**Comment by JimiC** [comment]
You need to adjust your typings to the new generic expression.

**Comment by mikl** [comment]
@JimiC and what would those In and Out types be? There's none in the typings and I there seems to be no obvious explanation of what they might be? A CommandBuilder takes and returns the main Yargs object.

As far as I can see from your example, you created your own Arguments interface and use that in conjunction with the one from Yargs, but I'm not sure I understand why?

**Comment by mikl** [comment]
Yeah, but you've also made using the typings much much harder.  At this point it might be easier to write my own command line argument parser than whatever black typing magic might be required to use these typings.

**Comment by JimiC** [comment]
There is no black magic here, white magic I agree. As I come from `C#` generic types is no stranger to me. I urge you to dick into `Generics`. It will open a whole new world to you and then you will have learned how to write reusable, type agnostic, code.

**Comment by steffenvv** [comment]
Hi @mikl, I just opened a PR that should make it easier to make your code work with the newest typings. The main idea behind the 12.0.2 change is that the compiler should infer as many types as possible for you, so omitting some explicit type annotations from your code may actually be the way to go. If you do want to declare the types explicitly, the first type argument of the command builder is the shape of the options leading up to your command, and the second type argument is the shape of the options to be parsed for that command. Hope this helps!

**Comment by JimiC** [comment]
@steffenvv solution just adds default values to the types. This is equal to setting those types to `any`. Personally, I'm in favor of explicit type declarations, which is a clear indication that the developer knows what (s)he is doing.

**Comment by pushplay** [comment]
My understanding of the new PR is that the default argument type is `{}` so no unsafe is newly enabled.  If it was `any` then yes we would be losing error checking power.

**Comment by steffenvv** [comment]
Yes, I don't think adding defaults for the type arguments is a type safety issue. They will still be correctly inferred in the cases where you let the compiler infer the types.

An interesting technique that I sometimes use is to let the compiler infer some interesting types for me, and *then* give them a name, using constructs like typeof and ReturnType, and by indexing into types. For example, an alternative to the example given above could be something like this:

```typescript
import * as yargs from "yargs";

const command = 'import-file <file>';
const describe = 'run the importer on a single file';
const builder = (yargs: yargs.Argv) => {
    return yargs
        .positional('file', {
            describe: 'path to file to import'
        })
        .options({
            cleanDestination: {
                boolean: true,
                describe: 'Clean the destination folder from previously generated files before proceeding.'
            }
        });
};

export type CommandBuilder = typeof builder;

export type Arguments = ReturnType<CommandBuilder>["argv"];

```

**Comment by pushplay** [comment]
That's pretty slick.  When I use `typeof` it's usually to extract some interface from a package that probably should have been named and exported anyways.

**Comment by steffenvv** [comment]
I'm not sure. I guess that depends on what you omitted. If I complete the example like this, it seems to work:

```typescript
interface In {
    foo: boolean;
}

interface Out {
    foobar: boolean;
}
 
const builder: yargs.CommandBuilder<In, Out> = (yargs): yargs.Argv<Out> => yargs.boolean('foobar').demandOption('foobar');
```

**Comment by wKovacs64** [comment]
Sorry, I screwed up my example (edited now). The sole field in both interfaces is optional. The implementation looks as such:

```ts
yargs
    .option('foo', {
      alias: 'foobar',
      describe: 'to foo or not to foo',
      type: 'boolean',
      default: false,
    })
```
Tacking on a `demandOption('foobar')` does seem to fix it, but then yargs tells the user it's required (which it isn't). An alternative is to omit the generic from the return type, so it just returns `Argv` (instead of `Argv<Out>`), but that doesn't feel "correct" either?

**Comment by steffenvv** [comment]
Maybe I'm the one who doesn't understand how commands works, but to me that looks like you're defining a command that accepts a --foo/--foobar option. Unfortunately it's not picking up the foobar alias when it's declared like that, so it infers an output of `{ foo: boolean }` which doesn't match your `Out` interface (but happens to match your `In` interface, adding some confusion.)

If you swith it around and do `.option('foobar', { alias: 'foo', ... })` it should typecheck. Or you can do `.option('foo', { ... }).alias('foo', 'foobar')` to have it recognize both aliases.

**Comment by wKovacs64** [comment]
You understand correctly. Moving the alias out of the options object and into its own chained function call did the trick. Thanks! 👍

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
