### ISSUE TITLE
React: unexpected error when spreading generic props

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#32355]
TS version 3.2.2

Is this a typings or a TypeScript issue?

``` ts
import * as React from 'react';
import { Component, ComponentType } from 'react';

const myHoc = <
    ComposedComponentProps extends { composedComponentProp: number }
>(
    ComposedComponent: ComponentType<ComposedComponentProps>,
) => {
    type WrapperComponentProps = ComposedComponentProps & {
        wrapperComponentProp: number;
    };

    class WrapperComponent extends Component<WrapperComponentProps, {}> {
        render() {
            const {
                wrapperComponentProp,
                ...composedComponentProps
            } = this.props;

            /*
            Type 'Pick<Readonly<{ children?: ReactNode; }> & Readonly<WrapperComponentProps>, "children" | Exclude<keyof ComposedComponentProps, "wrapperComponentProp">>' is not assignable to type 'IntrinsicAttributes & ComposedComponentProps & { children?: ReactNode; }'.
            */
            return <ComposedComponent {...composedComponentProps} />;
        }
    }

    return WrapperComponent;
};
```

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Kovensky @pshrmn 

If you do not mention the authors the issue will be ignored.

**Comment by ferdaber** [comment]
This is a known issue in TS where generic types are more strictly enforced in HOCs but are still sometimes erased (doesn't recombine properly after rest and object spread):  https://github.com/Microsoft/TypeScript/issues/28938#issuecomment-450636046

**Comment by OliverJAsh** [comment]
Thanks @ferdaber!
