### ISSUE TITLE
ink tests fail

### ISSUE THREAD

**Issue by Flarna** [DefinitelyTyped/DefinitelyTyped#32464]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cprecioso

ink tests fail currently. see e.g. CI run of #32159 
I verified that I get the same fail local without node involved.

Not sure if this is an issue in ink or in one of the packages used by ink.

```
ERROR: 16:18  expect          TypeScript@next compile error:
Type '{ children: (string | number)[]; green: true; }' is not assignable to type 'IntrinsicClassAttributes<Component<{ rgb?: [number, number, number] | undefined; hsl?: [number, number, number] | undefined; hsv?: [number, number, number] | undefined; hwb?: [number, number, number] | undefined; ... 50 more ...; bgWhiteBright?: boolean | undefined; }, {}, {}>> & { ...; }'.
  Property 'children' does not exist on type 'IntrinsicClassAttributes<Component<{ rgb?: [number, number, number] | undefined; hsl?: [number, number, number] | undefined; hsv?: [number, number, number] | undefined; hwb?: [number, number, number] | undefined; ... 50 more ...; bgWhiteBright?: boolean | undefined; }, {}, {}>> & { ...; }'.
```

**Comment by cprecioso** [comment]
It doesn't yield an error in my computer(?). Maybe something in #32159 changed, can you check again?

**Comment by Flarna** [comment]
Retriggered CI - ink and styled-react-modal have recovered.
