### ISSUE TITLE
[@types/bootstrap@3.3.41] Error TS2702: 'JQuery' only refers to a type, but is being used as a namespace here.

### ISSUE THREAD

**Issue by AndyMDoyle** [DefinitelyTyped/DefinitelyTyped#32487]
- [X] I tried using the `@types/bootstrap@3.3.41` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @denisname 

This morning we started seeing our gulp tasks fail with the following errors:

`/node_modules/@types/bootstrap/index.d.ts(268,50): error TS2702: 'JQuery' only refers to a type, but is being used as a namespace here.`

Reviewing our logs we saw our dependency on `@types/bootstrap` version `^3.3.40` took version 3.3.41 during the build process, which results in this error for us.

Changing our dependency to fix on `3.3.40` resolves the errors. The recent changes to index.d.ts appear to be to add JsDoc, but maybe another change crept in somewhere that has caused this.

**Comment by denisname** [comment]
Are you using jQuery 1 or 2? May you try this [fix](https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/909f8b2069ab20fbf15d87561867bd6be789582e/types/bootstrap/v3/index.d.ts), from PR #32541, and tell me if it works.

**Comment by chrisharding** [comment]
Yes, we are using jQuery 2.0.3. It looks like the fix in that pull request works, thanks.
