### ISSUE TITLE
@types/react >= 16.7.18 problem with IsExactlyAny and static propTypes

### ISSUE THREAD

**Issue by Slessi** [DefinitelyTyped/DefinitelyTyped#32588]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ferdaber @johnnyreilly 

I believe this is due to the `IsExactlyAny` type introduced in this commit https://github.com/DefinitelyTyped/DefinitelyTyped/commit/a6fd2ee6ac80beb78401c12181c81a597f44fa36#diff-96b72df8b13a8a590e4f160cbc51f40c as the problem did not occur in version `16.7.17` of the typings, and occurs in `>= 16.7.18`

```tsx
import * as React from 'react';

interface MyProps<T> {
  prop?: T;
}

class MyClass<T> extends React.Component<MyProps<T>> {
  // Removing this removes the error, for some reason?
  public static propTypes: {};
}

function test<T>() {
  // Types of property 'prop' are incompatible.
  const Component: React.FC<MyProps<T>> = (props) => <MyClass<T> {...props} />;
}
```

```
Type '{ prop?: T | undefined; children?: ReactNode; }' is not assignable to type '{ readonly children?: ReactNode; readonly prop?: (IsExactlyAny<T | undefined> extends true ? T | undefined : T | undefined) | undefined; }'.
  Types of property 'prop' are incompatible.
    Type 'T | undefined' is not assignable to type '(IsExactlyAny<T | undefined> extends true ? T | undefined : T | undefined) | undefined'.
      Type 'T' is not assignable to type '(IsExactlyAny<T | undefined> extends true ? T | undefined : T | undefined) | undefined'.
        Type 'T' is not assignable to type 'IsExactlyAny<T | undefined> extends true ? T | undefined : T | undefined'.
```

In this contrived example I can simply remove `public static propTypes: {};` but my actual use case requires it to be there

**Comment by disintegrator** [comment]
This issue is also blocking us from upgrading beyond 16.7.18. The real world example of where it's a problem can be found in react-apollo's Query and Mutation components. Both of these class components have generic props and also define propTypes. In our codebase we have a helper function that can generate components built on these two components. The simplified version of this helper function has the following structure:

```ts
import { DocumentNode } from "graphql";
import * as React from "react";
import { Mutation, MutationProps, Query, QueryProps } from "react-apollo";

export function createQuery<Data, Variables>(
  query: DocumentNode,
  displayName: string
) {
  type Props = Omit<QueryProps<Data, Variables>, "query">;
  const C: React.FC<Props> = props => (
    <Query<Data, Variables> {...props} query={query} />
  // ^^^^^^^^ type error 1
  );
  C.displayName = displayName;
  return C;
}

export function createMutation<Data, Variables>(
  mutation: DocumentNode,
  displayName: string
) {
  type Props = Omit<MutationProps<Data, Variables>, "query">;
  const C: React.FC<Props> = props => (
    <Mutation<Data, Variables> {...props} mutation={mutation} />
  // ^^^^^^^^ type error 2
  );
  C.displayName = displayName;
  return C;
}
```

Type error 1:
>Type 'Variables' is not assignable to type 'IsExactlyAny<Variables | undefined> extends true ? object | null | undefined : Variables | undefined'.

Type error 2:
>Type 'Data' is not assignable to type 'IsExactlyAny<Data | undefined> extends true ? object | null | undefined : Data | undefined'.

Since react hooks are landing soon and we are really excited to use them we'd really appreciate any guidance on how to address this issue so we can get on the latest react typings.

**Comment by Slessi** [comment]
@ferdaber My example reproduces the issue, you want a *more complex* example?

**Comment by ferdaber** [comment]
Ah I see it... I can take a look later today.

**Comment by ferdaber** [comment]
Okay so... conditionals and generics don't go very well in the contravariant position... I'll have to figure out what to do about this but right now this is the workaround:

```tsx
function test<T>() {
  const Component: React.FC<MyProps<T>> = (props) => <MyClass<T> {...props as JSX.LibraryManagedAttributes<typeof MyClass, typeof props>} />;
}
```

**Comment by ferdaber** [comment]
This obviously uses an assertion but at least forces the type checking to be bivariant, for now.

**Comment by basicdays** [comment]
Temporary workaround worked on my end as well. Thanks for pointing that out.

**Comment by stnwk** [comment]
Would love a proper fix, the workaround unfortunately did not work for me :(

How's it going? :) @ferdaber

**Comment by ferdaber** [comment]
Can you give me an example of where the fix did not work for you?

**Comment by alamothe** [comment]
Experiencing the issue with `react-apollo`, literally the same code as @disintegrator. Workaround looks strange but works.

**Comment by stnwk** [comment]
Has anyone _any_ idea how to fix this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
