### ISSUE TITLE
recompose: `ObservableConfig`/`Subscribable` conflicts with RxJS types

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#32625]
RxJS version 6.4.0

``` ts
import { ObservableConfig } from 'recompose';
import { from } from 'rxjs';

const rxjsConfig: ObservableConfig = {
    /* Argument of type 'Subscribable<T>' is not assignable to parameter of type 'ObservableInput<any>'.
    Type 'Subscribable<T>' is not assignable to type 'Iterable<any>'.
      Property '[Symbol.iterator]' is missing in type 'Subscribable<T>'. */
  fromESObservable: x => from(x),
}
```

My workaround:

``` ts
const rxjsConfig: ObservableConfig = {
    fromESObservable: from as ObservableConfig['fromESObservable'],
}
```

I boiled it down to the following issue:

``` ts
interface RecomposeSubscribable {
    subscribe(observer: {}): any;
}

interface RxSubscribable {
    subscribe(observer: {}): any;
    // Disabling this overload fixes the error below
    subscribe(next: null | undefined): any;
}

declare function from<O extends RxSubscribable>(input: O): any;

type Fn = (subscribable: RecomposeSubscribable) => any;
/* Argument of type 'Subscribable' is not assignable to parameter of type 'RxSubscribable'.
  Types of property 'subscribe' are incompatible.
    Type '(observer: {}) => any' is not assignable to type '{ (observer: {}): any; (next: null | undefined): any; }'.
      Types of parameters 'observer' and 'next' are incompatible.
        Type 'null | undefined' is not assignable to type '{}'.
          Type 'undefined' is not assignable to type '{}'. */
const fn: Fn = x => from(x);
```

Disabling the overloads in RxJS’s `Subscribable` makes the error disappear, so it's something to do with that I guess.

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @iskandersierra @clayne11 @Pajn @lucasterra @brian-lives-outdoors @TiuSh

If you do not mention the authors the issue will be ignored.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
