### ISSUE TITLE
[@types/qlik-engineapi] change definition of interface IHyperCube

### ISSUE THREAD

**Issue by ralfbecher** [DefinitelyTyped/DefinitelyTyped#32635]
The property **qMeasureInfo** is array of INxMeasureInfo:

qMeasureInfo: INxMeasureInfo[];

@konne

**Comment by konne** [comment]
@ralfbecher  I don't understand the issue in the actual defType Master this is already an array see
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/84cd3d14bacecdfe6d3bc2868cb58a21fe98c4b0/types/qlik-engineapi/index.d.ts#L8712
Please check

**Comment by ralfbecher** [comment]
@konne it's not in the version we get with npm install

**Comment by ralfbecher** [comment]
already fixed.
