### ISSUE TITLE
Types uses eye but mathjs had renamed eye to identity

### ISSUE THREAD

**Issue by avielkis** [DefinitelyTyped/DefinitelyTyped#32731]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andnp, @siavol, @bradbesserman, @pawkrol

If you do not mention the authors the issue will be ignored.

**Comment by andnp** [comment]
Do feel free to make a PR! It might take some time before I would able to do it myself.
