### ISSUE TITLE
Definition for "RemoteInfo" and related functions in dgram for Node

### ISSUE THREAD

**Issue by tekkusan** [DefinitelyTyped/DefinitelyTyped#32744]
- [X] I tried using the `@types/node` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
- Authors: @rbuckton 

I didn't want to make a pull request since I'm very new to typescript and I might be missing something, but it seems there are a few issues with the type definitions for the Node dgram module (as described in https://nodejs.org/api/dgram.html)

Namely, the "RemoteInfo" interface is missing a size : number (this caused a compiler error on JS code I was already using and trying to migrate to TS which led me to finding the issue) and in several places after that (basically in all the listener configuration functions) there are references to "AddressInfo" which should be "RemoteInfo" instead.

**Comment by tekkusan** [comment]
@SimonSchick 

Not sure if it's worth messing with your PR at this point, but I came across a couple of things in the crypto module in case you want to add them also. The createCipheriv and createDecipheriv functions don't currently allow for a null value in the initialization vector (for example, for ECB modes) as allowed in https://nodejs.org/api/crypto.html#crypto_crypto_createcipheriv_algorithm_key_iv_options

**Comment by SimonSchick** [comment]
Can you provide a failing test?
Also ideally create a new issue pls.

**Comment by tekkusan** [comment]
I have no experience with tests, but I'll open a new issue and provide an example and a link to the Node documentation.
