### ISSUE TITLE
Definition request: math.js

### ISSUE THREAD

**Issue by plantain-00** [DefinitelyTyped/DefinitelyTyped#3275]
https://github.com/josdejong/mathjs

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/mathjs/mathjs.d.ts

**Comment by mitchellmorris** [comment]
Am I wrong in thinking that this needs the following at the end of the file?

```
declare module "mathjs" {
    export = math;
}
```

Without it I can't get `import math = require('mathjs');` to work.
