### ISSUE TITLE
[@types/algoliasearch] QueryParameters is missing "sortFacetValuesBy" option

### ISSUE THREAD

**Issue by denisyilmaz** [DefinitelyTyped/DefinitelyTyped#32761]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CBaptiste @Haroenv @aherve @samouss @keichinger

missing definition for "sortFacetValuesBy" in QueryParameters. Both in full and in lite type definition files

**Comment by Haroenv** [comment]
That's correct, feel free to make a PR. Correct type is `"count" | "alpha"`. Documentation is here: https://www.algolia.com/doc/api-reference/api-parameters/sortFacetValuesBy/
