### ISSUE TITLE
[@types/react-navigation] 3.x, DrawerItemsProps must have screenProps

### ISSUE THREAD

**Issue by SaeedZhiany** [DefinitelyTyped/DefinitelyTyped#32777]
In react-navigation 3.x, type of props object pass to `contentComponent` is `DrawerItemsProps`. also drawer component created by `createDrawerNavigator` must wrapped by an object created by `createAppContainer` which has a `screenProps` used to send user additional props to drawer menu component.
example:
```
const DrawerNav = createDrawerNavigator(
  {
    SOME_ROUTE_NAME: {
      screen: <SomeSCreen/>
    }
  },
  {
    contentComponent: renderSidebar,
    initialRouteName: SOME_ROUTE_NAME,
  });

const AppContainer = createAppContainer(DrawerNav);

function renderSidebar(props: DrawerItemsProps) {
  const {props1, props2,} = props.screenProps; // <----- 
  return (
    <Sidebar
      props1
      props2
    />
  );
}

.
.
.

render() {
    const screenProps = {
      props1: some_value1,
      props2: some_value2
    };

    return (
      <View>
        <AppContainer key={'app navigator'} screenProps={screenProps}/> // <-------
        ...
      </View>
    )
  }
```

- [x] I tried using the `@types/react-navigation` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors
  - Authors: 
@Huhuanming
@mhcgrq
@fangpenlin
@petejkim
@Kyle Roach
@phanalpha
@charlesfamu
@Tim Wang
@Qibang Sun
@Sergei Butko:
@Veit Lehmann:
@Steven Miller
@Armando Assuncao
@Ciaran Liedeman
@Jérémy Magrin
@Luca Campana
@Ullrich Schaefer
@Linus Unnebäck
@Yosuke Seki
@Jake
@Gustavo Brunoro
@Denis Frezzato
@Mickael Wegerich
@Max Davidson
@Alec Hill
@Lachlan Young
@Jason Killian
@Jeroen Vervaeke
@Fellipe Chagas
@Deniss Borisovs
@Kenneth Skovhus

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
