### ISSUE TITLE
[@types/aws-lambda] Support API Gateway websocket integration

### ISSUE THREAD

**Issue by loikg** [DefinitelyTyped/DefinitelyTyped#32781]
- [x] I tried using the `@types/aws-lambda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @darbio, @skarum, @StefH, @tobyhede, @buggy, @y13i, @wwwy3y3, @OrthoDex, @MichaelMarner, @daniel-cottone, @kostya-misura, @coderbyheart, @palmithor, @daniloraisi, @simonbuchan, @Haydabase, @repl-chris, @aneilbaboo

WebSocket APIs in Amazon API Gateway have been announce recently (see [here](https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/)) and the documentation can be found [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api.html)

I am new to Typescript and AWS thus why i am not making a pull request directly but i am willing to prepare one. From my understanding the documentation reference for the field in the API Gateway event can be found [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-mapping-template-reference.html).

For testing purpose i simply added `connectionId` and `routeKey` field to `APIGatewayEventRequestContext` interface like so:

```
export interface APIGatewayEventRequestContext {
    ...
    identity: {
        ...
    };
    connectionId ?: string;
    routeKey ?: string;
    ...
}
```

If i was to make a pull request is it the correct modification i should be doing and thus just add the remaining new fields to APIGatewayEventRequestContext as optional fields ?

**Comment by simonbuchan** [comment]
Thanks for the offer, and welcome! Your suggested code seems fine, not having seen the event myself, and shouldn't be any trouble to get in, but be aware that DefinitelyTyped PRs are expected to do a couple more things, The "Contributing" section in the DefinitelyTyped readme goes into the steps to take, but fortunately [you have a lot of examples](https://github.com/DefinitelyTyped/DefinitelyTyped/pulls?utf8=%E2%9C%93&q=is%3Apr+aws-lambda) to look at to get an idea of what's involved in updating aws-lambda in particular. Essentially you will just need to add some level of testing (I don't really expect exhaustive testing for aws-lambda, the existing tests are largely just read and write the fields)

Pedantically (which is our job 😉) that last link is to the mapping template, in VTL, not the received event. This lets you send somewhat arbitrary content to your API gateway backend, using the custom integration. The event type in `@types/aws-lambda` is for the proxy integration, which should look very similar though.

For some reason AWS is terrible at documenting their lambda events, at best you get an example [like this](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format), but I couldn't see an example specifically for WebSocket. Ideally you would capture (in cloudwatch or whatever) the actual event(s) received to get an idea of what you could receive, it sounds like that's effectively what you did?

**Comment by loikg** [comment]
Hi, thanks for the answer ! I will look into the required steps and tests for the PR and submit one when i have time.

Yes i do find the AWS documentation terrible regarding events. Thank for pointing out that the last link is not the event documentation.

Yes currently i use a combination of the websocket developer guide and and output of the event in cloudwatch to see what's in the event.
