### ISSUE TITLE
[@types/mapbox-gl] Support for Testcafe

### ISSUE THREAD

**Issue by janhartmann** [DefinitelyTyped/DefinitelyTyped#32826]
I am currently using `"@types/mapbox-gl": "^0.51.3"` but apparently this is not working well with an issue I have in Testcafe (https://github.com/DevExpress/testcafe/issues/3401)

Line 50 of the types:

```
type Expression = [ExpressionName, ...any[]]
```

The `...any[]` is not compatible with how Testcafe is compiling TypeScript.

```
Error: TypeScript compilation failed.
/Users/janhartmann/Projects/manager-ui/client/node_modules/@types/mapbox-gl/index.d.ts (50, 40): Type expected.
```

I am suggesting changing this signature to:

```
type Expression = [ExpressionName, any]
// or
type Expression = [ExpressionName, any[]]

``` 

Which will make it behave again. @macobo what do you think?

**Comment by macobo** [comment]
Oops! Sorry to hear this change broke your app.

Some context on `type Expression` - it can take any number of arguments at this time. E.g. all the following are valid (assuming 'expr' is in ExpressionName):

```
['expr']
['expr', 1]
['expr', 1, 2, ['expr', 3]]
```

The `...any[]` is supposed to stand for "any number of elements of type any" in this tuple. See also https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#rest-elements-in-tuple-types

I don't think the proposed types would work here for that reason.

What version of typescript is TestCafe using? If pre-3.0, maybe that's causing the problem.

**Comment by janhartmann** [comment]
According to their package.json they are running 2.X.

I guess I need to make them upgrade! Thanks for the heads up ;-)

**Comment by macobo** [comment]
Nice, good luck!

In the meanwhile, I think you can use an older types definition, I think 0.51.3 would work on typescript 2.x
