### ISSUE TITLE
jest.fn's implementation argument is no longer optional

### ISSUE THREAD

**Issue by jerico-dev** [DefinitelyTyped/DefinitelyTyped#32863]
If you know how to fix the issue, make a pull request instead.
- [x] I tried using the `@types/jest` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- Authors: @antoinebrault 

This was introduced by PR #31094 / Commit 3b921eff19a12be00fa9626fb1973e91b93398c9

**Comment by antoinebrault** [comment]
What is the issue ? Do you have an example ? 

current implementation is : 

```typescript
function fn(): Mock;
function fn<T, Y extends any[]>(implementation: (...args: Y) => T): Mock<T, Y>;
```

**Comment by jerico-dev** [comment]
type PropOf<T> = T[keyof T]
...
mockedMethods.forEach(mockedMethod => mocked[mockedMethod] = jest.fn<PropOf<T>>() as MockFunction<T[keyof T]>)

(This already presumes the PR I just provided)

Before I either had the choice not being able to get proper typing at all or pass jest.fn(undefined as any) into jest.fn

**Comment by jerico-dev** [comment]
Let me give you the full source code - otherwise it will be hard to understand what we're up to...

We have a small utility function that allows us to mock any typescript interface like this:

```
...
let mockMyInterface: Mocked<MyInterface>
mockMyInterface = mock<MyInterface>('someMethod', 'someOtherMethod')
...
mockMyInterface.someMethod.mockReturnValue('12345')
...
```

```type GenericFunction = (...args: any[]) => any

export type MockFunction<F extends GenericFunction> = F & jest.Mock<ReturnType<F>, ArgsType<F>>

export type Mockable<T> = {
  [K in keyof T]: GenericFunction
}

export type Mocked<T extends Mockable<T>> = {
  [K in keyof T]: MockFunction<T[K]>
}

type PropOf<T> = T[keyof T]

export function mock<T extends Mockable<T>>(...mockedMethods: (keyof T)[]): Mocked<T> {
  const mocked: Mocked<T> = {} as Mocked<T>
  mockedMethods.forEach(mockedMethod => mocked[mockedMethod] = jest.fn<PropOf<T>>() as MockFunction<T[keyof T]>)
  return mocked
}```

**Comment by antoinebrault** [comment]
Ok I understand. Thanks. I'll review the PR.
