### ISSUE TITLE
jest: Regression: mock{Resolved|Rejected}... no longer has the correct return type

### ISSUE THREAD

**Issue by jerico-dev** [DefinitelyTyped/DefinitelyTyped#32890]
- [x] I tried using the `@types/jest` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @antoinebrault 

Assume a function:

```
function someDeferredResult(): Promise<SomeResultType> {...}
```

Expected:
The intention of mock{Resolved|Rejected}... is to pass in a value of type `SomeResultType` - AND NOT `Promise<SomeResultType>` - and generate a promise from it, see https://jestjs.io/docs/en/mock-function-api#mockfnmockresolvedvaluevalue.

Actual:
The 24.x typing broke this interface. It now assumes that mock{Resolved|Rejected}... gets a promise as an argument for a function that returns a promise.

This also breaks the mocking of async functions.

Background:

A mocked version of the above `someDeferredResult` should of course have the same signature as the original function. Let's assume that `someMockedDeferredResult` is just such a mock implementation.

Now const myMockFn = jest.fn(someMockDeferredResult) will have an inferred type of `Mock<Promise<SomeResultType>, []>`.

This means that myMockFn.mock{Resolved|Rejected}... will have the described undesired signature.

One possible fix for this would be to use conditional types so that mock{Resolved|Rejected} are only defined when the return type T extends `Promise<V>`.

Example:
``` 
mockResolvedValue<V>(value: T extends PromiseLike<V> ? V | PromiseLike<V> : never): Mock<T, Y>;
```

If you optionally want to support a return value of `Promise<T>` (why would you?) then you could also say:
``` 
mockResolvedValue<V>(value: T extends PromiseLike<V> ? V | PromiseLike<V> : T | PromiseLike<T>): Mock<T, Y>;
```
But I'd rather stick to what IMO the intended use case was for this method. I find the second option confusing and misleading.

**Comment by antoinebrault** [comment]
See #32816
