### ISSUE TITLE
Google Apps Script definitions for Hangouts Chat API

### ISSUE THREAD

**Issue by dustinmichels** [DefinitelyTyped/DefinitelyTyped#32906]
@grant @motemen 

I've been trying to generate a TypeScript types file for the objects in the [Google Hangouts Chat API](https://developers.google.com/hangouts/chat/reference/):

- [`Event`](https://developers.google.com/hangouts/chat/reference/rest/v1/Event)
- [`User`](https://developers.google.com/hangouts/chat/reference/rest/v1/User)
- [`Space`](https://developers.google.com/hangouts/chat/reference/rest/v1/spaces#Space)
- etc.

This service seems [designed to work with Google Apps Script](https://developers.google.com/hangouts/chat/quickstart/apps-script-bot), but is not exactly a Google Apps Script service.

I've tried adapting the [dts-google-apps-script](https://github.com/motemen/dts-google-apps-script) code. The docs are laid out similarly to the main Google Apps Script, but they are different enough the scarper doesn't quite work.

I've also tried using the ["discovery document"](https://chat.googleapis.com/$discovery/rest?version=v1) the service provides to generate types, or maybe to generate an `out.json` file that `dts-google-apps-script` could turn into the docs.

Do you know if there are existing solutions for generating type definition files for this kind of Google Service? Or for Hangouts Chat specifically? Is it reasonable/desirable to try integrating these kinds of more auxiliary google services into this collection of type def files?

**Comment by grant** [comment]
- [`Event`](https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/chat/v1.ts#L244)
- [`User`](https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/chat/v1.ts#L592)
- [`Space`](https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/chat/v1.ts#L545)

Perhaps you can use the Node client?

**Comment by dustinmichels** [comment]
Great, that's super helpful, thanks!
---

To anyone that comes across this post, it looks like you can use these types by running:

```bash
npm install googleapis
```

Then in your `.ts` code:

```typescript
import { chat_v1 } from "googleapis";

type User = chat_v1.Schema$User;
```
