### ISSUE TITLE
[@types/google-cloud__datastore] Wrong export format with v3+

### ISSUE THREAD

**Issue by Nargonath** [DefinitelyTyped/DefinitelyTyped#32952]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @beaulac @ThomasdenH @ogawa0071 

If you do not mention the authors the issue will be ignored.

This [line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/10bc3fc48a5f762ecf57cf007484eec3cd3f63f6/types/google-cloud__datastore/index.d.ts#L12) should be `export const Datastore = Datastore;` to match the [v3 export format](https://github.com/googleapis/nodejs-datastore/blob/7d9f77fd0f6c13bbb05723bcd30844a47cd19f85/src/index.ts#L805).

I try using this package with the latest `@google-cloud/datastore` and I get this error:
![image](https://user-images.githubusercontent.com/583657/52556236-42566200-2dec-11e9-88b8-6e5340581494.png)

If I'm right, I'll be happy to make a PR to fix that.

Thanks for the typings. 👍

**Comment by ThomasdenH** [comment]
The repository supplies its own types now, since it is written in Typescript. I think the current types can be deprecated with a message saying as much. Of course these types can be updated, but ideally we wouldn't do double work. Do you use the `DefinitelyTyped` version with a reason?

**Comment by Nargonath** [comment]
Yeah indeed you are right, I didn't look thoroughly enough in the package. I didn't find an `index.d.ts` at the package root so I thought it was not supplied. I guess that's just VSCode that pick it up for some reason.

**Comment by Nargonath** [comment]
The problem seems that `@google-cloud/datastore` does not declare a `typings` or `types` field in the package.json hence why the types are not picked up.
