### ISSUE TITLE
Null initialization vectors in Node crypto module

### ISSUE THREAD

**Issue by tekkusan** [DefinitelyTyped/DefinitelyTyped#32965]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick 

In createCipheriv and createDecipheriv, the initialization vector should be allowed to be null as described in https://nodejs.org/api/crypto.html#crypto_crypto_createcipheriv_algorithm_key_iv_options and https://nodejs.org/api/crypto.html#crypto_crypto_createdecipheriv_algorithm_key_iv_options ("If the cipher does not need an initialization vector, iv may be null.")

Currently, something like createCipheriv("aes-256-ecb", key, null) fails on the third parameter, and it's valid code for using AES in ECB mode (which does not use an IV).

**Comment by SimonSchick** [comment]
I don't think we want to hardcore all ciphers, which would be required for 100% correct type checking.
I suggest you just add `| null` in this case.

**Comment by tekkusan** [comment]
That's what I ended up doing, but I figured it would make sense to add the | null to the official .d.ts since it's a valid use in the Node docs? Obviously the execution would fail if it was used incorrectly, but then again, that could happen with any of the other types for the IV (a Buffer with a wrong size, etc.)

**Comment by SimonSchick** [comment]
@tekkusan what I meant is that you can create a PR for this 😛

**Comment by sunshinecotejo** [comment]
The issue is still persists in crypto version 4.0.0
