### ISSUE TITLE
Intl-tel-input JQueryDeferred type is missing

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [DefinitelyTyped/DefinitelyTyped#32971]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/intl-tel-input` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @fdnhkj @leonard-thieu @molnarm

If you do not mention the authors the issue will be ignored.

When attempting to use the typings for the `intl-tel-input` library I receive this error when `tslint` runs on my application. 

```
node_modules/@types/intl-tel-input/index.d.ts:125:30: Cannot find name 'JQueryDeferred'
```

It does appear that this is what the type of the `JQueryPlugin` object's `options` property but is not declared anywhere.

**Comment by metaliciouz** [comment]
Same error.

From repo: https://github.com/jackocnr/intl-tel-input

> IMPORTANT: since v14 we have removed the jQuery dependency. See below for how to initialise and use the plugin with pure JavaScript. If you want to stick with the jQuery version, there is now a separate jQuery wrapped version.

Latest **intl-tel-input** should be without jQuery dependency.

**Comment by mrKorg** [comment]
From here https://www.npmjs.com/package/intl-tel-input

IMPORTANT: since v14 we have removed the jQuery dependency. See below for how to initialise and use the plugin with pure JavaScript. If you want to stick with the jQuery version, there is now a separate jQuery wrapped version.

**Comment by papiliond** [comment]
Any progress in this issue?

**Comment by ak5** [comment]
Adding @peterblazejewicz :)

**Comment by peterblazejewicz** [comment]
So 2 options,

first is quick:
```json
"skipLibCheck": true,
```
added to `tsconfig`, this should fix that problem, but could impact code outcome

second, harder, we can split the module to two DT types, one with non-npm header.
I'll make a PR with different approach, removing dependincy to jQuery completely, but still allowing to reference additional types (`import 'intl-tel-input/jquery') or by 'tsconfig' addition, to include jQuery,
based on 'OTHER_FILES.txt', tbu

**Comment by peterblazejewicz** [comment]
#49842
