### ISSUE TITLE
[@types/hapi] typings don't support v17.0 `Hapi.server` syntax

### ISSUE THREAD

**Issue by BooleT37** [DefinitelyTyped/DefinitelyTyped#32994]
- [x] I tried using the `@types/hapi` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rafaelsouzaf, @jhsimms, @SimonSchick, @saboya

I'm in process of rewriting some js code to TypeScript right now and I have encountered an error in the following code:
```
const app = Hapi.server();
```
The error is:
```
TS2551: Property 'server' does not exist on type 'typeof import("path/to/my/project/node_modules/@types/hapi/index")'. Did you mean 'Server'?
```

After some digging I found out that Hapi has changed its default syntax for creating a server in v17.0.0 from
```
new Server([options])
```
to
```
const server = Hapi.server([options]);
```
This change is surprisingly omitted in changelogs, but you can clearly see it in the docs:
- [16.7.0 docs](https://hapijs.com/api/16.7.0#new-serveroptions)
- [17.0.0 docs](https://hapijs.com/api/17.0.0#-serveroptions)

However, `@types/hapi` do not support this syntax even though they claim to support hapi v18.0.
Is it intentional?
The workaround is simply replacing `Hapi.server` to `new Hapi.Server` in code, but I fear that the old syntax would be deprecated soon, so it's not ideal to continue using it.

**Comment by SimonSchick** [comment]
Not sure why this was done, I'm guessing to make `server` more factory-like?
@hueniverse can you shed some light onto this?
Also please read below.

In any case, I'd suggest we only add `export function server(opts?: ServerOptions): Server` keeping `Server` itself un-callable for now.
With the next major typings release we can make `Server` an interface and add `function Server` as a factory as well, unless `Server` will be removed as a factory function.

**Comment by saboya** [comment]
In order to support this properly export assignment would have to be used? I don't think this is a good compromise.

**Comment by hueniverse** [comment]
We support both. The new factory method is the preferred interface.
