### ISSUE TITLE
[@types/express-jwt and @types/express-unless] doesn't accept regex

### ISSUE THREAD

**Issue by lonix1** [DefinitelyTyped/DefinitelyTyped#32992]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wokim, @kacepe, @Sl1MBoy, @milan-mimra, @joaovieira 

The docs show this:

    app.use(jwt({ secret: 'shhhhhhared-secret'}).unless({ path: ['/token'] }));

And say this:

> In the example above, `path` can be a string, a regexp, or an array of any of those.

I need to specify a regex, so I tried this:

    app.use(jwt({ secret: 'shhhhhhared-secret'}).unless({path: [/foo/] }));

But that gives me an error:

> Argument of type '{ path: RegExp[]; }' is not assignable to parameter of type '(req: Request) => boolean'. Type '{ path: RegExp[]; }' provides no match for the signature '(req: Request): boolean'.

**Comment by lonix1** [comment]
I think the problem in the declaration file is here:

````
declare namespace unless {
    export interface Options {
        custom?: (req: express.Request) => boolean;
        path?: string | string[];        //  <----------------- regex is missing
        ext?: string | string[];
        method?: string | string[];
    }
    export interface RequestHandler extends express.RequestHandler {
        unless?: typeof unless;
    }
}
````

**Comment by joaovieira** [comment]
Already fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32840. Waiting to be merged.

**Comment by lonix1** [comment]
@joaovieira I guess I should close then... Thanks for confirming.

BTW: how long does it usually take for such merges?
