### ISSUE TITLE
[@types/react-redux] innacurate types in connect

### ISSUE THREAD

**Issue by chriskuech** [DefinitelyTyped/DefinitelyTyped#33009]
Possible duplicate of #32899

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo @pdeva @Kallikrein @jrakotoharisoa @apapirovski @surgeboris @soerenbf

**bug**
`connect` has inaccurate type checking.  Consider the following example:

```ts
interface IProps {
  a: Ta;
  b: Tb;
  c: Tc;
}

const mapStateToProps: (state: IState) => Pick<IProps, "a"> = ...
const mapDispatchToProps: (dispatch: Dispatch) => Pick<IProps, "b"> = ...

const MyComponent: (props: IProps) => JSX.Element = ...

export default connect(mapStateToProps, mapDispatchToProps)(MyComponent);
```

**What is the current behavior?**
There is no TypeScript compilation error, so the type system becomes inaccurate.

**What is the expected behavior?**
The last line should throw a typescript compilation error, because `Pick<IProps, "a"> & Pick<IProps, "b">` is incompatible with `IProps`, as it is missing property `c`.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**
`@types/react-redux@7.0.1`
`react-redux@6.0.0`

**Comment by wezleytsai** [comment]
This is typed correctly. The `connect` API does not require that all props are provided by the redux store.

In your example code, `connect` would return a component with a single prop `c` -- this is the `ownProps` for your component (where `Pick<IProps, "a">` is the `stateProps` and `Pick<IProps, "b">` is the `dispatchProps`).

**Comment by abathz** [comment]
I had the same problem

```ts
interface StateProps {
  name: string
}

interface DispatchProps {
  getFullName: typeof getFullName
}

type PropsComponent = StateProps & DispatchProps
type StateComponent = {}

class Main extends PureComponent<PropsComponent, StateComponent> {
  constructor (props: PropsComponent) {
    super(props)
  }

  onButtonClicked = () => {
    this.props.getFullName()
  }

  render () {
    return (
      <>
        <Title className='mb-3'>Welcome to NextJS with Typescript</Title>
        <Button onClick={this.onButtonClicked}>View Name</Button>
        <p>{this.props.name}</p>
      </>
    )
  }
}

const mapStateToProps = ({ simple }: any) => {
  const { name } = simple

  return { name }
}

export default connect(mapStateToProps, { getFullName })(Main)
```

I got error message `Argument of type 'typeof Main' is not assignable to parameter of type 'ComponentType<Matching<{ name: any; } & { getFullName: () => Promise<void>; }, PropsComponent>>'`

I use `@types/react-redux@7.0.3` and `react-redux@6.0.4`. what should i do?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
