### ISSUE TITLE
[@types/custom-functions-runtime] latest dist-tag is not the latest published version

### ISSUE THREAD

**Issue by akrantz** [DefinitelyTyped/DefinitelyTyped#33016]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32425 was the last update. It published version 1.4.10 but the latest dist-tag is 14.9.  Can someone fix this?

c:\>npm dist-tag -ls @types/custom-functions-runtime
latest: 1.4.9
ts2.4: 1.4.9
ts2.5: 1.4.9
ts2.6: 1.4.9
ts2.7: 1.4.9
ts2.8: 1.4.9
ts2.9: 1.4.9
ts3.0: 1.4.9
ts3.1: 1.4.9
ts3.2: 1.4.9
ts3.3: 1.4.9
ts3.4: 1.4.9

**Comment by ElizabethSamuel-MSFT** [comment]
@akrantz I don't think this is still an issue. Can you confirm?

Thanks.

**Comment by akrantz** [comment]
This is no longer an issue. Newer versions have been published.
