### ISSUE TITLE
[React] createRef without generic argument only works inline

### ISSUE THREAD

**Issue by dontsave** [DefinitelyTyped/DefinitelyTyped#33035]
this works:

```
<div ref={createRef()}/>
```

however this fails:
```
const ref = createRef();
<div ref={ref}/>;
```

It seems like the generic type for the ref in the second case is incompatible with HTMLDivElement. Is there a way to genericize createRef in the second case such that it can accept Elements without using `createRef<any>()`? 

`createRef<Element>()` doesn't seem to work.

**Comment by dontsave** [comment]
Following up on this. Forgot to ping the authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei

The above is also an issue when passing around a `MutableRefObject` that returns from React's `useRef`. 

This doesn't work, but it should:

```
const ref = useRef<HTMLElement>();
return <div ref={ref}>test</div>;
```

**Comment by ferdaber** [comment]
The first case works because of contextual typing, the generic parameter is inferred because of the call site.

For the second case, you should be using the `HTMLDivElement` parameter:
```tsx
const ref = useRef<HTMLDivElement>()
return <div ref={ref} />
```

**Comment by dontsave** [comment]
Right but I guess the question I have is how do we establish polymorphism such that we can enforce a MutableRefObject to be of a type returned by a `<div ref={..}` or an `<image ref={...}` or an `<svg ref={...}` without allowing it to be a non-element (string, number etc).

So, for example, this polymorphism can be enforced outside of a ref using `Element` like:

```
let element:Element;
let divElement:HTMLDivElement;
let imgElement:HTMLImageElement;
let svgElement:SVGElement;
	
element = divElement; //fine
element = imgElement; //fine
element = svgElement; //fine
element = 'string' //expected error
element = 12 //expected error
```

However ref polymorphism fails inside the JSX:

```
let r:MutableRefObject<Element>;

r.current = 'string'; //expected error
r.current = 12; //expected error

<div ref={r}/>; //unexpected error
<image ref={r}/>; //unexpected error
<svg ref={r}/>; //unexpected error
```

if any `HTMLDivElement`, `HTMLImageElement`, or `SVGElement` can be assigned to `Element` then it follows that refs to those elements should be assignable to `MutableRef<Element>`

**Comment by ferdaber** [comment]
Ah it's because the ref can be a function, which turns it into an invariant comparison for assignability checks. If it wasn't for the possibility of the ref being a callback, what you said would be possible. I don't know if there's any easy way out of that though :/

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
