### ISSUE TITLE
[@types/mongoose] - TypeScript 3.0+ compatibility with Promise.all

### ISSUE THREAD

**Issue by karthikiyengar** [DefinitelyTyped/DefinitelyTyped#33047]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @simonxca @horiuchi @sindrenm @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab

Anything with a `Promise.all` works perfectly in 2.9 and friends, but throws an error in 3.0+ 

```typescript
const test = await Promise.all([User.findOne({})])
```
```
Argument of type 'DocumentQuery<IUser, IUser>[]' is not assignable to parameter of type 'Iterable<IUser | PromiseLike<IUser>>'.
  Types of property '[Symbol.iterator]' are incompatible.
    Type '() => IterableIterator<DocumentQuery<IUser, IUser>>' is not assignable to type '() => Iterator<IUser | PromiseLike<IUser>>'.
      Type 'IterableIterator<DocumentQuery<IUser, IUser>>' is not assignable to type 'Iterator<IUser | PromiseLike<IUser>>'.
        Types of property 'next' are incompatible.
          Type '{ (value?: any): IteratorResult<DocumentQuery<IUser, IUser>>; (value?: any): IteratorResult<DocumentQuery<IUser, IUser>>; }' is not assignable to type '{ (value?: any): IteratorResult<IUser | PromiseLike<IUser>>; (value?: any): IteratorResult<IUser | PromiseLike<IUser>>; }'.
            Type 'IteratorResult<DocumentQuery<IUser, IUser>>' is not assignable to type 'IteratorResult<IUser | PromiseLike<IUser>>'.
              Type 'DocumentQuery<IUser, IUser>' is not assignable to type 'IUser | PromiseLike<IUser>'.
                Type 'DocumentQuery<IUser, IUser>' is missing the following properties from type 'IUser': firstName, aboutMe, lastName, email, and 70 more.ts(2345)
(method) Model<IUser>.findOne(conditions?: any, callback?: (err: any, res: IUser) => void): DocumentQuery<IUser, IUser> (+2 overloads)
Finds one document. The conditions are cast to their respective SchemaTypes before the command is sent.

@param projection — optional fields to return
```
I notice that the TypeScript version states 2.3 in the `d.ts`, but I couldn't find any material about 3.0 support. But looks like most of it works out of the box for me except this :-).

I'd be happy to help if someone has insights.

P.S: Might have something to do with this?
```

  node_modules/@types/mongoose/index.d.ts:2003:26
    2003     then<TRes>(resolve?: (res: T) => void | TRes | PromiseLike<TRes>,
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.

```

**Comment by jendrikw** [comment]
The core of the problem are the different signatures for `Query.then` and `Promise.then`. I think there is no reason for this, as `Query.then` is implemented as `.exec().then()`.

**Comment by karthikiyengar** [comment]
I was just going to drop a comment about this :-)

I added an exec to the queries and it does seem to work for now.
