### ISSUE TITLE
lodash round() type does not accept precision parameter

### ISSUE THREAD

**Issue by paddotk** [DefinitelyTyped/DefinitelyTyped#33041]
Lodash's `round()` function accepts one or two parameters: (1) the value to round, and optionally (2) precision. However, the declared type for this function does not include the second param, causing TypeScript to say this is wrong.

- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @aj-r @ailrun @e-cloud @thorn0 @jtmthf @DomiR

**Comment by aj-r** [comment]
What version of `@types/lodash` are you using? This is the definition for the latest version:

```ts
round(
    n: number,
    precision?: number
): number;
```

**Comment by paddotk** [comment]
4.14.121, the latest version on npm. I'm seeing ` type LodashRound = (n: number) => number;`

**Comment by aj-r** [comment]
Oh - it looks like you're using `lodash/fp`. In FP mode, `round` has a fixed arity of one (https://github.com/lodash/lodash/wiki/FP-Guide#fixed-arity) meaning that it only has one argument.

If you want to use the `precision` argument, use regular `lodash` (not `lodash/fp`).

**Comment by paddotk** [comment]
@aj-r Ah, I didn't realize there'd be a difference beteween the two. Thanks for clearing that up!
