### ISSUE TITLE
@types/aws-lambda: There are no types for the communication with Application Load Balancer

### ISSUE THREAD

**Issue by redlickigrzegorz** [DefinitelyTyped/DefinitelyTyped#33060]
- [x] I tried using the `@types/aws-lambda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dalen @trevor-leach @loikg @pl0xy @daniel-cottone

I am building right now the application with the usage of TypeScript and Serverless.
I replaced the API Gateway with Application Load Balancer which triggers the lambda functions directly.

I found that there are missing interfaces for this type of communication.
Could you tell me if it is a good observation? Maybe I should replace the library with a different one.

Apart from that, I created simple interfaces which are enough for my usage according to the [documentation](https://docs.aws.amazon.com/lambda/latest/dg/services-alb.html) and the article about the [differences](https://serverless-training.com/articles/api-gateway-vs-application-load-balancer-technical-details/).
```
export interface ApplicationLoadBalancerRequestEvent {
    requestContext: ApplicationLoadBalancerRequestContext;
    httpMethod: string;
    path: string;
    queryStringParameters?: { [name: string]: string };
    headers?: { [name: string]: string };
    multiValueQueryStringParameters?: { [name: string]: string[] };
    multiValueHeaders?: { [name: string]: string[] };
    body: string | null;
    isBase64Encoded: boolean;
}

export interface ApplicationLoadBalancerRequestContext {
    elb: {
        targetGroupArn: string;
    };
}

export interface ApplicationLoadBalancerResponse {
    statusCode: number;
    statusDescription: string;
    isBase64Encoded: boolean;
    headers?: { [name: string]: string };
    multiValueHeaders?: { [name: string]: string[] };
    body: string;
}
``` 
I suppose that it can be enough for me, but not enough for the whole appropriate communication.

**Comment by dbo** [comment]
👍 I'd appreciate these as well.

**Comment by dbo** [comment]
As far as I experience, the event's query params are encoded, worth to be documented IMHO.

**Comment by redlickigrzegorz** [comment]
Definitely, they are encoded. I will try to prepare something better, more specific in the meantime and create a pull request if it is possible. @dbo we can talk about it then (what should be added or removed).

**Comment by dbo** [comment]
The "differences" link is definitely a good resource, and IMO worth to be added as well. However, an official resource would be great, since AWS may change the interface.

**Comment by atombrenner** [comment]
The ALBEvent and the response is also documented here
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html#receive-event-from-load-balancer

**Comment by redlickigrzegorz** [comment]
@dbo @atombrenner the pull request is ready to review: #33763. Feel free to comment on my work.

**Comment by redlickigrzegorz** [comment]
I am closing this issue due to a successful merge of pull request #33763
