### ISSUE TITLE
[draft-js] Generic type 'ReactElement<P>' requires 1 type argument(s)

### ISSUE THREAD

**Issue by amensouissi** [DefinitelyTyped/DefinitelyTyped#33091]
Hello :) !
with the 3.3.1 typescript version, we have this error: 
```
ERROR in .../node_modules/@types/draft-js/index.d.ts
(626,27): error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).
```
we need to add a type argument to the wrapper type:

```
            interface DraftBlockRenderConfig {
                element: string;
                wrapper?: React.ReactElement<any>; // add a type argument
            }

```
- [x] I tried using the `@types/draft-js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dmitryrogozhny @eelco

**Comment by amensouissi** [comment]
please see the #33088

**Comment by VincentLanglet** [comment]
@amensouissi You have to update `@types/react`

**Comment by amensouissi** [comment]
@VincentLanglet thank you :)

**Comment by VincentLanglet** [comment]
@amensouissi No problem, I made the PR in the `@types/react`.
Don't forget to close your PR ;)
