### ISSUE TITLE
[@types/mongoose] Support for loadClass()

### ISSUE THREAD

**Issue by lonix1** [DefinitelyTyped/DefinitelyTyped#33103]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @simonxca @horiuchi @sindrenm @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @Ethan @vologa @jussikinnula @ondratra @alfirin @idandrd @dominikh @Fazendaaa @NormanPerrin @danmana @stablio

Mongoose now allows loading behavior from an [ES6 class into the schema](https://mongoosejs.com/docs/advanced_schemas.html#creating-from-es6-classes-using-loadclass) using `MySchema.loadClass(MyClass);`

This seems to work, but within the class the schema's properties obviously cannot be found.

````
class MyClass {
  public foo() { console.log(this.bar); }       // this.bar cannot be found, intellisense complains, warnings, etc.
}
````

I'm not sure how to deal with this other than allowing the warnings. If this cannot be addressed, at least maybe we can get a new section for it in the README.md explaining how to use it?

**Comment by jendrikw** [comment]
The solution is to annotate each function in the class with a `this` parameter, which tells typescript what `this` refers to when the function is called.

```
class UserClass {
	getFullName(this: IUser) {
		return `${this.firstName} ${this.lastName}`;
   }
}
```

**Comment by lonix1** [comment]
@jendrikw Thanks that works!

I actually discovered that if I change from `class MyClass { }` to `class MyClass extends mongoose.Model { }` then the problem goes away. But your solution is more accurate and I get full intellisense as well!

I guess this is not a bug. But it should be in the docs, it's so useful.

**Comment by jendrikw** [comment]
For the record, your code typechecks because Model has a construct signature of `new(doc?: any): T;` with `T` defaulting to `any`. The result is that you can access any property of `this`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
