### ISSUE TITLE
TS2315 Type 'Event' is not generic

### ISSUE THREAD

**Issue by merisahakyan** [DefinitelyTyped/DefinitelyTyped#33112]
export interface CarouselEventHandler<TElement> extends JQuery.Event<TElement, undefined> 
{
}

Code example where error acured

**Comment by wildough57** [comment]
Yeah, same thing but it might have been helpful to include the fact that this is in the **bootstrap** (4.1 in my case) type definitions.   I was able to eliminate this error by updating the @types/bootstrap  version to 4.2.2.

**Comment by DavidMorton** [comment]
I just ran into this as well. I downgraded to 3.3.6 in the meantime, and it put things back. I'm not sure what the alternative is supposed to be here.
