### ISSUE TITLE
[@types/react] ReactType not assignable to type LibraryManagedAttributes

### ISSUE THREAD

**Issue by jacobrask** [DefinitelyTyped/DefinitelyTyped#33116]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Jessidhia 

Are the errors below expected, and if that case could the ergonomics possibly be improved a bit so that you don't have to manually wrap in LibraryManagedAttributes?
 
```
function create1a<C extends ReactType>(Component: C) {
  // Type '{ children?: ReactNode; }' is not assignable to type 'LibraryManagedAttributes<C, any>'.
  const WrappedComponent: React.FC = props => <Component {...props} />
  return WrappedComponent
}

function create1b<C extends ReactType>(Component: C) {
  const WrappedComponent: React.FC<
    JSX.LibraryManagedAttributes<C, ComponentPropsWithRef<C>>
  > = props => <Component {...props} />
  return WrappedComponent
}

function create2a<C extends ReactType>(Component: C) {
  // Type 'ComponentPropsWithRef<C> & { ref: Ref<C>; children?: ReactNode; }' is not assignable to type 'IntrinsicAttributes & LibraryManagedAttributes<C, any>'.
  const WrappedComponent = forwardRef<C, ComponentPropsWithRef<C>>(
    (props, ref) => <Component {...props} ref={ref} />
  )
  return WrappedComponent
}

function create2b<C extends ReactType>(Component: C) {
  const WrappedComponent = forwardRef<C, JSX.LibraryManagedAttributes<C, ComponentPropsWithRef<C>>>((props, ref) => <Component {...props} ref={ref} />)
  return WrappedComponent
}
```

**Comment by Jessidhia** [comment]
That is correct. You didn't specify that the component you may want to wrap must be able to accept `children`, but the component you are producing will pass `children` to it anyway.

The problem is not with `ReactType` but with `React.FC` and its magic `children` 😒

I do want to find a more ergonomic pattern, though.

**Comment by jacobrask** [comment]
I see, nothing really immediately actionable here then, thanks anyway
