### ISSUE TITLE
Incorrect type for @types/node ChildProcess.stdio

### ISSUE THREAD

**Issue by hoehrmann** [DefinitelyTyped/DefinitelyTyped#33125]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick, @rbuckton 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5f59f3dc7a0965fb1767cf13c670c633bbbbf0a8/types/node/child_process.d.ts#L10 maps `ChildProcess.stdio` to a 3-tuple, but per https://nodejs.org/api/child_process.html#child_process_subprocess_stdio it's an array that can have more than three elements.

**Comment by SimonSchick** [comment]
Can you please provide a case when stdio would have more than 3 elements?
Is there any applicable pattern for this?
What we should definately do is mark those all `| null`.

**Comment by hoehrmann** [comment]
When you `spawn` a child process with `SpawnOptions.stdio` set to e.g. `['pipe', 'pipe', 'pipe', 'pipe']`.
