### ISSUE TITLE
[@types/jest] Missing dependency on @types/jest-diff

### ISSUE THREAD

**Issue by wolfy1339** [DefinitelyTyped/DefinitelyTyped#33124]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @ahnpnl @joshuakgoldberg @UselessPickles @r3nya @hotell @sebal @andys8 @antoinebrault

If you do not mention the authors the issue will be ignored.

I tried to build a project that has tests using jest, and the TypeScript compiler complained that it couldn't find the definition file for `jest-diff`, now of course I can install them manually and the error goes away, but it's needed for the definition file, so why is it not listed as a dependency

**Comment by VincentLanglet** [comment]
@wolfy1339 It is now, take the last version of `@types/jest`
