### ISSUE TITLE
kue config and callback interfaces

### ISSUE THREAD

**Issue by Diluka** [DefinitelyTyped/DefinitelyTyped#33147]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/kue` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - @drudge
  - @amiram 
  - @pc-jedi 
  - @deerawan 

If you do not mention the authors the issue will be ignored.

Please define the interfaces of configs and callbacks

**Comment by pc-jedi** [comment]
@Diluka Could you gave some more details? Maybe a short example of what is not defined?

**Comment by Diluka** [comment]
## Config objects' interfaces:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/72a3259557af036e821130e926c21fedb61933bc/types/kue/index.d.ts#L166

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/72a3259557af036e821130e926c21fedb61933bc/types/kue/index.d.ts#L28-L29

## Listener handler functions' params:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/72a3259557af036e821130e926c21fedb61933bc/types/kue/index.d.ts#L44-L53

**Comment by Diluka** [comment]
As document says https://github.com/Automattic/kue#pause-processing
There is missing parameter.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/72a3259557af036e821130e926c21fedb61933bc/types/kue/index.d.ts#L36
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/72a3259557af036e821130e926c21fedb61933bc/types/kue/index.d.ts#L66
