### ISSUE TITLE
[@types/react-big-calendar] Type the drag and drop addon

### ISSUE THREAD

**Issue by TomasHubelbauer** [DefinitelyTyped/DefinitelyTyped#33224]
@piotrwitek @paustint @pikpok @eps1lon @strongpauly @janb87 @ldthorne @jquense

I have figured out how to type the react big calendar drag and drop addon, but I am not sure how to contribute this to the typings file. I don't think I can just drop this code block in the `index.d.ts` file, if I'm wrong on that, I'll be happy to open a PR and do that.

The HOC returns the original calendar enriched by three props you can see below.

```typescript
declare module 'react-big-calendar/lib/addons/dragAndDrop' {
    import BigCalendar, { BigCalendarProps, Event } from 'react-big-calendar';

    type withDragAndDropProps<TEvent> = {
        onEventDrop: (args: { event: TEvent, start: stringOrDate, end: stringOrDate, allDay: boolean }) => void;
        onEventResize: (args: { event: TEvent, start: stringOrDate, end: stringOrDate, allDay: boolean }) => void;
        resizable: boolean;
    };

    declare class DragAndDropCalendar<TEvent extends Event = Event, TResource extends object = object>
        extends React.Component<BigCalendarProps<TEvent, TResource> & withDragAndDropProps<TEvent>>, {}

    function withDragAndDrop(calendar: typeof BigCalendar): typeof DragAndDropCalendar;
    export = withDragAndDrop;
};
```

If this looks okay to you and you can provide a review or guidance on how to PR this, I'll be happy to follow through.

**Comment by eps1lon** [comment]
You can add this without `declare module` by adding it to `types/react-big-calendar/lib/addons/dragAndDrop.d.ts`
