### ISSUE TITLE
[@types/forge-viewer] No parameters on callbacks in getObjectTree function

### ISSUE THREAD

**Issue by fehaa** [DefinitelyTyped/DefinitelyTyped#33235]
- [x] I tried using the `@types/forge-viewer` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] Authors: @alansmithnbs

Hello, using forge viewer version 6.4.2 there are some parameters returned by callback that aren't mapped: 

Examples:

- onSuccess(**scope.instanceTree**) / line **38508**
- onError(**scope.propertyDbError**) / line **38511**
- onError(**'F2D files do not have an InstanceTree.'**) / line **38514**

Thanks!

**Comment by dukedhx** [comment]
Looks like they have been correctly mapped [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/forge-viewer/index.d.ts#L445):
```
getObjectTree(successCallback?: (result: InstanceTree) => void, errorCallback?: (err: any) => void): void;
```
Anything I missed?

**Comment by fehaa** [comment]
> Looks like they have been correctly mapped [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/forge-viewer/index.d.ts#L445):
> 
> ```
> getObjectTree(successCallback?: (result: InstanceTree) => void, errorCallback?: (err: any) => void): void;
> ```
> Anything I missed?

It seems that on viewer documentation there are two ways to getObjectThree:

1. The one you mentioned: https://forge.autodesk.com/en/docs/viewer/v6/reference/javascript/model/#getinstancetree (but this one doesn't have any callbacks accordingly to documentation)
2. The other one that I was referring: https://forge.autodesk.com/en/docs/viewer/v6/reference/javascript/viewer3d/#getobjecttree-onsuccesscallback-onerrorcallback

When I debug using the non-minified library, I can see the callbacks in viewer code and I also can use them e.g.:

```
private viewer: Autodesk.Viewing.Viewer3D;

...

this.viewer.getObjectTree(objectTree => {
      tree = objectTree;
}, ...);
```

Thanks for replying!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
