### ISSUE TITLE
[@types/cassandra-driver

### ISSUE THREAD

**Issue by sbell8-chwy** [DefinitelyTyped/DefinitelyTyped#33242]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/cassandra-driver` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Svjard @pc-jedi 

The [API of RetryPolicy.rethrowResult](https://docs.datastax.com/en/developer/nodejs-driver/4.0/api/module.policies/module.retry/class.RetryPolicy/#rethrow-result) indicates it returns a [DecisionInfo](https://docs.datastax.com/en/developer/nodejs-driver/4.0/api/module.policies/module.retry/type.DecisionInfo/) object.

In the type definition this is [typed differently](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cassandra-driver/index.d.ts#L118) as `{ decision: retryDecision }`. The specific problem being a missing `consistency` field that is required.

However the problem is not as simple as updating the type definition as the [actual implementation](https://github.com/datastax/nodejs-driver/blob/master/lib/policies/retry.js#L121) returns an object consistent with the type file, but not consistent with the API. Meaning the implementation is also missing the `consistency` field.

This is further complicated in that the implementation returns the result of `rethrowResult` from other methods that are typed to return a `DecisionInfo` object such as in [onWriteTimeout](https://github.com/datastax/nodejs-driver/blob/master/lib/policies/retry.js#L66).

I think the correct solution would be to update the return of `rethrowResult` to be `DecisionInfo` and update the implementation of `rethrowResult` to include the `consistentcy` field, although I have no idea where it would get an appropriate value for `consistency` in that case. Or to make `consistency` of `DecisionInfo` optional, although I think that would have a much larger impact.

**Comment by pc-jedi** [comment]
Adding @michal-b-kaminski 

To sum this up: The [implementation](https://github.com/datastax/nodejs-driver/blob/master/lib/policies/retry.js#L121) matches the [type-definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cassandra-driver/index.d.ts#L118), but differs from the [documentation](https://docs.datastax.com/en/developer/nodejs-driver/4.0/api/module.policies/module.retry/type.DecisionInfo/), right?

**Comment by smbell** [comment]
That is most of it. The only other piece is that the return value from `rethrowResult` is returned directly from other methods like `onWriteTimeout` which doesn't match either they type-definition or the documentation.

**Comment by michal-b-kaminski** [comment]
I think that `rethrowResult` should return `DecisionInfo` and that `DecisionInfo` should have both `consistency` and `useCurrentHost` optional. That would make type-definition match both implementation and documentation and would allow implementation of all use cases in TypeScript. `consistency` is not required when decision is to rethrow as it applies more to retry attempts([doc](https://github.com/datastax/nodejs-driver/blob/master/lib/policies/retry.js#L104)) and according to that comment it can be `undefined`. Same with `useCurrentHost` - you don't need that information just to rethrow an error.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
