### ISSUE TITLE
[@types/styled-components] Type variables are not passed to wrapped components correctly

### ISSUE THREAD

**Issue by dstaley** [DefinitelyTyped/DefinitelyTyped#33250]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/styled-components@4.1.10` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek, @Igmat, @lavoaster, @Jessidhia, @jkillian

If you do not mention the authors the issue will be ignored.

If I have a React component with the following signature:

    class GridLayout<T> extends React.Component<VideoLayoutProps<T>>

And I'm wrapping it with `styled-components` like this:

    const StyledGridLayout = styled(GridLayout)

`GridLayout` is no longer able to determine the type of the `items` prop, and TypeScript throws the following error on the `renderCell` prop:

```
Type '(item: string) => Element' is not assignable to type '(item: {}) => ReactNode'.
  Types of parameters 'item' and 'item' are incompatible.
    Type '{}' is not assignable to type 'string'.
```

Using the `GridLayout` component without wrapping it works as expected (the following produces no errors):

```tsx
const Layout: React.SFC = () => (
  <GridLayout
    items={['one', 'two', 'three']}
    renderCell={item => <p>{item.toLowerCase()}</p>}
  />
);
```

Here's the complete example:

```tsx
interface VideoLayoutProps<T> {
  className?: string;
  items: T[];
  renderCell: (item: T) => React.ReactNode | undefined;
}

class GridLayout<T> extends Component<VideoLayoutProps<T>> {
  public render() {
    const items = this.props.items;
    const rendered: React.ReactNode[] = [];

    for (const item of items) {
      const renderedItem = this.props.renderCell(item);
      if (renderedItem) {
        rendered.push(renderedItem);
      }
    }

    return <div className={this.props.className}>{rendered}</div>;
  }
}

const StyledGridLayout = styled(GridLayout)({});

const App: React.SFC = () => (
  <StyledGridLayout
    items={['one', 'two', 'three']}
    // This cast isn't technically necessary, but it is to produce an error on renderCell as opposed to on item.
    renderCell={(item: string) => <p>{`${item.toLowerCase()}`}</p>}
  />
);
```

**Comment by Igorbek** [comment]
It's rather a typescript bug. Generic types are not survived after manipulation. There're open discussions on TypeScript of such thing as unification (https://github.com/Microsoft/TypeScript/issues/29904, https://github.com/Microsoft/TypeScript/issues/10247). As a library typings authors, we could define overloads that allow generic parameters to flow, but it is impossible to define for arbitrary arity and it won't account for constraints. More over it is likely to break non-generic cases.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
