### ISSUE TITLE
[@types/node] Buffer missing `inspect()`

### ISSUE THREAD

**Issue by unional** [DefinitelyTyped/DefinitelyTyped#33260]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@jkomyno
@a-tarasyuk
@alvis
@r3nya
@btoueg
@brunoscheufler
@smac89
@tellnes
@touffy
@DeividasBakanas
@eyqs
@Flarna
@Hannes-Magnusson-CK
@KSXGitHub
@hoo29
@kjin
@ajafff
@islishude
@mwiktorczyk
@matthieusieben
@mohsen1
@n-e
@octo-sniffle
@parambirs
@eps1lon
@SimonSchick
@ThomasdenH
@WilcoBakker
@wwwy3y3
@ZaneHannanAU
@jeremiergz
@samuela
@kuehlein

If you do not mention the authors the issue will be ignored.

**Search Terms:** Buffer inspect

The Buffer interface is missing the `inspect()` function:

https://nodejs.org/docs/latest/api/util.html#util_util_inspect_object_options
```sh
buffer.INSPECT_MAX_BYTES#
Added in: v0.5.4
<integer> Default: 50
Returns the maximum number of bytes that will be returned when buf.inspect() is called. This can be overridden by user modules. See util.inspect() for more details on buf.inspect() behavior.

Note that this is a property on the buffer module returned by require('buffer'), not on the Buffer global or a Buffer instance.
```

I agree that it is not well documented. :)

This is how `console.log()` prints `Buffer`

```ts
console.log(Buffer.from('abcde')) //  <Buffer 61 62 63 64 65>
console.log(Buffer.from('abcde').inspect()) //  <Buffer 61 62 63 64 65>
```

Also mentioned in SO:
https://stackoverflow.com/questions/21179524/how-to-convert-node-buffer-to-string-like-console-log-show

**Comment by SimonSchick** [comment]
I think the `inspect` is deprecated in favour of the `nodejs.util.inspect.custom` symbol.
See https://github.com/nodejs/node/issues/15549
I don't think we should add that method at this point.

**Comment by SimonSchick** [comment]
Also see https://github.com/nodejs/node/blob/master/doc/api/deprecations.md#dep0079-custom-inspection-function-on-objects-via-inspect

**Comment by SimonSchick** [comment]
@basarat I think this can be closed btw

**Comment by basarat** [comment]
Thanks :rose:
