### ISSUE TITLE
@types/redux-actions - createActions does not support recursive action maps

### ISSUE THREAD

**Issue by zsgalusz** [DefinitelyTyped/DefinitelyTyped#33264]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: * @jaysoo @alexgorbatchev @alechill @alexey-pelykh @7hi4g0

If you do not mention the authors the issue will be ignored.

Using this example for `createActions` from the redux-actions [documentation](https://redux-actions.js.org/api/createaction#createactionsactionmap):
```
const actionCreators = createActions({
  APP: {
    COUNTER: {
      INCREMENT: [amount => ({ amount }), amount => ({ key: 'value', amount })],
      DECREMENT: amount => ({ amount: -amount }),
      SET: undefined // given undefined, the identity function will be used
    },
    NOTIFY: [
      (username, message) => ({ message: `${username}: ${message}` }),
      (username, message) => ({ username, message })
    ]
  }
});
```

The resulting object is expected to contain something like this:
```{
  app: {
    counter: {
      increment: action,
      decrement: action,
      set: action
    }
    notify: action
  }
}
```

However, the typings right now only support a single depth, causing errors when trying to use eg. `actionCreators.app.counter.set` (as it is expecting `actionCreators.app` to be an `ActionFunctionAny`).

Would it be possible to add support for recursive action maps to `createActions`, or at least just make them compile?

**Comment by ParadeTo** [comment]
Have the same issue.

**Comment by about0** [comment]
Hey. Any update on this issue?

**Comment by vatosarmat** [comment]
Maybe better use [https://github.com/piotrwitek/typesafe-actions](url) ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
