### ISSUE TITLE
The DirectionsWaypoint.stopover field is defined as not optional.

### ISSUE THREAD

**Issue by atsarego** [DefinitelyTyped/DefinitelyTyped#33301]
The DirectionsWaypoint.stopover field is defined as not optional, but in accordance to the documentation it is optional.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a119e48b59caa0692c96caed59f63a9bf2012343/types/googlemaps/index.d.ts#L1469

**Comment by BendingBender** [comment]
@atsarego DefinitelyTyped is a community project, most types are contributed by external authors. If you want type definitions to improve you can either wait or you contribute. Your contribution will certainly be welcome.

In this case, you didn't mention the authors of this package, so I don't think that waiting is an option here.
