### ISSUE TITLE
[@types/auth0-lock]

### ISSUE THREAD

**Issue by dandrei** [DefinitelyTyped/DefinitelyTyped#33319]
Hey everyone,

The type `Auth0LockAuthParamsOptions` is missing the definition for the field `audience`. It should be a `string`.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @carusology @goldcaddy77 @lfaudreejr @willcaul

**Comment by carusology** [comment]
Hello @dandrei,

Are you sure you're not thinking of using the [`Auth0LockAuthOptions `](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/094be5661ef104a6533b6521fb639db7c36b214c/types/auth0-lock/index.d.ts#L98) type for your purposes? That has the `audience` property, and looks to be the in the correct level of the hierarchy (under `auth` rather than under `auth.params`).

https://auth0.com/docs/libraries/lock/v11/configuration#authentication-options

**Comment by dandrei** [comment]
Hi @carusology, here's what I'm working on:

    const options: Auth0LockConstructorOptions = {
        auth: {
            params: {
                **audience**,
                scope,
            },
            redirectUrl,
            responseType,
        },
        /* other fields */
    }
     
    const lock = new Auth0Lock(clientId, domain, options);

For `audience`, TS warns:
    ```Object literal may only specify known properties, and 'audience' does not exist in type 'Auth0LockAuthParamsOptions'.```

Version: ```   "@types/auth0-lock": "^11.4.11"```

**Comment by carusology** [comment]
@dandrei 

According [to the documentation I linked](https://auth0.com/docs/libraries/lock/v11/configuration#authentication-options), you are not putting `audience` in the correct spot, and you should actually be doing the following:

```ts
const options: Auth0LockConstructorOptions = {
    auth: {
        params: {
            scope
        },
        redirectUrl,
        responseType,
        audience
    },
    /* other fields */
}
 
const lock = new Auth0Lock(clientId, domain, options);
```

I don't see a problem here with the definition.

**Comment by dandrei** [comment]
Thanks, you're right. I was confused because in the code I had worked with the `audience` under `params`. But it also works as documented and it doesn't throw any errors.
