### ISSUE TITLE
[types/@node] missing definitions for module.filename

### ISSUE THREAD

**Issue by geogeim** [DefinitelyTyped/DefinitelyTyped#33357]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick

If you do not mention the authors the issue will be ignored.

missing definitions for: 
- `module.filename`
- `module.parent`
probably others

I am checking javascript code with tsc
here's my tsconfig.json:
```
{
  "compilerOptions": {
    "noEmit": true,
    "checkJs": true,
    "allowJs": true,
    "resolveJsonModule": true, 
    "module": "commonjs",
    "lib": ["es2018"],
    "target": "es2018",
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "../*"
      ],
      "#/*": [
        "./*"
      ]
    },
    "types": [
      "node"
    ],
  },
  "exclude": [
    "node_modules",
    "public"
  ]
}
```

**Comment by SimonSchick** [comment]
Can you provide a code sample, the definitions appear to be there 🤔

**Comment by geogeim** [comment]
`test.js`: 
```
module.exports = function(){ 
  return module.parent.filename;
}
```

tsc output:
```
Marian@atomsk MSYS /d/Work/ninesix/delivery2/tst
$ tsc
test.js:2:17 - error TS2339: Property 'parent' does not exist on type '{ "D:/Work/ninesix/delivery2/tst/test": () => any; }'.

2   return module.parent.filename;
                  ~~~~~~


Found 1 error.
```

**Comment by SimonSchick** [comment]
Can you take zip up your entire work space (including package.json etc.) and zip it up, I can't repro the issue over here

**Comment by geogeim** [comment]
[tst.zip](https://github.com/DefinitelyTyped/DefinitelyTyped/files/2899115/tst.zip)

**Comment by SimonSchick** [comment]
This doesn't look like a typings problem but one related to the way TSC attempts to determine module exports in JS files, I'd raise this to the https://github.com/Microsoft/TypeScript repo.

Suggestions:
- Switch to TS.
- Try using the `export` (es modules) syntax tho.
- Do not assign to `module.*`

**Comment by geogeim** [comment]
Hey, thanks for looking into this. 
I'm using tsc as a linter for this old project. Amazingly enough it caught some issues that we were unaware of :) It will slowly get rewritten to modern js, some parts are already there but until then I guess I'll just `@ts-ignore` these.

**Comment by SimonSchick** [comment]
np, please close this issue 🙂
