### ISSUE TITLE
Missing "sanitize" option for TooltipOptions

### ISSUE THREAD

**Issue by exeba** [DefinitelyTyped/DefinitelyTyped#33404]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/bootstrap` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @denisname 

See https://github.com/twbs/bootstrap/pull/28236

**Comment by denisname** [comment]
Will look at it.

**Comment by mikebm** [comment]
FYI. This needs to be ported over to v3 typings as they are missing there too.

**Comment by RudeySH** [comment]
Yes, please reopen this issue because Bootstrap 3.4.1 also added the `sanitize` option to `TooltipOptions`.

**Comment by ws-rob** [comment]
Not sure why this is closed since it's _still_ an issue six years later...
