### ISSUE TITLE
[@types/react] Problems with PropsWithChildren

### ISSUE THREAD

**Issue by linoleum00** [DefinitelyTyped/DefinitelyTyped#33416]
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] @VincentLanglet 

We had a production deploy yesterday, everything was working just fine after lunch, and when we where ready to deploy to production, TS errors everywhere:

Type '{}' is not assignable to type 'Readonly<PropsWithChildren<Pick< ...

Everywhere where we are instantiating a redux component (without any props, as one normally would do) we are getting this kind of error.

So we had to stick with version 16.8.4 an everything worked again.

Can you help me with a proper fix for this?

**Comment by VincentLanglet** [comment]
Sure ! But it’s better with some example.
I can’t do nothing without code.

**Comment by linoleum00** [comment]
Container A:

```
const mapStateToProps = (state) => {
    return {
        propA: "test"
    };
};

const ContainerA = connect(
    mapStateToProps
)(ViewA);

export default ContainerA;
```

View A:

```
class ViewA extends React.Component<ViewPropsA, {}> {

    constructor(props) {
        super(props);
    }

    render() {
        return (
            <ContainerB/>
        );
    }
}

export default ViewA;
```

Container B:

```
const mapStateToProps = (state) => {
    return {
        propB: state.someValue,
        propC: state.someOtherValue
    };
};

const ContainerB = connect(
    mapStateToProps
)(ViewB);

export default ContainerB;
```

View B:

```
class ViewB extends React.Component<ViewPropsB, {}> {

    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div>
                    {this.props.propB}
           </div>
        );
    }
}

export default ViewB;
```

So with the new version of @types/react , I'm gettin an error on this line on ViewA =>

```
<ContainerB/>
```

Type '{}' is not assignable to type 'Readonly<PropsWithChildren<Pick<ContainerB>>, missing propB, propC.

The only way of fixing this that I found,  is by setting propB and propC con that line like this, in ViewA: 

```
class ViewA extends React.Component<ViewPropsA, {}> {

    constructor(props) {
        super(props);
    }

    render() {
        return (
            <ContainerB propB={} propC={}/>
        );
    }
}

export default ViewA;
```

**Comment by VincentLanglet** [comment]
@linoleum00 I'm sorry, I create a file with
```
// tslint:disable
import React from 'react';
import { connect } from 'react-redux';

export type ViewPropsA = {
  propA: string;
};

export class ViewA extends React.Component<ViewPropsA, {}> {
  render() {
    return <ContainerB />;
  }
}

export const mapStateToPropsA = () => {
  return {
    propA: 'test',
  };
};

export const ContainerA = connect(mapStateToPropsA)(ViewA);

export type ViewPropsB = {
  propB: string;
  propC: string;
};

export class ViewB extends React.Component<ViewPropsB, {}> {
  render() {
    return <div>{this.props.propB}</div>;
  }
}

export const mapStateToPropsB = (state: any) => {
  return {
    propB: state.someValue,
    propC: state.someOtherValue,
  };
};

export const ContainerB = connect(mapStateToPropsB)(ViewB);
```

And I have no error.
Is it possible for you to create a github repository with the error ?

I have of course the error with this code
```
export class ViewA extends React.Component<ViewPropsA, {}> {
  render() {
    return <ViewB />;
  }
}
```
Can it be something wrong with your import/export ?

**Comment by VincentLanglet** [comment]
You say you error is
> Type '{}' is not assignable to type 'Readonly<PropsWithChildren<Pick>, missing propB, propC.

You miss-copy paste it.
How did you defined your props `ViewPropsA` and `ViewPropsB` ?
Since there is a `Pick` in the error message, this is maybe something related to https://github.com/Microsoft/TypeScript/issues/28339

**Comment by jhoch** [comment]
I have an example:

```
interface AdditionalProps { ... }
const func = <P>(Component<P & AdditionalProps>): JSX.Element => {
  const props: P & AdditionalProps = ...;
  return (
    <Component {...props} />
  );
};
```
The above fails with:
```
error TS2322: Type 'P & AdditionalProps' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<P & AdditionalProps, any, any>> & Readonly<PropsWithChildren<P & AdditionalProps>>'.
  Type 'P & AdditionalProps' is not assignable to type 'Readonly<PropsWithChildren<P & AdditionalProps>>'.

           <Component
            ~~~~~~~~~


Found 1 error.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
If I modify the code to add `PropsWithChildren`, it passes:
```
interface AdditionalProps { ... }
const func = <P>(Component<P & AdditionalProps>): JSX.Element => {
  const props: PropsWithChildren<P & AdditionalProps> = ...; // <- give the type checker some help
  return (
    <Component {...props} />
  );
};
```

**Comment by VincentLanglet** [comment]
It should be good now

**Comment by jhoch** [comment]
I bumped to 16.8.8 and my above issue was resolved, thank you very much! 🎉

**Comment by visormatt** [comment]
Stumbled across this issue, seems to be resolved in recent versions, should we close this issue out?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
