### ISSUE TITLE
mongoose ObjectId

### ISSUE THREAD

**Issue by davetayls** [DefinitelyTyped/DefinitelyTyped#3345]
I am defining a Schema which includes a type ObjectId. In my JavaScript I would use `mongoose.Schema.Types.ObjectId` but when I convert it to Typescript I get the following error:

```
error TS2305: Module '"mongoose"' has no exported member 'Schema'.
```

This is odd because there is definitely an `export class Schema` in the typescript definition with a static `Types` property.

here is my Typescript code

```typescript
import mongoose = require('mongoose');

export interface IManagerSchema extends mongoose.Document {
  user: mongoose.Schema.ObjectId;
}

export var ManagerSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.ObjectId,
    ref: 'User',
    required: true
  }
});
```

I've been trying to work this out for a couple of days now so any help would be really appreciated

**Comment by Dev-Addict** [comment]
I found out the ObjectId type is now defined under Types only when you are using package @types/mongoose
so you should use it like this
`import mongoose from 'mongoose';`
`const ObjectId = mognoose.Types.ObjectId`

**Comment by sisygoboom** [comment]
> I use this code in my model module:
> 
> ```ts
> import mongoose = require('mongoose');
> 
> export class ObjectId implements mongoose.Types.ObjectId {}
> ```

All you need is `mongoose.Types.ObjectId`, the rest is a troll
