### ISSUE TITLE
[@types/react-dom] 16.8.0 and above for some reason includes its' own react types deps

### ISSUE THREAD

**Issue by belfz** [DefinitelyTyped/DefinitelyTyped#33467]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @MartynasZilinskas  @theruther4d @Jessidhia 

If you do not mention the authors the issue will be ignored.

I've installed:
- `react 16.8.3`
- `react-dom 16.8.3`
- `@types/react 16.8.5`
- `@types/react-dom 16.8.2` (same happens for `16.8.0`)

When trying to compile the project, I get:
```
<my-project>/node_modules/@types/react-dom/index.d.ts
(90,18): Generic type 'ReactElement<P>' requires 1 type argument(s).
```
Additionally, I noticed an existence of the `node_modules/@types/react-dom/node_modules` (a `node_modules` directory under `@types/react-dom` dependency!), which in turn contains `@types/react` directory with an `index.d.ts` related to an older version of react (`16.4` mentioned in the comment at the top of the file).

I use node 8.9.1 with yarn 1.13.0 on OSX. Also checked on my mate's laptop with node 10.x, yarn 1.12.1 and OSX - same problem.

Thanks in advance.

**Comment by belfz** [comment]
anybody?

**Comment by pixelshaded** [comment]
I also ran in to this issue
