### ISSUE TITLE
[@types/react-is] 16.7.1 fails to compile

### ISSUE THREAD

**Issue by Prabhakar-17** [DefinitelyTyped/DefinitelyTyped#33481]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-is` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @AviVahl @christianchown @eps1lon 

If you do not mention the authors the issue will be ignored.

I've installed:
```
- react-is 16.8.3
- @types/react-is 16.7.1
```

When trying to compile the project I get:
```
node_modules/@types/react-is/index.d.ts:20:51 - error TS2707: Generic type 'ReactElement<P, T>' requires between 1 and 2 type arguments.
20 export function isAsyncMode(value: any): value is ReactElement;
```

Please see below screenshot for detail.
![image](https://user-images.githubusercontent.com/28021552/53595731-054be700-3bc4-11e9-97d5-5d455f92e24c.png)

I am using node 10.6.0 and yarn 1.13.0 on Windows machine. Thanks

**Comment by eps1lon** [comment]
Looks like an older version of `@types/react`.

The [latest `ReactElement`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/604c21a941c33ecc62893e5ed56e26dd6598e5eb/types/react/index.d.ts#L86) does not require type arguments. Can you upgrade your `@types/react`?

**Comment by Prabhakar-17** [comment]
I think it is the latest version as I am working on fixing an issue in jest library and I am sure they have latest version. If not, upgrading to latest would be little scary as not sure what else would break.
Is there any possible workaround you can think of?

**Comment by eps1lon** [comment]
I suspect that you soon encounter a host of other issues related with this. What version of `@types/react` are you using? With yarn you could do `yarn why @types/react`.

**Comment by Prabhakar-17** [comment]
`@types/react 16.8.1`

![image](https://user-images.githubusercontent.com/28021552/53616909-e15fc400-3c0a-11e9-9851-67fef185714a.png)

**Comment by eps1lon** [comment]
Seems like the default argument was only added recently #32990. Happy to review a PR that adds an explicit argument to `ReactElement` in the `react-is` types.

**Comment by Prabhakar-17** [comment]
To which version `@types/react-is `should be rolled-back? I tried upgrading `@types/react `but that didn't worked as there are other libraries that depend on it and the dependency hoisting comes into picture.
![image](https://user-images.githubusercontent.com/28021552/53732455-058a0200-3ea4-11e9-8626-1df784f45e5e.png)

**Comment by eps1lon** [comment]
@Prabhakar-17 I'm not sure. Just look through bisect the versions until you find the on that introduced `ReactElement`. 

When it comes to `@types` packages you have to do some manual surgery with your lockfile to force force a single `@types/react` version. You can post the entries that declare the used `@types/react` version and I can create a patch for you that results in a single `@types/react` version.

**Comment by Prabhakar-17** [comment]
Thanks @eps1lon Upgrading to the latest version as you mentioned, solved the issue.
