### ISSUE TITLE
If React Hooks surport  useState(await ...) to getData,we can used in ssr be better

### ISSUE THREAD

**Issue by dazjean** [DefinitelyTyped/DefinitelyTyped#33495]
I am new gay。
we konw  `Hooks can only be called inside the body of a function component`,but  if hooks can suppert it  we can easy get Default data in ssr,becauces  effect not be call by ssr

Example
```
let APP =  async() => {
    let initState = async () => {
        let response = await fetch('http://localhost:9991/mock/count.json');
        let listData = await response.json();
        return listData.count;
    };
    const [count, setCount] = useState(await initState());
    return (
        <div>
                <span>Count:{count}</span>
        </div>
    );
};


```

**Comment by vegtelenseg** [comment]
Hello,

I am not sure if I understand the issue you are raising. Could you please provide more detail?

Thank you

Siya

**Comment by dazjean** [comment]
OMG Sorry, I guess it was the wrong door. I don't know why I asked you the question of react. I will close this issue.
I made a mistake.
