### ISSUE TITLE
[infra] How to write tests when one test requires a newer typescript version than the rest

### ISSUE THREAD

**Issue by ExE-Boss** [DefinitelyTyped/DefinitelyTyped#33491]
- [x] I tried writing the `@types/tape-async` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ExE-Boss

---

In https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33478, I’ve got the main test file which works with all supported TypeScript versions, and then I’ve got tests that require TypeScript&nbsp;2.1 and TypeScript&nbsp;2.3, how do I make it so that the build doesn’t fail?

---

I&nbsp;tried putting `// TypeScript Version: 2.x` at&nbsp;the&nbsp;top, but&nbsp;it&nbsp;didn’t&nbsp;help:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cbe9422ac4bbf8bcc9addbdc04c8e317dd4b089a/types/tape-async/test/tape-async.async.test.ts#L1 https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cbe9422ac4bbf8bcc9addbdc04c8e317dd4b089a/types/tape-async/test/tape-async.generators.test.ts#L1

There’s also [`tape-async.test.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cbe9422ac4bbf8bcc9addbdc04c8e317dd4b089a/types/tape-async/test/tape-async.test.ts), which works with all supported TypeScript versions.

**Comment by sandersn** [comment]
Only `index.d.ts` supports the typescript version comment. You can't specify different versions for different test files. 

For your case, I would just require TS 2.3 for the whole project. At this point, the only people using TS 2.3 and below are either (1) maintaining an old code base or (2) adding to an old code base. In case (1), they are not going to start consuming type-async. In case (2), they will already have a collection of d.ts files they had to modify for compatibility, and they can just add type-async to this collection.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
