### ISSUE TITLE
Linq Dictionary declaration seems wrong

### ISSUE THREAD

**Issue by jesuslpm** [DefinitelyTyped/DefinitelyTyped#3350]
I think it should be like this:

    interface Dictionary<TKey, TValue> {
        Add(key: TKey, value: TValue): void;
        Get(key: TKey): TValue;
        Set(key: TKey, value: TValue): boolean;
        Contains(key: TKey): boolean;
        Clear(): void;
        Remove(key: TKey): void;
        Count(): number;
        ToEnumerable(): Enumerable<KeyValuePair<TKey, TValue>>;
    }

**Comment by michalgra** [comment]
I've sent a pull request #9655
