### ISSUE TITLE
[@types/aws-lambda] 8.10.19 - wrong SQSMessageAttribute interface definition

### ISSUE THREAD

**Issue by dlancer** [DefinitelyTyped/DefinitelyTyped#33514]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/aws-lambda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @darbio @skarum @StefH @buggy 

If you do not mention the authors the issue will be ignored.

Imho this interface definition is wrong.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1ce60bdc07f10e0b076778c6c953271c072bc894/types/aws-lambda/index.d.ts#L881-L885

Should be something like this:

```TypeScript
export interface SQSMessageAttribute {
    stringValue?: string;
    binaryValue?: string;
    stringListValues?: Array<string>;
    binaryListValues?: Array<any>;
    dataType: string;
}
```

**Comment by darbio** [comment]
@dlancer how have you come to this conclusion? More info and references please.

**Comment by therockstorm** [comment]
[Here's a reference](https://github.com/aws/aws-sdk-js/blob/master/apis/sqs-2012-11-05.normal.json#L923:L955). But as @dlancer shows, they're not capitalized in the actual message.
