### ISSUE TITLE
@types/selenium-webdriver@3.0.15 incorrectly implements IThenable

### ISSUE THREAD

**Issue by mehmetzahid** [DefinitelyTyped/DefinitelyTyped#33510]
Angular project build fails with @types/selenium-webdriver@3.0.15 and typescript@3.2.4.
Downgrading to @types/selenium-webdriver@3.0.4 and still using typescript@3.2.4 makes build complete successfully. (This suggestion was made in a similar problem in issue: #19682, might be a similar problem).

Angular project build output:

`ERROR in node_modules/@types/selenium-webdriver/index.d.ts(843,13): error TS2430: Interface 'IThenable<T>' incorrectly extends interface 'PromiseLike<T>'.
  Types of property 'catch' are incompatible.
    Type '<TResult = never>(onrejected?: (reason: any) => TResult | PromiseLike<TResult>) => import("/Users/noxthron/Sources/Angular/safir-depo-frontend/node_modules/@types/selenium-webdriver/index").promise.Promise<T | TResult>' is not assignable to type '<TResult = never>(onrejected?: (reason: any) => TResult | PromiseLike<TResult>) => Promise<T | TResult>'.
      Type 'Promise<TResult | T>' is missing the following properties from type 'Promise<TResult | T>': [Symbol.toStringTag], finally
node_modules/@types/selenium-webdriver/index.d.ts(1015,5): error TS2416: Property 'then' in type 'Promise<T>' is not assignable to the same property in base type 'IThenable<T>'.
  Type '<TResult1 = T, TResult2 = never>(onfulfilled?: (value: T) => TResult1 | PromiseLike<TResult1>, onrejected?: (reason: any) => TResult2 | PromiseLike<TResult2>) => Promise<TResult1 | TResult2>' is not assignable to type '<TResult1 = T, TResult2 = never>(onfulfilled?: (value: T) => TResult1 | PromiseLike<TResult1>, onrejected?: (reason: any) => TResult2 | PromiseLike<TResult2>) => PromiseLike<TResult1 | TResult2>'.
    Type 'Promise<TResult1 | TResult2>' is not assignable to type 'PromiseLike<TResult1 | TResult2>'.
      Types of property 'then' are incompatible.
        Type '<TResult1 = TResult1 | TResult2, TResult2 = never>(onfulfilled?: (value: TResult1 | TResult2) => TResult1 | PromiseLike<TResult1>, onrejected?: (reason: any) => TResult2 | PromiseLike<TResult2>) => Promise<...>' is not assignable to type '<TResult1 = TResult1 | TResult2, TResult2 = never>(onfulfilled?: (value: TResult1 | TResult2) => TResult1 | PromiseLike<TResult1>, onrejected?: (reason: any) => TResult2 | PromiseLike<TResult2>) => PromiseLike<...>'.
          Type 'Promise<TResult1 | TResult2>' is not assignable to type 'PromiseLike<TResult1 | TResult2>'.
            Types of property 'catch' are incompatible.
              Type '<TResult = never>(onrejected?: (reason: any) => TResult | PromiseLike<TResult>) => import("/Users/noxthron/Sources/Angular/safir-depo-frontend/node_modules/@types/selenium-webdriver/index").promise.Promise<TResult1 | TResult2 | TResult>' is not assignable to type '<TResult = never>(onrejected?: (reason: any) => TResult | PromiseLike<TResult>) => Promise<TResult1 | TResult2 | TResult>'.
                Type 'Promise<TResult1 | TResult2 | TResult>' is missing the following properties from type 'Promise<TResult1 | TResult2 | TResult>': [Symbol.toStringTag], finally
node_modules/@types/selenium-webdriver/index.d.ts(1015,5): error TS2416: Property 'then' in type 'Promise<T>' is not assignable to the same property in base type 'PromiseLike<T>'.
  Type '<TResult1 = T, TResult2 = never>(onfulfilled?: (value: T) => TResult1 | PromiseLike<TResult1>, onrejected?: (reason: any) => TResult2 | PromiseLike<TResult2>) => Promise<TResult1 | TResult2>' is not assignable to type '<TResult1 = T, TResult2 = never>(onfulfilled?: (value: T) => TResult1 | PromiseLike<TResult1>, onrejected?: (reason: any) => TResult2 | PromiseLike<TResult2>) => PromiseLike<TResult1 | TResult2>'.
    Type 'Promise<TResult1 | TResult2>' is not assignable to type 'PromiseLike<TResult1 | TResult2>'.
node_modules/@types/selenium-webdriver/index.d.ts(1040,5): error TS2416: Property 'catch' in type 'Promise<T>' is not assignable to the same property in base type 'PromiseLike<T>'.
  Type '<TResult = never>(onrejected?: (reason: any) => TResult | PromiseLike<TResult>) => import("/Users/noxthron/Sources/Angular/safir-depo-frontend/node_modules/@types/selenium-webdriver/index").promise.Promise<T | TResult>' is not assignable to type '<TResult = never>(onrejected?: (reason: any) => TResult | PromiseLike<TResult>) => Promise<T | TResult>'.
    Type 'Promise<TResult | T>' is missing the following properties from type 'Promise<TResult | T>': [Symbol.toStringTag], finally
node_modules/@types/selenium-webdriver/index.d.ts(4746,3): error TS2416: Property 'serialize' in type 'WebElement' is not assignable to the same property in base type 'Serializable<IWebElementId>'.
  Type '() => Promise<IWebElementId>' is not assignable to type '() => IWebElementId | IThenable<IWebElementId>'.
    Type 'Promise<IWebElementId>' is not assignable to type 'IWebElementId | IThenable<IWebElementId>'.
      Type 'Promise<IWebElementId>' is not assignable to type 'IThenable<IWebElementId>'.
        Types of property 'then' are incompatible.
          Type '<TResult1 = IWebElementId, TResult2 = never>(onfulfilled?: (value: IWebElementId) => TResult1 | PromiseLike<TResult1>, onrejected?: (reason: any) => TResult2 | PromiseLike<TResult2>) => Promise<TResult1 | TResult2>' is not assignable to type '<TResult1 = IWebElementId, TResult2 = never>(onfulfilled?: (value: IWebElementId) => TResult1 | PromiseLike<TResult1>, onrejected?: (reason: any) => TResult2 | PromiseLike<TResult2>) => PromiseLike<TResult1 | TResult2>'.
            Type 'Promise<TResult1 | TResult2>' is not assignable to type 'PromiseLike<TResult1 | TResult2>'.`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
