### ISSUE TITLE
[@types/grecaptcha]

### ISSUE THREAD

**Issue by JustFly1984** [DefinitelyTyped/DefinitelyTyped#33540]
Add support for Type definitions for Google Recaptcha 3.0

**Comment by JustFly1984** [comment]
Currently with v3 I see errors:

- grecaptcha.execute()
  Expected 0-1 arguments, but got 2.ts(2554)

- grecaptcha.ready
  Property 'ready' does not exist on type 'ReCaptcha'.ts(2339)

**Comment by RohrerF** [comment]
@DethAriel / @rafaeltavares how would that be done? create a new folder v2 and v3 and do the updated api there to not break the current or just update the existing and make a 3.x.x release?

**Comment by rafaeltavares** [comment]
@RohrerF It seems the v3 release doesn't introduce any API incompatibilities or deprecates the v2.
In that case, overloading the method `execute` and defining the method `ready` shall do the trick.
A 3.x release also seems appropriate.
