### ISSUE TITLE
react-jsonschema-form type declaration does not compile

### ISSUE THREAD

**Issue by RobbeB** [DefinitelyTyped/DefinitelyTyped#33582]
- [x] I tried using the `@types/react-jsonschema-form` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @iamdanfox @iplus26 @phbou72 @LucianBuzzo @sbusch 

The index.d.ts file does not compile on React 16.6.3 & typescript 3.3.3333
Issue: React.ReactElement required 1 type argument but none is provided.

**Comment by medfreeman** [comment]
So as said in #33808 , this has been fixed in [`@types/react`](https://www.npmjs.com/package/@types/react) latest versions (it seems since 16.8.4).
I think the issue can be be closed.
