### ISSUE TITLE
Type definitions for jQuery UI DateTimepicker

### ISSUE THREAD

**Issue by forsti83** [DefinitelyTyped/DefinitelyTyped#336]
Support for jQuery UI DateTimepicker would be very nice!

http://trentrichardson.com/examples/timepicker/
https://github.com/trentrichardson/jQuery-Timepicker-Addon

**Comment by neilsb** [comment]
This now appears to exist so this issue can be closed?

https://www.npmjs.com/package/@types/jquery.ui.datetimepicker

**Comment by olegshtch** [comment]
Why it is named `@types/jquery.ui.datetimepicker` while library itself is named as `jquery-ui-timepicker-addon`?

**Comment by zacnomore** [comment]
Initially added here: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/5c4144acda93492df9c75a65b5d54eb0cb6e755d

**Comment by sergey-koryshev** [comment]
`beforeShowDay` is missing: https://api.jqueryui.com/datepicker/#option-beforeShowDay
