### ISSUE TITLE
[@types/passport-github] userEmailURL missing from types definition

### ISSUE THREAD

**Issue by eak12913** [DefinitelyTyped/DefinitelyTyped#33619]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @yasupeke @mthmulders @codepunkt @ivan94

If you do not mention the authors the issue will be ignored.

Currently, if you wish to override the default Github URLs that passport-github will use for auth, then you can override `authorizationURL` and `userProfileURL` fields with custom values. 

In the original implementation setting `userEmailURL` was not necessary because the emails API URL was hard coded to be `${userProfileURL}/emails`. See the original code [here](https://github.com/jaredhanson/passport-github/blob/master/lib/strategy.js#L138)

In the newer implementation, a separate `userEmailURL` is required. See the newer code [here](https://github.com/cfsghost/passport-github/blob/master/lib/strategy.js#L125)

If you don't pass this optional parameter then the strategy will revert to sending the request for emails to github.com rather than your custom github.

**Comment by eak12913** [comment]
PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33621

**Comment by SimonSchick** [comment]
pls close

**Comment by eak12913** [comment]
Issue is confirmed resolved after updating to version `1.2.4` after https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33621 was merged.
