### ISSUE TITLE
[Update] Update @types/keytar to 4.4.1

### ISSUE THREAD

**Issue by queeniema** [DefinitelyTyped/DefinitelyTyped#33635]
The latest version of `keytar` is 4.4.1 and the current type definitions are for 4.0.2. It is missing [`findCredentials`](https://github.com/atom/node-keytar#findcredentialsservice) which I believe was added in 4.1.0.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @miniak, @shiftkey, @juturu

**Comment by shiftkey** [comment]
@queeniema would you be interested in submitting a PR to add in the new API?
