### ISSUE TITLE
Can't resolve 'fs'/'stream'/'zlib

### ISSUE THREAD

**Issue by sabrioezer** [DefinitelyTyped/DefinitelyTyped#33650]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/pdfkit` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @erichillah 

I have installed the packages with npm commands :
npm install pdfkit --save and npm install @types/pdfkit --save

When I try to use the pdfkit like the example in their webpage, [http://pdfkit.org/docs/getting_started.html](url),   I get the errors:

```
ERROR in ./node_modules/brotli/dec/dictionary-browser.js
Module not found: Error: Can't resolve 'fs' in '\node_modules\brotli\dec'
ERROR in ./node_modules/fontkit/index.js
Module not found: Error: Can't resolve 'fs' in '\node_modules\fontkit'
ERROR in ./node_modules/linebreak/src/linebreaker.js
Module not found: Error: Can't resolve 'fs' in '\node_modules\linebreak\src'
ERROR in ./node_modules/pdfkit/js/pdfkit.es5.js
Module not found: Error: Can't resolve 'fs' in '\node_modules\pdfkit\js'
ERROR in ./node_modules/png-js/png-node.js
Module not found: Error: Can't resolve 'fs' in '\node_modules\png-js'
ERROR in ./node_modules/unicode-properties/index.js
Module not found: Error: Can't resolve 'fs' in '\node_modules\unicode-properties'
ERROR in ./node_modules/iconv-lite/lib/streams.js
Module not found: Error: Can't resolve 'stream' in '\node_modules\iconv-lite\lib'
ERROR in ./node_modules/iconv-lite/lib/extend-node.js
Module not found: Error: Can't resolve 'stream' in '\node_modules\iconv-lite\lib'
ERROR in ./node_modules/pdfkit/js/pdfkit.es5.js
Module not found: Error: Can't resolve 'stream' in '\node_modules\pdfkit\js'
ERROR in ./node_modules/restructure/src/EncodeStream.js
Module not found: Error: Can't resolve 'stream' in '\node_modules\restructure\src'
ERROR in ./node_modules/pdfkit/js/pdfkit.es5.js
Module not found: Error: Can't resolve 'zlib' in '\node_modules\pdfkit\js'
ERROR in ./node_modules/png-js/png-node.js
Module not found: Error: Can't resolve 'zlib' in '\node_modules\png-js'
```

Did I forget something/ make some mistake by installation?
Thanks for help

**Comment by SimonSchick** [comment]
Add `node` in the `types` section in your `tsconfig` file.

**Comment by sabriozer33** [comment]
It didn't work :(

**Comment by MrCircuit** [comment]
Same for me :-(

**Comment by SimonSchick** [comment]
Please post minimal repros.

**Comment by MrCircuit** [comment]
I've got exactly the same setup and behaviour as the creator of the thread.

**Comment by erichillah** [comment]
@sabriozer33 Please post minimal repros, this looks more like a node error rather than a ts compile error. if you're using webpack check this repo https://github.com/blikblum/pdfkit-webpack-example for webpack configuration.

**Comment by sabriozer33** [comment]
https://github.com/sabriozer33/pdfkit-try

sorry for late answer. this is my first repo :)

**Comment by SimonSchick** [comment]
Yea this is webpack not loading polyfills for packages, this is not TS/DT related.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
