### ISSUE TITLE
[@types/react] Destructured props inferred as required

### ISSUE THREAD

**Issue by matt-tingen** [DefinitelyTyped/DefinitelyTyped#33742]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Asana @AssureSign @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @pshrmn @threepointone @saranshkataria 

I'm working on migrating a React project from JS to TS. I keep running into this issue when rendering JS components from TS. If the JS component is a functional component with the props destructured, TS considers all props required:
```javascript
// B.js
import React from 'react'
import PropTypes from 'prop-types'

const B = ({ content }) => <div>{content}</div>

B.propTypes = {
  content: PropTypes.string,
}

export default B
```

```typescript
// A.tsx
import React from 'react'
import B from './B'

// Property 'content' is missing in type '{}' but required in type '{ content: string; }'.ts(2741)
const A = () => <B />

export default A
```

If `B` is defined as `const B = props => <div>{props.content}</div>`, `content` is correctly inferred as optional. Ideally, I would like to be able to consume such JS components without modification, though.

I tried to dig into the issue, but I don't fully understand where this inference is occurring; whether it's in the definition of `ReactManagedAttributes`/`LibraryManagedAttributes`, TypeScript's handling of `LibraryManagedAttributes`, or `InferProps` in `@types/prop-types`.

**Comment by ferdaber** [comment]
This is correct behavior and not specific to React or JSX. If you have a function like this:
```ts
declare function myFunction({ foo, bar }): any
```

The first parameter (the destructured one) is inferred to have this type:
```ts
type param0 = {
  foo: any
  bar: any
}
```

The only way to get TypeScript to infer as optional is to either set a default value in the destructure, or annotate it properly:
```ts
// either works
declare function myFunction({ foo = null, bar = false }): any
type inferred_param0 = {
  foo?: any
  bar?: boolean
}

declare function myFunction({ foo, bar }: { foo?: any, bar?: boolean }): any
```

**Comment by matt-tingen** [comment]
I understand this to be the case for functions, but when used as a component in JSX, there does appear to inference from `propTypes` iff the props are not destructured. What is causing that inference?

**Comment by ferdaber** [comment]
Gotcha. The logic mostly contained in here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6a5529e838d9386fb6567296e84d945e25805281/types/react/index.d.ts#L2738

Essentially `JSX.LibraryManagedAttributes` will try its best to guess what the most appropriate type for each prop is, based on the definition of a function component's parameter, and prop types. If a property exists in the inferred type of the `prop` parameter of the function component, it will use the optionality modifier of that property, but the type of the corresponding propType, IF it is of type `any`, otherwise it will use the type of that property.

Regardless, a limitation of this conditional type is that it can't conditionally grab the optionality modifier from the propType, which by default would be optional unless you use `.required`.

**Comment by matt-tingen** [comment]
@ferdaber Thanks for the pointer! I've made some progress on understanding the issue.

Playing around with `MergePropTypes`, it seems the issue is due to mapping over the keys in `P` (`{ content: any }` derived from the function param), but (sometimes) using that key in `T` (`{ content?: string }` inferred via `PropTypes.InferProps`). When this happens, TypeScript seems to lose the `?` property modifier.

I was able to distill the issue down to a minimal repro outside of DefinitelyTyped, so I made a separate Typescript issue for that. For clarity, here is a minimal repro of the issue as it relates to `@types/react`:
```typescript
// Expected: okay
// Observed: Property 'bar' is missing in type '{}' but required in type '{ bar: string | null | undefined; }'.
const foo: JSX.LibraryManagedAttributes<
  { propTypes: { bar: typeof PropTypes.string } },
  { bar: any }
> = {};
```

Even if the TS issue were to be resolved, it would only be for homomorphic types. Since the parameter type and `propTypes` may not be homomorphic, we would want to fix this in `@types/react`, as well.
I do believe that is possible am working on a PR.

**Comment by matt-tingen** [comment]
I am still working on a PR, but have been busy lately.

In the mean time, if anyone else runs into this issue, there's a simple workaround for components which don't have `defaultProps`:

```javascript
import React from "react";
import PropTypes from "prop-types";

/** @param {PropTypes.InferProps<typeof propTypes>>} */
const Foo = ({ content }) => <div>{content}</div>;

// `propTypes` has to be its own variable for the `@param` to work.
const propTypes = {
  content: PropTypes.string
};
Foo.propTypes = propTypes;

export default Foo;
```

For components that do have `defaultProps`, you may be able to move the defaults into the destructuring without too much effort.

**Comment by ferdaber** [comment]
This workaround feels very roundabout, how about this? This is closer to how regular TS is written anyways:
```tsx
const Foo = ({ content }: { content?: string }) => <div>{content}</div>

Foo.propTypes = {
  content: PropTypes.string
}
```

**Comment by matt-tingen** [comment]
That would be fine if there's just a few simple props. For my use case, there are often lots of props potentially with `PropTypes.shape` and it was never my intention to touch this particular component. Since we already have `propTypes`, I just want to use the inferred props and avoid spending time on these JS components.
