### ISSUE TITLE
[@types/react-native] maxFontSizeMultiplier prop not supported 

### ISSUE THREAD

**Issue by jessamp** [DefinitelyTyped/DefinitelyTyped#33792]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:  @alloy @huhuanming @iRoachie @timwangdev @kamal @nelyousfi @alexdunne @swissmanu @bm-software @tkrotoff @a-tarasyuk @mvdam

If you do not mention the authors the issue will be ignored.

I was trying to use the maxFontSizeMultiplier prop and was receiving an error because it wasn't supported. Would it be possible to add this prop in? 

For reference:
https://facebook.github.io/react-native/docs/text#maxfontsizemultiplier

**Comment by jessamp** [comment]
@saranshkataria shouldn't this work for android as well?

**Comment by saranshkataria** [comment]
@jessamp I misread the docs initially and fixed it in the next commit
