### ISSUE TITLE
[@types/react-redux] type of "pre-built" connector

### ISSUE THREAD

**Issue by tianhuil** [DefinitelyTyped/DefinitelyTyped#33793]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo @pdeva @Kallikrein @jrakotoharisoa @apapirovski @surgeboris @soerenbf

*bug*: I'm trying to build a `connect(mapState, mapDispatch)` in a file to be re-used by different view components.  The underlying javascript code works [see this commit](https://github.com/tianhuil/todo-react/commit/382c9532cb03d781ea775bb9eeb824b48107a5f1) but you loose typing on the resulting "connected" component (e.g. `StatusButton` was transformed in [Header.tsx](https://github.com/tianhuil/todo-react/blob/382c9532cb03d781ea775bb9eeb824b48107a5f1/src/components/Header.tsx) and is not being type-checked).  This appears to be because the `connect` does not know the `ownProps` that will be passed into it when it's being used as an HOC.

My attempts to explicitly annotate the "connector" have failed:
- [Attempt 1](https://github.com/tianhuil/todo-react/pull/1/commits/71c75ef9fd05872dcc190825e27ec0580a538aec)
- [Attempt 2](https://github.com/tianhuil/todo-react/pull/1/commits/5234df7e278a0f1f0859a63389439e75f51aaebe)

*What is the current behavior?*
Both of them give the following errors
```
Argument of type 'ComponentType<T & FilterProps>' is not assignable to parameter of type 'ComponentType<Matching<{ stateStatus: Status; stateQuery: string; display: (completed: boolean, text: string) => boolean; } & { push: (__0: PushObj) => void; }, T & FilterProps>>'.
  Type 'ComponentClass<T & FilterProps, any>' is not assignable to type 'ComponentType<Matching<{ stateStatus: Status; stateQuery: string; display: (completed: boolean, text: string) => boolean; } & { push: (__0: PushObj) => void; }, T & FilterProps>>'.
    Type 'ComponentClass<T & FilterProps, any>' is not assignable to type 'ComponentClass<Matching<{ stateStatus: Status; stateQuery: string; display: (completed: boolean, text: string) => boolean; } & { push: (__0: PushObj) => void; }, T & FilterProps>, any>'.
      Type 'T & FilterProps' is not assignable to type 'Matching<{ stateStatus: Status; stateQuery: string; display: (completed: boolean, text: string) => boolean; } & { push: (__0: PushObj) => void; }, T & FilterProps>'.ts(2345)
```

*What is the expected behavior?*
I expected both Attempt 1 and Attempt 2 to succeed.  I don't the error makes sense because `T` is assignable to `Matching<T, T>` for all objects `T`, which is basically what the last error is claiming is not assignable.

**Comment by tianhuil** [comment]
- Authors: @tkqubo @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo @pdeva @Kallikrein @jrakotoharisoa @apapirovski @surgeboris @soerenbf - any thoughts on this issue?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
