### ISSUE TITLE
[mongoose] mongoose.Model<...> does not satisfy the constraint Document

### ISSUE THREAD

**Issue by Xenya0815** [DefinitelyTyped/DefinitelyTyped#33824]
**Version:**
- `@types/mongoose`: 4.7.44

**Code**

```ts
interface Foo extends mongoose.Document {
  bar: number;
}

type Entry = mongoose.Model<Foo>;
```

**Expected behavior:**
It should be fine.

**Actual behavior:**
I get the error `Type 'Foo' does not satisfy the constraint 'Document'.`

With version 4.7.43 the code works.

- [x] I tried using the `"@types/mongoose@4.7.44` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - @simonxca 
  - @horiuchi 
  - @lukasz-zak 
  - @murbanowicz

**Comment by jwalton** [comment]
I'm running into this too.  This is [the change](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/e4b587fab1a571c9e0ffd65d4d24f24f72324921#diff-044e786e3aecf933849f9822627903f7R2449) by @murbanowicz.

Changing [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1f1c65916e1d83eea71cf7b979427b33e7ea7fd5/types/mongoose/v4/index.d.ts#L2711) to:

```
    /**
     * Returns another Model instance.
     * @param name model name
     */
    model(name: string): Model<Document>;
```

Fixes this issue...  Although I admit I'm not entirely sure why.
```

**Comment by jwalton** [comment]
You also need `--strictFunctionTypes` in order to reproduce this.

**Comment by jwalton** [comment]
This is perhaps a simpler example; 

```
interface Document {
    model(name: string): Model<this>;
}

interface Model<T extends Document> {
    new (doc?: Partial<T>): T;
}

interface UserDocument extends Document {
    name: string;
}

const aUserDocument : UserDocument = {} as any;
const aDocument : Document = aUserDocument;
```

Here you'll get an error on the last line, because you can't assign `UserDocument` to `Document`.  The circular reference between Document and Model makes reasoning about this a little maddening (and is possibly the root of the problem), but basically `aUserDocument.model('foo')` returns a `Model<UserDocument>`, which has a constructor that takes a `Partial<UserDocument>`.  But, `aDocument.model('foo')` returns a `Model<Document>`, which instead has a constructor that takes a `Partial<Document>`.  In order for these constructors to be assignable to each other, `UserDocument` would have to be assignable to `Document`... but that's back to square one, so we'd have to recurse infinitely to decide if these were assignable to each other or not.

Fortunately for us, the definition of ` model(name: string): Model<this>;` is incorrect.  If you do:

```js
mongoose = require('mongoose');
Schema = mongoose.Schema;
catSchema = new Schema({name: String});
Cat = mongoose.model('Cat', catSchema);
dogSchema = new Schema({tag: String});
Dog = mongoose.model('Dog', dogSchema);
doc = new Cat({name: 'stashy'});

// Prints [ 'tag', '_id', '__v' ]
console.log(Object.keys(doc.model('Dog').schema.paths));
```

So here, even though `doc` is a `CatDocument`, calling `doc.model('Dog')` does not return a `Model<CatDocument>`.  If you change this to:

```
    model<T extends Document>(name: string): Model<T>;
```

it fixes the problem.

**Comment by jwalton** [comment]
Working on a PR...

**Comment by krzysiek3d** [comment]
You could do something like this to reuse "Entry" type if needed :)

interface Foo extends mongoose.Document {
  bar: number;
}

type Entry = mongoose.Model<Foo & Document>;

**Comment by kennyrafael** [comment]
> You could do something like this to reuse "Entry" type if needed :)
> 
> ```
> interface Foo extends mongoose.Document {
>   bar: number;
> }
> 
> type Entry = mongoose.Model<Foo & Document>;
> ```

You helped me a lot, thanks!

**Comment by ArnonAfriat** [comment]
Has anyone trying writing  a test for it?
Addressing  @jwalton example:

`interface UserDocument extends Document {
    name: string;
}`

When making the expected/mocked return object from the Model<UserDocument>, one should mock the UserDocument interface object and so needs to reproduce the mongoose.Document properties it extends. 
What is the best practice for it? what if you code is using some of the properties like .toJSON/toObject/save, these are also need to be mocked. 

What am I missing?

**Comment by charleston10** [comment]
Using NestJS with Mongoose
```
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import * as mongoose from 'mongoose';
import { Document } from 'mongoose';

export type PostDocument = Post & Document;

@Schema()
export class Post {

    @Prop({ type: String })
    message: string

    @Prop({ type: String })
    imageUrl: string

    @Prop({ type: String, required: true })
    userId: string; 

    @Prop({ type: Date })
    createdAt: Date;

    @Prop({ type: Date })
    updatedAt: Date;
}

const schema: mongoose.Schema<PostDocument> = SchemaFactory.createForClass(Post);

schema.pre<PostDocument>("save", function (next) {
    let now = new Date();

    if (!this.createdAt) {
        this.createdAt = now
    }

    this.updatedAt = now

    next();
});

export const PostSchema = schema
```

**Comment by nickerlan** [comment]
Got the same error and found out I didn't imported document form mongoose and it used some generic type instead.

`import { Document } from 'mongoose';`

**Comment by nhhockeyplayer** [comment]
>Got the same error and found out I didn't imported document form mongoose and it used some generic type instead.
this is terrible and should at least be configurable to avoid elusive errors in large codebases
