### ISSUE TITLE
[@types/jasmine] Limiting interfaces to Promise<any> is too rigid

### ISSUE THREAD

**Issue by silkentrance** [DefinitelyTyped/DefinitelyTyped#33825]
A PR for this will follow shortly. This is just for documentation purposes.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @pe8ter @SimonSchick 

## Rationale

Jasmine mostly depends on `PromiseLike<T>` and does not make use of any of the extra features that `Promise<T>` provides, namely, the `catch(...)` method is never being used.

In the type declarations for jasmine, the type is limited to just `Promise<any>` which might in effect be too rigid and should be extended so that it will support both interfaces, e.g.

```
   type PromiseOrPromiseLike = Promise<any> | PromiseLike<any>;
```

The type declarations that are now depending on `Promise<any|void>` can then be rewritten so that they will instead depend on `PromiseOrPromiseLike`.

Also, some of the async matchers, namely `toBeResolved()` and `toBeRejected()` take no argument, so these extraneous arguments should be removed from the type declaration.

**Comment by ienzam** [comment]
This PR may have got reverted during our recent changes, when we moved to 3.1.
Is this issue still valid for Jasmine 3.6?
Should we merge this back?
@silkentrance @sandersn

**Comment by sandersn** [comment]
Yes, I think it needs a re-merge. It was probably mistakenly put only in pre-3.1 types, and then I mistakenly didn't port it to the 3.1+ types.

**Comment by silkentrance** [comment]
I used `testdeck/testdeck-jasmine-seed` and it seems to work just fine with the PR not being in place. So this seems to have been resolved with the latest version of Jasmine.

**Comment by silkentrance** [comment]
I also just ran a build for testdeck and there is no longer an issue with the new typings, so everything seems to be working fine.
