### ISSUE TITLE
[@types/jasmine] Partial is not a good fit for objectContaining

### ISSUE THREAD

**Issue by silkentrance** [DefinitelyTyped/DefinitelyTyped#33820]
A PR for this is coming shortly, I just wanted to document this.

- [x] I tried using the `@types/jasmine` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick @pe8ter 

## Rationale

The interface declaration for objectContaining defines the following

```
    interface ObjectContaining<T> {
        new (sample: Partial<T>): Partial<T>;

        jasmineMatches(other: any, mismatchKeys: any[], mismatchValues: any[]): boolean;
        jasmineToString(): string;
    }
...
    function objectContaining<T>(sample: Partial<T>): ObjectContaining<T>;
```

and in the test it uses the following to test that interface

```
    it("The 'toContain' matcher is also for finding an object containing distinct properties in an Array", () => {
        const a = [{ a: "foo" }, { a: "bar" }, { b: "baz" }];

        expect(a).toContain(jasmine.objectContaining({ a: "foo" }));
        expect(a).not.toContain({ a: "quux" });
    });
```

Now, with the ts compiler option `strictFunctionTypes` set to true, these tests will fail due to a mismatch in the interface, complaining about {a?:string, b:string} | {a:string, b?:string} and {a:string, b:undefined} and so on.

As of now, the option is set to false which basically hides that issue.

It would be better to not make the interface expect a Partial, as that is defined as

```
/**
 * Make all properties in T optional
 */
type Partial<T> = {
    [P in keyof T]?: T[P];
};
```

This will eventually cause ts to infer that the Partial is either {a:string, b?: string} or {b: string, a?: string}. And passing in different objects as samples to the objectContaining matcher will now result in error as the sample never matches the partial.

From my standpoint, I want to check whether an arbitrary object matches the interface. Therefore it must be declared as any and not limited to just the known properties.

## References

See also the typings for jest, which builds on jasmine. There, ObjectContaining is not generic and objectContaining expects a sample that is of type any.

**Comment by SimonSchick** [comment]
Uhh, why was I tagged for this?

**Comment by silkentrance** [comment]
While Partial is not a good fit for the sample passed to objectContaining, the rest of all of the interfaces that provide a new() constructor like operation are also off the spec. Closing this for now, while I work things out.
