### ISSUE TITLE
ERROR in /../node_modules/@types/lodash/common/object.d.ts (1689,12): Cannot find name 'Exclude'.

### ISSUE THREAD

**Issue by faizu88** [DefinitelyTyped/DefinitelyTyped#33845]
package.json

{
  "name": "Test",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "bundle-report": "webpack-bundle-analyzer dist/stats.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.5",
    "@angular/common": "^4.2.5",
    "@angular/compiler": "^4.2.5",
    "@angular/compiler-cli": "^4.2.5",
    "@angular/core": "^4.2.5",
    "@angular/forms": "^4.2.5",
    "@angular/http": "^4.2.5",
    "@angular/platform-browser": "^4.2.5",
    "@angular/platform-browser-dynamic": "^4.2.5",
    "@angular/router": "^4.2.5",
    "@asymmetrik/ngx-leaflet": "2.6.1",
    "@asymmetrik/ngx-leaflet-draw": "2.7.1",
    "@types/angular-ui-bootstrap": "^0.13.44",
    "@types/fullcalendar": "^3.5.0",
    "@types/googlemaps": "^3.26.14",
    "@types/highcharts": "^5.0.36",
    "@types/jquery": "^2.0.46",
    "@types/jqueryui": "^1.11.35",
    "@types/leaflet": "1.2.7",
    "@types/leaflet-draw": "0.4.12",
    "@types/moment": "^2.13.0",
    "@types/node": "^6.0.79",
    "@ultimate/ngxerrors": "^1.3.0",
    "angular2-virtual-scroll": "^0.3.1",
    "babel-regenerator-runtime": "^6.5.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "dragula": "^3.7.2",
    "font-awesome": "^4.7.0",
    "fullcalendar": "^3.6.2",
    "fullcalendar-scheduler": "^1.9.3",
    "highcharts": "6.2.0",
    "jquery": "^3.2.1",
    "jquery-ui-sortable": "^1.0.0",
    "jqueryui": "^1.11.1",
    "leaflet": "1.3.1",
    "leaflet-draw": "1.0.2",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.14",
    "ng-treetable": "^1.2.3",
    "ng2-ckeditor": "1.1.9",
    "ng2-dragula": "^1.5.0",
    "ng2-pdf-viewer": "3.0.8",
    "ngx-bootstrap": "^1.9.1",
    "ngx-cookie-service": "^1.0.10",
    "ngx-malihu-scrollbar": "^1.1.2",
    "ngx-pipes": "~1.6.1",
    "ngx-restangular": "^1.0.11",
    "ngx-slick": "^0.1.3",
    "primeng": "4.2.2",
    "rxjs": "^5.1.0",
    "slick-carousel": "^1.8.1",
    "socket.io-client": "^2.0.4",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.4",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/leaflet": "1.2.7",
    "@types/leaflet-draw": "0.4.12",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "2.3.4",
    "webpack-bundle-analyzer": "^2.9.0"
  }
}

---------------------------------------------------------------------------------------------

Steps:
1. rm -rf node_modules package-lock.json
2. npm install
3. ng serve

ERROR in /../node_modules/@types/lodash/common/object.d.ts (1689,12): Cannot find name 'Exclude'.
ERROR in /../node_modules/@types/lodash/common/object.d.ts (1766,12): Cannot find name 'Exclude'.
ERROR in /../node_modules/@types/lodash/common/object.d.ts (1842,34): Cannot find name 'Exclude'.

Got this above error. Any way to solve this??

If I replace the file ("/../node_modules/@types/lodash/common/object.d.ts") with "https://codeshare.io/adWzlB" code then it works...

_Originally posted by @faizu88 in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33778#issuecomment-472460633_

**Comment by j-oliveras** [comment]
Exclude was added to typescript on version 2.8. You have a version of `@types/lodash` that needs minimum typescript 2.8.

Install the last typescript 2.3 version compatible with `npm i -D @types/lodash@ts2.3` and should work.

**Comment by faizu88** [comment]
@j-oliveras Thank you soo much dude. It's working charm. :)

**Comment by ashutosh291596** [comment]
@j-oliveras You are saviour
