### ISSUE TITLE
How do i add typings for my code

### ISSUE THREAD

**Issue by tbhaxor** [DefinitelyTyped/DefinitelyTyped#33873]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tbhaxor

If you do not mention the authors the issue will be ignored.
I want to add typings for my package
Npm Link: https://www.npmjs.com/package/metadefender
Github Link : https://github.com/tbhaxor/node-metadefender
The issue i create: https://github.com/tbhaxor/node-metadefender/issues/1

**Comment by Flarna** [comment]
Your project includes type definitions already therefore no extra definitions should be added here.
This repo holds type definitions for modules written in javascript which ship without definitions.

**Comment by tbhaxor** [comment]
@Flarna what if i want to add separate typings 
plz guide sir

**Comment by Flarna** [comment]
What do you mean with separate typings? rewrite by hand what is already generated by typescript?
Could you describe your use case?

**Comment by tbhaxor** [comment]
I mean writing typings an contributing to DefinitelyTyped Repo.
Since my project contains more than one .d.ts. So i want to know do i merge
all typings in one file i.e index.d.ts or add reference ?
Regards
---------------
Gurkirat Singh
(T3r@bYt3)

**Comment by Flarna** [comment]
I still don't understand why you would like to do this. Every user of your module `metadefender` gets the type definitions by `npm install metadefender` as the package.json has the line `"types": "./dist/index.d.ts"`.
index.d.ts imports the other d.ts files and reexports these definitions.

if you add type definitions on DefinitelyTyped it will only result in problems because double definition and different versioning.

**Comment by tbhaxor** [comment]
Thnx for help :)

Regards
---------------
Gurkirat Singh
(T3r@bYt3)
