### ISSUE TITLE
InputEvent is missing inputType, dataTransfer, getTargetRanges

### ISSUE THREAD

**Issue by fregante** [DefinitelyTyped/DefinitelyTyped#33903]
Source: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/dom-inputevent/index.d.ts
More info on mdn: https://developer.mozilla.org/en-US/docs/Web/API/InputEvent

- [x] I tried using the `@types/dom-inputevent` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @diagramatics 

Hopefully this will be added to TypeScript soon (related issue https://github.com/Microsoft/TypeScript/issues/29441)

Googlable output:

```
Argument of type '{ data: string; inputType: string; }' is not assignable to parameter of type 'InputEventInit'.
  Object literal may only specify known properties, and 'inputType' does not exist in type 'InputEventInit'.

15  		inputType: 'insertText'
```

**Comment by diagramatics** [comment]
Heya! I added `dom-inputevents` for a specific usage back then and it's definitely partially implemented just to satisfy what I'm aiming for. Happy for you to contribute and add this in if you'd like to. I don't use the package anymore sadly so there's less motivation for me to update this myself 😞

**Comment by fregante** [comment]
I'm seeing this in the official `dom.d.ts`

```ts
interface InputEventInit extends UIEventInit {
    data?: string | null;
    inputType?: string;
    isComposing?: boolean;
}
```

Incomplete but I think this can be closed for now since `input` is part of TypeScript
