### ISSUE TITLE
Aria property is missing for svg

### ISSUE THREAD

**Issue by VincentLanglet** [DefinitelyTyped/DefinitelyTyped#33910]
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei @Jessidhia @pshrmn @saranshkataria 

It seems like we can use aria property to svg element.
https://www.24a11y.com/2018/accessible-svg-icons-with-inline-sprites/

If i'm right, the svg definitions is not correct.

Svg props definitions.
```tsx
interface SVGProps<T> extends SVGAttributes<T>, ClassAttributes<T> {
    }
```
But Aria props are actually defined this way.
```tsx
interface HTMLAttributes<T> extends DOMAttributes<T> {
        /** Identifies the currently active element when DOM focus is on a composite widget, textbox, group, or application. */
        'aria-activedescendant'?: string;
        /** Indicates whether assistive technologies will present all, or only parts of, the changed region based on the change notifications defined by the aria-relevant attribute. */
        'aria-atomic'?: boolean | 'false' | 'true';

...
```

We should refactor Aria props to make both HTMLAttributes and SvgAttributes extending it.

I can do it, but can someone confirm it's right ?

**Comment by digiguru** [comment]
Looks like that's right as far as I can gleen from:
https://www.w3.org/TR/SVG/attindex.html

**Comment by VincentLanglet** [comment]
Tried this https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34555
