### ISSUE TITLE
Adding an accessToken type to the TileLayerOptions type

### ISSUE THREAD

**Issue by NathanDowner** [DefinitelyTyped/DefinitelyTyped#33949]
- [ *] I tried using the `@types/xxxx` package and had problems.
- [ *] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ *] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - The authors are:
                 Alejandro Sánchez <https://github.com/alejo90> @alejo90 
                 Arne Schubert <https://github.com/atd-schubert> @atd-schubert
                 Michael Auer <https://github.com/mcauer> @mcauer 
                 Roni Karilkar <https://github.com/ronikar> @ronikar 

There currently isnt any  property for the accessToken in the TileLayerOptions interface, for mapbox tile layers even though they seem to be required for using a mapbox map, as seen in the leaflet quick start guide: https://leafletjs.com/examples/quick-start/. As a result i'm getting the following error: 
	 "Argument of type '{ attribution: string; maxZoom: number; accessToken: string; }' is not assignable to parameter of type 'TileLayerOptions'.\n  Object literal may only specify known properties, and 'accessToken' does not exist in type 'TileLayerOptions'."

**Comment by AZITWB** [comment]
parameter  "id"  is also needed to use mapbox

**Comment by ShaneMcGowan** [comment]
parameter "id" used to work fine with mapbox, not sure what happened

**Comment by kygoh** [comment]
Even though leaflet quick start guide shows `accessToken: 'your.mapbox.access.token'` as one of its' options property, the `accessToken` property is not used at all in leaflet source.

Instead `accessToken` should just be passed as a parameter of the query string in the URL template as in the quick start guide:

`https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
