### ISSUE TITLE
Problem with mcrypt

### ISSUE THREAD

**Issue by jevilla94** [DefinitelyTyped/DefinitelyTyped#33983]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/mcrypt` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @pluma 

If you do not mention the authors the issue will be ignored.

Hello
I am using the package @types/mcrypt on a project with a ngx-admin template; built component is:

import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { TranslateService, LangChangeEvent } from '@ngx-translate/core';
import { getAlgorithmNames, getModeNames, MCrypt } from "mcrypt";

@Component({
  selector: 'ngx-recibo',
  templateUrl: './recibo.component.html',
  styleUrls: ['./recibo.component.scss'],
})
export class ReciboComponent implements OnInit {
  algos: string[];
  constructor(private translate: TranslateService) {
    this.translate.onLangChange.subscribe((event: LangChangeEvent) => {
    });
  }
  **public send() {
    algos = getModeNames();
    console.info(this.algos);
  }**
  useLanguage(language: string) {
    this.translate.use(language);
  }
  ngOnInit() {
  }
}

However, when I execute my project, this error is generated:
> ERROR in ./node_modules/bindings/bindings.js
> Module not found: Error: Can't resolve 'fs' in '/home/planestic/campus_cliente/node_modules/bindings'
> ERROR in ./node_modules/bindings/bindings.js
> Module not found: Error: Can't resolve 'path' in '/home/planestic/campus_cliente/node_modules/bindings'
> ERROR in ./node_modules/file-uri-to-path/index.js
> Module not found: Error: Can't resolve 'path' in '/home/planestic/campus_cliente/node_modules/file-uri-to-path'

**Comment by pluma** [comment]
That doesn't sound like you have a problem with the typings.

It mostly sounds like you're trying to use a package that wasn't written to work in the browser in a client-side application. I'm pretty sure mcrypt uses native bindings and there's no way to use the module in the browser.

In any case this doesn't look like it belongs here. The repo of the module in question is here: https://github.com/tugrul/node-mcrypt

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
