### ISSUE TITLE
Can the value argument of the doneFilter of JQueryGenericPromise.then() be undefined?

### ISSUE THREAD

**Issue by thdk** [DefinitelyTyped/DefinitelyTyped#34022]
- [x ] I tried using the `@types/xxxx` package and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  

- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@borisyankov
@choffmeister
@Steve-Fenton
@Diullei
@tasoili
@jasons-novaleaf
@seanski
@Guuz
@ksummerlin
@basarat
@nwolverson
@derekcicerone
@AndrewGaspar
@seikichi
@benjaminjackman
@s093294
@JoshStrobl
@johnnyreilly 
@DickvdBrink
@King2500
@leonard-thieu

For jquery v2, is it correct that the value argument of the doneFilter of deferred.then can be undefined?

```
/**
 * Allows jQuery Promises to interop with non-jQuery promises
 */
interface JQueryGenericPromise<T> {
    /**
     * Add handlers to be called when the Deferred object is resolved, rejected, or still in progress.
     * 
     * @param doneFilter A function that is called when the Deferred is resolved.
     * @param failFilter An optional function that is called when the Deferred is rejected.
     */
    then<U>(doneFilter: (value?: T, ...values: any[]) => U | JQueryPromise<U>, failFilter?: (...reasons: any[]) => any, progressFilter?: (...progression: any[]) => any): JQueryPromise<U>;

    /**
     * Add handlers to be called when the Deferred object is resolved, rejected, or still in progress.
     * 
     * @param doneFilter A function that is called when the Deferred is resolved.
     * @param failFilter An optional function that is called when the Deferred is rejected.
     */
    then(doneFilter: (value?: T, ...values: any[]) => void, failFilter?: (...reasons: any[]) => any, progressFilter?: (...progression: any[]) => any): JQueryPromise<void>;
}
```

The same for interface **JQueryDeferred<T>** where the 'value' argument of **resolve** and **resolveWith** is marked as optional.

I was hoping I could remove the question marks after the 'value' argument to fix half of the strict null check errors in my projects at once :)

I've put together a few sample to work with on stackblitz using jquery v2:
[https://stackblitz.com/edit/typescript-wwcsmm](https://stackblitz.com/edit/typescript-wwcsmm)

So, are those question marks correct?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
