### ISSUE TITLE
"SVGSVGElement" should be "SVGElement"?

### ISSUE THREAD

**Issue by snuuuz** [DefinitelyTyped/DefinitelyTyped#34033]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/d3-selection` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek @gustavderdrache  @borisyankov  @denisname 

`SVGSVGElement` in the following line seems to be a typo:
```
export type ContainerElement = HTMLElement | SVGSVGElement | SVGGElement;
```
I added the following temporary definition in my code and all is well...
```
export type ContainerElement = HTMLElement | SVGElement | SVGGElement;
```

**Comment by denisname** [comment]
I have doubts.
Could you give an example ?

**Comment by snuuuz** [comment]
Sorry. Wasn't caught up to latest Typescript - current version has definition for SVGSVGElement. Closing.
