### ISSUE TITLE
[@types/react-dom] error TS2707: Generic type 'ReactElement<P, T>' requires between 1 and 2 type arguments.

### ISSUE THREAD

**Issue by wolfy1339** [DefinitelyTyped/DefinitelyTyped#34041]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @MartynasZilinskas @theruther4d @Jessidhia

If you do not mention the authors the issue will be ignored.

I upgraded the types for `react-dom` and this issue was logged by tsc
```
> dashboard@0.1.0 pre-build /home/travis/build/hellomouse/GNS/dashboard
> tsc -p tsconfig.json && cd lib/src && eslint --fix . && cd ../.. && node scripts/moveCSS.js
node_modules/@types/react-dom/index.d.ts:90:18 - error TS2707: Generic type 'ReactElement<P, T>' requires between 1 and 2 type arguments.
90         element: ReactElement[],
                    ~~~~~~~~~~~~
Found 1 error.
```

**Comment by wolfy1339** [comment]
Ping?!

**Comment by wolfy1339** [comment]
Is anyone going to respond to this issue? @Asana @Microsoft @MartynasZilinskas @theruther4d @Jessidhia

**Comment by theruther4d** [comment]
Hey @wolfy1339, seems like you have mismatched versions of `@types/react` and `@types/react-dom`. Are you using the latest version of `@types/react`? 

Just a tip: if that :point_up: is indeed the solution to your problem, it can be quickly found by googling that error message. Keep in mind this is open source software, you’re not paying for it and none of us who have contributed to it are being paid to do so.

**Comment by truca** [comment]
Just found [this issue](https://github.com/react-dnd/react-dnd/issues/1440), tried the solution and it seems that it works

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
