### ISSUE TITLE
@types/react: The included global.d.ts prevents using elements/definitions from lib.dom.d.ts

### ISSUE THREAD

**Issue by weikinhuang** [DefinitelyTyped/DefinitelyTyped#34043]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @newyankeecodeshop @ferdaber @johnnyreilly @sandersn @RyanCavanaugh @tkrotoff @weswigham

Per the PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20005 that added a shim for the dom types to the react defs. (last comment by @petejkim). I'm encountering an issue where I'm trying to use the native `HTMLCanvasElement` as a typecast. But the one provided in the react typedef is extending an empty interface and I can't seem to exclude that lib from being used when using a mixed react/non-react project.

Ex.

```typescript
const c: HTMLCanvasElement = fnFromSomethirdParty();
c.width = 123;
// TS2339: Property 'width' does not exist on type 'HTMLElement'.
```

**Comment by ferdaber** [comment]
Can you post a minimal-reproducible repo for us to investigate?

**Comment by weikinhuang** [comment]
Very strange, I updated to the latest typedefs and the problem went away. Sorry for the noise. I'll reopen if I can get it to repro again.
