### ISSUE TITLE
ERROR in node_modules/@types/lodash/common/object.d.ts(1689,12): error TS2304: Cannot find name 'Exclude'. node_modules/@types/lodash/common/object.d.ts(1766,12): error TS2304: Cannot find name 'Exclude'. node_modules/@types/lodash/common/object.d.ts(1842,34): error TS2304: Cannot find name 'Exclude'. node_modules/ngx-webstorage/dist/app.d.ts(1,39): error TS2305: Module '"/home/sreejesh/project/admin-ui-2018/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

### ISSUE THREAD

**Issue by sreejeshmk** [DefinitelyTyped/DefinitelyTyped#34055]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/lodash2.8.3` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by j-oliveras** [comment]
You should use typescript 2.8 or newer or install a version of lodash types compatible with your typescript version (example with lodash for typescript 2.3): `npm i -D @types/lodash@ts2.3`.

**Comment by sreejeshmk** [comment]
@j-oliveras I tried that also but showing same kind of error. Now i'm facing only OpaqueToken error
