### ISSUE TITLE
hls.js has incorrect annotations for getter style properties.

### ISSUE THREAD

**Issue by karanlyons** [DefinitelyTyped/DefinitelyTyped#34130]
- [x] I tried using the `@types/hls.js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jgainfort, @brookback, @adripanico, @beraliv

(I think I _can_ open a PR for this, but I want to first make sure I’m not being stupid and that this _is_ an actual issue.)

Getter only style properties such as [`hls.autoLevelEnabled`](https://github.com/video-dev/hls.js/blob/v0.12.2/src/hls.js#L469) currently have the type `(value: T): T;` when in actuality they’re of type `T;`. I’m not sure if this was true of some v0.12 release (or perhaps earlier) but as of at least v0.12.2 there’s a mismatch between these annotations and the actual underlying js.

My guess is that _almost_ all `foo(value: T): T;`s should be `foo: T;`. Is there some intentionality to this behavior that I’m missing or would a PR be appreciated? Additionally is there a way to do this that correctly annotates these values as `readonly` without running afoul of TS rules regarding `readonly` attributes being set at initialization only?

**Comment by adripanico** [comment]
You are right.

Left side, a copy of the getter code. Right side, the types generated by tsc:

![image](https://user-images.githubusercontent.com/467658/54865273-52eee600-4d63-11e9-9cbe-d673cb97ed94.png)

**Comment by karanlyons** [comment]
Opened a PR that fixes this and removes some also nonexistent properties. Would love to see that merged in soon as at least since v0.12 these typings have been inaccurate.

I noticed a bunch of other things as well, and I’ve been _trying_ to rewrite these typings so they match the v0.12 releases, but it’s been a bit difficult as the documentation for hls.js is not in sync with the codebase, and additionally the publicly consumable API goes pretty deep (all the way down into AES keys for fragments or even fragment types themselves which have by my count at least 26 properties as seen in the [demo](https://video-dev.github.io/hls.js/demo/) vs. the typed 9).

The hls.js project are trying to [refactor their codebase to typescript](https://github.com/video-dev/hls.js/issues/2070), but this looks to be a longer term effort. What does the effort to maintain these type definitions look like, and is there any chance of working together with the hls.js team to keep these current?

**Comment by jgainfort** [comment]
The hls.js team expressed no interest on maintaining these type definitions. As you mentioned they will be moving to TS and thus deprecating these typings, but as you mentioned I would not expect that in the near future.

Personally I have moved much of my development into AVPlayer and don't use this library as much. Best way to maintain parity is through pull requests such as yours. Thank you!

If you ever have any questions you can always pop into the [video-dev slack ](http://video-dev.herokuapp.com/) in the #hlsjs channel. The majority of the maintainers and myself monitor it frequently.

**Comment by karanlyons** [comment]
Good to know! If I can actually get my rewrite to properly map things (stuff like their overloaded error type makes it hard to put together definitions that feel safe) I’ll file a PR for it, but I think waiting on upstream to move to TS themselves is probably the safer bet.
