### ISSUE TITLE
Please update the jquery.dataTables definition

### ISSUE THREAD

**Issue by AteByAte** [DefinitelyTyped/DefinitelyTyped#3414]
The current definition file is for v1.9.4 dated 6/2014 but the current version of jquery.dataTables is 1.10.4 dated 11/2014.

Thank you.

**Comment by Eagle3386** [comment]
+1 for updating the definitions. I'm not able to update it myself, but if I can be of any help, please let me know.

**Comment by JonCSL** [comment]
+1 here as well!

**Comment by CNBoland** [comment]
File jquery.dataTables-1.9.4.d.ts is for version 1.9.4. File jquery.dataTables.d.ts is intended for current version. I have been working on bringing it up to date. It is currently at 1.10.7, with additional fixes by other contributors. When my current PR for 1.10.8 is accepted, I'll move on to 1.10.9 and later.

**Comment by vvakame** [comment]
by #11718
