### ISSUE TITLE
[@types/node] unhandledRejection is not assignable to parameter of type Signals

### ISSUE THREAD

**Issue by Ionaru** [DefinitelyTyped/DefinitelyTyped#34166]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (3.3.4000)
- [x] I have a question that is inappropriate for StackOverflow. (Please ask any appropriate questions there).
- [x] Authors: @OliverJAsh, @rbuckton, @SimonSchick 

Given this code:
```ts
process.on('unhandledRejection', (reason: string, p: Promise<any>): void => {
    // Do something
});
```
Gives me the error:
`TS2345: Argument of type '"unhandledRejection"' is not assignable to parameter of type 'Signals'.`

This behaviour seems to have started somewhere between versions `11.9.4` and `11.11.6`.

**Comment by SimonSchick** [comment]
`reason` _should_ be an error, what is it in your case?

**Comment by Ionaru** [comment]
In `global.d.ts` I'm seeing this type:
```ts
type UnhandledRejectionListener = (reason: {} | null | undefined, promise: Promise<any>) => void;
```

While in 11.9.4 this used to be:
```ts
type UnhandledRejectionListener = (reason: any, promise: Promise<any>) => void;
```

While my code is not correct either, the Node.js documentation states that `reason` is of type `Error | any`
https://nodejs.org/api/process.html#process_event_unhandledrejection.

So why is it set to the backwards-compatible `unknown` now?

**Comment by OliverJAsh** [comment]
`any` is not type safe. See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33636#issuecomment-469901896.

The Node documentation's `any` is the same thing as TypeScript's `unknown`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types.

**Comment by Ionaru** [comment]
Thank you for the explanation, I will close this issue and modify my code since the problem lies there.
