### ISSUE TITLE
lodash chaining filter method has wrong type

### ISSUE THREAD

**Issue by altano** [DefinitelyTyped/DefinitelyTyped#3418]
_.flatten() has the correct return type, but _(...).flatten() does not:
```javascript
interface Item { }
var items: Item[] = [];
var arrayWrapper = _.flatten(items); // type = Item[]
var arrayStatic = _(items).flatten().value(); // type = {}[]
```
The definitions look correct so I'm not even sure what's wrong.  Do any of you recent contributors know how to fix it, @bczengel, @anthonychu, @szarouski, @motemen, @andrewvc, @dmorgantini?

**Comment by bczengel** [comment]
The return type of the chainable version of flatten can't be inferred. You have to specify it.

    _(items).flatten<Item>().value()

**Comment by chrootsu** [comment]
@altano I think the issue can be closed, isn't it?

**Comment by altano** [comment]
Yeah, this can be modeled using new features in TS such as union types and it looks like the .d.ts for lodash has been overhauled to make use of these new features, so this issue is irrelevant.
