### ISSUE TITLE
Types for jexl@2.1.1

### ISSUE THREAD

**Issue by oscarCrespo** [DefinitelyTyped/DefinitelyTyped#34186]
Is there any plans of adding Types for Jexl 2.1.1.  I've been trying to add the new `evalSync` but the latest version available is 1.1.2.

Thanks @m-tomczyk

**Comment by m-tomczyk** [comment]
Oh, >2.0.0 version is news for me. It somehow slipped under my radar. I'll definitely look into this by the end of the week

**Comment by m-tomczyk** [comment]
@oscarCrespo I submitted PR for this change. Tested it locally and it looked okay. So if maintainers will be fine with this it should go live soon

**Comment by oscarCrespo** [comment]
Nice @m-tomczyk! Thanks a lot man. Sorry for taking so long to answer.

**Comment by m-tomczyk** [comment]
No problem :) I guess ticket can be closed?
