### ISSUE TITLE
mongoose - orFail() has wrong typings

### ISSUE THREAD

**Issue by mrwillis** [DefinitelyTyped/DefinitelyTyped#34205]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/xxxx` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ]x I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 

@horiuchi <https://github.com/horiuchi>
@lukasz-zak <https://github.com/lukasz-zak>
@Alorel <https://github.com/Alorel>
@jendrikw <https://github.com/jendrikw>
@Ethan Resnick <https://github.com/ethanresnick>
@vologa <https://github.com/vologab>
@jussikinnula <https://github.com/jussikinnula>
@ondratra <https://github.com/ondratra>
@alfirin <https://github.com/alfirin>
@Idan Dardikman <https://github.com/idandrd>
@Dominik Heigl <https://github.com/various89>
@Fazendaaa <https://github.com/Fazendaaa>
@Norman Perrin <https://github.com/NormanPerrin>
@Dan Manastireanu <https://github.com/danmana>
@stablio <https://github.com/stablio>
@Emmanuel Gautier <https://github.com/emmanuelgautier>
@Frontend Monster <https://github.com/frontendmonster>
@Ming Chen <https://github.com/mingchen>
@Olga Isakova <https://github.com/penumbra1>
@Orblazer <https://github.com/orblazer>

Currently `orFail()` when used on a query returns `this`, which is `document | null`.  `orFail()` should simply return the type of `document` because it should throw on an error instead.

```typescript
export async function getDocument(otherDocument: IOtherDocument) {
  const document = await Document.findOne({
    searchThing: otherDocument._id
  }).orFail().exec()
// `document` is typed as Document | null
  if (!document) {
    throw new Error("Document not found")
  }
  return document
}
```

If you do not mention the authors the issue will be ignored.

**Comment by xrip** [comment]
Any intermediate solution other than short ` if (!document) { return ;}` ?

**Comment by idan** [comment]
@idandrd is the correct Idan here, untagging myself

**Comment by andreialecu** [comment]
FWIW I used [patch-package](https://www.npmjs.com/package/patch-package) to change the definition of `orFail` to this:

`orFail(err?: Error | (() => Error)): DocumentQuery<NonNullable<T>, DocType, QueryHelpers>;`

Seems to work in my case, but I'm not sure if it is a valid fix for all scenarios.
