### ISSUE TITLE
[video.js] Typings do not support boolean style children syntax.

### ISSUE THREAD

**Issue by karanlyons** [DefinitelyTyped/DefinitelyTyped#34214]
- [x] I tried using the `@types/video.js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @vbortone @scleriot @SWBennett06 @IgelCampus @giofreitas @gjanblaszczyk @sroucheray @Akxe @meikidd

video.js offers a [shorthand syntax](https://github.com/videojs/video.js/blob/v7.4.1/src/js/component.js#L500-L517) for de/selecting children components to be rendered by their parent:

```js
Videojs(el, {
  controlBar: {
    playToggle: false,
    volumePanel: true,
    ...
  }
})
```

Currently the type definitions only support a subset of the `children` syntax.

This is…hard to solve? The immediate thing that occurs is to just define `ControlBarOptions` (et al) as:
```ts
type Child = string | {
  name: string,
  children?: Child[] | { [key: string]: any }
};

interface ComponentOptions {
  children?: Child[];
  [key: string]: any;
}

interface ControlBarOptions extends ComponentOptions {
  volumePanel?: VolumePanelOptions | boolean;
}
```

but that obviously sucks since we’ve basically bailed out of typing. If `ControlBarOptions` were a type (shouldn’t it be?) and not an interface we could do:

```ts
type ComponentOptionsMap = {
  'playToggle': ComponentOptions,
  'volumePanel': VolumePanelOptions,
  // ...
  'fullscreenToggle': ComponentOptions,
};

type ComponentNames = keyof ComponentOptionsMap;

type Child =
  | ComponentNames
  | { [K in ComponentNames]: { name: K } & ComponentOptionsMap[K] }[ComponentNames];

type ComponentOptions = {
  children?:
    | Child[]
    | Partial<{ [K in ComponentNames]: ComponentOptionsMap[K] | boolean }>
};

type ControlBarOptions = ComponentOptions & {
  volumePanel?: VolumePanelOptions | boolean;
} & Partial<{
  [K in Exclude<ComponentNames, 'volumePanel'>]: ComponentOptionsMap[K] | boolean
}>;
```

which works _wonderfully!_ Defining `ComponentOptionsMap` would also allow us to use it to restrict the `Child` strings to `ComponentNames` as well, and we could define all the possible components in just one place and have complete and proper typing for the entirety of `options`. But with interfaces we’re (or at least _I’m_) stuck with just listing all the options verbosely in every location where this pattern is supported by video.js:

```ts
interface ControlBarOptions extends ComponentOptions {
  volumePanel?: VolumePanelOptions | boolean;
  playToggle?: boolean | ComponentOptions;
  // ...
  fullscreenToggle?: boolean | ComponentOptions;
}
```

What would we prefer to do? Is there perhaps a nice clean way to do this with interfaces as well? Technically _any_ object inheriting from `Component` can have `children` or this shorthand syntax, and can reference any registered component, which may include custom components written by users (if we can put the mapping in just one place then those writing custom components could easily just shadow the mapping).

Regardless, I should be able to offer a PR for any of these given options, but I’d like to throw it out to the room before I commit to one. My vote would be for the types solution if we can get away with changing over from interfaces and if there isn’t a nice way to do it otherwise.

**Comment by karanlyons** [comment]
For reference, I _think_ the total API example for component options ends up looking like this:
```js
Videojs(el, {
  parent: {
    child1: false, // Don't render child1.
    child2: true, // Render child2 with default options in “unspecified” or default order.
    child3: { // Render child3 with supplied options in “unspecified” or default order.
      opt1: 'value1',
      children: [ // Render children in specified order.
        'grandchild1', // Render grandchild1 first in order with default options.
        { // Render grandchild2 second in order with supplied options.
          name: 'grandchild2',
          opt2: 'value2',
          children: { // Render children in “unspecified” or default order.
            greatgrandchild1: true,
            greatgrandchild2: {}
          }
        }
      ],
    }
  }
})
```

When the children ordering is “unspecified”, the children are ordered based on whatever your JS engine chooses to do for `Object.keys()`. In any of the cases the supplied children are then inserted before any default children for that component (which are deduped).

**Comment by karanlyons** [comment]
I haven’t heard back from any authors, shall I just open a PR?

**Comment by Akxe** [comment]
You should probably pink the authors of video.js

**Comment by karanlyons** [comment]
I think you’re one of them! [You’re listed in the authors at least.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/video.js/index.d.ts#L3-L11) Any thoughts on my proposed solution? I don’t want to step on anyone’s toes here since this’ll be a slightly larger change.

**Comment by Akxe** [comment]
Yeah, anyone who edited should be written there, but I am not the maintainer here :/

**Comment by rramphal** [comment]
Hey @karanlyons, did you end up coming up with a PR after all? I think it's safe to at least propose a solution since the issue you have pointed out is pretty limiting.

**Comment by karanlyons** [comment]
Sorry, long time since I’ve looked at this ticket, but I believe what I offered above almost works as a drop in but it necessitates some other changes and I haven’t really looked at the fence hard enough to know if that’s okay. I don’t think I ever filed a PR, but hopefully the first two comments get you most of the way there.

**Comment by Akxe** [comment]
@karanlyons 
* You need to fork the repo ([see here](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request))
* Edit the file with:
  * new typing
  * [OPTIONAL] Add yourself as another author ([here](https://github.com/DefinitelyTyped/DefinitelyTyped#definition-owners))
  * Edit/Add tests to verify that the feature you are adding is correct and will be correct once someone else makes changes,
* Push to your forked repository
* Go to git and create a pull request from your forked repo

It might seem hard, but it not that bad, don't worry

**Comment by karanlyons** [comment]
Thanks 🙂 I do know how to do it, I just haven’t the time at the moment. Would we be comfortable, then, in making `ControlBarOptions` a `type` rather than an `interface`?

**Comment by Akxe** [comment]
@karanlyons  I came up with a more generic approach:
```ts
interface VolumePanelOptions extends ComponentOptions { }
interface ControlBarOptions extends ComponentOptions<'playToggle' | 'volumePanel' | 'fullscreenToggle'> { }
interface WithDoubleNestedOptions extends ComponentOptions<'withNestedComponent'> { }
interface WithNestedOptions extends ComponentOptions<'nestedComponent'> { }
interface NestedOptions extends ComponentOptions { }

class Component { }

/** Very privatre type! */
interface ComponentOptionsMap {
	'controlBar': ControlBarOptions,
	'playToggle': ComponentOptions,
	'volumePanel': VolumePanelOptions,
	// ...
	'fullscreenToggle': ComponentOptions,
	'withDoubleNestedComponent': WithDoubleNestedOptions,
	'withNestedComponent': WithNestedOptions,
	'nestedComponent': NestedOptions,
}

type ChildrenArrayOrObject<children extends void | keyof ComponentOptionsMap = void> =
	| ReadonlyArray<Component | children>
	| (
		children extends string
		? Partial<{ [K in children]: ComponentOptionsMap[children] | boolean }>
		: void
	);

interface ComponentOptions<children extends void | keyof ComponentOptionsMap = void> {
	children?: ChildrenArrayOrObject<children>;
}
```

With usage as this:
```ts
const V0: ControlBarOptions = {
	children: ['playToggle'],
}

const V1: ControlBarOptions = {
	children: {
		playToggle: true
	}
}

const V2: WithDoubleNestedOptions = {
	children: {
		withNestedComponent: true
	}
}

const V3: WithDoubleNestedOptions = {
	children: {
		withNestedComponent: {
			children: {
				nestedComponent: true,
			},
		},
	},
};

const V4: WithDoubleNestedOptions = {
	children: {
		withNestedComponent: {
			children: ['nestedComponent']
		}
	},
};
```

But in my playground I have an error, I can not figure out how to fix :/ ([playground](https://www.typescriptlang.org/play/?ssl=67&ssc=3&pln=34&pc=1#code/JYOwLgpgTgZghgYwgAgGoHsA2BXAthABThAkwHkAHMYdEAZ2QgA9IQATBgYXVwtonCVqtBgG9kAXwBQoSLEQpu4KFgBCcKEJr1GLAR2Tde-QVW10APAHIKmOAE8AKugDmLzBCvIAPsisA3LDxCYlIvXysYbExMOgQoCAFnNw8rAD5kcWlZaHgkZAB1YDAACwARdGwAIw8AOQg6SDYtEV1WAyM+ElNhemsAd2KS+saINk6TMHTMyRlwXIVCoZGmlp1mdq4eLoEwNcsrElHx7cnprLm5PJQVsf22-S3jbr2zVoupBDs6J53wGekUgA9AAqEFoaD2ZAUKDAfxwMAJZBgewUCAAQmQIKBlwW+QmL32AFk4BRMlIAJBWBC0RFqDRWABchlpKkw6k0b3oABpKTY7E5XO5PMyCbt9ryqYEcPgiCRMEy0EFZaFyFy6JKgUDkAA6PV8qIxOIJJJC1Ki06E9WSqyDUoVap1BpNMXgRVFe2VGoQW7Na18u3DZ1jV1TZkeoPHCV8o4uy27RW+6OAlFowwlYCYNgJEAAQSgUAcZE0VQAVhAEGALAgM1mcw92AxAsA2D5kABrCD2dAwFnPcXqklkgC8yGbbAyw8pvgAShA4GxaJh7PnC-YLKG2zXM9mBGlp8gABSUinbusCBsGRqwkAuE8AfmQRCg1DgmAs4gA2gBpZCgZBnruIAALoWv2PTmEOn6ATmwFtlU6BYPOICSPuFIUsy46UgAlAA3FIuLyPi8YQSI1a1kBl5NugLZtp23a9qGxKksgo7jhkoiUjBAj3qKFE5quRYluWlbkTuOZpPhgI0vQYDIs6ACMzJzguS4rgWDjWDJdLsgyGS+KIEiscgn4KcB+GfCIcmoAADBayj0pyvQMKOnGnvxAjMp+-IOMkwpWNyfjYCA-TEE0AXIAALAArMBvLSVZaBKSyDm6U55jGW53EgMybkUrYvlmhAzKItgECUtICWyWgABM4ZDA63pJuqmVcR5OXkuhga+qGJVQGVFVSFVjRoAAzPVnqOj6wZ+s5rXueJnmdRS3Uzb1y0LeeHV5ehsYhiRYB9WVkroRIJ1nRV8UWTJI2oJFE3lF6TpRi1rltYt20nqtxzrTt2VeYca0HVYwEntIFIXRIuFAA))

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
