### ISSUE TITLE
[@types/react] Interface 'ButtonProps<T>' cannot simultaneously extend types 'AnchorHTMLAttributes<T>' and 'ButtonHTMLAttributes<T>'

### ISSUE THREAD

**Issue by dawsonc623** [DefinitelyTyped/DefinitelyTyped#34274]
The error in the title is coming up after upgrading to version 16.8.10. PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34194 seems to be the cause; I manually reverted the type change and my code compiled fine after. The quick fix is a revert, but the "right" fix is to probably rework the `ButtonProps` interface so it can accommodate the change made in that PR.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Asana @AssureSign @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei @Jessidhia @pshrmn @threepointone @saranshkataria

**Comment by ferdaber** [comment]
It's expected that this change would be breaking for consumers, so yeah the true fix is to accommodate for the stricter `"type"` type.

**Comment by dawsonc623** [comment]
@ferdaber Is it common for this package to release breaking changes as patch releases?

**Comment by pshrmn** [comment]
@dawsonc623 Yes, DefinitelyTyped doesn't follow semver. https://blog.johnnyreilly.com/2018/09/ivan-drago-and-definitely-typed.html

**Comment by dawsonc623** [comment]
@pshrmn Ah, alright. I can see the logic there. I brought up this issue with the package that broke due to the PR in question. Unless you think there is anything that needs done on DefinitelyTyped's this issue can be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
