### ISSUE TITLE
Missing return types in Noty functions

### ISSUE THREAD

**Issue by crystalfp** [DefinitelyTyped/DefinitelyTyped#34294]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kingdango @thelfensdrfer 

If you do not mention the authors the issue will be ignored.

Missing return values on various functions:

./server/node_modules/@types/jquery.noty/index.d.ts:61:5 - error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.

61     (notyOptions: NotyOptions);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~

../server/node_modules/@types/jquery.noty/index.d.ts:64:5 - error TS7010: 'get', which lacks return-type annotation, implicitly has an 'any' return type.

64     get(id: any);
       ~~~~~~~~~~~~~

../server/node_modules/@types/jquery.noty/index.d.ts:65:5 - error TS7010: 'close', which lacks return-type annotation, implicitly has an 'any' return type.

65     close(id: any);
       ~~~~~~~~~~~~~~~

../server/node_modules/@types/jquery.noty/index.d.ts:66:5 - error TS7010: 'clearQueue', which lacks return-type annotation, implicitly has an 'any' return type.

66     clearQueue();
       ~~~~~~~~~~~~~

../server/node_modules/@types/jquery.noty/index.d.ts:67:5 - error TS7010: 'closeAll', which lacks return-type annotation, implicitly has an 'any' return type.

67     closeAll();
       ~~~~~~~~~~~

../server/node_modules/@types/jquery.noty/index.d.ts:68:5 - error TS7010: 'setText', which lacks return-type annotation, implicitly has an 'any' return type.

68     setText(id: any, text: string);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../server/node_modules/@types/jquery.noty/index.d.ts:69:5 - error TS7010: 'setType', which lacks return-type annotation, implicitly has an 'any' return type.

69     setType(id: any, type: string);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../server/node_modules/@types/jquery.noty/index.d.ts:73:5 - error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.

73     (notyOptions: NotyOptions);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~

../server/node_modules/@types/jquery.noty/index.d.ts:75:5 - error TS7010: 'show', which lacks return-type annotation, implicitly has an 'any' return type.

75     show();
       ~~~~~~~

../server/node_modules/@types/jquery.noty/index.d.ts:76:5 - error TS7010: 'close', which lacks return-type annotation, implicitly has an 'any' return type.

76     close();
       ~~~~~~~~

../server/node_modules/@types/jquery.noty/index.d.ts:77:5 - error TS7010: 'setText', which lacks return-type annotation, implicitly has an 'any' return type.

77     setText(text: string);
       ~~~~~~~~~~~~~~~~~~~~~~

../server/node_modules/@types/jquery.noty/index.d.ts:78:5 - error TS7010: 'setType', which lacks return-type annotation, implicitly has an 'any' return type.

78     setType(type: string);
       ~~~~~~~~~~~~~~~~~~~~~~

../server/node_modules/@types/jquery.noty/index.d.ts:79:5 - error TS7010: 'setTimeout', which lacks return-type annotation, implicitly has an 'any' return type.

79     setTimeout(timeout: number);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
