### ISSUE TITLE
Term type

### ISSUE THREAD

**Issue by namedgraph** [DefinitelyTyped/DefinitelyTyped#34310]
@AlexeyMz what is `{ __termBrand: string; }` used for in `Term`?
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e809175e0cb86f04a1227ee16d12b657846bbded/types/sparqljs/index.d.ts#L223

It gives all kinds of compilation problems, for example:

    error TS2345: Argument of type 'Term' is not assignable to parameter of type '{ __termBrand: string; } & "*"'.
      Type 'Term' is not assignable to type '"*"'.

    let actual = DescribeBuilder.fromString(query).term(DescribeBuilder.var("x")).build();

**Comment by AlexeyMz** [comment]
This a workaround for the lack of nominal types in TypeScript, see [Can I make a type alias nominal?](https://github.com/Microsoft/TypeScript/wiki/FAQ#can-i-make-a-type-alias-nominal) at TypeScript's FAQ.

According to the [SPARQL 1.1 grammar](https://www.w3.org/TR/sparql11-query/#grammar) `*` is a different kind of projection expression, incompatible with `Var` (i.e. `Term` in the typings), so it would be an error to assign `Term` to `*` projection and visa-versa.

In case you want to treat a string value as `Term` you should assert the type manually:
```
const term = "?var" as Term;
```
