### ISSUE TITLE
Lodash: `flow`: incorrect inference for generic function

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#34380]
TS v3.4.1

``` ts
declare const pipe: {
    <A, B>(a: () => A, ab: (a: A) => B): () => B;
    <A, B, C>(ab: (a: A) => B, bc: (b: B) => C): (a: A) => C;
};

declare const identity: <T>(t: T) => T;

// Expected and actual type: `<T>(a1: T) => T`
const fn1 = pipe(
    identity,
    identity,
);

// Expected type: `<T>(a1: T) => T`
// Actual type: `(a1: {}) => {}`
const fn2 = pipe(
    identity,
    value => identity(value),
);
```

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by aj-r** [comment]
I think typescript is struggling with the type inference since the second function (`value => identity(value)`) doesn't have any generic arguments. If you give it some generic arguments then it works as expected.

```ts
// Actual type: `<T>(a1: T) => T`
const fn2 = pipe(
    identity,
   <T>(value: T) => identity(value),
);
```

I don't think there is anything we can do about this in lodash without breaking other things.

**Comment by OliverJAsh** [comment]
Yeah, I tried to fix this in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34374.

I've stopped using Lodash's `pipe`/`flow` now in favour of https://github.com/Microsoft/TypeScript/issues/29904#issuecomment-471334674, which doesn't have this problem.

**Comment by OliverJAsh** [comment]
In TS 3.1+, this is fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35241/files#diff-854c815d18186623bc883d002819f561R175.
