### ISSUE TITLE
[@types/next] getInitialProps `Error` needs to be extended

### ISSUE THREAD

**Issue by Noviny** [DefinitelyTyped/DefinitelyTyped#34419]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @resir014 

If you do not mention the authors the issue will be ignored.

---

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/36a379245bea201376a5b1546715a59f5ba68b67/types/next/index.d.ts#L55

On this line, the default error object is being set to the javascript Error object. Next's own [custom error handling docs](https://nextjs.org/docs/#custom-error-handling) recommends checking for a `statusCode` on error, which they have types as:

```
Error & { statusCode?: number }
```

https://github.com/zeit/next.js/blob/aac50e4501f60f11914c0ae5f35f7718aaf56883/packages/next-server/server/render.tsx#L434

Could we amend the error in NextContext to use this typing?

(happy to create a PR, but wanted to validate this first, as I'm new to typescript)

Currently in my app I have:

```
interface InitialProps extends NextContext {
  err: Error & { statusCode?: number };
}
```

**Comment by youbicode** [comment]
Hey @Noviny , any progress on this ? I'm facing similar issue

**Comment by resir014** [comment]
@Noviny Sorry, I missed this in my issues!

In Next.js 9, which has its own typings now, the typings for `err` work exactly as you proposed.

We shouldn't need to update the typings now since Next.js already has its own typings, but I'd be happy to merge this as a maintenance fix for Next.js 8.

cc: @scottdj92

**Comment by Noviny** [comment]
@resir014 I'm not facing this as a problem anymore, but happy to contribute the maintenance fix. Will try and get it up this week.

**Comment by scottdj92** [comment]
Sure thing. I'll reiterate what @resir014 mentioned. When there's a PR up, I'll take another look and add it as a Next.js 8 maintenance update. Thanks for submitting an issue!
