### ISSUE TITLE
latest release of @types/node (11.13.0) breaks EventEmitter contract

### ISSUE THREAD

**Issue by bcoe** [DefinitelyTyped/DefinitelyTyped#34414]
Since pulling in the changes to `@types/node` yesterday, we have been running into issues with our upstream libraries that rely on the `EventEmitter` type.

Prior to `11.13`, `EventEmitter` could be cast to the type `Function`; allowing for code such as:

```js
promisifyAll(Bucket, {
  exclude: ['request', 'file', 'notification'],
});
```

Where bucket extends on `EventEmitter`. In the `11.13.0` release we receive the following error:

```
 Argument of type 'typeof Bucket' is not assignable to parameter of type 'Function'.
```

Would appreciate any help you might be able to provide, it might just be a matter of rolling back `11.13.0` and releasing it as `12.0.0`?

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick  

CC: @callmehiphop

**Comment by SimonSchick** [comment]
Can you please post of a full repro, I am not sure what's going on here.

**Comment by callmehiphop** [comment]
@SimonSchick I *think* this is the gist of what is going on

```ts
import {EventEmitter} from 'events';

class Bucket extends EventEmitter {}

// Argument of type 'typeof Bucket' is not assignable to parameter of type 'Function'.
decorate(Bucket);

function decorate(thing: Function) {
  // ...
}
```

@bcoe does that look accurate?

**Comment by bcoe** [comment]
@callmehiphop @SimonSchick yes, this reproduces the issue:

```bash
foo.ts:9:10 - error TS2345: Argument of type 'typeof Bucket' is not assignable to parameter of type 'Function'.
  Types of property 'once' are incompatible.
    Type '(emitter: EventEmitter, event: string | symbol) => Promise<any>' is not assignable to type '() => Function & FnProps<any>'.

9 decorate(Bucket);
```

and succeeds on `11.12.4`,

**Comment by SimonSchick** [comment]
That seems weird, I will take a look.

**Comment by SimonSchick** [comment]
What TypeScript version are you using? I cannot reproduce this issue.

**Comment by SimonSchick** [comment]
Oh, after reading your last comment it seems like the new `once` static method on the EventEmitter conflicts with some of your definition, in particular the `& FnProps<any>` part.

Since the implementation of `.once` is according to spec I think this is something you will have to solve on your end.

**Comment by SimonSchick** [comment]
That said, if you could please a full *self contained* repro that includes:

- package.json (including typescript version, avoid extra deps unless absolutely needed)
- tsconfig.json
- repro.ts (contains code that errors)

I'm willing to take a look, but without the full picture, I can't help you 😞

**Comment by callmehiphop** [comment]
I was working on a repro, but it turns out it likely is not an issue with `@types/node` per se, but rather a conflict between `@types/node` and [`@types/once`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/once/index.d.ts#L46).

**Comment by SimonSchick** [comment]
@bcoe can you confirm the above and close the issue please?

**Comment by bcoe** [comment]
@SimonSchick I can confirm we're unblocked, I think it was a particularly weird interaction between a variety of our libraries :+1:
