### ISSUE TITLE
[@types/workbox-sw] Missing v4 definitions

### ISSUE THREAD

**Issue by wilsonpage** [DefinitelyTyped/DefinitelyTyped#34437]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wessberg 

---

`workbox-sw` v4 is now the latest and `@types/workbox-sw` refers to v3, this results in broken type checking. For basic use-case:

`yarn add workbox-sw`
`yarn add -D @types/workbox-sw`

**Comment by wessberg** [comment]
Thanks for submitting this issue. I'm aware that v4 has been released and that the typings need to be updated to reflect the new version. I'll get around to it as soon as possible.

**Comment by wessberg** [comment]
I've submitted a PR that updates the `workbox-sw` types to v4.2.0: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34524
