### ISSUE TITLE
@types/react-virtualized List's onScroll type incompatible with ScrollSync's onScroll

### ISSUE THREAD

**Issue by hieuhlc** [DefinitelyTyped/DefinitelyTyped#34431]
- [x] I tried using the `@types/react-virtualized` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kaoDev @guntherjh @wasd171 @szabolcsx @Stevearzh @mgoszcz2 @brandonhall @sbusch

Please see these screenshots
<img width="913" alt="Screen Shot 2019-04-03 at 15 06 13" src="https://user-images.githubusercontent.com/4828178/55462893-0d170500-5622-11e9-8eac-c10b12dd69d4.png">
<img width="981" alt="Screen Shot 2019-04-03 at 15 03 39" src="https://user-images.githubusercontent.com/4828178/55462814-d5a85880-5621-11e9-83e5-60d2b99cc621.png">

If I ignore the typescript error those code still works. Please help. Thank you all.

**Comment by Stevearzh** [comment]
Looks like there is something difference between [`ScrollSyncChildProps.onScroll`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-virtualized/dist/es/ScrollSync.d.ts#L15) and [`ListProps.onScroll`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-virtualized/dist/es/List.d.ts#L56-L58)

**Comment by Stevearzh** [comment]
just submitted a PR for solving this problem

**Comment by hieuhlc** [comment]
Thank you @Stevearzh I'm gonna close the issue now
