### ISSUE TITLE
[@types/react-redux] connected component is typed as any

### ISSUE THREAD

**Issue by mbohgard** [DefinitelyTyped/DefinitelyTyped#34473]
- [x] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo @pdeva @Kallikrein @jrakotoharisoa @apapirovski @surgeboris @soerenbf 

After last minor/patch update (@types/react-redux@7.0.6, TSC 3.4.1), `TestContainer` below is typed as `any`. `Connector` seem to be typed correctly.

```
const Test: React.SFC<{ active: boolean }> = () => <div />

const Connector = connect(
  (state: State) => ({ config: state.config })
)

const TestContainer = Connector(Test)
```

Tips? Bug?

**Comment by schmod** [comment]
This is a weird one, and it only seems to occur if you have `hoist-non-react-statics` v2.x somewhere in your package tree.  

Doing a quick search seems to indicate that this may be the same issue as #33690
