### ISSUE TITLE
[@types/vinly]: export interface BufferFile, StreamFile, etc.

### ISSUE THREAD

**Issue by mheiber** [DefinitelyTyped/DefinitelyTyped#34501]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @thorn0 

We're writing code that manipulates only certain subtypes of `File`: `BufferFile`, `StreamFile`, etc.
It would be helpful if these types were exported.

I tried making the change like this (diff):

```diff
+ export interface BufferFile {
- interface BufferFile {
```

But TS complains: `An export assignment cannot be used in a module with other exported elements.ts(2309)`

What's the recommended way of solving this problem? If there is a way to export `BufferFile`, `StreamFile`, etc. then I can make a PR.

Thanks for your help!

**Comment by mheiber** [comment]
cc @PeterHajdu

**Comment by thorn0** [comment]
Once #34579 is merged, those types will be available via the namespace:

```ts
import Vinyl = require('vinyl');
let x: Vinyl.BufferFile;
```

**Comment by thorn0** [comment]
JFYI:
1) https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require
2) https://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by mheiber** [comment]
Thanks @thorn0 !
