### ISSUE TITLE
expect-puppeteer exports neither export `setDefaultOptions` nor `getDefaultOptions`

### ISSUE THREAD

**Issue by llimllib** [DefinitelyTyped/DefinitelyTyped#34509]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @JoshuaKGoldberg @tkrotoff

Without access to the `setDefaultOptions` function, there is no way (as far as I can tell, please correct me if I'm wrong) to modify the timeout value in `expect-puppeteer`. Here's the example given in [the documentation](https://github.com/smooth-code/jest-puppeteer/tree/2fe1970f9308ed57961065c2efaee83dd115e13f/packages/expect-puppeteer#configure-default-options) that is inaccessible:

```javascript
import { setDefaultOptions } from 'expect-puppeteer'

setDefaultOptions({ timeout: 1000 })
```

I took a look in the types file but it only exports the `expect` function and I don't know what's the right way to restructure it to export that as well as `setDefaultOptions` and `getDefaultOptions`. Would be happy to file a PR if given guidance.

edit:

It looks like this might work, but I am finding it very challenging to test consistently perhaps because of typescript caching type definitions?

```typescript
namespace expectPuppeteer {
  declare function setDefaultOptions(options: any): any;
  declare function getDefaultOptions(): any;
}
```

**Comment by tonyhallett** [comment]
The toMatch/toMatchElement and not.toMatch/not.toMatchElement matchers have as second argument an options object with properties polling and **timeout**.  So you can supply your timeout in this manner ( and it overrides what has been set by setDefaultOptions ).  Of course this does not help with using setDefaultOptions for a one time setting of timeout.

**Comment by llimllib** [comment]
we gave up and moved on to a different library long ago, unfortunately

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
