### ISSUE TITLE
@types/elasticsearch Param type for putScript Incorrect Definition

### ISSUE THREAD

**Issue by danhlee329** [DefinitelyTyped/DefinitelyTyped#34513]
I'm currently using `@types/elasticsearch:5.0.32` and found that `lang` is not part of the current param list for `putScript` in the elasticsearch-js API:

#### @elastic/elasticsearch API - `putScript` - v.6.6:
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/6.x/api-reference.html#_putscript

#### Current type definition for `putScript`
https://github.com/DefinitelyTyped/DefinitelyTyped/blame/30e9238945e38fa0f3b3eb7360f0f33cd8f90b9e/types/elasticsearch/index.d.ts#L505

Please remove `lang` from the `PutScriptParams` interface.

@SimonSchick

**Comment by SimonSchick** [comment]
I didn't write that part of the definitions, that'd be @pushplay feel free to make a PR tho.

**Comment by danhlee329** [comment]
I was in the process of getting a PR ready, but after looking at the header of `index.d.ts`, I notice that this is for elasticsearch version 5, where `putScript` does accept a `lang` parameter. Any momentum on getting types ready for v.6?

**Comment by SimonSchick** [comment]
Nope, guess you'll have to give it a kickstart 😛

**Comment by pushplay** [comment]
I'm not actively developing on ES right now so I don't have the urge to take it on the v6 upgrade.

**Comment by danhlee329** [comment]
Closing issue, have not been in the ES space for some time, may have interest down the road.
