### ISSUE TITLE
[@types/pino] - Type LogFn obj: object

### ISSUE THREAD

**Issue by ivoreis** [DefinitelyTyped/DefinitelyTyped#34510]
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
 - Authors: @psnider , @BendingBender, @screendriver , @paambaati , @alferpal , @mortiy

Hi,

I'm trying  to define a custom type for `obj` so I can leverate typescript language features such as autocomplete. What's the best way to type `obj: object` in:

```ts
    interface LogFn {
        (msg: string, ...args: any[]): void;
        (obj: object, msg?: string, ...args: any[]): void;
    }
```

Do we want to enhance this type with generics and pass them down like `LogFn<MyObjectType>`? Or is there a custom `*.d.ts` that I can add/create that will allow this? 

Thanks

**Comment by BendingBender** [comment]
Why do you want do add generics here? What do you try to achieve? You usually don't need generics if there is only one occurence of your generic type in the whole signature, which would be the case in your example above.

**Comment by ivoreis** [comment]
@BendingBender, I don't want to use generics here, I'm trying to understand what possible course of actions I can take. 

The goal is to enable autocomplete and validation of `obj` argument. Ex:

```ts
  interface AllowedLogValues {
    status?: number;
    statusText?: number;
    error?: Error;
  }
```

```ts
logger.info({ status: 300}); // should be accepted
logger.info({ statusMessage: 300}); // should not be accepted
```

**Comment by BendingBender** [comment]
Hm, this is an interesting requirement. Usually people want to be able to log anything, not just a certain type of objects.

Couldn't you just inherit from the `LogFn` interface, pin it to the type you need and hard-cast a logger instance to your derived interface? Should be doable without any changes to the definition.

**Comment by ivoreis** [comment]
Yeah, flexibility is ok most of the time but sometimes you end up with several fields with similar meaning but with different names and types and that's just messy. 😄 

Cheers @BendingBender, this brings me one step closer to my requirement 👍 (now just need to figure out how to make `pino-http` to play nice).

Somehow casting `pinoHttp`:
```
  pinoHttp({
    logger: pino() as MyLogger,
  });
```

it warns: 

```ts
Argument of type '{ logger: MyLogger; }' is not assignable to parameter of type 'Writable | Duplex | Transform | WritableStream | SonicBoom | undefined'.
  Object literal may only specify known properties, and 'logger' does not exist in type 'DestinationStream'.ts(2345)
```

**Comment by BendingBender** [comment]
I don't think that you need to cast `pino` instance when creating pinoHttp:
```ts
pinoHttp({
    logger: pino(),
});
```

You should instead make your own `IncomingMessage` type:
```ts
interface MyIncomingMessage {
    log: MyLogger;
}

function handle (req: MyIncomingMessage, res: ServerResponse) {
  logger(req, res)
  req.log.info(...)
  res.end('hello world')
}
```

**Comment by ivoreis** [comment]
Yeah typing `IncomingMessage` is the way to go 👍

Thanks for your help @BendingBender  🙇
