### ISSUE TITLE
@types/pouchdb-core - type Plugin doesn't seem to be correct

### ISSUE THREAD

**Issue by assemblethis** [DefinitelyTyped/DefinitelyTyped#34521]
- Authors: @sandersn 

I'm rewriting the pouch-vue plugin in TypeScript and came across an issue with the type Plugin from pouchdb-core/index.d.ts having a type of string:
```
**
     * Pass this to `PouchDB.plugin()`.
     */
    type Plugin = 'This should be passed to PouchDB.plugin()';

```
I get an error message of: Argument of type '(pouch: any) => void' is not assignable to parameter of type '"This should be passed to PouchDB.plugin()"'.ts(2345)

If I change type Plugin to any then I can get rid of it.

What was the intent here? What would be the best course of action here?

Thanks!

**Comment by assemblethis** [comment]
I'm relatively new to TypeScript, so trying to figure out how things are done at this point. What I know is that PouchDB plugins can either be functions or objects, such as the pouchdb-find and pouchdb-replication plugins, respectively. But both plugins have similar top-level typings:

```
declare module 'pouchdb-find' {
    const plugin: PouchDB.Plugin;
    export = plugin;
}

```
```
declare module 'pouchdb-replication' {
    const plugin: PouchDB.Plugin;
    export = plugin;
}

```
Seems like the top-level typings are not related to the actual plugins' internals.

pouchdb-find's index.js (https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-find/src/index.js):

```
var plugin = {};
<snip functions add to object prototype>
export default plugin;
```

pouchdb-replication's index.js (https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-replication/src/index.js):

```
function replication(PouchDB) {
<snip functions added to PouchDB's prototype>
export default replication;

```
It seems to me we're typing the plugins based on what the plugin() method ends up doing with the plugin code, which is applying the functions or objects to the PouchDB.Static type. And that is where the actual typings occur, and those types end up being an example of declaration merging?

So if you try to pass a type or interface that correctly describes the plugin's internals to the PouchDB.plugin() method you'll get an error: 'Argument of type '(pouch: any) => void' is not assignable to parameter of type '"This should be passed to PouchDB.plugin()"'.ts(2345)'

You in fact don't type the plugin as passed to PouchDB.plugin() but what it finally ends up doing to the PouchDB.Static type.

Is that close to the truth? :)

**Comment by sandersn** [comment]
This is a good question for the maintainers of pouchdb-core.
@spaulg @trubit
@geppy @fredgalvao
@TobiasBales @tiangolo
@kmoe

(I'm the maintainer of Definitely Typed itself and don't know anything about pouchdb's types.)

**Comment by tiangolo** [comment]
I'm sorry, I haven't checked those internals deeply enough to give a useful answer here.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
