### ISSUE TITLE
[@types/react] props are not assignable to LibraryManagedAttributes

### ISSUE THREAD

**Issue by dkamyshov** [DefinitelyTyped/DefinitelyTyped#34553]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Jessidhia

typescript: 3.3.1, 3.4.2
@types/react: 16.7.22, 16.8.12

I guess this issue is related to one of these: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30791 https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33116

Hello!

I think there might be a bug in @types/react. The following code illustrates the problem:

```typescript
import * as React from 'react';

interface IChildComponentProps {
  a: string;
  b: number;
}

interface ISomeComponentProps<ComponentsMap> {
  components: {
    [K in keyof ComponentsMap]: React.ComponentType<IChildComponentProps>;
  };
  key: keyof ComponentsMap;
}

function SomeComponent<ComponentsMap>(
  props: ISomeComponentProps<ComponentsMap>
) {
  const { components, key } = props;
  const Component = components[key];
  /*
    Type '{ a: string; b: number; }' is not assignable to type 'LibraryManagedAttributes<{ [K in keyof RowType]: ComponentType<IChildComponentProps>; }[keyof RowType], PropsWithChildren<IChildComponentProps>>'.ts(2322)
  */
  return <Component
    a='123'
    b={123}
  />;
}
```

It doesn't work even if I explicitly change ComponentType to SFC or ComponentClass. Unfortunately, I weren't able to find the root cause.

The only solution for me is to declare Component as following:
```typescript
const Component = components[key] as React.ComponentType<IChildComponentProps>;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
