### ISSUE TITLE
[@types/ramda] Error trailing comma not allowed when compiling

### ISSUE THREAD

**Issue by ignition42** [DefinitelyTyped/DefinitelyTyped#34565]
- [x] I tried using the `@types/ramda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @donnut, @tycho01, @mdekrey, @mrdziuban, @sbking, @afharo, @teves-castro, @1M0reBug, @hojberg, @samsonkeung, @angeloocana, @raynerd, @googol, @moshensky, @ethanresnick, @leighman, @CaptJakk, @deftomat, @deptno, @blimusiek, @biern, @rayhaneh, @rgm, @drewwyatt, @jottenlips, @minitesh, @Krantisinh, @pirix-gh

### Error trailing comma not allowed when compiling

This might be the wrong place, I'm using angular-cli and perhaps I could fix it changing the compiler options.  
Since c7e3f70 when using `ng build` or `ng serve` the following error appears. I think TypeScript should be able to compile with trailing commas.  
So by now I had to downgrade to 0.26.4, I didn't try 0.26.5 because I looks like is older than the commit.

@types/ramda: 0.26.6
typescript: 3.2.2
@angular/cli: 7.3.7

```
ERROR in node_modules/@types/ramda/index.d.ts(650,22): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(653,22): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(657,22): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(662,22): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(668,22): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(675,22): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(683,22): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(692,22): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(702,22): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(713,22): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(717,22): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(720,23): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(724,23): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(729,23): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(735,23): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(742,23): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(750,23): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(759,23): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(769,23): error TS1009: Trailing comma not allowed.
node_modules/@types/ramda/index.d.ts(780,23): error TS1009: Trailing comma not allowed.
```

**Comment by brekk** [comment]
@ignition42  I believe this issue can be closed?

**Comment by ignition42** [comment]
Indeed, now seems it's fixed. With version 0.26.8 I cannot reproduce it again.
