### ISSUE TITLE
[@types/yargs] Ordering of 'choices' inference in InferredOptionType/RequiredOptionType chain

### ISSUE THREAD

**Issue by adamdoyle** [DefinitelyTyped/DefinitelyTyped#34595]
- [x] I tried using the `@types/types` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @poelstra, @mizunashi-mana, @pushplay, @jeffkenney, @JimiC , @steffenvv, @forivall

----

### Sample (without default)
See error in trailing comment:
```typescript
  const result = yargs.command('command-name',
                               'description',
                               (y) => y.option('imageFormat',
                                               { choices: ['png', 'jpeg', 'svg'] as const })).argv;

  function imageOperation(type: 'png'|'jpeg'|'svg') {
    /* ... */
  }

  // error: Argument of type '"png" | "jpeg" | "svg" | undefined' is not assignable to parameter of type '"png" | "jpeg" | "svg"'.
  imageOperation(result.imageFormat);
```
### Sample (with default)
See [slightly worse] error in trailing comment:
```typescript
  const result = yargs.command('command-name',
                               'description',
                               (y) => y.option('imageFormat',
                                               { default: 'png', choices: ['png', 'jpeg', 'svg'] as const })).argv;

  function imageOperation(type: 'png'|'jpeg'|'svg') {
    /* ... */
  }

  // error: Argument of type 'string' is not assignable to parameter of type '"png" | "jpeg" | "svg"'.
  imageOperation(result.imageFormat);
```

### Relevant typing
Note the value returned by `option` and the type inference chain below, as well as the relative ordering of `{ default: /* ... */ }` and `{ choices: /* ... */ }`.
```typescript
option<K extends string,
       O extends Options>(key: K,
                          options: O): Argv<T&{ [key in K]: InferredOptionType<O> }>;

type InferredOptionType<O extends Options|PositionalOptions> =
    O extends { default: infer D } ? D :
    O extends { type: "count" } ? number :
    O extends { count: true } ? number :
    O extends { required: string | true } ? RequiredOptionType<O> :
    O extends { require: string | true } ? RequiredOptionType<O> :
    O extends { demand: string | true } ? RequiredOptionType<O> :
    O extends { demandOption: string | true } ? RequiredOptionType<O> :
    RequiredOptionType<O> | undefined;

type RequiredOptionType<O extends Options|PositionalOptions> =
    O extends { type: "array", string: true } ? string[] :
    O extends { type: "array", number: true } ? number[] :
    O extends { type: "array", normalize: true } ? string[] :
    O extends { type: "string", array: true } ? string[] :
    O extends { type: "number", array: true } ? number[] :
    O extends { string: true, array: true } ? string[] :
    O extends { number: true, array: true } ? number[] :
    O extends { normalize: true, array: true } ? string[] :
    O extends { type: "array" } ? Array<string | number> :
    O extends { type: "boolean" } ? boolean :
    O extends { type: "number" } ? number :
    O extends { type: "string" } ? string :
    O extends { array: true } ? Array<string | number> :
    O extends { boolean: true } ? boolean :
    O extends { number: true } ? number :
    O extends { string: true } ? string :
    O extends { normalize: true } ? string :
    O extends { choices: ReadonlyArray<infer C> } ? C :
    O extends { coerce: (arg: any) => infer T } ? T :
    unknown;
```

The observed behavior is a consequence of having `O extends { choices: ReadonlyArray<infer C> } ? C : /* ... */` at the [almost-]end of the hierarchy, such that the type of the default value (a `string` in the sample above) is used instead of inferring a union type from the `choices` array.

Is there a reason that `{ choices: /* ... */ }` needs to be at the end or can it be moved above `{ default: /* ... */ }`?

**Comment by steffenvv** [comment]
I don't think it needs to be at the end, no. I agree that the type inference would generally be improved by moving the default rule near the end of the list.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by Toxaris** [comment]
I observed the same thing today with @types/yargs@17.7.2.
