### ISSUE TITLE
[@types/yargs] Wrong type is returned by command(...)

### ISSUE THREAD

**Issue by adamdoyle** [DefinitelyTyped/DefinitelyTyped#34592]
- [x] I tried using the `@types/yargs` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:  @poelstra, @mizunashi-mana, @pushplay, @jeffkenney, @JimiC , @steffenvv, @forivall 

----

### Sample
Note actual and expected types in subsequent comments.
```typescript
import * as yargs from 'yargs';
const result = yargs.command('serve',
                             'Start the server.',
                             (yargs) => yargs.number('port')).argv;

// typeof result:
//    actual:                             { [x: string]: unknown; _: string[]; $0: string; }
//  expected:  { port: number|undefined }&{ [x: string]: unknown; _: string[]; $0: string; }
```

### Decomposed into multiple steps
```typescript
const builder = (yargs: yargs.Argv<{}>) => yargs.number('port');

// typeof builder: (yargs: yargs.Argv<{}>) => yargs.Argv<{port: number | undefined;}>
//      <-- good (i.e. correct / as-expected)

const commandResult = yargs.command('serve', 'Start the server.', builder);

// typeof commandResult: yargs.Argv<{}>
//      <-- bad; expected yargs.Argv<{ port: number|undefined }>

```
So it seems that `command(...)` is responsible for returning the wrong type.

### Typing for `command(...)`
The typing in question (based on the form used above) is:
```typescript
command<U>(command: string|ReadonlyArray<string>,
           description: string,
           builder?: (args: Argv<T>) => Argv<U>,
           handler?: (args: Arguments<U>) => void): Argv<T>;
```
Note that it accepts a parameter `builder` of type `builder?: (args: Argv<T>) => Argv<U>`.  Generic parameter `T` is the existing properties whereas `U` is the existing properties + one new property.  But then the typing for `command(...)` ultimately (and erroneously) returns the existing properties `T` instead of the new superset `U`.

### Corrected Typing
I would expect the following:
```typescript
command<U>(command: string|ReadonlyArray<string>,
           description: string,
           builder?: (args: Argv<T>) => Argv<U>,
           handler?: (args: Arguments<U>) => void): Argv<U>;
```

Using this typing, when I test the sample from the first section at the top of this issue, I now get the expected result.

I'd submit a PR, but not sure if this is the only instance of this problem nor whether there's unintended consequences.

**Comment by adamdoyle** [comment]
Also:  at least `usage(...)` has the same issue, possibly others

**Comment by joelverhagen** [comment]
An additional problem with the type definitions is that the command handler parameter can be a function that returns a promise (i.e. an async command handler), not just a synchronous void function.

I found this problem with `@typescript-eslint/no-misused-promises`.

yargs 13.0.0 code:
https://github.com/yargs/yargs/blob/cc8af7698b7c8daa55b215a780403f625d579f57/lib/command.js#L238

Latest code is very much the same:
https://github.com/yargs/yargs/blob/1b477454f87fd125184b3514360e23964a009478/lib/command.js#L234
