### ISSUE TITLE
[@types/graphql]  kind is not required for queryType

### ISSUE THREAD

**Issue by HsuTing** [DefinitelyTyped/DefinitelyTyped#34649]
- [X] I tried using the `@types/graphql` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @martijnwalraven

I download schema from `apollo-tooling` with command: `apollo service:download`. `apollo-tooling` use [introspectionFromSchema](https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo/src/commands/service/download.ts#L43) to generate a graphql file. As a result, I use `buildClientSchema` to build the `schema`. However, `@types/graphql` throw error like this: 

```js
error TS2345: Argument of type '{ "__schema": { "queryType": { "name": string; }; "mutationType": { "name": string; }; "subscriptionType": null; "types": ({ "kind": string; "name": string; "description": string; "fields": ({ "name": string; "description": string; "args": { ...; }[]; "type": { ...; }; "isDeprecated": boolean; "deprecationReason": s...' is not assignable to parameter of type 'IntrospectionQuery'.
  Types of property '__schema' are incompatible.
    Type '{ "queryType": { "name": string; }; "mutationType": { "name": string; }; "subscriptionType": null; "types": ({ "kind": string; "name": string; "description": string; "fields": ({ "name": string; "description": string; "args": { ...; }[]; "type": { ...; }; "isDeprecated": boolean; "deprecationReason": string; } | { ....' is not assignable to type 'IntrospectionSchema'.
      Types of property 'queryType' are incompatible.
        Property 'kind' is missing in type '{ "name": string; }' but required in type 'IntrospectionNamedTypeRef<IntrospectionObjectType>'.
```

In [graphql Introspection docs](https://graphql.org/learn/introspection/), `Kind` is not required for `queryType`. Is this a bug in `@type/graphql`?

**Comment by alamothe** [comment]
I'm having the same issue. I used `get-graphql-schema` to download the schema, and it does not have `"kind"` for `"queryType"`.

**Comment by pleunv** [comment]
Running into the same issue here. Any news or workaround?

**Comment by Naoto-Ida** [comment]
Same issue. Assumed it was some issue with incompatible GQL versions but tried all kinds of things with no success.

**Comment by Naoto-Ida** [comment]
Follow up:

According to [NPM](https://www.npmjs.com/package/@types/graphql) NPM, these types are deprecated.

**Comment by HsuTing** [comment]
Yes, you should remove the `@types/graphql` and upgrade `graphql`.
