### ISSUE TITLE
@types/terminal-kit term.noFormat should return a Terminal

### ISSUE THREAD

**Issue by tyrak** [DefinitelyTyped/DefinitelyTyped#34712]
- [x] I tried using the `@types/terminal-kit` package and had problems.
- [x] I tried using the latest stable version of tsc.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @katsanva

Shouldn't `term.noFormat` return a `Terminal` value so that I could do
`term.noFormat.red("hello")` as well as `term.noFormat("hello")`. In the current definition the type is `(str: string) => Terminal` which allows the latter example but not the former. Also, the same idea applies to `markupOnly`.

**Comment by katsanva** [comment]
@tyrak Are there any other such props, in addition to `noFormat` and `markupOnly`?

**Comment by tyrak** [comment]
@katsanva Based on my (possibly limited) usage of this package, these are the only properties that I found to have this issue. (I also have a separate problem but I will open a separate issue.)
