### ISSUE TITLE
@Types/react - If a component's prop is typed as ReactElement<ISomeInterface> it's not enforced, and actually typed as ReactElement<any>

### ISSUE THREAD

**Issue by carpben** [DefinitelyTyped/DefinitelyTyped#34713]
- [x ] I tried using the `@types/react` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
v 3.3
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Kovensky @pshrmn

```tsx 
type Child = React.ReactElement<{stl:string}>

const Parent: React.SFC<{children: Child}> = 
	({children}) => (React.cloneElement(children, {stl:"position:absolute;"}))
```

I'm counting on the child element to be of a certain type. More specifically, an element of a StyledComponent, which can handle a stl prop, and use it for it's style. However, in practice I can pass it anything. 

```tsx 
const App: React.SFC = 
   () => (
	<Parent>
		<div>hello</div>		
        </Parent>
	) 
```

Unfortunately this works and doesn't yield any error.

**Comment by ferdaber** [comment]
This is the way it works right now and is unfortunately a limitation of TypeScript's own support of JSX. Any JSX expression is "black-boxed" into the type of `JSX.Element` which is not generic, and is an alias for `React.ReactElement<any>`. There isn't any way to pass the constructor type into the JSX instance type itself.

**Comment by carpben** [comment]
Thanks ferdaber, 
Do you know if there is an open feature request at Typescript? I think it's worthwhile.

**Comment by ferdaber** [comment]
This is the closest we got: https://github.com/Microsoft/TypeScript/issues/21699 unfortunately I don't have much visibility into what the TS team is planning on doing to revamp JSX parsing. We are all kind of hoping that whatever change they come up with solves this issue but I'm not entirely sure as it's not on their roadmap yet.

**Comment by carpben** [comment]
Thanks @ferdaber. I guess the most we can do is like the request, to indicate to the Typescript team that we consider it important.
