### ISSUE TITLE
[@types/react] React.forwardRef custom static props

### ISSUE THREAD

**Issue by konrad147** [DefinitelyTyped/DefinitelyTyped#34757]
Hi

I'm trying to use `React.forwardRef` in my Typescript code. The problem is that I want to use dot notation and add some static objects to the ref:

```tsx
const Flex = React.forwardRef(FlexBuilder)
Flex.Item = React.forwardRef(FlexItemBuilder)
// error: Property 'Item' does not exist on type 'ForwardRefExoticComponent<FlexProps & RefAttributes<{}>>'.
```
I cannot add static in a similar way as I can for SFC
I read that I should attach statics to the inner function but it doesn't work in React and also did not fix the problem.
Is there any workaround for that?

**Comment by buyou0821** [comment]
same issue. Have you solved it?

**Comment by konrad147** [comment]
@buyou0821 Unfortunately not

**Comment by hyanmandian** [comment]
I solved this issue with something like this:

```
export interface Props = {
   ...yourPropsHere;
};

export interface CompoundedComponent extends React.ForwardRefExoticComponent<Props & React.RefAttributes<HTMLInputElement>> {
   yourStaticFunctionOrSomethingLikeThat: () => void;
}
```

maybe this can help you on your issue

**Comment by StevenLangbroek** [comment]
We're running into a related issue, but without the `forwardRef`. Basically we'd like any component to be able to act as a root, whether it's a `StyledComponent`, class component or function component... Any thoughts on how to handle that in a flexible way?

**Comment by JoshRosenstein** [comment]
@StevenLangbroek , yeah not sure what @konrad147  meant by:
> I cannot add static in a similar way as I can for SFC

Where the only statics allowed with SFC are propTypes,contextTypes,defaultProps,displayName

One way you can do it
```ts
type WithStatics<
  C extends React.ComponentType<any>,
  StaticCmps extends {
    [attachedComponents: string]: React.ComponentType<any>;
  } = {}
> = C & StaticCmps;

type GridProps = {};
type CellProps = {};

const Cell: React.FunctionComponent<CellProps> = props => <div {...props} />;

const Grid: WithStatics<
  React.FunctionComponent<GridProps>,
  { Cell: typeof Cell }
> = props => <div {...props} />;

Grid.defaultProps = { color: "red" };
Grid.Cell = Cell;
```

**Comment by konrad147** [comment]
@JoshRosenstein  It's available since Typescript 3.1 [Docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html)

Thanks to that the following code works without any errors:
```
const Grid = (props: React.PropsWithChildren<{}>) => (
  <div>
    {props.children}
  </div>
)

Grid.Cell = (props: React.PropsWithChildren<{}>) => (
  <div>
    {props.children}
  </div>
)

const MyComponent = () => (
  <Grid>
    <Grid.Cell>
      Cell's content
    </Grid.Cell>
  </Grid>
)
```
Unfortunately wrapping `Grid` component into `React.forwardRef` breaks that behavior and it's no longer possible to attach a property to a function.

**Comment by JoshRosenstein** [comment]
Im aware of properties declarations on functions, when you said `SFC`, thought you were referring to using the actual typings from @types/react :
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/44022e0f1f8faefd42a4eb747fd3ed9e68fb0721/types/react/index.d.ts#L492-L510

as 
```ts
const Grid: React.SFC<{}> = (props) => <div>{props.children}</div>;

//## ERROR
Grid.Cell = (props: React.PropsWithChildren<{}>) => <div>{props.children}</div>;

const MyComponent = () => (
  <Grid>
    <Grid.Cell>Cell's content</Grid.Cell>
  </Grid>
);
```
So by requesting custom static props for `forwardRef`, it should also be allowed on all other component types within `@types/react`.

**Comment by haideralsh** [comment]
Any update on this? I am having the same issue

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by ivan-kleshnin** [comment]
There seems to be much easier way to achieve the same result:

```tsx
const Flex = React.forwardRef(function Flex(...) {
  ...
})

const FlexRow = React.forwardRef(...)
const FlexColumn = React.forwardRef(...)

const FlexNamespace = Object.assign(Flex, {Row: FlexRow, Column: FlexColumn})

export {FlexNamespace as Flex}

// Now you can use `Flex`, `Flex.Row`, and `Flex.Column` with TS being happy
```

**Comment by ivan-kleshnin** [comment]
There seems to be much easier way to achieve the same result:

```tsx
const Flex = React.forwardRef(function Flex(...) {
  ...
})

const FlexRow = React.forwardRef(...)
const FlexColumn = React.forwardRef(...)

const FlexNamespace = Object.assign(Flex, {Row: FlexRow, Column: FlexColumn})

export {FlexNamespace as Flex}
```

Now you can use `Flex`, `Flex.Row`, and `Flex.Column` with TS being happy. The magic line is `Object.assign` which
does not cause the same type issue as `Flex.Row = FlexRow` does. Don't ask me why, I just accidentally found this 😄

**Comment by hnordt** [comment]
Thank you @ivan-kleshnin!

Your idea actually improves the semantics and makes very clear that we are creating a [compound component](https://kentcdodds.com/blog/advanced-react-component-patterns#compound-components). To make it very clear I just renamed `Namespace` to `Compound`:

```tsx
const RadioGroup = React.forwardRef<HTMLDivElement, RadioGroupProps>(
  function RadioGroup(props, ref) {
    ...
  }
)

const CompoundRadioGroup = Object.assign(RadioGroup, {
  Item: RadioGroupItem,
  Indicator: RadioGroupIndicator,
})

export default CompoundRadioGroup
```

**Comment by wallacerenan** [comment]
when I use this way:

Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
