### ISSUE TITLE
Typescript unable to find puppeteer types

### ISSUE THREAD

**Issue by number33** [DefinitelyTyped/DefinitelyTyped#34752]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @marvinhagemeister @cdeutsch @ksm2 @SimonSchick @serbanghita 

Versions
```
    "@types/jest": "^24.0.11",
    "@types/jest-environment-puppeteer": "^4.0.0",
    "@types/node": "^11.13.4",
    "@types/puppeteer": "^1.12.3",
    "@types/puppeteer-core": "^1.9.0",
    "jest": "^24.7.1",
    "jest-puppeteer": "^4.1.1",
    "puppeteer": "^1.14.0",
    "ts-jest": "^24.0.2",
    "typescript": "^3.4.3"
```

Summary

Trying to use the DirectNavigationOptions type annotation for my options object.  However running my app throws an error with this message `Cannot find name 'DirectNavigationOptions'`.  I'm certain that I'm missing something but not sure where to look.

tsconfig.json
```
{
  "compilerOptions": {
    "alwaysStrict": true,
    "baseUrl": "../",
    "target": "es6",
    "lib": ["es2015"],
    "module": "ES6",
    "moduleResolution": "Classic",
    "newLine": "lf",
    "outDir": "dist",
    "esModuleInterop": true
  },
  "include": [
    "src",
    "node_modules/@types/puppeteer/index.d.ts"
  ]
}```

**Comment by number33** [comment]
I believe I figured out the issue.  In my code I didn't import the interface types
```
import {
    ElementHandle,
    Response,
    NavigationOptions,
    WaitForSelectorOptions
} from 'puppeteer';```

I originally thought that I would be able to use the interfaces without having to explicitly import them.

If there is a way to use them without importing them, please feel free to let me know ;)

**Comment by serbanghita** [comment]
@number33 in TypeScript you need to explicitly import all the resources that you're working with in that specific file, otherwise the transpiling will fail. 

This can be closed as non-related.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
