### ISSUE TITLE
Request:  Renaming sigmajs to sigma and updating its definitions

### ISSUE THREAD

**Issue by cloakedch** [DefinitelyTyped/DefinitelyTyped#34776]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @qinfchen 

Please consider renaming this module from "sigmajs" to "sigma" (like the npm module).
Also the definitions are outdated.

**Comment by LinqLover** [comment]
Hi @cloakedch, I am also interested into using sigmajs with TypeScript. Allow me one question:

My problem is that by saying `import * as sigma from 'sigma';`, I can only use the [function `sigma(conf)` from sigma.js](https://github.com/jacomyal/sigma.js/blob/master/src/sigma.core.js#L63), but not the whole module. To illustrate: 

```ts
import * as sigma from 'sigma';
console.log(sigma);
```
gives me the following output
```
ƒ sigma(conf) {
    // Local variables:
    // ****************
    var i, l, a, c, o, id;
...
```
whereas, for example,
```ts
import * as d3 from 'd3';
console.log(d3);
```
is printed out as a Module object.

I did not find any way to use `sigma.parsers.gexf` which I would like to use.

You mention that you had problems using `@types/sigmajs`. Did you had a similar problem or could you solve it?

What is the reason that you check all points above? This has not yet been solved, has it?

**Comment by cloakedch** [comment]
Honestly, I did not use sigmajs for over a year, because I could not get the typings to work.

Did you try `sigma.sigma()` already? If so, then it is probably the same issue as I was facing: The definitions are simply outdated.

d3 is probably exporting the definitions in a module, while the (outdated) sigmajs definitions are just plain functions...

**Comment by LinqLover** [comment]
> Did you try sigma.sigma() already?

Nope, didn't work either. At the moment I "solved" the issues by copying the source of sigma.js v0.1 into my repo ...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
