### ISSUE TITLE
[@types/styled-system] Theme Interface is incorrect

### ISSUE THREAD

**Issue by peduarte** [DefinitelyTyped/DefinitelyTyped#34794]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @maxdeviant, @phobon, @zephraph, @damassi, @alloy, @maoueh, @Lavoaster @jschuler @adam187 @gretzky @chrislopresto 

---

Hey there 👋 

I've started to integrate `@types/styled-system` with the Design System I'm building - overall it's working really well, thanks for this.

I've noticed a few issues with the `Theme` Interface:
- `fontSizes` can also be an Array of Strings
- `space` can also be an Array of Strings
- `color` can be an object with nested Arrays

Styled System's documentation is missing some of these clarifications, however, I've raised them on their [Spectrum channel](https://spectrum.chat/styled-system/general/unitless-scales~dbd3da0b-398b-4498-9b39-4c4bd82165ea). 

I created a [CodeSandbox](https://codesandbox.io/s/j48y84p8pv) to demonstrate the errors.

Thanks 👊

**Comment by gretzky** [comment]
@peduarte why not just make a PR?

**Comment by peduarte** [comment]
@gretzky following on from https://github.com/styled-system/styled-system/issues/463

I'd love to contribute. I forked and cloned the repo, but the moment I make a single change, prettier is re-formatting everything. I didn't wanna create a PR with a bunch of stylistic changes.

How are you handling this? Just disabling prettier? Should there be a `lint-staged` step where we format files to ensure they're consistent?

**Comment by gretzky** [comment]
@peduarte this really depends on your editor setup. It sounds like you have prettier running globally in your editor and the configuration is set to format on save or type. You'd just need to disable that / configure your editor to only run inside of directories with configurations. This has nothing to do with the repo, its your editor. 

Personally I don't think it makes sense to set up lint-staged or other configs in this repo because then it has the potential to get messier.

**Comment by peduarte** [comment]
@gretzky @Lavoaster Done, please review: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35075
