### ISSUE TITLE
[@types/react-native] add type for undocumented `anchor` prop on `ActionSheetIOSOptions`

### ISSUE THREAD

**Issue by chadlavi-casebook** [DefinitelyTyped/DefinitelyTyped#34859]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @huhuanming @iRoachie @Skn0tt @timwangdev @kamal, others

If you do not mention the authors the issue will be ignored.

--- 

There is an undocumented prop `anchor` that can be passed to `ActionSheetIOS`'s `showActionSheetWithOptions` method, like this:
```
ActionSheetIOS.showActionSheetWithOptions({
  anchor: findNodeHandle(this.menuButton.current),
  ...
}, actionCallback)
```

It doesn't have type definitions because Facebook has failed to document the existence of this prop.

**Comment by iRoachie** [comment]
Seems to be no `achor` param here https://facebook.github.io/react-native/docs/actionsheetios#showactionsheetwithoptions

**Comment by chadlavi-casebook** [comment]
> Seems to be no `achor` param here https://facebook.github.io/react-native/docs/actionsheetios#showactionsheetwithoptions

@iRoachie Yep. As I said, this is, for some reason, undocumented by facebook; and since I assume you all only write types against the documented features, it's quite reasonable that you don't have any types for this. I only learned of its existence when I found someone else complaining that they had a problem with it in a github issue on anther project somewhere else. 

If you add an anchor prop that has a valid ref to some node to an instance of ActionSheetIOS and compile your app for iPad, you'll see that the Action sheet does, in fact, anchor to the referenced node; cf. my screenshot below. This isn't possible to do in ts, however, because the type definition isn't there. 

![image](https://user-images.githubusercontent.com/45078010/56435276-ebff1700-62a5-11e9-93ce-de1da22c62f0.png)

**Comment by iRoachie** [comment]
Seems to be in the code https://github.com/facebook/react-native/blob/master/Libraries/ActionSheetIOS/ActionSheetIOS.js#L46

**Comment by alloy** [comment]
Great thanks! Could you please also file a doc PR with the RN repo? (And can you CC me on it?)

**Comment by alloy** [comment]
lol, only now realized this is an issue, not a PR (on the road). Can you perhaps first file the doc PR so we can see if they didn’t document it because they don’t consider it final API yet? (That’s a reason I’ve seen in the past for not documenting some API.)

**Comment by chadlavi-casebook** [comment]
> lol, only now realized this is an issue, not a PR (on the road). Can you perhaps first file the doc PR so we can see if they didn’t document it because they don’t consider it final API yet? (That’s a reason I’ve seen in the past for not documenting some API.)

Sure! (FYI I'll probably do it under my personal account, @chadlavi; forgot I was still signed in with my work account when I opened this with y'all)

**Comment by chadlavi-casebook** [comment]
@alloy https://github.com/facebook/react-native-website/issues/892

**Comment by chadlavi-casebook** [comment]
> @alloy [facebook/react-native-website#892](https://github.com/facebook/react-native-website/issues/892)

I've opened a PR in their repo to add documentation for `anchor`; seems like they're not very responsive to issues.
