### ISSUE TITLE
[infrastructure] test suite broken by unidentified package.json

### ISSUE THREAD

**Issue by jgonggrijp** [DefinitelyTyped/DefinitelyTyped#34862]
I was working on a pull request for `types/backbone` and tried to run `yarn test` (equivalent to `npm run test`. I got the following error output:

```
Error: In package.json: Don't use a 'package.json' for @types dependencies.
    at checkPackageJsonDependencies (DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:199:19)
    at combineDataForAllTypesVersions (DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:99:37)
Error: Parsing failed.
    at fail (DefinitelyTyped/node_modules/types-publisher/src/util/util.ts:338:20)
    at ChildProcess.child.on (DefinitelyTyped/node_modules/types-publisher/src/util/util.ts:326:21)
    at ChildProcess.emit (events.js:189:13)
    at finish (internal/child_process.js:805:14)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Since this didn't seem to have anything to do with my changes, I tried this on master (commit 03186dbc08 at the time of writing) and got the same result. Unfortunately, this error message does not identify the package.json that is causing the issue.

I used `grep -lF @types/ types/*/package.json` to find all packages that do use a package.json for `@types` dependencies. Result:

```
types/angularfire/package.json
types/chai-webdriverio/package.json
types/forge-viewer/package.json
types/js-data-angular/package.json
types/physijs/package.json
types/react-redux/package.json
types/slack-winston/package.json
types/vue-resource/package.json
types/winston-dynamodb/package.json
types/winston-mail/package.json
types/wonder.js/package.json
```

I then blindly tried removing the `@types` dependencies from these package.json files (see exactly what I did in https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...jgonggrijp:remove-superfluous-dependencies). This got me rid of the error, but I got a different one in return:

```
Error: In package.json: Dependency scroll-into-view-if-needed not in whitelist.
If you are depending on another `@types` package, do *not* add it to a `package.json`. Path mapping should make the import work.
If this is an external library that provides typings,  please make a pull request to types-publisher adding it to `dependenciesWhitelist.txt`.
    at checkPackageJsonDependencies (/Users/julian/Documents/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:199:19)
    at combineDataForAllTypesVersions (/Users/julian/Documents/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:99:37)
Error: Parsing failed.
    at fail (/Users/julian/Documents/DefinitelyTyped/node_modules/types-publisher/src/util/util.ts:338:20)
    at ChildProcess.child.on (/Users/julian/Documents/DefinitelyTyped/node_modules/types-publisher/src/util/util.ts:326:21)
    at ChildProcess.emit (events.js:189:13)
    at finish (internal/child_process.js:805:14)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

I again needed `grep` to find the package that contains the offending dependency: it is react-scroll-into-view-if-needed. I don't know enough about the matter to understand whether this dependency should be whitelisted or deleted.

I would otherwise use `git bisect` to find the commit that introduced this problem, but I know that the test script has previously failed on master for different reasons.

All in all, I think this issue is about three problems:

 1. The test script is currently failing on master and it is not clear how to fix this. People working on pull requests are not able to verify their changes because of this.
 2. When the test script objects against a dependency in a package.json, it does not identify the exact file that is causing the error, which makes it rather cumbersome to debug.
 3. Neither the project README nor the issue template provides any guidance on how to report infrastructural problems.

~If you know how to fix the issue, make a pull request instead.~

- [x] I tried using the `@types/backbone` package and had problems. *I have a problem with the DefinitelyTyped repository as a whole, but I first noticed it while working on a pull request for `types/backbone`.*
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond. *Below I mention all authors of packages that seem to be playing a role, as well as the people that were active in #32909 and a few more people I guess-picked from recent frequent committers. My apologies in advance to any people I shouldn't have mentioned. If you know someone who should be mentioned as well, please do.*
  - Authors: @thSoft @sherlock1982 @Autodesk-Forge @alansmithnbs @reppners @gyohk @tkqubo @kenzierocks @clayne11 @tansongyang @nicholasboll @mdibyo @kallikrein @val1984 @jrakotoharisoa @apapirovski @surgeboris @soerenbf @BlueHatbRit @kaorun343 @nickiannone @idono87 @yyc-git @angusfretwell @allanpope @jonathanly @minestarks @sandersn @andy-ms @BendingBender 

~If you do not mention the authors the issue will be ignored.~

**Comment by sandersn** [comment]
Stupid initial question: have you tried pulling from master and re-installing node_modules? The build is working fine for me locally.

**Comment by jgonggrijp** [comment]
I did that just before starting my feature branch, but to make sure, I’ll try again when I’m back at my desk.

**Comment by jgonggrijp** [comment]
I ran

```console
$ git clean -fdx
$ git pull
$ yarn  # (equivalent to npm install)
$ yarn test
```

and now the error is gone. My apologies for the noise. Thanks @sandersn for helping out so quickly.

The previous time I ran `yarn`, I didn't bother to completely delete my `node_modules` first. I also didn't realise that the `yarn.lock` was my own creation, rather than a lockfile that belonged in the repository.

Out of curiosity, why not a controlled `package-lock.json` or `yarn.lock`?

**Comment by sandersn** [comment]
I took over the repo about 6 months ago so I'm not entirely sure. If I had to guess, I'd say it's because we install one of the two dependencies, types-publisher, from github rather than npm, and the other dependency, dtslint, used to be the same -- but it's now `latest` from npm, which is not much different. In other words, types-publisher and dtslint are effectively part of the code base of DT, so it should be running their latest versions at all times.

I'm not an expert on dependency management, so if you can point me to other ways to meet the goal of "always latest", I'd be happy to learn about them.

**Comment by jgonggrijp** [comment]
I understand that having a lockfile is at odds with keeping dependencies always at the latest version. Yarn's default install command will install the locked version is there is a lockfile, whether there is an update or not. My experience with NPM is a bit less reliable, but having a locked version will not help in any case. If you were to maintain a lockfile, you'd need to somehow ensure it is kept up-to-date, so I think it makes sense in this case to just not have one.

NPM and Yarn both automatically generate a lockfile if one doesn't exist yet, so it also makes sense to `.gitignore` it. However, this is not enough to prevent contributors from installing the dependencies, keeping their local clone on disk, coming back later and continue working with locked outdated versions of the dependencies. Like I did.

You need to ensure that recurring contributors run additional commands to keep the packages fresh. Ideally, contributors would always run `yarn upgrade` or `npm update --dev --no-save`, but this is impossible to enforce and very tricky to automate. I can think of a few other options:

 - Document the need to manually keep the packages fresh.
 - Automatically delete the `package-lock.json` or `yarn.lock`. This is relatively straightforward to do with a `postinstall` script. This might even be enough for people like me a few hours ago, who don't realize they need to force an upgrade but who do instinctively run `yarn` or `npm install` just because the dependencies may have changed.

Something like this should work both in bash and in cmd.exe:

```
rm -f package-lock.json yarn.lock || del /Q package-lock.json yarn.lock
```

With a little bit more sophistication you could probably make it work in powershell as well.

Anyway, I've learned my lesson. I'll make sure to upgrade the packages from now on.
