### ISSUE TITLE
[@types/koa-session] Consider replacing koa.Context with koa.BaseContext?

### ISSUE THREAD

**Issue by liaozhongwu** [DefinitelyTyped/DefinitelyTyped#34924]
- [x] I tried using the `@types/koa-session` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kerol2r20 @tlaziuk @hirochachacha 

Since @types/koa use **ParameterizedContext** inside:
```
type Middleware<StateT = any, CustomT = {}> = compose.Middleware<ParameterizedContext<StateT, CustomT>>;

type ParameterizedContext<StateT = any, CustomT = {}> = BaseContext & {
        app: Application;
        request: Request;
        response: Response;
        req: IncomingMessage;
        res: ServerResponse;
        originalUrl: string;
        cookies: Cookies;
        accept: accepts.Accepts;
        state: StateT;
        /**
         * To bypass Koa's built-in response handling, you may explicitly set `ctx.respond = false;`
         */
        respond?: boolean;
} & CustomT;

interface Context extends ParameterizedContext {}
```
so overwrite of **koa.Context** had no effect at all, using **koa.BaseContext** might be a good idea, thanks.

**Comment by liaozhongwu** [comment]
#34925

**Comment by mhockenbury** [comment]
Thanks for this! I just started bumping my head against the context type issues. `e.g. Types of parameters 'ctx' and 'context' are incompatible. -> Type 'ParameterizedContext<any, IRouterParamContext<any, {}>>' is not assignable to type 'Context'.`

I tested the changes in #34925 within my project and the type errors were cleared up.

**Comment by twhitbeck** [comment]
looks like the ball got dropped on this. I'm finding `@types/koa-session` completely useless without these changes

**Comment by lordofpipes** [comment]
@twhitbeck @liaozhongwu I've opened up a new pull request, this time with a new unit test.
