### ISSUE TITLE
@types/mongodb Aggregation should always return AggregationCursor<any> because of $lookup

### ISSUE THREAD

**Issue by patarapolw** [DefinitelyTyped/DefinitelyTyped#34956]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mongodb.d.ts` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT 

For example,

    public getQuery(userId: ObjectID, cond: any, options: any[], isUser: boolean = true): AggregationCursor<any> {
        return this.db.token.aggregate([
            {$lookup: {
                from: "vocab",
                localField: "name",
                foreignField: "simplified",
                as: "v"
            }},
            {$unwind: {
                path: "v",
                preserveNullAndEmptyArrays: true
            }},
            {$lookup: {
                from: "card",
                let: {entry: "$name"},
                pipeline: [
                    {$match: {
                        userId,
                        entry: "$$name"
                    }}
                ],
                as: "c"
            }},
            {$unwind: {
                path: "c",
                preserveNullAndEmptyArrays: !isUser
            }},
            {$lookup: {
                from: "deck",
                localField: "c.deckId",
                foreignField: "_id",
                as: "d"
            }},
            {$unwind: {
                path: "d",
                preserveNullAndEmptyArrays: true
            }},
            {$match: cond},
            ...options
        ], {allowDiskUse: true});
    }

The default typing of `AggregationCursor<T>` is plain wrong. Should always be `AggregationCursor<any>` for in case of `$lookup`.

**Comment by CaselIT** [comment]
The signature is `aggregate<T = TSchema>(callback: MongoCallback<AggregationCursor<T>>): AggregationCursor<T>;`, so you can set the type you want.

Try `this.db.token.aggregate<any>...`

**Comment by patarapolw** [comment]
Of course it works. Just to mention that aggregate typings can easily break because of `$lookup` and `$project`. It is no longer `TSchema`.

**Comment by CaselIT** [comment]
Indeed, `TSchema` is the default type, but it should be overridden when the return value is not a `TSchema`.

Maybe a case could be made to change the default type.
Try tagging the other authors in the issue so have also their opinion

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
