### ISSUE TITLE
TypeError: checkPropTypes is not a function

### ISSUE THREAD

**Issue by okhy** [DefinitelyTyped/DefinitelyTyped#35010]
- [x] I tried using the `@types/prop-types` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DovydasNavickas , @ferdaber , @eps1lon 

----
Hello, during jest/enzyme run I get the following error `TypeError: checkPropTypes is not a function` whenever I use a module that uses proptypes (like `react-router` in my case).

During my research I've concluded that Typescript sees PropTypes as {} even though I'm using `@types/prop-types` and I can see properly typed `checkPropTypes` function there.

Is there any suggestion you could give to help resolve this issue?

Project/code repo: https://github.com/okhy/ERM/tree/TASK_6_Routing

####How to reproduce: 
1. checkout `TASK_6_Routing` branch
2. `npm i`
3. `npm run test`

**Comment by eps1lon** [comment]
Do you use this function in your code or is this called in another module? A full stack trace would help. In any case this is not an issue with the types (the `TypeError` message is a bit misleading. The `TypeError` is a runtime error in this case which cannot be cause by any `@types/*` package.

**Comment by okhy** [comment]
Hello, the full error returned by Jest: 
```javascript
TypeError: checkPropTypes is not a function

      51 |   it("... renders no-poster message ", () => {
      52 |     const wrapper = shallow(
    > 53 |       <MemoryRouter>
         |       ^
      54 |         <MovieGridItem {...mockMovie} poster="" />
      55 |       </MemoryRouter>
      56 |     );

      at validatePropTypes (node_modules/react/cjs/react.development.js:1666:5)
      at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:1755:5)
      at Object.<anonymous> (src/components/MovieGrid/components/MovieGridItem/MovieGridItem.test.tsx:53:7)
```

**Comment by okhy** [comment]
Hello, any chance for a hint as to why that might happen?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
