### ISSUE TITLE
[@types/next-server/router.d.ts] add `useRouter` definition

### ISSUE THREAD

**Issue by JerryGreen** [DefinitelyTyped/DefinitelyTyped#35019]
- [ ] Add useRouter hook definition (https://github.com/zeit/next.js/pull/6869)

- [ ] Overall follow the version `8.1.0` (currently it's `8.0.4`) ?

**Comment by JerryGreen** [comment]
Not sure how to contribute here but here are the typings (custom from my project):

###### types/next/router.d.ts
```
import { RouterProps } from 'next-server/router'

export function useRouter(): RouterProps
```

**Comment by JerryGreen** [comment]
Need to add this function:

```
export function useRouter(): RouterProps
```

To here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/next-server/router.d.ts

**Comment by kachkaev** [comment]
@JerryGreen 👀 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35058
