### ISSUE TITLE
[@types/google-apps-script] Update types for Spreadsheet.Range

### ISSUE THREAD

**Issue by Serega124** [DefinitelyTyped/DefinitelyTyped#35059]
- [x] I tried using the `@types/google-apps-script` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (3.4.1)
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @motemen @grant 

According to the [Google Apps Reference](https://developers.google.com/apps-script/reference/spreadsheet/range#setBorder(Boolean,Boolean,Boolean,Boolean,Boolean,Boolean)), this code should work:
```javascript
var cell = sheet.getRange("B2");
// Sets borders on the top and bottom, but leaves the left and right unchanged
cell.setBorder(true, null, true, null, false, false);
```
But I get type error: `Argument of type 'null' is not assignable to parameter of type 'boolean'.` because of declared methods:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a07c7f577730ad2a52753ddf52ef15450ccfcdea/types/google-apps-script/google-apps-script.spreadsheet.d.ts#L1497-L1498

**Comment by mtgto** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37947 fixed
