### ISSUE TITLE
[@types/slate-react] Plugins prop missing Slate core plugin type

### ISSUE THREAD

**Issue by LudvigHz** [DefinitelyTyped/DefinitelyTyped#35065]
The `plugins` prop on the Editor only takes slate-reacts event and render hooks. The prop should also accept Slates core plugin type. https://docs.slatejs.org/slate-core/plugins

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andykent @majelbstoat @JanLoebel @PatrickSachs @YangusKhan @isubasti @sgreav @Kornil @jackall3n @benjiro

**Comment by DinMon** [comment]
Could you give example of prop missing from Slates Core?

**Comment by LudvigHz** [comment]
Whoops.
This was fixed in #35899

So I'll close this.
