### ISSUE TITLE
[@types/slate-react] EventHook wrong event type

### ISSUE THREAD

**Issue by LudvigHz** [DefinitelyTyped/DefinitelyTyped#35063]
Using either plugins or defining eventhandlers on a custom component requires type assertion of event.
It seems like all the event handlers use the `EventHook` type, where the event argument simply is an `Event`. It seems to me like they really should be specific to the event, ie. the event in `onClick` should be `KeyboardEvent` and not `Event`. This way you dont have to use type assertion every time. They should also use reacts event objects, as specified in the docs.
https://docs.slatejs.org/slate-react/plugins#hooks

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andykent @majelbstoat @JanLoebel @patricksachs @YangusKhan @isubasti @sgreav @Kornil @jackall3n @benjiro

If you do not mention the authors the issue will be ignored.

**Comment by gomesalexandre** [comment]
Hey ! I'm also experiencing issues with these typings, I'll update this issue if I find a solution to re-type in usage.
