### ISSUE TITLE
Type 'KnockoutObservableArray' is missing property 'getSubscriptionsCount' from type 'KnockoutObservableAny'

### ISSUE THREAD

**Issue by niemyjski** [DefinitelyTyped/DefinitelyTyped#351]
After updating to the latest knockout type definitions I'm getting the following error on one of my constructors. 
Supplied parameters do not match any signature of call target:
    Type 'KnockoutObservableArray' is missing property 'getSubscriptionsCount' from type 'KnockoutObservableAny'

The parameter type is: data?: KnockoutObservableAny
and the passed in type is: ko.observableArray([])

The culprit seems to be the commit on the 22nd:

interface KnockoutObservableBase extends KnockoutObservableFunctions {
    getSubscriptionsCount(): number;
}

**Comment by ltlombardi** [comment]
@niemyjski Already fixed. Could you close this issue?

**Comment by ltlombardi** [comment]
Hey @Igorbek , If you are feeling up to it, all the bellow I've analysed all the bellow issues, and requested them to be closed a long time ago:

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/672
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/676
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/765
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/1210
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/3327
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/3895
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/8625
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14381
