### ISSUE TITLE
ensureDir and ensureDirSync miss the options argument

### ISSUE THREAD

**Issue by sangdth** [DefinitelyTyped/DefinitelyTyped#35111]
- [x] I tried using the `@types/fs-extra` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alan-agius4 , @midknight41 , @shiftkey , @mees- , @jrockwood 

---

In the [source](https://github.com/jprichardson/node-fs-extra/blob/master/docs/ensureDir-sync.md), `ensureDirSync` has dir and options, but in [@types/fs-extra](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/39b4723424d50447bcce7cac1fe3c2b8a223d0cc/types/fs-extra/index.d.ts#L36), we have only `dir` argument, so tslint complain about it with `Expect 1 argument, but got 2` when I use `fs.ensureDirSync(rcDir, 0o700)`

---

I have tried to modify the code like this:
```javascript
export function ensureDirSync(path: string, options?: EnsureOptions): void;

...

export interface EnsureOptions {
    mode?: number
}
```
But it caused the tslint with new error:  `Argument of type 448 is not assignable to parameter of type EnsureOptions | undefined`

Seem like I have to let professional people solve it 💃

**Comment by shiftkey** [comment]
> Seem like I have to let professional people solve it 💃

I disagree, and I think you're pretty close to the solution.

Here's my guidance for getting this fixed

1. Add some tests in this file that you expect to work (but fail currently):

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/39b4723424d50447bcce7cac1fe3c2b8a223d0cc/types/fs-extra/fs-extra-tests.ts#L145-L149

The docs are a great guide for this, so feel free to borrow from those examples.

2. Update the declaration to add support both forms of `options` to satisfy the tests:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/39b4723424d50447bcce7cac1fe3c2b8a223d0cc/types/fs-extra/index.d.ts#L36-L38

I think you're close with the `EnsureOptions` you have in currently, but the example you mentioned also seems to indicate you can just pass in a number too:

```ts
export function ensureDir(path: string, options?: EnsureOptions | number): Promise<void>;
export function ensureDir(path: string, options?: EnsureOptions | number, callback?: (err: Error) => void): void;
export function ensureDirSync(path: string, options?: EnsureOptions | number): void;

... 

export interface EnsureOptions {
    mode?: number
}
```

3. When you feel this is good to go, open a PR and we can discuss the changes further (and hopefully merge it in!)

**Comment by sangdth** [comment]
Thanks, I have followed your guidance and made the PR here #35117
