### ISSUE TITLE
[@types/node-telegram-bot-api] WebHookOptions doesn't require key, cert and pfx

### ISSUE THREAD

**Issue by maple3142** [DefinitelyTyped/DefinitelyTyped#35206]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ammuench @agadar @Dabolus @Kallu609 @XC-Zhang

If you do not mention the authors the issue will be ignored.

As what I said in the title, it is not necessary to provide `key`, `cert` and `pfx` to use WebHook. https://github.com/yagop/node-telegram-bot-api/issues/125
```ts
interface WebHookOptions {
    host?: string;
    port?: number;
    key: string;
    cert: string;
    pfx: string;
    autoOpen?: boolean;
    https?: ServerOptions;
    healthEndpoint?: string;
}
`

**Comment by ammuench** [comment]
I'll get a PR open for this shortly
