### ISSUE TITLE
[different packages] intersection types used wrong

### ISSUE THREAD

**Issue by akomm** [DefinitelyTyped/DefinitelyTyped#35228]
Typescript has a lax behavior in a specific case of intersection:

```ts
// vendor typings
type A = {
  handler: (x: number) => void,
};
type B = {
  handler: (x: string) => void,
};

type C = A & B; // {handler: ((x: number) => void) & ((x: string) => void)}

// your consuming code
function works(c: C) {
  c.handler(10); // works
  c.handler("string"); // works
}
```

It is impossible to create type C. However, typings do not impose creation of types in the typings code itself. Also often consumer of typings do not instantiate things, like in the example above, we have a function which takes an C, however it might have been constructed by untyped vendor code for which the typing is provided (hoc for example).

TS does **not**:

1. Merge LHS over RHS, like `Object.assign` or object spread `{...a, ...b}`, as it is not what an intersection does.
2. Strictly fail to call C handler, because C handler is two different signatures at the same time, which both can not be satisfied at the same time.

TS does:
3. Treat the intersection as an **union** in this case.

Specifically when the property is a **function/method** signature. 

Using different typings over a longer period of time, I realized that many times the **1.** behavior is assumed. Intersection is used often as a merger, as often as object spread or `Object.assign` in JS. So quite common. This leads to typings which give false positives, because they basically allow all the possible types instead of one.

TS could have prevented this issue, if it behaved strictly as stated in case **2.**. People would realize the typing is wrong and fix it.

I did not start collect all the places I found this issue right ahead, until I recently realized this might be a common issue and also it started bother me as it affects important libraries. Last such example I recall:

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31893#issuecomment-451507397

As long as TS behaves this way, we must do something so people realize this mistake and stop using intersections the wrong way. 

However I am not certain how to achieve this here. I can not check every package and also can not add every possible author here so they are notified and can check this. 

Important is that no matter whether it remains this way or TS will be changed its behavior, in both cases this way of using intersection is wrong. While currently we get lax API, when this change it would simply cause havoc all over the place where it falsely gave positive before.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
