### ISSUE TITLE
[@types/fs-extra] New version 5.1.0 ensureDir has an incorrect type definition for callback

### ISSUE THREAD

**Issue by coopa** [DefinitelyTyped/DefinitelyTyped#35242]
- [X] I tried using the `@types/fs-extra` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alan-agius4 , @midknight41 , @shiftkey , @mees- , @jrockwood, @sangdth 

There is a minor, though build-breaking, issue introduced by a recent change to fs-extra 5.1.0 based on the following merge: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35117
This change makes it so TSC is no longer happy with a callback as a second parameter and throws the following error:
```error TS2345: Argument of type '() => void' is not assignable to parameter of type 'number | EnsureOptions'.
  Type '() => void' has no properties in common with type 'EnsureOptions'
```

Here is the target source in question: https://github.com/jprichardson/node-fs-extra/blob/master/lib/mkdirs/mkdirs.js

According to the source code using a callback as a second parameter is a legitimate use-case. As an aside, it also appears the actual callback type definition is incorrect being `(Error) => void` whereas it ought to be `(Error, string) => void`.

**Comment by shiftkey** [comment]
@coopa thanks for the report. I've extracted the relevant internal checks that aren't clear from the docs:

```js
function mkdirs (p, opts, callback, made) {
  if (typeof opts === 'function') {
    callback = opts
    opts = {}
  } else if (!opts || typeof opts !== 'object') {
    opts = { mode: opts }
  }

  // ...
```

Like we talked about in #35111, the best next steps would be to add a failing test to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/fs-extra/fs-extra-tests.ts that should reflect what is supported, and then open a PR to figure out how to address this in the signature itself.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
