### ISSUE TITLE
[@types/react] useMemo's deps are should be optional

### ISSUE THREAD

**Issue by Jonir227** [DefinitelyTyped/DefinitelyTyped#35275]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
    Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei @Jessidhia @pshrmn @saranshkataria @lukyth @eps1lon

```js
// allow undefined, but don't make it optional as that is very likely a mistake
function useMemo<T>(factory: () => T, deps: DependencyList | undefined): T;
```
I think this is not correct. this function is designed to have optional deps param.
and also conflict with `eslint-react-hooks`. see the example below.

I wanted make editor model only once. so l wrote code like this.

![image](https://user-images.githubusercontent.com/21289079/57347464-5e6c6400-718d-11e9-990a-82e3188a965d.png)

and got this warning.

![image](https://user-images.githubusercontent.com/21289079/57347525-8c51a880-718d-11e9-9aee-0bf688860b71.png)

so I removed empty array and then I got this

![image](https://user-images.githubusercontent.com/21289079/57347578-bc00b080-718d-11e9-9884-8ae970dcb9de.png)

I know that this model variable can be exist ouside of the function. but I'm curious that this function can be used without deps param in js but why cannot used like this in TS.

thanks for reading!

**Comment by Jessidhia** [comment]
I'm not sure if this is already in a release version of the eslint plugin, but omitting the second argument is _also_ an error according to the eslint plugin.

See this from the current eslint plugin code in master https://github.com/facebook/react/blob/c7398f33966c4fedcba2c48e915b379e8f334607/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js#L86-L107

**Comment by Jonir227** [comment]
thank's for the response. nice explaination! I'll close this issue.
