### ISSUE TITLE
[@types/react__router] Make staticContext a part of Router interface

### ISSUE THREAD

**Issue by Dattaya** [DefinitelyTyped/DefinitelyTyped#35279]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sergey-buturlakin @mrk21 @vasek17 @ngbrown @awendland @KostyaEsmukov @johnnyreilly @LKay @DovydasNavickas @tkrotoff @huy-nguyen @Grmiade @egorshulga @neuoy @rraina @pret-a-porter @t49tran @8enSmith @wezleytsai @eps1lon @HipsterBrown 

What do you think about making [`staticContext`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Router.js#L61) to be a part of the public API. I use [qhistory](https://github.com/pshrmn/qhistory) that can parse/stringify query params and need to provide it on the server as well: `<Router history={qhistory(...)} staticContext={staticContext}>`, but `Router` props so far only include `history`:

```ts
export interface RouterProps {
  history: H.History;
}
```

**Comment by eps1lon** [comment]
This is a question best answered by maintainers of `react-router`. We just add types for the public interface. We shouldn't decide what is part of the public API and what not.

**Comment by Dattaya** [comment]
Got it, thanks, closing then

**Comment by eps1lon** [comment]
I'm also a bit confused where this should be added. We already have [`staticContext` typed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e2e5298c1f2d2ea96fba2413b5bbe767f11c01f6/types/react-router/index.d.ts#L75)

**Comment by Dattaya** [comment]
`StaticRouter` [uses `Router` underneath](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/StaticRouter.js#L82): `<Router {...rest} history={history} staticContext={context} />` so it should be like that? :

```ts
export interface RouterProps {
  history: H.History;
  staticContext?: StaticContext;
}
```

**Comment by eps1lon** [comment]
Well this is best discussed by adding documented usage to the types test and see if it fails. I don't think it's helpful the extract type definitions from the implementation.
