### ISSUE TITLE
Lodash: `negate`: wrong overload is used for function with rest parameters

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#35273]
``` ts
declare const fnWithRestParameters: (...args: number[]) => boolean;
_.negate(fnWithRestParameters); // $ExpectType (...args: number[]) => boolean
```

With `strictFunctionTypes` disabled, this test fails. The actual type is `() => boolean`.

I tried to fix/workaround this in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35271, but we decided to wait for TS 3.0 support in the Lodash types, since we need generic rest parameters to fix it properly.

Opening this issue to track the bug, so we can revisit when TS 3.0 support lands.

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by aj-r** [comment]
For reference, the PR that adds ts3 support is #35241.
(I was wrong, it's actually ts3.1, not ts3.0)

**Comment by sandersn** [comment]
Yep, typesVersions was a new feature in 3.1, making it a lot easier to put the old/new divide at 3.1 instead of 3.0.

**Comment by aj-r** [comment]
The PR has been merged.

**Comment by OliverJAsh** [comment]
In TS 3.1+, this is fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35241/files#diff-da0934ce815afe03ba88e6bb5d6f6f2fR524.

Carried [the tests I wrote for this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35271/files#diff-6a82a43b7b79f07644334583c1add52aR3522) over to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35341.
