### ISSUE TITLE
Remove dependency to jQuery from angular

### ISSUE THREAD

**Issue by awerlang** [DefinitelyTyped/DefinitelyTyped#3528]
In the first lines of angular.d.ts there's this line:

```
/// <reference path="../jquery/jquery.d.ts" />
```

jQuery is optional for angular to work, and many run without it, because you might not need it.

If I remove its typing file, I got

```
Error   24  Incorrect reference: file "...\typings\jquery\jquery.d.ts" does not exist
```

Would it be possible to make it optional also in its typing?

For instance, when not using jQuery, interface for angular.element() would offer methods that aren't available and even some that don't fulfill the same signature.

I propose to have IAugmentedJQuery not extend JQuery but jqLite interface. For those using jQuery,it could extend current IAugmentedJQuery in another .d.ts.

What do you think?

PS: it could solve #2734, conflict with protractor, that defines a '$' symbol too.

**Comment by nojaf** [comment]
That would be good thing indeed. Where can I help?

**Comment by Dashue** [comment]
+1

**Comment by adidahiya** [comment]
+1

**Comment by awerlang** [comment]
@nojaf I did this PR. You could copy this .d.ts to your local repository before it is merged and see if anything's broken.

**Comment by nojaf** [comment]
Works for my project. I do only use the default angular.d.ts file in my code. So I can't speak for all of it. Great work however!
