### ISSUE TITLE
[@types/node] Argument is not assignable to parameter of type '() => void'

### ISSUE THREAD

**Issue by jgiovaresco** [DefinitelyTyped/DefinitelyTyped#35306]
The following PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33527) has changed the signature of `Server.listen` functions. It replaced the last argument type from `Function` to `() => void`

This change broke the following (pseudo) code

```
import Bluebird from 'bluebird';
import { createServer } from 'http';

const httpServer = createServer();
const PORT = 8080;
await Bluebird.fromCallback(cb => httpServer.listen(PORT, cb))
```

The compiler error is `TS2345: Argument of type '(err: any, result?: {} | undefined) => void' is not assignable to parameter of type '() => void'.`

As we can see the type of `cb` in `@types/bluebird` is a callback type `(err: any, result?: {} | undefined) => void` which is incompatible to the simple type `() => void`

Shouldn't we update the type of the last argument to be a "callback" type ? 

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] Authors: @SimonSchick

**Comment by SimonSchick** [comment]
You may want to re-read the [docs](https://nodejs.org/api/net.html#net_server_listen), the callback in `.listen` is in fact not a node-style error/result callback but an event listener callback.
The error is expected.

**Comment by jgiovaresco** [comment]
Indeed, my bad I misunderstood...
