### ISSUE TITLE
[@types/node-fetch] Possibly wrong introduction of 'url' property as mandatory part of ResponseInit

### ISSUE THREAD

**Issue by Retro64** [DefinitelyTyped/DefinitelyTyped#35303]
- [x] I tried using the `@types/node-fetch` package and had problems.
- Authors: @wilsonianb @PranavSenthilnathan

The last PR introduced the mandatory property 'url' in the RequestInit interface

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-fetch/index.d.ts#L182

Node fetch references (https://github.com/bitinn/node-fetch/blob/bf8b4e8db350ec76dbb9236620f774fcc21b8c12/README.md#new-responsebody-options) the official fetch spec regarding ResponseInit objects:

 https://fetch.spec.whatwg.org/#responseinit

This contains no 'url' property, so I assume the property should be an optional, but I have no context why it was introduced this way.

**Comment by wilsonianb** [comment]
Nice catch.
I think made `url` mandatory because it was required on [Response](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6c8d67bc13666a14e540485bf79157800198f6b9#diff-16dd1699972b26236bcd5bc367af23fbR165) and the [Response constructor](https://github.com/bitinn/node-fetch/blob/master/src/response.js#L26-L46) wasn't assigning a default value.
The spec that you linked says
>The url attribute’s getter, when invoked, must return the empty string if the context object’s response’s URL is null and the context object’s response’s URL, serialized with the exclude-fragment flag set, otherwise.

So I think `""` needs to either be assigned in the constructor or returned in the `url` getter if `url` is undefined.

**Comment by Retro64** [comment]
I just created an issue in node-fetch to fix the constructor (https://github.com/bitinn/node-fetch/issues/635). Nevertheless the RequestInit should follow the definition in the fetch specification, so I still suggest to make url optional - especially as it is breaking now and not to "fix" the bug in the constructor by enforcing properties. I might provide a PR for this missing '?'. What do you think @wilsonianb ?

**Comment by wilsonianb** [comment]
I also agree `url` should be made optional here.
Feel free to submit the pr or let me know if you'd like for me to do it.
And thanks for submitting both this and the issue in node-fetch.

**Comment by Retro64** [comment]
@wilsonianb I did not manage to tackle this during the weekend and it looks like I will not have time this week - could you maybe take over? Thanks

**Comment by dsvensson** [comment]
Shouldn't fetch be:

```
(input: RequestInfo, init?: RequestInit) => Promise<Response>
```

**Comment by wilsonianb** [comment]
@Retro64 no problem. Here's the PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35414

@dsvensson I also went ahead and updated the `input`/`url` type in the `fetch` definition.
