### ISSUE TITLE
[@types/react-redux] connect() loses discriminated union prop interface information

### ISSUE THREAD

**Issue by esseb** [DefinitelyTyped/DefinitelyTyped#35315]
- [x] I tried using the `@types/react-redux` package and had problems.
  - Tested `@types/react-redux@7.0.8`
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Tested `typescript@3.4.5`
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo, @kenzierocks, @clayne11, @tansongyang, @nicholasboll, @mdibyo, @kallikrein, @val1984, @jrakotoharisoa, @apapirovski, @surgeboris, @soerenbf

When using `connect()` to connect a component that uses a prop interface with a union type, the discriminated union type information appears to disappear.

My props interface setup:
```
interface IBaseProps {
  children: React.ReactNode;
  type: "name" | "nickname";

  // From connect
  theme?: "dark" | "light";
}

export interface INameProps extends IBaseProps {
  type: "name";
  name: string;
}

export interface INicknameProps extends IBaseProps {
  type: "nickname";
  nickname: string;
}

type IProps = INameProps | INicknameProps;
```

Testcase that shows the behavior with the unconnected component (which works as expected) and the connected component (which does not): https://codesandbox.io/s/n0oq10w170

The codesandbox testcase uses typescript@3.3.3, the same testcase with typescript@3.4.5 (the current latest) can be found on https://github.com/esseb/react-redux-type-union-prop-and-connect

The `src/Person.tsx` file includes the connected and unconnected components, and `src/index.tsx` shows examples of the connected and unconnected component in use which shows that the connected component does not behave as expected.

Screenshot from `src/index.tx` from the codesandbox testcase:
![Skjermbilde 2019-05-09 kl  14 16 35](https://user-images.githubusercontent.com/207794/57452836-14ef4800-7265-11e9-80cd-6d615a8f4ae9.png)

**Comment by nlesiecki** [comment]
Thanks for writing this up! I'm experiencing something similar in my project.

**Comment by rssfrncsrenishaw** [comment]
Might be worth updating this title to mention either "discriminated union" or "tagged union" which is what this issue is really about

**Comment by esseb** [comment]
@rssfrncsrenishaw I'm not very confident in the terminology. Is the title `[@types/react-redux] connect() loses discriminated union prop interface information` ok?

**Comment by esseb** [comment]
I think using [distributive conditional types](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#distributive-conditional-types) would solve this, as explained on https://stackoverflow.com/a/57103940/656578

I solved a similar issue in a custom HOC using that technique, but I'm not sure where to fix that in the react-redux types.

**Comment by jfirebaugh** [comment]
I briefly tried switching to a distributive `Omit` here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0e9f7eb3a2d623b0ce7d7b95ca8353c8b8e1b784/types/react-redux/index.d.ts#L39

But it didn't resolve the errors I was getting with connected components which use unions in prop types.

**Comment by valentinacala** [comment]
@esseb did you find a solution ? I'm also experiencing the same issue when using connect.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
