### ISSUE TITLE
Add types for estree jsx ast

### ISSUE THREAD

**Issue by golopot** [DefinitelyTyped/DefinitelyTyped#35355]
Is it better to put jsx ast types in a new package? Or should they be put in types/estree?

Facebook hosts this [draft of jsx spec](https://github.com/facebook/jsx/blob/master/AST.md).

**Comment by antross** [comment]
I recently created some JSX AST types as part of adding JSX support to webhint in https://github.com/webhintio/hint/pull/3109 and wanted to contribute them. 

Given this hasn't had a response I went ahead and opened a PR to add JSX AST types as a new package in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39215. We'll see where the discussion leads from there.
