### ISSUE TITLE
[@types/prosemirror-view] DecorationAttrs interface usage

### ISSUE THREAD

**Issue by jemhuntr** [DefinitelyTyped/DefinitelyTyped#35369]
The DecorationAttrs interface only exposes the members `class`, `style`, and `nodeName` when it supposedly should allow arbitrary attributes which ProseMirror will add directly to the DOM node as HTML attributes.

Currently, I need to forcefully cast the object so it doesn't give a type error:
```js
{ class: 'some-class', 'data-placeholder': 'Some text...' } as DecorationAttrs
```

Is this intended behavior?
If not, should the DecorationAttrs be a simple type like `{ [key: string]: string }` instead?

@bradleyayers @davidka @timjb @patsimm

**Comment by timjb** [comment]
@jemhuntr No, it should of course be possible to add other properties like `data-placeholder` to `DecorationAttrs`. One possibility to achieve this would be to add the line

```
  [key: string]: string;
```

to the interface definition. Compared to using the type `{ [key: string]: string }` this has the advantage of preserving IDE support for the special keys `class`, `style` and `nodeName`. I would approve a pull request implementing this change!

The reason this wasn't done in the first place is that the type definitions have been generated from the getdocs-style doc comments in the ProseMirror sources. Unfortunately, some important information needed for generating really good type definitions (e.g. should extra fields be allowed?) is not included in these comments. Hence, you will certainly come across other methods in the ProseMirror API where the documentation describes the expected form of the arguments in prose, but the type definitions do not capture that form. If you do so, please send a PR! :-)

**Comment by jemhuntr** [comment]
Just sent a PR :) Do let me know if there are any issues with the changes.

I'll close this issue now; we can just continue the discussion at my PR. Thanks!
