### ISSUE TITLE
[@types/react] Shouldn't the TypeScript definition for Reducers enforce ReadOnly for prevState?

### ISSUE THREAD

**Issue by justinhelmer** [DefinitelyTyped/DefinitelyTyped#35389]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Jessidhia

Because there are so many authors listed in the comments, I ran a git blame on the `Reducer` definition and only included that person.

---

I was a little bit surprised that my reducer was letting me modify the `state` argument, in a TypeScript project:

```ts
const reducer: Reducer<SomeStateType, SomeActionType> = (state, action) {
  switch (action.type) {
    case 'increment':
      state.count += 1;
      break;
    default:
      throw new Error();
  }

  return state;
}
```
**What is the expected behavior?**

I would expect to see:

```
TS2542: Index signature in type '<Readonly<SomeStateType>>' only permits reading.
```

**Suggested change**
Unless I'm not correctly understanding all of the use-cases, we should never be able to modify the `state` argument in the example above. What do you think about updating the type definition for `Reducer`?

```ts
type Reducer<S, A> = (prevState: <Readonly<S>>, action: A) => S;
```

I also tested that there is no negative implication of "double-wrapping" with `Readonly`, in the case where `S` is already defined as a `Readonly` type, i.e.

```ts
// @file some-reducer.ts
type S: <Readonly<SomeStateType>>;

// @file react/index.d.ts
type Reducer<S, A> = (prevState: <Readonly<S>>, action: A) => S;
```

More history: https://github.com/facebook/react/issues/15618

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
