### ISSUE TITLE
[@types/lodash] Property 'get' does not exist on type 'PrimitiveChain<undefined>

### ISSUE THREAD

**Issue by EugeneDraitsev** [DefinitelyTyped/DefinitelyTyped#35400]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aj-r
 
I have pretty simple chain expression:
```jsx
chain([{ type: 'axisX', dataType: 'Date' }])
  .find({ type: 'axisX' })
  .get('dataType')
  .value()
```

with `@types/lodash` **4.14.121** it works fine, but with **4.14.126** I get a type error:
```
Property 'get' does not exist on type 'PrimitiveChain<undefined> | ObjectChain<{ type: string; dataType: string; }>'.
  Property 'get' does not exist on type 'PrimitiveChain<undefined>'.
```

So it looks like typing issue, because `get` method will exist in this chain in any case (even if I pass null as chain argument)

**Comment by sandersn** [comment]
Notably, this only shows up with `--strict` on. I guess that this is *technically* correct, although if you have `--strict` on, undefined-ignoring chains contradicts the reason for turning it on in the first place.

I'll create a PR and see what people think.

**Comment by EugeneDraitsev** [comment]
@sandersn the problem here, that in strict mode you can use `!` to *skip* places where something can be undefined, but in this case you can't `!` and only one way to resolve this error -- use @ts-ignore?

Moreover error **is incorrect** here. It says:
```
Property 'get' does not exist on type 'PrimitiveChain<undefined> | ObjectChain<{ type: string; dataType: string; }>'.
  Property 'get' does not exist on type 'PrimitiveChain<undefined>'.
```

but property get **is exist** here in any case.
