### ISSUE TITLE
GraphNode interface inconsistent with documentation, dx/dy vs px/py.

### ISSUE THREAD

**Issue by jlennox** [DefinitelyTyped/DefinitelyTyped#3544]
I am new to d3 so may be misunderstanding.

The relevant API document is: https://github.com/mbostock/d3/wiki/Partition-Layout

> Several attributes are populated on each node:
> 
> parent - the parent node, or null for the root.
> children - the array of child nodes, or null for leaf nodes.
> value - the node value, as returned by the value accessor.
> depth - the depth of the node, starting at 0 for the root.
> x - the minimum x-coordinate of the node position.
> y - the minimum y-coordinate of the node position.
> dx - the x-extent of the node position.
> dy - the y-extent of the node position.

The GraphNode interface is:

```
export interface GraphNode  {
    id: number;
    index: number;
    name: string;
    px: number;
    py: number;
    size: number;
    weight: number;
    x: number;
    y: number;
    subindex: number;
    startAngle: number;
    endAngle: number;
    value: number;
    fixed: boolean;
    children: GraphNode[];
    _children: GraphNode[];
    parent: GraphNode;
    depth: number;
}
```

It appears px/py are used for the force layout (https://github.com/mbostock/d3/wiki/Force-Layout), which is indeed how it is in the interface GraphNodeForce.

Is px/py in GraphNode supposed to be dx/dy?

**Comment by jlennox** [comment]
I've made a pull request regarding this, https://github.com/borisyankov/DefinitelyTyped/pull/3545

Please reject if I am incorrect.

**Comment by tomwanzek** [comment]
As part of some legacy D3v3 issue clean-up, can this issue be please closed?

D3v4 has been released and supported with actively maintained definitions for several months now, so it would be great to have only current issues open for clarity.

Thanks in advance!

cc @gustavderdrache @andy-ms
