### ISSUE TITLE
With NodeJS v10 and TSC v3.4.5 @types/mongo throws error with this library

### ISSUE THREAD

**Issue by riginoommen** [DefinitelyTyped/DefinitelyTyped#35475]
Line Number
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1957e4cb6a5ed54ca310f015e5a61411bb713da7/types/mongodb/index.d.ts#L36

Error Log
```bash
riginoommen-mac:portal-server riginoommen$ rm -rf dist/ && grunt build && grunt serve
Running "newer:tslint:all" (newer) task
No newer files to process.

Running "copy:build" (copy) task
Created 3 directories, copied 5 files

Running "ts:build" (ts) task
Compiling...
Using tsc v3.4.5
node_modules/@types/mongodb/index.d.ts(36,10): error TS2305: Module '"tls"' has no exported member 'checkServerIdentity'.

>> 1 non-emit-preventing type warning
>> Error: tsc return code: 2
Warning: Task "ts:build" failed. Use --force to continue.

Aborted due to warnings.
Aborted due to warnings.
riginoommen-mac:portal-server riginoommen$ node -v
v10.15.3
```

**Comment by CaselIT** [comment]
Your issue seems strange.
Node v10 has that method
https://nodejs.org/docs/latest-v10.x/api/tls.html#tls_tls_checkserveridentity_hostname_cert

Maybe try to update the node typing?

**Comment by riginoommen** [comment]
@CaselIT Yes i updated the node typing and this got foxed thanks for suggesting

**Comment by niyazhussain** [comment]
@riginoommen  i  used npm install @types/node  -g still no luck .

**Comment by riginoommen** [comment]
@niyazhussain can you share the ```package.json``` here

**Comment by niyazhussain** [comment]
{
  "name": "SportyApi",
  "version": "0.1.0",
  "repository": {
    "type": "git",
  },
  "scripts": {
    "start": "npm run serve",
    "build": "npm run build-ts && npm run tslint  && npm run copy-static-assets",
    "serve": "node dist/server.js",
    "watch-node": "nodemon dist/server.js",
    "watch": "concurrently -k -p \"[{name}]\"  \"npm run watch-ts\" \"npm run watch-node\"",
    "test": "jest --forceExit --coverage --verbose",
    "build-ts": "tsc",
    "watch-ts": "tsc -w",
    "tslint": "tslint -c tslint.json -p tsconfig.json",
    "debug": "npm run build && npm run watch-debug",
    "serve-debug": "nodemon --inspect dist/server.js",
    "watch-debug": "concurrently -k -p \"[{name}]\" -n \"Sass,TypeScript,Node\" -c \"yellow.bold,cyan.bold,green.bold\"  \"npm run watch-ts\" \"npm run serve-debug\"",
    "prestartdev": "yarn install --production",
    "startdev": "pm2 start execute/process.prod.json",
    "stopdev": "pm2 stop execute/process.prod.json",
    "prestartprod": "yarn install --production",
    "startprod": "pm2 start execute/process.prod.json",
    "stopprod": "pm2 stop execute/process.prod.json",
    "copy-static-assets": "ts-node copyStaticAssets.ts"
  },
  "dependencies": {
    "@types/jsonwebtoken": "^7.2.8",
    "@types/nodemailer-mailgun-transport": "^1.3.3",
    "@types/superagent": "^3.8.6",
    "@types/uuid": "^3.4.3",
    "@types/winston": "^2.3.7",
    "async": "^2.6.0",
    "bcrypt-nodejs": "^0.0.3",
    "bcryptjs": "^2.4.3",
    "bluebird": "^3.5.1",
    "body-parser": "^1.18.2",
    "circleci": "^0.3.3",
    "compression": "^1.7.1",
    "connect-mongo": "^2.0.3",
    "cookie-parser": "^1.4.3",
    "cors": "^2.8.4",
    "dotenv": "^4.0.0",
    "errorhandler": "^1.5.0",
    "express": "^4.16.2",
    "express-flash": "0.0.2",
    "express-session": "^1.15.6",
    "express-validator": "^4.3.0",
    "fbgraph": "^1.4.1",
    "joi": "^13.1.2",
    "joi-phone-number": "^2.1.1",
    "jsonwebtoken": "^8.2.2",
    "lodash": "^4.17.4",
    "lusca": "^1.5.2",
    "mongoose": "^5.5.11",
    "morgan": "^1.9.0",
    "nodemailer": "^4.4.1",
    "nodemailer-mailgun-transport": "^1.4.0",
    "otp-generator": "^1.1.0",
    "otplib": "^10.0.1",
    "pug": "^2.0.0-rc.4",
    "superagent": "^4.1.0",
    "uuid": "^3.2.1",
    "winston": "^2.4.0"
  },
  "devDependencies": {
    "@types/async": "^2.0.45",
    "@types/bcrypt-nodejs": "0.0.30",
    "@types/bluebird": "^3.5.18",
    "@types/body-parser": "^1.16.8",
    "@types/compression": "0.0.33",
    "@types/connect-mongo": "0.0.42",
    "@types/cookie-parser": "^1.4.1",
    "@types/cors": "^2.8.3",
    "@types/dotenv": "^4.0.2",
    "@types/errorhandler": "0.0.32",
    "@types/express": "^4.0.35",
    "@types/express-session": "^1.15.6",
    "@types/jest": "^21.1.8",
    "@types/joi": "^13.0.5",
    "@types/jquery": "^3.2.17",
    "@types/lodash": "^4.14.91",
    "@types/lusca": "^1.5.0",
    "@types/method-override": "0.0.31",
    "@types/mongodb": "^3.0.0",
    "@types/mongoose": "^4.7.45",
    "@types/morgan": "^1.7.32",
    "@types/multer": "^1.3.6",
    "@types/node": "^7.0.50",
    "@types/nodemailer": "^4.6.0",
    "@types/passport-strategy": "",
    "@types/shelljs": "^0.7.7",
    "@types/supertest": "^2.0.4",
    "chai": "^4.1.2",
    "concurrently": "^3.5.1",
    "jest": "^21.2.1",
    "nodemon": "^1.13.0",
    "shelljs": "^0.7.7",
    "supertest": "^3.0.0",
    "ts-jest": "^21.2.4",
    "ts-node": "^4.0.2",
    "tslint": "^5.8.0",
    "typescript": "^2.6.2"
  },
  "jest": {
    "testEnvironment": "node"
  }
}

@riginoommen

**Comment by niyaza3** [comment]
@riginoommen i changed @types/node: 7.0.0 version to 10.10.0 mate  ,it is working charm.

**Comment by riginoommen** [comment]
> @riginoommen i changed @types/node: 7.0.0 version to 10.10.0 mate ,it is working charm.

Thats cool
