### ISSUE TITLE
Property 'relatedTarget' does not exist on type 'TriggeredEvent'

### ISSUE THREAD

**Issue by DaGLiMiOuX** [DefinitelyTyped/DefinitelyTyped#35482]
If you know how to fix the issue, make a pull request instead.

- [ x ] I tried using the `@types/xxxx` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu 
                   @borisyankov 
                   @choffmeister 
                   @Steve-Fenton 
                   @Diullei 
                   @tasoili 
                   @seanski 
                   @Guuz 
                   @ksummerlin 
                   @basarat 
                   @nwolverson 
                   @derekcicerone 
                   @AndrewGaspar 
                   @seikichi 
                   @benjaminjackman 
                   @JoshStrobl 
                   @johnnyreilly 
                   @DickvdBrink 
                   @King2500 
                   @terrymun 

After including `@types/jquery`, I still getting this error when compiling angular:
```
ERROR in src/app/admin/xxx/a.component.ts(98,21): error TS2551: Property 'relatedTarget' does not exist on type 'TriggeredEvent<Document, undefined, any, any>'. Did you mean 'delegateTarget'?
```
The piece of code is like this:
```
$(document).on('mouseleave.action', '.element', function(event) {
  var e = event.toElement || event.relatedTarget;
  // ... do some stuff
});
```
Using it like arrow function (`(event) => { ... }`) instead of `function` throws the same error. Probably a bug or a missing property.

Br,
D.

**Comment by leonard-thieu** [comment]
For namespaced-DOM events, you'll need to declare a type mapping.

```typescript
declare namespace JQuery {
    interface TypeToTriggeredEventMap<
        TDelegateTarget,
        TData,
        TCurrentTarget,
        TTarget
    > {
        'mouseleave.action': MouseLeaveEvent<TDelegateTarget, TData, TCurrentTarget, TTarget>;
    }
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
