### ISSUE TITLE
Problem importing big.js in NodeJS - "Cannot find external module"

### ISSUE THREAD

**Issue by aelr** [DefinitelyTyped/DefinitelyTyped#3548]
I've installed big.js via `npm` and the `d.ts` file via`tsd`. I am attempting to import it in NodeJS via:
`import Big = require('big.js')`, as I have done with other modules (e.g., `import _ = require('lodash')`).

However, I receive the following error upon compilation: 
`error TS2307: Cannot find external module 'big.js'`

In case it matters, I'm using TypeScript 1.3.  Also, I am using the typings reference in the file:
`/// <reference path="../typings/tsd.d.ts" />`

**Comment by vvakame** [comment]
@aelr https://github.com/borisyankov/DefinitelyTyped/blob/master/big.js/big.js.d.ts
big.js.d.ts does not export by external module syntax.
please send PR!

**Comment by nycdotnet** [comment]
@vvakame big.js is written in the UMD style - meaning it can be used in AMD/CommonJS or globally as an internal module.  Is there a good way to describe a UMD module in a d.ts?

**Comment by aelr** [comment]
[Looking more into d.ts development](http://www.typescriptlang.org/Handbook#writing-dts-files), the current definition was made using the "decomposed class" style, which comes with some tradeoffs.  On one hand, it allows usage of `Big` without the `new` keyword and can be set up to work with CommonJS with only a small change to the end of the current definition file:

```typescript
declare module "big.js" {
    var Big: BigJsLibrary.BigJS;
    export = Big;
}
```

On the other, when writing type declarations, the [correct type](http://stackoverflow.com/a/25747024/3599355) is `BigJsLibrary.BigJS`:

```typescript
var foo: BigJsLibrary.BigJS;
```

Using the standard class declaration style [prevents any usage of the class as a function](scriptlang.org/Handbook#interfaces).  Since I'm not interested in using `Big` without `new` and want to use `Big` as the type name, I have reworked the `d.ts` file to use the standard class definition.  I'm assuming that my changes aren't wanted here, as it will break applications that are currently using this file (both by changing the type declaration required and disabling usage without `new`).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
