### ISSUE TITLE
[@types/styled-components] extending redux-form Field error

### ISSUE THREAD

**Issue by rlesniak** [DefinitelyTyped/DefinitelyTyped#35515]
Nothing more to say, just take a look on sandbox example and its TS error: (Comp.tsx file)
https://codesandbox.io/s/elegant-haslett-v9mlk

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
 
- Authors: @Igorbek @Igmat @lavoaster @Jessidhia @jkillian @eps1lon @flavordaaave

**Comment by eps1lon** [comment]
We had to revert support for union props in #34499. Version 4.1.11 and 4.1.12 are the only versions supporting union props. We may want to revisit support for union props in TypeScript 3.5

**Comment by rlesniak** [comment]
Thank you for info.

**Comment by rlesniak** [comment]
So newest version of types will work with TS 3.5?

**Comment by eps1lon** [comment]
I don't know. Maybe the performance will stay as bad. There's not much interest in union props as of https://github.com/microsoft/TypeScript/issues/28339#issuecomment-478781328

**Comment by taylon** [comment]
Just tested a codebase that extends styles pretty heavily and was failing with 4.1.15 + Typescript 3.3 and was suffering with the slow compilation times with 4.1.15 + Typescript 3.4.

After updating to Typescript 3.5 RC (https://devblogs.microsoft.com/typescript/announcing-typescript-3-5-rc/) and using 4.1.15 it is working like a charm 👍
