### ISSUE TITLE
[@types/node] v11 & v12 are Missing querystring definitions

### ISSUE THREAD

**Issue by methodbox** [DefinitelyTyped/DefinitelyTyped#35579]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....
@Microsoft
@jkomyno
@alvis
@brunoscheufler

I believe `encode` and `decode` are aliases for `stringify` and `parse`, respectively. They exist in the 10.x node API but are not in the type definitions found here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v10/querystring.d.ts

You can see this in the CLI:
```bash
$> node --version
v10.15.0
$> node
node
> querystring
{ unescapeBuffer: [Function: unescapeBuffer],
  unescape: [Function: qsUnescape],
  escape: [Function: qsEscape],
  stringify: [Function: stringify],
  encode: [Function: stringify],
  parse: [Function: parse],
  decode: [Function: parse] }
> querystring.decode
[Function: parse]
> querystring.encode
[Function: stringify]
> querystring.decode('name=bob&age=10&favFood=pizza')
[Object: null prototype] { name: 'bob', age: '10', favFood: 'pizza' }
> querystring.encode({ name: 'bob', age: '10', favFood: 'pizza' })
'name=bob&age=10&favFood=pizza'
```
In a quick test the solution seems to be this, which I can file a PR for if necessary:

```ts
declare module 'querystring' {
  interface StringifyOptions {
    encodeURIComponent?: (str: string) => string;
  }

  interface ParseOptions {
    maxKeys?: number;
    decodeURIComponent?: (str: string) => string;
  }

  interface ParsedUrlQuery {
    [key: string]: string | string[];
  }

  interface ParsedUrlQueryInput {
    [key: string]: // The value type here is a "poor man's `unknown`". When these types support TypeScript
    // 3.0+, we can replace this with `unknown`.
    {} | null | undefined;
  }

  function stringify(obj?: ParsedUrlQueryInput, sep?: string, eq?: string, options?: StringifyOptions): string;
  //  new
  function encode(obj?: ParsedUrlQueryInput, sep?: string, eq?: string, options?: StringifyOptions): string;
  function parse(str: string, sep?: string, eq?: string, options?: ParseOptions): ParsedUrlQuery;
  //  new
  function decode(str: string, sep?: string, eq?: string, options?: ParseOptions): ParsedUrlQuery;
  function escape(str: string): string;
  function unescape(str: string): string;
}
```

**Comment by RMHonor** [comment]
If they are indeed aliases, would it not be safer to use `typeof` for a single source of truth?

```typescript
function stringify(obj?: ParsedUrlQueryInput, sep?: string, eq?: string, options?: StringifyOptions): string;
  //  new
  const encode: typeof stringify;
  function parse(str: string, sep?: string, eq?: string, options?: ParseOptions): ParsedUrlQuery;
  //  new
  const decode: typeof parse;
```

I'm not sure if the use of `const` here rather than `function` would cause issues

**Comment by methodbox** [comment]
@RMHonor

I like that, good call.

Alternatively, the functions could be refactored and the aliases be made actual type aliases; I’m not sure which is the best approach or if either has any pitfalls.

Any ideas on this?

**Comment by RMHonor** [comment]
@methodbox Honestly couldn't say, but my immediate thought is to follow the pattern of the JS implementation, in that you define `stringify` and `parse`, and reference them. Someone with a better understand of best practices might know better than me though!

**Comment by methodbox** [comment]
> @RMHonor
> 
> I like that, good call. `const` would not cause issues; it can even still be aliased.
> 
> Alternatively, the functions could be refactored and the aliases be made actual type aliases; I’m not sure which is the best approach or if either has any pitfalls.
> 
> Any ideas on thi

> If they are indeed aliases, would it not be safer to use `typeof` for a single source of truth?
> 
> ```ts
> function stringify(obj?: ParsedUrlQueryInput, sep?: string, eq?: string, options?: StringifyOptions): string;
> //  new
> const encode: typeof stringify;
> function parse(str: string, sep?: string, eq?: string, options?: ParseOptions): ParsedUrlQuery;
> //  new
> const decode: typeof parse;
> ```
> 
> I'm not sure if the use of `const` here rather than `function` would cause issues

Actually, I've tested this a couple of ways and I think my original suggestion is best.

If for no other reason than:

1). It's stated explicitly what the definition is for that method.
2). Viewing the type in, for example, VS Code, is too ambiguous; it references another function and it's not a type of the `function stringify`; it's an actual function which is the same shape. 

There's probably a less verbose way of describing it, but there's nothing wrong with verbosity in types.

I think I'll place a PR for this.

**Comment by methodbox** [comment]
So it looks like these made it into 10, but officially the Node docs don't show them until v11.

There isn't an @types for 12 yet, but I'm going to put in the PR with this added to the types for v11; if someone wanted to use them with v10, it looks like they were proposed but not official until 11 so I guess one could just use those type defs as needed or define them manually. 

They are defined in the docs as _aliases_ here: https://nodejs.org/docs/latest-v11.x/api/querystring.html#querystring_querystring_encode

**Comment by RMHonor** [comment]
> So it looks like these made it into 10, but officially the Node docs don't show them until v11.
> 
> There isn't an @types for 12 yet, but I'm going to put in the PR with this added to the types for v11; if someone wanted to use them with v10, it looks like they were proposed but not official until 11 so I guess one could just use those type defs as needed or define them manually.
> 
> They are defined in the docs as _aliases_ here: https://nodejs.org/docs/latest-v11.x/api/querystring.html#querystring_querystring_encode

v12 types are there, they're at the root of the node dir (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node), older versions are those in the specific dirs.

**Comment by methodbox** [comment]
Here's the PR. I added it in for v12 too, as they are both still function aliases in the current version.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35694

**Comment by methodbox** [comment]
Closing as this has been merged: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35694 which closes this issue.

@RMHonor We ended up using  your fix, btw, as it's better overall and achieves the definition intellisense I thought would be missing, so thanks for the assist!

**Comment by RMHonor** [comment]
Great to hear! Tooling seems to have got a lot better on this, as I had the same concerns as you, glad to know it works cleanly.
