### ISSUE TITLE
[jss] feature request: font-face types

### ISSUE THREAD

**Issue by trusktr** [DefinitelyTyped/DefinitelyTyped#35614]
@appsforartists, @kof, @pelotom, @eps1lon

A typing for font face rules could be convenient.

**Comment by eps1lon** [comment]
Please include code that currently fails the type checker and a link to the documentation for that runtime behavior.

**Comment by trusktr** [comment]
Here's a link to the `@font-face` JSS format: https://cssinjs.org/jss-syntax/?v=v10.0.0-alpha.16#font-face

There's no occurrence of `font-face` or `fontFace` in the `css.d.ts` file, so I guess it is missing.

In practice, I'm using `@material-ui/core` (http://material-ui.com) to apply the styles, but in that case all rules are typed as `CSSProperties`, which does include things like `fontFamily`, etc.

Where it trips is when I try to pass an array, so I have to cast it to trick it. For example:

```ts
    // avenirFont is an array of font rules, as per JSS docs.
    '@global': {
      '@font-face': ([...avenirFont] as unknown) as CSSProperties,
    },
```

What I've done in my local code to give the font faces a type is

```ts
export type FontFaceRule = {
  fontFamily: string
  src: string
  fallbacks: { src: string }[]
  fontStyle: string
  fontWeight: 0
}
```

and I'm using `FontFaceRule[]` as the type of `avenirFont` to aid in that part, before finally casting it.

Material-ui is typing `CSSProperties` like this:

```ts
import * as CSS from 'csstype';
import * as JSS from 'jss';

export interface CSSProperties extends CSS.Properties<number | string> {
  // Allow pseudo selectors and media queries
  [k: string]: CSS.Properties<number | string>[keyof CSS.Properties] | CSSProperties;
}

/**
 * This is basically the API of JSS. It defines a Map<string, CSS>,
 * where
 *
 * - the `keys` are the class (names) that will be created
 * - the `values` are objects that represent CSS rules (`React.CSSProperties`).
 */
export type StyleRules<ClassKey extends string = string> = Record<ClassKey, CSSProperties>;

export type StyleRulesCallback<ClassKey extends string = string> = (
  theme: Theme,
) => StyleRules<ClassKey>;
```

Seems like material-ui is making some custom styles on top of `csstype` and `jss`.

It seems that if the `@font-face` format is specified by JSS, maybe the typings for that should be in `@types/jss`.

**Comment by eps1lon** [comment]
I'm asking because I need some code to test this on. It's not apparent to me how this code would look in isolation.

**Comment by appsforartists** [comment]
I believe @kof and company are maintaining a d.ts in the primary repo now.  Should we even still have an `@types/jss`?
