### ISSUE TITLE
[@types/lodash] orderBy typing in chain looks broken

### ISSUE THREAD

**Issue by EugeneDraitsev** [DefinitelyTyped/DefinitelyTyped#35623]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aj-r @sandersn
 
I have this expression (and ts with strict mode):
```jsx
chain([{ id: 6 }, { id: 7 }, { id: 63 }, { id: 4 }, { id: 5 }])
    .map(x => ({ value: x.id }))
    .orderBy('value', 'desc')
    .value()
```

with `@types/lodash` **4.14.121** it works fine, but with **4.14.130** I get a type error:
```
Argument of type '"value"' is not assignable to parameter of type 'ListIterator<{ value: number; }, unknown> | ReadonlyArray<ListIterator<{ value: number; }, unknown>> | undefined'.

```

In this situation property `value` will exist in Array and this error have no any sense. Moreover it can  be workarounded only with `'value' as any`.

**Comment by aj-r** [comment]
@sandersn Looks like `CollectionChain<T>` is missing an overload that accepts `ListIteratee`.
