### ISSUE TITLE
[@types/lodash] Property 'includes' does not exist on type 'StringChain'.

### ISSUE THREAD

**Issue by EugeneDraitsev** [DefinitelyTyped/DefinitelyTyped#35627]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aj-r @sandersn
 
One more similar to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35400 and https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35625 issue (ts is in strict mode):

```jsx
    chain('test').split('_').toLower().includes('test').value()
```

with `@types/lodash` **4.14.121** it works fine, but with **4.14.130** I get a type error:
```
 Property 'includes' does not exist on type 'StringChain'.
```
`includes` function exists here.

**Comment by aj-r** [comment]
@sandersn `includes` should exist on `StringChain`. Maybe it only exists for `CollectionChain` right now?

**Comment by sandersn** [comment]
Yeah, I translated the definition from the static version, which looks like isn't *intended* to work for strings, but actually does. I'll put a fix up shortly.
