### ISSUE TITLE
[@types/passport/index.d.ts] namespace passport, interface AuthenticateOptions add new line "show?: string;"

### ISSUE THREAD

**Issue by Nadim-Ritter** [DefinitelyTyped/DefinitelyTyped#35657]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi @enaeseth @theigor @tlaziuk @danielpza @kstiehl 

I am using the IBM Cloud APP ID (https://cloud.ibm.com/docs/services/appid?topic=appid-login-widget#widget-display-nodejs) in my project to have a user management. I use the "AuthenticationOptions" interface in "/types/passport/index.d.ts" to pass the properties. I need to use the "show" properie to change the password, but this line is missing. If add "show?string;" to the interface, the code works. Can you add this to the module? Thanks

`declare namespace passport {  
    interface AuthenticateOptions {  
        authInfo?: boolean;  
        assignProperty?: string;  
        failureFlash?: string | boolean;  
        failureMessage?: boolean | string;  
        failureRedirect?: string;  
        failWithError?: boolean;  
        session?: boolean;  
        scope?: string | string[];  
        successFlash?: string | boolean;  
        successMessage?: boolean | string;  
        successRedirect?: string;  
        successReturnToOrRedirect?: string;  
        state?: string;  
        pauseStream?: boolean;  
        userProperty?: string;  
        passReqToCallback?: boolean;  
        prompt?: string;  
        //i need this line to be added
        show?: string;  
    }`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
