### ISSUE TITLE
[@types/chrome] HighlightInfo incorrect property name

### ISSUE THREAD

**Issue by opus1269** [DefinitelyTyped/DefinitelyTyped#35689]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @couven92 @otiai10

If you do not mention the authors the issue will be ignored.

The `tabs` property of `HighlightInfo` should be `tabIds`
https://developer.chrome.com/extensions/tabs#event-onHighlighted

**Comment by couven92** [comment]
@opus1269 I'll start a PR, will link to it when it's ready. Won't be long

**Comment by couven92** [comment]
@opus1269 Hmm... this is interesting, according to the source `HighlightInfo` has the correct `tabIds` property as shown here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cdc4f7e325af0d49010925eb65dac4882d128ed4/types/chrome/index.d.ts#L7270-L7273

**Comment by couven92** [comment]
@opus1269 OH! I see what happened. So `HighlightInfo` is correct. It is the shape used for `chrome.tabs.highlight()` and it uses the `tabs` property. The `onHighlighted` event that you are linking to uses `TabHighlightInfo` which uses `tabIds`. Easy to get confused here, sorry.

**Comment by couven92** [comment]
So @opus1269 please decide whether this is still an issue. I can offer to rename `TabHighlightInfo` to something like `TabHighlightedEventInfo` if that helps to tell these two very similar types apart.

**Comment by opus1269** [comment]
Ah, I see. Using TabHighlightInfo fixed the issue.  No need to change the type name. Maybe add comments about what they refer too?  If you don't think that is a good idea, go ahead and close the issue.

Thanks.

**Comment by couven92** [comment]
Yeah, problem with these is, that the names should be considered opaque. They are just inlined in Google's documentation, so the names aren't actually real. So almost all types in chrome that do not have any doc-comments on them (the type itself, not the properties) is most likely an inlined type where we just came up with a random name, because we had to call it something.

**Comment by couven92** [comment]
And @opus1269 I cannot close your issue, only you (the author) or a repo admin can do that :)
