### ISSUE TITLE
[@types/express-handlebars] Fix hbs signature

### ISSUE THREAD

**Issue by Silver96** [DefinitelyTyped/DefinitelyTyped#35687]
In ![d0912389d07ae28e694ff5763133f122c266777a](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d0912389d07ae28e694ff5763133f122c266777a) the definition for `Express.engine`'s second argument changed from `Function` to a more specific signature, while the `hbs` function still has the `Function` type. This leads to a typescript error due to the mismatching types.

------------------------------------------------------------------------------------------------------------
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/express-handlebars` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @stpettersens @yhaskell

If you do not mention the authors the issue will be ignored.

**Comment by dcbartlett** [comment]
This is still an issue.

![image](https://user-images.githubusercontent.com/1077050/67575326-53d96300-f70a-11e9-81cc-9677bb854dde.png)

Will see if i can make a PR for this.
