### ISSUE TITLE
[@types/eslint] Type `Node` should have property `parent`

### ISSUE THREAD

**Issue by golopot** [DefinitelyTyped/DefinitelyTyped#35701]
Currently the type `Node` is imported from `@types/estree`. But that type lacks the property `parent`, which is added by eslint. Since `node.parent` is frequently used. This is a high impact bug.

The only solution I find is to vendor the a modified copy of `@types/estree` in `@types/eslint`.
 
@pmdartus @j-f1 @saadq @mysticatea

**Comment by 43081j** [comment]
Could you not just have an extended `Node` (`ESLintNode` or some such thing) which the eslint types accept? (and make it inherit `Node`)

**Comment by OliverJAsh** [comment]
Done in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48615
