### ISSUE TITLE
Babel Plugin Relay Macro TypeScript

### ISSUE THREAD

**Issue by jedmao** [DefinitelyTyped/DefinitelyTyped#35707]
Hoping this will help TypeScript developers.

```bash
npm install --save react-relay babel-plugin-relay
npm install --save-dev @types/react-relay
```

```ts
// src/react-app-env.d.ts
declare module 'babel-plugin-relay/macro' {
	export * from 'react-relay'
}
```

```tsx
// src/components/Foo.tsx
import { graphql, QueryRenderer } from 'babel-plugin-relay/macro'
```

**Comment by pjvds** [comment]
you saved my day!

**Comment by JacekKosciesza** [comment]
Didn't work for me, got error:
```
ERROR:
Parse error: SyntaxError: Only declares and type imports are allowed inside declare module (6:2) in "react-app-env.d.ts"
```

**Comment by dzucconi** [comment]
For me, had to declare the default export:

```ts
import graphql from 'babel-plugin-relay/macro'
```

```ts
declare module "babel-plugin-relay/macro" {
  export { graphql as default } from "react-relay";
}
```

**Comment by jagadeesh93** [comment]
@jedmao I had the same bug .I applied this solution it worked fine for me . Could you please explain what is happening behind the scene ? . why it is throwing an error if i directly import from react-relay by skipping the babel-plugin-relay/macro thing

**Comment by jedmao** [comment]
It’s been too long, so I don’t remember exactly the issue I was facing, but it looks like I was just trying to make sure that there were no type collisions between the two libraries for using different types or different versions of types for graphql. In my code, I’m explaining that the graphql export from the macro is actually the same type information as the graphql export from react-relay.

**Comment by walteraandrade** [comment]
I love you.

**Comment by lai-caju** [comment]
> For me, had to declare the default export:
> 
> ```ts
> import graphql from 'babel-plugin-relay/macro'
> ```
> 
> ```ts
> declare module "babel-plugin-relay/macro" {
>   export { graphql as default } from "react-relay";
> }
> ```

Where should I place the declare file?

**Comment by walteraandrade** [comment]
Inside your src folder.

![image](https://user-images.githubusercontent.com/62224146/104464693-fd1bab80-5591-11eb-8fd8-e8aa094401b0.png)

**Comment by lai-caju** [comment]
> Inside your src folder.
> 
> ![image](https://user-images.githubusercontent.com/62224146/104464807-1b81a700-5592-11eb-9458-438ecf19c424.png)

Thanks! it works!

**Comment by tobias-tengler** [comment]
At the moment I always have to type/copy the macro import by hand, since intellisense is not working correctly for me:
![image](https://user-images.githubusercontent.com/45513122/115106580-e8bac680-9f65-11eb-9e0b-6aaf2745a819.png)
Has anyone found a solution for this? In a perfect world I could just write `graphql`, VS Code suggests me "import graphql from 'babel-plugin-relay/macro'" and I can hit that - done.
I also really don't want to eject my create-reacp-app if possible...

**Comment by thetrompf** [comment]
@tobias-tengler The solution suggested in the reply above your comment works fine for me.

Just add the following to `src/react-app-env.d.ts`.

```typescript

declare module 'babel-plugin-relay/macro' {
	export { graphql } from 'react-relay';
}
```
