### ISSUE TITLE
Support lodash 3.x

### ISSUE THREAD

**Issue by nidico** [DefinitelyTyped/DefinitelyTyped#3573]
Lodash 3.0 [is out](https://github.com/lodash/lodash/releases/tag/3.0.0). It contains a lot of new and useful functions and introduces breaking API changes - see [full changelog](https://github.com/lodash/lodash/wiki/Changelog#v300).

**Comment by demisx** [comment]
+1. Get a bunch of warnings for methods that exist in 3.7, but not in 2.x definition files.

**Comment by rankida** [comment]
+1

**Comment by robertjmason** [comment]
I might be stepping out on a limb here, but it sure would be nice if MS could pick a few libraries (such as this one, the [single most depended-upon one in npm](https://www.npmjs.com/browse/depended) with 600,000+ downloads per day) and make official definitions for them so we don't wind up with minefield d.ts files that have [a handful of defs from new versions](https://github.com/borisyankov/DefinitelyTyped/commit/2127b2f1e438efa61f3d087079a5f17385a38e4c) mixed in with [invalid defs subjected to breaking changes](https://github.com/lodash/lodash/wiki/Changelog#jan-26-2015--diff--docs).

**Comment by ichpuchtli** [comment]
+1
