### ISSUE TITLE
@types/lodash slow compilation times with  4.14.125 and up(tried 125 and 132)

### ISSUE THREAD

**Issue by kelly-tock** [DefinitelyTyped/DefinitelyTyped#35750]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/lodash` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sandersn 

If you do not mention the authors the issue will be ignored.

when I downgrade to 4.14.124, the compilation time returns back to normal. 125 was my projects upgrade that started slowing the compilation time down. I tried 132 and it is exhibiting the similar issues. 

TS 3.4.5
compiling with webpack and `babel-preset-typescript`, and linting with typescript-eslint, all latest versions. 

maybe TS 3.5 will fix it?

**Comment by kelly-tock** [comment]
time went from around 60 seconds to 5 minutes.

**Comment by kelly-tock** [comment]
3.5rc and 132 are also showing this behavior in slowdown.

**Comment by sandersn** [comment]
Oops, I read your posts in the wrong order, @kelly-tock. I won't re-post the text I wrote on the other bug, but sorry for advising you to open a bug you had already opened.

You might still check 3.3 to see whether it's also slow. As for usage patterns, curry, flow and partial now use overloads + conditional types, which might be a problem. Do you have lots of currying in your code?

**Comment by kelly-tock** [comment]
We have a fair amount of partial for sure. I can try 3.3 as well if you want me to.

**Comment by kelly-tock** [comment]
3.3 with latest types for lodash is slow as well. my project is pretty large, so refactoring out of _.partial is not a great option for us ATM. is there any other way to fix this? will the final release of 3.5 TS be any better?

**Comment by sandersn** [comment]
I don't think any lodash-affecting efficiency fixes have gone in since the RC.

Can you confirm that it's `_.chain(...).partial` or `_(...).partial` that's causing the problem? Try replacing some of those method calls with the non-chaining `_.partial(...)` calls and see if compilation gets faster.

If you can compile with just `tsc`, try adding the `--diagnostics` flag to get performance data. (time, memory and type count being the most important)

**Comment by kelly-tock** [comment]
we are compiling with @babel/typescript, only using tsc for type checking.  our main usage ATM is 

```js
_.flow(
_.partialRight(...),
_.partialRight(..),
)

i'll refactor one of our larger ones and see if that helps it out. 

our app is quite large(65k lines of code at least).

**Comment by sandersn** [comment]
4.14.125 only changed the chaining methods, so I would not expect to see a difference unless the code is `_(x).partialRight(y)` instead of `_.partialRight(x, y)`

**Comment by kelly-tock** [comment]
so what should I search for in my project then?  _.partial and _.partialRight?  _.flow?

**Comment by sandersn** [comment]
I think you should specify not `_`, something like this regex: `/[^_]\.(partial|flow)/`

**Comment by kelly-tock** [comment]
we just upgraded to typescript 3.5.1 and I tried out the latest types and performance was back to normal levels for the most part.  I refactored a few spots where we were doing _.flow(_.partial(..., _.partialRight()), _.partial(..., _.partialRight()), _.partial(..., _.partialRight())) and it seems to have helped.  will keep an eye on this.
