### ISSUE TITLE
@types/got has no default export

### ISSUE THREAD

**Issue by jsmiith** [DefinitelyTyped/DefinitelyTyped#35782]
- [x] I tried using the `@types/got` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @BendingBender, @LinusU, @ikokostya, @stijnvn, @wingsbob, @ryanwilsonperkin 

When I import got after installing these types, it is telling me that they do not have a default export, so I, therefore, can not use them.

**Comment by wingsbob** [comment]
https://github.com/sindresorhus/got/blob/v9.6.0/source/index.js#L60

Doesn't have a default export. Use `import * as got from 'got'`

**Comment by LinusU** [comment]
`import got = require('got')` should work as well, I think that's the preferred way to import Node.js (CommonJS) packages

**Comment by mruffieux** [comment]
It's also not packed with the beforeError hook and it seems that hooks are basically not typed correctly...
