### ISSUE TITLE
[react-intl] v3 (forwardRef, etc.)

### ISSUE THREAD

**Issue by antoinerousseau** [DefinitelyTyped/DefinitelyTyped#35812]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bgrieder @cdroulers @gyzerok @tillwolff @LKay @bhouser @kristerkari @formatlos @lukyth @obedm503 @anion155

----
The types need an upgrade for react-intl v3

https://github.com/formatjs/react-intl/wiki/Upgrade-Guide#300

- `injectIntl(MyComponent, { withRef: true })` becomes 
`injectIntl(MyComponent, { forwardRef: true })`
- add `useIntl` hook

**Comment by leoyli** [comment]
New type definition will needed for `useIntl` hook too.

**Comment by leoyli** [comment]
FYI, for this hook. Using augmentation, all we need is simply as:

```js
import { InjectedIntlProps } from 'react-intl';

declare module 'react-intl' {
  type intl = InjectedIntlProps['intl'];
  export function useIntl(): [InjectedIntlProps['intl']['formatMessage'], intl] {}
}
```

**Comment by Fenopiu** [comment]
> ```ts
> 
>   type intl = InjectedIntlProps['intl'];
> ```

I've needed to change your solution changing the last line from:
`export function useIntl(): [InjectedIntlProps['intl']['formatMessage'], intl] {}`
to:
`export function useIntl(): [InjectedIntlProps['intl']['formatMessage'], intl];`

Your solution give me this error: 
A function whose declared type is neither 'void' nor 'any' must return a value.ts(2355).

**Comment by leoyli** [comment]
@Fenopiu, I was actually using type augmentation by provide function overload, so it kind of work in my setup.  And as for the latest v3 beta.7, the API have slightly changed (but finalized), here is something you may want to use instead:

```
import { InjectedIntlProps } from 'react-intl';

declare module 'react-intl' {
  type intl = InjectedIntlProps['intl'];
  export function useIntl(): intl {}
}
```

**Comment by Fenopiu** [comment]
It works even putting the definition in the namespace declaration:
node_modules/@types/react-intl/index.d.ts
`declare namespace ReactIntl {
    ...
    type intl = InjectedIntlProps['intl'];
    function useIntl(): [InjectedIntlProps['intl']['formatMessage'], intl];
}`



Compiling I receive this error:

> Attempted import error: 'addLocaleData' is not exported from 'react-intl'.

The code it breaks is:
`import { addLocaleData, IntlProvider, Locale } from "react-intl";`

In the d.ts it is there and exportable (like injectIntl)... so it may be a non updated type change or maybe a bug / change in react-intl to discuss there?

**Comment by Fenopiu** [comment]
[addLocaleData v3 #1307](https://github.com/formatjs/react-intl/issues/1307)
So it have to be modified the d.ts file too.

**Comment by leoyli** [comment]
For people holding their eyes on this issue, the official package are now fully typed, which means we will have TS typing as the 1st class support from the package itself in v3.  No more outdated DT 🎉 

Check out their [upgrade guide](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#typescript-support).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
