### ISSUE TITLE
Property 'positions' does not exist on type 'typeof DrawerLayoutAndroid'

### ISSUE THREAD

**Issue by chj-damon** [DefinitelyTyped/DefinitelyTyped#35852]
If you know how to fix the issue, make a pull request instead.

- [*] I tried using the `@types/react-native` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [*] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @huhuanming @iRoachie @Skn0tt @timwangdev @kamal @swissmanu 

If you do not mention the authors the issue will be ignored.

**Comment by iRoachie** [comment]
There's no `positions` prop on Drawer? https://facebook.github.io/react-native/docs/drawerlayoutandroid#props

**Comment by chj-damon** [comment]
as you can see in the demo code:
`drawerPosition={DrawerLayoutAndroid.positions.Left}`
But actually `positions` does not exist on Drawer.

**Comment by alloy** [comment]
I’m a little unclear on what needs to happen here. @chj-damon, could you make a PR instead with what you need?
