### ISSUE TITLE
@types/mongoose any Types of property 'validate' are incompatible.

### ISSUE THREAD

**Issue by mohsen89z** [DefinitelyTyped/DefinitelyTyped#35860]
I've been using this style of validation for my mongoose schema:
![image](https://user-images.githubusercontent.com/8802395/58705818-f3433580-83b8-11e9-8832-3aa378a317d0.png)
[Mongoose Doc](https://mongoosejs.com/docs/validation.html#custom-validators)

But I get an error message stating `any Types of property 'validate' are incompatible. 'message' does not exist in type 'RegExp | [RegExp, string] | ValidateOpts | ...lots more)[]'.`

Please **test** your code before publishing it!

**Comment by TizioFittizio** [comment]
Same for me, any update on this?

**Comment by Imballinst** [comment]
I think `@types/mongoose` isn't compatible (yet) for Mongoose v5, isn't it?

Folder https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mongoose only has v3 and v4. The link that you gave is Mongoose v5. That might be the reason.

**Comment by mohsen89z** [comment]
@Alorel I think you're the owner?

**Comment by Alorel** [comment]
There are many contributors to mongoose typings: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L3

I do not have the capacity to make any changes at the moment.

**Comment by jaydp17** [comment]
Maybe it's a TypeScript issue, because the latest version of types (i.e. v5.5.6) works on TypeScript v3.4.5, but doesn't work on TypeScript v3.5.1.

**Comment by renso3x** [comment]
I encountered this issue as well.

**Comment by dbeig** [comment]
someone?

**Comment by ajs11174** [comment]
Here is how I fixed the issue on my end. 

I created a custom typings file for my project and added this to it.
````typescript
declare module "mongoose" {
    namespace SchemaTypeOpts {
        interface ValidateOpts {
            validator?: RegExp | ValidateFn<any> | undefined;
            message?: IMessageFn | string;
            type?: string;
            [key: string]: any;
        }
    }
}

interface IMessageFn {
    (properties: {[key: string]: any}): string;
}
````

Here is an example of my Schema.

```` typescript
const userSchema = new Schema({
	email: {
		type: String,
		validate: {
			validator: function(v: string) {
				return false;
			},
			message: 'It now works like it should',
			'you can also set': 'other properties'
		},
		required: [true, 'Email required']
	},
})
````

And here is what the validation error looks like. Notice how the other properties come through. This might help if you want some other context along with the error message.

```` typescript
MongooseError [ValidatorError]: It now works like it should
    at new ValidatorError (/root/workspace/my-project/node_modules/mongoose/lib/error/validator.js:29:11)
    at validate (/root/workspace/my-project/node_modules/mongoose/lib/schematype.js:978:13)
    at /root/workspace/my-project/node_modules/mongoose/lib/schematype.js:1031:11
    at Array.forEach (<anonymous>)
    at SchemaString.SchemaType.doValidate (/root/workspace/my-project/node_modules/mongoose/lib/schematype.js:987:14)
    at /root/workspace/my-project/node_modules/mongoose/lib/document.js:2102:9
    at processTicksAndRejections (internal/process/task_queues.js:82:9) {
  message: 'It now works like it should',
  name: 'ValidatorError',
  properties: {
    validator: [Function: validator],
    message: 'It now works like it should',
    'you can also set': 'other properties',
    type: 'user defined',
    path: 'email',
    value: 'mongoose@types.github.com'
  },
  kind: 'user defined',
  path: 'email',
  value: 'mongoose@types.github.com',
  reason: undefined,
  [Symbol(mongoose:validatorError)]: true
}
````

**Comment by Alex-Levacher** [comment]
After being stuck a moment I realized I had to use `msg` and not `message`.
```js
        validate: {
            validator: yourAsyncValidator,
            msg: "Your message",
        },
```
That's understandable from the fact that the `validate` option is waiting for an `AsyncPromiseValidationOpts` which is defined as:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L1219
And as you can see `AsyncPromiseValidationOpts` don't have any `message` property **BUT** `AsyncPromiseValidationOpts`extends `ValidateOptsBase` wich have a `msg` property
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L1198
Suggest a PR to add `message` property to `AsyncPromiseValidationOpts` could solve this issue as well.

**Comment by 3mard** [comment]
Any update on this ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
