### ISSUE TITLE
Does not include UIManager.dispatchViewManagerCommand nor UIManager.getViewManagerConfig

### ISSUE THREAD

**Issue by nschild** [DefinitelyTyped/DefinitelyTyped#35872]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/react-native@0.57.60` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @huhuanming @iRoachie @skn0tt @timwangdev @kamal @alexdunne @swissmanu @bm-software @tkrotoff @a-tarasyuk @mvdam @esemesek @mrnickel @souvik-ghosh @nossbigg @saranshkataria @franzmoro @tykus160 @jakebloom @ceyhun

If you do not mention the authors the issue will be ignored.

----------------------------------

I am cleaning up some of the warnings in my app and came across this item: 
<img width="694" alt="Screen Shot 2019-05-31 at 2 23 23 PM" src="https://user-images.githubusercontent.com/48523809/58726835-be32e500-83b0-11e9-8917-880971cd1f01.png">
`Accessing view manager configs directly off UIManager via UIManager['RNTBannerView'] is no longer supported. Use UIManager.getViewManagerConfig('RNTBannerView') instead.`

So, I tracked it down to the component and updated the code:
![Screen Shot 2019-05-31 at 2 22 20 PM](https://user-images.githubusercontent.com/48523809/58726534-00a7f200-83b0-11e9-8447-6a07048e65bb.png)
to the recommended format:
![Screen Shot 2019-05-31 at 2 21 47 PM](https://user-images.githubusercontent.com/48523809/58726576-1ae1d000-83b0-11e9-81ed-3c7dcf126e1e.png)
except, there are typescript errors.

I couldn't find much documentation on `dispatchViewManagerCommand` nor `getViewManagerConfig`, so I created some placeholder typings here:

    @types+react-native+0.57.60.patch
    
    diff --git a/node_modules/@types/react-native/index.d.ts b/node_modules/@types/react- native/index.d.ts
    index 879fad3..5ca52c0 100644
    --- a/node_modules/@types/react-native/index.d.ts
    +++ b/node_modules/@types/react-native/index.d.ts
    @@ -8361,6 +8361,10 @@ export interface UIManagerStatic {
             error: () => void, /* currently unused */
             success: (item: string, index: number | undefined) => void
         ): void;
    +
    +
    +    dispatchViewManagerCommand(a:any, b:any, c:any): void;
    +    getViewManagerConfig(a: string): any;
     }
     
     export interface SwitchPropsIOS extends ViewProps {

**Comment by alloy** [comment]
Thanks! It would be great if you could send a PR 🙏 You can take a look at the Flow source of RN itself, which likely specifies some type information.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
