### ISSUE TITLE
@types/react-date-range: Type 'Date' is missing the following properties from type 'Moment': format, startOf, endOf, add, and 76 more

### ISSUE THREAD

**Issue by Imballinst** [DefinitelyTyped/DefinitelyTyped#35886]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-date-range` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Junbong 

If you do not mention the authors the issue will be ignored.

-----------

Hey. is it possible for to re-new the type for `@types/react-date-range` because in https://github.com/Adphorus/react-date-range, it is said that the legacy version (v0) is **deprecated**, which uses `moment-timezone` as the main Date definition.

The current version uses plain JS `Date`. However, it is still in beta version, hence why I ask whether it is "ethical" to update this type definition or not. One of the possible solutions is replacing the occurrence of `moment.Moment` to plain JS `Date`. Alternatively, we might as well using oneOf so it is backward compatible, e.g. `moment.Moment | Date`.

But then again, I haven't really explored the TypeScript world, so my suggestion might not be according to best practices. For example, I'm not sure if adding oneOf will result in "loosened" type, which defeats the purpose of using TypeScript.

Personally I think it should be fine to replace it completely. People who use older version of `react-date-range` can revert to the version where it is still defined as `moment.Moment`.

**Comment by Imballinst** [comment]
Do you mind if I submit a PR with my alternative method @Junbong? So that `react-date-range` v1 Date types are supported, while maintaining backward compatibility.

**Comment by Junbong** [comment]
Hi @Imballinst 
Thank you for your suggestions.
But I wonder why do you think this type definition needs more `Date` type?
I mean v0 only uses `moment` inside so JS's plain `Date` may occur unpredictable errors.

**Comment by Imballinst** [comment]
because in the repository, it is written:

> :warning: Warning: the current branch represents the new pre-release version. Legacy version deprecated.
> A date library agnostic React component for choosing dates and date ranges. Uses date-fns for date operations.

And `date-fns` uses plain JS `Date` instead of `Moment`.

That is actually the reason why I made this issue: to clarify whether this type definition is meant only for the stable version (regardless of its deprecation status). If the answer is yes, then I think we can let this be as it is until v1 is released officially.

**Comment by Junbong** [comment]
Okay, I got it
but I think that v1 have been built completely different with v0.
The warning you mentioned is only for v1 and v0 still uses `moment` inside.
So, in my opinion, we need to create another type definition for v1 but not change this repository.

**Comment by Imballinst** [comment]
Makes sense. So I guess it will be better if we wait until v1 is officially released. Thanks for the discussion!
