### ISSUE TITLE
@types/chrome-apps is not a module

### ISSUE THREAD

**Issue by ddsoyka** [DefinitelyTyped/DefinitelyTyped#35912]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @niikoo @AdamLay @mzsm @RReverser @pyle @matthewkimber @otiai10 @couven92 @sreimer15

If you do not mention the authors the issue will be ignored.

---

I am trying to use the `@types/chrome-apps` NPM package type definitions with Typescript & create-react-app in my project and receiving an error.

`File './node_modules/@types/chrome-apps/index.d.ts' is not a module.`

```typescript
import { HidDeviceInfo } from 'chrome-apps'
```
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "include": [
    "src"
  ]
}
```
```typescript
/// <reference types="react-scripts"/>
/// <reference types="chrome"/>
/// <reference types="chrome-apps"/>
```

**Comment by pyle** [comment]
You should use the types like so:

```typescript
class Test {
  info?: chrome.hid.HidDeviceInfo;
}

```

That way, provided the @types/chrome-apps is in your devDependencies you won't need to do `/// <reference types="chrome-apps"/>` or import the specific interface.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
