### ISSUE TITLE
@types/fabric declare module instead of export namespace

### ISSUE THREAD

**Issue by jacobcarpenter** [DefinitelyTyped/DefinitelyTyped#35954]
Authors: @oklemencic; @joewashear007; @mrand01; @NotWoods; @bmartinson; @RogerioTeixeira; @BradleyHill; @bmkrol823; @glenngartner; @codertx

In my application, I need to defer loading `fabric` on the server. As a consequence, I have a few APIs that I want to inject `fabric` into, rather than have them import it directly.

With the [current typescript definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0cd0212b128c685adf75ce8acfa38ad322f3fee5/types/fabric/fabric-impl.d.ts#L4), if I try to declare a parameter as the type `fabric`, I get the following TypeScript error:

```
Cannot use namespace 'fabric' as a type. ts(2709)
```

However, if I change the definition from

```ts
export as namespace fabric;
```
to
```ts
declare module fabric {
```
[and add the corresponding closing brace at the end of the file], TypeScript seems appeased.

Is there any objection to `declare module`? What would the preference for indentation be (it seems a shame to edit every non-empty line just to indent it)?

**Comment by jacobcarpenter** [comment]
After a lot more searching/learning about Typescript, it looks like I can use the following syntax to refer to the current definition as a module:

```
type fabric = typeof import('fabric').fabric;
```

Big thanks to https://davidea.st/articles/typescript-2-9-import-types for putting me on the right track.

**Comment by phoenisx** [comment]
Not sure if this is related, but I feel due to the presence of Global Namespace, fabric types messes the `Object` class in JS, as can be seen in the screenshot.

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/11786283/132277322-a63a5019-90ed-4e20-9e8c-a82045e0ff44.png">

**Comment by kolkov** [comment]
> After a lot more searching/learning about Typescript, it looks like I can use the following syntax to refer to the current definition as a module:
> 
> ```ts
> type fabric = typeof import('fabric').fabric;
> ```
> 
> Big thanks to https://davidea.st/articles/typescript-2-9-import-types for putting me on the right track.

Thanks! This helped me for @types/yandex-maps and Angular with 'export = '.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yandex-maps/index.d.ts#L4731
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/694fd1234a89e7f9e3a6aa866c8338e9a3735cad/types/yandex-maps/index.d.ts#L4731
