### ISSUE TITLE
@types/node tls.d.ts SecureVersion TLSv1.3

### ISSUE THREAD

**Issue by Ghostium** [DefinitelyTyped/DefinitelyTyped#35952]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
- Authors: 
- @jkomyno
- @a-tarasyuk
- @alvis
- @r3nya
- @btoueg
- @brunoscheufler
- @smac89
- @tellnes
- @touffy
- @DeividasBakanas
- @eyqs
- @Flarna
- @Hannes-Magnusson-CK
- @KSXGitHub
- @hoo29
- @kjin
- @ajafff
- @islishude
- @mwiktorczyk
- @matthieusieben
- @mohsen1
- @n-e
- @octo-sniffle
- @parambirs
- @eps1lon
- @SimonSchick

The type SecureVersion https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/tls.d.ts#L337 is missing TLSv1.3.

Also, [maxVersion](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/tls.d.ts#L359) has now TLSv1.3 as default, and minVersion stays the same. See https://nodejs.org/dist/latest-v12.x/docs/api/tls.html#tls_tls_default_max_version

Note: Is there a smaller author list for specific NodeJS modules like tls? Maybe the authors from the commit history of tls.d.ts? Pinging all authors of @types/node, as directed in the issue template, seems a bit much.

**Comment by Flarna** [comment]
No, there is no smaller list. Usually the fastest path forward is to create a PR if you know what to change as you can directly test this in your code.
