### ISSUE TITLE
[@types/storybook__addon-centered] Latest Storybook Version (5.1) not Working

### ISSUE THREAD

**Issue by joealden** [DefinitelyTyped/DefinitelyTyped#35993]
- [x] I tried using the `@types/storybook__addon-centered` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kiyopikko

---

When attempting to upgrade my Storybook package versions:

| Package | Type | Update | Change |
|---|---|---|---|
| [@storybook/addon-centered](https://togithub.com/storybookjs/storybook) | devDependencies | minor | [`5.0.11` -> `5.1.1`](https://renovatebot.com/diffs/npm/@storybook%2faddon-centered/5.0.11/5.1.1) |
| [@storybook/react](https://togithub.com/storybookjs/storybook) | devDependencies | minor | [`5.0.11` -> `5.1.1`](https://renovatebot.com/diffs/npm/@storybook%2freact/5.0.11/5.1.1) |

I encounter an issue where `tsc` complains about incorrect types:

```
error TS2345: Argument of type '(() => { template: string; data(): { style: { readonly position: "fixed"; readonly top: "0"; readonly left: "0"; readonly bottom: "0"; readonly right: "0"; readonly display: "flex"; readonly alignItems: "center"; readonly overflow: "auto"; }; innerStyle: { ...; }; }; }) | ((storyFn: () => ReactNode) => Element)' is not assignable to parameter of type 'StoryDecorator'.
  Type '() => { template: string; data(): { style: { readonly position: "fixed"; readonly top: "0"; readonly left: "0"; readonly bottom: "0"; readonly right: "0"; readonly display: "flex"; readonly alignItems: "center"; readonly overflow: "auto"; }; innerStyle: { ...; }; }; }' is not assignable to type 'StoryDecorator'.

29   .addDecorator(centered)
                   ~~~~~~~~
```

From what I can tell, this is happening because TypeScript isn't picking up the `@types/storybook__addon-centered` type definitions correctly, as the exact same error occurs when removing the `@types/storybook__addon-centered` package completely.

Here are some screenshots that might be of some help:

![screenshot 1](https://user-images.githubusercontent.com/10297243/59025157-7813d080-884b-11e9-8125-15dcf7e4fa82.png)

This screenshot shows the contents of the type definition file in my node_modules.

---

![screenshot 2](https://user-images.githubusercontent.com/10297243/59025160-7a762a80-884b-11e9-9dab-e7280462811e.png)

This screenshot shows the type that TypeScript is inferring of `centered`.

---

![screenshot 3](https://user-images.githubusercontent.com/10297243/59025165-7ba75780-884b-11e9-9911-846b579fa645.png)

This screenshot shows what the type of `centered` was before I upgraded Storybook.

---

It is worth noting that although I am using TypeScript version `3.3.4000` in these screenshots, I have installed the latest `tsc` version as well (`3.5.1`) and the exact same error occurs.

**Comment by kiyopikko** [comment]
@joealden

You can resolve that by using `@storybook/addon-centered/react` instead of `@storybook/addon-centered`

Reference: https://github.com/storybookjs/storybook/blob/next/addons/centered/src/index.ts#L12-L14

**Comment by joealden** [comment]
@kiyopikko thanks, that worked!

I must have missed that using the import non-post-fixed was deprecated.

Closing.
