### ISSUE TITLE
Provide a way to import fetch typings on node env without importing `dom` TS lib

### ISSUE THREAD

**Issue by jtomaszewski** [DefinitelyTyped/DefinitelyTyped#36082]
Let's do one issue for all those related problems and discuss how it could be done?

Our problem: we have a next.js app that is rendered on both client and server. 
On client we use `tsconfig.json` that has the `lib: ['dom']`.
On server we use `tsconfig.server.json` that don't have that lib (as DOM apis are not available there).

Problem: we get errors like `Cannot find name 'fetch'` when trying to compile a TS app that uses https://www.npmjs.com/package/@types/isomorphic-fetch (or other isomorphic libs of which typedefs rely on TS dom lib, i.e. [apollo-link-rest](https://github.com/apollographql/apollo-link-rest/blob/master/tsconfig.json#L4)).

Related:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16002#issuecomment-338241158
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30814
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24765
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12968#issuecomment-263473496

What would be the best solution to handle all of those problems? This problem is apparent at least since mid-2017.

IMHO Ideally fetch typedef should not rely on dom lib. At least there should be a way to define `fetch` typedef without the need of importing full `dom` lib.

Maybe in TS source code https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts the `fetch` typedef should be extracted to sth like `dom.fetch` ?

Or maybe instead of importing anything dom-related on node env, we should somehow use own fetch definition ( https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node-fetch )? And just add it on server environment, i.e. with `"types": ["node-fetch"]` on `tsconfig.server.json` ? 

P.S. Does anyone know a workaround for making it work on node environment, at least for now, without having to do `lib: ['dom']` in tsconfig?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
