### ISSUE TITLE
connect function type throw weird error using mapDispatchToProps shorthand syntax with redux-thunk

### ISSUE THREAD

**Issue by babyadoresorange** [DefinitelyTyped/DefinitelyTyped#36105]
I have a type error using connect function with mapDispatchToProps shorthand syntax with @types/react-redux

in action.ts

`export function fetch(): ThunkAction<void, State, any, AnyAction>`

then A.ts

`type Props = { fetch: typeof fetch, etc... }`
`let A = class extends React.Component<Props, {}> {}`
`connect(mapStateToProps, { fetch })(A)`

it throw me this Error

> Types of property 'fetch' are incompatible.
          Type '() => void' is not assignable to type '() => ThunkAction<...>, any, AnyAction>'.
            Type 'void' is not assignable to type 'ThunkAction<...>, any, AnyAction>'.ts(2345)

I notice that this error is because I declared the return type of the action creator `ThunkAction<R, S, E, A>` as `ThunkAction<void, State, any, AnyAction>` where R is void.

That means somehow the connect function take the return type of the ThunkAction as the return type of my action creator. If I declare it as `ThunkAction<any, State, any, AnyAction>` then the problem goes away. Is this a normal behaviour ?

Authors: @tkqubo @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo @Kallikrein @jrakotoharisoa @apapirovski @surgeboris @soerenbf

**Comment by danpantry** [comment]
Did you import your `fetch` function from `action.ts`? This honestly might be a better question for StackOverflow with complete code excerpts on something like gist or codesandbox etc.
