### ISSUE TITLE
[@types/auth0] Missing properties in changePassword

### ISSUE THREAD

**Issue by kainoffke** [DefinitelyTyped/DefinitelyTyped#36108]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @westy92, @ianhowe76, @dauledk, @dancrumb

I tried to use the typings with with `auth0:2.17.1`. I wanted to create a password change ticket and pass a value for `mark_email_as_verified` but this field is missing in the typings. It seems like `mark_email_as_verified` and `includeEmailInRedirect` are currently missing in `PasswordChangeTicketParams`.

**Comment by ianhowe76** [comment]
Can you create a PR with the required changes?

**Comment by kainoffke** [comment]
I‘ll create a PR as soon as i have my Mac back from Service ;)

**Comment by kainoffke** [comment]
Finally opened up the PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36892
I hope its alright ;)

**Comment by kainoffke** [comment]
PR has been merged; I will close this issue.
