### ISSUE TITLE
Potential generic MergeDeep bug for ramda types

### ISSUE THREAD

**Issue by nicohvi** [DefinitelyTyped/DefinitelyTyped#36110]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond: @donnut, @tycho01 , @mdekrey, @mrdziuban, @sbking, @afharo, @teves-castro, @1M0reBug, @hojberg, @samsonkeung, @brekk, @biern, @rgm, @leighman

First off, thank you all for the excellent library :-)

This might be because I don't quite understand the `MergeDeep` type correctly, but in my mind the following should work:

```ts
function fn<T>(foo: T): T {
  return R.mergeDeepRight(foo, foo)
}
```
But it generates an error:
```
Type 'MergeDeep<T, T>' is not assignable to type 'T'.
  'MergeDeep<T, T>' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{}'.
```
When the type is **not** generic, everything works as expected:
```ts
interface Data {
  user: {
    name?: string;
    email?: string;
  }
}

function fn(foo: Data): Data {
  const base : Data = {
    user: {
      name: 'Frank'
    }
  }
  // return R.mergeDeepRight(foo, foo); works!
  return R.mergeDeepRight(base, foo); // also works
}
```

**@types/ramda**: 0.26.9
**typescript**: 3.5.1

**Comment by afharo** [comment]
Question (sorry I’m AFK so can’t test it myself):
Have you tried with `fn<T extends object>`?

It looks to me like it’s a typical Typescript weird behavior with generic types. It thinks T might be other than an object but `MergeDeep` is an extension of object so they might not match.

**Comment by nicohvi** [comment]
Thanks for the prompt reply, @afharo! 

> Have you tried with `fn<T extends object>`?

Yes, I've tried both `fn<T extends object>` as well as a myraid of other options (`extends {}`, `extends unknown` etc), but the result is essentially the same.

```
  'MergeDeep<T, T>' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'object'.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
