### ISSUE TITLE
[redux-form] InjectedFormProps change type does not support nested fields or function value

### ISSUE THREAD

**Issue by dpetranek** [DefinitelyTyped/DefinitelyTyped#36149]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/redux-form: 8.1.3` package and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  
- [ x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @iamandrewluca @amcasey 

It looks like in the most recent update we tightened the interace for the `change` function from
`change(field: string, value: any): void;`
to
`change<F extends keyof FormData>(field: F, value: FormData[F]): void;`

However, this type doesn't support updating nested values, either using dot notation, as from [this feature](https://github.com/erikras/redux-form/issues/55):

`change('field.nestedField', 'newValue')`

Or by using an update function, as mentioned in the [docs](https://redux-form.com/8.2.2/docs/api/props.md/#-code-change-field-string-value-any-function-code-)

`change('field', value => ({...value, nestedField: 'newValue'})`

I can currently work around this issue in a number of ways - 
1. the action creator `change` still has a generic `change(form: string, field: string, value: any)` signature,
2. I could assemble the whole new nested value at the callsite

But it would be good to support this official interface in the type.

```
change<F extends keyof FormData>(
  field: string, 
  value: FormData[F] | (fieldValue: FormData[F], allValues: FormData) => FormData[F]
): void;
```

This does loosen the possible values for `field`, but I think the tradeoff would be worth it so that we can support nested fields.

**Comment by iamandrewluca** [comment]
I will make a PR to revert my previous PR. At the moment TypeScript can't infer nested object keys using dot notation, and I think will not be supported in the near future.

**Comment by iamandrewluca** [comment]
@dpetranek see last version. This issue should be closed.
