### ISSUE TITLE
Optional disappearing problem

### ISSUE THREAD

**Issue by bugtype** [DefinitelyTyped/DefinitelyTyped#36189]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/yargs/v12` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

@poelstra @pushplay @jeffkenney @JimiC  @steffenvv @forivall 

There is a problem that `optional` will be disappearing.
In my opinion, to solve the problem, we have to change it as follows.

before
```typescript
    type Omit<T, K> = { [key in Exclude<keyof T, K>]: T[key] };
```

after
```typescript
    type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
```

**Comment by pushplay** [comment]
@bugtype Can you link to the document explaining what's disappearing?

The proposed definition of `Omit` matches TS 3.5's lib.d.ts and looks right to me.

**Comment by steffenvv** [comment]
The current version of Omit allows you to omit keys that aren't already in T, which we are doing in a few places. I tried the proposed version, and it broke the yargs-tests.ts in a couple of places, but I'm not sure that the usage in those test cases are wrong.

Can you illustrate with a test case how you want the current type inferences to change?

**Comment by bugtype** [comment]
```typescript 
import {Omit} from 'yargs'
import * as Joi from 'joi';
import 'joi-extract-type';

const schema = {
    aaaaaaa: Joi.number()
        .integer()
        .positive()
        .optional(),
        aaaaaaa2: Joi.number()
        .integer()
        .positive()
        .optional(),
        aaaaaaa3: Joi.number()
        .integer()
        .positive()
        .optional(),
        aaaaaaa4: Joi.number()
        .integer()
        .positive()
        .optional(),
        aaaaaaa5: Joi.number()
        .integer()
        .positive()
        .optional(),
        aaaaaaa6: Joi.number()
        .integer()
        .positive()
        .optional(),
        aaaaaaa7: Joi.number()
        .integer()
        .positive()
        .optional(),
        aaaaaaa8: Joi.number()
        .integer()
        .positive()
        .optional(),
        aaaaaaa9: Joi.number()
        .integer()
        .positive()
        .optional(),
        aaaaaaa10: Joi.array()
        .items(
            Joi.number()
                .positive()
                .integer(),
        )
};

const schema2 = {
    bbbbbb: Joi.number()
        .integer()
        .positive()
        .optional(),
        bbbbbb2: Joi.number()
        .integer()
        .positive()
        .optional(),
        bbbbbb3: Joi.number()
        .integer()
        .positive()
        .optional(),
        bbbbbb4: Joi.number()
        .integer()
        .positive()
        .optional(),
        bbbbbb5: Joi.number()
        .integer()
        .positive()
        .optional(),
        bbbbbb6: Joi.number()
        .integer()
        .positive()
        .optional(),
        bbbbbb7: Joi.number()
        .integer()
        .positive()
        .optional(),
        bbbbbb8: Joi.number()
        .integer()
        .positive()
        .optional(),
        bbbbbb9: Joi.number()
        .integer()
        .positive()
        .optional(),
        bbbbbb10: Joi.array()
        .items(
            Joi.number()
                .positive()
                .integer(),
        )
};

type argType = Joi.extractType<typeof schema>;
type Test1 = Omit<argType, 'aaaaaaa2'>;
```
### argType
<img width="425" alt="Screen Shot 2019-06-15 at 11 54 23 AM" src="https://user-images.githubusercontent.com/24269591/59546196-72616d80-8f64-11e9-9d18-e8471913f83c.png">

### Test1
<img width="451" alt="Screen Shot 2019-06-15 at 11 54 18 AM" src="https://user-images.githubusercontent.com/24269591/59546195-6f667d00-8f64-11e9-9ba8-4937e7949f7c.png">

**Comment by steffenvv** [comment]
I see, thanks. Can you also give an example where using Joi in combination with yargs is causing issues? Otherwise it seems like you could just use the standard Omit type instead of importing the version of Omit that's defined by yargs.

**Comment by bugtype** [comment]
Well... I'm not sure about any other issues...
Thank you for your answer. I'll use typescript 3.5 later.
Have a good time.
