### ISSUE TITLE
[@types/reach__router] HistorySource for createHistory is incompatible with window

### ISSUE THREAD

**Issue by sorahn** [DefinitelyTyped/DefinitelyTyped#36198]
Trying to use the `createHistory` function as described [here](https://reach.tech/router/api/createHistory) and I get the following error.

```
Argument of type 'Window' is not assignable to parameter of type 'HistorySource'.
  Types of property 'location' are incompatible.
    Type 'Location' is not assignable to type 'WindowLocation'.
      Property 'state' is missing in type 'Location' but required in type 'Location<any>'.ts(2345)
index.d.ts(30, 5): 'state' is declared here.
```

the `'state' is declared here` message links to [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/history/index.d.ts#L30).

I'm not sure what's wrong, or how to work around this with out just killing the whole types declaration for ~~@reach/router~~ history.

I'm very new to typescript and I barely know enough to get my app working, let alone submit a PR to fix the issue.  Sorry :(

@kingdaro

**Comment by BrunoQuaresma** [comment]
I have the same issue.

**Comment by sorahn** [comment]
@BrunoQuaresma my solution was to just add this line to my `react-app-env.d.ts` file

```
// remove after github bug fixed
// https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36198
declare module "history";
```

**Comment by BrunoQuaresma** [comment]
thank you @sorahn

**Comment by kingdaro** [comment]
@sorahn You might not know now, but it's a good time to learn 🙂

[Here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/reach__router/index.d.ts#L136), the function needs to be updated to also accept `Window`:
```ts
export function createHistory(source: HistorySource | Window): History;
```

Then, add a test to [this file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/reach__router/reach__router-tests.tsx) to make sure it works going forward.
```ts
// listen to the browser history
const windowHistory = createHistory(window)

// using a memory source
const source = createMemorySource("/starting/url")
const memoryHistory = createHistory(source)
```

**Comment by sorahn** [comment]
@kingdaro Thank you for the lesson! I wasn't sure if the fix would be changing the param type, or updating HistorySource interface.

I will try and make a pull request for this tomorrow.

**Comment by kingdaro** [comment]
Sure thing 👍 I think either would work though

**Comment by sorahn** [comment]
@kingdaro I haven't made this a PR yet, becasue I'm also unsure how the testing works.  I added 2 more `LocationProvider`s to the render function using the windowHistory and the memoryHistory.

Is the idea just to make sure that it renders as written?  I don't see any code that looks like it would click the buttons provided.

I ran `npm test` and it picked up the changes and ran the test and everything passed.  

diff: https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...sorahn:window-history

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
