### ISSUE TITLE
Support xmljs

### ISSUE THREAD

**Issue by lyoko17220** [DefinitelyTyped/DefinitelyTyped#36202]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xmljs` package and had problems (not exist).
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @blackshadev

**Comment by blackshadev** [comment]
Hi I gladly add type definitions for it, I am kinda busy right now but I will make time for it somewhere in the next month. To be honest, xmljs was written by me 4 years ago and I am quite surprised somebody besides me is actually using it.

**Comment by lyoko17220** [comment]
You have made a real simple xml->object converter so that's perfect for my use case ! Thanks for your help :)

**Comment by blackshadev** [comment]
see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36228

**Comment by lyoko17220** [comment]
Thanks for your support !

**Comment by blackshadev** [comment]
@lyoko17220 the merge request has been accepted and type definitions should be downloadable
