### ISSUE TITLE
@types/react-redux - Rendering connected component with undefined 'mergedProps' parameter throws TSLint error 2739

### ISSUE THREAD

**Issue by StrikeAgainst** [DefinitelyTyped/DefinitelyTyped#36268]
I ran into an issue using React Redux together with TypeScript and TSLint.

I added the option parameter to the connect function for my component, having to put a nullified parameter for mergeProps in between.

```
export default connect<PropsFromState, PropsFromDispatch, OwnProps>(
    mapStateToProps,
    mapDispatchToProps,
    null,
    { forwardRef : true }
)(MyComponent);
```

**What is the current behavior?**

Wanting to render the component throws a TSLint error for me:

`<MyComponent ownProp ref={ref => this.comp = ref}/>`

> Type '{ ownProp: true; ref: (ref: Component<Pick<MyComponent, "ownProp" | "stateProp" | "dispatchProp"> & OwnProps, any, any>) => Component<...>; }' is missing the following properties from type 'Readonly<Pick<MyComponentProps, "ownProp" | "stateProp" | "dispatchProp"> & OwnProps>': stateProp, dispatchProp - ts(2739)

...basically asking for state and dispatch props where it shouldn't ask for them.

Tracing back the type definition of connect (via Visual Studio Code), it refers me to

```
<TStateProps = {}, TDispatchProps = {}, TOwnProps = {}, TMergedProps = {}, State = {}>(
	mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps, State>,
	mapDispatchToProps: MapDispatchToPropsParam<TDispatchProps, TOwnProps>,
	mergeProps: MergeProps<TStateProps, TDispatchProps, TOwnProps, TMergedProps>,
	options?: Options<State, TStateProps, TOwnProps, TMergedProps>
): InferableComponentEnhancerWithProps<TMergedProps, TOwnProps>;
```

**What is the expected behavior?**

The component should not throw any error asking for state and dispatch props.

The type definition of connect should actually refer to

```
<TStateProps = {}, TDispatchProps = {}, TOwnProps = {}, State = {}>(
	mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps, State>,
	mapDispatchToProps: MapDispatchToPropsNonObject<TDispatchProps, TOwnProps>,
	mergeProps: null | undefined,
	options: Options<State, TStateProps, TOwnProps>
): InferableComponentEnhancerWithProps<TStateProps & TDispatchProps, TOwnProps>;
```

I'm using these versions:
react - 16.8.6
react-dom - 16.8.6
react-redux - 7.1.0
@types/react-redux - 7.1.0
typescript - 3.5.2
tslint - 5.16.0

**Comment by StrikeAgainst** [comment]
Authors: @tkqubo @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo @Kallikrein @jrakotoharisoa @apapirovski @surgeboris @soerenbf @MrWolfZ

**Comment by StrikeAgainst** [comment]
Well, the only way to work around this now was enabling 'strictNullChecks' in TypeScript...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
