### ISSUE TITLE
@types/react-route-config  interface RouteConfig bug?

### ISSUE THREAD

**Issue by kanghongyan** [DefinitelyTyped/DefinitelyTyped#36311]
- [ ] I tried using the `@types/react-router-config` package and had problems.
- [ ] I tried using the latest stable version of tsc. 3.4
  - Authors: @mathieutu

I use react-router-config-tests.tsx example

change  Home function to Home class, in order to  pass some props to component

there is Home class code:

```
interface IProps extends RouteConfigComponentProps<{}>{
    propsData: string
}
class Home extends React.Component<IProps, {}> {
    render() {
        
        const { propsData } = this.props;
        
        return (
            <div>
                <h2>Home</h2>
                {propsData}
            </div>
        )
    }
}
```

routerConfig code:
```
const routes: RouteConfig[] = [
    {
        component: Root,
        routes: [
            {
                path: "/",
                exact: true,
                component: Home
            },
            {
                path: "/child/:id",
                component: Child,
                routes: [{
                    path: "/child/:id/grand-child",
                    component: GrandChild
                }],
                loadData: () => Promise.resolve({})
            }
        ]
    }
];
```
but typescript report error in routes.routes:

<img width="958" alt="ts-RouteConfig-error" src="https://user-images.githubusercontent.com/11732738/59828519-ce196580-936d-11e9-998a-feab6adbbf9a.png">

when I rewrite RouteConfig interface to this, no error report:
```
interface RouteConfig {
    key?: React.Key;
    location?: Location;
    // todo: copy from @types/react-router-config
    // component?: React.ComponentType<RouteConfigComponentProps<any>> | React.ComponentType;
    component?: React.ComponentType<RouteConfigComponentProps<any>> | React.ComponentType<any>,
    path?: string;
    exact?: boolean;
    strict?: boolean;
    routes?: RouteConfig[];
    render?: (props: RouteConfigComponentProps<any>) => React.ReactNode;
    [propName: string]: any;
}
```

What am I do is change `component?: React.ComponentType<RouteConfigComponentProps<any>> | React.ComponentType` to `component?: React.ComponentType<RouteConfigComponentProps<any>> | React.ComponentType<any>`

bug in @types/react-route-config or something wrong?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
