### ISSUE TITLE
@types/react Cannot use React.memo with defaultProps

### ISSUE THREAD

**Issue by user753** [DefinitelyTyped/DefinitelyTyped#36320]
This works
```
export const Foo = (props: {foo: number}) => {
  return <div>{props.foo}</div>
}
Foo.defaultProps = {foo: 1}
```
This doesn't
```
export const Foo = React.memo((props: {foo: number}) => {
  return <div>{props.foo}</div>
})
Foo.defaultProps = {foo: 1}
```
```
TS2339: Property 'defaultProps' does not exist on type 'MemoExoticComponent<(props: { foo: number; }) => Element>'.
```

Authors: @ferdaber @johnnyreilly @sandersn @RyanCavanaugh @tkrotoff @weswigham

**Comment by ferdaber** [comment]
I believe `React.memo` does not actually support `defaultProps`, only the inner component does.

**Comment by user753** [comment]
@ferdaber 
```
export const Foo = React.memo((props: {foo: number}) => {
  return <div>{props.foo}</div>
}) as any
Foo.defaultProps = {foo: 1}
<Foo/> // render 1
```

**Comment by user753** [comment]
Could someone explain why `MemoExoticComponent` cannot just extend `FunctionComponent`?

**Comment by ferdaber** [comment]
Memoized components aren't actually functions, they are a special object type that React recognizes and treats as a component, so they are not actually callable. In the past, only some of the exotic components supported all of the features of function components (`propTypes`, `displayName`, or `defaultProps`) so they had to be separated out.

**Comment by user753** [comment]
@ferdaber It looks like these features works, so maybe it's time to change the typing?

**Comment by femiveys** [comment]
Is anyone looking into this?

**Comment by dungnguyen10989** [comment]
try it: 
```
(Foo as React.ComponentType<Props>).defaultProps = {
	foo: '1'
};
```

**Comment by ali-rival** [comment]
```
type Props = {
    hasProp?: boolean;
  };
  
const MyComponent = ({ hasProp }) => (
    <>
      {hasProp && (
         <h1>I have the prop</h1>
      )}
      <div>I don't have the prop</div>
    </>
);
  
MyComponent.defaultProps = {
    hasProp: false
};
  
export default React.memo<Props>(props => <MyComponent {...props} />);

**Comment by mikeaustin** [comment]
Any updates on how to add a property to the result of a React.memo()? I'm currently using the "as" typecast to any, but that's hacky. Example use is <Toolbar.Group ... /> where both are memoized.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by vladrozhnev** [comment]
```
type Props = {
  title: string;
};

type ExtendedComponent = React.NamedExoticComponent<Props> & {
  defaultProps: Props;
};

export const SomeComponent: ExtendedComponent = Object.assign(
  memo<Props>(() => null),
  { defaultProps: { title: 'Hello World!' } },
);
```
