### ISSUE TITLE
@type/underscore failed to build since yesterday.

### ISSUE THREAD

**Issue by VCL1995** [DefinitelyTyped/DefinitelyTyped#36326]
@type/underscore failed to build after the latest changes #36230

- @types/underscore/index.d.ts:107:34: ';' expected.
- @types/underscore/index.d.ts:107:61: ';' expected.
- @types/underscore/index.d.ts:107:64: Expression expected.
  - Authors: @regevbr @DanielRosenwasser

**Comment by regevbr** [comment]
This looks strange. What typescript version are you using?

**Comment by VCL1995** [comment]
"typescript": "2.3.3"

**Comment by regevbr** [comment]
The min version for underscore is now 2.8.
If you want to use a version with lower typescript version, please use
```shell
npm install @types/underscore@ts2.3
```

**Comment by DanielRosenwasser** [comment]
Yup, @regevbr is right. The correct workaround is indeed

```
npm install @types/underscore@ts2.3
```

or to upgrade to a newer version.

**Comment by VCL1995** [comment]
it worked. Thanks.

**Comment by regevbr** [comment]
Glad to hear! 
@DanielRosenwasser why did you add the question tag? Can we close the issue?
