### ISSUE TITLE
@types/react-native: StyleSheet.create() invalid styles parameter

### ISSUE THREAD

**Issue by svipas** [DefinitelyTyped/DefinitelyTyped#36357]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy, @huhuanming, @iRoachie, @skn0tt, @timwangdev, @kamal, @alexdunne, @swissmanu, @bm-software, @a-tarasyuk, @mvdam, @esemesek, @mrnickel, @souvik-ghosh, @nossbigg, @saranshkataria, @franzmoro, @tykus160, @jakebloom, @ceyhun, @mcmar

### Problem

Trigger autocompletion list (it's empty) - **BAD**

<img width="484" alt="Screen Shot 2019-06-21 at 21 43 09" src="https://user-images.githubusercontent.com/10441177/59944581-cc36cb80-946d-11e9-9ed6-1c313c9062ce.png">

Write any char (list is not empty) - **GOOD**

<img width="484" alt="Screen Shot 2019-06-21 at 21 43 20" src="https://user-images.githubusercontent.com/10441177/59944582-cc36cb80-946d-11e9-94ef-4eef09bb651d.png">

Trigger autocompletion second time when there's `height` prop (it's empty) - **BAD**

<img width="484" alt="Screen Shot 2019-06-21 at 21 43 27" src="https://user-images.githubusercontent.com/10441177/59944583-cccf6200-946d-11e9-8262-64eed87fa905.png">

Write any char when there's `height` prop (it's empty) - **BAD**

<img width="484" alt="Screen Shot 2019-06-21 at 21 43 34" src="https://user-images.githubusercontent.com/10441177/59944584-cccf6200-946d-11e9-8370-10f98117c102.png">

As you can see in pictures it works the only the first time and only if I type some character, but the second time it doesn't work and I can't trigger suggestions list to see properties I can modify because the list is empty and I get built-in VS Code snippets, etc.

### If I change from `styles: T` to `styles: T | NamedStyles<T>`

<img width="484" alt="Screen Shot 2019-06-21 at 21 48 39" src="https://user-images.githubusercontent.com/10441177/59944805-74e52b00-946e-11e9-9b69-83f69fa43a4d.png">
<img width="484" alt="Screen Shot 2019-06-21 at 21 48 51" src="https://user-images.githubusercontent.com/10441177/59944806-74e52b00-946e-11e9-8cd7-ee758110a112.png">
<img width="484" alt="Screen Shot 2019-06-21 at 21 48 58" src="https://user-images.githubusercontent.com/10441177/59944807-757dc180-946e-11e9-8374-b34940ca0976.png">
<img width="484" alt="Screen Shot 2019-06-21 at 21 49 09" src="https://user-images.githubusercontent.com/10441177/59944809-757dc180-946e-11e9-887f-71e0f5153caa.png">
<img width="484" alt="Screen Shot 2019-06-21 at 21 49 27" src="https://user-images.githubusercontent.com/10441177/59944810-757dc180-946e-11e9-8135-ff01b0cf69a2.png">

As you can see in pictures if I change from `styles: T` to `styles: T | NamedStyles<T>` in `StyleSheet.create()` everything works as expected.

**Comment by alloy** [comment]
I’m on a phone and so can’t easily consult the source,  but that does look like an improvement in resulting behavior. Can you PR it?

**Comment by svipas** [comment]
@alloy Yes, of course, I can. Thank you very much for the comment I'm very glad this will be fixed!

**Comment by svipas** [comment]
@alloy Opened a PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36362

**Comment by alloy** [comment]
Thanks!
