### ISSUE TITLE
react-router-dom outdated?

### ISSUE THREAD

**Issue by AnderssonPeter** [DefinitelyTyped/DefinitelyTyped#36368]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/react-router-dom` (4.3.4) package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (3.5.2)
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @huy-nguyen, @p-jackson, @johnnyreilly, @eps1lon

When using this package with `"react-router-dom": "^5.0.1"` and trying to use the `activeClassName` on a `Link` i get the following error:
```
TypeScript error in D:/Projects/MiFloraSwarm/MiFloraGateway/ClientApp/src/Header.tsx(8,14):
Type '{ children: string; to: string; className: string; activeClassName: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Link> & Readonly<LinkProps> & Readonly<{ children?: ReactNode; }>'.
  Property 'activeClassName' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Link> & Readonly<LinkProps> & Readonly<{ children?: ReactNode; }>'.  TS2322
```

Any chance we could get a update to 5.0.X?

**Comment by mmahalwy** [comment]
any update on this?

**Comment by gndelia** [comment]
+1 on this, it would be great to have it

**Comment by eps1lon** [comment]
There is no prop named `activeClassName` documented on [`Link`](https://reacttraining.com/react-router/web/api/Link). Did you mean [`NavLink`](https://reacttraining.com/react-router/web/api/NavLink) which does have this prop documented and [typed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a7e8fa6b541426d28c7e742b567a357e64cc26b8/types/react-router-dom/index.d.ts#L61)?

**Comment by AnderssonPeter** [comment]
@jaysoo switch to what?

**Comment by AnderssonPeter** [comment]
@eps1lon looks like you are right, thanks! (sorry for being confused)
