### ISSUE TITLE
Mathjs 6

### ISSUE THREAD

**Issue by niyoko** [DefinitelyTyped/DefinitelyTyped#36381]
Recenly, mathjs has a major version upgrade.
https://mathjs.org/history.html#20190608-version-600

@regevbr @blackshadev

**Comment by regevbr** [comment]
@niyoko why did you mention me?

**Comment by blackshadev** [comment]
Hi, why am I mentioned. I do not maintain, contribute or use MathJS. At least not that I know of.

**Comment by charlee** [comment]
@jtenner I noticed that you mentioned you were working on the typing in mathjs repo: https://github.com/josdejong/mathjs/issues/1539
Just wonder if you are still working on this?

**Comment by jtenner** [comment]
No. Sadly. I  don't think I am able to do this because I don't understand the types well enough and I don't have enough time.

Can someone else pick up the ball?

**Comment by charlee** [comment]
@jtenner No worry. I would like to take a look.
Can anyone assign this issue to me? @niyoko @blackshadev

**Comment by blackshadev** [comment]
@charlee , I do not maintain or contribute or use MathJS. I do not have any rights to assign any thing to anybody on MathJS or this repo. Please do not mention me.

**Comment by charlee** [comment]
Hello @niyoko, the PR has been merged and this issue can be closed soon.

**Comment by niyoko** [comment]
Thank you @charlee.
