### ISSUE TITLE
[@types/openid-client] Missing types for Passport Strategy

### ISSUE THREAD

**Issue by FlorianSW** [DefinitelyTyped/DefinitelyTyped#36390]
The types for the openid-client (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/openid-client/index.d.ts) are currently missing the type definition for the passport Strategy. The Stratey is defined in:
https://github.com/panva/node-openid-client/blob/master/lib/passport_strategy.js

**Comment by lkreimann** [comment]
I would love to have that in @types/openid-client, too! 
Not sure how to add that here, but I would like to offer my help, if I can be any help at all.

**Comment by FlorianSW** [comment]
No need for them anymore, the package provides their own types, and the passport strategy types are included there.
