### ISSUE TITLE
@types/react-relay dev-deps BC break

### ISSUE THREAD

**Issue by akomm** [DefinitelyTyped/DefinitelyTyped#36393]
- [x] I tried using the `@types/react-relay` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] @graphcool, @voxmatt, @alloy, @npirotte, @ckknight, @kastermester, @mattkrick

You have set dev-dependency on `@types/relay-runtime@*`. This is a terrible idea, becaue whenever you add new BC breaking versions (e. G. 4, 5, ...), you break older installation. I have now suddenly `@types/relay-runtime@5.0.0`. Installing explicitly `@types/relay-runtime@^1.3.12` leads to a dupe version 5.0.0 inside the react-relay types which is then used.

The worst thing is, that when you create a project and those newer BC breaking versions are not there, everything is fine. Then you check out elsewhere and make install and suddenly typing is broken, because now you have added version 4 and 5...

When I have BC constraints in versions, even without lockfile, stuff should not break. Yes maybe I get newer BC versions, but not major BC breaking ones...

**Comment by akomm** [comment]
Further checking I found out, that this issue is not so easy spotted when using npm, but still is a package issue. When you use yarn, it seem to behave weird by installing a dupe for the * version, even thought an explicit dependency, which matches * is already specified. However I do not close this because the core issue is still the package dependency:

When I install @types/react-relay, I will get now 5.0.0. I will also get @types/relay-runtime 5.0.0.
Everything will work, because you have added the dependency. However, the moment @types/relay-runtime 6.0.0 is out, I will get it, even though I still have @ŧypes/react-relay 5.0.0.

Then either add the proper, compatible version or do not add it at all or as peer dependency, so that one is forced to specify/install relay-runtime explicitly and such an unexpected break does not happen.

**Comment by alloy** [comment]
I agree with you, but this is alas not something we can control—DT packages are automatically created including decencies and their version constraints, and dependency managers should resolve this in an appropriate manner.

I see you already filed an issue with yarn, which I think is the best recourse. Thanks for doing that! Going to close this issue for maintenance sake, as there’s nothing actionable for us here.

**Comment by akomm** [comment]
@alloy

no dependecy manager out there does resolve it. neither yarn nor npm. They just install the newest version because its specified this way in your package.json. The problem can also happen using npm. Due to yarn I just had one additional way to trip over the issue.

So to clarify: you do not have control over the package.json dependencies section in this repository?

**Comment by alloy** [comment]
> no dependecy manager out there does resolve it. If you have * specified, it means "any version". Neither yarn nor npm does resolve there anything beside this. 

Yes, ‘any version’ imo should mean that when you e.g. perform `yarn upgrade @types/react-relay` yarn would install a _single_ latest version, or if you lock it to a certain version in your `package.json` only _that_ version would be used as `*` should be compatible with any other version.

> So to clarify: you do not have control over the package.json dependencies section in this repository?

Correct.

> I ask, because then there should maybe an general DT issue then?

I’m pretty sure there are issues about this, it’s at least brought up in unrelated issues every now and then.

Perhaps there are workarounds that could be made, in which case perhaps an issue could be raised with details on the workaround. However, to _me_ the `*` version constraint is the correct one and dependency managers should install a single version of a package with such a constraint.

**Comment by akomm** [comment]
@alloy 

but you realize, that when you `npm install @types/react-relay@^1.3.12`, you would get `@types/relay-runtime@5.0.0` currently? Which makes all your opinion regarding this meaningless, because neither npm, nor yarn (even when the other bug is fixed) not any package manager I am aware of in any other language would handle it like that. Because its total non-sense. This is simply wrong dev-deps spec, no matter whether you would do such a thing in rust, javascript, php, java, elsewhere. 

The only thing I understand is that you currently can not change it. But calling it "normal" is really odd.

**Comment by akomm** [comment]
@alloy 

but you realize, that when you `npm install @types/react-relay@^1.3.12`, you would get `@types/relay-runtime@5.0.0` currently? Which makes all your opinion regarding this meaningless, because neither npm, nor yarn (even when the other bug is fixed) or any package manager I am aware of in any other language would handle it like that. Because its total non-sense. This is simply wrong deps spec, no matter whether you would do such a thing in rust, javascript, php, java or elsewhere. 

The only thing I understand is that you currently can not change it because this single repo is updated via tool(?) indirectly or similar reason (not aware of detail, but I get the point, probably because its a single repo for many projects). But calling it "normal" is really odd.

**Comment by alloy** [comment]
We’re talking about different things.

I agree that you’d want the same typings version of the package version you’re using. What I am responding to is that you should be able to control it fine, as the end user, with `*` version constraints—were it not for eg yarn deciding to install different versions of the same typings package instead of a single deduped one.

**Comment by akomm** [comment]
@alloy

I feel either I misunderstand something terribly or you did not read my answer correctly. You are talking about yarn. I am talking about how this is also an issue with NPM, simply because * is a wrong constraint, while completely understand the current DT situation as reason why you can not do yet anything about it.

However why I am stil taking about is the decision whether its an issue on DT side or not and for that its important to understand whether something is wrong or not.

So again, currently running `npm install @types/react-relay@^1.3.12` would install `@types/relay-runtime@5.0.0`, which is wrong version of the dependency. AFAIK this is not NPM bug but how it is intended to work. Simply because the constraint is `any`. While your different interpretation of `*` might also make sense in a different world with different definition, it is not how npm or (fixed) yarn work. From package management point of view, one of the core ideas is, that I do not have to mess around with what versions of certain packages third party packages need. If everyone would make packages like that it would be hell on earth. Except its an optional dependency (like an ORM package and then different DBALs). There are however concept how, in case you do install a DBAL the correct version is also resolved in that case, but this gets out of scope now.

TO widen the thinking proccess, I asked myself the question: if I glance at other package management systems in other languages, will I find any working as you expect it to work and not like npm or (when fixed) yarn? If so, do they have a good example/reason for doing so? But AFAIK everyone in a set of different language would install the wrong dependency, when you set it like that.

You said it should be resolved by package manager, but I disagree, because a package manager can not resolve correct version if you tell that every version is okay. There is no information in your package.json, which could give any package manager a hint what version to install actually.

The only way currently is, to mess around with vendor dependencies in my root package.json, which is anti-pattern sets the whole concept upside-down.

**Comment by akomm** [comment]
@alloy

I feel either I misunderstand something terribly or you did not read my answer correctly. You are talking about yarn. I am talking about how this is also an issue with NPM, simply because * is a wrong constraint, while completely understand the current DT situation as reason why you can not do yet anything about it. If you agree on this, probably you can skip the further text! :D

However why I am stil taking about is the decision whether its an issue on DT side or not and for that its important to understand whether something is wrong or not.

So again, currently running `npm install @types/react-relay@^1.3.12` would install `@types/relay-runtime@5.0.0`, which is wrong version of the dependency. AFAIK this is not NPM bug but how it is intended to work. Simply because the constraint is `any`. While your different interpretation of `*` might also make sense in a different world with different definition, it is not how npm or (fixed) yarn work. From package management point of view, one of the core ideas is, that I do not have to mess around with what versions of certain packages third party packages need. Only if there is a conflict between two root dependencies I have in my project. If everyone would make packages like that it would be hell on earth. Except its an optional dependency (like an ORM package and then different DBALs). There are however concept how, in case you do install a DBAL the correct version is also resolved in that case, but this gets out of scope now.

TO widen the thinking proccess, I asked myself the question: if I glance at other package management systems in other languages, will I find any working as you expect it to work and not like npm or (when fixed) yarn? If so, do they have a good example/reason for doing so? But AFAIK everyone in a set of different language would install the wrong dependency, when you set it like that.

You said it should be resolved by package manager, but I disagree, because a package manager can not resolve correct version if you tell that every version is okay. There is no information in your package.json, which could give any package manager a hint what version to install actually.

The only way currently is, to mess around with vendor dependencies in my root package.json, which is anti-pattern sets the whole concept upside-down.
