### ISSUE TITLE
[@types/leaflet] Declaration merging of Namespace and Class causing issues with extends

### ISSUE THREAD

**Issue by Bored-Bohr** [DefinitelyTyped/DefinitelyTyped#36404]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/leaflet` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alejo90 @atd-schubert 

If you do not mention the authors the issue will be ignored.

Many namespaces and classes share the same name, so they are subject to [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html).

This causes issues when using Class.extend because it expects functions from the namespace to extended as well.

For example:
```typescript
declare module 'leaflet' {
    namespace Control {
        class CustomControl extends Control {
            constructor(options: CustomOptions);
        }
    }
    namespace control {
        function customControl(options: CustomOptions): Control.CustomControl;
    }
}

L.Control.CustomControl = L.Control.extend({
    ...
});
```
throws a typescript error: 
`Type '(new (...args: any[]) => any) & typeof Class' is missing the following properties from type 'typeof CustomControl': Zoom, Attribution, Layers, Scale, and 6 more.`

I originally submitted this as a [StackOverflow post](https://stackoverflow.com/questions/56639406/how-to-define-the-type-of-a-custom-leaflet-control), but realized that this is actually an issue with `@types/leaflet` since this breaks functionality when essentially copying code directly from within leaflet.

**Comment by achmedzhanov** [comment]
Created [https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36650](pull request) with fix

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
