### ISSUE TITLE
[@types/react-orm] Argument of type ... is not assignable to parameter of type 'never'.

### ISSUE THREAD

**Issue by ksweetie** [DefinitelyTyped/DefinitelyTyped#36426]
I'm getting `Argument of type ... is not assignable to parameter of type 'never'.` when trying to use either `withId` or `idExists` on a Model.

<img width="1023" alt="Screen Shot 2019-06-24 at 11 47 08 PM" src="https://user-images.githubusercontent.com/2036284/60074042-415d0780-96df-11e9-995c-67fa0b7a951e.png">

If I change:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f6da6d304ac2b5ec838afe5db250d9d7820b8ad7/types/redux-orm/Model.d.ts#L454

to:

```
withId(id: number): SessionBoundModel<M> | null; 
```

the error goes away. Am I doing something wrong? Thanks for all your work on these typings @tomasz-zablocki!

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomasz-zablocki

**Comment by tomasz-zablocki** [comment]
Hi,

`IdType<M>` should figure out the type to be either `string` or `number`. 
Apparently it did not, so it's either a bug in my typings, something in your Models that I had not anticipated while creating them or some minor issue in your models.

I'd need a broader context (the model class/field mappings) to investigate an issue. Could you provide more code, so that I can look into it ?

**Comment by ksweetie** [comment]
The only other part that looks relevant is the Model definition, which is:

```
export class PaymentSchedule extends Model { }
PaymentSchedule.modelName = 'PaymentSchedule'
```

**Comment by tomasz-zablocki** [comment]
try this:

```
export class PaymentSchedule extends Model<typeof PaymentSchedule> { }
PaymentSchedule.modelName = 'PaymentSchedule'
```

A heads up - since you've placed the model name outside the class body: when declaring fields, you'll need to place them inside the `PaymentSchedule` class body, like this:

```
export class PaymentSchedule extends Model<typeof PaymentSchedule> { 
  static fields = {
    //... field declarations
  }
}
PaymentSchedule.modelName = 'PaymentSchedule'
```

Placing them outside of the class body breaks the inference of `IdKey/IdType` and several other typing features.

I know this `<typeof 'ClassName'>` construct may seem redundant, but it's the most concise way I've found to retain the constructor function type on the class instances. There's an ongoing issue (I think since 2016), for a static `this` return type which would make that type parameter obsolete, but it seems to be slightly controversial if I remember correctly.

**Comment by tomasz-zablocki** [comment]
You can also take a look at the redux-orm-tests.ts file, there are several examples of declaring field interfaces, using `MutableQuerySet` etc.

**Comment by ksweetie** [comment]
Adding `<typeof PaymentSchedule>` didn't do it for me, but your suggestion to look at `redux-orm-tests.ts` was a huge help. I ended up adding the reducer as a `static reducer` inside the model definition, and that fixed everything. I defined the reducer outside of the model originally because of this line in the README:

```
Previously we advocated for reducers specific to Models by attaching a static reducer function on the Model class.
```

That makes it sound like the practice is discouraged going forward, though now I'm not sure.

Anyway, I really appreciate your help and super fast responses. Thank you! 🙏

**Comment by tomasz-zablocki** [comment]
I'll have to see whether the standalone, separate reducer, disconnected from any specific Model class can be defined in TypeScript using current typings. Thank you for hinting this, there might be an issue here.

**Comment by ksweetie** [comment]
I think I spoke too soon. I'm able to use `withId` inside of the model, but not from outside when I get the model via the session.

<img width="1008" alt="Screen Shot 2019-07-09 at 10 43 14 AM" src="https://user-images.githubusercontent.com/2036284/60907322-808a6d00-a236-11e9-9a2f-af8fdbd76aa9.png">

<img width="509" alt="Screen Shot 2019-07-09 at 10 52 26 AM" src="https://user-images.githubusercontent.com/2036284/60907825-b5e38a80-a237-11e9-8b15-b9d6184d203b.png">

<img width="726" alt="Screen Shot 2019-07-09 at 10 52 39 AM" src="https://user-images.githubusercontent.com/2036284/60907842-c0058900-a237-11e9-9140-614580088f6d.png">

As you can see, the not-working code is getting the type `ModelType<any>` while inside the model it gets `ModelType<PaymentSchedule>`. The selector to get the session looks like this:

```
import { createSelector } from 'reselect'

import orm, { RootStateType } from 'client/redux/orm'

export const selectEntities = (state): RootStateType => state.entities

export const getEntitiesSession = createSelector(
  selectEntities,
  entities => orm.session(entities),
)
```

Any ideas to fix this? Thanks @tomasz-zablocki!

**Comment by tomasz-zablocki** [comment]
@kwestie, your `createSelector` import seems wrong. You should use the special `createSelector` function from redux-orm. They can be combined with reselect selectors, but unless I'm missing something, you won't get `Session` combiner without redux-orm createSelector. 

If you had intended to use redux-orm selectors, then your inputs are wrong. createSelector can be invoked in two different ways. The lib docs are a bit confusing in this area.

I've submitted a PR to redux-orm types, which is generally selector related. It should be merged soon, along with the usual test file examples.

#36738  

I'm a bit concerned about withId causing you problems. Let me know if the selector thing is clear,  I'll take a look If the issue persists

**Comment by tomasz-zablocki** [comment]
You should be already able to update types from npm

**Comment by tomasz-zablocki** [comment]
@ksweetie is everything fine now ? Can we close this issue ?

**Comment by ksweetie** [comment]
@tomasz-zablocki Unfortunately, I ended up just getting rid of `redux-orm`. I was spinning my wheels with this for too long. It was probably my fault and not the library's or the typings, but I just spent too much time on it to justify continuing to try to fix it. Thank you for all of your support though, I really appreciate it!

**Comment by tomasz-zablocki** [comment]
@ksweetie, I'm very sorry to hear that. 

In all honesty, I'd heavily regret if my flawed delivery had made someone miss on **redux-orm** and all the convenience that comes with it.

I'd really appreciate, if you could share the problematic sources, but I expect you may had enough. :(
