### ISSUE TITLE
[@types/mongoose] omitUndefined option is missing

### ISSUE THREAD

**Issue by canvural** [DefinitelyTyped/DefinitelyTyped#36437]
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi
@lukasz-zak 
@Alorel
@jendrikw
@ethanresnick
@vologab
@jussikinnula
@ondratra
@alfirin
@idandrd
@various89
@Fazendaaa
@NormanPerrin
@danmana
@stablio
@emmanuelgautier
@frontendmonster
@mingchen
@penumbra1
@orblazer
@HughKu
@niuware
@vladmel1234
@jloveridge 

From the [docs](https://mongoosejs.com/docs/api.html#query_Query-setOptions):

> The following options are only for write operations: update(), updateOne(), updateMany(), replaceOne(), findOneAndUpdate(), and findByIdAndUpdate():
    upsert
    writeConcern
    timestamps: If timestamps is set in the schema, set this option to false to skip timestamps for that particular update. Has no effect if timestamps is not enabled in the schema options.
    omitUndefined: delete any properties whose value is undefined when casting an update. In other words, if this is set, Mongoose will delete baz from the update in Model.updateOne({}, { foo: 'bar', baz: undefined }) before sending the update to the server.

`omitUndefined` option is not in the type definition.

**Comment by welljsjs** [comment]
@sandersn @rbuckton @dinodeSimon @tomyam1 @amcasey @kerolloz @nacimgoura @sheetalkamat @borfig @ToucheSir @weswigham @PabloSzx @richarddd @andrewbranch @armanio123 @esetnik @RyanCavanaugh 

Could so care about this? It's September now and this issue was created in June.

**Comment by sandersn** [comment]
@welljsjs Definitely Typed is community-driven, so if you need a definition, you can add it yourself. 

Our PR process is highly automated so once it gets past the bot it is usually 1-2 days before it's published to npm.

**Comment by welljsjs** [comment]
Alright, thanks. Will do.
