### ISSUE TITLE
[@types/stripe] 6.30.3 requested_capabilities missing in create account

### ISSUE THREAD

**Issue by shadow1349** [DefinitelyTyped/DefinitelyTyped#36454]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/string` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wjohnsto @CodeAnimal @sampsonjoliver @LinusU @brannon @kkamperschroer @starhoshi @bruun @galtalmor @htunnicliff @squirly @tzarger @ifiokjr @yultyyev @cpsoinos @adamduren @saranshkataria @0xJoKe @delianides @gokulchandra @viralpickaxe @chrisleck @spacetag 

If you do not mention the authors the issue will be ignored.

When I try to create a Connect Account it does not recognize the requested_capabilities option (I get an error, see below) however this is a required option (https://stripe.com/docs/upgrades#2019-02-19).

ERROR: `Object literal may only specify known properties, and 'requested_capabilites' does not exist in type 'IAccountCreationOptions'`.

To reproduce:

```typescript
/**
 * "@types/stripe": "^6.30.3"
 * "stripe": "^7.3.0"
 */


import * as stripe from 'stripe';

const client = new stripe('mykey');
client.setApiVersion('2019-05-16');

const dob = new Date(1980, 1, 1);
(async () => {
  const act = await client.accounts.create({
    email: 'jd@email.com',
    country: 'US',
    type: 'custom',
    business_profile: {
      name: 'John Doe',
      support_email: 'jd@gmail.com',
      support_phone: '1231231234',
      support_url: 'https://mtwebsite.com',
      product_description: 'My Description'
    },
    metadata: {
      id: '123abc'
    },
    business_type: 'individual',
    individual: {
      address: {
        city: 'Seattle',
        country: 'US',
        line1: '123 Main St',
        line2: 'UNIT 1',
        postal_code: '123456',
        state: 'WA'
      },
      dob: {
        day: dob.getDate(),
        month: dob.getMonth(),
        year: dob.getFullYear()
      },
      first_name: 'John',
      last_name: 'Doe',
      phone: '1231231234'
    },
    requested_capabilities: ['platform_payments'], // <= ERROR
    tos_acceptance: {
      date: Math.floor(Date.now() / 1000),
      ip: '8.8.8.8'
    }
  });
})();
```

For now, I have been able to use this work around:

```
  const opts: stripe.account.IAccountCreationOptions = {
    email: 'jd@email.com',
    country: 'US',
    type: 'custom',
    business_profile: {
      name: 'John Doe',
      support_email: 'jd@gmail.com',
      support_phone: '1231231234',
      support_url: 'https://mtwebsite.com',
      product_description: 'My Description'
    },
    metadata: {
      id: '123abc'
    },
    business_type: 'individual',
    individual: {
      address: {
        city: 'Seattle',
        country: 'US',
        line1: '123 Main St',
        line2: 'UNIT 1',
        postal_code: '123456',
        state: 'WA'
      },
      dob: {
        day: dob.getDate(),
        month: dob.getMonth(),
        year: dob.getFullYear()
      },
      first_name: 'John',
      last_name: 'Doe',
      phone: '1231231234'
    },
    tos_acceptance: {
      date: Math.floor(Date.now() / 1000),
      ip: '8.8.8.8'
    }
  };

  opts['requested_capabilities'] = ['platform_payments']

  const act = await client.accounts.create(opts);
```

However, I think this is something that really needs to be resolved quickly, as this is a required option now.

**Comment by shadow1349** [comment]
Now that I'm using it a bit more, the `requirements` property is also missing from `stripe.accounts.IAccount`

**Comment by shadow1349** [comment]
`stripe.accounts.IAccount` is also missing 

* status
* details 
* details_code

**Comment by TheBigBiggerRice** [comment]
Any updates on this issue? A custom connect account has to be created with requested capabilities , and the above work around did not work for me.

**Comment by shadow1349** [comment]
@TheBigBiggerRice You can use my workaround, but I haven't heard anything about an actual fix.
