### ISSUE TITLE
[@types/node] http.AgentOptions should extend net.SocketConnectOpts

### ISSUE THREAD

**Issue by Jiia** [DefinitelyTyped/DefinitelyTyped#36463]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:
@DefinitelyTyped
@parambirs
@tellnes
@WilcoBakker
@smac89
@Flarna
@mwiktorczyk
@wwwy3y3
@DeividasBakanas
@kjin
@alvis
@eps1lon
@Hannes-Magnusson-CK
@jkomyno
@ajafff
@hoo29
@n-e
@brunoscheufler
@mohsen1
@KSXGitHub
@a-tarasyuk
@islishude
@r3nya
@ZaneHannanAU
@eyqs

According to [http documentation](https://nodejs.org/api/http.html#http_new_agent_options), the  constructor for `http.Agent` accepts an `options` object as the first argument and:

> options in socket.connect() are also supported

However the interface `http.AgentOptions` does not extend `net.SocketConnectOpts`.

I would have created a PR, but it turns out `https.AgentOptions` extends `http.AgentOptions` and `tls.ConnectionOptions` which then would have conflicting type definitions for `path` and `port`.

In `net.SocketConnectOpts` the properties `path` and `port` are required. However in `tls.ConnectionOptions` they are optional.

I'm uncertain how to correctly resolve the conflict.

**Comment by KSXGitHub** [comment]
> options in `socket.connect()` are also supported

It is supported but optional, this means that we should not use `extends`, but instead, we should use join and `Partial`.

**Comment by SimonSchick** [comment]
`Partial` isn't supported in the minimum required node version so this would involve a bunch of copy/paste.
@rbuckton are there any plans to bump up the minimum TS version across the board, there are quite a few things we can't type property or only via hacks due to this 😢

**Comment by xzyfer** [comment]
What's the way to work around this in userland?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
