### ISSUE TITLE
[@types/storybook__react-native] is missing types that are on @types/storybook__react

### ISSUE THREAD

**Issue by dccarmo** [DefinitelyTyped/DefinitelyTyped#36472]
I noticed this when importing `storiesOf`.

If I do this: `import { storiesOf } from '@storybook/react-native';`

VSCode gets the type from `node_modules/@storybook/react-native/dist/index.d.ts`

Whilst if I do this: `import { storiesOf } from '@storybook/react';`

It gets the correct type, but then my stories stop working.

Here are the versions I have:

```
"@storybook/react-native": "^5.1.9",
"@types/storybook__react-native": "^3.0.5",
```

Authors:
@joscha 
@wapgear 
@alechill 
@iRoachie 
@ceyhun

**Comment by joscha** [comment]
haven't used the react-native package before - can you produce a test that fails? I think the versions might be off, I can see a 5x on the storybook part but a 3x on the types.

**Comment by dccarmo** [comment]
@joscha Sorry, I don't think I know how to produce a typing test. How can I do that?

And it seems to me that it's only the case of copying and pasting what's on `@types/storybook__react`.

**Comment by joscha** [comment]
> @joscha Sorry, I don't think I know how to produce a typing test. How can I do that?

just a snippet of code and a command to transpile it

**Comment by dccarmo** [comment]
```
import React from 'react';
import { Text, View } from 'react-native';
import { storiesOf } from '@storybook/react-native';

storiesOf('Test View', module)
  .addDecorator(getStory => <View>{getStory()}</View>)
  .add('default', () => <Text>Test</Text>);
```

This should give you the error I'm talking about.

**Comment by roylau134** [comment]
any fix ?_?

**Comment by roylau134** [comment]
![image](https://user-images.githubusercontent.com/29243184/89898927-1780e000-dc14-11ea-92b4-509480dccf66.png)

```tsx
import { storiesOf } from '@storybook/react-native';

export default (storyName: string) => 
  storiesOf(storyName, module).addDecorator((storyFn) => (storyFn()));
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
