### ISSUE TITLE
[react] [react-dom] Add ConcurrentMode / unstable_createRoot

### ISSUE THREAD

**Issue by brunolemos** [DefinitelyTyped/DefinitelyTyped#36475]
I haven't used concurrent mode yet but noticed it isn't included in the type definitions.

I have the impression `unstable_ConcurrentMode` has been removed and now it's only `unstable_createRoot`, but not sure. See commit: https://github.com/facebook/react/commit/83fc258f2914c1a7c14c7b98ee362934576f266b

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Jessidhia, @eps1lon, @sandersn, @justjavac

**Comment by airhorns** [comment]
Is this a wontfix or just a small bit of work someone needs to do?

**Comment by eps1lon** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/experimental.d.ts explains how to get typings for `react@experimental`:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d952b3927e2b7b31eb285b8f10fc69ce04a2c6cc/types/react/experimental.d.ts#L1-L25

@brunolemos Would you be so kind and close this issue? We forgot to link this issue when we added the types in #39416
