### ISSUE TITLE
[@types/react-dates] renderCalendarDay prop type declaration incorrect

### ISSUE THREAD

**Issue by wkirby** [DefinitelyTyped/DefinitelyTyped#36501]
If you know how to fix the issue, make a pull request instead.

- [X ] I tried using the `@types/react-dates` package and had problems.
- [X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ArturAmpilogov, @NathanNZ 

If you do not mention the authors the issue will be ignored.

The type definition for `renderCalendarDay` appears to be incorrect.

```ts
renderCalendarDay?: (day: momentPropTypes.momentObj) => string | JSX.Element;
```

While the most recent source code for react-dates passes in a much more complext `props` object: https://github.com/airbnb/react-dates/blob/v20.2.5/src/components/CalendarMonth.jsx#L223-L239

**Comment by mehrad77** [comment]
I would confirm this is a issue
