### ISSUE TITLE
[@types/yup] concat() method in Schema<T> has wrong parameters

### ISSUE THREAD

**Issue by emiliskiskis** [DefinitelyTyped/DefinitelyTyped#36555]
- [x] I tried using the `@types/yup` package and had problems.
- [x] I tried using the latest stable version of tsc (3.5.2). https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dhardtke @vtserman @MoretonBayRC @sseppola @YashdalfTheGray @vincentjames501 @robertbullen @sat0yu @dancrumb @deskoh @mauricedb 

Right now, the concat method looks like this:
```
export interface Schema<T> {
    ...
    concat(schema: this): this;
    ...
}
```
That means, if you have an ObjectSchema with many different values, the T parameter will be all of those values with their types, making it impossible to concatenate two ObjectSchemas (which is possible according to yup documentation, mixed.concat()) with different keys.

Maybe the solution could be something like:
```
concat<E>(schema: this | ObjectSchema<E>): this | ObjectSchema<T & E>
```

Thank you for your contribution and help.

**Comment by YashdalfTheGray** [comment]
@emiliskiskis what you're saying definitely sounds correct. I checked the code to find the signature in case `.concat()` worked like the one on `Array.prototype` but it seems like it only takes in a single schema. I agree that we should change `concat(schema: this): this` to `concat<U>(schema: this | ObjectSchema<U>): this | ObjectSchema<T & U>`. 

Wanna turn in a PR?

**Comment by emiliskiskis** [comment]
@YashdalfTheGray Hey, I turned in the PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36577), but apparently I need to have the U generic type be in constraints of `object | null | undefined`, and it definitely isn't, but I kinda need it not to. I'm new to TS, what do you suggest to do?

**Comment by mauricedb** [comment]
@emiliskiskis 	

If I am not mistaken the following test addresses your issue:
```TypeScript
const partAShema = yup.object({
    a: yup.string()
});

const partBSchema = yup.object({
    b: yup.string()
});

const bothPartsSchema = partAShema.concat(partBSchema); // $ExpectType ObjectSchema<{ a: string; } & { b: string; }>
```

That test would be satisfied by adding the following to `ObjectSchema`:
```TypeScript
    concat(schema: this): this;
    concat<U extends object>(schema: ObjectSchema<U>): ObjectSchema<T & U>;
```

With one additional change: Setting the minimal TypeScript version to 2.9. Given that 2.9 was released a year ago and we are now at 3.5.2 I personally don't see an big issue with this updated requirement.

You can see the [commit here](https://github.com/mauricedb/DefinitelyTyped/commit/ec858e9e7e85aead04878672d81470cbec1e911c)

**Comment by emiliskiskis** [comment]
@mauricedb That's great, it looks like it'll solve the issue. Except can we expect `ObjectSchema<${ a: string; b: string; }>`, or is that not the same as with an intersecting type?

Thanks for your help.

**Comment by YashdalfTheGray** [comment]
We can expect what you said @emiliskiskis too, or you should be able to. In some sense @sseppola's test case covers what the schema is written to provide so it should always pass the test but I don't know how far DefinitelyTyped type tester resolves types before it does the check.

**Comment by mauricedb** [comment]
@emiliskiskis @YashdalfTheGray 	

The resulting types `ObjectSchema<{ a: string; } & { b: string; }>` or `ObjectSchema<{ a: string; b: string; }>` are functionally the same here. Now that is not always as simple as this. There is some interesting behavior here when there are overlapping properties though. Not quite sure what the rules for intersection types are but not seeing what I was expecting like the resulting type for `c` in `T2` and `T3`.

```TypeScript
type T1 = { a: string } & { b: string };
// Equivalent to: type T1 = { a: string; b: string; }

type T2 = { a: string; c: string } & { b: string; c: boolean };
// Equivalent to: type T2 = { a: string; b: string; c: never }

type T3 = { a: string; c: string } & { b: string; c: number };
// Equivalent to: type T3 = { a: string; b: string; c: string & number }
```

See the [TypeScript playground ](http://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAKgjFAvFA3lAhgLigZ2AJwEsA7AcygF8oAyVKAI2zyLMoG4AoAei6gFEAjgFdCAN3QAbCMWBRgAe2yhIsBMjRZcBEqTYMm2snoocOy6DABMSOpuY69AYwMtyVWmkZbXT7PXnyUujE7Ny8giLiUjJyinLgFtbqGC4O+t5pzlDEEKIQ+JSm5rAAzDYaqUZQWfas7nRetbrV2MRCALb0+aE8-MJiktKyCkoJpeUpGVWNhs01szTZHV0FJhyO8sR4cnDY8OUcUJMARMcANIfppxwUnOub28CWe0mol5qnF0den5dZ17dTBstsMSnsyup3thft9oec-nCbpwgA)here.

**Comment by emiliskiskis** [comment]
@YashdalfTheGray 
@mauricedb That's a great playground, I'll use it more often now. So, who will do the honours of the PR?

**Comment by mauricedb** [comment]
@emiliskiskis You started the PR so I will defer to you. Feel free to finish the PR if you want to. If not that is fine too, just let me know and I will create a new PR based on the commit I linked to before.

**Comment by YashdalfTheGray** [comment]
So I'm trying to figure out what behavior we want from the types because yup does a prepend on the schemas and it seems like if the target of the concat call is the new schema that you pass into the `schema.concat` call. 

I'll refer to the concat call schema as `this` and the new schema passed in as `arg`. If you look at the code [here][1], you can see that the line that we're most interested in is on line 125. Digging a little bit more into the code [here][2], you can see that if the `arg` has a property defined on it, that takes precedence over `this`. We would want the types to reflect this too I think. 

I think the problem with that is that the intersection type is kind of a best-effort thing from Typescript to represent what happens when you actually have an `Object.assign` type situation. What we really need is a safe way to merge the types but make sure that `arg`'s properties take precedence over `this`'s properties. 

We almost need something like [`Spread<L, R>`][3] here so that we can make sure that the types flow correctly. 

[1]:https://github.com/jquense/yup/blob/master/src/mixed.js#L115
[2]:https://github.com/jquense/yup/blob/master/src/util/prependDeep.js#L6
[3]:https://stackoverflow.com/questions/49682569/typescript-merge-object-types

**Comment by mauricedb** [comment]
@YashdalfTheGray 

Nice one, didn't know about the `Spread<L, R>`. I am sure I can use that some time in the future 👍

But I don't think we need it in this case as Yup will actually throw a runtime error if you combine different types. For example the following code:

```TypeScript
const stringNumber = yup.object({
  a: yup.string(),
  b: yup.number()
})

const stringBoolean = yup.object({
  a: yup.string(),
  b: yup.boolean()
})

const mixed = stringNumber.concat(stringBoolean)
```

This will throw an error `TypeError: You cannot `concat()` schema's of different types: number and boolean` [here](https://github.com/jquense/yup/blob/master/src/mixed.js#L119). This will only work if you define the `stringNumber.b` as `yup.mixed()`.

As result I think that using an intersection type that results in the type for `mixed.b` being `never` is appropriate. The only challenge I see is getting the type correct for the `yup.mixed()` case.

**Comment by YashdalfTheGray** [comment]
Yeah so that's what I was considering with the Spread thing that I suggested. We'd wanna handle the mixed case but if you think we can do it a different way, I'm down. 

Sorry no formatting because on phone.

**Comment by mauricedb** [comment]
Right but as far as I can tell the `Spread<L, R>` doesn't help there either. If there are matching keys the last one wins and it's type is used. So kind of like `Object.assign()` which is not how Yup works at all.

I agree about wanting to handle the mixed case as well, just not sure on how. Need to experiment here but don't have the time right now.

**Comment by YashdalfTheGray** [comment]
From the code it looks it is actually working like Object.assign, at least the prepend function in the utils for yup. But I took a cursory look this morning, I might be off in my understanding. And since it is working like Object.assign, I thought Spread would work.

**Comment by emiliskiskis** [comment]
Wow, never thought one line of code would provoke such a conversation. Maybe we should tag yup's author for consulting, would that help?

**Comment by YashdalfTheGray** [comment]
Haha. Well I wanna make sure that we get the right types out of concat() since we've got it wrong in the past.

I'm not opposed to quick fixing it but then we'll have to come back to the same issue once we get another issue saying that the types for `concat` don't work for `mixed`. That's not to say that I don't support that if that's the decision we make.

**Comment by emiliskiskis** [comment]
Don't want to leave this on hold forever... Is there a way to detect when types of same keys are intersecting (except when they're mixed), so we can prevent the runtime error, but allow the intended behavior?

**Comment by mauricedb** [comment]
Spent more time trying to fix this but not 100% successful. See the note at the bottom of [the PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36702) about the open item. Not sure how to fix this. I tried several approaches but non of them worked.
