### ISSUE TITLE
[@types/yup] - Type 'Ref' is not assignable to type 'string'

### ISSUE THREAD

**Issue by guillaumepn** [DefinitelyTyped/DefinitelyTyped#36579]
- [x] I tried using the `@types/yup` package and had problems.
- [ ] I tried using the latest stable version of tsc. (I'm using v3.3) https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  
- [x] [Mention] the authors so they can respond.
  - Authors: @dhardtke, @vtserman, @MoretonBayRC, @sseppola, @YashdalfTheGray, @vincentjames501, @robertbullen, @sat0yu, @dancrumb, @deskoh, @mauricedb

The latest version (0.26.19) made my CD pipeline crash with the following error : 
`TS2322: Type 'Ref' is not assignable to type 'string'.`

I'm guessing it comes from the latest version because the previous one was released 5 days ago and I did several pipelines since then that went fine

Here is the the line in my code that triggers this: 

`confirmPassword: yup.string().oneOf([yup.ref("password"), null], passwordMismatch[lang])`

I think this error shouldn't be thrown, as the Yup docs mention that `.ref` is expecting a string parameter

**Comment by mauricedb** [comment]
@guillaumepn 

Yes, agreed that should work.

With one little addition given that you are using `null` in `oneOf()` as well. So I changed the definition to include `nullable()` like this:
```TypeScript
confirmPassword: yup.string().nullable().oneOf([yup.ref("password"), null]),
```

**Comment by guillaumepn** [comment]
Thanks!
