### ISSUE TITLE
Unable to use Angular-route when not using module loader

### ISSUE THREAD

**Issue by quintonn** [DefinitelyTyped/DefinitelyTyped#36621]
I tried using '@types/angular-route' package.
I add a reference to angular and angular-route as follows in my typescript file:

> /// reference path="typings/angular/angular.d.ts" 
> /// reference path="typings/angular/angular-route.d.ts"
(I've remove angle brackets above not to break the markdown)

I'm not using imports because i don't want to use a module loader or anything like that.
I also don't want to use build tools other than visual studio and typescript (that should run automatically in visual studio).

I placed the d.ts files in my scripts folder under a typings sub-folder.
In my file the following line gives an errorL
> ng.route.IRouteProvider

This is the error:
> Angular has no exported member 'route'

I created a [stackoverflow ](https://stackoverflow.com/questions/56872655/typescript-error-angular-has-not-exported-member-route) question with a bit more details,

@gkalpak @park9140

**Comment by gkalpak** [comment]
I have no idea oof the top of my head, @quinton, sorry 😞
Sharing a minimal reproduction generally helps investigate :wink:

**Comment by quintonn** [comment]
I was looking at some of the other angular types (I.e. angular-jwt) and they have different code at the top of their file:

I tried to change the angular-route file to be similar to that but it still didn’t work.

 

But I manage to get it working for me as follows:

 

// TypeScript Version: 2.3

 

declare var _: string;

//export = _;

 

/// <reference path="angular.d.ts" />

 

export as namespace angularroute;

export = angularroute;

 

declare module angularroute {

    ///////////////////////////////////////////////////////////////////////////////

    // ngRoute module (angular-route.js)

    ///////////////////////////////////////////////////////////////////////////////

    export namespace route

 

Not sure if this will break module loaders and stuff like that, I have no experience with that.
But it’s working for me locally with Visual studio 2019 and TypeScript.

 

I’m sorry if this doesn’t help solve the problem, I don’t really know how to debug it to be honest.

 

Thanks

Quintonn

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
