### ISSUE TITLE
[@types/ioredis] Expose sentinelRetryStrategy in redis.options

### ISSUE THREAD

**Issue by rohitsud** [DefinitelyTyped/DefinitelyTyped#36736]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Currently `Redis.defaultOptions` has `sentinelRetryStrategy` set but this cannot be overwritten by passing an `options.sentinelRetryStrategy`. We need a way to overwrite it the same way `retryStrategy` can be overwritten.

**Comment by lschricke** [comment]
Hey @rohitsud, 
I'm experiencing the same issue you described above. As you closed this issue, I suppose you found a solution? I'll be glad to hear it if you you have some time.

Thanks!
