### ISSUE TITLE
oauth2-server.default is not a constructor

### ISSUE THREAD

**Issue by carlosen14** [DefinitelyTyped/DefinitelyTyped#36767]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@vangorra 
@cirick 
@d-fischer 
@rvitorsantos 

If you do not mention the authors the issue will be ignored.

Using like this. 
```js
import { OAuth2Server, ServerOptions } from 'oauth2-server'
const options: ServerOptions = {
  model: model,
  requireClientAuthentication: {
    "client_credentials": true,
    "password": false,
    "authorizationCode": true
  }
}
const oauth = new OAuth2Server(options) // << Error here
```

I am having this error, really don't know if is `tsc` or `@types` related.
```js
var oauth = new oauth2_server_1["default"]({
            ^
source-map-support.js:445
TypeError: oauth2_server_1.default is not a constructor
```

Here is the index.d.ts file, where is OAuth2Server class and it's constructor.
```js
declare class OAuth2Server {
    static OAuth2Server: typeof OAuth2Server; 

    /**
     * Instantiates OAuth2Server using the supplied model
     *
     * @param options
     */
    constructor(options: OAuth2Server.ServerOptions);
```

Also, why is @types/oauth2-server version behind the 'original' pkg?, Is't supposed to be paired?.

**Comment by koocbor** [comment]
Changing the import statement to:

```typescript
import OAuth2Server = require('oauth2-server');
import { ServerOptions } from 'oauth2-server';

const options: ServerOptions = {
  model: model,
  requireClientAuthentication: {
    "client_credentials": true,
    "password": false,
    "authorizationCode": true
  }
}
const oauth = new OAuth2Server(options)

```

corrects this error.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
