### ISSUE TITLE
I think there should be typeof variable in @types/boom. 

### ISSUE THREAD

**Issue by bugtype** [DefinitelyTyped/DefinitelyTyped#36781]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

@rogatty @AJamesPhillips @jineshshah36 @TimonVS @danielmachado 

https://github.com/hapijs/boom/blob/master/API.md
I think the boom object should have typeof.
typeof - the constructor used to create the error (e.g. Boom.badRequest).

```typescript
declare class Boom<Data = any> extends Error {
    /** Creates a new Boom object using the provided message and then calling boomify() to decorate the error with the Boom properties. */
    constructor(message?: string | Error, options?: Boom.Options<Data>);
    /** isBoom - if true, indicates this is a Boom object instance. */
    isBoom: boolean;
    /** isServer - convenience bool indicating status code >= 500. */
    isServer: boolean;
    /** message - the error message. */
    message: string;
    /** output - the formatted response. Can be directly manipulated after object construction to return a custom error response. Allowed root keys: */
    output: Boom.Output;
    /** reformat() - rebuilds error.output using the other object properties. */
    reformat(): string;
    /**
     * "If message is unset, the 'error' segment of the header will not be present and
     * isMissing will be true on the error object." mentioned in
     * @see {@link https://github.com/hapijs/boom#boomunauthorizedmessage-scheme-attributes}
     */
    isMissing?: boolean;
    /** https://github.com/hapijs/boom#createstatuscode-message-data and https://github.com/hapijs/boom/blob/v4.3.0/lib/index.js#L99 */
    data: Data;
}
```
typeof: internals.Boom?

**Comment by AJamesPhillips** [comment]
@bugtype sorry I can't help you. Am not working on this at the moment.

**Comment by SimonSchick** [comment]
Can you please be concise on what you want here?

**Comment by bugtype** [comment]
```typescript
const error = Boom.badData();
error.typeof // not working
```

I think that can use typeof in Boom.
I want to use this.
```typescript
const error = Boom.badData();
expect(error.typeof).to.equal(Boom.badData());
```


but it is not working in intellisense.
that is not showing.

<img width="310" alt="screenshot" src="https://user-images.githubusercontent.com/24269591/61012281-ca02c580-a3b8-11e9-89ce-9647e712c07e.png">

Am I using it wrong?

**Comment by SimonSchick** [comment]
Oh, I thought you were referring to the `typeof` operator, yea I guess we should add `readonly typeof: Function`

**Comment by bugtype** [comment]
Thank you!

**Comment by SneakyFish5** [comment]
Does this work for you @bugtype? https://github.com/SneakyFish5/DefinitelyTyped/commit/10841a149f19e816471b6c94fc8c9aca3fe9393e

**Comment by SimonSchick** [comment]
Should probably be `readonly`.

**Comment by SneakyFish5** [comment]
`ERROR: 30:22  ban-types  Don't use 'Function' as a type. Avoid using the `Function` type. Prefer a specific function type, like '() => void.'`

I get the above message when running `npm test`, however I don't think `() => void` works in this case because the function does return something as far as I can see from the example. Is there a different option you know of?

**Comment by AJamesPhillips** [comment]
You could use: `readonly typeof: () => any;` @SneakyFish5

**Comment by SimonSchick** [comment]
Rather `(message?: string, data?: any, ...extra: any[])`, kinda hard/annoying to type, that's why it wasn't initially added.
