### ISSUE TITLE
js-yaml incorrect safeLoad return type

### ISSUE THREAD

**Issue by fabiospampinato** [DefinitelyTyped/DefinitelyTyped#36807]
- Authors: @Bartvds @sclausen

`js-yaml`'s `safeLoad` function had a self-reported return type that was actually wrong, this has been fixed in the main repo https://github.com/nodeca/js-yaml/pull/508, the declaration file should be updated too.

**Comment by SneakyFish5** [comment]
`safeLoad`'s return type is already `any`, so I don't think there is a need to update it.

**Comment by fabiospampinato** [comment]
Well the return type isn't actually `any`, it seems that it returns either a string, undefined or a plain object.

**Comment by SneakyFish5** [comment]
So instead of `export function safeLoad(str: string, opts?: LoadOptions): any;` you'd want `export function safeLoad(str: string, opts?: LoadOptions): string | undefined | object;`?

**Comment by fabiospampinato** [comment]
Yes exactly.

Also if there are other `any`s being used this might be a good time to remove them and make the declaration stricter.

**Comment by SneakyFish5** [comment]
I've changed `load` to `export function load(str: string, opts?: LoadOptions): string | undefined | object;` as well.

There is this line of code with a bunch of functions that, (from my understanding of the documentation), should still return the same thing as safeLoad however it's written kind of oddly. Maybe you could make sense of it?

```
export function safeLoadAll(str: string, iterator?: undefined, opts?: LoadOptions): any[];
export function safeLoadAll(str: string, iterator: (doc: any) => void, opts?: LoadOptions): undefined;

export function loadAll(str: string, iterator?: undefined, opts?: LoadOptions): any[];

export function loadAll(str: string, iterator: (doc: any) => void, opts?: LoadOptions): undefined;

export function safeDump(obj: any, opts?: DumpOptions): string;
export function dump(obj: any, opts?: DumpOptions): string;
```

I don't want to break anything so I may just open a PR for safeLoad or load if you think that should be changed too, but not for others unless you have some kind of suggestion.

**Comment by fabiospampinato** [comment]
> I've changed load to export function load(str: string, opts?: LoadOptions): string | undefined | object; as well.

That should be correct.

> There is this line of code with a bunch of functions that, (from my understanding of the documentation), should still return the same thing as safeLoad however it's written kind of oddly. Maybe you could make sense of it?

I've read the code and I believe `loadAll` and `safeLoadAll` return `undefined` if an "iterator" is provided, otherwise they return an array of documents. A document should be either a string or a plain object, it won't return `undefined` in this scenario.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
