### ISSUE TITLE
@types/ember__utils typeOf missing 'object'

### ISSUE THREAD

**Issue by runspired** [DefinitelyTyped/DefinitelyTyped#36809]
`typeOf` checks that valid return types are keys of this interface: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ae6aa49a5f62ee00ced651389e7941ea19881af4/types/ember__utils/-private/types.d.ts#L5

However this is missing `'object'` as allowed here: http://api.emberjs.com/ember/3.10/functions/@ember%2Futils/typeOf

**Comment by igbopie** [comment]
+1

**Comment by runspired** [comment]
Just tried dropping out custom override in EmberData but this appears to still be an issue
