### ISSUE TITLE
Chart.js - Property 'options' does not exist on type 'Chart'

### ISSUE THREAD

**Issue by ZaLiTHkA** [DefinitelyTyped/DefinitelyTyped#36857]
- [x] I tried using the `@types/chart.js@2.7.55` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @anuti @FabienLavocat @KentarouTakeda @larrybahr @mernen @josefpaij @danmana @guillaume-ro-fr @archy-bold @braincore @frabnt @alexdor @mahnuh @Conrad777 @adripanico @wertzui @lekoaf

If you do not mention the authors the issue will be ignored.

>note: I didn't tick the "latest tsc" checkbox because my environment is running TS `3.5.2`, but `3.5.3` won't make any difference here.

The `onRefresh` callback from `chartjs-plugin-streaming` is called with the chart instance as it's only argument, so I've assigned the `Chart` type to the argument in the function I'm assigning to that key.

Inside this function, when I try access `chart.options` as per the [official documentation](https://www.chartjs.org/docs/latest/developers/updates.html#updating-options), I get the error `Property 'options' does not exist on type 'Chart'`.

---

If I change the type assignment to `ChartConfiguration`, then I get no errors accessing either `chart.data` or `chart.options`, but the naming convention there seems strange..

Should I be using `ChartConfiguration` here, even though I'm working with a reference to the *rendered* chart?

I know the constructor for elements in the `chart.data.datasets` array does change between the configuration I give it and the instance after the chart has rendered, so do I run a risk of mismatching the type definitions with the actual object here by using `ChartConfiguration`?

**Comment by adripanico** [comment]
I don't think this question belongs to here.

If you get the error accessing to chart.options with tsc, try to access it in runtime. If the property actually exists, then change the type definitions and make a PR to this repo. If the property does not exists, open an issue into the proper repo.

**Comment by ZaLiTHkA** [comment]
@adripanico, my point here is that the property does exist on the root `Chart` instance attached to the DOM at runtime.

Effectively, I *believe* it's the `options` parameter on [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chart.js/index.d.ts#L203) that we actually have access to on a new `Chart` instance from ChartJS. But the `Chart` interface defined here doesn't have any reference to it.

That's why I asked..

>Should I be using `ChartConfiguration` here, even though I'm working with a reference to the rendered chart?

Is this an error here in the definitions? Or with my understanding of the typings defined here?

**Comment by seantott** [comment]
My understanding of this issue is that the `options` property is shared between `chart.config.options` and `chart.options` in chart.js. 

However, this library has only implemented the point at `chart.config.options`. The main question that should be asked is which is the correct location to access the options property. As a workaround in any work, however, `chart.config.options` works perfectly for any use case, just being slightly longer to type.

**Comment by ZaLiTHkA** [comment]
> However, this library has only implemented the point at `chart.config.options`.

By "this library", you're referring to *this repo* that I opened this issue in? If so, then you should keep in mind this isn't a **library**, it's a collection of TypeScript definitions for third-party libraries that don't already have their own definitions... There's no business logic being implemented here at all.

> The main question that should be asked is which is the correct location to access the options property.

I included a link to the official documentation page as a reference of how I was accessing the chart's options property, which is why I posted this issue in the first place.

---

With that said, in my project I was building up the configuration object for a chart that hadn't been created yet, so I assigned the `ChartConfiguration` interface to my object so that my IDE would give me feedback about the structure and contents of the object as I was writing the code to build it...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
