### ISSUE TITLE
DefinitelyTyped NuGet Package Source

### ISSUE THREAD

**Issue by AndyCJ** [DefinitelyTyped/DefinitelyTyped#3694]
The NuGet search system leaves much to be desired, and it can be fairly hard to find the appropriate definitely typed package for a given JavaScript library.

One solution to this would be having a [Package Source](http://docs.nuget.org/create/hosting-your-own-nuget-feeds) hosted by the DefinitelyTyped project which users can add to the Package Source list in visual studio.

Then, when searching for typescript definitions the DefinitelyTyped Package Source can be selected and only the relevant packages will be shown.

**Comment by AndyCJ** [comment]
A downside to this approach is increased maintenance work, and possibly hosting costs.

**Comment by vvakame** [comment]
@staxmanade
