### ISSUE TITLE
DefinitelyTyped NuGet Tag

### ISSUE THREAD

**Issue by AndyCJ** [DefinitelyTyped/DefinitelyTyped#3695]
The NuGet search system leaves much to be desired, and it can be fairly hard to find the appropriate definitely typed package for a given JavaScript library.

One solution to this would be including a tag of "DefinitelyTyped" so that more restrictive searches can be made.

e.g. "tag:DefinitelyTyped jquery"

**Comment by vvakame** [comment]
@staxmanade

**Comment by staxmanade** [comment]
Have a look at: https://github.com/DefinitelyTyped/NugetAutomation/blob/master/CreatePackages.ps1#L72

Send a Pull Request!

After we merge it in, possibly this weekend I'll re-publish all packages to include the updated tag(s).
