### ISSUE TITLE
Consistent NuGet Package Naming

### ISSUE THREAD

**Issue by AndyCJ** [DefinitelyTyped/DefinitelyTyped#3696]
The NuGet search system leaves much to be desired, and it can be fairly hard to find the appropriate definitely typed package for a given JavaScript library.

One issue is that some of the DefinitelyTyped packages are named differently to the libraries/packages they are typing.

e.g. 
The package for knockout is called KnockoutJS, the DefinitelyTyped package is called knockout.TypeScript.DefinitelyTyped. Searching for "KnockoutJS typescript" yields nothing useful.
The the facebook libraries are called the Facebook SDK, the DefinitelyTyped package is called fbsdk.TypeScript.DefinitelyTyped. Searching for "facebook (sdk) typescript" yields nothing useful.

Using the same naming as the libraries/packages being defined would improve discoverability.

**Comment by AndyCJ** [comment]
An issue with this is that the existing names are already in use and consumers of the DefinitelyTyped packages have now learned these names.

**Comment by vvakame** [comment]
@staxmanade

**Comment by staxmanade** [comment]
true about the search system...

The DT NuGet upload has a consistent naming `{packageName}.TypeScript.DefinitelyTyped` - so if you know the name of the folder in the DT repo, you can figure out what the NuGet ID would be.
