### ISSUE TITLE
[@types/jasmine/ts3.1] expect(ArrayLike<T>).toEqual() missing ArrayLike<ObjectContaining<T>> type for `expected` parameter

### ISSUE THREAD

**Issue by fuzzley** [DefinitelyTyped/DefinitelyTyped#36971]
I tried using the `@types/jasmine` package and had problems.

It seems that the `ArrayLikeMatchers<T>#toEqual(expected, ..)` is missing a possible type for the `expected` parameter: `ArrayLike<ObjectContaining<Element>>`.

I have some test code like this.
```
const elements = service.locate(locator, context); // Returns Element[]
expect(elements).toEqual(
          [jasmine.objectContaining({tagName: 'DIV', id: 'find-this'})]);
```

I get the following compile error.
```
error TS2345: Argument of type 'ObjectContaining<{ tagName: string; id: string; }>[]' is not assignable to parameter of type 'Any | Spy | ArrayLike<Element> | ObjectContaining<ArrayLike<Element>> | ArrayContaining<Element>'.
  Type 'ObjectContaining<{ tagName: string; id: string; }>[]' is not assignable to type 'ArrayLike<Element>'.
    Index signatures are incompatible.
      Type 'ObjectContaining<{ tagName: string; id: string; }>' is missing the following properties from type 'Element': assignedSlot, attributes, classList, className, and 123 more.

45           [jasmine.objectContaining({tagName: 'DIV', id: 'find-this'})]);
```

This test was valid/passing before we updated the typings, so it seems that the appropriate type is missing.

Authors: @kolodny, @sheetalkamat

**Comment by mitchellwills** [comment]
This is generally a problem for a nested `jasmine.objectContaining`

For example this also fails with a similar error:
```
expect(val).toEqual({
  foo: jasmine.objectContaining({tagName: 'DIV', id: 'find-this'}),
});

// assuming val as some type like
interface Val {
  foo: {tagName: string, id: string, other: string};
}
```

**Comment by SLaks** [comment]
I think the more-general fix would be to use recursive conditional mapped types to allow ObjectContaining for any property at any level.

**Comment by fuzzley** [comment]
Actually, it looks like we're using `@types/jasmine` (not `ts3.1`), but both typings seem to have the same issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
