### ISSUE TITLE
[@types/mongoose] Model constructor argument (doc) should be <any>

### ISSUE THREAD

**Issue by ramtinsoltani** [DefinitelyTyped/DefinitelyTyped#36982]
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @danmana @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125

Updating to `@types/mongoose@5.5.8`, TypeScript suddenly started complaining about the model constructor:

```typescript
const UserModel = mongoose.model('users', new mongoose.Schema({
  username: { type: String, required: true },
  email: { type: String, required: false }
}));

const model = new UserModel({
  username: 'string',
  email: 'string'
});
```
Error is:
```
Object literal may only specify known properties, and 'username' does not exist in type 'Partial<Document>'.
```

This is happening since the constructor argument was changed from `doc?: any` (version 5.5.7) to `doc? Partial<Document>` (version 5.5.8).

**Comment by Alorel** [comment]
That's because you didn't define the model properly.

```typescript
interface UserInterface { // for lean queries
  _id: Types.ObjectId;
  username: string;
  email: string;
}
type UserDocumentInterface = UserInterface & Document; // for non-lean queries

const schema = new mongoose.Schema({...});
// pass interface as type parameter
const model = mongoose.model<UserDocumentInterface>(schema);
```
