### ISSUE TITLE
@types/koa-bodyparser  incompatible with `@types/koa@2.0.49`

### ISSUE THREAD

**Issue by xr** [DefinitelyTyped/DefinitelyTyped#36999]
## Environment Information
Koa: 2.7.0
@types/koa: 2.0.49
koa-bodyparser: 4.2.1
@types/koa-bodyparser: 4.3.0

## Problem
```
Property 'body' does not exist on type 'Request'.
```

## Reproduce
```
app.use(ctx => {
    const body = ctx.request.body;
});
```

## Similar issues
https://github.com/dlau/koa-body/issues/155

Authors: @zbinlin  @santialbo

**Comment by zbinlin** [comment]
Can you upload a minimal reproduced repo?

**Comment by xr** [comment]
thanks @zbinlin, but never mind now, i think it's my project specific thing, it works once updating all other dependencies to the latest version.
