### ISSUE TITLE
[@types/node] Bug in dns.lookup

### ISSUE THREAD

**Issue by goloroden** [DefinitelyTyped/DefinitelyTyped#37035]
Hey @OJezu, @RyanCavanaugh, @lifeiscontent, @armanio123, and @rbuckton 😊 

I think that there is a bug in the definition of the `lookup` function of the `dns` module. It's about [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e8d6fb67f97b50b357f317da6867dfb7a995fee6/types/node/dns.d.ts#L34). Here it says:

```typescript
function __promisify__(hostname: string, options: LookupAllOptions): Promise<{ address: LookupAddress[] }>;
```

Instead, this should be:

```typescript
function __promisify__(hostname: string, options: LookupAllOptions): Promise<LookupAddress[]>;
```

In the section for native promise support (see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e8d6fb67f97b50b357f317da6867dfb7a995fee6/types/node/dns.d.ts#L298), this is correct.

**Comment by SimonSchick** [comment]
Yea can confirm, this might be a remnant from previous refactoring, PR welcome.

**Comment by SimonSchick** [comment]
So, I think all of these should look like this:

```ts
        function __promisify__(hostname: string, options: LookupAllOptions): Promise<LookupAddress[]>;
        function __promisify__(hostname: string, options?: LookupOneOptions | number): Promise<LookupAddress[]>;
        function __promisify__(hostname: string, options?: LookupOptions | number): Promise<LookupAddress | LookupAddress[]>;
```

correct?

**Comment by SimonSchick** [comment]
ping @goloroden

**Comment by goloroden** [comment]
I think so.

**Comment by TheHollidayInn** [comment]
I think there may still be a problem here.

```
function __promisify__(hostname: string, options?: LookupOneOptions | number): Promise<LookupAddress[]>;
```
The options parameter is optional, and I think when you don't provide `options` the overloaded function `function lookup(hostname: string, callback: (err: NodeJS.ErrnoException | null, address: string, family: number) => void): void;` is used which has a string callback. 

I recreated the issue like so:
```
import dns from 'dns'
import {promisify} from 'util'

const dnsLookup = promisify(dns.lookup)
const result = await dnsLookup(domain)

console.log(result) // this is a string
```
