### ISSUE TITLE
Formatter makes strange changes

### ISSUE THREAD

**Issue by bookmoons** [DefinitelyTyped/DefinitelyTyped#37048]
The repo code formatter makes strange changes in some cases.

Original:

```ts
export abstract class FileData {
    protected __brand: never;

    /** File data. */
    data: string | bytes;

    /** Filename to include in MIME message. */
    filename?: string;

    /** Content type to include in MIME message. */
    content_type?: string;
}
```

Various things it's popped into at different times:

```ts
export abstract class FileData {
                                protected __brand: never;

                                /** File data. */
                                data: string | bytes;

                                /** Filename to include in MIME message. */
                                filename?: string;

                                /** Content type to include in MIME message. */
                                content_type?: string;
                            }
```

```ts
export abstract class FileData {
                    protected __brand: never;

                             /** File data. */
                    data: string | bytes;

                             /** Filename to include in MIME message. */
                    filename?: string;

                             /** Content type to include in MIME message. */
                    content_type?: string;
                   }
```

```ts
export abstract class FileData protected __brand: never;

/** File data. data: string | bytes;

/** Filename to include in MIME message. filename?: string;

/** Content type to include in MIME message. content_type?: string;
}
```

No idea how the heck that last one happened.

At one point it got into a state where it kept toggling back and forth. It didn't like its own output in either case. So I couldn't commit at all. Not really sure what to do about this but something seems off. It makes it awkward to work with my types sometimes.

**Comment by yume-chan** [comment]
I have a similar issue, the pre-commit hook made a complete mess, so I have to use --no-verify to commit.

Here is the commit from the formatter: https://github.com/yume-chan/DefinitelyTyped/commit/feb17c773ee2e48b3e4becf7e7496586599a53f0

For example at [index.d.ts#304](https://github.com/yume-chan/DefinitelyTyped/commit/feb17c773ee2e48b3e4becf7e7496586599a53f0#diff-419a2bb7dbf26eef8ebdc8748dc7a656R304) and [index.ts#379](https://github.com/yume-chan/DefinitelyTyped/commit/feb17c773ee2e48b3e4becf7e7496586599a53f0#diff-bf0a82ca02c6b6afc95a883a61c56ab0R379)

![image](https://user-images.githubusercontent.com/1330321/62995734-7a6e5880-be94-11e9-8318-1eaebc150294.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
