### ISSUE TITLE
Problem with MouseTrap callback

### ISSUE THREAD

**Issue by Sigkill79** [DefinitelyTyped/DefinitelyTyped#37059]
Hi!

I'm trying to override the stopCallback(), but it seems like it is never called (I make a console.log() that is never called). I see from this discussion: https://github.com/ccampbell/mousetrap/issues/288
where the author of Mousetrap mentions that it is moved to prototype, but it seems to be no prototype available.

Do you think maybe this is something that needs to be fixed here? @qcz @alanhchoi @nicbarker @ra-gg

**Comment by nicbarker** [comment]
👀

**Comment by nicbarker** [comment]
Could you paste a snippet of your usage here? I've just tested our implementation and it works by overriding in the following manner:
```
const foo = new Mousetrap();
foo.stopCallback = (event, element) => { console.log('stopCallback') }
```

**Comment by Sigkill79** [comment]
I'm not making a local instance of Mousetrap, but rather:
`Mousetrap.stopCallback = () => console.log('callback');`

No error or warning messages, but it's never triggered.

**Comment by nicbarker** [comment]
Ahhh, my apologies I see now. I'll take a look.

**Comment by nicbarker** [comment]
Interesting, your IDE is letting you assign that function directly to the `MousetrapStatic` class?
VSCode auto completion is telling me that it's read-only:
<img width="811" alt="Screen Shot 2019-07-23 at 11 39 17 AM" src="https://user-images.githubusercontent.com/2264338/61672128-93c13080-ad3e-11e9-86ef-928db4726808.png">

**Comment by Sigkill79** [comment]
This is what puzzles me a bit. There are no runtime errors/warnings when doing just that, and it seems like that overriding Mousetrap.stopCallback() should be fine by the documentation. Also, reading the property directly after setting it, looks fine (although, I'm no typescript expert).

I do have another weird error, in that if I try to evaluate `new Mousetrap();`, I get an error:
`TypeError: Object is not a constructor (evaluating 'new Mousetrap()')`
So, I cannot create a new instance either...

**Comment by Sigkill79** [comment]
So, I figured it out. I was importing mouse trap as `import * as Mousetrap from 'mousetrap`, changing it to `import Mousetrap from 'mousetrap';`, I can now access `Mousetrap.prototype`.

So, I assume this was my fault. Sorry about that, I'm really new to Typescript :)

**Comment by nicbarker** [comment]
All good mate, glad you figured it out 😊
