### ISSUE TITLE
Jasmine createSpyObj has new array parameter for specifying properties

### ISSUE THREAD

**Issue by rcollette** [DefinitelyTyped/DefinitelyTyped#37065]
If you know how to fix the issue, make a pull request instead.

- [ X] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @theodorejb @davidparsson @gmoothart @lukas-zech-software @Engineer2B @cyungmann @Roaders @devoto13 @dim @pe8ter @kolodny

jasmine.createSpyObj takes an array of property names as a parameter following the array of method names.  

 Merged to master 27 days ago in https://github.com/jasmine/jasmine/pull/1722

Maybe included in the package version bump 15 days ago?

**Comment by rcollette** [comment]
This also accepts an object where each object property value becomes the value of the property defined on the mock.

**Comment by zvirja** [comment]
@rcollette New version of jasmine has not been published yet. Let's wait for the release before updating typings.

**Comment by HonoluluHenk** [comment]
FYI: [Jasmine 3.5.0 is out](https://github.com/jasmine/jasmine/releases/tag/v3.5.0)
which includes this feature: "Allow users to pass property names to createSpyObj"

**Comment by simondel** [comment]
Hi @rcollette @zvirja @HonoluluHenk The types for 3.5.0 have been released. Please try them out to see if I've added them correctly.

**Comment by rcollette** [comment]
createSpyObj<T> should be able to take a signature like:

`createSpyObj<T>('name',[],{prop1:'value'})`

but the type declaration seems to be forcing me to specify an array of property names, unless T is undefined.

**Comment by simondel** [comment]
@rcollette Could you change the types in your node_modules so the `SpyObjPropertyNames` is:
```ts
type SpyObjPropertyNames<T = undefined> =
	T extends undefined ?
			(ReadonlyArray<string> | { [propertyName: string]: any }) :
			(ReadonlyArray<keyof T>) | { [P in keyof T]?: any });;
```

**Comment by rcollette** [comment]
Sorry for the delay... work priorities.

Using:
```Typescript
principal$ = new Subject<IPrincipal>();d
    authorizationService = createSpyObj<AuthorizationService>('authorizationService', [], { principal$ });
```

I get the following error.
![image](https://user-images.githubusercontent.com/136476/70090366-03e29b80-15e8-11ea-8f9a-2deeb47e17bb.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
