### ISSUE TITLE
[@type/react] Generic Props lost with React memo

### ISSUE THREAD

**Issue by gforge** [DefinitelyTyped/DefinitelyTyped#37087]
For some reason `React.memo` drops the generic prop type and creates a regular union type. I've posted on [StackOverflow](https://stackoverflow.com/questions/56891234/reacts-memo-drops-generics-in-the-returned-function?noredirect=1#comment100573160_56891234) but there doesn't seem to be a non-hacky solution (despite the 100 point bounty I put on the question). The following toy example illustrates the issue:

```tsx
interface TProps<T extends string | number> {
  arg: T;
  output: (o: T) => string;
}

const Test = <T extends string | number>(props: TProps<T>) => {
  const { arg, output } = props;
  return <div>{output(arg)} </div>;
};

const myArg = 'a string';
const WithoutMemo = <Test arg={myArg} output={o => `${o}: ${o.length}`} />;

const MemoTest = React.memo(Test);
const WithMemo = <MemoTest arg={myArg} output={o => `${o}: ${o.length}`} />;
```

The last line results in an error message for the `output` function's `o.length`:

```text
Property 'length' does not exist on type 'string | number'.
  Property 'length' does not exist on type 'number'.
```

A workaround is to assign the `React.memo` to a generic interface:

```tsx
interface MemoHelperFn {
  <T extends string | number>(arg: TProps<T>): JSX.Element;
}
```

but this in turn requires forcing TypeScript by adding a @ts-ignore to the assignment.

- [x] I tried using the `@types/react` package version `16.8.23`.
- [x] I tried using the latest stable version of tsc: 3.5.3
- Authors: @johnnyreilly @bbenezech @digiguru @DovydasNavickas @eps1lon @ericanderson @DovydasNavickas @ferdaber @franklixuefei @guilhermehubner @hotell @Jessidhia @jrakotoharisoa @lukyth @onigoetz @pascaloliv @pzavolinsky @saranshkataria @theruther4d @tkrotoff @pshrmn @threepointone

**Comment by ferdaber** [comment]
TS doesn't currently support the ability to "forward" free type parameters when performing operations with higher order functions, so the free type parameter is lost when you create it, so yeah unfortunately we're out of luck.

**Comment by gforge** [comment]
I kind of suspected that although it seems like it should be a high-priority issue as this should affect any higher-order-compoenten. Is [this](https://github.com/microsoft/TypeScript/issues/28938) the correct TS issue?

**Comment by steida** [comment]
As a workaround, we can use useMemo inside a component.

**Comment by gforge** [comment]
@steida Thanks. Saw your reply on SO as well. I've upvoted it but left it unchecked as it would be nice to have a link to the correct TS-issue so that people can vote on the issue and perhaps get some traction around the issue. There are currently 3000+ TS issues and I guess it isn't obvious for the TS team in what order to try and resolve these.

**Comment by troch** [comment]
I've left an answer on the SO question as well. Like @steida said, it is possible to use `useMemo`, so I posted an example of it with props shallow comparison. It still adds extra verbosity but it's the best workaround I've found. It gives you the same properties than `memo`: your components and its children are not unnecessarily re-rendered thanks to shallow comparison.

One problem it doesn't solve is the use of `forwardRef`.

Posting it here as well:

```tsx
import { ReactElement, useRef } from 'react'

const shallowEqual = <Props extends object>(left: Props, right: Props) => {
  if (left === right) {
    return true
  }

  const leftKeys = Object.keys(left)
  const rightKeys = Object.keys(right)

  if (leftKeys.length !== rightKeys.length) {
    return false
  }

  return leftKeys.every(key => (left as any)[key] === (right as any)[key])
}

export const useMemoRender = <Props extends object>(
  props: Props,
  render: (props: Props) => ReactElement,
): ReactElement => {
  const propsRef = useRef<Props>()
  const elementRef = useRef<ReactElement>()

  if (!propsRef.current || !shallowEqual(propsRef.current, props)) {
    elementRef.current = render(props)
  }

  propsRef.current = props

  return elementRef.current as ReactElement
}
```

**Comment by pie6k** [comment]
I'm using hook for that too, it's a little bit simpler than @troch solution

```ts
export function useMemoComponent<P>(
  component: FunctionComponent<P>,
) {
  return useMemo(() => memo(component), [component]);
}
```

and than inside some render function I use `const MemoizedComponent = useMemoComponent(Component)`

**Comment by frankwallis** [comment]
Unless you need all the baggage, maybe just override the typings locally:

```
const typedMemo: <T>(c: T) => T = React.memo;
const MemoTest = typedMemo(Test);
const WithMemo = <MemoTest arg={myArg} output={o => `${o}: ${o.length}`} />;
```

**Comment by kalbert312** [comment]
> Unless you need all the baggage, maybe just override the typings locally:
> 
> ```
> const typedMemo: <T>(c: T) => T = React.memo;
> const MemoTest = typedMemo(Test);
> const WithMemo = <MemoTest arg={myArg} output={o => `${o}: ${o.length}`} />;
> ```

Out of curiosity is there documentation on that `T = React.memo` syntax?

**Comment by ferdaber** [comment]
It's not a syntax thing, perhaps this will clarify:
```ts
interface IdentityFunction {
  <T>(fn: T): T
}

const typedMemo: IdentityFunction = React.memo;
const typedMemo = React.memo as IdentityFunction; // same as above but using assertion
```

**Comment by kalbert312** [comment]
Oh thanks... I misread it.

**Comment by kalbert312** [comment]
Looks like that workaround only works with `forwardRef` using the assertion due to the mismatch of the input and return types on `forwardRef` compared to `memo`'s signature.

**Comment by ferdaber** [comment]
Right, I doubt that annotating it will work since they're subtypes of each other.

**Comment by kieranbenton** [comment]
I think what you're looking for is...

```
const MemoizedComponent = React.memo(innerComponent) as typeof innerComponent;
```

**Comment by pie6k** [comment]
```tsx
export function typedMemo<C extends ComponentType>(Component: T): C {
  return memo(Component) as C;
}
```

This one returns the same type of component you're passing to it, but makes it memorized (and keeps generics)

**Comment by gastonmorixe** [comment]
```
react.d.ts

import * as React, { memo } from "react"

declare module "react" {
  function memo<P extends object>(
    Component: React.SFC<P>,
    propsAreEqual?: (
      prevProps: Readonly<React.PropsWithChildren<P>>,
      nextProps: Readonly<React.PropsWithChildren<P>>
    ) => boolean
  ): React.SFC<P>

  type GetComponentProps<T> = T extends
    | React.ComponentType<infer P>
    | React.Component<infer P>
    ? P
    : never
}

**Comment by nandorojo** [comment]
> Unless you need all the baggage, maybe just override the typings locally:
> 
> ```
> const typedMemo: <T>(c: T) => T = React.memo;
> const MemoTest = typedMemo(Test);
> const WithMemo = <MemoTest arg={myArg} output={o => `${o}: ${o.length}`} />;
> ```

This worked for me. I also added a second argument, like so:


```ts
const typedMemo: <T>(
  c: T,
  areEqual?: (
    prev: React.ComponentProps<T>,
    next: React.ComponentProps<T>
  ) => boolean
) => T = React.memo

const Memo = (Component, (prev, next) => prev.text === next.text)
<Memo text={'hi'} />
```

Seems to be working for me. The only problem is I get errors in the `areEqual`, saying `T is not assignable to "view"`, so I'm not sure what it should have instead of `React.ComponentProps<T>`.

**Comment by pie6k** [comment]
I ended up using this:

```tsx
import { ComponentType, memo, useEffect, ComponentProps } from 'react';

type PropsComparator<C extends ComponentType> = (
  prevProps: Readonly<ComponentProps<C>>,
  nextProps: Readonly<ComponentProps<C>>,
) => boolean;

function typedMemo<C extends ComponentType<any>>(
  Component: C,
  propsComparator?: PropsComparator<C>,
) {
  return (memo(Component, propsComparator) as any) as C;
}

function Foo<D>(props: { foo: 2, bar: D }) {
  return <div>foo</div>;
}

const Memoed = typedMemo(Foo);

/**
 * Generic remained!
 * const Memoed: <D>(props: {
 *     foo: 2;
 *     bar: D;
 * }) => JSX.Element
 */
```

**Comment by marc-ed-raffalli** [comment]
It could be more succinct by leveraging TS features `Parameters`:

```
export function genericMemo(
  Component: Parameters<typeof React.memo>[0],
  propsAreEqual: Parameters<typeof React.memo>[1]
) {
  return React.memo(Component, propsAreEqual) as typeof Component;
}
``` 

then

```
function Foo<D>(props: { foo: 2, bar: D }) {
  return <div>foo</div>;
}

const Memoed = genericMemo(Foo);
```

**Comment by benneq** [comment]
Did they fix this?

I'm using `"@types/react": "^16.9.52"`, `"@types/react-dom": "^16.9.8"`, `"typescript": "^4.1.0-beta"`

```
const Memoed2 = React.memo(Foo, (prev, next) => prev.foo === next.foo);

// const Memoed2: React.MemoExoticComponent<(<D>(props: {
//     foo: 2;
//     bar: D;
// }) => JSX.Element)>
```

**Comment by milos2211** [comment]
I'm still having problem with versions that @benneq provided.
With 
```
....
<Memoed2<SomeType>/>
....
```
I get:
```Expected 0 type arguments, but got 1.```

**Comment by jleider** [comment]
@pie6k's solution worked for me! https://github.com/DefinitelyTyped/DefinitelyTyped/issues/37087#issuecomment-699521381 🙏 

@marc-ed-raffalli's (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/37087#issuecomment-704575310) exhibited the same issue I was having with the standard React typings likely due to the lack of generic type parameters in the function signature.

**Comment by nak2k** [comment]
@nandorojo's solution worked by using `T extends ComponentType<any>` instead of `T`.

``` typescript
const typedMemo: <T extends ComponentType<any>>(
  c: T,
  areEqual?: (
    prev: React.ComponentProps<T>,
    next: React.ComponentProps<T>
  ) => boolean
) => T = React.memo;
```

And to make it work without variable assignment at runtime, I have modified it to work as follows:

``` typescript
declare module "react" {
  function memo<T extends React.ComponentType<any>>(
    c: T,
    areEqual?: (
      prev: Readonly<React.ComponentProps<T>>,
      next: Readonly<React.ComponentProps<T>>
    ) => boolean
  ): T;
}
```

**Comment by Ayc0** [comment]
I had this issue and I solved it by doing:

```tsx
interface TProps<T extends string | number> {
  arg: T;
  output: (o: T) => string;
}

const Test = <T extends string | number>(props: TProps<T>) => {
  const { arg, output } = props;
  return <div>{output(arg)} </div>;
};

const myArg = 'a string';
const WithoutMemo = <Test arg={myArg} output={o => `${o}: ${o.length}`} />;

const MemoTest = React.memo(Test) as typeof Test;
const WithMemo = <MemoTest arg={myArg} output={o => `${o}: ${o.length}`} />;
```

This isn't the best but it works and this is fairly simple to use.

**Comment by dgreene1** [comment]
I've found that the above solutions are a bit too complex and are (in some cases) removing the type information. Here's my solution, if anyone would be interested to tell me why it is or is not ideal. The benefit of the approach I see here is that it doesn't cause me to resort to type casting (i.e. `as`), the use of `unknown`, or the use of `any`.

```ts
export function genericMemo<PropType>(Component: React.ComponentType<PropType>) {
    return React.memo<React.ComponentType<PropType>>(Component);
}

export const ASimpleComponent = genericMemo(function<PropType extends { aPropCalledName: string }>(props: PropType) {
    return <div>name: {props.aPropCalledName}</div>;
});
```

With that example, you'll see that the type of `ASimpleComponent` is what I would expect:
```ts
React.MemoExoticComponent<React.ComponentType<{
    aPropCalledName: string;
}>>
```

**Comment by OliverJAsh** [comment]
For anyone interested in _why_ this issues occurs, see responses in https://github.com/microsoft/TypeScript/issues/30650.

**Comment by Albert-Gao** [comment]
> I think what you're looking for is...
> 
> ```
> const MemoizedComponent = React.memo(innerComponent) as typeof innerComponent;
> ```

This is the obvious winner to me, any solution with extra unnecessary function call just for passing types is typing for the sake of typing rather than convey the design thinking, use `as` in this case.

**Comment by gforge** [comment]
Thanks, I guess the `typeof` is the best solution for now. I'll close down this issue as this will probably not be resolved by changing the DefinitelyTyped repo.

**Comment by m0onspell** [comment]
Another solution for those who don't want to create `innerComponent` and `memoizedComponent` each time as suggested in #37087
```typescript
interface SomethingComponent {
  <T>(props: YourProps<T>): JSX.Element | null;
}

const Something: SomethingComponent = memo(/* ...definition */ );
```
Won't work if you have to use your passed generic type inside of the component definition.

**Comment by iway1** [comment]
use @kieranbenton 's solution it's super simple and works perfectly

**Comment by dennis-gonzales** [comment]
> I think what you're looking for is...
> 
> ```
> const MemoizedComponent = React.memo(innerComponent) as typeof innerComponent;
> ```

Thanks, exactly what I needed.

**Comment by Ploppy3** [comment]
Unfortunately there is no alternatives with JSDoc.

**Comment by gentlee** [comment]
```ts
/** Fixes problem with wrapping generic components. */
export const genericMemo = memo as <T>(fn: T) => T
```
