### ISSUE TITLE
[@types/debounce-promise] The argument is no longer multiple

### ISSUE THREAD

**Issue by wowissu** [DefinitelyTyped/DefinitelyTyped#37103]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/debounce-promise` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sandersn 

debounce-promise@3.1.2

The arguments of `debounce((args) => {})` are no longer return multiple arguments when using accumulate mode.
there is only one param with array type

```typescript
const two = debounce(
  (params: [string, number, { d: boolean }][]) => {
    console.log(params);

    // params = [
    //   ['1', 2, { d: false }], 
    //   ['1', 2, { d: false }], 
    //   ['1', 2, { d: false }]
    // ]

    params.forEach((a) => {
      console.log(a[0]);
    });

    return [4];
  },
  10,
  {
    accumulate: true,
  },
);
two('1', 2, { d: false }); // Expected 1 arguments, but got 3.ts(2554)
two('1', 3, { d: false }); // Expected 1 arguments, but got 3.ts(2554)
two('1', 4, { d: false }); // Expected 1 arguments, but got 3.ts(2554)
```

Here is a working version I edited at will. 

```typescript
declare namespace debounce {
  interface DebounceOptions {
    leading?: boolean;
    accumulate?: boolean;
  }

  interface DebounceOptionsAccumulate {
    leading?: boolean;
    accumulate: true;
  }
}

declare function debounce<T extends (args: any[]) => any>(
  func: T,
  wait: number,
  options: debounce.DebounceOptionsAccumulate,
): (
  ...args: Parameters<T>[0][0]
) => ReturnType<T> extends Promise<any>
  ? ReturnType<T>
  : Promise<ReturnType<T>>;

declare function debounce<T extends (...args: any[]) => any>(
  func: T,
  wait?: number,
  options?: debounce.DebounceOptions,
): (
  ...args: Parameters<T>
) => ReturnType<T> extends Promise<any>
  ? ReturnType<T>
  : Promise<ReturnType<T>>;

export = debounce;
```

**Comment by sandersn** [comment]
@whtsky is the author of these types.

**Comment by whtsky** [comment]
Looks like you already know how to fix this, so can you make a pull request instead?

**Comment by wowissu** [comment]
@whtsky Ok !

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
