### ISSUE TITLE
[@types/mongodb] `find` is incorrectly marked as deprecated

### ISSUE THREAD

**Issue by smeijer** [DefinitelyTyped/DefinitelyTyped#37128]
`@types/mongodb` declares `collection.find` as being deprecated, yet the official docs do not. The only thing being deprecated there, seems to be the `fields` options. Am I missing something here?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d376c1624ee13f42843e9d732cc7dda586636738/types/mongodb/index.d.ts#L929-L932

http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#find

**Comment by SneakyFish5** [comment]
So just removing the deprecated message like this is what you would want changed?: https://github.com/SneakyFish5/DefinitelyTyped/commit/b85956276ed1f7f840529bff78c49631c1282569

**Comment by smeijer** [comment]
@SneakyFish5, correct

**Comment by SneakyFish5** [comment]
For small changes like this, you'll be fine without a test in my experience.

**Comment by neilbryson** [comment]
As long as it won't show deprecated anymore in your editor, I guess everything's good.

**Comment by smeijer** [comment]
Thanks for the feedback 👍, created the PR.
