### ISSUE TITLE
[@types/firefox-webext-browser] missing `browser.tabs.TabStatus`, `browser.windows.WindowState` and similar objects

### ISSUE THREAD

**Issue by icl7126** [DefinitelyTyped/DefinitelyTyped#37130]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/firefox-webext-browser` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jsmnbom

I've noticed some of the "enum" like objects are missing here, even though they exists in Firefox and Chrome, for example:
```
browser.tabs.TabStatus = {
  "LOADING": "loading",
  "COMPLETE": "complete"
}
browser.windows.WindowState = {
  "NORMAL": "normal",
  "MINIMIZED": "minimized",
  "MAXIMIZED": "maximized",
  "FULLSCREEN": "fullscreen",
  "DOCKED": "docked"
}
```

TabStatus doc:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/TabStatus
(actually the doc specifies the type only, I'm not really sure where this feature is documented)

**Comment by behnood-eghbali** [comment]
why?

**Comment by SneakyFish5** [comment]
I just looked through the code and it seems it's already there.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/firefox-webext-browser/index.d.ts#L7191-#L7190

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/firefox-webext-browser/index.d.ts#L7831-#L7840

**Comment by icl7126** [comment]
@SneakyFish5 those are types, I mean a normal object with with values:
```
console.log(browser.tabs.TabStatus)
Object { LOADING: "loading", COMPLETE: "complete" }
```

That I can use instead of strings (since `tab.status` is defined as a plain `string`):
```
const loadedTab = tabs.find(t => tab.status === browser.tabs.TabStatus.COMPLETE);
```

I can't find the documentation for that, but the object exists.

**Comment by icl7126** [comment]
https://discourse.mozilla.org/t/looking-for-the-documentation-for-browser-tabs-tabstatus-object/43042
