### ISSUE TITLE
[@types/firefox-webext-browser] browser.tabs.create should return Promise<Tab>

### ISSUE THREAD

**Issue by icl7126** [DefinitelyTyped/DefinitelyTyped#37149]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/firefox-webext-browser` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jsmnbom

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a031f03c2c52eb8c3d71ccfcfafb9904a7f08bf5/types/firefox-webext-browser/index.d.ts#L7375

Based on the docs:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create

> Return value
> A Promise that will be fulfilled with a tabs.Tab object containing details about the created tab. If the tab could not be created (for example, because url used a privileged scheme) the promise will be rejected with an error message.

I can create PR if all I need to is change the return type - I'm not sure, I'm new here.

**Comment by icl7126** [comment]
And same thing seems to apply for `browser.windows.create` as well:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a031f03c2c52eb8c3d71ccfcfafb9904a7f08bf5/types/firefox-webext-browser/index.d.ts#L8003

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create

> Return value
> A Promise that will be fulfilled with a windows.Window object containing the details of the new window. This Window object will always have its tabs property set, unlike the Window objects returned from windows.get() and similar APIs, which only contain tabs if the populate option is passed. If any error occurs, the promise will be rejected with an error message.

**Comment by icl7126** [comment]
I've found another case - `browser.tabs.executeScript`:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a031f03c2c52eb8c3d71ccfcfafb9904a7f08bf5/types/firefox-webext-browser/index.d.ts#L7582

> Return value
> A Promise that will be fulfilled with an array of objects, representing the result of the script in every injected frame.

**Or am I missing something here? Why can all these API return `undefined` when docs says otherwise?**

**Comment by jsmnbom** [comment]
This should be fixed by jsmnbom/definitelytyped-firefox-webext-browser#29.
I'll make a PR soon for all cases (like 20 or so i think), so feel free to close this :)
