### ISSUE TITLE
jquery does not work with TravisCI

### ISSUE THREAD

**Issue by Judahh** [DefinitelyTyped/DefinitelyTyped#37163]
If you know how to fix the issue, make a pull request instead.
**The package ("@types/jquery": "^3.3.30") does not works at the first install, so it doesn't work in Travis.**

`
node_modules/@types/jquery/index.d.ts:29:22 - error TS6053: File '/home/judahholanda/backApp/node_modules/@types/jquery/JQueryStatic.d.ts' not found.

29 /// <reference path="JQueryStatic.d.ts" />
                        ~~~~~~~~~~~~~~~~~

node_modules/@types/jquery/index.d.ts:30:22 - error TS6053: File '/home/judahholanda/backApp/node_modules/@types/jquery/JQuery.d.ts' not found.

30 /// <reference path="JQuery.d.ts" />
                        ~~~~~~~~~~~

node_modules/@types/jquery/index.d.ts:31:22 - error TS6053: File '/home/judahholanda/backApp/node_modules/@types/jquery/misc.d.ts' not found.

31 /// <reference path="misc.d.ts" />
                        ~~~~~~~~~

node_modules/@types/jquery/index.d.ts:32:22 - error TS6053: File '/home/judahholanda/backApp/node_modules/@types/jquery/legacy.d.ts' not found.

32 /// <reference path="legacy.d.ts" />
                        ~~~~~~~~~~~

node_modules/@types/jquery/index.d.ts:34:10 - error TS2304: Cannot find name 'jQuery'.

34 export = jQuery;
            ~~~~~~
`

- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu @borisyankov 

If you do not mention the authors the issue will be ignored.

**Comment by leonard-thieu** [comment]
I couldn't reproduce this error.

[Travis CI Build](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/564224351?utm_source=github_status&utm_medium=notification)
https://github.com/leonard-thieu/DefinitelyTyped-issue-37163

Could you post a repro?

**Comment by Judahh** [comment]
Sorry, but I think it was some kind of cache problem (on Travis), I couldn't reproduce the same problem not even when copying my whole project with the reported problem to a new repo. I deleted all project, then uploaded again then it started working.
