### ISSUE TITLE
faker.date.soon is not a function

### ISSUE THREAD

**Issue by mfulton26** [DefinitelyTyped/DefinitelyTyped#37165]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c428e33e5c12c78187e44e80c8b4323e0f3da795/types/faker/index.d.ts#L71

I'm confused as to how the tests are passing as faker.date.soon is not a function (see https://github.com/Marak/faker.js/issues/639).

**Comment by loremaps** [comment]
It seems that `soon` was released with `v5.0.0`
