### ISSUE TITLE
[@types/mapbox-gl] Add setMaxWidth to PopupOptions

### ISSUE THREAD

**Issue by chloekraw** [DefinitelyTyped/DefinitelyTyped#37213]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dobrud, @patrickr, @macobo, @dmytro-gokun 

---

👋 `setMaxWidth` is missing from `mapboxgl.PopupOptions`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L627-L644

This was added in https://github.com/mapbox/mapbox-gl-js/pull/7906

Cutting this ticket in case anyone is available to do this quickly as it seems straightforward and I haven't contributed to this library before. Otherwise, I can look into making a pr later. Thanks!

**Comment by dmytro-gokun** [comment]
@chloekraw If you can wait, i'll work on this some day this week. Otherwise, just go ahead and create a PR. Let me know what you've decided.

**Comment by chloekraw** [comment]
@dmytro-gokun this week would be great! Thank you. I’ll look around for other PRs I can contribute in the future.

**Comment by frdeboffles** [comment]
In the meantime you can extend the popup option as follow:
```javascript
export interface MyPopupOptions extends PopupOptions {
  maxWidth?: string;
}
...
    const popupOptions: MyPopupOptions = {
      closeButton: false,
      closeOnClick: false,
      maxWidth: '400px'
    };
    const popup: Popup = new Popup(popupOptions);
...
```

**Comment by SneakyFish5** [comment]
Does this look good to you? If so I'll open the PR.

https://github.com/SneakyFish5/DefinitelyTyped/commit/1db4772fd2220379cd9edc9466639910832ba07d

**Comment by SneakyFish5** [comment]
Oh never mind I just saw someone pushed a fix

**Comment by frdeboffles** [comment]
Thanks @SneakyFish5, noticed in your commit that I forgot the getter and setter on the popup. I'll amend my PR

**Comment by SneakyFish5** [comment]
No problem, glad I could help @frdeboffles.

**Comment by chloekraw** [comment]
Thank you @frdeboffles @sneakyfish5!
