### ISSUE TITLE
@types/redux-orm: incorrect typing for RelationalFieldOpts.throughFields in fields.d.ts

### ISSUE THREAD

**Issue by gtnsimon** [DefinitelyTyped/DefinitelyTyped#37293]
- [x] I tried using the `@types/redux-orm` package and had problems.
- [x] Authors: @keenondrums, @tomasz-zablocki 

I'm using [redux-orm](https://github.com/redux-orm/redux-orm) (version 0.13.3) with types definitions from `@types/redux-orm` (version 0.13.4) but I have an issue with the definition of many-to-many relations in my models using `throughFields` prop of the `many` function parameter.

In [fields.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/redux-orm/fields.d.ts), the [ManyCreator](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bcbffb5c5c4a13afdd3024e34480a2888f7d4c67/types/redux-orm/fields.d.ts#L53) interface use [RelationalFieldOpts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bcbffb5c5c4a13afdd3024e34480a2888f7d4c67/types/redux-orm/fields.d.ts#L17) and is defined as follow:

```typescript
export interface RelationalFieldOpts {
    to: string;
    relatedName?: string;
    through?: string;
    throughFields?: {
        to: string;
        from: string;
    };
    as?: string;
}
```

The issue is that `throughFields` type require an objet with 2 keys: `to` and `from` but [according to the redux-orm doc for `many`](https://redux-orm.github.io/redux-orm/global.html#many) it accept an array of 2 `string` corresponding respectively to: `to` and `from`.

```typescript
// this is optional, since Redux-ORM can figure
// out the through fields itself as there aren't
// multiple foreign keys pointing to the same models.
throughFields: ['author', 'book'],
```

Currently, this result to an error while compiling:

```log
Type 'string[]' is missing the following properties from type '{ to: string; from: string; }': to, from  TS2739
```

As a workaround for now, I add:

```typescript
//@ts-ignore
```

**Comment by tomasz-zablocki** [comment]
@gtnsimon Thank you for reporting this issue, 

I'll fix it today

**Comment by tomasz-zablocki** [comment]
@gtnsimon done, waiting to be merged
