### ISSUE TITLE
Issue with Hash and Hmac update() functions.

### ISSUE THREAD

**Issue by systemmonkey42** [DefinitelyTyped/DefinitelyTyped#37309]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

In node/crypto.d.ts ( @SimonSchick ) for the 'Hash' and 'Hmac' classes, the `update()` functions  dont accept Buffer type arguments with an encoding of 'binary'.

The defaults encoding of strings passed to Hash.update() has been 'utf8' since v6, however I cannot specify a Buffer with an encoding of 'binary' without getting an error. (And passing a string results in an incorrect hash)

>let data = Buffer.from(input,'binary');
>hash.update(data,'binary');
2345: Argument of type 'Buffer' is not assignable to parameter of type 'string'.

The definition for update needs to include `Buffer` in the input data, and `binary`
in the `input_encoding` list.

```
class Hash extends stream.Duplex {
 update(data: string, input_encoding: Utf8AsciiLatin1Encoding): Hash;
```
example
```
class Hash extends stream.Duplex {
 update(data: string, input_encoding: Utf8AsciiLatin1Encoding): Hash;
 update(data : Buffer, input_encoding: Utf8AsciiBinaryEncoding ): Hash: 
```

I'm not familiar enough with the code base to create a pull request, and my attempts to far to implment even minor changes in type files have failed.

**Comment by SimonSchick** [comment]
I believe this is incorrect.

Please refer to https://nodejs.org/dist/latest-v12.x/docs/api/crypto.html#crypto_hash_update_data_inputencoding

**Comment by systemmonkey42** [comment]
Closing.  Thanks for your input (and your patience).  I understand what I was doing wrong now.
