### ISSUE TITLE
@types/jquery Drag Handler events getting typed as "Event" instead of "DragEvent"

### ISSUE THREAD

**Issue by renodubois** [DefinitelyTyped/DefinitelyTyped#37330]
- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu, @borisyankov (apologies if y'all aren't the right people to mention here)

I'm using a JQuery "drop" event selector, like so:
```
$("body").on("drop", (e) => {...})
```
The issue here is that `e.originalEvent` is getting typed as an `Event`, when it should be a `DragEvent`. This is causing me to have to cast that variable manually to a `DragEvent`, when I would expect it to be a drag event by default.

Happy to explain further if needed!

**Comment by leonard-thieu** [comment]
Will be fixed by #37349. Thanks for reporting this!
