### ISSUE TITLE
[@types/react-redux] connect error with mapDispatchToProps object shorthand with thunk action creator

### ISSUE THREAD

**Issue by tuomokar** [DefinitelyTyped/DefinitelyTyped#37369]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-redux` package and had problems.
  * Tested with versions:
    * 7.1.1 (current)
    * 6.0.10 (first version in which it didn't work)
    * 6.0.9 (no problem in this version)
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kenzierocks @clayne11 @tansongyang @nicholasboll @mDibyo @Kallikrein @val1984 @jrakotoharisoa @apapirovski @surgeboris @soerenbf @MrWolfZ 

There seems to be an error related to `connect` function's typings when using a thunk action creator with `mapDispatchToProps` object shorthand syntax. 

I made a simple reproduction repo here: https://github.com/tuomokar/react-redux-type-error-with-thunks

In that repo I created two otherwise identical components (`Counter1` and `Counter2`) but the first one uses the object shorthand version for `mapDispatchToProps` and the second one uses the function syntax. Using the first one, I get a compiler error like this for `connect`:

```
Argument of type '(props: Props) => Element' is not assignable to parameter of type 'ComponentType<Matching<{ sum: number; clickCount: number; } & { count: (amount: number) => Promise<void>; }, Props>>'.
  Type '(props: Props) => Element' is not assignable to type 'FunctionComponent<Matching<{ sum: number; clickCount: number; } & { count: (amount: number) => Promise<void>; }, Props>>'.
    Types of parameters 'props' and 'props' are incompatible.
      Type 'PropsWithChildren<Matching<{ sum: number; clickCount: number; } & { count: (amount: number) => Promise<void>; }, Props>>' is not assignable to type 'Props'.
        Types of property 'count' are incompatible.
          Type '(amount: number) => Promise<void>' is not assignable to type 'CountThunk'.
            Type 'Promise<void>' is not assignable to type 'ThunkAction<Promise<void>, {}, {}, IncreaseSumAction | IncreaseCountAction>'.
              Type 'Promise<void>' provides no match for the signature '(dispatch: ThunkDispatch<{}, {}, IncreaseSumAction | IncreaseCountAction>, getState: () => {}, extraArgument: {}): Promise<void>'.
```

I also tested the issue with older versions, and it would seem the problem was introduced in version 6.0.10, which was published in 21st of November last year. The previous version 6.0.9, in which the problem didn't manifest, was published in September last year. Looking at the commits between the publishing times of those versions, it would seem [this is the commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/57ba1bcd755c8bc2aac0e74dadc50215d9127bed#diff-e17ae37682234ef10ed127a622634fcb) in which the problem was introduced.

I can try to fix this myself at some point when I have time if nobody's up to it before that. No idea how to fix it at the moment, but I'm sure it's doable.

**Comment by NathanNZ** [comment]
I've had a go at it and couldn't get it working - got a bit more to learn about Typescript before I have a go at something this complex unfortunately! 

Would really appreciate if someone could look into this at some point, currently using a hack on InferThunkActionCreatorType to just allow 'any' for a 'TReturn' type, but this kills type safety so not something I'd like to keep around for a long time!

**Comment by tuomokar** [comment]
Ok sorry, forgot to give an update to this. It would seem like the types were actually wrong before and allowed for use that it shouldn't have done. When we bind a thunk, that bound thunk doesn't have the same types as the thunk itself, because thunk returns a function with the `dispatch` and `getState` parameters, while a bound thunk returns whatever that function returns.

So correct use would be something like this:

```
import { ThunkAction } from 'redux-thunk'

// define a "thunk creator", i.e. how the thunk itself is defined
type ThunkCreator = (...args: any[]) => ThunkAction<any, any, any, any>

// Define the type for the bound thunk - basically the result of the function returned by the thunk. Accepts the thunk's parameters.
type BoundThunk<T extends ThunkCreator > = (...args: Parameters<T>) => ReturnType<ReturnType<T>>

// when defining the component types
interface IComponentProps {
  someThunkAction: BoundThunk<typeof someUnboundThunk>
}

// binding:
const mapDispatchToProps = {
  someThunkAction: someUnboundThunk
}

export default connect(mapStateToProps, mapDispatchToProps)(SomeComponent)
```

The thunk itself can be typed as you would type it otherwise (for example how I did it in the example repository for reproduction of the issue).

Hopefully this helps. I'm closing this issue as there's no problem after all but instead it works as it should now. Simply requires a small refactor to use the correct types for the bound thunks.
