### ISSUE TITLE
[@types/styled-components] StyledComponentProps intersection of props

### ISSUE THREAD

**Issue by erictaylor** [DefinitelyTyped/DefinitelyTyped#37413]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek, @Igmat, @Lavoaster, @Jessidhia, @JKillian, @eps1lon, @flavordaaave, @wagerfield.

---

I'm encountering a problem with how `StyledComponentProps` intersects the defined "other props" (ie `O`) with `React.ComponentPropsWithRef<C>` when `O` contains properties that are defined in the resulting type of `React.ComponentPropsWithRef<C>`.

Example:
```tsx
interface Props {
  color: string | (string | null)[] | { [key: string]: string };
}

const Box = styled.div<Props>``;

<Box color={['hello', null, 'world']} /> // Results in error on color prop.
```

Because `color` is defined as `color: string` from `React.ComponentPropsWithRef<'div'>`, it is getting intersected with the definition from `Props` resulting in a type of:

```
color: string | (string & (string | null)[]) | (string & { [key: string]: string; })
```

I encountered this when trying to use `styled-components` with [styled-system](https://github.com/styled-system/styled-system).

---

After diving into this issue for awhile, I can think of two possible solutions and need feedback from the authors before deciding on whether a PR to adjust `StyledComponentProps` is a solution or not.

**Option 1:**
Update the `StyledComponentProps` definition to omit the props from `React.ComponentPropsWithRef<C>` where `O`. Along the lines of:
```
WithOptionalTheme<Omit<ReactDefaultizedProps<C, Omit<React.ComponentPropsWithRef<C>, keyof O>> & O, A> & ...
``` 

**Option 2:**
Option 1 is found to not be an option (for some reason I can't forsee, that the authors can provide potential insight into), and therefor a suggestion to the `styled-system` library would be made to possibly rename the conflicting prop types (ie. `color` to `textColor`).

---

I'm more than happy to provide a PR for addressing this issue if a solution can be identified and feedback from the authors indicate that any proposed change would not cause other issues.

**Comment by forivall** [comment]
I prepared a PR to solve option 1, but then realized that it was not necessary for our needs.  Anyways, you can find it here: https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...forivall:forivall/styled-components-override if you need it 🤷‍♀

**Comment by tpict** [comment]
This is blocking my team's upgrade to Typescript 3.7, specifically the overlap of `color` props as described. For some reason, it's not been an issue on 3.6.x. @forivall would you mind opening a PR against that branch? 🙂

**Comment by erictaylor** [comment]
See #46850

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
