### ISSUE TITLE
[@types/i18next-node-fs-backend] Property 'type' is missing in type 'BackEnd' but required in type 'Module'.

### ISSUE THREAD

**Issue by maksimkurb** [DefinitelyTyped/DefinitelyTyped#37433]
Typings not working on i18next@17.0.7 and above

```ts
import i18next from 'i18next'
import i18nFsBackend from 'i18next-node-fs-backend'

i18next
      .use(i18nFsBackend) // <-- error here
      .init({
        ...
      })
```

```
TS2345: Argument of type 'typeof BackEnd' is not assignable to parameter of type 'Module | ThirdPartyModule[] | Newable<ThirdPartyModule>[] | Newable<Module>'.
  Type 'typeof BackEnd' is not assignable to type 'Newable<Module>'.
    Property 'type' is missing in type 'BackEnd' but required in type 'Module'.
```

Have installed deps:
i18next@17.0.7 (or above)
i18next-node-fs-backend@2.1.3
@types/i18next-node-fs-backend@0.0.30

Related: [i18next#1294](https://github.com/i18next/i18next/issues/1294)

**Comment by mgroenhoff** [comment]
Related as well: https://github.com/i18next/i18next/pull/1296#issuecomment-518632903

If no one has picked this up yet I can.

**Comment by mgroenhoff** [comment]
Blocked on https://github.com/i18next/i18next/pull/1308 and https://github.com/microsoft/types-publisher/pull/640
