### ISSUE TITLE
[react-select] Useful types are not exported

### ISSUE THREAD

**Issue by dobesv** [DefinitelyTyped/DefinitelyTyped#37444]
Authors: @claasahl @jonfreedman @Methuselah96

Types like `ValueType`, `OptionProps`, `Theme` are not exported from the top level package.  Importing them from the inner packages causes some issues because the JavaScript code tries to import those paths as well.

The fix is to figure out which types should be exported for use and add them to the index.d.ts

**Comment by Methuselah96** [comment]
I'm not sure I understand what the issue is. I'm able to import `ValueType` as such:
```
import { ValueType } from 'react-select/src/types';
```
Can you expand on why that doesn't work for you?

**Comment by dobesv** [comment]
Those subpaths aren't valid in JavaScript, so if the import isn't removed by TypeScript you'll get an import error.  I think maybe for `src/types` this doesn't cause a problem but modules that have classes in them won't have the import removed.

**Comment by dobesv** [comment]
Although, it seems like I can resolve my issue by importing OptionProps from that `src/types` instead of from `src/components/Option`.

**Comment by dobesv** [comment]
I do wonder if exporting the types from the root is more correct ... I'll leave the issue & PR open for discussion.

**Comment by dobesv** [comment]
Or perhaps I should just close it and leave the PR instead.
