### ISSUE TITLE
Update @types/cassandra-driver to 4.1 and support the concurrent execution API

### ISSUE THREAD

**Issue by wwarby** [DefinitelyTyped/DefinitelyTyped#37452]
- [ X ] I tried using the `@types/cassandra-driver` package and had problems.
- [ X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ X ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Svjard, @pc-jedi, @michal-b-kaminski

The types for cassandra-driver are missing the concurrent execution API. As far as I can tell the types for this library (4.0) were last updated in February and the concurrent execution API was introduced in April (4.1). See https://docs.datastax.com/en/developer/nodejs-driver/4.1/api/module.concurrent.

**Comment by pc-jedi** [comment]
Thanks for reporting this.
Have you already discovered some missing functions/parameters?

**Comment by wwarby** [comment]
Yeah, there's a static API at `cassandra.concurrent.executeConcurrent()` which is missing from the type definition, and the type that it returns, `ResultSetGroup` is missing along with the object that defines the input parameters to the function.

**Comment by pc-jedi** [comment]
@wwarby Sorry for taking so long. I've push a PR. May you want to have a look.

**Comment by wwarby** [comment]
Ah cool, thanks. I may be reading the PR wrong, but I don’t see the optional “options” parameter to executeConcurrent in the change?

**Comment by pc-jedi** [comment]
Thanks, please add this to the PR. I'll take a look
