### ISSUE TITLE
Ramda: filter used along with sortBy in pipe results in type error

### ISSUE THREAD

**Issue by vicrac** [DefinitelyTyped/DefinitelyTyped#37454]
Hi,

I originally posted this issue at ramda's repo (https://github.com/ramda/ramda/issues/2876), and I got redirected here. Simple use case: filtering a list of objects and then sorting it by some property is crashing on types. I made the simplest possible reproduction (althought I had to bootstrap a whole Angular app for that, since Ramda REPL doesn't work with typescript and with typescript REPL one cannot add Ramda as dep): https://stackblitz.com/edit/angular-vwm9fc. (I used latest versions of both tsc, ramda, and types)

  - Authors: @googol

**Comment by googol** [comment]
You'll get it to work like so:
```
  R.filter<CalendarItem, 'array'>((item) => item.date < today),
```

There hasn't been any good ideas on how to actually fix the problem with filter inside a pipe, so we've built this workaround for it. I hope it helps

**Comment by vicrac** [comment]
Thanks for help, it solved my problem :) I think this workaround is worth adding to some docs, if you maintain any (I spend a nice deal of time to find it behore I opened issue).
