### ISSUE TITLE
@types/ioredis is missing lrangeBuffer and lpopBuffer

### ISSUE THREAD

**Issue by thmiyathmary** [DefinitelyTyped/DefinitelyTyped#37461]
- [x] I tried using the `@types/ioredis` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @plantain-00 @chrisleck @aliarham11 @br8h 

In `ioredis`, `lrangeBuffer()` and `lpopBuffer()` exist and I actually using them.
However, they doesn't exist in `@types/ioredis`.
Please add them.

Those definitions are maybe as follows:
- lrangeBuffer(key: KeyType, start: number, stop: number, callback: (err: Error, res: Buffer) => void)
- lpopBuffer(key: KeyType, callback: (err: Error, res: Buffer) => void): void

This is my first issue so I ’m sorry if they're wrong.

**Comment by plantain-00** [comment]
You can create a Pull Request to fix this

**Comment by thmiyathmary** [comment]
I'v created a PR and it was merged.
Thank you for approving my PR!
