### ISSUE TITLE
[fluent] Upstream renamed packages

### ISSUE THREAD

**Issue by Seally** [DefinitelyTyped/DefinitelyTyped#37541]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @JamesNimlos @huy-nguyen 

Apparently, the various NPM packages for Fluent have been renamed and old package names have been deprecated, so anyone who switched to the new names will likely have broken types for the time being:

* `fluent` => `@fluent/bundle` (starting from 0.13)
* `fluent-syntax` => `@fluent/syntax` (starting from 0.14)
* `fluent-langneg` => `@fluent/langneg` (starting from 0.3.0)
* `fluent-react` => `@fluent/react` (starting from 0.9.0)

(Same pattern for other packages, but those don't seem to have been typed yet). I might do a PR for this eventually, but I'm a bit preoccupied at the moment.

~_Note:_ To anyone who searched for this issue, renaming the package from something like `node_modules/@types/fluent` to `node_modules/@types/fluent__bundle` should act as a workaround.~
My investigation on the changes reveal that there are significant interface changes (thanks to wiml for noting that) in the latest versions compared to the ones in DefinitelyTyped, enough that without an update to the type definitions, it's almost unusable if you're using the latest version of `@fluent/bundle`. Renaming the installed package alone won't be enough.

**Comment by wiml** [comment]
There are a handful of other changes mentioned in [the changelog](https://github.com/projectfluent/fluent.js/releases) which should probably be reflected in the type definitions as well: e.g, the `ftl` helper is in its own package now, the `fromString` method is gone from FluentResource.

**Comment by JamesNimlos** [comment]
I think this can be closed by #40179 which was the successor to #38836

**Comment by Seally** [comment]
I'll close this for now, although there's currently movement to convert upstream packages to TypeScript (which is a different issue anyway): https://github.com/projectfluent/fluent.js/pull/436
