### ISSUE TITLE
mongodb: $nin types are wrong when field is an array

### ISSUE THREAD

**Issue by liorcode** [DefinitelyTyped/DefinitelyTyped#37616]
Seems that yesterday's commit (#37467) in mongodb types broke something:
@HosseinAgha added better types for `FilterQuery` which is great - but it doesn't cover some of the valid queries:
In my case it doesn't cover cases where a field is an array and `$nin` is used to match it against another array (which is supported by mongo (https://docs.mongodb.com/manual/reference/operator/query/nin/)

In the new type, `$nin` was defined as `T[]` but it's not necessarily the case - when `T` is already an array, the type here would become an array of arrays - which is wrong
Query example: `find({ tags: { $nin: [ "school" ] } })` - in that query, when tags is already an array, mongo will match documents with tags that do no include "school"

I guess a naive approach to solve it would just be to just the $nin type to `T | T[]` but not sure.

The 2nd problem i've encountered is a little more complicated - with $ne (but probably also for other comparisons): the type specified for it is `T`, but mongo also allows to compare different types: you can compare a single value array (`[1]`) to a value (`1`) and it works (https://docs.mongodb.com/manual/reference/bson-type-comparison-order/#arrays)

Please help 🙏

**Comment by HosseinAgha** [comment]
Hi @liorcode, 
Thank you for finding this bug. I'm currently working on a better more extensive tests for mongodb types in #37595. I'll add this scenario to the tests and will fix the issue.

**Comment by liorcode** [comment]
Thanks! note that i've edited my original message to cover another case, so you could add it to your tests as well 👍

**Comment by HosseinAgha** [comment]
@liorcode 
  - I fixed the problem with `$nin` and generally arrays
  - I don't think the point you are making on the comparing using different types is valid. [The article you provided](https://docs.mongodb.com/manual/reference/bson-type-comparison-order/#arrays) is about comparison order not comparing different types. 
  - On comparing different types here is what [the docs](https://docs.mongodb.com/manual/reference/operator/query/lt/index.html) say:  
   > For most data types, comparison operators only perform comparisons on fields where the BSON type matches the query value’s type. MongoDB supports limited cross-BSON comparison through [Type Bracketing](https://docs.mongodb.com/manual/reference/method/db.collection.find/#type-bracketing). 

In case of type bracketing the documentation mentions numbers only and is very vague about how it is going to treat numbers. Again I'd be happy if you provide a working query.

**Comment by liorcode** [comment]
Thanks for the fix @HosseinAgha!
As for the article I linked to, I was referring to this point:
> when comparing a field whose value is a single-element array (e.g. [ 1 ]) with non-array fields (e.g. 2), the comparison is between 1 and 2

Example: 
Given the documents 
```
[
  { tags: ["foo"] },
  { tags: ["bar"] },
  { tags: ["foo", "bar"] }
]
```
This query would select only the 2nd document - acting kinda like `$nin`
`find({ tags: { $ne: "foo" }})` 

(Yes, a little weird and might seem wrong, but valid. I actually had a working code with exactly this, which broke after the type change..)

**Comment by HosseinAgha** [comment]
OK I cover this case in my PR. You can now query by element type everywhere a field is an array.

**Comment by HosseinAgha** [comment]
OK. according to the official mongodb docs what you are saying here is not supported and leads to [unexpected results](https://docs.mongodb.com/manual/reference/operator/query/not/#not-and-data-types). Please also take a look at [this answer](https://stackoverflow.com/a/9791031/2245902).  
If I perform `$not` on a normal field I get error `"$not needs a regex or a document"`.  
I'll add the regex case by the way. Thank you again for the comments.

**Comment by liorcode** [comment]
Note that I was referring to `$ne` - (not equal) and not to `$not` which works differently: `$ne` only does `equal` comparison and not regex, and does support comparing single-element arrays to a value.
Thanks again for the fix

**Comment by HosseinAgha** [comment]
Oh sorry. In this case it should be fixed by the #37595.

**Comment by HosseinAgha** [comment]
@liorcode #37595 is merged. Could you update to `v3.2.3` and see if your issues are fixed?

**Comment by liorcode** [comment]
Seems all is fixed, thanks!

**Comment by HosseinAgha** [comment]
@liorcode I think you can close this now :)
