### ISSUE TITLE
`featurePolicy` is not included in Helmet package

### ISSUE THREAD

**Issue by danieldanielecki** [DefinitelyTyped/DefinitelyTyped#37627]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/helmet` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow, featurePolicy doesn't exists](https://stackoverflow.com/questions/57497817/ts2339-property-featurepolicy-does-not-exist-on-type-helmet).
- [x] Mention the authors, so they can respond.
  - Authors: @chdanielmueller

The [Helmet ](https://helmetjs.github.io/docs/) package introduced [featurePolicy](https://helmetjs.github.io/docs/feature-policy/), and this is missing in [these lines](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/helmet/index.d.ts#L13-L27).

**Comment by chdanielmueller** [comment]
@EvanHahn

**Comment by EvanHahn** [comment]
I intend to add full TypeScript support into Helmet (eventually removing files from DefinitelyTyped). However, Helmet is something I maintain in my spare time, so I may not get to it soon. I do not expect to be able to make a PR, but am happy to review something.

For what it's worth, the `feature-policy` module (`helmet.featurePolicy` is just an alias to this module) has TypeScript type definitions built in. You may be able to use that instead.
