### ISSUE TITLE
[@types/react] Incorrect type definitions for React.forwardRef

### ISSUE THREAD

**Issue by EvanPurkhiser** [DefinitelyTyped/DefinitelyTyped#37660]
- [x] I tried using the `@types/react@^16.7` package and had problems.
- [x] I tried using the latest stable version of tsc. `3.5.3`
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon

---

When using `React.forwardRef` I would like to add some `propTypes` and `defaultProps` to the returned component. The definition for the function is:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1709112cb66b86035ea8af59448424a5dc772010/types/react/index.d.ts#L730

Which returns a `ForwardRefExoticComponent`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1709112cb66b86035ea8af59448424a5dc772010/types/react/index.d.ts#L724-L728

If you follow the type extensions you will see it does not define `propTypes` as an allowed attribute.

Thus you cannot define `propTypes`, only `defaultProps`.

However looking at the argument accepted, `RefForwardingComponent`:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1709112cb66b86035ea8af59448424a5dc772010/types/react/index.d.ts#L503-L509

Seems to imply that you can have `propTypes` on the function passed, for example:

```tsx
const ExternalLink: React.RefForwardingComponent<
  HTMLAnchorElement,
  React.HTMLProps<HTMLAnchorElement>
> = ({href, ...otherProps}, ref) => <a ref={ref} {...otherProps} href={href} />;

ExternalLink.propTypes = {
  href: PropTypes.string.isRequired,
  target: PropTypes.string,
  rel: PropTypes.string,
};

// Should we allow these to be overridden?
ExternalLink.defaultProps = {
  target: '_blank',
  rel: 'noreferrer noopener',
};

export default React.forwardRef(ExternalLink);
```

However, doing this will produce the runtime error:

```
Warning: forwardRef render functions do not support propTypes or defaultProps. Did you accidentally pass a React component?
```

Seems like the types here are wrong?

**Comment by ar53n** [comment]
And with ForwardRef i can't use children props

**Comment by heyikang** [comment]
I encountered similar problems

codesandbox: https://codesandbox.io/s/summer-wave-2py0v

**Comment by andrew-chang-dewitt** [comment]
> 
> 
> And with ForwardRef i can't use children props

@heyikang did you ever find a solution to this? I'm struggling to find one anywhere.
