### ISSUE TITLE
[@types/oracledb] Connection.execute does not allow Buffer as bind value

### ISSUE THREAD

**Issue by doberkofler** [DefinitelyTyped/DefinitelyTyped#37677]
Dear @Bigous and  @connorjayfitzgerald !

I'm using oracledb 4.0.0 and the `BindParameters` type used in execute does not seem to allow to use a type `Buffer` that is needed to bind a `BLOB` value.
The oracledb documentation allows to bind a Buffer and the code actually works as expected.

Example:
```TypeScript
const blobContent = fs.readFileSync('somefile');
const bind = {
	name: filename,
	content: blobContent
};
await connection.execute('INSERT INTO myTable (name, content) VALUES (:name, :content)', bind, {});
``` 

The execute reports a type error as follows:
```
example.ts:42:92 - error TS2345: Argument of type '{ name: string; content: Buffer; }' is not assignable to parameter of type 'BindParameters'.
  Type '{ name: string; content: Buffer; }' is not assignable to type 'Record<string, string | number | Date | BindParameter | DBObject | null>'.
    Property 'content' is incompatible with index signature.
      Type 'Buffer' is not assignable to type 'string | number | Date | BindParameter | DBObject | null'.
        Type 'Buffer' is missing the following properties from type 'DBObject': attributes, elementType, elementTypeClass, elementTypeName, and 16 more.

42  	await connection.execute('INSERT INTO myTable (name, content) VALUES (:name, :content)', bind, {});
```

This is a basic example:
[Archive.zip](https://github.com/DefinitelyTyped/DefinitelyTyped/files/3510117/Archive.zip)

**Comment by connorjayfitzgerald** [comment]
Hi @doberkofler 

I'll update the definition now so that it will work. In the meantime, you should be able to get around it by changing your bind variable to:

```javascript
const bind = {
	name: filename,
	content: {
              val: blobContent,
              type: oracledb.BUFFER
        }
};
```

**Comment by connorjayfitzgerald** [comment]
See #37678

**Comment by doberkofler** [comment]
Excellent. Thank you!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
