### ISSUE TITLE
Definition Request: connect-redis

### ISSUE THREAD

**Issue by AyaMorisawa** [DefinitelyTyped/DefinitelyTyped#3772]
https://github.com/tj/connect-redis

**Comment by Xstoudi** [comment]
Pull request here #8336

**Comment by hinell** [comment]
@mhegazy close this issue please. The linked PR is already merged.

**Comment by iamclaytonray** [comment]
This issue can be closed.

**Comment by XBeg9** [comment]
Close this issue :)
