### ISSUE TITLE
@types/graphql-relay: Support latest version

### ISSUE THREAD

**Issue by ravishivt** [DefinitelyTyped/DefinitelyTyped#37783]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Arvitaly, @nitintutlani, @Grelinfo

The @types/graphql-relay targets graphql-relay v0.4.0.  The current version is v0.6.0.  This is preventing me from upgrading graphql and graphql-relay.

**Comment by kambleaa007** [comment]
do any one had idea of how to resolve

**Comment by ravishivt** [comment]
With the changes made in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37830, I no longer have compatibility issues.  Closing this.
