### ISSUE TITLE
[@types/theme-ui] ColorModes seems to need an additional level of nesting

### ISSUE THREAD

**Issue by erikdstock** [DefinitelyTyped/DefinitelyTyped#37838]
Raising from here:
https://github.com/system-ui/theme-ui/issues/121#issuecomment-523594570

cc @ifiokjr @sbardian 

In short the [ColorModes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0de3688b30e6e49f620930e14f3e7f7223fce204/types/theme-ui/index.d.ts#L42-L53) interface appears to really be more of a `ColorMode` (singular) so should be nested within a `[k: string]: { /* ColorMode */ }` bit.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by sbardian** [comment]
Working on the PR now.  Thanks @erikdstock
