### ISSUE TITLE
[@types/react-redux] 'connect' only works with classes defined in the same file where it's used

### ISSUE THREAD

**Issue by DBosley** [DefinitelyTyped/DefinitelyTyped#37844]
- [x] I tried using the `@types/react-redux` package and had problems.
  - Tried with `@types/react-redux` 7.1.2
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Tried with Typescript 3.5.3
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo @Kallikrein @val1984 @jrakotoharisoa @apapirovski @surgeboris @soerenbf @MrWolfZ 

When using the `connect` function, I get type errors when the component I'm connecting is imported. Adding a dumb container component to the same file where connect is called seems to fix the issue.

Examples:
Both examples use this component:
```
// MyComponent.tsx
import React from 'react';

export interface MyComponentOwnProps {
  foo: number;
}

export interface MyComponentMappedProps {
  bar: number;
}

export default class MyComponent extends React.Component<MyComponentOwnProps & MyComponentMappedProps> {}
```

This does not work:

```
// MyComponentContainer.tsx
import React from 'react';
import { connect } from 'react-redux';
import MyComponent, { MyComponentMappedProps } from './MyComponent';

const mapStateToProps = (state): MyComponentMappedProps => {
  return {
  bar: 0
  };
};

export default connect(mapStateToProps)(MyComponent);
```

This does work:
```
// MyComponentContainer.tsx
import React from 'react';
import { connect } from 'react-redux';
import MyComponent, { MyComponentMappedProps, MyComponentOwnProps } from './MyComponent';

class MyComponentContainer extends React.Component<
  MyComponentMappedProps & MyComponentOwnProps
> {
  render(): JSX.Element {
    return <MyComponent {...this.props}></MyComponent>;
  }
}

const mapStateToProps = (state): MyComponentMappedProps => {
  return {
    bar: 0
  };
};

export default connect(mapStateToProps)(MyComponentContainer);
```

I'm not sure if this is a problem with the type definitions, or with typescript itself.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
