### ISSUE TITLE
[@types/heremaps] Static fields of H.mapevents.Pointer

### ISSUE THREAD

**Issue by papiliond** [DefinitelyTyped/DefinitelyTyped#37859]
If you know how to fix the issue, make a pull request instead.

- [X ] I tried using the `@types/xxxx` package and had problems.
- [X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Josh-ES @denyo @fx88 @life777 

When trying to access any property of class `H.mapevents.Pointer`, for example `viewportY`, I get the following compiler error:
`Property 'viewportY' is a static member of type 'Pointer'ts(2576)`

Why it has to be static? In class `H.mapevents.Event` the `pointers`, `changedPointers`, etc. hold dynamic information about pointer events. Aren't they?

Thank you!

**Comment by denyo** [comment]
For me it's hard to say anything without a code sandbox. 
About your question, it's static because the docs say it is and the typings are based on the docs: https://developer.here.com/documentation/maps/topics_api/h-mapevents-pointer.html

**Comment by AndyMeps** [comment]
I've just come across this issue myself. It's definitely an instance type, not static; I'm happy to raise a PR for this, will it get rejected if the here.com docs don't match?

http://jsfiddle.net/n9tvjfe8/
