### ISSUE TITLE
@types/googlemaps/index.d.ts is not a module

### ISSUE THREAD

**Issue by denis132vilu** [DefinitelyTyped/DefinitelyTyped#37932]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by ziyaddin** [comment]
Could you explain your specific use case that caused this issue?

**Comment by RobertAKARobin** [comment]
@ziyaddin I have this same error. I'm running an Angular 8 app. I run:

```
npm i @types/googlemaps
```

Then, in a component file, I include:

```js
import {} from 'googlemaps';
```

I receive the error:

```
...'node_modules/@types/googlemaps/index.d.ts' is not a module.
```

**Comment by alambertt** [comment]
Me too

**Comment by ziyaddin** [comment]
@RobertAKARobin @alambertt try the following steps:
1. `npm install @types/googlemaps --save-dev`
2. add `"types": ["googlemaps"]` in `tsconfig.app.json` file

**Comment by jaiminp-nimblechapps** [comment]
@ziyaddin 

This also worked for me on Angular 8. Thank you so much!

**Comment by alambertt** [comment]
> @RobertAKARobin @alambertt try the following steps:
> 
> 1. `npm install @types/googlemaps --save-dev`
> 2. add `"types": ["googlemaps"]` in `tsconfig.app.json` file
> 3. remove `import {} from 'googlemaps';` from your code.

I wrote in the first line of my .ts this code and worked 100%
`/// <reference types="@types/googlemaps" />`

**Comment by jedicursandroidsayhello** [comment]
> > @RobertAKARobin @alambertt try the following steps:
> > 
> > 1. `npm install @types/googlemaps --save-dev`
> > 2. add `"types": ["googlemaps"]` in `tsconfig.app.json` file
> > 3. remove `import {} from 'googlemaps';` from your code.
> 
> I wrote this in the first line of my .ts and worked 100%
> `/// <reference types="@types/googlemaps" />`

Where did you added exactly?

**Comment by pradeekumar** [comment]
> > > @RobertAKARobin @alambertt try the following steps:
> > > 
> > > 1. `npm install @types/googlemaps --save-dev`
> > > 2. add `"types": ["googlemaps"]` in `tsconfig.app.json` file
> > > 3. remove `import {} from 'googlemaps';` from your code.
> > 
> > 
> > I wrote this in the first line of my .ts and worked 100%
> > `/// <reference types="@types/googlemaps" />`
> 
> Where did you added exactly?

index.html

**Comment by afogli** [comment]
add "types": ["googlemaps"] in tsconfig.app.json file 
in section "compilerOptions":  work for me
