### ISSUE TITLE
@types/react-relay ^5.0.0 QueryRendererProps and ReadyState removed

### ISSUE THREAD

**Issue by akomm** [DefinitelyTyped/DefinitelyTyped#37950]
- [x] I tried using the `@types/react-relay` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @graphcool @voxmatt @alloy @npirotte @ckknight @kastermester @mattkrick 

I just updated react-relay/runtime from version ^3.0.0 to ^5.0.0 to fix a bug and also the types accordingly. You have removed `QueryRendererProps` and `ReadyState` types and defined them as literal types in `QueryRenderer`. I could not find any replacement for them. This is a real issue, especially how you have done it (not possible to regain them via conditional infer for example). There is no way using custom react hooks or hoc for the QueryRenderer anymore, except copying all the literal prop types from the definition file into own code, which is terrible idea.

Any way to reintroduce the types back?

An example, what is made hard now with the new recent typings:
```tsx
import {useCallback, useMemo} from "react";
import * as React from "react";
import {QueryRenderer, QueryRendererProps, ReadyState} from "react-relay";
import {OperationBase} from "relay-runtime";
import QueryRendererError from "../components/Error/QueryRendererError";
import QueryRendererLoading from "../components/LoadingIndicator/QueryRendererLoading";

type RenderHandlers<
  Operation extends OperationBase
> = {
  renderLoading?: () => React.ReactNode,
  renderError?: (
    error: ReadyState<Operation>['error'],
    retry: ReadyState<Operation>['retry']
  ) => React.ReactNode,
  render: (
    props: Operation['response'],
    reload: ReadyState<Operation>['retry'],
  ) => React.ReactNode,
};

export default function useQueryRenderer<
  Operation extends OperationBase,
>({
  renderLoading,
  renderError,
  render,
  ...props
}: Omit<QueryRendererProps<Operation>, 'render'> & RenderHandlers<Operation>) {
  const _render = useCallback(({props, error, retry}: ReadyState<Operation>) => {
    if (error) {
      return renderError
        ? renderError(error, retry)
        : (<QueryRendererError message={error.message || String(error)} retry={retry}/>);
    }
    if (!props) {
      return renderLoading ? renderLoading() : (<QueryRendererLoading/>);
    }
    return render(props, retry);
  }, [render, renderError, renderLoading]);

  return useMemo(() => (
    <QueryRenderer<Operation>
      {...props}
      render={_render}
    />
  ), [_render, props]);
}
```

**Comment by alloy** [comment]
It is possible to get the typing back, e.g. see [this example](https://github.com/artsy/emission/blob/123f8987bcf2b8c80a92c191fb0755e2c06d3ed1/src/lib/utils/renderWithLoadProgress.tsx#L7), but I’m not against merging a PR that exports the type as a separate type alias again 👍

**Comment by akomm** [comment]
I have to check this tomorrow. I actually tried using `React.ComponentProps<typeof QueryRenderer>` as first choice and It did not work, I can not recall for what reason now.

**Comment by nirvdrum** [comment]
I've hit upon a case where exporting `QueryRendererProps` would be very handy. I'm using `found-relay`, which doesn't provide type definitions itself. It augments `found`'s `Route` component to add inject Relay's renderer props into `Route#render`. Given the lack of definition from `found-relay`, I'd like to provide my own interface definition that extends from `QueryRendererProps`, combining the properties from `QueryRendererProps` and the normal set of props passed to `Route#render`.

I'm still fairly new to TypeScript, so if there's a better way to do this given the current definitions, please let me know. Otherwise, I'll look at a PR to export `QueryRendererProps` again.

**Comment by nirvdrum** [comment]
For the time being, I've used @alloy's sample and then explicitly added properties for `match` and `variables` into my new interface. This might be the way to go anyway because I don't believe `found-relay` provides the `query` property.

**Comment by akomm** [comment]
I just skipped on it, because it use the relay-hooks query hook now.

**Comment by alloy** [comment]
👍 

Going to close this. Suggestion to create a PR still stands for any future readers.
