### ISSUE TITLE
[@types/styled-components] Filter prop when extending styles of a component

### ISSUE THREAD

**Issue by CodingDive** [DefinitelyTyped/DefinitelyTyped#37972]
I tried to get an example to work where a component is extended and some props that should not be forwarded to the component need to be filtered. https://www.styled-components.com/docs/api#using-custom-props

```TSX
import styled from 'styled-components'
import Header, { Props as HeaderProps } from './Header'

const Title =
  styled <
  { isActive: boolean } >
  (({ isActive, ...rest }) => <Header {...rest} />)`
  color: ${props => (props.isActive ? props.theme.primaryColor : props.theme.secondaryColor)}
`
```

Fails for me with following error

```
Type '{ isActive: boolean; }' does not satisfy the constraint '"symbol" | "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | "canvas" | ... 156 more ... | FunctionComponent<...>'.
  Type '{ isActive: boolean; }' is not assignable to type 'FunctionComponent<any>'.
    Type '{ isActive: boolean; }' provides no match for the signature '(props: any, context?: any): ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)> | null'.ts(2344)
```

- [ x ] I tried using the `@types/styled-components` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- Authors: @flavordaaave feel free to link some other type authors but you were the only one that showed up on GitHub for me.

**Comment by rhyek** [comment]
I'm having this exact issue. What is the fix? Using `@types/styled-components@4.1.19`.

**Comment by kirill-konshin** [comment]
Same thing here. Looks like still not fixed.

**Comment by GuruM** [comment]
For whomever comes upon this in the future, @dan-kez's answer here worked for me: https://github.com/styled-components/styled-components-website/pull/445#issuecomment-487251588

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
