### ISSUE TITLE
[@types/prop-types] IsOptional should not care about nulls

### ISSUE THREAD

**Issue by davidje13** [DefinitelyTyped/DefinitelyTyped#37999]
Authors: @DovydasNavickas @ferdaber @eps1lon

The definition of IsOptional currently reads:

```ts
export type IsOptional<T> = undefined | null extends T ? true : undefined extends T ? true : null extends T ? true : false;
```

As far as I can tell, this was added long ago in ffc83511271dfdb1646e22e69be3b243cd5b8e26 but with no reasoning for the complexity of the check.

It breaks for me, because I [explicitly distinguish between `null` and `undefined`](https://github.com/davidje13/prop-types-nullable/blob/master/index.js) in my types (and I am not the only one; https://github.com/facebook/react/issues/3163). This is necessary to ensure correct JSON representations.

This means that when I define PropTypes for an object which can have a nullable (but not undefinable) field, `InferProps` incorrectly claims that the field can be undefined.

Example: I use code similar to the following to ensure the various representations of types in my project do not go out-of-sync:

```ts
import PropTypes from 'prop-types';
import nullable from 'prop-types-nullable';

/// prop-types-nullable declares the following:
// interface NullableRequireable<T> extends Validator<T | null> {
//   isRequired: Validator<Exclude<T | null, undefined>>;
// }
// function nullable<T>(
//   type: Validator<T>,
// ): NullableRequireable<T | undefined>;

interface MyType {
  requiredString: string;
  nullableString: string | null;
}

const propTypesMyType: PropTypes.Requireable<MyType> = PropTypes.shape({
  requiredString: PropTypes.string.isRequired,
  nullableString: nullable(PropTypes.string).isRequired,
});

// Type 'Requireable<InferProps<{ requiredString: Validator<string>; nullableString: Validator<string | null>; }>>' is not assignable to type 'Requireable<MyType>'.
//   Type 'InferProps<{ requiredString: Validator<string>; nullableString: Validator<string | null>; }>' is not assignable to type 'MyType'.
//     Types of property 'nullableString' are incompatible.
//       Type 'string | null | undefined' is not assignable to type 'string | null'.
//         Type 'undefined' is not assignable to type 'string | null'.
```

---

I believe the declaration could be changed to:

```ts
export type IsOptional<T> = undefined extends T ? true : false;
```

which is simpler and appears to be more correct.

**Comment by eps1lon** [comment]
This is unfortunately how `prop-types` defines optional types (which originates from flow I think).

```jsx
class Component extends React.Component {
  static propTypes = { message: PropTypes.string };

  render() {
    return null;
  }
}


<Component />;
<Component message={undefined} />;
<Component message={null} />;
```
will not throw a prop-type warning since in every instance prop-types will consider `message` as absent while
```js
class Component extends React.Component {
  static propTypes = { message: PropTypes.string.isRequired };

  render() {
    return null;
  }
}


<Component />;
<Component message={undefined} />;
<Component message={null} />;
```
will throw an error for every instance but not because the types mismatch but because they're not specified (as far as prop-types is concerned).

Since you already found https://github.com/facebook/react/issues/3163 I'm not sure what we're supposed to do here. This is the runtime behavior which we're expressing in types. If you disagree with the runtime behavior then you should share your use case at the repository responsible for the runtime.

**Comment by davidje13** [comment]
@eps1lon that may be the core behaviour, but as you can see in the repository I linked to, it's trivial to extend the behaviour to allow this distinction while staying within the bounds of the library (i.e. there's no library modification going on here).

Really this comes down to supporting custom PropType implementations, which is a supported use-case for PropTypes. In this case, my custom PropType is handling `null` and `undefined` separately. This works perfectly at runtime; it's just the TypeScript types which have a problem.

Is there any reason for the complicated `IsOptional` check? I can't see any reason why changing it to only check for `undefined` would cause problems.

**Comment by eps1lon** [comment]
> Is there any reason for the complicated IsOptional check? I can't see any reason why changing it to only check for undefined would cause problems.

There's only one way to find out: Change the definition, run the tests and open a PR. I can only tell you how we got here.

**Comment by ferdaber** [comment]
When I first added the prop-types types I had to add both checks in the conditional type to detect both null and undefined, so the behavior might’ve changed since then (on the TS side, that is)
