### ISSUE TITLE
[@types/webpack] No types available when exporting the configuration as a function

### ISSUE THREAD

**Issue by astorije** [DefinitelyTyped/DefinitelyTyped#37998]
- [x] I tried using the `@types/webpack` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo, @bumbleblym, @bcherny, @tommytroylin, @mohsen1, @jcreamer898, @alan-agius4, @elliottsj, @jason0x43, @dennispg, @christophehurpeau, @ZSkycat, @johnnyreilly, @rwaskiewicz, @kuehlein, @grgur, @rubenspgcavalcante

The Webpack configuration can be exported as a function instead of an object: https://webpack.js.org/configuration/configuration-types/#exporting-a-function

The function has 2 arguments and returns a `Configuration`. As far as I know, there is no typing available for this function or the arguments. We (currently) only use the `mode` property of the second argument, so we are currently doing something like this:

```tsx
export default (
  _env: unknown,
  argv: { mode: Configuration['mode'] },
): Configuration => ({ /* ... */ });
```

But it would be nice to have a more accurate type definition for this.
Thanks for the hard work!

**Comment by rubenspgcavalcante** [comment]
Hey @astorije , thanks for the feedback. I opened a PR with the alterations following the Webpack documentation :)

**Comment by astorije** [comment]
This is awesome news, thank you so much @rubenspgcavalcante!

**Comment by astorije** [comment]
Thanks for your PR, @rubenspgcavalcante!
I've looked at it and I'm still not 100% sure how to resolve what made me open this issue. How would you type this in a Webpack configuration file?

I was initially hoping to be able to do something like the following:

```ts
const webpackConfig: ConfigurationFn = (env,  argv) => ({ /* ... */ });
export default webpackConfig;
```

**Comment by rubenspgcavalcante** [comment]
Ah got it, I can make an alias and expose the configuration factory, let me create a new issue and open another PR
