### ISSUE TITLE
[@types/react-select] StateManager props definition

### ISSUE THREAD

**Issue by jbojcic1** [DefinitelyTyped/DefinitelyTyped#38009]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.th
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @claasahl @jonfreedman @Methuselah96 @thchia 

I wanted to create wrapper component around react-select component and since I am using typescript I wanted to reuse props interface and just extend it but I wasn't able to find one interface that has all the props. Am I missing something?

Also when I look into the ts definitions, it seems that state manager props are built from couple of interfaces/types like this:

```
StateProps<SelectProps<OptionType>> & Props<OptionType> & SelectProps<OptionType>
```

where state props is:

```
type StateProps<T extends SelectProps<any>> = Pick<T, Exclude<keyof T,
  | 'inputValue'
  | 'value'
  | 'menuIsOpen'
  | 'onChange'
  | 'onInputChange'
  | 'onMenuClose'
  | 'onMenuOpen'
>>;
```

so I am wondering what is the point of taking subset of `SelectProps` with `StateProps<SelectProps<OptionType>>` and then doing & with `SelectProps` again. Am I missing something or result will again have all properties from `SelectProps`?

**Comment by jonfreedman** [comment]
There's an example of a wrapper @ https://github.com/mui-org/material-ui/blob/master/docs/src/pages/components/autocomplete/IntegrationReactSelect.js

Unfortunately adding types to this is a bit of work that I can't share however it is possible to create a type safe wrapper with styles [using a hook](https://stackoverflow.com/questions/55512097/how-do-i-export-a-typescript-react-component-which-uses-material-ui-withstyles).

I'm not sure what you're trying to do - if you want to allow all of the use cases (e.g. asyc, creatable, multi) you'll either need to union the types yourself, or have separate wrappers.  Specifically with the StateManager type, we only use that to maintain a reference e.g.

```typescript
private readonly selectRef: React.RefObject<StateManager<TI>>;
```

**Comment by gricey432** [comment]
That link is gone

**Comment by JKirchartz** [comment]
> There's an example of a wrapper @ https://github.com/mui-org/material-ui/blob/master/docs/src/pages/components/autocomplete/IntegrationReactSelect.js


This link is dead, here's one that work: https://github.com/mui-org/material-ui/blob/v4.5.2/docs/src/pages/components/integrated-autocomplete/IntegrationReactSelect.tsx

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
