### ISSUE TITLE
Invalid property name 'proccess'

### ISSUE THREAD

**Issue by digitaloc** [DefinitelyTyped/DefinitelyTyped#38004]
Authors: @skovy 

Definition of [cssProcessor ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/optimize-css-assets-webpack-plugin/index.d.ts) looks like:

`        
cssProcessor?: {
            proccess: (css: string, options?: object) => PromiseLike<any>;
        };
`

Shouldnt't it be like this? Without additional **c** letter.
`        
cssProcessor?: {
            process: (css: string, options?: object) => PromiseLike<any>;
        };
`

**Comment by skovy** [comment]
@digitaloc ah yes, you're definitely correct 🤦‍♂I'm happy to review a PR with the fix 👍
