### ISSUE TITLE
Feature Request: Add schema properties to document interface for mongoose

### ISSUE THREAD

**Issue by kerolloz** [DefinitelyTyped/DefinitelyTyped#38013]
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @danmana @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig 
---
after defining a schema and creating a model, the created documents don't have type inference according to their defined schema.

for [example](https://www.typescriptlang.org/play/index.html?esModuleInterop=true&target=2#code/JYWwDg9gTgLgBCCA7A5hCBnApnAZlCEOAckVXW2IG4AoAY2Q3gzoAssQBDOAXjiSwB3BMjSYsAOgDKbDpwAUAbxpx+nEFgBccZatUwAnmC1wpMKMFQq4AXxo2AlLXqN4AVWxReI8uImIAEywAG3kAIg8sKDCAGjgWdi4nGhckJjgAV09vAWFIqCU1DW0wgCkIViQw22SGNIhgyWCIFHksqIkkdSxkoA)
![image](https://user-images.githubusercontent.com/36763164/63966318-45b8ee80-ca9b-11e9-9e97-1b2bf0bfcfb5.png)
name property doesn't exist when you inspect the possible options as in the screenshot before.
what I want is that I can see the properties and methods that I have defined for the schema appear.
is that possible?

**Comment by jussikinnula** [comment]
@kerolloz, I have done it like this (sorry, the example is old - but still valid for Mongoose parts): https://github.com/jussikinnula/angular-mean-starter/blob/master/src/models/todo.model.ts

**Comment by kerolloz** [comment]
@jussikinnula
I always have to do that with all my models. It's kind of boring to write a schema then write an interface for the documents which will look almost the same as the schema definition. When you have like 10 models and each one has like 8 or so properties it makes me feel like I'm copying and pasting code. I believe it would be concise if we can figure out a solution for that.

**Comment by jussikinnula** [comment]
@kerolloz, yes actually it might be possible to create a Mongoose schema to model transformer. But I would personally think that as heresy, since logical abstraction and types should be designed so that logical models and data layer would be separate.

I often do this also for Mongoose, so that I create logical model for example `User` and an interface `IUser` which the model implements. Then I just create a Mongoose model for data saving which uses `IUser` as blueprint. It adds many benefits like later transforming project to AWS DynamoDB or repartitioning MongoDB tables.

**Comment by kerolloz** [comment]
> @kerolloz, yes actually it might be possible to create a Mongoose schema to model transformer. 

@jussikinnula 
is there a mongoose plugin or something that can help me with that?

**Comment by jussikinnula** [comment]
Actually it’s not possible to dynamically produce TypeScript interfaces. It is possible to create a generator which reads Mongoose models and spits out interfaces (into a file).

Or it’s also possible that you create a type like `export const userType = typeof new User({ ... });`, which should work on your case but I would consider it as a ”hack”.

**Comment by kerolloz** [comment]
@jussikinnula 

I found this repo and I thought it is worth mentioning
I  believe this is what I have been searching for...

https://github.com/szokodiakos/typegoose
