### ISSUE TITLE
[@types/multer-s3] Add ContentDisposition to Options

### ISSUE THREAD

**Issue by railsstudent** [DefinitelyTyped/DefinitelyTyped#38029]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/multer-s3` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention] the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tcaesvk @galtalmor @terski 

Current Options
`
interface Options {
    s3,
    bucket,
    key,
    acl,
    contentType?,
    metadata?,
    cacheControl?,
    serverSideEncryption?,
}
`

In multers3 github repo, the documention shows that contentDisposition: 'attachment' can be set in multerS3 object.

`
var upload = multer({
  storage: multerS3({
    s3: s3,
    bucket: 'some-bucket',
    acl: 'public-read',
    contentDisposition: 'attachment',
    key: function (req, file, cb) {
      cb(null, Date.now().toString())
    }
  })
})
`

**Comment by Abourass** [comment]
Same issue
