### ISSUE TITLE
[@types/styled-components] Unsupported syntax for tag function generics

### ISSUE THREAD

**Issue by dbchristopher** [DefinitelyTyped/DefinitelyTyped#38044]
I'm attempting to follow the [documented pattern](https://www.styled-components.com/docs/api#using-custom-props) for passing prop types to the styled element tag function. The example is as follows:

```typescript
interface TitleProps {
  readonly isActive: boolean
}

const Title = styled.h1<TitleProps>`
  color: ${props =>
    props.isActive ? props.theme.colors.main : props.theme.colors.secondary};
`
```

Unfortunately Typescript (v3.6) fails to parse the syntax and fails to compile with these errors:

```shell
Operator '>' cannot be applied to types 'boolean' and 'string'.ts(2365)
'TitleProps' only refers to a type, but is being used as a value here.ts(2693)
```

It seems the compiler can't understand the tag function syntax with generics `styled.h1<...>`. Are the documented types incorrect? Or is there a setting I need to enable for typescript to be able to parse that? No idea if it's a TS error, a Styled Components error, or a documentation mismatch with what's actually provided by the definitely typed library. Any clarity you can provide is greatly appreciated. 

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek, @Igmat, @Lavoaster, @Jessidhia, @JKillian, @eps1lon, @flavordaaave, @wagerfield.

**Comment by christophemilliere** [comment]
I had the same problem and I changed the version and the problem was fixed.
used version 4.1.18

**Comment by melounek** [comment]
I guess this is not an issue anymore and can be closed.
