### ISSUE TITLE
[@types/lodash]: _.get types look partially broken in TS3.6

### ISSUE THREAD

**Issue by nhardy** [DefinitelyTyped/DefinitelyTyped#38065]
- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @aj-r @e-cloud @thorn0 @jtmthf @DomiR @WilliamChelman 

It looks like TS3.6 has partially broken the type for `get` when `object` can be `null` or `undefined` and a `defaultValue` is specified. When this happens, instead of inferring the type of `TKey` correctly as the single value that is specified, it infers the value as all possible keys of `object`.

```typescript
import { get } from "lodash";

const object = Math.random() > 0.5
  ? { key: "value" otherKey: 1 }
  : undefined;
// This line will works in TS3.5, but errors in TS3.6 because `TKey` is inferred as `"key" | "otherKey"` instead of just `"key"`
const result: string = get(object, ["key"], "default");
```

If I change the line to `const result: string = get(object, ["key"] as const, "default");` and update the typings to accept `readonly [TKey]`, `readonly [TKey1, TKey2]`, etc. this also resolves the issue for TS3.6, but I don't think adding `as const` should be required.

**Comment by aj-r** [comment]
If TS3.6 is losing information about the type of the array, then I don't
think we can do much other than what you already mentioned.

Does it work if you pass the key as a plain string instead of an array?

get(object, "key", "default")

**Comment by nhardy** [comment]
This appears to be resolved as of TS3.7, so closing the issue.
