### ISSUE TITLE
Jstree typing for refresh function (Angular)

### ISSUE THREAD

**Issue by geyuqiu** [DefinitelyTyped/DefinitelyTyped#38085]
Hi, 

- [x] I tried using the `@types/jstree` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
- Authors: @adaskothebeast

need to add following property for Interface JSTree
```ts
/**
 * example usage in angular: 
 * public sourceTreeNativeElement: JSTree;
 * this.sourceTreeNativeElement = $(this.sourceTree.nativeElement) as JSTree;
 * this.sourceTreeNativeElement.jstree(true).settings.core.data = [];
 * this.sourceTreeNativeElement.jstree(true).refresh();
 */
settings?: JSTreeStaticDefaults;
```

If it looks ok, I can open a pull request :) 

Cheers
Yuqiu

**Comment by AdaskoTheBeAsT** [comment]
Hi,

you can prepare pull req or I can add that in the night.

Best regards

Adam

**Comment by AdaskoTheBeAsT** [comment]
Changes in pull req https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38161

**Comment by AdaskoTheBeAsT** [comment]
hi @amcasey could you please close that issue?

**Comment by amcasey** [comment]
@AdaskoTheBeAsT Happy to, but I believe it will do that automatically if you include `Fixes #nnnnn` in your PR description.
