### ISSUE TITLE
[@types/webpack]: interface CompilationHooks has not enough properties

### ISSUE THREAD

**Issue by nickbullock** [DefinitelyTyped/DefinitelyTyped#38093]
- [x] I tried using the `@types/webpack` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x]  Mention @tkqubo @bumbleblym @bcherny @tommytroylin @mohsen1 

Hi there!
I found that compilation.Compilation.hooks doesn't contain property 'dependencyReference'.
Then i checked webpack documentation and webpack package and found some hooks in difference with CompilationHooks interface.

###  CompilationHooks interface
With packages
```
    "webpack": "4.39.1"
    "@types/webpack": "4.39.1"
```
```interface CompilationHooks {} ```  contains 69 hooks.

### Webpack compilation hooks documentation page

https://webpack.js.org/api/compilation-hooks/ contains 72 hooks and diff with interface is

- chunkIds
- beforeOptimizeChunkIds
- optimizeCodeGeneration
- beforeModuleHash
- afterModuleHash
- beforeRuntimeRequirements
- afterRuntimeRequirements
- dependencyReference

### Webpack real compilation api

```
apply(compiler) {
    compiler.hooks.compilation.tap(PLUGIN_NAME, compilation => {
      console.log(Object.keys(compilation.hooks))
    });
}
``` 
contains 76 properties and diff with interface is 

- addEntry
- failedEntry
- succeedEntry
- dependencyReference
- beforeChunks
- afterChunks
- contentHash
- log

Is webpack documentation page out of date?
I can make a PR if you give me right direction.

**Comment by lekoaf** [comment]
Webpack has their own typescript declarations. No need to use this package.
https://github.com/webpack/webpack

**Comment by nickbullock** [comment]
@lekoaf it looks like webpack declarations doesn't have Compiler or Compilation typings.
Also Angular team uses this package.
I've found these typings only in webpack repo.
https://github.com/webpack/webpack/blob/master/declarations.d.ts
https://github.com/webpack/webpack/tree/master/declarations

**Comment by nickbullock** [comment]
Any thoughts? @rubenspgcavalcante @grgur @kuehlein @rwaskiewicz @johnnyreilly @ZSkycat @christophehurpeau @dennispg @jason0x43 @elliottsj @alan-agius4 @jcreamer898

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
