### ISSUE TITLE
xml2js missing parseStringPromise method.

### ISSUE THREAD

**Issue by rcollette** [DefinitelyTyped/DefinitelyTyped#38139]
If you know how to fix the issue, make a pull request instead.

- [X ] I tried using the `@types/xxxx` package and had problems.
- [X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @salib @jasonrm @ccurrens @edwardhinkle @BehindTheMath @claasahl @redlickigrzegorz

xml2js now has parseStringPromise method
https://www.npmjs.com/package/xml2js#promise-usage

**Comment by BehindTheMath** [comment]
This is fixed by #38064.

**Comment by rcollette** [comment]
Wow.  Thanks for the quick response.
