### ISSUE TITLE
typescript-bot not mentioning authors

### ISSUE THREAD

**Issue by devrelm** [DefinitelyTyped/DefinitelyTyped#38163]
@RyanCavanaugh 

It looks like @typescript-bot isn't mentioning authors. These are the last two author-mention comments that I've found. Both are at 3:22PM EDT Sept 4th:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38137#issuecomment-528046884

#38138, the next PR, was opened at 4:11PM EDT Sept 4th and didn't get an author-mention comment.

**Comment by devrelm** [comment]
@sandersn @basarat @johnnyreilly

**Comment by sandersn** [comment]
@RyanCavanaugh is the author of the bot and will be back from vacation on Tuesday. He's the only one with 2FA set up to update it, so...

**Comment by sandersn** [comment]
Turns out the VM's password expired. It took 3 engineers to generate a password that meets Microsoft complexity requirements, but the bot should be back at work!

**Comment by devrelm** [comment]
Thanks!
