### ISSUE TITLE
[@types/react-modal] @tippy.js/react and @types/react-modal conflict

### ISSUE THREAD

**Issue by abriginets** [DefinitelyTyped/DefinitelyTyped#38196]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @radziksh @drewnoakes @homburg @ttamminen @hallowatcher @peterblazejewicz @jpowell

 I'm sorry to bother you @atomiks. It might not be an issue with `@tippy.js/react` but your expert thought could help us understand an issue :)

**Issue description:** so I'm a user of [Preact](https://github.com/preactjs/preact) `10.0.0-rc.1` and [@tippy.js/react](https://github.com/atomiks/tippy.js-react) `2.2.3`. Today I've installed [react-modal](https://github.com/reactjs/react-modal) and since it doesn't have it's own typings, I had to install `@types/react-modal`. But right after the moment I installed it, all my filenames in VS Code became red-colored as there was a lot of errors:

> Type 'Element' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>'.ts(2322)
index.d.ts(8, 3): The expected type comes from property 'children' which is declared here on type 'TippyProps'
 
I think it's better I show you one time instead of telling about it.

![image](https://user-images.githubusercontent.com/17240507/64476304-c2338780-d195-11e9-952d-571983056a61.png)

In general, all JSX that is wrapped into <Tippy> tag is marked as an error code. But those errors will disappear as soon as I do `npm uninstall @types/react-modal --save-dev`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
