### ISSUE TITLE
Errors with promisify in jsonwebtoken

### ISSUE THREAD

**Issue by frbuceta** [DefinitelyTyped/DefinitelyTyped#38227]
## Issue Information

- [x] I tried using the `@types/jsonwebtoken` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] ~~I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).~~
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:
    - @SomaticIT
    - @danielheim
    - @brikou
    - @vpk
    - @rlgod
    - @kettil

## Description of the problem
After making the promise he gives me these mistakes. The truth is that I'm not sure if they are the types

---
> TS2322: Type 'unknown' is not assignable to type 'UserProfile'

```
import {
  sign as signToken,
  verify as verifyToken
} from 'jsonwebtoken'

const verify = promisify(verifyToken);

let userProfile: UserProfile;
userProfile = await verify(token, this.jwtSecret);
```

---
> TS2554: Expected 2 arguments, but got 3

```
import {
  sign as signToken,
  verify as verifyToken
} from 'jsonwebtoken'

const sign = promisify(signToken);

let token: string;
token = await sign(userInfoForToken, this.jwtSecret, {
  expiresIn: Number(this.jwtExpiresIn),
});
```

**Comment by rlgod** [comment]
There's a few issues here. 
1. The `verify` function callback is non standard in that it will be invoked with either the error or the result in the same argument position. `promisify` requires the function signature `function(err, result)`.

2. You would need to use the generic version of promisify which I think in the case of sign with the three parameters is `promisify<string, Secret, VerifyOptions, UserProfile>(sign)` or something like that.

**Comment by frbuceta** [comment]
> There's a few issues here.
> 
> 1. The `verify` function callback is non standard in that it will be invoked with either the error or the result in the same argument position. `promisify` requires the function signature `function(err, result)`.
> 2. You would need to use the generic version of promisify which I think in the case of sign with the three parameters is `promisify<string, Secret, VerifyOptions, UserProfile>(sign)` or something like that.

I fixed the problem by changing `import` to` require`

**Comment by dlip-immutable** [comment]
> I fixed the problem by changing import to require
Doesn't this mean that it would import promisify as an any type, thus ignoring the definitions?

**Comment by phgachoud** [comment]
```import {
  sign as signToken,
  verify as verifyToken
} from 'jsonwebtoken'

const sign = promisify(signToken);

let token: string;
token = await sign(userInfoForToken, this.jwtSecret, {
  expiresIn: Number(this.jwtExpiresIn),
});```

Note that `userInfoForToken` **has to be an object, not a Number for example**, if its the case `expiresIn` error appears

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
