### ISSUE TITLE
Missing static method `fromCartesian` of Cartographic class

### ISSUE THREAD

**Issue by rickkky** [DefinitelyTyped/DefinitelyTyped#38259]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Zuzon @hnipps @szechyjs @golyalpha @KeyboardSounds 

If you do not mention the authors the issue will be ignored.

Related dependencies version:

- "@types/cesium": "^1.59.0"
-  "cesium": "^1.61.0"
- "typescript": "^3.6.2"

There should have a `fromCartesian` static method in `Cartograhpic` class as shown in the screenshot of the official document.

I don't know whether it's because the version of @types/cesium is lower and has not been updated yet. If so, is there any plan to update the version and keep up with the latest version of cesium?

If it's not a problem of version, I'll be glad to create a PR to fix this.

Thanks for your effort!

![image](https://user-images.githubusercontent.com/25222955/64582574-90eacf80-d3c0-11e9-9439-07a3f9980d08.png)

```
class Cartographic {
    longitude: number;
    latitude: number;
    height: number;
    static ZERO: Cartographic;
    constructor(longitude?: number, latitude?: number, height?: number);
    clone(result?: Cartographic): Cartographic;
    equals(right?: Cartographic): boolean;
    equalsEpsilon(right: Cartographic, epsilon: number): boolean;
    toString(): string;
    static fromRadians(longitude: number, latitude: number, height?: number, result?: Cartographic): Cartographic;
    static fromDegrees(longitude: number, latitude: number, height?: number, result?: Cartographic): Cartographic;
    static toCartesian(cartographic: Cartographic, ellipsoid?: Ellipsoid, result?: Cartesian3): Cartesian3;
    static clone(cartographic: Cartographic, result?: Cartographic): Cartographic;
    static equals(left?: Cartographic, right?: Cartographic): boolean;
    static equalsEpsilon(left: Cartographic, right: Cartographic, epsilon: number): boolean;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
