### ISSUE TITLE
@types/facebook-instant-games generates TS2345 error

### ISSUE THREAD

**Issue by mobileben** [DefinitelyTyped/DefinitelyTyped#38268]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @oyvindjam @menushka @nialna 

I recently installed facebook-instant-games, version 6.3.

I'm using Webpack and Typescript. Transpiling this simple code

```
FBInstant.initializeAsync()
  .then(function()
  // Start loading game assets here
)
```

Generates the following error:

> TS2345: Argument of type 'void' is not assignable to parameter of type '(reason: any) => PromiseLike<never>'.

I believe the correct fix is this:

```
function initializeAsync(): Promise<any>;
```

I'm creating a PR for this.

**Comment by nialna** [comment]
Are you sure this isn't because your own code is expecting your promise to return a `reason` parameter? The `fbinstant` documentation doesn't mention any `reason` return type for `initializeAsync`. Besides, if it's not in the typing, it can't be coming from the package.

Can you post a snippet of the code where you're actually trying to use this function?

**Comment by mobileben** [comment]
@nialna Arggh, seems like the joke is on me :(. And apologies. I retried it this morning without my change and it worked. I'm trying to go through my history to see what I did. I had (thought, but clearly not) I copied the Quick Start code from FB.

Sorry ... I'm going to the corner to feel shame.
