### ISSUE TITLE
[@types/jquery] 'toElement' causes VS build failure

### ISSUE THREAD

**Issue by Serjster** [DefinitelyTyped/DefinitelyTyped#38278]
Using:
```
    "@types/jquery": {
      "version": "3.3.4",
      "resolved": "https://registry.npmjs.org/@types/jquery/-/jquery-3.3.4.tgz",
      "integrity": "sha512-KqgLNDh8oTl43/2B78S7tjwPnOxPtP9wQsLptbuQCmMwqH5QuPZOk36RsNgbs3mnq/3SCyG1l/GJmhKk5Dg68g=="
    },

tsc Version 3.0.3
VS 2019, Version 16.1.1
```

For me line 8146 is where the problem is
```
 // Generic members
    interface Event<TTarget = EventTarget, ...
```

When `'toElement'` is not commented out, I get an error that prevents the Build in VS from running, but as soon as I comment it out, the error goes away:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2344	(TS) Type '"altKey" | "bubbles" | "cancelable" | "changedTouches" | "ctrlKey" | "detail" | "eventPhase" | "metaKey" | "pageX" | "pageY" | "shiftKey" | "view" | "char" | "charCode" | "key" | ... 13 more ... | "touches"' does not satisfy the constraint '"altKey" | "bubbles" | "cancelable" | "changedTouches" | "ctrlKey" | "detail" | "eventPhase" | "metaKey" | "pageX" | "pageY" | "shiftKey" | "view" | "char" | "charCode" | "key" | ... 55 more ... | "DOM_KEY_LOCATION_STANDARD"'.
  Type '"toElement"' is not assignable to type '"altKey" | "bubbles" | "cancelable" | "changedTouches" | "ctrlKey" | "detail" | "eventPhase" | "metaKey" | "pageX" | "pageY" | "shiftKey" | "view" | "char" | "charCode" | "key" | ... 55 more ... | "DOM_KEY_LOCATION_STANDARD"'.	C:\Code\MyApp\application\src\Web (tsconfig or jsconfig project)	C:\Code\MyApp\application\src\Web\node_modules\@types\jquery\index.d.ts	8143	Active
```

Authors:
@leonard-thieu 
@borisyankov 
@choffmeister 
@Steve-Fenton 
@Diullei 
@tasoili 
@jasons-novaleaf 
@seanski 
@Guuz 
@ksummerlin 
@basarat 
@nwolverson 
@derekcicerone 
@AndrewGaspar 
@seikichi 
@benjaminjackman 
@s093294
@JoshStrobl 
@johnnyreilly 
@DickvdBrink 
@King2500

**Comment by leonard-thieu** [comment]
https://github.com/leonard-thieu/DefinitelyTyped-issue-38278

Could not repro. Could you post a repro?

My guess is that you're mixing up `JQuery.Event` and `Event` (the DOM version) somewhere. These types are not the same. Also note that you're running a very old version of `@types/jquery`. The current version is 3.3.31.

**Comment by Serjster** [comment]
Changed to version 3.3.31 and problem went away, thanks. How can I see the current version?

**Comment by leonard-thieu** [comment]
`npm info @types/jquery`
