### ISSUE TITLE
[@types/react-jsonschema-form] failed to import SchemaField 

### ISSUE THREAD

**Issue by hao-xx** [DefinitelyTyped/DefinitelyTyped#38281]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @chanceaclark @minestarks 

Hello ,
In your recent type update (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/970c733cdd07fa8f1e54a1fa4655a958fd19770b#diff-585576b203f20193115b32ff133bb6f9R268) SchemaField is named export, while in the code (https://github.com/rjsf-team/react-jsonschema-form/blob/master/src/components/fields/SchemaField.js#L443) SchemaField is default export.

Not sure how to import it correctly. I've tried 
`import { SchemaField } from 'react-jsonschema-form/lib/components/fields/SchemaField'`
which passed the compile but failed in browser.

And after change (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/970c733cdd07fa8f1e54a1fa4655a958fd19770b#diff-585576b203f20193115b32ff133bb6f9R268) this line to:
`export default class SchemaField<T> extends React.Component<SchemaFieldProps<T>> {}`, it works

**Comment by chanceaclark** [comment]
I've tried exporting the class as default like you mentioned and it works with the following:
```tsx
import React from 'react';
import SchemaField, { SchemaFieldProps } from 'react-jsonschema-form/lib/components/fields/SchemaField';

export const TestSchemaField: React.FC<SchemaFieldProps> = (props) => (<SchemaField {...props}>{/* ... */}</SchemaField>);
```

Though I am going to rework it like so:
```tsx
declare module 'react-jsonschema-form/lib/components/fields/SchemaField' {
    import { JSONSchema6 } from 'json-schema';
    import { FieldProps, UiSchema, IdSchema, FormValidation } from 'react-jsonschema-form';

    export type SchemaFieldProps<T = any> = Pick<FieldProps<T>, 'schema' | 'uiSchema' | 'idSchema' | 'formData' | 'errorSchema' | 'registry'>

    export default class SchemaField<T> extends React.Component<SchemaFieldProps<T>> {}
}
```

I will go ahead and submit another PR for the fix, though I did notice some other issues so I included them in the above code. Let me know if you see anything off.

**Comment by hao-xx** [comment]
Looks good. Thank you!
