### ISSUE TITLE
[@types/jss] TypeError: Date.now is not a function

### ISSUE THREAD

**Issue by malmil** [DefinitelyTyped/DefinitelyTyped#38293]
[@types/jss] TypeError: Date.now is not a function

- [x] I tried using the `@types/jss` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

using:
```
"@types/jss": "9.5.8",
"jss": "9.8.7",
"jss-preset-default": "4.5.0",
"typescript": "3.6.3"
```

I get the error "TypeError: Date.now is not a function" when running Jest tests with ts on
import jss from 'jss';
I've tried to remove all dates from the solution, but the error persist. 

  - Authors: 
@appsforartists 
@pelotom 
@eps1lon

**Comment by eps1lon** [comment]
Thank you for opening this issue.

> [@types/jss] TypeError: Date.now is not a function

This is not an error from TypeScript but a runtime type error. Errors when executing your runtime tests are not subject of this repository. Please open a new issue on the jss repository (https://github.com/cssinjs/jss/issues/new?template=---bug-report.md) and close this one.

**Comment by malmil** [comment]
Ok, thanks for the quick response. 
New issue: https://github.com/cssinjs/jss/issues/1191
