### ISSUE TITLE
[@types/styled-system__css] regression in theme interface

### ISSUE THREAD

**Issue by erikdstock** [DefinitelyTyped/DefinitelyTyped#38299]
In short, I can no longer access theme properties predictably.
```
Property 'breakpoints' does not exist on type 'Theme'.
  Property 'breakpoints' does not exist on type '{ alignContent?: ThemeValue<string | string[]>; alignItems?: ThemeValue<string | string[]>; alignSelf?: ThemeValue<string | string[]>; animationDelay?: ThemeValue<string | string[]>; ... 748 more ...; vectorEffect?: ThemeValue<...>; } & { ...; }'.

27             maxWidth: theme.breakpoints[1],
```
I believe a regression was introduced here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37359/files#diff-f5860094a6f9df5364afa09c389a9120R405-R409

cc @sztobar @sebald 

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by erikdstock** [comment]
No problem @sebald - Here is a codesandbox showing the issue (I think).
https://codesandbox.io/s/friendly-voice-0qjrs?fontsize=14

**Comment by erikdstock** [comment]
Hi @sebald - checking in on this, as it's hard to keep track of DT notifications. Does this issue make sense? I've been wondering if it might be wise to get all styled-system theme interfaces using one common theme interface - eg from `@types/styled-system` - But I haven't wondered too hard about it, so it's possible that it wouldn't work or be specific enough, these themes are not actually identical, etc.

**Comment by sebald** [comment]
Sorry that it took so long, was busy / sick :-/


The error you're getting is because `colors` is optional. But there is also some sort of regression regarding `ThemeValue`. Does this work with the previous version of the typings?

**Comment by erikdstock** [comment]
Hmmm, I'm actually not sure. If noone else has reported this bug maybe we should close.

For what it's worth I have also wondered if it would make sense for all of the system-ui theme projects to use/extend a single theme definition, perhaps the one from `@types/styled-system`?

**Comment by sebald** [comment]
IDK if using the same typings is a good idea, since they have a different scope. At least that is was the author of the packages said if I remember correctly.

Plus, they should be compatible, because they share the same structure, right?

**Comment by sebald** [comment]
But ofc, PRs welcome ;D
