### ISSUE TITLE
tool to automate PR process from user changes made in node_modules/@types .d.ts files

### ISSUE THREAD

**Issue by cancerberoSgx** [DefinitelyTyped/DefinitelyTyped#38346]
As user, when a typing declaration is miss something and there is a compile error, if I' really focused in the problem at hand Ii won't never think about stoping for making a PR to this project and most likely will try to avoid the compile error at all cost so the tests execute, some techniques are   //@ts-ignore ,  copy paste the type and add the missing piece,  redeclare or even remove the @type dependency and declare the module/ type as any or use require() and hard cast or worst.

Also a cheap technique in this case is navigating to the conflicting file node_module/@type/foo/index.d.ts and edit it  it directly which will be automatically solved in the editor itself without running tsc . And often in this case the change is adding a missing type, property, parameter added in a newer librar/standard version

I wonder if anybody knows of a tool that automate the process of creating a PR to this project from a change like just described, assuming  I have a local fork of this project with remotes correctly set. . 

When I finish the work executing the tool will detect changes in node_modules/@types somehow, update my fork, create a branch, apply detected change, commit and push and open the new pull request page in the browser. (of course, check for conflicts, versions, run tests, lints, etc. Also instead manually the user could run it in the npm script he finds more appropriate (after tests, before commit, etc)

I ask this here since I'm working on such tool and just now occurred to me that perhaps there is already something more formal or perhaps somebody has a script that does something similar.  and second I would like to know your  opinions / objections / feedback about such project ? and if you see any cons or warnings I should document before publishing.

I will round a couple of tests, create a project and share with you here with more details , thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
