### ISSUE TITLE
Type definitions for mssql are out of date

### ISSUE THREAD

**Issue by blitzmann** [DefinitelyTyped/DefinitelyTyped#38367]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jaminfarr, @buzinas, @mrrichar, @elhaard, @pkeuter, @mcdado, @woodenconsulting, @cahilfoley

Greetings!

It looks like the typings for mssql are behind the latest version.

According to the documentation found here: https://www.npmjs.com/package/mssql#tedious there is a `beforeConnect` option. However, the types are preventing me  from adding this property to the config object. 
```
{
            user: 'user',
            password: 'pass',
            beforeConnect: function(conn) { console.log("Connect!") }
        }
```

**Comment by cahilfoley** [comment]
Hey @blitzmann, thanks for that, I've updated the config type definition, the typescript bot just published a new version of @types/mssql (v4.3.1).
