### ISSUE TITLE
[@types/react] Add ability to extract the ref type from React.forwardRef

### ISSUE THREAD

**Issue by BPScott** [DefinitelyTyped/DefinitelyTyped#38374]
FAO @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon (found via [CODEOWNERS](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f574f4aa1344774ef08caf8c9e2f994c4e7fa30e/.github/CODEOWNERS#L4347))

It is possible to use `React.ComponentProps<typeof SomeComponent>` (/ComponentPropsWithRef/ComponentPropsWithoutRef) to extract the Props type of a given component. This allows you to reference the props of a component even if that type is not available (either because it was defined inline or inferred or the interface was never publicly exported). It would be useful to be able to do something similar for the type of the ref provided to React.forwardRef.

Consider the following code. It is a `Button` component that uses forwardRef to expose an API that is usable via ref. Well it's not strictly a component because React.forwardRef returns something that only looks like a component but whatever:

```tsx
interface EmptyProps {}

interface Focusable {
  focus: () => void;
}

const Button = React.forwardRef<Focusable, EmptyProps>(function Button(
  _props,
  ref,
) {
  const buttonRef = useRef<HTMLButtonElement>();

  useImperativeHandle(ref, () => ({
    focus() {
      buttonRef.current && buttonRef.current.focus();
    },
  }));

  return <button ref={buttonRef}>Hello</button>;
});
```

This then lets you consume it like so. Here is an App component that will trigger focusing the button. This works great however the `Focusable` interface doesn't really need be public - calling sites should be able to infer it based upon the `Button` component.

```tsx
function App() {
  // This works great, but what if Focusable is not publicaly available
  // We need a way of extracting this type out of Button
  const buttonRef = useRef<Focusable>(null);

  useEffect(() => {
    buttonRef.current.focus();
  });

  return (
    <React.Fragment>
      <Button ref={buttonRef} />
    </React.Fragment>
  );
}
```

---

Would it be possible to add a `ForwardRefRef` type (name up for grabs) to extract the type out of the result of calling React.forwardRef - in this example the `Button` component:

```tsx
type ForwardRefRef<P> = P extends React.ForwardRefExoticComponent<infer T>
  ? (T extends React.RefAttributes<infer S> ? S : never)
  : never;

export function App() {
  // `typeof buttonRef` resolves to `Focusable`.
  // This allows us to infer the type instead of having to expose and reference `Focusable`
  const buttonRef = useRef<ForwardRefRef<typeof Button>>(null);

  useEffect(() => {
    buttonRef.current.focus();
  });

  return (
    <React.Fragment>
      <Button ref={buttonRef} />
    </React.Fragment>
  );
}
```

**Comment by Jessidhia** [comment]
I remember trying to write a `RefType` helper type a while ago for that very purpose (not specific to ForwardRef, but to any component), but just writing the expression itself made the editor very sluggish... 🤔

**Comment by ferdaber** [comment]
This seems to work without any huge slowdown:
```ts
type ComponentRef<C> = Exclude<
  C extends JSXElementConstructor<{ ref?: infer R }>
    ? R
    : C extends keyof JSX.IntrinsicElements
    ? JSX.IntrinsicElements[C]['ref']
    : unknown,
  string | undefined
> extends Ref<infer T>
  ? T
  : unknown
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
