### ISSUE TITLE
TopoJSON language definition

### ISSUE THREAD

**Issue by Ledragon** [DefinitelyTyped/DefinitelyTyped#3838]
Hi,
For what I see there is no definition for the TopoJSON library (https://github.com/mbostock/topojson). Is it something that might be of interest? I already built a small thing, I could elaborate and publish it over here.

**Comment by stasberkov** [comment]
@Ledragon please follow http://definitelytyped.org/guides/contributing.html instruction: create branch of DefinitelyTyped repo, push your changes, submit pull request.

**Comment by Ledragon** [comment]
Thanks for the follow-up. I did not want to get the work started before letting anyone know... I will try and get back to this

**Comment by dsummersl** [comment]
Would love to have this.

**Comment by snolflake** [comment]
@Ledragon Can you share with us what you have? I was surviving with this [very superficial definition](https://gist.github.com/snolflake/1e255eba1fe074f80712477f3ed518f9) but now I'm interested in start using topojson 2.x. Did you had the chance to check out the new API?

Thanks for your work on d3 typings btw :pray:

**Comment by Ledragon** [comment]
Hi,
Thanks to @dsummersl and@snolflake for your interest, glad to see it could be useful.
What I did up to now is very limitated, and based on the v1 version of topojson (original post if from 2015, and I did not work much with topojson since then). It can be found [here](https://github.com/Ledragon/TopoJsonTypings).

Based on @snolflake work and mine, efforts could be joined to merge those two and update these for the new version of the API. Should we work on a separate repo just for the typings, then fork this one to integrate the work, or directly on the fork?

Let me know how you feel about engaging the work, then we shall proceed.

**Comment by snolflake** [comment]
@Ledragon I've started using v2 this weekend and basically there isn't many changes in the API, just split in modules like d3v4

I'm writing/validating the definitions for `topojson-client` as needed for my own project and after this project is finished I can share the result. After that we can improve whatever we got and have some help from @tomwanzek to publish definitions for both 1.x and 2.x

I think that it would be helpful for others even with got only the method signatures, convenient at least.

**Comment by Ledragon** [comment]
Sounds great for me, so I whenever ready let me know and we will get started!

**Comment by Ledragon** [comment]
Woot amazing! thanks @ricardo-mello
