### ISSUE TITLE
[@types/stripe]  checkout.sessions.create does not support 

### ISSUE THREAD

**Issue by larse514** [DefinitelyTyped/DefinitelyTyped#38392]
Tagging authors per issue creation template: @wjohnsto @CodeAnimal @sampsonjoliver @LinusU @brannon @kkamperschroer @starhoshi @bruun @galtalmor @htunnicliff @squirly @tzarger

I need to include a linked Stripe account via the checkout session process as part of a marketplace application, however it does not appear to be supported currently.  

Looking at the stripe [docs](https://stripe.com/docs/payments/checkout/connect) this is currently supported via the node library

![image](https://user-images.githubusercontent.com/14366365/64924711-fa961f80-d7ac-11e9-9a51-c9988c2fe6d6.png)

However there doesn't seem to be a current typings for this:

<img width="450" alt="Screen Shot 2019-09-15 at 11 33 12 AM" src="https://user-images.githubusercontent.com/14366365/64924665-a2f7b400-d7ac-11e9-99c6-9af1f821ac53.png">

Looking at the type definitions this is supported via the IHeaderOptions 

![image](https://user-images.githubusercontent.com/14366365/64924687-ca4e8100-d7ac-11e9-9439-3e4f36db6ce0.png)

However, it looks like only the retrieve method supports the IHeaderOptions

![image](https://user-images.githubusercontent.com/14366365/64924699-e3efc880-d7ac-11e9-9533-b6039fc71d71.png)

Is there a way to do this with existing types or does additional support need to be included?

**Comment by larse514** [comment]
For anyone that has a similar issue, thus far my workaround has been to call the Stripe API's directly via something like Axios.  There is some pain around using query strings to make the API calls.  Ping me directly if you have questions on how to get that to work.  Really hope to see some movement on this though as it will make my solution far easier to maintain

**Comment by pushplay** [comment]
This is an easy one.

In the future of a types package isn't supporting something you know should work you can cast to `any` and call it.  eg...

```typescript
const session: Stripe.checkouts.sessions.ICheckoutSession = await (stripe.checkout.sessions as any).create({
    payment_method_types: ['card'],
    line_items: [{
      name: "Cucumber from Roger's Farm",
      amount: 200,
      currency: 'usd',
      quantity: 10,
    }],
    payment_intent_data: {
      application_fee_amount: 200,
    },
    success_url: 'https://example.com/success',
    cancel_url: 'https://example.com/cancel',
  }, {
    stripe_account: '{{CONNECTED_STRIPE_ACCOUNT_ID}}',
  });
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
