### ISSUE TITLE
[@types/react] Cannot restrict type of children for function component

### ISSUE THREAD

**Issue by levrik** [DefinitelyTyped/DefinitelyTyped#38402]
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon

The following code

```ts
const DocumentPreviewLoader: React.FC<{
  projectName: string;
  documentId: string;
  children: (url: string) => React.ReactNode;
}> = ({ projectName, documentId, children }) => {
  const { data } = usePreviewsQuery({
    variables: {
      projectName,
      id: documentId
    }
  });

  if (!data) {
    return null;
  }

  return children(data.project.document.previews[0]);
};
```

results in the following error

```
Type '({ projectName, documentId, children }: PropsWithChildren<{ projectName: string; documentId: string; children: (url: string) => ReactNode; }>) => {} | null | undefined' is not assignable to type 'FunctionComponent<{ projectName: string; documentId: string; children: (url: string) => ReactNode; }>'.
  Type '{} | null | undefined' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)> | null'.
    Type 'undefined' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)> | null'.
```

If I remove the definition of `children`, the error disappears (but then calling `children` as a function doesn't work anymore of course).

If I understand it correctly TypeScript merges the declaration of `children` with my declaration of `children` which doesn't work here. Also in general the current definition causes issues if you're trying to type children if I understand this correct.

**Comment by levrik** [comment]
I just see that the problem comes from my `children` function returning `ReactNode` instead of `ReactElement` as expected by the `FC` type. Since seems to link to #35622 since I also can't just return `children` from a `FC` if I don't alter its definition.

**Comment by izatop** [comment]
Hello!

Since `props` member of `Component` definition  was changed to this

```
readonly props: Readonly<P> & Readonly<{ children?: ReactNode }>;
```

it rewrites your own `children` definition of the component props.

Someone tell me why is it happened?

**Comment by FredyC** [comment]
Have a look at the approach I have chosen for my project, perhaps it will help you.

https://gist.github.com/FredyC/3aba908bb0894b83dc25cf1a02d1928d

**Comment by codeclown** [comment]
Possibly related: it's not possible to type-check children when using a plain typed function (not `FC` etc.):

```ts
// Component which expects only a string as children
const SomeComponent = ({ children }: { children: string }) => {
  return createElement('span', null, children);
};

// Does not throw:
createElement(SomeComponent, null, 123); // <- 123 is not a string
```

In `createElement` the type of `children` is always `ReactNode[]`:

```ts
    function createElement<P extends {}>(
        type: FunctionComponent<P>,
        props?: Attributes & P | null,
        ...children: ReactNode[]): FunctionComponentElement<P>;
```

It should infer `children` type from `props.children`, if a type is defined there?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
