### ISSUE TITLE
[@types/react] React.createRef returns a weird definition.

### ISSUE THREAD

**Issue by NoMercy235** [DefinitelyTyped/DefinitelyTyped#38440]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon

Hello! I am facing an issue when trying to type the `ref` property of a custom component.

This is the setup I have:
```javascript
// someFile.TS
// Due to some weird Webpack rules and the app's architecture I have this interface in a file which
// cannot import the TableComponent from its TableComponent.tsx file.
// Therefore, I am trying to emulate the end result of the React.createElement function call
interface ITableComponent {
  tableProps: IlDataTableProps; // This is the only property I need to access
}

interface ITableComponentProps {
  ref: React.RefObject<ITableComponent>
}

// someOtherFile.TSX
class TableComponent extends React.Component<ITableComponentProps> implements ITableComponent {}

// somewhereInTheApp.TSX
class SomeComponent extends ... {
  tableRef = React.createRef<ITableComponent>();
  render () {
    return <TableComponent ref={this.tableRef}/>; // *Read below
  }
}
```
*Over here I get the following error:
![image](https://user-images.githubusercontent.com/24717857/65044496-ab471f00-d965-11e9-916f-69dc1dde010c.png)

Looking through the type definition of ref I came across this line:
```javascript
    type Ref<T> = { bivarianceHack(instance: T | null): void }["bivarianceHack"] | RefObject<T> | null;
```
and this one:
```
    function createRef<T>(): RefObject<T>;
```
Seeing as `createRef` returns a T, in my case that should be `ITableComponent`. And the ref type also has an option of `RefObject<T>`. However, as the error shows, it looks for something which is `(string & RefObject<T>)`. I don't understand where that `string &` is coming for and I also cannot find an explanation why is it needed. To my understanding, the `string` refs were the first implementation and were deprecated. So why does that type need to interfere with the `React.RefObject<T>`. Or, if it must interfere, why is it that the `React.createRef` function is not returning that `string & RefObject<T>` definition? If I change the definition to that in the `@types/react/index.d.ts` file everything works as it should.

**Comment by eps1lon** [comment]
I don't see any class implementing `ITableComponent`.

Could you try

```diff
-class TableComponent extends React.Component<ITableComponentProps> {}
+class TableComponent extends React.Component<ITableComponentProps> implements ITableComponent {}
```

and see if this passes?

**Comment by NoMercy235** [comment]
Sorry, I forgot to write it. It was there in the first place, but it didn't help, unfortunately. :(

Also, note that the `ITableComponent` from the screenshot is equivalent to `ITableComponentProps` in the above example.

**Comment by eps1lon** [comment]
Could you move all the files in a single file and prepare a reproduction on the [typescript playground](http://www.typescriptlang.org/play/). Otherwise it's hard to track where the issue comes from.

**Comment by NoMercy235** [comment]
Moving everything in a single file would solve the issue because I can just use `React.createRef<TableComponent>` and everything will be nice and pretty.

I understand that, but the problem is that it's not possible in my situation (which also means that it's hard to reproduce it in a playground or other environments). I just wanted to know why is it that the ref property has this definition:
```javascript
 //                              ↓In particular, why is this `string &` there
(property) ref?: (string & React.RefObject<ITableComponent>) | /* a couple of other options */
```
I assume that that's the end result of this type:
```javascript
type Ref<T> = { bivarianceHack(instance: T | null): void }["bivarianceHack"] | RefObject<T> | null;
```
But I don't know where the string union is coming from.

**Comment by Jessidhia** [comment]
That is likely from the `ClassAttributes` definition getting mixed in somehow, as it uses `LegacyRef<T>` as opposed to just `Ref<T>`. I'm not sure what may be causing it, though.

You may note that `LegacyRef<T>` is written using `|`, but there are some conditions I don't understand the cause of yet where pre-existing props can get intersected with `ClassAttributes`, and the intersection (`&`) distributes over the `|`.

**Comment by eps1lon** [comment]
> Moving everything in a single file would solve the issue because I can just use React.createRef<TableComponent> and everything will be nice and pretty.

You can keep the types. This is just so that you can share it on the playground.

**Comment by NoMercy235** [comment]
@Jessidhia As you said, this is probably the issue. I tried investigating a little bit, but I can't see how the `|` would be able to transform into `&`.

**Comment by eps1lon** [comment]
> @eps1lon Here is the typescript error reproduced in codesandbox: [codesandbox.io/s/misty-cookies-j4yl1](https://codesandbox.io/s/misty-cookies-j4yl1)

Thanks. This is a known limitation of TypeScript + react's ref. Basically it wants the passed ref to implement the same interface that  will be implemented (injected by `<TableComponet ref={tableRef} />`). You cannot use a "smaller" interface i.e. `tableRef = React.createRef<TableComponent>();` will pass.

For a better technical understanding I would refer you to @Jessidhia and https://github.com/microsoft/TypeScript/issues/30748#issuecomment-480197036. She has a better grasp on the technical details.

**Comment by NoMercy235** [comment]
I managed to find an ugly hack. It looks like I can trick the compiler if the interface mirrors the component completely:
```javascript
export interface ITableComponent {
  tableProps: IlDataTableProps;
  /* the definition of 16 other methods that were inside the class component */
  render: () => JSX.Element;
  context: unknown;
  setState: (...args: unknown[]) => unknown;
  props: ITableProps;
  state: unknown;
  refs: { [key: string]: React.ReactInstance };
  forceUpdate: (...args: unknown[]) => unknown;
}
```
If the interface looks like this, Typescript no longer complains that the ref property does not match. But I'm open to any other suggestions, if @Jessidhia find something. It might also be worth mentioning that declaring a variable with `any` when creating the reference:
```
tableRef = React.createRef<any>();
```
works as well. But, again, due to project circumstances, any is not an option.

**Comment by eps1lon** [comment]
> I managed to find an ugly hack. It looks like I can trick the compiler if the interface mirrors the component completely:

This is what I meant with `tableRef = React.createRef<TableComponent>();`. If you just repeat the interface any extension to `TableComponent` will issue the type error again though since your interface will be "smaller" again.

Would you be so kind and close this issue since this is essentially a duplicate of https://github.com/microsoft/TypeScript/issues/30748 and has to be solved in TypeScript itself not the type definitions.

**Comment by NoMercy235** [comment]
@eps1lon I am not sure I understand what you mean by this:

> This is what I meant with tableRef = React.createRef<TableComponent>();. If you just repeat the interface any extension to TableComponent will issue the type error again though since your interface will be "smaller" again.

I have updated my codesandbox example with the interface I am now using to bypass the error:
https://codesandbox.io/s/misty-cookies-j4yl1

I will close this ticket and hope for a fix on the Typescript repo. Thanks! 👍
