### ISSUE TITLE
False deprecated annotation of jQuery method

### ISSUE THREAD

**Issue by pubmikeb** [DefinitelyTyped/DefinitelyTyped#38470]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/jquery` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

I get _Deprecated symbol used consult docs for better alternative_ warning when using jQuery methods, which are not deprecated. I checked the jQuery API reference, as of mid-September 2019, none of these methods is marked as deprecated:
* [`.keydown()`](https://api.jquery.com/keydown/)
* [`.keypress()`](https://api.jquery.com/keypress/)
* [`.keyup()`](https://api.jquery.com/keyup/)

But anyway, for some reason at **[JQuery.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jquery/JQuery.d.ts#L6055)** I can find:
`@deprecated ​ Deprecated since 3.3. Use \`{@link on }\` or \`{@link trigger }\`.`

It looks like an error.
The official jQuery API reference has nothing about deprecation of these (and **_perhaps many other_**) modules.

The problem affects many IDEs (e.g. IDEA, VS Code, etc.), relying on **_JQuery.d.ts_**, for instance:
* https://youtrack.jetbrains.com/issue/WEB-36488
* https://youtrack.jetbrains.com/issue/WEB-41482
* https://www.reddit.com/r/jquery/comments/b3zgqc/help_keypress_is_deprecated_what_is_the/

**Comment by leonard-thieu** [comment]
Event aliases are indeed deprecated (https://blog.jquery.com/2018/01/19/jquery-3-3-0-a-fragrant-bouquet-of-deprecations-and-is-that-a-new-feature/). The jQuery documentation itself is outdated.

**Comment by pubmikeb** [comment]
@leonard-thieu, in my case it is a jQuery 2.2.3 version bundled with OpenUI5, therefore I assume that this methods should not be deprecated yet. Besides, I can't find any mention of [`.keydown()`](https://api.jquery.com/keydown/), [`.keypress()`](https://api.jquery.com/keypress/), and [`.keyup()`](https://api.jquery.com/keyup/) in the blog you posted.

**Comment by leonard-thieu** [comment]
The closest matching type declarations for 2.2.3 are `@types/jquery@2.0.54`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
