### ISSUE TITLE
Own property with withRouter became required

### ISSUE THREAD

**Issue by yulObraz** [DefinitelyTyped/DefinitelyTyped#38533]
I tried to upgrade react router (to version 4.3.1) with the `@types/react-router` package to version 4.4.5 and had problems.
Authors: @eps1lon

I had code:
```
type IOwnProps = {
    isOwnProperty?: boolean
}
type IRouteProps = {
    /*view?: 'week' | 'day' | 'month' | 'agenda',
    date?: string,
    isOnlyActiveEvents?: 'onlyActive',
    agendaLength?: number,*/
	....
}
type Props =
    IOwnProps
	...
    & RouteComponentProps<{ [key in keyof IRouteProps]?: string }>;

class MyComponent extends BaseComponent<Props, State> {
}

export default withRouter(connect<IStateProps, IDispatchProps, IOwnProps & RouteComponentProps<{ [key in keyof IRouteProps]?: string }>>(
    (state: ApplicationState) => {...},
    {...   }
)(MyComponent));
```

I have error TS2559 because isOwnProperty have became required.

This declaration with Omit makes optional own property required:
```
export function withRouter<P extends RouteComponentProps<any>>(component: React.ComponentType<P>): React.ComponentClass<Omit<P, keyof RouteComponentProps<any>>>;
```

**Comment by eps1lon** [comment]
Please include a complete example that reproduces on http://www.typescriptlang.org/play/index.html (it can now fetch `@types/` packages).

**Comment by yulObraz** [comment]
Have you example with react-router?

**Comment by eps1lon** [comment]
> Have you example with react-router?

I was referring to your code including the relevant imports and code in a typescript playground.

**Comment by yulObraz** [comment]
It would be quicker to change existing example.

**Comment by yulObraz** [comment]
http://www.typescriptlang.org/play/index.html?jsx=2#code/JYWwDg9gTgLgBAbznAShArjApgYQuCAOy0JgAUoIwBnAGmQHdgYALNTLKe97euAZSYwAxiwC+cAGaUQcAERQsAQ2EwAtJQ5Q1AE3xyA3AFgAUKEiw4AKjhLqqZaqkz5ilTEOnz0eEmFFiJwlpfFdHdUUddAAPTxMvUk5JFSw4AEkAeQZCCip7BFNkYGosnMowAH4ALjgAIwgIABtlQmMTMQTsKGThVLT+GCVsXJpEDrNE7pT0gBFisCHREfzxmABPMD6eLGW4AF5EQrhqfCwa6hgoYEIAczaxNuFGu3sAWTW8AmJSOCxo7EIOnsKHCADpPpBvjAADxHfqDYblewAMlm80WLF2qMy2SxqAw2AhRBI5CR0LS22WAD5TFTDiZkGB0LVGsBhHBFIDOAAKACU9OQyEUMHQUEIcG5R0FcGhOmAADcaQzpYKEKxiqCwEjQcVSiM4AAfA3yUpwfXULAecYq1Xq6ia7UgDGapRQJQge0nEBYa0q6EAejliqlcF5bWQ43Gpma8He2x0RKh+zgQjYBJ5R38hECMJD8KGOyRtDzc2oCxEmKLeb1SLgqO2iZJy3JlKRSuQVMlyuQ3IuBZqSkIa35ezp3IQEjs6QGBeWvOL3YlI7HE95R153PejdIa5MYdMpieL3xHGorwgUWav3+JCBDncoLIotw+EhJOhg7W9E-dIKys5Og8vyf7SsKoril2Nqygq7Y2jKgjMKIsFwTK2xwOWLB7HI-oYQAjP6VRelgcgcrenB7AgWp5PsdLQnG6YJq+xI-AgoJsVRNASLquLlBRlzoD6cD+lSEjCSGUFoRhWE4UMLAAEwEURJEAeRlG1qOMr0RwjFfCSiBsQ6eRcSUPFUBRySNBaokiUJyFwSBKGCv6-pwAAKiwxRwHoWD2IQEDwAw0AANbiXBznQpJsnSRhADMimnMpZFQBR3IcdQy6aWs8bbr4BlpdZ1mhdKvpQf6CEVnZyABkGdn7sqkamH8FjwIByToI08BZjmkHHAiqQaROC49hlE6mBu2xnhe7VYHVQA

**Comment by eps1lon** [comment]
> [Sample](http://www.typescriptlang.org/play/index.html?jsx=2#code/JYWwDg9gTgLgBAbznAShArjApgYQuCAOy0JgAUoIwBnAGmQHdgYALNTLKe97euAZSYwAxiwC+cAGaUQcAERQsAQ2EwAtJQ5Q1AE3xyA3AFgAUKEiw4AKjhLqqZaqkz5ilTEOnz0eEmFFiJwlpfFdHdUUddAAPTxMvUk5JFSw4AEkAeQZCCip7BFNkYGosnMowAH4ALjgAIwgIABtlQmMTMQTsKGThVLT+GCVsXJpEDrNE7pT0gBFisCHREfzxmABPMD6eLGW4AF5EQrhqfCwa6hgoYEIAczaxNuFGu3sAWTW8AmJSOCxo7EIOnsKHCADpPpBvjAADxHfqDYblewAMlm80WLF2qMy2SxqAw2AhRBI5CR0LS22WAD5TFTDiZkGB0LVGsBhHBFIDOAAKACU9OQyEUMHQUEIcG5R0FcGhOmAADcaQzpYKEKxiqCwEjQcVSiM4AAfA3yUpwfXULAecYq1Xq6ia7UgDGapRQJQge0nEBYa0q6EAejliqlcF5bWQ43Gpma8He2x0RKh+zgQjYBJ5R38hECMJD8KGOyRtDzc2oCxEmKLeb1SLgqO2iZJy3JlKRSuQVMlyuQ3IuBZqSkIa35ezp3IQEjs6QGBeWvOL3YlI7HE95R153PejdIa5MYdMpieL3xHGorwgUWav3+JCBDncoLIotw+EhJOhg7W9E-dIKys5Og8vyf7SsKoril2Nqygq7Y2jKgjMKIsFwTK2xwOWLB7HI-oYQAjP6VRelgcgcrenB7AgWp5PsdLQnG6YJq+xI-AgoJsVRNASLquLlBRlzoD6cD+lSEjCSGUFoRhWE4UMLAAEwEURJEAeRlG1qOMr0RwjFfCSiBsQ6eRcSUPFUBRySNBaokiUJyFwSBKGCv6-pwAAKiwxRwHoWD2IQEDwAw0AANbiXBznQpJsnSRhADMimnMpZFQBR3IcdQy6aWs8bbr4BlpdZ1mhdKvpQf6CEVnZyABkGdn7sqkamH8FjwIByToI08BZjmkHHAiqQaROC49hlE6mBu2xnhe7VYHVQA)

That code does not have any error in the playground. If that error is only displayed by your IDE and not while building make sure your IDE picks up the correct typescript version and config.

**Comment by yulObraz** [comment]
I have commented errored path3. It has error on the site

**Comment by eps1lon** [comment]
I know too little of `react-router` but I don't think you're supposed to pass render props into `withRouter` decorated ones anyway. Either use `<Router component={WithRouterComponent} />` or `<Router render={props => <Component {...props}} />` or `<Router render={() => <WithRouterComponent />}}`

**Comment by yulObraz** [comment]
Why? You can add withRouter to any component which needs history (history.push, for example). And it could have its own properties. May be I am not right that I added ...props with withProps. But it does not matter with broken own properties.

**Comment by eps1lon** [comment]
Yeah I won't have the time to fix this specific use case. You can just as well use `<Router component={WithRouterComponent} />` or `<Router render={props => <Component {...props}} />`.

**Comment by yulObraz** [comment]
In my IDE the error look like 

`Error	TS2559	(TS) Type '{ history: History<any>; location: Location<any>; match: match<any>; staticContext?: StaticContex...' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<Pick<IOwnProps & RouteComponentProps<{ v...'.	`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
