### ISSUE TITLE
d3 scales should allow string ranges (take two)

### ISSUE THREAD

**Issue by kaiyoma** [DefinitelyTyped/DefinitelyTyped#38574]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek @gustavderdrache @borisyankov @denisname 

I am running into the same issue that was reported a few years ago: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/8941

If I try to do this:

```
  return d3
    .scaleLinear()
    .domain(domain)
    .range(colors)
    .clamp(true);
```

where `colors` is an array of strings, I get this type-checking error:

```
Argument of type 'string[]' is not assignable to parameter of type 'readonly number[]'.
  Type 'string' is not assignable to type 'number'.
```

Specifically, the error is pointing to my use of `range(colors)`. According to the D3 API, `range` can take any value:

> _Unlike the domain, elements in the given array need not be numbers_

Source: https://github.com/d3/d3-scale/blob/v2.2.2/README.md#continuous_range

**Comment by kaiyoma** [comment]
Similarly, if I try to "cast" the type correctly:

```
d3.scaleLinear() as d3.ScaleLinear<string, string>
```

I get this error:

```
Conversion of type 'ScaleLinear<number, number>' to type 'ScaleLinear<string, string>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'number' is not comparable to type 'string'.
```

**Comment by gustavderdrache** [comment]
You need to specify your domain explicitly due to the [multiple overload signatures](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-scale/index.d.ts#L226-L256) — see the [tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-scale/d3-scale-tests.ts#L79-L85) for an example. It should be enough to just add the type parameter like so:

```typescript
  return d3
    .scaleLinear<string>() // explicit type parameter
    .domain(domain)
    .range(colors)
    .clamp(true);
```

**Comment by kaiyoma** [comment]
Oh nice, that worked great! Thanks a ton for your quick reply and explanation. Hopefully this information will be useful to future developers who stumble upon this issue.
