### ISSUE TITLE
[@types/bull] Missing "notFetch " in Job.moveToCompleted

### ISSUE THREAD

**Issue by CindyQ11** [DefinitelyTyped/DefinitelyTyped#38619]
- [ ] I tried using the `@types/bull` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bgrieder , @JProgrammer , @marshall007, @danmana， @aleccool213 

If you do not mention the authors the issue will be ignored.

**Comment by douglascayers** [comment]
Hi @CindyQ11, I've submitted PR to address this issue. Thanks
