### ISSUE TITLE
react-router-dom 5.1 installs incorrect dependencies.

### ISSUE THREAD

**Issue by jdetle** [DefinitelyTyped/DefinitelyTyped#38637]
@huy-nguyen @p-jackson @eps1lon @danielnixon
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

I lack the depth to understand the cause of this, but @types/react-router-dom latest installs the types for react-router-dom 5.1.0 but react-router 5.0.1, so the hooks are not properly imported from react-router, and typescript says they dont exist. I dont know how to fix this, and I can import just fine from react-router, but it seems like the types for react-router-dom 5.1 are inaccurate.

**Comment by jdetle** [comment]
@huy-nguyen @p-jackson @eps1lon @danielnixon

**Comment by eps1lon** [comment]
Not sure how to fix this for npm but in yarn you can remove the entry for `@types/react-router` from your lockfile and run `yarn install` again. It should pick up the latest version.

**Comment by jdetle** [comment]
Will try this out tomorrow morning and report back

**Comment by SpiritBreaker226** [comment]
> Not sure how to fix this for npm but in yarn you can remove the entry for `@types/react-router` from your lockfile and run `yarn install` again. It should pick up the latest version.

In case anyone was wondering this works.

**Comment by AveDemid** [comment]
Faced the same problem. Not sure if this is the best way, but I did so

- deleted folder node_modules
- deleted package-lock.json
- npm install

**Comment by jdetle** [comment]
Yeah it does.

**Comment by SanthoshRaju91** [comment]
This worked, thanks for saving me today

**Comment by j-u-p-iter** [comment]
Hey, @eps1lon! Thank you for your advice.

I have small question - don't you know, why correct dependency (correct version of @types/react-router) is not installed from the very beginning?
