### ISSUE TITLE
@types/mongodb upgrade minimum TypeScript version to v3 in order to fix TypeScript 2 hacks in the codebase

### ISSUE THREAD

**Issue by HosseinAgha** [DefinitelyTyped/DefinitelyTyped#38686]
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT @mrcrane

We are introducing many hacks and workarounds to support complex TypeScript types. These hacks will be no longer needed if we upgrade minimum required TS version to TypeScript v3. For example we've defined `Omit` using TS 2.7 supported types or we had to use dirty hacks that could easily be avoided using TS 3.0 `unknown` type. Please take a look at @mrcrane's [comment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38522#discussion_r328859007).  

As upgrading the minimum TS version for a popular package like `mongodb` is not easy (requires upgrading the min TS version of dependents and dependents of dependents so on! and then approval of maintainers of those packages) I'm creating this issue as a tracking point for this task.

**Comment by CaselIT** [comment]
Thanks for creating this issue. I agree that we should update the minimum version of typescript.

Can you also tag the authors of the dependent packages so we have also their feedback?

**Comment by HosseinAgha** [comment]
I think finding the authors takes the same amount of time as creating the upgrade PR. Plus the repo bot mentions them in the PR when we change their min TS version. I'd be happy to contribute but I'm currently very busy. 🙏

**Comment by CaselIT** [comment]
@HosseinAgha What is the minimum version that is required to fix the latest work around? 3.0?

**Comment by mrcrane** [comment]
Version 3.0 would be required to use `unknown` for the fix that is outlined in #38687

**Comment by mrcrane** [comment]
This was merged in #38789

**Comment by jahir9991** [comment]
i solved this problem with "typescript": "3.3.3" but @latest occurred another issues

**Comment by HosseinAgha** [comment]
@jahir9991 This is the repository for `@types/mongodb` package that you install to get TypeScript typings and this is an internal issue with the types. What problem are you talking about?
