### ISSUE TITLE
@types/node is missing properties Writable.writableObjectMode and Readable.readableObjectMode

### ISSUE THREAD

**Issue by mpiroc** [DefinitelyTyped/DefinitelyTyped#38704]
The properties in question were added in NodeJS 12.3.0:

* [`stream.Writable.writableObjectMode`](https://nodejs.org/api/stream.html#stream_writable_writableobjectmode)
* [`stream.Readable.readableObjectMode`](https://nodejs.org/api/stream.html#stream_readable_readableobjectmode)

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @uniqueiniquity @andrewbranch @armanio123 @rbuckton @Flarna

I'm not sure who the specific authors are (`index.d.ts` lists around 40), so I tagged the most recent 5 committers for `stream.d.ts`

**Comment by uniqueiniquity** [comment]
Hi @mpiroc, 

Usually I just help review and merge PRs from other contributors, but this seemed straightforward enough, so I went ahead and did it.
