### ISSUE TITLE
[stripe-v3] IPaymentMethod does not have 'card' parameter

### ISSUE THREAD

**Issue by BasedMusa** [DefinitelyTyped/DefinitelyTyped#38721]
I'm implementing a payment system in Firebase Cloud Functions (Typescript) for my Flutter app using Stripe. I need to check if the user has added the same card again or not. I've read online that the `card` parameter has the same `fingerprint` if the same card is added twice. But to compare the values, I can't find a `card`. When can we get this, or is there any other way to achieve the same results?

**Comment by 43081j** [comment]
it uses discriminated unions afaik.

check the type and it should infer the interface correctly:

```ts
if (paymentMethod.type === 'card') {
  // access paymentMethod.card here
}
```

**Comment by BasedMusa** [comment]
Thanks it works!
