### ISSUE TITLE
Latest version of @types/mongodb breaks tsc build

### ISSUE THREAD

**Issue by richwifunds** [DefinitelyTyped/DefinitelyTyped#38865]
With the latest version of typescript (3.6.3), on Macos Mojave:

../@types/mongodb/index.d.ts:863:7 - error TS2304: Cannot find name 'unknown'.

863       unknown extends U ? ObjectId : U

- [x] I tried using the `@types/xxxx` package and had problems.
  - Authors: @kamal

**Comment by MichaelPlouvier** [comment]
Same issue here. This really is a blocking issue. Please fix ASAP

**Comment by AviVahl** [comment]
I've just tested `typescript@3.6.3` with `@types/mongodb@3.3.6` and there are no type errors on my end.

Steps I took:
```
mkdir mongotest
cd mongotest
yarn init -yp
yarn add typescript @types/mongodb --dev
yarn tsc --init
echo "import {connect} from 'mongodb'; connect('');" > mongo.ts
yarn tsc
```

The error you got maybe points to some older `typescript` version in your stack (one that didn't have the `unknown` keyword yet?).

If you're using a recent `npm`/`yarn` version and have a lock file (`package-lock.json`/`yarn.lock`), that might be a good place to check for installed `typescript` versions.

If that doesn't seem to be the case, consider providing reproduction steps and used `tsconfig.json`.

**Comment by mjaniko** [comment]
Same issue here.

**Comment by HosseinAgha** [comment]
@richwifunds please mention the [@types/mongodb contributors](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongodb/index.d.ts#L4) in your issues to have a better change of response. @kamal is not `@types/mongodb` contributor.

@richwifunds @MichaelPlouvier @mjaniko We've updated the minimum required typescript version of `@types/mongodb` package [to TypeScript v3.0](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongodb/index.d.ts#L30) I checked with `typescript@3.6.4` and `@types/mongodb@3.3.6` and had no issues. as @AviVahl said you are probably using an older TS version.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by RaphiStein** [comment]
Problem for me was I was using a newer version of @types/mongodb with an older version of Typescript (`2.9`)

I used the release list to find a version that matches the Typescript version I am using (see the tag column)
https://www.npmjs.com/package/@types/mongodb
