### ISSUE TITLE
When test with dtslint, it shows a loop expect type.

### ISSUE THREAD

**Issue by rockwyc992** [DefinitelyTyped/DefinitelyTyped#38888]
In #38833 , I tried to resolved the side effert with what changed in `@types/express`.
But I got an Error like this:

``` typescript
ERROR: 206:1  expect  TypeScript@next expected type to be:
  RequestHandler<Dictionary<string>>
got:
  RequestHandler<ParamsDictionary>
```

Then, I push another PR ( #38887 ) to fix that, 
Without changing `ParamsDictionary` from `type` alias to `interface`, I got another Error like this:

``` typescript
ERROR: 206:1  expect  TypeScript@next expected type to be:
  RequestHandler<ParamsDictionary>
got:
  RequestHandler<Dictionary<string>>
```

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @19majkel94 @kacepe @micksatana @samijaber @aereal 

If you do not mention the authors the issue will be ignored.

**Comment by rockwyc992** [comment]
Relate to #37502, mention @OliverJAsh .
How about I change `ParamsDictionary` from `type` alias to `interface`?

I don't know why #18257 and #38887 need to do the same thing to fix it, but it is good enough to fix up all problems.

**Comment by OliverJAsh** [comment]
How come this doesn't error on `master` when we run `npm run lint express`?

**Comment by rockwyc992** [comment]
I have changed the definition of `@types/express`, so it provides generics params and makes some side-effect breaking out another package which use `@types/express`, too.

I think this is a bug for `dtslint`, which got an error that `RequestHandler` and `RequestHandler<Params>` are different type.

**Comment by rockwyc992** [comment]
The worst things, I found another issue microsoft/TypeScript#19198 .

There is another bug for `TypeScript`, it must give back `RequestHandler<Dictionary<string>>` by calling `checker.typeToString()` in `dtslint`. See [here](https://github.com/microsoft/dtslint/blob/master/src/rules/expectRule.ts#L371) for reference.

But now, it gave back `RequestHandler<ParamsDictionary>` , which is not a real exist type.
I think it is not a stable way to use `type` alias, before `TypeScript` fixed up.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
