### ISSUE TITLE
`toElement` removed from MouseEvent

### ISSUE THREAD

**Issue by spalger** [DefinitelyTyped/DefinitelyTyped#38910]
- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:
    - @leonard-thieu
    - @borisyankov
    - @choffmeister
    - @Steve-Fenton
    - @Diullei
    - @tasoili
    - @jasons-novaleaf
    - @seanski
    - @Guuz
    - @ksummerlin
    - @basarat
    - @nwolverson
    - @derekcicerone
    - @AndrewGaspar
    - @seikichi
    - @benjaminjackman
    - @s093294
    - @JoshStrobl
    - @johnnyreilly
    - @DickvdBrink
    - @King2500

TS removed the legacy `toElement` property from MouseEvents, so upgrading to TS@3.6.3 causes compilation errors:

```
      node_modules/cypress/types/jquery/index.d.ts:8155:87 - error TS2344: Type '"button" | "view" | "altKey" | "bubbles" | "cancelable" | "changedTouches" | "ctrlKey" | "detail" | "eventPhase" | "metaKey" | "pageX" | "pageY" | "shiftKey" | "char" | "charCode" | ... 13 more ... | "touches"' does not satisfy the constraint '"repeat" | "button" | "code" | "view" | "altKey" | "bubbles" | "cancelable" | "changedTouches" | "ctrlKey" | "detail" | "eventPhase" | "metaKey" | "pageX" | "pageY" | "shiftKey" | ... 55 more ... | "DOM_KEY_LOCATION_STANDARD"'.
        Type '"toElement"' is not assignable to type '"repeat" | "button" | "code" | "view" | "altKey" | "bubbles" | "cancelable" | "changedTouches" | "ctrlKey" | "detail" | "eventPhase" | "metaKey" | "pageX" | "pageY" | "shiftKey" | ... 55 more ... | "DOM_KEY_LOCATION_STANDARD"'.

      8155         TData = null> extends Partial<Pick<PointerEvent & KeyboardEvent & TouchEvent, 'altKey' | 'bubbles' | 'cancelable' |
                                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      8156         'changedTouches' | 'ctrlKey' | 'detail' | 'eventPhase' | 'metaKey' | 'pageX' | 'pageY' | 'shiftKey' | 'view' |
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      8157         'char' | 'charCode' | 'key' | 'keyCode' | 'button' | 'buttons' | 'clientX' | 'clientY' | 'offsetX' | 'offsetY' |
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      8158         'pointerId' | 'pointerType' | 'screenX' | 'screenY' | 'targetTouches' | 'toElement' | 'touches'>> {
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


      Found 1 error.
```

This code was removed by @leonard-thieu in https://github.com/DefinitelyTyped/DefinitelyTyped/commit/acbdedd54418746f9fc729ea76087d515975f407#diff-38ca0d3fc099227b1c19a1df229bc03eR62418 almost a year ago today, but that code has never been released best I can tell.

Is there a good reason this code hasn't been released? Is there an option to release an update branched from the most recent release?

**Comment by leonard-thieu** [comment]
https://github.com/cypress-io/cypress/issues/5065

**Comment by spalger** [comment]
Oh, my mistake, looks like I missed the fact that these were the types in the cypress module and not the types we are depending on.

**Comment by conficient** [comment]
I've just come across this error in my project with Typescript and VS2019 - removing the 'toElement' item seemed to fix it.
