### ISSUE TITLE
mapbox-gl ts error  "index.d.ts(53,40): error TS1110: Type expected."

### ISSUE THREAD

**Issue by kissenger** [DefinitelyTyped/DefinitelyTyped#38984]
I'm new to mapbox api and trying to install mapbox-gl I get the above error using Angular 6.  No errors showing up in Visual Studio Code in the offending index.d.ts file, but compilation fails with the error:
`ERROR in node_modules/@types/mapbox-gl/index.d.ts(53,40): error TS1110: Type expected.`

I have typescript v2.9.2 installed.

```
Angular CLI: 6.2.9
Node: 8.11.4
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.8.9
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/build-webpack     0.8.9
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9
@angular/cli                      6.2.9
@ngtools/webpack                  6.2.9
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.4
```

- [x ] I tried using the `@types/mapbox-gl` package and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  
- [ x] Mention Authors:
@macobo 
@dmytro-gokun 
@LiamAttClarke
@patrickr

**Comment by dmytro-gokun** [comment]
@kissenger 
1) If you want someone to help, provide a minimal reproduction project (as a zip file or a github repo or a stackblitz or something). It's very unlike anyone will spend time trying to recreate you environment.
2) After (1) is done, that will make a good question for stackoverflow.

NB. 2.9.2 is not the latest typescript version. The current version recommended to use with Angular 8 is 3.5.3. I have no idea about Angular 6 though.

**Comment by kissenger** [comment]
Yep, you put me in the right direction, thanks. I updated to angular v8 and typescript v3.5 and that sorted it.
