### ISSUE TITLE
[@types/ol] Update to version 6?

### ISSUE THREAD

**Issue by 9oelM** [DefinitelyTyped/DefinitelyTyped#39019]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
I'm using `ol@6.0.1` and `@types/ol@5.3.5` and have problems with some typings that have probably have not yet been updated.

Now that `ol` has been upgraded and it's not beta, I feel a need to update it. But at the same time, this is the first time for me to contribute to DefinitelyTyped. If @hanreev is not up for updating it, perhaps I could take a chance. 

- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
Yes I did and I know this one is not relevant to this!

- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/). 

- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @hanreev 

If you do not mention the authors the issue will be ignored.

**Comment by hanreev** [comment]
@9oelM I was published v6 definition to [@hanreev/types-ol](https://www.npmjs.com/package/@hanreev/types-ol) `v3.0.0`. Give it a try and if you found any error please [create a new issue](https://github.com/hanreev/types-ol/issues).

**Comment by 9oelM** [comment]
@hanreev Oh ok. Thanks for the prompt reply. I will try it!
