### ISSUE TITLE
[redis] Can't provide NX and PX flags to SET at the same time

### ISSUE THREAD

**Issue by goloroden** [DefinitelyTyped/DefinitelyTyped#39051]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @soywiz @CodeAnimal @MugeSo @UppaJung @Rokt33r @43081j @barnski @1pete @blablapolicja @ferrantejake @OpesanyaAdebayo

I am calling `set` like this:

```javascript
this.client.set(key, this.nonce, 'NX', 'PX', expiration, (err, reply): void => {
  if (err) {
    return reject(err);
  }

  resolve(reply);
});
```

Then, TypeScript complains about `"PX" is not assignable to parameter of type 'number'`. If I remove `PX`, and only hand over `NX`, it works as expected. Apparently you can not provide more than one flag (but this is supported by the Node.js `redis` module).

Could you maybe fix this eventually?

**Comment by Rokt33r** [comment]
@goloroden I'm not using redis library anymore so I don't have enough time to fix it. So why don't you submit a pr? Once you did it, I'll review the pr and help you finalize it.
