### ISSUE TITLE
[@types/react] type Ref does not include MutableRefObject but probably should.

### ISSUE THREAD

**Issue by aappddeevv** [DefinitelyTyped/DefinitelyTyped#39062]
I ran into a situation where I needed a MutableObjectRef in a child component so I could set the .current property manually--I was wrapping an old component that provides a function callback to get the html node element.

However, I could not do that without a cast in React.forwardRef as React.Ref includes React.RefObject but does not React.MutableObjectRef.

Thoughts?

**Comment by ndresx** [comment]
I just wanted to report the same, but it seems to be intended as you can see here https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31065#issuecomment-453841404.

**Comment by aappddeevv** [comment]
Yes, but that comment does not consider the 2 arg functional component for forwarding (forwardRef) the ref to be used as mutable in the other component.
