### ISSUE TITLE
[@types/puppeteer] innerText on elements is missing

### ISSUE THREAD

**Issue by goloroden** [DefinitelyTyped/DefinitelyTyped#39104]
- [x] I tried using the @types/xxxx package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for StackOverflow. (Please ask any appropriate questions there).
- [x] Mention the authors (see Definitions by: in index.d.ts) so they can respond.
  - Authors: @marvinhagemeister @cdeutsch @ksm2 @SimonSchick @serbanghita

Hey there 👋 

I am fetching an element using the `page.$eval` function, and the resulting element has some properties such as `innerHtml` – but `innerText` is missing.

Could you maybe add this?

**Comment by SimonSchick** [comment]
Can you post an explicit example?

**Comment by andfk** [comment]
+1 looks like the type needs to be changed to `HTMLElement` for the `innerText` to work but not ideal solution i guess?

**Comment by nathanmfast** [comment]
querySelectorAll returns NodeListOf<Element>:
https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll

innerText is not actually on Element:
https://developer.mozilla.org/en-US/docs/Web/API/Element 

innerText is on HTMLElement (as @andfk noticed):
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement

So it seems that the types are correct as-is, and it would probably be best to use type guards to ensure the Element you are dealing with is an instance of HTMLElement. More on that here:
https://www.typescriptlang.org/docs/handbook/advanced-types.html

**Comment by goloroden** [comment]
Thanks for explaining this! 😊

**Comment by nathanmfast** [comment]
Likewise! I had ran into the same issue and these comments helped me sort it out.
