### ISSUE TITLE
[@types/forge-apis] Many of the objects in the JS code are not declared

### ISSUE THREAD

**Issue by reediculous456** [DefinitelyTyped/DefinitelyTyped#39126]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dukedhx 

If you do not mention the authors the issue will be ignored.

`import { ActivitiesApi } from 'forge-apis';` does not exist in types but is in the library
`import { ObjectsApi } from 'forge-apis';` does not exist in types but is in the library
`import { WorkItemsApi, WorkItem } from 'forge-apis';`  does not exist in types but is in the library

It would appear all objects relating to the DesignAutomationAPI are not in the types definition file

**Comment by dukedhx** [comment]
Thanks for letting us know and will add these in the next version releasing next week.

**Comment by reediculous456** [comment]
These issues have been resolved
