### ISSUE TITLE
[@types/resemblejs] type definition missing  for getBuffer()

### ISSUE THREAD

**Issue by Benluc** [DefinitelyTyped/DefinitelyTyped#39135]
- [x] I tried using the `@types/resemblejs` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @pimterry 

I am trying to use getBuffer(), but it is not defined in `index.d.ts`.

![Bildschirmfoto 2019-10-15 um 11 54 08](https://user-images.githubusercontent.com/11851792/66821328-8c2ab580-ef42-11e9-9352-257b3bf63fa4.png)

I could fix it on my own by adding it, but i am not sure of the correct type. 

Is it string or the interface Buffer?

**Comment by pimterry** [comment]
> Is it string or the interface Buffer?

@benluc it's neither, it's an object with various properties about the comparison (e.g. `data.misMatchPercentage`). See [ResembleComparisonResult](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/resemblejs/index.d.ts#L63) and [the example code](https://www.npmjs.com/package/resemblejs#example) from the resemblejs docs.

If you're looking for the comparison image data, you can get it with `data.getImageDataUrl()`, that should give you a data URL string. The details of that are a question for the ResembleJS team though really, that's nothing to do with the type definitions.

Alternatively, from the ResembleJS docs it looks like there are some new separate APIs available via `require('resemblejs').compare` or `require("resemblejs/compareImages")` which might do what you want. That's not what you're using in your example above, but it would provide `getBuffer()`. There's no type definitions for those yet, but you're welcome to add some.
