### ISSUE TITLE
[@types/styled-components] Generics in functional components (and best practise for generics in general)

### ISSUE THREAD

**Issue by melounek** [DefinitelyTyped/DefinitelyTyped#39136]
I'm trying to use style my functional components with generics, but cannot find any approach to reach that.

For class-components is working this workaround: https://github.com/styled-components/styled-components/issues/1803#issuecomment-407332173

but for functional one, I didn't find a way how to do that, like you can see in the example below.

```javascript
import React from 'react';
import styled from 'styled-components';

let MyComponent: any;

type Props<T> = { a: T };

// with Functional doesn't work
const FunctionalComponent: <T>(p: Props<T>) => React.ReactElement<Props<T>> = props => (
  <MyComponent {...props} />
);
const StyledFunctional = styled(FunctionalComponent)`
  color: red;
`;
const StyledFunctionalRetyped = (styled(FunctionalComponent)`
  color: red;
` as React.ReactNode) as new <T>() => FunctionalComponent<T>;
//                                    -------------------
// => 'FunctionalComponent' refers to a value, but is being used as a type here.

// with Class component works fine
class ClassComponent<T> extends React.Component<Props<T>> {
  render() {
    return <MyComponent {...this.props} />;
  }
}
const StyledClassRetyped = (styled(ClassComponent)`
  color: red;
` as React.ReactNode) as new <T>() => ClassComponent<T>;

// example of usage
const Examples = (
  <>
    <StyledFunctional<string> a={8} />
    {/*               ------ => doesn't support generics (expected 0 arguments) */}
    <StyledFunctionalRetyped<string> a={8} /> {/* doesn't work*/}
    <StyledClassRetyped<string> a={8} /> {/* works properly (shows error) */}
  </>
);

```

- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] Mention the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @Lavoaster @Jessidhia @JKillian @eps1lon @flavordaaave @wagerfield

**Comment by kyrim** [comment]
I am having the exact same issue. Is there any way to work around this and preserve type safety?

Even being able to convert the functional component into a concrete implementation and then passing it to styled like `styled(FunctionalComponent<string>)` would be super useful.

**Comment by osdiab** [comment]
same!

**Comment by osdiab** [comment]
I've left my current workaround at the same issue on the `styled-components` repo: https://github.com/styled-components/styled-components/issues/1803#issuecomment-550895376

Maybe there's some TypeScript feature I don't know about, but I suspect that TypeScript itself isn't expressive enough to preserve the generics as is. After looking at the `styled-components` code it seems that the new type for the resulting component gets new props via this code in `styled-base/types/helper`:

```ts
export type PropsOf<
  Tag extends React.ComponentType<any>
> = Tag extends React.SFC<infer Props>
  ? Props & React.Attributes
  : Tag extends React.ComponentClass<infer Props>
    ? (Tag extends new (...args: Array<any>) => infer Instance
        ? Props & React.ClassAttributes<Instance>
        : never)
    : never
```

So in order to calculate the new props, it has to evaluate the original ones, and when it tries to do that I believe it just assumes the generics to be as general as possible given their constraints.

If TypeScript were to allow it to remain parameterized, then for each use of an unspecified generic, TypeScript would need to include that generic in the resulting type (which there can be arbitrary amounts depending on how many generic type parameters you pass in to the parent's generics); it would probably also preclude the parent from explicitly specifying its generics, because if it did then it wouldn't be correct if any of the type parameters passed in were generic.

I think this might be related to this long-unresolved issue on the TypeScript repo: https://github.com/microsoft/TypeScript/issues/1213

**Comment by Naararouter** [comment]
I've found the next solution for me. It seems, it fulfils a need task: https://github.com/styled-components/styled-components/issues/1803#issuecomment-573196034

**Comment by melounek** [comment]
Thanks @Naararouter !

Did some cleaning to find out core of the issue and it's all about wrapping the `styled()` component by a generic one, which handles the generics-typing.

```javascript
import React from "react";
import styled from "styled-components";

type Props<T> = { a: T; className?: string; }

const GenericComponent: <T>(p: Props<T>) => 
    React.ReactElement<Props<T>> = ({ a, ...props }) => <div {...props}>{a}</div>;

// wrapped styled-component and re-typed it works as expected
const StyledGeneric = <T extends {}>(props: Props<T>) => {
  const StyledComponent = styled(GenericComponent)`
    color: red;
  `;
  return <StyledComponent {...props} />;
};

export const Example = () => <StyledGeneric<number> a={8} />;
```
Closing.

**Comment by Naararouter** [comment]
@melounek I'm glad that my way was helpful, but...be careful, your simplification has, at least, one critical side-effect, that's why I came to my way exact. 
It will broken if you add, for example, `onChange?: (value: T) => void;` in your `interface Prop<T>`. Pretty common case.

**Comment by melounek** [comment]
Thanks! -> I updated my simplified solution by replacing `styled()` with `styled<React.FC<Props<T>>>()` so it handles your use-case too.

**Comment by Naararouter** [comment]
@melounek Still doesn't work for my initial case with antd library :( so...I'll be glad if you will have a time to let me know where can I miss something by adapting the code below for your example. I had been trying and...Did not work out, different unpleasant type error on each steps :'(

**Source**:
(this works fine, but adaptation by your method didn't work out)
```javascript
import { Select } from 'antd';
import { SelectProps } from 'antd/lib/select';
import React from 'react';
import styled, { StyledComponent } from 'styled-components';

export function StyledSelect<T>(): StyledComponent<React.FC<SelectProps<T>>, {}, {}, never> {
    return styled(props => <Select<T> {...props} />)`
        &.ant-select {
            width: 100%;
        }
    `;
}
```

P.s.: to be honest, maybe, this is related with antd definition mostly. I still have not had a time to check it thoroughly, but...in any case, styled-components & typescript is here...and I think we can continue this conversation here yet :D

**Comment by melounek** [comment]
@Naararouter I would do it this way:
```javascript
const StyledSelect = <T extends {}>(props: SelectProps<T>) => {
  const StyledComponent = styled<React.FC<SelectProps<T>>>(
    (Select as unknown) as React.FC<SelectProps<T>>
  )`
    color: red;
  `;
  return <StyledComponent {...props} />;
};
```
But I think, your solution is also OK. 
You are re-typing `styled-component` internals and I am re-typing `antd/select` internals, so neither one is perfect, but both will do it's job, so it's good to have both our codes in this thread.

PS: Another option is to wrap the antd/select with styled <div> to workaround this.

**Comment by choznerol** [comment]
Although still a bit verbose, `<StyledFunctional<FC<Props<Foo>>> ... />` seems to provide the same type safty as `<Functional<Foo> ... />` does.

Base on the example provided by OP:

> <img width="756" alt="圖片" src="https://user-images.githubusercontent.com/12410942/97783249-70d42c00-1bd1-11eb-9f94-928463bddfcc.png">

Now ts can tell that `'8'` is valid while `8` is invalid

P.s. I also use a similar workaround for [`antd/select`](https://ant.design/components/select/)

> <img width="344" alt="圖片" src="https://user-images.githubusercontent.com/12410942/97782770-67959000-1bce-11eb-8885-784515664140.png">

Environment:
- styled-components: 5.0.0
- @types/styled-components: ^5.1.4

**Comment by tokland** [comment]
@melounek, thanks, I tried your solution,  it types fine. However, now I get the typical runtime warning that the component has been created dynamically. Am I missing something? (styled-components": "5.2.1")

**Comment by melounek** [comment]
I just tested in freshly created app ((styled-components: 5.2.1 / "react-scripts": "4.0.0-next.98 / "typescript": "^4.1.0") and I didn't find any issue with starting or building the app

**Comment by tokland** [comment]
@melounek An example:

https://github.com/tokland/test-styled-components/blob/main/src/App.tsx

![image](https://user-images.githubusercontent.com/24643/99849125-41369500-2b7b-11eb-8c3f-a24f4acb14bd.png)

**Comment by melounek** [comment]
You are probably right @tokland and there is something wrong with my solution. Based on what the [official documentation](https://styled-components.com/docs/basics#define-styled-components-outside-of-the-render-method) says: `WARNING: THIS IS VERY VERY BAD AND SLOW, DO NOT DO THIS!!!`

But @choznerol 's solution probably solves our struggles. See my PR for your code if you see fit: https://github.com/tokland/test-styled-components/pull/1/files

**Comment by tokland** [comment]
@melounek, I see, so we just need to transform the generic type through `React.FC<ComponentProps<T>>`, that will work for me, thx!

**Comment by aaronmw** [comment]
@melounek what do you recommend in today's world where React.FC has been deprecated?

**Comment by melounek** [comment]
@aaronmw You sure? I don't see any `deprecated` note about it. Maybe you mixed up with `React.SFC`? See here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a8373718fbf79a60363bcdee7ffd2e5007f9c5df/types/react/index.d.ts#L545

**Comment by aaronmw** [comment]
@melounek Sorry, I was thinking of its removal from create-react-app. I was reading this whole thread just yesterday after trying to figure out the right way to do things, and with so many examples of React.FC in nearly every Typescript demo or answer, I am... Confused.

Here's the story of its removal from create-react-app: https://github.com/facebook/create-react-app/pull/8177

**Comment by badsyntax** [comment]
@melounek none of the workaround seems like a good solution. Can you re-open this issue and tag the styled-component TS authors so they're aware of this issue?

**Comment by melounek** [comment]
You think the the @choznerol 's [solution](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/39136#issuecomment-719950054) is not good enough?  - using `<StyledFoo<FC<Props<Bar>>> ... />`

Could you elaborate what are you missing or how exactly should be fixed the `styled-components` before reopening it?

**Comment by badsyntax** [comment]
Perhaps i'm having a bad day and missing something obvious, but I don't see how that solution will work in this context: https://codesandbox.io/s/awesome-worker-c78m8?file=/src/App.tsx

**Comment by melounek** [comment]
@badsyntax here: https://codesandbox.io/s/eager-wood-uk4of?file=/src/App.tsx

**Comment by badsyntax** [comment]
@melounek guess i am having a bad day. many thanks, i appreciate it!

**Comment by ahoisl** [comment]
The solution posted by @choznerol seems to be broken with release 5.1.10 of `@types/styled-components`. Previous correctly typed generic styled components do not compile any more and I could not get it to work.

It's basically reverted to the former behavior as when not explicitly specifying the generic type 😒 

Does anyone else experience the same problem with `@types/styled-components` 5.1.10?

**Comment by MauriceNino** [comment]
What worked for me was the answer from this SO post: https://stackoverflow.com/a/67546231/9150652

```tsx 
interface IProduct {
  id: string;
  name: string;
}

const StyledFlatList = styled(FlatList as new () => FlatList<IProduct>)`
  background-color: #f7f7f7;
`
```
