### ISSUE TITLE
[Enhancement] Latest Screeps definitions are not added. 

### ISSUE THREAD

**Issue by MatthewARoy** [DefinitelyTyped/DefinitelyTyped#39158]
https://screeps.com/forum/topic/2814/factories-new-resources-npc-strongholds

**Comment by pyrodogg** [comment]
Addressed by #39252

**Comment by 0l1v** [comment]
Note that #39252 addresses factories, new resources, strongholds, core invaders, ruins and some old stuff that were missing.
It does not address the store and market additions.

**Comment by pyrodogg** [comment]
Now fully addressed by #40613
