### ISSUE TITLE
`privateDecrypt` and `privateEncrypt` are missing from node crypto definitions

### ISSUE THREAD

**Issue by orva** [DefinitelyTyped/DefinitelyTyped#39180]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
 - Authors: @SimonSchick @Touffy @trivikr (notifying only authors who have been involved with `crypto.d.ts`)

These typings were removed in cbe21d594a3b24fd1b93719958bc90ab6007ac51 (released in `@types/node@12.11.0`) but both `privateDecrypt` and `privateEncrypt` are still part of the node `crypto` API. 

Below is snippet where removal happened and it also contains rather interesting changes to `public{Encrypt,Decrypt}` functions as well, which made me open this issue instead of making reverting PR.

```
-    function publicEncrypt(public_key: RsaPublicKey | KeyLike, buffer: Binary): Buffer;
-    function privateDecrypt(private_key: RsaPrivateKey | KeyLike, buffer: Binary): Buffer;
-    function privateEncrypt(private_key: RsaPrivateKey | KeyLike, buffer: Binary): Buffer;
-    function publicDecrypt(public_key: RsaPublicKey | KeyLike, buffer: Binary): Buffer;
+    function publicEncrypt(key: RsaPublicKey | RsaPrivateKey | KeyLike, buffer: NodeJS.ArrayBufferView): Buffer;
+    function publicDecrypt(key: RsaPublicKey | RsaPrivateKey | KeyLike, buffer: NodeJS.ArrayBufferView): Buffer;
```

**Comment by SimonSchick** [comment]
I think I incorrectly merged those together due to the change that allows and their names being lexically similar.
> `Because RSA public keys can be derived from private keys, a private key may be passed instead of a public key.` 

See [here](https://nodejs.org/dist/latest-v12.x/docs/api/crypto.html#crypto_crypto_publicdecrypt_key_buffer)

Fix PR is out, if you need to fix this locally you can either downgrade the node version temporarily or add

ts
```
declare module 'crypto' {
    function privateDecrypt(private_key: RsaPrivateKey | KeyLike, buffer: NodeJS.ArrayBufferView): Buffer;
    function privateEncrypt(private_key: RsaPrivateKey | KeyLike, buffer: NodeJS.ArrayBufferView): Buffer;
}
```

**Comment by orva** [comment]
That link explains a lot, thank you! 

We already have local temporary band-aids, so no worries. Thanks for the fast fix :)

**Comment by SimonSchick** [comment]
Please don't close the issue until the PR is merged lol.

**Comment by orva** [comment]
Ooops, I blame lack of morning coffee for the misclick
