### ISSUE TITLE
Leafletjs: can no longer extend classes using TypeScript's class system

### ISSUE THREAD

**Issue by coxm** [DefinitelyTyped/DefinitelyTyped#3923]
It used to be possible to extend Leaflet classes using TypeScript's class system, for example:

``` javascript
class MyMarker extends L.Marker {
    // ...
}
```

This has several benefits over using the Leaflet class system - in particular, much  better type checking. I've created two examples [here](https://gist.github.com/coxm/d89e3a79c894aca37241) to point out these advantages.

As of 427d97003e0cb8754a63fb9c6577606322c70634 this hasn't been possible (for example, `L.Marker` is now an interface, rather than a class, in the definitions file, so we hit "TS2311: A class may only extend another class"). Is there any way to make the definitions file more plugin-friendly without losing this ability?

**Comment by gentisaliu** [comment]
+1

**Comment by vvakame** [comment]
please try again on TypeScript 1.6.2.
