### ISSUE TITLE
[@types/yargs] the conversion of kebab-case to camelCase argument names is not done in the types

### ISSUE THREAD

**Issue by lf-** [DefinitelyTyped/DefinitelyTyped#39255]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @poelstra @mizunashi-mana @pushplay @jeffkenney @JimiC @steffenvv @forivall @ExE-Boss

If you do not mention the authors the issue will be ignored.

Hi! It appears that the yargs type definitions do not implement a behaviour in yargs where you can write something like `.option('option-name')` and the resulting object will have both a `option-name` and an `optionName` property. Currently the types only show the `option-name` property.

More full example:
```typescript
yargs.options({
    ['max-subjects']: {
        type: 'number',
        describe: 'Only scrape this many subjects; good for testing',
        default: 2,
    },
}).argv
```

yields

```javascript
{ _:
   [ '/usr/bin/node',
     '/home/lf/dev/build/scrape.js' ],
  'max-subjects': 2,
  maxSubjects: 2,
  '$0': 'build/scrape.js' }
```

**Comment by ExE-Boss** [comment]
This is&nbsp;pretty much impossible to&nbsp;currently&nbsp;do, as&nbsp;**TypeScript** doesn’t currently provide a&nbsp;way to&nbsp;do&nbsp;string transformations with&nbsp;type&nbsp;keys.

**Comment by lf-** [comment]
:(

I prefer the look of the kebab-case command line arguments in the help list, but it appears that you can give them in camelCase when defining them in the yargs options and then give them as kebab-case on the command line so at least the user experience is fine if a little odd. Doing this fixes the types issue.

Thanks for looking into this!

**Comment by forivall** [comment]
i usually handle this by defining a type definition like the following:
```
..., (rawArgs) => {
  type RawArgs = typeof rawArgs;
  interface Args extends RawArgs {
    kebabCase: Args['kebab-case'];
  }
  const args = rawArgs as Args;
  ...
```

**Comment by forivall** [comment]
Now that typescript 4.1 is out, you can do the following:

```ts
type PascalCase<S extends string> = string extends S
  ? string
  : S extends `${infer T}-${infer U}`
  ? `${Capitalize<T>}${PascalCase<U>}`
  : Capitalize<S>;
type CamelCase<S extends string> = string extends S
  ? string
  : S extends `${infer T}-${infer U}`
  ? `${T}${PascalCase<U>}`
  : S;
type CamelCaseKey<K extends PropertyKey> = K extends string ? CamelCase<K> : K;

export type CamelcaseKeys<T> = T &
  { [K in keyof T as Exclude<CamelCaseKey<K>, K>]: T[K] };
```

```ts
..., (rawArgs) => {
  const args = rawArgs as CamelcaseKeys<typeof rawArgs>;
  ...
```

Given some free time and demand for this (and re-remembering the proper way to supply types for specific versions of typescript in definitely typed), we can merge this in.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
