### ISSUE TITLE
MulterError missing from multer interface.

### ISSUE THREAD

**Issue by ram-nad** [DefinitelyTyped/DefinitelyTyped#39263]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jt000 @vilic @mxl 

If you do not mention the authors the issue will be ignored.

`MulterError` is not given as part of the Multer Interface.

**Comment by ram-nad** [comment]
I have also tried to add this code for solving this issue. Please let me know if it is correct approach.

```typescript
interface errorMessages {
        readonly 'LIMIT_PART_COUNT': 'Too many parts';
        readonly 'LIMIT_FILE_SIZE': 'File too large';
        readonly 'LIMIT_FILE_COUNT': 'Too many files';
        readonly 'LIMIT_FIELD_KEY': 'Field name too long';
        readonly 'LIMIT_FIELD_VALUE': 'Field value too long';
        readonly 'LIMIT_FIELD_COUNT': 'Too many fields';
        readonly 'LIMIT_UNEXPECTED_FILE': 'Unexpected field';
}

declare type ErrorCodes = 'LIMIT_PART_COUNT' | 'LIMIT_FILE_SIZE' | 'LIMIT_FILE_COUNT' | 'LIMIT_FIELD_KEY' | 'LIMIT_FIELD_VALUE' | 'LIMIT_FIELD_COUNT' | 'LIMIT_UNEXPECTED_FILE';

interface MulterError extends Error {
        /* Constructor for MulterError */
        new (code: ErrorCodes, field?: string)
        /* Name of the constructor */
        name: string;
        /* Error Message */
        message: string;
        /* Error code */
        code: ErrorCodes;
        /* Field Name */
        field?: string;
}

.......

interface Multer {
    (options?: multer.Options): multer.Instance;

    /* The disk storage engine gives you full control on storing files to disk. */
    diskStorage(options: multer.DiskStorageOptions): multer.StorageEngine;
    /* The memory storage engine stores the files in memory as Buffer objects. */
    memoryStorage(): multer.StorageEngine;
    /* Multer Error Object */
    MulterError: multer.MulterError;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
