### ISSUE TITLE
[@types/stripe] default_payment_method and off_session missing from ISubscriptionCustCreationOptions and ISubscriptionUpdateOptions

### ISSUE THREAD

**Issue by arbinoy** [DefinitelyTyped/DefinitelyTyped#39279]
- [x] I tried using the `@types/stripe 7.10.3` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask  any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wjohnsto @sampsonjoliver @brannon @kkamperschroer @starhoshi @bruun @galtalmor @htunnicliff @squirly @tzarger @ifiokjr @yultyyev @cpsoinos @adamduren @saranshkataria @0xJoKe @delianides @gokulchandra @viralpickaxe @chrisleck @opticalgenesis @spacetag @vaskevich @dhaspden @esetnik @schfkt @ChrisZieba @pushplay @Stilborg @jvik @richardwardza 

Can't proceed with the process because it's returning errors because of missing properties that were indicated in Stripe's API documentation. Appreciate the help. Thanks.

**Comment by pushplay** [comment]
This would be an easy first contribution.

**Comment by rdhelms** [comment]
@arbinoy @aldarund 
I see that the merged PR added these options to `ISubscriptionUpdateOptions`, but wasn't this issue also for `ISubscriptionCustCreationOptions`? Is there a separate issue where that is being tracked?

**Comment by pocketcolin** [comment]
@rdhelms I created a new PR to add the missing type definitions to `ISubscriptionCustCreationOptions` here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41911
