### ISSUE TITLE
[@types/electron-json-storage] Electron binary in dependencies

### ISSUE THREAD

**Issue by sameoldmadness** [DefinitelyTyped/DefinitelyTyped#39285]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/electron-json-storage` package and had problems.
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andy-ms

Due to `electron` package [being listed as a dependency](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18386/files#diff-d1dcdae1c558b269fdb626a0799400acR2-R4) Electron binary is present in `@types/electron-json-storage`.

This is problematic at least from a space usage perspective. Can we somehow prevent types from download binaries?

<img width="217" alt="Screenshot 2019-10-21 at 10 54 39" src="https://user-images.githubusercontent.com/1537724/67196463-25524400-f3fb-11e9-9325-f7a7b23d907e.png">

**Comment by KazuyaHayashi** [comment]
I made a PR to remove `electron` from `package.json` and it has been merged.
This issue should be resolved on `"@types/electron-json-storage": "~4.5.0"`
