### ISSUE TITLE
[@types/react-helmet] htmlAttributes type no longer allows data attributes

### ISSUE THREAD

**Issue by wKovacs64** [DefinitelyTyped/DefinitelyTyped#39357]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ykzts, @evanbb, @isman-usoh, @sammkj, @yuit

If you do not mention the authors the issue will be ignored.

---

Looks like `htmlAttributes` was changed from `any` to `JSX.IntrinsicElements['html']` in #39161. This does not allow for `data-*` attributes, which should be valid (AFAIK).

#### Example

```jsx
<Helmet htmlAttributes={{ 'data-foo': 'bar' }} />
```
```
Object literal may only specify known properties, and ''data-foo'' does not exist in
type 'DetailedHTMLProps<HtmlHTMLAttributes<HTMLHtmlElement>, HTMLHtmlElement>'.
```

Not sure of the appropriate fix. Thoughts?

**Comment by wKovacs64** [comment]
@ykzts @evanbb Can you take a look at this? Thanks.

**Comment by evanbb** [comment]
yeah, that makes sense... how about this?

```ts
type HtmlProps = JSX.IntrinsicElements['html'] & {
  [key: string]: string
};
```

that would still support typechecking of known attributes but enable you to add arbitrary attributes as well... not ideal as it would allow you to do this, which fails at runtime:

```ts
<Helmet htmlAttributes={{ 'arbitrary garbage': 'something bogus' }} />
```

ideally we could do something slick with mapped types like

```ts
type HtmlProps = JSX.IntrinsicElements['html'] & {
  [key: string]: isDataAttribute(key) ? string : never
}
```

but that's not supported 😭

**Comment by wKovacs64** [comment]
> ideally we could do something slick with mapped types like

Yeah, that's what I was hoping for, but I don't know how and sounds like it isn't possible. I'll PR the looser one. Thanks!
