### ISSUE TITLE
@types/mongodb - Generics does not work with v3.2.x or v3.3.x

### ISSUE THREAD

**Issue by lirbank** [DefinitelyTyped/DefinitelyTyped#39358]
Using generics to set the schema does not seem to work since v3.2.x of @types/mongodb

See this example using @types/mongodb v3.1.32 (works):
https://codesandbox.io/s/typesmongodb-3132-works-nmxbc

See this example using @types/mongodb v3.3.6 (type error):
https://codesandbox.io/s/typesmongodb-336-type-error-onshs

Reproduction (same as CodeSandbox):
```ts
import { Db, Collection } from "mongodb";

export default class Model<Schema extends { _id: string }> {
  private readonly db: Db;
  private readonly collection: Collection<Schema>;

  public constructor(db: Db, collectionName: string) {
    this.db = db;
    this.collection = db.collection(collectionName);
  }

  public findOneById(id: string) {
    // This gives the type error below on @types/mongodb v3.3.6
    return this.collection.findOne({ _id: id });
  }
}
```

TS Error:
```
Argument of type '{ _id: string; }' is not assignable to parameter of type 'FilterQuery<Schema>'.
  Type '{ _id: string; }' is not assignable to type '{ [P in keyof Schema]?: MongoAltQuery<Schema[P]> | QuerySelector<MongoAltQuery<Schema[P]>> | undefined; }'.
```

Authors: @CaselIT @alanmarcell @bitjson @dante-101 @mcortesi @EnricoPicci @AJCStriker @julien-c @daprahamian @denys-bushulyak @BastienAr @sindbach @geraldinelemeur @jishi @various89 @angela-1 @hector7 @floric @erikc5000 @Manc @jloveridge @ranguna @HosseinAgha @albertossilva

**Comment by HosseinAgha** [comment]
Hi @lirbank,  
This looks to me like a TypeScript [mapped types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types) bug.  
I can confirm that this does not work:  
```typescript
  const genericFunc = async <Schema extends { _id: string }>() => {
    type a = { [P in keyof Schema]: Schema[P] };
    const b: a = { _id: 'sd' };
  }
```
And this does work:  
```typescript
  type Schema2 = { _id: string };
  type a2 = { [P in keyof Schema2]: Schema2[P] };
  const b2: a2 = { _id: 'sd' };
```
We've implement `collection.find` types very similar with above code.  
There is not much that we can do here. I think you should open (look for) a TypeScript issue.  
I have to admit that you are doing a pretty complicated job with TypeScript generic types (generic on top of generic on top of generic 😄) and TypeScript compiler is still an awesome piece of engineering that lets you handle this scenarios.

**Comment by jimbuck** [comment]
Agreed, this is definitely a bug! If you guys put a bug into the TypeScript repo then please don't forget to reference this PR. I'd love to see where this goes.

My demo code: http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=11&pc=2#code/C4TwDgpgBAygxgCwgWwIZQLxQN5QPoCWAJgFxQDOwATgQHYDmUAvgNwBQbA9J1AOoD2VANbkSbUJCgAFVFWAFUAG3hI0ARkzTZ8pQB4VKVAD52cfrUpQARgCYyMuQuWJDGrLkKkoAcnJFvzOxcPAAi-BDktN7AUADugkJQABRWAK4xBDHkCPypikQAlGIAZqm0cPLmUPQQtBA0cACyEMA5RLyZCACiAB7AtUTkugAqUBB9A+SwLmhGSQU4bFDLUBLQDjrOqqg2mhtOIyZLK2YWMVZq9tpOBmi77vjEZL7+gWxMQA

**Comment by kevinclarkadstech** [comment]
Grrrrr I found the same issue using a generic service.  :/  TypeScript has been a little "dumber" lately it seems.  For a workaround I just asserted using as:

```collection.findOne({id: 2 } as FilterQuery<Entity<T>>, (error, result) => {
                        
                    })```

**Comment by HosseinAgha** [comment]
Hi @lirbank,  
According to (your issue) https://github.com/microsoft/TypeScript/issues/35077 and (my issue) https://github.com/microsoft/TypeScript/issues/35647 TypeScript (and mongo typings) work as expected in this scenario.  
I don't think our mongo driver generics can work with other generics in a format that you expect them to. __We need the `keyof Schema`__ in order to generate right typing for mongo methods and `keyof` is not working properly in this scenario (checkout https://github.com/microsoft/TypeScript/issues/35647#issuecomment-566543066).  
I think we have enough workarounds (including yours) for this issue to close.

**Comment by lirbank** [comment]
Hi @HosseinAgha - I agree, looks like we're at the end of the road with this one. 

Thanks for looking into it!

**Comment by rnbrady** [comment]
A workaround with reference to original example:

```typescript
return this.collection.findOne({ _id: id } as FilterQuery<Schema>);
```

**Comment by gyl89** [comment]
Got the aforementioned error after uploading to latest typescript version. The previous workaround did not work for me. I has to cast using
`this.collection.findOne({ _id: id } as any);`

**Comment by doflo-dfa** [comment]
At least the most recent mongodb typings also seem to conflate the Options for Find and FindOne which are both using FindOptions which there are in fact unique options for both methods
