### ISSUE TITLE
[@types/react-native] Missing Websocket types

### ISSUE THREAD

**Issue by AlexCatch** [DefinitelyTyped/DefinitelyTyped#39428]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
  - @alloy 
  - @huhuanming 
  - @iRoachie 
  - @Skn0tt 
  - @timwangdev 

If you do not mention the authors the issue will be ignored.

It appears the latest version of `global.d.ts` is missing types for WebSocket - causing any React Native apps that utilise WebSockets to throw a fit.

**Comment by alloy** [comment]
Please provide a PR instead, if possible–we generally don’t have the bandwidth to fix missing coverage for others and these issues just go stale.
