### ISSUE TITLE
[@types/react-helmet] bodyAttributes now requires 'className' property not being mapped in react-helmet ^5.2.0

### ISSUE THREAD

**Issue by clem-turp** [DefinitelyTyped/DefinitelyTyped#39430]
- [x] I tried using the `@types/react-helmet^5.0.13` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ykzts, @evanbb, @isman-usoh, @sammkj, @yuit 

Using `react-helmet^5.2.0`.
Since `bodyAttributes` is now a `JSX.IntrinsicElements['body']` instead of an `Object`, it now requires a `className` field. However, the `REACT_TAG_MAP` constant in the react-helmet library maps `class` to `className` and is thus ignoring the classes.

Maybe create a temporary type which extends `JSX.IntrinsicElements['body']` and adds a `class` field to it? While waiting to see if `react-helmet` would change the mapping.

**Comment by evanbb** [comment]
looks related to #39357 

see my [comment there](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/39357#issuecomment-547630291) for a proposed workaround

**Comment by evanbb** [comment]
and by "workaround" i mean a fix that would need to be implemented 😄
