### ISSUE TITLE
[@types/styled-components] Upcoming v5.0 

### ISSUE THREAD

**Issue by joshjg** [DefinitelyTyped/DefinitelyTyped#39450]
Creating this to track changes needed for v5.0 of styled-components, currently in beta.

Roadmap: https://github.com/styled-components/styled-components/issues/1934
Releases: https://github.com/styled-components/styled-components/releases

New APIs:
- `useTheme` hook
- `StyleSheetManager` `stylisPlugins` prop
- ?

**Comment by probablyup** [comment]
We also formally removed the `.attrs({ color: p => p.color })` "subfunction" syntax (it was deprecated.) The recommended pattern if you need to consume props is `.attrs(p => ({ color: p.color }))`

**Comment by probablyup** [comment]
For `StyleSheetManager` there's also the new boolean props:

- `disableCSSOMInjection`
- `disableVendorPrefixes`

**Comment by gbiryukov** [comment]
Also it seems there is no requirement for `StyleSheetManager` to either  have `sheet` either `target` props, both of them are optional.
This use-case is valid when you use `StyleSheetManager` on client side just to disable vendor prefixes.

**Comment by PaulACoroneos** [comment]
@probablyup  Hi there. I noticed there is an active PR to export useTheme for react native. But it appears there still isn't a type definition for useTheme for the React implementation. Is this as expected at this time? Thank you.

**Comment by joshjg** [comment]
#42415
