### ISSUE TITLE
React Router v0.13.x

### ISSUE THREAD

**Issue by BabakMN** [DefinitelyTyped/DefinitelyTyped#3991]
Please add definitions for react router v0.13.x

**Comment by duncanmak** [comment]
I'm working on this right now, my branch is here: https://github.com:duncanmak/DefinitelyTyped/tree/react-router-0.13

**Comment by Shearerbeard** [comment]
Awesome! I had just started messing with this myself but seems like your a lot further along than I am.

**Comment by Shearerbeard** [comment]
Just realized that this work was back in April, is this still in progress?

**Comment by kaoz28** [comment]
Not sure if I should drop this in here or if I should make a new issue... basically, I can not find a way to make Typescript understand rect-router's new way of using the context in react ES6 components.  Mainly, using code like this to get the react-router to function in react ES6 classes:

```
import React from 'react';
class LoginPage extends React.Component {
  ...
  onChange() {
    this.context.router.replaceWith('/');
  }
  ...
}

LoginPage.contextTypes = {
  router: React.PropTypes.func.isRequired
};

export default LoginPage;
```

Gives an error like this: ```Property 'contextTypes' does not exist on type 'typeof LoginPage'.```

Every React component using ES6 and react-router will need to do this since react's new ES6 features does not support mixins.  I am linking the discussion of this issue from the react-router repo (https://github.com/rackt/react-router/issues/975).  Has anyone seen this before?  How are people using Typescript, React ES6 components, and react-router?

**Comment by kaoz28** [comment]
After 3hrs, solved it with ES7 syntax:

```
import React from 'react';
class LoginPage extends React.Component {

  static contextTypes = {
  router: React.PropTypes.func.isRequired
};

...
  onChange() {
    this.context.router.replaceWith('/');
  }
  ...
}

export default LoginPage;
```

**Comment by kaoz28** [comment]
Ok, still not solved, as now Typescript is complaining about this syntax (the new way react-router is used in ES6 react classes).  I'm getting the following TS error now, but this is the only way to use react-router in react ES6 classes:

```
(51,19): Type 'typeof Unauthorized' is not assignable to type 'ComponentClass<any>'.
  Types of property 'contextTypes' are incompatible.
    Type '{ router: Validator<any>; }' is not assignable to type 'ValidationMap<any>'.
      Index signature is missing in type '{ router: Validator<any>; }'.
```

Narrowed down the culprit to the React TS def. file at:

```
interface ComponentClass<P> {
        new(props?: P, context?: any): Component<P, any>;
        propTypes?: ValidationMap<P>;
        contextTypes?: ValidationMap<any>;
        childContextTypes?: ValidationMap<any>;
        defaultProps?: P;
    }
```

Commenting out ```contextTypes?: ValidationMap<any>;``` makes it work, but I am nervous of the repercussions.  Has anyone else seen this, or is everyone still using React without ES6?

**Comment by Mauricio28** [comment]
Ok, just figured out that TS wanted contextTypes typed, here is the final version for anyone else that may run into this.  Not an issue with the react, or react rout-er type definitions:

```
import React from 'react';
class LoginPage extends React.Component {

  static contextTypes: React.ValidationMap<any> = {
  router: React.PropTypes.func.isRequired
};

...
  onChange() {
    this.context.router.replaceWith('/');
  }
  ...
}
```

**Comment by cdroulers** [comment]
@Shearerbeard The master branch is for 0.13.3 right now. https://github.com/borisyankov/DefinitelyTyped/blob/master/react-router/react-router.d.ts

There is a pull request to upgrade to 1.0.0 (https://github.com/borisyankov/DefinitelyTyped/pull/6073)

**Comment by robyoder** [comment]
Suggest this to be closed. Definition version is at 2.0.0 as of this writing.

**Comment by vvakame** [comment]
wow, thanks.
