### ISSUE TITLE
[@types/react-dates] chooseAvailableStartDate & chooseAvailableEndDate prop types incorrect

### ISSUE THREAD

**Issue by Coreylantz** [DefinitelyTyped/DefinitelyTyped#39929]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/react-dates` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ArturAmpilogov @NathanNZ

If you do not mention the authors the issue will be ignored.

`chooseAvailableStartDate?: (date: string) => string;`
`chooseAvailableEndDate?: (date: string) => string;`

I believe the prop should be an object:
https://github.com/airbnb/react-dates/blob/master/src/defaultPhrases.js#L29

**Comment by atdrago** [comment]
It looks like this is also true for `chooseAvailableDate`, `dateIsUnavailable`, and `dateIsSelected`: 
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/371a2eaabd23242dc28307cf1457f98955f2bf65/types/react-dates/index.d.ts#L299
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/371a2eaabd23242dc28307cf1457f98955f2bf65/types/react-dates/index.d.ts#L334
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/371a2eaabd23242dc28307cf1457f98955f2bf65/types/react-dates/index.d.ts#L368
