### ISSUE TITLE
[@types/node] Function fs.promises.opendir is missing

### ISSUE THREAD

**Issue by TdyP** [DefinitelyTyped/DefinitelyTyped#39930]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @a-tarasyuk @jkomyno @alvis @r3nya 

If you do not mention the authors the issue will be ignored.

The new function `fs.promises.opendir` is missing in types definition (property doesn't exist)

More infos on this function here: https://nodejs.org/api/fs.html#fs_fspromises_opendir_path_options

**Comment by AviVahl** [comment]
Will be added by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39914

**Comment by galkin** [comment]
@TdyP, could you check and close?

**Comment by AviVahl** [comment]
New signature has another issue tracked at https://github.com/DefinitelyTyped/DefinitelyTyped/issues/39994
