### ISSUE TITLE
[@types/node] fs.promises.opendir - fs.Dirent is not async-iterable

### ISSUE THREAD

**Issue by AviVahl** [DefinitelyTyped/DefinitelyTyped#39994]
Tried using the new `fs.promises.opendir` definitions (sample code from node documentation):
```ts
import fs from fs;
async function print(path: string) {
  const dir = await fs.promises.opendir(path);
  for await (const dirent of dir) {
    console.log(dirent.name);
  }
}
print('./').catch(console.error);
```
and got:
`Type 'Dirent' must have a '[Symbol.asyncIterator]()' method that returns an async iterator.ts(2504)`

I've noticed `fs.promises.opendir` and `fs.opendirSync` both return `Dirent` (wrong? should be `Dir`?). Callback and promisified versions appear to have the correct result type. 

- [x] I tried using the `@types/node@12.12.0` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick 

If you do not mention the authors the issue will be ignored.

**Comment by SimonSchick** [comment]
Yup, fixing.
