### ISSUE TITLE
feature.getGeometry() Needs a Union Type

### ISSUE THREAD

**Issue by theAndrewCline** [DefinitelyTyped/DefinitelyTyped#40046]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/ol` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

 @hanreev 

feature.getGeometry() is currently returning type Geometry, when in fact it can return Geometry | GeometryCollection

**Comment by hanreev** [comment]
@theAndrewCline
It's written in the [source](https://github.com/openlayers/openlayers/blob/af9f26b9d343e5496ea44a729265c4002616b240/src/ol/Feature.js#L142). If you think it was a mistake, open an issue there.

**Comment by theAndrewCline** [comment]
Okay sounds good. Thanks!

**Comment by hanreev** [comment]
one more thing, `GeometryCollection` is a derivative of `Geometry`
