### ISSUE TITLE
[@types/prop-types] Type error while using prop-types with typescript generics

### ISSUE THREAD

**Issue by BlueSky1997AL** [DefinitelyTyped/DefinitelyTyped#40063]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DovydasNavickas @ferdaber @eps1lon 

### Description

In the following codes:

```ts
import PropTypes from 'prop-types';
import React from 'react';

export interface TestProps<T> {
    value?: T;
    onChange?: (param1: string, param2: number, param3: boolean) => void;
}

class Test<T> extends React.Component<TestProps<T>> {
    public static propTypes = {
        onChange: PropTypes.func
    };
}

const el: JSX.Element = <Test onChange={(p1, p2, p3) => console.log(p1, p2, p3)} />;

export default Test;
```

The `onChange` attribute of `Test` component should be in `((param1: string, param2: number, param3: boolean) => void) | undefined` type like this:

![image](https://user-images.githubusercontent.com/28924863/67940585-f152fc00-fc0e-11e9-9448-d754e3d9fa21.png)

But when I pass a function into this attribute, I get a type error: `Parameter 'p1' implicitly has an 'any' type. ts(7006)`

![image](https://user-images.githubusercontent.com/28924863/67944136-bce33e00-fc16-11e9-804d-c0d13e3aad74.png)

When I modify `value?: T;` to `value?: T[];`, it works as expected:

![image](https://user-images.githubusercontent.com/28924863/67945162-33813b00-fc19-11e9-842a-dda68c8cc03f.png)

Remove `propTypes` also works:

![image](https://user-images.githubusercontent.com/28924863/67944998-de452980-fc18-11e9-983f-78ce72e342eb.png)

Remove generics also works:

![image](https://user-images.githubusercontent.com/28924863/67961905-53275c00-fc37-11e9-9b59-0dad12bc3c90.png)

Is this a problem with `@types/prop-types`?

### Environment

- `typescript@3.6.4`
- `react@16.11.0`
- `prop-types@15.7.2`
- `@types/prop-types@15.7.3`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
