### ISSUE TITLE
[@types/react-select] No possibility to use custom objects for options

### ISSUE THREAD

**Issue by hmeerlo** [DefinitelyTyped/DefinitelyTyped#40075]
- [x] I tried using the `@types/react-select` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @thchia @claasahl @jonfreedman @Methuselah96 

From what I understand from the react-select documentation (and implementation) I should be able to use any object as a base type for the options parameter. And then I could use getOptionLabel and getOptionValue to tell it what to use for label and value respectively. This is very handy for when you want to pass in data coming back from an API which you do not want to mutate and add a label and value property to (or which may already have such properties which you don't want to use). But if I use the type definitions from @types/react-select I am forced to pass in objects that have a label and value property (OptionType). Is this on purpose and if so, can I workaround this to support my use-case?

**Comment by jonfreedman** [comment]
You can use any option shape you like provided it's an object e.g. not a string, you just need to parameterize the Select, something like
```javascript
<Select<APIType> />
```

**Comment by hmeerlo** [comment]
@jonfreedman Sorry but that doesn't help, I'm already using that. The problem is here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8e0fa6fc55e715ccd9ee1656ba4ce2106067fbf9/types/react-select/src/Select.d.ts#L56

It explicitly states that the options must have a label and value prop, which isn't the case in the react-select code:

https://github.com/JedWatson/react-select/blob/54a4dfbfa70bc87d4cf09400ae07f1bfe0c6d606/packages/react-select/src/types.js#L4

**Comment by Methuselah96** [comment]
@hmeerlo No, `{ label: string; value: string}` is just the default value for the generic. `OptionTypeBase` can be found [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8e0fa6fc55e715ccd9ee1656ba4ce2106067fbf9/types/react-select/src/types.d.ts#L4-L6) and it can be any object just like in the Flow types.

**Comment by hmeerlo** [comment]
@Methuselah96 Thanks for your reply. My mistake, I'll re-add the type definition to my project and try to dig deeper why it complains about my types. I could not get it working correctly with typescript, although it works fine without the type definitions. I'll let you know the outcome.

**Comment by hmeerlo** [comment]
Apparently I refactored enough for it to work for me now. I can not tell what caused the problems for me, but it definitely wasn't a problem with the type definitions. So apologies for the disturbance.
