### ISSUE TITLE
[@types/codemirror] can't import submodules

### ISSUE THREAD

**Issue by ysulyma** [DefinitelyTyped/DefinitelyTyped#40103]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jacqt @basarat @mbilsing 

I am running into the error `TS2339: Property 'showHint' does not exist on type 'Editor'.`

Although this method is defined in `codemirror-showhint.d.ts`, there doesn't seem to be a way to access this file; TypeScript only picks up `index.d.ts`. Doing
```typescript
import "codemirror/codemirror-showhint";
```
in my code does not work. There is some discussion about importing submodules at https://github.com/microsoft/TypeScript/issues/8305, but I couldn't find a solution there.

**Comment by ficristo** [comment]
I can't reproduce. Tryed with this snippet of code:
```ts
import CodeMirror from "codemirror";
import "codemirror/addon/hint/show-hint";
import "codemirror/codemirror-showhint";

const cm = CodeMirror(document.body);

const hintFn: CodeMirror.HintFunction = (cm) => {
    return {
        from: {ch:0, line:1},
        to: {ch:0, line:1},
        list: []
    }
};

const hintOptions: CodeMirror.ShowHintOptions = {
    completeSingle: false,
    hint: hintFn
};

cm.showHint(hintOptions);
```

**Comment by webistomin** [comment]
> * [x]  I tried using the `@types/xxxx` package and had problems.
> * [x]  I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
> * [x]  I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
> * [x]  [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
>   
>   * Authors: @jacqt @basarat @mbilsing
> 
> I am running into the error `TS2339: Property 'showHint' does not exist on type 'Editor'.`
> 
> Although this method is defined in `codemirror-showhint.d.ts`, there doesn't seem to be a way to access this file; TypeScript only picks up `index.d.ts`. Doing
> 
> ```ts
> import "codemirror/codemirror-showhint";
> ```
> 
> in my code does not work. There is some discussion about importing submodules at [microsoft/TypeScript#8305](https://github.com/microsoft/TypeScript/issues/8305), but I couldn't find a solution there.

I have same error. How did you solve?😊

**Comment by SCWR** [comment]
```js
import "codemirror/codemirror-showhint";
```
It work for me.
