### ISSUE TITLE
mongodb typings for AggregationCursor incompatible with 3.3 driver

### ISSUE THREAD

**Issue by perbergland** [DefinitelyTyped/DefinitelyTyped#40125]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mongodb` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT
@alanmarcell
@bitjson
@dante-101
@mcortesi
@EnricoPicci
@AJCStriker
@julien-c
@daprahamian
@denys-bushulyak
@BastienAr
@sindbach
@geraldinelemeur
@jishi
@various89
@angela-1
@lirbank
@hector7
@floric
@erikc5000
@Manc
@jloveridge
@ranguna
@HosseinAgha
@albertossilva

If you do not mention the authors the issue will be ignored.

I tried using the latest mongodb driver (3.3.8) with the latest typings (3.3.1) but they seem to not be compatible when it comes to at least one method on the AggregationCursor returned from aggregate.

Specifically, the deprecated [each method](http://mongodb.github.io/node-mongodb-native/3.3/api/AggregationCursor.html#each) does not work at all but replacing it with the new forEach does (forEach is missing from typings).

Given
```
  const referencesCursor = dbo
    .collection("candidate")
    .aggregate([
      { $unwind: "$reference" },
      { $replaceRoot: { newRoot: "$reference" } },
      { $match: { answers: { $exists: true } } }
    ]);
```

this does not work - nothing gets executed
```
await referencesCursor.each(item=>...)
```

but this does:
```
await (referencesCursor as any).forEach(item=>...)
```

So to me it seems that "each" is not only deprecated now but even non-functional

**Comment by CaselIT** [comment]
You are welcome to add the `forEach` typing if you want.
