### ISSUE TITLE
[@types/lodash]: fromPairs() does not support pairs that are readonly arrays/tuples

### ISSUE THREAD

**Issue by UselessPickles** [DefinitelyTyped/DefinitelyTyped#40134]
`fromPairs()` does not support pairs that are readonly arrays/tuples.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @aj-r 

The current signature of `fromPairs` is:
```ts
        fromPairs<T>(
            pairs: List<[PropertyName, T]> | null | undefined
        ): Dictionary<T>;

        fromPairs(
            pairs: List<any[]> | null | undefined
        ): Dictionary<any>;
```

In both signatures, the type inside `List<>` is NOT readonly. This means that I get a compiler error if I try to use `fromPairs()` on a list of readonly pairs (tuples or arrays).

I expect that lodash does not actually depend on being able to mutate the pairs, and it should be safe to pass in readonly pairs. Therefore the types should should be something like `List<readonly [PropertyName, T]>` and `List<readonly any[]>`

I would go ahead and create a PR for this change, except that that correct support for readonly arrays and tuples (and the `readonly` keyword) is newer in TypeScript than the earliest supported TypeScript version of these types (2.8, according to `index.d.ts`). This could be partially mitigated by using `Readonly<>` instead of the `readonly` keyword. This might be "good enough", but I know there were some versions of TypeScript where `Readonly<>` applied to a tuple type would produce awkward results (don't remember the details).

So I have instead created this issue as a conversation starter to get suggestions on how to properly update the signatures of `fromPairs` to support readonly pairs without breaking types for earlier versions of TypeScript.

Also, I tried to test using `Readonly<>` but cannot test the types locally due to this error (this error occurs on a freshly synced project for me, running `npm run lint lodash`, even before I make any changes):

```
The 'use-default-type-parameter' rule threw an error in '/Users/jlau/Development/github/UselessPickles/DefinitelyTyped/types/lodash/lodash-tests.ts':
TypeError: Cannot read property 'default' of undefined
    at checkArgsAndParameters (/Users/jlau/Development/github/UselessPickles/DefinitelyTyped/node_modules/tslint/lib/rules/useDefaultTypeParameterRule.js:63:19)
    ...
```

**Comment by aj-r** [comment]
What about `ReadonlyArray<>`? I don't think it works for tuples but might work for the second overload.

I'm not sure what that error means.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
