### ISSUE TITLE
Proposal/Question: Adding ActiveX/Automation APIs, and their folder structure

### ISSUE THREAD

**Issue by zspitz** [DefinitelyTyped/DefinitelyTyped#4018]
I propose to add definition files for ActiveX objects accessible via Javascript -- MS Office applications, WIA, WMI and others. -- for use when targeting [WSH](https://msdn.microsoft.com/en-us/library/9bbdkx3k(v=vs.84).aspx) or [HTML Applications](https://msdn.microsoft.com/en-us/library/ms536473(v=vs.85).aspx). I have the following questions:

1. Does anyone else have use for this?
2. Is this within the scope of Definitely Typed? It depends on APIs external to Javascript in a particular environment.
3. The guidelines state that each library should be in a folder, with (in general) a single TypeScript definition file. How should this be applied to these libraries?
    * Each of these libraries should be in a separate root folder?
    * Some common prefix for all these libraries -- `ax.msword/microsoft.word.d.ts`, `ax.msexcel/microsoft.excel.d.ts`?
    * All the libraries should be in the same root folder?
    * Each library should be in its own subfolder of some root folder: `ax/msword/microsoft.word.d.ts`, `ax/msexcel/microsoft.excel d.ts`?

**Comment by vvakame** [comment]
1. I don't know. maybe no.
2. yes.
3. umm... please try with `All the libraries should be in the same root folder`. I'll review it when you send a PR.

**Comment by zspitz** [comment]
@vvakame Sorry about the delay; I've finally got around to a PR #9868.
