### ISSUE TITLE
[@types/node] incompatible with TS3.6.2

### ISSUE THREAD

**Issue by mprobst** [DefinitelyTyped/DefinitelyTyped#40237]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @galkin @SimonSchick and many others (and git blame doesn't load them all...)

The Node typings appear to be incompatible with tsc 3.6.4:

```
~/src/DefinitelyTyped/types/node $ tsc --version
Version 3.6.4

~/src/DefinitelyTyped/types/node $ tsc
../../../../.config/yarn/global/node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.

41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
        ~~~~~~~~~~~~~~

  index.d.ts:72:11
    72 interface IteratorResult<T> { }
                 ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.

index.d.ts:72:11 - error TS2300: Duplicate identifier 'IteratorResult'.

72 interface IteratorResult<T> { }
             ~~~~~~~~~~~~~~

  ../../../../.config/yarn/global/node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
            ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.

test/querystring.ts:47:11 - error TS2322: Type 'ParsedUrlQueryInput' is not assignable to type 'string | ParsedUrlQuery | null'.
  Type 'ParsedUrlQueryInput' is not assignable to type 'string'.

47     const query: string | null | querystring.ParsedUrlQuery = queryInput;
             ~~~~~

Found 3 errors.
```

**Comment by SimonSchick** [comment]
Run it in the ts3.2 folder.

**Comment by mprobst** [comment]
@SimonSchick that indeed passes, but I'm not sure I follow. Are you saying I need to use the `ts3.2/` files for TS3.2+? The comment in `index.d.ts` in the root suggests that that file is supposed to support TS3.2 as well? (or maybe that's a copy paste mistake)?

How do I put together a set of type definitions for TS3.6+? Are there docs on that anywhere?

**Comment by SimonSchick** [comment]
The ts3.2 file is usually automatically chosen when consuming the typings.
However it didn't error before so that's indeed new and _probably_ shouldn't happen.
cc @RyanCavanaugh

**Comment by mprobst** [comment]
Can you share a pointer to how that works? I have a job standard setup and
would like to reproduce.

**Comment by mprobst** [comment]
For whoever stumbles over this, the trick is the "typeVersions" attribute
in package.json that points to the subfolder.

**Comment by kika** [comment]
@mprobst You meant [typesVersions](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#version-selection-with-typesversions)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
