### ISSUE TITLE
[@types/vuelidate] return type for $touch and $reset should be void

### ISSUE THREAD

**Issue by Jexordexan** [DefinitelyTyped/DefinitelyTyped#40256]
Issue:

`$touch` and `$reset` are typed as returning `never`, which is incorrect. They DO return, but their return is `void`. 

`never` is meant for functions that run continuously or error out. Never docs: https://basarat.gitbooks.io/typescript/docs/types/never.html

- [x] I tried using the `@types/vuelidate` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @janesser @jubairsaidi

I will probably make a PR. But for posterity I want to have an issue to close.

**Comment by janesser** [comment]
alr8 point taken, will propose some PR?

**Comment by Jexordexan** [comment]
PR Posted for review

**Comment by Jexordexan** [comment]
And for what it's worth, @janesser, I'm not trying to be pedantic with types haha. I just ran into an issue where `never` was causing a strange error in my project and switching to `void` helped :)
