### ISSUE TITLE
[@types/koa] 2.0.49 depends on @types/koa-compose 3.2.5 which says koa has no Koa.Next

### ISSUE THREAD

**Issue by wisetc** [DefinitelyTyped/DefinitelyTyped#40265]
Some days later when I want to deploy my Koa application using docker, I found that it interrupted with error for Koa desn't have Koa.Next.

> node_modules/_@types_koa-compose@3.2.5@@types/koa-compose/index.d.ts:53:49 - error TS2694: Namespace '"/Users/myname/Work/codehub/my-node-project/node_modules/_@types_koa@
2.0.49@@types/koa/index.d.ts"' has no exported member 'Next'.
>
> 53     type Middleware<T> = (context: T, next: Koa.Next) => any;

I can run tsc locally  in success without docker using my current node_modules. But when I pull again from my repository and reinstall node_modules it fails at tsc process.

My `@types/koa` version is 2.0.49. I'm using Mac.

- [x] I tried using the `@types/koa` package 2.0.49 and had problems.
- [x] I am using version 3.5.3 of typescript.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DavidCai1993 @jkeylu @brikou @astashov

**Comment by wisetc** [comment]
Now I'm use `"@types/koa": "2.0.52"`, it is compatible with `"typescript": "3.5.3"`. And tsc configuration`"skipLibCheck": true` may help.

**Comment by sanjay-sridharan** [comment]
Thanks for the tip!  Updating @types/koa from 2.0.48 to 2.0.52 did the trick for me.
