### ISSUE TITLE
[@types/googlemaps] google.maps.Data.MouseEvent missing property

### ISSUE THREAD

**Issue by Gurran** [DefinitelyTyped/DefinitelyTyped#40328]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/googlemaps` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@cgwrench @Silver-Connection @nertzy @xaolas @mrmcnerd @martincostello @svenkreiss @bolatovumar @gauthierm @captain-igloo @demensky @life777 @simonhaenisch

google.maps.Data.MouseEvent is missing property
 ya: `MouseEvent`. 

![image](https://user-images.githubusercontent.com/42462633/68676443-56391b00-055a-11ea-8d3f-b64ae6f9098e.png)

Where `MouseEvent` is defined in [lib.dom.d.ts](https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L10726)

**Comment by demensky** [comment]
[Documentation] has no mentions of this property. Since you are seeing it in runtime and we are talking about JavaScript — it could be a minified private property necessary for internal use. It's a bad idea to add it to typings because it could change at any time — it's not in the public API according to the docs.

[Documentation]: https://developers.google.com/maps/documentation/javascript/reference/data#Data.MouseEvent

**Comment by demensky** [comment]
If you choose to rely upon this property, you can augment `@types` with your local typings override:

```ts
type NativeMouseEvent = MouseEvent;

declare namespace google.maps.Data {
    interface MouseEvent {
        ya: NativeMouseEvent;
    }
}
```

**Comment by Gurran** [comment]
@demensky 

I see. A bit annoying that the MouseEvent is forwarded without having it properly named (private). 
I understand why you might not want to add it to the typings. 

Here's to hoping Google adds is properly.

**Comment by Gurran** [comment]
@demensky 
Thanks for the quick response. 

Closing this issue.
