### ISSUE TITLE
[@types/ioredis] Missing commands

### ISSUE THREAD

**Issue by LosTigeros** [DefinitelyTyped/DefinitelyTyped#40324]
- [x] I tried using the `@types/ioredis` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @plantain-00 @chrisleck @aliarham11 @br8h @shaharmor

In `ioredis`, `zrangebylex()`, `zremrangebylex()` and `zrevrangebylex()` exist hovewer they don't exist in `@types/ioredis`.

Please create a pull request to fix it.

**Comment by plantain-00** [comment]
You can create a pull request to fix this.
