### ISSUE TITLE
[@types/ol] Can't set image in tileLoadFunction 

### ISSUE THREAD

**Issue by Peter-Optiway** [DefinitelyTyped/DefinitelyTyped#40349]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/ol` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @hanreev 

Hi I'm trying to use `tileLoadFunction` from `TileWMS` and `XYZ` and it has the following definition `LoadFunction = (p0: Tile, p1: string) => void;`

When looking at OpenLayer examples it says you should use `p0.getImage()` but Tile does not seem to contain a method named `getImage`?
Am i doing something wrong or is the definition of `LoadFunction` wrong?

After some research it seems like it should be `LoadFunction = (p0: ImageTile, p1: string) => void;`?

**Comment by hanreev** [comment]
@Peter-Optiway nothing wrong with the definition. See OpenLayers documentation, `ol/Tile.LoadFunction` takes 2 arguments, `ol/Tile` and `string`.
Just cast the first argument to `ol/ImageTile` if you need to load image tile. Remember, `ol/VectorTile` also extends `ol/Tile` and does not have `getImage` method.

Example:
```ts
import { ImageTile } from 'ol';
import { LoadFunction } from 'ol/Tile';

function tileLoadFunction(tile: ImageTile, src: string): LoadFunction {
    const image = tile.getImage();
    // your code here
}
```

**Comment by Peter-Optiway** [comment]
I got a error when just changing Tile to ImageTile, but i managed to get it working with the following code:
```
if (!(imageTile instanceof ImageTile)) {
    throw new Error('imageTile must be of type ImageTile');
}
```
