### ISSUE TITLE
[@types/mongoose] Missing arrayFilters option in update operations

### ISSUE THREAD

**Issue by numToStr** [DefinitelyTyped/DefinitelyTyped#40347]
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x]  Mention the authors (see Definitions by: in index.d.ts) so they can respond.
        Authors: 
            @horiuchi
            @ToucheSir
            @richarddd
            @orblazer 

Reference: https://docs.mongodb.com/manual/reference/operator/update/positional-filtered

In `mongoose`, update operations can take `arrayFilters` option but there is no type definition available for this.

**Comment by svmn** [comment]
Seems that `findOneAndUpdate()` method still not supports `arrayFilters` option.

**Comment by stephane-ruhlmann** [comment]
@svmn It was only added to `Mode.update`, will open a PR for `findOneAndUpdate()` cause I need it too.

Out of curiosity, how are you working around this?

**Comment by stephane-ruhlmann** [comment]
PR opened : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43062
