### ISSUE TITLE
[styled-components] Problems with `as` after 4.1.22

### ISSUE THREAD

**Issue by xumix** [DefinitelyTyped/DefinitelyTyped#40358]
Have problems with `@types/styled-components`@4.1.22( also 4.4.0) and `semantic-ui-react@0.88.1` and tsc 3.7.2

```
import styled from "styled-components/macro";
import { Header } from "semantic-ui-react";
export const RegistrationLink = styled(Header)`
  color: #000 !important;
  font-weight: 400 !important;
  display: block;
  cursor: pointer;
`;
```
`<RegistrationLink as="a" textAlign="center" size="tiny" onClick={this.goToRegister} />`

Getting this error:
```
No overload matches this call.
  Overload 1 of 2, '(props: Pick<Pick<PropsWithChildren<HeaderProps>, ReactText> & Partial<Pick<PropsWithChildren<HeaderProps>, never>>, ReactText> & { ...; } & { ...; }): ReactElement<...>', gave the following error.
    Type 'string' is not assignable to type 'undefined'.
  Overload 2 of 2, '(props: StyledComponentPropsWithAs<"a", any, {}, never>): ReactElement<StyledComponentPropsWithAs<"a", any, {}, never>, string | ... 1 more ... | (new (props: any) => Component<...>)>', gave the following error.
    Type '{ children: any; as: "a"; textAlign: string; size: string; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & Pick<Pick<Pick<DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>, "children" | ... 261 more ... | "referrerPolicy"> & { ...; }, "children" | ... 262 more ... | "referrerPolicy"> & Partial<...>, "children" | ... 262 more ... | "referrerPolicy"> & { ...; } & { ...; }'.
      Property 'textAlign' does not exist on type 'IntrinsicAttributes & Pick<Pick<Pick<DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>, "children" | ... 261 more ... | "referrerPolicy"> & { ...; }, "children" | ... 262 more ... | "referrerPolicy"> & Partial<...>, "children" | ... 262 more ... | "referrerPolicy"> & { ...; } & { ...; }'.  TS2769
```

@surgeboris @sandersn @Jessidhia @smockle

**Comment by bdelaforest** [comment]
@Jessidhia looking at [those lines of code](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-components/ts3.7/index.d.ts#L159-L161), it seems that when `as` is present, the original component props are not kept. 😕

**Comment by fabb** [comment]
Same here, and additionally I get this error: `Type instantiation is excessively deep and possibly infinite.`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
