### ISSUE TITLE
@types/jasmine - jasmine.Matchers methods missing

### ISSUE THREAD

**Issue by kdshop** [DefinitelyTyped/DefinitelyTyped#40357]
There are no types for following methods

- [nothing](https://jasmine.github.io/api/edge/matchers.html#nothing)
- [toBeInstanceOf](https://jasmine.github.io/api/edge/matchers.html#toBeInstanceOf)
- [toBeFalse](https://jasmine.github.io/api/edge/matchers.html#toBeFalse)
- [toBeTrue](https://jasmine.github.io/api/edge/matchers.html#toBeTrue)

@borisyankov

**Comment by peterblazejewicz** [comment]
This seems to be fixed now, thx!

**Comment by kdshop** [comment]
Thanks! Much appreciated!!
