### ISSUE TITLE
[@types/node] Process interface overloads "on" EventEmitter types.

### ISSUE THREAD

**Issue by alexander-wu** [DefinitelyTyped/DefinitelyTyped#40356]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- Authors:
@SimonSchick 

Node version: 10.x

When I emit custom event on process like this:

`process.on("my-custom-event", () => {})`

Typescript starts to complain: `Argument of type '"my-custom-event"' is not assignable to parameter of type 'Signals'`

The process object is an instance of EventEmitter according to the [Node.js documentation](https://nodejs.org/api/process.html#process_process). [Here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v10/globals.d.ts#L828-L839) you overload [EventEmitter 'on' method type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v10/globals.d.ts#L545). So according to the [Process](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v10/globals.d.ts#L703) interface you can not subscribe on its custom events, which is not correct. Or am I missing something?

**Comment by SimonSchick** [comment]
This code predates my contributions so I'm not super.

It's very uncommon that developers attempt to broadcast their own events using existing event emitters which is probably why this isn't supported.

_However_ it seems that most event emitter definitions do have the wildcard `string` variants, just process and a few others don't have it.

I'd personally advise against using `process` for broadcasting custom events but you are free to create a PR and add the missing overload(s).
