### ISSUE TITLE
@types/ioredis arg of echo has problem

### ISSUE THREAD

**Issue by hydemo** [DefinitelyTyped/DefinitelyTyped#40412]
the example of ioredis use by lua

var redis = new Redis();
 
// This will define a command echo:
redis.defineCommand("echo", {
  numberOfKeys: 2,
  lua: "return {KEYS[1],KEYS[2],ARGV[1],ARGV[2]}"
});
 
// Now `echo` can be used just like any other ordinary command,
// and ioredis will try to use `EVALSHA` internally when possible for better performance.
redis.echo("k1", "k2", "a1", "a2", function(err, result) {
  // result === ['k1', 'k2', 'a1', 'a2']
});

when I use  redis.echo("k1", "k2", "a1", "a2") it return the number of params of echo is 2 but get 4,

**Comment by SimonSchick** [comment]
This cannot be fixed, typings are static and you are overriding commands runtime/dynamically (which you really shouldn't be doing).

I'm also not sure if the issue you are talking about is even with the typings.

**Comment by ClaudiuCeia** [comment]
Sorry to bump this. I think OP got the example [from the official ioredis documentation](https://github.com/luin/ioredis#transparent-key-prefixing)

[echo](https://redis.io/commands/echo) is already a Redis command, but if the built-in commands can be overridden, would it make sense to define an overloaded type for all built-ins to allow users to specify the type? I'm not quite sure how best to do that at the moment though. 

FWIW, specifically for Lua scripts, what I'm currently doing is something like the below. I also don't redefine Redis built-in commands by convention so I'm side-stepping the issue described here by default.

```ts
type RedisClientOptions = {
  withLuaCommands: boolean;
}

// No Lua scripts
interface RedisClassic extends Redis.Redis {
  readonly kind: "classic";
}

// With Lua scripts
interface RedisWithLuaCommands extends Redis.Redis {
  readonly kind: "with_lua";
  // This is an example custom command, defined with 
  // registerRedisCommand below
  isAlive(): Promise<string>;
}

export type RedisClient = RedisClassic | RedisWithLuaCommands;

const registerRedisCommands = (client: Redis.Redis) => {
  // use client.defineCommand here
}

const createRedisClient = ({
  withLuaCommands,
}: RedisClientOptions) => {
  const client = new Redis({
    port: parseInt(process.env.REDIS_PORT!, 10),
    host: process.env.REDIS_HOST,
  }) as any;

  if (withLuaCommands) {
    registerRedisCommands(client as Redis.Redis);
    client.kind = "with_lua";
    return <RedisWithLuaCommands>client;
  }

  client.kind = "classic";
  return <RedisClassic>client;
};
```

Then I can just:

```ts
// ...
  const redisClient = createRedisClient({
    withLuaCommands: true,
  });

  // you get autocomplete and type checking here
  if (redisClient.kind === "with_lua") {
    // Do something if custom commands
    return redisClient.isAlive();
  }
// ...
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
