### ISSUE TITLE
[@types/react-native] Animated components are defined as any

### ISSUE THREAD

**Issue by Aure77** [DefinitelyTyped/DefinitelyTyped#40424]
**Animated.*** are defined as "_any_".
So I can't use `Animated.FlatList` props because of this :
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/dc156f32b209433ddb998c44a3c730c584c881e7/types/react-native/index.d.ts#L8385-L8390

- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:  @alloy, @huhuanming, @iRoachie, @Skn0tt, @timwangdev, @kamal, @alexdunne, @swissmanu, @a-tarasyuk, @mvdam, @Esemesek, @mrnickel, @souvik-ghosh, @nossbigg, @saranshkataria, @franzmoro, @tykus160, @jakebloom, @ceyhun, @mcmar

**Comment by zusinShinpei** [comment]
#41939
