### ISSUE TITLE
[`bunyan-format`] Incompatible type signature

### ISSUE THREAD

**Issue by MaximDevoir** [DefinitelyTyped/DefinitelyTyped#40444]
After upgrading `bunyan-format` to `0.2.1`, we started receiving an incompatible type signature error:

![bunyan-format](https://user-images.githubusercontent.com/10104630/69013922-e8199d00-0939-11ea-9aa1-df25444637e1.png)

`bunyan-format` returns the `stream.Writable` type:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cdf01cf33d2db0f25558413ce3ba98b472c4dd07/types/node/globals.d.ts#L640-L647

Meanwhile, `bunyan`'s `stream` option expects `NodeJS.WritableStream` from here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cdf01cf33d2db0f25558413ce3ba98b472c4dd07/types/bunyan/index.d.ts#L240

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cdf01cf33d2db0f25558413ce3ba98b472c4dd07/types/node/stream.d.ts#L119-L125

/cc @dex4er @Ashpabb

**Comment by MaximDevoir** [comment]
This may also be a `bunyan` error. I noticed that `bunyan`'s `stream` option expects `NodeJS.WritableStream`, whereas `bunyan`'s `streams` option also accepts `Stream`.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cdf01cf33d2db0f25558413ce3ba98b472c4dd07/types/bunyan/index.d.ts#L236-L244


When I changed Bunyan's [Logger Options](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cdf01cf33d2db0f25558413ce3ba98b472c4dd07/types/bunyan/index.d.ts#L236) to accept `Stream`

```diff
-     stream?: NodeJS.WritableStream; 
+     stream?: NodeJS.WritableStream | Stream; 
```

everything worked fine. Maybe Bunyan is missing something.

I'm not familiar with the source code of Bunyan or Bunyan-Format, so adding `Stream` may be incorrect.

----------------

...just thought I'd throw that out there

**Comment by dex4er** [comment]
I'm surprised that you see it after upgrade of bunyan-format. #40257 brought additional function declaration and it should not be related to this bug.

I agree that `bunyan` should accept `WriteStream` instead `NodeJS.WritableStream ` as a parameter and I'm going to do PR for this change.

**Comment by dex4er** [comment]
Actually there is a problem with this this ambient merging of class and function that made this class incompatible with `Writable`. Maybe this is a bug in Typescript itself. Probably it is better to switch to older syntax as far as this "innocent" change made `bunyan-format` broken.

**Comment by Ashpabb** [comment]
Noted - working on a more low level implementation now
