### ISSUE TITLE
declare var global lodash screw up

### ISSUE THREAD

**Issue by pocesar** [DefinitelyTyped/DefinitelyTyped#4046]
Well, I spent like 2 hours trying to find why my node code stopped working after refactoring, I split the code through many files. I use lodash in node.js and in the browser (but through browserify). Express was "silently" failing for me for one route specifically, even though no "code error" pre-typescript compile was being thrown. I had this inside one route:

``` typescript
    app.post('/:hash', function (req: IHashRequest, res: express.Response) {
        if (req.usuario.started && !_.isEmpty(req.body) && !req.usuario.done) {
         // ...
```

Typescript was compiling the code without warning me that `_` was undefined. I had no `import _ = require('lodash');` on top of this file, and it was considering valid code anyway because the lodash file has a global declaration for `_`:

``` typescript
declare var _: _.LoDashStatic;
```

it shouldn't. node won't add globals unless you ask it for it. so it should be left out for node counterparts. or defined manually by the person is using typescript for the browser.
some global declare like this can really hog down progress, since you are trying to find bugs that the preprocessor should be warning you about.

**Comment by maritz** [comment]
+1 this just bit me as well.
