### ISSUE TITLE
[@types/node] the module url has wrong types

### ISSUE THREAD

**Issue by maleeb** [DefinitelyTyped/DefinitelyTyped#40485]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @OliverJAsh, @ExE-Boss, @PranavSenthilnathan

**types/node/url.d.ts**
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/a3ef14ec5425901074c627f737e5f8be2e4c6fff#diff-da6972351b4c65de52b999c275c59551R27

The types in `url` interface should not be null. For example `parse()` is normally returning with `string | undefined` and not with `string | null` unless this is breaking change and you should bump the version.

**Comment by OliverJAsh** [comment]
> The types in `url` interface should not be null.

```sh-session
$ node
Welcome to Node.js v12.8.1.
Type ".help" for more information.
> url.parse('')
Url {
  protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: null,
  query: null,
  pathname: null,
  path: null,
  href: ''
}
```

**Comment by maleeb** [comment]
@OliverJAsh my fault, checked the wrong response
