### ISSUE TITLE
Definition Request: Sinon-as-promised

### ISSUE THREAD

**Issue by demisx** [DefinitelyTyped/DefinitelyTyped#4051]
GitHub Repo: https://github.com/bendrucker/sinon-as-promised
Script: https://github.com/bendrucker/sinon-as-promised/blob/master/src/index.js

It's a tiny, but very useful Javascript promise testing library. Thanks!

**Comment by demisx** [comment]
@bendrucker Ben, what are your thoughts about this? So far, this is the only library in my tests suite that doesn't have definitions in this repo leading to all soft of warnings in IDE.

**Comment by bendrucker** [comment]
I've never touched TypeScript nor done any definitions. But I'm happy to do it if you can give me:

1. A good post about how to write definitions
2. Instructions on where to put them and anything else I need to do so the TS compiler picks them up.

**Comment by demisx** [comment]
@bendrucker I also don't have any experience writing these yet, but they appear to be similar to header files in C. The beauty of these is that you don't have to use TypeScript at all in order to help your IDE recognize and auto-complete library properties in JavaScript files. Leads to better refactoring too.

The official guidelines on creating definition files for this repo is here: http://definitelytyped.org/guides/creating.html

Here is an example of definitions file (+ 1 test) for similar libs:
1. `Sinon-chai` 
  https://github.com/jt000/DefinitelyTyped/tree/master/sinon-chai

1. `Chai-as-promised`
https://github.com/jt000/DefinitelyTyped/tree/master/chai-as-promised

Hope this helps.

**Comment by bendrucker** [comment]
sinon-as-promised now has basically no code, since it uses https://github.com/bendrucker/create-thenable. I don't know how to handle this properly. The return value is guaranteed to have `then`, `catch`, and `finally` but it could have a ton more methods and it could have just those. 

Happy to help on a PR but I've changed my mind about working on this myself.

**Comment by JoshuaKGoldberg** [comment]
I can take a stab at this. :)

**Comment by JoshuaKGoldberg** [comment]
Oh, someone already did! https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/sinon-as-promised

This issue should be closed.

**Comment by rationull** [comment]
Also, as of sinon 2.0 promises are natively supported without needing to pull in sinon-as-promised. The sinon type definitions haven't been updated yet for 2.0 though. I just filed Issue #15320 covering the required updated.
