### ISSUE TITLE
React.ReactNode and React.ReactElement are Redundant.RedundantNames

### ISSUE THREAD

**Issue by jedwards1211** [DefinitelyTyped/DefinitelyTyped#40549]
React.Node and React.Element, like in Flow, would be much better.

How did these redundant names happen anyway?

**Comment by maclockard** [comment]
I would guess its to avoid accidental conflict with the top level DOM types `Node` and `Element`. If the redundancy bothers you, you can always import the types like so:
```
import React, {ReactNode} from "react";
```

To change at this point though would be a pretty massive breaking change considering how many other libs and people's code depend on the type. I would be very surprised if it ever changed.

**Comment by jedwards1211** [comment]
that's true, coming from Flow I was very used to relying solely on `import * as React from 'react'`
