### ISSUE TITLE
[@types/styled-components] `as` prop error

### ISSUE THREAD

**Issue by mario-jerkovic** [DefinitelyTyped/DefinitelyTyped#40650]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek, @Igmat, @Lavoaster, @Jessidhia, @JKillian, @eps1lon, @flavordaaave and @wagerfield 

I am using: 
- `"@types/react": "^16.9.13`
- `"@types/styled-components": "^4.4.0"`
- `"typescript": "^3.7.2"`

I am trying to set `as` property on my component which renders `styled-component`:
```javascript

type TypographyProps<T> = React.HTMLProps<T> & {
    // ...
    component?: keyof JSX.IntrinsicElements,
    // ...
}

export const Typography = <T extends any = HTMLDivElement>(props: TypographyProps<T>) => {
    const {
        children,
        className,
        component = 'div', // <- default component type
        fontFamily = TypographyFontFamily.primary,
        gutterBottom = false,
        paragraph = false,
        underline = false,
        underlineAlignment = UnderlineAlignment.bottom,
        variant,
    } = props

    return (
        <TypographyRoot
            as={component}
            className={className}
            fontFamily={fontFamily}
            gutterBottom={gutterBottom}
            paragraph={paragraph}
            underline={underline}
            underlineAlignment={underlineAlignment}
            variant={variant}
        >
            {children}
        </TypographyRoot >
    )
}

```
The issue is that typescript throw an error:
`Type instantiation is excessively deep and possibly infinite.`

**Comment by osdiab** [comment]
I am getting this as well, it's making it hard to use styled components at all

**Comment by osdiab** [comment]
Additionally whenever I extend a base element's props like so:

```ts
const MyInput: React.FC<React.HTMLProps<HTMLInputElement>> = props => {
  return <input {...props} />;
}
```

Then `as` typing also causes an error, saying that `string | undefined` doesn't match `undefined` for the type of the `as` prop. `as` prop is very broken right now

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
