### ISSUE TITLE
Handlebars 2 and 3 definition request

### ISSUE THREAD

**Issue by Vadorequest** [DefinitelyTyped/DefinitelyTyped#4077]
I'm looking for the version of Handlebar 2 and/or 3. Only the 1 is available yet.

http://handlebarsjs.com/

**Comment by BrkCoder** [comment]
@Vadorequest is it still relevant, I would like to help and add types definition asap. :)

**Comment by Vadorequest** [comment]
@BrkCoder I don't use handlebars nowadays and I don't know if that's still relevant.

**Comment by BrkCoder** [comment]
ok 👍

**Comment by Semigradsky** [comment]
@BrkCoder @Vadorequest The typings are provided directly by project:
https://github.com/handlebars-lang/handlebars.js/blob/master/types/index.d.ts

So this issue can be closed

**Comment by Vadorequest** [comment]
Thanks for the follow-up. Closing then!
