### ISSUE TITLE
@types/@xstyled__system has no rpxTransformers

### ISSUE THREAD

**Issue by wa4-fearless-otter** [DefinitelyTyped/DefinitelyTyped#40783]
I tried using the `@types/@xstyled__system` package and had problems.
It had no [rpxTransformers named export](https://www.smooth-code.com/open-source/xstyled/docs/transformers/#use-rem-instead-of-px).

@stevejay please add this. I would really appreciate it.

**Comment by stevejay** [comment]
PR submitted: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40788

**Comment by stevejay** [comment]
PR has been merged.

**Comment by wa4-fearless-otter** [comment]
Thank you
