### ISSUE TITLE
[@types/styled-components] Prop types coalescing

### ISSUE THREAD

**Issue by roikoren755** [DefinitelyTyped/DefinitelyTyped#40795]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @Lavoaster @Jessidhia  @JKillian @eps1lon @flavordaaave @wagerfield 

If you do not mention the authors the issue will be ignored.

Consider the following example:
```
interface IStyledDivProps {
  textColor: string;
}

const StyledDiv = styled.div.attrs(({ textColor }) => ({ textColor }))``;

const Hello: FunctionComponent<IStyledDivProps> = ({ textColor }) => <StyledDiv textColor={textColor}>Hello</StyledDiv>;
```

If left like this, TypeScript complains about property textColor not existing on `Pick<DetailedHTMLProps...`, at the `styled.div.attrs` line;

If I add type information to that line, 
```
const StyledDiv = styled.div.attrs<IStyledDivProps>(({ textColor }) => ({ textColor }))``;
```

TypeScript will now complain about the same thing, this time in the last line of the example, the Hello function component, and to resolve this I need to add type information after the call to `.attrs`, like such:
```
const StyledDiv = styled.div.attrs<IStyledDivProps>(({ textColor }) => ({ textColor }))<IStyledDivProps>``;
```

Is there any way to merge the two types passed to the generic functions? So that the first fix will work, and I would only have to add type annotations in one place in this example?

I'm using `styled-components@4.4.1`, `@types/styled-components@4.4.0` and `typescript@3.7.2`

**Comment by Lazyuki** [comment]
You can do 
```tsx
const StyledDiv = styled.div.attrs(({ textColor }: IStyledDivProps) => ({ textColor }))``;
```

**Comment by roikoren755** [comment]
> You can do
> 
> ```tsx
> const StyledDiv = styled.div.attrs(({ textColor }: IStyledDivProps) => ({ textColor }))``;
> ```

This works specifically for `textColor`, but not if I rename it `something`, for example.

**Comment by Lazyuki** [comment]
Sorry, not sure I follow what you mean. This [playground](https://www.typescriptlang.org/play/index.html?jsx=2&ts=3.7-Beta#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoUSWOAZxgE8AbJAEzm1wPubYFo0uSADskwmLTLlK4pFEzokcAJIBlRi1YARYADcACjjC04Ab3Jw6uJDAAWwYQHMAXHRhQHjigF9pg4fRw6rzaenAAvG4hAHSsetEoMO60ABQpplYgNvZOcN6uahpsOgZGtACUEQB8cOmZ2Z555eUABi0U5P6BABJITEwQrsjoMNEAYgCuwhjAEMIAwkJzYjAAPIUhJYYQxjWRdbTWdo3eleE1q8GaJfXHTuGmh1l3jt5Vvf0QqwD0V8V6VQoQA) compiles just fine

**Comment by roikoren755** [comment]
> Sorry, not sure I follow what you mean. This [playground](https://www.typescriptlang.org/play/index.html?jsx=2&ts=3.7-Beta#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoUSWOAZxgE8AbJAEzm1wPubYFo0uSADskwmLTLlK4pFEzokcAJIBlRi1YARYADcACjjC04Ab3Jw6uJDAAWwYQHMAXHRhQHjigF9pg4fRw6rzaenAAvG4hAHSsetEoMO60ABQpplYgNvZOcN6uahpsOgZGtACUEQB8cOmZ2Z555eUABi0U5P6BABJITEwQrsjoMNEAYgCuwhjAEMIAwkJzYjAAPIUhJYYQxjWRdbTWdo3eleE1q8GaJfXHTuGmh1l3jt5Vvf0QqwD0V8V6VQoQA) compiles just fine

This [sandbox](https://codesandbox.io/s/typescript-playground-export-q6d3l?fontsize=14&hidenavigation=1&theme=dark) also compiles correctly, but does not provide the wanted results. In this example, the `something` prop should be required, and the declaration of the `Hello` function component should fail the compilation. Is there a way to achieve that?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
