### ISSUE TITLE
Function overloads for 'http.listen()' (aka, net.listen()) are too broad.

### ISSUE THREAD

**Issue by systemmonkey42** [DefinitelyTyped/DefinitelyTyped#40818]
When importing `http`, and attempting to call `listen()` on the result of `createServer()`, error checking does not work properly.

The following signatures are known for `net.listen` (inherited by `http`)
```js

listen(port?: number | undefined, hostname?: string | undefined, backlog?: number | undefined, listeningListener?: (() => void) | undefined): this
listen(port?: number | undefined, hostname?: string | undefined, listeningListener?: (() => void) | undefined): this
listen(port?: number | undefined, backlog?: number | undefined, listeningListener?: (() => void) | undefined): this
listen(port?: number | undefined, listeningListener?: (() => void) | undefined): this
listen(path: string, backlog?: number | undefined, listeningListener?: (() => void) | undefined): this
listen(path: string, listeningListener?: (() => void) | undefined): this
listen(options: ListenOptions, listeningListener?: (() => void) | undefined): this
listen(handle: any, backlog?: number | undefined, listeningListener?: (() => void) | undefined): this
listen(handle: any, listeningListener?: (() => void) | undefined): this
```

The presense of
```js
listen(handle: any, listeningListener?: (() => void) | undefined): this
```

causes
```js
listen(options: ListenOptions, listeningListener?: (() => void) | undefined): this
```
to be ignored if the supplied parameters doesn't exactly match `ListenOptions`

Eg, 
```js
/** @type {net.ListenOptions} */
let opts = {
    port: "2000"
}

server.listen(opts, () => {});
```
This is an error, because 'opts' is explicitly a "ListenOptions", but 'port' is not a number.

However
```js
let opts = {
    port: "2000"
}

server.listen(opts, () => {});
```

This succeeds, because 'opts' is now treated as type 'any', matching the later signature.

Is it possible to remove 'any' from the signature to allow malformed `ListenOptions` to be detected?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
