### ISSUE TITLE
jquery.d.ts missing triggerHandler(event)

### ISSUE THREAD

**Issue by tkrotoff** [DefinitelyTyped/DefinitelyTyped#4094]
There are 2 ways to call `triggerHandler`:

- Already covered:
```
.triggerHandler('focus')
```

- Not covered:
```
el.triggerHandler({
  type: 'change',
  target: {
    files: [
      ...
    ]
  }
});
```

I discovered this via https://github.com/angular/angular.js/issues/8469 and the example provided: http://plnkr.co/edit/hs4EUMhP0NBWM6RmvuQq?p=preview

FYI AngularJS's jqLite (small lib that implements parts of jQuery) now (>= v1.3.0-beta.18) also supports the second way to call `triggerHandler`.

**Comment by vvakame** [comment]
@tkrotoff please send a PR. I'll review it.
