### ISSUE TITLE
[@types/react-overlays] Can't resolve 'react-overlays/AutoAffix'

### ISSUE THREAD

**Issue by larsnystrom** [DefinitelyTyped/DefinitelyTyped#40940]
- [X] I tried using the `@types/react-overlays` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aaronbeall, @vitosamson, @aarondancer

The following piece of code:

    import AutoAffix from 'react-overlays/AutoAffix';

Results in the error

> Module not found: Error: Can't resolve 'react-overlays/AutoAffix' in ...

Changing the code to

    import { AutoAffix } from 'react-overlays';

solves the issue. So I guess it's just a missing export in the `@types/react-overlays` package?

I should mention I'm using `react-overlays@1.2.0` and `@types/react-overlays@1.1.3`.

**Comment by peterblazejewicz** [comment]
One needs `esModuleInterop` option in `tsconfig.json` to support that notation. As this are CommonJS, hence:
```ts
import AutoAffix = require("react-overlays/lib/AutoAffix");
```

**Comment by larsnystrom** [comment]
@peterblazejewicz I have `esModuleInterop` set to `true`, that's not the problem here. The problem is that the typings say that the component is located at `react-overlays/lib/AutoAffix`, when in reality it is located at `react-overlays/AutoAffix`. It's a bug in the types declaration.

Also, I don't think you can mix `import` with `require` like you do in your example.

**Comment by NicoleRauch** [comment]
I also had issues with react-overlays and TypeScript, and in the process I discovered that the react-overlays module already contains the TypeScript type declarations. I removed @types/react-overlays and my problems were gone.

(I know, I am very late to the party 😅 But I thought maybe my comment at least helps somebody else...)
