### ISSUE TITLE
[@types/nodemailer] Support promises.

### ISSUE THREAD

**Issue by tianhuil** [DefinitelyTyped/DefinitelyTyped#40952]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/nodemailer` package and had problems
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] Potentially related issues: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/32305, https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16927
- [X] Authors: @andy-ms, @bioball, @rogierschouten, @dex4er, 

@andy-ms: thanks for upgrading NodeMailer to 4.*  Currently on version 6.2.2.  Any chance we could get the type definitions upgraded?

In particular, the type definitions do not support promises
```ts
const composer = new MailComposer({...})
const buffer = await composer.compile().build() // error about a missing callback
```
However, NodeMailer's javascirpt does support promises (see https://github.com/nodemailer/nodemailer/issues/929 and https://github.com/nodemailer/nodemailer/blob/master/examples/mailcomposer.js).

My current workaround is this
```ts
const composer = new MailComposer({...})
const buffer = await (composer.compile().build as () => Promise<Buffer>)()
```
but I would love to get this added to the definitions.

**Comment by dex4er** [comment]
https://github.com/nodemailer/nodemailer/commit/e56a84791da509664f632f44af316fc2247f005e says it was changed in v6.4.1 and I'm going to update the typings and include this variant of the `build` method.
