### ISSUE TITLE
Error with @types/webgl2 vs. built-in WebGL in tsc 3.7

### ISSUE THREAD

**Issue by garyo** [DefinitelyTyped/DefinitelyTyped#40995]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nkemnitz , @karhu 

I have a project with @types/webgl2@0.0.5 (latest version) and typescript 3.7, and get the errors below. Removing `@types/webgl2` from my package.json makes it work OK for me. Is this package now obsolete due to the built-in WebGL types in typescript 3.6/3.7? Or is there a true incompatibility (i.e. one is wrong)?

(see https://github.com/microsoft/TypeScript/issues/33672 where @RyanCavanaugh says "Someone will need to send a PR to DefinitelyTyped", so here I am.)

Errors:
```
$ tsc
node_modules/typescript/lib/lib.dom.d.ts:16482:11 - error TS2430: Interface 'WebGL2RenderingContext' incorrectly extends interface 'WebGL2RenderingContextBase'.
  Types of property 'clearBufferfv' are incompatible.
    Type '(buffer: number, drawbuffer: number, values: ArrayLike<number> | Float32Array, srcOffset?: number | undefined) => void' is not assignable to type '{ (buffer: number, drawbuffer: number, values: Float32List, srcOffset?: number | undefined): void; (buffer: number, drawbuffer: number, values: Iterable<number>, srcOffset?: number | undefined): void; }'.
      Types of parameters 'values' and 'values' are incompatible.
        Type 'Iterable<number>' is not assignable to type 'ArrayLike<number> | Float32Array'.
          Type 'Iterable<number>' is missing the following properties from type 'Float32Array': BYTES_PER_ELEMENT, buffer, byteLength, byteOffset, and 25 more.

16482 interface WebGL2RenderingContext extends WebGL2RenderingContextBase, WebGL2RenderingContextOverloads, WebGLRenderingContextBase {
                ~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
