### ISSUE TITLE
[@types/serve-static] Method signature refers to Express despite having support for vanilla IncomingMessage

### ISSUE THREAD

**Issue by vpzomtrrfrt** [DefinitelyTyped/DefinitelyTyped#40994]
- [x] I tried using the `@types/serve-static` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @urossmolnik @LinusU 

I'm trying to adopt TypeScript in a small server project, but the types for serve-static don't seem to be working.
```
TS2345: Argument of type 'IncomingMessage' is not assignable to parameter of type 'Request<ParamsDictionary, any, any>'.
```

I assume this is some express thing?

**Comment by peterblazejewicz** [comment]
try this:
```ts
npm i -D @types/node
npm i express
npm i -D @types/express
npm install serve-static
npm i -D @types/serve-static
```
your `tsconfig.json`:
```json
"types": ["node"], 
```
You need types for Node. If that helps, close issue.
hth

**Comment by vpzomtrrfrt** [comment]
Do I really have to install express? That's not great

**Comment by peterblazejewicz** [comment]
Sorry, maybe I misread the question. I've looked only into the type definition file, which refernces express. Are you using this types module in standalone usage, without Express? Like that one:
https://github.com/expressjs/serve-static#serve-files-with-vanilla-nodejs-http-server

**Comment by vpzomtrrfrt** [comment]
Yes. The `req` parameter is flagged as a type mismatch

**Comment by peterblazejewicz** [comment]
Can you redact the title, it seems you're correct. The definition directly depends on types from @types/express.
The solution is to rework the return type of the `serve(...)` method to return definition matching `(req, res, next): any`, but based on `@types/node` (compatible with Express, when used in that context). I'll redact my previous post.

**Comment by southrop** [comment]
Was there ever a workaroud or solution to this issue?

**Comment by vpzomtrrfrt** [comment]
My current workaround is to explicitly typecast the returned function when I call it

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
