### ISSUE TITLE
[@types/react-native-vector-icons] Property 'Button' does not exist on type 'typeof FontAwesome5Icon'.

### ISSUE THREAD

**Issue by dehy** [DefinitelyTyped/DefinitelyTyped#41000]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-native-vector-icons` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @iRoachie @timwangdev @robertying @Naturalclar 

If you do not mention the authors the issue will be ignored.

--------------

Hello and first, thank you for your work! I'm having a problem with ESLint where it cannot find the Button property on the Icon for FontAwesome5. It works without problem with FontAwesome. I'm not an expert of typescript and cannot figure out how to fix it.

Typescript v3.7.3
with ESLint v6.7.2
on React-Native v0.61.5

```ts
import Icon from 'react-native-vector-icons/FontAwesome5';

...

render() {
  return (
    <View>
      <Icon.Button
        name="bolt"
        onPress={}
        solid
      >Test</Icon.Button>
    </View>
  )
}
```

```error TS2339: Property 'Button' does not exist on type 'typeof FontAwesome5Icon'.```

Thank you !

**Comment by Naturalclar** [comment]
Seems like the definition for the Icon namespace listed below is missing from type definitions for FontAwesome5 and FontAwesome5Pro Icons https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ce019108970b5d39b578e0efed285b1743784b31/types/react-native-vector-icons/Icon.d.ts#L166-L171

I couldn't figure out a clean way to add similar namespace for FontAwesome5, so I've added a static class in #41007 

If there are cleaner solutions, please let me know  @iRoachie @timwangdev @robertying

**Comment by dehy** [comment]
After applying your patch, unfortunately, it doesn't recognize the "solid" property :

```
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<IconButtonProps>): Button', gave the following error.
    Type '{ children: string; name: string; backgroundColor: string; color: string; onPress: () => void; solid: true; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Button> & Readonly<IconButtonProps> & Readonly<...>'.
      Property 'solid' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Button> & Readonly<IconButtonProps> & Readonly<...>'.
  Overload 2 of 2, '(props: IconButtonProps, context?: any): Button', gave the following error.
    Type '{ children: string; name: string; backgroundColor: string; color: string; onPress: () => void; solid: true; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Button> & Readonly<IconButtonProps> & Readonly<...>'.
      Property 'solid' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Button> & Readonly<IconButtonProps> & Readonly<...>'.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
