### ISSUE TITLE
@types/mongoose No schema inference on model methods

### ISSUE THREAD

**Issue by eddiemf** [DefinitelyTyped/DefinitelyTyped#41048]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @danmana @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @tomyam1 @nephix @ChazEpps

I would like to know if there's any plausible reason for not having schema inference on all model methods such as `findOne`, `insert`, etc.

Given the following code:

```js
const userSchema = new Schema({
  name: String,
  email: String,
  password: String,
});

interface UserDocument extends Document {
  name: string;
  email: string;
  password: string;
}

const User = model<UserDocument>('User', userSchema);

// Will never give a compile error even though it's 
// possible to know the fields that should be defined here.
User.create({ emailll: 'some@email.com' });

// Same happens here since the param type is `any`
const user = new User({ dupa: '123' });
```

I would like to have the inference either from the model's schema or from the document interface that we define, but currently all types are `any` when it comes to query conditions or fields to insert, such as `User.create({ notSupposedToBeHere: 'but will be' })` which will either give a run time error due to validation or add the field to the database, but never a type error.

When using nodejs mongodb driver we can easily get the document fields by passing a schema type to the `collection` method, like so `db.collection<{name: string}>('user')` and properly get the `name` field when querying (although it will still allow for any other key to be there), and also get a type error when inserting a field that is not defined, preventing you at compile time to mess your database, so I guess that could be made possible here too.

So, again, is there any reason for this to not be done? 

Thanks!

**Comment by VanCoding** [comment]
This bugs me as well!

**Comment by silesky** [comment]
Agree. Typescript users will go through a lot of work to add typescript types when instantiating their model, 
 and then it seems like those types are just discarded. Typegoose and other solutions probably wouldn't need to exist for many people if the mongoose types worked as expected (?) out-of-the-box. 

I'm wondering, like the OP, is if there's history here, or it's just something that just hasn't been implemented yet. If the latter, I can take a look.

**Comment by avahe-kellenberger** [comment]
I am also having this issue and it's becoming a real pain. I'm having incorrect types returned with mongoose.model.find* as well, which stems from this issue. Would be great if someone could look into this, the issue has been open for a while
