### ISSUE TITLE
Property 'mask' does not exist on type 'JQuery<HTMLElement>

### ISSUE THREAD

**Issue by Ban-Dev** [DefinitelyTyped/DefinitelyTyped#41050]
Hi! I recently was trying to use the jquery mask in my angular project, so i installed in my project with: `npm i jquery-mask-plugin`, so in my TS file i wrote:
```javascript
ngOnInit() {
      $('.date').mask('11/11/1111');
      $('.time').mask('00:00:00');
      $('.date_time').mask('00/00/0000 00:00:00');
      $('.cep').mask('00000-000');
      $('.phone').mask('0000-0000');
      $('.phone_with_ddd').mask('(00) 0000-0000');
      $('.phone_us').mask('(000) 000-0000');
      $('.mixed').mask('AAA 000-S0S');
      $('.cpf').mask('000.000.000-00', {reverse: true});
      $('.money').mask('000.000.000.000.000,00', {reverse: true});
  }
```
Just as it is on the main site, but instead of  `$(document).ready(function(e))` i preferred to use the `ngOnInit()` , but when i save, the console hit me with the error: "Property 'mask' does not exist on type 'Jquery<HTMLElement>'"
What am i doing wrong? I have to import on the appModule? I have to declare it in the angular.json? I have to import in the component file that i'm going to use? What should i do??

**Comment by peterblazejewicz** [comment]
hi,
```bash
npm i -D @types/jquery
npm i -D @types/jquery-mask-plugin
```
then modify `tsconfig.app.json`:
```json
    "types": [
      "jquery",
      "jquery-mask-plugin"
    ]
  },
```
Plase close, if fixes your problem, thanks!
