### ISSUE TITLE
prop-types package RequirableKeys always returns never

### ISSUE THREAD

**Issue by Arlen22** [DefinitelyTyped/DefinitelyTyped#41074]
I discovered that propTypes.isRequired is broken in the current definition. The RequireKeys conditional generic always returns never, and the problem is because of certain code that I don't understand, but which I replaced with working code which I do understand. I've linked a comparison to my version of the file, but I don't have the time to go through all the steps to open a PR.

- [x] I tried using the `@types/prop-types` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DovydasNavickas @ferdaber @eps1lon 

https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...Arlen22:patch-1

```ts
export type RequiredKeys<V> = { [K in keyof V]-?:
    Exclude<V[K], undefined> extends Requireable<infer T> ? never
    : Exclude<V[K], undefined> extends Validator<infer T> ? K
    : never }[keyof V];
```

**Comment by Arlen22** [comment]
This affects https://github.com/facebook/prop-types/issues/306

**Comment by ferdaber** [comment]
Are you using `strictNullChecks` in your project?

**Comment by Arlen22** [comment]
But it gives the same error with or without. 

```
    "target": "es2018",
    "allowSyntheticDefaultImports": true,
    "jsx": "react-native",
    "lib": ["esnext"],
    "moduleResolution": "node",
    "importHelpers": true,
    "noEmit": true,
    "inlineSourceMap": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "strictNullChecks": true,
    "noImplicitAny": false,
    "strictBindCallApply": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
```
Here is my tsconfig settings.

**Comment by eps1lon** [comment]
@Arlen22 Could you make a reproducible example with https://www.typescriptlang.org/play/? While you can't pin a specific `@types/` version we can at least verify the issue with the latest version.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
