### ISSUE TITLE
intro.js should expose instance type

### ISSUE THREAD

**Issue by ippeiukai** [DefinitelyTyped/DefinitelyTyped#41108]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/intro.js` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Anahkiasen @LeonMontealegre

If you do not mention the authors the issue will be ignored.

<hr>

With https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37416 (`@types/intro.js@2.4.5`), IntroJS namespace is no longer exported.
That resulted in our code broken where variables are declared to hold IntroJs instances:

```TS
import * as introJs from 'intro.js';

class SomePage {

  introJsInstance: introJs.IntroJs;
  
  someMethod() {
    this.introJsInstance = introJs();
  }

}
```

The declaration should be fixed, or an alternative way to import instance and option types should be provided.

**Comment by peterblazejewicz** [comment]
Hey, please review the #41304, thanks!
