### ISSUE TITLE
Issues with express middleware (helmet, morgan)

### ISSUE THREAD

**Issue by morrigan** [DefinitelyTyped/DefinitelyTyped#41116]
Hi

- I tried using the `@types/express@4.17.0`, `@types/helmet@0.0.45` and `@types/morgan@1.7.37` packages and had problems.
- I tried using the latest stable version of tsc (3.7.3) with `esModuleInterop` and `strict` enabled.
- Pinging authors of express @borisyankov @CMUH @jessetrinity 

Sample code:
```
import express from "express";
import helmet from "helmet";
import morgan from "morgan";

const app = express();
app.use(morgan("short", {stream: morganLogger}));
app.use(helmet());
```

Error on both middlewares use: `No overload matches this call.
  The last overload gave the following error.
    Argument of type 'RequestHandler<any>' is not assignable to parameter of type 'PathParams'.
      Type 'RequestHandler<any>' is not assignable to type '(string | RegExp)[]'.`

Explicitly casting `app.use(helmet()  as RequestHandler)` removed the error but looking for a fix.

**Comment by stephanoparaskeva** [comment]
Did you find a solution to this issue?

**Comment by donbot-dev** [comment]
With `esModuleInterop: true` you must write import's like `import * as` for libraries using `export default`.

```typescript
import * as express from 'express';
import * as helmet from 'helmet';

const app = express();
app.use(helmet());
```
