### ISSUE TITLE
[@types/hapi__joi] Definition for Joi.append() and Joi.keys() doesn't allow object extensions

### ISSUE THREAD

**Issue by pdemarino** [DefinitelyTyped/DefinitelyTyped#41128]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/hapi__joi` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Bartvds, @myers, @cglantschnig, @SW, @GaelMagnan, @ralekna, @schfkt, @rokoroku, @dankraus, @wanganjun, @rafaelkallis, @aconanlai, @zaphoyd, @thewillg, @SimonSchick, @afharo, @lenovouser, @AnandChowdhary, @myovchev, @RecuencoJones, @everhardt
 

Trying to extend an object in Joi yields Typescript errors. Sample code:

```
export const schema = Joi.object({
    a: Joi.string()
});

export const extendedSchema = schema.append({
    b: Joi.string()  <<< ERROR
});

export const extendedSchema2 = schema.keys({
    b: Joi.string()    <<< ERROR
});
```
The error reported is: 
```
Argument of type '{ b: Joi.StringSchema; }' is not assignable to parameter of type 'SchemaMap<{ a: unknown; }>'.
  Object literal may only specify known properties, and 'b' does not exist in type 'SchemaMap<{ a: unknown; }>'.ts(2345)
```

**Comment by SimonSchick** [comment]
cc @HosseinAgha

**Comment by HosseinAgha** [comment]
It looks like TypeScript type inference creates this bug.   
I'm trying multiple tricks to bypass this for `any` type but had no luck so far.  
I think the tests are very generic, this should have been caught by tests (practically a regression) I've added some more tests.  
I'll create a PR when I reached a solution.

**Comment by myers** [comment]
And it's @laurence-myers not @myers

**Comment by pdemarino** [comment]
Oooops! Sorry!
