### ISSUE TITLE
[@types/yup] Declaration files generated by tsc output `any` for all fields for nested schemas

### ISSUE THREAD

**Issue by king-sam-perez** [DefinitelyTyped/DefinitelyTyped#41133]
Originally posted in yup, was referred to here. [Original Issue Link](https://github.com/jquense/yup/issues/726)

Hi DefinitelyTyped,

I am attempting to use yup to define schemas and associated typescript types. When I try to generate typescript declaration files for the schemas that I’ve written, I’ve noticed that the type information for any nested schemas is being lost and converted to any.
I’ve included a small example to illustrate the problem:
`example.ts`:
```
import * as yup from ‘yup’;
const NestedSchema = yup.object().shape({
  nested: yup.string()
});
export const TestSchema = yup.object().shape({
  working: yup.string(),
  broken: NestedSchema
});
export type Test = yup.InferType<typeof TestSchema>;
```
Run: `tsc -d example.ts`:
Actual generated `example.d.ts`:
```
import * as yup from ‘yup’;
export declare const TestSchema: yup.ObjectSchema<yup.Shape<object, {
    working: string;
    broken: yup.Shape<object, {
        nested: any;  // <---- TYPE INFORMATION LOST!
    }>;
}>>;
export declare type Test = yup.InferType<typeof TestSchema>;
```
Expected output:
```
import * as yup from ‘yup’;
export declare const TestSchema: yup.ObjectSchema<yup.Shape<object, {
    working: string;
    broken: yup.Shape<object, {
        nested: string;
    }>;
}>>;
export declare type Test = yup.InferType<typeof TestSchema>;
```
Is this a known issue? Is there any workaround? Any help would be much appreciated!

Platform:
macOS Mojave 10.14.6
node: v10.17.0
yup: 0.27.0
@types/yup: 0.26.26
tsc: 3.7.3

To repro the issue locally, check out: https://github.com/kingsmendv/issue-yup-infer-type-any/blob/master/package.json

**Comment by king-sam-perez** [comment]
Reaching out to some contributors:

@ericbiewener, @vtserman, @MoretonBayRC 

Hey everyone, I cross-posted this question on typescript [here](https://github.com/microsoft/TypeScript/issues/35720) and there was a response. Apparently, this is an issue with the typescript emitter, but the responder found a workaround.

I'm not too familiar with typescript declarations and type resolutions, but I was wondering if this made sense to you and if there was some workaround we could introduce here.

-Sam

**Comment by russell-dot-js** [comment]
Bumping this, was hoping the fix wouldn't be too crazy but having a hard time figuring out what's wrong (FWIW ts-server correctly infers the types, but tsc does not)

@ericbiewener, @vtserman, @MoretonBayRC -- do you have any idea how we could fix this?

**Comment by russell-dot-js** [comment]
@mauricedb I saw you comment on #42360 and was hoping you might be able to help us out over here as well

**Comment by mauricedb** [comment]
The issue seems to be with TSC

The derived type by `InferType<>` and the compiler is:
```ts
type Test = {
    working?: string;
    broken?: yup.Shape<object, {
        nested: string;
    }>;
}
```
which seems to be correct.

The `const TestSchema` doesn't but I am not quire sure what yo are trying to do with the declared fields there. 

BTW I typically write my types like this:
```ts
const NestedSchema = yup.object({
  nested: yup.string()
});
export const TestSchema = yup.object({
  working: yup.string(),
  broken: NestedSchema
});
```

This is results in a slightly nicer infered type:
```ts
type Test = {
  working?: string;
  broken?: {
    nested: string;
  };
};
```

Compile time checking or generated constant remain the same though.

**Comment by iampeterbanjo** [comment]
As a work around I'm using [type-fest](https://github.com/sindresorhus/type-fest) to `Merge` nested schemas which seems to work.

``` JavaScript
export type Product = yup.InferType<typeof ProductShape>; 

export type Products = {
  products: Product[];
};

// override prop products which was yup.array().of(ProductShape)
export type PaymentProps = Merge<
  yup.InferType<typeof PaymentsBodyShape>,
  Products
>;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
