### ISSUE TITLE
keys has wrong return type in @types/ramda

### ISSUE THREAD

**Issue by hgezim** [DefinitelyTyped/DefinitelyTyped#41158]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/ramda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@TheHandsomeCoder
@donnut
@mdekrey
@mrdziuban
@sbking
@afharo
@teves-castro
@1M0reBug
@hojberg
@samsonkeung
@angeloocana
@raynerd
@moshensky
@ethanresnick
@deftomat
@blimusiek
@biern
@rayhaneh
@rgm
@drewwyatt
@jottenlips
@minitesh
@krantisinh
@pirix-gh
@brekk
@nemo108
@jituanlin
@Philippe-mills
@Saul-Mirone

Here's the code to illustrate:

```
import {keys} from 'ramda';

interface Recipe {
  id: number;
}

const recipes: Recipe[] = [{ id: 1 }, { id: 2 }];

interface RecipesById {
  [index: number]: Recipe;
}

const recipesById: RecipesById = {};

recipesById[recipes[0].id] = recipes[0];
recipesById[recipes[1].id] = recipes[1];

// let allKeys: number[] = Object.keys(recipesById);
// above line erros with:
// error TS2322: Type 'string[]' is not assignable to type 'number[]'.

let ramdaKeys: number[] = keys(recipesById);
// above line compies happily and is incorrect as ramdaKeys is string[]
console.log(ramdaKeys); //
```
Running: https://repl.it/repls/AbleLustrousSandboxes

Also, TypeScript itself has `string[]` as return type for `Object.keys()`.

**Comment by peterblazejewicz** [comment]
for reference: https://ramdajs.com/docs/#keys

**Comment by pirix-gh** [comment]
@hgezim I can integrate those changes in a near future. Indeed, ramda does return `string` keys and not `number` for arrays.

https://ramdajs.com/repl/?v=0.26.1#?R.keys%28%5B%7B%20id%3A%201%20%7D%2C%20%7B%20id%3A%202%20%7D%5D%29%3B

**Comment by Georift** [comment]
This seems to [have been fixed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2490b045819e5e3ed1f930f97006bc9d2a54a336/types/ramda/index.d.ts#L898), although I couldn't track down the change.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
