### ISSUE TITLE
@types/react-native TVEventHandler

### ISSUE THREAD

**Issue by sureshsu** [DefinitelyTyped/DefinitelyTyped#41229]
If you know how to fix the issue, make a pull request instead.

- [ x] I tried using the `@types/react-native-0.60.26` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kamal 

The issue is, index.d.ts in the package don't have definitions for TVEventHandler and related dependencies needed to run react-native for TV devices.

Is there any plan to include them in the type definitions as they have been supported since 0.57 react native..?

Thanks

**Comment by burtek** [comment]
@sureshsu you would get more attention here if you pinged all authors from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts:|

@alloy, @huhuanming, @iRoachie, @skn0tt, @timwangdev, @kamal, @alexdunne, @swissmanu, @bm-software, @a-tarasyuk, @mvdam, @esemesek, @mrnickel, @souvik-ghosh, @nossbigg, @saranshkataria, @franzmoro, @tykus160, @jakebloom, @ceyhun, @mcmar, @theohdv, @TheSavior, @romain-faust, @bebebebebe, @Naturalclar, @chinesedfan, @vtolochk

**Comment by alloy** [comment]
The RN types have thus far been maintained opportunistically–that is, people add what they need when they need it. If you were to create a PR for the typings you need then that would be much appreciated 🙏

**Comment by Eljoy** [comment]
So, why the issue was closed?

**Comment by alloy** [comment]
As my comment was trying to explain, there is no point in having open issues for these typings when we only work perform work on them when _we need it_, that only leads to issue-tracker rot.
