### ISSUE TITLE
[@types/testing-library__dom] Use generic type in queries

### ISSUE THREAD

**Issue by bungu** [DefinitelyTyped/DefinitelyTyped#41234]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alexkrolick @kentcdodds @eps1lon @weyert @reyronald @wKovacs64 

Hi there. In my test file I'm trying to check if some fields in form has specific values. So I wrote a query that find input element like this:

```typescript
expect(getByTestId('card-number').value).toEqual('1251 0999 9999 9999');
```

But all queries return `HTMLElement` type, so I got error `TS2339: Property 'value' does not exist on type 'HTMLElement'`. It should be more specific type `HTMLInputElement` instead.

I tried to add generic result type in queries.d.ts. The only way I could find to do that is to change `type` to `interface`, otherwise there would be breaking changes in interfaces.

Before:

```typescript
export type GetByBoundAttribute = (container: HTMLElement, id: Matcher, options?: MatcherOptions) => HTMLElement;
```

After:

```typescript
export interface GetByBoundAttribute {
    <T = HTMLElement>(container: HTMLElement, id: Matcher, options?: MatcherOptions): T;
}
```

It works fine if i import queries from package, but the `screen` object type now broken.

All my changes with error details are in this commit: https://github.com/bungu/DefinitelyTyped/commit/8f4d9bac6dd06fe9c308668aee55fb01e724ef41

Is there any way we could add generic types to queries and `screen` both? I'm ready to make PR, but stuck with this issue.

**Comment by wKovacs64** [comment]
I looked into this once and got in over my head and had to move on. 😅  I ended up just using a type assertion in my tests:

```ts
expect((getByTestId('card-number') as HTMLInputElement).value).toEqual('1251 0999 9999 9999');
```

> I tried to add generic result type in queries.d.ts. The only way I could find to do that is to change `type` to `interface`, otherwise there would be breaking changes in interfaces.

Not sure I follow the change to interfaces. Why wouldn't your example just become the following?

```ts
export type GetByBoundAttribute<T = HTMLElement> = (container: HTMLElement, id: Matcher, options?: MatcherOptions) => T;
```

That aside, maybe @alexkrolick or someone can swoop in and tell us how to do this correctly. 🤷‍♂

**Comment by eps1lon** [comment]
You can use type casting instead as suggested by @wKovacs64 :

```ts
const input = getByTestId('card-number') as HTMLInputElement
```

Making the function generic would be inappropriate since the function cannot not at runtime with which type argument it got invoked. 

See https://twitter.com/SeaRyanC/status/1205170798282960896 (from a TS engineering lead) for more information why making it generic would be inappropriate.

**Comment by wKovacs64** [comment]
Well... there you have it! Thanks, @eps1lon!

**Comment by bungu** [comment]
> Not sure I follow the change to interfaces. Why wouldn't your example just become the following?

Then at the exporting section https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/testing-library__dom/queries.d.ts#L79 every generic type would be referred to default type `HTMLElement`. Exported values should implement another interface with its own generics, like this:

```typescript
export function getByLabelText<T = HTMLElement>(container: HTMLElement, id: Matcher, options?: SelectorMatcherOptions): T;
```

> Making the function generic would be inappropriate since the function cannot not at runtime with which type argument it got invoked.

I thinks it's not exactly the case, but i got it. There will be no issues if type `HTMLInputElement` would be extended by `HTMLElement`, but that types are not related.

It seems like type casting is quite good solution, thank you.
