### ISSUE TITLE
Add `Styled with Prettier` badge [README]

### ISSUE THREAD

**Issue by peterblazejewicz** [DefinitelyTyped/DefinitelyTyped#41245]
This is pure dev-x issue. Recent change to readme outlines usage of the `Prettier` in the repo.
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/9f2b299e70f71500b4d3bef7c30c366d5c7f057a#diff-04c6e90faac2675aa89e2176d2eec7d8R185

Can the `styled with Prettier` badge be added to the Readme, to point that out via visual clue?
https://github.com/prettier/prettier/blob/master/README.md#badge
Thanks!

**Comment by yardenshoham** [comment]
I guess this issue should be closed as #41793 wasn't accepted.

**Comment by peterblazejewicz** [comment]
Yup, closing. Thanks!
