### ISSUE TITLE
Bug in express-session: Store is a class

### ISSUE THREAD

**Issue by phillips1012** [DefinitelyTyped/DefinitelyTyped#4126]
https://github.com/borisyankov/DefinitelyTyped/blob/da2bb07e037a61e6ead149ae89063b00892f6929/express-session/express-session.d.ts#L56-L62

`Store` is actually an abstract class, in the  express-session definition.

See here:
- https://github.com/expressjs/session/blob/a7f7f6766f0877930b8c5dd09b59186ded0ce9c9/session/store.js#L23
- https://github.com/expressjs/session/blob/a7f7f6766f0877930b8c5dd09b59186ded0ce9c9/session/memory.js#L39

This bug makes it impossible to access `session.Store` to extend it:

![](https://i.imgur.com/fG1ONTF.png)

**Comment by vvakame** [comment]
@phillips1012 please send a PR. I'll review it.

**Comment by builtinnya** [comment]
Seems to be fixed in #8204.
