### ISSUE TITLE
Breaking change in @3.2.5

### ISSUE THREAD

**Issue by link2malkeet** [DefinitelyTyped/DefinitelyTyped#41267]
If you know how to fix the issue, make a pull request instead.

I tried using the `@types/koa-compose@3.2.5` package and had problems.
Seems there is breaking change 3.2.4 to 3.2.5, 
This code snippet changed FROM 
`declare namespace compose {
    type Middleware<T> = (context: T, next: () => Promise<any>) => any;
    type ComposedMiddleware<T> = (context: T, next?: () => Promise<any>) => Promise<void>;
}`
TO
`declare namespace compose {
    type Middleware<T> = (context: T, next: Koa.Next) => any;
    type ComposedMiddleware<T> = (context: T, next?: Koa.Next) => Promise<void>;
}`
Return type of next is changed.

Can we please bump it in a nice manner so that it does introduce any breaking change.
@maxdeviant @phobon @zephraph @damassi @alloy @maoueh @Lavoaster @jschuler @adam187 @gretzky @chrislopresto @peduarte

**Comment by alloy** [comment]
I’m unsure why you tagged us, the maintainers of Koa-compose are @jkeylu & @astashov and that change seems to have been made by @thewilkybarkid on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40213.

**Comment by RyanCavanaugh** [comment]
Types versions major numbers match their packages and are not semvered
