### ISSUE TITLE
Added typings for nice-try

### ISSUE THREAD

**Issue by Richienb** [DefinitelyTyped/DefinitelyTyped#41286]
The maintainer for `nice-try` doesn't wish to maintain types, migrate them from the PR to this repo. https://github.com/electerious/nice-try/pull/23

**Comment by peterblazejewicz** [comment]
@Richie765 
You could create a new type using `nice-try` module name, see:
https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package
Shout, if you need a hand
