### ISSUE TITLE
[@types/react-stripe-elements] Missing types

### ISSUE THREAD

**Issue by apedroferreira** [DefinitelyTyped/DefinitelyTyped#41281]
There are several missing type definitions, such as for example:

```props.stripe.handleCardAction```
```locale``` prop in `StripeProvider`

**Comment by peterblazejewicz** [comment]
> locale prop in StripeProvider

Can you refer to Stripe's relevant docs for sample usage? Thanks!

**Comment by apedroferreira** [comment]
> > locale prop in StripeProvider
> 
> Can you refer to Stripe's relevant docs for sample usage? Thanks!

Thanks for addressing this!

The main issue isn't so much that it's harder to figure out what methods the library provides, but that Typescript actually throws errors if we try to use them, which blocks the program from running.
