### ISSUE TITLE
ERROR in node_modules/@types/googlemaps/index.d.ts — A tuple type element list cannot be empty

### ISSUE THREAD

**Issue by fitdeveloper** [DefinitelyTyped/DefinitelyTyped#41308]
I tried using the `@types/googlemaps` package and had problems.
while trying to integrate the angular google maps - agm librarie in my angular project i got this error :

```
ERROR in node_modules/@types/googlemaps/index.d.ts(63,25): error TS1122: A tuple type element list cannot be empty.
node_modules/@types/googlemaps/index.d.ts(72,25): error TS1122: A tuple type element list cannot be empty.
node_modules/@types/googlemaps/index.d.ts(94,15): error TS1122: A tuple type element list cannot be empty.
node_modules/@types/googlemaps/index.d.ts(100,18): error TS1122: A tuple type element list cannot be empty.
node_modules/@types/googlemaps/index.d.ts(106,20): error TS1122: A tuple type element list cannot be empty.
node_modules/@types/googlemaps/index.d.ts(115,26): error TS1122: A tuple type element list cannot be empty.
node_modules/@types/googlemaps/index.d.ts(121,15): error TS1122: A tuple type element list cannot be empty.
node_modules/@types/googlemaps/index.d.ts(130,28): error TS1122: A tuple type element list cannot be empty.
node_modules/@types/googlemaps/index.d.ts(155,29): error TS1122: A tuple type element list cannot be empty.
node_modules/@types/googlemaps/index.d.ts(167,22): error TS1122: A tuple type element list cannot be empty.
node_modules/@types/googlemaps/index.d.ts(176,23): error TS1122: A tuple type element list cannot be empty.
node_modules/@types/googlemaps/index.d.ts(185,23): error TS1122: A tuple type element list cannot be empty.
node_modules/@types/googlemaps/index.d.ts(3308,76): error TS2370: A rest parameter must be of an array type.
```
somthing is worng with some configuration or maybe something i have missed i m working with material 6 and angular 6 in this project thanks for your help

version :     "@types/googlemaps": "^3.39.0",

in terminal console

**Comment by fitdeveloper** [comment]
here is what i have tried but not working : 
[stackoverflow source for question ](https://stackoverflow.com/questions/59472584/error-in-node-modules-types-googlemaps-index-d-ts-a-tuple-type-element-list/59490837?noredirect=1#comment105173171_59490837)

**Comment by andreyzenkov** [comment]
Same problem. Rolled back to 3.38.0 and it works.

**Comment by moridianmess** [comment]
Same here, rolling back solved this for me too.

**Comment by Domvel** [comment]
Version 3.38.0 seems to be the sweet spot version. My env: Windows 10, Node v12.16.1, Typescript 2.8.4 / 3.1.6.

**Comment by jgutix** [comment]
@fitdeveloper AGM doesn't use @type/googlemaps ([yet](https://github.com/SebastianM/angular-google-maps/pull/1648)?) they use their own [definitions](https://github.com/SebastianM/angular-google-maps/blob/master/packages/core/services/google-maps-types.ts)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
