### ISSUE TITLE
[@types/semver] Types have not been updated for version 7 of the package

### ISSUE THREAD

**Issue by kaiyoma** [DefinitelyTyped/DefinitelyTyped#41326]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Bartvds @BendingBender @LucianBuzzo @ajafff @ExE-Boss

Version 7 of the package changes the API such that this no longer works:

```
import { coerce } from 'semver';
```

Now you have to do something like this:

```
import { coerce } from 'semver/preload';
import { coerce } from 'semver/functions/coerce';
```

However, when doing either of the latter, TypeScript complains:

```
Could not find a declaration file for module 'semver/preload'.
```

More discussion here: https://github.com/npm/node-semver/issues/306

**Comment by peterblazejewicz** [comment]
@kaiyoma I'm attempting to update the types, can you look into #41409 and post your thoughts?
thanks!
