### ISSUE TITLE
[mongodb] Regression with filtering over ObjectID

### ISSUE THREAD

**Issue by nickbclifford** [DefinitelyTyped/DefinitelyTyped#41332]
- [x] I tried using the `@types/mongodb` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT @alanmarcell @bitjson @dante-101 @mcortesi @EnricoPicci @AJCStriker @julien-c @daprahamian @denys-bushulyak @BastienAr @sindbach @geraldinelemeur @jishi @various89 @angela-1 @lirbank @hector7 @floric @erikc5000 @Manc @jloveridge @ranguna @HosseinAgha @albertossilva @Rauno56

After updating to the most recent version of `@types/mongodb`, I now get an error when using an ObjectID to filter over a query.

```typescript
const canvasdata = db.collection<CanvasCacheEvent>('canvasFeeds');
const events = await canvasdata.find({ user: userDoc!._id }).toArray();
```
```
src/libs/canvas.ts:204:34 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(query?: FilterQuery<CanvasCacheEvent> | undefined): Cursor<CanvasCacheEvent>', gave the following error.
    Argument of type '{ user: ObjectID; }' is not assignable to parameter of type 'FilterQuery<CanvasCacheEvent>'.
      Type '{ user: ObjectID; }' is not assignable to type '{ [x: string]: string | RegExp | ParamList | QuerySelector<string | RegExp | ParamList | undefined> | undefined; type?: RegExp | ... 7 more ... | undefined; ... 21 more ...; _id?: string | ... 3 more ... | undefined; }'.
        Property 'user' is incompatible with index signature.
          Type 'ObjectId' is not assignable to type 'string | RegExp | ParamList | QuerySelector<string | RegExp | ParamList | undefined> | undefined'.
            Type 'ObjectId' has no properties in common with type 'QuerySelector<string | RegExp | ParamList | undefined>'.
  Overload 2 of 2, '(query: FilterQuery<CanvasCacheEvent>, options?: FindOneOptions | undefined): Cursor<CanvasCacheEvent>', gave the following error.
    Argument of type '{ user: ObjectID; }' is not assignable to parameter of type 'FilterQuery<CanvasCacheEvent>'.
      Type '{ user: ObjectID; }' is not assignable to type '{ [x: string]: string | RegExp | ParamList | QuerySelector<string | RegExp | ParamList | undefined> | undefined; type?: RegExp | ... 7 more ... | undefined; ... 21 more ...; _id?: string | ... 3 more ... | undefined; }'.
        Property 'user' is incompatible with index signature.
          Type 'ObjectId' is not assignable to type 'string | RegExp | ParamList | QuerySelector<string | RegExp | ParamList | undefined> | undefined'.
            Type 'ObjectId' has no properties in common with type 'QuerySelector<string | RegExp | ParamList | undefined>'.

204  	events = await canvasdata.find({ user: userDoc!._id }).toArray();
```

**Comment by HosseinAgha** [comment]
Could you provide the `CanvasCacheEvent` interface? what is the type of user field?

**Comment by nickbclifford** [comment]
Looks like I forgot to add the `user` field to the schema when first testing it. However, even when adding the correct field, I still get the same error.
Regardless, here's the interface:
```typescript
export type CanvasCacheEvent = ical.CalendarComponent & {
	_id: string | ObjectID,
	user: ObjectID
};
```
I see the casing is deprecated, but the type is the same, so I don't think it matters in this case.

**Comment by nickbclifford** [comment]
Have there been any updates to the types?

**Comment by nickbclifford** [comment]
Bumping this; I'm currently on version 3.5.26 of `@types/mongodb` and I still get the same error.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
