### ISSUE TITLE
[@types/highlight.js] Add types for `highlight.js/lib/highlight.js`

### ISSUE THREAD

**Issue by rtfpessoa** [DefinitelyTyped/DefinitelyTyped#41351]
As described in https://github.com/highlightjs/highlight.js/issues/2340 I would like to import file `highlight.js/lib/highlight.js` but I it complains that I don't have types for it since types were just defined for the index.js file.

@JoshuaKGoldberg I read the links you sent me, but I am still not understanding how to type a file inside a module. Can you maybe provide a bit more help in how I can accomplish that?

I have esModuleInterop enabled and the types for that file are exactly the same as the ones for the main entrypoint of the module, but I still cannot get it to work.

**Comment by JoshuaKGoldberg** [comment]
Sure, and thanks for following up!

For creating a place for the `lib/highlight.js` module definitions, I haven't looked too closely but I would guess including this snippet somewhere is what you're looking for:

```ts
declare module 'highlight.js/lib/highlight.js' {
    // Regular module contents go here: what shape are they?
}
```

If placing that in either of the existing `index.d.ts` _or_ something like a new `lib/highlight.js.d.ts` doesn't work.

As for what goes in there, I again haven't really taken a hard look - is that the area you're hoping for direction on?

**Comment by rtfpessoa** [comment]
@JoshuaKGoldberg I will try to test with that approach but I am pretty sure I tried that without success. I think the compiler complained saying that `highlight.js/lib/highlight.js` was not a module.

Anyone that comes to your mind that can help with this?

**Comment by rtfpessoa** [comment]
@JoshuaKGoldberg, thanks to your help I was able to get this working.
After some experiments this was the best I came up with: https://github.com/rtfpessoa/diff2html/pull/274/files#diff-ea4bf221053dc50439fd54f34beaa1f0, do you have any suggestions on how to deduplicate the types?

If you think this is fine I will contribute this upstream.

**Comment by rtfpessoa** [comment]
Hey @JoshuaKGoldberg, not sure if you missed my comment or just did not got time. If you could take a look would be greatly appreciated.

**Comment by JoshuaKGoldberg** [comment]
👋 I threw together a thing in https://github.com/rtfpessoa/diff2html/pull/278 - it may or may not work; I haven't had much time to dig very deeply. Good luck! 😄
