### ISSUE TITLE
D3 declarations cannot be merged with anything else

### ISSUE THREAD

**Issue by aleksey-bykov** [DefinitelyTyped/DefinitelyTyped#4139]
Due to using the following style the declaration merging with another ambient module that uses the same method names is [not possible](https://github.com/Microsoft/TypeScript/issues/2825):

```
// another module cannot extend the `select` method by an overload 
interface Selectors {
   select: {
      (): Selection;
      // ...
   }
}
```

Please consider using the following style that enables declaration merging:

```
interface Selectors {
    // no problem with overloads from a different ambient module
    select(): Selection;
    // ...
}
```

**Comment by vvakame** [comment]
@aleksey-bykov please send a PR. I'll review it.

**Comment by tomwanzek** [comment]
As part of some legacy D3v3 issue clean-up, can this issue be please closed?

D3v4 has been released and supported with actively maintained definitions for several months now, so it would be great to have only current issues open for clarity.

Thanks in advance!

cc @gustavderdrache @andy-ms
