### ISSUE TITLE
[@types/react-native] transform rotate property can also be number

### ISSUE THREAD

**Issue by sjsakib** [DefinitelyTyped/DefinitelyTyped#41410]
`rotate` property of `transform` can also be a number (in radian). But currently it takes only string.
So this code gives type error, but works fine.
```js
<View style={{ transform: [{ rotate: Math.PI }] }}>{...}</View>
```

- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @acoates-ms @alloy @huhuanming

**Comment by alloy** [comment]
Thanks for taking the time 🙏 However, please provide a PR instead, as these types are currently being maintained in an opportunistic fashion–i.e. we fix them when we have needs ourselves.
