### ISSUE TITLE
[node] Can't augement static side of Module since 13.1.2

### ISSUE THREAD

**Issue by Flarna** [DefinitelyTyped/DefinitelyTyped#41509]
Since https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41225 I'm no longer able to augment the static side of `class Module`.  Before it was possible as indicated there: #40927 (comment)

I get `Duplicate identifier 'Module' as error. Any hints how to tell typescript to merge the declarations?

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick @sandersn @andrewbranch

**Comment by andrewbranch** [comment]
Can can you try adding an empty `namespace Module {}` inside the current type definition’s `declare module "module"` block, then in your own code, augment like:

```ts
declare module 'module' {
  function _load(request: string, parent: NodeModule | undefined, isMain?: boolean): any;
  function _resolveFilename(request: string, parent: NodeModule | undefined): string;
}
```

and see if that works without causing other problems? Then we can PR that namespace declaration.

Doing that also seems to enable `import { Module } from 'module'` (cc @SimonSchick)

**Comment by Flarna** [comment]
I tried to add `namespace Module {}` in module.d.t and the following in my code (in a dedicated .d.ts file):
```ts
declare module "module" {
  namespace Module {
    function _load(request: string, parent: NodeModule | undefined, isMain?: boolean): any;
    function _resolveFilename(request: string, parent: NodeModule | undefined): string;
  }
}
```

I get following errors:
```
node_modules/@types/node/module.d.ts(15,16): error TS2300: Duplicate identifier 'Module'.
node_modules/@types/node/module.d.ts(20,5): error TS2309: An export assignment cannot be used in a module with other exported elements.
typings/extensions/node-ext.d.ts(85,12): error TS2300: Duplicate identifier 'Module'.
```

In @types/node v12 following works:
```ts
declare namespace NodeJS {
  namespace Module {
    function _load(request: string, parent: NodeModule | undefined, isMain?: boolean): any;
    function _resolveFilename(request: string, parent: NodeModule | undefined): string;
  }
}
```

**Comment by andrewbranch** [comment]
Right, do this:

```diff
declare module "module" {
-  namespace Module {
    function _load(request: string, parent: NodeModule | undefined, isMain?: boolean): any;
    function _resolveFilename(request: string, parent: NodeModule | undefined): string;
-  }
}
```

**Comment by Flarna** [comment]
Still get an error:
```node_modules/@types/node/module.d.ts(20,5): error TS2309: An export assignment cannot be used in a module with other exported elements.
```

**Comment by andrewbranch** [comment]
Ah, for some reason that didn't come up in my editor when I tried it earlier. I was kind of surprised that those module shapes were allowed to merge.

**Comment by Flarna** [comment]
Does this mean there is no solution for this in current typescript versions? Should we consider this as typescript bug?
Other option is to move the module definition back to `NodeJS` namespace but this has side effects that it is not possible to use e.g. `URL` there.

**Comment by andrewbranch** [comment]
Hold on, I think this does work for me—don’t forget that to write a module augmentation, the file you write it in must itself be a module.

![image](https://user-images.githubusercontent.com/3277153/72278396-c7439000-35e8-11ea-9857-5cfc651a15b1.png)

When I gave you [this](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41509#issuecomment-573156369) code snippet to try, I failed to include a top-level import or export declaration, so based on the errors you got I think you must have been trying it in a global/script file.

**Comment by Flarna** [comment]
I added the augmentations in a dedicated .d.ts file. If I use a .ts file instead it seems to work.

But honestly speaking I have no idea why. Would be nice to get some more insight.

I will raise a PR to add the empty namespace.

**Comment by arcanis** [comment]
In case someone else get this problem, I solved it by applying the following changes:
https://github.com/yarnpkg/berry/pull/915/files#diff-a8eacea1558d48d2862f185c492aa4f7
