### ISSUE TITLE
@types/victory - incorrect type on innerRadius

### ISSUE THREAD

**Issue by mikecsmith** [DefinitelyTyped/DefinitelyTyped#41685]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3435866e85f74bc31b21bd8c094db9bf8f385c60/types/victory/index.d.ts#L2943

The type definition on this line should be updated to:

```
number | ((props: VictoryPieProps) => number)
```

Apologies for not putting a PR together myself - work commitments getting in the way!

**Comment by mikecsmith** [comment]
Thanks for doing this so quickly @peterblazejewicz !

Quick bit of feedback: VictorySliceProps aren't quite functioning as intended on the typing for this. Passing the innerRadius prop allows you to construct a donut chart if you use the callback function with props.datum.y - but if you pass a number you get a circular cutout of a given pixel dimension.

I'm using it to produce a circular cutout which is responsive to the overall size of the VictoryPIe's container.

Effectively the radius prop in your VictorySliceProps should be a number. I'm pretty certain it's just the VictoryPieProps being passed into itself - you can see this on the radius if you console.log the props inside the callback.

I think it'd either be move the update back over to type VictoryPieProps - or update your VictorySliceProps to have the radius set as a number.

Quick example to replicate - make sure you've got latest @types/victory installed to the test case:

```tsx
import * as React from "react";
import * as ReactDOM from "react-dom";
import { VictoryPie } from "victory";

const TestPie = () => (
  <VictoryPie data={[{ x: "Cats", y: 7 }, { x: "Dogs", y: 27 }]} innerRadius={({ radius }) =>  radius * 0.2} />
);

ReactDOM.render(<TestPie />, document.getElementById("main");

```

Error on this usecase is:

```
var radius: SliceNumberOrCallback<VictorySliceProps, "radius">
The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.ts(2362)
```

I'm temporarily fixing it with ``` innerRadius={({ radius }) =>  (radius as number) * 0.2}```

Hope that helps and thanks again for resolving this so quickly!

**Comment by peterblazejewicz** [comment]
Will look into this, thanks for the headups!
