### ISSUE TITLE
Problem in d3.d.ts with the declaration of d3.csv.parseRows()

### ISSUE THREAD

**Issue by barry-tannenbaum** [DefinitelyTyped/DefinitelyTyped#4177]
The accessor parameter in d3.csv.parseRows() should be optional., just like the accessor parameter in the declaration of d3.csv.parse above it. Making it optional matches the declaration of d3.cvs.parseRows() at https://github.com/mbostock/d3/wiki/CSV, and adding the missing "?" allows my program to compile and work.

**Comment by vvakame** [comment]
@barry-tannenbaum please send a PR. I'll review it.

**Comment by barry-tannenbaum** [comment]
Unfortunately for some reason I didn't get your reply. I'm not quite sure what you want for a PR. I have a sample TypeScript project that I'd be happy to give you, if I could figure out how to attach a file.

Here's the diff:

$ hg diff
diff -r f8c1987f218b Scripts/typings/d3/d3.d.ts
--- a/Scripts/typings/d3/d3.d.ts        Mon May 11 11:08:09 2015 -0400
+++ b/Scripts/typings/d3/d3.d.ts        Mon May 11 11:09:49 2015 -0400
@@ -737,7 +737,7 @@
         *
         * @param string delimited formatted string to parse
         */
-        parseRows(string: string, accessor: (row: any[], index: number) => any): any;
+        parseRows(string: string, accessor?: (row: any[], index: number) => any): any;
         /**
         * Format an array of tuples into a delimited string.
         *

**Comment by barry-tannenbaum** [comment]
I didn't mean to close that...

**Comment by tomwanzek** [comment]
As part of some legacy D3v3 issue clean-up, can this issue be please closed?

D3v4 has been released and supported with actively maintained definitions for several months now, so it would be great to have only current issues open for clarity.

Thanks in advance!

cc @gustavderdrache @andy-ms
