### ISSUE TITLE
[@types/styled-components] Error using styled component in functional component

### ISSUE THREAD

**Issue by ortonomy** [DefinitelyTyped/DefinitelyTyped#41790]
- [x] I tried using the `@types/styles-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @Lavoaster @Jessidhia @JKillian @eps1lon @flavordaaave @wagerfield 

Admittedly I've very very new to TS, so I'm just coming to terms with all the syntax and the demands for different definitions of types. However, this seems like something that almost EVERY user of styled-components would like to do, but I can't find reference to this error anywhere.
The first demo of such a use case appears here in their docs: https://styled-components.com/docs/basics#adapting-based-on-props

 I've checked the `styled-components` typescript section and doesn't reference this usage at all: https://styled-components.com/docs/api#using-custom-props

![image](https://user-images.githubusercontent.com/6688676/72905998-6cd6cc00-3d6c-11ea-8399-939ee7a86536.png)

> `'FullScreenDiv' refers to a value, but is being used as a type here.ts(2749)`

I've done my searching and the closest I can get is this issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/39136

But I don't really understand if this is related to generics or something else.

**Comment by eps1lon** [comment]
It looks like you're in a `.ts` file while using JSX syntax. If you want to use JSX you need to use the `.tsx` file extension. For more information see https://www.typescriptlang.org/docs/handbook/jsx.html

Either way this issue is not specific to `styled-componets`. If my suggestion didn't help I would refer you to stackoverflow.com. It would help a lot if you would be so kind and link the created question and close this issue.

**Comment by ortonomy** [comment]
@eps1lon -- thanks for the tip. Worked perfectly.

![image](https://user-images.githubusercontent.com/6688676/72952468-ea322900-3dcc-11ea-9771-7ec6d60ed1cb.png)
