### ISSUE TITLE
[@types/hapi__joi]: This expression is not callable for validate and validateAsync in v16.0.7

### ISSUE THREAD

**Issue by shrujalshah28** [DefinitelyTyped/DefinitelyTyped#41805]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/hapi__joi` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors so they can respond.
  - Authors: @legraphista
  - Reviewer: @afharo 

After PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41788, I am getting below error while calling `validateAsync` function on compiled schema.

Error
```
This expression is not callable.
Each member of the union type '(<T = any>(value: any, options?: AsyncValidationOptions) => Promise<T>) | (<T = any[]>(value: any, options?: AsyncValidationOptions) => Promise<...>) | ... 9 more ... | (<T = symbol>(value: any, options?: AsyncValidationOptions) => Promise<...>)' has signatures, but none of those signatures are compatible with each other.
```

Versions
```
"typescript": "^3.7.5"
"@types/hapi__joi": "^16.0.7"
```
 
Workaround - ~Pin version to `16.0.6`~ Update version to `16.0.9`

**Comment by legraphista** [comment]
Hi @shrujalshah28 

I'm sorry that my changes disrupted your workflow.
Are you able to provide a self-contained snipped of code that reproduces the error?

**Comment by mike-dazn** [comment]
This has broken us too with the same versions.  16.0.6 was working ok.

**Comment by shrujalshah28** [comment]
Hi @legraphista 

Please take a look at this [demo](https://stackblitz.com/edit/typescript-jkdiik)

**Comment by legraphista** [comment]
Yes, I managed to pin down the issue. Looks like the definitions work on TS pre 3.5.3, but from 3.6.0 up are broken. I wonder how it managed to pass my local tests and the CI/CD pipeline on the repo too.

**Comment by shrujalshah28** [comment]
Resolved with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41976
