### ISSUE TITLE
[@types/lodash] README looks broken. What's correct?

### ISSUE THREAD

**Issue by whitphx** [DefinitelyTyped/DefinitelyTyped#41857]
@bczengel @chrootsu @stepancar

Hello, I tried to contribute `@types/lodash`, but got confused because the contents of https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/readme.md seems different from the actual situation.

Here are my confusions/questions.

## How to generate the files?
In the readme, developers are instructed to run `npm install` and `npm run generate`, which runs `ts-node generate-fp`. However, there is also `generate-all.sh` file and the comment in the file says:

> If some one want to update lodash modules, you must run this script under the same > dir where it lives.
> Or you can run them(generate-modules.ts) separately by hand

Which is correct? (`generate-all.sh` seems the right instruction, though.)

In the following, it is assumed `generate-all.sh` is correct.

## The generated files are different from the commited ones
For example, after `generate-all.sh` runs,  `types/lodash/tsconfig.json` is automatically updated (`generate-module.ts` seems to do this).
However, the auto-generated content was drastically different from the commited one:

```diff
         ],
         "noImplicitAny": true,
         "noImplicitThis": true,
-        "strictFunctionTypes": true,
         "strictNullChecks": true,
+        "strictFunctionTypes": true,
         "baseUrl": "../",
         "typeRoots": [
             "../"
         ],
         "types": [],
         "noEmit": true,
-        "forceConsistentCasingInFileNames": true,
-        "esModuleInterop": true
+        "forceConsistentCasingInFileNames": true
     },
     "files": [
         "index.d.ts",
-        "lodash-tests.ts"
+        "lodash-tests.ts",
+        "add.d.ts",
(...296 lines...)
+        "zipWith.d.ts"
```

In addition, a lot of `types/lodash.*/index.d.ts` files are also auto-generated with different contents from the commited ones:

```diff
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   ../../../package.json
        modified:   ../../lodash-es/index.d.ts
        modified:   ../../lodash-es/scripts/generate-modules.ts
        modified:   ../../lodash-es/tsconfig.json
        modified:   ../../lodash.add/index.d.ts
        modified:   ../../lodash.after/index.d.ts
(...283 lines...)
        modified:   ../common/common.d.ts
        modified:   ../common/function.d.ts
        modified:   ../fp.d.ts
        modified:   ../multiply.d.ts
        modified:   generate-modules.ts
        modified:   ../tsconfig.json
```

The diff is, for example, this: 
```
diff --git a/types/lodash.ary/index.d.ts b/types/lodash.ary/index.d.ts
index 1d44bac65a..d59ad17510 100644
--- a/types/lodash.ary/index.d.ts
+++ b/types/lodash.ary/index.d.ts
@@ -1,5 +1,5 @@
 // Type definitions for lodash.ary 4.1
-// Project: https://lodash.com
+// Project: http://lodash.com/
 // Definitions by: Brian Zengel <https://github.com/bczengel>, Ilya Mochalov <https://github.com/chrootsu>, Stepan Mikhaylyuk <https://github.com/stepancar>
 // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
 // TypeScript Version: 2.8
```

Is it ok to commit this auto-generated `tsconfig.json` and `types/lodash.*/index.d.ts`?
Are there some reasons why the auto-generated files are different from the committed ones and/or not commited newly?

For `types/lodash.*/index.d.ts` problem, I created a PR #41856.

## Type bugs in `generate-fp.ts`
When I ran `generate-all.sh`, `generate-fp.ts` is executed inside it and it raises the type errors like this:
```
/Users/tsuchiya/.nvm/versions/node/v10.16.0/lib/node_modules/ts-node/src/index.ts:421
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
generate-fp.ts:12:16 - error TS2307: Cannot find module 'fs'.

12 import fs from "fs";
                  ~~~~
generate-fp.ts:15:18 - error TS2307: Cannot find module 'path'.

15 import path from "path";
                    ~~~~~~
generate-fp.ts:57:53 - error TS7006: Parameter 'err' implicitly has an 'any' type.

57             fs.readdir(path.join("..", subfolder), (err, files) => {
                                                       ~~~
generate-fp.ts:57:58 - error TS7006: Parameter 'files' implicitly has an 'any' type.

57             fs.readdir(path.join("..", subfolder), (err, files) => {
                                                            ~~~~~
generate-fp.ts:63:45 - error TS7006: Parameter 'f' implicitly has an 'any' type.

63                 const filePaths = files.map(f => path.join("..", subfolder, f));
                                               ~
generate-fp.ts:126:55 - error TS7006: Parameter 'err' implicitly has an 'any' type.

126     fs.writeFile(path.join("..", "fp.d.ts"), fpFile, (err) => {
                                                          ~~~
generate-fp.ts:144:59 - error TS7006: Parameter 'err' implicitly has an 'any' type.

144     fs.writeFile(tsconfigPath, tsconfig.join(lineBreak), (err) => {
                                                              ~~~
generate-fp.ts:210:43 - error TS7006: Parameter 'err' implicitly has an 'any' type.

210         fs.writeFile(targetFile, output, (err) => {
                                              ~~~
```

This errors can be avoided by running the script by `npm run generate`, but it should be fixed.

## No explanation about `ts3.1`
There is no instruction about how to update files in `types/lodash/ts3.1`.
Are the files auto-generated by some scripts like `fp/*`, or can be changed by hand?

## Contributor name
It seems the contributors have to add their names not only to `types/lodash/index.d.ts` but also the template in `types/lodash/scripts/generate-modules.ts` in order to show the credits on the finally published packages.
I think this must be described in `types/lodash/readme.md` and the current contributors list in `types/lodash/index.d.ts` must be copied to the template.
How do you think?

**Comment by aj-r** [comment]
All good questions. Looks like the documentation hasn't been updated in a long time, feel free to sens a PR to update it.

> How to generate the files?

`generate-all.sh` is probably old, I would trust the advice in the readme.

> The generated files are different from the commited ones

It's possible that some people have edited files manually, instead of running the script. In that case, we should update the script, and possibly add a comment to those files so people know they're auto-generated. 

I'm not sure what's going on in `tsconfig.json` but it seems like the script is doing the wrong thing.

> Type bugs in generate-fp.ts

I don't have time to fix but feel free to create a PR.

> There is no instruction about how to update files in `types/lodash/ts3.1`. Are the files auto-generated by some scripts like `fp/*`, or can be changed by hand?

These files target TS>=3.1 (whereas files in the root target TS<=3.0). They are maintained separately, so when making a change, you need to update whichever version your issue applies to (or both). At a minimum, update the `ts3.1` types (unless of course you are fixing a bug that only happens in an old version of TS).

> It seems the contributors have to add their names not only to types/lodash/index.d.ts but also the template in types/lodash/scripts/generate-modules.ts in order to show the credits on the finally published packages.
I think this must be described in types/lodash/readme.md and the current contributors list in types/lodash/index.d.ts must be copied to the template.

Absolutely.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
