### ISSUE TITLE
[react-table] CellValue should be of generic D instead of any

### ISSUE THREAD

**Issue by waynevanson** [DefinitelyTyped/DefinitelyTyped#41864]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ggascoigne, @stramel

If you do not mention the authors the issue will be ignored.

I expect `cell.value` to be the generic type of `<D>`. Instead, it is the type of `any`.

I would like to change `export type CellValue = any` to `export type CellValue<D = any>= D`, or remove it complete and replace any reference to `CellValue` with `D`.

Is there any reason this is not the generic `<D>`?
I went through the types and didn't see any need for it to be `any` instead of `<D>` .

I'm happy to make the changes if they should be made.

**Comment by ggascoigne** [comment]
No that's not correct.

<D> is the data type of the individual rows of data that you pass to the table.  The Cell type is actually related to the return value of the column accessor, while this defaults to being the value of an individual object property, the acccessor can also be a function and so there are no guarantees as to its type.

**Comment by waynevanson** [comment]
Ahh I see. Thank you for your response.

I definitely prefer not to see this as any and I feel the only way to avoid the any is to use a generic for the Cell property.

This sounds like something that should be done, but Ill close it for now until the change is contributed.
