### ISSUE TITLE
[Request] Type definition for @auth0/auth0-spa-js

### ISSUE THREAD

**Issue by Crodaycat** [DefinitelyTyped/DefinitelyTyped#41874]
here it is: https://www.npmjs.com/package/@auth0/auth0-spa-js
Thanks.

**Comment by peterblazejewicz** [comment]
@Crodaycat 
it's written in the TypeScript already and ships its own typedfinitions:
https://github.com/auth0/auth0-spa-js/blob/master/package.json#L8
Do you have any issue using that types when you import library in your project?
