### ISSUE TITLE
@types/socketcluster update to v15

### ISSUE THREAD

**Issue by ChisholmKyle** [DefinitelyTyped/DefinitelyTyped#41893]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/socketcluster` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DanielRose 

If you do not mention the authors the issue will be ignored.

## Description

Socketcluster recently updated to v15. Code has been restructured based on `asyngular-client` and `asyngular-server` and prefix `SC` is now `AG`

@DanielRose thank you for adding the SCxxx types but it would be great if you can update to v15 with AGxxxx.

**Comment by DanielRose** [comment]
Ok, I'll take a look.

**Comment by DanielRose** [comment]
socketcluster itself changed into a cli-tool with version 15, so there are no type definitions which make sense. However, I updated the other related type-definitions, ex. socketcluster-server and socketcluster-client: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42068

**Comment by ChisholmKyle** [comment]
Thank you!!!

**Comment by DanielRose** [comment]
PR was merged, so you can close this :)

**Comment by ChisholmKyle** [comment]
Ok I started using it and looking good, except for the 'subscribeStateChange' listener data (see docs: https://socketcluster.io/docs/api-ag-client-socket/#events)

in [socketcluster-client/lib/clientsocket.d.ts:414](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a1039ae6e54bc66e06287f56d848192db43302b2/types/socketcluster-client/lib/clientsocket.d.ts#L414-L417) the `SubscribeStateChangeData` type should be

    interface SubscribeStateChangeData extends SubscribeData {
        channel: string;
        oldChannelState: AGChannel.ChannelState;
        newChannelState: AGChannel.ChannelState;
        subscriptionOptions: SubscribeOptions;
    }

I suppose I should create a new issue? Is there an easy way to amend your commit. Is another PR required?

**Comment by DanielRose** [comment]
Yup, my mistake. The PR is merged, so a new PR is needed. Do you want to do that?

**Comment by ChisholmKyle** [comment]
Would you mind doing the PR? I think the merge gets fast tracked when an author of the package makes the PR and I've never done one for DefinitelyTyped before.

Also, one other tiny thing came up:  for socketcluster-server, I think the option 'protocolVersion' is not required, see [socketcluster-server/server.d.ts:199-201](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ef627d674799f1b722e7666f2cc6653bfcf5aa23/types/socketcluster-server/server.d.ts#L199-L201)

**Comment by ChisholmKyle** [comment]
I made a new issue #42192

**Comment by jessetrinity** [comment]
The PR moves into the same fast lane if the author approves it too, and he seems pretty responsive :)
