### ISSUE TITLE
Definition Request: select2 4.0

### ISSUE THREAD

**Issue by nchen63** [DefinitelyTyped/DefinitelyTyped#4190]
Is anyone working on select2 4.0 typings? https://select2.github.io/announcements-4.0.html

**Comment by ashwinr** [comment]
+1

**Comment by krigsman** [comment]
+1

**Comment by scottasmith** [comment]
+1

**Comment by galuszkak** [comment]
This issue should be closed as those definitions are here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/select2/index.d.ts
