### ISSUE TITLE
@types/hapi__hapi: Fix RequestRoute.settings typings 

### ISSUE THREAD

**Issue by madtrick** [DefinitelyTyped/DefinitelyTyped#41936]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rafaelsouzaf, @jhsimms, @SimonSchick, @saboya, @lenovouser

--- 

After upgrading to Hapi v19 we saw some build errors and  we found that the problem lies in the typings of `request.route.settings`. With the current typings the object `request.route.settings` is [typed as `RouteSettings`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi__hapi/index.d.ts#L352) but `RouteSettings` lacks the `app` object (compared to `RouteOptions` which [does have it](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi__hapi/index.d.ts#L1988)). According to the docs, the `request.route.settings` is ["the route options object with all defaults applied."](https://hapi.dev/api/?v=19.0.5#-requestroute).

Shouldn't `request.route.settings` be typed as `RouteOptions`?

**Comment by saboya** [comment]
This was changed here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35867

Not sure if it was correct at the time or was an oversight.

**Comment by madtrick** [comment]
From what I see in hapi, the `route.settings` object exposes an `app` property https://github.com/hapijs/hapi/blob/74e523d68282838fbceca21d584df48ce6a3f181/lib/route.js#L99. Maybe @SimonSchick can help us understand the change he made in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35867

**Comment by SimonSchick** [comment]
Been a while but iirc route settings aren't the same as route options, hapi internally re-processes various options and 'normalizes' them for internal and external consumption.
If `app` was dropped in the process you're free to add it back I guess.

**Comment by saboya** [comment]
I just did, here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41968

I wrote a very simple hapi app to test this and `app` really is there, so I moved it to `CommonRouteProperties`

I believe this can be closed.

**Comment by madtrick** [comment]
> I believe this can be closed.

Yep, works now 🙇
