### ISSUE TITLE
[balanced-match] - Invalid type definition

### ISSUE THREAD

**Issue by lutherman** [DefinitelyTyped/DefinitelyTyped#41933]
I am using `balanced-match` **1.0.0** and `@types/balanced-match` **1.0.0**.
I tried the example of [@types/balanced-match/balanced-match-tests.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/balanced-match/balanced-match-tests.ts), but got the error as below:
```
/Users/XXX/repo/balanced-match-test-type/node_modules/balanced-match/index.js:26
  var ai = str.indexOf(a);
               ^

TypeError: Cannot read property 'indexOf' of undefined
    at range (/Users/XXX/repo/balanced-match-test-type/node_modules/balanced-match/index.js:26:16)
    at new balanced (/Users/XXX/repo/balanced-match-test-type/node_modules/balanced-match/index.js:7:11)
    at Object.<anonymous> (/Users/XXX/repo/balanced-match-test-type/index.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
``` 

And I found that [@types/balanced-match/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/balanced-match/index.d.ts) exports a class with two function:
```ts
//...

declare class Balanced {
    balanced(a: string|RegExp, b: string|RegExp, str: string): Output|void;

    range(a: string|RegExp, b: string|RegExp, str: string): Output|void;
}

export = Balanced;
```

However, the implementation of [balanced-match/index.js](https://github.com/juliangruber/balanced-match/blob/master/index.js) just exports a function with a sub-function, not a class:
```js
//...

module.exports = balanced;
function balanced(a, b, str) {
  //...
}

//...

balanced.range = range;
function range(a, b, str) {
  //...
}
```

Therefore, it causes a conflict between the type definition and the actual implementation.

When `const balanced = new Balanced();`, the actual implementation tries calling function `str.indexOf(a)` from undefined param `str`. It makes the test code fail at runtime.

----------------
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @adamzerella @weswigham

If you do not mention the authors the issue will be ignored.

**Comment by peterblazejewicz** [comment]
see: #42021

**Comment by lutherman** [comment]
Thank @peterblazejewicz

**Comment by lutherman** [comment]
> see: #42021

Thanks
