### ISSUE TITLE
[multer@1.4] why was multer.Instance removed?

### ISSUE THREAD

**Issue by lkho** [DefinitelyTyped/DefinitelyTyped#41970]
- [x] I tried using the `@types/multer@1.3.10` package and had no problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

The `Instance` interface was removed and the `declare class Multer` is not exported.
There is no where to reference the Multer instance.

```typescript
import multer from 'multer';
const x: multer.Instance = multer();
```

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f09d3f850c72391f75cc4c58364c31ee020b6ba0#diff-0b6c549b93259dc4abbf4d6899537232L65-L77

**Comment by peterblazejewicz** [comment]
The Multer class could be probalby just an interface within `multer` namespace, so that would be corect:
```ts
import multer from 'multer';
const x: multer.Multer = multer();
```
`Instance` can be aliased to `Multer`, `type Instance = Multer;`, for backward compatibility:
```ts
import multer from 'multer';
const x: multer.Instance = multer();
```
sounds OK?

**Comment by lkho** [comment]
but the Multer class is declared outside multer namespace, and is not exported. so that `import { Multer } from 'multer'` or simply referencing the class `Multer` from outside won't work.

**Comment by darkobits** [comment]
If using TypeScript 2.8 or above, you can use the built-in `ReturnType` helper to extract the return type of from the multer factory function thusly:

```ts
import multer from 'multer';

const x: ReturnType<typeof multer> = multer(...);
```

I would consider this a temporary work-around until something like `multer.Instance` is re-added to the type defs.

**Comment by restjohn** [comment]
The `ReturnType` trick does not work for me.  I'm using TypeScript 3.9.  I believe the Multer class declaration needs to change to an exported interface.
