### ISSUE TITLE
[jquery] Type definition order "wrong" for the common case

### ISSUE THREAD

**Issue by aried3r** [DefinitelyTyped/DefinitelyTyped#41980]
- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu
@borisyankov
@choffmeister
@Steve-Fenton
@Diullei
@tasoili
@jasons-novaleaf
@seanski
@Guuz
@ksummerlin
@basarat
@nwolverson
@derekcicerone
@AndrewGaspar
@seikichi
@benjaminjackman
@s093294
@JoshStrobl
@johnnyreilly
@DickvdBrink
@King2500
@terrymun

Two type definitions overlap because they both accept a `string` as their first parameter in `$()`. Namely the [definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e8899e3dd449af9fa8c719ed44e100260a3201eb/types/jquery/JQueryStatic.d.ts#L140) for [this one](https://api.jquery.com/jQuery/#jQuery-selector-context) and the [definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e8899e3dd449af9fa8c719ed44e100260a3201eb/types/jquery/JQueryStatic.d.ts#L101) for [this one](https://api.jquery.com/jQuery/#jQuery-html-ownerDocument) overlap, and return the wrong type documentation for – what I assume is – the common case.
I assume there's no way to have TypeScript discriminate between the two, but could we exchange the order of the two to have Visual Studio Code return the correct type documentation?

Example:
![Screenshot 2020-01-30 at 16 13 01](https://user-images.githubusercontent.com/1301152/73464760-b41e1780-437f-11ea-9626-d188b4b84816.png)

Btw, the type definition file contains 406 [zero width spaces](https://www.fileformat.info/info/unicode/char/200b/index.htm), should these be left in there? I assume they come from copying the documentation from api.jquery.com.

**Comment by martin-badin** [comment]
@aried3r What do you think about this?
```typescript
/**
  * Creates DOM elements on the fly from the provided string of raw HTML.
  * @param html_selector _&#x40;param_ `html_selector`
  * <br>
  * * `html (ownerDocument)` — A string of HTML to create on the fly. Note that this parses HTML, not XML. <br>
  * * `selector (context)` — A string containing a selector expression.
  * @param ownerDocument_context _&#x40;param_ `ownerDocument_context`
  * <br>
  * * `ownerDocument` — A document in which the new elements will be created. <br>
  * * `context` - A DOM Element, jQuery to use as context.
  * @see \`{@link https://api.jquery.com/jQuery/#jQuery-selector-context }\`
  * @see \`{@link https://api.jquery.com/jQuery/#jQuery-html-ownerDocument }\`
  * @since 1.0
  */
// <K extends keyof HTMLElementTagNameMap>(html_selector: K, ownerDocument_context?: Element | Document | JQuery | JQuery.Selector): JQuery<HTMLElementTagNameMap[K]>;
// <K extends keyof SVGElementTagNameMap>(html_selector: K, ownerDocument_context?: Element | Document | JQuery | JQuery.Selector): JQuery<SVGElementTagNameMap[K]>;
// tslint:disable-next-line:no-unnecessary-generics
<T extends Element = HTMLElement>(html_selector: JQuery.Selector, ownerDocument_context?: Element | Document | JQuery | JQuery.Selector): JQuery<T>;
/**
  * Creates DOM elements on the fly from the provided string of raw HTML.
  * @param html A string of HTML to create on the fly. Note that this parses HTML, not XML.
  * @param attributes An object of attributes, events, and methods to call on the newly-created element.
  * @see \`{@link https://api.jquery.com/jQuery/#jQuery-html-attributes }\`
  * @since 1.4
  */
// tslint:disable-next-line:no-unnecessary-generics
<T extends Element = HTMLElement>(html: JQuery.htmlString, attributes: JQuery.PlainObject): JQuery<T>;
```

**Comment by aried3r** [comment]
I believe that would work!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
