### ISSUE TITLE
[jquery] Problem when using JQuery with generic typing

### ISSUE THREAD

**Issue by King2500** [DefinitelyTyped/DefinitelyTyped#41999]
- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x]  Authors: @leonard-thieu @borisyankov @choffmeister @Steve-Fenton @Diullei @tasoili @jasons-novaleaf @seanski @Guuz @ksummerlin @basarat @nwolverson @derekcicerone @AndrewGaspar @seikichi @benjaminjackman @s093294 @JoshStrobl @johnnyreilly @DickvdBrink @terrymun

I tried the following and assume that the return type of the `find` method is wrong:
```ts
let $element: JQuery<HTMLFormElement> = $('.myForm');
$element.find('.child') // returns JQuery<HTMLFormElement> but should be JQuery<HTMLElement> or similar
// consequence:
$element.find('input.child').get(0) // returns HTMLFormElement which is wrong when you try to access Input-specific properties.

$element.find('li') // should be JQuery<HTMLLIElement> 
```
Current definition:
```ts
interface JQuery<TElement = HTMLElement> extends Iterable<TElement> {
    //...
    find(selector_element: JQuery.Selector | Element | JQuery): this;
    //...
}
```
First I suggest to change the return type for `find` method from `this` to `JQuery<TDecendent = HTMLElement>` if that is possible... ?

Maybe we can also have overloaded find methods with some specific cases when using explicit HTML tag-names like:

```ts
$element.find('li') // JQuery<HTMLLIElement>
$element.find('tr') // JQuery<HTMLTableRowElement>
$element.find('input') // JQuery<HTMLInputElement>
// ... and so on for all know HTMLElement sub types/tags ?
```
with
```ts
find('li'): JQuery<HTMLLIElement>;
find('tr'): JQuery<HTMLTableRowElement>;
find('input'): JQuery<HTMLInputElement>;
// ... and so on...
```

What do you think?
Are there any other similar methods where this problem applies?

**Comment by aliemre1990** [comment]
I am facing same issue. I have a table element. I need to get rows and iterate through it. But find method return type is HTMLTableElement

**Comment by martin-badin** [comment]
The type definition is wrong. That is correct.
`find<T extends HTMLElement>(selector_element: JQuery.Selector | T | JQuery<T>): JQuery<T>;`
