### ISSUE TITLE
[@types/lodash] `_.uniqBy` - An argument for 'iteratee' was not provided.

### ISSUE THREAD

**Issue by Vadorequest** [DefinitelyTyped/DefinitelyTyped#42000]
- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu  @stepancar 

The following code:

```ts
studentSolutionGroups[index] = {
      ...group,
      solutions: uniqBy(group.solutions),
    };
```

Generates the following error:
```
TS2554: Expected 2 arguments, but got 1.  
array.d.ts(1723, 54): An argument for 'iteratee' was not provided
```

**But the `iteratee` should be optional.**

> [iteratee=_.identity] (Function): The iteratee invoked per element.

Doc: https://lodash.com/docs/4.17.15#uniqBy

---

index.d.ts
```ts
// Type definitions for lodash.uniqBy 4.7
// Project: https://lodash.com
// Definitions by: Brian Zengel <https://github.com/bczengel>, Ilya Mochalov <https://github.com/chrootsu>, Stepan Mikhaylyuk <https://github.com/stepancar>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.8

// Generated from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/scripts/generate-modules.ts

import { uniqBy } from "lodash";
export = uniqBy;

```

@types/lodash/common/array.d.ts
```ts
    interface LoDashStatic {
        /**
         * This method is like `_.uniq` except that it accepts `iteratee` which is
         * invoked for each element in `array` to generate the criterion by which
         * uniqueness is computed. The iteratee is invoked with one argument: (value).
         *
         * @category Array
         * @param array The array to inspect.
         * @param [iteratee=_.identity] The iteratee invoked per element.
         * @returns Returns the new duplicate free array.
         * @example
         *
         * _.uniqBy([2.1, 1.2, 2.3], Math.floor);
         * // => [2.1, 1.2]
         *
         * // using the `_.property` iteratee shorthand
         * _.uniqBy([{ 'x': 1 }, { 'x': 2 }, { 'x': 1 }], 'x');
         * // => [{ 'x': 1 }, { 'x': 2 }]
         */
        uniqBy<T>(
            array: List<T> | null | undefined,
            iteratee: ValueIteratee<T>
        ): T[];
    }
```

**Comment by bodinsamuel** [comment]
I think this is okay like that, the documentation is specified as-is:

> This method is like _.uniq except that it accepts iteratee

So even if iteratee is showed as optional it looks like it's not and you should simply use `_.uniq()` instead.

**Comment by Vadorequest** [comment]
Okay, I understand better now, thank you.
