### ISSUE TITLE
[@types/aws-lambda] Missing key in Request context.

### ISSUE THREAD

**Issue by mrjackyliang** [DefinitelyTyped/DefinitelyTyped#42049]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @darbio, @skarum, @StefH, @tobyhede, @buggy, @y13i

If you do not mention the authors the issue will be ignored.

=====

`APIGatewayEventRequestContext` is missing a `protocol` key of type `string`. Mine shows this inside the `requestContext` object:
```json
{
  "protocol": "HTTP/1.1",
}
```

**Comment by simonbuchan** [comment]
Sure, this seems easy enough to add in a PR. I'll look at it after #42080 gets merged.

**Comment by mrjackyliang** [comment]
@simonbuchan Thanks!
