### ISSUE TITLE
[@types/passport] cannot extend User interface

### ISSUE THREAD

**Issue by ziofat** [DefinitelyTyped/DefinitelyTyped#42055]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/passport` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi @enaeseth @theigor @tlaziuk 

In @types/passport a User interface is defined in for `requset.user`. However it is a empty interface and I cannot use it in my code.

```ts
function(req: Request, res: Response) {
    console.log(req.user.uid); // Property 'uid' does not exist on type 'User'.
}
```

How can I extends the interface? As far as I know I can only add new fields into an existing interface. User is a complex entity and I don't want to have multiple definitions.

**Comment by bodinsamuel** [comment]
You can extend the User interface by doing this:
```ts
declare global {
  namespace Express {
    export interface User {
      foobar: string;
    }
  }
}
```

**Comment by ziofat** [comment]
@bodinsamuel Thanks, it works.

**Comment by jlebras** [comment]
If you have an already existing `User` class you can tell typescript to use it like this:

```
import { User as AppUser } from '<PATH_TO_YOUR_USER_CLASS>';

declare global {
    namespace Express {
        class User extends AppUser {}
    }
}
```

It may be basic stuff but I spend SOME time to find the correct way to do this, so I thought I would share it here.

**Comment by verycosy** [comment]
@jlebras It works well. Before see your comment, I waste a lot of time. Thanks !

**Comment by yoricktran** [comment]
> If you have an already existing `User` class you can tell typescript to use it like this:
> 
> ```ts
> import { User as AppUser } from '<PATH_TO_YOUR_USER_CLASS>';
> 
> declare global {
>     namespace Express {
>         class User extends AppUser {}
>     }
> }
> ```
> 
> It may be basic stuff but I spend SOME time to find the correct way to do this, so I thought I would share it here.

Where do you put this?

**Comment by HundredPercentCoverage** [comment]
I know this thread is old but I am also having this problem, and would like to know where folks put the type declaration file. For instance, I have mine in `types/express/index.d.ts`. The app runs if I add `"files": ["types/express/index.d.ts"],` to the `tsconfig.json`, but I am getting type errors in the IDE. It almost looks like it is preferring the Passport-created Express.User type against the one I have declared. If I take the line out of `tsconfig.json`, I no longer get type errors, but the app throws a TS compilation error when I try to run it.

**Comment by HundredPercentCoverage** [comment]
For anyone else with my issue, I solved it by updating the `tsconfig.json` file to remove the `files` part and added my `types` folder to the `typeRoots` field:
```json
{
  "compilerOptions": {
    "typeRoots": ["./types","./node_modules/@types"], 
  }
}
```

**Comment by taiwanhua** [comment]
> > If you have an already existing `User` class you can tell typescript to use it like this:
> > ```ts
> > import { User as AppUser } from '<PATH_TO_YOUR_USER_CLASS>';
> > 
> > declare global {
> >     namespace Express {
> >         class User extends AppUser {}
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It may be basic stuff but I spend SOME time to find the correct way to do this, so I thought I would share it here.
> 
> Where do you put this?

How should I handle it if I'm using an interface?

**Comment by MR5553** [comment]
> You can extend the User interface by doing this:
> 
> declare global {
>   namespace Express {
>     export interface User {
>       foobar: string;
>     }
>   }
> }

buddy are you drunken
have you ever you passport js with typescript in your life?

lets connect i'll show
