### ISSUE TITLE
[@types/webpack] missing "object" in DefinePlugin.CodeValuePrimitive

### ISSUE THREAD

**Issue by StefanoMagrassi** [DefinitelyTyped/DefinitelyTyped#42063]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/webpack` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @danielthank 

It seems that the `DefinePlugin.CodeValuePrimitive` definition lacks of a generic "object" type, even if it is one of the possible values (https://webpack.js.org/plugins/define-plugin/#usage - "If the value is an object all keys are defined the same way")

**Comment by danielthank** [comment]
I will fix it. Sorry for that.
