### ISSUE TITLE
[@types/node@13] global.Promise = Bluebird gives Symbol.species missing error

### ISSUE THREAD

**Issue by medington** [DefinitelyTyped/DefinitelyTyped#42084]
There appears to be a new incompatibility between the @types/node@13 with Bluebird Promises.

In @types/node@12 release it was possible to assign to the global Promise object using:

`global.Promise = bluebird`

However, in @types/node@13 this now generates a compiler error:
```
src/index.ts:4:1 - error TS2741: Property '[Symbol.species]' is missing in type 'typeof Bluebird' but required in type 'PromiseConstructor'.

global.Promise = bluebird

  node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts:173:14
    173     readonly [Symbol.species]: PromiseConstructor;
```

We have dependabot configured for our repo and this same issue has appeared in every v13 release of `@types/node` so far.

**Steps to reproduce:**
I created a [test project](https://github.com/medington/node-typing-issue/blob/master/src/index.ts) which makes this easy to reproduce:

```
git clone git@github.com:medington/node-typing-issue.git && cd node-typing-issue
npm install
npm run build
```
----
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/nodes@13` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick

**Comment by SimonSchick** [comment]
This appears to be due to v13 depending on new TS libs (which would be the root issue here) and that's not something I can (or am willing to) fix.
The easiest workaround is probably `global.Promise = <any>Bluebird`.

**Comment by medington** [comment]
Thanks for the quick feedback @SimonSchick ! Totally understood. I mostly wanted to get this issue logged so that others who may run into it will have a reference. I was honestly a bit surprised no one else has in the month since v13 was released.

For our project, I'll probably install `bluebird-global` which is a micro package that makes the assignment. Advantage there is you can put that import first and ensure it's replaced as early in app startup as possible. It'll also avoid the `<any>` cast and the directive to ignore it in strict mode with `noImplicitAny`.

I actually spent some time looking at the diffs between the v12 and v13 source and could not for the life of me see anything obvious in the changes to account for the error. I suspected it may have been related to a lib change, but don't know enough about how those get pulled in to confirm that.

**Do you think that this is something that I should also report to Bluebird typing authors?** Is this something that they can / should try to address? At the very least it might be worth a readme entry or comment somewhere in the code.

Thanks again for you time and your contribution! Have a great day.

**Comment by SimonSchick** [comment]
I guess bluebird (not the typings) could specify `Symbol.species` which would make the implementations compatible again and the typings could be adjusted accordingly.

Personal note: I find `Symbol.species` kind of confusing, it seems to be more or less an alias of the `constructor` property.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
