### ISSUE TITLE
Updated PR stuck at "needs author attention"

### ISSUE THREAD

**Issue by alvaromartmart** [DefinitelyTyped/DefinitelyTyped#42086]
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

I pushed the reviewer-requested changes to my PR (#41279) a while ago but it's still stuck at the "needs author attention" column of the project board. I don't know if this usuarlly takes so longas the first review came very soon, did I miss anything in the process?

- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @RyanCavanaugh.

**Comment by peterblazejewicz** [comment]
@alvaromartmart 
There is a way to push this changes into release, no worries.
Can you review my recent comments? Folks from MS (especially some of them) are busy and could not respond to all GitHub notifications promptly, so sry for delay!

**Comment by alvaromartmart** [comment]
Thank you @peterblazejewicz!

Ironically, now it's me who's been too busy lately to review my own PR 😅. I will review your comments ASAP.

**Comment by alvaromartmart** [comment]
Hi, my [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41279) is still awaiting review and I don't know how to move forward. Should I close the PR and open a new one so new reviewers are invited?? :sweat_smile:
