### ISSUE TITLE
mkdirp typings are for 0.x.0 versions, but 1.0 has breaking changes

### ISSUE THREAD

**Issue by AArnott** [DefinitelyTyped/DefinitelyTyped#42122]
The `mkdirp` package's recent 1.0 release completely changed the method signatures, making the `@types/mkdirp` typings for it incorrect. Node terminates (with no error) when we follow the typings, oddly.

Please update the typings for the new API.

**Comment by peterblazejewicz** [comment]
@AArnott 
Can you check changes from #42136? Thanks!
