### ISSUE TITLE
[@types/testing-library__react] The types provided by @testing-library/react for act() are wrong because of an old dependency.

### ISSUE THREAD

**Issue by VanTanev** [DefinitelyTyped/DefinitelyTyped#42129]
After installing `@testing-library/react@9.4.0`, `@types/testing-library__react@9.1.2` is installed.

Its definition for `act()` falls back to `@types/react-dom`, however it uses version `16.8.4` instead of the current version, `16.9.5`.

The difference is:
```typescript
// @types/react-dom @ 16.8.4
// node_modules/@types/testing-library__react/node_modules/@types/react-dom/test-utils/index.d.ts
export function act(callback: () => void | undefined): DebugPromiseLike | {};
```

```typescript
// @types/react-dom @ 16.9.5
export function act(callback: () => void | undefined): void;
export function act(callback: () => Promise<void | undefined>): Promise<undefined>;
```

The second definition of `act()` is required for the following usage pattern:
```typescript
// Argument of type '() => Promise<void>' is not assignable to parameter of type '() => void | undefined'.
await act(async () => {
  // [...]
})
```

---

We probably just need a new patch version of this module to be released for it to pick up the newer version of the `@types/react-dom` dependency? I honestly do not understand how DefinitelyTyped dependencies work.

I don't even understand where this dependency is coming from, given that `@types/testing-library__react` doesn't have a `package.json`?

  - Authors:  @alexkrolick   @kentcdodds    @eps1lon @weyert    @ifiokjr    @danieljcafonso

**Comment by peterblazejewicz** [comment]
> I honestly do not understand how DefinitelyTyped dependencies work.

This seems to be direct dependency of the main module:
https://github.com/testing-library/react-testing-library/blob/master/package.json#L50

**Comment by VanTanev** [comment]
I'm talking about `node_modules/@types/testing-library__react/node_modules/@types/react-dom`

This is the offending old version of `@types/react-dom` that breaks the types. I don't understand where it's version comes from. It seems like it's form here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/testing-library__react/tsconfig.json#L15 + here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/testing-library__react/index.d.ts#L13, and the version of the release module `package.json` is the latest that was available at the time when `@types/testing-library__react` was packaged.

**Comment by eps1lon** [comment]
Try removing the entry for types/react-dom from your lockfile and run install again. This should install the latest version of types/react-dom.

**Comment by VanTanev** [comment]
@eps1lon You are correct. Turns out that this was a yarn issue. The fix was to run:

```bash
yarn upgrade @testing-library/react
```

Note that `yarn install` did not work on its own, as it upgrades `@testing-library/react`, but not its transitive deps:
```
// does not upgrade transitive deps, we're left with old version of @types/react-dom!
yarn install @testing-library/react
```

**Comment by eps1lon** [comment]
> Turns out that this was a yarn issue. 

This is correct behavior. yarn will not update locked indirect dependencies without being told so.

Didn't know yarn upgrade fixes indirect dependencies as well. Removing the lockfile entry does the same thing.

**Comment by VanTanev** [comment]
By "issue," I meant "originating from yarn dependency handling," and not really "a bug."

I think the `yarn upgrade` approach is better than manually editing a [checks notes] 15kloc file.
