### ISSUE TITLE
Definition Request yahoo/fluxible

### ISSUE THREAD

**Issue by umidbekkarimov** [DefinitelyTyped/DefinitelyTyped#4213]
https://github.com/yahoo/fluxible it's also depend on https://github.com/yahoo/dispatchr

**Comment by craz-dom** [comment]
I will be start to do it on this holidays.

**Comment by snowcxt** [comment]
How's it going?

**Comment by VictorGa** [comment]
Is somebody working on this request already?

**Comment by umidbekkarimov** [comment]
Done in #6270

**Comment by VictorGa** [comment]
Awesome thanks :+1:

**Comment by snowcxt** [comment]
Why the query result is zero?

![image](https://cloud.githubusercontent.com/assets/1463415/10561323/c3e1c092-74d8-11e5-915a-470e61200698.png)

**Comment by umidbekkarimov** [comment]
@snowcxt pr didn't merged yet, need to add some test cases, but i don't have time now. 

Any pr from you will be appratiated.
