### ISSUE TITLE
Docs of auth0-js says it should be user_metadata and @types says it should be userMetaData

### ISSUE THREAD

**Issue by juliopiubello** [DefinitelyTyped/DefinitelyTyped#42157]
Docs: https://auth0.com/docs/libraries/auth0js/v9#signup

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cbcfdd4b12b863a82f5f1903c47fe22fa3b6975c/types/auth0-js/index.d.ts#L846

**Comment by peterblazejewicz** [comment]
@juliopiubello 
I believe both are correct, as they aliased the usage:
https://github.com/auth0/auth0.js/blob/master/src/authentication/db-connection.js#L53
Let me ask them which shuld be promoted,
Thanks!

**Comment by peterblazejewicz** [comment]
x-ref: auth0/auth0.js#1081

**Comment by juliopiubello** [comment]
@peterblazejewicz thanks!
