### ISSUE TITLE
Socketcluster small fixes for channel and options in v15

### ISSUE THREAD

**Issue by ChisholmKyle** [DefinitelyTyped/DefinitelyTyped#42192]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/socketcluster-client` package and had problems.
- [x] I tried using the `@types/socketcluster-server` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DanielRose 

If you do not mention the authors the issue will be ignored.

## Description

In `socketcluster-client`, the 'subscribeStateChange' listener data has a problem (see docs: https://socketcluster.io/docs/api-ag-client-socket/#events). In [socketcluster-client/lib/clientsocket.d.ts:414](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a1039ae6e54bc66e06287f56d848192db43302b2/types/socketcluster-client/lib/clientsocket.d.ts#L414-L417) the `SubscribeStateChangeData` type should be

    interface SubscribeStateChangeData extends SubscribeData {
        oldChannelState: AGChannel.ChannelState;
        newChannelState: AGChannel.ChannelState;
    }

In `socketcluster-server`, the option 'protocolVersion' should be optional, see [socketcluster-server/server.d.ts:199-201](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ef627d674799f1b722e7666f2cc6653bfcf5aa23/types/socketcluster-server/server.d.ts#L199-L201). It should have the `?` as follows:

    // Can be 1 or 2. Version 1 is for maximum backwards
    // compatibility with SocketCluster clients.
    protocolVersion?: 1 | 2;

**Comment by ChisholmKyle** [comment]
Looks like they just bumped the version number again to 16! I don't think many API changes happened for types though

**Comment by DanielRose** [comment]
I'll take a look!

**Comment by DanielRose** [comment]
PR is #42366

**Comment by ChisholmKyle** [comment]
Thank you :+1:
