### ISSUE TITLE
there is no any explain in amqplib

### ISSUE THREAD

**Issue by jikhww** [DefinitelyTyped/DefinitelyTyped#42206]
If you know how to fix the issue, make a pull request instead.

- [*] I tried using the `@types/amqplib` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [*] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @abreits @mnahkies @nfantone @nickzelei 

i m a new guy use rabbitmq with amqplib,but the @types/amqplib did not had any explain,i dont understand what means.
for example:
bindExchange(destination: string, source: string, pattern: string, args?: any): Promise<Replies.Empty>;
    unbindExchange(destination: string, source: string, pattern: string, args?: any): Promise<Replies.Empty>;

**Comment by mnahkies** [comment]
These are just type definitions, please see library documentation here http://www.squaremobius.net/amqp.node/

**Comment by jikhww** [comment]
Well, thank you very much. If there is, it would be better
