### ISSUE TITLE
[@types/echarts] color type error with v4.6.0

### ISSUE THREAD

**Issue by qiwang97** [DefinitelyTyped/DefinitelyTyped#42212]
- [x] I tried using the `@types/echarts` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @xieisabug  @AntiMoron @Ovilia @Roman

echarts supports  [liner gradient](https://echarts.apache.org/en/option.html#series-radar.areaStyle.color) now while the type of color is still `string`
```
// Linear gradient. First four parameters are x0, y0, x2, and y2, each ranged from 0 to 1, standing for percentage in the bounding box. If global is `true`, then the first four parameters are in absolute pixel positions.
color: {
    type: 'linear',
    x: 0,
    y: 0,
    x2: 0,
    y2: 1,
    colorStops: [{
        offset: 0, color: 'red' // color at 0% position
    }, {
        offset: 1, color: 'blue' // color at 100% position
    }],
    global: false // false by default
}
```

```
 areaStyle?: {

                /**
                 * Fill color.
                 *
                 * > Color can be represented in RGB, for example `'rgb(128,
                 * 128, 128)'`.
                 * RGBA can be used when you need alpha channel, for example
                 * `'rgba(128, 128, 128, 0.5)'`.
                 * You may also use hexadecimal format, for example `'#ccc'`.
                 * Gradient color and texture are also supported besides single
                 * colors.
                 * >
                 * > [see doc](https://echarts.apache.org/en/option.html#series-radar.radar.areaStyle)
                 *
                 *
                 * @default
                 * "#000"
                 * @see https://echarts.apache.org/en/option.html#series-radar.areaStyle.color
                 */
                color?: string;
}
```

please fix it
thanks

**Comment by qiwang97** [comment]
please alse check those [linestyle](https://echarts.apache.org/zh/option.html#series-line.lineStyle) and [itemstyle](https://echarts.apache.org/zh/option.html#series-line.itemStyle)

**Comment by mancoxu** [comment]
why n fix it ??????

**Comment by vortesnail** [comment]
still not fix? 4.9.0

**Comment by SteppingRazor** [comment]
> still not fix? 4.9.0
I've made a pull rewuest with fix for this issue almost a month ag, but noone approved/checked this yet.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by chenhengzhi666** [comment]
It still hasn't been repaired

**Comment by chenhengzhi666** [comment]
This problem is still not fixed !
