### ISSUE TITLE
[@types/react-loadable]: `loading` component prop type need to be loosen.

### ISSUE THREAD

**Issue by janzenz** [DefinitelyTyped/DefinitelyTyped#42259]
- [x] I tried using the @types/react-loadable package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for StackOverflow. (Please ask any appropriate questions there).
- [x] Mention the authors (see Definitions by: in index.d.ts) so they can respond. @Jessidhia @odensc @ianks @tlaziuk @iMobs
---
The loading component seems to strictly require `LoadingComponentProps` within its prop types. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/752136c29dec6f1e559dfc62f6acba08f207c280/types/react-loadable/index.d.ts#L31

According to the [react-loadable docs](https://github.com/jamiebuilds/react-loadable#creating-a-great-loading-component), the component can simply return a simple component even without props and even a `null`.

Another problem arises when the loading component is decorated by another HOC, for example:

```typescript
import { injectIntl, IntlShape } from 'react-intl';
import * as ReactLoadable from 'react-loadable';

type IProps = { intl: IntlShape };

const LoadingComponentWithIntl = injectIntl((props: IProps) => <LoadingComponent />)

ReactLoadable({
  loading: LoadingComponentWithIntl
});
```
The code above throws a type error:
```
{
Type 'FC<WithIntlProps<IProps>> & { WrappedComponent: ComponentType<IProps>; }' is not assignable to type 'ComponentType<LoadingComponentProps>'.
Type 'FC<WithIntlProps<IProps>> & { WrappedComponent: ComponentType<IProps>; }' is not assignable to type 'FunctionComponent<LoadingComponentProps>'.
```

I think it could be solved by changing the prop type from:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/752136c29dec6f1e559dfc62f6acba08f207c280/types/react-loadable/index.d.ts#L31

to more generic type:

```typescript
// Utility types found in:
// https://github.com/typescript-cheatsheets/react-typescript-cheatsheet/blob/master/HOC.md#section-0-full-hoc-example
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
type Optionalize<T extends K, K> = Omit<T, keyof K>;

// This simply makes LoadingComponentProps keys optional.
loading: React.ComponentType<Optionalize<T, LoadingComponentProps>>;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
