### ISSUE TITLE
Package Install Error - Visual Studio 2015 RC

### ISSUE THREAD

**Issue by aliveli186** [DefinitelyTyped/DefinitelyTyped#4241]
Install-Package angularjs.TypeScript.DefinitelyTyped
Attempting to gather dependencies information for package 'angularjs.TypeScript.DefinitelyTyped.3.4.9' with respect to project targeting '.NETFramework, Version=v4.5'
Install-Package : Response status code does not indicate success: 400 (One of the request inputs is out of range.).
At line:1 char:1
+ Install-Package angularjs.TypeScript.DefinitelyTyped
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by aliveli186** [comment]
Just to clearify that it's not NuGet issue,
jquery.TypeScript.DefinitelyTyped 2.2.4 Package install without problem.

**Comment by vvakame** [comment]
@staxmanade

**Comment by staxmanade** [comment]
Not sure...

Does this help? http://stackoverflow.com/questions/28842138/vs-2015-ctp-6-nuget-package-source

**Comment by arunamigo** [comment]
opening VS in administrator mode worked for me!

**Comment by lindexi** [comment]
When install json ,the nuget command say 

    + Install-Package Json
    + ~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
        + FullyQualifiedErrorId :     NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageComma  nd
