### ISSUE TITLE
[@types/jest] expect().not doesn't have a type

### ISSUE THREAD

**Issue by lixu-myob** [DefinitelyTyped/DefinitelyTyped#42439]
If you know how to fix the issue, make a pull request instead.

- [ X ] I tried using the `@types/xxxx` package and had problems.
- [ X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ X ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @NoHomey @jwbay @asvetliakov 

When I use `expect().not`, I received an error:
```
Property 'not' does not exist on type 'ChainedMatchers<ShallowWrapper<HTMLAttributes, any, Component<{}, {}, any>>>'.ts(2339)
```
It seems that expect().not is not typed properly, although `expect.not` works just as fine. Can we add type for `expect().not`?

**Comment by G-Rath** [comment]
`not` is typed: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8d98dc86af7dabaa430b11f8a1d8f2a00e07acc9/types/jest/index.d.ts#L691-L693

Could you provide a reproduction repo?

**Comment by lixu-myob** [comment]
@G-Rath Thanks for your reply. I realized that the error was actually because of `jest-chain`. The error message was a bit misleading. I solved it by adding `import 'jest-chain';` to my `global.d.ts`
