### ISSUE TITLE
[@types/victory] TypeScript types don't work 100% with the latest package version

### ISSUE THREAD

**Issue by kaiyoma** [DefinitelyTyped/DefinitelyTyped#42436]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @asvetliakov @snerks @Havret @alreadyExisted @jlismore @stackbuilders @ibarrae @dominictwlee @veddermatic @alecf

If you do not mention the authors the issue will be ignored.

I'm using the following versions in my project:

    "victory": "34.0.1",
    "@types/victory": "33.1.4",

If I upgrade to the latest Victory release (34.1.1) and run the type checker, I get a new error that wasn't present before:

```
node_modules/@types/victory/index.d.ts:874:18 - error TS2403: Subsequent variable declarations must have the same type.
 Variable 'VictoryTheme' must be of type 'VictoryThemeInterface', but here has type 'VictoryThemeInterface'.

874     export const VictoryTheme: VictoryThemeInterface;
                     ~~~~~~~~~~~~

  node_modules/victory-core/lib/index.d.ts:368:14
    368 export const VictoryTheme: VictoryThemeInterface;
                     ~~~~~~~~~~~~
    'VictoryTheme' was also declared here.
```

**Comment by ibarrae** [comment]
As you can see in this [PR](https://github.com/FormidableLabs/victory/pull/1481), they moved all the typescript definitions from `DefinitelyTyped` to `victory` :thinking: and following what _boygirl_ mentions:
> This PR adds typescript types from the definitely-typed project so that we can maintain them more easily going forward.

I think the correct way to solve this is to remove **@types/victory** from your project since this could be deprecated in the future @kaiyoma

**Comment by kaiyoma** [comment]
Ah yes, you're totally right. Once I dropped `@types/victory` everything worked again. Thanks for the quick response!
