### ISSUE TITLE
@types/googlemaps OverlayView.preventMapHitsAndGesturesFrom is missing

### ISSUE THREAD

**Issue by Bat-Orshikh** [DefinitelyTyped/DefinitelyTyped#42515]
`OverlayView.preventMapHitsAndGesturesFrom` method is missing. So without calling this method on overlay, When I click my created overlay the click event triggers on the map too…

This method is called on google map official example and it used `OverlayView.preventMapHitsAndGesturesFrom` to prevent map events.
https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/examples/overlay-popup
https://jsfiddle.net/81gs39uh/
- [X] I tried using the `@types/googlemaps` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Authors:
@tyv  @gshigeto @simonhaenisch 
Could you help me on that asap?
Or do you know how to add this method on typescript type definition?

**Comment by tyv** [comment]
Hi! 
I am not the author, I contributed few lines at the typings. 

the link to jsfiddle returns 404, but there is documentation for the `OverlayView.preventMapHitsAndGesturesFrom`
https://developers.google.com/maps/documentation/javascript/reference/overlay-view

If you want it asap, you can contribute.

**Comment by Bat-Orshikh** [comment]
Hi
I updated the links you can check it.
