### ISSUE TITLE
Problem with D3.min and D3.max

### ISSUE THREAD

**Issue by DavidBanksNZ** [DefinitelyTyped/DefinitelyTyped#4251]
Using Visual Studio Code, I imported the D3 typescript definition but have run into problems using d3.min and d3.max. It keeps saying the results of these function calls are objects, but they are actually numbers. Screenshot shows the problem

![vsc-d3min](https://cloud.githubusercontent.com/assets/7742102/7438915/0d6247c4-f0c1-11e4-97ab-887a4502d577.jpg)

**Comment by vvakame** [comment]
@DavidBanksNZ please send a PR. I'll review it.

**Comment by tomwanzek** [comment]
As part of some legacy D3v3 issue clean-up, can this issue be please closed?

D3v4 has been released and supported with actively maintained definitions for several months now, so it would be great to have only current issues open for clarity.

Thanks in advance!

cc @gustavderdrache @andy-ms
