### ISSUE TITLE
[@types/plotly.js] Unable to install - invalid tag name

### ISSUE THREAD

**Issue by dougleville** [DefinitelyTyped/DefinitelyTyped#42558]
If you know how to fix the issue, make a pull request instead.

- [ X ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @chrisgervang @mtadams007 @meganrm @Dadstart 

If you do not mention the authors the issue will be ignored.
-------------------------------------

Trying to install with npm and getting the following error. Sorry if this is a stupid question but it seems like a legitimate issue to me.

> npm install @types/plotly.js

> npm ERR! code EINVALIDTAGNAME
> npm ERR! Invalid tag name "^[object Object]": Tags may not have any characters that encodeURIComponent encodes.

**Comment by peterblazejewicz** [comment]
@dougleville 
can you try previous version?
```bash
npm i -D @types/plotly.js@1.44.24
```

note:
the NPM registry response for @types/plotly.js contains invalid key value for verison 1.44.29:
```json
 "dependencies": {
        "@types/d3": "^[object Object]"
      },
```

**Comment by dougleville** [comment]
> @dougleville
> can you try previous version?
> 
> ```shell
> npm i -D @types/plotly.js@1.44.24
> ```
> 
> note:
> the NPM registry response for @types/plotly.js contains invalid key value for verison 1.44.29:
> 
> ```json
>  "dependencies": {
>         "@types/d3": "^[object Object]"
>       },
> ```

@peterblazejewicz thanks, I'm able to install with the version you mentioned.

**Comment by jacobq** [comment]
This is also affecting `yarn upgrade` (prompts user to pick a valid version of `@types/plotly.js` from a list). I am fine with pinning at previous version to work around this, but I wish I knew the best place to report the problem. Is this it?

```
$ npm info @types/plotly.js@1.44.29 dependencies
{ '@types/d3': '^[object Object]' }
```

```
$ yarn why @types/d3
yarn why v1.21.1
[1/4] Why do we have the module "@types/d3"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@types/d3@3.5.43"
info Reasons this module exists
   - "@types#plotly.js" depends on it
   - Hoisted from "@types#plotly.js#@types#d3"
info Disk size without dependencies: "144KB"
info Disk size with unique dependencies: "144KB"
info Disk size with transitive dependencies: "144KB"
info Number of shared dependencies: 0
Done in 0.81s.
```

**Comment by enalposi** [comment]
Still happening for 1.44.31. Sticking with 1.44.28 for now.

**Comment by ciukstar** [comment]
Error while trying to update `@types/plotly.js@1.44.28` to `@types/plotly.js@1.44.31`
```
$ npm update @types/plotly.js
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "^[object Object]": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/usr/.npm/_logs/2020-03-11T19_41_17_265Z-debug.log
```
Environment:
```
$ node -v
v13.1.0
```
```
$ npm -v
6.14.2
```
```
$ npm list @types/plotly.js
...
└── @types/plotly.js@1.44.28
```
```
$ npm outdated
Package                Current   Wanted   Latest  Location
...       
@types/plotly.js       1.44.28  1.44.31  1.44.31 ...
...
```
```
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.6
Node: 13.1.0
OS: linux x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@angular/cdk                      9.1.2
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.1.2
@ngtools/webpack                  9.0.6
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

**Comment by peterblazejewicz** [comment]
@dougleville, folks.
Can you pls. verify the latest `@types/plotly.js` works for you and post a feedback here?
Credits to @sandersn 🙇

**Comment by sandersn** [comment]
Fixed by microsoft/types-publisher#753

**Comment by enalposi** [comment]
1.44.32 works here. Thanks guys.

**Comment by ciukstar** [comment]
No more errors after upgrading to `@types/plotly.js@1.44.32`.
Issue resolved. Thanks!
