### ISSUE TITLE
socketcluster-client invoke method return type

### ISSUE THREAD

**Issue by ChisholmKyle** [DefinitelyTyped/DefinitelyTyped#42580]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/socketcluster-client` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DanielRose 

If you do not mention the authors the issue will be ignored.

## Description

The AGClientSocket `invoke` methods have a template type where the response type from the server is the same as the data sent with the invoke request. The return type can be different.

In [types/socketcluster-client/lib/clientsocket.d.ts:147](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e32d4f0292c57f63310af65a7fb3708155cf8083/types/socketcluster-client/lib/clientsocket.d.ts#L147), perhaps it should be

```typescript
invokePublish<T, R>(channelName: string, data: T): Promise<{ channel: string; data: R }>;
```

And in  [types/socketcluster-client/lib/clientsocket.d.ts:178](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e32d4f0292c57f63310af65a7fb3708155cf8083/types/socketcluster-client/lib/clientsocket.d.ts#L178), perhaps it should be

```typescript
invoke<T, R>(event: string, data: T, options?: { ackTimeout?: number }): Promise<R>;
```

**Comment by DanielRose** [comment]
@ChisholmKyle You could close this, since it is fixed in#43463.
