### ISSUE TITLE
Is this signature correct?

### ISSUE THREAD

**Issue by code1x1** [DefinitelyTyped/DefinitelyTyped#42656]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9ee63c9d519f51ea5718fe8df52dac2c9ea89edb/types/node/v12/fs.d.ts#L912

The signature seams to be wrong. How do you call it with options.withFileTypes=true ?

**Comment by peterblazejewicz** [comment]
Hey,
```ts
fs.readdir(direcctory, { withFileTypes: true }, (err: NodeJS.ErrnoException | null, files: fs.Dirent[]) => {
        // implementation
    });
```
TS allows method overloads, so this seems be one to be implemented by your code:
https://www.typescriptlang.org/docs/handbook/functions.html#overloads
See details in the `fs` about that method on how this is done.
Thanks!

**Comment by code1x1** [comment]
okay thank you for the advice. Ill check that out
