### ISSUE TITLE
type for clearInterval and setTimeout don't seem correct

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#42659]
- [x] I tried using the `@types/globals.d.ts` package and had problems.

![Screenshot from 2020-02-26 10-55-00](https://user-images.githubusercontent.com/11139560/75377531-dc1d6f80-5886-11ea-9249-6218eac8d3fd.png)

it allows me to call clearInterval on a timeout, etc.

I tried finding globals.d.ts:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/globals

but I don't see it

**Comment by peterblazejewicz** [comment]
Hey, seems to be not an issue really.
Can you verify your tsconfig contains an entry similar to:
```json
"lib": [
    "es6",
    "dom"
],
```
thanks!

**Comment by ORESoftware** [comment]
my config is the default for create-react-app it's:

```json
{
  "compilerOptions": {
    "target": "es2018",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "allowJs": true,
  "include": [
    "src"
  ]
}

```

**Comment by peterblazejewicz** [comment]
OK, probably your `package.json` installs types for Node (@types/node), in that case point to the window global scope that way:
```ts
window.setTimeout(..)
window.clearTimeout(...)
```
This is quite common problem, see:
https://stackoverflow.com/questions/45802988/typescript-use-correct-version-of-settimeout-node-vs-window
