### ISSUE TITLE
Update types for react-query v1

### ISSUE THREAD

**Issue by dennismorello** [DefinitelyTyped/DefinitelyTyped#42678]
- [x] I tried using the `@types/react-query` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Hi @lukaszfiszer, @jacehensley and @matteofrana, I have updated `react-query` to the latest stable version (1.0.2) but the type definitions are outdated.

**Comment by sw-yx** [comment]
came here for answers too. what needs to be updated? I see that `status` is missing 
![image](https://user-images.githubusercontent.com/6764957/75597887-0416f980-5a66-11ea-9bf8-bbbfc0f74e15.png)

**Comment by sw-yx** [comment]
keeping a gist here with fixed https://gist.github.com/sw-yx/1c9428a30f87f678c4fba0a2fd45a47d

**Comment by ecoleman** [comment]
Most of the definitions need refactored. 

useQuery is no longer overloaded, and there is a dedicated usePaginatedQuery method. The refetch code has also changed to use a new cache object.

**Comment by lukaszfiszer** [comment]
Indeed, there is a huge list of changes in v.1 of react-query, which made those types definitions out-of-date. I'm working on it, hope to finish by the end of the weekend.

**Comment by dennismorello** [comment]
Any update on it? 😉

**Comment by lukaszfiszer** [comment]
PR opened: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42830 Code review and peer verification is more than welcomed!

**Comment by ilovett** [comment]
Thanks @lukaszfiszer  !!! 🙏
