### ISSUE TITLE
react-router-dom: NavLink/Link and state prop

### ISSUE THREAD

**Issue by ukch** [DefinitelyTyped/DefinitelyTyped#42683]
- [x] I tried using the `@types/react-router-dom` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @huy-nguyen @p-jackson @johnnyreilly @eps1lon @danielnixon @ynotdraw

I am trying to use the `NavLink` component to pass router state. According to the [code](/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/NavLink.js), `NavLink` should have all the same props as `Link`, plus a couple of others (see proptypes declaration). According to the [`Link` documentation](/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/Link.md) I should be able to pass router state by using the `state` prop. So I would expect code like the following to work:
```typescript.tsx
<NavLink to="/some/url" state={{ clear: true }}>link text</NavLink>
```
However, I receive the following error:
```
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<NavLinkProps<PoorMansUnknown>>): NavLink<PoorMansUnknown>', gave the following error.
    Type '{ children: any[]; to: string; state: { clear: boolean; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<NavLink<PoorMansUnknown>> & Readonly<NavLinkProps<PoorMansUnknown>> & Readonly<...>'.
      Property 'state' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<NavLink<PoorMansUnknown>> & Readonly<NavLinkProps<PoorMansUnknown>> & Readonly<...>'.
  Overload 2 of 2, '(props: NavLinkProps<PoorMansUnknown>, context?: any): NavLink<PoorMansUnknown>', gave the following error.
    Type '{ children: any[]; to: string; state: { clear: boolean; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<NavLink<PoorMansUnknown>> & Readonly<NavLinkProps<PoorMansUnknown>> & Readonly<...>'.
      Property 'state' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<NavLink<PoorMansUnknown>> & Readonly<NavLinkProps<PoorMansUnknown>> & Readonly<...>'.  TS2769
```
NB: While my specific problem is with the `NavLink` component, after a quick read of the TS definiton, it seems `Link` would have the same issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
