### ISSUE TITLE
carbon-components-react Tab seems to be overtyped

### ISSUE THREAD

**Issue by tbrannam** [DefinitelyTyped/DefinitelyTyped#42701]
@kalbert312  Thanks for working on these. And I'm not an expert on carbon-comonents-react - so I may be confused on the usage.

When trying to leverage `Tab` inside a Carbon-react `Tabs` - the typechecker complains that several of these callbacks are required - but the documentation doesn't directly discuss them - I think that these properties are meant to be internal to the component.  

Here's an example of the type error https://codesandbox.io/s/carbon-tab-types-cmy74 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3ef5e0c92beeaaff6b7848652e5c6d3daf230e2c/types/carbon-components-react/lib/components/Tab/Tab.d.ts#L19

**Comment by myan9** [comment]
@tbrannam @kalbert312  Same issue here! Following this type definition, we specified`handleTabAnchorFocus` prop in `Tab`, but got the following error in the javascript console: 
> Warning: React does not recognize the handleTabAnchorFocus prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase handletabanchorfocus instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Reference of our code:
https://github.com/IBM/kui/blob/master/plugins/plugin-sidecar/src/view/components/TopNavSidecar.tsx#L203-L215

**Comment by kalbert312** [comment]
Looking at the master version of old carbon-component-react this typings are correct: https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/Tabs/Tabs.js. The current version of the typings was made for 7.6: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/carbon-components-react/index.d.ts#L1. It looks like they completely rewrote `Tab` in the latest versions (`7.9.x`)... if someone wants to update it for 7.9 feel free to.

**Comment by tbrannam** [comment]
Thanks for the feedback, will look to update.

**Comment by kalbert312** [comment]
I recently updated the tabs types for 7.10. It fixes the issue where certain props are provided by the parent Tabs component. I guess it would have helped to use Tabs before I quickly jammed out types for them. Should be fixed in `7.10.3`.

**Comment by tbrannam** [comment]
Looking great, Thanks!
