### ISSUE TITLE
@types/pdfmake - Could not find declaration file for module

### ISSUE THREAD

**Issue by nmummau** [DefinitelyTyped/DefinitelyTyped#42761]
I tried using the `@types/pdfmake` package and had problems. This was first found in a Vue application I'm creating. So I created a sample Vue project and reproduced the error. I don't think it matters, but the project was created with vue cli v3.10.0.
`tsc -v` Version 3.8.3

I reached out to Enzo a few weeks ago and he suggested I make a sample repo that highlights the issue. The sample repo is here: https://github.com/nmummau/pdfmake-types-issue

Interestingly, when I add a Triple-Slash Directive I am able to get it to work. But without that directive, the declarations for `@types/pdfmake` cannot be found by Visual Studio Code.

Authors of @types/pdfmake are: @m1llen1um @radziksh @evolkmann @andipaetzold

Errors without Triple-Slash Directive:
![image](https://user-images.githubusercontent.com/10524529/75892270-062ede80-5dff-11ea-80d8-1dcafa1b5a7e.png)

**Comment by jeralm** [comment]
I tried cloning your repo but haven't had any luck reproducing the issue.
In anycase, I recommend you use default imports with the `--esModuleInterop` compiler option turned on. see [the bit from the related TypeScript release](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop). pdfMake is (to the best of my knowledge) a UMD module.

**Comment by nmummau** [comment]
@jeralm can you show me how you import pdfmake into your project? I'm having trouble following what you mean. Also, it's preventing me from fully testing your current open PR to update the type definitions.

**Comment by jeralm** [comment]
Might be helpful if I could reproduce the issue. Does running tsc give you any error at all? Is your vscode using the correct version of tsc? 
![image](https://user-images.githubusercontent.com/35611957/76380623-a322d780-6329-11ea-86a1-6c8e6fd1d38d.png)

I'll fork your sample repo to show you what I meant earlier.

**Comment by nmummau** [comment]
Interesting. No it's not... vs code is using 3.7.5. I've switched it to use 3.8.3. And now my sample repository is working on my machine too.
But the larger workspace (my real project) that I first experienced this in is still having the issue even after switching vscode to 3.8.3...

**Comment by nmummau** [comment]
Possibly it's related to [24781](https://github.com/microsoft/TypeScript/issues/24781)

**Comment by jeralm** [comment]
This is likely not related to pdfMake, but rather the TypeScript Language Server and / or vscode.

**Comment by nmummau** [comment]
This was a tsconfig.json issue in my project. I had to add "pdfmake" to `types`  to get it to work.
```
"typeRoots": ["./node_modules/@types"],
"types": ["pdfmake"]
