### ISSUE TITLE
Add adapter field to pouchDB

### ISSUE THREAD

**Issue by fredgalvao** [DefinitelyTyped/DefinitelyTyped#4278]
PouchDB defines a field called adapter that is described [here](http://pouchdb.com/adapters.html), and it's actually exposed through the root instance type ([here](https://github.com/pouchdb/pouchdb/blob/ef247eced792f374c1632d9b55821c3c3e62e473/lib/constructor.js#L99)) as a string field, the same of the PouchOptions, but this field is not declared in the PouchApi in the current pouch.d.ts file.

**Comment by vvakame** [comment]
@fredgalvao please send a pull request. I'll review it.

**Comment by fredgalvao** [comment]
I started a huge review and refactor on pouch.d.ts, I'll submit it very soon.

**Comment by AGBrown** [comment]
@fredgalvao, can you take a look at https://github.com/AGBrown/pouchdb.d.ts/, the pouchdb team and I have been working on a whole new pouchdb.d.ts file for pouchdb v3.4.0 and I am a long way down the road. Maybe we could combine efforts?

**Comment by fredgalvao** [comment]
Sure thing! As of right now with a very quick look at the code I can see yours is way ahead in detail than my refactor already.

I'll follow up at your repo so I can express where I think it can be improved.

**Comment by AGBrown** [comment]
@fredgalvao, thank you. Feel free to fork+PR, create issues, and generally rip into anything you like, including the module/interface structure and names - at this stage everything is up for grabs. We are quite active on IRC so come talk to us there as well.

**Comment by nolanlawson** [comment]
This seems superceded by #10171.
