### ISSUE TITLE
[@types/testing-library__react] not fully compatible types for act (missing async version)

### ISSUE THREAD

**Issue by sidoruk-sv** [DefinitelyTyped/DefinitelyTyped#42791]
Because of this (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/testing-library__react/index.d.ts#L52) typing, I got tslint warning:
```
await-promise  Invalid 'await' of a non-Promise value.
```

but in `@types/react-dom/test-utils` async overload exist:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-dom/test-utils/index.d.ts#L293

- [X] I tried using the `@types/testing-library__react` package and had problems.
- Authors: @alexkrolick @kentcdodds @weyert @ifiokjr @danieljcafonso

**Comment by domachine** [comment]
I'm also running into this. Swapping the definitions (promise-version first) seems to fix this.

**Comment by sidoruk-sv** [comment]
was fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44005
