### ISSUE TITLE
[styled-components] improper prop typing when overriding HTML property

### ISSUE THREAD

**Issue by danielkov** [DefinitelyTyped/DefinitelyTyped#42795]
This issue was originally posted to `styled-components/styled-components`.

[Here's the original issue.](https://github.com/styled-components/styled-components/issues/3044)

[Here's the CodeSandbox reproducing the issue.](https://codesandbox.io/s/vigorous-worker-bkfsm)

## Summary

When defining prop types to a styled constructor:

```ts
type ExampleProps = { color: Function };

const Example = styled.div<ExampleProps>`
  color: ${({ color }) => color()};
`
```
the type of `color` will be `string & Function`, which is not true.

Currently `styled-components` does not land this property on the DOM Node itself, therefore the correct typing should be `Function`, however even if it did place it on the DOM Node, the typing should be `string | Function`, instead of `string & Function`. This means `Example.propTypes` cannot be defined as expected, as seen in my example reproduction.

Upon further investigation I've found that this is caused by the props not being *merged* with the picked `DetailedHTMLAttributes`, but instead being combined with `&`. This causes a combination of their value types, instead of the desired behaviour of being able to override them via the generic parameter.

- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @surgeboris @sandersn @Jessidhia @smockle @Igorbek @Igmat @Lavoaster @eps1lon @flavordaaave @wagerfield @Lazyuki @mgoszcz2

I would love to submit a PR, but have no experience with this repository and feel a bit lost at first glance.

**Comment by danielkov** [comment]
To expand on this:

As I understand type merging is a difficult subject in TypeScript, due to it not yet being supported in the language, until [this issue is resolved](https://github.com/microsoft/TypeScript/issues/10727).

There are utility libraries implementing this functionality, [such as this one](https://github.com/pirix-gh/ts-toolbelt/blob/master/src/Object/Merge.ts).

For consideration I've included in my reproduction example the following snippet of a primitive implementation of merging `HTMLProps` with `Props`:

```ts
// Primitive implementation of Merge, not taking into account the following:
// Merge<{ optional: number }, { optional?: string }> = { optional: number | string }
// Merge<{ optional?: number }, { optional?: string }> = { optional: number | string | undefined }
type Merge<A extends object, B extends object> = {
  [key in keyof A]: key extends keyof B ? B[key] : A[key]
} &
  B;

// type Desired = Function
type Desired = Merge<{ color: string }, ExampleProps>["color"];
```

**Comment by erictaylor** [comment]
See PR #42795.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by jamiter** [comment]
@danielkov, did you ever have this issue resolved?
