### ISSUE TITLE
Can these declaration files be separated and enabled for Bower?

### ISSUE THREAD

**Issue by joewood** [DefinitelyTyped/DefinitelyTyped#428]
Could these type definitions be separated and enabled in [twitter/bower](http://github.com/twitter/bower) ?  I see a number of advantages:
- Different versions of the type definitions can be linked to specific released version of the component
- Pulling down the TS declarations file would also bring down the component itself, through a dependent `component.json`
- The files can stay in GitHub as the repository
- Deploy scripts can pull down the Bower dependencies, no need to check-in the declarations files

**Comment by fatso83** [comment]
Please close these older issues. You need a bot to close ancient questions.
