### ISSUE TITLE
[react-native] New AnimatedComponent type doesn't accept refs

### ISSUE THREAD

**Issue by benhamlin** [DefinitelyTyped/DefinitelyTyped#42806]
The AnimatedComponent<T> type added in change https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f7ba6e840d343675432dfd7886d112977d1531a0 are most welcome, but currently don't accept a `ref` prop. This is especially problematic on ScrollViews and such, as being able to call the various imperative `scrollTo` methods is pretty important.

```
Property 'ref' does not exist on type 'IntrinsicAttributes & AnimatedProps<ScrollViewProps> & { children?: ReactNode; }'.ts(2322)
```

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @zusinShinpei

**Comment by alloy** [comment]
I think this is covered by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42446

**Comment by Kyi-Moe-Min** [comment]
do you find a way to deal with it? I'm facing the same problem
