### ISSUE TITLE
[@types/tryghost__content-api] Incompatibily of PostObject type with @tryghost/content-api

### ISSUE THREAD

**Issue by Gwenael22** [DefinitelyTyped/DefinitelyTyped#42855]
Hello,

I have some problem to use "@types/tryghost__content-api" with the "@tryghost/content-api" as i mentioned here https://github.com/TryGhost/Ghost-SDK/issues/213

The Ghost team does not consider that it is issue on their side so ... do you think it is a good idea to implement the workaround they furnished ?

- [x] I tried using the `@types/tryghost__content-api` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @knguyen0125 , @antonve

**Comment by antonve** [comment]
Thank you for raising the issue. Currently a fix for this is being discussed in #42750

**Comment by Gwenael22** [comment]
Hello, thanks for the link. Sorry, I missed this discussion.
