### ISSUE TITLE
[@types/react] React.memo does not accept children

### ISSUE THREAD

**Issue by aaronbeall** [DefinitelyTyped/DefinitelyTyped#42865]
It seems that `React.memo()` results in a component that won't accept JSX children:

This works, note that `{children}` raises no error as expected because `PropsWithChildren` is used in the resolved inner component parameter:
```
const Foo = React.memo<{ title: string }>(({ children, title }) => (
    <div title={title}>{children}</div>
));
```

Rendering the resulting component with no children works:
```
const test = <Foo title="foo" />;
```

Rendering with JSX children results in `Error: Property 'children' does not exist on type 'IntrinsicAttributes & { title: string; }'`
```
const test2 = (
    <Foo title="foo">
       <b>Hello</b>
    </Foo>
);
```

I wonder if `ExoticComponent` should use `(props: PropsWithChildren<P>)` instead of just `(props: P)` as it does now? It seems to fix the issue local. Is there some reason not to do that?

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  Asked on gitter.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @pshrmn @threepointone @saranshkataria

**Comment by threepointone** [comment]
Please note that if you’re passing children to a .memo component, it’ll fail the props check every time, making the memoisation useless. (Since children will be a new object every time). So maybe this shouldn’t be changed?

**Comment by aaronbeall** [comment]
@threepointone Unless the children are themself memo'd (and haven't re-rendered), right?

**Comment by threepointone** [comment]
Maybe, but it seems like extra work if it’s going to be static in that fashion. Simpler then to memoise a component that already includes the children in it (which could still change for different props)

**Comment by aaronbeall** [comment]
@threepointone True, but JSX composition is a nice feature. The same argument could be made against `PureComponent`.

**Comment by threepointone** [comment]
You’re right, PureComponent probably shouldn’t accept children either 😅

I don’t feel strongly about this type change, just pointing out it might not be as helpful as you’d think. I do recommend you consider restructuring your code instead.

**Comment by Hotell** [comment]
I kinda agree with @aaronbeall . IMHO this should be handled by some linter, not type-system -> that you're using non memoized children within memoized component.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
