### ISSUE TITLE
Missing getElement method for atom

### ISSUE THREAD

**Issue by aminya** [DefinitelyTyped/DefinitelyTyped#42878]
`Workspace.getElement()` is missing 
Flight manual:
https://flight-manual.atom.io/api/v1.44.0/Workspace/

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e534774027767502c673b7f9b2859c1b3cbe9087/types/atom/index.d.ts#L2710

**Comment by peterblazejewicz** [comment]
/cc 
@GlenCFL @smhxx @lierdakil

**Comment by GlenCFL** [comment]
@aminya The documentation mentions `item.getElement()`, with this item being the one you provide to functions such as `Workspace.open()`. The `Workspace.getElement()` method isn't documented within the public API. We could probably do a better job defining the type of the `item` object, but I don't think we'd want to define `Workspace.getElement()` within a definition file for the public Atom API.

If you are after `Workspace.getElement()`, I'd suggest using [Module Augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) to add both the `Workspace.getElement()` method and the interface for the returned [WorkspaceElement](https://github.com/atom/atom/blob/v1.40.0/src/workspace-element.js#L10) with all relevant properties for your project.

**Comment by aminya** [comment]
> 
> 
> @aminya The documentation mentions `item.getElement()`, with this item being the one you provide to functions such as `Workspace.open()`. The `Workspace.getElement()` method isn't documented within the public API. We could probably do a better job defining the type of the `item` object, but I don't think we'd want to define `Workspace.getElement()` within a definition file for the public Atom API.
> 
> If you are after `Workspace.getElement()`, I'd suggest using [Module Augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) to add both the `Workspace.getElement()` method and the interface for the returned [WorkspaceElement](https://github.com/atom/atom/blob/v1.40.0/src/workspace-element.js#L10) [](/atom/atom/blob/HEAD@{2020-03-07T20:54:44Z}/src/workspace-element.js#L10) with all relevant properties for your project.

Thank you for your answer. 

Since I am not that familiar to the API, I leave this implementation to you and other developers who know the types and functions better. I just wanted to bring this up, so you are aware of it.

So is there an alternative you recommend instead of defining the type myself?

**Comment by lierdakil** [comment]
I'm a little late to the party, but Atom has a public API for getting the workspace element, that being `atom.views.getView(atom.workspace)`. This is a bit of a holdover from earlier model-view architecture that didn't use `getElement` on models at all, but it works perfectly well for the purpose.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
