### ISSUE TITLE
Update Knockout typings for version 3.3.0

### ISSUE THREAD

**Issue by ThomasMichon** [DefinitelyTyped/DefinitelyTyped#4288]
The stable release for Knockout 3.3.0 came out some time ago, and brought improvements to the binding context for components such as `$component` and `$componentTemplateNodes`, a `sycnhronous` flag for component definitions, a `ko.ignoreDependencies` utility method, and a few other things.

We should update the typings to support version 3.3.0.

**Comment by vvakame** [comment]
@ThomasMichon please send a pull request.

**Comment by IanYates** [comment]
I've been keeping my type definition file reasonably up to date with the KO changes.  I'll see if I can do something about creating a PR for it this weekend.

**Comment by nycdotnet** [comment]
@IanYates Please @ me when you submit and I'll review and pull in ASAP.  Thank you.

**Comment by chinaniit** [comment]
I'm compare source code, and update d.ts.
https://github.com/chinaniit/knockout-3.3.0.d.ts/blob/master/knockout.d.ts

**Comment by logankd** [comment]
Is there anything that needs to be updated for the newly released 3.4.0 version? https://github.com/knockout/knockout/releases/tag/v3.4.0

**Comment by mbest** [comment]
@logankd 3.4.0 adds some new APIs: `ko.tasks.*`, `ko.options.*`, `ko.onError`, `ko.isPureComputed`, and `deferred` extender.

**Comment by mattbrooks2010** [comment]
Support for `ko.tasks.*` was added in #9150. It looks like `ko.options.*` has been implemented whereas `ko.onError` and `ko.isPureComputed` still need to be defined.

**Comment by ltlombardi** [comment]
Isn't this supposed to be closed?

**Comment by nycdotnet** [comment]
Yep.  Thanks @ltlombardi
