### ISSUE TITLE
@types/cesium Missing types for MapboxImageryProvider and MapboxStyleImageryProvider

### ISSUE THREAD

**Issue by smonikantara** [DefinitelyTyped/DefinitelyTyped#42880]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Zuzon @hnipps @szechyjs @golyalpha @KeyboardSounds @soyarsauce @jrafidi @morgansierrasnyder @crocsx 

I could not find the types for [MapboxImageryProvider](https://cesium.com/docs/cesiumjs-ref-doc/MapboxImageryProvider.html) and [MapboxStyleImageryProvider](https://cesium.com/docs/cesiumjs-ref-doc/MapboxStyleImageryProvider.html). Are these on the roadmap for future releases?

Thanks.

**Comment by smonikantara** [comment]
@peterblazejewicz Thank you for adding the objects.

**Comment by peterblazejewicz** [comment]
you're welcome! I think we could close this one, the PR eventually lands in the master soon!
