### ISSUE TITLE
[@types/passport] upgrading from 1.0.0 to 1.0.1 is breaking

### ISSUE THREAD

**Issue by nmummau** [DefinitelyTyped/DefinitelyTyped#42971]
- [x] I tried using the `@types/passport@1.0.1` package and had problems.
- [x] I tried using the latest stable version of [tsc](https://www.npmjs.com/package/typescript). I am using tsc@3.8.3.
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors.
  - Authors: @horiuchi @enaeseth @theigor @tlaziuk @kstiehl @vaskevich @unindented 

**Explanation**
I currently have @types/passport@1.0.0 in my express app. It's working fine. I ran npm `update @types/pdfmake` which took me to 1.0.2. It broke my app. So I rolled that back. I tried updating to 1.0.1 and even that breaks my app. So I'll try to explain in a concise way what I'm doing...

```
//login.ts
import passport from 'passport';

passport.deserializeUser(async (user: login.IRequestUser, callback) => {
	try {
		interface IConfirmedPartialUser {
			loginId: number;
			userId: number;
		}
		//Just an example. In the real app, the loginId and userId is fetched from the database.
		var confirmedPartialUser = {
			loginId: 1,
			userId: 2
		} as IConfirmedPartialUser;

		const confirmedUser: login.IRequestUser = {
			loginId: confirmedPartialUser.loginId,
			userId: confirmedPartialUser.userId,
		};
		callback(null, confirmedUser);
	} catch (err) {
		callback(err);
	}
}
```

I have a middleware function that I use to hit the database to be sure the req.user.userId has permission to this feature. The feature in question is passed as a variable to the function.
This is where the issue happens in @types/passport@1.0.1. 
Screenshot below of the error in the IDE.
```
//require-feature.ts
import * as express from 'express';
import database from '@/database';

const requireFeature = (feature: string) => {
	return function(req: express.Request, res: express.Response, next: express.NextFunction) {
		console.log('Special feature required:', feature);

		console.log(req.user.userId); // <<<---ERROR

		//This is the real code. Basically it is hitting the database to make sure that the user has a certain "feature" based on the `feature: string` variable that is passed into this function.
		var ok = database
			.from('base.user')
			.join('base.user_feature_permission', 'user_feature_permission.user_id', 'user.user_id')
			.join('base.feature', 'feature.feature_id', 'user_feature_permission.feature_id')
			.where({ 'user.user_id': req.user.userId }) <<<---ERROR
			.where({ 'feature.is_active': true })
			.where({ 'feature.feature_name': feature })
			.first();

		if (ok) return next();
		else return res.status(401).redirect('/');
	};
};

export default requireFeature;

```

Usage of the `requireFeature(feature: string)` middleware looks like this in express 

```
//accounts.ts
import express from 'express';
const router = express.Router();

router.post(
	'/fetch-accounts',
	requireFeature('Admin'), //<<<--- the middleware function described above
	asyncHandler(async (req, res, next) => {
		//do the actual fetching of the accounts
		return res.send('account data');
	})
};
```

![image](https://user-images.githubusercontent.com/10524529/76136116-f8927800-5ffb-11ea-931c-f1a19e772426.png)

**Comment by peterblazejewicz** [comment]
@nmummau 
I think it is expected for your code to provide augmented module definition to provide information about the User properties, according to intention of the 1.0.1 changes:

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/91c229dbdb653dbf0da91992f525905893cbeb91#r34812715

One could either augment `User` definition to use expected types, or stick to '@types/passort@1.0.0':
https://unpkg.com/@types/passport@1.0.0/index.d.ts

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
