### ISSUE TITLE
[@types/node] StatsBase<T> is not correct in fs.d.fs

### ISSUE THREAD

**Issue by eGust** [DefinitelyTyped/DefinitelyTyped#42989]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Microsoft @DefinitelyTyped @Flarna @SimonSchick @andrewbranch @ExE-Boss

Currently [`StatsBase<T>` does not apply `T` to fields](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/fs.d.ts#L22)
```
    interface StatsBase<T> {
        isFile(): boolean;
        isDirectory(): boolean;
        isBlockDevice(): boolean;
        isCharacterDevice(): boolean;
        isSymbolicLink(): boolean;
        isFIFO(): boolean;
        isSocket(): boolean;

        dev: number;
        ino: number;
        mode: number;
        nlink: number;
        uid: number;
        gid: number;
        rdev: number;
        size: number;
        blksize: number;
        blocks: number;
        atimeMs: number;
        mtimeMs: number;
        ctimeMs: number;
        birthtimeMs: number;
        atime: Date;
        mtime: Date;
        ctime: Date;
        birthtime: Date;
    }
```

According to Node [documentation](https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_class_fs_stats), all those `number` should be `T`. 

This bug causes `{ bigint: true }` option on fs.{stat,fstat} still return `BigIntStats` with `number` types.

**Comment by SimonSchick** [comment]
Woops.
