### ISSUE TITLE
[@types/urijs] Missing properties and methods: duplicateQueryParameters, escapeQuerySpace, preventInvalidHostname

### ISSUE THREAD

**Issue by ahagelstein** [DefinitelyTyped/DefinitelyTyped#42995]
The type definition for [@types/urijs] is not complete.

Missing properties and methods:
duplicateQueryParameters
escapeQuerySpace
preventInvalidHostname

I have modified the type definition based on the latest version (see attachment).

Authors: @RodneyJT, @xt0rted, @petejohanson, @ljqx, @teamworkguy2, @Akuukis, @marcelltoth

[index.d.ts.txt](https://github.com/DefinitelyTyped/DefinitelyTyped/files/4303352/index.d.ts.txt)

**Comment by marcelltoth** [comment]
Hi,

Thanks for submitting the issue.

As you have already fixed the definitions yourself, would you mind opening a PR where we can manage the process more easily (and you also get credit for your work)?

See the DefinitelyTyped [contribution guide](https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute) here, or read about the [forking workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow) in general if you are not yet familiar.
