### ISSUE TITLE
angular-mocks respond in IRequestHandler should return IRequestHandler

### ISSUE THREAD

**Issue by blbigelow** [DefinitelyTyped/DefinitelyTyped#4300]
I am building out my tests in typescript and I'm getting a compile error trying to apply this:

``` javascript
var authRequestHandsler : angular.mock.IRequestHandler;

authRequestHandler = $httpBackend.whenPOST('/login').respond({message: 'user authenticated'});
```

In the docs for $httpBackend its shows that "respond" shouldn't just return void: https://docs.angularjs.org/api/ngMock/service/$httpBackend

**Comment by vvakame** [comment]
@blbigelow please send a pull request. I'll review it.

**Comment by begincalendar** [comment]
Should this issue be closed (as it seems to be resolved)?
