### ISSUE TITLE
Using github actions to maintain a definitelyTyped type definition?

### ISSUE THREAD

**Issue by dbrudner** [DefinitelyTyped/DefinitelyTyped#43016]
Hello, not sure if this is the appropriate place to ask this, but I'm also not sure where else I can look.

I'm creating type definitions for an externally-loaded javascript library (https://github.com/recurly/recurly-js). I haven't opened a pull request for this yet, but I will soon.

After those definitions get initially merged, the plan is to have a definitions-generating project inside our repo (https://github.com/recurly/recurly-js) emit a declaration file and use github actions to open pull-requests here whenever that file is updated.

I'm not sure if this workflow is appropriate or not. Is this ill-advised for a reason I'm not aware of?

**Comment by zacnomore** [comment]
It might make sense to just ship the definitions with package rather than going through that kind of trouble 
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by elliotbonneville** [comment]
I agree with @zacnomore, in this case it makes sense to just ship the typings with the project.

Is there a reason you want to store them in DefinitelyTyped?
