### ISSUE TITLE
Mandatory properties of ApplePayPaymentRequest makes calling CreatePaymentRequest pointless

### ISSUE THREAD

**Issue by dboshkoff** [DefinitelyTyped/DefinitelyTyped#43054]
- [x] I tried using the `@types/braintree-web` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @colinrcummings 

This is the definition of ApplePayPaymentRequest. Note that `countryCode, currencyCode, supportedNetworks, and merchantCapabilities` are defined as mandatory. 

```
interface ApplePayPaymentRequest {
    total: {
      label: string;
      amount: string;
    };
    countryCode: string;
    currencyCode: string;
    supportedNetworks: string[];
    merchantCapabilities: string[];

    billingContact?: any;
    shippingContact?: any;
    shippingMethods?: any;
    shippingType?: any;
    requiredBillingContactFields?: any;
    requiredShippingContactFields?: any;
  }
createPaymentRequest(paymentRequest: ApplePayPaymentRequest): ApplePayPaymentRequest
```

Because of this definition, the paymentRequest that is passed into `createPaymentRequest` must already have `countryCode`, `currencyCode`, `supportedNetworks`, and `merchantCapabilities` otherwise typescript will complain. However, the point of calling this function is to populate those values into the payment request from the braintree default payment configuration. So the type check defeats the purpose of calling the function. 

Can there be a different incoming type to `createPaymentRequest` which has those four fields as optional? 
Let me know if I'm misunderstanding the types in any way!

**Comment by colinrcummings** [comment]
@dboshkoff, I'm not an author of `@types/braintree-web`; I just submitted a PR to fix some of the definitions I ran into issues with (#40926) I suggest doing the same.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
