### ISSUE TITLE
readInt32BE Should have offset marked as optional

### ISSUE THREAD

**Issue by fireflysemantics** [DefinitelyTyped/DefinitelyTyped#43112]
See this Stackoverflow post:

https://stackoverflow.com/questions/60668616/converting-random-from-cuid-to-typescript?noredirect=1#comment107337457_60668616

**Comment by KpjComp** [comment]
To make things easier for Dev's.

NodeJS Docs ->

> offset <integer> Number of bytes to skip before starting to read. Must satisfy 0 <= offset <= buf.length - 4. Default: 0.

But inside -> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/globals.d.ts

It's defined as->
```readInt32BE(offset: number): number;```

But of course wants to be
```readInt32BE(offset?: number): number;```
