### ISSUE TITLE
add an array of literal objects in a backbone collection is missing

### ISSUE THREAD

**Issue by pligor** [DefinitelyTyped/DefinitelyTyped#4314]
Inside **backbone.d.ts**

and inside `class Collection<TModel extends Model> extends ModelBase`

this definition is missing:
`add(array: any[]);  //when you add a collection of models by only defining their attributes`

**Comment by vvakame** [comment]
@pligor please send a pull request. I'll review it.

**Comment by Spinarooni** [comment]
I think this has been implemented.
