### ISSUE TITLE
[@types/luxon] - all types as read-only

### ISSUE THREAD

**Issue by stekycz** [DefinitelyTyped/DefinitelyTyped#43182]
- [x] I tried using the `@types/luxon` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @colbydehart @FourwingsY @jsiebern @mastermatt @pietrovismara @dawnmist @ycmjason @mdanka

I want to use [`prefer-readonly-parameter-types` ESlint rule for TypeScript](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md), however, all usage of `DateTime` or `Interval` from `luxon` are not considered read-only.

I see that all properties are not marked read-only in the definition. I would expect them to be read-only because the library itself is immutable so having mutable fields does not make any sense.

I would add the flag to all value object types/classes to be usable with the rule. I am not sure about changing type definitions for options and parameters. However, I expect the library uses them immutably as well.

I am also aware it would be a BC breaking change. On the other hand, it should provide better type checking closer to what luxon probably wants.

**Comment by 43081j** [comment]
while it would make sense for them to be read-only, i suspect you shouldn't be linting your dependencies... there are many dependencies which won't follow your lint configuration so it makes sense to ignore `node_modules` from your eslint run.

**Comment by stekycz** [comment]
I am not linting my dependencies. I am linting my code and when I want to have an argument to some function to be type `DateTime` for example then the type is validated to be read-only. The only way I can make it work is by using `Readonly<...>` or [`DeepReadonly<...>`](https://github.com/piotrwitek/utility-types#deepreadonlyt) everywhere which makes the code less readable.

However, I still believe it should be read-only anyway. The usage with the ESlint rule is only the reason I found the issue 😉
