### ISSUE TITLE
Hi, this method gapi.client.people.get from @types/gapi.client.people is returned undefined. When I log "gapi.client.people" the function "get" is inside "people". Should I use "gapi.client.people.people.get()" instead of "gapi.client.people.get()"?

### ISSUE THREAD

**Issue by viviakemik** [DefinitelyTyped/DefinitelyTyped#43219]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by Maxim-Mazurok** [comment]
@viviakemik indeed, it seems like you have to use it like this:
```js
/**
 * Provides information about a person by specifying a resource name. Use
 * `people/me` to indicate the authenticated user.
 *
 * The request throws a 400 error if 'personFields' is not specified.
 */
await gapi.client.people.people.get({
    personFields: "Test string",
    "requestMask.includeField": "Test string",
    resourceName: "Test string",
});
```
Please, open new issue [here](https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/new) if you run into any issues with using `gapi.client.people` typings.
I can update `gapi.client.people` typings if they are outdated.
Also, you can [use](https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/85#issuecomment-601133279) fresh typings from our `types` branch which is updated every hour.
Thanks!
