### ISSUE TITLE
[@types/lodash.groupby] Return type should reflect it can be `undefined`

### ISSUE THREAD

**Issue by astorije** [DefinitelyTyped/DefinitelyTyped#43283]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/lodash.groupby` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel, @chrootsu, @stepancar

Consider the following code:

```ts
import groupBy from 'lodash.groupby';

interface Value {
  type: 'foo' | 'bar' | 'baz';
  value: number;
}

const values: readonly Value[] = [
  { type: 'foo', value: 1 },
  { type: 'bar', value: 2 },
];

const { foo, bar, baz } = groupBy(values, ({ type }) => type);

console.log(foo); // [Object {type: "foo", value: 1}]
console.log(bar); // [Object {type: "bar", value: 2}]
console.log(baz); // undefined
```

As you can see, `baz` holds a value of `undefined`, however its inferred type is incorrect: `const baz: Value[]`.

Later on, we have to provide a fallback value: `baz ?? []`. This is unexpected because according to the type checker, `baz` cannot be `undefined`. Additionally, when running ESLint with the rule [`@typescript-eslint/no-unnecessary-condition`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-condition.md) enabled, we get the following violation which confirms the incorrect type:

```
Unnecessary conditional, expected left-hand side of `??` operator to be possibly null or undefined
```

Looking at `collection.d.ts`, I see the following type:

```ts
groupBy<T>(collection: List<T> | null | undefined, iteratee?: ValueIteratee<T>): Dictionary<T[]>;
```

It seems to me this should something of the sort:

```ts
groupBy<T>(collection: List<T> | null | undefined, iteratee?: ValueIteratee<T>): Dictionary<T[] | undefined>;
```

I opened this as an issue and not a PR because I'd understand if it's a PEBCAK 😅

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
