### ISSUE TITLE
A refreshed d.ts for pouchdb v.3.4.0+, and v4.0.0+

### ISSUE THREAD

**Issue by AGBrown** [DefinitelyTyped/DefinitelyTyped#4328]
#### pouch.d.ts is out of date

The current pouchdb `pouch.d.ts` file is completely out of date. I (we) would like to more closely link the pouchdb `d.ts` file to the development of pouchdb itself. At [pouchdb.d.ts] I have started working on a total rewrite of the pouchdb definition file, supported by the pouchdb team.

*Why a rewrite*? pouchdb is now three major versions ahead of [the DefinitelyTyped `pouch.d.ts`]. For example the DefinitelyTyped `pouch.d.ts`: lacks promise support (#4277); is now missing many methods and properties (e.g. #4278); and has out of date definitions for existing members (e.g. `put` which now has many more implied overloads).

As the proof of any pudding is in the eating the challenges I have set the [new `pouchdb.d.ts`] are:

1. to start by releasing an updated `pouchdb.d.ts` for v3.4.0 into DefinitelyTyped as soon as possible;
1. to be able to write _every single pouchdb test_ in the [pouchdb test suite] with the `pouchdb.d.ts` file <sup>†</sup>;
1. to be able to support each pouchdb api version change, starting with v3.4.0;
1. to provide-self documenting pouchdb usage as far as is possible through typescript intellisense (rather than just `doc: any`) that matches, and embellishes, the [pouchdb documents].

#### Call for contributions

The new [pouchdb.d.ts] project **really needs reviewers and contributors** <sup>‡</sup> at this stage to help set the right direction for the new `pouchdb.d.ts` structure, and to publish the first major release (for a long time) of the `pouchdb.d.ts` file as soon as possible.

As soon as our first release is ready we will PR into DefinitelyTyped, linking to this issue for review.

-----------------

<sup>†</sup> *We haven't implemented even 20 % of them yet, but it is not even possible to write many of those tests with the current DefinitelyTyped pouch.d.ts file as can be seen by substituting our [new `pouchdb.d.ts`] with [the DefinitelyTyped `pouch.d.ts`] and viewing the resulting mass of typescript compile errors*

<sup>‡</sup> It would be incredibly helpful if anyone who has contributed to, or has an interest in, the existing pouch.d.ts file could take a look at this new d.ts project for pouchdb. I am therefore pinging #2767 - @mhegazy, #1512 - @joeriks, #154 @MrBigDog2U, and #4277, #4278 @fredgalvao (who has already responded to us).

[pouchdb.d.ts]: https://github.com/AGBrown/pouchdb.d.ts/ "The new pouchdb.d.ts repository on github"
[pouchdb test suite]: https://github.com/pouchdb/pouchdb/tree/3.4.0/tests "pouchdb v3.4.0 test suite"
[pouchdb documents]: http://pouchdb.com/api.html "pouchdb.com/api.html"
[new `pouchdb.d.ts`]: https://github.com/AGBrown/pouchdb.d.ts/blob/feat/pouchdb.d.ts "pouchdb.d.ts in pouchdb.d.ts on github"
[the DefinitelyTyped `pouch.d.ts`]: https://github.com/borisyankov/DefinitelyTyped/blob/176249d/pouchDB/pouch.d.ts "DefinitelyTyped pouch.d.ts at 176249d"

**Comment by AGBrown** [comment]
pouchdb has now released v4.0.0. The [pouchdb.d.ts](https://github.com/AGBrown/pouchdb.d.ts/) project will support this by building on the work for the v3.4.0 release, but the v3.4.0 release still needs to be completed first. We are a long way through, but help is still wanted.

**Comment by ximex** [comment]
please update to 5.x

**Comment by zamrokk** [comment]
:+1:

**Comment by MMJM** [comment]
:+1:

**Comment by nolanlawson** [comment]
Is this superceded by #10171?
