### ISSUE TITLE
[@types/mongoose] $all undefined

### ISSUE THREAD

**Issue by kerolloz** [DefinitelyTyped/DefinitelyTyped#43317]
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps @avaly @JanNemcik 

I am trying to use Model.exists method for making sure that all the values of an array exist for a field.

```ts
import mongoose from "mongoose";

interface IUser extends mongoose.Document {
    name: string;
}

const User = mongoose.model<IUser>("User", new mongoose.Schema({
    name: {
        type: String
    }
}))

await User.exists({
    name: {
        $all: ["John"],
    }
})
```
it throws the following error `Type 'string[]' is not assignable to type 'undefined'.`.

Here is a [typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBCCA7A5hCBnApnAZlCEOAIkVXW2IG4AoG4JGLKXAQwGMcBJAVWyjhYAHkyQATDAmRpMWAHQARCOwCuILIzgBvGnD1wkrdQC44GGFAYpaAXzrtk5uH2ZwAvFPKy5iMVgA2ADy8-AB8ABTELlDEADQGWADunjLYcgDK7AAWWCCs4Tr6BkZYpoVF+jAAnmClcOkWVrr6djYAlG10rImswPDRcsLA5hgFzXqGJtrjFQAkrP7+pgDaxABSEFlIcSQAsqxQANbEALqxM62dQA) of the same example.

**Comment by Manu1400** [comment]
Change your interface with `string[]` fix the issue:

```javascript
interface IUser extends mongoose.Document {
    name: string[];
}
```

**Comment by kerolloz** [comment]
Hey @Manu1400

Actually, this is not what I want to accomplish. The name should be a string not an array of strings.  
What I want here is to make sure, using `User.exists`, that every name in the array that I provide for the query exists for some user. For example, if my Users collection looks like

![image](https://user-images.githubusercontent.com/36763164/79390108-6ae96700-7f6f-11ea-9957-7ff8aef0bae7.png)

So

```ts
Users.exists({
  name: {
    $all:  [ "Kerollos" ]
  }
});  // returns true ✅

Users.exists({
  name: {
    $all:  [ "Kerollos", "Magdy" ]
  }
});  // returns true ✅

Users.exists({
  name: {
    $all:  [ "Kerollos", "Magdy", "Koko" ]
  }
}); // returns false ❌ => Because, "Koko" doesn't exist as a name for any user

```

Thank you for your reply, though. :smiley:

**Comment by youbek** [comment]
Same when using `.deleteMany`

```
  await User.deleteMany({ _id: {$all: _ids }}) // Type 'string[]' is not assignable to type 'undefined'.ts(2322)
```

**Comment by kerolloz** [comment]
@youbek 

You can use the following workaround 

```ts
return await User.deleteMany({
      // TODO WARNING remove never when $all problem is fixed
      _id: {$all: _ids as never},
    });
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
