### ISSUE TITLE
cannot  new signalR.HubConnectionBuilder() using signalr.d.ts

### ISSUE THREAD

**Issue by tnlthanzeel** [DefinitelyTyped/DefinitelyTyped#43349]
im building a an application where i use typescript. so i got the signalrd.t.s and tried 

`const client = new signalR.HubConnectionBuilder(); ` in my typescript. but it says "cannot find name signalR". please help. im stuck with this for hours

**Comment by peterblazejewicz** [comment]
You're probably reffereing to the SRCore, are you?
https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-3.1&tabs=visual-studio
It's plain TypeScript, no need for type definitions

**Comment by tnlthanzeel** [comment]
yes, its SRCore,i will try the documentation. thanks

**Comment by peterblazejewicz** [comment]
in the case it works, please close that one, thanks!
