### ISSUE TITLE
KoaJS: ctx.attachment() Expected 1 arguments, but got 2.

### ISSUE THREAD

**Issue by christianbundy** [DefinitelyTyped/DefinitelyTyped#43357]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DavidCai1993 @jkeylu @brikou @harryparkdotio chatoo2412

If you do not mention the authors the issue will be ignored.

---

Hi! I'm experiencing a problem where the type definitions conflict with the documentation.

```
src/index.js:424:28 - error TS2554: Expected 1 arguments, but got 2.

424     ctx.attachment(blobId, { type: "inline" });
                               ~~~~~~~~~~~~~~~~~~
Found 1 error.
```

Anything I can do to help debug?

**Comment by peterblazejewicz** [comment]
@christianbundy it seems definition is outdated in that part. TBU
