### ISSUE TITLE
Request ionic framework typings

### ISSUE THREAD

**Issue by Z-Clive** [DefinitelyTyped/DefinitelyTyped#4337]

**Comment by mhartington** [comment]
Hey there, willing to help out with this one. Other than the definition file, what else is needed?

**Comment by zmLGBBM** [comment]
@mhartington Hey Mike, thanks for your help, and the ionic framework you're working on. I do think these .d.ts files are all I need for the time being, that would definitely make developing with ionic much easier and fun. ;)

BTW, I'm mostly a C# developer, maybe others would have some to suggest?

**Comment by jfspencer** [comment]
@zmLGBBM I am currently converting my ionic project to typescript and would be happy to submit a first pull request for ionic. I will gather the work already done and update it for ionic 1.1

**Comment by zmLGBBM** [comment]
@jfspencer Great news! Thanks for your effort! It would be so much easier working with ionic ever since.

**Comment by jakebailey** [comment]
Old issue, but ionic is TS upstream.
