### ISSUE TITLE
Types for sinon v8 and v9?

### ISSUE THREAD

**Issue by lpepin-sama** [DefinitelyTyped/DefinitelyTyped#43414]
- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mrbigdog2u, @rationull, @lumaxis, @nicojs, @43081j, @joshuakgoldberg, ...

Hello,

I'm trying to use the latest version of sinon (9.0.1) but I can't find the right @types/sinon package for it. It seems that the most recent version of the @types package supports up to sinon@7.5.0 only. Are there plans to provide types packages for sinon 8 and 9 in the future? Any timeline on that?

**Comment by 43081j** [comment]
The versions are out of sync right now, the types are still _mostly_ correct for the latest version of sinon. A couple of fixes are in the process of being merged, too, at #43148

But even without that PR you should be able to use most of it just fine with the current types. We will bump the version in the next update.

**Comment by lpepin-sama** [comment]
Ok great, thank you!
