### ISSUE TITLE
Narrowing argument types after calling `toBeInTheDocument`.

### ISSUE THREAD

**Issue by afmfe-iul** [DefinitelyTyped/DefinitelyTyped#43421]
This is a feature request not a bug report.
- [x] I tried using the `@types/testing-library__jest-dom` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @gnapse, @jgoz, @smacpherson64

### Describe the feature you'd like:
Given the following code:

```js
// inputElement is of type `HTMLInputElement | null`
const inputElement = container.querySelector("input"); 
expect(inputElement).toBeInTheDocument();

// I'm assuming that since `toBeInTheDocument()` didn't throw from  now on
// `inputElement` should be of type `HTMLInputElement`, is this assumption correct?

// I get TS errors on inputElement
expect(inputElement.id).toMatch(inputLabel.id); // Object is possibly 'null'.
// (...)
fireEvent.change(inputElement); // Type 'null' is not assignable to type ...
```

I'm wondering if after performing `toBeInTheDocument`, it would be possible to narrow the type of the argument passed in the respective `expect` from `T | undefined | null` to `T`.

The alternative solution I'm using at the moment is adding:
```js
if (!inputElement) {
   throw new Error("Couldn't find the input element.");
}
```

Which seems redundant after calling `expect(inputElement).toBeInTheDocument()`.

### Suggested implementation:
Like suggested by @eps1lon on another issue maybe using [assertion functions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions) would make this possible? This example given in the TS documentation seems relevant:
```js
function assertIsDefined<T>(val: T): asserts val is NonNullable<T> {
    if (val === undefined || val === null) {
        throw new AssertionError(
            `Expected 'val' to be defined, but received ${val}`
        );
    }
}
```

**Comment by jgoz** [comment]
I don't believe this would be possible with assertion functions because the argument is actually passed to `expect`, not `toBeInTheDocument`. Also, I believe we would have to bump the minimum TS version to 3.8, which might break a lot of projects.

**Comment by eps1lon** [comment]
> Also, I believe we would have to bump the minimum TS version to 3.8, which might break a lot of projects.

We can always publish for different versions though there should be a strong argument for it since maintaining forks requires more work.

> I don't believe this would be possible with assertion functions because the argument is actually passed to expect, not toBeInTheDocument.

Yeah I didn't think about that one. Pretty sure you're right. We would need something like `expectToBeInTheDocument()`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
