### ISSUE TITLE
Bent types: Cannot find name 'Response'

### ISSUE THREAD

**Issue by JamesHopkin** [DefinitelyTyped/DefinitelyTyped#43456]
Attempting to compile a ts project, importing `@types/bent` (version 7.0.1) - getting compile error:

```
node_modules/@types/bent/index.d.ts:50:26 - error TS2304: Cannot find name 'Response'.
50     type FetchResponse = Response & { statusCode: number };
```

@Ovyerus, @elibarzilay - any ideas?

**Comment by Ovyerus** [comment]
Do you have the DOM lib loaded in your tsconfig? I think it might be from that - the `fetch()` response object. If that's missing it's probably causing this. Should probably add that as a `///` reference.

**Comment by JamesHopkin** [comment]
This is for a Node project. not a browser project.
I have
```
    "types": ["node"],
    "lib": ["esnext"],
```
in my tsconfig.json.

**Comment by Ovyerus** [comment]
Sounds about right. I'll get around to fixing that in the morning for me.

**Comment by JamesHopkin** [comment]
Much appreciated

**Comment by Ovyerus** [comment]
Ok so it seems to have `dom` in the lib section in tsconfig but for some reason that doesn't work. Including it as a triple slash reference appears to work though.

**Comment by JamesHopkin** [comment]
Fix works for me - thanks!
