### ISSUE TITLE
cannot find Grid components?

### ISSUE THREAD

**Issue by klower** [DefinitelyTyped/DefinitelyTyped#43533]
I cannot import { Grid, Row, Column } from 'carbon-components-react'; others like 'import { Button, Checkbox, Dropdown } from 'carbon-components-react';' is OK.

My config is:
{
  "name": "react-proj-ts",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@carbon/icons-react": "^10.9.2",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react-dom": "^16.9.0",
    "@types/react-redux": "^7.1.5",
    "@types/react-router-dom": "^5.1.3",
    "@types/redux-logger": "^3.0.7",
    "@types/redux-thunk": "^2.1.0",
    "carbon-components": "^10.10.2",
    "carbon-components-react": "^7.10.2",
    "carbon-icons": "^7.0.7",
    "icons-react": "^3.7.1",
    "node-sass": "^4.13.1",
    "node-sass-chokidar": "^1.4.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-redux": "^7.1.3",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.3.0",
    "redux": "^4.0.5"
  },
  "scripts": {
    "build-css": "node-sass-chokidar src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive",
    "start-js": "react-scripts start",
    "start": "npm-run-all -p watch-css start-js",
    "build-js": "react-scripts build",
    "build": "npm-run-all build-css build-js",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/carbon-components-react": "^7.7.1",
    "npm-run-all": "^4.1.5",
    "react-app-rewired": "^2.1.5",
    "typescript": "~3.7.2"
  }
}

**Comment by kalbert312** [comment]
Grid components were added at some point.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
