### ISSUE TITLE
MongooseFilterQuery doesn't support composite primary keys

### ISSUE THREAD

**Issue by gregbacchus** [DefinitelyTyped/DefinitelyTyped#43594]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @avaly @stephane-ruhlmann @horiuchi @lukasz-zak 

If you do not mention the authors the issue will be ignored.

The following causes a type complaint

```typescript
await DeviceModel.findOne({ _id: { deviceTypeId: 'test', deviceId: 'foo' } });
```

```text
Argument of type '{ _id: { deviceTypeId: string; deviceId: string; }; }' is not assignable to parameter of type 'MongooseFilterQuery<Pick<DeviceDocument, "_id" | "deleted">>'.
  Type '{ _id: { deviceTypeId: string; deviceId: string; }; }' is not assignable to type '{ _id?: string | RegExp | ObjectId | { _id: ObjectId; } | QuerySelector<string | RegExp | ObjectId | { _id: ObjectId; }> | undefined; deleted?: Condition<...>; }'.
    Types of property '_id' are incompatible.
      Type '{ deviceTypeId: string; deviceId: string; }' is not assignable to type 'string | RegExp | ObjectId | { _id: ObjectId; } | QuerySelector<string | RegExp | ObjectId | { _id: ObjectId; }> | undefined'.
        Type '{ deviceTypeId: string; deviceId: string; }' has no properties in common with type 'QuerySelector<string | RegExp | ObjectId | { _id: ObjectId; }>'.
```

even though the schema is 

```typescript
interface Device {
  _id: {
    deviceTypeId: string;
    deviceId: string;
  };
  // ..
}

type DeviceDocument = Device & Document;

new Schema<DeviceDocument>({
  _id: {
    type: {
      deviceTypeId: { type: String, required: true },
      deviceId: { type: String, required: true },
    }, required: true,
  },
  // ...
});
```

If seems that the acceptable types for `_id` have been hard coded for `MongooseFilterQuery`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
