### ISSUE TITLE
[styled-components] Support `shouldForwardProp` option

### ISSUE THREAD

**Issue by resir014** [DefinitelyTyped/DefinitelyTyped#43693]
The latest version of styled-components, 5.1.0, has [added support for `shouldForwardProp`](https://github.com/styled-components/styled-components/releases/tag/v5.1.0), which works slightly different than in `emotion`:

```tsx
const Comp = styled('div').withConfig({
  shouldForwardProp: (prop, defaultValidatorFn) => !['filterThis'].includes(prop),
})`
  color: red;
`;

render(<Comp filterThis="abc" passThru="def" />);

// Renders: <div className="[generated]" passThru="def"></div>
```

- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @surgeboris @sandersn @Jessidhia @smockle @Igorbek @Igmat @Lavoaster @eps1lon @flavordaaave @wagerfield @Lazyuki @mgoszcz2

**Comment by mattfwood** [comment]
Is there a way to force Typescript to allow this in the meantime?

**Comment by danilofuchs** [comment]
I would be happy to try to provide the new types for `@types/styled-components`. I will open a branch in my fork so you can take a look.

**Comment by danilofuchs** [comment]
Please check my PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43718
