### ISSUE TITLE
@types/react-query@1.1 Cannot use imported array as query key

### ISSUE THREAD

**Issue by burtyish** [DefinitelyTyped/DefinitelyTyped#43698]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @lukaszfiszer, @igorbek

When I import a query key of the form `[string, string]`, I get a type error.
If I use the same query key without importing it is accepted.

keys.ts
```
export const INCOMPLETE_TODOS_COMBO = ["todos", "incomplete"]
```

index.ts
```
/*
TS2769: No overload matches this call.   The last overload gave the following error.     
Argument of type 'string[]' is not assignable to parameter of type 'string | false | (() => string | false | null | undefined) | null | undefined'.       
Type 'string[]' is not assignable to type 'string'.
*/
function useIncompleteTodosError() {
  return useQuery(INCOMPLETE_TODOS_COMBO, getWhatever);
}

// Same query key as useIncompleteTodosError, but doesn't produce a type error
function useIncompleteTodos() {
  return useQuery(["todos", "incomplete"], getWhatever);
}
```

I think importing keys is important. I want to use constants to avoid typos and to make it easy to track usage of certain keys.

Demo:
https://codesandbox.io/s/react-typescript-pm4ve

**Comment by Igorbek** [comment]
It has nothing to do with the fact the key was imported. It has to do with its type. The inferred type of the key is `string[]`, while the key must have at least 1 element. If you set the type of the key to `[string, string]` it should work.

**Comment by burtyish** [comment]
@igorbek thanks for the response. I see what you mean.
I've changed my exported value as follows and it does work.
```
export const INCOMPLETE_TODOS_COMBO: [string, string] = ["todos", "incomplete"]
```
