### ISSUE TITLE
Chai definitions break types with `should` property

### ISSUE THREAD

**Issue by bevacqua** [DefinitelyTyped/DefinitelyTyped#43744]
Chai exports `interface Object { should: Chai.Assertion }` which [causes issues](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9120) with TS, causing it to infer that any `{}` has an implicit `should` property when my type contains `should`, but then completely fails to reconcile Chai's `should` with my own type declaration.

When I update Cypress — which has a dependency on Chai — `tsc` throws tens of errors.

Contrived example:

```ts
interface QueryContainer {
  bool?: BoolQuery
  …
}

interface BoolQuery {
  must?: QueryContainer[]
  should?: QueryContainer[]
  must_not?: QueryContainer[]
  filter?: QueryContainer[]
}

const query: QueryContainer = { bool: {} }
```

Was fine before, but with `cypress@4.3.0`:

```
whatever.ts:109:5 - error TS2322: Type '{ must: ({ term: { 'metadata.key': { value: string; }; }; } | { term: { 'metadata.value.keyword': { value: string; }; }; })[]; }' is not assignable to type 'BoolQuery'.
  Types of property 'should' are incompatible.
    Type 'Assertion' is not assignable to type 'QueryContainer[]'.

109     bool: {
        ~~~~

  whatever_types.ts:6467:3
    6467   bool?: BoolQuery
           ~~~~
    The expected type comes from property 'bool' which is declared here on type 'QueryContainer'

```

We can refine it a bit and get a better error:

```ts
const boolQ: BoolQuery = {}
const query: QueryContainer = { bool: boolQ }
```

Now we get:

```
whatever.ts:81:9 - error TS2322: Type '{}' is not assignable to type 'BoolQuery'.
  Types of property 'should' are incompatible.
    Type 'Assertion' is not assignable to type 'QueryContainer[]'.

81   const boolQ: BoolQuery = {}
           ~~~~~
```

If my `BoolQuery` type doesn't have its own `should` property that's incompatible with `Chai.Assertion`, then there's no problem, it's only when I have my own `should` property that the clash happens

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
