### ISSUE TITLE
[@types/pdfmake] type errors

### ISSUE THREAD

**Issue by princemaple** [DefinitelyTyped/DefinitelyTyped#43758]
As discussed in #42991, opening this PR as a reference.

1.
```ts
type TableLayout = PredefinedTableLayout | CustomTableLayout;
```

should probably be `PredefinedTableLayout | {[key: string]: CustomTableLayout}`

Reference from docs:
https://pdfmake.github.io/docs/document-definition-object/tables/
```js
pdfMake.tableLayouts = {
  exampleLayout: {
    hLineWidth: function (i, node) {
      if (i === 0 || i === node.table.body.length) {
        return 0;
      }
      return (i === node.table.headerRows) ? 2 : 1;
    },
    vLineWidth: function (i) {
      return 0;
    },
    hLineColor: function (i) {
      return i === 1 ? 'black' : '#aaa';
    },
    paddingLeft: function (i) {
      return i === 0 ? 0 : 8;
    },
    paddingRight: function (i, node) {
      return (i === node.table.widths.length - 1) ? 0 : 8;
    }
  }
};
```

2.
```ts
export function createPdf(
    documentDefinitions: TDocumentDefinitions,
    tableLayouts?: TableLayout,
    fonts?: TFontDictionary,
    vfs?: TFontDictionary,  // <- this
): TCreatedPdf;
```

is wrong as well, vfs type is different from fonts type, hence should not be TFontDictionary.

vfs looks like this
```js
{
  "Roboto-Italic.ttf": "AAEAAAASAQAABAAgR0RFRrRCsIIAAjGsAAA....base64 of font binary",
  "Roboto-Medium.ttf": "AAEAAAASAQAABAAgR0RFRrRCsIIAAiL8AAA....",
  "Roboto-MediumItalic.ttf": "AAEAAAASAQAABAAgR0RFRrRCsIIAAjW8AAAC....",
  "Roboto-Regular.ttf": "AAEAAAASAQAABAAgR0RFRrRCsIIAAijcAA...."
}
```

should probably just be any flat object.

/cc @jeralm

**Comment by syffs** [comment]
1. according to the [mentioned documention](https://pdfmake.github.io/docs/document-definition-object/tables/), to support user-defined layouts, this should be:
```ts
type TableLayout = string | PredefinedTableLayout | CustomTableLayout;
```
hence the below `tableLayouts` is supposed to hold these user-defined layouts:
```ts
export interface BufferOptions {
    fontLayoutCache?: boolean;
    bufferPages?: boolean;
    tableLayouts?: TableLayout;
    autoPrint?: boolean;
    progressCallback?: (progress: number) => void;
}
```
so `tableLayouts` should be of type `{[key: string]: CustomTableLayout}`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
