### ISSUE TITLE
[@types/node/events] Unable to declare events in derived classes of EventEmitter

### ISSUE THREAD

**Issue by zcbenz** [DefinitelyTyped/DefinitelyTyped#43754]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Flarna @a-tarasyuk @galkin @tdreyno @trivikr @SimonSchick 

When doing declarations like this:

```typescript
import events = require('events');

declare namespace Electron {

  class Base extends events.EventEmitter {
    on(event: 'blur', listener: Function): this;
  }

  class Derive extends Base {
    on(event: 'enter-html-full-screen', listener: Function): this;
  }
}
```

Typescript would throw this error:

```
main.ts:10:5 - error TS2416: Property 'on' in type 'Derive' is not assignable to the same property in base type 'Base'.
  Type '(event: "enter-html-full-screen", listener: Function) => this' is not assignable to type '(event: "blur", listener: Function) => this'.
    Types of parameters 'event' and 'event' are incompatible.
      Type '"blur"' is not assignable to type '"enter-html-full-screen"'.

10     on(event: 'enter-html-full-screen', listener: Function): this;
       ~~
```

There is no error if the `Derive` does not declare any event.

**Comment by SimonSchick** [comment]
Try defining interfaces and use declaration merging instead.

**Comment by zcbenz** [comment]
We ended up putting the events in base class to work around this.
