### ISSUE TITLE
jquery.when problem

### ISSUE THREAD

**Issue by spustlik** [DefinitelyTyped/DefinitelyTyped#4377]
Hi, 
I wanted to use $.when( ) with some promises to achieve waiting for all promises to be done /or any revoked.
TS definition allows me to use similar syntax to c# **await Task.WhenAll(array of tasks/awaitables)** so I used **$.when(array of promises)**. 
My promises returns **typed** results, each is of another type.

``` typescript
var promises = [];
promises.push(this.GetData1Async());
promises.push(this.GetData2Async());
$.when(promises)
.done((result)=>this.processResult(result[0], result[1]))
```

But it doesn't work. When reading doc for $.when, I found possible bug in definition - current definition 

``` TypeScript
when<T>(...deferreds: Array<T|JQueryPromise<T>/* as JQueryDeferred<T> */>): JQueryPromise<T>;
```

allows only to use array of promises with same type of result, so probably in my case, it is treat as object, and promise is not processed well. It calls done immediately, not waiting to resolve.

I can't figure the solution, but creating and issue to know, that this function can be used in way, when it doesn't work as expected.

**Comment by Kinchkun** [comment]
> But it doesn't work.

Can you provide the error message? 

Did this work?:

    $.when([this.GetData1Async(), this.GetData2Async())])
    .done((result)=>this.processResult(result[0], result[1]))

**Comment by vukasin0** [comment]
I just want to point that when has multiple signatures but only one as in current definitions.

I can provide only one promise object to when but not only array as it is now.

It would be nice to update definitions.

**Comment by vvakame** [comment]
@johnnyreilly

**Comment by johnnyreilly** [comment]
PRs welcome

**Comment by Gidmark** [comment]
I second this, worked around it by using (<any>$).when

This will return an error, but work fine with the <any> workaround:
`$.when(this.loadCars(), this.loadMaps()).then((cars: Array<Car>, maps: Array<Map>) => {

**Comment by vukasin0** [comment]
@Gidmark - workaround is still workaround :)

It would be nice to have it properly done - I'm running out of free time these days so I'm not good candidate for PR :(

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
