### ISSUE TITLE
the return value type of node.stream.destroy method is this, not void

### ISSUE THREAD

**Issue by LongTengDao** [DefinitelyTyped/DefinitelyTyped#43782]
If you know how to fix the issue, make a pull request instead.

I try to make a PR, but the check failed, and I can't figure out why. #43704 Maybe someone can fix this, I closed my PR ahead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @microsoft @DefinitelyTyped @jkomyno @a-tarasyuk @alvis @r3nya @btoueg @BrunoScheufler @smac89 @tellnes @Touffy @DeividasBakanas @eyqs @Flarna @Hannes-Magnusson-CK @KSXGitHub @hoo29 @kjin @ajafff @islishude @mwiktorczyk @mohsen1 @n-e @octo-sniffle @galkin @parambirs @eps1lon @SimonSchick @ThomasdenH @WilcoBakker @wwwy3y3 @samuela @kuehlein @j-oliveras @bhongy @chyzwar @trivikr @nguymin4 @yoursunny @qwelias @ExE-Boss @Ryan-Willpower @peterblazejewicz

If you do not mention the authors the issue will be ignored.

**Comment by Flarna** [comment]
This was the error message in CI test:
```
Error in node
Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/node/http.d.ts:331:9
ERROR: 331:9  expect  TypeScript@3.1 compile error: 
Property 'destroy' in type 'IncomingMessage' is not assignable to the same property in base type 'Readable'.
  Type '(error?: Error | undefined) => void' is not assignable to type '(error?: Error | undefined) => this'.
    Type 'void' is not assignable to type 'this'.
```
I would expect that you changed the API of a base class `Readable` but forgot to adapt subclass `IncomingMessage`.

**Comment by LongTengDao** [comment]
Thank you!

But in fact `IncompingMessage` wont return this, it's not extends `Readable` in fact. I would open an issue in Node js to discuss this problem first.

**Comment by Flarna** [comment]
Seems I doesn't return `this` but it extends `Readable`: https://github.com/nodejs/node/blob/master/lib/_http_incoming.js#L84

To my understanding this is something that works in  Javascript (even I think it should not be done) but typescript can't model this.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
