### ISSUE TITLE
[@types/webpack] New issue introduced with 4.41.10: Types of property 'libraryTarget' are incompatible

### ISSUE THREAD

**Issue by kaiyoma** [DefinitelyTyped/DefinitelyTyped#43787]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @bumbleblym @bcherny @tommytroylin @mohsen1 @jcreamer898 @alan-agius4 @elliottsj @jason0x43 @dennispg @christophehurpeau @ZSkycat @johnnyreilly @rwaskiewicz @kuehlein @grgur @rubenspgcavalcante @andersk @ofhouse @danielthank @sasurau4 @dionshihk

Version 4.41.9 of this package works fine, but upgrading to 4.41.10 leads to this error while type checking:

```
server.ts:98:46 - error TS2345: Argument of type 'Configuration' is not assignable to parameter of type 'Configuration |
 Configuration[]'.
  Type 'import(".../node_modules/@types/webpack/index").Configuration' is not assignable to type 'import(".../node_modules/@types/webpack-dev-server/node_modules/@types/webpack/index").Configuration'.
    Types of property 'output' are incompatible.
      Type 'import(".../node_modules/@types/webpack/index").Output | undefined' is not assignable to type 'import(".../node_modules/@types/webpack-dev-server/node_modules/@types/webpack/index").Output | undefined'.
        Type 'import(".../node_modules/@types/webpack/index").Output' is not assignable to type 'import(".../node_modules/@types/webpack-dev-server/node_modules/@types/webpack/index").Output'.
          Types of property 'libraryTarget' are incompatible.
            Type '"window" | "var" | "global" | "system" | "assign" | "this" | "commonjs" | "commonjs2" | "amd" | "umd" | "jsonp" | undefined' is not assignable to type '"window" | "var" | "global" | "assign" | "this" | "commonjs" | "commonjs2" | "amd" | "umd" | "jsonp" | undefined'.
              Type '"system"' is not assignable to type '"window" | "var" | "global" | "assign" | "this" | "commonjs" | "commonjs2" | "amd" | "umd" | "jsonp" | undefined'.

98     WebpackDevServer.addDevServerEntrypoints(config, options);
                                                ~~~~~~
```

We're not doing anything with `libraryTarget` in our code, let alone assigning `'system'` to it.

**Comment by kaiyoma** [comment]
@Geit This seems to be the commit that caused the breakage: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43491/commits/161f757e5a5a06ad915f21f9f322c0d6b01a7b1c

**Comment by kaiyoma** [comment]
For reference, we're already using the latest version of both webpack-dev-server packages:

```
    "webpack-dev-server": "3.10.3",
    "@types/webpack-dev-server": "3.10.1",
```

**Comment by ofhouse** [comment]
Seems more like a problem with your package manager than with the types itself.
You have two versions of the webpack types installed (at the locations /`node_modules/@types/webpack` and `/node_modules/@types/webpack-dev-server/node_modules/webpack`).
Maybe removing the `node_modules` folder and reinstalling the packages helps.
Otherwise you need to manually resolve the `@types/webpack` package to a single version in your `package.json`.

**Comment by ofhouse** [comment]
For reference: There is a similar issue raised here which describes a current problem with yarn's resolve algorithm: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/43232

**Comment by kaiyoma** [comment]
Yeah, this wouldn't be the first time I've had problems with yarn, and it definitely won't be the last. Thanks for the tips, I'll try them now.

**Comment by kaiyoma** [comment]
Yup, I tracked it down to a version mismatch with dependencies. Thanks for the help!
