### ISSUE TITLE
[@types/agenda] wrong parameter number for agenda.jobs

### ISSUE THREAD

**Issue by FedeBev** [DefinitelyTyped/DefinitelyTyped#43800]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/xxxx` package and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @princjef, @meirgottlieb

---

Hi there,

according to the documentation of [agenda](https://github.com/agenda/agenda), the [function agenda.jobs](https://github.com/agenda/agenda#jobsmongodb-native-query-mongodb-native-sort-mongodb-native-limit-mongodb-native-skip)
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1a9431f33abe2c9123909b295c4531f3d35637b0/types/agenda/index.d.ts#L99

accepts 4 parameters, the last 3 optional.
In my opinion the definition should be

```ts
/**
 * Find all Jobs matching `query` and pass same back in cb().
 * @param query
 */
jobs<T extends Agenda.JobAttributesData = Agenda.JobAttributesData>(query: any, sort?: any, limit?: number, skip?: number): Promise<Agenda.Job<T>[]>;
```
or, (maybe better? but would be a breaking change)

```ts
/**
 * Find all Jobs matching `query` and pass same back in cb().
 * @param query
 */
jobs<T extends Agenda.JobAttributesData = Agenda.JobAttributesData>(query: any, sort: any | null, limit: number | null, skip: number | null): Promise<Agenda.Job<T>[]>;
```

Maybe also bump the major version would be a good idea in order to be aligned with the agenda version, at least for the major.
Regarding public APIs there aren't any breaking changes from v2 to v3  

If PR with this fix are welcome I can deal with that soon.

thanks

**Comment by KiruyaMomochi** [comment]
I meet this problem too.
From the source code of agenda.js:
```javascript
/**
 * Finds all jobs matching 'query'
 * @name Agenda#jobs
 * @function
 * @param {Object} query object for MongoDB
 * @param {Object} sort object for MongoDB
 * @param {Number} limit number of documents to return from MongoDB
 * @param {Number} number of documents to skip in MongoDB
 * @returns {Promise} resolves when fails or passes
 */
module.exports = async function(query = {}, sort = {}, limit = 0, skip = 0) {
  const result = await this._collection
    .find(query)
    .sort(sort)
    .limit(limit)
    .skip(skip)
    .toArray();

  return result.map(job => createJob(this, job));
};
```

Too tired today. I may fix it if there is no one fixes it until tomorrow.
