### ISSUE TITLE
[@types/vscode] breaks vscode-languageclient package

### ISSUE THREAD

**Issue by kjeremy** [DefinitelyTyped/DefinitelyTyped#43805]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond. (It is unclear who the author of this package is based on the `index.d.ts` file)
  - Authors: @octref

Upgrading to @types/vscode 1.44 breaks users who also use the vscode-languageclient package.  See https://github.com/microsoft/vscode-languageserver-node/issues/610

**Comment by octref** [comment]
Please track it in https://github.com/microsoft/vscode-languageserver-node/issues/610.
