### ISSUE TITLE
ReactDOM.createRoot does not support 

### ISSUE THREAD

**Issue by pejman1** [DefinitelyTyped/DefinitelyTyped#43848]
I have got this error when I use react concurrent mode . ReactDOM.createRoot 
TS2339: Property 'createRoot' does not exist on type 'typeof import

**Comment by mmvsk** [comment]
It's an experimental feature of React, so it's not yet available here. Just ignore that line using `@ts-ignore`:

```
// @ts-ignore
ReactDOM.createRoot(root).render(<App />);
```

**Comment by eps1lon** [comment]
Check out https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7ec01838c4ba1066b3c456492473dcaa44ddf5cd/types/react/experimental.d.ts#L1-L25 on how to add typings for `react@experimental`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by martinKindall** [comment]
Still happening with following setup:

  `"@types/jest": "^27.4.1",
    "@types/node": "^16.11.26",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-scripts": "5.0.0",
    "typescript": "^4.6.3",`

**Comment by folt** [comment]
I'm getting the same error, can you tell me the status of the solution to the problem? Maybe a contribution is needed?

**Comment by eps1lon** [comment]
`createRoot` is available on `react-dom/client`. You need `@types/react-dom@^18.0.0` installed.

**Comment by alyc** [comment]
Still happening for me too, I am using 
    "@types/react": "^18.0.5",
    "@types/react-dom": "^18.0.1",

**Comment by JasonKleban** [comment]
Still getting `Cannot find module 'react-dom/client' or its corresponding type declarations.` with `"@types/react-dom": "^18.0.1"`

**Comment by djmisterjon** [comment]
plz reopen type is not avaible
![image](https://user-images.githubusercontent.com/24865815/167250955-08107402-a322-4fdf-9ca9-8032308d0cd8.png)
![image](https://user-images.githubusercontent.com/24865815/167250936-d5cc1cac-dd4b-4793-8114-2121c96ab4f3.png)
![image](https://user-images.githubusercontent.com/24865815/167250978-49259e18-ad37-4dca-b29c-7ede78f0c464.png)

**Comment by Yooooomi** [comment]
It works when importing from `'react-dom/client';`

```
import { createRoot } from 'react-dom/client';

const element = document.getElementById('root');
const root = createRoot(element!);
```

**Comment by henry-filosa** [comment]
[This doesn't appear to work for users of UMD imports](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64112).
