### ISSUE TITLE
Conflict using @types/mocha and @types/jest Subsequent variable declarations must have the same type.  Variable 'beforeEach' must be of type 'Lifecycle', but here has type 'HookFunction'

### ISSUE THREAD

**Issue by jogibear9988** [DefinitelyTyped/DefinitelyTyped#43912]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

Mocha:
@kazimanzurrashid @otiai10 @jt000 @enlight @cspotcode @1999 

Jest:
@NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @ahnpnl @joshuakgoldberg @UselessPickles @r3nya @hotell @sebald @andys8 @antoinebrault @favna @gstamac @ExE-Boss @quassnoi @Belco90 @tonyhallett @ycmjason @devanshj @pawfa @regevbr 

I need to use both Type declarations (we use jest for testing, and mocha is used by cypress)

**Comment by Favna** [comment]
This is an interesting issue and it looks like it's also a well known problem in the Cypress community. Have you attempted solutions proposed in places like the following?
- This issue on the Cypress repo: https://github.com/cypress-io/cypress/issues/281
  - Which mentions the medium article down below as well as this NPM package: https://www.npmjs.com/package/cypress-jest-adapter
- This sample repo that claims to resolve it: https://github.com/cypress-io/cypress-and-jest-typescript-example
- And this medium article: https://medium.com/@NicholasBoll/using-jest-matchers-in-cypress-5e8e7281f5dd

**Comment by JessicaSachs** [comment]
This has been fixed here https://github.com/cypress-io/cypress/issues/6690

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by texuf** [comment]
In case it helps anyone, I fixed this in a different package by adding `"skipLibCheck": true` in the modules `tsconfig.json`

**Comment by NoodleOfDeath** [comment]
I am getting this issue too, not sure what causes it

**Comment by iamgabrielsoft** [comment]
mocha and jest are conflicting themselve, uninstall the two and install jest back
