### ISSUE TITLE
d3: xhr bad callback type definitions?

### ISSUE THREAD

**Issue by jarandaf** [DefinitelyTyped/DefinitelyTyped#4394]
Are callback types correct in [xhr](https://github.com/borisyankov/DefinitelyTyped/blob/master/d3/d3.d.ts#L300) methods? 

Currently callback types are `(xhr: XMLHttpRequest) => void`. I would expect them to be something like `(error: any, data: any) => void`. 

I am pretty new to Typescript itself so I am not sure about that. The thing is that with the current type definition I wonder how I could trigger an HTTP POST JSON request with d3 API. The following is not possible:

``` js
d3.xhr(someURL)
    .header('Content-Type', 'application/json')
    .post(body, (error, data) => {
      if (error){
        console.error(error);
      } else {
        console.log(data);
      }
    });
```

**Comment by jarandaf** [comment]
PR #4395

**Comment by tomwanzek** [comment]
As part of some legacy D3v3 issue clean-up, can this issue be please closed?

D3v4 has been released and supported with actively maintained definitions for several months now, so it would be great to have only current issues open for clarity.

Thanks in advance!

cc @gustavderdrache @andy-ms
