### ISSUE TITLE
[@types/webpack] TS error when importing Stats class from Webpack package.

### ISSUE THREAD

**Issue by ernestostifano** [DefinitelyTyped/DefinitelyTyped#43952]
If you know how to fix the issue, make a pull request instead.

- [✅] I tried using the `@types/webpack` package and had problems.
- [✅] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [❌] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [✅] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo, @bumbleblym, @bcherny, @tommytroylin, @mohsen1, @jcreamer898, @alan-agius4, @elliottsj, @jason0x43, @dennispg, @christophehurpeau, @ZSkycat, @johnnyreilly, @rwaskiewicz, @kuehlein, @grgur, @rubenspgcavalcante, @andersk, @ofhouse, @danielthank, @sasurau4, @dionshihk 

If you do not mention the authors the issue will be ignored. ***(<- sorry guys... I am seeking no troubles, I promise! Nice to meet you all.)***

([Original Issue](https://github.com/webpack/webpack/issues/10711))

**What is the current behavior?**

```js
import {Stats} from 'webpack';

/* [...] */

const stats = new Stats(compilation);
```

TypeScript throws: ***"TS2511: Cannot create an instance of an abstract class."***

Could it be a problem with Webpack's `index.d.ts` file? Stats class is marked as abstract.

***NOTE:*** I only use TypeScript for type checking and declaration files generation for JS files with JSDoc annotations. So I am really not very familiar with TypeScript syntax. Maybe there is something that I'm missing.

**Other relevant information:**
webpack version: 4.42.1
Node.js version: 13.12.0
Operating System: macOS Catalina 10.15.3
Additional tools: N/A

**Comment by ofhouse** [comment]
Yeah seems like a mistake that `Stats` is abstract, it is definitely exported by the package (https://github.com/webpack/webpack/blob/v4.42.1/lib/webpack.js#L137).
It was added 3 years ago, maybe then it was an abstract thing (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/5c432057da8f089bac5fdf07b5606d4f771922f4).

Feel free to send a PR to fix it.
