### ISSUE TITLE
[@types/jasmine] Jasmine toHaveBeenCalledWith matcher treats optional method arguments as required under some conditions

### ISSUE THREAD

**Issue by Maximaximum** [DefinitelyTyped/DefinitelyTyped#43989]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @davidparsson @borisyankov 

Please consider this case:

```typescript
class Service {
    setValue(value: string, option?: undefined): void;
    setValue(value: string, option: string): void;
    setValue(value: string, option: string | undefined): void { /* some implementation*/ }
}

const service = new Service();

expect(service.setValue).toHaveBeenCalledWith('v'); 
//                       ^ Gives a ts error "Expected 2 arguments, but got 1. (2254)"

// Even though all of these use cases are valid and work fine:
service.setValue('v');
service.setValue('v', undefined);
service.setValue('v', 'someValue');
```

For some reason, the `toHaveBeenCalledWith()` matcher only accepts 2 arguments, even though the method under test (`setValue()`) has a second argument that is optional.

The expected behavior is that `expect(service.setValue).toHaveBeenCalledWith('v');` should not throw a ts compilation error.

Note: one might think that this can be worked around by adding a second parameter of `undefined` (like `expect(service.setValue).toHaveBeenCalledWith('v', undefined);`). However, calling `service.setValue('v');` is different from `service.setValue('v', undefined);`, since the value of `arguments.length` object inside the `setValue()` method is different.

**Comment by Maximaximum** [comment]
@davidparsson @boriskor would you mind to take a look into this issue?

**Comment by Maximaximum** [comment]
Actually it seems to be a duplicate of #42455

**Comment by kolodny** [comment]
Note that if you supply an overload that handles all those cases it works as expected:

```ts
class Service {
    setValue(value: string, option?: undefined): void;
    setValue(value: string, option: string): void;
    setValue(value: string, option?: string): void
    setValue(value: string, option?: string): void { /* some implementation*/ }
}

const service = new Service();

expect(service.setValue).toHaveBeenCalledWith('v');
```
