### ISSUE TITLE
[@types/react] add enterkeyhint attribute to input and textarea 

### ISSUE THREAD

**Issue by IljaDaderko** [DefinitelyTyped/DefinitelyTyped#43985]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon @zieka @dancerphil @dimitropoulos @disjukr @vhfmag

There is experimental input and textarea attribute `enterkeyhint` https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes that does not seem to be supported by type definitions. Even though experimental it is supported on latest releases of safari and chrome, perhaps it would be a good idea to add it?

Currently following error pops up when trying to use it in react:

<img width="1076" alt="Screenshot 2020-04-17 at 14 57 06" src="https://user-images.githubusercontent.com/3154053/79566893-f6700e80-80bb-11ea-8174-6a33c9778c42.png">

**Comment by eps1lon** [comment]
We shouldn't get this in before https://github.com/facebook/react/pull/18634.

Right now you can add it by using `enterkeyhint" and  module augmentation (see [Adding non-standard attributes](https://github.com/typescript-cheatsheets/react-typescript-cheatsheet/blob/master/docs/advanced/types-react-ap.md#adding-non-standard-attributes)). But the name will change later.

I also wouldn't consider it experimental. It's in the WHATWG spec. We just need to update the data upstream (https://github.com/mdn/browser-compat-data/pull/5990, https://github.com/mdn/sprints/issues/3109, https://github.com/microsoft/TSJS-lib-generator/pull/853). TS typings will have it in 4.0 apparently (https://github.com/microsoft/TSJS-lib-generator/pull/853#issuecomment-614726763).

**Comment by jens-duttke** [comment]
@eps1lon Since this is part of the already released React 17, when will the type definition get updated?

**Comment by eps1lon** [comment]
> @eps1lon Since this is part of the already released React 17, when will the type definition get updated?

Once #48971 is released.
