### ISSUE TITLE
@types/hapi__mimos typescript compilation

### ISSUE THREAD

**Issue by luiso1979** [DefinitelyTyped/DefinitelyTyped#43987]
When trying to build hapi19 there is a typescript error in **@types/hapi__mimos** because it cannot find **MimeEntry** in **@types/mime-db**

![image](https://user-images.githubusercontent.com/1564488/79576618-de03f200-80c3-11ea-8c92-be1d8f45a1cd.png)

Thanks

**Comment by SimonSchick** [comment]
Working fine here, try re-installing.
