### ISSUE TITLE
Catch is not defined on es6-promise Thenable

### ISSUE THREAD

**Issue by wjohnsto** [DefinitelyTyped/DefinitelyTyped#4400]
@JsonFreeman

Is there a reason for `catch` not being defined on `Thenables` for the es6-promise library? The standard way I use promises is below:

```ts
import {Promise} from 'es6-promise';

var someFunction: (): Thenable<any>;

someFunction().then((result) => {
    // process result
    ...
}).catch((error) => {
    // handle error
    ...
});

// OR

someFunction().catch((error) => {
    // handle error and return
    ...
}).then((result) => {
    // process result
    ...
});
```

Without some sort of typing for `catch` on a `Thenable` it makes the `catch` method on `Promise` rather useless.

EDIT: I would add them myself and submit a PR, but I was wondering if there was some definitive reason as to why it was left out.

**Comment by JsonFreeman** [comment]
Sorry @wjohnsto, somehow I missed this. The reason is simply that `catch` is not part of the promise standard.

**Comment by wjohnsto** [comment]
I appears it is!

http://www.ecma-international.org/ecma-262/6.0/#sec-promise.prototype.catch

**Comment by JsonFreeman** [comment]
Yes, my bad. That is the Promise, but Thenable should just have `then`.

**Comment by alexeagle** [comment]
@JsonFreeman appears to indicate in the most recent comment that `catch` doesn't belong on `Thenable` but it was added in #7653

This break's Angular's usage as well. It is not consistent with upstream typings in TypeScript/lib either:

https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2015.promise.d.ts
```
interface Promise<T> {
    catch(onrejected?: (reason: any) => T | PromiseLike<T>): Promise<T>;
}
```
suggests that `Thenable` should structurally match `PromiseLike` but it does not:

https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es5.d.ts
```
interface PromiseLike<T> {
    then<TResult>(onfulfilled?: (value: T) => TResult | PromiseLike<TResult>, onrejected?: (reason: any) => TResult | PromiseLike<TResult>): PromiseLike<TResult>;
    then<TResult>(onfulfilled?: (value: T) => TResult | PromiseLike<TResult>, onrejected?: (reason: any) => void): PromiseLike<TResult>;
}
```

I suggest we revert the addition of `catch` on `Thenable`. The OP should be solved by using the `Promise` type when you want to do error handling.
