### ISSUE TITLE
version 13.13 Interface 'Require' incorrectly extends interface 'RequireFunction'.

### ISSUE THREAD

**Issue by damianof** [DefinitelyTyped/DefinitelyTyped#44019]
Issue:
Interface 'Require' incorrectly extends interface 'RequireFunction'.
  Types of property 'cache' are incompatible.
    Type 'Dict<NodeModule>' is not assignable to type '{ [id: string]: NodeModule; }'.
      Index signatures are incompatible.
        Type 'NodeModule | undefined' is not assignable to type 'NodeModule'.
          Type 'undefined' is not assignable to type 'NodeModule'.ts(2430)

Caused by field cache: Dict&lt;NodeModule&gt; (changing to Dict&lt;any&gt; fixes it but not sure that is the accepted solution)

interface Require {
        /* tslint:disable-next-line:callable-types */
        (id: string): any;
        resolve: RequireResolve;
        cache: Dict<NodeModule>;
        /**
         * @deprecated
         */
        extensions: RequireExtensions;
        main: Module | undefined;
    }

**Comment by nguyenkhois** [comment]
I have the same issue when using React v16.3.1 + TypeScript 3.8.3  in Storybook project.
`ERROR in /.../node_modules/@types/node/globals.d.ts(1075,15);`

**Comment by scambier** [comment]
Same issue here with the default template for the Vue CLI Plugin Electron Builder

**Comment by Stoom** [comment]
Same with updating a dependencies in a vue app.

**Comment by damianof** [comment]
By any chance, anyone has had the time to see what type we can use instead of "any" ? I tried changing to Dict<NodeModule | undefined> but still complains and did not have the time to look deeper into it as i am currently fixing our CI server environment because of this.

**Comment by pkjy** [comment]
It seems a repeated declaration .I find the other declaration in file `@types\webpack-env\index.d.ts` in my node_modules.Where `cache` is declare as follow:
```... ohter codes ...
   cache: {
            [id: string]: NodeModule;
   }
```
And it's not  assignable to type `Dict<NodeModule>` in `node_modules\@types\node\globals.d.ts`.
I just change code in  `node_modules\@types\node\globals.d.ts` from 
```
interface Require {
        /* tslint:disable-next-line:callable-types */
        (id: string): any;
        resolve: RequireResolve;
        cache: Dict<NodeModule>;
        /**
         * @deprecated
         */
        extensions: RequireExtensions;
        main: Module | undefined;
    }
```
to 
```
interface Require {
        /* tslint:disable-next-line:callable-types */
        (id: string): any;
        resolve: RequireResolve;
        cache:  {
          [id: string]: NodeModule;
        }
        /**
         * @deprecated
         */
        extensions: RequireExtensions;
        main: Module | undefined;
    }
```
and temporarily fix the error .

**Comment by damianof** [comment]
We could try submitting a pull request with @pkjy suggestion I guess (or we can wait for a bit more feedback first)

**Comment by Joehunk** [comment]
Same, using TS 3.8.3 but not Vue.

**Comment by DevAngsy** [comment]
Same issue when using TS 3.8.3.

**Comment by DeepSeaPenguin2015** [comment]
Same issue when using TS 3.5.3 and @types/node 13.11.1  in a Vue system

**Comment by thegeekyglass** [comment]
@DeepSeaPenguin2015 I got 13.11.1 to work with vue, make sure your node_modules doesn't contain the lastest version and you don't have it installed locally.

**Comment by DeepSeaPenguin2015** [comment]
@thegeekyglass my node don't globally, how to make sure node_modules doesn't contain the lastest version, don't understand the words

**Comment by thegeekyglass** [comment]
@DeepSeaPenguin2015, I deleted the whole node_modules folder for the package/project i was working on and ran "npm install" after including "@types/node": "13.11.1" in my dev dependencies.  This also worked around the issue when the build was run a build server (Azure DevOps)

**Comment by DeepSeaPenguin2015** [comment]
@thegeekyglass Yes, I deleted the node_modules/@types/node file and "npm install @types/node@13.11.1 --save-dev", amzing it working now. Thank you very much !

**Comment by tx-steven** [comment]
Ran into this issue as well when updating ```@types/node```. Rolling it back solved the problem.

**Comment by dmitrirussu** [comment]
same issue

**Comment by dmitrirussu** [comment]
> @thegeekyglass Yes, I deleted the node_modules/@types/node file and "npm install @types/node@13.11.1 --save-dev", amzing it working now. Thank you very much !

thanks

**Comment by therealpaulgg** [comment]
Can confirm this issue, I have been getting the same issue at seemingly random times working in my Vue.JS projects. The instructions to downgrade to @types/node@13.11.1 worked.

**Comment by syabro** [comment]
@tdeekens is new version released?

**Comment by tdeekens** [comment]
Sorry? Version of what? We pinned our code to an earlier version of the types.

**Comment by roikoren755** [comment]
If anyone is still having this issue and finds this thread, for me updating `@types/webpack-env` fixed the problem

**Comment by EvHaus** [comment]
Upgrading to v14.6.0 seems to have resolved this issue for us.

**Comment by trumbitta** [comment]
I'm having the issue with v16.11.7
