### ISSUE TITLE
Generated Protobuf Map doesn't match all necessary methods

### ISSUE THREAD

**Issue by hc-denissilva** [DefinitelyTyped/DefinitelyTyped#44049]
When the following Message:
```typescript
// Message that encapsulates a map
message DomainMap {
  // Map of domain
  map<string, Domain> domains = 1;
}
```

Is compiled to TS this will generate:
```typescript
export class DomainMap extends jspb.Message {
  getDomainsMap(): jspb.Map<string, Supplier>;
  clearDomainMap(): void;
  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): DomainMap.AsObject;
  static toObject(includeInstance: boolean, msg: DomainMap): DomainMap.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: SupplierMap, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): SupplierMap;
  static deserializeBinaryFromReader(message: SupplierMap, reader: jspb.BinaryReader): DomainMap;
}
```

But when I create a method to return a map of specified map of the message, this will throw an error of missing methods (_This scenario my Domain = Supplier in my project_):
![image](https://user-images.githubusercontent.com/58428854/79762027-7ac3cb00-8322-11ea-96fd-84c3607abe9a.png)

Type Definition:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/069f404e6611098c620a265d05782db36efb4fc6/types/google-protobuf/index.d.ts#L170

Project tsconfig.json:
```json
{
  "compilerOptions": {
    "allowJs": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "strict": true,
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es2017",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "inlineSourceMap": false,
    "outDir": "dist",
    "baseUrl": ".",
    "typeRoots": ["src/application/types", "node_modules/@types"]
  },
  "include": [
    "src/**/*",
    "src/**/*.json"
  ]
}
```

Is there a reason to the Map method to have a del instead of a delete implementation ? The same for the other differences ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
