### ISSUE TITLE
@types/compression:1.7.0 not working with latest express typings

### ISSUE THREAD

**Issue by deusama** [DefinitelyTyped/DefinitelyTyped#44043]
```typescript
import express from 'express'
import compression from 'compression'
const app = express()
app.use(compression())
```

This is not working anymore since typings in compression seem to be incorrect with latest @types/express 4.17.6 .. anyone has a solution?

@santialbo @rburgt @neilbryson @peterblazejewicz

**Comment by peterblazejewicz** [comment]
@desuama

```ts
import express = require('express')
import compression = require('compression')
const app = express()
app.use(compression())
```
this is covered by tests in `@types/compression`.
For above to work:
```ts
import express from 'express'
import compression from 'compression'
const app = express()
app.use(compression())
```
your `tsconfig.json` requires es-interop now to be set:
```json
"esModuleInterop": true
```
I've amended to module definition to be CommonJS, as covered module, sorry for the setback!
