### ISSUE TITLE
[@types/mysql] createPool(...).config type is incorrect.

### ISSUE THREAD

**Issue by devon-whil** [DefinitelyTyped/DefinitelyTyped#44115]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wjohnsto @wjohnsto @kacepe @kpping @jdmunro @sedenardi

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mysql/index.d.ts#L190

`Pool.config` has the wrong type. It currently extends `ConnectionConfig`, but it should instead have property `connectionConfig: ConnectionConfig`. See:

https://github.com/mysqljs/mysql/blob/master/lib/PoolConfig.js#L13

The `createPool` input parameter does and should extend `ConnectionConfig`, but `Pool.config` should have `connectionConfig: ConnectionConfig`.

**Comment by kpping** [comment]
Hi, @devon-whil 
Thank you for submitting the issue.  From briefly investigated, you are right. 

We may have to create new `config` type for `mysql.createPool(config)` , may be `CreatePoolConfig` ?,  which extends `ConnectionConfig` and add `connectionConfig: ConnectionConfig` to `PoolConfig`

Would you like to submit the PR to fix the addressed issue ?

**Comment by aschekatihin** [comment]
Also encountered this problem. Please take a look at PR from me.
