### ISSUE TITLE
@types/js-cookie 2.2.6 compiler error with js-cookie 2.2.1

### ISSUE THREAD

**Issue by airandfingers** [DefinitelyTyped/DefinitelyTyped#44126]
I recently updated our packages, including @types/js-cookie version "^2.2.4" and js-cookie version "^2.2.1", but the recently-published @types/js-cookie 2.2.6 is incompatible with js-cookie 2.2.1.

Our code is:

```
resolve(Cookies.set(key, value, { secure: __DEV__ ? false : secure }));
```

And I'm getting this compiler error:

```
filename.ts:7:13 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'void | PromiseLike<void | null> | null | undefined'.
  Type 'string' is not assignable to type 'void | PromiseLike<void | null> | null | undefined'.
7     resolve(Cookies.set(key, value, { secure: __DEV__ ? false : secure }));
```

Downgrading to 2.2.4 made this error go away.

  - Authors: @theodorejb @BendingBender @alepee @yutod @nreynis

- PR that updated to 2.2.6: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43769

**Comment by nreynis** [comment]
This is due to those changes:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42483

They is a legitimate fix that won't be rolled back. You should either update your code or freeze the dependency.

**Comment by peterblazejewicz** [comment]
@airandfingers
Does above explain the problem and how to approach it? If so, please close!

**Comment by airandfingers** [comment]
Understood, we've rolled back, and we'll update the package and our code when we can.

Thanks for the quick replies!
