### ISSUE TITLE
@types/node 13.13.2 "Duplicate identifier assert"

### ISSUE THREAD

**Issue by simon-robertson** [DefinitelyTyped/DefinitelyTyped#44142]
When compiling a TypeScript project that references `@types/node`, the compiler (TSC) will report an error regarding duplicate `assert` identifiers.

```
node_modules/@types/node/assert.d.ts:56:14 - error TS2300: Duplicate identifier 'assert'.
56     export = assert;
                ~~~~~~
  node_modules/@types/node/ts3.7/assert.d.ts:56:14
    56     export = assert;
                    ~~~~~~
    'assert' was also declared here.
```

Rolling `@types/node` back to version `12.12.6` resolves the issue.

@G-Rath (mentioned due to the latest activity in the `ts3.*` directories)

**Comment by G-Rath** [comment]
@simon-robertson I'm not able to reproduce this so far, using just:

```
import assert from 'assert';

assert.ok('hello world');
```

Could you provide a reproduction repo?

**Comment by simon-robertson** [comment]
@G-Rath No need to actually import anything. I have created a very simple repo that reproduces the issue at my end.

https://github.com/simon-robertson/issue-nodets-assert

If you do the usual `npm install` followed by `npm run build` you will hopefully see the error reported by TSC. The version of Visual Studio Code doesn't appear to matter, the error occurs if you build from a standalone terminal or the editor's integrated one.

Installed Node version is 12.16.0
Installed VSCode version is 1.44.2

**Comment by G-Rath** [comment]
> No need to actually import anything.

Yeah, but just wanted to be sure :)

> I have created a very simple repo that reproduces the issue at my end.

Cheers, this errors on my local too.

It's because you've got the `typeRoots` property set to `node_modules/@types/node` which is incorrect; it should be `node_modules/@types`.

This is because `typeRoots` specifies paths to folders which contain packages that should be used for typings, so by pointing TS to `node_modules/@types/node` you're saying that the `node/3.*` folders are their own packages, and so they all get loaded.

This is counter to what's meant to happen, which is `node` is loaded as the package, which contains `typeVersions` that point to the `ts3.*` folder to use based on the TS version.

**Comment by simon-robertson** [comment]
That does make sense, although using `node_modules/@types/<lib>` was allowing me to include specific type declarations on a per project basic in a VSCode workspace (the workspace contains a single `node_modules` directory to ensure each project uses the same lib versions).

Creating a `node_modules` directory (package) in each project that only contains the type declarations required by the project might be the solution to this, so I will use that approach instead, but the source-of-truth for the lib versions will be lost. Nothing is ever easy with TypeScript :)

I will close this issue, and thank you for the clarification.

**Comment by G-Rath** [comment]
I think what you're after is [the `types` property](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types); from the docs:

> If types is specified, only packages listed will be included. For instance:

```
{
   "compilerOptions": {
       "types" : ["node", "lodash", "express"]
   }
}
```
> This tsconfig.json file will only include ./node_modules/@types/node, ./node_modules/@types/lodash and ./node_modules/@types/express. Other packages under node_modules/@types/* will not be included.

**Comment by simon-robertson** [comment]
That's interesting. I do remember trying `types` before but it didn't seem to work as expected. Maybe the workspace wasn't setup correctly at that time so I will give it another try.

Thanks @G-Rath
