### ISSUE TITLE
@types/react-modal Heroku build errors

### ISSUE THREAD

**Issue by itayganor** [DefinitelyTyped/DefinitelyTyped#44227]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @radziksh @drewnoakes @homburg @ttamminen @hallowatcher @peterblazejewicz @jpowell @FiberJW @nitzanmo

---

I have a custom wrapped component for ReactModal that looks like this (omitted some irrelevant parts):

```js
import React, {ReactNode} from 'react';
import ReactModal from 'react-modal';

import classes from './Modal.module.less';


function Modal({children, ...rest}: ModalProps) {
    return <ReactModal
        className={classes.modal}
        overlayClassName={classes.overlay}
        closeTimeoutMS={+classes.transitionDurationMS}
        {...rest}
    >
        {children}
    </ReactModal>;
}

interface ModalProps extends ReactModal.Props {
    children: ReactNode;
}

export default Modal;
```

I use `webpack -p --mode production` to build the bundle for my app. When I do it locally, It's totally fine. But when I do it on Heroku, it emits some weird error messages I couldn't figure out:

```
ERROR in /tmp/build_c3c84f45e57111f81122c427f2efef39/client/src/utils/Modal/Modal.tsx
[tsl] ERROR in /tmp/build_c3c84f45e57111f81122c427f2efef39/client/src/utils/Modal/Modal.tsx(8,17)
      TS2339: Property 'className' does not exist on type 'ModalProps'.
       
ERROR in /tmp/build_c3c84f45e57111f81122c427f2efef39/client/src/utils/Modal/Modal.tsx
[tsl] ERROR in /tmp/build_c3c84f45e57111f81122c427f2efef39/client/src/utils/Modal/Modal.tsx(8,28)
      TS2339: Property 'overlayClassName' does not exist on type 'ModalProps'.
```

I double-checked; I extend `ReactModal.Props` as the `ReactModal` component itself does. The IDE (webstorm) is absolutely fine with this.
Do you have an idea why it happens?

- **Typescript version:** 3.8.3 on both ends
- **Webpack version:** 4.42.1 on both ends

**Comment by peterblazejewicz** [comment]
Does the problem persist?

**Comment by homburg** [comment]
@itayganor Can you create a small repo example of your issue?

**Comment by itayganor** [comment]
Sorry to bother you all. I just created a small repo as an example and there was not a single problem in build. As it turns out, despite doing `npm i -D @types/react-modal`, it was not saved in devDependecies. That's why Heroku's enviroment couldn't find any declaration files related to `react-modal`. Thanks alot!
