### ISSUE TITLE
@types/react-bootstrap: declarations from lib/ are not installed

### ISSUE THREAD

**Issue by beerose** [DefinitelyTyped/DefinitelyTyped#44220]
Hi,
I installed `@types/react-bootstrap` version `1.0.0`, but folder `lib` with declarations is missing in node_modules. It results in `Cannot find module './lib'.ts(2307)` error in `node_modules/@types/react-bootstrap/index.d.ts`.

<img width="819" alt="Screenshot 2020-04-25 at 09 43 21" src="https://user-images.githubusercontent.com/9019397/80274222-37c67680-86d9-11ea-8258-0a9d9a92d15d.png">

---

- [x] I tried using the `@types/react-bootstrap` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @walkerburgin, @vsiao, @collingreen, @bes

**Comment by cameron-martin** [comment]
[The lib folder is present in this repository](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-bootstrap/lib), but not in the published package. Ping @sandersn, since according to his bio he's on DefinitelyTyped duty atm.

**Comment by josh08h** [comment]
Any news on this one?

**Comment by cameron-martin** [comment]
Not yet. I think the typescript team would be useful to help out with this, to give insight into how files are chosen during the publishing process.

**Comment by strigonLeader** [comment]
Is the workaround for this to copy all the type files into your project and maintain them on your own for now?

**Comment by cameron-martin** [comment]
I think the best way forward would be to file an issue here: https://github.com/microsoft/DefinitelyTyped-tools/tree/master/packages/publisher

**Comment by beerose** [comment]
I'm using this particular version in the project:
```
"@types/react-bootstrap": "0.32.21",
```
and it works fine. `lib` directory is properly included and there seem to be no other issues.

**Comment by sandersn** [comment]
@beerose react-bootstrap@1.0 ships with its own types, so you don't need `@types/react-bootstrap` anymore.

**Comment by beerose** [comment]
> @beerose react-bootstrap@1.0 ships with its own types, so you don't need `@types/react-bootstrap` anymore.

I am aware. However, we haven't migrated to `v1.0` (Bootstrap 4+) yet and we're using `v0.32.x` (Bootstrap 3). So I do need types.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
