### ISSUE TITLE
@types/testing-library__react uses old testing-library__dom

### ISSUE THREAD

**Issue by joemckie** [DefinitelyTyped/DefinitelyTyped#44239]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alexkrolick, @kentcdodds, @eps1lon @weyert @ifiokjr @danieljcafonso @timswalling

It's currently impossible to use some of the new features in `@testing-library/dom` (such as `waitFor`), as `testing-library__react` ships with `testing-library__dom@6.12.1`.

**Comment by eps1lon** [comment]
> as testing-library__react ships with testing-library__dom@6.12.1.

You should update your version of `@types/testing-library__react` and potentially (in your lockfile) `@types/testing-library__dom`. `@types/testing-library__react` ships with the latest version of `@types/testing-library__dom`: https://unpkg.com/@types/testing-library__react@10.0.1/package.json

**Comment by joemckie** [comment]
I tried updating a couple of times but it didn't work 😢I didn't go as far as to go into the lockfile though so I'll try that next, thanks! If this package doesn't rely on a specific version, I'll just close this as it looks like the problem is on my end. Thanks for the quick response!
