### ISSUE TITLE
CI doesn't allow any changes to package.json, so it's impossible to propose build improvements and have the PR pass

### ISSUE THREAD

**Issue by jedwards1211** [DefinitelyTyped/DefinitelyTyped#44278]
I made a PR to propose automatic prettier format enforcement.  The build failed because changes to package.json seem to be disallowed:
```
$ npm run test
> definitely-typed@0.0.3 test /home/travis/build/DefinitelyTyped/DefinitelyTyped
> node node_modules/types-publisher/bin/tester/test.js --run-from-definitely-typed
Clean data
Clean logs
Clean output
Error: 'git diff' should be empty. Following files changed:
package.json
    at Object.getDefinitelyTyped (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/get-definitely-typed.js:42:15)
```
Knowing that PRs marked as build failed tend to get ignored, this is quite frustrating.

Perhaps we should document an established procedure for proposing changes like this?

**Comment by onomatopoetry** [comment]
I don't think this testing error is limited to changes to package.json! I tried making a simple update to @types/uniqid and am seeing the same type of error:
```
$ npm test

> definitely-typed@0.0.3 test C:\Users\onoma\Documents\Experiments\DefinitelyTyped
> node node_modules/types-publisher/bin/tester/test.js --run-from-definitely-typed

Clean data
Clean logs
Clean output
Error: 'git diff' should be empty. Following files changed:
types/uniqid/index.d.ts
types/uniqid/uniqid-tests.ts
    at Object.getDefinitelyTyped (C:\Users\onoma\Documents\Experiments\DefinitelyTyped\node_modules\types-publisher\bin\get-definitely-typed.js:42:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! Test failed.  See above for more details.
```

I'm running `npm test` from the root of my forked DefinitelyTyped repo as the readme suggests.

**Comment by jedwards1211** [comment]
in that case I've noticed it just suffices to `git add` the changed files.  But in CI I don't know why this error would be appearing.

**Comment by onomatopoetry** [comment]
You're right! `git add` does fix the changes when running `npm test` locally. I must be looking at a different issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
