### ISSUE TITLE
jest-dom type definition for `toHaveDisplayValue()` is missing

### ISSUE THREAD

**Issue by majesticuser** [DefinitelyTyped/DefinitelyTyped#44361]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/testing-library__jest-dom` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @berickson1 

Hello, since the release of jest-dom 5.5.0 (https://github.com/testing-library/jest-dom/releases/tag/v5.5.0) there is the new matcher `toHaveDisplayValue()`

It would be nice if you could add a type definition for `toHaveDisplayValue()`.

Thank you and best regards

**Comment by berickson1** [comment]
I'm not an author of this library, but here's a PR for the changes, can you test it?
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44385
