### ISSUE TITLE
Modules not found: can't resolve 'marked' ...

### ISSUE THREAD

**Issue by MatherLyn** [DefinitelyTyped/DefinitelyTyped#44414]
I want to use @types/marked in my react project. Before I began to code, I ran
npm install --save @types/marked

But when I wrote:
import marked from 'marked';
...
then webpack can not resolve this module. Is this because the package is not finished?

**Comment by peterblazejewicz** [comment]
> then webpack can not resolve this module

In the tsconfig.json please enable option `esModuleInterop`:
https://stackoverflow.com/questions/56238356/understanding-esmoduleinterop-in-tsconfig-file
(obviousl, assuming you've installed marked as well)
hth

**Comment by MatherLyn** [comment]
That's it!
