### ISSUE TITLE
Definition request: Semantic UI

### ISSUE THREAD

**Issue by ip** [DefinitelyTyped/DefinitelyTyped#4447]
Support for Semantic UI JavaScript part.
http://semantic-ui.com/

**Comment by Elephant-Vessel** [comment]
+1 This is needed

**Comment by kataras** [comment]
I switched from bootstrap to Semantic UI today, I will try to make my own definitation file and when I learn the framework well I will re-write the definitions and upload here, but if someone knows already the framework please share with us! thanks!

**Comment by matantsu** [comment]
+1

**Comment by pnocera** [comment]
+1
Anay news ? kataras ?

**Comment by pnocera** [comment]
+1
Any news ? kataras ?

**Comment by IsaacBorrero** [comment]
+1 Would like to request this...

**Comment by val-samonte** [comment]
+1
I actually requested this to semantic-ui, however I think they have no plans to do this as of the moment.

**Comment by hugohomesquita** [comment]
I started, we will continue :D https://github.com/hugohomesquita/DefinitelyTyped

**Comment by leonard-thieu** [comment]
Fixed by #14252.
