### ISSUE TITLE
[@types/ol] SelectOptions.style missing false as possible option

### ISSUE THREAD

**Issue by MoritzW3L** [DefinitelyTyped/DefinitelyTyped#44529]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/ol` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @hanreev

If you do not mention the authors the issue will be ignored.

-------------------------------------------

First of all, thank you for your work on the typings. 

The Documentation of OpenLayers 6.X presents the option to set {style: false} for any Select-object.
This works for openlayers code but prevents transpilation when using the current version of @types/ol. 
A simple fix would be to add "| false" to Options.style in "interactions/Select.d.ts".
I searched through the ReleaseNotes and could not find any mention on when this changed in case this should be made avaiable retroactively.

Link to the corresponding Openlayers documentation:
https://openlayers.org/en/latest/apidoc/module-ol_interaction_Select-Select.html

Would it be possible to include the suggested change in the types-code? Asking this here because I am not entirely sure how pull requests are handled in a project like this.

Cheers

**Comment by peterblazejewicz** [comment]
@MoritzW3L Is this a problem with TSC compilere here? (can you post an output?)
The property seems to be already set to be undefined (as optional one):

https://github.com/openlayers/openlayers/blob/v6.3.1/src/ol/interaction/Select.js#L226
defined as:
```ts
style?: StyleLike;
```
which translates to:
```ts
(property) Options.style?: Style | Style[] | StyleFunction | undefined
```
and can be used as:
```ts
const selectInteraction = new Select({
    features: new Collection(vectorSource.getFeatures()),
    style: undefined,
});
```

**Comment by hanreev** [comment]
@MoritzW3L  Just pass `null` if you need a falsey value.

@peterblazejewicz to keep feature style unchanged we need to pass a falsey value, the default style will be used if the value is `undefined`.

**Comment by MoritzW3L** [comment]
Thank you for your response @hanreev and @peterblazejewicz
Setting the value to null does indeed have the desired effect. Though I feel like I can be forgiven for not interpreting "falsey" as "null".

Again, thank you for the help, I will close this issue now.

Cheers,

Moritz
