### ISSUE TITLE
[@types/mongodb] Missing error parameter in abort() callback for GridFSBucketWriteStream

### ISSUE THREAD

**Issue by alexy4744** [DefinitelyTyped/DefinitelyTyped#44549]
- [x] I tried using the `@types/mongodb` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT @alanmarcell @Dante-101 @mcortesi @EnricoPicci @AJCStriker @julien-c @daprahamian @Denys-Bushulyak @sindbach @geraldinelemeur @various89 @angela-1 @lirbank @hector7 @floric @erikc5000 @Manc @jloveridge @Ranguna @HosseinAgha @albertossilva @peterblazejewicz @LinusU @taxilian @xamgore @avaly

Hi, this is a follow up issue for #44360. The callback definition for `abort` is missing an error parameter, which may be present if there was an error removing chunks.

https://mongodb.github.io/node-mongodb-native/3.6/api/GridFSBucketWriteStream.html#abort
https://mongodb.github.io/node-mongodb-native/3.6/api/GridFSBucket.html#~errorCallback
https://mongodb.github.io/node-mongodb-native/3.6/api/lib_gridfs-stream_upload.js.html#line112

```typescript
const stream = bucket.openUploadStreamWithId(...);
stream.abort((error) => {});
```

```
Argument of type '(error: any) => void' is not assignable to parameter of type '() => void'.
```

**Comment by peterblazejewicz** [comment]
Not sure how it slipped under the radar, I've added now tests to cover different usage with callback,
#44553 thanks!
