### ISSUE TITLE
[@types/hapi__hapi] RequestRoute settings should not have optional members

### ISSUE THREAD

**Issue by stevendesu** [DefinitelyTyped/DefinitelyTyped#44547]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rafaelsouzaf, @jhsimms, @SimonSchick, @saboya, @lenovouser

If you do not mention the authors the issue will be ignored.

I have a plugin which defines an `onPreResponse` handler in HapiJS. The code looks roughly like this:

```
import * as Hapi from "@hapi/hapi";

declare module "@hapi/hapi"
{
	export interface PluginSpecificConfiguration
	{
		myPlugin: boolean;
	}
}

export default {
	name: "myPlugin",
	version: "1.0.0",
	register: async function (server: Hapi.Server)
	{
		server.ext("onPreResponse", async (request, h) =>
		{
			// Disable the plugin with route options
			// !!! This is the line with the error:
			if (request.route.settings.plugins.myPlugin === false)
				return request.response;

			if (request.response instanceof Error)
			{
				// Custom error display
				return h.response({
					custom: "error"
				});
			}
			else
			{
				// Pass along non-error responses
				return request.response;
			}
		});
	}
};
```

TypeScript is throwing an error on `request.route.settings.plugins.myPlugin`:

```
Object is possibly 'undefined'.ts(2532)
```

I can work around this by instead writing it like so:

```
if (request.route.settings.plugins?.myPlugin === false)
```

However this causes me to not get 100% unit test coverage, because this checks for `null` and `undefined` on a value ***that is always defined*** (it's usually an empty object: `{}`)

Per the [HapiJS documentation](https://hapi.dev/api/#-requestroute) and the [TypeScript definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi__hapi/index.d.ts#L351), the variable `request.route.settings` is:

>the route options object ***with all defaults applied.***

(emphasis mine)

This means that many members of `RouteSettings` (or `CommonRouteProperties`) which are normally optional are guaranteed to exist in this context:

 - `app` (defaults to `{}`),
 - `cache` (defaults to `{statuses: [200, 204], otherwise: 'no-cache'}`)
 - `compression` (defaults to `{}`)
 - `cors` (defaults to `false`)
 - etc

The only properties I found that ***didn't*** have defaults were:

 - `bind`
 - `vhost`
 - `auth`

Everything else was either `null` (e.g. `payload` or `security`) or had a value (often empty objects)

For the time being I've worked around the unit test coverage issue like so:

```
if (
	/* $lab:coverage:off$ */
	typeof request.route.settings.plugins !== "undefined" &&
	/* $lab:coverage:on$ */
	request.route.settings.plugins.myPlugin === false
)
	return request.response;
```

Although this is obviously ugly and confusing to future developers.

**Comment by stevendesu** [comment]
I can try to make a PR to fix this if I find some time next week, but I'm not actually sure off-hand the cleanest or "right" way to do it in TypeScript

Effectively I want to say:

```
export interface Settings {
    member?: type
}

export interface FilledSettings {
    member: type
}
```

But if the definition of `Settings` changes in the future, then the definition of `FilledSettings` would ***also*** have to change. So I'd prefer something like (this is probably not valid TypeScript, unless my random pseudo-code landed on a ***really*** lucky guess):

```
export interface FilledSettings extends Settings {
    [key: string]: Settings[key].type & !undefined
}
```

**Comment by saboya** [comment]
I'm not looking at the code right now but my guess is that the right way to tackle this is to create a type that represents the default values and do a union with the current type.

**Comment by stevendesu** [comment]
@saboya I played around in VS Code and I think instead of a [union type](https://www.typescriptlang.org/docs/handbook/advanced-types.html#union-types) what you want is in [**intersection type**](https://www.typescriptlang.org/docs/handbook/advanced-types.html#intersection-types):

```
export interface One {
    foo: string | number;
}

export interface Two {
    foo: string
}

export type Three = One & Two;

const test: Three = { foo: 4 };
```

This threw an error:

```
Type 'number' is not assignable to type 'string'.ts(2322)
```

So using an intersection of `RouteSettings` and `DefaultRouteSettings` you can exclude `undefined` as a possibility

**Comment by stevendesu** [comment]
I did notice a quirk of the VS Code tooling for TypeScript. It seemed to behave how you would expect (requiring `Three` to adhere to the restrictions of both `One` and `Two`), but when you highlight over the object it reports the type by only looking at interface `Two`:

```
export interface One
{
	foo: string
}

export interface Two
{
	foo: any
}

export type Three = One & Two;

const test: Three = { foo: 4 };
```

This threw the (much harder to interpret) error:

```
Type '{ foo: number; }' is not assignable to type 'Three'.
  Type '{ foo: number; }' is not assignable to type 'One'.
    Types of property 'foo' are incompatible.
      Type 'number' is not assignable to type 'string'.ts(2322)
```

But the error was thrown for the `test` variable and not for the `foo` member. Mousing over the `foo` member, it reports the type as `any`:

![Screen Shot 2020-05-07 at 11 33 07 AM](https://user-images.githubusercontent.com/1384974/81313971-8dded680-9056-11ea-9da1-f7384507e6d4.png)

This isn't the end of the world, but it ***is*** annoying.

Even changing the order of the operands for the intersection operators (`export type Three = Two & One`) gave the same behavior. TypeScript knows that `foo` has to be a `string`, but it still reports that `foo` is an `any` when I mouse over it.

**Comment by saboya** [comment]
@stevendesu Yeah, I meant intersection, sorry about that.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
