### ISSUE TITLE
@types/node  ,in events.EventEmitter and net.Socket and net.Server ,Some attribute definitions are missing

### ISSUE THREAD

**Issue by masx200** [DefinitelyTyped/DefinitelyTyped#44560]
@types/node  , in events.EventEmitter and net.Socket and net.Server ,Some attribute definitions are missing

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/941b0622f8087361ba28d25602a0c0d2a4301062/types/node/net.d.ts#L56

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/941b0622f8087361ba28d25602a0c0d2a4301062/types/node/v12/events.d.ts#L15

```js
assert(Reflect.get(new net.Socket,"allowHalfOpen")===false)
```
```js

assert("object"===typeof Reflect.get(new events.EventEmitter,"domain"))
```

```js
import events from 'events'

new events.EventEmitter().domain

```
类型“EventEmitter”上不存在属性“domain”。ts(2339)
```js
import net from 'net'
new net.Socket().allowHalfOpen

```
类型“Socket”上不存在属性“allowHalfOpen”。ts(2339)

The attribute "domain" does not exist on the type "EventEmitter". ts (2339)

The attribute "allowHalfOpen" does not exist on the type "Socket". ts (2339)

```js


console.log(Reflect.ownKeys(new net.Socket))
/*
[
  'connecting',
  '_hadError',
  '_parent',
  '_host',
  '_readableState',
  'readable',
  'domain',
  '_events',
  '_eventsCount',
  '_maxListeners',
  '_writableState',
  'writable',
  'allowHalfOpen',
  '_sockname',
  '_pendingData',
  '_pendingEncoding',
  'server',
  '_server',
  Symbol(asyncId),
  Symbol(kHandle),
  Symbol(kSetNoDelay),
  Symbol(lastWriteQueueSize),
  Symbol(timeout),
  Symbol(kBuffer),
  Symbol(kBufferCb),
  Symbol(kBufferGen),
  Symbol(kCapture),
  Symbol(kBytesRead),
  Symbol(kBytesWritten)
]
*/
```

```js
console.log(Reflect.ownKeys(net.Socket.prototype))
/*
[
  'constructor',        '_unrefTimer',
  '_final',             'setTimeout',
  '_onTimeout',         'setNoDelay',
  'setKeepAlive',       'address',
  '_connecting',        'pending',
  'readyState',         'bufferSize',
  '_read',              'end',
  'pause',              'resume',
  'read',               'destroySoon',
  '_destroy',           '_getpeername',
  'bytesRead',          'remoteAddress',
  'remoteFamily',       'remotePort',
  '_getsockname',       'localAddress',
  'localPort',          '_writeGeneric',
  '_writev',            '_write',
  '_bytesDispatched',   'bytesWritten',
  'connect',            'ref',
  'unref',              '_handle',
  Symbol(kUpdateTimer), Symbol(kAfterAsyncWrite)
]
*/
```

```js

console.log(Reflect.ownKeys(net.Server.prototype))
/*
[
  'constructor',
  '_listen2',
  'listen',
  'listening',
  'address',
  'getConnections',
  'close',
  '_emitCloseIfDrained',
  '_setupWorker',
  'ref',
  'unref',
  Symbol(nodejs.rejection)
]

*/
```

```js
console.log(Reflect.ownKeys(new net.Server))
/*
[
  'domain',         '_events',
  '_eventsCount',   '_maxListeners',
  '_connections',   'connections',
  '_handle',        '_usingWorkers',
  '_workers',       '_unref',
  'allowHalfOpen',  'pauseOnConnect',
  Symbol(kCapture), Symbol(asyncId)
]
*/
```

```js

console.log(Reflect.ownKeys(new events.EventEmitter))
/*
[
  'domain',
  '_events',
  '_eventsCount',
  '_maxListeners',
  Symbol(kCapture)
]
*/
```

```js

console.log(Reflect.ownKeys(events.prototype))

/*
[
  'constructor',        '_events',
  '_eventsCount',       '_maxListeners',
  'setMaxListeners',    'getMaxListeners',
  'emit',               'addListener',
  'on',                 'prependListener',
  'once',               'prependOnceListener',
  'removeListener',     'off',
  'removeAllListeners', 'listeners',
  'rawListeners',       'listenerCount',
  'eventNames',         Symbol(kCapture)
]

*/
```
authors:

@Microsoft

@DefinitelyTyped

@jkomyno

@a-tarasyuk

@alvis

@r3nya
@btoueg
[Microsoft TypeScript](https://github.com/Microsoft), [DefinitelyTyped](https://github.com/DefinitelyTyped), [Alberto Schiabel](https://github.com/jkomyno), [Alexander T.](https://github.com/a-tarasyuk), [Alvis HT Tang](https://github.com/alvis), [Andrew Makarov](https://github.com/r3nya), [Benjamin Toueg](https://github.com/btoueg), [Bruno Scheufler](https://github.com/brunoscheufler), [Chigozirim C.](https://github.com/smac89), [Christian Vaagland Tellnes](https://github.com/tellnes), [David Junger](https://github.com/touffy), [Deividas Bakanas](https://github.com/DeividasBakanas), [Eugene Y. Q. Shen](https://github.com/eyqs), [Flarna](https://github.com/Flarna), [Hannes Magnusson](https://github.com/Hannes-Magnusson-CK), [Hoàng Văn Khải](https://github.com/KSXGitHub), [Huw](https://github.com/hoo29), [Kelvin Jin](https://github.com/kjin), [Klaus Meinhardt](https://github.com/ajafff), [Lishude](https://github.com/islishude), [Mariusz Wiktorczyk](https://github.com/mwiktorczyk), [Mohsen Azimi](https://github.com/mohsen1), [Nicolas Even](https://github.com/n-e), [Nicolas Voigt](https://github.com/octo-sniffle), [Nikita Galkin](https://github.com/galkin), [Parambir Singh](https://github.com/parambirs), [Sebastian Silbermann](https://github.com/eps1lon), [Simon Schick](https://github.com/SimonSchick), [Thomas den Hollander](https://github.com/ThomasdenH), [Wilco Bakker](https://github.com/WilcoBakker), [wwwy3y3](https://github.com/wwwy3y3), [Samuel Ainsworth](https://github.com/samuela), [Kyle Uehlein](https://github.com/kuehlein), [Jordi Oliveras Rovira](https://github.com/j-oliveras), [Thanik Bhongbhibhat](https://github.com/bhongy), [Marcin Kopacz](https://github.com/chyzwar), [Trivikram Kamat](https://github.com/trivikr), [Minh Son Nguyen](https://github.com/nguymin4), [Junxiao Shi](https://github.com/yoursunny), [Ilia Baryshnikov](https://github.com/qwelias), [ExE Boss](https://github.com/ExE-Boss), [Surasak Chaisurin](https://github.com/Ryan-Willpower), and [Piotr Błażejewicz](https://github.com/peterblazejewicz).

**Comment by SimonSchick** [comment]
As far as `EventEmitter.domain` goes the `domain` package is deprecated and we really shouldn't encourage the usage of deprecated APIs.

As for everything else, if it is clearly documented, it should be added, if it isn't we generally consider it private API and it will not be added.

**Comment by adamchal** [comment]
@SimonSchick would you consider adding `Socket.pending`? It is [publicly documented](https://nodejs.org/dist/latest-v15.x/docs/api/net.html#net_socket_pending). I appreciate the concern of keeping private things out of the typed namespace, but would love to have this one typed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
