### ISSUE TITLE
[@types/lodash] intersectionWith reports error when first arg is destructured array of arrays and second arg is comparator

### ISSUE THREAD

**Issue by mint-thompson** [DefinitelyTyped/DefinitelyTyped#44669]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @aj-r @e-cloud @thorn0 @jtmthf @DomiR @WilliamChelman 

In the following code:
```ts
const allMyStrings = [
  ['apple', 'banana', 'orange'],
  ['Apple', 'banana', 'cheese']
];
const sharedStrings = intersectionWith(...allMyStrings, (a: string, b: string) => {
  return a.toLocaleLowerCase() == b.toLocaleLowerCase();
});
const allowedSharedStrings = intersectionWith(
  allMyStrings[0],
  allMyStrings[1],
  (a: string, b: string) => {
    return a.toLocaleLowerCase() == b.toLocaleLowerCase();
  }
);
```
The first call to `intersectionWith` produces an error, but the second call to `intersectionWith` is allowed. The following error is received:
```
TS2345: Argument of type '(a: string, b: string) => boolean' is not assignable to parameter of type 'List<string>'.
  Index signature is missing in type '(a: string, b: string) => boolean'.

1652     const sharedStrings = intersectionWith(...allMyStrings, (a: string, b: string) => {
```

However, the first call to `intersectionWith` should be allowed. When `@ts-ignore` is placed before the line that produces the error, the resulting code behaves as expected, and `sharedStrings` is `['apple', 'banana']`

**Comment by aj-r** [comment]
Looks like the last overload should be changed from:

```ts
        intersectionWith<T>(array?: List<T> | null, ...values: Array<List<T>>): T[];
```

to:

```ts
        intersectionWith<T>(array?: List<T> | null, ...values: Array<List<T> | Comparator2<T,  never>>): T[];
```

Feel free to submit a PR.

**Comment by charliematters** [comment]
Can I ask why the final argument has `never` as the second type? Surely we're providing an argument which conforms to `(a: T, b: T) => boolean`? I've just come across this, and while you can override the parameter types, it seems a bit odd?
