### ISSUE TITLE
Separate out Stripe.js and stripe-node definitions

### ISSUE THREAD

**Issue by cgwrench** [DefinitelyTyped/DefinitelyTyped#4467]
The type definitions for [Stripe.js](https://stripe.com/docs/stripe.js) and [stripe-node](https://github.com/stripe/stripe-node) are both contained within the [directory "stripe"](https://github.com/borisyankov/DefinitelyTyped/tree/86d1044eb34dfb80b86a7aa181ed1bd95116cbbe/stripe).

This means that both definitions are included in the corresponding [NuGet package](http://www.nuget.org/packages/stripe.TypeScript.DefinitelyTyped/), which is not ideal. It should be possible to use either of these definitions independently of the other.

I propose moving the Node.js typings into their own folder, `stripe-node`, to reflect the name of the Node.js package and the existing file names. We would then have the directory structure:

    /stripe
        /stripe.d.ts
        /stripe.d.ts.tscparams
    /stripe-node
        /stripe-node.d.ts
        /stripe-node-tets.ts

Note that that following the merge of #4366, we also have a `stripe-checkout` directory.

**Comment by mattbrooks2010** [comment]
:thumbsup:
