### ISSUE TITLE
@types/carbon-components-react the `to` property isn't working right with the Link component

### ISSUE THREAD

**Issue by BitForger** [DefinitelyTyped/DefinitelyTyped#44772]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kalbert312 

I'm running into an issue trying to use the types. It looks like they might not be defined right? 
```
Type '<S = PoorMansUnknown>(props: LinkProps<S> & RefAttributes<HTMLAnchorElement>) => ReactElement<any, string | ((props: any) => ReactElement<...> | null) | (new (props: any) => Component<...>)> | null' is not assignable to type 'string | ((props: Pick<{}, never>) => ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)> | null) | (new (props: Pick<...>) => Component<...>) | undefined'.
  Type '<S = PoorMansUnknown>(props: LinkProps<S> & RefAttributes<HTMLAnchorElement>) => ReactElement<any, string | ((props: any) => ReactElement<...> | null) | (new (props: any) => Component<...>)> | null' is not assignable to type '(props: Pick<{}, never>) => ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)> | null'.
    Types of parameters 'props' and 'props' are incompatible.
      Type 'Pick<{}, never>' is not assignable to type 'LinkProps<PoorMansUnknown> & RefAttributes<HTMLAnchorElement>'.
        Property 'to' is missing in type 'Pick<{}, never>' but required in type 'LinkProps<PoorMansUnknown>'.  TS2322
```
I'm not sure how to resolve this. Thoughts?

**Comment by weswigham** [comment]
I'm just a DT maintainer; I don't know anything about this package specifically - you may want to ping a different contributor to the package.

**Comment by BitForger** [comment]
> I'm just a DT maintainer; I don't know anything about this package specifically - you may want to ping a different contributor to the package.

ah.. my bad

**Comment by kalbert312** [comment]
Can I see your usage of it? I'm assuming it's the UIShell Link and not the basic Link component?

In my experience React components with generics can be hit or miss when it comes to type inference. You might need to specify the generic type explicitly like:

```typescript
import { Link as RRLink, LinkProps as RRLinkProps } from "react-router-dom";
import Link from "carbon-components-react/lib/components/UIShell/Link";
<Link<RRLinkProps> element={RRLink} to="/" />
```

Let me know if that helps.

**Comment by BitForger** [comment]
sure, it's being used like this
```
<CarbonHeader>
    <SkipToContent href="#main-content">Skip to content</SkipToContent>
    <HeaderName element={Link} to={"/"} prefix={"home"}>Home</HeaderName>
    <HeaderNavigation>
        <HeaderMenuItem element={Link} to={"/item"}>another tiem</HeaderMenuItem>
    </HeaderNavigation>
    <HeaderGlobalBar />
</CarbonHeader>
```
