### ISSUE TITLE
@types/socket.io - type socket.ServerOptions does not have "wsEngine"

### ISSUE THREAD

**Issue by Spejik** [DefinitelyTyped/DefinitelyTyped#44788]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/socket.io` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @progre @divillysausages @florentpoujol @KentarouTakeda @gigi @BrainMaestro @murbanowicz @kevinkam

If you do not mention the authors the issue will be ignored.

When creating a new socket.io server instance with `socket.listen(..)` the second (options) argument does not have the property wsEngine.
(The solution was simply adding `wsEngine?: string` into the type socket.ServerOptions)

**Comment by murbanowicz** [comment]
By any chance, can you create the PR for this issue? Especially if you have the fix already there should be quick. I would review that immediately.

**Comment by Spejik** [comment]
I don't know how to PR in this repo, but all I did is that I've taken the Options from https://socket.io/docs/server-api/ and put them into `interface ServerOptions`
But I can send you the file if you want 😃

**Comment by KentarouTakeda** [comment]
@Spejik 
I will fix it. Please wait a moment.

**Comment by peterblazejewicz** [comment]
Was this fixed in #44796?

**Comment by KentarouTakeda** [comment]
@peterblazejewicz 
Yes, published as 2.1.6 (Current latest version is 2.1.8)

**Comment by peterblazejewicz** [comment]
Thanks!
@Spejik  would you mind? thx!
