### ISSUE TITLE
[@types/ramda] curry loses generics on return type

### ISSUE THREAD

**Issue by viters** [DefinitelyTyped/DefinitelyTyped#44793]
I tried using the `@types/ramda` package and had problems. I tried using the latest stable version of tsc - confirmed both on `3.8.3` and `3.9.2`.

Let's take `objFromKeys` from Ramda cookbook and type it:

```typescript
const objFromKeys = <T>(
  fn: (k: string) => T,
  keys: readonly string[],
): {
  [key: string]: T;
} => zipObj(keys, map(fn, keys));

const ret = objFromKeys((k) => Boolean(k), ['a', 'b', '']);
```

Return has correct type:
![image](https://user-images.githubusercontent.com/13100466/82132493-99619880-97e0-11ea-9d51-b784ed40159a.png)

When you wrap it into curry:

```typescript
const objFromKeys = curry(<T>(fn: (k: string) => T, keys: readonly string[]): {
  [key: string]: T;
} => zipObj(keys, map(fn, keys)));

const ret1 = objFromKeys((k) => Boolean(k), ['a', 'b', '']);
const ret2 = objFromKeys((k) => Boolean(k))(['a', 'b', '']);
```

Return has incorrect type, regardless of how it is called:
![image](https://user-images.githubusercontent.com/13100466/82132505-c2822900-97e0-11ea-8b4b-728fe8eae1ba.png)
![image](https://user-images.githubusercontent.com/13100466/82132513-ca41cd80-97e0-11ea-9d68-5511d14dddf0.png)

Authors: @TheHandsomeCoder, @donnut, @mdekrey, @mrdziuban, @sbking, @afharo, @teves-castro, @1M0reBug, @hojberg, @samsonkeung, @angeloocana, @raynerd, @moshensky, @ethanresnick, @deftomat, @blimusiek, @biern, @rayhaneh, @rgm, @drewwyatt, @jottenlips, @minitesh, @Krantisinh, @pirix-gh, @brekk, @Nemo108, @jituanlin, @Philippe-mills, @Saul-Mirone

**Comment by pirix-gh** [comment]
This is a known problem, currently is a limitation.

**Comment by viters** [comment]
Oh, okay. Sorry I am not really up to date. Should I close this issue then?

**Comment by pirix-gh** [comment]
No problem, it's not well documented, you couldn't know. You can leave the issue open. It could be resolved by https://github.com/microsoft/TypeScript/issues/5453.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
