### ISSUE TITLE
[@types/eslint] supports `ESLint` class?

### ISSUE THREAD

**Issue by tyankatsu0105** [DefinitelyTyped/DefinitelyTyped#44799]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/). (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @pmdartus @j-f1 @saadq @JasonHK @bradzacher

According to [this post](https://eslint.org/blog/2020/05/eslint-v7.0.0-released#new-eslint-class), ESLint supports `ESLint` class since v7.0.0. 
And also `CLIEngine` is deprecated.

**Comment by mckennapsean** [comment]
Currently, the [definitions only support up to v.6.8.0](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/eslint/index.d.ts). v.7.0.0 just got released.

I assume we just need [a contributor to upgrade the type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute) accordingly?
