### ISSUE TITLE
Bug React.Children.map

### ISSUE THREAD

**Issue by tomasguerreiro** [DefinitelyTyped/DefinitelyTyped#44818]
If you know how to fix the issue, make a pull request instead.

- [   ] I tried using the `@types/xxxx` package and had problems.
- [ X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

Hello, I believe I found a bug in the build. The code below works perfectly in `next dev` but in` next build` it returns empty divisions

tried with 9.3.1 and 9.4.1

I modified the returns several times, added null, made several attempts but in none of them did I get the expected behavior of react

```
  function renderInputGroup() {
    return React.Children.map(props.children, (child: any) => {
      if (child.type.name.startsWith('Input')) {
        return child;
      }
    });
  }

  function renderChildren() {
    return React.Children.map(props.children, (child: any) => {
      if (!child.type.name.startsWith('Input')) {
        if (child.type.name.startsWith('Icon')) {
          return React.cloneElement(child, {
            color: child.props.color ?? 'neutral',
          });
        }
      }
    });
  }

  return (
    <div ref={elRef} {...props} className={style.formControl}>
      <div className={style.formGroup}>
        <div className={style.inputGroup}>{renderInputGroup()}</div>
        {renderChildren()}
      </div>
    </div>
  );
```

In dev (next dev)
![image](https://user-images.githubusercontent.com/21958418/82174564-78b04600-98a7-11ea-988c-fe9387e26644.png)

In Prod (next build && next start)
![image](https://user-images.githubusercontent.com/21958418/82174750-0ee46c00-98a8-11ea-973a-66d42daea444.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
