### ISSUE TITLE
@types/readable-stream throws error at run-time

### ISSUE THREAD

**Issue by ronlamck** [DefinitelyTyped/DefinitelyTyped#44828]
The following error was thrown from @types/readable-stream when starting a NestJS project.

Other observations:
1. The @types/readable-stream was installed as a dependency for the mssql package.
No error was thrown after the mssql package (and @types/readable-stream) was uninstalled
2. No error was thrown from the previous version which uses string instead of BufferEncoding for encoding varables.

*** Error Logs Start **
[18:59:15] Starting compilation in watch mode...

node_modules/@types/readable-stream/index.d.ts:13:15 - error TS2417: Class static side 'typeof _Readable' incorrectly extends base class static side 'typeof Readable'.
  The types of 'Stream.Readable.Writable' are incompatible between these types.
    Type 'typeof _Readable.Writable' is not assignable to type 'typeof import("stream").Writable'.
      Types of parameters 'options' and 'opts' are incompatible.
        Type 'import("stream").WritableOptions' is not assignable to type '_Readable.WritableOptions'.
          Type 'WritableOptions' is not assignable to type 'WritableStateOptions'.
            Types of property 'defaultEncoding' are incompatible.
              Type 'string' is not assignable to type 'BufferEncoding'.

13 declare class _Readable extends stream.Readable {
*** Error Logs End **

**Comment by sbleon** [comment]
I ran into this at compilation time in v14.0.3. I downgraded to v12.12.7 and the problem went away.

**Comment by SimonSchick** [comment]
This is likely due to an old/incompatible version of @types/readable-stream

**Comment by revitalist** [comment]
I'm getting the same problem.  Versions are:
Node 12.16.3
tsc 3.9.3
readable-stream 2.3.6 (which is used by mssql 6.2.0)
Any suggestions will be much appreciated!

**Comment by SimonSchick** [comment]
Can you please provide a miminal repro? (package.json, package-lock.json, index.ts, tsconfig.json)?

**Comment by revitalist** [comment]
See attached.  These are part of a standard NestJS install.  Thank you for investigating this - much appreciated.

**Comment by SimonSchick** [comment]
I don't think attachments work when sent via email 😛

**Comment by revitalist** [comment]
The basic repo (it was compressed using the standard Mac zip function).
[studentapi001-old.zip](https://github.com/DefinitelyTyped/DefinitelyTyped/files/4665294/studentapi001-old.zip)

**Comment by revitalist** [comment]
Apologies - I updated the issue instead.

**Comment by SimonSchick** [comment]
Yea it seems readable-stream isn't quite compatible with with pre v14 node versions anymore, this is partially my bad.

Run `npm i -D -E @types/readable-stream@2.3.5` to downgrade the version, this will install a compatible version and make the version number static.

**Comment by revitalist** [comment]
Shall do.  Many thanks.

**Comment by J-O-P** [comment]
Having the same problem. Thanks for the workaround with the downgrade, that helps for now.

**Comment by platzhersh** [comment]
Having a similar problem here:

Node: v12.18.0
typescript: 3.9.5
readable-stream: 2.3.5
@types/readable-stream: 2.3.7

I tried downgrading readable-stream types, but it didn't help

'''
../../node_modules/@types/readable-stream/index.d.ts:13:15 - error TS2417: Class static side 'typeof _Readable' incorrectly extends base class static side 'typeof Readable'.
  The types of 'Stream.Readable.Writable' are incompatible between these types.
    Type 'typeof _Readable.Writable' is not assignable to type 'typeof import("stream").Writable'.
      Types of parameters 'options' and 'opts' are incompatible.
        Type 'import("stream").WritableOptions | undefined' is not assignable to type '_Readable.WritableOptions | undefined'.
          Type 'import("stream").WritableOptions' is not assignable to type '_Readable.WritableOptions'.
            Type 'WritableOptions' is not assignable to type 'WritableStateOptions'.
              Types of property 'defaultEncoding' are incompatible.
                Type 'string | undefined' is not assignable to type '"ascii" | "utf8" | "utf-8" | "utf16le" | "ucs2" | "ucs-2" | "base64" | "latin1" | "binary" | "hex" | undefined'.
                  Type 'string' is not assignable to type '"ascii" | "utf8" | "utf-8" | "utf16le" | "ucs2" | "ucs-2" | "base64" | "latin1" | "binary" | "hex" | undefined'.

13 declare class _Readable extends stream.Readable {
'''

**Comment by SimonSchick** [comment]
Should be, yes.

**Comment by abumalick** [comment]
I tried with node 14.4.0 and I get the same error than with v12

```
yarn start                                                                                                                       ░▒▓ ✔ | 14.4.0 Node 
yarn run v1.22.4
$ nest start
node_modules/@types/readable-stream/index.d.ts:13:15 - error TS2417: Class static side 'typeof _Readable' incorrectly extends base class static side 'typeof Readable'.
  The types of 'Stream.Readable.Writable' are incompatible between these types.
    Type 'typeof _Readable.Writable' is not assignable to type 'typeof import("stream").Writable'.
      Types of parameters 'options' and 'opts' are incompatible.
        Type 'import("stream").WritableOptions' is not assignable to type '_Readable.WritableOptions'.
          Type 'WritableOptions' is not assignable to type 'WritableStateOptions'.
            Types of property 'defaultEncoding' are incompatible.
              Type 'string' is not assignable to type 'BufferEncoding'.

13 declare class _Readable extends stream.Readable {
```

@types/readable-stream@2.3.7

**Comment by abumalick** [comment]
Well, even v2.3.5 don't work for me in node v12 and v14

What works for fixing the build for me is this change:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/readable-stream/index.d.ts#L13
```
-declare class _Readable extends stream.Readable {
+declare class _Readable {
```

It is dirty, but well, at least it builds. Looking forward for a fix really

**Comment by troylatchman** [comment]
I think there is double trouble here. 

1. In Node14 the stream transform method takes a BufferEncoding type instead of a vanilla string.
Version 2.3.6 of this definition file assumes the user is on Node14. This should somehow be fixed to work on Node12 (current LTS) and Node14 (future LTS).

2. The stream definition was recently updated in Node types. There are 2 new fields that impact Node12 and higher: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45175
Assuming that was a valid merge, these new fields need to be carried over here.

As a workaround, we can take the latest version of both types before they started conflicting for Node12. 
`npm install --save-dev --save-exact @types/node@12.12.43`
`npm install --save-dev --save-exact @types/readable-stream@2.3.5`

**Comment by hiob10hiob** [comment]
Updating to node `v12.18.1` `@types/readable-stream@2.3.7` fixed this issue for me.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
