### ISSUE TITLE
[@types/chrome] [@types/firefox-webext-browser] Suggestion: use interfaces instead of namespaces for the APIs

### ISSUE THREAD

**Issue by JasonHK** [DefinitelyTyped/DefinitelyTyped#44827]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/chrome` and `@types/firefox-webext-browser` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:
    - `@types/chrome`: @matthewkimber @otiai10 @couven92 @rreverser @sreimer15 @MatCarlson @ekinsol @tregagnon @echoabstract @spasma @bdbai
    - `@types/firefox-webext-browser`: @jsmnbom

If you do not mention the authors the issue will be ignored.

---

With the current type definitions, IntelliSense isn't working properly when I wrote something like this:

```typescript
const api: typeof browser | typeof chrome = browser ?? chrome;

api.|
//  ^
// When I hit the tab key, nothing shows up.
```

Although this might be a bug related to TypeScript, it did cause some issue when these two definitions were used together.

So I suggest to refactor the definitions to use interfaces instead of namespaces like the example below:

```typescript
declare var chrome: Chrome;

interface Chrome {
    /**
     * Use the `chrome.accessibilityFeatures` API to manage Chrome's accessibility features.
     * 
     * This API relies on the `ChromeSetting` prototype of the type API for getting and setting
     * individual accessibility features.
     * 
     * In order to get feature states the extension must request `accessibilityFeatures.read` permission.
     * For modifying feature state, the extension needs `accessibilityFeatures.modify` permission. Note
     * that `accessibilityFeatures.modify` does not imply `accessibilityFeatures.read` permission.
     * 
     * __REMARKS:__ This API works only on Chrome OS.
     * 
     * @since Chrome 37
     * @permissions `accessibilityFeatures.read`
     */
    accessibilityFeatures: Chrome.AccessibilityFeatures;
    ...
}

declare namespace Chrome {
    interface AccessibilityFeatures {
        /**
         * Spoken feedback (text-to-speech).
         */
        spokenFeedback: Chrome.Types.ChromeSetting;
        ...
    }

    namespace Types {
        interface ChromeSetting { ... }
        ...
    }
    ...
}
```

I'm willing to help with refactoring if you guys want to give it a try.

**Comment by jsmnbom** [comment]
I'm unsure what firefox-webext-browser has to do this this? You're what? Trying to combine the APIs? But they are fundementally different tho? You probably want to be using something like https://github.com/mozilla/webextension-polyfill in that case, and then just use firefox-webext-browser.
In addition, I am not sure that it would be possible to change firefox-webext-browser to use interfaces due to the heavy amount of nesting.

**Comment by JasonHK** [comment]
> I'm unsure what firefox-webext-browser has to do this this? You're what? Trying to combine the APIs? But they are fundementally different tho? You probably want to be using something like https://github.com/mozilla/webextension-polyfill in that case, and then just use firefox-webext-browser.
> In addition, I am not sure that it would be possible to change firefox-webext-browser to use interfaces due to the heavy amount of nesting.

It seems that I'm just going in the wrong direction. Sorry about that :pray:
