### ISSUE TITLE
react-toastr return types are wrong

### ISSUE THREAD

**Issue by JoshMcCullough** [DefinitelyTyped/DefinitelyTyped#44847]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/792f2d312b1e97046d804dc4efbca4c7965ab8ad/types/react-toastr/index.d.ts#L16

A call to e.g. `toastr.info` returns a reference to the toastr/element, but the typings say it returns `void`.

**Comment by peterblazejewicz** [comment]
@JoshMcCullough are you sure about this api returning ref? It seems to be a void by definition:
https://github.com/tomchentw/react-toastr/blob/fcd3b4b7e6031dde7c128921489bffaad85729a9/src/components/ToastContainer.jsx#L68-L123

**Comment by JoshMcCullough** [comment]
Nope -- my bad. I was looking the code for _toastr_ and incorrectly assumed that _react-toastr_ would have correctly implemented the API -- but apparently not. You can see here that `toastr`'s API does return: https://github.com/CodeSeven/toastr/blob/master/toastr.js#L69

I'll close this and file a bug with `react-toastr` -- sorry!

**Comment by peterblazejewicz** [comment]
no worries mate!
