### ISSUE TITLE
@types/react-relay is missing typings for useSubscription

### ISSUE THREAD

**Issue by ChristianIvicevic** [DefinitelyTyped/DefinitelyTyped#44889]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @voxmatt @alloy @npirotte @ckknight @kastermester @mattkrick @jdk243 @renanmav @janicduplessis 

Just wanted to ping you since the typings for the react-relay package are missing for the `useSubscription` hook introduced end of February. Unfortunately I am inexperienced with regards to the process of DefinitelyTypes packages, so I'd appreciate if someone of you finds the spare time to update the typings accordingly.

For reference: https://github.com/facebook/relay/blob/relay-experimental/packages/relay-experimental/useSubscription.js

**Comment by ChristianIvicevic** [comment]
Until this is resolved I added a custom `react-relay.d.ts` file into my CRA project with the following content to alleviate the issue:

```ts
import * as reactRelayHooks from "react-relay/hooks";
import { GraphQLSubscriptionConfig, requestSubscription } from "relay-runtime";

declare module "react-relay/hooks" {
    export { reactRelayHooks };

    export function useSubscription<TSubscriptionPayload>(
        config: GraphQLSubscriptionConfig<TSubscriptionPayload>,
        requestSubscriptionFn?: typeof requestSubscription
    ): void;
}
```

**Comment by alloy** [comment]
Can you please provide a PR with your typings?

**Comment by ChristianIvicevic** [comment]
I just opened PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44915 for this issue.
