### ISSUE TITLE
[@types/ioredis] So can I use Maps or not?

### ISSUE THREAD

**Issue by LosTigeros** [DefinitelyTyped/DefinitelyTyped#44880]
- [x] I tried using the `@types/ioredis` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @plantain-00 @alavers

So the issue is basically this:
![image](https://user-images.githubusercontent.com/6253928/82316011-7abff500-99cc-11ea-8f7c-56a2476b8644.png)

Why can't I use `Map` on `.hmset` anymore but still can use it when I'm using `Pipeline`?
Is it supposed to be like that?
Should `.hmset` in `Commands` allow `Map` too?
Should `.hmset` in `Pipeline` not allow `Map`?

**Comment by alavers** [comment]
Oh. That may have been lost in [this refactoring](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/517880ac2f9a4e41b5d037061a7b9ef67380d041#diff-77c12eda472c636dbbde3195da016159L467). I presume your `Snowflake` is a string?

Should be easy to put that back.

**Comment by alavers** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45079

**Comment by LosTigeros** [comment]
Yes it's basically a string.

**Comment by alavers** [comment]
@LosTigeros should be fixed in @types/ioredis@4.16.4 thanks for reporting!

**Comment by LosTigeros** [comment]
Okay, thank you!
