### ISSUE TITLE
@types/cytoscape events style property not accepted

### ISSUE THREAD

**Issue by jsphstls** [DefinitelyTyped/DefinitelyTyped#44890]
- [x] I tried using the `@types/cytoscape` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:
@phreed
@wy193777
@ypconstante
@janniclas
@cerberuser
@gsbelarus
@peterjferrarotto
@spaxe

```
export const basic: Stylesheet[] = [
  {
    selector: 'node',
    css: {
      events: 'no'
    }
  }
```

```
Type '{ events: string; }' is not assignable to type 'Node | Edge | Core'.
  Object literal may only specify known properties, and 'events' does not exist in type 'Node | Edge | Core'.ts(2322)
```

https://js.cytoscape.org/#style/events

**Comment by MatthijsBon** [comment]
I _think_ I have a similar problem:  

```
Type '{"curve-style": "straight";"source-endpoint": string;"target-endpoint": string;}' 
is not assignable to type 'Node | Edge | Core'. 
Object literal may only specify known properties, and '"source-endpoint"' does not exist in type 'Node | Edge | Core'.
```

It seems as if there are style type definitions missing maybe?

**Comment by Veckodag** [comment]
> I _think_ I have a similar problem:
> 
> ```
> Type '{"curve-style": "straight";"source-endpoint": string;"target-endpoint": string;}' 
> is not assignable to type 'Node | Edge | Core'. 
> Object literal may only specify known properties, and '"source-endpoint"' does not exist in type 'Node | Edge | Core'.
> ```
> 
> It seems as if there are style type definitions missing maybe?

Hey Mate! 
Yeah it seems typings for [edge endpoints](https://js.cytoscape.org/#style/edge-endpoints) isn't included yet. Got a nice stylesheet with endpoint stuff for testing you can share?
Have a wonderful day!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
