### ISSUE TITLE
Changes to CI: From Travis/Devops to GitHub Actions

### ISSUE THREAD

**Issue by orta** [DefinitelyTyped/DefinitelyTyped#44906]
Tomorrow I'm going to be adding GitHub Actions to the CI suite. 

We'll run GH Actions alongside both travis and devops for a little while (only a few days) and during that time I'll switch the dt-mergebot to use GH Actions for CI verifications instead of travis. Then once that is stable I'll remove both Travis and DevOps from the CI. 

We'll still use DevOps for schedules tasks ATM.

Mainly because travis is now flaky ([probably the acquisition](https://news.ycombinator.com/item?id=18978251)) and if we're gonna change it up, we may as well move to just one CI provider.

**Comment by orta** [comment]
GH Actions is running on all new PRs, and the scheduled code owners sync is on on actions.

**Comment by orta** [comment]
This is ready with https://github.com/DefinitelyTyped/dt-mergebot/pull/94

**Comment by xamgore** [comment]
Could you please explain what does this label mean? Being a project contributor, what actions are expected from me?
![image](https://user-images.githubusercontent.com/4586392/84571687-76091980-ad9d-11ea-8888-84e7854fd1a5.png)

**Comment by orta** [comment]
It meant the bot originally couldn't find the CI report from GH Actions, then removed it - nothing is expected of you.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
