### ISSUE TITLE
Travis build failed for PR: API rate limit hit.

### ISSUE THREAD

**Issue by kalbert312** [DefinitelyTyped/DefinitelyTyped#44920]
Not sure what to do about this as it says some API rate limit was hit: 
https://travis-ci.org/github/DefinitelyTyped/DefinitelyTyped/builds/689011934

PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44900

It may have been caused by me pushing a fix commit and then another right after it for improper imports error in previous builds.

**Comment by orta** [comment]
We should probably allow danger to fail, we treat all the messaging as optional here anyway - I'll fix this in the GH Actions version with #44928
