### ISSUE TITLE
[@types/node] Capitalization of defaultEncoding was changed to defaultencoding

### ISSUE THREAD

**Issue by RAnders00** [DefinitelyTyped/DefinitelyTyped#44990]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick 

If you do not mention the authors the issue will be ignored.

There was a [fairly recent commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/daf04e0dcb922a9ed7f31ea8ea9aee0c9cdef368#diff-665b6f98978297aaa993cba6091bc1f5L127) to the node definitions that changed the capitalization of `defaultEncoding` to `defaultencoding`. I cannot see any change to Node.js that also made that capitalization change.

@SimonSchick - was this change by accident? Should it be reverted or is there a reason for that change?
 It breaks my project since I use that property.

**Comment by SimonSchick** [comment]
will fix ASAP
