### ISSUE TITLE
[@types/webgl2] Conflicts with lib.dom.d.ts

### ISSUE THREAD

**Issue by yunyu** [DefinitelyTyped/DefinitelyTyped#45011]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nkemnitz @karhu

The @types/webgl2 package conflicts with the lib.dom.d.ts definitions in TS 3.9.3. When loading them, I get:

```
  ERROR in node_modules/typescript/lib/lib.dom.d.ts(16313,11):
  TS2430: Interface 'WebGL2RenderingContext' incorrectly extends interface 'WebGL2RenderingContextBase'.
    Types of property 'clearBufferfv' are incompatible.
      Type '(buffer: number, drawbuffer: number, values: ArrayLike<number> | Float32Array, srcOffset?: number | undefined) => void' is not assignable to type '{ (buffer: number, drawbuffer: number, values: Float32List, srcOffset?: number | undefined): void; (buffer: number, drawbuffer: number, values: Iterable<number>, srcOffset?: number | undefined): void; }'.
        Types of parameters 'values' and 'values' are incompatible.
          Type 'Iterable<number>' is not assignable to type 'ArrayLike<number> | Float32Array'.
            Type 'Iterable<number>' is missing the following properties from type 'Float32Array': BYTES_PER_ELEMENT, buffer, byteLength, byteOffset, and 25 more.
  TS2430: Interface 'WebGL2RenderingContext' incorrectly extends interface 'WebGL2RenderingContextOverloads'.
    Types of property 'uniform1fv' are incompatible.
      Type '(location: WebGLUniformLocation | null, data: ArrayLike<number> | Float32Array, srcOffset?: number | undefined, srcLength?: number | undefined) => void' is not assignable to type '{ (location: WebGLUniformLocation | null, data: Float32List, srcOffset?: number | undefined, srcLength?: number | undefined): void; (location: WebGLUniformLocation | null, data: Iterable<...>, srcOffset?: number | undefined, srcLength?: number | undefined): void; }'.
        Types of parameters 'data' and 'data' are incompatible.
          Type 'Iterable<number>' is not assignable to type 'ArrayLike<number> | Float32Array'.
            Type 'Iterable<number>' is not assignable to type 'Float32Array'.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
