### ISSUE TITLE
[@types/theme-ui] SxStyleProp & Emotion's label

### ISSUE THREAD

**Issue by yuriybelike** [DefinitelyTyped/DefinitelyTyped#45020]
- [x] I tried using the `@types/theme-ui` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @erikdstock @ifiokjr @sbardian @pomber @wKovacs64 @prateekkathal @hasparus @leocantthinkfoaname

I discovered that I can use [Emotion's `label`](https://emotion.sh/docs/labels) property on `sx`:

```tsx
/** @jsx jsx */
import { jsx } from "theme-ui";
import React from "react";

const Paragraph = ({
  children
}: {
  children: React.ReactNode;
}): JSX.Element => {
  return <p sx={{ color: "red", label: "my-paragraph" }}>{children}</p>;
};

export { Paragraph };
```

It doesn't compile, but I can see it working as expected on Storybook (which ignores type errors).

> TS2322: Type 'string' is not assignable to type 'SystemStyleObject'.
> Version: typescript 3.8.3

> TS2322: Type '{ readonly label: "my-paragraph"; }' is not assignable to type 'SystemCssProperties | CSSPseudoSelectorProps | CSSSelectorObject | VariantProperty | UseThemeFunction | null | undefined'.
>   Type '{ readonly label: "my-paragraph"; }' is not assignable to type 'CSSSelectorObject'.
>     Property 'label' is incompatible with index signature.
>       Type '"my-paragraph"' is not assignable to type 'SystemStyleObject'.

![image](https://user-images.githubusercontent.com/60257988/82752007-7ecc8800-9dbb-11ea-9bfe-78c7423b2a57.png)

### More context
One of Theme UI's authors saying that this is an undocumented, but not unexpected behaviour: https://github.com/system-ui/theme-ui/pull/817/files#r408433642

**Comment by hasparus** [comment]
Wow, that's a bug. We expect label to be nested object.
We'll have to make sure to fix this in Theme UI 0.4-alpha types too.

Thanks for the issue!

**Comment by sbardian** [comment]
The only place I'm seeing `label` defined in emotion is under  `StyledOptions` from @emotion/styled-base [here](https://github.com/emotion-js/emotion/blob/e09fb216180063f1cad4fafe390e770e7398f811/packages/styled-base/types/index.d.ts#L35).  I'm wondering if this is something that needs to be added to the css prop types in emotion? 

If not we could just add a `& { label?: string}` to the `sx` definition [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ac0327a3ddfe6dac85bf13b99363e58925ee56f2/types/theme-ui/index.d.ts#L153) to support `label` on the `sx` prop? 

@hasparus not sure what you mean by "nexted object" from what I'm seeing it is just a string, so maybe I'm way off here?

**Comment by hasparus** [comment]
With the nested object (`SystemStyleObject`), I meant what's happening right now.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ac0327a3ddfe6dac85bf13b99363e58925ee56f2/types/theme-ui/index.d.ts#L139

We could do `export type SxStyleProp = SystemStyleObject | { label?: string }` as a fix here, but it should probably go into SystemStyleObject eventually.

**Comment by wKovacs64** [comment]
May as well just add it to `SystemStyleObject` instead?

**Comment by hasparus** [comment]
> May as well just add it to SystemStyleObject instead?

Yeah, I wasn't sure about it, but it turns out labels can be nested, and they all contribute to the className.

![image](https://user-images.githubusercontent.com/15332326/82840226-1f14d080-9ed2-11ea-8bde-eca4bb5efc5f.png)

https://codesandbox.io/s/wispy-cdn-3ockf?file=/src/index.tsx
