### ISSUE TITLE
[@types/google__maps] missing street_address in AddressType

### ISSUE THREAD

**Issue by clemens-smartparking** [DefinitelyTyped/DefinitelyTyped#45033]
"@types/google__maps": "0.5.12"

If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/google__maps` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @thewunder 

If you do not mention the authors the issue will be ignored.

I believe for the interface `ReverseGeocodingRequest` for the member `result_type?: AddressType` the option 'street_address' should be allowed. This has been removed recently.

We had existing code that was working with this option previously. https://developers.google.com/maps/documentation/geocoding/intro also has an example that uses street_address.

**Comment by martin-badin** [comment]
@clemens-smartparking I downloaded the folder and the AddressType contains `street_address`. I see the type locally but not in the Github repository. I don't know why.

```typescript
export type AddressType = (
    /** indicates a precise street address. */
    'street_address' |
    /** indicates a named route (such as "US 101"). */
    'route' |
    /** indicates a major intersection, usually of two major roads. */
    'intersection'
// ...
```

**Comment by martin-badin** [comment]
I found that the `street_address` was moved from `AddressType` to `GeocodingAddressComponentType ` in this PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36412. Should it be added back? 

I read the documentation and I think the types are wrong. I think the `AddressType` should contain `street_address` and the `GeocodingAddressComponentType` not. But I don't know why the types were changed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
