### ISSUE TITLE
[@types/lusca] missing csrf option "header"

### ISSUE THREAD

**Issue by shwao** [DefinitelyTyped/DefinitelyTyped#45040]
The lusca CSRF options have a property "header":
https://github.com/krakenjs/lusca/blob/0483eda77a6fcef08d9319369e1f2b6fd2a5dcba/lib/csrf.js#L49

Its missing in the type definitions:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f345d5ef8686cea2a136cb6b84d07b916dd50e15/types/lusca/index.d.ts#L44

@crutchcorn @builtinnya

**Comment by crutchcorn** [comment]
Great observation! I'd suggest making a PR for this, I'd be happy to review and approve :)
