### ISSUE TITLE
Definition Request: nuclear-js

### ISSUE THREAD

**Issue by mikeyoon** [DefinitelyTyped/DefinitelyTyped#4505]
Just checking if someone else is working on it, or if there is more interest in making a definition for it. I'm planning on working on it myself otherwise.

**Comment by rigoleto** [comment]
I'd also like to see a definition for nuclear

**Comment by rigoleto** [comment]
If anyone else is looking for this, I've got a good working start here: https://gist.github.com/rigoleto/3e8aca1228abc546797a. This was developed with TS 1.7.3

**Comment by bsideup** [comment]
:+1:
