### ISSUE TITLE
[@types/react] Including KeyboardEvent.key values in the type

### ISSUE THREAD

**Issue by dimitropoulos** [DefinitelyTyped/DefinitelyTyped#45062]
- [x] I tried using the `@types/react` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon @zieka @dancerphil @dimitropoulos @disjukr @vhfmag

-------

In the context of [a PR](https://github.com/elastic/eui/issues/3512) moving the (deprecated) `KeyboardEvent.keyCode` usages in a codebase to `KeyboardEvent.key` I noticed that the types for this are:

```ts
interface KeyboardEvent<...> {
    ...
    /**
     * See the [DOM Level 3 Events spec](https://www.w3.org/TR/uievents-key/#named-key-attribute-values). for possible values
     */
    key: string;
    ...
}
```

Which makes me wonder if there's any opposition to just including the list of possible named key attribute values into the react types?  [Here](https://www.w3.org/TR/uievents-key/#named-key-attribute-values) is the list (just item 3 from this document).

Although in the end any value will be accepted because it's still going to need to `| string` at the end (since all unicode characters are possible values of `KeyboardEvent.key`), it will help end users because it will provide completion for common values like `Enter`, `Control`, `Tab`, etc.

Any interest?

**Comment by ferdaber** [comment]
This would probably be better in TypeScript's own DOM lib if we were to implement it. The `key` value isn't React-specific though React does consume it.

**Comment by eps1lon** [comment]
I'd be careful how this is implemented cross platform. Ideally we would do `string | 'Enter' | ...` and Typescript would still add completions for the literals.

Do you know if there are any cross-platform inconsistencies for the `key` property?

**Comment by dimitropoulos** [comment]
yeah, the `string | 'Enter'` approach is what I was referencing in the last paragraph - so same page on that front.

I am not aware of any cross-platform inconsistencies (other than the three mentioned [in that document](https://www.w3.org/TR/uievents-key/#named-key-attribute-values), `Enter`, `Backspace`, and `Delete`).

I would be happy to take this suggestion over to the DOM lib types.  I did check there and it isn't implemented there either.  Just lemme know what you guys/gals think.

**Comment by dimitropoulos** [comment]
ok: I suggested over there https://github.com/microsoft/TypeScript/issues/38886

I'll report back on what they say - and if it gets added convert this issue to track consumption of the upstream types in the react types so it can flow through (if it doesn't/wouldn't automatically - I'll be sure to check at that time).

**Comment by dimitropoulos** [comment]
The report back is that this won't be possible until https://github.com/microsoft/TypeScript/issues/29729 is in.

It seems like it'll be implemented over on `lib.dom.d.ts` anyway so I'm fine with closing this (for now, anyway).

note @eps1lon that in addition to the [`(string & {})` hack](https://github.com/microsoft/TypeScript/issues/29729#issuecomment-661959682), there's also a utility in [type-fest called LiteralUnion](https://github.com/sindresorhus/type-fest/blob/master/source/literal-union.d.ts) that does the job of allowing `string` to be in the union but still giving the autocomplete/intellisense results.
