### ISSUE TITLE
CI error in my type fix PR: JSDoc tag '@param' is redundant in TypeScript code.

### ISSUE THREAD

**Issue by cakoose** [DefinitelyTyped/DefinitelyTyped#45110]
I'm trying to submit a tiny PR for the "@types/ffi-napi" package: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45109

The PR page says that my PR failed the CI build.  When I look at the Travis build log ([link](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45109)), the only error I see is:

> ERROR: 19:9  no-redundant-jsdoc-2  JSDoc tag '@param' is redundant in TypeScript code.

Two questions:
1. I didn't add these `@param` annotations.  Do I have to fix all of them before my tiny PR will go through?
2. Why is it bad to use JSDoc `@param`?  I understand that it's redundant to provide type information in JSDoc comments, but these particular JSDoc comments just document the parameters.

**Comment by cakoose** [comment]
Also, I don't get that error when I run `npm run tests` locally, maybe because it filters out errors on unchanged lines?

```
$ npm run test

> definitely-typed@0.0.3 test /Users/kannan/dev/DefinitelyTyped
> node node_modules/@definitelytyped/dtslint-runner/dist/index.js --path .

Using local DefinitelyTyped at .
Parsing definitions...
Found 6796 packages.
Parsing in parallel...
Parsing took 20.444 s
Running: git rev-parse --verify master
adb5ab2bbbea13e6b952df8064a301283bc9cee0
Running: git diff master --name-status
M	types/ffi-napi/ffi-napi-tests.ts
M	types/ffi-napi/index.d.ts
Testing 1 changed packages: ffi-napi
Testing 0 dependent packages:
Installing NPM dependencies...
  ./types/node: npm install --ignore-scripts --no-shrinkwrap --no-package-lock --no-bin-links --no-save
 from ./types/node: up to date in 0.34s
found 0 vulnerabilities
1> ffi-napi START
1> ffi-napi OK


=== SUGGESTIONS ===

{"ffi-napi": [{"fileName":"/Users/kannan/dev/DefinitelyTyped/types/ffi-napi/index.d.ts","ruleName":"npm-naming","message":"The declaration doesn't match the JavaScript module 'ffi-napi'. Reason:\nThe JavaScript module exports a property named 'version', which is missing from the declaration module."}]}


=== PERFORMANCE ===

{ "ffi-napi": 9107}
  * Percentiles:
99: 9107
95: 9107
90: 9107
70: 9107
50: 9107
```

**Comment by peterblazejewicz** [comment]
@cakoose 
thx for the issue, I've noticed same and reported this up. Recently there was a change in the linter used here to verify definition types.
No, the JSDoc are here to stay. 
Yes, you're correct that local tests results seem to out-of-sync with CI ones. 
Yes, the `npm test` should be source-of-the-truth both locally and on the CI (so the outcome shoudl be same).
This was how it worked until up recently.

**Comment by andrewbranch** [comment]
This was a bug in our testing infrastructure, and should be fixed now. I’ve restarted the failed jobs on your PR, @cakoose. FYI, I’ve been trying to keep #44317 up-to-date with known infrastructure issues.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
