### ISSUE TITLE
Unable to compile JSDOM

### ISSUE THREAD

**Issue by razafinarivohanania** [DefinitelyTyped/DefinitelyTyped#45173]
Hello, i try to use JSDOM with TypeScript but it fails. Many objects are not found and compilation cannot be done therefore.

- [x] I tried using the `@types/jsdom` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

- @leonard-thieu 
- @palmenhq 
- @ExE-Boss

**TypeScript** : v3.9.3
**NodeJs** : v12.16.3
**@types/jsdom**: v16.2.3

To reproduce the error :

```ts
import { JSDOM } from 'jsdom';
```
and compile with tsc after. Then, theses errors occur :

```sh
node_modules/@types/jsdom/index.d.ts:28:40 - error TS2304: Cannot find name 'DocumentFragment'.

28         static fragment(html: string): DocumentFragment;
                                          ~~~~~~~~~~~~~~~~

node_modules/@types/jsdom/index.d.ts:45:28 - error TS2304: Cannot find name 'Node'.

45         nodeLocation(node: Node): ElementLocation | null;
                              ~~~~

node_modules/@types/jsdom/index.d.ts:188:19 - error TS2304: Cannot find name 'HTMLScriptElement'.

188         element?: HTMLScriptElement | HTMLLinkElement | HTMLIFrameElement | HTMLImageElement;

and so on ...
```

I check what happens in node_modules/@types/jsdom directory, and there are many object not found :

![a](https://user-images.githubusercontent.com/24853543/83327454-a96b8480-a284-11ea-94e9-7433f0ade434.jpg)

Thanks in advance :)

**Comment by ExE-Boss** [comment]
You need to include [the `DOM` types](https://www.typescriptlang.org/tsconfig#high-level-libraries) in your `tsconfig.json`’s [`lib` option](https://www.typescriptlang.org/tsconfig#lib).

**Comment by razafinarivohanania** [comment]
@ExE-Boss Thanks :) it runs. I close issue.
