### ISSUE TITLE
"npm run test" fails on macOS: tar: Option --warning=none is not supported

### ISSUE THREAD

**Issue by cakoose** [DefinitelyTyped/DefinitelyTyped#45229]
(I filed this issue against dts-critic ([link](https://github.com/DefinitelyTyped/dts-critic/issues/30)) but haven't gotten any responses so re-filing here.)

I made a change to a DefinitelyTyped type definition. I tried running the linter but it failed:

```
$ npm run lint ffi-napi

> definitely-typed@0.0.3 lint /Users/kannan/dev/DefinitelyTyped
> dtslint types "ffi-napi"

tar: Option --warning=none is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
```

I think "--warning=none" is a non-standard option of GNU tar. MacOS comes with BSD tar, which doesn't support that option.

When I modify "node_modules/dts-critic/index.ts" and remove the "--warning=none" argument, everything seems to work fine.

**Comment by OliverJAsh** [comment]
I also ran into this.

> When I modify "node_modules/dts-critic/index.ts" and remove the "--warning=none" argument, everything seems to work fine.

In my case I had to modify `node_modules/dts-critic/dist/index.js` to workaround this.

/cc @sandersn

**Comment by cakoose** [comment]
Fixed: https://github.com/DefinitelyTyped/dts-critic/issues/30

**Comment by sandersn** [comment]
Yep, sorry about that. When we switched dts-critic from JS to TS I forgot to add a prepublish script that makes sure to build before publication. [That's fixed now](https://github.com/DefinitelyTyped/dts-critic/pull/34) and a new dts-critic/dtslint have shipped.
