### ISSUE TITLE
React: `createElement` and `createFactory` should require `props` param

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#45282]
If we use `createElement`/`createFactory` with a component that has _required_ props, we should be required to provide those props. However, because `createElement`/`createFactory` define the `props` param as optional, there is no error if we forget to provide the props object. Reduced test case:

```ts
import * as React from 'react';

declare const MyComponent: React.FunctionComponent<{ foo: number }>;

// no error ✅
React.createElement(MyComponent, { foo: 1 });
// no error!! ❌
React.createElement(MyComponent); // $ExpectError

const myComponentFactory = React.createFactory(MyComponent);

// no error ✅
myComponentFactory({ foo: 1 });
// no error!! ❌
myComponentFactory(); // $ExpectError
```

How can we fix this? IIUC, we want the `props` param to be optional if and only if the component props type has no required properties—otherwise it should be a required param. Something like this:

```ts
type Component<P> = (props: P) => unknown;

declare const createElement: {
    <P>(Component: Component<P>, props: P): null;
    (Component: Component<{}>): null;
};

{
    declare const MyComponent: Component<{ foo: number }>;

    createElement(MyComponent);
    createElement(MyComponent, { foo: 1 });
}
{
    declare const MyComponent: Component<{}>;

    createElement(MyComponent);
    createElement(MyComponent, { foo: 1 });
}
```

---

Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon @zieka @dancerphil @dimitropoulos @disjukr @vhfmag

If you do not mention the authors the issue will be ignored.

**Comment by dimitropoulos** [comment]
Thanks for the issue @OliverJAsh!

To save anyone else the time to reference:
1. The current implementation of `createElement`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f718963ff32567821e10b5073bb195d42face7be/types/react/index.d.ts#L265-L299
1. The current implementation of `createFactory`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f718963ff32567821e10b5073bb195d42face7be/types/react/index.d.ts#L248-L261

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
