### ISSUE TITLE
@types/mongoose throws errors after upgrading to 5.7.22

### ISSUE THREAD

**Issue by bastibense** [DefinitelyTyped/DefinitelyTyped#45305]
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

With the latest update to `@types/mongoose` I get a lot of errors in my IDE (vscode) about missing properties when creating new documents.

```(property) RocketDocumentPage.dimensions: [number, number]
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ order: number; label: string; width: number; height: number; publication: string; kiosk: Ref<KioskModel>; }' is not assignable to parameter of type 'Pick<{ _id: any; order: number; label: string; width: number; height: number; publication: Ref<PublicationModel>; kiosk: Ref<KioskModel>; userId: string; available: boolean; migrationRef: string; } & { ...; }, "order" | ... 7 more ... | "migrationRef"> & { ...; }'.
      Type '{ order: number; label: string; width: number; height: number; publication: string; kiosk: Ref<KioskModel>; }' is missing the following properties from type 'Pick<{ _id: any; order: number; label: string; width: number; height: number; publication: Ref<PublicationModel>; kiosk: Ref<KioskModel>; userId: string; available: boolean; migrationRef: string; } & { ...; }, "order" | ... 7 more ... | "migrationRef">': userId, available, migrationRefts(2769)
```

This can be easily reproduced by creating a model and trying to call `.create({ ... })` on it.

This worked perfectly fine with 5.7.21.

Downgraded to 5.7.21 as a workaround for now until this is fixed.

**Comment by bopfer** [comment]
The changes in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44619 for v5.7.22 destroyed my codebase as well.  None of my `create` calls pass a type check now.  My errors are similar to the OP error.

**Comment by bopfer** [comment]
I created a simple repo to show the error I am seeing in my code base: https://github.com/bopfer/mongoose-create-types

The README over there has info about the setup and how to show the error.

**Comment by andreialecu** [comment]
Try using the types from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45355 and see if they help.

There was an issue with arrays in the initial PR.

**Comment by andreialecu** [comment]
@bopfer regarding your repro:

https://github.com/bopfer/mongoose-create-types/blob/master/src/userModel.ts#L6-L11

```ts
type User = {
  firstName: string;
  lastName: string;
  fullName: string;
  language: string;
}
```

https://github.com/bopfer/mongoose-create-types/blob/master/src/createUser.ts#L3-L6
```ts
userModel.create({
  firstName: `Foo`,
  lastName: `Bar`,
})
```

You are defining all properties required, but only supplying two of them to `create`.

`fullName` is just a virtual getter, and language is optional because you're supplying a default. Your options are to either define your type like:

```ts
  type User = {
    firstName: string;
    lastName: string;
    readonly fullName: string;
    language?: string;
  }
```

or leave the type alone and override what `.create()` expects:

```ts
userModel.create<Omit<User, "language">>({
  firstName: `Foo`,
  lastName: `Bar`,
})
```

Instead of Omit you could also use `Pick` or `Partial` or you can supply your own custom type (but I don't see why that would be necessary).

**Comment by andreialecu** [comment]
Alternatively, if you don't care about complete type safety when using `.create()` (I'd strongly discourage it though), you can use `.create<any>(...)` or `.create<Partial<User>>(...)`

**Comment by andreialecu** [comment]
@bastibense the reason for your error is similar:

It seems to be erroring about missing `userId`, `available` and `migrationRef` when using create.

If those properties are not required in your types, just mark them optional in the interface, or use the override I mentioned above.

**Comment by bopfer** [comment]
@andreialecu Thanks for the input!  The `readonly` attribute will definitely help for the virtuals.

I think will will need to go with a separate type for creation.  I want to be able to do `user.language` and not have to deal with the possibility of it being undefined, since it is required, but has a default value.  So, it doesn't need to be in the `create`, but it will always be defined on a document.

Appreciate the help!

**Comment by bastibense** [comment]
To get stuff working again quickly I just went with the `.create<any>` approach. When I have a bit more time I'll look into a better solution like the ones suggested above (in my case it's only 3 calls I had to fix).

**Comment by EugeneKorshenko** [comment]
I also faced this issue and resolved it in following manner (really close to what @bastibense adviced):
`.create<Partial<MyModelSchemaType>>`. Hope this will be helpful.

**Comment by jamieowen** [comment]
I have the same problem too. 
I ended up using the create\<any\> solution.

For reference - i was declaring a typed ref to a model but trying to use typescripts Partial<ModeType> didn't seem to resolve it either.

e.g: 
```typescript
import { model, Document } from 'mongoose';

type IMyModel = SomeType & Document;
const MyModel = model<IMyModel>('MyModel', MyModelSchema);
MyModel.create({...}) // gives the error

// or...
type IMyModel = Partial<SomeType> & Document;
const MyModel = model<IMyModel>('MyModel', MyModelSchema);
MyModel.create({}); // still doesn't work...

// works - but bad..
type IMyModel = SomeType & Document;
const MyModel = model<IMyModel>('MyModel', MyModelSchema);
MyModel.create<any>({...})

```

**Comment by andreialecu** [comment]
@jamieowen you're supplying the type parameter to the wrong method. Try this instead:

```
MyModel.create<IMyModel>({});
```

**Comment by jamieowen** [comment]
Hey, yeah I know that..

But the type itself is passed in via the generic on the model<> call no? 
Which is what allows the create() function to understand the allowed argument types.

So it should be possible to set the Partial<> on the model<> statement?

**Comment by andreialecu** [comment]
Setting it `Partial` on model doesn't sound like a good idea. Your TypeScript type should properly correlate to the actual backing schema.

Any optional property in the database should also be optional in the type (using `?`). And any required field should be left required (add `!`).

Example:

```ts
interface MyModel {
  thisIsOptional?: string;
  thisIsRequired!: string;
  readonly thisIsReadonly: string;
}
```

If you properly define your type like the above, then there should be minimal issues with using the strong typed `.create()` and you won't need any overrides.

Using the schema above, the following is valid:
`.create({ thisIsRequired: "foo" })`

This, however is not:
`.create({ thisIsOptional: "foo" })` // missing `thisIsRequired`

**Comment by jamieowen** [comment]
Yeah that makes sense.. its currently what i am doing in general - i didn't mean that using <Partial> is good practice.

What I meant above is that using <Partial> on the model level was not working to fix the problem.  But using it at the create level is... as surely the partialled generic model type is passed to the create() function?

But no worries.. I just thought this was a bug as the error just came up on older code for me recently too.

I will keep an eye on it / and have better look later!

Cheers man!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
