### ISSUE TITLE
@types/atlassian-connect-js all options fields are required

### ISSUE THREAD

**Issue by braxtonhall** [DefinitelyTyped/DefinitelyTyped#45312]
- [x] I tried using the `@types/atlassian-connect-js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @josh- 

Fields for options are all required, although they should be optional.

For example, this valid use of the Atlassian JavaScript API
```typescript
AP.flag.create({
    title,
    body,
    error
});
```
produces the error:
> TS2345: Argument of type '{ title: any; body: any; type: "error"; }' is not assignable to parameter of type '{ title: string; body: string; type: "error" | "info" | "success" | "warning"; close: "manual" | "auto"; actions: { [key: string]: string; }; }'.   Type '{ title: any; body: any; type: "error"; }' is missing the following properties from type '{ title: string; body: string; type: "error" | "info" | "success" | "warning"; close: "manual" | "auto"; actions: { [key: string]: string; }; }': close, actions

The options interface:
```typescript
interface FlagCreateOptions {
    title: string;
    body: string;
    type: 'info' | 'success' | 'warning' | 'error';
    close: 'manual' | 'auto';
    actions: { [key: string]: string };
}
```
should likely be
```typescript
interface FlagCreateOptions {
    title?: string;
    body?: string;
    type?: 'info' | 'success' | 'warning' | 'error';
    close?: 'manual' | 'auto';
    actions?: { [key: string]: string };
}
```
for this example alone.

**Comment by josh-** [comment]
Thanks @braxtonhall! Will create a PR shortly 👍

**Comment by elibarzilay** [comment]
Resolving this, as mentioned in a comment on #45324 (which is why GH didn't do it).
