### ISSUE TITLE
[styled-components] not working with older versions of hoist-non-react-statics

### ISSUE THREAD

**Issue by marwankhalili** [DefinitelyTyped/DefinitelyTyped#45318]
- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @LavaToaster @Jessidhia @JKillian @eps1lon @flavordaaave @wagerfield @Lazyuki @mgoszcz2 @danilofuchs 

I have a dependency that installs hoist-non-react-statics@2 which causes errors for the definitions in @types/styled-components when using v4.4.1 or higher. This issue can be replicated by manually installing an older version: `npm i hoist-non-react-statics@2`.

My current solution is to add @types/hoist-non-react-statics@3 to my own package so that @types/styled-components imports the correct version. Perhaps the dependency for @types/hoist-non-react-statics should be "^3.0.0" instead of "*"?

**Comment by gorazu** [comment]
Thank you @marwankhalili , it seems that I have the same issue, whenever I use styled-components styled method I loose any typings on my components, as I am migrating an app to typescript it is really frustrating.

I also have several packages that use hoist-non-react-statics@2 and adding a newer version of `@types/hoist-non-react-statics` didn't fix the issue.

Any help would be appreciated !

**Comment by marwankhalili** [comment]
@gorazu Hey, I noticed that only adding the type declarations would not always fix the issue. Try also adding the package itself `npm i --save-dev hoist-non-react-statics@3`

**Comment by gorazu** [comment]
It worked when installing the package and the types, thank you very much @marwankhalili !

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
