### ISSUE TITLE
[@types/fancybox] Button list is not a closed set, but configurable

### ISSUE THREAD

**Issue by iustin** [DefinitelyTyped/DefinitelyTyped#45346]
I'm looking at `types/fancybox/index.d.ts` and it has this:

```
interface FancyBoxButtonTypes {
    "zoom": string;
    "share": string;
    "slideShow": string;
    "fullScreen": string;
    "download": string;
    "thumbs": string;
    "close": string;
}
```

And similar for `FancyBoxButtonTemplateOptions`:

```
interface FancyBoxButtonTemplateOptions {
    download?: string;
    zoom?: string;
    close?: string;
    arrowLeft?: string;
    arrowRight?: string;
    smallBtn?: string;
}
```

However, unless I'm mistaken, both the button types and and templates are fully customizable, using whatever button name one wants. See [How to create custom button in the toolbar](http://fancyapps.com/fancybox/3/docs/#faq-3) in the official docs.

I don't know enough TS to suggest any option than simply allowing any strings to be used as keys in FancyBoxButtonTypes, and I don't know how to make FancyBoxButtonTemplateOptions by any string→string mapping.

@borisyankov and @SPWizard01, thoughts?

**Comment by SPWizard01** [comment]
as far as i remember these are well known properties. if there are more of these available, will need to add them here. can you tell me what exact property are you missing/trying to set?

**Comment by iustin** [comment]
Hmm, unless I misunderstand, the button set are not "well known". There is a default set of buttons, true, but one can add any (random) button names as long as a template is added as well.

See what I do here (which is the file that I wanted to move over to TS): add [a new button template](https://github.com/iustin/corydalis/blob/0fb929386bd0a95e516607c7a4d759a98c6457d1/js/fancybox.js#L51), and then [later](https://github.com/iustin/corydalis/blob/0fb929386bd0a95e516607c7a4d759a98c6457d1/js/fancybox.js#L98) enable this new button name (called "view") to be shown. That code works without issue. Quoting here the example:

```
  // Custom view item button.
  $.fancybox.defaults.btnTpl.view = `
<button data-fancybox-view
        class="fancybox-button fancybox-button--view"
        title="Open image in viewer">
  <span class="fas fa-external-link-alt">
</button>`;
  $.fancybox.defaults.buttons = [
    'view',
    …
 ]
```

There's also code to handle the interaction with the new button, but for the purposes of this bug - I think the "fixed" set of button names is wrong, for what the library allows one to do.

**Comment by SPWizard01** [comment]
@iustin sorry to get back to you this late, totally forgot about this, i think i get what you mean.

are you thinking that we need to do something along the lines:
```
interface FancyBoxButtonTypes {
    "zoom": string;
    "share": string;
    "slideShow": string;
    "fullScreen": string;
    "download": string;
    "thumbs": string;
    "close": string;
    [key: string]?: string; //<< this
}

interface FancyBoxButtonTemplateOptions {
    download?: string;
    zoom?: string;
    close?: string;
    arrowLeft?: string;
    arrowRight?: string;
    /**
     * This small close button will be appended to your html/inline/ajax content by default,
     * if "smallBtn" option is not set to false
     */
    smallBtn?: string;
    [key: string]?: string; //<< this
}
```

by well defined i meant that we know that there is a zoom/close/download etc, i did not know you can add your own :)

**Comment by iustin** [comment]
Hi @SPWizard01, no worries, I also sometime remember open github issues/comments after a long while. It's not like this is one's main job :)

Regarding the way to fix it - yes, I think this is a good approach. I'm just a beginner in TypeScript, so I can't vouch for the correctnes of the implementation, but it does look right. Thanks for taking the time!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
