### ISSUE TITLE
How do I unsubscribe from TypeScript bot?

### ISSUE THREAD

**Issue by tobyhede** [DefinitelyTyped/DefinitelyTyped#45372]
I made a change years ago and TypeScript bot has been hassling me ever since. 

How do I turn it off?

**Comment by peterblazejewicz** [comment]
Hey, you would need to create PR with relevant lines with your Gihtub handle removed. That's all. Once merged, the bot will remove you from the owners list (autogenerated file)
Example:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45082

**Comment by tobyhede** [comment]
Thanks
