### ISSUE TITLE
[@types/echarts] With Typescript 3.8 throwing multiple compilation errors

### ISSUE THREAD

**Issue by dileepyelleti** [DefinitelyTyped/DefinitelyTyped#45389]
- [x] I tried using the `@types/echarts` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @xieisabug @AntiMoron @liveangela @Ovilia @iRON5 @tmtron @dwhitney @ruixuel

With typescript version 3.8 compilation is failing in multiple places. We are using echarts in angular application which is being upgraded to angular 9.

Example: 
using series-line.markLine.data.0.yAxis to draw line parallel to xAxis at specific yAxis value. 
In types (boxplot.d.ts) yAxis is not there and everywhere in examples(https://echarts.apache.org/examples/en/editor.html?c=line-aqi) that property is used. Getting below error - 
Object literal may only specify known properties, and 'yAxis' does not exist in type '{ type?: string; valueIndex?: number; valueDim?: string; coord?: any[]; name?: string; x?: number; y?: number; value?: number; symbol?: string; symbolSize?: number | any[]; symbolRotate?: number; symbolKeepAspect?: boolean; symbolOffset?: any[]; lineStyle?: { ...; }; label?: { ...; }; }

Similar error for series.tooltip.trigger 'trigger' does not exist.

Those fields are not available in docs options but widely used in examples

**Comment by Ovilia** [comment]
Could you please make a pull request?

**Comment by dileepyelleti** [comment]
@Ovilia Sure will do that. But those options were not available in echarts documentation and widely used in examples. Should we use them or are there any alternatives to these options.

**Comment by Ovilia** [comment]
@dileepyelleti ECharts is working on the next big version 5.0, in which TypsScript is used. So DefinitelyTyped may not be used afterwards and the type definition should work better afterwards.

**Comment by dileepyelleti** [comment]
@Ovilia Great news. Thank you
