### ISSUE TITLE
Lodash throttle missing cancel() method

### ISSUE THREAD

**Issue by milkisevil** [DefinitelyTyped/DefinitelyTyped#4542]
The `cancel()` method as demonstrated below is missing from `_.throttled()` and `_.debounce()` in lodash.d.ts

```javascript
var throttled = _.throttle( myFunc, 3000 );

// later...
throttled.cancel()
```

Fiddle: http://jsfiddle.net/L3ancdhs/

I'm not 100% sure on how this should be defined? Currently:

```javascript
throttle<T extends Function>(
      func: T,
      wait: number,
      options?: ThrottleSettings): T;
```

Interested in learning how this would be solved :)

**Comment by vvakame** [comment]
@milkisevil please send a pull request. I'll review it.

**Comment by milkisevil** [comment]
Thanks @vvakame , before we get to the PR stage, would you mind reviewing this: It's how I'd have imagined to implement this (with an interface extending a generic—which apparently isn't possible, at least in the [playground](http://www.typescriptlang.org/playground/)):

```typescript
// The d.ts
interface LoDashStatic {
    throttle<T extends Function>(
      func: T,
      wait: number,
      options?: ThrottleSettings): CancelableFunction<T>;
}

interface ThrottleSettings {
    leading?: boolean;
    trailing?: boolean;
}
  
interface CancelableFunction<T> extends T {  // Problem! An interface that extends a generic isn't possible?!
	cancel(): void;
}


// The app implementation
interface Hello extends Function { 
	world()
}

declare var _:LoDashStatic;
declare var hello:Hello;

var foo = _.throttle(hello, 2);
foo.world();
foo.cancel();
```

It'd be great to know if there's a more suitable approach, that is of course actually possible.

**Comment by chrootsu** [comment]
@milkisevil @vvakame I think the issue can be closed. It has been corrected by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6980
