### ISSUE TITLE
Missing some 14->12 backports in Events

### ISSUE THREAD

**Issue by orgads** [DefinitelyTyped/DefinitelyTyped#45469]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick @jkomyno @a-tarasyuk @alvis @r3nya @btoueg @BrunoScheufler @smac89 @tellnes @Touffy @DeividasBakanas @eyqs @Flarna @Hannes-Magnusson-CK @KSXGitHub @hoo29 @kjin @ajafff @islishude @mwiktorczyk @mohsen1 @n-e @octo-sniffle @galkin @parambirs @eps1lon @SimonSchick @ThomasdenH @WilcoBakker @wwwy3y3 @samuela @kuehlein @j-oliveras @bhongy @chyzwar @trivikr @nguymin4 @yoursunny @qwelias @ExE-Boss @Ryan-Willpower @peterblazejewicz

There were several backports from v14 to v12 in Events (versions 12.16 and 12.17). Search for "Added in: v12" in [the docs](https://nodejs.org/docs/latest-v12.x/api/events.html).

List;
* `EventEmitter.errorMonitor`
* `emitter[Symbol.for('nodejs.rejection')](err, eventName[, ...args])`
* `events.captureRejections`
* `events.captureRejectionSymbol`
* `events.on(emitter, eventName)`

Can you please add them to @types/node? Thank you.

**Comment by orgads** [comment]
Anybody?

**Comment by orgads** [comment]
cc @peterblazejewicz

**Comment by peterblazejewicz** [comment]
👍

**Comment by orgads** [comment]
Thanks for picking it up.

Any progress with this?

**Comment by orgads** [comment]
Ping

**Comment by duydao** [comment]
Is there a workaround for this?

**Comment by peterblazejewicz** [comment]
- [ ] EventEmitter.errorMonitor
- [ ] emitter[Symbol.for('nodejs.rejection')](err, eventName[, ...args])
- [ ] events.captureRejections
- [ ] events.captureRejectionSymbol
- [ ] events.on(emitter, eventName)

**Comment by orgads** [comment]
Any progress with this?

**Comment by ExE-Boss** [comment]
I’m fixing the remaining issues in <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50266>.
