### ISSUE TITLE
DefinitelyTyped/types/d3-array/

### ISSUE THREAD

**Issue by sathuer** [DefinitelyTyped/DefinitelyTyped#45464]
DefinitelyTyped/types/d3-array/

I tried to use d3-array least function, but i have error in d3-array.ts.

I found that does not exist definition in index.d.ts file. 

How to use d3-array least function?

**Comment by Ledragon** [comment]
See #32162, current types are out of date

**Comment by sathuer** [comment]
@Ledragon Thank you for reply and I solved other logic (reduce)
