### ISSUE TITLE
[webpack-plugin-serve] http-proxy-middleware ships with types that are favored over @types/http-proxy-middleware and are not the same

### ISSUE THREAD

**Issue by G-Rath** [DefinitelyTyped/DefinitelyTyped#45479]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @shellscape @PlayMa256 @chimurai @zebMcCorkle @BendingBender

I've pinged all the parties involved, as this is an interesting situation that I think might require some coordination.

`http-proxy-middleware` now ships with its own types, which don't export the same types are `@types/http-proxy-middleware` which are imported by `@types/webpack-plugin-serve`.

This causes TypeScript to error since it favors types from the original package over one's sourced from `@types`:

```
node_modules/@types/webpack-plugin-serve/index.d.ts:9:10 - error TS2305: Module '"../../http-proxy-middleware/dist"' has no exported member 'Config'.

9 import { Config as HttpProxyMiddlewareConfig, Proxy } from 'http-proxy-middleware';
           ~~~~~~

node_modules/@types/webpack-plugin-serve/index.d.ts:9:47 - error TS2305: Module '"../../http-proxy-middleware/dist"' has no exported member 'Proxy'.

9 import { Config as HttpProxyMiddlewareConfig, Proxy } from 'http-proxy-middleware';
                                                ~~~~~
```

For the first error it seems that the problem is mainly one of naming: the `Config` types equivalent in `http-proxy-middleware` is called `Options`, so that should be fixable by having `@types/http-proxy-middleware` re-export the `Config` type as `Options`, and then import the type under that name in `@types/webpack-plugin-serve`.

However looking further into this for the `Proxy` type, it seems that `Proxy` is equal to `ReturnType<createProxyMiddleware>` exported from `http-proxy-middleware`, and so actually the whole import can be replaced with just importing `createProxyMiddleware` and the `proxy` property type becoming `typeof createProxyMiddleware`....

As can probably be seen this is a bit of an interesting situation that I don't know the best way to solve without breaking at least something for some version combo.

I think a good path forward could be to replace the dependency on `@types/http-proxy-middleware` with a peerDependency on `http-proxy-middleware@1` and import in `createProxyMiddleware`, but am open to other suggestions.

-------

This can be reproduced by doing `npm i -D @types/webpack-plugin-serve webpack-plugin-serve typescript && touch index.ts && tsc --noEmit index.ts`

**Comment by IlCallo** [comment]
The same problem seem to happen on `webpack-dev-server` package, which requires `@types/http-proxy-middleware`.

I cannot understand who shall I ask to fix the dependency, nor where the dependency are stated, as they are not into the `package.json` of https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/webpack-dev-server :thinking:

**Comment by freddy38510** [comment]
Thanks @IlCallo, i should definitively test the extension with TypeScript support enabled :)

It seems that @quasar/cli is using version "1.0.4", whereas this extension is using version "1.0.5".
