### ISSUE TITLE
@types/is-regex has no TS version tags on npm, breaking VS Code Automatic Type Acquisition

### ISSUE THREAD

**Issue by curledUpSheep** [DefinitelyTyped/DefinitelyTyped#45486]
Problem: `@types/is-regex` does not have the TS version tags (`@ts3.8`, `@ts3.9`) on npm

Impact: in newest VS Code, this prevents [Automatic Type Acquisition](https://code.visualstudio.com/docs/languages/javascript#_intellisense-is-not-working-for-external-libraries) from working properly if `is-regex` is installed (discovered through VS Code TS logs). This failure impacts Automatic Type Acquisition for all packages, not just this specific package.

For reference:

- [Package with correct TS version tags](https://www.npmjs.com/package/@types/is-typedarray?activeTab=versions)
- [@types/is-regex, lacking TS version tags](https://www.npmjs.com/package/@types/is-regex?activeTab=versions)

- [x] I tried using the `@types/is-regex` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ljharb @ExE-Boss 

Edit: including @RyanCavanaugh and @sandersn because it seems these NPM tags are something that the specific authors of these types don't have control over

**Comment by sandersn** [comment]
Thanks for the heads up. I ran the tagger on is-regex so this should be fixed now. 

I think the publisher must have crashed while trying to tag is-regex -- I'll go see if I can find the logs for the publish.

**Comment by sandersn** [comment]
Yep, here's the end of the log:

```
=== Publishing packages ===
Publishing is-regex...
Tag @types/is-regex@1.0.0 as ["ts3.0","ts3.1","ts3.2","ts3.3","ts3.4","ts3.5","ts3.6","ts3.7","ts3.8","ts3.9","ts4.0","latest"]
```

And when the service restarts, it only checks that the package was published, not that it was tagged correctly.
