### ISSUE TITLE
[@types/mongoose] Bug when using indexed array elements

### ISSUE THREAD

**Issue by Eldar-X** [DefinitelyTyped/DefinitelyTyped#45480]
Hi! I am using latest release of @types/mongoose 5.7.24 and when my interface contains indexed elements create method always crash my app.

For example:

```ts
interface Test {
 myArray: ["HELLO" | "WORLD"]
}
const test: Test = { myArray: ["HELLO"] }
myModel.create(test);

/*
Type '"HELLO"' is not assignable to type '"WORLD"

But myArray: string[] working as expected
*/
```

- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi, @lukasz-zak, @Alorel, @jendrikw, @ethanresnick, @vologab @jussikinnula @ondratra, @alfirin, @idandrd, @various89, @Fazendaaa, @NormanPerrin, @stablio, @emmanuelgautier, @frontendmonster, @mingchen, @penumbra1, @orblazer, @HughKu, @niuware, @Vladmel1234, @jloveridge), @grimmer0125, @richarddd, @ToucheSir, @borfig, @dinodeSimon, @anthony-kenikh, @iamchathu, @lkho, @tomyam1, @nephix, @rlaace423, @ChazEpps, @avaly, @JanNemcik, @cl3dson, @richardsimko, @ith, @jeremyben, @tHBp

**Comment by jeremyben** [comment]
You used a tuple type instead of an array type.
Try this interface:
```ts
interface Test {
 myArray: ("HELLO" | "WORLD")[]
}
```

**Comment by Eldar-X** [comment]
@jeremyben  Okey it's wrong example but there is another issue  look at this
```ts
interface Test {
 myArray: ("HELLO" | "WORLD")[]
}

This is working:
myModel.create({myArray:["HELLO"]})

This is not
const myVar = {myArray: ["HELLO"]}
myModel.create(myVar)

Even type assertion not helping
const myVar = {myArray: ["HELLO"]} as Test
const myVar: Test = {myArray: ["HELLO"]}

Only working when pass object directly inside create function :(
```

**Comment by jeremyben** [comment]
I know, it's a well known problem with litteral types : 
Without hints, TypeScript won't assume that your string `"HELLO"` is meant as a litteral `"HELLO"`, so it types it as `string`.

You should use the `const` assertion to help TypeScript with that:

```ts
const myVar = { myArray: ["HELLO"] } as const
```

or directly on the right node:

```ts
const myVar = { myArray: ["HELLO"] as const }
```

**Comment by Eldar-X** [comment]
Thank you! I found solution based on your answer. I think problem is not of create method but in interface. I have very large project (Monorepo) where all my interfaces schemas etc. depends on each other and best solution looks like this.

const model = Model<Readonly<MyInterface>>

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
