### ISSUE TITLE
[@types/lodash] !isEmpty should tell typescript variable is not null

### ISSUE THREAD

**Issue by tettoffensive** [DefinitelyTyped/DefinitelyTyped#45521]
I asked on the typescript discord and was referred here. When using lodash methods like `isEmpty` which guard against falsey values, typescript still warns/complains of variables which could be null or undefined. The type definitions should be updated so that typescript knows that the values are not null/undefined.

- `@types/lodash@^4.14.104`
- `tsc --version => Version 3.9.5`
 - Authors: @bczengel @chrootsu @stepancar @aj-r @e-cloud @thorn0 @jtmthf @DomiR @WilliamChelman 

**The current state**:
```ts
if (!isEmpty(myArray)) {
  myArray?.map(...)
}
```

**My workaround right now so that typescript knows the variable is not null/undefined**:
```ts
if (myArray && !isEmpty(myArray)) {
  myArray.map(...)
}
```

**Comment by aj-r** [comment]
This has been requested many times but unfortunately is impossible. The
issue is that the reverse type guard (e.g. the else block) will incorrectly
believe that the variable is null/undefined.

**Comment by tettoffensive** [comment]
😢 Thanks @aj-r I guess I'll stick with my workaround.

**Comment by fatihaziz** [comment]
I encounter this problem,
my solution is make custom function that absolutly will return empty array,

	export const isEmpty = <T>(value: T | undefined) : value is undefined => {
		if (typeof value === `number` || typeof value === `boolean`) {
			return false
		}
		if (typeof value === `undefined` || value === null) {
			return true
		}
		if (value instanceof Date) {
			return false
		}
		if (value instanceof Object && !Object.keys(value).length) {
			return true
		}
		if (Array.isArray(value)) {
			if (value.length === 0) {
				return true
			}
			if (value.every(item => Guard.isEmpty(item))) {
				return true
			}
		}
		if (<any>value === ``) {
			return true
		}

		return false
	}

	// optional
	export const notEmpty = <T extends unknown>(value: T): value is Required<T> => {
		return !isEmpty(value) // add "as any" if still got error here
	}

then it will work fine when using it like

	const shouldBeEmpty : string | undefined = ""
	if(isEmpty(shouldBeEmpty)) {
		// shouldBeEmpty type: undefined
	}
	// outside block
	// shouldBeEmpty type: string
	

and the notEmpty will do the opposite.

I hope my workaround will help!
Best regards!

**Comment by neolivz** [comment]
function isEmpty(v: any): v is {} | undefined | null | '' | boolean | number {
  return _.isEmpty(v)
}

**Comment by fatihaziz** [comment]
> 

this become too generic given the boolean and number should be "not empty" value.

**Comment by liangl1412** [comment]
Recently ran into this and this is my workaround

in global.d.ts 
```
declare module 'lodash/isEmpty' {
    import _isEmpty from "lodash/isEmpty";
    const isEmpty = <T>(value: T | undefined): value is undefined => {
        return _isEmpty(value);
    }
    export default isEmpty;
}
```

basically use [type predicates](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) and wrap around `isEmpty` from lodash.

You probably also need add `"skipLibCheck": true,` if it complain about ambient context

**Comment by fatihaziz** [comment]
> Recently ran into this and this is my workaround
> 
> in global.d.ts 
> ```
> declare module 'lodash/isEmpty' {
>     import _isEmpty from "lodash/isEmpty";
>     const isEmpty = <T>(value: T): value is undefined | null => {
>         return _isEmpty(value);
>     }
>     export default isEmpty;
> }
> ```
> 
> basically use [type predicates](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) and wrap around `isEmpty` from lodash.
> 
> You probably also need add `"skipLibCheck": true,` if it complain about ambient context

Dont skip lib check
It will ignore all types descrepancy from your dependencies (aka node_modules)

**Comment by fatihaziz** [comment]
Guys, check this out: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60401
it might be fix this
