### ISSUE TITLE
[@types/async-redis] type definitions are not correct

### ISSUE THREAD

**Issue by boompig** [DefinitelyTyped/DefinitelyTyped#45529]
I tried using `@types/async-redis` and had issues with the types. In particular I am seeing the types for `@types/async-redis` are the same as those for `@types/redis`, which should not be the case.

I'm mentioning @peterblazejewicz @philipp-sapronov because I saw these users in git blame. Please let me know if you are not the right people in this context.

**Comment by boompig** [comment]
Here is a code sample that is essentially taken from https://www.npmjs.com/package/async-redis with minimal translation to Typescript. This will fail with `ts-node` with latest typescript:

`
import * as asyncRedis from "async-redis";
const client = asyncRedis.createClient();

export async function getFoo(): Promise<string> {
    return await client.get("foo");
}

export const asyncBlock = async () => {
    await client.set("foo", "hello world");
    const val = await getFoo();
    console.log(val);
};
`

**Comment by peterblazejewicz** [comment]
I believe you want to use 'esModuleInterop' in your config file and (removed just export to not rewrite stuff further):
```ts
const asyncRedis = require('async-redis');
const client = asyncRedis.createClient();

async function getFoo(): Promise<string> {
  return await client.get('foo');
}

const asyncBlock = async () => {
  await client.set('foo', 'hello world');
  const val = await getFoo();
  console.log(val);
};

(async () => {
    await asyncBlock();
})();
```
```
npx ts-node index.ts
hello world
```

**Comment by joshuabahr** [comment]
This doesn't solve the issue. The problem is that the types for async-redis believes that client.get('key') return value is boolean.

**Comment by codingbeans** [comment]
+1
The types are incorrect because they refer to the `redis` package and believe all the functions are returning `Promise<boolean>`.

**Comment by jamster10** [comment]
As a way around this, I opted to use the redis suggestion of using Promisify. and wrapping the functions I need. This ends up looking like this:

export const redisClient = redis.createClient(options);

export const redisAsync = {
  get: promisify(redisClient.get).bind(redisClient),
  hget: promisify(redisClient.hget).bind(redisClient),
  hgetall: promisify(redisClient.hgetall).bind(redisClient),
  hincrby: promisify(redisClient.hincrby).bind(redisClient),
  hset: promisify(redisClient.hset).bind(redisClient),
  expire: promisify(redisClient.expire).bind(redisClient)
};

with usage of course like:

const count = await redisAsync.hincrby("key", "value", 1);

It's a minimal approach, the typings are correct, and I no longer need async-redis package or its types.

**Comment by toman-game** [comment]
> As a way around this, I opted to use the [redis suggestion of using Promisify](https://www.npmjs.com/package/redis#promises). and wrapping the functions I need. This ends up looking like this:
> 
> ```js
> export const redisClient = redis.createClient(options);
> 
> export const redisAsync = {
>   get: promisify(redisClient.get).bind(redisClient),
>   hget: promisify(redisClient.hget).bind(redisClient),
>   hgetall: promisify(redisClient.hgetall).bind(redisClient),
>   hincrby: promisify(redisClient.hincrby).bind(redisClient),
>   hset: promisify(redisClient.hset).bind(redisClient),
>   expire: promisify(redisClient.expire).bind(redisClient)
> };
> ```
> 
> with usage of course like:
> 
> ```js
> const count = await redisAsync.hincrby("key", "value", 1);
> ```
> 
> It's a minimal approach, the typings are correct, and I no longer need async-redis package or its types.

Very helpful!!

**Comment by ttzn** [comment]
When using the `promisify().bind()` approach, make sure that the `strictBindCallApply` compiler flag is set, otherwise the resulting functions will be untyped.

**Comment by wbobeirne** [comment]
This unfortunately still isn't perfect, it looks like the various overloads aren't working.
```ts
import { RedisClient } from 'redis';
import { promisify } from 'util';

const redisClient = new RedisClient();
const redis = {
  set: promisify(redisClient.set).bind(redisClient),
}

redis.set('key', `value`, 'EX', 5);
                          ^^^^^^^
                          Expected 2 arguments, but got 4. ts(2554)
```

**Comment by ttzn** [comment]
At the moment these typings make very little sense to me, unless I'm missing something you can still pass callbacks which defeats the very purpose of the package, and every command returns `Promise<boolean>`. This should be the target:

```typescript
const client = createClient();
const value: Promise<string> = client.get("key");
const length: Promise<number> = client.llen("list");
const removed: Promise<string> = client.rpop("key");
const incremented: Promise<number> = client.incr("numkey");
```

**Comment by twixr** [comment]
Same issue, The return type of `redis.get` is `Promise<boolean>`, which is incorrect, it's supposed to be a string

**Comment by dyc3** [comment]
I've just spent the afternoon trying to do this dynamically, and I don't know enough about typescript to make it work.

<details>
<summary>Leaving my work here for reference, maybe somebody can get it to work.</summary>

```typescript
import { Commands, RedisClient, ClientOpts, Callback } from 'redis';

type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

type Omitted = Omit<RedisClient, keyof Commands<boolean>>;

// type GetLength<T extends any[]> = T extends { length: infer L } ? L : never;
type GetLength<T extends unknown[]> = T["length"];
type DropFirstInTuple<T extends unknown[]> = T extends [arg: any, ...rest: infer U] ? U : T;
type GetLast<T extends unknown[]> = T[GetLength<DropFirstInTuple<T>>];
type Head<T extends any[]> = T extends [ ...infer Head, any ] ? Head : any[]
type RemoveLastParameter<T extends (...args: any) => any> = (...args: Head<Parameters<T>>) => ReturnType<T>


type GetCallbackArg<Func extends ((cb: Callback<unknown>) => any)> = GetLast<Parameters<Func>>

type GetPromiseReturnType<Func extends ((cb: Callback<unknown>) => any)> = Required<GetLast<Parameters<GetCallbackArg<Func>>>>;

// A rough breakdown of what is happening in GetPromiseReturnType.
type base = RedisClient["ping"]
type step1 = Required<Parameters<base>>
type step2 = GetLast<step1>
type step2b = GetCallbackArg<base>
type step2c = GetLast<GetLast<[Required<Parameters<base>>]>> // HACK: because Required makes the tuple not a tuple anymore, put the tuple in an explicit tuple, and get the last value twice to unwrap it. Typescript bug?
type step2d = GetLast<Required<Parameters<base>>>
type step3 = Parameters<step2>
type step4 = GetLast<step3>


type MakeCallback<Args extends any[], Ret> = (...args: Args) => Ret


type ManualSignatures = {
    get(key: string): Promise<string>
    set(key: string, value: string): Promise<"OK">
    ping(data?: string): Promise<string>
    del(key: string): Promise<number>
}

type Promisified = {
    [P in keyof Omit<RedisClient, keyof Omitted>]: RedisClient[P] extends (cb: Callback<unknown>) => any ? MakeCallback<Parameters<RemoveLastParameter<RedisClient[P]>>, GetPromiseReturnType<RedisClient[P]>> : never;
}
```

</details>

Instead, I'm just going to hard code it, so we at least have some working types.

**Comment by philipp-sapronov** [comment]
@dyc3 hardcode is much better than advanced types by many reasons, most of helpers like Head, Last, DropFirst etc. have been already implemented in ts-toolbelt. Thank you for your job!

**Comment by jamesopti** [comment]
How do I use this without the built in `async-redis/src/index.d.ts` file getting in my way? is there a way to ignore it completely?

**Comment by peterblazejewicz** [comment]
@jamesopti 
as a start, you can use one of `include`/`exclude`/`files` tsconfig.json configuration options (pick one matching your project), to remove some types from resolution. You can trace how tsc picks a file using '--traceResolution' command line option
