### ISSUE TITLE
[types@react-redux] dependencies on redux 3.x are not supported

### ISSUE THREAD

**Issue by quasiunafantasia** [DefinitelyTyped/DefinitelyTyped#45596]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-redux` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x]  I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/). (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @kenzierocks @clayne11 @tansongyang @nicholasboll @mdibyo @kallikrein @val1984 @jrakotoharisoa @apapirovski @surgeboris @soerenbf @mrwolfz @dylanvann @Lazyuki @kazuma1989

Hi guys, 
I am using `redux 3.x.x` and `react-redux 7.2.0` (they supposed to be  [compatible ](https://github.com/reduxjs/react-redux/blob/master/package.json#L40) )
I am facing problems with `@types/react-redux 7.x` because they use types from `redux 4.x` and they are not compatible with types from the previous versions.
Could the version with dependency on the previous redux be added? Or what should be the version for such typings if i submit them via PR?

**Comment by quasiunafantasia** [comment]
Attaching a [gist](https://gist.github.com/quasiunafantasia/877fe84833dc968c4913168867c4bc6d) with the patch I am using to add type definitions for hooks 
Its 99% copypaste from `@types/react-redux 7.1.9` only the number of generic params for `Store` and `Dispatch` differs

**Comment by kazuma1989** [comment]
Hi! I got your problem.

[package.json](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c4ec1f4c777696ffc812376b2a11bc2b7235515a/types/react-redux/package.json#L6) should contain `"redux": "^2.0.0 || ^3.0.0 || ^4.0.0-0"` as a peer dependency but I don't know what will happen to the current users. It may be a breaking change. What about your local tests when you change the package.json?

And we need help from some experts.

**Comment by quasiunafantasia** [comment]
The typings start to fail because `Store` types are incompatible.
https://github.com/reduxjs/redux/blob/master/src/types/store.ts#L127
https://github.com/reduxjs/redux/blob/v3.5.2/index.d.ts#L114
Also the `AnyAction` type is missing in previous version and typings versions for `hoist-non-react-statics` are different

**Comment by robpc** [comment]
@quasiunafantasia Appreciate you taking the time to write-up this issue. The gist you posted looks encouraging, but could you provide more details about how you are using it? When I add it to my project, I get errors like `Duplicate identifier 'AnyIfEmpty'.` and `Subsequent property declarations must have the same type.` which are limitations of overriding definitions according to the typescript documentation.

**Comment by quasiunafantasia** [comment]
Were are using micro frontends, so and this influenced the solution.
we included the typings patch [(gist updated)](https://gist.github.com/quasiunafantasia/877fe84833dc968c4913168867c4bc6d) into one of our libraries.
To include it in project I needed to change the type definitions lookup setting in  
`tsconfig.json`  the following way:
```
"typeRoots": [
    "./node_modules/path/to/react-redux/patch/",
    "./node_modules/@types/"
]
```
It`s important to place the patch first. That`s weird, but TS did not see it otherwise.

the versions in the `package.json` are the following: 
```
{
 "@types/react-redux": "^5.0.20",
 "@types/redux": "^3.6.0",
  "react-redux": "^7.2.0",
```
We chose to go with the previous version of typings + patch because it was fitting the existing repos setup. It might be easier for you just to include the whole type definition and host it in your repo to avoid confusion with mismatching versions. 
Hope this helps

**Comment by robpc** [comment]
@quasiunafantasia Ahh thank you! Using the older version of `@types/react-redux` was the part I was missing.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
