### ISSUE TITLE
@types/mongoose create schema forces non-required properties at crate time

### ISSUE THREAD

**Issue by tomyam1** [DefinitelyTyped/DefinitelyTyped#45608]
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andreialecu 

In the example below, `addedInMiddleware` is required on the document but not on the create schema since it's added in a middleware.

The schema added in 88a54a939455efa0937b55ed507631415a574c44 causes `addedInMiddleware` to be required at compile time, but it shouldn't be.

@andreialecu I'd appreciate if you can fix this.

```typescript
import * as Mongoose from 'mongoose'

interface IDocument extends Mongoose.Document {
    addedInMiddleware: string
}

const schema = new Mongoose.Schema({
    addedInMiddleware: String,
})

schema.pre('validate', async function (this: IDocument) {
    if (!this.addedInMiddleware) this.addedInMiddleware = 'added';
});

const model = Mongoose.model<IDocument>('model', schema);

/*
TS2769: No overload matches this call.   
The last overload gave the following error.     
Argument of type '{}' is not assignable to parameter of type 'Pick<{ _id: any; addedInMiddleware: string; } & { _id: any; }, "addedInMiddleware"> & { _id?: any; }'.       
Property 'addedInMiddleware' is missing in type '{}' but required in type 'Pick<{ _id: any; addedInMiddleware: string; } & { _id: any; }, "addedInMiddleware">'.
 */
model.create({});
```

**Comment by andreialecu** [comment]
Proper usage here is:

```ts
type CreateDocument = Omit<IDocument, "addedInMiddleware">;
model.create<CreateDocument>({});
```

Or define your interface like:
```ts
interface IDocument extends Mongoose.Document {
    addedInMiddleware?: string
}
```

**Comment by tomyam1** [comment]
Sorry, neither of your suggestions are proper usage.

> Proper usage here is:
> 
> ```ts
> type CreateDocument = Omit<IDocument, "addedInMiddleware">;
> model.create<CreateDocument>({});
> ```

This will NOT work for nested objects.

> Or define your interface like:
> 
> ```ts
> interface IDocument extends Mongoose.Document {
>     addedInMiddleware?: string
> }
> ```

This is just wrong. `addedInMiddleware` is not optional in the doucment.

**Comment by andreialecu** [comment]
```ts
interface IDocument extends Mongoose.Document {
    readonly addedInMiddleware: string
}
```

This will also work if it's read only.

**Comment by andreialecu** [comment]
> This will NOT work for nested objects.

Of course it will, you can override the type at any level in the schema.

Here's a helper type to help with that:
https://github.com/piotrwitek/utility-types/issues/129

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
