### ISSUE TITLE
@types/spotify-api: VSCode cannot find namespace SpotifyApi unless index.d.ts open

### ISSUE THREAD

**Issue by hspinks** [DefinitelyTyped/DefinitelyTyped#45629]
I am having issues getting VSCode to recognize the types from `@types/spotify-api`. I have installed the package as a dev dependency currently using `v0.0.3` with the current latest version of TypeScript, `v3.9.5`. When I attempt to use the typings from the package, VSCode gives me an error: `Cannot find namespace 'SpotifyApi'. ts(2503)`. However, TypeScript is able to compile the code fine despite the VSCode error.

The fix that I've found is to open the `index.d.ts` file from the `node_modules` folder in my VSCode workspace. As soon as I do that, all of the errors disappear, and VSCode will autocomplete the typings from the package.

This is more of an inconvenience than a show-stopper, but it is definitely annoying to have to keep that file open at all times, and it's difficult to communicate with new collaborators about the issue. This seems like it may be an issue with VSCode, but I am using a number of other `@types` typings in this project (including `@types/lodash`, `@types/node`, and `@types/uuid`), and I am not having any of the same issues, so I thought I would check here first to see if anyone else has had similar issues. I'm relatively new to TypeScript, but if there's a fix that can be done in the package, I'm happy to take a stab at it if someone can provide a little bit of direction on where to start!

---

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @skovmand @Stadly @piksel @Some-Dood

**Comment by Some-Dood** [comment]
That is indeed strange. My first instinct here is that perhaps [Automatic Type Acquisition](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition) has not been enabled in your project yet. In order to do so, simply configure your `tsconfig.json` as in the documentation linked above.

**Comment by Some-Dood** [comment]
Apologies. I linked the wrong documentation. [Here](https://www.typescriptlang.org/v2/tsconfig#typeAcquisition) is the correct link.

To explain further, IntelliSense scans the `package.json` for any type packages. In theory, it should be able to "acquire" the `@types/spotify-api` package from your `devDependencies`. By then, it would be able to inject the `SpotifyApi` namespace into IntelliSense.

Hope this clarifies things better.

**Comment by hspinks** [comment]
@Some-Dood thanks so much for the quick response and helpful explanation! My project is a serverless service using the [`serverless-plugin-typescript`](https://github.com/prisma-labs/serverless-plugin-typescript) plugin to add TypeScript support. The plugin says it's zero-config and works without any tsconfig in the project. However, it looks like the lack of tsconfig is what was causing the issue.

I added a `tsconfig.json` to my project using the [default tsconfig](https://github.com/prisma-labs/serverless-plugin-typescript#tsconfigjson) from the project, and that immediately fixed the issue. VSCode is reading the typings fine now, and I didn't need to touch the `typeAcquisition` option. I'm not sure why the [default tsconfig included in the package](https://github.com/prisma-labs/serverless-plugin-typescript/blob/master/src/typescript.ts#L6) was doing something different, but looks like we are good to go now 😄 

Thank you!
