### ISSUE TITLE
[ramda] chain should accepts a curried function as its first parameter

### ISSUE THREAD

**Issue by qxg** [DefinitelyTyped/DefinitelyTyped#45639]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/ramda` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @TheHandsomeCoder @donnut @mdekrey @sbking @afharo @teves-castro @1M0reBug @hojberg @samsonkeung @angeloocana @raynerd @moshensky @ethanresnick @deftomat @blimusiek @biern @rayhaneh @rgm @drewwyatt @jottenlips @minitesh @Krantisinh @pirix-gh @brekk @Nemo108 @jituanlin @Philippe-mills @Saul-Mirone @Nicholaiii

ramda's chain is implemented as https://github.com/ramda/ramda/blob/v0.27.0/source/chain.js
```
var chain = _curry2(_dispatchable(['fantasy-land/chain', 'chain'], _xchain, function chain(fn, monad) {
  if (typeof monad === 'function') {
    return function(x) { return fn(monad(x))(x); };
...
```
`chain` expects `fn` to be a curried function. 

However, chain's type definition is
`export function chain<X0, X1, R>(fn: (x0: X0, x1: X1) => R, fn1: (x1: X1) => X0): (x1: X1) => R;`

We should change `fn` to `(x0: X0) => (x1: X1) => R` to reflect implementation.

**Comment by chughes87** [comment]
This one looks resolved?
