### ISSUE TITLE
[@types/yup] ValidationError.message can be more than just a 'string'

### ISSUE THREAD

**Issue by gmanriqueUY-ad** [DefinitelyTyped/DefinitelyTyped#45696]
- [x] I tried using the `@types/yup` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dhardtke @vtserman @MoretonBayRC @sseppola @YashdalfTheGray @vincentjames501 @robertbullen @sat0yu @deskoh @mauricedb @kalley @elias-garcia @iansan5653 @fjc0k

Currently, the `message` property on the `ValidationError` class is typed as `string`, but it can actually be something else if we use a function instead of a string when defining the validation message (both using the `setLocale` or when defining the `schema`).

I've made [this repl](https://repl.it/repls/GentleStrictHashmaps#index.js) (in JS) in which a `ValidationError` thrown has a `message` that is an `object` and not a `string`.

**Comment by mauricedb** [comment]
@gmanriqueUY-ad 

Maybe I am misunderstanding but the message is typed as:
```ts
export type TestOptionsMessage<Extra extends Record<string, any> = {}, R = any> =
    | string
    | ((params: Extra & Partial<TestMessageParams>) => R);
```

And your sample compiles without errors with the current type definition.

[Here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yup/yup-tests.ts#L671) is a test for it as well.

**Comment by iansan5653** [comment]
Yeah, seems to be working already for me as well: https://codesandbox.io/s/jolly-flower-75eye?file=/src/index.test.ts

**Comment by gmanriqueUY-ad** [comment]
Thanks for your answers @mauricedb and @iansan5653 . My repl wasn't clear enough because it was actually not using Typescript, :sweat_smile: , sorry about that.

I created [a new one](https://repl.it/repls/SympatheticGreedyMass#index.ts) using TS.

If you hover on `message` on line 19, TS says that the type is `string` (make sure you enabled intellisense on settings) but it actually is an object
![image](https://user-images.githubusercontent.com/58528974/85756373-1daf1180-b6e5-11ea-94d3-8ee61e01961f.png)

**Comment by iansan5653** [comment]
Ahh, I see. It should be something like

```
export class ValidationError<T = string> extends Error {
  message: T;
  /* ... */
}
```
along with some other changes to utilize the generic.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
