### ISSUE TITLE
[@types/react-native] Modal component statusBarTranslucent prop is missing

### ISSUE THREAD

**Issue by alexeymolchan** [DefinitelyTyped/DefinitelyTyped#45711]
- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention] the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @NickGerleman @alloy @zusinShinpei @Esemesek @jeremybarbet @akrger

Hi, statusBarTranslucent prop is missing for Modal component

<img width="589" alt="Снимок экрана 2020-06-25 в 23 36 05" src="https://user-images.githubusercontent.com/22521355/85792726-a5743a80-b73c-11ea-8b48-272c2d07934d.png">

**Comment by alloy** [comment]
@alexeymolchan Thanks for letting us know. Would you be willing to create a PR for this?
