### ISSUE TITLE
Duplicate identifier 'LibraryManagedAttributes'.  MANJARO LINUX

### ISSUE THREAD

**Issue by khelpixRF** [DefinitelyTyped/DefinitelyTyped#45740]
`/run/media/arielreyesflores/extended/src/APIClient/ClientApp/node_modules/@types/react/index.d.ts
TypeScript error in /run/media/arielreyesflores/extended/src/APIClient/ClientApp/node_modules/@types/react/index.d.ts(2835,14):
Duplicate identifier 'LibraryManagedAttributes'.  TS2300

    2833 |         // We can't recurse forever because `type` can't be self-referential;
    2834 |         // let's assume it's reasonable to do a single React.lazy() around a single React.memo() / vice-versa
  > 2835 |         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
         |              ^
    2836 |             ? T extends React.MemoExoticComponent<infer U> | React.LazyExoticComponent<infer U>
    2837 |             ? ReactManagedAttributes<U, P>
    2838 |             : ReactManagedAttributes<T, P>`

¿what is this in manjaro linux?

**Comment by jimmyandrade** [comment]
I am experiencing the same:

```
TS2300: Duplicate identifier 'LibraryManagedAttributes'.
node_modules/@types/react/index.d.ts (2953:14)

2953         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                  ~~~~~~~~~~~~~~~~~~~~~~~~

  ../../node_modules/@types/react/index.d.ts:2963:14
    2963         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    'LibraryManagedAttributes' was also declared here.
```

**Comment by IrvinDevFlores** [comment]
@jimmyandrade this happens because there a duplicate with yarn and package.json, this means that your could remove node_modules and then reinstal via: yarn install and all package will be added or you can try
`yarn remove @types/react
yarn add --dev @types/react`
**enyoy it.**

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
