### ISSUE TITLE
[@types/ramda] Support for placeholder

### ISSUE THREAD

**Issue by manueldois** [DefinitelyTyped/DefinitelyTyped#45741]
- [x] I tried using the `@types/ramda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors (some) : @TheHandsomeCoder @mdekrey @mrdziuban @sbking @Saul-Mirone @Philippe-mills 

Hi,
I'm starting with ramda on Node 10 + TS.
This works,
```javascript
import * as R from 'ramda'
R.add(R.__)(1)(2)
// => 3
```
But TS complains in two ways:

```
This expression is not callable.
     Type 'Number' has no call signatures.ts(2349)
Argument of type 'Placeholder' is not assignable to parameter of type 'number'
```

My `package.json`:
```javascript
  "devDependencies": {
    "@types/ramda": "^0.27.6",
    "typescript": "^3.9.5"
  },
  "dependencies": {
    "@types/node": "^13.11.0",
    "ramda": "^0.27.0"
  }
```

My `tsconfig.json`:
```javascript
{
  "compilerOptions": {
    "outDir": "./dist/",
    "noImplicitAny": true,
    "module": "commonJS",
    "target": "ES2019",
    "jsx": "preserve",
    "allowJs": true,
    "lib": ["ES2019"],
    "sourceMap": true,
  },
  "exclude": ["node_modules", "dist"],
  "include": ["src/**/*"]
}
```

If `R.__` is simply not yet supported, is there a way to tell TS to ignore the types of the methods arguments and returns?
More than typesafety, I want to keep intellisense for R's methods.

Thanks for your help!
And thank you authors for building these types!

**Comment by sindu12jun** [comment]
I also have the same issue, is there any update?

**Comment by sindu12jun** [comment]
```
const greet = R.replace('{name}', R.__, 'Hello, {name}!');
greet('Alice'); //=> 'Hello, Alice!'
```
This is copied from Ramda official doc, even this get type complained:

> Argument of type 'Placeholder' is not assignable to parameter of type 'string | ((match: string, ...args: readonly any[]) => string)'.   Type 'Placeholder' is not assignable to type '(match: string, ...args: readonly any[]) => string'.     Type 'Placeholder' provides no match for the signature '(match: string, ...args: readonly any[]): string'.

**Comment by manueldois** [comment]
Hi @sindu12jun.
No, I have not found an actual solution yet.
There's a workaround. Typecasting R.__ as any and the return as a function, not a value.
For example:

```javascript
const vowels = ['a','e','i','o','u']
const isVowel = R.includes( R.__ as any, vowels ) as unknown as Function
```

I could try and solve the issue by adding these function overloads to the declaration files, but I'd like to first contact the authors so I can know my pull request would be accepted.

**Comment by sindu12jun** [comment]
@manueldois sure, thank you for your response

**Comment by selfrefactor** [comment]
Actually, `R.__` might be dropped in the future according to this opened PR - https://github.com/ramda/ramda/pull/2705/files

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
