### ISSUE TITLE
@types/mongoose not work when use generic type

### ISSUE THREAD

**Issue by NateScarlet** [DefinitelyTyped/DefinitelyTyped#45751]
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
    - @horiuchi
    - @lukasz-zak
    - @jendrikw
    - @ethanresnick
    - @vologab
    - @jussikinnula
    - @ondratra
    - @alfirin
    - @idandrd
    - @various89
    - @Fazendaaa
    - @NormanPerrin
    - @stablio
    - @emmanuelgautier
    - @frontendmonster
    - @mingchen
    - @penumbra1
    - @orblazer
    - @HughKu
    - @niuware
    - @vladmel1234
    - @jloveridge
    - @grimmer0125
    - @richarddd
    - @ToucheSir
    - @borfig
    - @dinodeSimon
    - @anthony-kenikh
    - @iamchathu
    - @lkho
    - @tomyam1
    - @nephix
    - @rlaace423
    - @ChazEpps
    - @avaly
    - @JanNemcik
    - @cl3dson
    - @richardsimko
    - @ith
    - @jeremyben
    - @tHBp

This happens after i upgrade from 5.7.1 to 5.7.21.

```typescript
import { Types, Model, Document } from 'mongoose';

interface Doc extends Document {
  _id: Types.ObjectId;
}

async function work(model: Model<Doc>): Promise<void> {
  await model.find({ _id: Types.ObjectId() });
}

async function notWork<T extends Doc>(model: Model<T>): Promise<void> {
  // Argument of type '{ _id: ObjectId; }' is not assignable to parameter of type 'MongooseFilterQuery<Pick<T, Exclude<keyof T, "toString" | "update" | "get" | "set" | "removeListener" | "off" | "invalidate" | "increment" | "model" | "$isDeleted" | "remove" | "save" | "__v" | "$isDefault" | ... 42 more ... | "db">>>'.
  //   Type '{ _id: ObjectId; }' is not assignable to type '{ [P in keyof Pick<T, Exclude<keyof T, "toString" | "update" | "get" | "set" | "removeListener" | "off" | "invalidate" | "increment" | "model" | "$isDeleted" | "remove" | "save" | "__v" | "$isDefault" | ... 42 more ... | "db">>]?: P extends "_id" ? [...] extends [...] ? Condition<...> : Condition<...> : [...] extend...'
  await model.find({ _id: Types.ObjectId() });
}
```

**Comment by aemrebasus** [comment]
**This is the class related to the problem.** 


```

**@node_modules/@types/mongoose/index.d.ts**
/*
   * section schema.js
   * http://mongoosejs.com/docs/api.html#schema-js
   */
  class Schema<T = any> extends events.EventEmitter {
    /**
     * Schema constructor.
     * When nesting schemas, (children in the example above), always declare
     * the child schema first before passing it into its parent.
     * @event init Emitted after the schema is compiled into a Model.
     */
    constructor(definition?: SchemaDefinition, options?: SchemaOptions);

    /** Adds key path / schema type pairs to this schema. */
    add(obj: SchemaDefinition, prefix?: string): void;

    /** Return a deep copy of this schema */
    clone(): Schema;

```


**There are several methods like those. The methods SHOULD NOT get the T generic value because the class is using that key and it creating a conflict.  The methods SHOULD GET a new generic Key!!!** 

```
post<T extends Document>(method: string | RegExp, fn: (
      error: mongodb.MongoError, doc: T, next: (err?: NativeError) => void
    ) => void): this;

```


**Solution**

```
post<A=T>(method: string | RegExp, fn: (
      error: mongodb.MongoError, doc: A, next: (err?: NativeError) => void
    ) => void): this;

```

**Comment by aemrebasus** [comment]
> * [x]  I tried using the `@types/mongoose` package and had problems.
> * [x]  I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
> * [x]  I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
> * [x]  [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
>   
>   * Authors:
>     
>     * @horiuchi
>     * @lukasz-zak
>     * @jendrikw
>     * @ethanresnick
>     * @vologab
>     * @jussikinnula
>     * @ondratra
>     * @alfirin
>     * @idandrd
>     * @various89
>     * @Fazendaaa
>     * @NormanPerrin
>     * @stablio
>     * @emmanuelgautier
>     * @frontendmonster
>     * @mingchen
>     * @penumbra1
>     * @orblazer
>     * @HughKu
>     * @niuware
>     * @Vladmel1234
>     * @jloveridge
>     * @grimmer0125
>     * @richarddd
>     * @ToucheSir
>     * @borfig
>     * @dinodeSimon
>     * @anthony-kenikh
>     * @iamchathu
>     * @lkho
>     * @tomyam1
>     * @nephix
>     * @rlaace423
>     * @ChazEpps
>     * @avaly
>     * @JanNemcik
>     * @cl3dson
>     * @richardsimko
>     * @ith
>     * @jeremyben
>     * @tHBp
> 
> This happens after i upgrade from 5.7.1 to 5.7.21.
> 
> ```ts
> import { Types, Model, Document } from 'mongoose';
> 
> interface Doc extends Document {
>   _id: Types.ObjectId;
> }
> 
> async function work(model: Model<Doc>): Promise<void> {
>   await model.find({ _id: Types.ObjectId() });
> }
> 
> async function notWork<T extends Doc>(model: Model<T>): Promise<void> {
>   // Argument of type '{ _id: ObjectId; }' is not assignable to parameter of type 'MongooseFilterQuery<Pick<T, Exclude<keyof T, "toString" | "update" | "get" | "set" | "removeListener" | "off" | "invalidate" | "increment" | "model" | "$isDeleted" | "remove" | "save" | "__v" | "$isDefault" | ... 42 more ... | "db">>>'.
>   //   Type '{ _id: ObjectId; }' is not assignable to type '{ [P in keyof Pick<T, Exclude<keyof T, "toString" | "update" | "get" | "set" | "removeListener" | "off" | "invalidate" | "increment" | "model" | "$isDeleted" | "remove" | "save" | "__v" | "$isDefault" | ... 42 more ... | "db">>]?: P extends "_id" ? [...] extends [...] ? Condition<...> : Condition<...> : [...] extend...'
>   await model.find({ _id: Types.ObjectId() });
> }
> ```


The error  is saying that you cannot use _id anymore.

**Comment by NateScarlet** [comment]
I found out this is correct behavior. For generic `T extends { _id: ObjectId }`, the _id field can be a subclass of `ObjectId`, so i can't just use ObjectId as _id, a type cast is required.

```bson
import { Types, Model, Document, FilterQuery } from 'mongoose';

interface Doc extends Document {
  _id: Types.ObjectId;
}

async function correctUsage<T extends Doc>(model: Model<T>): Promise<void> {
  await model.find({ _id: Types.ObjectId() } as FilterQuery<T>);
}
```
