### ISSUE TITLE
Jasmine: Expected<T> appears to be overly strict with enums

### ISSUE THREAD

**Issue by sh-pq** [DefinitelyTyped/DefinitelyTyped#45776]
- [x] I tried using the `@types/jasmine` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @zvirja @chivesrs @stephenfarrar 

I've run into a problem with Jasmine's handling of expectations and enums. I am using:
* `jasmine-core@3.5.0` (latest)
* `@types/jasmine@3.5.11` (latest)
* `@types/jasminewd2@2.0.8` (latest)

Here is a minimal example:

```ts
enum Tab {
  Sprockets,
  Gizmos
}

class Page {
  public tab: Tab;

  public pickTab(newTab) {
    // * some side effects *
    this.tab = newTab;
  }
}

describe('Page', () => {
  let page: Page;

  beforeEach(() => {
    page = new Page();
  });

  it('should be able to pick a new tab', () => {
    page.tab = Tab.Sprockets;
    const newTab = Tab.Gizmos;

    page.pickTab(newTab);

    expect(page.tab).toBe(Tab.Gizmos);
  });
});
```

TypeScript is satisfied with this file. Jasmine 3.5.0, without type information, will run it. However, with type information it fails to compile with this error:

```
ERROR in src/app/test.spec.ts:28:27 - error TS2345: Argument of type 'Tab.Gizmos' is not assignable to parameter of type 'Expected<Tab.Sprockets>'.

28     expect(page.tab).toBe(Tab.Gizmos);
                             ~~~~~~~~~~
```

![Screenshot 2020-06-29 at 15 47 21](https://user-images.githubusercontent.com/33226922/86020609-08592080-ba20-11ea-9eff-d112a856de15.png)

If I move the `page.tab` declaration to a beforeEach, it will compile just fine:

```ts
describe('Page', () => {
  let page: Page;

  beforeEach(() => {
    page = new Page();
    page.tab = Tab.Sprockets; // <---
  });

  it('should be able to pick a new tab', () => {
    const newTab = Tab.Gizmos;

    page.pickTab(newTab);

    expect(page.tab).toBe(Tab.Gizmos);
  });
});
```

**Comment by chivesrs** [comment]
This seems to be less of a typings bug and more of TypeScript type inference?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
