### ISSUE TITLE
[lodash] Missing sample method on ArrayWrapper

### ISSUE THREAD

**Issue by nfantone** [DefinitelyTyped/DefinitelyTyped#4583]
I believe the `lodash.d.ts` definition is missing the [sample](https://lodash.com/docs#sample) method on its `LoDashArrayWrapper` interface.

A chain like this should work:

```javascript
 _.chain(someList).reject({id: id}).sample(5).value();
```

Instead, I got the following compiling error:

> Error:(42, 47) TS2339: Property 'sample' does not exist on type 'LoDashArrayWrapper<News>'.

Adding the following snippet to the `d.ts` resolves the issue:

```javascript
	interface LoDashArrayWrapper<T> {
		/**
		 * @see _.sample
		 **/
		sample(n: number): LoDashArrayWrapper<T>;
	}
```

**Comment by vvakame** [comment]
@nfantone please send a pull request. I'll review it.

**Comment by nfantone** [comment]
@vvakame Here, #4640

**Comment by chrootsu** [comment]
I think the issue can be closed.
