### ISSUE TITLE
@types/csso declares compress at the wrong place

### ISSUE THREAD

**Issue by xatian** [DefinitelyTyped/DefinitelyTyped#45863]
Hello,

- [X] I tried using the `@types/csso` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @screendriver, @erik-kallen

There is an error in your interface-definition of the csso-library.
The author of that library is using the csstree-library and he added the complete interface of that library with the property-name `syntax` to his export. Furthermore he created a `compress` method but he did not export this method in his own namespace `csso.syntax` but added it to the wrapped csstree import `csso.syntax.compress`.

**relevant part of the csso code file**
```ts
    var lib$1 = {
        version: require$$0.version,

        // main methods
        minify: minifyStylesheet,
        minifyBlock: minifyBlock,

        // css syntax parser/walkers/generator/etc
        syntax: Object.assign({
            compress: compress
        }, lib)
    };
```
`lib` =  csstree-library
`lib$1` = his own export
You can also find that he mentioned this on his github-page.

In your type-defintion you added this `compress` method directly to the css-interface which is wrong.
**index.d.ts**

```ts
interface Csso {
    /**
     * Minify source CSS passed as String
     * @param source
     * @param options
     */
    minify(source: string, options?: csso.MinifyOptions & csso.CompressOptions): csso.Result;

    /**
     * The same as minify() but for list of declarations. Usually it's a style attribute value.
     * @param source
     * @param options
     */
    minifyBlock(source: string, options?: csso.MinifyOptions & csso.CompressOptions): csso.Result;

    /**
     * Does the main task – compress an AST.
     */
    compress(ast: csstree.CssNode, options?: csso.CompressOptions): { ast: csstree.CssNode };

    syntax: typeof csstree;
}
```

To fix it please consider this:
**index.d.ts**

```ts
declare module "css-tree" {
    export function compress (ast: csstree.CssNode, options?: csso.CompressOptions): { ast: csstree.CssNode };
}

interface Csso {
    /**
     * Minify source CSS passed as String
     * @param source
     * @param options
     */
    minify(source: string, options?: csso.MinifyOptions & csso.CompressOptions): csso.Result;

    /**
     * The same as minify() but for list of declarations. Usually it's a style attribute value.
     * @param source
     * @param options
     */
    minifyBlock(source: string, options?: csso.MinifyOptions & csso.CompressOptions): csso.Result;

    syntax: typeof csstree;
}
```

Thank you!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
