### ISSUE TITLE
react-material-ui-form-validator: addValidationRule does not support Async

### ISSUE THREAD

**Issue by sheep-h** [DefinitelyTyped/DefinitelyTyped#45861]
@FrankBrullo

Hi, 

I'm using the latest version(2.0.5) of @types/react-material-ui-form-validator.

As far as I know, addValidationRule support Async. but, looks like does not support in typescript.

**Comment by FrankBrullo** [comment]
addValidationRule is part of react-form-validator-core.
I am not seeing any async support there.
Do you mind to point to the code that you are referring to?

Thanks.

**Comment by sheep-h** [comment]
@FrankBrullo

I am not good at English.
So I don't know if I understood it correctly.


This code only has an error in the type script.
**Argument of type '(value: any) => Promise<boolean>' is not assignable to parameter of type '(value: any) => boolean'.
  Type 'Promise<boolean>' is not assignable to type 'boolean'.ts(2345)**

```
...

ValidatorForm.addValidationRule('isCheck', (value: any) => {
	//async call
	return axios.get<any>(this.apiUrl , param).then(
		(res)=> {
			if(res.data.code == 200){
				return true;
			}else{
				return false;
			}
		}
	)
});

...
```






So, I would like you to change this code in the library with the following code.

```
export class ValidatorForm extends React.Component<ValidatorFormProps> {
    static addValidationRule(name: string, callback: (value: any) => boolean): void;
 ...
}
```
🔽 🔽 🔽 
```
export class ValidatorForm extends React.Component<ValidatorFormProps> {
    static addValidationRule(name: string, callback: (value: any) => boolean | Promise<boolean>): void;
 ...
}
```

Please check this part.
Thanks  :)

**Comment by FrankBrullo** [comment]
The function addValidationRule returns it is a synchronous call and it returns a boolean according to the react-form-validation-core documentation https://www.npmjs.com/package/react-material-ui-form-validator

`ValidatorForm.addValidationRule('isPasswordMatch', (value) => {
    if (value !== this.state.user.password) {
        return false;
    }
    return true;
});`

So the typescript definition is correct.
When you say "As far as I know, addValidationRule support Async.", where did you find that information?

I am not able to see it in the documentation anywhere else.

**Comment by sheep-h** [comment]
I got to know you here.
https://github.com/NewOldMax/react-material-ui-form-validator/issues/98

It says that this function is supported from react-material-ui-form-validator 2.0.6.

**Comment by FrankBrullo** [comment]
@sheep-h I have added the changes as you have requested in the next build. It should be going live in a couple of days.

Thanks for your feedback.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
