### ISSUE TITLE
@types/minio getObject promise should return a readable stream

### ISSUE THREAD

**Issue by adrian-delgado** [DefinitelyTyped/DefinitelyTyped#45872]
- [x] I tried using the `@types/minio` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @barinbritva @castorw @loremaps @OutdatedVersion

The `getObject` and `getPartialObject` should probably return a `NodeJS.ReadableStream` stream instead of the base `stream.Stream` (https://github.com/minio/minio-js/blob/ffd3fdb831777553bafd11f07ed8e8f2624d7816/src/main/minio.js#L362).

Similarly, `putObject` should probably accept a `NodeJS.WritableStream` stream instead of a base `stream.Stream`.

**Comment by barinbritva** [comment]
I'll check it out

**Comment by barinbritva** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45912

**Comment by barinbritva** [comment]
@adrian-delgado, for `putObject` uses ReadableStream too, because file is read to pass its content to S3
[putObject doc](https://docs.minio.io/docs/javascript-client-api-reference.html#putObject)

**Comment by adrian-delgado** [comment]
> @adrian-delgado, for `putObject` uses ReadableStream too, because file is read to pass its content to S3
> [putObject doc](https://docs.minio.io/docs/javascript-client-api-reference.html#putObject)

ah yes that makes sense. Thanks for looking into it.

**Comment by barinbritva** [comment]
@adrian-delgado, the fix was merged. Please, check if everything is ok for you. If so, please, close the issue.
And thanks for your report!

**Comment by adrian-delgado** [comment]
@barinbritva Everything ok for me. thank you :)
