### ISSUE TITLE
types for kurento-client

### ISSUE THREAD

**Issue by ninad-d** [DefinitelyTyped/DefinitelyTyped#45901]
Is something wrong with CI or publishing infrastructure? No

If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jhukdev 

I am using the @types/kurento-client. I think it has some of the types missing on it. For example I wanted to to use Mediapipeline to create a composite stream. The compiler throws error because as per type definition file Mediapipeline's create function does not accepts 'Composite' parameter.

**Comment by jhukdev** [comment]
Hi @ninad-d, 

It's likely some methods are missing from the definition file, myself and @michelalbers have done our best to cover types for common use cases we've encountered.

If you could put together a simple repo illustrating the issue, when I get a minute I can take a look for you. 

Alternatively, feel free to contribute!

All the best 👍

**Comment by ninad-d** [comment]
@jhukdev thanks for the reply. Just wanted to make sure that you are aware of it. Let me see if I can contribute to the typing as well.

**Comment by michelalbers** [comment]
> @jhukdev thanks for the reply. Just wanted to make sure that you are aware of it. Let me see if I can contribute to the typing as well.

Would be very happy to see that :)

**Comment by ninad-d** [comment]
Need to add some more typings.
