### ISSUE TITLE
Latest version of @types/graphql-resolvers breaks the TS level build.

### ISSUE THREAD

**Issue by sanket-work** [DefinitelyTyped/DefinitelyTyped#45910]
- [x] I tried using the `@types/graphql-resolvers` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] Mentioned 
                 Alejandro Corredor <https://github.com/aecorredor>
                 Luis Felipe Zaguini <https://github.com/zaguiini>
                 Mike Engel <https://github.com/mike-engel>
  - Authors: @aecorredor @zaguiini @mike-engel 

After upgrading to the latest version i.e v0.3.0 the TS build breaks with below error for wherever the combinedResolver function is used. The `graphql-resolvers` is at the latest stable release
```
error TS2322: Type 'IFieldResolver<void, IGraphQLCustomResolversContext, void, any>' is not assignable to type 'IResolverObject<any, any, any> | IResolverOptions<any, any, any> | IFieldResolver<any, any, any>'.
  Type 'IFieldResolver<void, IGraphQLCustomResolversContext, void, any>' is not assignable to type 'IFieldResolver<any, any, any>'.
    Types of parameters 'info' and 'info' are incompatible.
      Type 'GraphQLResolveInfo & { mergeInfo: MergeInfo; }' is not assignable to type 'GraphQLResolveInfo & { mergeInfo?: MergeInfo | undefined; }'.
        Type 'GraphQLResolveInfo & { mergeInfo: MergeInfo; }' is not assignable to type 'GraphQLResolveInfo'.
          Types of property 'returnType' are incompatible.
            Type 'import("/opt/app/node_modules/graphql/type/definition").GraphQLOutputType' is not assignable to type 'import("/opt/app/node_modules/@types/graphql-upload/node_modules/graphql/type/definition").GraphQLOutputType'.
              Type 'GraphQLScalarType' is not assignable to type 'GraphQLOutputType'.
                Type 'GraphQLScalarType' is missing the following properties from type 'GraphQLEnumType': getValues, getValue
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
