### ISSUE TITLE
webpack-env missing path

### ISSUE THREAD

**Issue by Nber1** [DefinitelyTyped/DefinitelyTyped#45927]
I'm using the latest typescript version and due to the addition from **path** to node in 12.12.48 I get this error in webpack-env:

```
node_modules/@types/webpack-env/index.d.ts:349:15 - error TS2430: Interface 'NodeJS.Module' incorrectly extends interface '__WebpackModuleApi.Module'.
  Types of property 'parent' are incompatible.
    Type 'Module | null' is not assignable to type 'NodeModule | null'.
      Property 'path' is missing in type 'Module' but required in type 'NodeModule'.

349     interface Module extends __WebpackModuleApi.Module {}
                  ~~~~~~

  node_modules/@types/node/globals.d.ts:236:5
    236     path: string;
            ~~~~
    'path' is declared here.
```

@use-strict @rhonsby

**Comment by doitadrian** [comment]
This seems to fix the problem :
![image](https://user-images.githubusercontent.com/5121148/86770362-e0d20b80-c050-11ea-98e8-342d8ca94462.png)

I can make a PR if this is indeed a solution.

**Comment by tk-1io** [comment]
Another possible solution which seems to work is to add the new `path` from https://github.com/DefinitelyTyped/DefinitelyTyped/commit/0a10d25cdff9176b7327550ad6ef038cfc2b21ee#diff-3f95a9ff9e45811e8917b45f79f9586aR236
also here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0a10d25cdff9176b7327550ad6ef038cfc2b21ee/types/node/v12/globals.d.ts#L1165

Not sure though whether they just forgot to add `path` there, or if the addition was intentionally just done to the `NodeModules` interface, but not to the `Module` class?
