### ISSUE TITLE
'testing-library__vue' tests are failing for 'getByRole'

### ISSUE THREAD

**Issue by rbuckton** [DefinitelyTyped/DefinitelyTyped#45937]
`testing-library__vue` is broken because `GetByRole` in `@testing-library/dom` is overloaded and the `BoundFunction` type uses a conditional type with `infer` on a function type so it only picks one of the two overloads (which happens to be the wrong one for this case).

This was found while running on-demand DT tests on the TypeScript repo: https://typescript.visualstudio.com/TypeScript/_build/results?buildId=78525&view=logs&j=abaf456e-5a9c-50a3-94a8-5c090880e34b&t=e32d0405-c032-566a-9962-793f4496de08&l=5515

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cimbul

**Comment by cimbul** [comment]
Upstream issue at testing-library/dom-testing-library#680. Should be fixed by testing-library/dom-testing-library#683. I can comment out the test if the failure is causing problems for the overall build status, but the actual fix will have to come from dom-testing-library.
