### ISSUE TITLE
@types/express - RequestHandler not behaving properly for middleware

### ISSUE THREAD

**Issue by owenallenaz** [DefinitelyTyped/DefinitelyTyped#45934]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/express` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov , @MichalLytek, @kacepe, @micksatana, @samijaber, @aereal, @JoseLion 

I am attempting to utilize the express `RequestHandler` for Typescript and it's not behaving the way I would expect.

I run the following code in the [this playground](https://www.typescriptlang.org/play/index.html?ssl=21&ssc=2&pln=1&pc=1#code/PTAEBMHsFMGcDsDkAXUB3SAnA1gKAJYC2ADlqgFSgCGso0oAZppIaAETQAexmcsbAbly4Q6LNlgESZUJRqgAxlnqNmrRFx58AtLGiYAbtF3IqyfAu1LeiAaGGiMOSUvixU16AAkq8cABt9AC5FZQA6ACVoAEcAVzhkHz9AzFAAXkZY+AVzSHhQAApeaIAaUF5YMvguZABKUABvXFAW+wBfXFd3UN4AWV9Yqn90zOzc-KKYkM9ImPj3Morp8KjYUjdoKprl3jCAORqAMSyc-Dz6ptb2hzAoOCRUJzwu1AALXwDgulm4hKTP1IZBgncaFYqLOBbTh1RrNVq4DovUCEAZDEbAsZnCbFELQH7zZAQ2C42ZrPJ6KHIEkHaHHTHnWFXBFAA).

```ts
import * as e from "express";
import * as core  from 'express-serve-static-core'; 

// works
const coreHandler: core.RequestHandler = function (req, res, next) {
    
}
const coreManual = function (req: core.Request, res: core.Response, next: core.NextFunction) {
    
}

// doesn't work
const handler: e.RequestHandler = function (req, res, next) {
    
}
const manual = function (req: e.Request, res: e.Response, next: e.NextFunction) {
    
}
```

When I use the core typings, it works as expected, I am able to get typeahead and completion for the req, res, next function variables. If I use the express typings it does not provide that capability, they all come through as `any`. My assumption was that the `express-serve-static-core` was meant for internal purposes, so the `express` bindings should be correct. I don't fully understand this stuff, but I believe it may be related to the mismatch in number of generic terms on core.RequestHandler and e.RequestHandler.

In the express typings it has:

```ts
interface RequestHandler<P extends core.Params = core.ParamsDictionary, ResBody = any, ReqBody = any, ReqQuery = core.Query> extends core.RequestHandler<P, ResBody, ReqBody, ReqQuery> { }
```

But core.requestHandler generic only accepts 3 params. If I drop the ReqQuery param, it appears to work:

```ts
interface Testing<P extends core.Params = core.ParamsDictionary, ResBody = any, ReqBody = any> extends core.RequestHandler<P, ResBody, ReqBody> { }
```

It works for my purposes, but I don't actually know what the intent of the ReqQuery portion is, so I did not do a PR since it probably has a reason for being there.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
