### ISSUE TITLE
Checkbox, icon style type mismatch

### ISSUE THREAD

**Issue by sureshChenniappan** [DefinitelyTyped/DefinitelyTyped#45952]
Hallo,
I am using the @types/react-native-material-ui package, in that for checkbox component, icon style props its mentioned as type of ViewStyle(https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native-material-ui/index.d.ts#L149) but in react-native-material-ui package (https://github.com/xotahal/react-native-material-ui/blob/master/src/Checkbox/Checkbox.react.js#L108), it needs color which is textStyle props, so @iRoachie, please update this package to be compatible with react-native-material-ui

Thanks a lot!

**Comment by iRoachie** [comment]
Gotcha!
