### ISSUE TITLE
[Mongoose] Cannot create model with required but default'd mutable property

### ISSUE THREAD

**Issue by cyrilgandon** [DefinitelyTyped/DefinitelyTyped#45974]
- [x] I tried using the `@types/mongoose` package and had problems.
 - Authors: @andreialecu

Not sure if it belongs here or on SO, but..
I'm trying to install new Creation typings for mongoose (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44619). Thanks for the huge work BTW on mongoose typings, much appreciation !!
I have a bunch of model with the same pattern, one readonly createdAt, and one required updatedAt, not required for creation, only for update:

```
interface Foo extends mongoose.Document {
    readonly createdAt: Date;
    updatedAt: Date;
}

const FooSchemaDefiniton = {
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now },
};

async function doCreation(){
    const FooModelSchema = mongoose.model<Foo>(`Foo`, {} as any);

    // Property 'updatedAt' is missing in type '{}' but required in type 'Pick<{ _id: any; updatedAt: {}; } & { _id: any; }, "updatedAt">'.ts
    await FooModelSchema.create({ }));
}
```

What solution can I take so TS does not complain, because `updatedAt` is a property handled with the default at creation and should not be required. I obvisouly do not want to make it optional in the model netiher.. And it is not readonly.. What should I do?

**Comment by andreialecu** [comment]
There's an override available via a type parameter to `.create<TOverride>()`. You can use it like this:

```ts
await FooModelSchema.create<Omit<FooSchemaDefiniton, "updatedAt">>({ }));

// or:
type FooCreateDto = Omit<FooSchemaDefiniton, "updatedAt">;
await FooModelSchema.create<FooCreateDto>({ }));
```

**Comment by cyrilgandon** [comment]
Oh, perfect. Since I sometimes need to set the value, I'll use something like:

```
type FooCreateDto = PartialFor< Foo, 'updatedAt'>
```

Thank you !

**Comment by andreialecu** [comment]
You could use `Optional<T, keys>` from https://github.com/piotrwitek/utility-types#optionalt-k for that purpose.

You're welcome.
