### ISSUE TITLE
[styled-components] attrs should not narrow prop types when defaulting them

### ISSUE THREAD

**Issue by ProdigySim** [DefinitelyTyped/DefinitelyTyped#45985]
```ts
declare const MyButton: React.FC<{ name: string }>;

const AttrsButton = styled(MyButton).attrs({
    name: 'foo' as const, 
})``;

const AttrsPropsNarrowCheck: React.FC = () => {
    return (
        <>
            <AttrsButton name="not foo" /> // Error: Type '"not foo"' is not assignable to type '"foo" | undefined'
        </>
    );
};
```

When defaulting a prop using the `attrs()` method, the resulting type gets narrowed, disallowing perfectly valid overrides to the prop.

In my codebase, this is an issue because we use string literals for various pixel sizes & color values for dev & debug convenience. So we may have code like `const ColoredIcon = styled(Icon).attrs({ iconColor: colors.default })`, but want to override the color later in usage.

- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @lavoaster @Jessidhia @JKillian @eps1lon @flavordaaave @wagerfield @Lazyuki @mgoszcz2 @danilofuchs

**Comment by ProdigySim** [comment]
I tried a relatively naiive fix for this:

```diff
diff --git a/types/styled-components/ts3.7/index.d.ts b/types/styled-components/ts3.7/index.d.ts
index 3dd62d65c9..5ffd0157f6 100644
--- a/types/styled-components/ts3.7/index.d.ts
+++ b/types/styled-components/ts3.7/index.d.ts
@@ -229,7 +229,7 @@ export interface ThemedStyledFunction<
         } = {}
     >(
         attrs: Attrs<StyledComponentPropsWithRef<C> & U, NewA, T>
-    ): ThemedStyledFunction<C, T, O & NewA, A | keyof NewA>;
+    ): ThemedStyledFunction<C, T, O & Pick<StyledComponentPropsWithRef<C> & U, keyof NewA>, A | keyof NewA>;
 
     withConfig: <Props extends O = O>(config: StyledConfig<StyledComponentPropsWithRef<C> & Props>) => ThemedStyledFunction<C, T, Props, A>;
 }
```
But I did not realize some of the other use cases of `attrs()` (defining new attributes), which is not handled by this solution.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
