### ISSUE TITLE
@types/lodash _.get has `any` overload defeating the stricter typing

### ISSUE THREAD

**Issue by NullEntity** [DefinitelyTyped/DefinitelyTyped#46012]
Lodash's _.get has an overload accepting any property which defeats the purpose of having the more restrictive type constraints.
```ts
import _ from 'lodash';
const foo = {bar: 0};
// LoDashStatic.get(object: any, path: _.Many<string | number | symbol>, defaultValue?: any): any
_.get(foo, 'doesntexist');
// LoDashStatic.get<{bar: string;}, "bar">(object: {bar: string;}, path: "bar" | ["bar"]): string
_.get(foo, 'bar');
```
I believe it'd be much better behavior if the any overload was removed so trying to access a property that won't exist on the type will error.

Authors: @bczengel @chrootsu @stepancar @aj-r @e-cloud @thorn0 @jtmthf @DomiR @WilliamChelman

**Comment by aj-r** [comment]
get also accepts deep property access using dot notation, e.g. _.get(obj,
'deep.property'). I'm worried that if we remove that overload, it will
break some people.

If you want stricter types then don't use get, use the ?. operator, e.g.
obj?.deep?.property.

**Comment by NullEntity** [comment]
You're right. I don't think there's a nice way to resolve this within the typing.
