### ISSUE TITLE
@types/react-color, it's missing a source in index.d.ts

### ISSUE THREAD

**Issue by linxianxi** [DefinitelyTyped/DefinitelyTyped#46095]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-color` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:   @LKay
                    @markspolakovs
                    @mntdn
@nkgrnkgr
@0815Strohhut
@dnlfrst
@ericktamayo
@alexandercerutti
                   ...

If you do not mention the authors the issue will be ignored.

in index.d.ts
![image](https://user-images.githubusercontent.com/47104575/87503344-86f7c400-c696-11ea-8cdb-63057b5b7966.png)

but i want to use the source, I added this manually
![image](https://user-images.githubusercontent.com/47104575/87503358-9119c280-c696-11ea-976b-d70b653b4c17.png)

in console.log,it has source
![image](https://user-images.githubusercontent.com/47104575/87503379-a2fb6580-c696-11ea-9b0f-e77e6a1efa97.png)

**Comment by ashiishme** [comment]
What about the types for `hsv` & `oldHue` as well? Or any other interface extends the **ColorResult** for these properties?

**Comment by alexandercerutti** [comment]
`ColorResult` is an interface of `@types/react-color` v3.
Sadly, v3 is a stale beta version. It hasn't been updated for years and I don't know if it will never be updated.
It has also diverged, because it has been created before v2 but v2 then was kept being updated.

If you check `v2` typings, [`ColorState`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-color/v2/index.d.ts#L44) has the properties you are talking about.

Since the latest stable version is the 2.18, you should install `@types/react-color@2.17.4`.

**Comment by linxianxi** [comment]
> [`ColorResult`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-color/index.d.ts#L33) is an interface of `@types/react-color` v3.
> Sadly, v3 is a stale beta version. It hasn't been updated for years and I don't know if it will never be updated anymore.
> It has also diverged, because it has been created before v2 but v2 then was kept being updated.
> 
> If you check `v2` typings, [`ColorState`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-color/v2/index.d.ts#L44) has the properties you are talking about.
> 
> Since the latest stable version is the 2.18.1, you should install `@types/react-color@2.17.4` or, at least, `@types/react-color@^2.17.4`, but not `@types/react-color@latest`.

Thanks. I installed it by npm i -D @types/react-color directly.I think most of users are like me.

**Comment by alexandercerutti** [comment]
Yes, there's a lot of mess with the handling of react-color typings. 😔 It has been discussed several times in the PRs.
You are welcome!
