### ISSUE TITLE
[@types/bent] Missing response decoding helpers

### ISSUE THREAD

**Issue by stramel** [DefinitelyTyped/DefinitelyTyped#46135]
@Ovyerus

`bent` defines some decoding helpers, `json`, `text` and `arrayBuffer` on the response. https://github.com/mikeal/bent/blob/edeec60b0625fb974ed4b00045023b8d9df3235f/src/nodejs.js#L74-L94 These seem to be missing in the current type definition

**Comment by Ovyerus** [comment]
Thanks for notifying me about this, will add. 👍
