### ISSUE TITLE
[request] @angular/localize

### ISSUE THREAD

**Issue by sorohan** [DefinitelyTyped/DefinitelyTyped#46160]
[@angular/localize/init](https://github.com/angular/angular/tree/master/packages/localize/init) declares the global `$localize`.

The types are provided by angular, but they cannot be used when publishing a library making use of `$localize`. See [this comment](https://github.com/ngx-translate/core/issues/495#issuecomment-655335648). I think the best solution is to have them typed here.

I've already confirmed that this will resolve the issue with using `$localize` in angular libraries. I'll make a PR for this as well.

**Comment by peterblazejewicz** [comment]
> I've already confirmed that this will resolve the issue with using `$localize` in angular libraries. I'll make a PR for this as well.

AS asked on the PR, can you explain how and what problem it would solve?

**Comment by sorohan** [comment]
Thanks for your help.

Angular provides a global template string function `$localize`, which is [added to the global by including `@angular/localize/init`](https://angular.io/guide/migration-localize) to an application's polyfills.

This does 2 things, it declares the `$localize` type so that typescript knows about it, but it is also effectful, and adds `$localize` to the globals.

That works for applications but in order to compile and publish a *library* which makes use of `$localize` you need to somehow declare the `$localize` global for typescript.

My understanding is that the best way for an NPM package to declare a global that's expected to be there without the need to `import` that package is to use DT. There's a good chance I'm wrong about that, so any advice on this would be appreciated. I've asked for advice from the angular team [here](https://github.com/angular/angular/issues/36757#issuecomment-660318825) too.

**Comment by peterblazejewicz** [comment]
@sorohan kudos!
