### ISSUE TITLE
chromecast-caf-receiver - Add type `player` to the cast namespce

### ISSUE THREAD

**Issue by WafaZaidan** [DefinitelyTyped/DefinitelyTyped#46169]
**Affected Repo**
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/chromecast-caf-receiver

**Version**
5.0.7

**Authors**
@brandonrisell
@craigrbruce
@Serabe

**Issue**
Currently the player instance exists on `cast` in the debugger, however, it doesn't exist as a type in the chromecast-caf-receiver
<img width="913" alt="Screenshot 2020-07-18 at 17 41 28" src="https://user-images.githubusercontent.com/35741448/87857346-f3d0bf80-c91d-11ea-996c-6c09e504e447.png">
So for example, if I need to control the log level of the player, I will have to cast the `cast` variable to `any` in order to achieve that
<img width="838" alt="Screenshot 2020-07-18 at 17 42 47" src="https://user-images.githubusercontent.com/35741448/87857379-1fec4080-c91e-11ea-8320-225585a796f8.png">

 
**Solution**
Provide type `player` on `cast` along with the `LoggerLevel` enum and the `setLoggerLevel` function which can be seen in the debugger of the receiver.
<img width="1058" alt="Screenshot 2020-07-18 at 16 19 55" src="https://user-images.githubusercontent.com/35741448/87857400-45794a00-c91e-11ea-987f-224de70fe11c.png">

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
