### ISSUE TITLE
[@types/mongoose] query types should check if key exists in class

### ISSUE THREAD

**Issue by kkoomen** [DefinitelyTyped/DefinitelyTyped#46186]
**Do you want to request a *feature* or report a *bug*?**

I consider this a **bug**.

**What is the current behavior?**

I have a users service class like so (using NestJS):

```ts
import { UpdateQuery, FilterQuery } from 'mongoose';
import { User } from './schemas/users.schema.ts';

class UsersService {
  constructor(@InjectModel(User.name) private readonly usersModel: Model<User>) {}

  async updateOne(
    conditions: FilterQuery<User>,
    fields: UpdateQuery<User>,
    options: Record<string, unknown> = {},
  ): Promise<T> {
    try {
      const result = await this.usersModel.findOneAndUpdate(
        conditions,
        fields,
        { new: true, ...options },
      );
      return result;
    } catch (err) {
      console.log(err);
    }
}
```

The `User` schema can look like something like this:

```ts
import { Document } from 'mongoose';

class User extends Document {
  username: string;
}
```

When I have my controller with this:

```ts
class MyController {
  constructor(private readonly usersService: UsersService) {}

  @Get()
  async update(@Body() body: UpdateUserDTO): Promise<User> {
    // This expression below should cause an error that 'test' does not exists on `User` which doesn't happen.
    return this.usersService.updateOne({ test: true });
  }
}
```

This can be fixed for some part by modifying the `updateOne()` in the `UsersService` like so:

```ts
 async updateOne(
    conditions: Partial<Record<keyof User, any>>,
    fields: Partial<Record<keyof User, any>>,
    options: Record<string, unknown> = {},
  ): Promise<T> {
    try {
      const result = await this.usersModel.findOneAndUpdate(
        conditions as FilterQuery<User>,
        fields as UpdateQuery<User>,
        { new: true, ...options },
      );
      return result;
    } catch (err) {
      console.log(err);
    }
  }
```

but the custom approach above doesn't work for fields named like `$addToSet` or keys that are supposed to select nested fields such as: `updateOne({...}, { 'myObject.nestedKey': true })`. I understand *why* obviously, but maybe it's possible to update these types to be more stricter if possible.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

The `FilterQuery`, `UpdateQuery`, `CreateQuery` and `DeleteQuery` (and other similar types) should all check whether the key is keyof `T`, in my case `T` is `User`.

**IF** there is a solution that can be done by the users themselves I'd love to know how, but the only option I see without having to redefine all the Mongoose query types such as `FilterQuery` is that Mongoose itself should check this which I would expect.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose: 5.9.14, the rest is irrelevant.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
