### ISSUE TITLE
[canvaskit-wasm] MakeCanvas() and getContext() missing in definition

### ISSUE THREAD

**Issue by mochaaP** [DefinitelyTyped/DefinitelyTyped#46194]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/canvaskit-wasm` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ashlanderr 

If you do not mention the authors the issue will be ignored.

The definition file is outdated.

**Comment by ashlanderr** [comment]
@mochaaP Hello! I've added definitions you asked. The package still contains some non-typed methods. I don't have much time right now to support them. If you interested, feel free to make a PR and I will review it.
