### ISSUE TITLE
[@types/react] Missing Partial<T> in useImperativeHandle?

### ISSUE THREAD

**Issue by alinnert** [DefinitelyTyped/DefinitelyTyped#46266]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon @zieka @dancerphil @dimitropoulos @disjukr @vhfmag @hellatan

---

I think there's a mistake in the type of `useImperativeHandle`. The React docs provide the following usage example:

~~~ js
useImperativeHandle(ref, () => ({
  focus: () => {
    inputRef.current.focus();
  }
}));
~~~

If I put this in my code I receive the following error:

~~~
Type '{ focus: () => void; }' is missing the following properties from type 'HTMLDivElement': align, addEventListener, removeEventListener, accessKey, and 233 more.ts(2740)
~~~

This means the type of `useImperativeHandler` expects me to implement an entire HTMLDivElement with all of its 200+ properties. I can avoid the error by doing this:

~~~ js
useImperativeHandle(ref, () => ({
  ...HTMLDivElement.prototype,
  focus: () => {
    inputRef.current.focus();
  }
}));
~~~

But this doesn't look right. Shouldn't the callback be expected to return a `Partial` of `typeof ref` (+ custom properties) instead?

So, shouldn't the type instead of...

~~~ ts
function useImperativeHandle<T, R extends T>(ref: Ref<T>|undefined, init: () => R, deps?: DependencyList): void;
~~~

...look like:

~~~ ts
function useImperativeHandle<T, R extends Partial<T>>(ref: Ref<T>|undefined, init: () => R, deps?: DependencyList): void;
//                                        ----------
~~~

**Comment by ferdaber** [comment]
What are you using for the type of your `ref`? Your callback needs to implement your `ref`. It sounds like if your `ref` is pointing to a div element, then you may not have used it correctly. Refs that dereference to host elements should be managed by React, other refs that you manage should be separate props that you pass in (which itself can be a ref object).

**Comment by ferdaber** [comment]
Example correct usage based on a button wrapper:
```tsx
const ButtonWrapper = forwardRef((
  props: JSX.IntrinsicElements['button'],
  ref: React.Ref<{ focus(): void }>
) => {
  const buttonRef = useRef<HTMLButtonElement>(null);
  useImperativeHandle(ref, () => ({ focus() { buttonRef.current?.focus(); } }));
  return <button ref={buttonRef}>Hello!</button>
});
```

Notice that there are separate refs, one that you internally manage, and one that React manages.

**Comment by alinnert** [comment]
Oh, you're right. I haven't realized there are two refs. Thank you for pointing that out.
