### ISSUE TITLE
@types/uuid needs updating to latest release

### ISSUE THREAD

**Issue by OneHoopyFrood** [DefinitelyTyped/DefinitelyTyped#46277]
Looks like the types need to be updated! [I see you guys (the lib authors) are maintaining this](https://github.com/uuidjs/uuid/issues/470#issuecomment-647448054), thank you! 

Specifically, the 8.2 update introduced a few new functions:`parse`, `stringify`, `validate` and `version`; and one new property: `NIL`.

@felipeochoa, @cjbarth, @LinusU, @ctavan

**Comment by ctavan** [comment]
There was a mistake in the readme of UUID where it stated that these new functions were introduced in `8.2.0` which is not the case. The new functions will be released as `8.3.0` which is not out yet. I'll take care of providing types once we release the actual library.

**Comment by OneHoopyFrood** [comment]
Ah! Good to know!
