### ISSUE TITLE
[@types/i18n] last update of @types/express-serve-static-core break the types

### ISSUE THREAD

**Issue by thib3113** [DefinitelyTyped/DefinitelyTyped#46281]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/i18n` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SomaticIT @FindQ

If you do not mention the authors the issue will be ignored.

Last update of @types/express-serve-static-core break your types .

```
./node_modules/@types/serve-static/node_modules/@types/express-serve-static-core/index.d.ts:505:18 - error TS2430: Interface 'Response<ResBody>' incorrectly extends interface 'Response'.
  Types of property 'locals' are incompatible.
    Type 'Record<string, any>' is missing the following properties from type 'i18nAPI': locale, __, __n, __mf, and 5 more.

505 export interface Response<ResBody = any> extends http.ServerResponse, Express.Response {
```

**Comment by niekvb** [comment]
This issue should be resolved as soon as [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46328) merges and packages are updated.
