### ISSUE TITLE
[@types/jest] 26.0.5: esModule field typing error

### ISSUE THREAD

**Issue by beInDev** [DefinitelyTyped/DefinitelyTyped#46283]
Hello!

I have an issue with the latest `@types/jest` version (**26.0.5**)
The problem occurs also with latest typescript version (**3.9.7**),  but I'm currently using 3.8.3

I'm attempting to mock a module (partially) and I get an error in tsc.

The mock
```
jest.mock('multer', () => {
  const fields = jest.fn()
  const defaultFunction: any = jest.fn()
  const memoryStorage = {
    isMemoryStorage: true,
  }
  defaultFunction.memoryStorage = jest.fn(() => memoryStorage)
  return {
    MulterError: class extends Error {
      public code?: string
      constructor(codeParam: string) {
        super()
        this.code = codeParam
      }
    },
    __esModule: true,
    default: defaultFunction,
    fields,
    memoryStorage: () => memoryStorage,
  }
})
```

The error
`Type '{ MulterError: typeof MulterError; __esModule: boolean; default: any; fields: jest.Mock<any, any>; memoryStorage: () => { isMemoryStorage: boolean; }; }' is not assignable to type '{ __esModule: true; }'`

Only quickfix I found so far
`__esModule: true as true`

This happened following latest update on this part
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46072#pullrequestreview-448772973
I tried understanding what the issue was in my code by reading the explanations but can't pinpoint it (also it seems like a breaking change to me since it was working before? 🤔)

 cc. @devanshj any help would be kindly appreciated 🙏

**Comment by devanshj** [comment]
Hey thanks for reporting, your code is fine the problem is `true` is inferred as `boolean` instead of `true`. We just need to type `mock` in a way that make the inference work. I think I know a way let me check if it works (afk) I'll get back in some time. In worst case we would revert it.

**Comment by beInDev** [comment]
@devanshj Thanks for the quick answer, I'll hold on the previous version until then 🙂

**Comment by devanshj** [comment]
[Reproduction](https://www.staging-typescript.org/play?jsx=0#code/C4TwDgpgBAsg9gYwNbwCYFcA2EBiBDBYOAJxAB4AVAPigF4oAKASjpoqggA9gIA7VAM5QA3lFQQAZnizAAXFHS8kvOAHdeUAL5QA-FHYAyEVAD6JiALRYI84MXTRt8igG4AsAChP4hJjzFoBDheAWAoAFtEJHlKKgZPKESIuAxseVDiAEteAHMAGgSkqUISEHl4ZCtsfBLSWM8WWhoANzhM1E9PSOQGACIJODhevMZGmmFCxIDgdGINCY8kpbFJaUw5KH7B4cnlswsqmyg7B13NT00mIA), [Fix](https://www.staging-typescript.org/play?jsx=0#code/C4TwDgpgBAsg9gYwNbwCYFcA2EBiBDBYOAJxAB4AVAPigF4oAKASjpoqggA9gIA7VAM5QA3lFQQAZnizAAXFHS8kvOAHdeUAL5QA-FHYAyEVAD6JiALRYI84MXTRt8igG4AsAChP4hJjzFoBDheAWAoAFtEJHlKABooACUObj5BWCirbHxCEnJqKgZPKGKIuAxseVDiAEteAHNYopKpHNJ5BM8WWhoANzhq1E9PSOQGACIJODgx+OZWESbigOB0Yg1hRZLi8SkZeQmpmc2tswtMmyg7B03NT00mIA), [Better Fix](https://www.staging-typescript.org/play?jsx=0#code/C4TwDgpgBAsg9gYwNbwCYFcA2EBiBDBYOAJxAB4AVAPigF4oAKASjpoqggA9gIA7VAM5QA3lFQQAZnizAAXFHS8kvOAHdeUAL5QA-FHYAyEVAD6JiALRYI84MXTRt8igG4AsAChP4hJjzFoBDheAWAoAFtEJHlKABooACUObj5BWCirbHxCEnJqOnTkTNwCIlJKKioGTyhaiLgMbHlQ4gBLXgBzWJq6qRzSeQTPFloaADc4VtRPT0jkBgAiCTg4BfjmVhEe2oDgdGINYW262vEpGXkllbXjk7MLYtt7CGPNT00mIA). I'll send a PR soon.

**Comment by devanshj** [comment]
[Yay, Finally!](https://www.staging-typescript.org/play?jsx=0#code/CYUwxgNghgTiAEYD2A7AzgF3gWyWA1gFzwA8AKvCAB4YgrBrwDe8oAZlAK4QbGcr4USAO4oANPAD6kkGgCySYNxDEMMTggC+8AD7NWIDtwwB+YihAA3EDHiaAfAAoAsACh4HnIuXFMMAJYoAOZibp7wHGAYSDAAnsSOAJTwALz28GRuyWnwlkj+wG5FrgD0JfBoABZI3MDwAA5QaGhuuASOAERsSEgdEkmp6UxhnnAYnDAozCPhHuxcPMRdPX0zs9KyCkoQKvBqGmuabpqJxWUV1bURUP4QrXj4nd29-dlDa2MTU8Pus3OGC148GWLzW4Q28m8O2IHAgaBAh2Op1cZ3KVRqEDqHFu93aIL68AGOR+4U+k2mvz+82MS2eHURrhOQA) Sending a PR

**Comment by beInDev** [comment]
@devanshj Nice that was fast! Thanks for the work 💪

**Comment by devanshj** [comment]
Unfortunately this is also not apt because a mock factory can also return a function, a string, etc etc there's a lot of complexity so I'm reverting before we can find a good fix.
