### ISSUE TITLE
[@types/serverless] Missing Package field on Serverless Definition

### ISSUE THREAD

**Issue by KingDarBoja** [DefinitelyTyped/DefinitelyTyped#46343]
- [x] I tried using the `@types/serverless` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:
    - @hassankhan 
    - @JonathanWilbur 
    - @a-pavlenko 
    - @fredericbarthelet 
    - @bryan-hunter 
    - @ThomasAribart 

Hi DefinitelyTyped Team,

Was looking at the TS Definition files for `@types/serverless` and noticed the `package` field being missing according to the official [serverless docs](https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/).

The type `Package` is already defined, however, the [Serverless class](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/serverless/index.d.ts#L56) do not have the `package?: Package` declaration (yes, it is optional).

Something like this:

```ts
declare class Serverless {
    constructor(config?: {});

    init(): Promise<any>;
    run(): Promise<any>;

    setProvider(name: string, provider: AwsProvider): null;
    getProvider(name: string): AwsProvider;

    getVersion(): string;

    cli: {
        log(message: string): null;
    };

    package?: Serverless.Package;  // <-- Missing!
    providers: {};
    utils: Utils;
    variables: {};
    yamlParser: YamlParser;
    pluginManager: PluginManager;

    config: Serverless.Config;
    serverlessDirPath: string;

    service: Service;
    version: string;
}
```

Also, the `Package` definition should add `excludeDevDependencies?: boolean` too to match the official docs.

Cheers!

**Comment by KingDarBoja** [comment]
Actually, I just noticed until now that the linked docs are for **AWS** provider, so not sure how this would work for all of those providers 🤔

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
