### ISSUE TITLE
importing React/experimental items issue TypeErrors and compile errors

### ISSUE THREAD

**Issue by Choongkyu** [DefinitelyTyped/DefinitelyTyped#46353]
I've been trying to add typescript [to this project](https://github.com/relayjs/relay-examples/tree/master/issue-tracker) and ran into the following issues:

this line `const { useCallback, unstable_useTransition, Suspense } = React;` leads to me seeing this error:
`TypeError: unstable_useTransition is not a function`

I've also tried logging unstable_useTransition and it shows as undefined although logging useCallback is fine.  

I've tried the advice of adding `"react/experimental"` to my types array in tsconfig, since including this line
`import {} from 'react/experimental` leads to this error:

`Module not found: Can't resolve 'react/experimental' in '/Users/user/code/relay-examples/issue-tracker/src/routing'`
 

the package.json is as follows:
```
{
  "name": "issue-tracker",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "history": "^4.10.1",
    "husky": "^3.0.9",
    "lint-staged": "^9.4.2",
    "react": "0.0.0-experimental-f42431abe",
    "react-dom": "0.0.0-experimental-f42431abe",
    "react-markdown": "^4.2.2",
    "react-relay": "0.0.0-experimental-8cc94ddc",
    "react-router": "^5.1.2",
    "react-router-config": "^5.1.1",
    "react-scripts": "3.2.0"
  },
  "scripts": {
    "start": "yarn run relay; concurrently --kill-others --names \"react-scripts,relay\" \"react-scripts start\" \"yarn run relay --watch\"",
    "build": "yarn run relay && react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "tsc": "tsc",
    "update-schema": "get-graphql-schema -h \"Authorization=bearer $REACT_APP_GITHUB_AUTH_TOKEN\" https://api.github.com/graphql > schema/schema.graphql",
    "relay": "yarn run relay-compiler --schema schema/schema.graphql --src ./src/ $@"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/node": "^14.0.26",
    "@types/react": "^16.9.43",
    "@types/react-dom": "^16.9.8",
    "@types/react-relay": "^7.0.8",
    "@types/react-router-config": "^5.0.1",
    "babel-plugin-relay": "^9.0.0",
    "concurrently": "^5.0.0",
    "eslint-plugin-prettier": "^3.1.1",
    "get-graphql-schema": "^2.1.2",
    "graphql": "^14.5.8",
    "prettier": "^1.18.2",
    "relay-compiler": "^9.0.0",
    "typescript": "^3.9.7"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "src/**/*.{js,jsx,json,css,md}": [
      "prettier --write",
      "git add"
    ]
  }
}

```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
