### ISSUE TITLE
[jasmine] Update @types/jasmine to reflect API changes in jasmine-core 3.6.0

### ISSUE THREAD

**Issue by Maximaximum** [DefinitelyTyped/DefinitelyTyped#46368]
At least, the typing for the new toHaveBeenCalledOnceWith matcher is missing

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@borisyankov @theodorejb @davidparsson @gmoothart @lukas-zech-software @Engineer2B @cyungmann @Roaders @devoto13 @fdim @pe8ter @kolodny @stephenfarrar @zvirja @djungowski @chivesrs

**Comment by chivesrs** [comment]
Are you willing to create a PR to add in these typings yourself? You can @ me in the PR and I can review.

**Comment by Maximaximum** [comment]
@chivesrs I could add the typing for the `toHaveBeenCalledOnceWith` matcher, but as far as I see, there are many more API changes in v 3.6.0, which would take me too much time to reflect, since I'm not really aware of how jasmine works. And probably all the changes should be applied as a single PR?

**Comment by selangley-wa** [comment]
Here are the 3.6.0 release notes in case someone is feeling ambitious:
[https://github.com/jasmine/jasmine/blob/main/release_notes/3.6.0.md](https://github.com/jasmine/jasmine/blob/main/release_notes/3.6.0.md)

**Comment by chivesrs** [comment]
Just add in the matcher you need for now? It's better than not having it. Typings are generally a user driven project.
