### ISSUE TITLE
[Request] Scratch Typings

### ISSUE THREAD

**Issue by Richienb** [DefinitelyTyped/DefinitelyTyped#46365]
Since the Scratch team [doesn't use Typescript](https://github.com/LLK/scratch-vm/issues/2533#issuecomment-664193818), can we put them here under @types/scratch or similar? Would it conflict with the unrelated `scratch` package on npm?

// @peterblazejewicz

**Comment by Richienb** [comment]
@peterblazejewicz Ping!

**Comment by peterblazejewicz** [comment]
@Richienb 
There is an organization on NPM that manages Scratch content:
https://www.npmjs.com/~scratch
They have excellent inline typings, hence probably to simplify devx decied to stay with JS only approach, e.g:
https://github.com/LLK/scratch-vm/blob/develop/src/extension-support/define-messages.js
https://github.com/LLK/scratch-vm/blob/develop/src/extension-support/extension-manager.js
etc.
They are using CommonJS modules, nothing non-standard, so in your case, AFAIK `@types/scratch-vm` is the package name and it could have only couple of export implemented required for extendsions, so `scratch-vm/extension-metadata`.
Here is similar approach (JS files, with inline typings), taken by ESLint:
https://github.com/eslint/eslint/tree/master/lib

**Comment by Richienb** [comment]
@peterblazejewicz That library contains the logic to run the Scratch VM. However, I want to add typings for the **environment** Scratch extensions run in. In the environment, the `Scratch` namespace is added as a global.

**Comment by Richienb** [comment]
// @peterblazejewicz

**Comment by peterblazejewicz** [comment]
Would be best to ask folks at LLK/Scratch about the suggested namespace they could eventually adopt in future. '@types/scratch' wont' work IMO, there is a legit package on NPM. I'm not accustomed on how to approach the problem with the `scratch` name, look here for advices:
https://docs.npmjs.com/using-npm/disputes.html
I think LLK folks are the best ones to ask though, why one canot stick to convention they've alreayd using `sratch-smth` or the newest one `@scratch/smth`: https://www.npmjs.com/package/@scratch/paper
With their approval maintainers here would probably adapt to whatever the name of  the @types/...  is to be used.

**Comment by Richienb** [comment]
@peterblazejewicz The Scratch team doesn't use TypeScript and therefore don't have an opinion here. If I get hold of the `scratch` package and turn it into a placeholder, can we then use `@types/scratch`? If not, can we compromise by using `scratch-env` (an unclaimed package name) instead?

**Comment by Richienb** [comment]
// @peterblazejewicz

**Comment by Richienb** [comment]
// @peterblazejewicz

**Comment by Richienb** [comment]
// @peterblazejewicz

**Comment by Richienb** [comment]
// @peterblazejewicz

**Comment by peterblazejewicz** [comment]
@Richienb i'm a regular mate, don't have really a final word on anything here.
My 2 cents about your question are just 2cents:
- it's always a good manner to ask other folks for opinion (LLK) in case one would like to use package with same name. 
- the name is up to you anyway, just remember it will be reviewed by maintainer for new package
- the DT package does not need to be on the NPM at all. It can be 'github' only, with proper line in the DT header and in 'tslint.json'
- your DT package could ship its own custom README.md to describe what's the purpose and why this name, etc
Make a PR
