### ISSUE TITLE
[@types/theme-ui] Type 'string' is not assignable to type 'SystemStyleObject' using gridGap inside sx prop

### ISSUE THREAD

**Issue by boi87** [DefinitelyTyped/DefinitelyTyped#46378]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

@erikdstock  @ifiokjr  @sbardian  @pomber  @wKovacs64  @prateekkathal 

Hi guys!
Hi! I've encountered a type error while trying to compose a grid, in the specific using the gridGap property.

tsx file:

```
{products.map((m, i) => (
<div
            key={i}
            sx={{
              display: "grid",
              gridTemplateColumns: "15% 2px auto 10% 2px 10%",
              my: [1],
             gridGap: "20px"
            }}
          >
{.....}
</div>
```

The error says: **Type 'string' is not assignable to type 'SystemStyleObject'**.
Once removed the gridGap the code compiles correctly. 

Full ERROR:
```
TypeScript error TS2322
Type 'string' is not assignable to type 'SystemStyleObject'.  TS2322

    27 |             key={i}
    28 |             sx={{
  > 29 |               display: "grid",
       |               ^
    30 |               gridTemplateColumns: "15% 2px auto 10% 2px 10%",
    31 |               my: [1],
    32 |               gridGap: "20px"
    33 |             }}
```

As a workaround, I just added a an inline `style` just for the grid gap.

Thanks for the help guys!
Mike

**Comment by wKovacs64** [comment]
Hey @boi87, not able to test this right now but try `gap` instead of `gridGap`. Does that work?

**Comment by boi87** [comment]
Amazing man, it does work indeed! Thanks a lot!!
