### ISSUE TITLE
[@types/better-sqlite3] Types are out of date, Integer package no longer needed thanks to BigInts.

### ISSUE THREAD

**Issue by etylermoss** [DefinitelyTyped/DefinitelyTyped#46381]
- [X] I tried using the `@types/better-sqlite3` package and had problems.
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Morfent @matrumz @sant123 @loghorn @andykais @mrkstwrt

With https://github.com/JoshuaWise/better-sqlite3/commit/758665a3db2df0e4b94af795df2f5dfc8e78f12d (v7.0.0 and above), the Integer dependency was removed, and replaced with natively supported BigInts.

**Comment by sant123** [comment]
Pull request is really welcome :)

**Comment by andykais** [comment]
I wouldnt mind putting up a pr, but first @etylermoss could you describe your error? I just created a sample repo with the latest packages and had no typescript compilation issues:
```json
{
  "dependencies": {
    "@types/better-sqlite3": "^5.4.0",
    "better-sqlite3": "^7.1.0",
    "typescript": "^3.9.7"
  }
}
```

```ts
import * as BetterSqlite from 'better-sqlite3'

const db = new BetterSqlite('some.db')

db.prepare("SELECT * FROM users WHERE id=?").get(BigInt('1152735103331642317'));
db.prepare("INSERT INTO users (id) VALUES (?)").run(BigInt('1152735103331642317'));
```

**Comment by rulatir** [comment]
```typescript
import BetterSqlite from 'better-sqlite3';

function openDb(filename: string) : BetterSqlite
{
    let db : BetterSqlite;
    db = new BetterSqlite(filename);
    return db;
}
```

```
src/db.ts:3:37 - error TS2709: Cannot use namespace 'BetterSqlite' as a type.

3 function openDb(filename: string) : BetterSqlite
                                      ~~~~~~~~~~~~

src/db.ts:5:14 - error TS2709: Cannot use namespace 'BetterSqlite' as a type.

5     let db : BetterSqlite;
               ~~~~~~~~~~~~
```

**Comment by mrkstwrt** [comment]
Shouldn't you be using `Database` interface over the `BetterSqlite` namespace there?

**Comment by rulatir** [comment]
In the code above, I could as well use `Foo`. This is a default import.

**Comment by rulatir** [comment]
OK, this is a [separate issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/52163)
