### ISSUE TITLE
[@types/joi] Outdated types

### ISSUE THREAD

**Issue by gurisko** [DefinitelyTyped/DefinitelyTyped#46418]
Since `@hapi/joi` was deprecated and we are returning back to `joi`, we should copy over types from `@types/hapi__joi` into `@types/joi`.

Authors: @notchairmk @lenovouser @hueniverse

**Comment by hueniverse** [comment]
Don't. I am going to copy them over to the package itself as a starting point for future types support. I think starting with what everyone is using anyway is the way to go. If someone wants to open a PR on joi with the matching v17 types, that would speed things up.

**Comment by gurisko** [comment]
@hueniverse Thank you for letting us know about the future plan of the repo. It would be nice if this gets into `joi` as soon as possible if you don't want to add it into `@types/joi`. I am going to close this one.
