### ISSUE TITLE
Types of property 'key' are incompatible. All animated components props are wrapper with `WithAnimatedValue`

### ISSUE THREAD

**Issue by desfero** [DefinitelyTyped/DefinitelyTyped#46426]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-native` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alloy @huhuanming @iRoachie 

If you do not mention the authors the issue will be ignored.

At the moment `withAnimatedValue` adds `Value | AnimatedInterpolation` to all props of `Animated` components. On top of that, it's also extending interface which means primitive types are not handled properly:
```
 type Test = number | string extends WithAnimatedValue<number | string> ? true : false // is false
```

Given that it causes some issues for code like:

```
type Props = { type: "brand" } & React.ComponentPropsWithoutRef<typeof Animated.Text>;

const TextWrapper: React.FunctionComponent<Props> = ({ brand, ...props  })=> <Animated.Text {...props} />
```

```
  Types of property 'key' are incompatible.         
      Type 'WithAnimatedValue<string | number | undefined> | undefined' is not assignable to type 'string | number | undefined'.           **Type 'WithAnimatedValue<string | number | undefined>' is not assignable to type 'string | number | undefined'**.             Type 'WithAnimatedValue<string | number | undefined>' is not assignable to type 'number'.``
```

We should refactor `WithAnimatedValue` to be only applied to props that really can handle `Value | AniimateInterpolation` type.

Below is the base example that will make it work properly but that it still needs some polishing and reviewing whether there is any kind of animated props that can also handle `Value` except `style` prop.  
```
    export type WithAnimatedValue<T> = StyleProp<T extends StyleProp<infer R> ? (R extends object
                ? { [K in keyof R]?: WithAnimatedValue<R[K]> }
                : R extends (infer P)[]
                ? WithAnimatedValue<P>[]
                : R | Value | AnimatedInterpolation) : never>

    export interface AnimatedComponent<T extends React.ComponentType<any>>
        extends React.FC<Omit<ComponentProps<T>, "style"> & { style?: WithAnimatedValue<ComponentProps<T>["style"]> }> {}
````

**Comment by alloy** [comment]
Thanks @desfero; would you mind turning this into a PR that also has a failing type test to demonstrate the issue clearly?

**Comment by desfero** [comment]
@alloy sure. Will do a PR tomorrow
