### ISSUE TITLE
[@types/google.script.client-side] Parameter type too strict

### ISSUE THREAD

**Issue by marekdedic** [DefinitelyTyped/DefinitelyTyped#46455]
Hi,
thanks for the typings, I tried to used them, but stumbled upon this issue... The `Parameter` type is too strict I think.

I tried passing as a parameter an object of type `Array<{id: string, value: string}>`. Firstly this failed altogether because it's an array, so I changed the definition from
```ts
type Parameter = number | boolean | string | { [index: number]: Parameter } | { [key: string]: Parameter } | null | undefined;
```
to

```ts
type Parameter = number | boolean | string | { [index: number]: Parameter } | { [key: string]: Parameter } | Array<Parameter> | null | undefined;
```
However, now it fails because my type `{id: string, value: string}` has no index signature... I tried to solve this by replacing the 2 object signatures with `Partial`s, but that doesn't work unfortunately...

A way to solve this would be to replace it with 
```ts
type Parameter = number | boolean | string | object | Array<Parameter> | null | undefined;
```
but that seems too loose :( Any ideas on how to do this correctly?

Thanks

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @clomie

If you do not mention the authors the issue will be ignored.

**Comment by clomie** [comment]
Hi,
The type `Array<{ id: string; value: string }>` can be passed as parameter. Actually below code works fine.

```
const array: Array<{ id: string; value: string }> = [];
google.script.run.foo(array);

// This is same as above.
type Foo = { id: string; value: string; };
const array: Array<Foo> = [];
google.script.run.foo(array);
```

Probably you defined element type of array as interface.
```
interface Foo {
  id: string;
  value: string;
}
```

Then it won't work. In that case element of `Array<Foo>` might have other properties that are inconsistent with `Parameter` type as follows for example.

```
class FooClass implements Foo {
  id = 'xxxxx';
  value = 'yyyyy';
  func() { console.log('foo'); }     // inconsistent with the Parameter type
}
const array: Array<Foo> = [new FooClass()];
google.script.run.foo(array);
```

Hopefully this helps you.

Thanks.

**Comment by marekdedic** [comment]
Oooh, you're right :slightly_smiling_face: 

Thanks :+1:
