### ISSUE TITLE
[@types/qrcode] toBuffer method is missing 

### ISSUE THREAD

**Issue by shwao** [DefinitelyTyped/DefinitelyTyped#46450]
The `toBuffer` method defined here:
https://github.com/soldair/node-qrcode/blob/f829dd296a5aadca7cf8657a0f1e4e86f236a6a7/lib/server.js#L105:L109

Is missing from the qrcode types. 

@plantain-00 , @mnahkies , @Marchelune

**Comment by plantain-00** [comment]
You can create a PR to fix this.
