### ISSUE TITLE
Removing a package's types if another package depends on them

### ISSUE THREAD

**Issue by EvanHahn** [DefinitelyTyped/DefinitelyTyped#46511]
I am the maintainer of `helmet`. I just released `helmet@4` which bundles type definitions, so I tried removing them from DefinitelyTyped (with `npm run not-needed`).

However, this breaks `koa-helmet`, which depends on `helmet@3`'s types.

How can I remove `helmet@4`'s types from DefinitelyTyped without breaking `koa-helmet`?

**Comment by peterblazejewicz** [comment]
The helmet was not versioned here properly via major.minor tagging IMO.
Let's say we could apply a versioning adding 3.23 as the current (so it can be relased under new version to NPM).
The probably we can remove 'no longer needed' v4.0 by adding 'as of' version 4.0.0 deprecation:
https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

/cc @sandersn

**Comment by EvanHahn** [comment]
To make sure I understand: it sounds like the first step is to properly version Helmet v3 in DefiniteyTyped. Is that right?

**Comment by sandersn** [comment]
I'm not sure the incorrect versioning is actually an obstacle here. The real problem is making sure that `@types/koa-helmet` still works after `@types/helmet` is deprecated. There are two ways to do this:

1. Update `@types/koa-helmet` to depend on `helmet@4`. Then remove `@types/helmet`. This is the method I recommend.
2a. Pin `@types/koa-helmet` to depend on `@types/helmet@0.0.47`. Then remove `@types/helmet`.
2b. Don't delete `@types/helmet`. Just leave it -- the compiler will ignore it when `helmet@4` and above are also installed. This is the easiest method, but tempts people to keep contributing here when they should be contributing to helmet directly.

For (1), you'll have to add `helmet` to https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/definitions-parser/allowedPackageJsonDependencies.txt.
For (2a), you'll have to add `@types/helmet` to the same list.

Method (2b) actually makes sense when the old version of a package is still popular and needs its types to be updated. But I don't think that applies to helmet.

**Comment by sandersn** [comment]
I just tested an upgrade of `@types/koa-helmet` to `helmet@4` and didn't see any compile errors in index.d.ts or the tests. I think that's the best approach.

The package.json template for DT is pretty simple -- I just copied the one from types/aframe/package.json.

**Comment by peterblazejewicz** [comment]
I'm not sure if #1 can work, the native koa-helmet depends on `helmet@3`:
https://github.com/venables/koa-helmet/blob/master/package.json#L29
what's the scenario with.
@EvanHahn
I"ll add `helmet` to allows list, will work anyway

**Comment by EvanHahn** [comment]
Sounds good! I'll keep an eye on https://github.com/microsoft/DefinitelyTyped-tools/pull/76.

**Comment by sandersn** [comment]
If the types are similar, I would still probably update `@types/koa-helmet` with a note in the source. If helmet@5 changes radically then we can pin its dependency to `helmet@4`.

**Comment by EvanHahn** [comment]
It looks like https://github.com/microsoft/DefinitelyTyped-tools/pull/76 has been merged but not deployed, so I don't think I can remove `helmet` from this repo yet. Maybe that's wrong!

@sandersn How would you update `@types/koa-helmet`? What would you change? If relevant, `helmet@4`'s types are fairly different from `helmet@3`.

I realize I don't know much about how DefinitelyTyped operates...apologies.

**Comment by sandersn** [comment]
Yeah, there was a deployment problem so I had to manually restart deployment.

The way I would update @types/koa-helmet is just to add a package.json with a dependency on `helmet@4`, then see what breaks. When I did the upgrade, *nothing* broke, which indicates either that `@types/koa-helmet` is missing tests, or that it doesn't use helmet very deeply.

If the types for helmet 3 and 4 are quite different, and koa-helmet is mostly just passing them through, then upgrading it to 4 could be very wrong. To find out if that's the case, look to see how koa-helmet is using the types. Looking at it myself, I see that koa-helmet uses a bunch of config types. They're matched with corresponding methods, so `xssFilter` takes `IHelmetXssFilterConfiguration`. Have those config types changed [much] in helmet 4?

**Comment by peterblazejewicz** [comment]
@sandersn well-laid, sir! thx!

**Comment by EvanHahn** [comment]
Helmet 4 removed a few things and some options are different. I'm not sure how different is too different, but the types are most definitely incompatible. Does that answer your question?

**Comment by sandersn** [comment]
It sounds like the best thing is to have `@types/koa-helmet` depend on `@types/helmet@3` then.

**Comment by EvanHahn** [comment]
Agreed. Should I change its references to `'helmet'` to `'@types/helmet'`, or something else? Again, pardon my DefinitelyTyped foolishness.

**Comment by sandersn** [comment]
No need to changes its code; instead you need to add a package.json with a reference to `@types/helmet`. `types/aframe/` is a good example (except it depends on three, not helmet).

**Comment by EvanHahn** [comment]
I tried this but couldn't get it to work. After removing the Helmet types, I tried two things in `types/koa-helmet`.

A first diff adds a `package.json` with a dependency on `helmet`:

```diff
diff --git a/types/koa-helmet/package.json b/types/koa-helmet/package.json
new file mode 100644
index 0000000000..f63dafccb5
--- /dev/null
+++ b/types/koa-helmet/package.json
@@ -0,0 +1,6 @@
+{
+  "private": true,
+  "dependencies": {
+    "helmet": "^3.23.3"
+  }
+}
```

This fails with "Cannot find module 'helmet' or its corresponding type declarations.". I also tried setting the version to `"*"` instead of `"^3.23.3"`, to the same effect.

And a second makes everything depend on `@types/helmet` instead:

```diff
diff --git a/types/koa-helmet/index.d.ts b/types/koa-helmet/index.d.ts
index 382dbc7918..42dd057615 100644
--- a/types/koa-helmet/index.d.ts
+++ b/types/koa-helmet/index.d.ts
@@ -15,7 +15,7 @@ import {
     IHelmetHidePoweredByConfiguration,
     IHelmetPermittedCrossDomainPoliciesConfiguration,
     IHelmetExpectCtConfiguration,
-} from 'helmet';
+} from '@types/helmet';
 import { Middleware, Context } from 'koa';
 
 declare namespace koaHelmet {
diff --git a/types/koa-helmet/package.json b/types/koa-helmet/package.json
new file mode 100644
index 0000000000..e4d4a98f69
--- /dev/null
+++ b/types/koa-helmet/package.json
@@ -0,0 +1,6 @@
+{
+  "private": true,
+  "dependencies": {
+    "@types/helmet": "^0.0.47"
+  }
+}
```

(I manually added `@types/helmet` to `node_modules/@definitelytyped/definitions-parser/allowedPackageJsonDependencies.txt` to see if this would work, but it also errors.)

Any thoughts about how to proceed here?

**Comment by peterblazejewicz** [comment]
@EvanHahn 
Can you make a repo with both setups (no modification, just npms packcage.json and tsconfig.json)? I can have a look, thanks!

**Comment by EvanHahn** [comment]
@peterblazejewicz Sure, but I don't think I understand what you mean. Do you want a fork of DefinitelyTyped? Or a repo that includes `koa-helmet`?

**Comment by peterblazejewicz** [comment]
A sample of new content, to look into how TS resolves definitions, so in `.gitignore` remove rule to not store `node_moduels`.

**Comment by EvanHahn** [comment]
Sorry, I still don't think I understand what you want. Is this a completely new project that shows what happens when you `npm install @types/koa-helmet`? Is this a fork of DefinitelyTyped that shows my changes, with `node_modules` included?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
