### ISSUE TITLE
[@types/jest] Unable to compile latest version when isolatedModules enabled

### ISSUE THREAD

**Issue by tnetennba3** [DefinitelyTyped/DefinitelyTyped#46571]
Hello 👋

The latest version of [@types/jest](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/package.json) includes a problematic jest-diff dependency. This [version](https://github.com/facebook/jest/blob/a679390828b6c30aeaa547d8c4dc9aed6531e357/packages/jest-diff/package.json) of jest-diff depends on a version of chalk that prevents Typescript from compiling when isolatedModules is enabled (see https://github.com/chalk/chalk/issues/382).

This issue in chalk has since been fixed in version 4 which is used by the latest version of jest-diff. I tried to create a pull request to update the jest-diff dependency in this package but I noticed that jest-diff uses [features](https://github.com/facebook/jest/pull/9693) only available in Typescript 3.8 and above. I then got myself into a web of dependency upgrades that I wasn't too confident making.

My current workaround is to use a downgraded version of @types/jest (^24.0.0) which doesn't include the problematic jest-diff dependency.

- [x] I tried using the `@types/jest` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:  @NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @ahnpnl @JoshuaKGoldberg @UselessPickles @r3nya @Hotell @sebald @andys8 @antoinebrault @gstamac @ExE-Boss @quassnoi @Belco90 @tonyhallett @ycmjason @devanshj @pawfa @regevbr

If you do not mention the authors the issue will be ignored.

**Comment by ms-ww** [comment]
Also running into this same issue.

**Comment by ms-ww** [comment]
I am still having it on @types/jest version ^24.0.0 (which resolves to 24.9.1)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
