### ISSUE TITLE
[@types/jest] `npm i @types/jest` causes http 404 Not found

### ISSUE THREAD

**Issue by Ogglas** [DefinitelyTyped/DefinitelyTyped#46591]
`npm i @types/jest` causes http 404. 

Command from:

https://www.npmjs.com/package/@types/jest

Even if you type `npm i @types/jest@26.0.9` it will still try to fetch `@jest/types@^25.5.0'`. `npm i @types/jest@25.2.3` will work. 

https://registry.npmjs.org/@jest%2ftypes

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@jest%2ftypes - Not found
npm ERR! 404
npm ERR! 404  '@jest/types@^25.5.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'pretty-format'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<USER>\AppData\Roaming\npm-cache\_logs\2020-08-06T11_12_37_944Z-debug.log
```

- [x] I tried using the `@types/jest` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @ahnpnl @JoshuaKGoldberg @UselessPickles @r3nya @Hotell @sebald @andys8 @antoinebrault @gstamac @ExE-Boss @quassnoi @Belco90 @tonyhallett @ycmjason @devanshj @pawfa @regevbr

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts

**Comment by wsmd** [comment]
```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@jest%2ftypes - Not found
```

@Ogglas it looks like you're trying to install `@jest/types` (it's the other way around `@types/jest`)

**Comment by Ogglas** [comment]
Works again now
