### ISSUE TITLE
Argument of type 'typeof InterviewContainer' is not assignable to parameter of type 'ComponentType<never>

### ISSUE THREAD

**Issue by dschinkel** [DefinitelyTyped/DefinitelyTyped#46603]
What am I missing? TS frustrates me to no end.

Using: 
```
"@types/react-redux": "^7.1.9", 
"react-redux": "^7.2.1"
```

`TS2345: Argument of type 'typeof InterviewContainer' is not assignable to parameter of type 'ComponentType<never>'.   Type 'typeof InterviewContainer' is not assignable to type 'ComponentClass<never, any>'.     Construct signature return types 'InterviewContainer' and 'Component<never, any, any>' are incompatible.       The types of 'props' are incompatible between these types.         Type 'Readonly<{ company: Company; match: RouteComponentProps<TParams, StaticContext, UnknownFacade>; fetchCompany: any; } & RouteComponentProps<...>> & Readonly<...>' is not assignable to type 'never'.`

```
import { fetchCompany } from '../actions/company/CompanyAsyncActions';
import Interview from './Interview';
import { Company, TParams } from '../../Interfaces';
import { RootState } from '../store';
import { RouteComponentProps } from 'react-router';

class InterviewContainer extends Component<{
  company: Company,
  match: RouteComponentProps<TParams>,
  fetchCompany: typeof fetchCompany
} & RouteComponentProps<{companyId: string}>, never> {
	async componentDidMount() {
		const { fetchCompany } = this.props;
		const { companyId } = this.props.match.params;
		await fetchCompany(companyId);
	}

	render() {
		const { company } = this.props;
		return company && <Interview className="ft-interview" company={company} />;
	}
}

const mapStateToProps = (state: RootState) => ({
	company: state.company.company,
});

const mapDispatchToProps = {
	fetchCompany,
};

export default connect(mapStateToProps, mapDispatchToProps)(InterviewContainer);
```
![Screen Shot 2020-08-06 at 2 09 51 PM](https://user-images.githubusercontent.com/338798/89588878-2af20c80-d80a-11ea-9c4e-e8f4c1f34b42.jpg)

**Comment by mariusnn** [comment]
`state.company.company` may be undefined (in `mapStateToProps`), but are declared as required in the prop-type passed to the component type.
Replacing `company: Company,` with `company?: Company,` (or ` company: Company | undefined`) on line 8 would fix the type-issue you're seeing.

**Comment by dschinkel** [comment]
thanks @mariusnn
