### ISSUE TITLE
Missing callback types for global queue events in @types/bull

### ISSUE THREAD

**Issue by abdatta** [DefinitelyTyped/DefinitelyTyped#46648]
Missing `global:` event names and their corresponding callback types, from queue listeners.
We have types for all the local events as below:
```ts
    on(event: 'error', callback: ErrorEventCallback): this;
    on(event: 'waiting', callback: WaitingEventCallback): this;
    on(event: 'active', callback: ActiveEventCallback<T>): this;
    on(event: 'stalled', callback: StalledEventCallback<T>): this;
    on(event: 'progress', callback: ProgressEventCallback<T>): this;
    on(event: 'completed', callback: CompletedEventCallback<T>): this;
    on(event: 'failed', callback: FailedEventCallback<T>): this;
    on(event: 'paused', callback: EventCallback): this;
    on(event: 'resumed', callback: EventCallback): this;
    on(event: 'removed', callback: RemovedEventCallback<T>): this;
    on(event: 'cleaned', callback: CleanedEventCallback<T>): this;
    on(event: 'drained', callback: EventCallback): this;
```
and we have a fallback type for other events (that includes global events as of now):
```ts
     on(event: string, callback: (...args: any[]) => void): this;
```
Using this definition for global events loses the type for the callbacks. So I believe we should have support for specific types for all the global events. If the authors agree, I can create a PR for the same.
Thank you.

- [x] I tried using the `@types/bull` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bgrieder @JProgrammer @marshall007 @weeco 

If you do not mention the authors the issue will be ignored.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
