### ISSUE TITLE
Definition request: Browser extensions

### ISSUE THREAD

**Issue by inf3rno** [DefinitelyTyped/DefinitelyTyped#4667]
It would be great to have some help (autocompletion) by browser extension SDKs, like:
 - https://developer.mozilla.org/en-US/Add-ons/SDK
 - https://developer.chrome.com/extensions

I am not sure whether this is possible based on documentation, it might need consultation with the browser developers, so they can give some data we can work with.

**Comment by pimterry** [comment]
Note that this already exists for Chrome at least: https://github.com/borisyankov/DefinitelyTyped/blob/master/chrome/chrome.d.ts

**Comment by mhegazy** [comment]
should be addressed by #9812
