### ISSUE TITLE
Types for SES notification event types for aws-lambda

### ISSUE THREAD

**Issue by Sparticuz** [DefinitelyTyped/DefinitelyTyped#46677]
- Authors: @simonbuchan, @darbio, @SachinShekhar (I didn't want to ping all the other contributors, but you three have accepted PR's in the past few months)

This is for aws-lambda types package. Would you be interested in the types for the SES -> SNS -> Notification events? It is a JSON string under event.Records.Sns.Message, but when parsed it is a standard AWS format (https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html). I put an issue because I'm not quite sure it would be a fit for the aws-lambda package, specifically because it requires parsing before it can be typed. Let me know and I'll try to put something together, (Or just take the code and put it in the right place, probably faster that way :) )

https://gist.github.com/Sparticuz/65f8849e73ba72a044f5d7084281cd08

**Comment by darbio** [comment]
The documentation says that it's a json object? Are you saying it's a string that needs to be parsed?

Either way, I think the types would be helpful, but I don't know if they fit in the aws-lambda package (being aws lambda specific).

Is there an SNS or SES package that would be more appropriate?

**Comment by simonbuchan** [comment]
I'm on my phone so I can't find it right now, but we do have some existing types that are parsed from a string by the user.

I'm fine with this, as to me the purpose of this package is to provide the typings determined by AWS that you have to deal with in a lambda. It is a bit of a grey area if you consider the type to be determined by another AWS other service, but all triggers essentially are that anyway, so I'll not very convinced.

**Comment by Sparticuz** [comment]
Yes, it's a json string that needs to be parsed. I'm not using any other package, other than aws-sdk.

The lambda function gets triggered from a SNS event. Basically any email sent from SES, will trigger a SNS message stating delivery, bounce, spam status, etc... which then triggers Lambda and sends that JSON object as a string in event.Records[].Sns.Message.
```
// Psuedocode
for each record in event.Records
notification = JSON.parse(record.Sns.Message)
```

notification is that object.

I will try to clean up my code and submit a PR. I'll have to do some research to see how to do this though. Basically https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9f8ff98dd1abb590654a7c75aaf26c09e25732dc/types/aws-lambda/trigger/sns.d.ts#L21 would instead be the type equivalent of `Message: JSON.stringify(Notification)` if that event exists?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
