### ISSUE TITLE
[@types/argparse] Support argparse 2.0

### ISSUE THREAD

**Issue by kevin-he-01** [DefinitelyTyped/DefinitelyTyped#46813]
Is something wrong with CI or publishing infrastructure? No

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/argparse` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @arcticwaters @tlaziuk @eps1lon @cakoose @ondkloss

If you do not mention the authors the issue will be ignored.

# The problem
`argparse` 2.0 (latest stable as of the time of writing) has recently been released. It included [various changes](https://github.com/nodeca/argparse/blob/f1a60eebdc487708085398da7e3fbcddd396d7b4/doc/migrate_v1_to_v2.md#migration-from-v1-to-v2) that require a different set of options and types, including [changing all `camelCase` names to `snake_case` ones](https://github.com/nodeca/argparse/blob/f1a60eebdc487708085398da7e3fbcddd396d7b4/doc/migrate_v1_to_v2.md#1-change-all-options-method-and-action-names-from-camelcase-to-snake_case), [add_argument](https://github.com/nodeca/argparse/blob/f1a60eebdc487708085398da7e3fbcddd396d7b4/doc/migrate_v1_to_v2.md#3-in-add_argument-argument-names-should-be-raw-params-not-array) with variable number of arguments instead of arrays, and the [new `version` option](https://github.com/nodeca/argparse/blob/f1a60eebdc487708085398da7e3fbcddd396d7b4/doc/migrate_v1_to_v2.md#5-version-option-of-argparseargumentparser-is-deprecated). Since `@types/argparse` currently only support `argparse` 1.0, sometimes to make the typescript compiler happy I have to keep doing things in the old, deprecated way. For typescript developers, this is probably the last block preventing them from migrating to `argparse` 2.0.

# Possible solutions
`argparse` 2.0 is a major change from 1.0 and I would suggest reading through [The migration guide](https://github.com/nodeca/argparse/blob/f1a60eebdc487708085398da7e3fbcddd396d7b4/doc/migrate_v1_to_v2.md) to get started. The changes are significant enough to probably have 2 separate declaration files, one for each major version.

**Comment by cakoose** [comment]
@kevin-he-01: Just FYI, for most DefinitelyTyped packages, you're probably going to have to make the improvements yourself.

Here is some information on dealing with new major versions: [link](https://github.com/DefinitelyTyped/DefinitelyTyped#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package).

**Comment by jcapinc** [comment]
I am interested in tackling this, should I take this from a full-reset perspective where I create types for the new library from scratch?

**Comment by cakoose** [comment]
Disclaimer: I'm no DefinitelyTyped expert or an argparse expert!

The old definitions are somewhat battle-tested.  There's probably a bunch of subtle things in those definitions that will be valuable to preserve in the new definitions.

Skimming over argparse's v1-to-v2 migration guide ([link](https://github.com/nodeca/argparse/blob/f1a60eebdc487708085398da7e3fbcddd396d7b4/doc/migrate_v1_to_v2.md#migration-from-v1-to-v2)), it looks like the changes are mostly cosmetic, so I'd recommend starting with a copy of the existing definitions and modify them.  (In the PR, it might even be nice to see two commits, one that makes a copy of the v1 definition and another that modifies it to match the v2 library.)

But these are just my own preferences.  I think just having a decent v2 definition will make a lot of people happy so do it however you want!

**Comment by jcapinc** [comment]
> Disclaimer: I'm not a DefinitelyTyped expert or an argparse expert!
> 
> The old definitions are somewhat battle-tested. There's probably a bunch of subtle things in those definitions that will be valuable to preserve in the new definitions.
> 
> Skimming over argparse's v1-to-v2 migration guide ([link](https://github.com/nodeca/argparse/blob/f1a60eebdc487708085398da7e3fbcddd396d7b4/doc/migrate_v1_to_v2.md#migration-from-v1-to-v2)), it looks like the changes are mostly cosmetic, so I'd recommend starting with a copy of the existing definitions and modify them. (It might be easiest to review a PR with two commits: one that makes a copy of the v1 definition and another that modifies it to match the v2 library.)
> 
> But these are just my own preferences. I think just having a decent v2 definition will make a lot of people happy so do it however you want!

yes, on further review that looks like it is the case. I think I will make a /v1/ folder and start on v2 in the basedir with the existing index.d.ts

**Comment by tmccombs** [comment]
It looks like the current version is for 2.0, this can probably be closed.

**Comment by kevin-he-01** [comment]
Whoops, forgot to close this. I am no longer developing the project that needs this. Thanks for resolving this though.
