### ISSUE TITLE
@types/mongodb 3.5.26 regression - nested fields are not supported

### ISSUE THREAD

**Issue by liorcode** [DefinitelyTyped/DefinitelyTyped#46817]
- [x] I tried using the `@types/mongodb@3.5.26` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @Celend 

After upgrading to `@types/mongodb` version 3.5.26, which introduced types for projection (#46488), the following code started failing:
```
usersCollection
      .find(
        {
          'account.pageId': {
            $in: pageIds,
          },
        },
        { projection: { 'account.pageId': 1 } },
      )
      .map((user) => user.account.pageId)
     .toArray();
```
It causes the following compile error:
`error TS2339: Property 'account' does not exist on type '{ 'account.pageId': unknown; }'`
Seems the new type might not take nested fields into account?
Is there some workaround for that?

**Comment by Celend** [comment]
It's seems fine to me?

Here is an example: https://github.com/Celend/types-mongodb-demo   
or checkout the test at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongodb/test/collection/findX.ts

**Comment by liorcode** [comment]
You forgot to use the returned type
here's a failing example: https://github.com/liorcode/types-mongodb-demo/blob/master/index.ts

**Comment by Celend** [comment]
Oh, it looks weird, as you can see, I did not change the return type for find method in the PR, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46488/files#diff-2b1325c7d29dbe7167881a665318da51R1106
  
But change the return type from `Cursor<T>` to `Cursor<TSchema>` it'll working fine, why?

**Comment by Celend** [comment]
会有 Redis 缓存，但是要放到 MongoDB 持久化，Redis 的话可能会因为内存不足被逐出。

**Comment by liorcode** [comment]
Seems it happens due to this line:
`find<T = TSchema>(query: FilterQuery<TSchema>, options?: FindOneOptions<T>): Cursor<T>;`
Here, you're passing the `T` along to `FindOneOptions` and it causes typescript to infer T differently than how it does normally- it infers T as whatever the type which is passed to the `projection`.
Without it - it normally doesn't infer `T`, and just use it's default type - `TSchema`
Not sure why exactly it does it.
One way around it, is what you said - to return the `Cursor<TSchema>`. But then if anyone would pass something to `T`, it wouldn't return it.

Another way, is to pass the `TSchema` to the `FindOneOptions` (instead of the `T`):
`find<T = TSchema>(query: FilterQuery<TSchema>, options?: FindOneOptions<TSchema>): Cursor<T>;`
(Note that this is the same solution for `FilterQuery`)

**Comment by Celend** [comment]
Wow, you're right, that's my fault, I'll make a PR to fix and re-check the changes, thanks so much!

**Comment by liorcode** [comment]
Thank you!

**Comment by Celend** [comment]
@liorcode Hi, I think this is a good solution(https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46863), could you please take a look?

**Comment by Celend** [comment]
It should be fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46863 @liorcode

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
