### ISSUE TITLE
Missing `theme` prop i CommonProps in React-select

### ISSUE THREAD

**Issue by gitowiec** [DefinitelyTyped/DefinitelyTyped#46838]
- [x] I tried using the `@types/react-select@2.0.19` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @claasahl, @jonfreedman 

I can't pass `theme` prop to components defined in `components` prop.
```
              <ReactSelectCreatable
                components={{
                  ...getSelectComponents<OptionType>(),
                  IndicatorsContainer: addErrorToIndicatorsContainer({ pending, error }),
                  Control: ({
                                    // @ts-ignore: Missing theme prop
                                    theme,
                                    ...props
                                  }) => {
                          console.log({ theme });
                          console.log({ props });

                          return (
                            <ReactSelectControl> //<-- this is just div styled with styled-components
                              <components.Control //<-- this is just import { components } from 'react-select';
                                {...props}
                                theme={
                                    // @ts-ignore: Missing theme prop
                                  theme
                                }
                              />
                            </ReactSelectControl>
                          );
                        },
                }}
                styles={{
                  ...getSelectStyles({ theme }),
                  ...(styles ? styles : {}),
                }}
                {...selectProps}
              />
```
Take a look at above example, every place where "theme" is there is Typescript error. The theme exists in runtime, it is passed from react-select to its children components.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
