### ISSUE TITLE
TS2339: Property 'user' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs>'

### ISSUE THREAD

**Issue by MIMAXUZ** [DefinitelyTyped/DefinitelyTyped#46861]
When trying to extend the Request interface from the package express to add some custom properties, I'm getting the following typescript error on my routers:
```
..\node_modules\ts-node\src\index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
   TSError: ⨯ Unable to compile TypeScript:
    src/app/middlewares/Authentification.ts:20:13 - error TS2339: Property 'user' does not exist on type 
   'Request<ParamsDictionary, any, any, ParsedQs>'.

   20         req.user = id;
    ....
```
I searched google for almost two days and none of them got a definite answer. The codes are working on my old project, but if I create a new project and use it, the above error occurs.

Now I'm using thoose packages:

- [ ] ts-node 8.10.2
- [ ] typescript 3.9.7
- [ ] express 4.17.1
- [ ] @types/node 14.6.0

- Now I'm using the latest stable version Typscript, express, Jsonwebtokens, TypeOrm and etc. My `tsconfig.json` file follow that:
```
{
   "compilerOptions": {
      "target": "es5",
      "module": "commonjs",
       "lib": ["es5",  "es6", "dom"
       ],
       "outDir": "./build",
       "emitDecoratorMetadata": true,
       "experimentalDecorators": true,
       "sourceMap": true,
      "moduleResolution": "node",
      "esModuleInterop": true,
      "allowJs": true,
      "noEmit": true,
      "noUnusedLocals": true,
      "noUnusedParameters": false,
      "preserveConstEnums": true,
      "skipLibCheck": true,
      "strict": true,
      "forceConsistentCasingInFileNames": true,
      "isolatedModules": true,
      "strictPropertyInitialization": false, /* Enable strict checking of property initialization in classes. */

   },
   "files": ["./src/types.d.ts", "./node_modules/@types/node/index.d.ts"],
   "include": ["src/**/*.ts"],
   "exclude": ["node_modules"],
   "typeRoots": ["./node_modules/@types"]
}
```
- My `type-d.ts` file follow as:
```
declare namespace Express {
  import { User } from "./app/entity/User";
  export interface Request {
    user?: User;
   // Alse tried as 
   // user: string
  // user?: string
  // user: any ...
  }
}
```
- My Router file follow as:
```
import bodyParser from "body-parser";
import express from "express";
import socket from "socket.io";
import {RegValidation, SignValidation } from "./../util";
import {UserCtrl, AuthCtrl} from "./../app/controller";
import Authentification from "./../app/middlewares/Authentification";
import cors from "cors";

const createRoutes = (app: express.Express, io: socket.Server) => {

    const options: cors.CorsOptions = {
        allowedHeaders: ["Origin", "X-Requested-With", "Content-Type", "Accept", "X-Access-Token"],
        credentials: true,
        methods: "GET,HEAD,OPTIONS,PUT,PATCH,POST,DELETE",
        origin: true,
        //origin: "*",
        optionsSuccessStatus: 204, // some legacy browsers (IE11, various SmartTVs) choke on 204
        preflightContinue: false
    };
    
    // declare controllers
    const UserController = new UserCtrl(io);
    // AuthCtrl
    const Auth = new AuthCtrl();

    app.use(cors());
    //enable pre-flight
    app.options( "*", cors(options));

    //Load files via URL
    app.use(express.static('public'));
    app.use(bodyParser.json());

    app.get( "/", Authentification, (_: express.Request, res: express.Response) => {
        res.send("Hello, World!");
    });

    // API for Users CRUD
    app.post("/user/register", RegValidation, UserController.create);
    app.post( "/user/login", SignValidation, Auth.authenticate);
};
export default createRoutes;
```
- And my middlewere file follw as:
```
import { Request, Response, NextFunction } from 'express'
import jwt from 'jsonwebtoken';

interface TokenPayload {
    id: string;
    iat: number;
    exp: number;
}

export default function AuthController ( req: Request, res: Response, next: NextFunction ) {
    const { authorization } = req.headers;
    if ( !authorization ) {
        res.send( 401 )
    }

    const token = authorization!.replace( 'Bearer', '' ).trim();
    try {
        const data = jwt.verify( token, 'BATMAN' );
        const { id } = data as TokenPayload;
        req.user = id;

        return next();
    } catch{
        res.sendStatus( 401 )
    }
}
// Also i tried with another codes but no solution
```
- My User model follow as:
```

@Entity( 'users' )
export class User {

    @PrimaryGeneratedColumn()
    id!: number;

    @Column({
        type: "varchar",
        length: 60,
    })
    first_name!: string;

    @Column({
        type: "varchar",
        length: 60,
    })
    last_name!: string;

    @Column({
        type: "varchar",
        length: 60,
        default: null,
        unique: true,
    })
    username!: string;

    @Column({
        type: "varchar",
        length: 60,
        unique: true,
    })
    email!: string;

    @Column({
        type: "varchar",
        default: "uploads/avatar.png"
    })
    avatar!: string;

    @Column({
        default: null,
    })
    birthday!: Date;

    @Column({
        default: null,
    })
    last_seen!: Date;

    @Column({
        default: true,
    })
    confirmed!: Boolean;

    @Column({
        default: true,
    })
    is_active!: Boolean;

    @Column({
        type: "varchar",
    })
    password!: string;

    @CreateDateColumn({ type: 'timestamp' })
    created_at!: Date;

    @UpdateDateColumn({ type: 'timestamp' })
    updated_at!: Date;
```
The codes are the same, working on my old project. But that is making an error in new project. Can anyone help?

**Comment by pdNN** [comment]
Hello, I got the same issue as you. How you managed to fix the error?

**Comment by MIMAXUZ** [comment]
@pdNN I didn’t do it that way. I used the other way.  I think it's better not to use types if you don't use interfaces when you use ORMs. So, I solved the problem through middleware as follows: 
First you need use ` res.locals.jwtPayload = jwtPayload;` inside your middlewere. So my full middleware like that:
```
 const token: string | null =
         "token" in req.headers ? (req.headers.token as string) : null;
    let jwtPayload;
    const secret: string = process.env.JWT_SECRET || "";

  if (token) {
      //Try to validate the token and get data
      try {
          jwtPayload = <any>jwt.verify( token, secret );
          res.locals.jwtPayload = jwtPayload;
          res.locals.user = res.locals.jwtPayload.data;
      } catch ( error ) {
          //If token is not valid, respond with 401 (unauthorized)
          res.status( 401 ).json( { message: "Invalid auth token provided or user unauthorized!", error } );
          return;
      }

      //The token is valid for a time you entered inside .env file
      //We want to send a new token on every request
      const { userId, email } = jwtPayload;
      const newToken = jwt.sign( { userId, email }, secret, {
          expiresIn: process.env.JWT_MAX_AGE,
          algorithm: "HS256",
      } );
      res.setHeader( "token", newToken );
      //Call the next middleware or controller
      next();
  }
  else {
    res.json({
      message: "Something went wrong! Please try again later...",
    });
  }
```
If you want to see how I used it in the full project, you can go inside my project on GitHub.  
Project URL:  https://github.com/MIMAXUZ/uMessenger/tree/master/node-server

**Comment by Scaralu** [comment]
I have the same issue.

That's how my express.d.ts file is filled:

```
declare namespace Express {
  interface Request {
    user: {
      id: string;
    };
  }
}
```

My ts and express versions are:

- [ ] typescript 3.9.5
- [ ] express 4.17.1

**Comment by leandroaugustolelis** [comment]
no solution?

**Comment by pdNN** [comment]
@leandroaugustolelis 
My issue was in the tsconfig.json file where I had to input in the typeRoots line the values of both my types paths, just like that:

"typeRoots": ["src/@types", "./node_modules/@types"], 


Full tsconfig.json file:
``
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */

    /* Basic Options */
    // "incremental": true,                   /* Enable incremental compilation */
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    // "lib": [],                             /* Specify library files to be included in the compilation. */
    // "allowJs": true,                       /* Allow javascript files to be compiled. */
    // "checkJs": true,                       /* Report errors in .js files. */
    // "jsx": "preserve",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
    // "sourceMap": true,                     /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    "outDir": "./build",                        /* Redirect output structure to the directory. */
    "rootDir": "./src",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "composite": true,                     /* Enable project compilation */
    // "tsBuildInfoFile": "./",               /* Specify file to store incremental compilation information */
    // "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */

    /* Strict Type-Checking Options */
    "strict": true,                           /* Enable all strict type-checking options. */
    // "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,              /* Enable strict null checks. */
    // "strictFunctionTypes": true,           /* Enable strict checking of function types. */
    // "strictBindCallApply": true,           /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
    "strictPropertyInitialization": false,  /* Enable strict checking of property initialization in classes. */
    // "noImplicitThis": true,                /* Raise error on 'this' expressions with an implied 'any' type. */
    // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    // "noUnusedLocals": true,                /* Report errors on unused locals. */
    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
    // "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */

    /* Module Resolution Options */
    // "moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    "baseUrl": "./src",                       /* Base directory to resolve non-absolute module names. */
    "paths": {
      "@modules/*": ["modules/*"],
      "@config/*": ["config/*"],
      "@shared/*": ["shared/*"],
    },                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    "typeRoots": ["src/@types", "./node_modules/@types"],                  /* List of folders to include type definitions from. */
    // "types": [],                           /* Type declaration files to be included in compilation. */
    // "allowSyntheticDefaultImports": true,  /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */
    // "allowUmdGlobalAccess": true,          /* Allow accessing UMD globals from modules. */

    /* Source Map Options */
    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */

    /* Advanced Options */
    "skipLibCheck": true,                     /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true  /* Disallow inconsistently-cased references to the same file. */
  }
}
``

typescript version: "^4.0.2",
express version: "^4.17.1",
ts-node-dev version: "^1.0.0-pre.61",

**Comment by leandroaugustolelis** [comment]
thank you =). I had this already solved, however, when I chance Request interface with user like:

declare namespace Express {
  interface Request {
    user: {
      id: string;
    };
  }
}

When I try to get request.user.id , it says "Property 'id' does not exist on type 'User'."  It seems that attribute id does not exist, very weird :(

**Comment by Scaralu** [comment]
I'm having the same issue, leandro.

**Comment by leandroaugustolelis** [comment]
Man, I solved, try using --files after ts-node script:

`"ts-node-dev `--files``

**Comment by guilhermeviinii** [comment]
> Cara, eu resolvi, tente usar --files após o script ts-node:
> 
> `ts-node-dev --files`

Thxxxxxxxxxxxxxxxx

**Comment by leonnardovv** [comment]
> thank you =). I had this already solved, however, when I change Request interface with user like:
> 
> ```
> declare namespace Express {
>   interface Request {
>     user: {
>       id: string;
>     };
>   }
> }
> ```
> 
> When I try to get request.user.id , it says "Property 'id' does not exist on type 'User'." It seems that attribute id does not exist, :(

Did you find a solution?

**Comment by praveennagaraj97** [comment]
> any solution?

Extend your request type before specifying 
interface ExtendedAuthStatsAttachedRequest extends Request {
  loggedUser: UserModel;
}

**Comment by programador404** [comment]
# Português:
### Pessoal eu estava tendo o mesmo problema, rodei vários sites e não resolvia! Eu apenas inverti a ordem no tsconfig.json do "typeRoots"[
      "./node_modules/@types",
       "./src/@types",
    ], 

para [
      "./src/@types",
      "./node_modules/@types",
    ],

#English:
### Guys I was having the same problem, I ran several sites and it didn't solve it! I just reversed the order in tsconfig.json from
"typeRoots"[
      "./node_modules/@types",
       "./src/@types",
    ], 

to [
      "./src/@types",
      "./node_modules/@types",
    ],

**Comment by tienduy-nguyen** [comment]
Try to change `declare namespace Express` to `declare module 'express'`
like this:
```js
import 'express';

declare module 'express' {
  interface Request {
    user?: any;
  }
}
```
In my case, I used the latest version of express: `express@4.17.1` and `typescript@4.2.4`

**Comment by tolumide-ng** [comment]
If you're using `ts-node` and not `ts-node-dev`, do this:

1. Create a `typings` folder in your `src` folder.
3. Create a folder within the `typings` folder with the name of the `package` you intend to extend.
4. Create an `index.d.ts` file with the new folder.

In my case, I am extending `express`, I ended up with something like this:

```
  src/
    - typings/
      - express/
        - index.d.ts
```

within the `index.d.ts` file I have this:

```
declare module Express {
    export interface Request {
        bucketUrl: string;
        fileName: string;
    }
}
```

Remember to update your `.tsconfig`:

```
{
  "compilerOptions": {
    "typeRoots" : ["./node_modules/@types", "./typings"]
  }
}
```

**Comment by IanMarcony** [comment]
> Man, I solved, try using --files after ts-node script:
> 
> `ts-node-dev --files`

Your solution solved for me, thanks

**Comment by IanMarcony** [comment]
Hey guys, I was tryng use "yarn start" with follow script: ts-node -r tsconfig-paths/register --files src/shared/infra/http/server.ts
This script solves for me

**Comment by vbgarciag** [comment]
> If you're using `ts-node` and not `ts-node-dev`, do this:
> 
> 1. Create a `typings` folder in your `src` folder.
> 2. Create a folder within the `typings` folder with the name of the `package` you intend to extend.
> 3. Create an `index.d.ts` file with the new folder.
> 
> In my case, I am extending `express`, I ended up with something like this:
> 
> ```
>   src/
>     - typings/
>       - express/
>         - index.d.ts
> ```
> 
> within the `index.d.ts` file I have this:
> 
> ```
> declare module Express {
>     export interface Request {
>         bucketUrl: string;
>         fileName: string;
>     }
> }
> ```
> 
> Remember to update your `.tsconfig`:
> 
> ```
> {
>   "compilerOptions": {
>     "typeRoots" : ["./node_modules/@types", "./typings"]
>   }
> }
> ```

In my case, I had to put "./typings" before "./node_modules/@types" and it worked! 

Thanks! 👍

**Comment by ChristianBermas** [comment]
router.post('/', async (req: Request | any, res: Response) => { req.user.id} );

need to pass 'any' in request :)

**Comment by sergey-developer** [comment]
> Hey guys, I was tryng use "yarn start" with follow script: ts-node -r tsconfig-paths/register --files src/shared/infra/http/server.ts
> This script solves for me

thank you, it solved my problem

**Comment by mobei12** [comment]
ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.3.5)
u should Keep the naming consistent, in both files(Express.d.ts and where use it)
Express.d.ts
`declare namespace Express{
    interface Request{
        user?:{
            user_id:string,
            user_name?:string
        }
    }
}`
xxx.ts
`router.get("/find", (Request, res) => {
    const user = Request.user
    //do something
});`

**Comment by CrisLDev** [comment]
> --files

your answer was perfect, now in script i execute like that
{
     "dev": "ts-node-dev --files src/index.ts"
}.
Thank your so much.

**Comment by Matzielab** [comment]
> Man, I solved, try using --files after ts-node script:
> 
> `ts-node-dev --files`

The creation of *.d.ts files fixed the IDE error for me and this fixed the error during compiling!
you can append the --files tag using nodemon, my start script looks like this

`"start": "nodemon --files index.ts"`

**Comment by AmosSpark** [comment]
> router.post('/', async (req: Request | any, res: Response) => { req.user.id} );
> 
> need to pass 'any' in request :)

Thank you, this is short and it work.

**Comment by mbukuru** [comment]
Thank you. I was able to solve the issue by adding 'any' to request

export const checkAuth = async (
  req: Request| any,
  res: Response,
  next: NextFunction
)

**Comment by abdulrizky** [comment]
> > Man, I solved, try using --files after ts-node script:
> > `ts-node-dev --files`
> 
> The creation of *.d.ts files fixed the IDE error for me and this fixed the error during compiling! you can append the --files tag using nodemon, my start script looks like this
> 
> `"start": "nodemon --files index.ts"`

**Comment by abdulrizky** [comment]
> > Man, I solved, try using --files after ts-node script:
> > `ts-node-dev --files`
> 
> The creation of *.d.ts files fixed the IDE error for me and this fixed the error during compiling! you can append the --files tag using nodemon, my start script looks like this
> 
> `"start": "nodemon --files index.ts"`

Thank you

**Comment by wsilva94** [comment]
1- tsConfig.json to add
`"typeRoots": [
        "./src/@types",
        "./node_modules/@types"
      ]`
2 - @types/express to add 
`import * as http from 'http';

declare module 'express-serve-static-core' {
  export interface Request extends http.IncomingMessage, Express.Request {
    userId: number;
  }
}`

**Comment by antoniovuono** [comment]
> wsilva94

thanks dude, 

it works for me, a just change the property who i need to type from my project.

`
import * as http from 'http';

declare module 'express-serve-static-core' {
    export interface Request extends http.IncomingMessage, Express.Request {
        user: {
            id: string;
        };
    }
}
`

**Comment by antoniovuono** [comment]
It works for me.

**Folder:**
@types>express>index.d.ts

**FILE: index.d.ts**
```
declare namespace Express {
    export interface Request {
        user: {
            id: string;
        };
    }
}
```

**ts-config: compilerOptions:**
  "typeRoots": [ "./src/@types", "./node_modules/@types" ],

**Comment by DENNIS-CODES** [comment]
You have to either extend Request with your own router handler,
- create a file in this format structure
![image](https://user-images.githubusercontent.com/65861136/205359779-88ba6a5e-eeb5-46a8-b6c7-0419c75944d4.png)
extend Request middleware with your own global namespace user like this
![image](https://user-images.githubusercontent.com/65861136/205360315-d268dcea-118b-47f2-9361-d4d5fc8d1c6b.png)
Then proceed to add this line in your ts.config file under compiler options
`"typeRoots":` ` ["src/@types", "./node_modules/@types"],`

**Comment by brunopassos** [comment]
> --files

Thanks man!

**Comment by jeremyng123** [comment]
> > --files
> 
> your answer was perfect, now in script i execute like that { "dev": "ts-node-dev --files src/index.ts" }. Thank your so much.

Does anyone have any clue why adding the --files flag worked? i want to know the 'why' and not just blindly copy the code. and yes, it fixed my problem, thanks. but i want to know why this flag is necessary?!

**Comment by craigedney** [comment]
> > > --files
> > 
> > 
> > your answer was perfect, now in script i execute like that { "dev": "ts-node-dev --files src/index.ts" }. Thank your so much.
> 
> Does anyone have any clue why adding the --files flag worked? i want to know the 'why' and not just blindly copy the code. and yes, it fixed my problem, thanks. but i want to know why this flag is necessary?!

agree: especially with something as critical as authentication...

**Comment by ParthParekh7** [comment]
I came up with a solution by creating an interface of any name you like
`export interface Payload {
    payload?: {
        id: string
        username: string
    }
}`

and use this in APIs like
`async (req: Request & Payload, res: Response)`

it is a better way to do it rather than defining any type.

**Comment by Dipesh-Das97** [comment]
Hi, I was able to fix this issue in my local development but now I am facing the issue with github actions.
I created a basic repo with Express and TS and created an issue. Please share any insights on the same.

https://github.com/Dipesh-Das97/Chat-App/issues/2

**Comment by nivel10** [comment]
EN: Greetings, I don't know if it's late. What I use is this: const { token, role} =<any>req;
ES: Saludos, no se si es tarde. yo lo que uso es esto: const { token, role} =<any>req;

**Comment by Deivid182** [comment]
> Man, I solved, try using --files after ts-node script:
> 
> `ts-node-dev --files`

Man thanks!! It works

**Comment by AnasShinkafi** [comment]
`tsnd --files `   That's how I solved my own

**Comment by sergio620** [comment]
> > Man, I solved, try using --files after ts-node script:
> > `ts-node-dev --files`
> 
> The creation of *.d.ts files fixed the IDE error for me and this fixed the error during compiling! you can append the --files tag using nodemon, my start script looks like this
> 
> `"start": "nodemon --files index.ts"`

Thank you so much!!

**Comment by RobertTompsky** [comment]
If you are using ORM like Prisma, create custom interface of req:
`export interface RequestWithUser extends Request {
    user: User (model from Prisma schema)
}`
Then use this interface where you need access to req.user, for example:
`export const auth = async (req: RequestWithUser, res: Response, next: NextFunction) => {
    try {
        const token = req.headers.authorization?.split(' ')[1];
        
        if (!token) {
            return res.status(401).json({
                message: "Токен не найден",
            });
        }

        const decoded = jwt.verify(token, process.env.JWT_SECRET) as { userId: string };

        if (!decoded || !decoded.userId) {
            return res.status(401).json({
                message: "Некорректный формат токена",
            });
        }

        const user: User | null = await prisma.user.findUnique({
            where: {
                id: decoded.userId
            }
        });

        if (user) {
            req.user = user
        } else {
            throw new Error('User not found');
        }

        next();
    } catch (error) {
        res.status(401).json({ message: "Пользователь не авторизован", error: error.message });
    }
}`
Maybe there is another solution, but this one definitely works

**Comment by 0cto-pus** [comment]
"baseUrl": "./src",                                
    "typeRoots": ["./node_modules/@types", "src/types"],
    "paths": {
      "types/*": ["types/*"]
    },                                    /* Specify multiple folders that act like './node_modules/@types'. */
    "types": ["node", "express"],   
    
    **I added the specifications to the ts.config file as above and fixed**
    
    
Here's my code if it helps:
  
  express.d.ts ->
```
 import { UserPayload } from './notes-types';

declare global {
  namespace Express {
    interface Request {
      user?: UserPayload;
    }
  }
}
```
note-types.ts ->
```
export interface UserPayload extends JwtPayload {
  email: string;
  _id: typeof ObjectId;
}
```

**Comment by HoppeDevz** [comment]
> Man, I solved, try using --files after ts-node script:
> 
> `ts-node-dev --files`

GOAT

**Comment by Sooraj-Rao** [comment]
This one worked for me thanks.

"dev": "nodemon --files ./index.ts"

**Comment by claudiocassimiro** [comment]
> Man, I solved, try using --files after ts-node script:
> 
> `ts-node-dev --files`

I love u man

**Comment by thekiwidev** [comment]
> You have to either extend Request with your own router handler, or cast it to type any or object
> 
> * create a file in this format structure
>   ![image](https://user-images.githubusercontent.com/65861136/205360717-36e942ec-97d3-4bcd-b6a4-0ffe7dd1ded0.png)
> * cast user to type any or object like this
>   ![image](https://user-images.githubusercontent.com/65861136/205360315-d268dcea-118b-47f2-9361-d4d5fc8d1c6b.png)
> * Then proceed to add this line in your ts.config file under compiler options
>   `"typeRoots":` ` ["src/@types", "./node_modules/@types"],`

this worked for me bro, thanks a bunch

**Comment by sandromatiass** [comment]
Cara pra mim resolvel coloquei daseguinte forma:

  "dev": "ts-node-dev --files src/server.ts"
  
  local: package.json

**Comment by SatishDevv** [comment]
Hello, I got the same issue as you. How you managed to fix the error?

**Comment by gtecotan** [comment]
use this;
/// <reference path="../custom_typings/express/index.d.ts" />
where we need to call req.user

**Comment by gtecotan** [comment]
/// <reference path="../custom_typings/express/index.d.ts" />

**Comment by gtecotan** [comment]
\/// <reference path="../custom_typings/express/index.d.ts" />

**Comment by gtecotan** [comment]
// <reference path="../custom_typings/express/index.d.ts" />

**Comment by gtecotan** [comment]
<reference path="../custom_typings/express/index.d.ts" />
like comment

**Comment by adeyemosamuel** [comment]
> nodemon --files ./index.ts

this worked for me. Many thanks

**Comment by Alfie-AD** [comment]
Nothing worked for me, then i realise `res.locals` was made for this.

just do `res.locals.user = yourUser` and access it at `res.locals.user`. No config needed

**Comment by Anilcodes01** [comment]
> Hello, I got the same issue as you. How you managed to fix the error?

I just added this line of code in my tsconfig.json and it solved the whole error 

 "files": ["./src/types/express/index.d.ts", "./node_modules/@types/node/index.d.ts"],
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules"],
  "typeRoots": ["./node_modules/@types"]

just try to use the first line of code, and make sure to specify the path of  your types.ts file.

**Comment by Manrus05** [comment]
npm i -D @types/passport-jwt @types/passport-local
I had the same problem, this helped me

**Comment by bimsara-jayasena** [comment]
> > Hello, I got the same issue as you. How you managed to fix the error?
> 
> I just added this line of code in my tsconfig.json and it solved the whole error
> 
> "files": ["./src/types/express/index.d.ts", "./node_modules/@types/node/index.d.ts"], "include": ["src/**/*.ts"], "exclude": ["node_modules"], "typeRoots": ["./node_modules/[@types](https://github.com/types)"]
> 
> just try to use the first line of code, and make sure to specify the path of your types.ts file.

this helped me.thank a lot

**Comment by thecodermehedi** [comment]
solution: https://gist.github.com/thecodermehedi/84bddee8f7c65eadf340e32e0c0a269a
