### ISSUE TITLE
Type mismatch in preloadjs

### ISSUE THREAD

**Issue by mayankdedhia** [DefinitelyTyped/DefinitelyTyped#4692]
Whenever I pass "createjs.HTMLAudioPlugin" in the "preloadQueue.installPlugin" method it gives me the following error.

Build: Argument of type 'typeof HTMLAudioPlugin' is not assignable to parameter of type '() => any'.

**Comment by vvakame** [comment]
@mayankdedhia please send a pull request. I'll review it.

**Comment by MrGekko** [comment]
For me https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13012 fixed the issue, so please check if it worked for you and close the issue.
