### ISSUE TITLE
[@types/reach__router] typings shouldn't depend on 'history' typings

### ISSUE THREAD

**Issue by dbanisimov** [DefinitelyTyped/DefinitelyTyped#46972]
`@reach/router` typings depend on `history` typings although the packages themselves don't have this dependency. This leads to problems when used in a codebase that actually uses the `history` package.

As an example in our particular case our app uses `react-router@6` which depends on `history@5` which includes it's own typings. We also use storybook which depends on `@reach/router` which uses `@types/reach__router` typings which depend on `@types/history@4` typings. Now, since actual library has typings built-in typescript uses those instead of `@types/reach__router` typings and that makes them incompatible, e.g. `LocationState` is not present in v5 history. Note that there is no conflict in the source code packages versions, as `@reach/router` has no dependency on `history`

Currently the `@reach/router` typings depend on `history` typings for `Location` and `LocationState` types:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0dc5a70adda8cf722f10d088f98f85cb9cf38951/types/reach__router/index.d.ts#L13-L14

Which in turn are fairly straightforward types:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0dc5a70adda8cf722f10d088f98f85cb9cf38951/types/history/index.d.ts#L27-L33

with all the properties being strings, or in the case of `LocationState` a union of an object and undefined.

Given that this is not a true dependency I think that it would make sense to pull in these type definitions directly in `@types/reach__router`. I might not be aware of all the complications of such a change, so please advise if you see any.

Authors: @kingdaro @xMokAx @awwit @wroughtec @chilledoj @Eyas

**Comment by jgoux** [comment]
Hello @dbanisimov , did you find a workaround? It's blocking me from compiling.
