### ISSUE TITLE
Is multer change the way with error handling when using with typescript？

### ISSUE THREAD

**Issue by xuntianxuntian** [DefinitelyTyped/DefinitelyTyped#47019]
In typescript :
`multer({options}).fields([...fields]})(req,res,next)`
in Official doc ,it turns to b :
`multer({options}).fields([...fields]})(req,res,err=>{})`

So,here is the problem,where does the error go?

I used to wrapped with try-catch to catch the errors,but it didn't work...

Did anyone has the same trouble with me ??

**Comment by peterblazejewicz** [comment]
@xuntianxuntian the JS is always a source-of-truth, the TS (definition types) does not produce any code on its won (.d.ts will not produce any outcome).
The `fields(...)` seems to return standard Express middleware:
https://github.com/expressjs/multer/blob/master/index.js#L68
