### ISSUE TITLE
compilation issue "node_modules/@types/lodash/common/common.d.ts:9:38: Declaration or statement expected"

### ISSUE THREAD

**Issue by kumaresan-subramani** [DefinitelyTyped/DefinitelyTyped#47022]
## Description

[@types/lodash](https://www.npmjs.com/package/@types/lodash), package has been updated 16 hours ago. Due to this upgrade we are facing below compilaiton error:

```
> @syncfusion/ej2-angular-documenteditor@18.2.54 packagr /jenkins/workspace/nents_hotfix_18.2.0.44_Vol2-AAPQ6ZYNQ3M33UKYQRVFVO4FLEH4ECWNZSYIZGIN435D3ISAWYKQ/third-party/angular
> ng-packagr -p ng-package.json && gulp npmrc-changelog-schematics-injection && gulp path-change

Building Angular library
Generating bundle for @syncfusion/ej2-angular-documenteditor
Cleaning bundle build directory
Processing assets
Running ngc

BUILD ERROR
Error at /jenkins/workspace/nents_hotfix_18.2.0.44_Vol2-AAPQ6ZYNQ3M33UKYQRVFVO4FLEH4ECWNZSYIZGIN435D3ISAWYKQ/third-party/angular/node_modules/@types/lodash/common/common.d.ts:9:11: ';' expected.
Error at /jenkins/workspace/nents_hotfix_18.2.0.44_Vol2-AAPQ6ZYNQ3M33UKYQRVFVO4FLEH4ECWNZSYIZGIN435D3ISAWYKQ/third-party/angular/node_modules/@types/lodash/common/common.d.ts:9:38: Declaration or statement expected.
Error at /jenkins/workspace/nents_hotfix_18.2.0.44_Vol2-AAPQ6ZYNQ3M33UKYQRVFVO4FLEH4ECWNZSYIZGIN435D3ISAWYKQ/third-party/angular/node_modules/@types/lodash/common/common.d.ts:9:56: '(' expected.
Error at /jenkins/workspace/nents_hotfix_18.2.0.44_Vol2-AAPQ6ZYNQ3M33UKYQRVFVO4FLEH4ECWNZSYIZGIN435D3ISAWYKQ/third-party/angular/node_modules/@types/lodash/common/common.d.ts:9:72: '(' expected.
Error at /jenkins/workspace/nents_hotfix_18.2.0.44_Vol2-AAPQ6ZYNQ3M33UKYQRVFVO4FLEH4ECWNZSYIZGIN435D3ISAWYKQ/third-party/angular/node_modules/@types/lodash/common/common.d.ts:9:86: '(' expected.
Error at /jenkins/workspace/nents_hotfix_18.2.0.44_Vol2-AAPQ6ZYNQ3M33UKYQRVFVO4FLEH4ECWNZSYIZGIN435D3ISAWYKQ/third-party/angular/node_modules/@types/lodash/common/common.d.ts:9:103: '(' expected.
Error at /jenkins/workspace/nents_hotfix_18.2.0.44_Vol2-AAPQ6ZYNQ3M33UKYQRVFVO4FLEH4ECWNZSYIZGIN435D3ISAWYKQ/third-party/angular/node_modules/@types/lodash/common/common.d.ts:9:112: ',' expected.
```

## is this regression

Yes, while using `4.14.159` all are working fine. when using latest it throws mentioned comilation error

## repo steps

1. download below sample
[sample.zip](https://github.com/DefinitelyTyped/DefinitelyTyped/files/5122894/sample.zip)

2. give `npm i`

3. then `npm run packagr`

4. you will see error in terminal

**Comment by Nabsef** [comment]
I have the same issue with this new update.

**Comment by peterblazejewicz** [comment]
@sandersn sorry for tagging, when you have time. NOt sure here is that is related to your changes (conditional types) or just to the tooling in the project.

**Comment by kumaresan-subramani** [comment]
Any update on this?

**Comment by kumaresan-subramani** [comment]
Also facing below issue too after `@tyes/node` package updation

## Error

[21:48:12] Starting 'schematics-tasks'...
[21:48:12] Starting 'schematics-build'...
**/jenkins/workspace/EJ2_ej2-es-build_master-EFD45P5PBZWJOW67KTEN5ISPYMET26TRP7EYUTAABES4O6X7COPQ/repositories/ej2-treemap/third-party/angular/node_modules/@types/node/assert.d.ts(2,68): error TS1144: '{' or ';' expected.**
[21:48:16] 'schematics-build' errored after 3.69 s
[21:48:16] TypeScript error: /jenkins/workspace/EJ2_ej2-es-build_master-EFD45P5PBZWJOW67KTEN5ISPYMET26TRP7EYUTAABES4O6X7COPQ/repositories/ej2-treemap/third-party/angular/node_modules/@types/node/assert.d.ts(2,68): error TS1144: '{' or ';' expected.
    at Object.getError (/jenkins/workspace/EJ2_ej2-es-build_master-EFD45P5PBZWJOW67KTEN5ISPYMET26TRP7EYUTAABES4O6X7COPQ/repositories/ej2-treemap/third-party/angular/node_modules/gulp-typescript/release/utils.js:53:15)

**Comment by sandersn** [comment]
@kumaresan-subramani what version of typescript are you using? It looks like it's a version that

1. Doesn't understand the typesVersion entry in package.json, so pre-3.1.
2. Doesn't understand conditional types, so pre-2.8.
3. (From your follow-up error) Doesn't understand asserts guards, so pre-3.7.

Definitely Typed only supports TS 3.2 and above, so you'll need to use an specific old version of type packages. You can find the best version for your Typescript by looking at the ts* tags for the package.

**Comment by kumaresan-subramani** [comment]
HI @sandersn ,

I am using typescript version `2.7.2`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
