### ISSUE TITLE
[@types/supertest] Can't chain `.post` after `.set`

### ISSUE THREAD

**Issue by kannan-at** [DefinitelyTyped/DefinitelyTyped#47075]
I ran into the following issue ([playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM51QVzAU1j1eAMyghDgHItd9CKBuAKEYGMIA7QuKAzAG3gBeFAHdkweNTwwCMAHTIA5jnYwAFBQAWMGGFQAuAPSHtugEbB2c6IooBKRnCdw5qHOooBBFixxgYFAA0lGZ8yJqGoeH2js5ykIQahgkBdvROxnAAKgDKAML6cAAKpDQwAJ6UKRRwACYQBHDsEPA4AB7AXBxwFbiUAEo4AI6YshRyrByoEHw4cnwQimo8WAKuMMgwmKjBK-zyZhC15WlAA)):

```typescript
import * as supertest from 'supertest';

const result = await supertest.agent('https://httpbin.org')
    .set('Accept', 'blah/blah')
    .post('/post');  // TSC: Property 'post' does not exist on type 'Request'.
console.log(result.status, result.body);
```

If I run this code in Node, it works correctly.  I think there's an issue with the type definition.

I had trouble understanding what the current types were doing, so I'm not sure how to fix it.  Tagging @aaltepet and @andrewbranch because this PR seemed related: #44420.

**Comment by aaltepet** [comment]
@kannan-at - It is counter-intuitive, but the order in your example is backwards.  The ``set`` must come after ``post``:

```
import * as supertest from 'supertest';

const result = await supertest.agent('https://httpbin.org')
   .post('/post')
   .set('Accept', 'blah/blah')
console.log(result.status, result.body);
```

See the example in the superagent docs: https://visionmedia.github.io/superagent/#setting-header-fields

**Comment by kannan-at** [comment]
Both orderings work at runtime (in both "supertest" and "superagent").  I normally call `.post` first, but there are cases where it's useful to do `.set` first, e.g.

```
function getApiClient() {
    return supertest.agent('https://whatever/api')
        .set('Content-Type', 'application/json')
        .set('Authorization', 'Bearer ...')
}

const r1 = await getApiClient().post('/todos').send(...);
const r2 = await getApiClient().get('/todos');
```

**Comment by aaltepet** [comment]
That's a fair example!  I agree the types should support this. The supertest typings are complex and resolving this discrepancy is beyond my ability.  If you're able to, I'd love to see how to resolve this :-)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
