### ISSUE TITLE
lodash: _([1, 2]).groupBy(n => n % 2).map((group, key) => group.length) fails

### ISSUE THREAD

**Issue by tandyjames** [DefinitelyTyped/DefinitelyTyped#4718]
The map method does not figure out the type when it is of a _.Dictionary<>.
The GroupBy returns a _.Dictionary<number[]>.
The map method should make group a number[] and key a string.
Instead it makes group a {} (it gets the key as a string correctly).

I'm not sure how to fix it... any ideas?
We do this pattern a lot: first group by... then map the group. When the group is {} it throws errors to do any dotting off the object at all.

Thanks!

**Comment by chrootsu** [comment]
@tandyjames As I can see, the issue has been fixed, isn't it?

**Comment by chrootsu** [comment]
@vvakame I think the issue can be closed.

```typescript
let groupByResult = _([1, 2]).groupBy(n => n % 2); // => _.LoDashImplicitObjectWrapper<number[]>
let unwrappedGroupByResult =  groupByResult.value(); // => _.Dictionary<number[]>

let mapResult = groupByResult.map<number, number>((group, key) => group.length); // => _.LoDashImplicitArrayWrapper<number>
let unwrappedMapResult =  mapResult.value(); // => number[]
```
