### ISSUE TITLE
[@types/compression-webpack-plugin] is incopatible with @gfx/zopfli

### ISSUE THREAD

**Issue by vitoyucepi** [DefinitelyTyped/DefinitelyTyped#47230]
- [x] I tried using the `@types/compression-webpack-plugin` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
      - @dublicator
      - @rhys-vdw
      - @peterblazejewicz

### Summary
I've found regression in compression-webpack-plugin@v5.0.1 webpack-contrib/compression-webpack-plugin#189.
Now it will support passing zopfli like in docs https://webpack.js.org/plugins/compression-webpack-plugin/#using-zopfli
```js
algorithm(input, compressionOptions, callback) {
  return zopfli.gzip(input, compressionOptions, callback);
},
```
But `@types/compression-webpack-plugin` isn't compatible with `@gfx/zopfli` and throw an error:
```
Error:(151, 46) TS2345: Argument of type 'AlgorithmCallback' is not assignable to parameter of type 'OnCompressComplete'.
  Types of parameters 'result' and 'buffer' are incompatible.
    Type 'Uint8Array' is missing the following properties from type 'Buffer': write, toJSON, equals, compare, and 48 more.
```

### Additional info
https://www.npmjs.com/package/@gfx/zopfli#using-zopfli-in-webpack-compressionplugin
```
module.exports = {
  plugins: [
    new CompressionPlugin({
      algorithm: gzip,
    }),
  ],
};
```
throws an error:
```
Error:(151, 5) TS2322: Type '(buffer: InputType, options: ZopfliOptions, cb: OnCompressComplete) => void' is not assignable to type 'Algorithm<ZopfliOptions>'.
  Types of parameters 'cb' and 'callback' are incompatible.
    Types of parameters 'result' and 'buffer' are incompatible.
      Type 'Uint8Array' is missing the following properties from type 'Buffer': write, toJSON, equals, compare, and 48 more.
```

**Comment by peterblazejewicz** [comment]
@vitoyucepi 
so it looks it will be fixed with released update to gzip callback implementation? As per comment here:
https://github.com/webpack-contrib/compression-webpack-plugin/issues/189#issuecomment-685336770

**Comment by vitoyucepi** [comment]
@peterblazejewicz it's already fixed in compression-webpack-plugin@v5.0.2 (webpack-contrib/compression-webpack-plugin#190) and my problem was in cache implementation.
Do you think I should create another issue in `@gfx/zopfli` repository?

**Comment by peterblazejewicz** [comment]
If I understand correctly, it should be just enough to accept wider spectrum of types, to comply with the patch version change, see my PR for details: #47234

**Comment by vitoyucepi** [comment]
In nodejs source Buffer extends UInt8Array. So it will possible to write just `UInt8Array` instead of `Buffer | UInt8Array`.

**Comment by peterblazejewicz** [comment]
cool, thx for review :), I'll amend.
