### ISSUE TITLE
DefinitelyTyped.BenchmarkPR  check failing

### ISSUE THREAD

**Issue by nikithauc** [DefinitelyTyped/DefinitelyTyped#47240]
The check DefinitelyTyped.BenchmarkPR  failed while creating [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47235).  I see that the same check has failed for a few recently opened PRs. What can be done to get all checks working?

**Comment by peterblazejewicz** [comment]
@nikithauc looks like infrastructure issue really
/cc @andrewbranch the relevant lines:
https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=62660&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=40b1ee41-44d6-5bba-aa04-4b76a5c732e5&l=53

**Comment by andrewbranch** [comment]
Oops, I updated its TS version to 4.0 but it looks like we haven’t yet told the installer that it’s published. Reverted. Thanks!
