### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by SinBirb** [DefinitelyTyped/DefinitelyTyped#47274]
- [x] I tried using the `@types/chartjs-plugin-annotation` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @danmana 
  - PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44114

`BoxAnnotationOptions.xMin` and `xMax` don't accept `Date` nor `Moment` types.

**Comment by peterblazejewicz** [comment]
@SinBirb can you point where these different (from number pixel) types are documented?
Thx!

**Comment by danmana** [comment]
You are right, it looks like it supports Dates too. I'll make an update

**Comment by SpineEyE** [comment]
Thank you!
