### ISSUE TITLE
d3-selection on() Event argument missing

### ISSUE THREAD

**Issue by Radiergummi** [DefinitelyTyped/DefinitelyTyped#47296]
- [x] I tried using the `@types/d3-selection` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond. Authors:
    - @tomwanzek 
    - @gustavderdrache
    - @borisyankov
    - @denisname 

D3 allow registering event listeners using the `on` method. Listener callbacks passed as the second parameter receive the DOM event fired and the respective datum associated to the element targeted by the event. This is outlined in the [D3 documentation](https://github.com/d3/d3-selection/blob/v2.0.0/README.md#selection_on) and apparent from [the source code](https://github.com/d3/d3-selection/blob/fcbb9cb7a663edd9fd3738fcb4093e10d20d65f2/src/selection/on.js#L1-L5).  

I suspect the D3 API has changed at some point in the past, as the D3 types describe a completely different set of arguments, making it impossible to properly attach event listeners to d3 elements:

```ts
on(typenames: string, listener: ValueFn<GElement, Datum, void>, capture?: boolean): this;

// ...where the definition of ValueFn is:
export type ValueFn<T extends BaseType, Datum, Result> = (this: T, datum: Datum, index: number, groups: T[] | ArrayLike<T>) => Result; 
```

Might it be that using `ValueFn` is a mistake, and there should rather exist a discrete event listener signature like the following:
```ts
export type EventListenerFn<T extends BaseType, E extends Event, Datum> = (this: T, event: E, datum: Datum) => void;
```

**Comment by lloydrichards** [comment]
I'm actually having the exact same problem and found out that it kind of a breaking change from V6 of D3.  Basically the problem came with ES6 and arrow functions where they were no longer able to bind `this` to the functions.  As a result of the newest version of D3 now has the `.on("mouseover", (e: Event, d: Datum)=> void)`  the Type for D3 is still using the old version (5.7 I think?).

http://definitelytyped.org/docs/d3--d3/interfaces/d3.selection.html#on
=/=
https://github.com/d3/d3-selection/blob/v2.0.0/README.md#selection_on

I've not found a good way to cast the types of the correct inputs, but tend to just console.log each one and double-check everything before casting them both to <any> (which sucks but is all I can do currently)

**Comment by lloydrichards** [comment]
https://observablehq.com/@d3/d3v6-migration-guide

As I'm trying to implement more and more of V6 I'm noticing a lot of breakage as a result of Typescript expecting certain things which either aren't there (Pointers) or are completely different (Select).  Until I hear from someone that the type will be updated soon, it'll probably be easier to just downgrade back to V5 for now

**Comment by Radiergummi** [comment]
Aha! That makes sense... I'm working on a new project and this is the first time I'm implementing D3 with Typescript, so I weren't aware of a new version. I opted for `@ts-ignore` above the listener attachments, as PhpStorm will not let me forget those... I guess I'm going to try and stay on V6 :/

**Comment by Methuselah96** [comment]
The types have been updated since this issue was made (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48261). I believe this issue can be closed.

**Comment by lstrahan** [comment]
The definition in @types/d3 for Selection.on() is still incorrect

**Comment by Methuselah96** [comment]
What is incorrect about them? What version are you on?

**Comment by lstrahan** [comment]
I am using d3@6.5.0 mailto:d3@6.5.0 and @types/d3@6.3.0

According to d3 V6 documentation, 'event' is now the first argument passed to event listeners.

@types/d3@6.3.0 contains the following definition...

on(typenames: string, listener: ValueFn<GElement, Datum, void>, capture?: boolean)


I think it should be something like this...

on(typenames: string, listener: ValueFn<Event, Datum>, capture?: boolean)


Thanks,
Lance

**Comment by Methuselah96** [comment]
> @types/d3@6.3.0 contains the following definition... on(typenames: string, listener: ValueFn<GElement, Datum, void>, capture?: boolean)

That's not the definition I'm seeing. The current definition should be this ([found here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-selection/index.d.ts#L904-L942)):

```
on(typenames: string, listener: (this: GElement, event: any, d: Datum) => void, options?: any): this;
```

Can you verify that `@types/d3-selection@2.0.0` is the installed package?

**Comment by lstrahan** [comment]
@types/d3 version = 6.3.0
but @types/d3-selection version is 1.4.2

I installed the latest @types/d3 package (which includes @types/d3-selection and others), but my @types/d3-selection is not 2.0

But the definition you are showing below still looks wrong. 'event' should be the first argument for the listener, not 'this: GElement'.

**Comment by Methuselah96** [comment]
Yes, unfortunately there's no way to force `@types/d3-selection` to be `^2.0.0` with the way DefinitelyTyped is set up, but it needs to be `^2.0.0`. If you're using `yarn.lock` or `package-lock.json` you can remove the lines relating to `d3` and reinstall and it should be fixed.

The `this: GElement` parameter is a fake parameter that just sets the value of `this` and is not a real parameter (see [this](https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters) for more info). The first parameter will be `event`.

**Comment by lstrahan** [comment]
Ok. I will try that. Thanks for your help.

**Comment by Radiergummi** [comment]
@Methuselah96 I take it this issue can definitely be closed now. Thank you ✌️
