### ISSUE TITLE
[@types/mongodb] Wrong readonly predicate on MongoDB types

### ISSUE THREAD

**Issue by efabris** [DefinitelyTyped/DefinitelyTyped#47338]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8340511f346a28abcdf4b0811550c1ca81ea20e5/types/mongodb/index.d.ts#L1329

The type "DotAndArrayNotation<AssignableType>" has "readonly" fields. This not allow to make update query as:

```

       eg: HousePet = {'cat': {'tom': {'name': 'tom', 'sex': 'm', 'color': 'white'}}}

       .....


        const cat: Cat = {name: 'tim', sex: 'm', color: 'black'}
        let set: MatchKeysAndValues<HousePet> = {}
        set['cat.' + cat.name] = cat
        let update_query: UpdateQuery<HousePet> = {
          $set: set,
        }

```

Should "readonly" be removed to fix the error "Index signature in type 'MatchKeysAndValues<Domain>' only permits reading."?

**Comment by filetvignon** [comment]
I would like to see this implemented as well. The only way past this is to always keep reassigning the $set object, as in
```
set = {...set, ['cat.' + cat.name]: cat}
```
which is not ideal.

Maybe create another type, so that this don't break, something like *EditableUpdateQuery*?

**Comment by sebastiangug** [comment]
Yeah this is affecting my usage as well. although thanks for that re-assigning idea, I was getting around it by just constructing an object with "any" type and hoping for the best. But I'd rather have something that's type safe, even though a little bit more verbose

**Comment by LinusU** [comment]
The `@types/mongodb` packages has been removed and typings are now shipped upstream as part of the `mongodb` package, so this issue can be closed...
