### ISSUE TITLE
Reference to node types is affecting tsconfig target

### ISSUE THREAD

**Issue by cscleison** [DefinitelyTyped/DefinitelyTyped#47341]
This is happening to a lot of libraries so I'm creating a "generic" issue first to see if this is really a problem with the libs definitions and how this should be addressed.
Repository [repro](https://github.com/cscleison/ts-error)
```json
// tsconfig.json

{
  "compilerOptions": {
    "strict": true,
    "allowJs": false,
    "target": "es5"
  },
  "include": ["./src"]
}
```

```ts
// src/index.ts

["a", "b"].map((c) => c.toUpperCase()); // should have no errors

[1, 2, 3].includes(0); // TS should complain about `includes` because it's not part of ES5
```

A lot of type definitions from DefinitelyTyped have `/// <reference types="node" />` inside them. If you check Nodejs types, it references `es2018`. As a result, by just installing a type or library, your codebase will **silently stop complaining** about ES features that are **higher** than your `target` configuration.

For example, if I do a `npm i -D webpack-dev-server` or `npm i -D @types/enzyme`, TypeScript stops complaining about the `includes` call.

It's definitely a case by case situation but should we remove these references, or should this problem be fixed somewhere else?

**Comment by cscleison** [comment]
@types/glob: @vvakame @voy @ajafff @peterblazejewicz the reference is in [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/glob/index.d.ts#L9) and I have the problem when I install `webpack-dev-server`:
```
npm list @types/node
ts-error@ C:\Users\cstein\src\ts-error
`-- webpack-dev-server@3.11.0
  `-- del@4.1.1
    `-- @types/glob@7.1.3
      `-- @types/node@14.6.4
```

**Comment by cscleison** [comment]
@types/cheerio: @blittle @wmaurer @umarniz @LiJinyao @chennakrishna8 @AzSiAz @nwtgck @privatenumber the reference is in [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cheerio/index.d.ts#L14) and the issue happens when I install `@types/enzyme`:
```
npm list @types/node
ts-error@ C:\Users\cscleison\src\ts-error
`-- @types/enzyme@3.10.5
  `-- @types/cheerio@0.22.21
    `-- @types/node@14.6.4
```

**Comment by cscleison** [comment]
`npm i -D jest` also causes the issue. A lot of internal packages from jest reference the node types. @SimenB @NoHomey @jwbay @regevbr

**Comment by SimenB** [comment]
If we don't include the dependency `/// <reference types="node" />` will fail and cause type errors (e.g. https://www.runpkg.com/?jest-haste-map@26.3.0/build/index.d.ts#7). If there are better ways to deal with that I'd love to fix it

**Comment by cscleison** [comment]
Yeah, it looks to me there's nothing wrong with the libs anyway. A testing lib might be using new ES specs and that's fine. Seems like I will have to go on a "defensive mode", specifying the [`types`](https://www.typescriptlang.org/tsconfig#types) in my main `tsconfig` and having an extra `tsconfig` only for tests.

**Comment by cscleison** [comment]
`"types": [],` did the trick
for anyone facing this, make sure that all the libs you are using in your source (not tests) also don't reference `node`. I had one lib doing it, and as its types were very simple, i just wrote custom types for it removing the reference.

closing
