### ISSUE TITLE
Definition request: Yandex Maps API

### ISSUE THREAD

**Issue by romka-chev** [DefinitelyTyped/DefinitelyTyped#4756]

**Comment by romka-chev** [comment]
For now i'm doing it in https://github.com/romka-chev/typed-ymaps-api. Can someon help with it?

**Comment by Delagen** [comment]
Created as can ) https://github.com/Delagen/typings-yandex-map

**Comment by Delagen** [comment]
Contributions are welcome )

**Comment by Delagen** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19388

**Comment by kachkaev** [comment]
I guess this issue should be marked as closed:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yandex-maps
