### ISSUE TITLE
Definition request: cytoscape.js

### ISSUE THREAD

**Issue by Cyberider** [DefinitelyTyped/DefinitelyTyped#4763]
cytoscape.js is a very popular graph theory diagramming library in the life sciences (bio sciences) industry. I'm new to TypeScript and JS otherwise I would make the definition file myself!

http://js.cytoscape.org/

There is a TS definition file for the sigma.js project which is also a graph theory diagramming library however that project is not nearly as feature rich as the cytoscape.js project.

**Comment by Fabian-Schmidt** [comment]
Hi,

i am currently in the process of creating one:
https://github.com/Fabian-Schmidt/DefinitelyTyped/tree/master/cytoscape

I have started creating a definition off the documentation. But not everything is in there now.
Most stuff is already working. But the library has a lot of functions.

**Comment by Cyberider** [comment]
The library has a LOT of functions! It is also I very well maintained and popular library compared to the alternative Sigma.js. The cytoscape.js library seems to have 2 main functional areas.
1. The actual visualization of the full dataset as pulled.
2. Client-side manipulation of that pulled dataset cached in the browser. (If I understand cytoscape.js correctly...).

It would make sense to start with 1 the actual visualization functionality first, which you probably are doing :-)

Thank you so much Fabian-Schmidt for your time, skills and effort in taking this project on! I am very excited!

Rick

**Comment by maxkfranz** [comment]
This looks really cool.

The docs are generated from a JSON spec of the API.  The file is: https://github.com/cytoscape/cytoscape.js/blob/master/documentation/docmaker.json

I wonder if this file could be used or modified slightly so we could automatically update the definition with future versions of Cytoscape.js.

There is pretty consistent naming conventions for parameters etc, so it would probably be possible to have a map of parameter names to types.

**Comment by Demurgos** [comment]
Is there any progress ?

**Comment by maxkfranz** [comment]
I haven't heard anything, but I'm hopeful someone's interested in building a bit of code to convert the JSON file/format I linked to into the definition.  That way, the TS definition would always be up to date.

**Comment by calebeaires** [comment]
Good work with that json, but someone had any progress?

**Comment by Cyberider** [comment]
@phreed is being shy/humble about his progress with this! Check it out:
https://github.com/phreed/ts-typings/blob/cytoscape/index.d.ts

**Comment by wy193777** [comment]
I just submitted @phreed 's work here: #20511. I guess @phreed no longer interested on it now.

**Comment by phreed** [comment]
Thanks for taking care of this. Yes I have other interests now.

**Comment by smith** [comment]
This now exists so I think this can be closed.
