### ISSUE TITLE
[@types/yup] TestOptionsMessage type should be updated to ReactNode (not string)

### ISSUE THREAD

**Issue by BohdanYavorskyi** [DefinitelyTyped/DefinitelyTyped#47651]
- [x] I tried using the `@types/yup` package and had problems.
- [x] I tried using the latest stable version of tsc. 
- Authors: @vtserman @dhardtke @MoretonBayRC @sseppola @YashdalfTheGray @vincentjames501 @robertbullen @sat0yu @deskoh @mauricedb @kalley @elias-garcia @iansan5653 @fjc0k

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f87f81730a873caec8d737e16971b5a08db06a5c/types/yup/index.d.ts#L49

Getting TS error:
Argument of type 'Element' is not assignable to parameter of type 'string | ((params: Partial<TestMessageParams>) => any) | undefined'.

<pre>
  const validationSchema = Yup.object().shape<Partial<FormValues>>({
    test: Yup.string().required(<>Test error<_/>),
  })
</pre>

Solution:
The type of TestOptionsMessage must be as ReactNode (not string) because it works well in such cases.

export type TestOptionsMessage<Extra extends Record<string, any> = {}, R = any> =
    | ReactNode
    | ((params: Extra & Partial<TestMessageParams>) => R);

**Comment by iansan5653** [comment]
I can't take a closer look at the moment but it definitely should not be `ReactNode` - this is not a React-specific library.

**Comment by mauricedb** [comment]
@BohdanYavorskyi Did you update your validation message to be a string and did that work? As @iansan5653 mentioned Yup is not tied to React and a React, or other framework, specific type is not a valid message type.

**Comment by BohdanYavorskyi** [comment]
Thanks @iansan5653 @mauricedb. I fixed my issues without changing types. So I'll close the issue soon.
