### ISSUE TITLE
Update Mongoose to 4.0

### ISSUE THREAD

**Issue by MrKomish** [DefinitelyTyped/DefinitelyTyped#4773]
Please, add type definition for mongoose 4.0.

**Comment by pocesar** [comment]
current mongoose implementation is really permissive, and hard to extend properly. IMHO it would have to be refactored to account for the typesafety that TS provides, but it would be a breaking change. I'm interested in this as well, and would be willing to give it a try, create two typings, mongoose and mongoose-legacy

**Comment by davidlondono** [comment]
+1

**Comment by Atsman** [comment]
The guy who implemented previous version is not going to refactor it. I check his activity on github and he is absent for a long time.

So i think that, we should implement new version on our own.

**Comment by dominikkukacka** [comment]
is there any news for this?

**Comment by pocesar** [comment]
just like new lodash, I think this needs a joint task force. the new lodash (4.x) definitions are superb btw, hinting just works(tm) https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/lodash/lodash.d.ts

notice the "checkmark" header, it's a hacky (but clever) way to get this done

**Comment by stevehipwell** [comment]
Do you have any news? Promise is broken if you want to use catch, will this be fixed?

**Comment by pocesar** [comment]
yeah, the promise.catch problem happened to me as well, and it's hard to extend the defined interfaces and classes in this typing. also most of the functions are missing their promise returns, like save(), populate(), execPopulate(), etc
had to manually edit the mongoose.d.ts to import bluebird to the typings file so I could use it in `mongoose.Promise = Bluebird`

**Comment by tomwanzek** [comment]
+1
Is there any work in progress on updating the mongoose.d.ts? Similar to @pocesar I ended up manually adding supplementary type definitions for MongooseArray and MongooseDocumentArray to use in model definitions, as they are completely missing from the current mongoose definition.

Also, this issue seems to overlap with #4262.

**Comment by simonxca** [comment]
Hey everyone, I've started working on an updated Definition for v4 here: https://github.com/simonxca/DefinitelyTyped/blob/mongoose4/mongoose/mongoose.d.ts

Still a long way to go, but I'm interested in suggestions on how to manage the breaking changes from v3 to v4.
