### ISSUE TITLE
[@types/ol] Last update broken

### ISSUE THREAD

**Issue by mhosman** [DefinitelyTyped/DefinitelyTyped#47778]
`ERROR in node_modules/@types/ol/Geolocation.d.ts:77:24 - error TS2304: Cannot find name 'GeolocationPositionError'.`

**Comment by timbru31** [comment]
Ping @hanreev as the code owner of this typings.

**Comment by hanreev** [comment]
TypeScript 4.1 changes#47681

**Comment by timbru31** [comment]
Thanks for the pointer!

**Comment by gongAll** [comment]
Just a small reminder for next releases: Only release breaking changes like this whenever Typescript is also officially released, since 4.1.0 is still only the "next" version. Great job tho :)

**Comment by th30d0r** [comment]
I cannot seem to find a stable version. My system runs on typescript 3.4.5 and any versions of this fails to compile with the above error

**Comment by dw-bayer** [comment]
add this bad boy to your tsconfig to jump over the issue.
```
{
  "compilerOptions": {
    "skipLibCheck": true
  },
}

**Comment by timbru31** [comment]
This has been fixed in #49172, can this be closed?

**Comment by mhosman** [comment]
Yeah, it seems it's working now. Closing. Thank you!
