### ISSUE TITLE
[@types/select2] requirejs dependency

### ISSUE THREAD

**Issue by john-larson** [DefinitelyTyped/DefinitelyTyped#47786]
Why is there a @types/requirejs dependency for @types/select2? It causes conflicts with other typings. Could this be removed if not necessary?

**Comment by martin-badin** [comment]
I looked at it and the type is necessary. One of the types from the package uses `Select2Plugin` interface.

```typescript
// --------------------------------------------------------------------------
// jQuery And Select2 Plugin
// --------------------------------------------------------------------------

export interface Select2Plugin<TElement = HTMLElement> {
    amd: { require: Require };
// ...
```

**Comment by forivall** [comment]
I inlined the require types, specifically only including the features that select2's built-in require handles.
