### ISSUE TITLE
[@types/bookshelf] knex version in package.json might be removed

### ISSUE THREAD

**Issue by i5on9i** [DefinitelyTyped/DefinitelyTyped#47785]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

@arcticwaters @vesse @ianldgs

I've got a problem with @types/bookshelf.

I've used latest bookshelf package with the latest knex.
The latest knex has its own types and bookshelf.js does not, so I've installed @types/bookshelf.
However, the error is shown when i use the bookshelf with knex such as the below.

```
Argument of type 'import("D:/a/prog/nodejs/jprice/node_modules/knex/types/index")<any, unknown[]>' is not assignable
 to parameter of type 'import("D:/a/prog/nodejs/jprice/node_modules/@types/bookshelf/node_modules/knex/types/index")<any, unknown[]>'.
  Types of property 'raw' are incompatible.
    Type 'import("D:/a/prog/nodejs/jprice/node_modules/knex/types/index").RawBuilder<any, any>' is not assignable to type 'import("D:/a/prog/nodejs/jprice/node_modules/@types/bookshelf/node_modules/knex/types/index").RawBuilder<any, any>'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'import("D:/a/prog/nodejs/jprice/node_modules/@types/bookshelf/node_modules/knex/types/index").Value' is not assignable to 
type 'import("D:/a/prog/nodejs/jprice/node_modules/knex/types/index").Value'.
          Type 'Raw<any>' is not assignable to type 'Value'.
            Property 'timeout' is missing in type 'import("D:/a/prog/nodejs/jprice/node_modules/@types/bookshelf/node_modules/knex/types/index").Raw<any>' but required in type 'import("D:/a/prog/nodejs/jprice/node_modules/knex/types/index").Raw<any>'.
```

### the cause
I've tried figure out and I have found the answer.

The cause is that the @types/bookshelf installed the its own knex package for its own `require('knex')`. After I deleted the `node_modules` in @type/bookshelf, the error had been gone.

Thus, I think the @types/bookshelf installs its own knex package because the version of knex in package.json is different from my project's knex version.
(I've used the latest knex version, which is `0.21.5`)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
