### ISSUE TITLE
[@types/react]Cannot use extended generic type in React.ComponentClass's props

### ISSUE THREAD

**Issue by icy0307** [DefinitelyTyped/DefinitelyTyped#47824]
React version:
@types/react@16.9.49
@types/prop-types@15.7.3
ts version 4.0.2
## Steps To Reproduce

~~~typescript
import React from 'react';
interface A {
    a: number;
}


function foo(param: React.ComponentClass<A>) {
    return param;
}

function foobar<T extends A >(param: React.ComponentClass<T>) {
    foo(param);
}

~~~

Link to code example:

https://www.typescriptlang.org/play?target=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKGADsYkpN0k4BBOAbyrh7hQC44NAK4gARgwqUAvlTmVMwmhmAQacTBAgAKMCigoQg5OhgA6AMK5INJHQsAbFAGdnAHlYA+AJSduvIhhhKHU9AxApWUoqRWUYVXUxfTcAFTgkAA96GgATZzZPXX1DY2JzK3A1OxhHF3cUnz9KXg0tIvDvSKogA

## The current behavior

`Argument of type 'ComponentClass<T, any>' is not assignable to parameter of type 'ComponentClass<A, any>'.
  Types of property 'propTypes' are incompatible.
    Type 'WeakValidationMap<T> | undefined' is not assignable to type 'WeakValidationMap<A> | undefined'.
      Type 'WeakValidationMap<T>' is not assignable to type 'WeakValidationMap<A>'.
        Types of property 'a' are incompatible.
          Type '(null extends T["a"] ? Validator<T["a"] | (T["a"] & null) | undefined> : undefined extends T["a"] ? Validator<T["a"] | (T["a"] & undefined) | null> : Validator<T["a"]>) | undefined' is not assignable to type 'Validator<number> | undefined'.
            Type 'null extends T["a"] ? Validator<T["a"] | (T["a"] & null) | undefined> : undefined extends T["a"] ? Validator<T["a"] | (T["a"] & undefined) | null> : Validator<T["a"]>' is not assignable to type 'Validator<number> | undefined'.
              Type 'Validator<T["a"] | (T["a"] & null) | undefined> | (undefined extends T["a"] ? Validator<T["a"] | (T["a"] & undefined) | null> : Validator<T["a"]>)' is not assignable to type 'Validator<number> | undefined'.
                Type 'Validator<T["a"] | (T["a"] & null) | undefined>' is not assignable to type 'Validator<number>'.
                  Type 'T["a"] | (T["a"] & null) | undefined' is not assignable to type 'number'.
                    Type 'undefined' is not assignable to type 'number'.
                      Type 'null extends T["a"] ? Validator<T["a"] | (T["a"] & null) | undefined> : undefined extends T["a"] ? Validator<T["a"] | (T["a"] & undefined) | null> : Validator<T["a"]>' is not assignable to type 'Validator<number>'.
                        Type 'Validator<T["a"] | (T["a"] & null) | undefined> | (undefined extends T["a"] ? Validator<T["a"] | (T["a"] & undefined) | null> : Validator<T["a"]>)' is not assignable to type 'Validator<number>'.
                          Type 'Validator<T["a"] | (T["a"] & null) | undefined>' is not assignable to type 'Validator<number>'.
                            Type 'T["a"] | (T["a"] & null) | undefined' is not assignable to type 'number'.
                              Type 'undefined' is not assignable to type 'number'.`
## The expected behavior
`param: React.ComponentClass<T extends A>` can assign to React.ComponentClass<A>`

Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:  @johnnyreilly @ferdaber 

If you do not mention the authors the issue will be ignored.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
