### ISSUE TITLE
Definition request: koa (2nd generation of express.js, gh-stars = 6,500)

### ISSUE THREAD

**Issue by Cyberider** [DefinitelyTyped/DefinitelyTyped#4796]
https://github.com/koajs/koa

There is also the main add-on that goes with it:
https://github.com/alexmingoia/koa-router

I'm new to JS and TS, so for now I can't create definitions, otherwise I would gladly do it and contribute...I'm sorry!

**Comment by xmlking** [comment]
+1

**Comment by xmlking** [comment]
I had to create `typings/koa-router.d.ts`  for my project.  it is not complete but at least have something to silence typescript compiler errors ;)

 https://github.com/xmlking/koa-router-decorators

```typescript
declare module 'koa-router' {

  export default class Router {
    params: Object;
    constructor({prefix: string}?);

    use(path: string, middleware): Router;
    prefix(prefix: string): Router;
    redirect (source: string, destination: string, code: number): Router;
    all(name: string, path: string, middleware: Function): Router;
    param(param, middleware): Router;
    allowedMethods(options: Object): Function;
    url(name: String, params: Object): string;
  }
}
```

**Comment by mlegenhausen** [comment]
+1

**Comment by Axure** [comment]
+1

**Comment by plantain-00** [comment]
+1

**Comment by buzinas** [comment]
+1

**Comment by iluuu1994** [comment]
:+1:

**Comment by jacobdr** [comment]
+1

**Comment by b3njamin** [comment]
:+1:

**Comment by jsdream** [comment]
+1

**Comment by DavidCai1993** [comment]
+1

**Comment by codeBelt** [comment]
+1

**Comment by codeartch** [comment]
A draft i made a while ago for personal use. So dont expect too much.
https://github.com/codeartch/KoaTypings

 Feel free to give me feedback.

**Comment by johnnyoshika** [comment]
+1

**Comment by lucasmciruzzi** [comment]
+1

**Comment by infloop** [comment]
+1

**Comment by lucasmciruzzi** [comment]
I'm working on this, the next week I'll try to have it done.

**Comment by theosherman** [comment]
+1

**Comment by pe8ter** [comment]
@Cyberider These typings exist. Can close.

**Comment by suttang** [comment]
+1

**Comment by mhegazy** [comment]
`@types/koa` ?

**Comment by pe8ter** [comment]
@Cyberider This is your Issue. You can close it.
