### ISSUE TITLE
Definition Request: NightwatchJS

### ISSUE THREAD

**Issue by GrayedFox** [DefinitelyTyped/DefinitelyTyped#4801]
Hey there Boris,

I would LOVE you to do [NighwatchJS](http://nightwatchjs.org/). I've been trying and trying to get autocomplete to properly work for this (by adding the library manually and updating node stuff) but I get about 1/3 of the functions/methods defined and the others are lost in the abyss.

Will offer reward for your time - happy to pass 30 euro for a fully integrated autocomplete for PhPstorm for Nightwatch. Not sure if that's a fair reflection of time it may require - open to discussions!

**Comment by Seltzer** [comment]
Hey,

I'm most of the way through writing bindings for the API as described [here](http://nightwatchjs.org/api). I'm pretty busy at the moment, but I'll push my progress to my fork in a couple of days so that you can take a look.

Cheers,
Nathan

**Comment by GrayedFox** [comment]
Ah. Mazing. Thank you !!! :laughing:

**Comment by jalami** [comment]
:+1:

**Comment by rkavalap** [comment]
@GrayedFox @Seltzer 
https://github.com/rkavalap/NightWatchTest/blob/master/typings/nightwatch/nightwatch.d.ts

**Comment by GrayedFox** [comment]
@rkavalap legend, thank you

**Comment by christofur** [comment]
For those still looking, there are some here: https://github.com/types/npm-nightwatch/blob/master/nightwatch.d.ts
