### ISSUE TITLE
[@types/xrm] control.setDisable() property is missing

### ISSUE THREAD

**Issue by existomwasilewski** [DefinitelyTyped/DefinitelyTyped#48126]
Hi,

Property setDisable and getDisable are missing in control.

` Xrm.Page.data.entity.attributes.forEach(function (attribute, index) {
                var control = Xrm.Page.getControl(attribute.getName());
                if (control && control.setDisable != 'undefined') { 
                    control.setDisable(true)
                }	
});`

In this code I am occuring error in  lane:
`control.setDisable(isDisabled)`

'TS2339: (TS) Property "setDisable" not exist in type of "control"'

But if I add this code in compiled JS file and import it to the D365 all is working fine. 

Authors: @6ix4our @scottdurow  @markusmauch  @daryllabar  @clownwilleatme

**Comment by daryllabar** [comment]
You've got a couple problems with your code.  First off, the return type of getControl is `Controls.Control`  This is the most generic control type which doesn't support the disable functions, and their for why you get a compile error.  You should cast the control type (there is a generic function for this `getControl<T extends Controls.Control>` to be able to easily apply this cast) to the Standard Control (or even the UiCanSetDisabledElement).

Secondly, the name of the control does not have to match the attribute name, (and there may be more than one control per attribute) so you should be looping through the attribute.controls collection.

Hope that helps!
