### ISSUE TITLE
Recent typings changes not appearing for latest version of puppeteer-core

### ISSUE THREAD

**Issue by thomassuckow** [DefinitelyTyped/DefinitelyTyped#48162]
Puppeteer-core types which are identical to puppeteer types are lagging far behind recent changes. Is is possible to alias the types so only one of them has to be updated?

If not, is it safe to merely copy all the files from puppeteer and make a PR for puppeteer-core?

@marvinhagemeister
@cdeutsch
@ksm2
@SimonSchick
@SerbanGhita
@JasonKaz
@davecardwell
@angrykoala
@peterblazejewicz
@okko

**Comment by okko** [comment]
According to https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteer-vs-puppeteer-core they should be the same thing with and without a browser download, so they should share the same API. It sounds like a good idea to alias puppeteer-core to puppeteer.

I have not used the puppeteer-core version, though. We should wait for someone else to confirm or to object.

**Comment by G-Rath** [comment]
`puppeteer-core` is already aliased:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d977155650b90a89e47d24262c285ea92cc5020e/types/puppeteer-core/index.d.ts#L1-L7

While it says v2 in the comment at the top, it's just a comment - the types don't specify any specific version of puppeteer anywhere. You might find that a package is pulling in an old version of `@types/puppeteer`, which you can fix by specifying the types as a dependency in your `package.json`.

**Comment by thomassuckow** [comment]
I'd swear I looked in the typings in puppeteer-core but must have been blind.

I'm wondering if the issue I am encountering is actually from the puppeteer repo. All the recent changes are against the v2 folder but the index.d.ts in the root of puppeteer is lacking those changes. (Do these v# folders magically apply to older versions? I can only find vague references to it in the DefinatelyTyped readme)

I ended up copying the root files into my project and making the changes. I'm working on the Google CLA to fix some typings in puppeteer itself, shame they aren't exposing them. Once I'm more confident in the changes I've made I might see about updating them here.

**Comment by thomassuckow** [comment]
I restored @types/puppeteer-core and it installed @types/puppeteer 3.0.2 but still doesn't have `page.waitForTimeout` . I see that it was added to the v2 folder, I'm guessing it should also be added to the root types file. I can see about making a PR for that if someone tell me that is where types for Puppeteer 5 belong.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
