### ISSUE TITLE
`@types/node`: `assert.strict.equal` should not be deprecated

### ISSUE THREAD

**Issue by rauschma** [DefinitelyTyped/DefinitelyTyped#48253]
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Flarna, @SimonSchick, @Semigradsky, @rbuckton, @mjbvz, @G-Rath, @sandersn 

* `assert.strict.equal` should not be deprecated: https://nodejs.org/dist/latest-v14.x/docs/api/assert.html#assert_assert_equal_actual_expected_message
* The problem is that `assert.strict` uses `typeof assert` here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/assert.d.ts

<img width="568" alt="definitely typed assert bug" src="https://user-images.githubusercontent.com/526114/94362580-a5c5fe00-00bc-11eb-971c-1146a22755b8.png">

**Comment by G-Rath** [comment]
But it is deprecated...?

![Screenshot_2020-09-27-23-39-49-344_com.android.chrome.jpg](https://user-images.githubusercontent.com/3151613/94362906-d3419480-011a-11eb-962f-6d0763d28014.jpg)


(I'm on mobile so might have missed something 🙂)

**Comment by rauschma** [comment]
@G-Rath: Very easy to miss indeed! I had to check again just now.

**Comment by G-Rath** [comment]
Unfortunately there's not a lot we can do here without maybe cloning the whole type?

I would recommend just using the explicitly strict version, as my understanding is that that's the preference now anyway (which is why all non-stict methods were deprecated)

**Comment by rauschma** [comment]
Can deprecations be removed via mapped types somehow?

> I would recommend just using the explicitly strict version, as my understanding is that that's the preference now anyway (which is why all non-stict methods were deprecated)

I don’t think that’s the case – [Node.js v15 will have `assert/strict`](https://nodejs.org/download/nightly/v15.0.0-nightly20200927af92317909/docs/api/assert.html#assert_strict_assertion_mode). I suspect that that will eventually become the new standard – along with the shorter method names. If `strictEqual` were enough/preferred, they wouldn’t have had to create that module.

**Comment by Flarna** [comment]
I guess the only solution is duplication. Not sure if it is possible to duplicate only the effected APIs or if it is needed to duplicate the whole assert module.

**Comment by Semigradsky** [comment]
Possible solution:
```ts
		const strict: typeof assert & {
            deepEqual: typeof assert.deepStrictEqual;
            notDeepEqual: typeof assert.notDeepStrictEqual;
            equal: typeof assert.strictEqual;
            notEqual: typeof assert.notStrictEqual;
        };
```

I can send PR but the tests are failing now: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48257
