### ISSUE TITLE
Expose SystemError, error.syscall, error.code, etc. to @types/node

### ISSUE THREAD

**Issue by pubmikeb** [DefinitelyTyped/DefinitelyTyped#48281]
- [X] I tried using the `@types/node` package and had problems.
- Authors: @victorperin, @Touffy, @n-e, et al.

Initially, I've opened an issue at Node.js (https://github.com/nodejs/node/issues/35402), but they pointed me to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) project.

**Is your feature request related to a problem? Please describe.**
In `www.mjs` module I have a function `_onError(error)` which handles Node.js errors, e.g.: [`SystemError`](https://nodejs.org/api/errors.html#errors_class_systemerror), [`error.syscall`](https://nodejs.org/api/errors.html#errors_error_syscall), [`error.code`](https://nodejs.org/api/errors.html#errors_error_code_1), etc..

To improve the IDE's (IntelliJ IDEA / WebStorm) the JS code inspection, I wanted to annotate the JS code with JSDoc. Unfortunately, the [`SystemError`](https://nodejs.org/api/errors.html#errors_class_systemerror), [`error.syscall`](https://nodejs.org/api/errors.html#errors_error_syscall), [`error.code`](https://nodejs.org/api/errors.html#errors_error_code_1) types are not exposed to outside via `@types/node`, which means IDEA can't recognize these types in my JSDoc and marks the code with warning "Unresolved variable":

![21_215048](https://user-images.githubusercontent.com/17231333/94471199-0a6e7f00-01c9-11eb-8e97-acf32446d3fc.png)

![21_215143](https://user-images.githubusercontent.com/17231333/94471206-0b9fac00-01c9-11eb-9455-d85959793591.png)

![22_081646](https://user-images.githubusercontent.com/17231333/94471210-0cd0d900-01c9-11eb-83da-c702f4e8e34a.png)

**Describe the solution you'd like**
To expose [`SystemError`](https://nodejs.org/api/errors.html#errors_class_systemerror), [`error.syscall`](https://nodejs.org/api/errors.html#errors_error_syscall), [`error.code`](https://nodejs.org/api/errors.html#errors_error_code_1), etc. via `@types/node`, so IDE is aware about these types and inspect the code in a more proper way.

**Describe alternatives you've considered**
Of course, I can define custom types but since these types are a part of Node.js, it would be better to provide this functionality out-of-box.

The same is relevant for the other Node.js's [common system errors](https://nodejs.org/api/errors.html#errors_common_system_errors), I want the IDE could recognize them and I could use them in my JSDoc.

P.S. Initially, I assumed it is an IDEA issue, so I opened a ticket there: https://youtrack.jetbrains.com/issue/WEB-47505, but WebStorm team respond that the «bottle neck» is in the Node.js's `@types/node`.

**Comment by Semigradsky** [comment]
Typings have `NodeJS.ErrnoException` type:
```ts
    interface ErrnoException extends Error {
        errno?: number;
        code?: string;
        path?: string;
        syscall?: string;
        stack?: string;
    }
```
Looks like error type should be `NodeJS.ErrnoException` instead of `SystemError`.

**Comment by pubmikeb** [comment]
@Semigradsky, great, thanks a lot.
I've tried to use `NodeJS` but definitely should make one step further and try `NodeJS.ErrnoException` as well.

**Comment by edwardgalligan** [comment]
Commenting here for posterity for Googlers finding this issue. The above comment isn't correct.

> Looks like error type should be NodeJS.ErrnoException instead of SystemError.

I'm not sure what the `NodeJS.ErrNoException` is but it doesn't map to anything defined in NodeJS - `SystemError` is an actual NodeJS error type (& as such should ideally be typed in `@types/node`).

Notably the interfaces for `NodeJS.ErrNoException` & `SystemError` are differing in that it's missing 5 properties:

```
interface SystemError {
    address: string;
    code: string;
    dest: string;
    errno: number;
    info: { [k: string]: any; }
    message: string;
    path: string;
    port?: number;
    syscall: string;
}
```

For extra posterity, there's more discussion of this here: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64508

**Comment by sdavids** [comment]
This should be reopened.

https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64508#discussioncomment-12436031
