### ISSUE TITLE
@types/detox type check fails because of expect being already defined

### ISSUE THREAD

**Issue by Andarius** [DefinitelyTyped/DefinitelyTyped#48309]
When running `tsc -p .`, it fails with the following errors

```
$ tsc -p .
node_modules/@types/detox/index.d.ts:15:11 - error TS2451: Cannot redeclare block-scoped variable 'expect'.

15     const expect: Detox.Expect<Detox.Expect<Promise<void>>>;
             ~~~~~~

  node_modules/@types/jest/index.d.ts:47:15
    47 declare const expect: jest.Expect;
                     ~~~~~~
    'expect' was also declared here.

node_modules/@types/jest/index.d.ts:47:15 - error TS2451: Cannot redeclare block-scoped variable 'expect'.

47 declare const expect: jest.Expect;
                 ~~~~~~

  node_modules/@types/detox/index.d.ts:15:11
    15     const expect: Detox.Expect<Detox.Expect<Promise<void>>>;
                 ~~~~~~
    'expect' was also declared here.


Found 2 errors.
```

Would it be possible to fix it by defining a definition file like this https://github.com/Andarius/DefinitelyTyped/commit/1b07f033ad1b3c2bfd6566c926b11222a87e2676 instead of global and then in tests using `import { by, device, element } from 'detox'`

Thanks !

@TareqElMasri 
@stevechun 
@hammadj 
@santiagofm 
@maxkomarychev 
@Dor256

**Comment by Dor256** [comment]
@Andarius

As far as I know TS doesn't recognize that global definition so what you have to do is import those anyway.

Try importing 
`expect` from detox and then compiling

**Comment by Andarius** [comment]
Hey @Dor256 , it's why I'm doing currently, but it fails due to `expect` already being defined by jest.

**Comment by saihaj** [comment]
I am having the same issue.  Other than `"skipLibCheck": true` to `tsconfig.json` is there a better way to resolve this issue?

**Comment by Andarius** [comment]
@saihaj, TS types are now part of the Detox library as for this release https://github.com/wix/Detox/releases/tag/18.1.0
