### ISSUE TITLE
@types/dygraphs is deprecated

### ISSUE THREAD

**Issue by pacocom** [DefinitelyTyped/DefinitelyTyped#48302]
Need https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/dygraphs @types for https://github.com/danvk/dygraphs

Thanks.

Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by BrkCoder** [comment]
Hey I would love to help and update this types for dygraphs, @pacocom  is this issue still relevant?
