### ISSUE TITLE
[styled-components] styled component is any

### ISSUE THREAD

**Issue by bartoszkrawczyk2** [DefinitelyTyped/DefinitelyTyped#48325]
- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @lavoaster @Jessidhia @jkillian @eps1lon @flavordaaave @wagerfield @Lazyuki @mgoszcz2 @danilofuchs

Hi,

I think I found a bug. Styled components have type any and all autocompletion and type checking of props is not working.

<img width="432" alt="Zrzut ekranu 2020-09-29 o 23 24 18" src="https://user-images.githubusercontent.com/7081383/94618405-63164880-02ab-11eb-9575-e5d4fbe9d334.png">
<img width="346" alt="Zrzut ekranu 2020-09-29 o 23 37 27" src="https://user-images.githubusercontent.com/7081383/94619214-c94f9b00-02ac-11eb-8221-113092d2c1c1.png">

But it looks like that type definitions are correctly loaded:
<img width="694" alt="Zrzut ekranu 2020-09-29 o 23 32 21" src="https://user-images.githubusercontent.com/7081383/94619110-960d0c00-02ac-11eb-9984-7a58cfe3d323.png">

versions:
"@types/styled-components": "^5.1.3",
"typescript": "4.0.3",
"@types/react": "^16.9.49",

**Comment by Ryan-Willpower** [comment]
Do you have any reproduce version of this bug?

**Comment by bartoszkrawczyk2** [comment]
I couldn't create a clean project to reproduce it. After 2 days it turned out to be a problem with dependencies in my project. The issue can be closed.

**Comment by andras-hegedus** [comment]
> I couldn't create a clean project to reproduce it. After 2 days it turned out to be a problem with dependencies in my project. The issue can be closed.

Hey @bartoszkrawczyk2 ! I have the same problem and can't figure out the cause. Can you tell me what was the problem with the dependencies? Was it a local module, a specific import, or a TS config maybe?

**Comment by matthieugicquel** [comment]
@andras-hegedus Take a look at [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33690#issuecomment-732774987), this is how I fixed a similar problem

**Comment by andras-hegedus** [comment]
> 
> 
> @andras-hegedus Take a look at [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33690#issuecomment-732774987), this is how I fixed a similar problem

Thanks @matthieugicquel , I think our problem was quite similar, but it wasn't connected to the package you mentioned in [the issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33690#issuecomment-732774987).

Some package update we could not pinpoint fixed it.
