### ISSUE TITLE
Maintaining a types package outside of DT

### ISSUE THREAD

**Issue by tpluscode** [DefinitelyTyped/DefinitelyTyped#48399]
There is a package in DT (`@types/rdf-js`) which does not provide types for an NPM package but instead is a reflection of a W3C RDF/JS Working Group specifications.

That Working Group is now discussing (https://github.com/rdfjs/types/issues/1) to have more control on the authoring and publishing process of those typings more closely, with move visibility to other members of said group.

The proposal is to remove `@types/rdf-js` and instead publish package(s) under the `@rdfjs/` scope.

There are a some questions we would like answered:

1. Will those types packages be seamlessly usable within projects just like `@types/rdf-js`?

    I expect implementors would simply `import { X } from "@rdfjs/types"`

2. How will this affect DT package which currently depend on `@types/rdf-js`?

**Comment by orta** [comment]
1: Yes, that work ( you can use the `"types"` field in the package.json to specify the root of your d.ts files)
2: There is a process for [deprecating a types module](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package) - but you'll need to let people know they should switch 👍🏻

**Comment by tpluscode** [comment]
Thank you. In fact, I figure that we could publish a types-only `rdf-js` package. In fact it already exists but we replaced it with `@types/rdf-js` in the past. Go figure. This way no changes will be required anywhere that people already have `import {} from 'rdf-js'`, correct?

About deprecating, I read that it will be necessary to add all DT packages which depend on `@types/rdf-js` to DefinitelyTyped-tools? And any future such package?
