### ISSUE TITLE
Objects within an object for MongoDB query not accepted by @types/mongoose

### ISSUE THREAD

**Issue by Kinetix-Lee** [DefinitelyTyped/DefinitelyTyped#48401]
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

I've just experienced a problem while using `@types/mongoose`. 

The second parameter for method `Model.updateOne(filter, doc)` should accept objects within an object (such as `{ $inc: { count: 1 } }`), however its typing doesn't allow this widely-used usage. 

Mainly-related code:

```
const update = {
  $inc: {
    count: increment,
  },
};
await ctx.model.AccessStats
  .updateOne({ uri }, update)
  .catch((err: any) => { throw err });
```

Console error output: 

```
     TSError: [egg-core] load file: F:\GitHub\kdev-api\app\service\accessStats.ts, error: ⨯ Unable to compile TypeScript:
app/service/accessStats.ts(70,31): error TS2345: Argument of type '{ $inc: { count: number; }; }' is not assignable to parameter of type 'MongooseUpdateQuery<Pick<any, string | number | symbol>>'.
  Type '{ $inc: { count: number; }; }' is not assignable to type 'UpdateQuery<Pick<any, string | number | symbol>>'.
    Types of property '$inc' are incompatible.
      Type '{ count: number; }' is not assignable to type 'OnlyFieldsOfType<Pick<any, string | number | symbol>, number | undefined, number | undefined>'.
        Type '{ count: number; }' is not assignable to type 'NotAcceptedFields<Pick<any, string | number | symbol>, number | undefined>'.
          Property 'count' is incompatible with index signature.
            Type 'number' is not assignable to type 'undefined'.
```

Mainly-related packages: `@types/mongoose` `egg-mongoose`

- Authors: @rnbrady @lmichelin @federico-dondi @pedroprado010 @orblazer @andreialecu @Sina7312 @various89 ...

**Comment by andreialecu** [comment]
This does work properly in many of my own projects, without any error. I cannot reproduce this.

**Comment by Kinetix-Lee** [comment]
> This does work properly in many of my own projects, without any error. I cannot reproduce this.

I don't think that PR was the right fix either (because nobody mentioned the same question), but it worked for me...

Could this model file help?

```
// app/model/AccessStats.ts
export default app => {
  const { mongoose } = app;
  const { Schema } = mongoose;
  const AccessStatsSchema = new Schema({
    uri: {
      type: String,
    },
    count: {
      type: Number,
    },
  }, {
    writeConcern: {
      w: 0,
      j: false,
    },
  });

  return mongoose.model('access_stats', AccessStatsSchema);
};

```

**Comment by andreialecu** [comment]
I think your problem is that you are not specifying the actual schema:

```ts
interface AccessStatsSchema {
  type: string;
  count: number;
}

export default app => {
  const { mongoose } = app;
  const { Schema } = mongoose;
  const AccessStatsSchema = new Schema({
    uri: {
      type: String,
    },
    count: {
      type: Number,
    },
  }, {
    writeConcern: {
      w: 0,
      j: false,
    },
  });

  return mongoose.model<AccessStatsSchema>('access_stats', AccessStatsSchema);
};
```

You may also want to look into https://github.com/typegoose/typegoose which might make working with mongoose and typescript easier for you.

**Comment by Kinetix-Lee** [comment]
> I think your problem is that you are not specifying the actual schema:
> 
> ```ts
> interface IAccessStatsSchema {
>   type: string;
>   count: number;
> }
> 
> export default app => {
>   const { mongoose } = app;
>   const { Schema } = mongoose;
>   const AccessStatsSchema = new Schema({
>     uri: {
>       type: String,
>     },
>     count: {
>       type: Number,
>     },
>   }, {
>     writeConcern: {
>       w: 0,
>       j: false,
>     },
>   });
> 
>   return mongoose.model<IAccessStatsSchema>('access_stats', AccessStatsSchema);
> };
> ```
> 
> You may also want to look into https://github.com/typegoose/typegoose which might make working with mongoose and typescript easier for you.

Thanks for your reply! 

However it popped out a new error which says "Untyped function calls may not accept type arguments."

Here's the code: 

```
// app/model/AccessStats.ts
interface IAccessStatsSchema {
  uri: string;
  count: number;
}

export default (app) => {
  const { mongoose } = app;
  const { Schema } = mongoose;
  const AccessStatsSchema = new Schema({
    uri: {
      type: String,
    },
    count: {
      type: Number,
    },
  }, {
    writeConcern: {
      w: 0,
      j: false,
    },
  });

  return mongoose.model<IAccessStatsSchema>('access_stats', AccessStatsSchema);
};
```

By the way, I've been trying typegoose for a couple of times, but it was the same error.

**Comment by Kinetix-Lee** [comment]
Project which is having this trouble runs the latest **Egg.js** framework, with TypeScript support. 

Related npm packages: `egg-mongoose` `@types/mongoose` `mongoose`

**Comment by andreialecu** [comment]
Your `app` parameter has no type so it becomes `any`. You're destructuring `mongoose` from it, so it will also be of type `any`. You're then running into this problem: https://stackoverflow.com/questions/48228735/untyped-function-calls-may-not-accept-type-arguments-angular-5-http-calls

In general, you're not really using TypeScript properly. I would try to refactor things to properly use types as a first step.

Try something like this:

```ts
import * as mongoose from 'mongoose';

interface IAccessStatsSchema {
  uri: string;
  count: number;
}

export default () => {
  const AccessStatsSchema = new mongoose.Schema({
    uri: {
      type: String,
    },
    count: {
      type: Number,
    },
  }, {
    writeConcern: {
      w: 0,
      j: false,
    },
  });

  return mongoose.model<IAccessStatsSchema>('access_stats', AccessStatsSchema);
};
```

If you need to pass a `mongoose` instance around, you're probably looking for `mongoose.Connection`.

**Comment by Kinetix-Lee** [comment]
Thanks @andreialecu , egg-mongoose makes connections for me, thus no need to connect manually. 

However, I tried `@typegoose/typegoose` just now and found the following error: 

`app/service/Test.ts(15,39): error TS2322: Type 'number' is not assignable to type 'undefined'.`

It's basically the same as previous ones. 

Additionally, I've tested other `doc` values than `{ $inc: { count: increment } }`, such as `{ $inc: 1 }`, it doesn't pass; `{ $inc: {} }` passes the check instead. That's kind of weird...

**Comment by andreialecu** [comment]
If you can create a small repro repository I could take a look for you.

**Comment by Kinetix-Lee** [comment]
> If you can create a small repro repository I could take a look for you.

If you would like to, it's now ready on [https://github.com/Kinetix-Lee/egg-mongoose-ts-test](GitHub).

(English is not my native language. If there's any non-proper language because of my English level, please forgive. )

**Comment by Kinetix-Lee** [comment]
`config/config.local.js` contains MongoDB credentials. 
`app/model` folder contains Mongoose models. 
`app/service/Test.ts` calls the model.

**Comment by andreialecu** [comment]
Your problem is that you have `count: string` when it should be `number`

**Comment by Kinetix-Lee** [comment]
> Your problem is that you have `count: string` when it should be `number`

That was one point, but after correction the type error remained.

**Comment by Kinetix-Lee** [comment]
Change L189 in `@types/mongoose/index.d.ts`

```ts
export type UpdateQuery<D> = MongooseUpdateQuery<DocumentDefinition<D>>;
```

 into

```ts
export type UpdateQuery<D> = MongooseUpdateQuery<DocumentDefinition<D>> | object;
```

Is a workaround, but I don't understand why MongooseUpdateQuery didn't accept `object`.

**Comment by Kinetix-Lee** [comment]
It seems weird that properties of `$inc` only accept `undefined` type. @andreialecu 

```
     TSError: [egg-core] load file: F:\GitHub\test\app\service\Test.ts, error: ⨯ Unable to compile TypeScript:
app/service/Test.ts(15,39): error TS2322: Type 'number' is not assignable to type 'undefined'.
```

**Comment by andreialecu** [comment]
I don't know anything about the `egg` framework you're using, but the following is a problem:

![image](https://user-images.githubusercontent.com/697707/94898848-e34ed080-049a-11eb-88de-3467b0ffa437.png)

That shouldn't be `Model<any, ...>`. The problem is in `egg-mongoose/index.d.ts` where this is defined:

![image](https://user-images.githubusercontent.com/697707/94899024-358ff180-049b-11eb-8e80-847fe9a2e173.png)

(`any` shouldn't be there)

It seems that `egg` libraries themselves are in what seems to be early stages of TypeScript support.

You can see what I mean by replacing your service class with this code, which will make things work:

```ts
import { Service } from "egg";
import TestModel from "../model/Test";

/**
 * Test Service
 */
export default class Test extends Service {
  /**
   * sayHi to you
   * @param name - your name
   */
  public async sayHi(name: string) {
    let id = 0;
    await (this.ctx.model.Test as ReturnType<typeof TestModel>)
      .updateOne({ id: 0 }, { $inc: { count: 1 } })
      .then((resolve: any) => {
        id = resolve[0].id;
      });
    return `${id}, ${name}`;
  }
}
```

**Comment by andreialecu** [comment]
Regarding the error:
> `TSError: [egg-core] load file: F:\GitHub\test\app\service\Test.ts, error: ⨯ Unable to compile TypeScript:
app/service/Test.ts(15,39): error TS2322: Type 'number' is not assignable to type 'undefined'.`

The technical reason why you're seeing it in the first place is because the typings are trying to be smart and only list `number` fields in `$inc`. But since your entire model is of type `any`, there are no `number` fields it knows about.

Here's how the type looks when you're not using `any`:
```
(property) $inc?: OnlyFieldsOfType<Pick<DocumentType<Test>, "_id" | "count" | "typegooseName">, number | undefined, number | undefined> | undefined
```
So it picks all properties that are of type number, in this case there is only one, and that is `count`. And you can also see it in autocomplete here:

![image](https://user-images.githubusercontent.com/697707/94899953-e054df80-049c-11eb-909c-35737e7a4c2e.png)

Here's how it looks with `any`:
```
(property) $inc?: OnlyFieldsOfType<Pick<any, string | number | symbol>, number | undefined, number | undefined> | undefined
```
Nothing can properly be picked from this type.

**Comment by Kinetix-Lee** [comment]
I got it. You've made a great workaround. It works! 
By the way, would you like to [contribute](https://eggjs.org/en/contributing.html) to `egg-mongoose`'s [TS support](https://github.com/eggjs/egg-mongoose/blob/master/index.d.ts)?

**Comment by Kinetix-Lee** [comment]
Thank @andreialecu again for his help!

**Comment by rambabusaravanan** [comment]
Thanks @andreialecu,  for finding the technical reason.

Do we have any workarounds for using `any` type in `$inc` operator?
If not, may I know why this is closed @Kinetix-Lee
