### ISSUE TITLE
[@types/node] npm test failure

### ISSUE THREAD

**Issue by dhrumilrana** [DefinitelyTyped/DefinitelyTyped#48515]
Used @type/node (node v14.12.0, v12.8.4) and `npm test` fails in the following way:

```
> definitely-typed@0.0.3 test .../projects/learn/DefinitelyTyped
> dtslint types

Error: ENOENT: no such file or directory, open '.../projects/learn/DefinitelyTyped/types/index.d.ts'
```

This fails on both linux and Mac systems with the mentioned node versions (have not tried on a Windows system).

It can be reproduced with:
```
git clone https://github.com/DefinitelyTyped/DefinitelyTyped.git
cd DefinitelyTyped
npm i
npm test
```

I didn't find this issue reported, so wondering if it's expected/known or an issue with my environment or Node.js version.
Thanks in advance.

Authors:  @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon @zieka @dancerphil @dimitropoulos @disjukr @vhfmag @hellatan

**Comment by BrenekH** [comment]
I was having this issue as well and it turns out for `npm test` a package needs to be specified (`npm test <package name>`). [relevant documentation](https://github.com/DefinitelyTyped/DefinitelyTyped#running-tests)
