### ISSUE TITLE
@types/yup How to resolve Yup.lazy arrays

### ISSUE THREAD

**Issue by patelrikin** [DefinitelyTyped/DefinitelyTyped#48524]
I am facing type issues with upgrading to latest @types/yup package and having difficulty on how should I have Array resolve to empty array. This error only happens if using `Yup.lazy` to return `Yup.object` which returns `undefined` as possible value.

Here's the simplified example:

```
interface A {
  strArr: string[];
  reqString: string;
  optionalNumber?: number;
  optionalNullableNumber?: number | null;
}
```

```
export const schema = Yup.lazy((value: A | undefined) => { // If I dont use `| undefined` then I get: -->  Type 'undefined' is not assignable to type 'A'.
  return Yup.object<A>().shape({
    strArr: Yup.array().of(Yup.string()).required(), // Type '(string | undefined)[] | undefined' is not assignable to type 'string[]'.
    reqString: Yup.string().required('Message'),
    optionalNumber: Yup.number().nullable(true), // Type 'number | null | undefined' is not assignable to type 'number | undefined'.
    optionalNullableNumber: Yup.number().nullable(true),
  });
});
```

- [x] I tried using the `@types/yup` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ejose19 and @iansan5653

PR #44589 https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b6a0ab604c73f27e860cc88d3a60d6b87e80d245#diff-4399881e5520c19aa7b6e59a9aac0ca9R333 updated `undefined` as return value of `Yup.Object`.

**Comment by ejose19** [comment]
@patelrikin This is not an issue with yup definitions, remember those kinds of questions are more tailored to StackOverflow (as mentioned in the template)

Correct schema:
```ts
export const schema = Yup.lazy((value: A) => {
  return Yup.object<A>()
    .shape({
      strArr: Yup.array().of(Yup.string().required()).required(),
      reqString: Yup.string().required('Message'),
      optionalNumber: Yup.number() //If null is really intended here, then you need to add null to the interface property,
      optionalNullableNumber: Yup.number().nullable(true),
    })
    .required();
});
```

**Comment by patelrikin** [comment]
@ejose19 Thank you for responding, I just wanted to make sure PR #44589 added `undefined` as possible return type of `Yup.object` which was intended or not thus posted here.

In terms of the solution that you gave `strArr: Yup.array().of(Yup.string().required()).required()` how should that be treated if an empty array is sufficient for `strArr: string[];`. 

Is `strArr: Yup.array().of(Yup.string().required()).defined().ensure()` way to go?

**Comment by ejose19** [comment]
@patelrikin Well I'm not the author of that PR, but it seems logical since it makes typescript being more strict and hence more accurate. Regarding the array, if you want an empty array to be valid, then either what you proposed or changing the .ensure for a .test() that check if the value is an array ```Array.isArray(value)``` when you don't want null to be a valid value.

Now that I see yup is missing a method for array that allows only array, something like .required but that also allows empty arrays.

**Comment by patelrikin** [comment]
@ejose19 Thanks for responding. `.ensure` seems like catches `undefined` and `null` and transforms them to empty array per: https://github.com/jquense/yup#arrayensure-schema, so good enough for my use case.

Closing this issue as its non-issue rather stricter typings for Yup from `>0.29.0` thus Yup validation typed prior to that version need to be updated to make sure appropriate casting in final validation.
