### ISSUE TITLE
[Braintree] Wrong definition: statusHistory is an array

### ISSUE THREAD

**Issue by hitech95** [DefinitelyTyped/DefinitelyTyped#48540]
@smrubin @sedenardi Loks like that the statusHistory argument is a list.
On the documentation is maked as a "collection".

On PHPand JAVA library is an Array:
https://github.com/braintree/braintree_php/blob/master/lib/Braintree/Subscription.php#L99
https://github.com/braintree/braintree_php/blob/master/lib/Braintree/Transaction.php#L446
https://github.com/braintree/braintree_php/blob/master/lib/Braintree/Dispute.php#L81

And on Node library test is also an array.
https://github.com/braintree/braintree_node/blob/master/spec/unit/braintree/dispute_spec.js#L42

**Comment by martin-badin** [comment]
I created PR to fix this issue.

**Comment by hitech95** [comment]
@martin-badin Its not only the Dispute Class is also Subscription and Transaction history.
https://developers.braintreepayments.com/reference/response/subscription/node#status_history
https://developers.braintreepayments.com/reference/response/transaction/node#status_history
