### ISSUE TITLE
[@types/chai] wrong declaration of overwriteChainableMethod, a fix and no test

### ISSUE THREAD

**Issue by jlaurens** [DefinitelyTyped/DefinitelyTyped#48635]
First we declare a fake chainable method for the sake of the demonstration.

```
import * as chai from 'chai';
function assertAge(this: any, n: number) {}
function chainAge(this: any) {}
chai.Assertion.addChainableMethod('age', assertAge, chainAge);
```
So far so good, except regarding the `any` type problem already discussed in ###(48634).

We just overwrite the functions by a simple call to `_super`. 

```
chai.Assertion.overwriteChainableMethod(
    'age',
    function(this: any, _super: any) {
        return function assertAge(this: any, n: number) {
            _super.call(this, n);
        };
    },
    function(this: any, _super: any) {
        return function chainAge(this: any) {
            _super.call(this);
        };
    } as any // WRONG type declaration here
);
```

It only works because of the last `as any` which is not acceptable.

**Fix**: Assuming that `Assertion` extends `AssertionStatic`, declare before `ChaiUtils`

```
    // Getters and setter that can be added or overwritten
    type Getter = (this: Assertion) => void;
    type Method = (this: Assertion, ...args: any[]) => void;
    // T is one of Getter or Setter
    type Overwrite<T> = (this: Assertion, _super: T) => T;
```

then declare

```
        addChainableMethod(
            // object to define the method on, e.g. chai.Assertion.prototype
            ctx: object,
            // method name
            name: string,
            // method itself; any arguments
            method: Method,
            // called when property is accessed
            chainingBehavior?: Getter
        ): void;
        overwriteChainableMethod(
            ctx: object,
            name: string,
            method: Overwrite<Method>,
            chainingBehavior?: Overwrite<Getter>
        ): void;
[...]
        addMethod(ctx: object, name: string, method: Method): void;
        addProperty(ctx: object, name: string, getter: Getter): void;
        overwriteMethod(ctx: object, name: string, method: Overwrite<Method>): void;
        overwriteProperty(ctx: object, name: string, getter: Overwrite<Getter>): void;
 ```

and the same within `Assertion`.

**Testing:** I would be happy to send a PR as soon as testing is possible but just like  ###(48634) there is a problem extending chai with properties that are only necessary for testing.

Any help ?

Thanks

@jedmao,
@Bartvds,
@AGBrown,
@olivr70,
@mwistrand,
@JoshuaKGoldberg,
@shaunluttin,
@Naktibalda,
@micksatana,
@ErikSchierboom,
@bparan,
@CXuesong,
@joeykilpatrick,

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
