### ISSUE TITLE
@types/node for v12 - async_hooks#AsyncLocalStorage.run return type is incorrect

### ISSUE THREAD

**Issue by hugebdu** [DefinitelyTyped/DefinitelyTyped#48688]
[AsyncLocalStorage#run](https://nodejs.org/dist/latest-v12.x/docs/api/async_hooks.html#async_hooks_class_asynclocalstorage) returns the result of passed function instead of `void`

- [+ ] I tried using the `@types/xxxx` package and had problems.
- [+] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @peterblazejewicz 

also there're no `runSyncAndReturn` in node 12

**Comment by josteink** [comment]
As shown in the PR to resolve this issue (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48944), the errors for `AsyncLocalStorage.run()` is actually not in the type-definitions, but in the NodeJS documentation for this function. The other part seems to remain true though.

I suggest you raise an issue with the NodeJS team the errors in the documentation.
