### ISSUE TITLE
[fabric] Object type defined in @types/fabric augments the default Object type from lib.es5.d.ts

### ISSUE THREAD

**Issue by nicu-chiciuc** [DefinitelyTyped/DefinitelyTyped#48690]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @oklemencic, @joewashear007, @mrand01, @NotWoods, @bmartinson, @RogerioTeixeira, @BradleyHill, @bmkrol823, @glenngartner, @codertx, @mike667, @nataliemarleny

If you do not mention the authors the issue will be ignored.

I've opened a PR some days ago but I underestimated the subtleties for the change.
> Text below is copied from the issue https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48503

Unfortunately the naming of the type `Object` is quite unfortunate since it tries to augment the `Object` type from `lib.es5.d.ts`. Some editors seem to figure this out quite well, VSCode add code completions from fabric.Object, unfortunatelly, WebStorm thinks that any empty object in code must/might have properties from the `fabric.Object`.
Even reading the JsDoc/typings for the package things get confusing since it's never clear if a type is referring to the ambient `Object` type or the local one.

The PR was opened as a Draft since this seems like a pretty radical change. The name of the type could also be changed to something shorter, if it is so desired.

I've also disabled the `"no-redundant-jsdoc-2"` rule since the tests don't pass when it is enabled. The test didn't pass before the commit either. Another PR might fix the JsDoc so this rule can be reenabled, but this one is just about finding a better name for `Object`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
