### ISSUE TITLE
[@types/chai] ...deep.keys... not supported

### ISSUE THREAD

**Issue by jlaurens** [DefinitelyTyped/DefinitelyTyped#48694]
The chai source [assertion.js](https://github.com/chaijs/chai/blob/23764f340d6d3796eafdb7a9869b423bc45e0c8b/lib/chai/core/assertions.js#L102) gives an `expect` example which reads

```
expect(new Set([{a: 1}])).to.have.deep.keys([{a: 1}]);
```

This test passes when in javascript but does not compile with typescript, reason: Property 'keys' does not exist on type 'Deep'.

Chai.Deep should be amended to declare the `keys` property.

**Comment by joeykilpatrick** [comment]
Resolved by #48696, issue can be closed
