### ISSUE TITLE
[@types/puppeteer] page.mouse.wheel(...) not supported

### ISSUE THREAD

**Issue by ce-bo** [DefinitelyTyped/DefinitelyTyped#48710]
The new `page.mouse.wheel()` API is not supported in package `@types/puppeteer` (v^3.0.2).
Would you be so kind and release a new type definition to support the new API?

@marvinhagemeister 
@cdeutsch 
@ksm2 
@SimonSchick 
@serbanghita 
@JasonKaz 
@davecardwell 
@angrykoala 
@peterblazejewicz 

Thank you!

**Comment by emmanuelgautier** [comment]
Puppeteer has their own typing definition since this version. You should have access to the mouse.wheel method.

Furthermore, this method seems not exists following the documentation: https://github.com/puppeteer/puppeteer/blob/v3.0.2/docs/api.md

**Comment by ce-bo** [comment]
Thanks @emmanuelgautier 

> Furthermore, this method seems not exists following the documentation: 
> https://github.com/puppeteer/puppeteer/blob/v3.0.2/docs/api.md

The wheel method exists in the latest puppeteer version:
https://github.com/puppeteer/puppeteer/blob/v5.3.1/docs/api.md


It is still recommended to install the @types/puppeteer package to use the latest puppeteer version 5.3.1 with typescript (but the @types/puppeteer package does not support the latest puppeteer API)
https://github.com/puppeteer/puppeteer/tree/v5.3.1#user-content-usage-with-typescript

The implementation of puppeteers own typescript definitions is not finished yet:
https://github.com/puppeteer/puppeteer/issues/6124

So I am a bit confused now. Any suggestions?

Thank you!
