### ISSUE TITLE
Multer callback function types are incorrect

### ISSUE THREAD

**Issue by joshverd** [DefinitelyTyped/DefinitelyTyped#48713]
It looks like Multer's callback function types are incorrect. Here's my example setup:
![image](https://user-images.githubusercontent.com/11580426/95760631-e010cd00-0c70-11eb-98ed-1364750cc135.png)

As you can see, the callback function is not typed at all, but Multer supports `error` and `data` parameters in that callback function. I think this is because `@types/multer` is thinking the callback function is `Express.NextFunction` which does not support such parameters.

Testing the callback function with an error:
![image](https://user-images.githubusercontent.com/11580426/95761071-6c22f480-0c71-11eb-9ee2-63e733bf505c.png)

_tagging authors_
@jt000 
@vilic 
@DavidBR-SW
@mxl 
@hyunseob
@PierreTchuente
@thrymgjol
@peterblazejewicz

**Comment by thrymgjol** [comment]
Hello, @joshverd. Could you provide some supporting documentation? I skimmed the source code and it appears that middleware created by `multer` passes a maximum of 1 parameter to the provided `next` function. If you are trying to access the form data, `multer` passes that by modifying the request object received by the middleware.

`single` ([defined in index.js](https://github.com/expressjs/multer/blob/master/index.js#L59)) returns the result of a single call to [`_makeMiddleware`](https://github.com/expressjs/multer/blob/master/index.js#L25), which in turn returns the result of a call to [`makeMiddleware`](https://github.com/expressjs/multer/blob/master/lib/make-middleware.js#L16). `makeMiddleware` returns a middleware taking 3 parameters. The 3rd parameter is `next`, which is called in [only](https://github.com/expressjs/multer/blob/master/lib/make-middleware.js#L18) [three](https://github.com/expressjs/multer/blob/master/lib/make-middleware.js#L35) [places](https://github.com/expressjs/multer/blob/master/lib/make-middleware.js#L53). The first of those calls passes 0 parameters. The remaining two each pass 1 parameter (`err`). This is consistent with the [definition of `NextFunction`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-serve-static-core/index.d.ts#L34):

```ts
interface NextFunction {
    (err?: any): void;
    (deferToNext: "router"): void;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
