### ISSUE TITLE
d3 stack() returns incorrect type

### ISSUE THREAD

**Issue by tandu** [DefinitelyTyped/DefinitelyTyped#48720]
```json
"d3-shape": "^2.0.0"
"@types/d3-shape": "^2.0.0"
```
Trying to create simple stacked area chart in react native with d3 that is date based. Each record is having date and a couple of values in dictionary: `{date: new Date(), a: 1, b: 2, c: 3}`. d3.stack() returns `Series<StackedAreaData, string>[]` while the real response is `Series<[number, number], string>[]`. Check the comment marked with !!!. Other questions in comments are not related but I would really appreciate if you direct or help me with them.

```ts
interface StackedAreaData {
  date: Date;
  [key: string]: number | Date; // haven't found a way to define other keys as numbers only
}

const [date, ...keys] = data.length ? Object.keys(data[0]) : []; // get all keys from the first object in array except the reserved 'date'
const stackedData = d3.stack<StackedAreaData>()
  .keys(keys)(data) as any as Series<[number, number], string>[]; // !!! Have to manually cast to match returned type
const x = d3.scaleUtc(d3.extent(data, pt => pt.date) as [Date, Date], [0, size.width]);
const y = d3.scaleLinear([0, d3.max(stackedData, d => d3.max(d, d => d3.max(d))) ?? 0], [size.height - 20, 5]);

const chart = d3.area()
  .x((_, i) => x(data[i].date) ?? 0) // no way to avoid `?? 0` here?
  .y0(d => y(d[0]) ?? 0)
  .y1(d => y(d[1]) ?? 0);
```

the resulting correct chart is at the bottom, the issue is only with typing:

<img width="475" alt="Screenshot 2020-10-12 at 21 14 36" src="https://user-images.githubusercontent.com/273313/95773727-16316980-0cd0-11eb-8f30-9688705c13ee.png">

Authors: @denisname, @tomwanzek, @andy-ms, @Methuselah96, @Tragetaschen, @benhjames, @sandersn, @gustavderdrache, @borisyankov

**Comment by Methuselah96** [comment]
Have you tried `d3.stack<StackedAreaData, string>()`?

**Comment by Methuselah96** [comment]
> d3.stack() returns Series<StackedAreaData, string>[] while the real response is Series<[number, number], string>[]

`Series<StackedAreaData, string>[]` extends from `Array<SeriesPoint<Daturm>>` (where `SeriesPoint<Datum>` contains `0` and `1` properties and extends from `number[]`).
So I believe it is actually correct and the two types that you mentioned are compatible.

**Comment by tandu** [comment]
I believe I tried it once when there were my other coding experiments in place so it was not working with them, now it works without complaints, thank you.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
