### ISSUE TITLE
[@types/html-webpack-plugin] Support for webpack 5

### ISSUE THREAD

**Issue by rajzik** [DefinitelyTyped/DefinitelyTyped#48804]
@types/html-webpack-plugin doesn't support webpack 5 types which are now generated by webpack itself.

```
node_modules/@types/html-webpack-plugin/index.d.ts:9:10 - error TS2305: Module '"../../webpack/types"' has no exported member 'Plugin'.

9 import { Plugin, compilation, Compiler } from 'webpack';
           ~~~~~~

node_modules/@types/html-webpack-plugin/index.d.ts:9:18 - error TS2724: Module '"../../webpack/types"' has no exported member 'compilation'. Did you mean 'Compilation'?

9 import { Plugin, compilation, Compiler } from 'webpack';
                   ~~~~~~~~~~~
```

- [x] I tried using the `@types/html-webpack-plugin` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @deevus, @bumbleblym, @tlaziuk

If you do not mention the authors the issue will be ignored.

**Comment by fwh1990** [comment]
Install `html-webpack-plugin@next` to compatible with webpack@5 that includes type definition itself.

**Comment by latipun7** [comment]
latest `html-webpack-plugin` (v4.5.0) already has its own type definition, and already support webpack 5. No need to install `@types/html-webpack-plugin`

**Comment by lanmch** [comment]
i meet the same problem with webpack5 and ts, hav you solve this problem?

**Comment by maverick-zhn** [comment]
I had the same issue even with the html-webpack-plugin (v4.5.0.) In my case, I changed just the module: 
This
`import { Compiler, compilation } from 'webpack';`
to this:
`import { Compiler, Compilation } from 'webpack';`
and 
`static getHooks(compilation: compilation.Compilation): HtmlWebpackPlugin.Hooks;`
to
`static getHooks(compilation: Compilation): HtmlWebpackPlugin.Hooks;`
I am not sure if this is the intended behavior though. Thanks.
