### ISSUE TITLE
[@types/webpack-bundle-analyzer] Support for webpack 5

### ISSUE THREAD

**Issue by rajzik** [DefinitelyTyped/DefinitelyTyped#48807]
[@types/webpack-bundle-analyzer] doesn't support webpack 5 types which are now generated by webpack itself.

```
node_modules/@types/webpack-bundle-analyzer/index.d.ts:9:10 - error TS2305: Module '"../../webpack/types"' has no exported member 'Plugin'.

9 import { Plugin, Compiler, Stats } from 'webpack';
           ~~~~~~

node_modules/@types/webpack-bundle-analyzer/index.d.ts:76:31 - error TS2702: 'Stats' only refers to a type, but is being used as a namespace here.

76         statsOptions?: null | Stats.ToJsonOptionsObject;
                                 ~~~~~
```

- [x] I tried using the `@types/webpack-bundle-analyzer` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kryops, @VladimirGrenaderov, @maxbogus, @peterblazejewicz

**Comment by aleksandr-sidorov** [comment]
In my case the `"webpack": "^5"` dependency was the problem. I have a specific Webpack version as a dependency in my app which types was in conflict with the latest Webpack version from the @types/webpack-bundle-analyzer
