### ISSUE TITLE
[@types/react-native] ToastAndroid.showWithGravityAndOffset is missing from types in TS

### ISSUE THREAD

**Issue by Darapsas** [DefinitelyTyped/DefinitelyTyped#48815]
The title pretty much explains it all

Authors: @alloy @huhuanming @iRoachie and others

Example: 
![20201015_150718](https://user-images.githubusercontent.com/20926795/96121028-2461ce80-0ef8-11eb-8648-8cee847ab51d.png)

TS error I am getting: 
```Property 'showWithGravityAndOffset' does not exist on type 'ToastAndroidStatic'```

Oh yeah and yes, I have tested it in on the latest release: ```"@types/react-native": "^0.63.25"```

**Comment by iRoachie** [comment]
Gotcha np
