### ISSUE TITLE
InferableComponentEnhancerWithProps does not correctly infer class-based (React.Component flavor) component properties

### ISSUE THREAD

**Issue by yurigenin** [DefinitelyTyped/DefinitelyTyped#48882]
- Authors: 
Qubo <https://github.com/tkqubo>
Kenzie Togami <https://github.com/kenzierocks>
Curits Layne <https://github.com/clayne11>
Frank Tan <https://github.com/tansongyang>
Nicholas Boll <https://github.com/nicholasboll>
Dibyo Majumdar <https://github.com/mdibyo>
Thomas Charlat <https://github.com/kallikrein>
Valentin Descamps <https://github.com/val1984>
Johann Rakotoharisoa <https://github.com/jrakotoharisoa>
Anatoli Papirovski <https://github.com/apapirovski>
Boris Sergeyev <https://github.com/surgeboris>
Søren Bruus Frank <https://github.com/soerenbf>
Jonathan Ziller <https://github.com/mrwolfz>
Dylan Vann <https://github.com/dylanvann>
Yuki Ito <https://github.com/Lazyuki>
Kazuma Ebina <https://github.com/kazuma1989>

When using a component class extending **React.Component** to connect to Redux store with **connect()** HOC the returned component is of an **InferableComponentEnhancerWithProps** type. But this type does not correctly derive the properties of the component because internally it relies on the component to extend **React.ComponentType**. But **React.Component** does not extend it, thus, the property inferring fails.

The definition of the **InferableComponentEnhancerWithProps** is here:

```
export type InferableComponentEnhancerWithProps<TInjectedProps, TNeedsProps> =
    <C extends ComponentType<Matching<TInjectedProps, GetProps<C>>>>(
        component: C
    ) => ConnectedComponent<C, Omit<GetProps<C>, keyof Shared<TInjectedProps, GetProps<C>>> & TNeedsProps>;
```
It uses **GetProps** type to match injected properties with **propTypes** properties:

```
export type GetProps<C> = C extends ComponentType<infer P> ? P : never;
```

It will always return **never** since **React.ComponentType** is defined as:

```
type ComponentType<P = {}> = ComponentClass<P> | FunctionComponent<P>;
```

But any component that is defined as:

```
class MyComponent extends React.Component<MyProps> {}
```

does not extend from either **ComponentClass** or **FunctionComponent**.

It results in all injected properties not getting omitted as intended because **GetProps** type is **never**:

```
ConnectedComponent<C, Omit<GetProps<C>, keyof Shared<TInjectedProps, GetProps<C>>> & TNeedsProps>;
```

I can only force it to work if I call **connect** like this:

```
class MyComponent extends React.Component<...> { ... };

connect(....)((MyComponent as unknown) as React.ComponentClass<...>);
```

Here's the demonstration:

![image](https://user-images.githubusercontent.com/11202960/96357675-38562d80-10bc-11eb-892c-b4befd1135e0.png)

As you see, TS says that any class that extends React.Component is not of type React.ComponentClass.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
