### ISSUE TITLE
[lodash][node] Requiring specific modules/functions

### ISSUE THREAD

**Issue by rickyrombo** [DefinitelyTyped/DefinitelyTyped#4889]
I’m working in a Node.js/TypeScript project, and I added lodash. I also added the typing on DefinitelyTyped: https://github.com/borisyankov/DefinitelyTyped/blob/master/lodash/lodash.d.ts

I want to use the modularity allowed in `lodash`, ie:

``` ts
import _ = require('lodash/collection');
_.findWhere(…)
```

TypeScript doesn’t know that ‘lodash/collection’ is a module, so I tell it by adding an ambient declaration into the typing file:

``` ts
declare module 'lodash/collection' {
    export = _;
}
```

However, then TypeScript will think I have access to _all_ lodash functions and not just the subset I'm actually getting. So really I should export the actual submodule/interface I want.

Therein lies the problem. The typing file doesn’t have any submodules/interfaces for the individual components, likely due to the definition file being used primarily for the browser environment I’m assuming. Instead, each method is added by merging declarations of the LoDashStatic interface.

I’m curious why the definition file doesn’t follow the structure of something like:

``` ts
//Do something like this for each major category
interface LoDashStatic extends LoDashCollections { } 

interface LoDashCollections {
    findWhere: findWhere;
   …
}

// this interface describes the function, so we could pull this out separately as well.
//_.findWhere
interface findWhere {
    <T>( collection: Array<T>,
            callback: ListIterator<T, boolean>,
            thisArg?: any): T;
     …
```

Which would allow me to do something like:

``` ts
declare var LoDashCollections: _.LoDashCollections;
declare module 'lodash/collection' {
    export = LoDashCollections;
}
```

Admittedly, now TypeScript thinks `LoDashCollections` is a global and accessible anywhere, so there's problems with this too.

Perhaps there’s a better way to get typing for Node modules that I’m missing? Or perhaps there's other issues with this approach?

I still think the hiearchical method I propose here is better than the way it is currently, even if it does clutter the TypeScript compiler's understanding of the global space. Obfuscating the variable names will make it less likely for someone to accidentally access the global definition, and having the actual methods you have available in the context of the submodule would be incredibly useful in Node projects.

I'd go through and do it myself but I want to make sure I'm not missing something important with the reasoning, as it would be a heck of a lot of work to do.

**Comment by jvilk** [comment]
In general, you don't want a definitions file to clutter the global namespace. This is why maintainers moved a large portion of the interfaces defined in [node.d.ts](https://github.com/borisyankov/DefinitelyTyped/blob/master/node/node.d.ts) into the [`NodeJS` module](https://github.com/borisyankov/DefinitelyTyped/blob/master/node/node.d.ts#L142), and then referenced those interfaces [in the typings for each Node module](https://github.com/borisyankov/DefinitelyTyped/blob/master/node/node.d.ts#L395).

While I've never used lodash, I'd imagine an effective refactoring of the lodash definition file would:

* Place all of the shared interfaces under a common module name, e.g. `module LoDash`.
* Define modules for each of the individual lodash modules, such as `lodash/collection`.
* And you can define an uber interface for the web crowd that extends all of the interfaces, and use it for the global exposed in the web environment / the conglomerate module that contains everything.

Hopefully that helps! These definition files get interesting for libraries that are used from multiple module systems (AMD/CommonJS/global variables). :)

**Comment by rickyrombo** [comment]
:boom: thanks. Node's example was exactly what I am trying to accomplish and illustrates how to avoid the global namespace problem. Now I just have a lot of work to do to refactor the lodash definition file... :(

**Comment by nikrolls** [comment]
@rickyrombo Did you make any progress on that? This is the exact issue we're running into trying to use lodash as efficiently as possible with JSPM.

**Comment by rickyrombo** [comment]
@nikrolls I have not. I made the small changes necessary to use the modules I was using to unblock my project and then continued working on the task at hand, expecting to come back and finish modularizing.

I'm open to revisiting this now. What's your timeframe?

**Comment by vvakame** [comment]
@chrootsu ?

**Comment by chrootsu** [comment]
@vvakame I have not used modularity of lodash and have to study it. I was planning to do it when definitions will be up to date but maybe I can make it before. I will think about this issue.

**Comment by nukuuk** [comment]
Hello, any progress on this?  Still unable to reference lodash modularized in typescript import statements.

**Comment by aspirisen** [comment]
I have the same problem that I can't import specific lodash function

**Comment by episodeyang** [comment]
I'm having the same problem.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
