### ISSUE TITLE
[@types/node] IncomingHttpHeaders contains 'set-cookie' which is a response header only

### ISSUE THREAD

**Issue by tozz** [DefinitelyTyped/DefinitelyTyped#48895]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @peterblazejewicz @victorperin

I don't know if the authors are correct, I took the latest ones from `http.d.s` that were also in the `Definitions by` list.

I noticed `set-cookie` is defined in `IncomingHttpHeaders` (as the only `string[]`). It's not a request header though, there's nothing a server can do with that header if the user sends it according to HTTP (at least nothing I've found). And how is the header supposed to be any array, the browser can only send a string?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

It's an easy fix but I must be missing something on why this is explicitly typed.

**Comment by tozz** [comment]
This is an issue in Node and not the types, sorry for wasting your time.

**Comment by pencilcheck** [comment]
Still having the same type issue here, looks like this hasn't been fixed at all
