### ISSUE TITLE
[@types/select2] templateSelection

### ISSUE THREAD

**Issue by Serraniel** [DefinitelyTyped/DefinitelyTyped#48975]
- [x] I tried using the `@types/select2` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @denisname 

Hi, I am not sure if the following is a problem with the types or our usage of select2 but we are currently migrating our project from js to typescript and noticed a problem with our templateSelection option in this code:
```ts
$(this.obj).select2({
    templateSelection: function (data, container): string {
        // Wenn gelockt, dann setzen wir css damit wir das x ausblenden
        if ($(data.element).attr('locked')) {
            $(container).addClass('locked-tag');
            data.locked = true;
        }
        return data.text;
    }
});
```
We get an error as we have two parameters in our function:
![2020-10-21_10-05-29](https://user-images.githubusercontent.com/8461282/96691410-278c0d00-1385-11eb-928a-27b77261ad5b.png)

According to the type definitions there only is one parameter:
```ts
templateSelection?: (selection: IdTextPair | LoadingData | Result) => string | JQuery;
```

However I cannot find a signature in the docs at https://select2.org/selections#templating, only the example which has one parameter, too, and some sentences about the return value.

But there also exists an example on the select2 page in which the template selection has two parameters `data` and `container` like in our usage, so I think our usage is not wrong at all:
https://select2.org/programmatic-control/retrieving-selections#using-a-jquery-selector
```js
$('#mySelect2').select2({
  // ...
  templateSelection: function (data, container) {
    // Add custom attributes to the <option> tag for the selected option
    $(data.element).attr('data-custom-attribute', data.customValue);
    return data.text;
  }
});
```

I am not sure if there just is a wrong example on the website or the signature with two params is missing in the types.

**Comment by tiaxter** [comment]
I found out the same issue

**Comment by Serraniel** [comment]
So I am not the only one having the issue :)

I meanwhile prepared a pull request for this (#49312) but it´s still in review. According to the source code that usage is correct.

**Comment by Serraniel** [comment]
The pull request related to this issue is merged, so I´ll close thise.
