### ISSUE TITLE
[@types/mini-css-extract-plugin] Doesn't work with webpack 5

### ISSUE THREAD

**Issue by dfilatov** [DefinitelyTyped/DefinitelyTyped#48982]
- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @JounQin @dobogo @skovy @peterblazejewicz

Error:
Type 'MiniCssExtractPlugin' is not assignable to type '((this: Compiler, compiler: Compiler) => void) | WebpackPluginInstance'. Property 'apply' is missing in type 'MiniCssExtractPlugin' but required in type 'WebpackPluginInstance'.ts(2322)

webpack 5 doesn't provide `Plugin` and `ChunkData` types used in `@types/mini-css-extract-plugin`

**Comment by latipun7** [comment]
it's already soved in `@types/mini-css-extract-plugin@1.2.1` (latest).
