### ISSUE TITLE
@types/mongoose - Wrong typings for "all" query

### ISSUE THREAD

**Issue by mehmetnyarar** [DefinitelyTyped/DefinitelyTyped#48988]
```ts
all(val: number): this;
all(path: string, val: number): this;
```

Value type should be an array, not a number.

[Documentation](https://mongoosejs.com/docs/api/query.html#query_Query-all)

@horiuchi @lukasz-zak @jendrikw

**Comment by JoelLau** [comment]
hi, can I take this up as part of hacktoberfest?
