### ISSUE TITLE
[@types/babel__core] Possible error in declaration of PluginObj

### ISSUE THREAD

**Issue by Elberet** [DefinitelyTyped/DefinitelyTyped#49018]
In the declaration for `babel.PluginObj`, the function arguments for the `pre` and `post` hooks appear to have the wrong type.

According to [this](https://github.com/babel/babel/blob/main/packages/babel-core/src/transformation/index.js#L92), plugin `pre`/`post` hooks receive the current file in arguments, not (a copy of) the state, while the declaration [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/babel__core/index.d.ts#L426) claims otherwise. I would provide a PR, but have too little practice with TypeScript to dare. 😅 

@yortus @marvinhagemeister @mgroenhoff @Jessidhia @ifiokjr

**Comment by SimenB** [comment]
#48845

**Comment by Elberet** [comment]
Thanks. 👍
