### ISSUE TITLE
arcgis-js-api issue with widget tutorial

### ISSUE THREAD

**Issue by bloigge** [DefinitelyTyped/DefinitelyTyped#49023]
@bsvensson @dasa @NoashX

In row 35924 `visibleFieldNames?: Set<string>;` which results in the Error `Cannot find name 'Set'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.` when trying to compile against target `es5` like in the [widget-creation-tutorial ](https://developers.arcgis.com/javascript/latest/sample-code/widgets-custom-widget/index.html#4-compiling-the-tsx-file)

**Comment by dasa** [comment]
Instead of changing the `target`, you can change the `lib`: https://www.typescriptlang.org/tsconfig#lib

Try `"lib": ["dom", "es5", "es2015.collection"]`

**Comment by bloigge** [comment]
Thanks - That did the trick!
