### ISSUE TITLE
Update codeowners

### ISSUE THREAD

**Issue by maraisr** [DefinitelyTyped/DefinitelyTyped#49032]
Looks like the github codeowners file is heavily outdated. @sandersn

**Comment by sandersn** [comment]
@orta @elibarzilay is CODEOWNERS still used for anything? It might be better to remove it.

**Comment by sandersn** [comment]
Huh. The Azure scheduled triggers interface is just gone, seemingly replaced by a "Sync from yaml" button. Looks like I need to port the weekly trigger to yaml. Fun!

**Comment by sandersn** [comment]
Nope, I forgot that I updated the script in July and moved it to Github Actions. I introduced a bug (forgot to call `os.cpus`) at the time. That is fixed now so it should resume updating.

**Comment by maraisr** [comment]
Thanks for looking at that so prompty @sandersn! Looks like https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49099 solves it.
