### ISSUE TITLE
Intercom-client outdated Lead.d.ts 

### ISSUE THREAD

**Issue by ZhaoKunLong** [DefinitelyTyped/DefinitelyTyped#49040]
Is something wrong with CI or publishing infrastructure?

No.

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/intercom-client` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mbernardy 

If you do not mention the authors the issue will be ignored.

<hr/>

Package versions:

- intercom-client: 2.11.0
- @types/intercom-client: 2.11.8

I'm using TypeScript with the intercom api like so:

```js
await intercomClient.contacts.create({
  role: 'lead',
  email: 'email@mail.com'
  name: 'name',          
});
```

but this results in an error: `'role' is not in Partial<Lead>`. I did confirm that this `role` field does exist in the new Intercom API, but the `Lead` type hasn't been updated yet. Can the intercom types be updated, please?

Thanks.

**Comment by Zhaokung** [comment]
Thank you, now it's nice. 
I will close this issue.
