### ISSUE TITLE
@types/flatbuffers doesn't correspond to generate files

### ISSUE THREAD

**Issue by savv** [DefinitelyTyped/DefinitelyTyped#49049]
These typedefs did not work for me when I followed the tutorial. Looking at the module, this makes sense. For example, ByteBuffer is only defined as a class, not as a type, which is what the flatbuffers generated file expects!

I got errors like:
```
ts/monster_generated.ts:53:19 - error TS2694: Namespace '"/Users/savv/flatbuffers/node_modules/@types/flatbuffers/index"' has no exported member 'ByteBuffer'.

53   bb: flatbuffers.ByteBuffer|null = null;
                     ~~~~~~~~~~

ts/monster_generated.ts:61:33 - error TS2694: Namespace '"/Users/savv/flatbuffers/node_modules/@types/flatbuffers/index"' has no exported member 'ByteBuffer'.

61 __init(i:number, bb:flatbuffers.ByteBuffer):Vec3 {
                                   ~~~~~~~~~~

ts/monster_generated.ts:102:39 - error TS2694: Namespace '"/Users/savv/flatbuffers/node_modules/@types/flatbuffers/index"' has no exported member 'Builder'.
```

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc (4.0.3)
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/)
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rgiese @andy-ms @krojew

**Comment by krojew** [comment]
Flatbuffers master branch is already using TS, so you can use that.

**Comment by savv** [comment]
I could, but it would require editing the generated file...

**Comment by savv** [comment]
It's very strange, because their own typescript files have this exact same problem. But I built my `flatc` compiler from master.

**Comment by savv** [comment]
This seems like an error on my part, the namespace looks strange.
