### ISSUE TITLE
[@types/history] Location state property should be optional

### ISSUE THREAD

**Issue by raksooo** [DefinitelyTyped/DefinitelyTyped#49060]
The `state` property on `Location` is required here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8cd814c4e3b37197b389e8b94cee7bb0de56ed52/types/history/index.d.ts#L27-L33

Which makes this function impossible to implement since the input state is optional but the state in the returned location is required:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8cd814c4e3b37197b389e8b94cee7bb0de56ed52/types/history/LocationUtils.d.ts#L4-L9

I've had a look at the implementation as well and am under the impression that the location state can be `undefined` if none is provided, even if `S` isn't nullable.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sergey-buturlakin @ngbrown @rokoroku @danielnixon

**Comment by amcasey** [comment]
Closing for the reasons mentioned in the corresponding PR.
