### ISSUE TITLE
Broken types for `serve-favicon`

### ISSUE THREAD

**Issue by wszydlak** [DefinitelyTyped/DefinitelyTyped#49139]
After pull https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48864 types for `serve-favicon` has errors when not using `esModuleInterop` flag.

When trying to use:

```ts
import * as favicon from 'serve-favicon';
```

It brokes with error: *This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag*

Probably issue is caused because of removed `declare namespace serveFavicon {} `

**It worked great in version 2.5.0** and was broken in **2.5.1** 

Authors of PR: @peterblazejewicz

**Comment by peterblazejewicz** [comment]
One can fix this by adding empty namespace back, yes, I agree, but I have a feeling this would be completetly wrong and not future proof.
Therre is no module export in this package, just direct function being exported, hence this old syntax is out of place.

I'd rather update your code to:
```ts
"esModuleInterop": true
```
in `tsconfig.json` (which is now enabled by default in new projects)
and use syntax like:

```ts
import express from 'express';
import favicon from "serve-favicon";
import path = require("path");

const app = express();
app.use(favicon(path.join(__dirname, "public", "favicon.ico")));
```
which is compatible with ES syntax,

For CommonJS syntax without interop flag:

```ts
import express = require('express');
import favicon = require('serve-favicon');
```
is a syntax to use

**Comment by wszydlak** [comment]
I use a lot of packages which are compatibile with `esModuleInterop` and without it. I think that this should be also in `serve-favicon`. We shouldn't force user to use `esModuleInterop`, instead we should have compatibility for both options. Let user decide if their code should be written with using `esModuleInterop` or not.

**Comment by peterblazejewicz** [comment]
addressing in #49321 49321
