### ISSUE TITLE
Type 'Module | null | undefined' is not assignable to type 'NodeModule | null'

### ISSUE THREAD

**Issue by tk-1io** [DefinitelyTyped/DefinitelyTyped#49151]
The latest `@types/webpack-env@1.15.3` no longer works together with the latest node v12 types `@types/node@12.19.2`.

Error:
```
node_modules/@types/webpack-env/index.d.ts:349:15 - error TS2430: Interface 'NodeJS.Module' incorrectly extends interface '__WebpackModuleApi.Module'.
  Types of property 'parent' are incompatible.
    Type 'Module | null | undefined' is not assignable to type 'NodeModule | null | undefined'.
      Type 'Module' is not assignable to type 'NodeModule'.
        Types of property 'parent' are incompatible.
          Type 'Module | null | undefined' is not assignable to type 'NodeModule | null'.
            Type 'undefined' is not assignable to type 'NodeModule | null'.

349     interface Module extends __WebpackModuleApi.Module {}
```

It seems it's not a problem in the `@types/webpack-env` package itself, but in the `@types/node` package.

[This change](https://github.com/Semigradsky/DefinitelyTyped/commit/aec9a1a0ba4412aa1d5faed875280f0a467e31a6#diff-fbb362680b965a40c12d1baf1c1380c6963ce86b2106ca8fafaba7323d91c009R1186) seems to have caused the error.

The changed `Module` [class](https://github.com/Semigradsky/DefinitelyTyped/blob/aec9a1a0ba4412aa1d5faed875280f0a467e31a6/types/node/v12/globals.d.ts#L1167) is no longer compatible to the `NodeModule` interface (in the same file). This is because the `parent` [property](https://github.com/Semigradsky/DefinitelyTyped/blob/aec9a1a0ba4412aa1d5faed875280f0a467e31a6/types/node/v12/globals.d.ts#L234) of the `NodeModule` interface has not been adjusted to match the changed one from the `Module` class.

The `@types/webpack-env` package just uses the `NodeModule` interface [here](https://github.com/Semigradsky/DefinitelyTyped/blob/aec9a1a0ba4412aa1d5faed875280f0a467e31a6/types/webpack-env/index.d.ts#L71) and expects it to be compatible to the `Module` class (which was the case before the change) [here](https://github.com/Semigradsky/DefinitelyTyped/blob/aec9a1a0ba4412aa1d5faed875280f0a467e31a6/types/webpack-env/index.d.ts#L349).

There was a [similar issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/45927) in the past (just not the `parent` property but a different one).

@Semigradsky @use-strict @rhonsby

**Comment by Semigradsky** [comment]
I thought it was fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47516
cc @jamescdavis

**Comment by tk-1io** [comment]
I think the change in the `@types/node` caused two incompatibilities and the fix in #47516 just fixed one of them. It restored the compatibility of the `@types/webpack-env`s `Module` [interface](https://github.com/Semigradsky/DefinitelyTyped/blob/aec9a1a0ba4412aa1d5faed875280f0a467e31a6/types/webpack-env/index.d.ts#L71) to the `Module` class of the `@types/node`. But the `@types/webpack-env` not just uses the (changed) `Module` class of `@types/node`, but also uses the `NodeModule` interface, which has not been updated accordingly, therefore causing another incompatibility.

**Comment by tk-1io** [comment]
... basically said, this code compiled before the [change](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48570/files#diff-fbb362680b965a40c12d1baf1c1380c6963ce86b2106ca8fafaba7323d91c009R1186) to the `Module` class:
```typescript
/// <reference types="node" />
const moduleClass: NodeJS.Module = {} as any;
const moduleInterface: NodeModule = moduleClass;
```
while with `@types/node@12.19.2` this throws:
```
index.ts:3:7 - error TS2322: Type 'Module' is not assignable to type 'NodeModule'.
  Types of property 'parent' are incompatible.
    Type 'Module | null | undefined' is not assignable to type 'NodeModule | null'.
      Type 'undefined' is not assignable to type 'NodeModule | null'.

3 const moduleInterface: NodeModule = moduleClass;
```

**Comment by jamescdavis** [comment]
`| undefined` for `Module.parent` was only added v14 of the node types (#47485). It was not backported to v12 (I'm guessing because it wasn't considered deprecated until node 14.6.0). But that does cause a type incompatibility with the latest webpack-env. Do we want to backport this to v12? @Semigradsky?

**Comment by tk-1io** [comment]
@jamescdavis I think it was backported partially, because the parent property of the `Module` class of v12 did got changed to support `| undefined` via v12.19.0, just the `NodeModule` interface of v12 didn't receive the same change

**Comment by jamescdavis** [comment]
Oh, yep, I see that now: #48570

In v14, it just aliases `Module` as `NodeModule`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7529b68e2bc20265b1e760add7947ea65db0fbe1/types/node/globals.d.ts#L42

But not in v12, so `NodeModule` needs updated separately.
