### ISSUE TITLE
[@types/datatables.net-buttons] Missing Button Definitions 

### ISSUE THREAD

**Issue by nsoqui** [DefinitelyTyped/DefinitelyTyped#49158]
I tried using the `@types/datatables.net-buttons` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Silver-Connection, @SammyG4Free, @jimhartford 

I am having an issue with a missing call for datatables-buttons.
I see now way to manually call the button actions like this.

The main definition I am looking for is to export csv data.

$.fn.dataTable.ext.buttons.csvHtml5.action.call(this, e, dt, node, config);

https://datatables.net/reference/option/buttons.buttons.action

**Comment by princefishthrower** [comment]
@nsoqui - I took a look into this, it looks like where TypeScript complains is at the `csvHtml5` not being a part of type `buttons`? Can you confirm? If so, I believe I can fix this. Or a screenshot of the error in any event would be helpful :smile:

**Comment by nsoqui** [comment]
Yeah that's exactly correct.

![image](https://user-images.githubusercontent.com/5043165/97357903-b56d6980-1857-11eb-89e8-bc84c81a0ad4.png)

**Comment by princefishthrower** [comment]
@nsoqui - perfect. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49164 is open which should solve this issue!

**Comment by nsoqui** [comment]
This is exactly what I needed.
I really appreciate your help and incredibly fast response time.
Cheers!

**Comment by princefishthrower** [comment]
@nsoqui - just an FYI, that pull request should be merged momentarily - sorry for the long delay
