### ISSUE TITLE
[@types/mongodb] support aggregation pipeline in update functions

### ISSUE THREAD

**Issue by legraphista** [DefinitelyTyped/DefinitelyTyped#49153]
- [x] I tried using the `@types/mongodb` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
<details>
<summary>- Authors:</summary>

//                 Federico Caselli <https://github.com/CaselIT>
//                 Alan Marcell <https://github.com/alanmarcell>
//                 Gaurav Lahoti <https://github.com/dante-101>
//                 Mariano Cortesi <https://github.com/mcortesi>
//                 Enrico Picci <https://github.com/EnricoPicci>
//                 Alexander Christie <https://github.com/AJCStriker>
//                 Julien Chaumond <https://github.com/julien-c>
//                 Dan Aprahamian <https://github.com/daprahamian>
//                 Denys Bushulyak <https://github.com/denys-bushulyak>
//                 Bastien Arata <https://github.com/BastienAr>
//                 Wan Bachtiar <https://github.com/sindbach>
//                 Geraldine Lemeur <https://github.com/geraldinelemeur>
//                 Dominik Heigl <https://github.com/various89>
//                 Angela-1 <https://github.com/angela-1>
//                 Hector Ribes <https://github.com/hector7>
//                 Florian Richter <https://github.com/floric>
//                 Erik Christensen <https://github.com/erikc5000>
//                 Nick Zahn <https://github.com/Manc>
//                 Jarom Loveridge <https://github.com/jloveridge>
//                 Luis Pais <https://github.com/ranguna>
//                 Hossein Saniei <https://github.com/HosseinAgha>
//                 Alberto Silva <https://github.com/albertossilva>
//                 Piotr Błażejewicz <https://github.com/peterblazejewicz>
//                 Linus Unnebäck <https://github.com/LinusU>
//                 Richard Bateman <https://github.com/taxilian>
//                 Igor Strebezhev <https://github.com/xamgore>
//                 Valentin Agachi <https://github.com/avaly>
//                 HitkoDev <https://github.com/HitkoDev>
//                 TJT <https://github.com/Celend>
//                 Julien TASSIN <https://github.com/jtassin>

</details>

Are there any plans to support aggregation pipeline in the update functions?
In MongoDB 4.2, aggregation pipelines have been added to update functions and you can perform in-db updates on the document based on the document's own data ([Documentation](https://docs.mongodb.com/manual/tutorial/update-documents-with-aggregation-pipeline/))

If it's as simple as updating the `update` param to be `UpdateQuery<TSchema> | Partial<TSchema> | object[]` then I could open a PR, but i fear it might break something else or make the types too relaxed.  
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1a58c7d4327286ecd5b80e8e1fb5ddc7bc3de6fa/types/mongodb/index.d.ts#L1470-L1474

**Comment by stefanomiccoli** [comment]
+1

**Comment by LinusU** [comment]
The `@types/mongodb` packages has been removed and typings are now shipped upstream as part of the `mongodb` package, so this issue can be closed...
