### ISSUE TITLE
googlemaps: request for comments on auto generation of typings

### ISSUE THREAD

**Issue by jpoehnelt** [DefinitelyTyped/DefinitelyTyped#49210]
I am working on the generation of `googlemap` types from the internal Google codebase with the eventual goal of updating the package here. I am looking for comments from the community regarding this effort.

* There will likely be breaking changes and some advanced features(generics) would be dropped.
* Comments would be generated from the same source as [reference documentation](https://developers.google.com/maps/documentation/javascript/reference).
* The typings would be updated with every weekly release.

I can expand on this further depending on feedback. I am planning on sharing an early version as I finish writing tests.

cc:
@demensky 
@cgwrench
@Silver-Connection
@nertzy
@xaolas
@martincostello 
@svenkreiss 
@bolatovumar
@gauthierm
@captain-igloo
@life777
@simonhaenisch
@gshigeto
@Bat-Orshikh

**Comment by demensky** [comment]
1.  > … generation of `googlemap` types from the internal Google codebase…

    How, then, will the work on accepting fixes from the community be organized?

2.  > … some advanced features(generics) would be dropped.

    Is it possible to do without significant losses?

3.  > The typings would be updated with every weekly release.

    👍

**Comment by jpoehnelt** [comment]
> How, then, will the work on accepting fixes from the community be organized?

These would be reported and fixed internally and that would cascade through to here.

> Is it possible to do without significant losses?

This is the main trade off of course, but I think it is balanced by having more correct and up to date types.

**Comment by demensky** [comment]
Do you want to fully privatize these definitions? Community can't make fixes? If the types will be generated from internal sources, would there be a way to somehow report the error or affect the generation? It is desirable that this fix does not take too long to apply.

**Comment by demensky** [comment]
Maybe it would be better if you create a parallel definition in which you can investigate all the problems?

**Comment by jpoehnelt** [comment]
>Community can't make fixes?

This is more of a process issue. The types are generated through an automated process. There is no way to make changes except by modifying the inputs to the process. The community does not have access to these inputs.

>If the types will be generated from internal sources, would there be a way to somehow report the error or affect the generation?

This would be reported the same as any other bug relating to the underlying library. 

![Screenshot 2020-10-29 at 10 16 55 AM](https://user-images.githubusercontent.com/3392975/97601552-e96b9a80-19cf-11eb-9d78-99cde1e7072a.png)

> Maybe it would be better if you create a parallel definition in which you can investigate all the problems?

Yes a parallel definition is an option, however I wouldn't consider there to be problems so much as slightly different implementations. The output is correct in so much as the reference docs and our internal type annotations are correct.

**Comment by simonhaenisch** [comment]
If you're planning to release official typings, would there be a package that you could provide them with (i. e. via `types` field in `package.json`)? I was thinking maybe [`@googlemaps/js-api-loader`](https://www.npmjs.com/package/@googlemaps/js-api-loader), but that already comes with types (only for the loader I assume).

**Comment by jpoehnelt** [comment]
> If you're planning to release official typings, would there be a package that you could provide them with

I wish this solution was available. I've been pushing for an npm package and a reworking of the bootstrapping process, but it is not something easily done given the complexities of an JS codebase. The v2 to v3 migration was over a decade ago...
