### ISSUE TITLE
react-select: Missing NoOptionsMessageProps type

### ISSUE THREAD

**Issue by cseas** [DefinitelyTyped/DefinitelyTyped#49241]
- [x] I tried using the `@types/react-select` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @claasahl @jonfreedman @Methuselah96 @thchia @danieldelcore @rjoonas

The type for `state` of NoOptionsMessage component is missing.

Intended use: Creating a custom NoOptionsMessage component

```tsx
import { components } from 'react-select';

export const NoOptionsMessage = (props: any) => {
  return (
    <>
      .... logic using props
      <components.NoOptionsMessage {...props} />
    </>
  );
};
```

The `any` in the above code could've been changed to `NoOptionsMessageProps` if that type was present.

**Comment by redbmk** [comment]
Have you tried using `NoticeProps`?

Looking at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/src/components/index.d.ts#L71 It might look something like:

```typescript
import { OptionTypeBase } from 'react-select/types';
import { components } from 'react-select';
import { NoticeProps } from 'react-select/components/Menu';

export const NoOptionsMessage<OptionType extends OptionTypeBase> = (props: NoticeProps<OptionType>) => {
  return (
    <>
      .... logic using state
      <components.NoOptionsMessage {...props} />
    </>
  );
};
```

**Comment by cseas** [comment]
That doesn't seem to work. I'm getting the following error:
![Selection_012](https://user-images.githubusercontent.com/29686866/97800180-3ada8a80-1c59-11eb-8272-738dcfa8f00c.png)

Version:
"react-select": "^3.1.0",
"@types/react-select": "^3.0.22",

**Comment by Methuselah96** [comment]
@cseas Try `'react-select/src/components/Menu'`.

**Comment by cseas** [comment]
I removed all the logic to check if the types even work. So here's my component now:
```tsx
import React from "react";
import { components, OptionTypeBase } from "react-select";
import { NoticeProps } from "react-select/src/components/Menu";

export const NoOptionsMessage<OptionType extends OptionTypeBase> = (props: NoticeProps<OptionType>) => {
  return (
    <>
      <components.NoOptionsMessage {...props} />
    </>
  );
};
```

And here's the error:
```
NoOptionsMessage.tsx: Unexpected token, expected ";" (24:29)
  22 | // }
  23 | 
> 24 | export const NoOptionsMessage<OptionType extends OptionTypeBase> = (props: NoticeProps<OptionType>) => {
     |                              ^
  25 |   return (
  26 |     <>
  27 |       <components.NoOptionsMessage {...props} />
```

**Comment by Methuselah96** [comment]
@cseas Yeah, feel free to add it to the main export. The `NoOptionsMessage` isn't the only component with those props, which is why it's not called `NoOptionsMessageProps`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
