### ISSUE TITLE
PropTypes.InferProps makes optional props incompatible with built-in React components

### ISSUE THREAD

**Issue by salemhilal** [DefinitelyTyped/DefinitelyTyped#49335]
- [X] I tried using the `@types/react` and `@types/prop-types` packages and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/). 
- [X] I'm mentioning the authors, but there appear to be a lot (especially for React), so I'm pinging the top 3 most recent contributors:
  - `@types/react` authors: @johnnyreilly, @bbenezech, @pzavolinsky
  - `@types/prop-types` authors: @DovydasNavickas, @ferdaber, @eps1lon

## The issue

* `PropTypes.InferProps` returns a props object that allows `null` and `undefined` for optional props. This makes sense, since prop type validating functions are ok with `null` and `undefined` if the prop is optional.
* Built-in React components, like `<a />`, define the type of optional props using the `?` signifier. For example, [the props for an anchor tag](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f80ccec07bd31b84033cf34fb1eca09dc9e07602/types/react/index.d.ts#L1931-L1941) specify that all of the props can either be defined as the given type, or undefined.
* If strict-null-checks are enabled, the results of `PropTypes.InferProps` collide with the accepted types on built-in React components.

## An example

I've reproduced this behavior here:
https://codesandbox.io/s/infer-prop-types-mismatch-8ybqj?file=/src/App.tsx

To save you a click, the code there looks like (roughly) like this:
```tsx
import * as React from "react";
import PropTypes from "prop-types";

const propTypes = {
  name: PropTypes.string
};

type Props = PropTypes.InferProps<typeof propTypes>;

export default function App(props: Props) {
  return (
    <div className="App">
      <h2 id={props.name}> // <-- error here
        The ID prop on this header has an invalid type assertion.
      </h2>
    </div>
  );
}
```

And the error looks like this:
```
(JSX attribute) React.HTMLAttributes<HTMLHeadingElement>.id?: string | undefined
Type 'string | null | undefined' is not assignable to type 'string | undefined'.
  Type 'null' is not assignable to type 'string | undefined'.ts(2322)
index.d.ts(1704, 9): The expected type comes from property 'id' which is declared here on type 'DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>'
```

## Solutions

* I'm unclear on what the right type-based solution would be here (I'm newer to TypeScript). 
* Practically speaking, I've stopped using `PropTypes.InferProps` since the effort it saves is somewhat offset by adding null checks to all of my props.
* It seems as though React components generally treat `null` and `undefined` identically (by not rendering those props) as far as I've been able to tell, although I don't know that this is always the case. If it is, expanding React's props to accept nulls on optional parameters could be a good solution.

This issue comes from my comment on a related issue here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/45094#issuecomment-715459689

**Comment by salemhilal** [comment]
Hey @eps1lon, sorry to tag you here but I saw you helped merge a PR for some React types recently. Do you know who the right people to tag in this issue are? I'm happy to open a pull request, but I don't know what the solution should be here.

**Comment by ferdaber** [comment]
Yeah this is really hard, we're super-hamstrung by the fact that the proptypes runtime allows both `null` and `undefined`. Do you know if host elements allow `null` in place of `undefined` for attributes?

**Comment by salemhilal** [comment]
@ferdaber if I understand what you’re asking, it seems as though they do. I haven’t been able to find a case in which `undefined` is treated differently than `null` in any native components.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
