### ISSUE TITLE
[@types/css-minimizer-webpack-plugin] Support for webpack 5

### ISSUE THREAD

**Issue by latipun7** [DefinitelyTyped/DefinitelyTyped#49354]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @peterblazejewicz

Error when tried to use the plugin in webpack 5 `minimizer` setting array.
```
Type 'CssMinimizerPlugin' is not assignable to type '((this: Compiler, compiler: Compiler) => void) | WebpackPluginInstance | "..."'.
  Type 'CssMinimizerPlugin' is not assignable to type '"..."'.ts(2322)
```

Webpack 5 now has its own type definition and didn't export `Plugin` instead exported `WebpackPluginInstance`.

**Comment by peterblazejewicz** [comment]
approved in #49355

**Comment by ybentz** [comment]
Looks like this is an issue again.
Webpack 5 comes with built-in types and [recommends](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#typescript-typings) removing the `@types/webpack` completely. This causes an error for me:

```
Type 'CssMinimizerPlugin' is not assignable to type '"..." | WebpackPluginInstance | ((this: Compiler, compiler: Compiler) => void)'.
  Type 'CssMinimizerPlugin' is not assignable to type 'WebpackPluginInstance'.
    Types of property 'apply' are incompatible.
      Types of parameters 'compiler' and 'compiler' are incompatible.
```
