### ISSUE TITLE
JQuery Types build error on typescript 2.4.1

### ISSUE THREAD

**Issue by hey24sheep** [DefinitelyTyped/DefinitelyTyped#49353]
I am having this build error I can't seem to fix it. It started after upgrading the project from 4.6.1 to 4.7.1. 

Currently in our project we have 4 projects with this Error. We are using old Angular and typescript for these 4 projects and we can't update at the moment. Is there any way to fix this error?

Solutions I have tried
- Upgrading/Downgrading typescript 
- changes to tsconfig
- changes to package.json with different versions latest and others

Current Info -
- Typescript as nuget package with 2.4.1 version
- .Net Version : 4.7.1
- Visual Studio 2019 version 16.7.6

Error - 
```
Build:Type '"button" | "view" | "screenX" | "screenY" | "altKey" | "bubbles" | "cancelable" | "changedTouches" | "ctrlKey" | "detail" | "eventPhase" | "metaKey" | "pageX" | "pageY" | "shiftKey" | ... 13 more ... | "touches"' does not satisfy the constraint '"button" | "code" | "view" | "location" | "screenX" | "screenY" | "height" | "width" | "altKey" | "bubbles" | "cancelable" | "changedTouches" | "ctrlKey" | "detail" | "eventPhase" | ... 55 more ... | "DOM_KEY_LOCATION_STANDARD"'.	node_modules\@types\jquery\index.d.ts	line: 8155	

```

Package.json
```
{
  "author": "",
  "dependencies": {
    "@types/kendo-ui": "^2017.3.1",
    "@types/spectrum": "^1.5.29",
    "@types/toastr": "^2.1.35",
    "@mdi/font": "^3.6.95",
    "flutter-cli": "0.0.15"
  },
  "devDependencies": {
    "@types/angular": "1.6.41",
    "@types/angular-gridster": "^0.13.3",
    "@types/angular-local-storage": "^0.6.0",
    "@types/angular-material": "^1.1.52",
    "@types/angular-ui-bootstrap": "^0.13.43",
    "@types/angular-ui-router": "^1.1.37",
    "@types/angular-ui-tree": "^2.8.31",
    "@types/jquery": "^3.2.5", // I have tried various versions but it doesn't seem to fix the error, It works fine on .net 4.6.1
    "@types/jquery.timeago": "^1.0.29",
    "@types/jqueryui": "^1.11.34",
    "@types/lodash": "4.14.67",
    "@types/lovefield": "^2.0.32",
    "@types/metismenu": "^2.6.1",
    "@types/oclazyload": "0.0.32",
    "@types/signalr": "^2.2.34",
    "@types/svg-pan-zoom": "3.3.0",
    "@types/ui-grid": "0.0.37",
    "gulp": "^4.0.0",
    "jasmine-core": "^2.5.2",
    "karma": "^2.0.4",
    "karma-chrome-launcher": "^2.0.0",
    "karma-jasmine": "^1.1.0",
    "karma-phantomjs-launcher": "^1.0.4",
    "pdfjs-dist": "^2.0.258"
  },
  },
  "version": "1.0.0"
}
```

tsconfig.json of 1 of those 4 projects. Every tsconfig is same and they all have their own tsconfigs in their own project folders.
```
{
  "compilerOptions": {
    "noEmitOnError": true,
    "noImplicitAny": true,
    "outFile": "../../outfile.js",
    "sourceMap": true,
    "sourceRoot": "/sourceRoot",
    "target": "es2015",// tried adding lib and changing this to es2016
    "typeRoots": [
      "../../node_modules/@types",
    ]
  },
  "compileOnSave": true
}
```

Any help would be appreciated. Thanks

**Comment by hey24sheep** [comment]
Can anyone please help me here?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
