### ISSUE TITLE
[@types/html-to-text] Support html-to-text 6

### ISSUE THREAD

**Issue by dqn** [DefinitelyTyped/DefinitelyTyped#49376]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @erykwarren, @CarsonF

Type definitions needs to be updated.

**Comment by CarsonF** [comment]
Looks like it was a major rewrite so new types will take some time. I'll try in the next few days.

**Comment by webstech** [comment]
@CarsonF Thanks for reviewing the PR when you get the time.

**Comment by dqn** [comment]
@webstech, @CarsonF It works. Thanks!
