### ISSUE TITLE
[material-ui] @types/material-ui doesn't seem to load after being installed

### ISSUE THREAD

**Issue by tim-rohrer** [DefinitelyTyped/DefinitelyTyped#49390]
- [x] I tried using the `@types/material-ui` package and had problems.

I am using Typescript 4.0.2, and am curious if perhaps that is the cause? 

The error I'm getting when I try to import from `material-ui` < v1:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/7756865/98330884-fe908c80-1fc0-11eb-8e90-183e5eb921aa.png">

`@types/material-ui` was installed with command:

`yarn install @types/material-ui --dev`

For good measure, I added `material-ui` to the array in my `tsconfig.json` file:
```
"types": [..., "material-ui"],
```

I've done all the things I've done before to load DefinitelyTyped definitions, but this is still giving the error like it isn't loaded.

- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

  - Authors: @ngbrown, @theigor, @alitaheri, @herrmanno, @DaIgeb, @allienna, @schlesingermatthias, @InsidersByte, @artyomsv, @dan-j, @minodisk, @samwalshnz, @reggino

**Comment by ngbrown** [comment]
Maybe try:

```ts
import {RefreshIndicator} from 'material-ui';
```

**Comment by tim-rohrer** [comment]
Thanks for the reply. Oddly, I came back to this project to try your idea, and the dang thing may have resolved itself :-) 

Anyway, I'll clean up the other issues and confirm the import actually works. If so, I'll close this.

**Comment by tim-rohrer** [comment]
@ngbrown I'm going to go ahead and close this as I:

1. could not get the error to re-occur
1. have come to realize RefreshIndicator is not being ported to the reworked code base for `material-ui`.

Thanks again for your quick response.
