### ISSUE TITLE
[@types/ramda]: Strange error with `mergeDeepLeft` + generics + extends

### ISSUE THREAD

**Issue by ranneyd** [DefinitelyTyped/DefinitelyTyped#49438]
I'm getting a very strange issue when I try to make a "partial setter" using generic types.

https://codesandbox.io/s/typesramda-mergedeepleft-w-generics-31yuc

What I'm trying to do:
- I have a state that includes a map with values of a certain object type (let's call it `Obj`).
- I want a "partial setter", where I give it a `Partial<Obj>` and a key, and it uses `mergeDeepLeft` to merge the partial object into the full state.
- When I make this function with the `Partial<Obj>`, everything works fine
- When I change it to `Partial<T>` where `T extends Obj`, I get this error:

```
'__MergeDeep<{ [x: string]: Partial<T>; }, Record<string, Obj>, 1, BuiltInObject, string>' is not assignable to type 'Record<string, Obj>'.
  Index signatures are incompatible.
    Type '_MergeDeep<Partial<T>, Obj, string, string, 1, BuiltInObject>' is not assignable to type 'Obj'.
      Type 'Obj | ChooseMergeDeep<Partial<T>, Obj, string, string, 1, BuiltInObject>' is not assignable to type 'Obj'.
        Type 'ChooseMergeDeep<Partial<T>, Obj, string, string, 1, BuiltInObject>' is not assignable to type 'Obj'.
          Type 'Obj | Exclude<Function & Partial<T>, null | undefined> | Exclude<RegExp & Partial<T>, null | undefined> | ... 19 more ... | (Partial<...> extends object ? __MergeDeep<...> : Obj | Exclude<...>)' is not assignable to type 'Obj'.
            Type 'Exclude<Function & Partial<T>, null | undefined>' is not assignable to type 'Obj'.
              Types of property 'foo' are incompatible.
                Type 'T["foo"] | undefined' is not assignable to type 'string'.
                  Type 'undefined' is not assignable to type 'string
```

How I read this is since `Partial<T>["foo"]` can be `undefined`, since it is `Partial`, the typings think we're setting that key to be `undefined` as opposed to falling back to said property in the second argument. However, it would be the exact same thing with `Obj` instead of `T extends Obj`, yet for just `Obj` it doesn't seem to care.

Any thoughts? I may totally be misreading this error and I may totally be missing some intricacies of typescript here, particularly surrounding generics.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
