### ISSUE TITLE
[@types/next-auth] Wrong types for getProviders method

### ISSUE THREAD

**Issue by SagnikPradhan** [DefinitelyTyped/DefinitelyTyped#49431]
- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @lluia @iaincollins @JuanM04 

Seems like the types for `getProviders` and `providers` method from `next-auth/client` is wrong. The method should return a promise containing an **array** of the providers but it is returning a promise containing an **object or null**.

**References** -
1. [Current Code](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/next-auth/client.d.ts#L39)
2. [Documentation](https://next-auth.js.org/getting-started/client#getproviders)

**Comment by SagnikPradhan** [comment]
Temporary Fix
```js
export const getStaticProps: GetStaticProps<{
  providers: SessionProvider[];
}> = async () => {
  return {
    props: {
      providers: ((await getProviders()) as unknown) as SessionProvider[],
    },
  };
};
```

**Comment by lluia** [comment]
Thanks for reporting the issue 💚 

Looking at the source code, [`getProviders`](https://github.com/nextauthjs/next-auth/blob/8115a7c66cdb1d86b0d2a0d76b9aa33c2bfaa33b/src/client/index.js#L136-L139) just calls the providers server endpoint, which in turn seems to return a [response with the following shape](https://github.com/nextauthjs/next-auth/blob/8115a7c66cdb1d86b0d2a0d76b9aa33c2bfaa33b/src/server/routes/providers.js#L8-L16):
```ts
{ [providerId: string]: ProviderObject }
```
Hence the [current types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/next-auth/client.d.ts#L39) we have for it seem mostly right; we could remove `| null` from them as that seems incorrect 🤔

**Comment by SagnikPradhan** [comment]
Weird. Seems like I was wrong (and there is no way I can check again cause I ended up scrapping the code 😅) Sorry for bugging, closing the issue.
