### ISSUE TITLE
[@types/babel__traverse] NodePath.get infers wrong type

### ISSUE THREAD

**Issue by gilbsgilbs** [DefinitelyTyped/DefinitelyTyped#49433]
- [x] I tried using the `@types/babel__traverse` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @yortus @marvinhagemeister @rpetrich @mgroenhoff @dlgrit @ifiokjr @ExE-Boss 

If you do not mention the authors the issue will be ignored.

---

The following snippet used to work, but now produces a TS error:

```typescript
function babelStuff(nodePath: NodePath) {
  if (nodePath.isMemberExpression()) {
    // nodePath is "NodePath<Node> & NodePath<MemberExpression>"
    const obj = nodePath.get("object");
    // Here, obj should be "NodePath<Expression>" but is now "NodePath<Node> | NodePath<Node>[]"
    // This is because TS picks definition from "NodePath.get(…)" instead of "NodePath.get<T>(…)".
    // As a consequence, doing this errors: "Property 'isIdentifier' does not exist on type 'NodePath<Node> | NodePath<Node>[]'"
    if (!obj.isIdentifier()) {
      console.log("obj is identifier");
    }
  }
}
```

I rely on this type-guard pattern a lot for a babel-plugin I maintain. The only workaround I have for now is to pass a generic type to "get" function explicitly:

```typescript
function babelStuff(nodePath: NodePath) {
  if (nodePath.isMemberExpression()) {
    //                       vvvvvvvv
    const obj = nodePath.get<"object">("object");
    // now "obj" has type "NodePath<Expression>" which allows:
    if (!obj.isIdentifier()) {
      console.log("obj is identifier");
    }
  }
}
```

But it's very cumbersome, and it's unclear why it regressed. I would expect TypeScript to be able to infer this type. Funny discovery: commenting out the non-generic definition of `get(…)` "fixes" the issue and makes TypeScript happy :thinking: . So TypeScript just knowingly picks the wrong definition from some reason, even though the generic-definition is somewhat correct.

I wasn't able to figure out which version of `babel__traverse` introduced the regression, but I suspect it is concomitant to a change in `@babel/types` (between v7.9.6 and 7.10.0+), which makes tracking the introduction of this bug a nightmare.

See also: https://github.com/babel/babel/issues/12336

Any help welcome. Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
