### ISSUE TITLE
[@types/socket.io-client] Cannot find namespace 'SocketIOClient'

### ISSUE THREAD

**Issue by zigang93** [DefinitelyTyped/DefinitelyTyped#49442]
Socket IO just release the version 3. I hope can update for support version
I believe this breaking changes cause the issue [link](https://socket.io/docs/migrating-from-2-x-to-3-0/#No-more-implicit-connection-to-the-default-namespace)

@florentpoujol @divillysausages @progre

**Comment by AviVahl** [comment]
it comes with a built in .d.ts file now.

**Comment by zigang93** [comment]
@AviVahl which mean I doesn't need to have this packages `@types/socket.io-client` anymore?

**Comment by AviVahl** [comment]
yep. not since v3.0.0.
