### ISSUE TITLE
[@types/mapbox-gl] Property 'mapContainer' does not exist on type 'Component'.ts(2339)

### ISSUE THREAD

**Issue by AveryTheDev** [DefinitelyTyped/DefinitelyTyped#49459]
I have a class component referencing a prop that I assume is being passed by a package I am using behind the scenes (mapbox-gl). My component, "Selection", claims the prop does not exist and I believe it is because I am using it in a tsx file now.

Warning I am getting

![image](https://user-images.githubusercontent.com/23192489/98702304-37758c00-2348-11eb-8e59-56a1b42acf4e.png)

Code:

```ts

import React, { Component } from "react";
import mapboxgl from "mapbox-gl";
import { MapContainer } from "../../styles";

const mapboxStyleURL = process.env.REACT_DARK_MODE_URL;
mapboxgl.accessToken = process.env.REACT_APP_MAPBOX_TOKEN;

class Selection extends Component<SelectionProps, SelectionState> {
  state = { lng: -81.6035, lat: 30.3501, zoom: 7.5, coordinateList: [] };

  configureMapOptions = (counties: string[], center: [number, number]) => {
    const { lng, lat } = this.state;

    const zoom_level = counties?.length > 0 ? 7.5 : 8;
    const map_center = center ? center : [lng, lat];

    return { zoom_level, map_center };
  };

  componentDidMount() {
    const { coordinates, polygons, center, counties } = this.props;
    const { zoom_level, map_center } = this.configureMapOptions(
      counties,
      center
    );

    const map = new mapboxgl.Map({
      container: this.mapContainer, //Error: Property 'mapContainer' does not exist on type 'Selection'.ts(2339)
      style: mapboxStyleURL,
      center: map_center,
      zoom: zoom_level,
    });
}


  render() {
    return (
      <div>
        <MapContainer>
          <div
            ref={(el) => (this.mapContainer = el)} //Error: Property 'mapContainer' does not exist on type 'Selection'.ts(2339)
            className="mapContainer"
          />
        </MapContainer>
      </div>
    );
  }
}

export default Selection;

interface SelectionProps {
  coordinates: number[];
  polygons: number[][][];
  center: [number, number];
  counties: string[];
}

interface SelectionState {
  lng: number;
  lat: number;
  zoom: number;
  coordinateList: number[];
}

```

I know that this code works in vanilla JS. Is there any way I can override this warning?

Authors: @dobrud @patrickr @macobo

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
