### ISSUE TITLE
[@types/mongoose] Unable to use async iterator

### ISSUE THREAD

**Issue by cjroebuck** [DefinitelyTyped/DefinitelyTyped#49494]
According to https://mongoosejs.com/docs/api/querycursor.html#query_Query-Symbol.asyncIterator, should be able to use DocumentQuery like so:

```ts

const userQuery = User.find({});

for await (const user of userQuery){
   // ...do something sync/async with user...
}

```
But getting error message from ts:
```
Type 'DocumentQuery<IUser[], IUser, {}>' must have a '[Symbol.asyncIterator]()' method that returns an async iterator.

104   for await (const user of userQuery){

Did you forget to use 'await'?
```

Works ok / type checks if I append ```.cursor()``` to the query

@horiuchi @lukasz-zak @jendrikw @ethanresnick @vologab

**Comment by borfig** [comment]
`[Symbol.asyncIterator]()` is indeed missing from `DocumentQuery<T, DocType extends Document, QueryHelpers = {}>`.
A proposed fix is at #49552.
