### ISSUE TITLE
[@types/auth0] passwordGrant() is missing `forwardedFor`

### ISSUE THREAD

**Issue by vicary** [DefinitelyTyped/DefinitelyTyped#49503]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @donaldpipowitch, @amiram, @wbhob, @pacey, @andy-ms, @westy92, @paulvanbrenk, @jussikinnula, @neshanjo, @akvamalin, @djmc, @dancrumb, @Gus-vcx, @saurabh73, @xTNTx, @segayuu, @ricardo-devis-agullo, @rameshanandakrishnan, @peterblazejewicz, @orangain, @mbfisher, @MengRS, @ashton, @lukasvan3l, @kkirsche, @kainoffke, @JulienDuf, @ianhowe76, @matt-oakes, @matchai, @danielglasgow, @clementheliou, @CatGuardian, @alexbjorlig, @duro, @isabela-morais, @pwrnrd

First of all, sorry for mentioning every single one of the contributors of `@types/auth0` here. Because my questions in the official support forum is simply ignored and I'd like comments from the community.

I believe this issue is broader than the title means.

For example, the `ManagementClient#passwordGrant()` method in fact allows a second object as argument, while it is totally undocumented, from online discussions I know that at least `{ forwadedFor }` is taken to have the SDK send `Auth0-Forwarded-For` header.

Shall we dig into the js source and type all of them? Or shall we deliberately ignore them and stick with officially documented features only and let typechecks fails?

**Comment by alexbjorlig** [comment]
Hi @vicary - no worries about the mention. It's after all only one e-mail, and people can unsubscribe if they don't want to be notified. I think the typings should document the js source - if the documentation is missing that is just another 🐛

**Comment by neshanjo** [comment]
@vicary The next time, please just mention the _current_ authors listed in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/auth0/index.d.ts Thanks!

**Comment by wbhob** [comment]
i haven’t used auth0 in a few years, but my intuition says to stick to officially documented properties. if our types diverge from their docs, then people may open issues asking for explanation of features we don’t fully understand. may be best to wait for official word from auth0

--
*Wilson Hobbs*

Schedule a meeting: scheduletime.withwilson.xyz ( https://scheduletime.withwilson.xyz )

Sent via Superhuman iOS ( https://sprh.mn/?vip=wilsonhobbs1@gmail.com )

**Comment by vicary** [comment]
auth0 has responded, see the issue in official repo referenced above, that they are going to maintain types officially, closing this one in favour of that.

**Comment by adrienne-98point6** [comment]
@vicary could we reopen this issue until auth0 has created a viable alternative types library? Their latest comment is open-ended about when they will begin to maintain types.

**Comment by vicary** [comment]
> @vicary could we reopen this issue until auth0 has created a viable alternative types library? Their latest comment is open-ended about when they will begin to maintain types.

@adrienne-98point6 Depends on how do you, or we the community, define the scope of this issue, that whether `DefinitelyTyped` should type against undocumented features.

As a reply from my statement above, you may ask "should it be documented?". But their official stance for this is still kind of unclear because this parameter only appears in isolated replies of their community forum.

Pragmatically said, it's not an easy task to reverse engineer at code level, while keeping track to all future versions.

What do you think?
