### ISSUE TITLE
[@types/yup] property `from` missing in TestContext

### ISSUE THREAD

**Issue by StudioSpindle** [DefinitelyTyped/DefinitelyTyped#49512]
@dhardtke @vtserman @MoretonBayRC @sseppola @YashdalfTheGray @vincentjames501 @robertbullen @sat0yu @deskoh @mauricedb @kalley @elias-garcia @iansan5653 @fjc0k

Given the following situation TS throws an error:

```ts
const schema = yup.object().shape({
  people: yup.array().of(
    yup.object().shape({
      name: yup.mixed().test({
        name: "example",
        message: "example",
        test() {

          // Property 'from' does not exist on type 'TestContext<object>'.
          const { from } = this;

          return true;
        }
      }),
      age: yup.number(),
    })
  )
});
```

But since it's a descendant of an array the `from` property does exist.

Created a stackblitz example: https://stackblitz.com/edit/typescript-94qntg

**Comment by StudioSpindle** [comment]
It's possible to circumvent this issue by typecasting `this` with an extended interface:

```ts
interface Person {
  name: string;
  age: number;
}

const schema = yup.object().shape({
  people: yup.array().of(
    yup.object().shape({
      name: yup.mixed().test({
        name: "thing",
        message: "thing",
        test() {
          const { from } = this as yup.TestContext & { from: yup.ArraySchema<Person[]> };
          console.log(from);
          return true;
        }
      })
    })
  )
});
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by SalahAdDin** [comment]
> It's possible to circumvent this issue by typecasting `this` with an extended interface:
> 
> ```ts
> interface Person {
>   name: string;
>   age: number;
> }
> 
> interface TestContextExtended {
>   from: {
>     schema: ObjectSchema;
>     value: Person;
>   }[];
> }
> 
> const schema = yup.object().shape({
>   people: yup.array().of(
>     yup.object().shape({
>       name: yup.mixed().test({
>         name: "thing",
>         message: "thing",
>         test() {
>           const { from } = this as yup.TestContext & TestContextExtended;
>           console.log(from);
>           return true;
>         }
>       }),
>       age: yup.number(),
>     })
>   )
> });
> ```
> 
> Working code example: https://stackblitz.com/edit/typescript-9qhxre

It didn't works for me, and this issue has two years, why  is there any advance on this?

Thank you

**Comment by mauricedb** [comment]
Yup has been rewritten in TypeScript some time ago and these type definitions are no longer required as Yup now ships with it's own up to date type definitions. If the issue still persist with those I suggest creating an issue in the Yup repository.

Maurice
