### ISSUE TITLE
Rogue dependency defined in historic @types package prevents unpublishing of unrelated packages on npm

### ISSUE THREAD

**Issue by yGuy** [DefinitelyTyped/DefinitelyTyped#49514]
We just found that there is a years old package for our software which has a package.json dependency with a "*" version specified on a software package declared in the package.json of the otherwise empty @types package.

This is actually a severe problem because if someone accidentally publishes a version of their package and there is a "rogue dependency" like this on that version, this prevents npm from letting you unpublish any version.

I feel like this is actually an npm bug, because this not a real "dependency". In fact the @types package is many years older than the package for which they are now trying to unpublish a version. They uploaded a version and now the 3 years old @types dependency prevents them from unpublishing the version, literally even minutes after they accidentally published it.

Still, the quickest way to resolve this would be to get rid of the "*" dependency in the package.json. However I failed to find the appropriate file in this repository. It was removed long ago from the repo by @RyanCavanaugh  in this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b1ce7a35258f743add189c27f3c422ea7127fb6d  - but it's still available on NPM: https://www.npmjs.com/package/@types/yfiles 

Now how can we adjust the package.json or deprecate that @types package on NPM in order to remove the rogue dependency on the the software package that someone else accidentally published so that they again can unpublish it?

Your quick help is greatly appreciated in this regard since we are approaching the 72 hour limit during which the package can be regularly unpublished.

@sandersn - can you please help with this or ping someone who can?

It worries me that anyone could just publish a package on npm, depend on arbitrary package names using "*" and thus prevent everyone else from ever unpublishing a package again. Yes, this is an npm issue, but please help, because in this case the @types package is the problem. Thanks!

**Comment by sandersn** [comment]
The problem is with the deprecated version, right?

**Comment by sandersn** [comment]
The normal place where we hold realtime conversations is [discord](discord.gg/typescript) -- might be easier to figure this out over there.

**Comment by sandersn** [comment]
Looks like npm-support unpublished this right after you left this comment. Do you still need our help? I guess a workaround would be to manually publish a new version of `@types/yfiles` which doesn't have the dependency. But there's no way for us to unpublish the current version, even if it would no longer be `latest`.

**Comment by yGuy** [comment]
Thanks, Nathan - actually I also reported the underlying problem to the npm team, after I opened this issue: https://github.com/npm/cli/issues/2165 

The immanent problem has been resolved in the meantime via an DMCA takedown request, so the priority for this is relatively low, now, from my personal point of view. 
I guess though, that the issue is that this could happen to others too, if a @types package gets published with the "*" dependency, you immediately prevent that package from ever being able to unpublish any versions again, cleanly, with the current npm implementation. 
The additional problem or issue that could be discussed here was that the specific package in question here was removed long ago from definitely typed, but it's still there as npm @type package, but not declared as deprecated (in which case I would hope npm would not regard it as a blocking depending project, anymore). The question is, should packages that get removed from this repo be automatically declared deprecated in npm types? And if not, should at least the dependencies be adjusted to only depend on compatible versions that existed at the time the package got removed from here? That could save others from a lot of troubles.

**Comment by sandersn** [comment]
Actually, it is deprecated, so npm's rule apparently applies there as well.

```
$ npm info @types/yfiles

@types/yfiles@2.1.0 | MIT | deps: 1 | versions: 22
Stub TypeScript definitions entry for yFiles for HTML, which provides its own types definitions

DEPRECATED ⚠️  - This is a stub types definition for yFiles for HTML (none). yFiles for HTML provides its own type definitions, so you don't need @types/yfiles installed!
```

The reason to use `"*"` is that if you install a deprecated `@types/X`, we want you to get the newest X if you don't already have it. But if you DO have it already, we don't want to install another version.

This isn't very useful, so it may make sense to drop the dependency entirely. I'll discuss it with the team.

**Comment by sandersn** [comment]
I opened https://github.com/microsoft/DefinitelyTyped-tools/pull/171 for commentary.

**Comment by RyanCavanaugh** [comment]
We don't plan to make any policy or technical changes as a result of this incident
