### ISSUE TITLE
Module '"../../webpack/types"' has no exported member 'Plugin'

### ISSUE THREAD

**Issue by Joshanity17** [DefinitelyTyped/DefinitelyTyped#49528]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/copy-webpack-plugin` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @peterblazejewicz 

`@types/copy-webpack-plugin`: **6.2.0**
`typescript`: **4.0.5**
`@types/webpack`: **4.41.25**

Whenever I try to build, I am getting this error
```
node_modules/@types/copy-webpack-plugin/index.d.ts(7,10): error TS2305: Module '"../../webpack/types"' has no exported member 'Plugin'.
```
I checked the `@types/webpack` and it seems that there are really no `Plugin` included in the export of it. I tried deleting the reference of `@types/copy-webpack-plugin` to `import { Plugin } from 'webpack';` and it works. However, I look at the [commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/1f79e9a86dec82f1be5131cebd522dfbe1e00710) for this and it seems like it is a fix for backward compatibility for no apparent reason.

**Comment by Joshanity17** [comment]
It seems that `import { Plugin } from 'webpack';` is referencing to [`webpack's types.d.ts`](https://github.com/webpack/webpack/blob/master/types.d.ts) directly instead of [`@types/webpack`](https://github.com/Joshanity17/DefinitelyTyped/blob/master/types/webpack/next.d.ts)

**Comment by dl748** [comment]
Looks like your commit failed.  I was able to get it to work by replacing it with the correct typings

```
import { Plugin } from 'webpack';
```
replaced with
```
import { WebpackPluginInstance as Plugin } from 'webpack';
```

**Comment by dl748** [comment]
Looks like your issue is that you are using webpack 4 typings when you've clearly updated to webpack 5.  copy-webpack-plugin should not be using the @types/webpack anymore but rather use the webpack buildin typings just like typescript does.

**Comment by nzjony** [comment]
Not sure if I should create a separate issue or hijack this one, but there are other issues with webpack 5, see: https://github.com/nzjony/copy-webpack-plugin-types-typescript-test

**Comment by Joshanity17** [comment]
@nzjony feel free to hijack it. I just stop because I think the CI/CD itself blocks relative path referencing. I think the typings that's included to the webpack module itself isn't aligned to what is in definitely typed

**Comment by dl748** [comment]
Also, see this issue I raised as well https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49757

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by u007** [comment]
i actually got the opposite when i upgraded my nuxt to 2.15.7, with error:
```
Module '"webpack"' has no exported member 'WebpackPluginInstance'
```

my fix was installing latest @types/webpack
```
npm i --save-dev @types/webpack
```
