### ISSUE TITLE
Property 'type' does not exist on type 'HTMLInputElement'

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [DefinitelyTyped/DefinitelyTyped#49568]
"@types/react": "^16.9.56",

![image](https://user-images.githubusercontent.com/69426460/99156014-916eac80-26ce-11eb-8aa1-488a789256de.png)

![image](https://user-images.githubusercontent.com/69426460/99156015-992e5100-26ce-11eb-90ca-fe082c406446.png)

**Comment by iamkacperwasik** [comment]
const type = (event as HTMLInputElement).type;

switch(type) {
   //...
}

**Comment by MaxmaxmaximusAWS** [comment]
yes but isn't that a bug of types?

**Comment by iamkacperwasik** [comment]
oh, my bad

here is the correct one:
const type = (e as ChangeEvent<HTMLInputElement>).target.type;

**Comment by iamkacperwasik** [comment]
oh, my bad

here is the correct one:
const type = (e as ChangeEvent<HTMLInputElement>).target.type;

**Comment by MaxmaxmaximusAWS** [comment]
do you mean that react is not able to understand without my prompts what type of event will come to the handler?

**Comment by iamkacperwasik** [comment]
> do you mean that react is not able to understand without my prompts what type of event will come to the handler?

It actually can. React uses something called [SyntheticEvent](https://reactjs.org/docs/events.html#form-events).
It's a wrapper around the browser’s native event.

![image](https://user-images.githubusercontent.com/57839948/104120810-ff83c880-5339-11eb-9422-a2b370b49fb9.png)


> the error says that typescript understands that event.target it is HTMLInputElement, but it does not find the type property of this element. Isn't that a type definition error?

I changed @types/react to 16.9.56 and @types/react-dom to 16.9.10 and everything works fine

![image](https://user-images.githubusercontent.com/57839948/104120558-0a3d5e00-5338-11eb-8765-0bee4ca621b0.png)
