### ISSUE TITLE
[@types/mongoose] MongooseUpdateQuery.push? is undefined 

### ISSUE THREAD

**Issue by notaphplover** [DefinitelyTyped/DefinitelyTyped#49563]
- [x] I tried using the `@types/mongoose` v5.10.0 package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] Mention the Authors: @horiuchi @lukasz-zak @jendrikw @ethanresnick @vologab

Given any type `T extends Document`, `Pick<MongooseUpdateQuery<Document>, '$push'>` is equal to `{ $push?: undefined; }`.

I expect to be able to use `MongooseUpdateQuery` to push elements in a subdocument.

Minimal example:

```Typescript
import { Document, MongooseUpdateQuery } from 'mongoose';

interface Foo extends Document {
  nonArrayProperty: number;
  bar: number[];
}

const query: MongooseUpdateQuery<Foo> = {
  $push: {
    bar: 2,
  },
};

```
[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEQgYwK4gKYDsYA0cAshLgOYQQDO2AqmACYCGM2AihtlAJ5wC+cAGZQIIOAHIQZSjWwSA3ACglwfNyHM02OADEqcbAA82uRtRToseeAiVw4uMgEEoUZjwAKosNxg8ALkcsACNuZQcQ5igg3FDuAG0AXWV+FTQyangARy5eINIKKloGFjZObh4AHn0IAD44AF5EezgAEjAMagALILsHSOiggCYCVv4x-gUgA)

On the other hand, no errors are thrown applying the same process to a type T which does not extends the `Document` class:

```Typescript
import { MongooseUpdateQuery } from 'mongoose';

interface Foo {
  nonArrayProperty: number;
  bar: number[];
}

const query: MongooseUpdateQuery<Foo> = {
  $push: {
    bar: 2,
  },
};

```
[Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgWQgOwOYQgZwKYCqYAJgIYx4CKArnlAJ5wC+cAZlBCHAOQjpa483ANwAoUcDQUorUgGM8cAGLZEouHDToAglCil6ABQ5g6MegC5N1EACM6YjbdJQraG-agBtALpim4nLoOPAAjrQMVqiY2PhEZBQ0dPQAPCoQAHxwALxqGgAkYNQ4ABZWCOoacM6ucABMADSVTE1MwkA)

Is this the expected behavior?

### Additional information

It seems there is a conflict at mongodb `PushOperator` type when `TSchema extends Document`. `PushOperator<Document>` is equal to `never`.

If we explore the mongodb `PushOperator` type:

```Typescript

export type PushOperator<TSchema> = ({
    readonly [key in KeysOfAType<TSchema, ReadonlyArray<any>>]?:
        | UpdateOptionalId<Unpacked<TSchema[key]>>
        | ArrayOperator<Array<UpdateOptionalId<Unpacked<TSchema[key]>>>>;
} &
    NotAcceptedFields<TSchema, ReadonlyArray<any>>) & {
    readonly [key: string]: ArrayOperator<any> | any;
};

```

We can see two intersections of types. If we try:

```Typescript
type SimplifiedPushOperator<TSchema> = ({
    readonly [key in KeysOfAType<TSchema, ReadonlyArray<any>>]?:
        | UpdateOptionalId<Unpacked<TSchema[key]>>
        | ArrayOperator<Array<UpdateOptionalId<Unpacked<TSchema[key]>>>>;
} &
    NotAcceptedFields<TSchema, ReadonlyArray<any>>);

type DocumentSimplifiedPushOperator = SimplifiedPushOperator<Document>
```

The type `DocumentSimplifiedPushOperator` is equal to `never`, so we can asume there must be a conflict in that type intersection.

### Additional information 2

Looking at your types:

```Typescript
 export type MongooseUpdateQuery<S> = mongodb.UpdateQuery<S> & mongodb.MatchKeysAndValues<S>;
```

The following change would probably solve the issue:

```diff
- export type MongooseUpdateQuery<S> = mongodb.UpdateQuery<S> & mongodb.MatchKeysAndValues<S>;
+ export type MongooseUpdateQuery<S> = mongodb.UpdateQuery<DocumentDefinition<S>> & mongodb.MatchKeysAndValues<DocumentDefinition<S>>;
```

But there's probably a good reason to not to do that change.

### Additional information 3

It seems you have `UpdateQuery` which is

```Typescript
export type UpdateQuery<D> = MongooseUpdateQuery<DocumentDefinition<D>>;
```

It feels a bit confusing, it's not easy to figure out when I should use `MongooseUpdateQuery` over `UpdateQuery`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
