### ISSUE TITLE
angular ui-grid api

### ISSUE THREAD

**Issue by raysuelzer** [DefinitelyTyped/DefinitelyTyped#4958]
@btesser -- Thanks for your work on this.  I'm looking at the GridAPI and it is "incomplete".  I say incomplete because it appears that ui-grid services (select) for example have public API's that register themselves with the core api.

So, in my code I would have something like:

```
onRegisterApi: (gridApi) => {
                    gridApi.selection.on.rowSelectionChanged($scope, (row) => {
                       foo(row)
                    });
```

Would it be problematic for me to add the features such as 'selection, pagination, etc' as types on the IGridAPI definition? 

I'd be happy to put in a PR.  

Thanks.

**Comment by raysuelzer** [comment]
I put in a PR here: https://github.com/borisyankov/DefinitelyTyped/pull/4960

**Comment by btesser-r7** [comment]
This has been resolved.... It can be closed @vvakame

**Comment by vvakame** [comment]
:+1:
