### ISSUE TITLE
[@types/react] Type safety violation by default value for component state

### ISSUE THREAD

**Issue by sg495** [DefinitelyTyped/DefinitelyTyped#49631]
Checklist:

- [✓] I tried using the `@types/react` package and had problems.
- [✓] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [✓] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [✓] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [✓] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei @jessidhia @saranshkataria @lukyth @eps1lon @zieka @dancerphil @dimitropoulos @disjukr @vhfmag @hellatan

Unless a value is explicitly assigned in the constructor, the property `state` in `React.Component<P, S, SS>` has the default value `undefined`, regardless of the specific type passed to the relevant type parameter `S`. This leads to a violation of type safety: the following minimal code example compiles without error but raises `TypeError` at runtime, with error message `"Cannot read property 'value' of undefined"`.

```ts
import React from 'react';
class MyComponent extends React.Component<{}, {value: string}> {
  constructor(props: {}) {
    super(props);
    console.log(this.state.value);
  }
}
new MyComponent({}); // Compiles OK, TypeError at runtime.
```

Furthermore, the value `undefined` is not actually assignable to the empty object literal type `{}`, the default value for the type parameter `S`. The type `undefined` (which makes it type-safe for `state` to have the default value `undefined`) is allowed as a value for the type parameter `S` of `React.Component<P, S, SS>`, because the type parameters are unbounded. However, using `undefined` (or `null`) will cause a static error, because `state` in a JSX element is expected to be of type `Readonly<{}>`. This is shown by the following minimal code example:

```ts
import React from 'react';
import ReactDOM from 'react-dom';
class MyComponent extends React.Component<{}, undefined> { }
ReactDOM.render(
  <MyComponent />,
  document.getElementById("root")
);
/* Error 2786:
'MyComponent' cannot be used as a JSX component.
  Its instance type 'MyComponent' is not a valid JSX element.
    Types of property 'state' are incompatible.
      Type 'undefined' is not assignable to type 'Readonly<{}>'.
*/
```

Using `React.createElement` also raises a slightly different error:

```ts
import React from 'react';
class MyComponent extends React.Component<{}, undefined> { }
React.createElement(MyComponent, {});
/* Error 2769:
No overload matches this call.
  The last overload gave the following error.
  Argument of type 'typeof MyComponent' is not assignable to parameter
  of type 'string | ComponentClass<{}, any> | FunctionComponent<{}>'.
    Type 'typeof MyComponent' is not assignable to type 'ComponentClass<{}, any>'.
      Construct signature return types 'MyComponent'
      and 'Component<{}, any, any>' are incompatible.
        The types of 'state' are incompatible between these types.
          Type 'undefined' is not assignable to type 'Readonly<any>'
*/
```

PS: The very last statement in the error might be a bit confusing to some future readers. As far as I'm aware, it is due to the fact that `Readonly<T>` is a mapped type, so that only object values are assignable to it. The following minimal code example shows this.

```ts
type Readonly<T> = {
  readonly [P in keyof T]: T[P];
};
let x: Readonly<any> = undefined;
/* Error 2322:
Type 'undefined' is not assignable to type 'Readonly<any>'.
*/
```

**Comment by eps1lon** [comment]
Could you share the actual code you're using? You're not supposed to construct React components manually.

`class MyComponent extends React.Component<{}, {}> ` seems to do just fine.

**Comment by ferdaber** [comment]
Right, the typings assume that you are using `React.Component` using actual React. In the React runtime it will automatically set `this.state` as an empty object if you choose to run stateless, and instantiating components are also forbidden by the framework, so neither of those use cases should be used in real life code.

**Comment by sg495** [comment]
I `new`ed the component just to show the issue without additional dependencies, the problem arose using React the normal way. Specifically, putting the following code in `index.tsx` of a fresh React app created with Create React App gives the exact same error:

```ts
import React from 'react';
import ReactDOM from 'react-dom';
class MyComponent extends React.Component<{}, { value: string }> {
  constructor(props: {}) {
    super(props);
    console.log(this.state.value);
  }
}

ReactDOM.render(
  <MyComponent />,
  document.getElementById("root")
);
```

The following code, which shows a totally legitimate use case for a component, gives _almost_ the same error (`index.tsx:76 Uncaught TypeError: Cannot read property 'value' of null`), showing that `this.state` is not actually initialized to an empty object:

```ts
import React from 'react';
import ReactDOM from 'react-dom';
class MyComponent extends React.Component<{}, { value: string }> {
  render() {
    return <h1>{this.state.value}</h1>
  }
}

ReactDOM.render(
  <MyComponent />,
  document.getElementById("root")
);
```

Indeed, it seems that `state` is set to `null`, as shown by running `console.log(this.state)` in `render`:

```
MyComponent {props: {…}, context: {…}, refs: {…}, updater: {…}, _reactInternals: FiberNode, …}
context: {}
props: {}
refs: {}
state: null
updater: {isMounted: ƒ, enqueueSetState: ƒ, enqueueReplaceState: ƒ, enqueueForceUpdate: ƒ}
_reactInternalInstance: {_processChildContext: ƒ}
_reactInternals: FiberNode {tag: 1, key: null, stateNode: MyComponent, elementType: ƒ, type: ƒ, …}
isMounted: (...)
replaceState: (...)
__proto__: Component
```

Finally, this would be a type-safety violation even if `state` were initialised to the empty object.

**Comment by ferdaber** [comment]
Ah so it sounds like state for class components are initialized as `null`.

**Comment by ferdaber** [comment]
I played around with this some more, the issue seems to be a bit more profound than a mistyped interface. It looks to be that the error is coming from the assignability check to `JSX.ElementClass`, however changing to:

```ts
declare namespace JSX {
  interface ElementClass extends React.Component<any, any> {
    render(): React.ReactNode;
  }
}
```

Doesn't solve the issue. From what I can see, TS does not consider `null` to be assignable to `Readonly<any>`, which is strange...

**Comment by ferdaber** [comment]
It seems that TS will not resolve `Readonly<any>` to `any`, it defers type resolution and keeps it as a mapped type, thus the assignability check failure.

**Comment by sg495** [comment]
I think the issue there is that that `Readonly<any>` is  mapped type:

```ts
type Readonly<T> = {
    readonly [P in keyof T]: T[P];
};
```

As such, it is an object type and neither `null` nor `undefined` will be assignable to it. Also, it is not quite the same as `any`, because writing is disallowed on its properties.

**Comment by sg495** [comment]
Changing the type for `state` from `state: Readonly<S>;` to `state: Readonly<S> | null | undefined;` at line 499 of `index.d.ts` ends up raising the correct error `Object is possibly 'null' or 'undefined'.` in the body of `render()` for the following code:

```ts
import React from 'react';
import ReactDOM from 'react-dom';
class MyComponent extends React.Component<{}, { value: string }> {
  render() {
    return <h1>{this.state.value}</h1>
  }
}
ReactDOM.render(
  <MyComponent />,
  document.getElementById("root")
);
```

This forces users to explicitly declare `state` with the desired type, in which case they have to initialize it in the constructor (as specified by the React documentation). The following code gives a working example:

```ts
import React from 'react';
import ReactDOM from 'react-dom';
class MyComponent extends React.Component<{}, { value: string }> {
  state: { value: string }
  constructor(props: {}) {
    super(props);
    this.state = {
      value: "hello"
    };
  }
  render() {
    return <h1>{this.state.value}</h1> // OK
  }
}
ReactDOM.render(
  <MyComponent />,
  document.getElementById("root")
);
```

The reason I included both `undefined` and `null` is that state is `undefined` after the constructor of `React.Component` and `null` after the JSX element has been created: having both covers the default values in both scenarios. I don't necessarily think this is an optional solution, by the way, or even a solution at all 😄. But it does capture this particular aspect of the `state` property initialization.

**Comment by ferdaber** [comment]
The issue with making state nullable is that despite the property being properly overridden by the explicit assignment in the constructor, all of the lifecycle methods use the `super` type of the state, which would make them all nullable, making it super inconvenient.

**Comment by ferdaber** [comment]
I think the only way to properly resolve this is to change `ElementClass` so that it doesn't extend from a regular React component, but one that has non-readonly instance properties, or even a larger supertype than that. Presumably very few people use that interface directly so it's a safer one to change.

**Comment by sg495** [comment]
I mean: _technically_ the super type of `state` should be nullable, because `state` _can_ be `null` in legitimate use cases. For example, the implementation of `setState` deals with the case where `state` is `null` by setting it to the given object, as can be seen running the following example:

```ts
// import React from 'react';
// import ReactDOM from 'react-dom';
class MyComponent extends React.Component<{}, {value: string}> {
  handleOnClick() {
    this.setState({ value: "hello" });
  }
  render() {
    console.log(this.state);
    return (
      <div>
        <button onClick={this.handleOnClick.bind(this)}>set state</button>
        <h1>Okay, Houston, we've had a problem here.</h1>
      </div>
    );
  }
}
ReactDOM.render(
  <MyComponent />,
  document.getElementById("root")
);
```

Before clocking the button, `null` is logged to console. After clicking the button, `{value: "hello"}` is logged to console. No error is raised at any point (neither static nor runtime).

**Comment by sg495** [comment]
Would changes to `ElementClass` have an effect inside classes extending `React.Component`? Because that's where most of the incorrect usage of `state` might happen, in my view. 

Ideally the best solution would be some change which results in correct code if `state` is initialised in the constructor (which everyone using state should do anyway) without the need to provide an explicit type for `state` in the class (as I've done in a previous example). I'm not sure this is doable though.

**Comment by ferdaber** [comment]
> I mean: _technically_ the super type of `state` should be nullable, because `state` _can_ be `null` in legitimate use cases. For example, the implementation of `setState` deals with the case where `state` is `null` by setting it to the given object, as can be seen running the following example:

> (It is true that the documentation of React prescribes that state should be set in the constructor when used, but the prescription (e.g. at [reactjs.org/docs/state-and-lifecycle.html#adding-local-state-to-a-class](https://reactjs.org/docs/state-and-lifecycle.html#adding-local-state-to-a-class)) is not particularly firm, and the behaviour of `setState` on `null` seems to reflect a tolerant approach to uninitialized state.)

Yes, but as maintainers of typings we have to balance convenience with type safety. This is often brought up time and again especially with users of such a large library like React. I am willing to bet that people are more than happy to sacrifice type safety in this case by conforming to setting their state initially always, over always having to null-check in their lifecycle methods (though I don't know how often class components are being used nowadays).

And no, as far as I can tell, changes to `ElementClass` only affects TypeScript's own typechecking against what types are available to use as JSX constructors, so it should be transparent to consumers unless they are using `ElementClass` directly. We do have type tests in the repo that will catch that.
