### ISSUE TITLE
[@types/mongoose] Missing properties in Map items types

### ISSUE THREAD

**Issue by ialexi-bl** [DefinitelyTyped/DefinitelyTyped#49652]
- [x ] I tried using the `@types/mongoose` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@horiuchi
@lukasz-zak
@jendrikw
@ethanresnick
@vologab
@jussikinnula
@ondratra
@alfirin
@idandrd
@various89
@Fazendaaa
@NormanPerrin
@stablio
@emmanuelgautier
@frontendmonster
@mingchen
@penumbra1
@orblazer
@HughKu
@niuware
@Vladmel1234
@jloveridge
@grimmer0125
@richarddd
@ToucheSir
@borfig
@dinodeSimon
@anthony-kenikh
@iamchathu
@lkho
@tomyam1
@nephix
@rlaace423
@chazepps
@avaly
@JanNemcik
@cl3dson
@richardsimko
@ith
@jeremyben
@andreialecu
@tHBp

I have a document that contains a field of type `Map`:

```ts
import { Types } from 'mongoose'

interface MyDocument {
  map: Types.Map<{ foo: number, bar: number }>
}
```

Now I'm trying to spread it:

```ts
const doc = MyModel.findOne({})

const item = doc.map.get('item1')!
doc.map.set('item2', {
  ...item,
  bar: 0
})
```

This doesn't work, because `item` actually turns out to contain a bunch of mongoose properties like `$parent`, `$isSingleNested`, etc. and the actual properties `foo` and `bar` are not spread, because AFAIU they are getters, so this doesn't work.

I can fix this by calling `toObject` on the `item`:

```ts
doc.map.set('item2', {
   ...item.toObject(),
  bar: 0
})
```

But now typescript complains that `Property "toObject" doesn't exist on type { foo: number, bar: number }`

So maybe `Types.Map<V>` should not just extend `Map<string, V>`, but also wrap `V` to add mongoose methods?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
