### ISSUE TITLE
[@types/d3-scale] ScaleQuantized is missing the thresholds() function

### ISSUE THREAD

**Issue by pekkapulli** [DefinitelyTyped/DefinitelyTyped#49664]
Hi, I couldn't find a typing for the `thresholds()` function that returns the computed domain from inside the scale. I'm not familiar with how to make PRs for types, so I'm wondering if someone could help?

- [x] I tried using the `@types/d3-scale` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek, @gustavderdrache, @borisyankov, @denisname, @rulonder, @Methuselah96

**Comment by Methuselah96** [comment]
I'm not sure what you're referring to. Can you provide a code sample?

**Comment by Methuselah96** [comment]
Made a PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49665

**Comment by pekkapulli** [comment]
Thanks, @Methuselah96, you're a hero!
