### ISSUE TITLE
[@types/puppeteer] Missing returns 'ElementHandle' in page.evaluateHandle 

### ISSUE THREAD

**Issue by dreamwayjgs** [DefinitelyTyped/DefinitelyTyped#49681]
Hello! The latest official document says [page.evaluateHandle](https://pptr.dev/#?product=Puppeteer&version=main&show=api-pageevaluatehandlepagefunction-args) could return Promise<JSHandle|ElementHandle>, but there is no return type 'ElementHandle' in <code>index.d.ts</code>.

In <code>puppeteer-test.ts</code>, 'ElementHandle' object is derived from 'asElement()' method of 'JSHandle.'

Is this intended? If I'd skip typing with <code>any</code> keyword when using page.evaluateHandle, it works anyway without using 'asElement()' like in <code>puppeteer-test.ts</code>. I think that the return type might be missed.

I'm not typescript expert, so I'm afraid to edit the .d.ts file. Please help.

Example -- Both works
A:
```typescript
const nextPageLink = await page.evaluateHandle(() => {
    const navs = document.querySelectorAll("nav li")
    const nextPageLi = navs[navs.length - 2]
    return nextPageLi.querySelector("a")
})
nextPageLink.asElement().click()
```
B:
```typescript
// Compile error without any. It says nextPageLink cannot have the methods of 'ElementHandle' like click()
// But works anyway. nextPage has click() obviously
const nextPageLink: any = await page.evaluateHandle(() => {
    const navs = document.querySelectorAll("nav li")
    const nextPageLi = navs[navs.length - 2]
    return nextPageLi.querySelector("a")
})
nextPageLink.click()
```

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @marvinhagemeister @cdeutsch @ksm2 @SimonSchick @serbanghita @JasonKaz @davecardwell @angrykoala @cameronhunter @1pete

**Comment by cameronhunter** [comment]
Thanks @dreamwayjgs, would you be willing to open a pull request?

**Comment by dreamwayjgs** [comment]
I have opened PR #50345. The type definition is just same latest puppeteer (5.5.0) code.

**Comment by dreamwayjgs** [comment]
OK. I'll open a PR soon.

**Comment by dreamwayjgs** [comment]
I have opened PR #50353. Please let me know if I made a mistake.
