### ISSUE TITLE
[@types/react] restrict the types ReactNode allows?

### ISSUE THREAD

**Issue by utkarshkukreti** [DefinitelyTyped/DefinitelyTyped#49705]
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon @zieka @dancerphil @dimitropoulos @disjukr @vhfmag @hellatan

If you do not mention the authors the issue will be ignored.

---

Right now, because of [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b8e8b1fb1dc2f4ee5e65c1cfb6dc20f811cb5e54/types/react/index.d.ts#L236), any value whatsoever is a valid ReactNode (the type `{}` allows any non-nullish value, not just empty objects). I frequently encounter runtime errors for using an invalid value in TSX. Is there any reason to allow this? should the `{}` be removed?

```
// type checks, but rendering this throws the error below at runtime
<div>{{foo: 'bar'}}</div>
```

> Error: Objects are not valid as a React child (found: object with keys {foo}). If you meant to render a collection of children, use an array instead.

I tried making this change and found a bug in the tests as well: https://github.com/utkarshkukreti/DefinitelyTyped/commit/871dba1c9fdc6912e1053c7d535f6410d24c85eb. I haven't tested this change in bigger TypeScript projects but I will as soon as I can.

**Comment by ferdaber** [comment]
Yes this is because of a mispurposing of ReactNode. It technically does allow everything on the runtime since any custom component can accept anything as a prop. However this only comes up for host elements. We are planning on fixing this in the v18 breaking change

**Comment by utkarshkukreti** [comment]
@ferdaber searching for React 18 led me to #46691 and #35622, the latter is the same as my question here. Thanks, I'll close this one.
