### ISSUE TITLE
[@types/react] csstype dependency not resolving

### ISSUE THREAD

**Issue by davidboschwitz** [DefinitelyTyped/DefinitelyTyped#49713]
This is a ticket to track the @types/react side of https://github.com/frenic/csstype/issues/119. 

Copied from the above ticket:

> Latest update (first seen today) seems to be breaking our build process. Please see below. I can attach debug logs if needed.
> 
> ```
> > node node_modules/typescript/bin/tsc
> 
> node_modules/@types/react/index.d.ts:38:22 - error TS2307: Cannot find module 'csstype' or its corresponding type declarations.
> 
> 38 import * as CSS from 'csstype';
>                         ~~~~~~~~~
> 
> 
> Found 1 error.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! reaver.js.coreui@1.0.0 build:compile: `node node_modules/typescript/bin/tsc`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the reaver.js.coreui@1.0.0 build:compile script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/dbosch/.npm/_logs/2020-11-21T00_14_23_140Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! reaver.js.coreui@1.0.0 build: `npm run build:css && npm run build:compile && npm run build:copy`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the reaver.js.coreui@1.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/dbosch/.npm/_logs/2020-11-21T00_14_23_179Z-debug.log
> ```
> 
> I have unblocked our build pipeline by manually adding `"csstype": "3.0.2"` as a dependency.
> 
> Thanks!

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@sandersn 
@Jessidhia
@DovydasNavickas
@eps1lon
@VincentLanglet
@tkrotoff
@franklixuefei
@ferdaber
@pelotom
@andy-ms
@pshrmn
@JoshuaKGoldberg
@jgoz
@ddwwcruz
@apexskier
@richseviora
@Pajn
@mbelsky
@onigoetz
@OliverJAsh
@devrelm
@mattmccutchen
@matt-tingen
@kaelig
@ericanderson
@uniqueiniquity
@appsforartists
@minestarks
@bowdenk7
@stipsan
@scally
@RyanCavanaugh
@Oblosys
@morcerf
@Hotell
@Herman-Freund
@Dante-101
@craigkovatch
@christophehurpeau
@adidahiya
@lifeiscontent
@Blasz
@yuit
@woutervh-
@vhfmag
@awmottaz
@wereHamster
@TomasHubelbauer
@charles-toller
@styfle

**Comment by davidboschwitz** [comment]
Authors part II
@shadowglen
@dryganets
@zieka
@sboehler
@saranshkataria
@samatar26
@kid-icarus
@rpokorny
@rbuckton
@Olian04
@rhysforyou
@pravdomil
@polco
@pocesar
@plantain-00
@paulvanbrenk
@pascaloliv
@p-jackson
@OhYee
@orta
@noomorph
@ndresx
@mjomble
@icosahebron
@micnic
@miracle2k
@voxmatt
@Andarist
@Markionium
@tenorok
@lukyth
@lukeic
@luixo
@lostfictions
@kylecrum
@kunnix
@G07cha
@kkirsche
@lttb
@dosentmatter
@JCQuintas
@theruther4d
@joshhead
@jrakotoharisoa
@Ailrun
@uiii
@janechu
@jakesyl
@jacquerie
@jacobwgillespie
@Jack-Works
@jablko
@magnetnation
@Igorbek
@ialexryan
@hankfanchiu
@guilhermehubner
@fregante
@gaspard
@frenic
@chabb
@vbfox
@ForbesLindesay
@foray1010
@Crashthatch
@alloy
@prigara
@dyst5422
@disjukr
@dimitropoulos
@dbismut
@davegregg
@devuxer
@dancerphil
@hellatan
@cynecx
@coreyward
@lemonmade
@cdeutsch
@bryanrsmith
@artem-malko
@armanio123
@newyankeecodeshop
@green-arrow
@amcasey
@kachkaev
@alexpyzhianov
@epzilla
@tony-scio
@magic-akari
@jessetrinity
@lwilkins

ps I feel like @-mentioning 142 authors is not worth any of our time.

**Comment by davidboschwitz** [comment]
Authors part III

@Jack-Works
@jablko
@magnetnation
@Igorbek
@ialexryan
@hankfanchiu
@guilhermehubner
@fregante
@gaspard
@frenic
@chabb
@vbfox
@ForbesLindesay
@foray1010
@Crashthatch
@alloy
@prigara
@dyst5422
@disjukr
@dimitropoulos
@dbismut
@davegregg
@devuxer
@dancerphil
@hellatan
@cynecx
@coreyward
@lemonmade
@cdeutsch
@bryanrsmith
@artem-malko
@armanio123
@newyankeecodeshop
@green-arrow
@amcasey
@kachkaev
@alexpyzhianov
@epzilla
@tony-scio
@magic-akari
@jessetrinity
@lwilkins

ps I feel like @-mentioning 142 authors is not worth any of our time.

**Comment by jakesyl** [comment]
@davidboschwitz

> [Mention](https://github.blog/2011-03-23-mention-somebody-they-re-notified/) the authors (see Definitions by: in index.d.ts) so they can respond.

That means the people listed [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L3):

![image](https://user-images.githubusercontent.com/6392429/99862990-1132c600-2b6a-11eb-8aeb-25625d9d7608.png)


Should be a lot less than 142

**Comment by davidboschwitz** [comment]
Ah, thank you for clarifying that! Sorry everyone!

**Comment by viko16** [comment]
Seems that `@types/react` 16.14.* had remove `csstype` from dependencies ? Why? 😢 

Diff
https://unpkg.com/browse/@types/react@16.14.1/package.json
https://unpkg.com/browse/@types/react@16.9.56/package.json

**Comment by eps1lon** [comment]
> Seems that `@types/react` 16.14.* had remove `csstype` from dependencies ? Why? 
> 
> Diff
> [unpkg.com/browse/@types/react@16.14.1/package.json](https://unpkg.com/browse/@types/react@16.14.1/package.json)
> [unpkg.com/browse/@types/react@16.9.56/package.json](https://unpkg.com/browse/@types/react@16.9.56/package.json)

Looks like the types-publisher has a bug. The [PR responsible for the broken release did not touch dependencies](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49701/files).

**Comment by pcorey** [comment]
I appreciate the quick fix. This is currently blocking our CI and deployment process.

**Comment by pcorey** [comment]
Is this scheduled to go out in a patch release any time soon?

**Comment by eps1lon** [comment]
> Is this scheduled to go out in a patch release any time soon?

Subscribe to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49717 to be notified once it's released. A will comment with the newly created version number.
