### ISSUE TITLE
mapbox-sdk: wrong type for BoundingBox used in GeocodeRequest

### ISSUE THREAD

**Issue by techieshark** [DefinitelyTyped/DefinitelyTyped#49733]
I'm using `@mapbox/mapbox-sdk@0.11.0` and running into an issue where the type definition is not correct. 

Here's the problem:

According to Mapbox docs, geocoder takes a bounding box which is an array of numbers. But the type definitions do not currently match that; they call `BoundingBox` an object.

```
   // typedefs for 0.6
    interface BoundingBox {
        minLongitude: number;
        minLatitude: number;
        maxLongitude: number;
        maxLatitude: number;
    }
```

API docs:
https://docs.mapbox.com/api/search/#forward-geocoding

Optional parameters | Description
-- | --
bbox | Limit results to only  those contained within the supplied bounding box. Bounding boxes should  be supplied as four numbers separated by commas, in  minLon,minLat,maxLon,maxLat order. ...
-- | --

Proposed fix is just change the above type def to:

```
    type BoundingBox = [
        minLongitude: number,
        minLatitude: number,
        maxLongitude: number,
        maxLatitude: number,
    ];
```

Tagging the authors since they may know better if the type was correct as of version 0.6 (in which case, maybe we want to create multiple typedef files vs just updating the version number at the top of the .d.ts file to 0.11?)

- [x] I tried using the `@types/mapbox__mapbox-sdk@0.6.5` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jeffbdye @mikeomeara1 @chachan

**Comment by jeffbdye** [comment]
Hey @techieshark! Thanks for the link to the docs, plus I see this assertion [here](https://github.com/mapbox/mapbox-sdk-js/blob/f71b570b48d96f2aace58c6ad7cf3fb19c946e8e/services/geocoding.js#L100) in the sdk that it's an array (effectively a tuple). 

I'll open a PR with your proposed fix above, thanks for such a detailed issue here! I'll tag you on that PR once I make the change.

**Comment by jeffbdye** [comment]
@techieshark Sorry to ping you again, did the changes in that PR work for you? Saw this issue was still open, wasn't sure if there were still any incorrect types or if the issue could be closed/resolved.

**Comment by techieshark** [comment]
@jeffbdye thanks for the work on that and the reminder here. Yep, that did the trick for me!  🚀 

Closing this. :)
