### ISSUE TITLE
error TS2694: Namespace '"react"' has no exported member 'ReactNode', 'DetailedHTMLProps', 'HTMLAttributes', 'SyntheticEvent', 'HTMLProps'

### ISSUE THREAD

**Issue by raphael10-collab** [DefinitelyTyped/DefinitelyTyped#49824]
In my react-typescript-electron project I have:

    "devDependencies": {
      "@types/react": "^17.0.0",
      "@types/react-dom": "^17.0.0"
     },
    "dependencies": {
      "react": "^17.0.1",
       "react-dom": "^17.0.1"
     }

I'm getting these error messages:

For this code:

    import React from 'react';
    type Props = React.HTMLProps<HTMLDivElement, HTMLDivElement>

I'm getting this error:

    error TS2694: Namespace '"react"' has no exported member 'HTMLProps'.
    type Props = React.HTMLProps<HTMLDivElement, HTMLDivElement>

For this code:

    import React, { useState } from 'react';
    interface Props {
    summary: React.ReactNode;
      children: () => React.ReactNode;
    }

I'm getting these errors:

     error TS2694: Namespace '"react"' has no exported member 'ReactNode'
     summary: React.ReactNode;

     error TS2694: Namespace '"react"' has no exported member 'ReactNode'
     children: () => React.ReactNode;

For this code:

     import React from 'react'
     type Value = React.ReactElement

I'm getting this error:

     error TS2694: Namespace '"react"' has no exported member 
    'ReactElement'
    

For this code:

    import React, { useState } from 'react';
    const onToggle = (e: React.SyntheticEvent) => {

I'm getting this error:

    error TS2694: Namespace '"react"' has no exported member 
    'SyntheticEvent'

For this code:

    import React from 'react';
    type Props =  
    React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, 
    HTMLDivElement>

I get these errors:

    error TS2694: Namespace '"react"' has no exported member  
    'DetailedHTMLProps'

For this code:

    import React, { Fragment } from 'react';
    export default function LogLink({ v, children }: Props) {
      function onClick(e: React.SyntheticEvent) {

I get this error:

    error TS2694: Namespace '"react"' has no exported member 
    'SyntheticEvent'

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
