### ISSUE TITLE
react-native-fbsdk types not updated for v3.0.0

### ISSUE THREAD

**Issue by ottob** [DefinitelyTyped/DefinitelyTyped#49829]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ifiokjr @titozzz @stuartforrest-infinity

Missing types for new functions introduced in https://github.com/facebook/react-native-fbsdk/pull/804 like https://github.com/facebook/react-native-fbsdk/blob/c4479dd58c9b791e953728ef068efc9bd0b4acba/src/FBSettings.js#L34

**Comment by stuartforrest-infinity** [comment]
@ottob do you have a full reference for what is missing?

Feel free to have a crack at [adding them](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request) in yourself. It's less than work I thought it would be when I did the same.

**Comment by ottob** [comment]
fixed by #50179
