### ISSUE TITLE
@types/facebook-pixel Missing `contents` property

### ISSUE THREAD

**Issue by WillSquire** [DefinitelyTyped/DefinitelyTyped#49869]
@noctishsu @VictorHom 

Typings are missing the `contents` property. See: https://developers.facebook.com/docs/facebook-pixel/implementation/conversion-tracking#pixel-standard-events

**Comment by VictorHom** [comment]
@WillSquire thanks for submitting the issue 👍 . Feel free to open a pr. I added a previous fix when I was working on implementing facebook pixel and wanted the correct types for my work
