### ISSUE TITLE
@types/facebook-pixel `status` should be a boolean

### ISSUE THREAD

**Issue by WillSquire** [DefinitelyTyped/DefinitelyTyped#49870]
@NoctisHsu @VictorHom

Property `status` on `CompleteRegistration` should be a boolean. See: https://developers.facebook.com/docs/facebook-pixel/implementation/conversion-tracking#pixel-standard-events

**Comment by VictorHom** [comment]
@WillSquire thanks for submitting the issue 👍 . Feel free to open a pr. I added a previous fix when I was working on implementing facebook pixel and wanted the correct types for my work
