### ISSUE TITLE
Mongoose Schema.create(Document[]) not properly being inferred

### ISSUE THREAD

**Issue by swaters-atlassian** [DefinitelyTyped/DefinitelyTyped#49899]
- [X] I tried using the `@types/mongoose` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript - using 4.1.2
- [X] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @amcasey @andreialecu 

I updated to the latest version of @types/mongoose (5.10.1) which pulled in this change for me https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44619

It looks like there is a problem with the type definitions when [passing in an array of Documents](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/88a54a939455efa0937b55ed507631415a574c44#diff-3af9aa3629458ee71874e0dcfaef3bbd36c011cf86af8a601c65280240c4bc86R3233) to create. In that case TS is matching to the [single Document signature](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/88a54a939455efa0937b55ed507631415a574c44#diff-3af9aa3629458ee71874e0dcfaef3bbd36c011cf86af8a601c65280240c4bc86R3231)

This means that any calls to create with an array makes TS think that the returned value is a single Document and not a Document[]

I haven't been able to find the exact root of the problem, but my best guess is that in all of the typing changes introduced in the linked change one of them results in matching an array for `CreateQuery<TCreate>`

If I change the ordering of the create method signatures and put the array ones before the single CreateQuery functions it resolves the problem, but that feels rather fragile. I am hoping someone with a bit more typescript experience can spot the issue in the definition of CreateQuery that is leading to the type confusion here.  Thanks!

Oh if you add this into the model test around like 616, it will highlight the problem:
```
const locModels: Location[] = 
    LocModel.create([
        { address: "foo", coords: [1, 2], facilities: ["foo", "bar"], name: "bar", openingTimes: ["foo"], rating: 10, reviews: ["foo"], notes: [] },
        { address: "foo", coords: [1, 2], facilities: ["foo", "bar"], name: "bar", openingTimes: ["foo"], rating: 10, reviews: ["foo"], notes: [] }
    ]);
```

If you are comfortable with pushing the array signatures up above the single Document signatures as a quick fix for this I can put up a PR for that along with the test I mentioned, but if you have a more permanent solution I'd love to see that :D

**Comment by acrilex1** [comment]
Mongoose did a particularly breaking move a few hours ago. They added types directly into the project, and those are incompatible with the ones in @types. See https://github.com/Automattic/mongoose/issues/9606 for more details.

I opened an issue explaining the situation, see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49902

**Comment by swaters-atlassian** [comment]
🤦‍♂️ well I will let you sort that out, in the meantime I'll see if the built-in types meet our needs. Thanks for the quick response.

**Comment by acrilex1** [comment]
>  well I will let you sort that out, in the meantime I'll see if the built-in types meet our needs. Thanks for the quick response.

The types seem to be fine, but if you use any @types packages depending on @types/mongoose, they are broken because your package-lock.json will require @types/mongoose for them. What a mess!

**Comment by swaters-atlassian** [comment]
Well we didn't have a problem with bringing in @types/mongoose from other deps, but their definitions for sure don't meet our needs.  Looks like a lot is missing and/or broken (at least for us). I think we are better off sticking with DefinitelyTyped...though I'm sure this will bite us if/when we need to update mongoose.  Thanks again for your help. I'll keep an eye on the issue you filed and can circle back around to this one once the fire is out if it still makes sense.
