### ISSUE TITLE
Incompatibility between @types/mongoose and newly added typings in mongoose

### ISSUE THREAD

**Issue by acrilex1** [DefinitelyTyped/DefinitelyTyped#49902]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi @lukasz-zak @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps @avaly @JanNemcik @cl3dson @richardsimko @ith @jeremyben @andreialecu @tHBp @1pete 

If you do not mention the authors the issue will be ignored.

Because of a recent move by mongoose (see https://github.com/Automattic/mongoose/issues/9606), the current types in this package are incompatible with those in mongoose v5.11. I know DefinitelyTyped doesn't follow SemVer, but I think that there is an urgent need for a fix about this issue.

The issue is affecting most @types/mongoose-* packages (and many others) because they automatically depend on @types/mongoose.

Sadly, mongoose did not backport their typings change to v3 and v4, so I think this package cannot be marked as a not needed directly.

Any clue on what could be done to phase-out @types/mongoose?

**Comment by acrilex1** [comment]
See https://github.com/Automattic/mongoose/issues/9625 for the issue about back-porting types for older version directly in mongoose package.

**Comment by kaznovac** [comment]
@acrilex1 i've started removal of the `@types/mongoose` in #49893.

this is what i intend to do [disclaimer: i'm by no means expert in types definitions]:
- for each packet depending on the `mongoose:^5` i'll make the `@types/*` use the official definitions
- for packets depending on the `mongoose:^4`, i'm thinking of making them dependent on already published `@types/mongoose:^4`, or to leave the definitions for v4 (how? i'll need to dig deeper in types publishing process) to evolve in this repository until the `mongoose:^4` reaches end-of-support

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
