### ISSUE TITLE
carbon-components-react Tooltip does not specify `align` attribute

### ISSUE THREAD

**Issue by starpit** [DefinitelyTyped/DefinitelyTyped#49956]
Is something wrong with CI or publishing infrastructure? No

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kalbert312 @sgregoire @matchilling

If you do not mention the authors the issue will be ignored.

**Comment by starpit** [comment]
also missing focusTrap, etc.

**Comment by kalbert312** [comment]
This should be resolved at this point.
