### ISSUE TITLE
google-apps-script DriveApp missing functions

### ISSUE THREAD

**Issue by FUSAKLA** [DefinitelyTyped/DefinitelyTyped#49952]
@mahaker @motemen
Hi, it seems that the GAS types are missing few functions from the `DriveApp`.

 - [createShortcut](https://developers.google.com/apps-script/reference/drive/drive-app#createShortcut(String))
 - [moveTo](https://developers.google.com/apps-script/reference/drive/file#moveTo(Folder))
 - [getTargetId](https://developers.google.com/apps-script/reference/drive/file#getTargetId())

Would it be possible to add those? I'd be happy to send PR but I'm complete stranger to the typescript environment and not sure how exactly it should look like.

Thanks for any advice!

**Comment by juandavidkincaid** [comment]
+1

**Comment by mahaker** [comment]
Thanks for open the Issue!
I've sent out a PR.
Sorry for the delay. 🙇
