### ISSUE TITLE
@types/mongoose - Type Definitions conflict with those in mongoose 5.11

### ISSUE THREAD

**Issue by emboxed** [DefinitelyTyped/DefinitelyTyped#49950]
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
  - Authors: @guillem-gelabert 

`@types/mongoose` is causing the build to fail with following message:

![image](https://user-images.githubusercontent.com/72232455/101198113-3c85dc80-3663-11eb-8f03-4b7f705f4e87.png)

Does this mean that mongoose is now providing it's own types, and `@types/mongoose` is deprecated or is it something else

**Comment by emboxed** [comment]
PS: build is working fine after removing `@types/mongoose` and only relying on `mongoose` type definitions.

**Comment by guillem-gelabert** [comment]
Yes, it looks like types for SchemaOptions were added three days ago.
https://github.com/Automattic/mongoose/commit/13140c019edcfaaec3df3a4a1132671675f2178d

How should we proceed?

**Comment by guillem-gelabert** [comment]
The types are for mongoose 5.10.9. And mongoose 5.11 includes now types.

**Comment by emboxed** [comment]
great thanks @guillem-gelabert

**Comment by prShadoko** [comment]
Just pasting the error message as text so a search leads to this issue (google still does not read text in images afaik)

```
node_modules/@types/mongoose/index.d.ts:79:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: DocumentDefinition, FilterQuery, UpdateQuery, NativeError, Mongoose, CastError, ConnectionOptions, Collection, Connection, disconnected, connected, connecting, disconnecting, uninitialized, Error, QueryCursor, VirtualType, Schema, SchemaTypeOpts, Subdocument, Array, DocumentArray, Buffer, ObjectIdConstructor, Decimal128, Map, Aggregate, SchemaType, Document, ModelUpdateOptions

79 declare module "mongoose" {
   ~~~~~~~

  node_modules/mongoose/index.d.ts:1:1
    1 declare module "mongoose" {
      ~~~~~~~
    Conflicts are in this file.
node_modules/@types/mongoose/index.d.ts:226:14 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'SchemaTypes' must be of type 'typeof Types', but here has type 'typeof Types'.

226   export var SchemaTypes: typeof Schema.Types;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
