### ISSUE TITLE
@types/react - Add Generics to components

### ISSUE THREAD

**Issue by waynevanson** [DefinitelyTyped/DefinitelyTyped#50023]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

@johnnyreilly
@bbenezech
@pzavolinsky
@digiguru
@ericanderson
@DovydasNavickas
@theruther4d
@guilhermehubner
@ferdaber
@jrakotoharisoa
@pascaloliv
@hotell
@franklixuefei
@Jessidhia
@saranshkataria
@lukyth
@eps1lon
@zieka
@dancerphil
@dimitropoulos
@disjukr
@vhfmag
@hellatan

---

Here is code in discussion:

```ts
type FC<P = {}> = FunctionComponent<P>;

interface FunctionComponent<P = {}> {
    (props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null;
    propTypes?: WeakValidationMap<P>;
    contextTypes?: ValidationMap<any>;
    defaultProps?: Partial<P>;
    displayName?: string;
}

// defaults
interface ReactElement<P = any, T extends string | JSXElementConstructor<any> = string | JSXElementConstructor<any>> {
    type: T;
    props: P;
    key: Key | null;
}
```

When I call a react component, the generic of the props is discarded. It contains useful information about props and should be kept.

```ts
interface Person {
  name: string
}

const MyComponent: React.FC<Person> = () => return <div></div>

MyComponent().props // is any, should be `Person`.
```

Easily fixed with this diff:

```diff
 interface FunctionComponent<P = {}> {
-    (props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null;
+    (props: PropsWithChildren<P>, context?: any): ReactElement<P any> | null;
     propTypes?: WeakValidationMap<P>;
     contextTypes?: ValidationMap<any>;
     defaultProps?: Partial<P>;
     displayName?: string;
 }
```

Having this feature is useful because it means functions can be applied to change props in the already called component, and Typescript will advise what does and doesn't change.

The change should be applied to all Component types.

How does this affect other users negatively? Would users experience some breaking changes?

**Comment by dimitropoulos** [comment]
At first glance I'm a big fan of this improvement!  Can you think of any downsides?

**Comment by waynevanson** [comment]
@dimitropoulos 
Someone wrote this LOC because it either broke something, or they would get back to it at another date.

I can't think of any downsides. My only concern is compatibility.
I would love to see this changed in a thick codebase and see if it breaks anything.

I'll be happy to PR

**Comment by eps1lon** [comment]
> Can you think of any downsides?

The code shown as motivation. You shouldn't call function components directly. Mainly because hooks exist now.

Furthermore, we don't actually know what element type is returned. The example is actually incorrect since it returns `React.Element<{}>` because the returned value is `<div />`.

You can already return typed elements with
```tsx
function Component(): React.ReactElement<Person>;
```
but TypeScript is not able to type-check it i.e. you could still return the wrong type.

**Comment by dimitropoulos** [comment]
That's fair and convincing to me.  Trying to think of a way to have TypeScript infer (as in, maybe using the `infer` keyword) the type but I haven't come up with anything..

**Comment by waynevanson** [comment]
> You shouldn't call function components directly. Mainly because hooks exist now.

Could you elaborate on the problem of calling components directly? We call functional components directly with jsx all the time.
`const Comp = () => null; <Comp />` is equivalent to `const Comp = () => null; Comp()`.
It seems to me it's not an issue.

> The example is actually incorrect since it returns `React.Element<{}>` because the returned value is `<div />`.

You're right, thank you.

It seems impossible with the current signatures of the React and how it's commonly used.

**Comment by eps1lon** [comment]
> We call functional components directly with jsx all the time. const Comp = () => null; <Comp /> is equivalent to const Comp = () => null; Comp().

Conceptually maybe. But if we talk strictly about equivalent as in "code equivalent" then `<Comp />` is equivalent to `React.createElement(Compo)` which does not just call `Comp` but creates an element that is represented by an object. The rendered (e.g. `react-dom`) then calls the function with the proper setup.

Try calling any function component directly that's using hooks. Unless you're doing that during render and while also following the rules of hooks you're probably don't get what you expected.
