### ISSUE TITLE
Types for Readability.js don't seem to work?

### ISSUE THREAD

**Issue by tomwilde** [DefinitelyTyped/DefinitelyTyped#50082]
Hi,

@charlesvdv & @awendland

[https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mozilla-readability](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mozilla-readability)

I installed Readability and the @types for it as follows: (latest for both)

```
  "dependencies": {
    "@mozilla/readability": "^0.3.0",
  },
  "devDependencies": {
    "@types/mozilla-readability": "^0.2.0",
}

```

and referenced in the tsx as:

`import Readability from "mozilla-readability";
`

The types show up in the IDE ok (VSCode) but on compilation (using WebPack) I get the following error:

`Module not found: Error: Can't resolve 'mozilla-readability' in ...
`

Am I missing something blindingly obvious?

thanks

Tom

- [x] I tried using the `@types/mozilla-readability` package and had problems.
- [x] I tried using the latest stable version of tsc (**v4.0.3**). https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).

**Comment by AviVahl** [comment]
The npm/scoped package is new (4 months ago; https://github.com/mozilla/readability/pull/608).

`@types/mozilla-readability` targets `mozilla-readability`
`@types/mozilla__readability`, which doesn't exist, _would_ target `@mozilla/readability`.

A possible solution here is to probably rename the type package and update its API to v0.3.

**Comment by tomwilde** [comment]
Hi,

thanks for coming back. Will try it out and let you know.

Tom

**Comment by AviVahl** [comment]
Try what out? Creating a PR and doing the work?

There's no `@types/mozilla__readability` package published to npm. The currently published types don't target the _current_ package name

**Comment by tomwilde** [comment]
That was the plan yes. The types themselves are quite minimal, just needs a update migrating it to a new directory and API number bump..?

**Comment by AviVahl** [comment]
I believe so, but I don't know what were the changes in 0.3... could be they bumped it just for the npm publishing. You may want to verify the types match current API...

**Comment by a1sabau** [comment]
typescript type definitions are now part of the library in 0.4.1, see https://github.com/mozilla/readability/pull/667 . It's not yet published on npm though...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
