### ISSUE TITLE
@ypes/ol compilation errors

### ISSUE THREAD

**Issue by yohny** [DefinitelyTyped/DefinitelyTyped#50102]
I tried to use the ol typings v6.4.2 in Angular project and in combination with RxJS they produced compilation errors and the project could not be built.

When used in `fromEvent`RxJS function, the compiler complains about incompatible argument of type Map
```ts
let myMap: Map; // type from ol
fromEvent(myMap, 'moveend').pipe(...) // error
```
the error is 
```
Argument of type 'Map' is not assignable to parameter of type 'FromEventTarget<Event | BaseEvent>'.
  Type 'Map' is not assignable to type 'HasEventTargetAddRemove<Event | BaseEvent>'.
    Types of property 'addEventListener' are incompatible.
      Type '(type: string, listener: Listener) => void' is not assignable to type '(type: string, listener: (evt: Event | BaseEvent) => void, options?: boolean | AddEventListenerOptions) => void'.
        Types of parameters 'listener' and 'listener' are incompatible.
          Type '(evt: Event | BaseEvent) => void' is not assignable to type 'Listener'.
            Type '(evt: Event | BaseEvent) => void' is not assignable to type 'ListenerFunction'.
              Type 'void' is not assignable to type 'boolean'.ts(2345)
```
which is caused by incompatible `ListenerFunction` type which returns `boolean`, that is incompatible with expected `void`. Here the fix is simple - make it return `boolean | void`, which is actually correct because the function does not have to return anything.

another issue is with using view's `fit()` method with geometries:
```ts
let myfFeature = new Feature();
// set up feature
myMap.getView().fit(myFeature.getGeometry()); // compilation error
```
the code (without using typings) is correct and works during runtime, but when typings are included it produces following error:
```
Argument of type 'Geometry' is not assignable to parameter of type 'Extent | SimpleGeometry'.
  Type 'Geometry' is missing the following properties from type 'SimpleGeometry': flatCoordinates, layout, stride, getSimplifiedGeometryInternal, and 9 more.ts(2345)
```

  - Authors: @hanreev

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
