### ISSUE TITLE
[aws-lambda] @types/aws-lambda seems unrelated to aws-lambda package

### ISSUE THREAD

**Issue by ankon** [DefinitelyTyped/DefinitelyTyped#50151]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] ~I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript~ (Irrelevant for the issue)
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SachinShekhar, @ivanmartos, @apalumbo, @simonbuchan (Sorry, it felt wrong to mention all authors listed -- you have worked on this package in 2020 from the history so I chose you ...)

I'm trying to understand why the [@types/aws-lambda](https://www.npmjs.com/package/@types/aws-lambda) package exists with that name, given that [aws-lambda](https://www.npmjs.com/package/aws-lambda) is a completely different thing that has only little to do with the types available _inside the AWS lambda environment_.

Initially I suspected that the aws-lambda package arrived later and picked a free but unfortunate name (see https://github.com/awspilot/cli-lambda-deploy/issues/3), but it seems they were first. So, based on the naming conventions I would expect @types/aws-lambda then be definitions for that package (as unneeded as that might be, given that that is a CLI tool).

The initial PR that introduced the aws-lambda types claims that the naming conventions have been checked (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10512), but the checklist offered by the bot then doesn't contain a check, and the PR seems to be closed without merge -- but that could be due to the "lost" history when everything moved to `types/`, given that the content is there.

I'm feeling like I'm missing something extremely obvious here, and would appreciate if someone could look into this issue. Right now I'm somewhat concerned that I'm depending on a `@types/XXX` package but not on the linked `XXX` package, and that all imports from `XXX` get magically resolved correctly. This feels like just an invitation for an automatic tool to just complain or add the `XXX` dependency ...

**Comment by simonbuchan** [comment]
Yeah, pretty much. The right name would have been something like "aws-lambda-env", as that seems to be something of a convention for these kinds of packages, but there are popular outliers, most obviously "node"!

Fortunately, the potential problems seem to be pretty limited, vscode may offer to install this if aws-lambda was being used, but fortunately for us this package is much more popular and shouldn't cause problems just by being installed, especially if that package is being used.

If there were a convenient renaming mechanism that let us deprecate this name without breaking it (including updates continuing to work), I would be happy to accept that, but for now it seems to have not enough value for the number of people it would disrupt.

This would be automatically fixed if we broke this package up later, eg `@aws-lambda/runtime`, `@aws-lambda/trigger-s3`, ..., but that's a whole lot of churn and has a bunch of issues to figure out about dependencies.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
