### ISSUE TITLE
Underscore get() and deepGet() are not present in index.d.ts

### ISSUE THREAD

**Issue by mabraithwaite** [DefinitelyTyped/DefinitelyTyped#50173]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

Underscore types are missing some functions including get() and deepGet() which is causing errors

  - Authors:  @borisyankov @jbaldwin @ccurrens @confususs @jgonggrijp @ffflorian @regevbr @peterblazejewicz @reubenrybnik

**Comment by jgonggrijp** [comment]
`deepGet` is an internal function, so it shouldn't be in there. `get` is new in Underscore 1.12, together with `toPath`.

**Comment by mabraithwaite** [comment]
There an estimate when `get` and `toPath` will be added?

**Comment by jgonggrijp** [comment]
@mabraithwaite The "authors" mentioned above (including me) are basically just a random* collection of people who happened to come by and fix something about the library. We're not a team, we don't make plans and we don't coordinate anything, except for reviewing PRs when they come.

I'm also not personally in a hurry to update `@types/underscore` with the additions in 1.11 and 1.12, so I can't give you any time estimate. If you need it fixed soon, your best bet is probably to submit a PR yourself and join the list of authors.

---
*) Well, not entirely random of course. I suspect @borisyankov was one of those early pioneers who wanted to make TypeScript useful and who created the first version of `@types/underscore`. As for myself, I do happen to maintain Underscore proper.

**Comment by peterblazejewicz** [comment]
@jgonggrijp Well written, sir!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
