### ISSUE TITLE
Typing of RootQuerySelector [key:string]: any

### ISSUE THREAD

**Issue by relief-melone** [DefinitelyTyped/DefinitelyTyped#50205]
I am currently working on a type to use for a better typing support of queries and so far I extedet the my Query selector to look like this

```ts
import { 
  UpdateQuery as OUpdateQuery,
  QuerySelector as OQuerySelector,
  RootQuerySelector
} from 'mongodb';

export type QuerySelector<T> = OQuerySelector<Partial<T>>  
& Partial<T>
| RootQuerySelector<Partial<T> | OQuerySelector<Partial<T>>>; 
```

Now this works pretty good except for one major flaw. And I came across this line in the index.d.ts file (I am using an older version of the types but in the current version it's line 1917)

```ts
[key: string]: any;
```
This will lead to every key being ok and basically rendering this very unsafe in regard to misspelling detection. Now I understand the reason for this and I have thought about and also did not come up with a solution to handle stuff keys like 'user.frients.name' but I think it would be better to split off the types to something like this

```ts
export type RootQuerySelector_BASE<T> = {
    /** https://docs.mongodb.com/manual/reference/operator/query/and/#op._S_and */
    $and?: Array<FilterQuery<T>>;
    /** https://docs.mongodb.com/manual/reference/operator/query/nor/#op._S_nor */
    $nor?: Array<FilterQuery<T>>;
    /** https://docs.mongodb.com/manual/reference/operator/query/or/#op._S_or */
    $or?: Array<FilterQuery<T>>;
    /** https://docs.mongodb.com/manual/reference/operator/query/text */
    $text?: {
        $search: string;
        $language?: string;
        $caseSensitive?: boolean;
        $diacraticSensitive?: boolean;
    };
    /** https://docs.mongodb.com/manual/reference/operator/query/where/#op._S_where */
    $where?: string | Function;
    /** https://docs.mongodb.com/manual/reference/operator/query/comment/#op._S_comment */
    $comment?: string;
    // we could not find a proper TypeScript generic to support nested queries e.g. 'user.friends.name'
    // this will mark all unrecognized properties as any (including nested queries)
    
    // Remove  this from base type
    // [key: string]: any;
};

export type RootQuerySelector<T> = RootQuerySelector_BASE<T> & {
    [key: string]: any;
}
```

This would give users the opportunity to use the base class and have safe typing for their QuerySelectors if nested fields are not required. Unfortunately I currently do not have the time to get into how to make a pr for the definately typed repo and I think it's not worth for such a little change. But if I come up with a solution for the nested queries I definately will

**Comment by relief-melone** [comment]
The problem of the paths should be possible to address now with TypeScript 4.
https://stackoverflow.com/questions/58434389/typescript-deep-keyof-of-a-nested-object

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
