### ISSUE TITLE
[@types/googlemaps] - Namespace 'google.maps' has no exported member 'MouseEvent'

### ISSUE THREAD

**Issue by robmass** [DefinitelyTyped/DefinitelyTyped#50253]
[ x ] I tried using the @types/googlemaps package and had problems.
[ x ] I understand that @types package versions do not follow SemVer.
[ x ] I have a question that is inappropriate for StackOverflow. (Please ask any appropriate questions there).
[ x ] Mention the authors (see Definitions by: in index.d.ts) so they can respond.
Authors: @demensky @cgwrench 

I have an angular 9 project and, after an `npm install`, the build process it stops with the following error:
```
ERROR in node_modules/@angular/google-maps/google-map/google-map.d.ts:68:38 - error TS2694: Namespace 'google.maps' has no exported member 'MouseEvent'.

68     mapClick: Observable<google.maps.MouseEvent | google.maps.IconMouseEvent>;
```
This occurs for the version 3.43.0 of `@types/googlemaps`, with `@angular/google-maps` 9.2.4 version.
A temporary fix for the problem is to add as devDependencies `@types/googlemaps` with an erlier version (3.39.14)

**Comment by demensky** [comment]
This change was [made recently](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50188/files#diff-f719382923bd4b09db7c683eae2410ad300dbf7d47f445ca799171493c08d343R140).

The renaming was done in accordance with version [3.34.3](https://developers.google.com/maps/documentation/javascript/releases#3.43.3).

>   *   Renamed the `google.maps.MouseEvent` interface to `google.maps.MapMouseEvent` and added a `domEvent` property, providing direct access to the underlying event from the DOM.

**Comment by mhp-borisbojic** [comment]
It also affects the latest angular version (11.0.3) and its google maps component @angular/google-maps 11.0.3. :(

**Comment by valibraimi** [comment]
It has any solutions yet ??

**Comment by robmass** [comment]
@valibraimi downgrading to an earlier version(3.39.14) solves this problem

**Comment by huynqhttt** [comment]
> This change was [made recently](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50188/files#diff-f719382923bd4b09db7c683eae2410ad300dbf7d47f445ca799171493c08d343R140).
> 
> The renaming was done in accordance with version [3.34.3](https://developers.google.com/maps/documentation/javascript/releases#3.43.3).
> 
> > * Renamed the `google.maps.MouseEvent` interface to `google.maps.MapMouseEvent` and added a `domEvent` property, providing direct access to the underlying event from the DOM.

it works for me

**Comment by mtpultz** [comment]
Affects Angular in general.  I'm using Angular 10 with `@angular/google-maps` v10.2.7, and have the same error.

**Comment by Piyush-zlatan** [comment]
Can someone help me to solve this issue? I am getting the same issue.

**Comment by lan-dry** [comment]
> Affects Angular in general. I'm using Angular 10 with `@angular/google-maps` v10.2.7, and have the same error.

Hi did you finally correct your issue please? Cuz I've got the same error

**Comment by felipedrumond** [comment]
just to confirm that the workaround works:

```
"dependencies": {
     "@angular/google-maps": "^11.0.0"
}

```
then add
```
"devDependencies": {
     "@types/googlemaps": "3.39.14"
}
```

**Comment by girishgodage** [comment]
> "@types/googlemaps": "3.39.14"

Thanks. It Worked for me

**Comment by websplee** [comment]
> just to confirm that the workaround works:
> 
> ```
> "dependencies": {
>      "@angular/google-maps": "^11.0.0"
> }
> ```
> 
> then add
> 
> ```
> "devDependencies": {
>      "@types/googlemaps": "3.39.14"
> }
> ```

Worked for me too :)

**Comment by inexuscore** [comment]
What a bloody disaster. Tried several version combinations, none of them worked. **@angular/google-maps: ^10.2.7** and **@types/googlemaps: 3.39.14** worked.

**Comment by radustavila** [comment]
Big bloddy disaster. None of them worked for me :(

**Comment by lan-dry** [comment]
Same for me. None of them worked. I'm @frustrated

**Comment by mhp-borisbojic** [comment]
FYI, the Angular team is working on a fix for this issue: https://github.com/angular/components/issues/21440

**Comment by aamirsultanmalik** [comment]
is there any permanent solution for this, none of  the above worked for me my Angular version is 10, and i am using @AGM/core.

**Comment by JavierExeni** [comment]
Yeah, Im developing an app in Ionic and Im getting the same error with the new <google-map> component.

**Comment by abbas-mgz** [comment]
same issues

**Comment by benoitmugnier** [comment]
Same issue here

**Comment by radustavila** [comment]
> This change was [made recently](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50188/files#diff-f719382923bd4b09db7c683eae2410ad300dbf7d47f445ca799171493c08d343R140).
> 
> The renaming was done in accordance with version [3.34.3](https://developers.google.com/maps/documentation/javascript/releases#3.43.3).
> 
> > * Renamed the `google.maps.MouseEvent` interface to `google.maps.MapMouseEvent` and added a `domEvent` property, providing direct access to the underlying event from the DOM.

Guys if you just wanna get rid of the error rename every occurence of MouseEvent to MapMouseEvent in the library files where the errors happen. I did this in order to be able to successfully run the project, but without using MapMouseEvent.

**Comment by mhp-borisbojic** [comment]
It was fixed now by angular and will be published soon: https://github.com/angular/components/pull/21441

This issue has nothing to do with the typings itself.

**Comment by CesarD** [comment]
I installed this morning and had the same issues as everyone else. Only combination that worked for me was @angular/google-maps: ^10.2.7, and @types/googlemaps: ^3.39.14
Only that way I was able to make it work. 
Installing the latest available from both didn't work at all (11.0.3 and 3.43.1 respectively).

**Comment by mhp-borisbojic** [comment]
> I installed this morning and had the same issues as everyone else. Only combination that worked for me was @angular/google-maps: ^10.2.7, and @types/googlemaps: ^3.39.14
> Only that way I was able to make it work.
> Installing the latest available from both didn't work at all (11.0.3 and 3.43.1 respectively).
> 
> I'm using Angular 11 BTW...

You've read my message, didn't you? 😉

**Comment by CesarD** [comment]
Yeah, that's why I mentioned that. The PR shows to be from 2 days ago, and current versions I specified are still bugging (I would assume the PR got already published in some new version on NPM). Or are there any newer versions than the ones I mentioned?

**Comment by mhp-borisbojic** [comment]
It's merged, but not released yet.

**Comment by CesarD** [comment]
Ok, guess we'll have to wait 'till then... In the meantime, that combination is the only one working for me. Perhaps it helps someone else while we wait for the final release of the fix.

**Comment by SeanGonzalezAbreu** [comment]
> I installed this morning and had the same issues as everyone else. Only combination that worked for me was @angular/google-maps: ^10.2.7, and @types/googlemaps: ^3.39.14
> Only that way I was able to make it work.
> Installing the latest available from both didn't work at all (11.0.3 and 3.43.1 respectively).
> 
> I'm using Angular 11 BTW...

I tried this and the other combinations, but no luck so far... Is there any other possible workaround ?

**Comment by BruneXX** [comment]
This was working till today, now I'm receiving again the error: error TS2694: Namespace 'google.maps' has no exported member 'MapMouseEvent'

Any ideas?

**Comment by demensky** [comment]
@BruneXX  Do you have `@types/googlemaps` version ≥ 3.43.2?

**Comment by BruneXX** [comment]
Hi @demensky I'm just trying with that version, hehe you read it my mind :)

**Comment by BruneXX** [comment]
With v3.43.2 it works perfect, thanks @demensky

**Comment by deygordillos** [comment]
"@angular/google-maps": "^10.2.7",
dev:
"@types/googlemaps": "3.39.14" 

Works for me

**Comment by aweisserv** [comment]
guys you are doing that on both packege.json AND packege-lock.json?

**Comment by trongpham99-cpu** [comment]
it's work, thanks !!

**Comment by moleonlips** [comment]
> 

What is your angular version?

**Comment by redevill** [comment]
> This change was [made recently](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50188/files#diff-f719382923bd4b09db7c683eae2410ad300dbf7d47f445ca799171493c08d343R140).
> 
> The renaming was done in accordance with version [3.34.3](https://developers.google.com/maps/documentation/javascript/releases#3.43.3).
> 
> > * Renamed the `google.maps.MouseEvent` interface to `google.maps.MapMouseEvent` and added a `domEvent` property, providing direct access to the underlying event from the DOM.

Where can we find breaking changes like this... was looking for some documentation telling me what to watch out for on the major version changes... but could not find any...???

**Comment by codeAhmad96** [comment]
> guys you are doing that on both packege.json AND packege-lock.json?

tried in both and  packege.json didn't work

**Comment by demensky** [comment]
@codeAhmad96 This package has been deprecated.

> Types for the Google Maps browser API have moved to @types/google.maps. Note: these types are not for the googlemaps npm package, which is a Node API.
