### ISSUE TITLE
[@types/evernote] package available using npm is not at the latest version

### ISSUE THREAD

**Issue by syeo66** [DefinitelyTyped/DefinitelyTyped#50291]
- [x] I tried using the `@types/evernote` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @corps @fcastilloec

I realized the version of @types/evernote on npmjs.com is 2.0.0 but here it seems it has been updated to 2.0.5. Don't know how this process should be working exactly. I'm suspecting it might have to do with the version in the index.d.ts file to be only 2.0 (but really don't know if it really matters and where the version of a package should be set)

**Comment by fcastilloec** [comment]
I don't remember exactly about the version, but if you look at the PR for those changes (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42291#discussion_r382783653) they mention that only major and minor versions should be shown. So, I think `2.0.0` is the same as `2.0.5`

**Comment by syeo66** [comment]
Okay, makes sense. Closing this issue.
