### ISSUE TITLE
[@types/evernote] It seems @types/evernote is defining Map<string, number> where the actual function returns {[key: string]: number}

### ISSUE THREAD

**Issue by syeo66** [DefinitelyTyped/DefinitelyTyped#50292]
- [x] I tried using the `@types/evernote` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @corps @fcastilloec

I realized a problem with NoteStore.findNoteCounts() because the types defined a Map but I actually received an object with the Notebooks Id as the key and the count as a value.
I looked into the SDKs code and realized it's defined using Thrift and is actually defined as a Map there. However I believe the Javascript implementation of Thrift does not seem to use actual Maps for that.
I would have gone through everything and create a PR but since there is a possibility the definition was generated I am reaching out using an Issue.

**Comment by fcastilloec** [comment]
When I did the definitions, I looked at the SDKs code (as you did) and it showed Map, that's why I defined it like that. I've never had a need to use that function before, so didn't test it. If you think is wrongly defined, a PR might be better

**Comment by syeo66** [comment]
Just for reference (I'll create a PR later):

```typescript
const noteStore = evernoteClient.getNoteStore()
const filter = new Evernote.NoteStore.NoteFilter()
noteStore.findNoteCounts(filter, false).then((n) => {
  // eslint-disable-next-line no-console
  console.log(n.notebookCounts)
})
```

Returns
```json
{1ea2cc21-2139-435a-b902-a2d345fe6a3f: 1, 1f3fdc0d-e128-4ea4-b623-9b9a3822f86f: 1}
```

the same might be true for n.tagCounts.
So, it is not a Map object.

**Comment by syeo66** [comment]
PR #50301

**Comment by syeo66** [comment]
So this should be fixed now. Thanks.
