### ISSUE TITLE
[@types/react-table] A slight type mismatch for Column and Row

### ISSUE THREAD

**Issue by datner** [DefinitelyTyped/DefinitelyTyped#50316]
Is something wrong with CI or publishing infrastructure? **_maybe?_**

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues. **none**
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped). **left a message on the discord**

If you know how to fix the issue, make a pull request instead. **I tried, it got complicated :(**

- [x] I tried using the `@types/react-table` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ggascoigne @stramel @gargroh @riceboyler

If you do not mention the authors the issue will be ignored.

I noticed 2 bugs when developing over `react-table` using typescript.

the first is that the newest version of `@types/react-table` lacks the `page: Array<Row<D>>` that master has in line `645` of `index.d.ts` and instead had `rows: Array<Row<D>>`, this affects the `usePagination` hook, giving `page` any and making ts complain when it's iterated over.

the second is that a column with no accessor doesn't implement the `Cell` renderer function, which is untrue. The logic should probably move to `UseTableColumnOptions` or at least also to `ColumnWithLooseAccessor`. Since even in the official examples for `usePagination` seen [here](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/row-selection?file=/src/App.js), the `Cell` property is used for a column with an `id` only.

Sorry I couldn't figure out the fix by myself, it's a bit overwhelming for me

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
