### ISSUE TITLE
[@types/i18n-js] t is able to return an object or array, not just a string

### ISSUE THREAD

**Issue by rye761** [DefinitelyTyped/DefinitelyTyped#50329]
### Issue Template
- [x] I tried using the `@types/i18n-js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ypresto 

If you do not mention the authors the issue will be ignored.

### Description
The `t` function from i18n-js can return an array or object depending on what is defined in the translations object and whether a complete or partial scope is used. This feature can be useful for getting a bunch of data at once. The return type of `t` should not simply be string.

**Comment by Semigradsky** [comment]
@rye761  I can change type definition to
`function t(scope: Scope, options?: TranslateOptions): unknown;`
But after this you will need to check all return values than this is string or smth else.
This is more right way but you sure that you will be happy with this?

**Comment by patrick99e99** [comment]
can you not just do something like:
```
type TranslateType = string | string[] | number | number[];
type TranslateObject = { [index: string]: (TranslateObject | TranslateObject[] | TranslateType | TranslateType[]) } ;
function translate(scope: Scope, options?: TranslateOptions): TranslateType[] | TranslateType | TranslateObject;
```

That will allow translate to handle all the correct return types.
