### ISSUE TITLE
[@types/react-select]: MultiValueRemove missing data props

### ISSUE THREAD

**Issue by tony** [DefinitelyTyped/DefinitelyTyped#50348]
`multiValueRemove` / `MultiValueRemove` (specifically `MultiValueRemoveProps`) receives `data` just like the other components

### tsc

```typescript
[tsl] ERROR in src/react-select.tsx(149,32)
      TS2339: Property 'data' does not exist on type 'CommonProps<IOptionType, true> &
      { children: ReactNode; innerProps: { className: string; onTouchEnd: (event: any) => void; 
      onClick: (event: any) => void; onMouseDown: (event: any) => void; }; selectProps: any; }'.
```

### See react-select:

`MultiValueRemove` uses `MultiValueGenericProps` (which has `data`) consistently since 2.0:

- 3.0.0 (Apr 29, 2019), [`MultiValueRemove`](https://github.com/JedWatson/react-select/blob/3.0.0/docs/PropTypes/components/MultiValueRemove.js) + [`MultiValueGenericProps`](https://github.com/JedWatson/react-select/blob/v3.0.0/packages/react-select/src/components/MultiValue.js#L64)
- 2.0.0 (Jul 22nd, 2018): [`MultiValueRemove`](https://github.com/JedWatson/react-select/blob/v2.0.0/docs/PropTypes/components/MultiValueRemove.js) + ([`MultiValueGenericProps`](https://github.com/JedWatson/react-select/blob/v2.0.0/src/components/MultiValue.js#L54s)

Official example of `multiValueRemove` receiving `{ data }`: https://github.com/JedWatson/react-select/blob/2f2aca2/docs/examples/StyledMulti.js#L46-L53

For 1.x `multiValueRemove` didn't get data props it seems: https://github.com/JedWatson/react-select/blob/451bcd5/docs/PropTypes/components/MultiValueRemove.js

### @types/react-select

As of December 1st / 3.1.1, `MultiValueRemove` doesn't get the `data` types

The reason why is it doesn't use `MultiValueGeneric` like the other customizable components do

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e52c6aa/types/react-select/src/components/MultiValue.d.ts#L45

### Ramifications

I style based off the value of the data (just like any other component being styled)

### Rest

- [x] I tried using the `@types/react-select` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @claasahl @jonfreedman @Methuselah96 @thchia @danieldelcore @rjoonas @kylemh 

If you do not mention the authors the issue will be ignored.

**Comment by Methuselah96** [comment]
Thanks for the issue! This should be resolved by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50349.
