### ISSUE TITLE
to, cc and bcc type issue in ParsedMail interface

### ISSUE THREAD

**Issue by zzq20y** [DefinitelyTyped/DefinitelyTyped#50477]
- [☑] I tried using the `@types/mailparser` package and had problems.
- [☑] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [☑] I understand that `@types` package versions.
- [☑] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- Authors: @Avol-V @psnider @peterblazejewicz 

Hi, we find the types of fields 'to', 'cc' and 'bcc' should be `AddressObject | AddressObject[]` at run time in this [interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/07f4c4fe86c8b84cfd7b8310298272966b4d47a6/types/mailparser/index.d.ts#L176). However, they are all of `AddressObject` type now. 

```
/**
 * Parsed mail object.
 */
export interface ParsedMail {
    /*Other fields*/

    /**
     * An address object for the `To:` header.
     */
    to?: AddressObject;
    /**
     * An address object for the `From:` header.
     */
    from?: AddressObject;
    /**
     * An address object for the `Cc:` header.
     */
    cc?: AddressObject;
    /**
     * An address object for the `Bcc:` header (usually not present).
     */
    bcc?: AddressObject;
    /**
     * An address object for the `Reply-To:` header.
     */
    replyTo?: AddressObject;
  
    /*Other fields*/
}
```

**Comment by mfogel** [comment]
Could you provide an example demonstrating this behavior? I'm not seeing it using mailparser v3.0.0, node v12.

```js
const {simpleParser} = require('Mailparser')
simpleParser('To: addr1@example.com, addr2@example.com')
  .then((parsed) => console.log(parsed.to))

/* Prints to console
{
  value: [
    { address: 'addr1@example.com', name: '' },
    { address: 'addr2@example.com', name: '' }
  ],
  html: '<span class="mp_address_group"><a href="mailto:addr1@example.com" class="mp_address_email">addr1@example.com</a></span>, <span class="mp_address_group"><a href="mailto:addr2@example.com" class="mp_address_email">addr2@example.com</a></span>',
  text: 'addr1@example.com, addr2@example.com'
}
*/
```

This is just one `AddressObject` with two addresses. A single `AddressObject` can contain multiple address, those are in the [`AddresObject.value` field](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fe09c3e3fc8ccd9a3111fde83e67345a897e5ec9/types/mailparser/index.d.ts#L77).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
