### ISSUE TITLE
[@types/ramda] curryN function arguments remove null from type unions

### ISSUE THREAD

**Issue by rpokorny** [DefinitelyTyped/DefinitelyTyped#50488]
- [x] I tried using the `@types/ramda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @TheHandsomeCoder @donnut @mdekrey @sbking @afharo @teves-castro @1M0reBug @hojberg @samsonkeung @angeloocana @raynerd @moshensky @ethanresnick @deftomat @blimusiek @biern @rayhaneh @rgm @drewwyatt @jottenlips @minitesh @krantisinh @pirix-gh @nemo108 @jituanlin @Philippe-mills @Saul-Mirone @Nicholaiii @devrelm @LORDBABUINO

I am trying to use `ramda`'s `curryN` to wrap a function whose argument is a type created via a union of the `null` type and something else.  The function which is returned by `curryN` does not include the `null` in the type for its argument, and thus causes a compilation error when I try to pass a `null` value to it with the `strictNullChecks` typescript compiler option turned on. I have created a repository which demonstrates the problem at https://github.com/rpokorny/ramda-curry-type-bug-demo .

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by rpokorny** [comment]
@millsp I have been told to ping you in regards to getting this issue moved to the new tracking.  See https://discord.com/channels/508357248330760243/757992230077333655/872515153344729088

**Comment by rpokorny** [comment]
To be clear, the issue is still valid.  I pushed an update to the test-case repo which bumps it to the newest `@types/ramda` version to demonstrate.

**Comment by rpokorny** [comment]
Actually, upon more thought I guess the intended way forward is that I re-create this issue as a Discussion topic.  I have done so at https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54948
