### ISSUE TITLE
[@types/next-auth] Overriding properties of built-in providers not supported by typings

### ISSUE THREAD

**Issue by monbrey** [DefinitelyTyped/DefinitelyTyped#50480]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @lluia @iaincollins @JuanM04

next-auth supports overriding all properties of built-in providers, and use object spread syntax to do so
https://github.com/nextauthjs/next-auth/blob/canary/src/providers/discord.js#L27

The typings don't support this, and TS will declare that the properties don't exist.
While there are some that shouldn't be changed, properties like `scope` and the `profile` function should be supported on all providers.

I encountered this when using the Discord provider, and wanted to add the additional `guilds` scope:
```ts
Providers.Discord({
  clientId: process.env.CLIENT_ID,
  clientSecret: process.env.CLIENT_SECRET,
  scope: "identify email guilds"
})
```
Which results in the error
```
Argument of type '{ clientId: string; clientSecret: string; scope: string; }' is not assignable to parameter of type 'ProviderDiscordOptions'.
  Object literal may only specify known properties, and 'scope' does not exist in type 'ProviderDiscordOptions'.
```

**Comment by JuanM04** [comment]
@lluia maybe we could `extend Record<string, string>` every options-type

**Comment by lluia** [comment]
@JuanM04 I agree I think it's a good solution 👍🏽

**Comment by JuanM04** [comment]
I've opened a PR: #50551

**Comment by JuanM04** [comment]
@monbrey, the version `3.1.21` has been published. If it works for you, feel free to close this issue.

**Comment by monbrey** [comment]
Sorry for the wait, thanks. LGTM
