### ISSUE TITLE
[@types/vast-client] Definitions do not support version 3.1.1

### ISSUE THREAD

**Issue by ngehlert** [DefinitelyTyped/DefinitelyTyped#50693]
are there plans to update the Definitions to support version 3.1.1 for the @types/vast-client ?
According to the migration guide https://github.com/dailymotion/vast-client-js/blob/master/docs/api/3.0-migration.md there were a lot of interface changes.

If I provide a PR can @jgainfort @kobawan verify it? Are you still in touch with the vast-client lib or what is the update process here?

**Comment by ngehlert** [comment]
little exmpale:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vast-client/index.d.ts#L365
`impressionURLTemplates: string[];`
but according to the migration guide (and the live version) it is instead `Array<{ id: String|null, url: String }>`

**Comment by jgainfort** [comment]
@ngehlert I currently am not using this library so there are no plans to update this afaik. I will however review any PR that is provided.

**Comment by ngehlert** [comment]
Discussion moved to PR
