### ISSUE TITLE
[@types/next-auth] Missing latest providers

### ISSUE THREAD

**Issue by jeremy-london** [DefinitelyTyped/DefinitelyTyped#50719]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/next-auth` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @lluia @JuanM04 

If you do not mention the authors the issue will be ignored.

Types should be complete with the latest release of the next-auth
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/next-auth is currently not showing the same supported providers as the current release

Current NextAuth Providers: https://github.com/nextauthjs/next-auth/blob/ecbaa14e30a41407f2ccac4981efd2a372ba8ef9/src/providers/index.js

DefinitelyTyped Reference: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/edeb604edec4b94286747145484bb508d2467bdd/types/next-auth/providers.d.ts

Found this error when attempting to use the FusionAuth provider supported by NextAuth 3.1.0 but not supported in the types.

**Comment by jcapinc** [comment]
I am looking into this

**Comment by JuanM04** [comment]
Those providers will be available with v3.2.0 (not released yet). For now, [these](https://github.com/nextauthjs/next-auth/blob/85b859231c6948d68749d60d861d65bcbcede6c2/src/providers/index.js) are available providers.

**Comment by jcapinc** [comment]
[The documentation](https://next-auth.js.org/providers/fusionauth) already has fusion auth listed as a valid type, I am making a PR for this right now.

**Comment by JuanM04** [comment]
I don't know if we can publish a `@types/next-auth: v3.2.0-canary`...

**Comment by jcapinc** [comment]
The documentation that FusionAuth is available on 3.1.0 is premature. Recommend closing this ticket, you can ping me when 3.2 comes out and I have a fix ready to go

**Comment by jeremy-london** [comment]
Thanks all for the help! I'll be using JS until the types get updated as needed. Looking forward to 3.2

**Comment by balazsorban44** [comment]
FWIW we are now at 3.5.0 😊

**Comment by jeremy-london** [comment]
@lluia @JuanM04 Any update on this?

NextAuth is at 3.11 now and has had this provider in the source code since August 2020 by @mprasanjith

https://github.com/nextauthjs/next-auth/commit/2f3291e48fecf74d84acfc34509e59b3e8b3c9c3

Can we please get the types updated to reflect the current NextAuth package?

**Comment by lluia** [comment]
@jeremy-london I'll try to find some time for it today 🧐 👍🏼 

Maintaining the types is a community effort, so if you're blocked in any way by them, you can always raise a PR yourself with the updates: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/next-auth 🪴

**Comment by lluia** [comment]
Most of the missing providers are gonna be added once [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51493) is merged 👍🏽

**Comment by lluia** [comment]
@jeremy-london there's [an updated of the types](https://www.npmjs.com/package/@types/next-auth) just went out that should contain the latest providers 📐 ; let me know if it solves your needs ✔️

**Comment by jeremy-london** [comment]
Looks good! Hopefully, we can get this moved/automated upstream! Appreciate the help everyone :D
