### ISSUE TITLE
[@types/braintree-web] missing HostedFieldOption of cardholderName

### ISSUE THREAD

**Issue by uncvrd** [DefinitelyTyped/DefinitelyTyped#50724]
- [x] I tried using the `@types/braintree-web` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @chlela @jbuckner 

@types/braintree-web 3.69 is missing the `HostedFieldOption` for `cardholderName` in the declaration which was added in [3.66](https://github.com/braintree/braintree-web/issues/480#issuecomment-696310477).

Here's the link to the location where it is missing: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/aef680843dc3938080759c8ffdb7b389890f1b71/types/braintree-web/modules/hosted-fields.d.ts#L40

**Comment by martin-badin** [comment]
@uncvrd I can update the definition but is the field required?

**Comment by uncvrd** [comment]
@martin-badin thanks Martin - it looks like it's optional like the other `fieldOption` props, referenced in the docs here: https://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html#~fieldOptions
