### ISSUE TITLE
[@types/argparse] missing BooleanOptionalAction

### ISSUE THREAD

**Issue by airbornemint** [DefinitelyTyped/DefinitelyTyped#50723]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @arcticwaters @tlaziuk @eps1lon @cakoose @Ondkloss @doberkofler 

`@types/argparse` 2.0.5 is missing the declaration for `BooleanOptionalAction`, which was added in `argparse` 2.0.0.

**Comment by cakoose** [comment]
@airbornemint: Most type definitions don't have an active "maintainer".  The "Authors" list is just a list of people who have touched it recently, usually to satisfy their own needs.

If you know how to make the changes you want, I'd recommend making a PR.
