### ISSUE TITLE
@types/lodash error TS2344: Type 'K' does not satisfy the constraint 'string'

### ISSUE THREAD

**Issue by BrandenKimSonos** [DefinitelyTyped/DefinitelyTyped#50780]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @aj-r @e-cloud @thorn0 @jtmthf @DomiR @WilliamChelman 

If you do not mention the authors the issue will be ignored.

When running `tsc compile` and referencing @types/lodash as a dependency, I run into a compilation error:

```
node_modules/@types/lodash/common/common.d.ts:234:132 - error TS2344: Type 'K' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

234     type MemoVoidDictionaryIterator<T, K extends string | number | symbol, TResult> = (acc: TResult, curr: T, key: K, dict: Record<K, T>) => void;
```

This is within the `common.d.ts` file and it gives me an error saying that type `K` must be a string and cannot be a union of types `string | number | symbol` when used in the Record.

I am not too sure why this is not compiling correctly because it seems a Record's key types are allowed to be `string | number | symbol`.

Here is a picture:

![image](https://user-images.githubusercontent.com/50924287/105543388-ba5f7f00-5cc7-11eb-8cfb-a9abadb6eec0.png)

My typescript version is the latest as of this time `4.1.3`

Is there possibly something wrong with my configurations in ts.config?

```
{
    "compilerOptions": {
        "alwaysStrict": true,
        "allowUnreachableCode": false,
        "allowUnusedLabels": true,
        "experimentalDecorators": true,
        "forceConsistentCasingInFileNames": true,
        "importHelpers": true,
        "inlineSources": true,
        "keyofStringsOnly": true,
        "module": "commonjs",
        "noImplicitAny": true,
        "noImplicitThis": true,
        "noEmitOnError": false,
        "noErrorTruncation": true,
        "noImplicitReturns": true,
        "noUnusedLocals": false,
        "pretty": true,
        "preserveConstEnums": true,
        "removeComments": false,
        "resolveJsonModule": true,
        "strict": true,
        "strictFunctionTypes": true,
        "strictNullChecks": true,
        "strictPropertyInitialization": true,
        "stripInternal": true,
        "target": "es2018"
        "inlineSourceMap": true,
        "outDir": "lib",
        "allowSyntheticDefaultImports": true,
        "lib": ["dom","es2018"],
    },
    "typeAcquisition": {
        "enable": true,
        "include": [ "node" ]
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude":[
        "node_modules"
    ]
}
```

Thanks!

**Comment by aj-r** [comment]
I'm guessing it's caused by this line of your tsconfig:

```
"keyofStringsOnly": true,
```

**Comment by BrandenKimSonos** [comment]
Yep that was the issue thanks!
