### ISSUE TITLE
[@types/better-sqlite3] Use generics for more specific return types, like the sqlite package does

### ISSUE THREAD

**Issue by leafac** [DefinitelyTyped/DefinitelyTyped#50794]
**The idea here is to use generics instead of [these `any`s](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b71dc542f83c8c655713a7c9abedcdfb62dfa845/types/better-sqlite3/index.d.ts#L26-L27). This is [what the `sqlite` package does](https://github.com/kriasoft/node-sqlite#use-generics-to-get-better-typings-on-your-rows) ([implementation](https://github.com/kriasoft/node-sqlite/blob/master/src/Database.ts#L150-L153)). (But the `sqlite` package is based on `sqlite3` and I think I’d rather use `better-sqlite3`.)**

If you know how to fix the issue, make a pull request instead.

**I’d love to send a pull request, but first I want to check with the original authors if this makes sense.**

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Morfent @matrumz @sant123 @Loghorn @andykais @mrkstwrt

If you do not mention the authors the issue will be ignored.

**Comment by sant123** [comment]
It makes totally sense!! If we can remove as `any` type as possible that would be great. Let me know when you create the pull request @leafac.

**Comment by leafac** [comment]
Okay, I’ll get to it soon…

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by AverageHelper** [comment]
To future googlers: I've started a Discussion [here](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62205) to try to continue this... discussion
