### ISSUE TITLE
await Model.find() returns any type

### ISSUE THREAD

**Issue by mikemeerschaert** [DefinitelyTyped/DefinitelyTyped#50858]
I have the following code
```TypeScript
import { Document, model, Model, Schema, Types } from "mongoose"

export interface User extends Document {
  _id: Types.ObjectId
  name: string
}

const UserSchema = new Schema<User>({
  name: {
    type: String
  }
})

const User: Model<User> = model<User>("User", UserSchema);

(async () => {
  const user = await User.findById("") // user is of type any
})()
```

But user has the any type only while using async / await. When using the callback the document is strongly typed.
![image](https://user-images.githubusercontent.com/2775912/105940505-5531c380-6010-11eb-9566-b63e1874cbed.png)

@bumbleblym @reduckted @chrisabrams @peterblazejewicz

**Comment by martin-badin** [comment]
Hi. I wrote your example to the test file of the package and I got these types `User | null`.

```
interface User extends mongoose.Document {
    _id: mongoose.Types.ObjectId
    name: string
}

const UserSchema = new mongoose.Schema<User>({
    name: {
        type: String
    }
})

const User: mongoose.Model<User> = mongoose.model("User", UserSchema);

(async () => {
    // $ExpectType User | null
    const user = await User.findById("") // user is of type any
})()
```

<img width="630" alt="Snímka obrazovky 2021-03-06 o 14 45 39" src="https://user-images.githubusercontent.com/5845264/110209042-a001ef00-7e8a-11eb-9b2d-c249aaf628cb.png">

**Comment by mikemeerschaert** [comment]
I'm no longer using mongoose for my project, but I'm going to assume this has been fixed from your message, going to close this one out.
