### ISSUE TITLE
[@types/degit] Options argument should be optional

### ISSUE THREAD

**Issue by aleclarson** [DefinitelyTyped/DefinitelyTyped#50893]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @peterblazejewicz

The `opts` argument should be optional.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/degit/index.d.ts#L8

**Comment by peterblazejewicz** [comment]
Yes, obviously, thx for follow up with PR!
