### ISSUE TITLE
[@types/jsonld] NodeObject should permit multiple @types

### ISSUE THREAD

**Issue by gsvarovsky** [DefinitelyTyped/DefinitelyTyped#50909]
- [x] I tried using the `@types/jsonld` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @chharvey

NodeObjects can have multiple types via an array, but this is not permitted in the types.
https://w3c.github.io/json-ld-syntax/#specifying-the-type

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/a6b5cb9b082067e364768175b12a5d41cf9aaf5d#r46505918

Happy to make a PR but it'll be a few days – I will make a comment here if I start work on it.

**Comment by chharvey** [comment]
Yes, this is a typo. It should be fixed by https://github.com/chharvey/DefinitelyTyped/commit/f5fcc313f6ab62fc1d001dd164b3d1e97851f873 .
