### ISSUE TITLE
[@types/aws-lambda] APIGatewayProxyEventV2 authorizer does not have a nested jwt 

### ISSUE THREAD

**Issue by abbaspour** [DefinitelyTyped/DefinitelyTyped#50939]
- [x] I tried using the `@types/aws-lambda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SachinShekhar @ngbrown 

AWS documentation for [API Gateway V2 request](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) mentions that in the case of JWT authorizer, claims are inside `jwt` object under `event.requestContext.authorizer` and @types/aws-lambda have adopted the same [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blame/master/types/aws-lambda/trigger/api-gateway-proxy.d.ts#L136)  

However, what I see in practice is that **authorizer information comes in as flat without `jwt` object**.

Here is my authorizer:

```terraform
resource "aws_apigatewayv2_authorizer" "auth0authorizer" {
  name             = "auth0authorizer"
  api_id           = aws_apigatewayv2_api.api.id
  authorizer_type  = "JWT"
  identity_sources = ["$request.header.Authorization"]

  jwt_configuration {
    audience = [var.api_audience]
    issuer   = "https://${var.auth0_domain}/"
  }
}
```

And here is the request object 
```json
{
  ....
  "requestContext": {
    "accountId": "377258293252",
    "apiId": "9kc4yptsm5",
    "authorizer": {
      "claims": {
        "aud": "some.api",
        "azp": "FT6TMjfHI2lkxjpAbG5tCjEdiEkyvMCA",
        "exp": "1612061676",
        "gty": "password",
        "iat": "1612053076",
        "iss": "https://tenant.auth0.com/",
        "scope": "get:data read:policies create:policy",
        "sub": "auth0|5fe435b5cbbc85006b071eba"
      },
      "scopes": null
    },
    ....
}
```

**Comment by SachinShekhar** [comment]
This issue is out of scope here. AWS documentation is the source of truth, so we can't refute it.

**Comment by abbaspour** [comment]
agree @SachinShekhar . please keep this open, while I raise it with AWS.

**Comment by abbaspour** [comment]
I had to set `payloadFormatVersion: 2.0` in order to receive the latest format. closing this issue.
