### ISSUE TITLE
[@types/google-apps-script] Namespace 'GoogleAppsScript' has no exported member 'Utilities'

### ISSUE THREAD

**Issue by JJPell** [DefinitelyTyped/DefinitelyTyped#50956]
- [x] I tried using the `@types/google-apps-script` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @PopGoesTheWza, @motemen

[Link to repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/google-apps-script)

I'm getting this error when trying to use the Utilites namespace within GoogleAppsScript
`Namespace 'GoogleAppsScript' has no exported member 'Utilities'`
I've tried to fix it but no luck. It's very strange as the [utilities file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-apps-script/google-apps-script.utilities.d.ts) is structured in the same way as all the other type definition files.

**Comment by martin-badin** [comment]
Doesn't work `GoogleAppsScript.Utilities`?

**Comment by JJPell** [comment]
Sorry, think this was an issue with VS Code as it went away once I updated to the latest version.

**Comment by Blacksmoke16** [comment]
I'm able to reproduce this in PHPStorm if anyone has any ideas. Was able to workaround it by adding a `/// <reference path="../node_modules/@types/google-apps-script/google-apps-script.properties.d.ts" />` to the file that uses it.
