### ISSUE TITLE
[@types/w3c-web-usb] Compiler says "Property 'usb' does not exist on type 'Navigator'" even after install the package.

### ISSUE THREAD

**Issue by soumi-akira** [DefinitelyTyped/DefinitelyTyped#51030]
I can't transpile typescript even after install `@types/w3c-web-usb` in Vue.js environment.

I found a stackoverflow post related to this

https://stackoverflow.com/questions/46447020/property-usb-does-not-exist-on-type-navigator-in-angular2-typescript-project/52765304#52765304

and it doesn't solved yet.

This is Angular environment but I face same problem on Vue.js environment.
If I have to do something additional, I would appreciate if you write that in readme.

## How to reproduce

```sh
npx @vue/cli create usb-test
```

- select `Manually select features`
- check `Typescript`
- you can select any options after that

```sh
cd usb-test
npm i -D @types/w3c-web-usb
```

open `src/App.vue` and replace class like below.

```ts
export default class App extends Vue {
  private async mounted(): Promise<void> {
    await navigator.usb.requestDevice({ filters: [] });
  }
}
```

compile this.

```sh
npm run build
```

this will finished with error.

```
19:21 Property 'usb' does not exist on type 'Navigator'.        
    17 | export default class App extends Vue {
    18 |   private async mounted(): Promise<void> {
  > 19 |     await navigator.usb.requestDevice({ filters: [] });
       |                     ^
    20 |   }
    21 | }
    22 | </script>
```

**Comment by jxmorris12** [comment]
I have the same issue!

**Comment by soumi-akira** [comment]
it worked by adding installed `d.ts` file in `tsconfig.json`!

```json
{
  ... other configs above ...
  "files": [
    "node_modules/@types/w3c-web-usb/index.d.ts"
  ]
}
```

By default, `node_modules` directory is excluded so installed `d.ts` is ignored I suppose.

```json
{
  "exclude": [
    "node_modules"
  ],
}
```

It might Vue problem or requirement so I close this issue.
