### ISSUE TITLE
@types/cls-hooked@4.3.2 - minor version breaks current projects

### ISSUE THREAD

**Issue by mopcweb** [DefinitelyTyped/DefinitelyTyped#51042]
Hi there!

new version of types for `cls-hooked` breaks curently working projects

![image](https://user-images.githubusercontent.com/40697120/106927483-e1cc3800-671a-11eb-9118-3a51931d52a5.png)
![image](https://user-images.githubusercontent.com/40697120/106927545-f3154480-671a-11eb-96b1-eaca8d595d3a.png)

@axiac ^^

please, could you revert changes and provide your changes in @5.0.0 release?
thanks

**Comment by axiac** [comment]
I created PR #51044 to revert them.
Thank you for your report.

However, the images you posted in the issue are not helpful. They present the two versions of the modified types but they can be easily retrieved from the history of this repo.
It would be more useful to put in the issue some of your code and the error messages you receive after you upgrade the types.

**Comment by mopcweb** [comment]
@axiac thanks!)

hm, problems were during the compilation process and i supposed they will be less valuable ... sorry for that
