### ISSUE TITLE
[@types/mongodb] types WithoutProjection<T> and WithProjection<T> should be exposed

### ISSUE THREAD

**Issue by notaphplover** [DefinitelyTyped/DefinitelyTyped#51063]
- [x] I tried using the `@types/mongodb 3.6.5` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT @alanmarcell @101 @mcortesi @EnricoPicci @AJCStriker @daprahamian @Bushulyak @BastienAr @sindbach @geraldinelemeur @various89 @1 @hector7 @floric @erikc5000 @Manc @jloveridge @Ranguna @HosseinAgha @albertossilva @peterblazejewicz @LinusU @taxilian @xamgore @avaly @HitkoDev @Celend @jtassin @addaleax

interface `Collection` exposes `find` and `findOne` methods that requires `options?: WithoutProjection<FindOneOptions<TSchema>>` and `options: WithProjection<FindOneOptions<T extends TSchema ? TSchema : T>>`. Types  `WithoutProjection<T>` and `WithProjection<T>` should be exposed in order to use those methods.

Consider the following code block:

```Typescript

import mongodb from 'mongodb';

...

export abstract class MongoDbSearchRepository<
  TModel,
  TModelDb,
  TOutputModelDb,
  TQuery
> implements SearchRepository<TModel, TQuery> {
...

  public async findOne(query: TQuery): Promise<TModel | null> {
...
    let entityDbFound: TOutputModelDb | null = await this.collection.findOne<TOutputModelDb>(
      mongoDbQuery,
      this.getFindOptions(),
    );
  }
...

  protected getFindOptions(): mongodb.FindOneOptions<
    TOutputModelDb extends TModelDb ? TModelDb : TOutputModelDb
  > {
    return {};
  }
```

The method `getFindOne` should return a `mongodb.WithoutProjection<mongodb.FindOneOptions>`, since WithoutProjection is not exported this type has to be replicated to use findOne. Otherwise this code is not Typescript compliant

**Comment by behuf** [comment]
same problem!

**Comment by LinusU** [comment]
Is this still a problem with `@types/mongodb@3.6.6`? I removed `WithProjection` just a day after adding it, in #51059.

Now you should be able to `mongodb.FindOneOptions` directly.

**Comment by notaphplover** [comment]
Hi @LinusU, thank you so much! What about `WithoutProjection` I'm checking `@types/mongodb@3.6.7` and I found the following definition:

**index.d.ts**
```Typescript
    find(
        query: FilterQuery<TSchema>,
        options?: WithoutProjection<FindOneOptions<TSchema>>,
    ): Cursor<TSchema>;

    ...

    findOne(
        filter: FilterQuery<TSchema>,
        options?: WithoutProjection<FindOneOptions<TSchema>>,
    ): Promise<TSchema | null>;

   ...

   findOne(
        filter: FilterQuery<TSchema>,
        options: WithoutProjection<FindOneOptions<TSchema>>,
        callback: MongoCallback<TSchema | null>,
    ): void;
```

I wonder if `WithoutProjection` could be exposed. Maybe there's a better alternative than exposing this type, but if that type is not exposed clients would need to replicate that type in some scenarios. If you want I can close this issue and open a new one only for the type `WithoutProjection`

Thank you so much for your time <3

**Comment by LinusU** [comment]
I see not problem with exporting it, PR welcome!

**Comment by notaphplover** [comment]
> I see not problem with exporting it, PR welcome!

On my way! <3

**Comment by notaphplover** [comment]
@LinusU I just submitted the PR. I hope everythin is fine, let me know if anything should be done and I'll go for it

**Comment by notaphplover** [comment]
@LinusU I just merged the PR, I'm closing the issue :). Feel free to post a comment here if have any questions regarding the issue or the PR
