### ISSUE TITLE
Error: ENOENT: no such file or directory, open './types/bell/index.d.ts'

### ISSUE THREAD

**Issue by davidalvarezr** [DefinitelyTyped/DefinitelyTyped#51156]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick

If you do not mention the authors the issue will be ignored.

---
It seems now your type is not in the main repository

We are all having this issue and it seems it's a problem caused by `./types/bell`.

Here are the PR where I found people having this issue (me included):  #51150, #51144, #51104, #51149

**Comment by tellnes** [comment]
I did have the same problem yesterday in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51151. It was fixed after https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51152 was merged. So to fix my PR I just pushed a new commit to my branch to trigger a new build and the rest of the automated process.

**Comment by davidalvarezr** [comment]
Thanks ! The tests passed !

Fixed with  #51152
