### ISSUE TITLE
[@types/k6] http.url tag function not typed

### ISSUE THREAD

**Issue by kz** [DefinitelyTyped/DefinitelyTyped#51195]
Hey all -- thanks for maintaining the @types/k6 package so far.

I notice the `http.url` [tag](https://k6.io/docs/using-k6/http-requests#url-grouping) is not handled:

![image](https://user-images.githubusercontent.com/1910781/107777341-99280680-6d3a-11eb-9c97-c2d1d6dad3c7.png)

I'd send a PR for [http.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/k6/http.d.ts) but I'm not sure how to represent tag functions in type files. Would any of you mind looking into this?

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @MajorBreakfast @bookmoons @na-- @ppcano @simskij

**Comment by ppcano** [comment]
@kz Thank you for reporting this. We need more time to look at it. 

Meanwhile, as an alternative to [group dynamic requests](https://k6.io/docs/using-k6/http-requests#url-grouping), you could set the tag `name` with any value like:

```js
  http.get(`${BASE_URL}detail.html?id=${id}`, {
    tags: { name: 'detail.html?id=' },
  });
 ```

**Comment by EdvinasDaugirdas** [comment]
Types added in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56198 🎉
