### ISSUE TITLE
[@types/mongodb] Deprecation warnings for w, fsync, j and wtimeout

### ISSUE THREAD

**Issue by goloroden** [DefinitelyTyped/DefinitelyTyped#51191]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT, @alanmarcell, @dante-101, @mcortesi, and others

When using `mongodb@3.6.4` with `@types/mongodb@3.6.7`, I get the following warning when trying to connect to a MongoDB:

> Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.

However, it is not possible to use `writeConcern` instead of `w`, because then `tsc` complains about:

> Object literal may only specify known properties, and 'writeConcern' does not exist in type 'MongoCallback<MongoClient>

So, I assume, that the types do not reflect the latest changes of the driver's API here. Could you maybe update this, eventually, please?

**Comment by dwalker93** [comment]
+1

**Comment by folkmanis** [comment]
writeConcern property should be added to CommonOptions interface that is referenced by write functions:

 ```
interface CommonOptions extends WriteConcern {
    session?: ClientSession;
    writeConcern?: WriteConcern;
}
```

After depreciation period `extends WriteConcern` can be removed.
