### ISSUE TITLE
[@types/node] BigIntOptions overloads don't exist on fs/promises typings

### ISSUE THREAD

**Issue by CDDelta** [DefinitelyTyped/DefinitelyTyped#51229]
Authors: @addaleax, @Flarna, @ExE-Boss

The `BigIntOptions` overloads on `fs` apis like `fs.stat()` don't exist on `fs/promises` typings. These options were added in Node v10.5.0, same version as the ones on `fs` were.

Exists on `fs` typings:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/adfe06c56f3f968316e4c707bcc57389a9e17b3e/types/node/fs.d.ts#L543

Does not on `fs/promises` typings:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/adfe06c56f3f968316e4c707bcc57389a9e17b3e/types/node/fs/promises.d.ts#L99

**Comment by Flarna** [comment]
There is currently an ongoing PR in this area: #50120 maybe this solves your needs.

If not I recommend to create a PR to correct this.

**Comment by CDDelta** [comment]
Thanks @Flarna, that PR looks sufficient.

**Comment by CDDelta** [comment]
Closed by #50120
