### ISSUE TITLE
[@types/prismjs] Fourth parameter of Prism.languages.insertBefore should be optional

### ISSUE THREAD

**Issue by webarnes** [DefinitelyTyped/DefinitelyTyped#51223]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @RunDevelopment 

If you do not mention the authors the issue will be ignored.

Prism.languages.insertBefore type definition has four required parameters but the fourth is actually optional: https://prismjs.com/docs/Prism.languages.html#.insertBefore

(static) insertBefore(inside, before, insert, root opt) → {Grammar}

Line 280:

```
insertBefore(
        inside: string,
        before: string,
        insert: Grammar,
        root: LanguageMap
    ): Grammar;
```

should be

```
insertBefore(
        inside: string,
        before: string,
        insert: Grammar,
        root?: LanguageMap
    ): Grammar;
```

**Comment by RunDevelopment** [comment]
Con confirm. That's an error in the DefinitelyTyped types. The suggested fix is correct.
