### ISSUE TITLE
[ @types/react-calendar]

### ISSUE THREAD

**Issue by athenawisdoms** [DefinitelyTyped/DefinitelyTyped#51255]
Using the sample code from the GitHub README,

```js
const [selectedDate, setSelectedDate] = useState(null);

    return (
        <div>
            <Calendar value={selectedDate} onChange={setSelectedDate} />
        </div>
    );
```

I received the following error. 

```js
Type 'Dispatch<SetStateAction<null>>' is not assignable to type 'OnChangeDateCallback'.
  Types of parameters 'value' and 'date' are incompatible.
    Type 'Date | Date[]' is not assignable to type 'SetStateAction<null>'.
      Type 'Date' is not assignable to type 'SetStateAction<null>'.
        Type 'Date' provides no match for the signature '(prevState: null): null'.  TS2322

    10 |     return (
    11 |         <div>
  > 12 |             <Calendar value={selectedDate} onChange={setSelectedDate} />
       |                                            ^
    13 |         </div>
    14 |     );
    15 | };
```

`react-calendar` package maintainer seeks help from the Typescript experts in the community! 
https://github.com/wojtekmaj/react-calendar/issues/477#issuecomment-763559699

```
"@types/react-calendar@^3.1.3":
  version "3.1.3"
  resolved "https://registry.yarnpkg.com/@types/react-calendar/-/react-calendar-3.1.3.tgz#bd0947c28738f6419649be22d80624b05fde2fb9"
  integrity sha512-4kvDfKta9bNnuRieuGYPxdDlh3UqRUKE8+fMbmZGk0Z/MdUGHupxXwPCWLbVH7FZU48o4bhT+XX8rfZrexdnAw==

react-calendar@^3.3.1:
  version "3.3.1"
  resolved "https://registry.yarnpkg.com/react-calendar/-/react-calendar-3.3.1.tgz#da691a5d59c88f178695fd8b33909a71d698021f"
  integrity sha512-iDIrhE0ABz3mChAIvA+5d2UtQGEb5oaUpLiEbrRdWHBYb45MhsbO59pG9HIy2uTdHkBF/nvzRV2JBmMfdg/0Qg==
  dependencies:
    "@wojtekmaj/date-utils" "^1.0.2"
    get-user-locale "^1.2.0"
    merge-class-names "^1.1.1"
    prop-types "^15.6.0"
```

- [x] I tried using the `@types/react-calendar` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Guymestef @ksoldau @giacomocerquone @ssukienn @premshree @EBruchet

**Comment by premshree** [comment]
Hi @athenawisdoms you need to type the `useState` like so, and it should work:

```ts
const [selectedDate, setSelectedDate] = useState<Date|Date[]|null>(null);
```

Hope this helps!
