### ISSUE TITLE
[@types/xrm] TS2339: Property 'getAll' does not exist on type 'ItemCollection '.

### ISSUE THREAD

**Issue by remyvd** [DefinitelyTyped/DefinitelyTyped#51280]
For example when trying to write:
`globalContext.userSettings.roles.getAll()`

`getAll()` will give back an array of the collection. 

![image](https://user-images.githubusercontent.com/8554104/108162880-fa7c1b00-7128-11eb-98be-53c579324c0a.png)

Authors: @6ix4our @scottdurow @markusmauch @daryllabar @clownwilleatme

**Comment by martin-badin** [comment]
@remyvd it seems the documented function `get` without any parameters is the same.

**Comment by remyvd** [comment]
Found the getAll in a blogpost and assumed it was a documented method. Sorry for this. The `get` functions seems to work the same way https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/collections/get.

Will close this issue.
