### ISSUE TITLE
[@types/chrome] Missing types for Chrome Extensions Manifest V3 Promises

### ISSUE THREAD

**Issue by JKrol** [DefinitelyTyped/DefinitelyTyped#51327]
Google introduced a new version of Extensions Manifest - V3 (https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/). It introduces new features and some functional changes. One of the changes is Promise support:
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/#promises

For example, when using tab query in V2 you had to use callback:
```js
chrome.tabs.query({active: true, currentWindow: true}, function (tabs) { /** ... **/ });
```
now, with V3, you can use `await` and callback is no longer required parameter:
```js
let tabs = await chrome.tabs.query({ active: true, currentWindow: true });
```

This information about optional callback and returned Promise is missing from types.

@types/chrome contributors: @matthewkimber, @otiai10, @couven92, @RReverser, @sreimer15, @matcarlson, @ekinsol, @tregagnon, @EchoAbstract, @spasma, @bdbai, @pokutuna

**Comment by cryptoquick** [comment]
Why is this closed? Is there v3 support yet?

**Comment by blaenk** [comment]
Yeah I think this was closed by accident @martin-badin. AFAIK that linked PR only added it for `chrome.tabs.query()`. Maybe it meant to say "Relates to" rather than "Closes".

**Comment by Alaboudi1** [comment]
Manifest v3 is no longer only supported by google. Mozilla has also started working on it. It would be awesome if we have promise based type definitions for the chrome.* APIs.

**Comment by cpakken** [comment]
Any progress on this? Manifest v2 is about to reach its end of life. With chrome at least and developers will have to start migrating to Manifest v3 very soon. I believe January 2022 is the time devs can submit Manifest v2 extensions.

**Comment by lcdss** [comment]
I got here after searching for [chrome.enterprise.deviceAttributes.getDirectoryDeviceId](https://developer.chrome.com/docs/extensions/reference/enterprise_deviceAttributes/#method-getDirectoryDeviceId), that says it returns a promise on v3, but the types don't know that.

**Comment by Messiahhh** [comment]
same question
