### ISSUE TITLE
EventEmitterOptions is not defined correctly in @types/formidable

### ISSUE THREAD

**Issue by jeremygottfried** [DefinitelyTyped/DefinitelyTyped#51341]
It seems like EventEmitterOptions is not defined correctly for @types/formidable.

The formidable docs specifically say to pass options into the constructor, not to the instance. [https://www.npmjs.com/package/formidable#formidable--incomingform](https://www.npmjs.com/package/formidable#formidable--incomingform)

The tests for @types/formidable are passing options to the instance.

[https://github.com/DefinitelyTyped/DefinitelyTyped/blob/81e930ed9983d081271ebf1978551b1e4c8b5b16/types/formidable/formidable-tests.ts#L37](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/81e930ed9983d081271ebf1978551b1e4c8b5b16/types/formidable/formidable-tests.ts#L37)

When I try to pass the options to the constructor like the formidable docs recommend, I get the following error: 
```ts
const form = new IncomingForm({ maxFileSize: 50 * 1024 * 1024, multiples: true });
```
```sh
Argument of type `{ maxFileSize: 50 * 1024 * 1024, multiples: true }` is not assignable to parameter of type 'EventEmitterOptions'. 
Object literal may only specify known properties and 'maxFileSize' does not exist in type 'EventEmitterOptions'.
```

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
  - Authors: @andy-ms , @evanshortiss , @itPiligrim , @taoqf

**Comment by evanshortiss** [comment]
@jeremygottfried the types appear to be designed for formidable@1.0.16 compatibility. You can see this [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/81e930ed9983d081271ebf1978551b1e4c8b5b16/types/formidable/index.d.ts#L1)

Looking at the [1.0.16 tag for formidable](https://github.com/node-formidable/formidable/tree/44c686aea0f97faf273a60cf2faa96cee32dec80#formidableincomingform) you can see that they changed the recommended usage, so the typings here need a PR for a new release to match the latest formidable API
