### ISSUE TITLE
@types/webpack needs a shim for v5

### ISSUE THREAD

**Issue by clar-cmp** [DefinitelyTyped/DefinitelyTyped#51379]
Webpack 5 exports its own types now. `@types/webpack` should be updated so it mentions this new release, because otherwise existing users who import `@types/webpack` will see conflicts.

Authors: @tkqubo @bumbleblym @bcherny @tommytroylin @mohsen1 @jcreamer898 @alan-agius4 @dennispg @christophehurpeau @ZSkycat @johnnyreilly @rwaskiewicz @kuehlein @grgur @rubenspgcavalcante @andersk @ofhouse @danielthank @sasurau4 @dionshihk @peterblazejewicz @spamshaker

**Comment by ofhouse** [comment]
Please see discussion at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49755.

**Comment by clar-cmp** [comment]
I searched the issues and didn't see it mentioned, should have searched PRs instead. Thank you!
