### ISSUE TITLE
[bootstrap-v5] Bootstrap types removed jQuery API, Bootstrap v5 conditionally exposes a jQuery API

### ISSUE THREAD

**Issue by kageurufu** [DefinitelyTyped/DefinitelyTyped#51387]
Bootstrap 5 removes the jQuery API *by default*, however when window.jQuery exists, the API is still exposed. The types recently removed the jQuery types, and I believe those should return.

https://getbootstrap.com/docs/5.0/getting-started/javascript/#still-want-to-use-jquery-its-possible

- [x] I tried using the `@types/react-bootstrap` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
  - Authors: @denisname, @peterblazejewicz, @martin-badin

**Comment by peterblazejewicz** [comment]
@martin-badin probably there could be a shim for v5, as separate package?

**Comment by martin-badin** [comment]
@peterblazejewicz I created MR. Please could you review. I think we don't need a separate package

**Comment by martin-badin** [comment]
@kageurufu Hi. It was helpful? Are you able to use this version of bootstrap with jQuery?

**Comment by kageurufu** [comment]
Yes, it works perfectly!
Thank you so much :)

**Comment by Liero** [comment]
@martin-badin: Is it possible to make jQuery dependency optional? Bootstrap itself has not dependency on jQuery so I think neither typings should have.

**Comment by Liero** [comment]
I mean dependency on JQuery typings,

see
https://www.npmjs.com/package/@types/bootstrap

![image](https://user-images.githubusercontent.com/3494407/144016087-7bb728a0-5fe0-44ce-89c1-c34bf7b7ee99.png)
