### ISSUE TITLE
[@types/dialogflow-fulfillment] High severity vulnerabilities from npm audit

### ISSUE THREAD

**Issue by cchardeau** [DefinitelyTyped/DefinitelyTyped#51434]
I tried using the `@types/dialogflow-fulfillment` package and had problems. `npm audit` shows 5 high severity vulnerabilities coming from `@types/dialogflow-fulfillment`. Will they be fixed ?

Authors: @nightillusions

**Comment by jakebailey** [comment]
This package has been removed from DT.
