### ISSUE TITLE
@types/actioncable package 

### ISSUE THREAD

**Issue by PhilCoggins** [DefinitelyTyped/DefinitelyTyped#51455]
- [ x] I tried using the `@types/xxxx` package and had problems.
- Authors: @zhu1230 @szechyjs 

I tried to pull in type declarations for ActionCable, but due to the fact that I am using the package `@rails/actioncable` the declarations would not resolve and I got the following in my text editor:
```
Could not find a declaration file for module '@rails/actioncable'. '... /node_modules/@rails/actioncable/app/assets/javascripts/action_cable.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/rails__actioncable` if it exists or add a new declaration (.d.ts) file containing `declare module '@rails/actioncable';`ts(7016)
```

I copied the declaration into my own types folder, and changed [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/actioncable/index.d.ts#L50) to 

```
declare module '@rails/actioncable' {
```

Adding the `@rails/` prefix seems to have fixed it. There are two `actioncable` npm packages, and it looks to me like `@rails/actioncable` is the canonical version.

Is there any way I can resolve this naming in my tsconfig? Or should this package be updated with my change above?

**Comment by martin-badin** [comment]
@PhilCoggins I created types but I am not sure they are correct. Please could you review it?
