### ISSUE TITLE
[@types/to-px] Default export shoud have optional element argument

### ISSUE THREAD

**Issue by aleclarson** [DefinitelyTyped/DefinitelyTyped#51479]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @vindhya

&nbsp;

As seen in the readme, there's an optional element argument:
https://github.com/mikolalysenko/to-px#api

**Comment by vindhya** [comment]
Thanks for raising this issue. I can make the update to the package.
