### ISSUE TITLE
Don't think CODEOWNERS works

### ISSUE THREAD

**Issue by maraisr** [DefinitelyTyped/DefinitelyTyped#51481]
I authored a PR and am also an owner of the types, yet I cannot merge as Alloy needs to approve?? Similarly Stephen is also an owner, but cannot either.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51480

**Comment by orta** [comment]
Your PR didn't have test changes - see the message here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51480#issuecomment-787589996

So, you didn't get the chance to merge it yourself and had to be done by someone with write access

**Comment by maraisr** [comment]
But that's why I'm asking, I should have write access coz I'm a code owner of the files. Have a check in the codeowners file, you'll spy my user against the library I was contributing to

**Comment by maraisr** [comment]
bump @orta

**Comment by orta** [comment]
I think you might need to show some links of this not wokring [as documented](https://devblogs.microsoft.com/typescript/changes-to-how-we-manage-definitelytyped/) . All of the linked PRs from you and me show the bot saying exactly what is happening and working as it should

**Comment by maraisr** [comment]
You can check the codeowners file and will notice I'm nowhere to be seen. None of the relay related packages ever have me requested for review officially by GitHub, only the bot. 

Recently some code was updated in the types I maintain by another unrelated pr, which could have been caught earlier if codeowners was triggered correctly.

**Comment by orta** [comment]
Perhaps you misunderstand how the system works? For example in relay-config which you linked at in the OP - you are not classed as someone who should get pinged, only alloy is today: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/relay-config/index.d.ts#L3

Otherwise, it'd be nice to see some links so I can see if it is broken 👍🏻
