### ISSUE TITLE
fs-extra An error occrus TS2694

### ISSUE THREAD

**Issue by kerry-Cho** [DefinitelyTyped/DefinitelyTyped#51506]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Andarist 

If you do not mention the authors the issue will be ignored.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5e2cff77298a9cf4499fd714029bc4cb072a2aa5/types/fs-extra/index.d.ts#L232

**Comment by kerry-Cho** [comment]
it was @type/node version, i used static version that 12.12.34 , considering backwards compatibility?

**Comment by forivall** [comment]
duplicate of #51521
