### ISSUE TITLE
[@types/node] stream/promises missing

### ISSUE THREAD

**Issue by AlessandroStaffolani** [DefinitelyTyped/DefinitelyTyped#51542]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/14.14.31` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @a-tarasyuk @jkomyno @alvis @r3nya

If you do not mention the authors the issue will be ignored.

I'm trying to use node v15 stream/promises functionalities like this one, but the type is missing:

```javascript
const { pipeline } = require('stream/promises');

async function run() {
  await pipeline(
    fs.createReadStream('archive.tar'),
    zlib.createGzip(),
    fs.createWriteStream('archive.tar.gz')
  );
  console.log('Pipeline succeeded.');
}

run().catch(console.error);
```
The example comes from the node documentation, link [here](https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback).

**Comment by F3n67u** [comment]
@cinderblock fyi, this issue already fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52357.
