### ISSUE TITLE
Error: Cannot find module 'node:*'

### ISSUE THREAD

**Issue by lisonge** [DefinitelyTyped/DefinitelyTyped#51726]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ExE-Boss 

If you do not mention the authors the issue will be ignored.

`env: node-v14.16.0`

package.json
```json
{
  "devDependencies": {
    "@types/node": "^14.14.20",
    "ts-node": "^9.1.1",
    "typescript": "^4.1.3"
  }
}
```
index.ts
```ts
import 'node:url';
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ES2020" ,
    "module": "CommonJS",
    "lib": [
      "ES2020",
    ] ,
    "allowJs": true,
    "declaration": true,
    "declarationMap": true, 
    "sourceMap": true, 
    "strict": true ,
    "moduleResolution": "Node",
    "esModuleInterop": true ,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true 
  },
}
```

exec cmd
```
npm i
npx tsnode ./index.ts
```
will throw error
`Error: Cannot find module 'node:url'`

i find ./node_modules/@types/node/url.d.ts
```ts
declare module 'node:url' {
    export * from 'url';
}
```
but
```shell
❯ node -v
v15.10.0
❯ node
Welcome to Node.js v15.10.0.
Type ".help" for more information.
> require('node:url')
Uncaught Error: Cannot find module 'node:url'
Require stack:
- <repl>
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
    at Function.Module._load (node:internal/modules/cjs/loader:768:27)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}
>
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
>
```

so How should I use module `node:*` ???

**Comment by ExE-Boss** [comment]
`node:`‑prefixed module imports are currently only supported [in **ECMAScript** modules](https://nodejs.org/api/esm.html#esm_node_imports).

---

**CommonJS** support is still being implemented: <https://github.com/nodejs/node/pull/37246>.

**Comment by lisonge** [comment]
typescript linter will be overrided in vscode 
when type `join`, vscode will linter `import {join} from 'node:path'` instead of  `import {join} from 'path'`

**Comment by lisonge** [comment]
```shell
npm i -D @types/node@[previous-version]
```
