### ISSUE TITLE
TS7016: Could not find a declaration file for module 'prettier/parser-glimmer'

### ISSUE THREAD

**Issue by robquinn** [DefinitelyTyped/DefinitelyTyped#51730]
I hate to be the person to leave an issue, but I thought it would be helpful to at least alert someone of this issue. Maybe the authors are already aware. But as it said in the description of leaving an issue, I will mention all of the authors.

I am using prettier in my project, both for formatting AND programmatically to format strings displayed to the user. The issue stems from the programmatic usage of prettier; Programmatic usage requires that you individually import the parser associated with the syntax in the given string. 

All is well for most parsers, however, the `parser-glimmer` does not have an associated declaration/types file. Consequently, someone using the `parser-glimmer` receives this error:

```
TS7016: Could not find a declaration file for module 'prettier/parser-glimmer'. '
D:/Repos/Russ_Lyon/LyonText/v10/lyon-text/node_modules/prettier/parser-glimmer.js' implicitly has an 'any' type.  
If the 'prettier' package actually exposes this module, consider sending a pull request to amend'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/prettier`
```

I checked the repo for prettier types at [DefinitelyTyped/DefinitelyTyped (prettier)](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/prettier), and confirmed that there is in fact no associated `parser-glimmer.d.ts` to go along with the `parser-glimmer` in the prettier package. So simply put, types need to be generated for prettier's `parser-glimmer`.

As stated in the instructions for writing an issue, here is a mention of all the authors that have contributed to the repo [DefinitelyTyped/DefinitelyTyped (prettier)](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/prettier):

@ikatyang
@ntotten
@ffflorian
@sosukesuzuki 
@tyankatsu0105 
@Shinigami92 
@sibiraj-s 
@thorn0 
@gengjiawen 
@SimenB 
@ryanatkn 
@rpetrich 
@peterblazejewicz 
@pengx17 
@kddeisz 
@ifiokjr 
@MasterEric 
@dcherman 
@ChristianMurphy 
@andy-ms 
@sandersn 

_I would be willing to take a shot at writing these type definitions, but I've never wrote or submited to DefinitlyTyped before. I will look into it. If you are about to do this, you can shoot me a message and ask if I am going to handle it or not. I definitly want to, just not sure if I have the time to do so yet._

**Comment by MasterEric** [comment]
Hey,

martin-badin was able to create the type definition for the parser for you. It appears the required changes were very minimal.

If you go and review/approve that PR, it will likely help speed up the approval process.
