### ISSUE TITLE
Type does not satisfy the constraint 'ObjectShape'.

### ISSUE THREAD

**Issue by move-zig** [DefinitelyTyped/DefinitelyTyped#51820]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dhardtke @vtserman @MoretonBayRC @sseppola @YashdalfTheGray @vincentjames501 @robertbullen @sat0yu @deskoh @mauricedb @kalley @elias-garcia @iansan5653 @fjc0k @lukaselmer 

If you do not mention the authors the issue will be ignored.

yup: 0.32.9
@types/yup: 0.29.11
typescript: 4.2.3

I can't seem to type an ObjectSchema.

When I use a type like this...

```
type Square = {
  width: number;
  height: number;
}

const schema = yup.object<Square>().shape({
  width: yup.number().required(),
  height: yup.number().required(),
});
```

I get this error:

> Type 'Square' does not satisfy the constraint 'ObjectShape'.
>   Property 'width' is incompatible with index signature.
>     Type 'number' is not assignable to type 'AnySchema<any, any, any> | Reference<unknown> | Lazy<any, any>'.ts(2344)

When I use an interface like this...

```
interface Square {
  width: number;
  height: number;
}

const schema = yup.object<Square>().shape({
  width: yup.number().required(),
  height: yup.number().required(),
});
```

I get this error:

> Type 'Square' does not satisfy the constraint 'ObjectShape'.
>   Index signature is missing in type 'Square'.ts(2344)

Both times, the type or interface in the angle brackets is highlighted as the issue in vscode.

Here is my tsconfig.json:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "outDir": "./dist/",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

**Comment by move-zig** [comment]
Reverting yup to 0.31.1 seems to fix the issue

**Comment by mauricedb** [comment]
Hi @move-zig 

You are aware that the latest versions of Yup have been rewritten in TypeScript and have their own included type definition? That makes these type definitions no longer relevant for the last version. And they are not compatible either.

**Comment by move-zig** [comment]
My mistake. Thanks!
