### ISSUE TITLE
[@types/eslint] incorrect return types for `SourceCode` token methods

### ISSUE THREAD

**Issue by erikbrinkman** [DefinitelyTyped/DefinitelyTyped#51921]
The `SourceCode` token methods always return `AST.Token`, but when `includeComments: true` is set, they could also be `ESTree.Comment`. I think the best solution would be to parameterize the functions, e.g.:
```
getTokenByRangeStart<Comments extends boolean>(offset: number, options?: { includeComments?: Comments }): AST.Token | null | (true extends Comments ? ESTree.Comment : never);
```

However, I recognize that since these are somewhat inherited, that you may want to limit the complexity of the methods.

Similarly, but less crucially, `SourceCode` also includes a `FilterPredicate`. It'd be ideal if:
1. `FilterPredicate` was `includeComments` aware, e.g. didn't allow `ESTree.Comment` if `includeComments` is `false` or omitted.
2. `FilterPredicate` was typed, so it was something like:
    ```
    type FilterPredicate<T extends AST.Token | ESTree.Comment> = (tokenOrComment: AST.Token | ESTree.Comment) => tokenOrComment is T;
    ```
    thus allowing guarded filters to actually pass down to the return type.

I'm happy to submit a PR or two, but I'm curious about your feedback first.

Authors: @pmdartus @j-f1 @saadq @JasonHK @bradzacher

**Comment by 43081j** [comment]
> The SourceCode token methods always return AST.Token, but when includeComments: true is set, they could also be ESTree.Comment

Are you sure? As far as i can see, `getTokenByRangeStart` always returns a `Token`. Changing `includeComments` to be `true` would just result in a token representing the comment being returned.

I was curious so i did try `getTokenByRangeStart(0, {includeComments: true})` in a file containing only a comment and received:

```ts
{
  type: 'Line',
  value: ' foo',
  range: [ 0, 6 ],
  loc: { ... }
}
```

**Comment by bradzacher** [comment]
> Are you sure? As far as i can see, getTokenByRangeStart always returns a Token. Changing includeComments to be true would just result in a token representing the comment being returned.

The `AST.Token` `type` union

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d04cd9a404f26b5fff022281f9e5bcbcb8f29114/types/eslint/index.d.ts#L18-L35

Does not include the values that are valid for the `ESTree.Comment` `type`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d04cd9a404f26b5fff022281f9e5bcbcb8f29114/types/estree/index.d.ts#L44-L47

They are two distinct sets.

**Comment by 43081j** [comment]
Aha. I would say that is a mistake, `Token` in the source most definitely can be a line (comment). I think the right fix here is to include it in the union rather than conditionally in specific methods. 

I understand these particular methods don't return comments by default but that shouldn't affect what the `Token` type is, it should have contained all types of token all along IMO.

**Comment by erikbrinkman** [comment]
My understanding was that token types should only refer to the AST. Since comments aren't functional, they don't belong in the ast, and most functions outside a few specific ones should never be able to return comments.

**Comment by 43081j** [comment]
A comment is just another piece of syntax. Not all languages have the same syntax for comments, so it is definitely part of the language. In many parsers we ignore them because they don't change the functionality, but they are still syntactical features are have to tokenise initially. 

You can see also that eslint's jsdoc defines the return type for this particular case as a `Token`. We just had an incomplete definition all along it seems.

**Comment by erikbrinkman** [comment]
I can see the argument, but that seems counter to the way eslint is actually organized. The middle parser espree defines [Comments](https://github.com/eslint/espree/blob/master/lib/espree.js#L23-L41) and [Tokens](https://github.com/eslint/espree/blob/master/lib/token-translator.js#L21-L34) separately. Looking through any of the code, e.g. [TokenStore](https://github.com/eslint/eslint/blob/master/lib/source-code/token-store/index.js#L209-L210), you'll see that these are treated as separate object classes. It seems counterintuitive to lump them into the same type in this instance. Similarly, there are other places that distinguish between them, e.g. [`Program`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/eslint/index.d.ts#L44-L49) has comments and tokens, not the union.

Finally from a typing perspective, I think what I proposed has value. If you're exhaustively searching through token types,  and you didn't set comments to true, it seems bad to have to filter for `line` and `block` even when those can never been in the return.

I can seem to tag them, but I'd be interested in @btmills take as the author of TokenStore.

**Comment by 43081j** [comment]
The token store consumes comments and tokens, yes. But one is a superset of the other. 

For example, this is why things like this exist:

https://github.com/mysticatea/eslint-utils/blob/master/src/token-predicate.js#L109-L120

To assert if a `Token` is a `Comment`. Because ultimately a comment is in fact just another token. 

Unfortunately it seems eslint is missing a typedef for it but I'm pretty sure that's how it would be defined. 

I'm aware it could be nice to type methods in such a way that they exclude comments from the union when not enabled, but that shouldn't affect what we define `Token` as. And in reality we should probably conform to the sources, which also define the return types as `Token`

**Comment by erikbrinkman** [comment]
I think where we're differing is that these types are both meant for the parser espree and eslint. From an espree perspective, [comments and tokens are different](https://github.com/eslint/espree/blob/master/lib/espree.js#L148-L153). This is what I keep referring back to. From an eslint perspective, there are very few cases when these are independent, and it therefore makes sense to have a single type `Token` that refers to this union.

The problem with naively extending the `Token` type to cover comments is that you'll be [more generally typing](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/eslint/index.d.ts#L44-L49) the parser output.

Therefore the most basic fix to me is still to just add `ESTree.Comment` to many of the SourceCode methods. If you think the change should also introduce a type that types the union I think that makes sense. From your reasoning maybe the change that makes the most sense would be to change `Token` to `ParserToken` and then define `type Token = ParserToken | ESTree.Comment`. However, that change is somewhat backwards incompatible if someone is assigning to the parser output (although this seems very unlikely). An alternative that's maybe a little more friendly would be to define `type CommentOrToken = Token | ESTree.Comment`, but I'm guessing you don't like the idea of not calling a comment a token.

I don't have any feelings about the union type, although I think it would simplify some of the typing. What I ultimately care about is updating the types so they're accurate. Thoughts?

**Comment by 43081j** [comment]
> From an espree perspective, comments and tokens are different. This is what I keep referring back to. 

FWIW the lines you link do not define that comments and tokens are different. Storing them separately does not imply they are different types.

Here is what defines they are different:

https://github.com/eslint/espree/blob/2080ce6cc8bef3057696967e518c87f749da6533/lib/token-translator.js#L21-L34

Conflicting with this, eslint defines the return type of the methods you originally mentioned as a `Token`. Which is what we should align with ideally.

I would personally keep it simple and define the return types as `Token|Comment`.

**Comment by erikbrinkman** [comment]
It seems we've at least come to consensus on how to fix it. Is it suitable to just put a PR?

**Comment by 43081j** [comment]
I think so, by the looks of it eslint has a fair amount of loose/incorrect jsdoc types anyway too. So wouldn't worry about aligning to them too strictly. 

It'll be a breaking change technically too but I imagine people are narrowing the token union already anyway. So it shouldn't affect anyone
