### ISSUE TITLE
Header files for dynamic .methods and .statics?

### ISSUE THREAD

**Issue by RdeWilde** [DefinitelyTyped/DefinitelyTyped#5193]
Is it possible to write TypeScript header/definiton files for code using object.methods and object.statics? 

Like this:
```typescript
import passportLocalMongoose = require('passport-local-mongoose')

interface IUserModel extends IUser, mongoose.Document  {};

var userSchema = new mongoose.Schema({
    username: String,
    password: String
});

userSchema.plugin(passportLocalMongoose, {});    // <<< From here
```
Trying to use this https://github.com/saintedlama/passport-local-mongoose/blob/master/lib/passport-local-mongoose.js
```javascript
// To here
module.exports = function(schema, options) {    // <<< thru here
   schema.methods.setPassword = function (password, cb)    // <<< to here
   // How do I apply this back to schema's methods??
   // ... etc ...
}
```

Obviously the problem will occur here:
```typescript
// app.ts

user.setPassword (..., ...) // TypeScrypt error, serPassword undefined

**Comment by RdeWilde** [comment]
Obviously the problem will occur here

```typescript
// app.ts

User.setPassword (..., ...) // TypeScrypt error, serPassword undefined

**Comment by RdeWilde** [comment]
I'm starting to think that Mongoose's .plugin-method implementation makes it impossible to write a correct typescript header for it, with autocompletion on the functionality provided by the plugin, right?

**Comment by RdeWilde** [comment]
https://github.com/borisyankov/DefinitelyTyped/issues/4153

**Comment by RdeWilde** [comment]
Added it here too with some more links:
http://stackoverflow.com/questions/31829109/header-files-for-mongoose-plugin-method-extending-via-methods-and-statics

**Comment by simonxca** [comment]
@RdeWilde  For methods you can do this:
```
interface IModel {
  setPassword: (password, cb) => void;
}

var Model = mongoose.model<IModel>(...);
var doc = new Model(...);
doc.setPassword(...);       // should let you use it
```

For statics it will be a bit trickier. We could do this:
```
interface IStatics {
  staticMethod: (...) => void;
}

var Model = mongoose.model<IModel, IStatics>(...);
Model.staticMethod;      // should let you use it
```
It will probably break everyone who is currently using `mongoose.model<IModel>`
Unless you've already found a better solution.

**Comment by simonxca** [comment]
I guess it's the price to pay for not looking ahead.

**Comment by simonxca** [comment]
I checked and it looks like I can define an override in the definitions:
```
model<T>(...): ModelConstructor<T>
model<T, S>(...): S & ModelConstructor<T>
```
Which will let us do:
```
interface IModel {
  // define methods here
}

interface IStatics {
  // define statics here
}

var Model = mongoose.model<IModel, IStatics>(...);
Model.static();       // should work
var doc = new Model();
doc.method();       // should also work
mongoose.model<IModel>(...);    // should not break
```

**Comment by linusbrolin** [comment]
Sorry to post in a closed issue, but I'm having problems with this exact plugin aswell.
I have a local type definition file for passport-local-mongoose, based on the one linked by @RdeWilde, which worked fine with the 3.x mongoose.d.ts but not with the updated 4.x mongoose.d.ts.

I'm not sure how I should fix the d.ts file for this plugin, and other plugins, to work with the new mongoose.d.ts?

Below is what I currently have, but it no longer works.

    declare module 'mongoose' {
      import passportLocal = require('passport-local');

      // methods
      export interface PassportLocalDocument extends Document {
        setPassword(password: string, cb: (err: any, res: any) => void): void;
        authenticate(password: string, cb: (err: any, res: any, error: any) => void): void;
      }

      // statics
      export interface PassportLocalModel<T extends PassportLocalDocument> extends Model<T> {
        authenticate(): (username: string, password: string, cb: (err: any, res: T, error: any) => void) => void;
        serializeUser(): (user: PassportLocalModel<T>, cb: (err: any) => void) => void;
        deserializeUser(): (username: string, cb: (err: any) => void) => void;
        register(user: PassportLocalModel<T>, password: string, cb: (err: any) => void): void;
        findByUsername(username: string, selectHashSaltFields: boolean, cb: (err: any) => void): any;
        createStrategy(): passportLocal.Strategy;
      }

      // error messages
      export interface PassportLocalErrorMessages {
        MissingPasswordError?: string;
        AttemptTooSoonError?: string;
        TooManyAttemptsError?: string;
        NoSaltValueStoredError?: string;
        IncorrectPasswordError?: string;
        IncorrectUsernameError?: string;
        MissingUsernameError?: string;
        UserExistsError?: string;
      }

      // plugin options
      export interface PassportLocalOptions {
        saltlen?: number;
        iterations?: number;
        keylen?: number;
        encoding?: string;
        digestAlgorithm?: string;
        passwordValidator?: (password: string, cb: (err: any) => void) => void;

        usernameField?: string;
        usernameUnique?: boolean;

        usernameQueryFields: Array<string>;

        usernameLowerCase?: boolean;

        hashField?: string;
        saltField?: string;

        limitAttempts?: boolean;
        lastLoginField?: string;
        attemptsField?: string;
        interval?: number;
        maxInterval?: number;
        maxAttempts?: number;

        errorMessages?: PassportLocalErrorMessages;
      }

      export interface PassportLocalSchema extends Schema {
        plugin(
          plugin: (schema: PassportLocalSchema, options?: PassportLocalOptions) => void,
          options?: PassportLocalOptions
        ): Schema;
      }

      export function model<T extends PassportLocalDocument>(
        name: string,
        schema?: PassportLocalSchema,
        collection?: string,
        skipInit?: boolean): PassportLocalModel<T>;
    }

    declare module 'passport-local-mongoose' {
      import mongoose = require('mongoose');
      var _: (schema: mongoose.Schema, options?: Object) => void;
      export = _;
    }

I also have a d.ts file for mongoose-paginate, which is also no longer working with mongoose.d.ts and need to be updated in the same way.
I would be happy to make PR's for both d.ts files to DefinitelyTyped once they have been updated to work again.

**Comment by simonxca** [comment]
Where is this .d.ts file from? DefinitelyTyped or your own version?

**Comment by linusbrolin** [comment]
Own version, based on the one in the Stackoverflow link by @RdeWilde

**Comment by linusbrolin** [comment]
My d.ts file for mongoose-paginate is very similar in structure, but much smaller:

    declare module 'mongoose' {
      export interface PaginateOptions {
        select?: Object|string;
        sort?: Object|string;
        populate?: Array<Object>|Array<string>|Object|string;
        lean?: boolean;
        leanWithId?: boolean;
        offset?: number;
        page?: number;
        limit?: number;
      }

      export interface PaginateResult<T extends Document> {
        docs: Array<T>;
        total: number;
        limit: number;
        page?: number;
        pages?: number;
        offset?: number;
      }

      export interface PaginateModel<T extends Document> extends Model<T> {
        paginate(query?: Object, options?: PaginateOptions, callback?: (err: any, result: PaginateResult<T>) => void): Promise<PaginateResult<T>>;
      }

      export function model<T extends Document>(name: string, schema?: Schema, collection?: string, skipInit?: boolean): PaginateModel<T>;
    }

    declare module 'mongoose-paginate' {
      import mongoose = require('mongoose');
      var _: (schema: mongoose.Schema) => void;
      export = _;
    }

There are basically two big issues:
1. Extending Model does not work anymore.
2. Injecting the plugin options, intefaces and overrides into the 'mongoose' namespace does not work anymore.

Both of these d.ts files have been built based on examples online on how to build d.ts files for mongoose plugins and worked well with the 3.x mongoose.d.ts file.

Unfortunately, the only mongoose plugins with d.ts files in DefinitelyTyped are so basic and are not built the same way, that they cannot be used as basis for these plugin d.ts files.

But I would be happy to provide these two d.ts files to DefinitelyTyped, if I knew how to update them to work with the 4.x mongoose.d.ts

**Comment by simonxca** [comment]
Okay taking a look at this, it will need some edits to mongoose.d.ts as well as your definitions. It would be good to provide these to DefinitelyTyped since TravisCI will tell us if we broke anything when we update the definitions in the future.

**Comment by simonxca** [comment]
@linusbrolin Are you willing to maintain those 2 .d.ts files though?

**Comment by simonxca** [comment]
Try this in another folder to see if it works for you:
1. Copy updated mongoose.d.ts https://raw.githubusercontent.com/simonxca/DefinitelyTyped/patch-mongoose/mongoose/mongoose.d.ts
2. Reference the above in your .d.ts files instead of the current version.

- Change ` interface PassportLocalDocument extends Document { ... }` to `interface PassportlocalDocument { ... }`. mongoose.d.ts should extend Document for you.
- For PassportLocalSchema change the return type to `this`.
- Model<T> is a bunch of types mashed together. To extend it you'll need to use a type reference:

```
export type PassportLocalModel<T extends PassportLocalDocument> = _PassportLocalModel<T> & Model<T>;
interface _PassportLocalModel<T extends PassportLocalDocument> { ... }
```
- For `PaginateModel` it's similar:
```
export type PaginateModel<T> = _PaginateModel<T> & Model<T>;
interface _PaginateModel<T> { ... }
```
Let me know if you get other errors.

**Comment by linusbrolin** [comment]
I need to go, but I'll have a look tomorrow and see if I can get it working. :)

I'm using the files for a couple of large projects at work, so yea I can maintain them, atleast while I'm working on those projects.

**Comment by linusbrolin** [comment]
@simonxca I've now tried the changes you suggested, and they seem to work. :)
The only thing is that my User interface still has to extend PassportLocalDocument, or it will complain.
So, when declaring models and schemas using any of these plugins, I have to do it like below:

    export interface User extends PassportLocalDocument {
      _id: Types.ObjectId | string;
      company: string;
      nameFirst: string;
      nameLast: string;
      email: string;
      username: string;
      password: string;
      salt: string;
    }

    export const UserSchema: PassportLocalSchema = <PassportLocalSchema>new Schema({
      // _id: Schema.Types.ObjectId, // Not needed, MongoDB autogenerates this
      company: String,
      nameFirst: { type: String, required: true },
      nameLast: String,
      email: String,
      username: String,
      password: String,
      salt: String,
    }

    let options: PassportLocalOptions = <PassportLocalOptions>{};
    options.usernameField = 'username';
    options.hashField = 'password';
    options.usernameLowerCase = true;

    UserSchema.plugin(passportLocalMongoose, options);
    UserSchema.plugin(mongoosePaginate);

    export type UserModel<T extends PassportLocalDocument> = _UserModel<T> & PassportLocalModel<T> & PaginateModel<T>;
    interface _UserModel<T extends PassportLocalDocument> {}

    export var UserModel: UserModel<User> = model<User>('User', UserSchema) as UserModel<User>;

This does work though, so all should be fine with the d.ts files?

**Comment by simonxca** [comment]
@linusbrolin Okay that's good! Last thing is you should add an override to `model()` for both of your .d.ts files to allow adding Static methods and properties to your Schemas:
```
export function model<T extends PassportLocalDocument, Statics>(
    name: string,
    schema?: PassportLocalSchema,
    collection?: string,
    skipInit?: boolean): Statics & PassportLocalModel<T>;
```
Other than that it should be good. Have you committed to DefinitelyTyped before?
You'll need to add a header and a test file. Please put me in the header file as an author as well. I can help review changes to these .d.ts files.

**Comment by linusbrolin** [comment]
@simonxca the .d.ts files already have model() overrides, just without the Statics part, so I'm assuming I should just modify the existing override in each .d.ts file and add the Statics parts, instead of adding an additional override?

No, I have not committed to DefinitelyTyped before.
But I can look at some other header and test files and see what needs to be done.

**Comment by simonxca** [comment]
@linusbrolin Actually hold on for now. There's some changes coming in. I talked to the guys maintaining mongoose.d.ts for typings and we're moving back to using interfaces since people have been extending them like you have (which is probably a better idea than the way I did it). Patch is here: https://github.com/simonxca/DefinitelyTyped/blob/patch-mongoose/mongoose/mongoose.d.ts

You're original files should work after the update (just needed 2 small fixes when I tried them). Sorry for causing you to change back and forth...
I'll put up a doc in this folder with examples of how to use and extend the definitions so people are aware in the future.

What you can do is fork DefinitelyTyped and create a branch with your definitions in folders named `passport-local-mongoose/passport-local-mongoose.d.ts` and `mongoose-paginate/mongoose-paginate.d.ts`. Put the link here, I'll review it to make sure it works, and you can submit a PR.

**Comment by linusbrolin** [comment]
@simonxca oh, sorry, I just submitted PR's a few minutes ago and totally missed reading this first.. :/

So, my type definitions should be changed back to how they were for the 3.x version of mongoose.d.ts?

**Comment by simonxca** [comment]
@linusbrolin Ahh no worries mongoose isn't updated yet. When it is, I'll update your files as well.
