### ISSUE TITLE
[@types/react-bootstrap-table2-toolkit] requires new release

### ISSUE THREAD

**Issue by matt-nydig** [DefinitelyTyped/DefinitelyTyped#51990]
@sandersn it's not clear to me how your release infra works, but I believe that `react-bootstrap-table2-toolkit` requires a new patch release to match the recent release of `@types/react-bootstrap-table-next`, which is a dependency. It appears that the release of the former was automated, but somehow that process is not catching the dep in the latter.

**Comment by sandersn** [comment]
The CI run detected the dependency, but react-bootstrap-table2-toolkit's compile passed, so it didn't require an update. #51913 is a pretty simple change, and ships as a patch release. Why does react-bootstrap-table2-toolkit need to update too?

**Comment by matt-nydig** [comment]
My apologies, I appear to be quite wrong here. I'm using an outdated version of the dep due to a dependency being pulled in upstream incorrectly. Sorry for the wasted time.
