### ISSUE TITLE
[@types/next-auth] ProviderCommonOptions idToken missing

### ISSUE THREAD

**Issue by sebascomeau** [DefinitelyTyped/DefinitelyTyped#52018]
- [x] I tried using the `@types/next-auth` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @luia @iaincollins @JuanM04 @balazsorban44 @euxn23

ProviderCommonOptions needs idToken prop because some providers are using id_token instead of access_token. Next-Auth have a conditional if on that prop. I need to set it for AzureADB2C provider.

https://github.com/nextauthjs/next-auth/blob/782482b9f475ca19019e5bc37f3053718d472cb2/src/server/lib/oauth/callback.js#L42

**Comment by balazsorban44** [comment]
it's true that some providers support id_token, but it's NOT a replacement for access_token! if set to true, the userinfo will be parsed from the id_token, instead of calling the userinfo oauth endpoint.

**Comment by gregory-j-baker** [comment]
MS Graph rejects the token when calling the user info endpoint, which is why idToken is required in the provider.

**Comment by gregory-j-baker** [comment]
@balazsorban44 why was this closed? We need to be able to send the idToken property to get Azure Active Directory to work.

**Comment by balazsorban44** [comment]
because it has been published. 😉

**Comment by gregory-j-baker** [comment]
Oops nevermind. I didn't realize this was fixed.
