### ISSUE TITLE
[@types/terser-webpack-plugin] v4.2.0 depends on webpack 5 types

### ISSUE THREAD

**Issue by rchl** [DefinitelyTyped/DefinitelyTyped#52056]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Danscho @peterblazejewicz 

The 4.2.0 version of `@types/terser-webpack-plugin` (currently the latest from the `4.x` range) depends on `"@types/webpack" "*"` which resolves to webpack 5 types which causes an error like:

```
Error: node_modules/@types/terser-webpack-plugin/index.d.ts(7,10): error TS2305: Module '"webpack"' has no exported member 'Plugin'.
```

The `4.x` version should depend on `@types/webpack ^4`.

**Comment by peterblazejewicz** [comment]
Sorry for the problem, the change in the @types/webpack is a broader effort to ease progressing with webpack ecosystem on DT.
Here, with `@types/terser`, there is no v4, which could use `paths` to resolve typings, I'll add one asap.

**Comment by rchl** [comment]
Confirmed fixed. Thanks!

**Comment by rchl** [comment]
Just wanna say that cc'in me in the PR was not the best idea because I'm now getting never-ending mentions from all the PRs over the github that somehow reference that PR also. So far got about 40 :)
