### ISSUE TITLE
[@types/styled-system__css] not compatible with styled-component css types

### ISSUE THREAD

**Issue by LoiKos** [DefinitelyTyped/DefinitelyTyped#52068]
Hi!
[x] I tried using the `@types/styled-system__css` package and had problems.

i tried to use the css utility from styled-system with the css from styled components but types seems to not be compatible:

<img width="901" alt="Capture d’écran 2021-03-29 à 19 59 38" src="https://user-images.githubusercontent.com/9548473/112879346-4d9ea180-90c9-11eb-91ba-d20e0b5f065c.png">

```ts

import 'styled-components/macro'
import {} from 'styled-components/cssprop'
import css from '@styled-system/css'

function Component(props) {
  return (
    <div
      css={css({
        display: 'flex',
        alignItems: 'center',
        '@media print': {
          display: 'block',
        },
      })}
    ></div>)}
```

  - Authors: @sebald @sztobar @RyanTheAllmighty

**Comment by sebald** [comment]
I guess the styled-system lib is mostly abandoned. I would suggest you try theme-ui instead. The lin is also written in TS so types should be much better and up to date 🙂

**Comment by LoiKos** [comment]
Okay ! Thank you for the quick answer and the hint, i'll check that :)
