### ISSUE TITLE
[@types/react] Helper for functional component return type?

### ISSUE THREAD

**Issue by lukewlms** [DefinitelyTyped/DefinitelyTyped#52080]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

I'd like to suggest adding a FC return type to the typedefs as a shortcut that I believe would be very commonly used.

It's currently easy to type a FC declared as const:

`const MyComponent: FC = () => { <>...</> }`

But not when declared as function.  It looks like the best way to do this currently is to use `JSX.Element | null` which is the return type of FC itself:

```
function MyComponent(): JSX.Element | null {
  return <>...</>;
}
```

That gets tedious when applied across a large project, especially when TS ESLint recommended rules are turned on and exports must be typed (@typescript-eslint/explicit-module-boundary-types).

Rather than every team determining an internal solution for this, a simple helper could be created.  Name could be something like JSXNode or FCReturnType - maybe someone has a better idea.  Currently we're using JSXNode since this is the only valid subset of `ReactNode` that considered valid JSX and can be returned from a component.

`type JSXNode = JSX.Element | null;`

I think the annoyance of this missing helper is demonstrated by the DefinitelyTyped React definitions, which sometimes use the type above and sometimes `JSX.Element<any, any> | null` when defining the same thing.  The typedefs have 5 instances of this explicitly-spelled-out type.  That seems to be asking for simplification.

I'd be happy to submit a PR if there's some agreement - it would simply add such a helper and use it in those five places in the type file.

  - Authors:

@johnnyreilly
@bbenezech
@pzavolinsky
@digiguru
@ericanderson
@DovydasNavickas
@theruther4d
@guilhermehubner
@ferdaber
@jrakotoharisoa
@pascaloliv
@hotell
@franklixuefei
@Jessidhia
@saranshkataria
@lukyth
@eps1lon
@zieka
@dancerphil
@dimitropoulos
@disjukr
@vhfmag
@hellatan

**Comment by dimitropoulos** [comment]
I'll second that.  Also, it seems like usually when the return type is needed it's for a reason that uncovers another issue.  That's not universally true, but it's been the trend.

**Comment by lukewlms** [comment]
Thanks for the extra info.  It seems like ReactNode is the intended eventual return type, is that right?  I.e. at that point JSX will be able to return not just Element or null, but also string, undefined, etc.  If that's the case then my suggestion would only be a stopgap.  We'll keep using it internally but plan to switch to ReactNode once that becomes compatible.
