### ISSUE TITLE
[@types/react-tracking] outdated type for useTracking hook

### ISSUE THREAD

**Issue by EduardoAraujoB** [DefinitelyTyped/DefinitelyTyped#52105]
# Problem
Latest version of `@types/react-tracking` have wrong type definitions for the hook `useTracking` since the library had an update and now this hooks returns a `Tracking` component that is missing in the type definitions and also accepts an object in this format `{ page: 'FooPage', action: 'childClick'}` as a parameter

- Authors: @damassi @alloy @ForbesLindesay @ferdaber @drbalm @sad-squid @chenasraf

**Comment by damassi** [comment]
@EduardoAraujoB - Will happily accept a PR if you don't mind.

**Comment by EduardoAraujoB** [comment]
@damassi I could do that, but I'm having issues to isolate some props of the track decorator and add it to the hook, also I'm having issues to type the provider from the track component, the local changes that I made isn't the ideal types to submit

**Comment by chenasraf** [comment]
Made a PR with the required changes, would love some feedback if anything is missing or needs to be changed, so this can be merged as promptly as possible. Thank you :)

/cc @alloy @damassi @EduardoAraujoB

**Comment by EduardoAraujoB** [comment]
thanks a lot @chenasraf I will check it out
