### ISSUE TITLE
[@types/copy-webpack-plugin] Types of parameters "compiler" and "compiler" are incompatible

### ISSUE THREAD

**Issue by SamuelTrew** [DefinitelyTyped/DefinitelyTyped#52114]
- [ .] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ .] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ .] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ .] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @amcasey @peterblazejewicz 
 
Sorry if I haven't tagged the relevant authors

- Operating System: Ubuntu 20.04
- Node Version: 12.15.0
- NPM Version: 6.14.8
- webpack Version: 5.28.0
- copy-webpack-plugin Version: 8.1.0
- - @types/xxx version: 6.4.1

### Expected Behavior

It should just run normally and copy the files

### Actual Behavior

Gives an error of `Types of property 'apply' are incompatible`, `Types of parameters 'compiler' and 'compiler' are incompatible` and that `Property '_pluginCompat' is missing in type {webpack/types}.Compiler but required in type {@types/copy-webpack-plugin/node_modules/@types/webpack/index}.Compiler`.

### Code

```js
new CopyPlugin({
         patterns: [{ from: path.resolve(__dirname, "public", "_redirects"), to: "dist" }],
}),
```

### How Do We Reproduce?

Just use the copy plugin as provided with the latest webpack, webpack types and copy versions

Thanks!

**Comment by amcasey** [comment]
Tagging the authors: @flying-sheep, @avin-kavish, @peterblazejewicz based on the list [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d436c208e28411811d3a0f8e2dceb0e7bb50218e/types/copy-webpack-plugin/index.d.ts#L3).

**Comment by peterblazejewicz** [comment]
@SamuelTrew 
There should be no `@types/webpack`, if you're using webpack@5.
So when you're move `@types/wepback` (4.*), it should compile just fine.
I think we should update `copy-webpack-plugin` to v8 and add dependency via package.json to webpack@% (so it won't resolve to @types/webpack

**Comment by peterblazejewicz** [comment]
@SamuelTrew do you have this option in your(s) tsconfig(s):
```json
"skipLibCheck": false,  
```

**Comment by peterblazejewicz** [comment]
#51556

**Comment by SamuelTrew** [comment]
Ahhh I see, my bad.
I have it set to true?
Testing with false lead to no difference once I removed @types/webpack.

Thank you so much! Removing the package worked!
