### ISSUE TITLE
Sharepoint.d.ts implicitly has 'any' type

### ISSUE THREAD

**Issue by Koen028** [DefinitelyTyped/DefinitelyTyped#5211]
Hi,
I'm very new to TypeScript and I recently ran into the following problem while using the sharepoint.d.ts.
When I try to build/compile my project in Visual Studio 2013 Update 5 + Web Essentials I get a lot of errors that have to do with not using the any statement in TypeScript. I have tried changing the TypeScript Build option "Allow implicit 'any' types" in the Project properties without succes.

An example of this problem can be found on line 653:

``` javascript
constructor(actionsId);
```

If I change that line to the following it gives no errors:

``` javascript
constructor(actionsId: any);
```

I would really like to know if I am doing something wrong.

Greetings,
Koen

**Comment by horiuchi** [comment]
@Koen028 Please fix the bug and send pull request :smile: 
I'll review that.
