### ISSUE TITLE
[@types/node-fetch] add ReferrerPolicy type

### ISSUE THREAD

**Issue by ahsan-a** [DefinitelyTyped/DefinitelyTyped#52173]
- [x] I tried using the `@types/node-fetch` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @torstenwerner
  - @nikcorg
  - @vinaybedre
  - @kyranet
  - @AndrewLeedham 
  - @JasonLi914
  - @southpolesteve
  - @ExE-Boss
  - @alexandrusavin
  - @OmgImAlexis
  - @kbkk

ReferrerPolicy types don't exist, and attempting to fetch with a referrerPolicy leads to an error. Possible referrerPolicies include:

```js
{
  "",
  "no-referrer",
  "no-referrer-when-downgrade",
  "same-origin",
  "origin",
  "strict-origin",
  "origin-when-cross-origin",
  "strict-origin-when-cross-origin",
  "unsafe-url"
}
```

**Comment by southpolesteve** [comment]
@ahsan-a This seems to be intentional. The node-fetch project documents `referrerPolicy` as not being implemented: https://github.com/node-fetch/node-fetch/tree/9e50c5bbc17dfc21e418fd798a45fb4fd0ae7b44#class-request. Have you opened an issue with the project itself? I'm generally of the opinion the types should match what the project actually does.

**Comment by ahsan-a** [comment]
Oh, I just copied the fetch request for the website I'm trying to make a CLI of from chrome devtools. The errors didn't show in JS and everything worked fine so I assumed this was a typescript types issue, and I didn't realise it wasn't supported in node-fetch. When removing the unsupported parts everything still worked fine. This was an issue on my end, sorry for the notification.
