### ISSUE TITLE
[Suggestion Discussion] Adding explicit descriptions to @types/mongodb

### ISSUE THREAD

**Issue by ImRodry** [DefinitelyTyped/DefinitelyTyped#52199]
- [X] I tried using the `@types/mongodb` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT @alanmarcell @dante-101 @mcortesi @EnricoPicci @AJCStriker @julien-c @daprahamian @denys-bushulyak @BastienAr @sindbach @geraldinelemeur @various89 @angela-1 @hector7 @floric @erikc5000 @Manc @jloveridge @ranguna @HosseinAgha @albertossilva @peterblazejewicz @LinusU @taxilian @xamgore @avaly @HitkoDev @Celend @jtassin @addaleax @emmanuelgautier @wyattjoh

The title of the issue may not be self-explanatory so let me elaborate. On the @types/mongodb package, all descriptions for all methods have `@see` and a link to the mongodb documentation, instead of having a simple and brief explanation of that the method does, as well as its accepted parameters and the returning type. While I understand that the documentation on the website is more complete, this is often an issue because most of the time you want a quick explanation without having to go on the website looking for what you want.
That being said, I'd like to propose the addition of more explicit descriptions to this package so that the people that use it can have an easier time.
Lastly, I made this issue since I didn't want to waste my time making a PR just for it to be rejected so I wanted to discuss the idea with the owners first to see what they think before making the said PR.

**Comment by LinusU** [comment]
I think it would be nice, as long as we also keep the `@see` links to the upstream documentation. I also think that we should copy the documentation exactly from upstream, and not try and write our own...

**Comment by ImRodry** [comment]
Yeah that was exactly my idea! We just need to make sure we get everything from the right places because sometimes the documentation can be slightly confusing.

**Comment by ImRodry** [comment]
While going through the links I noticed they all link to version 3.1 despite version 3.6 being available. Should I update them all to v3.6? (some would be deleted since they were removed)

**Comment by peterblazejewicz** [comment]
The will be tedious, but it's worth of it. An IDE like VSCode shows only DT help, nothing more, without an option from native package JSDOC. It shows multiple hints, but all are coming from TS world.

**Comment by ImRodry** [comment]
@peterblazejewicz it is indeed tedious and VSCode doesn't show all of the information that you can add therefore I'll only add the info that it does show. This will be useful either way because you can get summarized descriptions of what the methods do (which are already on the mongodb docs we just need to copy them)

**Comment by ImRodry** [comment]
> While going through the links I noticed they all link to version 3.1 despite version 3.6 being available. Should I update them all to v3.6? (some would be deleted since they were removed)

bumping this

**Comment by ImRodry** [comment]
It seems like https://mongodb.github.io/node-mongodb-native/3.6/api/Db.html#aggregate is missing from the package, could one of you add it? I've started working on the JSDoc comments, I can start the draft PR if you wish

**Comment by ImRodry** [comment]
I just now realized that all the mongodb docs links are redirecting to the v4.4 docs instead of v3.6 which is what these types are for, and thus there are some types from v4.4 in the package. Should I keep it this way or try to fix the ones I come across?

**Comment by wyattjoh** [comment]
I've been (personally at least) treating the types here as the "latest" version. There doesn't seem to be a super clear way to bind types to a specific version of the client.

**Comment by ImRodry** [comment]
> I've been (personally at least) treating the types here as the "latest" version. There doesn't seem to be a super clear way to bind types to a specific version of the client.

At the very top of the types file it says what version these types are for and, for mongodb, it says 3.6 so I would assume that all types are for this version and not the betas

**Comment by wyattjoh** [comment]
For some reason I misunderstood the versions... 3.x is the most recent stable release, you're right! I'd say if there was a variant of the documentation links that was "current" that would be ideal, but from cursory search, that doesn't seem to be the case.

**Comment by ImRodry** [comment]
Well we can easily mass replace all the latest version URLs to 3.6 just
like I did in my PR with the other docs (updated from 3.1 to 3.6) and if
3.7 or above is released we do the same again

This does mean, however, that some types are wrong and I’ve only spotted
one instance so far and I’m not sure if there are more and how many they are

**Comment by ImRodry** [comment]
Another question that just popped up: the QuerySelector type does not match the types given in the linked docs as it's missing a few and has types that cannot be found there. How should I go on about this? https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongodb/index.d.ts#L1994 here's the line

**Comment by LinusU** [comment]
> Another question that just popped up: the QuerySelector type does not match the types given in the linked docs as it's missing a few and has types that cannot be found there. How should I go on about this?

I think that the smoothest path forward would probably be to create a separate PR to fix those types, it should be an easy merge!

Also want to say a big thank you for your work, the draft PR looks amazing 🤩

**Comment by ImRodry** [comment]
Yeah, I wasn't thinking of including those in this one since these types look way too complicated and I can't find them in the official docs so I'll leave that up to you guys (although I will include the correct parameters in the JSDoc comment).

And thanks for the kind words :D I'll try to finish it by the weekend so that it can be reviewed and merged.
