### ISSUE TITLE
[@types/react-router-dom] Can install wrong version of @types/react-router

### ISSUE THREAD

**Issue by asktree** [DefinitelyTyped/DefinitelyTyped#52193]
I suspect this is an issue with DefinitelyTyped at large, but am not sure.

```

    "node_modules/@types/react-router": {
      "version": "4.4.0",
      "resolved": "https://registry.npmjs.org/@types/react-router/-/react-router-4.4.0.tgz",
      "integrity": "sha512-b16Fpy4nsxC4Ntu72+VAl0kYd1qrT8M5aRGBJ0D4RoY5QeGaA5VguPWu1If2+g2dLNvb8A4vAMQAcDgYdQ4L9w==",
      "dev": true,
      "dependencies": {
        "@types/history": "*",
        "@types/react": "*"
      }
    },
    "node_modules/@types/react-router-dom": {
      "version": "5.1.7",
      "resolved": "https://registry.npmjs.org/@types/react-router-dom/-/react-router-dom-5.1.7.tgz",
      "integrity": "sha512-D5mHD6TbdV/DNHYsnwBTv+y73ei+mMjrkGrla86HthE4/PVvL1J94Bu3qABU+COXzpL23T1EZapVVpwHuBXiUg==",
      "dev": true,
      "dependencies": {
        "@types/history": "*",
        "@types/react": "*",
        "@types/react-router": "*"
      }
    },
```

So we upgrade to 5.1.7 but it doesn't upgrade @types/react-router. This caused us problems (the specifics of which don't seem important). The problems were fixed once I accidentally jostled pkg lock and made it install @types/react-router 5.1.13 instead. 

This seems like it should definitely NOT happen! Is there something that the @types/react-router-dom authors can do to version intelligently, or is this a problem with DefinitelyTyped in general?

**Comment by asktree** [comment]
@huy-nguyen
@p-jackson
@johnnyreilly

**Comment by jakebailey** [comment]
react-router-dom now has native types, so there's nothing that can be done in DT for this.
