### ISSUE TITLE
[@types/codemirror] Missing addon/dialog types

### ISSUE THREAD

**Issue by Yash-Singh1** [DefinitelyTyped/DefinitelyTyped#52268]
The `addon/dialog` types are not there yet for codemirror.

Authors: @mihailik, @nrbernard, @Pr1st0n, @rileymiller, @toddself, @ysulyma, @azoson, @kylesferrazza, @fityocsaba96, @koddsson, @ficristo

**Comment by stof** [comment]
@Yash-Singh1 I have a good news for you. I just opened a PR adding all missing codemirror addons (as well as fixing core types)
