### ISSUE TITLE
[@types/react-helmet] Property metaTags does not exists on HelmetData, but returns from Helmet.peek

### ISSUE THREAD

**Issue by gabrielmaiaf** [DefinitelyTyped/DefinitelyTyped#52290]
- [x] I tried using the `@types/react-helmet` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @evanbb @isman-usoh @sammkj @yuit @ykzts @wKovacs64 @Andriy2 @peterblazejewicz 

Issue:
I tried to use Helmet.peek() to get metaTags while writing tests but it shows that doesn't exists on type HelmetData, but it exists if I create a variable containing all data from Helmet.peek(), as it shown on print screen.
![image](https://user-images.githubusercontent.com/28790641/114201171-d3cea980-994d-11eb-944c-32a0ba696c84.png)

If I write meta, as wrote in HelmetData type, it shows nothing:
![image](https://user-images.githubusercontent.com/28790641/114201389-0b3d5600-994e-11eb-895f-eb9a0c8397fe.png)

**Comment by peterblazejewicz** [comment]
@gabrielmaiaf mind posting proper snip? Would be tremendous help, thx!

**Comment by gabrielmaiaf** [comment]
@peterblazejewicz I used in this test, using Helmet.peek()  https://www.github.com/gabrielmaiaf/gabrielmaiaf.github.io/tree/master/src%2F__tests__%2Fcomponents%2Fseo.spec.tsx

I followed this test: https://www.takeshape.io/articles/unit-testing-your-gatsby-site-with-jest-and-react-testing-library/

**Comment by wKovacs64** [comment]
Hmm, that output from `Helmet.peek()` looks something like `Partial<HelmetData & HelmetTags>`?

**Comment by gabrielmaiaf** [comment]
@wKovacs64 just returns HelmetData:
![image](https://user-images.githubusercontent.com/28790641/114243861-460eb080-9985-11eb-9b73-7366e4168332.png)

**Comment by wKovacs64** [comment]
> @wKovacs64 just returns HelmetData:

Currently, yes, that's how the types are defined. I'm questioning whether that's accurate (doesn't appear to be). 🤔

**Comment by gabrielmaiaf** [comment]
I seeing that it's just HelmetData, but doesn't have HelmetTags 
```tsx
export interface HelmetProps {
    async?: boolean;
    base?: any;
    bodyAttributes?: BodyProps;
    defaultTitle?: string;
    defer?: boolean;
    encodeSpecialCharacters?: boolean;
    htmlAttributes?: HtmlProps;
    onChangeClientState?: (newState: any, addedTags: HelmetTags, removedTags: HelmetTags) => void;
    link?: LinkProps[];
    meta?: MetaProps[];
    noscript?: Array<any>;
    script?: Array<any>;
    style?: Array<any>;
    title?: string;
    titleAttributes?: Object;
    titleTemplate?: string;
}
declare class Helmet extends React.Component<HelmetProps> {
    static peek(): HelmetData;
    static rewind(): HelmetData;
    static renderStatic(): HelmetData;
    static canUseDOM: boolean;
}```

**Comment by peterblazejewicz** [comment]
follks correct me, if I'm wrong. Due to side effect func, the peek should really return entire internal state (during testing, as per note), not this 'Datum' thing

**Comment by peterblazejewicz** [comment]
should we recode return for peek to this shape?
https://github.com/nfl/react-helmet/blob/master/src/HelmetUtils.js#L209-L258

**Comment by wKovacs64** [comment]
Yep, there we go. 👍
