### ISSUE TITLE
[@types/styled-system] fontWeights on theme don't accept string as values

### ISSUE THREAD

**Issue by ebellumat** [DefinitelyTyped/DefinitelyTyped#52303]
In React Native on iOS i can't define the values of the properties from fontWeights as numbers, this cause errors.

Because of that, in my theme i have to define the fontWeights as string instead numbers. 

```typescript
export const theme = {
   ...
  fontWeights: {
    light: '300',
    normal: '400',
    medium: '500',
    SemiBold: '600',
    bold: '700',
    black: '900',
  },
  ...
 ```
 
 But, because of that, the type of RequiredTheme doesn't recognize my type, even if this working as a string, causing this annoying error on typescript.

![image](https://user-images.githubusercontent.com/26942680/114249937-77ca4c00-9972-11eb-89f0-0bb5175dfca4.png)

Please, anyone can add string on the definitions? In the docs of Styled-system this can be defined as a string.

Authors: @phobon @zephraph @damassi @alloy @maoueh @lavoaster @jschuler @adam187 @gretzky @chrislopresto @peduarte @Dhalton @elliotbonneville @jackcaldwell @eliseumds @craga89 @HipsterBrown @hammadj @maddhruv
@cherewaty

**Comment by damassi** [comment]
Hi @ebellumat - these tyeps come directly from [`csstype`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-system/index.d.ts#L26), and are applied [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-system/index.d.ts#L43).

So you'll want to file this issue over at that lib if having trouble.

**Comment by ebellumat** [comment]
Theres a easy way to override this type?
