### ISSUE TITLE
[@types/mongodb] $pull operator does not support conditions

### ISSUE THREAD

**Issue by dordadush** [DefinitelyTyped/DefinitelyTyped#52342]
- [x] I tried using the `@types/mongodb` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT @alanmarcell @101 @mcortesi @EnricoPicci @AJCStriker @c @daprahamian @Bushulyak @BastienAr @sindbach @geraldinelemeur @various89 @1 @hector7 @floric @erikc5000 @Manc @jloveridge @Ranguna @HosseinAgha @albertossilva @peterblazejewicz @LinusU @taxilian @xamgore @avaly @HitkoDev @Celend @jtassin @addaleax

Official [docs](https://docs.mongodb.com/manual/reference/operator/update/pull/) states that the `$pull` operator accepts a value or a condition in an update query.

The calculated typing of a field in the `$pull` operation is as follows:
```
(property) field?: Partial<ObjectId> | {
    generationTime?: QuerySelector<number> | undefined;
    equals?: QuerySelector<(otherID: string | ObjectId) => boolean> | undefined;
    getTimestamp?: QuerySelector<...> | undefined;
    toHexString?: QuerySelector<...> | undefined;
} | undefined
```

By this definition, I cannot use a condition as stated in the docs in order to `$pull` items that match a specified condition:
```
someModel.updateMany({}, {
  $pull: {
    someField: { $in: someList }
  }
}, options),
```

**Comment by LinusU** [comment]
> [...] I cannot use a condition as stated in the docs in order to [...]

Could you post an example of the code you want to use to do this?

**Comment by dordadush** [comment]
yes of course.
```
models.device.updateMany({}, {
  $pull: {
    someField: { $in: someList}
  }
}, options),
```

trying to `$pull` inside an `updateMany` operation.
added it to the issue description, thanks!

**Comment by LinusU** [comment]
The `@types/mongodb` packages has been removed and typings are now shipped upstream as part of the `mongodb` package, so this issue can be closed...

**Comment by peterblazejewicz** [comment]
Closing as per last comment
