### ISSUE TITLE
[@types/node] worker_threads.MessagePort does not extend EventTarget

### ISSUE THREAD

**Issue by stephenash** [DefinitelyTyped/DefinitelyTyped#52340]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ExE-Boss @SimonSchick @peterblazejewicz

Since v14.7 [`worker_threads.MessagePort`](https://nodejs.org/dist/latest-v15.x/docs/api/worker_threads.html#worker_threads_class_messageport) changed to extend `EventTarget` instead of `EventEmitter` in order to more closely match the [browser APIs](https://developer.mozilla.org/en-US/docs/Web/API/MessagePort). With `@types/node@14.14.37`, the `EventTarget` APIs are not available

```typescript
import { MessageChannel } from 'worker_threads';
const { port1: aelPort1, port2: aelPort2 } = new MessageChannel();

function messageListener(event: any) {
    console.log('Received from messageListener: ', event.data);
}
// @ts-ignore
aelPort1.addEventListener('message', messageListener);
aelPort2.postMessage("sending message to addEventListener");

setTimeout(() => {
    // @ts-ignore
    aelPort1.removeEventListener('message', messageListener);
    aelPort2.postMessage("should not log");
}, 100);

const { port1: onPort1, port2: onPort2 } = new MessageChannel();
// Existing EventEmitter APIs
onPort1.on('message', (event) => {
    console.log('Received from .on(): ', event);
});
onPort2.postMessage("sending message to on");

const { port1: onmessagePort1, port2: onmessagePort2 } = new MessageChannel();
// @ts-ignore
onmessagePort1.onmessage = (e: Event) => {
    // @ts-ignore
    console.log('Received from .onmessage: ', e.data);
}
onmessagePort2.postMessage("sending message to onmessage");

setTimeout(() => {
    aelPort1.close();
    aelPort2.close();

    onPort1.close();
    onPort2.close();

    onmessagePort1.close();
    onmessagePort2.close();
}, 1000);
```

When the above is [compiled](https://www.typescriptlang.org/play?module=1#code/JYWwDg9gTgLgBAbzgWQKYGd0EMDmqDCAFlgHYmoA2cAvnAGZQQhwDkA7tANapQD6MhKKiwATdCwDcAKADGEEunhJIsAIwAuOFkoAFaDFUAaOCpgAmTdop7YZmnAC8ccmxQZseIqXIUAFAEppKToAVxIZGGB5OBB3XFQAGWBFVHIoX1QAN1SYSxIAT39EKThSuDkFCApUADoKCBxfFgAlVBlUYGyRekZmWMx4pJS0zRZjLJyakSwYLECpaikAeiW4AAEYdABaYBwSaFQpKxsDGtERAFFskhghmFSeJv6PVDGYuLw7h6h54-0zGqQRRoAZ4XwAInQqREwBIOHeoNQcBgEC0Iku11uyXuaXB8ykUJgABVQKgICEYL4Ao4AHzFMpwFbrTY7PYHEplP5qGpCEAQbJXHJfNJPD6vYzPQbY77zBlc8yAiDAsUQ9CEckUbr7eD1HB46TUYyqAAMxvxFUUiBM+g0cHkJyM1tsmnt-3sThcbkRXjIlAC0iZFwAHtjYfDBTcLiBgDB7lA4ABBHQASXQUld3PkosRbwymKKDjpCA5pQtVVquqarXanVQ3QYTDgNSz-lG43zBvmGYVQJgIJequhYYRL2RqPk+qksnkluUNpdJEleAdxlMFjti7FJzstA9qFc-fiPp8-uWqw2212+yE6c3iIdzbvo6cGU0EZgBaLJcZ55ZV-ZDJltUdQNFWbQdF0PSNo+S6oG2cC1NMszzIs8iwduirKoig4kDCcIjvEY4brBk4EqgxKkuSlLUoW9KcroNo1DI9RQqecoMbYTEsagp7ft2qhcUqPGymU3YAsxQm8QyaFboxEmsSJpQyfe-yCQpBpGqaZoSEAA) and the result run in Node, the messages are all received as expected.

```
$ node worker_example.js
Received from messageListener:  sending message to addEventListener
Received from .on():  sending message to on
Received from .onmessage:  sending message to onmessage
```

**Comment by F3n67u** [comment]
Should we change `MessagePort` to extends `EventTarget` instead of `EventEmitter`? @SimonSchick I am willing to work on this issue if needed.

**Comment by F3n67u** [comment]
related issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/52976

**Comment by wellwelwel** [comment]
It's been a while, but I opened a _PR_ (#69723) to solve this issue with a simple approach. It would be great if someone could review it.
