### ISSUE TITLE
[@types/jest] type def for toThrow is incomplete. does not allow all throwable types.

### ISSUE THREAD

**Issue by rally25rs** [DefinitelyTyped/DefinitelyTyped#52346]
## 🐛 Bug Report

Typescript definition for `toThrow` is incorrect

## To Reproduce

```
test('js throw', async () => {
  async function testFunc() {
    throw {};
  }

  await expect(testFunc()).rejects.toThrow({}); // ts error
});
```

results in

```
Argument of type '{}' is not assignable to parameter of type 'string | RegExp | Error | Constructable | undefined'.
  Type '{}' is not assignable to type 'Constructable'.
    Type '{}' provides no match for the signature 'new (...args: any[]): any'.ts(2345)
```

## Expected behavior

Anything is throwable in JS.
The type def
```
        toThrow(error?: string | Constructable | RegExp | Error): R;
```
is incomplete and should probably just be `any` 🤷 

```
$ node
Welcome to Node.js v12.18.3.
Type ".help" for more information.
> throw []
Uncaught []
> throw {}
Uncaught {}
> throw null
Uncaught null
> throw Infinity
Uncaught Infinity
```

* @types/jest@26.0.20
* jest@26.6.3

Authors: @NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @ahnpnl @JoshuaKGoldberg @UselessPickles @r3nya @Hotell @sebald @andys8 @antoinebrault @gstamac @ExE-Boss @quassnoi @Belco90 @tonyhallett @ycmjason @devanshj @pawfa @regevbr

**Comment by tonyhallett** [comment]
At a quick glance the type definition agrees with the code
https://github.com/facebook/jest/blob/master/packages/expect/src/toThrowMatchers.ts

**Comment by rally25rs** [comment]
huh, ok, I was seeing:
  
```
function (
    this: MatcherState,
    received: Function,
    expected: any,
  ): ExpectationResult

  ...

  else if (expected !== null && typeof expected === 'object') {
      return toThrowExpectedObject(matcherName, options, thrown, expected);
```

and thinking `expected` is whatever is being passed to `toThrow(expected)`, which is type `any` in this jest source, but is typed `string | RegExp | Error | Constructable | undefined` in this .d.ts, and so causes a TS type mismatch error.

-----

Though it seems the actual jest `toThrow` matcher doesn't seem to work as I expected if you pass it an object anyway. I would have expected both of these to pass:

```
describe('tothrow', () => {
  function throwString() {
    throw 'str';
  }

  function throwObj() {
    throw {x: 1};
  }

  it('can test for a string being thrown', () => {
    expect(() => {
      throwString();
    }).toThrow('str');
  });

  it('can test for an object being thrown', () => {
    expect(() => {
      throwObj();
    }).toThrow({x: 1});
  });
});
```

but they don't
```
  tothrow
    ✓ can test for a string being thrown
    ✕ can test for an object being thrown (1 ms)

  ● tothrow › can test for an object being thrown

    expect(received).toThrow(expected)

    Expected message: undefined
    Received value:   {"x": 1}

      189 |     expect(() => {
      190 |       throwObj();
    > 191 |     }).toThrow({x: 1});
          |        ^
      192 |   });
      193 | });
      194 |
```

Weird... Oh well 🤷 

I can do the same thing with a `try/catch` in the test instead of the `toThrow` matcher anyway.

**Comment by tonyhallett** [comment]
> Though it seems the actual jest toThrow matcher doesn't seem to work as I expected

I'd expect that expect works as is documented
https://jestjs.io/docs/expect#tothrowerror
