### ISSUE TITLE
@types/node: missing `os.version()`

### ISSUE THREAD

**Issue by ilg-ul** [DefinitelyTyped/DefinitelyTyped#52354]
The definition of the `version()` function is missing from `@types/node/os.d.ts`.

**Comment by SimonSchick** [comment]
Please update your issue with the [issue template](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/ISSUE_TEMPLATE.md), the method is present in the [latest typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a1047ce24a0d9a4d0bcfc39cd9d2493bfd7fca2b/types/node/test/os.ts#L10) and has been for a long time.

**Comment by ilg-ul** [comment]
Oops! You are right, I was using `"@types/node": "^12.20.8"` where the function is missing, while the latest version is 14.14.39, where `os.version()` **is** defined.

Thank you, and sorry for the inconveniences.
