### ISSUE TITLE
error TS2304: Cannot find name 'Element' from @types/sizzle/index.d.ts:81:68

### ISSUE THREAD

**Issue by mrudangshah** [DefinitelyTyped/DefinitelyTyped#52383]
- [ ] I have tried this [link](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46167#issue-659993549) to fix my issue but it throws an error from this [@types/sizzle](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/sizzle) bundle

![Screenshot from 2021-04-15 11-16-33](https://user-images.githubusercontent.com/16753977/114830837-4b875300-9dea-11eb-9e47-88c41215cdb1.png)

Details:
package.json 
```
"scripts": {
    "build": "tsc server.ts --lib ES2015 --outDir dist",
    "start:watch": "tsc server.ts --lib ES2015 --outDir dist -w & nodemon dist/server.js"
},
"dependencies": {
"@types/node": "^10.9.4",
"ts-node": "^7.0.1",
"typescript": "^3.9.6",
}
```
tsconfig.js
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": { "*": ["types/*"] },
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": [
            "es2015",
            "DOM"
        ],
        "outDir": "./dist/",
        "rootDir": "./",
    },
}
```
Global Typescript version 4.2.4

@davecardwell @marvinhagemeister : can you please look into this ?

**Comment by fedemp** [comment]
I think it should be `dom`, not `DOM`. Maybe that's your problem.
