### ISSUE TITLE
Bump @types/cssnano/postcss version range to v5 - 8

### ISSUE THREAD

**Issue by nigelellis** [DefinitelyTyped/DefinitelyTyped#52498]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@types/cssnano@4.0.0` for the project I'm working on.

This bumps cssnano dependency to support postcss v8.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@types/cssnano/package.json b/node_modules/@types/cssnano/package.json
index a2d12ee..712a64a 100644
--- a/node_modules/@types/cssnano/package.json
+++ b/node_modules/@types/cssnano/package.json
@@ -17,7 +17,7 @@
     },
     "scripts": {},
     "dependencies": {
-        "postcss": "5 - 7"
+        "postcss": "5 - 8"
     },
     "typesPublisherContentHash": "a43be2c23af399f805d4e3e547b96760d5764e23481854a118d64cb23f470e78",
     "typeScriptVersion": "2.2"
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by stof** [comment]
Technically, the right fix would be to write type declarations for cssnano 5.0 (which would then depend on postcss 8 only, not on older versions)

**Comment by rchl** [comment]
But if the `cssnano` v5 doesn't have any breaking changes type-wise then it would be OK to just update the range? The type definitions for `cssnamo` are very simple.

But new major version of types would also be fine by me.

**Comment by Semigradsky** [comment]
`@types/cssnano` was removed, this ticket can be closed.
