### ISSUE TITLE
Add definition for angular-grid (ag-grid)

### ISSUE THREAD

**Issue by Kimpossibru** [DefinitelyTyped/DefinitelyTyped#5249]
I'd love to have a type file for angular-grid:

Project: https://github.com/ceolter/angular-grid

**Comment by Kimpossibru** [comment]
I think this is it:
https://gist.github.com/greglockwood/67ea53a5f43852ba24c4

Can we include it in TSD?

**Comment by Kimpossibru** [comment]
Here's the official one... oops :)
https://github.com/ceolter/angular-grid/blob/master/dist/angular-grid.d.ts

Would be nice to have it in TSD, though.

**Comment by ildarnm** [comment]
+1

**Comment by vvakame** [comment]
#6085
