### ISSUE TITLE
@types/react-window has an inccorect type on property height in interface FixedSizeListProps

### ISSUE THREAD

**Issue by oscarcarlstrom** [DefinitelyTyped/DefinitelyTyped#52615]
I am using the `@types/react-window` package and found an inncorrect type:
The **FixedSizeListProps** interface has a height property (**FixedSizeListProps['height']**) with type [**string | number**](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-window/index.d.ts#L127)

But if a string is provided to the height prop in FixedSizeList, you get the following error:
`Error: An invalid "height" prop has been specified. Vertical lists must specify a number for height. "string" was specified.`

Not sure if this is the intended behaviout of react-window or not. Hence no PR. It would make sense to accept number | string, since it can be very useful with a relative height (such as '50%', for example).

- Authors: @martynaskadisa , @heyimalex . @jgoz 

Also, @bvaughn the author of [react-window]( https://github.com/bvaughn/react-window) might want to take this into consideration.

**Comment by martynaskadisa** [comment]
I took that definition from react-window's docs:
> For horizontal lists, this can be a number or a string (e.g. "50%").
https://react-window.vercel.app/#/api/FixedSizeList

From your error message I'd assume you are trying to pass height as string to a vertical list, where height can only be a string when your list is in horizontal layout. Seems to be working as expected when `FixedSizeList` has `layout="horizontal"`
https://codesandbox.io/s/angry-http-144cm?file=/src/App.tsx

**Comment by bvaughn** [comment]
@martynaskadisa is correct.

**Comment by oscarcarlstrom** [comment]
Thanks guys! First time using react-window, so not quite familiar with the API yet. So @bvaughn, I'm just curious, why not allow dynamic heights in vertical lists? I get that it affects the number of rows that will be rendered at any given time. But couldn't that be calculated if a ref to the parent component is passed to the list? Or by allowing a callback to be passed to the height property (which can calculate the height)?
