### ISSUE TITLE
React: 17.0.2 breaking on npm start

### ISSUE THREAD

**Issue by troy191990** [DefinitelyTyped/DefinitelyTyped#52649]
@nex3 Not sure who the correct author is to mention and not sure if its a duplicate issue.
I just ran create-react-app testapp --template typescript
and then did npm i 

When running the app (React: 17.0.2) I get the following error:
Could not find a declaration file for module 'react'. 'D:/TestApps/PartnerProgram/lines/node_modules/react/index.js' implicitly has an 'any' type.
  If the 'react' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react`  TS7016

  > 1 | import React from 'react';
      |                   ^
    2 | import logo from './logo.svg';
    3 | import './App.css';
    4 |

Downgrade to React: 17.0.1 resolved the issue.

**Comment by samarmohan** [comment]
Make sure `@types/react`, `@types/react-dom`, and `@types/node` are installed.
