### ISSUE TITLE
[@types/chrome] Update types definition to support new MV3

### ISSUE THREAD

**Issue by LoKy-dev** [DefinitelyTyped/DefinitelyTyped#52677]
In November 9, 2020 Google has released a new version of its manifest for developing Chrome extension (you can check it out [here](https://developer.chrome.com/docs/extensions/mv3/intro/)).

With this chrome API now most methos support the Promise object, but this repo it's not been update to support them so most of the IDEs or Typescript repos that use this typing file give warning like this:
```javascript
// Void function return value is used!
let createdTab = await chrome.tabs.create({ url: 'https://example.com/' });
```
even if the code does work correctly (as you can check in the [offical documentation](https://developer.chrome.com/docs/extensions/reference/tabs/#method-create)).

**Comment by LoKy-dev** [comment]
Thank you @krisztianb for the datailed explanation.
I've been active on personal and friends project committing directly the changes to te repositories, this the first time that i'm contributing to an open repo, happy to help.

**Comment by yoichiro** [comment]
I have just submitted the pull request #53120 to add definitions for new functions which support a Promise.

**Comment by yoichiro** [comment]
@LoKy-dev The pull request #53120 has already been merged, and the new version for Promise support is available. If it works for you, you can close this issue, I think.

**Comment by LoKy-dev** [comment]
Yep, that totally worked. Thanks to all so much for your time and efforts.
