### ISSUE TITLE
@ckeditor/ckeditor5-core Typings: Wrong readonly modifier for value property

### ISSUE THREAD

**Issue by mmichaelis** [DefinitelyTyped/DefinitelyTyped#52759]
Typings for CKEditor's `Command` mark the `value` property as readonly:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/495730c9aca0e0bf1b43b90bdfffb35ddc8d14f6/types/ckeditor__ckeditor5-core/src/command.d.ts#L9

This is wrong, as it is quite typical that on `refresh` commands update their value according to the model. See for example `LinkCommand` implementation in Link Plugin.

This contradicts the documentation provided by CKEditor though:

* [Class Command (core/command~Command) - CKEditor 5 API docs](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_command-Command.html)

It marks the property as readonly, but this is wrong from the command perspective.

**Same applies to `isEnabled`.**

I assume, CKEditor wants to express: From the outside handle the property as readonly, but from a command implementation perspective, it must be writable.

**Comment by fedemp** [comment]
@mmichaelis Isn't the `value` property expected to be changed using the `set()` method?

**Comment by mmichaelis** [comment]
> @mmichaelis Isn't the `value` property expected to be changed using the `set()` method?

Not, if I take a look at the JavaScript sources for the `LinkCommand` for example: https://github.com/ckeditor/ckeditor5/blob/9af274efaf0ed5e8488aa305975dae85220e32b9/packages/ckeditor5-link/src/linkcommand.js#L67-L86

(This is the current reference I am using, because I implement something similar to the `LinkCommand`.)
