### ISSUE TITLE
@types/supertest polluting toplevel tsconfig with lib "dom"

### ISSUE THREAD

**Issue by maletor** [DefinitelyTyped/DefinitelyTyped#52765]
@types/supertest is including `dom` here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/supertest/tsconfig.json#L6

And when it does so, my entire project inherits this configuration, so I can use `BaseAudioContext` and other lib `dom` globals that make no sense in my strictly node project even though my `tsconfig.json` only includes `lib: ["es2020"]`.

What is actually going on here? Why does Typescript add `dom` to _my_ tsconfig (yet, `dom` doesn't show up in `npx tsc --showConfig`?) 

Could I use @types/supertest and not have dom included or is this strictly a bug and dom should be removed from here? I'm a little confused. Is this a types bug or a Typescript bug?

**Comment by maletor** [comment]
@jablko and @andy-ms

**Comment by aderant-smcd** [comment]
This is bothering me too - the current two solutions are adding dom to tsconfig on a project that is otherwise strictly node as maletor said, or reverting to @types/supertest 2.0.12 which doesn't seem to have the issue.

**Comment by jakebailey** [comment]
This is being fixed in #68402, no?

**Comment by DavidTanner** [comment]
This should be resolved with https://www.npmjs.com/package/@types/superagent/v/8.1.4
