### ISSUE TITLE
[hapi__hapi] Following 20.0.8, regression using hapi-auth-bearer-token type definitions

### ISSUE THREAD

**Issue by nulltoken** [DefinitelyTyped/DefinitelyTyped#52784]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

Following https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52509 by @saboya, it looks like leveraging `hapi-auth-bearer-token` types make TypeScript unhappy.

Given the following code

```ts
import * as Hapi from "@hapi/hapi";
import AuthBearer from 'hapi-auth-bearer-token';

...

await server.register([
  {
    plugin: AuthBearer
  }
]);
```

Using:
- `typescript`: 4.2.4
- `@hapi/hapi`: 20.1.2
- `hapi-auth-bearer-token`: 8.0.0
- `@types/hapi-auth-bearer-token`: 6.1.2

With @types/hapi__hapi`: 20.0.7 => No transpilation issue

With @types/hapi__hapi`: 20.0.8 => The following error is triggered
```
error TS2769: No overload matches this call.
  The last overload gave the following error.
    Type '{ plugin: Plugin<{}>; }' is not assignable to type 'Plugin<any>'.
      Object literal may only specify known properties, and 'plugin' does not exist in type 'Plugin<any>'.

80       plugin: AuthBearer
         ~~~~~~~~~~~~~~~~~~

  node_modules/@types/hapi__hapi/index.d.ts:3886:5
    3886     register(plugins: Plugin<any> | Array<Plugin<any>>, options?: ServerRegisterOptions): Promise<void>;
             ~~~~~~~~
    The last overload is declared here.
```

Given @saboya is also credited as author of the `hapi-auth-bearer-token` type package, I figured he might be the good person to reach out for help.

BTW, would anyone nudge in the proper direction, I'd be more than happy to open a pull request.

**Comment by saboya** [comment]
At first glance I can't see how that PR can possibly cause this, but I'll look into it and see if I can reproduce. Thanks for the report.

**Comment by nulltoken** [comment]
> At first glance I can't see how that PR can possibly cause this, but I'll look into it and see if I can reproduce. Thanks for the report.

Thanks for the feedback. I'm a little puzzled as well... However, I can consistently repro the issue.

**Comment by saboya** [comment]
This doest not produce an error for me, can you double check that you're doing everything correctly?

```typescript
import * as Hapi from "@hapi/hapi";
import AuthBearer from 'hapi-auth-bearer-token';

const server = Hapi.server();

await server.register([
  {
    plugin: AuthBearer
  }
]);

await server.register(AuthBearer);

await server.start();
```

**Comment by nulltoken** [comment]
@saboya Found! For some reason, my yarn.lock file was containing an old entry

```
"@types/hapi__hapi@*":
  version "20.0.5"
  resolved "https://registry.yarnpkg.com/@types/hapi__hapi/-/hapi__hapi-20.0.5.tgz#1cc41892a8ada002f4ee45fb8095b0aad0b0c17b"
  integrity sha512-xzGVjTr2i4xsJKKVrIOxVUq6H2m04ATtDiwOQHXdVBVnuEZoWbkN8tbb0L2S+DRXV7k2Zw5pW73YzDQHhbX5pw==
  dependencies:
    "@hapi/boom" "^9.0.0"
    "@hapi/iron" "^6.0.0"
    "@types/hapi__catbox" "*"
    "@types/hapi__mimos" "*"
    "@types/hapi__podium" "*"
    "@types/hapi__shot" "*"
    "@types/node" "*"
    joi "^17.3.0"
```

which was happily living next to

```
"@types/hapi__hapi@20.0.7":
  version "20.0.7"
  resolved "https://registry.yarnpkg.com/@types/hapi__hapi/-/hapi__hapi-20.0.7.tgz#c507ae81d49013727715ac4c8ac8f32892408719"
  integrity sha512-tJcizTio7R5O5uIRIRowAwru6sTjCGxGzRopMjm0Li5kIlSTtJ80z3hxpNZOW/7zfAuLIuh/kgG7kDHajT6AYw==
  dependencies:
    "@hapi/boom" "^9.0.0"
    "@hapi/iron" "^6.0.0"
    "@types/hapi__catbox" "*"
    "@types/hapi__mimos" "*"
    "@types/hapi__podium" "*"
    "@types/hapi__shot" "*"
    "@types/node" "*"
    joi "^17.3.0"
```

The upgrade to 20.0.8 caused some issues.

Dropping the old 20.0.5 star reference fixed everything.

**Comment by saboya** [comment]
@nulltoken np. Not sure how the lockfile ended up like that, but might be worth it to report to the npm / yarn folks (whatever you're using).
