### ISSUE TITLE
setInterval missing from node/timers/promises.d.ts

### ISSUE THREAD

**Issue by poluxus** [DefinitelyTyped/DefinitelyTyped#52797]
Hi, i'm quite new to typescritp so sorry if this is not the right place.

I'm trying to use `setInterval` from node `timer/promises` but i'm receiving error and i see that this is not in the [definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/timers/promises.d.ts).

Did i do something wrong or should i open a pull request ?

Thanks

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).

  - Authors: @SimonSchick

**Comment by SimonSchick** [comment]
This is in progress https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52775

**Comment by poluxus** [comment]
Thanks a lot.

Out of curiosity, why wasn't there before ?

**Comment by SimonSchick** [comment]
The latter.
