### ISSUE TITLE
[@types/chrome] string enum in declarativeNetRequest exported incorrectly?

### ISSUE THREAD

**Issue by idan315** [DefinitelyTyped/DefinitelyTyped#52844]
Trying to use the declarativeNetRequest API that I've added to chrome, it seems that the keys for the new enums (for example, `console.log(chrome.declarativeNetRequest.RuleActionType` are in all caps, and therefore trying to use the imported typescript definition (i.e `RuleActionType.Block`) returns `undefined`, while `RuleActionType.BLOCK` seems to return the correct string const.

Since this issue did not occur when testing these types locally before adding them to the repo I assume there is something with the import/export process of string enums that I'm missing?

Mentioning the other @types/chrome authors: @matthewkimber, @otiai10, @couven92, @RReverser, @sreimer15, @matcarlson, @ekinsol, @tregagnon, @EchoAbstract, @spasma, @bdbai, @pokutuna, @JasonXian, @usertim

**Comment by matcarlson** [comment]
@idan315 - Could you manually mark this issue as closed when you have a chance? It was fixed in #52973 but not marked as fixed.
