### ISSUE TITLE
[@types/react] type for useCallback breaks --noImplicitAny guarantees

### ISSUE THREAD

**Issue by gyzerok** [DefinitelyTyped/DefinitelyTyped#52873]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Jessidhia 

```ts
// With `--noImplicitAny` set to true I expect the following code to error.
// $ExpectError
useCallback((implicitAnyHere) => '', [])

// And this one to compile
useCallback((good: string) => '', [])
// As well as this one
useCallback<(arg: string) => string>((good) => '', [])
```

Currently type definition for `useCallback` breaks the guarantees that `--noImplicitAny` gives. If developer does not specify a type for a function they are passing, all the arguments will default to `any`, which can easily lead to errors. I would argue that for the end developer/consumer this `any` type is implicit. It was totally unexpected for me and I discovered it by getting a runtime error which I would expect to be caught compile-time.

You can play around with it [here](https://www.typescriptlang.org/play?ssl=5&ssc=1&pln=5&pc=41#code/GYVwdgxgLglg9mABCAzgUwMIEMA2OBGWEA1gDwAqiaAHlGmACYqIAUAdB1gE4DmKAXIixgAngG0AugEpEAXgB8Q0fJYRcBIsUHkANIgZoADgMQAlNFgYIcIgIJcuWEaWEj5U7YgDeAWABQiIGIXGhQIFxIaniEJADc-gC+-v6omOoxxCwsMAC2hjgwEDBQtqIAEmghMgqIAOS1epJSQA).

Changing type definition to the following will fix the issue, however use of `Function` type is discouraged and comes as error when running `npm test react`.
```ts
function useCallback<T extends Function>(callback: T, deps: DependencyList);
```

**Comment by gyzerok** [comment]
Here Jessica comes in git blame, however I will mention couple of other authors just in case: @johnnyreilly @ericanderson @hellatan

**Comment by gyzerok** [comment]
Since none of mention people reacted I am going to mention some others from the list: @vhfmag @disjukr @dimitropoulos @dancerphil @zieka @eps1lon

**Comment by eps1lon** [comment]
We have a comment about this in the types:

`// TODO (TypeScript 3.0): <T extends (...args: never[]) => unknown>`

Note that this wouldn't trigger implicity any but the value becomes "less useable" i.e. `never`. The `Function` usage here is interesting. I'm not sure what the rationale for disallowing is.

However, this would probably cause new type errors in peoples code. Considering we always get a considerable amount of complaints this happens, we'll do it in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46691 instead.

**Comment by gyzerok** [comment]
@eps1lon thanks for your reply!

Yeah, ideally I would expect to get an error at the definition, not usage site. From my perspective this error is going to be easier to understand. Looking at the playground - it won't be as easy to figure out what is error about as it is with `Function`.

Also I am wondering if such a change will cause any "useless" type errors for people. If so - yes, probably not the best idea to change it now, but if no I would at least think about it. Because I believe that in many cases it will highlight actual bugs in the code and that's exactly the reason people are using TypeScript. So from my perspective nothing to complain about, but rather be grateful for those :) What do you think? Can you imagine a case when such error is useless?

**Comment by eps1lon** [comment]
I agree with everything you said. But there are people who think that everything that breaks their existing code is a breaking change and they will tell you often and loudly about it. And I don't want to put up with that so I'd rather move this to React 18 typings.

**Comment by gyzerok** [comment]
Ok, I see. That's sounds unfortunate. One last question though: should this be added to the list inside the linked issue or it is being tracked due to the mentioned comment?

**Comment by eps1lon** [comment]
> Ok, I see. That's sounds unfortunate. One last question though: should this be added to the list inside the linked issue or it is being tracked due to the mentioned comment?

Added it already after you openend the issue. There are a bunch of other TODOs related to TypeScript 3.0 that we want to get in. The types are still written with TS < 3.0 in mind where we didn't have `unknown`.

**Comment by dimitropoulos** [comment]
> I agree with everything you said.

It's not every day you hear that from @eps1lon.  :smile: (I mean that in the kindest possible way to someone that puts in so much time/effort/love into these types)

I also agree, when we move to v18 it should be better.  After all, Dan said (https://twitter.com/dan_abramov/status/1293251763450126336) 9 months ago that they'd like to release within a year so maybe it's not super far away.

**Comment by kiliancs** [comment]
My override, with the advantage that it behaves exactly as one would expect, meaning the error is in the untyped argument, and the error is no-implict-any.

```ts
export type NoConstructor<T extends Function> = T extends new (
    ...args: unknown[]
) => unknown ? never : T;

declare function useCallback<T extends Function>(
    callback: NoConstructor<T>,
    deps: DependencyList,
): T;
```

Code with comments and example usage [in the TypeScript Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAIhkDsAmEEGMQBkCWBnYUAvFAEoQCGSA9ggDYgCCATk+SADzkIgB8A3ACgBaWuVy4oAFQj4AwqPFQA3gF8BAMwCu6YNhpRgM4ADFtaXTQAU+JgC4oN7AgDmASmVqBAegBUPgVA+UACiAB4imigS5FBoNDaa5lRMAHQB-oFQAKq4EFq0UADuABaoRdAIEBBIUDGgkFDqybWNZhYIRdjAxVSaBIVcui4GVI3ktLQARuRoANYj6VAABlwgS1DNS9qzCFSFCEsANFCTfeVQ1AgA5P2DI1CauVBgok7Lpjp6BycQaOSP0C6tVouCoiycESisXiwCYiWAyVwaUCiwAAhBQuQALYvCCLLSffQzNDwYC4BgfcxfdiSKAYwzICSU9o8SyLKAc2LjKYzWb2AByVFkMLhSSYNJ4i1c9gAblRsEhBCjMsTSeTmV9LE1RoQeB5XEqgl4vJzTWbOQA9K2LY1QAAK5FYWIghiYUCu2quUGwONo2DQXXoUGKYlqHSuqy99QgKUsAHYAAwJgBsrnSixEYiZVCFCgkqkWqrAZIpbU1xhz8izBptJvN9agVqbTdrUGYzk0zoQBCo6gM4GgNwHvagFdzWa9eCguwIWewzgQ5EmtGgCOejuxLogbpH0dbV0qMu3V1jACYAMwAFgArGnlUEiyWNVYtTn7I4XO5dfrDV4BNGoEFYUEASMUaTpUIGSQJkyxoPViFpelUGg6cIEKKA2VNFJsMdZxcHsbZdn2ABtABdAQvz1Qi9gQAJOQAflQo8mDojl7EkQQhFtBgfmAV0LjyJwui+RpNgBWRuWmOZ1m6LgDFKDZKkaJgqCxZZUWjXAvCYChzCWbwTQARjjFIExSc9DJSKAAElgCuCRJhdfjHL+AFvQIHTcEgcwJEkAcAGU0CYbBi3s5Zdms31-S6BhuH0211FEZwrK2XIJImKTZlfHU9VUY4yNcdZCmwCY6RYZoXP+J4lm1dYpx9F5ouAegDOWVYljSFBMx01pCQ6cTJN5cCkMZUdYIQVlWK5DLeQFIURXhZIJUOKaUDAfDYHgZDUAwHB8BW6UpE4gQBpmuZLGy99YScNwiD1bV8tImtTp5c7DHwZ8EHy96THGp7BBezLsru0SqEe560sG87pDkPN8ph4Aq3Ef6gA).

<img width="508" alt="Screen Shot 2021-10-29 at 13 14 43" src="https://user-images.githubusercontent.com/98786/139496394-b81b9cf3-4970-4131-811b-cb9e4535b323.png">

**Comment by Jack-Works** [comment]
Hello, I found a problem for this change: it no longer being able to infer type via contextual typing:

Example code:

```tsx
<a onClick={useCallback(event => {})} />
```

In @types/react 17, the type of event can be inferred because it is contextual typing, in @types/react 18 it no longer does.

**Comment by laverdet** [comment]
@gyzerok @eps1lon Sorry for the bikeshedding, but did you explore `extends (...args: unknown[]) => unknown` instead of `extends Function`?

Due to a bug in TypeScript [microsoft/TypeScript#50719] arguments cannot be inferred using the `extends Function` method. This is the issue @Jack-Works mentioned above.

```ts
type WithNumber = (number: number) => void;

const use1 = <Fn extends Function>(fn: Fn) => fn;
const withNumber1: WithNumber = use1((number) => {});
// Error: Parameter 'number' implicitly has an 'any' type. ts(7006)
const maybeWithNumber1: WithNumber | undefined = use1((number) => {});

// ---

const use2 = <Fn extends (...args: unknown[]) => unknown>(fn: Fn) => fn;
const withNumber2: WithNumber = use2((number) => {});
// This is ok
const maybeWithNumber2: WithNumber | undefined = use2((number) => {});
```
