### ISSUE TITLE
ua-parser-js: UAParser no-new usage not covered

### ISSUE THREAD

**Issue by ippeiukai** [DefinitelyTyped/DefinitelyTyped#52899]
UAParser can be used as a function that returns `ReturnType<UAParser[getResult]>`. That usage is not covered by `@types/ua-parser-js`.

```JS
var result = UAParser(uastring1);
```

On the side note, the current declaration is also missing the `new UAParser(extensions)` / `UAParser(extensions)` signature that is present in the original JS library.

see:
- https://github.com/faisalman/ua-parser-js/issues/423
- https://github.com/faisalman/ua-parser-js#constructor
---

- [x] I tried using the `@types/ua-parser-js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @superduper @legendecas @MeLlamoPablo @peterblazejewicz

**Comment by ippeiukai** [comment]
My current workaround:

```TS
import _UAParser from 'ua-parser-js';

type UAParser = _UAParser;
const UAParser = (_UAParser as unknown) as typeof _UAParser & {
  new (uastring: string, extensions?: any): UAParser;
  new (extensions?: any): UAParser;
  new (): UAParser;
  (uastring: string, extensions?: any): ReturnType<UAParser['getResult']>;
  (extensions?: any): ReturnType<UAParser['getResult']>;
  (): ReturnType<UAParser['getResult']>;
};
```

**Comment by BendingBender** [comment]
@ippeiukai Thank you for the hint. You can simplify your workaround a bit:
```ts
import _UAParser from 'ua-parser-js';

type UAParser = _UAParser;
const UAParser = (_UAParser as unknown) as typeof _UAParser & {
  new (uastring: string, extensions?: object): UAParser;
  new (extensions?: object): UAParser;
  (uastring: string, extensions?: object): _UAParser.IResult;
  (extensions?: object): _UAParser.IResult;
};
```
I've made an MR, you workaround should soon be obsolete.
