### ISSUE TITLE
"lodash-es"' has no exported member named 'chain'. Did you mean 'hasIn'?

### ISSUE THREAD

**Issue by VolodymyrKalynii** [DefinitelyTyped/DefinitelyTyped#52919]
`import {chain} from 'lodash-es';`

throws out a type error "lodash-es"' has no exported member named 'chain'. Did you mean 'hasIn'?
But library has this functions

**Comment by adam-drozdz-ie** [comment]
Any news on this issue? I see, that there was a PR to fix this, but it was closed without merging 👎

**Comment by patorjk** [comment]
I'm having the same problem...

**Comment by asingh04** [comment]
I can raise a new PR for this if this is still unresolved.
