### ISSUE TITLE
[@types/react] Invert the returned array of unstable_useTransition to reflect lastest react 

### ISSUE THREAD

**Issue by m-valvano-zakeke** [DefinitelyTyped/DefinitelyTyped#52949]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fdf9d32e35114e4208ba6ed72dc4c91412f54044/types/react/experimental.d.ts#L154

In the lastest experimental versions of React, the returned type of the unstable_useTransition has been inverted to:

[isPending, startTransition].

**Comment by Jack-Works** [comment]
This is not true.

Open this URL

```
data:text/html,<div id=root></div><script src="https://cdn.jsdelivr.net/npm/react@0.0.0-experimental-d75105fa9/umd/react.development.js"></script><script src="https://cdn.jsdelivr.net/npm/react-dom@0.0.0-experimental-d75105fa9/umd/react-dom.development.js"></script>
```

And run the following code:

```js
ReactDOM.createRoot(root).render(React.createElement(function App() {console.log(React.useTransition()); return null}))
```

You will find the order is `(2) [false, ƒ]`

**Comment by m-valvano-zakeke** [comment]
> This is not true.
> 
> Open this URL
> 
> ```
> data:text/html,<div id=root></div><script src="https://cdn.jsdelivr.net/npm/react@0.0.0-experimental-d75105fa9/umd/react.development.js"></script><script src="https://cdn.jsdelivr.net/npm/react-dom@0.0.0-experimental-d75105fa9/umd/react-dom.development.js"></script>
> ```
> 
> And run the following code:
> 
> ```js
> ReactDOM.createRoot(root).render(React.createElement(function App() {console.log(React.useTransition()); return null}))
> ```
> 
> You will find the order is `(2) [false, ƒ]`

?? ? Exacly, in react experimental was changed to bool, function but in the types it was still function, bool.

Than why this commit has been done after my issue?
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/7046ebd9123f4607f5383f057e8f3755314c83de
