### ISSUE TITLE
Problem with xreadgroup BLOCK 

### ISSUE THREAD

**Issue by nassertom** [DefinitelyTyped/DefinitelyTyped#53002]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
-------------------
the xreadgroup BLOCK implementation is not functional it indicates an error beyond 6 parameters (so it's good for xread BLOCK) but not with xreadgroup because there are 8 parameters.

however the javascript file generated by TypeScript works as is.

it's just that the error is confusing and wastes a lot of time the first time around.

I am in version:
ioredis ":" ^ 4.27.2 ",
"@ types / ioredis": "^ 4.26.3",
"typescript": "^ 4.2.4",

it crash on the "tsc" command
"start": "tsc && node dist / app.js",

@plantain-00 @chris-codaio @aliarham11

**Comment by plantain-00** [comment]
You can create a PR to fix this.

**Comment by nassertom** [comment]
I don't understand, you are asking me to fix the problem myself?
I can try.

**Comment by plantain-00** [comment]
yes, see: https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request

**Comment by nassertom** [comment]
done !

**Comment by nassertom** [comment]
sorry now is good : 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53026/commits

**Comment by nassertom** [comment]
it's done now
