### ISSUE TITLE
[@types/node] Error is missing "code" (and other members)

### ISSUE THREAD

**Issue by Paril** [DefinitelyTyped/DefinitelyTyped#53034]
@ExE-Boss @SimonSchick @peterblazejewicz

The `Error` type in Node has quite a few members not in the types. I've had to litter a lot of my error-handling code with `//@ts-expect-error` currently to work around it.

See: https://nodejs.org/api/errors.html#errors_error_code

**Comment by SimonSchick** [comment]
Not all `Error` types in node have codes.
Unfortunately TS does not support checked (or strongly typed) exceptions you should use type assertions to cover these cases.

**Comment by Paril** [comment]
That's fair, but `ErrnoException` isn't exposed in the typings, so there is no type you can even type assert into. That's what I'm getting at.

**Comment by SimonSchick** [comment]
It is though via `NodeJS.ErrnoException`?

**Comment by Paril** [comment]
Oh it's scoped to NodeJS, I see. Fair enough. I missed that when going over things/expected it to be a global.
