### ISSUE TITLE
Type Definition request for angular-file-upload

### ISSUE THREAD

**Issue by sasikumardr** [DefinitelyTyped/DefinitelyTyped#5322]
We already have angular-file-upload d.ts file. But that is actually for an angular module known as [ng-file-upload](https://github.com/danialfarid/ng-file-upload)
There is another popular angular module for file upload that goes by name angular-file-upload (repo url below). 

It would be great if someone finds time for creating definition file for this module.

https://github.com/nervgh/angular-file-upload

**Comment by vvakame** [comment]
NOTE https://github.com/borisyankov/DefinitelyTyped/commit/41537b6d1cbf7dcf89bb121834ec80cb0dceeffe

**Comment by gunpal5** [comment]
I have wrote typedefinition for angular-file-upload, but I don't have push permission for this repository.
