### ISSUE TITLE
Moving DT Issues to Discussions

### ISSUE THREAD

**Issue by orta** [DefinitelyTyped/DefinitelyTyped#53377]
Hi folks, after going through the most recent user feedback for DefinitelyTyped in https://github.com/microsoft/TypeScript/issues/44030 - we came to the conclusion that moving the DefinitelyTyped issues to use the new [GitHub Discussions feature](https://docs.github.com/en/discussions) on this repo. 

Issues have been an OK fit for the problem of 'this DT package has a bug', but increasingly more issues get no response and we'd like to try and re-frame how folks interact on this repo. Here's how we see it working in the future:

- "There's a bug in @types/xyz" -> Discussions
- "I'd like to request a package for xyz" -> Discussions
- "I made changes to a DT package but it didn't end up on @types/xyz" -> Issues
-  "How do we handle Webpack 5 types transition?" -> Issues

Roughly, if the problem is about a single @types/xyz package then it goes into GitHub Discussions where it can be classed as 'answered' by the poster, if the problem is systemic to DefinitelyTyped - then it's in GitHub Issues.

Next Monday (June 7th) is the switch day: 
- We'll have a script to close any Issues which haven't had a comment in > 6 months
- We'll change the docs in the repo and issues templates to start redirecting people to discussions
- We'll start using the bot for DT to try automate some of the notifications and tightening the format for an discussion topic to make it easier to current maintainers to get pinged

**Comment by SimonSchick** [comment]
Is this enforced at all?
Seeing tons of new issues being opened.

**Comment by orta** [comment]
Not enforced, through someone has to go through this page to make a new issue:

![Screen Shot 2021-08-03 at 2 12 20 PM](https://user-images.githubusercontent.com/49038/128021327-6d56384a-15be-4774-8a2a-0e48bb83e0db.png)

I'm hoping to get a review for https://github.com/DefinitelyTyped/dt-mergebot/pull/412 soon so that making a discussion will be a better experience than writing an issue. I don't think I can automate closing issues in a useful way though.

**Comment by zerze1** [comment]
>

**Comment by fregante** [comment]
Has this transition stalled? There are 684 open issues, [some](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/256) untouched in TEN years,  overshadowing the [18 infrastructure issues](https://github.com/DefinitelyTyped/DefinitelyTyped/labels/infrastructure)

**Comment by SimonSchick** [comment]
This seems to have failed, OP is no longer in this team @peterblazejewicz should probably close this.

**Comment by orta** [comment]
I got pretty far with this, but it was a manual effort (you dont know what issues had deleted comments which meant the API said it shouldn't count in the automation script, like that thread  probably) and then redirecting the right ones to disucssions just wasn't worth it on a day to day basis as people made new issues and ignored the change

**Comment by kachkaev** [comment]
Makes sense. Should this issue be unpinned then?

**Comment by SimonSchick** [comment]
For what it is worth, I think the effort wasn't strong handed enough, disabling issues or heavily restricting their creation / requiring escalation would've likely been a more effective measure, but hindsight is 20/20 as usual.

Thanks for taking action on this and all your work ❤️

**Comment by SimonSchick** [comment]
Also we should likely unpin this issue?
