### ISSUE TITLE
React big calendar export wrong

### ISSUE THREAD

**Issue by BillOTei** [DefinitelyTyped/DefinitelyTyped#53437]
- [X] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sbusch @JakeChampion @TomasHubelbauer @altruisticsoftware @catruzz @tomtom5152

an issue related to react big calendar components export https://stackoverflow.com/questions/67719329/react-big-calendar-custom-view-w-typescript/67721360#67721360

> creating a custom view with the typed big calendar, each time I use a calendar component such as Timegrid or any other in my custom Week component as in the example, I get a standard error such as react_devtools_backend.js:2560 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. 

related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48528 too.

**Comment by samarmohan** [comment]
#48545 ?

**Comment by DanielUche** [comment]
The Timegrid component still gives error.

**Comment by robertwt7** [comment]
Yeah I think `DateLocalizer` is not complete as well as defined here:


```
var DateLocalizer = function DateLocalizer(spec) {
  var _this = this;

  !(typeof spec.format === 'function') ? process.env.NODE_ENV !== "production" ? (0, _invariant.default)(false, 'date localizer `format(..)` must be a function') : invariant(false) : void 0;
  !(typeof spec.firstOfWeek === 'function') ? process.env.NODE_ENV !== "production" ? (0, _invariant.default)(false, 'date localizer `firstOfWeek(..)` must be a function') : invariant(false) : void 0;
  this.propType = spec.propType || localePropType;
  this.formats = spec.formats;

  this.format = function () {
    for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    return _format.apply(void 0, [_this, spec.format].concat(args));
  }; // These date arithmetic methods can be overriden by the localizer


  this.startOfWeek = spec.firstOfWeek;
  this.merge = spec.merge || _dates.merge;
  this.inRange = spec.inRange || _dates.inRange;
  this.lt = spec.lt || _dates.lt;
  this.lte = spec.lte || _dates.lte;
  this.gt = spec.gt || _dates.gt;
  this.gte = spec.gte || _dates.gte;
  this.eq = spec.eq || _dates.eq;
  this.neq = spec.neq || _dates.neq;
  this.startOf = spec.startOf || _dates.startOf;
  this.endOf = spec.endOf || _dates.endOf;
  this.add = spec.add || _dates.add;
  this.range = spec.range || _dates.range;
  this.diff = spec.diff || _dates.diff;
  this.ceil = spec.ceil || _dates.ceil;
  this.min = spec.min || _dates.min;
  this.max = spec.max || _dates.max;
  this.minutes = spec.minutes || _dates.minutes;
  this.firstVisibleDay = spec.firstVisibleDay || _dates.firstVisibleDay;
  this.lastVisibleDay = spec.lastVisibleDay || _dates.lastVisibleDay;
  this.visibleDays = spec.visibleDays || _dates.visibleDays;
  this.getSlotDate = spec.getSlotDate || getSlotDate;
  this.getTotalMin = spec.getTotalMin || getTotalMin;
  this.getMinutesFromMidnight = spec.getMinutesFromMidnight || getMinutesFromMidnight;
  this.continuesPrior = spec.continuesPrior || continuesPrior;
  this.continuesAfter = spec.continuesAfter || continuesAfter;
  this.sortEvents = spec.sortEvents || sortEvents;
  this.inEventRange = spec.inEventRange || inEventRange;
  this.isSameDate = spec.isSameDate || isSameDate;
  this.startAndEndAreDateOnly = spec.startAndEndAreDateOnly || startAndEndAreDateOnly;
  this.segmentOffset = spec.browserTZOffset ? spec.browserTZOffset() : 0;
};
```
