### ISSUE TITLE
@types/chart.js. Property 'borderColor' does not exist on type 'string'

### ISSUE THREAD

**Issue by dkirien** [DefinitelyTyped/DefinitelyTyped#53517]
Hi there!
I use Chart.js 2.9.4 and @types/chart.js 2.9.32 with React and TS.
I created a custom function for the tooltip. Tooltip model has ChartTooltipModel type, but labelColors has type string[] when actually it is an array of ChartTooltipLabelColor objects.
Maybe I use the wrong type of declarations?

**Comment by samarmohan** [comment]
I’ll fix this either later today or tomorrow. Thanks!
