### ISSUE TITLE
UseTableOptions needs globalFilter

### ISSUE THREAD

**Issue by jiveyTO** [DefinitelyTyped/DefinitelyTyped#53547]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5e9ab67330c392776ce6cc046e909a7026d5a868/types/react-table/index.d.ts#L179

I think globalFilter needs to be in here as it's being highlighted in my code.

  const tableInst = useTable(
    {
      columns,
      data,
      defaultColumn,
      globalFilter: myFilterFunction
    },
    useGlobalFilter,
    useFilters,
    useSortBy
  )

**Comment by jiveyTO** [comment]
Actually found the solution


create a folder @types and create the file @types/react-table-config.d.ts

in that file put

import { UseGlobalFiltersOptions } from 'react-table'

declare module 'react-table' {
  export interface TableOptions<D extends Record<string, unknown>>
    extends UseGlobalFiltersOptions<D> {}

  export interface TableInstance<D extends Record<string, unknown>>
    extends UseGlobalFiltersInstanceProps<D> {}
}

**Comment by AarRidho** [comment]
Hello fellow upcoming TypeScript users 👋 

Just want to help here, this link refers to how to use React-Table with TypeScript:
[Link Here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table#example-type-file)
