### ISSUE TITLE
Fix Type FTPOptions interface

### ISSUE THREAD

**Issue by AdelysAlberto** [DefinitelyTyped/DefinitelyTyped#53563]
Hi, can you please check the FTPOptions interface, it has a sshKeyPath key but is boolean?
The value sshKeyPath should be type "string" since it is used to take the path of the file system that has a .key file, then this type would be "string"

The actual interface is this. 
interface FTPOptions {    sshKeyPath?: boolean;    }

**Comment by samarmohan** [comment]
Which package is this in?

**Comment by orta** [comment]
Closing due to no response
