### ISSUE TITLE
@types/node version 15.9 breaks application using express.json()

### ISSUE THREAD

**Issue by rongem** [DefinitelyTyped/DefinitelyTyped#53635]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @SimonSchick

After updating @types/node to version 15.9, my typescript nodejs application breaks.

Code: 
import express from 'express';
const app: express.Application = express();
app.use('/login', express.json());

tsc errors:
src/app.ts:28:19 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'NextHandleFunction' is not assignable to parameter of type 'Application'.
      Type 'NextHandleFunction' is missing the following properties from type 'Application': init, defaultConfiguration, engine, set, and 61 more.

28 app.use('/login', express.json());
                     ~~~~~~~~~~~~~~
VS Code also displays this error.

Returning to @types/node version 15.6 fixes the issue for the moment.

**Comment by SimonSchick** [comment]
Please provide a self contained repro case containing:
- package.json (ideally package-lock.json)
- A single ts file that reproduces the error
- A tsconfig.json file

**Comment by rongem** [comment]
[src.zip](https://github.com/DefinitelyTyped/DefinitelyTyped/files/6602913/src.zip)

Here is the zip file with all your wishes. Running tsc succeeds.
Now run:
npm install @types/node@latest
tsc

App breaks.

**Comment by SimonSchick** [comment]
Try running `npm update` and/or `npm dedupe`, I believe your install is corrupted in some way due npm not deduplicating dependencies correctly after update (this has been a very long standing issue).

**Comment by rongem** [comment]
The code I've sent to you was tested with a fresh install. It happens to all my node projects, no matter if I create them newly or work on old ones.

**Comment by rongem** [comment]
Just seen that there is a new version of types/node:
+-- @types/node@15.12.1
But this doesn't change anything, neither does npm update nor npm dedup.

Deleting package-lock.json and folder npm_modules does the trick. Now my projects work again.
