### ISSUE TITLE
[@types/aws-lambda] version 8.10.77 introduces breaking change 

### ISSUE THREAD

**Issue by melissapalmer** [DefinitelyTyped/DefinitelyTyped#53663]
PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53581 seems to have caused a breaking change. 

Code using previous version that created a `const event: APIGatewayProxyWithCognitoAuthorizerEvent` with an identity now won't compile with version 8.10.77 as identity.clientCert is mandatory   (ie: if "@types/aws-lambda": "^8.10.72" had been used in package.json)

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/aws-lambda` package version 8.10.77 and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tulsidas @simonbuchan 

If you do not mention the authors the issue will be ignored.

**Comment by tulsidas** [comment]
The code I introduced defines clientCert as:

`clientCert: APIGatewayEventClientCertificate | null;`

Hence it's not mandatory.

I'm not clear if it's failing in your own test cases or if it is failing with actual events from AWS

**Comment by melissapalmer** [comment]
It is failing when building a project that previously used a lower version. 

ie: something like below will not compile now
```
const event: APIGatewayProxyWithCognitoAuthorizerEvent = {
         ...
            identity: {
              sourceIp: '127.0.0.1',
              userAgent: request.headers['user-agent'] ?? 'User-Agent Header Missing',
              accessKey: null,
              accountId: null,
              apiKey: null,
              apiKeyId: null,
              caller: null,
              cognitoAuthenticationProvider: null,
              cognitoAuthenticationType: null,
              cognitoIdentityId: null,
              cognitoIdentityPoolId: null,
              principalOrgId: null,
              user: null,
              userArn: null
            },
            ...
          },
          ...
        }
```

**Comment by tulsidas** [comment]
If you add `clientCert: null` to the identity object that should fix the issue.

If the issue is that you **don't** want to change your existing code then I'll defer to @simonbuchan as to what is the appropriate way forward (i.e. mantaining backward compatibility vs being strict to the actual data sent by AWS)

**Comment by melissapalmer** [comment]
The issue is that I **cannot** change the existing code, as it is within a dependency that is not mine.

**Comment by simonbuchan** [comment]
While this is really a community project, so (in my opinion) my opinion is just my opinion - I've generally held that breaking tests that generate AWS input is perfectly OK. You, as a test writer, have plenty of options for ensuring that code like the above works (I quite like using a Proxy that throws on undeclared property usage, ensuring you're only using expected properties), and in fact breaking it is potentially good, as it ensures that you are passing what AWS would.

In this sort of case I really don't know what advice I can give... take it up with the dependency, I guess? You can generally hack around the issue by using things like the following, though:

```ts
// use declaration merging to work around https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53663
declare module "aws-lambda/common/api-gateway" {
  export interface APIGatewayEventIdentity {
    clientCert?: APIGatewayEventClientCertificate | null;
  }
}
```

**Comment by melissapalmer** [comment]
Thanks @simonbuchan and @tulsidas thanks for the quick responses and information.
