### ISSUE TITLE
[@types/react-table] "TS2428: All declarations of ... must have identical type parameters." error with `skipLibCheck: false`

### ISSUE THREAD

**Issue by martinfrancois** [DefinitelyTyped/DefinitelyTyped#53702]
- [x] I tried using the `@types/react-table` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ggascoigne @stramel @gargroh @riceboyler

If I add a file `src/types/react-table-config.d.ts` with the same content as the [example type file](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table#example-type-file), with `skipLibCheck: false` in `tsconfig.json`, I get the following TypeScript errors:
```
node_modules/@types/react-table/index.d.ts:45:18 - error TS2428: All declarations of 'TableOptions' must have identical type parameters.
45 export interface TableOptions<D extends object> extends UseTableOptions<D> {}

node_modules/@types/react-table/index.d.ts:47:18 - error TS2428: All declarations of 'TableInstance' must have identical type parameters.
47 export interface TableInstance<D extends object = {}>

node_modules/@types/react-table/index.d.ts:51:18 - error TS2428: All declarations of 'TableState' must have identical type parameters.
51 export interface TableState<D extends object = {}> {

node_modules/@types/react-table/index.d.ts:55:18 - error TS2428: All declarations of 'Hooks' must have identical type parameters.
55 export interface Hooks<D extends object = {}> extends UseTableHooks<D> {}

node_modules/@types/react-table/index.d.ts:57:18 - error TS2428: All declarations of 'Cell' must have identical type parameters.
57 export interface Cell<D extends object = {}, V = any> extends UseTableCellProps<D, V> {}

node_modules/@types/react-table/index.d.ts:59:18 - error TS2428: All declarations of 'ColumnInterface' must have identical type parameters.
59 export interface ColumnInterface<D extends object = {}> extends UseTableColumnOptions<D> {}

node_modules/@types/react-table/index.d.ts:107:18 - error TS2428: All declarations of 'ColumnInstance' must have identical type parameters.
107 export interface ColumnInstance<D extends object = {}>

node_modules/@types/react-table/index.d.ts:114:18 - error TS2428: All declarations of 'Row' must have identical type parameters.
114 export interface Row<D extends object = {}> extends UseTableRowProps<D> {}
```
The same errors are also repeated inside of my `src/types/react-table-config.d.ts` file.

If I set `skipLibCheck: true` in `tsconfig.json`, the errors disappear.

I'm using the following `tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es5",
    "outDir": "build/main",
    "rootDir": "src",
    "moduleResolution": "node",
    "module": "commonjs",
    "declaration": true,
    "inlineSourceMap": true,
    "esModuleInterop": true,
    "skipLibCheck": false,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "traceResolution": false,
    "listEmittedFiles": false,
    "listFiles": false,
    "pretty": true,
    "jsx": "preserve",
    "lib": ["dom", "dom.iterable", "esnext"],
    "types": ["node", "jest"],
    "typeRoots": ["node_modules/@types", "src/types"],
    "baseUrl": "."
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules/**"],
  "compileOnSave": false
}
```

**Comment by ggascoigne** [comment]
This is definitely a bug.  The example was upgraded based on changes to the default eslint rules (IIRC), and the rest of the code wasn't.  As you can probably tell, I don't use `skipLibCheck: false` in my code.

I'll work on a fix.

**Comment by ggascoigne** [comment]
Ooof, well the naïve approach that I thought would be simple, isn't, and with `skipLibCheck: false`, react-table is the very least of my problems since I can't even get past the errors caused between:

node_modules/typescript/lib/lib.dom.d.ts and, node_modules/typescript/lib/lib.webworker.d.ts, as well as node_modules/@types/jest/index.d.ts and node_modules/@types/mocha/index.d.ts.

I can see why that flag exists and is used in the first place.

Not saying that I won't fix this, but I think that it'll take a bit more time than I'd been thinking.
