### ISSUE TITLE
Atom definitions outdated

### ISSUE THREAD

**Issue by steelbrain** [DefinitelyTyped/DefinitelyTyped#5372]
The config API, the notifications API, the event-kit API and a lot of others are missing from this repo.
https://atom.io/docs/api/latest/ <-- source for latest docs
/cc @basarat

**Comment by basarat** [comment]
Feel free to PR anyone :rose:

**Comment by enlight** [comment]
I'm working on some [here](https://github.com/enlight/atom-typings).

**Comment by smhxx** [comment]
FWIW, the outdated defs were replaced in #20146 and are now being actively maintained, so this issue can be marked as resolved.

**Comment by steelbrain** [comment]
Thanks @smhxx
