### ISSUE TITLE
Migrate to ESLint?

### ISSUE THREAD

**Issue by samarmohan** [DefinitelyTyped/DefinitelyTyped#53965]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/53964

<div type='discussions-op-text'>

<sup>Originally posted by **samarmohan** June 21, 2021</sup>
We use TSLint right now but it is deprecated, ESLint is the recommended option.</div>
This may be hard to do since there are thousands of packages.

**Comment by ChristianMurphy** [comment]
assuming you are referring to dtslint, there is an open issue for this at the dtslint repo https://github.com/microsoft/dtslint/issues/300

**Comment by orta** [comment]
Yeah, that issue is where this is being discussed 👍🏻
