### ISSUE TITLE
Create definition for Falcor

### ISSUE THREAD

**Issue by matijagrcic** [DefinitelyTyped/DefinitelyTyped#5412]
Create definition for [Falcor](http://netflix.github.io/falcor/doc/DataSource.html) API.  

Ref: Provide official TypesScipt definitions for api: Netflix/falcor#424

**Comment by gbouteiller** [comment]
+1

**Comment by timkindberg** [comment]
Any progress or even semi-finished work I could import into my project?

**Comment by mmiszy** [comment]
Any news on this one?

**Comment by ChanceM** [comment]
Should #8882 have closed this?
