### ISSUE TITLE
Unnecessary `children` prop declared in react-scroll-sync type defs

### ISSUE THREAD

**Issue by morellodev** [DefinitelyTyped/DefinitelyTyped#54171]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54170

<div type='discussions-op-text'>

<sup>Originally posted by **morellodev** June 30, 2021</sup>
The type definitions for `@types/react-scroll-sync` specify the `children` prop to both `ScrollSyncProps` and `ScrollSyncPaneProps` interfaces, which is unnecessary because the exported component types are of type `React.FC<P>` which automatically augment `P` with the `children` prop.</div>

**Comment by orta** [comment]
Fixed in #54173
