### ISSUE TITLE
@types/node: is @types/node@16 being developed?

### ISSUE THREAD

**Issue by jjangga0214** [DefinitelyTyped/DefinitelyTyped#54226]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54225 as well, originally.

<div type='discussions-op-text'>

<sup>Originally posted by **jjangga0214** July  2, 2021</sup>
It seems no one created a PR, yet, though there are several changes in node v16([changelog](https://nodejs.org/blog/release/v16.0.0/), [community blog](https://medium.com/the-node-js-collection/node-js-16-available-now-7f5099a97e70)).

Is there who wants to collaborate?

Thanks.</div>

**Comment by orta** [comment]
Closing because discussions is the right place for this conversation 👍🏻

**Comment by karlhorky** [comment]
Yep, and it was released:

- https://www.npmjs.com/package/@types/node
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53669
