### ISSUE TITLE
Run prettier on all packages

### ISSUE THREAD

**Issue by sandersn** [DefinitelyTyped/DefinitelyTyped#54239]
We tried this a couple of years ago, but ran into two problems:

1. DT didn't have a defined support window then, supporting TS 2.0 - 3.1, but prettier emitted TS 2.2 syntax.
2. Formatting the whole repository and issuing a PR for overloaded tools at nearly every step of the way.

We did write support for `#no-publishing-comment` into the publisher, so that a PR with that comment in its first commit causes the bot *not* to post one "I published X" message for each package.

Today, I think there's a better chance that DT's 2-year support window matches prettier's. And without strict prettier requirements, we can format small chunks at a time.

**Comment by peterblazejewicz** [comment]
Some folks are using different settings per-usus (as DT does not allow composing prettier configurations per DT package). This could make some folks non happy (there are couple of packages using tabs as per explicit owners consent). Except of this, would be great

**Comment by Methuselah96** [comment]
> 
> 
> Some folks are using different settings per-usus (as DT does not allow composing prettier configurations per DT package). This could make some folks non happy (there are couple of packages using tabs as per explicit owners consent). Except of this, would be great

Maybe DT packages could override the prettierrc in their specific directory if they want to?

I'm fully in favor of this change and hope we can do this.

**Comment by orta** [comment]
> Why does DT not allow composing prettier configurations per DT package?

Mainly that we don't really want lots of small areas inside DT that act differently - the tooling over DT is complicated enough

**Comment by jakebailey** [comment]
The repo was formatted with dprint last year.
