### ISSUE TITLE
[@types/node] Node v16 timers.d.ts (setTimeout, setImmediate etc.) no longer works for certain callbacks (e.g. Promise callbacks without a specified type)

### ISSUE THREAD

**Issue by birtles** [DefinitelyTyped/DefinitelyTyped#54285]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54258

<div type='discussions-op-text'>

<sup>Originally posted by **birtles** July  3, 2021</sup>
I just updated to @types/node 16.0.0 and I get errors from code that used to work like:

```ts
setImmediate(res);
// ^Expected 2 arguments, but got 1.ts(2554)
// timers.d.ts(54, 88): Arguments for the rest parameter 'args' were not provided.
```

It looks like 15.12.5 defined `setImmediate` like this:

```ts
declare function setImmediate(callback: (...args: any[]) => void, ...args: any[]): NodeJS.Immediate;
```

but 16.0.0 defines it like this:

```ts
function setImmediate<TArgs extends any[]>(callback: (...args: TArgs) => void, ...args: TArgs): NodeJS.Immediate;
```

Note that `TArgs` does not have any default value so it is resolved to `unknown` in the code sample above.

I can work around using:

```ts
setImmediate<any[]>(res);
```

but that seems a bit clumsy.

TypeScript version: 4.3.5</div>

**Comment by Kennypt** [comment]
I have the same issue, thanks for the fix

**Comment by apupier** [comment]
using 16.4.0, i'm still encountering this error:

```
src/extension.ts:109:31 - error TS2554: Expected 3 arguments, but got 2.

109      await new Promise(res => setTimeout(res, WAIT_STEP));
```

despite the modification on setTimeout

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54286/files#diff-e838d0ace9cd5f6516bacfbd3ad00d02cd37bd60f9993ce6223f52d889a1fdbaR45

Any ideas why? Still aproblem in DefintelyTyped?

**Comment by daniele-orlando** [comment]
I'm on @types/node **16.4.0** and I temporarily "fixed" it overloading the function with

```ts
function setTimeout<TArgs extends any[]>(callback: (...args: TArgs) => void, ms?: number): NodeJS.Timeout;
```

**Comment by birtles** [comment]
I thought @SimonSchick was going to fix this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54286#discussion_r664044979

**Comment by KapitanOczywisty** [comment]
@apupier @daniele-orlando Should be now fixed with `16.4.1`

**Comment by daniele-orlando** [comment]
Awesome. I recompiled and I confirm that `setTimeout` works as expected in `16.4.1`. Thank you very much!

**Comment by apupier** [comment]
I confirm too https://github.com/jboss-fuse/vscode-atlasmap/pull/647#pullrequestreview-713438920

Thank you very much @KapitanOczywisty !
