### ISSUE TITLE
@types/rethinkdb missing / incorrect definitions

### ISSUE THREAD

**Issue by BronislavKlucka** [DefinitelyTyped/DefinitelyTyped#54328]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54327

<div type='discussions-op-text'>

<sup>Originally posted by **BronislavKlucka** July  7, 2021</sup>
Hello, based on 
https://rethinkdb.com/api/javascript/insert

there are ``warnings`` and ``changes`` missing on ``WriteResult`` interface

maybe 
```
    type WriteChanges = {new_val: unknown, old_val: unknown}

    interface WriteResult {
        inserted: number;
        replaced: number;
        unchanged: number;
        errors: number;
        deleted: number;
        skipped: number;
        first_error: Error;
        generated_keys: string[]; // only for insert

        warnings: string;
        changes: Array<WriteChanges>
    }
```

**Comment by BronislavKlucka** [comment]
https://rethinkdb.com/api/javascript/get
table.get() parameter may by of both number|string (example in official documentation)

**Comment by orta** [comment]
Closing because this issue already has a discussion topic and DT issues are for infrastructure features/bugs/ideas
