### ISSUE TITLE
@types/node v14 should allow async iterables in stream.pipeline

### ISSUE THREAD

**Issue by paya-cz** [DefinitelyTyped/DefinitelyTyped#54604]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54574

<div type='discussions-op-text'>

<sup>Originally posted by **paya-cz** July 16, 2021</sup>
Per node doc, nodejs v14 supports async generators in `stream.pipeline`:
https://nodejs.org/docs/latest-v14.x/api/stream.html#stream_stream_pipeline_source_transforms_destination_callback

However, `@types/node` does not allow such usage (@types/node v14.17.5).
If I use @types/node v16.3.2, async generators are allowed.

Seems to me like the async generator support should be back-ported.</div>

**Comment by orta** [comment]
Closing because this issue already has a discussion topic and DT issues are for infrastructure features/bugs/ideas
