### ISSUE TITLE
@types/tar-stream Extract.on('entry') "next" callback should have an error parameter

### ISSUE THREAD

**Issue by paya-cz** [DefinitelyTyped/DefinitelyTyped#54621]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54174

Current type definition is:

```
export interface Extract extends stream.Writable {
    on(event: 'entry', listener: (headers: Headers, stream: stream.PassThrough, next: () => void) => void): this;
}
```

However, the `next` callback should accept an error parameter:
https://github.com/mafintosh/tar-stream/blob/e08fcd845744c43e1e71343f117be9993208103a/extract.js#L180
https://github.com/mafintosh/tar-stream/blob/e08fcd845744c43e1e71343f117be9993208103a/extract.js#L70

Thus, the correct type definition should be:

```
export interface Extract extends stream.Writable {
    on(event: 'entry', listener: (headers: Headers, stream: stream.PassThrough, next: (err?: any | null) => void) => void): this;
}
```

**Comment by orta** [comment]
Closing because this issue already has a discussion topic and DT issues are for infrastructure features/bugs/ideas
