### ISSUE TITLE
jquery.validation - add optional() and getLength() declarations

### ISSUE THREAD

**Issue by kamil-zacek** [DefinitelyTyped/DefinitelyTyped#54656]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54655

<div type='discussions-op-text'>

<sup>Originally posted by **kamil-zacek** July 21, 2021</sup>
Because of these two methods are widely used during write own validation rules like

$.validator.addMethod("rule", (value:string, element: HTMLElement, parameter) =>  $.validator.optional(element) || $.validator.getLength(value.replace(/\s+/g, " ").trim(), element),
$.validator.format("Write at least {0} characters."));

I need to add these two methods to index.d.ts file - into the interface ValidatorStatic {} (it is same as format() method already in this interface).

</div>

**Comment by kamil-zacek** [comment]
Diff is:

 types/jquery.validation/index.d.ts | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/types/jquery.validation/index.d.ts b/types/jquery.validation/index.d.ts
index 1506adf2c9..e0b1aa389a 100644
--- a/types/jquery.validation/index.d.ts
+++ b/types/jquery.validation/index.d.ts
@@ -228,6 +228,9 @@ declare namespace JQueryValidation {
          */
         setDefaults(defaults: ValidationOptions): void;
 
+        optional(element: HTMLElement): boolean;
+        getLength(value: string, element: HTMLElement): number;
+
         messages: { [index: string]: string };
         methods: { [index: string]: Function };
     }

But I don't have rights for create pull request :(

**Comment by orta** [comment]
Sounds good, you're welcome to make a fork and ship your changes. That said, I'm closing because this issue already has a discussion topic and DT issues are for infrastructure features/bugs/ideas
