### ISSUE TITLE
ioredis: xautoClaim is missing

### ISSUE THREAD

**Issue by prem15588** [DefinitelyTyped/DefinitelyTyped#54658]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54637

<div type='discussions-op-text'>

<sup>Originally posted by **prem15588** July 20, 2021</sup>
xautoclaim command is missing.

reference: https://redis.io/commands/xautoclaim</div>

**Comment by orta** [comment]
Closing because this issue already has a discussion topic and DT issues are for infrastructure features/bugs/ideas
