### ISSUE TITLE
Codeowners in 404

### ISSUE THREAD

**Issue by KapitanOczywisty** [DefinitelyTyped/DefinitelyTyped#54679]
There are some `codeowners` whose accounts no longer exists. Should we remove all of them?

I have script running at the moment to check which accounts were removed, and there is quite a few already.

Edit: I found around 200 not existing accounts,  some of them might be typo though. Let me know what do you think, before I'll move this further.

**Comment by orta** [comment]
The codeowners is auto-generated, so it'd need to take those 404s and remove them from the DT module comments - but ping me in the PR and I'll help get it merged if you take a look at it

**Comment by KapitanOczywisty** [comment]
I've meant of course removing from headers. In case - who should be assigned if removed user is the only owner?

**Comment by orta** [comment]
I'm not sure if the bot accepts _noone_ but that is probably the right answer. Failing that, set it to @typescript-bot - hah!

**Comment by KapitanOczywisty** [comment]
I see some users changed names, new one could be seen in commit history, I'll fix username if they commited to that file recently, the old contributors I'm removing.

**Comment by KapitanOczywisty** [comment]
@orta This is 25% of codeowners checked and updated, most of them are just wrong names. Let me know if you have any feedback.
https://github.com/KapitanOczywisty/DefinitelyTyped/commit/de6e43a55486d3a74dd43406c69f0fddf70aba77

**Comment by orta** [comment]
Looks good overall to me, I don't know how the CI will handle `// Definitions by:` but we can figure that out when there's a PR 👍🏻

**Comment by KapitanOczywisty** [comment]
@orta I think `Definitions by` should be renamed to `Notifications to:` or somethings like that, some people are adding even 3rd parties to the header like here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17187/files#diff-2b9842aac4869dade1082b0bc8affa65f6428c53c16dd740c931bd98e89d5e1eR4 vs https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17187/files#diff-8acf10f657b2db1aa8a3668c8a6bce3abf191868e430ddf6a742d55431e0b4e7R3

**Comment by orta** [comment]
We call them "DT module owners" so "owned by" is an ok swap, but not really worth it IMO

**Comment by KapitanOczywisty** [comment]
And all done: https://github.com/KapitanOczywisty/DefinitelyTyped/commit/9d4536e854bb94115bfba4502c85226e34d4108c I'll run some sanity checks tomorrow and make PR

**Comment by KapitanOczywisty** [comment]
I'll add `nobody <https://github.com/DefinitelyTyped>` for unowned packages as in #54393

**Comment by peterblazejewicz** [comment]
what's wrong with non-reachable code owner? Is this is an attribution for a piece of work or just contact address? if the handle is dead (for whatever reason), it can be remooved from generated derivative (code owners file)
Can this be marked (via custom script prune) as 'skip' for code owners generator code?

**Comment by KapitanOczywisty** [comment]
> what's wrong with non-reachable code owner?

They are useless and somebody can probably use new account to quickly merge and publish bad code in non-critical packages.

> if the handle is dead (for whatever reason), it can be remooved from generated derivative (code owners file)

As I mentioned in PR I'd keep map of `username - id` (and maybe `created at`) and use that to remove/update headers.

**Comment by peterblazejewicz** [comment]
So if the handle is defunct, add a special char (or a special term), and let new owner to reclaim it via PR change. Very simple process. I understand GitHub allows to reuse relinquished accounts. But also, there is no 100% the username is not visible at the moment for other reasons (undisclosed to GitHub).

**Comment by KapitanOczywisty** [comment]
> So if the handle is defunct, add a special char (or a special term), and let new owner to reclaim it via PR change.

This never happens, better to remove it entirely.

> But also, there is no 100% the username is not visible at the moment for other reasons (undisclosed to GitHub).

I'm not sure what you mean here. Usernames with bigger projects are reserved after account deletion, other ones are free to reuse.

**Comment by peterblazejewicz** [comment]
Why we would like to to remove people work attribution?

**Comment by KapitanOczywisty** [comment]
Because It's not a work attribution? https://github.com/DefinitelyTyped/DefinitelyTyped#definition-owners

**Comment by peterblazejewicz** [comment]
I'd say, by a very definition from this link: `people who want to maintain the quality of a particular module's types` et cetera, like a piece from a textbook.
If we have doubts, do not make changes, just prevent sending 404 requests (which is a problem to solve) and mark some handles as 'skip'
