### ISSUE TITLE
Interface 'ErrnoException' incorrectly extends interface 'Error' with exactOptionalPropertyTypes enabled

### ISSUE THREAD

**Issue by techmunk** [DefinitelyTyped/DefinitelyTyped#54725]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54673

<div type='discussions-op-text'>

<sup>Originally posted by **techmunk** July 22, 2021</sup>
Ts 4.4@next, building with `exactOptionalPropertyTypes` causes this error:

```
node_modules/@types/node/globals.d.ts:172:15 - error TS2430: Interface 'ErrnoException' incorrectly extends interface 'Error'.
  Types of property 'stack' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.

172     interface ErrnoException extends Error {
                  ~~~~~~~~~~~~~~


Found 1 error.
```

Changing stack property to match declaration in typescripts `lib.es5.d.ts` resolves this issue.

I believe this was added in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54342 in preparation for the next typescript release.

This is the only issue I've noticed building with exactOptionalPropertyTypes enabled so far. Though my current test case is very limited. </div>

**Comment by orta** [comment]
Closing because this issue already has a discussion topic and DT issues are for infrastructure features/bugs/ideas
