### ISSUE TITLE
word spell error

### ISSUE THREAD

**Issue by cizkey** [DefinitelyTyped/DefinitelyTyped#54843]
i find a word spell error

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/common/lang.d.ts

Line: 951,  @retrun 

```
    interface LoDashStatic {
        /**
         * Checks if value is a native function.
         * @param value The value to check.
         *
         * @retrun Returns true if value is a native function, else false.
         */
        isNative(value: any): value is (...args: any[]) => any;
    }
```

**Comment by orta** [comment]
Closing because this issue already is about a change to a DT module, and DT issues are for infrastructure features/bugs/ideas
