### ISSUE TITLE
Webpack plugins error with @types/webpack@^5

### ISSUE THREAD

**Issue by wallzero** [DefinitelyTyped/DefinitelyTyped#54856]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54855

<div type='discussions-op-text'>

<sup>Originally posted by **wallzero** July 30, 2021</sup>
Several Webpack plugin types cause errors when using `@types/webpack@^5`.

- @types/case-sensitive-paths-webpack-plugin
- @types/circular-dependency-plugin
- @types/compression-webpack-plugin
- @types/duplicate-package-checker-webpack-plugin
- @types/html-webpack-plugin
- @types/webpack-node-externals
- @types/webpack-subresource-integrity

Is it possible to instead use a peer dependency such as `"@types/webpack": "^4 || ^5`?</div>

**Comment by wallzero** [comment]
Looks like `@types/webpack-hot-middleware` is another one.

Also, `webpack@^5.0.0` provides its own types. You can see `@types/webpack-dev-middleware` has dropped the `@types/webpack` dependency altogether.

**Comment by orta** [comment]
Closing because this issue already has a discussion topic and DT issues are for infrastructure features/bugs/ideas.
