### ISSUE TITLE
@ckeditor/ckeditor5-mention

### ISSUE THREAD

**Issue by popuguytheparrot** [DefinitelyTyped/DefinitelyTyped#54959]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54958

<div type='discussions-op-text'>

<sup>Originally posted by **popuguytheparrot** August  5, 2021</sup>
Hello. Noticed that there is no type package for this plugin.</div>

**Comment by orta** [comment]
Closing because this issue already has a discussion topic and DT issues are for infrastructure features/bugs/ideas
