### ISSUE TITLE
Could you help remove the vulnerability introduced by package highlight.js?

### ISSUE THREAD

**Issue by evansrobert** [DefinitelyTyped/DefinitelyTyped#55072]
Hi, @peterblazejewicz @sandersn, 
### Issue Description
When I build my project, I notice that a vulnerability [**SNYK-JS-HIGHLIGHTJS-1048676**](https://snyk.io/vuln/SNYK-JS-HIGHLIGHTJS-1048676) detected in package **highlight.js(>=9.0.0 <10.4.1)** is directly referenced by **_@types/markdown-it@10.0.3_**.
   However,  **@types/markdown-it@10.0.3** is so popular that a large number of latest versions of active and popular downstream projects depend on it ([8,988 downloads per week](https://www.npmjs.com/package/@types/markdown-it/v/10.0.3?activeTab=versions) and about **36 downstream projects**, e.g., @factor/core 1.8.30, @electron/docs-parser 0.12.1, @vuepress/cli 2.0.0-alpha.8, @vuepress/plugin-git 2.0.0-alpha.1, cloud-ui.vusion 0.11.48, etc.). 
In this case, the vulnerability [**SNYK-JS-HIGHLIGHTJS-1048676**](https://snyk.io/vuln/SNYK-JS-HIGHLIGHTJS-1048676) can be propagated into these downstream projects and expose security threats to them.
   As you can see, **_@types/markdown-it@10.0.3_** is introduced into the above projects via the following package dependency paths:
(1)`cloud-ui.vusion@0.11.48 ➔ vusion-api@0.6.30 ➔ @types/markdown-it@10.0.3 ➔ highlight.js@9.18.5`
    **......**

I know that it's kind of you to have removed the vulnerability since **_@types/markdown-it@12.0.0_**. But, in fact, the above large amount of downstream projects cannot easily upgrade **@types/markdown-it** from version **_10.0.3_** to _**(>=12.0.0)**_:
    The projects such as **vusion-api**, which introduced **@types/markdown-it@10.0.3**, are not maintained anymore. These unmaintained packages can neither upgrade **@types/markdown-it** nor be easily migrated by the large amount of affected downstream projects.  

   **Given the large number of downstream users, is it possible to release a new patched version with the updated dependency to remove the vulnerability from package @types/markdown-it@10.0.3?**

### Suggested Solution

Since these inactive projects set a version constaint **10.0.\*** for **@types/markdown-it** on the above vulnerable dependency paths, if **@types/markdown-it** removes the vulnerability from **10.0.3** and releases a new patched version **_@types/markdown-it@10.0.4_**, such a vulnerability patch can be automatically propagated into the downstream projects.

In **_@types/markdown-it@10.0.4_**, maybe you can try to perform the following upgrade:
`highlight.js ^9.7.0 ➔ ^10.4.1`;  
**Note:**
**_highlight.js@10.4.1(>=10.4.1)_** has fixed the vulnerability [**SNYK-JS-HIGHLIGHTJS-1048676**](https://snyk.io/vuln/SNYK-JS-HIGHLIGHTJS-1048676).
Of course, you are welcome to share other ways to resolve the issue.

**Comment by orta** [comment]
You're welcome to look at back porting a release for markdown-it 10 by using the [subfolder](https://github.com/DefinitelyTyped/DefinitelyTyped#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package) structure, but given how this is easily fixed at package manager level using something like [yarn/pnpm resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) I think it's unlikely someone will make an older release for you.

**Comment by peterblazejewicz** [comment]
I'll update just `markdown-it` on DT, it looks a little dated, this will solve this properly (aligning with native package deps)
TBD

**Comment by evansrobert** [comment]
@peterblazejewicz, Thank you very much for your understanding and help.

**Comment by peterblazejewicz** [comment]
done here #55116

**Comment by evansrobert** [comment]
Thanks!
