### ISSUE TITLE
[@types/bootstrap-select] BootstrapVersion property is not available

### ISSUE THREAD

**Issue by dehy** [DefinitelyTyped/DefinitelyTyped#55074]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55073

<div type='discussions-op-text'>

<sup>Originally posted by **dehy** August 11, 2021</sup>
Hello there 👋 (oh, hello Github Discussions)

I'm using a special version of Bootstrap v4 that makes the bootstrap-select's BootstrapVersion auto-discovery non available. [Official Docs](https://developer.snapappointments.com/bootstrap-select/options/) says that we can manually override the version used by setting `$.fn.selectpicker.Constructor.BootstrapVersion`.

Unfortunately, tsc complains about `Constructor`:

My line:
```javascript
$.fn.selectpicker.Constructor.BootstrapVersion = '4';
```

The error:
```
[tsl] ERROR in /path/to/app/assets/js/app.ts(20,19)
      TS2339: Property 'Constructor' does not exist on type '{ (opts?: BootstrapSelectOptions | undefined):JQuery<HTMLElement>; (method: MethodType, ...args: (string | string[])[]): JQuery<...>; }'.
```

I'm not expert enough to understand what to update in the definition file.

Versions:
- tsc: 3.9.5
- webpack: 4.43.0

Ping Authors: @LKay @AlexTruba 

Thank you for your work!</div>

**Comment by orta** [comment]
Closing because this issue already has a discussion topic and DT issues are for infrastructure features/bugs/ideas
