### ISSUE TITLE
[@types/ws] Argument of type 'Duplex' is not assignable to parameter of type 'Socket'

### ISSUE THREAD

**Issue by strmer15** [DefinitelyTyped/DefinitelyTyped#55096]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55095

<div type='discussions-op-text'>

<sup>Originally posted by **strmer15** August 11, 2021</sup>
I just upgraded to the latest `@types/node` and now I'm getting this error:

```
src/index.ts:106:32 - error TS2345: Argument of type 'Duplex' is not assignable to parameter of type 'Socket'.
  Type 'Duplex' is missing the following properties from type 'Socket': connect, setTimeout, setNoDelay, setKeepAlive, and 9 more.

106     wss.handleUpgrade(request, socket, head, function (ws) {
                                   ~~~~~~
```

See https://github.com/websockets/ws/issues/1926 as well for another developer with the same issue who opened a bug with the `ws` package, but since they don't maintain their own type definitions, I'm opening the same bug report here.</div>

**Comment by orta** [comment]
Closing because this issue already has a discussion topic and DT issues are for infrastructure features/bugs/ideas

**Comment by elucidsoft** [comment]
So your just closing this because reasons even though its an actual issue?
