### ISSUE TITLE
Definition Request: Universal Windows Platform API (UWP)

### ISSUE THREAD

**Issue by Justin-Credible** [DefinitelyTyped/DefinitelyTyped#5517]
Add definitions for the [Universal Windows Platform API](https://msdn.microsoft.com/en-us/library/windows/apps/BR211377.aspx). Also known as UWP.

Note that this is different from WinJS; this is for all of the types located on the `windows.*` namespace when running on the Windows Runtime.

**Comment by Odonno** [comment]
I need too !

**Comment by lefb766** [comment]
I can see this have resolved. [winrt/winrt-uwp.d.ts](../tree/master/winrt/winrt-uwp.d.ts)

**Comment by BProg** [comment]
IS this still alive? I cannot find it anywhere on github
