### ISSUE TITLE
Missing 'chain' from 'lodash-es'

### ISSUE THREAD

**Issue by 0x0a0d** [DefinitelyTyped/DefinitelyTyped#55267]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@types/lodash-es@4.17.4` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@types/lodash-es/index.d.ts b/node_modules/@types/lodash-es/index.d.ts
index 95cf505..8297450 100644
--- a/node_modules/@types/lodash-es/index.d.ts
+++ b/node_modules/@types/lodash-es/index.d.ts
@@ -21,6 +21,7 @@ export { default as camelCase } from "./camelCase";
 export { default as capitalize } from "./capitalize";
 export { default as castArray } from "./castArray";
 export { default as ceil } from "./ceil";
+export { chain } from '@types/lodash';
 export { default as chunk } from "./chunk";
 export { default as clamp } from "./clamp";
 export { default as clone } from "./clone";
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by orta** [comment]
You're welcome to make a PRor a discussion for this, but our issues are for DT systems issues
