### ISSUE TITLE
@types/node: v16.6.1 missing web (WHATWG) stream primitives

### ISSUE THREAD

**Issue by Borewit** [DefinitelyTyped/DefinitelyTyped#55293]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55153

<div type='discussions-op-text'>

<sup>Originally posted by **Borewit** August 15, 2021</sup>
 Node v16.5.0 introduced the experimental [WHATWG Streams Standard (or "web streams")](https://nodejs.org/api/webstreams.html#webstreams_overview).
 
A stub module for `node:stream/web` has been introduced in PR #55057: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/dca7357e90ef804954aaf042ed158220bcd09079/types/node/stream/web.d.ts#L2, yet the following web stream primitives and sub-classes are missing from [@types/node v16.6.1](https://www.npmjs.com/package/@types/node/v/16.6.1): 
- [ReadableStream](https://nodejs.org/api/webstreams.html#webstreams_class_readablestream) - Represents a source of streaming data. 
- [WritableStream](https://nodejs.org/api/webstreams.html#webstreams_class_writablestream) - Represents a destination for streaming data. 
- [TransformStream](https://nodejs.org/api/webstreams.html#webstreams_class_transformstream) - Represents an algorithm for transforming streaming data.

Obviously _web streams_ has just been added. I thought I create a place holder for the fact this is pending. </div>

**Comment by orta** [comment]
Closing because this has a discussion
