### ISSUE TITLE
DOMException: Failed to open serial port.

### ISSUE THREAD

**Issue by PpyMohan** [DefinitelyTyped/DefinitelyTyped#55314]
![serialPort_code](https://user-images.githubusercontent.com/25381060/130397487-d63436f5-a36c-40e5-801d-cce954ff2f7d.JPG)
In my code i have got list for device and i am trying to make connection between web interface and device. it throw me an error :: 
DOMException: Failed to open serial port.

**Comment by orta** [comment]
This is the issues for DefinitelyTyped, you're probably wanting to use something like StackOverflow for a question about your code.
