### ISSUE TITLE
[@types/opossum] Wrong type

### ISSUE THREAD

**Issue by GiantKouKou** [DefinitelyTyped/DefinitelyTyped#55319]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55318

<div type='discussions-op-text'>

<sup>Originally posted by **GiantKouKou** August 23, 2021</sup>
Hi!

The attribute `timeout` of `CircuitBreaker.Options` is declared as `number | undefined`

But it can also take `false` as value

It's mentionned in the documentation here :
https://github.com/nodeshift/opossum/blob/536b312b7cc9f00156c83b87dc268c0ab14e023b/lib/circuit.js#L38</div>

**Comment by orta** [comment]
This already has a discussion 👍🏻
