### ISSUE TITLE
ITS: Confusing issue template choice

### ISSUE THREAD

**Issue by Chealer** [DefinitelyTyped/DefinitelyTyped#55413]
I came to report a simple bug in the README, but had some difficulty picking which template I needed to use with the screen below:
![image](https://user-images.githubusercontent.com/486141/131040985-ab5454c9-b89f-4e30-8703-d3ec63dcf5cb.png)

I will choose "Infrastructure Issue" by default, but at first I saw no good option. Obviously, "DT" (which I imagine is used to refer to DefinitelyTyped) is a pretty short acronym the vast majority of developers do not know. "Infrastructure" is also a pretty vague term, even in the context of IT. It can mean technological issues, like a server being down, which I imagine is not the case here.
Finally, filing a ticket is typically not conceived as "discussing an issue". Reporting may indeed involve discussion, but the same way I don't go to the convenience store to "discuss with the cashier", "report an issue" would be much clearer.

My suggestions:
1. Use "common issue" instead of / in addition to "infrastructure issue"
2. Use "report" instead of "discuss"
3. Avoid 2-letter acronyms (except those extremely common)
4. Move the first option last, and rename it "Other issue"

**Comment by orta** [comment]
Yeah, some fo these are good ideas and I've added them - some I can't because of how the GitHub infra for templates is set up - thanks
