### ISSUE TITLE
[@types/node] Drops support for TypeScript < 3.7 in 12.20.21 ("assert.d.ts:2:68 - error TS1144: '{' or ';' expected.")

### ISSUE THREAD

**Issue by Chealer** [DefinitelyTyped/DefinitelyTyped#55430]
This report was for some reason created as a "discussion" #55429 ; moving to a proper ticket.

Our TypeScript 3.5 project stopped compiling yesterday, due to an upgrade to @types/node 12.20.21, with a bunch of errors:

> ERROR in ../node_modules/@types/node/assert.d.ts:2:68 - error TS1144: '{' or ';' expected.
> 2     function assert(value: any, message?: string | Error): asserts value;

![image](https://user-images.githubusercontent.com/486141/131140254-b8827120-05b7-4cc9-aeb3-55887f1425eb.png)

This would be no surprise as TypeScript 3.5 is fairly old and DefinitelyTyped does not support old versions indefinitely, except after analysis it turns out our package.json properly specify the dependency:
`    "@types/node": "^12.7.1",`

In fact, @types/node had already dropped support for TypeScript 3.6, but for some reason, this week this change was backported to branch 12, and while 12.20.20 was fine, 12.20.21 drops support, breaking semantic versioning.

The exact reason why TypeScript 3.5 now fails to compile is usage of TypeScript 3.7 [assertion functions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions).

**Comment by sandersn** [comment]
See my comments on the discussion; this is by design and you'll need to specify 12.20.20 exactly if you're outside the 2-year DT support window.

**Comment by Chealer** [comment]
Thanks @sandersn but there is no need to specify exact versions with any regular package. npm allows to express dependencies with precise version constraints such as foo ~1.0.0 for version 1.0 (less than 1.1), which will suffice for all packages with semantic versioning.

**Comment by Chealer** [comment]
Is there a reason why this ticket is closed?

Also, if the claim about DefinitelyTyped not truly supporting semantic versioning in discussion #55429 is correct, then the README, which discusses semantic versioning much, must specify that DefinitelyTyped has no such support.

**Comment by eric-burel** [comment]
Hi, a similar issue is back with recent version of TS, 4.5.4 raises this issue, while 4.2 does not.
I have a non minimal repro if necessary:https://github.com/VulcanJS/npm-the-right-way, see  `my-package-esbuild`. Updating TS will break `yarn run buid:types`.
