### ISSUE TITLE
roll this repo into the org

### ISSUE THREAD

**Issue by staxmanade** [DefinitelyTyped/DefinitelyTyped#556]
Now that github is redirecting https://github.com/blog/1508-repository-redirects-are-here is there still any reason not to roll this under the org?

**Comment by icecreammatt** [comment]
:+1: for the move

**Comment by cspotcode** [comment]
+1 for this.

`DefinitelyTyped/typings` avoids repetition, concisely explains what the git repository contains (TS typings)  It also avoids naming a git repository "repository" which is a bit weird.  And "typings" is shorter than "repository"

Anything I can do to help make this happen?

**Comment by horiuchi** [comment]
:+1:

**Comment by johnnyreilly** [comment]
@borisyankov - any thoughts on this?  It's been around a long time and I think it'd be good to do it.

**Comment by borisyankov** [comment]
DefinitelyTyped/typings - make sense when you look at the org and the repos.
But still, to me look pretty nasty when considering all user's directories will now be called 'typings' :(

**Comment by vvakame** [comment]
what naming do you like?

**Comment by cspotcode** [comment]
Here are a few ideas:

- declarations
- dt-declarations
- typings.d.ts
- declarations.d.ts
- dt-typings
- community-declarations.d.ts
- ts-typings
- DefinitelyTyped (yeah it's a mouthful, but how many times will I really
type it?  Once to clone my fork, and that's it)
- definitely-typed (kebab-case feels more open-source-y, less Microsoft-y,
which may or may not be a good thing)

Or some other permutation of those?

**Comment by johnnyreilly** [comment]
I really don't mind what the name is - I'm happy with pretty much any of the suggestions made.  

But whatever it is I'd really like to see this happen.  It's really peculiar that we have an organisation set up on GitHub with a number of sub repo's but the main repo that brings people there is sat away from the organisation and underneath an individual account.  It would be good to have everything living together in a consistent fashion.

**Comment by horiuchi** [comment]
My idea:

- d.ts
- typings
- DefinitelyTyped

**Comment by staxmanade** [comment]
Done!
