### ISSUE TITLE
error: invalid path 'types/barnard59-base/nul.d.ts' when working with repo on Windows OS

### ISSUE THREAD

**Issue by peterblazejewicz** [DefinitelyTyped/DefinitelyTyped#55700]
- [x] Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- [x] Leave a message on the [DefinitelyTyped channel in the TypeScript Community Discord](https://discord.gg/typescript).

This is a git trivia, there is a new DT package which contains a file for a module, which defines `nul` type,
resulting `nul.d.ts` file causes error now on Windows OS when using git:
```bash
error: invalid path 'types/barnard59-base/nul.d.ts'
```
as the `nul` is (still) not allowed filename on Windows OS.

**Comment by tpluscode** [comment]
Sorry 😊 . 

Also, 🤯
