### ISSUE TITLE
Add helperText property to carbon-components-react MultiSelectProps definition

### ISSUE THREAD

**Issue by kovacsandor** [DefinitelyTyped/DefinitelyTyped#55798]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55797

<div type='discussions-op-text'>

<sup>Originally posted by **kovacsandor** September 15, 2021</sup>
As it can be seen below, carbon-components-react MultiSelect implementation makes use of a helperText property. It is missing in the type definition. 

https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/MultiSelect/MultiSelect.js

![image](https://user-images.githubusercontent.com/19869080/133441005-24c63c84-9051-49b5-a5c6-93b7b5f7933c.png)
</div>

**Comment by orta** [comment]
Closing because this has a GitHub discussion
