### ISSUE TITLE
Wrong typing in @types/react-native-menu-share

### ISSUE THREAD

**Issue by MeLoveCarbs** [DefinitelyTyped/DefinitelyTyped#55818]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@types/react-native-share-menu@5.0.1` for the project I'm working on.

Wrong typing in @types/react-native-menu-share

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@types/react-native-share-menu/index.d.ts b/node_modules/@types/react-native-share-menu/index.d.ts
index c5767b7..f52822c 100755
--- a/node_modules/@types/react-native-share-menu/index.d.ts
+++ b/node_modules/@types/react-native-share-menu/index.d.ts
@@ -7,7 +7,7 @@
 
 export interface ShareData {
     mimeType: string;
-    data: string;
+    data: string | string[];
     extraData?: object | undefined;
 }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by micro-chipset** [comment]
Already fixed
