### ISSUE TITLE
Missing method in @types/ibm_db

### ISSUE THREAD

**Issue by Arrt74** [DefinitelyTyped/DefinitelyTyped#55913]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55912

<div type='discussions-op-text'>

<sup>Originally posted by **Arrt74** September 22, 2021</sup>
ODBCStatement class in @types/ibm_db is missing method closeSync() defined in source class (https://github.com/ibmdb/node-ibm_db/blob/master/src/odbc_statement.cpp)</div>

**Comment by orta** [comment]
This has a discussion already
