### ISSUE TITLE
[@types/express] Type the HTTP code value of the Response type

### ISSUE THREAD

**Issue by RomainGuarinoni** [DefinitelyTyped/DefinitelyTyped#55983]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55982

<div type='discussions-op-text'>

<sup>Originally posted by **RomainGuarinoni** September 25, 2021</sup>

Would be interestingf if we could **type the HTTP code** of the Response object in express.

We could pass the HTTP code value like this : 

```ts
export interface Response<ResBody = any, Locals extends Record<string, any> = Record<string, any>, 
StatusCode extends number = number>
        extends core.Response<ResBody, Locals,StatusCode> {}
```

and we could type the res like this : 

```ts
import {Request, Response} from "express"

app.get("/",( 
   req : Request,
   res : Response<{}, {} , 200>
)=>{})

```

Actually we can only type the resBody and the locals as shown below : 

```ts
export interface Response<ResBody = any, Locals extends Record<string, any> = Record<string, any>>
        extends core.Response<ResBody, Locals> {}
```

</div>

**Comment by orta** [comment]
This has a discussion already

**Comment by RomainGuarinoni** [comment]
@orta as no one has discussed on the discussion, can i open a PR to try to fix this "issue" or is that not recommended  ?
