### ISSUE TITLE
FB.ui method share_open_graph @types/facebook-js-sdk

### ISSUE THREAD

**Issue by b0raG** [DefinitelyTyped/DefinitelyTyped#56016]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/56015

<div type='discussions-op-text'>

<sup>Originally posted by **b0raG** September 28, 2021</sup>
There is issue using 
 ```
  FB.ui({
            method: 'share_open_graph',
            action_type: 'og.likes',
            action_properties: JSON.stringify({
                object:'https://developers.facebook.com/docs/',
            })
          }, function(response){});
```
This is always failing assuming canvas_editor</div>

**Comment by orta** [comment]
This has a discussion already
