### ISSUE TITLE
[@types/parse] Parse.Schema.all() return type incorrect

### ISSUE THREAD

**Issue by dsyrstad** [DefinitelyTyped/DefinitelyTyped#56024]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/56023

<div type='discussions-op-text'>

<sup>Originally posted by **dsyrstad** September 28, 2021</sup>
### Issue Description
The declared return type from `Parse.Schema.all()` is defined as:
`static all(): Promise<Schema[]>;`

However, the actual return value is an array of the raw REST JSON response object, not `Parse.Schema`. 

### Steps to reproduce
1. Call `await Parse.Schema.all()`.
2. Take the first value of the array result and try to call any `Parse.Schema` method, such as `get()`.

### Actual Outcome
Typescript doesn't complain because it thinks it is a `Parse.Schema` object. However, at runtime you get an error:
`schema.get is not a function`.

### Expected Outcome
The result is defined as an interface of the REST response fields. See https://docs.parseplatform.org/js/guide/#schema for the definition. 

### Workaround
Define an interface:
```typescript
interface RawSchema {
  readonly className: string;
  readonly fields: {
    [key: string]: {
      type: string;
    }
  };
  readonly classLevelPermissions: Parse.Schema.CLP;
  // need to define indexes too...
}
```
and then cast the result of `all()`:
```typescript
const rawSchemas = await Parse.Schema.all() as any as RawSchema[];
```

###  Environment

Client
- Parse JS SDK version: `3.3.0`</div>

**Comment by orta** [comment]
This has a discussion already

**Comment by dsyrstad** [comment]
@orta  I originally intended to create an issue - which is this one - but github created a discussion instead #56023. I created this issue out of that discussion. I think the discussion could be closed instead of this issue.

**Comment by orta** [comment]
Sure, make the PR but discussions are used for discussing the individual types - we use issues for DT level issues (not each types) 👍🏻
