### ISSUE TITLE
`inspector.console` is missing in @types/node

### ISSUE THREAD

**Issue by simhnna** [DefinitelyTyped/DefinitelyTyped#56077]
Is there a reason why inspector.console is missing?
https://nodejs.org/docs/latest-v12.x/api/inspector.html#inspector_inspector_console

I've started a [discussion](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54793) but I'm not sure what I'm supposed to do since no one is reacting to it.

**Comment by akashshyamdev** [comment]
Is this error intentional?, If not, can I handle this issue as part of hacktoberfest

**Comment by orta** [comment]
This already has a discussion so I'm closing this thread, you're welcome to ship a PR if it's missing

**Comment by akashshyamdev** [comment]
@orta where's the discussion?

**Comment by orta** [comment]
> I've started a [discussion](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54793) but I'm not sure what I'm supposed to do since no one is reacting to it.
