### ISSUE TITLE
[braintree-web] CVV only case : number optional

### ISSUE THREAD

**Issue by borracciaBlu** [DefinitelyTyped/DefinitelyTyped#56167]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/51e462b9789948003fd7f9ba73663885ef5b381c/types/braintree-web/modules/hosted-fields.d.ts#L46

As per [docs](https://developer.paypal.com/braintree/docs/guides/hosted-fields/faq#can-i-verify-the-cvv-when-a-customer-uses-or-updates-a-vaulted-card?) there is a case for which number is undefined. 

Could that be changed to this pls? 
Let me know if you want me to PR

```
    number?: HostedFieldsField | undefined;
```

**Comment by martin-badin** [comment]
Feel free to create a PR.
