### ISSUE TITLE
jQuery Deferred

### ISSUE THREAD

**Issue by vadimzzz** [DefinitelyTyped/DefinitelyTyped#5630]
Recently I've found a mismatch in definition of `resolveWith()` method of `JQueryDeferred` class.
According to documentation: https://api.jquery.com/deferred.resolveWith

``` javascript
deferred.resolveWith( context [, args ] ) // args must be an Array
```

Your definition:

``` typescript
resolveWith(context: any, value?: T, ...args: any[]): JQueryDeferred<T>
```

So the correct call of this method causes syntax error:

``` typescript
var def:JQueryDeferred<string>;
var data:string;
def.resolveWith(this, [data]); // <-- syntax error here: TS2345: Argument of type 'string[]' is not assignable to parameter of type 'string'.
def.resolveWith(this, <any>[data]); // <-- this is a workaround to avoid that error
```

`rejectWith()` method also have incorrect definition but it does not produce syntax error.

**Comment by vvakame** [comment]
@johnnyreilly

**Comment by johnnyreilly** [comment]
Feel free to submit a PR!
