### ISSUE TITLE
Definition Request: React Native

### ISSUE THREAD

**Issue by Thegaram** [DefinitelyTyped/DefinitelyTyped#5634]
Please add a definition file for React Native (https://github.com/facebook/react-native).

I tried to make the React Native component View work with TypeScript. I came up with the type definition file below, based on the one for React.js (beginning omitted). Is this the correct approach?

```javascript
declare module "react-native" {
   // ... (define Component and other stuff)
    
    type ViewProps = {
        className?: string;
        style?: any;
        onClick?: any;
        children?: any;
    }
    
    class View extends Component<ViewProps, {}> { }
}
```

The React Native team uses *flow* instead of TypeScript. Might this be a problem?

**Comment by apolkingg8** [comment]
+1 for RN definition, but I think it's not an easy work. RN team said they use `Flow` so they won't support `.d.ts` at this time :cry:

**Comment by bparadie** [comment]
@Thegaram Here is my `react-native.d.ts`. It's very incomplete, though:
https://gist.github.com/bparadie/93cc1078d1db8fcd3c4e

**Comment by rcchen** [comment]
+1 for RN definitions

@bparadie that looks like a good place to start from, you should submit a PR so we can all start contributing to that :)

**Comment by marty-wang** [comment]
+1

**Comment by RobinThrift** [comment]
+1 here too, and +1 @rcchen 's idead

**Comment by joekim** [comment]
+1

**Comment by GabrielCTroia** [comment]
+1

**Comment by ManuelReina** [comment]
+1

**Comment by jittuu** [comment]
+1

**Comment by bgrieder** [comment]
Based on the work of Bernd Paradies, I created a Pull Request with definitions: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6651

These are very preliminary and need more work but I hope they can serve as a base. Please do not hesitate to comment, add, etc...

These definitions should be used with tsc set to target ES6 

I cannot get Travis to compile the test on Definitely Typed though; it may be related to the fact that the target is set to ES6. Any hint is appreciated

@bparadie Thanks for your work

**Comment by bparadie** [comment]
@bgrieder Thanks for picking up the mess! My apologies for not being more involved. Those react-native typings came out of work on a project that I had to put into the freezer for the time being. I am now working on other stuff. But I am very much interested in seeing react-native work together with typescript. I am not convinced that `flow` plus `babel` is such a good idea (see https://github.com/facebook/react-native/issues/2502#issuecomment-137972449). Anyways, please feel free to ping me if you have any questions. Cheers, Bernd.

**Comment by bgrieder** [comment]
@bparadie I have been happily using typescript for a while and initial tests with react-native are quite positive. When using ES6 as a target, transpilation is fast and no further transformation is required. I hope others will get involved an improve these definitions . Cheers

(nb: I set the target to es5 on DefinitelyTyped to pass the Travis build but these definitions are better used with the ES6 target: react-native is already supporting a pretty big chunk of ES6 and the resulting js can be used directly (no webpack, etc...))

**Comment by ManuelReina** [comment]
Thanks @bparadie for your work and @bgrieder thanks for creating the PR.

**Comment by vvakame** [comment]
by #6651
