### ISSUE TITLE
Definition request: Angular-Toastr

### ISSUE THREAD

**Issue by zckrs** [DefinitelyTyped/DefinitelyTyped#5643]
Can you add definitions for [Angular-Toastr](https://github.com/Foxandxss/angular-toastr) ?

***
[Angular-Toastr](https://github.com/Foxandxss/angular-toastr) ==! [Angularjs-Toaster](https://github.com/borisyankov/DefinitelyTyped/tree/master/angularjs-toaster)

**Comment by nkovacic** [comment]
Just submitted a pull request to add Angular-Toastr definition https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7393

**Comment by vvakame** [comment]
:+1:
