### ISSUE TITLE
highcharts-ng error at highcharts-ng.d.ts

### ISSUE THREAD

**Issue by wanwan31** [DefinitelyTyped/DefinitelyTyped#5646]
I'm getting an error at line 27 in highcharts-ng/highcharts-ng.d.ts
It should be a semicolon, and not a comma.
I copied the file and change it locally and i can confirm that it is working with semicolon.

**Comment by vvakame** [comment]
@wanwan31 please send a pull request. I'll review it.

**Comment by baltie** [comment]
Seems like #5665 closes this?
