### ISSUE TITLE
[@types/tabulator-tables] headerFilter should be boolean

### ISSUE THREAD

**Issue by simenstensas** [DefinitelyTyped/DefinitelyTyped#57140]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/01906126b2ced50d3119dc09aa64fbe5f4bb9ff2/types/tabulator-tables/index.d.ts#L1171

I am making my column definition and when trying to assign true to headerFilter after installing @types/tabulator-tables it suddenly wants me to use the "Editor" object instead.

Am I doing something wrong, or is this an issue?

http://tabulator.info/docs/4.5/filter#header
According to this information, it looks like it should be Editor | boolean | undefined.

**Comment by mike-lischke** [comment]
Note: `Editor` includes the `true` literal.

**Comment by martin-badin** [comment]
@simenstensas Hi. Types definitions are correct. As @mike-lischke mentioned `Editor` includes the `true` literal. Please, close this issue. Thanks
