### ISSUE TITLE
Xrm.App is not available on the latest release of @types/Xrm v9.0.47

### ISSUE THREAD

**Issue by dbcottam** [DefinitelyTyped/DefinitelyTyped#57322]
I would like to be able to use the SidePanes functionality that Microsoft has in Preview mode right now.

Xrm.App.sidePanes.getPane  does not work with an error of 'Property 'App' does not exist on type 'XrmStatic'.ts(2339)'

**Comment by martin-badin** [comment]
Hi. I created PR for type definitions but I don't see your mentioned object in the documentation. Please, could you provide documentation for that?

**Comment by dbcottam** [comment]
I found a work around for my issue.  I was directed from https://www.npmjs.com/package/@types/xrm
