### ISSUE TITLE
d3.time.format.utc.multi() isn't defined

### ISSUE THREAD

**Issue by thinkh** [DefinitelyTyped/DefinitelyTyped#5751]
[D3 documentation](https://github.com/mbostock/d3/wiki/Time-Formatting#format_multi):
> The multi method is available on any d3.time.format constructor. For example, d3.time.format.utc.multi returns a multi-resolution UTC time format, and locale.timeFormat.multi returns a multi-resolution time format for the specified locale.

According to the documentation the following example code doesn't work with the current tsd version:

```
  d3.time.format.utc.multi([
      ['.%L', function(d) { return d.getMilliseconds(); }],
      [':%S', function(d) { return d.getSeconds(); }],
      ['%I:%M', function(d) { return d.getMinutes(); }],
      ['%I %p', function(d) { return d.getHours(); }],
      ['%a %d', function(d) { return d.getDay() && d.getDate() != 1; }],
      ['%b %d', function(d) { return d.getDate() != 1; }],
      ['%b', function(d) { return d.getMonth(); }],
      ['%Y', function() { return true; }]
    ]);
```

It throws the error `Property 'multi' does not exist on type '(specifier: string) => Format'`.

Any ideas how to define this in the d3.d.ts?

**Comment by vvakame** [comment]
@thinkh please send a pull request. I'll review it.

**Comment by thinkh** [comment]
@vvakame Thanks, but I don't know how to express the d3 function as TypeScript definition. Does someone else is able to modify it and send you the pull request?

**Comment by vvakame** [comment]
@gustavderdrache and @borisyankov are definition authors.
https://github.com/borisyankov/DefinitelyTyped/blob/master/d3/d3.d.ts#L3

**Comment by gustavderdrache** [comment]
That's definitely an omission -- nice catch!

I've opened a pull request for it. You can see the changes [here](https://github.com/borisyankov/DefinitelyTyped/pull/5926/files). Luckily, this was a small change to make so you should be able to take a look and get a sense of how to add to a definitions file.

**Comment by thinkh** [comment]
@gustavderdrache Nice work, too. Thanks.
