### ISSUE TITLE
[braintree-web] Property 'on' does not exist on type 'ThreeDSecure'.

### ISSUE THREAD

**Issue by VinayKrMittal** [DefinitelyTyped/DefinitelyTyped#57686]
I have used below code and it's gives me error: 'Property 'on' does not exist on type 'ThreeDSecure'. And the code is as per official Braintree-web documentation.

```
  braintree.threeDSecure.create({
      authorization,
      version: '2'
    }, function (createErr, threeDSecureInstance) {
      if(threeDSecureInstance){
      threeDSecureInstance.on('lookup-complete', function (data, next) {
        // inspect the data
    
        // call next when ready to proceed with the challenge
        next();
      });
    }
```

![Screenshot 2021-12-13 at 4 42 19 PM](https://user-images.githubusercontent.com/26204445/145802462-c10953f7-50be-4774-aba2-0eb320d065be.png)

Anyone help me in this ?

**Comment by martin-badin** [comment]
Could you please provide documentation?

**Comment by VinayKrMittal** [comment]
> Could you please provide documentation?
@martin-badin link of documentation: https://braintree.github.io/braintree-web/current/ThreeDSecure.html#lookup-complete-examples


![Screenshot 2021-12-16 at 2 37 42 PM](https://user-images.githubusercontent.com/26204445/146341683-a7180c54-3a69-45ee-9bac-d75dc1dd2c10.png)

**Comment by peZhmanParsaee** [comment]
@VinayKrMittal This issue is resolved, and I linked a merged PR to it, you can test it and close this issue

**Comment by VinayKrMittal** [comment]
Thanks @peZhmanParsaee issue has been resolved. So, closing this.

**Comment by VinayKrMittal** [comment]
@peZhmanParsaee  why arguments in callback function are optional as data and next should be there.
