### ISSUE TITLE
[@types/react-router-dom] Missing types for react-router-dom and react-router v6

### ISSUE THREAD

**Issue by joaocasarin** [DefinitelyTyped/DefinitelyTyped#57705]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/57704

<div type='discussions-op-text'>

<sup>Originally posted by **joaocasarin** December 13, 2021</sup>
Well, these libraries have recently been updated to its v6, which changes some methods, attributes. The latest version of @types for these libraries has been released 25 days ago, but it is not yet supporting the new v6.

For those trying to use latest `react-router-dom` which version is 6.1.1 and latest `@types/react-router-dom` which version is 5.3.2, you will get a lot of errors referencing the old v5 methods, which are not available on v6 anymore, such as:

* match
* PromptProps
* Prompt
* Switch
* useHistory

And many others. There are literally 38 errors like that, some may be referencing the same method/attribute.

Full list of errors attached
[log.txt](https://github.com/DefinitelyTyped/DefinitelyTyped/files/7707433/log.txt)</div>

**Comment by SimonSchick** [comment]
Both of these packages ship their own types, I'm unsure why these would need to live on DT?

**Comment by joaocasarin** [comment]
@SimonSchick maybe because some would choose older versions of the package, so it needs the DT dependency.

**Comment by doubleyooz** [comment]
After a long time using react-router-dom@v6 and @types/react-router-dom I finally got a compatibility error.

I don't know what has changed, but now react-router-dom provides its own types and you can no longer use version 6 alongside @types/react-router-dom without facing errors. The solution is simply to uninstall the types package.

It would be nice if the @types/react-router-dom alerted the user about package incompatibility when you install it.
