### ISSUE TITLE
File '...node_modules/@types/gapi.auth2/index.d.ts' is not a module.ts(2306)

### ISSUE THREAD

**Issue by sameerparekh** [DefinitelyTyped/DefinitelyTyped#57766]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/57700

<div type='discussions-op-text'>

<sup>Originally posted by **sameerparekh** December 13, 2021</sup>
Hello. I have added @types/gapi.auth2 to my yarn project with yarn install. When I put the following into my .tsx file:

`import { GoogleUser } from 'gapi.auth2';
`

I get this error:

`
File '...node_modules/@types/gapi.auth2/index.d.ts' is not a module.ts(2306)
`

Thanks!</div>

**Comment by PythonCoderAS** [comment]
Did you install the actual `gapi.auth2` package? The `@types` package does not give you the actual module.

**Comment by orta** [comment]
Closing as it has an existing discussion

**Comment by PythonCoderAS** [comment]
> Closing as it has an existing discussion

It would be nice if you could link the previous issue.

**Comment by sameerparekh** [comment]
Hi I have installed gapi-script. I could not find a gapi.auth2 package on npm.

**Comment by PythonCoderAS** [comment]
> Hi @PythonCoderAS -- yes I have installed gapi-script. I could not find a gapi.auth2 package on npm. Is there another package I should be installing? Thanks!

The google developer docs (https://developers.google.com/identity/sign-in/web/reference) says you need to `gapi.load` the module instead of a classic import.

**Comment by sameerparekh** [comment]
Yes, I am running gapi.load, like this: 

gapi.load('client:auth2')

I see the doc you linked says 

gapi.load('auth2')

I can try that but I'm unclear how that impacts type definitions when the code compiles?

**Comment by sameerparekh** [comment]
My code works fine btw but I just can't import the GoogleUser type definition, so my code is working without a defined type for the GoogleUser-- I'm using 'any'
