### ISSUE TITLE
angularjs.TypeScript.DefinitelyTyped bug with $q service ?

### ISSUE THREAD

**Issue by warpdesign** [DefinitelyTyped/DefinitelyTyped#5777]
I'm using angularjs.TypeScript.DefinitelyTyped with Visual Code and when typing something like `$q(function(resolve, reject) {})` it returns an error:

`Value of Type 'IQService is not callable. Did you mean to include new?`

This is incorrect since the service is meant to be called (see doc: https://docs.angularjs.org/api/ng/service/$q)

I would have corrected it in the .ts file but I'm not familiar with the format.

**Comment by chrootsu** [comment]
Please check that you are using the latest version of the angular.d.ts file. I can't check Visual Studio, but Idea and tsc compiles this correctly. A needed type already exists in the angular.IQService interface.
https://github.com/borisyankov/DefinitelyTyped/blob/master/angularjs/angular.d.ts#L1002-L1003

**Comment by warpdesign** [comment]
I think Visual Code isn't using the latest version indeed. This is what I have for IQService:

    interface IQService {
        new (resolver: (resolve: IQResolveReject<any>) => any): IPromise<any>;
        new (resolver: (resolve: IQResolveReject<any>, reject: IQResolveReject<any>) => any): IPromise<any>;
        new <T>(resolver: (resolve: IQResolveReject<T>, reject: IQResolveReject<any>) => any): IPromise<T>;
       ...

Using the code from your link removes the error.

**Comment by warpdesign** [comment]
How can I know the version of angular.d.ts btw ? I did not find any version string inside the file.

**Comment by chrootsu** [comment]
If you are using the program tsd for manage type definition files and you are install them with the flag --save then you can see a hashes of commits of the current installed files inside a tsd.json otherwise I don't know.

**Comment by vvakame** [comment]
https://github.com/borisyankov/DefinitelyTyped/blob/master/angularjs/angular.d.ts#L1018-L1019
I think IQService has call signature.
do you have repro code?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
