### ISSUE TITLE
[@types/react-instantsearch-dom] DynamicWidgets - update types

### ISSUE THREAD

**Issue by emil-datcu** [DefinitelyTyped/DefinitelyTyped#57786]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/57783

<div type='discussions-op-text'>

<sup>Originally posted by **emil-datcu** December 20, 2021</sup>
Hi,
Can someone update the types for react-instantsearch-dom?
The library is now at 6.18, but the types are at just 6.12 and the DynamicWidgets component for example cannot be used because the types don't have it:
![image](https://user-images.githubusercontent.com/90839342/146762371-d5c6a0b6-b054-4c19-8829-74e582b46ac8.png)
</div>

**Comment by eyeamkd** [comment]
I can take this up!

**Comment by orta** [comment]
closing as it has a discussion
