### ISSUE TITLE
npm test <package name> fails with updates to tslint.json (mojang-minecraft)

### ISSUE THREAD

**Issue by mammerla** [DefinitelyTyped/DefinitelyTyped#58169]
With this check-in (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/9d35fe5b9f3bac0a30c252a61e411f84a6b7ba5d) - though now when I run npm test mojang-minecraft (my module) - it fails with:

  Error: If 'tslint.json' is present, it should extend "dtslint/dt.json"

I note the readme still says tslint.json should only extend dtslint/dt.json.  So - should I revert this change for my tslint.json files?  (or what is the new way to test individual modules?)  I'm sure I'm missing something obvious :)

@sandersn

**Comment by mammerla** [comment]
(the solution is run: npm i, of course.)

**Comment by userlerueda** [comment]
Same thing here, although I did do `npm i`
