### ISSUE TITLE
All test cases failed

### ISSUE THREAD

**Issue by rajusah15** [DefinitelyTyped/DefinitelyTyped#58306]
I tried many time by followed the steps given in README file but still observing all test cases are failing.
[root@29f12726e6f4 DefinitelyTyped]# npm test @types/node

> definitely-typed@0.0.3 test
> dtslint types "@types/node"

Error: On DefinitelyTyped, must include `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.
This was inferred as a DefinitelyTyped package because it contains a `// Type definitions for` header.
    at /usr/local/lib/node_modules/dtslint/bin/lint.js:150:23
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/dtslint/bin/lint.js:5:58)

**Comment by martin-badin** [comment]
please my PR
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58223
You have to extend from `@definitelytyped/dtslint/dt.json`

**Comment by jakebailey** [comment]
tslint is no more.
