### ISSUE TITLE
SocketCluster / ag-simple-broker - Should be `data` not `date`

### ISSUE THREAD

**Issue by GuillaumeCisco** [DefinitelyTyped/DefinitelyTyped#58352]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fe4a4455c9a620ba75133aff14802ad0a60c114e/types/ag-simple-broker/index.d.ts#L147

**Comment by GuillaumeCisco** [comment]
@DanielRose

**Comment by DanielRose** [comment]
@GuillaumeCisco Feel free to take a look at the PR.
