### ISSUE TITLE
Update Rx definitions to v3.1.2

### ISSUE THREAD

**Issue by gusbicalho** [DefinitelyTyped/DefinitelyTyped#5842]
The defs are available in the package
https://www.npmjs.com/package/rx

**Comment by baltie** [comment]
It seems to me that the rx definitions here at DefinitelyTyped are mostly for RxJS v2.5.3, with some stuff from the newer versions thrown in for good measure. For instance, the scan function that had it's arguments reversed in version 3.0. 

I'm not sure if there is any point in keeping the RxJS types around. The RxJS library is keeping the TypeScript definitions updated themselves and they are, as you say, part of the package, so why go here for typings that are inferior and outdated? With newer versions of RxJS (it's up to 4.0.1 now) coming rapidly, DefinitelyTyped/rx is becoming redundant.

@Igorbek What do you think?
