### ISSUE TITLE
WinRT.d.ts DefinitelyTyped incomplete

### ISSUE THREAD

**Issue by Norticaranda** [DefinitelyTyped/DefinitelyTyped#5844]
I'm doing a new universal app for Windows 10 in htm5+javascript.

My intention is use Typescript with winJs and WinRT. But when I try to use few namespaces, the winrt.d.ts is incomplete. For example, the next namespace and clases aren't

Windows.Graphics.Display.DisplayInformation

Windows.Media.SystemMediaTransportControls

**Comment by vvakame** [comment]
patches welcome!

**Comment by vojtechhabarta** [comment]
This method is also missing: `Windows.UI.ViewManagement.ApplicationView.getForCurrentView().tryEnterFullScreenMode()`

**Comment by SaschaNaz** [comment]
We really need an automated script to generate winrt.d.ts as we cannot fix it every time the API updates.

**Comment by SaschaNaz** [comment]
I've created a PR. #7287
