### ISSUE TITLE
node_modules/@types/superagent/index.d.ts(23,10): error TS2305: Module '"buffer"' has no exported member 'Blob'.

### ISSUE THREAD

**Issue by zaytsev5** [DefinitelyTyped/DefinitelyTyped#58445]
When github run CI/CD with my repo, it got the error: node_modules/@types/superagent/index.d.ts(23,10): error TS2305: Module '"buffer"' has no exported member 'Blob'.
Hope someone handled it

**Comment by valera33** [comment]
yes I see same problem with new release (4.1.15)
4.1.14 is OK

**Comment by ayeen** [comment]
When GitHub run CI/CD with my repo, it got the error: node_modules/@types/superagent/index.d.ts(23,10) 
Module '"buffer"' has no exported member 'Blob'.
Hope someone handled it

**Comment by zaytsev5** [comment]
> yes I see same problem with new release (4.1.15) 4.1.14 is OK

**Comment by djErock** [comment]
Build breaker for me. Manually installing 4.1.14 fixed but this was a peer dependency of a nest.js package. Please fix so I can get this out the devDeps ASAP. Thanks

**Comment by dantehemerson** [comment]
Same here @djErock. Since we don't have a solution for this yet,,can we reopen this issue @zaytsev5?

**Comment by zaytsev5** [comment]
> 

you mean switch @types/superagent to 4.1.14 ?

**Comment by valera33** [comment]
upgrading @types/node (from 12.x to 14.x) helped for me

**Comment by adrianoreine** [comment]
I changed the version and it worked. **Suggestion:** Improve your semantic versioning as this represents a **BREAKING CHANGE** and not a patch.

**Comment by mustafakaranja** [comment]
solution: upgrade the version of @types/node to 16. in my case it is working

**Comment by tamusjroyce** [comment]
I agree. This should support node 12.x or a minor bump rather than a patch for semantic versioning. So why did this get closed instead of reverted and the correct versioning bump?

**Comment by subhash-malireddy** [comment]
"@types/node": "^14.18.16", "@types/superagent": "^4.1.15".

The above versions worked for me.

**Comment by tamusjroyce** [comment]
node 14 and its typing breaks our framework. It won't be until the end of this year we can migrate from node 12 to 14.

**Comment by Notaduck** [comment]
> nest

Did you find a way to get it working?

**Comment by lebyanelm** [comment]
I tried to create a pull request with a fix here `https://github.com/lebyanelm/DefinitelyTyped/pull/1`
