### ISSUE TITLE
@types/node buffer `Uint` aliases

### ISSUE THREAD

**Issue by SheetJSDev** [DefinitelyTyped/DefinitelyTyped#58478]
Reference: https://nodejs.org/dist/latest-v16.x/docs/api/buffer.html#bufreaduintleoffset-bytelength

NodeJS traditionally capitalized the `i` in `UInt` e.g. `Buffer#readUInt32LE`.  When typed arrays were standardized in the browsers, the implementations and specs preferred to keep the `i` lowercase e.g. `Uint8Array`.

Node v14.9.0 added aliases to align with the typed array style, so `Buffer#readUint32LE` is an alias for `Buffer#readUInt32LE`.  This change was backported to v12.19.0.

These aliases are missing from @types/node.  The specific aliases can be found by searching for the phrase "This function is also available under the" in the Buffer documentation (currently 18 aliases exist)

**Comment by martin-badin** [comment]
Hi @SheetJSDev. Please could you review it?
