### ISSUE TITLE
openfin/v50 tests failing #58496

### ISSUE THREAD

**Issue by lavalleeale** [DefinitelyTyped/DefinitelyTyped#58502]
#58496 failed on an unchanged module (openfin/v50). I've tried running npm test openfin/v50 on master and it still fails
`Error: ../../../../../.dts/typescript-installs/4.6/node_modules/typescript/lib/lib.dom.d.ts(11244,14): error TS2687: All declarations of 'devicePixelContentBoxSize' must have identical modifiers.
Error: ../resize-observer-browser/index.d.ts(47,14): error TS2687: All declarations of 'devicePixelContentBoxSize' must have identical modifiers.
Error: ../resize-observer-browser/index.d.ts(47,14): error TS2717: Subsequent property declarations must have the same type.  Property 'devicePixelContentBoxSize' must be of type 'readonly ResizeObserverSize[]', but here has type 'readonly ResizeObserverSize[] | undefined'.`

**Comment by vbifonixor** [comment]
@lavalleeale Could you please share your solution if you've managed to fix this for yourself?

**Comment by lavalleeale** [comment]
A new update fixed it for me, but I have not tested recently to see if the behavior has returned
