### ISSUE TITLE
AngularJS IHttpRequestConfigHeaders Interface Wrong

### ISSUE THREAD

**Issue by acepoblete** [DefinitelyTyped/DefinitelyTyped#5855]
I think that the interface for IHttpRequestConfigHeaders is wrong.  All the properties for this object have been defined as strings, when they seem to be defined as objects in the angular doc.

https://docs.angularjs.org/api/ng/service/$http#setting-http-headers

I think that the interface should define each property as any, they way it did before.

**Comment by mickeyvip** [comment]
+1

**Comment by acepoblete** [comment]
`strings` are used in the `run()` method, but only to set child properties.  Its very clear in the angular $http source that the properties off of `$http.defaults.headers` are of type `Object`, not `string`.

here is the code from angular [source](https://github.com/angular/angular.js/blob/master/src/ng/http.js#L295)

```
var APPLICATION_JSON = 'application/json';
var CONTENT_TYPE_APPLICATION_JSON = {'Content-Type': APPLICATION_JSON + ';charset=utf-8'};

....

// default headers
headers: {
   common: {
      'Accept': 'application/json, text/plain, */*'
   },
   post:   shallowCopy(CONTENT_TYPE_APPLICATION_JSON),
   put:    shallowCopy(CONTENT_TYPE_APPLICATION_JSON),
   patch:  shallowCopy(CONTENT_TYPE_APPLICATION_JSON)
},
```

**Comment by billccn** [comment]
Hi, I am responsible for this bit of new typing. It should indeed by an object of `string|function` values. I was fooled in the same way as @mickeyvip.

To avoid confusion though, `$httpProvider.defaults` and `$http.defaults` is the same object in most cases. The `run()` should should be better written as `$http.defaults.headers.common['Authorization'] = 'Basic YmVlcDpib29w'`.

**Comment by acepoblete** [comment]
I'm not sure what needs to be done here.  but if you have something outlined I will modify my pull request and get things nailed down.  just need a little more guidance.

**Comment by billccn** [comment]
It's a bit complicated to explain. Since the current PR solves most of the
cases, I think it should go in first. The only thing is the indexer should
be typed to `any` as well.

**Comment by acepoblete** [comment]
i updated my pull request

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
