### ISSUE TITLE
Definition request: Relay

### ISSUE THREAD

**Issue by jzalucki** [DefinitelyTyped/DefinitelyTyped#5865]
Can you add definitions for **Relay**

**Comment by GrzegorzKaczan** [comment]
+1

**Comment by lukecwilliams** [comment]
Relay definitions exist, recommend closing this thread.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-relay

**Comment by alloy** [comment]
There’s now typings for Relay Modern.
