### ISSUE TITLE
crypto.d.ts randomInt documentation error

### ISSUE THREAD

**Issue by a-downing** [DefinitelyTyped/DefinitelyTyped#58684]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7467038c60726c43ccfc0f084cd8d5d8f062d234/types/node/crypto.d.ts#L1746
https://nodejs.org/api/crypto.html

"The range (`max - min`) must be less than 248."
Should actually be:
"The range (`max - min`) must be less than 2**48."

I'm not sure if this is from copying the formatted Node.js HTML documentation into a text document and losing <sup>48</sup>. If so, there could be errors like this elsewhere.

**Comment by kaikaibenkai** [comment]
The mistake appears to still be present.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0cd509f31f4d14a20da5b25c685e83b66ddba952/types/node/ts4.8/crypto.d.ts#L1923
