### ISSUE TITLE
/node_modules/@types/fs-extra/index.d.ts(269,53): TS2694: Namespace '"fs"' has no exported member 'Dir'.

### ISSUE THREAD

**Issue by hmz886love** [DefinitelyTyped/DefinitelyTyped#58768]
/node_modules/@types/fs-extra/index.d.ts(269,53):
TS2694: Namespace '"fs"' has no exported member 'Dir'.
/node_modules/@types/fs-extra/index.d.ts(382,52):
TS2694: Namespace '"fs"' has no exported member 'RmDirOptions'.
/node_modules/@types/fs-extra/index.d.ts(271,52):
TS2694: Namespace '"fs"' has no exported member 'OpenDirOptions'.

**Comment by hmz886love** [comment]
@types/fs-extra@9.0.13

**Comment by mkossoris** [comment]
I'm having this issue as of yesterday as well with same version as @hmz886love.

**Comment by mkossoris** [comment]
Installing @types/node@14.18.11 seems to have worked for me FYI
