### ISSUE TITLE
No declaration file was found for module "@ckeditor/ckeditor5-list/src/listproperties".

### ISSUE THREAD

**Issue by Mr-Lion** [DefinitelyTyped/DefinitelyTyped#58782]
Hello,

I noticed that the definition "listproperties.d.ts" is missing here.
Can someone help me with this?

![image](https://user-images.githubusercontent.com/6929357/153903436-983cda74-9610-412a-bf99-a6ad89c5fff8.png)

![image](https://user-images.githubusercontent.com/6929357/153903751-f344ddd8-a7d3-4b64-9583-d379acbd97e3.png)

Here is the exact translation of the error message in VSCode:
```
No declaration file was found for module "@ckeditor/ckeditor5-list/src/listproperties". "D:/projects/archv5/node_modules/@ckeditor/ckeditor5-list/src/listproperties.js" is implicitly of type "any".
   If the @ckeditor/ckeditor5-list package does indeed expose this module, consider submitting a pull request to modify https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ckeditor__ckeditor5-list. ts(7016)
```

I'm asking for your help, otherwise I can't get any further with my project and the module plays a very important and decisive role for me.

Thanks in advance for all the trouble

**Comment by Mr-Lion** [comment]
Hi @martin-badin,

Thanks for the answer. Unfortunately I'm not that advanced as to what typescript is. But what do I have to do exactly?
Has the problem been fixed and is there a new version?

Or do I have to create the file myself?
If yes, could you help me with that?
What is the best way I should go about it?

**Comment by martin-badin** [comment]
Hi @Mr-Lion. We have to wait for a review from a maintainer of the package.

**Comment by Mr-Lion** [comment]
Hi @martin-badin,

Hmm, thanks for the information.
But it shouldn't be too difficult to do it this way... After all, only a few additions are made.
Not all projects have to wait for this. It would be totally ridiculous.

Isn't there a way to speed this up?

**Comment by martin-badin** [comment]
Yes, we can ping a maintainer of the package in the PR or ping a DT maintainer.

**Comment by Mr-Lion** [comment]
Thanks for the hint. How can you do this here? Then let's do it so that this is accelerated accordingly. How can I watch this from here?
