### ISSUE TITLE
Update lru-cache to @7

### ISSUE THREAD

**Issue by stefanb2** [DefinitelyTyped/DefinitelyTyped#58834]
lru-cache@7 has deprecated `maxAge` and replaced it with `ttl`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/369ecc516615fb782639bd4d707be43a01c90df4/types/lru-cache/index.d.ts#L137

My current setup:
~~~~
@types/lru-cache": "^5.1.1",
"lru-cache": "^7.3.1",
~~~~

**Comment by vetlevo** [comment]
Also, the reset function is deprecated and has been replaced by clear.

**Comment by vetlevo** [comment]
Has been fixed in the latest version, the issue can be closed.
