### ISSUE TITLE
[@types/lodash] Argument of type 'number[][]' is not assignable to parameter of type 'ArrayLike<number[][]>'

### ISSUE THREAD

**Issue by artidata** [DefinitelyTyped/DefinitelyTyped#58863]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/58858

<div type='discussions-op-text'>

<sup>Originally posted by **artidata** February 18, 2022</sup>
In Javascript project the following code will do just fine:
```js
console.log(_.xor([[2,2],[1,1]],[[1,1]])) //[[2,2]]
```
but it will report error:

```error
Argument of type 'number[][]' is not assignable to parameter of type 'ArrayLike<number[][]>'
```
What should the correction be?</div>

**Comment by ExE-Boss** [comment]
The parameter type should be: `ArrayLike<number[]>`, `ArrayLike<readonly number[]>`, or `ArrayLike<ArrayLike<number>>`.
