### ISSUE TITLE
[@types/luxon] Add type for new method toUnixInteger

### ISSUE THREAD

**Issue by antFrancon** [DefinitelyTyped/DefinitelyTyped#58953]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@types/luxon@2.0.9` for the project I'm working on.

Upgrade types to fit with [Luxon last release](https://github.com/moment/luxon/blob/HEAD/CHANGELOG.md#231-2022-02-23)

```diff
diff --git a/node_modules/@types/luxon/src/datetime.d.ts b/node_modules/@types/luxon/src/datetime.d.ts
index 2a4ab29..6c49435 100755
--- a/node_modules/@types/luxon/src/datetime.d.ts
+++ b/node_modules/@types/luxon/src/datetime.d.ts
@@ -1353,6 +1353,11 @@ export class DateTime {
      */
     toSeconds(): number;
 
+    /**
+     * Returns the epoch seconds (as a whole number) of this DateTime.
+     */
+    toUnixInteger(): number;
+
     /**
      * Returns an ISO 8601 representation of this DateTime appropriate for use in JSON.
      */
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by martin-badin** [comment]
@antFrancon please review
