### ISSUE TITLE
Definition for del is wrong/incomplete

### ISSUE THREAD

**Issue by MartinJohns** [DefinitelyTyped/DefinitelyTyped#5908]
This file is apparently wrong: https://github.com/borisyankov/DefinitelyTyped/blob/master/del/del.d.ts

According to the project (https://github.com/sindresorhus/del) the `del` function returns a promise. But the definition says it returns void.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by tkrotoff** [comment]
@MartinJohns this issue can be closed

**Comment by vvakame** [comment]
thanks!
