### ISSUE TITLE
Cannot read properties of undefined (reading '__type')

### ISSUE THREAD

**Issue by GauravWeb8** [DefinitelyTyped/DefinitelyTyped#59171]
I'm facing Cannot read properties of undefined (reading '__type') issue on retrieving the content of cloud file attachment, in other attachments, it's working but not working in the cloud file attachment
see the below code:-
![image](https://user-images.githubusercontent.com/101108055/157021264-7bbed4d0-2e6d-4b8c-bcb8-8567e5e2c6bd.png)
`  if (attachments.length > 0) {
        for (let i = 0 ; i < attachments.length ; i++) {
          var options = { asyncContext: { type: attachments.attachmentType } };
          item.getAttachmentContentAsync(attachments[i].id,options , this.handleAttachmentsCallback);
        }
    }`
Error:-
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__type')
    at i (isAttachmentOfItemType.ts:15:21)
    at getAttachmentContentAsyncApiMethod.ts:45:9
    at ln (executeApiMethod.ts:109:9)
    at EndpointRegistrator.ts:41:9
    at Microsoft.Office.Common.Invoker.invoke (osfruntime.js:19:51976)
    at O (osfruntime.js:19:39836)
    at U (osfruntime.js:19:43619)`
 
![image](https://user-images.githubusercontent.com/101108055/157023384-f445bfd1-1f93-4f3a-871c-38523ba052c2.png)

**Comment by samantharamon** [comment]
Hi @GauravWeb8. We're sorry to hear you ran into an issue while retrieving the contents of a cloud-based attachment. Are you still experiencing issues with this? I tested the `getAttachmentContentAsync` method on a cloud-based file and I'm unable to replicate the error you received.

**Comment by samantharamon** [comment]
Hi @GauravWeb8. As we haven't heard back from you, we'll go ahead and close this issue. However, if you need any assistance, please don't hesitate to reopen this issue or create a new one. Thank you.
