### ISSUE TITLE
add token in typescript

### ISSUE THREAD

**Issue by RobotXX1** [DefinitelyTyped/DefinitelyTyped#59289]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@types/steamid@2.0.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@types/steamid/index.d.ts b/node_modules/@types/steamid/index.d.ts
index bb9d484..b8dd357 100644
--- a/node_modules/@types/steamid/index.d.ts
+++ b/node_modules/@types/steamid/index.d.ts
@@ -26,6 +26,7 @@ declare class SteamID {
     type: SteamID.Type;
     instance: SteamID.Instance;
     accountid: number;
+    token:string;
 
     /**
      * You can create a SteamID object from a Steam2 rendered ID, a Steam3 rendered ID, a SteamID64, or from the four parts that make up a SteamID.
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by martin-badin** [comment]
@RobotXX1 feel free to open PR.
