### ISSUE TITLE
scrollbooster dragOffset

### ISSUE THREAD

**Issue by aiphee** [DefinitelyTyped/DefinitelyTyped#59335]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

dragOffset is not a number but object containing numbers for `x` and `y`

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@types/scrollbooster/index.d.ts b/node_modules/@types/scrollbooster/index.d.ts
index 584aba9..5ab751d 100755
--- a/node_modules/@types/scrollbooster/index.d.ts
+++ b/node_modules/@types/scrollbooster/index.d.ts
@@ -12,7 +12,10 @@ export interface ScrollingState {
     isMoving: boolean;
     isDragging: boolean;
     position: Required<Position>;
-    dragOffset: number;
+    dragOffset: {
+        x: number;
+        y: number;
+    };
     borderCollision: {
         left: boolean;
         right: boolean;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by princefishthrower** [comment]
@aiphee - this should be resolved in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62538

**Comment by princefishthrower** [comment]
@aiphee - this should be resolved in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62540

**Comment by aiphee** [comment]
Works, thanks!
