### ISSUE TITLE
[@typescript/jsrsasign] ECDSA constructor missing param prv

### ISSUE THREAD

**Issue by irririki** [DefinitelyTyped/DefinitelyTyped#59490]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/59489

<div type='discussions-op-text'>

<sup>Originally posted by **irririki** March 27, 2022</sup>
I am using:
"jsrsasign": "^10.5.13",
"@types/jsrsasign": "^10.2.0",

In ECDSA.d.ts, the constructor is defined as 
[https://github.com/DefinitelyTyped/DefinitelyTyped/blob/173aa9174685d78871a5c035b74d856f4aef9cc8/types/jsrsasign/modules/KJUR/crypto/ECDSA.d.ts#L17](url)
`constructor(publicKey?: { curve: string; pub?: string | undefined });`

However, in ecdsa-modified-1.0.js, the params passed in the function might be prv or pub or both, as shown in line starting from 665 
[https://github.com/kjur/jsrsasign/blob/3f79b95baa34a2c35070b43d009f318d5c42ecc2/src/ecdsa-modified-1.0.js#L665](url)
```
if (params !== undefined) {
	if (params.prv !== undefined) this.setPrivateKeyHex(params.prv);
	if (params.pub !== undefined) this.setPublicKeyHex(params.pub);
}
```

To be in line with the code in jsrasign v10.5.13, I think the constructor should be changed to:
constructor(publicKey?: { curve: string; pub?: string | undefined; prv?: string | undefined});

</div>

**Comment by MysteryBlokHed** [comment]
Resolved in #59494
