### ISSUE TITLE
Question: how to write definitions for scripts that does not expose modules to the global scope?

### ISSUE THREAD

**Issue by billccn** [DefinitelyTyped/DefinitelyTyped#5967]
I am writing definitions for [error-stack-parser](https://github.com/stacktracejs/error-stack-parser/blob/master/error-stack-parser.js), which uses "Universal Module Definition (UMD)" to register the module if some module system is available. If successful, the module will not be accessible from the global scope.

However, most `d.ts` files for external modules seems to be written with a global module and then a external module definition pointing to the same thing. This seems a bit unsafe to me, as the user can legitimately refer to global module which is actually undefined.

If this is not intentional, how to write a module definition that is hidden from the global scope?

**Comment by use-strict** [comment]
You can try an approach similar to the react definition. If you know before-hand what flavor of the library you will use at runtime,  you can have two declaration files, one for commonjs/amd module and the other for the global namespace, and include the one you need. If the decision is only known at runtime, I'm afraid you are out of luck.
