### ISSUE TITLE
[@types/react-calendar] values for selected range can be null

### ISSUE THREAD

**Issue by xelaz** [DefinitelyTyped/DefinitelyTyped#59703]
Now CalendarProps has property value definition like this:
```
value?: Date | Date[] | null | undefined;
```

But i can set on select range functionality values like this [Date, null] or [null, null] or [Date, Date] [null, Date]
Is it better to rewrite the rule in this one:
```
value?: Date | null | [Date | null, Date | null] | undefined;
```

**Comment by ar-nelson** [comment]
Looks like this was resolved in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60039
