### ISSUE TITLE
@types/react@17.0.44 breaks everything

### ISSUE THREAD

**Issue by billnbell** [DefinitelyTyped/DefinitelyTyped#59862]
Reverted to 17.0.43 to fix it.

Its instance type 'WebView<{}>' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/Users/bill/theclub/TheClub/node_modules/@types/react-native-global-props/node_modules/@types/react/index").ReactNode'.

**Comment by GimpMaster** [comment]
I think the whole internet is seeing this bug unfortanetly

**Comment by GimpMaster** [comment]
See here:

https://stackoverflow.com/questions/71791347/npm-package-cannot-be-used-as-a-jsx-component-type-errors/71828113#71828113

**Comment by billnbell** [comment]
I get all of that, but I already has resolution in package.json, and the only thing that fixed it was 17.0.43. And I am 99% sure someone merged the 18 branch into 17.0.44.

**Comment by clisterdmello** [comment]
I got this issue with @types/react@18.0.8 (which is the latest). 

I have npm 6 so i use https://www.npmjs.com/package/npm-force-resolutions package to implement resolution (which comes by default in yarn ) 

NPM 8+ could take some inspiration from this below post.
https://stackoverflow.com/questions/52416312/npm-equivalent-of-yarn-resolutions

**Comment by eps1lon** [comment]
This is caused by duplicate versions of `@types/react` which is generally not supported.

Try to ensure only a single version of `@types/react` is installed. Either remove all lockfile entries for `@types/react` and re-install or ensure Yarn's `resolutions` or NPM's `overrides` is used.
