### ISSUE TITLE
D3 completely changed and dropped the Base Interface?

### ISSUE THREAD

**Issue by brandonr1** [DefinitelyTyped/DefinitelyTyped#6006]
I just got the latest D3 definition file and it broke my existing code because it moved many methods (like interpolate) out of the Base interface and dropped the Base interface (now interpolate is just an exported function)?  Was that planned and discussed?  Mainly I was just curious because it's a real hassle to have to go back and refactor all my current code... the change that broke things looks like May 29th 2015 by gustavderdrache.  Thanks in advance for any explanations on the why of it all...it was just pretty shocking to get latest and have it break things in such a big way.

Where did partition layout go?  Something has to be hosed with what was done on May 29th...partition layout is just gone now.

Also, I'm confused, because this shows the old structures: http://definitelytyped.org/docs/dcjs--dc/modules/d3.html

**Comment by vvakame** [comment]
@gustavderdrache ?

**Comment by gustavderdrache** [comment]
Yeah. It hurt pretty hard to refactor a lot of my code too (roughly ~10k lines of d3-heavy charting), but based on the comments I received when suggesting restructuring, it was necessary. The layering of interfaces in the old `D3` type was really tangled.

I have never seen that documentation page before, so I don't know where that comes from. It doesn't seem auto-generated, but I don't know who to ping to correct it.

Lastly, wow. I can't believe I missed an entire layout doing the restructuring. Doesn't seem too big, so I'll try to have a PR open later today.

**Comment by Ledragon** [comment]
+1 on the Base interface, I like injecting d3 as a constructor parameter, and I would love to have a type. Any way I can help, just let me know

**Comment by brandonr1** [comment]
Yeah, tangled seems like a good description for the existing stuff and thanks for the info.  I like that doc page, but it does create some confusion.

I'm not too keen on the loss of a base interface either, I'm making d3 directives in angularjs and wrapping up a lot of those exported functions in an interface(s) would be more appropriate I think.

Np on the layout, I could see there was a lot of work done, the effort is much appreciated.   

I reverted back for the moment, but I plan on shifting to the new typings as soon as I get a chance.

**Comment by gustavderdrache** [comment]
I prefer the nested namespaces (it matches d3's own organization), but the loss of the `Base` interface doesn't mean that d3 doesn't have a type anymore. You can accept an object with type `typeof d3`, and if you're looking for a subsection, you can look for `typeof d3.svg` or similar.

**Comment by Ledragon** [comment]
Coming back after a while. I did not know about the `typeof d3` trick, that is working perfectly for me. Thanks!
And I have to say, having types selection is great!

**Comment by tomwanzek** [comment]
As part of some legacy D3v3 issue clean-up, can this issue be please closed?

D3v4 has been released and supported with actively maintained definitions for several months now, so it would be great to have only current issues open for clarity.

Thanks in advance!

cc @gustavderdrache @andy-ms
