### ISSUE TITLE
Knex.js contains incorrect definition for json() method

### ISSUE THREAD

**Issue by demisx** [DefinitelyTyped/DefinitelyTyped#6014]
`json()` method can accept an optional second parameter `true` to create _jsonb_ type. See: http://knexjs.org/#Schema-json, but I believe this line https://github.com/borisyankov/DefinitelyTyped/blob/master/knex/knex.d.ts#L331 assumes only one parameter. This generates a warning on wrong number of arguments for this call:

``` ts
 table.json('data', true);
```

**Comment by demisx** [comment]
@yortus @tkrotoff Guys, I think the change to https://github.com/borisyankov/DefinitelyTyped/blob/master/knex/knex.d.ts#L331 should be this (see below). If this is correct, I'll go ahead and create a PR.

```js
json(columnName: string, jsonb?: boolean): ColumnBuilder;
```

**Comment by yortus** [comment]
@demisx LGTM

**Comment by taybin** [comment]
This can be closed as knex provides its own definitions now.
