### ISSUE TITLE
[@types/plotly.js] Config.setBackground type definition appears to be missing parentheses

### ISSUE THREAD

**Issue by jacobq** [DefinitelyTyped/DefinitelyTyped#60184]
I'm not sure how these were generated (automatically, I presume) or to whom I should mention this (@Domino987 @chrisgervang ?), but I noticed that there seems to be missing parentheses around the function form in the union type for `Config.setBackground` :
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ed7f7400fea8c9f286c24318dc615c523e5c4045/types/plotly.js/index.d.ts#L1587

```ts
//const broken: Pick<Config, 'setBackground'> = {
const broken: { setBackground: () => string | 'opaque' | 'transparent' } = {
  // Note () => string | 'opaque' | 'transparent' reduces to '() => string'
  setBackground: 'transparent', // TS2322: Type 'string' is not assignable to type '() => string'.
};
const fixed: { setBackground: (() => string) | 'opaque' | 'transparent' } = {
  setBackground: 'transparent', // OK!
};
// Flipping the order of these things gives a good clue:
// TS1385: Function type notation must be parenthesized when used in a union type.
type warning = { setBackground: 'opaque' | 'transparent' | () => string }; 
```

Given that the default value for this option is a (pre-defined/enum) string rather than a function that returns a string I think this type definition is a mistake. Am I wrong?
https://github.com/plotly/plotly.js/blob/3f6c0eba637dc5829a96d6bb768d1f78e61e30e0/src/plot_api/plot_config.js#L353-L363
(even in [v1.58](https://github.com/plotly/plotly.js/blob/v1.58.5/src/plot_api/plot_config.js#L346-L356))
(Related to https://github.com/plotly/plotly.js/issues/28)

**Comment by Domino987** [comment]
Could you create a PR to fix this? Thank you🙂

**Comment by jacobq** [comment]
> Could you create a PR to fix this? Thank you🙂

Oh, are these manually generated/maintained then? If so, I can make a PR once someone can confirm that this matches the API. The Plotly.js documentation is unfortunately rather incomplete.

**Comment by Domino987** [comment]
They are not but generated manually. And the bot merges PRS automatically though

**Comment by jacobq** [comment]
I was a little confused about how `setBackground` works so:

* I found [this example](https://codepen.io/etpinard/pen/JXagKL) of how to make background transparent ([from 2016](https://community.plotly.com/t/you-can-remove-the-white-background-of-the-graphics-background/933)), which actually doesn't use `setBackground` at all but rather `plot_bgcolor` and `paper_bgcolor`. ([similar advice on StackOverflow])
* I wrote this [demo on CodePen](https://codepen.io/jacobq_/pen/VwQLdWZ?editors=0010) to see what the current behavior is
(https://stackoverflow.com/questions/50853447/change-plot-background-color))
* Valid uses of `setBackground` appear to be:
  - Set to `'opaque'` which will cause the `plot_bgcolor` & `paper_bgcolor` to combine/blend with opaque white
  - Set to `'transparent'` which will cause the `plot_bgcolor` & `paper_bgcolor` to combine/blend with whatever is behind the plot container
  - Set to a function that takes arguments `[gd, bgColor]` and presumably uses `bgColor` (which I think is either `plot_bgcolor` or `paper_bgcolor`) to come up with some value and then call `gd._fullLayout._paper.style('background', /* resulting color here*/)`

See also:
https://github.com/plotly/plotly.js/blob/12069023b46b4583259a7cfba295e1e653c15266/src/plot_api/plot_api.js#L503-L506

I'll make a PR shortly.
