### ISSUE TITLE
lat and lng isn't a function

### ISSUE THREAD

**Issue by german-eycon** [DefinitelyTyped/DefinitelyTyped#60306]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@types/google.maps@3.48.8` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@types/google.maps/index.d.ts b/node_modules/@types/google.maps/index.d.ts
index e4d517b..5b3895f 100755
--- a/node_modules/@types/google.maps/index.d.ts
+++ b/node_modules/@types/google.maps/index.d.ts
@@ -3104,11 +3104,11 @@ declare namespace google.maps {
     /**
      * Returns the latitude in degrees.
      */
-    lat(): number;
+    lat: number;
     /**
      * Returns the longitude in degrees.
      */
-    lng(): number;
+    lng: number;
     /**
      * Converts to JSON representation. This function is intended to be used via
      * <code>JSON.stringify</code>.
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by danmana** [comment]
On `LatLng` the lat/lng properties are functions - see docs: https://developers.google.com/maps/documentation/javascript/reference/coordinates#LatLng.lat  
Maybe you are trying to use `LatLngLiteral` which has numbers for lat/lng ?

**Comment by jwilkey** [comment]
But PlaceResult, the type used with the Places API, PlaceResult.geometry.location is a LatLng, with function types, which is incorrect

**Comment by vlafranca** [comment]
I confirm lat lng should not be typed as functions but as number please

**Comment by wangela** [comment]
`google.maps.LatLng.lat()` and `google.maps.LatLng.lng()` are functions, as @danmana points out. This issue should be closed.
