### ISSUE TITLE
[@types/prettier] IsTuple<Remain> when build

### ISSUE THREAD

**Issue by thinhSP** [DefinitelyTyped/DefinitelyTyped#60324]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/60323

<div type='discussions-op-text'>

<sup>Originally posted by **thinhbuihong** May 13, 2022</sup>
Hi, 

I'm trying to build project and got this error,  I wonder if you could help me with this?
![image](https://user-images.githubusercontent.com/45941660/168251206-53ec47b8-64c3-46cb-818e-1d119c95ef1a.png)
</div>

**Comment by Dmitriy-Storozhenko** [comment]
I'm trying to revert to using some previous version but I have it as a dependency in another library, I'm downgrading it's version until the one which uses some working prettier version...

**Comment by scoplin** [comment]
I received the same error in a project of mine using AWS cdk/jsii.  Pinning to 2.6.0 fixed it.

The jsii tool appears to be using typescript 3.9.10, so I suspect https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59690 is the likely culprit as it apparently pushes the minimum typescript version to 4.2 -- not something I would have expected in a patch release.

**Comment by jakebailey** [comment]
This package has been removed from DT and is now typed upstream.
