### ISSUE TITLE
[@types/video.js] missing Vhs.xhr.beforeRequest

### ISSUE THREAD

**Issue by WillSquire** [DefinitelyTyped/DefinitelyTyped#60426]
Video.js typings are missing `Vhs.xhr.beforeRequest`, documented here: https://github.com/videojs/http-streaming#vhsxhr.  Since Vhs is included in Video.js by default, this seems like the best place to put it.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@types/video.js/index.d.ts b/node_modules/@types/video.js/index.d.ts
index 0683f71..026bdf5 100755
--- a/node_modules/@types/video.js/index.d.ts
+++ b/node_modules/@types/video.js/index.d.ts
@@ -6083,6 +6083,12 @@ declare namespace videojs {
         url: string;
         rawRequest: XMLHttpRequest;
     }
+
+    const Vhs: {
+      xhr: {
+        beforeRequest: (options: XhrOptions) => void;
+      };
+    };
 }
 
 /**
```

**Comment by princefishthrower** [comment]
@WillSquire - this should be resolved in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62538
