### ISSUE TITLE
Java Syntax Highlighting - NetBeans Plugin

### ISSUE THREAD

**Issue by geekdenz** [DefinitelyTyped/DefinitelyTyped#6047]
Sorry, if this is the wrong place to post this, but I'm trying to get help wherever possible.

I'm researching how to easiest extend NetBeans to do syntax highlighting and code completion in the IDE. I found https://github.com/palantir/eclipse-typescript . Do you think there is a way the Eclipse efforts can be extended/re-used instead of re-inventing the wheel?

**Comment by tkrotoff** [comment]
Not the right place, please close this issue. Just search for "NetBeans TypeScript" on Google.
Found https://github.com/Everlaw/nbts and https://netbeans.org/bugzilla/show_bug.cgi?id=233197, see also https://en.wikipedia.org/wiki/TypeScript#IDE_and_editor_support

**Comment by geekdenz** [comment]
Sorry, the issue had already resolved itself and I had forgotten I needed to close it here.
