### ISSUE TITLE
Readme is not generated correctly

### ISSUE THREAD

**Issue by Maxim-Mazurok** [DefinitelyTyped/DefinitelyTyped#60470]
On the NPM page: https://www.npmjs.com/package/@types/gapi.client.sheets

It says "Dependencies: [@types/maxim_mazurok__gapi.client.sheets](https://npmjs.com/package/@types/maxim_mazurok__gapi.client.sheets)", but that dependency doesn't exist. The correct dependency is https://www.npmjs.com/package/@maxim_mazurok/gapi.client.sheets

There's no README for @types/gapi.client.sheets in DT repo right now, so I assume it's auto-generated? How can I fix this?

**Comment by jakebailey** [comment]
Old issue, but checking newer packages, this isn't a problem anymore.
