### ISSUE TITLE
Can't make a pull request

### ISSUE THREAD

**Issue by hitriyvalenok** [DefinitelyTyped/DefinitelyTyped#60698]
Hello there. I am getting the next error on attempt to make a pull request:
> Can't create a new pull request: Push failed: remote: Permission to DefinitelyTyped/DefinitelyTyped.git denied to hitriyvalenok. unable to access 'https://github.com/DefinitelyTyped/DefinitelyTyped/': The requested URL returned error: 403

What's wrong with that? Thank you!

**Comment by MysteryBlokHed** [comment]
It seems like you're trying to push directly to `DefinitelyTyped/DefinitelyTyped` instead of your own fork. Try forking the repo and pushing your changes to a branch there 😄
