### ISSUE TITLE
Outdated `pretty-format` package causing downstream high CVE detected by trivy

### ISSUE THREAD

**Issue by KenjiDuggan** [DefinitelyTyped/DefinitelyTyped#60695]
Hey guys, 
I'm working on a project that uses `@types/jest` package, I have reason to believe that your `pretty-format` package may be outdated, it will require a bump I think. This causes a downstream dependency issue that raises a high CVE since the `ansi-regex` package is on an unstable version: 
![Screen Shot 2022-06-06 at 5 28 43 PM](https://user-images.githubusercontent.com/35086886/172252393-5832a879-5e8f-489b-9a58-c1ffb39e4152.png)
The current pretty-format leads us to having ansi-regex version 5.0.0 which gives a high CVE, lemme know if I am wrong here(new to bumping packages)!

**Comment by jakebailey** [comment]
This is no longer a problem, from what I can tell.
