### ISSUE TITLE
[@types/async-retry] Broken types

### ISSUE THREAD

**Issue by mindhaq** [DefinitelyTyped/DefinitelyTyped#60823]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/60193

<div type='discussions-op-text'>

<sup>Originally posted by **Morriz** May  5, 2022</sup>
Hi, I think commit 6f77b38 broke async-retry. We get build errors now:
```
#12 38.96   Object literal may only specify known properties, and 'maxTimeout' does not exist in type 'WaitTillAvailableOptions'.
[547](https://github.com/redkubes/otomi-core/runs/6303461374?check_suite_focus=true#step:6:547)
#12 38.96 src/common/k8s.ts(197,5): error TS2322: Type '{ retries: number; maxTimeout: number; }' is not assignable to type 'Options'.
[548](https://github.com/redkubes/otomi-core/runs/6303461374?check_suite_focus=true#step:6:548)
#12 38.96   Object literal may only specify known properties, and 'retries' does not exist in type 'Options'.
```
But those are part of the official published interface: https://github.com/vercel/async-retry#readme</div>

**Comment by rdsedmundo** [comment]
@mindhaq can you re-open this?

It's still not working, workaround is: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6f77b38130593a06e1988f1d3df162823ae186af#commitcomment-73774224
