### ISSUE TITLE
ckeditor__ckeditor5-engine: Wrong typing for DataController.processor

### ISSUE THREAD

**Issue by mmichaelis** [DefinitelyTyped/DefinitelyTyped#60965]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c4ff2006e60d182dafb5fe5423702257fb09a36e/types/ckeditor__ckeditor5-engine/src/controller/datacontroller.d.ts#L75

This typing is wrong, as can be seen here:

[Class DataController (engine/controller/datacontroller~DataController) - CKEditor 5 API docs](https://ckeditor.com/docs/ckeditor5/34.1.0/api/module_engine_controller_datacontroller-DataController.html#member-processor)

Thus, it should be `DataProcessor` rather than `HtmlDataProcessor`.

**Comment by berghall** [comment]
Found this comment in the typings:
```
 /**
  * Data processor used during the conversion.
  * Same instance as {@link #htmlProcessor} by default. Can be replaced at run time to handle different format, e.g. XML or Markdown.
 */
processor: HtmlDataProcessor;
```

Relevant?

**Comment by mmichaelis** [comment]
> Found this comment in the typings:
> 
> ```
>  /**
>   * Data processor used during the conversion.
>   * Same instance as {@link #htmlProcessor} by default. Can be replaced at run time to handle different format, e.g. XML or Markdown.
>  */
> processor: HtmlDataProcessor;
> ```
> 
> Relevant?

Hi,

not really. It just means, that by default, CKEditor 5 comes with a `HtmlDataProcessor`. But whatever you choose as your data-representation, may replace this. A valid value is, for example, the [GFMDataProcessor](https://ckeditor.com/docs/ckeditor5/34.2.0/api/module_markdown-gfm_gfmdataprocessor-GFMDataProcessor.html), when your data-representation is Markdown.

Thus, the type should be widened here to any instance of a [DataProcessor](https://ckeditor.com/docs/ckeditor5/34.2.0/api/module_engine_dataprocessor_dataprocessor-DataProcessor.html).

**Comment by jakebailey** [comment]
This package has been removed from DT.
