### ISSUE TITLE
FBSDK broke

### ISSUE THREAD

**Issue by pocesar** [DefinitelyTyped/DefinitelyTyped#6096]
The type for FBUIParams introduced in a new patch (https://github.com/borisyankov/DefinitelyTyped/commit/85df2c157bd54fea536626066bda175c0a46cbad) broke everything in TS 1.6. When doing FB.ui calls, it assumes PayDialogParams, always:

``` typescript
FB.ui({
  method: 'share_open_graph',
  action_type: 'og.likes',
  action_properties: JSON.stringify({
      object:'https://developers.facebook.com/docs/',
  })
}, function(response){});
```

most of the examples provided by FB in their [reference docs](https://developers.facebook.com/docs/sharing/web) now fail

**Comment by vvakame** [comment]
please send a pull request. I'll review it.
