### ISSUE TITLE
electron ipc duplicate identifier

### ISSUE THREAD

**Issue by seanzer** [DefinitelyTyped/DefinitelyTyped#6104]
I have an electron project that I compile using gulp-tsb in one pass. Some files reference github-electron-renderer.d.ts and others reference github-electron-main.d.ts. Unfortunately, the duplicate definition of ipc causes some errors which takes away from the advantage of having a d.ts to begin with. 

Has anyone else seen this issue?

**Comment by vvakame** [comment]
@jedmao ?

**Comment by jedmao** [comment]
I haven't; though, I don't actually use these definitions. I just created them because I was frustrated with the lack of documentation. Sorry I can't provide any more support than that. Maybe somebody else is using it?

**Comment by elisee** [comment]
This can be closed, the definition files have been merged into a single one.

**Comment by seanzer** [comment]
This specific issue is resolved with #7121, even though there are new issues being tracked. Closing.
