### ISSUE TITLE
@types/react-copy-to-clipboard 404 in npm

### ISSUE THREAD

**Issue by zombieJ** [DefinitelyTyped/DefinitelyTyped#61041]
ref: https://github.com/ant-design/ant-design/runs/7143113588?check_suite_focus=true

> npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types/react-copy-to-clipboard/-/react-copy-to-clipboard-5.0.3.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@types/react-copy-to-clipboard@https://registry.npmjs.org/@types/react-copy-to-clipboard/-/react-copy-to-clipboard-5.0.3.tgz' is not in this registry.

Issue #61032 is closed for `@types/eslint` but still exist one need restore. Please check, thx.

**Comment by jcesarmobile** [comment]
seems to be working fine 
there was a problem on npm that caused missing tarballs and was already fixed by them
https://status.npmjs.org/incidents/6wr25yb0b2dd
