### ISSUE TITLE
infrastructure: `npm test` fails when there are no TypeScript installs in ~/.dts

### ISSUE THREAD

**Issue by giact** [DefinitelyTyped/DefinitelyTyped#61184]
[A recent commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/f1747d083e99749f676054711ea6948e107eec51) has added the `NODE_OPTIONS="--require source-map-support/register"` environment variable to the `npm test` script.

This causes `dtslint` to fail when `~/.dts` has no TypeScript installations, e.g.

```shell
rm -fr ~/.dts/typescript-installs
npm test base-64
```

Will error out with `Error: Cannot find module 'source-map-support/register'`

This because `@definitelytyped/dtslint` calls `installAllTypeScriptVersions()` in `@definitelytyped/utils` which ends up `exec()`ing `"npm install --ignore-scripts --no-shrinkwrap --no-package-lock --no-bin-links"` with the same environment, looking for an inexistent module in the destination folder for the installation

I have two possible solutions:

1. Update the README to instruct developers to run `npx dtslint --installAll` before their first run of `npm test`. But I personally would not know where in the README that would be more appropriate.
2. Patch `DefinitelyTyped-tools` to remove the `NODE_OPTIONS` variable from the environment like I did here: https://github.com/microsoft/DefinitelyTyped-tools/compare/master...giact:DefinitelyTyped-tools:typescript-installer

If you like the second option, should I just send a pull request to that other repo?

**Comment by hellomusa** [comment]
FYI, running `npx dtslint --installAll` and then `npm test` resulted in the following error for me regarding TS version:
```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.8.0

YOUR TYPESCRIPT VERSION: 4.8.0-dev.20220711

Please only submit bug reports when using the officially supported version.

=============
```

**Comment by sandersn** [comment]
@hellomusa The latter error comes from eslint, which I just added a couple of weeks ago. I tried to silence the error when I set up eslint, but obviously failed. I'll try again next time I get @JoshuaKGoldberg to help me.

@giact can you open an issue on microsoft/DefinitelyTyped-tools, which now contains dtslint? I think your removal of NODE_OPTIONS is the best fix, so a PR would be welcome as well.

**Comment by giact** [comment]
@sandersn thank you, I created the PR: https://github.com/microsoft/DefinitelyTyped-tools/pull/502
