### ISSUE TITLE
[@types/node] Missing all Web Crypto API

### ISSUE THREAD

**Issue by LoKy-dev** [DefinitelyTyped/DefinitelyTyped#61212]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/61211

<div type='discussions-op-text'>

<sup>Originally posted by **LoKy-dev** July 12, 2022</sup>
I'm using the SubtleCrypto API on a project to generate custom JWT signed with RS256 algorithm and by doing so i found out that the whole webcrypto class is missing from the type definitions.

Since this feature was added in both v15 and v16 (now on LTS) not having those types breaks the project building building process of the tools that i'm working now.
I could use `// @ts-ignore` to get it working (because the underlying API code exist) but thats feels like sealing a wound with duct tape.

Example of the error
```typescript
// TS2339: Property 'subtle' does not exist on type 'typeof webcrypto'.
const key = await webcrypto.subtle.importKey(
	"jwk", jwk,
	{
		name: 'RSASSA-PKCS1-v1_5',
		hash: 'SHA-256',
	},
	false, [ "sign" ]
)
```

Offical Node.js [doc](https://nodejs.org/docs/latest-v16.x/api/crypto.html#cryptowebcrypto), Web Crypto API [doc](https://nodejs.org/docs/latest-v16.x/api/webcrypto.html)</div>

**Comment by jhmaster2000** [comment]
PR #60778 has been merged and already live on `@types/node@18.0.4`
