### ISSUE TITLE
[@types/jsdom] Module '"parse5"' has no exported member 'ElementLocation'

### ISSUE THREAD

**Issue by lmeerma** [DefinitelyTyped/DefinitelyTyped#61248]
Using the latest version of jsdom (20.0.0) and @types/jsdom (16.2.14) gives the following error:

```
node_modules/@types/jsdom/base.d.ts:5:10 - error TS2305: Module '"parse5"' has no exported member 'ElementLocation'.

import { ElementLocation } from "parse5";
```
If still needed, `ElementLocation` can be imported from `parse5/index`. JSDOM v20.0.0 ships with the latest version of parse5 (7.0.0)

**Comment by birgersp** [comment]
Can someone post a workaround? Downgrade jsdom, perhaps. What version would you suggest?

**Comment by olivier-drieux** [comment]
Going back to "jsdom": "^19.0.0" works for me.

**Comment by olivier-drieux** [comment]
> Can someone post a workaround? Downgrade jsdom, perhaps. What version would you suggest?

g back to "jsdom": "^19.0.0" works for me.

**Comment by mrdrogdrog** [comment]
The dependency on parse5 should be removed. 
According to https://www.npmjs.com/package/@types/parse5 the types for parse5 are in the lib itself.

**Comment by mrdrogdrog** [comment]
Created a PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61393

**Comment by SimenB** [comment]
`@types/jsdom@20` is released, so this issue can be closed

**Comment by OmShiv** [comment]
Using both 
```js
"@types/jsdom": "^20.0.0",
"jsdom": "^20.0.0",
```
...causes me another problem:
```
[!] Error: Cannot find module 'rollup-plugin-node-resolve'
```

**Comment by leegee** [comment]
Using `jsdom@22.0.0` and `parse5@^7.1.2` (as in the JSDOM 22.0.0 `package.json`), the error persists:
```bash
../../node_modules/@types/jsdom/base.d.ts:5:10 - error TS2305: Module '"parse5"' has no exported member 'ElementLocation'.

5 import { ElementLocation } from "parse5";
```

**Comment by captDaylight** [comment]
With this I'm no longer getting the problem:
 ``` json
    "@types/jsdom": "^21.1.1",
    "jsdom": "^22.1.0",
```

**Comment by leegee** [comment]
I have been using the below -- I'll try the above, thanks!
```
"@types/jsdom": "^16.2.14",
"jsdom": "^20.0.0",
```
