### ISSUE TITLE
ui-grid: enableGridMenu option is missing under gridoptions

### ISSUE THREAD

**Issue by ashwin027** [DefinitelyTyped/DefinitelyTyped#6133]
Options enableGridMenu and useExternalFiltering is missing under grid options. 

         /**
         * False by default. When enabled, this adds a settings icon in the top right of the grid, 
         * which floats above the column header. The menu by default gives access to show/hide columns, 
         * but can be customized to show additional actions.
         * @default false
         */
         enableGridMenu?: boolean;

          /**
             * Disables client side filtering. When true, handle the filterChanged event and set data,
             * defaults to false
             * @default false
             */
            useExternalFiltering?: boolean;

Please let me know I can submit a pull request for both these options.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by ashwin027** [comment]
PR #6187

**Comment by ashwin027** [comment]
PR #6202

**Comment by tandvu** [comment]
enableGridMenu does not work.  

http://plnkr.co/edit/?p=preview

When I set enableGridMenu to false, it still shows the menu

Tan

**Comment by AbhishekGarg** [comment]
@tandvu Please report it as an issue with the [ui-grid repo](https://github.com/angular-ui/ui-grid).
PS: It is working as expected, atleast in the plunker, grid menu is not shown.

@vvakame I hope this issue can be closed as the PR has been merged.
