### ISSUE TITLE
Add immutable-js library

### ISSUE THREAD

**Issue by zdychacek** [DefinitelyTyped/DefinitelyTyped#6139]
Hi,

I am posting link: https://github.com/facebook/immutable-js/blob/master/type-definitions/Immutable.d.ts.

Thanks,

O.

**Comment by leonyu** [comment]
Someone made a PR #6623 currently pending licensing issue

**Comment by andrerpena** [comment]
Immutable has type definitions already, inside the NPM package. The link is provided by @zdychacek.

I think we can close this issue

**Comment by leonyu** [comment]
I believe the problem has been resolved in TypeScript 2.0 for most user. Prior to 2.0 you had to manually copy those definition files into your project for it to work properly. Now `tsc` automatically resolves it. 

There might be some rare use cases where you still need to apply special treatment, but I am not aware of it.
