### ISSUE TITLE
[leaflet] 1.8: help needed with PR

### ISSUE THREAD

**Issue by someonewithpc** [DefinitelyTyped/DefinitelyTyped#61444]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/61360

<div type='discussions-op-text'>

<sup>Originally posted by **someonewithpc** July 20, 2022</sup>
I started a PR here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61339 but my TypeScript skills aren't very good yet, so while I was able to make it work for me and make it pass all the local tests, some dependents' tests fail. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61339#issuecomment-1190425288</div>

**Comment by jonkoops** [comment]
This issue can be closed as #61339 is now merged.
