### ISSUE TITLE
Ui-grid: Missing options for infinite scroll

### ISSUE THREAD

**Issue by ashwin027** [DefinitelyTyped/DefinitelyTyped#6152]
Options 'infiniteScrollRowsFromEnd', 'infiniteScrollUp' and 'infiniteScrollDown' are missing from IGridOptions as part of the infiniteScroll module.

            infiniteScrollRowsFromEnd: number;
            infiniteScrollUp: boolean,
            infiniteScrollDown: boolean,

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by ashwin027** [comment]
PR #6192

**Comment by AbhishekGarg** [comment]
Guess we can close this issue, PR being merged.
