### ISSUE TITLE
node_modules/@types/mime/Mime.d.ts:1:13 - error TS1005: '=' expected.

### ISSUE THREAD

**Issue by WilliamJJXue** [DefinitelyTyped/DefinitelyTyped#61582]
node_modules/@types/mime/Mime.d.ts:1:13 - error TS1005: '=' expected.

1 import type { TypeMap } from './index';
              ~

node_modules/@types/mime/Mime.d.ts:1:30 - error TS1005: ';' expected.

1 import type { TypeMap } from './index';
                               ~~~~~~~~~


Found 2 errors.

**Comment by NaveenThiyagarajan** [comment]
+1

**Comment by rahulgoyal-sd** [comment]
+1

**Comment by danielturriago** [comment]
Install version 2.0.3 of @types/mime to fix this error

**Comment by acheek24** [comment]
Installed above and get the same error on serve-static

node_modules/@types/serve-static/node_modules/@types/mime/Mime.d.ts:1:13

**Comment by lalobo** [comment]
installing @types/express also has this problem as it installs the latest version of @types/mime

**Comment by dheerajkhatri** [comment]
Did anyone find any solution for it, facing the same problem out of the blue?

**Comment by dheerajkhatri** [comment]
@WilliamJJXue can you tag this issue as high priority if possible?

**Comment by nirlav** [comment]
Same problem for me, any workaround?

**Comment by WilliamJJXue** [comment]
@dheerajkhatri  Sorry, I don't have this permission;
you can use this follow to solution https://github.com/DefinitelyTyped/DefinitelyTyped/issues/61582#issuecomment-1206710728；

**Comment by acheek24** [comment]
For me, resolved by installing 2.0.3 directly and dropping back a minor version of a dependency (foundation pact) that was pulling in express and mime transitively.

**Comment by gerlocian** [comment]
We've found that our project is using version 3.4.5 of typescript. The feature for `import type` was added in version 3.8. If your project is using a version below 3.8 of typescript, try updating the version to 3.8.3 or latest.

**Comment by gerlocian** [comment]
In addition, if you are unable to update your version of typescript, I also found that backing up the version of `@types/mime` to version 3.0.0 also fixes this issue. You can do this for your project and dependencies by utilizing this: https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions

**Comment by dheerajkhatri** [comment]
> We've found that our project is using version 3.4.5 of typescript. The feature for `import type` was added in version 3.8. If your project is using a version below 3.8 of typescript, try updating the version to 3.8.3 or latest.

it has worked for me as well but if we are using fixed version of library and code was stable since quite a time then how come suddenly it starts to break?

**Comment by droidappsfactory** [comment]
@types/serve-static has dependencies 
"dependencies": {
    "@types/mime": "*",
    "@types/node": "*"
  },
which is installing latest mime types regardless of typescript version of project

**Comment by droidappsfactory** [comment]
In my case typescript 3.4.5 and expressjs 4.16.3 , @type/express 4.16.0 

@type/express has dependencies declared as

```
"dependencies": {
    "@types/body-parser": "*",
    "@types/express-serve-static-core": "*",
    "@types/serve-static": "*"
}
```
which is installing latest serve-static types which is installing latest mime types which is not supported for typescript version

fixed the issue by installing @types/serve-static with required version

**Comment by kasingal** [comment]
This should be marked as high priority !!

**Comment by f3arnil** [comment]
Added "@types/mime": "3.0.0" and for me this helped - 3.0.1 for some reason also fail

**Comment by Semigradsky** [comment]
Looks like you just use old version of TypeScript. So possible solutions:
- update `TypeScript` to 3.8+
- or downgrade `@types/mime`

**Comment by jakebailey** [comment]
These versions are well outside our documented support window; closing.
