### ISSUE TITLE
auto generated tslint.json file fails PR checklist

### ISSUE THREAD

**Issue by MattiasMartens** [DefinitelyTyped/DefinitelyTyped#61653]
when auto generating a types package with the command `npx dts-gen --dt --name react-size-reporter --template module`, i saw this `tslint.json` file generated:

```
{ "extends": "dtslint/dt.json" }
```

but when i went to create a pull request, this item appeared in it:

> tslint.json [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) { "extends": "@definitelytyped/dtslint/dt.json" }, and no additional rules.

why does the GitHub PR checklist require `@definitelytyped/dtslint/dt.json` when the `dts-gen` command supplies `dtslint/dt.json`? moreover, which one is actually correct?

## P.S.

i also want to mention -- in case you can help -- that when i open the DefinitelyTyped project in VSCode my `.d.ts` files fail linting with:

```
Definition for rule 'no-dead-reference' was not found.eslint(no-dead-reference)
Definition for rule 'no-const-enum' was not found.
```

this is probably some kind of global config issue but i couldn't figure out how to fix it from googling. do you have a fix for this?

**Comment by jakebailey** [comment]
tslint is no more.
