### ISSUE TITLE
Is this @deprecated needed?

### ISSUE THREAD

**Issue by albertwangnz** [DefinitelyTyped/DefinitelyTyped#61673]
Hi @BendingBender, @JounQin and @weswigham,

May I ask why we have this @deprecated annotation?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b6e4e463aa953c1d83e25afd9d368ead0400f614/types/file-saver/index.d.ts#L27

The annotation is detected by SonarQube rule typescript:S1874 as a code smell, but I don't think we need this annotation here.

Thank you.

Regards,
Albert

**Comment by JounQin** [comment]
See https://github.com/eligrey/FileSaver.js/blob/master/src/FileSaver.js#L22

**Comment by BendingBender** [comment]
Well, the point here is to make sure that users use the variant with the options object instead of the deprecated one with the flag. Why do you think that this is incorrect?

**Comment by BendingBender** [comment]
> See https://github.com/eligrey/FileSaver.js/blob/master/src/FileSaver.js#L22
> 
> But maybe it should be moved as first function overloading?

As far as I see it in the definition tests, only the deprecated variant is marked as such. So no need to change the order.

**Comment by albertwangnz** [comment]
> 

I agree. I am not good at JS/TS but I feel if we change the signature of a method, we should deprecate the old one and create a new one.

**Comment by BendingBender** [comment]
This is exactly what happened here.

**Comment by albertwangnz** [comment]
So, just to confirm my understanding.

The 3rd param used to be disableAutoBOM (optional & defaults to true).
Now, the 3rd param becomes { autoBom: false } and is mandatory.

I am right?

Thanks.

**Comment by JounQin** [comment]
> I agree. I am not good at JS/TS but I feel if we change the signature of a method, we should deprecate the old one and create a new one.

The type definition align with the source codes, if you have such unexpected feeling, you should raise an issue to the original repository instead of current definition.

Also, it could an issue from SonarQube as @BendingBender pointed out at https://github.com/DefinitelyTyped/DefinitelyTyped/issues/61673#issuecomment-1212585704

**Comment by JounQin** [comment]
The 3rd parameter is never mandatory.

**Comment by albertwangnz** [comment]
> The 3rd parameter is never mandatory.

So, it used to defaults true, and now defaults false?

**Comment by JounQin** [comment]
> > The 3rd parameter is never mandatory.
> 
> So, it used to default true, and now defaults false?

Can you read the source codes by yourself please?

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/61673#issuecomment-1212584031

**Comment by BendingBender** [comment]
It's hard to tell how SonarQube interperts this definition, I'm not even sure whether they use the TS compiler to infer types but I suspect they only have some home-grown static analysis.

**Comment by BendingBender** [comment]
@albertwangnz We are not the package owners, we only maintain the TS definitions. If you want anything changed about how the package works, please reports it [in their issue tracker.](https://github.com/eligrey/FileSaver.js)

**Comment by JounQin** [comment]
> It's hard to tell how SonarQube interperts this definition, I'm not even sure whether they use the TS compiler to infer types but I suspect they only have some home-grown static analysis.

They do use TypeScript inside https://github.com/SonarSource/SonarJS/blob/master/eslint-bridge/src/linting/eslint/rules/deprecation.ts#L26

**Comment by albertwangnz** [comment]
Hi @BendingBender and @JounQin , 

Sorry to bother you. I think you are right. It looks like a SonarQube issue.

I will close this issue here.

Thanks a lot for so so fast responses.

Cheers.

Regards,
Albert
