### ISSUE TITLE
[dtslint] Using eslintrc for dtslint causes errors when running vanilla eslint (including IDE extensions)

### ISSUE THREAD

**Issue by thw0rted** [DefinitelyTyped/DefinitelyTyped#61764]
As requested in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61104, I'm filing this as a new issue.

Since that PR was merged, opening DT in an IDE that runs eslint via a plugin (like VSCode), or running vanilla eslint manually at the command line (try e.g. `npm exec eslint types/{some-package}/*.ts`) will fail with

> 1:1  error  Definition for rule 'no-dead-reference' was not found  no-dead-reference
> 1:1  error  Definition for rule 'no-const-enum' was not found      no-const-enum

Presumably, this is because dtslint uses `.eslintrc.json` for rules, even though it is not, strictly speaking, eslint.  Should dtslint keep dts-only rules under a separate key?  Or perhaps just use a different file altogether?  Alternately, is it possible to configure vanilla eslint to use dtslint as a plugin and/or parser?

**Comment by philting** [comment]
Totally agreed. I'm also using the ESLint plugin with VSCode, which I believe is a pretty common development setup. Spent a good amount of time thumbing through the `README` and open issues to see if I missed something in the installation. Definitely feel like calling the file `.eslintrc.json` is somewhat misleading if it's not actually an ESLint config file.

**Comment by zucchinho** [comment]
like @pting-me this tripped me up for a good half hour, definitely needs resolving one way or the other, great many devs use vscode+eslint plugin

**Comment by daelmaak** [comment]
Since the default ESLint extension doesn't work with DT's linting set up , is there another way to get lint assistance in VSCode then?

**Comment by jakebailey** [comment]
Eslint should now be working these days
