### ISSUE TITLE
error: A type predicate's type must be assignable to its parameter's type while doing npm i after @type/lodash:4.14.183

### ISSUE THREAD

**Issue by SatheeshKumarBalu** [DefinitelyTyped/DefinitelyTyped#61772]
After upgraded to latest version @type/lodash:4.14.183
got error while doing npm i
node_modules/@types/lodash/common/lang.d.ts:577:74 - error TS2677: A type predicate's type must be assignable to its parameter's type
like below
![image](https://user-images.githubusercontent.com/34299834/185072537-638d9c9a-8cc2-40ba-8063-637c576e871e.png)

**Comment by cppmx** [comment]
I have the same issue with lodash-es 4.17.21:

```bash
ERROR in node_modules/@types/lodash/common/lang.d.ts(577,74): error TS2677: A type predicate's type must be assignable to its parameter's type.
  Type 'EmptyObjectOf<T>' is not assignable to type 'T'.
    Type 'EmptyObject<T>' is not assignable to type 'T'.
```

**Comment by maulikprajapati** [comment]
I have exact issue. version: `@type/lodash:4.14.183`

**Comment by yahnic** [comment]
I have some issues with 14..14.21.

**Comment by ABaranchugov** [comment]
I was fix version for package @types/lodash.
It's work!

`"@types/lodash": "4.14.149",`

**Comment by naveedshahji** [comment]
> ```shell
> ERROR in node_modules/@types/lodash/common/lang.d.ts(577,74): error TS2677: A type predicate's type must be assignable to its parameter's type.
>   Type 'EmptyObjectOf<T>' is not assignable to type 'T'.
>     Type 'EmptyObject<T>' is not assignable to type 'T'.
> ```

same issue

**Comment by maulikprajapati** [comment]
@ABaranchugov I've already fixed version `4.14.149`, still getting this error.

**Comment by hammadrafiqe2** [comment]
@SatheeshKumarBalu i just removed the the carret `^` from `^4.14.179` and it works for me.

**Comment by SatheeshKumarBalu** [comment]
Thanks @hammadrafiqe2 .. Issue resolved for me by installing "@types/lodash": "4.14.182",

**Comment by ChrisWillems** [comment]
> I have exact same issue. version: `@type/lodash:4.14.149`

Check the dependencies to see if other libraries are using the latest version of @types/lodash ( npm i ) 
For me it was the scss-bundle library which was using the latest version of @types/lodash and caused the error.

**Comment by Xenya0815** [comment]
You mainly talk about workarounds by using old versions.

Is there also a fix planned so that overwriting the types is no longer necessary as soon as possible?

**Comment by rahossain** [comment]
hello, 
I use  "lodash-es": "4.17.11" in my package.json but it makes jenkin build failed  but jenkin build was working fine few days ago. But locally npm lodash-es compilation process works fine

now i am getting jenkin build errors :
..\Dev\Build\src\Web\node_modules\@types\lodash\common\lang.d.ts(577,74): error TS2677: Build:A type predicate's type must be assignable to its parameter's type.

what should i do to make jenkin build success?

**Comment by rahossain** [comment]
> Reference

how you fix that?

**Comment by rahossain** [comment]
> I have the same issue with lodash-es 4.17.21:
> 
> ```shell
> ERROR in node_modules/@types/lodash/common/lang.d.ts(577,74): error TS2677: A type predicate's type must be assignable to its parameter's type.
>   Type 'EmptyObjectOf<T>' is not assignable to type 'T'.
>     Type 'EmptyObject<T>' is not assignable to type 'T'.
> ```

How you fix that?

**Comment by cppmx** [comment]
> > I have the same issue with lodash-es 4.17.21:
> > ```shell
> > ERROR in node_modules/@types/lodash/common/lang.d.ts(577,74): error TS2677: A type predicate's type must be assignable to its parameter's type.
> >   Type 'EmptyObjectOf<T>' is not assignable to type 'T'.
> >     Type 'EmptyObject<T>' is not assignable to type 'T'.
> > ```
> 
> How you fix that?

In reviewing the package.json I found that the `types/lodash` library was also being added and that was causing the conflict. I removed the `types/lodash` library and left only `lodash-es`, that solved the problem.

**Comment by DoanVanThuong** [comment]
I have same issue.
 version: @type/lodash:4.14.118,  "lodash": "^4.17.20",

**Comment by nagendrareddysomannagari** [comment]
I have the same issue. I have added @types/lodash": "4.14.149" to package.json file and it has resolved the issue.

**Comment by RushPVA** [comment]
I have the same issue. I tried use old version and my builds were randomly succesfull or failed.
Only stable solution for me is using of tag version:
        "@types/lodash-es": "ts3.2",
        "@types/lodash": "ts3.2",
I use 3.2.x version of TypeScript, so it can be another tag in case of another version of TS.

**Comment by aalbericio** [comment]
I was unable to fix this issue so I ended up removing the devDependency.

**Comment by reinaldoborin** [comment]
> @SatheeshKumarBalu i just removed the the carret `^` from `^4.14.179` and it works for me.

Fixed for me, thank you.

**Comment by sajoku** [comment]
I ran into this error also and can't really seem to find a version of `@types/lodash` that fixes this.
I do however "solved" this by upgrading typescript itself.

```
-    "typescript": "^3.5.1",
+    "typescript": "^3.9.4",
```

**Comment by JimNflm** [comment]
I had the same issue and my solution was to match the version of '@types/node' with '@types/lodash'

"@types/lodash": "ts3.3"
"@types/node": "ts3.3"

**Comment by subham-spacer** [comment]
I dont have lodash in my package.json, but it is getting installed with version 4.17.21 due to which I am getting the above error. Can anyone please suggest how to fix?
<img width="931" alt="image" src="https://user-images.githubusercontent.com/111725153/234535642-c8b5dbc0-bd10-4928-9767-8215eeb96630.png">

**Comment by aijo** [comment]
> I dont have lodash in my package.json, but it is getting installed with version 4.17.21 due to which I am getting the above error. Can anyone please suggest how to fix? <img alt="image" width="931" src="https://user-images.githubusercontent.com/111725153/234535642-c8b5dbc0-bd10-4928-9767-8215eeb96630.png">

Recently I got the same error as you. my case is come from dependency of jest. I noticed that @types/babel__traverse just release new version as 7.18.4 and I think it ve issue so I try to force using babel__traverse 7.18.3 and it work with my case.

**Comment by jhfgloria** [comment]
> > I dont have lodash in my package.json, but it is getting installed with version 4.17.21 due to which I am getting the above error. Can anyone please suggest how to fix? <img alt="image" width="931" src="https://user-images.githubusercontent.com/111725153/234535642-c8b5dbc0-bd10-4928-9767-8215eeb96630.png">
> 
> Recently I got the same error as you. my case is come from dependency of jest. I noticed that @types/babel__traverse just release new version as 7.18.4 and I think it ve issue so I try to force using babel__traverse 7.18.3 and it work with my case.

I have yet another problem. I started having this problem in CI this morning, and I don't have any dependency that uses this package. It's not present in any of the my yarn.lock (I have 2 Angular repos one importing the other), so there's no version for force... Anyone else?

```
[ ERROR ]  TypeScript: ./node_modules/@types/babel__traverse/index.d.ts:297:72
           A type predicate's type must be assignable to its parameter's
           type.Type 'NodePath<T>' is not assignable to type
           'NodePath<Node>'.Types of property 'hasNode' are incompatible.Type
           '() => this is NodePath<NonNullable<T>>' is not assignable to type
           '() => this is NodePath<NonNullable<Node>>'.Type predicate 'this is
           NodePath<NonNullable<T>>' is not assignable to 'this is
           NodePath<NonNullable<Node>>'.Type 'NodePath<NonNullable<T>>' is not
           assignable to type 'NodePath<NonNullable<Node>>'.Types of property
           'unshiftContainer' are incompatible.Type '<Nodes extends Node |
           readonly Node[]>(listKey: keyof { [P in keyof NonNullable<T> as
           NonNullable<T>[P] extends any[] ? P : never]: P; }, nodes: Nodes) =>
           NodePaths<...>' is not assignable to type '<Nodes extends Node |
           readonly Node[]>(listKey: "range" | "leadingComments" |
           "trailingComments" | "innerComments", nodes: Nodes) =>
           NodePaths<Nodes>'.Types of parameters 'listKey' and 'listKey' are
           incompatible.Type 'string' is not assignable to type 'keyof { [P in
           keyof NonNullable<T> as NonNullable<T>[P] extends any[] ? P :
           never]: P; }'.Type 'string' is not assignable to type 'keyof { [P in
           keyof NonNullable<T> as NonNullable<T>[P] extends any[] ? P :
           never]: P; }'.Type '"range"' is not assignable to type
           '(NonNullable<T>[P] extends any[] ? P : never) |
           (NonNullable<T>["type"] extends any[] ? "type" : never) |
           (NonNullable<T>["leadingComments"] extends any[] ? "leadingComments"
           : never) | ... 6 more ... | (NonNullable<...>["extra"] extends any[]
           ? "extra" : never)'.

    L296:   */
    L297:  >(callback: (path: NodePath) => path is NodePath<T>): NodePath<T> | n
    L298:  findParent(callback: (path: NodePath) => boolean): NodePath | null;
```

**Comment by rwaskiewicz** [comment]
The StencilJS team started to this this issue this morning as well:
```
[ ERROR ]  TypeScript: ./node_modules/@types/babel__traverse/index.d.ts:297:72
           A type predicate's type must be assignable to its parameter's type.Type 'NodePath<T>' is not assignable to
           type 'NodePath<Node>'.Types of property 'hasNode' are incompatible.Type '() => this is
           NodePath<NonNullable<T>>' is not assignable to type '() => this is NodePath<NonNullable<Node>>'.Type
           predicate 'this is NodePath<NonNullable<T>>' is not assignable to 'this is NodePath<NonNullable<Node>>'.Type
           'NodePath<NonNullable<T>>' is not assignable to type 'NodePath<NonNullable<Node>>'.Types of property
           'unshiftContainer' are incompatible.Type '<Nodes extends Node | readonly Node[]>(listKey: keyof { [P in
           keyof NonNullable<T> as NonNullable<T>[P] extends any[] ? P : never]: P; }, nodes: Nodes) => NodePaths<...>'
           is not assignable to type '<Nodes extends Node | readonly Node[]>(listKey: "leadingComments" |
           "trailingComments" | "innerComments" | "range", nodes: Nodes) => NodePaths<Nodes>'.Types of parameters
           'listKey' and 'listKey' are incompatible.Type 'string' is not assignable to type 'keyof { [P in keyof
           NonNullable<T> as NonNullable<T>[P] extends any[] ? P : never]: P; }'.Type 'string' is not assignable to
           type 'keyof { [P in keyof NonNullable<T> as NonNullable<T>[P] extends any[] ? P : never]: P; }'.Type
           '"leadingComments"' is not assignable to type '(NonNullable<T>[P] extends any[] ? P : never) |
           (NonNullable<T>["type"] extends any[] ? "type" : never) | (NonNullable<T>["leadingComments"] extends any[] ?
           "leadingComments" : never) | ... 6 more ... | (NonNullable<...>["extra"] extends any[] ? "extra" : never)'.

    L296:   */
    L297:  findParent<T extends t.Node>(callback: (path: NodePath) => path is NodePath<T>): NodePath<T> | null;
    L298:  findParent(callback: (path: NodePath) => boolean): NodePath | null;
```

I don't think that this is strictly related to lodash **(and deeply apologize for spamming previous watchers of this issue)**. I found this issue by googling the output, and am putting this comment here for viz.

It appears that for (us, the Stencil team) that `@types/babel__traverse` (which is the common thread in comments here) was updated in the last 24 hours - https://github.com/DefinitelyTyped/DefinitelyTyped/commit/a7da713fe6ebbb37d3d7128b46bf849436bac75b. `@types/babel__traverse` gets pulled in by Jest project, which might explain it's prevalence this morning.

For us, the temporary fix is to run `npm i -D -E @types/babel__traverse@7.18.3` (where 7.18.4 is the version that included the PR I linked to above).

**Comment by windsmasher** [comment]
it helped @rwaskiewicz, thanks a lot!

**Comment by b-abdallah** [comment]
it work @rwaskiewicz, thanks a lot!

**Comment by subham-spacer** [comment]
It help @rwaskiewicz , thanks a lot!!
