### ISSUE TITLE
Why do you not use submodule ?

### ISSUE THREAD

**Issue by j1i-ian** [DefinitelyTyped/DefinitelyTyped#61996]
Performance is so awful.

github types directory contents loading time is about 20s.

Git clone time is almost taking 2 minutes.

and that all jobs are just only for my 4 files on PR.

It excited to me fearing for build. 
I cannot perfectly understand your monolithic systems.

Git is designed for fast, contrasts svn. I wish you can resolve this problem without conflicting git philosophy.

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/13825203/187069141-fd659778-c583-45ae-a8d1-a6c2bd8334e8.png">

**Comment by j1i-ian** [comment]
I've checked repository size with github size like below:

`curl https://api.github.com/repos/DefinitelyTyped/DefinitelyTyped | jq '.size'`

and... value is 864MB

I think It is abnormal.

**Comment by SimonSchick** [comment]
This repo currently has 81k commits, perform integration tests between different types would be rather time consuming to setup and would probably drastically increase latency in CI and lead to contributor churn/frustration.

If you have concerns about the repo size you may perform a shallow clone `git clone -–depth 1 <URL>`.

Performs isn't ideal but given the amount of files this is to be expected, the good news is that the amount of files in this repo is going down as more and more people are starting to implement types meaning the problem isn't going to get substantially worse!
Perhaps the maintainers want to perform an archival of the repository at some point (eg. squash the first ~40k commits) and force push, although that might bring it's own issues.

What is your suggested approach to mitigating this issue?

**Comment by SimonSchick** [comment]
Also anectotally: `curl https://api.github.com/repos/torvalds/linux | jq '.size`

Comparing dt with linux might be bold, but linux is 3.7gb, and it seems to work well for them :)

**Comment by jakebailey** [comment]
Git has gained many features which help mitigate this, and they are documented in the readme.
