### ISSUE TITLE
Dependency of a type's dependency is not declared in this type's `package.json` error (`no-outside-dependencies`).

### ISSUE THREAD

**Issue by sentisso** [DefinitelyTyped/DefinitelyTyped#62083]
When I'm trying to run `npm test steamcommunity` to test the `steamcommunity` types (**no code changes**), I get this error:
```
=============
Error: .../DefinitelyTyped/node_modules/form-data/index.d.ts:1:1
ERROR: 1:1  no-outside-dependencies  File .../nodejs/DefinitelyTyped/node_modules/form-data/index.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.  See: https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/no-outside-dependencies.md

   at testTypesVersion (.../nodejs/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:235:11)
   at runTests (.../nodejs/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:197:7)
   at main (.../nodejs/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:83:5)
```

## Testing

Tested on 2 different systems:
- Arch linux (`5.19.4-arch1-g14-1`)
- and Oracle Linux Server 8.6 (`5.4.17-2136.309.5.el8uek.aarch64`)

using 3 different nodejs versions on each system:
- `15.14.0` (npm `7.7.6`),
- `16.17.0` (npm `8.5.15`)
- and `17.9.0` (npm `8.5.5`)

## Steps to reproduce:
1. clone the `DefinitelyTyped` repo and `cd` into it
2. `npm i`
3. `npm test steamcommunity`

Why is this happening? Obviously the `steamcommunity` types were published before, so why does it break now with no changes made?
I've got a few changes waiting for this package, so this is kinda obstructing the deploy :/

**Comment by sentisso** [comment]
The _source_ package [node-steamcommunity](https://github.com/DoctorMcKay/node-steamcommunity) itself doesn't reference `form-data` at all, but only **its' dependency depends** on `form-data`!

`steamcommunity` depends on [request](https://www.npmjs.com/package/request) and `request` depends on `form-data`, but why does this _nested dependency_ break the DefinitelyTyped testing?

**Comment by sentisso** [comment]
There [used to](https://github.com/DoctorMcKay/node-steamcommunity/issues/199) be a problem with the source package and the `form-data` dependency, but this is no longer relevant and the `form-data` requirement is not longer used.

Maybe the test somehow has an old version of the type's source package cached?

**Comment by chrift** [comment]
I am also getting this error. Did you manage to find a solution?

**Comment by jakebailey** [comment]
I don't think this is a bug in the current version of DT.
