### ISSUE TITLE
[@types/xrm] wrong signature on removeOnProcessStatusChange

### ISSUE THREAD

**Issue by maeg02** [DefinitelyTyped/DefinitelyTyped#62092]
Hi 

I found a problem with Xrm.ProcessFlow.ProcessManager.removeOnProcessStatusChange method, the parameter should be the same as the addOnProcessStatusChange

so in my opinion line  4485 should be changed to:

`removeOnProcessStatusChange(handler: Events.ContextSensitiveHandler): void;`

https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/formcontext-data-process/eventhandlers/removeonprocessstatuschange
https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/formcontext-data-process/eventhandlers/addonprocessstatuschange

**Comment by maeg02** [comment]
do you agree with me @daryllabar?

**Comment by daryllabar** [comment]
Submit a PR and I'll approve it
