### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by mschilde** [DefinitelyTyped/DefinitelyTyped#62158]
It looks like #62142 broke the build of a lot of packages. The error message is `Definition for rule 'no-bad-reference' was not found`.

**Comment by lamartire** [comment]
Every new PR has the error

**Comment by philting** [comment]
Looks like this has been reverted with #62165 and can be closed

**Comment by mschilde** [comment]
Thanks for the quick fix! Now everyone rebase please :-)
