### ISSUE TITLE
[jsonld] Frame may contain an array for '@id'

### ISSUE THREAD

**Issue by bartalusg** [DefinitelyTyped/DefinitelyTyped#62177]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62176

<div type='discussions-op-text'>

<sup>Originally posted by **bartalusg** September  9, 2022</sup>
Hi there,

According to the specs:

- https://www.w3.org/TR/json-ld11/#frame-objects
- https://www.w3.org/TR/json-ld11-framing/#matching-on-id

the '@id' property of a Frame could also be an array of IRIs. 

This feature is supported by the jsonld package, but the type definitions would require some update, I believe.
Is this possible/feasible?

Thank you!</div>

**Comment by Semigradsky** [comment]
I'll try to fix it over the weekend.
