### ISSUE TITLE
`npm i` fails due to ssh constraints on local network

### ISSUE THREAD

**Issue by gerardolima** [DefinitelyTyped/DefinitelyTyped#62202]
Due to network constraints, I cannot use ssh to connect to GitHub -- i.e I cannot `npm i types/hapi__hapi`. Is there any workaround?

**Comment by MysteryBlokHed** [comment]
`npm install` shouldn't use ssh afaik—is there a specific error you get when you try?

**Comment by gerardolima** [comment]
closed due to no-response
