### ISSUE TITLE
[@types/node] net.d.ts is missing Socket.resetAndDestroy()

### ISSUE THREAD

**Issue by bguezzie** [DefinitelyTyped/DefinitelyTyped#62298]
I'm running Node.js v18.9.0 and pulled in the latest @types/node (v18.7.18).  Back in v18.3.0 Node.js added the following:
`net.Socket.resetAndDestroy(): net.Socket`
(see: [Socket.resetAndDestroy()](https://nodejs.org/api/net.html#socketresetanddestroy))

However I'm not seeing that method in the types for Socket.  Right now I'm having to use a ts-ignore, but I'd rather have it be there for real.  Ideally I'd submit a PR, but I haven't read up on the process yet and think it'd be faster if someone in-the-know were to do it.

Many thanks!

**Comment by Semigradsky** [comment]
I'll try to fix it over the weekend.
