### ISSUE TITLE
@types/express-serve-static-core/index.d.ts Typescript build error (version 4.17.31)

### ISSUE THREAD

**Issue by Anvba** [DefinitelyTyped/DefinitelyTyped#62300]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62299

<div type='discussions-op-text'>

<sup>Originally posted by **Anvba** September 16, 2022</sup>
Typescript (4.4.4) build fails to build the project with the latest types package [@types/express-serve-static-core]:

node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(99,68): error TS1110: Type expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(99,77): error TS1005: '}' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(99,78): error TS1128: Declaration or statement expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(99,80): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(101,33): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(101,48): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(102,8): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(108,22): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(108,23): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(108,33): error TS1005: ')' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(110,26): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(110,27): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(110,35): error TS1128: Declaration or statement expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(110,37): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(110,44): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(114,52): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(114,53): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(114,60): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(114,70): error TS1128: Declaration or statement expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(118,28): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(118,29): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(118,53): error TS1005: '(' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(118,55): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(118,62): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(224,41): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(233,31): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(259,62): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(355,49): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(356,59): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(357,5): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(357,25): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(357,44): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(358,31): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(363,84): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(378,13): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(379,14): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(379,29): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(392,20): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(401,28): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(402,45): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(405,13): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(479,56): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(483,48): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(502,35): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(502,58): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(508,36): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(510,13): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(516,53): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(556,26): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(562,31): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(585,24): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(666,20): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(671,46): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(684,46): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(732,40): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(735,22): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(736,51): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(742,13): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(742,68): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(743,13): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(744,13): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(745,13): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(745,68): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(747,43): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(751,48): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(752,44): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(753,47): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(792,40): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(794,54): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(795,31): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(797,35): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(802,26): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(809,49): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(809,64): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(810,66): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(823,49): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(823,64): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(824,66): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(837,52): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(840,26): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(848,54): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(849,12): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(849,39): error TS1109: Expression expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(882,38): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(883,36): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(891,72): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(896,20): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(896,31): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(905,20): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(916,31): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(919,23): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(923,20): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(923,30): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(923,52): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(927,14): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(927,63): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(928,14): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(929,14): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(944,36): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(946,19): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(958,46): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(972,31): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(972,60): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(975,23): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(975,46): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(977,9): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(994,16): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(994,38): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(994,70): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1000,12): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1001,12): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1071,53): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1072,12): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1074,25): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1089,52): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1104,16): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1104,29): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1104,46): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1140,18): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1152,18): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1163,17): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1166,18): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1170,31): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1170,48): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1186,16): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1187,33): error TS1005: ';' expected.
node_modules/@types/express/node_modules/@types/express-serve-static-core/index.d.ts(1255,1): error TS1160: Unterminated template literal.

Same closed issue -> https://github.com/DefinitelyTyped/DefinitelyTyped/issues/62264</div>

**Comment by splincode** [comment]
I have the same issue

**Comment by aut1sto** [comment]
same, using typescript 2.7

**Comment by aut1sto** [comment]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/83125752/190724334-626d36ca-ab35-445f-8bb0-43d7a7c8d092.png">

I think issue with new version, dunno why

**Comment by aut1sto** [comment]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/83125752/190725270-1cccd319-ae57-4e7b-a2cc-4a42e7688a6a.png">

Mime package also fails, its package from same author as express

**Comment by dlutton** [comment]
Same issue on typescript version 4.0.7.  express-serve-static-core version 4.17.30 works but 4.17.31 throws errors.

**Comment by msviha** [comment]
Same issue here with version 4.17.31 - I am using typescript 4.6.4

**Comment by iMichaelOwolabi** [comment]
I'm having the same problem with version 4.17.2

**Comment by pmhegdek** [comment]
We are facing the issue for typescript version 4.4.3

**Comment by ffedelefrsf** [comment]
Same here with typescript v. 3.9.7.
Got to add a `resolution` to `downgrade express-serve-static-core to 4.17.30` and then `update @nestjs/cli to 7.6.0 (webpack fix)`

**Comment by shahzore-qureshi** [comment]
Same issue here. I had to upgrade our TypeScript version from 3.9.7 to 4.8.3.

**Comment by iMichaelOwolabi** [comment]
Ok, so I had the same issue but updating my TypeScript version to 4.1.6 solved my problem as suggested in this [issue 62264](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/62264)

**Comment by MawRojas** [comment]
I had the same issue. I updated both TypeScript to 4.1.6 and downgraded the downgrade express-serve-static-core to 4.17.30.  
`npm install typescript@4.1.6` 
`npm install -D @types/express-serve-static-core@4.17.30`

**Comment by Malik-shahzadAli** [comment]
I resolved this issue by updating devDependencies  
 from  `"@types/express": "^4.17.0",`  to ` "@types/express": "^4.17.2",`
and adding new dependency   ` "@types/express-serve-static-core": "4.17.20"`,
without updating typescript my current typescript version is ` "typescript": "~3.8.3"`

**Comment by luisvidal86** [comment]
I have the same issue, I have this version:

`"@types/express-serve-static-core": "4.17.30"`

And I don't know what is the purpose of upgrading an existing version and breaking the backward compatibility. I have TypeScript version 3.X and cannot upgrade to latest for now.

**Comment by mastrzyz** [comment]
For some reason our build system also got affected here without us even touching the package.json or lock file as well.

We had in our lock file :

```
"@types/express@4.11.0":
  version "4.11.0"
  resolved "https://****/_packaging/npm-mirror/npm/registry/@types/express/-/express-4.11.0.tgz#234d65280af917cb290634b7a8d6bcac24aecbad"
  dependencies:
    "@types/body-parser" "*"
    "@types/express-serve-static-core" "*"
    "@types/serve-static" "*"
```


and had to update to : 


```
"@types/express@4.17.14":
  version "4.17.14"
  resolved "****/_packaging/npm-mirror/npm/registry/@types/express/-/express-4.17.14.tgz#143ea0557249bc1b3b54f15db4c81c3d4eb3569c"
  integrity sha1-FD6gVXJJvBs7VPFdtMgcPU6zVpw=
  dependencies:
    "@types/body-parser" "*"
    "@types/express-serve-static-core" "^4.17.18"
    "@types/qs" "*"
    "@types/serve-static" "*"
```

**Comment by AngelMTR** [comment]
Finally, I was able to solve the problem of my project.
Upgrading TypeScript crashes the project. For me, my TypeScript version is 3.8.3
I just set the `@types/express-serve-static-core` version to `4.17.28` and everything was solved.
You can go to the link https://www.npmjs.com/package/@types/express-serve-static-core?activeTab=versions
And check which version to use that is compatible with TypeScript

**Comment by omkarmhetar** [comment]
@AngelMTR,  I have installed the express-serve-static-core 4.17.12 which is compatible with typescript version 3.1.x but still it is giving me error
@types/express/node_modules/@types/express-serve-static-core/index.d.ts
         TS1110: Type expected.
@types/express/node_modules/@types/express-serve-static-core/index.d.ts(99,77)
      TS1005: '}' expected.
@types/express/node_modules/@types/express-serve-static-core/index.d.ts(99,78)
      TS1128: Declaration or statement expected.

**Comment by robrez** [comment]
Is there still no remedy here outside of pinning versions?

**Comment by gsllucas** [comment]
I had this error when building angular server side rendering. What I did to solve this was restauring an old version of package-lock.json of my application. Doing this, I was able o build ssr without the errors, and run as well the application with docker.

**Comment by kev-creator** [comment]
I have the same issue.

**Problem Description**
Estoy experimentando un error de TypeScript al intentar compilar mi proyecto Angular. El error se relaciona con el paquete @types/express-serve-static-core.

**package.json**

{
  "name": "client-admin",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --port 4100",
    "build-arv-staging": "ng build --base-href /ped-admin-staging/ --configuration=arv-staging",
    "build-arv-prod": "ng build --base-href /ped-admin/ --configuration=arv-production",
    "build-viv-staging": "git checkout staging && git pull && ng build --base-href /efilehub-admin-staging/ --configuration=viv-staging",
    "build-viv-prod": "git checkout master && git pull &&  ng build --base-href /efilehub-admin/ --configuration=viv-production",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "server": "node server.js"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.3.0",
    "@angular/cdk": "^14.2.7",
    "@angular/common": "^14.3.0",
    "@angular/compiler": "^14.3.0",
    "@angular/core": "^14.3.0",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "^14.3.0",
    "@angular/material": "^14.2.7",
    "@angular/platform-browser": "^14.3.0",
    "@angular/platform-browser-dynamic": "^14.3.0",
    "@angular/router": "^14.3.0",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.26",
    "@fortawesome/free-solid-svg-icons": "^5.12.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "bn-ng-idle": "^1.0.1",
    "body-parser": "^1.18.3",
    "bootstrap": "^4.4.1",
    "core-js": "^2.5.4",
    "express": "^4.16.4",
    "file-saver": "^2.0.2",
    "flowbite": "^1.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "3.5.0",
    "method-override": "^3.0.0",
    "moment": "2.29.4",
    "morgan": "^1.9.1",
    "ng-recaptcha": "^5.0.0",
    "ngx-moment": "^3.5.0",
    "ngx-spinner": "^8.1.0",
    "rxjs": "~6.5.3",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.12",
    "@angular/cli": "^14.2.12",
    "@angular/compiler-cli": "^14.3.0",
    "@angular/language-service": "^14.3.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "autoprefixer": "^10.4.14",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.4.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "postcss": "^8.4.26",
    "prettier": "^3.0.0",
    "protractor": "^3.3.0",
    "tailwindcss": "^3.3.3",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.0",
    "typescript": "~4.6.4"
  },
  "prettier": {
    "singleQuote": true
  }
}


**Issue view:** 
ERROR in node_modules/@types/express-serve-static-core/index.d.ts:104:68 - error TS1110: Type expected. 104 type RemoveTail<S extends string, Tail extends string> = S extends `${infer P}${Tail}` ? P : S; ~~~ node_modules/@types/express-serve-static-core/index.d.ts:104:77 - error TS1005: '}' expected. 104 type RemoveTail<S extends string, Tail extends string> = S extends `${infer P}${Tail}` ? P : S; ~ node_modules/@types/express-serve-static-core/index.d.ts:104:78 - error TS1128: Declaration or statement expected. 104 type RemoveTail<S extends string, Tail extends string> = S extends `${infer P}${Tail}` ? P : S; ~ node_modules/@types/express-serve-static-core/index.d.ts:104:80 - error TS1005: ';' expected. 104 type RemoveTail<S extends string, Tail extends string> = S extends `${infer P}${Tail}` ? P : S; ~ node_modules/@types/express-serve-static-core/index.d.ts:106:33 - error TS1005: ';' expected. 106 RemoveTail<RemoveTail<S, `/${string}`>, `-${string}`>, ~ node_modules/@types/express-serve-static-core/index.d.ts:106:48 - error TS1005: ';' expected. 106 RemoveTail<RemoveTail<S, `/${string}`>, `-${string}`>, ~ node_modules/@types/express-serve-static-core/index.d.ts:107:8 - error TS1005: ';' expected. 107 `.${string}` ~ node_modules/@types/express-serve-static-core/index.d.ts:113:22 - error TS1005: ';' expected. 113 : Route extends `${string}(${string}` ~ node_modules/@types/express-serve-static-core/index.d.ts:113:23 - error TS1005: ';' expected. 113 : Route extends `${string}(${string}` ~ node_modules/@types/express-serve-static-core/index.d.ts:113:33 - error TS1005: ')' expected. 113 : Route extends `${string}(${string}` ~ node_modules/@types/express-serve-static-core/index.d.ts:115:26 - error TS1005: ';' expected. 115 : Route extends `${string}:${infer Rest}` ~ node_modules/@types/express-serve-static-core/index.d.ts:115:27 - error TS1005: ';' expected. 115 : Route extends `${string}:${infer Rest}` ~ node_modules/@types/express-serve-static-core/index.d.ts:115:35 - error TS1128: Declaration or statement expected. 115 : Route extends `${string}:${infer Rest}` ~ node_modules/@types/express-serve-static-core/index.d.ts:115:37 - error TS1005: ';' expected. 115 : Route extends `${string}:${infer Rest}` ~ node_modules/@types/express-serve-static-core/index.d.ts:115:44 - error TS1005: ';' expected. 115 : Route extends `${string}:${infer Rest}` ~~~~

**Comment by TheMikeyRoss** [comment]
Im having this problem as well.

Oddly enough when I build my code in a windows machine i get no errors but when I do it in a ubuntu 22.04 machine I get the following error 



```
      TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' is not assignable to parameter of type 'PathParams'.
ts-loader-default_e3b0c44298fc1c14

```



Coming from the following code:

```
  app.use(
    "/graphql",
    expressMiddleware(server, {
      context: async ({ req }) => ({ headers: req.headers }),
    })
  );

```

**Comment by jakebailey** [comment]
These versions are well out of the support range of DT.

@TheMikeyRoss, your issue is different and unrelated. Consider creating a discussion thread with your question.
