### ISSUE TITLE
[@types/node-media-server] Type of TransTaskConfig.dash should be 'boolean', not 'true' 

### ISSUE THREAD

**Issue by AilurusRedPanda** [DefinitelyTyped/DefinitelyTyped#62485]
I have to write like `dash: true as true` because of this, or I would get a tsc error since "Type 'boolean' is not assignable to type 'true' ".
![x](https://user-images.githubusercontent.com/33323586/193271992-5b317e20-0d90-4816-90f6-0979e5d49749.png)

Then I've found another issue in the same file that also causes type errors. In Typescript, the type of an array with a specific type can be written as `Type[]` or `Array<Type>`, not `[Type]`.
![z](https://user-images.githubusercontent.com/33323586/193332068-efa5722b-66e2-4107-94cb-ed5bb2901b07.png)

**Comment by princefishthrower** [comment]
@AilurusRedPanda should be resolved in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62491
