### ISSUE TITLE
[@types/react-datepicker] - add onChange optional type in index.d.ts.

### ISSUE THREAD

**Issue by lokba** [DefinitelyTyped/DefinitelyTyped#62627]
I'm using Typescript with React.
When using react-datepicker, I experienced a type error problem when I wanted to make onChange optional.

index.d.ts -  [go to definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-datepicker/index.d.ts)
```typescript
export interface ReactDatePickerProps<
    CustomModifierNames extends string = never,
    WithRange extends boolean | undefined = undefined,
> {
    ...
    onChange(
        date: WithRange extends false | undefined ? Date | null : [Date | null, Date | null],
        event: React.SyntheticEvent<any> | undefined,
    ): void;
    ...
}
```

It seems onChange is not included optional type in index.d.ts.

**Comment by ccjmne** [comment]
It seems to me like `onChange` indeed is meant to be required:

**Comment by lokba** [comment]
@ccjmne  thanks for the comments!!

**Comment by Semigradsky** [comment]
@lokba will you close ticket?
