### ISSUE TITLE
Use `secrets` to manage a personal access token used by CI

### ISSUE THREAD

**Issue by rhysd** [DefinitelyTyped/DefinitelyTyped#62638]
Bare secret of personal access token is embedded in workflow `CI.yml`.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/29d4592066a1587254230035f5fbb7c5af46ef19/.github/workflows/CI.yml#L38-L39

After some checks at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62637#issuecomment-1272936513, I understood it had a write permission to change commit status.

This is dangerous because possible malicious user can use the token to change some status of this repository. GitHub provides a way to manage secrets safely: https://docs.github.com/en/actions/security-guides/encrypted-secrets

Can we use it for managing the secret token?

**Comment by sandersn** [comment]
@orta I believe this is an unrelated token that you use a lot of places, and that it doesn't need write access to the repo it's running on. Is that correct?

**Comment by rhysd** [comment]
Let me share the context for sure:

1. I created a PR #62637 which tried to replace the embedded token with `secrets.GITHUB_TOKEN`
2. But I found that Danger reported the below error in the PR check
3. So I thought `secrets.GITHUB_TOKEN` is not sufficient and some write permission is necessary to run Danger, which means the embedded token has the permission

```
Request failed [403]: https://api.github.com/user
Response: {
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/users#get-the-authenticated-user"
}
Could not add a commit status, the GitHub token for Danger does not have access rights.
If the build fails, then danger will use a failing exit code.
```

**Comment by rhysd** [comment]
@sandersn 

From [Danger document](https://danger.systems/js/guides/getting_started.html#setting-up-an-access-token):

> We recommend giving the token the smallest scope possible. This means just public_repo, this scope is [still ideally too much](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/) but this account shouldn’t have any access to other repos or organizations - so malicious use of the token is scoped to making new repos on it, or writing comments on other OSS projects.

So I believe the token has `public_repo` scope permission. And [GitHub document](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps) says that the `public_repo`

> Limits access to public repositories. That includes read/write access to code, commit statuses, repository projects, collaborators, and deployment statuses for public repositories and organizations. Also required for starring public repositories.


So the token for Danger has write permission and **must** be protected with secrets.

See this [Danger document](https://danger.systems/js/guides/getting_started.html#setting-up-an-access-token):

> You’ll want to save this token for later, when you add a DANGER_GITHUB_API_TOKEN to your CI.

**Comment by orta** [comment]
This discussion assumes the GitHub account which owns the token has access to this repo, which it doesn't! (or any repos)

Writing statuses is a limited API, this setup is fine

**Comment by rhysd** [comment]
@orta Thank you for the knowledge. I didn't know that the token is generated from a user which doesn't have the permission to modify this PR. So the user is dedicated for this use case and there is no other public repos owned by the user, am I correct? (Otherwise the public repos are exposed to everyone).

@sandersn I updated #62747 to add a comment which explains why the token can be exposed. It can avoid the discussion like this in the future. Can you take a look?

**Comment by orta** [comment]
Yeah, that's correct - and good improvement in the PR, merged.
