### ISSUE TITLE
[open-graph-scraper] Make OpenGraphImage fields optional

### ISSUE THREAD

**Issue by Dichotomia** [DefinitelyTyped/DefinitelyTyped#62675]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62674

<div type='discussions-op-text'>

<sup>Originally posted by **Dichotomia** October 12, 2022</sup>
Hello.

The library seems to enable height and width to be null on OpenGraphImage object.

Please reflect this on typings.

Best regards

</div>

**Comment by burno1** [comment]
I can take this

**Comment by burno1** [comment]
Opened PR [62739](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62739)

**Comment by Dichotomia** [comment]
Thanks a lot
