### ISSUE TITLE
Typescript ToolConfig

### ISSUE THREAD

**Issue by zxlvera** [DefinitelyTyped/DefinitelyTyped#62690]
Please update `ToolConfig` in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-email-editor/index.d.ts
from the following:
```
export interface ToolConfig {
    readonly enabled?: boolean | undefined;
    readonly position?: number | undefined;
    readonly data?: StringList | undefined;
}
```
to this:

```
export interface ToolPropertiesConfig {
  [key: string]: {
    value: string
    }
}

export interface ToolConfig {
    readonly enabled?: boolean | undefined;
    readonly position?: number | undefined;
    readonly properties?: ToolPropertiesConfig | undefined;
}
```

Reasoning: [Unlayer Documentations for Tools does not contain `data`](https://docs.unlayer.com/docs/heading)
also inside nested `properties` contains `{value: string}` object

PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62691

**Comment by jakebailey** [comment]
PR was merged.
