### ISSUE TITLE
Missing "Stack" component

### ISSUE THREAD

**Issue by manuelvegadev** [DefinitelyTyped/DefinitelyTyped#62842]
Im trying to use the [Stack component](https://github.com/carbon-design-system/carbon/tree/main/packages/react/src/components/Stack) but I cant found it.

**Comment by Semigradsky** [comment]
`Carbon` will soon have own typings: https://github.com/carbon-design-system/carbon/pull/12222

**Comment by manuelvegadev** [comment]
Oh wow! Thanks for the info!
