### ISSUE TITLE
[@types/koa-bodyparser]：错误 TS2717 #62920

### ISSUE THREAD

**Issue by PlayGuitar-CoderQ** [DefinitelyTyped/DefinitelyTyped#62921]
![img_v2_a933c6b0-2a3c-4eb3-988b-00fe436c0bcg](https://user-images.githubusercontent.com/55419399/198215175-03f4213f-02a5-440b-af88-417038221b69.png)

I found this problem when I executed tsc

@petarzarkov  😭

**Comment by amaschas** [comment]
It looks like you have some other package that is defining the type of the `body` property, and its conflicting with `koa-bodyparser`.
