### ISSUE TITLE
Add types definition for resize event on video element.

### ISSUE THREAD

**Issue by pennywisexy** [DefinitelyTyped/DefinitelyTyped#63061]

**Comment by Semigradsky** [comment]
@pennywisexy please provide full information. What the library, what the interface/type?

**Comment by pennywisexy** [comment]
> @pennywisexy please provide full information. What the library, what the interface/type?

library - @types/react, interface DOMAttributes.

**Comment by Semigradsky** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event

> In some earlier browsers it was possible to register `resize` event handlers on any HTML element. It is still possible to set `onresize` attributes or use [addEventListener()](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) to set a handler on any element. However, `resize` events are only fired on the [window](https://developer.mozilla.org/en-US/docs/Web/API/Window) object (i.e. returned by [document.defaultView](https://developer.mozilla.org/en-US/docs/Web/API/Document/defaultView)). Only handlers registered on the `window` object will receive `resize` events.

@pennywisexy so you should subscribe to window resize

**Comment by pennywisexy** [comment]
> https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event
> 
> > In some earlier browsers it was possible to register `resize` event handlers on any HTML element. It is still possible to set `onresize` attributes or use [addEventListener()](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) to set a handler on any element. However, `resize` events are only fired on the [window](https://developer.mozilla.org/en-US/docs/Web/API/Window) object (i.e. returned by [document.defaultView](https://developer.mozilla.org/en-US/docs/Web/API/Document/defaultView)). Only handlers registered on the `window` object will receive `resize` events.
> 
> @pennywisexy so you should subscribe to window resize

I was talking about resize event for the video element (HTMLMediaElement). It a small difference of these events. And the resize event for the video is not described in @types/react. It must be added.

**Comment by Semigradsky** [comment]
You are right, it should have `resize` event: https://html.spec.whatwg.org/multipage/media.html#mediaevents 👍

**Comment by pennywisexy** [comment]
Great!

**Comment by mariuslundgard** [comment]
@Semigradsky Hi there, I'm seeing TS errors in my project that sound like they might be introduced after #63076. In this case it's a SVG component with props of type `React.SVGProps<SVGSVGElement>`:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/406933/203785137-0f22a2ed-e536-457b-ba74-f284925df23c.png">

**Comment by Semigradsky** [comment]
Could you provide reproducible example?
