### ISSUE TITLE
`getObjectByProperty(name: string, value: string)` `value` type error

### ISSUE THREAD

**Issue by lyhanburger** [DefinitelyTyped/DefinitelyTyped#63070]
reference : https://github.com/mrdoob/three.js/blob/r144/docs/api/en/core/Object3D.html#L272

so https://github.com/DefinitelyTyped/DefinitelyTyped/blob/524782c5c83b65137a14934a044003d47d9d2c96/types/three/src/core/Object3D.d.ts#L367 
should be?
`getObjectByProperty(name: string, value: string)` -> `getObjectByProperty(name: string, value: any)`

**Comment by Semigradsky** [comment]
Yeah, for example in tests they used `boolean`:
https://github.com/mrdoob/three.js/blob/d091564e0279adb607f9a2867fdd9f6dbfe10b2e/test/unit/src/core/Object3D.tests.js#L523

**Comment by Semigradsky** [comment]
@KiyomiHan It was already fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63117

**Comment by epreston** [comment]
Hello all.   Can we close this issue since it's been fixed ?
