### ISSUE TITLE
ckeditor5-utils: PriorityString may also be a number

### ISSUE THREAD

**Issue by mmichaelis** [DefinitelyTyped/DefinitelyTyped#63311]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/47de3e0f285ad7de9398c660b49a984fc5f78279/types/ckeditor__ckeditor5-utils/src/priorities.d.ts#L1-L5

Compared to [ckeditor5/priorities.ts at v35.3.1](https://github.com/ckeditor/ckeditor5/blob/v35.3.1/packages/ckeditor5-utils/src/priorities.ts#L15) `PriorityString` could also be a number. And: `get` has a default priority, and thus, the parameter is optional. Suggested change:

```typescript
export type PriorityString = "normal" | "high" | "low" | "highest" | "lowest" | number; 
  
interface Priorities extends Record<PriorityString, number> { 
  get(key: PriorityString = "normal"): number; 
}
```

**Comment by Semigradsky** [comment]
@mmichaelis `@ckeditor/ckeditor5-utils` was rewritten on TypeScript, so `@types/ckeditor__ckeditor5-utils` no needed more?

**Comment by mmichaelis** [comment]
> @mmichaelis `@ckeditor/ckeditor5-utils` was rewritten on TypeScript, so `@types/ckeditor__ckeditor5-utils` no needed more?

Hi @Semigradsky, well, I think CKEditor 5 typings will soon reach EOL (or so I hope), as CKSource is heavily working on migrating to TypeScript. But: Typings are not published yet. To quote [release notes](https://ckeditor.com/docs/ckeditor5/35.3.0/updating/migration-to-35.html#there-is-now-a-typescript-code-on-github-and-how-it-affects-your-build):

> It affects you only if you use the [source code directly from git repository (GitHub)](https://github.com/ckeditor/ckeditor5). If you use it via any other channel (npm, CDN, ZIP, etc.) this change is completely transparent for you as we publish only JavaScript code there.

Meanwhile, the best option for all others seems to be to rely on typings (thankfully) provided here at DefinitelyTyped.

**Comment by jakebailey** [comment]
This package has been removed from DT.
