### ISSUE TITLE
Webpack.d.ts won't compile with Node.d.ts

### ISSUE THREAD

**Issue by scott-stephen** [DefinitelyTyped/DefinitelyTyped#6334]
Since the latest Webpack.d.ts commit, if I include the Node.d.ts I get the following error:

(312,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'RequireFunction'.

**Comment by use-strict** [comment]
https://github.com/borisyankov/DefinitelyTyped/pull/6307

**Comment by use-strict** [comment]
Can you close it? Thanks
