### ISSUE TITLE
NodeModule definition doesn't support Hot Module Replacement

### ISSUE THREAD

**Issue by niba** [DefinitelyTyped/DefinitelyTyped#6341]
Hot Module Replacement is a webpack feature that add possibility to inject updated modules into the active runtime. 
That feature extends a Module with addtiional property 'hot' that informs if something changed. Current definition of NodeModule (Node.ts file) doesn't have a property hot so it is impossible to read it in application. Mostly users don't have to read it but there are a situations like in React-Redux application where user needs to check if module was updated to pass a new redux state.

I'm quite new to Typescript so I don't know if there is a way to extend somehow NodeModule interface in Webpack definiton file with that additional property 'hot'

**Comment by jbrantly** [comment]
@tkqubo might be able to help since he wrote the webpack definition.

**Comment by tkqubo** [comment]
You can simply redefine (or override?) the `module` itself.  For example, the code below can compile

```ts
declare let module: number;
let value = 3 * module;
```

So I think this kind of redefinition will solve the problem:

```ts
declare var module: {
    exports: any;
    require(id: string): any;
    id: string;
    filename: string;
    loaded: boolean;
    parent: any;
    children: any[];
    hot: Hot;
};

interface Hot {
   // some implementation here...
}
```

**Comment by tkqubo** [comment]
@niba  If you can wait, I will do the definition of the module maybe by the end of this month.  Is that ok?

**Comment by niba** [comment]
I temporary solved it in my project by adding 

    interface NodeModule {
        hot: any;
    }

this definition to webpack.d.ts. It extended defined module in node.d.ts. I think its better to define this extension in webpack file, not in node

**Comment by tkqubo** [comment]
@niba is your problem fixed?  if so, I want wakame-san to close the issue, please? @vvakame

**Comment by niba** [comment]
@tkqubo yes, it's fixed. Thank you :)
