### ISSUE TITLE
@types/jwplayer missing getCues(), userActive and userInactive 

### ISSUE THREAD

**Issue by mdaoust-sidlee** [DefinitelyTyped/DefinitelyTyped#63510]
As seen on the the documentation, jwplayer has the getCues method
https://docs.jwplayer.com/players/reference/getcues

Also the userActive and userInactive are available but not really well documented. 
ex: 
```
player.on('userActive', onUserActive);
player.on('userInactive', onUserInactive);
```

Those method and events should define it in the type definitions here : https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jwplayer/index.d.ts

Thanks in advance.

**Comment by martin-badin** [comment]
please review https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63737

**Comment by mdaoust-sidlee** [comment]
Fixed 🎉. Thanks a lot.
