### ISSUE TITLE
[@types/react] React.forwardRef lose the first parameter's type When the Compoent's props type include ‘[index:string]:any’

### ISSUE THREAD

**Issue by StoneCode5** [DefinitelyTyped/DefinitelyTyped#63730]
I write a demo in [this link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecBi0A7ilACZJnIBm2ArgM5ICS4SUKMwAbkgBIoAdmQA2SOAF841KBBBwA5FFQYFAbgCwAKG0B6XXED45oGxzQCZpgMLlBKEEkAxKigDmSQDD-gDfjA98qBTuUClxoHXlQG6KgGtygN9ygKrygEPKgA6megZIAB5oSGDwgBgEVjaAmATOcCmOSFlCZHBCAJ5wEDAAFuxwaJWk6DDs2sCCTVDU6OIACrJgDLjacMNw6UgA-ABccAwwUK0OmlojxU5To3QgAEbsSysA2q0UcdOz84IOALrTpdoS2tpoEIKzcAAiSCAQ08iNAHT4ADCAB5ehB+gA+OAAXjgAAowH0GNMwf0AJQwqE4IYjJ4veB4MbYPKSGFwRHghh7EbKGB0KCCeE4lbDYFgCHMlkrQCIRoB6MxwYwkzkALnqAEPycHl7ssuXBgbp2Zy0UsJEtHs9Xh8voQoCRyDQyb8MH9qMRSFQkNQ4QikSikdhlNRptrdRRzdRgaUIRjoVjOXjXoTrEhiU5SbCKf1qcN9HBGOIFHHWGB2JwePxCmIFHAYBA4PFIEw4DYqhAipzE2wOFxeAJhGI4Q7sHDvVC4djpVyRBAHNNm5jcLV1RAxH8uw44QoxwoMRJMJyJGilQ8O3BafTGXDOSs2RyVzK4HyBUGhWKJU4pfu5QqV0utAvl-74AAVJCvWF9n2DFdrhmy3f7mNAGT4wBTRSsOBAEhzMZABC3QAF40ALk8txGGMYBKZNFCsBRsEoYAcygOAiGAEQRHJZQmDadCgyzE08LjKBENZTVczA3Rd3ouAgNAlA4EAQptIKDWCEL3JCDBQtCFAwrCyBw6ASNfJByMECoFj+OBmHgMgIELRT4BsJB4HzJAMFTdU-jYmMDKMrh1WmbDcOKEQGFzAiiNksj4HEyjpBk2i4DY4FGOdM19WY-8RjlXcJCAA)

when My componet'props type has '[index:string]: any',

    interface Props {

        name?: string;

        age?: number;

        [index: string]: any

    }

    const DemoForwardRef = React.forwardRef((props: Props, ref: React.ForwardedRef<any>) => {
    
        const { name, age } = props;
    
        // use 'useImperativeHandle' to expose method 
    
        useImperativeHandle(ref, () => ({
    
            log: () => { console.log('log') },
    
        }));
    
        return (
    
            <p>
    
                我是{name}，年龄{age}
    
            </p>
    
        );
    })

 **the editor lose the code completion of 'name' and  'age'**

**Comment by Mintoo200** [comment]
This either has been fixed or is an editor config issue : 
<img width="578" alt="image" src="https://github.com/DefinitelyTyped/DefinitelyTyped/assets/25901730/431d3ce3-4bb9-40c1-8cb3-9ccf7723f26a">
