### ISSUE TITLE
browser-sync.d.ts: expose interface BrowserSyncInstance

### ISSUE THREAD

**Issue by tkrotoff** [DefinitelyTyped/DefinitelyTyped#6382]
@joeskeen 

Example:
```TypeScript
function browserSyncInit() {
  return browserSync.create();
}
```

vs
```TypeScript
function browserSyncInit(): BrowserSyncInstance {
  return browserSync.create();
}
```

See https://github.com/borisyankov/DefinitelyTyped/blob/master/browser-sync/browser-sync-tests.ts#L82

I've previously made a commit for that: https://github.com/borisyankov/DefinitelyTyped/commit/dd836b4ac124caa70145cf98ecabeedc01e0b07e but it was removed afterwards.

Related PR: https://github.com/borisyankov/DefinitelyTyped/pull/6045

**Comment by andrewconnell** [comment]
+1

To pile on, why not expose all the other interfaces, such as **Options**? If you're building an options object to pass into `browserSync()`, if this interface was exposed, editors could provide some nice IntelliSense / autocomplete help.

**Comment by joeskeen** [comment]
@tkrotoff, @andrewconnell nice catch.  Sorry for the delayed response, I'll try to get that fixed quickly.
