### ISSUE TITLE
Signature for i18next: I18nextStatic.t

### ISSUE THREAD

**Issue by nidu** [DefinitelyTyped/DefinitelyTyped#6383]
Hello,

In i18next typing in interface `I18nextStatic` there's a method `t(key: string, options?: I18nTranslateOptions): string;`. `options` have a string type however it disallows using replacing variables (which are dynamic by nature, see section 'replace variables' [here](http://i18next.com/pages/doc_features.html)). Am i doing something wrong or options type should be `any` (like in `JQueryStatic.t` method)?

Thanks.

**Comment by artem1** [comment]
Hi.

Have same problem. As workasound i exclude i18next.d.ts and add simple
`declare var i18n: {t: (key: string, options?: any) => string};`

**Comment by cloakedninjas** [comment]
👍
