### ISSUE TITLE
openseadragon: mouseNavEnabled option wrongly typed?

### ISSUE THREAD

**Issue by nltesown** [DefinitelyTyped/DefinitelyTyped#64108]
Hello,

On that line:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/732df55fb468d4f0d143bb2e3d81e637ec879a61/types/openseadragon/index.d.ts#L353

Shouldn't it be: `mouseNavEnabled?: boolean | undefined;`?

**Comment by defnot001** [comment]
You are right [this line](https://github.com/openseadragon/openseadragon/blob/ead728dc3519bc578a0e29642445a6ca8837431f/src/openseadragon.js#L513) says it should be a boolean.

**Comment by nltesown** [comment]
Thanks! (I realize I should probably have made a pull request directly... Bad reflex!)

**Comment by defnot001** [comment]
Don't worry, wasn't too much effort 😅.
