### ISSUE TITLE
Split jQuery.d.ts into multiple files (per module)

### ISSUE THREAD

**Issue by janb87** [DefinitelyTyped/DefinitelyTyped#6446]
In my application I'm using a custom build of jQuery where I excluded some of the modules.

Special builds can be created that exclude subsets of jQuery functionality. This allows for smaller custom builds when the builder is certain that those parts of jQuery are not being used.
https://github.com/jquery/jquery#modules

My suggestion is to split also the definition files into one file per module. This way people using a custom build can also use a subset of the jQuery definition files.

jQuery.d.ts would become a file which includes all modules as a reference so it could still be used as before.

I'm willing to contribute these changes via a pull request if everybody is ok with it.

**Comment by vvakame** [comment]
@johnnyreilly

**Comment by johnnyreilly** [comment]
If this wouldn't impact existing users of the typings then it seems like a reasonable idea.  It is pretty massive as is.

Is there much of an advantage to you?  I guess if it's broken up you can avoid including the modules you're not using.

Question: what impact would this have on people consuming `jquery.d.ts` via nuget?  Would that still work seamlessly or would they have to do a bunch of tsconfig fiddling to ensure that they only used the `jquery.d.ts` file?

**Comment by janb87** [comment]
NuGet should keep on working as before. Reference to jQuery.d.ts would still be as before. People who only want to use Definitions from a specific module should directly reference the .d.ts file for the specific module.

On the other hand I would see more problems on people using the TSD (https://github.com/DefinitelyTyped/tsd) tool.
As there would be more files after this change it would be required to add all references to the files explicitly inside your tsd.json file. 

Another way to solve this is by changing the jQuery.d.ts file and group references of a specific module together.

For example:
```
// <editor-fold desc="ajax"> 
interface JQueryStatic {

    /**
     * Perform an asynchronous HTTP (Ajax) request.
     *
     * @param settings A set of key/value pairs that configure the Ajax request. All settings are optional. A default can be set for any option with $.ajaxSetup().
     */
    ajax(settings: JQueryAjaxSettings): JQueryXHR;

    ...
}
// </editor-fold> 

// <editor-fold desc="css"> 
interface JQuery {

     /**
     * Get the value of style properties for the first element in the set of matched elements.
     *
     * @param propertyName A CSS property.
     */
    css(propertyName: string): string;

    ...
}
// </editor-fold> 
```

This way it would be easy to remove definitions from the file using a tool (eg nodejs script).

**Comment by johnnyreilly** [comment]
Hmmmm.. I'm not so sure that I'm keen on this given the tsd impact.
