### ISSUE TITLE
[@types/cytoscape-fcose] Incorrect typing? 

### ISSUE THREAD

**Issue by jascenc1** [DefinitelyTyped/DefinitelyTyped#64468]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5a651c60a0c9f1fb6d93ff79e7ff96e6717d1e52/types/cytoscape-fcose/index.d.ts#L84

Seeing this as a function returning a number and not just number type in cytoscape.Js-fcose readme

**Comment by ColoredCarrot** [comment]
I agree; seems it can be either a `number` or a `(node) => number`, as seen in usage examples [here](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose/search?q=repulsion). Internally, cytoscape-fcose uses `optFn` to call this parameter, as defined [here](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose/blob/78afcf96512a409abc903699277ad616c02dfad9/src/fcose/cose.js#L35).

Same for `idealEdgeLength` and potentially others.

I'll look into making a PR, unless you call dibs? 😄

**Comment by jascenc1** [comment]
@ColoredCarrot looks like you got around to making that PR - thanks for the help!
