### ISSUE TITLE
18.14.1版本编译时错误

### ISSUE THREAD

**Issue by Jinxishihenian** [DefinitelyTyped/DefinitelyTyped#64472]
报错信息：node_modules\_@types_node@18.14.1@@types\node\ts4.8\test.d.ts(614,17)
文件源码：
![Snipaste_2023-02-24_11-31-20](https://user-images.githubusercontent.com/44466363/221085327-7577791a-05ed-42b0-80bf-d4556d95a847.png)

**Comment by juliejay** [comment]
Same here, builds are failing because of recent PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63892

**Comment by yukeehan** [comment]
same for me:
![image](https://user-images.githubusercontent.com/29190507/221288777-bb6decfb-19ef-4e88-bc1d-6bd8b1096bdf.png)

**Comment by black3279** [comment]
same build issue for me too

**Comment by black3279** [comment]
@Jinxishihenian  @juliejay @yukeehan 
I think this issue occurs about typescript version. If you upgrade your typescript verison to 4.8 (certainly 4.8 or maybe 4.2), this problem will be solved. or you can use npm version tag to match your @types/node version with typescript version.
ex) "@types/node": "ts4.1" => equal to 18.11.9
If your typescript version is low than 4.1, you should find the version match

**Comment by Jinxishihenian** [comment]
@black3279 是的，的确跟typescript版本有关系，我将typescript：~4.1.2改为typescript：^4.1.2并升级响应依赖如ts-loader,该问题消失.

**Comment by jakebailey** [comment]
This appears to have only happened with TS 4.1, which is not supported.
