### ISSUE TITLE
The definitelytyped.org website is down

### ISSUE THREAD

**Issue by joelverhagen** [DefinitelyTyped/DefinitelyTyped#64478]
This website is linked in the GitHub organization: http://www.definitelytyped.org/

I see this for both HTTP and HTTPS

![image](https://user-images.githubusercontent.com/94054/221273579-eba612dc-6f0a-4cbd-83ac-4b7e5339d233.png)

**Comment by SonicWim** [comment]
And it still is...

**Comment by joe-oli** [comment]
21/Mar/2024. Still down. One would think the inventors of the Typescript language would what to sponsor the site and keep it alive, but whatever...

**Comment by jakebailey** [comment]
It took a bunch of work, but https://definitelytyped.org is back up, hosted by https://github.com/DefinitelyTyped/definitelytyped.github.io once again. The content is ancient, so I'm not so sure it's that useful. But it's up .
