### ISSUE TITLE
Incorrect return types for Knex SchemaBuilder methods

### ISSUE THREAD

**Issue by Andorbal** [DefinitelyTyped/DefinitelyTyped#6460]
I'm new to typings, but it seems as if the Knex SchemaBuilder methods (https://github.com/borisyankov/DefinitelyTyped/blob/master/knex/knex.d.ts#L303) are returning the wrong type.  They return Promise<void> while the knex source has the methods just returning a reference to 'this' (https://github.com/tgriesser/knex/blob/master/lib/schema/builder.js#L27). 

I don't see any references to promises of any kind in there.  I'd be happy to create a PR, but I wanted to make sure I wasn't completely wrong here.

Thanks!

**Comment by tkrotoff** [comment]
Did you try yourself?

You might be 50% right, all SchemaBuilder should return SchemaBuilder.
[This tutorial](http://endpointsjs.com/tutorial/1) suggests that you can chain SchemaBuilder functions.

The "faulty" PR: #3989

I think SchemaBuilder should inherit from ChainableInterface like QueryBuilder does.

ping @yortus

**Comment by yortus** [comment]
@tkrotoff @Andorbal The [knex Schema Builder documentation](http://knexjs.org/#Schema) just states that they return promises and doesn't demonstrate chaining, but as you both show, chaining is clearly supported.

So as @tkrotoff  points out there needs to be a schema builder equivalent of `ChainableInterface` and possibly an equivalent of `QueryInterface`.

**Comment by casey-chow** [comment]
This still seems to be a problem, as the following code fails to typecheck:

```ts
exports.up = (knex: Knex): Promise<any> => 
    knex.schema.createTable('users', (table) => {});
```

With the following failure:

> [ts] 
Type 'SchemaBuilder' is not assignable to type 'Promise<any>'.  
Property '[Symbol.toStringTag]' is missing in type 'SchemaBuilder'. [2322]

**Comment by taybin** [comment]
I'm still duplicating this.  I was able to work around it for a bit with PromiseLike<T>, but PromiseLike doesn't expose `catch()` which I want.

**Comment by taybin** [comment]
This can be closed as knex provides its own definitions now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
