### ISSUE TITLE
Property 'collectFinancialConnectionsAccounts' does not exist on type 'Stripe'

### ISSUE THREAD

**Issue by AckerApple** [DefinitelyTyped/DefinitelyTyped#64744]
Stripe has added new types. Can we please get them data typed?

**Comment by kaznovac** [comment]
please use official stripe types (https://github.com/stripe/stripe-js), these are outdated/unmaintained and about to be removed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68416
