### ISSUE TITLE
Wrong data type in Dockerode types

### ISSUE THREAD

**Issue by kilian-bryon** [DefinitelyTyped/DefinitelyTyped#64837]
Hi,

I'm using this type definition of Dockerode but I spotted a little mistake. I want to add a create a Docker container and define its mac-address but the type is set to boolean instead of string.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d8c6e21d99e00769b450c6e091a85eb2eb4e63b3/types/dockerode/index.d.ts#L1149

Can this be fixed?

Thanks!

**Comment by nwalters512** [comment]
I believe this can be closed now that #64838 has been merged.
