### ISSUE TITLE
Improve the RequestAPI.Options declaration

### ISSUE THREAD

**Issue by eggers** [DefinitelyTyped/DefinitelyTyped#6489]
Currently, the following code will compile with no errors because all properties on `Options` are optional:

```typescript
import * as request from 'request';

request.defaults(8);
```

However, in reality either `uri` or `url` is required, so it would be preferable to enforce that constraint. The only way I know to do that would be to do something like this. However, other declarations that extend `RequestAPI.Options` would also need to be updated.

```
interface UriOptions {
  uri: string;
}

interface UrlOptions {
  url: string;
}

interface OptionalOptions {
...
}

export type Options = (UriOptions | UrlOptions) & OptionalOptions;
```

**Comment by enriched** [comment]
Need to fix the Options that are passed to default, also need to add baseUrl to the options.

**Comment by eggers** [comment]
good catches. thanks. +1
