### ISSUE TITLE
core-js.d.ts - split out ES7 / ES2016?

### ISSUE THREAD

**Issue by johnnyreilly** [DefinitelyTyped/DefinitelyTyped#6494]
I was just about to raise an issue about TypeScripts [lib.es6.d.ts](https://raw.githubusercontent.com/Microsoft/TypeScript/master/lib/lib.es6.d.ts) not having es6's `Array.prototype.includes`.  Then I realised; it's actually [part of ES2016](https://github.com/tc39/Array.prototype.includes/).

I'm currently writing TypeScript using ES6 and Babel and realised that using core-js.d.ts isn't compatible with this as the ES6 / ES2015 typings collide with what is in core-js.d.ts.

That being the case, it might be good to break out core-js.d.ts into a number of files based on ECMAScript version.  So like this perhaps:

`core-js.es2015.d.ts`
`core-js.es2016.d.ts`

@rbuckton do you have any thoughts on this?  For now I'm planning to do this locally so I can build.  But if people are happy with this I could take on splitting these up. 

PS would this be a better name if we did?  Officially it's ES2016 .... but we could go with this:

`core-js.es6.d.ts`
`core-js.es7.d.ts`

**Comment by vvakame** [comment]
:+1:

**Comment by digitalkaoz** [comment]
+1 please

**Comment by joewood** [comment]
Just hit this myself. Definitely required.
It would be even better if core-js could take on non-ambient typings into their repository so you just pull out what you need as you use it.

**Comment by BendingBender** [comment]
It would be preferable to split up the typings into DOM, ES2015, ES2016, ES2017, and non-ambient library variants, just as @joewood proposed.

Currently, when one installs the typings both the `"es5"` **and** `"dom"` libraries need to be enabled for `tsc@2` not to complain. It is definitely wrong that one has to enable the `"dom"` lib for a node environment just to be able to use core-js. Without it `tsc` (legitimately) complains that it can't find the `Node` type used to describe the `NodeList`(!!!) interface:
```
node_modules/@types/core-js/index.d.ts(749,43): error TS2304: Cannot find name 'Node'.
```

Worse than that is the fact that when using it with node, one gets all of the different language levels even when core-js is used exclusively in library mode. It leads to a situation where TypeScript suggests methods on Arrays (and other stuff) that is actually not available during runtime, beating the whole purpose of using TypeScript.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
