### ISSUE TITLE
superagent.d.ts: .end(err, res) is not typed

### ISSUE THREAD

**Issue by tkrotoff** [DefinitelyTyped/DefinitelyTyped#6498]
```TypeScript
import request = require('superagent')

request
  .post('/api/pet')
  .end(res => {  // <= res is of type any instead of request.Response
  });
```

With commit e263035131f79c05b980fbd9739dde6674200df0, CallbackHandler takes 2 different signatures instead of one and none of them are recognized.

```TypeScript
type CallbackHandler = { (err: any, res: request.Response): void; }|{ (res: request.Response): void; };
// FYI can also be written:
// type CallbackHandler = ((res: request.Response) => void) | ((err: any, res: request.Response) => void);
```

The proposed "solution" in [superagent-tests.ts](https://github.com/borisyankov/DefinitelyTyped/blob/master/superagent/superagent-tests.ts#L14) kills TypeScript purpose:
```TypeScript
request
  .post('/api/pet')
  .end((res: request.Response) => {
  });
```

ping @horiuchi

**Comment by horiuchi** [comment]
@tkrotoff Thank you for your report. :+1: 
That's `superagent.d.ts` definition for v0.15.
So, the latest version of `superagent` is changed the interface.
Please fix the definition file and send pull request, I'll review it :)

about: https://github.com/visionmedia/superagent/commit/e440274f56d2d4aff1e9edab4e5ef994ecfb48fa

**Comment by tkrotoff** [comment]
@horiuchi PR #6919

To make it clear: my writing was not about the API change (I did not know about that). It was about that TypeScript cannot type `res` in `.end(res => { ... })` when `CallbackHandler` takes 2 possible signatures (i.e `(...) | (...)`).
Now that SuperAgent `CallbackHandler` takes 1 signature instead of 2, it "solves" the problem (i.e without solving the underlying TypeScript issue).
