### ISSUE TITLE
due to the update on the `styled-components` the function `seal` is deprecated and no longer exists

### ISSUE THREAD

**Issue by emadbaqeri** [DefinitelyTyped/DefinitelyTyped#65020]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4e2081efcd3b2ddfc351c07391390847669e6b90/types/styled-components/index.d.ts#L387

**Comment by homersimpsons** [comment]
@emadbaqeri Maybe you should close this one in favor of #65021

**Comment by emadbaqeri** [comment]
Thanks for mentioning @homersimpsons
