### ISSUE TITLE
update angular material to 1.0.0

### ISSUE THREAD

**Issue by 0101adm** [DefinitelyTyped/DefinitelyTyped#6507]
https://github.com/angular/material/releases/tag/v1.0.0-rc1

**Comment by gmoothart** [comment]
This is out of date now, material is at 1.0.9:
https://github.com/angular/material/releases/tag/v1.0.9

**Comment by cwadrupldijjit** [comment]
I believe that this issue is irrelevant--the type definitions for Angular Material 1.x are already updated to version 1.1,
