### ISSUE TITLE
[TypeError: cheerio is not a function] with babel-node and Typescript ES6 mode when using cheerio(html)

### ISSUE THREAD

**Issue by tomduncalf** [DefinitelyTyped/DefinitelyTyped#6535]
I'm new to the Typescript world so might be misunderstanding how this should work, but from what I can see in https://github.com/borisyankov/DefinitelyTyped/pull/5688, `cheerio` should work with ES6 mode in Typescript. However, it seems that you cannot just call `cheerio(html)` - `tsc` will compile it fine, but `babel-node` spits out an error `TypeError: cheerio is not a function`. You instead have to call `cheerio.load(html)` and then interact with that (via `.root()` to get the `CheerioElement`).

Like I say, new to this so I may be making a rookie error here! I've uploaded a simple test case demonstrating what I mean: https://github.com/tomduncalf/cheerio-testcase

**Comment by tomduncalf** [comment]
I should add, while it's possible to work around loading a document with `cheerio.load`, I can't work out how to do code like the following: `let links = $html.find('a').toArray().filter(link => cheerio(link).attr('href').indexOf('youtube') > -1);` (as `cheerio is not a function`).

I did just realise I'm not sure if this is even a DefinitelyTyped issue, if not then apologies and if you could point me in the right direction, it would be greatly appreciated!

**Comment by karak** [comment]
Ah, should `cheerio(html)` cause compile error, as you say?
@tomduncalf Which do you mean?

**Comment by tomduncalf** [comment]
To be honest I’ve not worked with cheerio for a couple of years so can’t remember. I’ll close this for now as it’s probably invalid.

**Comment by karak** [comment]
@tomduncalf 
Thank you for your response.  All right.
BTY, the latest TS update might help you that provides compatibility of `import` with babel.
https://github.com/Microsoft/TypeScript/pull/19675
