### ISSUE TITLE
atob & btoa should not be marked as deprecated in NodeJS

### ISSUE THREAD

**Issue by jimmywarting** [DefinitelyTyped/DefinitelyTyped#65494]
Yes. they have marked it as legacy... and they recommend using typed arrays instead.
but it's definitely not deprecated. atob/btoa is still useful for simple things.

it's not something that is ever gona go away...

**Comment by Semigradsky** [comment]
I may propose to remain `Legacy.` in description:
![image](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/1198848/1bb3343a-5d1f-4a59-bec0-ee5e376b479c)
Will it be acceptable for you?

Or are you against using `@deprecated` JSDoc tag here?

**Comment by jimmywarting** [comment]
Could keep saying that it's legacy.
but remove the `@deprecated` and i would prefer if the message said "Legacy, Use typed arrays instead."
of recommending that ppl should use the NodeJS specific node:modules

**Comment by panva** [comment]
@Semigradsky see the original thread in the node project https://github.com/nodejs/node/issues/40754

The only issue we have is the use of @deprecated, the rest is okay for node-specific types.

**Comment by Semigradsky** [comment]
Ok, `@deprecated` is not appropriate here. This can confuse users and cause inconvenience when using tools like https://github.com/gund/eslint-plugin-deprecation.

Currently JSDoc tags are automatically generated from Node.js doc I will try to change it so it doesn't generate `@deprecated` for 'legacy' things.

**Comment by jimmywarting** [comment]
The dom lib atob/btoa dose not say it's deprecated.

i would honestly just wish for web platform APIs such as DOMException, web streams, TextEncoder, Blob, FormData, etc (including atob/btoa) could just be put into a shared library instead. see https://github.com/microsoft/TypeScript/issues/43972
