### ISSUE TITLE
[@types/memory-cache] del should return boolean, not void

### ISSUE THREAD

**Issue by thieman** [DefinitelyTyped/DefinitelyTyped#65622]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65619

<div type='discussions-op-text'>

<sup>Originally posted by **sosoxuc** May 28, 2023</sup>
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/memory-cache/index.d.ts#L12

[@types/memory-cache] `del` has wrong return type

Should not `del` has boolean return type? </div>

**Comment by younes-io** [comment]
@thieman I agree, `del` should have the `bool` type to indicate to the consumer whether the item has been successfully deleted or not.

**Comment by thieman** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65623.
