### ISSUE TITLE
Single definitions package for multiple libraries with the same API

### ISSUE THREAD

**Issue by owo** [DefinitelyTyped/DefinitelyTyped#65686]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65661

<div type='discussions-op-text'>

<sup>Originally posted by **owo** June  1, 2023</sup>
I'm working on a definitions package for [Skia Pathkit](https://skia.org/docs/user/modules/pathkit/) which provides two versions of the library, one for [WASM](https://www.npmjs.com/package/pathkit-wasm) and one for [asm.js](https://www.npmjs.com/package/pathkit-asmjs).

Both versions have the exact same API, the only difference is how you import them:

<br/>

```typescript
import PathKitInit from 'pathkit-wasm/bin/pathkit.js'
// vs
import PathKitInit from 'pathkit-asmjs/bin/pathkit.js'
```

<br/>

Can I just create a single definitions package called `pathkit` that supports both those libraries or should I have one package per library? It would be a hassle to manage what are essentially two duplicate definitions.

<br/>

If I were to use a single package, how should the starting comment line in `index.d.ts` be written?
I was thinking something like:

<br/>

```typescript
// Type definitions for pathkit-wasm 1.0 and pathkit-asmjs 1.0
```
</div>

**Comment by jakebailey** [comment]
You need to have two; you can re-export everything from one to another if that makes thing easier.
