### ISSUE TITLE
refreshFilters should be refreshFilter

### ISSUE THREAD

**Issue by dujavi** [DefinitelyTyped/DefinitelyTyped#65802]
refreshFilters() is undefined. It should be refreshFilter().

Thanks for you hard work!

Link to line: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/37f59bd0893549e5d3a76158ede7abc813f12e8c/types/tabulator-tables/index.d.ts#LL2886C18-L2886C18

**Comment by Noothan-am** [comment]
hey @dujavi,please assign it to me i will fix it

**Comment by dujavi** [comment]
I don't think I can assign it to you.

**Comment by handipriyono** [comment]
Hi @dujavi  , i think case this has been fixed.
With the new version -> https://www.npmjs.com/package/@types/tabulator-tables
version `5.4.9` 
please closed this issue. 
Thanks.
