### ISSUE TITLE
Lodash some methods missing in LoDashExplicitArrayWrapper

### ISSUE THREAD

**Issue by xuyang2** [DefinitelyTyped/DefinitelyTyped#6586]
TypeScript code (from https://lodash.com/docs#chain):

	var users = [
		{ 'user': 'barney',  'age': 36 },
		{ 'user': 'fred',    'age': 40 },
		{ 'user': 'pebbles', 'age': 1 }
	];

	var youngest = _.chain(users)
		.sortBy('age')
		.map(function(chr) {
			return chr.user + ' is ' + chr.age;
		})
		.first()
		.value();

tsc compiler complaints:

	error TS2339: Property 'sortBy' does not exist on type 'LoDashExplicitArrayWrapper<{ 'user': string; 'age': number; }>'.

the same happens with `pluck`

**Comment by chrootsu** [comment]
Yep, I work on it and if you write which of methods are interesting for you, I'll add them first.

**Comment by vvakame** [comment]
by #6600 :+1:

**Comment by joe-chung** [comment]
Still broken

**Comment by joe-chung** [comment]
error TS2339: Property 'first' does not exist on type 'LoDashEx
plicitArrayWrapper<string>'.

**Comment by chrootsu** [comment]
@joe-chung yep, there are some problems in the module definition and they make difficult adding of signatures `first` (and some other methods) right now

**Comment by thakursagar** [comment]
Property 'some' does not exist on LodashWrraper<any[]>

**Comment by thakursagar** [comment]
Property 'some' does not exist on type 'LodashWrapper<any[]>

**Comment by thakursagar** [comment]
```
Property 'some' does not exist on type 'LodashWrapper<any[]>'
```

**Comment by chrootsu** [comment]
@thakursagar The interface `LodashArrayWrapper` does not exist in the definition of `lodash` for a long time. Please check that you use the latest version of the definition. The method `some` already should work fine.

**Comment by gamebox** [comment]
Do you want me to submit a PR for _.reduce in the LoDashExplicitArrayWrapper ?  This would be helpful for us

**Comment by kenjiru** [comment]
@gamebox Yeah, please add _.reduce, it's definitely missing.

**Comment by jruddell** [comment]
need `_.uniqBy` as well

**Comment by rbcasperson** [comment]
also `_.flattenDepth()`

**Comment by zourtney** [comment]
and `_.sort`

**Comment by shashu10** [comment]
and _.sortby

**Comment by hhsadiq** [comment]
and _.split

**Comment by max0x7ba** [comment]
`_.flatMap` please

**Comment by alexeden** [comment]
@chrootsu `_.update` and `_.updateWith` please :)

**Comment by QimatLuo** [comment]
Property 'mean' does not exist on type 'LoDashStatic'.

**Comment by veganson** [comment]
Please add _(x).split

**Comment by RecuencoJones** [comment]
Same issue: `Property 'split' does not exist on type 'LoDashExplicitWrapper<string>'`

**Comment by charleshimmer** [comment]
`_.keyBy` seems to be missing as well

**Comment by anvesh48** [comment]
_.findWhere is also missing. Can you please add this aswell...

**Comment by Sebascn** [comment]
_.trim seems to be missing as well.

**Comment by JonAtOlo** [comment]
as is _.assign

**Comment by luisaceituno** [comment]
_.flatMapDeep please? :)

**Comment by webzfactory** [comment]
_.map

**Comment by ssalka** [comment]
Not sure why this is closed...there seems to be a bunch of methods missing from the typings (`_.uniqWith` for me)

**Comment by markoblad** [comment]
and `_.find`
`Property 'find' does not exist on type 'LoDashExplicitObjectWrapper<{}>'.`

**Comment by markoblad** [comment]
and `_.find`
on both
`Property 'find' does not exist on type 'LoDashExplicitObjectWrapper<{}>'.`
and
`Property 'find' does not exist on type 'LoDashExplicitArrayWrapper<{}[]>'`

**Comment by dunecatnat** [comment]
and _.pairs
`Property 'pairs' does not exist on type 'LoDashStatic'.`

**Comment by omarjmh** [comment]
_.include as well

**Comment by jakachira** [comment]
_.divide too

**Comment by Nibblesh** [comment]
_.deepClone also

**Comment by hejiaji** [comment]
whatever goes after _.chain would have this error, plz help to fix it @chrootsu @rbcasperson

**Comment by sinedied** [comment]
_.map also...

**Comment by anrepppp** [comment]
Property 'sortByOrder' does not exist on type 'LoDashStatic'

**Comment by lenovouser** [comment]
I checked the comments above, and these appear to be still missing:

```
_.divide();
_.include();
_.pairs();
```

**Comment by vguzev** [comment]
This bug should be reopened as a lot of methods (mentioned above) still do not have correct typings.

**Comment by yahyaKacem** [comment]
Also [transform](https://lodash.com/docs/4.17.4#transform) is missing too,
reported separately by someone else here #14748

**Comment by yahyaKacem** [comment]
A workaround may be like this:
```
(lodash.chain(stuff).pickBy(lodash.isArray) as any).transform(transformFunction, []).value();
```

**Comment by ahmedisadaf** [comment]
_.mapValues() does not exist on UnderscoreStatic. This method is missing from lodash Kindly update.

**Comment by itzikedar** [comment]
it seems that _mapValues is not include in the chain but working as stand alone

**Comment by bborowin** [comment]
Property 'keys' does not exist on type 'LoDashImplicitArrayWrapper<any>'

**Comment by remborg** [comment]
Property 'length' is missing in type 'LoDashImplicitArrayWrapper<...>'

**Comment by maxmarkus** [comment]
Property 'differenceWith' does not exist on type 'LoDashImplicitObjectWrapper<any>'.

**Comment by Lonli-Lokli** [comment]
Please ensure that you call https://lodash.com/docs/#prototype-value on the end of your chain

**Comment by abhiphirke** [comment]
_.times please

**Comment by uzilan** [comment]
_.partition please

**Comment by jituanlin** [comment]
_.cond Please

**Comment by ihardik** [comment]
_.next also please

**Comment by ingoncalves** [comment]
_.upperCase please

**Comment by nasreddineskandrani** [comment]
chain(blabla).mapValues() 
result on tslint error
`Property 'mapValues' does not exist on type 'LoDashExplicitObjectWrapper<{}>'.`

**Comment by chetmurphy** [comment]
_.where also missing.

**Comment by procedurallygenerated** [comment]
_.where and _.findWhere

Is everyone getting the typing you asked for :)

Seems like this thread has been open for a while.

**Comment by charlesr1971** [comment]
This almost works, but .pickBy is also subject to this problem!

(lodash.chain(stuff).pickBy(lodash.isArray) as any).transform(transformFunction, []).value();

**Comment by charlesr1971** [comment]
_.uniqWith please

**Comment by charlesr1971** [comment]
Is there are any way we can fix this ourselves?

This thread is a few years old and there are still functions that do not work!

**Comment by nguyennb9** [comment]
@charlesr1971 I have the issue with `_.uniqWith` too, it seems that the function still works but the interface is not defined it yet.

**Comment by jsdmaria** [comment]
Property 'length' is missing in type ... but required in type ...
Do this for _.chunk, please

**Comment by AN-SANGJUN** [comment]
In lodash chain(), when i use `import chain from 'lodash/chain` and `chain(value).split('.')` it makes an error.
In below commit, LoDash fixed LoDashExplicitWrapper, but it creates another side effect which does not have split  in prototype but can use split.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10717/commits/fdddacc2e801364decd875dee45bbaf90110631d

**Comment by Asghwor** [comment]
_.flatten please

**Comment by Leha1992** [comment]
_.omit please
