### ISSUE TITLE
var f1 = _({a:1}).assign({b:2}).value();

### ISSUE THREAD

**Issue by co-dh** [DefinitelyTyped/DefinitelyTyped#6589]
the above line failed to type with error TS2339: Property 'value' does not exist on type '{}'.

**Comment by vvakame** [comment]
um? lodash? underscore?

**Comment by co-dh** [comment]
loadash. 
I figured out that I need to give _assign type parameters to make it work. Is it possible to not give type parameters? or there are too many overloads that we have too?

**Comment by vvakame** [comment]
@chrootsu ?

**Comment by chrootsu** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6631
