### ISSUE TITLE
Sinon adds undefined to tsd.d.ts

### ISSUE THREAD

**Issue by nicky-lenaers** [DefinitelyTyped/DefinitelyTyped#6593]
I recently noticed that installing sinon using ``tsd install sinon --save`` adds a line with the text ``undefined`` to my ``tsd.d.ts`` file. When trying to install another typings file using ``tsd``, both the ``undefined`` **and** ``/// <reference path="sinon/sinon.d.ts" />`` lines are removed.

Running Win10 64x.

**Comment by vvakame** [comment]
please report to tsd repo.
