### ISSUE TITLE
React.createElement doesn't type check props

### ISSUE THREAD

**Issue by jameslong** [DefinitelyTyped/DefinitelyTyped#6608]
React.createElement doesn't seem to be type checking its second argument:

        /// <reference path="../typings/react/react.d.ts" />

        export class Test extends React.Component<{ a: string }, any> {
                render () {
                        return null;
                }
        }

        React.createElement(Test, 5);

Should not compile, but it gives no warnings. Is this a missing type declaration?

**Comment by mijay** [comment]
Have the same issue. Any update?

**Comment by vvakame** [comment]
please ping to definition authors.

**Comment by vsiao** [comment]
I believe this has since been fixed.
