### ISSUE TITLE
 Improve pinning of permissive dependencies

### ISSUE THREAD

**Issue by diogoteles08** [DefinitelyTyped/DefinitelyTyped#66136]
Hi! I'm Diogo and I'm back (see [#63492](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/63592)) hoping to offer a bit more help with security enhancements.

I noticed that some of your workflows (namely [UpdateCodeowners.yml](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/workflows/UpdateCodeowners.yml), [ghostbuster.yml](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/workflows/ghostbuster.yml) and [support-window.yml](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/workflows/support-window.yml)) are using `contents: write`  permissions and secrets while running unpinned external dependencies -- both external github actions and npm packages. This could make your secrets and source code vulnerable in case a dependency gets hijacked and changes the code your tags are pointing to.

A simple and effective way to eliminate that attack vector is to hash-pin the relevant dependencies, which ensures that the code you're calling won't be changed. Dependabot would still be able to suggest updates to the hash-pinned dependencies, also keeping comments next to the dependencies with their human-readable version.

If you have interest, I'd be happy to elaborate on the changes needed and possibly raise a PR implementing them.

Cheers,

**Comment by diogoteles08** [comment]
Hey @andrewbranch! This issue has been idle for quite some time. Does the team plan on considering these suggestions? Let me know and I can happily follow up with a PR.

If not interested, I'll probably wait up to 2 more months and close the issue.

Thanks!

**Comment by jakebailey** [comment]
If you want to send a PR to pin GHA stuff + dependabot like the other TS repos, that's totally fine.
