### ISSUE TITLE
Where is Points class?

### ISSUE THREAD

**Issue by zawawahoge** [DefinitelyTyped/DefinitelyTyped#6624]
I don't find Points class three.d.ts.

**Comment by vvakame** [comment]
@gyohk ?

**Comment by gyohk** [comment]
THREE.Point class has been added from r72. This definition file is based on r71, and I'm going to update to the latest version soon. please wait a few days.

**Comment by gyohk** [comment]
THREE.Point class has been added from r72.
This definition file is based on r71, and I'm going to update to the latest version soon.
Please wait a few days.

**Comment by zawawahoge** [comment]
@gyohk I see. I am looking forward to the release.
