### ISSUE TITLE
Getting error installing sequelize on node-version 18.17.1 [@types/sequelize-cursor-pagination]

### ISSUE THREAD

**Issue by shahabali1993** [DefinitelyTyped/DefinitelyTyped#66599]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/66595

<div type='discussions-op-text'>

<sup>Originally posted by **shahabali1993** September  4, 2023</sup>
I was trying to install sequelize on node-version **18.17.1** and on compilation got this error

```
$ yarn compile
yarn run v1.22.19
$ tsc
node_modules/@types/sequelize-cursor-pagination/index.d.ts:50:40 - error TS2344: Type 'ModelInst' does not satisfy the constraint '{}'.
50         <Model extends Sequelize.Model<ModelInst, ModelAttrs>, ModelInst, ModelAttrs>(model: Model) => WithPaginationModel<MethodName, Model, ModelInst, ModelAttrs>
                                          ~~~~~~~~~

  node_modules/@types/sequelize-cursor-pagination/index.d.ts:50:64
    50         <Model extends Sequelize.Model<ModelInst, ModelAttrs>, ModelInst, ModelAttrs>(model: Model) => WithPaginationModel<MethodName, Model, ModelInst, ModelAttrs>


Found 1 error in node_modules/@types/sequelize-cursor-pagination/index.d.ts:50
```

I went to file index.d.ts in node_modules folder and added **extends {}** with ModelInst and ModelAttrs which fixed the issue
I have shown the fix below

```
    function withPagination<MethodName extends string = 'paginate'>(options?: WithPaginationOptions<MethodName>): (
        <Model extends Sequelize.Model<ModelInst, ModelAttrs>, ModelInst extends {}, ModelAttrs extends {}>(model: Model) => WithPaginationModel<MethodName, Model, ModelInst, ModelAttrs>
    );
```</div>

**Comment by shahabali1993** [comment]
@pilagod

**Comment by shahabali1993** [comment]
@peterblazejewicz @Methuselah96 @nikcorg @pilagod can you please look into it?

**Comment by pilagod** [comment]
Hello @shahabali1993, this declaration is aim for v1.2, whereas their latest version is now v3.4, so I think the types here are outdated for a long period.

And I see  `sequelize-cursor-pagination` has already switched to TypeScript as its default language, maybe you could try to use it without installing additional types.

**Comment by shahabali1993** [comment]
Thanks @pilagod for the quick response, I did some digging and found out we don't need sequelize-cursor-pagination anymore.

**Comment by peterblazejewicz** [comment]
Closing
fyi: I'll try to phase out current types as no longer required, thx!

**Comment by peterblazejewicz** [comment]
fyi: #66622
