### ISSUE TITLE
Suggestion: make clearer how to install types for a scoped module

### ISSUE THREAD

**Issue by stevage** [DefinitelyTyped/DefinitelyTyped#66612]
I was attempting to install types for `@mapbox/mapbox-gl-draw`.

I can't see anything in the user instructions for how to do this.

If you go all the way to the very bottom of the README there is an instruction to package creators:

> Types for a scoped package @foo/bar should go in types/foo__bar. Note the double underscore.

IMHO that information should be much more prominent for users.

**Comment by jakebailey** [comment]
#68552
