### ISSUE TITLE
Want to use @types/node-ipc and NOT the ones in @node-ipc/node-ipc

### ISSUE THREAD

**Issue by randyram-at-ms** [DefinitelyTyped/DefinitelyTyped#66669]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/66668

<div type='discussions-op-text'>

<sup>Originally posted by **randyram-at-ms** September 11, 2023</sup>
The @node-ipc/node-ipc package provides types that are wrong, see: https://github.com/node-ipc/node-ipc/issues/4

The DefinitelyTypes ones in @types/node-ipc are great, I want to use those.  

If I `import IPC from 'node-ipc'` I get the @types/node-ipc definitions and tsc loves me.  But at runtime, 'node-ipc' is not found because it's installed in node_modules in the @node-ipc/node-ipc directory.

How can I effectively override the incorrect types provided by @node-ipc/node-ipc while still getting it to load at runtime?</div>

**Comment by jakebailey** [comment]
There is no way to do this besides patching the fork using patch-package or pnpm's built-in patching. If a package ships with types, they are always used.

At best, you could instead publish a library without types which re-exports from the fork, then pull that in like:

```json
{
    "dependencies": {
        "node-ipc": "npm:@username/node-ipc-wrapper"
    }
}
```

But, there's no action that can be taken by DT, so, closing.
