### ISSUE TITLE
media queries in foundation typings

### ISSUE THREAD

**Issue by samvloeberghs** [DefinitelyTyped/DefinitelyTyped#6668]
Hi @borisyankov,

Is there a specific reason why you did not put the media queries in the foundation typing?
http://foundation.zurb.com/docs/javascript-utilities.html#media-queries

Just asking before I consider doing a pull request.

Sam V.

**Comment by borisyankov** [comment]
No good reason ;)
They are either newer or they were just missed.
A pull request is more than welcome ;)

**Comment by samvloeberghs** [comment]
done & closing:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6669
