### ISSUE TITLE
[lodash] _.forEach iteratee return type is too strict.

### ISSUE THREAD

**Issue by optical** [DefinitelyTyped/DefinitelyTyped#6677]
The following contrived code segment does not compile
```javascript
interface Foo { };
let fooFactory: () => Foo = () => null;
_.forEach([1, 2, 3], () => fooFactory());
```
The error returned by the compiler is `error TS2345: Argument of type 'number[]' is not assignable to parameter of type 'Dictionary<{}>'.
  Index signature is missing in type 'number[]'.`

The issue here is that the `_.forEach` definition only allows the iteratee to return boolean or void, which causes typescript some trouble when selecting the correct overload. This is a convenience problem when the body of the forEach loop is an arrow function which returns something that is not a boolean. The implementation of forEach only really cares if the returned value is exactly false, otherwise it is disregarded. 

I feel like the return type of the iterator function here should be loose, as this makes writing arrow functions slightly more inconvenient as you have to use block syntax to have a void return type. Additionally lodash really doesn't care if you return arbitrary data back.

@chrootsu - Looks like this is your change, any thoughts?

**Comment by chrootsu** [comment]
Thanks, you are absolutely right. Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6678 .

**Comment by optical** [comment]
PR Merged - closing
