### ISSUE TITLE
linq.d.ts : Fix for OrderedEnumerable<T>

### ISSUE THREAD

**Issue by STARSCrazy** [DefinitelyTyped/DefinitelyTyped#6699]
Please change "ThenBy" and "ThenByDescending" in "OrderedEnumerable<T>" (linq.d.ts).

Old:
ThenBy(keySelector: ($) => T): OrderedEnumerable<T>;
ThenByDescending(keySelector: ($) => T): OrderedEnumerable<T>;
New:
ThenBy(keySelector: ($: T) => any): OrderedEnumerable<T>;
ThenByDescending(keySelector: ($: T) => any): OrderedEnumerable<T>;

**Comment by vvakame** [comment]
please send a pull request. I'll review it.
