### ISSUE TITLE
[@types/http-signature] _RequestSigner.writeDataHeader should be _RequestSigner.writeDateHeader

### ISSUE THREAD

**Issue by karvapallo** [DefinitelyTyped/DefinitelyTyped#67023]
The `http-signature` typings have a misspelled method name. The typo in question is called `writeDataHeader` in the `_RequestSigner` class. The method name is `writeDateHeader` NOT `writeDataHeader`

**Comment by Mayank1728** [comment]
I would love to contribute!

**Comment by MysteryBlokHed** [comment]
> I would love to contribute!

I already opened a PR to fix the issue (#67025), but you can review/approve it if you’re interested?
