### ISSUE TITLE
[@types/codemirror: 5.60.11] can't import submodules

### ISSUE THREAD

**Issue by fengyon** [DefinitelyTyped/DefinitelyTyped#67093]
## the code  is

```
import CodeMirror from 'codemirror';
import 'codemirror/addon/mode/simple.js';

// define rule to highlight of batch
CodeMirror.defineSimpleMode('batch', {})
```

## the problem is 

```
Property 'defineSimpleMode' does not exist on type 'typeof CodeMirror'
```

## the possible reason is
the newest version of @types/codemirro has no `addon`、`mode` files, so can't import submodules

### 5.60.11
 https://www.npmjs.com/package/@types/codemirror/v/5.60.11?activeTab=code
files: 
```
LICENSE
README.md
index.d.ts
package.json
```

### 5.60.6
 https://www.npmjs.com/package/@types/codemirror/v/5.60.6?activeTab=code
```
addon/
mode/
LICENSE
README.md
index.d.ts
package.json
```

**Comment by jakebailey** [comment]
I'm not sure how this ever worked. The index.d.ts doesn't pull these files in so they should have needed an to be in extra_files.

**Comment by jakebailey** [comment]
https://app.renovatebot.com/package-diff?name=@types%2fcodemirror&from=5.60.10&to=5.60.11 does show the difference though I feel like the tooling had to have been bugged to allow for this to work undeclared.

**Comment by dfreeman** [comment]
It looks like `@types/ember`'s `-private` subdirectory [was hit by this as well](https://app.renovatebot.com/package-diff?name=@types%2fember&from=4.0.6&to=4.0.7) (granting that it's super weird that that directory is _only_ referenced from other packages)

**Comment by jakebailey** [comment]
We tested package publishing and did a diff before and after, so I don't really know what happened here.

I'm pretty sure the fix is to use EXTRA_FILES, not references.

**Comment by eMerzh** [comment]
as far as i can tell i think there a other packages affected as well  like autosuggest-highlight which now look kinda broken

https://app.renovatebot.com/package-diff?name=@types%2fautosuggest-highlight&from=3.2.0&to=3.2.1

**Comment by jakebailey** [comment]
autosuggest-highlight is now fixed, the rest should slowly get fixed; https://app.renovatebot.com/package-diff?name=@types%2fautosuggest-highlight&from=3.2.0&to=3.2.2

**Comment by jakebailey** [comment]
https://app.renovatebot.com/package-diff?name=@types%2fcodemirror&from=5.60.11&to=5.60.12 has added all of the files back.

https://app.renovatebot.com/package-diff?name=@types%2fcodemirror&from=5.60.10&to=5.60.12 shows the _intented_ change. Sorry about the breakage!
