### ISSUE TITLE
@types/google-protobuf 3.15.8 sub directory is not included

### ISSUE THREAD

**Issue by jishidaaaaa** [DefinitelyTyped/DefinitelyTyped#67100]
Until 3.15.7, [google/protobuf](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/google-protobuf/google/protobuf) directory was included in the deliverables
But from 3.15.8, it is not included.

Probably due to pnpm migration of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67085

Similar to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/67093

**Comment by jakebailey** [comment]
Hmmm, index.d.ts doesn't reference those files at all, they should have been in an extra files list I'm pretty sure.

**Comment by jakebailey** [comment]
I meant `OTHER_FILES.txt`, sorry!

**Comment by jakebailey** [comment]
This is a bug in the publisher; I am working on fix.

**Comment by jakebailey** [comment]
Fixed now for this package.

Bad change: https://app.renovatebot.com/package-diff?name=@types%2fgoogle-protobuf&from=3.15.7&to=3.15.8

Good change: https://app.renovatebot.com/package-diff?name=@types%2fgoogle-protobuf&from=3.15.8&to=3.15.9

Intended change: https://app.renovatebot.com/package-diff?name=@types%2fgoogle-protobuf&from=3.15.7&to=3.15.9

**Comment by jishidaaaaa** [comment]
@jakebailey 
We have confirmed that the issue has been fixed in 3.15.9.
Thank you for your support.
