### ISSUE TITLE
Issue with missing files in type packages after recent upage

### ISSUE THREAD

**Issue by liana-p** [DefinitelyTyped/DefinitelyTyped#67110]
Hello,

I noticed strange behaviours in type packages coming from DefinitelyTyped which I suspect have to do with the recent big changes. Some packages that have deep files (ie. when you import `package/some/file`) have those files missing compared to before.

For example, the [remarkable](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/451dc8fc19383bc12af59522020e571957f1684e/types/remarkable) package has a `linkify` folder. This folder is present in the last version of the package on npm, but not in the new one. You can see this by comparing the files on the two npm versions:

* [2.0.5](https://www.npmjs.com/package/@types/remarkable?activeTab=code) (published 4 hours ago). The `linkify` folder is missing
* [2.0.4](https://www.npmjs.com/package/@types/remarkable/v/2.0.4?activeTab=code) (21 days ago). The `linkify` folder is there

I'm not seeing anything in the package itself that would explain this, as it doesn't seem to have changed particularly, outside of the commits related to monorepo changes.

I also noticed the same thing on another package: [react-virtualized](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/451dc8fc19383bc12af59522020e571957f1684e/types/react-virtualized).

Similarly to this one, it has a `dist/commonjs` folder with various files, and if you compare the previous package with the new one, one file is missing:

* [9.21.24](https://www.npmjs.com/package/@types/react-virtualized?activeTab=code) (4 hours ago): `List.d.ts` is missing
* [9.21.23](https://www.npmjs.com/package/@types/react-virtualized/v/9.21.23?activeTab=code) (21 days ago): `List.d.ts` is present

I suspect those files are being purged from the published package because they're not being imported by `index.d.ts`, possibly? You could say that ideally projects should only use types from the main package, but this change breaks imports like (in those two cases):

* `import { linkify } from 'remarkable/linkify';`
* `import { List } from 'react-virtualized/dist/commonjs/List';`

Those imports are valid, but their types have disappeared so the typescript compiler won't let them happen on the new version.

I don't think this is due to changes in the individual packages but something wrong with DefinitelyTyped publishing to npm.

I have also noticed another package having the same issue with a folder import, but haven't investigated yet if it's the same issue as at this point I assume it is.

**Comment by jakebailey** [comment]
This is currently being fixed; the publisher is fixing this A to Z and it's currently at the letter D.

**Comment by jakebailey** [comment]
remarkable has `linkify` again: https://www.npmjs.com/package/@types/remarkable?activeTab=code

react-virtualized does as well: https://www.npmjs.com/package/@types/react-virtualized?activeTab=code
