### ISSUE TITLE
Lint conflicts after pnpm LSC

### ISSUE THREAD

**Issue by appsforartists** [DefinitelyTyped/DefinitelyTyped#67113]
@jakebailey 

First, I can't imagine what a pain it must be making a large scale change on a git repo, one that's so big that its own README recommends using `sparse-checkout`.  Thanks for your efforts to make the commons better!

I [merged a new type two weeks ago](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/colab/index.d.ts) and am [trying to make a minor edit](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67112).  As requested, I installed `pnpm` and tried to run the tests.

First, I got snagged here:

```
~/Projects/DefinitelyTyped/types/colab/tslint.json
{ "extends": "@definitelytyped/dtslint/dt.json" }

Error: If 'tslint.json' is present, it should extend "@definitelytyped/dtslint/dtslint.json"
```

Apparently the name of the common lint file was changed, but the rename was not included in the large-scale change.  That's a little frustrating for authors because it takes some parsing to realize that this is an LSC issue, not a locally-created problem.  

I caught this and changed the file; however, now I'm getting this:

```
~/Projects/DefinitelyTyped/types/colab/index.d.ts
  1:2  error  Error parsing header. Expected: /\/\/ Type definitions for (non-npm package )?/  @definitelytyped/dt-header
```

It appears the linter is requiring code that was removed in your LSC.  

It looks like `dt-header` is [still being maintained](https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/header-parser/src/index.ts).  

Should the `index.d.ts` header removal be reverted, or does the linter need to remove that rule?

**Comment by jakebailey** [comment]
Can you `git clean -fdx` your repo and start again? It sounds like you have an old copy of the toolchain sitting around.

**Comment by jakebailey** [comment]
FWIW `header-parser` is a bad name for it now, it now parses the `package.json`.

**Comment by jakebailey** [comment]
RE: the sparse checkout, I don't even think doing that is a good idea, though pnpm would probably handle it gracefully. A blobless clone is better if you don't need the full git history by default.

**Comment by appsforartists** [comment]
```
$ git clean -fdx
Removing node_modules/
Removing yarn.lock
$ pnpm install
Scope: all 2 workspace projects
Downloading registry.npmjs.org/@dprint/darwin-arm64/0.41.0: 5.99 MB/5.99 MB, done
 WARN  6 deprecated subdependencies found: @gitbeaker/node@35.8.1, @npmcli/move-file@2.0.1, har-validator@5.1.5, request@2.88.2, uuid@3.4.0, w3c-hr-time@1.0.2
Packages: +815
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading registry.npmjs.org/typescript/5.3.0-dev.20231018: 5.75 MB/5.75 MB, done
Progress: resolved 820, reused 0, downloaded 815, added 815, done
Done in 18.9s
$ pnpm test colab

> definitely-typed@0.0.3 test ~/Projects/DefinitelyTyped
> node --require source-map-support/register node_modules/@definitelytyped/dtslint/ types "colab"

dtslint@0.0.183
Error: 'tslint.json' must extend "@definitelytyped/dtslint/dt.json"
    at checkTslintJson (~/Projects/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint@0.0.183_typescript@5.3.0-dev.20231018/node_modules/@definitelytyped/dtslint/src/lint.ts:186:11)
    at testTypesVersion (~/Projects/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint@0.0.183_typescript@5.3.0-dev.20231018/node_modules/@definitelytyped/dtslint/src/index.ts:195:18)
    at runTests (~/Projects/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint@0.0.183_typescript@5.3.0-dev.20231018/node_modules/@definitelytyped/dtslint/src/index.ts:170:13)
    at main (~/Projects/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint@0.0.183_typescript@5.3.0-dev.20231018/node_modules/@definitelytyped/dtslint/src/index.ts:83:5)
 ELIFECYCLE  Test failed. See above for more details.
 ```

**Comment by jakebailey** [comment]
Not really sure what is going on:

```console
$ git clean -fdx -e '/.vscode' -e '/.env'
$ pnpm install -w --filter '...{./types/colab}...'
Scope: 2 of 9116 workspace projects
 WARN  6 deprecated subdependencies found: @gitbeaker/node@35.8.1, @npmcli/move-file@2.0.1, har-validator@5.1.5, request@2.88.2, uuid@3.4.0, w3c-hr-time@1.0.2
.                                        | +800 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 805, reused 800, downloaded 0, added 800, done
Done in 6s
$ pnpm test colab

> definitely-typed@0.0.3 test /home/jabaile/work/DefinitelyTyped
> node --require source-map-support/register node_modules/@definitelytyped/dtslint/ types "colab"

dtslint@0.0.183
```

There's nothing _wrong_ with a sparse checkout per se, but you won't get any packages your package depends on or packages that depend on your package. A blobless clone would be like:

```console
$ git clone --filter blob:none git@github.com:DefinitelyTyped/DefinitelyTyped.git
```

I do see that the above is basically already what the readme says but without `--sparse`. You can de-sparse by running:

```console
$ git sparse-checkout disable
```

**Comment by appsforartists** [comment]
I forgot to revert the unstaged change to `tslint` to work around the original error.  After I deleted that change, it worked.

Perhaps there should be something like 

## Migration guide
If you checked out DefinitelyTyped before the Oct 17 2023 `pnpm` upgrade, you should reinstall `node_modules`:
```bash
# if you don't have pnpm installed:
yarn global add pnpm # or npm install -g pnpm
# remove untracked files, like node_modules
git clean -fdx
# setup your local clone with pnpm
pnpm install
```

**Comment by jakebailey** [comment]
Theoretically doing `pnpm install` will actually get rid of the old `node_modules`; I did add https://github.com/DefinitelyTyped/DefinitelyTyped#-important-this-repo-has-recently-changed-layout- but maybe we could do better. It'd only be temporary, though.

Note that you don't need to do a full `pnpm install` if you don't want to; the readme has some info on how to filter things, though a full install isn't all that bad.

**Comment by appsforartists** [comment]
I did see that headline, but I didn't notice anything.  At the very least, reminding people to re-run `install` after the change seems prudent.  It hadn't occurred to me that I'd have out of date dependencies.
