### ISSUE TITLE
[@types/node]DangerBotOSS

### ISSUE THREAD

**Issue by peterblazejewicz** [DefinitelyTyped/DefinitelyTyped#67205]
Please see this:
#67202

Usually bot reports issues within package itself, not within packages referencing PR being part of PR change.
In case of PR touching @types/node, this results in counter-productive input from DangerBotOSS IMO

thx!

**Comment by jakebailey** [comment]
I have no idea where those comments are coming from; danger doesn't run when the CI fails because it comes after the tests. In that PR, tests fail, which means that danger never ran at all. It's like someone else is pushing these comments.

**Comment by jakebailey** [comment]
Oh, seems like DT-tools is treating these packages as modified, not dependent.

**Comment by jakebailey** [comment]
Fix is merged, will release in a bit.
