### ISSUE TITLE
Why *shouldn't* <my-package>-tests.ts run?

### ISSUE THREAD

**Issue by DanKaplanSES** [DefinitelyTyped/DefinitelyTyped#67354]
The README says, "This [\<my-package\>-tests.ts] contains sample code which tests the typings. This code does *not* run, but it is type-checked." Why *shouldn't* this run? Wouldn't this reduce the possibility of types getting out of sync with the runtime? 

PS: I hope it's okay that I'm posting this as an issue. I was going to make it a Discussion, but [a pinned post says, "For larger systemic questions/reports, please use Issues."](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/53392)

**Comment by jakebailey** [comment]
Running that code is effectively arbitrary code execution; the only thing this repo should do is typecheck and other safe static analysis operations.

Examples are also usually garbage weird code that shouldn't be run even if it could; it's set up to check types and may not even be representative of the real usage.
