### ISSUE TITLE
The [@types/fixed-data-table-2] is missing types for ```Plugins.ResizeCell``` and ```Plugins.ReorderCell```

### ISSUE THREAD

**Issue by daniela-mateescu** [DefinitelyTyped/DefinitelyTyped#67372]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/67371

<div type='discussions-op-text'>

<sup>Originally posted by **daniela-mateescu** November 10, 2023</sup>
In the latest version of the FDT2 library, the ```Plugins.ResizeCell``` and ```Plugins.ReorderCell``` are needed for configuring a table with resizable/reordable column.  </div>

**Comment by daniela-mateescu** [comment]
I have created a pull request that fixes this issue: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67373

**Comment by timagixe** [comment]
@daniela-mateescu could you please close this issue since https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67373 has been merged?

**Comment by daniela-mateescu** [comment]
Thank you for the merge. I closed it.
