### ISSUE TITLE
DTS-GEN is not up to date

### ISSUE THREAD

**Issue by ScreamZ** [DefinitelyTyped/DefinitelyTyped#67396]
`npx dts-gen` doesn't include `.npmignore` by default

```
*
!**/*.d.ts
!**/*.d.cts
!**/*.d.mts
!**/*.d.*.ts
``` 

Also from #67241 `dts-gen` doesn't ship good version by default (see last comment)

Just tested with my new package : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67395

**Comment by jakebailey** [comment]
https://github.com/microsoft/dts-gen/pull/189 will fix this.
