### ISSUE TITLE
Issue with [@types/chrome] package for pageCapture

### ISSUE THREAD

**Issue by zyucan** [DefinitelyTyped/DefinitelyTyped#67545]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/67544

<div type='discussions-op-text'>

<sup>Originally posted by **zyucan** November 29, 2023</sup>
**Description of the problem:**

The `chrome.pageCapture.saveAsMHTML` API in Chrome Extension v3 now supports returning a promise(https://developer.chrome.com/docs/extensions/reference/pageCapture/#method-saveAsMHTML), but the TypeScript declarations in @types/chrome do not yet support this change. This is causing issues for developers who are working with this API in a TypeScript environment.

**Suggested Solution:**

Add support for the updated `chrome.pageCapture.saveAsMHTML` API in the @types/chrome declarations.</div>

**Comment by timagixe** [comment]
As far as I understood, according to the docs,

> Promises are supported in Manifest V3 and later, but callbacks are provided for backward compatibility. You cannot use both on the same function call. The promise resolves with the same type that is passed to the callback.

`saveAsMHTML` should have type like:
```ts
export function saveAsMHTML(details: SaveDetails): Promise<Blob>;
export function saveAsMHTML(details: SaveDetails, callback: (mhtmlData?: Blob) => void): void;
```

@zyucan could you please confirm this? I would like to contribute this change.

**Comment by zyucan** [comment]
I think the promise version should be: `export function saveAsMHTML(details: SaveDetails): Promise<Blob | undefined>;` because "mthmlData" may be undefined. @timagixe
