### ISSUE TITLE
TSC Build Error When Import is Used

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/DefinitelyTyped#6804]
Using the TypeScript statement
    `import * as appInsights from "applicationinsights";`

Results in the build failure:
`TS2497: Module '"applicationinsights"' resolves to a non-module entity and cannot be imported using this construct.`

**Comment by frankbenoit** [comment]
I get the same problem for importing nedb.
Have you found a work around?

**Comment by frankbenoit** [comment]
meanwhile found a workaround for my case ...
import NeDBDataStore = require("nedb");
