### ISSUE TITLE
Proposal: git hook to format files

### ISSUE THREAD

**Issue by tpluscode** [DefinitelyTyped/DefinitelyTyped#68133]
Formatting rules changed and now every time I update packages, I get the danger bot suggesting to run `pnpm dprint fmt`

Would you accept a PR with a github pre-commit hook (I'd go with [husky](https://npm.im/husky)) to automatically format changed files?

**Comment by oxwazz** [comment]
yea i think so +1

**Comment by jakebailey** [comment]
If we have anything, it should be optional and have a script to enable it (like https://github.com/microsoft/TypeScript/blob/main/package.json#L98). An autoformat can be harmful and annoying when making major infrastructure changes, and one of the design goals of the new formatting was that it would not be required.

**Comment by tpluscode** [comment]
Husky can totally be set up like that. Recommended usage is to have a postinstall script which creates the git hook. It could totally be made opt-in, similar to that TS link

**Comment by jakebailey** [comment]
FWIW you can also install dprint in vscode and format on save, which works very well.

Feel free to send a PR and ping me, but a postinstall is not an optional thing (and we ban package.json preinstall/postinstall scripts in the repo anyhow).

**Comment by tpluscode** [comment]
I mean, the setup script does not have to be `postinstall`. Does not need to be a script at all. One could simple run `npx husky install`

Will do the PR
