### ISSUE TITLE
[@types/validator] Cannot find namespace 'ValidatorJS'. Did you mean 'validator'?

### ISSUE THREAD

**Issue by kabamrrichman** [DefinitelyTyped/DefinitelyTyped#68152]
13.11.8 introduced build errors. I had to use 13.11.7 instead of 13.11.8.
`Error: ../../node_modules/class-validator/types/decorator/string/IsAlpha.d.ts(8,58): error TS2833: Cannot find namespace 'ValidatorJS'. Did you mean 'validator'?`

_Originally posted by @kabamrrichman in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/68121#issuecomment-1884113872_

**Comment by benasher44** [comment]
@kabamrrichman apologies! I'll take a look and work on a fix ASAP

**Comment by benasher44** [comment]
It looks like it's failing in class-validator package. What version are you using, so I can test?

**Comment by benasher44** [comment]
@kabamrrichman could also share your TypeScript version? It looks like that package is just doing a default import, which is covered by tests:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fba2208ba57cf9d675dc8de2cbca975b5b57b5cc/types/validator/validator-tests.ts#L1

**Comment by benasher44** [comment]
tsconfig.json would be great too!

**Comment by kabamrrichman** [comment]
class-validator@0.14.0
```json
"compilerOptions": {
	"module": "commonjs",
	"esModuleInterop": true,
	"moduleResolution":"Node",
	"target": "ES6",
	"noImplicitAny": true,
	"sourceMap": true,
	"allowJs": true,
	"allowSyntheticDefaultImports": true,
	"strict": true,
	"forceConsistentCasingInFileNames": true,
	"resolveJsonModule": true,
	"isolatedModules": true,
	"declaration": true,
	"outDir": "./dist",
	"noUncheckedIndexedAccess": true
}
```

**Comment by benasher44** [comment]
Thanks! And does your project have any other dependencies on @types/validator? Like does it have multiple versions installed?

Googled this issue, and it looks like people have run into this issue over the years (even with class-validator specifically) with multiple versions with slightly incompatible definitions installed.

**Comment by kabamrrichman** [comment]
> Thanks! And does your project have any other dependencies on @types/validator? Like does it have multiple versions installed?
> 
> Googled this issue, and it looks like people have run into this issue over the years (even with class-validator specifically) with multiple versions with slightly incompatible definitions installed.

Only class-validator@0.14.0 and @types/validator@13.11.7 (13.11.8 when issue occurred)

**Comment by marcovanetti** [comment]
We fixed our projects adding to the package.json
```
"overrides": {
    "@types/validator": "13.11.7"
 }
```
we know it's a temporary solution until the bug is fixed.

**Comment by dineshneoito** [comment]
Issue happened due to https://github.com/DefinitelyTyped/DefinitelyTyped/commit/bf9914fb2d465433a4c324312091da185cedc0fa. In types/validator/index.d.ts, exporting is changed but not handled in validator package. with earlier version "@types/validator": "13.11.7", it will work.

**Comment by benasher44** [comment]
@marcovanetti @dineshneoito if you could also provide your tsconfig and TS versions, that would be great

**Comment by kabamrrichman** [comment]
Is it possible to roll back this change and re-do it as a major version increase for @types/validator? 
class-validator 0.14.0 has this dep: `"@types/validator": "^13.9.0"`

**Comment by benasher44** [comment]
I don't think so. Major bump would imply a new version of validator as well.

**Comment by benasher44** [comment]
For the most part, types packages track their backing packages and aren't versioned independently.

Generally speaking, @types packages can break without major version bumps. For example, next month this repo is scheduled to drop support for TS 4.7, which will not result in a major version bump of all @types packages. Going forward, people will be able to. People could start using TS features only in 4.7+ without a major version bump, which could in fact break fresh installs.

For this reason, it's best practice use lock files. npm overrides / yarn package resolutions are also good tools here.

**Comment by benasher44** [comment]
The PR was merged, and a release was tagged: https://github.com/typestack/class-validator/releases/tag/v0.14.1

I expect there will be an updated package available soon.

**Comment by benasher44** [comment]
0.14.1 is now available on npm. I believe this issue can now be closed
