### ISSUE TITLE
Angular-material confirmdialog

### ISSUE THREAD

**Issue by Kajvdh** [DefinitelyTyped/DefinitelyTyped#6817]
I'm using the angular-material type definitions, but when I try to create a confirm dialog, the compiler complains that the `supplied parameters do not match any signatures of call target`.
```typescript
showDialog(): void {
            var confirmDialog: ng.material.IConfirmDialog = this.$mdDialog.confirm({
                controller: "CreateUserGroupCtrl",
                controllerAs: "ctrl",
                templateUrl: "assets/partials/dialogs/userGroupDialog.html",
                parent: angular.element(document.body),
                clickOutsideToClose: true
            });
            this.$mdDialog.show(confirmDialog).then((userGroupToInsert: IUserGroup) => {
                userGroupToInsert.$save((userGroup: IUserGroup) => this.userGroups.push(userGroup));
            });
        }
```

**Comment by vvakame** [comment]
@mtraynham @robertbaker ?

**Comment by mtraynham** [comment]
`this.$mdDialog.confirm()`  takes no parameters and instread returns a $mdDialogPreset with chainable configuration methods.

What you want is:
```
var confirmDialog: ng.material.IConfirmDialog =  this.$mdDialog.confirm()
    .controller("CreateUserGroupCtrl")
    .controllerAs("ctrl"),
    .templateUrl("assets/partials/dialogs/userGroupDialog.html")
    .parent(angular.element(document.body))
    .clickOutsideToClose(true);
```

Documentation here:
https://material.angularjs.org/latest/api/service/$mdDialog

Preset dialog options are here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angular-material/angular-material.d.ts#L30

**Comment by robertbaker** [comment]
Agree with @mtraynham. @Kajvdh does that work if you set the type to `any` instead?

It may be supported but undocumented, but the chained methods would be the way to go.

**Comment by Kajvdh** [comment]
@mtraynham Thanks! But unfortunately it doesn't work for me.
The tsc does indeed not complain anymore and says it's valid. But angular itself throws this error:
```
this.$mdDialog.confirm(...).controller is not a function
```

The `ok`, `cancel`, `title`, `content` configurations do work, but my configurations don't.

**Comment by mtraynham** [comment]
Hmm... which version of angular material are you using?

**Comment by Kajvdh** [comment]
I'm using angular `1.4.7`

**Comment by mtraynham** [comment]
Yeah this is a bug.  We should remove some of these properties off the chainable config as I'm sure the preCanned configurations have their own Controller and probably template...

You'd be better off using:
```
            var confirmDialogOptions: ng.material.IDialogOptions = {
                controller: "CreateUserGroupCtrl",
                controllerAs: "ctrl",
                templateUrl: "assets/partials/dialogs/userGroupDialog.html",
                parent: angular.element(document.body),
                clickOutsideToClose: true
            };
            this.$mdDialog.show(confirmDialogOptions).then((userGroupToInsert: IUserGroup) => {
                userGroupToInsert.$save((userGroup: IUserGroup) => this.userGroups.push(userGroup));
            });
```

**Comment by Kajvdh** [comment]
Thanks, this works indeed + the typescript compiler does not complain! Thanks a lot
