### ISSUE TITLE
[@types/node] crypto: getting TS2502 error in @types/node@20.11.8

### ISSUE THREAD

**Issue by samzilverberg** [DefinitelyTyped/DefinitelyTyped#68357]
I started getting this err today after updating to latest @types/node@20.11.8

```
node_modules/@types/node/crypto.d.ts:4478:13 - error TS2502: 'crypto' is referenced directly or indirectly in its own type annotation.

4478         var crypto: typeof globalThis extends {
                 ~~~~~~


Found 1 error in node_modules/@types/node/crypto.d.ts:4478
```

this is what the code looks like on those lines:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8eef7f48da3124d97c81e44063de0b35729a9064/types/node/crypto.d.ts#L4477-L4481

on 20.11.7 there is no problem.

using typescript 5.3.3

let me know if you need any other info.

**Comment by lenovouser** [comment]
Discussion is ongoing in #68186

**Comment by martinshaw** [comment]
Can also report having this issue

**Comment by Anonymous4078** [comment]
Seems to be fixed in #68353

**Comment by samzilverberg** [comment]
can confirm `@types/node@20.11.9` doesn't have this problem anymore.

**Comment by hugops** [comment]
I have similiar problem on 20.11.10, but i'm using typescript 4.7.4
I have no problems with the version 20.11.7

`Error: node_modules/@types/node/ts4.8/crypto.d.ts:4477:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'crypto' must be of type 'Crypto', but here has type 'Crypto'.

4477         var crypto: webcrypto.Crypto;
                 ~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:18084:13
    18084 declare var crypto: Crypto;
                      ~~~~~~
    'crypto' was also declared here.`
