### ISSUE TITLE
Subsequent variables declarations must have the same type

### ISSUE THREAD

**Issue by juaal12** [DefinitelyTyped/DefinitelyTyped#68379]
Hi,

I am facing an issue when trying to build an angular package. It seems that "crypto" variable is declared several times with different "Crypto" types. I have been digging a bit and it seems crypto is declared globally at @types/node/ts4.8/crypto.d.ts:4477:13 and also at typescript/lib/lib.dom.d.ts:18084:13 dropping this an error when trying to build.

DevOps pipeline message:

![image](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/38920479/fdf13886-f326-44e1-bcff-99c96bee9950)

I am using Nuke build and my package is being generated from a TS client generated by NSwag.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f58f90046075bcc38a262e1462fb06b8a22ab886/types/node/ts4.8/crypto.d.ts#L4477

**Comment by kanadgodse-lh** [comment]
Having the same issue and the build is failing in GitLab CI/CD via Docker.
nodejs version: 14.21.1
Angular version: 14.3.0:

Here's a snippet of the build log

```
#4 0.437 > node pre-build-prod.js && ng build
#4 0.437 
#4 0.504 The environment.prod.ts file was saved!
#4 0.506 The environment.ts file was saved!
#4 0.506 The firebase-messaging-sw.js file was saved!
#4 0.507 The manifest.json file was saved!
#4 3.726 - Generating browser application bundles (phase: setup)...
#4 6.857 - @sentry/angular [es2015/esm2015] (git://github.com/getsentry/sentry-javascript.git)
#4 214.2 ✔ Browser application bundle generation complete.
#4 220.1 ✔ Browser application bundle generation complete.
#4 220.1 
#4 220.1 Warning: /app/node_modules/ngx-intl-tel-input/fesm2020/ngx-intl-tel-input.mjs depends on 'google-libphonenumber'. CommonJS or AMD dependencies can cause optimization bailouts.
#4 220.1 For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
#4 220.1 
#4 220.1 
#4 220.1 
#4 220.1 Error: node_modules/@types/node/ts4.8/crypto.d.ts:4477:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'crypto' must be of type 'Crypto', but here has type 'Crypto'.
#4 220.1 
#4 220.1 4477         var crypto: webcrypto.Crypto;
#4 220.1                  ~~~~~~
#4 220.1 
#4 220.1   node_modules/typescript/lib/lib.dom.d.ts:18084:13
#4 220.1     18084 declare var crypto: Crypto;
#4 220.1                       ~~~~~~
#4 220.1     'crypto' was also declared here.
#4 220.1 
#4 220.1 
#4 220.1 
#4 220.5 npm ERR! code ELIFECYCLE
#4 220.5 npm ERR! errno 1
#4 220.5 npm ERR! clickit@0.0.0 build-prod: `node pre-build-prod.js && ng build`
#4 220.5 npm ERR! Exit status 1
```

**Comment by juaal12** [comment]
The bug was introduced in this commit (file ts4.8/crypto.d.ts) https://github.com/DefinitelyTyped/DefinitelyTyped/commit/75fea781e8326f14ae0b7b4822d0fb4bc2293088 .

**Comment by girirajawari1** [comment]
same issue coming for me.. how to solve this?

**Comment by juaal12** [comment]
@girirajawari1 

In my case, since I am using Nuke build, I added a new step which after creating a new angular project using `ng new my-workspace --no-create-application` executes `npm package npm install --save-dev @types/node@20.11.5`. 
This is a workaround that works for me. Downgrading the package version from 20.11.10 to 20.11.5 worked for me but I do not know if it will work for you since I do not know your application/environment needs.

**Comment by codershiba** [comment]
Will be fixed in #68371

**Comment by ymombrun** [comment]
Temporary workaround for me, was to use resolutions on package.json to force downgrading to version 20.11.7 (the one that was resolved at last sucessful build for my app)

```
...
"resolutions": {
     "**/@types/node" : "20.11.7"
},
...
```

**Comment by sterichards** [comment]
> Temporary workaround for me, was to use resolutions on package.json to force downgrading to version 20.11.7 (the one that was resolved at last sucessful build for my app)
> 
> ```
> ...
> "resolutions": {
>      "**/@types/node" : "20.11.7"
> },
> ...
> ```

This worked for me

Thank you

**Comment by odedBartov** [comment]
> npm install --save-dev @types/node@20.11.5

can you please elaborate where and when exactly you inserted this code?
should i remove node_modules before i update package.json with this? 
thank you!

**Comment by RamMohanSonte** [comment]
Both the versions 20.11.7 and 20.11.6 versions did not work out for us

"resolutions": {
     "**/@types/node" : "20.11.7"
},

**Comment by WagaoFC** [comment]
@RamMohanSonte do this in your devDependencies:

"devDependencies": {
"@types/node" : "20.11.7"
}

**Comment by jakebailey** [comment]
I just merged a PR which should fix this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68371

In a half hour when the package is published, please test and let me know if it works.

**Comment by kanadgodse-lh** [comment]
I solved it by adding `"skipLibCheck": true` in tsconfig.json
