### ISSUE TITLE
 [@types/events] [@types/node/events] Can `EventEmitter` interface be generic to accept specific event names and arguments?

### ISSUE THREAD

**Issue by Neosoulink** [DefinitelyTyped/DefinitelyTyped#68420]
Hello everyone,

I realized working on a `typescript` project with `events` library is a bit frustrating to handle **events** names especially if working with `String` instead of `Symbols`, and when writing event names manually on different stages of the app.

This issue is not exactly an issue, but more like a feature request.
It will be interesting to make the  `EventEmitter` class generic to accept specific **event names and arguments**.

We may have something like:

```ts
export class EventEmitter<T extends string | number, U> {
    static listenerCount(emitter: EventEmitter, type: T): number;

    emit(type: T, ...args: U[]): boolean;
    on(type: T, listener: Listener): this;
    off(type: T, listener: Listener): this;
    removeAllListeners(type?: T): this;
    // Other methods ...
}
```

And  will use it as follows:
```ts
Class MyClass extends EventEmitter<'APP_START' | 'APP_END' | 0 | 1> { /* ... */ }
```

Same for the original `NodeJs events` definition (`@types/node/events.d.ts`)

```ts
// ...
 global {
        namespace NodeJS {
            interface EventEmitter<T extends string | symbol, U> {
                addListener(eventName: T, listener: (...args: U[]) => void): this;
                emit(type: T, ...args: U[]): boolean;
                on(type: T, listener: Listener): this;
                off(type: T, listener: Listener): this;
                removeAllListeners(type?: T): this;
                // Other methods ...
           }
        }
    }
 ```
 
 Of course, the final implementation will have more details and comments than that.
 
 If there's a duplication with this issue or anything else, I'll close this issue or update it. 
 I'll be glad to contribute to this one.

**Comment by jakebailey** [comment]
Are you looking for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68313?

(Do note that issues are not heavily monitored, unlike discussions)

**Comment by Neosoulink** [comment]
Hey @jakebailey,

Yes, Exactly!
Looks like it's a long thread and many other developers are asking for the same thing.

Thanks @jakebailey for the reply, I'm closing this issue, duplication of #25302 

Current PR: #68313
Related discussion: #55298
