### ISSUE TITLE
Update to pnpm results in new array type linter errors

### ISSUE THREAD

**Issue by alison-mk** [DefinitelyTyped/DefinitelyTyped#68436]
Updating to pnpm is resulting in unexpected linter errors for office-js and office-js-preview type definitions. These linter errors are unrelated to the lines that I updated in the type definitions before running pnpm test. Do you have recommendations for resolving these linter errors that doesn't require changing the lines with errors? 

**Command** 
pnpm test office-js

**Errors** 
  28589:25  error  Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead  @typescript-eslint/array-type
  34221:68  error  Array type using 'Array<any>' is forbidden for simple types. Use 'any[]' instead  @typescript-eslint/array-type

**System information** 
MacOS 13.6.4  
node 20.11.0
npm 10.2.4 
dtslint 0.2.6

**Comment by alison-mk** [comment]
@jakebailey This PR fails `pnpm test office-js` and `pnpm test office-js-preview`:  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68453 

My fork and local clone are up to date with master. Some of the code in our office-js and office-js-preview files is generated, but not all of the code is generated, should we still consider disabling the lint rule?

**Comment by jakebailey** [comment]
I would just disable the lint rule for both packages in `.eslintrc.json`. Your two packages are already exempted from `dprint` formatting, so this is okay. Likely this is the same situation as #68433; when we moved the rule from tslint to eslint, we autofixed all currently broken packages and must have missed a bunch of generated cases. @sandern

**Comment by alison-mk** [comment]
Thank you! I reported this internally so that the compiled code can be fixed. So that my team can keep using the linter, I'll revert the failing changes in the DefinitelyTyped packages and close this issue.
