### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by nojaf** [DefinitelyTyped/DefinitelyTyped#6844]
It would be nice to have intellisense in VS code for webpack.

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/webpack/webpack.d.ts ?

**Comment by nojaf** [comment]
Must have mist it because of the ```Sorry, we had to truncate this directory to 1,000 files. 369 entries were omitted from the list.```
Thanks
