### ISSUE TITLE
Module '"react-dom"' has no exported member 'useFormState'. [2305]

### ISSUE THREAD

**Issue by kalvinyuu** [DefinitelyTyped/DefinitelyTyped#68486]
import { useFormState } from "react-dom" 
causes the error 
Module '"react-dom"' has no exported member 'useFormState'. [2305]
however,
import { useFormState } from "react-server-dom-webpack/server.edge"
causes no type errors

**Comment by jakebailey** [comment]
You need to reference `react-dom/experimental`, as this is a canary feature. See:

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-dom/experimental.d.ts
- https://react.dev/reference/react-dom/hooks/useFormState

In the future, please use https://github.com/DefinitelyTyped/DefinitelyTyped/discussions to report issues and ask questions.
