### ISSUE TITLE
Leaflet L.Control is overloaded too much

### ISSUE THREAD

**Issue by panesofglass** [DefinitelyTyped/DefinitelyTyped#6851]
In TypeScript 1.6.2, I get compilation errors with the current version of `leaflet.d.ts`:

<img width="413" alt="screenshot-1" src="https://cloud.githubusercontent.com/assets/8803/11292797/8a0459f2-8f18-11e5-932a-3662cd158ed2.png">

If I remove the `export var Control`, I can build my project that references `leaflet.d.ts`, but the DefinitelyTyped build fails. Any ideas?

**Comment by vvakame** [comment]
I can't reproduction your issue...

```
$ tsc -v
message TS6029: Version 1.6.2
$ tsc --noImplicitAny leaflet/leaflet-tests.ts
$ echo $?
0
```

**Comment by rgripper** [comment]
@vvakame Can we get this issue closed? :)
