### ISSUE TITLE
Latest d3.d.ts no longer supports extent<T, U>(arr: T[], map: (val: T) => U): U[]

### ISSUE THREAD

**Issue by panesofglass** [DefinitelyTyped/DefinitelyTyped#6852]
My previous version of `d3.d.ts` worked with `extent<T, U>(arr: T[], map: (val: T) => U): U[]` but fails with the latest `export function extent<T, U extends Numeric>(array: U[], accessor: (datum: T, index: number) => U): [U | Primitive, U | Primitive];`.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by tomwanzek** [comment]
As part of some legacy D3v3 issue clean-up, can this issue be please closed?

D3v4 has been released and supported with actively maintained definitions for several months now, so it would be great to have only current issues open for clarity.

Thanks in advance!

cc @gustavderdrache @andy-ms
