### ISSUE TITLE
VCS Web UI: Outline (ToC) never shows by default

### ISSUE THREAD

**Issue by Chealer** [DefinitelyTyped/DefinitelyTyped#68610]
DefinitelyTyped's source code, which includes Markdown files such as [README.md](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md), is visible via a web browser thanks to a web repository viewer which renders Markdown. The viewer even renders tables of contents in a widget titled _Outline_. Unfortunately, that widget never shows by default, even if the README's contents have (semi-)fixed width and the viewport offers plenty of space to display the widget full-width, as can be seen in the following screenshot: 
![image](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/486141/ab600e54-b366-414f-9638-ccbaf3110ed9)

The widget can only be toggled manually, by using a button at the top right. Unfortunately, this is made worse by a very poor discoverability of that button. Indeed, the icon has no label, no unique color and has a shape which resembles a hamburger menu at a glance. There is no other element offering to toggle―either directly above the contents or directly to its side. In fact, there is no toggle in the whole _Preview_ area.

The ideal would be to show the outline by default, at least responsively, when doing so does not squeeze the contents at all. If it's hidden, then there should be a prominent toggle (at the very least an _Outline_ or _Table of contents_ label somewhere).

**Comment by jakebailey** [comment]
We don't have control over any of this; this UI is completely handled by GitHub and you'd need to make this suggestion to them.

**Comment by Chealer** [comment]
Can this ticket be reopened?

**Comment by RyanCavanaugh** [comment]
Unfortunately, it's not going to be possible to create a text rendering system that simultaneously satisfies all possible user requests.

You're certainly welcome to import this markdown file into a place that renders it in a way that suits your needs.
