### ISSUE TITLE
[@types/apple-mapkit-js] is missing some attributes

### ISSUE THREAD

**Issue by inorganik** [DefinitelyTyped/DefinitelyTyped#68650]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/67410

<div type='discussions-op-text'>

<sup>Originally posted by **inorganik** November 14, 2023</sup>
MapKitInitOptions is missing:
- [libraries](https://developer.apple.com/documentation/mapkitjs/mapkitinitoptions)

MapConstructorOptions is missing
- [loadPriority](https://developer.apple.com/documentation/mapkitjs/mapconstructoroptions/4096368-loadpriority)
</div>

These types have not been updated and owners haven't responded since I created the discussion above so creating this issue.

**Comment by hkbertoson** [comment]
I just opened #68666  for this.

**Comment by hkbertoson** [comment]
PR has been merged.

**Comment by inorganik** [comment]
Thank you!

**Comment by inorganik** [comment]
Appears these changes were published under a new package name, `@types/apple-mapkit-js-browser` whereas these types used to be published under `@types/apple-mapkit-js`. Any insight on that @hkbertoson ?

**Comment by hkbertoson** [comment]
Not sure on that. Interesting.
