### ISSUE TITLE
@types/svg-sprite miss type definition

### ISSUE THREAD

**Issue by Asdreu** [DefinitelyTyped/DefinitelyTyped#68736]
This package define interface Svg is blow.
```
interface Svg {
        xmlDeclaration?: boolean | string | undefined;
        doctypeDeclaration?: boolean | string | undefined;
        namespaceIDs?: boolean | undefined;
        namespaceClassnames?: boolean | undefined;
        dimensionAttributes?: boolean | undefined;
        rootAttributes?: any;
        precision?: number | undefined;
        transform?: SvgTransformer | SvgTransformer[] | undefined;
}
```
It miss one attribute definition is `namespaceIDPrefix`.
In https://github.com/svg-sprite/svg-sprite/blob/main/docs/configuration.md#sprite-svg-options, can see more.I hope can fix it.

**Comment by jakebailey** [comment]
The issue tracker is not the right place for this, as the issue menu and the issue template say. Please file a discussion, or send a PR with your proposed change.

**Comment by LightEievui** [comment]
This issue can be closed now, PR was merged
