### ISSUE TITLE
react -> react-native. Make `SyntheticEvent.nativeEvent` generic

### ISSUE THREAD

**Issue by bgrieder** [DefinitelyTyped/DefinitelyTyped#6883]
Hi,

I am working on the definitions for react-native: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/react-native

React-native is an extension of React and a few types are shared.
One of the problematic interface definition is `SyntheticEvent` where for react-native, the `nativeEvent` property does not point to a lib.d.ts `Event` but something specific to the underlying platform.

To be able to reuse the existing `React.SyntheticEvent`  and avoid defining an unnecessary `ReactNative.NativeSyntheticEvent`, I would need to have the type `SyntheticEvent` defined as

```
interface SyntheticEvent<T> {
    bubbles: boolean;
    cancelable: boolean;
    currentTarget: EventTarget;
    defaultPrevented: boolean;
    eventPhase: number;
    isTrusted: boolean;
    nativeEvent: T;
    preventDefault(): void;
    stopPropagation(): void;
    target: EventTarget;
    timeStamp: Date;
    type: string;
}
```

Within React, all interfaces extending `SyntheticEvent` would then extend `SyntheticEvent<Event>` whereas in React Native, they would extends`SyntheticEvent<NativeTouchEvent>`

Could that be done ?

**Comment by jbrantly** [comment]
Seems reasonable to me.

**Comment by bgrieder** [comment]
OK. Thanks let me now when that is in; I will create a pull request against react-native

**Comment by dbuarque** [comment]
+1

**Comment by iRoachie** [comment]
@alloy Can close

**Comment by iRoachie** [comment]
@alloy Can close
