### ISSUE TITLE
react -> react-native: re-export types for react

### ISSUE THREAD

**Issue by bgrieder** [DefinitelyTyped/DefinitelyTyped#6884]
Hi,

I am working on the definitions for react-native: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/react-nativehttps://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/react-native

React-native is an extension of React and I would like to be able to just say:

    `export * from React`

Unfortunately, this is not doable today and I have to resort to a "trick"  extending all React interfaces to re-export them.
This will lead to a maintenance nightmare where every modification to React will require a modification React Native definitions.
This has actually already happened and @jbrantly had to push a modification: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/99443d33d58a59a7aaa43758afd0fde92301c488

Could this be looked into ?

**Comment by jbrantly** [comment]
I'm wondering if you can't just re-use the `__React` namespace? For example, you can add ReactNative specific stuff to __React, and then just export __React (and for the global version, `import ReactNative = __React`)

**Comment by bgrieder** [comment]
Good idea. This is fair since I believe (I did not fully check that claim) that react-native is an "extension" of react rather than a library that re-exports part of react.
I made the change and it is part of this pull request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6882

**Comment by joewood** [comment]
I couldn't get the react-native.d.ts to work. Using ES6 as target and jsx as "react" the generated JS from the packager causes a runtime error on the device:
```
undefined is not an object (evaluating '_react_native_1$defau.AppRegistry')
```
I think this has something to do with ES6 style default exports. Does babel need configuring for the packager?
It works fine for my own ES5 based React-native definitions, but I would like to move over the DefTyped ones.

**Comment by bgrieder** [comment]
@joewood Can you spot any difference between your code and  what is done [in this project](https://github.com/bgrieder/RNTSExplorer/) ?

The `AppRegistry` is imported (in a JS file) [there](https://github.com/bgrieder/RNTSExplorer/blob/master/index.ios.js)

It could be something is wrong with the definition of AppRegistry if you import it from ts.

The [tsconfig](https://github.com/bgrieder/RNTSExplorer/blob/master/tsconfig.json) uses es6 and jsx/react

**Comment by joewood** [comment]
It looks fairly similar. I just created an empty **react-native init** project and added typescript. The only real difference I see is that I'm using RN 0.16 - not sure if there's been an ES6 module migration between 0.14 and 0.16.

**Comment by bgrieder** [comment]
@joewood I just upgraded RNTSExplorer to react-native 0.16 and it is basically working but for a few warnings on prop types as far as I can tell

**Comment by joewood** [comment]
OK, that's one thing eliminated :-)
I'll clone the repo and eliminate the other differences. Thanks for your help - I'll post here when I spot it.
