### ISSUE TITLE
Is it possible to support @types in snappyjs library?

### ISSUE THREAD

**Issue by LIUHAIK** [DefinitelyTyped/DefinitelyTyped#68878]
Is it possible to support @types in snappyjs library?
snappyjs：https://github.com/zhipeng-jia/snappyjs

**Comment by hkbertoson** [comment]
Im sure it is. Are you sure this repo is still active?

**Comment by MysteryBlokHed** [comment]
Resolved in #68995. In the future, please use [discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions) to submit requests like this

**Comment by Longqin88888** [comment]
I found a problem with @types/snappyjs, the decompression interface is decompress, but in snappyjs the decompression interface is uncompress
