### ISSUE TITLE
[infra] CI "Format And Commit" job failing

### ISSUE THREAD

**Issue by MysteryBlokHed** [DefinitelyTyped/DefinitelyTyped#69041]
[This job](https://github.com/DefinitelyTyped/DefinitelyTyped/actions/workflows/format-and-commit.yml) has been failing on all recent commits:

<details>
<summary>Screenshots</summary>

![A screenshot of recent commits, showing the "x" indicating a CI failure.](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/13910387/8559649f-ef11-4d61-84af-f997c4ca9285)

![A screenshot of the dialog upon clicking on the latest of these commits, showing the specific job that is failing.](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/13910387/a92be0d6-e408-4377-9aa9-fba85a6ef4a8)
</details>

The error seems to be related to authentication required to push formatting changes. The job actually fails during the checkout step:

![A screenshot of a CI run, showing that the checkout step failed and that subsequent ones were skipped.](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/13910387/98becb68-fabe-4386-9c6f-d5bb0762ddcf)

```text
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +30b899f9eb095afb46792f7c9bd6c1c73895ef3f:refs/remotes/origin/master
  Error: fatal: could not read Username for 'https://github.com/': terminal prompts disabled
  The process '/usr/bin/git' failed with exit code 128
  Waiting 15 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +30b899f9eb095afb46792f7c9bd6c1c73895ef3f:refs/remotes/origin/master
  Error: fatal: could not read Username for 'https://github.com/': terminal prompts disabled
  The process '/usr/bin/git' failed with exit code 128
  Waiting 11 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +30b899f9eb095afb46792f7c9bd6c1c73895ef3f:refs/remotes/origin/master
  Error: fatal: could not read Username for 'https://github.com/': terminal prompts disabled
  Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by jakebailey** [comment]
Thanks for noticing; will look into this.

**Comment by jakebailey** [comment]
Fixed now.
