### ISSUE TITLE
ng-file-upload

### ISSUE THREAD

**Issue by charlierudolph** [DefinitelyTyped/DefinitelyTyped#6915]
[ng-file-upload.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a247bd7d5832c490f1a17fa839227cc6ceae1fec/ng-file-upload/ng-file-upload.d.ts) IFileUploadConfigFile(s) should have "fields" and shouldn't require a "method".

Based on searching through the source [here](https://github.com/danialfarid/ng-file-upload/blob/master/src/upload.js#L195).

Tagging the author @johnnyreilly

**Comment by johnnyreilly** [comment]
Feel free to submit a PR

**Comment by nkovacic** [comment]
Done https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7640
