### ISSUE TITLE
Backbone typescript definitions contradict backbone's own documentation

### ISSUE THREAD

**Issue by shumphrey** [DefinitelyTyped/DefinitelyTyped#6922]
Typescript is supposed to be a superset of javascript.
Backbone's documentation says you define your class by doing:

```
var MyModel = Backbone.Model.extend({});
```

Although this isn't the typescript way, I definitely think it should work, but with the current definition, it does not.

The changes introduced by #2077 break this.
Converting an existing backbone project to typescript is made quite awkward because of this.

I note #2517 tried to revert these changes previously.
I'd argue enforcing standards on library usage shouldn't be done in the definition for that library.

**Comment by sl1331** [comment]
In agreement. the "extend" method is also a public method (private in the typescript definition).

**Comment by mhegazy** [comment]
Feel free to send a PR and will merge it.

**Comment by trusktr** [comment]
I agree that this is bad.

**Comment by trusktr** [comment]
Is there a way to make type parameters for `.extend` so typescript knows what class is returned, rather than just `any`?

**Comment by ashwinr** [comment]
I have a straightforward fix to open up `.extend`. If that looks okay, can we please merge it?
