### ISSUE TITLE
 @types/node/stream.d.ts pipeline signature missing mandatory flag for callback

### ISSUE THREAD

**Issue by john30** [DefinitelyTyped/DefinitelyTyped#69432]
according to the implementation in
https://github.com/nodejs/node/blob/91dc8c93a3d6ffa9de3bb7b7507e52df4a4aad90/lib/internal/streams/pipeline.js#L185
the signature has changed with commit https://github.com/nodejs/node/commit/b920a10162398a9f72c1c15d0b15ddac08d3d4d8 to require the callback.
this should also be revealed here
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b8d1466d9111780dca384f9d79ac7f8c696efc01/types/node/stream.d.ts#L1542
and in the lines below

**Comment by codershiba** [comment]
Created #69498 to fix this.
