### ISSUE TITLE
@types/underscore does not provide type definitions for the isMap, isWeakMap,isSet,isWeakSet,toPath and restArguments interfaces.

### ISSUE THREAD

**Issue by xiaoxizi2303** [DefinitelyTyped/DefinitelyTyped#69527]
@types/underscore does not provide type definitions for the isMap, isWeakMap,isSet,isWeakSet,toPath and restArguments interfaces.

**Comment by neerajkumar161** [comment]
Hey. Can I try to work on this? I'm interested in types, maybe I can help
