### ISSUE TITLE
Cannot use namespace as type

### ISSUE THREAD

**Issue by bonitao** [DefinitelyTyped/DefinitelyTyped#69526]
See https://stackoverflow.com/questions/53853815/how-to-fix-cannot-use-namespace-as-a-type-ts2709-in-typescript.

The error seems to be here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2cb66849024b2e84a7bd4e3649b4e53b8df3e714/types/markdown-it/lib/index.d.mts#L149

And here is my client side patch:

```
diff --git a/dist/index.cjs.d.ts b/dist/index.cjs.d.ts
index 3937a618c13b3bfb017ab163cb613020bf670d40..a149fa7f935837a3ca6c3fd758b6e1281ba44bff 100644
--- a/dist/index.cjs.d.ts
+++ b/dist/index.cjs.d.ts
@@ -979,7 +979,7 @@ interface MarkdownIt {
      * Used by [linkify](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/linkify.js)
      * rule.
      */
-    readonly linkify: LinkifyIt;
+    readonly linkify: typeof LinkifyIt;

     /**
      * Link validation function. CommonMark allows too much in links. By default
 ```

**Comment by viceice** [comment]
this is fixed since [`@types/markdown-it@14.1.1`](https://unpkg.com/browse/@types/markdown-it@14.1.1/package.json), so this issue can be cosed

fixed by:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69492
