### ISSUE TITLE
mongoose Document should be a class not an interface

### ISSUE THREAD

**Issue by sebastianwahn** [DefinitelyTyped/DefinitelyTyped#6957]
# Recommendation

The mongoose.d.ts Document should be a class and not an interface, since mongoose has an implementation for Document (lib/document.js). 

`export interface Document { ... }` 

should be 
`export class Document { ... }`

# Use Case:

I try to implement a generic `Repository<T extends Document>`
Then i create a class `Model extends Document { ... }`

Now according (with `export interface Document { ... }`) i have to implement all functions which are already provided by mongoose.
With `export class Document { ... }` they are already provided by mongoose like it is the case

**Comment by vvakame** [comment]
please send a pull request with document url.
