### ISSUE TITLE
Definition Request: agenda

### ISSUE THREAD

**Issue by haimich** [DefinitelyTyped/DefinitelyTyped#6959]
I'd like to see the task scheduler **agenda** on DefinitelyTyped: https://github.com/rschmukler/agenda

Thanks!

**Comment by FedeBev** [comment]
Maybe this should be closed.

Agenda repository has been moved to https://github.com/agenda/agenda and [types definition exists](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/agenda)

@vvakame
