### ISSUE TITLE
this is unbelievable

### ISSUE THREAD

**Issue by dev-dantealighieri** [DefinitelyTyped/DefinitelyTyped#69614]
.

**Comment by JWJ212** [comment]
good issue :+1:

**Comment by Anonymous4078** [comment]
What is unbelievable?

**Comment by Saturate** [comment]
unbelievable bad issue

**Comment by dev-dantealighieri** [comment]
I was saying this is the worst library I've ever seen, I can write better code than this while I sleep, then I decided to delete my comment because it was harsh 🤣

**Comment by dev-dantealighieri** [comment]
🚀
