### ISSUE TITLE
Is `/types/node` maintained manually? Or auto generated?

### ISSUE THREAD

**Issue by kkocdko** [DefinitelyTyped/DefinitelyTyped#69689]
I have a type [`dirent.parentPath`](https://nodejs.org/api/fs.html#direntparentpath) missing in `node`'s type define. My question is, Is `/types/node` maintained manually? Or auto generated? Can I manually make a PR to fix it?

**Comment by AlttiRi** [comment]
Just update deps.

`"@types/node": "20.12.11"`

![Screenshot](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/16310547/5899932e-21ea-421b-b3c2-b438e0bfdf69)

https://www.npmjs.com/package/@types/node?activeTab=versions
![image](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/16310547/a79b31b8-1454-418e-ac23-84de7328fb71)
