### ISSUE TITLE
code works locally but as i uploade aws ubuntu getting this error 

### ISSUE THREAD

**Issue by incchi** [DefinitelyTyped/DefinitelyTyped#69809]
i even installed pkg as root and globally manually still unable to resolve the error

| [0] Caught an error: Error: html-pdf: Unknown Error
0|unite_for_freedom_api_3000 | [0] Auto configuration failed
0|unite_for_freedom_api_3000 | [0] 136600028223296:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libproviders.so): libproviders.so: cannot open shared object file: No such file or directory
0|unite_for_freedom_api_3000 | [0] 136600028223296:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
0|unite_for_freedom_api_3000 | [0] 136600028223296:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=providers, path=providers
0|unite_for_freedom_api_3000 | [0] 136600028223296:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=providers
0|unite_for_freedom_api_3000 | [0]
0|unite_for_freedom_api_3000 | [0] at ChildProcess.respond (/var/lib/jenkins/workspace/unite_for_freedom_backend/node_modules/html-pdf/lib/pdf.js:134:17)
0|unite_for_freedom_api_3000 | [0] at ChildProcess.emit (node:events:517:28)
0|unite_for_freedom_api_3000 | [0] at ChildProcess.emit (node:domain:489:12)
0|unite_for_freedom_api_3000 | [0] at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
0|unite_for_freedom_api_3000 | [0] POST /api/v1/user/coupon/book/buy 500 668 - 42.450 ms

**Comment by jakebailey** [comment]
This doesn't have anything to do with DefinitelyTyped; I would ask this on StackOverflow or something.
