### ISSUE TITLE
Electron Definitions are outdated

### ISSUE THREAD

**Issue by hinamiyagk** [DefinitelyTyped/DefinitelyTyped#6984]
In latest version of Electron(v0.35.x), Type Definitions are outdated because of some API changes.
For example,
* Add electron module which includes all public APIs(v0.35.0)
* Add ipcRenderer and ipcMain modules instead of ipc module(v0.35.0)

Also many APIs are added and missing from this repository.

**Comment by vvakame** [comment]
patches welcome!

**Comment by elisee** [comment]
This can be closed, the definition file has been updated!
