### ISSUE TITLE
Tests for false positives

### ISSUE THREAD

**Issue by denis-sokolov** [DefinitelyTyped/DefinitelyTyped#6987]
The current test system only checks for false negatives. That is, our tests catch a scenario, where a type definition is violated. But what about testing whether the type definition is not narrow enough?

In other words, `x: any => any` will pass any tests we ever have for a `sum` function. But we’d like to have the definition ensure `sum('foo')` is incorrect.

Is there any such capability in the test system or is any such capability planned?

**Comment by vvakame** [comment]
I think it is confirmation of compatibility.
It protect from invalid definitions.
It can detect breaking change of tsc.

@basarat ?

**Comment by basarat** [comment]
Something like fourslash would allow us to add such assertions. Feels like *a lot of work*. I created an issue regarding this a while back : https://github.com/DefinitelyTyped/DefinitelyTyped/issues/2472

**Comment by seansfkelley** [comment]
I'm starting to see this as a problem as well; for instance, in #8795 I'm trying to fix an issue where typings are too lenient, and as part of that I want to add a negative test, but the best I can do is [write the test then comment it out and hope that people read it](https://github.com/seansfkelley/DefinitelyTyped/blob/8a7d208e0dcb37d4f62588eeef2cd71b5b8bff98/react-redux/react-redux-tests.tsx#L323).

**Comment by andy-ms** [comment]
This should be possible with `$ExpectError` in [dtslint](https://github.com/Microsoft/dtslint).
