### ISSUE TITLE
[@types/node] Wrong return type for process.report.getReport()`

### ISSUE THREAD

**Issue by vHeemstra** [DefinitelyTyped/DefinitelyTyped#69958]
Wrong return type for Node's `process.report.getReport()` at:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/process.d.ts#L229

Defined as string, but should be a (JSON) object according to [their documentation](https://nodejs.org/api/process.html#processreportgetreporterr).

**Comment by Renegade334** [comment]
This method originally returned the JSON string output from the underlying API, but was changed to return the parsed JSON object in v13.0, and looks like this got missed.
