### ISSUE TITLE
d3.select('something').node() should return of type Node

### ISSUE THREAD

**Issue by pragyandas** [DefinitelyTyped/DefinitelyTyped#7014]
![d3 d ts](https://cloud.githubusercontent.com/assets/6696740/11510998/8508ad9a-988c-11e5-9860-1d2f8a34fca5.png)

While doing d3.select('svg').node() should return type 'Node' but rather returns 'EventTarget' on which things like 'appendChild' appears to create a compilation error.

Please find attached code snapshot for reference.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by samouss** [comment]
Hello, I check your pull request #7101 and I don't think that the correct type is `Node`.

The method `node()` should return the first non `null` value of the selection ([docs](https://github.com/mbostock/d3/wiki/Selections#node)).

The `d3.select` return a type of `Selection<any>` and then the signature of selection is `Selection<Datum>`, thus the type of `node()` should be `Datum` according to the documentation.

What do you think about that ?

**Comment by pragyandas** [comment]
@samouss Thanks for the suggestion but `Datum` is not equivalent to a DOM node and `node()` is supposed to return something on which we can perform operations like `childNodes, firstChild, lastChild, parentNode, etc...`. The most popular use of `node()` is to create a node on which we perform `appendChild` and all these methods are defined on the interface `Node`.

**Comment by blemoine** [comment]
@pragyandas : I think @samouss is right ; the ```node()``` method returns the first element of a ```Selection<Datum>```, so it's return type is ```Datum```. 

e.g. if `node()` return Datum, you could do :
```
const mySelection:Selection<Node> = d3.select(nodes);
const myNode:Node = d3.node();
```
but for the users would want to use a more precise type, the could also use node() without down casting (down casting is *bad*) :
```
const mySelection:Selection<HtmlFormElement> = d3.select("input")
const myFirstEventTarget:HtmlFormElement = d3.node();
```

**Comment by zbjornson** [comment]
@pragyandas I agree with @samouss and @blemoine, I think it makes more sense as Datum. Setting it directly to `Node` seems to be like manually narrowing the type, whereas this generic lets us know the actual type.
