### ISSUE TITLE
@types/eslint has an issue with the ESLint constructor, it also takes ESLint.LegacyOptions

### ISSUE THREAD

**Issue by heath-freenome** [DefinitelyTyped/DefinitelyTyped#70192]
I am converting a set of JS tests to Typescript and am having to cast `ESLint.LegacyOptions` to `ESLintOptions` because the [constructor()](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/77922c35d69509319534a514aca8275cf0eff0f5/types/eslint/index.d.ts#L1370) type is defined as follows:

```
constructor(options?: ESLint.Options);
```

and it really should be:

```
constructor(options?: ESLint.Options | ESLint.LegacyOptions);
```
Because that is the type that my static object needed to be converted to work with the `ESLint.ConfigData`. The `ESLint.Options` type expects the `plugins` type to be an array of `ESLint.Plugin` object rather than `string[]` which is accepted by `LegacyOptions`

Running the existing code works just fine with the `LegacyOptions` so I'm pretty sure the type is wrong.

**Comment by jakebailey** [comment]
Please use https://github.com/DefinitelyTyped/DefinitelyTyped/discussions, package owners are not pinged on issues

**Comment by heath-freenome** [comment]
@jakebailey Thanks, started a discussion
