### ISSUE TITLE
Upcoming changes within Node.js API docs JSON format

### ISSUE THREAD

**Issue by ovflowd** [DefinitelyTyped/DefinitelyTyped#70216]
Hi, y'all 👋 (Node.js project here). We are rewriting our API docs infrastructure and tooling, which will allow us to change the format of the `.json` files we generate within our API docs tooling.

The new project being crafted is https://github.com/nodejs/api-docs-tooling. It will contain numerous QoL updates and changes to how things are generated.

This includes our JSON-generated API docs, which are used here https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node/scripts/generate-docs to generate the TypeScript types within this repository (and which is used for `@types/node`)

We will make a few changes to the current format, as this opens the possibility of improving the structure of said types. We want to collaborate with the maintainers of `@types/node` to understand better current pain points and what we can improve on the JSON format.

This is the issue on our side to track the JSON generation: https://github.com/nodejs/api-docs-tooling/issues/57

**Comment by jakebailey** [comment]
You probably want to make a discussion, which the bot automates and pings maintainers in. Issues are untracked (except when someone like me opens it for some reason)

**Comment by flakey5** [comment]
Made a discussion for it here: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/70298 , I don't think the bot has pinged the maintainers though?

**Comment by jakebailey** [comment]
I have no idea why the bot isn't handling that :(
