### ISSUE TITLE
why interface FunctionComponent has different define between @types/react/index.d.ts and @types/react/ts5.0/index.d.ts

### ISSUE THREAD

**Issue by whyer11** [DefinitelyTyped/DefinitelyTyped#70458]
ts5.0 dir:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a75e4cafc6bf2be79d484abc66a7168f699805ed/types/react/ts5.0/index.d.ts#L1114

root dir:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a75e4cafc6bf2be79d484abc66a7168f699805ed/types/react/index.d.ts#L1113

the return type : ReactElement<any, any> | null   is very different from ReactNode

**Comment by jakebailey** [comment]
https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#decoupled-type-checking-between-jsx-elements-and-jsx-tag-types
