### ISSUE TITLE
[@types/node-zendesk] The node-zendesk types are broken in v5.0.13, even the examples don't compile.

### ISSUE THREAD

**Issue by ipeychev** [DefinitelyTyped/DefinitelyTyped#70549]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/70547

<div type='discussions-op-text'>

<sup>Originally posted by **ipeychev** September 13, 2024</sup>
**Describe the Bug**

The types are broken, the TypeScript code doesn't compile. I took an example from `node_modules/node-zendesk/dist/types/clients/core/tickets.d.ts`. Note the example:

```
* Create a new ticket.
* @example
     * const newTicket = await client.tickets.create({ subject: 'New ticket', description: 'Ticket description' });
     */
    create(ticket: CreateOrUpdateTicket): Promise<{
        result: Ticket;
    }>;
```

I took this code and created an app:

**Example Code**

```
import { createClient } from "node-zendesk";

async function test123() {
  const client = createClient({});
  const newTicket = await client.tickets.create({ subject: 'New ticket', description: 'Ticket description' });
}
```

**Expected Behavior**
The code to compile successfully.

**Actual Behavior**
There is a compilation error:

```
Object literal may only specify known properties, and 'subject' does not exist in type 'CreateOrUpdateTicket'.ts(2353)
(property) subject: string
```

![image](https://github.com/user-attachments/assets/ed68047f-b63a-479c-9422-02a080122238)

Environment Information

- 
- node-zendesk version: 5.0.13
- Node.js version: v20.9.0
- Operating System: MacOS
- Any other relevant software versions?

**Additional Context**

```
"dependencies": {
    "node-zendesk": "^5.0.13",
    "typescript": "^5.6.2"
  }
```

</div>

**Comment by stasinua** [comment]
@ipeychev Got your issue there. Thank you.
