### ISSUE TITLE
md5 typing on tsd conflicts with the npm module of the same name, it should be renamed

### ISSUE THREAD

**Issue by t27** [DefinitelyTyped/DefinitelyTyped#7057]
The current typing named `md5` [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/md5/md5.d.ts) doesn't match the binding of the *npm* module `md5`
To add the typing for the actual npm module called `md5` , we need to rename the current `md5` typing. The current `md5` typing is the typing for a project called `md5js`, 
also if renaming the existing typing is not possible, we can probably name it something like node-md5 or something similar.
I can submit a PR, what would be the best way to go about it? rename the existing typing or to publish a typing for an npm module with a different name than the npm module?

**Comment by vvakame** [comment]
@pine613 ?

**Comment by arcdev1** [comment]
+1

I have a typing ready to go for the npm module `md5` that I would like to submit, but not sure how to do so, because of this naming conflict.

**Comment by arcdev1** [comment]
Commit #9347 means that md5 now points to the [correct npm library](https://www.npmjs.com/browse/keyword/md5).
