### ISSUE TITLE
error TS2305: Module '"entities/lib/decode.js"' has no exported member 'EntityDecoder'.

### ISSUE THREAD

**Issue by shashi-chemist2u** [DefinitelyTyped/DefinitelyTyped#70886]
<!--
DO NOT use this template to report problems with a specific package.
Please use https://github.com/DefinitelyTyped/DefinitelyTyped/discussions instead.

Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped channel in the TypeScript Community Discord](https://discord.gg/typescript).
node_modules/parse5/dist/tokenizer/index.d.ts:3:10 - error TS2305: Module '"entities/lib/decode.js"' has no exported member 'EntityDecoder'.

3 import { EntityDecoder } from 'entities/lib/decode.js';
           ~~~~~~~~~~~~~


Found 1 error in node_modules/parse5/dist/tokenizer/index.d.ts:3
-->

node_modules/parse5/dist/tokenizer/index.d.ts:3:10 - error TS2305: Module '"entities/lib/decode.js"' has no exported member 'EntityDecoder'.

3 import { EntityDecoder } from 'entities/lib/decode.js';
           ~~~~~~~~~~~~~

Found 1 error in node_modules/parse5/dist/tokenizer/index.d.ts:3

parse5@7.2.0 version has breaking change; please use parse5@7.1.2 version

**Comment by jakebailey** [comment]
This has nothing to do with DefnitelyTyped; both `parse5` and `entities` ship their own types, so you should report a bug on the `parse5` repo if you have a problem with it.
