### ISSUE TITLE
`@types/react` version `18.3.9999` does not exist and fails package install

### ISSUE THREAD

**Issue by amandeep3-it** [DefinitelyTyped/DefinitelyTyped#70915]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/58aabc0cfd2baf08f5f71a2712ae7baa6cb2a3ce/types/react-smartbanner/package.json#L9

Why is the `@types/react` package set to version `18.3.9999`? It does not exist and causes the following error when installing dependencies:

```
npm error code ETARGET
npm error notarget No matching version found for @types/react@^18.3.9999.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
```

Please change the version to `^18.3.11` or something more suitable.

Tagging original Author:  @PCOffline

**Comment by PCOffline** [comment]
Hey, thanks for the feedback! Will fix
