### ISSUE TITLE
[@types/better-sqlite3] Class properties of `SqliteError` are inaccessible.

### ISSUE THREAD

**Issue by atifcppprogrammer** [DefinitelyTyped/DefinitelyTyped#71132]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/71131

<div type='discussions-op-text'>

<sup>Originally posted by **atifcppprogrammer** November  9, 2024</sup>
Hi there ! it seems that the `SqliteError` class has been typed incorrectly since the use of `type SqliteError = typeof SqliteError` line at the following two instances

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/better-sqlite3/index.d.ts#L91
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/better-sqlite3/index.d.ts#L141 

prevents access to the class's member properties i.e. `name`, `message` and `code`. The `code` property is particularly important since it corresponds to SQLite3 error codes as per the package documentation [here](https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#class-sqliteerror), having this information is crucial for my use case. 

</div>

**Comment by edlerd** [comment]
I am looking into this one.

**Comment by jakebailey** [comment]
I think this was done in #71144
