### ISSUE TITLE
Allow lodash.d.ts to accept Typescript arrays to _.some()

### ISSUE THREAD

**Issue by RichardJECooke** [DefinitelyTyped/DefinitelyTyped#7122]
Passing a normal array to _.some() works fine, but passing an array created using Typescript's interface syntax fails with the error: 
*error TS2345: Argument of type 'BooksArray' is not assignable to parameter of type 'List<Book> | Dictionary<Book>'.*

Compile the code sample below to get the compilation error on the last line:

```
import _ = require('lodash');

interface Book
{
	name: string;
}

interface BooksArray  //http://www.typescriptlang.org/Handbook#interfaces-array-types
{
	[index: number]: Book;
}

let works  : Array<Book> = [{name: '1'}];
let breaks : BooksArray  = [{name: '1'}];

_.some(works, {'name' : 'whatevs' });
_.some(breaks, {'name' : 'whatevs' });
```

**Comment by vvakame** [comment]
@chrootsu ?

**Comment by chrootsu** [comment]
@RichardJECooke Thank you for the bug report!
@vvakame Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7215
