### ISSUE TITLE
lodash: missed Cancellable from function, returned by _.debounce

### ISSUE THREAD

**Issue by Strate** [DefinitelyTyped/DefinitelyTyped#7135]
Subj. There should be a `cancel()` method for function, returned by `_.debounce`, as for function, returned by `_.throttle`

**Comment by vvakame** [comment]
@chrootsu ?

**Comment by chrootsu** [comment]
@Strate Thank you for the bug report!
@vvakame Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7148
