### ISSUE TITLE
Latest @types/react breaks async React components in NextJS

### ISSUE THREAD

**Issue by LZL0** [DefinitelyTyped/DefinitelyTyped#71363]
@types/react 18.3.14 introduces a new issue not present in 18.3.13 where the following type error is thrown when using async components inside the NextJS app directory:
```
Type error: 'Navigation' cannot be used as a JSX component.
  Its type '({}: {}) => Promise<Element>' is not a valid JSX element type.
    Type '({}: {}) => Promise<Element>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
      Type 'Promise<Element>' is not assignable to type 'ReactNode'.

  40 |   return (
  41 |     <>
> 42 |       <Navigation />
```

The component:
```
export default async function Navigation(): Promise<JSX.Element> {
  const { items: posts } = await api.posts.pagedPosts({ limit: 10 });
  const { items: tradeIdeas } = await api.tradeIdeas.pagedTradeIdeas({
    limit: 10,
  });
```

**Comment by thisislvca** [comment]
It also breaks when using the cache function imported from react

<img width="628" alt="image" src="https://github.com/user-attachments/assets/f69319fb-06a2-460a-a934-95d5b426a91c">

**Comment by paulocf92** [comment]
Same thing happening here, v18.3.14 breaks NextJS v14 projects.

**Comment by DarioLopes** [comment]
Same here, definitely interested to get a solution

**Comment by YusukeOkamoto** [comment]
In @types/react version 19.x and later, Promise<AwaitedReactNode> is included in ReactNode as shown here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L439


However, this is not included in version 18.x:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6eb6c4d8d70caf9f0558df11c36b51097879f0f9/types/react/v18/index.d.ts#L478-L489

**Comment by edx-jagadeesh-kumar** [comment]
One of my project had this issue , I pinned the `@types/react` to `18.3.12` and added a `resolution` for it in the `package.json` file.
```
"resolutions": {
    "@types/react": "18.3.12"
  },
```

**Comment by ElectricCodeGuy** [comment]
import { useFormStatus } from 'react-dom';  or import { useFormState } from 'react-dom'; does still give you a type error after the patch.

**Comment by tomatofishfan** [comment]
> One of my project had this issue , I pinned the `@types/react` to `18.3.12` and added a `resolution` for it in the `package.json` file.
> 
> ```
> "resolutions": {
>     "@types/react": "18.3.12"
>   },
> ```

This method works for me. Thank you so much!

**Comment by eps1lon** [comment]
Should be fixed with latest `@types/*` i.e. `@types/react@18.3.15` and `@types/react-dom@18.3.5`

**Comment by paulocf92** [comment]
> Should be fixed with latest `@types/*` i.e. `@types/react@18.3.15` and `@types/react-dom@18.3.5`

Worked like a charm, thank you!
