### ISSUE TITLE
[node] parameter type of "signal" in process.kill    

### ISSUE THREAD

**Issue by f111fei** [DefinitelyTyped/DefinitelyTyped#7152]
process.kill(pid:number, signal?:string): void;
shouldbe
process.kill(pid:number, signal?: string|number): void;

signal 0 can be used to test for the existence of a process.

see
https://nodejs.org/dist/latest-v5.x/docs/api/process.html#process_signal_events

Note that Windows does not support sending Signals, but Node.js offers some emulation with process.kill(), and child_process.kill(). Sending signal 0 can be used to test for the existence of a process. Sending SIGINT, SIGTERM, and SIGKILL cause the unconditional termination of the target process.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by f111fei** [comment]
@vvakame  #7223 
It's here

**Comment by vvakame** [comment]
:+1:
