### ISSUE TITLE
Add definitions for Plotly

### ISSUE THREAD

**Issue by stefan505** [DefinitelyTyped/DefinitelyTyped#7202]
Please add definitions for Plotly: https://github.com/plotly/plotly.js/issues/28

**Comment by boltzj** [comment]
It looks like it had been added : [plotly.js/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/plotly.js/index.d.ts)

**Comment by chrisgervang** [comment]
@boltzj this definition is about 1% of the plotly api. @stefan505 I've recently finished a more complete definition that includes components like rangeslider and rangeselector, and the scatter plot. I'm adding to it as I use more and more of plotly.

Can either of you help me understand how @types/plotly on npm can be changed to my more complete file? I can submit a PR to definitilytyped, but I want to ensure the @types bot links. The docs confuse me.

**Comment by stefan505** [comment]
@chrisgervang I am not entirely sure how @types works. Have you been able to make any progress on this?

**Comment by stefan505** [comment]
@chrisgervang , I just realized that http://microsoft.github.io/TypeSearch/ is already picking up plotly.js from DefinatelyTyped, it probably just requires an update. Perhaps you can liaise with another definition author: https://github.com/plotly/plotly.js/issues/28

cc: @stemcstudio

**Comment by chrisgervang** [comment]
Fixed in #15379

**Comment by Phoenix1747** [comment]
Is anyone currently maintaining the Plotly defs? Looks to me like they didn't get any updates since 2.12.
