### ISSUE TITLE
Property "ensure" does not exist on type "Require"

### ISSUE THREAD

**Issue by hitmands** [DefinitelyTyped/DefinitelyTyped#7212]
Hi, 
I'm using tsd for requirejs definitions (on a webpack+typescript+react project) and i'm getting this error:
`error TS2339: Property 'ensure' does not exist on type 'Require'.`

Is it a missed declaration?
Thanks in advance

**Comment by tkqubo** [comment]
Sorry for the late reply.  I don't know much about require.js, but I think you need to install `webpack-env` additionally.  As you can see in the comment here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6243#commitcomment-13792564 ,  webpack's definition and module extension is different.  @hitmands 

If you still can't resolve the issue, please reply to this message.  Thank you.
