### ISSUE TITLE
request: kendo ui web

### ISSUE THREAD

**Issue by dsoltesz** [DefinitelyTyped/DefinitelyTyped#722]

**Comment by tsvetomir** [comment]
Definitions are available for all Kendo UI widgets for a while now. I suggest we close this.

**Comment by tsvetomir** [comment]
@ciel - should be fixed, [PR pending](https://github.com/borisyankov/DefinitelyTyped/pull/4607)

**Comment by slawiko** [comment]
@dsoltesz it's done, please close this issue.
