### ISSUE TITLE
Definition Request: T3

### ISSUE THREAD

**Issue by jhawkins** [DefinitelyTyped/DefinitelyTyped#7248]
Please consider adding definitions for T3. http://t3js.org/

Thanks!

**Comment by webbiesdk** [comment]
I made a thing: https://gist.github.com/webbiesdk/fa0a5ce63b10bd01f9f9

It can properly be used as a starting point.

**Comment by jakebailey** [comment]
Link is dead, and this repo is no longer maintained.
