### ISSUE TITLE
Sinon: missing Document and Event types

### ISSUE THREAD

**Issue by akamud** [DefinitelyTyped/DefinitelyTyped#7269]
sinon.d.ts for version 1.6.0 does not contain definition for `Document` and `Event`:

![2015-12-19_11-40-26](https://cloud.githubusercontent.com/assets/954102/11913524/5b5c3b30-a645-11e5-8890-e2db76320fea.png)

**Comment by danmana** [comment]
This looks like it's fixed/patched in #11351
