### ISSUE TITLE
whatwg-fetch: use TypeScript’s Promise definition

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#7293]
This type definition references `es6-promise` from DefinitelyTyped, but there is now a type definition for `Promise` available in TypeScript itself: https://github.com/Microsoft/TypeScript/blob/master/src/lib/es6.d.ts

Could we use this instead?

**Comment by vvakame** [comment]
yes, like this. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/wu/wu.d.ts.tscparams

**Comment by glen-84** [comment]
And what if someone is not targeting ES6?

**Comment by OliverJAsh** [comment]
@vvakame Can you elaborate? I don't understand how that helps. Apparently `tscparams` are compiler options. Here we want to use `es6-promise` if you're targeting ES5 but not if you're targeting ES6. How can we do that?

**Comment by vvakame** [comment]
@OliverJAsh you can send a pull request. if you want to compile with `--target es6` in travis ci, you should use tscparams.

**Comment by OliverJAsh** [comment]
@vvakame If we're targeting ES6, we don't want whatwg-fetch to use es6-promise. If we are targeting ES5 or lower, we do want it to use es6-promise.

Can you explain how this is possible using tscparams? I know nothing about how this file works.

I'm really keen to get this working, so if you can explain how it should work, I will happily raise a pull request.

**Comment by OliverJAsh** [comment]
whatwg-fetch no longer references es6-promise
