### ISSUE TITLE
whatwg-fetch Response has no body attribute

### ISSUE THREAD

**Issue by meetshawn** [DefinitelyTyped/DefinitelyTyped#7297]
https://fetch.spec.whatwg.org/#response-class

Response class body attribute is missing. I guess this requires a ReadableStream definition too?

**Comment by vvakame** [comment]
please send a pull request.

**Comment by macklinu** [comment]
It looks like the latest whatwg-fetch type definition includes the `Response.body` attribute. See this line:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/85e11ba06a1a17450188be580174d6c51f781e3b/whatwg-fetch/whatwg-fetch.d.ts#L93
