### ISSUE TITLE
react typings not appearing in nuget

### ISSUE THREAD

**Issue by rwyborn** [DefinitelyTyped/DefinitelyTyped#7360]
I was just trying to grab the base react typings from nuget, however they do not seem to be  available (react.d.ts or react-global.d.ts). I am only seeing all the ancillary packages in a nuget search, ie react-addons, react-router etc.

**Comment by vvakame** [comment]
@staxmanade ?

**Comment by staxmanade** [comment]
Maybe you can goose the guys who took over the name on nuget.

Details here: https://github.com/DefinitelyTyped/NugetAutomation/issues/14

**Comment by rwyborn** [comment]
@wizzard0 has not touched his react typings package for over a year, and has not responded to the above issue for 6 months. Surely someone out there has some kind of admin rights to override and re-direct to the "real" react typings package.

**Comment by staxmanade** [comment]
I've reached out to NuGet and they said we need to work it out with the package owner. (Which is frustrating). If anyone out there can get some pull on either directions - that would be awesome!

**Comment by rwyborn** [comment]
I have sent an email to the author, will keep this issue updated with any developments.

**Comment by PrasathSivalingam** [comment]
Update d.ts s are here : https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/react

**Comment by wizzard0** [comment]
hi guys, I restored my NuGet account and would be happy to transfer the package ownership - nuget does not allow me to relinquish a name so as not to break apps that might be using the packages, I can only add people with publishing rights. Who shall I add?

**Comment by staxmanade** [comment]
I'm going to close this issue and allow discussion to continue here DefinitelyTyped/NugetAutomation/issues/14
