### ISSUE TITLE
Add definition for Gulp 4

### ISSUE THREAD

**Issue by demisx** [DefinitelyTyped/DefinitelyTyped#7425]
Gulp 4 introduces new methods such as `series()` and `parallel()` that aren't part of the current gulp definition file.

**Comment by onigoetz** [comment]
I believe this was just done with #16121

**Comment by gluons** [comment]
I still haven't seen `series()` and `parallel()` in `@types/gulp@4`.

**Comment by Bleser92** [comment]
I have the same problem.

When I run a task, I get this error

```
TSError: ⨯ Unable to compile TypeScript:
gulpfile.ts(4,20): error TS2305: Module '"../../../PROJECT/node_modules/@types/gulp"' has no exported member 'series'.
gulpfile.ts(4,28): error TS2305: Module '"../../../PROJECT/node_modules/@types/gulp"' has no exported member 'parallel'.
```

If I transfer types for series and parallel from @ types/undertaker to @ types/gulp, the error disappears.

**Comment by gluons** [comment]
Ping type authors: @drewnoakes (Drew Noakes), @GiedriusGrabauskas (Giedrius Grabauskas)

// I can't find GitHub account of Juan Arroyave.
