### ISSUE TITLE
The callback parameter for `mongoose.geoNear` is incorrect

### ISSUE THREAD

**Issue by grkuntzmd** [DefinitelyTyped/DefinitelyTyped#7440]
The callback parameter for the `mongoose.geoNear` function is listed as

    callback?: (err: any, res: T[]) => void

According the the [mongoose documentation](http://mongoosejs.com/docs/api.html#model_Model.geoNear), the actual call needs a third parameter:

    callback?: (err: any, res: T[], stats: any) => void

**Comment by horiuchi** [comment]
Please fix this bug and send pull request :+1:

**Comment by grkuntzmd** [comment]
Fixed and merged to master.

**Comment by horiuchi** [comment]
@grkuntzmd Oh, Thank you :+1:
