### ISSUE TITLE
bluebird.d.ts suffer from "error TS2503: Cannot find namespace 'Promise'."

### ISSUE THREAD

**Issue by Axure** [DefinitelyTyped/DefinitelyTyped#7452]
Actually every reference of `Promise` inside this file would throw one such error.

**Comment by vvakame** [comment]
What version of tsc do you use?

**Comment by Axure** [comment]
@vvakame message TS6029: Version 1.8.0-dev.20151103

**Comment by Axure** [comment]
```
{
    "compilerOptions": {
        "noImplicitAny": false,
        "removeComments": true,
        "preserveConstEnums": true,
        "target": "es6",
        "sourceMap": true,
        "experimentalDecorators": true,
        "experimentalAsyncFunctions": true
    },
    "files": [
    ]
}
```

**Comment by vvakame** [comment]
I can't reproduce it.

```
$ npm install -g typescript@beta
$ tsc -v
Version 1.8.0
$ git rev-parse master
58e206bb7524d65ce883c84ab1c8e089d10d8353
$ tsc --target es6 bluebird/bluebird.d.ts
$ echo $?
0
```

**Comment by junedev** [comment]
I had the same error when using the bluebird typing in my project. I think it results from a clash with the node.js Promise typing. It was fixed by just deleting the version of the bluebird typing I had and installing it again (and therefore pulling the latest version).

**Comment by Axure** [comment]
@junedev , exactly.

**Comment by eschwartz** [comment]
Just a note, for anyone else making the same dumb mistake I did:

```
function asyncFn():Promise.resolve<T> {
  return Promise.resolve();
}

// -> error TS2503: Cannot find namespace 'Promise'.
```

This is just because the return type should be `Promise<T>` not `Promise.resolve<T>`.

eg

```
function asyncFn():Promise<T> {
  return Promise.resolve();
}
```

Just a dumb mistake, but the error had me thinking that I wasn't pulling in typings for the core node library properly, which sent me on a wild goose chase.
