### ISSUE TITLE
Statements using process.stdin.isTTY are not supported in node.d.ts

### ISSUE THREAD

**Issue by ChrisPearce** [DefinitelyTyped/DefinitelyTyped#7454]
Statements using process.stdin.isTTY and/or process.stdout.isTTY are not supported in the current version on node.d.ts.

**Comment by vvakame** [comment]
by #7556 :+1:

**Comment by ChrisPearce** [comment]
I'm still encountering issues after the merge.

"process.stdin" seems to be defined as type "ReadableStream" whereas the merge adds a "isTTY" property to the "ReadStream" class.

My understanding is that when Node.js detects that it's being run inside a TTY context, then "process.stdin" will be a tty.ReadStream instance and "process.stdout" will be a tty.WriteStream instance.

However, the typings seem to be assuming that the process.stdin is a ReadableStream and not a ReadStream.
