### ISSUE TITLE
Add definition for sweetalert

### ISSUE THREAD

**Issue by murbano83** [DefinitelyTyped/DefinitelyTyped#7455]
Url: http://t4t5.github.io/sweetalert/
npm Url: https://www.npmjs.com/package/sweetalert

Thanks

**Comment by borislavjivkov** [comment]
There is an existing definition file for sweetalert: [https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/sweetalert](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/sweetalert)
