### ISSUE TITLE
Definitions for aws-sdk are woefully out of date

### ISSUE THREAD

**Issue by davepgreene** [DefinitelyTyped/DefinitelyTyped#7458]
The definitions are missing a bunch of services and aren't even close to being up-to-date to the sdk's API.

@enicholson and @aldrinleal have done a bunch of work creating a generator in the [ingenieux/aws-sdk-typescript](https://github.com/ingenieux/aws-sdk-typescript) repo. Is there any way we could get the output of it merged into this repo so we can use `tsd`?

**Comment by enicholson** [comment]
I'd definitely be in favor of that.  Are there other examples of using generated definitions in DefinitelyTyped? My only concern is that we'd need to be diligent to keep changes in the generator rather than allowing hand-edits.

**Comment by aldrinleal** [comment]
I published aws-sdk-typescript into NPM, so it should be easy to use it, provided you read the instructions (npm install --save-dev ; tsd link)

**Comment by davepgreene** [comment]
Very nice! :+1:

**Comment by aldrinleal** [comment]
@davepgreene, I'm new in those things, so if you could give me any real world feedback, it would be fairly nice :)

**Comment by Roam-Cooper** [comment]
Still seems out of date. There's no definition for ECR.

**Comment by QuantumInformation** [comment]
Typescript first dev, would get defs for free.
