### ISSUE TITLE
React's StatelessComponent results in error

### ISSUE THREAD

**Issue by pdeva** [DefinitelyTyped/DefinitelyTyped#7468]
If you create a stateless element like:

```
var Hi:React.StatelessComponent<{}> = 
          (props)=><h1>User info</h1>;
```

Everything is fine so far.
But when you try to use it inside another component like:

```
var Hello:React.StatelessComponent<{}> = 
          (props)=> <div><Hi></div>;
```

you will get an error (where you tried to use the `Hi` component):

```
Error:(9, 3) TS2605: 
JSX element type 'ReactElement<any>' is not a constructor function for JSX elements.
Property 'render' is missing in type 'ReactElement<any>'.
```

**Comment by pdeva** [comment]
pinging @vsiao since he seems to be the one who added the type definition for `StatelessComponent`

**Comment by vsiao** [comment]
Sorry, I don't use JSX. Maybe @RyanCavanaugh can help you.

**Comment by tomenden** [comment]
@pdeva did you find a way to solve this issue?

**Comment by SethDavenport** [comment]
@pdeva - I believe this has been fixed in TypeScript 1.8 - they improved their TSX to handle stateless components.

**Comment by stroborobo** [comment]
Right, that's fixed in 1.8:

https://github.com/Microsoft/TypeScript/issues/5675

There's still a problem with children though:

```typescript
const Foobar = ({ children }: { children: ReactNode[] }) => <div>{children}</div>
```

```
error TS2324: Property 'children' is missing in type 'IntrinsicAttributes & { children: (ReactElement<any> | string | number | {} | (ReactElement<any> ...'.
```

Could make that optional though, or is there a nicer way?

**Comment by Strato** [comment]
I bumped into the children error and it's annoying. Does anyone know how I can circumvent it until it's being fixed?

I've been looking for a way to cast a JSX component to any, to no avail.

Something like:

    <Parent as any>
        <Children/>
    </Parent>

**Comment by stroborobo** [comment]
@Strato What about optionals as I suggested? Better than casting stuff to `any`. You know, like this:

```typescript
const Foobar = ({ children }: { children?: ReactNode[] }) => <div>{children}</div>
```

**Comment by Strato** [comment]
I didn't understand this was possible. Thank you.

Hope it gets fixed soon in the definition, as it's a pretty common pattern.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
