### ISSUE TITLE
oclazyload.d.ts inject defines wrong return type

### ISSUE THREAD

**Issue by MarkusKramer** [DefinitelyTyped/DefinitelyTyped#7477]
I'm using oclazyload's inject function in my code (oclazyload version 1.0.9). It always seems to return a promise. However, oclazyload/oclazyload.d.ts defines it as

    inject(moduleName: string|string[]): boolean;

which is definitely wrong. I would suggest:

    inject(moduleName: string|string[]): ng.IPromise<any>;

**Comment by horiuchi** [comment]
Please fix the bug of defines and send pull request :+1:
