### ISSUE TITLE
webpack.d.ts outdated - missing pre|postLoader on Module

### ISSUE THREAD

**Issue by andrewconnell** [DefinitelyTyped/DefinitelyTyped#7497]
I've been trying to figure out how to fix this but i can't get the test written just right. The current [webpack.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/078b25d4a3d64dbfe0a134ad773d08fa23d021e3/webpack/webpack.d.ts#L27-L29) only provides for `loaders` on a `module`, but the current [config docs](http://webpack.github.io/docs/configuration.html#module-preloaders-module-postloaders) show support for additional loaders like `preLoaders` and `postLoaders` in addition to other props.

Seems the typedef is written for 1.12.2 when current version is 1.12.9. Anyone good with typedef tests? :frowning:

**Comment by tkqubo** [comment]
Since this PR a41272778c9e8c0f9c930e33df6e50713f87388f has been merged, you can now use properties like `preLoaders` and `postLoaders`.  Sorry for not notifying you @andrewconnell

**Comment by andrewconnell** [comment]
NP! Thanks for doing it now so we can update our project.
