### ISSUE TITLE
mongoose.d.ts Document interface should define _id as any

### ISSUE THREAD

**Issue by jhasselkus** [DefinitelyTyped/DefinitelyTyped#7499]
In the `Document` interface definition of mongoose.d.ts (line 426), the `_id` field definition of `_id: Types.ObjectId` is wrong, as it can be any type. Instead, it should be defined as `_id: any` to allow interfaces that extend `Document` to refine the definition of `_id` as appropriate to match the schema of the model/collection.

The current definition prevents the creation of models that use common `_id`  types like `string` and `number`.

Unit test code:

    interface IZip extends mongoose.Document {
        _id: string;
    }
    interface IPerson extends mongoose.Document {
        _id: mongoose.Types.ObjectId;
    }
    interface IThing extends mongoose.Document {
        _id: number;
    }

Let me know if you want me to submit a pull request that fixes this.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.
