### ISSUE TITLE
highcharts.d.ts does not support modules

### ISSUE THREAD

**Issue by erfangc** [DefinitelyTyped/DefinitelyTyped#7501]
also referenced in https://github.com/Microsoft/TypeScript/issues/6372

if we want to use Highcharts in a CommonJs or ES6 project we cannot use `import * as Highcharts from 'highcharts|highcharts-release'` as the `.d.ts` file does not export a module

Could we add support for that?

I tried doing:

```ts
declare module 'highcharts-release' {
    export = HighchartsStatic;
}
```

However, that mysteriously led to a problem where the transpiled output  does not include a `require` for highcharts.

**Comment by vvakame** [comment]
please send a  pull request. I'll review it.

**Comment by Successful** [comment]
This is a problem I just encountered. Would be incredibly helpful if we can find a solution to this .
