### ISSUE TITLE
express.d.ts has deprecated 3.x acceptsLanguage and acceptsCharset functions

### ISSUE THREAD

**Issue by brierel** [DefinitelyTyped/DefinitelyTyped#7507]
Current express.d.ts reflects express 4.x api, but still has two 3.x deprecated functions :
- req.acceptsLanguage(lang) became req.acceptsLanguages(lang [, ...])
- req.acceptsCharset(charset) became req.acceptsCharsets(charset [, ...])

Note also :
- new 4.x req.acceptsEncodings(encoding [, ...]) has not been added
- 3x req.acceptedLanguages and req.acceptedCharsets properties are no more in 4.x

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by brierel** [comment]
Ok, I created this Pull Request : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7581
