### ISSUE TITLE
Add react-tap-event-plugin typing for Material UI

### ISSUE THREAD

**Issue by gdespoulain** [DefinitelyTyped/DefinitelyTyped#7524]
Hi everybody,

I'm developing with Typescript and Material UI, and until React v1.0 is released Material still needs the react-tap-event-plugin as a requirement.

Would it be possible to add the typing required for react-tap-event-plugin? Basically it's a small thing which looks like that:
https://gitlab.com/Thecavepeanut/material-react-ts/blob/master/ws-global-typings/react-tap-event-plugin/react-tap-event-plugin.d.ts

Thanks! :)

**Comment by mxl** [comment]
Added https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8260
