### ISSUE TITLE
typescript.d.ts enum SyntaxKind - out of date? 

### ISSUE THREAD

**Issue by jcimoch** [DefinitelyTyped/DefinitelyTyped#7557]
According to this https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/typescript%2Ftypescript.d.ts definitions InterfaceDeclaration is code 213 but when we traverse AST of simple file with one interface and try to find out node where node.kind = 213 it turns out that there is none such node but 215 is. Maybe I'm not understanding this correctly, but as far as I know Interface declaration is for example:

 ``` js
interface IHello { 
   something: string 
}
 ```

and my result for AST is

```js
Node.kind = 215
NodeObject {
  pos: 15,
  end: 62,
  decorators: undefined,
  name: NodeObject { pos: 28, end: 35, text: 'IHello' },
  typeParameters: undefined,
  heritageClauses: undefined,
  members:
   [ NodeObject {
       pos: 37,
       end: 57,
       name: [Object],
       questionToken: undefined,
       type: [Object] },
     pos: 37,
     end: 57 ] }

```

Is it possible that typescript.d.ts is out of date? I'm using latest stable typescript API for generating AST.

**Comment by vvakame** [comment]
oh, yes. TypeScript bundle .d.ts itself now.
You should use it.
