### ISSUE TITLE
chrome comes with an error

### ISSUE THREAD

**Issue by sokolandia** [DefinitelyTyped/DefinitelyTyped#7610]
I don't know maybe I am missing some other dependences but chrome.d.ts from tsd install chrome --resolve --overwrite --save is invalid and produces following errors

>> typings/chrome/chrome.d.ts(5118,17): error TS2304: Cannot find name 'KeyAlgorithm'.
>> typings/chrome/chrome.d.ts(5173,97): error TS2304: Cannot find name 'CryptoKey'.
>> typings/chrome/chrome.d.ts(5173,121): error TS2304: Cannot find name 'CryptoKey'.

**Comment by sokolandia** [comment]
patched with  
interface KeyAlgorithm {}
interface CryptoKey {}

**Comment by sokolandia** [comment]
Now I can't import anything;

import identity = chrome.identity;
var a: identity; 

gives error TS2304: Cannot find name 'identity'

At the same time imports from angular and this line work fine.
import Tab = chrome.tabs.Tab;
var b: Tab;

tsd.d.ts is all referenced up

plz can someone check if it's me or is it a bug?

**Comment by Litee** [comment]
I suggest to close - chome definitions work find with lib.es6.d.ts (not default lib)
