### ISSUE TITLE
Update angular2 to beta

### ISSUE THREAD

**Issue by alex94puchades** [DefinitelyTyped/DefinitelyTyped#7626]
Now that angular2 has reached beta, we can trust the api will stabilize. However, the disposition of some files has changed (see https://angular.io/docs/ts/latest/quickstart.html#!#boot).

**Comment by vvakame** [comment]
angular2 bundled .d.ts file itself. please use it.

**Comment by softboy99** [comment]
how to use the boundled file?

**Comment by vvakame** [comment]
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Typings%20for%20NPM%20Packages.md
check this document.
