### ISSUE TITLE
react.typescript.definitelytyped NuGet package issue.

### ISSUE THREAD

**Issue by dberryalliance** [DefinitelyTyped/DefinitelyTyped#7638]
https://www.nuget.org/packages/React.TypeScript.DefinitelyTyped/

This package appears to be overriding, displacing the automated NuGet package build of the legitimate TypeScript "react" package.  References abound, throughout TypeScript .TSX guides and how-to documents about this package--however, the package does not follow the standard deployment model, and is not from the DefinitelyTyped GitHub repository.  I strongly encourage/recommend that a DefinitelyTyped administrator/project lead submit an abuse request to the NuGet repository about this ill-fitted plagiarism, and outdated hijacking of DefinitelyTyped material.

**Comment by vvakame** [comment]
@staxmanade ?

**Comment by staxmanade** [comment]
We're are working on it. You can follow the progress here https://github.com/DefinitelyTyped/NugetAutomation/issues/14
