### ISSUE TITLE
NuGet package generation issue

### ISSUE THREAD

**Issue by slozier** [DefinitelyTyped/DefinitelyTyped#7641]
I'm not sure if this is the correct place to report this...

There appears to be an issue with the generation of NuGet packages. For example, over the past few days there have been 40+ new versions of jquery.TypeScript.DefinitelyTyped on NuGet. The definition file is identical for all of these. I've also noticed the same issue with jqueryui.TypeScript.DefinitelyTyped.

**Comment by smithkl42** [comment]
I'm noticing this as well. It's not critical, but it's very definitely annoying. Not sure how the nuget packages are generated, but there definitely seems to be a problem.

**Comment by staxmanade** [comment]
WHY do people take over NuGet names that end with anything `*.TypeScript.DefinitelyTyped`? It was named that way for a reason... If someone wants to create a TypeScript def they should name it something other than ending with the above convention. grrr - just venting.

These people/projects are a problem (and so far I have no way to deter/counter them...)
https://github.com/DefinitelyTyped/NugetAutomation/blob/master/CreatePackages.ps1#L16-L23

It should be fixed now now: https://ci.appveyor.com/project/JasonJarrett/nugetautomation/history and not be updating every 2 hours (sorry about that)

**Comment by smithkl42** [comment]
Thank you!
