### ISSUE TITLE
Webpack interface should extend Function

### ISSUE THREAD

**Issue by delduggel** [DefinitelyTyped/DefinitelyTyped#7644]
I was attempting to build out a gulp library that invokes webpack programmatically in Typescript and ran into a snag when I went to call the webpack function itself. Looking in the webpack.d.ts file I couldn't find any functions that were being exported, but the object you get when you import the native JS version of Webpack is a function that takes a Configuration and a callback Function.

As a workaround, I edited webpack.d.ts and slapped an "extends Function" on the end of the Webpack interface and then I was able to execute it. I'm fairly new to Typescript and wasn't sure if this was the optimal solution as it doesn't supply the types for the arguments. I'll leave the optimal solution up to you, but however it's resolved I believe the type definition is missing that last crucial piece needed to invoke webpack programmatically.

Thanks!

**Comment by vvakame** [comment]
@tkqubo ?

**Comment by tkqubo** [comment]
@delduggel @vvakame Sorry for the late response.  I made a PR to add node.js api definitions.  I hope this would be of some help to you.  Since this definition is not complete, if you still find inconvenience, please let me know @delduggel

**Comment by delduggel** [comment]
That did the trick. Thanks
