### ISSUE TITLE
Generic KnockoutSubscribableFunctions + KnockoutSubscribable

### ISSUE THREAD

**Issue by lcorneliussen** [DefinitelyTyped/DefinitelyTyped#765]
Shouldn't all observables implement KnockoutSubscribable<T>?
(could be via KnockoutSubscribableFunctions<T>)

KnockoutObservableArray<T> would then be KnockoutSubscribable<T[]>

subscribe should return KnockoutSubscription, with the possibility to dispose the subscription. Currently KnockoutSubscription offers subscribe...

Or am i totally of?

**Comment by ltlombardi** [comment]
@vvakame This should be closed. Already fixed. :blush:

**Comment by ltlombardi** [comment]
Wow.. 6 year latter.

**Comment by lcorneliussen** [comment]
The ticket is 11 years old even 😁
