### ISSUE TITLE
Definition Request: Immutable.js

### ISSUE THREAD

**Issue by reverofevil** [DefinitelyTyped/DefinitelyTyped#7681]
Please, add definitions for [Immutable.js](https://github.com/facebook/immutable-js). There're already written definitions in a repo, yet they're not posted here. I've [asked](https://github.com/facebook/immutable-js/issues/764) Facebook guys for cooperation, because I don't know if the license allows it.

**Comment by AyaMorisawa** [comment]
dup of #6139 ?

**Comment by polkovnikov-ph** [comment]
Probably so. Yet I'd like to hear from the author of the mentioned PR, because things don't seem to be moving and author have already deleted the fork of `DefinitelyTyped` from his account.

**Comment by remojansen** [comment]
The [Immutable.d.ts](https://github.com/facebook/immutable-js/blob/master/type-definitions/Immutable.d.ts) file is included in the npm package.
