### ISSUE TITLE
Definition request: lodash-amd, lodash-es

### ISSUE THREAD

**Issue by rootical** [DefinitelyTyped/DefinitelyTyped#7691]
https://github.com/lodash/lodash/tree/amd
https://github.com/lodash/lodash/tree/es

**Comment by stephenlautier** [comment]
I've created a PR for lodash-es https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12812

**Comment by e-cloud** [comment]
sound like this issue can be closed now, @horiuchi

**Comment by e-cloud** [comment]
sound like this issue can be closed now, @horiuchi

**Comment by horiuchi** [comment]
@e-cloud Thank you for your mention. 👍
