### ISSUE TITLE
ui-grid.d.ts: Wrong definition for function: rowIdentity

### ISSUE THREAD

**Issue by debian0501** [DefinitelyTyped/DefinitelyTyped#7707]
The function rowIdentity is defined as
rowIdentity?(): any;

but should be defined as:
rowIdentity?(row: IGridRowOf<TEntity>): any; 

see ui-grid.js
baseOptions.rowIdentity = baseOptions.rowIdentity || function rowIdentity(row) {
        return gridUtil.hashKey(row);
};

**Comment by vvakame** [comment]
please send a pull request.

**Comment by AbhishekGarg** [comment]
PR #8966

**Comment by vvakame** [comment]
👍
