### ISSUE TITLE
Lodash "Function" return type is not compatible with actual functions

### ISSUE THREAD

**Issue by soswow** [DefinitelyTyped/DefinitelyTyped#7712]
Consider this simplest example:
```typescript
let func = (elementIndex: number, object: any, index: number) => {
    console.log(object, index, elementIndex);
};
let array = ["a", "b", "c"];
array.forEach(_.partial(func, 0));
```

In JS it would be perfect example of using `_.partial`, but with TS and current lodash definition it gives:
```
Argument of type 'Function' is not assignable to parameter of type '(value: string, index: number, array: string[]) => void'.
```

Since lodash definition of _.partial returns `Function`

I can't find how can I use it with current definition.

**Comment by vvakame** [comment]
@chrootsu ?

**Comment by chrootsu** [comment]
@soswow I can't reproduce the error. I tried all combinations of `tsc` 1.6.2, 1.7.3, 1.7.5 and the latest definitions of `lodash` 3.10, 4.0. It always compiles without errors.
Hmm... What versions of `tsc` and definition do you use?

**Comment by soswow** [comment]
@chrootsu hm. Indeed. I've made a fake example thinking there are general problem and haven't tested this particular example. It IS compiling for me.
Let me find an actual example where I had a problem.

**Comment by soswow** [comment]
Or maybe we bumped TypeScript version since I reported the bug ...

**Comment by soswow** [comment]
Let me close this issue and if I find any problem I'll reopen it.
We had 1.6.0 Typescrip at some point and  Lodash 3.10

**Comment by chrootsu** [comment]
@soswow Okay. However, thanks for a bug report! =)
