### ISSUE TITLE
AngularJS : IHttpRequestConfigHeaders interface Type

### ISSUE THREAD

**Issue by labrute** [DefinitelyTyped/DefinitelyTyped#7730]
I have a doubt about the IHttpRequestConfigHeaders interface.
I don't think that element (get, post ...) are String but an object.

You can see an example of how to define the headers here : (https://docs.angularjs.org/api/ng/service/$http) in Setting HTTP Headers section.

It doesn't match with the IHttpRequestConfigHeaders  interface defined in typescript :
``` 
interface IHttpRequestConfigHeaders {
        [requestType: string]: string|(() => string);
        common?: string|(() => string);
        get?: string|(() => string);
        post?: string|(() => string);
        put?: string|(() => string);
        patch?: string|(() => string);
    }
```

With the current definiton i have some issue when i change my cache settings : 

``` 
export function config($httpProvider: angular.IHttpProvider, $logProvider: angular.ILogProvider) {
    $httpProvider.defaults.cache = false;
    // initialize get if not there
    if (!$httpProvider.defaults.headers.get) {
        $httpProvider.defaults.headers.get = {}; // The problem
    }

    // enables Request.IsAjaxRequest() in ASP.NET MVC
    $httpProvider.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

    // disable IE ajax request caching
    $httpProvider.defaults.headers.get['If-Modified-Since'] = 'Mon, 26 Jul 1997 05:00:00 GMT';

    // extra
    $httpProvider.defaults.headers.get['Cache-Control'] = 'no-cache';
    $httpProvider.defaults.headers.get['Pragma'] = 'no-cache';

    // enable log
    $logProvider.debugEnabled(true);
}
``` 

It create an error on set 'get' property to empty object, and it should not.

Can somebody confirm that get, post, common, put and patch are not string ?

**Comment by rivanov2** [comment]
I tried to set the same thing, following [this](http://stackoverflow.com/questions/16098430/angular-ie-caching-issue-for-http) SO post, and got the same results as you. I think you're right.

**Comment by mmiszy** [comment]
I think the correct solution is more complicated. Allowed values of eg. `$httpProvider.defaults.headers.get` are either a string->string dictionary, or a function with one parameter. `string` is indeed not allowed.

```typescript
type HttpHeaderType = {[requestType: string]:string|((config:IRequestConfig) => string)};

interface IHttpRequestConfigHeaders {
    [requestType: string]: HttpHeaderType;
    common?: HttpHeaderType;
    get?: HttpHeaderType;
    post?: HttpHeaderType;
    put?: HttpHeaderType;
    patch?: HttpHeaderType;
}
```
