### ISSUE TITLE
AngularJs: angular.IHttpInterceptor's response method returns the wrong type

### ISSUE THREAD

**Issue by kawazoe** [DefinitelyTyped/DefinitelyTyped#7736]
I've been trying to write a simple HttpInterceptor based of the AngularJs typings and I noticed that in the angular.IHttpInterceptor interface, the response method is defined as follow:

```
response?: <T>(response: IHttpPromiseCallbackArg<T>) => IPromise<T>|T;
```

This is a problem because angular expects the full response to be returned and not just the data that it contains. For instance, the current implementation breaks the ngInclude directive. It should be defined as:

```
response?: <T>(response: IHttpPromiseCallbackArg<T>) => IPromise<IHttpPromiseCallbackArg<T>>|IHttpPromiseCallbackArg<T>;
```

**Comment by vvakame** [comment]
please send a pull request.
