### ISSUE TITLE
ag-grid require function declaration conflict

### ISSUE THREAD

**Issue by vlio20** [DefinitelyTyped/DefinitelyTyped#7738]
Hi,
I am using ag-grid.tsd and it has declaration for require function `declare function require(name: string): any;` (line 1467). 
The conflict is with "awesome-typescript-loader" library, it's `runtime.d.ts`.

Here is a screenshot of the error:
http://prntscr.com/9thxro

**Comment by vvakame** [comment]
ag-grid does not contains `require` implementations.
I think we can remove this line https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a39e8c409e7a56d3fb5842b3bbbf5357b5f1b752/ag-grid/ag-grid.d.ts#L1467
please send a pull request :wink:
