### ISSUE TITLE
Default arg to type any even definition specified as knex.QueryBuilder

### ISSUE THREAD

**Issue by singachea** [DefinitelyTyped/DefinitelyTyped#7749]
Hi @DomiR, @tkrotoff 
Sorry if this is a noob question or probably it might not be related to type definition here, but i'm really curious about autocomplete in both Atom and VS Code.

<img width="876" alt="screen shot 2016-01-24 at 1 36 26 am" src="https://cloud.githubusercontent.com/assets/813988/12531735/42808134-c23d-11e5-8da4-17488f073d2b.png">

The definition of collection should be here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/bookshelf/bookshelf.d.ts#L219

Somehow `qb` doesn't give any suggestion (typed `any`) unless I have to explicitly specify type `(qb: knex.QueryBuilder) =>`. Any simple explanation why both Atom and VS Code suggest `qb` as type `any`? I'm a newbie for typescript.

**Comment by tkrotoff** [comment]
Can you give us the small example so we can just copy-paste it and test?

**Comment by singachea** [comment]
Sure... 

Here is the normal express `app.js`
```javascript
import * as express from 'express';
import * as knex from 'knex';
import {Books} from './models/book'


let app = express();

app.get('/', async (req, res) => {
  let books = await (new Books()).query((qb) => {
    qb.where('id', '>', 6).andWhere('id', '<', 10)
  }).fetch()

  res.json(books)
});
```

And here is the `book.js` model

```javascript
import {bookshelf} from './connection';

export class Book extends bookshelf.Model<Book> {
  get tableName() { return 'books' };
}

export class Books extends bookshelf.Collection<Book> {
  get model() { return Book }
}
```

The app is running fine at `/` root with correct expected result, but I wonder why `qb` is not typed as `knex.QueryBuilder` as defined in bookshelf definition file.

**Comment by tkrotoff** [comment]
query() is defined multiple times:
```TypeScript
query(...query : string[]) : Collection<T>;
query(query : {[key : string] : any}) : Collection<T>;
query(callback : (qb : knex.QueryBuilder) => void) : Collection<T>;
query() : knex.QueryBuilder;
```
See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/bookshelf/bookshelf.d.ts#L217

If you comment out `query(query : {[key : string] : any}) : Collection<T>` then it works. I ignore why TypeScript is confused here. I could not find any example that uses `query(query : {[key : string] : any}) : Collection<T>`

Copy-paste ready example:
```TypeScript
/// <reference path="node_modules/DefinitelyTyped/node/node.d.ts" />
/// <reference path="node_modules/DefinitelyTyped/express/express.d.ts" />
/// <reference path="node_modules/DefinitelyTyped/bluebird/bluebird.d.ts" />
/// <reference path="node_modules/DefinitelyTyped/knex/knex.d.ts" />
/// <reference path="node_modules/DefinitelyTyped/bookshelf/bookshelf.d.ts" />

import * as Knex from 'knex';
import * as Bookshelf from 'bookshelf';

const config: any = {};
const knex = Knex(config);
const bookshelf = Bookshelf(knex);

class Book extends bookshelf.Model<Book> {
  get tableName() { return 'books'; }
}

class Books extends bookshelf.Collection<Book> {
  get model() { return Book; }
}

import * as express from 'express';

const app = express();

app.get('/', async (req, res) => {
  const books = await new Books().query(qb => {
    qb.where('id', '>', 6).andWhere('id', '<', 10);
  }).fetch();

  res.json(books);
});
```

**Comment by singachea** [comment]
Yes, you are right. If I comment that line 217, the `qb` is typed as `knex.QueryBuilder`. But then I tried to reorder them as:

```javascript
query(callback : (qb : knex.QueryBuilder) => void) : Collection<T>;
query(query : {[key : string] : any}) : Collection<T>;
```
And everything works as expected! I'm not sure if this is considered as bug. 

Here is the example to use both of them.
```javascript
app.get('/', async (req, res) => {
  let books = await (new Books()).query((qb) => {
    qb.where('id', '>', 6).andWhere('id', '<', 10)
  }).fetch()
  
  let books2 = await (new Books()).query({'where': {'id': 5}}).fetch()
  
  res.json({books: books, books2: books2})
});
```

**Comment by taybin** [comment]
This can be closed as knex provides its own definitions now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
