### ISSUE TITLE
mongodb.ts cursor.forEach missing?

### ISSUE THREAD

**Issue by jule64** [DefinitelyTyped/DefinitelyTyped#7755]
Hi guys, I can't find the `forEach` method definition of the Cursor class in mongodb.ts (master), can't find in the other branches either.  `Cursor.forEach` is part of mongodb lib (2.1 at least).
Happy to send a pull request with the method definition if you agree.
Thanks for the help

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by jule64** [comment]
#7565 fixed it. Thanks
