### ISSUE TITLE
Definition for QuillJs

### ISSUE THREAD

**Issue by sumitkm** [DefinitelyTyped/DefinitelyTyped#7767]
If no one is working on a definition for Quill JS http://quilljs.com is it okay to submit a PR for it?

Regards.

**Comment by vvakame** [comment]
:+1:

**Comment by sumitkm** [comment]
thank you, I should be able to submit it tonight GMT.

**Comment by sumitkm** [comment]
Pull request #7792 merged. Thank you very much!

**Comment by benbro** [comment]
@sumitkm any chance you could update the quilljs definition to 1.0.0?
https://github.com/quilljs/quill/releases/tag/v1.0.0

**Comment by sumitkm** [comment]
Yups, on it...

Cheers,
Sumit.

-----Original Message-----

**Comment by sumitkm** [comment]
@benbro Submitted PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11073 Should be available via definition managers once merged. You can use my fork till such time.
Cheers!

**Comment by benbro** [comment]
@ sumitkm thank you very much.
The link in your PR is for jquery instead of quilljs.

**Comment by benbro** [comment]
Added quill and the quill type definition to my package.json:
```json
"dependencies": {
    "quill": "^1.0.4",
    "@types/quill": "*"
}
```

I would expect to be able to do:
```javascript
import Quill from 'quill';
```
but instead I need to do:
```javascript
import * as Quill from 'Quill';
```
Is it possible to change it?


The auto complete in visual studio code gives me:
```
Quill (alias) new Quill(selector: string, options?: QuillJS...
{} QuillJS
```
Is it possible to show only Quill without the alias and QuillJS?
