### ISSUE TITLE
Add definition for mapbox-gl

### ISSUE THREAD

**Issue by NaiLi** [DefinitelyTyped/DefinitelyTyped#7774]
There is only a def for mapbox.js, one for mapbox-gl.js would be great!

**Comment by dobrud** [comment]
here you go: https://github.com/dobrud/typed-mapbox-gl
Let me know if something is missing

**Comment by alejo90** [comment]
@vvakame @mhegazy @andy-ms This issue can be closed now. 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d907b02638bf6c56ae3f632ca5c151cb869df5b4/mapbox-gl/mapbox-gl.d.ts
