### ISSUE TITLE
Compiler issues with jasmine.d.ts

### ISSUE THREAD

**Issue by MrWako** [DefinitelyTyped/DefinitelyTyped#7793]
Hi Folks, thanks for all the good work on the definitely typed modules. I'm using the jasmine.d.ts installed via tsd. The following 2 lines reproduces the issues I'm having:

/// <reference path="../typings/tsd.d.ts"/>
import \* as jasmine from 'jasmine';

When compiled with tsc they generate:

error TS2307: Cannot find module 'jasmine'.

which I think this is due to not having inverted commas around the name jasmine in the line

declare module jasmine {

If this is fixed then the next issues are:

error TS2503: Cannot find namespace 'jasmine'.

coming from the use of jasmine.Matchers & jasmine.Spy earlier in the file. Perhaps someone more familiar with type definitions could take a look.

Thanks

**Comment by MrWako** [comment]
Sorry the code above didn't style well. Was meant to be:

```javascript
/// <reference path="../typings/tsd.d.ts"/>
import * as jasmine from 'jasmine';
```

**Comment by chrootsu** [comment]
Hi. You have no need to import `jasmine` like an external module, it defines few functions (describe, it, etc...) and `jasmine` object in global context and they will be accessible during tests. You only have to reference to the definition file in test specs.

**Comment by MrWako** [comment]
Hi Chrootsu, thanks - yes I agree the current definition is great for writing Jasmine spec files. My problem is I also have a script (testRunner.js) to configure the reporters etc for Jasmine. A cut down version looks something like:
```
/// <reference path="../typings/tsd.d.ts"/>

import * as jasmine from 'jasmine';

let environment: jasmine.Env = new jasmine();
environment.loadConfigFile(__dirname + '../jasmine.json');

// configure reporters and add to environment

environment.execute();
```

and then I re-use this script for code coverage, something like:

```
istanbul cover testRunner.js
```

Its with this usecase that I'm having the issues with the module definition. Thanks.

**Comment by chrootsu** [comment]
Update still in the progress, but if you wish, you can already try it because your issue has to be solved.
https://github.com/chrootsu/DefinitelyTyped/blob/jasmine-update/jasmine/jasmine.d.ts

**Comment by MrWako** [comment]
Hi Chrootsu - many thanks for taking a look at this. The latest version is now working for me.

**Comment by chrootsu** [comment]
I'm glad that I can help. ^_^

**Comment by StefH** [comment]
Same issue still here with the new **typings-2.0**.

Error message in my _test.ts_ file:

> [ts] File 'c:/Users/.../node_modules/@types/jasmine/index.d.ts' is not a module.

**Comment by StefH** [comment]
@chrootsu Can you maybe create a PR ?

**Comment by chrootsu** [comment]
@StefH Sorry I have no time to do it right now. I have added a task to my list and I will try to take a look when it become possible.

**Comment by dave-hillier** [comment]
I'm seeing the same problem as @StefH.  What is the issue with it? How are they converted?

**Comment by radziksh** [comment]
+1

**Comment by mhegazy** [comment]
based on the [documentation](https://jasmine.github.io/2.1/node.html).


The file at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jasmine/index.d.ts should be augmented to include:

```ts
declare module "jasmine" {
    class jasmine {
        constructor(options: any);
        jasmine: jasmine.Jasmine;
        addMatchers(matchers: jasmine.CustomMatcherFactories): void;
        addReporter(reporter: jasmine.Reporter): void;
        addSpecFile(filePath: string): void;
        addSpecFiles(files: string[]): void;
        configureDefaultReporter(options: any, ...args: any[]): void;
        execute(files: any, filterString: any): any;
        exitCodeCompletion(passed: any): void;
        loadConfig(config: any): void;
        loadConfigFile(configFilePath: any): void;
        loadHelpers(): void;
        loadSpecs(): void;
        onComplete(onCompleteCallback: () => void): void;
        provideFallbackReporter(reporter: jasmine.Reporter): void;
        randomizeTests(value?: any): boolean;
        seed(value: any): void;
        showColors(value: any): void;
        stopSpecOnExpectationFailure(value: any): void;
        static ConsoleReporter(): any;
        env: jasmine.Env;
        reportersCount: number;
        completionReporter: jasmine.CustomReporter;
        reporter: jasmine.CustomReporter;
        coreVersion(): string;
        showingColors: boolean;
        projectBaseDir: string;
        printDeprecation(): void;
        specFiles: string[];
        helperFiles: string[];
    }
    export = jasmine;
}
```

Feel free to send a PR and I would be happy to get it in.

**Comment by SET001** [comment]
Still having this issue *(
