### ISSUE TITLE
RTCPeerConnection.d.ts - improvements

### ISSUE THREAD

**Issue by GeniousG** [DefinitelyTyped/DefinitelyTyped#7842]
Hi, 

I have two suggestions for the RTCPeerConnection.d.ts file.
1.  change:
```typescript
interface RTCIceServer {
  url: string;
  credential?: string;
}
```
to:
```typescript
interface RTCIceServer {
  urls: string;
  credential?: string;
}
```
At the moment I'm extending the interface with urls:string and set url = undefined as a workaround (which i find kind of ugly -> do you know another way?)

This would help, since urls is depricated.

Another thing would be to add (not really necessary since it can be added easily) to access the "getUserMedia" method created by adapter.js:

```typescripit
declare var getUserMedia: NavigatorGetUserMedia;
```

Thanks for reading ;) - what do you think?

Best regards,
George

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by GeniousG** [comment]
Thanks! Here is the pull request:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7876
