### ISSUE TITLE
Definition Request: ramda.js

### ISSUE THREAD

**Issue by r-k-b** [DefinitelyTyped/DefinitelyTyped#7880]
Voting for Ramda stub: <http://ramdajs.com/>

Work in progress: <https://github.com/donnut/typescript-ramda>

**Comment by arcseldon** [comment]
+1  definitely be very helpful.

**Comment by remojansen** [comment]
:+1: should we add them or wait? https://github.com/donnut/typescript-ramda/issues/39

**Comment by donnut** [comment]
I think the type definitions of ramda are now mature enough it can be added. I'll try to add it in the next couple of days.

**Comment by tylerlong** [comment]
Any updates?

**Comment by faceleg** [comment]
@donnut bump

**Comment by donnut** [comment]
The ramda typings are available using https://github.com/typings/typings

**Comment by faceleg** [comment]
Sadly they don't work with typescript 2's `npm install -- save @types/ramda`, which will be standard soon

**Comment by remojansen** [comment]
To work with @types/ramda all we need to do is to add them to the DefinitelyTyped there is a bot that publish them to npm

**Comment by donnut** [comment]
Hmmm, oke, I'll try to include the typings this week. Having multiply repo's with duplicate code is no fun :(

**Comment by donnut** [comment]
@remojansen I haven't read the contribution guide, but I hope there is no different format required.

**Comment by faceleg** [comment]
The new way is slated to become The One True Way, so hopefully you don't have to maintain two for long. 

The typings should work with the new way as they are.

**Comment by donnut** [comment]
:+1:

**Comment by rickmed** [comment]
bump :)

**Comment by donnut** [comment]
#10635

**Comment by faceleg** [comment]
Thank you so much @donnut!
