### ISSUE TITLE
Angular JS : ng.IDirective does not controller property

### ISSUE THREAD

**Issue by petrpcr** [DefinitelyTyped/DefinitelyTyped#789]
hi,
i try to write directive and  i'm afraid, that **_controller_** property missing. Visit  http://docs.angularjs.org/guide/directive   and try to read  **Writing directives (long version)**.

**Comment by galuszkak** [comment]
This should be closed, as `IDirective` has property controller. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/angular/index.d.ts#L1989 . I think this is fixed and should be closed.
