### ISSUE TITLE
Update angular-translate to 2.9.0

### ISSUE THREAD

**Issue by Slettan** [DefinitelyTyped/DefinitelyTyped#7933]
angular-translate was recently updated to 2.9.0 and introduced a couple of new features. It would be great if the type definitions could be updated to include these.

https://github.com/angular-translate/angular-translate/blob/master/CHANGELOG.md

Thanks.

**Comment by galuszkak** [comment]
I think those are included as newest version of angular-transalte in DefinitelyTyped is 2.15, therefore I believe this issue should be closed.
