### ISSUE TITLE
Quill.js definition is missing constructor interface

### ISSUE THREAD

**Issue by fongandrew** [DefinitelyTyped/DefinitelyTyped#7943]
@sumitkm, the new Quill interface at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/quill/quill.d.ts is missing a constructor interface.

I think the [tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/quill/quill-tests.ts) are passing because you have `export var Quill = require("quill")` at the top of your test, but the `require` function returns `any`, so your tests aren't properly exercising the definition. If you remove that line, you get a whole bunch of `error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature` when you try to build the test file.

**Comment by sumitkm** [comment]
@fongandrew Thanks Andrew, on it. Will submit a PR with the fix hopefully by end of day today (GMT).

**Comment by fongandrew** [comment]
Thanks! No rush on my end -- just wanted to point it out.

**Comment by sumitkm** [comment]
@fongandrew thanks for your inputs, glad to incorporate further suggestions.
@vvakame Thanks for merging.
