### ISSUE TITLE
Office.MailboxEnums.BodyType in office-js.d.ts has incorrect casing

### ISSUE THREAD

**Issue by Savij** [DefinitelyTyped/DefinitelyTyped#7953]
When calling:
`getTypeAsync(function (result) { ...}`

currently the definition is:
`Office.MailboxEnums.BodyType.HTML`

the value sent in result will not match this as the definition is incorrectly cased. 

The correct casing is:
`Office.MailboxEnums.BodyType.Html`
eg:
`if (result.value == Office.MailboxEnums.BodyType.Html) {...}`

**Comment by Savij** [comment]
I put in a PR with same info.

**Comment by ElizabethSamuel-MSFT** [comment]
@Savij: This is no longer applicable so please close. Thanks.
