### ISSUE TITLE
request.d.ts: Options union types 

### ISSUE THREAD

**Issue by aleung** [DefinitelyTyped/DefinitelyTyped#7979]
In request.d.ts ([lines](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4ec3c5bf291bc02f49eb30c1077340b235165c67/request/request.d.ts#L116-L122)) it defines options as union types:

``` js
interface CoreOptions {
    // ...
}
interface UriOptions {
    uri: string;
}
interface UrlOptions {
    url: string;
}
export type RequiredUriUrl = UriOptions | UrlOptions;
export type Options = RequiredUriUrl & CoreOptions;
```

With this definition, it's unable to access (read or overwrite) the `uri`/`url` property. Below TypeScript code fail to compile:

``` js
const opt: Options = {
  baseUrl: 'http://localhost',
  uri: 'bar'
};

console.log(opt.uri);
// error TS2339: Property 'uri' does not exist on type 'UriOptions | UrlOptions'.
```

**Comment by aleung** [comment]
@joeskeen 

How about define like this?

``` js
type OptionsWithUri = UriOptions & CoreOptions;
type OptionsWithUrl = UrlOptions & CoreOptions;
type Options = OptionsWithUri | OptionsWithUrl;
```

Then in application I can specify the opt type as `OptionsWithUri`:

``` js
const opt: OptionsWithUri = {
  baseUrl: 'http://localhost',
  uri: 'bar'
};
```

**Comment by joeskeen** [comment]
@aleung At first glance, it looks like it would work.  I'll have to dig in and try it out a little more this weekend, then would you like to put together a PR or should I?  Either way we should add your use case to the tests so that we don't have a regression of this issue.

**Comment by OwnageIsMagic** [comment]
```js
request.post(url, {...}, function(error, resp, body) {
      var redir = resp.request.uri.href;
})
```
I'm trying to get url after redirect, but TS says `Property 'uri' does not exist on type 'Options'.
  Property 'uri' does not exist on type 'OptionsWithUrl'.`
If I change to
```js
      var redir = resp.request.url.href;
```
`Property 'url' does not exist on type 'Options'.
  Property 'url' does not exist on type 'OptionsWithUri'.`
