### ISSUE TITLE
Lots of errors on JQuery dts and some in AngularJs dts

### ISSUE THREAD

**Issue by victorarcasrios** [DefinitelyTyped/DefinitelyTyped#7986]
I'm getting lots of errors on Visual Studio Typescript compiler when running my solution after adding this simple AngularJS controller

   ////// <reference path="../../../Scripts/typings/angularjs/angular.d.ts" />

```
"use strict";

class ProgressBarController {
    static $inject: Array<string> = ["$rootScope", "$element"];
    static measure = "px";
    static startPageFactor = 1;
    static endPageFactor = 1;

    private rootScope; // todo define RootScope boilerplate
    private element: JQuery;

    constructor($rootScope, $element: JQuery) {
        this.rootScope = $rootScope;
        this.element = $element;
    }

    getWidth(): string {
        var self = ProgressBarController,
            masterBarWidth = parseFloat(this.element.css("width").split(self.measure)[0]),
            totalPages = this.rootScope.app.pages.length - self.endPageFactor,
            eachPageProgress = (masterBarWidth / totalPages),
            currentPage = this.rootScope.app.currentIndex(),
            progress = eachPageProgress * (currentPage - self.startPageFactor);

        return progress + self.measure;
    }
}

angular.module("myDirectives")
    .controller("progressBarController", ProgressBarController);
```

I'm using AngularJS 1.4.9, DefinitelyTyped angular.d.ts for AngularJS 1.4+ and Visual Studio Community 2015 with Resharper 9.0 Update 1. The Typescript Tools of my project are on 1.7 and the compiler is aiming to ES3 for IE8 compatibility.

The errors are like more than 400 and the 95% come from jquery.d.ts. Are all different and one of them is "cannot find name bool".

I'm having problems also to use ng, IAngularStatic, IScope... so I just avoided them
Is annoying

**Comment by vvakame** [comment]
please try with master/HEAD of this repo.

**Comment by sergiomichels** [comment]
Same issue here with `IAngularStatic`. I'm using 

 - tsify@0.14.1
 - typescript@1.8.9

The error happens in my controller, when it references angular (forked from [here](https://github.com/enaukkarinen/Browserify-TypeScript-Angular-Gulp--Boilerplate))

```
/// <reference path="../../../typings/main.d.ts" />

import { Beef } from  "./beef";

"use strict";

export default class BeefController {
	
	beef :Beef;
	
    static $inject = ["$stateParams"];
    constructor(private $stateParams) {
		this.beef = this.$stateParams.beef;
        console.log(this.beef);
	}
}

angular.module("app.beef").controller("BeefController", BeefController);
```

```/src/features/beef/beef.controller.ts(18,9): Error TS2339: Property 'module' does not
exist on type 'IAngularStatic'.```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
