### ISSUE TITLE
React.d.ts type constrained definition for React.Component's setState method

### ISSUE THREAD

**Issue by saosebastiao** [DefinitelyTyped/DefinitelyTyped#7987]
In vanilla React, the state object in a component can be updated one key at a time using the setState method. So even though you may have `this.state === {foo: "bar", baz: "qux"}`, you can call `this.setState({foo:"boo"});` and leave the `baz` key intact. 

With typescript and its typed interfaces for the state object, if you want to incrementally update keys, you have two choices:

1) make the interface key definition nullable, losing some of the benefits of stronger typing:

```
interface ILoginModel {
  email?: string;
  password?: string;
  errorMsg?: string;
}
```

2) Update every key with every update. This potentially introduces bugs because this.state is updated asynchronously, and reading from it and assigning to it using this.setState can erase updates that are still in the pipeline. 

```
  handlePasswordChange = (event) => {
    this.setState({
      email: this.state.email,
      password: event.target.value,
      errorMsg: this.state.errorMsg
    });
  };
```

However, with typescript 1.8, we can now use type parameters as constaints. [For example](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript): 

```
function assign<T extends U, U>(target: T, source: U): T {
    for (let id in source) {
        target[id] = source[id];
    }
    return target;
}

let x = { a: 1, b: 2, c: 3, d: 4 };
assign(x, { b: 10, d: 20 });
assign(x, { e: 0 });  // Error 
```

This should give us an opportunity to use a non-nullable state interface definition, while being able to incrementally update the state object using `this.setState` one key at a time, without reading from `this.state`. 

However, this introduction would cause a backwards incompatibility with pre-1.8 users of typescript (which is still in beta, but likely to be released soon). As such, it should probably be discussed with the community before doing so, unless there is some way to qualify the type definitions based on typescript version.

**Comment by vsiao** [comment]
Actually, 1.8 doesn't really solve the problem. See https://github.com/Microsoft/TypeScript/issues/4889#issuecomment-178819795

**Comment by basarat** [comment]
> losing some of the benefits of stronger typing

Can you provide a specific example. With https://basarat.gitbooks.io/typescript/content/docs/types/freshness.html done I haven't found this to be a big problem :rose:

**Comment by flyon** [comment]
@basarat freshness does not seem to resolve this. 
Here's a specific example. The idea is to provide a class that extends React.Component, which defines it's own state properties but also allows any class that extends _it_ to define it's own:

```
import * as React from 'react';
interface AState {
	foo?:string;
}
interface BState {
	bar?:string;
}
//A is defining a state interface
class A<P,S extends AState> extends React.Component<P,S>
{
	componentWillMount()
	{
		this.setState({foo:"works"}); //<-- Argument of type '{ foo: string; }' is not assignable to parameter of type 'S'.
	}
}
//while still allowing classes that extend A to add their own state properties
class B extends A<any,BState>
{
	componentWillMount()
	{
		this.setState({bar:"should work too"});
	}
}
```
(this example requires `npm install @types/react`)

**Comment by flyon** [comment]
usecase 2 in the above mentioned https://github.com/Microsoft/TypeScript/issues/6218 is still relevant

**Comment by mDibyo** [comment]
FYI: Looks like this has been resolved with #12114.

**Comment by vvakame** [comment]
:eyes:

**Comment by lemonmade** [comment]
Now that mapped types/ `Partial` are a part of TS, would a PR be accepted to use it for `setState`? I don't see any other occurances of `Partial` in this repo and I'm unsure what the policy is in using new language features. I'd be happy to make the PR if it will be considered. Alternatively, does anyone know if it's possible to edit the `setState` definition (but only that definition) on a per-project basis?

**Comment by mariusschulz** [comment]
I've been wondering about the `setState` method as well. What's the policy here, @RyanCavanaugh?

**Comment by vsiao** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13155. NB: we used `Pick` instead of `Partial` because the latter doesn't play well with strict null checks.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
