### ISSUE TITLE
angular-animate.d.ts IAnimnateService Issue

### ISSUE THREAD

**Issue by HarelM** [DefinitelyTyped/DefinitelyTyped#7996]
I think the following line is no longer correct:
```js 
interface IAnimateService extends angular.IAnimateService 
```
I don't see a definition for ```IAnimateService ``` in angular namesapce, am I missing something?

**Comment by vvakame** [comment]
sorry I can't understand your pointer.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angularjs/angular-animate.d.ts#L29
I can't find `angular.IAnimateService` in angularjs/angular-animate.d.ts

**Comment by HarelM** [comment]
Please update the Nuget package then, this is the code I see when using the latest file from Nuget.

**Comment by vvakame** [comment]
@staxmanade ?

**Comment by staxmanade** [comment]
If you download the latest [nuget package](https://www.nuget.org/api/v2/package/angularjs.TypeScript.DefinitelyTyped/5.2.5) (as of this writing). rename it to a `.zip` file - unzip it, I don't see  `interface IAnimateService extends angular.IAnimateService` anywhere in the `angular-animate.d.ts` file...

@HarelM possibly check the nuget package you're downloading and that it is the latest version available on Nuget?

**Comment by HarelM** [comment]
Version 5.2.5 seems to solve the issue, I think the issue was in version 5.2.3.
