### ISSUE TITLE
angular-protractor Condition inheritance confusion

### ISSUE THREAD

**Issue by rapropos** [DefinitelyTyped/DefinitelyTyped#8001]
I must be misunderstanding something here, but I cannot see how protractor.until.Condition extends webdriver.until.Condition, despite it being declared as doing so. webdriver.until.Condition has two methods: `description` and `fn`. protractor.until.Condition, at least the ones generated by the ExpectedConditions functions, looks to me to be a function that returns a promise of a boolean. I think it would make more sense to eliminate the "extends webdriver.until.Condition" and instead put something like:

```
type Condition = () => webdriver.promise.Promise<boolean>;
```

**Comment by cnishina** [comment]
@andy-ms This should be closed since angular-protractor does not exist.
