### ISSUE TITLE
Definition request: awesomplete.js

### ISSUE THREAD

**Issue by sugarflux** [DefinitelyTyped/DefinitelyTyped#8024]
Definitions for awesomplete.js wanted - a lightweight type-ahead library.
https://leaverou.github.io/awesomplete

**Comment by webbiesdk** [comment]
I made a thing, maybe you can use it? 

https://gist.github.com/webbiesdk/fc495c33bbae30add3e1

**Comment by sugarflux** [comment]
That's great (at least a great starting point!)

Thanks muchly :)

~S~

**Comment by webbiesdk** [comment]
Why close the issue? There still isn't a declaration-file in the repository.

**Comment by sugarflux** [comment]
Good point. I'm a bit of a n00bie here - sorry!

**Comment by sugarflux** [comment]
So I just altered: 
constructor(input: HTMLElement | string, o: Object);

and

list: string | string[] | Element;

for my purposes... Would be happy to change it in your link but can't work out how...

**Comment by webbiesdk** [comment]
I just updated it, if you have further updates, just write what needs to be changed as a comment on the gist.
