### ISSUE TITLE
mongodb/mongodb.d.ts

### ISSUE THREAD

**Issue by r-ising** [DefinitelyTyped/DefinitelyTyped#8044]
hello,

i found a "bug" in mongodb.d.ts on line 240:

Please replace 
```
stats(options?: { scale?: number }): Promise<any>;;
```
to:

```
stats(options?: { scale?: number }): Promise<any>;
```

thanks

**Comment by vvakame** [comment]
please send a pull request.

**Comment by r-ising** [comment]
my old pull request #7086 is still open, should i send a next one?

**Comment by vvakame** [comment]
please make a new one. (and your old PR was merged!)

**Comment by r-ising** [comment]
ok  i created a new pull request: #8097
