### ISSUE TITLE
angular-component-router.d.ts does not compile

### ISSUE THREAD

**Issue by craigbroadman** [DefinitelyTyped/DefinitelyTyped#8054]
I have just updated angularjs.TypeScript.DefinitelyTyped in my project, but I am getting build errors because angular-component-router.d.ts does not compile - "Cannot find name 'Promise' (see screen shot).

I have temporarily resolved this by replacing "Promise<" with "IPromise<" but this doesn't seem right?

![image](https://cloud.githubusercontent.com/assets/5638263/13003963/78b5bc32-d170-11e5-9619-01d527401258.png)

**Comment by vvakame** [comment]
try with `--target es6` or https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/es6-promise/es6-promise.d.ts

**Comment by squadwuschel** [comment]
Why don't fix the issue and replace the "Promise" with "IPromise" like its used in the angular.d.ts then the problem is gone.

**Comment by Rouche** [comment]
Same thing here, had to edit locally for now.

**Comment by vvakame** [comment]
ah, i see. please send a pull request.

**Comment by squadwuschel** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8746

**Comment by vvakame** [comment]
:+1:
