### ISSUE TITLE
Valid code statement "process.stdin.isTTY" is not supported by node.d.ts

### ISSUE THREAD

**Issue by ChrisPearce** [DefinitelyTyped/DefinitelyTyped#8059]
The current node typings do not seem to support the valid code statement "process.stdin.isTTY".

Looking at the existing typings, "process.stdin" seems to be defined as type "ReadableStream", and "process.stdout" defined as type "WritableStream". This is ok for the majority of cases, but isn't correct when running inside a TTY context.

The Node JS documentation at https://nodejs.org/api/tty.html#tty_tty states that "When Node.js detects that it is being run inside a TTY context, then process.stdin will be a tty.ReadStream instance and process.stdout will be a tty.WriteStream instance.".

However, the typings seem to be assuming that the process.stdin is always of type ReadableStream and does not cater for it being a ReadStream.

The ReadStream has already been defined in the "tty" module as part of the commit #7556 "Merged
node: definition of the module tty has been changed". However, that commit does not assign the ReadStream type to the process.stdin property in the global NodeJS namespace.

**Comment by vvakame** [comment]
@chrootsu can you take a look?

**Comment by chrootsu** [comment]
Unfortunately I don't know how to fix that quickly, without global change of the node definition. Many interfaces should be moved from external modules into namespaces before that will be possible. I am going to try to fix it but later.
@ChrisPearce if it's necessary you can try to use this workaround:
```typescript
import * as tty from 'tty';
var stdin = <tty.ReadStream>process.stdin;
console.log(stdin.isTTY);
```

**Comment by guybedford** [comment]
This seems to be resolved by https://github.com/DefinitelyTyped/DefinitelyTyped/commit/915a86f88bc2aad2e1dd59e2fea5edb1603c3cd7.
