### ISSUE TITLE
Fresh clone shows modified files because repository contains crlf files

### ISSUE THREAD

**Issue by Oblosys** [DefinitelyTyped/DefinitelyTyped#8061]
When checking out a fresh clone, a number of files is marked as modified due to the new `* text=auto` setting in `.gitattributes` from pull request #7879. Any crlf files currently in the remote repository will have crlf line endings in the clone and are required to be commited to convert them to lf. It's all a bit confusing since the diff actually shows 0 differences because both repo and local versions are crlf. 

Unlike the ``core.autocrlf input``, the new setting applies to all files, not just the ones you actually modified. However, the number of files marked varies for different `core.autocrlf` values (`false`, `true`, or `input`) on cloning, which seems strange as both `false` and `input` should not convert on checkout and `core.autocrlf` should be overridden by `.gitattributes` anyway. There is even a difference between Mac and Windows for the same `core.autocrlf` value. You can make the marked files appear clean by temporarily changing `* text=auto` to `* text=none` in `.gitattributes`, followed by a `git status` and `git checkout .`

I can create a pull request to convert the current crlf files, but I have a feeling new ones may be introduced through pull requests from forks that have not been synced with upstream since #7879, so this may need to be done whenever a pull request is merged.

**Comment by chbrown** [comment]
Just hit the same issue, and I agree, the `* text=auto` seems a bit premature, considering how many modifications git shows with that change (55 in my case). Until that gets reverted, though, a workaround:

1. Run `git config core.autocrlf input` in the DefinitelyTyped repo
2. Edit `.gitattributes` and comment out the second line: `* text=auto` -> `#* text=auto`
3. You may need to reset and checkout à la [dealing-with-line-endings](https://help.github.com/articles/dealing-with-line-endings/)

And then simply don't commit your change to `.gitattributes` when submitting your PR.

**Comment by vvakame** [comment]
wow... @horiuchi #8008 ?
