### ISSUE TITLE
stripe?

### ISSUE THREAD

**Issue by jasonswearingen** [DefinitelyTyped/DefinitelyTyped#8085]
@a904guy @ejsmith @amritk  (the maintainers of ```stripe.d.ts```)

The current stripe.d.ts ( https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/stripe/stripe.d.ts )

has no relationship to the api's as defined here:   https://stripe.com/docs/api

What is the ```d.ts``` defining?  Can I replace this with definitions that conform to the current api?

**Comment by ejsmith** [comment]
It is describing their stripe.js library. The link you posted is their REST API.

**Comment by jasonswearingen** [comment]
ok, as that's main entrypoint is ```Stripe``` and the rest api is ```stripe``` I'll merge them into the same file
