### ISSUE TITLE
Incorrect options types for the gulp-istanbul in the ThresholdOptions interface

### ISSUE THREAD

**Issue by rotozoom** [DefinitelyTyped/DefinitelyTyped#8123]
Original:
        interface ThresholdOptions {
            coverageVariable?: string;
            thresholds?: { global?: Coverage|number; each?: Coverage|number };
        }
Should be:
        interface ThresholdOptions {
            coverageVariable?: string;
            thresholds?: { global?: Coverage**Options**|number; each?: Coverage**Options**|number };
        }

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by vvakame** [comment]
oops, already sent it. thanks!
