### ISSUE TITLE
[React.d.ts] React.Children.forEach(...) problem with casting of callback parameter type

### ISSUE THREAD

**Issue by drywolf** [DefinitelyTyped/DefinitelyTyped#8137]
In the callback of React.Children.forEach(...) the parameter type for the current element is `ReactChild`, which can not be casted back to a type derived from React.Component<P,S> (e.g. a custom component type `RibbonContainer` in the screenshot below).

![image](https://cloud.githubusercontent.com/assets/394294/13111195/d5c55c8a-d584-11e5-8401-ca4a7d2ada0f.png)

The compiler error says:

    Neither type 'ReactElement<any> | string | number' nor type 'RibbonContainer' is assignable to the other.
    Type 'ReactElement<any>' is not assignable to type 'RibbonContainer'.
        Property 'handleClick' is missing in type 'ReactElement<any>'.

Thanks

**Comment by vsiao** [comment]
The types are correct. `React.Children` operates on `ReactElement`s, not `React.Component` instances.

**Comment by drywolf** [comment]
@vsiao Thanks  for the reply.

Maybe I'm trying to use the wrong API for my usecase. I want to access some properties that are defined in the property interface of the "RibbonContainer" component.

But I also get an compiler error if I try to access the props directly on the given element:

        React.Children.forEach(this.props.children, (e, i) =>
        {
                e.props <--- error: 'props' does not exist on type 'ReactElement<any> | string | number'

What would be the right way to access the props of child components ?

Thanks

**Comment by vsiao** [comment]
So, the terminology is important here. In `render()`, you create elements, not components. To access the props, you'll need to cast `e` to `React.ReactElement<RibbonContainer.Props>`, probably.

**Comment by drywolf** [comment]
The more you know :laughing: ... Thanks, now I finally understand the difference between element & component, and it makes total sense. I'll have to see how I will handle this in my case.
