### ISSUE TITLE
winston.d.ts - addRewriter

### ISSUE THREAD

**Issue by r-ising** [DefinitelyTyped/DefinitelyTyped#8138]
hello,

i found a bug / problem in winston.d.ts:
the function addRewriter in LoggerInstance is removed in winston 2.x...

```
addRewriter(rewriter: MetadataRewriter): void;
```

old use:

```
logger.addRewriter(function(level, msg, meta) {
..
});
```

new use (since winston 2.x)

```
logger.rewriters.push(function(level, msg, meta) {
...
});
```

it's possible to change the winston.d.ts then it wouldn't work with winston 1.x.x.. if you want i can change it and create a pull request..

thanks

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by DABH** [comment]
@r-ising @vvakame I believe this is fixed in the current version of the winston typings, see e.g. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/winston/index.d.ts#L191 .  Can this issue go ahead and be closed then?

**Comment by r-ising** [comment]
@DABH yes thats correct, i close this issue.
