### ISSUE TITLE
Definition for componentHandler (Material-Design-Lite)

### ISSUE THREAD

**Issue by rubenspgcavalcante** [DefinitelyTyped/DefinitelyTyped#8148]
Definitions for componentHandler from Google's Material Design Lite wanted :+1: 

https://github.com/google/material-design-lite/wiki/How-the-Component-Handler-works

**Comment by Roaders** [comment]
Yes please

**Comment by bradzacher** [comment]
I have added the def in #9080

**Comment by vvakame** [comment]
👍
