### ISSUE TITLE
Policy on newest TypeScript features

### ISSUE THREAD

**Issue by RReverser** [DefinitelyTyped/DefinitelyTyped#8158]
Maybe this was answered somewhere before, but I couldn't find a policy in contribution guide on TypeScript version that we intend to support. This is especially important now, when TypeScript is rapidly evolving and adds new syntactic features that are incompatible with old versions and will break any old code.

Thank you.

**Comment by vvakame** [comment]
This repository support for latest `typescript@latest` only. It is from the point of view of the maintenance cost.
It means you can use `1.7.5` feature and can't use `1.8.0` feature now.

@borisyankov @Diullei @basarat and @DefinitelyTyped/contributors do you have any other comments?

**Comment by johnnyreilly** [comment]
I think that's generally agreed. We support TypeScript@latest.

**Comment by basarat** [comment]
> when TypeScript is rapidly evolving and adds new syntactic features that are incompatible with old versions and will break any old code

True. However if one fixes the code for the new version its mostly okay with the old version anyways. The new TypeScript is generally *stricter*. :rose:

>  but I couldn't find a policy in contribution guide on TypeScript version that we intend to support

The latest *stable* version.

**Comment by RReverser** [comment]
Okay, thank you for clarification. I'm just willing to change some definitions that I use daily from `string` to actual `'some' | 'other' | 'value'` list when appropriate, but will wait for 1.8 to become stable then.

**Comment by vvakame** [comment]
@RReverser https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8214 :+1:

**Comment by RReverser** [comment]
Woohoo :)
