### ISSUE TITLE
chai.d.ts missing key property in Include interface

### ISSUE THREAD

**Issue by alexpyzhianov** [DefinitelyTyped/DefinitelyTyped#8159]
I believe that interface `Include` should have `key` property as well as `keys`
Because this is a totally valid chain that is currently forbidden:
`expect(object).to.contain.key('something');`

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by j-oliveras** [comment]
@andy-ms Seems solved.
current: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/131650c616402fd8227098129d5fcacf9e4d15f4/types/chai/index.d.ts#L100

v2: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/131650c616402fd8227098129d5fcacf9e4d15f4/types/chai/v2/index.d.ts#L78
