### ISSUE TITLE
[Express.d.ts] IRoute doesn't account for array middlewares 

### ISSUE THREAD

**Issue by Tomino2112** [DefinitelyTyped/DefinitelyTyped#8160]
Hi,

Supplying array of middlewares throws error.

Example:

```
var middlewares = [midd1, midd2, midd3];

var router = new express.Router();

router.get("/", middlewares, (req, res) => {});
```

Error: `Argument of type '(RequestHandler | ErrorRequestHandler)[]' is not assignable to parameter of type 'RequestHandler'.`

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by Tomino2112** [comment]
I would like to, but having hard time coming up with the definition. 

Current is: 

```
interface IRouterMatcher<T> {
    (name: string|RegExp, ...handlers: RequestHandler[]): T;
}
```

But the way you express handles it is:

```
(name: string, ...hadlers: RequestHandler[]|ErrorRequestHandler[]): T;
```

And that is still not 100% correct. 

Basically after name you can have either single middleware, or array of middlewares. And this can be in any order you wish. 

So for example: 

```
let middlewares: RequestHandler[]|ErrorRequestHandler[] = [
    (req, res, next) => { next(); },
    (req, res, next) => { next(new Error()); },
    (err, req, res, next) => { next(); }
];

// This is possible way to write it
router.get('/user/:name', middlewares, (req, res) => {
    res.status(200).send('All good');
});

// This also
router.get('/user/:hobby', (req, res, next) => {
    next();
}, middlewares, (req, res) => {
    res.status(200).send('All good');
});

// And also this
router.get('/user/:hobby', (req, res, next) => {
    next();
}, middlewares, (err, req, res, next) => {
    next();
}, middlewares (req, res)=> {
    res.status(200).send('All good');
});
```

So theoretically you should say that the rest param should be either RequestHandler function, or ErrorRequestHandler function or array of either. I  dont know how to define that in TS, or if its even possible

**Comment by Tomino2112** [comment]
I have just updated typescript and error went away, but typing didn't change, so I suppose it was something on TypeScript side. Thanks
