### ISSUE TITLE
jQuery `bind` missing an overload

### ISSUE THREAD

**Issue by JD-Robbs** [DefinitelyTyped/DefinitelyTyped#8170]
Looking at this: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L1895

I think we're missing the following overload: `bind(eventType: string, events: any): JQuery;`

Simply binding `$(element).bind('someEvent', function(e) {})` is actually one of the commonest ways of using `bind()` - but not currently possible.  Unless, of course, I'm mistaken?

**Comment by mmiszy** [comment]
Why wouldn't it be possible? It's defined just a few lines below https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L1902
```typescript
bind(eventType: string, handler: (eventObject: JQueryEventObject) => any): JQuery;
```

**Comment by vvakame** [comment]
@johnnyreilly ?

**Comment by johnnyreilly** [comment]
Can't find any docs on that overload: http://api.jquery.com/bind/

**Comment by mmiszy** [comment]
Do you mean the example provided by @JD-Robbs ? `.bind('someEvent', function(e) {})` ? It's there in the docs. `.bind( eventType [, eventData ], handler )` – `eventData` is optional

**Comment by johnnyreilly** [comment]
I mean the overload `bind(eventType: string, events: any): JQuery;`. I don't see that covered in the API docs.

**Comment by johnnyreilly** [comment]
But you're right, the example quoted should work using the overload you point out.

**Comment by mmiszy** [comment]
I think the author meant to add this overload so that `events` could be a function and thus `.bind('someEvent', function(e) {})` would work. I'm sure he didn't realise the example just works because there's another overload for that.

**Comment by johnnyreilly** [comment]
Probably right. Closing.

**Comment by JD-Robbs** [comment]
Sorry, I actually just realised that the error came about due to additional parameters in the event callback, such as `$(element).bind('someEvent', function(e, additionalParam) {})`. That doesn't seem to be supported.

**Comment by mmiszy** [comment]
@JD-Robbs can you show me a real-life example where you can pass more than one argument to the jQuery `bind` callback?

**Comment by JD-Robbs** [comment]
@mmiszy When using plugins that set additional parameters pertaining to the event.  One example would be [jquery.inview](https://github.com/protonet/jquery.inview) where you can bind `$(element).on('inview', function(e, isInView) { if(isInView) console.log('The element is partially inside the viewport...'); });`.  Unless, that's not how `bind` is intended to be used.

**Comment by mmiszy** [comment]
@JD-Robbs we were discussing `bind` method, not `on`. The typing for `on` method you need is there https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L2302 Have you even seen the definitions file?
