### ISSUE TITLE
LineOptions missing in Charts.js

### ISSUE THREAD

**Issue by cagataycivici** [DefinitelyTyped/DefinitelyTyped#8188]
Please add the following to missing options to LineChartOptions;

`
    scaleShowVerticalLines?: boolean;
    scaleShowHorizontalLines?: boolean;
`

so it becomes;

`
interface LineChartOptions extends ChartOptions {
      scaleShowVerticalLines?: boolean;
      scaleShowHorizontalLines?: boolean;
   ...
`

Documentation for these two options are at;

http://www.chartjs.org/docs/#line-chart-chart-options

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by cagataycivici** [comment]
Here it is;

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8195

Thank you.

**Comment by cagataycivici** [comment]
Updated PR per your feedback;

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8201
