### ISSUE TITLE
is gapi.auth2.d.ts missing gapi.load(...)?

### ISSUE THREAD

**Issue by borysn** [DefinitelyTyped/DefinitelyTyped#8215]
I have an anuglar2 template, which has a databinding initialized by executing `gapi.auth2.getAuthInstance()...`, however, gapi.auth2 does not exist at this time.

In order to fix this, I resorted to pragmatically initializing auth2 at the top of my index page, like so...

`
var initAuth2 = function() {

          console.log('initAuth2');
          gapi.load('auth2', function() {
            gapi.auth2.init({
				client_id: 'CLIENT_ID.apps.googleusercontent.com'
			})
			.then(function() {
				auth2 = gapi.auth2.getAuthInstance();
				console.log('user is signed in: ' + auth2.isSignedIn.get());
			});
		});
	}
`

I run into a few issues here still though. One being, I am having a hard time controlling when this executes, sometimes i still hit the gapi.auth2 undefined error.

It might be better if I could use gapi.load(...) in typescript, or am I confused about how .load(...) is working?

### EDIT

I tried adding .load to the .d.ts file, and I'm starting to see it's not so simple. Even if I can use load, I still have no access to gapi.auth2 until the google platform.js async defer is complete. I run into the same issues without async defer as well.

`
declare module gapi {
    
    export function load(auth2: string, fn: any) : gapi.auth2.GoogleAuth;
    
}
`

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by flawless2011** [comment]
A few things...

First of all, I don't think you are loading gapi.auth2 properly.  You shouldn't need to load it the way you have described.  Are you using SystemJS to bootstrap Angular2?  Here is my SystemJS config on my index.html that you should try:

```javascript
    ...
    <script src="https://apis.google.com/js/platform.js"></script>

    <script>
      System.config({
        packages: {
          app: {
            format: 'register',
            defaultExtension: 'js'
          },
          'gapi.auth2': {
            format: 'cjs'
          }
        },
        map: {
          'gapi.auth2': 'https://apis.google.com/js/platform.js'
        }
      });
      System.import('app/boot')
            .then(null, console.error.bind(console));
    </script>
```

Second, I think you mean to be using gapi.client.load() which is defined in the gapi.d.ts typing file.  If you can't get around using load() try using the gapi.d.ts typing instead.

If you still have trouble, post more of your code so I can take a more in depth look at it.

**Comment by borysn** [comment]
@flawless2011 i gotcha. i didn't map gapi.auth2 to platform.js. i'll get some time to try that out tomorrow. I do mean to be using gapi.load though vs. gapi.client.load. defined i.e. [here](https://developers.google.com/identity/sign-in/web/people)  do I have a misunderstanding, as far as my contribution?

**Comment by borysn** [comment]
@flawless2011 thank you for trying to help, but that did not resolve my issue. I still run into gapi.auth2 undefined error. Even if I add gapi.load to typescript. I will try to explain my issue better.

gapi.auth2 is initialized asynchronously, so it's not always available when one of my components is initialized (login.component.ts). A property of that component is initialized via a service call (googlelogin.service.ts) which executes `gapi.auth2.getAuthInstance().isSignedIn.get()`. 

Here I get the gapi.auth2 undefined error. Even if I try to initialize gapi.auth2 in the root component, the .load does not fire until after the service call fails to at gapi.auth2 undefined. The issue seems to be that I'm unsure of how to have typescript wait for gapi.auth2 to initialize? The model is intialized before gapi.auth2 is ready.

here's what I'm trying.

**index.html**
```html
...

<script src="https://apis.google.com/js/platform.js" async defer></script>
	<script>
		System.config({
			packages: {
				'rvep': {
					format: 'register',
		            defaultExtension: 'js'
		        },

		        'gapi.auth2': {
					format: 'cjs'
				}
		   	},

		   	map: {
				'gapi.auth2': 'https://apis.google.com/js/platform.js'
			}
	     });
	     System.import('rvep/main')
	     	.then(null, console.error.bind(console));
	 </script>
```

**login.component.html**
```html
...

<div>
	<h3>RVEP</h3>
</div>
<div>
	<div id="rvepGoogleSignin"></div>
</div>
<div *ngIf="model?.isSignedIn">
	<a href="#" (click)="signOut()">Sign out</a>
</div>
<div>
	<div>is user signed in: {{model?.isSignedIn}}</div>
	<a href="#" (click)="glLoginService.isUserSignedIn()">Is Signed In?</a>
</div>
```

**rvep.component.ts (root component)**
```typescript
...

export class Rvep {
    
    ngOnInit() {
        console.log('rvep ngOnInit');
        gapi.load('auth2', function() {
            console.log('gapi.load');
            var auth2 = gapi.auth2.init({
                client_id: '514116175895-ohqig5ehcn2qb4k9ikmgj65m65bm2ipr.apps.googleusercontent.com'   
             });
                 
                if (auth2.isSignedIn.get()) {
                    auth2.signIn();
                }
                 
                console.log('is user signed in: ' + auth2.isSignedIn.get());
        });       
    }
    
}
```

**login.component.ts**
```typescript
...

export class Login {

    private oAuthUrl: string;
    
    public model: GoogleLoginModel = {isSignedIn:false};

    constructor(private glLoginService:GoogleLoginService) {}

    ngOnInit() {
        console.log('Login ngOnInit');
        this.glLoginService.emitter.subscribe((updatedModel) => {this.model = updatedModel;});
        this.glLoginService.pushState();
        this.renderSigninButton();
    }
    
    public signOut = () => {
        this.glLoginService.signOut();
    }
    
    // draw google signin button
    public renderSigninButton = () => {
       console.log("RenderSigninButton");
       gapi.signin2.render('rvepGoogleSignin', {
            'scope': 'profile email',
            'width': 220,
            'height': 50,
            'longtitle': true,
            'theme': 'dark',
            'onsuccess': this.onSuccess,
            'onfailure': this.onFailure
        });
    }
    
    // process after successful signin
    public onSuccess = (googleUser) => {
        console.log('Login onSuccess');
        this.glLoginService.logProfile(googleUser);
    }
    
    // process after signin failure
    public onFailure = (error) => {
        console.log(error);
    }
}
```

**googlelogin.service.ts**
```typescript
...

export class GoogleLoginService {
    
    // vars
    emitter: EventEmitter<GoogleLoginModel> = new EventEmitter(true);
    private model: GoogleLoginModel = {isSignedIn:false};
    
    // constructor
    constructor(private http: Http) {
        console.log('googlelogin constructor');
        this.emitter.share();
    }
    
    // push state
    public pushState = () => {
        console.log('googlelogin pushState');
        this.model.isSignedIn = this.isUserSignedIn();
        this.emitter.emit(this.model);
    }
    
    // process after successful signin
    public logProfile = (googleUser: gapi.auth2.GoogleUser) => {
        // Useful data for your client-side scripts:
        var profile = googleUser.getBasicProfile();
        console.log('ID: ' + profile.getId()); // Don't send this directly to your server!
        console.log('Name: ' + profile.getName());
        console.log('Image URL: ' + profile.getImageUrl());
        console.log('Email: ' + profile.getEmail());

        // The ID token you need to pass to your backend:
        var id_token = googleUser.getAuthResponse().id_token;
        console.log('ID Token: ' + id_token);

        this.pushState();
    }
    
    // signout of google 
    public signOut = () => {
        var auth2 = gapi.auth2.getAuthInstance();
        auth2.signOut().then(() => {
            this.pushState();
            console.log('User signed out.');
        });
    }
    
    // check if user is signed in
    public isUserSignedIn = (): boolean => {
        console.log('googlelogin isUserSignedIn');
        //this.initAuth2();
        var signedIn = gapi.auth2.getAuthInstance().isSignedIn.get();
        console.log('user is signed in: ' + signedIn);
        return signedIn;
    }

}
```

**Comment by borysn** [comment]
@flawless2011 I don't want this to turn into you fixing my code though haha, but I'm always open to correction. If this is a misunderstanding on my part, and not an issue with the typings (or the direction you'd like to take), we can go ahead and close this one up.

**Comment by flawless2011** [comment]
I don't mind helping out how I can.  I have a project you could look at to see how I'm using `gapi.auth2.d.ts` and I have not seen your undefined issue (with or without `async defer` on the Google script load).  

I think you should try using `ngAfterContentInit()` instead of `ngOnInit()` as your point of initializing `gapi.auth2`.  It is invoked later in the Component lifecycle and seems to happen after the library is loaded.

Here's a link to [my project](https://github.com/flawless2011/vaxtrax) you can see how I am using `gapi.auth2`.

Also lastly, I do think your `gapi.load()` should be put into a typing file, I just don't think it belongs in `gapi.auth2.d.ts.`  A better location in my opinion would be [gapi.d.ts](https://github.com/flawless2011/DefinitelyTyped/blob/master/gapi/gapi.d.ts) because that typing file includes the `gapi` module and I actually reference that typing file in my `gapi.auth2.d.ts` file.

**Comment by borysn** [comment]
@flawless2011 thanks, I'll make sure to check that out, but I did play around with the other component lifecycle hooks a little. I should go back and look though. 

I was also reading a few things [here](http://templecoding.com/blog/2016/02/17/async-await-with-es6-babel-and-typescript/) about async await in typescript. I think the solution may end up being some type of promise resolution with gapi.load(...). I'll have some time later tonight to get to that.

**Comment by borysn** [comment]
Here's what I've learned. `gapi.auth2.init({...}).then(() => {...})` gives a nice start for promise resolution. You can add the systemjs kick start to the then statement. Here, we have a solution that 100% of the time will load gapi.auth2 before typescript needs it.

Like so...

```html
<html>
<head>
<title>RVEP</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="google-signin-scope" content="profile email">
<meta name="google-signin-client_id"
	content="514116175895-ohqig5ehcn2qb4k9ikmgj65m65bm2ipr.apps.googleusercontent.com">
<!-- style -->
<link rel="stylesheet" type="text/css" href="/css/style.css">
<!-- gl auth -->
<script type="text/javascript">
	window.initAuth2 = function() {
		console.log('initAuth2');
		gapi.load('auth2', function() {
			gapi.auth2.init()
				.then(function() {
					auth2 = gapi.auth2.getAuthInstance();
					console.log('isSignedIn (index.html)' + auth2.isSignedIn.get());
					
					System.config({
						packages: {
							'rvep': {
								format: 'register',
					            defaultExtension: 'js'
					        }
					   	}
				     });
				     System.import('rvep/main')
				     	.then(null, console.error.bind(console));
				});
		});
	}
</script>
<script src="https://apis.google.com/js/client:platform.js?onload=initAuth2" async defer></script>
</head>
<body>
	<!-- rvep -->
	<rvep>Loading...</rvep>

	<!-- libs -->
	<script src="/js/lib/jquery.min.js"></script>
	<script src="/js/lib/es6-shim.min.js"></script>
	<script src="/js/lib/system-polyfills.js"></script>
	<script src="/js/lib/angular2-polyfills.js"></script>
	<script src="/js/lib/system.src.js"></script>
	<script src="/js/lib/Rx.js"></script>
	<script src="/js/lib/angular2.dev.js"></script>
	<script src="/js/lib/router.dev.js"></script>
	<script src="/js/lib/http.dev.js"></script>
	<script>
	</script>
</body>
</html>
```

I'm not exactly a fan of this solution, I'd rather do it completely in typescript, but I may run with this for now.

**Comment by borysn** [comment]
Some more issues I noticed with the gapi typings, as a result (may want separate issue thread?)

- gapi.auth2.init(...) may need empty parameter overload
- gapi.auth2.init(...).then(...) may be missing

**Comment by flawless2011** [comment]
> Some more issues I noticed with the gapi typings, as a result (may want separate issue thread?)

> gapi.auth2.init(...) may need empty parameter overload

I built the typing file based on Google's documentation.  It wasn't clear whether the params object could itself be optional.  If it does in fact work without params being passed in, then we can make it optional.

> gapi.auth2.init(...).then(...) may be missing

`gapi.auth2.init()` returns a `gapi.auth2.GoogleAuth` object which itself has a `then()` function.

**Comment by borysn** [comment]
@flawless2011 thanks for addressing my concerns. The original query has been resolved. You guys rock!

**Comment by linshu** [comment]
@flawless2011 I didn't find you are using gapi in your project https://github.com/flawless2011/vaxtrax. Did I look at a wrong one? Thanks!

**Comment by flawless2011** [comment]
@linshu I'm no longer using it for this project because I switched to using Firebase login.  If you go back to commit c4a686bb380fd59a793c9ccb14ddedf33ddb380d you can see it working before the switch.

**Comment by 18steps** [comment]
gapi.auth2 can now be found in @types/gapi.auth2 — however, when used together with @types/gapi, TypeScript errors that gapi has no exported member auth2.

This has something to do with them being in separate files, because when placed in the same file, there is no such error.

For now my fix is just to install both @types packages, copy and paste their content into the same file, and uninstall the packages again. Not a good solution.

**Comment by Maxim-Mazurok** [comment]
@18steps give [`@types/gapi.client`](https://www.npmjs.com/package/@types/gapi.client) a try.
It has both `gapi`, `gapi.client` and `gapi.auth` in it.
Also, it's being supported by https://github.com/Maxim-Mazurok/google-api-typings-generator which is now the best way to get Google API typings.
However, `@types/gapi.client` needs to be updated, and that's why I'm working on the [project to "un-minify" gapi source code](https://github.com/Maxim-Mazurok/gapi), in order to create extremely accurate typing. Feel free to contribute ;)
