### ISSUE TITLE
Re-split electron definitions into common, main, and render APIs

### ISSUE THREAD

**Issue by MrAndMrsK** [DefinitelyTyped/DefinitelyTyped#8227]
I propose that this change get reversed: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b10b59fe42978878f23b6bbae44c1c98a76ec492#commitcomment-16281602

"The purpose of using typescript is the strong typing and compile time errors about things that won't be valid at runtime. Combining the definitions of the main and render environments bypasses compile-time checks and allows attempts to use render-only APIs in the background scripts and background-only APIs in the foreground scripts."

**Comment by vvakame** [comment]
@jedmao @rhysd ?

**Comment by jedmao** [comment]
As long as you can ensure that @rhysd's original issue is not reintroduced, I support this change. The issue being:
> because currently github-electron-renderer.d.ts and
github-electron-main.d.ts can't be used with tsd.d.ts at the same
time.  tsd.d.ts includes both definition files.  So I unite them to
resolve it.

**Comment by MrAndMrsK** [comment]
Then I say it should be two different tsd packages, one for renders and one for main.  They really are completely separate environments.  

In that case, I wouldn't care whether the common types were concatenated into each of the two environment-specific files or if they stay separate - whichever would be easier to maintain I guess.

(I'll be absent from this discussion for about a week now, sorry)

**Comment by rhysd** [comment]
Yes, I [commented](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b10b59fe42978878f23b6bbae44c1c98a76ec492#commitcomment-16281602) but it's just an idea.  We should ensure the idea is correct.

And I wander we should only support `typings`.  I saw some `.d.ts` file managers.  Not all of them supports `browser.d.ts` and `main.d.ts`.

Separating `github-electron` package to `electron-main-process` package and `electron-renderer-process` package also looks good.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
