### ISSUE TITLE
node.d.ts EventEmitter should use `this`-typing

### ISSUE THREAD

**Issue by MrAndMrsK** [DefinitelyTyped/DefinitelyTyped#8228]
EventEmitter (and others?) should to be updated to the following for TSC 1.8, right?

```
    export interface EventEmitter {
        addListener(event: string, listener: Function): this;  // was `: EventEmitter`
        on(event: string, listener: Function): this;
        once(event: string, listener: Function): this;
        removeListener(event: string, listener: Function): this;
        removeAllListeners(event?: string): this;
        setMaxListeners(n: number): this;
        ...
```

This will more accurately preserve the return type which is always the implementing type.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by MrAndMrsK** [comment]
This is already fixed with https://github.com/DefinitelyTyped/DefinitelyTyped/blob/48c1e3c1d6baefa4f1a126f188c27c4fefd36bff/node/node.d.ts
