### ISSUE TITLE
[mongoose.d.ts] Can't use ES6 promises

### ISSUE THREAD

**Issue by sundriver** [DefinitelyTyped/DefinitelyTyped#8248]
Hi Guys,
 
I am trying to use ES6 Promises for Mongoose ODM in TypeScrpt.

I have the following line

```javascript
mongoose.Promise = Promise; // as instructed by MongooseJs docs to use ES6 futures
```

Which give me the following error:

```bash
error TS2322: Type 'PromiseConstructor' is not assignable to type 'typeof Promise'.
  Type 'Promise<any>' is not assignable to type 'Promise<any>'.
    Property 'end' is missing in type 'Promise<any>'.
```

I think this could be a bug from .d.ts file of mongoose

**Comment by vvakame** [comment]
umm... I don't have a answer. you can try `mongoose.Promise = Promise as any;`.

**Comment by Thomas-P** [comment]
Hi,
this is a problem, because Promise is not defined on the Mongoose class. Add Promise there and remove the MPromise definition at the bottom of the definition file and it will work as expected.
