### ISSUE TITLE
lodash update

### ISSUE THREAD

**Issue by lionelB** [DefinitelyTyped/DefinitelyTyped#8264]
Hello,

Since the last update of lodash.d.ts, I have some error on 
```$
.tmp/typings/lodash/lodash.d.ts(11552,44): error TS2304: Cannot find name 'Map'.
```

I can't figure how I can fix it.

**Comment by vvakame** [comment]
@chrootsu ?

simple answer, you should use `--target es6` or define `interface Map<K, V> {}` in global.

**Comment by lionelB** [comment]
thanks for the answer ! I will try it asap

**Comment by everettwolf** [comment]
@lionelB did you get it to work?

@vvakame more info?  

using gulp.  All our projects are broken due to this latest commit.

**Comment by everettwolf** [comment]
All of our front-end builds started breaking one by one. ;o) 

Switched to a different repository that has the older lodash: chbrown/DefinitelyTyped while it's sorted out. 

Had been on the borisyankov repo.

**Comment by chrootsu** [comment]
Oops, I'm sorry. Now I will separately test for ES5 too.

**Comment by everettwolf** [comment]
Thanks @chrootsu.  I've notified our team that you're on it.  The builds kick off automatically once a day, so they should go back to normal, or I'll manually run them when your pull request is merged.

**Comment by lionelB** [comment]
> @lionelB did you get it to work?
Yes we fix it using a temporary 
`interface Map<v, k> {}`
