### ISSUE TITLE
Error after adding node-uuid with typings

### ISSUE THREAD

**Issue by jpierson** [DefinitelyTyped/DefinitelyTyped#8275]
I'm trying to get a TypeScript node application running and have included node-uuid and it's typings using the _typings_ tool installing as an ambient module. 

```bash
$ typings install --ambient --save node-uuid
```

When running _tsc_ however I get the following error.

> typings/main/ambient/node-uuid/node-uuid.d.ts(21,22): error TS2304: Cannot find name 'UUIDOptions'.

Looking at the typings file _node-uuid.d.ts_ it appears to me that the _UUIDOptions_ isn't defined anywhere. Am I missing something or is this type definition file incomplete?

**Comment by jpierson** [comment]
Ok, digging a little more through the type definition I found [ode-uuid-base.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node-uuid/node-uuid-base.d.ts) which appears to have the _UUIDOptions_ interface defined. Trying randomly I found that running the following command in addition to the original one to add typings for node-uuid seems to have at least worked around the problem.

```
typings install --ambient --save node-uuid-base
```

Is this the expected experience? Am I doing something wrong? Is this an issue with [typings](https://github.com/typings/typings)?

**Comment by vvakame** [comment]
I think this issue is typings problems.

**Comment by tengyifei** [comment]
Right now `typings install --ambient --save node-uuid-base` does not work and
```
typings install --global --save node-uuid-base
```
cannot find the `node-uuid-base` repository. Maybe we can reopen the project?

**Comment by Xab01** [comment]
typings install dt~node-uuid  --global --save   ==> install  typings/globals/node-uuid/index.d.ts
typings install --global --save dt~node-uuid-base --> Give the error:
```

typings ERR! message Unable to find "node-uuid-base" ("dt") in the registry. Did you want to try searching another source? Also, if you want contribute these typings, please help us: https://github.com/typings/registry
typings ERR! caused by https://api.typings.org/entries/dt/node-uuid-base/versions/latest responded with 404, expected it to equal 200
```

**Comment by Xab01** [comment]
I found the issue: 

C:\Users\admin\Documents\expense>typings search node-uuid
Viewing 5 of 5

NAME                       SOURCE HOMEPAGE                                DESCRIPTION VERSIONS UPDATED
node-uuid                  npm    https://www.npmjs.com/package/node-uuid             2        2016-05-03T01:31:24.000Z
node-uuid                  dt     https://github.com/broofa/node-uuid                 1        2016-03-16T15:55:26.000Z
node-uuid/node-uuid-base   dt     https://github.com/broofa/node-uuid                 1        2016-03-16T15:55:26.000Z
node-uuid/node-uuid-cjs    dt     https://github.com/broofa/node-uuid                 1        2016-03-16T15:55:26.000Z
node-uuid/node-uuid-global dt     https://github.com/broofa/node-uuid                 1        2016-03-16T15:55:26.000Z


`typings install dt~node-uuid/node-uuid-base --global --save`
