### ISSUE TITLE
react-redux: `connect` typings seem to be too strict

### ISSUE THREAD

**Issue by seansfkelley** [DefinitelyTyped/DefinitelyTyped#8285]
Regarding the typings of `connect` (abbreviated here for reference):

```
class ElementClass extends Component<any, any> { }
interface ClassDecorator {
  <T extends (typeof ElementClass)>(component: T): T
}

function connect(...): ClassDecorator;
```

Calling `connect` on a `Component<P, S>` seems to return the same `Component<P, S>` even though the typings seem to specify it should be `Component<any, any>`. This causes compilation to fail, when I do something of the form:

```
<Provider store={...}>
  <ThingWithProps/>
</Provider>
```

Where `ThingWithProps` has non-optional props, but is `connect`ed and so of course will properly receive the props from `Provider`. I've created [an example repo](https://github.com/seansfkelley/react-redux-typings-bug) to illustrate.

Changing the typings like so:

```
export interface ClassDecorator {
  <T extends (typeof ElementClass)>(component: T): typeof ElementClass
}
```

allows the code to compile just fine, and it works fine at runtime too. Given that the props of the returned wrapped class are not the same as those of the class that was wrapped (in that the former's are "optional" since they will be supplied by `Provider`), it seems like a mistake to specify the same type on both sides of this function. But of course, if you have props that must be passed through from the parent component and not the `Provider`, you lose the typings for that prop in the above "fix".

I think I must be misunderstanding this, because it appears unusable in the current state.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by seansfkelley** [comment]
Sorry; I wasn't clear that this was supposed to be a question. The typings were changed be this strict months ago in #6357 (specifically, [line 14](https://github.com/tkqubo/DefinitelyTyped/commit/a513c4df6eb8505da8eef432891c8b69b73535d9#diff-4d61af625c8f5658f7e8d4468e98e4e4L14)), so just undoing it seems wrong, especially since the "fix" I proposed is basically exempting the wrapped component from any typechecking of its props. I don't know Typescript well enough to know if there's a good compromise here or if I'm doing something wrong in my own class definitions (but I suspect not). Perhaps the original author of that line @tkqubo may have some input?

**Comment by tkqubo** [comment]
@seansfkelley Oh sorry I updated `react-redux` definition more than a week ago but forgot to make a PR #8323.  I hope this will help solve your issue

**Comment by tkqubo** [comment]
Sorry again my pr doesn't seem to solve the issue.   Anyway in you example, `dummy` is meant to be a value injected by redux so we don't want to write like this `<ThingWithProps dummy={...} />`, right?

`ClassDecorator` definition you proposed will work well for you example

```ts
export interface ClassDecorator {
  <T extends (typeof ElementClass)>(component: T): typeof ElementClass
}
```

but using this definition, `connect`ed `ThingWithProps` then accepts any kind of props without compilation error (and the situation is maybe the same in my new react-redux pr)

```ts
<Provider store={store}>
  <ThingWithProps foo={3} bar={"baz"} />
</Provider>
```

I think making `dummy` prop optional can work as a workaround.

**Comment by seansfkelley** [comment]
Yeah, that's exactly what I was trying to demonstrate with the example. Thanks for checking it out; unfortunate that we have to sort-of lie about the typings (since they aren't optional, just injected by react-redux), but that seems like the best solution.
