### ISSUE TITLE
[lodash.d.ts] _.isMap Problem

### ISSUE THREAD

**Issue by RobertSandu** [DefinitelyTyped/DefinitelyTyped#8295]
Hi

//_.isMap
    //interface LoDashStatic {
    //    /**
    //     * Checks if value is classified as a Map object.
    //     *
    //     * @param value The value to check.
    //     * @returns Returns true if value is correctly classified, else false.
    //     */
    //    isMap<K, V>(value?: any): value is Map<K, V>;
    //}

Build: Cannot find name 'Map'.

**Comment by keepitreal** [comment]
`typings/lodash/lodash.d.ts(11552,44): error TS2304: Cannot find name 'Map'.`

Getting this as well.

**Comment by chrootsu** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/8264#issuecomment-189247585 this comment contains a workaround.

**Comment by vvakame** [comment]
by #8274
