### ISSUE TITLE
angular.d.ts Need properties for ng-model-options

### ISSUE THREAD

**Issue by ashwin027** [DefinitelyTyped/DefinitelyTyped#8328]
Hello!

I'm trying to set ng-model options conditionally from the controller but I'm unable to find properties for it.

Here is the page on the angular website that talks about this: https://docs.angularjs.org/api/ng/directive/ngModelOptions

I would submit a PR for this but I'm not quite sure of all the locations that it is used in. 
I would think that this is what the interface might look like

    interface INgModelOptions {
        updateOn?: string;
        debounce?: any;
        allowInvalid?: boolean;
        getterSetter?: boolean;
        timezone?: string;
    }

Please let me know if I can go ahead and submit a pull request to get just this interface added.

**Comment by vvakame** [comment]
please send a pull request. We'll review it.

**Comment by ashwin027** [comment]
#8428

**Comment by vvakame** [comment]
:+1:
