### ISSUE TITLE
material-ui definition does not work well with commonjs mode

### ISSUE THREAD

**Issue by pawsong** [DefinitelyTyped/DefinitelyTyped#8333]
My build settings:
- compilerOptions.module: "commonjs" in tsconfig.json
- typescript -> babel -> webpack

I use `commonjs` mode because typescript and babel have different interop rule and have a problem with latest definition file. For example,

``` typescript
declare module 'material-ui/lib/avatar' {
    export import Avatar = __MaterialUI.Avatar;
    export default Avatar;
}
```

supports following typescript imports: 

``` typescript
import { Avatar } from 'material-ui/lib/avatar';
// or
import Avatar from 'material-ui/lib/avatar';
```

but both do not work well with webpack. The exporting part of `material-ui/lib/avatar.js`

``` javascript
exports.default = Avatar;
module.exports = exports['default'];
```

looks like exporting default value but doesn't because the default exporting by the first line of above code is overwritten by the second line.

My current workaround is using older version of definition file. Is there any other suggestion?

**Comment by ngbrown** [comment]
@pawsong material-ui went to ES6 style exports, and that's what the definitions are around.  What version of TypeScript are you using? What version of material-ui are you trying to use?

**Comment by pawsong** [comment]
@ngbrown
 
Versions:
- TypeScript: 1.8.7
- material-ui: 0.14.4

I made a simple bug reproducing repo: https://github.com/pawsong/dt-material-ui-issue. Is there any wrong configuration?

**Comment by ngbrown** [comment]
@pawsong You mentioned you used Babel, but I don't see `babel` in your example.  No version of Node supports ES6 modules yet, and everyone has to run it through Babel, even for the tests.

Also, in my `tsconfig.json`, I have:

```
{
  "compilerOptions": {
    "module": "es6",
  },
}
```

**Comment by pawsong** [comment]
@ngbrown I intentionally did not include Babel in [dt-material-ui-issue](https://github.com/pawsong/dt-material-ui-issue) to make it clear that TypeScript with `"module": "commonjs"` is incompatible with the current definition in DT.

I do not use `"module": "es6"` option for some reasons:
- It does not support import assignment(which is unavoidable in case using some old DT definitions).
- Babel and TypeScript have different interop rules, especially handling default export, which makes problems when using non-es6 modules.
```typescript
import express from 'express' // Babel
import * as express from 'express' // TypeScript
```

Using `"module": "es6"` seems to fix this issue by forcing Babel interop rules, but it costs a lot :( By the way, thank you for your help!

**Comment by ngbrown** [comment]
Ok.

In `material-ui.d.ts` there is:

```ts
declare module 'material-ui/lib/avatar' {
    export import Avatar = __MaterialUI.Avatar;
    export default Avatar;
}
```

in `node_modules/material-ui/lib/avatar.js`:
```js
exports.default = Avatar;
module.exports = exports['default'];
```

So, I did a quick experiment, and here are three different outputs in `app.js`, with `"module": "commonjs"`:

doesn't work (note the access to `default`):

```js
"use strict";
const assert = require('assert');
// TS: import Avatar from 'material-ui/lib/avatar';
const avatar_1 = require('material-ui/lib/avatar');
assert(avatar_1.default !== undefined);
```


works:

```js
"use strict";
const assert = require('assert');
// TS: import * as Avatar from 'material-ui/lib/avatar';
const Avatar = require('material-ui/lib/avatar');
assert(Avatar !== undefined);
```


works:

```js
"use strict";
const assert = require('assert');
// TS: import Avatar = require('material-ui/lib/avatar');
const Avatar = require('material-ui/lib/avatar');
assert(Avatar !== undefined);
```

I don't know enough about what is going on behind the scenes with JavaScript modules to know where this is going in the future.  I do know I have had to try various things until something works...

Do you have any suggestions?

**Comment by pawsong** [comment]
IMHO the source of problem is that material-ui uses [add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports) which disables `exports.default`. I will post a issue on material-ui not to use it, but it is breaking changing for plain node.js projects so it doesn't seem to be easily accepted...

Actually, my opinion is as long as material-ui exports modules in CommonJS style with [add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports), ts declare files should use export assignment, which is closer to CommonJS than default export.

```typescript
declare module 'material-ui/lib/avatar' {
  import Avatar = __MaterialUI.Avatar;
  export = Avatar;
}
```

**Comment by ngbrown** [comment]
@pawsong It looks like you got traction on the material-ui side...

I thought about this, and I wouldn't want to change back to `export = Avatar` because I want the imports in TypeScript to match the documentation, especially with so many modules to bring in.

With the current export to default, TypeScript outputting ES6 modules, and the Babel; this is possible.

**Comment by pawsong** [comment]
@ngbrown I agree with you. If there are not many cases using `"module": "commonjs"`, just waiting for material-ui's update (0.15.x release) can be a reasonable choice. This is my current workaround:
```typescript
import _Avatar from 'material-ui/lib/avatar';
const Avatar = require('material/lib/avatar') as _Avatar;
```
By the way, thank you for your help again!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
