### ISSUE TITLE
Definition Request: Forge

### ISSUE THREAD

**Issue by mateusdemboski** [DefinitelyTyped/DefinitelyTyped#8360]
A native implementation of TLS in Javascript and tools to write crypto-based and network-heavy webapps. https://github.com/digitalbazaar/forge

**Comment by VitorBarbosa** [comment]
+1

**Comment by paralin** [comment]
So DefinitelyTyped seems right now to have a limited definitions file for this. It's missing a lot of stuff.

**Comment by mtycholaz** [comment]
+1

**Comment by andreyjkee** [comment]
+1

**Comment by Prior99** [comment]
+1

**Comment by chax** [comment]
+1

**Comment by yavin5** [comment]
+1

**Comment by johnnyzh82** [comment]
+1
