### ISSUE TITLE
Angular Resource Type.d,  typescript does not recognize a custom action on the angular $resource

### ISSUE THREAD

**Issue by kmassada** [DefinitelyTyped/DefinitelyTyped#8365]
- I want to talk about `angularjs/angular-resource.d.ts`.
  - The authors of that type definition are cc/ @miffels @diegovilar

I'm using this code to define a new method on my resource, 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angularjs/angular-resource.d.ts#L45-L48 

```typescript 
module app.common {
    interface IVenueService{

    }
    export interface IVenueResource extends ng.resource.IResourceClass<app.domain.IVenue>{
      update(IVenue: app.domain.IVenue) : app.domain.IVenue;
    }

    export class VenueService implements IVenueService{
      static $inject = ["$resource", "url"];
      constructor(private $resource: ng.resource.IResourceService, private url: URL_CONSTANTS){
      }

    getVenueResource(): ng.resource.IResourceClass<ng.resource.IResource<IVenueResource>>{
      // Define custom action as IActionDescriptor
      var updateAction : ng.resource.IActionDescriptor = {
          method: 'PUT',
          isArray: false
      };
      return <ng.resource.IResourceClass<ng.resource.IResource<IVenueResource>>>
      this.$resource(this.url.BASE_API+"/v1/venues/:id", {id: '@id'} ,{
        update: updateAction
      });
    }
  }
  angular
    .module("common.services")
    .service("venueService", VenueService);
}
```

when I want to use this resource's update method, I can't call on it directly, 

[http://i.stack.imgur.com/aKLBt.png](image)
```
module app.Venue {

  interface INavigationScope{
        venueResource: ng.resource.IResourceClass<ng.resource.IResource<app.common.IVenueResource>>;
  }

  class VenueListCtrl implements INavigationScope {
        venueResource: ng.resource.IResourceClass<ng.resource.IResource<app.common.IVenueResource>>;
  }
  sample(){
    var updatedVenue =this.venueResource.update({id: 1, name: 'Amphitheather'},
       ()=> {});
  }
}
```

I've already asked at [http://stackoverflow.com/questions/35687506/how-to-get-typescript-to-recognize-a-custom-action-on-the-angular-resource](s/o) and at that time, I was using a different variation. 

Soon realized that from this reference https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angularjs/angular-resource.d.ts#L85 

I should be using `IResourceClass<T>` to extend my interface, which I did. 

But which in return made the instance of the class return `IResourceClass<IResource<T>>`
neither still see .update as a method

**Comment by miffels** [comment]
Hi,

You'll need to use the right interfaces in your declarations:

```
interface INavigationScope{ venueResource: app.common.IVenueResource; }
```

Also, please make sure not to confuse resources and resource classes. I would recommend you to rename `IVenueResource` to `IVenueResourceClass` in order to avoid confusion. 

Best,
Michael

**Comment by kmassada** [comment]
Returning an instance of `IVenueResourceClass` which is a child of `ng.resource.IResourceClass<ng.resource.IResource<app.domain.IVenue>>` but with the update() method did the trick. 

Thanks so much @miffels
