### ISSUE TITLE
Incorrectly named property customerTreeAggregationFn in ui-grid typings file

### ISSUE THREAD

**Issue by Choc13** [DefinitelyTyped/DefinitelyTyped#8368]
The current master version of the [ui-grid/ui-grid.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/ui-grid/ui-grid.d.ts) seems to have an incorrect property on the definition of `treebase.IColumnDef<TEntity>`. At present it has a property named `customerTreeAggregationFn`, but I believe this should be `customTreeAggregationFn` as per the [UI-Grid docs](http://ui-grid.info/docs/#/api/ui.grid.treeBase.api:ColumnDef)

**Comment by vvakame** [comment]
please send a pull request. We'll review it.

**Comment by vvakame** [comment]
:+1:
