### ISSUE TITLE
gapi.youtube - "Cannot find name 'HttpRequest' "

### ISSUE THREAD

**Issue by orizens** [DefinitelyTyped/DefinitelyTyped#8378]
- [x] I tried using the latest [`gapi.youtube/gapi.youtube.d.ts.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/gapi.youtube/gapi.youtube.d.ts) file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

I'm getting this error (lots of it) when using typings with tsd checks:
```error TS2304: Cannot find name 'HttpRequest'.```

Thanks.

**Comment by vvakame** [comment]
@sgtfrankieboy ?

**Comment by sgtfrankieboy** [comment]
Make sure you also include the latest version of [`gapi/gapi.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/gapi/gapi.d.ts) as it defines `HttpRequest`.

**Comment by orizens** [comment]
@sgtfrankieboy Thanks - that sovles it.
