### ISSUE TITLE
d3.d.js : missing Force tick()

### ISSUE THREAD

**Issue by gjuchault** [DefinitelyTyped/DefinitelyTyped#8383]
- [x] I tried using the latest `d3/d3.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

The `Force` interface (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/d3/d3.d.ts#L2881) is missing the `tick()` function https://github.com/mbostock/d3/wiki/Force-Layout#tick

Thanks

**Comment by vvakame** [comment]
please send a pull request.

**Comment by tomwanzek** [comment]
As part of some legacy D3v3 issue clean-up, can this issue be please closed?

D3v4 has been released and supported with actively maintained definitions for several months now, so it would be great to have only current issues open for clarity.

Thanks in advance!

cc @gustavderdrache @andy-ms
