### ISSUE TITLE
AngularJS Mocks: missing definition for $componentController

### ISSUE THREAD

**Issue by mmmichl** [DefinitelyTyped/DefinitelyTyped#8385]
Angular 1.5 introduced `ngMock.$componentController`, which is currently completely missing.

docs: https://docs.angularjs.org/api/ngMock/service/$componentController

**Comment by vvakame** [comment]
please send a pull request.

**Comment by FreakenK** [comment]
Just created a PR for this

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8676
