### ISSUE TITLE
Sequelize: UpsertOptions is incomplete

### ISSUE THREAD

**Issue by konrad-garus** [DefinitelyTyped/DefinitelyTyped#8386]
`UpsertOptions` looks like:

```
interface UpsertOptions {
    validate? : boolean;
    fields? : string[];
    logging? : boolean | Function;
}
```

However, this operation accepts many more options: http://docs.sequelizejs.com/en/latest/api/model/#upsertvalues-options-promisecreated.

How about the following mapping:

```
interface UpsertOptions {
    validate? : boolean;
    fields? : string[];
    logging? : boolean | Function;
    transaction? : Transaction;
    searchPath? : string;
    benchmark? : boolean;
}
```

I can work on a PR later if this sounds like a good idea.

**Comment by vvakame** [comment]
please send a pull request. We'll review it.

**Comment by mattbishop** [comment]
Is this issue now closed @konrad-garus?
