### ISSUE TITLE
Cannot find namespace 'moment'

### ISSUE THREAD

**Issue by Sireini** [DefinitelyTyped/DefinitelyTyped#8388]
Hi everybody,

Iam new in using Typescript and angular. First of all i want to use moment.js and jquery i made a reference path in my bootstrap.v3.datetimepicker.d.ts and in my personal ts file. Linked to jquery and moment, and included the node_module scripts in the index.html. But it keeps giving me the error in my terminal that 'moment' namespace cannot be found. I think i am missing something but i do not know what...

Thanks in advance everybody

**Comment by karelwgonzalez** [comment]
I was having the same problem, and no amount of typings install moment was fixing the issue, regardless of the options I threw at it.

My solution was to manually grab a copy of `moment-node.d.ts` and place it in my `browser/ambient/moment` and `main/ambient/moment` directories so that `moment.d.ts` could get the definitions it needs.

**Comment by falconmick** [comment]
having the same issue... Really don't want to resort to hacky fixes

**Comment by leodsgn** [comment]
Same issue here. Thanks for the tip, @karelwgonzalez. I'll try it.

**Comment by rockResolve** [comment]
I'm using aurelia (jspm & system.js) with typescript.
I found adding an explicit import to my bootstrap.v3.datetimepicker.d.ts resolved the moment reference

    import * as moment from 'moment';

**Comment by karelwgonzalez** [comment]
Figured out a better solution that is similar, but not a manual import of the file.

Duplicate the `moment.d.ts` line from your `typings.json` and change the instances of `moment` to `moment-node`.

e.g.

```json
{
  "ambientDependencies": {
    "moment": "github:DefinitelyTyped/DefinitelyTyped/moment/moment.d.ts#56295f5058cac7ae458540423c50ac2dcf9fc711",
    "moment-node": "github:DefinitelyTyped/DefinitelyTyped/moment/moment-node.d.ts#56295f5058cac7ae458540423c50ac2dcf9fc711"
  }
}
```

Then run your typings installer again, and the error should go away.

**Comment by dachibro** [comment]
@karelwgonzalez Thank you for your solution.  It didn't work for me (maybe I did it wrong), but lead me to a solution that I could use.

`typings install --save --ambient moment moment-node`.

**Comment by karelwgonzalez** [comment]
@dachibro Weird.

If it was the last line in your json, did you remove the trailing comma? Either way, glad you got it working. 

I tried installing `moment-node` like that and I kept getting a not found error.

**Comment by dachibro** [comment]
@karelwgonzalez It's possible we are using different versions of typings, because my `typings.json` URLs look a lot different than yours:

```
"ambientDependencies": {
    "jasmine": "registry:dt/jasmine#2.2.0+20160317120654",
    "moment": "registry:dt/moment#2.8.0+20160316155526",
    "moment-node": "registry:dt/moment-node#2.11.1+20160329220348",
    "node": "registry:dt/node#4.0.0+20160330064709",
    "require": "registry:dt/require#2.1.20+20160316155526"
  }
```

I am using 0.7.12.

**Comment by karelwgonzalez** [comment]
@dachibro That's, probably exactly it. I'm still on 0.6.8 for my project.

**Comment by rockResolve** [comment]
Beware version problems too
`typings install bootstrap.v3.datetimepicker` uses bootstrap.v3.datetimepicker/bootstrap.v3.datetimepicker-3.0.0.d.ts


To get the latest version (4.17.37) use
`typings install "github:DefinitelyTyped/DefinitelyTyped/bootstrap.v3.datetimepicker/bootstrap.v3.datetimepicker.d.ts" `

**Comment by Rouche** [comment]
moment.d.ts version 2.13.0, same issue.

/// <reference path="../../../moment/moment.d.ts" />
private moment:  moment.Moment = require("moment/moment");

Cannot find namespace 'moment'

Have to backtrack to old version.

**Comment by luisrudge** [comment]
It's not work for me too :(

**Comment by luisrudge** [comment]
Installing both moment and moment-node works though...
`typings i -S moment moment-node --ambient`

**Comment by xuyang2** [comment]
typings install --save --global dt~moment dt~moment-node

**Comment by Rouche** [comment]
moment 2.13.0 now ships with its own .d.ts . But doesn't work as an amd unfortunatelly.

**Comment by vance** [comment]
I installed as a --global and it appears correctly in `typings/globals/index.d.ts` but the generated file is empty except for declaring moment. I do see that in my bower components, moment directory does include the typescript definition, but the two aren't linked for the compiler.

**Comment by shamoh19** [comment]
how integrate moment with Angular2?  Facinf similar kinda error

**Cannot find namespace 'moment'.**

**Comment by brianrt** [comment]
@shamoh19 You need to install the **@types/moment** module along with the **momentjs** module.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
