### ISSUE TITLE
Definition Request: Parse

### ISSUE THREAD

**Issue by zhouhao27** [DefinitelyTyped/DefinitelyTyped#8420]
Any typed definition for JavaScript SDK of Parse.com?

http://www.parsecdn.com/js/parse-latest.js

Are there any guideline to create the typescript definition file?

**Comment by zhouhao27** [comment]
Found one: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/parse/parse.d.ts
But this is too old.

**Comment by lifeisfunny** [comment]
+1

**Comment by dpoetzsch** [comment]
What exactly are you missing? I've been using this def for our medium-sized project and it works quite well.

Now that we are migrating to a self-hosted parse server I am missing the session token options for db requests but I'm going add those within the next days.

**Comment by estradanic** [comment]
This is wildly out of date
