### ISSUE TITLE
Lodash missing `cloneDeep` when using `chain`

### ISSUE THREAD

**Issue by kruncher** [DefinitelyTyped/DefinitelyTyped#8425]
- [x] I tried using the latest `lodash/lodash.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `lodash/lodash.d.ts`.
  - The authors of that type definition are cc/ @bczengel and @chrootsu 

Usage Example:
```typescript
let props = _.chain(xyz)
  .cloneDeep()
  .assign(props)
  .value();
```

**Comment by chrootsu** [comment]
@kruncher, thanks for bug report. Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8437.
What a question do you have?

**Comment by kruncher** [comment]
@chrootsu awesome thanks for the fast fix!!

Sorry, I didn't have a question; I was just a tad overzealous with the checkbox ticking ^_^

Thanks again!

**Comment by chrootsu** [comment]
No problem! ^_^

**Comment by kruncher** [comment]
@chrootsu It seems like your commit was merged into DefinitelyTyped although after having updated to the latest `lodash.d.ts` but I still seem to be getting the same type error:
```
error TS2339: Property 'cloneDeep' does not exist on type 'LoDashExplicitObjectWrapper<Foo>'.
```

If I manually replace the latest `lodash.d.ts` with the latest `lodash-3.10.d.ts` then it seems to detect `cloneDeep` perfectly fine.

Should this change be working with both of these definition files?

Many thanks!

**Comment by kruncher** [comment]
Awesome, thanks; seems to work perfectly :)

**Comment by chrootsu** [comment]
This PR has errors in the definition of lodash-3.10. In two cases (`_([1, 2, 3]).clone()` and `_([1, 2, 3]).deepClone()`) result type will be inferred as `number` instead of `numer[]`. A fix already exists (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8483) but isn't merged yet. Please be careful.
