### ISSUE TITLE
Type definition for moment.tz.guess() is incorrect

### ISSUE THREAD

**Issue by gerad** [DefinitelyTyped/DefinitelyTyped#8461]
`moment.tz.guess()` returns a string, but it is typed as `MomentZone` in `moment-timezone/moment-timezone.d.ts`

Here's the [code in `moment-timezone`](https://github.com/moment/moment-timezone/blob/develop/moment-timezone.js#L353) (note how it returns `zone.name`):

```js
return zoneScores.length > 0 ? zoneScores[0].zone.name : undefined;
```

Here's the [code in `moment-timezone/moment-timezone.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/moment-timezone/moment-timezone.d.ts#L73) (note it's expecting a zone):

```ts
guess(): MomentZone;
``` 

--

- [x] I tried using the latest `moment-timezone/moment-timezone.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - well, i'm using `typings`
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `moment-timezone/moment-timezone.d.ts`.
  - The authors of that type definition are cc/ @michelsalib, @jiaweihli, @gayansolid, @sammyhk, @sclausen

**Comment by vvakame** [comment]
please send a pull request.

**Comment by sclausen** [comment]
I made a pull-request DefinitelyTyped/DefinitelyTyped/pull/8502

**Comment by vvakame** [comment]
:+1:
