### ISSUE TITLE
React-router typings don't include useRouterHistory

### ISSUE THREAD

**Issue by joyt** [DefinitelyTyped/DefinitelyTyped#8508]
The react-router.d.ts file doesn't export [useRouterHistory](https://github.com/reactjs/react-router/blob/v2.0.0/docs/API.md#userouterhistorycreatehistory), even though it is part of the 2.0 API

**Comment by vvakame** [comment]
please send a pull request.

**Comment by GiedriusGrabauskas** [comment]
Merged in: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8449

**Comment by GiedriusGrabauskas** [comment]
Pull request merged: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8449
