### ISSUE TITLE
Cordova-Ionic: error TS2503: Cannot find namespace 'Ionic'.

### ISSUE THREAD

**Issue by kussberg** [DefinitelyTyped/DefinitelyTyped#8518]
Trying to setup Ionic with TS, but get following error:
`
typings/main/ambient/cordova-ionic/index.d.ts(10,12): error TS2503: Cannot find namespace 'Ionic'.
`
Typings.json looks following:
`
{
  "ambientDependencies": {
    "angular": "registry:dt/angular#1.5.0+20160310153852",
    "cordova": "registry:dt/cordova#0.0.0+20151102150547",
    "cordova-ionic": "registry:dt/cordova-ionic#0.0.0+20150401124604",
    "ionic": "registry:dt/ionic#0.0.0+20160119153736",
    "jquery": "registry:dt/jquery#1.10.0+20160303223636"
  }
}
`

@hendrikmaus

**Comment by hendrikmaus** [comment]
Hmm, nothing strikes me off the top of my head as Ionic is declared in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/cordova-ionic/plugins/keyboard.d.ts

Let me have a look if I can find something when I am back at the office.

**Comment by ekussberg** [comment]
@hendrikmaus here is the link to the project: 
https://github.com/ekussberg/tutorial1

**Comment by hendrikmaus** [comment]
At a glance, I can see that the file declaring Ionic was not pulled into the typings. That explains why it complains. Let me try and see why the typings are being pulled to an incomplete state.

**Comment by justnick21** [comment]
For anyone else hitting this, you need to install anything inside ambient modules manually eg. `typings install cordova-ionic/plugins/keyboard --ambient --save`. A drawback of using typing's it would seem!

**Comment by hendrikmaus** [comment]
@ekussberg I guess your query can be considered closed then

**Comment by rinogo** [comment]
Note that the updated command referenced by @justnick21 is `typings install dt~cordova-ionic/plugins/keyboard --global --save`

**Comment by Narretz** [comment]
Can someone explain why this is necessary and why typescript throws this uninformative error?

**Comment by raxim1** [comment]
Why? Why? Why i need to hack every time, when i'm trying to upgrade or build, it's a contraproductive mess of angular.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
