### ISSUE TITLE
As of today, installation attempts using https://api.typings.org/ are returning 404

### ISSUE THREAD

**Issue by avigold** [DefinitelyTyped/DefinitelyTyped#8701]
As of today, all installation attempts via typings are currently failing. I am using typings 0.7.9. 

For example:

```typings ERR! caused by https://api.typings.org/entries/npm/cryptojs/versions/latest responded with 404, expected it to equal 200```

Indeed, navigating in a browser to ``https://api.typings.org/entries/npm/cryptojs/versions/latest`` gives a 404.

Reproduction steps: attempt to install a package.
Frequency: always
Severity: high

**Comment by vvakame** [comment]
please report to typings.
