### ISSUE TITLE
Definitions reuest for QuaggaJS

### ISSUE THREAD

**Issue by MichaelSL** [DefinitelyTyped/DefinitelyTyped#8707]
Hi. Is it possible to add a definitions for [QuaggaJS](https://github.com/serratus/quaggaJS) barcodes decoding library?

**Comment by MichaelSL** [comment]
It seems that the library author made a [typings](https://github.com/serratus/quaggaJS/blob/master/type-definitions/quagga.d.ts)

**Comment by obedm503** [comment]
any reason why this is still open?
