### ISSUE TITLE
lodash _.flatMap uses any, and doesn't work when used in a chain

### ISSUE THREAD

**Issue by bcherny** [DefinitelyTyped/DefinitelyTyped#8713]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @vvakame @chrootsu 

```ts
_([]).flatMap(_ => _) // Property 'flatMap' does not exist on type...

_.flatMap([1,2], _ => _) // _ is "any", should be "number"
```

**Comment by chrootsu** [comment]
Thanks for the bug report. Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8717 .

**Comment by bcherny** [comment]
Thanks for the quick response!
