### ISSUE TITLE
Error	TS1110	Build: Type expected

### ISSUE THREAD

**Issue by cdebdeep** [DefinitelyTyped/DefinitelyTyped#8769]
I have downloaded the latest typescript compiler , but i am getting error when when i tries to build my Server.ts file. 
i am getting error from node.d.ts
**Error TS1110  Build: Type expected.**

My tsd.json file look like the following 
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "express/express.d.ts": {
      "commit": "4bd9b47f0ea79ba83c2e831c56bcaf8ba3a2c8ad"
    },
    "serve-static/serve-static.d.ts": {
      "commit": "4bd9b47f0ea79ba83c2e831c56bcaf8ba3a2c8ad"
    },
    "mime/mime.d.ts": {
      "commit": "4bd9b47f0ea79ba83c2e831c56bcaf8ba3a2c8ad"
    },
    "express-serve-static-core/express-serve-static-core.d.ts": {
      "commit": "4bd9b47f0ea79ba83c2e831c56bcaf8ba3a2c8ad"
    },
    "node/node.d.ts": {
      "commit": "4bd9b47f0ea79ba83c2e831c56bcaf8ba3a2c8ad"  
    }
  }
}

**Comment by vvakame** [comment]
replace `"repo": "borisyankov/DefinitelyTyped",` to `"repo": "DefinitelyTyped/DefinitelyTyped",` first.

**Comment by cdebdeep** [comment]
Hi,
I did the same but the error is the same.
And one more point to add is that i am building my  application in Visual Studio code , and the 
"repo": "borisyankov/DefinitelyTyped" is create by VS code itself.
Please help.

**Comment by cdebdeep** [comment]
Still no answer for me ! Please help.

**Comment by mikovenan** [comment]
I had a similar problem, due to my typescript installation being out of date.
Can you check what tsc version you have installed?

Running `tsc --version` in a terminal window should show you the version

**Comment by sferg-msft** [comment]
I have the same thing, it has to be user error somehow but I'm not sure what.

**Comment by cdebdeep** [comment]
My tsc version is
Version 1.0.3.0
still getting the same error

now i find one work around,

my app.ts file code is

///<reference path="../../typings/main.d.ts" />
module AngularJsDemo.Scripts{
    var app = angular.module('app',[]);
    app.filter('LimitToChar',function () {
        return function (InputValue:string,MaxCharCount:number) {
            return (InputValue.length>MaxCharCount)?InputValue.substring(0,MaxCharCount):InputValue;
          }
    });
    
    app.controller('TestController',function () {
        var InputValue:string;
    });
}


when i tries to generate the .js file it give me errors and all the errors are from the main.d.ts file that i reference in the 1st line. Now if i remove that reference the app.ts file of mine compile to generate the app.js file with one warning that angular is not define.
At least i got my js file.

**Comment by mikovenan** [comment]
@cdebdeep Your tsc version is outdated, thus causing the compile errors.
Simply remove the current typescript version and reinstall it with
`npm install typescript -g`

Following this, `tsc -version` should ouptut something like `Version 1.8.10` and your code will compile

Let me know if this solves your problem

**Comment by sferg-msft** [comment]
I fixed the issue.  I had to update my settings.json in vscode to point to the latest version of typescript.  Just because I had the latest typescript installed didn't mean it was being used by default.

See here: http://stackoverflow.com/questions/32380131/how-do-i-use-typescript-1-6-with-visual-studio-code-to-get-generators-support

**Comment by distinctdan** [comment]
I had the same issue, and installing the latest typescript as a separate npm package, and then configuring grunt-ts to use the custom tsc version fixed it for me.

**Comment by lexfrost** [comment]
Uninstall the current version of Typescript with:
npm uninstall typescript --save
Then reinstall i with:
npm install typescript --save-dev

**Comment by HarshaChinni** [comment]
Encountered this bug in `**May 2021**`

Uninstall the version of TS that you're running on. 
Install the latest version of TS available to you at that point

Eg. I did the following
npm uninstall -D typescript (This uninstalled 3.9.7 version)
npm i -D typescript@4.2.4

This fixed the problem

**Comment by mimoid-prog** [comment]
Typescript 4.0.3 failed build. Upgrade to the latest version (4.7.4) fixed the issue

**Comment by jakebailey** [comment]
Thse versions of TS are very much no longer supported by DT.
