### ISSUE TITLE
ui-grid.d.ts: Incorrect placement of refresh method

### ISSUE THREAD

**Issue by AbhishekGarg** [DefinitelyTyped/DefinitelyTyped#8775]
The method `refresh(rowsAltered?: boolean)` has been placed in the interface for `IGridInstanceOf<TEntity>`. It should be in `IGridCoreApi<TEntity>`.

It appears there is a little mix-up in the two. Ex: `queueRefresh` and `queueGridRefresh` are also there on `IGridInstanceOf<TEntity>`, and on `IGridCoreApi<TEntity>` too.

From ui-grid - `Grid` factory

    202     self.api = new GridApi(self); 
    203 
 
    204     /** 
    205      * @ngdoc function 
    206      * @name refresh 
    207      * @methodOf ui.grid.core.api:PublicApi 
    208      * @description Refresh the rendered grid on screen. 
    209      * The refresh method re-runs both the columnProcessors and the 
    210      * rowProcessors, as well as calling refreshCanvas to update all 
    211      * the grid sizing.  In general you should prefer to use queueGridRefresh 
    212      * instead, which is basically a debounced version of refresh. 
    213      * 
    214      * If you only want to resize the grid, not regenerate all the rows 
    215      * and columns, you should consider directly calling refreshCanvas instead. 
    216      * 
    217      */ 
    218     self.api.registerMethod( 'core', 'refresh', this.refresh );

**Comment by vvakame** [comment]
please send a pull request.

**Comment by AbhishekGarg** [comment]
PR #8947
