### ISSUE TITLE
react-redux's `connect` can output too-lenient type `React.ComponentClass<{}>`

### ISSUE THREAD

**Issue by seansfkelley** [DefinitelyTyped/DefinitelyTyped#8787]
There is an issue with the react-redux typings such that if you leave out the `TOwnProps` parameters to both `mapStateToProps` and `mapDispatchToProps`, you can end up with a wrapped component that will freely accept any set of props (literally anything). This issue is with the newest version of react-redux as of this writing; which were last touched 56295f5058cac7ae458540423c50ac2dcf9fc711.

So here's a snippet that erroneously compiles fine:

``` tsx
interface OwnProps {
  foo: string;
}

interface ConnectedProps {
  bar: string;
}

class FooComponent extends React.Component<OwnProps & ConnectedProps, {}> {
  render() {
    return <div/>;
  }
}

function mapStateToProps(state: any): ConnectedProps {
  return {
    bar: 'baz'
  };
}

const WrappedFoo = connect(mapStateToProps)(FooComponent);

// Missing `foo` but also specifying unknown property `quux`; this compiles fine.
React.createElement(WrappedFoo, { quux: 10 });
```

You can work around it by typecasting the result of `connect`, and everything works as expected:

``` tsx
const WrappedFoo = connect(mapStateToProps)(FooComponent) as React.ComponentClass<OwnProps>;
```

Or you can mention `OwnProps` in `mapStateToProps`:

``` tsx
function mapStateToProps(state: any, ownProps: OwnProps): ConnectedProps {
  return {
    bar: 'baz'
  };
}

const WrappedFoo = connect(mapStateToProps)(FooComponent);
```

A couple definitions:
- `OwnProps`: This is the type of the parameters that the connected version of the component accepts. That is, those that the parent must provide that aren’t auto-injected.
- `ConnectedProps`: This is the type of the parameters that are selected by `mapStateToProps`. It’s not strictly necessary to the typings or the workaround, but it helps clarify when debugging since it allows you to properly type `mapStateToProps`.

What I think is happening here is that when the optional `TOwnProps` seen in the signature of `mapStateToProps` and `mapDispatchToProps` is absent (as it is in the example), Typescript falls back on inferring `TOwnProps` as `{}`. The output of the whole process (after running `connect`) thus ends up as `React.ComponentClass<{}>`, at which point all bets are off, since `{}` accepts anything and everything.

For similar reasons, you also shouldn't specify something very lenient for `OwnProps`, such as the empty interface, which is functionally identical to `{}`. The only workaround for explicitly specifying "no own props" as far as I can tell is to use the typecast method to cast it to `React.ComponentClass<void>` (though probably with an intermediate `any` cast, since Typescript doesn't accept the `void` cast).

I tried to tweak the typings to fix this, but I wasn't able to find a better way to define `TOwnProps`. Thoughts, @tkqubo (as the listed maintainer)?

**Comment by tkqubo** [comment]
Thanks for your comment.  Yes I still don't know the best solution for this issue.
Anyway the first snippet you gave does not have sufficient type information for the compiler to infer the desired `TOwnProps` as `OwnProps`.  So we need to explicitly provide type information somewhere.  

for instance there might be options other than you gave:

```ts
// 1. provide type information to `connect` function
const WrappedFoo = connect<ConnectedProps, {}, OwnProps>(mapStateToProps)(FooComponent);
// 2. provide type information to `mapStateToProps` function
let mapStateToProps: MapStateToProps<ConnectedProps, OwnProps> = (state: any) => {
  return {
    bar: 'baz'
  };
};
```
But I thinks yours is the most suitable and succinct.
Sorry I cannot help you so much.

**Comment by labkey-nicka** [comment]
This is somewhat related to what @seansfkelley is discussing but could also be a separate issue. Mainly, `@connect` and `connect(...)` are no longer synonymous.

A lot of our class declarations use the `@connect` decorator like this:
```typescript
interface FooProps {
   someFoo: string
}

function mapStateToProps(state: any) {
   return {
      someFoo: state.someFoo
   }
}

@connect(mapStateToProps)
export default class FooComponent extends React.Component<FooProps, any> { ... }
```
which no longer works. Gives an error of:
```
error TS1238: Unable to resolve signature of class decorator when called as an expression. 
Type 'ComponentClass<{}>' is not assignable to type 'void'.
```
Declaring without the decorator still works:
```typescript
class FooComponent extends React.Component<FooProps, any> { ... }

export default connect(mapStateToProps)(FooComponent)
```
I may be missing something in my declaration of `mapStateToProps` relative to the more strict (and more useful) typings but using the decorator is something we'd like to continue doing if possible.

**Comment by tkqubo** [comment]
Sorry I will create a PR for some workaround, something like this:

```ts
interface ComponentClassDecorator {
  <TOwnProps, TStateProps, TDispatchProps>(
    mapStateToProps: MapStateToProps<TStateProps, TOwnProps>,
    mapDispatchToProps?: MapDispatchToPropsFunction<TDispatchProps, TOwnProps>|MapDispatchToPropsObject
  ): (connectedClass: ComponentClass<TOwnProps & TStateProps & TDispatchProps>) => ComponentClass<TOwnProps & TStateProps & TDispatchProps>;
}

@(connect as ComponentClassDecorator)(fooMapStateToProps)
class FooComponent extends React.Component<FooProps, any> {  }
```

And this workaround has several limitations.  Other solutions are welcomed.

**Comment by seansfkelley** [comment]
Does that work? It seems like it would be subject to the same flaws as the existing method, if `TOwnProps` never gets mentioned in `mapStateToProps` or `mapDispatchToProps`.

Also, the return type of the decorator is not right; you want the component yielded at the end of the process to just be a `React.ComponentClass<TOwnProps>`.

I tried playing around with this a while before I first filed the bug and wasn't able to come up with a better scheme than the workarounds I first presented.

**Comment by tkqubo** [comment]
Oh yes you are right.

We still have to explicitly give type information for `TOwnProps`.

On top of that, maybe due to the decorator restrictions in TypeScript, original class' type and decorated result class' type should be exactly the same (otherwise it simply produces `void`)

c.f. lib.core.d.ts

```ts
interface ClassDecorator {
  <TFunction extends Function>(target: TFunction): TFunction|void;
}
```

Therefore we cannot produce `ComponentClass<TOwnProps>` no matter what types this `connect` decorator is defined.

The 'limitations' I said above when using `ComponentClassDecorator` are:

- generated component class will be `ComponentClass<TOwnProps & TStateProps & TDispatchProps>`; we cannot remove `TStateProps` nor `TDispatchProps` from it
- all the extra properties in `TStateProps` and `TDispatchProps` should be optional, otherwise you have to provide unwanted extra properties when using that component like below:
```ts
interface OwnProps {
  foo: number;
}
interface StateProps {
  bar: number;
}
...
<ConnectedComponent foo={42} bar={42} />
// but bar value above is not actually needed, it should be injected by mapStateToProps!
```

I'm not 100% sure my understanding about this issue is correct and even if this is the case, I don't know this kind of workaround is really useful or not.

**Comment by seansfkelley** [comment]
Does this function have to be a `ClassDecorator`? It's not right now and the types check out if you give it a type hint or specify a parameter for `TOwnProps`.

**Comment by tkqubo** [comment]
Any decorators on function or class seems to be treated as a `ClassDecorator` in TypeScript, although we provide different kind of typing to them.   I think this is sort of specification in TypeScript while `connect` implementation is not conformant to that.

**Comment by use-strict** [comment]
Decorators are used for metaprogramming. They are mainly for adding/changing some internal behavior, but they never change the signature. That's a given. `connect` would work as a decorator only when passed no params. Otherwise, it must be called as a regular function.

**Comment by use-strict** [comment]
@seansfkelley , I think there the problem might be with the typing of `React.createElement`.

Try this:
```
ReactDOM.render(<WrappedFoo quux={10} foo="asd" bar="asdf"/>, document.body);
```

You will see that it accepts neither of the three params.

**Comment by seansfkelley** [comment]
Hm, good point on the decorator comment. I always use it as a function so that slipped my mind, though when using it as a function you definitely want to yield something with just `TOwnProps`.

To clarify, your example

```tsx
ReactDOM.render(<WrappedFoo quux={10} foo="asd" bar="asdf"/>, document.body);
```

seems to have nothing to do with `ReactDOM.render` but actually just the TSX

```tsx
<WrappedFoo quux={10} foo="asd" bar="asdf"/>;
```

which produces the error

```
react-redux-tests.tsx(386,5): error TS2346: Supplied parameters do not match any signature of call target.
react-redux-tests.tsx(386,33): error TS2339: Property 'quux' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<{}, {}>> & {} & { children?: ReactElemen...'.
```

It seems that there's an issue with how TSX statements are type checked, if only that they don't agree with `createElement`, which they probably should. `createElement` accepts and `ComponentClass<P>` with no constraints on `P` so it makes sense that it works fine there.

I thought the issue might be that the addition of `{ children?: ReactNode }` was causing the type checking to jump from checking against `{}`, which as noted above allows all properties, to one that specifies `children`, thereby triggering a stricter type-check, but that doesn't appear to be the case. If I munge `react.d.ts` to strip all the typing that the TSX statements use, they still fail:

```
react-redux-tests.tsx(386,17): error TS2339: Property 'quux' does not exist on type '{} & {} & {} & {}'.
```

Curious. Nothing in the [JSX docs](https://www.typescriptlang.org/docs/handbook/jsx.html) that I can see explains why this might be the case.

**Comment by use-strict** [comment]
> seems to have nothing to do with `ReactDOM.render` but actually just the TSX

Yes, you are correct. I only gave a context for the example so that it would be valid code.

> createElement accepts a `ComponentClass<P>` with no constraints on `P` so it makes sense that it works fine there.

Depends on how you look at it. There is a constrain between `P` and `ComponentClass<P>`, so it should throw errors if you have incompatible parameters. On the other hand, JSX behaves as expected, so I wouldn't waste too much time trying to figure that out, but instead focus on `createElement` which doesn't have the correct behavior.

**Comment by remojansen** [comment]
I'm having the same problem that @labkey-nicka is having.

**Comment by SkurkifyMSI** [comment]
I ran into this issue today. 

My temporary fix is explicitly casting the connected component when exporting. This allows the props on the connected component to be validated by typescript.

```
export default connect(selector)(MyComponent) as () => MyComponent;
```

**Comment by altayaydemir** [comment]
Until this is resolved, I decided to use react-redux's connect feature without using its type definitions. It works as expected.

```tsx
const { connect } = require('react-redux');

@connect(
  state => ({ test: state.test )},
  dispatch => ({
    getTest: (id: string) => dispatch(getTest(id))
  })
)
class Component ...

export { Component } 
```

**Comment by seansfkelley** [comment]
@labkey-nicka I believe your primary issue is unrelated; it appears you're also getting the too-lenient type of `{}`, but I don't _think_ it should be related to the problem with using `connect` as a decorator. If this is still an issue for you, could you file another issue to track it separately?

@SkurkifyMSI did you try the workaround I first proposed?

```
const WrappedFoo = connect(mapStateToProps)(FooComponent) as React.ComponentClass<OwnProps>;
```

I think it'll give you better typing than casting to `() => MyComponent`.

FWIW, I've been using the cast workaround for a couple months now and, though gross, it doesn't seem particularly fragile, since I always keep the `OwnProps` type up-to-date.

**Comment by seansfkelley** [comment]
For any further discussion on the usage-as-decorator-doesn't-type-check issue, please use https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9951. This issue is specifically about the type out of the output being inferred as `React.ComponentClass<{}>`; the appearance of that type in an error message about usage as a decorator can be confusing but these issues are independent.

**Comment by tiagoefmoraes** [comment]
In my tests i found that
 ```typescript
const WrappedFoo = connect<ConnectedProps, {}, OwnProps>(mapStateToProps)(FooComponent);
``` 
defines the correct types the same way as adding the `ownProps` param to `mapStateToProps`.

Just another workaround ...

**Comment by thasner** [comment]
@tiagoefmoraes using `{}` as a type argument is essentially `any`. Please use `void` instead:
`const WrappedFoo = connect<ConnectedProps, void, OwnProps>(mapStateToProps)(FooComponent);`

This should prevent you from passing arbitrary `props` to `WrappedFoo`

**Comment by thasner** [comment]
@seansfkelley it's probably worth re-testing your example now that https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15929 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16024 have merged

**Comment by seansfkelley** [comment]
Generic defaults might be able to help with this issue -- not sure how they interplay in this particular scenario, but definitely worth a shot of defaulting to (probably) `void`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
