### ISSUE TITLE
Incorrect underscore definitions

### ISSUE THREAD

**Issue by Emm** [DefinitelyTyped/DefinitelyTyped#8834]
Incorrect definitions for several methods of the `_Chain` interface: methods such as `any()` should return `_Chain<T>` but `_ChainSingle<boolean>`.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by many20** [comment]
hi you missed

all(iterator?: _.ListIterator<T, boolean>, context?: any): _ChainSingle<boolean>;
