### ISSUE TITLE
react-redux - issues with react typings

### ISSUE THREAD

**Issue by use-strict** [DefinitelyTyped/DefinitelyTyped#8866]
- [x] I tried using the latest `react/react.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `react-redux/react-redux.d.ts`.
  - The authors of that type definition are cc/ @RyanCavanaugh , @tkqubo 

After updating react.d.ts to the latest, I started getting errors with react-redux. Looks like the new typing for ReactComponent#props (`P & {children?: ReactNode}`) is causing some weird problems with type inference. Unfortunately the tests for react-redux are typed as `Component<any, any>` and they pass unconditionally. That's something to fix with a separate PR.

For reference, here is a modified example from react-redux-tests.tsx:

``` typescript
interface CounterProps {
    value: number;
    onIncrement?: () => void;
}
interface CounterState {
    counter: number;
}
declare var increment: Function;

class Counter extends Component<CounterProps, CounterState> {
    render() {
        return (
            <button onClick={this.props.onIncrement}>
                {this.props.value}
            </button>
        );
    }
}

function mapStateToProps(state: CounterState) {
    return {
        value: state.counter
    };
}

// Which action creators does it want to receive by props?
function mapDispatchToProps(dispatch: Dispatch) {
    return {
        onIncrement: () => dispatch(increment())
    };
}

connect(
    mapStateToProps,
    mapDispatchToProps
)(Counter);
```

The error is: 

```
[ts] Argument of type 'typeof Counter' is not assignable to parameter of type 'ComponentClass<{ value: number; } & { onIncrement: () => any; } & { children?: ReactElement<any> ...'. Type 'Counter' is not assignable to type 'Component<{ value: number; } & { onIncrement: () => any; } & { children?: ReactElement<any> | str...'. Types of property 'props' are incompatible. Type 'CounterProps & { children?: ReactElement<any> | string | number | {} | (ReactElement<any> | strin...' is not assignable to type '{ value: number; } & { onIncrement: () => any; } & { children?: ReactElement<any> | string | numb...'. Type 'CounterProps & { children?: ReactElement<any> | string | number | {} | (ReactElement<any> | strin...' is not assignable to type '{ onIncrement: () => any; }'. Type '{ children?: ReactElement<any> | string | number | {} | (ReactElement<any> | string | number | an...' is not assignable to type '{ onIncrement: () => any; }'. Property 'onIncrement' is missing in type '{ children?: ReactElement<any> | string | number | {} | (ReactElement<any> | string | number | an...'.
```

As a workaround, if I split `CounterProps` into `StateProps` and `DispatchProps` and explicitly type the return values of `map*ToProps`, then everything works again.

Seems to me that `CounterProps & { children?: ReactNode }` should be the same as `{ value: number; } & { onIncrement: () => any; } & { children?: ReactNode }`. Am I missing something?

**Comment by use-strict** [comment]
The commit in question is https://github.com/DefinitelyTyped/DefinitelyTyped/commit/92cf86a3e2bf344cca458946bc8587f6776784ba

This seems to have caused some issues with `React.createElement` as well. It allows anything to pass as valid props.

See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/8787

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
