### ISSUE TITLE
Definition Request: Ready with a definition for node-serialport

### ISSUE THREAD

**Issue by sumitkm** [DefinitelyTyped/DefinitelyTyped#8926]
Hi, 

I have a definition ready for the node-serialport library https://github.com/voodootikigod/node-serialport

npm - https://www.npmjs.com/package/serialport

Will it be okay to submit a pull request?

**Comment by underscorebrody** [comment]
These are already available here, though I'm not sure if they are up to date

**Comment by sumitkm** [comment]
Closing this, my definitions weren't up to scratch, and I couldn't get back to fixing them, but the new ones quoted above seem perfect.
