### ISSUE TITLE
Typings for node-fetch

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#8931]
Is it possible to retro fit the typings for whatwg-fetch for use with node-fetch? Essentially all is needed is this at the end:

``` ts
declare module 'node-fetch' {
    function fetch(url: string|Request, init?: RequestInit): Promise<Response>;
    export default fetch;
}
```

**Comment by vvakame** [comment]
please send a pull request with `node-fetch/node-fetch.d.ts`.

**Comment by andy-ms** [comment]
We now have `@types/node-fetch`.

**Comment by lygstate** [comment]
Need upgrade node-fetch
