### ISSUE TITLE
Bitmap constructor of createjs have to admit a Object like a parameter, may be?

### ISSUE THREAD

**Issue by fcanocapdepon** [DefinitelyTyped/DefinitelyTyped#8933]
I am unsing the definitions for createjs library and cant compile next line:

let icon = new createjs.Bitmap(this.render.queue.getResult("floor"));

Because the contructor of Bitmap not admit a Object and the "getResult" function returns an object.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by fcanocapdepon** [comment]
Ok
