### ISSUE TITLE
How to remove a module?

### ISSUE THREAD

**Issue by vitaly-t** [DefinitelyTyped/DefinitelyTyped#8956]
Sometime ago somebody [published TypeScripts here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/pg-promise) for my library [pg-promise](https://github.com/vitaly-t/pg-promise).

Since then the library started [its own, correct distribution of TypeScripts](https://github.com/vitaly-t/pg-promise/tree/master/typescript), while the one published here is a small fraction of it, and completely invalid.

How can I get it removed here? I have no plans to maintain it here, and it is only causing issues to developers who try to use it.

**Comment by vvakame** [comment]
I created #8987 . related #8421 
cc/ @ISO50

My opinion.

1. If npm package author want to get full control of own package. I agree to it. 

2. but, `pg` package is not yours. your pg-promise.d.ts contains reference to your `pg.d.ts`. https://github.com/vitaly-t/pg-promise/blob/3888d70abf5f562a20be7224254757368adf2654/typescript/pg-promise.d.ts#L5
I think this is not so good.

I'm not pg package user. I'm sorry when I say that strange.

**Comment by vitaly-t** [comment]
@vvakame I don't know who or how created TypeScript for `pg`, and whether they are usable at all.

What I created with `pg-promise` is the precise sub-set of `pg` that's needed within `pg-promise`.

**Comment by vitaly-t** [comment]
@vvakame Thank you for the PR you did!

**Comment by vitaly-t** [comment]
It was done awhile ago.
