### ISSUE TITLE
underscore _.max(object) should be allowed

### ISSUE THREAD

**Issue by danvk** [DefinitelyTyped/DefinitelyTyped#8961]
The underscore `_.max` method is [declared to take a List][1], but Objects work just as well:

```
> _.max({a: 1, b: 2})
2
```

Perhaps `max` should be declared to take a `Collection` rather than a `List`?

- [x] I tried using the latest `underscore/underscore.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `underscore/underscore.d.ts.d.ts`.
  - The authors of that type definition are cc/ @borisyankov @jbaldwin @ccurrens 

[1]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/641df27e73ca67fa7199a3deedae104198d41a17/underscore/underscore.d.ts#L537

**Comment by vvakame** [comment]
could you send a pull request?

**Comment by danvk** [comment]
I've sent out https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9222 which adds these definitions. @vvakame please take a look.
