### ISSUE TITLE
Type definitions for Angular UI Bootstrap

### ISSUE THREAD

**Issue by karrhu** [DefinitelyTyped/DefinitelyTyped#8984]
The version in the file seems to be off. For which version are these typings for? 0.13.3 seems way too old, newest is 1.3.1. Version in the comments could be updated to match the actual library version.

**Comment by vvakame** [comment]
You can do that! it's very helpful.

**Comment by Totemika** [comment]
What version exactly is the tsd file compatible with? I need to use a higher version (1.2.5)

**Comment by Dinistro** [comment]
Looks like a dup of #8394
