### ISSUE TITLE
usestaticfileloader implementation in typescript definition file doesn't allow to load json files from more than one location

### ISSUE THREAD

**Issue by imfarhadk** [DefinitelyTyped/DefinitelyTyped#8985]
The current definition allows only one directory location
 useStaticFilesLoader(options: IStaticFilesLoaderOptions): ITranslateProvider;

Is this an error?

can the implementation be modified to include multiple locations as defined in JS?

$translateProvider.useStaticFilesLoader({
            files: [{
                prefix: 'locale-',
                suffix: '.json'
            }, {
                prefix: 'breeze/locale-',
                suffix: '.json'
            }]
        });

**Comment by vvakame** [comment]
Are you talking about https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angular-translate/angular-translate.d.ts ?
cc/ @michelsalib

**Comment by imfarhadk** [comment]
the useStaticFilesLoader function only takes one IStaticFilesLoaderOptions type object. It doesn't handle the array of IStaticFilesLoaderOptions objects

**According to the documentation:**

Let's say you have two localization files locale-de.json and locale-en.json. You can simply use the loader like this:

    `$translateProvider.useStaticFilesLoader({
        prefix: 'locale-',
        suffix: '.json'
    });
    $translateProvider.preferredLanguage('en');`

Alternatively, if you have multiple translation files in distinct locations, you may instead supply an array of files to the loader:

    `$translateProvider.useStaticFilesLoader({
        files: [{
            prefix: 'locale-',
            suffix: '.json'
        }, {
            prefix: '/absolute/path/to/locale-',
            suffix: '.json'
        }, {
            prefix: 'another/path/to/locales/',
            suffix: ''
        }]
    });
    $translateProvider.preferredLanguage('en');`

The first case is supported in typescript definition, but not the second case.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by imfarhadk** [comment]
I have not done any changes to the definition files. I was under the impression that one of the developers will make the change to resolve the issue.
