### ISSUE TITLE
Module "classnames" definition does not support ES6 module definition

### ISSUE THREAD

**Issue by ArtemZag** [DefinitelyTyped/DefinitelyTyped#9003]
- [x] I tried using the latest `classnames/classnames.d.ts` file in this repo and had problems.

![image](https://cloud.githubusercontent.com/assets/1687370/14561286/dec359a6-031d-11e6-92ae-7797160e5740.png)

As I result I get message "Module 'classnames' has no default export".

**Comment by vvakame** [comment]
you should use `import * as classnames from "classnames";`.
https://github.com/JedWatson/classnames/blob/master/index.js#L39

**Comment by ArtemZag** [comment]
@vvakame, Thanks. I'll try. The strange thing is that this also works:

> import classnames from 'classnames';

I get typescript error but everything works.

**Comment by alexey-pelykh** [comment]
Time to get back to this due to [original package change](https://github.com/JedWatson/classnames/pull/105): PR #25205 or PR #25206
