### ISSUE TITLE
D3.d.ts lacks things when dealing with d3.event

### ISSUE THREAD

**Issue by juepiezhongren** [DefinitelyTyped/DefinitelyTyped#9013]
i am using d3.d.ts for somedays while transferring my js project into ts?
when i write this codes:
                var t_x = d3.event._pageX_;
                var t_y = d3.event._pageY_;
pageX and pageY are occured to be mistake!
Event interface are required to be expanded!

**Comment by vvakame** [comment]
please send a pull request.

**Comment by tomwanzek** [comment]
As part of some legacy D3v3 issue clean-up, can this issue be please closed?

D3v4 has been released and supported with actively maintained definitions for several months now, so it would be great to have only current issues open for clarity.

Thanks in advance!

cc @gustavderdrache @andy-ms
