### ISSUE TITLE
Turf not importing and test file has errors

### ISSUE THREAD

**Issue by pauldhawk** [DefinitelyTyped/DefinitelyTyped#9027]
- [x] I tried using the latest `turf/turf.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @...gcroteau Guillaume Croteau.

I cannot import the turf js library. When I run the test file or any other file referencing the turf library i get the following error : ReferenceError: turf is not defined

i've used //<, import 'turf', import \* as turf from 'turf', import turf = require('turf')

other modules are importing no problem.
my tsconfig settings are 
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
} 

when i run the test file (or run)

I've tried importing via // < and import but it 

the error i get when trying to compile the turf-test.ts is:

turf/turf-tests.ts(426,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'polygon' must be of type 'Polygon', but here has type 'Feature<Polygon>'.
turf/turf-tests.ts(495,37): error TS2345: Argument of type 'Polygon' is not assignable to parameter of type 'Feature<Polygon>'.
  Property 'geometry' is missing in type 'Polygon'.

turf@2.0.2
latest def file

any idea what is wrong

**Comment by danvk** [comment]
I'm also running into this @gcroteau

**Comment by danvk** [comment]
Changing `declare namespace turf {` to `declare module "turf" {` in [`turf/index.d.ts`][1] fixed this for me. I'll send a PR.

[1]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/544a35a10866b32afda9c7f029c0764558563f4f/turf/turf.d.ts#L8

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
