### ISSUE TITLE
Kendo-UI missing footerAttributes in GridColumn

### ISSUE THREAD

**Issue by EmirKrkic** [DefinitelyTyped/DefinitelyTyped#9036]
- [X] I want to talk about `kendo-ui.d.ts`.

There is no definition for footerAttributes in the GridColumn interface.

**Comment by vvakame** [comment]
cc/ @tsvetomir

**Comment by tsvetomir** [comment]
@vvakame: I'm tracking this issue in our repo . Please, feel free to close this issue. Thanks!

**Comment by vvakame** [comment]
I'm waiting your PR 😉
