### ISSUE TITLE
es6-shim Promise.reject doesn't makes sense, maybe

### ISSUE THREAD

**Issue by xealot** [DefinitelyTyped/DefinitelyTyped#9043]
- [x] I tried using the latest `es6-shim/es6-shim.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `es6-shim/es6-shim.d.ts`.
  - The authors of that type definition are cc/ @vvakame 

The `Promise.reject` definition doesn't make a lot of sense to me.

How can it accept a reason of `any` but return a promise of `void`? I think the intent is that `void` is supposed to ignore the type. But if you have a function like this:

```typescript
function terribleExample(): Promise<number> {
    if (false) {
        return Promise.reject(new Error("NOPE"));
    }

    return new Promise((resolve, reject) => {
        resolve(4);
    });
}
```

Typescript says that you cannot assign `void` to `number`:
```error TS2322: Type 'Promise<void>' is not assignable to type 'Promise<number>'.
  Type 'void' is not assignable to type 'number'.```

I made sure and double checked documentation at MDN (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject)

> The static Promise.reject function returns a Promise that is rejected. For debugging purposes and selective error catching, it is useful to make reason an instanceof Error. 

Updating `es6-shim.d.ts` and setting the reject response type to `any` obviously works. But is that the correct thing to do? Looking at `es6-promise` typings it appears this decision was made as well:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/es6-promise/es6-promise.d.ts#L53

**Comment by vvakame** [comment]
@xealot please send a pull request. I'll review it. cc/ @rbuckton

**Comment by rbuckton** [comment]
When you pass an error to `Promise.reject`, it cannot infer the type from the error. The current behavior is to have `Promise.reject` return a `Promise<void>`, unless you use the generic overload, e.g.:

```ts
return Promise.reject<number>(new Error("NOPE"));
```

I can understand relaxing the restriction to returning a `Promise<any>` over `Promise<void>`, though I generally try to avoid using `any` in the return position of a signature if I can avoid it.

**Comment by xealot** [comment]
I agree that using `any` should be avoided, I can override my `reject` call to share the type of the promise I'm looking for.

You would need two template markers to fully represent the success and error chains, but as it stands that may be overkill and may not provide much advantage.
