### ISSUE TITLE
Problem using decimal.js using es6 import module

### ISSUE THREAD

**Issue by joeferner** [DefinitelyTyped/DefinitelyTyped#9045]
- [x] I tried using the latest `decimal.js/decimal.js.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (using: 1.8.10)
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `decimal.js/decimal.js.d.ts`.

@vvakame @musicist288 @jvilk

I would like to import 'decimal.js' into my project using the following ES6 syntax.

```typescript
import Decimal from 'decimal.js';

function calc(a: Decimal): Decimal {
   ...
}
```

But I get the following error

```
error TS2305: Module ''decimal.js'' has no exported member 'Decimal'
```

I also tried

```typescript
import { Decimal } from 'decimal.js';
... and ...
import * as Decimal from 'decimal.js';
```

**Comment by jvilk** [comment]
`import * as Decimal from 'decimal.js';` is the appropriate syntax for replacing `import Decimal = require('decimal.js');`

The following code works for me:

```{ts}
/// <reference path="./decimal.js/decimal.js.d.ts" />
import * as Decimal from 'decimal.js';

```

Sounds like you're referencing the definitions file incorrectly.

**Comment by joeferner** [comment]
```typescript
/// <reference path="../typings/decimal.js/decimal.js.d.ts" />
import * as Decimal from 'decimal.js';

function calc(a: Decimal) {
   ... 
}
```

gives me the following error...

```
error TS2304: Cannot find name 'Decimal'.
```

**Comment by jvilk** [comment]
That's because the type is `decimal.Decimal`. I used `namespace decimal` to declare the types to be prefaced with `decimal`, and exported the main interface as the `decimal.js` module. AFAIK, there's no cleaner way to do this.

Other definition files, such as Node.js, do the same thing.

**Comment by joeferner** [comment]
Ah I see, I'm new to this whole ES6 import stuff. Got it to work with:

```typescript
/// <reference path="../typings/decimal.js/decimal.js.d.ts" />
import * as Decimal from 'decimal.js';

function calc(a: decimal.Decimal) {
   ... 
}
```

**Comment by jvilk** [comment]
This is just a difficult edge case in TypeScript definition files, so the problem is totally understandable.

Good luck on your code!
