### ISSUE TITLE
Missing components in react-bootstrap

### ISSUE THREAD

**Issue by danilojrr** [DefinitelyTyped/DefinitelyTyped#9062]
@walkerburgin @vsiao 

There are some components missing in react-bootstrap. I'm using it right now and would like to add some of them.
See this: https://github.com/danilojrr/DefinitelyTyped/commit/a6a476190ce2197f04f541c360fdccc543f0005d
So, you are the original authors, then... can I proceed with this change?

**Comment by vsiao** [comment]
sure. please open a PR with links to relevant documentation.

**Comment by larsw** [comment]
Any news on this?

**Comment by vsiao** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9070 is the relevant PR
