### ISSUE TITLE
chai definitions break tsx

### ISSUE THREAD

**Issue by arolson101** [DefinitelyTyped/DefinitelyTyped#9120]
- [X] I tried using the latest `chai/chai.d.ts` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] I want to talk about `chai/chai.d.ts`.
  - The authors of that type definition are cc/ @Bartvds 

The bit at the end of chai.d.ts:

``` ts
interface Object {
    should: Chai.Assertion;
}
```

breaks tsx support because it thinks that all objects must have a `should` property (specifically, " Property 'should' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<...").  It should be:

``` ts
interface Object {
    should?: Chai.Assertion;
}
```

**Comment by nikolaymatrosov** [comment]
This Object interface expansion also cause another bug. Typescript compiler adds 
```/// <reference types="chai">``` to all d.ts generated based on sources containing `Object`. (E.g. https://github.com/angular-redux/ng2-redux/pull/209/files)
I think it is better to eliminate polution Object interface with `should` property and make separate version of typings for those who need `should` assertion syntax.

**Comment by villasv** [comment]
It also breaks my compilation process because I have typings for Elasticsearch Search body requests. It has an internal interface

```
export interface Bool {
  should?: Query | Query[];
  filter?: Query | Query[];
  must?: Query | Query[];
  must_not?: Query | Query[];
}
```

And when I try to build an object with
``` 
const b: Bool = { should: query }
```

I get a type error saying that `Query` and `Assertion` are incompatible.

**Comment by villasv** [comment]
I agree with @nikolaymatrosov that we should not pollute the Object interface by default and I'm going to make a PR removing that last bit.

**Comment by villasv** [comment]
I couldn't manage a feasible PR because I tried to make it happen in the existing @types/chai package, but now I think we should instead create an alternatives types library that is exactly the same but doesn't contain the Object declaration.

**Comment by bevacqua** [comment]
This `interface Object { should: Chai.Assertion }` thing is causing TS to infer that an `{}` requires a `should` property when my type contains `should`, but then completely fails to reconcile the two. So when I update Cypress, which has a dependency on Chai, then `tsc` throws tens of errors.

Contrived example:

```
interface QueryContainer {
  bool?: BoolQuery
  …
}

interface BoolQuery {
  must?: QueryContainer[]
  should?: QueryContainer[]
  must_not?: QueryContainer[]
  filter?: QueryContainer[]
}

const query: QueryContainer = { bool: {} }
```

Was fine before, but with `cypress@4.3.0`:

```
whatever.ts:109:5 - error TS2322: Type '{ must: ({ term: { 'metadata.key': { value: string; }; }; } | { term: { 'metadata.value.keyword': { value: string; }; }; })[]; }' is not assignable to type 'BoolQuery'.
  Types of property 'should' are incompatible.
    Type 'Assertion' is not assignable to type 'QueryContainer[]'.

109     bool: {
        ~~~~

  whatever_types.ts:6467:3
    6467   bool?: BoolQuery
           ~~~~
    The expected type comes from property 'bool' which is declared here on type 'QueryContainer'

```

We can refine it a bit and get a better error:

```
const boolQ: BoolQuery = {}
const query: QueryContainer = { bool: boolQ }
```

Now we get:

```
whatever.ts:81:9 - error TS2322: Type '{}' is not assignable to type 'BoolQuery'.
  Types of property 'should' are incompatible.
    Type 'Assertion' is not assignable to type 'QueryContainer[]'.

81   const boolQ: BoolQuery = {}
           ~~~~~
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
