### ISSUE TITLE
angularjs/angular.d.ts $routeConfig

### ISSUE THREAD

**Issue by SebastianSchenk** [DefinitelyTyped/DefinitelyTyped#9122]
- [x] I tried using the latest `angularjs/angular.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `angularjs/angular.d.ts`.
  - The authors of that type definition are cc/ @diegovilar

During the last changes of angular.d.ts the property $routeConfig of the IComponentOptions interface was removed. I don't really understand why, since it is the recommended way to define routes with the new component router (https://code.angularjs.org/1.5.5/docs/guide/component-router)

Could you re-include this property please?

**Comment by rvl** [comment]
@mmiszy removed it with the following reason:
> They're not valid properties for components in pure AngularJS. They're an extension added by the Component Router. People who don't use the Component Router will surely find these properties confusing (I do). This should go to a separate typings file for the Component Router.

The thing is, `$routeConfig` doesn't appear in `angularjs/angular-component-router.d.ts` which means our projects no longer compile...

**Comment by mmiszy** [comment]
@rvl @SebastianSchenk As a workaround you can easily add it on your own in your project – you have some kind of `custom.d.ts` or `shim.d.ts` file, don't you?
And as it's been established, this property should be added to `angular-component-router.d.ts` because it's not part of angularjs – pull requests are welcome.

**Comment by rvl** [comment]
Thanks @mmiszy. The third option is to just keep the old version of `angular.d.ts`, which is what I'm going to do.

**Comment by mickeyvip** [comment]
While the issue with `$routeConfig` can be avoided by having `custom.d.ts`:

```typescript
declare namespace angular {
    interface IComponentOptions {
        $routeConfig?: any[];
    }
}
```

I have another issue:

```typescript
const MyComponent: IComponentOptions = {
    templateUrl: "my.component.html",
    $routeConfig: routeConfig,
    bindings: { $router: '<' },
    controllerAs: "model",
    controller: MyComponentController
};
```

```
$ tsc
src/modules/module.ts(14,36): error TS2345: Argument of type '{ templateUrl: string; $routeConfig: RouteDefinition[]; bindings: { $router: string; }; controlle...' is not assignable to parameter of type 'IComponentOptions'.
  Types of property 'bindings' are incompatible.
    Type '{ $router: string; }' is not assignable to type '{ [binding: string]: string; }'.
      Index signature is missing in type '{ $router: string; }'.
```

The workaround I use is declaring `bindings` with the required type signature:

```typescript
const bindings: {[bindngs: string]: string} = { $router: '<' };
const MyComponent: IComponentOptions = {
    templateUrl: "my.component.html",
    $routeConfig: routeConfig,
    bindings: bindings,
    controllerAs: "model",
    controller: MyComponentController
};
```

**Comment by mmiszy** [comment]
What TypeScript version do you use @mickeyvip ? It sounds like a bug in TypeScript that I have mentioned here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8150#commitcomment-16807414

**Comment by mickeyvip** [comment]
@mmiszy , I'm on `1.8.10`

**Comment by mmiszy** [comment]
@mickeyvip are you sure that's the version you're using? I tested your code and I don't get any errors, as expected.
[See on Playground](http://www.typescriptlang.org/play/#src=interface%20IComponentOptions%20%7B%0A%09controller%3F%3A%20string%20%7C%20Function%20%7C%20(string%20%7C%20Function)%5B%5D%3B%0A%09controllerAs%3F%3A%20string%3B%0A%09template%3F%3A%20string%20%7C%20Function%20%7C%20(string%20%7C%20Function)%5B%5D%3B%0A%09templateUrl%3F%3A%20string%20%7C%20Function%20%7C%20(string%20%7C%20Function)%5B%5D%3B%0A%09bindings%3F%3A%20%7B%5Bbinding%3A%20string%5D%3A%20string%7D%3B%0A%09transclude%3F%3A%20boolean%20%7C%20string%20%7C%20%7B%5Bslot%3A%20string%5D%3A%20string%7D%3B%0A%09require%3F%3A%20string%20%7C%20string%5B%5D%20%7C%20%7B%5Bcontroller%3A%20string%5D%3A%20string%7D%3B%0A%7D%0A%0Aconst%20MyComponent%3A%20IComponentOptions%20%3D%20%7B%0A%20%20%20%20templateUrl%3A%20%22my.component.html%22%2C%0A%20%20%20%20bindings%3A%20%7B%20%24router%3A%20'%3C'%20%7D%2C%0A%20%20%20%20controllerAs%3A%20%22model%22%0A%7D%3B)

**Comment by mickeyvip** [comment]
@mmiszy, I just recreated the issue happening in my code.

Indeed, as you pointed out, when I have:

```typescript
const MyComponent: IComponentOptions = {
    templateUrl: "my.component.html",
    $routeConfig: routeConfig,
    bindings: { $router: '<' },
    controllerAs: "model",
    controller: MyComponentController
};
``` 

it compiles OK.

But I had several code changes and extracted `bindings` into a `const`:

```typescript
const bindings = { $router: '<' };
const MyComponent: IComponentOptions = {
    templateUrl: "my.component.html",
    $routeConfig: routeConfig,
    bindings: bindings,
    controllerAs: "model",
    controller: MyComponentController
};
```

And now the compilation fails, unless I have explicitly set type on `cons bindings`:

```typescript
const bindings: {[bindngs: string]: string} = { $router: '<' };
```

Am I doing something wrong here?

**Comment by mmiszy** [comment]
@mickeyvip thanks for a very detailed explanation :) You're not doing anything wrong here, and there's nothing wrong with `angular.d.ts`, it's just how TypeScript works… at for least for now. Your solution is correct and giving an explicit index type to your `const bindings` it's the right thing to do.
However, this behaviour will change to a more friendly one in the future, probably in TypeScript 2.0 – see https://github.com/Microsoft/TypeScript/issues/6041

**Comment by mickeyvip** [comment]
@mmiszy, thank you.

**Comment by kresli** [comment]
I know this is an old thread, but for whoever come over this again the above solution is wrong because you loosing types. The correct solution is 

```
const bindings: { [K in keyof Bindings]: string } = {}
```

**Comment by benyaminl** [comment]
I have a silly question, I install both `@types/angular-route` and `@types/angular`, but seems the `angular.IComponentOptions` only detect from the `@types/angular`, is there any specific way to make it works with `@types/angular-route` definition? Thank you!

cc @mickeyvip @mmiszy (sorry for interuption).
