### ISSUE TITLE
crypto-js incorrect typings

### ISSUE THREAD

**Issue by dragGH102** [DefinitelyTyped/DefinitelyTyped#9133]
Issue: **crypto-js** typings are incorrect. For example: 

> CryptoJS.AES(pars)

is a valid typing but **not a valid function** (undefined)
whereas 

> CryptoJS.AES.encrypt(pars) 

is a valid function but **not a valid typing**

CryptoJS (latest version) has been installed from NPM.
The issue is particularly severe in Angular 2 since it'd not allow the app to start if any invalid typing.
I am also confident this is **not** an Angular 2 beta issue, since having a look to the .d.ts file, **I can clearly see there is no "encrypt" function**.

How to **REPRODUCE**:

Within Angular:
- Create a sample Angular 2 app (latest beta will be fine) or use boilerplate (https://github.com/mschwarzmueller/angular-2-beta-boilerplate)
- typings install --ambient crypto-js
- add **cryptojs: 'node_modules/crypto-js/crypto-js.js'** in SystemJS' map configuration
- **import CryptoJS from 'cryptojs'** (in some-component.component.ts)
- first try with **console.log(CryptoJS.AES('password','key'))** , then try **console.log(CryptoJS.AES.encrypt('password','key'))**.==> **After each try**: Ctrl+C (stop running npm app), then **npm start**

**Standalone**:
- npm install crypto-js
- typings install --ambient crypto-js
- **import CryptoJS from 'cryptojs'** (in any TS file)
- first try with **console.log(CryptoJS.AES('password','key'))** , then try **console.log(CryptoJS.AES.encrypt('password','key'))**

**StackOverFlow question**: http://stackoverflow.com/questions/36772710/how-to-import-non-core-npm-modules-in-angular-2-e-g-to-use-an-encryption-libra

**Issue questionnaire**
- [X] I tried using the latest `crypto-js/crypto-js.d.ts` file in this repo and had problems ==> yes, I downloaded the file manually but it was not recognized (perhaps some mistake as mine, see my SO overflow question above. So I finally installed via **typings install**.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X]  StackOverflow: I already tried asking there (see my SO overflow question above)
- [X] The authors of that type definition are cc/ @Michael Zabka (no valid cc suggestion available)

**Comment by vvakame** [comment]
please send a pull request first.

**Comment by dragGH102** [comment]
@vvakame isn't a pull request meant to fix it? I am not expert in typings.
Or you mean I should provide a full example?

**Comment by vvakame** [comment]
fix it if you can. 😉 
We are not expert in `crypto-js`. 
cc @misak113

**Comment by dragGH102** [comment]
@vvakame thanks for the answer.
I am not expert either. Did you mention @misak113 as the person in charge of crypto-js definitions?
If not, shall I write directly do crypto-js developer about the typings? (I am not sure who is actually developing the typings)

**Comment by misak113** [comment]
Ok, there ware some differences between Hasher & Cipher functions which I didn't covered. I have created fix PR for current version including full test cases from official documentation. Please could you review it & merge it? @vvakame https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9191

**Comment by vvakame** [comment]
👍
