### ISSUE TITLE
Threejs TrackballControls set target0 has no effect?

### ISSUE THREAD

**Issue by TardigradeX** [DefinitelyTyped/DefinitelyTyped#9149]
Im trying to set the target of  **/threejs/three-trackballcontrols.d.ts** to the center of my Mesh,

The typed file only makes **target0** variable available. Which is, in my opinion an internal variable used in the reset method. Setting it to a vector position has no effect.

The variable which should be made public is **target**, without the 0.
I can pull and change this if nobody has objections.

**Comment by vvakame** [comment]
cc @gyohk @florentpoujol @SereznoKot

**Comment by florentpoujol** [comment]
In the code, the `target` property is just below the "internal" comment, so I'm not sure it's supposed to be public.
But it doesn't hurt to add it.
