### ISSUE TITLE
OpenLayers ol.Object interferes with global Object type

### ISSUE THREAD

**Issue by matthiasdailey-ccri** [DefinitelyTyped/DefinitelyTyped#9186]
- [x] I tried using the latest `openlayers/openlayers.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `openlayers/openlayers.d.ts`.
  - The authors of that type definition are cc/ @bolkhovsky @woutergd @vvakame @aindlq

# Issue:
It seems that since Openlayers defines a class `Object` in the `ol` namespace, all references to the basic `Object` global type are broken. 

I am new to both typings and typescript, but as far as I know, within a namespace, references to classes in the same namespace do not need to be prefixed by the namespace name.

```ts
declare namespace A {
  class foo {}
  // within here, foo does not need to be referenced as A.foo
  // can be referenced as simply `foo`, like so:
  interface IBar {
    myFoo: foo,
    myObj: Object // global Object type
  }
  // but now we overshadow the global Object type
  class Object {
    get(key: string): any;
  }
  // now all references to the type `Object` in this namespace will be broken
}
```

The typescript compiler is interpreting all the `Object` type declarations in the `ol` namespace as if they are pointing to `ol.Object`. And object literals are not interchangeable with `ol.Object`, so it is not possible to instantiate certain classes.

For example, trying to write this:

```ts
var f = new ol.Feature({});
f.setProperties(<Object>{a: 1, b: 2})
```

causes this error in tsc v1.8.10:
```
Argument of type 'Object' is not assignable to parameter of type 'ol.Object'.
Property 'get' is missing in type 'Object'.
```
The error is because the d.ts file defines setProperties like so: `setProperties(values: Object): void;`, and `Object` refers to `ol.Object` instead of the normal global `Object`.

To solve this problem I think we could define a type alias at the top of the file (`declare type GlobalObject = Object;`) and replace all usages of `Object` with `GlobalObject`. That seems to solve the problem for me. I want to get your input before I submit a PR, since I'm new to this. Thanks.

**Comment by bolkhovsky** [comment]
@matthiasdailey-ccri thanks for the very detailed explanation! In fact, the subject is rather new for me as well. I'd ask @basarat to comment out this issue with his expert opinion,  because I'm pretty sure that the OL is not the only library which has a class named `Object`.

**Comment by matthiasdailey-ccri** [comment]
Fixed with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10119
