### ISSUE TITLE
webpack: Stats needs `compilation` property

### ISSUE THREAD

**Issue by donaldpipowitch** [DefinitelyTyped/DefinitelyTyped#9208]
- [x] I tried using the latest `.d.ts` file in this repo and had problems.

See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/webpack/webpack.d.ts#L477.
`interface Stats` needs `compilation` property. I think there are even more properties missing like `endTime`.

**Comment by vvakame** [comment]
please send a pull request.
