### ISSUE TITLE
parse5.d.ts : Wrong interface or method return type.

### ISSUE THREAD

**Issue by Supamiu** [DefinitelyTyped/DefinitelyTyped#9235]
- [x] I tried using the latest `parse5/parse5.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @nicojs @chrootsu 

When you call `treeAdapters.default.getAttrList(node)` you get an `Attribute[]`. So, if you want to add an attribute to this node, you have to do something like `treeAdapters.default.getAttrList(node).push({key: 'foo', value:'bar'})`.

Problem is that `key` property is ignored, because this should be an `ASTAttribute[]` or `Attribute` interface should have `name` instead of `key`. Since I don't know which one is the good fix, created an issue instead of a PR.

**Comment by vvakame** [comment]
@Supamiu please send a pull request. I'll review it.

**Comment by Supamiu** [comment]
@vvakame problem is that I don't know which one would be the good fix, since I'm not a parse5 developer, I don't know if I should edit `getAttrList(node)` return type or `Attribute` interface.
