### ISSUE TITLE
Definition Request: p5js

### ISSUE THREAD

**Issue by LujunWeng** [DefinitelyTyped/DefinitelyTyped#9245]
p5.js is a JS client-side library for creating graphic and interactive experiences, based on the core principles of Processing. http://twitter.com/p5xjs — http://p5js.org/

**Comment by AgentMulder** [comment]
Yes. Do add p5.d.ts to the repository

**Comment by arendon1** [comment]
i'd love to work p5js with typescript, it would be awesome.

**Comment by Spongman** [comment]
it's being worked on ;-)

https://github.com/processing/p5.js/pull/2279

**Comment by arendon1** [comment]
Sweet!

**Comment by Kinrany** [comment]
This issue can be closed: [@types/p5](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/p5)
