### ISSUE TITLE
react-router LocationDescriptor type is not exported

### ISSUE THREAD

**Issue by cramhead** [DefinitelyTyped/DefinitelyTyped#9265]
- [ ] I tried using the latest `react-router/index.d.ts` file in this repo and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x] I want to talk about `react-router/index.d.ts` and `history.d.ts`.
  - The authors of that type definition are cc/ @ngbrown 
    Sergey Buturlakin https://github.com/sergey-buturlakin, Yuichi Murata https://github.com/mrk21, Václav Ostrožlík https://github.com/vasek17, Nathan Brown https://github.com/ngbrown

When I install react-router I get the following errors

```
ERROR in /Projects/REACT/rangle/typescript-react-redux-starter/typings/browser/ambient/react-router/index.d.ts
(32,22): error TS2305: Module 'HistoryModule' has no exported member 'LocationDescriptor'.

ERROR in /Projects/REACT/rangle/typescript-react-redux-starter/typings/browser/ambient/react-router/index.d.ts
(111,30): error TS2305: Module 'HistoryModule' has no exported member 'LocationDescriptor'.

ERROR in /Projects/REACT/rangle/typescript-react-redux-starter/typings/browser/ambient/react-router/index.d.ts
(211,31): error TS2305: Module 'HistoryModule' has no exported member 'LocationDescriptor'.
```

Steps to reproduce

Clone https://github.com/rangle/typescript-react-redux-starter and get it running, i.e. npm install; npm run dev
run node_modules/typings/dest/bin.js install react-router --ambient --save
run npm run dev

Expected Behavior
Typings throw no errors

Actual Behavior
Typings compilation throws three errors

I can see from the code that history.d.ts doesn't export the LocationDescriptor type, but it's used in the react-router type definition.

**Comment by vvakame** [comment]
@cramhead definition is exported by default in `.d.ts` context.
You should use with `history.d.ts`. `typings` remove reference comment from .d.ts.

**Comment by cramhead** [comment]
Tried that. When I add the history typings I get duplicate errors. I've added them as ambient.

**Comment by bittersweetryan** [comment]
I'm seeing the same thing with react-router  2.4. Perhaps the `history.d.ts` file might not be up to date with the latest history api.  https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/history/history.d.ts states that its for `v1.8` and 2.4 lists history `^2.0.1` as a dependency.

**Comment by cramhead** [comment]
I upgraded to typings 1.0.4 and it seems to have resolved the issue. 
Note, I specified them with ```--global```, which used to be ```--ambient``` and specified the definitely typed as the source with ```typings install dt~react-router --global --save``` and ```typings install dt~react-router/history --global --save```

**Comment by xuqingkuang** [comment]
@cramhead Thanks for your tips it solved the issue before.

But I just upgrade to TypeScript 2.0.0beta and use npm with @types repo to instead of typings, the issue appear again.

    ERROR in D:\Project\node_modules\@types\react-router-redux\index.d.ts
    (26,39): error TS2305: Module '"history"' has no exported member 'LocationDescriptor'.

    ERROR in D:\Project\node_modules\@types\react-router-redux\index.d.ts
    (45,55): error TS2305: Module '"history"' has no exported member 'History'.

    ERROR in D:\Project\node_modules\@types\react-router-redux\index.d.ts
    (59,52): error TS2305: Module '"history"' has no exported member 'History'.

    ERROR in D:\Projec\node_modules\@types\react-router-redux\index.d.ts
    (60,48): error TS2305: Module '"history"' has no exported member 'History'.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
