### ISSUE TITLE
jquery.d.ts: Incorrect parameter name

### ISSUE THREAD

**Issue by mnpenner** [DefinitelyTyped/DefinitelyTyped#9275]
- [x] I tried using the latest `jquery/jquery.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @johnnyreilly @Diullei @basarat and 67 more

Error is here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4cdfbe96b666eec5e1defbb519a62abf04e96764/jquery/jquery.d.ts#L320

All these guys have incorrect parameter names. Doc comments need to be updated to match function signature.

![screenshot from 2016-05-10 12-04-07](https://cloud.githubusercontent.com/assets/1112998/15159040/62685238-16a7-11e6-88cb-d4ab0291bd01.png)

**Comment by johnnyreilly** [comment]
Sure. Pull requests always welcome. please could you  link back to the API docs when you do it? Makes merging a much quicker process. Thanks.
