### ISSUE TITLE
wrong type for IState.template

### ISSUE THREAD

**Issue by abuscom-leonhard** [DefinitelyTyped/DefinitelyTyped#9330]
Using the latest version of  angular-ui-router/angular-ui-router.d.ts

I think the right definition for the property `template` of the `interface IState` should be
`
template?: string | {(params: IStateParamsService): string};
`
and not 
`
template?: string | {(): string};
`

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by AbhishekGarg** [comment]
PR #9354

**Comment by vvakame** [comment]
👍
