### ISSUE TITLE
Definition Request: material-ui v0.15

### ISSUE THREAD

**Issue by jcain** [DefinitelyTyped/DefinitelyTyped#9336]

**Comment by renestalder** [comment]
Is there already something in work? @ngbrown @herrmanno

Also I found this, updated some days ago.
http://www.nuget.org/packages/material-ui.TypeScript.DefinitelyTyped/0.7.9

What's different with this?

**Comment by ngbrown** [comment]
@jcain @renestalder : I already started a branch here

https://github.com/ngbrown/DefinitelyTyped/tree/material-ui-0-15-0

This version of material-ui is significantly different, so while my new definitions currently have no syntax errors, I haven't tested it in my actual project yet, nor have I updated the tests to their current documentation.

Please try it out from my branch and let me know of any errors you find.

I'm not familiar with how DefinitelyTyped manages their NuGet packages, but it looks like it just increments the version number everytime the underlying files change.  I use `npm` and `tsd`.

**Comment by renestalder** [comment]
Thanks @ngbrown. Included it via typings.

Since I never used Material UI before, I just stick to the [getting started](http://www.material-ui.com/#/get-started/usage) guide.

```js
import getMuiTheme from 'material-ui/styles/getMuiTheme';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
```

At the moment, I get this one:

```
Cannot find module 'material-ui/styles/MuiThemeProvider'.
```

getMuiTheme seems to work.

**Comment by renestalder** [comment]
OK, that's better.

```js
import getMuiTheme from 'material-ui/styles/getMuiTheme';
import {MuiThemeProvider} from "material-ui/styles";
```

**Comment by renestalder** [comment]
So here is a complete solution now:

http://stackoverflow.com/a/37412793/317428

I will give further feedback if something doesn't work.

**Comment by ngbrown** [comment]
@renestalder your problem with `MuiThemeProvider` is part of why I haven't made a pull request yet.  I have to go through all the documentation and make sure everything in the documentation works with the new definitions.  It's a big job.  Check out how long the previous test file was.

**Comment by renestalder** [comment]
@ngbrown Can not thank you enough for your work.

I added it to the project. Until now, it works like expected, but I will not have the chance to test every component.

**Comment by herrmanno** [comment]
@ngbrown Looks quite good.
Would you mind to push your current version (0.15.0) to the types-2.0 branch so it can be consumed via npm?

**Comment by leviathan88** [comment]
can we get a valid link so we can install the typings, the one provided in the stackoverflow question does not work, come on people :dancers:

**Comment by ngbrown** [comment]
TypeScript 2.0 is not released yet.  As far as I know, the types-2.0 branch is under control of Microsoft.  Please communicate with them.

**Comment by leviathan88** [comment]
:D I meant this link is not working : typings install material-ui:github:ngbrown/DefinitelyTyped/material-ui/material-ui.d.ts#material-ui-0-15-0 -SG anymore

how can I install it so I material-ui typings for the never version because the old one is not working
thanks

**Comment by ngbrown** [comment]
@leviathan88 That branch has been merged into the master branch of DefinitelyTyped and material-ui.d.ts can be installed through the normal `tsd` or `typings` methods.

**Comment by leviathan88** [comment]
OK, thanks for that,
the problem now is when I install it I get many errors in the material-ui/index.d.ts files
like this: interface _'EnhancedButtonProps' cannot simultaneously extend types 'HTMLAttributes' and 'SharedEnhancedButtonProps<EnhancedButton>.'_

**Comment by leviathan88** [comment]
I had outdated react typings installed so it was throwing those errors, installing newer version solved the problem, thanks
