### ISSUE TITLE
Definition Request: jsonrpc-serializer

### ISSUE THREAD

**Issue by paolotagliaferri** [DefinitelyTyped/DefinitelyTyped#9368]
Hello, I'm using this JSON-RPC library in many projects:

https://github.com/soggie/jsonrpc-serializer

It would be nice to have the typings for handling JSON-RPC messages.
Do you know if there is some already typed alternative or if it's possible to generate the typings in an easy way?

Thank you very much for your help! :)

**Comment by Akim95** [comment]
@paolotagliaferri check this out https://github.com/Microsoft/dts-gen

**Comment by paolotagliaferri** [comment]
@Akim95 Thanks for sharing that tool, and thanks also for your pull request containing the definition!

**Comment by Akim95** [comment]
Welcome, Pull request already merged maybe you can close this issue. 😄
