### ISSUE TITLE
whatwg-fetch,isomorphic-fetch: BodyInit should accept ArrayBuffer

### ISSUE THREAD

**Issue by tamird** [DefinitelyTyped/DefinitelyTyped#9378]
https://developer.mozilla.org/en-US/docs/Web/API/Request/Request:

> body: Any body that you want to add to your request: this can be a Blob, ArrayBuffer, FormData, URLSearchParams, or USVString object. Note that a request using the GET or HEAD method cannot have a body.

@ryan-codingintrigue: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/whatwg-fetch/whatwg-fetch.d.ts#L82
@toddlucas: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/isomorphic-fetch/isomorphic-fetch.d.ts#L23

**Comment by ryan-codingintrigue** [comment]
Thanks for this, I've added `BodyInit` to the list of supported types. I'm pretty sure we should have URLSearchParams in there too, but not sure if this is part of any TypeScript definition yet.

**Comment by shaunluttin** [comment]
The lack of `URLSearchParams` is a major pain point.

**Comment by toddlucas** [comment]
@shaunluttin Does it make sense for this to be part of the fetch typings or more general browser typings? I'm not sure myself. It is documented in the fetch spec, so maybe.

I don't see that node-fetch supports it (the other half of the isomorphic-fetch implementation). It could be added for the browser half (whatwg-fetch), but users would need to be aware of the context that they're using it in.

I'd be happy to add it if it makes sense. I've just been following what the whatwg-fetch folks have been doing (with consideration given for node-fetch concerns). Which implementation are you using? Does it conform to the interface documented in the fetch spec?

**Comment by shaunluttin** [comment]
> Does it make sense for this to be part of the fetch typings or more general browser typings? 

I don't know either. 

> Which implementation are you using? Does it conform to the interface documented in the fetch spec?

The pain comes when using it with the [`aurelia-fetch-client`. ](https://github.com/aurelia/fetch-client). Maybe there is a way to rely on its types instead. 

> Does it conform to the interface documented in the fetch spec?

I don't know that answer to that either.

**Comment by toddlucas** [comment]
@SaschaNaz, @ryan-codingintrigue Do you have thoughts about where URISearchParams should live? Seems like it might better fit in a browser API typing. But if it's not anywhere, yet, maybe we add it to whatwg-fetch and isomorphic-fetch. What do you think?

**Comment by SaschaNaz** [comment]
I think we should add a new URLSearchParams definition file and then add a reference on this fetch definition.

**Comment by ryan-codingintrigue** [comment]
`URLSearchParams` is not defined within the Fetch standard, it is part of the [URL Standard](https://url.spec.whatwg.org/#urlsearchparams), but Fetch is the only specification to actually use the interface right now.

AFAIK, global definitions like this should be in TypeScript's `lib.d.ts` definition
(See https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L11759)

But they only go into that once Microsoft Edge supports the feature and at present, URLSearchParams [is not present in Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/urlapi/).

**Comment by SaschaNaz** [comment]
Then the right place to open a PR is here: https://github.com/Microsoft/TSJS-lib-generator
