### ISSUE TITLE
Definition Request: firebase v3.0.2

### ISSUE THREAD

**Issue by jamiehumphries** [DefinitelyTyped/DefinitelyTyped#9407]
[Firebase](https://console.firebase.google.com/) have just done a big upgrade to 3.0.2, it would be great to get an update to the type definition.

**Comment by dragouf** [comment]
I'm agree with that. It would be great.

**Comment by ciesielskico** [comment]
+1

**Comment by arahansen** [comment]
Agreed, this would be awesome! Current definitions appear to be incompatible with the revamped service.

**Comment by ivangabriele** [comment]
+1

**Comment by andrey3diq** [comment]
Yes, we definitely need it!

**Comment by dszczyt** [comment]
+1

**Comment by techiebud** [comment]
Here, Here!  Would love a definitions file with this new FireBase 3.0 SDK.    FYI:  Loving the Firebase platform so far.

**Comment by ivanz** [comment]
Heads up that as of version 3.2.1 and above the SDK itself (or at least the NPM package) contains typings already: https://firebase.google.com/support/release-notes/js#wzxhzdk4version_321_-_july_26_2016wzxhzdk5
