### ISSUE TITLE
Property 'pickBy' does not exist on type 'LoDashStatic'

### ISSUE THREAD

**Issue by yahyaKacem** [DefinitelyTyped/DefinitelyTyped#9414]
- yes, I tried using the latest `lodash/lodash.d.ts` file in this repo and had problems.
- yes, I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- yes, I have a question that is inappropriate for [StackOverflow].
- I want to talk about `lodash/lodash.d.ts`.
  - The authors of that type definition are cc/ @stepancar 

I import lodash into my app like this `import * as lodash from 'lodash';` and it worked until I wanted to use the `pickBy` method then I got this error:
>Property 'pickBy' does not exist on type 'LoDashStatic'

I'm using lodash.forIn in the same file only lodash.pickBy gave that error.
How can I fix this?
I already checked the file in the typings folder the `pickBy` function defined is there!!

**Comment by yahyaKacem** [comment]
sorry, turned out that I had to remove it from the `ambientDependencies` in my typings.json and leave it only in the dependencies.

**Comment by gotnull** [comment]
I'm getting this issue and AFAIK I din't have `ambientDependencies` in my typings.json.

I get the exact same error:

> Property 'pickBy' does not exist on type 'LoDashStatic'

**Comment by y471n** [comment]
Same issue as above. Any solutions?

**Comment by ArturFormella** [comment]
The same problem:
```
✗ npm install lodash
✗ npm install @types/lodash
✗ npm run serve
src/modules/utils.ts (58,29): Property 'get' does not exist on type 'LoDashStatic'. (2339)

import * as _ from "lodash";
const browserIpBanana = _.get(request, "body.ip", requestIp);
```

From package.json:
```
    "@types/lodash": "^4.14.161",
    "lodash": "^4.17.20",
```

**Comment by vihardesu** [comment]
same issue
