### ISSUE TITLE
mongoose.d.ts [ts] Type 'Promise<IEntityModel>' is not assignable to type 'Promise<IEntityModel>'.   

### ISSUE THREAD

**Issue by JeffreyChan** [DefinitelyTyped/DefinitelyTyped#9424]
my IEntityModel definition:
`interface IEntityModel extends mongoose.Document {
}`
my method fefinition:
`    create(item: T): Promise<IEnityModel>{
        return this._model.create(item);
    }`
How can I fix this problem?
here is error tips by VSCODE:

> [ts] Type 'Promise<IEntityModel>' is not assignable to type 'Promise<IEntityModel>'.
  Types of property 'then' are incompatible.
    Type '<U>(onFulFill: (result: IEntityModel) => void | U | Promise<U>, onReject?: (err: any) => void | U...' is not assignable to type '{ <TResult>(onfulfilled?: (value: IEntityModel) => TResult | PromiseLike<TResult>, onrejected?: (...'.
      Type 'Promise<any>' is not assignable to type 'Promise<any>'.
        Property 'catch' is missing in type 'Promise<any>'.
(method) mongoose.Model<IEnityModel>.create(doc: Object, fn?: (err: any, res: IEnityModel) => void): mongoose.Promise<IEnityModel> (+3 overloads)

**Comment by vvakame** [comment]
@JeffreyChan please send a pull request. I'll review it.

**Comment by simonxca** [comment]
Hey sorry no one replied. The reason this happens is you're returning an ES6 promise while mongoose returns a mongoose Promise, which are not compatible.

**Comment by simonxca** [comment]
I updated the definitions so you can plug in and use your own promise library by assigning
`type MongoosePromise<T> = your_promise<T>` in your main `.d.ts` file.

Please try the new definitions and open an issue if you have any problems.

**Comment by AnimaMundi** [comment]
I have tried:
```
/// <reference path=".../../../../node_modules/@types/bluebird/index.d.ts" />
type MongoosePromise<T> = Promise<T>;
```
but I keep getting the error: `Duplicate identifier 'MongoosePromise'`.

**Comment by simonxca** [comment]
@AnimaMundi Hmm could you check if there's a folder called `node_modules/@types/mongoose-promise`? If so, delete that folder and see if it works. This is because mongoose references a definition called mongoose-promise which defines `MongoosePromise<T>`. If you install via `typings install dt~mongoose` it doesn't install mongoose-promise automatically. But with `npm install @types/mongoose` it probably does, hence the naming conflict.

**Comment by simonxca** [comment]
I'll have to make some changes for these definitions to work with the new `@types` structure.

**Comment by AnimaMundi** [comment]
Yeah it works when I delete that module and I also had to delete the line `/// <reference types="mongoose-promise" />`. 
It was definitely installed automatically.

To fix this, it would be great if there was some way to explicitly exclude a dependency from being automatically imported in tsconfig without using noResolve and messing up all the other imports at the same time.

If the dependency is removed from the typings themselves, then people will have to manually install mongoose-promise which undoes the work they've done to overcome this.

**Comment by simonxca** [comment]
@AnimaMundi Yup. Using `type MongoosePromise` may not be good for Typescript 2.0 so heads up for upcoming changes, unfortunately some of your code may break. After the changes I'll post a doc here explaining how to use these definitions.

**Comment by AnimaMundi** [comment]
My code has already broken because of other changes so it's cool,
if you want a hand with this I'd be happy to help

**Comment by simonxca** [comment]
@AnimaMundi I have a question where did you find documentation for `npm install @types/mongoose` I tried it and my editor (Visual Studio Code) can't find the definitions, though the code compiles when I run `tsc`.

**Comment by AnimaMundi** [comment]
@simonxca This is because Visual Studio Code is not running Typescript 2.0 by default. You need to manually set the path to the Typescript compiler.

`"typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib"`

You can do it globally with user settings to point to your global installation of Typescript 2.0 or do it on per project with workspace settings and point to a local installation.
Restart the editor after setting that option and it should pick up the definitions properly then.

**Comment by simonxca** [comment]
@AnimaMundi Perfect, it worked! Thank you. That's all I could find too 😕
Well I'll start testing this and see where it goes.

**Comment by simonxca** [comment]
@AnimaMundi Changes are coming soon for Promises. See here: https://github.com/simonxca/DefinitelyTyped/blob/patch-mongoose/mongoose/mongoose.d.ts

I've added a README of how to use the definitions in case there are other changes that affect you. (I don't think so for now). Check out the promise section https://github.com/simonxca/DefinitelyTyped/tree/patch-mongoose/mongoose
