### ISSUE TITLE
React: missing svg foreignObject element definition

### ISSUE THREAD

**Issue by SereznoKot** [DefinitelyTyped/DefinitelyTyped#9481]
- [x] I tried using the latest `react/react-dom.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @pspeter3 @vsiao

**Comment by pspeter3** [comment]
So you want to add this to React DOM?

**Comment by SereznoKot** [comment]
Yeah, I think now with full svg support all  the svg tags should be added
as well...

**Comment by vsiao** [comment]
Full SVG support is available only via `React.createElement`. `React.DOM` exports only factories listed at http://facebook.github.io/react/docs/tags-and-attributes.html#svg-elements

**Comment by vsiao** [comment]
Though if you're using JSX it'll need to be added to the `IntrinsicElements` interface.

**Comment by SereznoKot** [comment]
@vsiao Yeah, exactly, totally forgot to mention JSX, thanks
