### ISSUE TITLE
React-Native promise typings incorrect

### ISSUE THREAD

**Issue by nschurmann** [DefinitelyTyped/DefinitelyTyped#9489]
This should be working:

![screen shot 2016-05-27 at 4 29 13 pm](https://cloud.githubusercontent.com/assets/5099344/15620444/a01cc6c2-2430-11e6-9a17-c7ef8e605f00.png)

After deleting the types for the promises works.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by jokester** [comment]
propose to close this: the unnecessary types got removed in #10264 .
