### ISSUE TITLE
Infinite redirect loop on website

### ISSUE THREAD

**Issue by niedzielski** [DefinitelyTyped/DefinitelyTyped#9499]
Visiting http://definitelytyped.org/tsd/ either directly, by tapping TSD on the http://definitelytyped.org/ homepage, or through Google causes an infinite redirect loop. Here is the output from Chromium and Firefox (both with cookies enabled):

> The tsdpm.org page isn’t working
> 
> tsdpm.org redirected you too many times.
> Try:
> Reloading the page
> Clearing your cookies
> ERR_TOO_MANY_REDIRECTS

---

> The page isn't redirecting properly
> 
> Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
> 
> This problem can sometimes be caused by disabling or refusing to accept cookies.
>

**Comment by vvakame** [comment]
thank you for your reports.
https://github.com/DefinitelyTyped/definitelytyped.github.io/issues/51
