### ISSUE TITLE
It would be great if there will be typings of infoBox.js and Rich-marker.js

### ISSUE THREAD

**Issue by Sireini** [DefinitelyTyped/DefinitelyTyped#9505]
It will be great if there where typings of these two libraries in combination with: https://github.com/SebastianM/angular2-google-maps

Because the infoBubble from here is not working because it has no exported members "Map", "Marker", "LatLng"

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by jakebailey** [comment]
This package is in TS upstream.
