### ISSUE TITLE
highcharts.d.ts accessing formatter object

### ISSUE THREAD

**Issue by LithMage** [DefinitelyTyped/DefinitelyTyped#9533]
Hi,

question concerns formatter at
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/highcharts/highcharts.d.ts#L5237 

normaly you would be able to assign to it custom formatter (callback function within wich we could access through 'this' x, y, series variables) http://plnkr.co/edit/VkhPpxKlRtHKEyg2t5TS?p=preview sample of how i go about it at the moment. how could i do that within typescript as you can see my current solution involves pure JavaScript?

**Comment by vvakame** [comment]
cc/ @damianog @baltie

**Comment by damianog** [comment]
Hi @LithMage 

this issue is by design, due the fact that highcharts is a pure javascript library.
As they explain in the API documentation http://api.highcharts.com/highcharts#tooltip.formatter you could understand that **this** is scoped to the point object.

**Comment by LithMage** [comment]
thanks @damianog i will just use pure JavaScript for this part then :)

**Comment by damianog** [comment]
@vvakame  consider #9533 closed.
