### ISSUE TITLE
restangular IProvider does not support method chaining

### ISSUE THREAD

**Issue by mickelus** [DefinitelyTyped/DefinitelyTyped#9543]
- [x] I tried using the latest `restangular/restangular.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [x] I want to talk about `restangular/restangular.d.ts`.
- The authors of that type definition are cc/ @borisyankov 

Most methods on the RestangularProvider object returns itself to allow for method chaining, this is not reflected on the IProvider interface as most of its methods return void.

**Comment by dszczyt** [comment]
+1

**Comment by vvakame** [comment]
please send a pull request. I'll review it.
