### ISSUE TITLE
Mongoose definitions latest version

### ISSUE THREAD

**Issue by tarurar** [DefinitelyTyped/DefinitelyTyped#9547]
Hi guys, any plans to update mongoose definitions to the latest version? It seems current definitions is out of date since there are mongoose 4.4.x versions. Current definition is related to 3.8.5 version of mongoosejs.

**Comment by simonxca** [comment]
@tarurar currently working on an updated version here:
https://github.com/simonxca/DefinitelyTyped/blob/mongoose4/mongoose/mongoose.d.ts
