### ISSUE TITLE
Provide additional Error properties for Node.js

### ISSUE THREAD

**Issue by miqid** [DefinitelyTyped/DefinitelyTyped#9568]
Hello there,

I'm trying to access [`Error.stackTraceLimit`](https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_stacktracelimit) in an application I'm building and the TypeScript compiler is barking at me because it seems like the Node.js type definitions don't cover it. I've currently got a simple workaround by defining an interface which `ErrorConstructor` extends from to include this property. On that note, [`Error.captureStackTrace()`](https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_capturestacktrace_targetobject_constructoropt) doesn't appear to be covered either.

I was wondering if this is something that should be included in `node.d.ts`. I couldn't find any previous discussion on this property via search, so I thought I'd raise the question. I'm also relatively new to the TypeScript ecosystem, so pardon the question if it's silly.

I'm also happy to try make a pull request if it turns out being something to add.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by vvakame** [comment]
by #9618 👍
