### ISSUE TITLE
AngularJS IComponentOptions require does not accept string or array

### ISSUE THREAD

**Issue by dutchmega** [DefinitelyTyped/DefinitelyTyped#9571]
AngularJS/angular.d.ts, interface IComponentOptions, attribute require.
require?: string | string[] | {[controller: string]: string};

string and string[] are not accepted with an AngularJS component, as it required object mapping. Giving it anything else actually does nothing.

Correct example that uses object syntax which gives error due missing required component:
https://jsfiddle.net/zz21eh4k/11/

Incorrect example that uses array syntax which does nothing:
https://jsfiddle.net/zz21eh4k/12/

Documentation AngularJS: https://docs.angularjs.org/guide/component#intercomponent-communication

**Comment by vvakame** [comment]
please send a pull request.
