### ISSUE TITLE
kendo-ui.d.ts Circle class doesn't support parameterized constructor

### ISSUE THREAD

**Issue by pwombwa** [DefinitelyTyped/DefinitelyTyped#9580]
http://docs.telerik.com/kendo-ui/api/javascript/geometry/circle#kendogeometrycircle Says that the Circle class constructor should accept the following arguments :- 
1. **center : kendo.geometry.Point** 
                The location of the circle center.
2. **radius : Number**
                The radius of the circle.

**Comment by vvakame** [comment]
cc/ @tsvetomir

**Comment by tsvetomir** [comment]
The constructors were documented in telerik/kendo-ui-core@c04d79871c75987aaf05ace08b7cbb0b2335c1a1

The generated constructor definitions will be included in the next release and I'll merge them here.
