### ISSUE TITLE
redux-promise: Argument of type 'Promise' is not assignable to parameter of type 'Middleware'.

### ISSUE THREAD

**Issue by ndarilek** [DefinitelyTyped/DefinitelyTyped#9585]
- [x ] I tried using the latest `redux-promise/redux-promise.d.ts` file in this repo and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] I want to talk about `redux-promise/redux-promise.d.ts`.
  - The authors of that type definition are cc/ @molekilla

Getting this error:

```
client/index.tsx (21, 5): Argument of type 'Promise' is not assignable to parameter of type 'Middleware'.
  Type 'Promise' provides no match for the signature '<S>(api: MiddlewareAPI<S>): (next: Dispatch<S>) => Dispatch<S>'
```

This is with Meteor and the barbatus:typescript package. I don't know what TSC it is using but have no reason not to think it's latest stable.

I've looked at the tests and don't see any reason this shouldn't work. Here is the relevant portion of my code. I'm trying to build up a Meteor Redux TypeScript demo so it's a bit bare:

```
import {routerMiddleware, routerReducer, syncHistoryWithStore} from "react-router-redux"
import {applyMiddleware, combineReducers, createStore} from "redux"
import promise from "redux-promise"

const store = createStore(
  combineReducers({
  }),
  applyMiddleware(
    promise,
    routerMiddleware(browserHistory)
  )
)
```

Thanks.

**Comment by molekilla** [comment]
take a look here, looks related, will try it too
https://github.com/gaearon/redux-thunk/issues/35

**Comment by ndarilek** [comment]
FWIW, I tried `import promise = require("redux-promise")`, no change.

**Comment by molekilla** [comment]
it loads, but unable to fix Typescript issues, it did work with typescript < 1.8

https://github.com/molekilla/rutha-2016/commit/b93d357d8e4c386863a73889beca49e59437ad6e

**Comment by edgardz** [comment]
Worked for me using 
```
const promise = require("redux-promise");
const rootReducer = combineReducers({
  ...
});
const enhancer = compose(
  applyMiddleware(promise),
  ...
);
const store   = createStore(rootReducer, {}, enhancer);
```

**Comment by inlightmedia** [comment]
I got this error (redux-promise: Argument of type 'Promise' is not assignable to parameter of type 'Middleware'. ) when importing using:

`import * as promise from 'redux-promise'. `

When I remove the "* as" the error went away.

I'm using TS 3.4.5 and I have allowSyntheticDefaultImports set to true.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
