### ISSUE TITLE
Lodash FP params aren't typed properly

### ISSUE THREAD

**Issue by MikaAK** [DefinitelyTyped/DefinitelyTyped#9589]
- [x] I tried using the latest `lodash/lodash.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `lodash/lodash.d.ts`.
  - The authors of that type definition are cc/ @bczengel @stepancar @chrootsu 

I'm using lodash v4.13.1 and I'm noticing the fp module just points to `_`. This is no longer the case if it was in the past as the param order is swapped for some things. I would gladly make a PR if someone can point me in the right direction. 

Currently, it will show something like `get('prop', item)` as being in the wrong order but that is not the case if you [try it out](https://tonicdev.com/57095f6fd2703c1100cc5b4f/5757a90193e6131300920250) for yourself. 

Could someone tell me what to do to submit a PR or help get this updated!

**Comment by TeamworkGuy2** [comment]
As you probably see, DefinitelyTyped is completely community driven, check out some of the closed pull requests for the general format of how to submit one, also check out the [Contribution guide](http://definitelytyped.org/guides/contributing.html). 

My workflow is to fork the DT repo, create a patch for the definition which passes the existing tests and fixes the type error I found, test that it compiles without error (see Contribution guide), push to my github and just use github to create the pull request.  You'll see a pull request template when you go to create the pull request to remind you if you missed anything. 

It's pretty straightforward and other people will patch your work if you don't cover all the corner cases, that's what's great about DT.

**Comment by frederickfogerty** [comment]
@MikaAK did you make any progress on this?

**Comment by nahuel** [comment]
this is related to #7896 (wrongly closed), the re-export of lodash functions as lodash/fp is totally incorrect.
