### ISSUE TITLE
chart.d.ts(chart.js) doesn't work for the last chart.js

### ISSUE THREAD

**Issue by John0King** [DefinitelyTyped/DefinitelyTyped#9608]
chart.d.ts(chart.js) doesn't work for the last chart.js

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by ulikoehler** [comment]
There is no `chart.d.ts` in the `chart.js` folder any more - instead there is `index.d.ts` which seems to work well with the newest version of `chart.js` (I have only tested a few features, so please provide an error description if it still doesn't work for you).

Can we close this issue as it no longer reflects the current state of the repository?
