### ISSUE TITLE
Jquery.slimscroll.d.ts addition

### ISSUE THREAD

**Issue by mbeauchamp7** [DefinitelyTyped/DefinitelyTyped#9610]
- [ ] I tried using the latest `jquery.slimscroll.d.ts` file in this repo and had problems.

I had an angular directive that was using the option `{destroy:true}` and as I was converting my code to TypeScript, I ran into this "missing" option. Maybe I'm not using it correctly...

I added this to `interface IJQuerySlimScrollOptions`

``` javascript
// used to destroy the slimscroll    
    destroy?: boolean;
```

I think the owner is @vvakame 

Thanks

**Comment by vvakame** [comment]
cc/ @chintans
