### ISSUE TITLE
Making node.d.ts usable for amd only projects

### ISSUE THREAD

**Issue by blendsdk** [DefinitelyTyped/DefinitelyTyped#9639]
I would like to have intellisense for built-in nodes modules when using amd (--module "amd") compilation.
This way I can state `var fs = require('fs')` and have the IDE suggest options to me. 

I was thinking to provide an interface to solve the problem like:
```
/// in node.d.ts
interface fs:NodeJSModuleFunction {
     realpathSync(path: string | Buffer, cache?: { [path: string]: string }): string;
}
```

and use the above like:
```
var fs:NodeJSModuleFunction = require("fs");
``` 

Would this make sense? Is there anyone else who wishes to have the same functionality?
I personally need this because I am compiling all my sources into a single file and simple cannot use
`import` to use the built-in modules 

Let me know if there are any objections or reservations. If not then I would like to give try making the d.ts file for amd and perhaps call it node-amd.d.ts

Thanks

**Comment by vvakame** [comment]
You can use `import fs = require("fs");`. It is not ES6 import syntax.

**Comment by blendsdk** [comment]
After re-reading my original  question and doing some research, it is clear to be that the way proposed is not really going to work, thank you.
