### ISSUE TITLE
definitelytyped.org/tsd redirects to invalid page

### ISSUE THREAD

**Issue by SaschaNaz** [DefinitelyTyped/DefinitelyTyped#9670]
Redirection goes to http://tsdpm.org/ and then http://ww2.tsdpm.org/?folio=7POYGN0G2 which says 

>This domain name expired on Jun 10 2016 11:52AM
>Click here to renew it.

**Comment by chaseoli** [comment]
+1

**Comment by vvakame** [comment]
see https://github.com/DefinitelyTyped/definitelytyped.github.io/issues/51
