### ISSUE TITLE
Can We Stick to a Common Definition Name Casing?

### ISSUE THREAD

**Issue by TeamworkGuy2** [DefinitelyTyped/DefinitelyTyped#9716]
I've noticed a few new definitions aren't following the accepted[1] lower-dash-casing used by the previous ~1800 definitions, specifically: 
- CybozuLabs-md5 (@pine)
- DataStream.js (@tatx)
- FileSaver (@cyrilschumacher) - npm 'file-saver'
- Finch (@DavidSichau) - npm 'finchjs'
- Headroom (@hakubo)
- HubSpot-pace (@borislavjivkov)
- JSONStream (@Bartvds) - npm 'JSONStream'
- PayPal-Cordova-Plugin (@Justin-Credible)

When I started using DefinitelyTyped definitions, I thought it was a little odd that some library names where different from their 'official' name to match the lower-dash-casing convention, but it makes a lot of sense now that I've used DT for a while.  For example, when I'm adding JQuery typings to a project I don't need to remember if it's 'JQuery' or 'jQuery' or 'Jquery', I know everything in DT is lower case, so it must be 'jquery'.  This lightens the mental complexity. 

I think the current 1800 projects make a good precedent for sticking with one convention. 
Would you guys (DT contributors/admins and community feedback) be okay with pull requests renaming the above mentioned definitions using the common dash-casing naming convention? 

---

[1]The DT [Contribution guide](http://definitelytyped.org/guides/contributing.html) isn't explicit about using a specific convention. It does recommend lowercase:

> **Naming the file**
> Try to use a **simple lowercase identifier** as name of the definition file, like **library.d.ts** or **node-hoge.d.ts**. To keep naming conflicts to a minimum please use the package name as used in the npm package registry. The only exception here should be NuGet / Windows oriented code as they use a camel-case convention.
> [...]
> **Location**
> The typing must be placed in a folder. The folder name must be similar to library name.
> Example: **qunit.d.ts** in in a folder named **qunit**

**Comment by yeiniel** [comment]
I think i'm experiencing some problems with this. I'm trying to use typescript@next and the JSONStream package. I found the @types/jsonstream and installed. Now if i import JSONStream the compailer says it doesn't find a definition for it and if i import jsonstream Node throw an exception running the code because the jsonstream package is not found. Any idea?

**Comment by mhegazy** [comment]
The name of the folder should match the name of the npm package for the reason @yeiniel explained. I would consider any declaration folder that does not match its npm package a bug that should be fixed. please feel free to send PRs for these, and i will merge them.

**Comment by yeiniel** [comment]
I would like to hekp you @mhegazy  with the PR but i don't found where to modify the package.json used to upload @types/jsontream to NPM in order to fix the problem.

**Comment by mhegazy** [comment]
The packages are published from the types-2.0 branch, using the [types-publisher](https://github.com/Microsoft/types-publisher) tool. It should be sufficient to change the folder name, and the publisher should pick these up. so just rename the folder on the branch, and make sure all the other packages that reference it use the new name in `/// <reference types`

We also need to file a bug for deprecating the other packages, and adding a reference to the new ones (e.g. `angularjs`). for now we do these manually. so i would file a bug for each renamed package.

**Comment by yeiniel** [comment]
The folder name is correct. Is the package publisher on NPM the one with the wrong name.

**Comment by mhegazy** [comment]
> The folder name is correct. Is the package publisher on NPM the one with the wrong name.

which package is this specifically?

**Comment by yeiniel** [comment]
The JSONStream package is the one. In the DefinitelyTyped repo the folder
name is "JSONStream" but the package published in NPM is
"@types/jsonstream". I'm aware that the same author of JSONStream has
published the same package on NPM with the name "jsonstream". But the
latter seems to not be the canonical one because it's more outdated.

Yeiniel Suarez Sosa
Automatic Control Engineer

**Comment by mhegazy** [comment]
this is gonna be a problem then.. not sure what we can do. new NPM packages can not have uppercase letters in their names. the original package has been shipped already. May be we can make the package lookup in the compiler always look for the lower case name of the type package..

**Comment by mhegazy** [comment]
@RyanCavanaugh though?

**Comment by RyanCavanaugh** [comment]
> May be we can make the package lookup in the compiler always look for the lower case name of the type package.

Seems reasonable

**Comment by mhegazy** [comment]
Filed https://github.com/Microsoft/TypeScript/issues/9824 to track this.

**Comment by DanielRosenwasser** [comment]
The package for Polymer is spelled with an uppercase `P`, so I don't know whether that's the best idea. Why can't we just redirect the packages as appropriate?

**Comment by mhegazy** [comment]
> The package for Polymer is spelled with an uppercase P,

I was talking about `@types` packages, not all npm packages.

> Why can't we just redirect the packages as appropriate?

what do you mean redirect?

**Comment by yeiniel** [comment]
@mhegazy i see you closed an issue on the typescript compiler repo. That means there is a solution for this one? If so how can be tested?

**Comment by Kaffiend** [comment]
in the case of file-saver npm saves the types in "@types/filesaver" but the modules aren't found with the current file-saver lib until you manually rename it to "@types/file-saver".

**Comment by DanielRosenwasser** [comment]
We'd take a PR @Kaffiend

**Comment by Kaffiend** [comment]
ill try to get to that this evening.

**Comment by tomwheyprotein** [comment]
Is this issue closed?  There is a "forceConsistentCasingInFileNames": false property in the tsconfig.json compilerOptions, which solves my compile errors for the casing difference between JSONStream and @types/jsonstream.

**Comment by yoshigev** [comment]
Another option for solving this is using npm aliases:
```
npm i @types/JSONStream@npm:@types/jsonstream
```
