### ISSUE TITLE
Angularjs - `IComponentController.$postInit` should be `IComponentController.$postLink`

### ISSUE THREAD

**Issue by mickeyvip** [DefinitelyTyped/DefinitelyTyped#9717]
I want to talk about `DefinitelyTyped/angularjs.d.ts`.

There seems to be the wrong name for `IComponentController.$postInit`, it should be 

`IComponentController.$postLink`

Thank you.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by mickeyvip** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9816

Thank you
