### ISSUE TITLE
d3 type defs problems

### ISSUE THREAD

**Issue by basters** [DefinitelyTyped/DefinitelyTyped#9728]
Hi everyone. I tried using the latest 
**registry:npm/d3#3.0.0+20160211003958** and **registry:dt/d3#0.0.0+20160614091820** 
but I get a type error then I try to implement simple zoom functions.

For example:

`var x = d3.time.scale()
  .domain([new Date('2016-06-10'), new Date('2016-06-25')])
  .rangeRound([0, 1000]);`

And I get error about error types for domain...

> Argument of type 'Scale' is not assignable to parameter of type 'Scale'.
> 
> Types of property 'domain' are incompatible.
> 
> Type '{ (): Date[]; (dates: number[]): Scale; (dates: Date[]): Scale; }' is not assignable to type '{ (): number[]; (values: number[]): Scale; }'.
> 
> Type 'Date[]' is not assignable to type 'number[]'. Type 'Date' is not assignable to type 'number'.

But If we look d3 typings

```
domain(): Date[];
domain(dates: number[]): Scale<Range, Output>;
domain(dates: Date[]): Scale<Range, Output>;
```

domain can take Date array!
If we disable types, then all works fine.

The next example:

```
var drag = d3.behavior.drag()
  .on('drag', function (d) {
    d3.event.sourceEvent.stopPropagation();
  })
  .on('dragstart', function () {
    //
  });
```

I get error about:

> Property 'sourceEvent' does not exist on type 'Event | BaseEvent'.

But If we look in types again:

`export var event: Event | BaseEvent;
`
and

```
interface BaseEvent {
     type: string;
     sourceEvent?: Event;
 }
```

And the last example: 

```
var xScale = d3.time.scale().domain([new Date('1-1-2014'), new Date('1-31-2014')]).range([0, width]);
var zoom = d3.behavior.zoom().scaleExtent([.025, 1]).x(xScale);
```

> Argument of type 'Scale<number, number>' is not assignable to parameter of type 'Scale'
> Type '{ (): Date[]; (dates: number[]): Scale<number, number>; (dates: Date[]): Scale<number, number>; }' is not assignable to type '{ (): number[]; (values: number[]): Scale; }'
> Type 'Date[]' is not assignable to type 'number[]'

if you believe the documentation, it should work fine - https://github.com/d3/d3/wiki/Zoom-Behavior

I also have a simple example - https://github.com/wis-ekubesh/ts-d3-error-example you look how it works

And the original code without typescript (also work fine) http://codepen.io/donyainman/pen/GpwJyM

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by tomwanzek** [comment]
As part of some legacy D3v3 issue clean-up, can this issue be please closed?

D3v4 has been released and supported with actively maintained definitions for several months now, so it would be great to have only current issues open for clarity.

Thanks in advance!

cc @gustavderdrache @andy-ms
