### ISSUE TITLE
Export type RouteProps

### ISSUE THREAD

**Issue by ephoton** [DefinitelyTyped/DefinitelyTyped#9730]
I tried using the latest `react-router/react-router.d.ts` file in this repo and had problems.
Type of Route is not exported, we need that type when using [Dynamic Routing](https://github.com/reactjs/react-router/blob/master/docs/guides/DynamicRouting.md#dynamic-routing)

**Comment by vvakame** [comment]
please send a pull request. I'll review it.
cc/ @sergey-buturlakin @mrk21@vasek17 @ngbrown

**Comment by ephoton** [comment]
@vvakame  Same as [issue 9731](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9731) which was already resolved.
