### ISSUE TITLE
Express req.param() deprecated

### ISSUE THREAD

**Issue by Aides359** [DefinitelyTyped/DefinitelyTyped#9754]
- [x] I want to talk about `express/express.d.ts`.
  - The authors of that type definition are cc/ @borisyankov 

According to the [express documentation](http://expressjs.com/de/api.html#req.param) `req.param(name [, defaultValue])` is deprecated.

> Deprecated. Use either req.params, req.body or req.query, as applicable.

In some situations however it might still be suitable

> [...] should be favoured for clarity - unless you truly accept input from each object.

Nonetheless I think it would be a good idea to add the `@deprecated` description to the function definition (keep the old or replace it?).

What is your opinion on that? I wouldn't mind creating a PR if the change is appropriate.

**Comment by mhegazy** [comment]
The declaration should not be removed as long as it is available. Adding `@deprecated` comment would be my recommendation.
