### ISSUE TITLE
ChartJS isn't up to date

### ISSUE THREAD

**Issue by aclerbois** [DefinitelyTyped/DefinitelyTyped#9784]
Hi everybody,

I would like try to use chartjs with TypeScript but it's impossible because the latest version are incompatible with the latest typings file present in our repository.

Example, I would like use a line chart with 0 of LineTension and the property isn't present in our typing file.

In addition, pl-ease could you add the version of Chartjs for the current typing file available.

Here the form :
- [X] I tried using the latest `chartjs/chart.d.ts` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] I want to talk about `chartjs/chart.d.ts`
  - The authors of that type definition are cc/ @....

Sincerely,

Adrien C.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by negyxo** [comment]
Are current typings up to date?

I was trying to use the latest chart.js lib, but it seems that constructor definition is not correct in the current typings. Per this [stackoverflow comment](https://stackoverflow.com/questions/32468818/unable-to-draw-method-in-chart-js-v2-cant-be-found) from chart.js v2.0.0, there are no more dedicated  methods for each chart type, this is now passed through constructor.
