### ISSUE TITLE
Require? twice in angular type definition

### ISSUE THREAD

**Issue by kristho91** [DefinitelyTyped/DefinitelyTyped#9830]
- [x] I tried using the latest `angular/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `angular/index.d.ts`.

It seems that after the latest update, the interface IComponentOptions contains "require?" twice, but with two different type-definitions:

```
/**
  * Define object mapping to other directive or component required controllers.
  */
require?: any;
```

and

`require?: {[controller: string]: string};`

And now I can't build my project :(

**Comment by ramseyfeng** [comment]
Ran into the same issue.
Temporary fix by setting the version of angular to an legacy one:

    typings install dt~angular@1.4.0 --global --save

**Comment by Nagogus** [comment]
[https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d1c9da62053609b84f5052bbeaf2bf15ff240c70](url) 
Now it is fixed

**Comment by mhegazy** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9831
