### ISSUE TITLE
colors module ES6 errors

### ISSUE THREAD

**Issue by raijinsetsu** [DefinitelyTyped/DefinitelyTyped#9844]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

The type definitions are causing TS2300/Duplicate identifier errors due to collision with ES6. Exact output is:

```
514     bold(): string;
        ~~~~

node_modules/typescript/lib/lib.es6.d.ts(514,5): error TS2300: Duplicate identifier 'bold'.


109     bold: string;
        ~~~~

typings/globals/colors/index.d.ts(109,5): error TS2300: Duplicate identifier 'bold'.
```

It appears that the tscparams file for this is preventing the error from appearing in the unit tests. According to the package's documentation, using the 'colors/safe' module would not override the string classes native methods and would do away with this error. But, as the definitions do not have this sub module, Typescript does not allow the import of 'colors/safe'.

**Comment by raijinsetsu** [comment]
I plan on writing a PR for this but I have never had to write a definition that included a sub-module.

**Comment by itbrandonsilva** [comment]
I'm running into this issue as well. Have you discovered anything new around this?

**Comment by raijinsetsu** [comment]
No. I haven't been able to break the module down. Right now, I'm running
with a custom definition.

**Comment by Dante-101** [comment]
This error resurfaced in our systems after upgrading to Typescript 2.7.

```
node_modules/@types/colors/index.d.ts(118,9): error TS2717: 
Subsequent property declarations must have the same type.
Property 'bold' must be of type '() => string', but here has type 'string'.
```

Any ideas how to fix this? I am importing the colors using `import * as colors from 'colors/safe'`

**Comment by DABH** [comment]
Weird, I just spent some time trying to repro this, and while I can get the ES6 bold() in the node console, it doesn't seem to detect it using tsc (i.e. I can't repro the error).  The point is String.bold() is deprecated and so this shouldn't be a conflict at some point...

@Dante-101 Can you provide a MWE to repro this, so we can figure out best way to solve?

Types for colors are moving to https://github.com/Marak/colors.js/tree/develop so feel free to open a new Issue there and we'll investigate.  Thanks!

**Comment by Dante-101** [comment]
A bit late but here it is.
https://github.com/Dante-101/colors-ts-def-mwe

`tsc` returns this error. I am using Typescript 2.7.2
`node_modules/@types/colors/index.d.ts(118,9): error TS2717: Subsequent property declarations must have the same type.  Property 'bold' must be of type '() => string', but here has type 'string'.`

**Comment by DABH** [comment]
Thanks @Dante-101 !  Please follow the discussion here: https://github.com/Marak/colors.js/issues/168

I’ll give my tentative “fix” a try with your MWE soon-ish...

**Comment by DABH** [comment]
Please close this issue -- it appears to be solved as of `colors@1.2.0` (colors bundles its own types now, `@types/colors` not required).  Thanks!

**Comment by samal84** [comment]
Can confirm this is fixed in never versions.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
