### ISSUE TITLE
Missing withRouter definition on react-router.

### ISSUE THREAD

**Issue by galvesribeiro** [DefinitelyTyped/DefinitelyTyped#9845]
- [X] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

The react-router definitions lack the definition of [`withrouter(component)](https://github.com/reactjs/react-router/blob/v2.5.1/modules/withRouter.js#L9) and due to the lack of it, tons of other router-based features are inaccessible thru TypeScript. Can it be added?

Thanks

**Comment by galvesribeiro** [comment]
Just for the sake of tests, manually changed the index.d.ts to add this:

```
declare module "react-router/lib/withRouter" {
    export default function withRouter<T>(wrappedComponent: T):ReactRouter.Component ;
}
```

**Comment by emzero** [comment]
I've created a [PR ](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9851) with it. Waiting approval.

**Comment by frederickfogerty** [comment]
`withRouter` is available on the modular type definitions at https://github.com/typed-typings/npm-react-router

**Comment by pocesar** [comment]
withRouter is returning `React.ComponentClass<any>`, makes it impossible for using inside `render` of `Route`

**Comment by darrenhaken** [comment]
@pocesar is there any update on getting it to work with types?

**Comment by pocesar** [comment]
@darrenhaken I'm using a typecast the withRouter result like `withRouter(Class) as React.ComponentClass<ClassProps>`

**Comment by darrenhaken** [comment]
@pocesar do you mean like this?
`withRouter(connect(mapStoreStateToProps, mapDispatchToProps)(Component)) as React.ComponentClass<AllProps>;`

**Comment by guilhermehubner** [comment]
I've found a way to solve this problem as you can see below:

```ts
type OwnProps = RouteComponentProps<{id: number}>;

const mapStateToProps = (state: GlobalStateType, ownProps: OwnProps): StateToPropsType => ({
        id: ownProps.match.params.id
});

const mapDispatchToProps = (dispatch: DispatchType): DispathToPropsType => ({
    ...
});

export default withRouter(connect<StateToPropsType, DispathToPropsType, OwnProps> (
    mapStateToProps,
    mapDispatchToProps
)(MyPage));
```

In router: 
```ts
<Provider store={store}>
   <BrowserRouter>
      <Switch>
         <Route path="/:id(\d+)" component={MyPage} />
      <Switch>
  <BrowserRouter>
</Provider>
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
