### ISSUE TITLE
No typings for Twilio

### ISSUE THREAD

**Issue by AlexLeung** [DefinitelyTyped/DefinitelyTyped#9888]
Could we have typing definitions for the Twilio API? https://www.twilio.com/docs/libraries/node

I could start on this myself, but the definitely typed contribution guide is not very clear on how to add new definitions. Do I fork then create a sub-folder?

**Comment by underscorebrody** [comment]
Yes, you would fork and then create a folder for `twilio`

**Comment by nickiannone** [comment]
I'm working on one myself right now; follow along at nickiannone/DefinitelyTyped.

**Comment by nickiannone** [comment]
This has been approved and merged into master. Requesting that this issue be closed.

**Comment by vvakame** [comment]
by #10528
