### ISSUE TITLE
ExpressJs: using error handling middleware

### ISSUE THREAD

**Issue by tarurar** [DefinitelyTyped/DefinitelyTyped#9891]
- [x] I tried using the latest `express-serve-static-core\express-serve-static-core.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Is seems that this type definition has some problems with using error handler as a middleware. Just have a look at the screenshot below:

![cmixnzgwgaa56ff](https://cloud.githubusercontent.com/assets/142044/16481718/c642bd8c-3ebd-11e6-86de-4c0b96f9ad90.jpg)

My first idea was maybe there is something wrong with the compiler itself, but please have a look at @basarat's comment:

> seems like an express definition problem. Compilers deleting the wrong overload
- The authors of that type definition are cc/ @vvakame, @flcdrg

**Comment by flcdrg** [comment]
My changes were just to remove a circular dependency between express.d.ts and serve-static.d.ts (by extracting the common bits into express-serve-static-core.d.ts. I assume you have express and serve-static already added.

Other than that, it may be that as @basarat says, the definitions themselves need updating.

**Comment by tarurar** [comment]
> Other than that, it may be that as @basarat says, the definitions themselves need updating.
That is what I am talking about.

**Comment by xavdid** [comment]
I'm having the same issue.

`app.use((err, res, req, next) => {})` gives the same error as above (pasting so it's better searchable): 

```
Argument of type '(err: Request, req: Response, res: NextFunction, next: any) => void' is not assignable to parameter of type 'PathParams'.
  Type '(err: Request, req: Response, res: NextFunction, next: any) => void' is not assignable to type '(string | RegExp)[]'.
    Property 'push' is missing in type '(err: Request, req: Response, res: NextFunction, next: any) => void'.
```

Is there an official maintainer of the express typings or is it up to one of us to make a PR?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
