### ISSUE TITLE
jquery.d.ts is missing event.currentTarget

### ISSUE THREAD

**Issue by JodiWarren** [DefinitelyTyped/DefinitelyTyped#9899]
- [x] I tried using the latest `jquery/jquery.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `jquery/jquery.d.ts`.

---

There is no definition for event.currentTarget. This means that TypeScript thinks it's an EventTarget, when it should be an element.

See jQuery API: https://api.jquery.com/event.currentTarget/

---

My personal use case:
```
event.currentTarget.classList.toggle('active');
```
is rejected with `error TS2339: Property 'classList' does not exist on type 'EventTarget'.`

**Comment by vvakame** [comment]
@johnnyreilly ?

**Comment by johnnyreilly** [comment]
Do you want to raise a PR for this? Seems legitimate that we should update
