### ISSUE TITLE
dt~react-router error TS2503: Cannot find namespace 'HistoryModule'.

### ISSUE THREAD

**Issue by AlexLeung** [DefinitelyTyped/DefinitelyTyped#9928]
I tried to download the React-Router typings definition using `typings install --save --global dt~react-router`, but my code will still not compile because the HistoryModule referenced by typings/globals/react-router/index.d.ts does not exist.

Earlier I was recommended to go with `typings --save react-router`, but although this includes the dreaded "HistoryModule", it is missing other key typing definitions for properties which the React Router elements typically have (missing onChange property of Route element). Is there something else from typings that I need to download to get this to work? Also, how can I tell if I need to download multiple other global typings definitions to get a different one to work, because I'm not aware of any way and the typings command does not appear to understand if a global typing definition depends on other modules.

**Comment by mhegazy** [comment]
@blakeembrey any ideas about the cause of this?

**Comment by blakeembrey** [comment]
The CLI tells you that there's been references stripped, it is up to the user to make sure they get installed. This is because references are not an adequate dependency system.

![image](https://cloud.githubusercontent.com/assets/1088987/16542386/941b6450-405a-11e6-88e7-fc7d2a6b88e4.png)

```
typings install dt~react-router/history --global
```

**Comment by AlexLeung** [comment]
Thanks! Now I seem to be getting a different error: `(109,1): error TS2309: An export assignment cannot be used in a module with other exported elements.`

**Comment by AlexLeung** [comment]
This seems to be the solution. Thanks! It seemed to be conflicting with the `dt~history` definition, but after removing that, everything works fine.

**Comment by giterrish** [comment]
Is it possible to issue a warning rather than info?
Maybe "you may need to install ..."

**Comment by mayerwin** [comment]
Why is this issue closed? This is a rather confusing requirement.

**Comment by andfaulkner** [comment]
The above answer worked for me as well, no problems.

@mayerwin: I think it closed because @blakeembrey's solution works consistently?

**Comment by mayerwin** [comment]
This is a workaround, I wouldn't say it allows the issue to be closed. What we need is react-router/history to be automatically installed upon installing react-router, or the whole thing to be packaged in a single type definition.

**Comment by blakeembrey** [comment]
I believe on the DefinitelyTyped side it should be resolved with `types-2.0` as they now have a dependency system that isn't references. If it doesn't work with `@types/react-router`, make a PR to `types-2.0` to fix it.

**Comment by bofcarbon1** [comment]
Just learning React but and this idea of a history module requirement to do routing I do not like. Sounds like more state management confusion to me. I'm leaning toward MobX over Redux because I don't like be bossed around with that immutable outer layer state store. I'm trying to get get an example I found on github to run but big problems with dependencies and built in requirements that I don't have to worry about in Angular.  grrrrr
