### ISSUE TITLE
weird error when installing @types/body-parser

### ISSUE THREAD

**Issue by gdi2290** [DefinitelyTyped/DefinitelyTyped#9929]
maybe body-parser deps needs to be updated
<img width="967" alt="screen shot 2016-07-02 at 12 14 43 am" src="https://cloud.githubusercontent.com/assets/1016365/16539000/113f6d44-3fea-11e6-9e28-d14dd7a04757.png">

current workaround
`"@types/body-parser": "github:gdi2290/types-body-parser",`
https://github.com/gdi2290/types-body-parser

**Comment by mhegazy** [comment]
We had some issues publishing over the weekend. should be fixed now.
