### ISSUE TITLE
How to use tooltip object

### ISSUE THREAD

**Issue by r0lan2** [DefinitelyTyped/DefinitelyTyped#9960]
Hi,
I am using the version  2.3.3 of the file highcharts.d.ts  with Highcharts JS v4.2.5 and transpaling with version 1.8.34 of Typescript. The thing is that I am trying follow an example about how to click event witth the tooltip of Highchart. The example in JS is working here: http://jsfiddle.net/2swEQ/2/

From the example above I can' find the way to translate the next line to TypeScript:

`this.myTooltip = new Highcharts.Tooltip(this, this.options.tooltip);`

I tried to do something like this:

`public highchartTooltip : HighchartsTooltipOptions;
this.myTooltip = new self.highchartTooltip(this, this.options.tooltip);`

But I am getting the error: "Cannot use 'new' with an expression whose type lacks a call or construct signature"... so i don't know how to create a object to initialize the tooltip according the js example.

Also I can see the definition of tooltip in http://code.highcharts.com/highcharts.src.js

`var Tooltip = Highcharts.Tooltip = function () {
     this.init.apply(this, arguments);
  };
  Tooltip.prototype = {...`

is something missing on this definition file?

I am asking the same in stackoverflow but with no much help:
http://stackoverflow.com/questions/38188014/how-to-use-highcharts-tooltip-type-in-typescript.

Is this a issue? .. If it is an issue. is there some workaround ?

**Comment by hanssens** [comment]
I've just spend some time with updating the .d.ts file and came acroos this issue. In the .d.ts file, the tooltip is not defined as a seperate class but as an interface. Just as the [api docs mentiona](http://api.highcharts.com/highcharts/tooltip).

Which means, you're able to do the following instead:

    let tooltipOptions = <Highcharts.TooltipOptions> {
        // options here...
    };

    let chart = new Highcharts.Chart({
        tooltip: tooltipOptions
    });

@r0lan2 Late answer, I know. But does this help your case?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
