### ISSUE TITLE
@types/uglify-js includes /// <reference types="source-map" />

### ISSUE THREAD

**Issue by gdi2290** [DefinitelyTyped/DefinitelyTyped#9979]
@types/uglify-js currently has 
/// <reference types="source-map" />

workaround
https://github.com/gdi2290/types-uglify-js
"@types/uglify-js": "github:gdi2290/types-uglify-js",

**Comment by mhegazy** [comment]
This is expected, `@types/uglify-js` depends on `@types/source-map`. it is used to access `SourceMapGenerator`.

**Comment by mhegazy** [comment]
so do not see what is the problem here.

**Comment by gdi2290** [comment]
kool, thanks! `@types` makes ts a lot easier for new devs to get into
