### ISSUE TITLE
koa-bodyparser is missing a request.body

### ISSUE THREAD

**Issue by jeffijoe** [DefinitelyTyped/DefinitelyTyped#9992]
- [ ] I want to talk about `koa-bodyparser/koa-bodyparser.d.ts`.
  - The authors of that type definition are cc/ @hellopao @liushigit 

`ctx.request.body` needs to be typed.

```
import * as Koa from 'koa'

declare module 'koa' {
  interface Request {
    body?: any;
  }
}
```

Something like above.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by jeffijoe** [comment]
All I got is the type def above, don't know how to write tests.

**Comment by unhealthy** [comment]
+1, body is needed
Currently, I extend the Request interface by myself in my code

**Comment by pe8ter** [comment]
@jeffijoe This issue can be closed. See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/koa-bodyparser/index.d.ts.

**Comment by avindra** [comment]
Please close this issue. It has been fixed:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/koa-bodyparser/index.d.ts#L20-L22

**Comment by jeffijoe** [comment]
Great!

**Comment by aendrew** [comment]
I'm not sure this *is* resolved.

Instantiating both with:

```typescript
import * as koa from 'koa';
import koaBodyParser = require('koa-bodyparser');
const app = new Koa();
app.use(koaBodyParser())
```

... I get the following compiler failure:

```
TSError: ⨯ Unable to compile TypeScript
lib/index.ts (25,5): Object is possibly 'undefined'. (2532)
lib/index.ts (28,6): Argument of type '(ctx: Context, next?: (() => any) | undefined) => any' is not assignable to parameter of type '(ctx: Context, next: Function) => any'.
  Types of parameters 'next' and 'next' are incompatible.
    Type 'Function' is not assignable to type '(() => any) | undefined'.
      Type 'Function' is not assignable to type '() => any'.
        Type 'Function' provides no match for the signature '(): any'. (2345)
lib/index.ts (33,14): Argument of type 'string | 5555' is not assignable to parameter of type 'number'.
  Type 'string' is not assignable to type 'number'. (2345)
```
