### ISSUE TITLE
@types/cors can not find module '../serve-static'

### ISSUE THREAD

**Issue by yeiniel** [DefinitelyTyped/DefinitelyTyped#9995]
Once i installed @types/cors and try to compile my typescript code it fail with the message

`node_modules/@types/cors/node_modules/@types/express/index.d.ts(16,30): error TS2307: Cannot find module '../serve-static'.`

As you can see npm is placing the @types/express inside the @types/cors especific node_modules. This is because my code depend on a different version of @types/express that is placed on muy package node_modules folder. I know that this error is showing because @types/express peer-depend on @types/serve-static and i can solve it downgrading my own version of @types/express. But the root problem here is related with versions. I think @types/cors should depend on "@types/express": "^4.0.27-alpha" and not "@types/express": "4.0.27-alpha" which is the current dependency.

**Comment by mhegazy** [comment]
fixed in `@types/cors@0.0.28-alpha`

**Comment by yeiniel** [comment]
Thanks

you should know that the same problem is presenting with @types/compression

**Comment by mhegazy** [comment]
publishing one more round for the other packages.

**Comment by yeiniel** [comment]
Thanks.
